### ISSUE TITLE
Back-off pulling image "gcr.io/kubernetes-helm/tiller:v2.16.1"

### ISSUE THREAD

**Issue by RonZhang724** [helm/helm#10004]
We are using helm2 to install the applications. But since this morning, we started having issue installing the tiller due to ImagePullBackOff.

Seems like the tiller deployment is trying to pull from "gcr.io/kubernetes-helm/tiller:v2.16.1" but failed

I can't pull this image manually either:
```
docker pull gcr.io/kubernetes-helm/tiller:v2.16.1                                                                                                                               ronzhang@M-FVFZG1MSL413
v2.16.1: Pulling from kubernetes-helm/tiller
89d9c30c1d48: Downloading
5724ac4da768: Download complete
9a2e33016f21: Download complete
7d76178d79a8: Download complete
unknown blob
```

Any idea what might be happening?

**Comment by bacongobbler** [comment]
The correct image name is `ghcr.io/helm/tiller`, not `ghcr.io/kubernetes-helm/tiller`.

```
><> docker pull ghcr.io/helm/tiller:v2.16.1
v2.16.1: Pulling from helm/tiller
89d9c30c1d48: Pull complete 
5724ac4da768: Pull complete 
9a2e33016f21: Pull complete 
7d76178d79a8: Pull complete 
Digest: sha256:3c70ee359d3ec305ca469395a2481b2375d569c6b4a928389ca07d829d12ec51
Status: Downloaded newer image for ghcr.io/helm/tiller:v2.16.1
ghcr.io/helm/tiller:v2.16.1
...
```

Helm 2's support lifecycle ended on November 2020. As a result we are no longer providing support for any support tickets related to Helm 2. See [the blog post](https://helm.sh/blog/helm-2-becomes-unsupported/) for more details.

**Comment by heidemn-faro** [comment]
Remember: "Cool URIs don't change" ;-) 
https://www.w3.org/Provider/Style/URI

Not so nice if suddenly your Tiller pod cannot be started after replacing some Kubernetes nodes :-(

**Comment by wmessiassilva** [comment]
Problema:
Image do tiller
Imagem com problema: gcr.io/kubernetes-helm/tiller:v2.9.1
gcr.io/kubernetes-helm/tiller:v2.17.0 - em alguns casos essa imagem que estava
Imagem que resolveu o problema: ghcr.io/helm/tiller:v2.17.0

Cenário:
Tem um tiller deployado em cada um dos namespace listados aqui:

Captura de Tela 2022-11-01 às 16 55 51

Kubectl edit deploy e trocar a imagem do contêiner na mão.
Ou então executar esse comando:
kubectl set image deployment/tiller-deploy tiller=ghcr.io/helm/tiller:v2.17.0 -n namespace

Problema resolvido, faltando apenas testar um novo deploy no cluster GKE de dev da google cloud.
