### ISSUE TITLE
Potential enhancement for `helm create`: values.schema.json

### ISSUE THREAD

**Issue by kreempuff** [helm/helm#10009]
Currently `helm create` gives user a nice starting template to iterate on. Seeing as the `values.schema.json` is optional, does it make sense to have the `helm create` command create the schema file as well? Or is that too much friction?

**Comment by hickeyma** [comment]
@kreempuff We have tended to keep the scaffolding command to generate basic Helm chart artefacts which give a user the basic starting point. 

With that said, I think this is worth discussing at our next weekly meeting on Thursday. I will add it to the list. Thank you for raising.

**Comment by hickeyma** [comment]
@kreempuff This was discussed at the weekly meeting yesterday. It was decided that adding to the values file to the scaffold chart is adding complexity that is not required in a basic chart.

It was however agreed that we need to revisit the area of the scaffold chart, starter charts and chart best practises. I have raised proposal #10025 for Helm 4 so we can work on this.

I know this is not exactly what you are looking for now but hopefully we can improve this for Helm 4. If it's ok with you, you might close this issue in favour of #10025?

**Comment by kreempuff** [comment]
@hickeyma yeah that works for me!
