### ISSUE TITLE
Tiller can not be downloaded through storage.googleapis.com

### ISSUE THREAD

**Issue by hampuslidin** [helm/helm#10003]
I tried to download the tiller binary from https://storage.googleapis.com/kubernetes-helm/helm-v2.17.0-linux-amd64.tar.gz, but I am receiving an error that says:

```xml
<Error>
    <Code>AccessDenied</Code>
    <Message>Access denied.</Message>
    <Details>Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.</Details>
</Error>
```

Is the binary available from somewhere else? This affects Helm 2 and commands using tiller, for instance `helm tiller install`:

```
$ helm tiller install
Installed Helm version v2.17.0
Installing Tiller v2.17.0 ...
tar: This does not look like a tar archive

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Error: plugin "tiller" exited with error
```

**Comment by yxxhero** [comment]
@hampuslidin  please try use helm v3. thanks very much.

**Comment by hampuslidin** [comment]
@yxxhero Thank you for the fast response, but I was wondering if there was another way to get a hold of the binary. I understand that support for Helm v2 has ended, but any way to get that binary would help us in the mean time until we upgrade to Helm v3.

**Comment by beep-bop-cloud** [comment]
Same issue here.
`docker pull gcr.io/kubernetes-helm/tiller:v2.16.1`
`Error response from daemon: pull access denied for gcr.io/kubernetes-helm/tiller, repository does not exist or may require 'docker login': denied: Permission denied for "v2.16.9" from request "/v2/kubernetes-helm/tiller/manifests/v2.16.1".`
 is there a workaround until we get the time to upgrade to Helm v3 ?

**Comment by hampuslidin** [comment]
@beep-bop-cloud I have found out that Tiller docker images have moved to Docker Hub: https://hub.docker.com/r/helmpack/tiller/tags?page=1&ordering=last_updated

**Comment by yxxhero** [comment]
@hampuslidin  try this: https://get.helm.sh/helm-v2.17.0-linux-amd64.tar.gz

**Comment by beep-bop-cloud** [comment]
@hampuslidin thanks a lot, solved the issue for me !
`helm init --tiller-image helmpack/tiller:v2.16.9` works like a charm

**Comment by hampuslidin** [comment]
@yxxhero Awesome, that link works for me. And now the original link also seems to work, so I guess it was something temporary going wrong? Anyway, I think the issue can be closed. Thanks for the help!

**Comment by diclophis** [comment]
Is `helmpack/tiller` published from an official source, or is it a 3rd party?

**Comment by yxxhero** [comment]
it a 3rd party. @diclophis

**Comment by bacongobbler** [comment]
`helmpack/tiller` is an official image, published by helmbot.

https://github.com/helm/helm/blob/a690bad98af45b015bd3da1a41f6218b1a451dbe/.circleci/deploy.sh#L75-L77

**Comment by bacongobbler** [comment]
related tickets:

#10004 #10005

It appears today was the day that the Google cloud storage bucket as well as the google container registry were shut down.
