### ISSUE TITLE
Installation fails even when release is uninstalled with error "cannot re-use a name that is still in use"

### ISSUE THREAD

**Issue by vishal662** [helm/helm#10002]
I am calling Helm APIs to perform install and uninstall 

In my code i am calling helm Install API and if helm install fails calling uninstall to release the releasename.

Getting contradicting error msg:
**Error while install**:  cannot re-use a name that is still in use
**Error while uninstall**: uninstall: Release not loaded: kafka-zookeeper-two: release: not found

The difference which i see in helm client code is that while install **Query** is called which is present in Queryor structure and while uninstall **Get** is called which is also present in Queryor structure.

This issue is intermittent.

**Comment by bacongobbler** [comment]
@vishal662 do you have some sample code we can use to reproduce the issue? "cannot re-use a name that is still in use" usually indicates a release secret is present in the namespace you wish to install, while the uninstall message implies no release record was found.

Usually this means one of two things

1. your kubernetes cluster is in an unhealthy state which you'll need to inspect. A "split-brained" etcd cluster that lost quorum is one possible fault
2. you're issuing requests against two different kubernetes contexts. In other words, you are attempting to install the release in one cluster, and attempting to delete the release in another.

Are you able to share more information about your setup?

**Comment by vishal662** [comment]
Below is the code which i am using.
Since i am using the same gin context to install and uninstall, so i don't this its possible that install is happening on one cluster and uninstall on other.

`func returnActionConfig(ctx *gin.Context) (*SaveFilePath, *action.Configuration) {
	response := SaveFilePath{}
	InfoLogger.Println("Inside returnActionConfig")

	kubeConfigFile, err := ctx.FormFile("kubeconfig")
	if err != nil {
		ErrorLogger.Println("get form err for kubeconfig file: ", err.Error())
		response.Detail = "get form err for kubeconfig file: " + err.Error()
		response.Status = http.StatusBadRequest
		return &response, nil
	}

	kubeConfigPath := filepath.Base(kubeConfigFile.Filename)
	if err := ctx.SaveUploadedFile(kubeConfigFile, kubeConfigPath); err != nil {
		ErrorLogger.Println("upload file err for kubeconfig file: ", err.Error())
		response.Detail = "upload file err for kubeconfig file: " + err.Error()
		response.Status = http.StatusInternalServerError
		return &response, nil
	}

	releaseNamespace := ctx.Request.FormValue("releasenamespace")

	actionConfig := new(action.Configuration)
	if err := actionConfig.Init(kube.GetConfig(kubeConfigPath, "", releaseNamespace), releaseNamespace, os.Getenv("HELM_DRIVER"), func(format string, v ...interface{}) {
		str := fmt.Sprintf(format, v)
		InfoLogger.Println(str)
	}); err != nil {
		ErrorLogger.Println("Initialization of action configuration failed: ", err.Error())
		response.Detail = "Initialization of action configuration failed: " + err.Error()
		response.Status = http.StatusInternalServerError
		return &response, nil
	}

	response.Status = http.StatusOK
	response.KubeConfigPath = kubeConfigPath
	return &response, actionConfig
}

//ChartInstallFromRepo ...
func (services helmInstallService) ChartInstallFromRepo(ctx *gin.Context) {

	repoUpdateErr := repoUpdate()
	if repoUpdateErr != nil {
		ErrorLogger.Println("Repo Update Error: ", repoUpdateErr)
	}
	response := InstallOrUpgradeResponse{}

	var err error
	var release *release.Release
	var valueExtPath string

	saveFileResp, actionConfig := returnActionConfig(ctx)
	if saveFileResp.Status != http.StatusOK {
		ErrorLogger.Println("ChartInstallFromRepo: ", saveFileResp.Detail)
		response.Status = saveFileResp.Status
		response.Detail = saveFileResp.Detail
		ctx.JSON(http.StatusOK, response)
		return
	}

	valueExtFile, valueExtErr := ctx.FormFile("valueExt")
	if valueExtErr != nil {
		ErrorLogger.Println("get form err for valuesExt file: ", valueExtErr.Error())
	} else {
		valueExtPath = filepath.Base(valueExtFile.Filename)
		if err := ctx.SaveUploadedFile(valueExtFile, valueExtPath); err != nil {
			ErrorLogger.Println("upload file err for valueExt file:", err.Error())
			response.Detail = "upload file err for valueExt file:" + err.Error()
			response.Status = http.StatusInternalServerError
			ctx.JSON(http.StatusOK, response)
			return
		}
	}
	InfoLogger.Println("Values Ext File: ", valueExtFile)
	client := action.NewInstall(actionConfig)

	if client.Version == "" && client.Devel {
		client.Version = ">0.0.0-0"
	}
	client.ReleaseName = ctx.Request.FormValue("releasename")
	client.ChartPathOptions.Version = ctx.Request.FormValue("chartversion")
	repo := ctx.Request.FormValue("reponame")
	chart := ctx.Request.FormValue("chartname")
	cp, err := client.ChartPathOptions.LocateChart(fmt.Sprintf("%s/%s", repo, chart), setting)
	if err != nil {
		ErrorLogger.Println("Locating chart failed: ", err.Error())
		response.Detail = "Locating chart failed: " + err.Error()
		response.Status = http.StatusBadRequest
		ctx.JSON(http.StatusOK, response)
		removeFile(valueExtPath)
		return
	}

	p := getter.All(setting)
	// valueOpts := &values.Options{}
	// vals, err := valueOpts.MergeValues(p)
	// if err != nil {
	// 	log.Fatal(err)
	// }

	// Check chart dependencies to make sure all are present in /charts
	chartRequested, err := loader.Load(cp)
	if err != nil {
		ErrorLogger.Println("Loading chart failed: ", err.Error())
		response.Detail = "Loading chart failed: " + err.Error()
		response.Status = http.StatusInternalServerError
		ctx.JSON(http.StatusOK, response)
		removeFile(valueExtPath)
		return
	}

	// validInstallableChart, err := isChartInstallable(chartRequested)
	// if !validInstallableChart {
	// 	log.Fatal(err)
	// }

	if req := chartRequested.Metadata.Dependencies; req != nil {
		// If CheckDependencies returns an error, we have unfulfilled dependencies.
		// As of Helm 2.4.0, this is treated as a stopping condition:
		// https://github.com/helm/helm/issues/2209
		if err := action.CheckDependencies(chartRequested, req); err != nil {
			if client.DependencyUpdate {
				man := &downloader.Manager{
					Out:              os.Stdout,
					ChartPath:        cp,
					Keyring:          client.ChartPathOptions.Keyring,
					SkipUpdate:       false,
					Getters:          p,
					RepositoryConfig: setting.RepositoryConfig,
					RepositoryCache:  setting.RepositoryCache,
				}
				if err := man.Update(); err != nil {
					ErrorLogger.Println("updating local chart dir failed: ", err.Error())
					response.Detail = "updating local chart dir failed: " + err.Error()
					response.Status = http.StatusInternalServerError
					ctx.JSON(http.StatusOK, response)
					removeFile(valueExtPath)
					return
				}
			} else {
				InfoLogger.Println("Dependency Update failed: ", err.Error())
				response.Detail = "Dependency Update failed: " + err.Error()
				response.Status = http.StatusInternalServerError
				ctx.JSON(http.StatusOK, response)
				removeFile(valueExtPath)
				return
			}
		}
	}

	client.Namespace = ctx.Request.FormValue("releasenamespace")

	if valueExtErr == nil {
		var vals map[string]interface{}
		vals, err = chartutil.ReadValuesFile(valueExtPath)
		release, err = client.Run(chartRequested, vals)
	} else {
		release, err = client.Run(chartRequested, nil)
	}
	if err != nil {
		ErrorLogger.Println("Helm installtion failed: ", err.Error())
		response.Detail = "Helm installtion failed: " + err.Error()
		response.Status = http.StatusInternalServerError
		//uninstall chart to free release name
		ChartUninstallSvc(ctx)
		ctx.JSON(http.StatusOK, response)
		removeFile(valueExtPath)
		return
	}
	InfoLogger.Println(release.Manifest)
	InfoLogger.Println("Helm installation successful")
	response.Detail = "Helm installation successful"
	response.Status = http.StatusOK
	response.RevisionNumber = release.Version
	response.AppVersion = release.Chart.AppVersion()
	response.ChartName = release.Chart.Name() + "-" + release.Chart.Metadata.Version
	response.Description = release.Info.Description
	response.RevisionNumber = release.Version
	response.UpdatedTime = release.Info.LastDeployed.String()
	response.DeployStatus = release.Info.Status.String()
	removeFile(valueExtPath)
	ctx.JSON(http.StatusOK, response)
}

func ChartUninstallSvc(ctx *gin.Context) *Response {
	response := Response{}
	saveFileResp, actionConfig := returnActionConfig(ctx)
	if saveFileResp.Status != http.StatusOK {
		ErrorLogger.Println("ChartUnInstall : ", saveFileResp.Detail)
		response.Status = saveFileResp.Status
		response.Detail = saveFileResp.Detail
		return &response
	}

	releaseName := ctx.Request.FormValue("releasename")

	chartUninstall := action.NewUninstall(actionConfig)
	releaseresp, err := chartUninstall.Run(releaseName)

	if err != nil {
		ErrorLogger.Println("ChartUninstall Error: ", err.Error())
		response.Status = http.StatusInternalServerError
		response.Detail = err.Error()
		return &response
	}

	InfoLogger.Println("ChartUninstall successful for release Name: ", releaseName)

	InfoLogger.Println("ChartUninstall Info: ", releaseresp.Release.Info)
	response.Status = http.StatusOK
	response.Detail = "Chart Uninstall successful for release Name: " + releaseName
	return &response
}`

**Comment by mattfarina** [comment]
I noticed you're not logging the details inside the actions. When you initialize the actionconfig you're not using a real logger. I see the line...

```
if err := actionConfig.Init(kube.GetConfig(kubeConfigPath, "", releaseNamespace), releaseNamespace, os.Getenv("HELM_DRIVER"), func(format string, v ...interface{}) {
```

The last argument to `Init` is a logger. You can [see the signature for `Init` here](https://github.com/helm/helm/blob/efe2638f87b597403f34009e1029a6f0b44db8f2/pkg/action/action.go#L365). More details on the `Configuration` object are [here](https://github.com/helm/helm/blob/efe2638f87b597403f34009e1029a6f0b44db8f2/pkg/action/action.go#L81-L98).

This logger is used to [log when the release record is removed](https://github.com/helm/helm/blob/efe2638f87b597403f34009e1029a6f0b44db8f2/pkg/action/uninstall.go#L133-L146). I'm wondering if that's happening.

**Comment by vishal662** [comment]
@mattfarina , Thanks for pointing it out. I will add the logger.  
But the removal of release is verified with the chartuninstall function called after chartinstall func where the output says "Release not loaded". 
Is anything else missed here betweeen chartinstall and chartuninstall?

**Comment by mattfarina** [comment]
If you're getting a "Release not loaded" message it means it did not find it.

Both uninstall and the part of install that checks for an existing release name use the same underlying functionality.

I'm not sure what's going on but I am curious if there is a caching issue somewhere.

**Comment by vishal662** [comment]
@mattfarina , Which all caches helm maintains for release names? Also when and how much time it takes to get removed?

**Comment by vishal662** [comment]
Please let me know if anything else can be checked for this issue.

**Comment by tekumara** [comment]
Check you are using the correct namespace.

eg:
```
helm list --namespace my-app
```
