### ISSUE TITLE
`helm test` fails with an active `--filter` and `--logs`

### ISSUE THREAD

**Issue by djmcgreal-cc** [helm/helm#10018]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"dirty", GoVersion:"go1.16.5"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
* GKE
* docker-desktop
* MicroK8s

Seemingly one can't use `helm test` with both `--filter` and `--logs` arguments. If you filter down the tests which are run and want the logs, the command tries to access the logs of pods that were never created. For example:
```
helm test sc --filter name=sc-configuration-test --logs
NAME: sc
LAST DEPLOYED: Wed Aug 11 10:43:41 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE:     sc-configuration-test
Last Started:   Wed Aug 11 12:57:27 2021
Last Completed: Wed Aug 11 13:00:39 2021
Phase:          Succeeded

Error: unable to get pod logs for sc-apm-test: pods "sc-apm-test" not found
```

**Comment by mattfarina** [comment]
Looking inside [the function that gets the logs,](https://github.com/helm/helm/blob/efe2638f87b597403f34009e1029a6f0b44db8f2/pkg/action/release_testing.go#L104) there is no accounting for filtering. That would cause this.

**Comment by hatati** [comment]
Unstale

**Comment by hatati** [comment]
Let me try and see if I can do something about this.

**Comment by hatati** [comment]
A PR has been created https://github.com/helm/helm/pull/10516

**Comment by hatati** [comment]
Unstale

**Comment by hatati** [comment]
Hi @mattfarina 
Can this issue be opened up again?

**Comment by Laurianti** [comment]
Is there any update?
