### ISSUE TITLE
.Release.Namespace renders empty when chart installed over Helm SDK

### ISSUE THREAD

**Issue by Langohr23** [helm/helm#10019]
Hello,

I am currently installing Helm Charts via the helm sdk. It worked quite flawless until I started to use namespaces. (e.g. https://github.com/helm/helm/issues/8780)

Now i used the variabel {{ .Release.Namespace }} in one of the templates but it is always rendered empty (""). Any ideas how to fix it? 

Helm-SDK Version: 3.5.4

Kubernetes Distribution: k3s

**Comment by bacongobbler** [comment]
Did you set the `Install` action's Namespace field?

https://github.com/helm/helm/blob/efe2638f87b597403f34009e1029a6f0b44db8f2/pkg/action/install.go#L85

**Comment by bacongobbler** [comment]
see https://github.com/helm/helm/pull/10230
