### ISSUE TITLE
Allow `helm repo list` to not error when there are no repositories

### ISSUE THREAD

**Issue by akshaymankar** [helm/helm#10028]
If I run `helm repo list` and there are no repositories, it exits with status 1 and prints this error:

```
Error: no repositories to show
```

It would be nice if it accepted another parameter, say `--allow-empty`, to signal that it is ok to not have any repositories to show. When `-o json` or `-o yaml` is specified, this could result in an empty array.

Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.2", GitCommit:"", GitTreeState:"", GoVersion:"go1.16"}
```

**Comment by ericpromislow** [comment]
I just ran into this. This is a bug in the same sense that doing `ls DIR` on an empty existing directory DIR should return a non-zero status. In most cases there's nothing wrong for a container-like thing to report that it contains zero items.
