### ISSUE TITLE
Specifying in-chart values files

### ISSUE THREAD

**Issue by jarojasm95** [helm/helm#10022]
Hello - I'd like to propose allowing helm to install a chart and use a values file that is inside the chart. Example:
```
 |-- my-chart
 |   |-- Chart.yaml
 |   |-- values.yaml
 |   |-- templates
 |   |-- | ... # helm templates
 |   |-- values
 |   |-- | integration.values.yaml
 |   |-- | production.values.yaml
 |   |-- | ... # other values files
```
If the above chart is *not* packaged (local chart) then one can specify `--values my-chart/values/integration.values.yaml` - but if the chart is in a remote location or packaged then this is not possible without first pulling and extracting the chart.

I think adding this functionality would benefit public and private helm charts for scenarios where the chart maintainer/creator wants to provide the chart users "values files" for specific use-cases (such as different environments, different cloud providers, etc). 

Possible solutions:
- add support for a `chart://` prefix to values files that exist within the chart - this means users still use the `--values` option but need a specific syntax. Example: `helm install my-chart my-chart-0.1.1.tgz -f chart://values/integration.values.yaml`
- add a new cli option (maybe `--chart-values`) where the parameter is the values files which *must* exist within the chart. Example: `helm install my-chart my-chart-0.1.1.tgz --chart-values values/integration.values.yaml`

Is this a reasonable feature? I'd be open to contributing a PR to this

**Comment by mattfarina** [comment]
@jarojasm95 Thanks for the suggestion. We have a [Helm Improvement Proposal](https://github.com/helm/community/tree/main/hips) process and it might be good to have this go through that.
