### ISSUE TITLE
helm upgrade recreates pods even if deployments spec.template did not change 

### ISSUE THREAD

**Issue by hevemula** [helm/helm#10021]
looking for help to understand the behavior of helm upgrade.

I have a chart that has the following structure 

├── Chart.yaml
├── Jenkinsfile
├── README.md
├── charts
├── templates
│   ├── NOTES.txt
│   ├── _helpers.tpl
│   ├── deployment.yaml
│   ├── ingress.yml
│   ├── service.yaml
│   └── tests
└── values.yaml

my `spec.replicas` in my `deployment` value is templatized as below

  `replicas: {{ .Values.microservice.replicas }}`

let's assume when helm install was done the value of microservice.replicas is 3

when I do a `helm upgrade <releaseName> <chart> --reuse-values --set microservice.replicas=5 `

my  expectation was that it will add 2 more pods ie scale my deployment
but in reality, it creates 5 new pods and terminates the 3 pods that were created as part of helm install ie a rollout of the deployment

my understanding is that from [ref](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#updating-a-deployment)

_A Deployment's rollout is triggered if and only if the Deployment's pod template (that is, .spec.template) is changed, for example, if the labels or container images of the template are updated. Other updates, such as scaling the Deployment, do not trigger a rollout._

Output of `helm version`:
`version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"dirty", GoVersion:"go1.16.4"}`

Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.11", GitCommit:"c18ff7bd5227b42c617cf371cf315d0423e91d5e", GitTreeState:"clean", BuildDate:"2021-05-25T17:38:04Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
`AKS`

**Comment by bacongobbler** [comment]
What you are describing is all Kubernetes business logic. Helm simply renders the templates and sends them to Kubernetes as an update through their API. The behaviour that occurs when replicas change from 3 to 5 is up to Kubernetes.

**Comment by bacongobbler** [comment]
Here is the extent of helm’s interaction with the Kubernetes API: https://github.com/helm/helm/blob/main/pkg/kube/client.go#L501

**Comment by mattfarina** [comment]
@hevemula Helm sends the manifests to Kubernetes and it works them out from there. In this case, a deployment creates a replicaset which creates and manages pods. When a change is made to the template a new replicaset is created and pods are moved or otherwise managed by Kubernetes. This all happens in Kubernetes controllers and Helm (or other tools) don't do the management. [You can find more details in the Kuberentes docs here](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment).
