### ISSUE TITLE
Multiple dependencies and the same alias result in the same resource name

### ISSUE THREAD

**Issue by slm940208** [helm/helm#10037]
name: chartA
dependencies:
  - name: chartB
    alias: aaa
---
name: chartB
dependencies:
  - name: chartC
    alias: aaa

If both chartA and chartB contain a service, the name will be the same service name testname-aaa after rendering.

helm install testname chartA, chartB will create service testname-aaa, chartC also willl create service testname-aaa.

now, don't deal with this situation?

**Comment by bacongobbler** [comment]
I'm not sure how you can solve this unless both of your service names use a slightly more unique name.

Can you please provide more information? What are you attempting to achieve with this example?

**Comment by R-omk** [comment]
> What are you attempting to achieve with this example?

it looks like the author of the issue wanted to reuse the same value for both charts.
But for this purpose YAML anchors can be used.

I believe that in such a situation there should be a conflict error, or at least a warning.
