### ISSUE TITLE
How to check the parameters of the charts that have been deployed?

### ISSUE THREAD

**Issue by wajika** [helm/helm#10031]
Others deployed a chart and now I want to upgrade it.

But I got an error when I executed helm upgrade
"spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden"

I did a test. If I upgrade a chart that uses the same parameters, it works.
I guess the parameters of the chart are not the same as what I used.

Is there any way to output the parameters of the chart?

```
helm install redis \
bitnami/redis \
--set master.persistence.storageClass=nas \
--set master.persistence.size=8Gi \
--set volumePermissions.enabled=true
```
For example, if redis is deployed, I need to know the following three parameters:
```
master.persistence.storageClass=nas 
master.persistence.size=8Gi 
volumePermissions.enabled=true
```

**Comment by mattfarina** [comment]
The issue you're encountering has to do with the generated Kubernetes manifests. The generated manifests from the newer version of the chart you are using is attempting to change fields that cannot be changed. The chart may have made a breaking change at some point and changed a property that cannot be changed in a deployed resource.

**Comment by wajika** [comment]
> The issue you're encountering has to do with the generated Kubernetes manifests. The generated manifests from the newer version of the chart you are using is attempting to change fields that cannot be changed. The chart may have made a breaking change at some point and changed a property that cannot be changed in a deployed resource.

In fact, I just want to add a parameter to the chart.

example:

Others deployed a dapr
```
helm upgrade dapr xxx/xxx \
--namespace dapr-system \
--wait
```

Then I found that I need to add a parameter

```
helm upgrade dapr dapr/dapr \
--namespace dapr-system \
--set global.logAsJson=true \
--wait
```
But this will prompt an error, because the "chart hub" is different, which means that the image is different. According to the characteristics of K8S, statefulset can only change the three fields of'replicas','template', and'updateStrategy', or can we consider adding a switch that ignores the "chart hub" address?

**Comment by wajika** [comment]
Hope that more people will participate in the discussion and provide interesting methods.
