### ISSUE TITLE
Create CR and CRD from the same helm chart

### ISSUE THREAD

**Issue by rapatchi** [helm/helm#10030]
We have a scenario where we wanted to create both CRD and one CR resource of that CRD in  the same helm chart.

We tried using the CRD folder approach as suggested in the documentation. But we won't be able to support upgrade scenario of existing charts because of this limitation: https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations
 
 So we tried the following:
Install CRD as pre-install hook and try installing the CR as a normal template. But we are getting the following error:

PS C:\Users\rapatchi\Desktop\chart> helm install azure-arc .\azure-arc-k8sagents-0.1.4002-private\azure-arc-k8sagents\ -f userValues.txt --atomic --timeout 5m0s --debug
install.go:173: [debug] Original chart version: ""
install.go:190: [debug] CHART PATH: C:\Users\rapatchi\Desktop\chart\azure-arc-k8sagents-0.1.4002-private\azure-arc-k8sagents

Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "ClusterConnectCertificate" in version "clusterconfig.azure.com/v1beta1"
helm.go:81: [debug] unable to recognize "": no matches for kind "ClusterConnectCertificate" in version "clusterconfig.azure.com/v1beta1"
unable to build kubernetes objects from release manifest
helm.sh/helm/v3/pkg/action.(*Install).Run
        /home/circleci/helm.sh/helm/pkg/action/install.go:258
main.runInstall
        /home/circleci/helm.sh/helm/cmd/helm/install.go:242
main.newInstallCmd.func2
        /home/circleci/helm.sh/helm/cmd/helm/install.go:120
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:80
runtime.main
        /usr/local/go/src/runtime/proc.go:204
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1374
        
Could you suggest us the correct way to handle this scenario ?.

Output of `helm version`:
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"e1d093448d0ed9b9b1a48f49833ff1ee64c05ba5", GitTreeState:"clean", BuildDate:"2021-06-03T00:20:57Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AKS

**Comment by mattfarina** [comment]
If you're looking at CRDs, upgrades, and changes I would suggest reading [the context around CRD handling in Helm](https://github.com/helm/community/blob/main/hips/hip-0011.md). There is a great deal of information on how Kubernetes handles CRDs and problematic situations you may end up in.

The issue you're seeing is that manifests for everything are built before the hooks are run. This is needed to that helm has the hook manifests to run. In doing this, Helm (Kubernetes packages really) will see that some of the built manifests are not valid for this cluster. That will cause an error.

I'm not sure of a nice way around it, off hand. Have you considered installing the CRDs via a second chart. This is the alternative method in the Helm docs.
