### ISSUE TITLE
tpl fuction useage

### ISSUE THREAD

**Issue by egoisz** [helm/helm#10035]
values.yaml
```
  otherServer:
    uama-server-config: {
      env: {
        config: "--spring.config.location=classpath:bootstrap.yml,file://{{ .backendConfigDir }}/application-dynamicRoutes.yml,file:///data/apply/config/nprod/middleware.properties",
        }
      }
defaultConfig:
  backendConfigDir: "/data/apply/config/nprod"
```
_helpers.tpl
```
{{- define "deploymentEnv" -}}
{{- $default := .default -}}
{{- $custom := .custom -}}
env:
 {{- range $key, $value := .custom.env }}
- name: {{ $key }}
 {{- if regexMatch "{{ .* }}" $value -}}
  value: {{ tpl $value $default  }}
 {{- else -}}
  value: {{ $value | quote }}
 {{- end -}}
 {{- end }}
{{- end }}
```
run helm template return
```
Error: template: /templates/otherserver-deploy-template.yaml:35:12: executing "uama-deploy/templates/otherserver-deploy-template.yaml" at <include "deploymentEnv" .>: error calling include: template: uama-deploy/templates/_helpers.tpl:44:12: executing "deploymentEnv" at <tpl $value $default>: error calling tpl: cannot retrieve Template.Basepath from values inside tpl function: --spring.config.location=classpath:bootstrap.yml,file://{{ .default.backendConfigDir }}/application-dynamicRoutes.yml,file:///data/apply/config/nprod/middleware.properties: "BasePath" is not a value
```
how can i use tpl fuction to achieve {{ .default.backendConfigDir }} ---> /data/apply/config/nprod

Output of `helm version`:
version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by bacongobbler** [comment]
Hi @egoisz. Does the documentation help provide some answers for you?

https://helm.sh/docs/howto/charts_tips_and_tricks/#using-the-tpl-function

Let us know if you run into further issues.

**Comment by yxxhero** [comment]
Please show where used the `deploymentEnv`. @egoisz  Thanks very much.

**Comment by egoisz** [comment]
> Please show where used the `deploymentEnv`. @egoisz Thanks very much.
I simplified the actual usage like this:
values.yaml
```
name: HY
template: "I am {{ .name }} !"
```

test.yaml
```
text: {{ tpl .Values.template .Values }}
```

helm template return:

Error: template: uama-deploy/templates/test:1:9: executing "uama-deploy/templates/test" at <tpl .Values.template .Values>: error calling tpl: cannot retrieve Template.Basepath from values inside tpl function: I am {{ .name }} !: "BasePath" is not a value
helm.go:81: [debug] template: uama-deploy/templates/test:1:9: executing "uama-deploy/templates/test" at <tpl .Values.template .Values>: error calling tpl: cannot retrieve Template.Basepath from values inside tpl function: I am {{ .name }} !: "BasePath" is not a value

I can work ok like this :
values.yaml
```
name: HY
template: "I am {{ .Values.name }} !"
```
test.yaml
```
text: {{ tpl .Values.template . }}
```

I prefer to use the former method，
Does helm support the use of the former？
The second argument to the tpl function must be a top-level scope ?

**Comment by yxxhero** [comment]
@egoisz form the source code. The second argument to the tpl function must be a top-level scope.

**Comment by egoisz** [comment]
> @egoisz form the source code. The second argument to the tpl function must be a top-level scope.

Thank you for your explanation
