### ISSUE TITLE
http2: client connection lost

### ISSUE THREAD

**Issue by xor222xor** [helm/helm#10049]
Hello, 
I'm trying to run helm in a gitlab runner container of the same cluster and I get an error:

``` helm upgrade --debug -n kk-test keycloak ./chart/keycloak-11.0.0.tgz -f ./chart/values.yaml```
```
upgrade.go:123: [debug] preparing upgrade for keycloak
upgrade.go:131: [debug] performing update for keycloak
upgrade.go:303: [debug] creating upgraded release for keycloak
Error: UPGRADE FAILED: create: failed to create: Post "https://10.10.10.3:6443/api/v1/namespaces/kk-test/secrets": http2: client connection lost
helm.go:81: [debug] Post "https://10.10.10.3:6443/api/v1/namespaces/kk-test/secrets": http2: client connection lost
create: failed to create
helm.sh/helm/v3/pkg/storage/driver.(*Secrets).Create
	/home/circleci/helm.sh/helm/pkg/storage/driver/secrets.go:164
helm.sh/helm/v3/pkg/storage.(*Storage).Create
	/home/circleci/helm.sh/helm/pkg/storage/storage.go:66
helm.sh/helm/v3/pkg/action.(*Upgrade).performUpgrade
	/home/circleci/helm.sh/helm/pkg/action/upgrade.go:304
helm.sh/helm/v3/pkg/action.(*Upgrade).Run
	/home/circleci/helm.sh/helm/pkg/action/upgrade.go:132
main.newUpgradeCmd.func2
	/home/circleci/helm.sh/helm/cmd/helm/upgrade.go:155
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:80
runtime.main
	/usr/local/go/src/runtime/proc.go:204
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374
UPGRADE FAILED
main.newUpgradeCmd.func2
	/home/circleci/helm.sh/helm/cmd/helm/upgrade.go:157
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:80
runtime.main
	/usr/local/go/src/runtime/proc.go:204
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374
```

Although it works without errors:
`helm ls -A --all`

Also I can execute the command in pods:
`curl -k https://10.10.10.3:6443/api/v1/namespaces/kk-test/secrets`

helm version 3.6.3
kubernetes 1.16

Thanks for any help

**Comment by bacongobbler** [comment]
The error would indicate that helm lost its connection to Kubernetes. Port 6443 is typically where your Kubernetes API server is listening by default.

I would try to troubleshoot your connection status following the Kubernetes troubleshooting guide.

https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/

**Comment by Pictor13** [comment]
Maybe there was some maintenance while the deployment was running and connection was lost. 

The upgrade should still be there, in *pending-upgrade* state; check the status with `helm history` and eventually fix with `helm rollback`.

**Comment by jza0330** [comment]
Exactly same problem is happening to me. 
The symptom is, this is only happens when I access k8s cluster remotely via VPN.
When I'm in house there are no problems...

**Comment by ricardo-passos** [comment]
@jza0330 how did you manage to get to that number `1392`? I'm curious because your comment has helped me to solve the very same problem you were facing

**Comment by jza0330** [comment]
> @jza0330 how did you manage to get to that number `1392`? I'm curious because your comment has helped me to solve the very same problem you were facing

It's mtu of VPN interface. So to find this out you have to do ifconfig | grep mtu  or some similar command. Depends on OS

**Comment by itd-fsc** [comment]
I also suddenly had the issue that I could no longer connect to the cluster while using the VPN.
Reboot, VPN restart, and MTU setting all did not help.

But disabling and re-enabling the VPN `tun0` interface fixed everything:
```
sudo ifconfig tun0 down
sudo ifconfig tun0 up
```

**Comment by pancak3** [comment]
> [@jza0330](https://github.com/jza0330) how did you manage to get to that number `1392`? I'm curious because your comment has helped me to solve the very same problem you were facing

@ricardoo-cavalheiro  I think you can refer to the MTU value of the interface that works properly. 

> Exactly same problem is happening to me. The symptom is, this is only happens when I access k8s cluster remotely via VPN. When I'm in house there are no problems...
> 
> and the solution was to change MTU of network interface I use in WSL linux to the value of MTU of VPN interface on windows. `sudo ifconfig eth0 mtu 1392 up`

jza mentioned that in house it works, so they may checked the wifi or wired interface and used the mtu value there. This is my guess though. I used `sudo ip link set dev tailscale0 mtu 1420 up` as I noticed the container network interfaces use `1420` by default.
