### ISSUE TITLE
Which one would be the 'final one' apply to k8s when define duplicate resources?

### ISSUE THREAD

**Issue by anurnomeru** [helm/helm#10045]
We found that when define duplicate resources on chart or sub chart,  each resourceinfo will created, and the back resource will cover the front resource, how does helm control the order of these resources?

Can I get a clear order before 'helm install'?

**Comment by bacongobbler** [comment]
https://github.com/helm/helm/blob/29da1b94e9e5e7ac800e5a43b0f4dafbe2e89d70/pkg/releaseutil/manifest_sorter.go#L69-L78

**Comment by anurnomeru** [comment]
> https://github.com/helm/helm/blob/29da1b94e9e5e7ac800e5a43b0f4dafbe2e89d70/pkg/releaseutil/manifest_sorter.go#L69-L78

Thanks!
