### ISSUE TITLE
Helm lint not able to expand aliases

### ISSUE THREAD

**Issue by Klapeyron** [helm/helm#10050]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"ac26f1b96417683d8d13ed3c38bffdfe2ebd5520", GitTreeState:"clean", BuildDate:"2021-03-10T23:38:06Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.):  
`AKS`

It seems like there is some issue with `helm lint`, which is unable to check if mandatory parameters are set or not, when dependency has an alias. Please see below step-by-step minimal example:

Let's create 2 packages `foo` and `bar` and make `foo` a dependency in `bar`. In the same time, we will alias `foo` as `foo-aliased` in `bar`. 

```sh
$ helm create foo
$ helm create bar
$ cat -<<EOF >> bar/Chart.yaml 
dependencies:
- name: foo
  repository: file://../foo
  alias: foo-aliased
  version: 0.1.0
EOF
```

Now let's add some schema for package `foo`, so we will require following syntax:

```yaml
foo:
  test:
    loglevel: "info"
```

```sh
cat -<<EOF >> foo/values.schema.json
{
    "$schema": "https://json-schema.org/draft-07/schema#",
    "title": "Test schema",
    "type": "object",
    "required": [
        "test"
    ],
    "properties": {
        "test": {
            "description": "Some test properties",
            "type": "object",
            "required": [
                "loglevel"
            ],
            "properties": {
                "loglevel": {
                    "type": "string",
                    "enum": [
                        "debug",
                        "info",
                        "warn",
                        "error"
                    ]
                }
            }
        }
    }
}
EOF
```

If we will `helm lint` package `foo`, then we will see that it is not providing mandatory fields in `values.yaml`, so we should provide them in package `bar` (which is fine).

```sh
$ helm lint foo
==> Linting foo
[INFO] Chart.yaml: icon is recommended
[ERROR] values.yaml: - (root): test is required

[ERROR] templates/: values don't meet the specifications of the schema(s) in the following chart(s):
foo:
- (root): test is required


Error: 1 chart(s) linted, 1 chart(s) failed
```

If we will try to build and lint `bar`, we will see that mandatory parameters are missing:

```sh
$ helm template bar/ --dependency-update
Error: values don't meet the specifications of the schema(s) in the following chart(s):
foo-aliased:
- (root): test is required
```
```sh
$ helm lint bar/
==> Linting bar/
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: values don't meet the specifications of the schema(s) in the following chart(s):
foo:
- (root): test is required


Error: 1 chart(s) linted, 1 chart(s) failed
```

But both commands see different errors.

* Helm template is expecting `foo-aliased` to be set (seems correct)
* Helm lint is expecting `foo` to be set (seems incorrect)

If we will add mandatory parameter to `bar`:

```sh
$ cat -<<EOF >> bar/values.yaml
foo-aliased:
  test:
    loglevel: "info"
EOF
```

We will see that `helm template` will work as expected, but `helm lint` will still see an issue as above.

**Comment by whyando** [comment]
I'd agree this is a bug. Helm lint seems to be ignoring the fact that an alias is set for the subchart, and omitting the values under the aliased path.
(Whether or not the values under the non-aliased path values should be included or not is another matter - in my opinion another bug)

**Comment by bacongobbler** [comment]
duplicate of https://github.com/helm/helm/issues/8659?
