### ISSUE TITLE
Unclear error with not escaped json as a value with --set-string

### ISSUE THREAD

**Issue by emil14** [helm/helm#10051]
I was trying to lint my helm files, the error was:

```
Error: failed parsing --set-string data: list must terminate with '}'
```

It wasn't easy at all to figure out what the heck linter wants from me because I did not want any lists in my values!

As it turns out one of the values was json and without proper escaping it looks like a list to helm. I dig into source code and found this - https://github.com/helm/helm/blob/a499b4b179307c267bdf3ec49b880e3dbd2a5591/pkg/strvals/parser.go#L369

It would be great if there will be the way to figure out the real issue without made user think about lists if there was no lists :)

**Comment by bacongobbler** [comment]
@emil14 can you please share an example? How would you suggest we improve this. PRs to improve the error message in specific cases are more than welcome.
