### ISSUE TITLE
Garbage collection of failed release revisions

### ISSUE THREAD

**Issue by hickeyma** [helm/helm#10070]
Failed release revisions can cause the max history limit to be exceeded because Helm needs a revision to succeed as a reference point for rollback. This can happen in an automated environment like CI/CD.

At the moment, users have to remove said failed revisions by deleting the Secret(s) from the cluster.  It would be nice to have capability to cleanup the failed revisions. The ask here is to implement it first as a [Helm plugin](https://helm.sh/docs/topics/plugins/) and then if the plugin is popular to integrate it into core functionality.

Idea germinated from @michaelkoro  in #10056

**Comment by isutton** [comment]
Hi @hickeyma,

I've created https://github.com/isutton/helm-janitor to provide a path to what you've mentioned in the description: it is a Helm plugin written in Go that could potentially serve as host for this cleanup procedure, perhaps having other cleanups available and, if needed and kept the separation of concerns, be imported to Helm if so desired.

Please take a look, and let me know what you think. Perhaps one important piece of knowledge missing that you could be helpful is what sort of predicates are we looking for to decide which artifacts must be removed from the cluster.
