### ISSUE TITLE
occasionally  helm instal  errorl:Unable to continue with install: could not get infotmation about the resource 

### ISSUE THREAD

**Issue by maoyangLiu** [helm/helm#10078]
Output of `helm version`: 3.3.4

Output of `kubectl version`: 1.20.10

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

When I test 50 concurrent helm install release, occasionally there will be the following error：

Unable to continue with install: could not get infotmation about the resource :deployments.apps "xxxx" is forbidden,User “system:serviceaccount:xxx” cannot get resource "deployment" in API group "apps"  in the namespace "xxxx"
I want to know if this is the cause of helm or k8s, and how to avoid it

**Comment by mattfarina** [comment]
A few things that might help.

First, You should be on Helm 3.5 or 3.6 if you're interacting with Kubernetes 1.20. You can see the [version support policy](https://helm.sh/docs/topics/version_skew/#supported-version-skew) for more details. This is derived from our use of Kubernetes packages and their support policies.

Second, if you add `--debug -v 10` to a command you'll get a lot more debug information that may show some details. The `--debug` provides more details from Helm while `-v 10` provides more verbose logging to the underlying Kubernetes packages. Some information may show up there.

**Comment by maoyangLiu** [comment]
This is a mistake of mine,I foud the reason  when I add  --debug -v 10. Thanks a lot
