### ISSUE TITLE
outdated packages

### ISSUE THREAD

**Issue by 030** [helm/helm#10080]
Output of `helm version`:

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

I ran trivy and there are some issues in the binary. Could you update the packages and release a newer version?

**Comment by hickeyma** [comment]
@030 Do you mind following the process in [Helm Security Process and Policy](https://github.com/helm/community/blob/main/SECURITY.md) and not raise any security issues in this queue?
