### ISSUE TITLE
Wrong cluster version detected (v1.20.0 when I'm running v1.21.2)

### ISSUE THREAD

**Issue by mhavelant** [helm/helm#10086]
Hi!

I have `kubeVersion: ^1.21.0` in my Chart.yaml, and I'm running a v1.21 cluster in AKS. When I run  `helm template`, I'd expect it to succeed, but instead I'm getting this error:

```text
Error: chart requires kubeVersion: ^1.21.0 which is incompatible with Kubernetes v1.20.0
helm.go:88: [debug] chart requires kubeVersion: ^1.21.0 which is incompatible with Kubernetes v1.20.0
```

The cluster was recently (2 weeks ago maybe) updated to v1.21 from v1.20, but Azure shows everything (master + workers) to be at 1.21 as expected and so does kubectl. Any tips what I could try (apart from setting kubeVersion to ^1.20.0)?

---

Output of `helm version`:
`version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}`
Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"bd9d9ae2719e67a582f48c5dc2f81e87fe1deb8a", GitTreeState:"clean", BuildDate:"2021-08-16T22:02:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

**Comment by bacongobbler** [comment]
The template command does not establish a connection with your cluster. It uses the internal kubernetes client version by default.

If you want it to establish a connection to fetch your cluster’s current capabilities, use the -validate flag.

**Comment by mhavelant** [comment]
Yep, that was it, thank you for the help!
