### ISSUE TITLE
Limitations to value files?

### ISSUE THREAD

**Issue by jverhounik** [helm/helm#10090]
Hey guys!

I was wondering whether you can help me out with this?

I have the following code within a "values.yaml" file:

```
logstashPipeline:
 
{{ $key := "pipeconf" }}
{{ printf "%s%s %s" $key ":" "|" | indent 2 }}
```
 

Now I expect the output to look something like this:

```
logstashPipeline:

  pipeconf: |
```

Unfortunately, I receive the following error message when running a "helm install --dry-run":

> helm install logstash . --dry-run -f ../../values/logstash.yaml
> Error: failed to parse ../../values/logstash.yaml: error converting YAML to JSON: yaml: line 38: could not find expected ':'

I also made sure to add a value to the key (pipeconf) but without success...

I am trying to generate this within a "values.yaml" file. When I do the same within a template file, let's say a configmap.yaml and add a value to the key like this:

```
data:
{{ $key := "pipeconf" }}
{{ printf "%s%s %s" $key ":" "|" | indent 2 }}
      input {
        kafka {
          id => "input_kafka_monitoring"
          bootstrap_servers => "${KAFKA_BOOTSTRAP_SERVERS}"
          topics_pattern => [
            "monitoring.*"
          ]
          codec => "json"
        }
      }
```

It will workout just fine:

```
data:

  pipeconf: |
      input {
        kafka {
          id => "input_kafka_monitoring"
          bootstrap_servers => "${KAFKA_BOOTSTRAP_SERVERS}"
          topics_pattern => [
            "monitoring.*"
          ]
          codec => "json"
        }
      }
```

I was wondering if I made any mistakes, could it be the indentation or are there limitations to what you can do within a values.yaml file?

_If you guys need any files or info in general I am more than willing to provide you the needed info!_

Output of `helm version`: version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Minikube

**Comment by mattfarina** [comment]
I can see where the confusion can happen. _values.yaml_ files cannot have templates in them.

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!

**Comment by jverhounik** [comment]
I've been able to find a workaround for my initial issue! Thanks for your answers!
