### ISSUE TITLE
UPGRADE FAILED: rendered manifests contain a new resource that already exists. Unable to continue with update

### ISSUE THREAD

**Issue by smithdebug** [helm/helm#10107]
Output of `helm version`: 
`HELM_VERSION="3.0.3"`

Output of `kubectl version`:
`KUBECTL_VERSION="1.14.6/2019-08-22"`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
EKS

I'm trying to helm install but helm comes back saying with following error
Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict

have tried the following solution but it doesn’t seems to work.

`KIND=deployment`
`NAME=my-app-staging`
`RELEASE=staging`
`NAMESPACE=default`
`kubectl annotate $KIND $NAME meta.helm.sh/release-name=$RELEASE`
`kubectl annotate $KIND $NAME meta.helm.sh/release-namespace=$NAMESPACE`
`kubectl label $KIND $NAME app.kubernetes.io/managed-by=Helm`

**Comment by yxxhero** [comment]
@smithdebug try to delete conflict resource If it doesn't matter to recreate it. Careful operation!

**Comment by bacongobbler** [comment]
I do not believe resource adoption was available in Helm 3.0.3. It was introduced later into Helm 3’s release cycle.

Please try again using a more recent version. Helm 3.6.3 is the latest available release.

**Comment by smithdebug** [comment]
Updated the Helm version to 3.6.3 and it works like a charm. Thanks @bacongobbler
