### ISSUE TITLE
helm package command unzips/tars dependencies which does not work for multiple versions of same subchart

### ISSUE THREAD

**Issue by bert-at-github** [helm/helm#10102]
Output of `helm version`: version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"}

We use different versions of the same subchart as dependencies in a single chart.
Without packaging, this works fine because the chart/ folder contains the .tgz version of the subcharts, and these filenames contain the version, like "base-microservice-chart-0.3.6.tgz" and "base-microservice-chart-0.3.7.tgz"
The top chart specifies this version in the dependencies block, and all works fine.

When packaging this structure, the subcharts are unzipped and stored in the output tar using the subchart name as folder, but without the version (so "base-microservice-chart", which is the same for both versions).
As a result, in the tar the yaml files of both versions have the same folder/file names, and when un-tarring only one of these will be created on disk.  Not sure if this is the first one encountered in the tar byte stream, or if the last one is overwriting the first.

But in the end, only one version of the base chart is available, and helm removes the artifacts of the other dependency.

Would it be possible to keep both versions, for example by storing the tgz (with version in the name) embedded in the packaged chart, or store the subchart exploded as today, but under a versioned folder name? 

For info, I saw there was a question raised about this last year (https://github.com/helm/helm/issues/9128), but that was closed without a solution.

**Comment by charlesvg** [comment]
We have the same exact problem

**Comment by hobti01** [comment]
This topic was discussed with Helm 2 https://github.com/helm/helm/pull/5872 where some initial work was done, but @bacongobbler has rightly pointed out that there is more than just the file storage to accommodate to make this work as expected.
We would also be very interested in a solution to this.  Our expectation was that using different aliases would change the effective name of the chart at all levels.  If a chart used resource names that did not include the chart name then it would simply not be compatible with this method of packaging and deployment.  We do not expect that Helm would add an affix to resources or otherwise rename them in situations where two charts use static names, so perhaps that can be removed from the scope of any proposed solution.

**Comment by bacongobbler** [comment]
If anyone is interested in thinking this through I'd highly recommend following the contributing guide. Specifically the section on [Proposing an Idea](https://github.com/helm/helm/blob/main/CONTRIBUTING.md#proposing-an-idea). Chart aliases have always been a point of contention: some users want it to work the way it does today, and some others want it to work the way described here.

**Comment by charlesvg** [comment]
@bacongobbler I'm curious to when someone would want the current behavior, any idea? I haven't done the analysis @bert-at-github  did and maybe I should, but based on @bert-at-github 's input it seems the current behavior isn't even deterministic (or if it is deterministic, it might simply depend on the folder names you have, the last folder that contains the dependency might be the one that gets it to survive the compress/uncompress ?)

**Comment by bert-at-github** [comment]
I understand that backwards compatibility is important, but the behavior today is not consistent: 
When deploying from a local environment, without first packaging the chart, it works fine and different versions of the same subchart are used.
But when packaging that chart, only one subchart version will be available.   Dependencies that specify the 'other' version just seemed to get ignored in the template generation, and as a result artifacts are not created or removed if they existed before.

**Comment by R-omk** [comment]
Related https://github.com/helm/helm/issues/8804

**Comment by diyi0926** [comment]
@charlesvg @bert-at-github I'm facing the exact same issue. I'm wondering if you found a solution or workaround for this?
