### ISSUE TITLE
 Add Strict option to ApiVersions on helm template

### ISSUE THREAD

**Issue by Ragatzino** [helm/helm#10109]
Add strict option to ApiVersions in order to allow for strict control of ApiVersions in templating : 
Common usage : 
- argoCD : 
see https://github.com/argoproj/argo-cd/issues/3594

**Comment by sathieu** [comment]
not stale.

@bacongobbler Would you accept a `--api-versions-file` flag as discussed in #10108? Some *Application Distributors* need this feature.

**Comment by sathieu** [comment]
Not stale.

**Comment by sathieu** [comment]
> @bacongobbler Would you accept a `--api-versions-file` flag as discussed in #10108? Some *Application Distributors* need this feature.

@mattfarina ?

**Comment by Morriz** [comment]
bumping with a link to my comment here: https://github.com/helm/helm/pull/10108#issuecomment-1086645834

don't want to put stress on this, but just wish to crosslink discussion points

**Comment by Morriz** [comment]
bump

**Comment by sathieu** [comment]
Still needed (while less important, because no big API jump since the ingress v1).

**Comment by sathieu** [comment]
not stale...

**Comment by sathieu** [comment]
not stale ...
