### ISSUE TITLE
 io/fs: package io/fs is not in GOROOT, when use v3.7.0-*

### ISSUE THREAD

**Issue by MandssS** [helm/helm#10101]
helm: v3.7.0-*
go version go1.15.5 darwin/amd64

Require `v3.7.0-rc.2` or `v3.7.0-rc.1` to the project, then run go mod tidy. I get:

![image](https://user-images.githubusercontent.com/13030286/132188080-a8663da1-8ad9-4890-af5b-213b67d4f461.png)

**Comment by hickeyma** [comment]
@mandrean Can you try it again using Go 1.16?

**Comment by hickeyma** [comment]
Go 1.15.10+ should also fix it

**Comment by hickeyma** [comment]
Some references:

- https://github.com/golang/go/issues/44792
- https://golang.org/doc/devel/release#go1.15.minor

**Comment by bacongobbler** [comment]
Please upgrade to a more recent version of Go. It is part of the standard library.

Closing.
