### ISSUE TITLE
Helm Search Repo Ignores Chart Annotations

### ISSUE THREAD

**Issue by jessebye** [helm/helm#10118]
## Description

We would like to add annotations in our Chart.yaml:

```
annotations:
  branch: alpha
```

Then be able to search these with `helm search repo`. 

I confirmed that the annotations make it into the repo's `index.yaml`, so it seems like it should be searchable? But when I tested it, searching by a keyword that should have matched an annotation returned no results.

## Version Info

Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-eks-d88609", GitCommit:"d886092805d5cc3a47ed5cf0c43de38ce442dfcb", GitTreeState:"clean", BuildDate:"2021-07-31T00:29:12Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
EKS

**Comment by zonggen** [comment]
From my understanding, current `helm search repo` will only look into the chart repo name, chart name, description and keywords (code: https://github.com/helm/helm/blob/main/cmd/helm/search/search.go#L223)

An example:
```
$ helm repo add bitnami https://charts.bitnami.com/bitnami
```

If you look at their `index.yaml` (https://charts.bitnami.com/bitnami/index.yaml), they have a similar annotation:
```
annotations:
  category: Infrastructure
```
Then
```
$ helm search repo Infrastructure
NAME                    CHART VERSION   APP VERSION     DESCRIPTION                                       
bitnami/grafana-tempo   0.2.5           1.1.0           Grafana Tempo is an open source, easy-to-use an...
bitnami/haproxy         0.2.9           2.4.4           HAProxy is a TCP proxy and a HTTP reverse proxy...
```
`bitnami/grafana-tempo` and `bitnami/haproxy` have `infrastructure` in their keyword list and have `category: Infrastructure` in the annotation. On the other hand, `bitnami/kafka` also has `category: Infrastructure` but does not have the `infrastructure` in the keyword list, it's not included in the result.

So I think this is a feature request, to support searching on the chart annotations.

**Comment by bacongobbler** [comment]
Correct. Annotations are not looked up at this time.

Marking as a feature request.
