### ISSUE TITLE
Helm 3 uninstall - status uninstalling

### ISSUE THREAD

**Issue by rponcegarcia** [helm/helm#10113]
Hi guys, I'm having the following problem running `helm uninstall -n namespace release`

I am using the version of helm v3.6.3, when I delete a release, the state of the release stays in "uninstalling" for days and never changes the state to uninstalled, and this causes me not to be able to deploy later.

I am using EKS on AWS, version 1.21
Helm v3.6.3
Python 3.7.2

I have recently migrated from helm 2 to helm 3 with https://github.com/helm/helm-2to3
Can you help me please? I don't know if this is a known issue

**Comment by yxxhero** [comment]
@rponcegarcia Please show your cmd output. try it with --options. Thanks very much.
