### ISSUE TITLE
Helm login timeout issue - deploying over high latency connections

### ISSUE THREAD

**Issue by dmpavlidis** [helm/helm#10123]
Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1+k3s1", GitCommit:"75dba57f9b1de3ec0403b148c52c348e1dee2a5e", GitTreeState:"clean", BuildDate:
"2021-05-21T16:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1+k3s1", GitCommit:"75dba57f9b1de3ec0403b148c52c348e1dee2a5e", GitTreeState:"clean", BuildDate:
"2021-05-21T16:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform: Azure container registry

We are facing a very strange issue with "helm registry login" causing timeouts and our deployments to fail.

### Environment

K3s cluster running on Redhat - domain joined.

### Some background info:

We are using Azure Devops pipelines to deploy our application to vessels. 
Vessels are connected online via satellite connection - bandwidth is limited (max 2Mbps) and latency is over 500ms

The pipeline is running a bunch of different tasks and we have noticed that it may fail due to intermittent connection issues but by rerunning the pipeline we overcome those issues.

There is a problem, however, that we have pinpointed that seems to fail at every run, maybe due to high latency or other reasons (which is why we are opening this issue to get some assistance).

The command running via the devops pipeline is:

```
helm registry login $(ContainerRegistry.Name).azurecr.io -u 00000000-0000-0000-0000-000000000000 --password-stdin
```

### Error

The error is:

Error: Get "https://"azureregistry".azurecr.io/v2/": net/http: request canceled (Client.Timeout exceeded while awaiting headers)

![image](https://user-images.githubusercontent.com/5367229/133061600-f69be5b0-ea43-43ce-a898-d557e90eace1.png)

### Troubleshooting steps

Searching online for this error, pointed to different people solving this by using the Google DNS.

We have verified that we can work around the issue by changing the DNS settings (temporarily):

Normally, in our environment the DNS is setup like this (let's call them normal settings):

- Linux VM is domain joined - DNS is the Domain Controller
- The DC has as forwarder DNS the Firewall/UTM onboard.
- The Firewall/UTM has as forwarder Google DNS.

When we face the error, we can overcome it by setting the onboard router as DNS directly (with Google DNS as forwarder).

The reasons we cannot leave it like this:
- Security
- Local DNS entries cannot be resolved

We have verified that DNS is resolving hostnames correctly with both normal settings and the workaround.

The strange parts:
- Same normal settings work on other vessels at the same time.
- This is not reproducible every day on the same vessel, it seems it works some days and some others not.

My feeling is that "helm login" seems to be extra sensitive with some latency issues, but we cannot either pinpoint them or add a switch to allow for bigger timeout.

Do you have any idea on how to approach/resolve this issue? Currently, it's a bit hit or miss if we will be able to deploy and we are stuck.

If more information is needed, I would be happy to provide it. 

Thanking you in advance for any feedback on what to check/try.

**Comment by jimbogr77** [comment]
An update for reference:

We seem to be able to bypass the issue by eliminating the last step in the dns lookup forwarding chain:

> Normally, in our environment the DNS is setup like this (let's call them normal settings):
> 
> Linux VM is domain joined - DNS is the Domain Controller
> The DC has as forwarder DNS the Firewall/UTM onboard.
> ~~The Firewall/UTM has as forwarder Google DNS.~~

So now, the domain controller is allowed to forward the DNS request directly to the Google DNS.

Another issue though that we have found is that when we tried to use Cloudflare DNS or Fortigate DNS, sometimes one of the DNS entries would return an IP ending in 0 causing the timeout. 

Will post an update as the investigation continues.

**Comment by dmpavlidis** [comment]
Hi all,

Coming back to this, we are concluding to one of the first principles in IT: **It's always DNS**

We are still investigating why this happens, so we can resolve the root cause.

## Explanation

It seems that when se face the issue, the two hostnames used to connect to Azure resolve to an IP ending in 0:

### On vessels with the issue:

```
nslookup management.azure.com

Non-authoritative answer:
management.azure.comcanonical name = management.privatelink.azure.com.
management.privatelink.azure.comcanonical name = arm-frontdoor-prod.trafficmanager.net.
arm-frontdoor-prod.trafficmanager.netcanonical name = westeurope.management.azure.com.
westeurope.management.azure.comcanonical name = rpfd-prod-am-01.cloudapp.net.
Name:rpfd-prod-am-01.cloudapp.net
Address: **13.69.114.0**
```

```
nslookup eurnneregistry.azurecr.io

Non-authoritative answer:
eurnneregistry.azurecr.iocanonical name = 39eb6677cb034873bd0db919447eb159.trafficmanager.net.
39eb6677cb034873bd0db919447eb159.trafficmanager.netcanonical name = neu.fe.azcr.io.
neu.fe.azcr.iocanonical name = neu-acr-reg.trafficmanager.net.
neu-acr-reg.trafficmanager.netcanonical name = r1021neu.northeurope.cloudapp.azure.com.
Name:r1021neu.northeurope.cloudapp.azure.com
Address: **13.69.236.0**
``` 

### On vessel without the issue:

```
nslookup management.azure.com

Non-authoritative answer:
management.azure.comcanonical name = management.privatelink.azure.com.
management.privatelink.azure.comcanonical name = arm-frontdoor-prod.trafficmanager.net.
arm-frontdoor-prod.trafficmanager.netcanonical name = switzerlandnorth.management.azure.com.
switzerlandnorth.management.azure.comcanonical name = rpfd-switzerlandnorth.cloudapp.net.
Name:rpfd-switzerlandnorth.cloudapp.net
Address: **51.107.60.33**
```

We can work around the issue by forcing the hostname to resolve to another IP (by changing DNS, using static hosts etc) but this is not a viable solution.

**Comment by CoeckelberghPJ** [comment]
Coming back to this as we ran into the same issue again. 
I saw that it was mentioned by @bacongobbler as something worth evaluating. Has this been looked at at that time or hasn't this been picked up yet?
