### ISSUE TITLE
Helm dependency update fails with OCI on version 3.7.0-rc.3

### ISSUE THREAD

**Issue by FelipeEmerim** [helm/helm#10128]
Output of `helm version`:
version.BuildInfo{Version:"v3.7.0-rc.3", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.7"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.11", GitCommit:"abd6c80a2a7ad2abb79ed250047b72580f96b7ca", GitTreeState:"clean", BuildDate:"2021-08-23T18:11:34Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.19) exceeds the supported minor version skew of +/-1

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Azure (Using Azure container registry)

I have a Chart that has an OCI dependency like bellow: (I changed the registry name to not expose our registry :) )

```yaml
dependencies:
  - name: library
    version: 0.3.1
    repository: oci://registry.azurecr.io/helm
```

When I run helm dependency update against the version 3.7.0-rc.3 it fails with the error:

```
Getting updates for unmanaged Helm repositories...
...Unable to get an update from the "oci://registry.azurecr.io/helm" chart repository:
        object required
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "hashicorp" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading library from repo oci://registry.azurecr.io/helm
Save error occurred:  could not download oci://registry.azurecr.io/helm/library: manifest does not contain minimum number of descriptors (2), descriptors found: 1
Error: could not download oci://registry.azurecr.io/helm/library: manifest does not contain minimum number of descriptors (2), descriptors found: 1
```

Running the command on previous 3.7 release candidates or on latest 3.6 works fine. Is this a bug with helm, or something we should change on our Chart publishing. The Charts were published using latest 3.6. Will we have to publish them again when 3.7 comes out?

**Comment by bacongobbler** [comment]
In #9782, some changes were made to how helm pushes and pulls manifests. As this is experimental code, we do not make any backwards compatibility guarantees.

You will need to rebuild and re-upload your chart when you upgrade.

Thanks.

**Comment by FelipeEmerim** [comment]
Fair enough! I just wanted to be sure about what I need to do. I will rebuild it when 3.7 comes out.
Thank you for your time!

**Comment by vijtrip2** [comment]
Hi, I am seeing the same issue with helm 3.7 release.
The chart uploaded by built using helm 3.7 and pulling the chart still shows this message.

```bash
$ helm version
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}
```

Helm chart.yaml
```yaml
...
dependencies:
- name: aws-load-balancer-controller
  version: 1.2.7
  repository: https://aws.github.io/eks-charts
- name: apigatewayv2-chart
  version: v0.0.6
  repository: oci://public.ecr.aws/aws-controllers-k8s
```

`helm dependency update` output:

```bash
$ helm dependency update        
Getting updates for unmanaged Helm repositories...
...Unable to get an update from the "oci://public.ecr.aws/aws-controllers-k8s" chart repository:
        object required
...Successfully got an update from the "https://aws.github.io/eks-charts" chart repository
Hang tight while we grab the latest from your chart repositories...
Saving 2 charts
Downloading aws-load-balancer-controller from repo https://aws.github.io/eks-charts
Downloading apigatewayv2-chart from repo oci://public.ecr.aws/aws-controllers-k8s
Pulled: public.ecr.aws/aws-controllers-k8s/apigatewayv2-chart:v0.0.6
Digest: sha256:5416d770d6b25d6d72c26362c836c9e1b72f2736b42ada3f54eeb443aa5a49bd
Deleting outdated charts
```

As you can see getting an update for 'oci://public.ecr.aws/aws-controllers-k8s' is still failing with helm 3.7. Any suggestions?
