### ISSUE TITLE
lookup an annotation containing a slash

### ISSUE THREAD

**Issue by schwichti** [helm/helm#10127]
I want to implement a validation rule that checks if a namespace has the annotation `linkerd.io/inject=enabled`.
This is what I have tried:
 
```
{{if eq (lookup "v1" "Namespace" "" "namespace").metadata.annotations.linkerd.io/inject "enabled"}}
{{ fail "Linkerd injection not enabled." }}
{{end}}
```
Which gives me the parse error: bad character U+002F '/'
Is there a way to workaround this?

Output of `helm version`: version.BuildInfo{Version:"v3.6.2", GitCommit:"ee407bdf364942bcb8e8c665f82e15aa28009b71", GitTreeState:"clean", GoVersion:"go1.16.5"}

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"windows/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

**Comment by chris-maclean** [comment]
I think you can use the `get` function to grab this information:

```
{{ if eq (get (lookup "v1" "Namespace" "" "namespace").metadata.annotations "linkerd.io/inject") "enabled" }} 
```

If that's too many nested layers, consider saving a variables and accessing it with `$`:

```
{{ $myNamespace := (lookup "v1" "Namespace" "" "namespace") }}
{{ if eq (get $myNamespace.metadata.annotations "linkerd.io/inject") "enabled" }}
  {{ fail "Linkerd injection not enabled." }}
{{ end }}
```

**Comment by zonggen** [comment]
Found two possible solutions:
1. https://github.com/helm/helm/issues/2192#issuecomment-293739257
2. https://github.com/helm/helm/issues/8898#issuecomment-713836898

Both worked with your example, I tested with `helm create hello-world` and inserted the annotation check at `deployment.yaml`. No more `bad character U+002F '/'` with both methods.

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!
