### ISSUE TITLE
helm cli cmd for listing chart shows large names as truncated

### ISSUE THREAD

**Issue by ashishwigwag** [helm/helm#10132]
**Issue**
The `helm chart list` command doesn't display complete name(when long)  of helm chart.
```
$ helm chart list
REF                                                             NAME            VERSION DIGEST  SIZE    CREATED
localhost:8080/0166f9ba7080361e2d83535a00000000/test-helm...    newchart        0.1.0   88fa905 1.4 KiB 2 weeks
localhost:8080/0166f9ba7080361e2d83535a00000000/test-helm...    newchart        0.1.0   88fa905 1.4 KiB 10 days
```

It's difficult to manage the saved charts and versions as the most important values *name and tag *are missing.

Output of `helm version`:
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2-argus", GitCommit:"6d994d2f4e555d47e6f69419a21fee3e2e42f218", GitTreeState:"clean", BuildDate:"2021-08-06T08:34:55Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"linux/amd64"}

**Comment by bacongobbler** [comment]
`helm chart list` was removed in HEAD; see #9782.
