### ISSUE TITLE
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /dev/null

### ISSUE THREAD

**Issue by macrotex** [helm/helm#10138]
When running helm commands I am seeing this error:

WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /dev/null

Output of `helm version`: 
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}

Output of `kubectl version`:
 Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.13-gke.1200", GitCommit:"ee714a7b695ca42b9bd0c8fe2c0159024cdcba5e", GitTreeState:"clean", BuildDate:"2021-08-03T09:21:57Z", GoVersion:"go1.15.13b5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.19) exceeds the supported minor version skew of +/-1

Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE

**Comment by zonggen** [comment]
Answers from previous issues:
 - https://github.com/helm/helm/issues/9115
 - https://github.com/helm/helm/issues/8776

Hope this answers your question/concern :)

**Comment by macrotex** [comment]
> 
> 
> Answers from previous issues:
> 
>     * [WARNING: Kubernetes configuration file is group/world-readable #9115](https://github.com/helm/helm/issues/9115)
> 
>     * [Warning after upgrading to 3.3.3 #8776](https://github.com/helm/helm/issues/8776)
> 
> 
> Hope this answers your question/concern :)

The part that those issues don't address is why my error message refers to /dev/null.

**Comment by lindhe** [comment]
You can probably fix this by running:

```console
chmod g-r ~/.kube/config
```

**Comment by bacongobbler** [comment]
Is your KUBECONFIG environment variable set to /dev/null or something?

**Comment by akankshakumari393** [comment]
`chmod 600 ~/.kube/config` this should work

**Comment by bzdgn** [comment]
`chmod 700 ~/.kube/config` should work, **read**/**write**/**access** for the user but not for the group;

```
 ~ #ls -lrt ~/.kube/config  
-rwx------  1

 ~ #helm list
NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART	APP VERSION
~ #
```
