### ISSUE TITLE
request stricter validation

### ISSUE THREAD

**Issue by mcandre** [helm/helm#10139]
The Helm configuration design is perhaps too flexible. There is no single schema to validate the top-level values.yaml content against. This increases risk. For example, if a user like me accidentally typos `image.imagePullPolicy`, instead of the needed `image.pullPolicy` key, then Helm happily executes the chart without a peep.

I would love for the Helm system to provide a strict top-level scheme, so that we can automate basic validation checks. Any custom fields can be nested in a `custom` second level key, for example.

**Comment by bacongobbler** [comment]
Helm introduced the concept of validating a values file against a JSONSchema in Helm 3.0. You can read all about it here: https://helm.sh/docs/faq/changes_since_helm2/#validating-chart-values-with-jsonschema

Hope this helps.
