### ISSUE TITLE
GPG key for Release 3.7.0

### ISSUE THREAD

**Issue by rotskyi** [helm/helm#10137]
Greetings!

We are using the GPG key included in Helm release for validating those releases and spotted today that instead of @mattfarina latest release (3.7.0) is signed by @bacongobbler 

Was it done on purpose? Who will be signing releases from now on?

Thanks in advance!

**Comment by hickeyma** [comment]
@rotskyi Releases can be cut by any of the core maintainers. @bacongobbler is a core maintainer and he cut the release for 3.7.0, even though @mattfarina cut the RCs for 3.7.0. @mattfarina just happens to have been cutting releases of late and we are thankful for him for doing it.

Hope this helps.

**Comment by hickeyma** [comment]
In other words, whoever cuts the release check their key.

**Comment by rotskyi** [comment]
Thanks for reply! Is there somewhere a list of core maintainers? We are really grateful for releases, guys, just in terms of security we need some signatures to check against 🤔

**Comment by bacongobbler** [comment]
https://github.com/helm/helm/blob/main/KEYS
