### ISSUE TITLE
Install new release 3.7.0 failed

### ISSUE THREAD

**Issue by trombini77** [helm/helm#10133]
Output of `helm version`:
I have a GIthub Actions workflow with a step that always take the last helm master release like this:

 curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
chmod u+x get_helm.sh
./get_helm.sh
rm get_helm.sh
helm version

The ouput was:

Helm v3.7.0 is available. Changing from version v3.6.3.
Downloading https://get.helm.sh/helm-v3.7.0-linux-amd64.tar.gz
Verifying checksum... SHA sum of /tmp/helm-installer-g7cox2/helm-v3.7.0-linux-amd64.tar.gz does not match. Aborting.
Failed to install helm
	For support, go to https://github.com/helm/helm.
Error: Process completed with exit code 1.

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by bacongobbler** [comment]
CI is currently building Helm 3.7.0's release assets. It should be complete in a few minutes.

If you want to follow along: https://app.circleci.com/pipelines/github/helm/helm/3054/workflows/0073cbd2-97dd-45e4-9ad7-660aa4b07969/jobs/14629

Thanks for being patient.

**Comment by trombini77** [comment]
Thanks for the feedback.
