### ISSUE TITLE
use "helm upgrade" for deploy appmesh-controller, "--namespace" explicitly specifying doesn't work

### ISSUE THREAD

**Issue by yanmin950122** [helm/helm#10147]
Output of `helm version`:
![image](https://user-images.githubusercontent.com/24740678/133716965-78573413-a028-4e9e-a74a-f15cac67aee8.png)
Output of `kubectl version`:
![image](https://user-images.githubusercontent.com/24740678/133717082-3766e42b-a1c6-4f45-a3e9-d791108350b3.png)

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AWS

I use "helm upgrade" to deploy appmesh-controller in local environment. But the  param ''--namespace" is not  transferred  to the template.
```
helm upgrade -i appmesh-controller eks/appmesh-controller \
    --namespace appmesh-system \
    --set region=$AWS_REGION \
    --set serviceAccount.create=false \
    --set serviceAccount.name=appmesh-controller
```

![image](https://user-images.githubusercontent.com/24740678/133718488-a1f0f49c-a7ec-421a-b3e6-2699eb803f33.png)

Please check this issue for details of this: https://github.com/aws/eks-charts/issues/602

**Comment by bacongobbler** [comment]
Please use a more recent version of Helm 3. We do not provide support for pre-alpha release candidates of Helm 3.
