### ISSUE TITLE
Proposal: Make --install the default behavior for helm upgrade

### ISSUE THREAD

**Issue by mcandre** [helm/helm#10142]
Interested in the upgrade task behaving idempotently by default. Any strong opposition to making `--install` the default behavior?

**Comment by bacongobbler** [comment]
Yes. `helm upgrade` is expected to fail when a release does not exist unless the `--install` flag is provided. This prevents users from "fat-fingering" a typography in their release name. That is why it was introduced as a feature flag.

Consider this:

```
helm upgrade --install myapp myapp.tgz
helm upgrade --install myap myapp.tgz
```

To many users this is undesirable behavior.

In any case, if you want to propose this as a change for Helm 4, please see https://github.com/helm/helm/blob/main/CONTRIBUTING.md#proposing-an-idea

Thanks.
