### ISSUE TITLE
HELM PUSH --version

### ISSUE THREAD

**Issue by helldweller** [helm/helm#10155]
Output of `helm version`:
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): baremetal

I used the push plugin (https://github.com/chartmuseum/helm-push) and now you have replaced it with your own. (helm push)
The --version option is sorely missing!

**Comment by yxxhero** [comment]
@helldweller try `helm version`

**Comment by bacongobbler** [comment]
`helm push` only accepts charts that were packaged with `helm package`. Once a chart has been packaged, Helm does not make any changes to its metadata as that will invalidate any signatures generated with `helm package --sign`. Therefore we will not be introducing a `--version` flag to `helm push`, as that will modify the chart's metadata and invalidate the signature.

chartmuseum's `helm push` plugin was an early concept design that both packages and pushes a chart in one command, but did not include core concepts like [package attestation or signing](https://helm.sh/docs/topics/provenance/#the-provenance-file) in its design.

In your case, chartmuseum's `helm push --version` is identical to helm's `helm package --version && helm push`.

Please use the `helm package --version` flag before a `helm push`.

Thanks.
