### ISSUE TITLE
helm dependencies should be installed separately in order

### ISSUE THREAD

**Issue by protosam** [helm/helm#10159]
This is a feature request.

# Problem Statement

Helm just renders all the things, validates it, and sends it off to the cluster. When your chart is trying to apply a custom resource that comes from one of the dependencies the install can fail.

An example of this is if you use the `cert-manager` chart as your dependency and you go to apply a `ClusterIssuer`. It also fails if you try to move your `ClusterIssuer` to a post-install hook because cert-manager is still in the middle of setting itself up.

# Requested/Proposed Functionality

Provide charts the ability to install each chart in order as defined in the dependencies. Helm checking each as it installs them before moving to the next one.

---
A bit of my thoughts on this. If my chart depends on another chart to work, the other chart should be installed. It's not very dependable.

**Comment by bacongobbler** [comment]
Hi @protosam.

When proposing a new idea to the Helm project, please make sure to write up a [Helm Improvement Proposal](https://github.com/helm/community/tree/main/hips). A Helm Improvement Proposal is a design document that describes a new feature for the Helm project. The proposal should provide a concise technical specification and rationale for the feature, including information like how this idea plans to address backwards compatibility.

It is also worth considering vetting your idea with the community via the [cncf-helm mailing list](https://github.com/helm/community/tree/main/hips). Vetting an idea publicly before going as far as writing a proposal is meant to save the potential author time. Many ideas have been proposed; it's quite likely there are others in the community who may be working on a similar proposal, or a similar proposal may have already been written.

HIPs are submitted to the [helm/community repository](https://github.com/helm/community). [HIP 1](https://github.com/helm/community/tree/main/hips) describes the process to write a HIP as well as the review process.

After your proposal has been approved, follow the [developer's guide](https://helm.sh/docs/community/developers/) to get started.

Hope this helps.

**Comment by protosam** [comment]
Done with [PR 212](https://github.com/helm/community/pull/212). Should we just close this? @bacongobbler

**Comment by bacongobbler** [comment]
Yes. Let's continue the discussion in the HIP.

Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!
