### ISSUE TITLE
Does helm lint support any form of lint reports like JUnit or ESLint?

### ISSUE THREAD

**Issue by caryyu** [helm/helm#10151]
As we're leveraging SonarQube as our unified QA management system, the use case is we'd like to integrate helm lint's output into it, which one of the solutions for YAML that I could figure out is [YamlLint-Checkstyle](https://github.com/thomaspoignant/yamllint-checkstyle), however, which can only support the YAML level lint, not helm lint, therefore, I just want to ask if there is a solution for it, thanks.

**Comment by bacongobbler** [comment]
not according to the docs, no. https://helm.sh/docs/helm/helm_lint/
