### ISSUE TITLE
Helm hooks fight against the declarative philosophy of Kubernetes, what are the plans going forward?

### ISSUE THREAD

**Issue by JoaRiski** [helm/helm#10153]
As the title says, the way Helm currently handles hooks is imperative as opposed to being declarative, which goes against the philosophy of kubernetes-based systems.

With the removal of Tiller (a good change in my opinion), helm no longer has any other way to provide hook capabilities beyond waiting for clients to handle the imperative state tracking. Moreover, charts that rely on hooks are potentially unusable if templates need to be pre-rendered and deployed with something else. As an example, [Pulumi](https://www.pulumi.com/) was not able to handle helm hooks until very recently, and personally I don't believe they even should be required to do so, given their non-declarative nature.

The first thing that comes to mind would be using custom [operators](https://kubernetes.io/docs/concepts/extend-kubernetes/operator/) for handling what the hooks do now, but in a more sane fashion compared to what Tiller used to do. Ideally the ecosystem would have enough operators that charts can rely on instead of using helm hooks.

Are there any plans on changing this behavior or has it been brought up for discussion somewhere? I tried checking the most obvious places + search engines, but didn't find any relevant discussion.

My personal view currently is that helm hooks should be replaced with something better suited to the ecosystem, e.g. the operator pattern example, and I'd imagine pushing towards that would provide better opportunities for new operator-based tooling such as https://schemahero.io/ to grow.

**Comment by bacongobbler** [comment]
Hi @JoaRiski. Thank you for sharing your opinions.

> Are there any plans on changing this behavior or has it been brought up for discussion somewhere?

In general, changing the behavior of an existing Helm feature cannot occur until the next major release. Helm maintains a very strong commitment to backward compatibility. All of our changes to protocols and formats are backward compatible from one major release to the next. No features, flags, or commands are removed or substantially modified unless we need to fix a security issue.

That being said... No. There are no plans to change the way hooks work. Many users are using helm hooks as they are today. To change their behavior means any charts that were built any time between Helm 2.0.0 and Helm 3.7.0 with hooks will no longer work. Changing a hook's behavior also affects strategies like upgrades or rollbacks in a significant manner, potentially breaking users running Helm in production scenarios.

> My personal view currently is that helm hooks should be replaced with something better suited to the ecosystem

If you'd like to propose a change to Helm, we have a proposal system in place called the [Helm Improvement Proposal](https://github.com/helm/community/blob/main/hips/hip-0001.md), or HIP for short. If you would like to propose an idea, a HIP is the right place to get started as it asks the author to consider cases like backwards compatibility and security concerns with their changes, along with how to teach new and existing users how to migrate or use this new system.

Closing as answered. If you'd like to write a proposal, please follow the Contributing Guide on ["Proposing an Idea"](https://github.com/helm/helm/blob/main/CONTRIBUTING.md#proposing-an-idea). 

Please let me know if you have further questions.
