### ISSUE TITLE
helm template adds default namespace

### ISSUE THREAD

**Issue by aleybovich** [helm/helm#10161]
When running `helm template` on `bitnami/rabbitmq` helm chart, it always inserts the default namespace into all objects. Is there a way to tell helm not to add `namespace: default` to all objects in the generated template? 

Output of `helm version`:
```version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:10:22Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  local Docker Desktop Kubernetes

**Comment by bacongobbler** [comment]
Helm does not inject a namespace into a template. In fact, nothing is injected into the templates. The chart author has full control here.

Please open a support ticket with bitnami. Thanks.

**Comment by bacongobbler** [comment]
For context: #3553
