### ISSUE TITLE
The minimal value of history-max option

### ISSUE THREAD

**Issue by flying-snail0630** [helm/helm#10168]
`helm version`: 
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}

`kubectl version`: 
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:39:34Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): `minikube`

According to the helm document.

`--history-max int              limit the maximum number of revisions saved per release. Use 0 for no limit (default 10)`

So I assume the minimal value for history-max is 1. However, when I run command **helm upgrade <release-name> -i --history-max 1** to install the chart more than 1 time, I realize the history length of that release is more than 1. The history-max 1 behavior is consistent with history-max 2.

`helm history example -n <ns>`
```
REVISION	UPDATED                 	STATUS    	CHART                	APP VERSION	DESCRIPTION     
2       	Fri Sep 17 21:10:57 2021	superseded	xxx	1.0        	Upgrade complete
3       	Fri Sep 17 21:11:39 2021	deployed  	xxx	1.0        	Upgrade complete
```

**Comment by bacongobbler** [comment]
This is working as intended. `--history-max 1` will retain one release OTHER than the release currently deployed. This allows the user to issue a `helm rollback`. Helm must retain at least one revision to ensure a clean upgrade.
