### ISSUE TITLE
Is have any flags/plugins for colored output of helm command?

### ISSUE THREAD

**Issue by razdenand** [helm/helm#10173]
I use helm chart and helm command for deploy my app, and I want to get colored output for helm command, because colored output would help you find errors faster when deploying. Is there a mechanism that allows you to make a color output of helm 3 commands?

**Comment by bacongobbler** [comment]
No, there is no support for colored output at this time.

**Comment by Gilad-Sharaby** [comment]
in macOS, you can pipe to yq:
```shell
 helm template my-service charts/main --values charts/main/dev.yaml | yq
```
