### ISSUE TITLE
helm function urlquery doesnt encode character ','

### ISSUE THREAD

**Issue by varunshaji** [helm/helm#10170]
Output of `helm version`:
Version:"v3.6.2", GitCommit:"ee407bdf364942bcb8e8c665f82e15aa28009b71", GitTreeState:"dirty", GoVersion:"go1.16.5"}
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:52:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Its veru qeird . I have a string with a , in it .url query encodes everything except the comma

**Comment by bacongobbler** [comment]
Please open an issue with the Go team. `urlquery` is part of `text/template`, so any fixes will need to be applied there.

https://pkg.go.dev/text/template#hdr-Functions
