### ISSUE TITLE
Support for "Uploader Plugins"

### ISSUE THREAD

**Issue by jdolitsky** [helm/helm#10175]
In order to use the new 3.7+ `helm push` functionality with non-OCI backends (e.g. ChartMuseum), we should add support for "Uploader Plugins", similar in form to what is already possible in "Downloader Plugins": https://helm.sh/docs/topics/plugins/#downloader-plugins

The helm-push plugin (https://github.com/chartmuseum/helm-push) is currently broken with Helm 3.7+ as the `push` subcommand conflicts with the name of the plugin.

Working code for this functionality can be found on an old branch here: https://github.com/bloodorangeio/helm/blob/hip-6-push/pkg/pusher/pluginpusher.go

For more info, please see https://github.com/chartmuseum/helm-push/pull/110#issuecomment-925035486

**Comment by sathieu** [comment]
Thanks @jdolitsky. Could the http/https uploader plugin should be bundled in Helm itself? Starting from the `helm-push` plugin behavior would hopefully unify the currently diverging APIs (Nexus/Artifactory/Chartmuseum/...).

**Comment by jdolitsky** [comment]
@sathieu - I'm not sure... It is dissimilar to OCI, since not all chart repos are ChartMuseum repos. People may be confused thinking they can upload a chart to a non-ChartMuseum repo if we did that.

**Comment by sathieu** [comment]
@jdolitsky I understand your concerns. I thought it was a good opportunity to have a common interface for all implementations (like other package managers have).

**Comment by scottrigby** [comment]
Not stale
