### ISSUE TITLE
Version comparison fails

### ISSUE THREAD

**Issue by oliverdawid** [helm/helm#10179]
When installing longhorn on my microk8s, it fails because of version comparison:
helm thinks, that v1.22.1-3+e6976ed80e19e1 is smaller than v1.18.0.

Output of `helm version`:
Error: INSTALLATION FAILED: chart requires kubeVersion: >=v1.18.0 which is incompatible with Kubernetes v1.22.1-3+e6976ed80e19e1

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:52:24Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.1-3+e6976ed80e19e1", GitCommit:"e6976ed80e19e15585876f690d102e8177c76e99", GitTreeState:"clean", BuildDate:"2021-08-27T01:34:12Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
microk8s v1.22.1
Installation via snap on ubuntu

**Comment by KanShiori** [comment]
In longhorn v1.2.0, the `kubeVersion` in Charts.yaml is ">=v1.18.0", so "v1.22.1-3+e6976ed80e19e1" is smaller than "v1.18.0".

It change to `kubeVersion: ">=1.18.0-0"` in  longhorn v1.2.1-rc1, maybe you can try longhorn v1.2.1-rc1.


Charts.yaml Ref: https://github.com/longhorn/longhorn/blob/84d2f4891204cd5fae32735482c9f65eaa49e3ad/chart/Chart.yaml#L5

Helm Doc Ref: https://helm.sh/docs/chart_template_guide/function_list/#working-with-prerelease-versions

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!
