### ISSUE TITLE
--post-renderer does not support cross-platform bash/sh scripts

### ISSUE THREAD

**Issue by esune** [helm/helm#10180]
Output of `helm version`: `version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}`

Output of `kubectl version`: 
```bash
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", 
Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:39:34Z", GoVersion:"go1.16.7", 
Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): `minikube`

I am using Helm on Windows 10, Git bash is my shell of choice. I also use Ubuntu on WSL2and have aliased the `helm` command so that I can share the executable between the two platforms while it's installed in Windows.

I have create an `sh` script to use `envsubst` as a `--post-renderer`, but when I invoke the command (regardless of whether this is in WSL2 or Git Bash under Windows) Helm throws the following error:
```bash
$ helm template mytemplate ./mytemplate/ --post-renderer envsubst/envsubst.sh
Error: error while running post render on files: error while running command \\wsl$\Ubuntu\home\esune\git-repos\myproject\helm\envsubst\envsubst.sh. error output:
: fork/exec \\wsl$\Ubuntu\home\esune\git-repos\myproject\helm\envsubst\envsubst.sh: %1 is not a valid Win32 application.
```
It appears that Helm is expecting the file to be a Win32 file (it will, in fact, run `bat` files) and it is therefore impossible to use the script even if the correct interpreter (Git bash) is installed on the host machine. This seems like a big issue as it prevents charts from being usable cross-platform.

**Comment by zonggen** [comment]
From my understanding Helm is using the standard `os/exec` library (https://github.com/helm/helm/blob/main/pkg/postrender/exec.go#L46). And within the standard library

> The Windows version specified by internally-linked Windows binaries is now Windows 7 rather than NT 4.0.
> Reference: https://golang.org/doc/go1.13#windows

Can you explicitly call the interpreter, Git Bash in this case (something like `--post-renderer "/path/to/bash -c envsubst/envsubst.sh" `) and see if it works?

**Comment by esune** [comment]
```bash
Error: invalid argument "/bin/bash -c envsubst/envsubst.sh" for "--post-renderer" flag: unable to find binary at /bin/bash -c envsubst/envsubst.sh: exec: "/bin/bash -c envsubst/envsubst.sh": stat /bin/bash -c envsubst/envsubst.sh: no such file or directory
```
I also tried using `$(pwd)/envsubst/envsubst.sh` to have a fully qualified path for the script, same result.

I think the issue might be with Helm using Go's `os/exec` to spawn the new process and how it might expect a "compatible" architecture for the target binary. I am not familiar enough with Go to provide further input, but I think this doesn't really scale well when you potentially have developers using different host architectures executing the same Helm command.

**Comment by esune** [comment]
Still looking for clarifications/suggestions.

**Comment by esune** [comment]
Still looking for clarifications/suggestions.

**Comment by esune** [comment]
Still looking for clarifications/suggestions.

**Comment by joejulian** [comment]
Your error was because you used the whole string as the name of the binary. It looked for the command, spaces and all, as the name of the command. You need to split that between `--post-renderer` and `--post-renderer-args`. See https://helm.sh/docs/helm/helm_install/#options

**Comment by esune** [comment]
@joejulian I am not sure I follow you: there are no arguments in my call, just the path to the executable to be used as renderer, which is consistent with the documentation.
The reported issue is not that the command doesn't work, but that it ONLY works under Linux and not in other bash-compatible shells such as Git bash due to Go relying on the architecture of the underlying OS to spawn the process.

**Comment by joejulian** [comment]
```
Error: invalid argument "/bin/bash -c envsubst/envsubst.sh" for "--post-renderer" flag: unable to find binary at /bin/bash -c envsubst/envsubst.sh: exec: "/bin/bash -c envsubst/envsubst.sh": stat /bin/bash -c envsubst/envsubst.sh: no such file or directory
```
is caused by `--post-renderer "/bin/bash -c envsubst/envsubst.sh"` as you've told it the name of the file you're trying to run is that entire string, spaces and all.

Try `--post-renderer /bin/bash --post-renderer-args -c --post-renderer-args envsubst/envsubst.sh`

**Comment by esune** [comment]
> 
> Try `--post-renderer /bin/bash --post-renderer-args -c --post-renderer-args envsubst/envsubst.sh`

I will give a try your suggestion, however to be 100% clear my initial command 9see opening post) was:
```
$ helm template mytemplate ./mytemplate/ --post-renderer envsubst/envsubst.sh
Error: error while running post render on files: error while running command \\wsl$\Ubuntu\home\esune\git-repos\myproject\helm\envsubst\envsubst.sh. error output:
: fork/exec \\wsl$\Ubuntu\home\esune\git-repos\myproject\helm\envsubst\envsubst.sh: %1 is not a valid Win32 application.
```

This works on Linux, will not work in Windows under a bash-compatible shell. No spaces in the post-renderer argument in this case.

**Comment by joejulian** [comment]
Does envsubst.sh have a [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) to inform the library function what program to execute the script with? Clearly without it windows is trying to interpret text as a binary.

**Comment by esune** [comment]
> Does envsubst.sh have a [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) to inform the library function what program to execute the script with? Clearly without it windows is trying to interpret text as a binary.

Yes, it does have a shebang identifying `bash` as the interpreter/executor for the script.

**Comment by joejulian** [comment]
Well I'm stumped. Someone with a similar question asked [here](https://github.com/helm/helm/issues/11441#issuecomment-1279537991) and it worked for them. Maybe there's a nugget there that I'm just missing.

**Comment by esune** [comment]
@joejulian in the other question they are using a `ps1` script (Powershell) in Powershell on Windows. Powershell is part of the OS architecture in windows.

Since I would like my script to be portable, I used bash and am using Git Bash as interpreter in Windows. Bash is not part of the OS architecture in windows.

Quoting one of my previous replies:
> I think the issue might be with Helm using Go's os/exec to spawn the new process and how it might expect a "compatible" architecture for the target binary.

**Comment by joejulian** [comment]
Again, I can only give you hints to what worked for someone else. Ultimately, this is for helm support and what you seem to need is operating system support. If you think it's Go's os/exec, perhaps you need to visit Gopher's slack. Maybe write a small go program and see if you can run your script from there. If it works, maybe that'll shine some light on this issue.

**Comment by joejulian** [comment]
fyi, I did double-check the source. The command you give helm is run from here: https://github.com/helm/helm/blob/main/pkg/postrender/exec.go#L47

There's nothing in there that would tell windows to run it any other way. I suppose, if the shebang isn't being interpreted by windows, the other option would be to run bash as your post-renderer and specify your script as the post-renderer-option.

**Comment by esune** [comment]
Thank you @joejulian, I'll try to follow-up with the Go team if/when I get a chance. This issue may come in handy in the future if someone else is having a similar problem.
