### ISSUE TITLE
uninstall helm release which installed using helm install --generate-name

### ISSUE THREAD

**Issue by amjad489** [helm/helm#10187]
I have installed the helm chart using the following command and the install command was successfull.

```
helm install --generate-name
```

However i'm unable to uninstall helm release after this using `helm uninstall` command.

I get the following error. 
```
Error: uninstall: Release name is invalid:
```

I understand the reason as to why its throwing this error. But I want to know how I can uninstall this release

**Comment by bacongobbler** [comment]
Can you please provide the output of `helm list -all-namespaces`? Thanks.

**Comment by amjad489** [comment]
seems issue from my side. closing it.

**Comment by amjad489** [comment]
thanks you @bacongobbler
