### ISSUE TITLE
Add ability to pass Capabilities to lint

### ISSUE THREAD

**Issue by tarioch** [helm/helm#10190]
With #5392 support was added to helm template to provide capabilities. It would be great if that would also be possible for helm lint. 

e.g. currently I'm getting warnings that the produced ingress is deprecated, but this is only because the chart supports newer and older versions.

This was originally requested as part of #3377 but I think it got lost

**Comment by zonggen** [comment]
Partial duplicate of https://github.com/helm/helm/issues/3377 but I think it makes sense to continue `lint` story here. PRs are welcomed and would love to take a look!

**Comment by mlushpenko** [comment]
not stale

**Comment by genofire** [comment]
Please reopen this issue again. Like in #3377 said, it solves only template (not linting).

**Comment by wrenix** [comment]
@gjenkins8 could you reopen this issue again? (or should i create another like #12451 ) ?
