### ISSUE TITLE
Helm 3.7.0 sdk locate chart

### ISSUE THREAD

**Issue by martin-schoenegger** [helm/helm#10191]
Hello everyone!

I am trying to use the install function of the helm sdk with the new oci:// feature. 
I have a docker registry deployed locally without authentication. 
Using the helm 3.7.0 binary I can perform `helm pull oci://localhost:5000/my-chart --version v1.2.3` and `helm push my-chart-v1.2.3.tgz oci://localhost:5000/my-chart --version v1.2.3` without any issues. However when I try to get the chart in a go program using [LocateChart()](https://github.com/helm/helm/blob/main/pkg/action/install.go#L675) helm is trying to GET "127.0.0.1:5000/index.yaml" which is not present on the registry and I get the error: "object required"

This is my client code in short form:

```
	"helm.sh/helm/v3/pkg/action"
	"helm.sh/helm/v3/pkg/chart"
	"helm.sh/helm/v3/pkg/chart/loader"
	"helm.sh/helm/v3/pkg/cli"
	"helm.sh/helm/v3/pkg/release"
	
        settings := cli.New()
        actionConfig := new(action.Configuration)
	err := actionConfig.Init(settings.RESTClientGetter(), "my-namespace", os.Getenv("HELM_DRIVER"), log.Printf)
	if err != nil {  ... }
	client := action.NewInstall(actionConfig)
	client.GenerateName = false
	client.Atomic = true
	client.RepoURL = "oci://127.0.0.1:5000"
	client.Version = "v1.2.3"
	client.ReleaseName = "my-release"
	client.Namespace = "my-namespace"
	client.UseReleaseName = true
	chartPathOptions := &client.ChartPathOptions

	envSettings := cli.New()
	envSettings.Debug = true
	chartPath, err := chartPathOptions.LocateChart("chart-name", envSettings)
	if err != nil { ... }
	helmChart, err := loader.Load(chartPath)
	if err != nil {...}
        release, err := client.Run(helmChart, valuesYaml)


```
Do I need to configure something I am not aware of on the client side(go program)? Do I need to configure the registry? Is it rather recommended to use NewPull().Run()? Or is there somewhere an example for sdk version 3.7.0?

Thank you in advance for your advice.

Best regards Martin

Output of `helm version`:
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-12T12:32:49Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
minikube

**Comment by yxxhero** [comment]
@martin-schoenegger
try: 
1. not set `client.RepoURL`
2. chartPath, err := chartPathOptions.LocateChart("oci://localhost:5000/my-chart", envSettings)

**Comment by martin-schoenegger** [comment]
Thank you, that did the trick.

**Comment by yxxhero** [comment]
Thanks very much. I will close the issue. @martin-schoenegger
