### ISSUE TITLE
Can i retrieve the content of a file from a url?

### ISSUE THREAD

**Issue by antonisnyc94** [helm/helm#10192]
e.g 
{{ (.Files.Glob "**url_link**").AsSecrets | indent 2 }}

Thanks in advance!!
Tony

**Comment by bacongobbler** [comment]
No. We've intentionally prevented the template engine access to external resources (such as issuing HTTP requests) for security purposes.

Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!
