### ISSUE TITLE
--create-namespace deleted old namespace

### ISSUE THREAD

**Issue by patryksandomierski** [helm/helm#10195]
We had namespace chart with e.g.:
```
namespace.yaml
limitrange.yaml
rolebinding.yaml
```
etc.
It was installed (updated) using `helm upgrade --install --history-max 1 -n $NAMESPACE $CLUSTER-$NAMESPACE-app-namespace /path/to/chart --wait`
It was working for a long time but since helm v3 doesn't allow creating namespace from template, and we wanted programmatically create namespaces, we deleted `namespace.yaml` from chart and added flag `--create-namespace` to run command.
Logs:
```
05:59:56 +0200 Release "$CLUSTER-$NAMESPACE-app-namespace" has been upgraded. Happy Helming!
05:59:56 +0200 NAME: $CLUSTER-$NAMESPACE-app-namespace
05:59:56 +0200 LAST DEPLOYED: Wed Sep 29 03:59:52 2021
05:59:56 +0200 NAMESPACE: $NAMESPACE
05:59:56 +0200 STATUS: deployed
05:59:56 +0200 REVISION: 125
05:59:56 +0200 TEST SUITE: None
05:59:56 +0200 rolebinding.rbac.authorization.k8s.io/edit-1 annotated
05:59:56 +0200 rolebinding.rbac.authorization.k8s.io/edit-1 annotated
```
Looks fine, but in effect namespace was deleted. Disappeared.
After this disaster, we added annotation `"helm.sh/resource-policy": keep`. ATM, we cannot create namespaces using helm - only using `oc`.

Output of `helm version`:
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"}

Output of `kubectl version`:
Client Version: openshift-clients-4.5.0-202006231303.p0-21-g297a4ac42
Kubernetes Version: v1.20.0+9689d22

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Microsoft ARO

**Comment by hickeyma** [comment]
I am unsure what exactly is causing your issue without more details. In the meantime, here are some suggestion wrt namespaces:

- Create the namespace ahead of time and manage it outside the context of the chart(s) using it **OR**
- Create namespace on the fly using `--create-namespace` flag. Avoid having a manifest/template in the chart to create the namespace

It is recommended to do one or the other but not both. This is where the confusion occurs in the system.

Related #9966 #9965

**Comment by bacongobbler** [comment]
I think I understand where the confusion may be coming from.

> and we wanted programmatically create namespaces

You had a chart that declared its own namespace. In general that is considered bad practice for this exact reason. If you choose to change or remove the namespace from the chart, the namespace as well as any resources that were deployed in that namespace will be deleted.

The best practice described in the documentation is to use the `--namespace` parameter to declare which namespace your chart should be installed into. If the namespace does not already exist, provide the `--create-namespace` flag when first installing to ensure it is created ahead of time before your chart is installed.

Side note: `--create-namespace` only creates the namespace when the chart is being installed for the first time. It does not re-create the namespace on subsequent upgrades - the namespace is assumed to be present. Source: https://github.com/helm/helm/blob/9fafb4ad6811afb017cc464b630be2ff8390ac63/pkg/action/install.go#L305-L328

Sorry to hear you ran into this.

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!
