### ISSUE TITLE
Run command 'helm lint my-chart-v1.0.0.tgz', the check passes, is 'v1.0.0' a valid semantic version number?

### ISSUE THREAD

**Issue by ruanyulin2017** [helm/helm#10199]
The Chart.yaml:
apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name my-chart
version: v1.0.0

helm lint my-chart-v1.0.0.tgz, output:
==> Linting my-chart-v1.0.0.tgz
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, no failures

my helm version is v2.16.9, is 'v1.0.0' a valid semantic version number?

**Comment by bacongobbler** [comment]
Helm 2's support lifecycle ended on November 2020. See [the blog post](https://helm.sh/blog/helm-2-becomes-unsupported/) for more details.
