### ISSUE TITLE
Does installing helm from Apt work?

### ISSUE THREAD

**Issue by arbogast** [helm/helm#10202]
Versions:
https://baltocdn.com/helm/stable/debian all/main amd64 helm amd64 3.7.0-1 [13.8 MB]

During installation similar to the one described here: https://helm.sh/docs/intro/install/#from-apt-debianubuntu, after command `curl https://helm.baltorepo.com/organization/signing.asc | apt-key add -` I'm receiving error:
```
apt-key add -

+ curl https://helm.baltorepo.com/organization/signing.asc

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed


  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: apt-key output should not be parsed (stdout is not a terminal)


  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

curl: (60) SSL certificate problem: certificate has expired
```
Maybe it's connected with Let's Encrypt root certificate expiration?

**Comment by mattfarina** [comment]
On the Helm project we don't support or maintain an apt repo. This is provided by the Helm community rather than the Helm project. The Helm docs point people to community locations but we are not in a position to support them and do not have access to them.

**Comment by arbogast** [comment]
Thanks for info!

**Comment by Baklap4** [comment]
Do we know who maintains this apt community project?

**Comment by bacongobbler** [comment]
The repository URL should give some hint as to who maintains the repository. Balto maintains it.

https://www.getbalto.com/
