### ISSUE TITLE
Does go library of helm support the listing all K8s resources installed as part of helm chart.

### ISSUE THREAD

**Issue by yogesh-reddy** [helm/helm#10204]
While using the helm go client and installing the charts is there a way to checks what are Kubernetes resources are installed as part of a chart?

**Comment by mattfarina** [comment]
Are you looking to see the resources installed as part of a chart after the install has completed or prior to installation? If you perform a[ dry-run install](https://github.com/helm/helm/blob/9fafb4ad6811afb017cc464b630be2ff8390ac63/pkg/action/install.go#L80) you can see the resources that would be installed.
