### ISSUE TITLE
Feature request: improve error message when no official releases are published and --devel is not set

### ISSUE THREAD

**Issue by howardjohn** [helm/helm#10212]
Output of `helm version`: v3.7.0"

Currently, if you try to interact with a helm chart that does not have a official release set, you will get an error message that is a bit misleading:
```
$ helm show readme foo/bar
Error: failed to download "foo/bar"
```

Adding `--devel` fixes it, but its not very discoverable.

It would be great if it was changed to something like
```
$ helm show readme foo/bar
Error: failed to find a suitable version of "foo/bar", but a development version was available. Use --devel to use it.
```

**Comment by anshulvermapatel** [comment]
I will be working on this one.
