### ISSUE TITLE
helm  dependency update with oci registry  does not allow version starts with  "~" 

### ISSUE THREAD

**Issue by ching08** [helm/helm#10217]
Output of `helm version`:
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.17"}

`helm deplendecy update` works with the following yaml. However ; I got the following 404 error when replacing version `0.0.5` with `~0.0.5`
```yaml
dependencies:
- name: mychart
  version: 0.0.5
  repository: "oci://<reg>/my-charts"
```

Error outuput:

response.status="401 Unauthorized" url="https://<oci_reg>.com/v2/my-charts/mychart/manifests/~0.0.1

Details:
```sh
DEBU[0025] fetch response received                       host=<oci_reg>.com response.header.connection=keep-alive response.header.content-length=208 response.header.content-type="application/json; charset=utf-8" response.header.date="Tue, 05 Oct 2021 18:08:39 GMT" response.header.docker-distribution-api-version=registry/2.0 response.header.server=nginx response.header.set-cookie="sid=4a576152449f39eccf70e2a99a8bf7ae; Path=/; HttpOnly" response.header.www-authenticate= response.header.x-request-id=4dcb03a7-4779-41d3-86cc-82276a7525ae response.status="401 Unauthorized" url="https://<oci_reg>.com/v2/my-charts/mychart/manifests/~0.0.1"
```

**Comment by bacongobbler** [comment]
This is a known limitation with OCI at this time. It does not support semantic version ranges unlike chart repositories. See HIP 6 for more details.
