### ISSUE TITLE
Recreate flag does not work for rollback in the SDK

### ISSUE THREAD

**Issue by talonx** [helm/helm#10215]
This is about the Helm Go SDK. I'm attempting a rollback programmatically. 

Sample code 
```
	rollback := action.NewRollback(actionConfig)
	rollback.Version = targetV
	rollback.Recreate = true
	rollback.Wait = true
	rollback.WaitForJobs = true
	rollback.Timeout = time.Duration(5) * time.Minute
```
The Recreate flag is set to true, the chart gets rolled back to the previous version (targetV is defined previously) but the pods do not get recreated. 

However, the flag --recreate-pods flag works as expected in the helm rollback CLI command. I thought the CLI tool also uses the same codebase, so the behaviour should be identical.

What am I doing wrong?

**Comment by yxxhero** [comment]
@talonx Please show whole code that about rollback.

**Comment by talonx** [comment]
@yxxhero here you go 
```
	settings := cli.New()
	actionConfig := new(action.Configuration)

	if err := actionConfig.Init(settings.RESTClientGetter(), namespace, "secret", func(format string, v ...interface{}) {
		fmt.Sprintf(format, v)
	}); err != nil {
		handleErr("Failed to create the actionConfig", err)
	}

	rollback := action.NewRollback(actionConfig)
	//https://pkg.go.dev/helm.sh/helm/v3@v3.7.0/pkg/action#Rollback
	rollback.Version = max - 1
	rollback.Recreate = true
	rollback.Wait = true
	rollback.WaitForJobs = true
	rollback.Timeout = time.Duration(5) * time.Minute

```

I've left out variable declarations.

**Comment by yxxhero** [comment]
@talonx I see no `Run` method.

**Comment by talonx** [comment]
@yan234280533 sorry I left that out 
```
	if err := rollback.Run(releaseName); err != nil {
		handleErr("Failed to rollback", err)
	}
```

**Comment by talonx** [comment]
"Run" runs fine and the rollback also happens. What does not happen is the recreation of pods.

**Comment by yxxhero** [comment]
@talonx  You code is right. can you show your charts to reappearance this issue.

**Comment by talonx** [comment]
@yxxhero Thanks for the response. Just to make sure I understand the way the Recreate flag works - it will force restart the pods even if there is no change in the deployment or any of the other K8S resources in the chart, correct?

**Comment by yxxhero** [comment]
yes

**Comment by talonx** [comment]
> yes

Ok. Then it can be easily replicated by a simple nginx chart which has just a Deployment (no Service or ConfigMap required for this experiment). Steps to replicate would be

1. Deploy the chart (Revision 1)
2. Do a helm upgrade without making any changes (Revision 2)
3. Do a rollback using the code above to Revision 1. It will rollback successfully but the pods don't get restarted.

I'm not sure if it's relevant, but this is on GKE `1.20.10-gke.1600`

**Comment by yxxhero** [comment]
@talonx I will test it in freetime.
