### ISSUE TITLE
Command to update chart version

### ISSUE THREAD

**Issue by Moser-ss** [helm/helm#10222]
My organization uses a lot of Javascript and Node.Js and in the npm world, we have the command [`npm version`](https://docs.npmjs.com/cli/v7/commands/npm-version) that help people to update the package version.

Because Helm is a package version looks strange doesn't offer a command to update the chart version.

Does make sense to add this command to the Helm, or should be a plugin? 

If I had the command the expected behaviour will be very similar of what we have in the command `npm version`

**Comment by mattfarina** [comment]
I would suggest starting this as a Helm plugin.

The `helm package` command does have a `--version` flag to set it at the time of packaging. This is where Helm handles that problem.

Note, there is a `helm version` command that shows you version details about Helm itself.
