### ISSUE TITLE
getting some error while adding private nexus repository

### ISSUE THREAD

**Issue by krishnaraman001** [helm/helm#10232]
Getting this below error when i run  the command

**helm repo add nexus https://{company url}/repository/helm-charts/ --username <username> --password <password>**

**error:
index.go:346: skipping loading invalid entry for chart "jp-jobpull-service" "0.5.5.1" from https://{company url}/repository/helm-charts/: validation: chart.metadata.version "0.5.5.1" is invalid
**

Output of `helm version`:
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

please let me know how to fix this issue?

**Comment by mlkmhd** [comment]
@mattfarina 
how can I disable semantic versioning verification? because we use a different versioning scheme
