### ISSUE TITLE
dry-run is missing the namespace for `--namespace=<ns>` CLI resources

### ISSUE THREAD

**Issue by deitch** [helm/helm#10231]
Output of `helm version`:

```
version.BuildInfo{Version:"v3.7", GitCommit:"", GitTreeState:"", GoVersion:"go1.16.9"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5+k3s1", GitCommit:"acad8ef8402021d6a78405c0b4fe420982e5ad1e", GitTreeState:"clean", BuildDate:"2021-09-20T17:40:35Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

(but I get it with all others)

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Any

## Summary

If you run the following command (filling in, of course):

```
helm install --namespace foo chart
```

It will install the resource of `chart`, including injecting the metadata value of `namespace: foo` where the resource is a namespaced resource and has not overridden. That does make sense.

However, if you run:

```
helm install --dry-run --namespace foo chart
```

The manifests for the resources will be produced _without_ the `namespace: foo` metadata in them.

So if your (simplified) template is:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
spec:
  replicas: 1
  ...
```

Then the `helm install --namespace foo` will correctly install the deployment in the namespace `foo`, but `helm install --namespace foo --dry-run`  will return the manifest above unchanged.

Context (probably not all that helpful): I came across this will installing rook-ceph. The operator is simply in a `Deployment` without namespace, expecting the user to run `helm install --namespace <ns>`. 

I dug into the helm code. As far as I can tell, the rendering into manifests occurs [here](https://github.com/helm/helm/blob/932d2a98a2a01c069aaefb25b12c1ece1f1879d5/pkg/action/install.go#L259), which does not take into account the namespace, while the building of the actual resources for the kube client occurs [here](https://github.com/helm/helm/blob/932d2a98a2a01c069aaefb25b12c1ece1f1879d5/pkg/action/install.go#L275). 

Those resources generated at the second step never are used or returned when `i.DryRun == true`, hence it is lost.

**Comment by deitch** [comment]
If I understood you correctly, then the behaviour makes sense. The only confusion is the expectation.

You are saying that the net _effect_ of `helm install --namespace foo somechart` may be similar to:

1. Render all of the templates
2. Inject the namespace into any resources that are namespaced and do not have an explicit namespace
3. Run `kubectl apply resources` (obviously using client-go and not the CLI, etc.)

But that is not what it actually does. What it does is:

1. Render all of the templates
2. Run `kubectl apply -n <ns> resources`

It works this way because:

* it is much easier to take advantage of the client-go's built-in facility for namespacing manifests as they are applied (why reinvent the wheel)
* it allows helm to modify templates _only_ where they are explicitly templated, rather than getting into the hairy (and confusing) business of modifying templates

If I did understand it correctly, then it does make sense. 

The only thing that I would be left to suggest is making some of the docs more explicit around it. Essentially, if you run the equivalent of `helm render` (which doesn't exist, but `helm install --dry-run` is the same thing), the docs should tell you it will not inject namespaces into the manifests, only render the templates, and if you want to inject or get the equivalent of namespace-contexting (I know, "contexting" most certainly is not a real word), then you need to do it separately.

**Comment by bacongobbler** [comment]
Please feel free to make suggestions to the documentation here: https://github.com/helm/helm-www/

We'd appreciate any contributions/suggestions over there.

In the meantime, I'm going to close this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!

**Comment by bacongobbler** [comment]
> Essentially, if you run the equivalent of `helm render` (which doesn't exist, but `helm install --dry-run` is the same thing),

`helm template`?
