### ISSUE TITLE
Cannot revert changes during rollback because rollback hooks are taken from previous revision

### ISSUE THREAD

**Issue by emike922** [helm/helm#10233]
During my tests I found that pre-/post-rollback hooks are already taken from the "target" revision (older chart version).
I was expecting the hooks from the current revision (newer chart version) to be executed, or there to at least be an additional rollback hook type that does that.

For this case, assume that the mentioned old chart is not equipped (does not have a rollback hook) to deal with changes made by the new chart during a rollback. So it **has** to be the new chart reverting them.

Am I missing something obvious?

Output of `helm version`:
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.13", GitCommit:"53c7b65d4531a749cd3a7004c5212d23daa044a9", GitTreeState:"clean", BuildDate:"2021-07-15T20:53:19Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Minikube

**Comment by zonggen** [comment]
Would love to take a look and help finding the solution. Could you provide an example to demonstrate the problem?
