### ISSUE TITLE
--dependency-update does not work with helm upgrade -i

### ISSUE THREAD

**Issue by tgwallenborg** [helm/helm#10239]
Output of `helm version`:
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"0b17c6315e806a66d507e77760a5d60ab5cccfd8", GitTreeState:"clean", BuildDate:"2021-08-30T01:42:22Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS

### Issue
When I try to run `helm upgrade -i --dependency-update` to install a new helm chart --dependency-update does not work.
I get:
_Error: found in Chart.yaml, but missing in charts/ directory: subchart-name_

But it works if I use `helm install chart --dependency-update`

**Comment by tgwallenborg** [comment]
A sample Chart.yaml:

`apiVersion: v2
name: test-service
description: A Helm chart for the testservice

version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: "common-chart"
    version: "0.1.3"
    repository: "https://artifact.net/repository/helm-chart/"`

**Comment by grantral** [comment]
I also have this issue.

Command: `helm version`
<details>
<summary>Output</summary>

```
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}
```
</details>

Command: `HELM_EXPERIMENTAL_OCI=1 helm upgrade test .helm --namespace test --atomic --cleanup-on-fail --create-namespace --dependency-update --install --values .helm/values.yaml --wait-for-jobs`:
<details>
<summary>Output</summary>

```
Getting updates for unmanaged Helm repositories...
...Unable to get an update from the "oci://cr.yandex/helm" chart repository:
object required
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading common from repo oci://cr.yandex/helm
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x185b0da]

goroutine 1 [running]:
helm.sh/helm/v3/internal/experimental/registry.(*Client).Pull(0x0, 0xc0043c8bc0, 0x38, 0x0, 0x0, 0x0, 0x38, 0xc001211558, 0x44f0a5)
helm.sh/helm/v3/internal/experimental/registry/client.go:235 +0x21a
helm.sh/helm/v3/pkg/getter.(*OCIGetter).get(0xc005321b80, 0xc0043c8ac0, 0x37, 0xc0012115f0, 0xc0043c8ac0, 0x37)
helm.sh/helm/v3/pkg/getter/ocigetter.go:57 +0x23b
helm.sh/helm/v3/pkg/getter.(*OCIGetter).Get(0xc005321b80, 0xc0043c8ac0, 0x37, 0xc0022b2ac0, 0x7, 0x8, 0xc005321b80, 0x0, 0x0)
helm.sh/helm/v3/pkg/getter/ocigetter.go:36 +0x77
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo(0xc001211a10, 0xc0022b68c0, 0x37, 0xc0022b68f8, 0x6, 0xc002293590, 0x47, 0x8, 0x0, 0x0, ...)
helm.sh/helm/v3/pkg/downloader/chart_downloader.go:99 +0x142
helm.sh/helm/v3/pkg/downloader.(*Manager).downloadAll(0xc0001ef050, 0xc000186038, 0x1, 0x1, 0x0, 0x0)
helm.sh/helm/v3/pkg/downloader/manager.go:360 +0xd95
helm.sh/helm/v3/pkg/downloader.(*Manager).Update(0xc0001ef050, 0xc0001ef050, 0x1)
helm.sh/helm/v3/pkg/downloader/manager.go:201 +0x1b7
main.newUpgradeCmd.func2(0xc000393180, 0xc0000c9740, 0x2, 0xc, 0x0, 0x0)
helm.sh/helm/v3/cmd/helm/upgrade.go:168 +0x7b7
github.com/spf13/cobra.(*Command).execute(0xc000393180, 0xc0000c9680, 0xc, 0xc, 0xc000393180, 0xc0000c9680)
github.com/spf13/cobra@v1.2.1/command.go:856 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000232a00, 0xc0001860d0, 0x1, 0xc0006abf60)
github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
helm.sh/helm/v3/cmd/helm/helm.go:87 +0x27b
```
</details>

**Comment by Lemmah** [comment]
_Hello, I am a further activity…remove stale, not stale._

**Comment by wreckerbecker** [comment]
I am still facing this issue. `helm upgrade --dependency-update` won't update with local repo.

helm version: v3.10.3+g835b733

```yaml
dependencies:
  - name: partials
    version: 1.0.1
    repository: file://../partials
```

**Comment by noomz** [comment]
I am still facing this issue. `helm upgrade --dependency-update` won't update with local repo.

helm version: v3.10.3+g835b733

```yaml
dependencies:
  - name: common-charts
    version: 1.0.1
    repository: file://../common-charts
```

**Comment by w13915984028** [comment]
Per investigation, the https://github.com/harvester/harvester/issues/3185 is similar to @noomz said, the  `helm upgrade --dependency-update won't update with local repo.`
