### ISSUE TITLE
Should helm be setting the field manager to "helm" instead of "Go-http-client" ?

### ISSUE THREAD

**Issue by red8888** [helm/helm#10240]
Output of `helm version`: `version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"dirty", GoVersion:"go1.15.5"}`

When I deploy will helm I see this: `manager: Go-http-client`

I'm not super well versed in how server-side applies work yet, but isn't this field easily configurable? Shouldn't it be set to "helm"? Feel like it would be more specific than just `Go-http-client` which I'm assuming is the default when using the GO client.

I could be incorrect in how I think this works, but if you apply with kubectl the manager is set to "kubectl"

**Comment by mattfarina** [comment]
Thanks for bringing this up. The last time I looked into this it wasn't actually Helm that was doing this but something else. Could you provide the details on a resource you're seeing this on?

**Comment by red8888** [comment]
Sure! As I said I have to admit my ignorance of SSA, still brushing up on it so not sure if this is desired behavior. 

I use GKE but I believe SSA is enabled by default for all k8s clusters 1.17 and up? So maybe GKE is like reseting this field when I deploy?

Here is a full (scrubbed) manifest of a service deployed to my cluster
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: sxxxx
    cloud.google.com/neg-status: xxxxx
    meta.helm.sh/release-name: xxxxx
    meta.helm.sh/release-namespace: xxxxx
  creationTimestamp: "2021-07-23T16:38:23Z"
  labels:
    app.kubernetes.io/instance: xxxxxx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name:xxxxx
    app.kubernetes.io/version: xxxxx
    application: xxxxxx
    helm.sh/chart:xxxxxx
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:cloud.google.com/neg: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
          f:application: {}
          f:helm.sh/chart: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/name: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: Go-http-client
    operation: Update
    time: "2021-07-23T16:38:23Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:cloud.google.com/neg-status: {}
    manager: glbc
    operation: Update
    time: "2021-07-23T16:38:23Z"
  name: xxxxxx
  namespace: xxxxxxx
  resourceVersion: "108090606"
  selfLink: /api/v1/namespacesxxxxxxx
  uid: xxxxxxx
spec:
  clusterIP: xxxxxx
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: xxxxxx
    app.kubernetes.io/name: xxxxxx
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

```

**Comment by bacongobbler** [comment]
I'm going to start asking dumb questions. Apologies if this is common knowledge.

What is an SSA? What are you referring to when you mention that acronym? Are you referring to "server-side apply"?

For context, Helm does not use server-side apply (yet). It's all client-side. But the output you shared does look like a separate tool is handling the resource. I'm not sure that's coming from Helm other than the `helm.sh/chart:xxxxxx` label. Are you using `helm template` and passing that to something else?

Can you better described how you're using Helm in this context?

**Comment by red8888** [comment]
Forgot about this.

@bacongobbler not managing this with any other tool just using helm for deployments. I thought maybe server side apply is factoring into this, but I am not well versed enough in it to know for sure. 

Im running GKE v1.17. I would be concerned if GKE is using SSA and helm is currently not able to work with it correctly. I'm not seeing deployment errors yet though.
