### ISSUE TITLE
Helm fails to download charts from secured private repository with error 401

### ISSUE THREAD

**Issue by adamko147** [helm/helm#10243]
Starting from helm 3.6.x, helm fails to download charts from private chart repository when authentication is used. The error reported is `401`

let's say I have private repo as 
```
helm repo add private-repo https://private-repo/charts --username <user> --password <pwd>
```
when downloading charts (e.g. helm pull private-repo/mychart) helm shows an error
```
Error: failed to fetch https://private-repo:443/charts/mychart-1.0.0.tgz : 401
```

After looking around the code for a while, it seems to me related to change https://github.com/helm/helm/commit/17ed9c4cd3c61290587a22953e5359af5ecccaa2.

I've tried to test with adding second repository with `:443` port, e.g.
```
helm repo add private-repo2 https://private-repo:443/charts --username <user> --password <pwd>
```
and then 
```
helm pull private-repo2/mychart
```
worked well

Output of `helm version`:
```
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
_Not Relevant_

**Comment by hickeyma** [comment]
@adamko147 Do you mind checking this and see if it works for you.

**Comment by adamko147** [comment]
@zonggen Yes, was looking into that code as well. Unfortunately golang's `url.Parse` does not deald with defaults, so it parses `https://private-repo` as `Scheme=="http" and `Host=="private-repo" while for `https://private-repo:443` it's `Scheme=="https"` and `Host=="private-repo:443".
If you think it's okey, I can try to open PR with following change:
- get `url.Scheme`, `url.Hostname()` and `url.Port()` - Hostname() is without port. Port() is empty if not specified in the url, so set the port to 443 for https scheme and to 80 for http scheme if port was not specified.
- compare scheme, hostname and port in the condition.

I think it should solve the issue without harming the security, as 443 is well defined standard port for https.
Thoughts?

**Comment by zonggen** [comment]
Found a related issue that also had this discussion: https://github.com/helm/helm/issues/9997#issuecomment-893464128
Seems like https://github.com/helm/helm/pull/9886 was created to address this :) Thanks for the explanation!

**Comment by Madhur-Jatiya** [comment]
`resource "helm_release" "openmetadata" {
  name = "openmetadata"
  # repository = "https://github.com/Madhur-Jatiya/helm-demo"
  chart = "https://github.com/Madhur-Nucleusteq/helm-demo/releases/download/Madhur-1.2.1/Madhur-1.2.1.tar.gz"
  namespace = kubernetes_namespace.openmetadata_namespace.id
  timeout   = 1000
  }`
  
  in this code, I am getting this error
  
  
![image](https://github.com/helm/helm/assets/70679523/f36051ab-17bb-4360-bd66-9ebd5f8dba5b)
