### ISSUE TITLE
Helm addes imagePullPolicy to deployment

### ISSUE THREAD

**Issue by joda01** [helm/helm#10252]
Helm adds an imagePullPolicy entry to each deployment. The imagePullPolicy entry is set to **ifNotPresent** when using version tags for the docker images. If the tag is changed back to latest the imagePullPolicy still stays in  **ifNotPresent**. As a result rollout restart of deployments using latest tags will not update the image.

I think helm should not manipulate/set the imagePullPolicy option and let Kubernetes decide.

Output of `helm version`:
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}

Output of `kubectl version`: 
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1+k3s1", GitCommit:"75dba57f9b1de3ec0403b148c52c348e1dee2a5e", GitTreeState:"clean", BuildDate:"2021-05-21T16:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1+k3s1", GitCommit:"75dba57f9b1de3ec0403b148c52c348e1dee2a5e", GitTreeState:"clean", BuildDate:"2021-05-21T16:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
K3OS

**Comment by bacongobbler** [comment]
This is done automatically by Kubernetes. See https://kubernetes.io/docs/concepts/containers/images/#imagepullpolicy-defaulting.

> if you omit the imagePullPolicy field, and you specify the tag for the container image that isn't :latest, the imagePullPolicy is automatically set to IfNotPresent.
