### ISSUE TITLE
Derive Kubeconfig from Service Account

### ISSUE THREAD

**Issue by nWhitehill** [helm/helm#10251]
I wanted to propose adding a new flag that tells helm to derive a kubeconfig by assuming that it is running in a kubernetes pod with a service account that has permissions to deploy the chart.

The main use case for this would be for CI systems. In tools like gitlab, the gitlab runner could have permissions attached to the service account. The running pod could then call helm commands without needing to fetch the kubeconfig or have it already stored in the image. 

The official go client library already supports this functionality and has an [example](https://github.com/kubernetes/client-go/tree/f6ce18ae578c8cca64d14ab9687824d9e1305a67/examples/in-cluster-client-configuration) of loading a configuration based on service account.

**Comment by bacongobbler** [comment]
https://github.com/helm/helm/blob/main/pkg/kube/client.go#L92

https://github.com/helm/helm/blob/f41f46c6c6a1fae459b51a110f76d60f33281f74/pkg/kube/client.go#L102-L104

https://github.com/helm/helm/blob/f41f46c6c6a1fae459b51a110f76d60f33281f74/pkg/action/action.go#L286

There are a few levels of indirection, but Helm does use `kubernetes.NewForConfig` to construct its own kubeconfig. Therefore, it should work in-cluster.

**Comment by nWhitehill** [comment]
@aytekinar the default service account doesn't have enough permissions. You need to create a role binding and role. You can use the built in kubernetes cluster admin role. See: https://kubernetes.io/docs/reference/access-authn-authz/rbac/#default-roles-and-role-bindings

The quickest way to bootstrap it would be to add the following to the same namespace the default service account is in. However, the better option would be to also create a new service account and bind that service account to a role or cluster roll that allows it to deploy only into the specific namespaces you want. Then you would tell your pod to use your new service account.

```yml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: {your namespace}
roleRef:
  kind: ClusterRole
  name: cluster-admin

**Comment by aytekinar** [comment]
Hi @nWhitehill,

Thank you very much for your time and response. Regarding the following comment of yours:

> @aytekinar the default service account doesn't have enough permissions. You need to create a role binding and role. You can use the built in kubernetes cluster admin role. See: https://kubernetes.io/docs/reference/access-authn-authz/rbac/#default-roles-and-role-bindings

I had done the following, which I also mentioned in my comment, which probably slid from your eyes:

```cmd
$ kubectl -n <namespace> create rolebinding --clusterrole=admin --serviceaccount=<namespace>:default admin-sa-default
```

Changing `admin` to `owner` or `cluster-owner` (from Rancher's perspective, I guess) does not make any difference, either.
