### ISSUE TITLE
Obscure bug: Only get warning when using chart as a subchart

### ISSUE THREAD

**Issue by pmorch** [helm/helm#10265]
I only get this warning:

> coalesce.go:199: warning: cannot overwrite table with non table for myfield (map[])

when I use `mychart` as a subchart of another chart. If I use `mychart` directly, I don't get the warning.

I just wanted to report it so it is out there. Feel free to close it if it is too obscure :-)

## Details

The warning occurs because in the chart's `values.yaml`, I have `myfield: {}` that I override with an array. But I only get the warning when used as a subchart.

Say I have a chart that contains `mychart` as a subchart.

In `mychart`'s `values.yaml`, I have:

```yaml
myfield: {}
```

Because I made a mistake, I'm using it like this overriding the object/hash `{}` with an array:
```bash
$ cat custom-direct.yaml 
myfield:
  - 1
  - 2
$ helm template foo -f custom-direct.yaml charts/mychart > /dev/null
```

That is of course wrong, but the interesting thing is that there is no STDERR warning output here.

If I now do it in the parent chart:

```bash
$ cat custom-parent.yaml 
mychart:
  myfield:
    - 1
    - 2
$ helm template foo -f custom-parent.yaml . > /dev/null 
coalesce.go:199: warning: cannot overwrite table with non table for myfield (map[])
```

notice that now I _do_ get a warning, when asking the parent chart to render `mychart` as a subchart.

I expect to always get the warning. Not only when I use `mychart` as a subchart. The annoying thing is that no amount of unit testing of `mychart` will catch this warning until it is used in a larger system.

I've attached [coalesce-bug.tar.gz](https://github.com/helm/helm/files/7392978/coalesce-bug.tar.gz) containing the charts and files used above.

```bash
$ helm version    
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.8", GitCommit:"fd5d41537aee486160ad9b5356a9d82363273721", GitTreeState:"clean", BuildDate:"2021-02-17T12:33:08Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.19) exceeds the supported minor version skew of +/-1
```

K8s provided by Nutanix Karbon
Running in Ubuntu-20.04 under WSL2 on Windows 10.

**Comment by yxxhero** [comment]
@pmorch I will try to solve it. Thanks very much.

**Comment by ahmetkaftan** [comment]
> @pmorch I will try to solve it. Thanks very much.

Hey, any updates?

**Comment by pmorch** [comment]
I don't think this has been resolved, so bump to remove stale label.

**Comment by yxxhero** [comment]
@pmorch Oh. Sorry. I will update it.

**Comment by pmorch** [comment]
Ping to avoid going stale.

**Comment by joejulian** [comment]
It looks like this happens only with subcharts because [this bit of the dependencies merge](https://github.com/helm/helm/blob/663a896f4a815053445eec4153677ddc24a0a361/pkg/chartutil/dependencies.go#L251) and upgrades are the only actions that use the `CoalesceTables` function.

To get this in template (or install) some additional check would need to be made that isn't being made today. I'm not sure where that would live, or what that would look like.
