### ISSUE TITLE
CRD's within templates directory

### ISSUE THREAD

**Issue by cdancy** [helm/helm#10273]
Is there any path that can be taken to get a CRD to install, or overwrite an existing, within a given chart structure? We've got a chart that updates its existing CRDs and need to get those versions into a production system and have helm overwrite they existing versions. This is a 3rd party chart and not ours which is why I'm asking. Hoping there is some way we can repackage the chart to get their CRDs to install and overwrite their existing ones without being skipped.

**Comment by hickeyma** [comment]
@cdancy You can put CRDs into the templates directory like any other Kubernetes resource and it will be rendered and passed to Kubernetes API as usual. As CRDs are cluster resources then putting them in its own chart is best. The management of CRDs in this way are not supported by Helm.

Helm support of CRDs and the reasoning behind it are described in: https://github.com/helm/community/blob/main/hips/hip-0011.md. This document should provide a good insight as it covers the discussion arounds CRDs raised in the last number of years.

Let me know if this helps.

**Comment by Chili-Man** [comment]
hey @hickeyma , I'm confused, so reading this https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-2-separate-charts , it says that the CRDs should be put into a separate chart, but what does that exactly mean? Putting the CRDs in the templates directory?

**Comment by hickeyma** [comment]
@Chili-Man If you want to be able to add templating to your CRD manifests then have a separate chart for your CRD and manage then them separately from the chart that requires the CRD(s).
