### ISSUE TITLE
helm lint error

### ISSUE THREAD

**Issue by codergitcli** [helm/helm#10278]
Output of `helm version`: version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}

**Issue**: With v3.7.1 version of helm, the helm lint command throws error if the template has multiple objects separated with YAML separator like below

    ==> Linting .
    [INFO] Chart.yaml: icon is recommended
    [ERROR] templates/sample.yaml: unable to parse YAML: invalid Yaml document separator: apiVersion: v1

    Error: 1 chart(s) linted, 1 chart(s) failed

**Steps to reproduce:**

helm create lint-issue
vi lint-issue/templates/sample.yaml with below content

```
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: serviceaccount1
  labels:
    {{- include "lint-issue.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: serviceaccount2
  labels:
    {{- include "lint-issue.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
```

helm lint lint-issue

Above command will throw the error.

**NOTE**: 
Everything works fine without error with helm version v3.6.x. 
Also the issue seems to be limited to helm lint. helm template/install seems to be working fine with v3.7.1

**Comment by sincejune** [comment]
can I take on this issue if no one else is working on it?

**Comment by zonggen** [comment]
Can you try to remove the leading dash of the second document? I made a similar mistake before: https://github.com/helm/helm/issues/10149#issuecomment-929205040

```diff
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: serviceaccount1
  labels:
    {{- include "lint-issue.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
- {{- if .Values.serviceAccount.create -}}
+ {{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: serviceaccount2
  labels:
    {{- include "lint-issue.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
```

Hope this helps!

**Comment by laupow** [comment]
> Can you try to remove the leading dash of the second document? 

When working with chart dependencies, patching the template to work with Helm 3.7 isn't often possible.

For instance, we have a chart with dependencies that lints at 3.6.3 but fails on 3.7.x: 

```bash
$ helm version
version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.17.3"}

$ helm lint deploy/
==> Linting deploy/
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/secrets.yaml: unable to parse YAML: invalid Yaml document separator: apiVersion: kubernetes-client.io/v1

Error: 1 chart(s) linted, 1 chart(s) failed

$ helm363 version
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}

$ helm363 lint deploy/
==> Linting deploy/
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, 0 chart(s) failed
```

I think the conclusion is correct: it's a template issue. But unfortunately it manifests while upgrading to Helm 3.7.x and will require upstream changes for some charts.
