### ISSUE TITLE
Multiple installations to different namespaces of the same helm chart with Cluster scoped resources

### ISSUE THREAD

**Issue by DrissiReda** [helm/helm#10283]
I need to install the same helm Chart to different namespaces, so multiple times. The chart contains cluster scoped resources like ClusterRoles or CustomResourceDefinitions. 

The problem is I can only install it once, the second time I have an "already exists not managed by helm" error.

What I've tried:

- Putting CRDs in a separate folder, works well, except that I can't since my CRDs contain helm values and the crds folder doesn't accept templates.
- Using something like this:
```
{{- $crds := lookup "apiextensions.k8s.io/v1" "CustomResourceDefinition" .Release.Namespace "path.to.new.crd" -}}
{{- if not $crds -}}
{{- end }}
```

But this isn't ideal either, because if I install the same helm to the same namespace twice, the resources get deleted, the third time they appear again, fourth they disappear, and so on.

Does anybody have a more elegant solution to this?

**Comment by komalarg2010** [comment]
I am also facing the  same issue with lookup.. resources keeps getting deleted every alternate time with helm upgrade when lookup is used.. is there any solution to this?

**Comment by bacongobbler** [comment]
Have you considered splitting out the cluster-scoped resources to a separate chart?

Basically you're mixing two contexts with your application - you want to install an app to a specific namespace (scoped to a "user" role), but you also want to install globally scoped resources (scoped to a "cluster administrator" role). The two roles directly conflict with each other.

This is also one of the reasons why managing cluster-scoped resources with a helm chart can be difficult. Many users choose to manage these roles separately to work around these issues.

See also [HIP 11](https://github.com/helm/community/blob/main/hips/hip-0011.md) for more context.

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!

**Comment by DrissiReda** [comment]
Another solution that might not be ideal is using the following on the cluster scoped resources that are inside your `lookup` block:

```yaml
  annotations:
    "helm.sh/resource-policy": keep
```

However this means that these resources are no longer managed by Helm.

In my case it doesn't matter since they're CRD instances which means they get cleaned when the CRD that defines them is deleted.
