### ISSUE TITLE
Help for  include function 

### ISSUE THREAD

**Issue by yangvipguang** [helm/helm#10280]
{{ include "toYaml" $value | indent 2 }}

I know the $value is a  variable.

But below, I don't understand well.  The second parameter is a variables or something else?  

 1、 Does the include function pass the template common.affinities.nodes to dict？ I do't understand very well.  
![1635389227(1)](https://user-images.githubusercontent.com/11416887/139177948-15fe300b-33f6-46d4-9c57-6ac8f06a6127.jpg)

2、Does the context  pass to $ variable?
![image](https://user-images.githubusercontent.com/11416887/139178235-fd393814-3f9f-4f96-a480-4838da4bf428.png)

3、is  the dot  .   variable ?
value: {{include "mytpl" . | lower | quote}}

**Comment by yangvipguang** [comment]
@yxxhero   i have read the doc before.But the document description is not particularly clear. Only one example like above. {{ include "toYaml" $value | indent 2 }} .  There is no clear explanation for the first and second cases I asked. 

I don't know if I understand it correctly. For the include function, the first parameter is the template name, and the second parameter is the scope or context. This scope may be：
1、$: root context
2、. : current context
3、Function formatting（dict、list）：Custom context。It's like in a programming language, customizing a function, and then calling other functions in this function scope.

**Comment by yxxhero** [comment]
@yangvipguang You need to write it yourself and verify it. You will understand that if you can't, you can contact me directly by email.
