### ISSUE TITLE
Error: INSTALLATION FAILED: failed to download

### ISSUE THREAD

**Issue by l1z4a** [helm/helm#10285]
Output of `helm version`:
```
$ helm version
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}
```

Output of `kubectl version`:
```
$ sudo k3s kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5+k3s2", GitCommit:"724ef700bab896ff252a75e2be996d5f4ff1b842", GitTreeState:"clean", BuildDate:"2021-10-05T19:59:14Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5+k3s2", GitCommit:"724ef700bab896ff252a75e2be996d5f4ff1b842", GitTreeState:"clean", BuildDate:"2021-10-05T19:59:14Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
$ sudo k3s --version
k3s version v1.21.5+k3s2 (724ef700)
go version go1.16.8
```

Steps to reproduce failure:
* Use a fresh Ubuntu 20.04 server edition installation with packages up-to-date
* `$ curl -sfL https://get.k3s.io | sh -`
* `$ alias k="sudo k3s kubectl"`
* `$ curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3`
* `$ chmod 700 get_helm.sh`
* `$ ./get_helm.sh`

```
Downloading https://get.helm.sh/helm-v3.7.1-linux-amd64.tar.gz
Verifying checksum... Done.
Preparing to install helm into /usr/local/bin
helm installed into /usr/local/bin/helm
```

* `$ helm repo add rancher-stable https://releases.rancher.com/server-charts/stable`
* `k create namespace cattle-system`
* `$ helm repo add jetstack https://charts.jetstack.io`
* `$ export KUBECONFIG=/etc/rancher/k3s/k3s.yaml`
* `$ helm repo update`

```
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "jetstack" chart repository
...Successfully got an update from the "rancher-stable" chart repository
Update Complete. ⎈Happy Helming!⎈
```
* `$ sudo helm install   cert-manager jetstack/cert-manager   --namespace cert-manager   --create-namespace   --version v1.6.0   --set installCRDs=true`

```
Error: INSTALLATION FAILED: failed to download "jetstack/cert-manager" at version "v1.6.0"
```

What can I do to troubleshoot this?

**Comment by zonggen** [comment]
I also tried to reproduce your issue but no error was produced.

```shell
$ helm repo add rancher-stable https://releases.rancher.com/server-charts/stable
"rancher-stable" has been added to your repositories

$ helm repo add jetstack https://charts.jetstack.io
"jetstack" has been added to your repositories

$ k create namespace cattle-system
namespace/cattle-system created

$ helm repo update 
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "jetstack" chart repository
...Successfully got an update from the "rancher-stable" chart repository
...Successfully got an update from the "stable" chart repository
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈

$ helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version v1.6.0 --set installCRDs=true
NAME: cert-manager
LAST DEPLOYED: Tue Nov  9 15:37:27 2021
NAMESPACE: cert-manager
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
cert-manager v1.6.0 has been deployed successfully!

In order to begin issuing certificates, you will need to set up a ClusterIssuer
or Issuer resource (for example, by creating a 'letsencrypt-staging' issuer).

More information on the different types of issuers and how to configure them
can be found in our documentation:

https://cert-manager.io/docs/configuration/

For information on how to configure cert-manager to automatically provision
Certificates for Ingress resources, take a look at the `ingress-shim`
documentation:

https://cert-manager.io/docs/usage/ingress/
```

Environment:
```shell
$ helm version 
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"dirty", GoVersion:"go1.16.6"}

$ k version 
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:39:34Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}

$ minikube version 
minikube version: v1.23.0
commit: 5931455374810b1bbeb222a9713ae2c756daee10
```

**Comment by AminSojoudi** [comment]
I tried this and it worked:
`helm repo update`  and then run the install command. `helm install ------`

**Comment by bacongobbler** [comment]
@l1z4a any updates here?

**Comment by whisp1986** [comment]
I was having issues with this as well.

There is an issue with syntax between the two helm versions (2 and 3 - as its been updated). In the docs (below) the install reference is to version 2.12.1 or higher - The official tutorial for version 3 of helm doesn't exist yet.

https://rancher.com/docs/rancher/v2.0-v2.4/en/installation/resources/advanced/helm2/helm-rancher/

I have found this page which may be helpful (although i've not tried the solution offered):

https://github.com/ibrokethecloud/rancher-helm3

I hope this helps.

**Comment by mickelsonmichael** [comment]
I am having the same issue pulling a chart from a GitLab registry. The yaml file lists the chart and following the URL leads to the expected file, but helm cannot locate the chart. Debug output as follows with proper names redacted:

```
 helm install pis "team/mychart" --debug
install.go:178: [debug] Original chart version: ""
Error: INSTALLATION FAILED: chart "mychart" matching  not found in teamindex. (try 'helm repo update'): no chart version found for mychart-
helm.go:88: [debug] no chart version found for mychart-
helm.sh/helm/v3/pkg/repo.IndexFile.Get
        helm.sh/helm/v3/pkg/repo/index.go:218
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).ResolveChartVersion
        helm.sh/helm/v3/pkg/downloader/chart_downloader.go:247
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo
        helm.sh/helm/v3/pkg/downloader/chart_downloader.go:89
helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart
        helm.sh/helm/v3/pkg/action/install.go:753
main.runInstall
        helm.sh/helm/v3/cmd/helm/install.go:194
main.newInstallCmd.func2
        helm.sh/helm/v3/cmd/helm/install.go:125
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.2.1/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.2.1/command.go:974
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.2.1/command.go:902
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:87
runtime.main
        runtime/proc.go:225
runtime.goexit
        runtime/asm_amd64.s:1371
chart "mychart" matching  not found in team index. (try 'helm repo update')
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).ResolveChartVersion
        helm.sh/helm/v3/pkg/downloader/chart_downloader.go:249
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo
        helm.sh/helm/v3/pkg/downloader/chart_downloader.go:89
helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart
        helm.sh/helm/v3/pkg/action/install.go:753
main.runInstall
        helm.sh/helm/v3/cmd/helm/install.go:194
main.newInstallCmd.func2
        helm.sh/helm/v3/cmd/helm/install.go:125
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.2.1/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.2.1/command.go:974
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.2.1/command.go:902
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:87
runtime.main
        runtime/proc.go:225
runtime.goexit
        runtime/asm_amd64.s:1371
INSTALLATION FAILED
main.newInstallCmd.func2
        helm.sh/helm/v3/cmd/helm/install.go:127
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.2.1/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.2.1/command.go:974
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.2.1/command.go:902
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:87
runtime.main
        runtime/proc.go:225
runtime.goexit
        runtime/asm_amd64.s:1371
```

**Comment by Choppra** [comment]
Hi, fresh install, Debian 10, apt install method.  Running latest k3s and latest helm.  I cannot download any charts.  It goes to immediately fails download.

`$ helm install happy-panda bitnami/wordpress --debug
install.go:178: [debug] Original chart version: ""
Error: INSTALLATION FAILED: repo bitnami not found
helm.go:88: [debug] repo bitnami not found
helm.sh/helm/v3/pkg/downloader.pickChartRepositoryConfigByName
        helm.sh/helm/v3/pkg/downloader/chart_downloader.go:328
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).ResolveChartVersion
        helm.sh/helm/v3/pkg/downloader/chart_downloader.go:213
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo
        helm.sh/helm/v3/pkg/downloader/chart_downloader.go:89
helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart
        helm.sh/helm/v3/pkg/action/install.go:753
main.runInstall
        helm.sh/helm/v3/cmd/helm/install.go:194
main.newInstallCmd.func2
        helm.sh/helm/v3/cmd/helm/install.go:125
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.2.1/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.2.1/command.go:974
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.2.1/command.go:902
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:87
runtime.main
        runtime/proc.go:225
runtime.goexit
        runtime/asm_amd64.s:1371
INSTALLATION FAILED
main.newInstallCmd.func2
        helm.sh/helm/v3/cmd/helm/install.go:127
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.2.1/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.2.1/command.go:974
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.2.1/command.go:902
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:87
runtime.main
        runtime/proc.go:225
runtime.goexit
        runtime/asm_amd64.s:1371`

**Comment by bacongobbler** [comment]
Did you make sure to `helm repo add` the bitnami charts repository? Refer to the docs for more info.

**Comment by Choppra** [comment]
> Did you make sure to `helm repo add` the bitnami charts repository? Refer to the docs for more info.

Yes, this is happening to no matter which repo/chart I attempt to add or pull.

**Comment by joel-simonsson** [comment]
Hi

As far as i can tell I have the same issues as OP and Choppra, I can not download any charts.
I have been searching for an answer but can not find one.

Any updates on this?
Anything I can do to help find the problem.

**Comment by hsiang-ever** [comment]
hi

I have the same issue when using `helm upgrade --install <release-name> <chart-url> --debug` 
There is no any error and warning. And output message shows it upgrade successfully.
```
upgrade.go:154: [debug] updating status for upgraded release for <release-name>
Release "<release-name>" has been upgraded. Happy Helming!
```
And chart repo is stored in gitlab package registry.

I found out that the above command works when deleting some charts of older version.
It's very weird and I have no idea why it works that way.

**Comment by Choppra** [comment]
Tried this.  I have no charts installed.  Clean install fails immediately.

**Comment by cafecrema** [comment]
If anyone have also this problemm make sure that you added the bitnami repro in the sudo context - not in the user context. I cannot use/install packages with helm without sudo (connection error) - but I could install the repos there. So I got the samem errors as OP here.

**Comment by sindhusri16** [comment]
Is there any update on how to solve this issue. I added a repo and installed a chart from the repo and then uninstalled that chart and deleted the pods and services related to it. Now when I'm trying to install a chart, I'm facing this issue, its not installing simple charts from bitnami repo.

**Comment by Choppra** [comment]
I finally figured this out.

Granted I am setting this up in a lab so what I'm recommending isn't recommended for production.  But you can likely figure out what to do.

Create a /.kube/ directory (in the users profile path) and save the kube config to your profile path with the following command

kubectl config view --raw > ~/.kube/config

Also, i setup k3s with a world readable kube config due to all the issues i had with sudo vs not sudo.

I was able to add bitmani's repo and install a Wordpress chart without issue.

This was a huge pain to fix.  I think part of the issue is sudo/root/user context as someone briefly mentioned above.  I took that idea and ran with it.

**Comment by stan-sz** [comment]
We have hit a similar error message for an oci:// helm chart. The tag exists in the ACR and a rerun of the `upgrade --install` command succeeded.

**Comment by stan-sz** [comment]
> That error occurs when Helm fails to download the chart from the repository.
> 
> https://github.com/helm/helm/blob/accf82ba1c5fe32a0004f6ec7fd021b77fddf51f/pkg/action/install.go#L769
> 
> At a high level, `helm install` looks under your config directory for the cached index file for `jetstack`. Helm loads that file, then attempts to find the appropriate version. It then looks at the `urls` field to fetch the chart.
> 

@bacongobbler: The return line you mentioned is not showing the value of `err`, it only bubbles up when `--debug` is passed. Displaying the value of `err` would help nail down the randomness of this problem.

**Comment by jxsl13** [comment]
https://helm.sh/docs/topics/registries/
```shell
export HELM_EXPERIMENTAL_OCI=1
```

**Comment by sbleicher** [comment]
I ran into the same issue when running: 
```
helm install vault hashicorp/vault
```

I updated the permissions on `/etc/rancher/k3s/k3s.yaml` to `644`. Not sure if this change had any actual impact and I do not recommend keeping those permissions. Then I ran `helm install` without a name and it installed:
```
helm install hashicorp/vault --generate-name
```

Doesn't feel like a great fix, but it worked for my use case
