### ISSUE TITLE
helm upgrade with lookup is deleting the resource 

### ISSUE THREAD

**Issue by komalarg2010** [helm/helm#10281]
Output of `helm version`:
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.5", GitCommit:"e338cf2c6d297aa603b50ad3a301f761b4173aa6", GitTreeState:"clean", BuildDate:"2020-12-09T11:18:51Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.5", GitCommit:"e338cf2c6d297aa603b50ad3a301f761b4173aa6", GitTreeState:"clean", BuildDate:"2020-12-09T11:10:32Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
NA

I am creating  few istio CRDs in a helm chart - idea is to create them only if it does not exist. So using lookup was a convenient option. 

 I have used lookup for about 3 resources in this chart 

 one such example: 
{{- if not (lookup "networking.istio.io/v1alpha3" "Gateway" .Release.Namespace .Values.serviceMesh.gateway.name) }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.serviceMesh.gateway.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
{{- range $port := .Values.serviceMesh.gateway.ports }}
  \- port:
      number: {{ $port.internal }}
      name: {{ $port.protocol }}-{{ $port.internal }}
      protocol: {{ $port.protocol }}
    hosts:
    \- "*"
    tls:
      minProtocolVersion: TLSV1_2
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
        - TLS_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_RSA_WITH_AES_256_GCM_SHA384
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key 
{{- end }}
{{- end }}

output Helm install for the first time : (trimmed) 

helm upgrade --install foo /tmp/foo-22.0.69.tgz --namespace=nf1 -f values.yaml --debug
history.go:53: [debug] getting history for release foo
Release "foo" does not exist. Installing it now.
install.go:172: [debug] Original chart version: ""
install.go:189: [debug] CHART PATH: /tmp/foo-22.0.69.tgz 
client.go:122: [debug] creating 5 resource(s)
NAME: foo
LAST DEPLOYED: Thu Oct 28 12:17:06 2021
NAMESPACE: nf1
STATUS: deployed
REVISION: 1
TEST SUITE: None
USER-SUPPLIED VALUES:
...
COMPUTED VALUES:
...
HOOKS:
MANIFEST:
\# Source: foo/templates/gateway.yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: app-gw
  namespace: nf1
spec:
  selector:
    istio: ingressgateway
  servers:
   - port:
      number: 643
      name: https-643
      protocol: https
    hosts:
    - "*"
    tls:
      minProtocolVersion: TLSV1_2
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
        - TLS_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_RSA_WITH_AES_256_GCM_SHA384
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key

\# Source: foo/templates/virtualservice.yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app-vs
  namespace: nf1
  labels:
    release: foo
spec:
  hosts:
    - 10.62.79.98
    - 10.62.79.99
  gateways:
    - app-gw
  http:
    - match:
        - uri:
            prefix: /api/v1/
      route:
        - destination:
            host: appv1.nf1.svc.cluster.local
            port:
              number: 80
      retries:
        attempts: 0

Gateway is successfully created : 
$ kubectl get gw -n nf1
NAME                      AGE
app-gw                    14m
gui-ingress-gw        37h

When we are trying to upgrade to new chart version, gateway gets deleted and not created again 

/usr/local/bin/helm3 upgrade --install foo /tmp/foo-22.0.70.tgz --namespace=nf1 -f values.yaml --debug
history.go:53: [debug] getting history for release foo
upgrade.go:121: [debug] preparing upgrade for foo
upgrade.go:129: [debug] performing update for foo
upgrade.go:301: [debug] creating upgraded release for foo
client.go:187: [debug] checking 2 resources for changes
client.go:236: [debug] Deleting "ext-ingressgw-643" in nf1...
client.go:236: [debug] Deleting "ext-ingressgw-680" in nf1...
client.go:236: [debug] Deleting "app-gw" in nf1...
upgrade.go:136: [debug] updating status for upgraded release for foo
Release "foo" has been upgraded. Happy Helming!
NAME: foo
LAST DEPLOYED: Thu Oct 28 12:35:14 2021
NAMESPACE: nf1
STATUS: deployed
REVISION: 2
TEST SUITE: None
USER-SUPPLIED VALUES:
...
COMPUTED VALUES:
...
HOOKS:
MANIFEST:

\# Source: foo/templates/virtualservice.yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app-vs
  namespace: nf1
  labels:
    release: foo
spec:
  hosts:
    - 10.62.79.98
    - 10.62.79.99
  gateways:
    - app-gw
  http:
    - match:
        - uri:
            prefix: /api/v1/
      route:
        - destination:
            host: appv1.nf1.svc.cluster.local
            port:
              number: 80
      retries:
        attempts: 0

Note that in debug output, Gateway contents are not there and gateway resource is deleted 

$ kubectl get gw -n nf1
NAME               AGE
gui-ingress-gw   37h

If I upgrade the same chart again, gateway  gets created 

/usr/local/bin/helm3 upgrade --install foo /tmp/foo-22.0.70.tgz --namespace=nf1 -f values.yaml --debug
history.go:53: [debug] getting history for release foo
upgrade.go:121: [debug] preparing upgrade for foo
upgrade.go:129: [debug] performing update for foo
upgrade.go:301: [debug] creating upgraded release for foo
client.go:187: [debug] checking 5 resources for changes
client.go:208: [debug] Created a new Service called "ext-ingressgw-643" in nf1
client.go:208: [debug] Created a new Service called "ext-ingressgw-680" in nf1
client.go:208: [debug] Created a new Gateway called "app-gw" in nf1
upgrade.go:136: [debug] updating status for upgraded release for foo
Release "foo" has been upgraded. Happy Helming!
NAME: foo
LAST DEPLOYED: Thu Oct 28 12:43:03 2021
NAMESPACE: nf1
STATUS: deployed
REVISION: 3
TEST SUITE: None
USER-SUPPLIED VALUES:
...

$ kubectl get gw -n nf1
NAME               AGE
app-gw      22m
gui-ingress-gw   38h

Is there any workaround possible for this ?

**Comment by bacongobbler** [comment]
Helm looks at all available templates rendered by the engine. If a template has been removed from the set, then it is assumed that the user requested Helm to delete that resource.

Source:

https://github.com/helm/helm/blob/39fc522ebb77b0e71cae8e809076ab2603263470/pkg/kube/client.go#L266-L286

In other words, when the resource does not exist, `if not (lookup ...)` returns `true`, rendering the resource as a template. But if it DOES exist, then `if not (lookup ...)` returns false, returning an empty template. That explains the behaviour.

Perhaps a better idea would be to use the `crd-install` hook that comes pre-built in Helm. See https://helm.sh/docs/topics/charts_hooks/#the-available-hooks for more details.

**Comment by komalarg2010** [comment]
crd-install is removed with crds folder introduction in helm3.  Also, upgrade of CRDs isn't supported as of now. https://github.com/helm/community/blob/f9e06c16d89ccea1bea77c01a6a96ae3b309f823/architecture/crds.md

Moving these to crds folder is not an option for me..
I am using the lookup for some ExternalName services, secrets as well, mainly lookup for a resource, and if no object is found, lookup returns empty , which I used for checking the existence of an object.. All of this breaks with upgrade.. 

Probably the correct usecase of lookup is to render the object when present and use it to extract specific values. Existence check of lookup shouldn't atleast be used to create the same object..

**Comment by bacongobbler** [comment]
> Existence check of lookup shouldn't atleast be used to create the same object

For the reasons I explained above, in this situation you should not be using `lookup`, yes.

> Also, upgrade of CRDs isn't supported as of now.

Yes. There are a number of issues related to upgrading CRDs that we do not provide support for it. [HIP 11](https://github.com/helm/community/blob/main/hips/hip-0011.md) goes into more detail as to why we cannot provide support.

**Comment by komalarg2010** [comment]
Thanks for response.. 

Will lookup behaviour continue this way or will there be any fix for this?

**Comment by bacongobbler** [comment]
Lookup’s behaviour will not be changing.

**Comment by yue9944882** [comment]
hitting the issue when managing resources w/ `if not lookup..` clause, the resources will be deleted upon the upgrade. IMHO if we can extend/define the resources' lifecycle in the chart e.g. we can mark the resource wrapped by `if not lookup` to be an immutable resource throughout the installed chart's lifecycle, then it will not be deleted unexpectedly.

> Perhaps a better idea would be to use the crd-install hook that comes pre-built in Helm. See https://helm.sh/docs/topics/charts_hooks/#the-available-hooks for more details.

crd-install is very close to the "chart-lifecycle immutable" i said above. but sadly it doesn't support templating. so the workaround doesnt work for us.

**Comment by bacongobbler** [comment]
Closing this issue as the original question raised by the OP has been answered. Thanks!

**Comment by carlos-ffs** [comment]
Hey, Guys!

I was using the exact same approach as in this Issue. In resume, check if the resource was already created and if so not create it again. The main goal with this approach was to make sure other releases that try to create the resource with the same metadata.name would not trigger the expected error of another release owning the resource. 

However, I was having the same problem when executing helm upgrade, where the other resources would get deleted and not recreated again. 

Well, I found a solution for this:
- Add annotations to identify the helm release name like such (I am using my case):
  ``` 
  apiVersion: platform.confluent.io/v1beta1
  kind: ConfluentRolebinding
  metadata:
    name: {{ $name }} 
    namespace: {{ $release.Namespace }}
    annotations:
      meta.helm.sh/release-name: {{ $release.Name }}
      meta.helm.sh/release-namespace: {{ $release.Namespace }}
  ``` 
- Then, check if the _**resource exists and it has the meta.helm.sh/release-name equal to the .Release.Name**_ or _**if the resource doesn't exist at all**_ ($name is the metadata.name that i construct for the resource): 
```
{{- $rolebind := lookup "platform.confluent.io/v1beta1" "ConfluentRolebinding" $release.Namespace $name }}
{{- if or (and $rolebind (eq (index $rolebind.metadata.annotations "meta.helm.sh/release-name") $release.Name)) (not $rolebind) }}
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: {{ $name }} 
  namespace: {{ $release.Namespace }}
  annotations:
    meta.helm.sh/release-name: {{ $release.Name }}
    meta.helm.sh/release-namespace: {{ $release.Namespace }}
.
.
.
{{- end }}
```

With this approach we make sure the helm release that owns the resource will upgrade it accordingly, and if it doesn't exist at all then it will be created.
