### ISSUE TITLE
Installation via `scripts/get` fails if directory /usr/local/bin does not exist

### ISSUE THREAD

**Issue by centic9** [helm/helm#10298]
When installing current version via `scripts/get`, installation fails if the target directory for the binaries does not exist.

At https://github.com/helm/helm/blob/v3.7.1/scripts/get#L141 a simple copy is done without checking if the directory exists. This results in the binary being installed as "/usr/local/bin", i.e. an executable file instead of a directory.

Creating the directory before starting the script makes it work fine.

Output of `helm version`: not installed yet, tried latest master, v3.7.1

FYI, `get-helm-3` uses a slightly different copy-operation which will fail if the bin-directory does not exist.

**Comment by bacongobbler** [comment]
If you set $HELM_INSTALL_DIR prior to running the script, you can change the location where the helm binary will be installed.

That being said this is certainly an interesting bug. What distribution comes without /usr/local/bin being present?

Feel free to work on a patch.

**Comment by bacongobbler** [comment]
A quick fix may be to change line 141 to ` runAsRoot cp "$HELM_TMP_BIN" "$HELM_INSTALL_DIR/$PROJECT_NAME"`. That way it will fail in the case where $HELM_INSTALL_DIR does not yet exist.

**Comment by centic9** [comment]
Sure, I added "PROJECT_NAME" and "TILLER_NAME" via PR #10302 to make the script fail in this (rare) case.

My distribution is a customized minimized image which has some stuff removed, not sure if there are other minimal distributions out there doing the same.
