### ISSUE TITLE
Helm upgrade not working as expected

### ISSUE THREAD

**Issue by areebrtc** [helm/helm#10295]
Issue - 
The helm upgrade with --reuse-values option fails to upgrade if there is any change in schema of new chart. Suppose, the running helm release had a field named as **mykey** and in values.yaml file this fields was set blank as **mykey: ""**. 
Now, in the new chart values.schema.json was introduced and the schema for this parameter was changed to accept either integers or null. During upgrade helm chart reports error about this parameter as **Invalid type. Expected: [integer,null], given: string**. 

The command used to upgrade is as below - 

**helm upgrade ReleaseName NewChartName --reuse-values --set mykey=null** 

Result
Upgrade failed due unexpected type of the updated parameter. 
**Error: UPGRADE FAILED: values don't meet the specifications of the schema(s) in the following chart(s):**
...

Expected
The upgrade should because after --reuse-values option, the parameter (whose schema got changed) is then overridden using --set option in the upgrade command. 

Output of `helm version`: v3.5.4

Output of `kubectl version`: v1.17.1

**Comment by bacongobbler** [comment]
Hi @areebrtc. Do you have a sample chart that can be used to demonstrate your issue?

**Comment by areebrtc** [comment]
Hi @bacongobbler ,

I am working on private helm chart. Right now, I don't have any chart. I have tried with latest helm chart version 3.7.1, the results are still same.

To recreate this issue, please follow the below steps - 
1. Deploy any helm chart without values.schema.json
2. In the same chart, update values.yaml parameter like port number to string (in earlier deployment it was integer, this is just for re-creating the issue)
3. Now, make create values.schema.json for the updated chart, where schema would expect port number as string rather than integer or it could remain null ( "type" : [ "string", "null" ] )
4. Deploy the updated chart, using any of two below command, it will fail

**helm upgrade ReleaseName UpdatedChart --reuse-values --set port=**  

**helm upgrade ReleaseName UpdatedChart --reuse-values --set port=null**

This works fine
**helm upgrade ReleaseName UpdatedChart --reuse-values --set port=\0** 
**helm upgrade ReleaseName UpdatedChart --reuse-values --set port="80"**  

I want to keep this number null as defined in its schema that this parameter can accept a string or null value to it.

**Comment by areebrtc** [comment]
Hi @bacongobbler ,

It is a scenario where the schema of a parameter has been changed in new version a chart. In version 1, the parameter was string type and in version 2, it was changed to integer. I have few queries as upgrade is not working between theses versions. It throws an error saying "Invalid type. Expected: string, given integer". Please note I am using --reuse-values option in upgrade.

My queries -
Does helm allow and support this change ?
Is upgrade possible ? If not, is there any workaround ?

**Comment by areebrtc** [comment]
Closing as no update received after 19 days.
