### ISSUE TITLE
Install dependencies first

### ISSUE THREAD

**Issue by Warxcell** [helm/helm#10292]
Hello, I have project with RDBMS dependency. Same project have pre-install hooks which loads tests data (only for development), then pre-install,pre-upgrade hook which runs migrations (prod) .

First problem is on development - since helm first runs hooks, then installs the chart and dependencies - create-database hook will never succeed, because it requires database running and healthy, but database is installed after the hooks.
Second problem is missing configmap/secrets, because they are not annotated. I managed that with duplicating all the configs with suffix "hook".

But how to overcome the first problem?

**Comment by bacongobbler** [comment]
It sounds like you have an ordering problem - you want the database to be created and running before you load test data and run migrations. You should probably be using a post-install hook instead.

**Comment by Warxcell** [comment]
Ok that makes sense, the only issue is that some services will crash until DB is created... but I guess no easy way to fix this?

**Comment by bacongobbler** [comment]
If you want things to run in sequential order, you can provide a weight to certain hooks.

From https://helm.sh/docs/topics/charts_hooks/#writing-a-hook:

> It is possible to define a weight for a hook which will help build a deterministic executing order.

> Hook weights can be positive or negative numbers but must be represented as strings. When Helm starts the execution cycle of hooks of a particular Kind it will sort those hooks in ascending order.

That way you can have certain hooks (create-database) run prior to other hooks (database migrations).
