### ISSUE TITLE
Stored release could be compressed more efficiently

### ISSUE THREAD

**Issue by armsnyder** [helm/helm#10308]
## Problem

Hi, my team manages a Helm chart for a Kubernetes operator, and we've decided to include our CRDs in the `templates` section of the chart. Our CRDs contain embedded DeploymentSpec types which are quite large.

We are bumping up against the default 1 MB storage limit on the Secret that Helm uses as the default storage backend for releases.

It looks like the way that the `release` payload is constructed has some inefficiencies. Some of these may be more realistic to improve than others, but for completeness sake, this is what we found:

## 1. Payload is base64-encoded twice after compression (33% size increase compared to encoding once)

Running the process in reverse reveals that the payload is base64-encoded twice:

```shell
kubectl get secret sh.helm.release.v1.example-operator.v1 -o=jsonpath='{.data.release}' | base64 --decode | base64 --decode | gzip --decompress > release.json
```

Encoding twice causes a 33% increase in size, comparing:

```shell
helm template ./example-operator | gzip | base64 | wc -c
  641693
```

```shell
helm template ./example-operator | gzip | base64 | base64 | wc -c
  855593
```

## 2. Manifest data is stored as yaml (67% size increase compared to json, even with compression)

The `manifest` key in the stored release JSON contains the entire rendered manifest as a YAML string, which compresses much less efficiently than if the manifest were a JSON string, in cases where you have repeated data at different levels of indentation.

A perfect example of this would be our case where we are embedding Deployment types in our CRDs at differently nested levels in the CRD schema. Because of the different indentation levels in the YAML manifest, gzip has to compress each line and its indentation separately. Whereas, if it were JSON, then gzip could use the same Huffman code for the entire embedded type in each instance where it occurs.

To demonstrate the difference between compressed JSON and compressed YAML:

```shell
helm template ./example-operator | yq eval --output-format=json --indent=0 | gzip | wc -c
  287436
```

```shell
helm template ./example-operator | gzip | wc -c                      
  481267
```

## 3. Chart files are encoded differently than the manifest (??% size increase)

In the decoded `release` JSON, the original files stored under `.chart.templates` and `.chart.files` are represented using base64 encoding. Whereas, the `.metadata` is a YAML string. The difference in encoding means that the strings appear entirely different even though their data is similar. So again, gzip cannot take advantage of the repeated data.

## Version

Output of `helm version`: `version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.17"}`

**Comment by bacongobbler** [comment]
Agreed. There are probably ways in which we can be more efficient with how Helm compresses the content.

For context, helm used to store release metadata in configmaps. Helm had to base-64 encode the metadata to preserve its content. With the migration to Secrets, Kubernetes now also base-64 encodes the content, resulting in the release being base64-encoded twice.

The trick will be trying to maintain backwards compatibility. Because after fixing these issues users will still want to load their old releases generated from helm 3.0 onwards.

My suggestion - should you wish to pursue this - would be to write a HIP and consider working on this as a Helm 4 feature. That way you have the opportunity to make these improvements without being concerned about backwards compatibility.

Hope that helps.

**Comment by armsnyder** [comment]
Still relevant. These asks could be implemented in Helm 3 in a backwards compatible way IMO, albeit with varying degrees of complexity. The base64 one seems the easiest -- just try decoding twice, but allow the second decode to fail.

**Comment by hickeyma** [comment]
I have removed the stale label @armsnyder. Are you able to push a PR to move this along?

**Comment by armsnyder** [comment]
I don't have time this month unfortunately. I'll update this issue again if I start working on something.

**Comment by armsnyder** [comment]
bump still relevant

**Comment by pkandarpa-cs** [comment]
this issue is still relevant. Please re-open?

**Comment by jabbas** [comment]
still revelant
please reopen
