### ISSUE TITLE
oras has supported insecure push, can helm support it ?

### ISSUE THREAD

**Issue by metisy** [helm/helm#10318]
https://github.com/oras-project/oras/pull/122/commits/9441b802a2190e2278000023a891593998cdac66

**Comment by metisy** [comment]
@bacongobbler

**Comment by metisy** [comment]
@bacongobbler

**Comment by metisy** [comment]
https://github.com/oras-project/oras/blob/main/cmd/oras/push.go

**Comment by bacongobbler** [comment]
#6324.
