### ISSUE TITLE
Helm install command not setting port correctly

### ISSUE THREAD

**Issue by sadityalal** [helm/helm#10317]
Hi,

After installing Helm in my centos virtual machine, i tried to create nginx application.
I added the value of targetPort in service.yaml and values.yaml.
After running the command helm install I tried to describe my service as application was not accessible with node ip and node port.
I noticed that there is something wrong with the output:

############################################
Name:                     nginx-chart
Namespace:                default
Labels:                   app.kubernetes.io/instance=nginx-chart
                          app.kubernetes.io/managed-by=Helm
                          app.kubernetes.io/name=nginx-app
                          app.kubernetes.io/version=1.16.0
                          helm.sh/chart=nginx-0.1.0
Annotations:              meta.helm.sh/release-name: nginx-chart
                          meta.helm.sh/release-namespace: default
Selector:                 app.kubernetes.io/instance=nginx-chart,app.kubernetes.io/name=nginx-app
Type:                     NodePort
IP Families:              <none>
IP:                       10.108.89.80
IPs:                      <none>
Port:                     http  80/TCP
TargetPort:               80/TCP
NodePort:                 http  32501/TCP
Endpoints:                192.168.84.133:80
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
################################################

There is http appended with Port and NodePort. due to which my application is not accessible.
Below are my values.yaml and service.yaml files

##############################################
Values.yaml
##############################################
service:
  type: NodePort
  port: 80
  targetPort: 80

##############################################
service.yaml
##############################################
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx.fullname" . }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "nginx.selectorLabels" . | nindent 4 }}
#############################################

Below are the version details
#############################################
- Output of `helm version`:
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}

- Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"clean", BuildDate:"2019-11-13T11:20:18Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"clean", BuildDate:"2019-11-13T11:11:50Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

- Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Centos 7, VirtualBox  
##############################################

Could you please help me with this?

Thanks,
Saurabh

**Comment by bacongobbler** [comment]
Can you please share the chart you are trying to install?

Generally speaking, the chart author writes templates that will populate fields based on the values provided by `--set` or `--values`. Helm has no control how the chart is rendered - it just takes the templates as input, merges all of the provided values, then renders the output.

**Comment by bacongobbler** [comment]
Ah... I see the value the template is looking for is called `.Values.service.port`, but you're providing it as `port`.

Change your values.yaml to 

```
service:
  port: 80
```

To change the "port" value.

Hope this helps.

**Comment by bacongobbler** [comment]
For reference... Using the example you provided I could not reproduce the issue. Here's what I used:

```
$ helm create test-10317
$ cd test-10317
$ rm -rf templates/*
$ rm values.yaml
$ cat << EOF > templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: foo
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
EOF
$ cat << EOF > values.yaml
service:
  type: NodePort
  port: 8080
  targetPort: 80
EOF
```

Here was the output:

```
><> helm template .
---
# Source: test-10317/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: foo
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      name: http
```

**Comment by bacongobbler** [comment]
I'm not sure what you're asking us to fix here... It sounds like an issue with the chart you're attempting to use, in which case you should be opening a ticket against the maintainers of the chart, not Helm.

**Comment by sadityalal** [comment]
Hi, 

I created the chart using below command:

#helm create nginx

And values I have already pasted, I am not sure if I am doing some mistake as I am in learning phase only.
I tried it several times but getting the wrong output :(

**Comment by bacongobbler** [comment]
Can you please explain what was the expected output? When you run `helm install`, what do you expect the output of the rendered template to look like?

**Comment by sadityalal** [comment]
whenever I execute the command:
kubectl describe service nginx-chart
I get the below output:

Name: nginx-chart
Namespace: default
Labels: app.kubernetes.io/instance=nginx-chart
app.kubernetes.io/managed-by=Helm
app.kubernetes.io/name=nginx-app
app.kubernetes.io/version=1.16.0
helm.sh/chart=nginx-0.1.0
Annotations: meta.helm.sh/release-name: nginx-chart
meta.helm.sh/release-namespace: default
Selector: app.kubernetes.io/instance=nginx-chart,app.kubernetes.io/name=nginx-app
Type: NodePort
IP Families:
IP: 10.108.89.80
IPs:
Port: http 80/TCP
TargetPort: 80/TCP
NodePort: http 32501/TCP
Endpoints: 192.168.84.133:80
Session Affinity: None
External Traffic Policy: Cluster
Events:

As you can see: 
Port: http 80/TCP, there is http in front of Port, is it as expected?

Thanks,

**Comment by bacongobbler** [comment]
Yes. Your values.yaml looks like this:

```
service:
  type: NodePort
  port: 80
  targetPort: 80
```

Basically, you're passing the value "80" to the template. If you change the port number in your values.yaml, the rendered output will change to match the value you provided.

Please have a read through the introduction: https://helm.sh/docs/intro/using_helm/#customizing-the-chart-before-installing

Thanks

**Comment by bacongobbler** [comment]
As far as the "http" in front of the port, that is likely the expected output of `kubectl describe`. In other words you should investigate further with the Kubernetes maintainers.

**Comment by sadityalal** [comment]
Thanks for the clarification :)
