### ISSUE TITLE
helm v3 uses deleted dependency: github.com/garyburd/redigo

### ISSUE THREAD

**Issue by mtojek** [helm/helm#10310]
Hi Team,

It looks like helm v3 uses the `distribution/distribution` library in version which still uses `github.com/garyburd/redigo`. The library `garyburd/redigo` seems to be deleted: https://github.com/garyburd/redigo/

```
github.com/garyburd/redigo v0.0.0-20150301180006-535138d7bcd7 h1:LofdAjjjqCSXMwLGgOgnE+rdPuvX9DxCqaHwKy7i/ko=
github.com/garyburd/redigo v0.0.0-20150301180006-535138d7bcd7/go.mod h1:NR3MbYisc3/PwhQ00EMzDiPmrwpPxAn5GI05/YaO1SY=
```

distribution/distribution has switched to gomodule/redigo in this PR: https://github.com/distribution/distribution/pull/3239

**Comment by yxxhero** [comment]
@mtojek PRs is welcome.
