### ISSUE TITLE
How i can create sub-chart from main chart in helm?

### ISSUE THREAD

**Issue by PV-giri** [helm/helm#10319]
Output of `helm version`:

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by yxxhero** [comment]
I need more details. thanks very much. @PV-giri

**Comment by bacongobbler** [comment]
Have you had the chance to read the chart development guide yet? https://helm.sh/docs/topics/charts/
