### ISSUE TITLE
Overriding of Sub Chart Name in the _helpers.tpl in the Parent Chart

### ISSUE THREAD

**Issue by skumarp7** [helm/helm#10329]
Hi, 

Is it possible to override .Chart.Name object of the Subchart from the _helpers.tpl in the parent chart. Basically, we have Chart A which has 2 dependencies Chart B and  Chart C. Each of the chart has its own template functions in their own _helpers.tpl. These template functions uses .Chart.Name which is used to update the common Labels. According to the Helm Best Practices, when the chart is deployed using umbrella chart,  the dependency chart should have the name of umbrella chart. We are unable to override the .Chart.Name or any other Chart object in the parent chart (chart A) as they are only pointing to the Sub Chart's Chart.yaml information. 

{{- define "commonLabelsWithoutChartVersion" -}}
{{- if .Values.common_labels }}
app.kubernetes.io/name: {{ .Chart.Name }}                       //When overrided from Chart A (Parent Chart), it gives the Chart name of subchart (B)
app.kubernetes.io/instance: {{ .Release.Name }}
app.kubernetes.io/component: "Example"
app.kubernetes.io/part-of: {{ .Values.partOf }}
app.kubernetes.io/managed-by: "helm"
{{- end }}
{{- end }}

 
So, Is it possible to override the .Chart.Name or any other .Chart built in object from the parent _helpers.tpl ?

**Comment by bacongobbler** [comment]
No, it is not possible to “rewrite” built-in variables or values passed into the template engine. They act similar to constants.

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!

**Comment by bacongobbler** [comment]
For more info see https://pkg.go.dev/text/template
