### ISSUE TITLE
new "helm wait" command

### ISSUE THREAD

**Issue by nimrodishi** [helm/helm#10321]
Hi,
Couldn't find a way to do this with current options.
For multiple reasons, I'd like to be able to split the `helm install/upgrade --wait` into `helm install/upgrade` and `helm wait` (or something similar).
I want the ability to run the checks that helm would do on that release. Is there any existing option to achieve something similar? If not, are there any design/vision issues with such an option?

If it seems useful, I can look into implementing it, just wanted to get some feedback before diving in.

Thanks!

Output of `helm version`:
```
version.BuildInfo{Version:"v3.6.1", GitCommit:"61d8e8c4a6f95540c15c6a65f36a6dd0a45e7a2f", GitTreeState:"dirty", GoVersion:"go1.16.5"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-21T20:21:49Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
EKS

**Comment by bacongobbler** [comment]
This would be a good candidate for a plugin. See https://helm.sh/docs/topics/plugins/ for more details.
