### ISSUE TITLE
Helm lint does not report api deprecations in k8s 1.21+

### ISSUE THREAD

**Issue by sboschman** [helm/helm#10324]
Output of `helm version`: 3.6 / 3.7

helm 3.7 compiled against client-go 1.22
helm 3.6 compiled against client-go 1.21

Linting a chart with a policy/v1 PodDisruptionBudget or a PodSecurityPolicy (both deprecated in 1.21) should trigger a deprecation warning. But it doesn't...

After some digging through the code I believe the issue is the following:
The k8s version used to run `k8s.io/apiserver/pkg/endpoints/deprecation` is supplied as [const](https://github.com/helm/helm/blob/release-3.6/pkg/lint/rules/deprecations.go#L28). Overriding const values with `ldflags` is not possible and silently fails / does nothing (golang [issue](https://github.com/golang/go/issues/47072)). Hence the deprecation check is always performed against k8s 1.20, and not the expected client-go version defined with [`ldflags`](https://github.com/helm/helm/blob/main/Makefile#L65).

**Comment by bacongobbler** [comment]
re-opening as per https://github.com/helm/helm/pull/10325#issuecomment-973020514

**Comment by Dean-Coakley** [comment]
I think this issue can be closed, fixed in: https://github.com/helm/helm/pull/10370 ?

**Comment by bacongobbler** [comment]
Yes, thank you.
