### ISSUE TITLE
--password flag in helm repo add seems broken

### ISSUE THREAD

**Issue by Olesp** [helm/helm#10328]
Hi,
I'm using [Chartmuseum](https://chartmuseum.com/) as a private helm repo. 
But I've used the Basic auth method to secure the API.
When I want to add the repo I use the command :
`helm repo add chartmuseum https://mycustom.domain.com --username <username> --password <mypassword>`
But I get the following error :
`Error: looks like "https://mycustom.domain.com" is not a valid chart repository or cannot be reached: failed to fetch https://mycustom.domain.com/index.yaml : 401 Unauthorized`

However, when I omit the --password flag I get prompted for it.
When I then type it it proceed and add the repo correctly.
So I think the --password flag doesn't work as it is supposed to.

Output of `helm version`:
`version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"dirty", GoVersion:"go1.16.4"}`

**Comment by bacongobbler** [comment]
Can you please check again with Helm 3.7.1?

**Comment by Olesp** [comment]
I've updated to 3.7.1 and the problem still occurs when providing --password <mypassword> flag

**Comment by alex-petrov-vt** [comment]
Hmm, I just tested with chartmuseum running on localhost with basic auth and `--password` flag worked for me.
Output of `helm version`:
`version.BuildInfo{Version:"v3.7+unreleased", GitCommit:"b6a04cfbd544f0bbeea449129c1497eec8d99e2b", GitTreeState:"dirty", GoVersion:"go1.16.5"}`

**Comment by bacongobbler** [comment]
Okay. Can you please follow up with chartmuseum? I suspect it has something to do with how you set up your server. If there's something else at play within Helm we can look into that further. Thanks!
