### ISSUE TITLE
status stuck pending-upgrade / pending-install when kill / kill -9 / ctrl+c `helm upgrade --install --atomic` 

### ISSUE THREAD

**Issue by SilverChard** [helm/helm#10323]
status stuck pending-upgrade / pending-install when kill / kill -9 / ctrl+c `helm upgrade --install --atomic` 

helm should receive stop signal and rollback upgrade/install?

Output of `helm version`:
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:47:43Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
EKS

**Comment by hickeyma** [comment]
@SilverChard There was work down on handling signalling in 3.7.0. Do you mins checking with the latest version of Helm (3.7.1) to see if you can reproduce this issue?

**Comment by SilverChard** [comment]
![image](https://user-images.githubusercontent.com/9633121/140925917-ffad92cd-d54b-474c-95b0-fd0dd301f485.png)
 
v3.7.1 perfect work! thank you for your patience and help!
