### ISSUE TITLE
How to delete older revision of any release

### ISSUE THREAD

**Issue by jainpratik163** [helm/helm#10339]
we have installed MS using helm and we are upgrading that MS multiple times, now when we are running the helm list command it fails, and when we check we notice it is failing because we have lots of revisions.

so we want to know is there any way we can delete the old revisions and keep only the last few revisions only.

Output of `helm version`:v3.3.0

Output of `kubectl version`: v1.19.0

Cloud Provider/Platform (AKS, GKE, Minikube etc.): OCP/AWS

**Comment by bacongobbler** [comment]
```
><> helm help upgrade | grep -- history
      --history-max int              limit the maximum number of revisions saved per release. Use 0 for no limit (default 10)
```

**Comment by jainpratik163** [comment]
thanks for the info but I doubt if we can delete the old revision of any installed helm.

eg  below are the revision of my MS which we installed now i want to delete revsion from 2-4 , can we do this .
i know we can uninstall whole release but i don't want to do this.

```
2               Mon Aug 23 18:11:56 2021 
3               Mon Aug 23 19:43:38 2021 
4               Wed Aug 25 18:50:40 2021 
5               Thu Sep  2 12:52:54 2021 
6               Fri Sep  3 11:20:03 2021
```

**Comment by zonggen** [comment]
I believe when you do `helm upgrade --history-max=3 $RELEASE $CHART`, it will automatically trim the revision history. In your case, it will result in something like:
```
5               Thu Sep  2 12:52:54 2021 
6               Fri Sep  3 11:20:03 2021
7               Lates timestamp
```

**Comment by jainpratik163** [comment]
without the `helm upgrade` command we cannot delete it?

**Comment by bacongobbler** [comment]
They are stored as secrets in kubernetes. You can just delete them with `kubectl delete`.

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!

**Comment by jainpratik163** [comment]
is there any command where we can delete old revision with a secret we can delete but we should command for doing this.
when we run helm upgrade command with max history it will try to download helm chart and we don't want this.

**Comment by moio** [comment]
I ended up writing a little script to accomplish that

https://gist.github.com/moio/2c9a58cba986a5c771a08de0343d8ced

HTH

**Comment by jainpratik163** [comment]
@moio this script is in ruby , i am looking script in shell.

**Comment by liranfarage89** [comment]
@jainpratik163 
I asked chatGPT to do that:

```sh
#!/bin/bash

# Prints kubectl commands to trim Helm history in excess of the parameter below
# Assumes the default Helm history storage (Secrets)

HISTORY_ENTRIES_TO_RETAIN=2

# Get all namespaces
namespaces=$(kubectl get ns -o name | sed 's/namespace\///g')

secrets_to_drop=()

# Iterate over each namespace
for namespace in $namespaces; do
    # Get all secrets in the namespace
    secrets=$(kubectl get secret --namespace "$namespace" -o name)

    # Iterate over each secret and filter Helm release secrets
    helm_secrets=()
    while IFS= read -r name; do
        if [[ $name =~ ^secret\/(sh\.helm\.release\.v1\..+)\.v([0-9]+)$ ]]; then
            base_name="${BASH_REMATCH[1]}"
            version="${BASH_REMATCH[2]}"
            helm_secrets+=("$namespace|$base_name|$name|$version")
        fi
    done <<< "$secrets"

    # Group secrets by namespace/base_name and sort by version
    if [[ ${#helm_secrets[@]} -gt 0 ]]; then
        IFS=$'\n'
        sorted_secrets=($(printf "%s\n" "${helm_secrets[@]}" | sort -t '|' -k4 -nr))
        unset IFS

        # Remove excess secrets, keeping only the most recent ones
        for i in "${!sorted_secrets[@]}"; do
            if (( i >= HISTORY_ENTRIES_TO_RETAIN )); then
                secrets_to_drop+=("${sorted_secrets[i]}")
            fi
        done
    fi
done

# Print kubectl delete commands for the secrets to drop
for secret_info in "${secrets_to_drop[@]}"; do
    IFS='|' read -r namespace base_name name version <<< "$secret_info"
    echo "kubectl delete secret --namespace $namespace ${name#secret/}"
done
```

**Comment by Zvezdoreel** [comment]
Wrote this one liner, baybe it will be helpful for someone (it deletes all the releases secrets except the currently installed one)

```sh
 IFS=$'\n';for i in $(helm ls --no-headers); do helm status ${i/ */}| grep -E "REVISION:|NAME:" | awk 'BEGIN { ORS=" " }; {print $2}' | awk '{print "oc get secret | grep sh.helm.release.v1." $1 " | grep -v v"  $2}' | bash | awk '{print "oc delete secret "$1}' | bash; done; IFS=$'\n\t '
 ```
