### ISSUE TITLE
Update k8s dependencies to 1.22.3

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#10330]
Dependabot makes PRs for individual dependencies (e.g., [here](https://github.com/helm/helm/pulls?q=is%3Apr+is%3Aopen+label%3Adependencies)). With Kubernetes we need to update all of the dependencies together. That means updating to 0.22.3 across the board in the go.mod file.

**Comment by dperaza4dustbit** [comment]
Looking into this now
