### ISSUE TITLE
Old References to HELM_PLUGIN_SELF

### ISSUE THREAD

**Issue by rwxrob** [helm/helm#10354]
The old plugin `testdata` contains references to `$HELM_PLUGIN_SELF`
instead of `$HELM_PLUGIN_DIR` that mislead beginners looking at the
tests as examples of how to begin (since other official examples are
somewhat lacking).

**Comment by bacongobbler** [comment]
Hmm. I can understand the confusion. Generally speaking we refer users to the [Related Projects](https://helm.sh/docs/community/related/#helm) section.

Feel free to contribute a patch.
