### ISSUE TITLE
Helm doesn't update route config

### ISSUE THREAD

**Issue by chinkung** [helm/helm#10357]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2021-03-14T19:33:08Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.11) exceeds the supported minor version skew of +/-1
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): OpenShift

# Issue

I try to update existing route name "test" to point to new service name test-new-service with targetPort "test-new-tcp" below is correct route information I see from upgrade command with debug mode

```
helm upgrade -i test -f ./config/test/config.yaml ./test/ --history-max 5 --namespace test --wait --timeout 3m --debug
```

Route output from above command
```
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: "test"
  labels:
    app: "test"
    deploymentconfig: "test"
  annotations:
    haproxy.router.openshift.io/hsts_header: max-age=31536000;includeSubDomains;preload
    template.alpha.openshift.io/wait-for-ready: "true"
spec:
  host: "test.com"
  port:
    targetPort: "test-new-tcp"
  tls:
    termination: edge
  to:
    kind: Service
    name: "test-new-service"
    weight: 100
status:
  ingress: []
```

Command is run without any issue
```
Release "test" has been upgraded. Happy Helming!
```

However, the existing route name "test" is not update with new service "test-new-service" but still point to the same service, I believe it should update with new route.

**Comment by bacongobbler** [comment]
From https://docs.openshift.com/container-platform/3.7/rest_api/apis-route.openshift.io/v1.Route.html

> Once a route is created, the host field may not be changed. 

I suspect the same may be true with the `to` field as well. In other words, Helm may be submitting the new manifest to Openshift, but Openshift is refusing the proposed changes.

You could attempt to verify this with either kubectl or the oc commands. Haven’t worked with Openshift all that much but I’d give that a try.
