### ISSUE TITLE
Helm cannot download packages from private github release

### ISSUE THREAD

**Issue by hamza3202** [helm/helm#10360]
I have hosted my helm repository on a private github repository. The index.yaml is a normal file whereas the packages are stored as github release assets. Helm is able to read the index of repository but when it starts to pull the package it fails.

If i do 
```
helm pull <my-package>
``` 
I get a JSON response back from github instead of the tar.gz file and this is apparently because helm downloads the file without specifying the `Accept: application/octet-stream` header.

Is there any way I could instruct helm to pass this header as well?

**Comment by bacongobbler** [comment]
is this similar to https://github.com/helm/helm/issues/9997? How did you set this up?

Do you have a sample repository to test against? It would be great if there was a sample repository that is public which we can fork, then mark as private for testing.

**Comment by hamza3202** [comment]
It is similar but still different
So here is the sample repo https://github.com/hamza3202/helm-charts-demo

There are two branches
- gh-pages
> Uses https://github.com/helm/chart-releaser-action and works fine with public repo. But it doesn't work with private repos because the [URL](https://github.com/hamza3202/helm-charts-demo/blob/3c68f21cc58ebdff80aa888cb8d3c1981259a936/index.yaml#L12) does not work for private repos.

- release 
> This is the same as gh-pages except that I have changed the [URL](https://github.com/hamza3202/helm-charts-demo/blob/69afadafd859c3069fa46d9deed08b836c503459/index.yaml#L12) to release package asset. I got the new link by reading api documentation of github
https://docs.github.com/en/rest/reference/repos#get-a-release-asset

The URL used in release repo works for both public and private repos. For private repos, you just have to pass the `Authorization` header. However it also requires that you specify `Accept: application/octet-stream` header which I believe helm is not providing right now.

P.S to get the correct URL of an asset that is used in release branch you can use this API call https://docs.github.com/en/rest/reference/repos#get-a-release-by-tag-name
The JSON returned should contain asset id at `assets[].id`

**Comment by hamza3202** [comment]
If i can get helm to pass `Accept: application/octet-stream` then I can create a pull request to https://github.com/helm/chart-releaser to use the URL based on API reference. Right now it is using a so called 'browser_download_url` that doesn't work when using CLI with private repos

**Comment by hamza3202** [comment]
@bacongobbler any feedback on this?

**Comment by hamza3202** [comment]
@bacongobbler are we still interested in fixing this?
