### ISSUE TITLE
Broken 3 way merge cases

### ISSUE THREAD

**Issue by distorhead** [helm/helm#10363]
Hi!

There is 2 cases of failed release upgrades with helm, which require manual intervention to fix release integrity, instead of automatically resolving the situation by the 3 way merge.

## Release with a new resource in the chart

1. Chart was successfully deployed.
2. Add new resource into the chart, say sts/mysts. And introduce some error in this custom branch for some already existing resource (not mysts, but some already existing resource).
3. Deploy of the updated chart will fail with an expected error. New resource mysts will be created at this step.
4. Try to upgrade release using previous version of the chart, where mysts resource is not exists and there is no errors in the chart templates. After upgrade introduced error will be repaired as expected, but newly created resource mysts will not be deleted.

## Release with a new field of existing resource in the chart

1. Chart was successfully deployed.
2. Add new field into the existing resource, say field `spec.containers.command` into the deployment/mydeploy, which is intentionally broken command (`command: [ "no-such-cmd" ]` for example).
3. Deploy of the updated chart will fail with an expected error (use `--wait` flag).
4. Next try to upgrade release using previous version of the chart, where there is no broken command field. After upgrade resource in the cluster will still have the broken command field.

Both of these errors occur because helm creates 3 way merge patches not between 1) previous version of the release, 2) current chart templates and 3) current kubernetes resources, but between 1) previous version of the release in the **deployed**  state, 2) current chart templates and 3) current kubernetes resources.

As a result in the first case `sts/mysts` does not treated as a managed resource by the helm, and this resource is not deleted.

In the second case new field `spec.containers.command` does not treated as a managed field by the helm as well, and this field is not deleted.

Solution: create 3wm patches between previous version of the release in whatever state.

**Comment by bacongobbler** [comment]
I believe this was intentional behaviour when we first wrote this up. Following this code path, your chart was successfully deployed to Kubernetes (it was a valid manifest), but you applied a change that caused the app to fail when starting up.

In this case it is expected for the user to issue a `helm rollback` to return back to a known good state before upgrading.

can you please provide a test case to reproduce this issue?

**Comment by bacongobbler** [comment]
Hmm... Perhaps the `--wait` flag is what's tripping the release status to enter a FAILED state. That may cause differing behaviour than what's expected.

**Comment by bacongobbler** [comment]
Marking as a question/support issue until we can determine whether this is a bug or not.

**Comment by distorhead** [comment]
Indeed, I missed `helm rollback` in these scenarios. When using rollback before next upgrade these cases work ok, for example:

1. Successful helm-upgrade.
2. Introduce new field into templates.
3. Failed helm-upgrade.
4. Helm-rollback.
5. Fix templates.
6. Successful helm-upgrade.

The next scenario would not work, though:

1. Successful helm-upgrade.
2. Introduce new field into templates.
3. Failed helm-upgrade.
4. Fix templates.
5. Failed helm-upgrade.
6. Try helm-rollback to successful revision => FAIL.

— after retried helm-upgrade on the 5th step, release enters a broken state and helm-rollback does not help anymore. I think to exit this state you need to introduce broken changes again (step 2), try helm-upgrade again (step 3), then run helm-rollback (step 6), and only then fix templates and try upgrade.

By the way, 3 way merge is a powerful tool, which allows _automatic_ resolution of such cases without even requiring to run helm-rollback. Helm rollback by itself may be useful thing for own purpose — just to rollback to the state, but the requirement to run helm-rollback before upgrade seems not right.

**Comment by bacongobbler** [comment]
> but the requirement to run helm-rollback before upgrade seems not right.

Most people use the `--atomic` flag to automatically issue a `helm rollback` in case the release enters a failed state. We don't have that flag enabled by default to address backwards compatibility concerns, but it's there.
