### ISSUE TITLE
Flag `--kubeconfig` is ignored when file is a bash process substitution `<(echo "$KUBECONFIG_ADMIN")`

### ISSUE THREAD

**Issue by ctison** [helm/helm#10376]
Helm's `--kubeconfig` flag is ignored when the passed file is a [Bash process substitution][2] (e.g. `<(echo "$KUBECONFIG_ADMIN")`)

In a bash on Github Actions [Ubuntu 20.04][1]:
```bash
# $KUBECONFIG_ADMIN is a multiline variable containing a kubeconfig content in YAML format

# Helm ignores the kubeconfig flag
$ helm list --kubeconfig <(echo "$KUBECONFIG_ADMIN")
Error: Kubernetes cluster unreachable: Get "http://localhost:8080/version?timeout=32s": dial tcp [::1]:8080: connect: connection refused

# Kubectl works
$ kubectl --kubeconfig <(echo "$KUBECONFIG_ADMIN") get ns
default
kube-system
[...]

$ echo <(echo "$KUBECONFIG_ADMIN")
/dev/fd/63
```

Output of `helm version`:
```
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```

[1]: https://github.com/actions/virtual-environments/blob/ubuntu20/20211114.1/images/linux/Ubuntu2004-README.md
[2]: https://www.gnu.org/software/bash/manual/bash.html#Process-Substitution

**Comment by bacongobbler** [comment]
Any idea what would cause this issue?

**Comment by bacongobbler** [comment]
For reference, this was discussed in https://github.com/helm/helm/issues/9183 but OP closed the ticket without explanation. [Someone did suggest](https://github.com/helm/helm/issues/9183#issuecomment-822070820) this may be OS-specific.

What OS/bash version are you using?

**Comment by joemiller** [comment]
@bacongobbler I noticed that process substitution with `kubectl` will not work with the `/bin/bash` v3.2.57 that ships with macOS 12. It works fine with bash 5.x from homebrew on macOS or bash 5.x on linux though. This was confusing to debug and I am wondering if other folks are hitting this trap.

**Comment by trallnag** [comment]
I'm experiencing the same issue. What's weird for me is that it works with `kubectl` but not `helm`.

**Comment by bacongobbler** [comment]
@trallnag what version of bash are you using? I know MacOS ships with a very old version of bash... Assuming you're on MacOS perhaps try installing a newer version of bash using Homebrew.
