### ISSUE TITLE
Release newer version to use containerd 1.5.8

### ISSUE THREAD

**Issue by cgchinmay** [helm/helm#10386]
There are some security fixes with containerd v1.5.8. I do see the [PR](https://github.com/helm/helm/pull/10377) has been merged to update it to v1.5.8. 
Requesting to release the helm with this fix

**Comment by zonggen** [comment]
FYI: The next minor release (3.8) mentioned in the PR is scheduled for 19 Jan 2022: https://calendar.google.com/calendar/u/0/embed?src=8tji8e0obp5skr2pval9g55ftk@group.calendar.google.com.

**Comment by bacongobbler** [comment]
Yep! Helm 3.8 is scheduled for release in January. That release will include the PR referenced above.

The Helm Security team performed an audit and did not discover any relevant security concerns with regards to the containerd CVEs, so there is no need to expedite a security patch release for Helm at this time.

Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!

**Comment by cgchinmay** [comment]
Thanks for the update. Btw @bacongobbler here is the containerd release which mentions the fixed CVE: https://github.com/containerd/containerd/releases/tag/v1.5.8
