### ISSUE TITLE
Error on missing keys

### ISSUE THREAD

**Issue by PepijnK** [helm/helm#10388]
Template rendering is one of the most important things that Helm does. It bothers me that there is almost no configuration possible of how to deal with missing values. Currently, the way how to specify a required value is very [cumbersome](https://stackoverflow.com/questions/53866196/how-best-to-say-a-value-is-required-in-a-helm-chart) and drastically pollutes the template with obvious messages. The implicit behavior of falling back to "default" values (like 0 or "") could lead to unpredictable situations that burned me in the past during deployment situations (a miss-spelled value reference was causing the db username not to be provisioned and was to be found out after the deployment).

So it could save a lot of headache to invert the logic, and make missing values error by default. At least make it configurable to be "less strict". Also, with the current set of helm functions, there is always a way to fallback or to conditionally set a value when a value is not present in the map. 

Using helm v3.7.1

**Comment by bacongobbler** [comment]
Helm has [a list of user profiles (roles)](https://github.com/helm/community/blob/main/user-profiles.md) in a priority order. The top role is the "Application Operator". This is someone who takes a chart and installs it. They may not know much about the internals of the chart they are trying to run. This is conceptually similar to a Linux package manager where someone can install an application without knowing how to set it up with systemd, what default features should be enabled, where its config files need to live,  or where to put the binaries. They install an app with `apt install postgresql` and it just works.

Changing the way Helm renders templates and how it handles missing values would constitute a departure from this user profile, as this puts additional burden on the Application Operator to understand what values to set. Going back to the Linux package manager analogy, this is the same as asking the Application Operator to fetch the source code, set the appropriate feature flags with MAKEPKG's `./configure`, compile from source, install everything in the appropriate location and install a new systemd unit.

> I know about `helm lint` but it spews pretty useless:
> `[INFO] Chart.yaml: icon is recommended`

Charts are presented in a chart repository. We made a decision early on that an icon identifying the package was something all chart repositories would require, so we recommend that charts include one. It's very similar to how a browser will fetch a favicon when you hit the webpage for the first time. `helm template` wasn't introduced until much further.

As noted in `helm lint`, it is only a recommendation, and you can safely ignore that message.

**Comment by PepijnK** [comment]
First, my impression was that we could benefit from helm's templating engine by running helm template commands during the deployment step in our ci/cd pipeline. It would be a pity if that use case is not supported. 

Secondly, how could lenient error handling be a good thing for the client? It leads to relying too much on default behavior, sometimes leading to even more complexity and non transparent error situations. For example (to stay in the Linux analogy), you rather would have `rm` to error on the missing argument then that it would do something default like wiping your current directory. By adding the default behavior there is instantly a legacy created of implicit side effects that higher scripts and tools are going to rely on. I reckon the same happened to helm and there is probably no way back without breaking compatibility. 

In order to support those businesses that want to use helm to just render parameterized templates, could we at least add the helm template `strict` option and/or add a `mode` to the linter that will ignore icons and other meta stuff for private repos?

**Comment by StarlessNights** [comment]
I would also expect Helm to fail when encountering undefined values. Just like [Helmfile does](https://helmfile.readthedocs.io/en/latest/writing-helmfile/#missing-keys-and-default-values).

At the very least this should be documented in bold. Right now you have to infer this indirectly from the [required function docs](https://helm.sh/docs/howto/charts_tips_and_tricks/#using-the-required-function).

One of the main points of kubernetes manifests is to be declarative and explicit. This feels like a departure from this principle.

Application Operators not knowing too much about the internals of the chart they are trying to run is exactly the point.
It's not an argument for never changing anything.
