### ISSUE TITLE
Add flag to disable resource print when install/upgrade

### ISSUE THREAD

**Issue by LorisFriedel** [helm/helm#10389]
Hello!

It would be great to have a flag disabling resource print when executing a `helm install/upgrade`, something like --silent, --quiet or --dont-print-resources and only show what's important (the operation exit status). When having a lot of resources that can be big, it generated a lot of unnecessary logs.

Linked to #2478

**Comment by bacongobbler** [comment]
We're happy to review PRs that provide this functionality. #2478 was closed due to inactivity - likely because piping stdout to /dev/null accomplishes the same thing.
