### ISSUE TITLE
Error Installation  

### ISSUE THREAD

**Issue by scorpius81** [helm/helm#10399]
Hi have error when try install KubeApps, first I had Rancher then I removed it 

helm install kubeapps bitnami/kubeapps   --namespace kubeapps   --set ingress.enabled=true   --set ingress.hostname=k8s-kubeappsxxxxxx.xxx.it   --set ingress.annotations."kubernetes\.io/ingress\.class"=nginx 

Error: INSTALLATION FAILED: create: failed to create: Internal error occurred: failed calling webhook "rancher.cattle.io": failed to call webhook: Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/mutation?timeout=10s": service "rancher-webhook" not found

**Comment by bacongobbler** [comment]
Please file issues related to the KubeApps chart with the KubeApps maintainers.

**Comment by scorpius81** [comment]
Hi 

I keep this error with all the charts I try to place with Helm 

helm install --values=ghost-values.yaml stable/ghost --generate-name
WARNING: This chart is deprecated

Error: INSTALLATION FAILED: create: failed to create: Internal error occurred: failed calling webhook "rancher.cattle.io": failed to call webhook: Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/mutation?timeout=10s": service "rancher-webhook" not found

**Comment by bacongobbler** [comment]
You have a webhook installed in your kubernetes cluster. Remove it.

**Comment by scorpius81** [comment]
I have removed everything, can you tell me how to remove it or check if it is present?

thanks a lot

**Comment by scorpius81** [comment]
Ok, I Solved :

kubectl delete MutatingWebhookConfiguration rancher.cattle.io
