### ISSUE TITLE
question: How to use define in if statement

### ISSUE THREAD

**Issue by gxglls** [helm/helm#10395]
Look at a simple example：
```
{{ if eq 1 1 }}
{{ define "lib" }}
a: 1
{{ end }}
{{ end }}
```

Error when executing `helm template`:
`Error: parse error at (clean_chart/templates/test.yaml:2): unexpected <define> in command`

I think use define in if statement is a common scenario, thanks for your help!

**Comment by bacongobbler** [comment]
Not possible according to text/template's documentation on `define`.

From https://pkg.go.dev/text/template#hdr-Nested_template_definitions:

> Template definitions must appear at the top level of the template, much like global variables in a Go program.

In other words, template definitions (`define`) cannot be nested under an `if`. They must be declared at the top level.

If you want to suggest changes to text/template, please submit issues with the Go team.

Thanks!
