### ISSUE TITLE
Proposal: disable values schema validation for charts including a values.schema.json file

### ISSUE THREAD

**Issue by antaloala** [helm/helm#10398]
Even when a chart designer/maintainer has decided to include a ``values.schema.json`` file in the Helm chart he/she releases it could be that the user of that chart (using it directly or as a dependency in an integration/umbrella Helm chart) cannot assure to fulfill the defined schema for the deployment specific values passed to that subchart (e.g. he/she passes a deployment specific values.yaml file to the ``helm install/upgrade`` command applied on that chart, where some "old" Helm parameter removed from the ``values.schema.json`` of a newer version of that (sub)chart still remains).

I think it would be useful to support a new option in ``helm install``, ``helm upgrade``, ``helm lint`` and ``helm template`` allowing to disable the values schema validation (in case a ``values.schema.json`` file is packaged in the target Helm chart or some listed subchart)

**Comment by the-scott-hand** [comment]
Running into this issue now. A helm chart im using has a `values.schema.json` which points to a git repo for some of the values, which unfortunately means I cant helm install the chart without an internet connection unless I untar the helm chart, remove the schema file, and then install. Would be interested in a flag like `--skip-validation` where it does the equivalent of not having the schema file in the chart. Does a flag like this exist?

**Comment by jedcunningham** [comment]
(Just bumping so the stale bot doesn't close this feature request!)

**Comment by jedcunningham** [comment]
(Not stale)

**Comment by Salec** [comment]
Would love to see this implemented

**Comment by lubojr** [comment]
As a developer of charts with linked values schemas I would also want to not prevent my users from failing to install the script when not having internet connection. :+1: for this feature request.

**Comment by JvD-Ericsson** [comment]
Hello, 
I made an attempt to solve this problem. This is my first time contributing so, please let me know if anything is wrong so I can fix.

**Comment by zswanson** [comment]
Can we get a maintainer to review #11510 for integration?
@joejulian ?

**Comment by joejulian** [comment]
Joe is on vacation - VacationBot

**Comment by michbeck100** [comment]
is there any progress on this? In air-gapped evironments this can be crucial.

**Comment by zswanson** [comment]
We've made an in-CI workaround by fetching the chart to our CI agent, inflating it, renaming the json schema file, and then running the helm upgrade with the _local_ chart path rather than the remote.

**Comment by anessi** [comment]
I have created a merge request (https://github.com/helm/helm/pull/12743) that solves this issue, including tests and doc updates. However, it seems to be really hard to get hold of a maintainer to look into it. I have mentioned it on the #helm-dev slack channel, but no luck. I will try again, but maybe you can vote on the PR if you want to see this fixed.

**Comment by tthornton3-chwy** [comment]
@anessi it looks like your PR got approved! I would love to have this merged in (bumped up against this myself earlier). Do you need any help rebasing or anything?

**Comment by anessi** [comment]
> @anessi it looks like your PR got approved! I would love to have this merged in (bumped up against this myself earlier). Do you need any help rebasing or anything?

@tthornton3-chwy : I'd love to merge, but I don't have write permissions, so depend on the maintainers to merge it.
