### ISSUE TITLE
helm plugin install tgz: extracting files from archive

### ISSUE THREAD

**Issue by Connlp** [helm/helm#10402]
Output of `helm version`:  version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}

The self-made tgz plug-in is installed and uninstalled and then installed, the cache directory conflicts.

**Comment by hickeyma** [comment]
@Connlp Do you mins providing more details showing the commands and the error output?
