### ISSUE TITLE
helm lint "Killed"

### ISSUE THREAD

**Issue by NathanDotTo** [helm/helm#10404]
I am trying to debug some templates, so I tried `helm template`, which didn't help much (another story). I then tried `helm lint`, which hung for a minute or so, then returned with `Killed`

```
helm version
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}
```
First with `helm template`, with the output elided `...` up to the error:
```
$ helm template coolsox-microk8s helm --debug -n $LAB --set dockerRepository=$DOCKER_REPO --set labVersion=1.0.0-$USER -f microk8s-helm-values.yaml
install.go:178: [debug] Original chart version: ""
install.go:199: [debug] CHART PATH: .../application/deploy/helm
...
Error: YAML parse error on helm-chart/templates/xx-db-agent-dep.yaml: error converting YAML to JSON: yaml: did not find expected node content
helm.go:88: [debug] error converting YAML to JSON: yaml: did not find expected node content
YAML parse error on helm-chart/templates/xx-db-agent-dep.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
	helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:146
helm.sh/helm/v3/pkg/releaseutil.SortManifests
	helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:106
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
	helm.sh/helm/v3/pkg/action/action.go:165
helm.sh/helm/v3/pkg/action.(*Install).RunWithContext
	helm.sh/helm/v3/pkg/action/install.go:259
main.runInstall
	helm.sh/helm/v3/cmd/helm/install.go:265
main.newTemplateCmd.func2
	helm.sh/helm/v3/cmd/helm/template.go:82
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.2.1/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.2.1/command.go:974
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.2.1/command.go:902
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:87
runtime.main
	runtime/proc.go:225
runtime.goexit
	runtime/asm_amd64.s:1371
```
The error message is not very useful, so I need to dig further, BUT....:
```
$ helm lint helm --debug -n $LAB --set dockerRepository=$DOCKER_REPO --set labVersion=1.0.0-$USER -f microk8s-helm-values.yaml
Killed
$ 
```
Not very helpful, sadly.

**Comment by yxxhero** [comment]
YAML parse error on helm-chart/templates/xx-db-agent-dep.yaml @NathanDotTo

**Comment by NathanDotTo** [comment]
Thank you for your comment @yxxhero. The focus of this issue is that `helm lint` dies without reporting any actionable result. 

That there is a a problem with `xx-db-agent-dep.yaml` is evident, in the abstract, but there is *apparently* no means to actually debug what the underlying concrete cause is. 

In a sense, then, there are really two issues here:

 - That `helm lint` dies without providing any useful output
 -  That there is apparently no means, within the scope of Helm tooling, to debug YAML errors of the kind seen here

The second issue has been widely discussed elsewhere too. I have nothing new to add to the observations of others in that respect.

**Comment by NathanDotTo** [comment]
Similar to #2004
