### ISSUE TITLE
Clarification of `required` function

### ISSUE THREAD

**Issue by tamalsaha** [helm/helm#10419]
From docs, https://helm.sh/docs/howto/charts_tips_and_tricks/

`The required function allows you to declare a particular values entry as required for template rendering. If the value is empty, the template rendering will fail with a user submitted error message.`

I tried `{{ required "Namespace demo is required" (lookup "v1" "Namespace" "" "demo") }}`, where namespace demo does not exist. I did not get the error from required.

Looking at the implementation of `required`, it is clear why. `required` implementation only checks for `nil` or `""`. Should required throw error for any empty value (anything considered false by `if`) ? If not, is there one function that does that?

ref: `empty` https://github.com/Masterminds/sprig/blob/master/docs/defaults.md#empty

**Comment by bacongobbler** [comment]
https://github.com/helm/helm/blob/5d47255a3d6c886850d6c6cbead1b00b204d07b1/pkg/engine/engine.go#L154-L174
