### ISSUE TITLE
bug: `helm repo index` updates each `created` to now in existing index.yaml

### ISSUE THREAD

**Issue by thomassa** [helm/helm#10411]
Given a directory `charts` which contains some charts (.tgz) and an existing `index.yaml` for those charts,
when a new chart file is added to the directory,
and then I run
`helm repo index charts/`
I expect `charts/index.yaml` to gain a new entry for the new chart, and to have no other changes.

Instead, it gains the new entry as expected, but also every existing entry has its `created` value set to the current time, the same as the `created` timestamp of the new entry and the top-level `generated` timestamp.

I wondered if it might help to add the flag
`--merge charts/index.yaml` but it makes no difference.

Output of `helm version`:
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.13", GitCommit:"2444b3347a2c45eb965b182fb836e1f51dc61b70", GitTreeState:"clean", BuildDate:"2021-11-18T02:35:55Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"454b5b515582f8ac8419435dc9c230fc97fb844b", GitTreeState:"clean", BuildDate:"2021-11-01T19:59:05Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}

**Comment by bacongobbler** [comment]
This is all I could find on existing test cases with `helm repo index --merge`:

https://github.com/helm/helm/blob/d83dd95cae27ef95792ebfa0f4dc5ca6d9fda538/pkg/repo/index_test.go#L184-L221

Have a look through `pkg/repo` and see if you find any interesting behaviour.

https://github.com/helm/helm/blob/a499b4b179307c267bdf3ec49b880e3dbd2a5591/pkg/repo/index.go#L253

**Comment by bacongobbler** [comment]
Test case:

```
><> mkdir /tmp/test-10411
><> cd $_
><> mkdir charts
><> cd charts/
><> helm create foo
Creating foo
><> helm package foo
Successfully packaged chart and saved it to: /tmp/test-10411/charts/foo-0.1.0.tgz
><> helm repo index .
><> ls
foo  foo-0.1.0.tgz  index.yaml
><> cat index.yaml
apiVersion: v1
entries:
  foo:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-11-30T07:52:21.176121582-08:00"
    description: A Helm chart for Kubernetes
    digest: c0fecacc95d6b7fa4a56276f9485d9dfeeb77d27a2d35e00718084395a4931e5
    name: foo
    type: application
    urls:
    - foo-0.1.0.tgz
    version: 0.1.0
generated: "2021-11-30T07:52:21.175660493-08:00"
><> helm create bar
Creating bar
><> helm package bar
Successfully packaged chart and saved it to: /tmp/test-10411/charts/bar-0.1.0.tgz
><> cd ..
><> helm repo index charts/ --merge charts/index.yaml
><> cat charts/index.yaml
apiVersion: v1
entries:
  bar:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-11-30T07:54:54.951570194-08:00"
    description: A Helm chart for Kubernetes
    digest: bb1fabcd3077b30fc71e11f6c7a1a6be74d70f8e9b24befe8ed834dc1681219b
    name: bar
    type: application
    urls:
    - bar-0.1.0.tgz
    version: 0.1.0
  foo:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-11-30T07:54:54.951865768-08:00"
    description: A Helm chart for Kubernetes
    digest: c0fecacc95d6b7fa4a56276f9485d9dfeeb77d27a2d35e00718084395a4931e5
    name: foo
    type: application
    urls:
    - foo-0.1.0.tgz
    version: 0.1.0
generated: "2021-11-30T07:54:54.951100929-08:00"
```
