### ISSUE TITLE
Does helm have a division method that can return decimals

### ISSUE THREAD

**Issue by pycgo** [helm/helm#10414]
Output of `helm version`:
helm-v3.7.1
Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

my question:
Does helm have a division method that can return decimals directly? like 11 / 2  return 5.5 ,div is not work.

**Comment by bacongobbler** [comment]
You will want to use [floating point division](https://github.com/Masterminds/sprig/pull/181) for that.

Sprig supports [float point mathematical functions](http://masterminds.github.io/sprig/mathf.html) like `divf 10 2 4`, which is equivalent to `10 / 2 / 4` which returns `1.25`.

**Comment by pycgo** [comment]
> You will want to use [floating point division](https://github.com/Masterminds/sprig/pull/181) for that.
> 
> Sprig supports [floating point mathematical functions](http://masterminds.github.io/sprig/mathf.html) like `divf 10 2 4`, which is equivalent to `10 / 2 / 4` which returns `1.25`.

Thank you very much, this worked！
