### ISSUE TITLE
AAD plug-in configuration 

### ISSUE THREAD

**Issue by vmathpal** [helm/helm#10415]
I have deployed Jenkins using helm chart. Post deployment I have configured azure ad plugin for authentication which works fine however the aad configuration is not persistent across restarts of pod. I have azure file share as pv where /var/Jenkin_home is mounted. Please assist

**Comment by bacongobbler** [comment]
> I have deployed Jenkins using helm chart.

Unless you think you've run into a Helm bug, please file issues related to the usage of a chart with the community members who maintain that chart. In this situation it's likely related to how the chart is rendered rather than a Helm bug. Thanks.
