### ISSUE TITLE
helm harbor charmusem

### ISSUE THREAD

**Issue by shifeichen** [helm/helm#10426]
i use harbor as my chart registry
[root@docker-node ~]# helm repo add --username=myuser--password=123456  myrepo registry.mydomain.com/charts
Error: could not find protocol handler for: 

and 

[root@docker-node ~]# helm chart push registry.mydomain.com/charts/josephChart:0.1.0
The push refers to repository [registry.mydomain.com/charts/josephChart]
ref:     registry.mydomain.com/charts/josephChart:0.1.0
digest:  26bb1fdac0966b7d708abc47d3bff380ff7ec7bd3d9dacf695a3bd7835b64b1b
size:    3.5 KiB
name:    josephChart
version: 0.1.0
Error: unexpected response: 401 Unauthorized

**Comment by zonggen** [comment]
Which Helm version were you using? Here are some of the previous conversations that might help:
- https://github.com/helm/helm/issues/8955
- https://github.com/helm/helm/issues/5861

**Comment by shifeichen** [comment]
hi, i use helm 3.4.1 ,and do following operation


get "Error: unexpected response: 401 Unauthorized"&nbsp;

Chen Shifei

Tel. :+86&nbsp;15828553520


&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "helm/helm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月4日(星期六) 凌晨4:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [helm/helm] helm harbor charmusem (Issue #10426)





 
Which Helm version were you using? Here are some of the previous conversations that might help:
  
#8955
 
#5861
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by luoqiygq** [comment]
这个问题是怎么解决的啊
