### ISSUE TITLE
Please document all default top level helm values so users can create strict json schemas

### ISSUE THREAD

**Issue by red8888** [helm/helm#10423]
Output of `helm version`: `version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"dirty", GoVersion:"go1.15.5"}`

I am defining my schema with `additionalProperties: false`:

```
{
            "$schema": "http://json-schema.org/schema#",
            "title": "My Chart",
            "type": "object",
            "additionalProperties": false,
            ....
```

For validation to pass I needed to add the "global" property and the names of all my chart's dependancies:

```
# chart.yaml
dependencies:
- name: some-dependancy
  repository: https://blah
  version: 1.2.3

# schema
...
"global": {
    "description": "Builtin helm value. Must include in schema for validation to succeed",
    "type": "object"
},
"some-dependancy": {
    "description": "This chart uses XYZ features of this subchart",
    "type": "object"
}
...
```

I actually like defining the dependancies in the schema because it provides another documentation opportunity. The global property is weird but not a big deal.

These values should be clearly documented so users know to add them. And if any additional top level values are added via an update to helm that should be noted in the release because if a minor version added a new value my validation would fail.

**Comment by mattfarina** [comment]
I'm sorry but I didn't see a question or a specific feature request. Is there something you're looking for from the Helm project?

**Comment by hickeyma** [comment]
@red8888 Are you looking for chart creators/maintainers to document their values?
