### ISSUE TITLE
Consider provide a way to use internal registry by mirroring all the images to avoid docker pull limit (without overriding templates)

### ISSUE THREAD

**Issue by Dentrax** [helm/helm#10437]
**Motivation**

Docker Hub limits the number of Docker image downloads (“pulls”) based on the account type of the user pulling the image. [^1]

Assume the following example:
```bash
$ helm repo add falcosecurity https://falcosecurity.github.io/charts
$ helm upgrade --install falco falcosecurity/falco
```

As we see the following image spec, we're pulling the exact image: `docker.io/falcosecurity/falcosidekick:2.24.0`
```
image:
  registry: docker.io
  repository: falcosecurity/falcosidekick
  tag: 2.24.0
  pullPolicy: IfNotPresent
```

We are running a thousand of Kubernetes clusters. The most unpleasant thing that we have to do after each chart update is to pull the all images (with versions) and push to internal registry. Finally, we have to replace all the image `registry` to point to our registry as follows:
```
image:
  registry: ${IMAGE_REGISTRY}
  ...
```

To make the quality of life better, we should get rid of this chore job without mutating the image spec directly. Here is the example usage:

BEFORE:
```bash
# 1. repo add
$ helm repo add falcosecurity https://falcosecurity.github.io/charts
# 2. check the new chart's template after each release
# 3. find and replace `image` fields to point internal registry
# 4. pass a `-f` flag to override all `image` fields
# 5. finally, install
$ helm upgrade --install falco falcosecurity/falco -f templates/falco_values_override.yml
```

PROPOSAL:
```bash
# 1. repo add
$ helm repo add falcosecurity https://falcosecurity.github.io/charts
# 2. pull the all necessary images
$ helm copy images --from falcosecurity/falco --to registry.my-internal-gitlab.com
# -or-
# If the --mirror-images-to flag is specified, Helm will copy (mirror) all
# the necessary images that provided in templates
$ helm pull falcosecurity/falco --mirror-images-to registry.my-internal-gitlab.com
# 3. we didn't mutate `image` fields, helm should use the given `--registry`
$ helm upgrade --install falco falcosecurity/falco --registry registry.my-internal-gitlab.com
```

Any thoughts, alternative ways, feedback would be greatly appreciated!

cc: @f9n @developer-guy @necatican

[^1]: https://docs.docker.com/docker-hub/download-rate-limit

**Comment by mattfarina** [comment]
I love the idea of being able to inspect a chart for the images and then copy them from one registry to another. There are many uses for this beyond the Docker Hub limits.

That being said, this is the type of feature we suggest as a stand alone tool or as a plugin. There is a fair amount of complexity that would need to be worked out. And, it's all for a limited set of users. Many people don't use Docker Hub and that group is increasing in size.

This is also a difficult problem. How do you discover the images in the manifests to copy them or replace them? For the Kubernetes built-in resources it would be possible to know their locations. But, we also have to deal with Custom Resources and there is no way to know all of the different schemas and where images are specified with those.

This would also introduce a change in Helm beyond the image handling. That is altering the generated manifests to replace the old registries with a new one.

I would love to see this problem tackled but I think it needs to happen as a separate project where the complexity can be tackled apart from the rest of what Helm is doing.
