### ISSUE TITLE
Feature request: overall timeout option 

### ISSUE THREAD

**Issue by caleb15** [helm/helm#10432]
Output of `helm version`: version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): EKS

Helm has a timeout option for individual kubernetes operations, like jobs for hooks. However, it does not have a overall timeout option for the entire upgrade/install. A overall timeout would be useful so helm knows to cancel the deloyment and clean up if it takes too long. Otherwise you run into issues where a supervising process/system (ex: CircleCI) hard-cancels the depoyment after the supervisor's timeout, leaving the release in a bad state, like pending-rollback.

**Comment by caleb15** [comment]
Here's an example of another person who ran into this issue: [Kubernetes slack link](https://kubernetes.slack.com/archives/C0NH30761/p1638264516075700)

**Comment by llu94** [comment]
If it's ok with everyone here I'd like to try my hand at this. Expect something by the end of the weekend out of me. Unless someone has already started working on this.

**Comment by caleb15** [comment]
I haven't started working on it yet, go ahead :)

**Comment by llu94** [comment]
Quick update: I have run into some data races which is always very fun. Will work on this a bit more and maybe try another track if I can't untangle the mess. Stay tuned.

**Comment by llu94** [comment]
@caleb15 @mattfarina I have a functioning implementation of an overall timeout for rollback operations in Helm. Please take a look whenever convenient. If it looks good, I will cut another PR for upgrades and installs.

**Comment by llu94** [comment]
Does the community still want this feature/does anyone want to review my code?
