### ISSUE TITLE
completion prints the "documentation" of the subcommand and is injected on validation

### ISSUE THREAD

**Issue by metal3d** [helm/helm#10438]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}
```

Using "bash" completion (in bash session of course), when I press TAB, the subcommand are well displayed but the help of the subcommand is also printed. Validating the completion prints the subcommand + help.

Exemple:
```
$ source <(helm completion bash)
$ helm s[TAB] 
# then I go to "search" and it injects the below line in the terminal:
helm search\ \ \(search\ for\ a\ keyword\ in\ charts\) 
```

![helm](https://user-images.githubusercontent.com/100080/144878816-17366371-7d16-4202-a6b7-7849ac9cca4b.gif)

**Comment by marckhouzam** [comment]
Hi @metal3d.  This is because you probably use the bash `menu-complete` option.  It is a bug for which a fix is ready: https://github.com/spf13/cobra/pull/1509

Until then what you can do is turn off descriptions for completions:
  `source <(helm completion bash --no-descriptions)`

**Comment by metal3d** [comment]
wooo thank you !

**Comment by metal3d** [comment]
Hello, even with helm `version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}` the description is buggy :(
