### ISSUE TITLE
Memory leak in the upgrade action

### ISSUE THREAD

**Issue by jkmw** [helm/helm#10439]
During the upgrade action we noticed a memory leak which only occurs when helm is used as a "library" and not as a cli tool.

Actually, there are two places:

1. The [`performUpgrade`](https://github.com/helm/helm/blob/1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4/pkg/action/upgrade.go#L260) method waits [at this point](https://github.com/helm/helm/blob/1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4/pkg/action/upgrade.go#L326) for the `rChan`, which is either filled by the `releasingUpgrade` or `handleContext` method. If the result comes from `releasingUpgrade()`, then [`handleContext()`](https://github.com/helm/helm/blob/1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4/pkg/action/upgrade.go#L344) will wait until the context ([`ctx`](https://github.com/helm/helm/blob/1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4/pkg/action/upgrade.go#L347)) is cancelled, which in most cases will never happen and keeps the routine running.

2. If [`ctx`](https://github.com/helm/helm/blob/1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4/pkg/action/upgrade.go#L347) is indeed cancelled, `handleContext()` calls `reportToPerformUpgrade()` which fills the already [consumed `rChan`](https://github.com/helm/helm/blob/1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4/pkg/action/upgrade.go#L339). However, this is never read because the only consumer (`performUpgrade()`) has already returned; The routine remains running forever.

---

Output of `helm version`:
```shell
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}
```

**Comment by zhanghaohao** [comment]
#11805
