### ISSUE TITLE
Cloud helm render the template outside the templates folder but still in charts?

### ISSUE THREAD

**Issue by fred214** [helm/helm#10449]
component
├───Charts.yaml
├───list.yaml
└───templates/
For some reason I want to add {{ if ... }} in list.yaml and render it. but I found the helm can not render the list.yaml for is outside the templates folder, if I put it in the templates folder, it works.
Is there some way that I can render the file outside the templates folder?
Thanks a lot

**Comment by mattfarina** [comment]
It isn't possible to have templates outside of the templates folder. The templates folder and any sub-directories you make within it are where they need to live. There are other files and directories that can be in a chart. So, templates have been scoped to just one part of it.

You can find more details in the docs at https://helm.sh/docs/topics/charts/

**Comment by fred214** [comment]
@mattfarina Thanks for the reply
