### ISSUE TITLE
Problem with Helm search repo

### ISSUE THREAD

**Issue by bd-br** [helm/helm#10448]
Output of `helm version`: v3.7.1

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:59:07Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  EKS

I'm having trouble with helm search repo.  I add the repo with

helm repo add aws-pca https://cert-manager.github.io/aws-privateca-issuer

and then run

helm search repo aws-pca/aws-privateca-issuer

I received the following output

NAME                            CHART VERSION   APP VERSION     DESCRIPTION
aws-pca/aws-pca-issuer          0.1.2           v0.3.1          An addon for cert-manager to sign certificates ...
aws-pca/aws-privateca-issuer    1.0.0           v1.0.0          An addon for cert-manager to sign certificates ...

I am looking to just get information for the aws-privateca-issuer chart

I also tried running 

helm search repo -r '\vaws-pca/aws-privateca-issuer\v'
helm search repo -r 'aws-privateca-issuer'

Is there a way to just get information for the aws-privateca-issuer chart

**Comment by bacongobbler** [comment]
Once you have identified the chart name with `helm search`, you can use `helm show aws-pca/aws-privateca-issuer` to find out more information about the chart.

`helm search repo` [searches for keyword matches](https://github.com/helm/helm/blob/8ca401398d8b6dfd41b46f446abcd5285e219829/cmd/helm/search_repo.go#L115), so there is no way to get information from a single chart as any chart can include that chart's name in their keywords (as you observed).

**Comment by bd-br** [comment]
I'll give that a try.  Thank you!
