### ISSUE TITLE
helm pull oci:// throws tls handshake failure

### ISSUE THREAD

**Issue by kirankumar26** [helm/helm#10452]
When running helm pull oci:// against the private registry we are getting tls handshake failure error. But helm registry login against the private registry is working fine. And also tried hitting the command with --ca-file, --cert-file and --key-file flags but still getting tls handshake failure. Please anyone let me know is there any specific location where I need to place the certs to work "helm pull oci://<private-registry>".

**Comment by kirankumar26** [comment]
hi @bacongobbler, I have stuck with the above mentioned issue to validate helm cli and also I am beginner to helm cli. Please help us.

**Comment by zonggen** [comment]
Hi @kirankumar26, do you always have the TLS handshake error or it's intermittent? Also could you try with `sudo` command?

Refer to some possibly related issues:
 - https://github.com/helm/helm/issues/8172
 - https://github.com/helm/helm/issues/10396

**Comment by kirankumar26** [comment]
Thanks @zonggen, I always have the TLS handshake error while doing helm pull oci://.

**Comment by kirankumar26** [comment]
Hi @zonggen, I have tried running the helm pull oci:// with sudo, but still I am getting remote: SSL handshake failure error. Just want to know is there any specific path to have the certificates to be pick by helm cli. And also just want to know is --ca-file, --cert-file and --key-file flags will work for Artifactory repository in harbor rather than chart repository. Basically I want to pull charts from Artifactory repository where the docker images stores. Please guide me.

**Comment by kirankumar26** [comment]
Hi @zonggen/@bacongobbler, I have tried running the helm pull oci:// with sudo, but still I am getting remote: SSL handshake failure error. Just want to know is there any specific path to have the certificates to be pick by helm cli, please guide me.

**Comment by kirankumar26** [comment]
Hi, Please one help us to fix the error. It's almost a month and we are stuck. basically the helm cli is not able to present the certificate to the remote server and hence resulting handshake failure error while pulling the chart using oci:// scheme.

**Comment by pytimer** [comment]
Can this issue help you? https://github.com/helm/helm/issues/10659#issuecomment-1050695708

**Comment by kirankumar26** [comment]
@pytimer- we have configured our oci registry two way tls, so when we are running helm pull oci:// it is unable to present certificate while handshake with oci registry and throwing remote error: tls: handshake failure. Please can you suggest me anything I am missing here.

we tried helm 3.8.1 and 3.8.2 also

**Comment by pytimer** [comment]
> Can this issue help you? https://github.com/helm/helm/issues/10659#issuecomment-1050695708

Try use this branch, this branch code not merged to helm current release.

**Comment by jimmidyson** [comment]
This is still an issue - can we reopen please?
