### ISSUE TITLE
consider provide a flag to mutate pull untar directory name: --untardirname?

### ISSUE THREAD

**Issue by Dentrax** [helm/helm#10459]
Consider the following example:

```
$ helm pull fluent/fluent-bit --version 0.19.10 --untar --untardir tmp
```

I think it would be better to pull chart files into given `tmp` folder:

```
$ ls ./tmp/fluent-bit
Chart.yaml  README.md   ci          dashboards  templates   values.yaml
```

But helm creates a new folder called `fluent-bit` to put charts into. In this case, `--untardirname` would be a solution to override directory name:

```
$ helm pull fluent/fluent-bit --version 0.19.10 --untar --untardirname tmp
$ ls ./tmp
Chart.yaml  README.md   ci          dashboards  templates   values.yaml
```

Output of `helm version`:
```
version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.17.3"}
```

Output of `kubectl version`:
```
v1.22.3
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): `Kubernetes`

**Comment by Dentrax** [comment]
Any ideas?

**Comment by saylerb** [comment]
I ran into this today, and found myself wanting to do the same thing that Dentrax wanted to do.
