### ISSUE TITLE
add new adapters to sign and verify Helm Charts

### ISSUE THREAD

**Issue by developer-guy** [helm/helm#10451]
At the time of writing this, GnuPG is the only option of signing/verifying Helm Charts. But there are new vendors that might help us to do the same such as [cosign](https://github.com/sigstore/cosign). Also, I believe there will be others in the future, so, we need to design this signing/verifying feature in an extensible way like accepting these adapters via a flag, for example, `--sign cosign|gpg|..`.

WDYT?

Output of `helm version`:

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by mattfarina** [comment]
I agree that embracing other models to sign and verify charts would be great.

Something like this first needs to be a [Helm Improvement Proposal (HIP)](https://github.com/helm/community/tree/main/hips). Is that something you're interested in writing or starting?

**Comment by scottrigby** [comment]
Cross-referencing https://github.com/helm/community/issues/325

**Comment by stevehipwell** [comment]
@scottrigby I don't think these two issues are the same. AFAIK I still can't publish a Helm chart using sigstore instead of GPG and have Helm validate this as part of the standard lifecycle?

**Comment by rhartman93** [comment]
To be more specific, the current helm sigstore implementation relies on GPG signing but hosting material in rekor, which is a weird bridge it feels like. If I understand correctly, if a chart is in an OCI registry, it can just be signed with cosign, and verified all the same, it's just the helm sigstore plugin doesn't integrate with that at all. If helm doesn't want to include cosign directly into the verification, even including this as a valid pattern of signing/verifying charts in the docs around signing would be beneficial I'd say

**Comment by stevehipwell** [comment]
@rhartman93 I sign all of my OCI charts with Cosign (I could sign the non-OCI ones too), so I really just want Helm to make use of these signatures with the verify command.
