### ISSUE TITLE
How to make Helm plugin install work with Azure devops url?

### ISSUE THREAD

**Issue by sarvan24** [helm/helm#10469]
Output of `helm version`:  version.BuildInfo{Version:"v3.6.2", GitCommit:"ee407bdf364942bcb8e8c665f82e15aa28009b71", GitTreeState:"clean", GoVersion:"go1.16.5"} 

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"windows/amd64"} 

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AKS

I have my helm plugin code pushed to a Azure devops repo and I want other developers to install the helm plugin with the following command

`helm plugin install https://dev.azure.com/xyz/_git/my-helm-plugin`

I am getting a Cannot detect VCS error when I do this. How can I make this work? 

According to [this ](https://github.com/helm/helm/issues/7679#issuecomment-591460826)I think I need to provide some hint to helm to detect the type of VCS this is (git). But I am at loss as to how to mention that. It would be good to add a Flag to `helm plugin install ` to explicitly say what VCS it is in cases where it cannot detect it automatically.

**Comment by bacongobbler** [comment]
https://github.com/helm/helm/blob/8ca401398d8b6dfd41b46f446abcd5285e219829/pkg/plugin/installer/installer.go#L66-L75
