### ISSUE TITLE
How do I specify the startup order of multiple CustomResources

### ISSUE THREAD

**Issue by moluzhui** [helm/helm#10464]
I have a project that needs to use `multiple CustomResource` and I want to know the default order of execution and if I can customize the order between them

Output of `helm version`: v2.17

Output of `kubectl version`: 1.18.12

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by bacongobbler** [comment]
The default execution order cannot be modified. Custom resource types are considered "unknown" and therefore are sorted after everything else, and they are sorted alphabetically.

For Helm 3: https://github.com/helm/helm/blob/8ca401398d8b6dfd41b46f446abcd5285e219829/pkg/releaseutil/kind_sorter.go#L141

For Helm 2: https://github.com/helm/helm/blob/a690bad98af45b015bd3da1a41f6218b1a451dbe/pkg/tiller/kind_sorter.go#L141

Closing as Helm 2's support lifecycle ended on November 2020. See [the blog post](https://helm.sh/blog/helm-2-becomes-unsupported/) for more details.
