### ISSUE TITLE
Feature request: Support for "host-gateway" in "hostAliases"

### ISSUE THREAD

**Issue by devedse** [helm/helm#10467]
Output of `helm version`: `v3.6.3`

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Local Docker Desktop for Windows with WSL

### Introduction

Our solution currently consists of quite a significant number of containers. Some of these containers expose API endpoints and we expose these externally.

The different container endpoints call each other through this external connection rather then the internal network traffic to be able to work/test with certificates. (We've mappend dev.coolproject.com to the developers machine's external IP: 192.168.2.123)

For example if container 1 needs some data from container 2 it would do:
https://dev.coolproject.com/container2api/blah

Since hostname resolving falls back to the Windows host running kubernetes it will actually redirect to 192.168.2.123 which is then redirected to the right container (container2).

The problem here is though that every time the developer machine's ip address changes we need to manually update the hosts file.

### Feature request

In docker it's possible to add hostAliases, apparently it's also possible now to add `host-gateway` to refer to the external ip address of the host running docker (See: https://github.com/docker/for-linux/issues/264#issuecomment-965465879)

Currently this doesn't seem to be possible in Helm though. I tried adding it to the Helm charts:
![image](https://user-images.githubusercontent.com/2350015/146372493-6b219c57-4ec4-4159-8412-4897cda2cc22.png)

But running this failed with the following error:

```
Error: UPGRADE FAILED: cannot patch "container2-api" with kind Deployment: Deployment.apps "container2-api" is invalid: spec.template.spec.hostAliases.ip: Invalid value: "host-gateway": must be valid IP address
```

Would it be possible to add this to Helm charts as well?

**Comment by bacongobbler** [comment]
Hi @devedse. The error you are seeing comes straight from Kubernetes. In other words I think you are trying to ask whether a certain feature exists in Kubernetes, not Helm. Helm's responsible for rendering templates and values. Kubernetes processes the rendered templates as manifests.

Have you tried reaching out to the broader Kubernetes community on whether such a feature exists?

**Comment by devedse** [comment]
I'll migrate the issue to the k8s GitHub then 😄
