### ISSUE TITLE
Helm repo_name naming conventions

### ISSUE THREAD

**Issue by sarathsprakash** [helm/helm#10460]
Helm allows you to add a repo with the following naming conventions

`helm repo add hub/library https://hub/chartrepo/library`

It works fine with the search option

`helm search repo hub/library`

However when pulling down images, it fails
```
~> helm pull hub/library/elasticsearch
Error: chart "library/elasticsearch" matching not found in hub index (try 'helm repo update'): no chart found
```

This is because helm can't allow differentiate between repo_name and chart. However In that case it should avoid having the repo_name created with `/` in the first place itself.

**Comment by hickeyma** [comment]
Verified this as a bug. Thanks for raining @sarathsprakash

**Comment by yank1** [comment]
@sarathsprakash @hickeyma , There is a new PR to solve the issue. :-)

**Comment by moustafab** [comment]
ArgoCD (probably incorrectly as per design) uses the url as the name in ArgoCD `v2.2.X` so for a repo hosted at `https://strimzi.io/charts` the add command executed by ArgoCD is `helm repo add https://strimzi.io/charts https://strimzi.io/charts`. This is valid in versions before v3.8.1, so I'm not sure the solution selected (validating on the repo add side) is the best solution to this problem. 

Perhaps trying to split on other `/` characters or doing a first match with the repo list is a way to maintain consistent deterministic behavior even in the case where a user has done something weird like `helm repo add a/b https://a.b` and has a chart `c` while also doing `helm repo add a https://example.com` and then trying `helm pull a/b/c` should always pick repo `a` and chart `b/c` in this case. While in the case that only `helm repo add a/b https://a.b` exists in the list then `helm pull a/b/c` should pull from repo `a/b` the chart `c`. And finally in the case that only `helm repo add a https://example.com` is in the repo list then `helm repo pull a/b/c` should pull from repo `a` the chart `b/c`.
