### ISSUE TITLE
Run Kubernetes API requests (e.g. during helm upgrade) in parallel

### ISSUE THREAD

**Issue by pgilfillan** [helm/helm#10478]
We have a Helm chart which depends on subcharts for all services in our stack, so that we can install everything together. This makes it pretty big, a couple of hundred resources. The problem is that it can take a long time to both install and upgrade (a few minutes) which slows down our CI a lot.

If you add `--debug` to a helm upgrade command for example you see these messages get logged one at a time, maybe half a second apart:
```
client.go:464: [debug] Looks like there are no changes for ConfigMap "test-enclave-redis-scripts"
client.go:464: [debug] Looks like there are no changes for ConfigMap "test-enclave-redis"
client.go:464: [debug] Looks like there are no changes for ConfigMap "test-enclave-redis-health"
client.go:464: [debug] Looks like there are no changes for ConfigMap "test-enclave-open-match-configmap-default"
client.go:464: [debug] Looks like there are no changes for ConfigMap "test-enclave-open-match-configmap-override"
client.go:464: [debug] Looks like there are no changes for ConfigMap "test-enclave-rabbitmq-config"
...
```
which suggests that these checks/upgrades are done sequentially. That seems to match what I'm seeing in the code here https://github.com/helm/helm/blob/8ca401398d8b6dfd41b46f446abcd5285e219829/pkg/kube/client.go#L219, it visits every resource updating them one at a time.

Would it be possible to do this in parallel? Maybe change the `Visit` function to use goroutines, or add a secondary `VisitParallel` function which uses goroutines and then use it in certain spots like above. This would speed up installation/upgrades by over a minute at an estimate. I imagine there would have to be a maximum batch size to prevent Kubernetes API overload on even larger charts.

---

Output of `helm version`: 
`version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}`

Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:59:07Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by edaniels** [comment]
This is still an issue in 2025. Can we do something about this? I have a release with 300+ resources and this takes forever. Moreover, the way upgrade currently works has this visitor traversal happen multiple times. Would it be possible to have a parallelization factor that chunks up the manifest YAML and adds multiple `.Stream()`s into the builder?
