### ISSUE TITLE
Relative filesystem schema references in `values.schema.json` broken

### ISSUE THREAD

**Issue by jedcunningham** [helm/helm#10481]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.17.3"}
```

## Issue

When using a relative filesystem reference in `values.schema.json`, it looks for the file in your CWD, not in the chart directory/tarball.

In practice, this means one cannot use relative references in charts when they may want to (e.g. so you don't need outbound routing to an external/remote schema).

## How to reproduce

Create a new chart:

```
$ helm create demo
Creating demo
$ cd demo
```

Create `values.schema.json`:

```yaml
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "replicaCount": {
            "$ref": "file://./another_schema.json"
        }
    },
    "title": "Values",
    "type": "object"
}
```

And create `another_schema.json`:

```yaml
{
    "$schema": "http://json-schema.org/schema#",
    "type": "integer"
}
```

Now, from `demo`, lint the chart:

```
$ helm lint .
==> Linting .
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, 0 chart(s) failed
```

Now, `cd` up a directory and lint again:

```
$ cd ..
$ helm lint demo
==> Linting demo
[INFO] Chart.yaml: icon is recommended
[ERROR] values.yaml: open ./another_schema.json: no such file or directory
[ERROR] templates/: values don't meet the specifications of the schema(s) in the following chart(s):
demo:
open ./another_schema.json: no such file or directory

Error: 1 chart(s) linted, 1 chart(s) failed
```

The same behavior happens with a tarball:

```
$ cd demo
$ helm package .
Successfully packaged chart and saved it to: ...demo/demo-0.1.0.tgz
$ helm lint demo-0.1.0.tgz 
==> Linting demo-0.1.0.tgz
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, 0 chart(s) failed
$ cd ..
$ helm lint demo/demo-0.1.0.tgz 
==> Linting demo/demo-0.1.0.tgz
[INFO] Chart.yaml: icon is recommended
[ERROR] values.yaml: open ./another_schema.json: no such file or directory
[ERROR] templates/: values don't meet the specifications of the schema(s) in the following chart(s):
demo:
open ./another_schema.json: no such file or directory

Error: 1 chart(s) linted, 1 chart(s) failed
```

**Comment by bacongobbler** [comment]
Hi @jedcunningham. Thanks for finding this bug. We'd appreciate a patch. Thanks!

**Comment by Xitric** [comment]
Hey, my team and I ran into this issue recently, and we are also interested in supporting relative file paths in `$ref`s to avoid repeating ourselves across our many Helm charts and their schemas.

I looked into the library used by Helm to support JSON schemas (xeipuuv/gojsonschema), and it seems to [not officially support relative file paths](https://github.com/xeipuuv/gojsonschema#loaders):

> Local file, using a reference: References use the URI scheme, the prefix (file://) and a _full path_ to the file are required.

However, I wonder if schema IDs could be used to avoid local file references, and instead reference schemas based on an ID ([Loading local schemas](https://github.com/xeipuuv/gojsonschema#loading-local-schemas)). This would entail somehow informing Helm about the schemas upfront such that they can be loaded into memory.

**Comment by hwo411** [comment]
Is there a chance it gets fixed? We also ran into this issue.

In our case there is a workaround, since we always run lint outside the chart directory, but the issue is still annoying.

**Comment by martincomputershare** [comment]
Should not have been closed by the bot.

**Comment by shaun-nx** [comment]
Hi folks.
Would is be possible to re-open the discussion around this?
Would love to see if we can collaborate around a proposal to make this work.
