### ISSUE TITLE
Provide min/max for values

### ISSUE THREAD

**Issue by rrey** [helm/helm#10496]
Hello !

I hope I did not miss anything on the documentation, but I was wondering if one can specify the min/max allowed for an integer from the values.

An easy example would be for `replicas`. If for some reason I have a component that is unable to scale over `3` I'd like the chart to fail if the user provide the value `4` for `replicas`.

Is there something to achieve this that I would have missed ?

**Comment by mattfarina** [comment]
You can include a [jsonSchema](https://helm.sh/docs/topics/charts/#schema-files) file in a chart. Helm will use it to validate the values. Numbers can have max and min values in the schema. This is the method we would recommend.

**Comment by rrey** [comment]
Awesome !
It was in the doc ! Sorry for the noise !
