### ISSUE TITLE
helm Upgrade can not support  apiextv1.CustomResourceDefinition

### ISSUE THREAD

**Issue by shaoshigood** [helm/helm#10495]
Output of `helm version`:
    3.7.2 
Output of `kubectl version`:
v1.19.4

       When I used helm upgrade my release , it failed with error "cannot patch xxxx with kind CustomResourceDefinition:  "" is invalid: patch: Invalid value: "map[metadata:map[.........."

     In the func createPatch (pkg\kube\client.go )，  apiextv1.CustomResourceDefinition is bad dealt.

	_, isUnstructured := versionedObject.(runtime.Unstructured)
	// On newer K8s versions, CRDs aren't unstructured but has this dedicated type
	_, isCRD := versionedObject.(*apiextv1beta1.CustomResourceDefinition)     //  apiextv1.CustomResourceDefinition also is CRD

	if isUnstructured || isCRD {
		// fall back to generic JSON merge patch
		patch, err := jsonpatch.CreateMergePatch(oldData, newData)
		return patch, types.MergePatchType, err
	}

**Comment by tszysong** [comment]
@zonggen please check this issue

**Comment by tianjie1168** [comment]
@zonggen

**Comment by leroyZTE** [comment]
@zonggen zonggen

**Comment by TongX123** [comment]
@zonggen
_, isCRD := versionedObject.(*apiextv1beta1.CustomResourceDefinition)     //  apiextv1.CustomResourceDefinition also is CRD
maybe a bug in code?current code only support **apiextv1beta1**.CustomResourceDefinition,
lack support for the new version **apiextv1**.CustomResourceDefinition.
**as far as I can see, support for old version of k8s will be removed in 1.22+**, please see the warning below:
'Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition’
