### ISSUE TITLE
Generating AES B64 input for the decryptAES function with openssl

### ISSUE THREAD

**Issue by nWhitehill** [helm/helm#10502]
Output of `helm version`: version.BuildInfo{Version:"v3.6.2", GitCommit:"ee407bdf364942bcb8e8c665f82e15aa28009b71", GitTreeState:"dirty", GoVersion:"go1.16.5"}

Output of `kubectl version`: NA

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  NA

I am trying to generate a base64 AES encrypted string to use with helm's decryptAES function. I'm using the following command in openSSL `echo "encryptMe" | openssl aes-256-cbc -e -k examplePassword -nosalt -base64`

When I take the ouput of that command and attempt to render it with the following:
`password: {{ "+oaBHwsZhx6OeWmJDihT4Q==" | decryptAES "examplePassword" }}`
I get the error:  

> Error: (removed)  at <decryptAES "examplePassword">: error calling decryptAES: runtime error: index out of range [-1]

Looking at the sprig library functions here:
https://github.com/Masterminds/sprig/blob/master/crypto.go#L597

It looks like the sprig functions aren't generating the IV the same way open-ssl is, but I'm not sure what value to set as the IV for openssl.

I would ask in the sprig github, but the project appears to be dead.

Any help would be greatly appreciated!

**Comment by bacongobbler** [comment]
> I would ask in the sprig github, but the project appears to be dead.

The project is still active - two of Helm's core maintainers are maintainers of that project. I would suggest continuing the discussion in the relevant repository - there's nothing we can do here other than contribute PRs to sprig.

Thanks.
