### ISSUE TITLE
htpasswd function is incomplete

### ISSUE THREAD

**Issue by Morriz** [helm/helm#10508]
The fact that it is not possible to provide arguments to `htpasswd` has been the cause of many hours of pain. There are apps out there that dictate certain encoding should be chosen, but that is not possible with the current implementation. I saw this upstream remark, but also wanted to insert one here for cross referencing so ppl can be made aware of this:

https://github.com/Masterminds/sprig/issues/32#issuecomment-976406377

**Comment by bacongobbler** [comment]
Thanks for raising this @Morriz. As this issue pertains to functions provided by a third library, I would suggest others continue to follow the ticket upstream for updates. Once a release has been made available, we can update our dependencies accordingly. I imagine introducing a new argument to `htpasswd` may be regarded as a breaking change so it’s likely another function may be introduced such as `htpasswdwithopt`.

For now, let’s stick to tracking the issue upstream. Closing.

**Comment by Morriz** [comment]
Thanks for the update. I don’t think adding arguments breaks anything btw.
