### ISSUE TITLE
Option to download dependency chart of requirements.yaml fom a private helm repo!?

### ISSUE THREAD

**Issue by pankaj-83incs** [helm/helm#10501]
I tried but didn't find any option to download dependency charts from a private repo. Is it even possible? If Yes, please share related docs and if No, any particular reason for that ?

**Comment by yxxhero** [comment]
@pankaj-83incs Can you show a example for this issue? Thanks very much.

**Comment by pankaj-83incs** [comment]
Let me share an example:

https://github.com/codecentric/helm-charts/tree/master/charts/keycloak

Check the dependencies in Chart.yaml of the above chart. I want to get this dependency from my private helm repo secured with user password whereas using the above chart from the public repo.

**Comment by yxxhero** [comment]
Any error logs for this? @pankaj-dahiya

**Comment by pankaj-dahiya** [comment]
HI, @yxxhero This is kind of a question/ feature request ... That I want to download chart dependencies from the private repo.

When I am accessing a private helm repo, I can do that via:

helm repo add private https://raw.githubusercontent.com/CodeWithStu/helm-private-demo/gh-pages/ --username <Your Username> --password <Your PAT token>

Now, my use case - 
I have two charts - 
Chart A - MyPythonApplicationChart
Chart B - MysqlChart

Both are in a private repo, and Chart A is parent to ChartB (Chart A has a dependency on chart B)

I want to pull Chart A and do helm install ChartA. With this, I want it to automatically pull ChartB and install because of the dependency.

**Comment by yxxhero** [comment]
helm dependency --help

**Comment by pankaj-dahiya** [comment]
Can you share me an example command for my use case, I tried all the available options but didn't succeed.

**Comment by yxxhero** [comment]
@pankaj-dahiya can you show your tests. so I can known what should I do.

**Comment by fsniper** [comment]
This issue is also affecting us with Provate Azure Blob Store Containers. 
We are using SAS Tokens for enabling access to this repos and this works flawlessly with any operation except `helm dependency update`.

```
# Failure Scenario:
## If your dependency repository has GET parameters such as SAS_TOKENS, 
## helm dependency update ignores the GET parameters at the package download stage.

 % helm dependency update
Getting updates for unmanaged Helm repositories...
...Successfully got an update from the "https://OURREPOS.blob.core.windows.net/test/upstream/?sp=racwdli&st=2022-06-10T13:09:05Z&se=2022-06-13T21:09:05Z&spr=https&sv=2021-06-08&sr=c&sig=xxxxxxxx" chart repository
Hang tight while we grab the latest from your chart repositories...
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading nginx from repo https://OURREPOS.blob.core.windows.net/test/upstream/?sp=racwdli&st=2022-06-10T13:09:05Z&se=2022-06-13T21:09:05Z&spr=https&sv=2021-06-08&sr=c&sig=xxxxxxxxx
Save error occurred:  could not download https://OURREPOS.blob.core.windows.net/test/upstream/nginx-12.0.3.tgz: failed to fetch https://OURREPOS.blob.core.windows.net/test/upstream/nginx-12.0.3.tgz : 404 The specified resource does not exist.
Error: could not download https://OURREPOS.blob.core.windows.net/test/upstream/nginx-12.0.3.tgz: failed to fetch https://OURREPOS.blob.core.windows.net/test/upstream/nginx-12.0.3.tgz : 404 The specified resource does not exist.



Success scenario:
## If you add the repo into your helm repo config before the dependency update,
## you can succesfully acquire the dependency

 % helm repo add test 'https://OURREPOS.blob.core.windows.net/test/upstream/?sp=racwdli&st=2022-06-10T13:09:05Z&se=2022-06-13T21:09:05Z&spr=https&sv=2021-06-08&sr=c&sig=xxxxxx'
"test" has been added to your repositories

nosni-reverse-proxy % helm dependency update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "test" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading nginx from repo https://OURREPOS.blob.core.windows.net/test/upstream/?sp=racwdli&st=2022-06-10T13:09:05Z&se=2022-06-13T21:09:05Z&spr=https&sv=2021-06-08&sr=c&sig=xxxxxxx
Deleting outdated charts
```
