### ISSUE TITLE
helm pull | repo public.ecr.aws not found

### ISSUE THREAD

**Issue by carloscruzadomatrix** [helm/helm#10509]
Output of `helm version:
version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS

Hi, 
I want to floow the tutorial https://aws.amazon.com/es/blogs/containers/integrate-amazon-api-gateway-with-amazon-eks/.  In one of the steps I need to put the following command:

helm chart pull $CHART_REF
helm chart export $CHART_REF --destination $CHART_EXPORT_PATH

I read that "helm chart pull" doesnt exist more, so I used "helm pull" the CHART_REF are  "public.ecr.aws/aws-controllers-k8s/apigatewayv2-controller:v0.0.8" but when I put the command I hace the following error:

helm pull $CHART_REF
Error: repo public.ecr.aws not found

Can you help me?

**Comment by yxxhero** [comment]
@carloscruzadomatrix Please show the value of $CHART_REF

**Comment by bridgetkromhout** [comment]
Hi, @carloscruzadomatrix! The blog post you are following has some issues. I suggest looking at https://gallery.ecr.aws/aws-controllers-k8s/apigatewayv2-chart instead (referenced from https://gallery.ecr.aws/aws-controllers-k8s/apigatewayv2-controller).

You need to specify the `oci://` part for an oci registry, and currently the version has to be explicit with a flag:
```
$ helm pull oci://public.ecr.aws/aws-controllers-k8s/apigatewayv2-chart --version v0.0.8
Pulled: public.ecr.aws/aws-controllers-k8s/apigatewayv2-chart:v0.0.8
Digest: sha256:299d8b520291ade6d136a7529b7fd44338d58b5b8239813aed97e8fd81ca1f00
```

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!
