### ISSUE TITLE
can  `--post-renderer`  support  assign  the cmd args into  `executable` ?

### ISSUE THREAD

**Issue by tanguofu** [helm/helm#10511]
now helm  `--post-renderer` only accept  the `executable` in `PATH`;  

but it is very  necessary that  the `post-renderer-executable`   worked with some args ,for example change the docker.io registry into private docker registry when deploy the chart without internet access.

can helm can add `args` to assign the args in to  `post-renderer-executable` such as ` --post-renderer-args` 
```
helm install mychart stable/wordpress --post-renderer ./path/to/render_executable --post-renderer-args "--args_to_render_executable  "
````
if this proposal be ok, i d like  to contribute a PR.

**Comment by marckhouzam** [comment]
I believe this is a good idea. It was discussed before in #9047 where you will find some guidance on dealing with backwards-compatibility.

But for those not aware, the current way to pass arguments to the post-renderer is to write a little executable shell script that calls the post-renderer with the arguments, and have helm call that script.

**Comment by tanguofu** [comment]
@marckhouzam  could u review this PR#10514  https://github.com/helm/helm/pull/10514, many thanks
