### ISSUE TITLE
[ERROR] Chart.yaml: version '22-05858181' is not a valid SemVer

### ISSUE THREAD

**Issue by allenjol** [helm/helm#10517]
When I use helm lint chart, i get an error
```console
$ helm lint ${Chart_HOME}/
 ==> Linting ./Chart/chart_name/
 [ERROR] Chart.yaml: version '22-05858181' is not a valid SemVer
 [INFO] Chart.yaml: icon is recommended
 Error: 1 chart(s) linted, 1 chart(s) failed
```
My helm version is:
```console
$ helm version
 version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

I think it's a BUG. How to resolved it?

**Comment by hatati** [comment]
Why do you think it's a bug? It clearly don't adhere to the semantic version specification which states 
> A normal version number MUST take the form X.Y.Z where X, Y, and Z are non-negative integers, and MUST NOT contain leading zeroes. X is the major version, Y is the minor version, and Z is the patch version. Each element MUST increase numerically. For instance: 1.9.0 -> 1.10.0 -> 1.11.0.`
https://semver.org/#spec-item-2

**Comment by allenjol** [comment]
Thank you for you reply @hatati.I understand that my version number is not a standard semantic format. In the past, I have always used this format for the version number of HELM and have not encountered any errors with this version number in the past year. But today the mistake cropped up. I looked at helm's official website and saw no such problems, then I wondered if it was a bug

**Comment by hatati** [comment]
The helm documentation states that the chart version must follow the [ SemVer 2 ](https://semver.org/spec/v2.0.0.html) standard https://helm.sh/docs/topics/charts/#charts-and-versioning. I believe that the actual bug is that the helm linter approved the `22-05858181` version number as you stated. A bug that seems to be resolved. Pursuit of non-semantic Chart versions should not be labeled as a `bug`, but as a `proposal` instead

**Comment by allenjol** [comment]
Thank you for your explanation, I see. I'm still wondering why there was no error when I used the non-standard version number as chart version before, but I have encountered such error today.

**Comment by allenjol** [comment]
Perhaps I really should have followed the standard semantics of chart Version from the helm official from the start
