### ISSUE TITLE
Helm doesn't use Dockerhub credentials to pull images

### ISSUE THREAD

**Issue by AAber** [helm/helm#10510]
Hi,
I use AWS EKS and my pod deployments hit the Dockerhub rate limit.
I purchased a Dockerhub pro account to extend my rate limit.
I configured my Dockerhub credentials into a k8s secret.
I tested my Dockerhub account credentials by deploying a pod using the following kubectl command:
``kubectl run prom --image=prom/prometheus:v2.16.0 --restart=Never -n monitoring``
With the above command kubectl is able to bypass the rate limit and pull the prometheus image, so far so good.

When I run this helm command:
``helm install prometheus prometheus-community/prometheus --namespace monitoring --values https://bit.ly/2RgzDtg --version 11.0.3``
Most of the pods fail with ErrImagePull and show this error:
``Normal Pulling 14s kubelet Pulling image "prom/prometheus:v2.16.0"
Warning Failed 14s kubelet Failed to pull image "prom/prometheus:v2.16.0": rpc error: code = Unknown desc = Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit``

I tested this option:
``export HELM_EXPERIMENTAL_OCI=1``
``helm registry login -u myaccountname docker.io``

After the successful login l attempted the above helm install again but got the same ErrImagePull and rate limit errors.

Did I miss some configuration?
Please advise.

Thx.
AAber

Helm v3.7.2
K8s version v1.18.9-eks-d1db3c

**Comment by AAber** [comment]
Please put a hold on this ticket.
I used the "helm template" command to export the Helm chart to a yaml manifest.
Then I used kubectl to apply the yaml manifest.
After this procedure I still have the ErrImagePull error so there is a good chance Helm is not the cause for the issue.

**Comment by yxxhero** [comment]
https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/ @AAber
