### ISSUE TITLE
Major BUG: Latest Helm go client library is not compatibale with k8s.io/apimachinery/pkg/runtime/serializer/json

### ISSUE THREAD

**Issue by pankaj-83incs** [helm/helm#10524]
Helm go client package - "helm.sh/helm/v3/pkg/action" is importing "k8s.io/apimachinery/pkg/runtime/serializer/json".
After importing this package, helm is using below variable:
// hold a single instance of the case-sensitive decoder
var caseSensitiveJsonIterator = json.CaseSensitiveJSONIterator()
 whereas CaseSensitiveJSONIterator is missing/undeclared in the latest version of "k8s.io/apimachinery/pkg/runtime/serializer/json".

**Comment by bacongobbler** [comment]
The latest version of Helm [compiled successfully](https://app.circleci.com/pipelines/github/helm/helm/3413/workflows/067b91b1-c95b-4ca4-b2c7-6ad8806a7779/jobs/14992) - are you sure you are using go modules? How are you installing Helm?

**Comment by bacongobbler** [comment]
I just did a complete code search of helm... There is no reference to a `caseSensitiveJsonIterator` or to `json.CaseSensitiveJSONIterator()`. Perhaps you've checked out an older version of Helm?

Either case this doesn't appear to be an issue on the latest version of the code. Please re-open if you still think this is an issue.
