### ISSUE TITLE
helm search repo naming lowercase

### ISSUE THREAD

**Issue by zhaorendong** [helm/helm#10525]
Output of `helm version`:
3.7.2
Output of `kubectl version`:
v1.18.3
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
 I upload a chart (HelmTest-0.1.0.tgz) to the repo, then use command "helm search repo " to show charts, but it convert to lowercase.
![image](https://user-images.githubusercontent.com/12930436/148369296-663cc2c0-f8a2-497a-8950-45ddd91424a8.png)

# helm install cc myrepo/helmtest
Error: INSTALLATION FAILED: failed to download "myrepo/helmtest"

# helm install ccc myrepo/HelmTest
NAME: ccc
LAST DEPLOYED: Thu Jan  6 17:49:39 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None

**Comment by joejulian** [comment]
I was able to duplicate this behavior using chartmuseum and the servecm and cm-push plugins:

```
helm servecm --port=8879 --storage local --storage-local-rootdir ./local --context-path=/charts
```

```
$ helm create MyChart
Creating MyChart
$ helm cm-push MyChart local
Pushing MyChart-0.1.0.tgz to local...
Done.
$ helm repo add local http://127.0.0.1:8879/charts
"local" has been added to your repositories
$ helm search repo MyChart
NAME         	CHART VERSION	APP VERSION	DESCRIPTION                
local/mychart	0.1.0        	1.16.0     	A Helm chart for Kubernetes
$  helm fetch local/mychart
Error: chart "mychart" matching  not found in local index. (try 'helm repo update'): no chart name found
$ helm fetch local/MyChart
$
```

**Comment by zonggen** [comment]
@joejulian verified this behavior and changing label to bug.

**Comment by hown3d** [comment]
Hi @joejulian I'd like to take this issue.
