### ISSUE TITLE
Get `helm chart list` and `helm repo list` using helm API

### ISSUE THREAD

**Issue by johnliu26** [helm/helm#10522]
Output of `helm version`:
```
helm client version helm.sh/helm/v3 v3.2.4
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}
```

Output of `kubectl version`:
```
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.5", GitCommit:"e338cf2c6d297aa603b50ad3a301f761b4173aa6", GitTreeState:"clean", BuildDate:"2020-12-09T11:10:32Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): `AKS`

Followup to the issue https://github.com/helm/helm/issues/10520.

1. Could you please tell me why the `helm chart list` was dropped in more recent versions?
2. Do we have any walkaround or other method to get the resources of `helm chart list` and `helm repo list` using helm API?

Thanks for your help!

**Comment by bacongobbler** [comment]
> 1. Could you please tell me why the `helm chart list` was dropped in more recent versions?

https://github.com/helm/community/blob/main/hips/hip-0006.md#6-helm-chart-is-removed-integrated-into-rest-of-cli

This functionality was removed in https://github.com/helm/helm/pull/9782.

> 2\. Do we have any walkaround or other method to get the resources of `helm chart list` and `helm repo list` using helm API?

Once you invoke `helm package`, the chart will be packaged as a tarball in the current directory. From the API you could interact with it either through the `pkg/chart/loader` package or by passing the tarball as an argument to `helm install`/`[pkg/action/Install](https://github.com/helm/helm/blob/main/pkg/action/install.go#L73)`.

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!
