### ISSUE TITLE
helm list doesn't show the release

### ISSUE THREAD

**Issue by iusergii** [helm/helm#10531]
I tried to fix bunch of helm releases with `pending-upgrade` status by [deleting the secret with last  release versions](https://github.com/helm/helm/issues/8987#issuecomment-786149813). After I re-run the CD for failed charts to restore the version.
As a result some of helm chart doesn't shown via helm list. 
```bash
> helm ls -a --namespace default | grep my-release
>
```
Meantime I can see it with --filter flag:
```bash
helm ls --namespace default --filter my-release
NAME                          	NAMESPACE   	REVISION	UPDATED                              	STATUS  	CHART              	APP VERSION
my-release                      defaultx	7       	2022-01-07 10:41:24.357165136 +0000 UTC	deployed	my-release-0.1.117	0.1.117 
```
I deleted all helm secrets and re-run CD again but the result the same. Secret appeared but list doesn't show the release. 
```bash
kubectl get secrets --field-selector type=helm.sh/release.v1 | grep my-release
sh.helm.release.v1.my-release.v1                      helm.sh/release.v1   1      70m
```

Output of `helm version`:
CD version: 3.4.2
Local version 3.7.2

Output of `kubectl version`:
v1.23.1

Cloud Provider/Platform : 
EKS

**Comment by hickeyma** [comment]
@iusergii Does it work when you use `--A` flags? In other words, with the following command: `helm ls -A`.

**Comment by iusergii** [comment]
@hickeyma 
- `helm ls -A`
- `helm ls -A --namespace <ns>`

Both don't show the release.

**Comment by hickeyma** [comment]
Ok, what's the output of these commands:

- `kubectl get secret -l owner=helm,name=my-release --all-namespaces`
- `kubectl get secret -l owner=helm,,status=deployed,name=my-release --all-namespaces`

**Comment by hickeyma** [comment]
This can be tricky to track down the exact cause. Do you mind trying to following to see if it sheds some light on the issue:

- Confirm that `kubectl` and `helm` are pointing to the same cluster. Both use [kubeconfig files](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/) for connecting to a cluster.
- What version of Helm are you using? Just confirm that the binary you are running is Helm 3 and one of the latest releases.
- Check that the [storage backend](https://helm.sh/docs/topics/advanced/#storage-backends) that the Helm binary is using is `Secrets`. Check that `HELM_DRIVER` env var is not set to something else like `configmap`, `sql` etc.  You can also check by running `helm env` and see if is set there also.
