### ISSUE TITLE
Error: UPGRADE FAILED: another operation (install/upgrade/rollback) is in progress

### ISSUE THREAD

**Issue by fanglijun** [helm/helm#10549]
`helm upgrade --install --atomic --wait` gives `Error: UPGRADE FAILED: another operation (install/upgrade/rollback) is in progress`

Output of `helm version`:
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.17.2"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:41:42Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7", GitCommit:"1f86634ff08f37e54e8bfcd86bc90b61c98f84d4", GitTreeState:"clean", BuildDate:"2021-11-17T14:35:38Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by drduker** [comment]
Error: UPGRADE FAILED: another operation (install/upgrade/rollback) is in progress
is something that i've also experienced lately, super annoying

**Comment by drduker** [comment]
Found a fix described towards the end of this page regarding deleting the secret in the same namespace that his holding the helm release hostage:
https://stackoverflow.com/questions/51760640/why-helm-upgrade-install-failed-when-previous-install-is-failure
