### ISSUE TITLE
index.json - necessary for large projects

### ISSUE THREAD

**Issue by thernstig** [helm/helm#10542]
There are multiple issues reported regarding performance problems when the index.yaml size starts to increase:
https://github.com/helm/helm/issues/6155
https://github.com/helm/helm/issues/9931
https://github.com/helm/helm/issues/9865 (not related to the index file being .yaml, but still related)

@mattfarina has created a benchmark showing that JSON parsing is an order of magnitude faster: https://github.com/mattfarina/yamlbench
@mattfarina also created https://github.com/mattfarina/helm-index-json to show some JSON split testing.

As more and more indices are growing in size, this problem is bound to happen to more and more users.

Would it be due time to look into placing a .json index file next to the .yaml file, so that Helm opts to use the .json file but falls back to .yaml if it does not exist?

Just the switch from YAML -> JSON should help significantly in this area. JSON is also more natural for computer-written data as opposed to YAML which might be more suited for data where users also at times edit the files manually.

**Comment by mattfarina** [comment]
I love this idea. Personally, I've not had the time to do it. If someone has the time, this would be great.

**Comment by tlnd-rdalverny** [comment]
Has SQLite been considered as a possible option too? (in terms of memory usage and access speed, it might have a point)

**Comment by thernstig** [comment]
unstale

**Comment by thernstig** [comment]
unstale

**Comment by thernstig** [comment]
unstale

**Comment by thernstig** [comment]
unstale

**Comment by joejulian** [comment]
Actually I'm realizing this would actually be a very easy thing for a first time contributor, if you're interested @thernstig . The only thing that would be changed is to use the json marshaller instead of yaml when creating the index.yaml file if some configuration flag is set. Yaml is a superset of json so no further changes would be needed.

Then you could stop typing "unstale" every 90 days. :grinning:

**Comment by ibilalkayy** [comment]
Hey, @joejulian I want to contribute to it but don't have any idea how to do it. Can you guide me?

**Comment by thernstig** [comment]
@ibilalkayy try https://github.com/helm/helm/blob/main/CONTRIBUTING.md
