### ISSUE TITLE
Error: deployments.apps "oracledb-19c-oracle-db" already exists

### ISSUE THREAD

**Issue by JithuPaul24** [helm/helm#10543]
### What happened?
I'm trying to reinstall a chart which got stuck because there is an issue inside the pod which makes it readiness probe stuck. Pod says running but it will not succeed. So, I uninstalled/deleted the chart and made changes to the chart to fix the issue and tried to install again.

`helm install oracledb-19c oracle-db-1.0.0.tgz`

Then it started failing saying

**Error: INSTALLATION FAILED: deployments.apps "oracledb-19c-oracle-db" already exists**

> C:\Users\paju\Desktop\Oracle_db_helm>helm list
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS  CHART           APP VERSION
oracledb19c     habs-namespace  1               2022-01-12 12:37:28.3759001 -0500 EST   failed  oracle-db-1.0.0

I tried **`kubectl get deployments.apps -A`** and there is no deployments.app 'oracledb-19c-oracle-db'

> C:\Users\paju\Desktop\Oracle_db_helm>kubectl get deployments.apps -A
> NAMESPACE NAME READY UP-TO-DATE AVAILABLE AGE
> gatekeeper-system gatekeeper-audit 1/1 1 1 20d
> gatekeeper-system gatekeeper-controller 2/2 2 2 20d
> kube-system azure-policy 1/1 1 1 20d
> kube-system azure-policy-webhook 1/1 1 1 20d
> kube-system azuredefender-collector-misc 1/1 1 1 19d
> kube-system coredns 2/2 2 2 21d
> kube-system coredns-autoscaler 1/1 1 1 21d
> kube-system metrics-server 1/1 1 1 21d
> kube-system omsagent-rs 1/1 1 1 21d
> kube-system tunnelfront 1/1 1 1 21d

 I went and cleaned up every resources (deployments, services, pv, pvc, volumes, pods if they existed )

I confirmed by doing `kubectl get all --all-namespaces` and there is no resources related to this chart in the cluster at the time. I try again with the `helm install` and see the same error.

Then I tried with **`helm upgrade oracledb-19c oracle-db-1.0.0.tgz --install`**

Result :

> Release "oracledb-19c" does not exist. Installing it now.
> Error: deployments.apps "oracledb-19c-oracle-db" already exists

I tried with the `--debug` on and this is what I get

> C:\Users\paju\Desktop\Oracle_db_helm>helm install oracle19c oracle-db-1.0.0.tgz --debug
> install.go:178: [debug] Original chart version: ""
> install.go:199: [debug] CHART PATH: C:\Users\paju\Desktop\Oracle_db_helm\oracle-db-1.0.0.tgz
> client.go:128: [debug] creating 5 resource(s)
> Error: INSTALLATION FAILED: deployments.apps "oracle19c-oracle-db" already exists
> helm.go:88: [debug] deployments.apps "oracle19c-oracle-db" already exists
> INSTALLATION FAILED
> main.newInstallCmd.func2
> helm.sh/helm/v3/cmd/helm/install.go:127
> github.com/spf13/cobra.(*Command).execute
> github.com/spf13/cobra@v1.2.1/command.go:856
> github.com/spf13/cobra.(*Command).ExecuteC
> github.com/spf13/cobra@v1.2.1/command.go:974
> github.com/spf13/cobra.(*Command).Execute
> github.com/spf13/cobra@v1.2.1/command.go:902
> main.main
> helm.sh/helm/v3/cmd/helm/helm.go:87
> runtime.main
> runtime/proc.go:225
> runtime.goexit
> runtime/asm_amd64.s:1371

**I'm stuck at this!!!**

### What did you expect to happen instead?

I would like to see all the resources related to the chart get deleted from the K8 cluster when I do an uninstall and when I install/upgrade the chart , this error should not happen.

### How can we reproduce the bug? (as minimally and precisely as possible)

`helm version`

> version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}

`kubectl version`

> C:\Users\paju\Desktop\Oracle_db_helm>kubectl version
> Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"windows/amd64"}
> Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-18T19:30:35Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}

Kubernetes Cluster:

**Cloud Provider: Microsoft Azure**
Anything else we need to know?
**I already have the helm 3 , so I cannot use the --purge option with helm delete. Also, I don't have tiller in the K8s server because it is helm 3.**

**Comment by JithuPaul24** [comment]
Even when the subsequent helm installs say status 'FAILED', the actual process is happening inside the , deployment object was created, pod got created. pvc is bound.

**Comment by Navdeepuniyal** [comment]
Is there any update on this issue? I am facing the same.

**Comment by bharu11** [comment]
Were you able to find a fix for this? @JithuPaul24
