### ISSUE TITLE
"my chart" has no deployed releases error - if history is full and no revision is in `deployed` status

### ISSUE THREAD

**Issue by cebernardi** [helm/helm#10550]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.17.2"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:41:42Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T22:31:47Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  kind

We're experiencing situations where helm fails to upgrade a release with
```
Error: UPGRADE FAILED: "my-hello" has no deployed releases
```

if the history is full (default capacity is 10), and no revision in the history is in status `deployed`.

I believe the error is generated as follows:

When `helm` performs the upgrade, it creates a new release in the storage https://github.com/helm/helm/blob/main/pkg/action/upgrade.go#L323,
and if the recorded history has reached max capacity (`maxHistory`), it tries to remove the least recent release to make space for the new one: https://github.com/helm/helm/blob/a27c468c82fe2cb9a4e07d7c82c9df6b6fed9ed7/pkg/storage/storage.go#L62-L68.

When it removes the least recent release, it wants to preserve the last deployed one, so it invokes Deployed https://github.com/helm/helm/blob/a27c468c82fe2cb9a4e07d7c82c9df6b6fed9ed7/pkg/storage/storage.go#L179, which returns an error if we have no revision in the history in `deployed` status. https://github.com/helm/helm/blob/a27c468c82fe2cb9a4e07d7c82c9df6b6fed9ed7/pkg/storage/storage.go#L121-L123

at this point, the error is bubbled up and the release interrupts.

I think the behavior should be different and helm should just remove the least recent release if no deployed releases are found in the history, and proceed with the release.

Could the maintainers confirm if this is the intended behavior, or if I can propose a fix?

**How to reproduce it:**

Create a kind cluster and install a release that will fail the installation:
```
kind create cluster --image "kindest/node:v1.20.0"
helm repo add cloudecho https://cloudecho.github.io/charts/
helm repo update cloudecho
helm install my-hello cloudecho/hello -n hello --wait --create-namespace --timeout=30s --set image.repository="wrongrepo"
```

Perform more upgrades that won't fix the release:

```
helm upgrade my-hello cloudecho/hello -n hello --wait --timeout=30s --set image.tag=v1
helm upgrade my-hello cloudecho/hello -n hello --wait --timeout=30s --set image.tag=v2
helm upgrade my-hello cloudecho/hello -n hello --wait --timeout=30s --set image.tag=v3
```

at this point the history will be:

```
helm history my-hello -n hello
REVISION	UPDATED                 	STATUS	CHART      	APP VERSION	DESCRIPTION
1       	Thu Jan 13 10:46:22 2022	failed	hello-0.1.2	0.1.0      	Release "my-hello" failed: timed out waiting for the condition
2       	Thu Jan 13 10:47:55 2022	failed	hello-0.1.2	0.1.0      	Upgrade "my-hello" failed: timed out waiting for the condition
3       	Thu Jan 13 10:55:28 2022	failed	hello-0.1.2	0.1.0      	Upgrade "my-hello" failed: timed out waiting for the condition
4       	Thu Jan 13 10:56:28 2022	failed	hello-0.1.2	0.1.0      	Upgrade "my-hello" failed: timed out waiting for the condition
```

now perform another upgrade reducing the history capacity: (in this case the upgrade would fix the release)

```
helm upgrade my-hello cloudecho/hello -n hello --wait --timeout=30s --set image.repository="cloudecho/hello" --history-max=3
```

helm tries to shorten the history, preserving the last deployed release, but because no revision is in `deployed` status, the release will not proceed, giving:
```
Error: UPGRADE FAILED: "my-hello" has no deployed releases
```

but if we perform the same upgrade without `history-max` (meaning that the history capacity will be the default 10, so no need to remove any revision from the history), the upgrade proceeds:

```
helm upgrade my-hello cloudecho/hello -n hello --wait --timeout=30s --set image.repository="cloudecho/hello"
Release "my-hello" has been upgraded. Happy Helming!
NAME: my-hello
LAST DEPLOYED: Thu Jan 13 12:08:39 2022
NAMESPACE: hello
STATUS: deployed
REVISION: 6
```

**Comment by cebernardi** [comment]
this is particularly impacting us, as we have a large number of applications that reach this condition during their initial development stage.

**Comment by sethgupton-mastery** [comment]
This has started biting us too.

Looks like it was previously fixed in helm 2 but must have been rebroken in helm 3. https://github.com/helm/helm/pull/4978

**Comment by JohnJAS** [comment]
Exact the same issue on helm v3.5.3
