### ISSUE TITLE
Is there a way to set the API version your targeting with helm lint? Also, is there a list of helm lint warnings?

### ISSUE THREAD

**Issue by borgilb** [helm/helm#10556]
I'm looking at some related issues, but I'm still unclear on how this is supposed to work:
* https://github.com/helm/helm/pull/8608

My question is if it is possible to use helm lint like dry run where I can have it target a specific cluster or set an API version I want to target. I want to have strict set but I'm using older k8s clusters.

For example I'm on 1.19 and "policy/v1" is not supported. If I lint with the latest version of helm I get a warning for using "policy/v1beta1". I want strict set to capture warning, but only warning that are relevant to my actual clusters. 

Can't I just tell helm lint what version I'm on like dry run can be pointed to an actual cluster? I understand why you might want to do this, but chart linting isn't the mechanism I find especially useful for checking API versions. That is something I handle separately with different automation and tools like "kube no trouble".

I guess I'm just worried about what else I'll miss out on without strict set. Where is there a list of the warnings helm lint raises? I couldn't find anything like that in the docs.

Helm lint's output isn't structured at all (https://github.com/helm/helm/issues/4205) so capturing warnings versus errors in CD/CI is wonky as well.

EDIT
====

More succinctly:
1. I want to target a specific k8s api version with lint wrt to that specific versions API support without having to downgrade the helm exe version
2. I want a list of what `--strict` actually checks for so I can determine if its OK to not use it or if some of its checking is too important for me to ignore

The second point is just an ask for documentation because I can't find any definitive official list of rules it checks.

**Comment by brnck** [comment]
Having the same problem. 

K8s cluster version is 1.20.X

Helm 3.7.1 strict lint passes, however, Helm 3.7.2 returns:

```
[INFO] Chart.yaml: icon is recommended
[WARNING] templates/pdb.yaml: policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget

Error: 1 chart(s) linted, 1 chart(s) failed
```

Ran the same command on both versions:
```
helm lint --strict .
```
