### ISSUE TITLE
v3.8.0-rc.1: Add OCI as a chart repository does not work

### ISSUE THREAD

**Issue by jfeddern** [helm/helm#10565]
Hi there,

first of all I would like to say thank you very much for all the effort you put into getting the OCI capabilities from experimental to a full feature!

I tested the usual things already (package, push, pull, auth) and everything looks very good and feels stable!

I just stumbled across the `helm repo add` functionality and was wondering if this should work already for OCI helm repositories?
At least I got an error while trying to add an OCI repo as an helm chart repository, but maybe this is a mistake from my site.

Steps to reproduce:

1. Login to registry
`aws ecr get-login-password --region eu-central-1 | helm-3.8.0-rc registry login --username AWS --password-stdin <aws_account_id>.dkr.ecr.eu-central-1.amazonaws.com`
2. Package helm chart
`helm-3.8.0-rc package test-chart`
2. Push to registry
`helm-3.8.0-rc push test-chart-0.1.0.tgz oci://<aws_account_id>.dkr.ecr.eu-central-1.amazonaws.com/chart-repo`
3. Add registry as helm repository
```
helm-3.8.0-rc repo add my-chart-repo oci://<aws_account_id>.dkr.ecr.eu-central-1.amazonaws.com/chart-repo --debug
Error: looks like "oci://<aws_account_id>.dkr.ecr.eu-central-1.amazonaws.com/chart-repo" is not a valid chart repository or cannot be reached: object required
helm.go:84: [debug] object required
looks like "oci://<aws_account_id>.dkr.ecr.eu-central-1.amazonaws.com/chart-repo" is not a valid chart repository or cannot be reached
main.(*repoAddOptions).run
	helm.sh/helm/v3/cmd/helm/repo_add.go:206
main.newRepoAddCmd.func1
	helm.sh/helm/v3/cmd/helm/repo_add.go:82
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.3.0/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.3.0/command.go:974
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.3.0/command.go:902
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
	runtime/proc.go:255
runtime.goexit
	runtime/asm_amd64.s:1581
```

Output of `helm version`: 
helm-3.8.0-rc version
version.BuildInfo{Version:"v3.8.0-rc.1", GitCommit:"0c8320b685880ddf99f564f9e3ae7616eedf0cec", GitTreeState:"clean", GoVersion:"go1.17.5"}

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS

**Comment by zonggen** [comment]
Reproduced this behaviour with local OCI registry:
```bash
$ helm repo add oci oci://localhost:5000/v2 --debug

Error: looks like "oci://localhost:5000/v2" is not a valid chart repository or cannot be reached: object required
helm.go:88: [debug] object required
looks like "oci://localhost:5000/v2" is not a valid chart repository or cannot be reached
main.(*repoAddOptions).run
        helm.sh/helm/v3/cmd/helm/repo_add.go:206
main.newRepoAddCmd.func1
        helm.sh/helm/v3/cmd/helm/repo_add.go:82
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.3.0/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.3.0/command.go:974
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.3.0/command.go:902
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:87
runtime.main
        runtime/proc.go:255
runtime.goexit
        runtime/asm_amd64.s:1581
```

**Comment by pytimer** [comment]
I think `helm repo` cannot work via oci registry, because it always to download `index.yaml` file, but oci registry i can't find this file, so add failed.

I don't know whether `helm repo` should support oci registry?

**Comment by jfeddern** [comment]
Me neither, thats actually my question. If it does not make any sense to support `helm repo` for oci repositories it's totally fine for me. 
I was just wondering if it should be supported or not.

**Comment by scottrigby** [comment]
Hey @jfeddern thank you for testing out difference cases for OCI support in `v3.8.0-rc.1`!

And thanks @zonggen and @pytimer 

`helm repo` subcommands are not supported for OCI registries. See https://helm.sh/docs/topics/registries/ for a list of supported commands.
