### ISSUE TITLE
Throttling messages while running helm upgrade commands

### ISSUE THREAD

**Issue by zonggen** [helm/helm#10560]
## Description of problem:

User facing throttling messages when running the `./helm upgrade` command. The same issue with `oc` commands as well but after the `oc` binary upgrade issue is solved. Need a similar fix in helm binary as well.

Find this bug for `oc` client: https://bugzilla.redhat.com/show_bug.cgi?id=1899575

## How reproducible:
- Intermittent

## Steps to Reproduce:
1. Add many CRD's (>100) to OpenShift 4 and add workloads
2. Run helm upgrade commands on the cluster

## Actual results:
- Throttling messages while running.
```
[root@Server~]# ./helm upgrade --debug --namespace helm-example --install --set env.active_profile=dev,environment=dev --wait platform-auth-internal-api https://example.com/artifactory/helm-local/helm-example/platform-auth-internal-api-394419.tgz --dry-run -v 6  > /tmp/test
history.go:56: [debug] getting history for release platform-auth-internal-api
install.go:173: [debug] Original chart version: ""
install.go:190: [debug] CHART PATH: /root/.cache/helm/repository/platform-auth-internal-api-394419.tgz

I1028 11:37:01.745973   94954 request.go:668] Waited for 1.168719201s due to client-side throttling, not priority and fairness, request: GET:https://api.example.com:6443/apis/apps.openshift.io/v1?timeout=32s
```

## Expected results:
- No throttling messages while running it. 

## Output of `helm version`:
`version.BuildInfo{Version:"v3.6.2+5.el8", GitCommit:"eb607dd4f123eaedab662cef21008d177f2c3426", GitTreeState:"clean", GoVersion:"go1.15.13"}`

## Output of `kubectl version`:
`N/A`

## Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
`OpenShift`

**Comment by zonggen** [comment]
The default burst limit from `k8s` is 100 (https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cli-runtime/pkg/genericclioptions/config_flags.go#L441), and  `oc` has increased this limit to 250 (https://github.com/openshift/oc/pull/696/files). It's still possible to hit the throttling limit in some environment with more than 250 CRDs (see https://bugzilla.redhat.com/show_bug.cgi?id=1899575).

The cause this bug is because Helm is using `k8s`'s `genericclioptions.ConfigFlags`(https://github.com/helm/helm/blob/main/pkg/cli/environment.go#L91), which has limit of 100, so will be prone to this specific throttling issue. If we can configure the discoveryBurst using either 1. cli option or 2. env variable, then it could solve this issue.

**Comment by legal90** [comment]
@zonggen Default value for the discovery burst limit was updated to 300 in kubernetes: https://github.com/kubernetes/kubernetes/pull/109141. 

Should we update that value in helm too?
https://github.com/helm/helm/blob/82195652495d757d87c1a01f640973f20ca141b0/pkg/cli/environment.go#L45
