### ISSUE TITLE
Allow multiple values files in helm chart

### ISSUE THREAD

**Issue by efiShtain** [helm/helm#10562]
When working on charts which should be deployed to multiple environment (dev, test, stage, prod), it is sometimes required to pass multiple values.yaml using the -f flag when deploying the chart

It would be convenient feature to store all those values yaml inside of the chart, and add a flag (--internal-file or something) which allow to use this extra values files

the idea is to make a chart fully self deployed and include all relevant values inside
so instead of  "helm install -f <local path to values-prod.yaml>" I could use "helm install --internal-file values-prod.yaml"

**Comment by bacongobbler** [comment]
This is best left for high-level tools like helmfile to solve, IMO. Helm provides the mechanism to include multiple values files during install/upgrade. There have been several proposals related to this discussion such as #4275 and #10022.

In any case, we have a [Helm Improvement Proposal](https://github.com/helm/community/blob/main/hips/hip-0001.md) process and it might be good to have this go through that.
