### ISSUE TITLE
Allow referencing files outside of chart directory when a dedicated flag is provided (--allow-insecure)

### ISSUE THREAD

**Issue by efiShtain** [helm/helm#10563]
Helm doesn't allow reading files outside of the chart's directory as a security measurement

Sometimes when developing private charts, the security issue is not a real concern

Can we add a special flag which will allow helm to read files outside of the chart's directory? (like --allow-insecure)

**Comment by bacongobbler** [comment]
duplicate of #3276. See #10077.

**Comment by aboukhal** [comment]
@bacongobbler while #10077 would solve the need for breaking out of the sandbox to include external files, it's not really a duplicate. The almost 10 year history of #8840 and #10077 and the unsolvable review findings on the basic design of the feature demonstrate that it is deadlocked. Maybe it's time to acknowledge that #10077 does not align with the maintainer's vision and thus the design is unfixable, and implement a simpler solution to just blindly allow to break out of the sandbox with a feature flag for users that know exactly what they're doing.
