### ISSUE TITLE
Helm SSL Issue on connecting to Charts Repo

### ISSUE THREAD

**Issue by vinayhegdebms** [helm/helm#10567]
Hi All,

Unable to run a docker container that fails due to an underlying Helm error as follows

```
Error: error initializing: Looks like "https://charts.helm.sh/stable" is not a valid chart repository or cannot be reached: Get "https://charts.helm.sh/stable/index.yaml": x509: certificate signed by unknown authority
```

`Software Versions:`
1. Helm: v2.17.0
2. Curl: v7.58.0
3. Docker: 18.06.3-ce

Command Run:
```
helm repo add stable https://charts.helm.sh/stable
```

Troubleshooting Steps:
1. Verify if `ca-certificates` exists, re-install via didn't help either. Can't use `-k` or `--insecure` as a workaround
2. Added [Helm Website](https://charts.helm.sh/stable) SSL as trusted via the steps [here](https://curl.haxx.se/docs/sslcerts.html)
3. SSL Chain also looks valid as per [SSLShopper](https://www.sslshopper.com/ssl-checker.html#hostname=charts.helm.sh)
4. Running the `openssl` command gives errors (_output truncated_)
```
openssl s_client -showcerts -connect charts.helm.sh:443
issuer=C = US, ST = California, L = Sunnyvale, O = Fortinet, OU = Certificate Authority, CN = FG1K5D3I15805464, emailAddress = support@fortinet.com

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 2883 bytes and written 396 bytes
Verification error: self signed certificate in certificate chain

```

Can someone please verify if the SSL is correct and help me debug this issue? Let me know if any further info is required

**Comment by bacongobbler** [comment]
Works for me.

```
><> helm repo add stable https://charts.helm.sh/stable
"stable" has been added to your repositories
```

> `Software Versions:`
> 
>     1. Helm: v2.17.0

Helm 2's support lifecycle ended on November 2020. See [the blog post](https://helm.sh/blog/helm-2-becomes-unsupported/) for more details.

Can you please try again using Helm 3?

**Comment by vinayhegdebms** [comment]
@bacongobbler thanks for the recommendation, we did review the blog post while debugging & are working on the Helm upgrade from 2 to 3 (_having other issues with it_) as well.

Until then, could you please suggest any workarounds to fix this for Helm 2?

**Comment by jhaagmans** [comment]
I have a similar issue. I am trying to work my way through getting helm 2 to run so I can use `2to3` to migrate the helm2 installations to helm3. I get a connection refused error, though:

```bash
Error: error initializing: Looks like "https://charts.helm.sh/stable/" is not a valid chart repository or cannot be reached: Get "https://charts.helm.sh/stable/index.yaml": dial tcp: lookup charts.helm.sh on [::1]:53: read udp [::1]:53265->[::1]:53: read: connection refused
```
