### ISSUE TITLE
(Possible) race condition while using k8s API ttlSecondsAfterFinished

### ISSUE THREAD

**Issue by guidoiaquinti** [helm/helm#10576]
👋 Hi! I would like to report a possible race condition while installing/upgrading a chart with a template using the kubernetes API [ttlSecondsAfterFinished](https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/).

If `ttlSecondsAfterFinished` is set to 0 or a low number, Helm could fail with `UPGRADE FAILED: jobs.batch "test-job" not found` when running with `--wait` and `--wait-for-jobs`. Unfortunately I don't have a clean repro.

Output of `helm version`:
```
version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.17.3"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:06:30Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/arm64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): kind on macOS

**Comment by bacongobbler** [comment]
Thanks @guidoiaquinti. Any suggestions on a fix?
