### ISSUE TITLE
Connecting to cluster with insecure tls way.

### ISSUE THREAD

**Issue by yogesh-reddy** [helm/helm#10570]
I was using helm client from my go code to perform helm operations.
I see that `*cli.EnvSettings` has no way to disable the tls check from code it was giving me error if i not provide my cert data.

Let me know if there is a way to connect insecurely.

i am getting this error.

 Kubernetes cluster unreachable: Get "https://xyx/version?timeout=32s": x509: certificate signed by unknown authority

**Comment by pytimer** [comment]
@yogesh-reddy You can setting custom client that implement `genericclioptions.RESTClientGetter` interface. I don't have a complete example here, but you can see the following code for reference. This is part of my code.

```go
// ToRESTConfig returns restconfig
func (c *kubernetesClient) ToRESTConfig() (*rest.Config, error) {
	return c.config, nil
}

func (c *kubernetesClient) ToRawKubeConfigLoader() clientcmd.ClientConfig {
	loadingRules := clientcmd.NewDefaultClientConfigLoadingRules()

	overrides := &clientcmd.ConfigOverrides{
		AuthInfo: clientcmdapi.AuthInfo{
			Token: c.config.BearerToken,
		},
		ClusterInfo: clientcmdapi.Cluster{
			Server:                c.config.Host,
			InsecureSkipTLSVerify: c.config.Insecure,
		},
	}

	overrides.Context.Namespace = c.namespace

	return clientcmd.NewNonInteractiveDeferredLoadingClientConfig(loadingRules, overrides)
}
```
