### ISSUE TITLE
Release.IsInstall is true when running helm template command

### ISSUE THREAD

**Issue by derba** [helm/helm#10579]
Output of `helm version`:

version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-12T12:32:49Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Minikube

Issue:

`Release.IsInstall` is true when running `helm template` command.

a.yaml:

```yaml
{{- if or .Release.IsInstall .Release.IsUpgrade }}
  {{- if not (.Capabilities.APIVersions.Has "my.api.com/v1") }}
    {{ fail "My API not supported" }}
  {{- end }}
{{- end }}

apiVersion: my.api.com/v1
kind: MyStuff
...
```

Commands:

```sh
$ helm lint a/
==> Linting a/

1 chart(s) linted, 0 chart(s) failed
$ helm template a/
Error: execution error at (a/templates/a.yaml:3:7): My API not supported
```

That behavior is in conflict with Helm documentation: https://helm.sh/docs/topics/charts/#predefined-values

"*Release.IsInstall: This is set to true if the current operation is an install.*"

I want both helm lint and template commands successfully pass.

**Comment by bacongobbler** [comment]
By default, a `helm template` uses the same APIs as a `helm install` to simulate what would happen if you ran `helm install`. To switch to an upgrade, use `helm template --is-upgrade` as per the help text:

>       --is-upgrade                   set .Release.IsUpgrade instead of .Release.IsInstall

Hope this helps.

**Comment by bacongobbler** [comment]
Closing as intentional behaviour.
