### ISSUE TITLE
The `helm pull` command does not remove temporarily index files from repository cache location

### ISSUE THREAD

**Issue by sboschman** [helm/helm#10583]
Helm pull [uses](https://github.com/helm/helm/blob/86a94f2f53b0519a3b22648a11f332c85cd8da1a/pkg/repo/chartrepo.go#L233) a temporarily index file, which isn't removed.
As the cached index file is never reused, I guess it should be removed automatically by Helm.

Scenario:
CD tools, like ArgoCD, run numerous `helm pull` commands which causes the cache directory size to grow. Depending on your ephemeral storage constraints this results in pods being evicted as they exceed the storage limits.

Output of `helm version`:
```
$ helm version
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}
```

Output of `kubectl version`: n/a

Cloud Provider/Platform (AKS, GKE, Minikube etc.): n/a

Check repository cache location:
```
$ helm repo
...
--repository-cache string     path to the file containing cached repository indexes (default "~/.cache/helm/repository")
...
```

Clean up cache folder and check it is empty:
```
$ ls -ah ~/.cache/helm/repository/
.   ..
```

Run a repo update:
```
$ helm repo update
...
Update Complete. *Happy Helming!*
```

Check our cache dir, all seems as expected:
```
$ ls -ah ~/.cache/helm/repository/
.  ..  stable-charts.txt  stable-index.yaml
```

Lets pull a chart (using bitnami/kafka here as example):
```
$ helm pull --version 14.9.1 --repo https://charts.bitnami.com/bitnami kafka
$ ls -ah
.  ..  kafka-14.9.1.tgz
```

Check our cache dir:
```
$ ls -ah ~/.cache/helm/repository/
.  ..  'deZbVF1bUWI1H+i+PNkPYPlhuxo=-charts.txt' 'deZbVF1bUWI1H+i+PNkPYPlhuxo=-index.yaml' stable-charts.txt  stable-index.yaml
```

Repeating the same helm pull command creates new cache files every time.

**Comment by mattfarina** [comment]
Those cached files are used for some things. For example, `helm search repo` uses the cached index files to perform a search. I am sure Helm could do a better job of cleaning up its cache. Is there some specific use case and flow that you are looking for?

**Comment by sboschman** [comment]
I think a `helm search repo` is performed against the 'normal' cached index files, i.e. `stable-index.yaml`, which are linked to the repositories defined in the repositories.yaml with `helm repo add`. I am referring to the cached index files with the random prefix, which seem to originate from the `helm pull` command and bypass the 'normal' cached index files for that repository.

```
// FindChartInAuthAndTLSAndPassRepoURL finds chart in chart repository pointed by repoURL
// without adding repo to repositories, like FindChartInRepoURL,
// but it also receives credentials, TLS verify flag, and if credentials should
// be passed on to other domains.
// TODO Helm 4, FindChartInAuthAndTLSAndPassRepoURL should be integrated into FindChartInAuthRepoURL.
```
(https://github.com/helm/helm/blob/86a94f2f53b0519a3b22648a11f332c85cd8da1a/pkg/repo/chartrepo.go#L230)

As far as I can tell from the method linked above, this cached index file with a random prefix in only used once in e.g. a `helm pull` to get the download uri for a chart.

Ideally this random temp index file is just cleaned up after the chart uri has been extracted from it. CD tools like ArgoCD heavily rely on `helm pull` and the helm cache just keeps growing. At some point you are running out of disk space or ephemeral storage space. We have a 4gb limit, and I see pods being forcefully evicted with 4gb of helm cache in use.

**Comment by sboschman** [comment]
This is still an issue with 3.8.1

> version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.5"}

```
$ ls -gh Library/Caches/helm/repository     
total 0

$ helm pull --version 14.9.1 --repo https://charts.bitnami.com/bitnami kafka

$ ls -gh Library/Caches/helm/repository               
total 26592
-rw-r--r--  1 staff   1.1K Apr 20 10:47 uNKn3j0x2avGGhPt+vifKYQYtyQ=-charts.txt
-rw-r--r--  1 staff    13M Apr 20 10:47 uNKn3j0x2avGGhPt+vifKYQYtyQ=-index.yaml

$ helm pull --version 14.9.1 --repo https://charts.bitnami.com/bitnami kafka

$ ls -gh Library/Caches/helm/repository
total 53184
-rw-r--r--  1 staff   1.1K Apr 20 10:50 KzRnhl2twEjSMhoRaiiqs-dWh6c=-charts.txt
-rw-r--r--  1 staff    13M Apr 20 10:50 KzRnhl2twEjSMhoRaiiqs-dWh6c=-index.yaml
-rw-r--r--  1 staff   1.1K Apr 20 10:47 uNKn3j0x2avGGhPt+vifKYQYtyQ=-charts.txt
-rw-r--r--  1 staff    13M Apr 20 10:47 uNKn3j0x2avGGhPt+vifKYQYtyQ=-index.yaml

$ helm pull --version 14.9.1 --repo https://charts.bitnami.com/bitnami kafka

$ ls -gh Library/Caches/helm/repository
total 79776
-rw-r--r--  1 staff   1.1K Apr 20 10:50 KzRnhl2twEjSMhoRaiiqs-dWh6c=-charts.txt
-rw-r--r--  1 staff    13M Apr 20 10:50 KzRnhl2twEjSMhoRaiiqs-dWh6c=-index.yaml
-rw-r--r--  1 staff   1.1K Apr 20 10:51 lHHy9X22OvDtd4ni9txmOM3wtvQ=-charts.txt
-rw-r--r--  1 staff    13M Apr 20 10:51 lHHy9X22OvDtd4ni9txmOM3wtvQ=-index.yaml
-rw-r--r--  1 staff   1.1K Apr 20 10:47 uNKn3j0x2avGGhPt+vifKYQYtyQ=-charts.txt
-rw-r--r--  1 staff    13M Apr 20 10:47 uNKn3j0x2avGGhPt+vifKYQYtyQ=-index.yaml

$ helm repo add bitnami https://charts.bitnami.com/bitnami 
"bitnami" has been added to your repositories

$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈

$ ls -gh Library/Caches/helm/repository
total 106368
-rw-r--r--  1 staff   1.1K Apr 20 10:50 KzRnhl2twEjSMhoRaiiqs-dWh6c=-charts.txt
-rw-r--r--  1 staff    13M Apr 20 10:50 KzRnhl2twEjSMhoRaiiqs-dWh6c=-index.yaml
-rw-r--r--  1 staff   1.1K Apr 20 10:53 bitnami-charts.txt
-rw-r--r--  1 staff    13M Apr 20 10:53 bitnami-index.yaml
-rw-r--r--  1 staff   1.1K Apr 20 10:51 lHHy9X22OvDtd4ni9txmOM3wtvQ=-charts.txt
-rw-r--r--  1 staff    13M Apr 20 10:51 lHHy9X22OvDtd4ni9txmOM3wtvQ=-index.yaml
-rw-r--r--  1 staff   1.1K Apr 20 10:47 uNKn3j0x2avGGhPt+vifKYQYtyQ=-charts.txt
-rw-r--r--  1 staff    13M Apr 20 10:47 uNKn3j0x2avGGhPt+vifKYQYtyQ=-index.yaml
```

The `bitnami-index.yaml` belongs to the `repo add` flow and is not an issue. The issue is the random named files generated by the `helm pull --repo` command, which are only used for a single `helm pull` invocation and not removed after use.

**Comment by pierluigilenoci** [comment]
@mattfarina @matthiasfehr could you please take a look?

**Comment by pierluigilenoci** [comment]
@mattfarina @matthiasfehr could you please take a look?

**Comment by mgs255** [comment]
I was looking at this as it seemed a bit strange.  I was thinking of attempting a fix by generating a temp name based on a hash of the repository url.  Additionally, if the file is less than 5 mins old, then skip downloading the index file and just use the existing cached version.

**Comment by johnlane** [comment]
What is the preferred way to clean up Helm cache?

I have over 10,000 files totalling over 15GB making a hole in my disk. Loads of pairs of files like this

```
'ZyqGi5cEV9SQft6EZPUKiw3ZyqE=-index.yaml'
'ZyrNJ5IQchN9KOdxpSLX0ew8Rm8=-charts.txt'
```

Is `rm -r` a suitable tool to use here?

**Comment by joejulian** [comment]
That's what I do.

**Comment by pierluigilenoci** [comment]
I would love to have one of Helm's maintainers provide their feedback here.

**Comment by joejulian** [comment]
This question has been answered. The behavior cannot be changed as it would violate [hip-0004](https://github.com/helm/community/blob/aa8e13054d91ee69857b13149a9652be09133a61/hips/hip-0004.md). My recommendation is that you either script your cleanup or use an ephemeral volume for your `HELM_REPOSITORY_CACHE`.

**Comment by johnlane** [comment]
Sorry it hasn't been answered in that no confirmation has been given that just deleting the files (e.g. with `rm`) is ok. If that's ok then that's fine, but could that fact be confirmed (and perhaps documented somewhere) ?
