### ISSUE TITLE
Error: UPGRADE FAILED: another operation (install/upgrade/rollback) is in progress

### ISSUE THREAD

**Issue by matti** [helm/helm#10599]
This closed issue still exists, hitting it every month as many, many others: https://github.com/helm/helm/issues/8987

this happens when: computer goes to sleep, ci/cd pipeline is interrupted, control+c etcq2
"workarounds" include:

`kubectl delete secret sh.helm.release.v1.asdf.v1 -n asdf`

and

>We reverted to 3.2.4

**Comment by joejulian** [comment]
Ir was closed because the person that reported the issue closed it. They determined that the problem was a flaw in their CI process.

Please provide a debug log from the fault, along with the `helm history` of the release.

**Comment by matti** [comment]
simple control+c during install is enough to repro this

**Comment by bacongobbler** [comment]
A recent fix was released in Helm 3.7 where a cancelled upgrade via a CTRL+C will force the release into a failed state, allowing you to retry the upgrade, preventing the `pending-upgrade` issue many users mentioned in that ticket. See https://github.com/helm/helm/pull/9180.

Issues related to connection timeouts are being tracked in https://github.com/helm/helm/issues/4558, but #9180 should solve the CTRL+C and/or CI pipeline being interrupted as both send SIGTERM.

**Comment by matti** [comment]
well, just got hit by this again by simply control+c

**Comment by matti** [comment]
ACTUALLY somehow an old helm install was installed - so with helm 3.8.0 this works!

**Comment by arash-bizcover** [comment]
https://github.com/helm/helm/issues/4558#issuecomment-958961462
