### ISSUE TITLE
Bug - Client certificate not reaching for tls handshake (helm oci pull) 

### ISSUE THREAD

**Issue by suryatech27-cloud** [helm/helm#10597]
Helm Version - v3.7.2
While doing **helm oci:// pull for artifact repository** its causes to handshake failure issue. 

So I debug helm CLI code, I just added a few print statements in go native library - net/HTTP - transport.go 
addTLS function does not get tlsconfig value for a handshake so handshake failure is happening.

`transport.go : addTLS () =================> TLSClientConfig :  &{<nil> <nil> [] map[] <nil> <nil> <nil> <nil> <nil> <nil> [h2 http/1.1]  NoClientCert <nil> false [] false false [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] <nil> 0 0 [] false 0 <nil> {{0 0} 0 0 0 0} [] []}`

`Error: failed to do request: Head "https://myprivatedns.com/v2/reponame/context/demotestchart/manifests/1.0": remote error: tls: handshake failure
`

so I manually added few line of code for client certificate in **transport.go** , now the tls handshake failure got resolved. but now i am getting **401 unauthorized.**

```
func (pconn *persistConn) addTLS(name string, trace *httptrace.ClientTrace) error {
	fmt.Println("transport.go : addTLS () =================> TLSClientConfig : ", pconn.t.TLSClientConfig)
	// Initiate TLS and check remote host name against certificate.
	if tlsConf := pconn.t.TLSClientConfig; tlsConf.Certificates == nil && tlsConf.ClientCAs == nil && tlsConf.CipherSuites == nil {
		cert, err := tls.LoadX509KeyPair("/etc/docker/certs.d/myprivatedns.com/client.pem", "/etc/docker/certs.d/myprivatedns.com/client.key")
		if err != nil {
			fmt.Println(err, "Failed in LoadX509KeyPair")
		}
		capool := x509.NewCertPool()
		cacert, err := ioutil.ReadFile("/etc/docker/certs.d/myprivatedns.com/cacerts.crt")
		capool.AppendCertsFromPEM(cacert)
		if err != nil {
			fmt.Println(err, "readCacerts from pool")
		}

		tlsConfig := &tls.Config{
			Certificates: []tls.Certificate{cert},
			ClientCAs:    capool,
			ClientAuth:   tls.RequireAndVerifyClientCert,
			//CipherSuites: []unit16{tls.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384},
			// CipherSuites: []unit16{
			// 	tls.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,
			// 	tls.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
			// 	tls.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
			// },
			MinVersion:               tls.VersionTLS12,
			PreferServerCipherSuites: true,
		}
		pconn.t.TLSClientConfig = tlsConfig
	}
....
}
```
it means oci pull for artifact repository not presenting the certificate for tls handshake so 
can anyone please check and fix the issue for next release.

**Comment by bacongobbler** [comment]
Hi @suryatech27-cloud. Helm is maintained by a number of volunteers. Our job as maintainers is to review and cut releases at a regular cadence. We'd appreciate your efforts in identifying and providing a fix. See https://github.com/helm/helm/blob/main/CONTRIBUTING.md for more details.

Thanks!

**Comment by suryatech27-cloud** [comment]
Hi @bacongobbler, actually what I did is not the fix for helm CLI, just checked why the client not presenting the certificate for a handshake and I found that the helm  CLI not providing config details to the net/HTTP library so which causes handshake failure issue.

yes, I am referring to the net/http package.  https://github.com/golang/go/blob/master/src/net/http/transport.go.
