### ISSUE TITLE
--set to empty array

### ISSUE THREAD

**Issue by matti** [helm/helm#10598]
https://helm.sh/docs/intro/using_helm/#the-format-and-limitations-of---set

Doesn't mention how to set (override) a key to empty array

**Comment by matti** [comment]
Also doesn't mention how to unset: `--set key=null`

**Comment by bacongobbler** [comment]
The source code for the documentation can be found here: https://github.com/helm/helm-www

**Comment by yxxhero** [comment]
@matti PR is welcome for helm doc. Thanks very much.
