### ISSUE TITLE
Unable to get an update from the "oci://" registry object required on helm dep update

### ISSUE THREAD

**Issue by shyam-ks** [helm/helm#10600]
Getting error on dependency update

Chart.yaml

dependencies:
  - name: chart-name-x
    version: "1.0.358"
    repository: "oci://ghcr.io/org-name"

Getting updates for unmanaged Helm repositories...
...Unable to get an update from the "oci://ghcr.io/org-name" chart repository:
	object required
Saving 1 charts
Downloading chart-name-x from repo oci://ghcr.io/org-name

Helm tool version: 'v3.7.2'

**Comment by bacongobbler** [comment]
Hi @shyam-ks. How did you upload this chart to the repository? The error message appears to be emitting from one of Helm's dependencies most likely to when Helm pulls down the index manifest from the OCI registry.

If you can try to share a way to reproduce this error using a sample chart (a basic `helm create && helm package` should suffice), that would be helpful.
