### ISSUE TITLE
Files.Get>: nil pointer evaluating interface {}.Get

### ISSUE THREAD

**Issue by hunkeelin** [helm/helm#10610]
I have the following in my templates/configmap.yaml
```
 11 data:
 12   foo.conf: |-
 13     {{ .Files.Get "/tmp/foo.conf" }}
 ```

Whenever I ran help install I get the following error 
```
templates/configmap.yaml:13:13: executing "foo/templates/configmap.yaml" at <.Files.Get>: nil pointer evaluating interface {}.Get
```
What am I missing?

**Comment by bacongobbler** [comment]
Can you please provide a full example using the output from `helm create`? That way we have something to test against.

My hunch is that you have this block nested within an `if`, `for`, or some other encasing block that changes the scope of the dot operator. You can try using `$.Files.Get` to try accessing the root scope in most cases.

**Comment by hunkeelin** [comment]
Hmm adding the `$.` and putting foo.conf on the helm path does do the trick. Thanks!!!


However now i'm running into a new error it's complaining json to yaml parsing. What i want to do is simply have the content of a file in configmap

```
ubuntu$ test % ls
Chart.yaml	charts		foo.conf	stuff		templates
ubuntu$ test % ls templates 
configmap.yaml
ubuntu$ test % cat templates/configmap.yaml 
apiVersion: v1
kind: ConfigMap
metadata:
  name: "testcm"
data:
  foo.conf: |-
    {{ .Files.Get "foo.conf" }}

ubuntu$ test % cat foo.conf 
###

#include "path"
###

daemonize no
#priority -10
graceful_die_on_errors yes
ubuntu$ test % helm upgrade -i test .  --dry-run
Release "test" does not exist. Installing it now.
Error: YAML parse error on test/templates/configmap.yaml: error converting YAML to JSON: yaml: line 13: could not find expected ':'

```

**Comment by bacongobbler** [comment]
Indentation in YAML is significant. Make sure to add a `nindent 4` to the end of your `.Files.Get` invocation so that the file is correctly indented according to the YAML specification on multi-line values.

This is what your template looks like without `nindent 4`:

```
><> helm template --debug .
install.go:178: [debug] Original chart version: ""
install.go:199: [debug] CHART PATH: /tmp/test-10610

---
# Source: test-10610/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "testcm"
data:
  foo.conf: |-
    ###

#include "path"
###

daemonize no
#priority -10
graceful_die_on_errors yes
Error: YAML parse error on test-10610/templates/configmap.yaml: error converting YAML to JSON: yaml: line 13: could not find expected ':'
```

Notice how every line after the first line in your file is moved to the beginning of the document. YAML treats this as a new key/value pair, hence why it is reporting an error.

Changing your template to the following:

```
><> cat templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "testcm"
data:
  foo.conf: |-
    {{- .Files.Get "foo.conf" | nindent 4 }}
```

(note that I also added a hyphen which will chomp leading whitespace)

This change results in the expected output.

```
><> helm template .
---
# Source: test-10610/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "testcm"
data:
  foo.conf: |-
    ###

    #include "path"
    ###

    daemonize no
    #priority -10
    graceful_die_on_errors yes
```

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!
