### ISSUE TITLE
helm registry login fails with helm 3.8

### ISSUE THREAD

**Issue by revit13** [helm/helm#10611]
I get the following error when doing `helm registry login` command on linux ubuntu machine:

bin/helm registry login -u user ghcr.io
Password:
** Message: 07:59:21.304: Remote error from secret service: org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.freedesktop.Secret.Collection' on object at path /org/freedesktop/secrets/collection/login
Error: error storing credentials - err: exit status 1, out: `No such interface 'org.freedesktop.Secret.Collection' on object at path /org/freedesktop/secrets/collection/login`

Output of `helm version`: version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}

**Comment by revit13** [comment]
@jdolitsky Here is the content of `~/.docker/config.json`. I do not have an entry for `credsStore`
`
{
        "auths": {
                "ghcr.io": {
                        "auth": "..."
                },
                "https://index.docker.io/v1/": {
                       "auth": "..."
                },
                "localhost:5000": {
                        "auth": "..."
                }
        }
}`

**Comment by revit13** [comment]
`sudo apt install gnupg2 pass` seems to fix the issue. Thanks!

**Comment by SuperSandro2000** [comment]
Did you install docker-compose from the ubuntu repository? They by default install the docker desktop credential helper which does not work on headless machines.
