### ISSUE TITLE
Improve OCI registry client configuration options for devs

### ISSUE THREAD

**Issue by antgamdia** [helm/helm#10623]
Congrats on the 3.8 release! Happy to see OCI-related logic was extracted out of the experimental directory, meaning 3rd party developers can just import Helm and use it.

Precisely, in my team, we'd wanted to use the Helm OCI registry client to interact with OCI registries instead of dealing directly with ORAS. However, I find the current support (as of `v3.8.0`) quite limited.
More specifically:

- We'd need to be able to customize the resolver passed through the oras Registry, as we are adding a custom header and a preconfigured httpclient with the proper auth (not only _basic auth_ but also _bearer token_)

Currently, the only `ClientOption` are  `ClientOptDebug`, `ClientOptWriter` and `ClientOptCredentialsFile`, so adding a new one allowing customizing the resolver would make the trick.

Additionally, I'd like to have more `LoginOptions` as well. Currenlt only `LoginOptBasicAuth` and `LoginOptInsecure` are available.
As stated before, we'd like to customize other things like `userAgent` or `authorization` headers (or any other header) with arbitrary values.

Relevant file: https://github.com/helm/helm/blob/v3.8.0/pkg/registry/client.go

I don't know what's your roadmap on improving this kind of stuff, but willing to contribute if you want. 

Output of `helm version`: `version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.6"}`

**Comment by jdolitsky** [comment]
@antgamdia would love to have a PR to extend the options available to the registry client
