### ISSUE TITLE
How to change storageClassName of an already installed Chart?

### ISSUE THREAD

**Issue by waterdrop01** [helm/helm#10625]
Output of `helm version`: `version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}`

Output of `kubectl version`: `Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:09:57Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}`

Hello, I just got bitten by Helm uninstall command ([see this issue](https://github.com/helm/helm/issues/10621)) and completely lost days of work (my PVC got deleted by Helm somehow).

Hence, I want to make sure that this won't reproduce in the future. (IMO Persistent Volume should NEVER be deleted. Unless the user explicitly says so).

In my helm `values.yml` file, I changed the `storageClassName` value, in order to use one that has a `Retain` policy. 

But, when trying to `helm upgrade`, helm complains with the following error:

```
Error: UPGRADE FAILED: failed to replace object: PersistentVolumeClaim "grafana" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims
  core.PersistentVolumeClaimSpec{
  	AccessModes:      {"ReadWriteOnce"},
  	Selector:         nil,
  	Resources:        {Requests: {s"storage": {i: {...}, s: "10Gi", Format: "BinarySI"}}},
- 	VolumeName:       "",
+ 	VolumeName:       "pvc-831a7c65-cd0a-40b6-8777-10fb5331093e",
- 	StorageClassName: &"scw-bssd-retain",
+ 	StorageClassName: &"scw-bssd",
  	VolumeMode:       &"Filesystem",
  	DataSource:       nil,
  	DataSourceRef:    nil,
  }
```

So, Anyone knows how am I supposed to do to NOT DELETE EXISTING PVCs, and still CHANGE THEIR storageClassName?

I don't want to `kubectl patch`, any change should be committed in the helm `values.yml` file.

Thank you!

**Comment by bacongobbler** [comment]
> Anyone knows how am I supposed to do to NOT DELETE EXISTING PVCs, and still CHANGE THEIR storageClassName?

The short answer is that you can't. Changing anything about a PVC's metadata after creation (asides `resources.requests`) is forbidden by Kubernetes. The error message you're seeing comes directly from the Kubernetes API. Helm has no control over what Kubernetes allows or does not allow in this case.

You can delete and rename the PVC (deleting existing data), or create a new PVC referencing the new storage class. But you cannot change the storage class name.

Hope that helps.

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!
