### ISSUE TITLE
helm install --replace DELETED MY PVC

### ISSUE THREAD

**Issue by waterdrop01** [helm/helm#10621]
Output of `helm version`: `version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}`

Output of `kubectl version`: `Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:09:57Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}`

Hello, I don't understand how the hell `helm install --replace` did REMOVE my existing PVC???

Here are the commands I ran:

```
helm uninstall grafana --keep-history --namespace=monitoring
release "grafana" uninstalled
```
Then
```
helm upgrade grafana grafana/grafana --version 6.21.2 --namespace=monitoring --values helm-grafana-monitoring-values.yml
```
But it had the following error: `Error: UPGRADE FAILED: "grafana" has no deployed releases`, So I tried:
```
helm install grafana grafana/grafana --version 6.21.0 --namespace=monitoring --values helm-grafana-monitoring-values.yml
```
But it had the following error: `Error: cannot re-use a name that is still in use`, so I tried using `--replace`:
```
helm install grafana grafana/grafana --version 6.21.0 --namespace=monitoring --values helm-grafana-monitoring-values.yml --replace
```

PROBLEM, I lost all my grafana dashboards! :( days of work gone. can't believe it.

Indeed, when running:
```
kubectl get pvc -n monitoring 
NAME                      STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
grafana                   Bound    pvc-831a7c65-cd0a-40b6-8777-10fb5331093e   10Gi       RWO            scw-bssd       11m
```
I can see that my PVC age is 11 minutes (while it was created more than a year ago).

Please, someone help to explain what happened.

**Comment by waterdrop01** [comment]
I had to run these commands following this issue on the Grafana helm chart => https://github.com/grafana/helm-charts/issues/996

**Comment by yxxhero** [comment]
@waterdrop01
--replace                      re-use the given name, only if that name is a deleted release which remains in the history. This is unsafe in production

**Comment by waterdrop01** [comment]
thanks @yxxhero 

Could you precise the "This is unsafe in production"?

Does that explain that it DELETED my PVC?

**Comment by yxxhero** [comment]
@waterdrop01 I see you do the uninstall action.

**Comment by waterdrop01** [comment]
@yxxhero yes, but according [to this issue](https://github.com/helm/helm/issues/5156), uninstalling a chart doesn't remove its PVC. What am I missing?

**Comment by yxxhero** [comment]
@waterdrop01 Your situation is different from him. Your PVCs is managed by helm, not generated by statefulset. Do you understand?

**Comment by yxxhero** [comment]
https://helm.sh/docs/howto/charts_tips_and_tricks/#tell-helm-not-to-uninstall-a-resource @waterdrop01

**Comment by waterdrop01** [comment]
Oh boy. No I didn't notice the difference. phhhew

Any reason why `helm uninstall` would delete the PVC? 

IMO Persistent Volume should NEVER be deleted. Unless the user explicitly says so (by using `kubectl delete pvc` or a flag when running `helm uninsatll`.

**Comment by waterdrop01** [comment]
Thanks for the link. I will read the documentation. 

In my case, everything is managed by Helm. Example of my grafana helm `values.yml` file:

```yml
image:
  repository: grafana/grafana
  tag: 8.3.4
  pullPolicy: IfNotPresent

persistence:
  type: pvc
  enabled: true
  storageClassName: scw-bssd
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  annotations: {}
  finalizers:
    - kubernetes.io/pvc-protection
```
I would like to change `storageClassName` to `scw-bssd-retain`. But `helm upgrade` complains about immutability.

1- Is that the correct way to ensure following `helm uninstall` won't remove PV with valuable data?
2- If not, where am I supposed to add the annotation `"helm.sh/resource-policy": keep`?

Thanks a lot for your help!

**Comment by yxxhero** [comment]
@waterdrop01 Grafana PVC is created directly through the template system with helm. statefulset's PVCs is created by k8s.
