### ISSUE TITLE
Azure acr - Could not retrieve list of tags for repository oci...

### ISSUE THREAD

**Issue by michal-kania** [helm/helm#10624]
Command from azure dev ops windows agent:
`helm dependency update ./filePath`

The chart in ./filePath contains dependencies like 
```
dependencies:
- name: yyyy
  version: ...
  repository: "oci://redacted.azurecr.io/helm/xxx"
```
Helm 3.8.0
**Error: could not retrieve list of tags for repository oci://redacted.azurecr.io/helm/xxx: GET "https://redacted.azurecr.io/v2/helm/xxx/yyyy/tags/list": GET "https://redacted.azurecr.io/oauth2/token?scope=repository%3Ahelm%2Fxxx%2Fyyyy%3Ametadata_read%2Cpull&service=redacted.azurecr.io": unexpected status code 401: unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information.**

It worked with helm 3.7.0

I tested it with service principal and acr admin user, but both of them are probably missing posibility for metadata/read permission described here:
https://docs.microsoft.com/en-us/azure/container-registry/container-registry-repository-scoped-permissions#concepts
Helm 3.8.0 works only with ACR Tokens (preview)
https://docs.microsoft.com/en-us/azure/container-registry/container-registry-repository-scoped-permissions#create-token---portal
with metadata/read permission scope.
This is marked as Preview and allowed only with azure container registry Premium SKU.

Is it intended behavior?
Is there any posibility to skip GET .../tags/list which might not be necessary and i am already specifiying dependency version?

Thanks.

**Comment by jdolitsky** [comment]
Hi. Would you be able to share what you have for the `version` value? It is my understanding that if this is an exact version, tag listing will not/should not occur

**Comment by bacongobbler** [comment]
Possibly related to #10608?

**Comment by michal-kania** [comment]
Hi, version is (in my case) replaced by previous pipeline step and it is specified exactly.
During the day i was abel to force previous helm 3.7.0 by changing version of helm installer to HelmInstaller@1 (previous @0 helm intaller is always using latest installed version from cache even if lower version number is specified).
And with helm 3.7.0 everything is working fine again.
**Log:**
...Unable to get an update from the "oci://redacted.azurecr.io/helm/xxx" chart repository:
	object required
Downloading accesspoint-ms from repo oci://redacted.azurecr.io/helm/xxx
Pulled: redacted.azurecr.io/helm/xxx/yyyy:0.1.34
Digest: sha256:bd2a267c28d0f0ca88afd0df17b91fedf1432055117a36b543245101691e0452
Deleting outdated charts

Version (tag) exists in acr as specified.
I am using exact version number filled by previous pipeline steps. No tilde or another characters (^1.2.3) to search for different versions.

**Comment by jdolitsky** [comment]
cc @sabre1041 @scottrigby

**Comment by ngoyal16** [comment]
Same with AWS Public ECR - As aws public ecr also do not have /tags/list function as of now. 

If specifying a specifc version it should directly fecth the content instead of tag list first.

**Comment by sabre1041** [comment]
Ill take a look and see what the best approach to resolve

**Comment by jdolitsky** [comment]
perhaps it is solved with direct `helm install`, but not with dependency stuff

**Comment by sabre1041** [comment]
@jdolitsky found the issue. Will push an update shortly with a resolution
