### ISSUE TITLE
`helm push` does not upload `.prov` files over the OCI interface

### ISSUE THREAD

**Issue by muhittink** [helm/helm#10636]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}
```
Seems to be a bug. We are signing our charts with `helm package --sign` , the `.prov` are generated next to the chart tar file. But helm 3.8 will not upload the `.prov` files when pushing over the OCI Interface using Harbor 2.4.

**Comment by jdolitsky** [comment]
Appears to be an issue within Harbor. Just tried this:

```
helm create demo
helm package --sign --key helm-test --keyring ./testdata/pgp/helm-test-key.secret demo/
helm push demo-0.1.0.tgz oci://bundle.bar/u/jdolitsky/helm-test
```

Resulting manifest:
```
{
	"schemaVersion": 2,
	"config": {
		"mediaType": "application/vnd.cncf.helm.config.v1+json",
		"digest": "sha256:ff1a5b6b030beb6d80ed19ee6573edf7de40803ef73c8502cffb6f2a10ba39d7",
		"size": 138
	},
	"layers": [
		{
			"mediaType": "application/vnd.cncf.helm.chart.provenance.v1.prov",
			"digest": "sha256:1afb01500b18f8593b254d4c0390ed1adc71e9a1d244428a6be6f13d76f79776",
			"size": 724
		},
		{
			"mediaType": "application/vnd.cncf.helm.chart.content.v1.tar+gzip",
			"digest": "sha256:99d62749d40c7a17582deb6e3a59ef619dbd1622b2e386e814e7e4151054ad34",
			"size": 3751
		}
	]
}
```

So is it just that it is not displayed within the Harbor interface? What if you try to `helm pull --verify` it?

**Comment by muhittink** [comment]
Thank you for the quick reply!
Yes, I can confirm that. It's just an issue with the Harbor UI.
`helm pull --verify` works!
I will investigate this at the harbor repository.

**Comment by MartinLoeper** [comment]
For future reference: I had to manually upload the provenance file to harbor to make it work. This was possible using the oras cli.

`oras attach --artifact-type application/vnd.cncf.helm.config.v1+json example.org/xxxx/my-helm:1.0.0 my-helm-1.0.0.tgz.prov:application/vnd.cncf.helm.chart.provenance.v1.prov`

**Comment by sabre1041** [comment]
Harbor only supports signed content using Cosign or Notary. Since helm only supports PGP, there does not appear to be any issue with Helm. I also confirmed using the latest version of Harbor that the provenance file is included as a layer within the pushed OCI based helm chart

**Comment by MartinLoeper** [comment]
Thanks for confirming @sabre1041! That explains why the artifact is still marked as not-signed in the harbor UI.
