### ISSUE TITLE
helm delete <package> does not delete pod or replicaset

### ISSUE THREAD

**Issue by dev-samples** [helm/helm#10637]
Seems `helm delete <package>` does not remove pods or replicasets that was installed as part of `helm upgrade --install <package> repo/<package>`. Pretty sure it did that at some point and I can only find this very old/related issue:

https://github.com/helm/helm/issues/747

Example:

`helm upgrade --install kube-ops-view stable/kube-ops-view --namespace test`

Followed:

`helm delete kube-ops-view --namespace test`

The pods and replicasets are still running.

I have tried with both helm 3.1.2 and 3.8.0

**Comment by yxxhero** [comment]
https://kubernetes.io/docs/concepts/architecture/garbage-collection/#owners-dependents

**Comment by SimonPfeiffer** [comment]
We are seeing the same issue after updating Kubernetes (Azure AKS) from Version 1.21 to 1.22. Seems like the replicasets are not removed.

`kubectl get rs -n <namespace>`

**Comment by SimonPfeiffer** [comment]
@yxxhero have you tried this on your side? The link provided is not really helping. I assume it is a significant bug with helm and new kubernetes versions.

**Comment by dev-dsp** [comment]
Still actual.

**Comment by yxxhero** [comment]
@dev-dsp How to reproduce your issue? Please show a example. Thanks very much.

**Comment by MageshSrinivasulu** [comment]
@simonpfeiffer where you able to fix this issue?
