### ISSUE TITLE
Error when using Helm as library (not through the cli)

### ISSUE THREAD

**Issue by revit13** [helm/helm#10631]
I get the errors below when using Helm as a library (not through the cli). I wonder if I missed initialization or misused Helm as a library. otherwise, I can open pull requests for the fixes.

Here is the call to `action.NewPullWithOpts` in our code which calls Helm's function as library: https://github.com/revit13/the-mesh-for-data/blob/helm3.8/pkg/helm/helm.go#L261

For the first error it seems that [`p.Settings`](https://github.com/helm/helm/blob/main/pkg/action/pull.go#L83) is null in pull.go which causes the fail, initializing it solves the problem -https://github.com/fybrik/helm/blob/fybrik-release-3.8/pkg/action/pull.go#L79

For the second error, it seems that `cfg.RegistryClient` is nil, initializing it solves the problem: https://github.com/fybrik/helm/blob/fybrik-release-3.8/pkg/action/action.go#L419

Here are the errors:
`
goroutine 22 [running]:
testing.tRunner.func1.2({0x234a160, 0x36c1430})
        /usr/local/go/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
        /usr/local/go/src/testing/testing.go:1212 +0x218
panic({0x234a160, 0x36c1430})
        /usr/local/go/src/runtime/panic.go:1038 +0x215
helm.sh/helm/v3/pkg/getter.collectPlugins(0x0)
        /data/revital/helm/pkg/getter/plugingetter.go:34 +0x2e
helm.sh/helm/v3/pkg/getter.All(...)
        /data/revital/helm/pkg/getter/getter.go:181
helm.sh/helm/v3/pkg/action.(*Pull).Run(0xc0001c42a0, {0xc000058750, 0x2a})
        /data/revital/helm/pkg/action/pull.go:86 +0x152
command-line-arguments.(*Impl).Pull(0xc00020b860, {0xc0000583c0, 0xd}, {0xc000058420, 0x28})
        /data/revital/the-mesh-for-data/pkg/helm/helm.go:264 +0x1b8
command-line-arguments.TestHelmRegistry(0xc00020b860)
        /data/revital/the-mesh-for-data/pkg/helm/helm_test.go:102 +0x492
testing.tRunner(0xc00020b860, 0x2681628)
        /usr/local/go/src/testing/testing.go:1259 +0x102
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1306 +0x35a
FAIL    command-line-arguments  0.663s
FAIL
`

`oroutine 34 [running]:
testing.tRunner.func1.2({0x234a160, 0x36c1430})
        /usr/local/go/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
        /usr/local/go/src/testing/testing.go:1212 +0x218
panic({0x234a160, 0x36c1430})
        /usr/local/go/src/runtime/panic.go:1038 +0x215
helm.sh/helm/v3/pkg/registry.(*Client).Pull(0x0, {0xc000059ce6, 0xc0000c3820}, {0x0, 0x0, 0x3})
        /data/revital/helm/pkg/registry/client.go:282 +0x424
helm.sh/helm/v3/pkg/getter.(*OCIGetter).get(0xc0000c3840, {0xc000059ce0, 0x30})
        /data/revital/helm/pkg/getter/ocigetter.go:53 +0x271
helm.sh/helm/v3/pkg/getter.(*OCIGetter).Get(0xc00038c960, {0xc000059ce0, 0x30}, {0xc00004f540, 0x5, 0x40})
        /data/revital/helm/pkg/getter/ocigetter.go:36 +0x70
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo(0xc0000c3ce8, {0xc000129dd0, 0x2a}, {0xc000128175, 0x1}, {0xc0001281b0, 0x27})
        /data/revital/helm/pkg/downloader/chart_downloader.go:100 +0xea
helm.sh/helm/v3/pkg/action.(*Pull).Run(0xc0001c60e0, {0xc000129dd0, 0x2a})
        /data/revital/helm/pkg/action/pull.go:129 +0xbd1
command-line-arguments.(*Impl).Pull(0xc000103520, {0xc000128150, 0xd}, {0xc0001281b0, 0x27})
        /data/revital/the-mesh-for-data/pkg/helm/helm.go:264 +0x1b8
command-line-arguments.TestHelmRegistry(0xc000103520)
        /data/revital/the-mesh-for-data/pkg/helm/helm_test.go:102 +0x492
testing.tRunner(0xc000103520, 0x2681600)
        /usr/local/go/src/testing/testing.go:1259 +0x102
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1306 +0x35a
FAIL    command-line-arguments  0.602s
FAIL
`

Output of `helm version`: version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}

**Comment by hickeyma** [comment]
@revit13 Thanks for raising this. It is required to init settings and set the `RESTClientGetter` as shown in [SDK example in the docs](https://helm.sh/docs/topics/advanced/#simple-example). It is not bug as such. 

FYI, It is on the backlog for Helm 4 to revisit the SDK and look to improve its usage.

**Comment by revit13** [comment]
@hickeyma Thanks for the answer! I'll have a look! I also opened https://github.com/helm/helm/issues/10629 and [pr](https://github.com/helm/helm/pull/10630) to make `parseReference` visible when using Helm as a library. I wonder if there is a way to use this function without this PR.

**Comment by bacongobbler** [comment]
Let's continue the discussion regarding #10629 in that ticket.

Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!

**Comment by revit13** [comment]
@hickeyma Thanks again for the link to the SDK example. In addition to what is written, I had to add an explicit setting of `client.Settings = settings` and of `RegistryClient` to avoid failure as shown below. I appreciate it if you could inform me if I should init them differently. Thanks

`var buf bytes.Buffer

settings := cli.New()
actionConfig := new(action.Configuration)
if err := actionConfig.Init(settings.RESTClientGetter(), "", os.Getenv("HELM_DRIVER"), log.Printf); err != nil {
return err
}
actionConfig.RegistryClient, err = registry.NewClient(registry.ClientOptWriter(&buf))
if err != nil {
	return err
}

client := action.NewPullWithOpts(action.WithConfig(actionConfig))`
client.Settings = settings
client.Version = chartRef.Reference
client.DestDir = destination
_, err = client.Run("oci://" + chartRef.Registry + "/" + chartRef.Repository)

**Comment by hickeyma** [comment]
@revit13 I don't think you need `registry.NewClient()`. You will need to pass `namespace` in `actionConfig.Init()`.

**Comment by revit13** [comment]
@hickeyma when removing the `actionConfig.RegistryClient, err = registry.NewClient` lines I get the following error:

`oroutine 37 [running]:
testing.tRunner.func1.2({0x234a140, 0x38bd430})
        /usr/local/go/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
        /usr/local/go/src/testing/testing.go:1212 +0x218
panic({0x234a140, 0x38bd430})
        /usr/local/go/src/runtime/panic.go:1038 +0x215
helm.sh/helm/v3/pkg/registry.(*Client).Pull(0x0, {0xc00011ecf6, 0xc00032d808}, {0x0, 0x0, 0x3})
        /data/tmp/helm/pkg/registry/client.go:282 +0x424
helm.sh/helm/v3/pkg/getter.(*OCIGetter).get(0xc00032d828, {0xc00011ecf0, 0x30})
        /data/tmp/helm/pkg/getter/ocigetter.go:53 +0x271
helm.sh/helm/v3/pkg/getter.(*OCIGetter).Get(0xc000684a00, {0xc00011ecf0, 0x30}, {0xc0001253c0, 0x5, 0x40})
        /data/tmp/helm/pkg/getter/ocigetter.go:36 +0x70
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo(0xc00032dcd0, {0xc0004323c0, 0x2a}, {0xc00011e1d5, 0x1}, {0xc00011e210, 0x28})
        /data/tmp/helm/pkg/downloader/chart_downloader.go:100 +0xea
helm.sh/helm/v3/pkg/action.(*Pull).Run(0xc0001c21c0, {0xc0004323c0, 0x2a})
        /data/tmp/helm/pkg/action/pull.go:126 +0xb91
command-line-arguments.(*Impl).Pull(0xc0005836c0, {0xc00011e1b0, 0xd}, {0xc00011e210, 0x28})
        /data/the-mesh-for-data/pkg/helm/helm.go:273 +0x24e
command-line-arguments.TestHelmRegistry(0xc0005836c0)
        /data/the-mesh-for-data/pkg/helm/helm_test.go:102 +0x492
testing.tRunner(0xc0005836c0, 0x2681618)
        /usr/local/go/src/testing/testing.go:1259 +0x102
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1306 +0x35a
FAIL    command-line-arguments  0.441s
FAIL

Also, if I do not specify `namespace` will it use all namespaces? Thanks
`

**Comment by hickeyma** [comment]
@revit13 I see it now. This is probably because of the OCI functionality.

@jdolitsky @scottrigby Do we have any example in the docs of using OCI through the SDK?

**Comment by revit13** [comment]
@jdolitsky  @scottrigby I appreciate it if you could take a look at the code snippet above and let me know if the usage is ok. Thanks
