### ISSUE TITLE
helm sign with yubikey / smartcard

### ISSUE THREAD

**Issue by BlackthornYugen** [helm/helm#10633]
The documentation appears to require that you export private keys in order to use gpg package sign.

Is there any documentation that could help someone sign using a smartcard/yubikey? Even if it can't be done with helm package --sign... is there documentation on the to be signed data structure so that I could use the gpg tools to sign directly?

**Comment by jdolitsky** [comment]
@BlackthornYugen - I've had this same issue. Checkout this plugin for yubikey support: https://github.com/technosophos/helm-gpg

**Comment by BlackthornYugen** [comment]
Thanks @jdolitsky -- looks like this should work for me. But this solution would not be interoperable with `helm install --verify` right? Both the signer and verifier need the plugin?

**Comment by jdolitsky** [comment]
@BlackthornYugen - that is correct (unfortunately).

Its worth pointing to the helm-sigstore plugin, which is another approach to Helm chart provenance via sigstore: https://github.com/sigstore/helm-sigstore

**Comment by BlackthornYugen** [comment]
@jdolitsky thanks again. Will have a look at that too.

Do you know if there is a technical reason that a signing plugin couldn't produce a compatible provenance file?

**Comment by jdolitsky** [comment]
@BlackthornYugen you might find some background on this topic here: https://github.com/helm/helm/issues/7599

**Comment by BlackthornYugen** [comment]
It looks like https://gitlab.com/MatthiasLohr/helm-sign ( thanks @MatthiasLohr! ) might be what I'm looking for. Will consider that along with the other options that have been suggested. 

Thanks!

**Comment by MatthiasLohr** [comment]
Took me one afternoon to write this little workaround tool, hoping that the feature will be covered soon by helm itself... Unfortunately, I was wrong...
