### ISSUE TITLE
Produce SPDX-format SBOM alongside release artifacts in get.helm.sh

### ISSUE THREAD

**Issue by jdolitsky** [helm/helm#10635]
ChartMuseum v0.14.0 was released yesterday. As part of this release, an SPDX-format SBOM (Software Bill of Materials) was produced at build time using the Kubernetes [`bom`](https://github.com/kubernetes-sigs/bom) CLI.

Since ChartMuseum release process was copied over from Helm's, it should be fairly straightforward to copy this process over (see [`scripts/release-artifacts.sh`](https://github.com/helm/chartmuseum/blob/main/scripts/release-artifacts.sh) and follow the [`Makefile`](https://github.com/helm/chartmuseum/blob/main/Makefile) targets). A new script [`scripts/sbom.sh`](https://github.com/helm/chartmuseum/blob/main/scripts/sbom.sh) was added to help with this, which might require a few modifications.

Related to #10634

**Comment by mattfarina** [comment]
I like the idea. I think it needs to be a HIP (and one I would review in short order).

Should the sbom be on get.helm.sh or on the GitHub release? If on get.helm.sh, how would it be named so there is a unique one for each release?

**Comment by jdolitsky** [comment]
Ok. I can take action to get this into a HIP.

As far as where it is stored... both? I'm not sure it hurts.

Similar to the release tarballs, the release version would be in the filename:
```
https://get.helm.sh/chartmuseum-v0.14.0.spdx
```
