### ISSUE TITLE
Sign release artifacts stored in get.helm.sh using sigstore cosign

### ISSUE THREAD

**Issue by jdolitsky** [helm/helm#10634]
ChartMuseum v0.14.0 was released yesterday. As part of this release, all artifacts stored in in `get.helm.sh` were signed using ephemeral GitHub OIDC tokens ("keyless" signing), and recorded in the sigstore transparency log.

Since ChartMuseum release process was copied over from Helm's, it should be fairly straightforward to copy this process over (see [`scripts/release-artifacts.sh`](https://github.com/helm/chartmuseum/blob/main/scripts/release-artifacts.sh) and follow the [`Makefile`](https://github.com/helm/chartmuseum/blob/main/Makefile) targets).

A prerequisite to this would be fully moving off of CircleCI and onto GItHub Actions for the release job.

**Comment by mattfarina** [comment]
I like this idea. I think we need a HIP for it. I would review it in short order. You might be able to combine this HIP with the sbom one around supply chain security.

**Comment by jdolitsky** [comment]
Cool, sure. I can propose a general "supply chain" HIP and try to keep it short and straightforward, including both of these.

**Comment by scottrigby** [comment]
Cross-referencing https://github.com/helm/community/issues/325
