### ISSUE TITLE
There is some issue in helm version 3.7.2 and that is we can install multiple releases with the same name within the same namespaces. 

### ISSUE THREAD

**Issue by wasim-cloud** [helm/helm#10642]
There is some issue in helm version 3.7.2 and that is we can install multiple releases with the same name within the same namespaces. Can someone from developer community check on this.

output for reference:
helm list -n edfi
NAME                 	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART                      	APP VERSION
edfi-connecter  	edfi     	2       	2022-01-21 18:09:33.2841518 +0530 IST  	deployed	edfi-0.1.0          	1.16.0
edfi-connector 	edfi     	1       	2022-02-03 16:33:25.521377174 +0530 IST	deployed	edfi-connector-0.1.0	1.16.0

helm history edfi-connecter -n edfi
REVISION	UPDATED                 	STATUS    	CHART            	APP VERSION	DESCRIPTION
1       	Fri Jan 21 18:04:08 2022	superseded	edfi-0.1.0	1.16.0     	Install complete
2       	Fri Jan 21 18:09:33 2022	deployed  	edfi-0.1.0	1.16.0     	Upgrade complete 

and the got release-name got installed with helm upgrade --install release-name -n namespace

Output of `helm version`:v3.7.2
developer@CGLX-LPT-user11:~$ helm version
version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}

Output of `kubectl version`:
developer@CGLX-LPT-user11:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS EKS

**Comment by bacongobbler** [comment]
Looks fine to me. Note that the revision field is unique. One reports it’s version 1 and another at version 2. Version 1 is in the “superseded” state, and version 2 is in the “deployed” state.

I don’t see any issue here based on the output. What issues are you experiencing?

**Comment by wasim-cloud** [comment]
two releases names are running with same name within same namespace?

**Comment by bacongobbler** [comment]
> edfi-connecter
> edfi-connector

One ends in "er" and one ends in "or". You have two unique release names.

Closing.

**Comment by wasim-cloud** [comment]
oh got it. Its a spelling mistake then

**Comment by hickeyma** [comment]
@wasim-cloud Yes, kind of.  Its just that they are 2 different/unique release names which means Helm is working as expected. I responded in the mail thread but I missed the issue open. Thanks @bacongobbler for updating the issue.
