### ISSUE TITLE
How to update apiversion of ingress in helm chart

### ISSUE THREAD

**Issue by par5706** [helm/helm#10646]
Hi Team,
Ingress betav1 is being deprecated, due to which applications are facing issues. we  Need to troubleshoot and update helm charts to latest versions.
Could anyone please help me on this how we can achieve this.

**Comment by marckhouzam** [comment]
Hi @par5706.  This is something I assume many people will need to deal with before upgrading to Kubernetes 1.22.  There may be some info posted around.  I haven't personally started working on this effort for my clusters, but I have given it a little thought.  Here are my first thoughts.  I haven't tested them so some of them may not work as I expect.  Be careful.

1. if you use public charts, you should be able to find a newer version which uses `networking.k8s.io/v1` of `Ingress`.
1. if any such public charts does not yet have such a version, they will need one, so making a PR for them will surely be appreciated
1. if you have internal charts that don't use the new version of Ingress, you will need to update them yourself
1. as for releases already on your cluster which use the deprecated version, you can do different things
    1. you can upgrade all of them using the new chart version **before** upgrading to Kubernetes 1.22
    1. you can upgrade to kube 1.22 which I believe will automatically migrate for you (you should test this well first), and then use the [helm mapkubeapis](https://github.com/helm/helm-mapkubeapis) plugin to migrate your helm releases to the new version (you should also test this first).  Without using the helm mapkubeapis plugin, you will no longer be able to upgrade using helm for releases that were not already on the new Ingress version.
    1. you may also be able use the [helm mapkubeapis](https://github.com/helm/helm-mapkubeapis) **first** to migrate all your releases to the new Ingress version before upgrading to kube 1.22.  This may be the simplest approach if it works, but I haven't had time to try it yet.

I hope this helps.

/cc @hickeyma

**Comment by hickeyma** [comment]
For releases, It seems to work best to map the APIs after upgrading to the Kubernetes version (4 ii in https://github.com/helm/helm/issues/10646#issuecomment-1029374262).
