### ISSUE TITLE
helm registry login x509: certificate relies on legacy Common Name field, use SANs instead

### ISSUE THREAD

**Issue by kirankumar26** [helm/helm#10658]
I am running helm 3.8.0, while doing helm registry login causing GET /v2/": x509: certificate relies on legacy Common Name field, use SANs instead. Even I set export GODEBUG="x509ignoreCN=0", still facing the same error.

**Comment by bacongobbler** [comment]
Hi @kirankumar26. We need more information to properly diagnose the issue. How did you set up the registry? Would you mind sharing a set of steps others can follow to help reproduce the issue?
