### ISSUE TITLE
Helm error - doesn't match $setElementOrder list intermittently

### ISSUE THREAD

**Issue by jain-tt** [helm/helm#10650]
Output of `helm version`:
v3.8.0

Output of `kubectl version`:

1.22

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  GKE

Intermittently during the helm upgrade, my release kinda struck with the "**doesn't match $setElementOrder**" error, and eventually, I have delete the deployment object manually and run the helm upgrade again.

I did not make any change in the env variables, sometimes it just successes successfully other times it just struck.

It is happening for the k8s deployment object where I am merging 2 different lists of environment variables. 

**Example:**

I have a valued file:

`
.shared: &shared
  PLATFORM: dev
  AUTH_TENANT: xyz

app1:
 environment:
  <<: *shared

app2:
  environment:
    key1: value1
    PLATFORM: dev
`

In the helm template, I have a logic:

`
containers:
      - name: dummy-apps
        image: 'test'
        env:
        {{- range $name, $value := .Values.app1.environment }}
        - name: "{{ $name }}"
          value: "{{ $value }}"
        {{- end }}
        {{- range $name, $value := .Values.app2.environment }}
        - name: "{{ $name }}"
          value: "{{ $value }}"
        {{- end }}

`

With this many times, helm release struck with "doesn't match $setElementOrder list:" error and I can see it is printing a lot of env variables. The weird part is either it should pass or fail but this error happens intermittently. If I keep on retrying it may succeed at times and started failing again.

**Comment by macobo** [comment]
I ran into a similar issue: https://github.com/helm/helm/issues/6002 gave me the needed hint, I had the same env variable set twice in the expanded manifest. :)

**Comment by Auggie321** [comment]
Hi folks,

Got this error too.
search lots of informations, but couldn't found some useful.
then i resolved this as following:
```
## helm2 environment
helm upgrade test test-5.6.7-2023.tgz -f values.yaml

got same old error
:UPGRADE FAILED
Error: The order in patch list:
[map[name:LC_ALL value:C.UTF-8] map[name:LC_ALL value:C.UTF-8]
```
then add --force, do it again successfully.
```
helm upgrade test test-5.6.7-2023.tgz -f values.yaml --force
```

after that, test new charts, use first upgrade command successfully too.

```
helm upgrade test test-5.6.8-2023.tgz -f values.yaml

Release "test" has been upgraded.
LAST DEPLOYED: Wed Mar  8 16:23:26 2023
NAMESPACE: test
STATUS: DEPLOYED
```
maybe this hint will help someone.
