### ISSUE TITLE
[lint] values.yaml: file does not exist

### ISSUE THREAD

**Issue by bentcoder** [helm/helm#10651]
Hi,

Either the [documentation](https://helm.sh/docs/helm/helm_lint/) is needs to be corrected or this bug with `helm lint` command needs to be resolved. At least if the flag is explicitly given by the user, this info is pointless.

As you can see below, description for the `-f, --values` flag for `lint` and `template` commands are exactly the same. However, the `lint` command doesn't work the way `template` does.

Thanks

---

> -f, --values strings           specify values in a YAML file or a URL (can specify multiple)

```bash
$ helm lint .helm/app --values .helm/app/values-dev.yaml
==> Linting .helm/app
[INFO] values.yaml: file does not exist

1 chart(s) linted, 0 chart(s) failed
```
---

> -f, --values strings               specify values in a YAML file or a URL (can specify multiple)

```bash
$ helm template .helm/app --values .helm/app/values-dev.yaml
// This works perfectly fine
```

---

**Environment**

```bash
$ helm version
version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GoVersion:"go1.17.6"}
```

```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GoVersion:"go1.15.3", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2",GoVersion:"go1.15", Platform:"linux/amd64"}
```

```bash
$ minikube version
minikube version: v1.14.2
```

**Comment by bacongobbler** [comment]
Is there a values.yaml file next to your Chart.yaml?

**Comment by bentcoder** [comment]
No because I have specific multiple ones with different names for the same purpose.

**Comment by bacongobbler** [comment]
Try placing an empty values.yaml file in your chart.

As per the [Chart File Structure](https://helm.sh/docs/topics/charts/), a default values.yaml is required IIRC.

**Comment by bentcoder** [comment]
It feels like a hack to be fair :)
