### ISSUE TITLE
defining a problem after helm lint

### ISSUE THREAD

**Issue by ramazansakin** [helm/helm#10652]
Output of `helm version`:
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"windows/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Minikube

Question:
I'm getting this error when I lint my chart:
[ERROR] Chart.yaml: version should be of type string but it's of type float64

what does this mean? I couldnt find any sensible answer on web, any help would be nice ?

Thanks

**Comment by hickeyma** [comment]
@ramazansakin To get a better understanding, do you mind showing the your `version` property?

**Comment by ramazansakin** [comment]
No, actually its just as default:
![image](https://user-images.githubusercontent.com/9968219/152780517-3b9757b8-3713-4b0f-bd92-36954f50f7b0.png)

**Comment by ramazansakin** [comment]
Btw, I m trying to upgrade my traefik version v1.5.4-alpine to v2.5.0.

**Comment by hickeyma** [comment]
Helm uses [Semantic Versioning 2](https://semver.org) for [Version Numbers](https://helm.sh/docs/chart_best_practices/conventions/#version-numbers). 

Testing this, it works as `1.0.0` or as a string of `"1.0"`.

It looks like the error message is returned by [Masterminds semver constraint](https://github.com/Masterminds/semver/blob/master/constraints.go#L79) when it is checks for [constraint in Helm lint rule](https://github.com/helm/helm/blob/main/pkg/lint/rules/chartfile.go#L136-L144).

@mattfarina You might be able to shed some light why it works like this.

**Comment by ramazansakin** [comment]
Thanks @hickeyma , it disappered after converting to string :)
