### ISSUE TITLE
Helm is interpreting commas in passwords wrongly when using --set or --set-string

### ISSUE THREAD

**Issue by anetbnd** [helm/helm#10663]
I want to pass randomly generated (long) passwords to `helm install` and `helm upgrade`. For this I use `--set` or `--set-string`.
However, if the password contains `,` or `\` then it is wrongly handled by helm, because those characters have a special meaning for helm. 

The passwords are generated automatically, so I cannot change them inside the process. The only workaround I could imagine is to have a script, running before the helm command and introduce encapsulation if necessary. But I also know, that this issue is a big issue for many people since 6 year (!):

* https://github.com/helm/helm/issues/1556
* https://github.com/helm/helm/pull/1576
* https://github.com/helm/helm/issues/1556
* https://github.com/helm/helm/pull/9182

So, when people over 6 years complain again and again about this issue and even provided help in creating pull requests (see the `--set-literal` pull-request #9182), then I cannot understand, why this is still an issue. Obviously there is a real usecase for helm to assign plain literals to variables without any change in it. So why is this usecase not addressed? Why force people working with helm introducing ugly workarounds and spending sometimes days of bug hunting, just because the behavior of helm in this regard is not intuitive? 

Output of `helm version`: 
```
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"windows/amd64"}
```

**Comment by bacongobbler** [comment]
Let’s continue the discussion in #9182. In the future please kindly ask to reopen a ticket to carry on a discussion before opening a new ticket.

I’ve approved the PR. It just needs another maintainer to approve before it can be merged.

Thank you for bringing this up.
