### ISSUE TITLE
Download file from template

### ISSUE THREAD

**Issue by yeplaa** [helm/helm#10660]
In my Helm template, i need to generate a configmap with the file content downloaded from a remote url. This list of remote url will setted by the user with the values. 
So, i need to download a file directly by Helm but i don't found the feature. It it possible? Have you an idea how i could integrate my need? 

Thanks

Output of `helm version`: 
version.BuildInfo{Version:"v3.7+unreleased", GitCommit:"8ca401398d8b6dfd41b46f446abcd5285e219829", GitTreeState:"clean", GoVersion:"go1.17.3"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v0.21.0-beta.1", GitCommit:"88e7eba36ac7cc026d064bb6e4a988acc18a144e", GitTreeState:"clean", BuildDate:"2021-11-04T19:40:22Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.11", GitCommit:"27522a29febbcc4badac257763044d0d90c11abd", GitTreeState:"clean", BuildDate:"2021-09-15T19:16:25Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  Rancher 2.5

**Comment by bacongobbler** [comment]
This is not possible as it poses a security risk. Your best bet would be to download the file prior to `helm install|upgrade|template`.

**Comment by yeplaa** [comment]
Thanks @bacongobbler for your reply. Unfortunately, i can't download the file before the helm install because my chart will hosted on the Marketplace UI. I haven't used yet the hook pre-install, but maybe i could download from a container my files and then updated the content of my configmap. But it's not a nice solution..

**Comment by yeplaa** [comment]
Have you an another idea? What do you think? Thanks
