### ISSUE TITLE
Override Push Location

### ISSUE THREAD

**Issue by rpf3** [helm/helm#10675]
Output of `helm version`:
> version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}

I am trying to push both a Docker image as well as a Helm chart into Amazon ECR.  My Chart.yaml has `name: my-app` but I want to be able to push these charts into an ECR repository called `my-app/helm` similar to my Docker images which are pushed to `my-app/docker`.  I cannot use the same ECR repository because of tag collisions and I'd prefer not to name my Helm chart anything `my-app-helm`.

Is there a way to override the location of `helm push` so that it isn't dependent on the `name` in the Chart.yaml file?  Am I barking up the wrong tree here entirely?

**Comment by bacongobbler** [comment]
`helm push` accepts a path in the repository field, so if you want a chart named “foo” in the “my-app” org, you can use `helm push . oci://example.com/my-app`. Have you tried that yet?

From the docs:

```
$ helm push mychart-0.1.0.tgz oci://localhost:5000/helm-charts
Pushed: localhost:5000/helm-charts/mychart:0.1.0
Digest: sha256:ec5f08ee7be8b557cd1fc5ae1a0ac985e8538da7c93f51a51eff4b277509a723
```

https://helm.sh/docs/topics/registries/

**Comment by bacongobbler** [comment]
The chart name and repository name must match,m. It is not possible to use a name that does not match the chart at this time.

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!

**Comment by rpf3** [comment]
Is this something that might be a valuable feature for someone to work on or would it not be worth my time to investigate it?

**Comment by tisonkun** [comment]
@bacongobbler this causes users need to have both `org` and `orgcharts` org if they want to use the same name for the app image and the helm charts OCI artifacts.

Any changes since then we can set the chart name to `product` while the OCI artifact can be `org/product-charts`?
