### ISSUE TITLE
trying to delete a template file in a repo after adding it, how to do it?

### ISSUE THREAD

**Issue by ngingihy** [helm/helm#10679]
Output of `helm version`: "v3.7.2"

Output of `kubectl version`: 1.20

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  pivotal cloud foundry

**Comment by hickeyma** [comment]
@ngingihy You would require to update the chart to the next version with the template removed. Then upload it to the repo. You cannot do it on the fly.
