### ISSUE TITLE
apt repository missing origin value

### ISSUE THREAD

**Issue by wyuenho** [helm/helm#10676]
I've followed the [instructions](https://helm.sh/docs/intro/install/#from-apt-debianubuntu) to installed Helm using apt. However, when configuring `unattended-upgrade`, I issued the command `apt-cache policy` to take a look at the `o=` field for the Helm repo, but noticed it's missing. Which means I can't configure unattended-upgrade for Helm because the [configuration](https://github.com/mvo5/unattended-upgrades#supported-options-reference) requires both the `o=` and `a=` fields to be present.

**Comment by bacongobbler** [comment]
As the instructions laid out, this is maintained by the helm community and is not an official helm project. More specifically it is maintained by the kind folks at Balto CDN. Please reach out to them for further assistance. Thanks.
