### ISSUE TITLE
support `upgrade --wait` for CRDs

### ISSUE THREAD

**Issue by SilverChard** [helm/helm#10671]
1. should `waitForResources` support register some func let developer who use helm pkg wait for CRD ready?
2. is there a plan to support a 3-way merger of CRDs?

**Comment by bacongobbler** [comment]
Unfortunately, Helm does not provide any support around upgrading CRDs. See [HIP 11](https://github.com/helm/community/blob/main/hips/hip-0011.md) for more details.

if you have suggestions/improvements for the SDK, please feel free to provide a patch and we'll review it.
