### ISSUE TITLE
Restart of completed pod or  job when i launch helm upgrade

### ISSUE THREAD

**Issue by yeplaa** [helm/helm#10688]
In my Helm chart, i deploy a pod that is completed once the script related is terminated. I could also used a K8s job for my use-case. 
I need that my pod (or job) is restarted when i launch a **Helm upgrade**. So the annotation added in my pod don't work...

The only solution that i found is the **post-upgrade Hook** usage in my pod. 
As indicated in the Hook documentation : 

_If the resource is a Job or Pod kind, Helm will wait until it successfully runs to completion. And if the hook fails, the release will fail. This is a blocking operation, so the Helm client will pause while the Job is run._

The pod restart works, but I would like Helm will not wait until it successfully runs to completion because the Chart will deployed from GUI MarketPlace. The treatment can be long..
Is it possible to avoid this pause with hook usage? Or without Hook usage, do you known how i could restart my pod when i launch Helm upgrade?

Output of helm version:
version.BuildInfo{Version:"v3.7+unreleased", GitCommit:"8ca401398d8b6dfd41b46f446abcd5285e219829", GitTreeState:"clean", GoVersion:"go1.17.3"}

Output of kubectl version:

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v0.21.0-beta.1", GitCommit:"88e7eba36ac7cc026d064bb6e4a988acc18a144e", GitTreeState:"clean", BuildDate:"2021-11-04T19:40:22Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.11", GitCommit:"27522a29febbcc4badac257763044d0d90c11abd", GitTreeState:"clean", BuildDate:"2021-09-15T19:16:25Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Rancher 2.5

**Comment by bacongobbler** [comment]
Please refer to “automatically roll deployments” under the Chart Tips and Tricks Guide. 

https://helm.sh/docs/howto/charts_tips_and_tricks/

**Comment by yeplaa** [comment]
@bacongobbler I tried to use “automatically roll deployments” feature but it doesn't work with pod/job because the pod/job is stopped, completed. It works with a pod running but maybe not with a pod stopped.

What do you think?

**Comment by joejulian** [comment]
Jobs aren't re-run if their definition is changed. What if you use [generateName](https://kubernetes.io/docs/reference/using-api/api-concepts/#generated-values) instead to ensure a new job is created with each helm upgrade?

**Comment by yeplaa** [comment]
_generateName_ doesn't work on Helm. It seems not supported. 

But as indicated  https://github.com/helm/helm/issues/3348  i added {{ .Release.Revision }} in my job name and it works !!

Thanks for your help.
