### ISSUE TITLE
installing kong from github repo

### ISSUE THREAD

**Issue by ngingihy** [helm/helm#10680]
Output of `helm version`: 3.7.2          

Output of `kubectl version`: 1.2 
 
Cloud Provider/Platform (AKS, GKE, Minikube etc.): pivotal cloud foundry

I'm trying to install KONG chart but i just want to exclude one file from its templates, so i forked the repo deleted the file and trying to install from the forked public repo.

`helm repo add charts https://github.com/ngingihy/charts`

this is the error i keep getting 

`Error: looks like "https://github.com/ngingihy/charts" is not a valid chart repository or cannot be reached: failed to fetch https://github.com/ngingihy/charts/index.yaml : 404 Not Found`

any help on how to fix this?

**Comment by hickeyma** [comment]
If you want to use your fork then you need to setup a Helm chart repo in GH. This is a good blog on how to do it: https://medium.com/@mattiaperi/create-a-public-helm-chart-repository-with-github-pages-49b180dbb417

Alternatively, you could just download the chart (`helm pull`), extract it and then install the chart from the filesystem.

**Comment by bridgetkromhout** [comment]
As @hickeyma stated, a github repo can be used as a helm chart repository, but you do need to configure it. Here is the info in the docs that explains how: https://helm.sh/docs/topics/chart_repository/#github-pages-example

**Comment by hickeyma** [comment]
Thanks @bridgetkromhout for adding the Helm docs link.
