### ISSUE TITLE
Cant pull images from ECR OCI repo with Helm 3.8.0

### ISSUE THREAD

**Issue by gotpist1** [helm/helm#10697]
Output of `helm version`: 3.8.0

Output of `kubectl version`: 1.23.3

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS and minikube locally

When trying to pull a helm chart with this command
`helm pull --untar oci://<registry>.dkr.ecr.eu-west-1.amazonaws.com/<repository> --untardir "dir" --version podname-2.16.0`

We get this output:
`Unable to locate any tags in provided repository: oci://<registry>.dkr.ecr.eu-west-1.amazonaws.com/<repository>`

When Executing the same command in helm 3.7.1, it works just fine. After reading this: https://github.com/helm/helm/issues/8090

i have omitted the real registry end repository btw.

My guess is it has something to do with our strange "version" which is a tag. Unfortunately, we can't change the tag names.

If not, something has changed and is not documented.

Any help is much appreciated!

**Comment by jdolitsky** [comment]
The version `podname-2.16.0` appears to be invalid semver, which is probably why it is looking for matching tags. Can you try `2.16.0` instead?

You probably want
```
helm pull --untar oci://<registry>.dkr.ecr.eu-west-1.amazonaws.com/<repository>/podname \
  --untardir "dir" --version 2.16.0
```

cc @sabre1041 @scottrigby

**Comment by sabre1041** [comment]
@jdolitsky @gotpist1 Thats correct. strict SemVer is now enforced which is why it is unable to locate a valid version

**Comment by gotpist1** [comment]
> The version `podname-2.16.0` appears to be invalid semver, which is probably why it is looking for matching tags. Can you try `2.16.0` instead?
> 
> You probably want
> 
> ```
> helm pull --untar oci://<registry>.dkr.ecr.eu-west-1.amazonaws.com/<repository>/podname \
>   --untardir "dir" --version 2.16.0
> ```
> 
> cc @sabre1041 @scottrigby

Unfortunately, no. The structure is set up so that the different charts are located under the same root, but with specific tags for each image. If there was a possibillity to use the digest, that would work to. But i cant find anything on that either. So i guess our only bet is to keep using 3.7.1 then?

It would have been nice if helm allowed a specific tag instead of only enforce semver.

**Comment by jdolitsky** [comment]
@gotpist1 - I guess my question would be how did you upload this chart? `helm push` should enforce semver just as `helm pull` does. Perhaps this was not the case with previous revisions (`helm chart push` etc.)

**Comment by gotpist1** [comment]
@jdolitsky The push was created using an earlier version of helm, when this was not enforced :/

**Comment by sabre1041** [comment]
@gotpist1 You can use tools like `skopeo` or `crane` to copy the existing chart into a tag that is using a valid semver reference
