### ISSUE TITLE
[Question] How do you manage one-off jobs?

### ISSUE THREAD

**Issue by Warxcell** [helm/helm#10696]
Lets say you have a set of pre-defined commands which can be ran - how do you manage them with helm ?

For example: you have 2 jobs to run tests:
Currently I'm doing a two Jobs with `spec.suspend: true` which are loaded into K8s as template and then bash scripts, basically takes the `spec.template.spec` of Job and creates a Pod with these specs.

```
namespace=input from user
context=input from user
jobName=input from user

specTemplate=$(kubectl get job $jobName --context $context --namespace $namespace -o json | jq '.spec.template.spec')

if [ $# -ne 0 ]; then
  specTemplate=$(echo "$specTemplate" | jq --arg args $1 '.containers[0].args = []')

  for arg in "$@"; do
    specTemplate=$(echo "$specTemplate" | jq --arg arg $arg '.containers[0].args |= . + [$arg]')
  done
fi

podManifest="
{
  \"apiVersion\": \"v1\",
  \"kind\": \"Pod\",
  \"metadata\": {
    \"name\": \"tests\"
  },
  \"spec\": $specTemplate
}"

function delete() {
  echo "$podManifest" | kubectl delete -f - --namespace $namespace --context $context --ignore-not-found=true
}

delete
echo "$podManifest" | kubectl apply -f - --namespace $namespace --context $context

trap delete INT

kubectl wait --for=condition=Ready pod/tests --namespace $namespace --context $context
kubectl attach tests --namespace $namespace --context $context --container tester

```

The problem with this variant is that Jobs are immutable, so once loaded - if upgraded - it will fail and require manual intervention to fix the issue. Tried also with mark the job with `"helm.sh/hook": post-install,post-upgrade` and `"helm.sh/hook-delete-policy": before-hook-creation`, so helm could delete the Job before new release is upgraded, but another issue raised: helm waits for job to complete, but it never runs in a first place, because of `spec.suspend: true` - https://github.com/helm/helm/issues/10555

Other thing I was thinking is to create a suspended cronjob and then `kubectl create job YY --from=cronjob/XX` or use it as template with the script above.

Are there any other variants?

**Comment by joejulian** [comment]
Typically, helm would be used to template the Job you want to create and that template would be the source of truth. It sounds like you're trying to use Jobs in the api as a template instead of as Jobs. Maybe `helm template` might fit that need better?

**Comment by Warxcell** [comment]
@joejulian but that would mean `prepare again all the values, as for the original helm upgrade command` 
Furthermore: helm template doesn't attach you to running job. The idea is to have a simple command:

`run tests release_name` which creates pod, attach to it, and removes it upon completion, rather than

```
helm template release_name -f values.yaml -f values2.yaml -f values3.yaml --set-file blabla=file.json --set someRandomVar=value
kubectl attach -it pod/release_name_job_name
kubectl delete -it pod/release_name_job_name
```

**Comment by joejulian** [comment]
Your own suggestion is very close. Your helm chart would only have a Pod resource, then you would:
```
helm template release_name -f values.yaml -f values2.yaml -f values3.yaml \
    --set-file blabla=file.json --set someRandomVar=value \
    -s templates/job-tests.yaml | kubectl apply -f -
kubectl attach -it pod/release_name_job_name
kubectl delete -it pod/release_name_job_name
```

**Comment by Warxcell** [comment]
What do you think for feature that stores pod manifest somewhere as metadata and then have commands like 

`helm command list $releaseName` which will list all stores manifests
`helm command run --rm -it -c $containerName $commandName $releaseName --args ["arg1", "arg2"] ` (`-c $containerName required only if more than one container`, `--args` also optional, allow overwriting of default args from the manifest)

These pod manifests can be marked with `"helm.sh/command-template": "true"`

It will ease a lot local development where you need to run some commands frequently and also running one-off commands, which are not part of the release cycle itself. Honestly `helm template --passing values` etc then attach && delete, could take few minutes to setup - its way too much hassle.

**Comment by joejulian** [comment]
The command you're suggesting would need a [hip(helm improvement proposal)](https://github.com/helm/community/tree/main/hips) written. See [hip-0001](https://github.com/helm/community/blob/main/hips/hip-0001.md) for instructions on how to write that up.

As for this specific support request, since you have a working solution, I'm going to go ahead and close this issue. Feel free to reopen it if you feel you're still blocked.
