### ISSUE TITLE
Odd behavior with empty lists, concat, and toJson

### ISSUE THREAD

**Issue by mcg1969** [helm/helm#10699]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  Minikube 1.25.1

Odd behavior of the Helm/Spring `concat` function with regards to empty lists:

Input:
```
# {{ list | toJson }}
# {{ concat (list) (list) | toString }}
# {{ concat (list) (list) | toJson }}
# {{ dict | toJson }}
# {{ merge (dict) (dict) | toString }}
# {{ merge (dict) (dict) | toJson }}
```
What I would expect:
```
# []
# []
# []
# {}
# map[]
# {}
```
What I actually get: in the `concat` case, a `null` instead of the empty list.
```
# []
# []
# null
# {}
# map[]
# {}
```
I've already worked around this, but I wanted to report it and see if this is intended behavior—because if it is, the [docs](https://helm.sh/docs/chart_template_guide/function_list/#concat) do not indicate this would be the behavior. Perhaps there is a subtlety of the JSON standard I'm missing!

**Comment by bacongobbler** [comment]
hmm... Functions like `concat` are provided by third-party libraries. Specifically [`sprig`](/Masterminds/sprig). I would file issues related to function output there. When a fix has been made upstream, we can bump to the latest version of sprig and receive the fix.

Thanks for the report.

**Comment by bacongobbler** [comment]
however, if it's `toJson` that may be the culprit, here's the source for that: https://github.com/helm/helm/blob/a499b4b179307c267bdf3ec49b880e3dbd2a5591/pkg/engine/funcs.go#L140-L147

**Comment by mcg1969** [comment]
The problem is that I don't know for sure if the culprit is sprig or Helm's use of it. The fact that the `toString` form is correct but `toJson` is not suggests it's the latter. Again, no worries, I have a workaround for this already, but I do think it's worth figuring out for future users.

I suppose I should have tested `toYaml` as well...

**Comment by Tommyf** [comment]
I just ran into this exact issue, but with `toYaml`.

For now, I need to use a workaround if I am likely to be using `concat` on potentially empty lists.

Do we know if this is a problem with the `concat` function in Sprig, or the `toYaml`/`toJson` functions in Helm?

**Comment by joejulian** [comment]
Doesn't look to be a helm problem. See this [go-template playground](https://repeatit.io/#/share/eyJ0ZW1wbGF0ZSI6Int7IHR5cGVPZiBsaXN0IH19XG57eyB0eXBlT2YgKGNvbmNhdCBsaXN0IGxpc3QpIH19XG57eyB0b0pzb24gbGlzdCB9fVxue3sgdG9Kc29uIChjb25jYXQgbGlzdCBsaXN0KSB9fVxuXG4iLCJpbnB1dCI6IiIsImNvbmZpZyI6eyJ0ZW1wbGF0ZSI6InRleHQiLCJmdWxsU2NyZWVuSFRNTCI6ZmFsc2UsImZ1bmN0aW9ucyI6WyJzcHJpZyJdLCJvcHRpb25zIjpbImxpdmUiXSwiaW5wdXRUeXBlIjoieWFtbCJ9fQ==) example.
