### ISSUE TITLE
Error: INSTALLATION FAILED: configmaps "my-configmap-name" already exists

### ISSUE THREAD

**Issue by mdbr000** [helm/helm#10705]
I have a chart that references another 3rd party chart as a dependency using the `dependencies` directive in `Chart.yaml`.  This 3rd party chart creates a default ConfigMap that is to be overwritten by the operator with custom values, if needed.  To do this, the 3rd party docs indicate that the ConfigMap must be overwritten using the same name as the default ConfigMap they provide.  Their documentation gives an example where `kubectl` is used to apply the ConfigMap *after* installation.

I have the need to define my own ConfigMap  to override the 3rd party ConfigMap, and have placed this ConfigMap in my chart folder as a template.  Helm seems to have an issue with this.  It will throw the following error during a `helm install`: `Error: INSTALLATION FAILED: configmaps "my-configmap-name" already exists.

Is there a workaround to this issue? I need to have the installation of this chart completely automated and scriptable, with no required "post processing" with kubectl necessary in order to apply my custom ConfigMap settings to the installation.

Helm version: version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}

Output of `helm version`: `version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}`

Output of `kubectl version`: `Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"f59f5c2fda36e4036b49ec027e556a15456108f0", GitTreeState:"clean", BuildDate:"2022-01-19T17:33:06Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  Minikube

**Comment by joejulian** [comment]
Best case, the 3rd party chart has a way to disable the creation of that configmap.

If not, the best I've got is to use a post-install hook to use the `bitnami/kubectl` container to `kubectl apply` the desired data to the configmap.

**Comment by ankitjain28may** [comment]
I am having the same issue, do we have any workaround for this?

**Comment by ankitjain28may** [comment]
JFYI: For the workaround, I used the post-install, post-upgrade hooks to my custom templates. Since my custom templates are secrets and config maps, I need my deployment to use the latest changes to my cm, and secrets, I added post hooks to my deployment entity as well through `values.yaml` which generally all helm charts support (Passing annotations via values.yaml to deployments).
