### ISSUE TITLE
Invalid value for default var

### ISSUE THREAD

**Issue by lokinehn** [helm/helm#10709]
Hello!
I'm getting error while creating a helm update 

> Error: template: isochron-map/templates/_helpers.tpl:18:16: executing "isochron-map.fullname" at <$name>: invalid value; expected string
> helm.go:84: [debug] template: isochron-map/templates/_helpers.tpl:18:16: executing "isochron-map.fullname" at <$name>: invalid value; expected string

I don't understand what is wrong here, because identical projects with the same configured charts work well

Part of helpers with defining var (created by default):

> {{- define "isochron-map.fullname" -}}
> {{- if .Values.fullnameOverride }}
> {{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
> {{- else }}
> {{- $name := default .Chart.Name .Values.nameOverride }}
> {{- if contains $name .Release.Name }}
> {{- .Release.Name | trunc 63 | trimSuffix "-" }}
> {{- else }}
> {{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
> {{- end }}
> {{- end }}
> {{- end }}

Part of Values with this variables:
 
> nameOverride: "isochron-map"
> fullnameOverride: "isochron-map"

Chart.yaml:

> apiVersion: v2
name: isochron-map
description: A Helm chart for Kubernetes for isochron-map project
type: application
version: 0.1.0
appVersion: "$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID"

Helm version:
version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}

Kubectl version:
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:00:47Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.20) exceeds the supported minor version skew of +/-1

**Comment by joejulian** [comment]
I tried to duplicate your issue using the bits that you included and didn't have any luck. Can you come up with something step-by-step that you can share that will cause this issue?

**Comment by lokinehn** [comment]
> I tried to duplicate your issue using the bits that you included and didn't have any luck. Can you come up with something step-by-step that you can share that will cause this issue?

Okay, should i send here all not working helm chart with templates?

**Comment by joejulian** [comment]
You can create a tarball and attach it to the issue, I think. I've never done that with a tarball, but I have included a gif before. The textbox I'm typing this in says, "Attach files by dragging & dropping, selecting or pasting them." so I think it should work.

**Comment by bacongobbler** [comment]
Yes. The best option would be to attach the tarball that `helm package` generates. That way we have the same helm chart to test against. A code author can then use that chart as a unit test against their bugfix.

**Comment by lokinehn** [comment]
Okay, i've found a cause of the error. It was wrong template syntax in configmap manifest.
Thanks all for respondning!
