### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by j-zimnowoda** [helm/helm#10702]
Big files, a lot of flow control statements, loops etc.,
I am getting lost in finding context for a given `{{ end }}` statement 😟 

Currently, I either indent flow control statements or put comments after `{{ end }}` statement. But perhaps there are better solutions 💡 

I am wondering about your best practices.

**Comment by bacongobbler** [comment]
Hi @j-zimnowoda, the document for best practices for chart templates can be found here: https://helm.sh/docs/chart_best_practices/templates/

If you have additional suggestions, please feel free to contribute to [helm/helm-www](/helm/helm-www).

Thanks!
