### ISSUE TITLE
Failed to create pod after rollback

### ISSUE THREAD

**Issue by victorguosh** [helm/helm#10703]
As described in https://github.com/helm/helm/issues/6036, Do the three steps to reproduce (copied from https://github.com/helm/helm/issues/6036) :
1)Install helm chart version 0.1.0 from attachment. This chart version doesn't have service account. Verify that pods are in running state.
2) Perform helm upgrade with chart version 0.1.4 from attachment. This chart version brings in service account "hello-world-sa". Verify that pods are in running state.
3) Perform a helm rollback to previous version.
The above three steps **succeed.**
After rollback, do 
step 4) **Delete one running pod, then it is found that new pod will not be created after the running pod is deleted.**
**Normally because the replicas is 2, a new pod should be created.**

After check the replicaset.app as below:
kubectl -n test describe replicaset.app/hello-world-5d8d55497f
Name:           hello-world-5d8d55497f
...
Events:
  Type     Reason        Age                  From                   Message
  ----     ------        ----                 ----                   -------
  Warning  FailedCreate  74s (x17 over 115s)  replicaset-controller  Error creating: pods "hello-world-5d8d55497f-" is forbidden: error looking up service account test/hello-world-sa: serviceaccount "hello-world-sa" not found

The failure of pod creation is caused by the serviceAccount.  
Check the deployment after rollback, 
kubectl -n test get deployment  hello-world -o yaml
...
      serviceAccount: hello-world-sa
      serviceAccountName: hello-world-sa
...
The serviceACcount exists in the K8S resource depoyment hello-world, but it does not defined in the hello-world-0.1.0 helm tgz package.

Output of `helm version`:
version.BuildInfo{Version:"v3.7.1", GitCommit:"23c99f11754e1b4ac585e2f1d2d1be59a611a2d2", GitTreeState:"clean", GoVersion:"go1.16"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"49499222b0eb0349359881bea01d8d5bd78bf444", GitTreeState:"clean", BuildDate:"2021-12-14T12:50:25Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"49499222b0eb0349359881bea01d8d5bd78bf444", GitTreeState:"clean", BuildDate:"2021-12-14T12:41:40Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
cncf

**Comment by yxxhero** [comment]
@victorguosh https://github.com/kubernetes/kubernetes/issues/108208 please see.

**Comment by victorguosh** [comment]
> @victorguosh [kubernetes/kubernetes#108208](https://github.com/kubernetes/kubernetes/issues/108208) please see.

Thanks for your information. It is mostly the cause of this issue.
