### ISSUE TITLE
template --pre-render option

### ISSUE THREAD

**Issue by Diliz** [helm/helm#10704]
Hello there!

First, thanks for your hard work :)

I encountered a need and I don't think I'm the only one who wants to do that, I would love to have a pre-render option for the template command.

The use case:

I got multiple applications, deployed the same way with helm charts and kustomize.
Actually kustomize let me injects labels on specific ressources , but I need to statically define each infra-environnements, I can't do logical stuff there.

And here's the catch, I want to enforce specific rules on this labels to be able to not let anybody else put some bad labels there, and then manage this "labels rules" in the helm charts build and release ci steps.

Having a pre-render kustomize capacity would let me use helm templates in kustomize, and will be able to inject this labels before the template is rendered, and use variables defined in the values.yml or given in the environment when deploying, giving me the possibility to use kustomize injection dynamically.

Dunno if there's a way to do this, but I think it's not a bad feature to add :)

**Comment by joejulian** [comment]
Would the `post-renderer` flag do what you're looking for? You could run it with the template command:

```
      --post-renderer postrenderer   the path to an executable to be used for post rendering. If it exists in $PATH, the binary will be used, otherwise it will try to look for the executable at the given path (default exec)
```

**Comment by Diliz** [comment]
Actually I want to inject template in an already packaged helm chart template, without injecting any values in it.

My use case is to add annotations template in an already existing helm chart (which does not have annotations), without having to mirror it or edit the original charts themselves, and before applying values to the templates, like what kustomize do, but before applying values to the templates... In a pre render hook or something else.

The only "way" I found to stay with a full helm / kustomize stack is to use a job I which will act as an injector, like for the vault injector.

**Comment by Diliz** [comment]
For more information, I opened an issue in kustomize as well: https://github.com/kubernetes-sigs/kustomize/issues/4519
