### ISSUE TITLE
How to ensure that subchart is installed before the parent chart?

### ISSUE THREAD

**Issue by davinder2385** [helm/helm#10713]
The parent chart depends on a subchart. I want to ensure that the subchart is installed first when executing helm install, and then install the parent chart. What should I do? I need help, please.

Output of `helm version`:
version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2+k3s1", GitCommit:"5a67e8dc473f8945e8e181f6f0b0dbbc387f6fca", GitTreeState:"clean", BuildDate:"2021-06-21T20:52:44Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2+k3s1", GitCommit:"5a67e8dc473f8945e8e181f6f0b0dbbc387f6fca", GitTreeState:"clean", BuildDate:"2021-06-21T20:52:44Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  rancher/k3s

**Comment by bacongobbler** [comment]
Helm is not designed to accommodate this workflow. Helm templates every chart’s templates at once, then submits every resource to kubernetes at once.

It’s worth keeping in mind that Kubernetes (and by extension, Helm) is a declarative system, where a manifest declares the desired state. Handling IFTTT (if-this-then-that) sort ordering as described here are characterized as imperative systems.

Chart hooks are an exception to the rule, which allow the chart author to declare certain resources to exist before or after the main `helm install` control loop has completed execution.

Hope this helps.

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!
