### ISSUE TITLE
helm install throws error: tag explicitly required

### ISSUE THREAD

**Issue by dmoeff** [helm/helm#10718]
After running: 
helm install myhelmtest oci://myregistry.azurecr.io/helm/mychart --version 0.7.0 --debug

I am getting an error:
install.go:173: [debug] Original chart version: "0.7.0"
Error: tag explicitly required
helm.go:81: [debug] tag explicitly required
helm.sh/helm/v3/internal/experimental/registry.(*Client).PullChart
        /home/circleci/helm.sh/helm/internal/experimental/registry/client.go:153
helm.sh/helm/v3/pkg/getter.(*OCIGetter).get
        /home/circleci/helm.sh/helm/pkg/getter/ocigetter.go:52
helm.sh/helm/v3/pkg/getter.(*OCIGetter).Get
        /home/circleci/helm.sh/helm/pkg/getter/ocigetter.go:36
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo
        /home/circleci/helm.sh/helm/pkg/downloader/chart_downloader.go:99
helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart
        /home/circleci/helm.sh/helm/pkg/action/install.go:675
main.runInstall
        /home/circleci/helm.sh/helm/cmd/helm/install.go:185
main.newInstallCmd.func2
        /home/circleci/helm.sh/helm/cmd/helm/install.go:120
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:80
runtime.main
        /usr/local/go/src/runtime/proc.go:204
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1374

Any idea why?

**Comment by bacongobbler** [comment]
Which version of Helm is this?

**Comment by bacongobbler** [comment]
ping.
