### ISSUE TITLE
Test-style error running make test with golangci-lint version 1.44.2 

### ISSUE THREAD

**Issue by jsolana** [helm/helm#10711]
Hi!

I want to contribute to the project. After read the **[developers guide](https://helm.sh/docs/community/developers/)**  when run `make test'  I received the next result:

`
make test
GO111MODULE=on go build  -trimpath -tags '' -ldflags '-w -s -X helm.sh/helm/v3/internal/version.metadata=unreleased -X helm.sh/helm/v3/internal/version.gitCommit=65d8e72504652e624948f74acbba71c51ac2e342 -X helm.sh/helm/v3/internal/version.gitTreeState=dirty -X helm.sh/helm/v3/pkg/lint/rules.k8sVersionMajor=1 -X helm.sh/helm/v3/pkg/lint/rules.k8sVersionMinor=23 -X helm.sh/helm/v3/pkg/chartutil.k8sVersionMajor=1 -X helm.sh/helm/v3/pkg/chartutil.k8sVersionMinor=23' -o '/home/javi/go/src/helm.sh/helm/bin'/helm ./cmd/helm
GO111MODULE=on golangci-lint run
internal/test/test.go:91:24: error-strings: error strings should not be capitalized or end with punctuation or a newline (revive)
		return errors.Errorf("does not match golden file %s\n\nWANT:\n'%s'\n\nGOT:\n'%s'\n", filename, expected, actual)
		                     ^
make: *** [Makefile:116: test-style] Error 1

`

Output of `helm version`:

version.BuildInfo{Version:"v3.8+unreleased", GitCommit:"65d8e72504652e624948f74acbba71c51ac2e342", GitTreeState:"dirty", GoVersion:"go1.17.7"}

Output of `golangci-lint --version`:
golangci-lint has version 1.44.2 built from d58dbde5 on 2022-02-17T20:58:06Z

Removing the newline  fix the problem in 'internal/test/test.go':

`
return errors.Errorf("does not match golden file %s\n\nWANT:\n'%s'\n\nGOT:\n'%s'", filename, expected, actual)
`
Kind regards

**Comment by joejulian** [comment]
The newer linters are much more opinionated about how to do errors in go. I'm sure the core maintainers would be happy to have PRs that address issues found in newer linters. Thanks for bringing this up.
