### ISSUE TITLE
Generate a binary release for MacOS arm architecture.

### ISSUE THREAD

**Issue by david-streamlio** [helm/helm#10712]
The new MacBooks use an M1 chipset that is not compatible with the amd64 distribution of Helm, so it would be nice if a binary distribution for that platform could be added to future releases.

**Comment by bacongobbler** [comment]
According to https://github.com/helm/helm/blob/main/Makefile#L4, arm64 builds are already available. Can you please try using the installation instructions?

**Comment by bacongobbler** [comment]
https://helm.sh/docs/intro/install/#from-script

**Comment by bacongobbler** [comment]
For reference, support for arm64 was added in https://github.com/helm/helm/commit/ecdc34c5abd1d0242294ec95190f13044bd67504.

**Comment by bacongobbler** [comment]
I am going ahead and closing this for the time being, as I am assuming arm64 support for M1 macs have been available since helm 2.16. But please let us know if you run into any issues. Thanks.
