### ISSUE TITLE
`make test` appears to have issues on main causing it to fail.

### ISSUE THREAD

**Issue by purejgleason** [helm/helm#10729]
### What I would expect

When I run `make test` from the Helm source root, everything should compile right.

### What actually happens

I get 2 lint errors, which I can put in a PR to fix if we can fix the other issues. Once silenced I get the following run fails...

```
2022/03/06 11:17:21 http: TLS handshake error from 127.0.0.1:52642: remote error: tls: bad certificate
    chartrepo_test.go:314: Expected TLS error for function  FindChartInAuthAndTLSAndPassRepoURL not found, but got a different error (looks like "https://127.0.0.1:52640" is not a valid chart repository or cannot be reached: Get "https://127.0.0.1:52640/index.yaml": x509: “Acme Co” certificate is using a broken key size)
--- FAIL: TestFindChartInAuthAndTLSAndPassRepoURL (0.02s)
```

```
FAIL
FAIL    helm.sh/helm/v3/pkg/repo        0.655s
```

```
?       helm.sh/helm/v3/pkg/uploader    [no test files]
FAIL
```

I am running on OSX with the following golang

>go version devel go1.18-b37a5391f9 Tue Dec 7 20:14:56 2021 +0000 darwin/amd64

Output of `helm version`: n/a

Output of `kubectl version`:

`Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Minikube

**Comment by bacongobbler** [comment]
related: https://github.com/helm/helm/issues/10711

**Comment by bacongobbler** [comment]
This could be related to the version of Go you're running. Helm is compiled against [Go 1.17](https://github.com/helm/helm/blob/65d8e72504652e624948f74acbba71c51ac2e342/.github/workflows/build-pr.yml#L15).

**Comment by bacongobbler** [comment]
ping - any updates?
