### ISSUE TITLE
Is there a method to check chart exist in the OCI registry?

### ISSUE THREAD

**Issue by DanielXLee** [helm/helm#10721]
For the chart repo, we have a method FindChartInAuthAndTLSAndPassRepoURL to check if chart exist in the chart repo, for the OCI registry, does have a method to check it?https://github.com/helm/helm/blob/65d8e72504652e624948f74acbba71c51ac2e342/pkg/repo/chartrepo.go#L230

Output of `helm version`: 3.8.0

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by bacongobbler** [comment]
Hi @DanielXLee. Have you had a chance to look at `helm pull`'s implementation? That may better answer your question.

Th source code is available here: https://github.com/helm/helm/blob/main/pkg/action/pull.go

**Comment by DanielXLee** [comment]
@bacongobbler thank you, I'm not found the check method for the chart in OCI registry,  this method only for the helm repo
https://github.com/helm/helm/blob/e9abdc5efe11cdc23576c20c97011d452201cd92/pkg/action/pull.go#L119
