### ISSUE TITLE
post-upgrade hooks failed: job failed: BackoffLimitExceeded

### ISSUE THREAD

**Issue by ujwala02** [helm/helm#10720]
while upgrading operator through helm charts, I am facing this issue 

Output of `helm version`:
$ helm version
version.BuildInfo{Version:"v3.7.2",

Output of `kubectl version`:
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.2", GitCommit:"9d142434e3af351a628bffee3939e64c681afa4d", GitTreeState:"clean", BuildDate:"2022-01-19T
17:35:46Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b4d7da0049ead870833a07a1c24ad5ad218fb36c", GitTreeState:"clean", BuildDate:"2022-02-01T
10:32:31Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

aks

**Comment by ujwala02** [comment]
When i run debug i see this error 

helm.go:88: [debug] post-upgrade hooks failed: job failed: BackoffLimitExceeded
UPGRADE FAILED
main.newUpgradeCmd.func2
        helm.sh/helm/v3/cmd/helm/upgrade.go:202
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.2.1/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.2.1/command.go:974
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.2.1/command.go:902
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:87
runtime.main
        runtime/proc.go:225
runtime.goexit
        runtime/asm_amd64.s:1371

**Comment by bacongobbler** [comment]
Hi @ujwala02. We require more information before we can help. Can you share the job template in an example chart? Using `helm create` as a baseline would help here.

We need something to test against so we can verify why the job is failing.

Any job logs or status reports from kubernetes would be helpful as well.

Thanks.
