### ISSUE TITLE
Inconsistent helm repo list behavior 

### ISSUE THREAD

**Issue by luinnar** [helm/helm#10734]
Command `helm repo list` act differently when repository config file don't exists:

```bash
$ helm repo list
Error: no repositories to show
$ helm repo list -o json
[]
$ echo $?
0

$ rm ~/.config/helm/repositories.*

$ helm repo list -o json
Error: no repositories to show
$ echo $?
1
```

In both cases helm should return return empty list of repositories without exiting with error code.

Output of `helm version`:
* version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}
* version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}

**Comment by bacongobbler** [comment]
fixed in https://github.com/helm/helm/pull/10519.
