### ISSUE TITLE
helm install / upgrade don't respect --registry-config

### ISSUE THREAD

**Issue by jancespivo** [helm/helm#10738]
Hi, it seems `helm upgrade` and `helm install` don't respect  `--registry-config`

This works (/tmp/registry_config.json is filled with creds):
```shell
helm registry login --registry-config /tmp/registry_config.json --username <username> --password <password>
```
This doesn't:
```shell
helm install oci://<registry>/<repo>/<chart> --version <version> --registry-config /tmp/registry_config.json
```
`Error: failed to download "oci://<registry>/<repo>/<chart>" at version "<version>"`

Without `--registry-config` everything works fine.

Output of `helm version`:

`version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.6"}`

Thx!

**Comment by yxxhero** [comment]
@jancespivo /tmp/registry_config.json can you show the file? Thanks very much.

**Comment by jancespivo** [comment]
@yxxhero 

`gcloud auth application-default print-access-token | helm registry login -u oauth2accesstoken --password-stdin https://europe-docker.pkg.dev --registry-config /tmp/registry_config.json`

`cat /tmp/registry_config.json`

```json
{
    "auths": {
        "https://europe-docker.pkg.dev": {
            "auth": "**********"
        }
    }
}
```
Actual auth key is replaced with stars.

**Comment by yxxhero** [comment]
@jancespivo   from the code. It's a bug. I will create a PR for this. can you help me to test? Thanks very much.

**Comment by jancespivo** [comment]
@yxxhero I can confirm the version from your PR works.

**Comment by yxxhero** [comment]
@jancespivo it's ok? wait for your result?

**Comment by jancespivo** [comment]
@yxxhero Sry, I haven't expressed it clearly. It is **ok** :)

**Comment by yxxhero** [comment]
@yxxhero ok. Thanks for you reply.
