### ISSUE TITLE
Helm 3.8.2 upgrade CRD cannot convert int64 to float64

### ISSUE THREAD

**Issue by hezise** [helm/helm#10730]
while upgraded the CRD I got the following error:
Error: UPGRADE FAILED: cannot patch "systemupgrades.radware.com" with kind CustomResourceDefinition:  "" is invalid: patch: Invalid value: "map[spec:map[versions:[map[name:v1 schema:map[openAPIV3Schema:map[properties:map[spec:map[properties:map[curStep:map[default:0 maximum:14 minimum:0 type:integer] lastUpgradeResult:map[properties:map[canceledStep:map[default:0 maximum:14 minimum:0 type:integer] running_date:map[format:date-time type:string] upgrade_result:map[enum:[cancel upgrade rollback] type:string]] type:object] operation:map[default:upgrade enum:[rollback upgrade] type:string] prevStep:map[default:0 maximum:14 minimum:0 type:integer] rollbackRequired:map[default:false type:boolean] stepCompleted:map[default:false type:boolean] stepCompletedSuccessfully:map[default:true type:boolean] stepDescription:map[default:N/A type:string] traceId:map[default:N/A type:string] upgradeCompleted:map[default:false type:boolean] upgradeParams:map[properties:map[scp_filepath:map[default:N/A type:string] scp_hostname:map[default:N/A type:string] scp_password:map[default:N/A type:string] scp_username:map[default:N/A type:string] upgrade_mode:map[default:online enum:[offline online] type:string] version:map[default:N/A type:string]] type:object]] type:object]] type:object]] served:true storage:true]]]]": cannot convert int64 to float64

it works fine with helm 3.2.1

Output of `helm version`:
rsion.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.11", GitCommit:"c6a2f08fc4378c5381dd948d9ad9d1080e3e6b33", GitTreeState:"clean", BuildDate:"2021-05-27T23:47:11Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
kubespray 2.15

**Comment by bacongobbler** [comment]
I'm afraid I don't have enough information to help you out here. Can you please provide a sample chart to help reproduce the issue? That way we can better understand how one enters this situation. It can also help provide a test case to test against any follow-up patches.

Thanks.

**Comment by hezise** [comment]
Hello @bacongobbler,
[old-helm-init.zip](https://github.com/helm/helm/files/8257406/old-helm-init.zip)
[old-helm.zip](https://github.com/helm/helm/files/8257409/old-helm.zip)
[new-helm-init.zip](https://github.com/helm/helm/files/8257411/new-helm-init.zip)

sorry for my late response.
I've uploaded 3 files
old-helm-init.zip will create the CRD
old-helm.zip will create an object bases on that CRD
then upgrade the CRD using new-helm-init.zip

Regards,
Hezi Sela

**Comment by hezise** [comment]
Hello @bacongobbler ,
any update?

**Comment by hezise** [comment]
hello,
any update?

**Comment by hezise** [comment]
Hello @bacongobbler ,
I tried the same thing with 3.8.2 and also got the same error
I changed the title

**Comment by hezise** [comment]
after reading [](https://github.com/helm/helm/issues/5806) I removed the minimum and maximum from CRD and upgrade worked fine.
the question is why when performing helm install it works but when running helm upgrade it doesnt?
