### ISSUE TITLE
helm list should print chart and chart version separate

### ISSUE THREAD

**Issue by elwood218** [helm/helm#10749]
Feature request: The command `helm list` at the moment prints Chart and its version in one string.
```
NAME                   	NAMESPACE         	REVISION	UPDATED                                	STATUS  	CHART                                   	APP VERSION
cert-manager           	foo               	6       	<TIMESTAMP>   	deployed	cert-manager-v1.5.3                     	v1.5.3
```

Like `APP Version` there also should be a *Chart version*. So that there are 2 columns for the `Chart name` `cert-manager` and for `Chart version` `1.5.3`. 
That also should be adjusted for the yaml or json output of course.
Doing that it will be much easier to use that in Ansible Plays or whatever.. so it is not necessary to get the version via regex..

Output of `helm version`:
```
version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.6"}
```

**Comment by elwood218** [comment]
.. and the Chart column should also show the repo or how it is possible to get the repository info of that helm chart?

**Comment by bacongobbler** [comment]
What happens if you use the `--output json` flag? Does that split out the fields as you'd expect?

**Comment by bacongobbler** [comment]
Keep in mind that the default output (`--output table`) is meant to be human-readable. Machine-readable output is meant to be provided by alternate `--output` functions.

**Comment by yxxhero** [comment]
@elwood218 need more info.

**Comment by elwood218** [comment]
@yxxhero which info you need?? 
At the moment the output shows helm chart name and version in one string.. But this should be separated.. So what info you else need???

**Comment by yxxhero** [comment]
> What happens if you use the `--output json` flag? Does that split out the fields as you'd expect?

@elwood218

**Comment by elwood218** [comment]
@bacongobbler you didn't understand the request.

**Comment by yxxhero** [comment]
@elwood218 welcome to create a PR for this feature. Thanks very much.

**Comment by elwood218** [comment]
I already checked all different output!
```
    "chart": "generic-0.1.0",
```

Chart `key` is always the same and the value is always `<chart-name>-<version>`. But it should be like separated keys: 
```
   "chart": "generic",
   "version": "0.1.0"
```

**Comment by elwood218** [comment]
Wow.. @yxxhero yeah after your questions I see that you are not the one who could solve that

**Comment by Blaimi** [comment]
Why is this request closed? I have the same problem :(. I want to get the version of the chart of a installed release. It's not easily possible to extract the version from "chart" because semver allows `-` and the chartname allows numbers.

current state of `helm list --filter='monitoring' -n monitoring -o json`:

```json
[{
"name":"monitoring",
"namespace":"monitoring",
"revision":"6",
"updated":"2022-11-09 15:57:10.30892234 +0100 CET",
"status":"deployed",
"chart":"kube-prometheus-stack-40.1.2",
"app_version":"0.59.1"
}]
```
my proposal (to be downwards-compatible)
```json
[{
"name":"monitoring",
"namespace":"monitoring",
"revision":"6",
"updated":"2022-11-09 15:57:10.30892234 +0100 CET",
"status":"deployed",
"chart":"kube-prometheus-stack-40.1.2",
"chart_name":"kube-prometheus-stack",
"chart_version":"40.1.2",
"app_version":"0.59.1"
}]
```

**Comment by kominoshja** [comment]
Why is this closed as complete? It doesn't appear in helm ls
```json
[
   {
      "app_version" : "",
      "chart" : "templated_docker-compose-1.0.0",
      "name" : "example",
      "namespace" : "default",
      "revision" : "1",
      "status" : "deployed",
      "updated" : "2024-08-12 23:11:02.065325133 +0000 UTC"
   }
]
```

**Comment by EHJ-52n** [comment]
Please re-open or provide a link to the successor issue or solution.
