### ISSUE TITLE
Manifest Bug in OCI registries - no compatibility mode

### ISSUE THREAD

**Issue by ognif** [helm/helm#10742]
I think there is a really bad bug inside helm 3.8. The bug is for helm manifests inside OCI registries. 
As I can read at your webpage:

The chart layer media type was switched from application/tar+gzip to application/vnd.cncf.helm.chart.content.v1.tar+gzip

But you do not have added any down compatibility. This means in clear words, all our customers cannot pull the charts with helm 3.4.2 as sample.

Some companies have long process and workflows to change a software version. So to do not add down compatibility is complete aways from the needs.

I also was not able to find any hotfix or trick to adjust this. The only way is to push the Helm chart with old version and experimental feature. So in clear words, our ci pipeline is broken.

My helm: 3.8x (custom build in case of other errors)
Customers helm: as sample helm 3.4.2

Error from ALL customers: 
Error: manifest does not contain a layer with mediatype application/tar+gzip

**Comment by bacongobbler** [comment]
This is the point of a feature being marked experimental. We marked it experimental to inform the user that the feature does not comply to the same backwards compatibility constraints as supported features do, and to treat it as such.

in other words, there will not be any support provided for charts pushed while the feature was marked as experimental.

**Comment by ognif** [comment]
Do you really know what you type? Sorry, but in 3.8 OCI is NOT anymore experimental. And so we use it in production. 
BUT it is not usable in production because customers with older versions of helm CANNOT pull the chart that was pushed WITHOUT experimental. This is definitly a bug our you have a wired idea of "experimental"

**Comment by ognif** [comment]
AND CLOSED! Ignoring bugs? What kind of developing team you are? Thsis is the second time your software will fail ALL quality needs.

**Comment by ognif** [comment]
Amazing....it is not a bug beause it is experimental. But i is not anymore experimental...no matter...close...it is a bug.

**Comment by bacongobbler** [comment]
Here's the situation as I understand it:

- You built your chart using Helm 3.8 (which is supported)
- Your clients are attempting to pull it with Helm 3.4.2 (which is NOT supported)

Helm 3.4.2 still had experimental support for OCI. There is no guarantee of forwards or backwards compatibility for clients older than Helm 3.8.0 because it is still marked as an experimental feature. Therefore we cannot guarantee that Helm clients prior to Helm 3.8 can pull charts from an OCI registry.

Please ask your clients to upgrade to Helm 3.8.
