### ISSUE TITLE
Datree helm plugin in windows not install installed

### ISSUE THREAD

**Issue by AreebAbdulGhani** [helm/helm#10747]
![post](https://user-images.githubusercontent.com/92576221/157467708-daa728ea-5987-48a2-89f7-3c43d6c56a7f.png)

**Comment by AreebAbdulGhani** [comment]
Help me to install helm
I tried a lot but failed

**Comment by bacongobbler** [comment]
Have you read the documentation? There are multiple ways you can install the Helm client.

https://helm.sh/docs/intro/install/

**Comment by AreebAbdulGhani** [comment]
Still its showing error

**Comment by bacongobbler** [comment]
Can you please provide more information? What steps did you follow? What error are you seeing?

**Comment by eyarz** [comment]
@bacongobbler I guess this error is related to another issue that you opened back in 2019:
https://github.com/helm/helm/issues/7117

**Comment by hickeyma** [comment]
@AreebAbdulGhani Can you run any Helm command. For example, `helm version` or `helm ls`?

**Comment by AreebAbdulGhani** [comment]
It's working.

**Comment by hickeyma** [comment]
What's working @AreebAbdulGhani? Can you provide more details, like output.

**Comment by AreebAbdulGhani** [comment]
First I installed Helm, after that i was trying to install Datree helm
plugin, but it didn't worked on windows
So yeah, Helm is working fine

**Comment by hickeyma** [comment]
The error in the description seems different but this might have something to do with plugin install on Windows. Do you mind trying the following the [WSL instructions](https://github.com/helm/helm-2to3#for-windows-using-wsl) which are used for another plugin? You will need to change the instructions to use the latest Helm and `datree` plugin.

**Comment by AreebAbdulGhani** [comment]
Great, thanks for letting me know.

**Comment by hickeyma** [comment]
Thanks @eyarz for letting us know/

@AreebAbdulGhani Can you try the steps and let us know how you get on?

**Comment by AreebAbdulGhani** [comment]
Ok, I'll check it out.
