### ISSUE TITLE
How to render templates into local files without "--- #Source: helm/templates/xxx.yaml" lines

### ISSUE THREAD

**Issue by bh4rtp** [helm/helm#10755]
I just use helm to create local yaml files for docker swarm. 
```
$ helm template --output-dir ./app ./app
```
But there are at least two lines like this:
```
---
# Source: helm/templates/docker-compose.yaml
```
How to remove these comment lines? Thanks.

**Comment by bacongobbler** [comment]
You could try using `sed` to strip those lines from the output.

**Comment by bacongobbler** [comment]
source: https://github.com/helm/helm/blob/8ab18f7567cedffdfa5ba4d7f6abfb58efc313f8/pkg/action/action.go#L172-L177

**Comment by bh4rtp** [comment]
Thank you for the solution:)
I suggest add a command option to skip outputting these lines.
