### ISSUE TITLE
Support --wait with helm status

### ISSUE THREAD

**Issue by stan-sz** [helm/helm#10750]
`helm status` is a non-blocking call. Having it support `--wait` in combination with `--timeout` could have the same meaning as in `upgrade` or `install` commands:

> will wait until all Pods, PVCs, Services, and minimum number of Pods of a Deployment, StatefulSet, or ReplicaSet are in a ready state before marking the release as successful. It will wait for as long as --timeout

**Comment by marckhouzam** [comment]
Hi @stan-sz.  Helm status does not show or follow the status for the deployed resources, so what would it wait for?

**Comment by stan-sz** [comment]
@marckhouzam can we make it wait for the deployed resources?

**Comment by marckhouzam** [comment]
I do understand your point.  However I think we would be mixing two concepts.  `helm status` shows the status of a helm release, its name, the date it was deployed, etc.  The command does not show the status of the deployed resources (it used to in helm v2).

I feel it would be confusing to have it wait for resources for which it does not show the status.

**Comment by stan-sz** [comment]
`install`, `upgrade` and `rollback` - all have the `--wait` and `--timeout` options. Having this functionality in `status` would open up scenarios for helm orchestrators to spawn multiple upgrades/installs async and then checking their statuses.

**Comment by bacongobbler** [comment]
I agree with @marckhouzam on this one. We're conflating two points with this feature request. `status` is meant to display the current status of the release. It is not meant to wait until the release is in a ready state.

Perhaps it would be more prudent to pul this out into a separate `helm wait` plugin as described in https://github.com/helm/helm/issues/10321.

**Comment by stan-sz** [comment]
Either way - the end result is that there's a blocking way to check if the last install/upgrade succeeded. Can you reopen #10321 then?

**Comment by stan-sz** [comment]
Another option is to enable this experience via a subcommand: `helm status wait [release name]`
