### ISSUE TITLE
resource with hook not removed after helm uninstall 

### ISSUE THREAD

**Issue by zffocussss** [helm/helm#10758]
Hi guys:
   I have a chart which contains some resource with helm hooks, like post-install,post-upgrade.after invoking helm uninstall,the resources are not removed,and keep running.As I know hooked resource are not managed by helm after helm upgrade/install.
  How can I remove all the resources with helm, including hooks resource,typically jobs,other resource?

**Comment by bacongobbler** [comment]
Chart hooks are unmanaged. That is to say, there is no way to remove hooks with helm. You will need to use `kubectl` or some other client to remove those resources from the cluster.
