### ISSUE TITLE
Feature Request: Source chart metadata info to be exposed as built-in objects for pre/post upgrade/rollback Helm hooks rendering

### ISSUE THREAD

**Issue by antaloala** [helm/helm#10752]
As ```helm upgrade``` and ```helm rollback``` sub-command can be used to move a Helm release to whatever newer or older version of a given Helm chart (from the latest one applied in the scope of that Helm release) it would be really useful, mainly for the development of pre/post upgrade/rollback Helm hooks, to be able to get information on the currently deployed Helm chart we are upgrading/rolling back from.

I think this new feature could mimic the ``{{ .Chart.xxx }}`` built-in objects, naming it as (as a possibility) ``{{ .OriginChart.xxx }}``, holding the source chart's metadata related fields stored in the ```.data.release.chart.metadata``` stanza of the k8s Secret (or ConfigMap) object related to the latest version of the involved Helm Release from which to upgrade/rollback.

It would be also useful to expose the ```.data.release.info``` so the upgrade/rollback hooks can know if latest deployed Helm chart in the scope of the involved Helm release was successfully (or not) deployed.

- This info would be maybe better allocated in a subfield inside the already supported ``.Release`` object (e.g. ``.Release.latestStatus`` )

**Comment by bacongobbler** [comment]
related: https://github.com/helm/helm/issues/5825

**Comment by antaloala** [comment]
Thanks @bacongobbler.
Should I then better write a HIP for this?
