### ISSUE TITLE
Helm cannot download provenance files when the Chart URL has a query string.

### ISSUE THREAD

**Issue by HoustonPutman** [helm/helm#10770]
Output of `helm version`: v3.7.1

Output of `kubectl version`: N/A - This fails before communicating with Kubernetes

Cloud Provider/Platform (AKS, GKE, Minikube etc.): N/A - This fails before communicating with Kubernetes

Steps to reproduce:

Create a helm repository `index.yaml` where a Chart has the following URL: `https://www.apache.org/dyn/closer.lua/solr/solr-operator/v0.5.0/helm-charts/solr-0.5.0.tgz?action=download`

All commands will pass and this will work until you try to use `--verify`, because Helm tries to add `.prov` to the end of the URL instead of adding it to the end of the path, like it does throughout the rest of the codebase.

```
failed to decode signature
helm.sh/helm/v3/pkg/provenance.(*Signatory).Verify
	helm.sh/helm/v3/pkg/provenance/sign.go:246
helm.sh/helm/v3/pkg/downloader.VerifyChart
	helm.sh/helm/v3/pkg/downloader/chart_downloader.go:308
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo
	helm.sh/helm/v3/pkg/downloader/chart_downloader.go:131
helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart
	helm.sh/helm/v3/pkg/action/install.go:753
main.runShow
	helm.sh/helm/v3/cmd/helm/show.go:205
main.newShowCmd.func4
	helm.sh/helm/v3/cmd/helm/show.go:121
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.2.1/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.2.1/command.go:974
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.2.1/command.go:902
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:87
runtime.main
	runtime/proc.go:255
runtime.goexit
	runtime/asm_amd64.s:1581
```

Note: This is how official apache release artifacts are meant to be downloaded, so a fix here would very much help the many Apache projects that provide official Helm charts.

**Comment by bacongobbler** [comment]
Thanks for identifying this. We'd welcome a patch.

**Comment by d-d-up** [comment]
I want to work on this.

**Comment by d-d-up** [comment]
@bacongobbler
