### ISSUE TITLE
Alternative file extension

### ISSUE THREAD

**Issue by computerquip-work** [helm/helm#10771]
Apologies if this was brought up previously, I didn't see anything in the issues.

The templated yaml isn't really yaml, it's yaml with the helm template syntax embedded into it. However, Helm still requires the "yaml" extension. This confuses editors because they try to parse the the file as normal yaml and spew out errors since it isn't truly yaml. For example, this confuses VS Code's Kubernetes extension by default, at least without extra configuration.

I think any extension that's unique to helm but also indicates it's not valid yaml is more reasonable than requiring the "yaml" file extension.

**Comment by bacongobbler** [comment]
Helm doesn't necessarily require the .yaml extension for templates. That's just a common convention.

I'm surprised the VSCode Kubernetes extension does not detect that it is opening a helm template file. IIRC it checks whether it's within the context of a helm chart which disables the syntax highlighter. Source: https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/1044#issuecomment-1046353905

Can you make sure you're using the most recent version of the extension?

Anyhoo, this is valid:

```
$ ls templates/
NOTES.txt  _helpers.tpl  deployment.txt
$ helm template . | head -n 5
---
# Source: test-10771/templates/deployment.txt
apiVersion: apps/v1
kind: Deployment
metadata:
```

**Comment by bacongobbler** [comment]
Closing as the original ask (supporting alternative file extensions) is already supported.

**Comment by computerquip-work** [comment]
Yeah, unfortunately the detection doesn't seem to work on any templated files so I suppose I'll have to figure out why. My original thought was to just change the extension to something other than yaml and make a file association. Thanks for the lead regardless.

**Comment by wyardley** [comment]
Helm does _recommend_ using the target file's extension as a "best practice": https://helm.sh/docs/chart_best_practices/templates/#structure-of-templates

See https://github.com/prettier/prettier/issues/6517 for some good discussion. IMO, using `.yaml.gotmpl` (e.g., for `.yaml` files) or similar might make more sense than the recommendation above.

Obviously, validation could be done on the rendered files, but not sure if there would be an easy way to do validation on the pseudo-yaml + templating.
