### ISSUE TITLE
determine whether to define a template

### ISSUE THREAD

**Issue by duanhongyi** [helm/helm#10772]
It is recommended to add built-in functions to determine whether the template is defined.

```
{{- define "common.affinities.nodes.soft" -}}
/* some code */
{{end}}
```

We use the following function to determine whether it is defined:

```
{{- ifdef "common.affinities.nodes.soft" }}
{{end}}
```

**Comment by bacongobbler** [comment]
Sorry, I’m not sure what you are asking us to implement here. Care to elaborate?
