### ISSUE TITLE
possibility of having a list charts option for OCI Registry support

### ISSUE THREAD

**Issue by Lekinho** [helm/helm#10782]
For index.yaml based registry, this was achieved by fetching the index.yaml file from the repository.

For OCI Registry, Is there an alternative? 
It appears one can only pull individual charts but there's no way to get a list of all charts in a registry/namespace?

**Comment by bacongobbler** [comment]
The [OCI distribution specification](https://github.com/opencontainers/distribution-spec) that tells Helm and others how to interact with registries, does not contain a search API. The topic of having a search API has come up in the past but has not become a reality and is not expected to anytime soon.

If there is no API specification we can follow, how do we make search work and work well? To do this we have to work with registries like ACR, ECR, Harbor, and others.

See also https://github.com/helm/helm/issues/9983.

**Comment by rowi1de** [comment]
https://github.com/helm/helm/issues/11000 Could be implemented partially 😇

**Comment by rowi1de** [comment]
There is an api that allows listing chart versions which would already be very helpful https://github.com/opencontainers/distribution-spec/blob/main/spec.md#content-discovery

**Comment by rowi1de** [comment]
Not stale just waiting for an answer
