### ISSUE TITLE
[FEATURE REQUEST] Add urlencode template function 

### ISSUE THREAD

**Issue by DrissiReda** [helm/helm#10794]
My use case is simple, on multiple occasions, I have to supply a username/password on a uri with basic authentication, but sometimes the passwords have special characters. I'd like a way to url encode the supplied passwords.

Example:

With this `values.yaml` file:

```yaml
username: postgres
password: $@cr4d
endpoint: psql.ns:5432
database: test
```

This template:

```yaml
name: psqlUri
value: "--backend-store-uri=postgresql://{{ .Values.username }}:{{ .Values.password | urlenc }}@{{ .Values.endpoint }}/{{ .Values.database }}
```

Should render: 

```yaml
name: psqlUri
value: "--backend-store-uri=postgresql://postgres:%24%40cr4d%2A@psql.ns:5432/test
```

The solution to supply it already encoded is impractical because it might be annoying for some users, and I might need to supply it in its raw form elsewhere on the helm. In this particular example I might also need it to create the postgresql secret with the env var `PGPASSWORD` .

Is there any difficulty to include this feature?

**Comment by bacongobbler** [comment]
Please file feature requests related to template functions with [sprig](/Masterminds/sprig). Thanks.

**Comment by ReneWerner87** [comment]
it already exists in golang templates

![image](https://github.com/user-attachments/assets/f68fb81f-ec70-4836-aa33-bdbaa4f4bf61)

https://coveooss.github.io/gotemplate/docs/functions_reference/base-go-template-functions/#__urlquery__
