### ISSUE TITLE
Library versioning for subdependencies is ignored

### ISSUE THREAD

**Issue by albgp22** [helm/helm#10790]
Hi there helm community!

We just found an unexpectedly weird behaviour of helm when importing different versions of a library in different dependencies. To see this, let's imagine the following chart structure.

```
|-- mainchart
|---- subdep1
|------ mylibrary (v1)
|---- subdep2
|------ mylibrary (v2)
```

The detected issue is that, even when this dependencies use different versions of the _mylibrary_ library chart, then when _mainchart_ is rendered, all dependencies are using the same version of _mylibrary_! That is, v1.

You can test this behaviour for yourself using this laboratory setup: https://github.com/albgp22/helm-ibrary-issue.

Let's go in deeper detail: We've created a helm library chart defining the following (not really useful) helper:

```
{{- define "lib.hardcodedString" -}}
"Comes from library 1"
{{- end }}
```

Let's say we update the version of the chart and modify this helper to be as follows

```
{{- define "lib.hardcodedString" -}}
"Comes from library 2"
{{- end }}
```

Now a given chart (mydependency1) imports the first version for this chart. We render a mock object on it getting

```
# Source: subdep1/templates/whateverObject.yaml
dependency1: "Comes from library 1"
```

Same happens with a second chart (mydependency2) importing the second version of the library:

```
# Source: subdep2/templates/whateverObject.yaml
dependency2: "Comes from library 2"
```

Everything works fine! So we expected it to be the same when importing this dependencies in a big main chart

```
dependencies:
- name: subdep1
  version: 0.1.0
  repository: file://../subdep1
- name: subdep2
  version: 0.1.0
  repository: file://../subdep2
```

But, if we render them we get the surprising rendering

```
# Source: main/charts/subdep1/templates/whateverObject.yaml
dependency1: "Comes from library 1"
---
# Source: main/charts/subdep2/templates/whateverObject.yaml
dependency2: "Comes from library 1"
```

Library from first dependency has overriden the library in second dependency even having different version :(

If we invert the dependency order in Chart.yaml from _main_ library we get the same result, so it doesn't seems to depend on the dependency order, it seems to be taking the lowest version among all imported library versions.

**We expect:** helm to allow each dependency to use its own library version.

Output of helm version:
`version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}`

Output of kubectl version: 
`Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): not relevant.

**Comment by bacongobbler** [comment]
Function templates are globally namespaced. That is to say, when two charts declare the same function name like `lib.hardcodedString`, the behaviour as to which function is rendered is undetermined.

My suggestion would be to namespace these template functions. Assuming you require the availablility of both v1 and v2 to be available to the chart, I'd suggest `lib.hardcodedString` and `lib.v2.hardcodedString` or something similar to that nature.

**Comment by hedgss** [comment]
@bacongobbler 
This solution is not convenient, because it means that I will need not only to update the version in the Chart.yaml. 
I also will need to make changes in the templates folder each time.

**Comment by YaytayAtWork** [comment]
If it isn't practical to automatically separate the libraries in use how about either:
1. Making it deterministic so that users can predict which will be used.
Presumably by saying that if the parent chart depends on a version then that is the version that will be used.
2. Failing if different versions of the same chart are referenced.
Annoying, but less annoying than having unpredictable behaviour.

**Comment by Yaytay** [comment]
Please don't just ignore this issue.

**Comment by joejulian** [comment]
Happy to have a contribution to address this. Probably should start with a [HIP](https://github.com/helm/community/blob/main/hips/hip-0001.md)

**Comment by jonathansloman** [comment]
This issue causes real problems for us (and probably anyone else using a helm library template against multiple projects).

**Comment by joejulian** [comment]
A workaround has been posted. Have you tried it?

**Comment by hedgss** [comment]
The proposed workaround is not convenient to use.
Perhaps it can be used in some cases, but in my case it is not an acceptable solution.

Imagine that you have 30 functions in the library. You will need to update each time all the versions in the library and all places where they are used.

At this moment, I am using another workaround.
1. make umbrella charts as small as possible and deploy them separately. 
2. Use the same helm library in all dependencies of one umbrella chart.

**Comment by joejulian** [comment]
This support issue has been answered with two solutions. The behavior is well documented and cannot be changed in helm 3. Closing.

**Comment by jonathansloman** [comment]
@joejulian This is a disappointing response. The workarounds are not ideal, and cause extra work for those of us using helm libraries where we have parent charts with many dependencies. It's hard to believe there isn't a way in helm to associate specific versions of a library chart with individual sub-dependencies.

Also, where is it well documented? There is no mention of it here: https://helm.sh/docs/topics/library_charts/

**Comment by hedgss** [comment]
@joejulian 
When it comes to the library, the intuitive expectation is that it is some kind of isolated code.
In this case, it doesn't work and it is critical.
Moreover, this limitation even is not mentioned in the documentation.

Workarounds are NOT proper solutions. They are inconvenient and require additional effort.
I agree with you that the default behaviour should not have breaking changes, but you still have some options:
- Add a flag that changes the default behaviour. In this case, it can be used if proper isolation is required.
- Make changes in the new helm version.
