### ISSUE TITLE
Bump golang version to latest as v1.17 has high risk vulnerabilities

### ISSUE THREAD

**Issue by shubham-in10se** [helm/helm#10805]
Hi,
The helm binary uses golang version 1.17, which has a lot of high risk vulnerabilities, as per the latest security scans.  It is because of this that all the images having even the latest helm binary baked into them are failing the security scans.

Kindly upgrade the golang version used to 1.17.7 or above.

Thanks.

**Comment by bacongobbler** [comment]
Duplicate of https://github.com/helm/helm/issues/10780. The next release will be cut with the latest available version of Go.

Please search for duplicate issues before posting next time. Thanks.
