### ISSUE TITLE
Conditional template import from a common chart

### ISSUE THREAD

**Issue by EyalZilberblum** [helm/helm#10813]
Output of `helm version`: 
`version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.16"}`

Output of `kubectl version`: 
`Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.8", GitCommit:"7061dbbf75f9f82e8ab21f9be7e8ffcaae8e0d44", GitTreeState:"clean", BuildDate:"2022-03-16T14:03:36Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): `EKS`

I am using a chart that has a dependency to a common chart that contain several templates.
i would like to know how to import a template using a condition in the chart's values.yaml

common chart structure:
.
├── Chart.yaml
└── templates
    ├── _deployment.yaml
    ├── _destinationrule.yaml
    ├── _helpers.tpl
    ├── _hpa.yaml
    ├── _ingress.yaml
    ├── _service.yaml
    ├── _serviceentry.yaml
    ├── _util.yaml
    └── _virtualservice.yaml

chart structure:
.
├── Chart.yaml
├── values.yaml
└── templates
    ├── deployment.yaml
    ├── destinationrule.yaml
    ├── hpa.yaml
    ├── ingress.yaml
    ├── service.yaml
    └── virtualservice.yaml

For example if i want to use an ingress with the chart i would assume adding the following flag in the values.yaml:
ingress:
  enabled: <false|true>

and in the common template have this:
{{- define "common.ingress.tpl" -}}
{{- if .Values.ingress.enabled }}

The following results in an empty ingress.yaml

how can i proceed from here

**Comment by hickeyma** [comment]
@EyalZilberblum If you put the condition at the top of the files, does that work?

In other words:

```yaml
{{- if .Values.ingress.enabled }}
{{- define "common.ingress.tpl" -}}
```

**Comment by EyalZilberblum** [comment]
> 

Error: parse error at (clean_chart/templates/test.yaml:2): unexpected <define> in command

**Comment by hickeyma** [comment]
Does you values file have have `ingress.enabled` set?
