### ISSUE TITLE
Error: chart requires kubeVersion: < 1.23.0-0 which is incompatible with Kubernetes v1.23.0 [bug]

### ISSUE THREAD

**Issue by jakaye80** [helm/helm#10819]
Output of `helm version`:
 ke@master01 rke]$ ./helm-3.8.1 version
version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.5"}

Output of `kubectl version`:
Client Version: [version.Info](http://version.info/){Major:"1", Minor:"21", GitVersion:"v1.21.1",

output of `rke version`:
rke]$ rke version --config rke_config.yml
INFO[0000] Running RKE version: v1.3.3

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

I'm trying to upgrade Rancher on a VM and issue the following helm (3.8.1) command with errors:` helm template ...`

```
rke@master01 rke]$ ./helm-3.8.1 version
version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.5"}
[rke@master01 rke]$ ./helm-3.8.1 template rancher ./rancher-2.6.3.tgz  \
--output-dir rancher-2.6.3  \
--no-hooks --namespace cattle-system -\
-set hostname=m10.localdoain \
--set useBundledSystemChart=true
```

`Error: chart requires kubeVersion: < 1.23.0-0 which is incompatible with Kubernetes v1.23.0`

**When I download and use an older version of helm it works 3.7.2** 

```
rke@master01 rke]$ ./helm-3.7.2 version
version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}
```

```
[rke@master01 rke]$ ./helm-3.7.2 template rancher ./rancher-2.6.3.tgz \
 --output-dir rancher-2.6.3 \
--no-hooks --namespace cattle-system  \
--set hostname=m10.localdoain \
--set useBundledSystemChart=true
```

```
wrote rancher-2.6.3/rancher/templates/serviceAccount.yaml
wrote rancher-2.6.3/rancher/templates/clusterRoleBinding.yaml
```
Problem: helm version 3.8.1 does not template properly like 3.7.2 
Furthermore, if you add the flag `--kube-version v1.20.13 ` then it will generate without error against 3.8.1

**Comment by bacongobbler** [comment]
The argument is working as intended. ` < 1.23.0-0` means the chart must be rendered with a version of the Kubernetes client LESS than 1.23.0. Helm 3.8 is [compiled against Kubernetes 1.23.4](https://github.com/helm/helm/blob/v3.8.1/go.mod#L37). Hence the error.

**Comment by bacongobbler** [comment]
Please file issues with the rancher chart maintainers.

**Comment by jhughes2112** [comment]
This is the highest hit on a google search, so I will mention that the solution to this is **sometimes** that your local helm is out of date and the chart is fine.  Upgrade helm.

**Comment by newman-dani** [comment]
Same issue with certmanager, only when installing using ```k8s.helm.v3.Chart``` or ```k8s.helm.v3.Release```

**Comment by hongbo-miao** [comment]
Thanks @jhughes2112 ! 😃
I have a similar issue. I posted the details at https://stackoverflow.com/questions/78615279/got-error-chart-requires-kubeversion-1-19-0-0-which-is-incompatible-with-ku
