### ISSUE TITLE
Can't push a chart to registry

### ISSUE THREAD

**Issue by Mr-Mark2112** [helm/helm#10814]
I'm trying tu push a chart to registry, but i'm getting this error:
```
helm push cacheserver-core-chart-3.16.0.tgz https://.../sre --debug
Error: scheme prefix missing from remote (e.g. "oci://")
helm.go:84: [debug] scheme prefix missing from remote (e.g. "oci://")
helm.sh/helm/v3/pkg/uploader.(*ChartUploader).UploadTo
        helm.sh/helm/v3/pkg/uploader/chart_uploader.go:49
helm.sh/helm/v3/pkg/action.(*Push).Run
        helm.sh/helm/v3/pkg/action/push.go:69
main.newPushCmd.func1
        helm.sh/helm/v3/cmd/helm/push.go:48
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.3.0/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.3.0/command.go:974
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.3.0/command.go:902
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
        runtime/proc.go:255
runtime.goexit
        runtime/asm_amd64.s:1581
```
Output of `helm version`: version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}

If i try to use http:// or https:// scheme, then i get error like:
```
Error: scheme "https" not supported
```
If i use repo name, then i get oci error:
```
#helm repo list
NAME                    URL
sre                     https://..../sre
#helm push cacheserver-core-chart-3.16.0.tgz sre --debug
Error: scheme prefix missing from remote (e.g. "oci://")
```

**Comment by hickeyma** [comment]
@jdolitsky Can you push a chart to ChartMuseum using the `helm push` command or do you have to use the [ChartMuseum push plugin](https://github.com/chartmuseum/helm-push)?

**Comment by Mr-Mark2112** [comment]
> @jdolitsky Can you push a chart to ChartMuseum using the `helm push` command or do you have to use the [ChartMuseum push plugin](https://github.com/chartmuseum/helm-push)?

No, i can't push a chart using helm ```helm push```.  I never used this plugin

**Comment by johannes85** [comment]
I have a similar problem with a previously added repo. Did you solved the issue?

**Comment by Mr-Mark2112** [comment]
> I have a similar problem with a previously added repo. Did you solved the issue?

I've managed to push my chart with version 3.6

**Comment by laksgreen** [comment]
I'm using the latest version: "v3.8.0" and "chartmuseum/helm-push" plugin, still getting same error.
Error: scheme prefix missing from remote (e.g. "oci://")

**Comment by laksgreen** [comment]
helm push command is not working instead of that, I used "cm-push"

**Install the Plugin:** 
`$ helm plugin install https://github.com/chartmuseum/helm-push`

**Push a chart to your favorite repository,**
`$ helm cm-push  ./myhelm-chart  helmchartmuseum`

Ref: https://github.com/chartmuseum/helm-push

Thanks!

**Comment by NUAAMETEOR** [comment]
> helm push command is not working instead of that, I used "cm-push"
> 
> **Install the Plugin:** `$ helm plugin install https://github.com/chartmuseum/helm-push`
> 
> **Push a chart to your favorite repository,** `$ helm cm-push ./myhelm-chart helmchartmuseum`
> 
> Ref: https://github.com/chartmuseum/helm-push
> 
> Thanks!

good!!

**Comment by jonnylangefeld** [comment]
I just ran into this too. I never used chartmuseum and did not have the old `helm push` plugin.
Now on `3.9.3` I see the same issue as described here.

Regarding
> I've managed to push my chart with version 3.6
This can't work without a plugin. I downloaded [`3.6.3`](https://github.com/helm/helm/releases/tag/v3.6.3) and got
```
╰─ ./darwin-amd64/helm push app-0.1.2.tgz my-artifactory
Error: unknown command "push" for "helm"

Did you mean this?
	pull

Run 'helm --help' for usage.
```

```
╰─ helm version
version.BuildInfo{Version:"v3.9.3", GitCommit:"414ff28d4029ae8c8b05d62aa06c7fe3dee2bc58", GitTreeState:"clean", GoVersion:"go1.19"}
```

**Comment by ventsyv** [comment]
Same issue with helm 3.10.0
```
NAME       	URL                                                 
bitnami    	https://charts.bitnami.com/bitnami                  
my-charts	https://jfrog.domain.com/artifactory/my-charts

helm push helm-charts/test-chart-0.1.0/test-chart/ my-charts
Error: scheme prefix missing from remote (e.g. "oci://")
```

**Comment by joejulian** [comment]
Should "helm push" work with ChartMuseum? According to the CM docs, you upload with either curl or the plugin: https://chartmuseum.com/docs/#uploading-a-chart-package

**Comment by jensens** [comment]
I had the same problem after upgrading to helm 3.10.2 and it seems the ChartMuseum plugin in it's recent version (installed as `helm plugin install https://github.com/chartmuseum/helm-push`) is needed and then `helm cm-push ...` is the command.  In Gitlab-CI this looks like so:

```
helm-package:
  stage: build
  image:
    name: alpine/helm:3.10.2
    entrypoint: [""]
  variables:
    CHART: chart
  before_script:
    - apk add git
    - helm plugin install --version=v0.10.3 https://github.com/chartmuseum/helm-push.git
    - >
      helm repo add ${CHART}
      --username ${CI_REGISTRY_USER}
      --password ${CI_REGISTRY_PASSWORD}
      ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/stable
  script:
    - helm package ${CHART} -d ${CHART}
    - helm cm-push ${CHART}/*.tgz ${CHART}
```

**Comment by joejulian** [comment]
Thank you @jensens . Closing this as answered.

**Comment by Ruchira-R** [comment]
`Error: scheme prefix missing from remote (e.g. "oci://")`

I am getting this error while pushing my Chart to Amazon ECR.

Note : This comes up once in a while, after 1-2 hours the error goes away and I can start pushing again.

How do I fix it?

My Helm Version is `3.9.3`

**Comment by gechaozhong** [comment]
cm-push instead of push, then it works
