### ISSUE TITLE
Helm duplicate service ports problem

### ISSUE THREAD

**Issue by emilnkrastev** [helm/helm#10823]
Hello,

I'm observing strange behavior with kubernetes service object upon helm upgrade. Helm allows me to add service port with already existing port number and when I remove the duplicate service port in service.yaml and call upgrade helm deletes the other service port as well.

Output of `helm version`:
`version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.5"}`
Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}`
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
EKS and vanilla kubernetes

How to reproduce the issue:

1. Clone the following repo:
https://github.com/emilnkrastev/helm-service-problem
2. `helm install service-test .`
3. Uncomment the following lines:
https://github.com/emilnkrastev/helm-service-problem/blob/main/templates/service.yaml#L18-L21
4. `helm upgrade service-test .`
5. `kubectl describe svc service-test`
![image](https://user-images.githubusercontent.com/19404889/161318825-f85eb64c-3245-4afe-a865-bbd54839b7bf.png)
6. Comment the following lines:
https://github.com/emilnkrastev/helm-service-problem/blob/main/templates/service.yaml#L18-L21
7. `helm upgrade service-test .`
8. `kubectl describe svc service-test`
![image](https://user-images.githubusercontent.com/19404889/161318534-554b8d75-3074-4128-a20b-0a67c3b53bc7.png)

**Comment by bacongobbler** [comment]
For context: Helm does not directly remove objects from Kubernetes. Helm's job is to render the templates and submit the templates to Kubernetes. Kubernetes is the actor responsible for reconciling the current state of an object with the desired state (the template submitted on a `helm upgrade`). In other words, either the template you provided removed all service ports somehow, or Kubernetes decided to drop all ports.

Perhaps a simpler method to test this theory would be to take your example, run a `helm template` on each template and manually submit them to kubernetes via `kubectl apply`, and see if the behaviour differs.

**Comment by emilnkrastev** [comment]
I tried your suggestion and the behavior does not differ - still end up with deleted service ports. It's not related to helm.

Thank you!

We can close the issue.

**Comment by plachta11b** [comment]
I saw the same issue with helm `version.BuildInfo{Version:"v3.15.1", GitCommit:"e211f2aa62992bd72586b395de50979e31231829", GitTreeState:"clean", GoVersion:"go1.22.3"}`. @emilnkrastev How did you solve that? Why it's not related?

**Comment by emilnkrastev** [comment]
> I saw the same issue with helm `version.BuildInfo{Version:"v3.15.1", GitCommit:"e211f2aa62992bd72586b395de50979e31231829", GitTreeState:"clean", GoVersion:"go1.22.3"}`. @emilnkrastev How did you solve that? Why it's not related?

My solution was to recreate the whole service object and it was feasible in my scenario.
It's not related to helm because the simple kubectl apply is giving the same issue.

**Comment by plachta11b** [comment]
> > I saw the same issue with helm `version.BuildInfo{Version:"v3.15.1", GitCommit:"e211f2aa62992bd72586b395de50979e31231829", GitTreeState:"clean", GoVersion:"go1.22.3"}`. @emilnkrastev How did you solve that? Why it's not related?
> 
> My solution was to recreate the whole service object and it was feasible in my scenario. It's not related to helm because the simple kubectl apply is giving the same issue.

Thank you for the explanation. I found that a related issue https://github.com/kubernetes/kubernetes/issues/105610 is still open. This behavior could be dangerous, so I hope it will be fixed soon.
