### ISSUE TITLE
Container is not running after deploy the app from helm bitnami/charts 

### ISSUE THREAD

**Issue by ramkrishna2k3** [helm/helm#10825]
Output of `helm version`: 
version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.5"}

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:32:02Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  VMware cloud/Sphere

I have my kube cluster up and running on vmware cloud vsphere 
kubectl commands runs very well
When I try to do helm charts, my pods stay in Pending status forever.

steps:
helm install dokuwiki-demo bitnami/dokuwiki
kubectl get pods 
root@Master-VM:/home/ubuntu# kubectl get pods
NAME                                     READY   STATUS             RESTARTS       AGE
dokuwiki-demo-59898c4d8c-rftbc           0/1     Pending            0              2m27s

root@Master-VM:/home/ubuntu# kubectl logs dokuwiki-demo-59898c4d8c-rftbc
# **No Output**

root@Master-VM:/home/ubuntu# kubectl describe pods dokuwiki-demo-59898c4d8c-rftbc
Name:           dokuwiki-demo-59898c4d8c-rftbc
Namespace:      default
Priority:       0
Node:           <none>
Labels:         app.kubernetes.io/instance=dokuwiki-demo
                app.kubernetes.io/managed-by=Helm
                app.kubernetes.io/name=dokuwiki
                helm.sh/chart=dokuwiki-12.2.11
                pod-template-hash=59898c4d8c
Annotations:    prometheus.io/port: 9117
                prometheus.io/scrape: true
Status:         Pending
IP:
IPs:            <none>
Controlled By:  ReplicaSet/dokuwiki-demo-59898c4d8c
Containers:
  dokuwiki:
    Image:       docker.io/bitnami/dokuwiki:20200729.0.0-debian-10-r548
    Ports:       8080/TCP, 8443/TCP
    Host Ports:  0/TCP, 0/TCP
    Requests:
      cpu:      300m
      memory:   512Mi
    Liveness:   http-get http://:http/doku.php delay=120s timeout=5s period=10s #success=1 #failure=6
    Readiness:  http-get http://:http/doku.php delay=30s timeout=5s period=10s #success=1 #failure=6
    Environment:
      DOKUWIKI_USERNAME:         user
      DOKUWIKI_FULL_NAME:        User Name
      DOKUWIKI_PASSWORD:         <set to the key 'dokuwiki-password' in secret 'dokuwiki-demo'>  Optional: false
      DOKUWIKI_EMAIL:            user@example.com
      DOKUWIKI_WIKI_NAME:        My Wiki
      APACHE_HTTP_PORT_NUMBER:   8080
      APACHE_HTTPS_PORT_NUMBER:  8443
    Mounts:
      /bitnami/dokuwiki from dokuwiki-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-mq8zv (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  dokuwiki-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  dokuwiki-demo
    ReadOnly:   false
  kube-api-access-mq8zv:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                    From               Message
  ----     ------            ----                   ----               -------
  Warning  FailedScheduling  5m                     default-scheduler  0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling  2m39s (x1 over 3m39s)  default-scheduler  0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims.

**Comment by hickeyma** [comment]
@ramkrishna2k3 This looks like an issue with Persistent Volumes (PV) and binding with Persistent Volume Claims (PVC).  In the Bitnami Helm chart README, it mentions a known [persistence](https://github.com/bitnami/charts/tree/master/bitnami/dokuwiki#persistence) issue as well.

You will need to investigate the binding and why this is not happening in the cluster. It would be worth checking online for suggestion like [this](https://stackoverflow.com/questions/60774220/kubernetes-pod-has-unbound-immediate-persistentvolumeclaims). Otherwise, you might have to raise an issue with Bitnami.
