### ISSUE TITLE
Parser can't handle template snippets in --set flag

### ISSUE THREAD

**Issue by bluebrown** [helm/helm#10822]
Output of `helm version`: 

```
version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}
```

I noticed that the strval parser can't handle setting snippets such as `--set foo.bar="{{  .Values.buzz }}"`.  Doing this with the intention of rendering it with `tpl`.

I have tested this with helm 3.7.2. But I think the issue is not fixed yet, since I only noticed it when using the parser directly from go code.  https://github.com/helm/helm/blob/ee3f270e1eff0d462312635ad91cecd6f1fce620/pkg/strvals/parser.go#L45
Afterwards, I have used helm CLI to validate that it wasn't an issue with my code but the parser itself.

## Reproduce:

```bash
$ helm create foo
Creating foo

$ helm template test foo/ --set image.tag="{{ .Values.replicaCount }}"
Error: failed parsing --set data: key "}" has no value
```

**Comment by bacongobbler** [comment]
https://helm.sh/docs/intro/using_helm/#the-format-and-limitations-of---set

Curly braces are used to denominate a list. e.g. `--set name={a, b, c}` becomes

```
name:
  - a
  - b
  - c
```

You'll have to escape the curly braces.

**Comment by bluebrown** [comment]
Oh, OK, I see. Sorry, I missed that in the docs. I only knew the array index syntax `--set name[0]=a`. Thank you.
