### ISSUE TITLE
Support for conditionals on folder level + subfolders for template folder

### ISSUE THREAD

**Issue by rufreakde** [helm/helm#10828]
We are using **helm** together with **argoCD** and **bitnami sealed secrets**. 

To allow an easy landscape handling it would be nice to support subfolders in the templates directory that can hold a `conditional.tpl` that applies automatically to all files in its directory.

## conditional.tpl
```
# your conditional rule for this folder
{{ if .Values.dev }} # .Values.prod etc.
# this folders files are all deployed if values.dev is set
```

This way we would be able to maintain some different encrypted sealed secrets files or landscape specific values for configmaps on file level in a  declarative manner across all of our landscapes! Also this functionality could be reused for subcharts since it would be folder based.

It is also very cumbersome to use helm values.yaml for encrypted sealed secrets to circumvent this limitation of use!

Best regard,
rufreakde

**Comment by joejulian** [comment]
Could you use the `post-renderer` flag with kustomize to inject your secret?

**Comment by rufreakde** [comment]
> Could you use the `post-renderer` flag with kustomize to inject your secret?

I am not that experienced with this topic. From the documentation the post-renderer
https://helm.sh/docs/topics/advanced/#usage
```md
A post-renderer can be any executable that accepts rendered Kubernetes manifests on STDIN and returns valid Kubernetes manifests on STDOUT. It should return an non-0 exit code in the event of a failure. This is the only "API" between the two components. It allows for great flexibility in what you can do with your post-render process.

A post renderer can be used with install, upgrade, and template. To use a post-renderer, use the --post-renderer flag with a path to the renderer executable you wish to use:

$ helm install mychart stable/wordpress --post-renderer ./path/to/executable
If the path does not contain any separators, it will search in $PATH, otherwise it will resolve any relative paths to a fully qualified path

If you wish to use multiple post-renderers, call all of them in a script or together in whatever binary tool you have built. In bash, this would be as simple as renderer1 | renderer2 | renderer3.

You can see an example of using kustomize as a post renderer [here](https://github.com/thomastaylor312/advanced-helm-demos/tree/master/post-render).
```

I found a blog post using the post-renderer with argoCD.
https://dev.to/camptocamp-ops/use-kustomize-to-post-render-helm-charts-in-argocd-2ml6

I will investigate thurder and if I find a solution I will share it here so others can laverage this feature as well. Thanks for sharing @joejulian
