### ISSUE TITLE
Managing concurrent deployments by CI/CD

### ISSUE THREAD

**Issue by schollii** [helm/helm#10829]
Sometimes 2 developers merge to master within a couple minutes of each other. Whoever merges second will often get a helm failure to deploy due to "another operation (install/upgrade/rollback) is in progress". This is because circleci does not currently support queueing deployment jobs (unlike spinnaker, eg, which does), and circleci is for now what is being used. 

So I'm looking for way to make a helm deploy job wait till current one is done. 

One trick I think should work, is to use `kubectl create secret` (or `configmap`) since if the secret already exists, then the command fails. So I could easily script the deployment so that it first loops until that command succeeds, only then would it deploy new release, and at end (regardless of any failures), it would delete that secret. 

Does anyone foresee any gotchas with this approach? 

Also I'm wondering if there is data that a script could check for, that would tell it whether a helm install is in progress? I might not need the create-k8s-secret-as-lock approach, although checking such data will not prevent a race condition (eg one script checks if that data is true, sees it is true, and triggers a deploy, but meanwhile another script also saw that data true and started deploy first). 

Output of `helm version`:
```
$ helm version
version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.6"}
```

Output of `kubectl version`:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"b631974d68ac5045e076c86a5c66fba6f128dc72", GitTreeState:"clean", BuildDate:"2022-01-19T17:51:12Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.11-eks-f17b81", GitCommit:"f17b810c9e5a82200d28b6210b458497ddfcf31b", GitTreeState:"clean", BuildDate:"2021-10-15T21:46:21Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): EKS

**Comment by joejulian** [comment]
What about using `helm get -n <namespace> <release> --all` (or equivalent) and only deploying if the release is "deployed" or missing?

**Comment by schollii** [comment]
@joejulian too easy to get race condition: one deployment one script checks if that data is true, sees it is true, and triggers a deploy, but meanwhile another script also saw that data true and started deploy first. More abstractly, you can't do it without an atomic operation that succeeds only if no deployment is in progress AND gets a lock at the same time; both need to happen together. You cannot separate them and still get reliable mutual exclusion.

**Comment by schollii** [comment]
One gotcha with the strategy I mentioned is that deploy order is not guaranteed to match merge order. So for example if two merges A and B occur, in that order, very close together in time, the pipeline might run B deployment before A deployment. So really, The deployment script should wait for parent commit pipeline to finish or abort. Then it knows it can proceed safely. This is unfortunately not easy to do.

**Comment by schollii** [comment]
@joejulian can you clarify how this is different from what I describe in my OP?
