### ISSUE TITLE
Programatically change Helm values.yaml locally

### ISSUE THREAD

**Issue by 0GiS0** [helm/helm#10827]
Hi folks,

Trying to integrate a CI pipeline with Helm I faced some issues because I don't find the way to change the chart locally to commit those changes in a programatically way. I'll explain: If you have plain manifests you can do something like this to change the file and then push it to the repo:

```
kubectl patch --local -f tour-of-heroes-api/deployment.yaml -p '{"spec":{"template":{"spec":{"containers":[{"name":"tour-of-heroes-api","image":"$(ACR_NAME).azurecr.io/tourofheroesapi:$(Build.BuildId)"}]}}}}' -o yaml > temp.yaml && mv temp.yaml tour-of-heroes-api/deployment.yaml
cat tour-of-heroes-api/deployment.yaml
git add . 
git commit -m "Update tourofheroesapi to $(Build.BuildId)"
git push
```

Using kubectl patch --local is easy to do this but I couldn't find a fancy way to do the same with Helm... It would be nice if helm CLI could patch local files in order to perform this kind of automated tasks when you need to automate the whole process with a GitOps operator...

any thoughs?

Thank you so much!

**Comment by bacongobbler** [comment]
Sounds like a good use case for a third party tool.

**Comment by 0GiS0** [comment]
> Sounds like a good use case for a third party tool.

Well... with plain manifests you don't need a third party tool... you can do this with kubectl patch --local
