### ISSUE TITLE
`helm uninstall` deletes some PVCs

### ISSUE THREAD

**Issue by melissachang** [helm/helm#10820]
Output of `helm version`:

version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.8"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:17:57Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.15-gke.1000", GitCommit:"d71f5620130949cf5f74de04e6ae8f3a96e4b718", GitTreeState:"clean", BuildDate:"2022-02-02T09:21:18Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.20) exceeds the supported minor version skew of +/-1

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

GKE

----

Based on #5156, I expected `helm uninstall` to leave PVCs alone. Instead, `helm uninstall` deleted some of my PVCs.

Repro
- Install release which creates 12 PVCs
- `helm uninstall gradle-enterprise`
- Now only 3 PVCs

**Comment by yxxhero** [comment]
@melissachang one question: pvc which be deleted is created by helm?

**Comment by melissachang** [comment]
Yes, updated original bug to be more clear

**Comment by yxxhero** [comment]
@melissachang try use reclaim policy. Thanks very much.

**Comment by melissachang** [comment]
Someone explained the reason the 3 PVCs persisted was because they're associated with a `StatefulSet`, whereas the 9 PVCs there were deleted were associated with a `Deployment`.

If this is WAI, perhaps the fix to this issue could be to update https://helm.sh/docs/helm/helm_uninstall/. I couldn't find any information on PVCs there. The only thing I could find was #5156.

**Comment by yxxhero** [comment]
Someone explained the reason the 3 PVCs persisted was because they're associated with a StatefulSet, whereas the 9 PVCs there were deleted were associated with a Deployment.
@melissachang  it's right.  try  to use reclaim policy.  https://helm.sh/docs/topics/charts_hooks/#hook-deletion-policies

**Comment by joejulian** [comment]
Stated differently, the 3 PVCs that persisted were _not_ part of the helm manifest, only the StatefulSet was. The 9 PVCs that were deleted _were_ part of the manifest (created via template) and owned by the helm release. Deleting the helm release will delete all the resources in that manifest.
