### ISSUE TITLE
http: server gave HTTP response to HTTPS client

### ISSUE THREAD

**Issue by ypf-bendan** [helm/helm#10838]
When I use docker registry as a chart storage tool, I get this error: "http: server gave HTTP response to HTTPS client".
`# helm registry login 10.235.104.12:5000
Username: coapps
Password: 
INFO[0010] Error logging in to endpoint, trying next endpoint  error="Get \"https://10.235.104.12:5000/v2/\": http: server gave HTTP response to HTTPS client"
Error: Get "https://10.235.104.12:5000/v2/": http: server gave HTTP response to HTTPS client`

But docker login can login normally
`docker login 10.235.104.12:5000
Username: coapps
Password: 
Login Succeeded`

when use flag `--insecure`, login success, But push chart also failed.
`helm push chartmuseum-3.6.2.tgz oci://10.229.106.97:5000/helm-charts
Error: failed to do request: Head "https://10.229.106.97:5000/v2/helm-charts/chartmuseum/blobs/sha256:058e7bc5403d6a66519fd5b87372be382e935d0427d0fb142890d323d07726f3": http: server gave HTTP response to HTTPS client`

Output of `helm version`:
version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.5"}

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by w7089** [comment]
You probably need to download registry certificate and put it to trusted certs. Assuming name of cert is `ca.crt` and you are on linux follow the below:

```
cp [path_to_cert] /tmp/ca.crt
sudo cat /tmp/ca.crt | tee -a /etc/ssl/certs/ca-certificates.crt
```

**Comment by wangchao732** [comment]
I have same issue.
