### ISSUE TITLE
Helm 3 dry run does not validate label values

### ISSUE THREAD

**Issue by swright-eti** [helm/helm#10840]
I added the following label to a service definition:
` metrics.path: /{{ .Chart.Name }}/stats/prometheus`

When I do a dry run the template renders this and does not report any issues:
` metrics.path: /device-api/stats/prometheus`

But when I do an install without dry run Helm reports this:
`helm install device-api .
Error: INSTALLATION FAILED: Service "device-api" is invalid: metadata.labels: Invalid value: "/device-api/stats/prometheus": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')`

Output of `helm version`:

> version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.5"}

Output of `kubectl version`:

> Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.7+k3s1", GitCommit:"8432d7f239676dfe8f748c0c2a3fabf8cf40a826", GitTreeState:"clean", BuildDate:"2022-02-24T23:03:47Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Rancher K3s on bare metal.

**Comment by swright-eti** [comment]
If its not doing any validation, then why does a dry run fail with something like this.

I add a junk key like this to the container spec in a deployment template: 
` - thispropertyisillegal: nope`

Then do a dry run:
`helm install launchpad launchpad/ --dry-run
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Deployment.spec.template.spec.containers[0]): unknown field "thispropertyisillegal" in io.k8s.api.core.v1.Container, ValidationError(Deployment.spec.template.spec.containers[0]): missing required field "name" in io.k8s.api.core.v1.Container]`

**Comment by bacongobbler** [comment]
The kubernetes client comes built-in with some client validation. It knows the difference between a well-formed manifest and an invalid one. The client does not have any server-side validation, which is the error you’re running into in the OP. Label names are validated server-side IIRC.
