### ISSUE TITLE
Error: release: not found

### ISSUE THREAD

**Issue by impsik** [helm/helm#10844]
Output of `helm version`:
version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.5"}
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.10", GitCommit:"98d5dc5d36d34a7ee13368a7893dcb400ec4e566", GitTreeState:"clean", BuildDate:"2021-04-15T03:20:25Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
Cloud Provider/Platform (AKS, GKE, Minikube etc.): vmware

I have Rancher installed with helm and i wanted to upgrade Rancer. When i try to get values i get error:

```
helm get values rancher -n cattle-system
Error: release: not found
```
`helm list -A -n cattle-system` shows that some rancher parts are deployed. rancher-monitoring, rancher-webhook etc.
Rancher itself is working fine. 
`kubectl get pods -n cattle-system` shows that pods are up and running.
`helm repo list` shows that rancher-latest repo is also installed
Rancher was deployd with older helm version, 3.2 if i remember correctly. I also tried to use that version, but same problem.
`helm list --uninstalled --failed` output is also empty
`kubectl config get-contexts` shows that i'm using correct cluster

**Comment by adamyaziji** [comment]
`helm list -A -n cattle-system` is going to show you releases in all namespaces because of the `-A` flag. Is it possible that you deployed the rancher chart in a namespace other than `cattle-system`?

**Comment by impsik** [comment]
> `Is it possible that you deployed the rancher chart in a namespace other than cattle-system`?

`kubectl get pods -n cattle-system` shows that rancher is running under cattle-system NS
From Rancher UI i can double confirm that.
![image](https://user-images.githubusercontent.com/22597757/162568767-fd0b7014-9f51-4233-bb2e-e2f8d6f58c74.png)

**Comment by gausk** [comment]
@impsik can you share the output of `helm list -A`?

**Comment by impsik** [comment]
@gausk 
```
helm list -A
NAME                  	NAMESPACE               	REVISION	UPDATED                                 	STATUS  	CHART                                                                             	APP VERSION
cert-manager          	cert-manager            	1       	2021-05-06 12:50:30.354029945 +0300 EEST	deployed	cert-manager-v1.3.1                                                               	v1.3.1     
fleet                 	fleet-system            	3       	2021-05-05 11:41:42.740220371 +0000 UTC 	deployed	fleet-0.3.200                                                                     	0.3.2      
fleet-agent           	fleet-system            	1       	2021-02-11 11:17:49.42591835 +0000 UTC  	deployed	fleet-agent-v0.0.0+s-93f5f60605a130a5b02eebfb8cbda9c8fbfa3161c39432b15f3c8602bf7fa	           
fleet-crd             	fleet-system            	1       	2021-02-11 11:17:25.305450353 +0000 UTC 	deployed	fleet-crd-0.3.200                                                                 	0.3.2      
rancher-monitoring    	cattle-monitoring-system	1       	2021-06-02 14:43:37.067040601 +0000 UTC 	deployed	rancher-monitoring-9.4.202                                                        	0.38.1     
rancher-monitoring-crd	cattle-monitoring-system	1       	2021-06-02 14:43:22.886445043 +0000 UTC 	deployed	rancher-monitoring-crd-9.4.202                                                    	           
rancher-operator      	rancher-operator-system 	1       	2021-02-11 11:16:35.884973164 +0000 UTC 	deployed	rancher-operator-0.1.200                                                          	0.1.2      
rancher-operator-crd  	rancher-operator-system 	1       	2021-02-11 11:17:02.656290423 +0000 UTC 	deployed	rancher-operator-crd-0.1.200                                                      	0.1.2      
rancher-webhook       	cattle-system           	1       	2021-02-11 11:16:48.630773444 +0000 UTC 	deployed	rancher-webhook-0.1.0-beta900                                                     	0.1.0-beta9
```

**Comment by gausk** [comment]
@impsik as you can see the release name is `rancher-webhook`  in `cattle-system` namespace hence you should try `helm get values rancher-webhook  -n cattle-system`

**Comment by impsik** [comment]
@gausk rancher and rancher-webhook are two different things. If you look at the image from one of my previous comment then you can see that rancher is deploy under cattle-system namespace, or current output via kubectl
```
$ kubectl get pods -n cattle-system
NAME                               READY   STATUS    RESTARTS   AGE
rancher-687ccbb6cf-2cffd           1/1     Running   26         276d
rancher-687ccbb6cf-nv7v2           1/1     Running   20         276d
rancher-687ccbb6cf-rqmlz           1/1     Running   18         276d
rancher-webhook-577f5cb47c-phrhq   1/1     Running   0          13d
```

**Comment by impsik** [comment]
Anyone have any ideas on how to debug this problem?

**Comment by bacongobbler** [comment]
Everyone has suggested using `helm list -A`. The `-A` flag lists all releases in every namespace that is in the "deployed" state, but it does not catch releases which are in a different state than "deployed". It is possible that your rancher release is in an unhealthy state.

Try running `helm list -a -A` (long form `helm list --all --all-namespaces`) to list every release in every namespace, without any filtering applied.

**Comment by bacongobbler** [comment]
https://helm.sh/docs/helm/helm_list/#helm

**Comment by impsik** [comment]
@bacongobbler 
```
$ helm list -a -A
NAME                  	NAMESPACE               	REVISION	UPDATED                                 	STATUS  	CHART                                                                             	APP VERSION
cert-manager          	cert-manager            	1       	2021-05-06 12:50:30.354029945 +0300 EEST	deployed	cert-manager-v1.3.1                                                               	v1.3.1     
fleet                 	fleet-system            	3       	2021-05-05 11:41:42.740220371 +0000 UTC 	deployed	fleet-0.3.200                                                                     	0.3.2      
fleet-agent           	fleet-system            	1       	2021-02-11 11:17:49.42591835 +0000 UTC  	deployed	fleet-agent-v0.0.0+s-93f5f60605a130a5b02eebfb8cbda9c8fbfa3161c39432b15f3c8602bf7fa	           
fleet-crd             	fleet-system            	1       	2021-02-11 11:17:25.305450353 +0000 UTC 	deployed	fleet-crd-0.3.200                                                                 	0.3.2      
rancher-monitoring    	cattle-monitoring-system	1       	2021-06-02 14:43:37.067040601 +0000 UTC 	deployed	rancher-monitoring-9.4.202                                                        	0.38.1     
rancher-monitoring-crd	cattle-monitoring-system	1       	2021-06-02 14:43:22.886445043 +0000 UTC 	deployed	rancher-monitoring-crd-9.4.202                                                    	           
rancher-operator      	rancher-operator-system 	1       	2021-02-11 11:16:35.884973164 +0000 UTC 	deployed	rancher-operator-0.1.200                                                          	0.1.2      
rancher-operator-crd  	rancher-operator-system 	1       	2021-02-11 11:17:02.656290423 +0000 UTC 	deployed	rancher-operator-crd-0.1.200                                                      	0.1.2      
rancher-webhook       	cattle-system           	1       	2021-02-11 11:16:48.630773444 +0000 UTC 	deployed	rancher-webhook-0.1.0-beta900                                                     	0.1.0-beta9
```

**Comment by bacongobbler** [comment]
Hmm. If nothing shows up when you use that command, then there are four possible outcomes here:

1. You installed rancher using an older version of helm, such as Helm 2. You will need to check and migrate that release to Helm 3.
2. The release was installed with a separate Helm storage driver. You’ll want to check and verify following the Helm docs on alternative storage drivers. 
3. The release secret was deleted with `kubectl delete` or through other commands. A quick way to check might be to see if the rancher Deployment contains a label that specifies it was “installed-by” Helm.
4. Rancher was never installed with Helm. perhaps a `helm template` was piped to `kubectl apply`.

Hope this helps.

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!
