### ISSUE TITLE
How to check the environment information of all nodes while helm Install

### ISSUE THREAD

**Issue by dazuimao1990** [helm/helm#10857]
HI everyone，I met a problem when develop charts for my application.

How to check the environment information of all nodes while helm Install? 

For example, the nodes of kubernetes should meet the following conditions:

- kernel version >= 4.0.0
- 80 443 ports should not be used.
- anything else. etc...

My application needs these conditions,otherwise it will fail to deploy.

So I was wondering if there was a mechanism for this kind of environment check, and if it didn't pass, the HELM process could be terminated and the problem message printed to the screen.

Anyone helps? thanks 😊

**Comment by bacongobbler** [comment]
Some cluster information provided by kubernetes is available through the [built-in objects API](https://helm.sh/docs/chart_template_guide/builtin_objects/). Anything else may have to go [through the `lookup` function](https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-lookup-function).

Hope this helps.

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!
