### ISSUE TITLE
Deployed resources differ from stored manifest

### ISSUE THREAD

**Issue by sbkg0002** [helm/helm#10865]
## Output of `helm version`:
```
version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.18.1"}
```

## Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

## Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
EKS

## Hem chart
The issue is with the [Goldilocks Helm Chart](https://github.com/FairwindsOps/charts/blob/master/stable/goldilocks/templates/dashboard-ingress.yaml#L1). The chart snippet in question:
```yaml
{{- if and .Values.dashboard.enabled .Values.dashboard.ingress.enabled }}
{{- $fullName := include "goldilocks.fullname" . -}}
{{- $apiV1 := false -}}
{{- if and (.Capabilities.APIVersions.Has "networking.k8s.io/v1") (semverCompare ">= v1.19.0" .Capabilities.KubeVersion.Version) -}}
apiVersion: networking.k8s.io/v1
{{- $apiV1 = true -}}
{{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
```

## The issue
The chart correctly creates a `Ingress` object with `apiVersion: networking.k8s.io/v1`:
```
# kubectl get ingress -n goldilocks goldilocks-dashboard -oyaml | head -1
apiVersion: networking.k8s.io/v1
```
But, the stored manifest does not:
```
# helm get manifest goldilocks -n goldilocks | grep -A2 dashboard-ingress.yaml
# Source: goldilocks/templates/dashboard-ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
```

Since the stored manifest is used by tools like `kubens` and `pluto` to detect depricated API versions, this results in false positives.

What am I missing?

**Comment by joejulian** [comment]
The API server will return whatever version you query from it. The only way to determine the version that's actually stored, would be to query etcd. Additionally, the API server will always use the storage version that is considered the "latest stable", which occasionally is not actually the latest. It will store it that way regardless of which version you deliver to it.
