### ISSUE TITLE
Support multiple YAML documents through stdin

### ISSUE THREAD

**Issue by jkroepke** [helm/helm#10866]
Hi,

as maintainer of https://github.com/jkroepke/helm-secrets, I'm looking into a way to pass decrypted value secured files to helm.

Currently, encrypted value files needs to be decrypted first and the decrypted value file needs to be passed 2 a second helm call.

Helm allow values from stdin (https://github.com/helm/helm/pull/2809), but it's not possible to pass multiple YAML documents through stdin.

**Comment by iverberk** [comment]
I need this functionality for a similar use-case. Hopefully this can be merged soon!

**Comment by jkroepke** [comment]
@iverberk consider to leave a comment on the PR, it may helps more

**Comment by Orrimp** [comment]
Dito

**Comment by jkroepke** [comment]
Thanks for the Information

**Comment by joejulian** [comment]
This can be solved in bash using [process substitution](https://tldp.org/LDP/abs/html/process-sub.html):
```
helm install myrelease mychart --values <(openssl aes-256-cbc -d -in secretvalues.yaml.enc)
```

The `<()` creates a pipe with two fds and replaces itself with the path of that pipe. Helm will then open that pipe and read from it.

**Comment by jkroepke** [comment]
Hi @joejulian 

the solution you advertised does not match the original posting, since helm supports stdin in this case.

```
openssl aes-256-cbc -d -in secretvalues.yaml.enc | helm install myrelease mychart --values -
```

What I want is something like this:

```bash
{ openssl aes-256-cbc -d -in secretvalues.yaml.enc; openssl aes-256-cbc -d -in secretvalues.dev.yaml.enc } | helm install myrelease mychart --values -
```

Having n amount of values files and pass them to helm.

Note, this would not work:

```bash
helm install myrelease mychart --values <(openssl aes-256-cbc -d -in secretvalues.yaml.enc; openssl aes-256-cbc -d -in secretvalues.dev.yaml.enc)
```

But what happens now, if the openssl command fails? Then crazy shell magic is required nothing here works in windows.

**Comment by jkroepke** [comment]
@joejulian could you please re-open this issue? Otherwise I have to create a new one.

**Comment by joejulian** [comment]
This is easily solved like this:

```
helm install <(openssl aes-256-cbc -d -in secretvalues.yaml.enc) --values <(openssl aes-256-cbc -d -in secretvalues.dev.yaml.enc)
```
