### ISSUE TITLE
Enhancement request: more debug logging messages

### ISSUE THREAD

**Issue by MrDrMcCoy** [helm/helm#10864]
Output of `helm version`:

```
version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.8"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"archive", BuildDate:"2022-03-17T21:14:47Z", GoVersion:"go1.18", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"56709e92afa973c26fad3d4a44723fefa51481b7", GitTreeState:"clean", BuildDate:"2022-03-10T07:59:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): `AKS`

### Issue

When a Helm chart pulls in extraneous, non-template files that cause the chart to exceed the maximum entity size limit for your Kubernetes provider, Helm provides no mechanism to determine which object has exceeded this size or why. Running Helm with `--debug`, `--dry-run`, or generating manifests with `helm template` will not show any objects of unusual size. The only way to determine why issues like this may occur is to shunt Helm through something like `mitmproxy` as I had  to (#10851), which showed that the generated release secret had pulled in undesired files that were not accounted for by `.helmignore`.

### Proposed solution

The stress, pain, and lost productivity from battling scenarios like this could be easily avoided if the logging outputs would be enhanced in the following ways:

1. Add debug messages to show each non-template file that is added to the chart.
2. Improve the `Request entity too large` error to include some metadata about the generated resource that was too large, to give both users and devs a clue about where they should be looking.

**Comment by joejulian** [comment]
I am a little curious about why `helm template` didn't show that. If the resource is over 1MB, it should be over 1MB when templated. Any ideas why that was different?

I agree, however, that more details would be valuable. I've run in to that constraint numerous times, myself.

**Comment by MrDrMcCoy** [comment]
@joejulian The reason that `helm template` and `--dry-run` didn't show anything unusual is that Helm was sucking non-template files into the release secret, and the release secret is not included in the dry-run and template operations. As a result, the test data and previous release files that were not properly excluded in `.helmignore` were silently inflating the release secret beyond the maximum K8S object size. Having logging to show when non-template files are pulled in to a release would help to not only avoid issues like this in the future, but also potentially avoid data leaks in externally-facing charts.

**Comment by MrDrMcCoy** [comment]
Were I a Go developer, I would take this on myself, but alas I am not. Is there a kind soul that can take this on, or must it die a slow death at the hands of the stale actions bot?

**Comment by joejulian** [comment]
> the test data and previous release files that were not properly excluded

I don't really understand this part. It would seem that those would be in the output of `helm template` regardless. Looking at what's included in the template output seems like it should be a good way to determine what shouldn't be there.

As an aside, `helm template myrelease mychart --values myvalues.yaml | gzip | wc -c` should give you an approximation to start estimating the size of the release secret.
