### ISSUE TITLE
How to check if Helm release is up to date before upgrading?

### ISSUE THREAD

**Issue by Jont828** [helm/helm#10863]
I'm working on a helm controller where a CRD containing fields like repo URL, chart name, release name, version, and values is given to the controller. If the release doesn't exist, I call `installClient.RunWithContext()` to install the release on the cluster. I'd like to implement behavior such that if the release does exist, we can check if there is anything to change before running `upgradeClient.RunWithContext()`. If there's nothing to change, I'd like to reconcile loop to be a no-op. It seems like `upgradeClient.RunWithContext()` is not idempotent since the revision number is still incremented, so I'm wondering how I could implement a Reconciler that only upgrades if there is something to change.

**Comment by joejulian** [comment]
I did it by comparing the values and chart version. If neither of those change, then there's be nothing to apply.

**Comment by Jont828** [comment]
@joejulian How would you check the values? I'm getting the existing release `existing` with `getClient.Run(name)` and trying to compare `existing.Config` with the values I'm passing in. However, I'm running into an issue where the string value "6" is parsed by MergeValues as an `int64` while the value I'm getting back is a `float64`. 

```
p := helmGetter.All(settings)
valueOpts := &helmVals.Options{
	Values: parsedValues,
}
vals, err := valueOpts.MergeValues(p)
if err != nil {
	return nil, false, err
}

getter := helmAction.NewGet(actionConfig)
release, err := getter.Run(spec.ReleaseName)

fmt.Printf(cmp.Diff(release.Config, vals))
```
This gives the diff below:


```
map[string]interface{}{
-       "cloudControllerManager": map[string]interface{}{"containerResourceManagement": map[string]interface{}{"limitsCPU": float64(6)}},
+       "cloudControllerManager": map[string]interface{}{"containerResourceManagement": map[string]interface{}{"limitsCPU": int64(6)}},
        "infra":                  map[string]interface{}{"clusterName": string("default-9181")},
  }
```
The issue seems to be that
