### ISSUE TITLE
How do I specify the latest build number in Chart.yaml and command line?

### ISSUE THREAD

**Issue by red8888** [helm/helm#10862]
FYI opened an SO post for this question: https://stackoverflow.com/questions/71861292/how-do-i-specify-the-latest-build-number-in-chart-yaml-and-command-line

Output of `helm version`:  "v3.8.0"

Im using full semver2 version strings which helm supports, here is an example: `'1.2.3-myfeature+11'`

The build number is incremented by my CI/CD system every build. In my Chart.yaml and, more importantly, via command line I want to specify a version constraint that always pulls the latest build number. I'm not sure what the right syntax is.

I want to get the latest version (build number) of '1.2.3-myfeature'

If I just do this it does not pull the latest build number, I'm not sure how it chooses which version to pull:
`helm pull myrepo/mychart --version '1.2.3-myfeature' --devel`

If I do this I get a syntax error:
`helm pull myrepo/mychart --version '1.2.3-myfeature*' --devel`

`no chart version found for...`

This also does not work:
`helm pull myrepo/mychart --version '~1.2.3-myfeature' --devel`

It seems to be using alphanumeric sorting against the entire string after `~1.2.3-` when I try this last example?

**Comment by bacongobbler** [comment]
From https://semver.org/#spec-item-10:

> Build metadata MUST be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence.

In other words, when you use build metadata, there is no order.

**Comment by red8888** [comment]
This would also mean there would be no order between version like this too right?
`'~1.2.3-myfeature+10'`
`'~1.2.3-myOtherfeature+4'`

**Comment by bacongobbler** [comment]
From https://semver.org/#spec-item-9:

> Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1

A way you could accomplish this is by using the convention `1.2.3-myfeature.11` and `1.2.3-myfeature.12`. That should in theory be sortable.

**Comment by red8888** [comment]
hmm it seemed like the entire string after the version number is treated the same though.

If I used `.<BUILD_NUMBER>` and specified version constraints like this would I get my desired behavior? 
`'~1.2.3-myfeature'`
`'~1.2.3-myOtherfeature'`

Where `'~1.2.3-myfeature'` would return `1.2.3-myfeature.<HIGHEST NUMBER>` ?
