### ISSUE TITLE
Can “helm show” support viewing values.schema.json

### ISSUE THREAD

**Issue by xiaomudk** [helm/helm#10860]
Output of `helm version`:

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

## If it is supported, I can get the json schema through the api to generate the html form, which is definitely a great feature!

`helm show` add subcommand schema,like this:
```
  schema    show the chart's values.schema.json
```

**Comment by xiaomudk** [comment]
@joejulian @yxxhero  can we discuss its necessity？

**Comment by joejulian** [comment]
The schema is not stored in the release. That data is not available to `show`. What problem are you trying to solve?

**Comment by joejulian** [comment]
This seems to have been abandoned. Closing.
