### ISSUE TITLE
Please make .Files.Get produce warnings when empty output is caused by an error (e.g. because of a missing file)

### ISSUE THREAD

**Issue by hartwork** [helm/helm#10875]
Hello Helm team,

thanks for creating and sharing Helm as software libre, very nice! :pray: 

It has come to my attention that `.Files.Get` can easily become a source of frustration because:
- It behaves somewhat unexpected compared to Unix (e.g. `"dir/file.txt"` works but `"./dir/file.txt"` does not and `"dir/../dir/file.txt"` does not either)
- It does not produce errors or warnings, not even with `--debug`, and just produces empty output in case of an error.

I understand that changing the code to abort with an error on e.g. a missing file would potentially break existing charts that rely on the current behavior.
What I would like to suggest is for `.Files.Get` to produce warnings, at least with `--debug`, to ease user debugging at least a bit.  What do you think?

Thanks and best

Sebastian

**Comment by butterfly1924** [comment]
Why can't we support unix-supported Filepath format?

**Comment by hartwork** [comment]
I have slightly adjusted my wording now to make it clear that I consider aborting on error backwards incompatible, and just that. I don't expect any trouble from fully supporting Unix filepaths now.

**Comment by hartwork** [comment]
@helm any comments?

**Comment by joejulian** [comment]
You can solve this by checking the output:
```
{{- $f := .Files.Get $path -}}
{{- if empty $f -}}
{{- error $path is empty or has produced and error -}}
{{- else -}}
{{- $f -}}
{{- end -}}
```

**Comment by hartwork** [comment]
Please drop stale mark

**Comment by joejulian** [comment]
This support question has been answered. Closing.

**Comment by hartwork** [comment]
This was not a support question.
