### ISSUE TITLE
Function `pick`, `omit` and like takes a list of string as the argument

### ISSUE THREAD

**Issue by ckyoog** [helm/helm#10876]
As defined in https://helm.sh/docs/chart_template_guide/function_list/#pick, the function `pick`, `omit` and like takes variadic strings arguments.
```
$new := pick $myDict "name1" "name2"
$new := omit $myDict "name1" "name3"
```
It would be wonderful if they can take a list of string as argument. For most of cases I have met, the keys to `pick` or `omit` come from some dynamic list. For instance, the keys are defined in the values file.

Now my workaround is like
```helm
{{- $new := dict }}
{{- range $key, $val := $sourceDict }}
  {{- if has $key $keysToPickList }}
    {{- $new = dict $key $val | merge $new }}
  {{- end }}
{{- end }}
```
or this one with less code and better performance
```
{{- $new := dict }}
{{- range $key := $keysToPickList }}
  {{- $new = pick $sourceDict $key | merge $new }}
{{- end }}
```

**Comment by bacongobbler** [comment]
As these functions are provided by [sprig](/Masterminds/sprig), please file feature requests there. If implemented, we will pick them up in the next release update. Thanks!

**Comment by ckyoog** [comment]
OK, thank you! (oh, wait, it's you again.)
