### ISSUE TITLE
coalesce.go:175: warning: skipped value for Helm-Chart.env: Not a table. Error: INSTALLATION FAILED: template: Helm-Chart/templates/deployment.yaml:33:21: executing "Helm-Chart/templates/deployment.yaml" at <.name>: can't evaluate field name in type interface {}

### ISSUE THREAD

**Issue by webcoderz** [helm/helm#10878]
Output of `helm version`:
version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.17.5"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

AWS EKS && azure AKS

i am bringing env variables into my pods like 

    
```
containers:
        - env:
   {{- range .Values.env }}
          - name: {{ .name  }}
            value: {{ .value | quote }}
   {{- end }}
```

and the envs in values.yaml are like

```
env:
 - name: FOO
   value: "bar"
 - name: SOME_VAR
   value: "SOMETHING"
 - name: SOME_OTHER_VAR
   value: "bar"
```

i used to be able to do
```
helm install chart_name --name release_name \
 --set env.FOO="BAR"
```

at deployment but now am getting 
coalesce.go:175: warning: skipped value for Helm-Chart.env: Not a table. Error: INSTALLATION FAILED: template: Helm-Chart/templates/deployment.yaml:33:21: executing "Helm-Chart/templates/deployment.yaml" at <.name>: can't evaluate field name in type interface {}

going even further verbose trying to deploy via

```
helm install chart_name --name release_name \
 --set env.FOO.value="BAR"
```

gives me an 

coalesce.go:175: warning: skipped value for helm-chart.env: Not a table.
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(DaemonSet.spec.template.spec.containers[0].env[0]): missing required field "name" in io.k8s.api.core.v1.EnvVar

if i dont try to override any of the .Values.env it deploys just fine. in this case i just want to override maybe one or two out of the many env variables i have set there.

**Comment by mmoscher** [comment]
Having the exact same issue on ubuntu 20.04 using helm v3.8.1

Any clues what's going wrong?

**Comment by webcoderz** [comment]
ye im running Ubuntu 20.04.4 as well tried downgrading helm to 3.6.1 also, still same issue

**Comment by webcoderz** [comment]
bump

**Comment by webcoderz** [comment]
bump

**Comment by webcoderz** [comment]
bump

**Comment by joejulian** [comment]
To do what you're suggesting, you'd have to have your values like:
```yaml
env:
  FOO: bar
  SOME_VAR: SOMETHING
  SOME_OTHER_VAR: bar
```

Then you would add them to your container template by walking the key, value:
```yaml
  env:
{{- $key, $value := range .Values.env }}
    - name: {{ $key }}
      value: {{ $value }}
{{- end }}
```

**Comment by joejulian** [comment]
--set env.FOO=baz
