### ISSUE TITLE
Feature request: Support a values file directory, such as values.d

### ISSUE THREAD

**Issue by tculp** [helm/helm#10886]
Re-open of #10416 

Values.yaml files often get large and can get unwieldy. It would be convenient to be able to easily split up values files.

While multiple values.yaml files can be specified on the command line, it is somewhat cumbersome, especially with more than one or two files. Also, in subcharts, additional values files are infeasible.

A common paradigm in the linux world is to have a combination of a config file and a config.d folder, such as for system services. Such a paradigm could be used by helm to allow a values.d or values.yaml.d folder, which would automatically get loaded and merged with the values.yaml file.

Even if it was a non-default parameter, such as --values-dir, this would still be quite useful.

Side note: I find the GitHub stale-bot actively harmful, and it probably shouldn't run on feature requests

**Comment by hickeyma** [comment]
Closing as #10416 re-opened.
