### ISSUE TITLE
Can we reference values.yaml files values in Chart.yaml dependencies section:

### ISSUE THREAD

**Issue by parasappafluke** [helm/helm#10887]
Output of `helm version`:  **v3.1.2**

Output of `kubectl version`: **v1.21**

Cloud Provider/Platform (AKS, GKE, Minikube etc.): **AWS EKS**

Hello All,
Is there way we can reference `values.yaml` file values in Chart.yaml dependencies section. One of requirement is we have a `umbrella` chart, where we want the dependencies chart version to be read from different env `values.yaml `file, so that we can specify different chart version for subcharts for different env.
Thanks 
parasappa

**Comment by mariot8** [comment]
afaik there is no such option yet, see https://github.com/helm/helm/issues/2205

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!
