### ISSUE TITLE
Error: validation: chart.metadata.version "2.9.0-00056318"  is broken when numeric characters only

### ISSUE THREAD

**Issue by sta-szek** [helm/helm#10882]
Output of `helm version`: `version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}`

The version: `2.9.0-00056318` is valid SemVer2, according to:

```
<valid semver> ::= <version core>
                 | <version core> "-" <pre-release>
                 | <version core> "+" <build>
                 | <version core> "-" <pre-release> "+" <build>

<version core> ::= <major> "." <minor> "." <patch>

<major> ::= <numeric identifier>

<minor> ::= <numeric identifier>

<patch> ::= <numeric identifier>

<pre-release> ::= <dot-separated pre-release identifiers>

<pre-release identifier> ::= <alphanumeric identifier>
                           | <numeric identifier>
```

we fall into category: `<version core> "-" <pre-release>` which in our case is:
`<version core>` -> `2.9.0` -> proper version
`-` -> the proper dash sign
`<pre-release>` -> `00056318` -> aplhanumveric

https://semver.org/#semantic-versioning-specification-semver

what is interesting, it happens randomly, some helm charts are being deployed with that version, some are reporting errors literally speaking out of sudden.

is there any temporary workaround? i mean to disable `chart.metadata.version` validation when we do helm template / validate ? but preserve all other checks?

--- edit
tested with commit `2.9.0-8d72c591` and it passed -> looks like the SemVer check in helm is broken, and when there is no letters in the `pre-release identifier` then it fails.

`2.9.0-8d72c591` -> works
`2.9.0-00056318` -> fails

updated ticket summary

**Comment by bacongobbler** [comment]
From https://semver.org/#spec-item-9

> Numeric identifiers MUST NOT include leading zeroes.

**Comment by joejulian** [comment]
The way we handle that is by adding `dev.` before the sha when generating versions. `2.9.0-00056318` becomes `2.9.0-dev.00056318`

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!
