### ISSUE TITLE
[Query] How to share configurations of values.yaml between different charts

### ISSUE THREAD

**Issue by xiaofhe** [helm/helm#10885]
Hi,
    How to share configurations of values.yaml between different charts
    I have my first Chart1 and its values1.yaml where the parameter A should be configured by operator, for example A is set to 1. 
    I also the second Chart2 and its values2.yaml where there is parameter A too. it should be also set to 1 as that in values1.yaml.
    currently the operator should configure it twice in two values.yaml files while the configuration is totally the same.
    is there any way to share the configurations  between two different charts ?
    the purpose is to reduce the duplicated configuration and let the operator configure the same parameter at only one values.yaml ? 
   thanks

**Comment by hickeyma** [comment]
@xiaofhe You should be able to add common values to a common values file and pass it using the `--values` flag or alternatively set on CLI using `--set` flag.
