### ISSUE TITLE
helm install does not respect --username and --password flags for OCI charts

### ISSUE THREAD

**Issue by pantosha** [helm/helm#10881]
The `helm install` command ignores `--username` and `--password` parameters when it's called for chart from OCI registry

```sh
helm install oci://repo.azurecr.io/helm/chartname --username user --password password --generate-name --namespace ns
```

Output of `helm version`:
```
version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.17.5"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"07959215dd83b4ae6317b33c824f845abd578642", GitTreeState:"clean", BuildDate:"2022-03-30T18:28:25Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS

**Comment by joejulian** [comment]
@pantosha Could you please extend that description a bit? What symptoms are you encountering/can you document how those are being ignored?

**Comment by CiiDyR** [comment]
Hey @joejulian 

I think what @pantosha is trying to suggest is the following: Currently when you want to install a helm chart, you need to run `helm registry login` first. You can't just use `helm template oci://registry --username username --password supersecure` instead.
It would be pretty handy to not have to authenticate against the registry prior to using it. Sometimes (especially in CI) it's helpful to just pass the authentication data right with the command
