### ISSUE TITLE
Install memory leak in 3.7.2

### ISSUE THREAD

**Issue by denouche** [helm/helm#10883]
Hello,
A memory leak in install action was fixed in v3.8.1: https://github.com/helm/helm/commit/5059ae843ef6b504fe55f914953e249a14ff5838
But this commit hasn't been cherry-picked to the v3.7 branch, so the 3.7.2 release still have this problem.
Is it possible to cherry-pick this commit to v3.7 branch and release a v3.7.3 with the fix?
Thanks in advance!

**Comment by bacongobbler** [comment]
We are not cherry picking fixes into older releases. Please upgrade to Helm 3.8 to receive the fix.

**Comment by denouche** [comment]
I'm stuck with Helm 3.7 because some Kubernetes Cloud Provider are still in kubernetes v1.19 on stable channel, and Helm 3.8 does not support Kubernetes 1.19 anymore.
