### ISSUE TITLE
If $HELM_DATA_HOME contains spaces, plugins stop working

### ISSUE THREAD

**Issue by jkroepke** [helm/helm#10884]
Output of `helm version`:
version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.8"}

If `HELM_DATA_HOME` contains spaces, like `/Users/My Name/Library/helm` or `C:\Users\My Name\AppData\Roaming\helm`, no plugins can be executed.

Error:

> Error: fork/exec /Users/My: no such file or directory

> 'C:\Users\My' is not recognized as an internal or external command,
operable program or batch file.

Helm manually splits the command by space:

https://github.com/helm/helm/blob/699ea6dcef302d7ded608bc8a1ab6c404de81685/pkg/plugin/plugin.go#L152
https://github.com/helm/helm/blob/699ea6dcef302d7ded608bc8a1ab6c404de81685/pkg/plugin/plugin.go#L124-L129

**Comment by sureshdsk** [comment]
@joejulian i would like to work on this issue.

**Comment by sureshdsk** [comment]
@joejulian I've created a PR #10913   that fixes this issue. can you review the PR?

**Comment by piroux** [comment]
ping  @yxxhero @zonggen

**Comment by sureshdsk** [comment]
@yxxhero @zonggen @joejulian  who is the right person to review this and merge?  https://github.com/helm/helm/pull/10913

**Comment by jkroepke** [comment]
👍
