### ISSUE TITLE
How to verify if I have Helm3 installed? 

### ISSUE THREAD

**Issue by shivanshi18** [helm/helm#10897]
Output of `helm version`: version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  microk8s

**Comment by bacongobbler** [comment]
Try `helm version`.

**Comment by shivanshi18** [comment]
Output of helm version: version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}


does this mean I have Helm3 or Helm CLI v3 ? or is it the same thing?

**Comment by bacongobbler** [comment]
They're the same thing.

**Comment by bacongobbler** [comment]
https://helm.sh/docs/faq/changes_since_helm2/#removal-of-tiller
