### ISSUE TITLE
How to remove the dependency of service principals in "helm repo add" 

### ISSUE THREAD

**Issue by shivanshi18** [helm/helm#10898]
Output of `helm version`: version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  microk8s

**Comment by shivanshi18** [comment]
currently we use :

helm repo add $(registryName)  https://$(registryName).azurecr.io/helm/v1/repo --username SPID --password SECRET

**Comment by bacongobbler** [comment]
I’m not quite sure I understand the question. What is it that you are trying to achieve?

**Comment by bacongobbler** [comment]
Ping.
