### ISSUE TITLE
mustToJson isn't validating json strings correctly

### ISSUE THREAD

**Issue by red8888** [helm/helm#10895]
Output of `helm version`:
version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.6"}

I used mustToJson against this string: `'[{"dfsdfdsf": "sdfsdf"]'`
It didn't throw an error and returned this: `"[{\"dfsdfdsf\": \"sdfsdf\"]"`

It should fail because thats invalid json right? Or maybe I'm misunderstanding how it supposed to work. I also opened an issue with sprig for this behavior: https://github.com/Masterminds/sprig/issues/332

**Comment by bacongobbler** [comment]
Thanks. As this has to be solved at sprig, let’s close this ticket in favour of Masterminds/sprig#322. Once a fix has been made available we will pick it up in the next release.
