### ISSUE TITLE
Can jsonschema support include the new contentMediaType field?

### ISSUE THREAD

**Issue by red8888** [helm/helm#10894]
Output of `helm version`: 
version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.6"}

Draft 7 supports neat new fields for validating string properties: https://json-schema.org/understanding-json-schema/reference/non_json_data.html#contentschema

Helm 3 uses draft 7 but in my testing contentMediaType was ignored.

I tried adding this property:
```
                        "myprop": {
                            "type": "string",
                            "contentMediaType": "application/json",
                            "default": ""
                        },
```

set the myprop param to "not valid json" and ran helm lint. It passed while it _should_ have failed.

I'm hoping supporting this is as easy as bumping up the jsonschema package helm uses? Maybe that package doesn't yet support this, but seems like it was released several years ago so hopefully it does.

**Comment by bacongobbler** [comment]
gojsonschema has not seen any activity since October 2020. It is likely out of date and unlikely to receive any fixes or changes.

we discussed replacing it with something that is more well maintained in https://github.com/helm/helm/issues/10732, but I haven’t seen anyone pick up the work.
