### ISSUE TITLE
helm harbor is not a valid chart repository or cannot be reached: object required

### ISSUE THREAD

**Issue by w7089** [helm/helm#10892]
I've successfully pushed some locally built helm chart to harbor private helm registry using below commands:

```
helm registry login private.harbor.com
helm push chart-version.tgz oci://private.harbor.com/some-project
```

Now I fail to add helm repo (for the goal of installation of the pushed helm chart) using below commands:

```
$ helm repo add helm-test2 oci://private.harbor.com/some-project/
Error: looks like "oci://private.harbor.com/some-project/" is not a valid chart repository or cannot be reached: object required
$ helm repo add helm-test2 oci://private.harbor.com/some-project/helm-test-repo
Error: looks like "oci://private.harbor.com/some-project/helm-test-repo" is not a valid chart repository or cannot be reached: object required
$ helm repo add helm-test2 https://private.harbor.com/some-project/helm-test-repo
Error: looks like "https://private.harbor.com/some-project/helm-test-repo" is not a valid chart repository or cannot be reached: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type repo.IndexFile
$ helm repo add helm-test2 https://private.harbor.com/some-project
Error: looks like "https://private.harbor.com/some-project" is not a valid chart repository or cannot be reached: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type repo.IndexFile
```

How to `helm repo add` Harbor OCI helm repository?

It's important to note that docker images are stored alongside pushed helm charts at  `private.harbor.com/some-project/`.

Alternative way that worked is uploading helm chart under `Helm charts` tab in `some-project` in Harbor UI. 

Afterwards, below commands for adding and installing the chart worked:

```
helm repo add helm-test https://private.harbor.com/chartrepo/some-project
helm repo update helm-test
helm install chart helm-test/chart --version 1.5.0
```

I would use this method, but have no idea how to push to `https://private.harbor.com/chartrepo/some-project`, pushing to `oci://...` worked only after following [this][1] github link.

Below attempts failed:

```
helm push chart-version.tgz oci://private.harbor.com/chartrepo/some-project
Error: unexpected status: 401 Unauthorized
helm push chart-version.tgz https://private.harbor.com/chartrepo/some-project
Error: scheme "https" not supported
```

I'm using latest helm (3.8) and harbor version (2.5)

  [1]: https://github.com/goharbor/harbor/issues/13170

**Comment by bacongobbler** [comment]
Have you tried reaching out to the Harbor maintainers? They may be better suited to answer questions related to how Harbor works and why you’re seeing this error raised from the server.

**Comment by crazy-canux** [comment]
OCI not working with "helm repo".
https://helm.sh/zh/docs/topics/registries/

**Comment by joejulian** [comment]
This says that at your url, the `index.yaml` file could not be unmarshalled into a [IndexFile struct](https://github.com/helm/helm/blob/d83dd95cae27ef95792ebfa0f4dc5ca6d9fda538/pkg/repo/index.go#L81-L93). This suggests that the url might be returning something other than what's expected.

See what happens if you use curl:
```

**Comment by joejulian** [comment]
Closing for lack of response.

**Comment by jr00364** [comment]
> I've successfully pushed some locally built helm chart to harbor private helm registry using below commands:
> 
> ```
> helm registry login private.harbor.com
> helm push chart-version.tgz oci://private.harbor.com/some-project
> ```
> 
> Now I fail to add helm repo (for the goal of installation of the pushed helm chart) using below commands:
> 
> ```
> $ helm repo add helm-test2 oci://private.harbor.com/some-project/
> Error: looks like "oci://private.harbor.com/some-project/" is not a valid chart repository or cannot be reached: object required
> $ helm repo add helm-test2 oci://private.harbor.com/some-project/helm-test-repo
> Error: looks like "oci://private.harbor.com/some-project/helm-test-repo" is not a valid chart repository or cannot be reached: object required
> $ helm repo add helm-test2 https://private.harbor.com/some-project/helm-test-repo
> Error: looks like "https://private.harbor.com/some-project/helm-test-repo" is not a valid chart repository or cannot be reached: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type repo.IndexFile
> $ helm repo add helm-test2 https://private.harbor.com/some-project
> Error: looks like "https://private.harbor.com/some-project" is not a valid chart repository or cannot be reached: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type repo.IndexFile
> ```
> 
> How to `helm repo add` Harbor OCI helm repository?
> 
> It's important to note that docker images are stored alongside pushed helm charts at `private.harbor.com/some-project/`.
> 
> Alternative way that worked is uploading helm chart under `Helm charts` tab in `some-project` in Harbor UI.
> 
> Afterwards, below commands for adding and installing the chart worked:
> 
> ```
> helm repo add helm-test https://private.harbor.com/chartrepo/some-project
> helm repo update helm-test
> helm install chart helm-test/chart --version 1.5.0
> ```
> 
> I would use this method, but have no idea how to push to `https://private.harbor.com/chartrepo/some-project`, pushing to `oci://...` worked only after following [this](https://github.com/goharbor/harbor/issues/13170) github link.
> 
> Below attempts failed:
> 
> ```
> helm push chart-version.tgz oci://private.harbor.com/chartrepo/some-project
> Error: unexpected status: 401 Unauthorized
> helm push chart-version.tgz https://private.harbor.com/chartrepo/some-project
> Error: scheme "https" not supported
> ```
> 
> I'm using latest helm (3.8) and harbor version (2.5)

I was receiving this same error,

To push the chart to harbor you need to sign into the registry first:

%    helm registry login -u username http://private.harbor.com
Login Succeeded
%    helm push chart-version-1.0.0.tgz oci://private.harbor.com/project/
Pushed: private.harbor.com/project/chart-version-1.0.0.tgz
Digest: sha256:23456...

Worked for me
