### ISSUE TITLE
Helm dependencies with multiple namespaces

### ISSUE THREAD

**Issue by robsoned** [helm/helm#10905]
Hello everyone!

Is there any way to deploy the dependencies in different Kubernetes namespaces?

At the moment I'm trying to isolate the subcharts on different namespaces, but I'm not being able to find some solid answer if it is possible, or I would have to make a workaround. Like deploying the charts manually.

Is it there anything that could be done like the example below?

    dependencies:
    - name: first_chart
      version: 1.10.1
      repository: https://firstchart.repo
      namespace: namespace-a
    - name: second_chart
      version: 1.10.2
      repository: https://secondchart.repo
      namespace: namespace-b
  
  
Thanks!

**Comment by yxxhero** [comment]
@robsoned You can deploy as different releases.

**Comment by robsoned** [comment]
@yxxhero You mean do not declare in the chart.yaml and run helm install for each of them?

Like: 
`helm install app1 first_chart -n namespace-a`
`helm install app2 second_chart -n namespace-b`

**Comment by yxxhero** [comment]
@robsoned  yes. you are right.

**Comment by bacongobbler** [comment]
Helm does not provide capabilities to install dependencies in a different namespace. However, there are other tools that use helm to manage chart releases across several namespaces. Helmfile is one example.

Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!
