### ISSUE TITLE
helm lint performance issues mk2

### ISSUE THREAD

**Issue by efiacor** [helm/helm#10908]
Output of `helm version`: v3.6.3

Output of `kubectl version`: v1.22.4

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Minkube

We reported an issue regarding linting of a heavily nested project here - https://github.com/helm/helm/issues/7656
The issue was ultimately related to our (over) use of go templates.
The lint of the umbrella chart is now at ~11 hrs which is killing our CI chain.
Is there ANY way we can improve this?

**Comment by bacongobbler** [comment]
Hi @efiacor. We cannot help you if there is no sample chart to help reproduce the issue... Can you please provide a sample? That way we can begin to determine the root cause.

**Comment by bacongobbler** [comment]
Have you had a chance to read through the suggestions made in https://github.com/helm/helm/issues/7656#issuecomment-620890762? I took a cursory glance at your chart and saw a large number of dependencies relying on the `tpl` function.

As suggested in that comment, none of the maintainers have the time to dive deeper into the performance issues plaguing the `tpl` function, however that is likely the first step I would suggest investigating. Feel free to dive in there. The best place to start is [the `tpl` function in `pkg/engine`](https://github.com/helm/helm/blob/0816322bdff21526388efd8fc697efd5eb982b3d/pkg/engine/engine.go#L127-L152).

**Comment by efiacor** [comment]
Ok. Thanks @bacongobbler . We will take a look
