### ISSUE TITLE
Can we removed the  the indirect dependency on ''github.com/pmezard/go-difflib"

### ISSUE THREAD

**Issue by billrein** [helm/helm#10907]
Output of `helm version`:
helm.sh/helm/v3 v3.8.1-0.20220127200439-4827ca1f1679
Output of `kubectl version`:
 GitVersion:"v1.15.0"
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
OCP

Hi, github.com/pmezard/go-difflib is no longer maintained. But I found that helm/helm has an indirect dependence on it.
Can we removed the  the indirect dependency on ''github.com/pmezard/go-difflib"?
thanks.

**Comment by bacongobbler** [comment]
The indirect dependency likely comes from one of helm’s direct dependencies. So in order to remove go-difflib from helm, you’ll have to remove it from that dependency first.

Do you know what dependency uses go-difflib?

**Comment by billrein** [comment]
it look like that "github.com/stretchr/testify" dependency uses go-difflib

**Comment by bacongobbler** [comment]
Okay. Since there's no action to be taking here, I'm closing this. Please file a ticket with testify to remove go-difflib from their dependency list. Thanks.

**Comment by bacongobbler** [comment]
https://github.com/stretchr/testify/issues/1187
