### ISSUE TITLE
Library Chart Testing

### ISSUE THREAD

**Issue by thepaulmacca** [helm/helm#10911]
More of a question than an issue!

I'm quite new to Helm, and am currently setting up a library chart for a project

I'm using `chart-testing` for linting and that's working great, but the next thing I'd like to look at as part of the CI process is a strategy for testing these templates on something like a Kind cluster, before bumping the version and pushing to an ACR as an OCI artifact

Because these aren't deployable, this is where I'm getting a bit stuck, and I can't see much out there on testing these types of charts

How have others managed this?

Thanks

**Comment by hickeyma** [comment]
What I have found is that people tend to create library charts when they notice duplication in their application charts. Hence when they abstract the common code to a library chart then it is being used in 1 or more application charts and is therefore easier to test as part of their existing setup.

I don't know of any way to test library charts in isolation so to speak. A library chart is only rendered when the application chart that uses it is, and it is this rendered manifests which are deployed to a cluster. 

A good place to ask this would be in the #charts channel in the [Kubernetes slack workspace](https://github.com/helm/helm#community-discussion-contribution-and-support).

**Comment by thepaulmacca** [comment]
Thanks for coming back to me, I'm going down this route to save a lot of duplicated code in the long run. I'll ask the question in Slack and see if anyone comes back on it

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!
