### ISSUE TITLE
Cannot set values to `null` inside `--values`

### ISSUE THREAD

**Issue by nazarewk** [helm/helm#10915]
Might be a duplicate of https://github.com/helm/helm/issues/9136 , but I have observed i'm getting different behaviors depending on whether i use `-f values.yaml` or not.

I've created a gist for minimal reproducible difference: https://gist.github.com/nazarewk/954779d56c97c2ff72b56b78096807e7

I guess the most relevant part is:
```
++ helm template .
+ diff -C5 /dev/fd/63 /dev/fd/62
++ helm template . -f values.yaml
*** /dev/fd/63	2022-04-29 12:23:39.257193677 +0200
--- /dev/fd/62	2022-04-29 12:23:39.257193677 +0200
***************
*** 4,10 ****
  kind: ConfigMap
  metadata:
    name: release-name-parent-test-cm
    annotations:
      values.yaml: |
-       test-value: null
        test-value-2: false
--- 4,9 ----
```

**Comment by nazarewk** [comment]
Note using `--set test-value=null` does not help at all.

**Comment by bacongobbler** [comment]
Here's the code within pkg/strvals:

https://github.com/helm/helm/blob/48fba01cc7bf87b357de8f9bebce5826e8fad16d/pkg/strvals/parser.go#L430-L432
