### ISSUE TITLE
How to tell helm not to manage a resource?

### ISSUE THREAD

**Issue by shibin-george** [helm/helm#10925]
Output of `helm version`: `version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}`

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"b631974d68ac5045e076c86a5c66fba6f128dc72", GitTreeState:"clean", BuildDate:"2022-01-19T17:51:12Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"633e1432a197dc4a6a1807311429a9808b99ff5b", GitTreeState:"clean", BuildDate:"2022-03-30T18:27:54Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  `AKS`

Hi!

My deployment uses a secret that was deployed as part of a helm chart. This is now an issue for me:
The thing is I don't want the secret to be reverted to an unwanted state during `helm upgrade` or `rollback`.
So, I want to instruct helm not to manage that specific kubernetes secret.
https://helm.sh/docs/howto/charts_tips_and_tricks/#tell-helm-not-to-uninstall-a-resource says `this annotation instructs Helm to skip deleting this resource when a helm operation (such as helm uninstall, helm upgrade or helm rollback) would result in its deletion`.
It also says `However, this resource becomes orphaned. Helm will no longer manage it in any way` which implies that helm will avoid any updates to resource during upgrade or rollback but its not explicitly stated in any docs.
Will `"helm.sh/resource-policy": keep` work for my requirement?
To be clear, I don't want to delete the `secret` resource. I want to migrate a resource that is currently managed by helm and move it outside of helm's reach without causing a downtime :)
(the secret holds a password and any updates to during rollback will cause a downtime.)

**Comment by akankshakumari393** [comment]
From what I understood , removing labels from the secret resource should work.
