### ISSUE TITLE
Unable to build via make on for local development

### ISSUE THREAD

**Issue by Aju100** [helm/helm#10936]
I am not able to successfully build the helm repo for local setup and development. Reference from https://helm.sh/docs/community/developers/

Requirements:
Snap has installed from the snap: 

``` sudo snap install helm --classic```

Output of `helm version`: 

```version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

Issue while building it locally
```
clone the repo and cd helm
make
```

Output:
```
[innovate@csaju helm ]$ make
GO111MODULE=on CGO_ENABLED=0 go build  -trimpath -tags '' -ldflags '-w -s -X helm.sh/helm/v3/internal/version.metadata=unreleased -X helm.sh/helm/v3/internal/version.gitCommit=2cd709c4a65beba044ee40062594e66811a8b0ba -X helm.sh/helm/v3/internal/version.gitTreeState=dirty  -X helm.sh/helm/v3/pkg/lint/rules.k8sVersionMajor=1 -X helm.sh/helm/v3/pkg/lint/rules.k8sVersionMinor=24 -X helm.sh/helm/v3/pkg/chartutil.k8sVersionMajor=1 -X helm.sh/helm/v3/pkg/chartutil.k8sVersionMinor=24' -o '/home/innovate/Desktop/opensource/helm/bin'/helm ./cmd/helm
build helm.sh/helm/v3/cmd/helm: cannot load embed: malformed module path "embed": missing dot in first path element
make: *** [Makefile:80: /home/innovate/Desktop/opensource/helm/bin/helm] Error 1
[innovate@csaju helm ]$ 

```

Here is the config of .bashrc
```
export GOPATH=$HOME/go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
```

Since helm has been installed via snap and its the location as ``` helm: /snap/bin/helm ```
Do we need to export and config in bashrc too? Since docs prefer to export helm too? How can I build local helm successfully

**Comment by bacongobbler** [comment]
If you are compiling from main, you need at least Go 1.17: https://github.com/helm/helm/blob/2cd709c4a65beba044ee40062594e66811a8b0ba/go.mod#L3

The `embed` package was introduced in Go 1.16... This sounds like you're trying to compile Helm with an older version of Go.

What version of Go do you have installed?
