### ISSUE TITLE
can dep add a values argument? 

### ISSUE THREAD

**Issue by izouxv** [helm/helm#10938]
# Chart.yaml
dependencies:
- name: nginx
  version: "1.2.3"
  repository: "file://../dependency_chart/nginx"
  
can add a values argument? 
like this 

dependencies:
- name: nginx
  version: "1.2.3"
  repository: "file://../dependency_chart/nginx"
  values: "file://../nginx_values.yaml"

thank you

**Comment by bacongobbler** [comment]
No; see https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#overriding-values-from-a-parent-chart
