### ISSUE TITLE
Helm uninstall is not removing workloads with volumes that uses a CSIDriver

### ISSUE THREAD

**Issue by VitorEstevam** [helm/helm#10949]
I'm using a CSIDriver to manage some volumes in three workloads. When I do a helm uninstall {chart} these three workloads get stuck at Terminating status.  Looking in the k3s logs I saw the following message

`Error: "UnmountVolume.TearDown failed for volume \"spire-agent-socket\" (UniqueName: \"kubernetes.io/csi/80621856-bf9a-4406-be77-06cc31242e87spire-agent-socket\") pod \"80621856-bf9a-4406-be77-06cc31242e87\" (UID: \"80621856-bf9a-4406-be77-06cc31242e87\") : kubernetes.io/csi: mounter.SetUpAt failed to get CSI client: driver name csi.spiffe.io not found in the list of registered CSI drivers"`

This means that the driver is being removed before the workloads and this is breaking the volume TearDown. 

This problem is related at the [driver's documentation](https://github.com/spiffe/spiffe-csi#failure-to-terminate-pods-when-driver-is-unhealthy-or-removed) and the solution is removing the workloads before the driver. 

looking at [helm's uninstall order](https://github.com/helm/helm/blob/2cd709c4a65beba044ee40062594e66811a8b0ba/pkg/releaseutil/kind_sorter.go#L72) I didn't see any reference to CSIDrivers. 

Does anyone know some way to fix this? 

<br/>

Output of `helm version`:

```
version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.5"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5+k3s2", GitCommit:"724ef700bab896ff252a75e2be996d5f4ff1b842", GitTreeState:"clean", BuildDate:"2021-10-05T19:59:14Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5+k3s2", GitCommit:"724ef700bab896ff252a75e2be996d5f4ff1b842", GitTreeState:"clean", BuildDate:"2021-10-05T19:59:14Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
k3s

**Comment by bacongobbler** [comment]
> This means that the driver is being removed before the workloads and this is breaking the volume TearDown.

This is one of the many issues when managing a CRD's lifecycle. See [HIP 11](https://github.com/helm/community/blob/main/hips/hip-0011.md) for more details on this behaviour.
