### ISSUE TITLE
Releases being unlisted

### ISSUE THREAD

**Issue by m42jbz** [helm/helm#10947]
v3.8.2 was available just recently, then got unlisted and v3.8.1 was the latest available. Now, a few hours later, the latest version is v3.6.3 and our Azure pipelines using a HelmInstaller step with version set to "latest" are already failing, because --dependency-update is not supported.

**Comment by hickeyma** [comment]
There is an issue at the moment with the listing of releases. You can access the releases using the URL of the release. For example, https://github.com/helm/helm/releases/tag/v3.8.1, https://github.com/helm/helm/releases/tag/v3.8.2 etc.

**Comment by hickeyma** [comment]
This is currently being investigated.

**Comment by BenWalters** [comment]
Anyone hitting this issue should be able to get around it until it's fixed by unchecking the box shown below
![image](https://user-images.githubusercontent.com/43746367/167721997-22a5c878-b419-42c6-ba94-85f3a7884fc3.png)

**Comment by bacongobbler** [comment]
This is a VERY common misconception about how GitHub refers to the “latest” release.

In GitHub, “latest” refers to the release that was most recently updated. If I were to backport a patch to an older release (say, Helm 3.6) and cut a new release, Helm 3.6.3 would become the “latest”. It DOES NOT mean that Helm 3.6.3 is the latest and most up-to-date TAG of Helm - just that it was the last RELEASE. Savvy?

As a result, the HelmInstaller GitHub action must NOT use the “latest” release page for this very same reason. Instead, they should rely on steps similar to Helm’s own get-helm-3 script:

https://github.com/helm/helm/blob/main/scripts/get-helm-3#L108

Hope this helps.

**Comment by m42jbz** [comment]
@bacongobbler Good point! However, the releases were not even listed in the GitHub response. Today it works fine again.

**Comment by bacongobbler** [comment]
In this case, it appears something is up with GitHub’s release ordering causing some other release to be listed as “latest”. But my earlier point still stands - referring to the “latest” tag as the most up-to-date version is a big misstep.

**Comment by bacongobbler** [comment]
Closing as resolved.

**Comment by bacongobbler** [comment]
Quick note: it appears HelmInstaller is doing the right thing now. They scour the releases page and sort versions semantically. Wasn’t always the behaviour in the past, but glad they fixed that. :)

The action failed because the releases page was somehow corrupted - not much we can do to help there. Other repositories were listing similar issues:  https://github.com/Genymobile/scrcpy/issues/3253

Glad it’s been fixed and order has been restored
