### ISSUE TITLE
Helm hook - Job status - timeoutSeconds too high

### ISSUE THREAD

**Issue by waewoo** [helm/helm#10942]
Output of helm version:
> version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.17.5"}

Output of kubectl version:
> Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.15+IKS", GitCommit:"bef807c747db0037aebbcbebd12699950a06d1a2", GitTreeState:"clean", BuildDate:"2022-01-20T14:23:00Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):
> IBMCloud Kubernetes (IKS)

hello,

When I use a helm hook (pre-install or post-install) specifying for example an optional wait with timeout of 600s... I noticed that the command to retrieve the status of my job indicated a timeout parameter (**timeoutSeconds**) that seemed "random":
`c0509 13:13:41.985950 2943713 round_trippers.go:466] curl -v -XGET  -H "Accept: application/json" 'https://XXXXXXXXXXXX/apis/batch/v1/namespaces/mynamespace/jobs?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dkafka-connect-dev-1&resourceVersion=69903348&timeoutSeconds=423&watch=true'`

423 secondes in this example.

In this case, even if my deployment is done in 100 seconds and I put a **timeout** of **130** seconds for example .... in the end my deployment is indicated as failed because the command curl to recover job status takes **423** seconds before hand over.

I am therefore obliged to set a timeout greater than 423 seconds for my deployment to end in success. Knowing that the value of timeoutSeconds varies, I have to put a very large timeout to cover the value defined in this variable timeoutSeconds.

Do you know how this timeoutSeconds value is defined? and especially how it would be possible to reduce it?

` helm install kafka-connect-dev-1 ./kafka-connect --wait --timeout 30s  --debug -v 9`

```
apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-connect-dev-1
  annotations:
    helm.sh/hook: pre-install
  labels:
    app: kafka-connect
    release: kafka-connect-dev-1
    helm.sh/chart: kafka-connect-1.0.0
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/name: kafka-connect
    app.kubernetes.io/instance: kafka-connect-dev-1
    app.kubernetes.io/component: kafka-connect
    app.kubernetes.io/managed-by: Helm
spec:
  template:
    metadata:
      name: kafka-connect-dev-1
      labels:
        app: kafka-connect
        release: kafka-connect-dev-1
        helm.sh/chart: kafka-connect-1.0.0
        app.kubernetes.io/version: "3.1.0"
        app.kubernetes.io/name: kafka-connect
        app.kubernetes.io/instance: kafka-connect-dev-1
        app.kubernetes.io/component: kafka-connect
        app.kubernetes.io/managed-by: Helm
    spec:
      imagePullSecrets:
        - name: my-secret-reg
      restartPolicy: Never
      containers:
      - name: kafka-connect-post-install
        image: "private.fr2.icr.io/myregistry/kafka-connect-splunk:2.0.7-3.1.0"
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash"]

```

Extract of helm command in debug mode showing curl call to get job status 
```
I0509 13:13:41.985950 2943713 round_trippers.go:466] curl -v -XGET  -H "Accept: application/json" 'https://XXXXXXXXXXXX/apis/batch/v1/namespaces/mynamespace/jobs?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dkafka-connect-dev-1&resourceVersion=69903348&timeoutSeconds=423&watch=true'
client.go:557: [debug] Add/Modify event for kafka-connect-dev-1: ADDED
client.go:596: [debug] kafka-connect-dev-1: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
I0509 13:13:41.992798 2943713 round_trippers.go:570] HTTP Statistics: GetConnection 0 ms ServerProcessing 6 ms Duration 6 ms
I0509 13:13:41.992814 2943713 round_trippers.go:577] Response Headers:
I0509 13:13:41.992820 2943713 round_trippers.go:580]     Strict-Transport-Security: max-age=15552000; includeSubDomains
I0509 13:13:41.992825 2943713 round_trippers.go:580]     Vary: Accept-Encoding
I0509 13:13:41.992828 2943713 round_trippers.go:580]     Date: Mon, 09 May 2022 11:13:41 GMT
I0509 13:13:41.992832 2943713 round_trippers.go:580]     X-Content-Type-Options: nosniff
I0509 13:13:41.992842 2943713 round_trippers.go:580]     Set-Cookie: BIGipServer~IKSxXXX~IKSxXXXXXXXXXXXX~P_XXXXXXXXXXXX=121768358.25467.0000; path=/; Httponly; Secure
I0509 13:13:41.992847 2943713 round_trippers.go:580]     X-Xss-Protection: 1; mode=block
I0509 13:13:41.992851 2943713 round_trippers.go:580]     X-Frame-Options: SAMEORIGIN
I0509 13:13:41.992855 2943713 round_trippers.go:580]     X-Content-Security-Policy: default-src 'self'
I0509 13:13:41.992859 2943713 round_trippers.go:580]     Cache-Control: no-cache, private
I0509 13:13:41.992863 2943713 round_trippers.go:580]     Content-Type: application/json
```

**Comment by bacongobbler** [comment]
Hi @waewoo. We ask that users please provide a simple sample chart to help reproduce their issue. The output from `helm create` is a good starting point. Once you can reproduce the issue, that will help the community identify potential fixes and help serve as a test case preventing future code regressions.

I cannot tell what might be the cause of the issue based on the information provided here. Please provide a sample chart and a set of instructions for testing. Optimally, the chart should not involve a complex set of instructions to install, and should be pretty easy to install on a local development cluster such as minikube.

Thanks.
