### ISSUE TITLE
SDK release 3.8.3

### ISSUE THREAD

**Issue by Segflow** [helm/helm#10943]
This commit https://github.com/helm/helm/commit/bd7c97f786f59b993dc34884f3d44ca0297f13e8 broke helm v3.8.2. 

Can we tag master with v3.8.3 so we can use it?

**Comment by bacongobbler** [comment]
Can you please explain how that commit "broke" Helm v3.8.2?

**Comment by Segflow** [comment]
```
go/pkg/mod/helm.sh/helm/v3@v3.8.2/pkg/kube/client.go:92:12: cannot use cmdutil.NewFactory(getter) (value of type "k8s.io/kubectl/pkg/cmd/util".Factory) as type Factory in struct literal:
        "k8s.io/kubectl/pkg/cmd/util".Factory does not implement Factory (wrong type for Validator method)
                have Validator(validationDirective string, verifier *"k8s.io/cli-runtime/pkg/resource".QueryParamVerifier) (validation.Schema, error)
                want Validator(validate bool) (validation.Schema, error)
```

In 3.8.2 the helm kube client is defined like this:
```
// Client represents a client capable of communicating with the Kubernetes API.
type Client struct {
	Factory Factory
	Log     func(string, ...interface{})
	// Namespace allows to bypass the kubeconfig file for the choice of the namespace
	Namespace string

	kubeClient *kubernetes.Clientset
}

...
type Factory interface {
	// ToRawKubeConfigLoader return kubeconfig loader as-is
	ToRawKubeConfigLoader() clientcmd.ClientConfig
	// KubernetesClientSet gives you back an external clientset
	KubernetesClientSet() (*kubernetes.Clientset, error)
	// NewBuilder returns an object that assists in loading objects from both disk and the server
	// and which implements the common patterns for CLI interactions with generic resources.
	NewBuilder() *resource.Builder
	// Returns a schema that can validate objects stored on disk.
	Validator(validate bool) (validation.Schema, error)
}

```

So factory is using the old interface, this makes us no able to use 3.8.2 with k8s sdk 2.24.

**Comment by bacongobbler** [comment]
The justification behind this change was mentioned in the review. Please see https://github.com/helm/helm/pull/10928#pullrequestreview-963693316 for more details.

**Comment by bacongobbler** [comment]
cc @mattfarina

**Comment by mattfarina** [comment]
@Segflow An understanding of how Helm handles releases may help in explaining why what you're asking for is difficult.

Helm follows semantic versioning. That means feature additions go in at minor versions and bug fixes go in at patch versions. Helm 3.8.3, being a patch release, must only have bug fixes. The main (default) branch has new features in it. We would be breaking that contract if we tagged main at 3.8.3.

On Helm we have release branches. Right before we start a new minor release a release branch is created. Bug fixes are cherry picked to the release branch and we patch releases come from the release branches.

I don't see how we can do a 3.8.3 release from main without breaking from semantic versioning.

I understand the inconvenience here. Kubernetes changed an API in a breaking way. We try to shield from that and sometimes can. But, in this instance we were not able to.

**Comment by Segflow** [comment]
Can we do 3.9?

**Comment by bacongobbler** [comment]
Yes. Helm 3.9 is scheduled for May 18th, which is next Wednesday.

**Comment by mattfarina** [comment]
I am in the process of doing a release candidate for Helm 3.9. The release candidate will be available today.

**Comment by bacongobbler** [comment]
https://github.com/helm/helm/releases/tag/v3.9.0-rc.1

Closing as there’s no further action to take here. Helm 3.9.0 will be released as scheduled next week. Thanks!
