### ISSUE TITLE
helm releases 3.7.x and 3.8.x are gone from the github release page

### ISSUE THREAD

**Issue by KaiOdenthal** [helm/helm#10948]
Hi,

As of today the releases 3.7.x and 3.8.x are gone from the github releases page and 3.6.3 is listed as latest again.
Can you please check the release management and correct this?
Currently external tools like the Helm ask for azure devops dont pull any newer versions than 3.6.3 which breaks all build with the new helm push command and oci integration. Helm installer does installs 3.6.3 even with 3.8.1 hardcoded
Thanks and Best Regards,
Kai

**Comment by hickeyma** [comment]
Closing as duplicate
