### ISSUE TITLE
EOL policy

### ISSUE THREAD

**Issue by pravorskyi** [helm/helm#10954]
Hi! Is there any information about what are the oldest supported versions of Helm that may receive bug fixes and security updates?

I have read "Helm Version Support Policy" and "Release schedule policy", but I didn't find any information there about when support for released versions of Helm ends.

For example, there is a 3.8.x release. When does it become unsupported by the Helm team?

Thank you.

**Comment by bacongobbler** [comment]
As soon as the next minor release is out (3.9.x), Helm 3.8 will only receive critical security patches as needed. No further patch releases are provided. That is to say, if Helm 3.9.0 is released and you find a bug, it will become available in Helm 3.9.1. No backports will be provided for Helm 3.8.

Hope that helps answer your question.

**Comment by bacongobbler** [comment]
See also

- https://github.com/helm/community/blob/main/SECURITY.md
- https://github.com/helm/community/blob/main/hips/hip-0002.md#cancelling-a-patch-release

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!
