### ISSUE TITLE
Helm push fails with: Error: scheme "https" not supported

### ISSUE THREAD

**Issue by shivanshi18** [helm/helm#10957]
Output of `helm version`: 3.8

I did login into the registry using: 
    USER_NAME="00000000-0000-0000-0000-000000000000"
    PASSWORD=$(az acr login --name $(registryName) --expose-token --output tsv --query accessToken)
    helm registry login $(registryName).azurecr.io  --username $USER_NAME  --password $PASSWORD 
    
    Helm login succeeds. 

I am trying to do a helm push using helm3 command: helm push $(build.artifactStagingDirectory)/$chart-${{ parameters.RELEASE_TAG }}.tgz  https://$registryname.azurecr.io/bonsai/$chart

It fails at this step within ADO. gives the error : 

    Error: scheme "https" not supported

**Comment by bacongobbler** [comment]
As suggested, the scheme “https” is incorrect. The correct scheme is “oci”. 

Refer to https://helm.sh/docs/topics/registries/#the-push-subcommand for more information. Thanks.

**Comment by ben-xD** [comment]
I am a bit confused on the difference between that doc @bacongobbler linked (https://helm.sh/docs/topics/registries/#the-push-subcommand ) and https://helm.sh/docs/helm/helm_push/

From reading elsewhere, should I assume `https` support was dropped?

Thanks

**Comment by reitzig** [comment]
Took some digging, but apparently, yeah: [helm/helm:pkg/pusher/pusher.go#112](https://github.com/helm/helm/blob/main/pkg/pusher/pusher.go#L112)

Which is confusing, even in the sources: I reached that one from a branch _specifically_ handling the case "not oci": [helm/helm:pkg/action/push.go#102](https://github.com/helm/helm/blob/main/pkg/action/push.go#L102)
