### ISSUE TITLE
Helm incorrectly parses multiline yaml

### ISSUE THREAD

**Issue by vladimirtiukhtin** [helm/helm#10952]
Output of `helm version`:
3.5.4

Everything work fine using |, but if I put > instead, helm preserves line breaks. That is visible either after deployment or by doing `helm template -o json`

**Comment by bacongobbler** [comment]
The yaml library Helm uses is likely the one to blame here. Have you tested this in isolation against `sigs.k8s.io/yaml`?

https://github.com/kubernetes-sigs/yaml

**Comment by edwbuck** [comment]
It is unlikely that the mulitline is failing at the parsing of the values.yaml.  I am currently passing a mulit-line value from values.yaml, encoded as so:

```
configMap:
  product:
    cert: |
      -----BEGIN CERTIFICATE-----
      asdfasdfasdfasdfasdfasdfasdfasdf
      ... a bunch of lines of text....
      asdfasdfasdfasdfasdf=
      -----END CERTIFICATE-----
    next_item: 3
```

Which correctly is passed to the template, as seen through

```
apiVersion: v1
... a bunch of lines ...
data:
  ca_cert: 
{{ .Values.confiMap.product.cert | indent 4 }}
```

By altering the value 4 in the clause ` | indent 4 `  one can make the indentation correct for your specific YAML needs.

However, there is a problem at the templating level.  I need to inject a "pipe" character and a newline to have the first line of the passed value fall below the YAML label, as it currently formats to

```
    data:
       ca_cert:       
          ----BEGIN CERTIFICATE-----
          asdfasdfasdfasdfasdf
          ... and so on....

```
Putting the pipe in the text of the template

```
     ca_cert: | 
{{ .Values.... }}
```

crashes the helm chart functions.  While

```
     ca_cert:
{{ .Values.... }}
```

renders, but without the required "|" that will tell Kubernetes to expect a multi-line value.

Note that ">" works, but any variation of "|" does not ("|+" and "|-" also fail).  I'm still looking at the issue directly, but this should assist you in your efforts.

To render the templates, so I can see the formatting after rendering, I am using

`helm install --dryrun foo .`

The name "foo" was selected primarily to avoid naming conflicts with other deployed templates.

**Comment by edwbuck** [comment]
Ok, the final answer lies in using (within the template) the command "toYaml"

This will inspect the multiline value, and add the necessary "|\n" to put the value under a mulit-line YAML directive.

The final template text should look like

   multiline_property: {{ toYaml .Values.path.to.item | indent 4 }}

or some other indentation level that places the value clearly under the indentation of the multiline_property value.
