### ISSUE TITLE
Error: manifest does not contain minimum number of descriptors (2), descriptors found: 1

### ISSUE THREAD

**Issue by shivanshi18** [helm/helm#10968]
What are the causes for this error?  The charts are being built with helm = 3.8 but still I see this error on  Helm upgrade.

**Comment by bacongobbler** [comment]
Can you share your template?

**Comment by shivanshi18** [comment]
parameters:
  DEPLOY_SP: ''
  DEPLOY_PASSWORD: ''
  DEPLOY_TENANT_ID: ''
  AKS_CLUSTER_NAME: ''
  AKS_RESOURCE_GROUP: ''
  REGISTRY_SERVER_NAME: ''
  REGISTRY_LOGIN: ''
  REGISTRY_PASSWORD: ''
  RELEASE_TAG: ''
  HELM_PUSH_TIMEOUT_SECONDS: '45'

steps:
- bash: |
    az login --identity
    az aks get-credentials \
        -n ${{ parameters.AKS_CLUSTER_NAME }} \
        -g ${{ parameters.AKS_RESOURCE_GROUP }} \
        --overwrite-existing
      echo "************ HELM PACKAGING ********"
      for package_name in $(system.defaultWorkingDirectory)/src/Services/Auth/Auth/charts/auth $(system.defaultWorkingDirectory)/src/inkling/compiler-service/charts/compiler $(system.defaultWorkingDirectory)/src/backend/converter/charts/converter $(system.defaultWorkingDirectory)/src/Services/ControlPlane/ControlPlane/charts/controlplane $(system.defaultWorkingDirectory)/src/Services/DataManagement/DataManagement/charts/datamanagement $(system.defaultWorkingDirectory)/src/Services/DataService/charts/dataservice $(system.defaultWorkingDirectory)/src/Services/Orchestration/charts/orchestrationengine $(system.defaultWorkingDirectory)/src/Services/TickTock/charts/ticktock $(system.defaultWorkingDirectory)/src/Services/OfflineCleanup/charts/offlinecleanup $(system.defaultWorkingDirectory)/src/Services/BillingJob/charts/billingjob $(system.defaultWorkingDirectory)/src/Services/InklingLighthouseJob/charts/inklinglighthousejob $(system.defaultWorkingDirectory)/src/Services/Prober/Prober/charts/prober $(system.defaultWorkingDirectory)/src/Services/GenericWorkflowService/GenericWorkflowService/charts/genericworkflowservice $(system.defaultWorkingDirectory)/src/Services/SimControl/SimControl/charts/simcontrol $(system.defaultWorkingDirectory)/src/Services/SimulatorGateway/SimulatorGateway/charts/simulatorgateway $(system.defaultWorkingDirectory)/src/Services/ManagedSimService/ManagedSimService/charts/managedsimservice  $(system.defaultWorkingDirectory)/src/Services/WatsonagentVerifier/WatsonagentVerifier/charts $(system.defaultWorkingDirectory)/infrastructure/kube/external_charts/consul-inject; do
        helm package --version ${{ parameters.RELEASE_TAG }} --destination $(build.artifactStagingDirectory) $package_name
      done
  continueOnError: false
  displayName: 'helm package auth, compiler, converter, controlplane, datamanagement, dataservice(DAS), orchestrationengine, ticktock, offlinecleanup, billingjob, inklinglighthousejob, prober, genericworkflowservice, simcontrol, simulatorgateway, managedsimservice, watsonagentverifier, consul-inject'

- bash: |
    timeout=${{ parameters.HELM_PUSH_TIMEOUT_SECONDS }}

    #
    # How does this helm registry login work - 
    # 1. We provided Contributor Role to VMSS Managed Identity (this step is done in azure portal)
    # 2. We then login using MSI of the VMSS (az login --identity)
    # 3. We then login into the helm registry using a password and a username. 
    #    Here we get password using az acr login as we already have provided contributor role to VMSS MSI
    # Used guidelines from : https://docs.microsoft.com/en-us/azure/container-registry/container-registry-helm-repos#authenticate-with-the-registry
    #

    USER_NAME="00000000-0000-0000-0000-000000000000"
    PASSWORD=$(az acr login --name $(registryName) --expose-token --output tsv --query accessToken)
    helm registry login $(registryName).azurecr.io  --username $USER_NAME  --password $PASSWORD
    echo "Helm registry login done"
    echo "************ PUSHING HELM PACKAGES INTO ACR REPO ********"
    for chart in auth compiler converter controlplane datamanagement dataservice orchestrationengine ticktock offlinecleanup billingjob inklinglighthousejob prober genericworkflowservice simcontrol simulatorgateway managedsimservice watsonagentverifier consul-inject; do
      retries=8
      pushExitCode=''
      echo "************ PUSHING HELM PACKAGE ${chart}-${{ parameters.RELEASE_TAG }}.tgz INTO REPO ********"
      while [ $retries -gt 0 ]; do
        # timeout function exits with code 124 when inside command 'helm push' times out
        echo "Starting helm push for ${chart}"
        timeout $timeout helm push $(build.artifactStagingDirectory)/$chart-${{ parameters.RELEASE_TAG }}.tgz  oci://$(registryName).azurecr.io/bonsai
        pushExitCode=$?
        retries=$((retries-1))
        if test $pushExitCode -ne 0; then
          # Something went wrong during helm push command, potentially it timed out.
          if test $pushExitCode -eq 124; then
            echo "************ HELM PUSH TIMED OUT AFTER ${timeout}s ... ********"
          fi

          # Sleep to give it time to populate then check if helm package still got pushed successfully.
          # Scenario could be that on first try helm push timed out due to known bug in Azure CLI or that the package already exists due to a previous successful run.
          sleep 3
          helm show chart $chart --version ${{ parameters.RELEASE_TAG }}
          showExitCode=$?
          if test $showExitCode -eq 0; then
            # This means helm push actually succeeded earlier, despite Azure CLI not behaving as expected.
            echo "************ HELM PUSH SUCCEEDED, DESPITE AZURE CLI CLIENT TIMING OUT OR REPORTING ERROR. MOVING TO NEXT PACKAGE... ********"
            break
          fi

          if [ $retries -eq 0 ]; then
            echo "************ HELM PUSH FAILED FOR PACKAGE ${chart}-${{ parameters.RELEASE_TAG }}.tgz WITH EXIT CODE ${pushExitCode}. NO MORE RETRIES... ********"
            exit $pushExitCode
          else
            # Package did not get pushed which means helm push failed. Retry
            echo "************ HELM PUSH FAILED WITH EXIT CODE ${pushExitCode}, RETRYING ${retries} MORE TIMES... ********"
          fi
        else
          # Helm push succeeded
          break
        fi
      done
      echo "************ COMPLETED PUSHING HELM PACKAGE ${chart}-${{ parameters.RELEASE_TAG }}.tgz INTO REPO ********"
    done
  continueOnError: false
  displayName: 'az acr helm push auth, compiler, converter, controlplane, datamanagement, dataservice(DAS), orchestrationengine, ticktock, offlinecleanup, billingjob, inklinglighthousejob, prober, genericworkflowservice, simcontrol, simulatorgateway, managedsimservice, watsonagentverifier, consul-inject'

**Comment by shivanshi18** [comment]
Error I get:


	helm.sh/helm/v3/pkg/getter/ocigetter.go:53
helm.sh/helm/v3/pkg/getter.(*OCIGetter).Get
	helm.sh/helm/v3/pkg/getter/ocigetter.go:36
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo
	helm.sh/helm/v3/pkg/downloader/chart_downloader.go:100
helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart
	helm.sh/helm/v3/pkg/action/install.go:753
main.newUpgradeCmd.func2
	helm.sh/helm/v3/cmd/helm/upgrade.go:135
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.3.0/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.3.0/command.go:974
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.3.0/command.go:902
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
	runtime/proc.go:255
runtime.goexit
	runtime/asm_amd64.s:1581
************ HELM UPGRADE FAILED WITH EXIT CODE 1, RETRYING 3 MORE TIMES... ********
history.go:56: [debug] getting history for release auth
Error: manifest does not contain minimum number of descriptors (2), descriptors found: 1
helm.go:84: [debug] manifest does not contain minimum number of descriptors (2), descripto

**Comment by kfirfer** [comment]
Im getting this error while I trying to helm pull from dockerhub when I put ~ as a version:
~5.0.0-helm

**Comment by bennypea** [comment]
I found that this error occurs when I have not authenticated to the helm repository I have pushed my chart to. Once I authenticate, push my chart, then the error is gone when using the chart.

**Comment by sabre1041** [comment]
> I found that this error occurs when I have not authenticated to the helm repository I have pushed my chart to. Once I authenticate, push my chart, then the error is gone when using the chart. For some reason I dont get a 403, just this particular error on using the chart.

Would you be able to provide more context into the issues that you experienced?

**Comment by bennypea** [comment]
I am using an artifactory repo. This error occurs when pushing as anon
