### ISSUE TITLE
Better error message for `helm status` output when release not found

### ISSUE THREAD

**Issue by ChanderG** [helm/helm#10967]
Faced this when trying to install `consul`, but this should occur with any chart.

The command to install the chart include a different namespace, like so:
```
helm install -f ./config.yaml consul hashicorp/consul --create-namespace -n consul
```
which seems to work fine.

As a newcomer to helm, I run the following command:
```
helm status consul
```

which returns a short cryptic message:
```
Error: release: not found
```

It took me a while to figure out that I needed to include namespace in the `status` command. So, the following works:
```
helm status -n consul consul
```

It would nice to have friendlier error messages. At the very least, it will be useful to mention the release name in the error message, so that it doesn't feel like something has failed to load. Something like this would be nice:
```
Error: release '<release name>' not found in namespace '<namespace>'
Check if you have typos in the release name, or that the release exists in the right namespace.
```

Output of `helm version`:
```
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}
```
I have also tried on the latest release:
```
version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.17.5"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.0-2+59bbb3530b6769", GitCommit:"59bbb3530b6769e4935a05ac0e13c9910c79253e", GitTreeState:"clean", BuildDate:"2022-05-13T06:43:45Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.0-2+59bbb3530b6769", GitCommit:"59bbb3530b6769e4935a05ac0e13c9910c79253e", GitTreeState:"clean", BuildDate:"2022-05-13T06:41:13Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
microk8s

**Comment by hickeyma** [comment]
@ChanderG Thanks for raising this issue. Would you be willing to push a PR to improve the error message?

**Comment by ChanderG** [comment]
Sure - I can take a stab.

**Comment by kitarp29** [comment]
Hi @hickeyma  I would like to work on it too.
Could you help me to get started with this?

**Comment by hickeyma** [comment]
@kitarp29 I think @ChanderG I working on it already.

**Comment by cleverhu** [comment]
I'd like to work on it.
