### ISSUE TITLE
Request help: how to use `randAlphaNum` method in two subcharts

### ISSUE THREAD

**Issue by mangoGoForward** [helm/helm#10969]
Output of `helm version`: 
```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

I want to define a variable in `_helper` template which use `randAlphaNum` method to create, but when I `include` it twice in one template, I got different value, how can I get same value in twice `include`, and how can I use it in other subcharts?

Thanks!!!

**Comment by joejulian** [comment]
I don't know if this would work, but what if you tested .Values.myrandom and returned it if it's set. If it's not, set it and return it.

The following is untested and just a theory:
```
{{ if hasKey .Values.myrandom }}
{{ .Values.myrandom }}
{{ else }}
{{ $myrandom := randAlphaNum 24 }}
{{ $_ = set .Values "myrandom" $myrandom }}
{{ $myrandom }}
{{ end }}
```

**Comment by mangoGoForward** [comment]
> I don't know if this would work, but what if you tested .Values.myrandom and returned it if it's set. If it's not, set it and return it.
> 
> The following is untested and just a theory:
> 
> ```
> {{ if hasKey .Values.myrandom }}
> {{ .Values.myrandom }}
> {{ else }}
> {{ $myrandom := randAlphaNum 24 }}
> {{ $_ = set .Values "myrandom" $myrandom }}
> {{ $myrandom }}
> {{ end }}
> ```

Thanks, it works to me.
