### ISSUE TITLE
Errors retrieving dependencies from Library Chart - ACR

### ISSUE THREAD

**Issue by thepaulmacca** [helm/helm#10970]
Output of `helm version`:

```bash
version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.5"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): ACR

This is a bit of a continuation of #10624, but it's been stale for a while and thought it'd be best to create a new issue for my specific case.

I've created a Library Chart that's hosted in an Azure Container Registry as an OCI artifact, and I'm getting errors when running `helm dependency update` in my pipeline (Azure Pipelines).

The dependencies for my application chart are currently set to this:

```yaml
dependencies:
- name: chart-library
  version: ~0.1.0
  repository: oci://<redacted>.azurecr.io/helm
```

The latest version of the library chart is `0.1.3` and I'm getting this error:

```bash
Error: could not retrieve list of tags for repository oci://<redacted>.azurecr.io/helm: GET "https://<redacted>.azurecr.io/v2/helm/chart-library/tags/list": GET "https://<redacted>.azurecr.io/oauth2/token?scope=repository%3Ahelm%2Fchart-library%3Ametadata_read%2Cpull&service=<redacted>.azurecr.io": unexpected status code 401: unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information.
```

The service principal has been assigned the `AcrPull` RBAC role, on the ACR hosting the library chart.

I'm assuming this is due to me specifying a range for the version above. Is using a range possible, or do we have to use a specific version?

If I use a specific version:

```yaml
dependencies:
- name: chart-library
  version: 0.1.3
  repository: oci://<redacted>.azurecr.io/helm
```

I'm getting this error:

```bash
Saving 1 charts
Downloading chart-library from repo oci://<redacted>.azurecr.io/helm
Save error occurred:  could not download oci://<redacted>.azurecr.io/helm/chart-library: failed to authorize: failed to fetch anonymous token: unexpected status: 401 Unauthorized
Error: could not download oci://<redacted>.azurecr.io/helm/chart-library: failed to authorize: failed to fetch anonymous token: unexpected status: 401 Unauthorized
```

Is there something I'm doing wrong, or is it a permissions issue?

This works locally using my login, but not with the service principal in the pipeline. Looking at the docs, the `AcrPull` permissions should be sufficient

Any help/pointers would be much appreciated, as it's blocking my testing currently

Thanks

**Comment by vaibhavramdasi** [comment]
I'm getting exact same error with version 3.9. Any idea what is the fix?
