### ISSUE TITLE
Fail to Helm Install with Namespace defined in Chart

### ISSUE THREAD

**Issue by xfzhang1974** [helm/helm#10976]
My local helm version 3.8.2, and I have a namespace defined with customized labels in the current folder.
helm will not create namespace with or without --create-namespace option, which seems dumb.

$helm install kserve . --namespace kserve
Error: INSTALLATION FAILED: create: failed to create: namespaces "kserve" not found
$helm install --create-namespace kserve . --namespace kserve
Error: INSTALLATION FAILED: no Namespace with the name "kserve" found

**Comment by yxxhero** [comment]
Please check your k8s permissions. @xfzhang1974 Thanks very much.
