### ISSUE TITLE
Helm upgrade fails with Error: failed to authorize: failed to fetch oauth token: unexpected status: 401 Unauthorized

### ISSUE THREAD

**Issue by shivanshi18** [helm/helm#10977]
Helm upgrade has started failing suddenly with failed to authorize
Running ADO pipeline on VMSS and az login --identity

It was working perfectly fine earlier, there was a sudden break at this step

Template: 

    az login --identity
    kubectl config set-context --current --namespace=$(aksClusterNamespace)

    for chart in auth  ; do
      echo "**************UPGRADING $chart*************************************"

      retries=4
      timeout=5m0s

      while [ $retries -gt 0 ]; do

        helm upgrade -f $(system.defaultWorkingDirectory)/infrastructure/kube/env_configs/$(envConfigFile) $chart oci://$(registryName).azurecr.io/bonsai/$chart/$chart --version ${{ parameters.RELEASE_TAG }} --namespace $(aksClusterNamespace) --set image.repository=$(registryName).azurecr.io/bonsai/$chart --set image.tag=${{ parameters.RELEASE_TAG }} --install  --atomic --cleanup-on-fail --wait --debug --timeout $timeout

        helmUpgradeExitCode=$?
        retries=$((retries-1))
        if test $helmUpgradeExitCode -ne 0; then
          # Something went wrong during helm upgrade command, potentially it timed out.
          if [ $retries -eq 0 ]; then
              echo "************ HELM UPGRADE FAILED FOR PACKAGE $chart WITH EXIT CODE ${helmUpgradeExitCode}. NO MORE RETRIES... ********"
              exit $helmUpgradeExitCode
          else
            # Helm Upgrade was not successful. Retry
            echo "************ HELM UPGRADE FAILED WITH EXIT CODE ${helmUpgradeExitCode}, RETRYING ${retries} MORE TIMES... ********"
          fi
        else
          # Helm Upgrade succeeded
          break
        fi

Error:

**************UPGRADING auth*************************************
history.go:56: [debug] getting history for release auth
Error: failed to authorize: failed to fetch oauth token: unexpected status: 401 Unauthorized

**Comment by bacongobbler** [comment]
What version of Helm are you using?

**Comment by bacongobbler** [comment]
https://github.com/helm/helm/issues/10624

**Comment by gouthamMN** [comment]
I still face this issue? Was there any solution?
