### ISSUE TITLE
Truncation in _helpers.tpl considered dangerous

### ISSUE THREAD

**Issue by jdemeyer** [helm/helm#10973]
The default `_helpers.tpl` (generated by `helm create`) has code like
```
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
```

This is actually dangerous as the truncation could cause name collisions with 2 different release names mapping to the same `fullname` (collisions are likely if you use a naming scheme where 2 release names differ only in a suffix).

I'd much rather have Kubernetes throwing an error at me because the name is too long, rather than silently breaking existing deployments. So I suggest to simply remove the `trunc 63`.

**Comment by hickeyma** [comment]
@jdemeyer If you are interested, please push a PR
