### ISSUE TITLE
Helm upgrade remove resource which has changed its releaseName

### ISSUE THREAD

**Issue by bai3shuo4** [helm/helm#10983]
Output of `helm version`:
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.18-174+430dc8561c449d-dirty", GitCommit:"430dc8561c449d229a50945e7676ad629bad004f", GitTreeState:"dirty", BuildDate:"2022-01-11T09:19:02Z", GoVersion:"go1.15.11", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.18-233+d3cc2498e44fe1-dirty", GitCommit:"d3cc2498e44fe1b2c8960dee0f2d314d19509eda", GitTreeState:"dirty", BuildDate:"2022-05-20T08:18:08Z", GoVersion:"go1.15.11", Compiler:"gc", Platform:"linux/arm64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

In my case, I need to remove a resource(statefulset-xx) in release A to release B. Release A has deployed in cluster. I follow the next steps:
1. annotate statefulset-xx releaseName to release B
2. move statefulset-xx from A chart template to B chart template
3. helm upgrade release A
When I do this, **I will find that statefulset-xx has been deleted!** I think it should not happen because its releaseName has changed to B and it should be managed by B. I read the code and find the problem
https://github.com/helm/helm/blob/823d92942119dfa07fd763bf6306bd67686811a8/pkg/kube/client.go#L277-L297

In this upgrade function, it will make difference with target and original release. It will delete resource without check its releaseName.  Pre-ownershipcheck will not do this because statefulset-xx is not in release A chart any more!

**Comment by luisdavim** [comment]
You can try adding the following annotation to the resource to prevent it's deletion:

```
helm.sh/resource-policy: keep
```

**Comment by bacongobbler** [comment]
Yep. This is expected behaviour. You "removed" a resource from the chart by changing its name to something else. @luisdavim's suggestion is the documented approach to keeping resources around during an upgrade.

Closing as intentional behaviour.

**Comment by bacongobbler** [comment]
For reference: https://helm.sh/docs/howto/charts_tips_and_tricks/#tell-helm-not-to-uninstall-a-resource
