### ISSUE TITLE
Diff between values.yaml and deployed manifest

### ISSUE THREAD

**Issue by emahdij** [helm/helm#10982]
Hi
I need to know the difference between values.yaml file that I will upgrade and existing values that's deployed.
is there any way to find diff that?

**Comment by hickeyma** [comment]
@emahdij The `helm get values` command will return the values for the deployed release. You could then do a diff from there.

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!
