### ISSUE TITLE
Update go version from 1.17 to 1.18

### ISSUE THREAD

**Issue by jinwoov** [helm/helm#10985]
Output of `helm version`: 3.9.0

Output of `kubectl version`:  1.24.0

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Prisma

The recent scan on our Twistlock shows that GO version 1.17 has vulnerabilities. The latest scan from Helm package 3.9.0 shows, it is using 1.17 Go version. I was wondering if its possible to bump up Go in Helm to use 1.18 instead. Thank you

**Comment by bacongobbler** [comment]
Please see https://github.com/helm/helm/pull/10806. Thanks.
