### ISSUE TITLE
Is there any method to override subchart value conditionally?

### ISSUE THREAD

**Issue by jixinchi** [helm/helm#10989]
Assuming that I have a chart A with a subchart B.

In chart A, there is a `xxxEnable` variable. In chart B, there is a `podAnnotations` variable.
What I want to achieve is that, if `xxxEnable` is true in chart A, set `podAnnotations` as `xxx: yyy` in chart B.

I don't want to change anything in chart B, because chart B may be used in various scenarios, and `podAnnotations` is a general variable.

Thanks!

**Comment by genofire** [comment]
Sound like templating of dependence charts would solve it #2133 or #10992

**Comment by meyerkev** [comment]
+1

I have a lot of sub-charts that are being deployed with values-<X>.yaml that are mostly setting up 10 values that depend on certain conditions.  

Being able to set cluster_name and account_id to generate EKS Role ARN would be incredibly useful.

**Comment by bacongobbler** [comment]
https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#helm

**Comment by bacongobbler** [comment]
Parents can override values of a child chart. Please see the document above and let me know if you have further questions.

https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#overriding-values-from-a-parent-chart

**Comment by meyerkev** [comment]
I think this is subtly missing the issue here.  

The goal is to have something like: 

templates/serviceaccount.yaml:
```
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-rollback
    "helm.sh/hook-weight": "-10"
    {{- toYaml . | nindent 4 }}
    {{- end }}
```

values-staging.yaml
```
account_id: 123456789012
environment: staging
```

values.yaml:
```
serviceaccount:
  annotations: 
    eks.amazonaws.com/role-arn: "arn:aws:iam::{{ .Values.account_id }}::role/eks-sa-{{ .Values.environment }}"
```

For future people who find this issue, our current workaround is doing this with a really nasty [Helmfile](https://github.com/helmfile/helmfile) that does most of the job of values.yaml because they *do* support recursive templating.  

And maybe that's the answer for Helm.  To tell people to use Helmfile

**Comment by genofire** [comment]
how you solve it in Helmfile ? (the recusive templating)

**Comment by genofire** [comment]
Not solved

**Comment by joejulian** [comment]
The question was asked, it was answered with documentation. An alternative solution was suggested.

The question has been raised several times regarding templating values.yaml and there's been a clear message from the core maintainers that that kind of complexity will not be added.

Please try out genofire's suggestion or consider writing a [helm plugin](https://helm.sh/docs/topics/plugins/) that does what you need.

**Comment by genofire** [comment]
I do not have any suggestion. I just tried to understand, what @meyerkev means.
