### ISSUE TITLE
Helm install hangs when Big Files are in Chart Directory

### ISSUE THREAD

**Issue by SudonymTM** [helm/helm#10999]
Hello everyone!
Today I've stumbled upon a Bug which had me frustrated for a while.

I've abused my Chart Directory on my VM for other Stuff aswell and made a Folder called "script" in it.
This Folder contained around 170 GitHub Repositories since I was merging my Databases to a different Cluster.

Now as I wanted to install my Helm Chart again after coming back to it after a few days, I've stumbled upon this.

When I ran the "helm install" command with my Arguments, nothing happened, nothing.
When I've added "--debug" to the command, it only showed me this:
`install.go:178: [debug] Original chart version: ""
install.go:195: [debug] CHART PATH: /home/sudonym/xxx-cluster-resources/helm/xxx-web`

After I've tested a different Helm Chart, which worked without any problems whatsoever, I've remembered the Script Directory I had in there as well and I moved it back a directory out of the Helm Scope.

Tadaa, everything worked fine again.

Not many People will do the same as I did, but when you do - there's barely any way to debug this other than remembering what the Hell you did. So maybe a "Huge"-File Check should be implemented?

Output of `helm version`:
version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.17.5"}

Output of `kubectl version`:
Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.22.8
WARNING: version difference between client (1.24) and server (1.22) exceeds the supported minor version skew of +/-1

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
DigitalOcean

**Comment by yxxhero** [comment]
@SudonymTM Do you have a example for this issue? a github address? Thanks very much.

**Comment by SudonymTM** [comment]
You could replicate it just by having huge Files in the Helm Repo Directory :) 
Pushing that to GitHub would be a little bit... big so to say :D
