### ISSUE TITLE
Should "General Conventions" best practices discourage the use of "-" in chart names?

### ISSUE THREAD

**Issue by brianloss** [helm/helm#10994]
Issue #2192 indicates that although there is a workaround for referencing subchart values when the chart name contains a "-" there are updated naming conventions in https://helm.sh/docs/chart_best_practices/values/ that indicate dashes should not be used in names (see the [final comment](https://github.com/helm/helm/issues/2192#issuecomment-892738573) in the issue). However that the [Chart Names](https://helm.sh/docs/chart_best_practices/conventions/#chart-names) guidance still indicates dashes are acceptable in the name, and even encourages it by listing two out of three example names having "-" characters in them. With the guidance as it stands, a chart developer can follow best practices and name a chart in a way that makes it difficult to use as a sub chart. It would seem to me either the chart naming best practices needs to be updated or a better solution for #2192 needs to be addressed.

**Comment by Ornias1993** [comment]
> there are updated naming conventions in https://helm.sh/docs/chart_best_practices/values/ that indicate dashes should not be used in names

No idea what you're going on about here.
That link still clearly states `Words may be separated with dashes (-)`.
May means "allowed but not required" and should be read in conjunction with the RFC guidelines:
https://datatracker.ietf.org/doc/html/rfc2119#section-5

**Comment by brianloss** [comment]
> > there are updated naming conventions in https://helm.sh/docs/chart_best_practices/values/ that indicate dashes should not be used in names
> 
> That link still clearly states `Words may be separated with dashes (-)`. 

You've hit on the inconsistency. The [link you included](https://helm.sh/docs/chart_best_practices/values/ ) when you quoted my issue absolutely does **not** say that words may be separated with dashes. It says for variable values that dashes are invalid. We're on the same page that the documentation for [chart names](https://helm.sh/docs/chart_best_practices/conventions/#chart-names) says that dashes are allowed. I'm questioning whether it *should* say that, given the problems their use creates for anyone wanting to extend a chart whose name has dashes in it. Just read the comments in #2192 and you'll see the difficulties in trying to make templates that reference values from a sub chart. The workaround suggested in the issue (using the index function) might only be a partial workaround, too, unless there's some other way to [set such values on the cli](https://github.com/helm/helm/issues/2192#issuecomment-353861196). A solution to the problem would be to prohibit dashes in chart names, or at the least, discourage their use.

**Comment by brianloss** [comment]
Thanks, I appreciate the response. I'm aware that, unfortunately, the Go team has no interest in making any improvement here. I think dashes could be made illegal in names, and IMO the logical way to do it would be to deprecate and make it illegal in the next major revision of the chart apiVersion. That wouldn't break any existing chart and would only make renaming a requirement to move to the new chart apiVersion. It seems like Helm 3 with apiVersion 2 would have been a good time to do that if it were going to happen.

My bad--I missed some of the rolled up history in #2192, and it looks like changes making dashes illegal were made and then rolled back. It also appears that changes highlighting the drawbacks of using dashes in chart names were also rolled back or otherwise lost. I haven't been able to find in the history where changes from #4379 left after #4400 were removed, so I am unable to figure out if they were just lost in renaming or if they were removed for another reason. If there was a reason, then it would seem pointless for me to try to get them re-introduced into the docs. In either case, it seems this issue should be closed and any other work happens on helm-www. Sorry for the issue churn here.
