### ISSUE TITLE
Explicit values param may break default values changes in further deploys

### ISSUE THREAD

**Issue by distorhead** [helm/helm#10993]
Test repo to reproduce bug: https://github.com/distorhead/test-helm-values.

1. Clone test repo to reproduce bug:
    ```
    git clone https://github.com/distorhead/test-helm-values
    cd test-helm-values
    ```

2. Deploy first time:
    ```
    git checkout cf2b2566ef1d92cee90cfa68b22d47699ce39b7e
    helm upgrade --install --namespace test-helm-values test-helm-values .
    ```

    ```
    # values.yaml
    arr:
      - one
      - two
      - three
    ```

3. Deploy second time with explicit --values param, and the same values.yaml:
    ```
    helm upgrade --install --namespace test-helm-values test-helm-values . --values ./values.yaml
    ```

4. Change values.yaml and deploy without explicit values param:
    ```
    git checkout 272dbee56738b2d9007bba6e983699ab232aaea5
    helm upgrade --install --namespace test-helm-values test-helm-values .
    ```

    ```
    # values.yaml
    arr:
      - one
      - two
      - three
      - four
    ```

5. Check resulting values and manifests:
    ```
    helm get all --namespace test-helm-values test-helm-values
    ```

   — this will contain `arr: [one, two, three]`, but expected `arr: [one, two, three, four]`.

`helm template` command will use correct version of values.yaml though.

**Comment by bacongobbler** [comment]
Have you tried modifying the value of the `--revision` and/or the `--all` flag for `helm get values` to determine whether it's retrieving the incorrect revision, or not retrieving the full set of computed values?
