### ISSUE TITLE
How to upgrade appversion in charts.yaml automatically and upload it in artifactory.

### ISSUE THREAD

**Issue by kavita1205** [helm/helm#11002]
As of now, we are updating appversion in Charts.yaml manually and then, we are running command "helm package ." which generates ".tgz" file , after that we are uploading this file to artifactory, so that latest appversion should be visible during next deployment.

Do we have any solution where we can automatically update appversion in Charts.yaml directly in artifactory.

**Comment by hickeyma** [comment]
@kavita1205 AFIK, this is the way to do this. Maybe there is another way but no way to do this directly.

**Comment by kavita1205** [comment]
@hickeyma Thanks for responding. What is AFIK? Can you please explain.

**Comment by kavita1205** [comment]
@hickeyma Can you please tell what is the other way to do this?

**Comment by hickeyma** [comment]
As far as I know (AFIK). As I said above, I think this the the way to do it.

**Comment by kavita1205** [comment]
@hickeyma I do not see any url or text, where you have mentioned to any way to fix this issue. :(
Can you please paste here your answer.
