### ISSUE TITLE
Go version used in V3.7.0

### ISSUE THREAD

**Issue by mbhadale** [helm/helm#11006]
Hi, I need information about go version used in v3.7.0 branch/tag/

I did helm version and it prints:

helm version
```
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}
```

but in the source code, I see: GoVersion: "go1.13.10"

https://github.com/helm/helm/blob/v3.7.0/cmd/helm/version.go#L36

This is a description string and looks like needs to be updated. 
Could you please confirm that the go version used in 3.7.0 is indeed go1.16.8?

**Comment by luisdavim** [comment]
I think this relates to: https://github.com/helm/helm/security/advisories/GHSA-cjjc-xp8v-855w

**Comment by mbhadale** [comment]
Affected  versions due to above CVE are:  2.0.0-2.16.7,3.0.0-3.0.3
Also, It says Helm 3.1.0 and newer are compiled against Go 1.13.7+.

I need to know which go version is used to compile helm 3.7.0

is GoVersion:"go1.16.8" correct?

**Comment by mbhadale** [comment]
Thanks for the confirmation!

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!
