### ISSUE TITLE
helm lint: error calling include: template: no template "..." associated with template "gotpl"

### ISSUE THREAD

**Issue by HarishKM7** [helm/helm#11008]
# The Setup

I have 3 Helm charts:
* 1 library chart called `lib`
* 1 "empty" application chart called `admin`
* Another application chart called `jws`
  * `jws` is physically nested under `admin` & `admin` depends on it

```
tree .
.
├── admin
│   ├── Chart.yaml
│   ├── jws
│   │   ├── Chart.yaml
│   │   └── templates
│   │       └── config-map.yaml
│   └── templates
└── lib
    ├── Chart.yaml
    └── templates
        └── _master.yaml

6 directories, 5 files
```

```
cat admin/Chart.yaml
apiVersion: v2
appVersion: "3.7"
dependencies:
- name: jws
  repository: file://jws
  version: 1.0.0
- name: lib
  repository: file://../lib
  version: 1.0.0
name: admin
type: application
version: 3.7.1171
```

```
cat admin/jws/Chart.yaml
apiVersion: v2
name: jws
type: application
version: 1.0.0
```

```
cat admin/jws/templates/config-map.yaml
{{ include "lib.master" . }}
```

```
cat lib/Chart.yaml
apiVersion: v2
name: lib
type: library
version: 1.0.0
```

```
cat lib/templates/_master.yaml
{{ define "lib.master" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-cm
data:
  key: value
{{ end }}
```

# The Issue

The chart installs fine but fails linting:

```
helm dependency update --skip-refresh admin
Saving 2 charts
Deleting outdated charts
```

```
helm lint --quiet --with-subcharts admin
==> Linting admin/charts/jws-1.0.0.tgz
[ERROR] templates/: template: jws/templates/config-map.yaml:1:3: executing "jws/templates/config-map.yaml" at <include "lib.master" .>: error calling include: template: no template "lib.master" associated with template "gotpl"

Error: 3 chart(s) linted, 1 chart(s) failed
```

```
helm list | grep admin
<no output>
```

```
kubectl get cm my-cm
Error from server (NotFound): configmaps "my-cm" not found
```

```
helm install admin admin
NAME: admin
LAST DEPLOYED: Wed Jun  1 09:59:33 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

```
helm list | grep admin
admin	default  	1       	2022-06-01 09:59:33.150291 +0530 IST  	deployed	admin-3.7.1171          	3.7
```

```
kubectl get cm my-cm
NAME    DATA   AGE
my-cm   1      13s
```

```
helm uninstall admin
release "admin" uninstalled
```

# Expected Result

Chart linting should succeed.

# Steps to Reproduce This Issue

1. Download & unzip [charts.zip](https://github.com/helm/helm/files/8811052/charts.zip)
2. Run `helm dependency update` & `helm lint` commands as seen in the `The Issue` section above

# `helm version`

version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.18.2"}

# `kubectl version`

Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:36:49Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"darwin/arm64"}

Kustomize Version: v4.5.4

Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.6-eks-7d68063", GitCommit:"f24e667e49fb137336f7b064dba897beed639bad", GitTreeState:"clean", BuildDate:"2022-02-23T19:29:12Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}

# P.S.

I realize that the chart structure is a bit unorthodox. `jws` should either be under `admin/charts` or live outside of `admin`, instead of being just a sub-directory of `admin`. We're working on fixing this. However, in the meanwhile, we'd still like to be able to lint our charts.

**Comment by bacongobbler** [comment]
Does the issue resolve itself if `jws` is under `admin/charts`? I wonder if there's some issue with regards to dependency resolution between `helm lint` and `helm install`

**Comment by HarishKM7** [comment]
@bacongobbler Yes, the issue resolves itself if `jws` is under `admin/charts`.
