### ISSUE TITLE
How to tell if a dependency is out of date

### ISSUE THREAD

**Issue by WoodyWoodsta** [helm/helm#11016]
I've searched far and wide, but I don't seem to be able to find any documentation on checking to see if a current chart's dependencies are out of date, nor any official way to see the latest versions of charts in a repository (though this would be tedious for charts with many dependencies). Is there a `helm` cli command to do any of the above? If not, what is the best way to check for outdated dependencies?

**Comment by hickeyma** [comment]
@WoodyWoodsta You can use the `helm search` command to check the Artifact Hub or a repository for a chat and its latest version. Alternatively, you would go to where the chart is hosted to get the latest version.

**Comment by WoodyWoodsta** [comment]
Ah, perfect. `helm search repo` is what I needed. Thank you!
