### ISSUE TITLE
Packaging and Pushing Charts into ECR which is prepended with a namespace 

### ISSUE THREAD

**Issue by baeyf** [helm/helm#11017]
Output of `helm version`:
version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.17.5"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.15", GitCommit:"8f1e5bf0b9729a899b8df86249b56e2c74aebc55", GitTreeState:"clean", BuildDate:"2022-01-19T17:27:39Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.15-eks-a64ea69", GitCommit:"03450cdabfc4162d4e447e6d8c5037efe6d29742", GitTreeState:"clean", BuildDate:"2022-05-12T18:44:04Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS

I have created a ECR with the name bar/foo/abc and now i want to package my chart and push it to this ECR. 
I am doing helm package -u dir/ -n bar/foo/abc but when i do helm push helm-test-chart-0.1.0.tgz oci://aws_account_id.dkr.ecr.region.amazonaws.com/ i am getting this error 
`Error: failed to do request: Post "https://account-id.dkr.ecr.us-east-1.amazonaws.com/v2/foo/bar/abc/abc/blobs/uploads/": EOF`

can you suggest me the correct way to push a chart if we have ECR created like ^

**Comment by alexzerd** [comment]
Same, executing

```
helm package .
helm push foobar oci://<aws-account-id>.dkr.ecr.<aws-region>.amazonaws.com/
```
results in:
`Error: failed to do request: Post "https://<aws-account-id>.dkr.ecr.<aws-region>.amazonaws.com/v2/foobar/blobs/uploads/": EOF`

**Comment by nickjmv** [comment]
Same issue here! +1

**Comment by manuelnucci** [comment]
I was having the same problem and figured it out.

The chart's name declared in `Chart.yaml` file must be the *same* as the name of the ECR repository. Only then one can execute

```shell
helm push foobar-X.Y.Z.tgz oci://<aws-account-id>.dkr.ecr.<aws-region>.amazonaws.com/
```

and delegate ECR to know in which repository to store the chart.

@baeyf If I understood correctly, in your case the repository URL should be `oci://<aws_account_id>.dkr.ecr.<aws-region>.amazonaws.com/foo/bar` and then the chart named `abc` should be there.

**Comment by nickjmv** [comment]
Great findings, this is indeed working!

**Comment by greggbjensen** [comment]
I ran into this same issue with the `EOF` error using AWS ECR with GitHub Actions.  The fix was adding the following environment variable:

```yaml
env:
  HELM_EXPERIMENTAL_OCI: 1
```

**Comment by joejulian** [comment]
Looks like this question has been answered. Thanks @manuelnucci

**Comment by aizada92** [comment]
same issue here. Chart.yaml file must be the same as the name of the ECR repository as you guys suggested but stillI am facing error while pushing.Error: failed to do request: Post "https://<aws-account-id>.dkr.ecr.<aws-region>.amazonaws.com/v2/test/test/uploads/": EOF Any Idea ?

**Comment by nvaklinov** [comment]
Same here as @aizada92

**Comment by michal-rybinski** [comment]
Seems (as it often is the case) that I was being an idiot.

I was blindly copying "push commands" from ECR not noticing that they have "docker login" in them instead of helm...
After I adjusted my command to use "helm registry login" AND created the repository BEFORE pushing - as outlined here https://docs.aws.amazon.com/AmazonECR/latest/userguide/push-oci-artifact.html - I was able to successfully push the tgz into it.

**Comment by vinibassi** [comment]
@manuelnucci 
@greggbjensen 

I tried both of your answers and I still get the same error, I wonder if I have to configure something in my ECR?
I'm using Helm version 3.9.0
I created the repo `api-chart` before pushing using `helm push` and the created repo URL is: `https://<aws.account.id>.dkr.ecr.<aws.region>.amazonaws.com/v2/api-chart`
But when I `helm push` I get this message on debug:
`helm.go:84: [debug] failed to do request: Post "https://<aws.account.id>.dkr.ecr.<aws.region>.amazonaws.com/v2/api-chart/api-chart/blobs/uploads/": EOF`
It's still appending the same name to the URL

**Comment by OfirYaron** [comment]
like @michal-rybinski, seems I was an idiot as well,
My little misadventure involved using the OCI URL (ECR path) along with the repository name, which, unsurprisingly, led to the same error.

To anyone else stumbling upon this message in the vast digital wilderness, I sincerely hope you won't have to endure the thrilling 60-minute rollercoaster ride that I just had. and I hope I helped.

**Comment by alephpt** [comment]
@[manuelnucci](https://github.com/manuelnucci)  saved me, 
BUT it took me a while to fully comprehend that the name of the repository in ECR must be the same as the Chart.yaml name

**Comment by NerijusMacaitis** [comment]
Is there other way to go around this Chart.yaml and repo name thing? 
What if I have much of different apps with different names, do you suggest that I need to create loads of repos? :/
