### ISSUE TITLE
option to set time-format via env variable or config file

### ISSUE THREAD

**Issue by RafalSkolasinski** [helm/helm#11028]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.17.5"}
```

Output of `kubectl version`:

N/A

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

N/A/

---

The `helm list` command allows to provide `--time-format` flag to control how date is rendered, for example:
```
helm list --time-format "2006-01-02"
```

It would be nice if one can set the default format in some config file, e.g. under `ls ~/.config/helm/` or at least as environmental variable.

**Comment by hickeyma** [comment]
@RafalSkolasinski Do you mins providing the use case for this.

**Comment by RafalSkolasinski** [comment]
Just convenience when working a lot with with helm from terminal. Usual output is too wide and lines gets wrapped which make the output harder to read. 

I could create an alias, true, but I'd prefer to be able to just set it once somewhere and keep using `helm list` as usual.

**Comment by bacongobbler** [comment]
This ask is quite similar to guy’s `.gitconfig` file, where you can set things like what signing key you use with the `signoff` flag, or what email address/name you use when authoring commits.

For example: https://github.com/bacongobbler/dotfiles/blob/main/gitconfig

commands like `aws configure` would be good inspiration for this.

I’m in favour of this request.

**Comment by hickeyma** [comment]
Thanks for the feedback @bacongobbler

**Comment by hickeyma** [comment]
@RafalSkolasinski This was discussed at the developer call today and it was agreed that this could be implemented.

It was suggested to implement it as a env variable which should only be CLI visible and not as part of the SDK package. It was also suggested that we look to provide configuration file settings as raised by @bacongobbler  in https://github.com/helm/helm/issues/11028#issuecomment-1149389317.  https://github.com/helm/helm/issues/11036 has been raised to track this effort.

**Comment by hickeyma** [comment]
@RafalSkolasinski Do you fell like pushing a PR for this?
