### ISSUE TITLE
helm template --output-dir: failure to render non-hook resources if a hook resource is part of the template

### ISSUE THREAD

**Issue by consideRatio** [helm/helm#11030]
```shell
# prepare chart for testing
cd /tmp
helm create test && cd test && rm -rf templates/*

cat <<EOF > templates/mixed.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: not-a-hook-in-mixed-template
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: a-hook-in-mixed-template
  annotations:
    # what matters seem to be that "helm.sh/hook" is specified at all
    "helm.sh/hook": pre-install,pre-upgrade
EOF
```

```shell
# verify bug, this currently finds only a single
# manifest rendered, but two should be around
helm template . --output-dir rendered
cd rendered/test/templates
grep "name:" *

# RESULT: one manifest, the hook resource independent of ordering
# not both as we would get and expect if the template file had only hooks
# or only non-hooks.
#
#   name: a-hook-in-mixed-template
#
```

Output of `helm version`:

```
version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.17.5"}
```

**Comment by bacongobbler** [comment]
I'm not sure what the expected behaviour is here. AFAICT Helm relies on the fact that one file == one manifest. Putting multiple manifests in a "mixed" template seems like an odd edge case.

**Comment by consideRatio** [comment]
I recall reading it as a best practice to not render multiple resources from a single YAML template, but that `helm` requires that would be a surprise to me as a user who has read the helm docs multiple times since version 2 and onwards.

I think that unless this is a bug, and its accepted to have this buggy behavior when multiple resources are rendered from the same template file, `helm lint` or `helm lint --strict` should not accept this without a warning at least.

@bacongobbler I invest significant time to report clear and reproducible bugs when I find them, and to me, this issue is a clear bug or undocumented assumption. Maybe it isn't important to resolve, I can get that as it is a seldom occurring situation, I'd be fine with a "wontfix" resolution to this issue, but to see this considered a support question makes me a bit sad. I have not opened this issue looking for help for my own gain, but to help this project even though I don't know Golang well enough to contribute as a code contributor.

Thank you for your work on this project, and I also understand the workload of triaging issues etc, it is a lot of work. That is why I care about providing clear reproducible and tightly scoped issues.
