### ISSUE TITLE
`helm repo index` does not provide recursion

### ISSUE THREAD

**Issue by wibed** [helm/helm#11039]
despite:
- https://github.com/helm/helm/issues/1401
- https://github.com/helm/helm/pull/1997
- https://github.com/helm/helm/issues/1401

recursive index of charts is not functional.

Preferably, i would either pull charts by cloning them into a directory. including locally developed charts. 
and not move generated files around

**Comment by bacongobbler** [comment]
Please provide a test case and a patch. The instructions for contributing code can be found in https://github.com/helm/helm/blob/main/CONTRIBUTING.md.

Thanks.
