### ISSUE TITLE
rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: kind: ConfigMap, namespace: default, name: indusnet-client-confi

### ISSUE THREAD

**Issue by TanushmaniPitchuka** [helm/helm#11037]
Hi All,

I'm trying to deploy the helm chart it is giving below error message

rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: kind: ConfigMap, namespace: default, name: indusnet-client-confi

**Comment by luisdavim** [comment]
check https://micarlise.dev/adopt-existing-helm-resources/
