### ISSUE TITLE
How to pass a custom kubernetes client to helm 3 go client

### ISSUE THREAD

**Issue by Segflow** [helm/helm#11047]
Given a custom k8s [*rest.Config](https://pkg.go.dev/k8s.io/client-go@v0.24.1/rest#Config) (e.g one created by controller-runtime), how can I can make helm3 clients that uses that? 

We using helm to programmatically install charts, and we need this capability to write tests.

**Comment by yxxhero** [comment]
@Segflow May be https://github.com/helm/helm/blob/657850e44b880cca43d0606ebf5a54eb75362c3f/pkg/action/action.go#L366

**Comment by pperiyasamy** [comment]
@Segflow did you make it work ? I too have similar situation, need to use controller-runtime rest.Config with helm3 client.

Tried the below:
```
	kubeConfig := genericclioptions.NewConfigFlags(false)
	kubeConfig.APIServer = &cfg.Host
	kubeConfig.BearerToken = &cfg.BearerToken
	kubeConfig.CAFile = &cfg.CAFile
	kubeConfig.Namespace = &namespace
	if err := actionConfig.Init(kubeConfig, r.Settings.Namespace(), os.Getenv("HELM_DRIVER"), debugLog); err != nil {
		return err
	}
```
But this doesn't seem to solve the issue, seeing `x509: certificate signed by unknown authority `error while helm client connecting into api server.

**Comment by pperiyasamy** [comment]
this seems to be passing after having kubeconfig Insecure set with true.

**Comment by Segflow** [comment]
That's too dangerous I believe

**Comment by yxxhero** [comment]
> That's too dangerous I believe

I think so.

**Comment by Segflow** [comment]
Even with 
```
	configFlags := genericclioptions.NewConfigFlags(false)
	configFlags.APIServer = &config.Host
	configFlags.BearerToken = &config.BearerToken
	configFlags.CAFile = &config.CAFile
	configFlags.CertFile = &config.CertFile
	configFlags.KeyFile = &config.KeyFile
	configFlags.BearerToken = &config.BearerToken
	configFlags.Insecure = &config.Insecure
	configFlags.Namespace = &opts.Namespace
```

It does not work because when you create an Envtest cluster you get a config where the CERT, CA and keys are not stored inside a file but rather in memory, eg `cfg.CertFile` is empty, while `cfg.CertData` is filled. Unfortunately `genericclioptions.ConfigFlags` does not have those fields.

**Comment by pperiyasamy** [comment]
@yxxhero @Segflow Thanks for coming back on this! yes, I'm using Envtest cluster in the unit tests and i hope it's ok to use insecure option to workaround this issue. do you agree ? But i'm still seeing `unable to build kubernetes objects from release manifest: unknown` error while installing the chart.

**Comment by pperiyasamy** [comment]
> Envtest cluster you get a config where the CERT, CA and keys are not stored inside a file but rather in memory, eg `cfg.CertFile` is empty, while `cfg.CertData` is filled

Let me try writing into temp files and use that for `genericclioptions.ConfigFlags`.

**Comment by pperiyasamy** [comment]
> Let me try writing into temp files and use that for `genericclioptions.ConfigFlags`.

it worked. thanks.
