### ISSUE TITLE
Multiple simultaneous upgrades of the same release does not work

### ISSUE THREAD

**Issue by oEscal** [helm/helm#11058]
First of all, this is an edge case, and most users will probably not face it. But it exists, and probably should be treated. The scenario is the following: imagine we have some Helm release, and we want to upgrade it. Everything works fine, but and if we upgrade this same release in two different operations simultaneously? For instance, with the following commands:
```bash
helm3 upgrade launch-mp1-test ./launch_mp1_test --namespace mp1 --output yaml --set mp1.replicas=1 --timeout 1800s &
helm3 upgrade launch-mp1-test ./launch_mp1_test --namespace mp1 --output yaml --set mp1_from_python.replicas=1 --timeout 1800s &
```
In this case, the first command runs successfully, but the second one fails with the following error:
```
Error: UPGRADE FAILED: release: already exists
```

This is something common if we are using Helm in some distributed computing scenario. 

The version I am using is v3.9.0, and I also tested with v3.7.2.

**Comment by cleverhu** [comment]
```
 ⚙ daocloud-cleverhu@daocloud  ~/helmtest/demo  Release "demo" has been upgraded. Happy Helming!                             [3:53:31 09/12]
NAME: demo
LAST DEPLOYED: Mon Sep 12 03:53:29 2022
NAMESPACE: tekton
STATUS: deployed
REVISION: 7
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace tekton -l "app.kubernetes.io/name=demo,app.kubernetes.io/instance=demo" -o jsonpath="{.items[0].metadata.name}")
  export CONTAINER_PORT=$(kubectl get pod --namespace tekton $POD_NAME -o jsonpath="{.spec.containers[0].ports[0].containerPort}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace tekton port-forward $POD_NAME 8080:$CONTAINER_PORT

[1]  - 99348 done       helm upgrade --install demo ./
 ⚙ daocloud-cleverhu@daocloud  ~/helmtest/demo  Error: UPGRADE FAILED: release: already exists                               [3:53:31 09/12]

[2]  + 99371 exit 1     helm upgrade --install demo ./
```
I tried `helm upgrade --install demo ./ &` twice and it reproduced successfully.

**Comment by FyiurAmron** [comment]
FWIW, the problem still persists, and makes debugging problematic. The error message in extremely unhelpful in this case.

**Comment by joejulian** [comment]
Reminds me of the old Rodney Dangerfield joke:

I went to the doctor and I said, "Hey doc, it hurts when I do this."
He said, "Stop doing that."

**Comment by elina-israyelyan** [comment]
The issue is still there and a proper message would be needed . Besides the message it would be nice to have a param that will enable to give a priority to the upgrade and queue them correspondingly to not miss anything. What do you think about this ? @oEscal @FyiurAmron 
Or being able to give a way for defining the minutes  the upgraded value should be left intact.
