### ISSUE TITLE
Need documentation about OCI

### ISSUE THREAD

**Issue by jycamier** [helm/helm#11059]
I need to add the [OCI annotations](https://github.com/opencontainers/image-spec/blob/main/annotations.md) and particularly `org.opencontainers.image.source` but I don't find any information about it in the doc.

**Comment by sabre1041** [comment]
@jycamier Helm does not pass any annotations to charts that are published to OCI registries. However, I do believe that it would be a good enhancement.

Thoughts on possible implementation:

* Map applicable properties from `Chart.yaml` to [documented annotations](https://github.com/opencontainers/image-spec/blob/main/annotations.md)
* User defined annotations

**Comment by scottrigby** [comment]
I agree this would be a good feature

**Comment by bacongobbler** [comment]
closing as a duplicate of #11062.
