### ISSUE TITLE
If else flow in Helm Charts

### ISSUE THREAD

**Issue by kaikiat** [helm/helm#11056]
Hi team,

I am having difficulties in creating a flow like this for my helm chart
```
{{- if .Release.Namespace eq "production-namespace" -}}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
{{- else if .Release.Namespace eq "staging-namespace" -}}
apiVersion: apps/v1
kind: Deployment
{{- end }}
```
I want to change the apiVersion and kind depending on the namespace. I wonder if anyone here has insights and experience on this. Thank you

**Comment by yxxhero** [comment]
`{{- if eq .Release.Namespace "production-namespace" -}}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
{{- else if eq .Release.Namespace "staging-namespace" -}}
apiVersion: apps/v1
kind: Deployment
{{- end }}`
