### ISSUE TITLE
dict key "y" got "true"

### ISSUE THREAD

**Issue by chuckliu1979** [helm/helm#11054]
Output of `helm version`:
version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Problem:

if put a dict with key "y", then it will be set to "true" in the .Values

snippet in values.yaml:

size:
  x: 1
  y: 2
  z: 3

test cm.yaml:cat templates/my-cm.yaml 
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm
data:
  size: {{ .Values.size | quote }}

Results:helm template . 
---
# Source: test/templates/my-cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm
data:
  size: "map[true:2 x:1 z:3]"

**Comment by chuckliu1979** [comment]
with values.yaml:size:
  x: 1
  y: 2
  z: 3

y: 4

template:apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm
data:
  size: {{ .Values.size | quote }}
  y: {{ .Values.y | quote }}

results:
 helm template . 
---
# Source: test/templates/my-cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm
data:
  size: "map[true:2 x:1 z:3]"
  y:

so it key is "y", the parse incorrect

**Comment by bacongobbler** [comment]
The value “y” in YAML is a Boolean truthy value. So is “true”, “yes”, and “on”.  See the YAML specification for more information.

**Comment by chuckliu1979** [comment]
got it. so the key should be quoted

**Comment by bacongobbler** [comment]
yes. That way the parser interprets it as a string.

Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!
