### ISSUE TITLE
If multiple errors exist, only one is returned making debugging really difficult

### ISSUE THREAD

**Issue by asilverman** [helm/helm#11055]
See here:
https://github.com/helm/helm/blob/7ceeda6c585217a19a1131663d8cd1f7d641b2a7/pkg/kube/client.go#L371-L386

I would advise that instead you append all errors into a slice of errors and serialize them into  a single error that can be passed back to the caller, that way troubleshooting a failed helm deployment becomes more straightforward

**Comment by yxxhero** [comment]
@asilverman PRs is welcome. Thanks very much.

**Comment by cleverhu** [comment]
I'd like to try this.
