### ISSUE TITLE
Feature request: Allow helm get <release> to specify the revision 

### ISSUE THREAD

**Issue by sandipchitale** [helm/helm#11052]
Presumably, to support rollback, Helm keeps track of previous manifests (and maybe the values, notes, and hooks). It will be great if the following was supported:

```
helm get all|hooks|manifest|notes|values RELEASE_NAME [RELEASE_REVISION] [flags]
```

This will be especially useful for hooks as those are deleted.

This will give us automatic and permanent information about each revision of the release. Hopefully, this is possible.

**Comment by sandipchitale** [comment]
I have implemented this in a VSCode extension:

https://marketplace.visualstudio.com/items?itemName=sandipchitale.vscode-kubernetes-helm-extras

This extension works with VSCode Kubernetes extension. The action is invoked from the context menu of Helm release revision secret nodes.

**Comment by yxxhero** [comment]
@sandipchitale PRs is welcome. Thanks very much.
