### ISSUE TITLE
Proposal: Allow a way to create an idempotent index.yaml file

### ISSUE THREAD

**Issue by colearendt** [helm/helm#11057]
Per discussion [here](https://github.com/helm/helm/issues/4482), there is reluctance to depend on filesystem times for chart "created" time. 

However, there are [other occasions](https://github.com/helm/chart-releaser/issues/133) where being able to create an index.yaml file from a set of data that is reliable (i.e. GitHub tags, releases, git logs, etc.). As a result, it would be ideal to have a way to generate the index file in an idempotent fashion.

I believe the only piece of data that is not reproducible is the "created" time. As a result, it would be ideal to have a way to `IndexFile.MustAdd()` with deterministic input / output (i.e. allow specifying the timestamp). This would allow index file creation to be idempotent downstream, which could improve CI mechanisms, migration to different build systems, and migration to different helm repositories without losing timestamp data.

Relevant code: 
https://github.com/helm/helm/blob/657850e44b880cca43d0606ebf5a54eb75362c3f/pkg/repo/index.go#L120-L146

Would a PR implementing such a solution be permissible? What approach would be preferable?

**Comment by yxxhero** [comment]
@colearendt Can you create a HIP for this feature. Thanks very much.

**Comment by colearendt** [comment]
Woops missed that process 😅 Thanks, will do!

**Comment by colearendt** [comment]
I started a HIP for this - haven't submitted yet

**Comment by colearendt** [comment]
I started on a HIP for this. Need to finish!

**Comment by colearendt** [comment]
Grr. My HIP is stagnant. Still hoping to get back to this 🙈

**Comment by colearendt** [comment]
Still hoping to get back here
