### ISSUE TITLE
Mongodb-Sharded pod crashlook backoff

### ISSUE THREAD

**Issue by ramkrishna2k3** [helm/helm#11051]
Output of `helm version`:
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                                APP VERSION
mongodb-sharded default         1               2022-06-17 07:12: +0000 UTC deployed        mongodb-sharded-5.0.8               5.0.9

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"}

Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.8-gke.201", GitCommit:"2dca91e5224568a093c27d3589aa0a96fd3ddc9a", GitTreeState:"clean", BuildDate:"2022-05-11T18:39:02Z", GoVersion:"go1.16.14b7", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

enabled parameters in values.yml: volume permission and metrics in [charts](https://github.com/bitnami/charts)/[bitnami](https://github.com/bitnami/charts/tree/master/bitnami)/mongodb-sharded/

I generated the config.yml after enabling the parameters and deployed through ytt. But the pod is failing to run. 

![image](https://user-images.githubusercontent.com/46816331/174246967-5adf3305-e170-492b-8439-3d6689c9be0f.png)

**checked logs of each pods:**
![image](https://user-images.githubusercontent.com/46816331/174247210-82093b41-1a87-4190-a153-671c51779ec2.png)
![image](https://user-images.githubusercontent.com/46816331/174247409-0b7f22c9-b38d-4c0b-a78f-2016389f3192.png)
![image](https://user-images.githubusercontent.com/46816331/174247631-2ca0c72b-fb91-4c89-9c8d-a9c9e656bf76.png)
![image](https://user-images.githubusercontent.com/46816331/174247788-b013f99c-76b6-4d5a-b0d3-61265bc0985b.png)

is there any issue in the code 

[mongoconfig.txt](https://github.com/helm/helm/files/8925474/mongoconfig.txt)

**Comment by yxxhero** [comment]
@ramkrishna2k3 This is not a issue of helm.

**Comment by ramkrishna2k3** [comment]
> @ramkrishna2k3 This is not a issue of helm.

@yxxhero  when I change the permission to chmod 777 then the pod starts Running.

**Comment by ramkrishna2k3** [comment]
oods: my mongodb-sharded-mongos-6956d4f4ff-mjclj describes the below error. Can somebody help me in this. 
513e768e685b988539a760401c00c72e934e1082ad96891602e8f4" in 19.047411818s
  Normal        Created            25m                    kubelet             Created container metrics
  Normal        Started            25m                    kubelet             Started container metrics
  Warning       Unhealthy          24m                    kubelet             Readiness probe failed: Current Mongosh Log ID:  62b93a470ec6caae37e46d47
Connecting to:                     mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.5.0
MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017
  Warning       Unhealthy  24m  kubelet  Readiness probe failed: Current Mongosh Log ID:  62b93a63de6878feba7c88d1
Connecting to:             mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.5.0
MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017
  Warning       Unhealthy  24m  kubelet  Readiness probe failed: Current Mongosh Log ID:  62b93a6592058e0d68a4cb88
Connecting to:             mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.5.0
MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017

**Comment by yxxhero** [comment]
> pods: my mongodb-sharded-mongos-6956d4f4ff-mjclj describes the below error. Can somebody help me in this. 513e768e685b988539a760401c00c72e934e1082ad96891602e8f4" in 19.047411818s Normal Created 25m kubelet Created container metrics Normal Started 25m kubelet Started container metrics Warning Unhealthy 24m kubelet Readiness probe failed: Current Mongosh Log ID: 62b93a470ec6caae37e46d47 Connecting to: mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.5.0 MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017 Warning Unhealthy 24m kubelet Readiness probe failed: Current Mongosh Log ID: 62b93a63de6878feba7c88d1 Connecting to: mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.5.0 MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017 Warning Unhealthy 24m kubelet Readiness probe failed: Current Mongosh Log ID: 62b93a6592058e0d68a4cb88 Connecting to: mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.5.0 MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017

This is not issue for helm. Please check your network or k8s cluster.
