### ISSUE TITLE
Feature: Publish OCI Annotations

### ISSUE THREAD

**Issue by sabre1041** [helm/helm#11062]
Metadata in the form of annotations can be associated to [OCI based images](https://github.com/opencontainers/image-spec/blob/main/annotations.md). Helm also supports defining annotations on the `Chart.yaml` file. When publishing charts to OCI based registries, annotations should also be published to the image manifest.

Annotations would be associated with the following:

1. Known/Predefined keys
2. User defined annotations

The following table defines how OCI annotations are mapped including applicable fields from the `Chart.yaml` file.

| OCI Annotation                      | Description |  `Chart.yaml` field |
| ----------------------------------- | ------------| ------------------- |
| `org.opencontainers.image.created`  | RFC 3339 date the chart was published to the registry | |
| `org.opencontainers.image.authors` | Comma separated list of maintainers in the form `Maintainer Name 1 (email), Maintainer Name2 (email)` | `maintainers` |
| `org.opencontainers.image.url`| URL of the project | `home` |
| `org.opencontainers.image.source` | First item from the `sources` property | `sources` |
| `org.opencontainers.image.version` | Chart Version | `version` |
| `org.opencontainers.image.title` | Chart name | `name` |
| `org.opencontainers.image.description` | Chart description | `description` |
| `<User Defined Annotations>` | Additional annotations to include | `annotations` |

Additional annotations as designated in the `annotations` field within the `Chart.yaml` file.

Certain user defined annotations cannot override the generated value:

* `org.opencontainers.image.created`
* `org.opencontainers.image.title`
* `org.opencontainers.image.version`

Related to #11059

**Comment by scottrigby** [comment]
My only question is whether the oci artifact digest would change if annotations were added, or if it's only calculated on the content. Asking because currently, helm push is idempotent. Can not look into it right now, but discussed with @sabre1041 and one of us will check on this

**Comment by mpashkovskiy** [comment]
While we are waiting for the PR to get merged here is a workaround:

1. create `annotations.json`
    ```json
    {
      "$manifest": {
        "annotation1": "foo",
        "annotation2": "bar"
      }
    }
    ```
2. create either empty `config.json` or convert `Chart.yaml` to JSON and save it as `config.json`
3. push the chart with oras (version 0.15.0 was used)
    ```bash
    aws ecr get-login-password | oras push -u AWS --password-stdin \
      $(ECR_REGISTRY)/$(IMAGE_NAME):$(IMAGE_TAG) \
      --config config.json:application/vnd.cncf.helm.config.v1+json \
      --annotation-file annotations.json \
      $(IMAGE_NAME)-$(IMAGE_TAG).tgz:application/vnd.cncf.helm.chart.content.v1.tar+gzip
    ```
4. `aws ecr batch-get-image` could be used to pull information about the image
    ```json
    {
	    "schemaVersion":2,
	    "mediaType":"application/vnd.oci.image.manifest.v1+json",
	    "config":{
		    "mediaType":"application/vnd.cncf.helm.config.v1+json",
		    "digest":"sha256:ca3d163bab055381827226140568f3bef7eaac187cebd76878e0b63e9e442356",
		    "size":3
	    },
	    "layers":[
		    {
			    "mediaType":"application/vnd.cncf.helm.chart.content.v1.tar+gzip",
			    "digest":"sha256:4daf63839a7c00eb96b332da4002509059bd6c2082c32b3a269681c7e3a379b9",
			    "size":3833,
			    "annotations":{
				    "org.opencontainers.image.title":"..."
			    }
		    }
	    ],
	    "annotations":{
                "annotation1": "foo",
                "annotation2": "bar"
            }
    }
    ```

Example of a `Makefile`:

```Makefile
ECR_REGISTRY = ???
IMAGE_NAME = ???
IMAGE_TAG = ???

annotations.json:
	echo '{"$$manifest": {"annotation1": "foo","annotation2": "bar"}}' > annotations.json

config.json:
	echo '{}' > config.json

.PHONY: oras-publish
oras-publish: annotations.json config.json
	aws ecr get-login-password | oras push -u AWS --password-stdin \
		$(ECR_REGISTRY)/$(IMAGE_NAME):$(IMAGE_TAG) \
		--config config.json:application/vnd.cncf.helm.config.v1+json \
		--annotation-file annotations.json \
		$(IMAGE_NAME)-$(IMAGE_TAG).tgz:application/vnd.cncf.helm.chart.content.v1.tar+gzip

.PHONY: get-annotations
get-annotations:
	aws ecr batch-get-image \
		--repository-name $(IMAGE_NAME) \
		--image-id imageTag=$(IMAGE_TAG) \
		--output json | jq -r '.images[].imageManifest'
```

Hope that will help someone in the meantime.
