### ISSUE TITLE
make test fails if a local ~/.kube/config with non default namespace exists

### ISSUE THREAD

**Issue by devfbe** [helm/helm#11063]
I noticed that when I execute "make test" for running the helm unit tests, ~130 tests fail. This only happens when my default namespace in the kube config is not "default". If I switch it back to "default", all unit tests succeed.

The tests also succeed, if there is no ~/.kube/config.

This happens in the current main branch (657850e44b880cca43d0606ebf5a54eb75362c3f).

Expected behavior:

Unit tests run isolated and don't interfere with the local ~/.kube/config (which might be dangerous if other developers writing tests are not aware of this fact).

**Comment by yxxhero** [comment]
@devfbe Can you the more info. Thanks very much.
