### ISSUE TITLE
delete pending-upgrade release

### ISSUE THREAD

**Issue by anutator** [helm/helm#11067]
Output of `helm version`: 3.9.0
Output of `kubectl version`: 1.18.7
Cloud Provider/Platform (AKS, GKE, Minikube etc.):  own bare-metal

I'd like to remove pending-upgrade release automatically in Gitlab. Is there any helm analog for command
`kubectl -n NS delete secret -l name=release-name,status=pending-upgrade`

I use helm docker image in Gitlab and I'd like not to add kubectl to image.

**Comment by jemygraw** [comment]
i think you just need to use `helm uninstall <releaseName>` rather than to delete the secret.
