### ISSUE TITLE
`helm get notes` not working for flux apps 

### ISSUE THREAD

**Issue by mirsahibmovsumov** [helm/helm#11089]
I cannot get release notes of fluxcd through [helm3](https://pkg.go.dev/helm.sh/helm/v3). 
it returns `release: not found `. Both helm3 go client and cli are the same:
```
helm.exe get notes miri2-miri  --kubeconfig ./kube.yaml -n taikun-apps
Error: release: not found
```
it works for another namespace and non-flux apps
```
C:\Program Files\helm.exe get notes taikun  --kubeconfig ./kube.yaml -n monitoring
C:\Program Files\helm>

```

**Comment by yxxhero** [comment]
@mirsahibmovsumov Please ensure your release namespace is right. Thanks very much.

**Comment by mirsahibmovsumov** [comment]
@yxxhero, thanks for your answer. Let me show you 
`C:\Program Files\helm>helm.exe ls -A --kubeconfig ./kube.yaml
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
miri-miri-miri  miri            1               2022-05-10 14:51:12.268405314 +0000 UTC deployed        jenkins-3.12.2          2.332.3
miri-miri2-miri miri            1               2022-05-11 08:32:50.650290596 +0000 UTC deployed        jenkins-3.12.2          2.332.3
taikun          monitoring      3               2022-05-23 14:13:50.048788358 +0000 UTC deployed        taikun-lma-0.1.24       1.16.0

C:\Program Files\helm>helm.exe get notes miri-miri-miri  --kubeconfig ./kube.yaml -n miri
Error: release: not found

C:\Program Files\helm>helm.exe get notes taikun --kubeconfig ./kube.yaml -n monitoring

C:\Program Files\helm>`

**Comment by yxxhero** [comment]
@mirsahibmovsumov thanks very much. Can you explain what is flux apps? I don't known about it.

**Comment by mirsahibmovsumov** [comment]
@yxxhero, it’s CRD in Kubernetes representing helm chart. We install helm charts using this : https://fluxcd.io/docs/components/helm/

**Comment by yxxhero** [comment]
@mirsahibmovsumov Ok. I will see this issue. Thanks very much.

**Comment by yxxhero** [comment]
@mirsahibmovsumov

**Comment by mirsahibmovsumov** [comment]
@yxxhero , Flux is installing it yes

**Comment by bacongobbler** [comment]
> Flux is installing it yes

Issues relating to the flux project should be filed with the Flux maintainers. Please file a ticket with their team. Thanks.

**Comment by mirsahibmovsumov** [comment]
I've asked it in CNCF flux slack channel. The answer was to specify `storageNamespace` parameter equal to  `targetNamespace ` and it worked.
