### ISSUE TITLE
Unable to upgrade Helm Chart

### ISSUE THREAD

**Issue by rav17** [helm/helm#11097]
Hi Team,

I am working on Helm Chart and it working as expected when its does the fresh install of K9s objects like deployment, pvc, services etc. But When I try ti upgrade the existing deployment again, the Helm throws following error :

![image](https://user-images.githubusercontent.com/10693825/176421406-5eb4bf68-9254-42d2-8571-24bf057180f4.png)
 

Output of `helm version`:
version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.5"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.15-eks-a64ea69", GitCommit:"03450cdabfc4162d4e447e6d8c5037efe6d29742", GitTreeState:"clean", BuildDate:"2022-05-12T18:44:04Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

EKS

**Comment by yxxhero** [comment]
@rav17 Please check your network issue. Thanks very much.

**Comment by rav17** [comment]
@yxxhero . I am a bit confused here, if it was netwrok issue, then the helm chart shouldn't be able to do the installation at the first place. the issue is its happening only during the upgrade of the already installed deployment using the same Helm Chart
