### ISSUE TITLE
[FR] Better Sibling Context Handling, Helper Template usage

### ISSUE THREAD

**Issue by jslay88** [helm/helm#11095]
After multiple discussion with users over the years on the k8s slack, it is clear that passing data (helper templates, root context, etc), between sibling charts is not an uncommon need. 

While we do have the use of `global` values, this does not lend itself to being able to pass dynamically generated values from sibling helper templates, to other siblings; without a lot of workaround and strife. At the moment, it seems like root context is lost the moment you get into a child/sibling helper template, even if you pass `$` to it, so you can't even determine anything about the context that is being passed outside of that chart. 

Having a better mechanism within Helm to either pass around a proper root context to siblings, so that they can leverage global helper templates to determine the generated values of their siblings. 

Ergo, having an umbrella chart, that contains 3 childs, 2 of which require a db, the third being the db. Being able to pass the DB's helper template values to the 2 siblings, such as the generated service name of the DB chart.

**Comment by jslay88** [comment]
bump

**Comment by joejulian** [comment]
Happy to have a contribution to address this. Probably should start with a [HIP](https://github.com/helm/community/blob/main/hips/hip-0001.md) also take a look at the [contributing](https://github.com/helm/helm/blob/main/CONTRIBUTING.md) doc.

**Comment by creiche** [comment]
I would love to see this working since ran into this issue in a recent project.  Trying to use an umbrella chart to deploy many services where they cross reference each other's helpers.
