### ISSUE TITLE
Bump Go to 1.18

### ISSUE THREAD

**Issue by yxxhero** [helm/helm#11106]
Output of `helm version`:
None
Output of `kubectl version`:
None
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
None

`Bump Go to 1.18`

**Comment by wujunwei** [comment]
I wonder why  it's 1.17 in latest go.mod now ?

https://github.com/helm/helm/blob/44ec1c1575d405675272ee2d8131130a5decee7c/go.mod#L1-L5
