### ISSUE TITLE
Introduce `--wait-fail-fast` option for `--wait` and `--wait-for-jobs` 

### ISSUE THREAD

**Issue by Dentrax** [helm/helm#11116]
Imagine we have hundreds of nodes and want to roll out a new version of template using Helm. We usually pass `--wait` command with `--timeout 15m` to ensure our rollout succeeded. The problem here is if one of pods crashed due to new upgrade or have some `ImagePullBackOff` error, `--wait` still _waits_ for given _timeout_ time. This unnecessarily increases' pipeline duration. Instead, we would introduce a new flag to tackle this problem:

`--wait-fail-fast`: Observe the first pod that being deployed new, if _any error_ occurred (if condition is not _NotReady_), throw deployment fail and exit with 1.

Volunteer to implement this flag, if that makes sense!

Output of `helm version`: `3.9.0`

Output of `kubectl version`: `1.24`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): `-`

**Comment by bacongobbler** [comment]
I don't think a new flag has to be introduced for this. This seems more like a bug with the `--wait` flag's intended behaviour.

**Comment by Dentrax** [comment]
/reopen

Hey @bacongobbler, I've worked on a demo a few months ago by introducing `--wait-ignore-unschedulable` for backward compatibility. See the commit on my fork: https://github.com/Dentrax/helm/commit/b2ac9fa7d253d93f1300afe78bff074e38b61cb2 Then I decided to hold this due a known-bug in `--wait` flag, see the related fix here: https://github.com/helm/helm/pull/10920 I'll be got into it again once the following PR is merged.
