### ISSUE TITLE
Misleading behaviour of --set and --reuse-values

### ISSUE THREAD

**Issue by camaeel** [helm/helm#11117]
1. I want to install my helm chart with replicas set to zero, so I execute: `helm upgrade --install --namespace kyverno kyverno kyverno  --set kyverno.replicaCount=0`. All is fine - helm chart is installed with 0 replicas set. 
2. Then I want to check diff of this helm chart with replicas value set to default from helm chart's values.yaml file (value is 3). When I execute now `helm diff upgrade --install --no-color --namespace kyverno kyverno kyverno --allow-unreleased` I get a diff in replicas of deployment. 
3. Then I want to install it with default value of replicas: `helm upgrade --install --namespace kyverno kyverno kyverno`, but there is no change in the installed resources. 

I found this article: https://medium.com/@kcatstack/understand-helm-upgrade-flags-reset-values-reuse-values-6e58ac8f127e which mentions that depending if there are any --set parameters passed to the command implcitily either --reuse-values or --reset-values is used. This is completely inconsistent and misleading, as `helm template` produces different output than `helm upgrade --install`. Also this silent change to --reuse-values if no --set parameters are passed is error prone. 

Output of `helm version`: version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.18.2"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.9", GitCommit:"6df4433e288edc9c40c2e344eb336f63fad45cd2", GitTreeState:"clean", BuildDate:"2022-04-13T19:57:43Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.9", GitCommit:"6df4433e288edc9c40c2e344eb336f63fad45cd2", GitTreeState:"clean", BuildDate:"2022-04-13T19:52:02Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): none

**Comment by bacongobbler** [comment]
I'm not sure what's the suggested change to be made here. Any changes to the current behaviour would be a breaking change UNLESS you can prove that

a) changing its behaviour will not break backwards compatibility, or
b) this behaviour is unintentional and can be construed as a bug

Based on the information provided here, I don't think this is a bug but more or of a misunderstanding of how the values system works. Therefore any suggested improvements to the system will have to wait until Helm 4.

**Comment by camaeel** [comment]
Design of the whole approach is totally wrong. 

Proper solution for me would be to always use as default --reset-values mode if --reuse-values is not explicitly passed. 

`helm template` should also behave the same way as `helm upgrade` does.
