### ISSUE TITLE
unclear wording on documentation for "required" function

### ISSUE THREAD

**Issue by majewsky** [helm/helm#11114]
On <https://helm.sh/docs/howto/charts_tips_and_tricks/#using-the-required-function>, it is not clear which values will actually make the "required" function fail. The second paragraph says:

> If the entry is empty in `values.yaml`, the template will not render

But the final line reads:

> The above will render the template when `.Values.foo` is defined, but will fail to render and exit when `.Values.foo` is undefined.

"empty" sounds like zero values such as `""` will be rejected, but "defined/undefined" sounds like only null values will be rejected.

**Comment by yxxhero** [comment]
@majewsky https://github.com/helm/helm-www
thanks very much. Please create a PR for this in helm-www
