### ISSUE TITLE
Strict naming policy for OCI causing naming clashes 

### ISSUE THREAD

**Issue by flaviu-muresan** [helm/helm#11127]
Not sure if this is the right place to ask, but we work in a large organisation where all teams are sharing the same container registry. The newly introduced [strict naming policy](https://helm.sh/docs/topics/registries/#deprecated-features-and-strict-naming-policies) for OCI artefacts is opening up for name clashes, e.g. two projects might be developing services/charts with the same name  but deployed to different namespaces. This makes it impossible to guarantee them pulling the correct artefact at deployment time. Prior to 3.7.0 we used to tag the chart artefact with the repo's name to guarantee uniqueness.

Did we miss something or is there a way around this with the current policy in place?

**Comment by mattfarina** [comment]
This is a good place to ask.

Could you provide an example of what you mean?

With Helm you should be able to have a chart at `oci://example.com/foo/bar` and `oci://example.com/baz/bar`. Two charts with the same name in different namespaces. Helm should be looking at the **[basename](https://en.wikipedia.org/wiki/Basename)** to be the same as the chart name and not the namespace.

Are you experiencing an issue? Or, am I misunderstanding?

**Comment by flaviu-muresan** [comment]
Thank you @mattfarina , what you suggested is also what we were about to do, and that would definitely work. The issue is that currently we have a lot of other CI/CD components relying on a naming convention that is no longer possible to implement under this strict naming policy, so I just wanted to confirm that there is indeed no other way before changing all of them (or that there's no plans to revisit the policy and perhaps allow more flexible tagging again, in future versions).
