### ISSUE TITLE
Upgrade version of containerd to 1.6.6

### ISSUE THREAD

**Issue by billrein** [helm/helm#11121]
**Description**
Upgrade containerd from v1.6.3  to v1.6.6

containerd  version >= 1.6.0, < 1.6.6 of containerd has problem of "Host memory exhaustion through ExecSync "
https://github.com/advisories/GHSA-5ffw-gxpp-mxpf

**Describe the solution you'd like** 
upgrade version of containerd to 1.6.6

**Additional context**
https://github.com/advisories/GHSA-5ffw-gxpp-mxpf

**Comment by yxxhero** [comment]
@billrein welcoem to create a PR for this issue.

**Comment by bacongobbler** [comment]
To be clear, this CVE does not affect Helm because it does not use containerd's container runtime interface - only the [`remotes.Resolver` struct](https://github.com/helm/helm/blob/c52cd40acef183d29f6def5026e66616b9993c88/pkg/registry/client.go#L30).

**Comment by hickeyma** [comment]
PR #11093 opened for this.
