### ISSUE TITLE
helm install --skip-crds failed when crds are manually installed

### ISSUE THREAD

**Issue by andyli** [helm/helm#11137]
I'm trying to install the [cloudnative-pg chart](https://github.com/cloudnative-pg/charts/tree/main/charts/cloudnative-pg), with the CRDs being manually managed.

The steps I used:

 1. install the [CRDs](https://github.com/cloudnative-pg/charts/blob/main/charts/cloudnative-pg/templates/crds/crds.yaml) manually
 2. add helm repo: `helm repo add cnpg https://cloudnative-pg.github.io/charts`
 3. run `helm install` with `--skip-crds`: 
```
$ helm install cnpg --namespace database cnpg/cloudnative-pg --skip-crds
Kubeconfig user entry is using deprecated API version client.authentication.k8s.io/v1alpha1. Run 'aws eks update-kubeconfig' to update.
Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: CustomResourceDefinition "backups.postgresql.cnpg.io" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "cnpg"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "database"
```

I think with `--skip-crds`, helm should not try to install/import the existing CRDs?

Output of `helm version`:
```
version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.17.5"}
```

Output of `kubectl version`:
```
Kubeconfig user entry is using deprecated API version client.authentication.k8s.io/v1alpha1. Run 'aws eks update-kubeconfig' to update.
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.15", GitCommit:"8f1e5bf0b9729a899b8df86249b56e2c74aebc55", GitTreeState:"clean", BuildDate:"2022-01-19T17:27:39Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.15-eks-a64ea69", GitCommit:"03450cdabfc4162d4e447e6d8c5037efe6d29742", GitTreeState:"clean", BuildDate:"2022-05-12T18:44:04Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

AWS EKS

**Comment by phil9909** [comment]
Looking at the cloudnative-pg chart I noticed that they have put the `crds` folder as a sub-folder of `templates`.
To use the Helm CRD handling the `crds` folder should be in the root of the chart.
Documentation: https://helm.sh/docs/topics/charts/#custom-resource-definitions-crds

I saw you already figured this out yourself and opened an issue on the chart: https://github.com/cloudnative-pg/charts/issues/15
I guess this was just an mistake, but let's see what the cloudnative-pg maintainers will say.

Currently, I don't see why this is an issue on Helm-side. If you agree, please close this issue. You can also reopen any time.

**Comment by andyli** [comment]
Are there any valid reasons to keep crds inside `templates` instead of the `crds` in chart root? If only the latter is supported/preferred, it would be good to have helm to print a warning when it detects there are crds out of place.

**Comment by phisco** [comment]
We tend to change crds spec in a retrocompatible way, when we built the chart IIRC putting the crds in the crds folder didn't allow updating them.

**Comment by phisco** [comment]
any particular reason to manually manage CRDs?

**Comment by andyli** [comment]
> any particular reason to manually manage CRDs?

I'm doing it just because all the other helm charts I used (e.g. [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#from-35x-to-36x) and [cert-manager](https://cert-manager.io/docs/installation/helm/#3-install-customresourcedefinitions)) require me to do so, so I thought I need to.

**Comment by phisco** [comment]
Indeed, we put the CRDs in the template folder exactly to avoid having to do that, we added the annotation in order to avoid deleting all the resources in case of deletion of the chart, just to be safe. Feel free to close both issues if you think it's the case.
