### ISSUE TITLE
helm upgrade --install --version does not find development version

### ISSUE THREAD

**Issue by sptowey** [helm/helm#11135]
Output of `helm version`:
`version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.17.5"}`

Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"42a9a90338d705a1650fb68b7891f84b62adb0b0", GitTreeState:"clean", BuildDate:"2022-06-15T04:25:21Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
docker desktop and AKS

---
As title states, I cannot install a development version (version with letters) of a chart from a repository. The version exists in the repository (revealed by --devel flag), but will not install.

`helm search repo appendicitis --versions --devel`
NAME                                            CHART VERSION   APP VERSION     DESCRIPTION
vrad-harbor-vrad/ct-abdomen-appendicitis        0.0.18          1.0             vRad CT Abdomen Appendicitis Inference helm chart
vrad-harbor-vrad/ct-abdomen-appendicitis        0.0.18-rc       1.0             vRad CT Abdomen Appendicitis Inference helm chart
vrad-harbor-vrad/ct-abdomen-appendicitis        0.0.18-r        1.0             vRad CT Abdomen Appendicitis Inference helm chart
**vrad-harbor-vrad/ct-abdomen-appendicitis        0.0.18-dev      1.0             vRad CT Abdomen Appendicitis Inference helm chart**
vrad-harbor-vrad/dev-ct-abdomen-appendicitis    0.0.17          1.0             vRad CT Abdomen Appendicitis Inference helm chart

`helm upgrade -n dev --install vrad-harbor-vrad/ct-abdomen-appendicitis --dry-run ct-abdomen-appendicitis --username "<redacted>" --password "<redacted>" -f values.yaml --version 0.0.18-dev`
Error: release name is invalid: vrad-harbor-vrad/ct-abdomen-appendicitis

I have also tried with the --devel flag, but from my understanding, the --version flag overrides the --devel flag.

**Comment by yxxhero** [comment]
Error: release name is invalid: vrad-harbor-vrad/ct-abdomen-appendicitis

**Comment by sptowey** [comment]
> Error: release name is invalid: vrad-harbor-vrad/ct-abdomen-appendicitis

The release name should be valid. You can see that it exists with the given version number via the helm search repo command.

**Comment by yxxhero** [comment]
helm upgrade -n dev --install ct-abdomen-appendicitis vrad-harbor-vrad/ct-abdomen-appendicitis --dry-run --username "<redacted>" --password "<redacted>" -f values.yaml --version 0.0.18-dev

**Comment by sptowey** [comment]
> helm upgrade -n dev --install ct-abdomen-appendicitis vrad-harbor-vrad/ct-abdomen-appendicitis --dry-run --username "" --password "" -f values.yaml --version 0.0.18-dev



> helm upgrade -n dev --install ct-abdomen-appendicitis vrad-harbor-vrad/ct-abdomen-appendicitis --dry-run --username "" --password "" -f values.yaml --version 0.0.18-dev

Incredible. I can't believe I wasted 2 days on this, and my only mistake was having the args in the wrong order.

Thanks so much for your help!
