### ISSUE TITLE
go 1.18 template change

### ISSUE THREAD

**Issue by phil9909** [helm/helm#11146]
The following template will produce different results, depending on the go version used to compile `helm` (same helm commit):

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- if and .Values.deployment.metadata .Values.deployment.metadata.name }}
  name: {{ .Values.deployment.metadata.name }}
  {{- else }}
  name: fallback
  {{- end }}
spec: {}
```

In go 1.18 compiled helm, it works:

```bash
$ ~/workspace/helm/helm-go1.18 template .                                                                                                                           
---
# Source: short/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fallback
spec: {}
```

In go 1.17 compiled helm, it fails:

```bash
$ ~/workspace/helm/helm-go1.17 template .
Error: template: short/templates/deployment.yaml:4:48: executing "short/templates/deployment.yaml" at <.Values.deployment.metadata.name>: nil pointer evaluating interface {}.name

Use --debug flag to render out invalid YAML
```

## Reproduction

I tried this with the current head of `main`, at the time of writing this 93779886 

1. Compile helm
    ```bash
    # build helm with go 1.18
    docker run --rm -v $PWD:$PWD -w $PWD golang:1.18 go build -o helm-go1.18 ./cmd/helm 
    
    # build helm with go 1.17
    docker run --rm -v $PWD:$PWD -w $PWD golang:1.17 go build -o helm-go1.17 ./cmd/helm
    ```
1. Create a Helm chart:
    - with empty `values.yaml`
    - minimal `Chart.yaml` (the one create by `helm create ...` will do)
    - the template from above in the `templates` folder
1. Call `helm-go1.18 template` and `helm-go1.17 template` on the chart (without any values)

## Root Cause

go 1.18 changed how `and` and `or` works in templates:

> The and function no longer always evaluates all arguments; it stops evaluating arguments after the first argument that evaluates to false. Similarly, the or function now stops evaluating arguments after the first argument that evaluates to true. This makes a difference if any of the arguments is a function call. 
>
> Source [Go 1.18 Release Notes](https://go.dev/doc/go1.18#text/template)

## Implications

In general, it think this is a good thing and might even be worth a mention in the release notes as a feature, as it makes writing charts more convenient (related [Best Practices > Values > Flat or Nested Values](https://helm.sh/docs/chart_best_practices/values/#flat-or-nested-values) and https://github.com/helm/helm/issues/11070).

The downside: Charts written by people using the upcoming helm 3.10 might not be usable by people using helm 3.9 or lower.
Same applies for people using helm using unofficial binary distributions (maybe brew) or self-compiled helm version (given they use go < 1.18). 
According to [HIP-0004 Document backwards-compatibility rules](https://github.com/helm/community/blob/main/hips/hip-0004.md) this change is allowed:
> the template syntax cannot change except when the change is directly from the Go programming language  

Others? Tell me.

**Comment by louismrose** [comment]
I think this inconsistency is perhaps already in the wild.

When downloading https://get.helm.sh/helm-v3.9.0-linux-amd64.tar.gz, I see:

```
version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.17.5"}
```

But after installing Helm v3.9.0 via brew on macOS, I see:

```
version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.18.2"}
```

Is there any official advice from the maintainers of this project as to when the Go version is expected to be bumped with respect to the Helm version?

**Comment by yxxhero** [comment]
@hickeyma @bacongobbler @scottrigby
