### ISSUE TITLE
multiple path based routing from helm

### ISSUE THREAD

**Issue by srishtiaggarwal** [helm/helm#11152]
Hi Team,

I have a query related to the helm, I want to create a common host based or Path based routing ingress for multiple services. 
Example - Something like this -
spec:
  rules:
  - host: [service1.example.com](http://service1.example.com/)
    http:
      paths:
      - backend:
          service:
            name: service1
            port: 
              nameber: 80
        path: /*
        pathType: ImplementationSpecific
  - host: [service2.example.com](http://service2.example.com/)
    http:
      paths:
      - backend:
          service:
            name: service2
            port:
              number: 80
        path: /service2/*
        pathType: ImplementationSpecific
      - backend:
          service:
            name: service3
            port:
              number: 80
        path: /service3/*
        pathType: ImplementationSpecific
 Is it possible using helm to set a common ingress and use it for multiple services? If possible, then can you please guide me?

**Comment by joejulian** [comment]
If I'm understanding your question, you may find [named templates](https://helm.sh/docs/chart_template_guide/named_templates/) useful for that. Define your common elements, then include them using `{{ template "common_elements" .}}` in your ingress template.
