### ISSUE TITLE
Customised helm chart implementing local volumes for kubernetes

### ISSUE THREAD

**Issue by directsahan** [helm/helm#11158]
Hi All,

Good day and hope you are doing fine. For a customised project I'm using microk8s and I have clustered the system using 3 nodes. So it is a 3 nodes microk8s cluster. I will explain the assistance I need in point form. Hope that will help to decode.

- I'm deploying (via helm charts) 2 elastic search pods to the cluster. 7.17.3 version. The elastic search cluster never got initialised because of underlying storage provisioner allocation method issue. None of the pods were getting up. Then I investigated and found out that the elastic search was using "microk8s-hostpath" as the storage class in the values.yaml of the es helm chart.
- Further when I checked online documentation it was said that "hostpath" storage provisioner is not suitable for cluster k8s environments. Then the options were to use a NFS or local-storage for me. If I introduce NFS I will have to introduce mode automation code because all needs to be automated.
- Then I decided to write a complete customised helm chart (with templates) to facilitate underlying storage (storageclass, pv and pvc) for the elastic search pods using local storages method. 
- But the blocker that I'm facing is when using local storage it is tightly coupled with Node affinity and I have to provide a node name in the values section. Therefore somehow I need to inject the node name in to the values section dynamically taking random participant node from the cluster. I can share the helm chart to have a look if requested.
- Is there any solution for my blocker? Thanks.

**Comment by joejulian** [comment]
This was answered and there's been no further follow up by the issue creator. Closing.
