### ISSUE TITLE
Please introduce error types for error messages in source code 

### ISSUE THREAD

**Issue by sophsoph321** [helm/helm#11156]
Hi, 
I'm part of the team at Microsoft that works on Arc for Kubernetes. One of our codebases written in go lang leverages helm library functions and we're exposing the error messages that the helm source code returns, to our customers. Currently, we are parsing the helm error messages before returning the error to our customers. 
For example, for the helm error `"rendered manifests contain a resource that already exists. Unable to continue with update: Secret "azuremlfessl"in namespace "azureml"exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name"must equal "trainingakscompute": current value is "inferencecompute"`, we're returning the following to the customer: 
```
Error: Extension Upgrade failed due to a resource already existing in your cluster 
failed to upgrade chart from path [] for release [trainingakscompute] : err [rendered manifests contain a resource that already exists. Unable to continue with update: Secret "azuremlfessl"in namespace "azureml"exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name"must equal "trainingakscompute": current value is "inferencecompute"] 
Recommendation:  
Manually delete the existing resource on your cluster and try installation again. To delete the existing resource, run the following command: kubectl delete <resource type> -n <namespace name> <resource name>.
```
For this example, the way we parse the helm error is that we check whether the sentence "rendered manifests contain a resource that already exists" is present in the error string. The problem with parsing the helm error messages this way is that we're making assumptions of a free-formed string and our current approach could break if you guys, the helm team, decide to change/re-word your error messages. 

Please add Error Types along with your error messages, so that we can rely on the error types instead of the having to parse the error messages that helm returns.

**Comment by bacongobbler** [comment]
Go commonly uses [error types for type checking](https://earthly.dev/blog/golang-errors/). We use this across the Helm codebase wherever we can for strict error type checking. However, that doesn't work for clients written in other programming languages.

Please see [the contributing guide](https://github.com/helm/helm/blob/main/CONTRIBUTING.md#proposing-an-idea) for proposing new ideas to the project. Something like "standard error codes" would likely require coordination across several projects, as Helm would have to

- change its error messages to report error codes
- document what each error code means, and what context it should be used
- explain how clients should consume and/or report these error messages.

If this sounds interesting to you, please feel free to [write a HIP](https://github.com/helm/community/tree/main/hips). Once that's accepted, you can work on a reference implementation.

**Comment by sophsoph321** [comment]
@bacongobbler If ErrorTypes are more commonly used in go lang as opposed to error codes, my team is also fine with introducing ErrorTypes in Helm. Would we still need to write a HIP? Could you also give an example where ErrorTypes wouldn't work for clients written in other programming languages?

**Comment by sophsoph321** [comment]
@bacongobbler I attended the Helm developer call earlier today and we decided that since we're going to add error types for the error message strings in the Helm source code as opposed to introducing error codes, a HIP wouldn't be necessary. I'll be starting an implementation once I have the bandwidth to take on this task.

**Comment by karenhchu** [comment]
Closing this per Sophie's request; she will re-open the issue when she starts work on it.

**Comment by bentito** [comment]
Was this ever picked up again in something that perhaps isn't linked here?

It still seems pretty useful to people making programmatic use of Helm.
