### ISSUE TITLE
Add `helm test --set` to allow passing in custom variables

### ISSUE THREAD

**Issue by dsgnr** [helm/helm#11163]
There are occasions where it would be super nice to be able to set variables dynamically for `helm test`. For example, authentication tokens with a short TTL.

With `helm upgrade/install` we have the option to use `--set` to override variables used in the templates, but `helm test` currently does not have this option.

Use case:
User deploys Helm chart
User wants to perform integration testing, but needs to inject their identity token into the environment.
User wants to run `helm test <my_chart> --set TOKEN=<foo>`

Alternatively, if there is a way to specify a variable in the template that can be injected from a host environment variable (or even call a Helm plugin) that would be fantastic.

This would be particularly useful where developers and service accounts do not receive a fixed authentication token.

**Comment by yxxhero** [comment]
PR is welcome @dsgnr

**Comment by YarikRevich** [comment]
Hello, I'd like to work on your issue

**Comment by joejulian** [comment]
The tests are templated at the time of the chart installation and stored in the release secret. Could you just set the token during the install?

```
helm install my_release my_chart --set TOKEN=foo
helm test my_release
```
