### ISSUE TITLE
Helm upgrade fails due to admission webhook failure

### ISSUE THREAD

**Issue by brysk** [helm/helm#11176]
I have ingress-nginx controller deployed inside my cluster and trying to upgrade a very simple helm chart. There's only one resource created by this chart - ingress. I made a simple change inside the values and as a result of this change I'm expecting to get the same Ingress resource created but with just a different name. It looks like helm is trying to create the resource first causing the following:

`Error: UPGRADE FAILED: failed to create resource: admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: host "demostore.example.com" and path "/app" is already defined in ingress default/demostore-ingress`

So it's trying to create the resource, webhook is called and fails. Otherwise nginx would not be valid due to duplicated host definition. 

Shouldn't helm upgrade delete the existing resource first and only then try to create new resource? I know it's now aware of existing webhook admission and its also safer to create the resource first, not delete. I'm wondering if there's any way how this can be improved?

Output of `helm version`:

`version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.18.2"}`

Output of `kubectl version`:

`Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:38:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"5a97ee6d15525f6e4a1c2646bf1dfd2ebd5220b5", GitTreeState:"clean", BuildDate:"2022-06-15T04:26:33Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

**Comment by yxxhero** [comment]
@brysk Can you provider a example for this?

**Comment by joejulian** [comment]
No response since July.

**Comment by zhanghaohao** [comment]
I have the same problem now, helm version and kubectl version is the same as @brysk commented above.
As my knowledge for Helm is when `helm upgrade` is performed, helm add the existing resources which is  not in current resource list to the toBeDeleted group, and helm will delete these resources first, then upgrade resources which have already existed in k8s cluster.

For the scenario, since the upgraded ingress name is different from the ingress name existed in cluster, the existed ingress should be deleted by Helm first, then new ingress will created.
For other resource type like Service/Deployment, the result is what we expected, so the question is why ingress behave different ?

**Comment by wujunwei** [comment]
> helm will delete these resources first, then upgrade resources which have already existed in k8s cluster.

During `helm upgrade`, helm will generate `target release` and `original release` , check first `target` for something to update (by three-way-merge patch) or create and then compare  two release for  something to delete.

So when modifying the names of resources that may conflict, a conflict will be reported. like nodePort-service , ingress.

Why didn't Helm choose to delete the resource first ?
If  we delete resource first such as deployment, pod will be deleted also, API services provided by the pod will be interrupted until a new deployment is created ( Considering the launch time of the new pod, may be few seconds) which is intolerable in most cases. I think this should be considered when making a helm package.

**Comment by atayl16** [comment]
I'm going to put this here in case it helps someone in the future. I needed to run `kubectl -n demostore delete ingress routes-rewrite-app` to fix this where `demostore` is your namespace and `app` is the route.
