### ISSUE TITLE
helm uninstall  is fail

### ISSUE THREAD

**Issue by zsdyx** [helm/helm#11191]
helm uninstall prerequisites datahub/datahub-prerequisites
 
 error info:
Error: uninstall: Release not loaded: prerequisites: query: failed to query with labels: Get "https://192.168.49.2:8443/api/v1/namespaces/default/secrets?labelSelector=name%3Dprerequisites%2Cowner%3Dhelm": stream error: stream ID 3; INTERNAL_ERROR; received from peer
[root@VM-4-16-centos ~]# helm uninstall prerequisites datahub/datahub-prerequisites  --wait --timeout 10m0s --debug
Error: uninstall: Release not loaded: prerequisites: query: failed to query with labels: the server was unable to return a response in the time allotted, but may still be processing the request (get secrets)
helm.go:84: [debug] the server was unable to return a response in the time allotted, but may still be processing the request (get secrets)
query: failed to query with labels
helm.sh/helm/v3/pkg/storage/driver.(*Secrets).Query
        helm.sh/helm/v3/pkg/storage/driver/secrets.go:125
helm.sh/helm/v3/pkg/storage.(*Storage).History
        helm.sh/helm/v3/pkg/storage/storage.go:156
helm.sh/helm/v3/pkg/action.(*Uninstall).Run
        helm.sh/helm/v3/pkg/action/uninstall.go:72
main.newUninstallCmd.func2
        helm.sh/helm/v3/cmd/helm/uninstall.go:56
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.4.0/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.4.0/command.go:974
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.4.0/command.go:902
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
        runtime/proc.go:255
runtime.goexit
        runtime/asm_amd64.s:1581
uninstall: Release not loaded: prerequisites
helm.sh/helm/v3/pkg/action.(*Uninstall).Run
        helm.sh/helm/v3/pkg/action/uninstall.go:74
main.newUninstallCmd.func2
        helm.sh/helm/v3/cmd/helm/uninstall.go:56
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.4.0/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.4.0/command.go:974
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.4.0/command.go:902
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
        runtime/proc.go:255
runtime.goexit
        runtime/asm_amd64.s:1581
[root@VM-4-16-centos ~]#  query: failed to query with labels: the server was unable to return a response in the time allotted, but may still be processing the request (get secrets)
-bash: syntax error near unexpected token `('

**Comment by yxxhero** [comment]
@zsdyx Please check your k8s network. Thanks very much.

**Comment by joejulian** [comment]
This has been answered.
