### ISSUE TITLE
no such file or directory helm v3

### ISSUE THREAD

**Issue by johnfelipe** [helm/helm#11190]
```
root@felipe:~# helm install -f packages/ops/configs/redis-values.yaml dev-redis redis/redis
Error: INSTALLATION FAILED: open packages/ops/configs/redis-values.yaml: no such file or directory

```

how solve this?

**Comment by yxxhero** [comment]
@johnfelipe Are you sure the `packages/ops/configs/redis-values.yaml` exist?

**Comment by johnfelipe** [comment]
im in root path of my linux host
but im trying to install with helm redis in amazon EKS, wich command do i need put in putty for `packages/ops/configs/redis-values.yaml`
im using `helm repo add redis https://charts.bitnami.com/bitnami`

sorry for noob question but im lost here

**Comment by yxxhero** [comment]
@johnfelipe anything else I can help you?

**Comment by johnfelipe** [comment]
> im in root path of my linux host but im trying to install with helm redis in amazon EKS, wich command do i need put in putty for `packages/ops/configs/redis-values.yaml` im using `helm repo add redis https://charts.bitnami.com/bitnami`
> 
> sorry for noob question but im lost here

???

**Comment by yxxhero** [comment]
```shell
helm repo add bitnami https://charts.bitnami.com/bitnami
helm install dev-redis bitnami/redis --create-namespace --namespace dev-redis -f packages/ops/configs/redis-values.yaml 

```

**Comment by johnfelipe** [comment]
```
root@felipe:~# helm repo add bitnami https://charts.bitnami.com/bitnami
"bitnami" already exists with the same configuration, skipping
root@felipe:~# helm install dev-redis bitnami/redis --create-namespace --namespace dev-redis -f packages/ops/configs/redis-values.yaml
Error: INSTALLATION FAILED: open packages/ops/configs/redis-values.yaml: no such file or directory

```

**Comment by yxxhero** [comment]
```
ls packages/ops/configs/redis-values.yaml
```

**Comment by johnfelipe** [comment]
```
root@felipe:~# ls packages/ops/configs/redis-values.yaml
ls: cannot access 'packages/ops/configs/redis-values.yaml': No such file or directory

```

**Comment by yxxhero** [comment]
The error is obvious. Your file doesn't exist. Is there any problem

**Comment by johnfelipe** [comment]
> im in root path of my linux host but im trying to install with helm redis in amazon EKS, wich command do i need put in putty for `packages/ops/configs/redis-values.yaml` im using `helm repo add redis https://charts.bitnami.com/bitnami`
> 
> sorry for noob question but im lost here

then how can continue steps for install?
im using commands normally, may be do i need put another setting?
helm version downgrade or something?

**Comment by yxxhero** [comment]
@johnfelipe You should put a exist file. I can't understand your mean.

**Comment by johnfelipe** [comment]
steps:

```
aws --version
aws-cli/2.7.20 Python/3.9.11 Linux/5.4.0-110-generic exe/x86_64.ubuntu.20 prompt/off

```

```
eksctl version
0.107.0
```

```
uname -a
Linux felipe 5.4.0-110-generic #124-Ubuntu SMP Thu Apr 14 19:46:19 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```

```
kubectl version --client
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4

```

i create cluster in amazon

`eksctl create cluster -f cluster.yaml`


```
kubectl describe configmap -n kube-system aws-auth
Name:         aws-auth
Namespace:    kube-system
Labels:       <none>
Annotations:  <none>

Data
====
mapRoles:
----
- groups:
  - system:bootstrappers
  - system:nodes
  rolearn: arn:aws-cn:iam::543317460867:role/eksctl-xrengineprod-nodegroup-mng-NodeInstanceRole-YV0R85NARKMM
  username: system:node:{{EC2PrivateDNSName}}
- groups:
  - system:bootstrappers
  - system:nodes
  rolearn: arn:aws-cn:iam::543317460867:role/eksctl-xrengineprod-nodegroup-ng-NodeInstanceRole-6S7GHCHY8U3
  username: system:node:{{EC2PrivateDNSName}}

mapUsers:
----
[]


BinaryData
====

Events:  <none>

```

```
root@felipe:~# kubectl get nodes
NAME                                                STATUS   ROLES    AGE   VERSION
ip-192-168-55-116.cn-northwest-1.compute.internal   Ready    <none>   11h   v1.22.9-eks-810597c
ip-192-168-61-159.cn-northwest-1.compute.internal   Ready    <none>   11h   v1.22.9-eks-810597c
```

helm repo add agones https://agones.dev/chart/stable

"agones" has been added to your repositories

helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx

"ingress-nginx" has been added to your repositories

helm repo add redis https://charts.bitnami.com/bitnami

"redis" has been added to your repositories

helm repo add xrengine https://helm.xrengine.io/

"xrengine" has been added to your repositories

helm repo update

```
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "xrengine" chart repository
...Successfully got an update from the "ingress-nginx" chart repository
...Successfully got an update from the "agones" chart repository
...Successfully got an update from the "redis" chart repository
Update Complete. ⎈Happy Helming!⎈
```
when i want install redis show me this error of this issue

**Comment by yxxhero** [comment]
@johnfelipe What error?

**Comment by johnfelipe** [comment]
> ```
> root@felipe:~# ls packages/ops/configs/redis-values.yaml
> ls: cannot access 'packages/ops/configs/redis-values.yaml': No such file or directory
> ```

this one

**Comment by yxxhero** [comment]
@johnfelipe no such file. can you create a new one?

**Comment by hickeyma** [comment]
@johnfelipe The error you are getting is because you are specifying a [values file](https://helm.sh/docs/chart_template_guide/values_files/) during the install and the file does not exist. 

> but im trying to install with helm redis in amazon EKS, wich command do i need put in putty for packages/ops/configs/redis-values.yaml

Suggest checking with the documentation in EKS or follow the [chart doc](https://github.com/bitnami/charts/tree/master/bitnami/redis).

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!
