### ISSUE TITLE
Yaml anchors in subcharts

### ISSUE THREAD

**Issue by Diliz** [helm/helm#11207]
Hello!

Output of `helm version`:
```
ersion.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.17.5"}
```

Output of `kubectl version`:
```
Client Version: v1.24.1
Kustomize Version: v4.5.4
Server Version: v1.23.5+3afdacb
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Any

## Current Behaviour:

The child template:
```
name: {{ .Values.name }}
some-attribute-using-name: {{ .Values.some-attribute-using-name }}
```
Parent Values:
```
subchart-alias:
 name: &name toto
```
Child values:
```
name: &name tata
some-attribute-using-name: *name
```

When templating parent chart:
```
name: toto
some-attribute-using-name: tata
```

## Expected behaviour:

When templating parent chart:
```
name: toto
some-attribute-using-name: toto
```

## Proposal

The problem: I think that each subcharts values are being rendered before being merged at some point.
One solution: It would be cool/ok if the top chart would serve as a base, then merge all the values, then render it.

Hard part of it which can fix the cons bellow: Anchors should be aliased if we don't want failures when using multiple times the same anchor in multiple subcharts.

## Pros

This would simplify the use of shared values by using yaml default behaviour.
This would allow smaller root values files without the need to override too much variables in it.

## Cons

As well as the helpers, this can lead to failures when using the same subchart multiple times or if multiple subcharts uses the same anchors.

## Why

Sometimes/usually, you don't control the lifecycle of the subchart you're using, it's maintained by somebody else than you, so you can't use values variables in the values file itself to overwrite , so usually we use yaml anchors to do this.

A real world example would be to have an application chart, using custom subcharts with custom default values for subsubcharts, and if you want to deploy your application with different names, ports, etc, (for any reason), and the subsubcharts doesn't allow it by setting global values:
- you have to use kustomize or any other tool that'll do this to target everything you want to override
- OR you have to change aaaaaaalll the values that use the same original value in subsubcharts in the root parent chart, making your application chart values bigger than needed

## Conclusion

I have not deep dived helm code, so I don't know how this values files are managed, but even if the go yaml lib is used at some point, helm have it's own logic for gathering/reading/rendering the multiple values files.

Thanks for your support,
Diliz

**Comment by PengWang-SMARTM** [comment]
I came here for the same reason that the anchor behavior is slightly different from what I thought. I searched the issue list, and found Issue [9558 ](https://github.com/helm/helm/issues/9558) explains why there is no overriding anchor very well.

My current "workaround" is, to the example above, coping the the config again in the parent values.yaml so it looks like:
```
subchart-alias:
  name: &name toto
  some-attribute-using-name: *name
```

Certainly, I also feel it would be nice to allow overriding anchor, although it appears not an easy task.

The cons mentioned above may not be a real issue because, for each subchart instance, there is only one parent/grandparent in the chain.

**Comment by joejulian** [comment]
Happy to have a contribution to address this. Probably should start with a [HIP](https://github.com/helm/community/blob/main/hips/hip-0001.md) also take a look at the [contributing](https://github.com/helm/helm/blob/main/CONTRIBUTING.md) doc.

**Comment by joejulian** [comment]
Looking back at this (thanks stale bot), I realize it's not possible. The yaml parser happens on reading the values file. The anchors are resolved by the yaml parser and helm never sees the anchors.

To do this any differently would require a rewrite. Maybe bring it up again when planning begins for helm 4.

**Comment by PengWang-SMARTM** [comment]
> 

@joejulian 
I don't really know what's exactly behind the scenes. If value yaml files are merged together before evaluating the anchor/alias, then there is a chance to override the anchor. Otherwise, it's impossible (to me).
