### ISSUE TITLE
Invalid reference format with charts containing space in name

### ISSUE THREAD

**Issue by jonathan-boudreau-work** [helm/helm#11200]
Steps to reproduce:
- In Chart.yaml, specify a name with a space, e.g., `sample chart`
- Package the chart
- Push to a registry, e.g., `sample chart-1.1.3.tgz oci://localhost:5001/sample-charts`

Expected result: The chart is now available in the registry. Or a descriptive error message is given back.
Actual result: I get a cryptic `invalid reference format` error.

Output of `helm version`:
```
version.BuildInfo{Version:"v3.9.2", GitCommit:"1addefbfe665c350f4daf868a9adc5600cc064fd", GitTreeState:"clean", GoVersion:"go1.18.4"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-19T15:39:43Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AKS

**Comment by yxxhero** [comment]
@jonathan-boudreau-work try to 
```
"sample chart-1.1.3.tgz" oci://localhost:5001/sample-charts
```

Also, why use spaces in name?

**Comment by jonathan-boudreau-work** [comment]
Because normally you'd place a space between two words.

**Comment by yxxhero** [comment]
@jonathan-boudreau-work you can use samplechart. or PR is welcome. Thanks very much.

**Comment by jonathan-boudreau-work** [comment]
I'm not familiar with go, just wanted to at least report it since I wasted a lot of time on figuring this out.

**Comment by yxxhero** [comment]
@jonathan-boudreau-work Thanks very much.

**Comment by bacongobbler** [comment]
https://helm.sh/docs/chart_best_practices/conventions/#chart-names

While it isn't explicitly listed in that document, spaces in the chart name are not accepted by Helm. This is because Go's text/template system runs into issues when variable names contain spaces or underscores. Use dashes instead.

In your case, `sample chart` should be renamed to `sample-chart`.

Thanks.

**Comment by bacongobbler** [comment]
Looking more closely at the OP, I noticed you were able to package the chart. If `helm package` allowed you to package the chart, that should be considered a bug.

Re-opening. Please feel free to submit a pull request to fix this behaviour. We'd welcome the help.

**Comment by jonathan-boudreau-work** [comment]
Yes, I was able to package it without any error message. Its only when I push to the registry that I get an error.
