### ISSUE TITLE
Unexpected behavior of atomic when brand new release is installed

### ISSUE THREAD

**Issue by wasker** [helm/helm#11203]
Output of `helm version`: version.BuildInfo{Version:"v3.9.2", GitCommit:"1addefbfe665c350f4daf868a9adc5600cc064fd", GitTreeState:"clean", GoVersion:"go1.17.12"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8", GitCommit:"bd30c9fbc8dc9668d7ab4b0bd4fdab5c929c1ad7", GitTreeState:"clean", BuildDate:"2022-06-21T17:15:16Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

Repro:

1. Assume there's no namespace "myns".
2. `helm upgrade myrelease mychart --create-namespace --install --atomic --namespace myns --set app.image.repository=mycr.azurecr.io/myrepo --set-string app.image.tag=DOESNTEXIST`
3. `helm upgrade myrelease mychart --create-namespace --install --atomic --namespace myns --set app.image.repository=mycr.azurecr.io/myrepo --set-string app.image.tag=STILLDOESNTEXIST`

(2) results in helm immediately returning with indication of success:

```
Release "myrelease" does not exist. Installing it now.
NAME: myrelease
LAST DEPLOYED: Thu Aug  4 13:16:11 2022
NAMESPACE: myns
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

However, kubectl get pods paints a different picture:

```
NAME                                         READY   STATUS             RESTARTS   AGE
pod/myrelease-694ffdd4b-cw9z2   0/1     ImagePullBackOff   0          8m16s
pod/myrelease-694ffdd4b-t662x   0/1     ImagePullBackOff   0          8m31s 
```

(3) results in helm attempting deploy a new version, but now it waits for something to succeed, before ultimately failing with an error `Error: UPGRADE FAILED: an error occurred while rolling back the release. original upgrade error: timed out waiting for the condition: release myrelease failed: timed out waiting for the condition`.

My expectation of an atomic operation would be that (2) would fail to deploy, as (3) does.

**Comment by yxxhero** [comment]
@wasker PR is welcome.
