### ISSUE TITLE
Advice on switching to helm on existing non-helm app

### ISSUE THREAD

**Issue by patrik93** [helm/helm#11219]
Hi, 

I'm currently working on a helm transition from regular manifest files, and I wonder how the actual transition should look like. I did not find any guide, description about how to actually install on a cluster where I already have a running and operating application. When i try to install (or even dry-run it) i have this error message:
`Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: PersistentVolumeClaim "pvc" in namespace "my-namespace" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "my-app"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "default"`

I understand that, helm cannot overwrite resources which was not created by it. 

Could you help me out with some best practices and tips on this topic, please? Is there any other proper way other then deleting the old manifest type of application and installing the helm chart?

**Comment by bormm** [comment]
It's unclear what your expectations/requirements are. 

Do you want to run the helm based deployment in parallel with the other one until you finished creating the helm chart? You could use a separate namespace for that if you have only resources that are encapsulated in an namespace.

Or do you want to be able to update the plain manifest deployment with a helm deployment? I think that is dangerous, because how did you know your helm deployment works correctly on a fresh cluster?

I would not put any effort on trying get helm linked to a previous plain deployment.

**Comment by patrik93** [comment]
First of all, thanks for you help. Let me answer the questions below: 

> Do you want to run the helm based deployment in parallel with the other one until you finished creating the helm chart? You could use a separate namespace for that if you have only resources that are encapsulated in an namespace.

This case is clear, I can test it in a separated namespace as you mentioned or even a whole new environment. 
 
> Or do you want to be able to update the plain manifest deployment with a helm deployment? I think that is dangerous, because how did you know your helm deployment works correctly on a fresh cluster?
> 
> I would not put any effort on trying get helm linked to a previous plain deployment.

I meant for example when the first part is done, testing works in a separated namespace and I can be sure everything is working. I reached that point when I'm able to switch - or maybe install is a better word -  to helm type of deployment instead of the manifest in a staging or production environment where is more intolerant for that time when I delete the previous manifest deployed resources and install the helm chart to the cluster. 

I hope this helps to let you understand my situation.

**Comment by kfox1111** [comment]
So, are you asking as:
* a developer of said static manifests / helm charts, in order to make transitioning from one type of deployment to the other for your users/yourself?
* a user of some software that has both static manifests and helm charts and you'd like to switch between them?

The former could be done with enough effort invested in testing / keeping things well in sync I think. The latter I think is way too hard in general and probably to the point of playing with fire.

**Comment by patrik93** [comment]
Hi @kfox1111,

I'm asking this as a developer. Forgive me, I'm fairly new to helm and I don't have the overview what this process means when I decide on the following:
 _My helm chart is tested, everything is working as the static manifest. Now its time to install the helm chart to my production cluster. I have this error which does not allow me to overwrite the existing static deployments (for a very good reason), how can I resolve this?_ 

Is there any better solution than `kubectl delete -f myapp.yml` and after this `helm install my-app-chart`?

**Comment by kfox1111** [comment]
So, you created a chart, then did something like helm template <other options>   then took the result and loaded it in as a static manifest into production. Then now you want to manage it more like a proper helm release via helm upgrade? (just trying to be very very clear to prevent bad advise)

**Comment by patrik93** [comment]
The first part is not correct, i already have an application deployed with static manifests, and I want to replace it with a helm chart of the same application. The second part is correct, I would like to manage my already existing application (but exists with static files) with a helm chart. I already made the helm chart.

**Comment by kfox1111** [comment]
The farther apart the objects are that were statically loaded into the cluster and what is in the helm chart, the harder to do safely/more risky it will be. ideally you would do:
helm template <releasename> <chartname> -f <your custom values> -n <namespace> | kubectl diff -f -
and it would show no changes. If that is the case, setting the helm owner annotations/labels on the objects in the cluster and helm upgrading over it, with the exact same settings, should be ok...

as always though, testing on a test instance before doing it in prod is highly recommended.

**Comment by patrik93** [comment]
Thanks for your effort to make it clear for me. I think I'm fine know!
