### ISSUE TITLE
Predicted release dates from the release notes seem incorrect

### ISSUE THREAD

**Issue by crenshaw-dev** [helm/helm#11218]
The [3.9.0 release notes](https://github.com/helm/helm/releases/tag/v3.9.0) say 3.9.1 was to be released on June 8, 2022. 3.9.1 was released on July 13, 2022. 

The [3.9.1 release notes](https://github.com/helm/helm/releases/tag/v3.9.1) say 3.9.2 should be expected on August 10, 2022. It was released early on July 21, 2022.

The [3.9.2 release notes](https://github.com/helm/helm/releases/tag/v3.9.2) say we can expect 3.9.3 on August 10, 2022.

Should these predictions just be dropped from the release notes, to avoid confusion?

**Comment by joejulian** [comment]
I don't have an answer to whether they should or not, but release dates are governed by https://github.com/helm/community/blob/main/hips/hip-0002.md
