### ISSUE TITLE
how to use Release.IsInstall

### ISSUE THREAD

**Issue by xifour** [helm/helm#11211]
Output of `helm version`:
3.8.1
Output of `kubectl version`:
1.22.5

i just use "helm install"  first to install.
then i will use kubectl edit cm to change the content of my cm.
so this cm may be different with the cm of templates in my helm.
i try to use the Release.IsInstall to distinguish the action between install and upgrade 
i wanna when i use "helm upgrade" ,it can unchange my cm ,not use cm in my helm 

what can i do 

this is the content of my configmap.yaml
{{- if "Release.IsUpgrade" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tmp.fullname" . }}
data:
  {{- (.Files.Glob "files/*").AsConfig | nindent 2 }}
{{- end }}

**Comment by yxxhero** [comment]
@xifour I think you should use GIT and other tools to manage your helm resources. This is a better way. Thanks very much.
