### ISSUE TITLE
Unable to use .Values.global.environment in values passed to range template?

### ISSUE THREAD

**Issue by v1ferrarij** [helm/helm#11217]
Hello,

I do not know even this is even possible, but if anyone would be able to advise if so that would be great.

I am trying to pass Values.global.environment to another value which is consumed in a range loop.

so here is my template:
```
  triggers:
    {{- range .Values.triggers }}
      {{- $data := dict "root" $ "trigger" . }}
      {{- if eq .type "azure-servicebus" }}
{{- include "function.servicebus" $data | indent 4 }}
      {{- end }}
    {{- end }}

{{/* metadata for an Azure Service Bus Trigger */}}
{{- define "function.servicebus" }}
- type: azure-servicebus
  metadata:
    {{- if .root.Values.triggerAuth.enabled }}
    namespace: {{ .trigger.serviceBusName }}
    {{- end }}
    {{- if .trigger.queueName }}
    queueName: {{ .trigger.queueName }}
    {{- else }}
    topicName: {{ .trigger.topicName }}
    subscriptionName: {{ .trigger.subscriptionName }}
    {{- end }}
    {{- if not .root.Values.triggerAuth.enabled }}
    connectionFromEnv: {{ .trigger.connectionFromEnv }}
    {{- end }}
    messageCount: {{ .trigger.messageCount | quote }}
  {{- if .root.Values.triggerAuth.enabled }}
  authenticationRef:
{{- include "function.trigger-auth-name" .root | indent 4 }}
  {{- end }}
{{- end }}
```
passing the value serviceBusName in values.yaml:
```
####
global:
  environment: dev
triggers:
- type: azure-servicebus
  serviceBusName: "sbus-{{ tpl .Values.global.environment $ }}" 
####
```
However, the value get's passed as a literal, so if I was to inspect the YAML created from this chart the value of the serviceBusName is

"sbus-{{ tpl .Values.global.environment $ }}" 

instead of

sbus-dev

I know this is something to do with the way the chart is being compiled, as passing Values.global.environment to any other value which is not a range loop works fine.

Thanks

**Comment by joejulian** [comment]
Values are not processed as templates so no, that won't work.

All I can think of is adding another field:
```
triggers:
  - type: azure-servicebus
    serviceBusNameRef: ["global","environment"]
```

Then using dig you could do something along the lines of (this is untested and has at least one assumption):
```
{{- $default := .serviceBusName -}}
{{- $result := $values -}}
{{- $key := range .serviceBusNameRef -}}
{{- $result = dig $key $default $result -}}
{{- end -}}
{{ $result }}
```
