### ISSUE TITLE
Can Chart.yaml support variables with values.yaml?

### ISSUE THREAD

**Issue by WB-jastme** [helm/helm#11222]
Output of `helm version`:  version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.6"}

Output of `kubectl version`:  
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.11-aliyun.1", GitCommit:"88d5e8b", GitTreeState:"", BuildDate:"2021-10-25T13:55:31Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.11-aliyun.1", GitCommit:"88d5e8b", GitTreeState:"", BuildDate:"2021-10-25T13:52:50Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
aliyun ack

```
NAME  	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART       	APP VERSION
eureka	default  	1       	2022-05-19 14:24:14.312923848 +0800 CST	deployed	eureka-0.1.0	1.16.0     
```
I want to customize appVersion, but i can't use  variables  in Chart.yaml with values.yaml .

values.yaml
```
appVersion:  test
```
Chart.yaml
```
appVersion: {{ .Values.appVersion }}
```

**Comment by joejulian** [comment]
Neither Chart.yaml nor values.yaml are parsed by the template engine. This is not supported.
