### ISSUE TITLE
Warn or fail when duplicate blocks are in values.yaml

### ISSUE THREAD

**Issue by cfldtn** [helm/helm#11223]
I'm using Helm as follows:

```
version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}
```

We just lost a chunk of time with an issue involving a values.yaml like this:

```
global:
  important: settings

other:
  stuff: here

global:
```

Needless to say, the trailing line saying `global:` was a mistake; the file was big enough that we didn't spot it for quite some time.

Helm appears to interpret this as the final `global:` being an empty block, thus the first block with the important settings in it got ignored.

I believe this is probably how YAML is supposed to work (sigh) but would it be acceptable for Helm to at least warn users when duplicate blocks occur like this? Especially if the "winning" block is empty.

**Comment by cfldtn** [comment]
If this is an acceptable idea we may be able to work on a patch, but let me know before we do.

**Comment by hickeyma** [comment]
@cfldtn Thank you for raising this issue.

There are 2 ways to look at this:

1. Helm should account for this as the empty `global` unsets any potential setting from previous. It must be a human error. OR
2. This is valid YAML and maybe a user wants to unset this for whatever reason

I would like to other community and maintainers opinions if this is something we want or should restrict.
