### ISSUE TITLE
"include" always returns a string, regardless of the actual type

### ISSUE THREAD

**Issue by joejulian** [helm/helm#11231]
https://github.com/helm/helm/blob/3d1bc72827e4edef273fb3d8d8ded2a25fa6f39d/pkg/engine/engine.go#L112-L125

I noticed when I put some complex logic in a `define` and referenced it in an `if`, it was always treating the result as true.
```yaml
{{ define "not-true"}}
{{ false }}
{{ end }}
{{ if include "not-true" }}
BOO!
{{ else }}
YAY!
{{ end }}
```
```text
BOO!
```

This is because the `include` function always returns a string.

There is no fix for this function that would be backward compatible, but perhaps we could add an additional function that works like json's decodeState.literalStore to allow types to carry through.

**Comment by phil9909** [comment]
Unfortunately I don't think this is possible with go templates. [`ExecuteTemplate`](https://pkg.go.dev/text/template#Template.ExecuteTemplate) just writes to a buffer and any type information is lost.

Any idea how this could work?

As a workaround you can use `(include "..." .) | fromJson`, but this works only for complex types not boolean.
For numbers you can use `atoi`.

**Comment by joejulian** [comment]
Yeah, I built a really hacky workaround.

```
{{- define "complex.logic" -}}
{{- $data := .Values.data -}}
{{- toJson (dict "bool" (and (dig "value1" false $data) (not (empty (dig "value2" "" $data))))) -}}
{{- end -}}
```

```
{{- if (include "complex.logic" . | fromJson).bool }}
```

Which at least tells the reader that the include value being returned is a bool.

Maybe this should be a sprig issue, adding a function that interprets strings as json values, ie. `true` is a bool but `"true"` is a string.

**Comment by joejulian** [comment]
Ok, so it shouldn't be a sprig issue. Looks like there is nobody maintaining that project.

**Comment by joejulian** [comment]
I will look at the sprig fromJson function to see how it works. Maybe it _should_ interpret values in this way, but currently it only interprets maps.
