### ISSUE TITLE
Debugging Templates section in the docs - wrong description. 

### ISSUE THREAD

**Issue by w7089** [helm/helm#11238]
Hi.

`helm template` [docs](https://helm.sh/docs/helm/helm_template/) state that templates are locally rendered.

Whereas, [Debugging Templates docs](https://helm.sh/docs/chart_template_guide/debugging/) state: `helm template --debug` **is a great way to have the server render your templates** which seems wrong.

Should I open pr on the  Debugging Templates section rephrase or I miss  something?

**Comment by sudermanjr** [comment]
My guess is that the `server` language is a holdover from pre-helm3 behavior. My understanding is also that template rendering is done locally. A PR would definitely be appreciated. :-D

**Comment by w7089** [comment]
opened [pr](https://github.com/helm/helm-www/pull/1347)
