### ISSUE TITLE
helm lint output template on error

### ISSUE THREAD

**Issue by patrickviet** [helm/helm#11239]
So I made a mistake in my template, and it didn't pass lint.
The error was
```[ERROR] templates/ingress.yaml: unable to parse YAML: error converting YAML to JSON: yaml: line 158: did not find expected key```

I'd really really like to see the line 158 of the lint-rendered YAML (and the lines around it too). What would be wonderful would be if I could actually see that output on error. Some kind of option like ```--output-rendered-template-on-error``` that sends it to stderr, stdout, or even a temp file, would be wonderful. And even better if it would maybe only output the specific template that had an error in it

Of course there is ```helm template``` but that doesn't always work for complex templates, and doesn't work the same as helm lint. For example, the 'required' values are not handled the same (helm lint just gives them some placeholder value)

Output of `helm version`: version.BuildInfo{Version:"v3.9.3", GitCommit:"414ff28d4029ae8c8b05d62aa06c7fe3dee2bc58", GitTreeState:"clean", GoVersion:"go1.17.13"}

Output of `kubectl version`: not relevant

Cloud Provider/Platform (AKS, GKE, Minikube etc.): not relevant

**Comment by joejulian** [comment]
How about
```
helm install myrelease mychart --dry-run --ouput yaml
```
