### ISSUE TITLE
"helm template" doesn't set $.Release.Name?

### ISSUE THREAD

**Issue by rehevkor5** [helm/helm#11232]
When using `helm template` with various parameters including `--name-template`, apparently it's not setting `$.Release.Name`. I get this error:

> Error: template: mychart/templates/istio/cert-manager-certificate.yaml:19:6: executing "mychart/templates/istio/cert-manager-certificate.yaml" at <include "ingress.hostname.allurls" .Values.istio.foo>: error calling include: template: mychart/templates/istio/_ingress.tpl:18:5: executing "ingress.hostname.allurls" at <include "ingress.hostname" .>: error calling include: template: mychart/templates/istio/_ingress.tpl:2:4: executing "ingress.hostname" at <$.Release.Name>: nil pointer evaluating interface {}.Name 

Output of `helm version`:

> version.BuildInfo{Version:"v3.9.3", GitCommit:"414ff28d4029ae8c8b05d62aa06c7fe3dee2bc58", GitTreeState:"clean", GoVersion:"go1.17.13"}

Output of `kubectl version`: N/A

Cloud Provider/Platform (AKS, GKE, Minikube etc.): N/A

**Comment by rehevkor5** [comment]
I suspect that the behavior of `$` might be different from what the documentation suggests...

https://helm.sh/docs/chart_template_guide/variables/ says this:

> However, there is one variable that is always global - `$` - this variable will always point to the root context. This can be very useful when you are looping in a range and you need to know the chart’s release name.

Also, https://helm.sh/docs/chart_template_guide/control_structures/#modifying-scope-using-with says this:

> we can use $ for accessing the object Release.Name from the parent scope. $ is mapped to the root scope when template execution begins and it does not change during template execution.

I do not see any explanation of what the "root context" or the "root scope" is? Seems like that should be explained somewhere in the docs? Is it really true that "root context" or "root scope" or "top-level scope" is a global value that doesn't change? To me it is looking like `$` is **not** a global value which never changes, but is instead local to a specific invocation of a named template (via `include` or `template`)...

Also, that's the only place I see the words "root" and "context" being used. Everywhere else in the doc it's referred to as "scope". Also, the docs use both "top-level scope" and "root scope". It would be nice to make the terminology consistent.

**Comment by rehevkor5** [comment]
Aha... it looks like I am not the only one who has been confused about this: https://github.com/helm/helm/issues/7915

Also, it sounds like Helm is relying on gomplate's "Context" functionality? https://docs.gomplate.ca/syntax/#the-context So it seems like it would be better to call it "context" not "scope".

I guess the documentation does need to be updated. I will see if I can take some time to contribute improvements to it...

**Comment by joejulian** [comment]
This is how go templates work. I agree with @rehevkor5 that this would be better handled through a documentation improvement. Please open an issue in [helm-www](https://github.com/helm/helm-www/issues).
