### ISSUE TITLE
get helm failed with checksum error

### ISSUE THREAD

**Issue by haowells** [helm/helm#11246]
Hi Helm support,

I try to install helm on my mac, Is this error means helm tarball corrupted on storage backend ?

haolin@C02D66FAMD6T:~$ curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11156  100 11156    0     0  12876      0 --:--:-- --:--:-- --:--:-- 13002
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /Users/haolin/tc/kc/kubeconfig
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /Users/haolin/tc/kc/kubeconfig
WARNING: "kubernetes-charts.storage.googleapis.com" is deprecated for "stable" and will be deleted Nov. 13, 2020.
WARNING: You should switch to "https://charts.helm.sh/stable" via:
WARNING: helm repo add "stable" "https://charts.helm.sh/stable" --force-update
Helm  is available. Changing from version v3.8.1.
Downloading https://get.helm.sh/helm--darwin-amd64.tar.gz
Verifying checksum... SHA sum of /var/folders/4k/w6v175v15hj32635sgmy0lxh395pf1/T/helm-installer-XXXXXX.A3YmqtTA/helm--darwin-amd64.tar.gz does not match. Aborting.
Failed to install helm
	For support, go to https://github.com/helm/helm.

**Comment by yxxhero** [comment]
@haowells I can't reproduce your issue. Thanks very much. I think that the issue may be network.
