### ISSUE TITLE
GO Package vulnerabilities in helm 3.9.3 release

### ISSUE THREAD

**Issue by harshpan** [helm/helm#11248]
On upgrading our Helm version from 3.8.2 to 3.9.3 we noticed many GO package related vulnerabilities. Please, let us know by when we can expect these to be fixed. 

Output of `helm version`: 3.9.3

Output of `kubectl version`: 1.23.0
[helm_3.9.3_vuln.xlsx](https://github.com/helm/helm/files/9380907/helm_3.9.3_vuln.xlsx)

Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE

**Comment by yxxhero** [comment]
@harshpan PR is welcome. thanks very much.

**Comment by joejulian** [comment]
Wouldn't that be ironic if that attached excel file was, itself, a viral contagion. As a matter of security I do not open MS formatted documents from untrusted sources (not saying you're not worthy of trust, I just don't know you and this is your first issue ever).

If this is a legitimate concern, please file a new issue with sufficient readable text that it can be acted upon.

**Comment by harshpan** [comment]
Thank you i will do that.

Regards
Harsh Pandey

**Comment by harshpan** [comment]
I have created a new issue and listed the Vulnerabilities that came while scanning through GCP GCR vulnerability scanner.

GO Package vulnerabilities in helm 3.9.3 release #11313
