### ISSUE TITLE
Proposal: Add installed/upgraded resource list info 

### ISSUE THREAD

**Issue by astraw99** [helm/helm#11253]
Currently, we got this output when do the `install/upgrade` operation, but without any resource list info.
```
NAME: happy-panda
LAST DEPLOYED: Fri Aug 12 18:17:42 2022
NAMESPACE: default
STATUS: deployed
REVISION: 37
TEST SUITE: None
```

This proposal is to display the installed/upgraded resource list info, as follows:
```
NAME: happy-panda
LAST DEPLOYED: Fri Aug 12 18:17:42 2022
NAMESPACE: default
STATUS: deployed
REVISION: 37
TEST SUITE: None

Installed/Upgraded resources:
ns1/pod1
ns2/deploy2
...
```
`Installed` display all the installed items, `Upgraded` just display the updated items.

**Comment by joejulian** [comment]
This would need to be behind a flag as it changes the output which may break automation that relies on current behavior.

**Comment by astraw99** [comment]
> This would need to be behind a flag as it changes the output which may break automation that relies on current behavior.

Sure, we can add a flag `--show-resources` to achieve it.

If this proposal feature get approval, I will raise a PR, thanks.

**Comment by joejulian** [comment]
If it was me, I'd just create the PR. The core maintainers are all very busy people and giving them the fewest tasks possible usually gets the best results.

**Comment by astraw99** [comment]
OK, got it. I will try.
Thanks.
