### ISSUE TITLE
Reference subchart annotations

### ISSUE THREAD

**Issue by vinibali** [helm/helm#11255]
Hello there!

What would be the way to reference the annotations of a subchart in the umbrella chart?
I would like to print all the annotations from the subchart's Chart.yaml file at the umbrella chart's NOTES.TXT.
So far none of the pages I found, was working. Please note, all my charts are using hypens.

Thanks and best regards

**Comment by vinibali** [comment]
Just to bump this, I assume something like this should work:
```
{{ index .Chart.Annotations "my-subchart" }}
```

**Comment by vinibali** [comment]
I'm still looking for a solution for this scenario.

**Comment by joejulian** [comment]
Try adding this to your NOTES.txt file:

```
{{ . }}
```
so you can see everything you could possibly reference. If it's not in there, you can't reference it.

**Comment by vinibali** [comment]
Thanks @joejulian.
I can see all the needed lines in the output, however it's very scrambled.
How can I figure out how to reference some of those lines? It seems every key-value pair is just separated with one space at the moment.

**Comment by vinibali** [comment]
I just used grep with color to make the output somewhat readable. And it seems that the whole Chart.yaml has no sections to reference it's values. It looks, all the values are listed under the Release section without keys.
I'll try to remove all the sensitive data from the output and share them here:
`map[Capabilities:0xc00083b0e0 Chart:{{company-project-product-clm  [] 0.0.7-1 A Helm chart for deployment [] [0xc00048e420]  v2   v1.0.2 false map[]  [0xc0003f85a0 0xc0003f8630] application} true} Files:map[.helmignore:[35] product-info.yaml:[112] kubeVersion.yaml:[107]] Release:map[IsInstall:true IsUpgrade:false Name:company-project-product-clm-default Namespace:default Revision:1 Service:Helm] Subcharts:map[company-product-cert-manager:map[Capabilities:0xc00083b0e0 Chart:{{company-product-cert-manager *subchart1_chart.yaml_home* [*subchart2_chart.yaml_home*] 0.0.2-1 *description for subchart2*. [cert-manager kube-lego letsencrypt tls] [0xc000848780]  v1   v1.0.0 false map[company-product-cert-manager-bazelbuilder_os:3.45.0-15 company-product-cert-manager-bazelbuilder_image:v0.0.1-202-2 company-product-cert-manager_os:3.45.0-15 company-product-cert-manager_os_sha256:*cheksum* company-product-cert-manager_image:v1.0.0-202-2 company-product-cert-manager_repo_tag:v1.0.0 company-product-cert-manager_repo_url:https://github.com/jetstack/cert-manager]  [] } false} Files:map[.helmignore:[35] company-crd/company-product-cert-manager-crd-0.0.0-1.tgz:[*numbers*] company-product-info.yaml:[112] kubeVersion.yaml:[107]] Release:map[IsInstall:true IsUpgrade:false Name:company-project-product-clm-default Namespace:default Revision:1 Service:Helm] Subcharts:map[] Template:map[BasePath:company-project-product-clm/charts/company-product-cert-manager/templates Name:company-project-product-clm/charts/company-product-cert-manager/templates/NOTES.txt] Values:map[affinity:map[] cainjector:map[affinity:map[] containerSecurityContext:map[] enabled:true extraArgs:[] image:map[pullPolicy:IfNotPresent repository:registry.company.com/proj-project-subchart2-dev/cert-manager-cainjector tag:v1.0.0-202-2] nodeSelector:map[] podLabels:map[] replicaCount:1 resources:map[] securityContext:map[runAsNonRoot:true] serviceAccount:map[automountServiceAccountToken:true create:true] strategy:map[] tolerations:[]] clusterResourceNamespace: containerSecurityContext:map[] extraArgs:[] extraEnv:[] featureGates: global:map[imagePullSecrets:[] leaderElection:map[namespace:default] logLevel:2 networkPolicy:map[enabled:true] podSecurityPolicy:map[enabled:false useAppArmor:true] priorityClassName: pullSecret:docker-registry-credentials rbac:map[create:true] registry:map[url:registry.company.com]] image:map[pullPolicy:IfNotPresent repository:registry.company.com/proj-project-subchart2-dev/cert-manager-controller tag:v1.0.0-202-2] ingressShim:map[] nodeSelector:map[] podLabels:map[] prometheus:map[enabled:true servicemonitor:map[enabled:false interval:60s labels:map[] path:/metrics prometheusInstance:default scrapeTimeout:30s targetPort:9402]] replicaCount:1 resources:map[] securityContext:map[runAsNonRoot:true] serviceAccount:map[automountServiceAccountToken:true create:true] startupapicheck:map[affinity:map[] backoffLimit:4 enabled:true extraArgs:[] image:map[pullPolicy:IfNotPresent repository:registry.company.com/proj-project-subchart2-dev/cert-manager-ctl tag:v1.0.0-202-2] jobAnnotations:map[helm.sh/hook:post-install helm.sh/hook-delete-policy:before-hook-creation,hook-succeeded helm.sh/hook-weight:1] nodeSelector:map[] podLabels:map[] rbac:map[annotations:map[helm.sh/hook:post-install helm.sh/hook-delete-policy:before-hook-creation,hook-succeeded helm.sh/hook-weight:-5]] resources:map[] securityContext:map[runAsNonRoot:true] serviceAccount:map[annotations:map[helm.sh/hook:post-install helm.sh/hook-delete-policy:before-hook-creation,hook-succeeded helm.sh/hook-weight:-5] automountServiceAccountToken:true create:true] timeout:1m tolerations:[]] strategy:map[] tolerations:[] volumeMounts:[] volumes:[] webhook:map[affinity:map[] containerSecurityContext:map[] extraArgs:[] hostNetwork:false image:map[pullPolicy:IfNotPresent repository:registry.company.com/proj-project-subchart2-dev/cert-manager-webhook tag:v1.0.0-202-2] livenessProbe:map[failureThreshold:3 initialDelaySeconds:60 periodSeconds:10 successThreshold:1 timeoutSeconds:1] nodeSelector:map[] podLabels:map[] readinessProbe:map[failureThreshold:3 initialDelaySeconds:5 periodSeconds:5 successThreshold:1 timeoutSeconds:1] replicaCount:1 resources:map[] securePort:10250 securityContext:map[runAsNonRoot:true] serviceAccount:map[automountServiceAccountToken:true create:true] serviceLabels:map[] serviceType:ClusterIP strategy:map[] timeoutSeconds:10 tolerations:[] url:map[]]]] company-project-product-clusterctl:map[Capabilities:0xc00083b0e0 Chart:{{company-project-product-clusterctl *subchart1_chart.yaml_home* [] 0.0.2-1 Provides intent-based Kubernetes cluster lifecycle management functionality with a pluggable architecture [] [0xc0009a8480]  v2   v1.0.2 false map[cluster-api-aws-infrastructure-provider_os:3.45.0-15 cluster-api-aws-infrastructure-provider_repo_tag:v1.0.0 cluster-api-aws-infrastructure-provider_repo_url:https://github.com/kubernetes-sigs/cluster-api-provider-aws.git cluster-api-azure-infrastructure-provider_repo_tag:v1.0.1 cluster-api-azure-infrastructure-provider_repo_url:https://github.com/kubernetes-sigs/cluster-api-provider-azure.git cluster-api_os:3.45.0-15 cluster-api_repo_tag:v1.0.2 cluster-api_repo_url:https://github.com/kubernetes-sigs/cluster-api.git company-project-product-capa-info-init_image:v1.0.0-202-2 company-project-product-capi-info-init_image:v1.0.2-202-2 company-project-product-capz-info-init_image:v1.0.1-202-2 company-project-product-clusterctl_app:v1.1.4 company-project-product-clusterctl_capi_deployer:v0.1 company-project-product-clusterctl_os:3.45.0-15 company-project-product-clusterctl_image:v1.0.2-202-2 company-project-product-clusterctl_kubectl:v1.23.4 company-project-product-clusterctl_kustomize:v4.5.2]  [] application} false} Files:map[.helmignore:[35] company-product-info.yaml:[112] kubeVersion.yaml:[107]] Release:map[IsInstall:true IsUpgrade:false Name:company-project-product-clm-default Namespace:default Revision:1 Service:Helm] Subcharts:map[] Template:map[BasePath:company-project-product-clm/charts/company-project-product-clusterctl/templates Name:company-project-product-clm/charts/company-project-product-clusterctl/templates/NOTES.txt] Values:map[affinity:map[] autoscaling:map[enabled:false maxReplicas:100 minReplicas:1 targetCPUUtilizationPercentage:80] defaultImages:map[clusterctlImage:registry.company.com/proj-project-subchart1-dev/company-project-product-clusterctl:v1.0.2-126-1 coreImages:map[envVarSuffix:map[bootstrap:BOOTSTRAP controlPlane:CONTROL_PLANE core:CORE] image:registry.company.com/proj-project-subchart1-dev/company-project-product-capi-info-init:v1.0.2 name:company-project-product-capi-info-init repositories:map[bootstrap:proj-project-subchart1-dev/cluster-api/kubeadm-bootstrap-controller-amd64 controlPlane:proj-project-subchart1-dev/cluster-api/kubeadm-control-plane-controller-amd64 core:proj-project-subchart1-dev/cluster-api/cluster-api-controller-amd64] tags:map[bootstrap:v1.0.2 controlPlane:v1.0.2 core:v1.0.2]]] fullnameOverride: global:map[leaderElection:map[namespace:LEADERELECTION_NAMESPACE-CHANGETHIS] networkPolicy:map[enabled:true] pullSecret:docker-registry-credentials registry:map[url:registry.company.com]] imagePullSecrets:[] ingress:map[annotations:map[] enabled:false hosts:[map[host:chart-example.local paths:[]]] tls:[]] nameOverride: nodeSelector:map[] podAnnotations:map[] podSecurityContext:map[] providerImages:[map[envVarSuffix:INFRASTRUCTURE_AWS image:registry.company.com/proj-project-subchart1-dev/company-project-product-capa-info-init:v1.0.0 name:aws repository:proj-project-subchart1-dev/cluster-api-aws/cluster-api-aws-controller-amd64 tag:v1.0.0] map[envVarSuffix:INFRASTRUCTURE_AZURE image:registry.company.com/proj-project-subchart1-dev/company-project-product-capz-info-init:v1.0.1 name:azure repository:proj-project-subchart1-dev/cluster-api-azure/cluster-api-azure-controller-amd64 tag:v1.0.1]] replicaCount:1 resources:map[] securityContext:map[] service:map[port:80 type:ClusterIP] serviceAccount:map[annotations:map[] create:true name:] tolerations:[] workload:map[namespace:WORKLOAD_NAMESPACE-CHANGETHIS]]]] Template:map[BasePath:company-project-product-clm/templates Name:company-project-product-clm/templates/NOTES.txt] Values:map[enabled:true company-product-cert-manager:map[affinity:map[] cainjector:map[affinity:map[] containerSecurityContext:map[] enabled:true extraArgs:[] image:map[pullPolicy:IfNotPresent repository:registry.company.com/proj-project-subchart2-dev/cert-manager-cainjector tag:v1.0.0-202-2] nodeSelector:map[] podLabels:map[] replicaCount:1 resources:map[] securityContext:map[runAsNonRoot:true] serviceAccount:map[automountServiceAccountToken:true create:true] strategy:map[] tolerations:[]] clusterResourceNamespace: containerSecurityContext:map[] extraArgs:[] extraEnv:[] featureGates: global:map[imagePullSecrets:[] leaderElection:map[namespace:LEADERELECTION_NAMESPACE-CHANGETHIS] logLevel:2 networkPolicy:map[enabled:true] podSecurityPolicy:map[enabled:false useAppArmor:true] priorityClassName: pullSecret:docker-registry-credentials rbac:map[create:true] registry:map[url:registry.company.com]] image:map[pullPolicy:IfNotPresent repository:registry.company.com/proj-project-subchart2-dev/cert-manager-controller tag:v1.0.0-202-2] ingressShim:map[] nodeSelector:map[] podLabels:map[] prometheus:map[enabled:true servicemonitor:map[enabled:false interval:60s labels:map[] path:/metrics prometheusInstance:default scrapeTimeout:30s targetPort:9402]] replicaCount:1 resources:map[] securityContext:map[runAsNonRoot:true] serviceAccount:map[automountServiceAccountToken:true create:true] startupapicheck:map[affinity:map[] backoffLimit:4 enabled:true extraArgs:[] image:map[pullPolicy:IfNotPresent repository:registry.company.com/proj-project-subchart2-dev/cert-manager-ctl tag:v1.0.0-202-2] jobAnnotations:map[helm.sh/hook:post-install helm.sh/hook-delete-policy:before-hook-creation,hook-succeeded helm.sh/hook-weight:1] nodeSelector:map[] podLabels:map[] rbac:map[annotations:map[helm.sh/hook:post-install helm.sh/hook-delete-policy:before-hook-creation,hook-succeeded helm.sh/hook-weight:-5]] resources:map[] securityContext:map[runAsNonRoot:true] serviceAccount:map[annotations:map[helm.sh/hook:post-install helm.sh/hook-delete-policy:before-hook-creation,hook-succeeded helm.sh/hook-weight:-5] automountServiceAccountToken:true create:true] timeout:1m tolerations:[]] strategy:map[] tolerations:[] volumeMounts:[] volumes:[] webhook:map[affinity:map[] containerSecurityContext:map[] extraArgs:[] hostNetwork:false image:map[pullPolicy:IfNotPresent repository:registry.company.com/proj-project-subchart2-dev/cert-manager-webhook tag:v1.0.0-202-2] livenessProbe:map[failureThreshold:3 initialDelaySeconds:60 periodSeconds:10 successThreshold:1 timeoutSeconds:1] nodeSelector:map[] podLabels:map[] readinessProbe:map[failureThreshold:3 initialDelaySeconds:5 periodSeconds:5 successThreshold:1 timeoutSeconds:1] replicaCount:1 resources:map[] securePort:10250 securityContext:map[runAsNonRoot:true] serviceAccount:map[automountServiceAccountToken:true create:true] serviceLabels:map[] serviceType:ClusterIP strategy:map[] timeoutSeconds:10 tolerations:[] url:map[]]] company-project-product-clusterctl:map[affinity:map[] autoscaling:map[enabled:false maxReplicas:100 minReplicas:1 targetCPUUtilizationPercentage:80] defaultImages:map[clusterctlImage:registry.company.com/proj-project-subchart1-dev/company-project-product-clusterctl:v1.0.2-126-1 coreImages:map[envVarSuffix:map[bootstrap:BOOTSTRAP controlPlane:CONTROL_PLANE core:CORE] image:registry.company.com/proj-project-subchart1-dev/company-project-product-capi-info-init:v1.0.2 name:company-project-product-capi-info-init repositories:map[bootstrap:proj-project-subchart1-dev/cluster-api/kubeadm-bootstrap-controller-amd64 controlPlane:proj-project-subchart1-dev/cluster-api/kubeadm-control-plane-controller-amd64 core:proj-project-subchart1-dev/cluster-api/cluster-api-controller-amd64] tags:map[bootstrap:v1.0.2 controlPlane:v1.0.2 core:v1.0.2]]] fullnameOverride: global:map[leaderElection:map[namespace:LEADERELECTION_NAMESPACE-CHANGETHIS] networkPolicy:map[enabled:true] pullSecret:docker-registry-credentials registry:map[url:registry.company.com]] imagePullSecrets:[] ingress:map[annotations:map[] enabled:false hosts:[map[host:chart-example.local paths:[]]] tls:[]] nameOverride: nodeSelector:map[] podAnnotations:map[] podSecurityContext:map[] providerImages:[map[envVarSuffix:INFRASTRUCTURE_AWS image:registry.company.com/proj-project-subchart1-dev/company-project-product-capa-info-init:v1.0.0 name:aws repository:proj-project-subchart1-dev/cluster-api-aws/cluster-api-aws-controller-amd64 tag:v1.0.0] map[envVarSuffix:INFRASTRUCTURE_AZURE image:registry.company.com/proj-project-subchart1-dev/company-project-product-capz-info-init:v1.0.1 name:azure repository:proj-project-subchart1-dev/cluster-api-azure/cluster-api-azure-controller-amd64 tag:v1.0.1]] replicaCount:1 resources:map[] securityContext:map[] service:map[port:80 type:ClusterIP] serviceAccount:map[annotations:map[] create:true name:] tolerations:[] workload:map[namespace:WORKLOAD_NAMESPACE-CHANGETHIS]] global:map[leaderElection:map[namespace:LEADERELECTION_NAMESPACE-CHANGETHIS] networkPolicy:map[enabled:true] pullSecret:docker-registry-credentials registry:map[url:registry.company.com]]]]`

**Comment by joejulian** [comment]
Gah, sorry. I should have said:
```
{{ . | toYaml }}
```
so it's readable. That's all just a dump of the go struct.

**Comment by vinibali** [comment]
Thanks for that! One more thing, I'd like to add. The lookup for the subchart values is working from Helm version 3.8.1.
