### ISSUE TITLE
documents for "Subcharts" built-in object

### ISSUE THREAD

**Issue by chuckliu1979** [helm/helm#11257]
I do not find any document for "Subcharts" object, not released yet ?

**Comment by hickeyma** [comment]
@chuckliu1979 Can you provide more details on what you are referring to?

**Comment by chuckliu1979** [comment]
> @chuckliu1979 Can you provide more details on what you are referring to?

sure.

i see ".Subcharts" object here: https://github.com/helm/helm/blob/main/pkg/engine/engine.go#L360
but no document found: https://helm.sh/docs/chart_template_guide/builtin_objects/

**Comment by joejulian** [comment]
@chuckliu1979 Would you please file an issue in the [documentation repo](https://github.com/helm/helm-www/issues)?
