### ISSUE TITLE
Helm charts: How to read a value from environment variables

### ISSUE THREAD

**Issue by vlakka1** [helm/helm#11264]
Hi,

We are deploying our services using helm onto AWS EKS clusters. AWS by default provides an environment variable AWS_REGION which indicates the region that is being deployed to.

The images are stored in AWS ECR which is region specific. The repository url(defined in values.yaml) is something like:

repository: 5***********.dkr.ecr.us-east-1.amazonaws.com/fds/core-api.

I want to know if its possible to read "us-east-1" from environment variable AWS_REGION.

Please let me know and share examples if any.

**Comment by TheoGthr** [comment]
Hello, you can find an example [here, on StackOverflow](https://stackoverflow.com/a/49930497).
The main idea is to declare us-east-1 in your values file, so it can be overridden by setting it in your `helm install` command: `helm install ... --set region=$AWS_REGION` for example.

**Comment by hickeyma** [comment]
@vlakka1 Did the response by @TheoGthr in https://github.com/helm/helm/issues/11264#issuecomment-1230166372, answer our question?

**Comment by vlakka1** [comment]
Hi @hickeyma, I still have to try this out and will keep this thread updated on the results. The issue is we use a common Jenkins pipeline across many projects for helm deployments. I have to figure out a way to fork that and include this setting for a particular Jenkins job.

**Comment by joejulian** [comment]
Since this support question was answered, I'm going to close this.
