### ISSUE TITLE
list: default behavior should list all statuses by default (instead of just deployed and failed) for better UX

### ISSUE THREAD

**Issue by Dentrax** [helm/helm#11262]
Default behavior of `$ helm list` is currently lists only `deployed` and `failed` statuses. For example, to list "actually" _all_ statuses, we have to pass `--all` flag. From the end user perspective, wouldn't it be more user-friendly if it lists all statuses by default? What's the motivation of extra `--all` flag here?

Output of `helm version`:

```
version.BuildInfo{Version:"v3.9.3", GitCommit:"414ff28d4029ae8c8b05d62aa06c7fe3dee2bc58", GitTreeState:"clean", GoVersion:"go1.19"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4", GitCommit:"95ee5ab382d64cfe6c28967f36b53970b8374491", GitTreeState:"clean", BuildDate:"2022-08-17T18:46:11Z", GoVersion:"go1.19", Compiler:"gc", Platform:"darwin/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by hickeyma** [comment]
@Dentrax I don't know the history behind it but I would imagine it is because `deployed` and `failed` releases are the most pertinent releases to be shown. If people want releases with all status, then they can use the `--all` flag.
