### ISSUE TITLE
How can we pass values in secret file other than using values.yaml

### ISSUE THREAD

**Issue by kavita1205** [helm/helm#11269]
Hi Team,
We generally pass values using values.yaml file in secret file but if I don't want to secret value via values.yaml. So what is the other way to pass secret values in secret.yaml.

**Comment by joejulian** [comment]
If you have data in a secret, generally you want to build your templates to either mount that secret into the pod that needs the data, or to set environment variables from that secret data.

https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod
https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables
