### ISSUE TITLE
lint --strict is not

### ISSUE THREAD

**Issue by mnp** [helm/helm#11277]
Output of `helm version`:
version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"clean", GoVersion:"go1.19"}

My impression is `lint --strict` should exit nonzero if there are any warnings but I see otherwise.

```shell
# myvals.yaml
additionalLabels:
  app.kubernetes.io/name: minio

$ helm repo add minio https://charts.min.io

$ helm pull minio/minio

$ helm lint --strict --values myvals.yaml minio-4.0.13.tgz
coalesce.go:223: warning: destination for additionalLabels is a table. Ignoring non-table value ([])
coalesce.go:175: warning: skipped value for minio.additionalLabels: Not a table.
coalesce.go:175: warning: skipped value for minio.additionalLabels: Not a table.
==> Linting minio-4.0.13.tgz

1 chart(s) linted, 0 chart(s) failed 

$ echo $?
0                     # I expect nonzero here because there were warnings
```

Thanks!

**Comment by joejulian** [comment]
I'll label this as a bug, but I think it's not because it's not the linter that's throwing that warning. That error is coming from the values merge before it gets to the templating.

**Comment by mnp** [comment]
Yeah I can appreciate the error is elsewhere but there's some grief here for CI usecases. We try to be "lint clean" in CI and there's no way to detect a warning or error without parsing the output. So exit nonzero on `--strict` would be really slick if it always Did the Right Thing.

**Comment by joejulian** [comment]
I was thinking about this some more... I wonder if you had json schemas for the values of the subcharts if it would fail the linter.
