### ISSUE TITLE
Helm upgrade doesn't replace failed pods if options --wait --timeout were used 

### ISSUE THREAD

**Issue by vosmax** [helm/helm#11278]
Hi there! 

I've faced with interesting behaviour of helm upgrade command: 

How to reproduce:

1. Deploy chart by this command 
```
$ helm upgrade --install my-app  --wait --timeout 20s
```
2. Add `initContainer` section to the deployment with non-zero exit code to make init container fail
```
      initContainers:
      - name: dummy
        image: alpine
        command: ['exit', '71'] 
```
3. Deploy updated chart by this command 
```
$ helm upgrade --install my-app  --wait --timeout 20s
Error: UPGRADE FAILED: timed out waiting for the condition

myapp                        0/1     Init:CrashLoopBackOff   1 (12s ago)       30s
```
4. Remove `initContainer` section in deployment
5. Deploy chart
 ```
$ helm upgrade --install my-app  --wait --timeout 20s
Error: UPGRADE FAILED: timed out waiting for the condition
```

As a result we see that we have the failed pod from step 3 and new one from step 5. 
BUT release failed based on the failed container that wasn't replace by new manifest in step 5 

If render manifests and use native `kubectl apply -f` everything works as expected. 

Is this a bug or feature? 

Versions:
```
kubectl version 
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.10", GitCommit:"7e54d50d3012cf3389e43b096ba35300f36e0817", GitTreeState:"clean", BuildDate:"2022-08-17T18:32:54Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.12-eks-6d3986b", GitCommit:"dade57bbf0e318a6492808cf6e276ea3956aecbf", GitTreeState:"clean", BuildDate:"2022-07-20T22:06:30Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

Helm version 
version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"clean", GoVersion:"go1.19"}
```

**Comment by wujunwei** [comment]
you can try with `--force`

**Comment by wujunwei** [comment]
I see from the source code, if the current release's status is not successful, it will regard last successful deployed release as  current release. so when you remove initContainer section in deployment,it will compare to last successful deployed one which has no initContainer section. helm thought it is same .it would not do anything but wait it tobe normal.

so you can add `--force` flag to replace the new deployment without comparation .

**Comment by vosmax** [comment]
> it will regard last successful deployed release as current release
Looks weird. Current release has to be the last deployed, even if failed. Really, strange logic. I cannot find explanation why so. It has to compare current release and previous. Why does it compare only with the last success release?  

> so you can add `--force` flag to replace the new deployment without comparation
Yes, I can, also `--atomic` can save the situation. but I want to understand the nature of such behavior

**Comment by wujunwei** [comment]
> Looks weird. Current release has to be the last deployed, even if failed. Really, strange logic. I cannot find explanation why so. It has to compare current release and previous. Why does it compare only with the last success release?

I agree with you， I hope some one could explain it 🙏.

**Comment by wujunwei** [comment]
> > it will regard last successful deployed release as current release
> 
> Looks weird. Current release has to be the last deployed, even if failed. Really, strange logic. I cannot find explanation why so. It has to compare current release and previous. Why does it compare only with the last success release?
> 
> > so you can add `--force` flag to replace the new deployment without cooperation
> 
> Yes, I can, also `--atomic` can save the situation. but I want to understand the nature of such behavior

I found this issue #5595 may explain everything.
