### ISSUE TITLE
How Imagecredentials can be access if its values are defined in secret file instead of values file

### ISSUE THREAD

**Issue by kavita1205** [helm/helm#11270]
I am using below configuration for Imagepullsecrets.
My query- Here within defin Imagepullsecrets , we are pulling imagecredentials.registry, imageCredentials.username imageCredentials.password from values.yaml file. If I don't want to expose these username, registry and password in values file then what is the other way to achieve this.

For example - If I want to pass these username, registry and password in secrets file then how we can access it in helm chart i.e. .Secrets.imagecredentials.registry instead of .Values. imagecredentials.registry ?

{{- define "imagePullSecret" }}
{{- printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.imageCredentials.registry (printf "%s:%s" .Values.imageCredentials.username .Values.imageCredentials.password | b64enc) | b64enc }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}

**Comment by kavita1205** [comment]
@mattfarina can you please help me here.

**Comment by joejulian** [comment]
You can specify the secret to use in your values and just reference that secret in imagePullSecrets. See the kubernetes documentation at https://kubernetes.io/docs/concepts/configuration/secret/#using-imagepullsecrets-1
