### ISSUE TITLE
Not able to use dynamic array structure while using --set flag

### ISSUE THREAD

**Issue by hari4147** [helm/helm#11276]
set using an array list destroy the values yaml structure
1. I have powershell script to set a collection of values to a single key in values.yaml
![image](https://user-images.githubusercontent.com/37335234/186882578-5430f649-12f2-4ebf-89b1-781bb1ae585f.png)

But when I execute the The script result like this.
![image](https://user-images.githubusercontent.com/37335234/186883013-394aa88b-45ca-400c-a73b-bb241e8308bc.png)
Actually I want the values like this, But i got this structure only use the set flag like this **helm upgrade testing testconfig --set "KeyvautCollection={may0,may1}"**
![image](https://user-images.githubusercontent.com/37335234/186883468-362c4884-3ea8-483b-aeca-84197799ef19.png)
 **I want to pass a dynamic array along with --set flag**

**Comment by joejulian** [comment]
How about something more like this:
```
$i=0
$testArray= [System.Collections.ArrayList]@()
for(($i=0); $i -lt 3; $i++)
{
$secret="may"+$i
$testArray.Add($secret)
}
$keyvaultCollection=(ConvertTo-Json -InputObject $testArray -Compress)

echo "helm install foo --set KeyvaultCollection=$keyvaultCollection"
```

obviously without the "echo" but just for demonstration purposes, this results in

```
0
1
2
helm install foo --set KeyvaultCollection=["may0","may1","may2"]
```

Which I think is what you're asking for.
