### ISSUE TITLE
Proposal: split values.yaml by subcharts

### ISSUE THREAD

**Issue by PengWang-SMARTM** [helm/helm#11283]
`values.yaml` becomes harder to manage with subcharts in some cases.

It would be nice if `values.yaml` file can be **optionally** broken down into `values.<subchart-alias>.yaml` files, so that each `values.<subchart-alias>.yaml` file would be just like the `values.yaml` file for the subchart.

**Comment by joejulian** [comment]
You can do that now, you'd just have to include the `--values` flag once for each file.

**Comment by PengWang-SMARTM** [comment]
Hi @joejulian, it's great to know this `--values` flag. I should read the help message first.

However, it would be more convenience if helm can automatically pick up all `values.<subchart-alias>.yaml` files just like `values.yaml` without using the `--values` flags, so I could be more lazy :P. Actually, I believe it would also be helpful when not using the command line. `--values` can be used to specify arbitrary files to override defaults.

Since we have the `--values` flag, I created this as only a proposal for your consideration rather than a feature request.

**Comment by joejulian** [comment]
One more thought came to mind that I'll share as I close this out:

```sh
printf -- "--values\0%s\0" *.yaml | xargs -0 helm install myrelease mychart
```
