### ISSUE TITLE
Add rollme: {{ randAlphaNum 5 | quote }} annotation in deployment.yaml

### ISSUE THREAD

**Issue by CatchSandeepVaid** [helm/helm#11288]
Output of `helm version`: 3.9

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"ece9ecf2f9aecbd86d3eba31f0be62e4b6353a5a", GitTreeState:"clean", BuildDate:"2022-07-28T23:33:17Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AKS

[This helm link](https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments) 
` template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
        {{- toYaml . | nindent 8 }}
      {{- end }}`

If podAnnotations is empty ({}) in values.yaml, the rollme annotation will not get added to my deployment.

**Comment by yxxhero** [comment]
@CatchSandeepVaid Please format your code.
