### ISSUE TITLE
http2: client connection lost - is there any possibility of a retry?

### ISSUE THREAD

**Issue by stuartdrennan** [helm/helm#11292]
Occasionally I am seeing `http2: client connection lost` in helm install/upgrade operation.  

This is more noticeable in long running installs.  

`helm install` is happening within pods inside the cluster but there may be network drops due to cluster size, traffic volume or possible rolling restarts of etcd/api servers, none of which me or my team can control.  Understand these problems are not really helms issue, but would it be possible for helm to retry in this situation, rather than fail?   

kubectl v18.2.0
helm v3.9.0

**Comment by yxxhero** [comment]
@stuartdrennan run helm install again?

**Comment by stuartdrennan** [comment]
Certainly an option, but an inbuilt retry mechanism would be a lot simpler and cleaner so the install doesn't get into a failed state when the chart itself didn't actually fail :)

**Comment by yxxhero** [comment]
@stuartdrennan There is no such retry mechanism at present. Thanks very much.

**Comment by stuartdrennan** [comment]
It looks like https://github.com/helm/helm/pull/11401/files may fix this

**Comment by mbelt** [comment]
This issue was not resolved by [PR 11401](https://github.com/helm/helm/pull/11401/files).

Helm should have better connection handling when monitoring for `--atomic` or `--wait`. 

An unstable connection to the API server while monitoring the progress of a release should not cause the release to fail.
