### ISSUE TITLE
If clause for template existence check

### ISSUE THREAD

**Issue by fox-md** [helm/helm#11291]
Can you please advice, is it possible to check template existence with `if` clause?
Below option does not work for me.
I created `hook.env`, but trying to call `hook` template that does not exist.

```
...
        env:
        {{- if eq (include "hook" .) "true" -}}
        {{ include "hook" . }}
        {{- end -}}


{{- define "hook.env" -}}
        env:
          - name: SOME_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-secret-key
                key: url
                optional: false
{{- end -}}
```
I am getting below error:
```
Error: UPGRADE FAILED: template: nginx/templates/hook.yaml:29:19: executing "nginx/templates/hook.yaml" at <include "hook" .>: error calling include: template: no template "hook" associated with template "gotpl"
```

Output of `helm version`:

version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.17.5"}

Thank you

**Comment by yxxhero** [comment]
@fox-md 
```
no template "hook"
```
Do you have any templte "hook" by `define`?

**Comment by fox-md** [comment]
Hi @yxxhero,
No, I do not. I would like to store below block in a chart library and to include it only if chart has template `hook` defined
```
        {{- if eq (include "hook" .) "true" -}}
        {{ include "hook" . }}
        {{- end -}}
```

**Comment by matthiasvegh** [comment]
Hi @fox-md,

If you know the name of the template you wish to check for (`hook` in your example), you can try the following:

```
{{- define "hookwrapper" -}}
{{- block "hook" . }}DEFAULT{{ end -}}
{{- end -}}
```

By calling `include` on `"hookwrapper"` you can determine if the hook existed, or if the block took effect. DEFAULT could be omitted, but then you wouldn't be able to tell if `hook` was defined and simply rendered nothing, or if `hook` was not defined.
