### ISSUE TITLE
Define variable in values.yaml and use same file

### ISSUE THREAD

**Issue by TigranKhudav** [helm/helm#11297]
Can I set a value in value.yaml and use it in the same file ?
for example.

`values.yaml`

name: example

containerEnv:
 &nbsp;&nbsp;&nbsp;&nbsp;\- name: URL
 &nbsp;&nbsp;&nbsp;&nbsp;value: "`<name>`.com"

Labels:
&nbsp;&nbsp;&nbsp;&nbsp; app.kubernetes.io/name: `<name>`

**Comment by fisju** [comment]
you can use anchors for that but there is a limitation that you cannot modify the value (e.g. concatenate)
see https://helm.sh/docs/chart_template_guide/yaml_techniques/#yaml-anchors

**Comment by TigranKhudav** [comment]
Thanks @fisju  
But we can use in the string ?
for example.

url: `&Url` "example"
 
containerEnv:
    - name: URL
    value: "http://`<Url>`.com"
