### ISSUE TITLE
trimAll can't identify 'e'

### ISSUE THREAD

**Issue by huangcj7** [helm/helm#11305]
I use the {{  trimAll "te" "$test"  }}
and my expected output is **$st**
but it is $tes

also if I use {{  trimAll "e" "test"  }} ,there is nothing to do

**Comment by joejulian** [comment]
According to [sprig documentation](http://masterminds.github.io/sprig/strings.html#trimall):

## trimAll

Remove given characters from the front or back of a string:

trimAll "$" "$5.00"

The above returns 5.00 (as a string).

---

I think you're looking for [regexReplaceAll](http://masterminds.github.io/sprig/strings.html#regexreplaceall-mustregexreplaceall)

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!
