### ISSUE TITLE
Add command line gate for changing a release's chart

### ISSUE THREAD

**Issue by xrl** [helm/helm#11320]
We author many charts and make many releases. Sometimes we screw up and overwrite an existing release by running a `helm install` with the name of an existing release that's on a different chart.

It would be nice to have a flow like:

```
$ helm ls
my-release                   the-app      525             2022-09-09 15:23:22.440161232 +0000 UTC deployed        my-chart-0.1.242
$ helm install --upgrade my-release my-other-chart ...
ERROR release is already installed with chart `my-chart`. In order to replace with `my-other-chart` use `--allow-chart-change`
```

**Comment by joejulian** [comment]
This would require storing that information in the release object. Please review the [HIP related to this proposal](https://github.com/helm/community/pull/269) and add any feedback you might have. Once that feature is implemented, this wouldn't be that difficult to implement.
