### ISSUE TITLE
sts replicas terminate parallely when using helm hook pre-upgrade and post-upgrade for sts

### ISSUE THREAD

**Issue by abhishekkarigar** [helm/helm#11332]
helm version
version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1+6438632", GitCommit:"6438632813d72669a22c860cd6c218fd4fe4ec24", GitTreeState:"clean", BuildDate:"2021-10-15T20:13:58Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.25) and server (1.21) exceeds the supported minor version skew of +/-1

OpenShift 
Client Version: 4.9.0-0.okd-2022-02-12-140851
Server Version: 4.8.18
Kubernetes Version: v1.21.1+6438632

**Comment by joejulian** [comment]
Please include more details. An example or explanation that can be followed to reproduce the issue is appreciated.
