### ISSUE TITLE
What are changes or key features planned for HELM 4 ?

### ISSUE THREAD

**Issue by abhishek-kumar0409** [helm/helm#11331]
Are there any resources / links available to know more about the strategy of helm 4?

**Comment by joejulian** [comment]
Here's a link that filters for open issues labeled for v4:
https://github.com/helm/helm/issues?q=is%3Aopen+is%3Aissue+label%3Av4.x

Also useful is the [weekly developer meetings](https://docs.google.com/document/d/1d-6xJEx0C78csIYSPKJzRPeWaHG_8W1Hjl72OJggwdc/edit#heading=h.cafxi2yfgqg1).

If there's a specific feature you'd like to develop for v4, please raise an issue and write a hip!
