### ISSUE TITLE
wait for all the replicas of one of the statefulset to be upgraded and then upgrade other statefulset.

### ISSUE THREAD

**Issue by abhishekkarigar** [helm/helm#11333]
helm version
version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1+6438632", GitCommit:"6438632813d72669a22c860cd6c218fd4fe4ec24", GitTreeState:"clean", BuildDate:"2021-10-15T20:13:58Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.25) and server (1.21) exceeds the supported minor version skew of +/-1

OpenShift
Client Version: 4.9.0-0.okd-2022-02-12-140851
Server Version: 4.8.18
Kubernetes Version: v1.21.1+6438632

**Comment by abhishekkarigar** [comment]
there is a statefulset A which has 3 replicas.  
there is another statefulset B which has 3 replicas.

when doing `helm upgrade` i want to make sure that Statefulset A is upgraded first with all 3 replicas and then start upgrading statefulset B

**Comment by joejulian** [comment]
That's not something helm can solve. Kubernetes resources are meant to be declarative and there's no way to hook one sts to another.

Off the top of my head, I can think of two options, one is to just do this as two separate charts, upgrading one at a time. The other is to write a controller that blocks the pods you don't want upgraded using finalizers.

**Comment by abhishekkarigar** [comment]
@joejulian thanks for the reply, will look into it

**Comment by abhishekkarigar** [comment]
@joejulian  will helm dependency help to resolve this issue ?

**Comment by joejulian** [comment]
No, sorry, dependencies just allow you to include other charts. In the end, it's effectively the same as running `helm template ... | kubectl apply -f -`.

**Comment by abhishekkarigar** [comment]
i was going through operators sdk and came to know there are two operators helm operators and go based operators.
@joejulian will the helm based operator resolve my issue ?

**Comment by joejulian** [comment]
Sorry, I'm not familiar with it.

**Comment by joejulian** [comment]
I always use kubebuilder to frame up a controller using controller-runtime. It's, in my opinion, the fastest way to get started writing a controller from scratch. If there's one already written that solves it for you, that's great!

**Comment by abhishekkarigar** [comment]
okay, will look into this kubebuilder
