### ISSUE TITLE
How to apply range to generate files via config map at pod volume?

### ISSUE THREAD

**Issue by vidhangithub** [helm/helm#11337]
Output of `helm version`:3.9.4

Output of `kubectl version`:1.21.4

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Minikube

_We are trying to apply range on below configurations_ :- 

**values.yaml**
===========
configs:
  configName: my-configmap
  volumeMountsVar:
    name: volumemount
    mountPathVar: /opt/serverconfig
    readOnlyFlag: true

serverConfigFiles:
  bootstrap: |
    http.port=9080
    https.port=-1
    circuitbreaker.allowHealthIndicatorToFail=false
    circuitbreaker.registerHealthIndicator=true
    circuitbreaker.slidingWindowType=COUNT_BASED
    circuitbreaker.slidingWindowSize=20
    circuitbreaker.minimumNumberOfCalls=10
    circuitbreaker.failureRateThreshold=50
    circuitbreaker.waitDurationInOpenState=5000
    circuitbreaker.permittedNumberOfCallsInHalfOpenState=1
    circuitbreaker.automaticTransitionFromOpenToHalfOpenEnabled=true
    timelimiter.cancelRunningFuture=true
    timelimiter.timeoutDuration=2s
    threadPoolBulkHead.maxThreadPoolSize=60
    threadPoolBulkHead.coreThreadPoolSize=30
    threadPoolBulkHead.queueCapacity=30
  jvmoptions: |
    -Xmx768m
  serverenv: |
    test

**configmap.yaml**
===========
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.configs.configName }}
  namespace: {{ default .Release.Namespace .Values.namespace }}
data:
  bootstrap.properties:
  {{ .Values.serverConfigFiles.bootstrap | toYaml | nindent 2}}
  jvm.options:
  {{ .Values.serverConfigFiles.jvmoptions | toYaml | nindent 2}}
  server.env:
  {{ .Values.serverConfigFiles.serverenv | toYaml | nindent 2}}

**deployment.yaml**
============
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ default .Release.Namespace .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    version: v{{ default .Chart.Version .Values.image.tag }}
    env: {{ .Values.env }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
      env: {{ .Values.env }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 10 | quote }}
      labels:
        app: {{ .Values.name }}
        version: v{{ default .Chart.Version .Values.image.tag }}
        env: {{ .Values.env }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.registrypath }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name:  {{ .Values.configs.volumeMountsVar.name }}
              mountPath: {{ .Values.configs.volumeMountsVar.mountPathVar }}
              readOnly: {{ .Values.configs.volumeMountsVar.readOnlyFlag }}
      volumes:
        - name:  {{ .Values.configs.volumeMountsVar.name }}
          configMap:
            name: {{ .Values.configs.configName }}
            items:
              - key: "bootstrap.properties"
                path: "bootstrap.properties"
              - key: "jvm.options"
                path: "jvm.options"
              - key: "server.env"
                path: "server.env"
      imagePullSecrets:
        - name: {{ .Values.image.secretName }}

_with above configuration we are able to generate three files at pod volume ( /opt/serverconfig)  successfully , but we are trying achieve same using range which we can apply on configmap.yaml and deployment.yaml so that if in future we add some other file at values.yaml it gets added to configmap and pod volume automatically._  

_we tried few options but nothing works. Can somebody help here?_

Regards
Vidhan Chandra

**Comment by joejulian** [comment]
If I were doing it, I would just make the values match the files:
```
serverConfigFiles:
  bootstrap.properties: |
    http.port=9080
    https.port=-1
    circuitbreaker.allowHealthIndicatorToFail=false
    ...
  jvm.options: |
     -Xmx768m
  server.env: |
    test
```
Then your configmap would just need:
```
data:  {{ .values.serverConfigFiles | toYaml | nindent 2 }}
```

**Comment by vidhangithub** [comment]
@joejulian - Thanks for your quick reply. Sorry I didn't try that then and there as previous settings were working fine. I tested it today but It was unable to create the files ( bootstarp.properties, jvm.options  and servers.env) at pod volume. Do i Still need to have below in **deployment.yaml**  :-

`volumes:
    - name: {{ .Values.configs.volumeMountsVar.name }}
      configMap:
          name: {{ .Values.configs.configName }}
           items:
               - key: "bootstrap.properties"
                  path: "bootstrap.properties"
               - key: "jvm.options"
                 path: "jvm.options"
              - key: "server.env"
                path: "server.env"
imagePullSecrets:
    - name: {{ .Values.image.secretName }}`

and if I need to do so , I hope  I need to add a entry as key and path on deployment.yaml  every time I add a new file at configmap. Please help me to understand if I am wrong.

Thanks in advance.

**Comment by joejulian** [comment]
If the configmap uses filenames in the data, then you only need to mount the configmap:
```
volumes:
  - name: {{ .Values.configs.volumeMountsVar.name }}
    configMap:
      name: {{ .Values.configs.configName }}
```

Each of those keys will be a file in the mounted ConfigMap. See [Configure a Pod to Use a ConfigMap](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#populate-a-volume-with-data-stored-in-a-configmap) in the kubernetes docs.

This way you don't need to add keys and paths, you just mount the ConfigMap.

**Comment by joejulian** [comment]
Since this has sat idle for this long, I'm going to assume this answered your question and close this. I hope it helped.
