### ISSUE TITLE
helm rollback fail because pvc can't be reduced

### ISSUE THREAD

**Issue by dongxijia** [helm/helm#11359]
Helm rollback the chart fail when upgraded a chart where pvc  was expanded,  because PVC can't be reduced.

Could helm support not rollback PVC  when a chart is rollbacking ？Otherwise, if PVC capacity is expanded, the chart cannot be rollback.

**Comment by joejulian** [comment]
The immediate answer is no. Helm cannot support that use case.

Could it in the future? My initial impression is that the core maintainers would not consider supporting the logic required to solve this. It's generally rejected to add any complex logic, the argument being that helm is a templating tool, not an operator.

I do wonder if excluding PVCs from a rollback might be accepted though. Should they be considered immutable? What about other immutable resources? Can you roll back an immutable secret?

Would love to see what the opinion of the @helm/helm-core-maintainers is on this one.
