### ISSUE TITLE
Lookup resources to be installed in a release

### ISSUE THREAD

**Issue by devzer01** [helm/helm#11367]
I am preparing helm helper functions to ultimately provide a consistent single chart for all application development, one of the issues I had is that Helm does not provide the ability to lookup objects that would be part of the pending release. I am still reading through the source code so I have to see in what Order things are read, but there can always be post-processing stage for some function execution. 

Anyway i found a work around to the issue as follows

```bash
helm template  --name-template ha-backend-stage --output-dir validation .
for f in `find validation -name \*.yml -print`
 do 
  PV_VARS=$(yq '. | select(.kind == "PersistentVolume") | .metadata.name' $f)
done

# then feed the values in during the install phrase using --set to be able to configure the volume and mounts in the deployment description
```

**Comment by joejulian** [comment]
Typically you would use [named templates](https://helm.sh/docs/chart_template_guide/named_templates/) for that, and template the name so you can include it for both the PV name, and any place you need to reference that PV.
