### ISSUE TITLE
Does the name space in `helm status` always match the namespace flag?

### ISSUE THREAD

**Issue by Jont828** [helm/helm#11366]
I was discussing with @sbueringer and wanted to clarify something. When we want to get the helm status in a namespace, we pass it in with a `-n` flag and there's also a `NAMESPACE` field in the output. Is the `-n` flag always going to match the `NAMESPACE` in the output? I would think so but I wanted to make sure.

```
NAME: nginx-ingress-1663364363
LAST DEPLOYED: Fri Sep 16 17:39:26 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
The NGINX Ingress Controller has been installed.
```

**Comment by joejulian** [comment]
As far as I can tell, you are correct. I could probably hack together a way to break that, ie copy a release secret to another namespace, but no way that's supported.

**Comment by Jont828** [comment]
Makes sense to me, if I find a release in a namespace I'd expect the metadata/JSON stuff to list it in the same namespace.
