### ISSUE TITLE
How to manage HELM deployments based on environments using value.yaml

### ISSUE THREAD

**Issue by yugeshN** [helm/helm#11360]
I have a requirement to deploy multiple deployments with different values using values.yaml. I'm able to deploy multiple deployments using "range loop".  I want to manage the deployment count based on the environment. For example  I need 2 deployments for DEV and 5  deployments for QA environment . How to manage this Please guide 

My values.yaml  ( below list will deploy 2 deployments for all the environments)

deployments:      
  - name: deployment1
    slice: 1
    replicaCount : 1
    hpaname: hpa1
  - name: deployment2
    slice: 2
    replicaCount : 1
    hpaname: hpa2
    
My deployment.yaml 

{{- $root := . -}}
{{- range $deployment := .Values.deployments -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $root.Chart.Name }}-{{ $deployment.name }}-{{ $root.Values.environment }}-{{ $root.Chart.AppVersion }}
  labels:
    version: {{ $root.Chart.AppVersion }}
    app: {{ $root.Chart.Name }}
    env: {{ $root.Values.environment }}
    slice: "{{ $deployment.slice }}"

**Comment by joejulian** [comment]
The way I do it is to have different values files:

dev.yaml
```
fullName: myrelease-dev
deployment:
  replicas: 1
```

prod.yaml
```
fullName: myrelease-prod
deployment:
  replicas: 10
ingress:
  enabled: true
```

Then you use those values files during installation:
```
helm install myrelease mychart --values dev.yaml
```

**Comment by yugeshN** [comment]
We are not deploying helm charts manually, During the codepipeline automation 'deployment.yaml' should target to the respective values.yaml based on the environment.  May be I should define a if condition in deployment.yaml

Below 'deployment.yaml' able to call parameters from 'values.yaml' using range loop. I would like to use 1 "deployment.yaml' for all the environments like DEV, QA, PROD. Is it possible to write a "if" or "If else" condition to target the different values.yaml files based on the environment ? Example below

DEV environment > valuesdev.yaml
QA environment > valuesqa.yaml


Deployment.yaml (This is targeting to Values.yaml using range loop ) 

{{- $root := . -}}
{{- range $deployment := .Values.deployments -}}
apiVersion: apps/v1
kind: Deployment
metadata:
name: {{ $root.Chart.Name }}-{{ $deployment.name }}-{{ $root.Values.environment }}-{{ $root.Chart.AppVersion }}
labels:
version: {{ $root.Chart.AppVersion }}
app: {{ $root.Chart.Name }}
env: {{ $root.Values.environment }}
slice: "{{ $deployment.slice }}"

deployments:
  - name: deployment1
    slice: 1
    replicaCount : 1
 - name: deployment2
   slice: 2
   replicaCount : 2
   hpaname: hpa2

**Comment by joejulian** [comment]
Sure, you could do it that way. I'd be wary of exceeding the storage limit of a secret for the release artifact. The release secret has to be able to hold the entire manifest.
