### ISSUE TITLE
Output full paths to files with errors from lint

### ISSUE THREAD

**Issue by tillig** [helm/helm#11365]
I'm trying to create a [problem matcher for VS Code](https://code.visualstudio.com/Docs/editor/tasks#_defining-a-problem-matcher) such that I can include `helm lint` as part of the build for a chart repo and have problems tied back to actual files.

Right now when `helm lint` finds a problem, it outputs locations of problems in a sort of relative way:

```text
$ helm lint
==> Linting .
[ERROR] Chart.yaml: version is required
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: validation: chart.metadata.version is required
[ERROR] : unable to load chart
	validation: chart.metadata.version is required

Error: 1 chart(s) linted, 1 chart(s) failed
```

In order to actually indicate the file that is built, you end up needing to put three things together:

- The current folder (in case you didn't pass in a path or passed in a relative path)
- The message from the linter (`==> Linting _____`)
- The name of the file after `[ERROR]` or `[INFO]`

That's not terribly easy to do from an automated build "find the file based on a regex match" sort of thing.

It would be nice if the `helm lint` messages could optionally output an absolute path to the file with the issue, something like:

```text
$ helm lint --full-paths
==> Linting /Users/myname/path/to/chart/
[ERROR] /Users/myname/path/to/chart/Chart.yaml: version is required
[INFO] /Users/myname/path/to/chart/Chart.yaml: icon is recommended
[ERROR] /Users/myname/path/to/chart/templates/: validation: chart.metadata.version is required
[ERROR] : unable to load chart
	validation: chart.metadata.version is required

Error: 1 chart(s) linted, 1 chart(s) failed
```

If that was the case, you could very easily create a plugin problem matcher to integrate `helm lint` into an IDE like VS Code.

**Comment by joejulian** [comment]
See also https://github.com/helm/helm/issues/11357

**Comment by tillig** [comment]
Still an issue.

**Comment by tillig** [comment]
Still am issue.

**Comment by tillig** [comment]
Still an issue.

**Comment by tillig** [comment]
Still an issue.
