### ISSUE TITLE
Question: where are the starter files ?

### ISSUE THREAD

**Issue by asafbennatan** [helm/helm#11381]
where can i find the starter files that are being used with `helm create`?
 i would like to use them as a start point to some customization i require.
Thanks

P.S
for clarification I am looking for something like https://github.com/uptownaravi/helm-starter
but official

**Comment by yxxhero** [comment]
@asafbennatan maybe `helm create -s`?

**Comment by asafbennatan** [comment]
getting `Error: unknown shorthand flag: 's' in -s`

**Comment by yxxhero** [comment]
@asafbennatan oh. sorry.
`-p, --starter string`

**Comment by asafbennatan** [comment]
i got what you mean , i am aware of this flag i plan to use it with a starter i will write , i want to base that starter based on the existing template we get by the default `helm create`

**Comment by yxxhero** [comment]
@asafbennatan I got. you can alias `helm create -p test/test`?

**Comment by asafbennatan** [comment]
but how will that help ? , i am looking for similar files that we have in https://github.com/uptownaravi/helm-starter ( those are not that same as what helm create outputs since it contains __CHART_NAME__ )

**Comment by joejulian** [comment]
Are you looking for https://github.com/helm/helm/blob/main/pkg/chartutil/create.go ?

**Comment by asafbennatan** [comment]
@joejulian exactly , Thanks!
