### ISSUE TITLE
no matches for kind "Deployment" in version  "app/v1" ensure CRDs are installed first

### ISSUE THREAD

**Issue by mvivek0210** [helm/helm#11382]
![Annotation 2022-09-25 121814](https://user-images.githubusercontent.com/73626924/192131846-a5f051d9-4983-4238-a435-c17584342189.png)

**Comment by cleverhu** [comment]
The apiVersion for deployment is apps/v1

**Comment by fahimjason** [comment]
> The apiVersion for deployment is apps/v1

@cleverhu Thank you so much.

**Comment by NhatVodka** [comment]
@cleverhu U saved my day bro =)))

**Comment by pradeepwwhy** [comment]
Thank you guys, this helps :)

**Comment by gulshkr** [comment]
Can anyone tell, How this problem can be solved I have faced the same problem....
