### ISSUE TITLE
Malformed JSON output

### ISSUE THREAD

**Issue by stan-sz** [helm/helm#11385]
Output of `helm version`: 3.10.0

>helm upgrade foo-bar oci://foo.azurecr.io/helm/foo-bar --install --namespace foo --version 1.0.0 --output json

yields

```json
Pulled: foo.azurecr.io/helm/foo-bar:1.0.0
Digest: sha256:f4bcf923e259199f5ef3506e3edea83a70f3474be5d94ead6bae4654ef1b91e7
{
    "name": "foo-bar",
    "info": {/*content*/},
    "chart": {/*content*/}
}
```

So there are extra two lines before the regular json response. This is due to:

https://github.com/helm/helm/blob/c52cd40acef183d29f6def5026e66616b9993c88/pkg/registry/client.go#L419-L420

**Comment by nilsalex** [comment]
I have a similar issue. We use output from `helm show values oci:///foo.io/bar --version 1.0.0 --jsonpath '{.foo.bar}'`, which with helm version 3.9.4 used to be just the value of `.foo.bar`.

With 3.10.0, we get
```
Pulled: ...
Digest: ...
<value of .foo.bar>
```

I did a bisect and the issue starts to appear with this commit: https://github.com/helm/helm/commit/9f199b6517c21394bca555983c70fc232d65014c

**Comment by yxxhero** [comment]
@nilsalex Thanks very much. I will test this issue.

**Comment by yxxhero** [comment]
[root@devops ~]# helm show values oci://localhost:5000/aaa/abc --version 0.1.0 --jsonpath '{.autoscaling.enabled}'
Pulled: localhost:5000/aaa/abc:0.1.0
Digest: sha256:fc93deb645f85bd9ecb46f570927702f9440a9331cb0aa0a3cb746ad27656eab
false[root@devops ~]#

false[root@devops ~]# helm version
version.BuildInfo{Version:"v3.10.0", GitCommit:"ce66412a723e4d89555dc67217607c6579ffcb21", GitTreeState:"clean", GoVersion:"go1.18.6"}

@nilsalex I can't reproduce your issue.

**Comment by d-d-up** [comment]
@yxxhero I want to fix it.

**Comment by stan-sz** [comment]
Please note that there are more cases of such message logging in that file.

**Comment by wernerb** [comment]
@d-d-up This is a larger issue. Since helm 3.10.0 it makes any output from `helm template` invalid kubernetes as well.
```bash
$ helm template oci://mychart --version 0.0.1 | kubectl apply -f- dry-run=server
error: error validating "STDIN": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
```
Because of the extra two lines.

**Comment by yxxhero** [comment]
@d-d-up ping

**Comment by jouve** [comment]
as a side effect, this breaks [helmfile/helmfile](https://github.com/helmfile/helmfile/) template

**Comment by ianroberts** [comment]
This is still an issue in the latest v4.2.4, and the latest main branch - when I specify `--output json` I'm still getting the `Pulled` and `Digest` lines printed on stdout ahead of the actual JSON response.  If it's not desirable to put these lines onto stderr in all cases, could they at least go onto stderr when the user requests JSON or YAML output, so that stdout remains as valid parseable JSON/YAML?
