### ISSUE TITLE
Do you have api documentation

### ISSUE THREAD

**Issue by ZhangSetSail** [helm/helm#11392]
Output of `helm version`: v3.6.3

Output of `kubectl version`: 

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3+k3s1", GitCommit:"61a2aab25eeb97c26fa3f2b177e4355a7654c991", GitTreeState:"clean", BuildDate:"2021-11-04T00:24:35Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
aliyun

Hello, I want to know the interface of the help operation. Do you have api documentation

**Comment by joejulian** [comment]
Help is generated by [sfp13/cobra](https://github.com/spf13/cobra) from the definitions in the go files found under [cmd/helm](https://github.com/helm/helm/tree/main/cmd/helm)

**Comment by joejulian** [comment]
And I just realized that "help" is probably a typo and you meant "helm". Maybe you're looking for this? https://helm.sh/docs/topics/advanced/#go-sdk

**Comment by hickeyma** [comment]
Go docs might also be of help: https://pkg.go.dev/helm.sh/helm/v3

**Comment by ZhangSetSail** [comment]
Okay Thank you
