### ISSUE TITLE
helm lint stuck with malformed template object

### ISSUE THREAD

**Issue by jgarec** [helm/helm#11391]
Hi

Output of `helm version`:

> version.BuildInfo{Version:"v3.10.0", GitCommit:"ce66412a723e4d89555dc67217607c6579ffcb21", GitTreeState:"clean", GoVersion:"go1.19.1"}

With this template file (notice the space between the first and the second curly brackets): 
`{ {- $relname := .Release.Name -}}`

helm lint does not respond whereas helm template throws an error (which is the normal behaviour) :
> Error: YAML parse error on onboarding-ms/templates/secret.yaml: error converting YAML to JSON: yaml: did not find expected node content
Use --debug flag to render out invalid YAML`

**Comment by joejulian** [comment]
Well that is an interesting one. To duplicate this issue:

```bash
helm create test
echo '{ {- $relname := .Release.Name -}}' > test/templates/bad.yaml
helm lint test
```
The command hangs.

**Comment by wujunwei** [comment]
https://github.com/helm/helm/blob/422c406b5c86d3df66a2edd1542de3d57b9d8065/pkg/lint/rules/template.go#L136-L142
```go
func (dec *Decoder) Decode(v any) error {
	if dec.err != nil {
		return dec.err
	}
       ...
}

```
As the code shown above,if parse yaml error happen ,it always return error next time.

**Comment by wujunwei** [comment]
It's a amazing  bug :)

**Comment by wujunwei** [comment]
ping 
still stucked with current version.
