### ISSUE TITLE
Allow to specify Chart version in values.yaml

### ISSUE THREAD

**Issue by migs35323** [helm/helm#11393]
Would it be possible to have an object to specify the chart version the inside the values.yaml?

Different Chart versions can expect different ways of inserting values, so it would be great if we could specify a chart version in a values.yaml and this would basically have the same effect as the  --version flag, it would fetch and install the chart matching that constraint...

**Comment by joejulian** [comment]
I think you might want a higher order api object, similar to the Chart.yaml that matches any defined fields against those in the chart's Chart.yaml. Maybe that resource could include values, or a reference to values (by filename, maybe).

For example:
```
apiVersion: v2
kind: HelmChart
name: redpanda
version: ~2.1
appVersion: ~22.2
```
would match any v2 helm chart with the name `redpanda` a chart version of `2.1.*` and an appVersion of `22.2.*`.

**Comment by ebuildy** [comment]
This is a good feature, Helm allows to use values to set `condition` field, so I think this is something possible to achieve.

As a workaround, we use argocd ` helm` source manifest.
