### ISSUE TITLE
Helm Upgrade Install return with Error: create: failed to create: status code 413 but did not return more information (post secrets)

### ISSUE THREAD

**Issue by badigeranand007** [helm/helm#11398]
Output of `helm version`: version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"clean", GoVersion:"go1.17.13"}

Output of `kubectl version`: WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
The connection to the server localhost:8080 was refused - did you specify the right host or port?

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  EKS 
When I execute the command below for deploying the app I get error. The same was working fine few days ago and all of sudden started failing.

oot@144-8-225-229:/apps/opt/jenkins/83-aws-us-east-1-ontv-vzontime-ple-appointment-availability-service # helm upgrade --install --wait --timeout 1200s --history-max 10 --debug appointment-availability-service-ple ./ --namespace ontv-vzontime-ple -f=.//values_ple.yaml --set-string global.build.env=ple --kubeconfig=/root/kubeconfig_ple_EAST
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /root/kubeconfig_ple_EAST
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /root/kubeconfig_ple_EAST
history.go:56: [debug] getting history for release appointment-availability-service-ple
Release "appointment-availability-service-ple" does not exist. Installing it now.
install.go:178: [debug] Original chart version: ""
install.go:195: [debug] CHART PATH: /apps/opt/jenkins/83-aws-us-east-1-ontv-vzontime-ple-appointment-availability-service

Error: create: failed to create: the server responded with the status code 413 but did not return more information (post secrets)
helm.go:84: [debug] the server responded with the status code 413 but did not return more information (post secrets)
create: failed to create
helm.sh/helm/v3/pkg/storage/driver.(*Secrets).Create
        helm.sh/helm/v3/pkg/storage/driver/secrets.go:164
helm.sh/helm/v3/pkg/storage.(*Storage).Create
        helm.sh/helm/v3/pkg/storage/storage.go:69
helm.sh/helm/v3/pkg/action.(*Install).RunWithContext
        helm.sh/helm/v3/pkg/action/install.go:340
main.runInstall
        helm.sh/helm/v3/cmd/helm/install.go:264
main.newUpgradeCmd.func2
        helm.sh/helm/v3/cmd/helm/upgrade.go:121
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.4.0/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.4.0/command.go:974
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.4.0/command.go:902
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
        runtime/proc.go:255
runtime.goexit
        runtime/asm_amd64.s:1581

**Comment by joejulian** [comment]
According to RFC 9110

> The 413 (Content Too Large) status code indicates that the server is refusing to process a request because the request content is larger than the server is willing or able to process. The server MAY terminate the request, if the protocol version in use allows it; otherwise, the server MAY close the connection.

So it looks like your Secret is [too big](https://kubernetes.io/docs/concepts/configuration/secret/#restriction-data-size).

**Comment by badigeranand007** [comment]
@joejulian 
In my values.json I dont even have any secret
pls see below
global:
    project:
      lob: vzw
      vsad: ontv
    build:
      # commitId: read_from_jenkins
      env: prod
      #branch: master
  
  ### Auto Scaling requirements
  autoscaling:
    min: 1
    max: 2
    cpu:
      targetCPUUtilization: 70
    memory:
      targetMemoryUtilization: 160
  
  ## Define your container
  deployment:
    tmpfs: yes
    template:
      
      imagePullSecrets:
        - name: regsecret
      containers:
        - name: appointment-availability-service
          image: XXXXXXXX/appointment-availability-service:UAT.REL-Build_09-27-2022_256
          volumeMounts: 
            - name: logs
              mountPath: /apps/opt/vzontime/microservices/log
            - name: config
              mountPath: /apps/opt/vzontime/config/vzot_config_repo/proxy-config
            - name: rasp
              mountPath: /apps/opt/rasp/logs
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /appointment-availability-service/health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 60
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /appointment-availability-service/health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 60
            successThreshold: 1
            failureThreshold: 3
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 256m
              memory: 1Gi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod-oracle-east
          - name: NEW_RELIC_APP_NAME
            value: ONTV-appointment-availability-service-prod
          - name: NEW_RELIC_PROXY_HOST
            value: XXXXXX
          
      volumes:
        - emptyDir: {}
          name: logs
        - emptyDir: {}
          name: config
        - emptyDir: {}
          name: rasp
     
  
  ## Define your Service
  service:
    ports:
      - name: http
        port: 8080
        targetPort: 8080
        protocol: TCP
    type: ClusterIP
  ## Define your Ingress
  ingress:
    annotations:
      alb.ingress.kubernetes.io/group.name: ontv-vzontime-prod-eks-east
      alb.ingress.kubernetes.io/security-groups: 'XXXX'
      alb.ingress.kubernetes.io/subnets: 'XXXX'
      alb.ingress.kubernetes.io/certificate-arn: "XXXXX"
   
    tls:
    - hosts:
      - XXXXXX
      - XXXXXX
    rules:
    - host: XXXXXXXX
      http:
        paths:
        - path: /appointment-availability-service
          backend:
            service:
              name: appointment-availability-service
              port:
                name: http
          pathType: Prefix
    - host: XXXXXXXX
      http:
        paths:
        - path: /appointment-availability-service
          backend:
            service:
              name: appointment-availability-service
              port:
                name: http
          pathType: Prefix

Please let me know if you need more info

**Comment by joejulian** [comment]
The release data is kept in a secret. If that's :point_up:  your entire chart, I'm guessing there must be other files in your chart directory that is being included in the chart data. Check for extra files under your chart directory.

**Comment by badigeranand007** [comment]
Joe, Thank you for your respone.
I do have  deployment.yaml, horizontal-auto-pod-scaler.yaml ,service.yaml , ingress.yaml but they dont contain any secret too.

![image](https://user-images.githubusercontent.com/60767277/193161994-1783746e-756c-4561-bf24-d6fa6b0a967e.png)

**Comment by badigeranand007** [comment]
I think I got it. it looks for the other larger file in the directory and then it was throwing error
Thank you so much. You made my day.
