### ISSUE TITLE
Accesing files from libraries chart dependencies

### ISSUE THREAD

**Issue by rschamizo** [helm/helm#11402]
# Problem
I have a library who create a configmap from file with this:

```
{{- range $job  := .Values.global.jobs.items }}
{{ if $job.enabled }}
apiVersion: v1
data:
{{ ($.Files.Glob (printf "%s%s%s" "newman/" $job.name "/*")).AsConfig | indent 2 }}
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-{{$job.name}}-newman
---
{{- end }}
{{- end }}
```
![image](https://user-images.githubusercontent.com/78882304/193376298-7e59f887-03ea-4d71-ae57-16a47f7e9332.png)

Now i want to reuse this library from others helm Charts so i added it as dependecy, but cannot access the files now although use the same variables. 

# Question
I want to have the same folder in the root chart, and load this files from this, without have the folder 'newman' inside the newman-hooks chart itself.

¿Is any way to do this?

Thank you in advance.

# Versions
Output of `helm version`:
version.BuildInfo{Version:"v3.5", GitCommit:"", GitTreeState:"", GoVersion:"go1.16.6"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3+k3s1", GitCommit:"5fb370e53e0014dc96183b8ecb2c25a61e891e76", GitTreeState:"clean", BuildDate:"2022-01-27T02:12:21Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3+k3s1", GitCommit:"5fb370e53e0014dc96183b8ecb2c25a61e891e76", GitTreeState:"clean", BuildDate:"2022-01-27T02:12:21Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
k3s version v1.23.3+k3s1 (5fb370e5)
go version go1.17.5

**Comment by joejulian** [comment]
If you set the file location with a value, you can override that value in the top-level chart.

**Comment by joejulian** [comment]
Since this has sat idle for this long, I'm going to assume this answered your question and close this. I hope it helped.
