### ISSUE TITLE
[QUESTION] changing  value of dependency of dependency

### ISSUE THREAD

**Issue by Krzysztof-Lempicki** [helm/helm#11400]
# Helm version
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}

# Cloud Provider/Platform:
Minikube

# Problem
I am using helm charts this way:

* generic-service chart - is template for any service
* oauth2-service-base - is template for any env. It has dependency `generic-service chart`
* oauth2-service-local - is template for local env. It has dependency `oauth2-service-base chart`

When I override value for `generic-service chart` in  `oauth2-service-base` work as expected.
When I want to override value for `generic-service chart` in `oauth2-service-local` value is not 
overridden,  `oauth2-service-base` value is present.

# Question
Is override of template value of dependency of dependency possible?

**Comment by joejulian** [comment]
This is intentional. Template functions are globally namespaced. That is to say, chart dependencies and the root chart share the same function namespace, so if two charts define a function named _helpers.serviceAccountName, it is undefined which function will be called.

**Comment by Krzysztof-Lempicki** [comment]
@joejulian 

This means that way that I want to use Helm:

`abstract chart -> less abstract chart -> implementation chart` 

is not corresponding with helm architecture.

I want to avoid situation where someone want to create 
chart for `my_new_env` and just copy paste chart from another one
and just changing few values.

How I can achieve that in way that is more corresponding with Helm architecture?

**Comment by joejulian** [comment]
You mention value and template. I think there may be some miscommunication. Can you offer an example that I can duplicate on my own? That would help me offer better advice.

If you have a sample chart directory, you can tar it and drop it in your response.

**Comment by Krzysztof-Lempicki** [comment]
github: "Something went really wrong..." when I drop file.
Link to `we transfer`: https://we.tl/t-admK4ahr6E
