### ISSUE TITLE
UPGRADE FAILED: error validating "": error validating data: unknown object type "nil" in Secret.data.config.yaml

### ISSUE THREAD

**Issue by digbijaya18** [helm/helm#11416]
UPGRADE FAILED: error validating "": error validating data: unknown object type "nil" in Secret.data.config.yaml

**Comment by joejulian** [comment]
This needs more information. My only guess is that you didn't put quotes around "config.yaml" so it thinks you're dereferencing a key named config.

**Comment by bhat-ganesh** [comment]
This seems to be the behaviour on newer version of `helm`. Earlier versions of helm would indicate a warning on the `nil` filed. The new version just errors out.

**This is a big change in behaviour with helm. Is there an option to not error out and just stay with warning?**

Can this be considered a bug?



I ran into this exact issue with my postgres deployment. Here is the behavior change with the newer helm:
```
NEW HELM 

version.BuildInfo{Version:"v3.9.3", GitCommit:"414ff28d4029ae8c8b05d62aa06c7fe3dee2bc58", GitTreeState:"clean", GoVersion:"go1.19"}

Error: UPGRADE FAILED: cannot patch "postgres-postgresql-ha-pgpool" with kind Deployment: The order in patch list:
[map[name:PGPOOL_BACKEND_NODES value:<nil>] map[name:PGPOOL_BACKEND_NODES value:0:my-staging-psql-instance.-north-1.rds.amazonaws.com:5432,] map[name:PGPOOL_NUM_INIT_CHILDREN value:325]]
 doesn't match $setElementOrder list:
 
 [map[name:BITNAMI_DEBUG] map[name:PGPOOL_POSTGRES_CUSTOM_USERS] map[name:PGPOOL_POSTGRES_CUSTOM_PASSWORDS] map[name:PGPOOL_NAMESPACE] map[name:PGPOOL_BACKEND_NODES] map[name:PGPOOL_SR_CHECK_USER] map[name:PGPOOL_SR_CHECK_PASSWORD] map[name:PGPOOL_SR_CHECK_DATABASE] map[name:PGPOOL_ENABLE_LDAP] map[name:PGPOOL_POSTGRES_USERNAME] map[name:PGPOOL_POSTGRES_PASSWORD] map[name:PGPOOL_ADMIN_USERNAME] map[name:PGPOOL_ADMIN_PASSWORD] map[name:PGPOOL_ENABLE_LOAD_BALANCING] map[name:PGPOOL_ENABLE_LOG_CONNECTIONS] map[name:PGPOOL_ENABLE_LOG_HOSTNAME] map[name:PGPOOL_ENABLE_LOG_PER_NODE_STATEMENT] map[name:PGPOOL_NUM_INIT_CHILDREN] map[name:PGPOOL_MAX_POOL] map[name:PGPOOL_CHILD_LIFE_TIME] map[name:PGPOOL_CLIENT_IDLE_LIMIT] map[name:PGPOOL_CONNECTION_LIFE_TIME] map[name:PGPOOL_ENABLE_TLS] map[name:PGPOOL_BACKEND_NODES]]

```

```
OLDER HELM

version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}

W1122 09:39:28.443268   13291 warnings.go:70] spec.template.spec.containers[0].env[5].name: duplicate name "PGPOOL_BACKEND_NODES"
Release "postgres" has been upgraded. Happy Helming!
```

Unfortunately, in my use case with [postgressql-ha chart](https://github.com/bitnami/charts/blob/main/bitnami/postgresql-ha/templates/pgpool/deployment.yaml#L147-L148), I cannot get past this error without manual intervention. The only other way would be to override the entire chart and bypass this error.

If there were an option to not completely error out then it would mean we can continue to work with such chart limitations.

**Comment by joejulian** [comment]
Can you narrow it down to which exact release changed this behavior? If we can find the commit, I can change this to a bug.

**Comment by joejulian** [comment]
I wasn't able to duplicate this. Without more information I'm going to have to agree with the bot and close this.

**Comment by maximveksler** [comment]
we've faced the same issue
