### ISSUE TITLE
helm upgrade --install does not return error code when deployment fails, on helm v3

### ISSUE THREAD

**Issue by davidegiunchi** [helm/helm#11421]
Output of `helm version`:

version.BuildInfo{Version:"v3.10.0", GitCommit:"ce66412a723e4d89555dc67217607c6579ffcb21", GitTreeState:"clean", GoVersion:"go1.18.6"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.13-eks-15b7512", GitCommit:"94138dfbea757d7aaf3b205419578ef186dd5efb", GitTreeState:"clean", BuildDate:"2022-08-31T19:15:48Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): EKS 1.22
```
helm upgrade -f values-prod.yaml web-fo --set build_id=12345 microservices/helm/web-fo -n microservices --install --wait
Error: UPGRADE FAILED: another operation (install/upgrade/rollback) is in progress
```

"helm upgrade --install" returns systematically an exit code to 0 even if the status is FAILURE.
Is there an option to the command which allow returning an error code ? We need this to detect failure on our deployments.
The problem seems to be solved on helm 2, but it's still present on helm3: [https://github.com/helm/helm/issues/4134#issuecomment-1262236351](https://github.com/helm/helm/issues/4134#issuecomment-1262236351) .

Thanks

**Comment by VaibhavSharma-47** [comment]
<img width="716" alt="image" src="https://user-images.githubusercontent.com/43334232/213403670-5d5d747e-c345-4ad0-a06d-a4d02a701bea.png">
I can not reproduce this, is it fixed now ?

**Comment by joejulian** [comment]
I have tested this on v3.11.3 and also get the non-zero exit code on failure. Closing this as cannot reproduce.
