### ISSUE TITLE
helm is not find the corresponding chart

### ISSUE THREAD

**Issue by calvin0327** [helm/helm#11447]
<img width="770" alt="企业微信截图_5c76aeaf-b93f-4512-98bc-e12d44850a14" src="https://user-images.githubusercontent.com/45745657/196328568-a254fffc-320c-424b-a6e6-15e9667524af.png">

When I specify an explicit version, helm doesn't seem to pull the corresponding package.
Is there a problem with the cache?

Output of `helm version`:
`version : 3.6.1`

Output of `kubectl version`:
`v1.20.11`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
generic k8s cluster

**Comment by hickeyma** [comment]
@calvin0327 Do you mind showing the command you are running? Also, what version you expect?

**Comment by joejulian** [comment]
closing due to lack of participation
