### ISSUE TITLE
Command line and values option to lock chart to be applied only to the specific K8s context

### ISSUE THREAD

**Issue by sirantd** [helm/helm#11444]
I'm looking for something that is similar to the terraform's `[allowed_account_ids] - (Optional) List of allowed AWS account IDs to prevent you from mistakenly using an incorrect one (and potentially end up destroying a live environment).`

It would be nice if I could specify in the my-values.yaml some K8s context and if it differs from some I am currently on - it would fail to apply with an error: you are trying to deploy into the wrong cluster.

I understand that it's not the case when you are using CI/CD but when you have more than one cluster and by mistake apply changes to the wrong one. I am also aware of the `helm diff` plugin or `--dry-run`, it's just another safety fuse I'd like to have. Moreover, it can fail much faster because there is no need to get any information from the k8s but just check the context locally.

**Comment by joejulian** [comment]
This sounds like it could be able to be implemented as a plugin. You might give the [plugins guide](https://helm.sh/docs/topics/plugins/) a look and see if you can implement something there. Could be a good project.

**Comment by sirantd** [comment]
It could work but require adding an alias to the helm command to call the helm with the plugin name instead. I don't see other ways how to call some plugin each time if it's just installed.

Anyway, thx for the idea, will check how to implement it.

**Comment by joejulian** [comment]
Since there was an answer and no further discussion, I'm going to close this as solved.
