### ISSUE TITLE
unable to install helm on minikube-redhat linux

### ISSUE THREAD

**Issue by hemanthmoorthy** [helm/helm#11450]
$ curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 
$ chmod 700 get_helm.sh 
$ ./get_helm.sh

Error message: Helm v3.10.1 is installed helm not found.Is /usr/local/bin on your $PATH?
 Failed to install helm

Please help on this

**Comment by joejulian** [comment]
Is `/usr/local/bin` on your $PATH?

**Comment by joejulian** [comment]
closing due to lack of participation
