### ISSUE TITLE
`snakecase` template function turns `abc_123_def` into `abc_123__def`

### ISSUE THREAD

**Issue by jwhitaker-swiftnav** [helm/helm#11458]
As per the title, running
```
{{ "abc_123_def" | snakecase }}
```
in my template gives`abc_123__def`. I would expect it to give `abc_123_def`.

I've tracked down the issue to an indirect dependency and raised a PR - https://github.com/huandu/xstrings/pull/52 . However I still want to raise this in helm directly to track until it's fixed and updated.

Thanks!

Output of `helm version`:
```
version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"clean", GoVersion:"go1.17.13"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:26Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.10-eks-15b7512", GitCommit:"cd6399691d9b1fed9ec20c9c5e82f5993c3f42cb", GitTreeState:"clean", BuildDate:"2022-08-31T19:17:01Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
N/A

**Comment by yxxhero** [comment]
@hickeyma  we need to upgrade https://github.com/Masterminds/sprig if https://github.com/huandu/xstrings/pull/52 has been merged.

**Comment by hickeyma** [comment]
@yxxhero would you like to push a PR to https://github.com/Masterminds/sprig?

**Comment by yxxhero** [comment]
@hickeyma yes. if https://github.com/huandu/xstrings is released. I will push a PR for this issue.

**Comment by yxxhero** [comment]
see: https://github.com/Masterminds/sprig/pull/348

**Comment by yxxhero** [comment]
@mattfarina ping

**Comment by yxxhero** [comment]
see: https://github.com/helm/helm/pull/11582
