### ISSUE TITLE
Helm dependency update recursive

### ISSUE THREAD

**Issue by nodesocket** [helm/helm#11457]
How can I run `helm dependency update` recursively in the top level directory instead of having to do:

```bash
cd DevOps/helm

for chart in "fusionauth" "minio" "postgresql" "rabbitmq" "redis" "traefik"; do
    cd $chart || exit 3
    helm dependency update --skip-refresh
done
```

This step is very slow and pulls down the Bitnami common chart over and over again.

**Comment by joejulian** [comment]
Can you just make a wrapper chart do which all of those are dependencies?

**Comment by nodesocket** [comment]
@joejulian thanks for the reply. I'd prefer not to have to create a wrapper chart. All the above charts are 3rd party and auxility support applications needed for our core applications. Our core applications are a series of Helm charts, not a single.

**Comment by joejulian** [comment]
The only other idea I can think of would be to set up a pull through caching proxy. That way even though it's pulling the bitnami core, it's doing it locally.

**Comment by nodesocket** [comment]
@joejulian interesting about setting up a caching proxy. Can you elaborate or have any links on setting this up? Is it possible using just [Caddy](https://caddyserver.com/)?

**Comment by joejulian** [comment]
I haven't done so in a long time. Last time I did it was using squid to manage my (now 28 year old) son's internet access.

**Comment by joejulian** [comment]
Hope that helped. Closing.
