### ISSUE TITLE
Private dependencies on Chart preventing marshalling dependencies

### ISSUE THREAD

**Issue by derpsteb** [helm/helm#11454]
Hey everyone,
I am trying to send a chart with local dependencies over the wire. To do so I tried marshaling the chart with `json.Marshal`. Since the `dependencies` field in the [Chart](https://github.com/helm/helm/blob/main/pkg/chart/chart.go#L56) type is private, the field is not marshalled. Currently using v3.9.4.

What is the intended way of marshaling a `Chart` object? 

Looking at [helm package](https://helm.sh/docs/helm/helm_package/) we have the problem that the chart is loaded from an `embed.FS`. Would you be interested in a patch that allows running [package](https://pkg.go.dev/helm.sh/helm/v3@v3.9.4/pkg/action#Package.Run) on an `embed.FS`?

Thanks already.

**Comment by joejulian** [comment]
I don't see any reason why not.

**Comment by derpsteb** [comment]
Thanks for the answer :)

I found [chartutil.Save](https://pkg.go.dev/helm.sh/helm/v3@v3.10.1/pkg/chartutil#Save) by now, which pretty much does exactly what I needed. Reading the chart with a slightly modified version of loadDir and then putting it into `Save` gives me the .tgz I needed.
