### ISSUE TITLE
How to add AWS ECR oci repo

### ISSUE THREAD

**Issue by Hammond95** [helm/helm#11452]
Output of `helm version`: `version.BuildInfo{Version:"v3.10.0", GitCommit:"ce66412a723e4d89555dc67217607c6579ffcb21", GitTreeState:"clean", GoVersion:"go1.18.6"}`

Output of `kubectl version`: 

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  `AWS`

============

AWS ECR gives you a way to push helm charts and use it as repo for charts via OCI support.

I am able to push helm charts on ECR, as explained here on their docs: https://docs.aws.amazon.com/AmazonECR/latest/userguide/push-oci-artifact.html.

But unfortunately I am unable to add the ECR as helm repo registry.
I tried different things and I think that this commands, is the closest I got:

```bash
> export HELM_EXPERIMENTAL_OCI=1

> aws ecr get-login-password --region eu-west-1 | helm repo add adtech oci://[[AWS_ACCOUNT]].dkr.ecr.eu-west-1.amazonaws.com --username AWS --password-stdin --debug

Error: looks like "oci://[[AWS_ACCOUNT]].dkr.ecr.eu-west-1.amazonaws.com" is not a valid chart repository or cannot be reached: object required
helm.go:84: [debug] object required
looks like "oci://[[AWS_ACCOUNT]].dkr.ecr.eu-west-1.amazonaws.com" is not a valid chart repository or cannot be reached
main.(*repoAddOptions).run
	helm.sh/helm/v3/cmd/helm/repo_add.go:211
main.newRepoAddCmd.func1
	helm.sh/helm/v3/cmd/helm/repo_add.go:82
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.5.0/command.go:872
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.5.0/command.go:990
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.5.0/command.go:918
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
	runtime/proc.go:250
runtime.goexit
	runtime/asm_amd64.s:1571
```

Is this a known bug or is there a way to fix this?

I don't think this is a reachability problem since I am able to perform the push of a chart.

**Comment by Hammond95** [comment]
I see that also the issue #10892 has a similar problem, and the root cause may be AWS not providing an index.yaml endpoint as stated in this comment https://github.com/helm/helm/issues/10892#issuecomment-1279544202, and somehow confirmed by this open issue on aws roadmap https://github.com/aws/containers-roadmap/issues/1603.

**Comment by Hammond95** [comment]
I am still wondering if there is a workaround 🤔

**Comment by joejulian** [comment]
I know you can `helm install asdf https://charts.redpanda.com/redpanda-2.2.1.tgz`, can you do the same using `oci://...`?

**Comment by Hammond95** [comment]
The `helm install --help` says the following:

```
There are six different ways you can express the chart you want to install:

1. By chart reference: helm install mymaria example/mariadb
2. By path to a packaged chart: helm install mynginx ./nginx-1.2.3.tgz
3. By path to an unpacked chart directory: helm install mynginx ./nginx
4. By absolute URL: helm install mynginx https://example.com/charts/nginx-1.2.3.tgz
5. By chart reference and repo url: helm install --repo https://example.com/charts/ mynginx nginx
6. By OCI registries: helm install mynginx --version 1.2.3 oci://example.com/charts/nginx
```

So I think the answer is yes. But I perform the installation using helmfile, never tried with helm directly.

**Comment by joejulian** [comment]
I checked. The answer is yes. It looks like the issue you're having a problem with is helmfile support. I'm going to go ahead and close this issue.

**Comment by artemptushkin** [comment]
helm: 3.12.0

for anyone who's searching how to **just pull** a chart from AWS ECR repo, from [here](https://stackoverflow.com/a/73264017/7785738):

```shell
AWS_PROFILE=ss aws ecr get-login-password --region eu-central-1 | helm registry login 123.dkr.ecr.eu-central-1.amazonaws.com --username AWS --password-stdin

helm pull oci://123.dkr.ecr.eu-central-1.amazonaws.com/my-helm-chart
```

Expect `*.tgz` file locally
