### ISSUE TITLE
Helm release secret storage optimization ?

### ISSUE THREAD

**Issue by ValentinOzanne** [helm/helm#11464]
Hello,

We are facing some issues with helm release storage in k8s in a growing project. We encounter such error :  
`Error: UPGRADE FAILED: create: failed to create: Secret "sh.helm.release.v1.xxxxxxxxxx.v16" is invalid: data: Too long: must have at most 1048576 bytes`

After analysis the content of the secret, I would like to share some optimization suggestion regarding the content of this secret:
- Data content : It seems the global values are replicated on each subchart. Would it be possible to make helm store them only one at top level ?
- Data encoding : it seems that data is encoded twice in Base64 before gzip: would it be possible to remove the second Base64  encoding step ?

**Comment by joejulian** [comment]
It's not actually double base64 encoded. When you `kubectl get secret` it's output base64 encoded. Try it out:

```
$ kubectl create secret generic foo --from-literal test="The quick brown fox jumps over the lazy yellow dog."
secret/foo created
$ kubectl get secret foo -o yaml
apiVersion: v1
data:
  test: VGhlIHF1aWNrIGJyb3duIGZveCBqdW1wcyBvdmVyIHRoZSBsYXp5IHllbGxvdyBkb2cu
kind: Secret
metadata:
  name: foo
  namespace: default
type: Opaque
```

**Comment by ValentinOzanne** [comment]
Hello @joejulian 

Regarding Data encoding suggestion, I was talking about the following encoding workflow of a helm release stored in a secret

1. gzip compress - Helm zipping
2. base64 encoding  - Helm encoding :  **?? necessary ??**
3. base64 encoding (again) - Kubernetes secrets encoding

cf. https://gist.github.com/DzeryCZ/c4adf39d4a1a99ae6e594a183628eaee

=> It seems your example is showing a simple k8s secret, not a helm release data. The Data encoding optimization question is related to the step 2 (base64 encoding by Helm that seems to be redundant with secret encoding.

**Comment by joejulian** [comment]
Not sure how I lost track of this, sorry. I understand what you're asking, now, and the short answer for helm 3 is "no". Changing the storage would be a breaking change.

I remember looking at this ages ago and finding that there was, indeed, a reason and it had something to do with the storage abstraction. Unfortunately I've forgotten the details.

I'm sure when it comes time for helm 4 planning, storage changes will be a part of that.
