### ISSUE TITLE
Does Helm support adopting K8S resources created during the upgrade/rollback process, for example, a resource created by a helm hook job 

### ISSUE THREAD

**Issue by Shiva19908** [helm/helm#11469]
Hi Guys,
Does helm adopt resources created by a helm hook, for example, a resource created by a helm pre-upgrade hook? We are getting below error during the upgrade:
`upgrade.go:434: [debug] warning: Upgrade "abc" failed: no Service with the name "abc-headless" found
Error: UPGRADE FAILED: no Service with the name "abc-headless" found
helm.go:84: [debug] no Service with the name "abc-headless" found
helm.sh/helm/v3/pkg/kube.(*Client).Update.func1
        helm.sh/helm/v3/pkg/kube/client.go:257
helm.sh/helm/v3/pkg/kube.ResourceList.Visit
        helm.sh/helm/v3/pkg/kube/resource.go:32
helm.sh/helm/v3/pkg/kube.(*Client).Update
        helm.sh/helm/v3/pkg/kube/client.go:230
helm.sh/helm/v3/pkg/action.(*Upgrade).releasingUpgrade
        helm.sh/helm/v3/pkg/action/upgrade.go:376
runtime.goexit
        runtime/asm_amd64.s:1571
UPGRADE FAILED
main.newUpgradeCmd.func2
        helm.sh/helm/v3/cmd/helm/upgrade.go:201
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.5.0/command.go:872
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.5.0/command.go:990
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.5.0/command.go:918
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
        runtime/proc.go:250
runtime.goexit
        runtime/asm_amd64.s:1571` 

What we are doing is:
We are creating a K8S service in the pre-upgrade hook job and adding relevant labels and annotations so that Helm would adopt this service. But this is not working as expected i.e., Helm is throwing above error and is not adopting the created K8S service. However, if we create the same K8S service before the upgrade (i.e., before running helm upgrade command), Helm adopts the resource and works as expected. Furthermore, if we run helm upgrade again the second time after it failed the first time with the above error it passes and works as expected i.e., Helm adopts the K8S service! Hence, we would like to know if Helm supports adopting of resources created during the upgrade process, for example, by a hook job?

Output of `helm version`: version.BuildInfo{Version:"v3.10.1", GitCommit:"9f88ccb6aee40b9a0535fcc7efea6055e1ef72c9", GitTreeState:"clean", GoVersion:"go1.18.7"} 

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"51351e76484eb80accdd7702d9bd03652ad830b3", GitTreeState:"clean", BuildDate:"2022-05-20T08:46:07Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  K8S

**Comment by Shiva19908** [comment]
It seems here in this function call the "adoption" will happen

https://github.com/helm/helm/blob/7ed9d16dc764a5b94b378a7e217865efaa0d9ac8/pkg/action/upgrade.go#L299

after that line in same function, the pre-upgrade hooks would be executed by this function https://github.com/helm/helm/blob/7ed9d16dc764a5b94b378a7e217865efaa0d9ac8/pkg/action/upgrade.go#L330

i think that if a hook creates resources to be adopted, it would be too late. Is my observation correct? If so, would helm support adopting resources created during the upgrade or rollback process?

**Comment by joejulian** [comment]
You are correct, it's too late. The adoption is checked before any resources are applied in order to prevent part of the manifest from being applied only to find out part way through that one of the resources already exists and can't be adopted.

**Comment by Shiva19908** [comment]
hi @joejulian thanks for the confirmation :)

**Comment by Shiva19908** [comment]
hi @joejulian thanks for the confirmation :)
