### ISSUE TITLE
Option to recreate pods as part of the --atomic flag

### ISSUE THREAD

**Issue by bsloan-icl** [helm/helm#11468]
Is it possible to recreate pods if a helm upgrade fails? We currently have Jenkins installed on AKS via the helm chart and it would be useful to automatically rollback the release if the upgrade fails. For example, after running helm upgrade there could be an imagepullbackoff error. When using the --atomic flag the release will be rolled back but the pods remain in the imagepullbackoff state. It currently requires manual intervention to delete the imagepullbackoff pods and restore Jenkins to a working state.

**Comment by joejulian** [comment]
As long as your apps/v1 resource changes, the rollback should change it back, ie. if your Deployment changes because your image tag changed, when it rolls back it'll revert that tag change, which will change the Deployment and cause Kubernetes to scale down the errant ReplicaSet and create a new one.

If that's not happening, I think it's only possible if your app resource is a hook. Hooks are a bit special.

**Comment by bsloan-icl** [comment]
Jenkins uses a stateful set and when using the --atomic flag it does revert the faulty tag change but the stateful set isn't scale down. Looking at the docs https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#forced-rollback it looks like this is a k8s issue rather than helm.

**Comment by joejulian** [comment]
Or it's a Jenkins chart issue if it doesn't need OrderReady (I don't know if it does). OrderReady is the default but maybe it could work with Parallel? If it could, I think that wouldn't need the same manual intervention.

The manual intervention need for OrderReady STS is valid. If all the pods were rolled, you could lose quorum and potentially lose data. You definitely don't want Helm forcefully rolling pods.

**Comment by bsloan-icl** [comment]
Hmm interesting idea. I'll have to do some digging and see if parallel is something we could use. Thanks a lot for your help joejulian. I'll go ahead and close this issue.
