### ISSUE TITLE
Flags in helm package command

### ISSUE THREAD

**Issue by dcristobalhMad** [helm/helm#11466]
To improve the CI/CD system, would it be possible to set values as variables and the chart version in cli? OCI approach. Example:

`helm package ./test-chart --version 1.2.3 --set repository.image=nginx:latest`

I believe that this facilitates the software life cycle and could be a standard in the future.

**Comment by joejulian** [comment]
This isn't something that helm supports. You might be able to write a [helm plugin](https://helm.sh/docs/topics/plugins/) to get that behavior.

**Comment by dcristobalhMad** [comment]
Hey @joejulian, there seems to be a PR solving this, right? #11460  Sorry if I have misunderstood something

**Comment by joejulian** [comment]
Ah, I wasn't aware. Thanks!

**Comment by dcristobalhMad** [comment]
Hey @joejulian , no worries. After put my comment I saw it xD. Anyway I am going to close this issue, It does not make sense right now. Thanks!!
