### ISSUE TITLE
Add supporting of output flag at helm get manifest

### ISSUE THREAD

**Issue by AssafKatz3** [helm/helm#11471]
Hi,

The idea is to use a similar code (or the same) as `kubectl get`, so it will be possible to get the list of all managed resources of a specific release. This will be useful for examing the current status of resources that were created by release.
The command will be for example:
`helm get manifest kafka -o name`
This will be backward compatibility by defining the default value to be yaml (unlike kubectl get).
Thanks
N.B. It will be useful for hooks subcommand also.

**Comment by joejulian** [comment]
`helm get manifest` already outputs all the resources in yaml. If you could add come context around what your end-goal is, perhaps there's a way to accomplish it already.

**Comment by AssafKatz3** [comment]
> `helm get manifest` already outputs all the resources in yaml. If you could add come context around what your end-goal is, perhaps there's a way to accomplish it already.

Hi,
I want to pass specific resources type to kubectl wait, today I need to parse the output YAML, and then I can use it. In addition, I want to know the resources in which the microservice (=release) is used, and it is hard to do it with YAML. In other words, I want to pass a list of resources to kubectl subcommands, and it is hard to do it currently.
Thanks

**Comment by joejulian** [comment]
I do that with `yq` filtering, ie:
```
helm get manifest foo | yq -y 'select(.kind == "Deployment")' | kubectl wait --for condition=avalable -f -
```

**Comment by AssafKatz3** [comment]
> I do that with `yq` filtering, ie:
> 
> ```
> helm get manifest foo | yq -y 'select(.kind == "Deployment")' | kubectl wait --for condition=avalable -f -
> ```

Hi,
I don't have yq in my image so I used python for it, I still think that it is useful enough for adding it to HELM itself.
Thanks

**Comment by joejulian** [comment]
So if you wanted to add this, I would probably see if there's a way to just use the output library from kubectl, that way you could get all the different formats:
```
(-o|--output=)json|yaml|name|go-template|go-template-file|template|templatefile|jsonpath|jsonpath-as-json|jsonpath-file|custom-columns|custom-columns-file|wide
```
I'd start by looking here: https://github.com/helm/helm/blob/7ed9d16dc764a5b94b378a7e217865efaa0d9ac8/cmd/helm/get_manifest.go#L57

If you need any help, come ask at the weekly developer meeting. There's always someone willing to spend a little time helping contributors.

**Comment by AssafKatz3** [comment]
Hi,
We still need this feature, even though some time has passed. We’re planning to integrate 'helm lint' into various systems and would like to read and process its output automatically.

Thanks
