### ISSUE TITLE
[Suggestion] macOS release binaries are not Code-signed with a developer or team ID

### ISSUE THREAD

**Issue by virtualpeter** [helm/helm#11473]
Referring to the apple developer Codesigning in particular, but similar consideration could be made for binaries intended to run on Windows11

Looking at released macOS binaries for v3.10.1:
* The arm64 binary has an 'ad-hoc' signature 
* The x86_64 binary is not signed

So, they are not even consistently signed, but also not signed in a way that is useful for desktop software today.

It seems like the topic has been mentioned before at cncf but went stale. https://github.com/cncf/tag-security/issues/558

**Comment by joejulian** [comment]
Everyone that might be able to so much as comment on this is at Kubecon this week.
