### ISSUE TITLE
Helm template post-render doesn't work if set --output-dir

### ISSUE THREAD

**Issue by clintmod** [helm/helm#11475]
https://github.com/helm/helm/issues/10115

**Comment by clintmod** [comment]
Creating duplicate issue that's open because the stupid stale bot closed it.

**Comment by clintmod** [comment]
I can confirm that this is still a problem with:

```
helm version
version.BuildInfo{Version:"v3.10.1", GitCommit:"9f88ccb6aee40b9a0535fcc7efea6055e1ef72c9", GitTreeState:"clean", GoVersion:"go1.19.2"}
```

**Comment by joejulian** [comment]
Closing this and responded in the original. This is not something that can be done in helm.
