### ISSUE TITLE
apt package installation of Helm not possible from IPv6-only host since baltocdn.com is IPv4-only

### ISSUE THREAD

**Issue by AndiDog** [helm/helm#11476]
I'm trying to set up an IPv6-only Kubernetes cluster. To install the desired CNI, I want Helm. To install Helm, I want to [install it via apt](https://helm.sh/docs/intro/install/#from-apt-debianubuntu) in order to get updates automatically. But because the host only has a IPv4 record, it cannot be reached.

You'd get an error like

```
Cannot initiate the connection to baltocdn.com:443 (151.139.128.10). - connect (101: Network is unreachable)
```

DNS record lookup:

```
$ host baltocdn.com
baltocdn.com has address 151.139.128.10
```

Can the Debian/Ubuntu packages be placed on a hoster that supports IPv6?

Sadly, on the same note, installation from script also fails:

```
# curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11156  100 11156    0     0   217k      0 --:--:-- --:--:-- --:--:--  217k
Downloading https://get.helm.sh/helm--linux-amd64.tar.gz
Verifying checksum... SHA sum of /tmp/helm-installer-3eMsyC/helm--linux-amd64.tar.gz does not match. Aborting.
Failed to install helm
	For support, go to https://github.com/helm/helm.
```

That's because it gets the latest version from `github.com/...`, a host which again isn't ready for IPv6 🫣 (https://github.com/community/community/discussions/10539). The script-based installation works only if you specify the `DESIRED_VERSION` variable explicitly.

**Comment by joejulian** [comment]
I think you have two options. One is to host a mirror of the baltocdn apt repo on an ipv6 host, or add a nat64 gateway. For some reason the world still, after all these years, isn't ready for IPv6.
