### ISSUE TITLE
The helm data type is automatically converted

### ISSUE THREAD

**Issue by isyinun** [helm/helm#11488]
Output of `helm version`:v3.7.1

Output of `kubectl version`:v1.20.8

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

The helm package xxx package command creates packaging and compression 1.0, 2.0 et. are automatically converted to 1, 2 et.

![image](https://user-images.githubusercontent.com/46102310/198916511-6d29a029-245e-4a5f-b112-02c2b61361e6.png)

![image](https://user-images.githubusercontent.com/46102310/198917984-671d29f6-865a-4792-a541-6b3533778ff4.png)

**Comment by joejulian** [comment]
This is because `2.0`, in json, is a float. Normally folks don't see this because they use full semantic versions, ie 2.0.0 which is a string. If you want a two position version, you'll need to enclose it in quotes:
```
version: "2.0"
```

**Comment by isyinun** [comment]
Yes, I also found what you said thanks!But is it necessary for helm to optimize not to convert 2.0 to 2?

**Comment by joejulian** [comment]
No, that's the job of the yaml parser and it's doing that job correctly.
