### ISSUE TITLE
upgrade by helm:  spec.containers[0].ports[5].hostPort: Duplicate value: "TCP//10044"

### ISSUE THREAD

**Issue by moozooooo** [helm/helm#11486]
I want to mofiy hostPort to containerPort：
Before:

           - hostPort: 10044
              containerPort: 4990
              protocol: TCP

I want to change 4990 to 8000, like this:

           - hostPort: 10044
              containerPort: 8000
              protocol: TCP

But upgrade by helm, get this wrong:

**spec.containers[0].ports[5].hostPort: Duplicate value: "TCP//10044"**.

Why does this happen? 
What shoud I do?

Output of `helm version`:
v3.8.2
Output of `kubectl version`:
v1.20.0

**Comment by yxxhero** [comment]
@moozooooo 
please try use:

```bash
--force                                      force resource updates through a replacement strategy
```

**Comment by moozooooo** [comment]
> @moozooooo please try use:
> 
> ```shell
> --force                                      force resource updates through a replacement strategy
> ```
> 
> this flag will use replace strategy, please test it on your test environment. Thanks very much.

tks, I try this, but,find another problem:

`Error: UPGRADE FAILED: failed to replace object: Service "service-clusterip" is invalid: spec.clusterIPs[0]: Invalid value: []string(nil): primary clusterIP can not be unset`

because, in the chart template, there is service-clusterip.
why service-clusterip got this wrong? what should I do?

**Comment by joejulian** [comment]
It looks like the upgrade is merging the lists where the values initially installed with the chart and the new values are two distinct list items, causing that duplicate value (without names, that will happen). The solution is probably to use `--reset-values` which will completely replace the values with those in your values file. Be sure this is what you want to happen (it sounds to me like it probably is).
