### ISSUE TITLE
Invalid Manifest Pushing to AWS ECR

### ISSUE THREAD

**Issue by rpf3** [helm/helm#11482]
I am using Helm to push a chart to Amazon ECR.  However it appears that the chart manifest is missing metadata that is expected by AWS.  After hearing back from the AWS ECR team, they suggested opening an issue here to continue the debugging.  The full thread is [here](https://github.com/aws/aws-sdk/issues/193) but the short of it is that the payload to AWS is missing the `imageManifestMediaType` property as described [here](https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_PutImage.html#API_PutImage_RequestSyntax).

Output of `helm version`:

> version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.5"}

Output of `kubectl version`:

> Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-6d3986b", GitCommit:"8877a3e28d597e1184c15e4b5d543d5dc36b083b", GitTreeState:"clean", BuildDate:"2022-07-20T22:05:32Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

AWS

**Comment by joejulian** [comment]
According to their documentation:

> [imageManifestMediaType](https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_PutImage.html#API_PutImage_RequestSyntax)
> 
>     The media type of the image manifest. If you push an image manifest that does not contain
>     the mediaType field, you must specify the imageManifestMediaType in the request.

Since the OCI spec requires the mediaType field and helm provides it, I don't understand why they would be expecting their non-standard property.

**Comment by joejulian** [comment]
I'm going to close this assuming that my query was sufficient.
