### ISSUE TITLE
Helm create uses old HPA Version

### ISSUE THREAD

**Issue by userbradley** [helm/helm#11495]
[Jump to issue](#issue)

Output of `helm version`: 

```shell
➜ helm version    
version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"clean", GoVersion:"go1.17.13"}
```

Output of `kubectl version`:

```shell
➜ kubectl version                                    
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:26Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3-gke.2100", GitCommit:"25d7334511e90d0b636707059c955baebce769cd", GitTreeState:"clean", BuildDate:"2022-08-16T09:24:54Z", GoVersion:"go1.18.3b7", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  GKE, v1.24.3-gke.2100

# Issue

When creating a new helm chart using `helm create <chart>` the HPA is using an old outdated and soon to be deprecated version

<details>
<summary>Warning</summary>

_note: Task is just a better version of makefile, the command it runs is `helm upgrade <reelase> <chart>

```shell
➜ task upgrade
task: [upgrade] helm upgrade $releaseName $chart
W1102 13:34:17.245653   42748 warnings.go:70] autoscaling/v2beta1 HorizontalPodAutoscaler is deprecated in v1.22+, unavailable in v1.25+; use autoscaling/v2 HorizontalPodAutoscaler
W1102 13:34:17.269708   42748 warnings.go:70] autoscaling/v2beta1 HorizontalPodAutoscaler is deprecated in v1.22+, unavailable in v1.25+; use autoscaling/v2 HorizontalPodAutoscaler
W1102 13:34:20.310690   42748 warnings.go:70] autoscaling/v2beta1 HorizontalPodAutoscaler is deprecated in v1.22+, unavailable in v1.25+; use autoscaling/v2 HorizontalPodAutoscaler
W1102 13:34:20.438095   42748 warnings.go:70] autoscaling/v2beta1 HorizontalPodAutoscaler is deprecated in v1.22+, unavailable in v1.25+; use autoscaling/v2 HorizontalPodAutoscaler
W1102 13:34:20.463040   42748 warnings.go:70] autoscaling/v2beta1 HorizontalPodAutoscaler is deprecated in v1.22+, unavailable in v1.25+; use autoscaling/v2 HorizontalPodAutoscaler
W1102 13:34:20.488023   42748 warnings.go:70] autoscaling/v2beta1 HorizontalPodAutoscaler is deprecated in v1.22+, unavailable in v1.25+; use autoscaling/v2 HorizontalPodAutoscaler

```
</details>

The Deprecation notice is [Here](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#horizontalpodautoscaler-v126)

What would be nice to see is the New version:

## Issues related

https://github.com/helm/helm/issues/10710

**Comment by joejulian** [comment]
A fix for this should include a test that fails if any resource [here](https://github.com/helm/helm/blob/main/pkg/chartutil/create.go) receives a deprecation warning.

**Comment by hzliangbin** [comment]
@joejulian I am interested in this issued, may i take it?

**Comment by joejulian** [comment]
@hzliangbin please do, yes.

**Comment by wujunwei** [comment]
> A fix for this should include a test that fails if any resource [here](https://github.com/helm/helm/blob/main/pkg/chartutil/create.go) receives a deprecation warning.

@joejulian   It's hard to judge a resource rendered by a helm manifest is deprecated or not. it was affected by the version of users' k8s .we should handle it like ingress.
https://github.com/helm/helm/blob/3974136b6eba92f17a821aac52a80b59a9fa1202/pkg/chartutil/create.go#L223-L229
@hzliangbin  If you are too busy to fix it, I'd like to do it for you :-)

**Comment by joejulian** [comment]
> > A fix for this should include a test that fails if any resource [here](https://github.com/helm/helm/blob/main/pkg/chartutil/create.go) receives a deprecation warning.
> 
> @joejulian   It's hard to judge a resource rendered by a helm manifest is deprecated or not. it was affected by the version of users' k8s .we should handle it like ingress.
> https://github.com/helm/helm/blob/3974136b6eba92f17a821aac52a80b59a9fa1202/pkg/chartutil/create.go#L223-L229
> @hzliangbin  If you are too busy to fix it, I'd like to do it for you :-) 

True, but for testing purposes we can use the [linter deprecations](https://github.com/helm/helm/blob/main/pkg/lint/rules/deprecations.go).

**Comment by wujunwei** [comment]
> True, but for testing purposes we can use the [linter deprecations](https://github.com/helm/helm/blob/main/pkg/lint/rules/deprecations.go).

I have tried it, we can't use lint releative package in  [create.go](https://github.com/helm/helm/blob/main/pkg/chartutil/create.go),it will cause `import cycle not allowed in test`

**Comment by wujunwei** [comment]
> True, but for testing purposes we can use the [linter deprecations](https://github.com/helm/helm/blob/main/pkg/lint/rules/deprecations.go).

[linter deprecations](https://github.com/helm/helm/blob/main/pkg/lint/rules/deprecations.go) depends on LDFLAGS  which is not set when test uint case, it's 1.20 by default. it will lead to `autoscaling/v2beta1` is not regarded as deprecated.
https://github.com/helm/helm/blob/7838fb769d00f53c858d994a873f42c2960a7d25/pkg/lint/rules/deprecations.go#L30-L34
If we set ldflags when testing , `helm template` test case may face faill because of template 's annotation is diff from k8s version 
https://github.com/helm/helm/blob/21e694e0f9575700f16f6c87002c6ccdc434edc4/cmd/helm/testdata/output/template-show-only-multiple.txt#L10-L12

we can also set the variate `k8sVersionMinor `  and all "helm template" 's output to version 25. it case that we should keep the variate `k8sVersionMinor`  same with the version of `k8s.io` package which we used.

Is there a plan to have the best of both worlds?

PS: it means some currenct test cases may have bugs, because of  Fixed variate `k8sVersionMinor=20`

**Comment by hzliangbin** [comment]
@wujunwei just take it

**Comment by joejulian** [comment]
> > True, but for testing purposes we can use the [linter deprecations](https://github.com/helm/helm/blob/main/pkg/lint/rules/deprecations.go).
> 
> [linter deprecations](https://github.com/helm/helm/blob/main/pkg/lint/rules/deprecations.go) depends on LDFLAGS `k8sVersionMinor ` which is not set when test uint case, it's 1.20 by default. it will lead to `autoscaling/v2beta1` is not regarded as deprecated.
> 
> https://github.com/helm/helm/blob/7838fb769d00f53c858d994a873f42c2960a7d25/pkg/lint/rules/deprecations.go#L30-L34

My intention was always to come back at this and make those override-able with a cli flag.

**Comment by wujunwei** [comment]
> My intention was always to come back at this and make those override-able with a cli flag.

I have a few question about it, how to do it when testing? and what's the content in test case about it ?
https://github.com/helm/helm/blob/21e694e0f9575700f16f6c87002c6ccdc434edc4/cmd/helm/testdata/output/template-show-only-multiple.txt#L10-L12
