### ISSUE TITLE
plugin install command needs git

### ISSUE THREAD

**Issue by Wonong** [helm/helm#11492]
It looks that `helm plugin install` command needs git to be installed.
When I execute command in machine where git is not installed, i found error message like link below
https://github.com/snapcrafters/helm/issues/15

because of this issue, `snapcratfers` developers updated their required packages configuration.
https://github.com/snapcrafters/helm/pull/51/files#diff-56759910381a014fecfd7556dd72ddd68c747d922a5b7df2044b9ce7c552f5f5R27

So, how about changing `get-helm-3` script like below to notify users? 
here is an example I think.
https://github.com/Wonong/helm/commit/9e21460515d836cb7169acb3e7615800778fd7e1

**Comment by yxxhero** [comment]
@Wonong PRs is welcome. thanks very much.
