### ISSUE TITLE
UPGRADE FAILED could not get information about the resource

### ISSUE THREAD

**Issue by clcc2019** [helm/helm#11499]
UPGRADE FAILED: could not get information about the resource: proto: wrong wireType = 5 for field ContentEncoding

I can get this resource，It is normal when I delete this deployment

Output of `helm version`:
v3.9.0

Output of `kubectl version`: 
v1.22.11

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Self

**Comment by joejulian** [comment]
What kubernetes version?

**Comment by clcc2019** [comment]
> What kubernetes version?

kubernetes v1.22.11

**Comment by phil9909** [comment]
Can you provide some reproductions steps?
