### ISSUE TITLE
docker feed: quay.io empty search results

### ISSUE THREAD

**Issue by mac2000** [helm/helm#11507]
**steps:**
- add quay.io docker feed to octopus cloud
- press save and test
- try search for any image

**expected:** search results found something

**actual:** empty results

<img width="727" alt="image" src="https://user-images.githubusercontent.com/88868/199929249-82744f70-6aa4-41f8-888f-08a44e61cc2e.png">

> note: it does not matter if anonymous or username with password is used

**Comment by yxxhero** [comment]
@mac2000 sorry. I can't find anything about helm?

**Comment by mac2000** [comment]
Oh my gosh how stupid I am 🤷‍♂️

I was believing I am creating issue in octopus deploy repository

Sorry 

> probably that’s a result of having quadrillion of open tabs in browser while trying to figure out why something does not work

**Comment by mac2000** [comment]
Oh my gosh how stupid I am 🤷‍♂️

I was believing I am creating issue in octopus deploy repository

Sorry 

> probably that’s a result of having quadrillion of open tabs in browser while trying to figure out why something does not work
