### ISSUE TITLE
helm list -A does not show the correct namespace

### ISSUE THREAD

**Issue by fe-dagostino** [helm/helm#11519]
Output of `helm version`:  
    v3.10.1+g9f88ccb

Output of `kubectl version`:  
    Client Version: v1.25.3
    Kustomize Version: v4.5.7
    Server Version: v1.25.0

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
    minikube version: v1.27.0
    commit: 4243041b7a72319b9be7842a7d34b6767bbdac2b

---
How to see the problem:
- suppose to have a chart named "mychart"
- create a file  namespace.yaml inside template such as  the following:
              apiVersion: v1
              kind: Namespace
              metadata:
                name: {{ .Values.namespace }}
- in deployment.yaml as well as service.yaml specify the name space as part of metadata eg. the following:
              apiVersion: apps/v1              
              kind: Deployment
              metadata:
                name: {{ include "mychart.fullname" . }}
                namespace: {{ .Values.namespace }}
- set namespace in values.yaml  for example to development as for the following:
              namespace: development
- now that you have a Chart ready to go execute helm:
              helm install mychart
note: without to specify namespace due to the fact we have namespace.yaml for that.

Result: 
- namespace.yaml --- (OK) cause to create a new namespace "development" if we follow the example above
- deployment.yaml --- (OK) application due to metadata is installed in the correct namespace and so under
- service.yaml -- (OK) is installed accordingly with the namespace in metadata

so executing :
  Kubectl get all -A 

all seems to be in the correct place.

Instead executing:
  helm list -A

mychart result under namespace "default" and not under namespace "development" as expected.
The workaround is to force the namespace calling helm with -n option, but I guess this result is inconsistent since de facto all have installed under a "development" namespace.

Also moving namespace.yaml as template no make anymore sense if I have to double it both in values.yaml as well as during installation.

So, expected result should be to have helm list -A reporting the installation namespace accordingly with the installation or report an error in order to avoid an inconsistent status and to force user to work correctly.

**Comment by joejulian** [comment]
This is the correct behavior. You're installing the helm release in `default` by not specifying a namespace for the release. The kubernetes resources are installed in the namespaces you specified in the templates/values, but the _helm release_ is in `default`.

To verify this, check out `kubectl -n default get secrets` and see the release secret that is stored there.

**Comment by fe-dagostino** [comment]
Dear Joe,
         thanks so much for your answer! however, this not explain the inconsistency, may be I didn't explain well enough, so let's try again and hopeful this time you will get the point.

chart name  my-chart

file: namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    istio-injection: enabled

values.yaml
...
namespace: my-ns
....

then execute the following:

helm install my-chart -n my-ns --generate-name
Error: INSTALLATION FAILED: create: failed to create: namespaces "my-ns" not found

----------------------
Well we have an error since "my-ns" will be create only when  "namespace.yaml" will be processed, this means that no make sense to have the "namespace.yaml" inside the chart.

the workaround

kubectl create namespace my-ns
kubectl label namespace my-ns istio-injection=enabled

NOW that we have the namespace and we can try again the command, but

helm install my-chart -n my-ns --generate-name
Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: Namespace "my-ns" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm";  .....

OPS, we have a new error, then let's try to REMOVE "namespace.yaml" from the chart and then execute again the command

helm install my-chart -n my-ns --generate-name

This time it works.

CONCLUSION:
- if you use to create a namespace in your chart in order to install all under such namespace, you cannot have the chart itself in this namespace since it is not jet created and then you should have the chart installed in any other namespace already existing
- if you create the namespace before to install the chart, then you have to remove any "kind: Namespace" from your chart or this will generate an error. So, which is the sense to have "template" if we have to partially manage stuff with kubectl?

SUGGESTION:
Since namespaces have the highest priority, could be nice to check all namespace before to exit with an error, so coming back to the condition where we have "namespace.yaml" and we execute the command

helm install my-chart -n my-ns --generate-name

Before to exit with error, could be nice to search if the chart the creation for the same namespace provided as parameter for the installation and if yes, then continue, if not then in this case return an error.

----
I hope now is much more clear, anyway up to you to reopen or to keep closed the issue.

**Comment by dgisser** [comment]
@fe-dagostino just faced the exact same issue with istio, thanks for explaining your workaround!
