### ISSUE TITLE
Proposal for a new Cryptographic function: randBytes

### ISSUE THREAD

**Issue by giuliocalzolari** [helm/helm#11517]
a function `randBytes` can improve the helm usage and avoid workaround. In a Cryptographic context is very common to have bytes as input 

e.g.
```
randBytes 24
```

**Comment by joejulian** [comment]
Happy to have a contribution to address this. Probably should start with a [HIP](https://github.com/helm/community/blob/main/hips/hip-0001.md) also take a look at the [contributing](https://github.com/helm/helm/blob/main/CONTRIBUTING.md) doc.

**Comment by joejulian** [comment]
On second though, this wouldn't go in helm. Helm uses the [sprig library](https://github.com/Masterminds/sprig/issues) for most functions and this would fit best within that library.

I'm going to close this, here, as it's out of scope for the helm project.
