### ISSUE TITLE
Question about helm upgrade.

### ISSUE THREAD

**Issue by liang1000** [helm/helm#11516]
##

Output of `helm version`: v3.9.3

Output of `kubectl version`: v1.20.5

Cloud Provider/Platform (AKS, GKE, Minikube etc.): EKS

first, I deployed with command: kubectl apply -f ....

then I replace the command, using helm upgrade --install

but I get the error: 
Error: rendered manifests contain a resource that already exists. Unable to continue with install: Deployment "x" in namespace "xxx" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "x"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "xxx"

how can i fix the problem...

**Comment by joejulian** [comment]
As it says, you have resources defined in the chart manifest that already exist and are not owned by helm.

Don't deploy with kubectl.
The way to recover from this is to `kubectl delete -f ...` then `helm upgrade --install ...`
