### ISSUE TITLE
Question regarding configuration drift while dealing with failed releases.

### ISSUE THREAD

**Issue by sigurdblueface** [helm/helm#11525]
Hello. I have a couple of questions regarding helm release secrets. 
As I found out, secrets hold last applied configuration, but not the actual result of applying configuration.

My case is as follows:
At first, I had a successful `deployed` release, then upgraded it with a chart version, which brings `spec.selector` changes (immutable field).
After that upgrade release became `failed`, while selector block in cluster resources stood untouched. 
Helm stored last applied configuration in a release secret.
On the next attempt to deploy helm compares latest secret (the failed one) with manifests to be applied and sees no difference between them. Everything seems up to date.

While actual resources in cluster do differ. 

So my questions are: 
1. Is this expected? Is there a possibility to validate manifests with real state of cluster resources, not with last applied configuration from a secret?
2. Is there a possibility to store somehow the real state of resources? Or just diff between real state and expected.
3. What is a proper way to deal with such breaking changes? As I understood this is a Kubernetes limitation, but complete reinstall of a release doesn't seem to me as a good way to get things working. Maybe there could be a some sort of workaround: like deploying a new manifest with the new selector, and afterwards deleting/scaling to zero an old one?

Many thanks in advance.

Output of `helm version`:
version.BuildInfo{Version:"v3.10.1", GitCommit:"9f88ccb6aee40b9a0535fcc7efea6055e1ef72c9", GitTreeState:"clean", GoVersion:"go1.19.2"}
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:51:05Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2+k3s1", GitCommit:"5a67e8dc473f8945e8e181f6f0b0dbbc387f6fca", GitTreeState:"clean", BuildDate:"2021-06-21T20:52:44Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): bare metal k8s

**Comment by joejulian** [comment]
1. Yes it's expected. Yes you can validate against the state of the cluster using the dry-run flag before that initial upgrade. I should be able to show you the failures. You could also use the `--atomic` flag to roll back to the last known good release. Lastly, when you had an error without using atomic, you would then roll back `helm rollback` to go back to the last known good release allowing the next upgrade to work from the expected state.
2. No. The release resource is already pushing the limits of the storage, frequently. Use the rollback feature and/or back up with velero.
3. As mentioned, rolling back is the solution to your specific issue. To the greater question about adding complex logic to helm to handle doing things that kubernetes specifically prevents you from doing: that is not within the scope of this project. Helm is a templating tool, nothing more. That said, helm does allow you to pass the template output into another program for post-processing using the `--post-renderer` flag. Perhaps you could write an engine to do those more complex upgrades and plug it in there.
