### ISSUE TITLE
How does the mustRegexMatch returns an error?

### ISSUE THREAD

**Issue by wanglongzhong** [helm/helm#11523]
I am trying to using the helm function  mustRegexMatch to validate a timeout values from value.yaml.
it seems I can't get any errors.
 but from the https://helm.sh/docs/chart_template_guide/function_list/#regexmatch-mustregexmatch  documentation  "regexMatch panics if there is a problem and mustRegexMatch returns an error to the template engine if there is a problem."

my yaml file as below
{{- $connectionIdleTimeout := .Values.timeouts }}
{{- $asdas := $connectionIdleTimeout | mustRegexMatch `^(([1-9])|(1[0-9])|(2[0-4]))h$`}}
    timeouts:
      connection-idle-timeout: {{ $connectionIdleTimeout | quote }}
      asdcs: {{ $asdas | quote  }}

command 1 : $  helm template . --set timeouts="24h" --show-only  templates/mustRegexMatch.yaml

Output:
timeouts:
      connection-idle-timeout: "24h"
      asdcs: "true"

command 2: $  helm template . --set timeouts="26h" --show-only  templates/mustRegexMatch.yaml

Output:
timeouts:
      connection-idle-timeout: "26h"
      asdcs: "false"

I not get any errors from mustRegexMatch. 
is there anyone known this?
is there anyone have a good solutions for validate parameters values on value.yaml

Output of `helm version`:
version.BuildInfo{Version:"v3.4.1", GitTreeState:"clean", GoVersion:"go1.14.11"}
Output of `kubectl version`:
N/A
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
N/A

**Comment by wanglongzhong** [comment]
1

**Comment by joejulian** [comment]
The wording on that is pretty confusing. This comes from the sprig library: https://github.com/Masterminds/sprig/blob/3ac42c7bc5e4be6aa534e036fb19dde4a996da2e/regex.go#L12
This is just a wrapper for https://pkg.go.dev/regexp#MatchString the only difference being that regexMatch throws away the error and mustRegexMatch doesn't.

If you write and invalid regex mustRegexMatch with throw an error:
```
Error: template: testchart/templates/deployment.yaml:2:23: executing "testchart/templates/deployment.yaml" at <mustRegexMatch "^(qwert$">: error calling mustRegexMatch: error parsing regexp: missing closing ): `^(qwert$`
```
where regexMatch will not error and will just fail to match anything, always returning `false`.
