### ISSUE TITLE
Ability to specify a different values.yaml file from inside the chart

### ISSUE THREAD

**Issue by salarai** [helm/helm#11532]
Idea: When packaging helm charts, I want to be able to have multiple values.yaml file depending on the environment I want. This file can be addresses through a command line parameter (maybe?) and if not specified, the default values.yaml file is used.

What needs to change:

- multiple values file in the chart
- helm command line to be able to specify not only default, but another file inside the chart.

**Comment by yxxhero** [comment]
@salarai you can specify a different by -f flag.
```
-f, --values strings                             specify values in a YAML file or a URL (can specify multiple)
```

**Comment by joejulian** [comment]
closing as duplicate of #4782
