### ISSUE TITLE
Question regarding plugin install and locking plugin version for helm charts

### ISSUE THREAD

**Issue by benydc** [helm/helm#11530]
1. Does helm support plugin version locking per chart?

2. For example, we have a helm chart repo where we use a couple of plugins like helm-docs and helm-secrets, when we share the repo with someone new and they have a different plugin version, there will be issues due to big version differences. 

3. If this is not a feature already, I'm happy to contribute to helm source code and maybe others will find this helpful?

**Comment by joejulian** [comment]
I don't see anything in https://github.com/helm/helm/blob/704bf4fa867a8e8bac8e42ae323889f880be5281/cmd/helm/load_plugins.go

How would that work?

**Comment by phil9909** [comment]
I could think of two approaches:

- Extend `Chart.yaml` with a `plugins` section:
  ```yaml
  apiVersion: v2
  name: example
  type: application
  version: 0.1.0
  
  plugins:
  - name: helm-docs
    version: ^1.2.0
  - name: helm-secrets
    version: ^2.1.0
  ```
  Rendering would fail, if the plugin:
  - is not installed
  - is installed, but the version does not match the given semver range (could be an optional field)
- Extend the [`.Capabilities` builtin object](https://helm.sh/docs/chart_template_guide/builtin_objects/#helm) to include a list of plugins (e.g. `.Capabilities.Plugins`). In the template one could call [`fail`](https://helm.sh/docs/chart_template_guide/function_list/#fail), if a required plugin is not in the list or the version does not match the expectations.

While the first approach is for the common cases easier, it is also less flexible. E.g. Maybe a (library) Chart doesn't want to require a certain version of a plugin, but behave differently based on the major version of a plugin. Or only offer certain functionality, if plugin x is installed. I guess this is only possible with the second approach. Maybe we even want both (like we have for the Kubernetes version: [`kubeVersion` in `Chart.yaml`](https://helm.sh/docs/topics/charts/#the-kubeversion-field) and `.Capabilities.KubeVersion` builtin object). Maybe you can come up with something completely different.

One general problem I see with this: There is no central plugin registry, so there might be naming conflicts.

Anyway, I guess this would require a [HIP](https://github.com/helm/community/blob/main/hips/README.md) first to cleanly design this feature.

**Comment by joejulian** [comment]
I agree with the bot. Since being proposed, this seems to have lost traction. I'm going to go ahead and close it. :(
