### ISSUE TITLE
Handle EKS token refresh when using this as a library

### ISSUE THREAD

**Issue by cartucciam** [helm/helm#11538]
Hi there, how do you handle token refresh for deployments taking more than 15 minutes? 

All I can think of is using the ExecProvider in rest.Config to invoke the aws cli, is there a way to do that with the aws sdk instead? 

[A couple of years ago](https://github.com/helm/helm/pull/8855/files) this code used to call the factory the user provides instead that the `c.getKubeClient()` directly which would have allowed to inject a token refresh in between.

```go
// IsReachable tests connectivity to the cluster.
func (c *Client) IsReachable() error {
	client, err := c.getKubeClient()
	if err == genericclioptions.ErrEmptyConfig {
		// re-replace kubernetes ErrEmptyConfig error with a friendy error
		// moar workarounds for Kubernetes API breaking.
		return errors.New("Kubernetes cluster unreachable")
	}
	if err != nil {
		return errors.Wrap(err, "Kubernetes cluster unreachable")
	}
	if _, err := client.ServerVersion(); err != nil {
		return errors.Wrap(err, "Kubernetes cluster unreachable")
	}
	return nil
}
```

Cheers,
Matteo

**Comment by joejulian** [comment]
I had that problem once. I just created a serviceaccount and used it's token for authentication.

**Comment by cartucciam** [comment]
I suspect my use case needs something more flexible that this, during the pod lifespan there are multiple instances of Helm targeting different clusters in other accounts

**Comment by joejulian** [comment]
I wonder if running your credential refresh in another window would work.

Otherwise, if you could run from an instance inside the same aws account, you could use an instance role that wouldn't expire.

**Comment by cartucciam** [comment]
One thing I could do is having a goroutine periodically overriding `rest.Config` which is passed by reference to the Helm configuration but this would simply be bad.

I understand that the mentioned PR change fixed an issue but that very issue could have been fixed without removing from the user the ability to implement `getKubeClient()` in the factory.

This change is biased towards the use case of running this as a CLI tool

**Comment by joejulian** [comment]
I was digging through client-go. It looks like it might try to reload tokens every minute. Did you try updating the kubeconfig in the background?

**Comment by cartucciam** [comment]
> I was digging through client-go. It looks like it might try to reload tokens every minute. Did you try updating the kubeconfig in the background?

Thanks, I'll try

**Comment by joejulian** [comment]
No feedback so I'm hoping this means you were successful.
