### ISSUE TITLE
How do I render library charts to view the output of my functions during development?

### ISSUE THREAD

**Issue by red8888** [helm/helm#11544]
Somewhat related to this question: https://github.com/helm/helm/issues/8895

I know library charts are not installable, but I would really like a way to see the output of their functions without having to add it as a dependency to another chart.

As I am developing a library chart I'm writing functions with logic based on set params. How can I run a values file against my library chart to view the output of my functions?

I can _lint_ a library chart against a values file, but how do I execute my functions? Is the only way to have another chart use it as a dependency? I was hoping for a way to just get a dump of the output of all my functions.

I might wind up just setting the chart to application and including a config map to dump values- which is kind of dumb. I could have a condition that renders a config map if set param "testOutputs" == "true" and use that to view my function values while I'm developing, but then its like whats the point of marking a chart as a library if it makes it a pita to develop?

**Comment by red8888** [comment]
Apart from limiting users from installing the chart what does making a chart a library chart do for you?

I get that enforcing correct usage is good, but it'd be great if the tooling supported library charts better. I would expect lint or template commands to have special behavior for the library chart type to support dev workflows. Otherwise it's harder for me to use than regular application charts which can also be used just like library charts. Not asking for an advanced unit testing framework or anything just an easy way to run my functions while I'm working on them.

This is what I have been doing which works reasonably well, but its hacky:
```
{{/*
Hacky way to view outputs of this charts functions during development.
Every function in this chart is added to this config maps values.

A folder of test values files with different inputs is looped over running helm 
template against each one dumping the rendered config map to the console

Provides an easy way to see the output of these functions for different inputs
*/}}

{{- if .Values.testOutputs -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: testOutputs
data:
    my-library-chart.funcOne: {{ include "my-library-chart.funcOne" . }}
    my-library-chart.funcTwo: {{ include "my-library-chart.funcTwo" . }}
    my-library-chart.funcThree: {{ include "my-library-chart.funcThree" . }}
{{- end -}}
```

**Comment by bjw-s** [comment]
> I wonder if @bjw-s, who has managed the hugely popular k8s-at-home library until recently, would have any suggestions.

Thanks for the ping! I pretty much do the same thing as @red8888: I either (temporarily) add in a hacky `{{ <whatever template I want to test> }}` or `{{ .Values }}`, or I leverage my local instance of [my app-template chart](https://github.com/bjw-s/helm-charts/tree/main/charts/other/app-template) to see what the output is with a real-life set of values.

Additionally I have a set of unit tests (based on the [helm3-unittest](https://github.com/vbehar/helm3-unittest) framework) that I can run: https://github.com/bjw-s/helm-charts/tree/main/charts/other/app-template/tests

**Comment by red8888** [comment]
@bjw-s thanks for responding! Not a huge deal just curious if there was some new fangled native way to do this. I played with unit-test a while back maybe thats what I want.

When you say "temporarily" do you mean you switch the chart type to application, add a template, then remove the template and switch back to library? Or do you just use the application chart type?

**Comment by joejulian** [comment]
@red8888 I hope that was helpful. I think you got at least some ideas on how to move forward and it's been a long while with no further activity so I'm going to go ahead and close this.

**Comment by Tchoupinax** [comment]
Hey,
I'm wondering if someone knows why `helm template` does not work with library. Naively I would have thought that `helm install` uses underneath `helm template`. Isn't the case?
