### ISSUE TITLE
Option to send Deprecation Warnings and/or Errors to Sentry, "plugin" or Script

### ISSUE THREAD

**Issue by salzig** [helm/helm#11558]
Hej,
we have quite some deployments on a not so insignificant number of clusters. So it's "hard"/time consuming to always keep an eye on the output generated by helm.

Would it be a good idea to integrate some form of callback in Helm to signal/notify senty/slack/etc about deprecation warnings, or also errors, in a standardized way?

**Comment by joejulian** [comment]
I don't think it's a bad idea at all.

Today, `helm lint` will show the warnings. You can scrape those.

To improve this, `lint` would need machine-readable output and would need the ability to [set the kubernetes version](https://github.com/helm/helm/issues/10664) that you're linting against.

**Comment by salzig** [comment]
Maybe it's a good think to improve lint too, but to be honest i would prefer "the real deal" and signal while(/after) applying. 

Linting is already done in our pipelines to check if those charts "work", and I'm fine with change requests having failing lint jobs cause someone missed something - and i prefer not to see those errors in sentry or else where. But when those lint pipelines are green, those changes get merged and are used on different clusters and will not be linted again (they can't change magically, so why should we?). In the daily life cycle those charts are then applied to a cluster where we didn't "know" an update had hapend (yep, out of our reach), and that's where it would help to capture those problems and give us a heads up.

**Comment by joejulian** [comment]
I wonder if you could implement such a thing using a plugin or post-renderer

**Comment by joejulian** [comment]
Looks like this proposal has gone inactive. Closing.
