### ISSUE TITLE
(Question) Where do the helm downloads tgz files during helm install execution

### ISSUE THREAD

**Issue by srinivasev** [helm/helm#11557]
**Question** - Where do the helm install command stores the charts which are intended to install ?. Or helm install works without downloading the chart into local machine ?.

Or helm install internally invokes helm pull command for downloading the chart into local machine and use this for installing ?.

Output of `helm version`: `version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
`

Output of `kubectl version`: `[root@atvts3607 srini]# kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"49499222b0eb0349359881bea01d8d5bd78bf444", GitTreeState:"clean", BuildDate:"2021-12-14T12:41:40Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
`

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  Plain Kubernetes

**Comment by phil9909** [comment]
The charts are stored in the `repository` directory within the cache path.
The cache path can be configured using the `HELM_CACHE_HOME` environment variable. If it is not explicitly configured it uses some Operating System specific default:

Operating System | Cache Path
-- | -- |
Linux | $HOME/.cache/helm
macOS | $HOME/Library/Caches/helm
Windows | %TEMP%\helm

See https://helm.sh/docs/faq/uninstalling/#i-want-to-delete-my-local-helm-where-are-all-its-files

**Comment by joejulian** [comment]
question was answered. Closing.
