### ISSUE TITLE
How to prevent PVCs from being deleted when uninstalling a Helm release

### ISSUE THREAD

**Issue by antoniodiazroman** [helm/helm#11559]
Greetings,

I'm dealing with bringing a deployed Helm release (**Hazelcast**) to **Argo CD**, and in order to do that, I must first **uninstall** the release with Helm and reinstall it using Argo CD.

The thing is that when I uninstall the release, **the Management Center PVC is also removed**, and that's something I do not desire because this PVC contains data that I need to keep. My intention is to keep this PVC and redeploy Hazelcast with Argo CD configuring the `values.yaml` to use the existing PVC instead of generating a new one.

Things that I have already tried:

- Using the Helm annotation `helm.sh/resource-policy`, it works well when the release has been deployed with this annotation, but it is useless if the release has not. Please note that our Hazelcast releases have been all deployed without this annotation.
- Remove Helm labels and annotations from the PVC metadata. I supposed that Helm uses this kind of metadata for taking ownership of the Kubernetes resources it manages, but removing this metadata does not do the trick, and the PVC is also removed. With this in mind, I cannot guess the way Helm takes ownership of the resources if not using this metadata.

Additional info that could be of interest:

- My Helm version is 3.10.2
- My Kubectl version is 1.25.2
- My Kubernetes platform is an on-premise Kubeadm cluster with version 1.20.15
- The Management Center application version is 3.12.6 and is based on a Statefulset, however the PVC is not generated using a `volumeClaimTemplates` section, but using a traditional `volumes` section

Thank you very much beforehand.

**Comment by joejulian** [comment]
What about adding the `helm.sh/resource-policy` to the pvc, running an update manually, then uninstalling?
You could probably just delete the release secrets and let helm reclaim ownership of the resources.
You could add a finalizer to the PVC to prevent it being deleted.

That's what I've got off the top of my head. LMK if any of that's helpful.

**Comment by joejulian** [comment]
Looks like the bot is right. Closing.
