### ISSUE TITLE
Certificate expired in CircleCI tests

### ISSUE THREAD

**Issue by drivera-armedia** [helm/helm#11568]
The following error is shown while [this PR](https://github.com/helm/helm/pull/11071) is being [tested](https://app.circleci.com/pipelines/github/helm/helm/4571/workflows/814befa8-ce95-49de-b42a-e22a67481b1b/jobs/16143):

```
2022/11/24 16:01:39 http: TLS handshake error from 127.0.0.1:43576: read tcp 127.0.0.1:33057->127.0.0.1:43576: use of closed network connection
--- FAIL: TestDownloadTo_TLS (0.01s)
    chart_downloader_test.go:253: Get "https://127.0.0.1:33057/signtest-0.1.0.tgz": x509: certificate has expired or is not yet valid: current time 2022-11-24T16:01:39Z is after 2022-08-21T22:36:36Z
FAIL
```
This seems to be related to the test environment's certificate having expired in August and not being updated.

**Comment by yxxhero** [comment]
@drivera-armedia try to rebase your code.
