### ISSUE TITLE
Charts should be able to read the permissions associated with the installation user who is invoking Helm

### ISSUE THREAD

**Issue by robmoore-i** [helm/helm#11577]
Feature request: As a Chart author, I would like to be able to access, through an object like `.InstallationUser` or `.Permissions`, the RBAC configuration associated with the installation user i.e. the k8s service account user who has invoked e.g. `helm install`.

In my particular case, this is because I'd quite like to save that info to a ConfigMap for use in debugging a failed installation. This is useful because in some cases, users run the installation with a service account that doesn't have permission to create certain types of objects. Debugging this can be non-trivial, so a feature like this would be great.

My perspective is from a software vendor who distributes their product for on-prem installation, via a Helm chart, and supports customers in successfully installing that product in their infrastructure.

From reading the docs, I don't getting this information in the chart is possible today. At least, there is nothing written about it. There is the [rbac doc](https://helm.sh/docs/topics/rbac/), but this doesn't contain anything on the topic of inspecting or debugging permissions issues.

Let me know what you think of this,
Thanks,
Rob

**Comment by joejulian** [comment]
You could probably use the lookup function in a similar way to how https://github.com/rajatjindal/kubectl-whoami/blob/master/pkg/k8s/tokenreview.go does it.

**Comment by joejulian** [comment]
Since a suggestion was given and there was no further response, I'm going to assume the suggestion solved the problem and close this.
