### ISSUE TITLE
Disable warning when Kube Config is group/world-readable

### ISSUE THREAD

**Issue by theAkito** [helm/helm#11592]
Pretty much https://github.com/helm/helm/issues/11083 and https://github.com/helm/helm/issues/9115.

My configuration file is a symlink, which does not have permissions, but according to `ls` & whatever Helm uses internally, it looks like it has `777` permissions, which is ultimately not true, though.

Changing permissions of a symlink only works on BSD and whatever operating systems use the same tools. Linux is not part of that group.

I would like to be able to disable this permanent warning, because it is wrong. The file itself is safe. It's just the symbolic link, which appears as if it were accessible by everyone.

**Comment by et304383** [comment]
Wow.  Just came here from Google.  This warning message should be based on the real file path, not the symlink.  It should be easy to check if it's a symlink first.

At the very least, provide a way to disable this annoying warning.

**Comment by theAkito** [comment]
> At the very least, provide a way to disable this annoying warning.

There was some talk about "our audit team recommended to never hide this warning" or something, but in this case, it is utterly unnecessary, because it is simply *wrong*. So, this warning should just be removed, if a symbolic link leads to a properly permissioned file.

**Comment by xodmqjw** [comment]
Maybe I'm missing some point but in [this code](https://github.com/helm/helm/blob/3636f6824757ff734cb265b8770efe48c1fb3737/cmd/helm/root_unix.go#L45) permissions already are checking using `stat` syscall. Thus there should be no warnings because this syscall gets status of a file, not a symlink (according to the [docs](https://man7.org/linux/man-pages/man2/lstat.2.html) )

Here is a test to check:
```go
func TestCheckSymlinkPerms(t *testing.T) {
	tdir := t.TempDir()
	tfile := filepath.Join(tdir, "testconfig")
	_, err := os.OpenFile(tfile, os.O_CREATE|os.O_APPEND|os.O_RDWR, 0400)
	if err != nil {
		t.Errorf("Failed to create temp file: %s", err)
	}

	linkfile := filepath.Join(tdir, "testconfig.symlink")
	_ = os.Symlink(tfile, linkfile)

	tconfig := settings.KubeConfig
	settings.KubeConfig = linkfile
	defer func() { settings.KubeConfig = tconfig }()

	text, err := checkPermsStderr()
	if err != nil {
		t.Fatalf("could not read from stderr: %s", err)
	}
	if text != "" {
		t.Errorf("Expected no warning messages, got %q", text)
	}
}
```

**Comment by mfordjody** [comment]
Is it assigned? I want to solve this problem

**Comment by johanot** [comment]
Why is the warning even there in the first place? It's _not_ insecure to have a world-readable kubeconfig. Having world-readable _secrets_ is insecure, but the kubeconfig format supports detached secrets.

**Comment by Shawn1874** [comment]
I agree with @RafalSkolasinski.  The K3S documentation at https://docs.k3s.io/installation/configuration specifically instructs users to setup 644 permissions on the k3s config file to support non-root users making kubectl commands and kubectl doesn't warn us about this.  In general this warning is annoying and there should be a way for us to disable it.

**Comment by michael-dez** [comment]
@theAkito Does the kubeconfig that the symlink is pointing to have 777 permissions?

**Comment by theAkito** [comment]
> @theAkito Does the kubeconfig that the symlink is pointing to have 777 permissions?

https://github.com/helm/helm/issues/11592#issuecomment-1335561224

If it has proper permissions, it cannot be set to 777.

**Comment by rnemeth90** [comment]
Is anyone working on this? If not, please assign to me and I'll submit a PR.

**Comment by RafalSkolasinski** [comment]
I don't believe this should get closed

**Comment by mohag** [comment]
My ~/.kube is a symlink:
```
$ ls -lah ~/.kube
lrwxrwxrwx 1 username username 26 Jan 17  2019 /home/username/.kube -> /mnt/c/Users/username/.kube
```

There is no "world" permissions on the file, yet helm is still complaining (there is group permissions though, but it complains about world-permissions as well) (It looks like 777 from within WSL, but that is just part of the story and nothing else complains about it..)
![image](https://github.com/user-attachments/assets/bc9d6932-5973-4493-8126-4cb40160f230)
