### ISSUE TITLE
FR: `--skip-chart-notes` for install/upgrade

### ISSUE THREAD

**Issue by fivaldi** [helm/helm#11598]
Refer to %subject% :-)  
(Or just `--skip-notes`?)
 
TL;DR

```
% helm install ...
NAME: ingress-nginx
LAST DEPLOYED: Sat Dec  3 18:16:12 2022
NAMESPACE: ingress-nginx
STATUS: deployed
REVISION: 4
TEST SUITE: None
NOTES:
The ingress-nginx controller has been installed.
It may take a few minutes for the LoadBalancer IP to be available.
You can watch the status by running 'kubectl --namespace ingress-nginx get services -o wide -w ingress-nginx-controller'
...
%
```

VERSUS (feature request)

```
% helm install --skip-chart-notes ...
NAME: ingress-nginx
LAST DEPLOYED: Sat Dec  3 18:16:12 2022
NAMESPACE: ingress-nginx
STATUS: deployed
REVISION: 4
TEST SUITE: None
%
```

**Comment by yxxhero** [comment]
@fivaldi PRs is welcome.

**Comment by miles-w-3** [comment]
I’m working on this now as a first issue, should notes still be included as a part of the chart so they can be retrieved later, so this flag only skips printing notes to the console, or should they not be included in the release at all? I think the former option makes more sense, but want to make sure what the request is

**Comment by joejulian** [comment]
> I’m working on this now as a first issue, should notes still be included as a part of the chart so they can be retrieved later, so this flag only skips printing notes to the console, or should they not be included in the release at all? I think the former option makes more sense, but want to make sure what the request is

@miles-w-3 skip printing to the console makes sense to me, fwiw.

**Comment by miles-w-3** [comment]
Great thanks, I think the pr should be ready then
