### ISSUE TITLE
K8s service account is deleted when converting it to a hook resource

### ISSUE THREAD

**Issue by mattmelgard** [helm/helm#11608]
Output of `helm version`: `v3.9.0+g7ceeda6`
Output of `kubectl version`: `v1.19.7`
Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE (API Version: `v1.23.8-gke.1900`)

We have a chart for deploying our internal services and the values schema offers the option to define helm hooks as part of the release of the service. Since we use GKE's Workload Identity, we also have a k8s service account defined for the each service that is named after the service itself.

Because the GCP identity is bound to the name of the k8s service account and in order for hook jobs to assume the same GCP identity as the service (as they often do in our case) so we don't have to define a separate workload identity binding for the hook, we conditionally configure the k8s service account as a hook resource if hook jobs are enabled on the chart so that it can be deployed prior to any hooks or services and be available to any hook jobs that are executing prior to install. We also define it without a deletion policy so that it is not cleaned up after hooks have run and can then be available for the running service workloads themselves.

What I'm seeing, however, is that when a service account that was previously not a hook is then converted to a hook (by conditionally applying hook annotations in the case of our chart), the service account is instead deleted and the release fails.

For more context, here's how the service account template is defined:

```
{{- if .Values.serviceAccount.create -}}
{{- $k8sServiceAccountName := include "syndio-service.serviceAccountName" $ -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $k8sServiceAccountName }}
  labels:
    {{- include "syndio-service.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.hooks }}
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-10"
  {{- end }}
  {{- with .Values.serviceAccount.workloadIdentity }}
  {{- if .enabled }}
    iam.gke.io/gcp-service-account: "{{ default .gcpServiceAccountName (printf "%s-sa" $k8sServiceAccountName) }}@{{ required "gcpProjectID is required if Workload Identity is enabled" .gcpProjectID }}.iam.gserviceaccount.com"
  {{- end }}
  {{- end }}
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
```

Running a `helm diff` on the release after attempting to deploy it first with a normal service account, and then again after hooks are enabled, I can see that the service account is deleted but is never restored as a helm hook resource prior to install.

```
- # Source: syndio-service/templates/serviceaccount.yaml
- apiVersion: v1
- kind: ServiceAccount
- metadata:
-   name: apiv3
-   labels:
-     helm.sh/chart: syndio-service-1.12.0
-     app.kubernetes.io/name: apiv3
-     app.kubernetes.io/managed-by: Helm
-     app: apiv3
-     cf_build_id: 638e82b60e69d7daa5ec5c55
-   annotations:
-     iam.gke.io/gcp-service-account: "apiv3-sa@realms-b5c8de3d.iam.gserviceaccount.com"
- 
```

Is this expected behavior? I personally would expect the outcome to be that the k8s service account is simply left unchanged since it is now being installed with `pre-install,pre-upgrade` triggers and no deletion policy. If this is expected, what is the best way to approach or workaround this problem?

**Comment by joejulian** [comment]
It's expected because the prior release had the ServiceAccount in the manifests, and the new release does not. Hooks are not managed, so they're not accounted for when reconciling the release.

What should happen is you'll get an error stating that the ServiceAccount already exists when applying the pre-upgrade hook and the release will fail.

If you made it a post-upgrade, the SA would be deleted but then the hook would create it again. Maybe that will get you what you need?

**Comment by mrballcb** [comment]
I am facing the same behavior as OP, with helm 3.4.2.  Adding hooks to a resource that didn't have hooks before results in a resource deletion after the hook, but then it doesn't get recreated.

We wrote some helm charts that deploy 1) configmap 2) secret 3) job 4) app, and have deployed several apps with this.  Only the job (goose migration) has helm hooks, priority +2.

Imagine that we have updated the configmap by either modifying an existing value or added a new key/value pair.  When we deploy the helm chart, the job runs first as expected, but it runs before the configmap (or secret) has been updated, so it's using old values from the prior deployment.

According to the helm hook documentation, setting the hooks with a smaller priority in the configmap/secret are supposed to cause them to be updated first.  So we add the hooks to the configmap and secret with priority -2  and deploy.  Remember, the existing configmap that it's replacing does not have any hook annotations.  When deployed (`helm upgrade -i`) the configmap/secret are updated first (good), the job runs (good), the configmap/secret get deleted and **not replaced** (bad), the app pod tries to start but it can't mount the configmap/secret so is stuck in state CreateContainerConfigError and the helm deploy eventually "times out waiting for the condition".

I saw another suggestion to add `"helm.sh/resource-policy": keep` which would block the configmap/secret from being deleted between the job run and new pod starting, but that also results in leaving the configmap/secret behind when we do a helm uninstall, which then blocks reinstalling unless we manually remove that configmap/secret using kubectl.

I have not yet found a way to add a helm hook to a resource that didn't previously have them, and not lose the resource during a `helm upgrade` command.

**NOTE:**  Installing a helm chart from scratch with all hook annotations present on resources works just fine.  Upgrading the deployment when the resources already have hook annotations works fine.  It's just updating a resource to have hooks causes this failure.

**Comment by joejulian** [comment]
The resources that were installed in your release are stored in the release secret. When you remove a resource from the release (and changing it to a hook counts as removing it), the resource is deleted when upgrading. The only way to get it back would be to create it again. If you want it to be a hook, you'll need to do it in post-upgrade. The only other possibility that comes to mind is deleting the release secret, orphaning the resources that were installed by helm, and re-installing. Helm _should_ be able to adopt the resources - though you might get hook-stage errors about resources that already exist. I'm not sure if hooks can adopt resources.

**Comment by mattmelgard** [comment]
@joejulian thanks for the replies so far. I guess I'm wondering why a `post-upgrade` hook would re-create the resource but the `pre-upgrade` hook will not? I guess I would think the order of operations would be something like:

1. Existing (non-hook) `serviceaccount` is deleted on upgrade since it's now a hook resource
2. Hook based `serviceaccount` is created immediately afterward
3. Hook jobs are executed using the hook based `serviceaccount`
4. New pods are rolled out for the upgrade using the hook created `serviceaccount` resource since it uses a `before-hook-creation` deletion policy by default and should not be deleted after hooks run

The way it plays out in actuality though seems to be:

1. Existing `serviceaccount` is deleted on upgrade
2. Hook based `serviceaccount` is created
3. Hook jobs execute
4. Hook based `serviceaccount` is deleted for some reason(?)
5. Pods roll out but fail to start because of the missing `serviceaccount`

**Comment by joejulian** [comment]
Install a chart that contains a resource, any resource. For your example it's a ServiceAccount, but the actual kind is irrelevant.

1. All the resources that were installed are saved in the release manifest. You can view this manifest by running `helm get manifest` against the release. This will show you all the resources that helm considers itself the owner of for that release.
2. Install an upgrade that adds the pre-install hook label.
3. The new template will create a pre-install hook, but remove that resource from the manifest body.
4. The hooks are applied, and the hook configuration uses its pre-delete to delete then recreate the resource.
5. The main helm body is processed. The release manifest contains the resource, but the new manifest does not. This resource is deleted.

**Comment by mattmelgard** [comment]
Hmm. Okay, well if that's the case I'll have to find some other way to define a serviceaccount for hooks. Thanks for your help!

**Comment by yinzara** [comment]
Is there any way to convert service-accounts to hook based service accounts without uninstalling them?
