### ISSUE TITLE
OCI Pre-release 

### ISSUE THREAD

**Issue by TheQueenIsDead** [helm/helm#11605]
Hi there,

I see that OCI version range support has been added (https://github.com/helm/helm/pull/10527) allowing me to do wonderful things like this:
```bash
$ helm pull oci://<registry>.azurecr.io/helm/test
Pulled: <registry>.azurecr.io/helm/test:1.2.4
Digest: sha256:530f873c501911cfc9ab6cc4e879ddedefcdc6472f0cebb5cf1323357c523858

$ helm pull oci://<registry>.azurecr.io/helm/test --version "<=1.0.*"
Pulled: <registry>.azurecr.io/helm/test:1.0.0
Digest: sha256:cb078c2aa0563f100187f9c2d0deb7ae75f566e236ca7041d707d97f0b7cf1cf
```

However, I do not see the ability to pull a pre-release version without explicitly defining the full tag?

I have some chart version published like so:
![image](https://user-images.githubusercontent.com/30706552/205797433-fccf0ef7-4ac3-40cc-8cdc-cc36ef2ce476.png)

And I have attempted to pull some artifacts defined by their "-dev" or "-rc*" versions, but to no avail unless I explicitly pull the fully specified tag. Is there a way to specify that pre-release versions can be pulled? I believe there are package managers that have special syntax to allow this, is there an option in helm?

I am essentially trying to work around the inability to specify `latest` on a chart via OCI.

Any help appreciated, if it can not be done within the Helm I will look at getting a list of tags via the Azure CLI instead 👍 

Helm Version
```
version.BuildInfo{Version:"v3.10.0", GitCommit:"ce66412a723e4d89555dc67217607c6579ffcb21", GitTreeState:"clean", GoVersion:"go1.18.6"}
```

**Comment by sabre1041** [comment]
Use the `--devel` flag which will allow you to leverage prerelease versions

**Comment by TheQueenIsDead** [comment]
Superb, apologies for missing that, I see it is noted in the helm pull output :+1: 

```console
$ helm pull --help

Retrieve a package from a package repository, and download it locally.
...
Flags:
...
  --devel                      use development versions, too. Equivalent to version '>0.0.0-0'. If --version is set, this is ignored.
  -h, --help                       help for pull
...
```

Thank you for the quick assistance on an oversight on my part :heart:
