### ISSUE TITLE
Helm upgrade doesn't update configmaps of dependent charts

### ISSUE THREAD

**Issue by pvallone** [helm/helm#11613]
`helm upgrade` doesn't seem to be applying updates to the configmaps of dependent charts. If I deploy chart A by itself and update something in its `values.yaml` file that maps to something in a configmap, the update gets applied to the configmap. If chart A is a dependency of chart B, and I try to update that same configuration from chart B's `values.yaml` file, the configmap change does not get applied when I `helm upgrade` chart B.

This might be a duplicate of #5915, but that issue is closed. Based on some of the comments in that issue, such as [this one](https://github.com/helm/helm/issues/5915#issuecomment-1247551649), it seems like others are also noticing that configmaps aren't getting updated.

Output of `helm version`:
`version.BuildInfo{Version:"v3.10.1", GitCommit:"9f88ccb6aee40b9a0535fcc7efea6055e1ef72c9", GitTreeState:"clean", GoVersion:"go1.18.7"}`

Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-fb459a0", GitCommit:"b07006b2e59857b13fe5057a956e86225f0e82b7", GitTreeState:"clean", BuildDate:"2022-10-24T20:32:54Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
EKS

**Comment by yxxhero** [comment]
@pvallone would you post a example so that we can debug this issue?

**Comment by joejulian** [comment]
Are you editing the values.yaml files in the charts themselves, then just doing a `helm upgrade`? I'm pretty sure that won't work as with no specified changes, the upgrade with use the values in the release, not in the updated chart (I could be wrong).

Instead of editing the chart, if you create your own yaml file with the values you're changing and apply that file while upgrading with the `--values` flag, does it work then?

**Comment by pvallone** [comment]
I'm going to close this until I'm able to get back to it, as I feel bad leaving the issue open. I appreciate the input so far. I'm seeing the issue with an internal/proprietary chart, so it's not easy for me to share an example.
