### ISSUE TITLE
Linting error on null in dependencies is misleading

### ISSUE THREAD

**Issue by dastrobu** [helm/helm#11627]
When doing `helm lint` on a chart with the following dependencies: 

```
dependencies:
  - name: foo
    version: 1.2.3
  - null
```

it fails with 
```
==> Linting .
[ERROR] templates/: validation: dependency cannot be an empty list
```

This is quite misleading, as a chart with an empty list (`dependencies: []`) does not fail linting.

This was caused by #11044 and I would suggest to simply change the error message to a more meaningful one. 

Output of `helm version`: 
```
version.BuildInfo{Version:"v3.10.2", GitCommit:"50f003e5ee8704ec937a756c646870227d7c8b58", GitTreeState:"clean", GoVersion:"go1.19.3"}
```

**Comment by wujunwei** [comment]
You can see this commented by maintainer  https://github.com/helm/helm/pull/11044#discussion_r952537884

**Comment by dastrobu** [comment]
@wujunwei good point. 
@hickeyma can you explain your review comment? Given that an empty list (`[]`( does not fail linting, it seems confusing to me (see https://github.com/helm/helm/issues/11627#issue-1489706440).

**Comment by hickeyma** [comment]
@dastrobu Maybe empty entry? Refer to https://github.com/helm/helm/pull/11044#discussion_r954867393

**Comment by dastrobu** [comment]
@hickeyma sure, empty is fine as well for me. Keep in mind, though, that we cannot distinguish empty and explicit null cases: 

````yaml
dependencies:
  - name: foo
    version: 1.2.3
  # explicit null
  - null
  # empty
  - 
````
The [yaml spec](https://yaml.org/spec/1.2.2/#72-empty-nodes) refers to them as "empty nodes". So if we really care about precise error messages, I would suggest: "dependencies must not contain empty or null nodes" (PR updated accordingly).

**Comment by hickeyma** [comment]
@dastrobu Do you mind pushing the PR for this?

**Comment by dastrobu** [comment]
@hickeyma I am not sure if I understood your comment, there is an open PR #11628, which should fix this issue and addresses the comments I got on the code to the best of my knowledge. 
Can I do anything apart from waiting for a review from the maintainers?
