### ISSUE TITLE
Github private repos returning 404

### ISSUE THREAD

**Issue by alexwhiteoval** [helm/helm#11640]
Output of `helm version`:
```
  Version:"v3.10.2",
  GitCommit:"50f003e5ee8704ec937a756c646870227d7c8b58",
  GitTreeState:"clean",
  GoVersion:"go1.18.8"
```

Output of `kubectl version`:
Client:
```
  Major:"1", 
  Minor:"24", 
  GitVersion:"v1.24.0", 
  GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", 
  GitTreeState:"clean", 
  BuildDate:"2022-05-03T13:46:05Z", 
  GoVersion:"go1.18.1", 
  Compiler:"gc", 
  Platform:"linux/amd64"
```
Server:
```
  Major:"1", 
  Minor:"23+", 
  GitVersion:"v1.23.13-eks-fb459a0", 
  GitCommit:"55bd5d5cb7d32bc35e4e050f536181196fb8c6f7", 
  GitTreeState:"clean", 
  BuildDate:"2022-10-24T20:35:40Z", 
  GoVersion:"go1.17.13", 
  Compiler:"gc", 
  Platform:"linux/amd64"
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
`AWS EKS`

Github is now returning 404s for the previous method of adding private helm charts with
`helm repo add $REPO https://$TOKEN@raw.githubusercontent.com/$ORG/$REPO/master/`

A curl request to the same url + index.yaml also returns a 404. In order to pull the yaml file you need to run the following curl command
`curl -H 'Authorization: token $TOKEN' -H 'Accept: application/vnd.github.v3.raw' -O -L https://api.github.com/$ORG/$REPO/master/index.yaml`

Supplying the username/password variables to the helm command does not work either.

**Comment by joejulian** [comment]
Do you know, has Github documented this change?

**Comment by alexwhiteoval** [comment]
Not that I can find

**Comment by joejulian** [comment]
```
curl https://${GITHUB_USER_TOKEN}@raw.githubusercontent.com/joejulian/${PRIVATE_REPO}/master/README.md
```
worked for me.

**Comment by channyein87** [comment]
I have the same issue. Looks like GitHub made some changes related to permission. It is working after I updated the token permission to `write:packages`.

**Comment by joejulian** [comment]
This looks to me like it's resolved. Closing.
