### ISSUE TITLE
[Bug] On condition, giving an empty value still returns the content of the chart

### ISSUE THREAD

**Issue by CedricGabette** [helm/helm#11641]
Output of `helm version`: 
`version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.18.9"}`

Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v0.21.0-beta.1", GitCommit:"9aacc905facea5a8bbc0871e29014605dffcea0d", GitTreeState:"clean", BuildDate:"2022-02-07T18:06:27Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}`

I have a charts containing a chart.yaml defining the following dependencie:

>dependencies:
&ensp; - name: sub-chart
&ensp; &nbsp; condition: subchart.enabled

I have a values.yaml containing :

>subchart:
&ensp; enabled: false

And a second file values-injected.yaml containing:

>subchart:

When running `helm template . -f values.yaml`  I'm expecting to fail that the command return nothing and it does as expected.

But when running  `helm template . -f values-injected.yaml` I'm expecting the same result but the helm is executed and return the config given in the charts. 

I find it to be a strange behaviour, if you don't give a state, the map should be ignored.

**Comment by joejulian** [comment]
When you set a key to null, it gets deleted. In yaml this is the equivalent to this json:

yaml
```yaml
subchart:
```
json
```json
{
  "subchart": null
}
```

Therefore, with a `values.yaml` file in the chart like:

```
subchart:
  enabled: false
```

### Test 1: enable subchart

__test1.yaml__

```
subchart:
  enabled: true
```

`helm template -f test1.yaml` result:

```
subchart:
  enabled: true
```  

### Test 2: disable subchart

__test2.yaml__

```
subchart:
  enabled: false
```

`helm template -f test2.yaml` result:

```
subchart:
  enabled: false
```

### Test 3: set subchart key to null

__test3.yaml__

```
subchart:
```

`helm template -f test3.yaml` result:

```
```

**Comment by joejulian** [comment]
Since an answer was given and there's been no further activity on this issue, I'm going to go ahead and close it.
