### ISSUE TITLE
How to refer it if the key in values.yaml contains dot  

### ISSUE THREAD

**Issue by pan3793** [helm/helm#11653]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.19.4"}
```
Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Suppose I have a `values.yaml`

```
a:
  b.c: hello, world
```

How can I refer it in templates?

I have tried, but neither `{{ .Values.a.b.c }}` nor `{{ .Values.a."b.c" }}` work.

**Comment by sabre1041** [comment]
You can use `{{ index .Values.a "b.c" }}`

**Comment by pan3793** [comment]
Thanks, it works.
