### ISSUE TITLE
helm trust path for new signing key

### ISSUE THREAD

**Issue by Foxboron** [helm/helm#11652]
Output of `helm version`: N/A

Output of `kubectl version`: N/A

Cloud Provider/Platform (AKS, GKE, Minikube etc.): N/A

Yo,

With the release of `3.10.3` there is a new key doing releases. I can't seem to find any trust path between @mattfarina and @hickeyma and would appreciate if this could be resolved.

If Matt could sign Martins key, or if Matt could publish a signed statement about this key, that would be preferable.

Thanks!

**Comment by joejulian** [comment]
Closing as duplicate of #11596

**Comment by Foxboron** [comment]
@joejulian how is this a duplicate of that issue?

**Comment by hickeyma** [comment]
Re-opening as this is not really a duplicate of #11596 

@Foxboron Are you able to find my key in https://github.com/helm/helm/blob/main/KEYS?

**Comment by hickeyma** [comment]
Refer to #6093 for more details.

**Comment by Foxboron** [comment]
@hickeyma I have no clue how I have missed this file :/ sorry.

I'd like if commits with key additions where properly signed with something that is not Githubs signing keys, preferably by an existing keyholder as well.  Or the file itself signed by one of the older keys in the file. 

Validating additions would require the github pull-request history and I don't think that is necessarily great if we consider VCS compromises.

**Comment by Foxboron** [comment]
> Do you have specific ways that we can improve the process?

Yes,

The addition of a new release key should only be added with a signed commit from an existing release key. This can either be the existing release manager adding the key, or a locally signed merge commit.

The subsequent release should also be done by an existing manager, not the newly added key.

If there is a supply chain attack that compromises the build server + vcs repository, they can do seemingly legitimate releases by adding a new key and it would be indistinguishable from the existing release manager keys. The current model also assumes the github pull-request history is always going to be present to validate any commits that adds new release manager keys. If we *only* have the git checkout there is no chain of trust from an existing release manager to a new release manager.

I haven't found a release where a new release manager cuts the release after being added, but I don't see any such notes in the checklist either.
