### ISSUE TITLE
How can I push chart to an insecure OCI registry with helm v3

### ISSUE THREAD

**Issue by dreamerkr** [helm/helm#11682]
helm 3.10.0 and after version

Upload a chart to a registry.

If the chart has an associated provenance file,
it will also be uploaded.

Usage:
helm push [chart] [remote] [flags]

Flags:
-h, --help help for push

Global Flags:
--burst-limit int client-side default throttling limit (default 100)
--debug enable verbose output
--kube-apiserver string the address and the port for the Kubernetes API server
--kube-as-group stringArray group to impersonate for the operation, this flag can be repeated to specify multiple groups.
--kube-as-user string username to impersonate for the operation
--kube-ca-file string the certificate authority file for the Kubernetes API server connection
--kube-context string name of the kubeconfig context to use
--kube-insecure-skip-tls-verify if true, the Kubernetes API server's certificate will not be checked for validity. This will make your HTTPS connections insecure
--kube-tls-server-name string server name to use for Kubernetes API server certificate validation. If it is not provided, the hostname used to contact the server is used
--kube-token string bearer token used for authentication
--kubeconfig string path to the kubeconfig file
-n, --namespace string namespace scope for this request
--registry-config string path to the registry config file (default "/root/.config/helm/registry/config.json")
--repository-cache string path to the file containing cached repository indexes (default "/root/.cache/helm/repository")
--repository-config string path to the file containing repository names and URLs (default "/root/.config/helm/repositories.yaml")

but not find -insecure-skip-tls-verify

**Comment by dreamerkr** [comment]
**helm push --debug demo-0.1.0.tgz oci://172.16.13.61:5000/mytest**

WARN[0000] reference for unknown type: application/vnd.cncf.helm.config.v1+json
WARN[0000] reference for unknown type: application/vnd.cncf.helm.chart.content.v1.tar+gzip
DEBU[0000] checking and pushing to                       url="https://172.16.13.61:5000/v2/mytest/demo/blobs/sha256:9ebda4cd8288db14d228fc0a911b1eeb7e74d55b01fc3534bfe4d7d46c1ffabb"
DEBU[0000] do request                                    request.header.accept="application/vnd.cncf.helm.chart.content.v1.tar+gzip, */*" request.header.user-agent=Helm/3.10.3 request.method=HEAD url="https://172.16.13.61:5000/v2/mytest/demo/blobs/sha256:9ebda4cd8288db14d228fc0a911b1eeb7e74d55b01fc3534bfe4d7d46c1ffabb"
DEBU[0000] checking and pushing to                       url="https://172.16.13.61:5000/v2/mytest/demo/blobs/sha256:ff1a5b6b030beb6d80ed19ee6573edf7de40803ef73c8502cffb6f2a10ba39d7"
DEBU[0000] do request                                    request.header.accept="application/vnd.cncf.helm.config.v1+json, */*" request.header.user-agent=Helm/3.10.3 request.method=HEAD url="https://172.16.13.61:5000/v2/mytest/demo/blobs/sha256:ff1a5b6b030beb6d80ed19ee6573edf7de40803ef73c8502cffb6f2a10ba39d7"
Error: failed to do request: Head "https://172.16.13.61:5000/v2/mytest/demo/blobs/sha256:9ebda4cd8288db14d228fc0a911b1eeb7e74d55b01fc3534bfe4d7d46c1ffabb": http: server gave HTTP response to HTTPS client
helm.go:84: [debug] failed to do request: Head "https://172.16.13.61:5000/v2/mytest/demo/blobs/sha256:9ebda4cd8288db14d228fc0a911b1eeb7e74d55b01fc3534bfe4d7d46c1ffabb": http: server gave HTTP response to HTTPS client

**Comment by sabre1041** [comment]
@dreamerkr support is not available for non https based OCI registries. There is a concerted effort to strengthen the capabilities surrounding OCI which is being tracked in #11352

**Comment by dreamerkr** [comment]
> @dreamerkr support is not available for non https based OCI registries. There is a concerted effort to strengthen the capabilities surrounding OCI which is being tracked in #11352

tks,now，How to solve this problem? the best solution use https? but I only want try it

**Comment by dreamerkr** [comment]
> @dreamerkr support is not available for non https based OCI registries. There is a concerted effort to strengthen the capabilities surrounding OCI which is being tracked in #11352

now，we support push helm chart to Docker Registry？

**Comment by sabre1041** [comment]
@dreamerkr can you elaborate on your question?

**Comment by dreamerkr** [comment]
> @dreamerkr can you elaborate on your question?

I want push helm chart file to Docker Registry，I can run [Docker Registry](https://docs.docker.com/registry/deploying/)，Question whether pushing the helm chart file to Docker Registry？

**Comment by joejulian** [comment]
This and #11683 are duplicates. Closing this one as the other has more activity.

**Comment by cridam** [comment]
@joejulian , reading the description, i don't think the issue are duplicated. This thread was about non https registry, while the other is about self-signed registry. Can you/we reopen it ?

**Comment by sabre1041** [comment]
@cridam you are correct, plain HTTP support was not added in the original PR. @souleb was going to look into adding that capability once the first PR was merged. 

Reopening issue.
