### ISSUE TITLE
helm init: please don't assume cluster install

### ISSUE THREAD

**Issue by philips** [helm/helm#1168]
I really appreciate fast onboarding of helm. But, the `helm init` process was a bit too magical: I wasn't prepared for the system to just use my default kubectl context and install a new deployment into my kube-system namespace. Perhaps we can break out init into two parts:
1. helm init: installs the HELM_HOME and tells you to run `helm cluster-install` to install the cluster component?
2. helm cluster-install: installs tiller and also has flags to choose the cluster context, target namespace, etc.

**Comment by sgoings** [comment]
I actually really like the default behavior of a single command to get a working helm/tiller up and running! It seems like you're surprised by _where_ tiller got installed (not that it was installed on `init`). Is that truly the problem you're looking to solve with this issue (raising awareness somehow that the command is doing local + remote work)?

**Comment by philips** [comment]
@sgoings I am a Kubernetes enthusiast and so I just download the tool for the first time and want to try buildin a package. I do the usual copy/paste of instructions from GitHub and little do I know the thing called "init" just installed something to my production cluster because that was the current context of `kubectl`.

I think it needs to be renamed to something like `helm cluster-install`. Or perhaps we add a `helm init --cluster-install` flag, that way it is still one command.

**Comment by JeanMertz** [comment]
I agree, and was equally surprised. As a Kubernetes enthusiast, I try a lot of Kubernetes-related tools that could enhance the productivity of the engineers working at our company, but I want to test those tools within the confines of my laptop and Minikube cluster.

I had to warn my colleagues on a Saturday "it was me installing something in kube-system, don't be alarmed", because I was experimenting with Helm.

**Comment by bacongobbler** [comment]
Right now there is `helm init --client-only` if you just want to bootstrap the client itself.

**Comment by jascott1** [comment]
I agree we should close this issue as the docs seem to inform about the behavior 
https://github.com/kubernetes/helm/blob/master/docs/install.md#easy-in-cluster-installation
https://github.com/kubernetes/helm/blob/master/docs/quickstart.md#prerequisites

**Comment by bacongobbler** [comment]
closing as intentional by design.

**Comment by bacongobbler** [comment]
Oh sorry. I missed the "keep open" label on this label. @thomastaylor312 want me to re-open this as a talking point for Helm 3?

**Comment by thomastaylor312** [comment]
@bacongobbler Yeah, let's keep it open and I'll put it in the "upcoming - major" milestone so we make sure to revisit this

**Comment by jaygorrell** [comment]
As a long-time k8s user (but new Helm user), I came to post just this. I have a few engineers that will be setting up helm but the cluster only needs installed once -- given that scenario at least, it does seem unexpected that installing the server-side would happen by default.

I like the idea of `init` for client-side with an extra parameter for the server-side... or at least a `--yes` confirmation required for the current init behavior. Though that doesn't seem to be a pattern in Helms CLI.

**Comment by stealthybox** [comment]
Helm 3 removes Tiller, so this issue doesn't apply.

For Helm 2, this would be a breaking change.
I agree that the default U/X for this is dangerous though, so it's worth considering.

**Comment by bacongobbler** [comment]
Yeah, I think because we've already removed tiller in dev-v3 we can assume this can be closed as being implemented in Helm 3. Let's close this out once we release an alpha though :)

**Comment by bacongobbler** [comment]
closing as implemented in the dev-v3 branch.
