### ISSUE TITLE
update helm chart

### ISSUE THREAD

**Issue by abdelaziz009** [helm/helm#11699]
hello guys,
I am trying to install rancher using helm chart and i am stuck with below error  and i am new in helm chart how can i edit it to make it compatible with my k3s version 

Error: INSTALLATION FAILED: chart requires kubeVersion: < 1.22.0-0 which is incompatible with Kubernetes v1.25.3+k3s1
helm.go:84: [debug] chart requires kubeVersion: < 1.22.0-0 which is incompatible with Kubernetes v1.25.3+k3s1

helm version:
version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.18.9"}

**Comment by hickeyma** [comment]
@abdelaziz009 The error message is saying that the chart you are using can only be deployed on a Kubernetes cluster where the version is less than 1.22.x. You are trying to deploy it on cluster version 1.25.3.
