### ISSUE TITLE
Private AKS is not able to find the path of my local files to do a deployment through Helm

### ISSUE THREAD

**Issue by hvaandres** [helm/helm#11697]
Helm Version:  3
Kubernetes Version: 1.23.12

I'm currently trying to deploy my helm charts through my private aks cluster. However, I'm unable to do anything since it can't find the path of my local directory.

This is the command that I'm running:

```
az aks command invoke \
--resource-group aharo-aks-appgateway01 \
--name aharo-aks02 \
--command "helm install haro ./haro_files_helm_chart" 
```
This is the error message that I'm getting

```
command started at 2023-01-06 22:49:46+00:00, finished at 2023-01-06 22:49:46+00:00 with exitcode=1
Error: INSTALLATION FAILED: path "./haro_files_helm_chart" not found

```
To prove that this type of command can work, I tried one from the Microsoft Documentation:

```
az aks command invoke \   
--resource-group aharo-aks-appgateway01 \
--name aharo-aks02 \  
--command "helm repo add bitnami https://charts.bitnami.com/bitnami && helm repo update && helm install my-release bitnami/nginx"

```

What else can I do to find the path of my directory? Do you know if I could be missing any configuration on my cluster?

**Comment by joejulian** [comment]
according to the documentation, I suspect you need the `--file` flag. https://learn.microsoft.com/en-us/cli/azure/aks/command?view=azure-cli-latest#az-aks-command-invoke

This is not a helm question, so I'm closing it. Please see Microsoft support resources for help with their cli.
