### ISSUE TITLE
Wait for CRD ready state

### ISSUE THREAD

**Issue by rpuserh** [helm/helm#11717]
I have [CRD](https://github.com/hashicorp/terraform-helm/blob/main/example/workspace_random.yml) which I want to wrap to helm(template).

The question is how do I know if CRD resource is ready?
In other words, I want cli to wait until CRD becomes ready when using --wait

**Comment by joejulian** [comment]
The wait flag already waits for CRD readiness: https://github.com/helm/helm/blob/76157c6d06f981a42bfbb9ec636bae5443cb2c8f/pkg/kube/ready.go#L153-L163

**Comment by rpuserh** [comment]
I'm trying to use terraform k8s operator (but it's not waiting even when using --wait flag with helm  )

also reached terraform k8s operator team here is ticket: https://github.com/hashicorp/terraform-k8s/issues/155

**Comment by joejulian** [comment]
That's not terraform, that's FluxCD. I see you say it takes 15 minutes. The helm default is 5 minutes. Perhaps you need to extend the timeout. For FluxCD, see their documentation: https://fluxcd.io/flux/components/helm/helmreleases/

For support with FluxCD, see https://fluxcd.io/support/#getting-help-from-the-flux-community

**Comment by rpuserh** [comment]
HELM status changes to ready in a few seconds.
However, helm created resource is not ready (it becomes ready ~15 min). 

I want helm to wait for created resources to become ready.

**Comment by joejulian** [comment]
Ah, so you don't mean the CRD, you mean the custom resource. There's no way to determine when a custom resource is ready - or even if a custom resource _can_ be ready. There's no standard. This would need to be tackled in kubernetes before helm could do anything.

**Comment by aweis89** [comment]
Until there's an official standard, why not just create a simple interface and check if it's implemented so we have a way to achieve this common use-case?

Could be as simple as:
```go
type HelmReadiness interface {
    Ready() bool
}
` ``

**Comment by joejulian** [comment]
Maybe you can do that with hooks: set up a pod that checks the custom resource for your desired status. It can't be done as part of the helm binary though. It's not up to helm to create kubernetes standards. iirc, that's under the authority of sig-apimachinery.

**Comment by zmberg** [comment]
@joejulian Can helm support CR like [this](https://argo-cd.readthedocs.io/en/stable/operator-manual/health/#custom-health-checks)?

**Comment by drewwells** [comment]
Can we update the title to `CR` and re-open this? Helm does not support ready status of CRs: https://github.com/helm/helm/blob/main/pkg/kube/ready.go#L88

**Comment by drewwells** [comment]
Just checking how kubectl works, CRDs define additional printer columns that kubectl will use. 

https://github.com/kubernetes/kubernetes/blob/55f2bc10435160619d1ece8de49a1c0f8fcdf276/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types.go#L72

A very standard one is type=Ready, see cert-manager 
https://github.com/cert-manager/cert-manager/blob/master/deploy/crds/crd-certificates.yaml#L28

Helm could attempt to divine this and return True if it doesn't match
