### ISSUE TITLE
Helm Parent values override not replicating to sub charts

### ISSUE THREAD

**Issue by MalcolmCyber** [helm/helm#11719]
``
Hi,

If I have a parent chart with sub charts, and parent chart has a generic values file that I want to use the -f flag to override values based on the environment I install the chart to, the sub charts do not pick up the override parent values. The child chart was added via helm dependency build.

Folder structure:
```
child/
- templates/
- chart.yaml
- values.yaml

parent/
   - charts/
         - chart-version.tgz
   - templates/
   - Chart.yaml
   - values.yaml

helm-overrides/
   - parent-tst-override.yaml
   - parent-prd-override.yaml
```

The parent Chart.yaml looks like:

```
apiVersion: v2
appVersion: "1.0"
name: parent
version: "1.0"
dependencies:
- name: child
  version: "1.0"
  condition: child.enabled
  repository: "file://../child/"
```

The commands below return the values of the parent values.yaml rather than the override parent values.

```
cd parent
helm dependency build
cd ..
helm template name parent -f ../helm-overrides/parent-tst-override.yaml
```

Ideally I want the values from the helm-overrides YAML to be passed to the child template output yaml. It currently only takes it from the parent values.yaml file.
```
helm version
`version.BuildInfo{Version:"v3.10.0", GitCommit:"ce66412a723e4d89555dc67217607c6579ffcb21", GitTreeState:"clean", GoVersion:"go1.18.6"}`
```

**Comment by joejulian** [comment]
Your description sounds like that fits the [documentation](https://helm.sh/docs/chart_template_guide/subcharts_and_globals/). To override a child's value, you'd need to prefix it with `child` in the parent values. Perhaps you're looking to use `global`?

**Comment by MalcolmCyber** [comment]
Hi @joejulian  I can override in the parents values files, but I don't want to do that as it causes complications in the way we deploy the `parent` helm to different environments. If I override using a separate YAML file it does not override the `child` values, even for `global.`

**Comment by joejulian** [comment]
Ah, but it does.

myoverride.yaml
```
global:
   foo: "fubar"
child:
  bar: "baz"
```

```
helm template parent/ -v myoverride.yaml
```

in both charts, .Values.global.foo will be "fubar" and in the child chart .Values.bar will be "baz".

**Comment by EvertonSA** [comment]
> Ah, but it does.
> 
> myoverride.yaml
> 
> ```
> global:
>    foo: "fubar"
> child:
>   bar: "baz"
> ```
> 
> ```
> helm template parent/ -v myoverride.yaml
> ```
> 
> in both charts, .Values.global.foo will be "fubar" and in the child chart .Values.bar will be "baz".

do you mean?

```helm template parent/ -f myoverride.yaml```

**Comment by EvertonSA** [comment]
> Ah, but it does.

I also confirm it does. I was facing an issue with grafana loki and azure, but I was doing it wrong, needed something like this:

```
loki:
  loki:
    storage: azure
    azure:
    ...
    
```

**Comment by joejulian** [comment]
Closing as answered.
