### ISSUE TITLE
Format of config.json

### ISSUE THREAD

**Issue by tashoyan** [helm/helm#11714]
What is the format of the file config.json, which is accepted by the command line argument `--registry-config`? I did not find any specification in the documentation.
My goal is to specify registry URL, username, password in this config file.

Output of `helm version`:
version.BuildInfo{Version:"v3.9.1", GitCommit:"a7c043acb5ff905c261cfdc923a35776ba5e66e4", GitTreeState:"clean", GoVersion:"go1.17.5"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:51:43Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.10", GitCommit:"eae22ba6238096f5dec1ceb62766e97783f0ba2f", GitTreeState:"clean", BuildDate:"2022-05-24T12:50:52Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): On premise

**Comment by joejulian** [comment]
It's a docker [ConfigFile](https://github.com/docker/cli/blob/850fb6921cf7a208fd47d83074f27d0eb7ae268e/cli/config/configfile/file.go#L18) that is used for storing auths to registries and other docker configuration. If you've logged in to docker hub, look at `~/.docker/config.json` for the most common use case.

**Comment by tashoyan** [comment]
Thanks. Maybe makes sense add a reference in Helm documentation
