### ISSUE TITLE
Bug: why do all operations try to load kubeconfig?

### ISSUE THREAD

**Issue by ksharma-qc** [helm/helm#11722]
Operations like helm login or helm push shouldn't require a kubeconfig file. The current behavior is to print a warning, which has cascading effect on software which wrap around Helm. Such as the maven-helm-plugin which fails execution. 

It would be ideal to not try to load the kubeconfig for operations that don't need Kubernetes cluster access.

**Comment by joejulian** [comment]
Technically not a bug as it's working as designed.

I don't have an answer to why, however.

**Comment by joejulian** [comment]
Since this was answered and there's been no further activity, I'm going to go ahead and close this.
