### ISSUE TITLE
command like `helm version` but that tells compiled version of kubernetes?

### ISSUE THREAD

**Issue by ericb-summit** [helm/helm#11724]
As it stands now if you run helm against a chart that requires a k8s minor version that is newer than that compiled against helm, you get a human readable error that (having never seen it before) is ambiguous as to whether it is the client or the backend that is too old.

I have seen this [useful table](https://helm.sh/docs/topics/version_skew/#:~:text=As%20of%20Helm%203%2C%20Helm,n%2D1%20versions%20of%20Kubernetes), and that is excellent for humans (thanks).

But is there a helm command that outputs the k8s versions supported by the helm binary?  It would be nice to know a priori so that scripts calling helm could check this and fail early.

Right now the only options I see are 
a) blind faith, and fail at some point later; let the user figure it out
c) copy paste the helm version <-> k8s version data from the table into the script (and keep doing so)

Thanks

**Comment by joejulian** [comment]
Helm uses client-go. They used to publish a [compatibility table](https://github.com/kubernetes/client-go#compatibility-matrix) but it hasn't been updated in a long time. Without upstream publishing the compatibility matrix, I'm not sure how the helm project could have any better data.

**Comment by joejulian** [comment]
Since this was answered and there's been no further activity, I'm going to go ahead and close this.
