### ISSUE TITLE
[Organisational] Look for new/additional Maintainers

### ISSUE THREAD

**Issue by Ornias1993** [helm/helm#11732]
This is basically an "organisational" bug.

A lot of PR's get completely ignored by the current maintainers, some being finished and all feedback fixed... Just get ignored months or sometimes even years. This is hurting Helm as a product and a project.

This showcase Helm should be **actively** be looking for additional maintainers and showcases that the current maintainers, that are only really responsive to PR's from their inner circle, *may* even need to step-down.

I'm aware this is an controversial and somewhat unfriendly position to take.
But even as a maintainer myself, 250+ PR's that mostly don't even get basic responses *combined* with not actively looking for help, becomes the point that "just being overburdened" turns into "negligence".

I'm not saying "kick them out", but as maintainers it's also our/your job to actively look for help if you cannot handle your job.
Yes, finding more maintainers or contributors is freaking hard, I'm aware, but at least show us you put effort into fixing the issue this important project is plagued with.

*note:
I'm using job loosely here:
Pro-Deo and Pro-Pecunia

**Comment by joejulian** [comment]
This is not helpful. The solution to these issues is to find ways to help. Criticism via github issue will not do that. Closing.

**Comment by stavros-k** [comment]
> This is not helpful. The solution to these issues is to find ways to help. Criticism via github issue will not do that. Closing.

Maybe pin an issue, that helm is looking for maintainers? (Assuming that's the case).

That at least will let people know if you are going to accept maintainers.
Maybe also some info as to what areas Helm needs assistance from those maintainers.
