### ISSUE TITLE
Multiple ingresses are not deleted after helm failure 

### ISSUE THREAD

**Issue by julya935** [helm/helm#11731]
Steps to reproduce the bug:

1. Deploy a release with an ingress which has a certain host and a path
2. Deploy another release in the same namespace with several different ingresses one of which is identical to the one in (1)

Expected behavior: 
release fails with an error:
`Error: release test1 failed, and has been uninstalled due to atomic being set: admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: host "test.com" and path "/" is already defined in ingress test2` 
release rolls back with all related resources (including ingresses).

 What we've got in reality:
release fails with an error:
`Error: release test1 failed, and has been uninstalled due to atomic being set: admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: host "test.com" and path "/" is already defined in ingress test2` 
release rolls back but **ingresses are kept present** except for the one which overlapped with the other one.

Output of `helm version`:
`version.BuildInfo{Version:"v3.9.0",  GoVersion:"go1.17.5"}`
Output of `kubectl version`: 
`Client Version: version.Info{Major:"1", Minor:"21", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}`
Cloud Provider/Platform (AKS, GKE, Minikube etc.): Yandex Cloud

**Comment by joejulian** [comment]
Perhaps you could supply a minimum repro. If you need to upload charts, just tar them up and use the attach feature (keep it as small as possible).

There are a couple possibilities off the top of my head: the rollback failed and the release is in error, or the ingresses not deleted were installed as hooks.

Metadata from the ingresses that you expected to be deleted might be helpful, as well as `helm history`.

**Comment by julya935** [comment]
[test.tar.gz](https://github.com/helm/helm/files/10498769/test.tar.gz)
You should firstly deploy chart1 and then chart2 to reproduce the case

**Comment by joejulian** [comment]
Didn't fail for me as I don't have whatever webhook would be validating the condition.

**Comment by julya935** [comment]
Sorry, install https://kubernetes.github.io/ingress-nginx chart version: "4.2.0" with default values

**Comment by joejulian** [comment]
Install chart1 which has 1 ingress record attached to the root path, `/`.

Install chart2 which has 3 ingress records, one of which also is attached to the root path.

The nginx webhook blocks the installation of the Ingress with the duplicate path.

The uninstall sometimes fails to remove some or all of the Ingress resources because the records may not be seen by the client at the time of the delete.

```
$ helm install --debug -n foo test2 chart2 --create-namespace --atomic --wait
install.go:193: [debug] Original chart version: ""
install.go:210: [debug] CHART PATH: /tmp/test_repro/chart2

client.go:133: [debug] creating 1 resource(s)
client.go:133: [debug] creating 3 resource(s)
install.go:442: [debug] Install failed and atomic is set, uninstalling release
uninstall.go:95: [debug] uninstall: Deleting test2
client.go:477: [debug] Starting delete for "test2-test2" Ingress
client.go:477: [debug] Starting delete for "test2" Ingress
client.go:477: [debug] Starting delete for "test2-test" Ingress
client.go:481: [debug] Ignoring delete failure for "test2-test2" networking.k8s.io/v1, Kind=Ingress: ingresses.networking.k8s.io "test2-test2" not found
client.go:481: [debug] Ignoring delete failure for "test2-test" networking.k8s.io/v1, Kind=Ingress: ingresses.networking.k8s.io "test2-test" not found
client.go:481: [debug] Ignoring delete failure for "test2" networking.k8s.io/v1, Kind=Ingress: ingresses.networking.k8s.io "test2" not found
uninstall.go:148: [debug] purge requested for test2
Error: INSTALLATION FAILED: release test2 failed, and has been uninstalled due to atomic being set: admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: host "test.com" and path "/" is already defined in ingress foo/test1
helm.go:84: [debug] admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: host "test.com" and path "/" is already defined in ingress foo/test1
release test2 failed, and has been uninstalled due to atomic being set
helm.sh/helm/v3/pkg/action.(*Install).failRelease
	helm.sh/helm/v3/pkg/action/install.go:450
helm.sh/helm/v3/pkg/action.(*Install).reportToRun
	helm.sh/helm/v3/pkg/action/install.go:434
helm.sh/helm/v3/pkg/action.(*Install).performInstall
	helm.sh/helm/v3/pkg/action/install.go:372
runtime.goexit
	runtime/asm_amd64.s:1594
INSTALLATION FAILED
main.newInstallCmd.func2
	helm.sh/helm/v3/cmd/helm/install.go:141
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.6.1/command.go:916
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.6.1/command.go:1044
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.6.1/command.go:968
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
	runtime/proc.go:250
runtime.goexit
	runtime/asm_amd64.s:1594
```

A workaround is to not use the `--atomic` flag and, instead, uninstall the failed chart. In my tests, this was sufficient:
```
helm install --debug -n foo test2 chart2 --create-namespace || helm delete -n foo test2 
```

One possible fix might be to close the client after the install and to create a new client to do the delete. This should ensure the client's not operating from cache.
