### ISSUE TITLE
Uninstalling Chart Releases in pending states does not remove all resources

### ISSUE THREAD

**Issue by Kartikey-star** [helm/helm#11730]
I tried to install  Gitlab helm chart using cli https://artifacthub.io/packages/helm/gitlab/gitlab?modal=install . This particular chart takes some time to move to deployed state. While the chart release is still in pending install state i uninstall the release from a different terminal. The release is uninstalled but the the process of install is still in progress.  After sometime the resources tagged with the release start appearing , though the release does not exist.
Steps to reproduce,
1 Install gitlab helm chart. `helm install gitrelease  gitlab/gitlab --version 6.7.3 --set certmanager-issuer.email=km@gmail.com`
2. From a new terminal check the status of release. ``helm status gitrelease`
3. While the state is stiil pending-install uninstall the Helm release with helm uninstall gitrelease
4. Since we did not kill the Helm install command , the resources related to the release keep getting created while release no longer exist.

Output of `helm version`:
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/arm64"}
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Openshift Cluster

**Comment by joejulian** [comment]
Helm is not intended to be used in parallel. You must stop the installation before deleting.

**Comment by Kartikey-star** [comment]
Hi @joejulian I agree that the issue would not occur if the install command is stopped and then we move to uninstall. But i believe the issue is very much reproducable if one user starts an installation and another user in same namespace goes for a deletion of the release in pending install phase
