### ISSUE TITLE
Helm orphans network policy resources

### ISSUE THREAD

**Issue by patrick-vonsteht** [helm/helm#11748]
Hi, we encounter an issue that leads to helm leaving orphaned network policy resources in the cluster.

I could reproduce two cases:

Case 1:
Start with a _successful_ deployment without network policy
Execute an _unsuccessful_ deployment with a network policy
Execute another unsuccessful deployment with a _renamed network policy_
Result: both network policies are still there
Expected result: only one network policy is there (with the last chosen name)

Case 2:
Start with a _successful_ deployment with a network policy
Execute an _unsuccessful_ deployment with a network policy _with changed name and port_
Result: both network policies are still there
Expected result: only one network policy is there (with the last chosen name)

As soon as we reached the first failed state, it seems that helm is in a broken state and every further rename of a network policy continues to create a new network policy without cleaning up the old one.

As a counter test, I also tested various renames and port changes with _successful_ deployments. For example this sequence worked without problem:
```
Set name to test-network-policy-1
Set name to test-network-policy-2
Set name to test-network-poilcy-123
Set name to test-network-poilcy-1234567
Set port to: 99
Set port to: 123, Set name to: test-network-policy-123
Set port to 87, Set name to: test-network-policy-blablu
```

As another counter test, I also tested case 2 with _just a name change_. This didn't lead to the problem.
As another counter test, I also tested case 2 with _just a port change_. This didn't lead to the problem.
As another counter test, I also tested case 2, but _started with an unsuccessful deployment_. This didn't lead to the problem.
As another counter test, I also tested case 1, but _started with an unsuccessful deployment without network policy_. This didn't lead to the problem.

See the following repository for a minimal example code, instructions on how to reproduce this issue with the minimal example, and example output with more details about case1 and case 2 mentioned above: https://github.com/patrick-vonsteht/test-netpol-deploy-fail

---

Output of `helm version`:
version.BuildInfo{Version:"v3.10.2", GitCommit:"50f003e5ee8704ec937a756c646870227d7c8b58", GitTreeState:"clean", GoVersion:"go1.18.8"}

Output of `kubectl version`:
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:27:13Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Docker Desktop

**Comment by joejulian** [comment]
Are you using the `--atomic` flag? Is the rollback successful?

**Comment by patrick-vonsteht** [comment]
I'm not using the `--atomic` flag. My helm command looks like `helm upgrade --install --wait --timeout 5s ...`.

The roll back works successfully and leaves helm in a healthy state. The problem only occurs if we upgrade to a new release without rolling back first.

**Comment by joejulian** [comment]
I believe this sounds like it's working as intended. The resources that remain from an error state are not valid. Helm operates from the last `deployed` state. This is why the atomic flag, and the rollback command exist, to return your resources to a known-good state from which to operate.

**Comment by joejulian** [comment]
This looks to me like it's resolved. Closing.
