### ISSUE TITLE
Question/support - How to separate array of string controlled via values.yaml

### ISSUE THREAD

**Issue by harshsingh-cs** [helm/helm#11743]
Output of `helm version`:
version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"clean", GoVersion:"go1.19"}
Output of `kubectl version`:
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-08-05T16:28:52Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): local testing 

I want to achieve something like this in my config.toml

config.toml
animals = ["lion", "cat", "tiger"]

what i did  in my config.toml
animals = [{{ .Values.wildlife }}]
and used these values.yaml 
values.yaml 
wildlife = "lion","cat","tiger"

but i do not see every string with "" quotes
here are the results 
-       animals = ["test", "foo", "bar" ]
+       animals = [ lion,cat,tiger]

**Comment by joejulian** [comment]
Assuming that .Values.wildlife is a list of strings, you could:
```
animals = {{ toJson .Values.wildlife }}
```

**Comment by harshsingh-cs** [comment]
@joejulian  using this 
`animals = {{ toJson .Values.wildlife }}`

it actually outputs as 

`+       animals = [ "lion,cat,tiger"]`

rather I want it to be 
`animals = ["lion", "cat", "tiger"]`

**Comment by joejulian** [comment]
Well I did say, "Assuming that .Values.wildlife is a list of strings" :)

If you want to use a string and split it at some arbitrary character:
```
animals = {{ toJson (split "," .Values.wildlife) }}
```
the idea being that if you have a list of strings, toJson will create `["string1","string2","string3"]` or you can always use the classical split/join combination to build your string.

**Comment by harshsingh-cs** [comment]
@joejulian  
not sure what i am doing wrong here 
after using toJson I am getting 
`+  animals = [ {"_0":"cat","_1":"cat","_2":"tiger"} ]`
I would want to remove unnecessary `{}` and `_0...`

my values.yaml 
`wildlife: lion,cat,tiger`

help is appreciated

**Comment by stavros-k** [comment]
Assuming `.Values.wildlife` is a `string`

`values.yaml`
```yaml
wildlife: '"lion","cat","tiger"'
```
tpl
```yaml
config.toml:
  animals = {{ join "," (values ((split "," .Values.wildlife) | toJson | fromJson)) }}
```

output
```yaml
config.toml:
  animals = "lion","cat","tiger"
```

**Comment by joejulian** [comment]
Why am I just learning about helm-playground now? :grin: 

`values.yaml`
```
wildlife: "lion,cat,tiger"
```
template:
```
config.toml:
  animals = {{ toJson (splitList "," .Values.wildlife) }}
```
output
```
config.toml:
  animals = ["lion","cat","tiger"]
```


https://helm-playground.com/#t=LQhQGMHsDsDMEsDmA6ALpAtgGwFygAT4CG08GRWAzvgLz4De9%2B6AUpTPgBSUAOW8qADLxKqfACIANOPzIAahQCuAU0rIA7vCwATfrGUBKfAF9joIA&v=LQhQHcEsBsBNsgMwKYC4AEByBB7AdgDQDGAhgC4FmQDmyATpkA

**Comment by baeyf** [comment]
I am kinda facing the same problem as @harshsingh-cs 

tried the suggestion by @stavros-k  but the sting is not getting enclosed within double quote ""
only difference is i am using if statements 

helm diff - 
`+       api = [ debug,bor,admin,net,eth,web3,txpool ]`

values.yaml 
```
apiMngt: net,eth,web3,txpool,debug,bor,admin
apiMngtMasterNode: net,eth,web3,bor
```
config file- 
`api = [{{ if .Values.masternode }} {{ join "," (values ((split "," .Values.apiMngtMasterNode) | toJson | fromJson)) }} {{ else }} {{ join "," (values ((split "," .Values.apiMngt) | toJson | fromJson)) }} {{ end }}]`

how would i place the list of string in double quotes

**Comment by stavros-k** [comment]
@baeyf  the SplitList @joejulian mentioned will work for you just fine (you can even skip the `[]` on `api`

**Comment by joejulian** [comment]
I'm going to go ahead and close this as answered.
