### ISSUE TITLE
no repository definition for https://charts.helm.sh/stable, https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami

### ISSUE THREAD

**Issue by freebased** [helm/helm#11762]
Could be similar to: https://github.com/bitnami/charts/issues/10586, https://github.com/bitnami/charts/issues/10539

Hello, my GitHub Actions pipeline returns me an error regarding helm repository for graylog

```
Packaging chart 'charts/graylog'...
Error: no repository definition for https://charts.helm.sh/stable, https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
```

At first it had a problem with https://charts.bitnami.com/bitnami and https://charts.helm.sh/stable repositories, then i found https://github.com/bitnami/charts/issues/10586, https://github.com/bitnami/charts/issues/10539 and replaced `https://charts.bitnami.com/bitnami` with `https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami`, but it still gives me an error regarding the repos, you can find graylog chart attached in tar.gz file.

GitHub Actions workflow: https://helm.sh/docs/howto/chart_releaser_action/#github-actions-workflow

[graylog.tar.gz](https://github.com/helm/helm/files/10480148/graylog.tar.gz)

**Comment by freebased** [comment]
error also relates to mariadb-galera...
```
Packaging chart 'charts/mariadb-galera'...
Error: no repository definition for https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
```
...mongodb itself (not only in graylog) and prometheus

**Comment by joejulian** [comment]
See if you can curl https://charts.bitnami.com/bitnami/index.yaml. If you cannot, check your proxy and proxy configuration.

**Comment by joejulian** [comment]
I'm going to go ahead and close this as inactive.
