### ISSUE TITLE
Selectively Deploy resource based on some condition e.g Dev Environment

### ISSUE THREAD

**Issue by drtobbyas** [helm/helm#11768]
How can I selectively deploy some resources based on predefined conditions? For example,  I have a Helm chart with deployment, config map, ingress, service e.t.c, I want to deploy the deployment and service in my Development environment ignoring the ingress resources and configMap but deploy all in the production environment. 

Please how do I achieve this? This will be a great feature to help prevent having to keep multiple helm charts for the same application for the different environments.

Output of `helm version`: version.BuildInfo{Version:"v3.10.2", GitCommit:"50f003e5ee8704ec937a756c646870227d7c8b58", GitTreeState:"clean", GoVersion:"go1.18.8"}

Output of `kubectl version`: lient Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.8", GitCommit:"fdc77503e954d1ee641c0e350481f7528e8d068b", GitTreeState:"clean", BuildDate:"2022-11-09T13:38:19Z", GoVersion:"go1.18.8", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4+k3s1", GitCommit:"c3f830e9b9ed8a4d9d0e2aa663b4591b923a296e", GitTreeState:"clean", BuildDate:"2022-08-25T03:45:26Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  All

**Comment by joejulian** [comment]
There's a couple ways of handling this. In your template, wrap sections in `if` blocks:
```
{{- if .Values.ingress.enabled }}
...
{{- end }}
```
then in your `dev.yaml` values:
```
ingress:
  enabled: false
```
This is the most common method.

If you don't have control over your charts, you can use [kustomize](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/) as a `--post-renderer` to alter the manifest before it's committed.

**Comment by joejulian** [comment]
closing this as answered
