### ISSUE TITLE
helm list --all-namespaces is empty

### ISSUE THREAD

**Issue by aruns05** [helm/helm#11761]
Output of `helm version`:
version.BuildInfo{Version:"v3.11.0", GitCommit:"472c5736ab01133de504a826bd9ee12cbe4e7904", GitTreeState:"clean", GoVersion:"go1.19.5"}

helm list --all-namespaces  This is not fetching any record.  I got updates that helm init is no longer needed in helm 3 and above. Can anyone advise what can be done

Output of `kubectl version`:

Cloud Provider/Platform AKS

**Comment by hickeyma** [comment]
@aruns05 have you deployed charts to the cluster you are connecting to using Helm 3?

**Comment by joejulian** [comment]
From your question, I have a couple of theories:

One theory is that you installed charts with helm 2 and are now trying to manage them with helm 3. If true, see the [helm-2to3](https://github.com/helm/helm-2to3) plugin.

@hickeyma already offered the obvious

The third possibility is that you're trying to list failed releases. `helm list`, by default, only lists releases in a "deployed" state. To view releases in other states, add the `--all` flag.

**Comment by joejulian** [comment]
I'm going to go ahead and close this as inactive.
