### ISSUE TITLE
Create global variables for template

### ISSUE THREAD

**Issue by LaurentAerens** [helm/helm#11767]
Probably this is not possible but i was wondering if it is possible to create a variable that you can use within several definitions in my helper.tpl file. because now i have:

{{- define "sql.sapassword" -}}
{{- if not .Values.SQL.sapassword }}
{{- randAlphaNum 20 | nospace -}}
{{- else}} 
{{- .Values.SQL.sapassword -}}
{{- end -}}   
{{- end }}

but then i need to use that password to configure the sql database, call it in NOTES.txt and create a connection string with it.
i would do that like:

{{- define "connectionstringmsSQL" }}
{{- $passwd := include "sql.sapassword" .}}
{{- printf "Server=mssql;Database=master;User=sa;Password=%s;" $passwd -}}
{{- end }}

my current issue is that every time i use sql.sapassword it creates a different randAlphaNum.
Is it possible to create one var like:

{{- $sqlpasswd := randAlphaNum 20 | nospace }}

and then use that var in several places in the helper.tpl file?
Or is there a better way to do this?

**Comment by joejulian** [comment]
There's no way to do that and even if you could, it would change every time you ran your template. This is normally managed by requiring the user of the chart to specify a password.

**Comment by joejulian** [comment]
closing this as answered.

**Comment by Aiosa** [comment]
I would love to be able to have global variables accross templates, which do not come from `values.yaml`. I have bunch of URLs that are dynamically based on the service names, which are dependent on the release name. If I want to have pod dependencies (awaiting init container) or provide pods with urls to other pods, or simply define `NO_PROXY` I would have to compute urls of services in each yaml over and over again. I cannot use `values.yaml` as it cannot compute these dynamic hostnames.
