### ISSUE TITLE
Passing --atomic and --wait together

### ISSUE THREAD

**Issue by smartaquarius10** [helm/helm#11776]
Team,

If we pass both --wait and --atomic together then does atomic still works as is by overriding --wait flag?

I know that atomic flag internally includes wait's functionality as well. But, the issue is with Azure devops because HelmDeploy@0 task internally passes --wait flag by default. Hence, it is not possible to ignore it. 

Can we pass both flags together and still take the benefits of atomic flag like rollback etc. Please suggest. Thank you.

Kind Regards,
Tanul

**Comment by joejulian** [comment]
If wait or atomic is set, wait is set:
https://github.com/helm/helm/blob/76157c6d06f981a42bfbb9ec636bae5443cb2c8f/pkg/action/install.go#L236

So yes, it doesn't hurt to set both flags.

**Comment by smartaquarius10** [comment]
@joejulian got it thanks 🙂
