### ISSUE TITLE
Low level command for deploying built resources

### ISSUE THREAD

**Issue by VanCoding** [helm/helm#11783]
As far as I know, there is currently no way to only use the "deployment" part of helm, and completely skipping the "building resources" part. So if I build my kubernetes resources for example with [cdk8s](https://cdk8s.io/index.html) and I then want to deploy them using helm, I would have to create a "Chart.yaml" file and write the resources in a file in a "templates" directory. Only then, I could use `helm install` or `helm upgrade`. And even then, helm would still treat my resources as templates and look for placeholders inside them, which doesn't really make any sense.

It would of course be possible to directly apply the resources via `kubectl apply -f`, but then I would miss out on features like pruning old resources, deployment success checking or rollbacks. So using helm with built resources would still make a lot of sense.

So it would be cool to have some kind of low-level command to do just the deployment part of helm. I haven't looked into the source code, but building the resources and deploying them probably already is properly separated and I can imagine that it wouldn't even be that much work to implement this.

What do you think?

**Comment by joejulian** [comment]
I think this would require a helm improvement proposal (hip). See https://github.com/helm/community/blob/main/hips/hip-0001.md

**Comment by VanCoding** [comment]
It turned out that it is already somewhat possible to just pass the finished kubernetes resources to helm and have it deploy them.
It's more of a workaround, though:

In the templates directory, you'll just need one single file containing the following:
```
// templates/resources.yaml
{{- range $resource := .Values.resources -}}
---
{{- $resource | toJson }}
{{ end }}
```

And then, if you have your resources as JSON, for example like this:

```js
// resources.json
{
  "resources":[
    {
      "apiVersion": "apps/v1",
      "kind": "Deployment"
      /* ... */
    },
    {
      "apiVersion": "networking.k8s.io/v1",
      "kind": "Ingress",
       /* ... */
    }
  ]
}
```

They can be applied like this:
`helm upgrade --install -f - --namespace my-namespace --create-namespace my-app ./ < resources.json`

But normally, you probably wouldn't pipe static JSON resources to helm, but JSON generated by another tool.

I still think that it would be cool if helm supported that use case, but I don't have the time to create an HIP and therefore will close this.
