### ISSUE TITLE
Helm command to remove drift, resync k8s to most recently applied revision 

### ISSUE THREAD

**Issue by benjimin** [helm/helm#11784]
I'm looking for an idempotent helm command to revert any drift between the kubernetes cluster and the currently deployed revision of a release.

**Feature-proposal**
I'd like a command `helm sync [RELEASE_NAME]` that performs something like:

`helm get manifest <RELEASE_NAME> | kubectl apply -f -`

It doesn't increment (nor rollback) the revision. It just ensures that the deployment is still in the expected state, undoing any changes that may have occured "out of band" _since_ the current revision was deployed.

**Use-case**
Sometimes a kubernetes resource is modified in-place (by `kubectl edit`) to quickly experiment and trial whether a potential change will have the intended effect (before developing a new chart version etc). Also, especially in multi-developer clusters, occasionally a random kubernetes resource gets deleted unintentionally. It would be helpful to have a simple safe supported command that restores the resources if there is any discrepancy, and has no effect if there is no discrepancy.

**Alternatives**
AFAIK, other existing ways of fixing drift are more disruptive:
* Could `uninstall` the release, then `rollback` to reinstall the release, but this will momentarily cause service downtime (and risk  loss of persistent data).
* If using flux then can delete the HelmRelease with `kubectl delete --cascade=false hr/..` (prompting flux to automatically restore it), which triggers a reconciliation but loses the revision history.
* Could make a "substantive yet impactless" modification to the chart, and then `upgrade` the release. But this floods histories with spurious changes (and if repeated too frequently then _meaningful_ revision history expires).
* Could try deleting the Secret where helm has stored internal metadata concerning the current revision? But seems too reliant on undocumented behaviour.

**Summary**
Does this feature already exist? Is it already in the roadmap in some other form? Would a PR be received favourably?

**Comment by joejulian** [comment]
I believe you're looking for this `helm update` flag:
```
      --force     force resource updates through a replacement strategy
```

**Comment by benjimin** [comment]
@joejulian I'm not aware of the `helm update` command, is this a new feature or do you mean `helm upgrade`? 

The issue with the latter is that it requires re-supplying the chart/values, and so risks introducing even more drift from the desired state (if the user fails to exactly replicate the chart/values that were supplied previously). Also, it will add a spurious entry to the history.

Alternatively, did you mean something like:
```
helm rollback RELEASE $(helm history RELEASE -o json | jq '.[]|select(.status=="deployed").revision') --force
```
It still seems a _little_ cumbersome, needing to figure out the current release number, and still creating a spurious history entry (making me hesitant to apply it too frequently), but it seems like maybe the best available option in the absence of any command like the proposed `helm sync`.

My feature request is to add something like `helm sync` that can be run repeatedly if you are unsure whether drift has occurred, or even put in a cron job to ensure no drift is permitted. So the idea is it wouldn't require the user to specify anything about the current revision, and it wouldn't grow the history either (because it isn't supposed to change the release from what the helm user last specified). Do you think this idea is a bad fit for helm?

**Comment by joejulian** [comment]
Oops yeah. Upgrade. Doing too many things at once again.

**Comment by joejulian** [comment]
I'm at dinner now, but can't you use force with reuse-values?

**Comment by benjimin** [comment]
How would you ensure `helm upgrade` uses the exact same chart version as the most recent revision?

**Comment by joejulian** [comment]
The only way (today) is to pass it the same version. Someone was doing work toward getting the chart version to be easily extractable, but today it's kind of a pain. Here's how I get the version for the `operator` release in the `kadalu` namespace:

```
$ k get secret -n kadalu -l owner=helm,name=operator,status=deployed -o yaml | 
    yq -r '.items[0].data.release' | base64 -d | base64 -d | gunzip | 
    yq -r '.chart.metadata.version'
0.8.16
```

Note the `name` label matches the release. I only want the release with the `deployed` status (there should be only one). And, of course, that is the secret owned by helm.

Then it's just a `helm upgrade ... --version=0.8.16`.
