### ISSUE TITLE
Helm install/upgrade wait robustness

### ISSUE THREAD

**Issue by MichaelMorrisEst** [helm/helm#11789]
When we run helm install/upgrade commands with the '--wait' argument helm will periodically poll the cluster to check each of the objects it created and waits for them to complete before returning control back to the user. 
If at any time during this process (which can take a considerable time) there is any network interruption, or if the cluster has any temporary issue and doesn't respond to one of the periodic requests for an update on a status, helm will never attempt to reconnect, it bombs out immediately and marks the entire release as failed.

We would like to implement a solution that increase the robustness of the wait process by retrying failed requests. 

Proposal is to implement a new flag ('--wait-retries' perhaps)  on the install and upgrade commands that will instruct helm to retry failed status checks. There would be no retry in the case of a HTTP status code less than 500 as a retry would be unlikely to succeed.
Existing behaviour is maintained by default where the user does not make use of this new flag.

I will create a pull request of how I would envisage the code would look, but am open to other suggestions as to how to achieve the same goal if the community is agreeable to the concept

**Comment by joejulian** [comment]
@gjenkins8 You are correct, https://pkg.go.dev/k8s.io/client-go/tools/watch#UntilWithSync is intended to handle watches with error resiliency.

**Comment by MichaelMorrisEst** [comment]
Hi @gjenkins8 , @joejulian 

Thanks for your comments.

I have looked into your suggestion on using the watches and the PR related to jobs. The additional RBAC requirement would similarly be an issue here. The implementation could check the users permissions and proceed with watching or current impl based on the permissions. However this would mean the issue this PR is trying to address would still exist in the case where the user does not have the permission to watch. Its probably an idea worth pursuing but as an additional improvement rather than an alternative to what I am proposing here.

On the issue of whether a flag should be provided or keep re-trying up to a sane default, I think providing the flag gives the user most flexibility to adjust the number of retries based on the situation they are encountering while also enabling behaviour to be as today (if # retries set to 0). If we hard code a set number of retries there is always the danger that it will not suffice in a particular scenario but Im not opposed to a hard coded value instead if thats preferred

**Comment by ericsuhong** [comment]
We were encountering frequent "**http2: connection closed**" errors in our AKS environment, which was causing almost ALL helm deployments to fail while waiting for deployment to become ready.

We used this PR's implementation, and it completely fixed our deployment issue.

Now deployments are able to finish even with multiple transient http2 connection errors while helm is watching for deployment:
````
2024-01-08 16:45:40.782658: ready.go:281: [debug] Deployment is not ready: sampleservice/sampleservice-deployment. 0 out of 3 expected pods are ready
2024-01-08 16:45:42.748168: ready.go:281: [debug] Deployment is not ready: sampleservice/sampleservice-deployment. 0 out of 3 expected pods are ready
2024-01-08 16:46:27.741679: wait.go:86: [debug] Error received when checking status of resource sampleservice-service. Error: 'Get "
https://10.0.0.4/api/v1/namespaces/sampleservice/services/sampleservice-service
": http2: client connection lost', Resource details: 'Resource: "/v1, Resource=services", GroupVersionKind: "/v1, Kind=Service"
2024-01-08 16:46:27.741752: Name: "sampleservice-service", Namespace: "sampleservice"'
2024-01-08 16:46:27.741831: wait.go:93: [debug] Retryable error? true
2024-01-08 16:46:27.741953: wait.go:70: [debug] Retrying as current number of retries 0 less than max number of retries 30
2024-01-08 16:46:28.084141: ready.go:281: [debug] Deployment is not ready: sampleservice/sampleservice-deployment. 0 out of 3 expected pods are ready
2024-01-08 16:46:28.782072: ready.go:281: [debug] Deployment is not ready: sampleservice/sampleservice-deployment. 0 out of 3 expected pods are ready
..... Deployment eventually succeeds!
````

Is it possible to merge this robustness implementation into next helm release?
