### ISSUE TITLE
Is it possible to delete and create the deployment using helm?

### ISSUE THREAD

**Issue by smartaquarius10** [helm/helm#11785]
Hello,

We need to delete the pods or deployment first and then install/upgrade the new chart using helm.

Is it possible to do this with helm. We don't want rolling update. 

`helm del` and `helm uninstall` command will also remove the release history which we don't want. What is the best possible procedure can be followed to delete the old deployment and then start the new deployment using helm.

Any suggestions please. 

Kind Regards,
Tanul

**Comment by SoulPancake** [comment]
You can follow 
```
kubectl delete deployment <deployment-name>
```
and then 
```
helm install <chart-name> <release-name> <path-to-chart>
```
If you do not want to keep the release history, you can add the --reset-values or --recreate-pods flag when installing the new chart. This flag will recreate all the resources associated with the release.

**Comment by smartaquarius10** [comment]
No, I want to keep the history so that we can execute `helm rollback` whenever needed.

I was thinking if there is some flag in helm. I think this one is the only possible to perform the steps.. Thank you :)
