### ISSUE TITLE
Bug: Intermittent deployment of Helm tests, when using multiple tests   

### ISSUE THREAD

**Issue by zfalen-deloitte** [helm/helm#11792]
I have a helm chart with a `/templates/tests` directory as described here:
https://helm.sh/docs/topics/chart_tests/

Within the `tests` directory, I have two tests. One is a "readiness check" that uses a custom label on our pods to check whether any containers are _not_ in a "success" state. 

The other test is an "integration test" that runs a suite of API calls against individual `Service` objects _(routed via `Ingress`)_ to verify the stack is working correctly when a new image tag is used.

Both tests are configured per the documentation and have the `"helm.sh/hook": test` annotation etc.

Both of these tests are designed to run as part of a Github Actions CI/CD pipeline, and _(when running both)_ they are meant to happen in order `readiness-test` -> `integration-test` _(hopefully for obvious reasons 🙃)_. We target these tests using the `--filter` flag described in the docs link above. For instance:
`helm test ${{ steps.release-name.outputs.serviceTestReleaseName }} --filter name=${{ steps.release-name.outputs.serviceTestReleaseName }}-readiness-check -n ${{ steps.release-name.outputs.serviceTestNamespace }}`

This is working _most_ of the time, but _occasionally_, for reasons I don't really understand, only the _first_ test _(`readiness-check`)_ apparently gets deployed. When I run the follow-up command, with a different filter applied for `name`, the integration test does **not** run, e.g.
`helm test ${{ steps.release-name.outputs.serviceTestReleaseName }} --filter name=${{ steps.release-name.outputs.serviceTestReleaseName }}-integration-test -n ${{ steps.release-name.outputs.serviceTestNamespace }}`

^ Usually this command works great, stands up the test container, runs the `Pod` and all is well. When it works it spits out a log like so: 
```
Run helm test reporting-service-1-3-51 --filter name=reporting-service-1-3-51-integration-test -n reporting-service-1-3-51-int-test
NAME: reporting-service-1-3-51
LAST DEPLOYED: Mon Feb  6 18:54:24 2023
NAMESPACE: reporting-service-1-3-51-int-test
STATUS: deployed
REVISION: 1
TEST SUITE:     reporting-service-1-3-51-readiness-check
Last Started:   Mon Feb  6 [18](https://some-job-url.com)23
Last Completed: Mon Feb  6 18:55:32 2023
Phase:          Succeeded

TEST SUITE:     reporting-service-1-3-51-integration-test
Last Started:   Mon Feb  6 18:55:44 20[23](https://some-job-url.com)
Last Completed: Mon Feb  6 18:57:07 2023
Phase:          Succeeded
```

So, you see both tests ran, and succeeded. Awesome. But when it _fails_ to create the second job, we only get output from the _first_ test suite, like so:
```
Run helm test reporting-service-1-3-53 --filter name=reporting-service-1-3-53-integration-test -n reporting-service-1-3-53-int-test
NAME: reporting-service-1-3-53
LAST DEPLOYED: Mon Feb  6 20:02:31 2023
NAMESPACE: reporting-service-1-3-53-int-test
STATUS: deployed
REVISION: 1
TEST SUITE:     reporting-service-1-3-53-readiness-check
Last Started:   Mon Feb  6 20:05:54 2023
Last Completed: Mon Feb  6 20:05:56 2023
Phase:          Succeeded
NOTES:
```

Note that in the block above, the `--filter` is searching for `integration-test` by name, but we _only_ get output from the `readiness-check`. Interestingly enough, because my pipeline leaves the Helm deployment in place even when the pipeline fails so I can debug things, I am able to replicate the issue from my local command line. Running the `helm test` command as above produces the exact same output.

What's even _more_ interesting, is if I run `helm test` against the deployment _without_ any `--filter` flag, meaning it _should_ run all of the tests together, I _still_ only get output from the `readiness-check` test. 

**The MOST interesting part** is that if I "kick the tires" by running `helm upgrade`, using the _same_ chart / version and passing `--reuse-values`, which should theoretically make no updates to the deployment, the issue is completely resolved. E.x.

`helm test reporting-service-1-3-53 -n reporting-service-1-3-53-int-test`
I get only the first test, so i run...
`helm upgrade reporting-service-1-3-53 my-chart-repo -n reporting-service-1-3-53-int-test --reuse-values`
then, again...
`helm test reporting-service-1-3-53 -n reporting-service-1-3-53-int-test`
... This gives me _BOTH_ tests

**TWO THOUGHTS:**
1. It seems like the helm chart is just... occasionally skipping the second test during `install` and it picks it up again during `upgrade` - this is **probably where the bug is**.

2. Running `helm test` with a `--filter` flag, should _probably_ result in a `exit 1` failure if no matches are found for your specified filter, otherwise you get false-positives. 

Cheers
-Z

Output of `helm version` _(on the Github runner):_
version.BuildInfo{Version:"v3.11.0", GitCommit:"472c5736ab01133de504a826bd9ee12cbe4e7904", GitTreeState:"clean", GoVersion:"go1.18.10"}

Output of `kubectl version` _(on my local command line... not sure about the runner):_
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-ffeb93d", GitCommit:"f76e2b475d1433cdb6bd546e9e8f129fde938fb7", GitTreeState:"clean", BuildDate:"2022-11-29T18:41:00Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS EKS

**Comment by ccoffman4477** [comment]
+1

**Comment by tjuravich** [comment]
+1!

**Comment by detox3r** [comment]
+1

**Comment by joejulian** [comment]
Please don't spam comments. Use the :+1: icon on the description. Spamming comments makes it harder for me, a volunteer doing issue triage on my own time, to help out. Thanks!

@zfalen-deloitte Next time you see this issue, can you check `helm get hooks ...` and see if both tests are in there?

Additionally, if you set the `--debug` flag for the install and for tests when they're failing that might give you some hints as well.

**Comment by zfalen-deloitte** [comment]
@joejulian Will do this when I see it pop up again. In both cases - `install` and `test` - neither command actually, _fails_, it seems the test itself just doesn't ship with the installation. I will try `helm get hooks` and see if it shows up in that list.

**Comment by zfalen-deloitte** [comment]
@joejulian it took a lot of doing this time around but I managed to trigger this behavior again. Appears to be very intermittent and hard to replicate. 

In this case the release name _(pardon the horrible random name)_ was `ccpoctcng-scccccc-05c8259`. Command to install it from CI was
`helm install ccpoctcng-scccccc-05c8259 oci://ghcr.io/my-chart-path --values ./integration-values.yaml -n ccpoctcng-scccccc-05c8259-int-test --create-namespace`

Test tried with the following command/logs:
```
helm test ccpoctcng-scccccc-05c8259 --filter name=ccpoctcng-scccccc-05c8259-integration-test -n ccpoctcng-scccccc-05c8259-int-test

NAME: ccpoctcng-scccccc-05c8259
LAST DEPLOYED: Tue Feb 14 18:[3]

NAMESPACE: ccpoctcng-scccccc-05c8259-int-test
STATUS: deployed
REVISION: 1
TEST SUITE:     ccpoctcng-scccccc-05c8259-readiness-check
Last Started:   .....
Phase:          Succeeded
```

Note the lack of the `integration-test` as noted in the original post. CI failed with:
```
kubectl logs ccpoctcng-scccccc-05c8259-integration-test -n ccpoctcng-scccccc-05c8259-int-test > integration-test.log  

Error from server (NotFound): pods "ccpoctcng-scccccc-05c8259-integration-test" not found
Error: Process completed with exit code 1.
```

Here is the output from `helm get hooks ...`

```
helm get hooks ccpoctcng-scccccc-05c8259 -n ccpoctcng-scccccc-05c8259-int-test

---
# Source: my-chart/templates/tests/mychart-readiness.yaml
apiVersion: v1
kind: Pod
metadata:
  name: ccpoctcng-scccccc-05c8259-readiness-check
  labels:
    helm.sh/chart: my-chart-v1.3.80
    helm.sh/release: ccpoctcng-scccccc-05c8259

    mytag/object-type: test-container
  annotations:
    "helm.sh/hook": test
  namespace: ccpoctcng-scccccc-05c8259-int-test
spec:
  serviceAccountName: ccpoctcng-scccccc-05c8259-internal-kubectl
  containers:
    - name: kubectl
      image: alpine/k8s:1.23.16
      # GET ALL PODS THAT ARE NOT IN A RUNNING STATE, FAIL W/ERROR IF ANY ARE UNHEALTHY
      command: ["/bin/bash", "-c"]
      args:
        - echo "Checking Blueprint deployment for unhealthy containers....";
          UNHEALTHY_CONTAINERS=$(kubectl get pods -l mytag/object-type=service-container -o jsonpath='{.items[*].status.containerStatuses[*].state}' | jq 'keys[0]' | fgrep -vx "\"running\"");

          if [ ! -z "$UNHEALTHY_CONTAINERS" ]; then
            echo "At least one service container is not ready!";
            exit 1;
          else
            echo "All service containers are ready!";
            exit 0;
          fi

  restartPolicy: Never
  ```

Note that the ^ above does **_not_** show the `integration-test.yaml` file as part of the output. So it looks like it just ... didn't deploy!

**Comment by joejulian** [comment]
So the template isn't producing any output. Can you share the template for that test?

**Comment by zfalen-deloitte** [comment]
Sure. It's sort of obnoxious looking with a bunch of variables, but it's super basic.

```
{{- $serviceDefaults := dict -}}
{{- $serviceDefaults = $.Files.Get "service-defaults.yaml" | fromYaml -}}

{{- $integrationTestDefaults := get $serviceDefaults "integration-test" }}

{{- /* COMBINE OVERRIDES W/DEFAULT SETTINGS */ -}}
{{- $integrationTestOverrides := $.Values.myChart.integrationTest }}
{{- $integrationTestSettings := mergeOverwrite $integrationTestDefaults $integrationTestOverrides }}

{{- $adminIngressHostName := $.Values.myChart.ingress.admin.hostName | default $.Values.myChart.ingress.rootHostName -}}
{{- $userIngressHostName := $.Values.myChart.ingress.user.hostName | default $.Values.myChart.ingress.rootHostName }}

apiVersion: v1
kind: Pod
metadata:
  name: {{ $.Release.Name }}-integration-test
  labels:
    {{- include "myChart.selectorLabels" . | indent 4 }}
    myChart/object-type: test-container
  annotations:
    "helm.sh/hook": test
  namespace: {{ $.Release.Namespace }}
spec:
  imagePullSecrets:
    {{- range $.Values.myChart.imagePullSecret }}
    - name: {{ .name }}
    {{- end }}
  containers:
    - name: integration-test
      image: {{ $integrationTestSettings.IMAGE_TAG }}:{{ $integrationTestSettings.IMAGE_VERSION }}
      env:
        {{- if $.Values.myChart.ssl.enabled }}
        - name: ADMIN_API_ROOT
          value: https://{{ $adminIngressHostName }}
        - name: USER_API_ROOT
          value: https://{{ $userIngressHostName }}
        {{- else }}
        - name: ADMIN_API_ROOT
          value: http://{{ $adminIngressHostName }}
        - name: USER_API_ROOT
          value: http://{{ $userIngressHostName }}
        {{ end }}

  restartPolicy: Never
  ```
  
It's not keyed off of anything from `Values` in terms of conditional rendering, and the crazy thing is that when I subsequently run something like `helm upgrade some-release-name my-chart-repo -n some-ns --reuse-values`, it apparently "kicks the tires" enough that the test actually shows up in the release and functions correctly.

**Comment by joejulian** [comment]
Well that's just bizarre. Short of tracing helm or sharing the chart I'm stuck. The on again off again nature makes me want to blame a named template that exists in both parent and subchart, but that's just a theory from past experience. I'm not sure how that could prevent the processing of a template though.

Maybe something writing over $ or $.Template? $.Subcharts if this is a subchart?

**Comment by zfalen-deloitte** [comment]
Not a subchart. Just a fairly simple template at the top level of `/templates/tests` keying off of some things in `Values.yaml` - although we have some kinda funny things happening up top with `mergeOverwrite` etc.

Stumped here as well. It's not really _blocking_ on anything since we can make it redeploy and fix itself with a couple different methods. But it is strange.

I am loosely suspicious that it's something to do with having _multiple_ tests in that folder since `helm test` is a relatively obscure feature and things like `--filter` are still sort of evolving.

**Comment by joejulian** [comment]
Since we're all stumped, there's been no further activity for a while, and I (at least) cannot duplicate the problem, I'm going to go ahead and close this. It's at least slightly more personal than the bot doing it.

Feel free to reopen this if you think I can help further.
