### ISSUE TITLE
Getting MPL license issue in our blackduck code scan for Hashicorp for transitive dependency

### ISSUE THREAD

**Issue by mayankmike86** [helm/helm#11797]
Getting MPL license issue in our blackduck code scan for Hashicorp for transitive dependency.
We have imported helm/package/action to perform some helm action in our go code.
But our blackduck scanner is complaining about the hashicorp MPL license.
Is helm is using a purchased license from hashicorp ? If yes can you please help me with the license documentation which we can use to refer

**Comment by joejulian** [comment]
MPL is the [Mozilla Public License](https://www.mozilla.org/en-US/MPL/).

If you grep for "hashicorp" in go.mod, you can see that there's an indirect dependency on `github.com/hashicorp/golang-lru`

Then you can run this to see why it's linked:
```
$ go mod why github.com/hashicorp/golang-lru
# github.com/hashicorp/golang-lru
helm.sh/helm/v3/pkg/repo/repotest
github.com/distribution/distribution/v3/registry
github.com/distribution/distribution/v3/registry/handlers
github.com/distribution/distribution/v3/registry/storage/cache/memory
github.com/hashicorp/golang-lru
```

If the MPL is unacceptable for your use, I think you'd need to fork and remove the OCI capability (don't quote me on that though).
