### ISSUE TITLE
helm search repo regexp doesn't work as expected

### ISSUE THREAD

**Issue by Andrea-Gallicchio** [helm/helm#11798]
`regexp` seems to not work as expected; Indeed, if I run:

`helm search repo local-helm-repository/serviceabc`

It returns:

```
NAME                                     	CHART VERSION	APP VERSION	DESCRIPTION
local-helm-repository/serviceabc	0.2.5        	1.16.0     	A Helm chart for Kubernetes
```

But, if I use regexp as follow: 

`helm search repo local-helm-repository/serviceabc --regexp 'local-helm-repository/serviceabc'
`

It says `No results found`; Even if I run: 

`helm search repo local-helm-repository/serviceabc --regexp '\vlocal-helm-repository/serviceabc\v'
`

Output of `helm version`:
version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.19.4"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
EKS/Local Environment

**Comment by joejulian** [comment]
I cannot duplicate your results, even using the same helm version as you.

**Comment by Andrea-Gallicchio** [comment]
> I cannot duplicate your results, even using the same helm version as you.

So.. are you saying that my example works fine to you? that's really weird.

Unfortunately it doesn't to me, even if I use different regex like just `service` or `abc` or whatever.

**Comment by joejulian** [comment]
This seems to have been abandoned. Closing.
