### ISSUE TITLE
helm template uses wrong policy api version

### ISSUE THREAD

**Issue by camaeel** [helm/helm#11809]
I tried to template a helm chart with code:
```
{{- if .Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
```
With command: `helm template --repo https://kubernetes-sigs.github.io/aws-ebs-csi-driver --version 2.14.1 aws-ebs-csi-driver -s templates/poddisruptionbudget-controller.yaml`

It renders output with apiVersion: policy/v1beta1 instead of policy/v1 so looks like it doesn't know about policy/v1. It was mentioned in other ticket (https://github.com/helm/helm/issues/10760) that it should take version from kubectl library used in helm source code. This is v0.26.0 so should support policy/v1 (and maybe even shouldn't provide policy/v1beta1).

Output of `helm version`:
```
version.BuildInfo{Version:"v3.11.1", GitCommit:"293b50c65d4d56187cd4e2f390f0ada46b4c4737", GitTreeState:"clean", GoVersion:"go1.19.5"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.9", GitCommit:"9710807c82740b9799453677c977758becf0acbb", GitTreeState:"clean", BuildDate:"2022-12-08T10:15:09Z", GoVersion:"go1.18.9", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-25T19:38:29Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/arm64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
N/A

**Comment by VaibhavSharma-47** [comment]
I noticed that if we run it with a `--validate ` flag we will get `policy/v1`. 

In the helm documentation I see - 
```Any values that would normally be looked up or retrieved in-cluster will be faked locally. Additionally, none of the server-side testing of chart validity (e.g. whether an API is supported) is done.```

So I guess this is expected but I would let a core contributor confirm this.

**Comment by camaeel** [comment]
Yes, --validate runs with "real" cluster. But in my case I want to template helm chart earlier, and IMHO api versions are not calculated in expected way. 
So I'd like to know why is that, and what is the default set of APIs provided for templating.

**Comment by FeLvi-zzz** [comment]
> why is that, and what is the default set of APIs provided for templating.

`helm template` uses `chartutil.DefaultCapabilities`, it depends on `k8s.io/client-go` version.
https://github.com/helm/helm/blob/7c9d636f40e751c775cd1baea5ef2fd4f7139f6e/pkg/action/install.go#L244
https://github.com/helm/helm/blob/0a6d0b8be905db65be2452c3773243d3a12161cf/go.mod#L44

How to check the default set of APIs is as follows:
```
$ cat templates/foo.yaml
{{ range .Capabilities.APIVersions }}
# {{ . }}
{{- end }}

$ helm template foo .
---
# Source: foo/templates/foo.yaml
# v1
# admissionregistration.k8s.io/v1
# admissionregistration.k8s.io/v1alpha1
# admissionregistration.k8s.io/v1beta1
# internal.apiserver.k8s.io/v1alpha1
# apps/v1
# apps/v1beta1
# apps/v1beta2
# authentication.k8s.io/v1
# authentication.k8s.io/v1alpha1
# authentication.k8s.io/v1beta1
# authorization.k8s.io/v1
# authorization.k8s.io/v1beta1
# autoscaling/v1
# autoscaling/v2
# autoscaling/v2beta1
# autoscaling/v2beta2
# batch/v1
# batch/v1beta1
# certificates.k8s.io/v1
# certificates.k8s.io/v1beta1
# coordination.k8s.io/v1beta1
# coordination.k8s.io/v1
# discovery.k8s.io/v1
# discovery.k8s.io/v1beta1
# events.k8s.io/v1
# events.k8s.io/v1beta1
# extensions/v1beta1
# flowcontrol.apiserver.k8s.io/v1alpha1
# flowcontrol.apiserver.k8s.io/v1beta1
# flowcontrol.apiserver.k8s.io/v1beta2
# flowcontrol.apiserver.k8s.io/v1beta3
# networking.k8s.io/v1
# networking.k8s.io/v1alpha1
# networking.k8s.io/v1beta1
# node.k8s.io/v1
# node.k8s.io/v1alpha1
# node.k8s.io/v1beta1
# policy/v1
# policy/v1beta1
# rbac.authorization.k8s.io/v1
# rbac.authorization.k8s.io/v1beta1
# rbac.authorization.k8s.io/v1alpha1
# resource.k8s.io/v1alpha1
# scheduling.k8s.io/v1alpha1
# scheduling.k8s.io/v1beta1
# scheduling.k8s.io/v1
# storage.k8s.io/v1beta1
# storage.k8s.io/v1
# storage.k8s.io/v1alpha1
# apiextensions.k8s.io/v1beta1
# apiextensions.k8s.io/v1
```

Also, `helm template` has `--api-versions` flag.
```
$ diff -U0 <(helm template foo .) <(helm template foo . --api-versions policy/v1/PodDisruptionBudget)
--- /dev/fd/63  2023-04-15 22:54:48.355906600 +0900
+++ /dev/fd/62  2023-04-15 22:54:48.355906600 +0900
@@ -54,0 +55 @@
+# policy/v1/PodDisruptionBudget
```

**Comment by FeLvi-zzz** [comment]
On the other hand, `--api-versions` can ADD only, cannot remove API version from the default set.

related #10108

**Comment by rtarasov** [comment]
Hi Guys! I'm getting this wrong behaviour with helm 3.12.3 on AKS cluster 1.25.6:
`helm upgrade --install akv2k8s spv-charts/akv2k8s --namespace ugsvt-akv2k8s -f akv2k8s.yml
Error: UPGRADE FAILED: unable to build kubernetes objects from current release manifest: resource mapping not found for name: "akv2k8s-envinjector" namespace: "" from "": no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"`

the `kubectl api-resources` returns:
`poddisruptionbudgets                                                     pdb                      policy/v1                              true         PodDisruptionBudget`

Could you please advice?
