### ISSUE TITLE
build helm with go 1.20 (fix DNS on MacOS)

### ISSUE THREAD

**Issue by thesuperzapper** [helm/helm#11807]
Go `1.20` was [released on 2023-02-01](https://go.dev/doc/devel/release#go1.20), and I believe we should use this version in Helm.

While I know that is very recent release, version `1.20` of Go fixed a significant issue that is affecting Helm's ability to resolve DNS correctly on MacOS:
- https://github.com/golang/go/issues/12524

If we start building with Go 1.20, it is likely that the following issues will be resolved:
- https://github.com/helm/helm/issues/5800
- https://github.com/helm/helm/issues/10874
- https://github.com/helm/helm/issues/11306
- https://github.com/Homebrew/homebrew-core/issues/110500

**Comment by joejulian** [comment]
I'll just mark this as a support issue since the go upgrades are done as a matter of course anyway.

**Comment by thesuperzapper** [comment]
@joejulian do we have a timeline yet for upgrading the go version to 1.20?

**Comment by joejulian** [comment]
Isn't 3.12.0 built with 1.20?

**Comment by thesuperzapper** [comment]
@joejulian it looks like the release workflows have [hard-coded go `1.20`](https://github.com/helm/helm/blob/main/.github/workflows/release.yml#L26), but the actual [`go.mod` file is still showing `1.19`](https://github.com/helm/helm/blob/v3.12.0/go.mod#L3), which is fine, as long as we still want to support people building with go `1.19`.

**Comment by thesuperzapper** [comment]
In any case, this issue can now be closed as the issue is no longer present in helm 3.12.0.
