### ISSUE TITLE
Helm SSL Issue on connecting to Charts Repo

### ISSUE THREAD

**Issue by elangelo** [helm/helm#11808]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.11.1", GitCommit:"293b50c65d4d56187cd4e2f390f0ada46b4c4737", GitTreeState:"clean", GoVersion:"go1.18.10"}
```

Output of `kubectl version`:
```
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"archive", BuildDate:"2023-01-18T22:38:55Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
N/A

The actual problem:

```
$ helm repo add stable https://charts.helm.sh/stable
Error: looks like "https://charts.helm.sh/stable" is not a valid chart repository or cannot be reached: Get "https://charts.helm.sh/stable/index.yaml": dial tcp: lookup charts.helm.sh on [::1]:53: read udp [::1]:48747->[::1]:53: read: connection refused
```
I have the same issue with any repo i'm trying to add... bitnami, apache, prometheus... none of them work for me and they all fail with this error

**Comment by joejulian** [comment]
Works for me. Check with your dns/proxy administrator.

**Comment by elangelo** [comment]
Helm works for me on another computer as well... So maybe i should have phrased it a bit differently....
So the computer where helm is not working has, as far as i know, no problems with certificates, i can use curl, wget, whatever just fine... Only helm seems to complain about this certificate thing. I can't imagine that helm does not use the 'standard' ssl libraries on my system... but something is different than for instance curl...

**Comment by elangelo** [comment]
OK i was able to fix this.
https://wiki.archlinux.org/title/Systemd-resolved
Not sure why this only showed up with helm and no other programs whatsoever but they do mention in the notes:
> Failure to properly configure /etc/resolv.conf will result in broken DNS resolution.

I've basically activated the stub mode:
`ln -rsf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf`
