### ISSUE TITLE
Helm Template Does Not Preserve String Escaping of String Literals

### ISSUE THREAD

**Issue by mike-capyh** [helm/helm#11817]
Output of `helm version`:

`version.BuildInfo{Version:"v3.11.1", GitCommit:"293b50c65d4d56187cd4e2f390f0ada46b4c4737", GitTreeState:"clean", GoVersion:"go1.18.10"}`

Output of `kubectl version`:

```
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:58:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:51:45Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}

```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):   bare-metal/kubeadm

### Expected Behavior:

`helm template` outputs valid, re-parse-able `yaml` manifests even if an included values string-literal contains yaml special characters.  In other words, if values inputs are properly escaped, the output should also remain properly escaped.

### Actual Behavior:

`helm template` does not preserve escaping of values string literals with eg an exclamation mark, causing attempts to re-parse the output to treat the exclamation mark as a yaml tag marker instead of part of the string literal.

### Motivation / Use Case:

This can break downstream tooling that relies on `template` outputting valid re-parse-able yaml, eg `skaffold`'s helm-deploy.
See [this skaffold issue](https://github.com/GoogleContainerTools/skaffold/issues/8429).

## Simplified Repro (in compatible nix environment, eg Ubuntu 20.04.5 LTS):

```bash
REPRO=~/temp/helm-template-escape
mkdir $REPRO && pushd $REPRO
helm create test

echo 'testValue: "!anEscapedStringLiteral"'  >> test/values.yaml

cat > test/templates/config.yaml <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  test-value: {{ .Values.testValue }}
EOF

helm template test ./test | grep test-value

echo 'EXPECTED:  test-value: "!anEscapedStringLiteral"'
echo 'ACTUAL:    test-value: !anEscapedStringLiteral'
```

**Comment by joejulian** [comment]
That is indeed how yaml works. A quoted string is always interpreted as a string. Converting that data back to yaml will not include the quotes if they're not needed to make the data a string, ie.
```
message:
  - hello world is a string
  - "2.0"
  - 2.0 would not be a string because the reverse of that is a float
```

**Comment by mike-capyh** [comment]
Thank you for taking the time to look into this!

`A quoted string is always interpreted as a string. ` -> That was my understanding, and indeed how I would like `helm` to interpret inputs.

`Converting that data back to yaml will not include the quotes if they're not needed to make the data a string` -> Maybe this is where some of my confusion lies.  My understanding is that, in my example, the quotes _are_ needed to make the data a string.  That is, `!`, when not escaped, [has special meaning](https://yaml.org/spec/1.2.2/) (see 3.2.1.2. Tags) in `yaml`, and so it needs to be escaped when that special meaning is not desired.  In other words, when `helm template` strips those quotes, it changes the meaning of my input from a normal string literal to a special yaml construct.

Your float example is a much clearer demonstration than the tag marker, so let's borrow it.  Please try running the example repro again, but using:

 `echo 'testValue: "2.0"'  >> test/values.yaml`
 
What would you expect this to output?  On my system I get `  test-value: 2`.

To me, it appears that:
- the input was a string literal
- the output is no longer a string literal, it is now numeric
- thus, helm is effectively re-interpreting the input:  the output is valid yaml, but not the yaml we asked for.

Apologies in advance if I am missing something here, and thanks again for your time!

**Comment by joejulian** [comment]
Ah, I think I found it. Yes, indeed, it's a string in go. The go template will happily just place that string into the template and voila, you have an unquoted string. The trick is to convert it back to yaml:
```
test-value: {{ toYaml .Values.testValue }}
```

Which produces:
```
  test-value: '!anEscapedyaddayadda'
```

**Comment by mike-capyh** [comment]
Thanks!  I've confirmed that `toYaml` also works on my end.  

Now knowing what to look for, I checked some bigger public charts, and found:
- The `quote` function also works.
- This issue is alluded to, indirectly, [in the Helm docs](https://helm.sh/docs/chart_template_guide/functions_and_pipelines/).

I think for now that resolves my use cases, and we can probably close this issue.  A few follow-up questions come to mind, but I understand if they are out of scope:

1) To confirm:  helm's point of view is that it is not helm's responsibility, but the chart developer's responsibility, that through-values are actually guaranteed-through (ie, all string values intended to be passed-through as-is must go through `quote`, `toYaml`, etc. during template substitution)?
2) Is there a work-around for downstream users who do not control the chart templates (if the chart author did not use an escaping function)?
3) Is there a good place in the docs to make this issue (and the consequences) clearer to beginner helm chart authors?

**Comment by joejulian** [comment]
1: probably. Helm is a community so it's not like just one person is laying down the law though. Changes to something like this would need to go through the Helm Improvement Proposal ([HIP](https://github.com/helm/community/blob/main/hips/hip-0001.md)) process.
2. You might be able to nest quotes in such a way that they end up in the final output.
3. Nothing specific comes to mind. Maybe the go-template docs might be a good thing to understand though. If you find anything specific that you wish to contribute for documentation, please file a PR in [helm-www](https://github.com/helm/helm-www)

closing this as suggested
