### ISSUE TITLE
Helm test --logs to optionally output only from failed tests

### ISSUE THREAD

**Issue by Illidanek** [helm/helm#11819]
It would be great if aside from [respecting --filter when using the --logs flag](https://github.com/helm/helm/issues/10566) we were also able to specify that `helm test --logs` outputs only logs from failed tests.

An example use-case is for CI/CD pipelines, so that logs are output only if there is an error, for investigation, whereas successful tests simply yield some short success message and exit.

This is especially useful for cases where we want to delete the test pod after execution so as to not take up space on the cluster, especially since investigating test failures can take place a while after the test execution. Furthermore, looking at test job results is faster and more convenient than searching through Pod logs.

### Suggested solution 1 - an additional 'logs-failed' flag

`helm test mychart --logs-failed`

### Suggested solution 2 - parameters for the existing 'logs' flag

`helm test mychart --logs all` (default)
`helm test mychart --logs failed`
`helm test mychart --logs succeeded`

**Comment by joejulian** [comment]
Oh yes, please! Is this something you can open a PR for?

**Comment by rhzx3519** [comment]
@joejulian Hi, I built a PR just for this issue. Please review the code.
