### ISSUE TITLE
Multiple Schema Validators for various value YAMLs

### ISSUE THREAD

**Issue by jl-beast** [helm/helm#11815]
Output of `helm version`:
```version.BuildInfo{Version:"v3.10.0", GitCommit:"ce66412a723e4d89555dc67217607c6579ffcb21", GitTreeState:"clean", GoVersion:"go1.18.6"}```
Output of `kubectl version`:
```Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:22:29Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"windows/amd64"}```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): DIY

A Helm Chart can have multiple value files, which can be specified with the '-f' option when installing. Some feature sets may have variables in one values file that are not defined in another or require different validation rules, such as different regex validation or requirements.

However, there is currently no way to specify linting rules for a specific value file. The only linting mechanism available is the values.schema.json, which provides global linting options for all value files during installation. This can cause problems when trying to maintain a consistent format for '-f' install overrides.

To address this issue, I would appreciate having something like a corresponding *.schema.json file for each values *.yaml file. This would enable efficient linting through name-matching, ensuring the consistency and maintainability of alternative value files during testing.

An alternative would be allowing .YAML files to specify which Linter they would use. But I think that forces information to be read from the .YAML file, which is probably more work and less effective.

Please let me know, if you need a more specific use case example or any other information.

**Comment by joejulian** [comment]
There is only one default values file and all potential values should be documented there https://helm.sh/docs/chart_best_practices/values/.
The schema file is used to document which keys are possible to define and how those keys can be used. That doesn't change from one implementation of the values to the next. After all, your chart's templates can only make use of the keys it makes use of. That potential of use isn't going to change and that potential is what's documented in the schema.

**Comment by jl-beast** [comment]
Could there at least be support with Helm Lint to have you be able to pass in an alternative schema file for it to lint against? This could help with testing new linters or for building up a manual system for running and testing?

**Comment by joejulian** [comment]
If that's something you think you'd like to contribute it could certainly be worth writing up a [hip](https://github.com/helm/community/blob/main/hips/hip-0001.md) about.

Currently, there's no way to do that (short of renaming files).
