### ISSUE TITLE
Resource gets removed on upgrade when labels are not matching

### ISSUE THREAD

**Issue by Aeternax** [helm/helm#11811]
Hi there,

I've moved a dependency-chart from one chart to another separate chart to make future releases simpler.
This has led to an unfortunate situation as follows:
- main release dependency on a redis chart v 17.3.7.
- New release created for the redis chart dependency v17.3.7.

In terraform it's listed as a dependency, so it will install the dependency release first and sees all resources exist with the same data.
Then upgrades the main release (which ends up wanting to remove the dependency-resource).
This then caused the installation to fail on "pending-upgrade".

Worked around this by re-installing the dependency release.
Then I upgraded the redis chart version to **v17.7.3**.

### Expectation:
New release installs component with newer version.
main release wants to uninstall the old version of redis but can't find it any longer.

### Reality:
main release removes the redis resources on upgrade.

I understand that helm should check all 4 labels and they should match for it to act on those resources.
`app.kubernetes.io/managed-by: {{ .Release.Service | quote }}`
`app.kubernetes.io/instance: {{ .Release.Name | quote }}`
`app.kubernetes.io/version: {{ .Chart.AppVersion }}`
`helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"`

But seemingly the chart version is not compared on upgrade (Removal).

helm version: helm 3.8.1 x64
Azure Kubernetes Service.

**Comment by joejulian** [comment]
A helm release stores the manifest of that release in a secret like `sh.helm.release.v1.myrelease.v1`. When a helm chart is deleted, it deletes the resources in that manifest from the cluster, regardless of how they're labeled in the cluster with one exception. If the resources are labeled with `helm.sh/resource-policy: keep` prior to installation, those resources will not be deleted.

The matching labels you reference are used for adopting resources already in the cluster, but are not checked on deletion.

**Comment by joejulian** [comment]
This seems to have answered the issue. Closing.
