### ISSUE TITLE
How to perform lookup in parent chart when object is created from subchart?

### ISSUE THREAD

**Issue by keshavprasadms** [helm/helm#11810]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.11.0", GitCommit:"472c5736ab01133de504a826bd9ee12cbe4e7904", GitTreeState:"clean", GoVersion:"go1.19.5"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:51:24Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:27:13Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  **Minikube**

Hello Community,

I am creating an umbrella chart our application which can install all the components in one go. The umbrella chart looks like this (simplified version)
```
parent-chart
├── Chart.yaml
├── charts
│   ├── subchart1
│   │   ├── Chart.yaml
│   │   ├── templates
│   │   │   └── configmap.yaml
│   │   └── values.yaml
│   └── subchart2
│       ├── Chart.yaml
│       ├── templates
│       │   └── configmap.yaml
│       └── values.yaml
├── templates
│   └── configmap.yaml
└── values.yaml
```

In `subchart1`, I am creating a kubernetes secret. I am reading this secret in my `parent-chart` using `lookup` function of helm. 

This works fine if I install the `subchart1` first and then the parent chart as independent charts (secret object will be created by the `subchart1`).

The secret value created by the `subchart1` is dynamic. I cannot control / set these values.

My requirement is that the subcharts should to be installed first and then the parent chart. Is this possible with an umbrella chart?

I am also open to suggestions if I need to change my approach. Please provide your thoughts.

**Comment by joejulian** [comment]
The short answer is that you can't use lookup for this. There's nothing to look up during the templating phase. You can, however, exercise the template of the subchart configmap (in your example above).

```
{{ $subchart1Configmap := fromYaml (include (
    print 
        .Subcharts.subchart1.Template.BasePath
        "/configmap.yaml"
    )
    .Subcharts.subchart1
)}}
```
Then you can just parse `$subchart1Configmap` for whatever's in the CM that you need.

**Comment by keshavprasadms** [comment]
Thanks a ton @joejulian 🦸🏻 . Your suggestion works very well for my use case and I am able get this working.

**Comment by kuwv** [comment]
@joejulian IME this is causing a new secret to be generated and isn't an actual solution to this problem.
