### ISSUE TITLE
Not able to pull using Helm GO SDK

### ISSUE THREAD

**Issue by alishah730** [helm/helm#11813]
Output of `helm version`: `version.BuildInfo{Version:"v3.11.0", GitCommit:"472c5736ab01133de504a826bd9ee12cbe4e7904", GitTreeState:"clean", GoVersion:"go1.19.5"}`

Output of `kubectl version`: `Client Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.9-dispatcher-dirty", GitCommit:"2c922a0aeb84a19590ed91f00449636b87bb507a", GitTreeState:"dirty", BuildDate:"2023-01-11T06:21:51Z", GoVersion:"go1.18.9", Compiler:"gc", Platform:"darwin/arm64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  Mininkube, on-premise, trying to implement pull via Go helm SDK
 

while pulling like below its working as expected 

```helm pull https://charts.bitnami.com/bitnami/redis-17.7.3.tgz```

OR

```
helm repo add bitnami https://charts.bitnami.com/bitnami
helm pull bitnami/redis --version 17.7.3
```

while trying to use Go SDK  https://pkg.go.dev/helm.sh/helm/v3@v3.11.1/pkg/registry with the below sample code

```
package main

import (
	"fmt"
	"log"
	"bytes"

	"helm.sh/helm/v3/pkg/registry"
)

func main() {
	var out bytes.Buffer

	client,err := registry.NewClient(registry.ClientOptDebug(true),
	registry.ClientOptEnableCache(true),
	registry.ClientOptWriter(&out),)
	if err != nil {
		log.Fatal(err)
	}
	
	

	pulledChart,err :=client.Pull("https://charts.bitnami.com/bitnami/redis:17.7.3")
	if err!= nil {
        log.Fatal(err)
    }

	fmt.Println("Chart has been downloaded to:", pulledChart.Manifest)

}
````

getting error : 

```
2023/02/12 12:19:53 invalid_reference: invalid repository
exit status 1
```

is this bug or I'm doing something wrong?

**Comment by joejulian** [comment]
The `registry` client is for OCI registries. I think you're looking for the action client: https://github.com/helm/helm/blob/46103aa1df0388d07444f25e0688ffe946812ebe/cmd/helm/pull.go#L46

**Comment by joejulian** [comment]
This seems to be solved. Closing.
