### ISSUE TITLE
Feature Request: Finer-grained --debug

### ISSUE THREAD

**Issue by andrewm-aero** [helm/helm#11827]
The `--debug` flag to `helm upgrade --wait` is too coarsely-grained.

I like the fact that it shows "progress" events, unfinished jobs, unready deployments, unbound PVCs, etc, this is useful.

I don't like the fact that it then vomits the entire rendered YAML to the terminal, which, for charts of any meaningful size, tends to push the rest of the terminal history off the buffer. This is not useful. If I wanted that, `helm template` does exactly the same thing.

As far as I can tell, there is no way to have the former without the latter. I would appreciate a flag that can accomplish this.

**Comment by joejulian** [comment]
Seems like you could even just add that as an optional argument to the debug flag. Good idea. Is this something you're wanting to contribute?

**Comment by andrewm-aero** [comment]
Ideally, Helm would use a numeric verbosity level, in the same way that Kubernetes components do with klog (including go-client and kubectl), or that the controller-runtime does with go-logr, in place of semantic levels like "info" and "debug" (If you're not acquainted with this school of thought, https://dave.cheney.net/2015/11/05/lets-talk-about-logging is a good introduction), which seems like a much bigger change. I suppose I could do a band-aid fix, if that idea is a non-starter.

**Comment by alok1929** [comment]
Hey could you tell me how I would get started with this issue ? 

Any sort of links and how I would be able to reproduce this issue locally would be of great help.

**Comment by joejulian** [comment]
On second thought, this is not a good first issue. The uses the standard go log library which does not support anything about debug levels. Redoing logging would probably involve replacing the logger with klog and that's not only not easy but would change the output enough that anybody that's built tooling around scraping it would be broken. I can't think of a way to satisfy this feature without some major work.

Considering how little time the core maintainers have, unless someone is willing to contribute this in a backward compatible way, it's not going to happen in v3.

**Comment by rhzx3519** [comment]
`--debug` is a global flag for all commands, do we need to consider the impact to all commands if we add some arguments for `--debug`?

**Comment by sashamor** [comment]
For anyone still experiencing this issue -- this is a `sed` command that deletes everything from `USER-SUPPLIED VALUES:` down:

```bash
helm install --debug ... | sed '/USER-SUPPLIED VALUES:/,$d'
```

We now use this in our deploys, so we can debug when a deploy fails, but not print any secrets/configuration that may reveal sensitive data.
