### ISSUE TITLE
ValidationError(Deployment.spec.template.spec.nodeSelector)

### ISSUE THREAD

**Issue by efcunha** [helm/helm#11837]
Output of `helm version`: 3

Output of `kubectl version`: 1.25.2

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  EKS

Hello I have the following error in the helm chart

I created a file with the variables > values.yaml

nodeSelector: homologacao

In the deployment.yaml file

{{- if .Values.nodeSelector }}
  nodeSelector: {{ .Values.nodeSelector }}
{{-end }}

But I am getting the following error:
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.nodeSelector): invalid type for io.k8s.api.core.v1.PodSpec.nodeSelector: got "string", expected "map"

**Comment by joejulian** [comment]
Oops, this one slipped through the cracks.

Probably a bit late but it says right there what you need to do. Replace the string value with a map:
```
nodeSelector:
   node-type: pineapple
```

see: https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes/#create-a-pod-that-gets-scheduled-to-your-chosen-node
