### ISSUE TITLE
Helm command that sets release status

### ISSUE THREAD

**Issue by Nick-Triller** [helm/helm#11830]
Hi helm maintainers!

I would like to propose a helm subcommand that can be used to update the status of the latest revision of a release.

Such a command is useful when a helm release is stuck in `pending-upgrade` (or any other) status. The most common cause is that the helm process was killed in the middle of an operation. Attempting `helm upgrade` in this state results in the following error:
```
Error: UPGRADE FAILED: another operation (install/upgrade/rollback) is in progress
```
Setting the release status to `deployed` allows running `helm upgrade` again. I have a script that does exactly this, but it would be convenient to be able to do it with helm cli. Furthermore, this exact situation generates regular support requests that could be resolved with this command in the future. Some users even resort to reinstalling the helm release, accepting downtime in the process (e.g. https://github.com/helm/helm/issues/11565).

It could be implemented as a "ignore status" flag on upgrade / rollback commands as well, but I imagine that would tempt users to set the flag by default in CI environments which is dangerous.

I would be happy to implement the proposed functionality if the helm project is inclined to accept such a contribution!

**Comment by Nick-Triller** [comment]
I just came across the helm plugin https://github.com/k3s-io/helm-set-status which claims to do exactly what I am proposing to implement in helm cli itself.

**Comment by yxxhero** [comment]
@Nick-Triller I think that you can try to use https://github.com/k3s-io/helm-set-status. but please notice that `This plugin alters the internal state of helm releases. Use with care!`.

**Comment by joejulian** [comment]
Glad to see you found a solution. Closing this issue then.

**Comment by Nick-Triller** [comment]
Hi @joejulian,

We already had a solution when I created the issue (our own script that works like helm-set-status plugin). My intention was to propose implementing a command such as helm-set-status in helm cli itself because so many helm users run into this problem at some point.
