### ISSUE TITLE
go.mod specifies 1.17 but should be 1.18

### ISSUE THREAD

**Issue by scottrigby** [helm/helm#11838]
### Problem

It appears there was a regression from #10912, resulting in a mismatch between the go versions in go.mod and the circle tests, here:
https://github.com/helm/helm/blob/017785a2f1104eb4299f8d31feb550c213350f13/go.mod#L3

## What happened

Changing go version 1.18 to 1.17 was introduced in this commit https://github.com/helm/helm/pull/10912/commits/ffa19a4b5d836283a91a4c16f8b81e734a973afc (see it [inline here](https://github.com/helm/helm/pull/10912/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6)).

There was a reason though. Note the commit comment:
> fix circleci tests

Luckily, we are now finishing migrating CircleCI to GitHub Actions, in this PR https://github.com/helm/helm/pull/11676. We could revert go.mod back to 1.18 in that PR, but it would be scope creep for the Circle migration task. So I'm making this follow-up issue to address this separately.

## Proposed fix

- [ ] Revert go.mod back to `1.18`
- [ ] Once we fix this, use the `go-version-file` option in GitHub Actions, per this thread https://github.com/helm/helm/pull/11676#discussion_r1110590602. It was using this parameter that led us to find this mismatch, so it's a good idea to use it once we can.

**Comment by nikzayn** [comment]
@scottrigby I am taking this up. I will once test the code as per mentioned in the proposed fix sections. Do let me know what other things I need to take care of!!

/assign

**Comment by wujunwei** [comment]
I found it last month , but nobody answers me :( https://github.com/helm/helm/issues/11106#issuecomment-1381439168

**Comment by joejulian** [comment]
This is on purpose and fill be fixed by the PR whose comment explains this requirement.

https://github.com/helm/helm/pull/11676#discussion_r1112595497
