### ISSUE TITLE
Helm docs template function list missing new `sprig` functions

### ISSUE THREAD

**Issue by mjnagel** [helm/helm#11841]
Docs in question: https://helm.sh/docs/chart_template_guide/function_list/

These docs seem to be out of date with all available functionality in Helm. In particular there are a number of `sprig` functions that show in [sprig docs](https://masterminds.github.io/sprig/) but do not have corresponding documentation on the Helm side (`dig` and a number of the string manipulation functions are some of the ones I noticed).

Do these docs simply need a refresh, maybe they referenced all possibilities in a previous sprig version? Or alternatively was the intent always to limit this to "common functions" and the lack of `dig` is expected? This might also be a broader conversation about maintaining a "duplication" of the sprig docs and whether there's value there or if this would be better suited by linking to sprig docs.

**Comment by joejulian** [comment]
Please file docs issues in [helm-www](https://github.com/helm/helm-www/issues). I'd move it but I don't have permissions.

**Comment by hickeyma** [comment]
Duplicate of https://github.com/helm/helm-www/issues/1422
