### ISSUE TITLE
Upgrade deployment with reuse-values

### ISSUE THREAD

**Issue by micgruber** [helm/helm#11844]
If we try to upgrade the service via 

helm upgrade -n service service . --reuse-values --set service.replicaCount=1 --wait

all the pods can't get recreated. The pods will remain in the state Back-off restarting failed container. After that I have to do a rollback and everything works fine after that. Is there something I missed when using --reuse-values. I also tried:

helm get values service -n service  > values.yaml -a; `
helm upgrade service  -n service . -f values.yaml --set service .replicaCount=1

But I experienced the same issue.

Output of `helm version`:
3.11.1

Output of `kubectl version`:
Client Version: v1.25.2
Kustomize Version: v4.5.7
Server Version: v1.24.9

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Aks

**Comment by micgruber** [comment]
Hi,

I found out what is creating the issue. The problem is that I deploy the Variable initialy with the HelmDeploy@0 and the overrideValues Property, which uses internaly the --set Option. Initaly the value is set correctly to 1000000. But after executing the upgrade it tries to use the value: 1e+06.

I found the issue https://github.com/helm/helm/pull/3599. Thus, we have to change how the variables get set. Instead of --set we should use --set-string. So, I think you can close the ticket.

**Comment by joejulian** [comment]
Thanks!
