### ISSUE TITLE
Helm upgrade fails because of wrong ownership without running the hooks pre-install/pre-upgrade 

### ISSUE THREAD

**Issue by mcbenjemaa** [helm/helm#11857]
## Summary
I included a new hook that will change ownership for certain resource to helm, 
once, I Upgraded the release, it turns out **Helm verify ownership of the rendered resources**  before even the hook gets executed?

If this is intended ? 

I really would love to have a hook that runs before helm ownership verification. 

Output of `helm version`: v3.11.1

Output of `kubectl version`: v1.23.16

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  CAPI, CAPG, CAPA

**Comment by joejulian** [comment]
Yes, the adoption/conflicting resource code:
https://github.com/helm/helm/blob/bb463b4c27c5b27b82e7a4f9dd5263446aaac66a/pkg/action/install.go#L295-L300

happens before the install:
https://github.com/helm/helm/blob/bb463b4c27c5b27b82e7a4f9dd5263446aaac66a/pkg/action/install.go#L352

which is where the pre-install hooks are applied:
https://github.com/helm/helm/blob/bb463b4c27c5b27b82e7a4f9dd5263446aaac66a/pkg/action/install.go#L361-L367

**Comment by mcbenjemaa** [comment]
Can we add a hook before this verification ?
I want to add a job that actually change the ownership

**Comment by joejulian** [comment]
There are no hooks that happen before this verification, no. Perhaps you could write a plugin that could do that?

**Comment by mcbenjemaa** [comment]
I would prefer something in helm client as we have an operator that relies on it for deployments.

**Comment by joejulian** [comment]
Maybe make two charts, then. One with only hooks that change ownership, and one that is the actual chart.

If you want to propose adding an entirely different layer of hooks, that would require someone willing to contribute and maintain the new code. It would start with creating a [Helm Improvement Proposal](https://github.com/helm/community/blob/main/hips/hip-0001.md).

**Comment by joejulian** [comment]
Since a workaround is possible and there's been no further activity on this, I'm going to go ahead and close it.
