### ISSUE TITLE
wait: consider respecting also `READY` container count

### ISSUE THREAD

**Issue by Dentrax** [helm/helm#11867]
Currently `--wait` flag only awaits `Status == Running` condition to be `true`. But in some cases, this still evaluates to `true` even no ready containers are there. For example,

```
NAME                  READY   STATUS    RESTARTS       AGE
foo-7d6d8499f5-4hjz9  0/1     Running   0              1m
```

Helm `--wait` does not respect the `READY`. I think the correct condition would be `STATUS == Running` and `all containers is ready == 1/1`.

Output of `helm version`: `v3.11.1`

Output of `kubectl version`: `v1.23.7`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): `-`

**Comment by joejulian** [comment]
Actually helm does wait for ready:

https://github.com/helm/helm/blob/e007c900ce5f2233c8583565d5ba1b0433b1a213/pkg/kube/ready.go#L274-L281

What you're probably seeing is the maxUnavailable being met.

**Comment by joejulian** [comment]
Since I answered this and there's been no further questions, I'm going to go ahead and close this.
