### ISSUE TITLE
Debug helm look up for secret.yml

### ISSUE THREAD

**Issue by neethucleetus** [helm/helm#11868]
`helm version`: 3

I have a secret.yml file , and run helm install test5 ./ -n mynamespace. When opened in k8 dashboard secret, i am able to see the secret value.

below code is from deployment.yml file

```
{{- $secret := default (dict "data" (dict)) (lookup "v1" "Secret" "" "mysecrets") }}
{{- if $secret.data.redispassword }}
  {{- $redisPassword := $secret.data.redispassword | b64dec }}
{{- end }}
```
When installs, above condition is not met, since it says $secret itself is nill.

Below code works,

```
valueFrom:
secretKeyRef:
name: mysecrets
key: redispassword
```
I need to get password in template for multiple condition purpose

helm dry-run prints the secrct.yml file and value is present. The issue is with lookup, How to print all value of a screct.yml to debug. Something like covert dictionary object to string.

Thank you for your consideration, help and time.

Repo link - https://github.com/DevSecOpsTut/helm-test

**Comment by joejulian** [comment]
try:

```
{{- $secret := default (dict "data" (dict)) (lookup "v1" "Secret" .Release.Namespace "mysecrets") }}
{{- if $secret.data.redispassword }}
  {{- $redisPassword := $secret.data.redispassword | b64dec }}
{{- end }}
```

**Comment by neethucleetus** [comment]
@joejulian thank you for your time and help, I had tested your suggestion earlier.
Below is the secrets created as part of helm install
[Imgur](https://imgur.com/DbeqC3L)

Secret.yaml file

```
apiVersion: v1
kind: Secret
metadata:
  name: mysecrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  password: abcd=
  redisHost: 
  jwtsecret: ""
  redispassword: abcd==
```

deployment.yaml
Below is the logical template
```
{{- $redisPassword := printf "" }}
{{- $secret := default (dict "data" (dict)) (lookup "v1" "Secret" .Release.Namespace "mysecrets") }}
{{- if $secret.data.redispassword }}
  {{- $redisPassword := $secret.data.redispassword | b64dec }}
{{- end }}
{{- $redisHosts := printf "%v:%v:%v" .Values.redis.host .Values.redis.port "us-east" -}}
{{- if $redisPassword -}}
  {{- $redisHosts = printf "%v:%v" $redisHosts $redisPassword -}}
{{- end -}}
```
1. with heml template or debug dry-run above template cannot be test.
2. Lookup is returning nil
3. If a sample helm repo with a redis and nodejs where we can pass redis host as env value . I am trying modify mine and push it
4. As part of heml install order, Is secrect installed first, the values and then deployment happens, Am i right.

Much appricate if you could guide me

**Comment by abelkbil** [comment]
@neethucleetus - My guess you need K8 version 1.18 or above . Documentation is not mentioned. Could you comment @adamreese . Thanks

**Comment by joejulian** [comment]
@abelkbil No, it's the shadow assignment. He creates $redisPassword outside the if block and is hoping that the command inside the if block will replace the value, but by using `:=` it creates a new $redisPassword variable that's scoped to the life of the if block. When it exits the if block, the original $redisPassword which hasn't been altered is used.

To accomplish what he's trying to accomplish, he needs to use `=` to avoid creating a new variable that's only scoped to the if block.
