### ISSUE TITLE
feature: in-built `schema` generator

### ISSUE THREAD

**Issue by zhekazuev** [helm/helm#11869]
**Why**

I and community(e.g. [teleport](https://goteleport.com/) - link to [charts](https://charts.releases.teleport.dev/)) use `json-schemas` quite often to validate values.

I have to do it in a way that's not quite native, and invent a bicycle:
- https://objectpartners.com/2021/01/21/why-we-started-using-json-schema-in-our-internal-helm-charts/
- https://www.arthurkoziel.com/validate-helm-chart-values-with-json-schemas/

As far as I know, there are already recommended ways to do this using golang: https://json-schema.org/implementations.html#schema-generators .

Is it possible to integrate [the json-schema generator](https://github.com/invopop/jsonschema) directly into the helm binary(e.g. like a `go-templates` by `Masterminds/sprig`)?

**What**

To make it work like this:
```bash
helm schema ....
```

**How**

Source code of generator: https://github.com/invopop/jsonschema
Helm plugin(old and not maintained): https://github.com/karuppiah7890/helm-schema-gen

**Related**

* [Note: Fisher: https://github.com/karuppiah7890/helm-schema-gen - this plugin is not currently maintained, but this discussion happened before](https://github.com/helm/community/blob/bc4e17caceabc6553c01a783b33e97ac2835e797/meeting-notes/2021.txt#L838)
* [helm/helm-www: Related Projects and Documentation - helm-schema-gen](https://github.com/helm/helm-www/blob/f2accdf9f063ef47f589a9613902220cc2667ab3/content/en/docs/community/related.md?plain=1#L35)

**Comment by joejulian** [comment]
If you'd be interested in contributing such a feature, please read the [contributing guidelines](https://github.com/helm/helm/blob/main/CONTRIBUTING.md). This feature would also need to start with a [helm improvement proposal](https://github.com/helm/community/blob/main/hips/hip-0001.md).
