### ISSUE TITLE
Helm repo update returns 0 (success) on failure

### ISSUE THREAD

**Issue by cebe** [helm/helm#11907]
Running `helm repo update` returns a successful code (0) on network timeout.

It should return non-zero, e.g. 1 instead.

![image](https://user-images.githubusercontent.com/189796/224892755-b58def3c-0f99-45fe-8d97-69d41f82d57d.png)

Output of `helm version`:

```
$ helm version
version.BuildInfo{Version:"v3.11.2", GitCommit:"912ebc1cd10d38d340f048efaf0abda047c3468e", GitTreeState:"clean", GoVersion:"go1.18.10"}
```

Output of `kubectl version`:

```
kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.26.2
Kustomize Version: v4.5.7
Server Version: v1.26.1
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

digital ocean, but not relevant in this case as far as I see.

**Comment by kenichi-kocha** [comment]
From `helm rep update --help` and my verification, the `--fail-on-repo-update-fail` flag may solve your issue.

Output of `helm rep update --help`:
![helm_repo_update_help](https://user-images.githubusercontent.com/64531971/224918353-c816e791-7f23-48a9-bc72-c595e89a3b7a.PNG)

The result of my verification:
![with_fail-on-repo-update-fail](https://user-images.githubusercontent.com/64531971/224920167-5f25403e-5896-4f21-ac27-dadf439e79bb.PNG)

**Comment by cebe** [comment]
@kenichi-kocha Thanks for checking, that would work indeed. Why is this not the default behavior?

**Comment by kenichi-kocha** [comment]
I'm sorry that I don't know the reason, because this is my first time participating in helm community.
But according to the comment of the flag, it seems that it has been discussed at the following issue.

https://github.com/helm/helm/issues/10016

The comment:
![comment_fail-on-repo-update-fail](https://user-images.githubusercontent.com/64531971/224924189-76efc7f7-2a0d-4778-915a-93e4f2a1d777.PNG)

**Comment by cebe** [comment]
Thanks for finding that! So this issue is a duplicate, closing it.
