### ISSUE TITLE
delete resources not in use when upgrade

### ISSUE THREAD

**Issue by yuntianfeijing** [helm/helm#11906]
During deployment, a function is enabled and some resources are created, then I want to disable it, the resources  not delete
eg: 
1、enable ingress at a chart install
2、the ingress resource will be create
3、upgrade the release set ingress  disable
the ingress  still exist
Output of `helm version`:

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by yuntianfeijing** [comment]
![image](https://user-images.githubusercontent.com/42763234/224888867-6e395f63-3cba-4fce-b43b-c21b84a6d5d3.png)

**Comment by joejulian** [comment]
The resources that were in a one helm release (call it v1) that are not in the target list of resources for the helm release upgrade (v2) will be deleted here: [helm/pkg/kube/client.go:459](https://github.com/helm/helm/blob/d27d1bde4ca6f2650388ba8f5fd94911166dc13c/pkg/kube/client.go#L459).

If that's not happening in your chart, perhaps you have the annotation `"helm.sh/resource-policy": keep`
