### ISSUE TITLE
Helm repo is unable to create 

### ISSUE THREAD

**Issue by Kiran-38** [helm/helm#11904]
Output of `helm version`: version.BuildInfo{Version:"v3.6.2+5.el8", GitCommit:"eb607dd4f123eaedab662cef21008d177f2c3426", GitTreeState:"clean", GoVersion:"go1.15.13"}

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"b05f7d40f9a2dac30771be620e9e9148d26ffd07", GitTreeState:"clean", BuildDate:"2023-02-06T19:26:01Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4+a34b9e9", GitCommit:"b6d1f054747e9886f61dd85316deac3415e2726f", GitTreeState:"clean", BuildDate:"2023-01-10T15:55:28Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Redhat

**Issue**: 
MINGW64 $ helm repo add test-chartmuseum https://chartmuseum/..net --debug
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/admin/clusterconfigs/auth/kubeconfig Error: looks like "https://chartmuseum/..net" is not a valid chart repository or cannot be reached: Get "https://chartmuseum/..net/index.yaml": EOF helm.go:81: [debug] Get "https://chartmuseum/..net/index.yaml": EOF looks like "https://chartmuseum/..net" is not a valid chart repository or cannot be reachedmain.(*repoAddOptions).run        /builddir/build/BUILD/src/helm.sh/helm/cmd/helm/repo_add.go:187main.newRepoAddCmd.func1        /builddir/build/BUILD/src/helm.sh/helm/cmd/helm/repo_add.go:81github.com/spf13/cobra.(*Command).execute        /builddir/build/BUILD/src/helm.sh/helm/vendor/github.com/spf13/cobra/command.go:852github.com/spf13/cobra.(*Command).ExecuteC        /builddir/build/BUILD/src/helm.sh/helm/vendor/github.com/spf13/cobra/command.go:960github.com/spf13/cobra.(*Command).Execute        /builddir/build/BUILD/src/helm.sh/helm/vendor/github.com/spf13/cobra/command.go:897main.main        /builddir/build/BUILD/src/helm.sh/helm/cmd/helm/helm.go:80runtime.main        /usr/lib/golang/src/runtime/proc.go:204runtime.goexit        /usr/lib/golang/src/runtime/asm_amd64.s:1374

Able to ping the chartmuseum..net but still the problem persist. please do help in this regard.

Thanks
Kiran M

@Kiran-38

**Comment by yxxhero** [comment]
https://chartmuseum/..net?  please ensure the address.

**Comment by Kiran-38** [comment]
Hi @yxxhero, https://chartmuseum.apps.slab748cluster.tre.nsn-rdnet.net for security reason I have not given domain the actual url.

**Comment by yxxhero** [comment]
@Kiran-38 could you show the result of the following cmd:
`curl https://chartmuseum.apps.slab748cluster.tre.nsn-rdnet.net/index.yaml`

**Comment by Kiran-38** [comment]
curl: (52) Empty reply from server

**Comment by yxxhero** [comment]
@Kiran-38 please check the sever of https://chartmuseum.apps.slab748cluster.tre.nsn-rdnet.net.

**Comment by Kiran-38** [comment]
[empty reply](curl: (52) Empty reply from server)

PING chartmuseum.apps.slab748cluster.tre.nsn-rdnet.net(2a00:8a00:4000:20c::2:8fa (2a00:8a00:4000:20c::2:8fa)) 56 data bytes
64 bytes from 2a00:8a00:4000:20c::2:8fa (2a00:8a00:4000:20c::2:8fa): icmp_seq=1 ttl=64 time=1.22 ms
64 bytes from 2a00:8a00:4000:20c::2:8fa (2a00:8a00:4000:20c::2:8fa): icmp_seq=2 ttl=64 time=0.253 ms
64 bytes from 2a00:8a00:4000:20c::2:8fa (2a00:8a00:4000:20c::2:8fa): icmp_seq=3 ttl=64 time=0.254 ms
64 bytes from 2a00:8a00:4000:20c::2:8fa (2a00:8a00:4000:20c::2:8fa): icmp_seq=4 ttl=64 time=0.161 ms

**Comment by yxxhero** [comment]
@Kiran-38 I think that is not an issue of the helm.

**Comment by joejulian** [comment]
Usually when I see this it's because you're behind a proxy and you're being redirected.

Either way, an empty reply from the server validates helm's response that it's not a valid repository. When you can curl the index.yaml, helm will also work.

**Comment by Kiran-38** [comment]
I am sorry closing the issue, as the problem was identified that the network address is not updated properly in helm values and now things are working fine. Thanks for the quick response.
