### ISSUE TITLE
in my project that contains the chart for all the app I need to pass my Chart.version in my values.yaml but i am not able 

### ISSUE THREAD

**Issue by narjesshmida** [helm/helm#11915]
this is the values.yaml file that contains many config for all the microservices in the application i have this section where i want to inject my Chart.version 

```
my-component:
  config:
    projectVersion: {{ .Chart.version .}}

```
and this Chart.yaml file 

```
apiVersion: v1
description: xxxxxxxxxxxxxxxxxxx
name: here_the_name_of_all_the_app
version: 2.1.0-162
```

i got always of parsing and the componenet when deployin is not able to read  {{ .Chart.version .}}  any help pleaase

**Comment by joejulian** [comment]
The problem is that the functions are all built to accept a `map[string]Interface` and .Chart isn't one:
```
ChartType: {{ typeOf .Chart }}
```
```
ChartType: struct { chart.Metadata; IsRoot bool }
```
and trying to get the `.value` from that struct will fail:
```
can't evaluate field version in type struct { chart.Metadata; IsRoot bool }
```

There is a simple cheat, however. Pass it to and from json (or yaml):
```
{{ $chart := toJson .Chart | fromJson }}
ChartVersion: {{ $chart.version }}
```
```
ChartVersion: 0.1.0
```

**Comment by narjesshmida** [comment]
@joejulian  thank you for your solution it helps me very much

**Comment by joejulian** [comment]
You're looking for the semver function: http://masterminds.github.io/sprig/semver.html
