### ISSUE TITLE
Missing documentation on dynamic label addition (CLI)

### ISSUE THREAD

**Issue by cglacet** [helm/helm#11911]
I can't find any documentation on how to pass [labels](https://helm.sh/docs/chart_best_practices/labels/) using command line arguments.

I have seen command lines here and there that seems to work for annotations, but the logic behind it doesn't seem documented.

Here are some examples of commands that work:

```bash
helm template helm/myTemplate -f helm/static_values.yaml --set annotations.annotationKey=annotationValue
```

On the other hand, the same with labels doesn't seem to work :

```bash
helm template helm/myTemplate -f helm/static_values.yaml --set labels.labelKey=labelValue
```

I tried other forms (random guesses since I couldn't find any documentation):

```bash
helm template helm/myTemplate -f helm/static_values.yaml \
  --set labels.labelKeyA=labelValueA \
  --set label.labelKeyB=labelValueB \
  --set metadata.labels.labelKeyC=labelValueC \
  --set metadata.label.labelKeyD=labelValueD
```

None of which works.

**Comment by joejulian** [comment]
The chart has to be configured to accept annotations or labels. See you chart's `values.yaml`. Most of them are well documented.
