### ISSUE TITLE
Reference dependency chart files in parent chart.

### ISSUE THREAD

**Issue by MohamadTahir** [helm/helm#11914]
Hello, I have created a common helm chart that has common components that I could use in other charts, one of those common things is a deployment and a typical configMap/secret, and I made sure to update my deployment every time the configMap/secret get updated, following [this](https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments). 

Now I have a use case where a chart that is using my common chart has a deployment that uses the same configMap/secret being generated in the common chart, I want the deployment in the parent chart to get updated when the configMap/secret gets updated but I can not reference configMap/secret (couldn't find documentation on how to do such a thing). I thought of a few solutions but I don't think any of them is clean enough, here are my solutions.

1- Just give the deployment a random annotation using `{{ randAlphaNum 5 | quote }}` and re-deploy every time.

2- Since I have the chart in my dependencies that means I will pass the values for the configMap/secret through the parent chart values.yaml file and I could just create the same configMap/secret file in the parent chart and use those files to create the sha, but that will defeat the purpose of the common chart.

what do you think? is there a better way to achieve my goal? thank you ahead of time.

**Comment by joejulian** [comment]
Assuming you use a value to set configMap/secret, the parent chart could set that value and use it [[1](https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#overriding-values-from-a-parent-chart)]:
```
subchart:
  configMap:
    data:
      foo: bar
```
Your subchart would access that as `.Values.configMap.data` and the parent chart would use it as `.Values.subchart.configMap.data`

The other option would be to use the [global](https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#global-chart-values) special value.
