### ISSUE TITLE
Helm behind proxy

### ISSUE THREAD

**Issue by hermanmaleiane** [helm/helm#11913]
How can i use Helm behind a proxy.

$ helm repo add rancher-alpha https://releases.rancher.com/server-charts/alpha

Error: looks like "https://releases.rancher.com/server-charts/alpha" is not a valid chart repository or cannot be reached: Get "https://releases.rancher.com/server-charts/alpha/index.yaml": proxyconnect tcp: tls: first record does not look like a TLS handshake

**Comment by joejulian** [comment]
The standard HTTP library in Go reads the environment variables HTTP_PROXY , HTTPS_PROXY , and NO_PROXY
