### ISSUE TITLE
Helm debian package installation

### ISSUE THREAD

**Issue by mattfox** [helm/helm#11937]
I maintain and host the unofficial Debian package for Helm, documented here: https://helm.sh/docs/intro/install/#from-apt-debianubuntu

The web site for the repo is here: https://helm.baltorepo.com/

I have changed the repo to use a new CDN provider. Hopefully this doesn't introduce any issues but I'm making this issue here as a notification and a place to discuss any issues. I'll close it myself in a few days if nobody reports problems.

The repo gets about 70,000 downloads/week and uses 4.5 TB/month bandwidth.

**Comment by joejulian** [comment]
I'll mention this at the next helm developer meeting on Thursday the 30th.

**Comment by mattfox** [comment]
I haven't heard of any trouble with the new CDN so I'll close this.

**Comment by mdrakiburrahman** [comment]
The steps in the new destination throws:

![image](https://user-images.githubusercontent.com/46581776/228993321-fef0d9ef-8582-489a-b737-f1d05dba97d5.png)

**Comment by mattfox** [comment]
Yes there was an issue. It should be resolved now. Please try again.

**Comment by tremblaysimon** [comment]
Does `https://helm.baltorepo.com/` URL mark as deprecated and we should use only `https://baltocdn.com/helm` as documented to skip problems in the future?
