### ISSUE TITLE
Helm lint returns diffrent result in 3.9.4 helm version

### ISSUE THREAD

**Issue by miki90014** [helm/helm#11935]
Output of `helm version`: 3.4.1 and 3.9.4

Hi, I' think I have found bug or there is some changes in helm lint that I don't understand. 
While I was using helm lint command in `helm version: 3.7.4`, I've cleared a values.yaml file and used other files (configuration files) to set values.
Example: `helm lint path_to_chart -f config.yaml -f global.yaml`.

The purpose of this action was to verify values.schema.json. In my configuration files I was modifing properties to correct or incorrect values according to schema. In my schema there was a property like this:

```yaml
...
"unifiedLogging": {
        "type": "object",
        "default": {},
        "properties": {
          "extension": {
            "type": "object",
            "default": {},
            "additionalProperties": true
          },
          "syslog": {
            "properties": {
              "enabled": {
                "type": ["null", "boolean"],
                "default": false
              },
              "facility": {
                "type": ["null", "string"],
                "default": null
              },
              "host": {
                "type": ["null", "string"],
                "default": null
              },
             ...
              }
            }
}
...
```
So, to check my schema I set in global.yaml:
```yaml
...
"unifiedLogging": "wrong_type"
...
```
And I removed all unifiedLogging's properties, to have only this string as value.
Because I set string when the actual type should be an object, helm lint returns error and that is expected error. However, when I've switched version of helm to 3.9.4, helm lint returns no error. 
And in other fields like this one for example:
```yaml
...
"istio": {
          "type": "object",
          "default": {
            "enabled": false
          },
          "title": "The istio Schema",
          "required": ["enabled"],
          "properties": {
            "enabled": {
              "type": "boolean",
              "default": false,
              "title": "The enabled Schema",
              "examples": [false]
            },
            "version": {
              "type": "string",
              "default": "1.15",
              "title": "The version Schema",
              "examples": ["1.15"]
            },
            ...
        },
...
```
When I do the same modification:
```
...
"istio" : "wrong_type"
...
```
Result of helm lint is as expected: helm lint returns error in 3.4.1 and 3.9.4 version.

Below I attached logs from both helm version, while I was modifing "unifiedLogging" property to invalid type accordingto schema:
Helm 3.4.1 with returned error:
```
Executing command:
helm --namespace rp lint /tmp/test-temp-dir/nokia-csf-authentication -f /tmp/test-temp-dir/config/config.yaml -f /tmp/test-temp-dir/config/dimensions.yaml -f /tmp/test-temp-dir/config/global.yaml -f /tmp/test-temp-dir/config/preset.yaml    
08:59:23.079    DEBUG   Started process id: 3347    
08:59:23.278    INFO    rc: 1   
08:59:23.278    INFO    stdout:
==> Linting /tmp/test-temp-dir/nokia-csf-authentication
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: values don't meet the specifications of the schema(s) in the following chart(s):
nokia-csf-authentication-operator:
- global.unifiedLogging: Invalid type. Expected: object, given: string
08:59:23.278    INFO    stderr:
coalesce.go:160: warning: skipped value for containerSecurityContext: Not a table.
coalesce.go:196: warning: cannot overwrite table with non table for unifiedLogging (map[extension:map[] syslog:map[enabled:<nil> facility:<nil> host:<nil> keyStore:map[] keyStorePassword:map[] port:<nil> protocol:<nil> trustStore:map[] trustStorePassword:map[]]])
coalesce.go:196: warning: cannot overwrite table with non table for unifiedLogging (map[extension:map[] syslog:map[enabled:false facility:<nil> host:<nil> keyStore:map[] keyStorePassword:map[] port:<nil> protocol:<nil> trustStore:map[] trustStorePassword:map[]]])
coalesce.go:160: warning: skipped value for containerSecurityContext: Not a table.
coalesce.go:196: warning: cannot overwrite table with non table for unifiedLogging (map[extension:map[] syslog:map[enabled:<nil> facility:<nil> host:<nil> keyStore:map[] keyStorePassword:map[] port:<nil> protocol:<nil> trustStore:map[] trustStorePassword:map[]]])
coalesce.go:196: warning: cannot overwrite table with non table for unifiedLogging (map[extension:map[] syslog:map[enabled:false facility:<nil> host:<nil> keyStore:map[] keyStorePassword:map[] port:<nil> protocol:<nil> trustStore:map[] trustStorePassword:map[]]])
Error: 1 chart(s) linted, 1 chart(s) failed
```
Helm 3.9.4 with no returned error:
```
Executing command:
helm --namespace rp lint /tmp/test-temp-dir/nokia-csf-authentication -f /tmp/test-temp-dir/config/config.yaml -f /tmp/test-temp-dir/config/dimensions.yaml -f /tmp/test-temp-dir/config/global.yaml -f /tmp/test-temp-dir/config/preset.yaml    
11:20:32.950    DEBUG   Started process id: 22810   
11:20:33.595    INFO    rc: 0   
11:20:33.595    INFO    stdout:
==> Linting /tmp/test-temp-dir/nokia-csf-authentication
[INFO] Chart.yaml: icon is recommended
[WARNING] templates/ckey_cert_refresh_job.yaml: batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
1 chart(s) linted, 0 chart(s) failed
11:20:33.595    INFO    stderr:
coalesce.go:220: warning: cannot overwrite table with non table for nokia-csf-authentication.operator.global.unifiedLogging (map[extension:map[] syslog:map[enabled:false facility:<nil> host:<nil> keyStore:map[] keyStorePassword:map[] port:<nil> protocol:<nil> trustStore:map[] trustStorePassword:map[]]])
coalesce.go:220: warning: cannot overwrite table with non table for nokia-csf-authentication.cmdb.global.unifiedLogging (map[extension:map[] syslog:map[enabled:<nil> facility:<nil> host:<nil> keyStore:map[] keyStorePassword:map[] port:<nil> protocol:<nil> trustStore:map[] trustStorePassword:map[]]])
coalesce.go:220: warning: cannot overwrite table with non table for operator.global.unifiedLogging (map[extension:map[] syslog:map[enabled:false facility:<nil> host:<nil> keyStore:map[] keyStorePassword:map[] port:<nil> protocol:<nil> trustStore:map[] trustStorePassword:map[]]])
coalesce.go:139: key unifiedLogging is table. Skipping
coalesce.go:139: key unifiedLogging is table. Skipping
coalesce.go:139: key unifiedLogging is table. Skipping
coalesce.go:139: key unifiedLogging is table. Skipping
```

**Comment by joejulian** [comment]
Please try 3.11.2 and see if the problem still exists.

**Comment by miki90014** [comment]
I have to use on 3.9.4 helm version. Is there any way to avoid this "skipping"?
Logs:

Executing command:
helm --namespace rp lint /tmp/test-temp-dir/nokia-csf-authentication -f /tmp/test-temp-dir/config/config.yaml -f /tmp/test-temp-dir/config/dimensions.yaml -f /tmp/test-temp-dir/config/global.yaml -f /tmp/test-temp-dir/config/preset.yaml    
11:20:32.950    DEBUG   Started process id: 22810   
11:20:33.595    INFO    rc: 0   
11:20:33.595    INFO    stdout:
==> Linting /tmp/test-temp-dir/nokia-csf-authentication
[INFO] Chart.yaml: icon is recommended
[WARNING] templates/ckey_cert_refresh_job.yaml: batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
1 chart(s) linted, 0 chart(s) failed
11:20:33.595    INFO    stderr:
coalesce.go:220: warning: cannot overwrite table with non table for nokia-csf-authentication.operator.global.unifiedLogging (map[extension:map[] syslog:map[enabled:false facility:<nil> host:<nil> keyStore:map[] keyStorePassword:map[] port:<nil> protocol:<nil> trustStore:map[] trustStorePassword:map[]]])
coalesce.go:220: warning: cannot overwrite table with non table for nokia-csf-authentication.cmdb.global.unifiedLogging (map[extension:map[] syslog:map[enabled:<nil> facility:<nil> host:<nil> keyStore:map[] keyStorePassword:map[] port:<nil> protocol:<nil> trustStore:map[] trustStorePassword:map[]]])
coalesce.go:220: warning: cannot overwrite table with non table for operator.global.unifiedLogging (map[extension:map[] syslog:map[enabled:false facility:<nil> host:<nil> keyStore:map[] keyStorePassword:map[] port:<nil> protocol:<nil> trustStore:map[] trustStorePassword:map[]]])
coalesce.go:139: key unifiedLogging is table. _**Skipping**_
coalesce.go:139: key unifiedLogging is table. _**Skipping**_
coalesce.go:139: key unifiedLogging is table. _**Skipping**_
coalesce.go:139: key unifiedLogging is table. _**Skipping**_

**Comment by joejulian** [comment]
grep -v?

Why do you need to continue using an unsupported version of helm?
