### ISSUE TITLE
Tpl function cannot find variable

### ISSUE THREAD

**Issue by kiweezi** [helm/helm#11946]
When using the `tpl` function, global context variables cannot be referenced.

Here I try to get the name from a variable defined in the current context:
```yaml
# configmap.yaml
{{- $name := "Jim" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: test
data:
  name: {{ tpl "{{ $name }}" . }}
```
I do the same with the global context:
```yaml
data:
  name: {{ tpl "{{ $name }}" $ }}
```

Both fail with the same error, describing an `undefined variable "$name"`:
```powershell
PS > helm template ../helm/test --debug
Error: template: test/templates/configmap.yaml:7:11: executing "test/templates/configmap.yaml" at <tpl "{{ $name }}" .>: error calling tpl: error during tpl function execution for "{{ $name }}": parse error at (test/templates/configmap.yaml:1): undefined variable "$name"
helm.go:84: [debug] template: test/templates/configmap.yaml:7:11: executing "test/templates/configmap.yaml" at <tpl "{{ $name }}" .>: error calling tpl: error during tpl function execution for "{{ $name }}": parse error at (test/templates/configmap.yaml:1): undefined variable "$name"
```

I'm still fairly new to Helm and I apologise if I have made a mistake here.
I have not been able to find any docs explaining this behaviour. I've also found some issues which describe problems that relate to this behaviour and [show valid workarounds](https://github.com/helm/helm/issues/7626#issuecomment-587945056), but none address it directly.
If this is intentional and not a bug, I think it would be a good idea to describe this somewhere, as I spent a day trying to figure it out!

Output of `helm version`:
```powershell
PS > helm version
version.BuildInfo{Version:"v3.10.1", GitCommit:"9f88ccb6aee40b9a0535fcc7efea6055e1ef72c9", GitTreeState:"clean", GoVersion:"go1.18.7"}
```

Output of `kubectl version`:
```powershell
PS > kubectl version --client --output=yaml
clientVersion:
  buildDate: "2022-11-09T13:36:36Z"
  compiler: gc
  gitCommit: 872a965c6c6526caa949f0c6ac028ef7aff3fb78
  gitTreeState: clean
  gitVersion: v1.25.4
  goVersion: go1.19.3
  major: "1"
  minor: "25"
  platform: windows/amd64
kustomizeVersion: v4.5.7
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
[OVHCloud](https://www.ovh.com)

**Comment by joejulian** [comment]
`{{- $name := "Jim" }}` is a local template variable that does not exist outside the template being processed. Those variables are not part of the `map[string]interface` that is `.` or `$`.

Add your wanted variable to `.`:
```
{{ $_ := set . "name" "test" }}
name: {{ tpl "{{ .name }}" . }}
```

**Comment by kiweezi** [comment]
Thanks @joejulian for clearing that up! I didn't know about `$_`.
Is there a doc where I can read further about this? Or how I might add to the `$` context?
I can't find a page about reserved variables, other than the mention of `$` on the [variables doc](https://helm.sh/docs/chart_template_guide/variables/).
