### ISSUE TITLE
Add Helm to the CNCF Project Summary Table 

### ISSUE THREAD

**Issue by CathPag** [helm/helm#11940]
Dear maintainers,

The CNCF Business Value Subcommittee has developed a project summary table to supplement the CNCF Landscape and includes further information about CNCF projects for the broader cloud native community. We would like to request your project to submit a PR to the CNCF Landscape repository with additional details that will help further inform the community about your project and its use cases through the popular landscape and this new addition.

The table is located here: https://landscape.cncf.io/summary
There are directions located here: https://github.com/cncf/landscape/blob/master/readme_summary.md

Many thanks for this - we hope it will help further get the word out about your project.

**Comment by joejulian** [comment]
I'll bring this up at the next developers meeting.
