### ISSUE TITLE
helm comments are not working as expected

### ISSUE THREAD

**Issue by karthiksiva-github** [helm/helm#11959]
Let's say my helm chart has only one manifests which is given below.( This works fine as expected without issues and I can able to install helm chart without any issues)

**#comment 1
#comment**
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-network-policy
spec:
  podSelector:
    matchLabels:
      role: db
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - ipBlock:
            cidr: 172.17.0.0/16
            except:
              - 172.17.1.0/24
        - namespaceSelector:
            matchLabels:
              project: myproject
        - podSelector:
            matchLabels:
              role: frontend
      ports:
        - protocol: TCP
          port: 6379
  egress:
    - to:
        - ipBlock:
            cidr: 10.0.0.0/24
      ports:
        - protocol: TCP
          port: 5978

**Scenario 2**

Now, I am using the same resource manifests with no changes, just that I have included entire yaml contents under IF clause like below, and this is where I am getting a weird error  "**Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: apiVersion not set**"

**#comment 1
#comment**
{{- if .Values.global.networkpolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-network-policy
spec:
  podSelector:
    matchLabels:
      role: db
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - ipBlock:
            cidr: 172.17.0.0/16
            except:
              - 172.17.1.0/24
        - namespaceSelector:
            matchLabels:
              project: myproject
        - podSelector:
            matchLabels:
              role: frontend
      ports:
        - protocol: TCP
          port: 6379
  egress:
    - to:
        - ipBlock:
            cidr: 10.0.0.0/24
      ports:
        - protocol: TCP
          port: 5978
{{- end }}

**Scenario 3:**
When I give the comments like below, helm chart is getting installed without any issues. 

**{{- /*
This is a comment.
*/}}**
{{- if .Values.global.networkpolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-network-policy
spec:
  podSelector:
    matchLabels:
      role: db
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - ipBlock:
            cidr: 172.17.0.0/16
            except:
              - 172.17.1.0/24
        - namespaceSelector:
            matchLabels:
              project: myproject
        - podSelector:
            matchLabels:
              role: frontend
      ports:
        - protocol: TCP
          port: 6379
  egress:
    - to:
        - ipBlock:
            cidr: 10.0.0.0/24
      ports:
        - protocol: TCP
          port: 5978
{{- end }}

So my question is, why helm installation is successful when I provide the comments in the form of template comments and this is not a template file and this is normal yaml file.

Output of `helm version`: v3.9.4

Output of `kubectl version`:
Client Version: v1.22.1
Server Version: v1.18.20

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  Local Kubernetes

**Comment by amannijhawan** [comment]
Hi,
Can you format the helm chart correctly as code, it’s difficult to parse what’s going on with the current charts as the indentation is not correct.

Thanks

**Comment by ecomger** [comment]
> Hi, Can you format the helm chart correctly as code, it’s difficult to parse what’s going on with the current charts as the indentation is not correct.
> 
> Thanks

I've replicated this error too. Here is the sample code:
```
# Comment
# Comment
{{- if .Values.global -}}
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers
  - name: niginx
     image: nginx.1.14.2
     ports
     - containerPort: 80
{{- end }}
```
Whereas this code, with the hyphen just before the call to the conditional statement 'if .Valules.global' removed, works:
```
# Comment
# Comment
{{ if .Values.global -}}
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers
  - name: niginx
     image: nginx.1.14.2
     ports
     - containerPort: 80
{{- end }}
```
