### ISSUE TITLE
Local dependency not found if in a directory different than charts

### ISSUE THREAD

**Issue by alsastre** [helm/helm#11958]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.11.1", GitCommit:"293b50c65d4d56187cd4e2f390f0ada46b4c4737", GitTreeState:"clean", GoVersion:"go1.19.5"}
```

I am new to helm and was playing with how dependencies can be used to manage charts for different components so I am not sure if this is a misunderstanding on my part or a bug.

### Scenario:
One chart (`poc2-stack-playground`) with one pod template and one subchart (`example-subchart-app`) with one deployment and configmap.
Code available [here](https://github.com/alsastre/helm-poc2-stack-playground) with all the existing files
In summary:
Dependency defined:
```
dependencies:
  - name: example-subchart-app
    repository: "file://subcharts/example-subchart-app"
    version: "0.1.0"
```
Chart contains:
```
./templates/simplepod.yaml
```
Subchart contains (no conditions)
```
./subcharts/example-subchart-app/templates/deployment.yaml
./subcharts/example-subchart-app/templates/configmap.yaml
```

### Problem:
`helm dep list/update`: Succeeds but...
```
NAME                	VERSION	REPOSITORY                           	STATUS
example-subchart-app	0.1.0  	file://subcharts/example-subchart-app	ok
```
- `helm install test-parentchart . --debug --dry-run`: Installation fails due to missing dependency
- `helm install test-parentchart . --debug --dependency-update --dry-run`:  Installation does not include subchart components

If subchart is created in the `charts` folder:
- `helm install ...`: Installs expected components, pod, deployment and configmap

### Expected behaviour:
- It should be possible to have the code of local charts in a different folder. (`helm dep update` should copy the required files,tgz)
- If the dependency is found by `helm dep update`, `helm install` should not complain of missing dependencies

Thanks for your help

**Comment by joejulian** [comment]
Cannot duplicate.

```
version.BuildInfo{Version:"v3.11.1", GitCommit:"293b50c65d4d56187cd4e2f390f0ada46b4c4737", GitTreeState:"clean", GoVersion:"go1.20.1"}
```

**Comment by alsastre** [comment]
Found the problem, thank you @joejulian 
I tried using the repo and I was able to install the helm without issues.

The difference between the repo and the folder where I was testing was the `.helmignore`, so I reviewed and saw that I had added `*tgz`  (instead of adding it to the `.gitignore`)

After removing `*tgz` from the `.helmignore` the installation and dependencies work as expected.
