### ISSUE TITLE
docker-credential-desktop requirement to build template

### ISSUE THREAD

**Issue by disparo13** [helm/helm#11951]
I just want to build a local template on my MacOS terminal without deploying/installing anything to anywhere.

Running the command
`helm template karpenter oci://public.ecr.aws/karpenter/karpenter --version v0.27.0 --dry-run`

causing an error:
`Error: error getting credentials - err: docker-credential-desktop resolves to executable in current directory (./docker-credential-desktop), out: ```

I have no Docker desktop installed and don't wan't to install it - I use Podman instead.

Output of `helm version`:
version.BuildInfo{Version:"v3.11.2", GitCommit:"912ebc1cd10d38d340f048efaf0abda047c3468e", GitTreeState:"clean", GoVersion:"go1.20.2"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:33:11Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS

**Comment by joejulian** [comment]
Maybe delete the docker credential helper from the current directory then?
```
rm ./docker-credential-desktop
```

This is a tool that oras uses for helping with credentials that may be needed for oci.

**Comment by disparo13** [comment]
@joejulian I'm running from an empty directory.

```
~/git/111
➜ ls -l
total 0

~/git/111 
➜ helm template karpenter oci://public.ecr.aws/karpenter/karpenter --version v0.27.0 --dry-run
Error: error getting credentials - err: docker-credential-desktop resolves to executable in current directory (./docker-credential-desktop), out: ``
```

**Comment by joejulian** [comment]
Do this:

```
strace -e trace=file -ff helm template karpenter oci://public.ecr.aws/karpenter/karpenter --version v0.27.0 --dry-run 2>&1 | grep docker-credential
```

It will dump a huge list of places it's checking, but I'm betting one of them doesn't fail. Rename or delete the one that succeeds and that should get you going.

Report back what you find. I don't know if the error can be reported any better, but with sufficient information maybe we can turn this into a bug report.

**Comment by disparo13** [comment]
@joejulian I couldn't run `strace` command on MacOS - it requires the Linux kernel, which I of course - don't have. I couldn't find a replacement for it as well. But running with the `--debug` gave me that output. Does it help?


```
➜ helm template karpenter oci://public.ecr.aws/karpenter/karpenter --version v0.27.0 --dry-run --debug
install.go:194: [debug] Original chart version: "v0.27.0"
DEBU[0000] resolving                                     host=public.ecr.aws
DEBU[0000] do request                                    host=public.ecr.aws request.header.accept="application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, */*" request.header.user-agent=Helm/3.11.3 request.method=HEAD url="https://public.ecr.aws/v2/karpenter/karpenter/manifests/v0.27.0"
DEBU[0000] fetch response received                       host=public.ecr.aws response.header.content-length=58 response.header.content-type="application/json; charset=utf-8" response.header.date="Mon, 17 Apr 2023 15:27:52 GMT" response.header.docker-distribution-api-version=registry/2.0 response.header.www-authenticate="Bearer realm=\"https://public.ecr.aws/token/\",service=\"public.ecr.aws\",scope=\"aws\"" response.status="401 Unauthorized" url="https://public.ecr.aws/v2/karpenter/karpenter/manifests/v0.27.0"
DEBU[0000] Unauthorized                                  header="Bearer realm=\"https://public.ecr.aws/token/\",service=\"public.ecr.aws\",scope=\"aws\"" host=public.ecr.aws
INFO[0000] trying next host                              error="error getting credentials - err: exec: \"docker-credential-desktop\": executable file not found in $PATH, out: ``" host=public.ecr.aws
Error: error getting credentials - err: exec: "docker-credential-desktop": executable file not found in $PATH, out: ``
helm.go:84: [debug] error getting credentials - err: exec: "docker-credential-desktop": executable file not found in $PATH, out: ``
```

**Comment by joejulian** [comment]
Huh.. maybe that error message is useless. This looks like it might be because of the 401 error. I'll see if I can repro this.

**Comment by disparo13** [comment]
@joejulian Finally I found this https://stackoverflow.com/questions/65896681/exec-docker-credential-desktop-exe-executable-file-not-found-in-path/65896682#65896682

The solution is `Delete the line with credsStore from ~/.docker/config.json.`

In my case the line was `credsStore: "desktop"`

I just couldn't imagine that helm can be tight with Docker configuration somehow. 

But thanks for your attention and willingness to help anyway!

**Comment by alex-wahl** [comment]
@disparo13 Thanks a lot!!!!
