### ISSUE TITLE
Helm upgrade takes a long time for frequently upgraded apps that have large values

### ISSUE THREAD

**Issue by PrashantRaj18198** [helm/helm#11965]
For apps that have a large values file upgrades are taking a lot time and memory when they have been upgraded quite a few times.

### Repro
- Create a helm release for a [sample application](https://artifacthub.io/packages/helm/hello/hello) doesn't need to have too many resources, just having a large values file (~2000 lines) should be enough. 
- Upgrade it a bunch of times (~500 times).
- Each time you try to do `helm upgrade`, helm will use more memory because it loads up all the revisions that have been made before doing an upgrade, this is a lot of data.

### Potential Solution
- Since revisions are stored as kubernetes secret and there is no way of limiting the data coming from kubernetes, we can try to introduce something that cleans up old revisions in the `helm upgrade` itself. For example, having the ability to keep the latest 20 past revisions would be great.

**Comment by joejulian** [comment]
`helm upgrade` has the `--history-max` flag for this. It defaults to 10.

**Comment by PrashantRaj18198** [comment]
I am using the golang package but that seems to have this as well. Thanks for the responding to this. I'm closing this.
