### ISSUE TITLE
Wrong USER-SUPPLIED VALUES at case of Linting

### ISSUE THREAD

**Issue by SlavaUtesinov** [helm/helm#11964]
I guess there is a bug when I create a client with `Linting` option and call `client.InstallChart` providing `ValuesYaml` (some code fragments have been omitted for brevity):
```
opt := &helmclient.KubeConfClientOptions{
    Options: &helmclient.Options{
	Linting: true
    },
}
client, err := helmclient.NewClientFromKubeConf(opt)
spec := &helmclient.ChartSpec{
    ValuesYaml: valuesYaml,
}
release, err := client.InstallChart(ctx, spec, opt)
```
 The bug is located at the following section https://github.com/helm/helm/blob/v3.11.2/pkg/lint/rules/values.go#L74,L75:
```
coalescedValues := chartutil.CoalesceTables(make(map[string]interface{}, len(overrides)), overrides)
coalescedValues = chartutil.CoalesceTables(coalescedValues, values)
```
It sometimes mutates input argument - `overrides` (the second line at the code snippet) with values from chart's values.yaml what leads to mutation of USER-SUPPLIED VALUES output when I eventually call `helm get all release-name`:

expected output:
```  
USER-SUPPLIED VALUES:
image:
  repository: v0
```
actual:
```
USER-SUPPLIED VALUES:
image:
  repository: v0
  tag: v2
  pullPolicy: v3
``` 
chart's values.yaml:
```
image:
  repository: v1
  tag: v2
  pullPolicy: v3
```  
`ValuesYaml`:
```  
image:
  repository: v0
```

**Comment by joejulian** [comment]
This looks right to me. When you pass values, they're merged with the values.yaml in the chart.

**Comment by SlavaUtesinov** [comment]
@joejulian Yes, it is right to merge this values. But there is USER-SUPPLIED VALUES and COMPUTED VALUES (merged) to understand where each value came from and at this case value.yaml values leak to user supplied section.

**Comment by rushikeshsuryawanshi** [comment]
Hey @joejulian I would like to contribute to this issue
