### ISSUE TITLE
Helm sdk can't close PostgreSQL Connection

### ISSUE THREAD

**Issue by yeVoker** [helm/helm#11975]
Output of `helm version`: v3.7.1

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by liangyuanpeng** [comment]
@yeVoker 
Have not get the issue, helm have not manager your postgreSQL. It just deploy your resource on your k8s.

**Comment by wujunwei** [comment]
Do you mean using PostgreSQL as backend storage? If it is an SDK scenario, when do you think the connection should be closed?

**Comment by joejulian** [comment]
This is not a complete issue. I'm going to go ahead and close it. If you still have a question, please provide sufficient details for someone other than yourself to understand it.
