### ISSUE TITLE
Helm works only with owner role with psql

### ISSUE THREAD

**Issue by GOodCoffeeLover** [helm/helm#11970]
Hi, we are using helm with the sql storage (psql) instead classic secrets storage. We are trying to separate permissions for database. But helm only works with access role = owner, but not with read-write rights. Looks like helm always runs migrations with `CREATE TABLE`, which are not allowed for read-write user. Is there a way to fix it in helm, maybe by manual checking existence of table or migration?

<img width="1409" alt="image" src="https://user-images.githubusercontent.com/55360517/230487954-30417ea2-c9c9-48b1-876c-bf275e0129dc.png">

Output of `helm version`:
version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.19.4"}

Output of `kubectl version`:
k version -oyaml
clientVersion:
  buildDate: "2022-10-12T10:47:25Z"
  compiler: gc
  gitCommit: 434bfd82814af038ad94d62ebe59b133fcb50506
  gitTreeState: clean
  gitVersion: v1.25.3
  goVersion: go1.19.2
  major: "1"
  minor: "25"
  platform: darwin/arm64
kustomizeVersion: v4.5.7
serverVersion:
  buildDate: "2022-03-16T14:02:06Z"
  compiler: gc
  gitCommit: 38d3c1f3d5306401bcf39a71bad3b5a5106033d7
  gitTreeState: clean
  gitVersion: v1.21.11
  goVersion: go1.16.15
  major: "1"
  minor: "21"
  platform: linux/amd64

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Vanila self managed kubernetes

**Comment by yxxhero** [comment]
@GOodCoffeeLover PR is welcome.
