### ISSUE TITLE
Issue with helm update from public repo

### ISSUE THREAD

**Issue by onjectiondevops** [helm/helm#11984]
I am facing intermediate issue while updating helm repo. It happens randomly. 
```
# helm dependency update charts/chart/ --debug
Getting updates for unmanaged Helm repositories...
...Successfully got an update from the "https://cdmbase.github.io/helm-chart/helm-packages" chart repository
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "kube-orchestration" chart repository
...Successfully got an update from the "incubator" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈

Error: error loading /root/.cache/helm/repository/stable-index.yaml: empty index.yaml file
helm.go:84: [debug] empty index.yaml file
```

**Comment by joejulian** [comment]
If you're referring to the helm/charts repo, that's long since been deprecated. If it still works at all, that's a surprise.

> Nov 13, 2020 | At 1 year, support for this project will formally end, at which point the stable and incubator  chart repos will be marked obsolete. At that time these chart repos  will likely be garbage collected and no longer available. This git  repository will remain as an archive.
--- | ---

https://github.com/helm/charts/#deprecation-timeline
