### ISSUE TITLE
Warnings on running helm in Ubuntu 20.04 on WSL2

### ISSUE THREAD

**Issue by sampathsris** [helm/helm#11992]
Output of `helm version` (warnings redacted):
```
version.BuildInfo{Version:"v3.10.1", GitCommit:"9f88ccb6aee40b9a0535fcc7efea6055e1ef72c9", GitTreeState:"clean", GoVersion:"go1.18.7"}
```

Output of `kubectl version`:
*Not applicable*

Platform: 
WSL running Ubuntu 20.04
```sh
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
```
```cmd
PS> wsl -v
WSL version: 1.1.6.0
Kernel version: 5.15.90.1
WSLg version: 1.0.50
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19042.2728
```

<hr />

I'm running Ubuntu 20.04 on WSL2, and whenever I run any `helm` command, I get the following warnings:

> 2023/04/13 18:50:51.020212 system_key.go:129: cannot determine nfs usage in generateSystemKey: cannot parse mountinfo: incorrect number of tail fields, expected 3 but found 4
> 2023/04/13 18:50:51.024784 cmd_run.go:1046: WARNING: cannot create user data directory: cannot determine SELinux status: failed to obtain SELinux mount path: incorrect number of tail fields, expected 3 but found 4

Searching for this error has not produced anything meaningful. While the warnings must have good intentions, it clutters the output and is very much in the way as the warnings are printed on any and all helm commands. How can I fix/suppress this warning?

**Comment by mattfarina** [comment]
I think these are messages from snap and not Helm.

**Comment by sampathsris** [comment]
@mattfarina Thanks. Do we know what `snap` commands we can execute to reproduce this (i.e., what snap commands does helm want to execute internally)? If I know this I might be able to fix it in snap.

**Comment by sampathsris** [comment]
@mattfarina I think my earlier question does not make sense. I've realized that helm does not invoke any snap commands, rather snap invokes helm.

I ran helm with `SNAP_CONFINE_DEBUG=yes`, and this is the output I got:

```
$ SNAP_CONFINE_DEBUG=yes helm ls
2023/04/14 02:34:53.395489 system_key.go:129: cannot determine nfs usage in generateSystemKey: cannot parse mountinfo: incorrect number of tail fields, expected 3 but found 4
2023/04/14 02:34:53.399251 cmd_run.go:1046: WARNING: cannot create user data directory: cannot determine SELinux status: failed to obtain SELinux mount path: incorrect number of tail fields, expected 3 but found 4
DEBUG: -- snap startup {"stage":"snap-confine enter", "time":"1681419893.460473"}
DEBUG: umask reset, old umask was  022
DEBUG: security tag: snap.helm.helm
DEBUG: executable:   /snap/snapd/18596/usr/lib/snapd/snap-exec
DEBUG: confinement:  classic
DEBUG: base snap:    core18
DEBUG: ruid: 1000, euid: 0, suid: 0
DEBUG: rgid: 1000, egid: 1000, sgid: 1000
DEBUG: apparmor extensions to the system are not available
DEBUG: -- snap startup {"stage":"snap-confine mount namespace start", "time":"1681419893.461157"}
DEBUG: preparing classic execution environment
DEBUG: -- snap startup {"stage":"snap-confine mount namespace finish", "time":"1681419893.461195"}
DEBUG: set_effective_identity uid:1000 (change: yes), gid:1000 (change: yes)
DEBUG: creating user data directory: /home/samslk/snap/helm/372
DEBUG: ruid: 1000, euid: 1000, suid: 0
DEBUG: setting capabilities bounding set
DEBUG: regaining SYS_ADMIN
DEBUG: loading bpf program for security tag snap.helm.helm
DEBUG: read 14 bytes from /var/lib/snapd/seccomp/bpf//snap.helm.helm.bin
DEBUG: clearing SYS_ADMIN
DEBUG: execv(/snap/snapd/18596/usr/lib/snapd/snap-exec, /snap/snapd/18596/usr/lib/snapd/snap-exec...)
DEBUG:  argv[1] = helm
DEBUG:  argv[2] = ls
DEBUG: umask restored to  022
DEBUG: working directory restored to /home/samslk/experiments/misc/helm-tutorial
DEBUG: -- snap startup {"stage":"snap-confine to snap-exec", "time":"1681419893.461324"}

...normal helm output from this point onwards
```

So it indeed looks like the warnings are coming from snap, as the helm executable is not started by snap until later.

Therefore I will close this issue myself. Thank you for your help.

**Comment by sampathsris** [comment]
In the end I had to remove helm from snap.

```sh
sudo snap remove helm
```

And installed it [using the script as described in helm documentation](https://helm.sh/docs/intro/install/#from-script). Then it worked perfectly.
