### ISSUE TITLE
US baltocdn serves stale arm64 files?

### ISSUE THREAD

**Issue by cloneable** [helm/helm#12004]
Hi, I'm trying to install helm via apt in debian:bullseye and at least one baltocdn server instances seems to serve stale/broken/corrupted arm64 package index:

Commands (taken from https://helm.sh/docs/intro/install/#from-apt-debianubuntu)

```shell
apt-get update && apt-get install curl gnupg apt-transport-https --yes

curl "https://baltocdn.com/helm/signing.asc" | gpg --dearmor | tee /usr/share/keyrings/helm.gpg >/dev/null
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | tee /etc/apt/sources.list.d/helm-stable-debian.list
apt-get update
```

Output:

```
Err:5 https://baltocdn.com/helm/stable/debian all/main arm64 Packages
File has unexpected size (3392 != 3320). Mirror sync in progress? [IP: 143.244.50.88 443]
Hashes of expected file:
- Filesize:3320 [weak]
- SHA256:9be66a086b4295f7e7afc1475a22db84d84362f4c81581de29750655655688df
- MD5Sum:4d1dbeec6f5d825f6657fcb83b540162 [weak]
Release file created at: Fri, 10 Mar 2023 03:34:56 +0000
Fetched 7652 B in 1s (8502 B/s)
Reading package lists... Done
E: Failed to fetch https://baltocdn.com/helm/stable/debian/dists/all/main/binary-arm64/Packages.xz File has unexpected size (3392 != 3320). Mirror sync in progress? [IP: 143.244.50.88 443]
Hashes of expected file:
- Filesize:3320 [weak]
- SHA256:9be66a086b4295f7e7afc1475a22db84d84362f4c81581de29750655655688df
- MD5Sum:4d1dbeec6f5d825f6657fcb83b540162 [weak]
Release file created at: Fri, 10 Mar 2023 03:34:56 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

`143.244.32.0/19` seems bad for the last 24 hours at least. So can't be ongoing mirror sync. European CDN instances seem to serve consistent files.

Please take a look.

**Comment by mattfarina** [comment]
@cloneable thanks for bringing this up. Unfortunately, the Helm project does not maintain that distribution location. It is members of the community. We don't have a way to react to this.

If this persists, we may need to remove the community project from our docs.

**Comment by cloneable** [comment]
I understand. Thank you! I'll try again tomorrow.

```
curl -s "https://baltocdn.com/helm/stable/debian/dists/all/Release" --resolve 'baltocdn.com:443:143.244.50.88' | grep main/binary-arm64/Packages
 43a3f951883b7a839612667d5098f113 20098 main/binary-arm64/Packages
 a478557328b6087233c61f1bd64ecd44 3726 main/binary-arm64/Packages.gz
 4d1dbeec6f5d825f6657fcb83b540162 3320 main/binary-arm64/Packages.xz
 0dc3bed217be62c89386189ed0ad6fb1e32d8460516c240d619975628219af82 20098 main/binary-arm64/Packages
 0ef640a3a62bb78ec9387fb50a8440d9e7285c0a328907976b8266b0ee5c0357 3726 main/binary-arm64/Packages.gz
 9be66a086b4295f7e7afc1475a22db84d84362f4c81581de29750655655688df 3320 main/binary-arm64/Packages.xz
```

```
curl -s "https://baltocdn.com/helm/stable/debian/dists/all/main/binary-arm64/Packages.xz" --resolve 'baltocdn.com:443:143.244.50.88' | sha256sum
bbfc701813e56aeec5cc5e106cdd2d76d3b87316e90c5b9f209bb59ed541a75e  -
```

**Comment by denys-pidlisnyi** [comment]
> @cloneable thanks for bringing this up. Unfortunately, the Helm project does not maintain that distribution location. It is members of the community. We don't have a way to react to this.
> 
> If this persists, we may need to remove the community project from our docs.

I think you can add a note about this information on the documentation without removing

**Comment by mattfox** [comment]
I'm the package maintainer and run Balto. I changed to a new CDN (BunnyCDN) a few weeks ago so maybe there's still a few things to learn about the new one. I have purged the CDN cache, maybe someone can try again and see if it's resolved.

**Comment by cloneable** [comment]
Seems to work now. Thank you! Feel free to close.
