### ISSUE TITLE
Please reopen issue #10733

### ISSUE THREAD

**Issue by ProbstDJakob** [helm/helm#12001]
Could you please reopen the issue #10733 since the problem has not been solved and prevents deploying charts with for example CronJobs requesting a PV like a backup job.

**Comment by joejulian** [comment]
I've reopened the issue. Would you be able to contribute a fix?

**Comment by ProbstDJakob** [comment]
Thank you.
I could open a PR, but there is already one (#11335). I did not look closely too say if it resolves the problem appropriately, but with a brief look into it, I would say it could be a solution.
