### ISSUE TITLE
Allow custom messages to be printed on uninstall if "helm.sh/resource-policy": keep is used

### ISSUE THREAD

**Issue by faisalchishtii** [helm/helm#12017]
Currently the following message is printed on uninstalling something if we use `"helm.sh/resource-policy": keep`

```
# helm uninstall <release>
These resources were kept due to the resource policy:
[ClusterRoleBinding] ops-rolebinding
[ClusterRole] ops-role
[ServiceAccount] ops-serviceaccount

```

My use case is the following: 

On uninstall, I need to cleanup few directories on all the worker nodes. For this, we make use of pre-delete hooks to spawn DaemonSet that does the job, then a Job deletes the DaemonSet. The job also delete the roles, sa, bindings etc that are not deleted by Helm. So, in this scenario, above message would be misleading for the customer/user. We do this as K8s natively does not support Jobs to be running on all worker nodes. 

Is there a way to override these message from the templates to avoid the confusion. If not, would it be acceptable to have this?

Output of `helm version`: `version.BuildInfo{Version:"v3.11.3", GitCommit:"323249351482b3bbfc9f5004f65d400aa70f9ae7", GitTreeState:"clean", GoVersion:"go1.20.3"}`

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:32:02Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): BareMetal/KVM

**Comment by joejulian** [comment]
There is not a way. Those messages come from the resources stored in the release manifest. When delete is walking the manifests, those resources are marked with that annotation and the response is generated. Perhaps just don't mark them with that annotation if they'll be deleted anyway?

**Comment by faisalchishtii** [comment]
@joejulian  We use the annotation to prevent service account, role, role binding etc. from getting deleted prior to running the cleanup DaemonSet. Then a Job deletes the DaemonSet and the service accounts etc.

**Comment by joejulian** [comment]
What if you run the DS as a pre-delete hook? Helm won't care if all the resources it wants to delete are already gone.

**Comment by joejulian** [comment]
oops

**Comment by faisalchishtii** [comment]
The DS has to run post deletion of resources. It won't work otherwise due to the nature of the app.
