### ISSUE TITLE
Can't disable  LoadBalancer creation

### ISSUE THREAD

**Issue by biozit** [helm/helm#12022]
I am trying to use Helm, but I don't have permission to create a LoadBalancer, and I can't find a way to disable it:

`  Warning  error   3m46s  helm-controller  Helm install failed: admission webhook "validation.gatekeeper.sh" denied the request: [block-load-balancer] User is not allowed to create service of type LoadBalancer`

**Comment by wujunwei** [comment]
It is obvious that a webhook named “gatekeeper” within your k8s cluster has rejected the creation of a 'loadbalance' type service.

**Comment by yxxhero** [comment]
@biozit please see https://github.com/helm/helm/issues/12022#issuecomment-1521238814. I will close the issue. if you have more issues. please free to post new issues.
