### ISSUE TITLE
Helm lint `--with-subcharts` fails on use of templates from superchart

### ISSUE THREAD

**Issue by astellingwerf** [helm/helm#12027]
While using `helm install` or `helm template` it works to reuse templates from the superchart in subcharts, but the same practice makes `helm lint` fail.

Imagine a hierarchy with a superchart and a subchart, with (beside the boilerplate) files:
`superchart\templates\_helpers.tpl`:
```helm
{{- define "superchart.randomString" -}}
{{- printf "%s" (randAlphaNum 16) }}
{{- end }}
```
`superchart\charts\subchart\templates\output.yaml`:
```helm
# include "superchart.randomString"  =>  {{ include "superchart.randomString" . }}
```

Running `helm template .` outputs something like:
```
---
# Source: superchart/charts/subchart/templates/output.yaml
# include "superchart.randomString"  =>  zcLXTjrNa4hOQlXr
```

But running `helm lint --with-subcharts .` outputs:
```
==> Linting .
[INFO] Chart.yaml: icon is recommended

==> Linting charts/subchart
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: template: subchart/templates/output.yaml:1:44: executing "subchart/templates/output.yaml" at <include "superchart.randomString" .>: error calling include: template: no template "superchart.randomString" associated with template "gotpl"

Error: 2 chart(s) linted, 1 chart(s) failed
```

Output of `helm version`:
`version.BuildInfo{Version:"v3.11.3", GitCommit:"323249351482b3bbfc9f5004f65d400aa70f9ae7", GitTreeState:"clean", GoVersion:"go1.20.3"}`

**Comment by joejulian** [comment]
Could you make a tarball of that chart tree and attach it, please? It'll save us time trying to duplicate it (I'm trying to get through 80 issues in the one hour I have today... not gunna make it :disappointed: ). Thanks in advance.

**Comment by astellingwerf** [comment]
I trust that a zip is also fine... [helm-issue-12027.zip](https://github.com/helm/helm/files/11442762/helm-issue-12027.zip)

**Comment by joejulian** [comment]
Thanks for that. I was able to duplicate the behavior you're experiencing and have concluded that it's working as documented.

Attached is a tarball with a couple small changes to your example that you might try.
[superchart.tar.gz](https://github.com/helm/helm/files/11500752/superchart.tar.gz)

---

To duplicate your issue, I did the following:

I added the missing dependency definition:
```
dependencies:
  - name: subchart
```

`helm template .  `
```
---
# Source: superchart/charts/subchart/templates/output.yaml
# include "superchart.randomString"  =>  rbiFyRmjit39v9c
```
`
helm lint . --with-subcharts` does, indeed, fail.
```
[INFO] Chart.yaml: icon is recommended

==> Linting charts/subchart
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: template: subchart/templates/output.yaml:1:44: executing "subchart/templates/output.yaml" at <include "superchart.randomString" .>: error calling include: template: no template "superchart.randomString" associated with template "gotpl"

Error: 2 chart(s) linted, 1 chart(s) failed
```

```
cd chart/subchart
helm lint .
==> Linting .
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: template: subchart/templates/output.yaml:1:44: executing "subchart/templates/output.yaml" at <include "superchart.randomString" .>: error calling include: template: no template "superchart.randomString" associated with template "gotpl"

Error: 1 chart(s) linted, 1 chart(s) failed
```
fails as expected.

This is expected according to the documentation:
> 1.  A subchart is considered "stand-alone", which means a subchart can never explicitly depend on its parent chart.
> 2. For that reason, a subchart cannot access the values of its parent.
> 3. A parent chart can override values for subcharts.
> 4. Helm has a concept of global values that can be accessed by all charts.
https://helm.sh/docs/chart_template_guide/subcharts_and_globals/

**Comment by astellingwerf** [comment]
Hmm, I'm slightly confused now: When rendering templates, it will use the override from the superchart. If so, I'd be tempted to say that it then also must those when linting.

**Comment by myk0la-b** [comment]
Hello @joejulian, my team and I experienced the same issue, exactly as @astellingwerf mentions it:
> When rendering templates, it will use the override from the superchart

While you mention that 
>  helm `lint . --with-subcharts` does, indeed, fail as expected

This is very confusing since helm lint treats subcharts as independent charts, while when the superchart is being rendered the subchart is not treated as independent chart. 
And the [documentation](https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#sharing-templates-with-subcharts) states next: 
> Parent charts and subcharts can share templates. Any defined block in any chart is available to other charts.

Now, this does not make sense. It's either should be or should not be possible to reference superchart's templates.

If it's allowed, then helm lint does not function correctly by not allowing to lint a chart with subcharts as a whole.

If it's not allowed, then the rendering of the templates is wrong.

Please reopen the issue.

Best regards,
Mykola

**Comment by myk0la-b** [comment]
@astellingwerf We were able to figure out what's going on there. Please see my pull request for documentation improvement. What do you think? Is it clear?

**Comment by iccole** [comment]
I've experienced this and while I understand why it happens, what's the guidance? Obviously linting should be a step. So is the guidance to not use the `--with-subcharts` flag? Or is it to ensure all subcharts are stand-alone and not to use global values? 

The behavior is pointing helm usage towards a particular pattern, except there's no acknowledgment on the "correct" way to helm.
