### ISSUE TITLE
Add TOML parsing capability

### ISSUE THREAD

**Issue by dominikmueller** [helm/helm#12024]
Currently, the standard library includes functions to parse data from [JSON and YAML](https://github.com/helm/helm/blob/main/pkg/engine/funcs.go#L50-L56), but there is no built-in function to parse data from [TOML](https://toml.io/).

Given that TOML is sometimes used as format for configuration files (e.g. [GitLab Runner configuration](https://docs.gitlab.com/runner/install/kubernetes.html#additional-configuration)), it would be beneficial to have a `fromToml` function in the standard library, like `fromJson` and `fromYaml`, to provide consistency for developers.

Example use case:
We want to deploy GitLab runners with helm and want to use Googles config-connector to create necessary GCS buckets for caching.
The bucket name therefore needs to be provided twice: in the config-connector resource and in the GitLab config TOML. 
To keep the config DRY, we want to be able to extract the GCS bucket name from GitLab's TOML configuration. This is not possible without parsing the TOML configuration.
Other solutions such as YAML anchors or reusing values in the same `values.yaml` file won't work either.

PS: I have a PR in the making. Just adding this issue to adhere to the contribution guidelines.

**Comment by joejulian** [comment]
Most of the go template functions available come from [masterminds/sprig](https://github.com/masterminds/sprig/). You might try there first.

**Comment by dominikmueller** [comment]
I added the TOML parsing in #12026 using the already available package [BurntSushi/toml](https://github.com/helm/helm/blob/17beedb49cc8d681b393f6e007f24b0b526717f4/pkg/engine/funcs.go#LL25C3-L25C29).

I tried to keep it identical to the other parsing implementations (`fromJson`, `toJson` etc.) - meaning I added the error return message etc.
And I tried to adopt to the existing `toToml` [implementation](https://github.com/helm/helm/blob/17beedb49cc8d681b393f6e007f24b0b526717f4/pkg/engine/funcs.go#L121-L133).


I can create another MR in masterminds/sprig if that is the future way to go. Just wondering if the other functions should therefore also be extracted to that dependency to stay consistent. Do you have an opinion on that?

**Comment by jouve** [comment]
@joejulian sprig has not had a new feature for almost 3 years, it looks abandoned

**Comment by joejulian** [comment]
It's not.
