### ISSUE TITLE
Use default fullname, name values without overriding in another chart

### ISSUE THREAD

**Issue by ishaan1091** [helm/helm#12032]
I am a bit new to helm and wasn't able to find a solution to this online. The problem I am facing is that I have the following helm charts

```
-- helm/charts
|--- mongodb
|--- service1
|--- service2
```
Now the service name for mongodb is ```{{ include mongodb.fullname . }}``` so it is dependent on chart name and release name. Now service1 and service2 both need the IP:PORT of mongodb service as their env variables. 

How can I get this in environment variables which is to be passed in spec.container.env in both service1 and service2

Output of `helm version`:
```
version.BuildInfo{Version:"v3.11.3", GitCommit:"66a969e7cc08af2377d055f4e6283c33ee84be33", GitTreeState:"clean", GoVersion:"go1.20.3"}
```

Output of `kubectl version`: 
```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:14:41Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:33:12Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/arm64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Minikube

**Comment by wujunwei** [comment]
You can write the variables（like .values.mongodb_fullname） that control these parameters to the global values of the parent package,then in subcharts, use something like `{{ .values.global.mongodb_fullname }}` or `{{ .values.global.mongodb_port }}` to get or use the services' name and port.

**Comment by ishaan1091** [comment]
I want the mongodb fullname to be the one defined by default in _helpers.tpl. I don't want to manually define it / hardcode it. I want it to be <release-name>-<chart-name>. If I define a values.yaml file in helm directory for declaring this variable then I will not be using the default fullname

That is why I can't use global values. Do you have any idea as to how I can proceed here?

**Comment by wujunwei** [comment]
All the methods I can think of need to hard coding "chart name" without using global values，Because they are in different charts

**Comment by joejulian** [comment]
I cheated. In my subchart, I added the ability to turn-off creating the deployment and instead I set up all my values and do:
```
{{ include (print .Subcharts.console.Template.BasePath "/deployment.yaml") $helmVars }}
```
in a template in the parent chart. It's a major cheat but it works beautifully.

https://github.com/redpanda-data/helm-charts/blob/redpanda-4.0.16/charts/redpanda/templates/console/deployment.yaml
