### ISSUE TITLE
Crash during helm upgrade --install

### ISSUE THREAD

**Issue by sambhav2411** [helm/helm#12057]
I am trying to upgrade install a helm chart. The helm chart has CRDs and pre-install hooks. The hook runs a Job, which does 'kubectl apply -f' and re-applies the CRDs. This is the helm chart - https://github.com/kubernetes-sigs/secrets-store-csi-driver/tree/main/charts/secrets-store-csi-driver

This is the stack trace -

`Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)goroutine 462 [running]:k8s.io/apimachinery/pkg/util/runtime.logPanic(0x29dde20, 0x39c6810) /go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/runtime/runtime.go:74
0x99k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0) /go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/runtime/runtime.go:48
0x89panic(0x29dde20, 0x39c6810) /usr/local/go/src/runtime/panic.go:969
0x1c7os.OpenFile(0xc000c67b80, 0x9e, 0x0, 0x0, 0x3a3ece0, 0x0, 0x9e) /usr/local/go/src/os/file.go:331
0xa2os.Open(...) /usr/local/go/src/os/file.go:307k8s.io/client-go/discovery/cached/disk.(*CachedDiscoveryClient).getCachedFile(0xc001c7df00, 0xc000c67b80, 0x9e, 0x0, 0x0, 0x0, 0x0, 0x0) /go/pkg/mod/k8s.io/client-go@v0.20.4/discovery/cached/disk/cached_discovery.go:146
0x138k8s.io/client-go/discovery/cached/disk.(*CachedDiscoveryClient).ServerResourcesForGroupVersion(0xc001c7df00, 0xc001a716e0, 0x1c, 0x2be9976, 0x1, 0xc00052db70) /go/pkg/mod/k8s.io/client-go@v0.20.4/discovery/cached/disk/cached_discovery.go:66
0x10ck8s.io/client-go/discovery.fetchGroupVersionResources.func1(0xc00052de80, 0x2e85aa0, 0xc001c7df00, 0xc001a703e0, 0x14, 0xc00052db70, 0x7, 0xc00052de90, 0xc0003e3f20, 0xc0003e3e90) /go/pkg/mod/k8s.io/client-go@v0.20.4/discovery/discovery_client.go:361
0xf2created by k8s.io/client-go/discovery.fetchGroupVersionResources /go/pkg/mod/k8s.io/client-go@v0.20.4/discovery/discovery_client.go:357`

Output of `helm version`:
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-13+d2965f0db10712", GitCommit:"d2965f0db1071203c6f5bc662c2827c71fc8b20d", GitTreeState:"clean", BuildDate:"2021-06-26T01:02:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14", GitCommit:"0f77da5bd4809927e15d1658fb4aa8f13ad890a5", GitTreeState:"clean", BuildDate:"2022-06-15T14:11:36Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by wujunwei** [comment]
Could you please offer some steps which can reproduce it ?

**Comment by sambhav2411** [comment]
This error is coming in our production setup. This is the helm chart we are trying to install - https://github.com/kubernetes-sigs/secrets-store-csi-driver/tree/main/charts/secrets-store-csi-driver.

This is happening very randomly and sets the helm chart status to pending-upgrade. The helm chart has CRDs and also, the helm chart has pre-install hooks . The pre-install hooks run a Job, which does 'kubectl apply -f crds/'. 

Can you offer some advice as in which flow can this happen ? Could this be during CRD installation or job run or any other flow ?

**Comment by sambhav2411** [comment]
This is happening pretty randomly in our production k8s cluster. This is the hooks code - https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/main/charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml. 

Also, this is directly giving stack trace from k8s, with no stack trace from helm code. But, this sets helm chart status to 'pending-upgrade'.  How is this possible ?

**Comment by sambhav2411** [comment]
Hey, This is one more stack trace -
panic: runtime error: invalid memory address or nil pointer dereference[signal 0xc0000005 code=0x0 addr=0x0 pc=0xb774e2]goroutine 1 [running]:os.OpenFile(0xc0013b9880, 0x7e, 0x0, 0x0, 0x311ece0, 0x0, 0x7e)    /usr/local/go/src/os/file.go:331 +0xa2os.Open(...)    /usr/local/go/src/os/file.go:307k8s.io/client-go/discovery/cached/disk.(*CachedDiscoveryClient).getCachedFile(0xc00111f0c0, 0xc0013b9880, 0x7e, 0x0, 0x0, 0x0, 0x0, 0x0)    /go/pkg/mod/k8s.io/client-go@v0.20.4/discovery/cached/disk/cached_discovery.go:146 +0x138k8s.io/client-go/discovery/cached/disk.(*CachedDiscoveryClient).ServerGroups(0xc00111f0c0, 0x24de41c, 0x22c9e04, 0x22d619d)    /go/pkg/mod/k8s.io/client-go@v0.20.4/discovery/cached/disk/cached_discovery.go:109 +0xe5k8s.io/client-go/discovery.ServerGroupsAndResources(0x2565aa0, 0xc00111f0c0, 0x0, 0x2030004, 0x0, 0x20, 0x2030008, 0x2030008, 0x0, 0x24de441)    /go/pkg/mod/k8s.io/client-go@v0.20.4/discovery/discovery_client.go:256 +0x5bk8s.io/client-go/discovery/cached/disk.(*CachedDiscoveryClient).ServerGroupsAndResources(0xc00111f0c0, 0x24de456, 0xc001168ed0, 0xa8dfb0, 0xc002018030, 0x30, 0x30, 0x220c200, 0xc00111f0c0)    /go/pkg/mod/k8s.io/client-go@v0.20.4/discovery/cached/disk/cached_discovery.go:102 +0x45k8s.io/client-go/restmapper.GetAPIGroupResources(0x2565aa0, 0xc00111f0c0, 0xc00111f0c0, 0x2565aa0, 0xc00111f0c0, 0x2560700, 0xc001169080)    /go/pkg/mod/k8s.io/client-go@v0.20.4/restmapper/discovery.go:148 +0x5bk8s.io/client-go/restmapper.(*DeferredDiscoveryRESTMapper).getDelegate(0xc002018060, 0x0, 0x0, 0x0, 0x0)    /go/pkg/mod/k8s.io/client-go@v0.20.4/restmapper/discovery.go:202 +0xc9k8s.io/client-go/restmapper.(*DeferredDiscoveryRESTMapper).RESTMapping(0xc002018060, 0x0, 0x0, 0xc00220ff10, 0xe, 0xc000d7b9f0, 0x1, 0x1, 0x2044f60, 0x1, ...)    /go/pkg/mod/k8s.io/client-go@v0.20.4/restmapper/discovery.go:286 +0x39k8s.io/client-go/restmapper.shortcutExpander.RESTMapping(...)    /go/pkg/mod/k8s.io/client-go@v0.20.4/restmapper/shortcut.go:71k8s.io/cli-runtime/pkg/resource.(*mapper).infoForData(0xc001fcfb30, 0xc001d68a80, 0x66, 0x70, 0x0, 0x0, 0x0, 0x6, 0x2030004)    /go/pkg/mod/k8s.io/cli-runtime@v0.20.4/pkg/resource/mapper.go:65 +0x4d8k8s.io/cli-runtime/pkg/resource.(*StreamVisitor).Visit(0xc00111ee80, 0xc002d4b1c0, 0x25bac3f05e0, 0x38)    /go/pkg/mod/k8s.io/cli-runtime@v0.20.4/pkg/resource/visitor.go:590 +0x1d0k8s.io/cli-runtime/pkg/resource.EagerVisitorList.Visit(0xc000d7a6c0, 0x1, 0x1, 0xc00111ef40, 0xc00111ef01, 0xc00111ef40)    /go/pkg/mod/k8s.io/cli-runtime@v0.20.4/pkg/resource/visitor.go:213 +0xd5k8s.io/cli-runtime/pkg/resource.FlattenListVisitor.Visit(0x250da00, 0xc002d4b0e0, 0x251e0a0, 0x311cba0, 0xc001fcfb30, 0xc00111ef00, 0x8, 0xc001169540)    /go/pkg/mod/k8s.io/cli-runtime@v0.20.4/pkg/resource/visitor.go:391 +0x8dk8s.io/cli-runtime/pkg/resource.FlattenListVisitor.Visit(0x250da40, 0xc001fcfb60, 0x251e0a0, 0x311cba0, 0xc001fcfb30, 0xc002d4b180, 0xa8dfb0, 0xc0011695f0)    /go/pkg/mod/k8s.io/cli-runtime@v0.20.4/pkg/resource/visitor.go:391 +0x8dk8s.io/cli-runtime/pkg/resource.ContinueOnErrorVisitor.Visit(0x250da40, 0xc001fcfbc0, 0xc00111eec0, 0xc000d7a601, 0xc00111eec0)    /go/pkg/mod/k8s.io/cli-runtime@v0.20.4/pkg/resource/visitor.go:354 +0xa3k8s.io/cli-runtime/pkg/resource.DecoratedVisitor.Visit(0x250d9c0, 0xc000d7a6e0, 0xc002d4b120, 0x3, 0x4, 0xc000d7a6f0, 0xc0021e1780, 0xc001169740)    /go/pkg/mod/k8s.io/cli-runtime@v0.20.4/pkg/resource/visitor.go:326 +0x8dk8s.io/cli-runtime/pkg/resource.(*Result).Infos(0xc0021e1780, 0xc0021e1780, 0x0, 0x0, 0x1, 0xc000d7a6c0)    /go/pkg/mod/k8s.io/cli-runtime@v0.20.4/pkg/resource/result.go:122 +0xcbhelm.sh/helm/v3/pkg/kube.(*Client).Build(0xc0002f9860, 0x2509720, 0xc001f71620, 0xc0009da801, 0x36ce, 0x3800, 0x10, 0x0, 0x0)    /home/circleci/helm.sh/helm/pkg/kube/client.go:186 +0x205helm.sh/helm/v3/pkg/action.(*Upgrade).performUpgrade(0xc000098f00, 0xc0007197a0, 0xc0004937a0, 0x1, 0x1, 0xc0007197a0)    /home/circleci/helm.sh/helm/pkg/action/upgrade.go:256 +0x342helm.sh/helm/v3/pkg/action.(*Upgrade).Run(0xc000098f00, 0xc000034800, 0x17, 0xc0007bd680, 0xc000c6fe90, 0x0, 0x0, 0x0)    /home/circleci/helm.sh/helm/pkg/action/upgrade.go:132 +0x29emain.newUpgradeCmd.func2(0xc00009b340, 0xc000460aa0, 0x2, 0xa, 0x0, 0x0)    /home/circleci/helm.sh/helm/cmd/helm/upgrade.go:155 +0x2e9github.com/spf13/cobra.(*Command).execute(0xc00009b340, 0xc000460960, 0xa, 0xa, 0xc00009b340, 0xc000460960)    /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x47cgithub.com/spf13/cobra.(*Command).ExecuteC(0xc0001dab00, 0xc0003822d0, 0x1, 0xc00079ff60)    /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375github.com/spf13/cobra.(*Command).Execute(...)    /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895main.main()    /home/circleci/helm.sh/helm/cmd/helm/helm.go:80 +0x24d

**Comment by wujunwei** [comment]
You can switch to the latest Helm. If there is still the same problem, I will track it.

**Comment by sambhav2411** [comment]
Thanks @wujunwei . We are using k8s version 1.21.14 in our production clusters. It is not possible to upgrade k8s version at this point. Is it still recommended to switch to latest helm.

Also, I was planning to use --atomic flag with helm upgrade --install, so that helm release status does not go to 'pending-upgrade', because we have a retry mechanism to retry installing helm charts on failure. The `pending-upgrade` state breaks the retry.

**Comment by wujunwei** [comment]
> We are using k8s version 1.21.14 in our production clusters. It is not possible to upgrade k8s version at this point. Is it still recommended to switch to latest helm

According to the [support version policy](https://helm.sh/docs/topics/version_skew/) of `helm` , the latest version does not support  **1.21**.

**Comment by sambhav2411** [comment]
Thanks @wujunwei . Let me switch to 3.9x. Also, is it recommended to use --atomic to prevent going into `pending-upgrade`.

**Comment by wujunwei** [comment]
> Thanks @wujunwei . Let me switch to 3.9x. Also, is it recommended to use --atomic to prevent going into `pending-upgrade`.

If this problem is reproduced in the future，feel free to let me know. ( It would be even better with stack trace then)

**Comment by wujunwei** [comment]
>  Also, is it recommended to use --atomic to prevent going into pending-upgrade.

See from the stack trace above, even you use `--atomic` . it 's panic here, Helm did not perform any recover logic, resulting in that subsequent rollback operations may not being executed either

**Comment by joejulian** [comment]
You're in a tough spot. Helm uses client-go for interfacing with the Kubernetes API. If you can use a modern kubectl, you should be able to use helm. I would try with the latest and see if it works. If it does, let us know if you can still hit that crash and we'll turn this into a bug report.

If it somehow fails, let us know. Maybe we can help.
