### ISSUE TITLE
`helm push`  invalid repository due to invalid chart name

### ISSUE THREAD

**Issue by way-zer** [helm/helm#12055]
Output of `helm version`:  `version.BuildInfo{Version:"v3.11.3", GitCommit:"66a969e7cc08af2377d055f4e6283c33ee84be33", GitTreeState:"clean", GoVersion:"go1.20.3"}`

Output of `kubectl version`: `
```
kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"archive", BuildDate:"2023-04-15T11:34:19Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8", GitCommit:"a12b886b1da059e0190c54d09c5eab5219dd7acf", GitTreeState:"clean", BuildDate:"2022-06-16T05:51:36Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.27) and server (1.23) exceeds the supported minor version skew of +/-1
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  K8s installed by kubekey

## Problem
when use `helm push` with invalid chart name, output confusing error `Error: invalid_reference: invalid repository`
Example:
```shell
helm package .
# Successfully packaged chart and saved it to: .../Workspace-0.4.4.tgz
helm push Workspace-0.4.4.tgz oci://harbor.example.com/library
# Error: invalid_reference: invalid repository
# change the chart name to `workspace`, it works.
```
It took a lot of time to troubleshoot until found #12025

**Comment by SumantxD** [comment]
@way-zer does solving this issue involves allowance of Capital letters in the repository name by modifying the regular expression, if so i would like to work on it , can you assign me this issue?

**Comment by way-zer** [comment]
First, I think it should output the correct error message when name invalid.
Then, I search the `oci` spec. 
> <name> MUST match the following regular expression:
> `[a-z0-9]+([._-][a-z0-9]+)*(/[a-z0-9]+([._-][a-z0-9]+)*)*`
> <reference> as a tag MUST be at most 128 characters in length and MUST match the following regular expression:
> `[a-zA-Z0-9_][a-zA-Z0-9._-]{0,127}`

**Comment by joejulian** [comment]
This is where helm calls oras's ParseRegistry. The error message comes from oras.
https://github.com/helm/helm/blob/2398830f183b6d569224ae693ae9215fed5d1372/pkg/registry/util.go#L138

Since the error you see is all the error we receive, a change would be needed upstream to address your request.

**Comment by kycheng** [comment]
I encountered a similar problem, but the error was an invalid tag.

```sh
# ./helm
version.BuildInfo{Version:"v3.12.2", GitCommit:"1e210a2c8cc5117d1055bfaa5d40f51bbc2e345e", GitTreeState:"clean", GoVersion:"go1.20.5"}
# ./helm  push chart-v3.14.0.tgz oci://registry.com/test/chart:1
Error: invalid_reference: invalid tag
```
Check the code of oras, it should be able to identify correctly.

Is it because oci://registry.com/test/chart:1 is passed in at the following location?

[check ](https://github.com/helm/helm/blob/2398830f183b6d569224ae693ae9215fed5d1372/pkg/registry/util.go#L138)
