### ISSUE TITLE
Allow for icons to be files in local repository

### ISSUE THREAD

**Issue by alonsocamaro** [helm/helm#12058]
Is this a request for help?: No

Is this a BUG REPORT or FEATURE REQUEST? (choose one): FEATURE REQUEST
Currently in the Chart.yaml file the icon attribute must be a URL. Instead of pointing to another place, I (also) would like to have the option to store the icon together with the Chart.yaml file in the same directory. So, the URL can also be a (relative) file path w.r.t. the Chart.yaml directory.

Version of Helm and Kubernetes: Helm3

Which chart: Any

What happened: n/a

What you expected to happen: n/a

How to reproduce it (as minimally and precisely as possible): n/a

Anything else we need to know: -

This is a copy of https://github.com/helm/charts/issues/7904 because the repository has been obsoleted

Looking into https://github.com/helm/helm/issues/1034 maybe the way to solve the inconveniences indicated would be that the helm repo index command could extract the image files automatically

**Comment by SumantxD** [comment]
@alonsocamaro I would like to work on this issue, 
Correct me if i am wrong, but this is my current understanding of the issue :-
1) there are several Chart.yaml files in the codebase with (icon: https://example.png)
2) apart from the above approach there should also be the option to store icon in the same directory as that of Chart.yaml file 
3) and we can access those icons through relative paths

--> If my understanding is not wrong 
1) do you want me to refactor all the Chart.yaml file directory and include an icon.svg in their root directory, and refer then through relative paths
2) and after that add a documentation that would standardize the process of adding icons , by the further contribuers

**Comment by joejulian** [comment]
I'm intrigued. What tool would find that useful? Packaged charts are tarballs so I'm really curious how something that could display the icon would reach it.
