### ISSUE TITLE
The quick start guide docs doesn’t allow for scrolling

### ISSUE THREAD

**Issue by jmrnilsson** [helm/helm#12060]
The docs over at https://helm.sh/docs/intro/cheatsheet/ has a transient error so it doesn’t allow for scrolling up or down on IOS Safari. It’s pretty bad.  

Same goes for Firefox on IOS..

**Comment by z4ce** [comment]
Can you close this issue and open a new one under helm/helm-www?

**Comment by jmrnilsson** [comment]
Sure. It’s been done! Thanks.

https://github.com/helm/helm-www/issues/1464
