### ISSUE TITLE
Method engine.Render fails to parse a template with default values

### ISSUE THREAD

**Issue by Subhajit97** [helm/helm#12068]
Hi! I'm trying to render a template with the default values configured in the `Values.yaml` file before installing the chart. I'm using the [engine.Render()](https://pkg.go.dev/helm.sh/helm/v3@v3.11.3/pkg/engine#Render) method to perform the rendering.

I have passed the chart, as well as the values set in the `Values.yaml` file. Below is the code snippet that I'm using:

```
// Load the chart from the specified path
chart, err := loader.Load("path/to/chart")
if err != nil {
	os.Exit(1)
}

// Read the default values.yaml file of the chart
valuesBytes, err := os.ReadFile("path/to/values.yaml")
if err != nil {
	os.Exit(1)
}

values, err := chartutil.ReadValues(valuesBytes)
if err != nil {
	os.Exit(1)
}

renderedChart, err := engine.Render(chart, values)
if err != nil {
	fmt.Printf("render_error: %v", err)
	os.Exit(1)
}
```

And, using the above code, I'm getting the below error:
```
render_error: template: <template_relative_path>:10:23: executing "<template_relative_path>" at <.Values.vault.namespace>: nil pointer evaluating interface {}.vault exit status 1
```
But the file `Values.yaml` has the value configured for `vault.namespace`:
```
vault:
  namespace: vault
```

Is there anything I'm missing here, or it's a bug?

Output of `helm version`:
```
version.BuildInfo{Version:"v3.11.3", GitCommit:"66a969e7cc08af2377d055f4e6283c33ee84be33", GitTreeState:"clean", GoVersion:"go1.20.3"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:14:41Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:33:12Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/arm64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): `Minikube`

**Comment by joejulian** [comment]
Does your chart have subcharts? Maybe you could create an example chart and attach it to this issue so we can see what you're up against.

**Comment by fardin01** [comment]
@joejulian I came across this issue as well. You can reproduce it using OPA GateKeeper chart [here](https://github.com/open-policy-agent/gatekeeper/tree/master/charts/gatekeeper).

```
render_error: template: gatekeeper/templates/webhook-configs-pre-delete.yaml:1:27: executing "gatekeeper/templates/webhook-configs-pre-delete.yaml" at <.Values.disableValidatingWebhook>: nil pointer evaluating interface {}.disableValidatingWebhook
```

**Comment by joejulian** [comment]
Render expects `values`  to have the values under a `Values` key:

Tangentially, your example should lose the chart's default values. This example should get what you're looking for, I think.

```
package main

import (
	"fmt"
	"os"

	"helm.sh/helm/v3/pkg/chart/loader"
	"helm.sh/helm/v3/pkg/chartutil"
	"helm.sh/helm/v3/pkg/engine"
)

func main() {
	// Load the chart from the specified path
	chart, err := loader.Load(".")
	if err != nil {
		os.Exit(1)
	}

	// Read the default values.yaml file of the chart
	fileValues, err := chartutil.ReadValuesFile("./values.yaml")
	if err != nil {
		os.Exit(1)
	}
	coalescedValues := chartutil.CoalesceTables(chart.Values, fileValues)
	values := map[string]interface{}{
		"Values": coalescedValues,
	}

	renderedChart, err := engine.Render(chart, values)
	if err != nil {
		fmt.Printf("render_error: %v", err)
		os.Exit(1)
	}
	fmt.Println(renderedChart)
}
```

You might also consider using https://github.com/helm/helm/blob/ad1fd058ad990760c75515eb9867dfd527b3cc3c/pkg/cli/values/options.go#L42-L44 in place of loading the values yourself.

**Comment by Subhajit97** [comment]
Thanks, @joejulian! It works when I pass the values using the `Values` key.

I was trying to parse a few templates defined in this chart: https://github.com/bitnami/charts/tree/main/bitnami/redis

But I'm getting the below error:
```
Error: template: redis/templates/replicas/statefulset.yaml:2:15: executing "redis/templates/replicas/statefulset.yaml" at <include "common.capabilities.statefulset.apiVersion" .>: error calling include: template: redis/charts/common/templates/_capabilities.tpl:77:7: executing "common.capabilities.statefulset.apiVersion" at <semverCompare "<1.14-0" (include "common.capabilities.kubeVersion" .)>: error calling semverCompare: Invalid Semantic Version (SQLSTATE HV000)
```

Is there anything I need to pass in the code?

**Comment by joejulian** [comment]
Honestly, I think if I was going to do this I'd start here and implement a stripped down version of runInstall:
https://github.com/helm/helm/blob/1c4885fce74d44b94a8b100f660cca4cc633176c/cmd/helm/template.go#LL88C20-L88C20
