### ISSUE TITLE
v3.12.0 Failed deployments

### ISSUE THREAD

**Issue by vikaskoppineedi** [helm/helm#12071]
Output of `helm version`: version.BuildInfo{Version:"v3.12.0", GitCommit:"c9f554d75773799f72ceef38c51210f1842a1dea", GitTreeState:"clean", GoVersion:"go1.20.3"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  EKS. 

In our pipelines , we download the latest version of helm3 and use it for deployments.  Starting with three hours ago, our deployments started failing with the following error. 

```
Error: UPGRADE FAILED: error validating "": error validating data: the server responded with the status code 426 but did not return more information
```

I reverted to the last working version of helm in our pipelines ( v3.11.3 )  and our pipelines are working now. 

```
curl -L https://git.io/get_helm.sh | bash -s -- --version v3.11.3
```

**Comment by joejulian** [comment]
Was this with any particular repo or oci reference?

**Comment by dlq84** [comment]
I have the same issue, It doesn't seem to have anything to do with any helm repo. I'm using it to deploy a local (on-disk) helm chart. Seems to have something to do with the connection to the cluster.

**Comment by mattfarina** [comment]
What version of Kubernetes are y'all using?

**Comment by joejulian** [comment]
possibly related: https://forum.gitlab.com/t/cicd-pipeline-stops-working-status-code-426/84908

**Comment by dlq84** [comment]
> What version of Kubernetes are y'all using?

I've used it both 1.24 and 1.25, same issue on both.

**Comment by vikaskoppineedi** [comment]
yes I am on k8s 1.25.

**Comment by joejulian** [comment]
I can't duplicate this problem. I've tried as far back as 1.21 but it works every time.

**Comment by joejulian** [comment]
Maybe try setting `GODEBUG=http2debug=1` and see if you can find something to explain what it's trying to upgrade the connection to.

**Comment by joejulian** [comment]
I've also tried this on EKS.

Really need more details if you can get them. Not sure what's different between what I'm trying and what's causing this error.

**Comment by gaby** [comment]
I also had someone report the same error as @vikaskoppineedi the error doesnt happen with latest 3.11.x release

Rel https://github.com/dtzar/helm-kubectl/issues/136

**Comment by ceefour** [comment]
Happened to me too:

```
Error: UPGRADE FAILED: error validating "": error validating data: the server responded with the status code 426 but did not return more information
```

Downgrading to Helm 3.11 "fixed" the issue.

**Comment by MaxWinterstein** [comment]
@joejulian added debug variable to my CI and upgraded to 3.12 again. Debug log is huge, and i am not really into go, but this looks intresting to me:

```go
[000:11] h2_bundle.go:9019: http2: Transport encoding header ":authority" = "my-gitlab-kas.example.org"
[000:11] h2_bundle.go:9019: http2: Transport encoding header ":method" = "GET"
[000:11] h2_bundle.go:9019: http2: Transport encoding header ":path" = "/k8s-proxy/openapi/v3?timeout=32s"
[000:11] h2_bundle.go:9019: http2: Transport encoding header ":scheme" = "https"
[000:11] h2_bundle.go:9019: http2: Transport encoding header "authorization" = "Bearer ci:3:[MASKED]"
[000:11] h2_bundle.go:9019: http2: Transport encoding header "accept" = "application/json, */*"
[000:11] h2_bundle.go:9019: http2: Transport encoding header "user-agent" = "Helm/3.12.0"
[000:11] h2_bundle.go:9019: http2: Transport encoding header "accept-encoding" = "gzip"
[000:11] h2_bundle.go:9968: http2: Transport received HEADERS flags=END_HEADERS stream=121 len=88
[000:11] h2_bundle.go:9968: http2: Transport received DATA stream=121 len=7029 data="XXX" (6773 bytes omitted)
[000:11] h2_bundle.go:9968: http2: Transport received DATA flags=END_STREAM stream=121 len=10 data="XXX"
[000:11] h2_bundle.go:9019: http2: Transport encoding header ":authority" = "my-gitlab-kas.example.org"
[000:11] h2_bundle.go:9019: http2: Transport encoding header ":method" = "GET"
[000:11] h2_bundle.go:9019: http2: Transport encoding header ":path" = "/openapi/v3/api/v1?hash=some-hash&timeout=32s"
[000:11] h2_bundle.go:9019: http2: Transport encoding header ":scheme" = "https"
[000:11] h2_bundle.go:9019: http2: Transport encoding header "authorization" = "Bearer ci:3:[MASKED]"
[000:11] h2_bundle.go:9019: http2: Transport encoding header "accept" = "application/json"
[000:11] h2_bundle.go:9019: http2: Transport encoding header "user-agent" = "Helm/3.12.0"
[000:11] h2_bundle.go:9019: http2: Transport encoding header "accept-encoding" = "gzip"
[000:11] h2_bundle.go:9968: http2: Transport received HEADERS flags=END_HEADERS stream=123 len=41
[000:11] h2_bundle.go:9968: http2: Transport received DATA stream=123 len=76 data="WebSocket protocol violation: Connection header \"\" does not contain Upgrade\n"
[000:11] h2_bundle.go:9968: http2: Transport received DATA flags=END_STREAM stream=123 len=0 data=""
[000:11] Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: the server responded with the status code 426 but did not return more information
[000:11] helm.go:84: [debug] error validating "": error validating data: the server responded with the status code 426 but did not return more information
[000:11] helm.sh/helm/v3/pkg/kube.scrubValidationError
[000:11] helm.sh/helm/v3/pkg/kube/client.go:809
```

In particular this one:
```
data="WebSocket protocol violation: Connection header \"\" does not contain Upgrade\n"
```

As said, there is KAS running in my case: https://docs.gitlab.com/ee/administration/clusters/kas.html

Throwing the same command directly against my cluster works fine.

**Comment by Mdumala** [comment]
I hade the same problem .

First i thought it could be due to https://gitlab.com/gitlab-org/gitlab/-/issues/407161

But i'm using helm to deploy to kubernetes ( with KAS and gitlab runner)

Error from --debug 

> Error: UPGRADE FAILED: error validating "": error validating data: the server responded with the status code 426 but did not return more information
> helm.go:84: [debug] error validating "": error validating data: the server responded with the status code 426 but did not return more information
> helm.sh/helm/v3/pkg/kube.scrubValidationError
> 	helm.sh/helm/v3/pkg/kube/client.go:809
> helm.sh/helm/v3/pkg/kube.(*Client).Build
> 	helm.sh/helm/v3/pkg/kube/client.go:350
> helm.sh/helm/v3/pkg/action.validateManifest
> 	helm.sh/helm/v3/pkg/action/upgrade.go:539
> helm.sh/helm/v3/pkg/action.(*Upgrade).prepareUpgrade
> 	helm.sh/helm/v3/pkg/action/upgrade.go:267
> helm.sh/helm/v3/pkg/action.(*Upgrade).RunWithContext
> 	helm.sh/helm/v3/pkg/action/upgrade.go:151
> main.newUpgradeCmd.func2
> 	helm.sh/helm/v3/cmd/helm/upgrade.go:207
> github.com/spf13/cobra.(*Command).execute
> 	github.com/spf13/cobra@v1.6.1/command.go:916
> github.com/spf13/cobra.(*Command).ExecuteC
> 	github.com/spf13/cobra@v1.6.1/command.go:1044
> github.com/spf13/cobra.(*Command).Execute
> 	github.com/spf13/cobra@v1.6.1/command.go:968
> main.main
> 	helm.sh/helm/v3/cmd/helm/helm.go:[83](https://gitlab.com/iuniqa/iuniqa-code/-/jobs/4274577078#L83)
> runtime.main
> 	runtime/proc.go:250
> runtime.goexit
> 	runtime/asm_amd64.s:1598
> UPGRADE FAILED
> main.newUpgradeCmd.func2
> 	helm.sh/helm/v3/cmd/helm/upgrade.go:209
> github.com/spf13/cobra.(*Command).execute
> 	github.com/spf13/cobra@v1.6.1/command.go:916
> github.com/spf13/cobra.(*Command).ExecuteC
> 	github.com/spf13/cobra@v1.6.1/command.go:1044
> github.com/spf13/cobra.(*Command).Execute
> 	github.com/spf13/cobra@v1.6.1/command.go:968
> main.main
> 	helm.sh/helm/v3/cmd/helm/helm.go:83
> runtime.main
> 	runtime/proc.go:250
> runtime.goexit
> 	runtime/asm_amd64.s:15[98](https://gitlab.com/iuniqa/iuniqa-code/-/jobs/4274577078#L98)
> Cleaning up project directory and file based variables
> 00:01
> ERROR: Job failed: exit code 1

So i wrote my own docker image with helm version 3.11.3 and everything is fine for now

**Comment by vikaskoppineedi** [comment]
Do we have anything in common? are we all on GitLab?

**Comment by joejulian** [comment]
for gitlab's proxy, this is very likely related: https://gitlab.com/gitlab-org/gitlab/-/issues/407161

**Comment by joejulian** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/117495 and picked into release-1.27 which is due for a release any day now.

**Comment by joejulian** [comment]
Kubernetes patch release scheduled for 2023-05-17

**Comment by gaby** [comment]
Is this fix with with 1.27.2 ?

**Comment by joejulian** [comment]
Can I get someone who's facing this issue to test with #12096 and report on the PR, please?

**Comment by joejulian** [comment]
@vikaskoppineedi @gaby @Mdumala @MaxWinterstein @ceefour Can one of you test the PR?

**Comment by cglacet** [comment]
That's super strange, I have the same pipeline for my staging and production clusters (using gitlab agents). It works well in my staging cluster, but fails in the production one.

I used to have a slightly older server version of Kubernetes in production (1.24.xx vs. 1.25.4-2), so I though maybe this is the issue and update my production (now its 1.25.9-0) but I still have the same error. 

I haven't tried yet to change the helm image used to build but for now I'm using `devth/helm`.

There is a slight other difference between my production and staging because staging is the cluster that runs all my pipelines (including the production). So I have a litle bit more config in my production pipeline, something like this:

```yaml

k8s-deploy-production:
    stage: deploy
    image: devth/helm
    variables:
        KUBE_CONTEXT: production
    environment:
        name: production
        kubernetes:
            namespace: production-app-x
    script:
        - kubectl config get-contexts
        - kubectl config use-context project_path/production-app-x:production
        - helm template ...
        - helm upgrade ...
``` 

I'll try to change the version of `devth/helm` I'm using tomorow and see if that solves the issue.

**Comment by MaxWinterstein** [comment]
@joejulian #12096 does the job for me.

```bash

    curl -Ss https://dl.google.com/go/go1.20.4.linux-amd64.tar.gz | tar -C /usr/local -xzf-
    mv /usr/local/go/bin/go /usr/local/bin/
    
    git clone https://github.com/joejulian/helm.git
    cd helm

    git checkout client-go
    make
    cp bin/helm /usr/local/bin/

    helm version
```
```go
version.BuildInfo{Version:"v3.11+unreleased", GitCommit:"54ca3a82c289907a691539f8e25c2d92ae068ba3", GitTreeState:"clean", GoVersion:"go1.20.4"}

```

**Comment by gaby** [comment]
@cglacet Did you try the 3.12 one though?

**Comment by lucj** [comment]
I had the issue with 3.12.0, it seems to work fine with 3.12.1
