### ISSUE TITLE
curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3    curl: (22) The requested URL returned error: 403 Forbidden

### ISSUE THREAD

**Issue by lakshminarayanankp** [helm/helm#12089]
I have an issue in downloading the file from the repo, i have statement on my Dockerfile and it fails to download.

#12 [8/8] RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3     && chmod +x get_helm.sh && ./get_helm.sh
#12 0.526 curl: (22) The requested URL returned error: 403 Forbidden
#12 ERROR: process "/bin/sh -c curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3     && chmod +x get_helm.sh && ./get_helm.sh" did not complete successfully: exit code: 22
------
 > [8/8] RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3     && chmod +x get_helm.sh && ./get_helm.sh:
#12 0.526 curl: (22) The requested URL returned error: 403 Forbidden
------
Dockerfile:21
--------------------
  20 |     
  21 | >>> RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 \
  22 | >>>     && chmod +x get_helm.sh && ./get_helm.sh
  23 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3     && chmod +x get_helm.sh && ./get_helm.sh" did not complete successfully: exit code: 22
Cleaning up project directory and file based variables
00:00
ERROR: Job failed: exit status 1

**Comment by yxxhero** [comment]
@lakshminarayanankp I can't reproduce your issue. please check your network.

**Comment by joejulian** [comment]
Looks like a network issue on your end. I'm sorry but we cannot help with that.
