### ISSUE TITLE
ingress created by helm is not opening in the browser

### ISSUE THREAD

**Issue by Subhasish5** [helm/helm#12083]
Hi Team,

I created a helmrelease by applying the helmrelease.yml file from my local in a given namespace and it created the pods, svcs and ingress as well.

The kubernetes pod is not running because it's failing crashloopbackoff and the ingress is not loading in the browser.

Can you help.

Thanks and Regards,
Subhasish

**Comment by NeodymiumFerBore** [comment]
How do you want your Ingress to respond anything if your app is crashed?

**Comment by joejulian** [comment]
This is not a topic we can help with in helm issues. Helm installed what it was configured to install. I suggest checking with the chart or application provider.
