### ISSUE TITLE
Feature request: Dedicated command to set values on an existing release

### ISSUE THREAD

**Issue by tomdcc** [helm/helm#12097]
Hi

We distribute our application as a helm chart and images that it links to. The app is installed in a wide variety of target environments, from single-node k3s installations in a VM to multi-node fully managed cloud k8s clusters, and everything in between. The devops / operational rigor varies similarly - some customers have everything version controlled and driven by infrastructure, some have very manual but very locked down processes, others are just trialling our product in a throwaway environment and may not be familiar with k8s or helm at all, and don't need or want any particular process around config management.

We see some evidence of customers accidentally upgrading the version of the app when they only intend to change some config value. We talk about this in our documentation, but it's easy for someone not familiar with helm to assume that if they're running e.g. `helm upgrade --reuse-values` and don't specify an updated version, that they won't get an updated version. For our app this can be particularly problematic as running a newer version will often migrate database schemas or mutate internal configuration data in a way that makes downgrading to the intended version a backup restore rather than a simple rerun of `helm`.

There are a few problems with using `helm upgrade` when you just want to change some config:
- Running `helm upgrade` just to change a config value is counter-intuitive and confusing to new users. This is a common operation and deserves its own non-confusing command.
- As described above the parameters may lead a user not familiar with helm to think that they won't be altering the version when they will end up doing so.
- Users who don't make that mistake may nonetheless simply forget to put the existing release's version in the command. We go to a lot of effort to validate that user-supplied config will result in a valid installation and fail at `helm install/upgrade/template` time if something is missing or wrong, but we have no defense against a user accidentally omitting the chart version.
- Given the above, the penalty for a missed parameter is a broken system rather than a failed helm command.

A safe, intuitive way to set values on an existing release without an accidental application upgrade being in the picture would be a big step forward for usability when doing this. The proposed command would look something like:

```
helm set values «release-name» [... values]
```

So e.g. 
```
helm set values my-release -f values.yaml --set foo=bar --set-file cert.key=some-cert.key
```

- `set values` chosen given the existing `get values` and `show values` commands.
- My understanding is that a release stores the source of the chart installed, so the "chart source" would not be necessary. But if that's not correct or if we'd like to allow overrides regardless, the source and version could be specified as per `helm upgrade`. In that instance, the chart name and version would be checked against the those stored in the release and the command would fail if they don't match.
- `--reuse-values` would be implied, but could be changed using `--reset-values`.
- Post renderers would still need to be specified if used.

(#11546 raised a similar concept but was still talking about altering existing install / upgrade commands and was trying to solve a different problem (multiple users modifying the same release) and was probably rightly told that they had a process issue. The above issues weren't raised or considered.)

**Comment by joejulian** [comment]
The release artifact does not store the chart, it only stores the rendered manifest, the hooks, the notes, and the values.

**Comment by tomdcc** [comment]
Poking around in there I can see templates under `chart.templates`. It _looks_ like everything... This is helm 3.11.1.

But even if that weren't the case, such a command would still be valuable even if the chart source still had to be referenced.

**Comment by joejulian** [comment]
Nice. I was wrong. It doesn't hold any subcharts though.

I saw someone else, once, working on a similar idea. The chart metadata is in there and a feature could certainly be developed that used the chart version. The chart reference isn't in there though. That would need to be added.

I balk at adding something large as we already have a lot of users hitting the size limit of secrets.

If you would like to contribute something like this, I think that could be pretty useful.

**Comment by dberardo-com** [comment]
this feature would be a must!! 

many times i install helm chart from local folders which are located on remote machines ... so how could i then update the values from the local machine if there is no chart folder on it ??? 

any workaround as of today?
