### ISSUE TITLE
Helm release exists in all namespaces, but not in its namespace

### ISSUE THREAD

**Issue by ImIOImI** [helm/helm#12098]
Output of `helm version`:
version.BuildInfo{Version:"v3.12.0", GitCommit:"c9f554d75773799f72ceef38c51210f1842a1dea", GitTreeState:"clean", GoVersion:"go1.20.4"}

^^^Installed via brew

Output of `kubectl version`:
Client Version: v1.27.1
Kustomize Version: v5.0.1
Server Version: v1.26.3

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS remote version 1.26

I am attempting to delete a helm chart that had an outdated api (autoscaling/v2beta1) after updating the cluster to 1.26 and I was only partially successful after modifying the associated release secret with the outdated API. When I run 
```
helm list -A
```

| NAME  | NAMESPACE |REVISION | UPDATED |STATUS |
|---|---|---|---|---|
|gateway-schema-xxxx   |xxxx   |14   | 2023-04-19 20:58:49.397744128 +0000 UTC   | deployed  |

This shows the release at version 14 (it was at version 42 before I uninstalled it). So it must have gotten rolled back a couple months?

However, when I try to list it or any resources in the xxxx namespace it doesn't show the release that was listed above
```
helm list -n <release namespace>
```

Furthermore:
```
❯ helm get all gateway-schema-xxxx
Error: release: not found
❯ helm get all gateway-schema-xxxx-n xxxx
Error: release: not found
```

Further inspection of all "normal" resources (secrets, configmaps, deployments, services, hpas, etc) associated with the helm chart seems to indicate that they're all gone.

If I try installing the chart again (with the updated API) I get the following error:

```
Error: UPGRADE FAILED: unable to build kubernetes objects from current release manifest: resource mapping not found for name: "gateway-schema-testclub-sumer-app" namespace: "" from "": no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta2"
ensure CRDs are installed first
```

For completeness:
```
❯ helm mapkubeapis gateway-schema-xxxx -n xxxx
2023/05/23 14:01:57 Release 'gateway-schema-xxxx' will be checked for deprecated or removed Kubernetes APIs and will be updated if necessary to supported API versions.
2023/05/23 14:01:57 Get release 'gateway-schema-xxxx' latest version.
Error: failed to get release 'gateway-schema-xxxx' latest version: release: not found
Error: plugin "mapkubeapis" exited with error
❯ helm del gateway-schema-xxxx -n xxxx
Error: uninstall: Release not loaded: gateway-schema-xxxx: release: not found
```

It feels like there is some persistent memory of a previous release that exists somewhere on the cluster, and I just can't find it. My ultimate goal is to reinstall the helm chart. At this point I don't care about history or anything like that. Any help towards that end would be appreciated.

**Comment by ImIOImI** [comment]
> It would be a secret. `kubectl get secret -A -l owner=helm` will find it.

Ok, I feel like an idiot now... the secret was in a different namespace than the one the helm chart was installed in. I must have fumbled something while attempting to delete and reinstall the chart. Once I deleted the secret in the wrong namespace, everything functioned normally. I have so many helm charts with so many releases and secrets I'm not surprised that I missed it, but that's certainly an aggravating error.

**Comment by joejulian** [comment]
Glad that solved it for you!
