### ISSUE TITLE
Control <CHART>.fullname template in child package

### ISSUE THREAD

**Issue by bebosudo** [helm/helm#12101]
I'm writing a Helm chart (e.g. `mysoftware`) that uses bitnami/mysql as a dependency, which uses [`common.names.fullname`](https://github.com/bitnami/charts/blob/358ca646a20a7af6bd892802dd4caeb186cfdc46/bitnami/common/templates/_names.tpl#L16-L32) to name its objects (a clone of the default [`<CHARTNAME>.fullname`](https://github.com/helm/helm/blob/2398830f183b6d569224ae693ae9215fed5d1372/pkg/chartutil/create.go#L437-L448) function).

As you probably already know, that function has the advantage/drawback of "adapting" the name of the objects depending on the release name used: so if I'm installing my chart as release `mysoftware`, that `.fullname` function will return a name like `mysoftware-mysql`; but if I'm installing a release called `mysoftware-with-mysql8`, that function will return `mysoftware-with-mysql8` as the name for the mysql objects that will be created.
This makes reusing components of child charts more difficult (e.g. to look up values inside secrets created by the child chart).

I can control this by defining the value `mysql.fullnameOverride=mysoftware-mysql`, and every time the mysql dependent chart will call the `.fullname` function it will return that value.
I'd like to keep the release name though, to differentiate what's being installed in a namespace.
If I use `mysql.nameOverride=mysql` I'm back at step 1, because `.fullname` will check if the value `mysql` is contained within my release and if so, will not add `-mysql` at the end.

Is there a way to "force" a child chart's `.fullname` function to create objects with a certain suffix, no matter what the release name is called?

One alternative I just thought of is to create a template `dependent-mysql-name` that also checks if `mysql` is part of the release name and, if so, return just the release name, otherwise return the full `<releasename>-mysql`, mimicking what's done in `.fullname`. Are there other options?

Let me know if this isn't clear. I couldn't find similar issues or a section in the docs, but feel free to tell me to RTFM.

---

Output of `helm version`:
```
version.BuildInfo{Version:"v3.11", GitCommit:"", GitTreeState:"", GoVersion:"go1.19.6"}
```

Output of `kubectl version`:
```
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:21:19Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.9-eks-0a21954", GitCommit:"eb82cd845d007ae98d215744675dcf7ff024a5a3", GitTreeState:"clean", BuildDate:"2023-04-15T00:37:59Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.27) and server (1.25) exceeds the supported minor version skew of +/-1
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
EKS

**Comment by bebosudo** [comment]
I created the following template:
```go
{{/* Check if a chart name is contained inside a release, and return the release if so, or return
     the concatenation <releaseName>.<chartName>, to mimic what common.names.fullname does.
     Useful when working on child charts, which change their fullname depending on the parent chart.
     E.g. if you install the release 'mysoftware-with-mysql8', the mysql fullname will return just the
     release name, because 'mysql' is already stored inside the release.

     Example usage:
     {{ include "fullnameForChart" (dict "chartName" "mysql" "releaseName" .Release.Name) }}
*/}}
{{- define "fullnameForChart" -}}
{{- if contains .chartName .releaseName -}}
  {{- .releaseName | trunc 63 | trimSuffix "-" -}}
{{- else -}}
  {{- printf "%s-%s" .releaseName .chartName | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
```

Usage is `include "fullnameForChart" (dict "chartName" "mysql" "releaseName" .Release.Name)` and it will return the fullname that the child chart used (in this case `mysql`), depending on your release name.

I use it whenever I need to refer to something that the child chart created, e.g. to return the service name for mysql when in replication mode or not, or when an external db is provided I use it like so:
```go
{{/* Return the MySQL Hostname */}}
{{- define "mysoftware.databaseHost" -}}
{{- if .Values.mysql.enabled }}
  {{- if eq .Values.mysql.architecture "replication" }}
    {{- printf "%s-%s" (include "fullnameForChart" (dict "chartName" "mysql" "releaseName" .Release.Name)) "primary" -}}
  {{- else -}}
    {{- include "fullnameForChart" (dict "chartName" "mysql" "releaseName" .Release.Name) -}}
  {{- end -}}
{{- else -}}
  {{- print .Values.externalDatabase.host -}}
{{- end -}}
{{- end -}}
```

I'm still interested in hearing your opinion though.

**Comment by joejulian** [comment]
I think that's a pretty creative solution. I like it!

**Comment by bebosudo** [comment]
I later discovered that this is already included in bitnami/common:
https://github.com/bitnami/charts/blob/1db7ab9676df504d27f49b76c6df7047c84859b0/bitnami/common/templates/_names.tpl#L39-L57
Closing this issue.
