### ISSUE TITLE
Avoid Helm accessing remote repository during helm dependency build

### ISSUE THREAD

**Issue by nosalan** [helm/helm#12107]
I have an umbrella chart that has 2 subcharts: 1 reference to another chart on local filesystem (common-templates) and  1 chart archive in tgz format (redis) and. This is how these 2 dependencies are defined: 

![image](https://github.com/helm/helm/assets/2273250/d4ced1b6-d0d5-4aff-8592-ba266782fa9e)

In order for helm to use the subchart from the local filesystem (`common-templates`) I need to run the `helm dependency build` during deployment time because it's convenient that way to load the latest 'common-templates' from the same repository. However, this command also tries to update the first chart (redis) and connect to remote `https://charts.bitnami.com/bitnami` registry. 

I would like to avoid that because there's no internet access on the deploy agent. Is there a way to use `helm dependency build` for specific (local) chart only and skip the remote one because there already is tgz file for it in charts dir?

Tried this but it seems it's not supported:
![image](https://github.com/helm/helm/assets/2273250/e6bf5f48-2890-41b2-946b-18b512b844f8)

Output of `helm version`:
`version.BuildInfo{Version:"v3.11.3", GitCommit:"323249351482b3bbfc9f5004f65d400aa70f9ae7", GitTreeState:"clean", GoVersion:"go1.20.3"}`

**Comment by joejulian** [comment]
Are you looking for the `--skip-refresh` flag?

**Comment by nosalan** [comment]
@joejulian I tried that but it didn't help, helm still tried to connect to the internet. I guess `--skip-refresh` flag is to control if the repository cache stored on e.g. `%TEMP%\helm` is to be refreshed and not to skip the remote chart update.

**Comment by jouve** [comment]
in charts/, put a symlink to your local chart, then you don't need to run ` helm dep up`
