### ISSUE TITLE
helm template with multiple filter for key values

### ISSUE THREAD

**Issue by vivuu1989** [helm/helm#12102]
We configured CSI driver in our AKS  cluster for secret management using keyvault  and the configuration files are as below.

under helm value file  of each application we are enabling and passing the keyvault secret names as below. The keyvault given (myappscommonkv01) is common for a set of applications (eg:- AppA, APPB, AppC, etc) . In this keyvault we have some secrets specific to each apps (for eg:- in the below example, the secrets are specific for AppA and APPB) and some secrets which is common for all apps(eg:COMMON-SECRET-1,COMMON-SECRET-2).

AppA Helm value.yaml file example

      keyvault:
        enabled: true
        name: myappscommonkv01
        secrets:
        - MY-SECRET-1      ######## secret specific for AppA
        - MY-SECRET-2      ######## secret specific for AppA
        - COMMON-SECRET-1  ######## secret Common  for AppA & AppB
        - COMMON-SECRET-2  ######## secret Common  for AppA & AppB

AppB Helm value.yaml file example

      keyvault:
        enabled: true
        name: myappscommonkv01
        secrets:
        - MY-SECRET-3      ######## secret specific for AppB
        - MY-SECRET-4      ######## secret specific for AppB
        - COMMON-SECRET-1  ######## secret Common  for AppA & AppB
        - COMMON-SECRET-2  ######## secret Common  for AppA & AppB

Below is the used Secretproviderclass helm template for these apps.

    spec:
      provider: azure
      secretObjects:
      - data:
          {{- range .Values.keyvault.secrets }}{{/* <-- only one range loop */}}
        - key: {{ . }}
          objectName: {{ $.Release.Name | upper }}-{{ . }} 
          {{- end }}      
        secretName: {{ $.Release.Name }}-kvsecret
        type: opaque
      parameters:
        usePodIdentity: "false"
        useVMManagedIdentity: "false"
        userAssignedIdentityID: ""
        keyvaultName: {{ .Values.keyvault.name | default "mykv01" }}    
        objects: |
          array:
            {{- range .Values.keyvault.secrets }}{{/* <-- only one range loop */}}        
            - |
              objectName: {{ $.Release.Name | upper }}-{{ . }}
              objectType: secret
            {{- end }}
        tenantId: {{ .Values.keyvault.tenantid }}
    {{- end }}
    {{- end -}} 

  
and the application are using the Deployment helm template envt variable part as below.

           env:
        {{- if eq .Values.keyvault.enabled true }}
        {{- range .Values.keyvault.secrets }}{{/* <-- only one range loop */}}
          - name: {{ regexReplaceAll "\\W+" . "_" }}
            valueFrom:
              secretKeyRef:
                name: {{ $.Release.Name }}-kvsecret
                key: {{ . }}
          {{- end }}
          {{- end }}
        {{- if eq .Values.keyvault.enabled true }}
          volumeMounts: 
          - name:  {{ $.Release.Name }}-volume
            mountPath: '/mnt/secrets-store'
            readOnly: true
          {{- end }} 
		  
		  

As you have seen, we are using the {{ $.Release.Name }} prefix in the helm template to pick the application specific keys from the keyvault. So in the keyvault, sameway we are creating the secrets keys with prefix of "releaseName" for avoiding any conflicts, which is working fine. eg: keyname in the keyvault will be as `MYAPPA-MY-SECRET-1, MYAPPA-MY-SECRET-2, MYAPPB-MY-SECRET-2, MYAPPB-MY-SECRET-2`

But in the case of common secrets, we are facing mismanagement of the secrets as, for each apps, we have to repeatedly prefix the "releasenames" to the same secret key name.

eg: keyname in the keyvault will be as `MYAPPA-COMMON-SECRET-1, MYAPPB-COMMON-SECRET-1,MYAPPA-COMMON-SECRET-2, MYAPPB-COMMON-SECRET-2`          

 
 
 So Looking for a way in the helm template, where we should be able to fetch both common keys names (without prefixed with appname) from keyvault and app specific key names(which are prefixed with the releasename). 

Expected Keyvault secret key names in the keyvault as below.

    MYAPPA-MY-SECRET-1 ##### specific for each apps,and provided ith prefix
    MYAPPA-MY-SECRET-2 ##### specific for each apps,and provided ith prefix
    COMMON-SECRET-1   ########## common for both Apps A&B and no prefix
    COMMON-SECRET-2    ########## common for both Apps A&B and no prefix

Any guidance?

**Comment by vivuu1989** [comment]
Any guidance?.. Highly anticipated.

**Comment by joejulian** [comment]
I think you're saying you don't want the common secrets to be managed by multiple charts. I would think that they should be managed independently, one "common" chart that establishes the common resources and is installed once, then each of your additional charts would be managed independently.

**Comment by vivuu1989** [comment]
What I am looking to achieve is, avoid duplicate entries in keyvault , for
the common secrets without having release name as Pre-fix

**Comment by joejulian** [comment]
:heavy_plus_sign: I think we're saying the same thing.

**Comment by joejulian** [comment]
Another option is to use the `lookup` function in your chart. If the resource exists, just skip that part of the template.

**Comment by vivuu1989** [comment]
Can u help me with sample
