### ISSUE TITLE
Create Release from manifests. Without Chart.

### ISSUE THREAD

**Issue by stockersky** [helm/helm#12110]
I have been using Helm for some time. It's great. But having many different environments with different configurations can turn into Values nightmare. In fact we end up working much more on Values files than on Helm templates.

I gave Kustomize a try and it fits really well the "multiple environments" use-case.
However, I appreciate the Helm Release : track of history, rollback to a specific version, etc...

Something like this would be great :

```
# 1. Create manifests from specific environment using Kustomize Overlays:
kubectl kustomize ./dev/. > manifests.yaml

# 2. Create a Helm Release from this manifest. No Chart, no Values, no rendering stage, just pure K8s manifests:
helm upgrade --install <MY_RELEASE> manifests.yaml
```

When creating a Release, Helm:
1. generates the manifests by filling placeholders in Chart Templates with Values,
2. apply generated manifests to Kubernetes
3. keeps track of the Release (so you can list Releases and versions of Release, perform Rollback, etc...)

I would only need the feature in steps 2 & 3 : create a Release only from raw manifests (a directory of manifests or one big manifest file). Without using the Helm Chart/Values rendering phase.

I don't know if its possible yet (Helm command to create Releases are expecting a Chart argument, but maybe i'm missing something).

**Comment by stockersky** [comment]
I have found this [exemple](https://github.com/thomastaylor312/advanced-helm-demos/tree/master/post-render) : Kustomize is used in a script as the argument of the `--post-renderer` parameter...

ex : `helm upgrade --install --dry-run rabbitmq-per ../../helm-chart-rabbitmq/. --post-renderer ./post-render-kustomize.sh`

I just created a Helm Chart were I copied the 'base' manifests of Kustomize in the Helm Chart Templates directory. As it.

Well, it works. But at the end, it's neither a Helm, neither a Kustomize workflow...

For exemple, Kustomize file inside the 'performance' environment overlay would need the 2 last labels :

```yaml
resources:
  - all.yaml
nameSuffix: -per
namespace: sit-per
commonLabels:
  app: myapp
  name: rabbitmq-per
  tags.datadoghq.com/env: per
  tags.datadoghq.com/service: myapp
  tags.datadoghq.com/version: '1'
  app.kubernetes.io/managed-by: Helm
  meta.helm.sh/release-name: rabbitmq-per
```

Helm would throw an error if those Labels are not set.
Indeed, Labels `app.kubernetes.io/managed-by` & ` meta.helm.sh/release-name: rabbitmq-per` are meant to be automatically added by Helm. But as I overwrite it with Kustomize within the `post-render` step, those labels would be deleted. So you have to hardcode them ( the first Label is not much of a problem but the second is).... 

You also have to point to a all.yaml manifest instead of existing directory of base manifests...

Well, at the end, with this, I don't feel like taking the best of both worlds.

It would definitely be more elegant to just provide raw manifests directly to Helm.

**Comment by joejulian** [comment]
Something like this maybe?

```sh
helm template --output-dir $KUSTOMIZE_DIR myrelease mychart
kustomize build $KUSTOMIZE_DIR -o $HELM_INSTALL_DIR/templates
helm install myrelease $HELM_INSTALL_DIR
```
Where the chart in `$HELM_INSTALL_DIR` has an empty template directory.

**Comment by jouve** [comment]
> In fact we end up working much more on Values files than on Helm templates.

I've been using https://github.com/helmfile/helmfile/ to manage values for multiple envs.
