### ISSUE TITLE
--pass-credentials does not take effect

### ISSUE THREAD

**Issue by zchcc** [helm/helm#12117]
Output of `helm version`: 3.12.0

`helm pull` 的 `--pass-credentials` 会被 `repositories.yaml` 的 `pass_credentials_all` 设置覆盖
这会导致 `pass_credentials_all` 为 `false` 时,  `helm pull xxx`即便使用了`--pass-credentials`也是无效的, 认证信息都不会被传递

我不确定这是helm的设计还是一个bug, 我的感觉是bug, 因为这个逻辑太奇怪了

google translate:
`--pass-credentials` for `helm pull` will be overridden by `pass_credentials_all` setting in `repositories.yaml`

This will cause `helm pull xxx` to be invalid even if `--pass-credentials` is used when `pass_credentials_all` is `false`, and the authentication information will not be passed

I'm not sure if this is the design of helm or a bug, I feel like it's a bug, because the logic is so weird

https://github.com/helm/helm/blob/c9f554d75773799f72ceef38c51210f1842a1dea/pkg/action/pull.go#L90
https://github.com/helm/helm/blob/c9f554d75773799f72ceef38c51210f1842a1dea/pkg/downloader/chart_downloader.go#L239

**Comment by joejulian** [comment]
I believe this is the correct behavior as any setting that tries to prevent you sharing your credentials should be the setting with priority.

See https://github.com/advisories/GHSA-56hp-xqp3-w2jf

**Comment by zchcc** [comment]
假如就是这么设计的, 那我觉得当用户`pull` 或者 `install` 走入这段安全逻辑的时候, helm应该有提示或者警告, 否则用户将很难定位问题, 因为没有任何有效的错误信息. 我遇到这个问题时就浪费了很多时间, 把源码下载下来debug才解决的.

google translate:
If this is the design, then I think that when the user `pull` or `install` and enters this security logic, helm should have a prompt or warning, otherwise the user will find it difficult to locate the problem because there is no effective error message. I encountered this A lot of time was wasted when there was a problem, and the source code was downloaded and debugged to solve it.

**Comment by joejulian** [comment]
Good idea! Would you have any interest in contributing that change? Seems like an easy first contribution.
