### ISSUE TITLE
helm push to OCI registry failed when the registry integrate with keycloak 

### ISSUE THREAD

**Issue by CheneyCookie** [helm/helm#12121]
Output of `helm version`: v3.12.0

Output of `kubectl version`: v1.25.3

OCI registry version: https://github.com/distribution/distribution 2.8.1

I am using helm3.12.0 to pull push helm chart to OCI registry, the registry integrated with keycloak which means will use token to auth.
I could login and pull chart from OCI registry by `helm registry login` and `helm pull`, but when I try to push chart by `helm push`, it reports an error 
`Error: push access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed`

From the packet capture by using tcpdum, I see the request to get token as below
`GET /auth/realms/master/protocol/docker-v2/auth?scope=repository:mychart:pull&scope=repository:mychart:pull,push&service=registry`
There are two scope to request permissions, one is `scope=repository:mychart:pull`, another is `scope=repository:mychart:pull,push`, this is redundant, so that keycloak will only return pull permission in the token.
So I think it's a bug, only one scope is enough to request permissions

**Comment by guigomcha** [comment]
I run into the same issue here. Did you fix it somehow? I am able to work with the docker CLI and even with a custom ORAS CLI with no problem though....
Another super annoying thing was that helm did not try to login with the docker credentials and gave me this error
```
Error: failed to authorize: failed to fetch oauth token: unexpected status from GET request to https://MYREGISTRY/realms/master/protocol/docker-v2/auth?scope=repository%3Ademo%3Apull&scope=repository%3Ademo%3Apull%2Cpush&service=hdar-distribution: 401 Unauthorized
```

After the helm registry login, is when I get the error from the issue

**Comment by guigomcha** [comment]
This issue is solved by @CheneyCookie  in his linked PR. Would love to see it merged
