### ISSUE TITLE
Sometimes Helm Release are not visible in "helm ls", yet resources are there

### ISSUE THREAD

**Issue by rabbagliettiandrea** [helm/helm#12148]
I am encountering an issue where Helm releases are sometimes not visible in the `helm ls` command output, even though the resources have been successfully created. To resolve this issue, I need to manually delete the resources (specifically, a Bitnami PostgreSQL StatefulSet) using kubectl.

### Steps to Reproduce

1. Install Helm chart
2. Check `helm ls` output

Output of `helm version`: 
`version.BuildInfo{Version:"v3.12.0", GitCommit:"c9f554d75773799f72ceef38c51210f1842a1dea", GitTreeState:"clean", GoVersion:"go1.20.4"}`

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:13:27Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1+k3s1", GitCommit:"bc5b42c27908ab430101eff0db0a0b22f870bd7a", GitTreeState:"clean", BuildDate:"2023-04-27T21:02:08Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/arm64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
k3s

**Comment by jouve** [comment]
by default, ` helm list`  only list deployed or failed releases, maybe your release in some other state.

can you try with ` helm list -a `  ?
