### ISSUE TITLE
Helm upgrade points to old service account and fails with missing token 

### ISSUE THREAD

**Issue by TahjidAshfaque** [helm/helm#12147]
Output of `helm version`: version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"clean", GoVersion:"go1.17.13"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.12", GitCommit:"2cb4598553d0a2ca5f3eb7980c99cd8236cc5011", GitTreeState:"clean", BuildDate:"2021-06-16T12:52:44Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/amd64"}

We have a application that generates a service account using the following yaml file:

`{{- if not (lookup "v1" "ServiceAccount" .Release.Namespace (.Values.serviceAccountName | default "service-account")) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: instancename
  name: {{ .Values.serviceAccountName | default "service-account" }}
  namespace: {{ .Release.Namespace }}
{{- end }} `

When we do helm install the first time it works without any issues. But when we try to do `helm upgrade`, it gets stuck in the containercreating stage with the following message
` Warning  FailedMount  5s (x5 over 13s)  kubelet            MountVolume.SetUp failed fo │
│ r volume "service-account-token-xxxxx" : secret "service-account-token-xxxxx" not found`

The old pod keeps running without any problem. This only happens with `helm upgrade`, running `helm uninstall` and `helm install` fixes the issue. I would appreciate any help or suggestions. Please feel free to ask for any more information you might need.

**Comment by TahjidAshfaque** [comment]
> 

Thank you, we have figured out the solution thanks to your reply.

**Comment by jouve** [comment]
yes,  *very simplified* , but you can imagine that install/upgrade is `helm template` then ` kubectl apply` the generated yaml

**Comment by TahjidAshfaque** [comment]
Thank you
