### ISSUE TITLE
helm is not upgrading through values.yaml

### ISSUE THREAD

**Issue by itsmeshaik** [helm/helm#12170]
Output of `helm version`: v3.12.1
![error](https://github.com/helm/helm/assets/111228261/cd27af4c-7602-4c00-aa33-4e9e5912d5a0)

Output of `kubectl version`: 1.23

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AWS EKS

Error: UPGRADE FAILED: template: camunda-platform/charts/zeebe-gateway/templates/gateway-deployment.yaml:80:24: executing "camunda-platform/charts/zeebe-gateway/templates/gateway-deployment.yaml" at <include "camundaPlatform.issuerBackendUrl" .>: error calling include: template: camunda-platform/templates/_helpers.tpl:124:8: executing "camundaPlatform.issuerBackendUrl" at <include "camundaPlatform.keycloakURL" .>: error calling include: template: camunda-platform/templates/_helpers.tpl:115:63: executing "camundaPlatform.keycloakURL" at <include "identity.keycloak.contextPath" .>: error calling include: template: no template "identity.keycloak.contextPath" associated with template "gotpl"

can't figure out why its not upgrading, anybody can help on this

Output of helm version:
version.BuildInfo{Version:"v3.12.1", GitCommit:"f32a527a060157990e2aa8bf4501df4501df3", GitTreeState:"clean", GoVersion:"go1.20.4"}

**Comment by wujunwei** [comment]
The error meesage shows that **helm** can not find  template `identity.keycloak.contextPath`.
