### ISSUE TITLE
Documentation URL field

### ISSUE THREAD

**Issue by Kartikey-star** [helm/helm#12184]
Hi Team, 
Wanted to understand the community recommended way of specifying an external documentation URL in chart definition.
 By looking at the helm documentation https://helm.sh/docs/topics/charts/ `The Chart.yaml File`, there isn't any specific way. 
So is the `annotations` field the one which needs to be populated?

**Comment by wujunwei** [comment]
It may be `home` field? `home: The URL of this projects home page (optional)`
or you can show your short documentation on `notes` which will print after install and upgrade.

**Comment by Kartikey-star** [comment]
Hi @wujunwei , thanks for your inputs. `home` field can be used for documentation , but is it the most popular way of providing external links?
