### ISSUE TITLE
pre-upgrade and post-upgrade jobs run every time

### ISSUE THREAD

**Issue by angeloudy** [helm/helm#12180]
helm version: `version.BuildInfo{Version:"v3.12.1", GitCommit:"f32a527a060157990e2aa86bf45010dfb3cc8b8d", GitTreeState:"clean", GoVersion:"go1.20.4"}`

I have an umbrella chart that includes some subcharts.
One subchart contains a job that has 'pre-install,pre-upgrade' hook.
The other two contain 'post-install,post-upgrade' hooks.

I found that these jobs are triggered every time I run `helm upgrade`.
I also tried just run `helm upgrade` with the exact same version of umbrella chart and those jobs still get triggered, while none of my deployments change.
Similar to this one https://github.com/helm/helm/issues/8361

**Comment by wujunwei** [comment]
You can use `--no-hooks` flag to disable hooks when install or upgrade.
