### ISSUE TITLE
Is there any method can display the merged values without touching the kubernetes APIServer?

### ISSUE THREAD

**Issue by FuyuanChu** [helm/helm#12190]
Output of `helm version`:

```
> helm version
version.BuildInfo{Version:"v3.10.2", GitCommit:"50f003e5ee8704ec937a756c646870227d7c8b58", GitTreeState:"clean", GoVersion:"go1.18.8"}
```

Output of `kubectl version`:

```
> kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.11-dispatcher", GitCommit:"2b68cbbf969871468570eb0d05cc9c216090b9b6", GitTreeState:"clean", BuildDate:"2023-03-01T18:19:51Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.12-gke.1000", GitCommit:"b4e24aa2edb70ab31433ba75bd4052409d858719", GitTreeState:"clean", BuildDate:"2023-03-30T09:32:49Z", GoVersion:"go1.19.7 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  GKE

 `helm upgrade -i --dry-run --debug` will show the user-supplied values and computed values. However, we have a different scenario. We are now trying to add static semantic analysis for the helm values using OPA. So we need to get the merge values in our CI jobs without accessing the Kubernetes APIServer since it is a totally static check.

**Comment by yxxhero** [comment]
is similar to `kubectl --dry-run='client'`? @FuyuanChu

**Comment by wujunwei** [comment]
If I understand your meaning correctly, I think you can use [sql-storage-backend](https://helm.sh/docs/topics/advanced/#sql-storage-backend) to  store your release in database. you can see your values by sql without touching the kubernetes APIServer.
