### ISSUE TITLE
helm rollback returns release not found

### ISSUE THREAD

**Issue by prashant-shahi** [helm/helm#12221]
Tried `helm rollback` couple of times before.

I am getting the error below, when I try to rollback again.
 
```
Error: release: not found
```

I am able to see the same release with `helm list` but not able to `helm rollback`.

Output of `helm version`: v3.11.2

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.5", GitCommit:"804d6167111f6858541cef440ccc53887fbbc96a", GitTreeState:"clean", BuildDate:"2022-12-08T10:15:02Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.5-gke.1200", GitCommit:"4eb57372b0f0ac0023caca078161b75185febeef", GitTreeState:"clean", BuildDate:"2023-06-01T19:55:11Z", GoVersion:"go1.19.9 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform: GKE

**Comment by yxxhero** [comment]
@prashant-shahi please show the whole process.

**Comment by Ithrael** [comment]
<img width="1438" alt="image" src="https://github.com/helm/helm/assets/38208715/976d0fd7-163d-4364-bd75-05d172eb2405">
When I deleted the history versions of the release and kept only the latest version of the release, I encountered the error when doing "helm rollback xxx".
Please check if your release has any historical versions.

**Comment by Ithrael** [comment]
https://github.com/helm/helm/pull/12290
