### ISSUE TITLE
`helm chart` command not supported despited being in docs

### ISSUE THREAD

**Issue by BBBmau** [helm/helm#12254]
Was wanting to work with the OCI registry and found that when wanting to use the `helm chart` command it doesn't exist.

The current registry doc can be found here https://v3-1-0.helm.sh/docs/topics/registries/#the-chart-subcommand

**Comment by MichaelMorrisEst** [comment]
`helm chart` subcommand was removed in v3.7.0 (see https://github.com/helm/community/blob/main/hips/hip-0006.md)
You are looking at an old version of the doc, latest is: https://helm.sh/docs/topics/registries/#commands-for-working-with-registries

**Comment by BBBmau** [comment]
my mistake. thank you!
