### ISSUE TITLE
Helm Deployment Bug under namespace with resource quota

### ISSUE THREAD

**Issue by Rafircp** [helm/helm#12258]
Helm chart fails with 'operation cannot be fulfilled on resourcequotas' on CLI

Helm chart fails with an error like below:
Error: Operation cannot be fulfilled on resourcequotas "<resourcequota-name>": the object has been modified; please apply your changes to the latest version and try again
helm.go:81: [debug] Operation cannot be fulfilled on resourcequotas "<resourcequota-name>": the object has been modified; please apply your changes to the latest version and try again

Kubernetes (k8s) version 1.26.0

cat /etc/os-release 
NAME="Rocky Linux"
VERSION="8.6 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.6 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8"

Reference of the previous github link https://github.com/helm/helm/issues/9710

**Comment by yxxhero** [comment]
@Rafircp Needs more informations.

**Comment by MathieuCoupe** [comment]
Hi, I got the same issue.
When deploying a chart using "helm upgrade --install --atomic" to an openshift namespace, I often get this error:
> Error: release app failed, and has been uninstalled due to atomic being set: Operation cannot be fulfilled on resourcequotas "core-object-counts": the object has been modified; please apply your changes to the latest version and try again

How can I get more details about what happens ?

**Comment by nightguide** [comment]
Hi, I got the same issue.

`Error: release cm-consumer failed, and has been uninstalled due to atomic being set: Operation cannot be fulfilled on resourcequotas "object-counts": the object has been modified; please apply your changes to the latest version and try again
helm.go:84: [debug] Operation cannot be fulfilled on resourcequotas "object-counts": the object has been modified; please apply your changes to the latest version and try again`

**Comment by jasonkengland** [comment]
I am seeing this issue in my namespace as well. Running on k8s version v1.30.3

**Comment by pchico83** [comment]
I have been seeing the same issue quite often since upgrading to Helm 4. I think the issue is related to server side apply.
Is the issue going to be solved upstream? Or is it the recommended fix to disable server-side apply?
