### ISSUE TITLE
helm sdk can't list all charts

### ISSUE THREAD

**Issue by imaemo** [helm/helm#12269]
Output of `helm version`: `version.BuildInfo{Version:"v3.9.2", GitCommit:"1addefbfe665c350f4daf868a9adc5600cc064fd", GitTreeState:"clean", GoVersion:"go1.17.12"}
`

Output of `kubectl version`:
```bash
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.15", GitCommit:"2c67202dc0bb96a7a837cbfb8d72e1f34dfc2808", GitTreeState:"clean", BuildDate:"2023-06-14T09:48:46Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/arm64"}

```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  self hosted 

Hello,

I'm using helm sdk to list all of the helm chart, and below is the code
```golang
package main

import (
  "fmt"
  "log"
  "os"

  "helm.sh/helm/v3/pkg/action"
  "helm.sh/helm/v3/pkg/cli"
)

func main() {

  settings := cli.New()
  
  actionConfig := new(action.Configuration)

  err := actionConfig.Init(settings.RESTClientGetter(), "", os.Getenv("HELM_DRIVER"), log.Printf) 
  if err != nil {
    log.Fatal(err)
  }  

  listClient := action.NewList(actionConfig)
  listClient.All = true

  results, err := listClient.Run()
  if err != nil {
    log.Fatal(err)
  }

  for _, release := range results {
    fmt.Println(release.Name) 
  }
}
```

I have set `listClient.All` to `true`, but the results didn't contains all status's chart, like `pending-install`, could anyone help on this?

**Comment by Ithrael** [comment]
It seems that none of the filter conditions are working. I tried listClient.Deployed=True and listClient.Failed=True, but the results returned are the same as those obtained from helm list.

/assign

**Comment by Ithrael** [comment]
https://helm.sh/docs/topics/advanced/#simple-example 
So the example in the document needs to be modified, adding a line list.SetStateMask(). However, I'm not sure if the initial design was intended to include SetStateMask() in client.Run(). If that's the case, the logic of Run() needs to be modified, and the example in the document doesn't need to be modified.

**Comment by Ithrael** [comment]
> https://helm.sh/docs/topics/advanced/#simple-example So the example in the document needs to be modified, adding a line list.SetStateMask(). However, I'm not sure if the initial design was intended to include SetStateMask() in client.Run(). If that's the case, the logic of Run() needs to be modified, and the example in the document doesn't need to be modified.

@gjenkins8 I would like to ask for your opinion on this matter

**Comment by imaemo** [comment]
> helm uses the StateMask parameter to filter releases of different statuses through bitwise & operations. When listClient.All=True is used, the value of StateMask should be updated，look (https://github.com/helm/helm/blob/main/pkg/action/list.go#L293). In the Run(look https://github.com/helm/helm/blob/main/pkg/action/list.go#L148) function, the SetStateMask() function is not called, resulting in the StateMask not being updated successfully when listClient.All=True is used.
> 
> Add list.SetStateMask() under listClient.All = true. for example:
> 
> ```
>   listClient := action.NewList(actionConfig)
>   listClient.All = true
>   // add the line 
>   list.SetStateMask()
> 
>   results, err := listClient.Run()
> ```

thanks a lot, it works

**Comment by Ithrael** [comment]
Calling SetStateMask() in listClient.Run() can resolve the issue(client.Deployed=true), but it will have an impact on the way of setting StateMask (client.StateMask = 16). I will  submit a pull request after detailed testing.
