### ISSUE TITLE
如何连接内网搭建的https的prometheus？

### ISSUE THREAD

**Issue by xinsir88** [helm/helm#12305]
求大神指导，如何连接内网的https的prometheus，--prometheus-insecure-skip-verify 参数应该如何配置？
我使用Grafana配置这个prometheus数据源需要开启skip-verify才能连接成功。

**Comment by Ithrael** [comment]
你用的哪个版本的helm，有这个--prometheus-insecure-skip-verify参数吗，你是想说你执行helm repo add  xxxx 要--insecure-skip-tls-verify才可以吗，多给一些信息吧

**Comment by yxxhero** [comment]
@xinsir88 sorry. this is not an issue of the helm. please post an issue on the Prometheus repo. Thanks so much. BTW. please use English.

**Comment by yxxhero** [comment]
@xinsir88 please open an new issue if you have more issue about helm.
