### ISSUE TITLE
[QUESTION] How to iterate over 2 lists to get values from the same indexes?

### ISSUE THREAD

**Issue by tenkinogawa** [helm/helm#12308]
Hello, 
I would like to iterate over 2 lists at the same time and get values from identical indexes from both lists
template.yaml:

```
{{- $values1 := splitList ", " .Values.values1 }}
{{- $values2 := splitList ", " .Values.values2 }}
{{- range $index, $value1 := $values1 }}
{{- range $index, $value2 := $values2 }}
- data1: "something/{{$value1}}"
  data2: {{ $value2 }}
{{- end }}
{{- end }}
```

values:
```
values1: "data1_1, data1_2"
values2: "data2_1, data2_2"
```

```
The result I get:
- data1: "something/data1_1"
  data2: data2_1
- data1: "something/data1_1"
  data2: data2_2
- data1: "something/data1_2"
  data2: data2_1
- data1: "something/data1_2"
  data2: data2_2
```
  
The result I want:

```
- data1: "something/data1_1"
  data2: data2_1
- data1: "something/data1_2"
  data2: data2_2
```

Can someone help me obtain that result?

**Comment by Ithrael** [comment]
`   {{- $values1 := splitList ", " .Values.values1 }}
    {{- $values2 := splitList ", " .Values.values2 }}
    {{- range $index, $value1 := $values1 }}
      {{- range $index, $value2 := $values2 }}
      - data1: "something/{{$value1}}"
        data2: {{ $value2 }}
    {{- end }}
    {{- end }}`
可能这样写你更容易理解，与你的代码作用是一样的，两层range，要遍历4次，我不确定你的场景是什么样的。但是如果要用你的例子得到你的结果，你应该只能range一层，比如
`   {{- $values1 := splitList ", " .Values.values1 }}
    {{- $values2 := splitList ", " .Values.values2 }}
    {{- range $index, $value1 := $values1 }}
      - data1: "something/{{$value1}}"
        data2:  {{ index $values2 $index }}
    {{- end }}`

**Comment by tenkinogawa** [comment]
@Ithrael thank you, that's exactly what I needed!
