### ISSUE TITLE
`mimir-distributed` helm chart not following `Restricted Pod Security Standard` as claimed by Grafana docs

### ISSUE THREAD

**Issue by dorkamotorka** [helm/helm#12301]
As per [Grafana Mimir documentation](https://grafana.com/docs/helm-charts/mimir-distributed/latest/run-production-environment-with-helm/) it should be possible to install `mimir-distributed` helm-chart by following the Kubernetes [Restricted security policy](https://kubernetes.io/docs/concepts/security/pod-security-standards/). But when I'm deploying on the GKE Autopilot, this does not hold true. All component like `ruler`, `compactor`, `ingester`, `Alertmanager`, `store gateway` require this helm configuration:
```
  containerSecurityContext:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
```
in order to avoid errors like `read-only filesystem`, `permission denied while accessing X directory`. The configuration above is obviously against the best security practices in Kubernetes. I think anybody should be able to reproduce this scenario by just deploying the `mimir-distributed` helm chart onto the GKE Autopilot. Note, that I'm using GCS storage buckets for the components where the configuration allows it but still as per my investigation there are some temporary file the Mimir is trying to save onto a filesystem.

Output of `helm version`:
```
version.BuildInfo{Version:"v3.12.0", GitCommit:"c9f554d75773799f72ceef38c51210f1842a1dea", GitTreeState:"clean", GoVersion:"go1.20.4"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.16", GitCommit:"51e33fadff13065ae5518db94e84598293965939", GitTreeState:"clean", BuildDate:"2023-07-19T12:26:21Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.14-gke.2700", GitCommit:"20f1946282011a3f0cec885eaafe3decc9c367c9", GitTreeState:"clean", BuildDate:"2023-06-22T09:23:35Z", GoVersion:"go1.19.9 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE Autopilot

**Comment by sabre1041** [comment]
@dorkamotorka Helm supports setting these types of configurations, but they must be configured within the chart implementation, which is the case in this instance. Would recommend submitting an issue against the Grafana repository instead
