### ISSUE TITLE
Any idea if there is a way to get the number of pods deployed from a helm chart

### ISSUE THREAD

**Issue by NavyaEV** [helm/helm#12326]
I want to add a check where I need to compare the number of pods that can be deployed on kubernetes env with the number of pods that a helm chart deploys. Charts may contain deployments/services/stateful-sets.

With out parsing the charts file by file, is there a way to get the number of pods a helm chart can deploy?

Output of `helm version`:
$ helm version
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}

Output of `kubectl version`:
[root@appliance-1 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1+k3s-2d1556d1-dirty", GitCommit:"2d1556d1a405f353e7a2ec05413ad0bee6ae19bd", GitTreeState:"dirty", BuildDate:"2023-07-11T07:39:07Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by JossWhittle** [comment]
Helm is only going to know about the resources that it outputs the manifests for. So if you want to count `Pod`s but you're creating a higher level resource not literal Pod manifests, you'd have to count the number of `Deployments`/`ReplicaSets`/`StatefulSets` ect that you are producing and scale that by the `replicas` field for each. 

But that's not foolproof. Any kind of auto-scaling controller isn't going to let you know how many replicas will actually exist at helm templating time. And you might find some public charts always use a `HPA` even if they set the values to not actually scale. 

This is always going to be a lossy heuristic. Maybe you can get a lower bound on how many Pods will be created. But even then. 

---

But if you do want to do this, I can only see it working from helm like follows:

Do a helm dry run, dumping the YAML for the install, and pipe it into `yq` to query for sub-documents with `kind: Deployment` or w/e else you want to consider. Look for `spec.replicas` within those documents and count them up.

**Comment by JossWhittle** [comment]
@Ithrael can probably do it all in yq with a reduction https://mikefarah.gitbook.io/yq/operators/reduce

Should be able to pipe the stdout from helm template directly into yq with no need for writing to files first too.

**Comment by Ithrael** [comment]
> https://mikefarah.gitbook.io/yq/operators/reduce

By default, the helm template will generate multiple yaml results on the console, which yq seems unable to parse. I tried to use awk to split them and then parse them with yq, but it was unsuccessful. In the end, I resorted to this method of writing files, parsing, and deleting files.  
If you could help me achieve this, I would be very grateful.

**Comment by JossWhittle** [comment]
https://github.com/mikefarah/yq/issues/157#issuecomment-403789021 should work for this.

**Comment by Ithrael** [comment]
> [mikefarah/yq#157 (comment)](https://github.com/mikefarah/yq/issues/157#issuecomment-403789021) should work for this.

Thanks, You're right, the script can be simplified
`helm template tests python -f tests/python/api.yml --dry-run | xargs -0 -I {} | yq -r '.spec.replicas' | awk '{sum+=$1} END {print sum}'`

**Comment by NavyaEV** [comment]
@JossWhittle , @Ithrael, could get the count as expected with --dry-run or with --debug as suggested. Thank you for the help.
