### ISSUE TITLE
Authentication error in kafka helm chart 

### ISSUE THREAD

**Issue by sjafari2** [helm/helm#12325]
Author: Soheila Jafari-Khouzani <sjafarikhouzani@unm.edu>
Date:   Wed Aug 23 12:49:15 2023  MDT

I am using the kafka helm chart and I am following the commands to create a client to run producer and consumer on it. My helm version is v3.12.3. Here are the information I get after installing kafka helm chart: 
`NAME: my-pipeline
LAST DEPLOYED: Wed Aug 23 04:50:06 2023
NAMESPACE: kafkastreamingdata
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
CHART NAME: kafka
CHART VERSION: 24.0.14
APP VERSION: 3.5.1

** Please be patient while the chart is being deployed **

Kafka can be accessed by consumers via port 9092 on the following DNS name from within your cluster:

    my-pipeline-kafka.kafkastreamingdata.svc.cluster.local

Each Kafka broker can be accessed by producers via port 9092 on the following DNS name(s) from within your cluster:

    my-pipeline-kafka-controller-0.my-pipeline-kafka-controller-headless.kafkastreamingdata.svc.cluster.local:9092
    my-pipeline-kafka-controller-1.my-pipeline-kafka-controller-headless.kafkastreamingdata.svc.cluster.local:9092
    my-pipeline-kafka-controller-2.my-pipeline-kafka-controller-headless.kafkastreamingdata.svc.cluster.local:9092

The CLIENT listener for Kafka client connections from within your cluster have been configured with the following security settings:
    - SASL authentication

To connect a client to your Kafka, you need to create the 'client.properties' configuration files with the content below:

security.protocol=SASL_PLAINTEXT
sasl.mechanism=SCRAM-SHA-256
sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required \
    username="user1" \
    password="$(kubectl get secret my-pipeline-kafka-user-passwords --namespace kafkastreamingdata -o jsonpath='{.data.client-passwords}' | base64 -d | cut -d , -f 1)";

To create a pod that you can use as a Kafka client run the following commands:

    kubectl run my-pipeline-kafka-client --restart='Never' --image docker.io/bitnami/kafka:3.5.1-debian-11-r25 --namespace kafkastreamingdata --command -- sleep infinity
    kubectl cp --namespace kafkastreamingdata /path/to/client.properties my-pipeline-kafka-client:/tmp/client.properties
    kubectl exec --tty -i my-pipeline-kafka-client --namespace kafkastreamingdata -- bash

    PRODUCER:
        kafka-console-producer.sh \
            --producer.config /tmp/client.properties \
            --broker-list my-pipeline-kafka-controller-0.my-pipeline-kafka-controller-headless.kafkastreamingdata.svc.cluster.local:9092,my-pipeline-kafka-controller-1.my-pipeline-kafka-controller-headless.kafkastreamingdata.svc.cluster.local:9092,my-pipeline-kafka-controller-2.my-pipeline-kafka-controller-headless.kafkastreamingdata.svc.cluster.local:9092 \
            --topic test

    CONSUMER:
        kafka-console-consumer.sh \
            --consumer.config /tmp/client.properties \
            --bootstrap-server my-pipeline-kafka.kafkastreamingdata.svc.cluster.local:9092 \
            --topic test \
            --from-beginning
`
I exactly follow the instructions, creating a client.properties file with the provided information. I run the commands to run "my-pipeline-kafka-client" pod and I copy the client.properties inside the pod and I run the kafka-console-producer.sh command as mentioned above. But, when it comes to this point, producer can not connect to kafka brokers. Here is the error:

`ERROR [Producer clientId=console-producer] Connection to node -1 (my-pipeline-kafka-controller-0.my-pipeline-kafka-controller-headless.kafkastreamingdata.svc.cluster.local/10.244.103.178:9092) failed authentication due to: Authentication failed during authentication due to invalid credentials with SASL mechanism SCRAM-SHA-256 (org.apache.kafka.clients.NetworkClient)`

Points to be considered:
The secret my-pipeline-kafka-user-passwords is available and I can get the password and user1 from it. 
This authentication error happens for both consumers and producers.

 Signed-off-by: sjafarikhouzani@unm.edu

**Comment by yxxhero** [comment]
@sjafari2 thanks. this is not an issue of helm. please post a new issue in kafka helm chart.

**Comment by sjafari2** [comment]
Can you please give me some hints for solving it? I appreciate it.

**Comment by traksel** [comment]
@sjafari2 hi
Inside the container, check the values in the `password` placeholder. ConfigMap is mounted inside the container as is

**Comment by pyildargit** [comment]
@sjafari2 can you tell me how you solved it? i have the exact very same issue..

**Comment by PrajwalSD** [comment]
Was there a solution for the above problem?

**Comment by Amin-Siddique** [comment]
If you're using Kraft instead of zookeeper below is worth mentoining: 

**Kafka Raft mode does not support SCRAM, so you should use PLAIN configuration instead of SCRAM mechanism like below:**

security.protocol=SASL_PLAINTEXT
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required \
    username="user1" \
     password="$(kubectl get secret my-pipeline-kafka-user-passwords --namespace kafkastreamingdata -o jsonpath='{.data.client-passwords}' | base64 -d | cut -d , -f 1)";

**Comment by ChanStacker** [comment]
The helm chart indeed installs kafka in KRAFT mode but the client.properties has not been amended accordingly it seems.  Updating the sasl mechanism to PLAIN solves the authentication issue.

**Comment by NiikhilMohanG** [comment]
I have tried by updating the sasl mechanism, but still getting authenticatio issue.

**Comment by kishanmaino** [comment]
Can someone tell me how it is resolved ..? I'm also facing the similar issue

**Comment by abrekhov** [comment]
> Can someone tell me how it is resolved ..? I'm also facing the similar issue

Change
sasl.mechanism=SCRAM-SHA-256
to
sasl.mechanism=PLAIN

in client.properties

this helped me.

**Comment by jjmurre** [comment]
I also had to change `sasl.jaas.config` to `org.apache.kafka.common.security.plain.PlainLoginModule`.

Furthermore, is is important that the `kubectl` command to obtain the password has already been executed before the `client.properties` file is copied to the container (the container does not have the `kubectl` tool).
