### ISSUE TITLE
Executing Helm in a rootless container tries to erroneously `mkdir /.config`

### ISSUE THREAD

**Issue by zemzelett** [helm/helm#12345]
Hello everyone, we are trying to build a rootless container image containing Helm in order to deploy a Kubernetes Nginx-based Ingress from within a Gitlab CI pipeline.

Gitlab CI fails to executed the command `helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx` with the error: `Error: mkdir /.config: permission denied`. All relevant environment variables have been set accordingly. The container works when run via docker locally but executing the command leads to Helm installing into `/.config` which seems wrong to me. Are we doing something wrong?

The following is the Dockerfile of the image we are creating:

<details>
<summary>Dockerfile</summary>

```dockerfile
FROM debian:bookworm-slim

RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections && apt-get install -y -q
RUN apt-get update && apt-get install --no-install-recommends -y gpg curl dialog apt-utils ca-certificates

ENV HOME=/home/ciuser
ENV XDG_CONFIG_HOME=/home/ciuser/.config
ENV HELM_CONFIG_HOME=/home/ciuser/.config
ENV HELM_HOME=/home/ciuser/.config/helm

# Install kubectl as per official docs
RUN curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
RUN echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list
RUN apt-get update && apt-get install -y kubectl

# Install helm
RUN curl --insecure https://baltocdn.com/helm/signing.asc | gpg --dearmor | tee /usr/share/keyrings/helm.gpg > /dev/null \
    && apt-get install apt-transport-https --yes \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | tee /etc/apt/sources.list.d/helm-stable-debian.list

RUN apt-get update && apt-get install --no-install-recommends -y helm \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# set a different user, as the GitLab CI does not allow starting images with the default root user
RUN addgroup --gid 1001 ciuser \
    && useradd --uid 1001 --gid 1001 --shell /bin/bash --create-home ciuser

WORKDIR /home/ciuser

RUN mkdir /home/ciuser/.config
RUN mkdir /home/ciuser/.config/helm
RUN chmod -R 700 /home/ciuser
RUN chown -R 1001:1001 /home/ciuser

USER 1001
```
</details>

I have looked up issues #8038 and #8606 but they offer no solution.

What i find curious is how Helm comes to try to access `/.config` when it is supplied with a different directory that exists and it has access to.

I appreciate any hints towards a solution.

Output of `helm version`:

```
version.BuildInfo{Version:"v3.12.3", GitCommit:"3a31588ad33fe3b89af5a2a54ee1d25bfe6eaa5e", GitTreeState:"clean", GoVersion:"go1.20.7"}
```

Output of `kubectl version`:

```
Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Not sure what to supply here.

**Comment by dinushchathurya** [comment]
It seems like you have missed the **Helm Cache Home** directory. Please refer to **Dockerfile** in this [repository](https://github.com/open-source-srilanka/eks-helm-client). It may help to solve your issue.

**Comment by zemzelett** [comment]
Adding `ENV HELM_CACHE_HOME=/home/ciuser/.config/cache` and `RUN mkdir /home/ciuser/.config/helm/cache` sadly does not change the outcome.

I also added `HELM_DATA_HOME`, `XDG_DATA_HOME`, `XDG_CACHE_HOME` in the same manner. All to no avail.

**Comment by dinushchathurya** [comment]
Try using ` -p` flag. Ex: `RUN mkdir -p /home/ciuser/.config/helm`

**Comment by zemzelett** [comment]
In order to make sure the environment variables are actually present within the pipeline i ran `printenv` inside it and none of them are present. Should've done that much earlier...

I'll investigate further and report back. Thanks so far. :)

**Comment by zemzelett** [comment]
I've got it working by setting the environment variables inside the _.gitlab-ci.yml_ to a valid directory inside the job.

This is obviously an issue with Gitlab.

I'll close this issue, sorry for the noise.
