### ISSUE TITLE
helm reliance on burst rate seems less viable than using QPS during discovery in managed environment

### ISSUE THREAD

**Issue by iamasmith** [helm/helm#12347]
This is more of a general issue with helm that I noticed by virtue that it cascades down to the helm Terraform provider which adopts the same discovery approach for the config built.

In GKE, if you use Anthos Config Management and a range of other products you will end up with a very large number of CRDS. 

We have observations of GKE installations carrying 341 CRDs, largely because of Anthos Config Connector which has CRDs for almost all GCP resources as it is used to provision those resources.

All clusters are minimum 1.26 K8S and come with rate limiting and QPS enable and also come with Google's 'Flow Control Guardrail' validating webhook. (more on that in a minute).

Where we use helm is via a Terraform provider, however, this problem would present with helm in it's more normal form and the provider inherits the problem due to the lack of QPS support as referenced by @phil9909 in https://github.com/helm/helm/issues/11280

We observe the helm deploy fail because of the discovery.NewDiscoveryCkuebtFirConfigOrDie() call without QPS settings in the REST config. Burst is set as a workaround here but burst really only allows a certain burst per second and rate limiting is applied even on burst the fair scheduling mechanism has some defences which means that it is very easy to exceed what burst will give you with 2 helm deployments occurring quite close together.

We have tried tuning the FlowSchema associated with the service account being used to apply the helm configuration, however, there are more issues around the Guard Rail webhook that you probably should be aware of.

The Guard Rail webhook explicitly blocks you from using one of the system predefined PriorityLevelConfigurations such as workload-high, or to avoid the issue completely the 'exempt' policy in a FlowSchema. The same Webhook also blocks you from defining a new policy with exempt.

In order to continue using GKE as a service we try to avoid customisation as far as possible to Google defined controls like this and probably other customers will feel the same.

Hence, it appears given the way things are going with these service offerings helm's use of burst to avoid rate limiting issues doesn't seem viable and in this scenario we are forced to look at the lesser change with is to avoid using the specific helm chart (Istio Gateway) and render it out for delivery avoiding the discovery call that lacks the WithDiscoveryQPS setting.

Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE

**Comment by iamasmith** [comment]
That would be great, I think kpt looking at the implementation simply used a fairly restricted limit (IIRC around 60) to overcome the problem and that was hard coded.

**Comment by z4ce** [comment]
Would you be interested in making a PR for it?

**Comment by iamasmith** [comment]
Sure, I can take a look at it :)

**Comment by iamasmith** [comment]
btw, my original interest was helm terraform provider and I mentioned (but typo'd) what they do for burst. This was much easier to implement than I imagined because the config is passed directly to build a client with the burst/qps and other parameters.
I'll raise another PR with Hashicorp for the QPS parameter for their provider depending upon the outcome of this as I suspect they are more likely to be amenable to the proposed change if it has gone into helm upstream.
