### ISSUE TITLE
Will helm 3.13.0 support server side dry runs?

### ISSUE THREAD

**Issue by red8888** [helm/helm#12342]
I'm sorry to ask, but I had trouble understanding the state of this.

My understanding is currently helm does not support server side dry runs like kubectl does.

But this PR added support for this right? https://github.com/helm/helm/pull/9426

So does this mean when `3.13.0` is released on September 13, 2023 I'll be able to do this:
`helm upgrade --install --dry-run=server --debug ...`

And get the same behavior as a kubectl server side dry run?

Again sorry if this is a dumb question I just wasn't clear on what that PR added exactly.

Thanks!

**Comment by z4ce** [comment]
@gjenkins8 is working on a HIP for server side apply, check it out. I think this PR would be very dependent on what comes out of that HIP. https://github.com/helm/community/pull/312

**Comment by red8888** [comment]
@z4ce Forgive my ignorance, whats the difference exactly? When `--dry-run=server` is set for helm install/upgrade how is the behavior different than kubectl dry run? I'm not clear on what lookups are.

Really all I want to know is if I do `--dry-run=server` with this next release will I get validation of resource specs like I would with kubectl dry-run?

**Comment by z4ce** [comment]
@red8888 Ah, no helm doesn't have anything like that -- including the PR you included. You would have to run `helm template` or `helm install --dry-run` and pipe the contents to `kubectl apply --dry-run=server`. It could be an interesting PR for yet-another-dry-run mode or enhancing `--dry-run=server` to actually create but not persist the objects in the cluster.

**Comment by red8888** [comment]
@z4ce  Ah gotcha. Are there good examples of piping `helm install --dry-run` to `kubectl apply --dry-run=server`? Is it really as easy as piping one to the other?

**Comment by z4ce** [comment]
Helm template is really the easiest way:

```
╰─ helm  template  oci://registry-1.docker.io/bitnamicharts/mysql  | kubectl apply --dry-run=server -f -
Pulled: registry-1.docker.io/bitnamicharts/mysql:9.12.1
Digest: sha256:ef35c9b5e16b5930284f00120869b11575a102bab33598473d1e1de4510da903
serviceaccount/release-name-mysql created (server dry run)
secret/release-name-mysql created (server dry run)
configmap/release-name-mysql created (server dry run)
service/release-name-mysql-headless created (server dry run)
service/release-name-mysql created (server dry run)
statefulset.apps/release-name-mysql created (server dry run)
```

With `install --dry-run` you'd have to pull out the manifests probably by using `install --post-renderer --post-renderer-args` to get the manifests out.

**Comment by joejulian** [comment]
The big reason the ability to dry-run against the server was added was for the `lookup` function to be able to tests that your templates are doing the right thing when they're using it. Without accessing the server, a lookup will always return an empty string.

**Comment by red8888** [comment]
@joejulian OK I understand this now! I actually didn't realize "lookups" were referring to a [helm function](https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-lookup-function).
