### ISSUE TITLE
Helm inline-errors

### ISSUE THREAD

**Issue by HerrDerb** [helm/helm#12349]
I propose an option that goes with `helm template` which allows the template to render, even if there are errors. 
e.g. `--inline-errors`

Helm would render the template and if an error occurs, it would not abort the template process and spit out an error which might be  a riddle itself. 
Instead the template would render anyway putting the error right into the spot of the failing template function. This way, I can much better understand where exactly an error occurs.

Usage example:
Right now I have a template that creates N kubernetes resources. My raw template file contains 72 lines. Running `helm template` ends with the error message:  

> unable to parse YAML: error converting YAML to JSON: yaml: line 96: did not find expected key

Alternatively: an option that outputs the rendered template until the line of error

**Comment by jouve** [comment]
you should be able to see the rendered templates using ` --debug`

**Comment by HerrDerb** [comment]
That is what it says, but with '--debug' I only get rendered all templates until the errorenous one. Not a single line of this then. This makes it always a little guess work especially when using range.
