### ISSUE TITLE
I need help getting an file-index when "range"-ing over output from Files.Glob

### ISSUE THREAD

**Issue by sik-asn** [helm/helm#12368]
Hello. I am sort of new to writing Helm charts.

I've written one that uses `range` over a number of files from `.Files.Glob`.

The problem is I cannot get an index-variable for the current-file I'm iterating over, as ".Files.Glob" seems to evaluate to a special kind of map, and not a `Dictionary` or something I can turn into a `List`. `len` seems to work, but only to get the size of this special map.

Do you have any suggestions how to fix this?

**Comment by sik-asn** [comment]
### templates/app.yaml
```tpl
{{- $files:= .Files.Glob "some/dir/*" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: some-name
spec:
  rules:
{{- range $path, $_:= $files}}
    - host: "{{ mustRegexSplit ".json" (mustRegexSplit "some/dir/" $path -1 | last) -1 | first  }}.example.com"
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: some-name
                port:
                  number: {{ fail "I need an index here 😢" }}
{{- end }}
```

**Comment by Ithrael** [comment]
` {{- $values1 := splitList ", " .Values.values1 }}
 {{- $values2 := splitList ", " .Values.values2 }}
 {{- range $index, $value1 := $values1 }}
      - data1: "something/{{$value1}}"
        data2:  {{ index $values2 $index }}
 {{- end }}`
This is a scenario where I use the index, Take a look at the usage of the index, can it help you?

**Comment by sik-asn** [comment]
`index` gets a value by key, so It doesn't work for me. I want a counter that increments as I `range` over `.Files.Glob` output.

index gives me a byte-representation of the file in the collection, not the index of the item in that collection. Does that make sense?

**Comment by z4ce** [comment]
You can just declare a variable and increment it like:

```
{{- $var := 3000 -}}
{{- range .Values.items -}}
port:
  number: {{- add1 $var -}}
{{- end -}}
```

**Comment by sik-asn** [comment]
I tried this, but I might have done something wrong. I'll give it another try :)

**Comment by sik-asn** [comment]
@z4ce your example yields "3001" on every iteration of "$var". $var doesn't seem to increment

**Comment by Ithrael** [comment]
Does this help you? @sik-asn 
```
{{- $files:= .Files.Glob "**/*.txt" }}
        {{- $index := 0 }}
        {{ range $path, $byte := $files }}
        - index: {{ $index }}
        - path: {{$path}}
        - content: |
          {{ $byte | printf "%s" | indent 4 }}
        {{- $index = add $index 1 }}
        {{- end }}
```
<img width="804" alt="image" src="https://github.com/helm/helm/assets/38208715/4f336393-45ea-4928-9789-050c2d4eeb67">

<img width="625" alt="image" src="https://github.com/helm/helm/assets/38208715/144244a6-7b4b-4244-8de0-520964caf25f">

**Comment by sik-asn** [comment]
@Ithrael it works great! I must've done the syntax wrong. I used ":=" instead of "=".

Thanks again! <3
