### ISSUE TITLE
Proposal: use the self-contained Kubernetes Go Client

### ISSUE THREAD

**Issue by arschles** [helm/helm#1237]
The new client is self-contained and carries with it significantly fewer dependencies. Docs are located at https://godoc.org/k8s.io/client-go

**Comment by adamreese** [comment]
I would love to!!! :heart:

We are using some packages that are not included in the new client.  I have been trying to see what I can refactor out.

**Comment by thomastaylor312** [comment]
@adamreese Is this still something we are planning to do in a minor release or are we wanting to do this for 3.0?

**Comment by bacongobbler** [comment]
FYI this may be a tad more important now that kubernetes's main repo is using an unorthodox script to restore and save dependencies, so client library paths are broken in v1.6.0.

```
><> git diff glide.yaml 
diff --git a/glide.yaml b/glide.yaml
index f8a7af4..c16e355 100644
--- a/glide.yaml
+++ b/glide.yaml
@@ -23,7 +23,7 @@ import:
 - package: google.golang.org/grpc
   version: 1.0.3
 - package: k8s.io/kubernetes
-  version: ~1.5.0
+  version: v1.6.0-rc.1
   subpackages:
   - pkg/api
   - pkg/api/errors

><> glide up
...
[ERROR] Error scanning k8s.io/kubernetes/pkg/client/restclient: open /home/bacongobbler/.glide/cache/src/https-k8s.io-kubernetes/pkg/client/restclient: no such file or directory
[ERROR] This error means the referenced package was not found.
[ERROR] Missing file or directory errors usually occur when multiple packages
[ERROR] share a common dependency and the first reference encountered by the scanner
[ERROR] sets the version to one that does not contain a subpackage needed required
[ERROR] by another package that uses the shared dependency. Try setting a
[ERROR] version in your glide.yaml that works for all packages that share this
[ERROR] dependency.
...
[ERROR] Failed to retrieve a list of dependencies: Error resolving imports
```

**Comment by bacongobbler** [comment]
See https://github.com/kubernetes/kubernetes/issues/42403

**Comment by sttts** [comment]
The error message `Error scanning k8s.io/kubernetes/pkg/client/restclient` sounds correct. There is no such package anymore.

**Comment by bacongobbler** [comment]
There was some discussion going on in SIG Apps to bring in a new "kubernetes client for users" in January. It'd be good to take part in that discussion especially since we'll be kicking off the dev summit in late February.

**Comment by mattfarina** [comment]
We are now using client-go so this is an issue that we can close.
