### ISSUE TITLE
[question] Question about PR Lifecycle

### ISSUE THREAD

**Issue by dayeguilaiye** [helm/helm#12376]
I'm new to github. I tried to rise a PR to fix a simple bug in helm.
Before I do that, I've already read the [CONTRIBUTING.md](https://github.com/helm/helm/blob/main/CONTRIBUTING.md), but still got some questions:

## 1. About **awaiting review** tag

> The maintainer in charge of triaging will apply the proper labels for the issue. This should include at least a size label, bug or feature, and **awaiting review** once all labels are applied.

> Once a review has the **awaiting review** label, maintainers will review them as schedule permits. The maintainer who takes the issue should self-request a review.

When and who will add `awaiting review`  tag?
And I barely found this tag in PRs, is this tag still in use?

My PR seems stuck here which passed the CI check, but seems no one review.
What should I do? Should I ask someone to review or just need to wait?

## 2. Where is the good place to ask about those questions?

The first problem is not a technical problem, I think it may not a good question in issue.
I know some projects have a **Discussions** while helm has not. So I ask this question here.

**Comment by yxxhero** [comment]
@dayeguilaiye where is your PR?

**Comment by dayeguilaiye** [comment]
@yxxhero Here is my PR: https://github.com/helm/helm/pull/12299

To be clear, I'm not complaining about anything, I'm really new to github and CNCF, I really don't know and want to learn those things.

It can tell from the so many mistakes I made in this PR :(

**Comment by yxxhero** [comment]
@dayeguilaiye I saw that PR. waitting for @joejulian

**Comment by dayeguilaiye** [comment]
@yxxhero Thanks for your reply! I just don't know if there is anything I should do. Now I understand that there is nothing to do, I will close this issue. Sorry to bother you.
