### ISSUE TITLE
.Capabilities.APIVersions.has doesn't find api version

### ISSUE THREAD

**Issue by rtarasov** [helm/helm#12402]
Hi Guys! I'm getting this wrong behaviour with helm 3.12.3 on AKS cluster 1.25.6:
`helm upgrade --install akv2k8s spv-charts/akv2k8s --namespace ugsvt-akv2k8s -f akv2k8s.yml Error: UPGRADE FAILED: unable to build kubernetes objects from current release manifest: resource mapping not found for name: "akv2k8s-envinjector" namespace: "" from "": no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"`

the kubectl api-resources returns:
`poddisruptionbudgets                                                     pdb                      policy/v1                              true         PodDisruptionBudget
`

I have checked the akv2k8s chart and I think it fails on this construct:
`{{- if .Capabilities.APIVersions.Has "policy/v1" }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget`

Could you please advice?

Thank you in advance!

Output of `helm version`:
version.BuildInfo{Version:"v3.12.3", GitCommit:"3a31588ad33fe3b89af5a2a54ee1d25bfe6eaa5e", GitTreeState:"clean", GoVersion:"go1.20.7"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:47:38Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.6", GitCommit:"94c50547e633f1db5d4c56b2b305670e14987d59", GitTreeState:"clean", BuildDate:"2023-06-12T18:46:30Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):
AKS 1.25.6

**Comment by rtarasov** [comment]
Hi @Ithrael ! Thank you for quick response. Debug produces the next:
`helm upgrade --install akv2k8s spv-charts/akv2k8s --namespace ugsvt-akv2k8s -f akv2k8s.yml --debug
history.go:56: [debug] getting history for release akv2k8s
upgrade.go:150: [debug] preparing upgrade for akv2k8s
upgrade.go:158: [debug] performing update for akv2k8s
Error: UPGRADE FAILED: unable to build kubernetes objects from current release manifest: resource mapping not found for name: "akv2k8s-envinjector" namespace: "" from "": no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
ensure CRDs are installed first
helm.go:84: [debug] resource mapping not found for name: "akv2k8s-envinjector" namespace: "" from "": no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
ensure CRDs are installed first
unable to build kubernetes objects from current release manifest
helm.sh/helm/v3/pkg/action.(*Upgrade).performUpgrade
	helm.sh/helm/v3/pkg/action/upgrade.go:281
helm.sh/helm/v3/pkg/action.(*Upgrade).RunWithContext
	helm.sh/helm/v3/pkg/action/upgrade.go:159
main.newUpgradeCmd.func2
	helm.sh/helm/v3/cmd/helm/upgrade.go:207
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.6.1/command.go:916
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.6.1/command.go:1044
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.6.1/command.go:968
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
	runtime/proc.go:250
runtime.goexit
	runtime/asm_arm64.s:1172
UPGRADE FAILED
main.newUpgradeCmd.func2
	helm.sh/helm/v3/cmd/helm/upgrade.go:209
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.6.1/command.go:916
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.6.1/command.go:1044
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.6.1/command.go:968
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
	runtime/proc.go:250
runtime.goexit
	runtime/asm_arm64.s:1172`

Thank you in advance!

**Comment by Ithrael** [comment]
I used the same charts and command `helm upgrade --install akv2k8s spv-charts/akv2k8s --namespace akv2k8s`, and still can't reproduce the issue.
<img width="1044" alt="image" src="https://github.com/helm/helm/assets/38208715/04b0e52d-fbb6-47fa-80e5-17c9b22579bc">
At this moment, I'm not sure what's causing the issue. It could be the configurations or permissions in k8s leading to `Capabilities.APIVersions.has` returning a false value. Would it be convenient for you to try a different k8s version?

**Comment by Mauzer93** [comment]
Did you get this working? I am experiencing the exact same issue atm

**Comment by Ithrael** [comment]
> Did you get this working? I am experiencing the exact same issue atm

I am unable to reproduce the issue. If you can provide a stable method for reproduction, I am willing to continue working.
