### ISSUE TITLE
Can helm upgrade a certain CR first?

### ISSUE THREAD

**Issue by tonyaw** [helm/helm#12401]
When helm install/upgrade/rollback a helm release, it sorts manifests based on "InstallOrder".
For CR(CustomerResource)s, as they aren't defined in InstallOrder, they will be put at last to perform install/upgrade/rollback.
Is my understanding right?

If Yes, my question is:
I have a CR that must be install/upgrade/rollback before any pod. Is it possible to configure helm to install/upgrade/rollback CR before any pod?

**Comment by Ithrael** [comment]
It seems that you may need to familiarize yourself with Helm hooks. https://helm.sh/docs/topics/charts_hooks/#the-available-hooks。
Based on your requirements, you should consider using the "pre-install" hook.

**Comment by tonyaw** [comment]
I know helm hook.
But if I used helm hook to manage the CR, I need to care its whole lifecycle, for example, create it in pre-install hook, and upgrade it in pre-upgrade hook.
If I want to treat CR as a normal manifest, is it any way to solve my issue?
Thanks!

**Comment by Ithrael** [comment]
> I know helm hook. But if I used helm hook to manage the CR, I need to care its whole lifecycle, for example, create it in pre-install hook, and upgrade it in pre-upgrade hook. If I want to treat CR as a normal manifest, is it any way to solve my issue? Thanks!

As far as I know, it should not be possible. 
Hooks support multiple parameters, using hooks to satisfy your scenario should be relatively easy.
<img width="683" alt="image" src="https://github.com/helm/helm/assets/38208715/6d363061-5939-4e62-bbe4-9a85f35003b9">

**Comment by leftjs** [comment]
> Thanks! If I add pre-upgrade annotation to a CR definition, will this hook create a new CR resource or update the existing CR before upgrade? I don't want to create a job to handle the CR lifecycle. :-)

I have the same problem. Have you found a solution?
