### ISSUE TITLE
When run `helm plugin update`, the plugin is updated but the helm plugin list still shows the older version

### ISSUE THREAD

**Issue by csun-cpointe** [helm/helm#12408]
When updating the `unittest` plugin, the `helm plugin list` still shows older version of `unittest`. The issues are seen on both ubuntu and i386 environments. The same issue also seen when updating `diff`

Plugin: unittest
Original version: 0.3.2
Latest version: 0.3.5

1) Testing on ubuntu (docker container)
``` 
ubuntu
helm:  v3.12.3
install unittest: v0.3.5 (`helm plugin install https://github.com/helm-unittest/helm-unittest.git --version 0.3.5`)
    => unittest fails => expected (we expected the test failed on v0.3.5)


ubuntu
helm: v3.12.3
install unittest: v0.3.2 (`helm plugin install https://github.com/helm-unittest/helm-unittest.git --version 0.3.2`)
    => unittest passes => expected
update unittest (`helm plugin update unittest`)
	downloads v0.3.5 => "succeeds"
	plugin list shows v0.3.2
	unittest fails (imply unittest version is v0.3.5)
	plugin.yaml still shows v0.3.2
uninstall plugin (`helm plugin uninstall unittest`)
install no version (i.e. latest: `helm plugin install https://github.com/helm-unittest/helm-unittest.git`)
	downloads v0.3.2 => "succeeds"
	plugin list shows v0.3.2
	behavior matches v0.3.2
install diff v3.7.0 (`helm plugin install https://github.com/databus23/helm-diff --version 3.7.0`)
	plugin list shows v3.7.0
update diff (`helm plugin update diff`)
	downloads latest => "succeeds"
	plugin list shows v3.7.0
	plugin.yaml shows v3.7.0
uninstall diff (`helm plugin uninstall diff`)
install diff latest (`helm plugin install https://github.com/databus23/helm-diff`)
	downloads 3.7.0 => "succeeds"
	plugin list shows 3.7.0
	
```

Output of `uname -a` on the ubuntu image:
```
Linux 9e7a6a560fa0 6.1.30-0-virt #1-Alpine SMP Fri, 26 May 2023 06:53:59 +0000 aarch64 aarch64 aarch64 GNU/Linux
```

2) Testing on i386 (Using Rosetta Terminal/macos-amd64)
```
install unittest: v0.3.2 (`helm plugin install https://github.com/helm-unittest/helm-unittest.git --version 0.3.2`)
    => unittest passes => expected
update unittest (`helm plugin update unittest`)
	downloads v0.3.5 => "succeeds"
	plugin list shows v0.3.2
	unittest fails (imply unittest version is v0.3.5)
	plugin.yaml still shows v0.3.2
uninstall plugin (`helm plugin uninstall unittest`)
install no version (i.e. latest: `helm plugin install https://github.com/helm-unittest/helm-unittest.git`)
	downloads v0.3.2 => "succeeds"
	plugin list shows v0.3.2
	behavior matches v0.3.2
	
```

Output of `kubectl version`:
```
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.2", GitCommit:"fc04e732bb3e7198d2fa44efa5457c7c6f8c0f5b", GitTreeState:"clean", BuildDate:"2023-02-22T13:39:03Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.5+k3s1", GitCommit:"7cefebeaac7dbdd0bfec131ea7a43a45cb125354", GitTreeState:"clean", BuildDate:"2023-05-26T22:50:26Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"linux/arm64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
[Dockerfile.txt](https://github.com/helm/helm/files/12665545/Dockerfile.txt)

**Comment by z4ce** [comment]
I was able to reproduce the behavior you're seeing. Was this working in a previous version of helm that you know of?

I also tried it with the helm dashboard plugin and I am seeing it fail in the same way.

**Comment by z4ce** [comment]
I had a look into the code for this and it looks like there isn't any code that changes the tag that the repo is using. We call "Update" on the repo, but that would only update anything if whatever the tag is referring to changed.

The most immediate solution to this would be to change the tag when you run `helm plugin update` from whatever version you have to the HEAD of the default branch like if you didn't specify a version at all when you first ran it.

**Comment by csun-cpointe** [comment]
@z4ce thanks for the response. Do you mean that we have to make sure we change the git tag to the latest version before we run the `helm plugin update`? 
Because, in our use case, we just want to make sure that we always use the latest helm unittest plugin when we run test without tracking the version.
Can you give an example? Thanks.

**Comment by z4ce** [comment]
If you installed with `helm plugin install https://github.com/helm-unittest/helm-unittest.git` then running `helm plugin update unittest` should work (based on what I'm reading in the code)... I believe it's using `--version` that is locking it to the old version reference.

**Comment by mattfarina** [comment]
I think this is a bug in the update logic.

The installer logic looks for specific references and if one isn't found it does semver constraint analysis. This way you can specify a version or a range, the same way you can with Helm charts.

The update logic finds the particular VCS (i.e. git) reference and just pulls updates to it.

The installer intent seems clear. The update logic doesn't flow with that which I think is a bug.

Update should, I think:
- check if the current checked out ref is semver. If so, update based on semver.
- if the vcs reference is not semver do a pull (i.e. to update the branch).

Contributions are welcome including to the masterminds/vcs package.
