### ISSUE TITLE
Setup image repository for helm install charts

### ISSUE THREAD

**Issue by novohool** [helm/helm#12400]
helm3:
When helm deploys applications, can it specify the image repository, just like kubeadm does?
```
kubeadm config images pull --image-repository xxx
```

**Comment by Aisuko** [comment]
Hi, @novohool. Is this works for you?

```
helm install mychart ./mychart --set image.repository=newrepo
```

**Comment by novohool** [comment]
> Hi, @novohool. Is this works for you?
> 
> ```
> helm install mychart ./mychart --set image.repository=newrepo
> ```

set just configures the variables that have been defined in values.yaml. What I want here is obviously to define the image mirror repository.
