### ISSUE TITLE
index.json reading doesn't work

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#12422]
https://github.com/helm/helm/pull/12245 added the ability to work with `index.json` files. But, there are two problems with it that need to be worked out.

1. Helm does not have a method to _read_ the created _index.json_ files. It assumes the extension is `.yaml` when autodiscovering.
2. If Helm 3.13.0+ creates an _index.json_ file, what is the story for older versions of Helm that do not know to look for the _index.json_ file? Is this a new opt-in feature all the way around?

cc @joejulian @sabre1041 

Output of `helm version`: 3.13.0

Output of `kubectl version`: N/A

Cloud Provider/Platform (AKS, GKE, Minikube etc.): N/A

**Comment by hiddeco** [comment]
The PR I submitted (which got merged) does not create an `index.json` file but rather writes the JSON to `index.yaml`. Given this being a superset, it should not create any issues by default.

**Comment by hiddeco** [comment]
See also further thoughts around autodiscovery in https://github.com/helm/helm/pull/12245#issuecomment-1647442138, and further reasoning behind JSON parsing in https://github.com/helm/helm/pull/12245#issuecomment-1661767828.

**Comment by hiddeco** [comment]
Further proof:

```console
$ ls -lha
total 4,0K
drwxr-xr-x 3 hidde users   80 sep 27 23:17 .
drwx------ 4 hidde users   80 sep 27 23:15 ..
drwxr-xr-x 4 hidde users  140 sep 27 23:15 test
-rw-r--r-- 1 hidde users 3,7K sep 27 23:16 test-0.1.0.tgz

$ helm repo index . --json

$ cat index.yaml
{
  "apiVersion": "v1",
  "generated": "2023-09-27T23:17:59.916568775+02:00",
  "entries": {
    "test": [
      {
        "name": "test",
        "version": "0.1.0",
        "description": "A Helm chart for Kubernetes",
        "apiVersion": "v2",
        "appVersion": "1.16.0",
        "type": "application",
        "urls": [
          "test-0.1.0.tgz"
        ],
        "created": "2023-09-27T23:17:59.917007622+02:00",
        "digest": "c2a6bddb3728038373fb3a36e5fbedef6add615df790f9341454fd82c3b02418"
      }
    ]
  }
}

$ docker run -d -p 8080:80 -v $PWD:/usr/share/nginx/html nginx
Unable to find image 'nginx:latest' locally
latest: Pulling from library/nginx
a803e7c4b030: Pull complete 
8b625c47d697: Pull complete 
4d3239651a63: Pull complete 
0f816efa513d: Pull complete 
01d159b8db2f: Pull complete 
5fb9a81470f3: Pull complete 
9b1e1e7164db: Pull complete 
Digest: sha256:32da30332506740a2f7c34d5dc70467b7f14ec67d912703568daff790ab3f755
Status: Downloaded newer image for nginx:latest
e5a10ba9af3c6a779308b153f104e21cde96da1ca504ab4a95b38e3ff675ef34

$ helm version
version.BuildInfo{Version:"v3.10.3", GitCommit:"v3.10.3", GitTreeState:"", GoVersion:"go1.19.9"}

$ helm repo add compatability-test http://localhost:8080
"compatability-test" has been added to your repositories

$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "compatability-test" chart repository

$  helm pull compatability-test/test

$ echo $?
0

**Comment by joejulian** [comment]
```
	f.BoolVar(&o.json, "json", false, "output in JSON format")
```
https://github.com/helm/helm/pull/12245/files#diff-a7730f6ac920fbecd35940df424c8adf31a4db73b9a48b60a9d995fb08c4c498R74

As mentioned, the premise is incorrect. This flag does not change the output filename, it simply produces json output instead of yaml. The yaml parser can read json (json is a subset of yaml) so all older versions of helm can still read a json encoded index.yaml.

**Comment by thernstig** [comment]
A question. Far back in the days I did perfs on YAML/JSON reading via Python libs. Both built-in as well as open source packages.

YAML parsing was infinitely slower.

Now, this is Golang here, but  considering you write JSON to YAML, it is still a YAML parser doing the parsing. I would _guess_ you would get much better perfs if a JSON parser read the .yaml file instead. Hence why writing to a .json would have benefits in discoverability and potentially even better perfs.

Note that this is all guessworks as I have no idea how smart the Go YAML parser is. But just throwing two cents in here.

**Comment by hiddeco** [comment]
@thernstig this is already intelligently being done by checking if the file contains valid JSON before invoking the actual parser, see: https://github.com/helm/helm/commit/e21c9cf7e243ca30868c2dfdd232168d7c4f744e (and the further benchmarks in the PR).

**Comment by mattfarina** [comment]
Note, if you want to see some testing on perf for parsing comparing yaml, json parsed as yaml (legacy helm), and json parsing (newer helm) you can find that at https://github.com/mattfarina/yamljsonperftest
