### ISSUE TITLE
helm list --selector no longer working in version 3.13.0 cli

### ISSUE THREAD

**Issue by meggerUC** [helm/helm#12435]
Using a `--selector` flag on `helm list` no longer works after updating to version 3.13.0 from 3.12.1

```
$ helm version
version.BuildInfo{Version:"v3.13.0", GitCommit:"825e86f6a7a38cef1112bfa606e4127a706749b1", GitTreeState:"clean", GoVersion:"go1.20.8"}

$ helm list --deployed -n kube-system --selector name=metrics-server
NAME    NAMESPACE       REVISION        UPDATED STATUS  CHART   APP VERSION
```

when using version 3.12.3 =
```
$ helm version
version.BuildInfo{Version:"v3.12.3", GitCommit:"3a31588ad33fe3b89af5a2a54ee1d25bfe6eaa5e", GitTreeState:"clean", GoVersion:"go1.20.7"}

$ helm list --deployed -n kube-system --selector name=metrics-server
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
metrics-server  kube-system     3               2023-04-10 17:04:54.325699796 -0700 PDT deployed        metrics-server-3.9.0    0.6.3
```

`helm ls` _does_ work without the selector.

Output of `helm version`: version.BuildInfo{Version:"v3.13.0", GitCommit:"825e86f6a7a38cef1112bfa606e4127a706749b1", GitTreeState:"clean", GoVersion:"go1.20.8"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.9-eks-49d8fe8", GitCommit:"53e5004c71669ab3835f7b9c30f79dee82c30c17", GitTreeState:"clean", BuildDate:"2023-01-09T23:48:25Z", GoVersion:"go1.18.9", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): EKS

**Comment by hiddeco** [comment]
This bug was introduced in #10533.

Due to "system labels" getting filtered from any object https://github.com/helm/helm/blob/v3.13.0/pkg/storage/driver/secrets.go#L102, they are no longer available by the time the selection on `name=metrics-server` is attempted: https://github.com/helm/helm/blob/v3.13.0/pkg/action/list.go#L191-L195.

**Comment by hiddeco** [comment]
Reason the tests did not catch this is likely because it makes use of the in-memory driver which did not see the same changes as introduced to other drivers in the above PR.
