### ISSUE TITLE
Add support for extra management labels to all resources

### ISSUE THREAD

**Issue by nonsocode** [helm/helm#12431]
Output of `helm version`: 3.12.3

Output of `kubectl version`: 
```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:47:40Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Minikube

When helm installs a release, it adds labels and annotations to all resources for management purposes. This is sufficient for helm itself, but when helm is used as one of the tools of a larger orchestration process, we may want to add additional management labels to resources created by a helm release.

The ability to set custom labels to all resources created by a helm release would be a huge win.

This is a request to add support.

**Comment by hiddeco** [comment]
You can achieve this using [Helm's post rendering feature](https://helm.sh/docs/topics/advanced/) in combination with something like [Kustomize's label transformer](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/transformerconfigs/README.md#labels-transformer).
