### ISSUE TITLE
[Feature] Show final rendered values in Helm 3 with multiple value files

### ISSUE THREAD

**Issue by patsevanton** [helm/helm#12499]
Hello! I see final rendered values after install release with multiple value files.
This is inconvenient.
Please add feature for show final rendered values in Helm 3 with multiple value files.

**Comment by balint-backmaker** [comment]
Hello, I can second this, it would be nice to have `helm template --show-values . -f ... -f ...` to confirm the end results. It cuts down on a lot of backtracking! :pray:
