### ISSUE TITLE
Appending new values to the chart of a dependency

### ISSUE THREAD

**Issue by vishalbalaji-v** [helm/helm#12512]
If I add some `base` as a dependency to some `app`, how do I add new values to the charts in the `base`?

Let's say I have a folder like this

```
base
    templates
        file.yaml
    Chart.yaml
    values.yaml
```
The file.yaml has some content
```
name: {{ .Values.name }}
age: {{ .Values.age }}
```

Now let's say I have some app that needs to use this, and I am using the base as a dependency on the `Chart.yaml`
```
apiVersion: v2
name: APP_NAME
version: 0.0.1
dependencies:
  - name: base
    version: 0.0.1
    repository: "file://../base"
```

I can edit the values that have been inherited from base by having a `values.yaml` like this

```
base:
    name: SOME_OTHER_NAME
    age: SOME_OTHER_AGE
```

But what if I want to add some new value in the middle of a file?

For eg, what if I want my final result to look like this? How would I get this result? I want to keep the name of the file as it is
```
name: {{ .Values.base.name }}
place: {{ .Values.place }}
age: {{ .Values.base.age }}
```

I can add an if/else condition for place in the `base` and then inherit it, but this doesn't seem like a scalable approach because I cannot exhaustively put everything necessary in my base.

The use case for me would be that I am creating some base extendable templates that others within my organisation can use for specific projects. Currently we use `kustomize` for it, and `kustomize` has options to add values to a specific path

**Comment by z4ce** [comment]
I'm not sure if I really understand what you're attempting to achieve, but I think defining [named templates ](https://helm.sh/docs/chart_template_guide/named_templates/)or global variables might be where you want to start looking.
