### ISSUE TITLE
pending-rollback - no more actions possible. 

### ISSUE THREAD

**Issue by Danny-P** [helm/helm#12516]
Hi,

I am running an AWS EKS k8s Cluster. On that I have several Helm charts deployed. Once I did the update to the latest k8s version I did not realize that one of this Deployments has a PodDisruptionBudget which has been removed in a k8s version.

Now I am not able to update the affected Helm Chart because PodDisruptionBudget is not known. I have removed it from Helm Charts, but that did not help. I tried to uninstall the deployment but that was also not possible due to the same reason.

Now I have changed the Manifest inside the secret and removed the PodDisruptionBudget from there.
But when I do a ````helm upgrade```` now I get the error:
````
Error: UPGRADE FAILED: another operation (install/upgrade/rollback) is in progress
````
Helm history give me:
````
37              Fri Nov 11 08:34:19 2022        failed                  dpn-1.1.0        1.1.0          
40              Sat Sep 16 19:54:04 2023        pending-rollback        dpn-1.1.0        4.17.1          Rollback to 39             
I tried to remove the secrets 38 and 39 which where in pending uninstall state as well. But that did not help, too.
````
Anything more I can try to be able to upgrade the helm chart? To re-setup the whole cluster would be lot of work...

Output of `helm version`:
version.BuildInfo{Version:"v3.12.3", GitCommit:"3a31588ad33fe3b89af5a2a54ee1d25bfe6eaa5e", GitTreeState:"clean", GoVersion:"go1.20.7"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.4-eks-8ccc7ba", GitCommit:"892db4a4e439987d7addade5f9595cadfa06db2e", GitTreeState:"clean", BuildDate:"2023-08-15T16:06:56Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.4-eks-2d98532", GitCommit:"3d90c097c72493c2f1a9dd641e4a22d24d15be68", GitTreeState:"clean", BuildDate:"2023-07-28T16:51:44Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS EKS

**Comment by z4ce** [comment]
One possible option here is just to delete your previous helm state and reinstall with the helm chart that doesn't have the PodDisruptionBudget. 

The steps would look something like

1.  backup your current releases `kubectl get secrets -l owner=helm,name=my-release -o yaml > backup.yaml`
3. `helm get values my-release > my-values`
4. `kubectl delete secrets -l owner=helm,name=my-release` (this is gonna be destructive)
5. `helm install my-release ./my-chart -f values.yaml`

I did a quick test of this with a chart and it seemed to work as everything deployed still had the helm annotations on them. I'm sure things like pre-install hooks would run again, so beware there. Definitely something spin up a development environment to try it out before attempting in production.

**Comment by Danny-P** [comment]
Great! That helped and now I am able to use helm again :-)
