### ISSUE TITLE
helm repo update with empty repositories[] fails with error 1

### ISSUE THREAD

**Issue by patrikbeno** [helm/helm#12526]
Having explicitly configured empty list of repositories is a valid situation that should not make `helm repo update` fail.

But it does:

repositories.yaml:
```
repositories: []
```

test:
```
$ helm repo update --repository-config repositories.yaml ; echo $?
Error: no repositories found. You must add one before updating
1
```

This behavior complicates automation and actual error detection.

Full test case:

```
$ (set -x; helm version; tee repositories.yaml <<<'repositories: []'; export HELM_REPOSITORY_CONFIG=repositories.yaml; helm repo update; echo $?; helm repo list; echo $?)
+ helm version
version.BuildInfo{Version:"v3.13.1", GitCommit:"3547a4b5bf5edb5478ce352e18858d8a552a4110", GitTreeState:"clean", GoVersion:"go1.20.8"}
+ tee repositories.yaml
repositories: []
+ export HELM_REPOSITORY_CONFIG=repositories.yaml
+ HELM_REPOSITORY_CONFIG=repositories.yaml
+ helm repo update
Error: no repositories found. You must add one before updating
+ echo 1
1
+ helm repo list
Error: no repositories to show
+ echo 1
1
```

**Comment by opencmit2** [comment]
Hi@patrikbeno 

First, the helm configuration file repositories.yaml is set as repositories: []. There is indeed no issue with the syntax of the file. However, the prerequisite for performing an update is the existence of repositories. From the perspective of the helm command, I believe this is reasonable.

**Comment by patrikbeno** [comment]
> First, the helm configuration file repositories.yaml is set as repositories: []. There is indeed no issue with the syntax of the file. However, the prerequisite for performing an update is the existence of repositories. From the perspective of the helm command, I believe this is reasonable.

Strongly disagree. `helm repo update` means _do update if there is anything to update_.

It is entirely different to `helm repo update my-repo` which would be right to complain 'no such repository'.
I would be OK with this error if there was no `repositories.yaml` file, or if the didn't contain `repositories[]` array/list.
But empty `repositories[]` is a valid configuration that should not cause this error. 

The only proper action is no-op update, maybe with a supressable warning.

**Comment by patrikbeno** [comment]
not stale
