### ISSUE TITLE
Labels removed after rollback

### ISSUE THREAD

**Issue by chojnack** [helm/helm#12521]
Output of `helm version`:
$ ./linux-amd64/helm version
version.BuildInfo{Version:"v3.13.1", GitCommit:"3547a4b5bf5edb5478ce352e18858d8a552a4110", GitTreeState:"clean", GoVersion:"go1.20.8"}

Output of `kubectl version`:

$ kubectl version
Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Private cloud

1. Install a chart with -l parameter. The lab is added to the release secret as expected:

[cinek@localhost helm313]$ ./linux-amd64/helm install -n ncms -l profile=myprofile test helloworld-go-1.3.47.tgz 
...
[cinek@localhost helm313]$ kubectl get secret -n ncms sh.helm.release.v1.test.v1 -o json|jq '.metadata.labels'
{
  "modifiedAt": "1698231264",
  "name": "test",
  "owner": "helm",
  "profile": "myprofile",   <-- my label added here
  "status": "deployed",
  "version": "1"
}

2. Upgrade the release with new parameter - the label is propagated to the new revision as expected:

[cinek@localhost helm313]$ ./linux-amd64/helm upgrade -n ncms test helloworld-go-1.3.47.tgz  --set aqq=sdf
...
[cinek@localhost helm313]$ kubectl get secret -n ncms sh.helm.release.v1.test.v1 -o json|jq '.metadata.labels'
{
  "modifiedAt": "1698231469",
  "name": "test",
  "owner": "helm",
  "profile": "myprofile",  <-- my label preserved in revision 1
  "status": "superseded",
  "version": "1"
}
[cinek@localhost helm313]$ kubectl get secret -n ncms sh.helm.release.v1.test.v2 -o json|jq '.metadata.labels'
{
  "modifiedAt": "1698231469",
  "name": "test",
  "owner": "helm",
  "profile": "myprofile", <-- my label propagated to revision 2
  "status": "deployed",
  "version": "2"
}

3. rollback the upgraded release - label not propagated to the next revision

[cinek@localhost helm313]$ ./linux-amd64/helm rollback -n ncms test
Rollback was a success! Happy Helming!

[cinek@localhost helm313]$ kubectl get secret -n ncms sh.helm.release.v1.test.v3 -o json|jq '.metadata.labels'
{
  "modifiedAt": "1698231681",
  "name": "test",
  "owner": "helm",
  "status": "deployed",
  "version": "3"
}
'profile=myprofile' label is missing in v3.

--------
I'd expect the labels added in v3 to be the same as in v1. Also, it think adding '-l' parameter to the 'rollback' command would be also useful. If I mark my rollbacks with a special label I could find which revisions are rollbacks just by checking the secret (no need to run and parse helm history).

Marcin

**Comment by z4ce** [comment]
Can you try this in Helm v3.12 and see if the behavior is the same? There was label logic that changed between 3.12 and 3.13 and I wonder of that broke this rollback functionality.

**Comment by chojnack** [comment]
Hi,

The revision secret labelling was added as a new feature in 3.13 (AFAIK).
I checked in source code and I think it just needs to add Labels in action/rollback similarily it is in action/upgrade.
THen in prepareROllback function the labels from previousRelease.Labels and r.Labels should be merged and added in the new release (targetRelease := &release.Release{ ...

I have pripared a draft solution locally. I'm testing it now, so I can prepare a merge request if you agree.

Marcin

**Comment by z4ce** [comment]
@chojnack definitely a fix this would be great. Rollback should rollback to the previous state. As for the idea of adding a `-l` to the rollback command, I'd recommend trying to start a thread in #helm-dev on Kubernetes Slack or join the [weekly developer call ](https://tockify.com/cncf.public.events/detail/158/1695918600000) and see what folks think.

**Comment by chojnack** [comment]
Hi,

I sent a PR for this issue: https://github.com/helm/helm/pull/12529.
I also sent a post on #helm-dev slack channel.

Marcin

**Comment by chojnack** [comment]
Hi,

I still don't see any response to my PR or the slack post. Do I need to do anything else to have this accepted?

Marcin

**Comment by chojnack** [comment]
Hi,

I closed the previous pull request and created a new one with just the missing labels fix.

https://github.com/helm/helm/pull/12539

I'm not sure however if I can create a nother pull request on top of this one with the "rollback -l" change  bfore this one is merged?

Marcin
