### ISSUE TITLE
Helm pulls invalid chart

### ISSUE THREAD

**Issue by lkoniecz** [helm/helm#12548]
```
helm search repo hc-helm-sandbox/some-chart --versions --devel
NAME                      	CHART VERSION      	APP VERSION	DESCRIPTION
my-repo/some-chart	5600-some-build.333	1.16.0     	A Helm chart for Kubernetes
my-repo/some-chart	5600-build.222     	1.16.0     	A Helm chart for Kubernetes
my-reposome-chart	5600-a-build.444   	1.16.0     	A Helm chart for Kubernetes
my-repo/some-chart	5600-a-build.222   	1.16.0     	A Helm chart for Kubernetes

tree
.

0 directories, 0 files
```

so I pull a chart
```
helm pull hc-helm-sandbox/some-chart --version 5600-a-build.333
```

what I get is
```
tree
.
└── some-chart-5600-some-build.333.tgz

1 directory, 1 file
```

on the contrary, when I delete the `5600-some-build.333` chart and pull non existing, I get

```
helm search repo hc-helm-sandbox/some-chart --versions --devel
NAME                      	CHART VERSION   	APP VERSION	DESCRIPTION
my-repo/some-chart	5600-build.222  	1.16.0     	A Helm chart for Kubernetes
my-repo/some-chart	5600-a-build.444	1.16.0     	A Helm chart for Kubernetes
my-repo/some-chart	5600-a-build.222	1.16.0     	A Helm chart for Kubernetes


helm pull my-repo/some-chart --version 5600-build.555
Error: chart "some-chart" matching 5600-build.555 not found in my-repo index. (try 'helm repo update'): no chart version found for some-chart-5600-build.555
```

```
helm pull hc-helm-sandbox/some-chart --version 5600-a-build.333
```
pulls `some-chart-5600-build.222.tgz` which is the last alphabetically wise chart matching whatever logic.

but this

```
helm pull my-repo/some-chart --version 5500-a-build.333
Error: chart "some-chart" matching 5500-a-build.333 not found in my-repo index. (try 'helm repo update'): no chart version found for some-chart-5500-a-build.33
```

Pulls nothing.  Should it make an exact-match check?
This is really error prone

Output of `helm version`:
```
version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.17.5"}
```
Output of `kubectl version`:

```
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.24.17-eks-f8587cb
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS EKS

**Comment by CobraFighter** [comment]
echo "Adding Helm repo: $name - $url"

**Comment by Ithrael** [comment]
I can reproduce this issue. When helm pull specifies a version, it will iterate through the existing versions and check them against the specified semantic constraints, (here)[ https://github.com/helm/helm/blob/main/pkg/repo/index.go#L218]. If it returns true, it will return the corresponding version. For the test case of this issue, this function returned true. 5600-build.222 is the latest version, and it passed the Constraint.Check of 5600-a-build.333, so 5600-build.222 was returned. I am not sure if 5600-build.222 should pass the semantic check of 5600-a-build.333, if it shouldn't, then there might be a problem with the (semver)[https://github.com/Masterminds/semver/] code.
