### ISSUE TITLE
Print title from `helm get values` as comment

### ISSUE THREAD

**Issue by lindhe** [helm/helm#12562]
When getting values from a release via `helm get values`, the first line of the output is a title that describes what values are shown:

```console
$ helm get values my-release
USER-SUPPLIED VALUES:
foo: bar
```

```console
$ helm get values --all my-release
COMPUTED VALUES:
foo: bar
```

This causes the output from `helm get values` to not be proper YAML. I propose we add `# ` before the title string, so that it is proper YAML. This way, it is easy for users to pipe the output directly to a file and get a valid (values) YAML file.

**Proposed solution**

```console
$ helm get values my-release
​# USER-SUPPLIED VALUES:
foo: bar
```

```console
$ helm get values --all my-release
​# COMPUTED VALUES:
foo: bar
```

Output of `helm version`:

```console
$ helm version
version.BuildInfo{Version:"v3.13.0", GitCommit:"825e86f6a7a38cef1112bfa606e4127a706749b1", GitTreeState:"clean", GoVersion:"go1.20.8"}
```

Output of `kubectl version`:

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.7", GitCommit:"84e1fc493a47446df2e155e70fca768d2653a398", GitTreeState:"clean", BuildDate:"2023-07-19T12:23:27Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.8+rke2r1", GitCommit:"395f0a2fdc940aeb9ab88849e8fa4321decbf6e1", GitTreeState:"clean", BuildDate:"2023-08-24T15:33:01Z", GoVersion:"go1.20.7 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

n/a

**Comment by mattfarina** [comment]
You can already get proper YAML out. Try the format `helm get values my-release -o yaml`. The `-o` is short for `--output`. You can specify yaml or json which are both good for machine interaction.

**Comment by lindhe** [comment]
Thanks a lot for the input! I had missed the `-o yaml` flag.

In my opinion, it would still be an improvement to have the default (which is `-o table`, I guess? Whatever kind of table this is...) produce valid YAML, since it is so very close already. But having `-o yaml` is certainly good enough. Feel free to close this if you do not think it is worth implementing.

**Comment by joejulian** [comment]
It might be worth considering for helm v4, but changing the default in v3 would break existing users.
