### ISSUE TITLE
Flux v2 | helm is not supporting helmrelease.helm.toolkit.fluxcd.io/v2

### ISSUE THREAD

**Issue by rohit6261** [helm/helm#12566]
We are using Azure Flux extension to install Flux v2 in AKS. We changed apiVersion to helmrelease.helm.toolkit.fluxcd.io/v2 in helm release file. When try to deploy this helmrelease file it is throwing error: "install CDR first". Below is our sample yaml. Any help here,

apiVersion: helmrelease.helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
name: nginx
spec:
releaseName: nginx

**Comment by hiddeco** [comment]
This is not the right place to ask this question, as the Helm project has not directly anything to do with https://github.com/fluxcd/flux2.

But to answer your question: there is no `helmrelease.helm.toolkit.fluxcd.io/v2` version within Flux, the latest version till date is `helmrelease.helm.toolkit.fluxcd.io/v2beta1`. See also https://fluxcd.io/flux/guides/helmreleases/ and https://fluxcd.io/flux/components/helm/helmreleases/.
