### ISSUE TITLE
Helm subchart version dynamic update

### ISSUE THREAD

**Issue by Durgaprasad-Polavarapu** [helm/helm#12579]
i'm looking for suggesstion on how to override Helm subchart version, we have around 20+ microservice charts which are using a sub-chart,  if new version is published on sub-chart , we have to update sub-chart version in all microservice charts which is quite repetetive.  Is there any best practice on this?

**Comment by Ithrael** [comment]
We have similar requirements, and we publish through GitOps. The general process is as follows:

1. Specify the version with a wildcard, such as WEB_CHART_SEMVER: "^0".
2. Pull the image and unzip it, using helm pull xxxxx --untar.
3. Get the chart's version number.
4. Pull another image and unzip it, using helm pull xxxx --untar.
5. Replace the version number with yq, using yq w -i "xxxxxxx/Chart.yaml" "appVersion" "0.1.1".
6. Deploy with helm.
