### ISSUE TITLE
How to upgrade if all helm secret has been deleted

### ISSUE THREAD

**Issue by nashiyue** [helm/helm#12598]
Output of `helm version`:
Version:"v3.7.0"

Output of `kubectl version`:
v1.20.15

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by nashiyue** [comment]
Use helm upgrade command and response: 
`

> Error: UPGRADE FAILED: "ranger" has no deployed releases

`
but the pod is running ok

**Comment by yxxhero** [comment]
@nashiyue try add `--install`

**Comment by nashiyue** [comment]
> @nashiyue try add `--install`

I use upgrade ranger ./ranger-chart --install， it works； It re-generate a sh.helm.release.v1.ranger.v1 secret, but i want to know whether it will influence those pods already running or just do one thing generate  the sh.helm.release.v1.ranger.v1 secret; if I use the chart is difference with those already running pods' charts; What will happen @yxxhero
