### ISSUE TITLE
gateway api template

### ISSUE THREAD

**Issue by kfox1111** [helm/helm#12603]
Now that the gateway api has hit v1.0, it would be nice if:
```
helm create foo
```

Included generating support for a gateway api HTTPRoute (https://gateway-api.sigs.k8s.io/api-types/httproute/) out of the box.

**Comment by yxxhero** [comment]
@kfox1111 PR is welcome.

**Comment by hegerdes** [comment]
I created a PR in #12912 that would fix this.

But if you need the `HTTPRoute` template now @kfox1111 you can copy the default route template from the PR and work with that. Just replace <CHARTNAME> withe the name of your chart

**Comment by idc77** [comment]
When I run `helm create <name>` there is no HttpRoute or Gateway template.
How do I invoke it?
