### ISSUE TITLE
helm template includes pre-delete hooks

### ISSUE THREAD

**Issue by jamiechapmanbrn** [helm/helm#12621]
When using helm template, I don't expect pre-delete hooks to be generated with the other manifests to apply.

Possibly a warning should be printed on stderr or pre-delete hooks should be dropped entirely here.

**Comment by MichaelMorrisEst** [comment]
Have you tried the '--no-hooks' flag

**Comment by jamiechapmanbrn** [comment]
I can't use no-hooks as some of the hooks in the repository in question are pre-install hooks which are necessary. I really can't see why anyone would want the pre-delete hooks by default.
