### ISSUE TITLE
Support the '--set-literal' option in 'helm diff'

### ISSUE THREAD

**Issue by lemonshir** [helm/helm#12636]
Hi team,

It's great that the `--set-literal` option is added to `helm install` and `helm upgrade` since [v3.12.0](https://github.com/helm/helm/releases/tag/v3.12.0). Could you help add this option to `helm diff install` and `helm diff upgrade` as well? Some users like me want to print the `diff` result before the `upgrade` with the same option list. Thanks!

Output of `helm version`:

```
$ helm version
version.BuildInfo{Version:"v3.13.2", GitCommit:"2a2fb3b98829f1e0be6fb18af2f6599e0f4e8243", GitTreeState:"clean", GoVersion:"go1.20.10"}
```

Output of `kubectl version`:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.11", GitCommit:"3cd242c51317aed8858119529ccab22079f523b1", GitTreeState:"clean", BuildDate:"2023-11-15T17:00:54Z", GoVersion:"go1.20.11", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
$ minikube version
minikube version: v1.25.2
commit: 362d5fdc0a3dbee389b3d3f1034e8023e72bd3a7
```

**Comment by jouve** [comment]
helm-diff is another project => https://github.com/databus23/helm-diff/

**Comment by yxxhero** [comment]
@lemonshir please post a new issue in https://github.com/databus23/helm-diff

**Comment by lemonshir** [comment]
Thanks guys. Will do.
