### ISSUE TITLE
Helm connects to remote k8s cluster

### ISSUE THREAD

**Issue by ForcemCS** [helm/helm#12648]
Since my k8s cluster has no nodes and only provides pods, I want to install helm on a node outside the cluster, but how does it interface with a remote K8S cluster?

**Comment by mattfarina** [comment]
Helm isn't something you install into a cluster. It's a tool, like kubectl, that you use when interacting with a cluster. It uses the same credential store as kubectl and communicates with a kubernetes cluster the same way kubectl does. It even uses the same underlying libraries.

Does that help?

**Comment by ForcemCS** [comment]
Of course，thanks for your help.
