### ISSUE TITLE
Helm does not include the digest for an oci chart in release metadata

### ISSUE THREAD

**Issue by apjoseph** [helm/helm#12647]
Helm is currently not including the oci digest in release metadata. This is extremely problematic when dealing with development versions of charts as there is no way to mechanism to determine what version of a chart was installed.

Example:
```
helm install eg oci://docker.io/envoyproxy/gateway-helm --version v0.0.0-latest -n envoy-gateway-system --create-namespace
```

Output of `helm version`:
```
version.BuildInfo{Version:"v3.10.1", GitCommit:"9f88ccb6aee40b9a0535fcc7efea6055e1ef72c9", GitTreeState:"clean", GoVersion:"go1.18.7"}
```
Output of `kubectl version`:
```
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.4-eks-8cb36c9`
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
`EKS`

**Comment by mattfarina** [comment]
While different from #4256, I think this goes along with it.

I'm going to mark this as a feature request. Help wanted. It should work for both OCI and non-OCI charts.

**Comment by busyboy77** [comment]
+1
