### ISSUE TITLE
How to handle replicas conflict between helm and HPA

### ISSUE THREAD

**Issue by tonyaw** [helm/helm#12650]
Output of `helm version`:
helm version
version.BuildInfo{Version:"v3.13.3", GitCommit:"c8b948945e52abba22ff885446a1486cb5fd3474", GitTreeState:"clean", GoVersion:"go1.20.11"}
Output of `kubectl version`:
kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.2
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Local server

I want to use "helm upgrade" to change the control of replicas from helm to HPA.
Based on Kubernetes official website, the best practice is to remove "replicas" field entirely:
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#migrating-deployments-and-statefulsets-to-horizontal-autoscaling
There is always "one-time degradation", and helm changes the replicas to 1.

I tried to apply "Client Side Apply" solution provided by above link to avoid this degradation, but always fails.
After some debug, I found helm's behavior is same in following two cases:
1. Change replicas to be empty("replicas:")
2. Change replicas by remove replicas field entirely. 
In both case, helm always sends PATCH command + {"spec":{"replicas":**null**}}, and it always leads Kubernetes to set replicas to default value 1.

Is it a helm bug or just by design?
In this way, how can I  switch the control of replicas from helm to hpa without service degradation(replicas is changed to 1)?

**Comment by mattfarina** [comment]
This has to do with the structure of your chart. If you want to use HPA, that needs to be added to the chart and the manifests in the chart need to be updated to use that. Then when you `helm upgrade` it would use HPA instead. This isn't a product of Helm. Rather it's a product of the contents of the chart you're trying to upgrade.

Does that make sense?

**Comment by tonyaw** [comment]
@mattfarina, Thanks for your info.
Question here is:
We need to upgrade helm chart to move the control of replicas from helm to HPA.
It means:
1. In old helm chart(chart1), manifest of deployment contains replicas field, and there is no manifest for HPA.
2. In new helm chart(chart2), remove replicas field of manifest of deployment, and add manifest of HPA.
Now, I need to upgrade from chart1 to chart2.
In this case, during this upgrade, we will meet degradation issue(replicas to be reduced to 1) as mentioned in my previous message.
How to avoid degradation here? :-)
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#migrating-deployments-and-statefulsets-to-horizontal-autoscaling provides two options to avoid degradation, but none of them can't work with helm.
Hope it is clearer now. :-)

**Comment by yannispgs** [comment]
I am currently experiencing the same issue. I want to remove that static `replicas` field, so I tried all the suggestions I found in posts and none have worked so far.

The HPA manifest is already in the Chart and has the Chart Deployment specified in the `scaleTargetRef` field. However, as soon as I remove the `spec.replicas` field from the Deployment, the `helm upgrade` (or `helm install`) command results in a Deployment having temporarily 1 Pod. The HPA then scales up, but I have this every single run, not just once...

I will use a workaround to get the current number of Pods for my Deployment and specify this as the `spec.replicas` value, but this is highly annoying.

**Comment by tonyaw** [comment]
@yannispgs,
If you already enabled HPA, the WR you mentioned will have problem during "hem rollback". 
Consider following case:
1. During installation, replicas is 10. (v1)
2. Before upgrade, replicas is scaled out to 20 by HPA.
3. Do upgrade(v1->v2), your WR is OK as replicas is no change. (v2)
4. Do rollback(v2->v1), replicas will be changed to 10 instead of 20.

My WR to avoid the replicas degradation is to patch helm release secret v1 to let helm think it is an upgrade from removed-replicas to removed-replicas.
It can work, but I hope helm can provide an official solution.

**Comment by tonyaw** [comment]
@mattfarina ,
I want to emphasize that helm's behavior is same in following two cases:
1. Change replicas to be empty("replicas:")
2. Change replicas by remove replicas field entirely.
In both cases, helm always sends PATCH command + {"spec":{"replicas":null}}(See one example as following).
It always leads Kubernetes to set replicas to default value 1.
Please help to confirm if it is a helm bug or just by design.

PATCH example:
ERge@@>ZA ;O4F
PATCH /apis/apps/v1/namespaces/test/deployments/test-app?fieldManager=helm HTTP/1.1
Host: 127.0.0.1:8001
User-Agent: Helm/3.13.3
Content-Length: 26
Accept: application/json
Content-Type: application/strategic-merge-patch+json
Accept-Encoding: gzip

{"spec":{"replicas":null}}

**Comment by tonyaw** [comment]
@mattfarina , any update from helm side?

**Comment by tonyaw** [comment]
@mattfarina , could you please help to give update from helm side?
Do you think my WA provided in following link(patch secret) is a feasible solution? 
https://github.com/helm/helm/issues/12650#issuecomment-1865767720

**Comment by max0ne** [comment]
If anyone still a short term fix, here's a script that makes Helm forget it manages the `replicas` field
https://gist.github.com/max0ne/c70068d780bc59ed2eaa4db99f3c55a2

**Comment by yannispgs** [comment]
The issue not resolved at all. It can only be reopened by repo maintainers ?

**Comment by luka5** [comment]
I was just running into the same issue. One option how we can mitigate the problem is to utilize the lookup function and dynamically loading the current value:

```
spec:
  replicas: {{ (lookup "apps/v1" "Deployment" .Release.Namespace "my-deployment").spec.replicas | default 1 }}
```

This way we keep the current value when running helm upgrade.

**Comment by BenjaminHerbert** [comment]
I ran into this problem when using `helm upgrade --force` with a deployment (without .spec.replicas) and autoscaling with HPA enabled. As the resource was _replaced_, Kubernetes set the default value to **1**, as the field was missing in the deployment. Shortly after, HPA took over and scaled it to `minReplicas` again.
I could observe this by making a kubectl watch and looking at the `.metadata.managedFields.fieldsV1["f:spec"]["f.replicas"].manager` field during the upgrade.
