### ISSUE TITLE
helm push report an error 

### ISSUE THREAD

**Issue by ForcemCS** [helm/helm#12665]
我按照此处的[文档](https://helm.sh/docs/topics/registries/)进行部署了一个本地仓库，使用的是registry镜像，它是正常工作的.
但是我执行下面截图的操作会产生报错，我无法定位到原因
<img width="713" alt="1703319250484" src="https://github.com/helm/helm/assets/57245053/7ec57d6f-55b9-424c-a3de-165488a96509">

**Comment by ForcemCS** [comment]
@yxxhero I have deployed a local repository using a registry mirror as per the documentation [here](https://helm.sh/docs/topics/registries/) and it is working fine.
However, when I run the screenshot below, I get an error, and I can't figure out why.
<img width="681" alt="1703406924184" src="https://github.com/helm/helm/assets/57245053/3986eb9d-ed3c-4a61-ab2e-38bea5d93c31">

**Comment by tomrss** [comment]
@ForcemCS According to the [docs](https://helm.sh/docs/topics/charts/#charts-and-versioning) the chart version should be semantic version, it seems that in your case the version is v1 that is not SemVer. Maybe you can try with 1.0.0 instead if v1.
