### ISSUE TITLE
Error: Kubernetes cluster unreachable with helm 3.0 

### ISSUE THREAD

**Issue by the4amfriend** [helm/helm#12682]
**Describe the bug**

I want to use helm with k3s but when I type helm install awx (full command below) for example I get:
Error: Kubernetes cluster unreachable

**To Reproduce**

Installed helm with apt-get using steps [here ](https://helm.sh/docs/intro/install/#from-apt-debianubuntu)
Install AWX using helm as per steps [here](https://ansible.readthedocs.io/projects/awx-operator/en/latest/installation/helm-install-on-existing-cluster.html)

**Expected behavior**
Installation should work.

**Actual behavior**
Error: Kubernetes cluster unreachable

**Additional context**

Logs from my failure and success below - found solution [here](https://github.com/k3s-io/k3s/issues/1126)

```
administrator@ub02:~$ helm install -n awx --create-namespace my-awx-operator awx-operator/awx-operator
Error: INSTALLATION FAILED: Kubernetes cluster unreachable: Get "http://localhost:8080/version": dial tcp 127.0.0.1:8080: connect: connection refused
administrator@ub02:~$ ls -lrt /etc/rancher/k3s/k3s.yaml
-rwxr--r-- 1 administrator administrator 2961 Jan  4 17:20 /etc/rancher/k3s/k3s.yaml
administrator@ub02:~$ kubectl config view --raw >~/.kube/config
administrator@ub02:~$ helm install -n awx --create-namespace my-awx-operator awx-operator/awx-operator
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/administrator/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/administrator/.kube/config
NAME: my-awx-operator
LAST DEPLOYED: Thu Jan  4 17:33:10 2024
NAMESPACE: awx
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
AWX Operator installed with Helm Chart version 2.10.0
administrator@ub02:~$
```

**Output of `helm version`:** Helm Chart version 2.10.0

**Output of `kubectl version`:** v1.28.5+k3s1

**Cloud Provider/Platform (AKS, GKE, Minikube etc.):**  Ubuntu 23.10

**Comment by banjoh** [comment]
I believe this works as intended. `kubectl` in a k3s cluster behaves this slightly different compared to upstread `kubectl`. As you can see, its a symlink to `k3s`

```sh
$ which kubectl
/usr/local/bin/kubectl
$ ls -al /usr/local/bin/kubectl
lrwxrwxrwx 1 root root 3 Jan  4 20:30 /usr/local/bin/kubectl -> k3s*
```

`kubectl get pods` is the same as `k3s kubectl get pods`
```sh
$ kubectl get pods
No resources found in default namespace.
$ k3s kubectl get pods
No resources found in default namespace.
```

I believe `k3s` binary references `/etc/rancher/k3s/k3s.yaml` config directly, but I have not looked at the code.

`helm` on the other hand will go looking for the config in `KUBECONFIG` env var or in `~/.kube/config` file which won't exist by default. This is why you are seeing the behaviour you described
