### ISSUE TITLE
Bug - https://raw.githubusercontent.com/helm/helm/v3.13.0/scripts/get-helm-3 has version issue

### ISSUE THREAD

**Issue by subhradeepnag** [helm/helm#12703]
Hi!

While I was installing helm on my docker container using this https://raw.githubusercontent.com/helm/helm/v3.13.0/scripts/get-helm-3, I noticed it actually installs version 3.13.3 and not 3.13.0

Also, if we try to install helm using this - https://raw.githubusercontent.com/helm/helm/v3.13.3/scripts/get-helm-3, it installs 3.13.1 and not 3.13.3

**Comment by weidongkl** [comment]
![image](https://github.com/helm/helm/assets/7512609/4a9675dc-7819-4f8d-859e-2bc1550cfac7)

now  https://get.helm.sh/helm-latest-version  is 3.13.1,do it download version 3.13.1.  the helm-latest-version should update to 3.13.3

**Comment by weidongkl** [comment]
you can use `export DESIRED_VERSION=v3.13.0` to download 3.13.0 heml

```bash
$ git branch 
* main
$ export DESIRED_VERSION=v3.13.0
$ ./get
get         get-helm-3  
$ ./get-helm-3 
Downloading https://get.helm.sh/helm-v3.13.0-linux-amd64.tar.gz
^C
$ 

```

**Comment by subhradeepnag** [comment]
Ahh...it worked!
Thanks!
