### ISSUE TITLE
Helm template prints out the list using white space separator instead of comma 

### ISSUE THREAD

**Issue by jhanbo** [helm/helm#12705]
I have a list in values.yaml file 

```yaml
regions:
- EU
- US
```

if I print this list in the template like this `regions: {{ .Values.regions }}`
`helm template` command will translate it to `regions: [EU US]`
I expect the output to be `regions: [EU, US]`

Is that the expected behaviour? 

Output of `helm version`:  v3.4.2

Thank you!

**Comment by mattfarina** [comment]
@jhanbo The templating engine, which is part of the Go standard library, does not automatically render a value as YAML. It doesn't know the context for the type of document. Can you try `{{ toYaml .Values.regions }}`?

**Comment by jhanbo** [comment]
@mattfarina It works!! 

Thank you!

**Comment by jhanbo** [comment]
I think we can close this issue
