### ISSUE TITLE
Imported values doesn't override subchart values

### ISSUE THREAD

**Issue by hedayat** [helm/helm#12730]
Output of `helm version`: 3.14.0

According to #12480, imported values should override sub-chart values (although, according to the docs it should also override parent chart values as noted [here](https://github.com/helm/helm/issues/12677#issuecomment-1878408783), but that's a separate issue), but as far as I can tell, they don't. It's great if at least you can override sub-chart values with imported ones.

**Comment by intetinte** [comment]
This is basically what is reported here:
https://github.com/helm/helm/issues/12511

**Comment by hedayat** [comment]
Thanks for the PR! I hope it is merged upstream if it fixes things. :(

#12511 seems a bit bigger than this one, so I think I'll leave it open to see what developers decide.

**Comment by intetinte** [comment]
I just did some investigation what went wrong in the helm application. All that is in the https://github.com/helm/helm/issues/12511
Zooming out a bit - it is basically "Imported values doesn't override subchart values" that I have reported

**Comment by hedayat** [comment]
Still active :P
