### ISSUE TITLE
Unable to run command from inside main container using Helm values.yaml

### ISSUE THREAD

**Issue by subhankar-banerjee** [helm/helm#12763]
I was trying to install Jenkins using Helm Chart version 4.7.2 ...I am using values.yaml for the installation ... now the query is if I need to run a script inside the main container like below ..how I can achieve this... in values.yaml file I couldn't find that section ...

Sample POD yaml 
==========================

` spec:
  containers:
  - args:
    - ....
	- ....
	command:
	- /jenkins-startup/startup.sh
	env:
	.
	.
	.
	.
	.   `

looks like we don’t have any options to call the shell script from the inside main container ..only option is to call from inside customInitContainer only .. then the query is how to run any command from inside the main container ?

is there any other alternative to achieve this ?

**Comment by z4ce** [comment]
For questions about specific helm charts you should reach out to the help chart authors. Try this for Jenkins: https://github.com/jenkinsci/helm-charts/issues

**Comment by subhankar-banerjee** [comment]
that helps ... thanks a lot ...

but can you please tell me what way I can run update-ca-certificates command inside the main container?
