### ISSUE TITLE
Question on Helm's MaxHistory limit during rollback 

### ISSUE THREAD

**Issue by varshaprasad96** [helm/helm#12764]
Helm cli by default sets the default MaxHistory limit during rollback to 10: https://github.com/helm/helm/blob/3fc9f4b2638e76f26739cd77c7017139be81d0ea/pkg/cli/environment.go#L42, whereas no limit is imposed by default in here: https://github.com/helm/helm/blob/f32a527a060157990e2aa86bf45010dfb3cc8b8d/pkg/storage/storage.go#L41-L43.

Is there a particular reason for this behaviour? Are there any use-cases where it is preferred to have it set to 0. 

Context: We use helm library for scaffolding a helm based operator. Though storing unlimited rollbacks is not a desired feature, just wanted to make sure the reason behind the decision to leave it to 0 by default.

**Comment by z4ce** [comment]
I suspect there isn't any specific reason. But @technosophos wrote the code so he would know :)
