### ISSUE TITLE
helm install not working - mac arm64

### ISSUE THREAD

**Issue by abhishekrhyme** [helm/helm#12778]
**helm install superset1 superset-0.12.3.tgz --debug**
install.go:214: [debug] Original chart version: ""
install.go:231: [debug] CHART PATH: /Users/mymac/helm/superset-0.12.3.tgz

client.go:142: [debug] creating 16 resource(s)
client.go:486: [debug] Starting delete for "superset1-init-db" Job
client.go:490: [debug] Ignoring delete failure for "superset1-init-db" batch/v1, Kind=Job: jobs.batch "superset1-init-db" not found
wait.go:66: [debug] beginning wait for 1 resources to be deleted with timeout of 5m0s
client.go:142: [debug] creating 1 resource(s)
client.go:712: [debug] Watching for changes to Job superset1-init-db with timeout of 5m0s
client.go:740: [debug] Add/Modify event for superset1-init-db: ADDED
client.go:779: [debug] superset1-init-db: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for superset1-init-db: MODIFIED
client.go:779: [debug] superset1-init-db: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
Error: INSTALLATION FAILED: failed post-install: 1 error occurred:
	* timed out waiting for the condition

helm.go:84: [debug] failed post-install: 1 error occurred:
	* timed out waiting for the condition

INSTALLATION FAILED
main.newInstallCmd.func2
	helm.sh/helm/v3/cmd/helm/install.go:154
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.8.0/command.go:983
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.8.0/command.go:1115
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.8.0/command.go:1039
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
	runtime/proc.go:267
runtime.goexit
	runtime/asm_arm64.s:1197

Output of `helm version`:
version.BuildInfo{Version:"v3.14.0", GitCommit:"3fc9f4b2638e76f26739cd77c7017139be81d0ea", GitTreeState:"clean", GoVersion:"go1.21.6"}

Output of `kubectl version`:
Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.25.2

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Docker-desktop

**Comment by z4ce** [comment]
You'll need to talk to the Helm chart author about the issue you're seeing.

**Comment by abhishekrhyme** [comment]
Do u have arm64 version of apache/superset

*Thanks and Regards,*

*Abhishek Sen*

*Contact: 925.367.1751*
