### ISSUE TITLE
Error: UPGRADE FAILED: unable to build kubernetes objects from current release manifest: resource mapping not found for name: "zookeeper" namespace: "zookeeper" from "": no  matches for kind "PodDisruptionBudget" in version "policy/v1beta1" ensure CRDs are installed first

### ISSUE THREAD

**Issue by PulaNaresh** [helm/helm#12803]
Output of `helm version`: version.BuildInfo{Version:"v3.13.1", GitCommit:"3547a4b5bf5edb5478ce352e18858d8a552a4110", GitTreeState:"clean", GoVersion:"go1.20.8"}

Output of `kubectl version`:  Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.26.6
WARNING: version difference between client (1.28) and server (1.26) exceeds the supported minor version skew of +/-1

Cloud Provider/Platform (AKS, GKE, Minikube etc.):   AKS

Hi All,

I made a change in the poddisruptionbudget.yaml file where I updated the Apiversion from policy/v1beta to policy/v1. After saving the file, I attempted to deploy these changes using the helm upgrade command, which I've shared below.

helm upgrade -i zookeeper zookeeper/ -f zookeeper/zookeeper-values.yaml -n zookeeper

Even pdb also running fine.

NAME        MIN AVAILABLE   MAX UNAVAILABLE   ALLOWED DISRUPTIONS   AGE
zookeeper   N/A                                 1                                          1                     6h

**Comment by antoinedeschenes** [comment]
`policy/v1beta1` was removed in k8s 1.25, so the existing release state isn't valid in your current cluster version.

You can patch your release with https://github.com/helm/helm-mapkubeapis and it should be able to upgrade.
