### ISSUE TITLE
Feature(/bug): .Files.Get on non exiting file can succeed

### ISSUE THREAD

**Issue by xrow** [helm/helm#12836]
I was using this line of code:

`{{ (tpl (.Files.Get "files/backup.sh") .) | indent 4 }}
`
But due to my mistake the file files/backup.sh did not exist. Not helm lint nor helm install was able to detect the error. I got rendered as a empty string. In my believe that shoudl be a proepr error message. 

Output of `helm version`:

[root@localhost scm]# helm version
version.BuildInfo{Version:"v3.14.2", GitCommit:"c309b6f0ff63856811846ce18f3bdc93d2b4d54b", GitTreeState:"clean", GoVersion:"go1.21.7"}

Output of `kubectl version`:
not relevant

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Any

**Comment by sabre1041** [comment]
This is the expected result as a file that is not present will return an empty byte array. If you would like an error to be thrown, you can first check to see if the file is indeed present, and if not, throw an error

**Comment by xrow** [comment]
@sabre1041 Thanks we can close it then. Though I am wondering about that use case of silencing ...
