### ISSUE TITLE
json schema validation technical challenges

### ISSUE THREAD

**Issue by onionringois** [helm/helm#12858]
Output of `helm version`:
version.BuildInfo{Version:"v3.14.1", GitCommit:"e8858f8696b144ee7c533bd9d49a353ee6c4b98d", GitTreeState:"clean", GoVersion:"go1.21.7"}

Output of `kubectl version`:
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  Not relevant

Hello everyone,
We are a team that uses Helm on a daily basis, including writing our own application charts and dependent libraries.

While researching and starting to work with the Helm template combined with the values.schema.json, we have come across two main challenges that prevent us from adopting this mechanism.

**1.Using go templating inside values.yaml file -**
We have found a creative way to use the _tpl_ command and create a dynamic and templated values.yaml. A very simple example of it with the default Helm create chart:

We create this helper function:
![image](https://github.com/helm/helm/assets/104347278/5e99a4f2-0bc0-471a-8303-4d90e4d75e85)
Then in the values.yaml, we use it:
![image](https://github.com/helm/helm/assets/104347278/d84cf084-9b5e-4509-ba55-d38d8a8fdb1a)
And then we call it in the deployment.yaml using the _tpl_ function:
![image](https://github.com/helm/helm/assets/104347278/c9c2a494-f919-4c0d-b4b4-af806cc2d4df)
The end template turns out like this:
![image](https://github.com/helm/helm/assets/104347278/d4f99620-c3b6-4e2d-bccf-a10fa18623b9)

This can make the values.yaml very dynamic (though not so easy to read...).

The problem that occurs from this is related to the JSON schema. The end values.yaml file includes some templating, while, as you can assume, I would like to validate the JSON schema against the templated values file. For example, suppose I had a utility to apply templating on the values.yaml file; I would want to validate the JSON schema against it.

Currently, to address this issue, we create an additional file in the chart whose sole purpose is to template our values, allowing us to obtain the true, untemplated version of them. This approach doesn't seem like the right solution to me.

**2. Dealing with library dependencies -**
We are working in an environment that includes 80-100 charts that use our own dependency chart (sometimes the dependency chart has a dependency chart of its own).

Our ideal situation is that while executing helm template, it will take the values.schema.json from each dependency and sub-dependency and validate the values against a merged JSON schema that includes all of the sub-schemas.

I am aware that this point can be solved very easily by copying and pasting the JSON schema to all of our "end charts," but we are worried about repetitive code and the wrong management of changes.

Similarly, in this scenario, we can generate a JSON schema on-demand from the schemas of the library dependencies and sub-dependencies. However, this approach involves iterating through the dependencies and their dependencies, which also doesn't seem like the right idea.

**Please,** 
if you have any tips or help regarding each of the two problems, reach out and comment. We would be more than happy to elaborate more on each problem.

**Comment by itay1213141** [comment]
+1, ran into a similar problem as well
