### ISSUE TITLE
helm dependency list prints warnings to stdout instead of stderr 

### ISSUE THREAD

**Issue by godfried** [helm/helm#12850]
When running `helm dependency list`, warnings are printed to stdout instead of stderr. For example:
```
$ helm dependency list charts/system-under-test 2> /dev/null 
NAME                    VERSION REPOSITORY                                              STATUS       
ska-tango-base          0.4.9   https://artefact.skao.int/repository/helm-internal      wrong version
ska-tango-util          0.4.10  https://artefact.skao.int/repository/helm-internal      wrong version
ska-tmc-mid             0.15.7  https://artefact.skao.int/repository/helm-internal      wrong version
ska-csp-lmc-mid         0.18.2  https://artefact.skao.int/repository/helm-internal      wrong version
ska-mid-cbf-mcs         0.12.18 https://artefact.skao.int/repository/helm-internal      wrong version
ska-sdp                 0.18.1  https://artefact.skao.int/repository/helm-internal      ok           
ska-tango-taranta       2.7.2   https://artefact.skao.int/repository/helm-internal      wrong version
ska-tango-tangogql      1.3.10  https://artefact.skao.int/repository/helm-internal      ok           
ska-log-consumer        0.1.6   https://artefact.skao.int/repository/helm-internal      ok           
ska-tango-alarmhandler  0.4.0   https://artefact.skao.int/repository/helm-internal      ok           
ska-tango-archiver      2.7.0   https://artefact.skao.int/repository/helm-internal      wrong version

WARNING: "charts/system-under-test/charts/ska-mid-cbf-tmleafnode-0.12.2.tgz" is not in Chart.yaml.
```

Warnings should be printed to stderr instead. The problem appears to be in this line:
https://github.com/helm/helm/blob/main/pkg/action/dependency.go#L64
The same writer is passed to both `printMissing` and `printDependencies`; `printMissing` should rather be passed a stderr writer. 
I'm happy to submit a PR for this change, if my suggestion is considered the correct behaviour.

Output of `helm version`:
`version.BuildInfo{Version:"v3.11.2", GitCommit:"912ebc1cd10d38d340f048efaf0abda047c3468e", GitTreeState:"clean", GoVersion:"go1.18.10"}`
Output of `kubectl version`:
`Client Version: v1.26.3
Kustomize Version: v4.5.7
Server Version: v1.28.2`
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Minikube

**Comment by robertsirc** [comment]
To fix this it would be a breaking change. Users might not be using helm and expect this result but not as an error. Agree it probably should be fix.
