### ISSUE TITLE
Compare new values.yaml and old values.yaml during helm upgrade

### ISSUE THREAD

**Issue by rayalaka** [helm/helm#12870]
Is there a way to compare new values.yaml and old values.yaml during helm upgrade.

My requirement is that helm upgrade should have an intelligence to act according on comparing existing values (installed chart) and upgrade values.yaml (upgraded chart)

Output of `helm version`: version.BuildInfo{Version:"v3.14.1", GitCommit:"e8858f8696b144ee7c533bd9d49a353ee6c4b98d", GitTreeState:"clean", GoVersion:"go1.21.7"}

Output of `kubectl version`: Client Version: v1.28.5
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.5+k3s1

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  K8s, OpenShift Container Platform, K3s

**Comment by BenHesketh21** [comment]
It might not match up with what you need but there is a helm diff plugin. https://github.com/databus23/helm-diff It can be used to show the difference an upgrade would make in manifests.
