### ISSUE TITLE
Docs: Add note for prerelease versions about invalid leading zeros

### ISSUE THREAD

**Issue by cpboyd** [helm/helm#12872]
The [helm docs](https://helm.sh/docs/chart_best_practices/dependencies/#prerelease-versions) state:

> The following provides a pre-release as well as patch-level matching: `version: ~1.2.3-0`

Per #9356, leading zeros are invalid (now enforced by helm 3.5.2) so it seems appropriate to add a note to this page that the specified example isn't valid for an actual version.

Or change the example to `version: ~1.2.3-1` instead, but the a note would still seem beneficial.

**Comment by z4ce** [comment]
Are you sure Helm actually has a problem with this? As per the spec, it looks valid: https://semver.org/#spec-item-9

**Comment by cpboyd** [comment]
@z4ce I'm not suggesting it's a **_technical_** problem.

I'm just stating that it seems problematic to use `version: ~1.2.3-0` in the docs when `1.2.3-0` in and of itself isn't valid anymore.

This could easily be changed to something valid like `version: ~1.2.3-1` or `version: ~1.2.3-4`

**Comment by cpboyd** [comment]
Ok. So after checking, that is in fact valid but the error is confusing:
```
➜ helm package --version "1.2.3-0"api
api-1.2.3-0.tgz
➜ helm package --version "1.2.3-01" helm/api
Error: Version segment starts with 0
```

The error indicates _**starts with 0**_ is the issue, rather than explicitly stating that the problem is leading zeros.

**Comment by z4ce** [comment]
Agree an error indicating leading zeros would be better.
