### ISSUE TITLE
OCI image annotation org.opencontainers.image.created should use timestamp of pushed TGZ instead of current time

### ISSUE THREAD

**Issue by patrikbeno** [helm/helm#12884]
```
helm create mychart
helm package mychart

# initial push [ok]
helm push mychart*tgz oci://registry:5000 --plain-http

# now, following should be a noop, but it pushes new manifest with different digest
helm push mychart*tgz oci://registry:5000 --plain-http
```

subsequent helm push calls always pushes new manifest with different digest because of change in `org.opencontainers.image.created`

There is no change in config (same digest), no change in layers (same digest). And only change in manifest is `org.opencontainers.image.created` annotation.

This, for example, complicates detection of actual change in mutable tags, and produces useless objects in registry.

At this point, helm push operation should be idempotent, it should even skip push if there are no changes to be pushed.

Helm 3.14.3

**Comment by z4ce** [comment]
This seems like overall a good idea to me. Not sure we could do this in a minor release or not. In theory someone could be relying on a workflow that is pushing identical charts with new timestamps.. although it does feel like it would be rare or non-existent.

**Comment by sabre1041** [comment]
I will take a look at this issue in the next few days
