### ISSUE TITLE
Helm template for multiple nginx domain template

### ISSUE THREAD

**Issue by rahulsyal92** [helm/helm#12898]
Hello Team,

Hope you are fine..
 I  am working on one Kubernetes application and we are using helm chart for multiple environment . 
I have nginx running on a pod and nginx having five domain for each environment . These nginx domain are different for every environment. we decide to mount these nginx configuration through configmap.
We need helm template for this scenerio.
Could you pls  share template to fix .

Pls revert if any further info required.

**Comment by z4ce** [comment]
If you need assistance with specific charts you should reach out those chart authors.
