### ISSUE TITLE
Programmatically search/list all charts in a repository

### ISSUE THREAD

**Issue by lu-jason** [helm/helm#12897]
Just wondering if it was possible to programmatically call the equivalent of `helm search repo <repo-name>`  programmatically in the Helm code.

From looking at the code initially, it seems like all the code for searching for charts within a repository is all contained in the cmd/ folder, i.e. https://github.com/helm/helm/blob/v3.14.3/cmd/helm/search_repo.go and is all private to cobra.

Is there something else that I am missing?

Cheers.

**Comment by chris-kapstan** [comment]
Found this issue while trying to do the same thing, ended up using this workaround for now
```
chartRepo, err := repo.NewChartRepository(&repo.Entry{URL: url}, getter.Providers{
      {
          Schemes: []string{"http", "https"},
          New:     func(options ...getter.Option) (getter.Getter, error) { return getter.NewHTTPGetter(options...) },
      },
  })
  if err != nil {
      return nil, err
  }

  file, err := chartRepo.DownloadIndexFile()
  if err != nil {
      return nil, err
  }

  data, err := os.ReadFile(file)
  defer os.Remove(file)

  err = yaml.Unmarshal(data, chartRepo.IndexFile)
  if err != nil {
      return nil, err
  }
```
