### ISSUE TITLE
Helm on RHEL 8.9 bash: helm: command not found

### ISSUE THREAD

**Issue by JOkaru13** [helm/helm#12890]
Hello,

         I have installed Helm on RHEL8.9 with Binary Releases but get the error "bash: helm: command not found"

[root@ linux-amd64]# chmod +x helm /usr/local/bin/
[root@ linux-amd64]# helm version
bash: helm: command not found

        Another way to install it? please advise.

Thanks,
JOkaru13

**Comment by mahmut-Abi** [comment]
maybe /usr/local/bin is not in  your $PATH .
you can try "echo $PATH" to confirm this.

**Comment by JOkaru13** [comment]
Hello mahmut-Abi,

         Thanks for suggest, I move the helm to /usr/local/sbin  can run normally. but for the helm support version

3.14.3 is support kubernetes 1.29.2 

https://helm.sh/docs/topics/version_skew/

       After run deploy nginx-ingress controller with helm install ingress-nginx ingress-nginx/ingress-nginx --set xxxxxxxx 
getting the error about version are not support.  Maybe I will downgrade kubernetes version right?

_Error: INSTALLATION FAILED: Kubernetes cluster unreachable: Get "https://10.xx.xxx.xx::64436443/version": Request denied_

Thanks,

**Comment by mahmut-Abi** [comment]
I think you need confirm kubectl command run correctly.
