### ISSUE TITLE
BUG: helm non-deterministic random use of charts files or tgz

### ISSUE THREAD

**Issue by ramalhais-sky** [helm/helm#12955]
helm randomly uses either the files under charts directory, or the .tgz files it generated previously from helm dependency update

To work-around this bug, always run:
helm dependency update
before running helm template or install or upgrade

**Comment by JoniJnm** [comment]
I use `helm dependency build .` before the `helm upgrade`. There is a `--dependency-update` argument but seems like it doesn't work when the tgz chart file is downloaded.

To reproduce the problem:
* Create a chart empty with one dependency (mysql, for example)
* Commit and push the chart.yaml and chart.lock files to a repository (the charts folder should be ignored in git)
* Create a new branch with a new version of the chart
* Commit and push the chart.yaml and chart.lock

Now if you change between branches and run

`helm upgrade --install --dependency-update my-chart .`

You can see how helm is reusing the tgz chart file even if the version doesn't match with the chart.lock file
