### ISSUE TITLE
Helm unable to update the dependency chart

### ISSUE THREAD

**Issue by Shobhit29** [helm/helm#12995]
I am not using the OCI registry for my Helm charts. When I am trying to use the command `helm dep up` I am getting error as below:
```
Getting updates for unmanaged Helm repositories...
Error: could not find protocol handler for: alias
```
It seems it is looking for oci:// handler, but unable to find in the Chart/requirements file. Is there an option where i can disable the OCI or tell helm to use the legacy helm repo.

Output of `helm version`:  3.14.4

Output of `kubectl version`: v1.28.2

**Comment by banjoh** [comment]
@Shobhit29 do you have an example `Chart.yaml` that you can share for us to reproduce this?
