### ISSUE TITLE
Can not use helm binary

### ISSUE THREAD

**Issue by njwgroeneveld** [helm/helm#13003]
Hi all, Im facing some issues while installing and especially using helm.
Is somebody who can support me? Im using ubuntu on my raspberry Pi
Here are my stats

uname -a:
Linux student-desktop 6.8.0-1004-raspi #4-Ubuntu SMP PREEMPT_DYNAMIC Sat Apr 20 02:29:55 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

file /usr/local/bin/helm
/usr/local/bin/helm: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=hlhj6ZxuF2rHXUR8U1kv/o98cLzuYIE1DSSja5_ac/9YcBg8sZXScQ_0eHyyGm/H0_V3FfeMyB-jnZT4jkB, stripped

Output of `helm version`:
bash: /usr/local/bin/helm: cannot execute binary file: Exec format error

Output of `kubectl version`:
Client Version: v1.29.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Minikube

Hope somebody can support me on this,
Cheers!

**Comment by yxxhero** [comment]
```
cannot execute binary file: Exec format error
```
see above. it means the binary format is not match your os.


and yor os is `aarch64`. please try to use `https://get.helm.sh/helm-v3.14.4-linux-arm64.tar.gz`
