### ISSUE TITLE
Not able to install helm via get-helm3 for 3.15.0 version

### ISSUE THREAD

**Issue by bharatgoelharness** [helm/helm#13024]
bash-4.4# curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
bash-4.4# ls
get_helm.sh 
bash-4.4# chmod 700 get_helm.sh
bash-4.4# 
bash-4.4# ./get_helm.sh --version v3.15.0
Downloading https://get.helm.sh/helm-v3.15.0-linux-amd64.tar.gz
Verifying checksum... SHA sum of /tmp/helm-installer-iHsVy1/helm-v3.15.0-linux-amd64.tar.gz does not match. Aborting.
Failed to install helm with the arguments provided: --version v3.15.0
Accepted cli arguments are:
        [--help|-h ] ->> prints this help
        [--version|-v <desired_version>] . When not defined it fetches the latest release from GitHub
        e.g. --version v3.0.0 or -v canary
        [--no-sudo]  ->> install without sudo
        For support, go to https://github.com/helm/helm.

**Comment by yxxhero** [comment]
there is no v3.15.0 version. latest rc version is v3.15.0-rc.2
