### ISSUE TITLE
Update backward compatibility promise in CONTRIBUTING.md to reflect HIP 0004

### ISSUE THREAD

**Issue by banjoh** [helm/helm#13045]
In the [Semantic Versioning section of CONTRIBUTING.md](https://github.com/helm/helm/blob/main/CONTRIBUTING.md#semantic-versioning) document, the backward compatibility promise does not align to [HIP-0004](https://github.com/helm/community/blob/main/hips/hip-0004.md)

### CONTRIBUTING.md
> We also try very hard to not change publicly accessible Go library definitions inside of the `pkg/` directory of our source code.
- This ought to say public functions MUST not be changed in the `pkg/` directory

> Go libraries inside of `pkg/` SHOULD remain backward compatible, though code inside of `cmd/` and `internal/` may be changed from release to release without notice.
- SHOULD ought to be changed to MUST
- Question: Since `cmd/` is meant to be internal code, should have all code that isn't meant to be a subcommand live in `cmd/helm/internal`, to allow ease of sharing code within the `cmd/helm` package, but ensure no one can import that code?

The section should point to HIP-0004

### HIP-0004
> programs using the Helm Go API will continue to compile
- Should this also include changing functionality? If a public function/method should probably not change overall internal functionality e.g if a change removes previous functionality and makes the function a no-op, perhaps this should not be allowed.

**Comment by scottrigby** [comment]
@banjoh thanks for making this follow-up issue! Adding my replies from slack here for better transparency.

> Should this also include changing functionality?

HIP-0004 covers that point, indirectly, by linking to another article that covers it:

> exported Go APIs will remain compatible as per [this article](https://blog.golang.org/module-compatibility)

that article, under “Add configuration methods”, says:

> So far we’ve talked about overt breaking changes, where changing a type or a function would cause users’ code to stop compiling. However, behavior changes can also break users, even if user code continues to compile…

**Comment by banjoh** [comment]
I'll incorporate your suggestions in a PR.

Leaving the description as is, else comments won't make sense afterwards :)
