### ISSUE TITLE
Helm version for v3.15.0 reports v3.15.0-rc.2

### ISSUE THREAD

**Issue by TheMeier** [helm/helm#13040]
```
$ tar xzvf helm-v3.15.0-linux-amd64.tar.gz
linux-amd64/
linux-amd64/README.md
linux-amd64/LICENSE
$ linux-amd64/helm version
version.BuildInfo{Version:"v3.15.0-rc.2", GitCommit:"c4e37b39dbb341cb3f716220df9f9d306d123a58", GitTreeState:"clean", GoVersion:"go1.22.3"}

```

**Comment by yxxhero** [comment]
@mattfarina could you take an review? thanks so much.

**Comment by sabre1041** [comment]
Confirmed, seeing the same on the `darwin arm64` artifacts

**Comment by erik-bershel** [comment]
We've temporary pinned 3.14.4 for GitHub Actions / Azure DevOps. Please drop a confirmation that it's expected behaviour for us to unlock updates of Helm. Thanks in advance.
- https://github.com/actions/runner-images/pull/9867

**Comment by mattfarina** [comment]
This is interesting because the both tags point to the same commit. When this was created, the release tag was added and CI did the build. So, how do we get CI to handle the tags properly?

**Comment by mattfarina** [comment]
If I look at the `build-cross` make target the version comes from ...

```
git describe --tags --abbrev=0 --exact-match 2>/dev/null
```

When I run this in Linux environments, I get the release version. I'm not able to duplicate it.

But, the wrong version shows up in the [release job](https://github.com/helm/helm/actions/runs/9102189102/job/25021198797) and the release job checkout out the exact right tag.

We need to update the build job (GHA workflow) to make sure the `VERSION` environment variable is the tag, I think?

**Comment by yxxhero** [comment]
@mattfarina maybe we can rerelease?

**Comment by TheMeier** [comment]
Uhm isn't that even worse that homebrew ships a different binary?

**Comment by robertsirc** [comment]
@TheMeier this isn't unusual in open source.

**Comment by mattfarina** [comment]
@TheMeier open source is about the source code rather than the builds. For example, pretty much everyone uses curl. The curl projects does not distribute binaries. Everyone gets them from their OS, package manager, etc. It's not just acceptable but expected to have different builds of the same source.

**Comment by mattfarina** [comment]
The pull request at https://github.com/helm/helm/pull/13059 provides a simple fix. The tag is passed in as the explicit version rather than being automatically detected.

**Comment by mattfarina** [comment]
3.15.1 is out and it contains the proper version. Problem fixed.
