### ISSUE TITLE
Helm Apt install/package is broken and can't be installed

### ISSUE THREAD

**Issue by stephenmelrose** [helm/helm#13046]
Output of `helm version`: NA
Output of `kubectl version`: NA
Cloud Provider/Platform (AKS, GKE, Minikube etc.): NA, although this is within CircleCI

I wasn't sure where to post this. I couldn't find a Twitter account. I'm not sure if this is specific to CircleCI but Helm currently won't install for is due to an issue with the package hosting.

```
Get:12 https://baltocdn.com/helm/stable/debian all/main amd64 Packages [4,604 B]
Err:12 https://baltocdn.com/helm/stable/debian all/main amd64 Packages
  File has unexpected size (4684 != 4604). Mirror sync in progress? [IP: 185.93.1.246 443]
  Hashes of expected file:
   - Filesize:4604 [weak]
   - SHA256:fb51e86d451f4f0732afc79a8e12e6e225320c7598206ea00e142addc32e3081
   - MD5Sum:0483e492458f061c8b2c51dcc7c55fc1 [weak]
  Release file created at: Thu, 22 Feb 2024 14:08:59 +0000
```

This is our Helm install,

```
curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
sudo apt-get update
sudo apt-get install -y helm
```

**Comment by claco** [comment]
I assume, on the yearly type issue?

https://github.com/helm/helm/issues/11937

**Comment by stephenmelrose** [comment]
@mattfox I’m not at home at the moment so I can’t verify if this is ongoing but any thoughts?

**Comment by stephenmelrose** [comment]
@claco Still happening for us and pretty consistently.

**Comment by mattfox** [comment]
I believe a CDN cache wasn't purged after the 3.15.0 release. It's been purged now and should work again.

**Comment by stephenmelrose** [comment]
Confirmed. Thanks @mattfox
