### ISSUE TITLE
add / update Supported Kubernetes Versions page to have 3.15 version

### ISSUE THREAD

**Issue by doribd** [helm/helm#13079]
Nothing more than just update the supported k8s versions page.

**Comment by yxxhero** [comment]
@doribd PR is welcome.

**Comment by doribd** [comment]
@yxxhero can i be sure that 3.15 is for k8s 1.30-1.27 and that this is only a document fix ? as per the tags of 3.15.x i can't see it in the release notes.

**Comment by mattfarina** [comment]
This has already been fixed so I'm closing the issue.
