### ISSUE TITLE
Update package go to version 1.22.4 

### ISSUE THREAD

**Issue by louisjimenez** [helm/helm#13139]
Please update Go version to 1.22.4 https://go.dev/doc/devel/release#go1.22.0

**Comment by mattfarina** [comment]
I just pulled down the latest release (in this case [v3.15.2](https://github.com/helm/helm/releases/tag/v3.15.2)) and inspected the version of Go used on two of the builds. The results showed 1.22.4.

<img width="195" alt="Screenshot 2024-06-26 at 5 48 22 PM" src="https://github.com/helm/helm/assets/62991/46c9e531-8aaa-42f1-9e21-927fc65cf52e">

<img width="161" alt="Screenshot 2024-06-26 at 4 38 21 PM" src="https://github.com/helm/helm/assets/62991/24db3fec-39c0-42d3-9b98-4c9aab871371">

I'm unable to reproduce the issue you're seeing with an outdated Go.

**Comment by louisjimenez** [comment]
3.15.2 addresses this. Thanks!
