### ISSUE TITLE
Keda ScaledObject not updated at helm upgrade

### ISSUE THREAD

**Issue by heresie** [helm/helm#13132]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.15.2", GitCommit:"1a500d5625419a524fdae4b33de351cc4f58ec35", GitTreeState:"clean", GoVersion:"go1.22.4"}
```

Output of `kubectl version`:
```
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.14+rke2r1
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): On-Premise RKE2

Keda version: 2.14.2

---

Hello everybody 👋,

We are currently experiencing some curious behavior from helm when trying to update a release that contains [Keda](https://github.com/kedacore/keda) `ScaledObject`.

1. I have manifests with a `Deployment` and a `ScaledObject`, the `ScaledObject` has `maxReplicaCount=10`
2. I deploy a new Release through Helm Chart.
3. For some reason, I need to edit the `ScaledObject` to change the `maxReplicaCount`. I do it with kubectl, updating to `maxReplicaCount=5`
4. At some point, I need to reset `maxReplicaCount` to default project values, so I redeploy the Chart again
5. The `ScaledObject` has not been reseted to `maxReplicaCount=10` and stayed at previous value (`5`)

Example output: 
```
Cleaning previous installation ...
release "keda-issue-example" uninstalled
Applying Helm Chart ...
Release "keda-issue-example" does not exist. Installing it now.
NAME: keda-issue-example
LAST DEPLOYED: Thu Jun 20 09:55:45 2024
NAMESPACE: keda-issue-example-helm
STATUS: deployed
REVISION: 1
TEST SUITE: None
Sleep 2 seconds ...
Current HPA & ScaledObject status ...
HorizontalPodAutoscaler maxReplicas=10
ScaledObject            maxReplicaCount=10
Changing ScaledObject maxReplicaCount to 5 ...
scaledobject.keda.sh/myapp patched
Sleep 2 seconds ...
Current HPA & ScaledObject status ...
HorizontalPodAutoscaler maxReplicas=5
ScaledObject            maxReplicaCount=5
Reapplying Helm Chart ...
Release "keda-issue-example" has been upgraded. Happy Helming!
NAME: keda-issue-example
LAST DEPLOYED: Thu Jun 20 09:55:50 2024
NAMESPACE: keda-issue-example-helm
STATUS: deployed
REVISION: 2
TEST SUITE: None
Sleep 2 seconds ...
Current HPA & ScaledObject status ...
HorizontalPodAutoscaler maxReplicas=5
ScaledObject            maxReplicaCount=5
```

If I do the same but using `kubectl` only, the `maxReplicaCount` value is well updated : 

```
Cleaning previous installation ...
namespace "keda-issue-example" deleted
Applying manifests ...
namespace/keda-issue-example created
deployment.apps/myapp created
scaledobject.keda.sh/myapp created
Sleep 2 seconds ...
Current HPA & ScaledObject status ...
HorizontalPodAutoscaler maxReplicas=10
ScaledObject            maxReplicaCount=10
Changing ScaledObject maxReplicaCount to 5 ...
scaledobject.keda.sh/myapp patched
Sleep 2 seconds ...
Current HPA & ScaledObject status ...
HorizontalPodAutoscaler maxReplicas=5
ScaledObject            maxReplicaCount=5
Reapplying manifests ...
deployment.apps/myapp unchanged
scaledobject.keda.sh/myapp configured
Sleep 2 seconds ...
Current HPA & ScaledObject status ...
HorizontalPodAutoscaler maxReplicas=10
ScaledObject            maxReplicaCount=10
```

I made the demonstration material to reproduce this bug in a dedicated repository: https://github.com/heresie/scaledobject-helm-kubectl-issue

What do you think? Have I missed something?

Thanks in advance

**Comment by yxxhero** [comment]
@heresie you should update values if you want update release. for this case. you can try set `maxReplicaCount=11`.

**Comment by yxxhero** [comment]
> Hello @yxxhero,
> 
> Thank you for your response.
> 
> I don't understand why I should update the value of `maxReplicaCount`. I just need to rollback manual changes and set the `maxReplicaCount` to default Chart values.
> 
> You mean that if I don't change the value Helm is not able to compare the current value in the Kube object and the desired state in the Chart?

@heresie yes.

**Comment by heresie** [comment]
I found another way to force the recreation of the `ScaledObject` resource in this thread https://github.com/helm/helm/issues/7082.

By doing the upgrade with `--force` it works well.
