### ISSUE TITLE
helm install/upgrade error - unable to retrieve credentials

### ISSUE THREAD

**Issue by manas-suleman** [helm/helm#13179]
Output of `helm version`: v3.15.2

Output of `kubectl version`: v1.28.2-3598+6e2789bbd58938-dirty

Cloud Provider/Platform (AKS, GKE, Minikube etc.): BareMetal

Hi,

We have a baremetal OKD system (Openshift upstream) and I've been using helm to install and manage Github Actions Runner Controller and it had been working just fine. It had been installed in Ubuntu20 WSL. I recently had to export my WSL to a new system and while everything else is working just fine (CLI login to OKD and other OKD operations) but helm is having issues.

I'm trying to run below command:
`helm upgrade arc-runner-set-dind --namespace arc-runners -f values.yaml oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set`

Getting the following error:
```
Error: GET "https://ghcr.io/v2/actions/actions-runner-controller-charts/gha-runner-scale-set/tags/list": unable to retrieve credentials
helm.go:84: [debug] GET "https://ghcr.io/v2/actions/actions-runner-controller-charts/gha-runner-scale-set/tags/list": unable to retrieve credentials
```
I think the issue may be exclusive to Github Registry because I can use use helm charts hosted outside of it. I've tried reinstalling helm (through multiple sources like `apt` or installer script etc.), and deleting the cache and config files but it is simply not working. I've exhausted my options and not sure what else could be the problem so reaching out here for support. Really appreciate any direction I can get.

Thanks,

**Comment by yxxhero** [comment]
@paolo-depa @manas-suleman did you upgrade your helm? is it same helm version before?

**Comment by paolo-depa** [comment]
> @paolo-depa @manas-suleman did you upgrade your helm? is it same helm version before?

I installed from scratch v3.15.2, then upgraded to v3.15.3, both showing the issue.
Then I removed helm and installed backward one by one all the official releases up to v3.14.2 - nope.

I need to say that opening a Cloud Shell on Azure and running:
`helm upgrade  --debug  --install trento-server oci://registry.suse.com/trento/trento-server `
it works: the only difference I could spot is with the underlying version of go

```
-- Azure cloud shell
# helm version
version.BuildInfo{Version:"v3.14.2", GitCommit:"", GitTreeState:"clean", GoVersion:"go1.21.6"}

-- Local shell
#helm version
version.BuildInfo{Version:"v3.14.2", GitCommit:"c309b6f0ff63856811846ce18f3bdc93d2b4d54b", GitTreeState:"clean", GoVersion:"go1.21.7"}
```

**Comment by aiciobanu** [comment]
Hello,

I had the same problem, and after browsing through several issues I have stumbled on #13092. 

It seems that Helm uses the same file as docker for credentials (`~/.docker/config.json`), and if it doesn't exist it will search for helm's default registry config path (you can also provide the global option  `--registry-config`).

When installing Docker desktop, the `config.json` file is created automatically, thus, people don't run into this issue that often. I ran into it by chance after removing the application from my system.

I have bypassed this issue by creating the `~/.docker/config.json` file:
```
{
  "auths": {}
}
```

The registries I am using are public and do not require credentials.

Hope this helps.

**Comment by manas-suleman** [comment]
@yxxhero yes. I tried with latest versions as well as installing helm from several resources. helm works just fine in powershell on the same system that has helm inside WSL not working.
@aiciobanu thanks for the suggestion but unfortunately it didn't fix the issue for me even though I'm also using a public registry.

**Comment by paolo-depa** [comment]
Thanks @aiciobanu, removing that file solved for me

**Comment by manas-suleman** [comment]
Thanks @paolo-depa for the hint, removing the file fixed it

**Comment by MikeSpreitzer** [comment]
@paolo-depa , @ALL-SPACE-Anas: removing _what_ file fixed your problem? I am getting a report of this problem from someone else, trying to debug indirectly.

**Comment by scottrigby** [comment]
> [@paolo-depa](https://github.com/paolo-depa) , [@ALL-SPACE-Anas](https://github.com/ALL-SPACE-Anas): removing _what_ file fixed your problem? I am getting a report of this problem from someone else (who is using `helm` 3.17.0 on Ubuntu 22.04.5), trying to debug indirectly.

They were referring to `~/.docker/config.json`. See https://github.com/helm/helm/issues/13179#issuecomment-2241269742

See https://helm.sh/docs/topics/registries/#commands-for-working-with-registries

**Comment by MikeSpreitzer** [comment]
I have been happily using `helm` while `~/.docker/config.json` does not exist, and also while it exists but says nothing about the particular OCI registry holding my Helm charts. Is there something that I can put in my `~/.docker/config.json` that will provoke error messages like the one in this Issue? I tried to accomplish that and failed.

**Comment by SadaGowda** [comment]
While using the WSL Ubuntu, the ~/.docker/config.json did not exist, created one and still doesn't resolve the issue, @nx-sbourdeaud any suggestion value for wsl ubuntu
