### ISSUE TITLE
Build a "canary" image for the helm client alone

### ISSUE THREAD

**Issue by sebgoa** [helm/helm#1320]
there is a Docker image for tiller, but we could use a docker image for the client 'helm'.

Would it be possible to add that in the automated build ?

**Comment by technosophos** [comment]
What would be base image for this be?

**Comment by technosophos** [comment]
I guess we'd want `kubectl` in there, too, right?

**Comment by sebgoa** [comment]
helm does not need kubectl client side does it ? only tiller.

the idea is to run helm commands as k8s jobs (was mentioned by someone else). It would solve auth issues...

**Comment by technosophos** [comment]
In that case, no it probably doesn't need `kubectl`. I had been envisioning a general-purpose Docker container.

**Comment by technosophos** [comment]
Hey @devth: Do you have anything that might be worth contributing here? I know you've been doing quite a bit with Docker images for Helm.

**Comment by devth** [comment]
Here's [my Dockerfile](https://github.com/devth/helm-docker/blob/master/Dockerfile) if it helps. I used `FROM google/cloud-sdk` for convenience but it sounds like you wouldn't want to do that.

I haven't upgraded it to latest yet.

**Comment by technosophos** [comment]
@devth I don't have any strong opinions about the base image (though I know some community members do have strong opinions about that kind of thing). I did notice that your Docker image seems to be the most popular by at least a few hundred pulls. I'll see how far we can get with your image, and we'll ping you on the PR.

**Comment by technosophos** [comment]
There has recently been renewed interest in this, and I believe @lachie83 even built a few images.

**Comment by lachie83** [comment]
I published mine here `docker pull lachlanevenson/k8s-helm` I could take a crack at getting CI setup.

**Comment by pigmej** [comment]
any updates on that?

**Comment by bacongobbler** [comment]
See current discussion in #1929.

**Comment by bacongobbler** [comment]
See https://github.com/helm/helm/pull/1929
