### ISSUE TITLE
helm-occur 

### ISSUE THREAD

**Issue by pietro-coretto** [helm/helm#13210]
`helm version`:
Installed from MELPA  helm-20240726.954

`emacs version:`
GNU Emacs 29.4 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo
 version 1.16.0) of 2024-06-24

When I search over a buffer using  `M-x helm-occur` I get the following error

```
helm-grep--ag-command: Wrong type argument: stringp, nil
```

**Comment by ramnes** [comment]
You're not in the right repository. You're issue is about Emacs Helm, but you're in Kubernetes lands here. :)

**Comment by banjoh** [comment]
@pietro-coretto I think the correct place you want to post your questions is https://github.com/emacs-helm/helm/issues

**Comment by pietro-coretto** [comment]
sorry I'll posto there

**Comment by ramnes** [comment]
Close the issue maybe? :)

**Comment by pietro-coretto** [comment]
I posted in the wrong place, moved the issue to https://github.com/emacs-helm/helm/issues
