### ISSUE TITLE
helm template not creating as helm install

### ISSUE THREAD

**Issue by jaswanth2273** [helm/helm#13234]
-------------
deployment file 

{{- $replicaCount := .Values.replicaCount | int }}
{{- range $i, $e := until  $replicaCount  -}}
{{- $name := printf "app%02d" (add $e 1) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          image: nginx
{{- end }}

-----------------------------
values.yaml 
replicaCount: 4

------
expected output: creating 4 deployment files with name app01, app02,app03,app04 

output:  creating only deployment file with app04.

--- 
helm template value 

Source: app/templates/depl.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app01
  template:
    metadata:
      labels:
        app: app01
    spec:
      containers:
        - name: app01
          image: nginx
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app02
  template:
    metadata:
      labels:
        app: app02
    spec:
      containers:
        - name: app02
          image: nginx
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app03
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app03
  template:
    metadata:
      labels:
        app: app03
    spec:
      containers:
        - name: app03
          image: nginx
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app04
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app04
  template:
    metadata:
      labels:
        app: app04
    spec:
      containers:
        - name: app04
          image: nginx
---------

**helm output with debug**
helm upgrade --install app app/ -n app --debug
history.go:56: [debug] getting history for release app
upgrade.go:142: [debug] preparing upgrade for app
upgrade.go:150: [debug] performing update for app
upgrade.go:322: [debug] creating upgraded release for app
client.go:229: [debug] checking 1 resources for changes
client.go:512: [debug] Looks like there are no changes for Deployment "app04"
upgrade.go:157: [debug] updating status for upgraded release for app
Release "app" has been upgraded. Happy Helming!
NAME: app
LAST DEPLOYED: Tue Aug  6 08:57:47 2024
NAMESPACE: app
STATUS: deployed
REVISION: 4
TEST SUITE: None
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
replicaCount: 4

HOOKS:
MANIFEST:
--- Source: app/templates/depl.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app01
  template:
    metadata:
      labels:
        app: app01
    spec:
      containers:
        - name: app01
          image: nginx
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app02
  template:
    metadata:
      labels:
        app: app02
    spec:
      containers:
        - name: app02
          image: nginx
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app03
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app03
  template:
    metadata:
      labels:
        app: app03
    spec:
      containers:
        - name: app03
          image: nginx
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app04
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app04
  template:
    metadata:
      labels:
        app: app04
    spec:
      containers:
        - name: app04
          image: nginx

-----
Output of `helm version`:
version.BuildInfo{Version:"v3.14.3", GitCommit:"f03cc04caaa8f6d7c3e67cf918929150cf6f3f12", GitTreeState:"clean", GoVersion:"go1.21.7"}

Output of `kubectl version`: v1.30.3

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  onprem

**Comment by stavros-k** [comment]
Add `---` under the range statement.
