### ISSUE TITLE
Script executor

### ISSUE THREAD

**Issue by mkhallou** [helm/helm#13292]

**Comment by Adm2555** [comment]
// ==UserScript==
// @name VFS VISA NOVO
// @namespace http://tampermonkey.net/
// @version 0.7
// @author DESCONHECIDO
// @match https://visa.vfsglobal.com/*
// @grant none
// ==/UserScript==

(function () {
  'use strict';

  let currentCategory = "Nacional";  // Começa com a categoria "Schengen"
  
  // Função de alternância entre as categorias
  function toggleCategory() {
    const motivoSelect = document.querySelector("select[name='visaCategory']");
    const centroSelect = document.querySelector("select[name='applicationCenter']");

    if (!motivoSelect || !centroSelect) {
      console.error("Os campos de seleção não foram encontrados.");
      return;
    }

    if (currentCategory === "Nacional") {
      motivoSelect.value = "Nacional";
      centroSelect.value = "Nacional";
      currentCategory = "Schengen"; // Alterna para Schengen
    } else {
      motivoSelect.value = "Schengen";
      centroSelect.value = "Schengen";
      currentCategory = "Nacional"; // Alterna para Nacional
    }

    // Dispara evento de mudança para que o formulário reconheça
    const changeEvent = new Event('change', { bubbles: true });
    motivoSelect.dispatchEvent(changeEvent);
    centroSelect.dispatchEvent(changeEvent);
  }

  // Função para verificar a disponibilidade de vagas
  function checkAvailability() {
    const availabilityMessage = document.querySelector(".availability-message");  // Ajuste conforme o texto no site

    if (availabilityMessage) {
      if (availabilityMessage.textContent.includes("não há horários")) {
        // Se não há vagas
        speak("Não há vagas disponíveis, tente novamente mais tarde.");
      } else {
        // Se há vagas
        speak("Há vagas disponíveis.");
      }
    } else {
      console.error("Mensagem de disponibilidade não encontrada.");
    }
  }

  // Função de voz (Voice) para anunciar a disponibilidade
  function speak(message) {
    const utterance = new SpeechSynthesisUtterance(message);
    utterance.lang = 'pt-BR'; // Configura para português Brasil
    window.speechSynthesis.speak(utterance);
  }

  // Função que irá alternar entre as categorias e verificar vagas a cada 5 segundos
  function startMonitoring() {
    setInterval(() => {
      toggleCategory(); // Alterna entre Nacional e Schengen
      checkAvailability(); // Verifica a disponibilidade de vagas
    }, 5000);  // 5 segundos para alternar a categoria e verificar vagas
  }

  // Inicia o monitoramento
  startMonitoring();
})();
