### ISSUE TITLE
get.helm.sh down

### ISSUE THREAD

**Issue by emilianobonassi** [helm/helm#13303]
https://dnschecker.org/#A/get.helm.sh

unable to download anymore helm

a lot of ci/cd might experience issues

**Comment by ajmoorexyz** [comment]
I can confirm 😢 

```zsh
% wget https://get.helm.sh/helm-v3.15.4-linux-amd64.tar.gz
--2024-09-05 21:32:12--  https://get.helm.sh/helm-v3.15.4-linux-amd64.tar.gz
Resolving get.helm.sh (get.helm.sh)... failed: No address associated with hostname.
wget: unable to resolve host address ‘get.helm.sh’
```

**Comment by ConejoCapital** [comment]
it's over for helmers

**Comment by mattfarina** [comment]
The DNS entry was updated to lower the TTL in preparation for a CDN change. Somehow this caused the DNS to be dropped. I'm seeing it come back intermittently. We will continue to follow this. Sorry for the inconvenience.

**Comment by POnakS** [comment]
@mattfarina thanks for such quick action!

**Comment by valytica-mattb** [comment]
Thanks for the response. Currently breaking our CI processes

**Comment by drivera-armedia** [comment]
Yeah I have one CICD path blocked on this... is there an ETA on the fix?

**Comment by emilianobonassi** [comment]
looks resolved to me

**Comment by mattfarina** [comment]
This does appear to be resolved. Will close the issue after another day just to be on the safe side so a duplicate isn't opened.

**Comment by koslib** [comment]
are we back at it?

**Comment by jeff1326** [comment]
Seems that get.helm.sh is down again for me


See https://github.com/helm/helm/issues/31434

**Comment by riuvshyn** [comment]
get.helm.sh is down.

**Comment by unique-serghei** [comment]
get.helm.sh is down since  arround 30 mins

**Comment by akash-numosai** [comment]
Unable to download helm from this endpoint
Run azure/setup-helm@v4
Warning: Error while fetching latest Helm release: TypeError: fetch failed. Using default version v3.18.4
Installing v3.18.4
  Downloading 'v3.18.4' from 'https://get.helm.sh/'
  
  Waiting 14 seconds before trying again
  
  Waiting 20 seconds before trying again
  Error: Error: Failed to download Helm from location https://get.helm.sh/helm-v3.18.4-linux-amd64.tar.gz

**Comment by steffkelsey** [comment]
It is not DNS this time. We resolve to an address and then hang

```
root@instance:~# wget https://get.helm.sh/helm-v3.18.4-linux-amd64.tar.gz
--2025-10-29 17:11:57--  https://get.helm.sh/helm-v3.18.4-linux-amd64.tar.gz
Resolving get.helm.sh (get.helm.sh)... 13.107.213.40, 13.107.246.40
Connecting to get.helm.sh (get.helm.sh)|13.107.213.40|:443...
```

**Comment by riuvshyn** [comment]
it is always DNS....

**Comment by 123varma007** [comment]
We are facing the same - request timeout while downloading helm-v4.0.0-beta.2-linux-amd64.zip from [https://get.helm.sh](https://get.helm.sh)

**Comment by SauravNirmit** [comment]
When It will be back?

**Comment by shay2911** [comment]
Probably when Azure will be back XD
https://azure.status.microsoft/en-us/status

<img width="1220" height="530" alt="Image" src="https://github.com/user-attachments/assets/0215df27-ff57-4c86-8828-b9f1fb6e66d2" />

**Comment by RulanAkzhigitov** [comment]
:(

**Comment by D4nutz** [comment]
helm works for me now
