### ISSUE TITLE
Error: INSTALLATION FAILED: repo bitnami not found

### ISSUE THREAD

**Issue by tko81** [helm/helm#13336]
when I install mysql with my own yaml, I encountered a strange problem. The result of repo list shows that bitnami repo is already in my ubuntu 24.04, but I cannot install mysql

    helm repo list
    NAME   	URL
    bitnami	https://charts.bitnami.com/bitnami
    
    sudo helm install my-db -f values.yaml bitnami/mysql
    Error: INSTALLATION FAILED: repo bitnami not found

I can also find the bitnami/mysql
    
    helm search repo bitnami/mysql
    NAME         	CHART VERSION	APP VERSION	DESCRIPTION
    bitnami/mysql	11.1.16      	8.4.2      	MySQL is a fast, reliable, scalable, and easy t...

Output of `helm version`: 
version.BuildInfo{Version:"v3.16.1", GitCommit:"5a5449dc42be07001fd5771d56429132984ab3ab", GitTreeState:"clean", GoVersion:"go1.22.7"}

Output of `kubectl version`: 
Client Version: v1.30.4+k3s1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.4+k3s1

Cloud Provider/Platform (AKS, GKE, Minikube etc.): k3s

thanks for your reply~

**Comment by yardenshoham** [comment]
It's because you used sudo

**Comment by tko81** [comment]
> It's because you used sudo
Thank you for your comment. The first time I executed the command without sudo, I received a 'permission denied' error. After your comment, I modified the permissions of the 'k3s.yaml' file, and it works!
