### ISSUE TITLE
helm malforms image tag with `--reuse-values`

### ISSUE THREAD

**Issue by maazghani** [helm/helm#13378]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.16.1", GitCommit:"5a5449dc42be07001fd5771d56429132984ab3ab", GitTreeState:"clean", GoVersion:"go1.22.7"}
```

Output of `kubectl version`:
```
Client Version: v1.29.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): "N/A" 

We ran into an issue where running `helm upgrade --install --reuse-values $release` results in a malformed image tag, but only when the image tag happens to be all numbers. 

For example, when the existing helm release's deployment manifest included an image tag that was alphanumeric, it had no issue reusing the values. But we were able to reproduce that when we run the  `helm upgrade --install --reuse-values $release` with a number, for example `29111998`, helm tries to update the image tag to `2.9111998e+07`.

**Comment by mattfarina** [comment]
For these numbers, are they wrapped in quotes? If not, try wrapping them in quotes.

It looks like you are getting into a characteristic of YAML and the YAML parser used and maintained by the Kubernetes project. When you have a number not wrapped in quotes it can be parsed and worked on as a number. In YAML it's valid to write it in the form `2.9111998e+07`. The Kuberentes YAML library does this.

The way to handle this is to wrap the name in quotes.

**Comment by maazghani** [comment]
Thanks @mattfarina! That was the issue.
