### ISSUE TITLE
Processing null values not working when specifying values.yaml

### ISSUE THREAD

**Issue by alongwill** [helm/helm#13388]
Output of `helm version`: 
```
version.BuildInfo{Version:"v3.16.2", GitCommit:"13654a52f7c70a143b1dd51416d633e1071faffb", GitTreeState:"clean", GoVersion:"go1.22.7"}
```

I'm trying to implement the extraArgs in my template in a similar way to [cluster-autoscaler](https://github.com/kubernetes/autoscaler/blob/master/charts/cluster-autoscaler/templates/deployment.yaml#L132)

**Template**
```yaml
data:
  test-args: |
    {{- range $key, $value := .Values.extraArgs }}
      {{- if not (kindIs "invalid" $value) }}
      - --{{ $key }}={{ $value }}
      {{- else }}
      - --{{ $key }}
      {{- end }}
    {{- end }}
```

**Values**
```yaml
extraArgs:
  debug: true     # should output --debug=true
  verbose: null   # should output --verbose
```

✅ This works:

```sh
helm template .
---
# Source: testchart/templates/test-template.yaml
data:
  test-args: |
      - --debug=true
      - --verbose
```

❌ This doesn't

```sh
helm template . --values=values.yaml
---
# Source: testchart/templates/test-template.yaml
data:
  test-args: |
      - --debug=true
```

Can anyone advise why the template is not displaying `--verbose` when specifying `values.yaml`?

**Comment by alongwill** [comment]
I've simplified this to just iterate over a list of args, so not an issue for me anymore.

**Comment by scottrigby** [comment]
For anyone who happens upon this, the reason passing --values=values.yaml deletes the key is that null as a specified value is means to allow users to delete an existing key in a chart's values. The first example above is a chart simply setting a key to a value "null". The second example above passes that same value back as a user-specified override, which by Helm's convention deletes the key. I explained it in more detail here: https://github.com/helm/helm/issues/13459#issuecomment-2614824357
