### ISSUE TITLE
credential required for basic auth Error while Using --username --password flags to helm install for private distribution repo

### ISSUE THREAD

**Issue by rahulbapumore** [helm/helm#13404]
We are trying to install helm chart stored at private distribution registry, but we are getting error while installing even though we pass --username , --password flag to helm install command.
we want authentication to happen with helm install command only, we dont want to login to repo beforehand
Below is the command, let me know if I am missing anything in below command -

helm install rel oci://abc.io/chart1 --username=admin --password=admin   --ca-file ca.crt --cert-file client.cert  --key-file client.key WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /src/admin.conf WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /src/admin.conf Error: INSTALLATION FAILED: GET "https://abc.io/v2/chart1/tags/list": credential required for basic auth

Output of `helm version`:
helm version
version.BuildInfo{Version:"v3.13.3", GitCommit:"c8b948945e52abba22ff885446a1486cb5fd3474", GitTreeState:"clean", GoVersion:"go1.20.11"}

Output of `kubectl version`:
kubectl version
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.2
WARNING: version difference between client (1.28) and server (1.30) exceeds the supported minor version skew of +/-1

**Comment by rahulbapumore** [comment]
@banjoh

**Comment by banjoh** [comment]
@rahulbapumore this will be fixed by https://github.com/helm/helm/pull/12769

**Comment by banjoh** [comment]
Fixed by https://github.com/helm/helm/pull/12769. It'll be available in helm v4 though. If needed it can be backported.
