### ISSUE TITLE
.Capabilities.HelmVersion.Version does not include the patch version

### ISSUE THREAD

**Issue by jdiegosierra** [helm/helm#13482]
Let's suppose I'm using Helm version 3.16.1. When I execute the following:
{{- $version := semver .Capabilities.HelmVersion.Version -}}
I get 3.16.0.

Why does .Capabilities.HelmVersion not include the patch version? Is there any specific reason or advantage to omitting that information?

**Comment by mattfarina** [comment]
How was the Helm binary built? I'm not able to replicate your issue. I see the patch version accurately.

**Comment by jdiegosierra** [comment]
To be honest, I'm not able to reproduce it. Probably I was doing something wrong. Sorry.
