### ISSUE TITLE
e2e testing for helm/tiller

### ISSUE THREAD

**Issue by michelleN** [helm/helm#1354]
Can we re-open the discussion of an e2e test suite of helm ?

cc/ @adamreese @technosophos

**Comment by prydonius** [comment]
cc @viglesiasce since I'm sure he has good ideas about this

**Comment by thomastaylor312** [comment]
Just bringing this back to the top. It may be a good idea to focus on this for 2.4. If we agree, we can move this to that milestone

**Comment by nebril** [comment]
We got some basic e2e test framework that uses helm for review for rudder-appcontroller. I can spend some time on trying to move it to helm repository after it's merged to rudder-appcontroller.

link to PR: https://github.com/nebril/rudder-appcontroller/pull/1

**Comment by nebril** [comment]
@dshulyak

**Comment by bacongobbler** [comment]
#2846 should resolve this issue.

**Comment by bacongobbler** [comment]
https://github.com/helm/acceptance-testing
