### ISSUE TITLE
Add AppVeyor CI support for Windows

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#1606]
[AppVeyor](https://www.appveyor.com/) provides a windows CI service (like Circle or Travis). And, it's free for open source.

Since helm has windows builds, I think, it's worth doing windows CI and this seems like a good option.

**Comment by technosophos** [comment]
That could be really useful. Wanna set that up? ;-)

**Comment by mattfarina** [comment]
@technosophos there are two parts. First, the config file and second the service itself (which requires things like bing on the org and a commit hook). The first part I'm happy to do. How do we approach the second part?

**Comment by technosophos** [comment]
I don't know. I'll have to see if we need CNCF to do something, or if we can just do it.

**Comment by bacongobbler** [comment]
related: #1968
