### ISSUE TITLE
Platform-specific commands for plugins

### ISSUE THREAD

**Issue by technosophos** [helm/helm#1638]
In the current plugin model, there is one way to declare a command to execute:

```yaml
command: executable.thing
```

However, this assumes that all of the platforms that we support can have the same entry point. This may not be the case. For example, a shell script cannot be run on both Windows and Linux with the same entry point.

In the executing Helm binary, we have a few bits of runtime info at our disposal that can tell us the OS we're running in and the system architecture. We could use these to provide support for some optional ways to specify a command. I'd suggest something like this:

Let's support something like `commands: $OS-$ARCH`

```yaml
command: generic-version
platformCommands:
  windows: foo.bat
  linux-386: foo.sh
```

- OS and ARCH are any of the supported GOOS/GOARCH flags
- Architecture is optional. If omitted, all archs are considered supported

So in the example above

- if I run on Windows, `foo.bat` will get executed
- if I run on linux, and GOARCH is 386, `foo.sh` is run, otherwise, `generic-version` is run
- on MacOS, `generic-version` is run, because there are no specific platform alternatives

The advantage that that gives us is being able to produce plugins that run on multiple architectures, but can optimize for native. This will benefit Windows integration, and also benefit those wishing to do binary-only plugins.

This issue came up in #1628

**Comment by jascott1** [comment]
@technosophos do we want to throw the keep open label on this?

**Comment by bacongobbler** [comment]
Yes I would argue this should be kept open. This is also a design issue in Draft as well, so it'd be good to learn from this experience.

CC @michelleN

**Comment by bacongobbler** [comment]
This is an action item for Draft at https://github.com/Azure/draft/issues/396. Let's see if we can find a way to get plugins to work for Draft, then propose a new system for Helm 3.

**Comment by bacongobbler** [comment]
https://github.com/helm/helm/pull/5176
