### ISSUE TITLE
Migrate storage to Kubernetes Third Party Resources

### ISSUE THREAD

**Issue by spiddy** [helm/helm#1650]
Current storage driver populates ConfigMaps in `kube-system` namespace for storing the releases. Now with [Third Party Resources](http://kubernetes.io/docs/user-guide/thirdpartyresources/) we can have a cleaner solution. Create our own `Releases` resource where we can populate all the information.

Moreover, current solution is packaging a lot of info inside a `release` field that cannot be reused for filtering (e.g. use kubernetes API to filter releases by chart name) which reduces extensibility by other tools. With TPR we can have all the information inside the YAML.

Not sure about this but probably we may even be able to elevate kubernetes rollout feature to rollback releases.

We can rollout this as an alternative/optional storage driver since it is backwards incompatible (otherwise we need a migration process from one storage to another)

**Comment by technosophos** [comment]
This has been a long-standing desire among the Helm team. I'd love to do this. It is currently the only item on the 3.0.0 roadmap (https://github.com/kubernetes/helm/wiki/Roadmap#3x-roadmap), but if we could make it entirely backward compatible, we might be able to do it before 3.0.

**Comment by technosophos** [comment]
Just to provide a brief update based on recent discussions: The Helm team has decided that we will no longer use alpha and beta Kubernetes features because of the high probability of serious breakages.

Doesn't really impact this issue, since it's on the 3.x roadmap. But I wanted to capture it here anyway.

**Comment by TamalSaha** [comment]
+100 from me.

**Comment by sputnick** [comment]
@technosophos in what capacity? PVCs are alpha/beta.

**Comment by TamalSaha** [comment]
@sputnick using TPRs allow applying authorization to specifically for release data. Once #1918 is merge, to properly enforce RBAC, you need to run tiller in a namespace and ensure that unauthorized modifications of configmaps in that namespace is not possible.

With TPR, you need to restrict unauthorized modification of Tiller specific TPRs. With TPRs it will be possible to apply RBAC to Tiller api directly in addition to underlying kube objects.

**Comment by bacongobbler** [comment]
Given the current state of TPRs (renaming, constant API changes/rewrites), I wouldn't start development on this effort until the CRD (new name for TPR) API has stabilized.

**Comment by andrewhowdencom** [comment]
Now that CRD has been stabilised, it might be worth revising this. Additionally, if it can be sufficiently abstracted, it might serve to develop a standard entity for "applications", and help with the kubernetes dashboard integration.

**Comment by pierreozoux** [comment]
What is the status of this?

**Comment by andrewhowdencom** [comment]
@pierreozoux maybe checkout the spec for Helm 3.0. Part of that covers this, I believe.

**Comment by bacongobbler** [comment]
yes. https://github.com/kubernetes-helm/community/blob/master/helm-v3/003-state.md

**Comment by pierreozoux** [comment]
Should we close this issue then?

**Comment by bacongobbler** [comment]
Yes.

For reference, we're storing release information in a secret, not a CRD. This is because of the potential for sensitive information being part of the config, which can be protected by [encrypting secret data at rest](https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/).
