### ISSUE TITLE
Need tiller binary distributed with each release

### ISSUE THREAD

**Issue by spothala** [helm/helm#1690]
We want this feature to run tiller locally along with helm in same container/vm. We cannot use docker image of tiller due to our policies.

**Comment by technosophos** [comment]
Will simply running `make bootstrap build` from source not work for your needs?

**Comment by spothala** [comment]
Thats how am building tiller binary right now. Its time taking sometimes as `make bootstrap build` clones entire kubernetes repo if we've to do clean build. And we've to track/build tiller version separately whenever there is a new version of helm (Not a big deal though).

So it would be great if we get binary distributed in each release.

**Comment by technosophos** [comment]
Okay, there is a PR to add this as a separate build. We could just add a downloadable package. See #1722

**Comment by spothala** [comment]
Thank you very much... @technosophos

**Comment by technosophos** [comment]
Added to meta issue #1968

**Comment by jascott1** [comment]
@spothala Closing this since it appears fixed in PR #1798 and due to inactivity. Please feel free to re-open if necessary.

**Comment by bacongobbler** [comment]
re-opening; #1798 is neither a PR nor does it actually fix the problem. In fact it redirects back to this issue 😄

**Comment by bacongobbler** [comment]
fixed in #4443 which'll be in the next release (2.11) since we're already cutting release candidates for 2.10.
