### ISSUE TITLE
`helm upgrade --recreate-pods` flag should do a soft restart

### ISSUE THREAD

**Issue by technosophos** [helm/helm#1702]
@chancez  correctly noted here that the `--recreate-pods` flag does _not_ do a soft restart. We should fix that. https://github.com/kubernetes/helm/pull/1648#issuecomment-267684171

**Comment by HamletDRC** [comment]
Is there any plan or ETA on this?

**Comment by bacongobbler** [comment]
AFAIK nobody is currently working on this, so if you feel like taking a crack at it go ahead!

**Comment by paulgmiller** [comment]
A naive proposal would be to shove revision into the spec of deployment/daemonset/statefulset so that they gracefully do rolling upgrade if so configured. I'd go further but I still owe bacongobbler an improved wait.go before I pretend to commit to anything else. @HamletDRC I'm also microsoft  (work on azureml's k8 cluster) if you want to talk.

**Comment by hustshawn** [comment]
@technosophos can the `--recreate-pods` add extra options which can perform pods rolling update, instead of the current behavior that destroy all pods and create new.

**Comment by Amos-85** [comment]
I think it will be great if --recreate-pods flag will include which deployment/pods to recreate instead the whole application,
sometime you don't really need / want to recreate the whole chart and just need to redeploy part of it, especially in umbrella charts.

**Comment by thomastaylor312** [comment]
Would using an annotation on the object (like described in the [docs](https://helm.sh/docs/charts_tips_and_tricks/#automatically-roll-deployments-when-configmaps-or-secrets-change)) be a better and more declarative way to do this? I think trying to make it soft restart to meet everyone's specific use case will just lead to pain for everyone

**Comment by towolf** [comment]
FYI, kubectl is doing this also by adding an annotation to the owning object's pod spec, and that works perfectly, I'm using it all the time now.

check out `kubectl rollout restart {deployment,statefulset,daemonset} xyz`

**Comment by KetsuN** [comment]
Any official note or progress on this?  Feels like a tool revolving around deploying resources should have an option to do a seamless rollout.

**Comment by thomastaylor312** [comment]
@rorysavage77 That definition is correct. "Restarting" a pod is not an actual thing and is done by terminating a pod and letting a controller do the work of recreating.

@KetsuN Like I stated before, I am not entirely convinced yet that we need to add additional logic to Helm itself that is just duplicating all of the update strategy logic that Kubernetes already does for you. As I linked in the docs and in the example that @towolf gave, the way to do this declaratively is to add an annotation that changes to the pod template spec and then it will update the pods according to the defined update strategy.

As I am typing this, it gets me wondering if we should deprecate that flag 🤔

**Comment by rimusz** [comment]
I’m in favour to deprecate the flag.
adding the annotation and using kubectl rollout restart are good enough for the job, no needs to make helm more complex

**Comment by thomastaylor312** [comment]
After discussion today in the dev call, we are comfortable with deprecating the flag. It will remain in Helm 3, but additional work will not be done with it. Before marking as deprecated, I will be writing documentation detailing how to use annotations to roll pods

**Comment by thomastaylor312** [comment]
Closed by https://github.com/helm/helm-www/pull/286 and #6463
