### ISSUE TITLE
Uninstall should prompt for confirmation (and have a force flag)

### ISSUE THREAD

**Issue by technosophos** [helm/helm#177]
Because `helm uninstall` performs an operation on the k8s cluster, we should really prompt for confirmation before deleting. I'm envisioning something like this:

```
helm uninstall alpine
---> Components to be uninstalled:
  pod/alpine
  service/alpine-gateway
Are you sure you want to delete these 2 items (Y,n): y
---> Running `kubectl delete` ...
```

To sidestep, the user can provide a `--force` flag

**Comment by bacongobbler** [comment]
+1

**Comment by michelleN** [comment]
@technosophos Could we go a little further to ask "This will run a `kubectl delete` operation. Are you sure you want to delete these 2 items (Y,n):"

**Comment by sgoings** [comment]
@michelleN we could do that, or follow the `rm -i` method which is a prompt for every file (in our case: chart) removal.

**Comment by michelleN** [comment]
:+1:

**Comment by technosophos** [comment]
The difference between `rm -i` and something like this is that the units you remove with `rm` are not necessarily interdependent.

For charts, when you deploy a chart, you assume coupling between all of these things. So can we accurately do a thing-by-thing deletion and assure the user that we won't leave them in a broken state?

I feel like if the answer is no, we should not allow it. They can always selectively delete using kubectl itself.

**Comment by arschles** [comment]
my $0.2 is that if we understand the dependency graph and we do chart by chart deletion, then we should delete in dependency order. that seems like a lot of logic (right now) just to do something that users could do themselves with `kubectl`.

maybe instead it's a part of a larger issue to add more dependency related commands to helm?

**Comment by arschles** [comment]
unrelated request - it would be nice to add a `-y` flag to `helm uninstall` so that you can run it in CI systems

**Comment by technosophos** [comment]
The issue here is that a specific chart may be deployed into Kubernetes, and have several associated manifests (a service, a few RCs, a volume, some secrets...). If we delete, say, a service but not the RCs, we could leave things in an uncertain state. Or if we keep an RC and delete the volume and secret it uses, we would at best get cluster errors, and at worst get really weird side-effects.

**Comment by arschles** [comment]
I see, I was thinking in terms of service => service, or even chart => chart dependencies
