### ISSUE TITLE
Allow renaming deployed release?

### ISSUE THREAD

**Issue by whitecolor** [helm/helm#1809]
What do you think about allowing to rename to existing deployed release while upgrade?

**Comment by technosophos** [comment]
You would want it to do something like this?

- Change release name
- Regenerate all templates
- Destroy old resources
- Create new resources

Or are you thinking it would work differently?

**Comment by whitecolor** [comment]
Yes, though release name may have not so drastic impact on templates and eventually existing resources.

**Comment by technosophos** [comment]
Added to feature triage queue

**Comment by whitecolor** [comment]
Was not implemented I believe?

**Comment by bacongobbler** [comment]
It might be possible this could be implemented as a plugin by interacting with tiller directly. Still, I'll file this as a feature request for the time being.

**Comment by AssafKatz3** [comment]
Any update about it?

**Comment by chainlink** [comment]
Also following

**Comment by bacongobbler** [comment]
No update to report. :)

**Comment by chainlink** [comment]
Is there a work around?

**Comment by bacongobbler** [comment]
No

**Comment by AssafKatz3** [comment]
This is still a big problem for us.

/remove-lifecycle stale

**Comment by bacongobbler** [comment]
This isn't something we plan to implement any time soon. If someone from the community wants an idea for a plugin, this is a great opportunity to do so!

**Comment by chainlink** [comment]
Is it just a matter of renaming on the config map?

**Comment by chainlink** [comment]
Ah yeah, ok. Hrm. I'm also looking for a lower touch solution (ie. rename in place w/o create/destroy), but not sure if you could change the annotations or other properties without a create/destroy cycle.

**Comment by schollii** [comment]
Some k8s resources like Service get the release name prepended so that multiple releases can coexist (otherwise nameclash would occur and prevent installation).

**Comment by bacongobbler** [comment]
Closing this as a wontfix as the effort and risk involved to rename the rendered resources without causing downtime for the application is incredibly high. Given the time investment and risks involved, it's probably not worth the time to consider implementing a vanity name change.

We'd still love to see someone pick this up as a plugin! If that plugin seems like a workable solution then we can consider absorbing that into the core Helm codebase. Thanks!

**Comment by Hokwang** [comment]
Oh, I need change release name only..

**Comment by bacongobbler** [comment]
Changing the release name also affects how the templates can be rendered as many charts rely on `{{ .Release.Name }}`, hence the high risk.

**Comment by thangbn** [comment]
> Changing the release name also affects how the templates can be rendered as many charts rely on `{{ .Release.Name }}`, hence the high risk.

Very bad call to use the release name within templates, are we looking to change this in helm 3 as we can afford to put in breaking changes

**Comment by AssafKatz3** [comment]
@thangbn We are using release name for labeling the objects in order to associate them with release (they are creating through operator so we cannot use other options)

**Comment by omesser** [comment]
@thangbn - It is common to use release name within templates exactly with the purpose of associating them with the release name (like @AssafKatz3 said) and I do not believe this is in any way a bad call or practice (unless there's a better way of doing the same thing which I am not familiar with).
