### ISSUE TITLE
Build and release cross-platform tiller images

### ISSUE THREAD

**Issue by ravishivt** [helm/helm#1862]
Now that we have cross-platform binaries being built, it would be great if helm also built and released cross-platform tiller images.  See https://github.com/kubernetes/kubernetes/blob/d9aed2c5ab47c581ed1f9c5dccd07402fe055f05/cluster/images/hyperkube/Makefile for an example Makefile that uses QEMU to do cross-platform docker builds.

**Comment by technosophos** [comment]
This would definitely be good to have.

**Comment by ravishivt** [comment]
I just looked at tiller's Dockerfile.  We can ignore the QEMU approach since there are no docker `RUN` commands in the Dockerfile.  We just have to side-load the cross-compiled binaries onto a architecture-specific docker base image.  [hypercube's Makefile](https://github.com/kubernetes/kubernetes/blob/d9aed2c5ab47c581ed1f9c5dccd07402fe055f05/cluster/images/hyperkube/Makefile#L33) might a good reference for that.

**Comment by technosophos** [comment]
We need to come up with an overall strategy for rebuilding the CircleCI deployment. At this point we have too many competing requests for these features.

I just created #1968 to track the big picture. Would you mind weighing in on that issue?

**Comment by kfox1111** [comment]
Is there any status update on this?

**Comment by bacongobbler** [comment]
we're not going ahead with this given that Tiller has been removed in Helm 3. Closing!
