### ISSUE TITLE
Feature request: Allow inheriting files from parent templates

### ISSUE THREAD

**Issue by andrewhowdencom** [helm/helm#1892]
At the moment, children templates can inherit values in the parent `Values.yml` file if that file includes the value, prefixed by the chart name. For example, 

```
mysql:
    mysqlRootPassword: herapderpa # This overrides the mysqlRootPassword on the top level of its Values.yml
```

There is no such inheritance allowed for files. It appears that values are being explicitly passed down the stack in the following snippet: 

https://github.com/kubernetes/helm/blob/c8af660b181daf4000aca87e19e583fd1abec0b3/pkg/engine/engine.go#L217-L222

It would be good for files to be passed down the stack also, though there is no convention for doing as such. One suggestion might be to create a folder with the name of the child chart, and inherit the files supplied in that folder. For example, 

```
mysql/
    mysql.conf
```

In the case above, the mysql.conf file would override the mysql.conf file in the root of the mysql chart, stored in charts/ (note: don't go looking, I made that up)

Thaanks!

**Comment by technosophos** [comment]
I think we could do this, provided we have a good convention. Maybe along side `charts/` we have something like an `overrides/` directory that could contain information like this. It might get tricky. For example, how do I override `mychart/charts/wordpress/charts/mysql/my.cnf` but not `mychart/charts/drupal/charts/mysql/my.cnf`?

**Comment by andrewhowdencom** [comment]
If I was to choose an API, I would try and model it after the inheritance behaviour of .Values.yml. So, instead of 

```
overrides/my.conf
```

You would have

```
overrides/drupal/mysql/${my.conf
overrides/wordpress/mysql/my.conf
```

So, the format would be something like 

```
overrides/${CHART_A}/${CHART...N}/${PATH_TO_FILE}
```

If I understand correctly, .Values.yml inherits along a simliar syntax

```
---
# child
foo: bar
```

```
# parent
child:
  foo: baz
```

**Comment by jascott1** [comment]
@andrewhowdencom Closing this issue due lack of activity for 6 months. Please feel free to re-open  or create a new proposal.

**Comment by andrewhowdencom** [comment]
Hola @jascott1; I think this is still valid -- A pattern of embedding files in the yaml has started to emerge, which is not so elegant: 

https://github.com/kubernetes/charts/blob/master/stable/prometheus/values.yaml#L545

I just don't have the skills to implement it (:

Cannot reopen.

**Comment by jascott1** [comment]
Re-opening based on OP request.

**Comment by johnny** [comment]
I would like to see this as well. The only way to add files to a subchart seems to be embedding them into the `values.yaml` file, which becomes very unwieldy for big files, e.g. grafana dashboards: https://github.com/kubernetes/charts/issues/1079

The parent chart would define the dashboards in `overrides/grafana/dashboards` and the grafana child chart could pull them into a configmap like this:

```
data:
{{- (.Files.Glob "dashboards/*.json").AsConfig | indent 2 -}}
```
/remove-lifecycle stale

**Comment by vladfr** [comment]
I would like to see this as well. A pattern would be to override `config` files, but not override the Kube templates. I'm now adding support for splunk in the fluent-bit chart, and I need to copy the whole chart to do it.
`/reopen`
`/remove-lifecycle rotten`

**Comment by andrewhowdencom** [comment]
/reopen /remove-lifecycle-rotten

Mostly I've been editing files as part of `Values.yml` but it's kind of nasty

**Comment by andrewhowdencom** [comment]
cc @technosophos  directly, as I think the bot is misbehaving

**Comment by bacongobbler** [comment]
we're no longer part of the kubernetes org, so slash comments and the stale issue bot have been disabled for the time being.

**Comment by bacongobbler** [comment]
FYI, this is being addressed as part of the Helm 3 proposals through the extension model: https://github.com/helm/community/blob/master/helm-v3/001-charts.md#the-ext-directory

**Comment by HamzaK8s** [comment]
@bacongobbler I really need it on Helm v2 do you any work-around to let my child chart inherit files from the parent templates ?

**Comment by anapsix** [comment]
@HamzaK8s how about using `tpl` functions? See example in [stable/keycloak](https://github.com/helm/charts/blob/master/stable/keycloak/values.yaml#L138-L140)

**Comment by amitripshtos** [comment]
I'm having this issue also, and can't find a good solution to it rather doing something hacky such providing a ConfigMap from the parent chart and let the subchart use that.

Anyone has a solution ?

**Comment by sesquipedalian-dev** [comment]
> FYI, this may be addressed as part of the Helm 3 proposals through the extension model: https://github.com/helm/community/blob/master/helm-v3/001-charts.md#the-ext-directory
> 
> If you have feedback on that particular model we'd love to hear it!

Now that Helm 3 is released, I'm trying to do this with a library chart and it doesn't seem to be working.  I still get the error: 
```
at <.Files.Glob>: nil pointer evaluating interface {}.Glob
```
Was the 'hoisting' thing mentioned here (https://github.com/helm/community/blob/master/helm-v3/001-charts.md#the-ext-directory) implemented?

**Comment by bacongobbler** [comment]
Library charts were implemented, yes. @hickeyma gave a talk about this feature at Helm Summit EU. You can find the recording on YouTube if you want to learn more about it.

**Comment by edobry** [comment]
Is there a document somewhere showing how to do this with Helm 3? It still seems to not be possible.

**Comment by dpiessens** [comment]
FYI this issue is documented in HELM with no resolution. If grafana is a sub-chart it can't get files from the parent chart. There are some ugly work-arounds but I personally think the easiest one is to make them config maps and then link in the values file.
https://github.com/helm/helm/issues/1892

**Comment by lindhe** [comment]
I think this is still of interest.

**Comment by rromannissen** [comment]
> I would like to see this as well. The only way to add files to a subchart seems to be embedding them into the `values.yaml` file, which becomes very unwieldy for big files, e.g. grafana dashboards: [helm/charts#1079](https://github.com/helm/charts/issues/1079)
> 
> The parent chart would define the dashboards in `overrides/grafana/dashboards` and the grafana child chart could pull them into a configmap like this:
> 
> ```
> data:
> {{- (.Files.Glob "dashboards/*.json").AsConfig | indent 2 -}}
> ```
> 
> /remove-lifecycle stale

Something like this would be very helpful to define a configuration model for applications based on Helm charts that wouldn't require actual knowledge about Helm for developers. Application configuration would be modelled as a simple chart with values and the actual configuration files, with a dependency to a chart packaging the templates that define all required Kubernetes objects for deployment, including ConfigMaps and Secrets. Not having this inheritance for files implemented requires packaging the ConfigMap and Secret templates on each application configuration chart for this to work, which leads to code repetition and is a bit messy. 

And I agree that embedding all configuration files in the values.yaml is not a suitable solution for this, as developers would be forced to mess with a different format instead of working with the type and format for files they are used to.

I'm really interested in this feature being implemented.

**Comment by dgsardina** [comment]
I am pretty sure this still applies. I am unable to find a solution for this and I believe this is a common pattern. 
In my case I want to have a template in a subchart that renders configmaps with content of a directory on the parent chart. Any suggestions without embedding the files on the values of the parent or adding code to the parent are more than welcome.

**Comment by brian-groux-hs** [comment]
I found a way around this limitation for anyone interested. We were trying to render files from a parent and child into the same config map. 

In the parent (we will call  it `parent` in the example) in a non-underscored file, so for example "templates/blah.yaml"
```
{{- $_ := set .Values "renderedfiles" (($.Files.Glob "files/**").AsConfig ) -}}
```
_this renders the files to a string and stores it in `.Values.renderedfiles`_

Then in the child chart, you can do something like this
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
  namespace: default
data:
# from base
{{ .Values.parent.renderedfiles | indent 2 }}
# from local (child) context
{{ ($.Files.Glob ""files/**" ).AsConfig | indent 2 }}
```

**Comment by brian-groux-hs** [comment]
> Hello Brian, Could you please give the helm version you use to do the trick ? Did you get it work using a binary file ? ( using b64enc i guess)
> 
> thank you Bruno

`version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.16"}`

We were were merging source code files into a single configmap from both the parent and child. Not 100% how this would work with binaries. I am guessing as long as the render into variable didn't try to mangle the encoding it should work? I mean if `.AsConfig ` works for you today it should work when rendering into a variable unless there is some encoding/decoding that Helm would do implicitlly.

**Comment by Timo-Weike** [comment]
This is still a problem and the work around of @brian-groux-hs does not work for us.

We for now fallback to the workaround the the parent chart renders the needed files into config-maps.

**Comment by colearendt** [comment]
Unfortunately @brian-groux-hs 's example does not work when a [library chart](https://helm.sh/docs/topics/library_charts/#helm) is involved either, because library charts are not permitted to execute templating code and `$.Files.Get` runs in the context of the calling chart (not the subchart / library chart where I want it to). It would be very nice to be able to embed files into the "defining chart"'s context.

As it is, my workaround will likely be to generate an out-of-helm helper that embeds files in helper functions (appending `define`, the file and `end` together, for instance)

**Comment by colearendt** [comment]
Wanted to share the solution we came up with in case it is useful to anyone else. Objective is to embed files inside of a library chart so that they can be easily used and referenced in parent charts. Technically the inverse of what is requested in this issue, but related in some fashion.

Specifics:
1. use a script / helper / etc. (we used [`just`](https://github.com/casey/just), which took a bit of escaping). This creates a file that _looks_ like a usual `.tpl`
```
# example of a single line... weird escaping is a Justfile convention
echo {{ '{{- define \"my-chart.b64.job\" -}}' }} >> $FILEPATH
```
2. Inline and Base64 encode the input files (to protect against escaping / etc.). These blobs can then be referenced by parent charts
```
echo {{ '{{- define \"my-chart.b64.job\" -}}' }} >> $FILEPATH
cat $INCLUDE_DIR/job.tpl | base64 >> $FILEPATH
echo {{ '{{- end }}' }} >> $FILEPATH
```
3. Test and ensure that the desired output is being generated
```
{{- define "my-chart.b64.job" -}}
IyBWZXJzaW9uOiAxCmFwaVZ...
{{- end }}
```
4. Define the user-facing helper that base64 decodes the data:
```
{{- define "my-chart.job" -}}
  {{- include "my-chart.b64.job" nil | b64dec }}
{{- end }}
```
5. Call this template helper if/when needed in parent charts to inject the desired files (i.e. `{{ include "my-chart.job" nil }}`)

**Comment by WoodyWoodsta** [comment]
I'm still looking for this as well. The config map pattern of including files works best when using `{{ Files.get "" }}`, and so this only works if it's in a top level chart.

**Comment by gilesknap** [comment]
> I found a way around this limitation for anyone interested. We were trying to render files from a parent and child into the same config map.
> 
> In the parent (we will call it `parent` in the example) in a non-underscored file, so for example "templates/blah.yaml"
> 
> ```
> {{- $_ := set .Values "renderedfiles" (($.Files.Glob "files/**").AsConfig ) -}}
> ```
> 
> _this renders the files to a string and stores it in `.Values.renderedfiles`_
> 
> Then in the child chart, you can do something like this
> 
> ```
> ---
> apiVersion: v1
> kind: ConfigMap
> metadata:
>   name: myconfigmap
>   namespace: default
> data:
> # from base
> {{ .Values.parent.renderedfiles | indent 2 }}
> # from local (child) context
> {{ ($.Files.Glob ""files/**" ).AsConfig | indent 2 }}
> ```

@brian-groux-hs I'm trying to use your approach above. I can't get the .Values.parent to work in the child - I assume 'parent' is the 'name:' supplied in the parent's Chart.yaml. I don't think this works - the only values from parent that I can see in child are 'global:' ones. But I can't see how to get your syntax for setting values to work for global.

Please could you share the details of the parent that you got this working with? 

Thanks!

**Comment by MaxWinterstein** [comment]
@brian-groux-hs I would also love to see a reproduction of that. As you can see a few out here would love to adopt this. Passing files to subcharts is discussed in other issues as well.

According the docs, and my experience, this is true:

> For that reason, a subchart cannot access the values of its parent.

Source: https://helm.sh/docs/chart_template_guide/subcharts_and_globals/

I did some digging and found this statement:

> Helm works by pulling in a chart and all the dependencies into a global namespace and then renders all of the templates there. The first time a template is defined it is the one used everywhere. This is one of the things that enables library charts. This is what is causing you a problem.

Source https://github.com/helm/helm/issues/8804#issuecomment-700733687

Which made me belive, if the order of the files would be correct, this might work.

But no matter how hard I drop `a` and `0` before stuff, when looking at the output of `helm template...` it seems like subcharts are rendered before the parent, so this wouldn't work.

---

We have kinda similar thing and I currently solve it by passing the files via `--set-file` and some wild bash one liner 

```bash
$(for i in $(ls config/); do echo -n \ --set-file mySubChart.files.${i//./\\.}=./config/$i;done)"
```
