### ISSUE TITLE
Optimize scanReposForURL function

### ISSUE THREAD

**Issue by technosophos** [helm/helm#1904]
Per #1855, there is probably a way to optimize the traversal algorithm (maybe with a cache) that is used by scanReposForURL()

**Comment by thomastaylor312** [comment]
@technosophos This is probably a good one to try and do as part of 2.4 given its focus 😄, should we bring it in?

**Comment by irajdeep** [comment]
@technosophos I am planning to work on this if no one else is currently working on it :)

**Comment by thomastaylor312** [comment]
@irajdeep Sounds great! I would target Helm v3 as we are mostly focusing on bug fixes for v2

**Comment by irajdeep** [comment]
sounds cool, I will start working on it then
