### ISSUE TITLE
Proposal: add dependency define command

### ISSUE THREAD

**Issue by scottrigby** [helm/helm#1947]
When a kubernetes chart version bumps, it's dependency in other charts must also be bumped. This however (as I found out in kubernetes/charts/pull/619) is rather tedious. 

I temporarily wrote a quick [dependency version bump utility script](https://gist.github.com/scottrigby/4cba8b7454c3ecb38a1136cd06261092) that works well enough for now, but this is of course not ideal.

I looked at the `helm dependency` commands:
```sh
Available Commands:
  build       rebuild the charts/ directory based on the requirements.lock file
  list        list the dependencies for the given chart
  update      update charts/ based on the contents of requirements.yaml
```
But if there were a utility to *define* dependencies, that in combination with the existing tool to update would make this process a breeze.

A *define* command could be something like:
```sh
Available Commands:
  …
  define      define a dependency for a given chart

Usage:
  helm dependency define CHART DEPENDENCY VERSION REPOSITORY

If the dependency already exists for the chart, and REPOSITORY is not passed, the existing defined repository will remain.
```

Or something like that. I'm opening an issue rather than a Golang PR because:
1. This is (maybe?) faster, and
2. I'm new to Helm and Charts, and want to think through the value of this with the community before adding it.

Thoughts?

**Comment by technosophos** [comment]
I'd definitely accept a PR for this feature. It would be useful for sure.

Probably the ARGV line would look like this: `hem dep define DEPENDENCY REPOSITORY -v VERSION -f (or -c) PATH_TO_CHART (default: ".")`

That would make VERSION and PATH_TO_CHART optional, which seems right to me.

**Comment by technosophos** [comment]
@larryrensing is working on this.

**Comment by scottrigby** [comment]
From [Slack](https://kubernetes.slack.com/archives/helm/p1487266071012948):

@larryrensing is up for collaborating on this together. 

Do you want to add me as an assignee?

I've been planning on working on this together with @rabellamy too (specifically as I'm currently learning Golang… finally).

I'm in the Helm public dev meeting now so we can talk about how to best collaborate (we can also always use Slack as our entry point).

**Comment by prydonius** [comment]
+1 this will be a great step in automating updating chart dependencies, which I suspect @bitnami-bot will find useful :)

cc @sameersbn

**Comment by technosophos** [comment]
Bumped to 2.4.0 because the PR wasn't quite ready.

**Comment by technosophos** [comment]
Bumped to 2.5.0

**Comment by technosophos** [comment]
The WIP PR for this has been closed for lack of progress, which means this is not going to get done in time for 2.5.0. Deferring this to 2.6 and marking it as Help Wanted.

@scottrigby if this is still something you'd like to work on, lemme know. Otherwise, we'll try to get some momentum behind it after 2.5 is released.

**Comment by thomastaylor312** [comment]
It looks like work has stalled on this so I am bumping back on the backlog milestone. If someone would like to take this on, let us know.

**Comment by bacongobbler** [comment]
I think it's safe to close this after 3 years of inactivity. If further interest comes up let's reopen this.
