### ISSUE TITLE
Add --label flags to add new label pairs during installation

### ISSUE THREAD

**Issue by DoctorZK** [helm/helm#1950]
For developers using public repository and templates, they might want to add labels about the release during "helm install *", in which way, developers can characterize his own releases without modifying the template files in the template directory. We have two approaches in mind to solve this problem:
1, patching metadata.labels.$key with $value after release installation
2, rendering  the template files and and adding lines in template.yaml and value.yaml before release installation.

We prefer the first approach, since which decoupes the helm client and tiller server. Further it follows the principle that rendering releases in the tiller server rather than in the helm client. Which approach would you prefer?

**Comment by technosophos** [comment]
In the past, we've talked about doing it this way:

- Render templates
- Inject the labels into every resource definition
- Save and install the modified manifests

But there are a couple of difficulties:

1. If the template already defines a label that is passed in with `--label`, which do we prioritize?
2. On resource types that have multiple label paths (Deployments, RS, RC), do we only patch the top-level labels (`metadata.labels`), or do we also patch the spec template labels?
3. During upgrade, how we merge the labels that were specified in the install with the labels specified in upgrade.
4. During upgrade, how do we handle a case where an upgrade's template value overrides a label set on install using `--label` 

I think that if we can figure these out, then we could implement this sort of feature.

**Comment by technosophos** [comment]
This now supersedes #1800 

Also, with Helm 2.2.0, the new changes to the `pkg/kube` are done, which means this fix is much easier now than it was a month ago.

/cc @sbezverk  @kfox1111 and @intlabs

**Comment by technosophos** [comment]
I'm marking this as "help wanted", but we do need to answer those few open questions before beginning to implement this.

**Comment by DoctorZK** [comment]
For your questions: 

1,If the template already defines a label that is passed in with --label, which do we prioritize?
  The value that is passed in --label should be prioritized, since developers might use this --label to update the label, which is similar with --set

2, On resource types that have multiple label paths (Deployments, RS, RC), do we only patch the top-level labels (metadata.labels), or do we also patch the spec template labels? 
   For resources with pod engaged(i.e.,"Deployment", "ReplicaSet", "StatefulSet", "DaemonSet" ) , we patch the labels for both the top-level labels and the spec template labels. Otherwise, we only patch labels for their top-level labels.

3, During upgrade, how we merge the labels that were specified in the install with the labels specified in upgrade.
   This is an excellent question, however, we do not figure out a simple and proper solution for this question. We will insistently work on this question and propose a proposal shortly for solving this question.   
  
4, During upgrade, how do we handle a case where an upgrade's template value overrides a label set on install using --label
 The value in the upgrade template should be prioritized, since upgrade process is triggered after installation, and the latter the value is passed to tiller, the higher priority it gains.

**Comment by DoctorZK** [comment]
For the third question : "During upgrade, how we merge the labels that were specified in the install with the labels specified in upgrade." 
We find an effective approach to solve this problem. We drop the specified label pairs through "--label" during installation if we use traditional upgrade method. And we change tiller to support users specify the "--labels" to redefine the label pairs if they want the labels pairs to take effects after upgrade. What is your opionion about this solution?

**Comment by vinayagg** [comment]
Will it be better to provide --set that can create or (if value already exists) override any value in deployment yaml?
We can use it for so many features. 
helm --set metadata.labels.name=myapp --set spec.type=NodeIp <myapp>

**Comment by bacongobbler** [comment]
@vinayagg that was added in https://github.com/kubernetes/helm/pull/2557. :)

As for the original issue, I'm starting to dislike `helm init` being our documented process for configuring a tiller instance and I would push back on adding features like `--label` moving forward.

`helm init`'s original goal was to be a very simple command to install a tiller instance for developer's  ease of use, not for production deployments. We've essentially re-implemented core helm features for `helm init` itself. For example, `helm upgrade` was basically reverse-engineered and re-implemented as `helm init --update`. This is not a long-term scalable solution where we have to re-implement every core feature of `helm` to bootstrap tiller. The problem is that we've opened these floodgates and as such, `helm init` has become the de-facto process for users wanting to deploy Tiller.

I do not have an answer to this problem (other than to deploy kubernetes manifests that mimic `helm init` using `kubectl`), but I would *love* to gather a discussion group around this topic at the dev summit in January. This has been a growing concern for other tools similar to Helm like [`draft`](https://github.com/Azure/draft).

**Comment by mfilotto** [comment]
/remove-lifecycle stale

In our ci, it would be very handy to easily find and display logs of pods of the same release ( with a label release for example )

**Comment by ensonic** [comment]
Meh, this would be still nice to have. Applying a label during the installation would serve as a nice marker of what was installed together.
@DoctorZK did you close since you lost hope, that this ever gets done?

**Comment by alahijani** [comment]
Any chance this will be re-opened?

**Comment by bacongobbler** [comment]
I'll re-open this. This would be a useful feature for someone from the community to tackle.

**Comment by JianrongZhangBoston** [comment]
This feature is indeed very useful and I'd love to see it implemented.

**Comment by dotw** [comment]
we also need this feature since we install the same chart for different users and we'd like add labels to the instances to let Prometheus collect monitoring resources.

**Comment by hickeyma** [comment]
@thomastaylor312 I wonder if post-render #7260 could satisfy this use case?

**Comment by thomastaylor312** [comment]
Yes, I think the new post-render stuff will satisfy this use case

**Comment by hickeyma** [comment]
Closing as feature supported in #7260

**Comment by ThomasSteinbach** [comment]
@hickeyma The post-render hook (#7260) does not satisfy this use case, because he does not process hooks (#7891). It would be really nice having a simple option to add labels to really all resources.

**Comment by zees-dev** [comment]
Agree with @ThomasSteinbach here.

It requires too much effort to add labels onto the manifests resources.

To add labels via post-rendering; i'm assuming one would need to create an executable/script which loops through the resources of the manifest and adds labels onto them.
This would be an external dependency that would need to be managed/distributed separately.

**Comment by sethgupton-mastery** [comment]
+1 for having a simple option to add labels to really all resources including hooks.

**Comment by jojotong** [comment]
Recording to:
```go
type PostRenderer interface {
	// Run expects a single buffer filled with Helm rendered manifests. It
	// expects the modified results to be returned on a separate buffer or an
	// error if there was an issue or failure while running the post render step
	Run(renderedManifests *bytes.Buffer) (modifiedManifests *bytes.Buffer, err error)
}
```
I use `PostRenderer` and kustomize library to implement custom labels, eg:
```go
import (
        ...
	"sigs.k8s.io/kustomize/kyaml/kio"
)
...

var render = myPostRender{}

type myPostRender struct{}

func (r *myPostRender) Run(renderedManifests *bytes.Buffer) (modifiedManifests *bytes.Buffer, err error) {
	nodes, err := kio.FromBytes(renderedManifests.Bytes())
	if err != nil {
		return renderedManifests, errors.Wrap(err, "parse rendered manifests failed")
	}
	for _, v := range nodes {
		labels := v.GetLabels()
		if labels == nil {
			labels = make(map[string]string)
		}
                // your labels
		labels["key"] = "value"
		v.SetLabels(labels)
	}

	str, err := kio.StringAll(nodes)
	if err != nil {
		return renderedManifests, errors.Wrap(err, "string all nodes failed")
	}

	return bytes.NewBufferString(str), nil
}
```
