### ISSUE TITLE
Add lint rule for spec.matchLabels on Deployment

### ISSUE THREAD

**Issue by technosophos** [helm/helm#1990]
Resources like Deployment, ReplicaSet, and DaemonSet should, as a best practice, declare `selector.matchLabels` rules in their pod template:

https://kubernetes.io/docs/concepts/tools/kubectl/object-management-using-declarative-config/#defining-controller-selectors-and-podtemplate-labels

Doing so prevents a number of odd-ball cases where pods are not appropriately updated.

We should write a linting rule to catch this case.

**Comment by thomastaylor312** [comment]
This could be a nice stretch goal feature for 2.4 if we are able to finish the other work.

**Comment by bacongobbler** [comment]
related: #2694
