### ISSUE TITLE
Support federated k8s cluster

### ISSUE THREAD

**Issue by podollb** [helm/helm#1998]
It seems that helm is unable to work with k8s federated clusters. Is getting that working on the roadmap?

**Comment by rcarlson8974** [comment]
This is our #1 issue right now.  To get HA, we need to be in multiple regions and zones.  To deploy once, we need Federated clusters.  Without this getting implemented, we have to do something kludgy like running a helm command per cluster, which is less than ideal or dropping down to kubectl which also has limitations.  I would love to see this added to the road map.

**Comment by technosophos** [comment]
We would _love_ to add this feature. We talked about it during the last KubeCon, but honestly we need some help.

Tiller can talk to exactly one Kubernetes API server right now. If that API server can make the federation transparent, Helm could probably work.

I'd need to look at the docs, but if the control plane provides a Kubernetes API server, it might be possible to deploy Tiller into the control plane and point it at that API server. But, again, I don't know enough about the functioning of a federation to be sure about this.

Would love to talk about this more, and begin identifying the details.

**Comment by technosophos** [comment]
I'm trying to gauge interest in this feature. Please weigh in here (even if it's just a 👍 ) so that I can figure out how important this is to people.

**Comment by rcarlson8974** [comment]
👍 👍 👍 👍 👍 👍 👍 👍 👍 👍

**Comment by podollb** [comment]
Agree. It's pretty important IMHO, especially now that people are starting to move to federated k8s deployments (so it's a fork in the road, to continue to use helm, with no support to deploy to a federated k8s with helm).

**Comment by iamzhout** [comment]
wanted +1 :+1:

**Comment by acts-human** [comment]
+1 👍

**Comment by unguiculus** [comment]
:thumbsup:

**Comment by omegarus** [comment]
+1

**Comment by sethew** [comment]
👍

**Comment by nilsher** [comment]
👍

**Comment by szibis** [comment]
:+1:

**Comment by nagas** [comment]
👍

**Comment by technosophos** [comment]
That's enough evidence to convince me. ;-)

**Comment by v1k0d3n** [comment]
big huge :+1: from us @technosophos

**Comment by rimusz** [comment]
👍

**Comment by bobhenkel** [comment]
:+1: :+1:

**Comment by rcarlson8974** [comment]
@technosophos ballpark ETA on when something (even beta) might be ready?  We are going live in a couple weeks and if there was a chance something would be ready by then, it would change some of our sprint planning, etc....

**Comment by bacongobbler** [comment]
no ballpark ETA on this. There is an experimental backend for tiller at https://github.com/kubernetes-helm/rudder-federation which @nebril is working on, but there are no plans on adding this to the roadmap any time soon. Please feel free to give that a shot.

I know your comment was from March, but from what I've seen, federation support was just pulled out of kubernetes core into https://github.com/kubernetes/federation so I'm not sure how far out federation support will be considered stable at this point. It's November and kubernetes federation support is still very much in an alpha state. I wouldn't consider going live with federation support if you're going to be running this in production.

**Comment by naveensrinivasan** [comment]
@technosophos Any update on this?

**Comment by v1k0d3n** [comment]
huge 👍👍 from this guy... :)

**Comment by v1k0d3n** [comment]
@technosophos, this is a pretty old issue but maybe it could be retitled for the federation-v2 model? most everyone is well aware of this work already, but for those who aren't it can be found [at this link](https://github.com/kubernetes-sigs/federation-v2).

**Comment by danehans** [comment]
[federation-v2](https://github.com/kubernetes-sigs/federation-v2) appears to be the future of Kubernetes Federation. I understand v2 is not production ready, but should https://github.com/helm/helm/issues/2539 target this version instead of v1?

**Comment by bacongobbler** [comment]
closing as stale. Please feel free to comment here if you're working on federation support. Thanks!
