### ISSUE TITLE
Provide signed binaries. EOM.

### ISSUE THREAD

**Issue by redbaron** [helm/helm#2039]

**Comment by bacongobbler** [comment]
It appears checksums are uploaded along with the binaries. It's just not in the release notes. See https://github.com/kubernetes/helm/blob/master/scripts/ci/deploy.sh#L47

Does that work for you?

**Comment by bacongobbler** [comment]
e.g. the checksum for the linux binary is at https://storage.googleapis.com/kubernetes-helm/helm-v2.2.1-linux-amd64.tar.gz.sha256

**Comment by redbaron** [comment]
@bacongobbler , having checksum isn't enough as it doesn't protect from silent code/tarball replacement. Ideally there should be a signature  file for every `.sha256` file. Public key  for signature verification should be published outside of regular code sharing/distribution infrastructure,so no github or CDN. publish it to keybase.io or to any GPG keyserver

**Comment by technosophos** [comment]
I agree that we should be doing this. After all, we can cryptographically sign charts, but we don't cryptographically sign Helm itself.

Once we have the build system reworked (#1968), we should be able to accomplish this.

**Comment by thomastaylor312** [comment]
Marking as keep open because it is blocked by #1968

**Comment by mattfarina** [comment]
As of the RC that just went out we are now signing. See https://github.com/helm/helm/releases/tag/v2.13.0-rc.2

I'll close after v2.13.0 goes out. If there are any issues with this please let us know.
