### ISSUE TITLE
Can't build helm (github.NewClient dependency problem)

### ISSUE THREAD

**Issue by sgoings** [helm/helm#207]
After running:

```
make bootstrap
make build
```

I get:

```
go build -o bin/helm -ldflags "-X main.version=v0.1.0+611a8f3" helm.go
# github.com/deis/helm/release
release/latest.go:24: cannot use github.NewClient(nil).Repositories (type *github.RepositoriesService) as type GHRepoService in assignment:
	*github.RepositoriesService does not implement GHRepoService (missing GetLatestRelease method)
make: *** [build] Error 2
```

**Comment by sgoings** [comment]
google/go-github dependency was on this commit in the vendor directory:

```
commit 930e6fdb8dc2b11458fdeb55b3cd68e5370a1a28
Author: Will Norris <will@willnorris.com>
Date:   Wed May 6 09:20:34 2015 -0700

    add Victor Castell as contributor
```

Going into `vendor/github.com/google/go-github` and executing a `git pull origin master` fixed the problem above. However... this reveals an underlying problem that we are not pinning all versions to a specific one or forcing an update to the latest HEAD of that dependency.

**Comment by michelleN** [comment]
:scream: yeah, the glide.yaml file doesn't specify a specific version for github.com/google/go-github. I'm surprised glide didn't get HEAD.

**Comment by mattfarina** [comment]
@sgoings thanks for sharing this. Did you happen to have `github.com/google/go-github` in your `GOPATH` prior to running those two make commands? If you did, did you happen to have a specific version checked out?

I'm attempting to figure out why you would have experienced that issue.

You can learn more about what happened by running the following command instead of make bootstrap. Just be sure to remove your `vendor/` directory first.

```go
$ glide --debug -y glide-full.yaml up
```

This will provide a bunch of debugging information. It might tell you what happened.

**Comment by sgoings** [comment]
@mattfarina I did have github.com/google/go-github in my GOPATH with version: 

```
commit 930e6fdb8dc2b11458fdeb55b3cd68e5370a1a28
Author: Will Norris <will@willnorris.com>
Date:   Wed May 6 09:20:34 2015 -0700

    add Victor Castell as contributor
```

Which was the same version that existed in my vendor directory (see above).

After changing vendor/github.com/google/go-github/ back to version `930e6f...` (which was the cause of this problem) I ran the debug version of glide you supplied and got the following output: https://gist.github.com/sgoings/eadea640e08ea5fc0ac0

**Comment by michelleN** [comment]
@sgoings I just ran into the same issue.

**Comment by mattfarina** [comment]
I think I know what might be causing this. Glide now tries to get packages from your GOPATH. If no version is set in the `glide.yaml` file it attempts to discover the default branch. For example, it will make calls to the GitHub API to get it. But, there are times where anonymous API limits can be hit or some places where it just can't figure out the default branch so it leaves it with what's in the GOPATH.

The short term fix is to always set a version or use the `--skip-gopath` flag (e.g., `glide up --skip-gopath`). Any suggestions on an alternative?

**Comment by michelleN** [comment]
@mattfarina That make sense. I had go-github in my GOPATH checked out on a very old version (idk why). For now, I've pinned to a particular version. It seems like the safest option.

**Comment by mattfarina** [comment]
@michelleN work on the 0.8 version of Glide should fix this situation (and remove the need for the `glide-full.yaml` file).
