### ISSUE TITLE
Helm client connection to tiller pod

### ISSUE THREAD

**Issue by moshe0076** [helm/helm#2212]
Hi,

I'm having a problem connecting to the Tiller pod running on a Kubernetes cluster on AWS. The thing is that for the connection from the Helm client on my computer to work I need to open all TCP ports between the Kubernetes nodes.
Is this the only way to go? Is there a port range that need to be open between the nodes?

Thanks,
Moshe

**Comment by thomastaylor312** [comment]
It [looks like](https://github.com/kubernetes/helm/blob/master/pkg/kube/tunnel.go#L87) it is not configurable right now and there isn't a specific port range. If you'd like, we can turn this into a feature request and discuss the possibility of adding it.

**Comment by moshe0076** [comment]
Hi,
Yes please.
Controlling the the port range will sure make it more secure and logical from my point of view.

Thanks!

**Comment by moshe0076** [comment]
Thanks All!

**Comment by bacongobbler** [comment]
closing as inactive.
