### ISSUE TITLE
add --kubeconfig option

### ISSUE THREAD

**Issue by scheeles** [helm/helm#2219]
In kubectl there is the option for ```--kubeconfig=''``` It is the path to the kubeconfig file to use for CLI requests.

I would like to be able to to the same with helm.

**Comment by seh** [comment]
Here's a small fragment I've used in some of my programs, which may involve some cruft that _client-go_ no longer mandates:
```go
// Assume: fs *pflag.FlagSet
// Assume: interactive bool
loadingRules := clientcmd.NewDefaultClientConfigLoadingRules()
fs.StringVar(&loadingRules.ExplicitPath, "kubeconfig", "",
	`Path to the kubeconfig file to use`)
overrides := &clientcmd.ConfigOverrides{}
// This adds a whole bunch of related flags that we find in kubectl.
clientcmd.BindOverrideFlags(overrides, fs, clientcmd.RecommendedConfigOverrideFlags(""))

var clientConfig clientcmd.ClientConfig
if interactive {
	clientConfig = clientcmd.NewInteractiveDeferredLoadingClientConfig(loadingRules, overrides, os.Stdin)
} else {
	clientConfig = clientcmd.NewNonInteractiveDeferredLoadingClientConfig(loadingRules, overrides)
}
```

**Comment by thomastaylor312** [comment]
Is there any problem with specifying the `KUBECONFIG` env variable? Helm does honor it

**Comment by technosophos** [comment]
I'd be find adding a global option for this. It should be pretty straightforward, since this would follow the same pattern as `--host` and `$HELM_HOST`.

**Comment by kenden** [comment]
@thomastaylor312 using `KUBECONFIG` works, but I personally prefer a `--kubeconfig` option if I just have one command to run. 
Then it is just one command to type (`helm`) instead of two (`export` and `helm`).

**Comment by seh** [comment]
Per [my earlier comment](https://github.com/kubernetes/helm/issues/2219#issuecomment-291851452), I think that if you're going to allow specification of a configuration file, you should also accept the same override flags that _kubectl_ does.

**Comment by scheeles** [comment]
I think helm should provide the same UX experience like kubectl, where it make sense.  Most of the time I use `--kubeconifg` instead of `export` & `kubectl` or `helm`

**Comment by gogodi91** [comment]
Using --kubeconfig when running the helm command would help reduce ambiguity if running helm on a automated basis. When using environment variables in this manner, race conditions might occur and you might end up running your helm chart against a k8s stack you didnt want to.

**Comment by gardlt** [comment]
could I take a crack at this issue?

**Comment by bacongobbler** [comment]
re-opening as #2621 was reverted due to breaking $KUBECONFIG as seen in #3378

**Comment by Nowaker** [comment]
It'd be nice to have this implemented... again. :laughing:

**Comment by rchakra3** [comment]
First time contributor - can I pick this up?

**Comment by bacongobbler** [comment]
Yep!

**Comment by rchakra3** [comment]
I've got a PR up. I'd appreciate a review! :)

**Comment by iahmad94** [comment]
@rchakra3 Thank you! Any idea when this will get merged in? I'm currently in a situation where the  --kubeconfig flag would be very helpful!

**Comment by bacongobbler** [comment]
Feel free to test this feature with v2.10.0-rc.3!

**Comment by schollii** [comment]
Meanwhile another option when running from bash is this: 

`KUBECONFIG=path/to/config kubectl ...`

**Comment by retr0h** [comment]
I ended up being lame for now, and adding a zsh function to my shell.

```
kubecctx() {
    KUBE_CONTEXT_DEFAULT_FILE=config.yml
    KUBE_CONTEXTS_DIR=~/.kube/contexts
    KUBE_CONTEXTS=$(ls -d ${KUBE_CONTEXTS_DIR}/* | xargs -n 1 basename)
    KUBE_CONTEXT_CURRENT_CONTEXT=$(echo "${KUBE_CONTEXTS}" | fzf)

    KUBECONFIG="${KUBE_CONTEXTS_DIR}/${KUBE_CONTEXT_CURRENT_CONTEXT}/${KUBE_CONTEXT_DEFAULT_FILE}"

    echo "Switched to KUBECONFIG '${KUBECONFIG}'."
}
```
