### ISSUE TITLE
add golint to bootstrap

### ISSUE THREAD

**Issue by michelleN** [helm/helm#226]
Currently github.com/golang/lint/golint is not included in the list of dependencies identified by the glide file. The `make test` command requires it, so should it be put in? I guess not everyone using glide is writing tests and actively developing so I don't want to add an unnecessary dependency. Anyone have thoughts?

**Comment by sgoings** [comment]
My thought is we should add this depedency in via a similar process as we do with `make bootstrap`. Thoughts?

**Comment by ingvagabund** [comment]
As long as golint is not needed exclusively for building, it should not go into the glade.yml file. For some golang projects I use a dependency file (Godeps.json, GLOCKFILE, ...) to checkout out if all project's dependencies are present (imported package) and up-to-date (commit) on my system. Introducing non-building dependency will give a false alarm I am missing one deps even if I am not.

**Comment by mattfarina** [comment]
For the time being I would suggest using `go get` to retrieve it. Glide will put the build dependencies in the `vendor/` folder. With `golint` you really want it in the GOPATH and installed as a binary so it can be called against the codebase.

What's the planned usage for `golint`? Since [helm currently has 0 golint issues](http://goreportcard.com/report/deis/helm) may I suggest that it's run on pull requests and a comment filed to any pull request that raises any golint issues.

**Comment by mboersma** [comment]
> What's the planned usage for `golint`?

It is run on all go code by `make test-style` (or `make test`), and is run by Travis CI on each PR. (Getting to 0 issues was mostly a matter of adding comments.)

I added it to [.travis.yml](https://github.com/deis/helm/blob/master/.travis.yml#L23) but left installing `golint` as an exercise for the reader. :-p I think adding `go get github.com/golang/lint/golint` to `make bootstrap` is the way to go for now.

**Comment by technosophos** [comment]
I agree with the sentiment that the right place to add `golint` is to the `bootstrap` Makefile target. @michelleN would you mind re-titling the issue to reflect that? I think it should be a pretty simple fix from there.

**Comment by technosophos** [comment]
Or, alternately, we could add a bootstrap-dev target that adds dev dependencies.

**Comment by sgoings** [comment]
More than one bootstrap make target makes me cringe. Still in favor of putting it within `make bootstrap`. I'll submit a PR for this right quick.

**Comment by technosophos** [comment]
Yeah, on further consideration, I think it should go under `bootstrap`, whose target audience is developers and CI -- the two groups that need the linter.
