### ISSUE TITLE
`helm install` should ask for confirmation when auto-choosing a release name

### ISSUE THREAD

**Issue by majewsky** [helm/helm#2269]
I just rolled out my application to a new k8s cluster. Because the `helm install` line gets pretty long pretty fast, I used a previous dry run from my shell history:

```
helm install path/to/chart --namespace foo --values /path/to/values.yaml --dry-run --debug
```

and just removed the `--dry-run --debug` from the end. Only after Helm was done did I notice that I hadn't set `--name foo` as usual, resulting in one of these cutesy autogenerated names that break my workflow because I expect `release_name == chart_name` everywhere. So an additional roundtrip of `helm delete --purge` and `helm install` was necessary.

It would be nice if, when running interactively, `helm install` would ask for confirmation when auto-choosing a release name (except, of course, for dry runs), e.g.

```
$ helm install path/to/chart
Deploy this chart as "eager-lemur"? [Y/n] 
```

**Comment by bacongobbler** [comment]
This would break backwards compatibility with the current CLI (meaning: won't happen in the v2.0 timeline), and this does partially boil down to user error. However, I do understand the viewpoint where "safety comes first".

Would a wrapper around your helm binary suffice?

```
#!/bin/sh

if [ "$1" != "install" ]; then
    exec helm "$@"
fi

while true; do
    read -p "Are you sure you want to do this? " yn
    case $yn in
        [Yy]* ) exec helm "$@"; break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done
```

Usage: `helm.sh install ...`

If not then perhaps a feature flag like `--prompt` could be a potential feature if you want to write it up.

**Comment by bacongobbler** [comment]
slating this as a Helm 3 discussion topic.

**Comment by stealthybox** [comment]
+💯

When I'm teaching new users helm, they frequently install charts without providing a name.
The behavior is too magical.

This can result in one dev creating 10 or so `adjective-animal` releases of their chart as their learning, or an infra team member installing some cluster service without a proper name, leading to us having to reinstall it.

IMO this should be an opt-in flag like `--generate-name`.

**Comment by stealthybox** [comment]
> Would a wrapper around your helm binary suffice?
This would not suffice for teaching new users.
The tooling should be safe as a standard.

This would be a good improvement to consider for Helm 3

**Comment by bacongobbler** [comment]
Agreed. I already threw this on the milestone a few months ago, so after we release the alpha of helm 3 with the core infrastructure rebuilt, we'll start looking into these tickets. Totally agree with your thoughts on this

**Comment by bacongobbler** [comment]
Currently in Helm 3, the user [must provide a name or provide `--generate-name`](https://github.com/helm/helm/blob/ba622c69419aed463335caeeb63db9d8b0229a64/cmd/helm/install.go#L199). If neither has been done, then it errors out.

Closing as resolved.
