### ISSUE TITLE
Feature: Stream hook logs back to helm client

### ISSUE THREAD

**Issue by johnw188** [helm/helm#2298]
When performing helm release operations such as `install`, `upgrade`, `delete` and `rollback`, the helm client will block without feedback while hooks execute. If chart owners aren't careful with their error handling, kubernetes can put the hook job into an infinite loop of failure. Conversely, long running hooks such as database migrations can be executing successfully while the user is unaware that code is executing.

To mitigate these issues helm should stream hook logs back to the helm client.

## UI

Successful install:
```
› helm install internal/jenkins
Executing pre-install hooks: ldap-update-job, credential-update-job
[credential-update-job] Updating Jenkins credentials
[ldap-update-job] Updating LDAP configuration
[credential-update-job] Validating credentials
[credential-update-job] Successfully updated credentials!
[ldap-update-job] Successfully updated LDAP!

Executing post-install hooks: migrate-db
[migrate-db] Starting database migration
[migrate-db] Database migration completed

Install was a success! Happy Helming!

```

Install with issues:
```
› helm install internal/jenkins
[credential-update-job] Updating Jenkins credentials
[ldap-update-job] Updating LDAP configuration
[credential-update-job] Validating credentials
[credential-update-job] Successfully updated credentials!
[ldap-update-job] ERROR: Invalid password/token for user: john.welsh
[ldap-update-job] Updating LDAP failed
[credential-update-job] Updating Jenkins credentials
[ldap-update-job] ERROR: Invalid password/token for user: john.welsh
[ldap-update-job] Updating LDAP failed
...
```

Open questions

- Timestamps?
- Should pod name be surfaced somewhere?
  - Note that the pod name can change if the hook fails or gets evicted before it completes
  - Pod names are super long (`john-ci-jenkins-update-credentials-xzz5f-1z166`)

Future enhancements

- Retry counter for jobs?

## Implementation

In the tiller proto definition:

```
// GetReleaseLogs gets a stream of log events for a given release.
    rpc GetReleaseLogs(GetReleaseLogsRequest) returns (stream GetReleaseLogsResponse) {
}

message GetReleaseLogsRequest {
    // Name is the name of the release
    string name = 1;
    // Version is the version of the release
    int32 version = 2;
}

message GetReleaseLogsResponse {
    // Source is the name of the hook that generated the log
    string source = 1;
    // Log is a single log line
    string log = 2;
}
```

The helm client will then make two gRPC calls - one to install, the other to grab logs.

Questions

- Is this too chatty? Should logs be collected and passed in chunks?
- Should the API be made specific to hooks (`GetReleaseHookLogsRequest`) or left more generic for future expansion?
- What other fields should be in the response object?

**Comment by thomastaylor312** [comment]
So I don't think pod names should be passed back exactly for the reason you specified. I don't think this is too chatty because I think most people prefer seeing the live output as they watch a release. Also, I can't think of another field you would need in the response (unless you use timestamps), but if I think of something, I'll drop it in here. I think the timestamps may be a good thing to add because it can be helpful for debugging, especially if you are not watching the release as it happens. They would allow for you to go back and see if certain events correlate.

As for the generic question, I think it would be the best to keep it as generic as possible. I could see the use case where someone using the `--wait` flag would want to watch the logs of the pods they are spinning up.

Thanks for taking this on, I am excited to see this!

**Comment by georgecrawford** [comment]
> I could see the use case where someone using the --wait flag would want to watch the logs of the pods they are spinning up.
Yes, yes, yes. That would be so useful for us. Is that in scope here? We have a setup which occasionally times-out a helm release, and seeing the logs from the pods created by the deployment would be fantastic.

**Comment by thomastaylor312** [comment]
@georgecrawford I don't think that is in scope for this issue specifically, but that will be easy to add with the design proposed

**Comment by technosophos** [comment]
Bumping this to 2.5, since the 2.4 release is slated for today.

**Comment by technosophos** [comment]
Any update on this? I'm reviewing issues for the stability/security requirement on 2.6, and not sure if this one is likely to be ready for review in time.

**Comment by sstarcher** [comment]
It would be great if this could make it in.

**Comment by technosophos** [comment]
Unfortunately, work seems to have stalled out on this. We'll give it a week or so, but then I'll have to bump this to 2.7

**Comment by johnw188** [comment]
Hey there, this issue has kind of been my bane. I'm going to take another crack at it this weekend to try to make 2.6.

Basically the streaming of logs is working great, clients can subscribe to logs and they get sent through via tiller. The problem is what I thought would be the easy part - accessing the pod logs from tiller so they can be streamed back.

**Comment by technosophos** [comment]
Any update on where we are with this? It's probably safer at this point to bump to 2.7

**Comment by bacongobbler** [comment]
ping, any update? Just checking whether we can expect the feature in time to review for 2.8 or if we should hold off on targeting specific milestones. Thanks! :)

**Comment by bacongobbler** [comment]
pulling off the milestone due to inactivity.

**Comment by max-zelinski** [comment]
we really need this feature - are there any updates? :)

**Comment by Natashaylwong** [comment]
we also need this feature. are there any updates?

**Comment by bacongobbler** [comment]
No but feel free to pick this back up! It looks like the original author is unresponsive.

**Comment by iczman** [comment]
This feature will be super helpful for debugging my hook failures. Right now I have to manually dig into the pod to read the log, which is painful since I'm usually reading logs at much higher level in GitLab CI. With this feature I can then bubble up any errors from my hook to tiller and then finally up to my CI.

**Comment by bacongobbler** [comment]
I haven't seen any movement from the community on this proposal. Closing as inactive.

**Comment by rafis** [comment]
Any update?
https://github.com/helm/helm/issues/3481
