### ISSUE TITLE
Using helm install -p <path> wipes out file content

### ISSUE THREAD

**Issue by jchauncey** [helm/helm#231]
It will remove all content from all files in the chart path.

**Comment by technosophos** [comment]
@jchauncey can you drop in the exact command you used? I'm trying to reproduce locally.

**Comment by jchauncey** [comment]
`helm install -p $PWD elasticsearch'

or

`helm install -p ~/.helm/workspace/charts/elasticsearch elasticsearch`

**Comment by technosophos** [comment]
Ah, so the input and output file are the same in that case? I think I see the error -- I think we truncate the output file. So essentially, any syntax error will obliterate your source file.

I'm leaning toward just disallowing setting the source and destination as the same file.
