### ISSUE TITLE
`helm delete {release}` deletes a StorageClass it didn't create when `helm install` fails

### ISSUE THREAD

**Issue by Mario54** [helm/helm#2349]
**Helm Version**

```shell
$ helm version
Client: &version.Version{SemVer:"v2.3.0", GitCommit:"d83c245fc324117885ed83afc90ac74afed271b4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.3.0", GitCommit:"d83c245fc324117885ed83afc90ac74afed271b4", GitTreeState:"clean"}
```

**Kubernetes Version**

```shell
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:44:38Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"dirty", BuildDate:"2017-04-07T20:46:46Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}
```

# Reproduction steps
Create a chart with a StorageClass.

```yaml
# templates/storageclass.yaml

apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
    name: standard
provisioner: kubernetes.io/gce-pd
parameters:
    type: pd-standard
    zone: us-east1-b
```

```yaml
# Chart.yaml

apiVersion: v1
description: StorageClass bug
name: storageclass
version: 1.1.1
```

Package the chart and install it.

```shell
$ kubectl get storageclass
NAME                 TYPE
standard (default)   k8s.io/minikube-hostpath

$ helm package .

$ helm install storageclass.tgz -n storageclass
Error: release storageclass failed: the API version in the data (storage.k8s.io/v1beta1) does not match the expected API version (storage.k8s.io/v1)
```

The install fails because of a mismatch between the resource and the Kubernetes version. The StorageClass isn't created.

```shell
$ kubectl get storageclass
NAME                 TYPE
standard (default)   k8s.io/minikube-hostpath
```

Then, I delete the release.

```shell
$ helm delete storageclass --purge

$ kubectl get storageclass
No resources found.
```

`helm` deletes the StorageClass even though `helm install` didn't create it. It already existed in the cluster. This can be dangerous as a resource can be deleted and the user doesn't know about it.

**Comment by redbaron** [comment]
been bitten by it as well. helm is doing something weird: instead of storing UIDs of resources it created, it saves names. it also uses latest realease in a history as source of truth (lets say to generate resource updates) ,even if that release was failing. these 2 together makes helm to "adopt" resources which are not part of a release and then delete all of them on release deletion :)

**Comment by technosophos** [comment]
Very likely, the solution we need to pursue is to use UIDs for all of the operations, which requires changing what is stored in the release object. That, in turn, will potentially break backward compatibility. So if anyone picks this up, _please be very careful_ to test backward compatibility for both larger charts (like Kolla) and for older release formats.

**Comment by dfernandezm** [comment]
Any update on this? We are currently pushing some automation with Helm to production and this issue is making it really dangerous. Any workaround to limit scope of FAILED vs DEPLOYED or how to get the real 'source of truth' on which resources belong to which release?

**Comment by redbaron** [comment]
Helm is dangerous, accept it :)

**Comment by bacongobbler** [comment]
closing as inactive.
