### ISSUE TITLE
Feature Request: helm delete --wait

### ISSUE THREAD

**Issue by ahawkins** [helm/helm#2378]
`helm install --wait` can wait for everything to be ready. Can a new `helm delete --wait` do something similar? I'm using `helm delete --purge` in my build pipeline followed by this script (to do something similar to `--wait`).

```
#!/usr/bin/env bash

set -euo pipefail

main() {
	local kinds=( Service Deployment Pod Secret ConfigMap )
	local counter=0 attempts=30

	for release in "$@"; do
		echo "--> Deleting release ${release}"

		if helm ls --kube-context "${KUBE_CONTEXT}" | grep -qF "${release}"; then
			echo "==> Found helm release; deleting with --purge"
			helm delete "${release}" --purge  --kube-context "${KUBE_CONTEXT}"
		else
			echo "==> No release found; deleting manually"

			for kind in "${kinds[@]}"; do
				echo "==> Deleting any dangling ${kind}"

				kubectl delete "${kind}" \
					-l "release=${release}" \
					-n "${KUBE_NAMESPACE}" \
					--force \
					--grace-period 0 \
					--context "${KUBE_CONTEXT}" 2>/dev/null
			done
		fi

		echo "--> Awaiting resource deleting confirmation"
		for kind in "${kinds[@]}"; do
			counter=0

			while [ $counter -lt $attempts ]; do
				pending_resources="$(kubectl get "${kind}" \
					-o wide \
					-l "release=${release}" \
					-n "${KUBE_NAMESPACE}" \
					--context "${KUBE_CONTEXT}" 2>/dev/null
				)"

				if [ -n "${pending_resources}" ]; then
					echo "${release} ${kind} still running. ${counter}/${attempts} tests completed; retrying."
					echo "${pending_resources}" 1>&2
					echo 1>&2

					# NOTE: The pre-increment usage. This makes the arithmatic expression
					# always exit 0. The post-increment form exits non-zero when counter
					# is zero. More information here: http://wiki.bash-hackers.org/syntax/arith_expr#arithmetic_expressions_and_return_codes
					((++counter))
					sleep 10
				else
					break
				fi
			done

			if [ $counter -eq $attempts ]; then
				echo "${release} ${kind} failed to delete in time.";
				return 1
			fi
		done

		echo "--> Awaiting helm confirmation"
		counter=0

		while [ $counter -lt $attempts ]; do
			if helm ls --all --kube-context "${KUBE_CONTEXT}" | grep -qF "${release}"; then
				echo "${release} still in tiller. ${counter}/${attempts} checks completed; retrying."

				# NOTE: The pre-increment usage. This makes the arithmatic expression
				# always exit 0. The post-increment form exits non-zero when counter
				# is zero. More information here: http://wiki.bash-hackers.org/syntax/arith_expr#arithmetic_expressions_and_return_codes
				((++counter))
				sleep 10
			else
				break
			fi
		done

		if [ $counter -eq $attempts ]; then
			echo "${release} failed to purge from tiller delete in time.";
			return 1
		fi
	done
}

main "$@"
```

**Comment by michelleN** [comment]
There needs to be some refactoring of the `--wait` logic before this can happen but yeah it makes sense.

**Comment by alisondy** [comment]
/remove-lifecycle stale
This is still an issue

**Comment by bacongobbler** [comment]
We removed the stale bot from helm/helm after the move to the CNCF. No need to try and remove the stale labels; it's all been removed. :)

**Comment by YingjunHu** [comment]
Any luck on this?

**Comment by bacongobbler** [comment]
Nope. Are you working on an implementation?

**Comment by YingjunHu** [comment]
Not yet since I wasn't sure if there's any ongoing fix. I'll try to implement it if it's not planned for both helm2 and 3

**Comment by bacongobbler** [comment]
AFAIK nobody's working on this. Feel free to work on an implementation!

**Comment by jamesla** [comment]
+1

**Comment by Sora233** [comment]
Hi @bacongobbler 
I am working on this now.
When I try to delete a deployment, I want to wait the pods controlled by the deployment until they all stop.
However those pods don't appear in the big chart manifest, I have no idea which label or selector I can use.
Any suggestions?

**Comment by marckhouzam** [comment]
@Sora233 I'm not familiar with this area but one possible investigation route would be to look at how the `helm install --wait` command determines what to wait for.

**Comment by Sora233** [comment]
@marckhouzam `helm install --wait` command watch the deployment until ready, that means all pods are good.
when run `helm uninstall`, deployment is deleted despit the pods.

**Comment by tomcruise81** [comment]
Any updates on this? Is there a PR that should be attached to it?

**Comment by bacongobbler** [comment]
No update

**Comment by tomcruise81** [comment]
Is the intention here that order would be respected too? Looking at the description of `helm install --wait`:

> if set, will wait until all Pods, PVCs, Services, and minimum number of Pods of a Deployment, StatefulSet, or ReplicaSet are in a ready state before marking the release as successful. It will wait for as long as --timeout

the description doesn't mention respecting sort order of manifests. If so, then it'd have implications on the implementation of #3635.

What I mean is, should Pods be terminated as part of something like uninstalling a Deployment, and those Pods all being terminated would allow moving to the next "kind" as per https://github.com/helm/helm/blob/master/pkg/releaseutil/kind_sorter.go#L66-L100. So **ALL** Deployments (and their respective Pods) would be uninstalled _prior to_ any ReplicaSets?

Is the reverse how `helm install --wait` works today - each Kind is waited on (if waiting is permitted) prior to moving to the next Kind?

**Comment by bacongobbler** [comment]
> Is the intention here that order would be respected too?

I would assume so, yes. We'd need to delete object in reverse order. Otherwise we may delete its parent and report a false positive that the object no longer exists (e.g. by deleting a ClusterRole before deleting a ClusterRoleBinding).

**Comment by bacongobbler** [comment]
Re-marking this as a feature; this has been a highly requested feature for some time. If someone from the community wishes to implement this, feel free.

**Comment by Bessonov** [comment]
Activity :/

**Comment by omerfsen** [comment]
Activity 👍

**Comment by arocki7** [comment]
Waiting for it.

**Comment by micktg** [comment]
Waiting for it as well

**Comment by bacongobbler** [comment]
In the interest of preventing spam to users subscribing to this thread, instead of commenting "+1" or "waiting for it", please add a :+1: to the OP or consider hitting the "subscribe" button on the top-right, under "Notifications". That way we can keep the conversation relevant to the discussion at hand. I've gone ahead and deleted those comments. Thanks!

**Comment by bacongobbler** [comment]
That being said, I'm interested to hear who from the community is willing to work on this feature. OP proposed this idea over three and a half years ago.

There has to be a point where we say the community has not taken enough initiative on this feature request, and we have to close it out as stale/unimplemented.

**Comment by Bessonov** [comment]
@bacongobbler I don't think that closing this issue is the right way to handle it. If you close it, you get new issues about this topic. Just remove the stale bot, then everyone get less spam. A bot against "+1" spammers would do better job.

**Comment by jerriais** [comment]
> Hi @bacongobbler
> I am working on this now.
> When I try to delete a deployment, I want to wait the pods controlled by the deployment until they all stop.
> However those pods don't appear in the big chart manifest, I have no idea which label or selector I can use.
> Any suggestions?

When I'm doing this manually I often find that even when all pods are gone some services are still being deleted `watch kubectl get svc`. Maybe it could work by checking to see if all services are gone, then the delete can be considered as complete...

**Comment by bacongobbler** [comment]
> I don't think that closing this issue is the right way to handle it. If you close it, you get new issues about this topic.

The Helm project receives about 3-4 new tickets per day. Nearly all of them are support issues or requests for clarification. The stale issue bot has been incredibly helpful to manage these issues, as many of them are either left open or fall off our radar, either because there's little engagement from the OP or the community on certain tickets. On the off chance that there is a ticket that needs to stay open, we can add "keep open" labels to the ticket.

We are very keen to review community contributions that are willing to take the time to implement this feature. But if the ticket goes stale due to 3 months of inactivity (and in this case, it's been left open for nearly 4 years), then it's clearly not a priority ticket item, or community members have found a workaround (as the OP demonstrated in his first comment).

**Comment by archerbj** [comment]
looking forward to seeing this

**Comment by Ornias1993** [comment]
> > I don't think that closing this issue is the right way to handle it. If you close it, you get new issues about this topic.
> 
> The Helm project receives about 3-4 new tickets per day. Nearly all of them are support issues or requests for clarification. The stale issue bot has been incredibly helpful to manage these issues, as many of them are either left open or fall off our radar, either because there's little engagement from the OP or the community on certain tickets. On the off chance that there is a ticket that needs to stay open, we can add "keep open" labels to the ticket.
> 
> We are very keen to review community contributions that are willing to take the time to implement this feature. But if the ticket goes stale due to 3 months of inactivity (and in this case, it's been left open for nearly 4 years), then it's clearly not a priority ticket item, or community members have found a workaround (as the OP demonstrated in his first comment) and there's little incentive to implement the requested feature.

Just because no one submits a fix, doesn't mean no one would willing to. It only means what it says on the tin: No one submitted a fix. 
Assuming willingness was the issue is a retorical mistake. It could just as well be simply the users having need for this issue, not being comfortable or knowlegable enough to fix it, them not having the time required to put into it, etc.

**Comment by ishaan-rd** [comment]
Any updates?

**Comment by eranelbaz** [comment]
Got this issue...
uninstalled helm chart but all the resources was still up...
I had to remove them using `kubectl` cli and search for all resources by hand...

**Comment by patsevanton** [comment]
I use werf - https://werf.io/
werf helm uninstall application
