### ISSUE TITLE
Proposal: chart values schema

### ISSUE THREAD

**Issue by berndtj** [helm/helm#2431]
The chart values are pretty free-form, which is nice as it presents a very low barrier to entry.  However, it would be nice if chart authors had a means to validate the values against a schema.  This proposal is to introduce an optional values.schema file into the charts.  The schema could be jsonschema or swagger/openapi (thought I think the former is a more natural fit).

I think this should be optional, but if present the computed (post merge) values would be checked against the schema for validity.  If invalid, the operation (install/update) should fail.

**Comment by technosophos** [comment]
I would love to see that functionality. We tried this with YAML annotations in the past, but that did not work. An optional JSON Schema, etc, might be nice.

**Comment by yuvipanda** [comment]
+1, it'd also make generating UIs for people to edit values easier, provide better error messages, etc.

**Comment by berndtj** [comment]
UI form generation and/or validation is certainly a use-case for this.

**Comment by bgrant0607** [comment]
+1 to JSON Schema

**Comment by bgrant0607** [comment]
Should this be a proposal rather than a feature?

**Comment by bacongobbler** [comment]
I think this can be both.

**Comment by eicnix** [comment]
Is somebody already working on this? Otherwise I would take a look at a PR for this.

My approach would be to allow users to provide a optional `values.schema` file that contains a JSON schema describing the values. If the `values.schema` file is present the values will be validated by tiller before the rendering process.

**Comment by jeff-knurek** [comment]
this would be nice. it'd also be cool if it could be tied in with the plugin that @rodcloutier talked about in his helm summit talk [Helm Journey at Ubisoft](https://www.youtube.com/watch?v=M2MmqN_nznI) _(of course, that plugin isn't open source/available yet)_

**Comment by berndtj** [comment]
I doubt anyone's started anything.  I know I haven't.  My original use-case was to create a catalog with UI (forms) which could be generated based on the JSON schema for simple one-click deployments.  My priorities have changed a bit.  I still think it's a good idea/feature especially for "production" charts.

**Comment by mattfarina** [comment]
This is part of the Helm 3 roadmap. See https://github.com/helm/community/blob/master/helm-v3/001-charts.md#schematized-values-files for more details.

**Comment by silesky** [comment]
my team has currently implemented a values-metadata.yml from scratch for helm charts (using our own custom validation schema) to create a dynamic catalog.  We are eager to migrate to a community-driven JSON schema solution.

**Comment by masaeedu** [comment]
Is there a way to introspect Go template/whatever templating language is being used in charts to find all the holes in the templates folder? I'd be fine with a separate schema file, but if it's voluntarily managed separately from the actual chart definition, well, people are lazy and things get out of sync.

**Comment by bacongobbler** [comment]
closed in #5350
