### ISSUE TITLE
.yml vs .yaml

### ISSUE THREAD

**Issue by jchauncey** [helm/helm#248]
So I noticed taht I had a manifest with `.yml` as the extension instead of `.yaml`. It was kind of confusing as to why it was never being installed. It would be helpful if we printed a warning or just accepted that extension as well.

**Comment by arschles** [comment]
+1 on accepting both

**Comment by technosophos** [comment]
Pretty sure there are only a few places where we do things like this:

https://github.com/helm/helm/blob/master/manifest/manifest.go#L38

So it would be really easy to accept either extension.

**Comment by arschles** [comment]
I'll take this one

**Comment by arschles** [comment]
Fixed by #306
