### ISSUE TITLE
Pass main chart name to sub-charts

### ISSUE THREAD

**Issue by rimusz** [helm/helm#2506]
There is no way to get main charts name to subchart, e.g. if you want to access from subchart deployment the main chart service.
For not to get around is only hardcoding main charts name as a global value:
```global:
  ## Main chart name
  mainChart: nginx
```

in subchart:
```'{{ .Release.Name }}-{{ .Values.global.mainChart }}-somename:123'```

**Comment by fibonacci1729** [comment]
@technosophos

**Comment by jascott1** [comment]
@rimusz I doubt it helps but have to point out that you can also use `--set` so its not as hard-coded. Im assuming you want the subchart to know parent chart's name so subchart can react dynamically somehow and want this to occur automatically so you can swap out parent charts without further action. If possible please share your use case and perhaps we can help figure out a solution.

**Comment by technosophos** [comment]
This was by design (following the principle that a subchart should only know what the parent explicitly passes in). I'd be okay with a workaround provided that the parent chart explicitly enables the pass-down (e.g. it is not automatic).

**Comment by johngmyers** [comment]
/remove-lifecycle rotten
/remove-lifecycle stale

In my use case, I have a subchart that defines a helm lifecycle hook that is common to multiple services. In order to perform its function (retrieving/constructing configuration for the service), it needs to know the name and version of the service that is using it. So I want it to know the .Chart.Name and .Chart.AppVersion of the chart that is invoking it.

(An additional wrinkle is that the lifecycle hook will be a subchart of a subchart of the service's chart.)

**Comment by johngmyers** [comment]
There is no --set option on "helm package", so the workaround isn't particularly effective.

**Comment by yann-soubeyrand** [comment]
According to this page https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/, one of the labels to use is app.kubernetes.io/part-of. This would be great if we could use something like {{ .Chart.Parent.Name }} to set the value of this label.

**Comment by blacksails** [comment]
Another approach could be to just expose the release chart name on the .Release variable. It is not as flexible as the parent approach, but it solves most of the usecases for when you want the chartname in labels.

**Comment by gp42** [comment]
Any news on that? need it exactly for the `app.kubernetes.io/part-of` label as mentioned above.

**Comment by mkjpryor-stfc** [comment]
+1

While in general I agree with the principle that the child chart should not know or care about the parent, IMHO having access to the parent chart name in order to set `app.kubernetes.io/part-of` is a case Helm should support.

Perhaps just the parent name and maybe version could be made available at `.Chart.Parent.{Name,Version}`?

**Comment by mkjpryor-stfc** [comment]
Then charts could include something like:

```
labels:
  {{- with .Chart.Parent }}
  app.kubernetes.io/part-of: {{ .Chart.Parent.Name }}
  {{- end }}
```

Maybe this could even go into the default template that is generated by the scaffold.

**Comment by mkjpryor-stfc** [comment]
I can also envisage cases where you might want to include the name of the parent chart in the `fullname` template.

**Comment by hickeyma** [comment]
@mkjpryor-stfc Would this be covered with #7477 ?

**Comment by mkjpryor-stfc** [comment]
@hickeyma 

I think the main difference is that what is proposed here would require zero configuration. Charts can assume that the information is either present at the standard location or not present at all.

#7477 covers the more general case of permitting child charts to access values from the parent, from what I can see.

I think it is important that this is something that is standardised. #7477 alone could allow something similar but would rely on charts adopting a convention that it is not guaranteed would be followed.

**Comment by hickeyma** [comment]
I think maybe allowing but not providing as a standard is what @technosophos suggested in https://github.com/helm/helm/issues/2506#issuecomment-307131659?

**Comment by mkjpryor-stfc** [comment]
@hickeyma @technosophos 

I would argue that in this particular case, we want to standardise as it allows for charts to be built in such a way that they can populate a recommended label (`app.kubernetes.io/part-of`) without further configuration.

See my previous comment:

> While in general I agree with the principle that the child chart should not know or care about the parent, IMHO having access to the parent chart name in order to set app.kubernetes.io/part-of is a case Helm should support.

**Comment by bacongobbler** [comment]
See https://github.com/helm/helm/pull/7477.

**Comment by bacongobbler** [comment]
As discussed earlier, implying values being passed from parent to sub-chart won't be accepted. #7477 is OK since it is explicitly passing down values, effectively ring-fencing what values are passed down and where.

As discussed earlier in the thread:

> I'd be okay with a workaround provided that the parent chart explicitly enables the pass-down (e.g. it is not automatic).
