### ISSUE TITLE
helm install https://.../.tgz -> "file not found"

### ISSUE THREAD

**Issue by rajivm** [helm/helm#2572]
This seems to be not working with both the install & upgrade commands since version 2.2.0 (it is working when I use 2.1.3, but when trying 2.2.0 or 2.4.2 it fails.

Specifically I'm doing:
`helm install https://www.example.com/some/folder/app-0.0.20.tgz`
and the result is:
`Error: file "https://www.example.com/some/folder/app-0.0.20.tgz" not found`

Trying to fetch the file otherwise (curl, etc.) works just fine and it works with helm 2.1.3.

**Comment by rajivm** [comment]
Found the issue... it looks like it will fail if `helm repo update` has never been run, even if there is no dependency on the repo cache. With debug:

```[debug] Created tunnel using local port: '59721'

[debug] SERVER: "localhost:59721"

[debug] Original chart version: ""
Error: no cached repo found. (try 'helm repo update'). open /Users/rajiv/.helm/repository/cache/stable-index.yaml: no such file or directory```

**Comment by fibonacci1729** [comment]
@rajivm sounds like you resolved this. Can I close this issue?

**Comment by rajivm** [comment]
@fibonacci1729 While I found a workaround, the error is still wrong. It probably should either: a) just work since its not relying on any helm repo, b) say that `helm init` / `helm repo update` must be run.

**Comment by bacongobbler** [comment]
Hi @danielnorberg! Would you mind explaining the issue you're hitting, what version etc? It's been a while since we've heard an update on this ticket so we should probably set a new baseline for triaging/debugging. Thanks!

**Comment by michelleN** [comment]
@glb thanks. Did you run that before a `helm repo update` or after?
@danielmbarlow What do you think the error should be in order to be more helpful?

**Comment by danielmbarlow** [comment]
I suspect that question was intended for @danielnorberg, @michelleN

**Comment by glb** [comment]
@michelleN I don't remember what I did then, but here's a trace from trying from scratch:
```
(minikube)
∴ rm -rf ~/.helm/

(minikube)
∴ helm install --debug --namespace fission --set serviceType=NodePort,routerServiceType=NodePort https://github.com/fission/fission/releases/download/0.10.0/fission-all-0.10.0.tgz
[debug] Created tunnel using local port: '55969'

[debug] SERVER: "127.0.0.1:55969"

[debug] Original chart version: ""
Error: Couldn't load repositories file (/Users/glb/.helm/repository/repositories.yaml).
You might need to run `helm init` (or `helm init --client-only` if tiller is already installed)

(minikube)
∴ helm init --client-only
Creating /Users/glb/.helm/repository 
Creating /Users/glb/.helm/repository/cache 
Creating /Users/glb/.helm/repository/local 
Creating /Users/glb/.helm/plugins 
Creating /Users/glb/.helm/starters 
Creating /Users/glb/.helm/repository/repositories.yaml 
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com 
Adding local repo with URL: http://127.0.0.1:8879/charts 
$HELM_HOME has been configured at /Users/glb/.helm.
Not installing Tiller due to 'client-only' flag having been set
Happy Helming!

(minikube)
∴ helm install --debug --namespace fission --set serviceType=NodePort,routerServiceType=NodePort https://github.com/fission/fission/releases/download/0.10.0/fission-all-0.10.0.tgz
[debug] Created tunnel using local port: '55977'

[debug] SERVER: "127.0.0.1:55977"

[debug] Original chart version: ""
[debug] Fetched https://github.com/fission/fission/releases/download/0.10.0/fission-all-0.10.0.tgz to /Users/glb/.helm/cache/archive/fission-all-0.10.0.tgz

[debug] CHART PATH: /Users/glb/.helm/cache/archive/fission-all-0.10.0.tgz
```

**Comment by bacongobbler** [comment]
closing as inactive. Please re-open if this continues to occur with more recent versions of Helm. Thanks.
