### ISSUE TITLE
Remove `-p` from `helm install`

### ISSUE THREAD

**Issue by technosophos** [helm/helm#259]
The `-p` flag is sorta outside of the normal workflow, and is known to cause problems with dependencies. It currently has a big batch of branching logic to handle the case right now, and it's easy to screw things up this way.

Is there any good reason to keep it around?

@gabrtv @arschles and I discussed, and I feel like we could comfortably get rid of this.

**Comment by gabrtv** [comment]
+1 on removing this.  The `AltInstall` stuff is a :snowflake: and not the pretty kind.  I also think that this will help drive resolution on #249, which has similar motivations.

**Comment by arschles** [comment]
:+1:

**Comment by technosophos** [comment]
Changed from proposal to enhancement.
