### ISSUE TITLE
Clarification request: should RepoFile permit duplicate Entry elements?

### ISSUE THREAD

**Issue by ljnelson** [helm/helm#2606]
(Steven Harris ( @seh ) requested that I create this issue after a discussion we had on Slack.)

While working on [microbean-helm][0], I wanted to understand how the `helm` command line tool works with chart repositories.  That led me into the Go code around processing (e.g.) `~/.helm/repository/repositories.yaml` and (e.g.) `~/.helm/repository/cache/stable-index.yaml`.

(I am not (yet!) a Go programmer.)

My understanding is that `pkg/repo/repo.go` contains the `RepoFile` type for representing the first one, and that `pkg/repo/chartrepo.go` contains the `ChartRepo` type for representing the second one.  Both of them use a type called `Entry`, if I'm reading right, to represent what looks like perhaps a union of information used to represent a "thing" in each file.  In the case of a `RepoFile` struct, `Entry` represents some information you need to talk to a chart repository and there are many of them (as you might expect).  In the case of a `ChartRepo`, `Entry` seems to represent kind of like its primary key, and there is only one of them.  (I don't know why `Entry` serves this double purpose but I wanted to list what I've learned in case it is helpful here.)

At any rate: it looks to me like `RepoFile` "has" an `Add` function that (deliberately?) allows you to add duplicate entries (so I guess this structure allows you to add a representation of a chart repository twice).  But then all usage that I can find in the codebase of `RepoFile` structs seems to key off an entry's name (i.e. it treats this `RepoFile` structure like a map in terms of its usage.

Is there a reason for permitting duplicates in a `RepoFile` struct?

[0]: https://microbean.github.io/microbean-helm

**Comment by ljnelson** [comment]
This [class diagram](https://lairdnelson.files.wordpress.com/2017/06/chartrepository.png) represents my attempt to make sense of the _concepts_ at work here; I hope it helps.

**Comment by thomastaylor312** [comment]
@technosophos Do you have an idea on this one? I am not quite sure

**Comment by bacongobbler** [comment]
Yes, it should allow duplicate entry elements with the same name. What it *should not* allow are duplicate entry elements with the same name **and** the same version.

I think this question is out of date now since type ChartRepo uses [type *Entry](https://github.com/kubernetes/helm/blob/c5c6e6375b5e9f475bd65309f74af89e430db6b9/pkg/repo/chartrepo.go#L46) whereas type IndexFile uses a type [map[string]ChartVersions](https://github.com/kubernetes/helm/blob/d4ccef7ba7752577c35d31eb330845d18273b7f5/pkg/repo/index.go#L81). Because it uses a map[string]ChartVersions, every name is guaranteed to be unique due to the inherent nature of a `map`.

Good question, @ljnelson.

**Comment by ljnelson** [comment]
Thanks for your input.  I think, perhaps, you misunderstood my question, or I asked it badly.

So: I understand that an `index.yaml` may have many entries in it, each of which refers unambiguously to a chart with a particular name and version.  For example, the stable one is here: kubernetes-charts.storage.googleapis.com/index.yaml  Indeed, there are several entries for `wordpress` at various versions.  I don't, I suppose, have a question about it.

What I am not sure about is: `repositories.yaml` apparently [can have fully duplicate entries in it](https://github.com/kubernetes/helm/blob/d4ccef7ba7752577c35d31eb330845d18273b7f5/pkg/repo/repo.go#L37), since it is merely an array of entries.  So I could, for example, have a `repositories.yaml` like this (note the two duplicate entries):
```
apiVersion: v1
generated: 2017-05-02T17:14:34.08505128-07:00
repositories:
- caFile: ""
  cache: stable-index.yaml
  certFile: ""
  keyFile: ""
  name: stable
  url: https://kubernetes-charts.storage.googleapis.com/
- caFile: ""
  cache: stable-index.yaml
  certFile: ""
  keyFile: ""
  name: stable
  url: https://kubernetes-charts.storage.googleapis.com/
```
…at least according to [the data structure](https://github.com/kubernetes/helm/blob/d4ccef7ba7752577c35d31eb330845d18273b7f5/pkg/repo/repo.go#L37).  My question was: is this deliberate?  Should the `repositories.yaml` above be flagged as invalid?

Thanks again for your time and for responding so courteously to this issue.

**Comment by bacongobbler** [comment]
From the pkg side yes, but from the [CLI side no](kubernetes-charts.storage.googleapis.com). This logic should be rolled into the package, though. :)

I'll re-open this as a good starter refactor if anyone wants to get their feet wet with `pkg/repo`. :)

**Comment by ljnelson** [comment]
Thanks.  For posterity, my takeaway is: **duplicate entries should not be permitted in a `repositories.yaml`** via any mechanism.  I'll double-check that I'm enforcing that in [microbean-helm](https://microbean.github.io/microbean-helm/apidocs/org/microbean/helm/chart/repository/ChartRepositoryRepository.html#fromYaml-java.io.InputStream-).

**Comment by bacongobbler** [comment]
Correct. :)

**Comment by bacongobbler** [comment]
closing as inactive.
