### ISSUE TITLE
Make CONTRIBUTING.md stand on its own

### ISSUE THREAD

**Issue by arschles** [helm/helm#265]
Right now it says that helm is part of Deis. Thinking it would be better to specify the contributing rules for Helm w/o linking back to Deis (even though the contribution rules are the same)

**Comment by bacongobbler** [comment]
The logic behind this was so we didn't have to maintain multiple identical files for contributing to any deis-related project. We would have one source of truth for contributions. I can see the idea behind this though.

**Comment by arschles** [comment]
@bacongobbler yea, I see the idea behind keeping the contribution rules all in one place as well. I'm ok either way for now, just wanted to keep this on the record

**Comment by technosophos** [comment]
Yeah, we should probably rewrite that file to be a little more generic, even if it's something like "we follow the guidelines set by..." and then point back to Deis
