### ISSUE TITLE
deletion completed with 1 error(s): object not found, skipping delete

### ISSUE THREAD

**Issue by whitecolor** [helm/helm#2656]
`heml delete release-name`

`Error: deletion completed with 1 error(s): object not found, skipping delete`

Actually seems to delete everything that was under this release, though it would be useful to get more precise error description.

**Comment by technosophos** [comment]
It happens if one of the things it tries to delete something that Kubernetes itself can't find. 90% of the time, this is because the resource is already deleted.

If anyone wants to see if they can improve the error text there, that would be good.

**Comment by yan234280533** [comment]
Can I have an try to analysis and solve this problem ?  I will synchronize the progress in this issue.

**Comment by jascott1** [comment]
@seh Is this really a bug? I think we would really need to reproduce in a bug way to be sure.

**Comment by seh** [comment]
I labeled it as such based solely on the description and not on any investigation into the Helm code, figuring that either Helm is misinterpreting the situation or could offer a different, less alarming message. Perhaps that's better termed an "enhancement," depending on how severe you consider @whitecolor's resulting confusion or annoyance to be.

**Comment by whitecolor** [comment]
It s not severe definitely I can assume what resource it is missing, but I would be more clear if helm could provide full info for the case.

**Comment by dihmuzikien** [comment]
Hi,
Has the issue been fixed yet?
If not, can I try to work on this as my first contribution? Also, I could use some guidance on what the expected behavior would be.

Thanks!

**Comment by soumyakantiroychowdhury** [comment]
I am seeing this issue in the following version:

```
$ helm version
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```
Here is the output:

```
$ helm delete littering-shark
Error: deletion completed with 1 error(s): release "littering-shark": object "" not found, skipping delete
```

Although from subsequent `helm ls` command I can see that the release is deleted, so are pods and services.

**Comment by vkukk** [comment]
Still happens
```
Client: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
```
```
$ helm delete vault 
Error: deletion completed with 2 error(s): release "vault": object "" not found, skipping delete; release "vault": object "" not found, skipping delete
```

**Comment by shark-horse** [comment]
Happened today for me as well:
```
$ helm version
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```

**Comment by bacongobbler** [comment]
As noted earlier, `helm delete` is attempting to delete an object that no longer exists, so the error reported here is correct and intentional. The behaviour to report an error is intended to inform the user to look into the error and make sure something else didn't occur (e.g. if there was an etcd leader split, causing data corruption).

This is working as intended. Closing.
