### ISSUE TITLE
Proposal: pluggable rulesets for helm lint

### ISSUE THREAD

**Issue by kyleschlosser** [helm/helm#2694]
Helm provides a built in linter, accessed through the `helm lint` command, which provides basic validation of the chart contents. 

In corporate and departmental scenarios, a team may want to augment the built in linting capabilities with their own linting rules, for example: 

service.type=ClusterIP --> Default service type must be ClusterIP if a service is defined
resources != nil --> resources limits and requests must be defined for all charts

To provide this capability, the existing plugin mechanism within Helm could be utilized, augmenting the plugin.yaml metadata attributes with indicators that a plugin contains linting rules: 

```
name: "mylinter"
...
linter: true
```

When the `helm lint` command is run, the internal lint rules would first be evaluated, followed by any lint plugins. The results of the internal linter and various plugins would be accumulated before being presented to the user. 

See issue #1495

**Comment by thomastaylor312** [comment]
@kyleschlosser Can you give an example of what this would look like? I think that would help solidify this a bit

**Comment by kyleschlosser** [comment]
My organization requires that the values.yml contain specific content. I suspect that not all organizations would want to enforce some of these rules, for example: 

- service.type=ClusterIP --> Default service type must be ClusterIP if a service is defined
- resources != nil --> resources limits and requests must be defined for all charts

Since Helm already has a plugin mechanism, perhaps linters could be accounted for within that framework rather than trying to find another way to plugin validation rules.

**Comment by thomastaylor312** [comment]
So the proposal is to flag a plugin as containing a linting plugin, and add the logic to helm to handle that properly, correct? Just want to make sure it is as clear as possible 🙂. Then we'll see if anyone has comments and I'll close the original issue

**Comment by kyleschlosser** [comment]
Yes, that's right. I have updated the opening comment to better reflect that.

**Comment by darrenhaken** [comment]
Has any work been done on this?

**Comment by Overbryd** [comment]
I am commenting here to not let this get stale or deleted.
This would help us in validating packages submitted in our CI.

I can image optional checks like would be pretty common, and could greatly enhance the value of `helm lint`:

```
# checks if a livenessProbe, readinessProbe is present and properly configured
--check=livenessProbe
--check=readinessProbe
# checks if resource requests (memory and cpu) are configured
--check=resources.requests
# checks if memory resource requests are configured
--check=resources.requests.memory
# checks if cpu resource limits are configured
--check=resources.limits.cpu
```

**Comment by k** [comment]
I would like to be able to use `.helm` extensions without the linter complaining to differentiate from standard yaml for our file validators.

**Comment by cabrinoob** [comment]
This feature would be very useful. I vote for it!

**Comment by bridgetkromhout** [comment]
Hi, all - many changes have been made to the linter since this issue was opened. If you have a remaining request, we now have a defined process so that if you'd like, you can submit a Helm Improvement Proposal so as to work in the community to make these ideas a reality: https://github.com/helm/community/blob/master/hips/hip-0001.md - meanwhile, I will close this issue. Thanks!

**Comment by jspiro** [comment]
+1 – I came looking specifically for a way to ensure certain resources exist, e.g. limits.
