### ISSUE TITLE
Proposal: Allow for custom metadata to be added to deployed helm release

### ISSUE THREAD

**Issue by groundnuty** [helm/helm#2734]
This is a feature proposal.

### Setup description:
A bare-metal k8s cluster shared by a group of developers used mainly for CI/CD workflow. Each developer has very (too) broad access rights (basically everyone is an admin).

We all share a single tiller instance. The deployments are done either by hand (`helm install`), or by our CI system which internally uses also `helm install`.

For the sake of isolation, each release deployment is deployed into its own namespace (current solution is that release_name=namespace).

#### Automatic release deletion
People tend to deploy things and forget to delete them. Writing a cron job that would delete all development releases everything seems too harsh (someone might want to work on the same release next day). It would be nice to be able to have a `helm tag` or `helm label` command that would add metadata to a release.

At the moment I realize this with:
~~~
kubectl -n kube-system label cm/develop.v1 delete=true
~~~
Ofc instead of *delete* there can be a *valid-until* with a date before each it should not be garbe collected. There is plenty of ideas here.

#### Setting release owner
Same story, this time a label would be `release-owner=<some user name>`. In this case, it would be beneficial to have this information in a table presented by `helm ls`. By extension `helm ls` would need to allow custom columns.

It this feature will be deemed worthy to add to helm, I'm willing to implement this myself as my first contribution to helm.

**Comment by jascott1** [comment]
Hi @groundnuty would you please prepend "proposal:" to the title of this issue?

**Comment by groundnuty** [comment]
*bumb* would hate for this Proposal to disappear :-)

**Comment by bacongobbler** [comment]
:)

**Comment by bacongobbler** [comment]
Something vaguely similar to this proposal would be https://github.com/kubernetes/helm/issues/3254 in the sense that if we go to a CRD model for v3.0, it would open up the opportunity to install charts with custom metadata to the release.

For the time being, `kubectl -n kube-system label cm/develop.v1 delete=true` sounds to be the right approach, though it'd be awesome to see a plugin to do this work as well. Alternatively, [a custom rudder implementation](https://github.com/kubernetes/helm/pull/2079) might be another solution for Helm 2.0 users.

**Comment by bacongobbler** [comment]
closing as inactive.

**Comment by invidian** [comment]
Why this got closed? I think this is still very valuable addition for helm.

**Comment by groundnuty** [comment]
@bacongobbler me and my usecae are I'm waiting for it since 2017! :-)

**Comment by bacongobbler** [comment]
> Why this got closed?

Because @groundnuty is exactly right. This feature request has been open for 3 years with no movement from the community. If someone really wanted this they would’ve written a pull request by now. Feel free to work on something if you’re feeling motivated.
