### ISSUE TITLE
refetch notes

### ISSUE THREAD

**Issue by kfox1111** [helm/helm#2742]
Notes for the chart often contains useful information that you may need to revisit. Unless the user knows to save the note output, it can be lost currently.

There should be a command such as:
helm notes <release name>

That will redisplay the notes for a given release.

**Comment by kfox1111** [comment]
@jascott1 Wish list item.

**Comment by danielhoherd** [comment]
> Unless the user knows to save the note output, it can be lost currently.

I think the situation is even worse than this. Today one of my co-workers installed a service and he saw the notes printed out. I went to interface with the service and there was no way I could see the notes.

I think the current state of affairs with not being able to recall the notes from the service install is almost like installing an application and outputting its man page into the terminal, then deleting the man page. The notes are often the short manual on how to use the service, and they are rendered with variables that are tedious to rediscover and fill in.

I looked for a `helm notes` equivalent and expected to find it, so I agree with @kfox1111 that it should be there.

**Comment by bacongobbler** [comment]
I believe all the information is available on tiller's end. It's just a matter of wiring that up with a new feature to the Helm CLI as well as a new RPC endpoint. If someone wants to take a crack at it, go for it!

**Comment by danielhoherd** [comment]
After a bit more digging I discovered that the notes are printed when you run `helm status <deploy-name>`, which solves my issue.

**Comment by adshmh** [comment]
I can submit a PR for this. But the release RPC endpoint already returns the whole Info struct, of which Notes is a member (via Status field):

https://github.com/kubernetes/helm/blob/b6660cd5c9a9ee35ff24034fcc223b7eaeed3ee2/pkg/tiller/release_status.go#L59-L63

Should I just reuse that in the new Helm CLI feature, i.e. helm notes, or add a new RPC endpoint? @bacongobbler would appreciate your advice on this.

**Comment by bacongobbler** [comment]
I think it's best to re-use existing RPC endpoints where possible :)

It's been a while since I've dug into the code, but if I recall we should be able to re-use all of `helm status`'s RPC endpoints, just returning the Notes struct from the release Info object.
