### ISSUE TITLE
Prosed changes to Helm governance

### ISSUE THREAD

**Issue by technosophos** [helm/helm#2792]
Helm is a few years old now. Currently, the governance structure of Helm is very flat ("core maintainer" is the only official role). This is great for voting and other official decision making, but it does not lend well to explaining or ascribing responsibilities. So this document is an attempt to fix that.

## tl;dr

There are two official categories of Helm leadership: Project Maintainers and Architecture Maintainers. Each has a designated communicator (Project Manager, Release Manager). All maintainers have equal votes in voting process, but the expectations and requirements for each group are slightly different.

## A Project / Architecture Distinction

Among the existing maintainers, there is already a clear distinction of interest: Some are primarily interested in the Helm project as a whole, and ensuring that it blends well with the Kubernetes ecosystem. Some are focused on the actual code of the Helm project. The proposal at hand is that this distinction should become formal.

We should divide maintainer responsibilities into two categories: Project Maintainer and Architecture Maintainer.

### Common responsibilities

The following responsibilities are common to all maintainers  ([source](https://gist.github.com/technosophos/c269362e154540b4bfc3bb2ac210df41)):

- Positively represent Helm, Tiller, and Charts
- Hang out in the #helm-dev and #helm-users Slack channel
- Make a good-faith effort to come to the public developer's meeting
- Participate in formal Helm decision making, such as casting an official vote for new maintainers
- Uphold the Code of Conduct (that is, not just follow, but cultivate that as part of the project's culture)

### Project Maintainers

The project maintainers are primarily concerned with Helm's interface to the rest of the Kubernetes world, not in the support sense (though we of course participate in that) but in the directoral sense.

The project maintainers' responsibilities are:

- Set and track the release roadmap
- Facilitate/represent the needs of the Kubernetes Chart team
- Act as "project management" for release cycles
- Communicate upstream to the Kubernetes governance
- Manage the `kubernetes-helm` org
- Perform the champion role for projects working through the Helm incubator

### Architecture Maintainers

Architecture maintainers are "close to the code" in the sense that they are responsible for currating the Helm codebase and its related aspects.

Architecture maintainers as a whole have the following responsibilities.

- Participate in resolution of critical security issues as needed
- Review PRs
- Participate in bug resolution
- Comment on proposals and issues as appropriate
- Produce releases

## The Roles of Project Manager and Release Manager

Out of this division, it seems sensible to give each group a designated spokesperson.

### Project Manager

The project manager represents the project maintainers. This person's role is to make sure that a roadmap is created and updated, and that the current release candidate's target matches the roadmap.

- Currate the roadmap
- Present roadmap updates regularly in SIG-Apps and the Helm Public Dev meeting
- Communicate "upstream" for the project (e.g. to the Kubernetes governance board

### Release Manager

The release manager's role is to move the codebase forward. This is the individual who will typically make the final call on whether a release is ready to go.

- Make the call on releases
- Be the voice of SemVer compliance and other forms of code cleanliness
- Be the Helm "subject matter expert"
- Tie-breaker on difficult technical decisions

## Starting Lineup

The Helm project already has a strong set of core maintainers, and it can be a delicate matter to divide a team. But to ease the initial transition, this proposal includes an initial lineup for the two maintainer categories (order is unimportant):

| Project Maintainers | Architecture Maintainers |
| ---- | ---- |
| Manager (_temporary_): technosophos | Manager: adamreese  |
| ---- | ---- |
 | vaikas-google  | seh |
 | viglesiasce | fibonacci1729 |
 | prydonius | jascott1 |
 | migmartri | michelleN |
 |  | thomastaylor312 |
 | | bacongobbler |
| | nebril |

Ideally, the project manager role could be transitioned to an experienced project manager with sufficient time to perform the required duties.

## Adding, Removing Maintainers

This makes only one change to the process for adding, removing, or stepping down from maintainership positions.

_At nomination time, an individual should be nominated into one of those two categories, and that will be made clear during voting._

**Comment by cblecker** [comment]
It may also be advisable to review how the helm governance structure (both current and proposed) fits into the larger Kubernetes organization and structure (what kind of oversight does sig-apps provide, helm contributors becoming k8s org members, etc). Maybe there are pieces that you want to adopt from k8s, and parts you want to call out as opting out of.

**Comment by thomastaylor312** [comment]
I really like this and am fully supportive of it. I agree with @cblecker that it is probably a good idea to see what we can adopt from the larger Kubernetes community before giving this the final go ahead. Probably a good topic for the developer meeting

**Comment by thomastaylor312** [comment]
@technosophos Have we accepted and gone ahead with this or do we still need to do some discussion?

**Comment by technosophos** [comment]
I think we just need to transition this into the documentation somewhere. I am hoping that @SlickNik will join me on the PM side of the house.

**Comment by SlickNik** [comment]
@technosophos -- Definitely. More than happy to join you and help with the PM side of things! Also +1 on this proposal as it is defined here. 👍

**Comment by thomastaylor312** [comment]
@technosophos @SlickNik was this going to be turned into documentation?

**Comment by cblecker** [comment]
probably not rotten :)
/remove-lifecycle rotten

**Comment by bridgetkromhout** [comment]
Hi @technosophos - looks like https://github.com/helm/community/blob/master/governance/governance.md has plenty of documentation now - is there more to do, or can this issue be resolved? Thanks.

**Comment by technosophos** [comment]
I believe this is not completely superseded by existing documentation. So I am closing. Thanks for the ping.
