### ISSUE TITLE
cache path in $HELM_HOME/repository/repository.yaml is hardcoded

### ISSUE THREAD

**Issue by bacongobbler** [helm/helm#2839]
As a user, when I run `mv $HELM_HOME /tmp/helm; export HELM_HOME=/tmp/helm`, all Helm commands should work as expected.

This currently does not work as expected because the cache path in `$HELM_HOME/repository/repositories.yaml` contains absolute paths to cache indexes, which is loaded during [`repo.LoadRepositoriesFile()`](https://github.com/kubernetes/helm/blob/a2323f8658b29dedc8485020730556793f5d14e0/pkg/repo/repo.go#L56-L66), used in commands like `helm repo update`.

```
><> cat /tmp/helm/repository/repositories.yaml 
apiVersion: v1
generated: 2017-05-12T17:12:36.856307157-07:00
repositories:
- caFile: ""
  cache: /Users/bacongobbler/.helm/repository/cache/stable-index.yaml
  certFile: ""
  keyFile: ""
  name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- caFile: ""
  cache: /Users/bacongobbler/.helm/repository/cache/deis-index.yaml
  certFile: ""
  keyFile: ""
  name: deis
  url: https://charts.deis.com/workflow
- caFile: ""
  cache: /Users/bacongobbler/.helm/repository/cache/incubator-index.yaml
  certFile: ""
  keyFile: ""
  name: incubator
  url: https://kubernetes-charts-incubator.storage.googleapis.com/
```

This file is written out during `helm init`, which is why when I `mv $HELM_HOME` to another directory, some repo commands may fail.

This issue was found while debugging #2837. Some more context can be found there.

**Comment by rprobotics** [comment]
It looks like Home() in /usr/local/opt/go/src/k8s.io/helm/pkg/helm/helmpath/helmhome.go uses $HOME to create the cache path.

**Comment by rprobotics** [comment]
Would it make sense to hard code $HELM_HOME into this repositories.yaml file, and use os.ExpandEnv() whenever evaluating from this file?

**Comment by bacongobbler** [comment]
In other files we [use relative references to files](https://github.com/kubernetes/helm/blob/a2323f8658b29dedc8485020730556793f5d14e0/pkg/repo/chartrepo.go#L129-L138) and add $HELM_HOME on-the-fly. Given there is already precedent for this, we should continue to follow that precedent.

**Comment by rprobotics** [comment]
If this is a low-priority issue, and can be done by somebody new to the Helm sources than you can assign to me. I have already been looking into it, and finished a quick hack to get it working. But my changes used os.ExpandEnv()

I think this would be a good bug for me to get familiar with Helm source code.

**Comment by bacongobbler** [comment]
Please feel free to take this on! Yes, this should be a relatively simple fix, I would imagine.

**Comment by rprobotics** [comment]
Cool. I'll continue working on this for the next few days. Not sure how much time I can dedicate to it just yet, but I'll make sure to keep this thread updated and use it for any questions.

**Comment by rprobotics** [comment]
@bacongobbler Do you have a repo I can test 'local' with? 

To test I've been running:
helm repo add test https://kubernetes-charts.storage.googleapis.com 
and
helm repo add stable https://kubernetes-charts.storage.googleapis.com

These both work. But when I try to use that URL with 'local' it fails. I'm going to go ahead and open the pull request since my initial tests passed.

**Comment by rprobotics** [comment]
PR: https://github.com/kubernetes/helm/pull/2862

**Comment by rprobotics** [comment]
Looks like CircleCI failed because of a timeout? Doesn't look related to my changes

**Comment by bacongobbler** [comment]
Fixed in Helm 3 as it now follows the XDG base directory specification.

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
