### ISSUE TITLE
Proposal: Add istio-inject flag 

### ISSUE THREAD

**Issue by rprobotics** [helm/helm#2878]
This is a proposal to add an extra flag (istio-inject) to Helm that will basically do what istioctl's 'kube-inject' does. The goal will be to inject any necessary istio parameters to the resulting YAML files Helm produces while still maintaining the benefits from Helm. 

The kube-inject code can be taken from the istio project and ported to Helm. We would probably want to work with istio maintainers to make sure the two are kept in sync.

@thomastaylor312

**Comment by thomastaylor312** [comment]
@rprobotics Do you know if the istio cube-inject code is in a library we could import and use?

**Comment by jrnt30** [comment]
There is actually work being done already with Istio to have a [Dynamic Admission Controller](https://kubernetes.io/docs/admin/extensible-admission-controllers/) which would provide this out of band of Helm, which I think would probably be a bit more robust. 

Essentially https://github.com/istio/pilot/issues/335 is the Epic covering the tasks, but the Istio/pilot now contains the start of this implementation.

**Comment by seh** [comment]
I don't think this should be part of Helm itself. A plugin would be more palatable.

**Comment by rprobotics** [comment]
Does anybody know the ETA on the Dynamic Admission Controllers? That project seems like it'll be more long-term sustainable than the quick-fix I suggested. If the project is still months away than it might make sense to develop the plugin as @seh suggested.

**Comment by thomastaylor312** [comment]
I think a plugin would be the best way to start. You could track the admission controller and then deprecate the plugin

**Comment by jrnt30** [comment]
Are plugins now able to inject themselves in the actual provisioning pipeline?  When we had looked at this before, part of the problem was that Plugins weren't able to change the actual manifests of the resources being created.

**Comment by bacongobbler** [comment]
Tiller has a concept known as release modules (like rudder). See https://github.com/kubernetes/helm/issues/1924 for some background context

**Comment by so0k** [comment]
for anyone interested, k8s 1.7.3 > required for automatic Istio sidecar injection 
https://istio.io/docs/setup/kubernetes/sidecar-injection.html#automatic-sidecar-injection

/close

**Comment by briansmith** [comment]
I don't think there should be a `<service-mesh-platform>-inject` flag per service mesh platform. It would be better if the mechanism were flexible enough to support [linkerd](https://github.com/linkerd/linkerd) and [Conduit](https://github.com/runconduit/conduit) and other things as well.

**Comment by maorfr** [comment]
Hi,

how about this plugin?
https://github.com/maorfr/helm-inject

**Comment by maorfr** [comment]
@bacongobbler I think this issue can be closed :)
