### ISSUE TITLE
tiller api return coded error

### ISSUE THREAD

**Issue by weiwei04** [helm/helm#2894]
use  [grpc status](https://github.com/grpc/grpc-go/blob/master/status/status.go) to return coded error for tiller grpc api

like we can change error define in [release_server.go](https://github.com/kubernetes/helm/blob/master/pkg/tiller/release_server.go)
```golang
var (
	// errMissingChart indicates that a chart was not provided.
	errMissingChart = errors.New("no chart provided")
        ...
)
```

into

```golang
import (
       "google.golang.org/grpc/status"
       "google.golang.org/grpc/codes"
)
    
var (
       errMissingChart = status.Errorf(codes.NotFound, "chart not found")
       ...
)
```

and the tiller client side can process the coded error like
```golang

resp, err := client.GetReleaseContent(ctx, req)
if err != nil {
    if s, ok := status.FromError(); ok {
        // check s.Code()  
    }
}

```
this won't change the current tiller grpc api, but will return a coded error for client program to process.

I can open a pr to change the related tiller error into grpc status.Status error.

@technosophos  what do you think?

**Comment by technosophos** [comment]
This would not require existing clients to change code at all, right?

If no changes are required for existing clients, I like this change.

**Comment by weiwei04** [comment]
Yes, this would not require existing clients to change code.

1. For helm cmd, the existing clients would not need to change, since the current tiller grpc api return a normal golang error, and the grpc.Status satisfy the Error interface can be used as a error.

2. For other developers, who may use tiller grpc api directly, I am not sure if they check the error like
```golang
resp, err := client.GetReleaseContent(ctx, req)
if err != nil && strings.HasPrefix(err.Error(), "invalid release name") {
    ...
}
```
for this kind of usage, the err.Error() is not stable by itself, I think there's no need to be compatible with this kind of usage.

**Comment by bridgetkromhout** [comment]
As per @bacongobbler's comment in https://github.com/helm/helm/pull/2900#issuecomment-536683461, we are no longer adding new features to Helm 2, and Tiller is no longer present in Helm 3. Thank you for your issue; I am closing it at this time.
