### ISSUE TITLE
Helm needs to handle PodDisruptionBudget updates

### ISSUE THREAD

**Issue by egeland** [helm/helm#2914]
If a chart includes a PDB, and a value in this is changed, helm errors out with
```
Error: UPGRADE FAILED: PodDisruptionBudget.policy "example-app-pdb" is invalid: spec: Forbidden: updates to poddisruptionbudget spec are forbidden.
```

If updates are not allowed, helm should delete and replace the object, IMO.

Tested on helm `2.5.1` - will test on latest to confirm behaviour there.

**Comment by jascott1** [comment]
Hi @egeland 
Can you confirm you tried the `--force` command?
```
--force                force resource update through delete/recreate if needed
```

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

**Comment by pjelar** [comment]
@bacongobbler I'm hit with the same issue using 2.8.0.

```
helm upgrade consul -f /app/config/infr/consul/values.yaml stable/consul --namespace=vault --force
Error: UPGRADE FAILED: no PodDisruptionBudget with the name "consul-consul-pdb" found
```

**Comment by djsd123** [comment]
I can confirm that this is very much still an issue. 

`Error: UPGRADE FAILED: no PodDisruptionBudget with the name "cluster-logging-fluentd" found`

I can also confirm that performing a `helm del <CHART> --purge` and then redeploying from the chart works around this.

```
➜  ~ helm version
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
```

**Comment by akboyd88** [comment]
I'm also able to reproduce this:

helm version
Client: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}

**Comment by ChrisCooney** [comment]
I have seen this exact behaviour too. It's preventing us from ensuring availability during node maintenance.

**Comment by cablespaghetti** [comment]
Same issue. Only occurs occasionally (v2.12.3). I'll add force to all my scripts and see if it goes away.

**Comment by mlushpenko** [comment]
Also for me:
```
kubectl get pdb referral                                                                                                                                                              10:29:50
NAME       MIN AVAILABLE   MAX UNAVAILABLE   ALLOWED DISRUPTIONS   AGE
referral   N/A             1                 0                     2d
```

but at the same time, helm reports:
```
no PodDisruptionBudget with the name "referral" found
```

```
helm version                                                                                                                                                                          10:31:18
Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
```

**Comment by mlushpenko** [comment]
I tried deleting manually pdb resource and deployment itself, but then got :
```
UPGRADE FAILED
ROLLING BACK
Error: no Service with the name "referral" found
```
what worked for me is rolling back to the latest successful deployment and then trying deployment again. So I have suspicion helm in some way couldn't handle history of failed deployments as on fail it was rolling back to another failed release (I was using `--atomic` option).

Perhaps `--atomic` should rollback to the latest successful deployment?

**Comment by bacongobbler** [comment]
Rolling this ticket into https://github.com/helm/helm/issues/7082 to keep the conversation all in one plare RE: recreating objects on an upgrade. Thanks.

**Comment by patiltejasg** [comment]
Hi there,
I'm trying k8s version update from 1.21.7 to 1.22.6 in my AKS cluster. Its provisioning status is failing after repeated attempts due to pdb for ingress deployment which is done through helm chart. 

I deleted current pdb deployment and ran a new pdb with Allowed disruption: 1 (earlier it was 0) but it didnt got applied and rolled back to the earlier values (Allowed disruption: 0) 

 Kindly guide/suggest a way to overcome this issue ASAP.
Will appreciate your inputs.

Thanks in advance !!
