### ISSUE TITLE
watch closed before Until timeout

### ISSUE THREAD

**Issue by scd-systems** [helm/helm#2918]
Hi,
we got reproducable error messages from tiller/helm during helm install process of a job chart. The job it self gets finished successfully in kubernetes, but helm/tiller dies with the error message from above.

Tiller log:
>09:16:35[tiller] 2017/09/08 07:16:35 preparing install for jobx
 09:16:35[storage] 2017/09/08 07:16:35 getting release history for "jobx" 
09:16:35[tiller] 2017/09/08 07:16:35 rendering postinstall chart using values
 09:16:352017/09/08 07:16:35 info: manifest "postinstall/templates/configure-storage-nfs.yaml" is empty. Skipping. 
09:16:35[tiller] 2017/09/08 07:16:35 performing install for jobx 
09:16:35[tiller] 2017/09/08 07:16:35 executing 5 pre-install hooks for jobx
 09:16:35[kube] 2017/09/08 07:16:35 building resources from manifest 
09:16:35[kube] 2017/09/08 07:16:35 creating 1 resource(s) 
09:16:35[kube] 2017/09/08 07:16:35 Watching for changes to Job configure-buckets with timeout of 5m0s 
09:16:35[kube] 2017/09/08 07:16:35 Add/Modify event for configure-buckets: ADDED
 09:16:35[kube] 2017/09/08 07:16:35 configure-buckets: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
 09:17:06[tiller] 2017/09/08 07:17:06 warning: Release jobx pre-install postinstall/templates/couchbase-buckets.yaml could not complete: watch closed before Until timeout
 09:17:06[tiller] 2017/09/08 07:17:06 failed install perform step: watch closed before Until timeout

kube-apiserver reports very often:
>09:16:03 E0908 07:16:03.467638 1 watch.go:228] unable to encode watch object: write tcp 10.42.188.75:6443->10.42.51.83:36618: write: connection reset by peer (&streaming.encoder{writer:(*framer.lengthDelimitedFrameWriter)(0xc4206ebbc0), encoder:(*versioning.codec)(0xc425b55b90), buf:(*bytes.Buffer)(0xc421a29ea0)}) 
09:16:03 E0908 07:16:03.467674 1 watch.go:228] unable to encode watch object: write tcp 10.42.188.75:6443->10.42.51.83:36618: write: connection reset by peer (&streaming.encoder{writer:(*framer.lengthDelimitedFrameWriter)(0xc4217c2760), encoder:(*versioning.codec)(0xc422ce5050), buf:(*bytes.Buffer)(0xc421962230)})

Tiller version: 2.6.1

helm version:
Client: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}
 Server: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}

Docker version:  1.12.6
Operating system: 1465.6.0
Kubernetes: 1.7.4 (also tested 1.6.6 and 1.7.2 with the same results)

Howto Reproduce: 
>  helm install --tiller-namespace anyname -n jobx -f values.yaml --namespace anyname jobs/

Error: watch closed before Until timeout

**Comment by bacongobbler** [comment]
According to [some unit tests](https://github.com/kubernetes/helm/blob/099790a00c699951aff866464fca8fec9bab4b96/pkg/kube/client_test.go#L428-L438), this appears to happen when the pod goes into a PodUnknown state. Can you confirm the state of your pods in the cluster?

**Comment by scd-systems** [comment]
Hi @bacongobbler, 

I cannot confirm, Kubernetes reports always "PodCompleted".
The job and pod finish successful, but tiller stop working with "watch closed" error.

Regards,

**Comment by scd-systems** [comment]
Hi @bacongobbler ,

Short update:

When we start tiller local and set environment variable HELM_HOST=localhost:<TILLERPORT> then we got helm install running without "watch closed" errors.
But this workaround is not acceptable for production area.

Regards,

**Comment by bacongobbler** [comment]
I'm not familiar/aware what exactly would cause this issue. Can you please tell us how you deployed kubernetes (what cloud provider, or a link to documentation if on bare metal) as well as from what machine you are running `helm` from?

That way, we can try to stand up a similar kubernetes cluster to try and reproduce the issue. We have never hit a similar bug before in our production clusters on Azure Container Services.

**Comment by scd-systems** [comment]
Hi @bacongobbler ,

we deploy Kubernetes cluster via Rancher Server (rancher.com).
The underlaying OS from rancher server and the agents are CoreOS.
Kubernetes cluster it self runs inside of docker containers.
The "CloudProvider" is rancher and the underlaying hypervisor infrastructure is based on vSphere.

We already tried Rancher 1.6.6 up to 1.6.9 with Kubernetes versions 1.6.6, 1.7.2, 1.7.4 and always got the same results with helm/tiller.

Regards,

**Comment by scd-systems** [comment]
Hi @bacongobbler,

It seems that the watch close is related to the helm hooks.
I tried chart without the pre-install hook from the chart file, and helm did the job.

Our helm chart:

Chart.yaml:
`apiVersion: v1
description: jobx
name: jobs
version: 1.0.0`

values.yaml
`replicaCount: 1
resources:
  requests:
    memory: 50Mi
    cpu: 200m
  limits:
    memory: 300Mi
    cpu: 300m`

templates/jobx.yaml
`
apiVersion: batch/v1
kind: Job
metadata:
  name: jobx
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": "pre-install"
spec:
  template:
    metadata:
      name: jobx
    spec:
      initContainers:
      - name: init-waitforetcd
        image: "{{ .Values.global.etcdctl.image.repository }}:{{ .Values.global.etcdctl.image.tag }}"
        command: ['sh', '-c', 'until wget --spider --timeout=1 etcd:2379/v2/keys; do echo .; sleep 1; done;']
      containers:
      - name: jobx
        image: "{{ .Values.global.jobs.image.repository }}:{{ .Values.global.jobs.image.tag }}"
        imagePullPolicy: {{ .Values.global.jobs.image.pullPolicy }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
        command: ["/bin/sh", "-c", "/job.sh"]
      restartPolicy: Never
`

You can try out the chart by run the containers with just run a shell (example image: centos/7)
It does not matter which command or image used. It always fail with watch close error.


Regards,

**Comment by djhaskin987** [comment]
I too ran into this issue. My chart has hooks as well. In addition, maybe this has to do with upstream? https://github.com/kubernetes/kubernetes/issues/31345

**Comment by bacongobbler** [comment]
Which version of draft are you running? Pretty sure the watch flag hasn’t worked for a few releases ever since the UX update in 0.5. :)

**Comment by djhaskin987** [comment]
I don't use draft. Just helm.

**Comment by bacongobbler** [comment]
Oh I'm terribly sorry. I was context switching and thought this was the draft issue queue. My bad!

**Comment by djhaskin987** [comment]
The error is generated by this line in kubernetes: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/watch/until.go#L68

The function, "Until", is commented about thusly:

> // Until reads items from the watch until each provided condition succeeds, and then returns the last watch
> // encountered. The first condition that returns an error terminates the watch (and the event is also returned).
> // If no event has been received, the returned event will be nil.
> // Conditions are satisfied sequentially so as to provide a useful primitive for higher level composition.
> // A zero timeout means to wait forever.

I betcha *anything* this is a network issue, looking at the line of code. 

I think this error means "The connection was dropped before I could tell what happened".

I have been getting intermittent connection drops as well as this error (like actual tcp error messages in addition to this one coming out of helm).

**Comment by djhaskin987** [comment]
Some further conjecture.

I keep seeing either 

`Error: Get https://10.43.0.1:443/apis: read tcp 10.42.77.177:39960->10.43.0.1:443: read: connection reset by peer`

or

`watch closed before Until timeout`

I think these are the same error. I think after further review that a firewall rule we have resets connections after 60 seconds as part of a reload.

**Comment by djhaskin987** [comment]
So therefore, I think what's happening is that both mssages above are essentially dropped connections to the kubernetes API. when these connections are dropped, helm marks the deploy as failed, instead of retrying. Is this intentional? Is there anyway for helm to deal with dropped connections and make progress in the face of them?

**Comment by viroos** [comment]
I have  the same error:
helm init --tiller-image gcr.io/kubernetes-helm/tiller:v2.7.2
kubectl rollout status deployment/tiller-deploy --namespace kube-system --watch=true"
Waiting for deployment spec update to be observed...
Waiting for deployment spec update to be observed...
Waiting for rollout to finish: 0 out of 1 new replicas have been updated...
Waiting for rollout to finish: 0 of 1 updated replicas are available...
error: watch closed before Until timeout

/remove-lifecycle rotten

**Comment by kaikun213** [comment]
I got the same issue via GitLab auto-devops.

```
Waiting for rollout to finish: 0 of 1 updated replicas are available...
error: watch closed before Until timeout
ERROR: Job failed: exit code 1
```

**Comment by sstarcher** [comment]
Just got the same issue with a very long --timeout setting

**Comment by jkattmann** [comment]
I got the same issue on a freshly deployed 1.10.6 AKS cluster using helm to deploy the stable/influxdb chart with the hook for post-install job https://github.com/helm/charts/blob/master/stable/influxdb/templates/post-install-set-auth.yaml

```
helm install stable/influxdb --values "C:\Users\JoelK\Desktop\influxValues.yaml" --name influx --namespace citadel --debug
[debug] Created tunnel using local port: '52467'

[debug] SERVER: "127.0.0.1:52467"

[debug] Original chart version: ""
[debug] Fetched stable/influxdb to C:\Users\JoelK\.helm\cache\archive\influxdb-0.10.0.tgz

[debug] CHART PATH: C:\Users\JoelK\.helm\cache\archive\influxdb-0.10.0.tgz

Error: watch closed before Until timeout
C:\Users\JoelK\Desktop\test\blueprints\k8s
λ  helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

Any updates on this?

**Comment by strtdusty** [comment]
I see the same issue on 1.10.3 AKS cluster using helm to uninstall heptio-ark.

**Comment by gurvindersingh** [comment]
I think the issue is with AKS as I am also having similar issue with AKS in westeurope region (1.10.6 k8s version)

**Comment by gaieges** [comment]
Just stumbled on the same thing, although I can't reproduce it reliably, it pops up during the `helm test` phase after a new install during a deploy, and breaks the deploy(`helm install`, `helm test`, if fail: `helm rollback`).  

I use AKS as well.

I **think** this might be relevant?:

```
Today 2:00:51 PM tiller-deploy-759cb9df9-w4xcf tiller [Error] 2018/08/23 19:00:51 Error getting status for pod simplecurl-tests: pod not found
```

**Comment by paulgmiller** [comment]
Seems kubectl is trying to fix this in 1.12 with this PR https://github.com/kubernetes/kubernetes/pull/67817/files
@tnozicka 
Maybe Helm should follow the same practice?

**Comment by jonathanjfshaw** [comment]
This is definitely an AKS issue:
https://github.com/Azure/AKS/issues/676

**Comment by viroos** [comment]
>This is definitely an AKS issue:
>Azure/AKS#676

My issue was on Tectonic

**Comment by BobLamarley** [comment]
> I got the same issue via GitLab auto-devops.
> 
> ```
> Waiting for rollout to finish: 0 of 1 updated replicas are available...
> error: watch closed before Until timeout
> ERROR: Job failed: exit code 1
> ```

I'm facing the same issue as you, i'm using a k8s cluster on DigitalOcean and i'm using autoDevOps on gitLab :)
Do you resolve your issue ?
Here is my gitLab console : 
![image](https://user-images.githubusercontent.com/7857364/52281063-8d402780-295d-11e9-8811-c2a2c5c5ac84.png)
Here is what i got when i'm checking pods on my k8s 
![image](https://user-images.githubusercontent.com/7857364/52281114-af39aa00-295d-11e9-837e-203853b34cfd.png)

**Comment by tnozicka** [comment]
If this is using the `kubectl rollout status` command, I've fixed it in k8s 1.12. If it was using `Until` (`UntilWithoutRetry`) it should switch to `UntilWithSync`.

**Comment by BobLamarley** [comment]
I'm in 1.13 for both k8s client and server according to my screenshot :)

**Comment by tnozicka** [comment]
no downgrade, it's in every release since k8s 1.12 (https://github.com/kubernetes/kubernetes/pull/67817/commits/77932116693a81198f919d7f5fe77bf3e6a91a27) - btw. its' client side fix so maybe helm is vendoring the old client?

**Comment by BobLamarley** [comment]
Mmmh there is something i don't get it
I used the GitLab interface in order to install Helm on my kubernetes, and Helm seems to be installed : 
![image](https://user-images.githubusercontent.com/7857364/52403812-eaf08300-2ac7-11e9-933b-2271d82e69e6.png)
But when i check via command line, there is no helm : 
![image](https://user-images.githubusercontent.com/7857364/52404132-9568a600-2ac8-11e9-93c2-b257d5924b96.png)
I think there is a relation with RBAC rules and the ServiceAccount i was force of bind with a ClusterRoleBinding, and maybe i have to use this ServiceAccount i have created to see helm ? ^^
But for answering to your last post, how can i check if helm is vendoring the old client ? :)

**Comment by jonathanjfshaw** [comment]
Helm is not an argument for the kubectl command.
Run kubectl --kubeconfig=... first in order to intitalise the credentials
using the kubectl app.
Then Helm version to run the Helm app.

**Comment by BobLamarley** [comment]
I put my k8s-crypthome-kubeconfig.yaml at $HOME/.kube in order to not have to pass my credentials everytime.
I if type `kubectl`, am i supposed to stay inside my K8s CLI ? it seems strange to me what you tell me ^^

**Comment by jonathanjfshaw** [comment]
Helm is a separate CLI tool.

>

**Comment by BobLamarley** [comment]
Ah, my bad, thanks for the info, it works better ^^
![image](https://user-images.githubusercontent.com/7857364/52422633-b9db7700-2af6-11e9-929e-ed9c8cbf5eae.png)
But unfortunately, i'm still stuck on my issue :'(

**Comment by sachinmuralig** [comment]
I'm having this same issue with Helm Test : https://stackoverflow.com/questions/54806918/helm-test-fails-with-error-watch-closed-before-untilwithoutretry-timeout?noredirect=1

**Comment by arocki7** [comment]
I have the same issue with longer jobs.

**Comment by arocki7** [comment]
If we use a load balancer, please check the timeout. You might want to increase the timeout value.

**Comment by BobLamarley** [comment]
I use a loadbalancer between 3 nodes but it's a kubernetes cluster set up and managed by DigitalOcean so i don't know how to check and modify this value, i will do some research :)
But i'm trying to deploy a little app with jobs relatively short, done via gitlab AutoDevOps, seems strange ...

**Comment by arocki7** [comment]
@BobLamarley You might want to just check with DigitalOcean Support. They could modify this setting for you. Usually, The idle timeout setting will be around 60 seconds. So, you are likely to have a problem when you have to watch running for more than 60 seconds.

**Comment by maciej-sawicki-codilime** [comment]
@arocki7 it would better if it was fixed in Tiller. Long long polling may not be the best idea.

**Comment by arocki7** [comment]
@maciej-sawicki-codilime It has been fixed in Kubernetes v1.12.

https://github.com/kubernetes/kubernetes/pull/67817

**Comment by agronholm** [comment]
If it has been fixed, why am I still seeing this on Kubernetes 1.14.0 on AKS (westeurope)? It's a freshly created cluster too.

**Comment by hobti01** [comment]
@agronholm this issue is fixed in `kubectl` but not in Helm/Tiller which do not use kubectl.

For us the error also still occurs and looks like:
```
[main] 2019/07/25 08:51:09 Starting Tiller v2.13.1 (tls=false)
...
[kube] 2019/07/25 09:07:53 Watching for changes to Job log-svc-kibana-ext-post with timeout of 50m0s
...
[tiller] 2019/07/25 09:27:52 warning: Release log-svc post-upgrade log-svc/templates/kibana/post-hook.yaml could not complete: watch closed before UntilWithoutRetry timeout
```

This happens in any Kubernetes cluster, it is not cloud-provider-specific.

If you run Tiller locally, like we do, then firewall/load balancer timeouts cause an error here https://github.com/helm/helm/blob/master/pkg/kube/client.go#L820-L842

If I read https://github.com/kubernetes/kubernetes/pull/67817 correctly, the fix is to use `UntilWithSync` instead of `UntilWithoutRetry` 🤞

**Comment by agronholm** [comment]
Ah, so this needs to be fixed on the Tiller side? Getting that fix into Tiller could be problematic given that Helm 3 will not have a Tiller component.
But thank you for letting me know! :+1:

**Comment by hobti01** [comment]
20/20 hindsight 😨 
https://github.com/helm/helm/pull/4734#pullrequestreview-161769635

And it would be great if Helm 3 could be changed before forward-porting this issue:
https://github.com/helm/helm/blob/dev-v3/pkg/kube/client.go#L431

I'm going to boldly invoke @adamreese as he authored the original code 😄

**Comment by hickeyma** [comment]
@bacongobbler @adamreese Do you think this should be updated as suggested above using `UntilWithSync` instead of `UntilWithoutRetry`. If so, I can push a PR if you like.

**Comment by skinenbayev** [comment]
Keep in mind that Auto DevOps requires port 5000 be exposed in Dockerfile and your app listening on it.

**Comment by bacongobbler** [comment]
@hickeyma sure!

**Comment by mfilotto** [comment]
I also have this issue on long running hooks
Kubernetes v1.13.5
Helm v2.10.0

**Comment by hickeyma** [comment]
Sorry but got distracted and only getting back to this issue now.

The good thing is that it looks like it has been fixed by @riconnon in https://github.com/helm/helm/pull/6014. Thanks @riconnon.

Going to close this and we can re-open if its still exists.

**Comment by stopsopa** [comment]
I've encounter this issue in OpenShift cluster. My dirty hack for this (which surprisingly seems to work perfectly) is triggering rollout status twice and ignoring exit code of the first call:

```

oc rollout status dc $OS_DC --request-timeout=0 || true

oc rollout status dc $OS_DC --request-timeout=0 

```
