### ISSUE TITLE
Proposal: testing chart - show log of test pod

### ISSUE THREAD

**Issue by gardlt** [helm/helm#2923]
# Problem

Currently when we test our helm charts we get a Success or Fail. 

# Proposed solution
I propose to provide a flag that will allow the users to see the log of the test pod to get information about why it failed or passed

# Behavior 
In the `helm test <command>`  adding a flag`--log` or `--output` flag. In which, at the end of the test we output the test-pod log if flag is present. If the test pod is still present in the cluster(user did not use the clean up flag), the user should be able to get the output of the test-pod.

**Comment by technosophos** [comment]
This makes sense to me

**Comment by TD-4242** [comment]
I've been fighting with a way to do this in my CI server for the last 2 days.  Having this as an option would be amazing.  Also a way to do the --cleanup without actually running the tests would be nice as well.
