### ISSUE TITLE
`helm upgrade --install` doesn't actually perform install if there are duplicates

### ISSUE THREAD

**Issue by jeff-knurek** [helm/helm#2947]
If you have the same resources (_ie secrets_) in a chart, _(or more likely, multiple subcharts create the same secret)_ `helm upgrade --install` fails with 

`Error: release releaseName failed: secrets "secret-name" already exists`

-----
**To reproduce:** 
* `helm create test`
* add secrets file to `test/templates`
* make a copy of the secrets file in the same path
* `helm upgrade --install releaseName test/`

---- 
**Work-around:**
* run the same cmd again: `helm upgrade --install releaseName test/`

It seems that after the namespace exists, `upgrade` allows for the duplicate resources. It switches from `creating 3 resource(s)` to `checking 3 resources for changes`.

This workaround defeats the whole purpose of having an `--install` option to upgrade. But it's worth noting that this error also appears when running `helm install test/  --name releaseName`

----
Logs in the tiller:
```
[tiller] 2017/09/18 15:28:13 getting history for release t2
[storage] 2017/09/18 15:28:13 getting release history for "t2"
[tiller] 2017/09/18 15:28:13 preparing install for t2
[storage] 2017/09/18 15:28:13 getting release history for "t2"
[tiller] 2017/09/18 15:28:13 rendering test2 chart using values
2017/09/18 15:28:13 info: manifest "test2/templates/ingress.yaml" is empty. Skipping.
[tiller] 2017/09/18 15:28:13 performing install for t2
[tiller] 2017/09/18 15:28:13 executing 0 pre-install hooks for t2
[tiller] 2017/09/18 15:28:13 hooks complete for pre-install t2
[storage] 2017/09/18 15:28:13 getting release history for "t2"
[storage] 2017/09/18 15:28:13 creating release "t2.v1"
[kube] 2017/09/18 15:28:13 building resources from manifest
[kube] 2017/09/18 15:28:13 creating 3 resource(s)
[tiller] 2017/09/18 15:28:13 warning: Release "t2" failed: secrets "secret-name" already exists
[storage] 2017/09/18 15:28:13 updating release "t2.v1"
[tiller] 2017/09/18 15:28:13 failed install perform step: release t2 failed: secrets "secret-name" already exists
```
and if you run the same command again (ie: workaround):
```
[tiller] 2017/09/18 15:23:27 getting history for release t2
[storage] 2017/09/18 15:23:27 getting release history for "t2"
[tiller] 2017/09/18 15:23:28 preparing update for t2
[storage] 2017/09/18 15:23:28 getting last revision of "t2"
[storage] 2017/09/18 15:23:28 getting release history for "t2"
[tiller] 2017/09/18 15:23:28 rendering test2 chart using values
2017/09/18 15:23:28 info: manifest "test2/templates/ingress.yaml" is empty. Skipping.
[tiller] 2017/09/18 15:23:28 creating updated release for t2
[storage] 2017/09/18 15:23:28 creating release "t2.v2"
[tiller] 2017/09/18 15:23:28 performing update for t2
[tiller] 2017/09/18 15:23:28 executing 0 pre-upgrade hooks for t2
[tiller] 2017/09/18 15:23:28 hooks complete for pre-upgrade t2
[kube] 2017/09/18 15:23:28 building resources from updated manifest
[kube] 2017/09/18 15:23:28 checking 3 resources for changes
[kube] 2017/09/18 15:23:28 Looks like there are no changes for Secret "secret-name"
[kube] 2017/09/18 15:23:28 Looks like there are no changes for Secret "secret-name"
[kube] 2017/09/18 15:23:28 Looks like there are no changes for Secret "secret-name"
[tiller] 2017/09/18 15:23:28 executing 0 post-upgrade hooks for t2
[tiller] 2017/09/18 15:23:28 hooks complete for post-upgrade t2
[storage] 2017/09/18 15:23:28 updating release "t2.v1"
[tiller] 2017/09/18 15:23:28 updating status for updated release for t2
[storage] 2017/09/18 15:23:28 updating release "t2.v2"
[storage] 2017/09/18 15:23:29 getting last revision of "t2"
[storage] 2017/09/18 15:23:29 getting release history for "t2"
[kube] 2017/09/18 15:23:29 Doing get for Secret: "secret-name"
[kube] 2017/09/18 15:23:29 Doing get for Secret: "secret-name"
[kube] 2017/09/18 15:23:29 Doing get for Secret: "secret-name"
```

**Comment by arehmandev** [comment]
To add to this, if the configmap generated by helm is too big, it will not store the 'release', but it will deploy things. So you have to manually delete resources via kubectl delete

**Comment by andreychernih** [comment]
I think we are having a similar problem, but with `ServiceAccount`. We do have a _single_ copy of a ServiceAccount resource in our chart. When we do `helm upgrade --install` for the first time, we are getting the following error:

```
[debug] Created tunnel using local port: '36831'

[debug] SERVER: "localhost:36831"

[debug] Fetched jiff/environment to /root/.helm/cache/archive/environment-0.0.1.tgz

Release "environment" does not exist. Installing it now.
[debug] CHART PATH: /root/.helm/cache/archive/environment-0.0.1.tgz

2017/10/11 16:17:22 warning: skipped value for secrets: Not a table.
2017/10/11 16:17:22 warning: skipped value for secrets: Not a table.
Error: release environment failed: serviceaccounts "bastion" already exists
```

```
[main] 2017/10/11 16:16:00 Starting Tiller v2.6.1 (tls=false)
[main] 2017/10/11 16:16:00 GRPC listening on :44134
[main] 2017/10/11 16:16:00 Probes listening on :44135
[main] 2017/10/11 16:16:00 Storage driver is ConfigMap
[storage] 2017/10/11 16:16:09 listing all releases with filter
[storage] 2017/10/11 16:16:13 listing all releases with filter
[tiller] 2017/10/11 16:17:22 getting history for release environment
[storage] 2017/10/11 16:17:22 getting release history for "environment"
[tiller] 2017/10/11 16:17:24 preparing install for environment
[storage] 2017/10/11 16:17:24 getting release history for "environment"
2017/10/11 16:17:24 warning: destination for secrets is a table. Ignoring non-table value []
2017/10/11 16:17:24 warning: skipped value for secrets: Not a table.
2017/10/11 16:17:24 warning: skipped value for secrets: Not a table.
[tiller] 2017/10/11 16:17:24 rendering environment chart using values
[tiller] 2017/10/11 16:17:26 performing install for environment
[tiller] 2017/10/11 16:17:26 executing 0 pre-install hooks for environment
[tiller] 2017/10/11 16:17:26 hooks complete for pre-install environment
[storage] 2017/10/11 16:17:26 getting release history for "environment"
[storage] 2017/10/11 16:17:26 creating release "environment.v1"
[kube] 2017/10/11 16:17:26 building resources from manifest
[kube] 2017/10/11 16:17:28 creating 57 resource(s)
[tiller] 2017/10/11 16:17:28 warning: Release "environment" failed: serviceaccounts "bastion" already exists
[storage] 2017/10/11 16:17:28 updating release "environment.v1"
[tiller] 2017/10/11 16:17:28 failed install perform step: release environment failed: serviceaccounts "bastion" already exists
[storage] 2017/10/11 16:48:43 listing all releases with filter
[storage] 2017/10/11 16:53:53 listing all releases with filter
```

Subsequent runs of the same command succeed.

**Comment by varunpalekar** [comment]
I am also facing same problem: 
```
$ install_tiller
Checking Tiller...
$HELM_HOME has been configured at /root/.helm.

Tiller (the Helm server-side component) has been upgraded to the current version.
Happy Helming!
deployment "tiller-deploy" successfully rolled out
[debug] Created tunnel using local port: '45981'

[debug] SERVER: "localhost:45981"

Client: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}
tiller run successfully
$ helm_docker_secret
secret "gitlab-registry" deleted
secret "gitlab-registry" replaced
$ helm_deploy
Error: UPGRADE FAILED: no release provided
```

**Comment by gsemet** [comment]
same issue here

**Comment by bacongobbler** [comment]
Can you try with v2.8.2 with `helm upgrade --install --force`?

**Comment by alexclifford** [comment]
@bacongobbler I still get this on v2.8.2. I worked around it by not using dependencies (that are shared between my other applications) and installed the dependencies manually.

**Comment by hummelo** [comment]
same issue exsits with version 2.9.1

**Comment by pkrishnath** [comment]
same issue here with version 2.9.1

**Comment by vakaobr** [comment]
same issue here with version 2.9.1

**Comment by aliisakroe** [comment]
Has anyone found a solution to this yet? I'm having the same problem.

**Comment by pkrishnath** [comment]
There is a hack : https://medium.com/@valercara/helm-stuck-in-pending-update-and-how-to-fix-it-13c4b2eaf9f7

**Comment by silenceper** [comment]
same issue here with version v2.7.2

**Comment by omerlh** [comment]
same issue with helm 2.1.1

**Comment by bfarayev** [comment]
same issue exists in v2.10.0

**Comment by konokimo** [comment]
Any fixes for this yet? Or do we just have to run it twice? Seems like a bad idea

**Comment by xoen** [comment]
For what is worth still happens on `v2.12.3` (tiller)/`v2.12.2` (client).

I found this really surprising/annoying. Wasn't kubernetes declarative? Why do I care if a configmap/resource is there or not (usually)? Kubernetes will figure things up and eventually have make the state I requested happen.

It's not clear to me at this stage what Helm is trying to do. I thought Helm was pretty much "just" rendering the templates and run a `kubectl apply` of the rendered YAML files? (and of course keeping track of the releases/revisions).

If anyone understand this better I'd love to understand the issue a bit better 🤷‍♂️

**Comment by bacongobbler** [comment]
This was an intentional design decision. We chose the defensive decision: If something other than Helm creates a resource, Helm will not alter it. A name collision is treated as an error condition. In our view, it would be an error for Helm to assume that it can "adopt" an existing resource and treat it as part of a release.

**Comment by bacongobbler** [comment]
However, the behaviour in the OP's discussion seems like a different issue altogether. The chart is declaring the same resource twice, and Helm does not understand how to reconcile the two. It's not clear to me what's the proposed solution for this issue. To me it seems like this is intentional behaviour; one should not be able to apply the same resource twice in the same release.

**Comment by xoen** [comment]
@bacongobbler thanks for your replies:
1. I see what you mean about the design decision
2. I didn't get that the OP had a problem where the same resource was created twice.

Still not sure how to work around my problem where I'm trying to upgrade a release which has a dependency (on `stable/redis` in my case) without getting weird errors. Bear in mind the existing resource **was** created by Helm, I just upgraded the dependency and now it's not happy.

Bear in mind that in a test environment I managed to have the upgrade work, by some combination of `--force`/`--no-hooks`/`--wait`/etc...but I can't make it work again.

Any ideas on how to work around helm refusing to apply these resources? Surely the `--force` flag should tell him to do it anyway?

**Comment by phroiland** [comment]
remove **_--wait_**

I went through so many troubleshooting efforts related to **_UPGRADE FAILS_** or **_release already exists_** on Azure Pipelines, that all it took was to remove/uncheck **_wait_**

No force, no wait, no problems.

**Comment by bacongobbler** [comment]
@phroiland how does `--wait` relate to the original issue? The original report is talking about how a chart declaring the same resource twice can cause an error. It's the same error, but a different diagnosis (and therefore different solution). `--wait` will not help here.

**Comment by choldrim** [comment]
`upgrace -i --force ` works well with me, client version `v2.12.2`, server version `v2.12.0`

**Comment by cs94njw** [comment]
But when applying in Kubernetes, it will skip over resources which already exist.  Why doesn't Helm do the same?  Why not just ignore it?  Or make ignoring it a command line parameter?
I can't tell what version of helm I have installed - there's seemingly no command for that.  But I'm pretty sure it is a recent version.

We are using Helm for our CI/CD, and so running it twice isn't great.  
I think that actually our service has already been created by an Umbrella chart, and when I'm trying to upgrade an individual module it then complains.  So actually, Helm is already managing it.
I don't want to modify the Umbrella chart for SNAPSHOT deployments as other people may be modifying and deploying other module at the same time.

**Comment by xoen** [comment]
@cs94njw run `helm version` will tell you what version of helm (Client) and tiller (Server) you're using.

**Comment by cs94njw** [comment]
Thanks @xoen !  Sorry.  I did try that and didn't recognize it.  Tired today :(
Helm client: 2.12.0, server: 2.12.0

**Comment by manlme** [comment]
I met it in 2.14.

**Comment by IronCore864** [comment]
Still exists, client/server v2.14.2, even with upgrade --install --force, can't make it work. In my case it's a configmap.

**Comment by antoineozenne** [comment]
I found a solution for my case. I have an umbrella chart and subcharts that all create a regcred to pull docker images. The thing : use a .helmignore file. I just set `charts/*/regcred.yaml` in a `.helmignore` file in umbrella chart root, then helm ignores these duplicate files. when installing or upgrading. Hope it helps !

**Comment by bappr** [comment]
Still exist and v3

**Comment by santmcodes** [comment]
still exists in 2.16.  Is re-run the only workaround ?

**Comment by felipecrs** [comment]
I think `--force` makes sense in this case, but if not, we could also introduce a new parameter such as `--ignore-existing-secrets`.

The problem of re-running is that it makes very less scriptable, and it's time wasting.

**Comment by jeff-knurek** [comment]
`--force` could have unexpected side effects, cause it destroys everything first then re-installs 

the problem with "adding a new parameter" is that version 2.x is deprecated and the code is frozen, so nothing more can be done about it. It seems that the related issues in v3 are resolved.

**Comment by adapasuresh** [comment]
-bash-4.2$ helm version
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}

-bash-4.2$ helm upgrade --install --debug cbysconnector-test service-helms/CbysConnector-Test --set image.tag=cbysconnector-test-91dbb7f-26 --set image.repository=642803614633.dkr.ecr.ap-south-1.amazonaws.com/pluraldev --namespace=default
history.go:56: [debug] getting history for release cbysconnector-test
Release "cbysconnector-test" does not exist. Installing it now.
install.go:173: [debug] Original chart version: ""
install.go:190: [debug] CHART PATH: /var/lib/jenkins/workspace/CbysConnector-Test-Java/EKS_Dev/CbysConnector-Test-job/HelmDir/service-helms/CbysConnector-Test

client.go:122: [debug] creating 6 resource(s)
Error: configmaps "filebeat-configmap-cybsconnector" already exists
helm.go:81: [debug] configmaps "filebeat-configmap-cybsconnector" already exists

**Comment by mike-velotix** [comment]
still happens on 
`version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.19.4"}`

**Comment by ShamimShahraeini** [comment]
encountering the same issue:

`v3.14.4`
