### ISSUE TITLE
relative path home directory doesn't work

### ISSUE THREAD

**Issue by Stelminator** [helm/helm#2975]
I was trying to use a relative path home directory with [mcuadros/terraform-provider-helm](https://github.com/mcuadros/terraform-provider-helm) so that it would be portable to my CI system (currently Terraform Enterprise) and work for other developers.  I discovered that relative paths for helm's home directory did not work as expected when I attempted to work around https://github.com/mcuadros/terraform-provider-helm/issues/23.  I also found an issue with generation of symbolic links for `repository/cache/local-index.yaml`.

# Expected behavior:
Helm should work with relative path home directories, not just absolute paths.

# Observed behavior:
Helm does not work with relative path home directories.

# Steps to Reproduce:

```
$ cd /tmp
$ mkdir helm-home
```

## With relative path `helm-home` in working directory `/tmp/`:

```
$ helm init --home=helm-home
Creating helm-home/repository
Creating helm-home/repository/cache
Creating helm-home/repository/local
Creating helm-home/plugins
Creating helm-home/starters
Creating helm-home/cache/archive
Creating helm-home/repository/repositories.yaml
$HELM_HOME has been configured at helm-home.
Warning: Tiller is already installed in the cluster.
(Use --client-only to suppress this message, or --upgrade to upgrade Tiller to the current version.)
Happy Helming!
```
### Non-working symbolic link
```
$ ls -la helm-home/repository/cache/local-index.yaml
lrwxr-xr-x 1 christopher 37 2017-09-26 11:04 helm-home/repository/cache/local-index.yaml -> helm-home/repository/local/index.yaml
$ cat helm-home/repository/cache/local-index.yaml
cat: helm-home/repository/cache/local-index.yaml: No such file or directory
$ cat helm-home/repository/local/index.yaml
apiVersion: v1
entries: {}
generated: 2017-09-26T11:04:47.698510686-07:00
```
### Non-working cache path
(Note the mention of the strange duplicated path `helm-home/repository/cache/helm-home/repository/cache/monocular-index.yaml`)
```
$ helm --home=helm-home repo add monocular https://kubernetes-helm.github.io/monocular
Error: Looks like "https://kubernetes-helm.github.io/monocular" is not a valid chart repository or cannot be reached: open helm-home/repository/cache/helm-home/repository/cache/monocular-index.yaml: no such file or directory
$ rm -rf helm-home
```
## With absolute path `/tmp/helm-home` in working directory `/tmp/`:
```
$ mkdir helm-home
$ helm init --home=/tmp/helm-home
Creating /tmp/helm-home/repository
Creating /tmp/helm-home/repository/cache
Creating /tmp/helm-home/repository/local
Creating /tmp/helm-home/plugins
Creating /tmp/helm-home/starters
Creating /tmp/helm-home/cache/archive
Creating /tmp/helm-home/repository/repositories.yaml
$HELM_HOME has been configured at /tmp/helm-home.
Warning: Tiller is already installed in the cluster.
(Use --client-only to suppress this message, or --upgrade to upgrade Tiller to the current version.)
Happy Helming!
```
### Working symbolic link with absolute path:
```
$ ls -la helm-home/repository/cache/local-index.yaml
lrwxr-xr-x 1 christopher 42 2017-09-26 11:05 helm-home/repository/cache/local-index.yaml -> /tmp/helm-home/repository/local/index.yaml
$ cat helm-home/repository/cache/local-index.yaml
apiVersion: v1
entries: {}
generated: 2017-09-26T11:05:43.082540595-07:00
$ cat helm-home/repository/local/index.yaml
apiVersion: v1
entries: {}
generated: 2017-09-26T11:05:43.082540595-07:00
```
### Working home directory with abosolute path:
```
$ helm --home=/tmp/helm-home repo add monocular https://kubernetes-helm.github.io/monocular
"monocular" has been added to your repositories
```

# Potential (Probable?) Cause:
I believe this has to do with this line in chartrepo.go
https://github.com/kubernetes/helm/blob/8cf72adf521311225274fa835a2b04060eeb781a/pkg/repo/chartrepo.go#L136-L138

I didn't quite untangle the path handling, otherwise, this would be a pull request.

**Comment by bacongobbler** [comment]
I opened a similar ticket at https://github.com/kubernetes/helm/issues/2839. Someone is working on it at #2862.

**Comment by Stelminator** [comment]
@bacongobbler I saw your #2839, but missed #2862.  I am uncertain if everything I've mentioned would be fixed by #2862.  Close this one if you wish.

**Comment by rprobotics** [comment]
@Stelminator I'll go through this issue, and fix up any cases that I've missed in my PR. Sounds like the other issue you linked is beyond the scope of my PR. I can look into that issue as well, but most likely I won't be able to get started on it for at 2-3 weeks.

**Comment by Stelminator** [comment]
@rprobotics if `--home=` works with relative paths, I think my workaround for https://github.com/mcuadros/terraform-provider-helm/issues/23 would actually work.  There may yet be a better solution to that one, but, either would unblock me from combining helm and Terraform Enterprise.

**Comment by Stelminator** [comment]
@rprobotics @bacongobbler #2862 and removing the lines below seems to fix my issue.  #2862 fixes the repro above, then removing these lines makes everything seem to work.  I'm not sure about the backwards compatibility mentioned above them, though.
https://github.com/kubernetes/helm/blob/8cf72adf521311225274fa835a2b04060eeb781a/pkg/repo/chartrepo.go#L136-L138

**Comment by Stelminator** [comment]
> then removing these lines makes everything seem to work.

This turned out to not be necessary.  See https://github.com/kubernetes/helm/pull/2862#issuecomment-332975515

**Comment by bacongobbler** [comment]
Fixed in Helm 3 as it now follows the XDG base directory specification.

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
