### ISSUE TITLE
Can't refer to aliased subcharts by alias names in master chart

### ISSUE THREAD

**Issue by omkensey** [helm/helm#2993]
I have a chart with two subcharts in progress.  The subcharts have hyphenated names, so to avoid working around hyphens in YAML keys, I aliased them to non-hyphenated names.  However, when I try to use the alias names in the parent chart's templates, I get a render error if the values.yaml has the unaliased names for the subchart value keys; if the aliased names are used, then the subchart value keys are not actually computed into the subchart templates, leaving everything that isn't a global value blank.

**Comment by omkensey** [comment]
I believe the attached file is a minimal reproducer for showing the issue -- from what I understand, it should work, but instead throws a render error.

[testchart-0.2.0.tar.gz](https://github.com/kubernetes/helm/files/1350498/testchart-0.2.0.tar.gz)

**Comment by thomastaylor312** [comment]
@omkensey Thanks for doing the due diligence to reproduce this one. I'll try to get around to fixing this. If it isn't a huge blocker, we may wait until 2.7.1 to fix

**Comment by omkensey** [comment]
I think I have a workaround I can use for now, and can PR it to something cleaner later.

**Comment by thomastaylor312** [comment]
@omkensey That would be great! If you don't get around to it, let me know and I'll try to take it on

**Comment by josdotso** [comment]
I just hit this problem majorly.  I'm wrapping a wrapper chart and the hyphens in the upstream chart name are killing me.  Fixing this would logically fix the fact that range ops don't appear to work any better using "index".. Re: https://github.com/kubernetes/helm/issues/2192

**Comment by josdotso** [comment]
This also seems to indicate that aliasing two of the same upstream chart for different purposes with unique alias-named values.yaml trees is impossible.  I would go so far as to say the default at values.yaml should be the alias if alias exists.  If alias DOES exist, then canonical name shouldn't work IMHO -- because collisions. (Unless we intelligently scope (and fall through) "global" usage of an aliased chart via its canonical name -- apart from alias config).

**Comment by omkensey** [comment]
>  I would go so far as to say the default at values.yaml should be the alias if alias exists. If alias DOES exist, then canonical name shouldn't work IMHO -- because collisions.

As I understand it, that's how aliasing is supposed to work, actually -- see #2508.

The workaround I've been using is to set a variable at the top of the template, e.g.:

`{{- $newname := index .Values "hyphenated-name" -}}`

Then further down you can refer to $newname.whatever.

@thomastaylor312 that's the workaround I was referring to above; I've not got the coding chops to actually fix this in the helm code.

**Comment by omkensey** [comment]
Over in my chart PR kubernetes/charts#1719, unguiculus just said

> [requirements.yaml] is used for dynamically linked dependencies only, whereas you added the dependencies directly to the charts folder. I guess that's the reason why you can't use aliases in this case.

So maybe that's the issue with what I (and @josdotso?) am doing -- but if that's the case, IMHO directly-added charts should be aliasable just like charts retrieved dynamically, so I'd argue there's still a bug here.

**Comment by josdotso** [comment]
Absolutely @omkensey !

Ranging on the index-based variable wasn't working for me last night when I tried it.  Are you ranging over any such variables?

**Comment by omkensey** [comment]
No, I'm not ranging anything in my chart.

**Comment by thomastaylor312** [comment]
@omkensey I think that the comment from unguiculus was correct. The requirements file doesn't care what you have explicitly put in your `charts` directory and so that would be why you can't alias. So I don't think that is necessarily a bug in this case, but more of a feature add (I admit that is kind of splitting hairs)

@josdotso So you are having this issue even with dynamic deps?

**Comment by josdotso** [comment]
@thomastaylor312, Yes -- I believe so. I'm using requirements.yaml and `helm dependency build` on a clone.  I'll try to further confirm from scratch, but the dep build just pulls a tgz named for the canonical package with a directory in it named for the canonical package.  It seems like the deps should be pulled to tgz of alias + canonical version name, instead.  However, there's no mutating of the folder inside the tgz, so maybe I just misunderstand the mechanism.

**Comment by thomastaylor312** [comment]
@josdotso It actually only does the "renaming" inside of helm when putting together the manifests to send to tiller

**Comment by hstenzel** [comment]
I believe I just hit this bug, but with a twist.

In my scenario, I have a chart for my test harness. It needs to enable or disable various features of its subchart. However, the values being modified show up both in `USER-SUPPLIED VALUES` and `COMPUTED VALUES`, however the `requirements.yaml` condition is not being honored.

**Comment by MPV** [comment]
Here's how I reproduce this bug:

```
$ tree parent-chart
parent-chart
├── Chart.yaml
├── charts
│   ├── a -> ../../another-chart
│   └── b -> ../../another-chart
├── templates
│   └── _helpers.tpl
└── values.yaml
```

```
$ cat parent-chart/values.yaml
a:
  name: "A"
b:
  name: "B"
```

```
$ cat another-chart/values.yaml
name: "default-name"
```

And there I can see that the `COMPUTED VALUES` aren't being set correctly for the aliased charts:
```
$ helm install --dry-run --debug parent-chart 2>&1
[...]
COMPUTED VALUES:
a:
  name: "A"
b:
  name: "B"
another-chart:
  name: "default-name"
[...]
```

Whereas I'm only expecting this:
```
[...]
COMPUTED VALUES:
a:
  name: "A"
b:
  name: "B"
[...]
```

...and in turn that the right a/b values would be applied to their respective aliased subchart. 😊

**Comment by MPV** [comment]
@omkensey / @thomastaylor312 Were any of you able to take a stab at this?

**Comment by tomislater** [comment]
@MPV Yeah, I have found the same issue here: https://github.com/helm/helm/issues/7093#issuecomment-564584708
