### ISSUE TITLE
consider switching to dep

### ISSUE THREAD

**Issue by bacongobbler** [helm/helm#2997]
As per [the latest release of glide](https://github.com/Masterminds/glide/releases/tag/v0.13.0), it would seem that it'd make sense to migrate over to [dep](https://github.com/golang/dep) as that is starting to be absorbed into the core Go toolchain [according to their roadmap](https://github.com/golang/dep/wiki/Roadmap).

**Comment by mattfarina** [comment]
If there are issues switching to dep please file an issue with that project so they can correct the problem.

**Comment by edevil** [comment]
Any news on this?

**Comment by robbert229** [comment]
This has started to rot, but it makes sense to see about migrating away from glide to dep.

**Comment by bacongobbler** [comment]
Now that the setup-apimachinery script has been removed we're in a pretty good position to switch over.

**Comment by mattfarina** [comment]
Helm v3 has switched to deb. Closing. We can open another issue when we debate go module. :)
