### ISSUE TITLE
helm dependency update fails after helm upgrade

### ISSUE THREAD

**Issue by nsitbon** [helm/helm#2998]
Hi

I'm using Helm from Concourse pipeline I just upgraded Helm to 2.6.1 (from 2.4.2) and my pipeline doesn't work anymore.
The culprit line seems to be https://github.com/kubernetes/helm/blob/v2.6.1/pkg/downloader/manager.go#L220
```console
$ helm dependency update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "ci" chart repository
...Successfully got an update from the "local" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Error: Unable to move current charts to tmp dir: rename /tmp/build/put/staging-helm/cvhub-api/charts /tmp/build/put/staging-helm/cvhub-api/tmpcharts: invalid cross-device link
```
I cannot change the path used by Concourse  but if I do the same command manually on my mac from my home directory (i.e not from /tmp) it works:
```console
% ~/Downloads/helm dependency update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "ci" chart repository
...Successfully got an update from the "local" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading elasticsearch-singlenode from repo http://127.0.0.1:8879
±|develop ✘| cvhub-api
% pwd
/Users/nsitbon/github/cvhub-api/scripts/helm/cvhub-api
```
As far as I understand the error and the related code it seems that you should not use Rename rather you should use Move.

Any help would be appreciated.

Best regards.

**Comment by redbaron** [comment]
It seems that either source or destination is mount point, therefore rename doesn’t work. If you change your concourse pipeline so that both source and destination are on the same mount point it should work

**Comment by nsitbon** [comment]
I know and like I said I'm just a Concourse user I cannot change how it works and how it mounts directory. However I expect Helm working whatever the configuration like before.

**Comment by bacongobbler** [comment]
This should be a relatively quick fix. I know what’s causing this. I’ll make a PR this morning.

**Comment by bacongobbler** [comment]
For now you should downgrade to v2.5.x.

**Comment by nsitbon** [comment]
This is exactly what I did. Thx @bacongobbler

**Comment by thomastaylor312** [comment]
@bacongobbler Did you end up opening a PR for this? Is it a bug that should be pulled into 2.7?

**Comment by bacongobbler** [comment]
Sorry didn’t get around to making a PR last week, but I’ll have some free time on Monday. Thanks for the ping :)

**Comment by bacongobbler** [comment]
This was a bug introduced in a new feature for 2.6 so yeah it should be slated for 2.7.

**Comment by redbaron** [comment]
Marking it as a bug means, that any use of `os.Rename` is a bug "because of concourse". Atomic rename of a `.tmp` folder into final destination next to it is a well known, widely use pattern, there is nothing wrong with it.

@nsitbon , concourse gives you full control over final mounts and file locations.

**Comment by nsitbon** [comment]
@redbaron I disagree with "widely use pattern" I mean you should not make any assumptions on the filesystem or impose anything. By the way I don't find anything in the concourse documentation giving me access to the final mounts and file location as concourse is using docker to run its tasks it makes sense to mount the result from one task to another via mount points. Anyway  Concourse or not I do think you shouldn't impose filesystem requirements because in this case you would force all your users to change their code whereas in the other case you only have to change your code.

**Comment by bacongobbler** [comment]
I also disagree, though for different reasons. I was calling out the fact that [we are not utilizing `os.TempDir()`](https://github.com/kubernetes/helm/pull/2790#discussion_r133293551) as an issue, not the fact that using `os.Rename` is a bug. If Concourse sets up and utilizes $TMPDIR correctly, this shouldn't be an issue moving forward, especially since we use `ioutil.TempDir` everywhere else in the codebase.

> As far as I understand the error and the related code it seems that you should not use Rename rather you should use Move.

os.Rename is a `move` operation, so we're doing the right thing here.

**Comment by bacongobbler** [comment]
#3021 is the proposed fix. @nsitbon if you have some time and are able to build helm from scratch, would you mind testing that fix? Thanks!

**Comment by redbaron** [comment]
>  I disagree with "widely use pattern"

It is a fact. It is only way to create a directory with it's content in an atomic way. Every good behaving program creates directories with populated content in this way.  What you are asking is essentially to ban `rename(2)` syscall when called with  directories as an argument. This alone should set alarms off and begs the question is it a right thing to ask. Just search github for `os.Rename`, every single time it is called on directories, it can break your concourse setup. Do all of them wrong?

As for concourse, feel free to ask them on a slack channel, they are very helpful. If you change what task is producing from content of ` charts` to a `charts` directory itself, in other words move mount point 

```
/tmp/build/put/staging-helm/cvhub-api/charts
                                     ^- from here
                           ^----------- to here
```

everything will just work.

@bacongobbler patch makes things worse and wont help with this "problem" at all, as it is even more likely that $TMPDIR is on a separate mountpoint from `m.ChartPath`. Absolute correct way would be to do `ioutil.TempDir(m.ChartPath, "tmpcharts")`, then there can be no clashes with random leftovers in tmpdir.

**Comment by bacongobbler** [comment]
Right; my PR won't resolve the issue when re-naming directories across devices which is the original issue. I was talking about moving the files from the local directory over to /tmp as it should've been done in the first place, which is actually the wrong way to go about it anyways.

Pulling out of v2.7.0 and tagging as question/support.

**Comment by nsitbon** [comment]
@redbaron I may not have been clear what I mean by not a "widely use pattern" is not the use of os.Rename but more the fact that you are making assumptions about the layout of the filesytem. Feel free to use whatever syscalls you need for your the data you own but not for the data owned by other. From my point of view it's a regression as my code was working before and now it doesn't. Are you going to ask every other software developer (I mean other than Concourse dev) to change how they mount file or are you going to manage it yourself? From a developer perspective when I use some kind of library I hope they won't make assumption that will force me and any other user to change their code. It's better to fix one place than to fix n (read 10 or 100 or 1000) places.

**Comment by redbaron** [comment]
Problem is helm "owns" both source and destination of os.Rename.  If you hijack one of them by making it a mount point, it is not a helm problem.

**Comment by nsitbon** [comment]
I disagree the creator is the owner so helm is not owning the source.

**Comment by bacongobbler** [comment]
dep has a convenient function called [`RenameWithFallback`](https://github.com/golang/dep/blob/5b1fe9e6d89372487d0aac78d9c5362a517857e7/internal/fs/fs.go#L103-L118) which will fall back to a copy-and-remove operation in the case of a cross-device link error. This should be a relatively quick fix if someone wants to take a crack at it!

**Comment by databus23** [comment]
I ran into this as well but was a little baffled by it because source and target are on the same mount point in this concourse scenario.

I think the problem is that the mount point is an overlayfs filesystem (thats how concourse passes inputs into task containers).

I found this in the (unrelated) docker docs in the [working with overlay section](https://docs.docker.com/engine/userguide/storagedriver/overlayfs-driver/#modifying-files-or-directories):

> *Renaming directories:* Calling rename(2) for a directory is allowed only when both the source and the destination path are on the top layer. Otherwise, it returns EXDEV error (“cross-device link not permitted”). Your application needs to be designed to handle EXDEV and fall back to a “copy and unlink” strategy.

**Comment by databus23** [comment]
A workaround for the concourse case is to copy the charts from the `input` volume before running  `helm dep up` e.g.:
```
cp -r staging-helm/cvhub-api/charts staging-helm.bak
helm den up staging-helm.bak/staging-helm/cvhub-api
```

**Comment by smoya** [comment]
This issue is happening to me when running a docker run command only in Docker for mac. Same command on a linux env work with no problem at all.

I think implementing https://github.com/golang/dep/blob/5b1fe9e6d89372487d0aac78d9c5362a517857e7/internal/fs/fs.go#L103-L118 in helm code would be a quick win.

**Comment by bacongobbler** [comment]
@smoya yup, noted that earlier at https://github.com/helm/helm/issues/2998#issuecomment-337342285 😂

**Comment by smoya** [comment]
@bacongobbler Yes, I missed writing that I agree with your suggestion. 👍

**Comment by chancez** [comment]
Is there a work-around for this that doesn't involve modifying helm?

**Comment by chancez** [comment]
Ah, found one: manually call helm package on dependencies, specifying the destination `chart/` directory of the parent chart.

**Comment by Anuraag-Advani** [comment]
I have the same error in docker(mac). Why do I see it when I have not mounted the directory?

**Comment by bricerisingslalom** [comment]
I'm trying out using RenameWithFallback to rename the file like was previously suggested, but I am by no means a go developer. Are there any instructions for building helm so I can test my changes? I'm not having a lot of luck on my own

**Comment by bacongobbler** [comment]
[The Developer Guide](https://docs.helm.sh/developers/) should help you get started. If you're new to Go, [The official Go install guide](https://golang.org/doc/install) is a good resource as well. Let us know if you run into any issues!

**Comment by bricerisingslalom** [comment]
Thank you @bacongobbler !

**Comment by bricerisingslalom** [comment]
@bacongobbler I managed to get it working by ruthlessly stealing the fs package from the deps project and throwing it into helm. I've never done open source development before, is doing that koscher in the open source community?

**Comment by bricerisingslalom** [comment]
Deps seems like a cool product, but I have concerns with using their fs package in helm when it doesn't seem to be a core feature of deps. With any release of deps they could decide to change their implementation, and that could lead to a broken build in helm unless we stick to a hard release number. Also if we decide we need more features from the fs package, that could lead to us needing to make contributions to deps that may not be part of the scope of their project right?

**Comment by bacongobbler** [comment]
The dep core maintainers are pretty good about maintaining backwards compatibility, and that's why we pin versions. If we eventually need to extend the fs package then we can talk to the maintainers about splitting it out and maintaining it as a separate package. I wouldn't worry about it.

**Comment by bricerisingslalom** [comment]
Cool, I'll go ahead and make that change then :thumbsup:

**Comment by bricerisingslalom** [comment]
When I try to reference their fs package I get this error
```pkg/downloader/manager.go:32:2: use of internal package k8s.io/helm/vendor/github.com/golang/dep/internal/fs not allowed```
After some reading, my understanding is that internal is a special folder in a go project for packages that are only meant to be used within a project and not distributed. I seem to be getting that error both when the package is find in the `vendor` folder as well as when it's from my $GOPATH. Is there a way I can still make this import work?

**Comment by bacongobbler** [comment]
Oh..  if they've marked it as internal then probably not.

**Comment by bricerisingslalom** [comment]
I'm working on a PR now, but one of the style checks looks for this string in files 
```Licensed under the Apache License, Version 2.0 (the "License");```

But the fs files from dep have this string in them
```// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.```

Does this mean that I can't use the dep fs package in helm, or can this code fall under multiple open source liscenses? Do we need to get input for the dep maintainers?

**Comment by bricerisingslalom** [comment]
Is there something I can do to help with getting this fix merged?

**Comment by chriscone** [comment]
Are there plans for merging this PR?  Our team could use this fix also

**Comment by bacongobbler** [comment]
Thanks for the ping @chriscone.

for reference, here is the PR (had to go looking to find it again): https://github.com/helm/helm/pull/5038

The PR introduces code from dep, which is BSD-licensed code which is okay to re-license it as Apache 2 code. The problem at hand, though, is that we're unsure if copying code from `internal/fs` follows the DCO.

I can't recall who was looking into this, but it probably fell through the cracks. I'll open a ticket with the [CNCF service desk](https://github.com/cncf/servicedesk#legal-services) and see if we can get the legal team to weigh in on this topic.

**Comment by wknapik** [comment]
Just ran into this in a containerized CI pipeline running on Linux with helm 2.12.3.
Helm's operations do not cross the boundary of the filesystem bind-mounted from the host as $HOME.
That's the first time I've seen this happen with this setup.

**Comment by de-code** [comment]
A simple workaround for me (which I didn't see above), was to just remove the `charts` directory - or add it to something like `.dockerignore` to not copy it in the first place (if it's part of a Docker build). May not work for everyone.

**Comment by bacongobbler** [comment]
due to inactivity, I had to close #5038. If anyone else feels like taking this across the finish line, please feel free!

**Comment by bacongobbler** [comment]
fixed in https://github.com/helm/helm/pull/6750.
