### ISSUE TITLE
Improve helm lint

### ISSUE THREAD

**Issue by michelleN** [helm/helm#300]
A more advanced version of linter would include the following: 

1. verify docker images exist
2. "Do the dependencies exist, and are the version constraints possible to match?" - @technosophos 
3. make the chart name uniqueness check smarter
4. Take in a path instead of a chart name to lint
5. Be able to lint all charts and output json (so that @sgoings can scrape through the travis ci log when travis builds master and update bades to either success/fail)
Something like ...
```
[helm-lint] Running helm-lint...
{ "charts": 
  [
    {
      "name": "redis", 
      "status": 50, 
      "failed_criteria": ["lint-type-1", "lint-type-2"]
    }, 
    {
      "name": "alpine", 
      "status": 100
    }
  ]
}
```

More suggestions/feedback welcome.

**Comment by sgoings** [comment]
See also #307

**Comment by sgoings** [comment]
@michelleN thoughts on breaking these bullet points out into separate issues? I'm interested in chipping in on a few of these.

**Comment by adamreese** [comment]
It would be nice if lint would give a list of all failures rather than exit on first failed check.

**Comment by michelleN** [comment]
@sgoings yeah that's a great idea. I'll do that.

**Comment by michelleN** [comment]
@adamreese agreed

**Comment by michelleN** [comment]
Closing in favor of using smaller issues to complete this task. Please reference issues #308 #310 #311 #312 #313.
