### ISSUE TITLE
Another code consolidation opportunity in pkg/chartutils/requirements.go

### ISSUE THREAD

**Issue by ljnelson** [helm/helm#3018]
I believe that the lines here (https://github.com/kubernetes/helm/blob/v2.6.2/pkg/chartutil/requirements.go#L261-L293) can be drastically, drastically simplified.

Unless I am missing something (always possible, since I am no kind of Go programmer), this block:

* "sets aside" subcharts that aren't referenced in a `requirements.yaml` in a new list, `chartDependencies` (seemingly as a fix for #2830)
* potentially renames those that are referenced, using the `alias` value if there is one, and adds them to `chartDependencies` as well.  (`chartDependencies` now contains all the original subcharts; it's just that some of them might have different names now, and the list is in potentially a different order (which doesn't matter).)
* replaces the chart's original subchart list with `chartDependencies`
* sets all `requirements.yaml` `dependencies` entries to an enablement status of `true`
* renames all `requirements.yaml` `dependencies` entries to the value of their `alias`, if they have one

This reduces to:

* go through the list of subcharts in-place.  If a `requirements.yaml` `dependencies` entry applies to it (`name` and `version` are applicable), possibly rename it in-place with the `alias`.  In all other cases, leave it alone.
* While you're at it, rename the `requirements.yaml` entry to its `alias` too, if it has one, and make sure its enablement status is `true`.

Filed here per @jascott1's request for tracking potential refactoring opportunities.  Feel free to nuke, edit, remove, disparage, etc.

**Comment by thomastaylor312** [comment]
Thanks for submitting this! I'll mark as a refactor and help wanted in case anyone would like to do this

**Comment by ljnelson** [comment]
Who knows; if I get my confidence together and decide I want to start breaking things in Go maybe I'll take a crack at it!

**Comment by bacongobbler** [comment]
closing as inactive.
