### ISSUE TITLE
Problems with randAlphaNum and upgrades

### ISSUE THREAD

**Issue by withnale** [helm/helm#3053]
There are problems with using randAlphaNum in charts when upgrades occur. I'm sure this is working as expected right now, but is problematic and it should at least be documented if there is no alternate implementation right now.

If you consider the current stable/redis chart, if you don't specify a password in your values when creating the chart a random one is created using the following data block for the secret...

```yaml
data:
  {{- if .Values.redisPassword }}
  redis-password: {{ .Values.redisPassword | b64enc | quote }}
  {{- else }}
  redis-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
{{- end -}}
```

So far so good. However, this value is recreated to a new random string whenever it is evaluated, which invalidates the secret - so anything which subsequently reads the secret using `secretKeyRef` will be given the incorrect password.

To reproduce is simple...

```bash
bash% helm install stable/redis
bash% kubectl get secret solid-ibis-redis -o jsonpath="{.data.redis-password}" | base64 --decode
YAILVFmyeK% 

bash% helm upgrade --set my.irrelevant.key=1 solid-ibis stable/redis
bash% kubectl get secret solid-ibis-redis -o jsonpath="{.data.redis-password}" | base64 --decode
Ky7iOZbC2J%
```

Now I can understand what is happening, but I'm interested how people should write their charts to avoid this problem. We often use mongo, redis and rabbitmq as subcharts and having a random password generated and shared across the various subcharts is pretty useful.

I was vaguely looking at hooks, but I could only create a secret on a pre-install hook, but this then gets left behind when the instance is deleted.

Any ideas...?

**Comment by jascott1** [comment]
@withnale 

Would only generating on actual install (not upgrade) help? You could try 

```
{- else }}
  {{- if .Release.IsInstall }}
  redis-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
{{- end }}
```

**Comment by ianburrell** [comment]
@withnale 

There is [technique to update deployments when Secrets change](https://github.com/kubernetes/helm/blob/master/docs/charts_tips_and_tricks.md#automatically-roll-deployments-when-configmaps-or-secrets-change). None of the charts do this for secrets. It would also lead to unnecessary restarts. There are also containers that only set the initial password and don't change password when updated (kubernetes/charts#362).

**Comment by ianburrell** [comment]
@jascott1 

I don't think that will work because on update, the secret will be empty or missing. What is needed is some way to save the random value from install.

1. Reference previous value of secret
2. Template default values
3. Deterministically generate random values

**Comment by jascott1** [comment]
Im not sure what the ultimate solution is but in this case I would generate the secrets outside and put them in the values.yaml. While not ideal, it is straightforward and less time consuming than hacking around the current constraints of the system. Its possible that the redis example is just a low friction installation method for evaluating the chart and production installations are intended to supply their secrets via values (the template does accommodate secrets from values.yaml).

**Comment by thomas-riccardi** [comment]
/remove-lifecycle stale

The issue is still there; the current workaround is to require users to give the secrets as values, and stop using `randAlphaNum`, which is bad because we then have no guarantee the user uses proper random values.

**Comment by beltran-rubo** [comment]
It seems the feature of keeping a resource only works with "helm delete" but not with "helm upgrade"

```
  annotations:
    "helm.sh/resource-policy": keep
```

That would fix the issue for reusing secrets or any other resource.

**Comment by alexvicegrab** [comment]
Using an annotation to prevent a resource being updated would go a long way, yes. That way in the unusual event when we'd want to recreate the secret, we'd delete it in K8S and then update the chart.

**Comment by michaelfig** [comment]
Rather than an annotation to prevent updates, could we have an annotation on the source template to say it shouldn't overwrite anything?

**Comment by verwilst** [comment]
I would like to use randAlphaNum to generate an APP_KEY for my Laravel app. This cannot be regenerated on every helm upgrade, since changing APP_KEY invalidates all Hash::make()'ed passwords for example.

**Comment by XBeg9** [comment]
Any updates here?

**Comment by jseguillon** [comment]
Maybe we should add a flag to exclude all secrets when upgrading ? Or maybe we could add a flag to exclude some  ressources from upgrade based on k8s selectors or regexp pattern ?  

Seems to be this would be enough for a first workaround.

**Comment by jkroepke** [comment]
I have the same problem w/ the certificate function, e.g.: genSignedCert

On every upgrade a new certificate is generated.

http://masterminds.github.io/sprig/crypto.html

**Comment by spk83** [comment]
Would pre-install hook work in this case? Create secret with that annotation...

**Comment by ahilsend** [comment]
A pre-install hook wouldn't delete the secret on deleting the release though. Which is a bit of an annoyance for CI/CD deployments that create secrets that way.

**Comment by micw** [comment]
A workaround is to combine .Release.IsInstall with "helm.sh/resource-policy": keep:

```
{{- if .Release.IsInstall }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
 password: "{{ randAlphaNum 10 | b64enc }}"
{{- end }}
```

Drawback is that if the secret is deleted manually, it's only re-created if the chart is re-installed.

**Comment by FrenchBen** [comment]
I'm guessing no progress has made on this? having a resource deleted after it was created upon install is quite annoying.

**Comment by wemu** [comment]
we encountered a similar issue with having randAlphaNum in names:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.tkNameId }}-wes-{{ randAlphaNum 4 | lower }}
  labels:
```

I expected helm to know its last release resources and see that the resource in the new releleas is missing and therefore delete it. But it does not (the resource comes from a required chart). All the resources remain in kubernetes after an upgrade.

**Comment by viane** [comment]
Hi, i don't understand why we can't use `Release.IsUpgrade` and `Release.IsInstall` to control  random secret generation at certain condition? Can somebody explain? I'm facing the same problem but I don't know why people complains pf using those built-in object.

**Comment by jkroepke** [comment]
@viane can you make a example without define the generated secrets inside a values.yaml.

**Comment by viane** [comment]
@jkroepke I randomly generate those values in a secret yaml, then reference the `data` from that secret.

**Comment by jkroepke** [comment]
@viane How I can reference data? I can't see such a helm function to get data from deployed resources.

**Comment by nullck** [comment]
try to use these annotations:
```
  annotations:
    “helm.sh/hook”: “pre-install”
    “helm.sh/hook-delete-policy”: “before-hook-creation”
```

reference:  https://medium.com/nuvo-group-tech/move-your-certs-to-helm-4f5f61338aca

**Comment by pbecotte** [comment]
Just as a reminder, nullck's solution works- so long as the secret never gets deleted/has to be recreated.

**Comment by antonu17** [comment]
Nullck's referenced solution works indeed, but only for _newly_ installing releases. If a template is added to the existing (and installed) helm chart `pre-install` hook will not work. Adding `pre-upgrade` hook will cause the same behavior as subj.

**Comment by bacongobbler** [comment]
> Maybe the solution is another type of hook or hook policy, something along the lines of "if-not-exists" where it always gets created if it isn't there, but never gets updated if it is?

Perhaps the new `lookup` function introduced in Helm 3.1 could prove useful in this regard. https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-lookup-function

**Comment by codeclown** [comment]
For anyone who stumbles here from Google, here's how I resolved this issue using the `lookup` function mentioned above:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: foobar-secret
type: Opaque
{{- $previous := lookup "v1" "Secret" .Release.Namespace "foobar-secret" }}
data:
  {{- if $previous }}
  foobarPassword: {{ $previous.data.foobarPassword }}
  {{- else if .Values.foobarPassword }}
  foobarPassword: {{ .Values.foobarPassword | b64enc | quote }}
  {{- else }}
  foobarPassword: {{ randAlphaNum 40 | b64enc | quote }}
  {{- end }}
```
