### ISSUE TITLE
switch `tiller` to `tiller serve`

### ISSUE THREAD

**Issue by bacongobbler** [helm/helm#3069]
As part of #2841, one of the discussion points for 3.0 was to change the execution of `tiller` to `tiller serve`. That way we can introduce new commands like `tiller version` due to the limitations of spf13/cobra.

**Comment by thomastaylor312** [comment]
I think this would be a great idea. We could even bring it in now if we can have the root level `tiller` just be an alias for `tiller serve` until we hit Helm 3

**Comment by mattfarina** [comment]
Since tiller was removed for v3 I'm closing this issue. It's been overcome by events.
