### ISSUE TITLE
Release failure or error logs

### ISSUE THREAD

**Issue by tommysitu** [helm/helm#3077]
I am using Helm version 2.6.1.

When a release is failed, how can I see more details about the failure? 
Running `helm history <release-name>` won't give me the full description: 
REVISION	UPDATED                 	STATUS	CHART                              	DESCRIPTION
1       	Tue Oct 31 10:28:08 2017	FAILED	my-chart	    Release "my-chart" failed: Servic...

I can't find any command or flag that could return the logs, please help.

**Comment by thomastaylor312** [comment]
@tommysitu Helm doesn't provide the logs for you. You have to debug it using `kubectl logs` if you'd like to see the logs. There is some work to stream back logs with Helm, but it is only for hooks (see #2342). Does that answer your question?

**Comment by tommysitu** [comment]
I can't use `kubectl logs` because my Helm release failed at creating k8s service, which is before creating any pods.  I think Helm must have kept the log somewhere, hence the description `Release "my-chart" failed: Servic...` which is truncated with ellipsis, and there is no way to see the full description.

**Comment by bacongobbler** [comment]
When you first ran `helm install`, the logs should have been displayed in full to you. Did that not happen for you?

Try and see if `helm status <release-name>` shows any more information. If not, https://github.com/kubernetes/helm/pull/2950 would be a good one to pull in for `helm status`.

**Comment by tommysitu** [comment]
`helm status` only shows that the release is failed, not quite useful for debugging. `helm install` will print the log at the time you run it, but in our environment upgrading Helm releases are triggered by  background jobs. So it would be more useful to have `helm status` or `helm history` to return the reason of failure.

**Comment by stealthybox** [comment]
I've also stumbled into this issue.

**Comment by Nowaker** [comment]
+1. Because Helm is in charge of upgrades, it should collect everything relevant to the upgrade process.

**Comment by randude** [comment]
+1 I installed version 1.0.1, then upgraded to 1.0.2. When I tried to go back to 1.0.1 with the rollback, i got an error and the who env. got messed up.

**Comment by pruneau628** [comment]
+1
At least a non-ellipsized error message would help.

**Comment by vlavicka** [comment]
Actually, if you run `helm history <release> -o yaml` you get full error message without ellipsis.

**Comment by bacongobbler** [comment]
You can also run `helm history RELEASE --col-width=0` to get the full un-buffered output.

I think we can consider this closed since the original request for non-ellipsized error messages have been documented. Please let me know if there's something else in this ticket that we need to address and we can re-open this. Thanks!

**Comment by android2221** [comment]
All hail bacongobbler!

**Comment by tcr-ableton** [comment]
I don't know you folks, but even with `helm history RELEASE --col-width=0`, my output is still truncated. It looks like a pretty big output indeed, but still, part of the context is truncated to `...`. Is there a way to go around that: that makes the description absolutely unusable to me at the moment. It feels a bit like a guessing game 👯‍♂

**Comment by cc-stjm** [comment]
@tcr-ableton you should find that:

`helm history --col-width=0 RELEASE` works (note the order of arguments)

**Comment by Leibniz137** [comment]
I also had @tcr-ableton 's issue with truncated output:
```
$ helm history --col-width=0 rabbitmq-ha
Upgrade "rabbitmq-ha" failed: v1.StatefulSet.Spec: v1.StatefulSetSpec.Template: v1.PodTemplateSpec.Spec: v1.
PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.v1.EnvVar.Value: Name: ReadString: expects " or n, but found 0, error found in #10 byte of ...|,{"name":0,"value":"|..., bigger context
 ...|gement-password","name":"rabbitmq-ha"}}},{"name":0,"value":"map[name:RABBIT_MANAGEMENT_USER valueFro|...
```
using these versions:
```
$ helm --tiller-namespace helm version
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```
One thing I did find helpful though was to run the install/upgrade with `--debug --dry-run` flags. Once I could see the template that was rendered, it was obvious what the error was. I was using a chart from a remote repo, so I couldn't use `helm template`

The specific issue with the ellipsis (`...`) though remains

**Comment by icyi2i** [comment]
Using Helm 3.5.3. --debug flag is the solution in my case.

`helm history <release-name> -n <namespace> --debug`

**Comment by csabakollar** [comment]
😞 
```
❯ helm history gloo --debug -o yaml
- app_version: ""
  chart: gloo-ee-1.0.0
  description: 'Release "gloo" failed: timed out waiting for the condition'
  revision: 1
  status: failed
  updated: "2022-08-09T11:46:50.890958+01:00"
```
Not so helpful. Installation via Terraform :(
