### ISSUE TITLE
feature/proposal: let linter discover old templating for "fullname" and provide guidance

### ISSUE THREAD

**Issue by davidkarlsen** [helm/helm#3081]
See: https://github.com/kubernetes/helm/pull/2845 for a background.
There was a change in how the naming is done and the default generated _helper.
Maybe the linter should detect the old scheme and warn so that existing charts can move forward to the newer style - this would increase awareness and help on consistency.

**Comment by bacongobbler** [comment]
I doesn't look like this ticket has been touched in nearly a year, so it doesn't seem like there's interest in someone contributing a patch. I'm going to close this for now, but please feel free to re-open with a patch. Thanks.
