### ISSUE TITLE
Document Values vs Raw better

### ISSUE THREAD

**Issue by rcorre** [helm/helm#3109]
I'm using helm as a library, and trying to get structured data out of the helm interface.
In particular, I want the default and overridden values. I expected that I could call `GetReleaseContent` and use:

```
rel := response.GetRelease()
return InfoResponse{
    Name:           rel.GetName(),
    Namespace:      rel.GetNamespace(),
    Info:           rel.GetInfo(),
    ValueDefaults:  rel.GetChart().Values.Values,
    ValueOverrides: rel.GetConfig().Values,
    Version:        rel.GetVersion(),
}
```

However, `rel.GetChart().Values.Values` and `rel.GetConfig().Values` are nil. It looks like only the `Raw` values are populated. Why? The function/type docstrings don't mention anything about it. I'm not clear on whether this is a bug or just something that needs to be documented better.

In the latter case, I'd like to see docstrings on the public fields saying:

- When `Values` will be non-nil (if ever, and if not, why is it public?)
- What exactly `Raw` is (looks like yaml, but is that a guarantee?)

I'm on tiller `2.6.1` and our client is pinned to be3ae4ea91b2960be98c07e8f73754e67e87963c.

**Comment by bacongobbler** [comment]
fixed in Helm 3.
