### ISSUE TITLE
linter should accept a chart path

### ISSUE THREAD

**Issue by michelleN** [helm/helm#311]

**Comment by michelleN** [comment]
Please see https://github.com/helm/helm/pull/263 for more context.

Currently to lint a chart, one uses the command `helm lint [chart-name]` which assumes that the chart is in the workspace directory. 
@sgoings made a good point by stating that our current workflow is workspace centric so the current usage: `helm lint [chart-name]` feels natural to me.
@technosophos mentioned it might, however, be a better user experience for lint to take in a chart path instead of just the name. 

I think taking a chart path would be really helpful so we're not confined to charts in the workspace directory. I was thinking of adding an optional --path flag to help with this. 

Any thoughts or something I might be missing @technosophos @sgoings ?

**Comment by sgoings** [comment]
If you're going to say: "--path" you should also still require the name of the chart that needs to be tested at that path. If you want users to pass in a Chartfile, maybe "--chartfile" or "--chart" makes more sense?
