### ISSUE TITLE
YAML to JSON error fixed by cleaning local repository 

### ISSUE THREAD

**Issue by drewwells** [helm/helm#3111]
We have an issue that 1 in 10-20 charts will fail with `YAML to JSON` error. This chart does not change, it is just being packaged with a new name. The only known workaround is to wipe the local cache and `helm init`. This error appears to be independent of the current path being packaged. Removing all the templates still results in this `YAML to JSON` error occurring

```
-> % helm package tkm-chart
Successfully packaged chart and saved it to: /path/to/tkm-chart-1.2.11.12-5a43454f-dirty.tgz
Error: error converting YAML to JSON: yaml: line 214: could not find expected ':'
-> % mv ~/.helm ~/.helm.bak
-> % helm init --client-only
Creating /dir/.helm
Creating /dir/.helm/repository
Creating /dir/.helm/repository/cache
Creating /dir/.helm/repository/local
Creating /dir/.helm/plugins
Creating /dir/.helm/starters
Creating /dir/.helm/cache/archive
Creating /dir/.helm/repository/repositories.yaml
$HELM_HOME has been configured at /dir/.helm.
Not installing tiller due to 'client-only' flag having been set
Happy Helming!

-> % helm package tkm-chart
Successfully packaged chart and saved it to: /path/to/tkm-chart-1.2.11.12-5a43454f-dirty.tgz
-> % rm -rf ~/.helm
-> % mv ~/.helm.bak ~/.helm
-> % helm package tkm-chart
Successfully packaged chart and saved it to: /path/to/tkm-chart-1.2.11.12-5a43454f-dirty.tgz
Error: error converting YAML to JSON: yaml: line 214: could not find expected ':'
```

**Comment by jascott1** [comment]
Hi @drewwells 

What versions of Helm and k8s are you running? Also does this occur for any chart after n number of installs or just this chart?

**Comment by drewwells** [comment]
```
-> % helm version
Client: &version.Version{SemVer:"v2.5.1", GitCommit:"7cf31e8d9a026287041bae077b09165be247ae66", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.5.1", GitCommit:"7cf31e8d9a026287041bae077b09165be247ae66", GitTreeState:"clean"}

-> % k version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T21:07:53Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.7", GitCommit:"8e1552342355496b62754e61ad5f802a0f3f1fa7", GitTreeState:"clean", BuildDate:"2017-09-28T23:56:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

foolishly, I deleted my broken ~/.helm. I will get back to you on any chart failing or just this one.

**Comment by drewwells** [comment]
This happens for any chart that you attempt to package after the local repo is corrupted

```
-> % helm --home ~/.helm.bad package secured-prometheus -d build/
Successfully packaged chart and saved it to: build/secured-prometheus-0.2.2.tgz
Error: error converting YAML to JSON: yaml: line 702: could not find expected ':'
```

Same line number on every error message. I've kept the broken repo this time, for further debugging (but can't share it)

**Comment by wknapik** [comment]
I've been seeing this error from time to time as well. It's *really* annoying when it happens in CI jobs. Never thought to delete the .helm directory. Could be a workaround...

```
% head -n1 /etc/os-release
NAME="Arch Linux"
% helm version
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
% kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:48:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.8", GitCommit:"e8c167a115ec662726904265d17f75a6d79d78d8", GitTreeState:"clean", BuildDate:"2017-10-01T00:01:59Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
% 
```

**Comment by wknapik** [comment]
At this point I run `rm -fr ~/.helm` in CI pipelines, as a workaround, but it still happens occasionally.

**Comment by cory-klein** [comment]
We just saw this exact same issue today and it was indeed resolved by removing `~/.helm`. However as a long-term solution we've added this to our Jenkinsfile:

```
environment {
  HELM_HOME = '${env.WORKSPACE}/.helm'
}
```

This causes helm to place it's home directory in the job workspace, preventing templates or assets from previous builds to carry over into the next build in the first place.

**Comment by wknapik** [comment]
Still a problem as of helm v2.11.0.

**Comment by aubm** [comment]
I managed to reproduce the bug.

It appears that too many concurrent `helm package` operations will eventually leave the local `index.yaml` file corrupted.

Here is the sample go code that I use to reproduce:

```go
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"os/exec"
	"sync"
)

var (
	nbConcurrentProcesses int
)

func init() {
	flag.IntVar(&nbConcurrentProcesses, "n", 10, "nb concurrent processes")
	flag.Parse()
}

func main() {
	wg := sync.WaitGroup{}
	for i:= 0; i < nbConcurrentProcesses; i++ {
		wg.Add(1)
		go func(i int) {
			defer wg.Done()
			runHelmInstall(i)
		}(i)
	}
	wg.Wait()
}

func runHelmInstall(i int) {
	output, err := os.Create(fmt.Sprintf("output_process_%v.txt", i))
	exitOnError(err)
	defer output.Close()

	// helm package /tmp/cerebro
	cmd := exec.Command("helm", "package", "/tmp/cerebro")
	cmd.Stdout = output
	cmd.Stderr = output
	if err := cmd.Run(); err != nil {
		fmt.Printf("failed to run helm install: %v\n", err)
		return
	}

	fmt.Println("it all good baby") // idée de Clément
}

func exitOnError(err error) {
	if err == nil {
		return
	}
	log.Fatal(err.Error())
}
```

```
go run main.go -n 500
```

**Comment by wknapik** [comment]
For me this happens with some regularity when running 17 concurrent helm package invocations. I'm also working around #2258 by retrying failed calls up to 2 times (for a total of 3), so the actual number might be higher.

This bug was last triggered in my CI today, with helm version 2.12.3 on Linux.

**Comment by evisong** [comment]
In my case, we're triggering 8 `helm package` commands in parallel on an AWS EC2 instance.

According to the debug log:

```
[debug] Setting version to 1.0.0
[debug] Setting appVersion to 1.0.0
Successfully packaged chart and saved it to: target/one_chart-1.0.0.tgz
[debug] Successfully saved target/one_chart-1.0.0.tgz to /root/.helm/repository/local

[debug] Setting version to 1.0.0
[debug] Setting appVersion to 1.0.0
Successfully packaged chart and saved it to: target/the_other_chart.tgz
Error: error converting YAML to JSON: yaml: line 14: could not find expected ':'
```

All `helm package` commands are able to create the helm tgz. However, the successful ones manage to save the *.tgz to local helm repo, but the failure ones throw error at this step.

We have other pipeline steps to upload helm charts to a centralized repo, so I'm adding `--save=false` flag to bypass the local repo.

This workaround is running for days, so far so good.

**Comment by wknapik** [comment]
@evisong didn't work for me unfortunately ;/

```
% ls -a
.  ..  .helmignore  Chart.yaml  templates  values.yaml
% cat .helmignore 
.DS_Store
.git/
.gitignore
.bzr/
.bzrignore
.hg/
.hgignore
.svn/
*.swp
*.bak
*.tmp
*~
.project
.idea/
*.tmproj
% helm package .
Successfully packaged chart and saved it to: foo/bar-v1.2.3.tgz
% helm package --save false .
Error: chart metadata (Chart.yaml) missing
%
```
In fact, that kinda looks like a new bug.

It's the first time I'm seeing this error and google is not turning up anything useful.
I did find #3622, but that seems to be a different issue.

**Comment by wknapik** [comment]
Ehh, it's the stupid command line parser - need to use `--save=false` :|

**Comment by wknapik** [comment]
Thanks for the hint @evisong.

**Comment by bacongobbler** [comment]
I haven't seen any movement from the community to try and fix this issue, so I'm closing this as inactive.
