### ISSUE TITLE
Order resources in `helm status` output

### ISSUE THREAD

**Issue by arschles** [helm/helm#3127]
If you execute `helm status` on the same release, the ordering of the Kubernetes resources changes even if nothing else has.

I'm not sure, but it seems like the ordering is non-deterministic. I believe that they should be ordered deterministically so that multiple calls to `helm status` (or, some people run it inside a `watch` or similar) are easier to read.

**Comment by thomastaylor312** [comment]
@arschles I have seen the same behavior and I am all for deterministic ordering. I don't think this requires much discussion, so I am going label it as a feature. If for some reason there is problem we can always move it back to a proposal state.

**Comment by arschles** [comment]
Thanks @thomastaylor312

**Comment by thomas-riccardi** [comment]
/remove-lifecycle frozen

This feature is very useful, for example when using `watch helm status bla`.

The resources types could be sorted in the same order as they are applied.

**Comment by bacongobbler** [comment]
@thomas-riccardi keeping the "lifecycle/frozen" label keeps this issue from closing. I don't think that was your intention. :)

/lifecycle frozen

**Comment by MPV** [comment]
The PR #3214 by @silenceshell seems to have gone stale.

Anyone else up for giving it a try?

I'd like to but my Golang skills aren't good enough yet.

**Comment by bacongobbler** [comment]
#5140 seems to be the most promising PR. Assuming that gets merged, that should also solve your use case with the watch flag. Thanks for pointing out that use case!
