### ISSUE TITLE
Would be nice to lint all charts at once

### ISSUE THREAD

**Issue by michelleN** [helm/helm#313]
Be able to lint all charts and output json (so that @sgoings can scrape through the travis ci log when travis builds master and update bades to either success/fail) Something like ...
```
[helm-lint] Running helm-lint...
{ "charts": 
  [
    {
      "name": "redis", 
      "status": 50, 
      "failed_criteria": ["lint-type-1", "lint-type-2"]
    }, 
    {
      "name": "alpine", 
      "status": 100
    }
  ]
}
```

**Comment by arschles** [comment]
:+1:

maybe add an `--all` flag to the lint cmd?

**Comment by michelleN** [comment]
@arschles yeah absolutely.
