### ISSUE TITLE
helm install --replace fails with "cannot re-use a name that is still in use"

### ISSUE THREAD

**Issue by Morriz** [helm/helm#3134]
Hi, I try to idempotently deploy a package with:
```
helm install --replace --tiller-namespace=system --namespace=system -n somepackage
```
(I use the `system` namespace, and tiller is deployed into it, so no mistake there), but the second time it fails with

`"Error: cannot re-use a name that is still in use"`

The first install runs flawless, it's the subsequent ones that fail. I am using helm version:
```
Client: &version.Version{SemVer:"v2.7.0-rc1", GitCommit:"1eff362941a349ab577c356f037ee093b23767a7", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.0-rc1", GitCommit:"1eff362941a349ab577c356f037ee093b23767a7", GitTreeState:"clean"}
```

**Comment by splisson-altair** [comment]
workaround: helm upgrade --install

**Comment by Morriz** [comment]
Ah, yes, tnx. I saw that somewhere. Which is the real problem: where can I read about deploying helm packages idempotently with the same command. It's not in the documentation.

Is anybody reading this with the know how to edit the docs about this? I suspect ppl are losing time finding out about this, like me.

**Comment by bacongobbler** [comment]
@Morriz the documentation is available [in the docs/ section](https://github.com/kubernetes/helm/tree/master/docs) of the codebase. If you file a PR to amend the documentation, https://docs.helm.sh/ will be updated.

**Comment by Morriz** [comment]
Tnx, but maybe somebody else can edit the docs, as I obviously don't have the expertise ;p

**Comment by bacongobbler** [comment]
looks like @splisson has already done the work in #3148. :)

**Comment by Morriz** [comment]
Yes, but imo these intructions should come as close to, or even replace the original instructions in ‘using helm’, because I think helm should advocate a stateless approach. As such it would be wise to support the majority of users that prefer the 12 factor approach, who steer away from unrepeatability. That point is more important than just this doc update...

**Comment by atombender** [comment]
We are getting this with 2.8.2 when using `upgrade --install`. Regression?

```
$ /usr/local/bin/helm --kube-context t11e-gke upgrade ftp-server-production --values values.yml --timeout 300 --namespace=production --wait --install --force 
Error: UPGRADE FAILED: cannot re-use a name that is still in use

$ helm ls ftp-server
NAME                 	REVISION	UPDATED                 	STATUS  	CHART           	NAMESPACE
ftp-server-production	9       	Thu Mar 22 17:25:10 2018	DEPLOYED	ftp-server-0.0.1	production
```

**Comment by splisson-altair** [comment]
does it work if you specify the release name:
helm upgrade ftp-server-production --values values.yml --timeout 300 --namespace production --wait --install --force ftp-server-production

**Comment by atombender** [comment]
Unfortunately, I deleted the release as there was some urgency involved. (Of course, this caused me bunch of extra work, since I now had to reattach a PVC and load balancer manually etc., since Helm doesn't seem to have a way to remove a release but preserve the current resources. Ugh.)

I tried manually rewriting history by deleting the configmap corresponding to the release and restarting Tiller. I also tried a rollback, which worked, but the next deploy failed with the same error.

How does specifying the release name affect things? Doesn't it just default to what's in `Chart.yaml`?

**Comment by atombender** [comment]
@splisson-altair Actually, I see now that we do pass both the release name and the chart path. Not sure why that didn't get included in my paste. (Will edit.)

**Comment by splisson-altair** [comment]
usually if I have some issue like that with a release, I do: helm delete <release> --purge

**Comment by atombender** [comment]
That's what I did. This is highly desirable, as it deletes some state such as the connection between services and load balancers, or PVCs with their PVs.

**Comment by atombender** [comment]
I'm getting this on a lot of deploys now. Until this is fixed, is there a temporary workaround *aside* from `helm delete --purge`?

**Comment by atombender** [comment]
Note this is currently happening for a deploy that is currently in the `DEPLOYED` state. The one I pasted about above was stuck in `PENDING_UPGRADE`. So it seems unrelated to status.

**Comment by atombender** [comment]
@technosophos Any progress on this? It's hitting us in production, where we can't just `helm del --purge` stuff that in use, like statefulsets that need to be carefully managed.

**Comment by bacongobbler** [comment]
I'm sorry! We simply haven't had the time to look into your issue in particular. If you have a patch, we'd happily look into it. :)

**Comment by atombender** [comment]
I don't even know what's causing it. What is happening that's making it consider a name to be "in use"?

**Comment by atombender** [comment]
I've noticed a couple of times now that the error shows up if I have something invalid (e.g. reference to a variable that has a typo) in the chart, and goes away if I fix the error. It looks a lot like Helm is masking the underlying linting error, and emitting the `cannot re-use` error instead. I didn't realize this earlier because the workflow was using did not lint the charts beforehand,

**Comment by juliohm1978** [comment]
Thumbs up to @atombender for the tip. Helm is **really** misleading with the error message. My underlying chart template evaluated to a Yaml with indententation errors and helm spits out this exact message:

```
Error: UPGRADE FAILED: cannot re-use a name that is still in use
```

Fixing my chart template got rid of the problem. Thank God I can `helm template` to view the processed yaml created by the template to check for errors.

**Comment by atombender** [comment]
I strongly recommend running all charts through `helm template` and then taking the output through `kubectl apply --dry-run`, which acts as a linter. This is how I discovered the problem; we have an internal tool that wraps Helm and does this automatically now.

**Comment by worldofprasanna** [comment]
We also got the same `Error: UPGRADE FAILED: cannot re-use a name that is still in use` and we have to delete the release and recreate again.

It would be more helpful if we get the error message because of which this is failing.

**Comment by atombender** [comment]
@technosophos Can we please reopen this? The issue still exists on 2.9.0.

As an aside, I have noticed that sometimes this error occurs even when the manifests don't contain any syntactical or semantic errors. However, since Helm is masking the underlying error, there's no way to tell what's preventing the deploy from working. All that is in Tiller's log is:

```
[tiller] 2018/05/04 15:22:57 getting history for release elasticsearch-production
[storage] 2018/05/04 15:22:57 getting release history for "elasticsearch-production"
[tiller] 2018/05/04 15:22:58 preparing update for elasticsearch-production
[storage] 2018/05/04 15:22:58 getting deployed releases from "elasticsearch-production" history
[storage] 2018/05/04 15:22:58 getting last revision of "elasticsearch-production"
[storage] 2018/05/04 15:22:58 getting release history for "elasticsearch-production"
[storage] 2018/05/04 15:22:58 getting release history for "elasticsearch-production"
[tiller] 2018/05/04 15:22:59 failed update prepare step: cannot re-use a name that is still in use
```

**Comment by atombender** [comment]
FWIW, another workaround is to patch the last configmap, changing the label `STATUS` to `DEPLOYED`.

**Comment by technosophos** [comment]
Re-opening this issue, as it has re-appeared in 2.9.0

**Comment by atombender** [comment]
@technosophos Cool. We're still on Kubernetes 1.8 (though I'm personally using `kubectl` 1.9). Is the regression you found only against 1.9?

**Comment by technosophos** [comment]
It's in the client library. So it would happen on any Kubernetes server version.

At this point we're pretty confident that it has to do with the missing validation. PR is is #4042.

**Comment by so0k** [comment]
I'm still getting this error on Helm 2.9.1:

```
$ helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

I'm using the following chart - https://github.com/so0k/flask_app_k8s/tree/master/chart/flask-app

How to reproduce:

```
$ helm upgrade --install --set image.tag=master test chart/flask-app/
Release "test" does not exist. Installing it now.
NAME:   test
LAST DEPLOYED: Mon May 28 18:21:34 2018
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/ConfigMap
NAME            DATA  AGE
test-flask-app  1     0s
...
```

Running helm upgrade with `--reuse-values` flag hits this error
```
$ helm upgrade --force --reuse-values --timeout 300 test chart/flask-app/
Error: UPGRADE FAILED: cannot re-use a name that is still in use
```

But without the `--reuse-values` flag, there is no error
```
$ helm upgrade --force --timeout 300 test chart/flask-app/
Release "test" has been upgraded. Happy Helming!
LAST DEPLOYED: Mon May 28 18:22:40 2018
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/ConfigMap
NAME            DATA  AGE
test-flask-app  1     1m
...
```

**Comment by so0k** [comment]
@technosophos - should I create a new issue for my previous comment?

**Comment by pv93** [comment]
This is broken for us:
```
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
```

Looks like it only happens when we use --reuse-values as well

**Comment by txomon** [comment]
So it has happened to me whlle developing a chart, I added a PVC. The change was really small, so I started to add changes one by one, trying to see what was going wrong.

I am using [helmsman](https://github.com/Praqma/helmsman), and this happened many times during development.

It seems to me that this gets triggered when there is an invalid template. In my case, running `helm template -f values.yaml` was giving me `Error: rendering template failed: assignment to entry in nil map`.

In my specific case, I am using the common chart as templating helpers, and the docs describe wrong how to usa of the template, causing the previous error. More specifically, they document the use of the PVC as follows:

```
{{- template "common.persistentvolumeclaim" (list . "pypicloud.persistentvolumeclaim") -}}
{{- define "pypicloud.persistentvolumeclaim" -}}
{{- end -}}
```

However this makes the template "pypicloud.persistentvolumeclaim" have a nil value when read as YAML. One way I have found to overcome this is by overwriting the same way a known value:

```
{{- template "common.persistentvolumeclaim" (list . "pypicloud.persistentvolumeclaim") -}}
{{- define "pypicloud.persistentvolumeclaim" -}}
metadata:
  name: {{template "common.fullname" .}}
{{- end -}}
```

**Comment by iomv** [comment]
It happens to me as well on k8s 1.9.7 and helm 
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```
It is really annoying because I cannot figure out what is causing it

**Comment by elchtestAtBosch** [comment]
I also ran into the masking problem. Is it possible to fix it and make Helm show the actual problem in the error message.

**Comment by joshwand** [comment]
same here - templating error hidden by incorrect error message. suggest renaming the issue to reflect the actual bug? or should we split and create a new one?

**Comment by juliohm1978** [comment]
Can't the title be edited? Either way, the ißue does need to be addressed.

**Comment by 27Bslash6** [comment]
^ Agreed. This issue is still present and still a problem that I have to workaround on a regular basis by deleting and redeploying released.

It's also not a support question, this is a bug.

**Comment by remcohaszing** [comment]
I keep running into this issue.

`helm upgrade --install` works for me, but actually I need to use `helm install --replace`, because I want to fully reset my installations for review environments.

I read a lot of comments that this error really just hides a template issue, but I don’t think this is the issue for me, since `helm upgrade --install` works.

Is `helm install --replace` really broken or could there be something wrong with my own setup after all?

**Comment by bacongobbler** [comment]
Is this issue still present on more recent versions of Helm 2 (e.g. 2.14.3)?

@juliohm1978 what would you suggest we change the title to?

**Comment by hazim1093** [comment]
Just for info, I got this error when using helm client v2.11.0 to deploy to a tiller v2.16.3. 
Updating the client to v2.16.3 solved it

**Comment by makhijamanish** [comment]
> I keep running into this issue.
> 
> `helm upgrade --install` works for me, but actually I need to use `helm install --replace`, because I want to fully reset my installations for review environments.
> 
> I read a lot of comments that this error really just hides a template issue, but I don’t think this is the issue for me, since `helm upgrade --install` works.
> 
> Is `helm install --replace` really broken or could there be something wrong with my own setup after all?

helm  install --replace worked for me

**Comment by mahesheBen** [comment]
Try the helm uninstall --releasename command and then do the helm install. It worked for me in Helm 3.4

**Comment by K1ngram4** [comment]
> I keep running into this issue.
> 
> `helm upgrade --install` works for me, but actually I need to use `helm install --replace`, because I want to fully reset my installations for review environments.
> 
> I read a lot of comments that this error really just hides a template issue, but I don’t think this is the issue for me, since `helm upgrade --install` works.
> 
> Is `helm install --replace` really broken or could there be something wrong with my own setup after all?

`helm install --replace`it works,good job

**Comment by GoingMyWay** [comment]
Hi, is there any official workaround to fix this issue?  This answer help me: https://stackoverflow.com/a/70465191/5046896

**Comment by GoingMyWay** [comment]
Another workaround is to delete the corresponding namespace and then create a new one. For example deleting the namespace `kuberhealthy`:

```
helm ls --all-namespaces
kubectl delete namespace kuberhealthy
kubectl create namespace kuberhealthy
```

**Comment by samos123** [comment]
Deleting the namespace isn't an option if this happens on the default namespace. I'm having a similar issue where my helm install returned an error and then helm uninstall also errored. Now the release is gone but Helm seems to think it's still there.

**Comment by cooervo** [comment]
I was getting this error due to trying to install istio in a cluster with already istio installed had to connect to the correct cluster then it worked

**Comment by mausch** [comment]
This is still an issue, please reopen. At the very least the error message needs to be improved.
I just got it, `helm list -A` didn't list the offending chart and deleting the namespace isn't always an option.
I tried all the flags mentioned here, none of them worked.
I worked around it by manually deleting all related resources and importantly also the helm secret for the release (the one with type `helm.sh/release.v1`)
