### ISSUE TITLE
[Proposal] Helm Upgrade (Tiller) to perform Automatic rollback?

### ISSUE THREAD

**Issue by dhilipkumars** [helm/helm#3149]
As you all might know the concept of "rollback" itself is removed from deployment (the only core controller that supported it) and the community is in favor of supporting rollback at the higher layer such that the declarative model is not broken by kubernetes.

Ref: https://github.com/kubernetes/kubernetes/issues/23211

Chart is an excellent library of actual applications that can be quickly installed in kubernetes,  one more great aspect about chart is that it's versioned.

There is a `helm upgrade` command (even though i have not tried it myself) assume that it automatically triggers kubernetes rolling updates for those controllers that support it. (if helm upgrade changes the podspec such as images etc.,)

How about introducing an option `--autorollback` to `Helm Upgrade` sub-command such that if the upgrading version fails Helm (Tiller) would automatically retain/rollback to the current version? 

The declarative model is kept intact as chart releases are versioned?   Or is it still the same problem? 

I cant think of a better place for a feature like automatic rollback in our eco-system.  Please let me know your thoughts.

There has been some discussion around it already in the below reference. 

Ref: https://github.com/kubernetes/helm/issues/1796

**Comment by dhilipkumars** [comment]
cc @kubernetes/helm-maintainers

**Comment by bacongobbler** [comment]
This might be a problem if we decide to move forward with a more declarative model for Helm 3 as seen in #3089.

I don't see a problem if someone wants to implement it for Helm 2, but that workflow may be something that may not get ported over if we decide that we want to move Helm to a more declarative model in the future (read: this may not port over to Helm 3 in that case).

**Comment by dhilipkumars** [comment]
@bacongobbler Good to know this can go in Helm 2.0 for starters.

I would like to know how would this can be a problem with declarative model? Every release is versioned plus the concept of `rollback` is already supported by Helm? We are only going make this automatic when the `upgrade` fails? 

Or should this behaviour be declared in one of the chart's yaml file rather than being a sub-command?  Like the upgrade sequence? Like what is the order the charts need to be upgraded? a chart could have multiple components like deployments, statefulsets etc., 
And what should happen if the upgrade fails? Keep trying or rollback? (these were discussed as rollback statergy for core-controllers too)

**Comment by mcwienczek** [comment]
+1 for this. I've seen many times that deployment has failed because of wrong application configuration or implementation and the only thing that saved us were old replicas of the application still running.

**Comment by seancurran157** [comment]
+ 1

**Comment by distorhead** [comment]
+1

**Comment by larsha** [comment]
@distorhead That is not working correctly. If your last deploy is marked as failed (as it will be if you have one failed deploy) your command will be empty. I would use something like this:

```last_deployed_release=$(helm history "${RELEASE_NAME}" --max 20 | grep DEPLOYED | head -n1 | awk '{print $1}')```.

**Comment by distorhead** [comment]
@larsha 

If you have a single failed release revision, then you have to purge it, because there are no revisions to rollback to.

Otherwise release is supposed to always be in the DEPLOYED state, because either previous helm install/upgrade succeeded or there was an rollback.

So commands are working correctly, no need to get release history.

**Comment by larsha** [comment]
@distorhead Ah my bad, missed you are getting the last deployed release before actually doing the helm install/upgrade!

**Comment by distorhead** [comment]
There is another way to make autorollback: rollback on the next run, before upgrade. That way user have a chance to inspect errors and cluster state after failed upgrade.

```
    - export namespace=myns
    - export releaseName=myrelease
    - export lastReleaseStatus=$(helm list $releaseName -dr --output json | jq -r .Releases[0].Status)
    - |
        if [ "x$lastReleaseStatus" == "xFAILED" ] ; then
          export lastDeployedReleaseRevision=$(helm list $releaseName --deployed -dr --output json | jq -r .Releases[0].Revision)
          if [ "x$lastDeployedReleaseRevision" != "x" ] ; then
            helm rollback $releaseName $lastDeployedReleaseRevision
          fi
        fi
```

New `--atomic` option (https://github.com/helm/helm/pull/5143) from 2.13.0 performs rollback in the first variation: immediately after failed deploy.

**Comment by bacongobbler** [comment]
`--atomic` rolls back the release when an upgrade fails. See #5143 and #6011. Closing!
