### ISSUE TITLE
Feat: Configuration option for tiller probeAddr IP/port.

### ISSUE THREAD

**Issue by libesz** [helm/helm#3159]
Currently the probeAddr listens on *:44135 and [it is not configurable](https://github.com/kubernetes/helm/blob/e8e6ac5d7783808cc0bd1adad053bec339849647/cmd/tiller/tiller.go#L62). Together with the host networking option for tiller, installation gives unexpected external visibility for this listening point for any potential user.
This might have a configuration option, similarly to the [grpcAddr](https://github.com/kubernetes/helm/blob/e8e6ac5d7783808cc0bd1adad053bec339849647/cmd/tiller/tiller.go#L70), or in this case, I would even expect that is can be disabled entirely if not needed.

**Comment by libesz** [comment]
Up!
We would have interest in implementing this. Simply need a thumbs up that it will be accepted as described above.
Thanks!

**Comment by bacongobbler** [comment]
So long as this is configurable through the CLI and documented, I don't see why not. 👍

**Comment by libesz** [comment]
Hey, thanks @gavinmead ! 👍 Fine for us, we deferred the fix for this so it is very welcomed!

**Comment by gavinmead** [comment]
Been crazy busy with work.  I have some free time now.  Apologies for the delay.

**Comment by AlexShemeshWix** [comment]
Any update on this issue? I really need it.

**Comment by mumoshu** [comment]
#5557 partly address this

**Comment by mumoshu** [comment]
#5561 resolves this
