### ISSUE TITLE
Helm cannot install a namespace template

### ISSUE THREAD

**Issue by rcorre** [helm/helm#3179]
Helm cannot install the following template:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    foo: {{ .Values.foo }}
  name: {{ .Release.Namespace }}
spec:
  finalizers:
  - kubernetes
```

The problem is acknowledged in [this comment](https://github.com/kubernetes/helm/issues/2853#issuecomment-325366436), but the OP was a little different from this. In my case, the namespace does not exist prior to `helm install`. However, helm (presumably) creates the namespace first, then tries to run the template, and bails out claiming the namespace already exists (even though it was the one that created it). My use case is modifying the annotations on my namespace during `install`/`upgrade`

`helm upgrade` actually _does_ work:
```sh
# namespace doesn't exist
[rodencor@heredesk mychart]$ kubectl get ns ryan-namespace
Error from server (NotFound): namespaces "ryan-namespace" not found

# install fails
[rodencor@heredesk mychart]$ helm install . --name ryan-namespace --namespace ryan-namespace
Error: release ryan-namespace failed: namespaces "ryan-namespace" already exists

# but upgrade succeeds!
[rodencor@heredesk mychart]$ helm upgrade ryan-namespace . --set foo=baz
Release "ryan-namespace" has been upgraded. Happy Helming!
LAST DEPLOYED: Tue Nov 21 13:34:20 2017
NAMESPACE: ryan-namespace
STATUS: DEPLOYED

RESOURCES:
==> v1/Namespace
NAME            STATUS  AGE
ryan-namespace  Active  56s


[rodencor@heredesk mychart]$ kubectl get ns ryan-namespace -ojsonpath='{.metadata.annotations}' && echo
map[foo:baz]
```

**Comment by jdolitsky** [comment]
+1

**Comment by jascott1** [comment]
Hi @rcorre 

You are correct in that helm is first creating the namespace for the release you are creating with `--namespace` and then it tries (and fails) to create the same namespace from the manifest which you have given the same name `{{ .Release.Namespace }}`. Im not sure there will be another solution other than using `helm upgrade` as you have described or possibly `helm install --upgrade`.

**Comment by rcorre** [comment]
Could helm detect if the release namespace is provided as a template and not create it? Or take an `InstallOption` to avoid creating a namespace (though it would have to instantiate `Namespace` templates before other templates)?

**Comment by unguiculus** [comment]
I came across this myself just recently. We deploy every pull request of our app into its own namespace. I wanted to manage this with the chart so the namespace is automatically created upon deployment and deleted upon undeployment. It had to fail and I found out why digging into the sources. 

What's the reason the namespace is auto-created? While kubectl would fail, Helm does some magic behind the scene. Why not make Helm fail as well?

**Comment by jascott1** [comment]
Currently everything in the chart is in a single namespace. If we supported namespace manifests I would think we would want to support multiple namespaces, making auto detection tricky. Not to blindly defer this but it might be a good candidate to bring up for 3.x.

**Comment by sheerun** [comment]
A huge pain is inability to specify namespaces to deploy to in values.yaml

I also deploy servies per-namespace and ideally there should special or not-so-special key in values.yaml that specifies to which namespace deploy all resources by default. Something like:

```
__namespace: my-project
```

so I don't need special handling for passing appropriate --namespace to helm upgrade

**Comment by blandman** [comment]
> A huge pain is inability to specify namespaces to deploy to in values.yaml
> 
> I also deploy servies per-namespace and ideally there should special or not-so-special key in values.yaml that specifies to which namespace deploy all resources by default. Something like:
> 
> ```
> __namespace: my-project
> ```
> so I don't need special handling for passing appropriate --namespace to helm upgrade

Is this still true? I would love to have this functionality.

**Comment by col** [comment]
I would also love to be able to specify the namespace to deploy to within the `values.yaml` file.

**Comment by bacongobbler** [comment]
Fixed in Helm 3 now that Helm no longer creates the namespace as part of `helm install --namespace`.
