### ISSUE TITLE
Test pod not deleted with helm.sh/hook-delete-policy

### ISSUE THREAD

**Issue by unguiculus** [helm/helm#3211]
I have a chart with tests. The test pod is annotated as follows:

```yaml
annotations:
    helm.sh/hook: test-success
    helm.sh/hook-delete-policy: hook-succeeded
```

I would expect the pod to be deleted once the test has run successfully. This is, however, not the case.

```
$ helm version
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
```

**Comment by jroucheton** [comment]
Hi,

I have the same kind of issue.
I defined the following job:

`apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}
{{ include "{{ .Chart.Name }}.labels" . | indent 2 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
.......`

But even if this job has been executed with success, this one is still created....

Regards,

**Comment by unguiculus** [comment]
@jroucheton My issue is specifically about tests. For other hooks `helm.sh/hook-delete-policy` works as expected for me.

**Comment by ericleu** [comment]
Any update on this issue?  I am experiencing the exact same issue.  Test pod not deleted after success result.

**Comment by natcho** [comment]
I have also observed this issue.

**Comment by bacongobbler** [comment]
re-labeling as a feature if someone wants to tackle this!

**Comment by rrpolanco** [comment]
FWIW I've been able to work around this by telling `helm test` to clean up after itself via `--cleanup` flag.

**Comment by jlegrone** [comment]
This should be closed by https://github.com/helm/helm/pull/6054.
