### ISSUE TITLE
Helm should allow easier "management" of child charts placed manually in `charts`

### ISSUE THREAD

**Issue by omkensey** [helm/helm#3221]
I have a PR (kubernetes/charts#1719) that uses two subcharts, with a `requirements.yaml` to make it easy to choose whether one or the other is not deployed.  Currently the acceptance test is failing because it does `helm dep up` before trying to install the chart, and with no `repository` line in requirements.yaml `helm dep up` fails.  Declaring the "local" repository causes `helm dep up` to fail a la #2887.  I could eliminate the use of `requirements.yaml` but then I'd have to wrap every template in an `{{- if foo.enabled }}` block, which seems inelegant at best.

It may seem nonsensical to have the source repo be the `charts` directory but in my case it's the direct result of these constraints:

* using subcharts
* wanting to allow subcharts to be turned on or off independently
* wanting that to be easy to maintain

I propose one of the following two fixes:

* `helm dep up` ignores dependencies that have no repo declared instead of throwing an error
* if `helm dep up` sees a dependency source URL that resolves to the `charts` directory of the installing chart, it does not try to download the dependency but checks that it is already present and meets any declared constraints like version requirements, erroring only if those checks fail.

**Comment by jascott1** [comment]
@omkensey Thanks for brining this up. IIRC when using `file://` and `helm dep up` it does not update dependencies, is that your experience? We might consider fixing `file://` for `charts/` dir as you said so that it works but does not update.

**Comment by omkensey** [comment]
It looks like it tries to update, but fails.  I'm getting the same behavior as issue #2887.

**Comment by balboah** [comment]
I like the local charts dir requirement suggestion

**Comment by technosophos** [comment]
> `helm dep up` ignores dependencies that have no repo declared instead of throwing an error

That makes sense to me. I would call the current behavior a bug.

After looking a bit at how things are, I also agree with @balboah that we need to improve the way that the `file://` charts are handled in requirements.txt. The two pieces of code that are in conflict in this issue were developed independently (at about the same time), and I think we just need to do a little upkeep to make the experience more consistent.

Because of the error message, I am re-marking this as a bug.
