### ISSUE TITLE
Unable to --set with spaces or newlines

### ISSUE THREAD

**Issue by sathieu** [helm/helm#3251]
I'm trying to do:
```
helm upgrade kubernetes-dashboard stable/kubernetes-dashboard --reuse-values \
  --set 'ingress.annotations.nginx\.ingress\.kubernetes\.io/configuration-snippet=allow 10.20.30.40;\ndeny all;'
```

It doesn't work:
```
Error: This command needs 2 arguments: release name, chart path
```

NB I tried a lot of other things without success

**Comment by bacongobbler** [comment]
Does escaping the whitespace work? e.g.

```
--set 'ingress.annotations.nginx\.ingress\.kubernetes\.io/configuration-snippet=allow\ 10.20.30.40;\ndeny all;'
```

**Comment by sathieu** [comment]
All three commands returns:
```
Error: This command needs 2 arguments: release name, chart path
```

**Comment by sathieu** [comment]
My bad. I had an error in my shell (which export http_proxy var then call the helm binary). I replaced ```$*``` by ```"$@"```.

No the results are:
```
kubectl get ing -n kube-system kubernetes-dashboard-pp-kubernetes-dashboard -o yaml
[...]
    nginx.ingress.kubernetes.io/configuration-snippet: allow 10.20.30.40;ndeny all;
[...]
    nginx.ingress.kubernetes.io/configuration-snippet: '"allow 10.20.30.40;ndeny all;"'
[...]
    nginx.ingress.kubernetes.io/configuration-snippet: '"allow 10.20.30.40;ndeny all;"'

```

So \<something> is always replaced by <something> (unless something is in ```= , . }```).

I will propose a PR.

**Comment by marcellodesales** [comment]
@sathieu Same problem here... I had to use `\\n\\` in place of a space.

```
helm install --dry-run --debug --namespace d8b21ce --name d8b21ce --set replicaCount=3 --set ingress.enabled=true --set ingress.hosts={d8b21ce-api.config-reference.a.company.com} --set ingress.annotations={kubernetes.io/ingress.class:\\n\\nginx} config-service
```

**Comment by Kemyke** [comment]
This answer helped me to solve this issue: https://stackoverflow.com/a/48551402/5506379

**Comment by jonathanjfshaw** [comment]
I'm finding this bizarrely hard:

This works:
```
helm template mychart --set myvalue='some value'
```
Nothing like this does:
```
export TEST="--set myvalue='some value'" && helm template mychart $TEST
```

No matter what value I try to use for 'some command', it does not get passed in properly if it has a space. Nothing I try works; not single quotes, backslashes, nothing. Just the part of the value before the space gets passed into the template.

**Comment by lapcchan** [comment]
> I'm finding this bizarrely hard:
> 
> This works:
> 
> ```
> helm template mychart --set myvalue='some value'
> ```
> 
> Nothing like this does:
> 
> ```
> export TEST="--set myvalue='some value'" && helm template mychart $TEST
> ```
> 
> No matter what value I try to use for 'some command', it does not get passed in properly if it has a space. Nothing I try works; not single quotes, backslashes, nothing. Just the part of the value before the space gets passed into the template.

i have the same problem too, any workaround?

**Comment by bacongobbler** [comment]
Answered in https://github.com/helm/helm/issues/4504#issuecomment-440416138. Closing.

**Comment by tomislater** [comment]
It is not answered.

If you try something like that:
```
FLAGS="--set something.command='npm command'"; helm upgrade --install --debug --dry-run micro micro-chart $FLAGS
```

You got errors like that:
```
Error: unknown flag: --set something.command
helm.go:81: [debug] unknown flag: --set something.command
```

**Comment by tomislater** [comment]
@lapcchan You can try:
```
export TEST=--set=myvalue="some value" && helm template mychart "${TEST}"
```
