### ISSUE TITLE
Helm 3: Separate concerns within Helm 

### ISSUE THREAD

**Issue by bgrant0607** [helm/helm#3255]
For the record...

Previously discussed here:
https://groups.google.com/d/msg/kubernetes-sig-apps/71c1FHem3-Y/i-ue6oWADQAJ

Helm provides multiple high-level functions, such as: 
1. Package management -- search, browse, bundle, push, and pull of off-the-shelf application packages and their dependencies.
2. Application lifecycle management -- install, delete, upgrade, rollback -- and pre- and post- hooks for each of those lifecycle transitions, and success/failure tests.
3. Configuration customization via parameter substitution, aka template expansion, aka rendering.

It's useful for Helm to provide an integrated framework for the 3 functions, but a number of users would also like them to be independently usable. 

For instance, some want to pull a package and use another workflow to manage the application. Others want to use a different customization strategy than gotpl, without sending a PR to Helm to add another renderer. Some want to use gotpl for their own apps, but without the package management and app lifecycle managment. Others may want to use the package management for package discovery, but use git for version management and Operators for lifecycle management. (AIUI, using the app lifecycle management and configuration customization without package management is already supported.)

In https://github.com/kubernetes/helm/issues/2577#issuecomment-341854344, I suggested extracting substitution/expansion into external plugins.

**Comment by bgrant0607** [comment]
My extended Helm summit presentation deck on this topic:
https://docs.google.com/presentation/d/10dp4hKciccincnH6pAFf7t31s82iNvtt_mwhlUbeCDw/edit#slide=id.p

**Comment by davidewatson** [comment]
I would also like to use `kustomize` with the application lifecycle management provided by `helm`. Some of this is possible now with `helm` v2 using scripts and CI, though the operator model described for [`helm` v3](https://github.com/helm/community/blob/master/helm-v3/008-controller.md) would be more flexible, in part because, the relative uniformity of declarative k8s resources makes them good for building and composing automation.

**Comment by pinkavaj** [comment]
Might be related to #5276

**Comment by bacongobbler** [comment]
One of the approaches we tried with Helm 3 was to expose a Go SDK which users can try out and re-implement certain parts of Helm's functionality. For those interested, have a look at [pkg/action on godoc.org](https://godoc.org/github.com/helm/helm/pkg/action).

While we are not planning to split up the Helm codebase into separate plugins (that would be a maintenance nightmare on both our end as well as others'), community members are more than welcome to re-implement chunks of Helm using these packages similar to the `cmd` package.

Thanks!
