### ISSUE TITLE
Bug/Feature Request: suppress requirements.lock generated timestamp

### ISSUE THREAD

**Issue by jgiles** [helm/helm#3267]
Checking in requirements.lock files is a great way to make package generation reproducible.

However, the `generated:` timestamp leads to unnecessary changes in requirements.lock files when invoking `helm dep update`. These changes tend both to obscure the important differences in lock file deltas (the changed subchart versions) and to cause unnecessary merge conflicts in version control.

In the degenerate case where none of the dependency versions are changed, 'helm dep update' will generate a lock file identical except for the timestamp. I'm uncertain whether this last behavior holds when updating a lock file in place (I'm seeing https://github.com/kubernetes/helm/issues/2731, so am always deleting and re-generating the lock file).

Notably, the other mainstream dependency-lock file formats I'm familiar with (e.g. `Gopkg.lock`) do not include a generation timestamp. Same dependency versions -> same lock file is a useful property.

**Proposal**: Add a `--no-stamp` flag for `helm dep update` which suppresses the generated timestamp. Or just eliminate the timestamp entirely, but perhaps that is too large a change.

In the meantime, would manually stripping out the timestamp be likely to break things? A quick examination of the helm codebase suggests that the timestamp is written but never actually read and used.

**Comment by jgiles** [comment]
/remove-lifecycle stale

If the proposal is acceptable, we would be happy to implement it.

**Comment by bacongobbler** [comment]
closing as inactive.
