### ISSUE TITLE
Release new tiller docker image on arm64

### ISSUE THREAD

**Issue by kevin-zhaoshuai** [helm/helm#3269]
Now tiller image only support X86_64.
https://console.cloud.google.com/gcr/images/kubernetes-helm/GLOBAL/tiller
Do we plan to release tiller image for other architecture?
Tiller image is an essential image for helm user, we need it in project "Kolla-kubernetes".
If you don't have a machine on arm64, we linaro can help to build it.

**Comment by vielmetti** [comment]
Second this proposal, and the Works on Arm project also would have an arm64 system to provide for the task of testing and CI. http://github.com/worksonarm/cluster

**Comment by vielmetti** [comment]
There was a discusssion of this on the Kubernetes #helm-users Slack channel, at https://kubernetes.slack.com/archives/C0NH30761/p1521144772000010 with @technosophos and @mattfarina . Hoping to get this work in scope for a future release.

**Comment by kevin-zhaoshuai** [comment]
@vielmetti Great! I appreciate your work

**Comment by gaozhangfei** [comment]
@vielmetti does https://github.com/jessestuart/tiller-multiarch will be merged in tiller master branch?
Tiller v2.9.1 seems still does not support arm64

**Comment by bacongobbler** [comment]
@gaozhangfei see https://github.com/kubernetes/helm/pull/4200

**Comment by gaozhangfei** [comment]
Thanks @bacongobbler
That's great, will it be appeared at tiller v2.9.2 version? 
Can't wait to have a try :)

**Comment by bacongobbler** [comment]
It will not. See my updated comment + the comments in that thread. Basically there's a few things blocking that section of work.

**Comment by michael-robbins** [comment]
Where did we get with this? Been 6+ months...

**Comment by bacongobbler** [comment]
https://github.com/helm/helm/pull/5039

**Comment by bacongobbler** [comment]
Closing for the same reasons in https://github.com/helm/helm/pull/2649. For posterity:

As per [the announcement on the mailing list](https://lists.cncf.io/g/cncf-helm/topic/last_v2_feature_release/34301238), Helm 2.15.0 is the last release where we will be merging new features for Helm 2. Tiller has been removed in Helm 3 so I don't see us moving forward with this proposal, so I'm going to close this as something we do not plan to merge in the 2.15 timeframe.

That being said, the [tiller-multiarch](https://github.com/jessestuart/tiller-multiarch) project has been providing amd64 tiller images for Helm 2, so I'd suggest focusing efforts on that project going forward. Thanks!
