### ISSUE TITLE
[Proposal] `helm test` should perform automatic cleanup (pre-test)

### ISSUE THREAD

**Issue by particledecay** [helm/helm#3279]
Currently, executing the `helm test` command runs a number of defined test pods and returns while not removing any of those pods. This is desirable if you need to inspect a pod to find out why a particular test failed. However, when you attempt to run the tests again against the same release, you will inevitably encounter the dreaded `ERROR: pods "awesome-shark-test" already exists`.

Enter the `--cleanup` flag, which was introduced to fix this issue. However, this only works _as part of a test run_. That means that the cleanup happens immediately following the test completion. Unfortunately, you will not be able to inspect any failed pods. You can't know ahead of time whether all your tests will pass (otherwise what's the point of tests? :smile:)

*I think the more appropriate behavior would be to remove pods either as part of a new run or when explicitly told to do so.*

I didn't want to work on this and then submit a PR only to have it shut down, so I thought I'd open it up for discussion first. I believe there are two good approaches here:

1. Change the behavior of `--cleanup` - this flag would now mean "remove any existing pods if one already exists." This creates a new issue: backwards compatibility (v3?)
2. Add a new command - something like `autoremove` (a la apt) or just a new `cleanup` command, which would generically mean "remove any artifacts that are leftover from operations on the chart."

I'd lean toward option 2, especially since many other package managers out there take this approach.

**Comment by kjbflood** [comment]
I'd suggest that "help test <release>" should clean up, then run the tests. That way, you'd always have the pods to review until you ran the tests again, at which stage, you want to see the current status anyway and may not care about previous results.

**Comment by TheRealJoeLinux** [comment]
@kjbflood if there is no need for backwards compatibility, then I agree with you. If you're running `helm test` then you want to run tests... the conflict with existing pods is a Kubernetes-specific restriction and shouldn't prevent actions performed on explicitly transitory workloads like tests.

**Comment by jeffery-do** [comment]
I second the idea of having a flag such as `helm test --autoremove` which remove duplicate test pods, and waits for them to exit before continuing.
To me, it seems like anyone who uses helm test in a CI/CD pipeline would need to write a script to do this, unless this is implemented as a flag.

**Comment by pvalsecc** [comment]
Or leave the behavior as is and introduce and option to dump the logs of the failing pods.

**Comment by franck102** [comment]
The default behavior should be to cleanup all test pods, and to print their logs to stdout.
There is no reason for helm polluting the namespace with test pods; and the logs are useful whether the test passed or not, this allows success messages more useful than "PASSED: xxx-foo-test"

**Comment by hickeyma** [comment]
Hey @michelleN, you mentioned at the last dev call that you have WIP around Helm test. It would be great if you could reference it here so we can continue the discussion. Thanks.

**Comment by michelleN** [comment]
here is the proposal for helm test in v3 which will have subcommands under the top level `helm test` command to help with things like cleanup https://github.com/helm/community/pull/40

**Comment by seb-pereira** [comment]
Hi,

Sorry to comment late in the game, but I recently faced a use case that does not seem to be handled (unless I missed something) in current spec described in https://github.com/helm/helm/issues/3279#issuecomment-456004890).

**Use case**: 
deployment is automated and considered successful when `helm install --wait [...] && helm test [...]` succeeds.
- if deployment ok: test pods should be removed (we do not want test pod to remain in a production env)
- if deployment fails due to tests not passing: failed test pods should not be deleted, in order to investigate pods logs.

**Comment by bacongobbler** [comment]
This has now been implemented in Helm 3. Test hooks can have the `hook-deletion-policy` annotation attached where it will clean itself when the tests succeed, similar to other hooks. See #6054 for more info.
