### ISSUE TITLE
Create a new "post-ready" hook

### ISSUE THREAD

**Issue by particledecay** [helm/helm#3282]
The `post-install` hook is used to run tasks that happen basically as soon as the `helm install` command returns. If you add the `--wait` flag, helm essentially "hangs" until (I believe) at least one of each resource is in a running/ready state. But that also means that you can't get your prompt back until that happens (go ahead and try deploying an elasticsearch chart and see how long it takes you).

I'd like to open a discussion around a new `post-ready` hook, that would be triggered by the same conditions as the `--wait` flag. IOW, you don't have to hang to get your prompt back just to run a task that you expect to run once you have enough running resources.

A few use cases off the top of my head:

- creation of an elasticsearch index after the cluster has initialized
- syncing users/groups after an IPA service has initialized
- sending an alert/slack notification once a service is ready
- copying data to/from a service
- restoring a database

I recognize there are a few things to consider right off the bat:

- if you get the prompt back, that means some process needs to exist asynchronously to "trigger" the annotated resource
- if the `helm install` command returns but there is a post-ready resource waiting to run, how do you display/track those?

**Comment by stealthybox** [comment]
This would make this behavior much easier to rely on.
The relationship between `--wait` and `post-install` is pretty obscure.

For anybody looking for the official docs on the existing behavior, it's here:
https://github.com/kubernetes/helm/blob/master/docs/charts_hooks.md#hooks-and-the-release-lifecycle

**Comment by mandrean** [comment]
I was looking for exactly this in the docs but then I found this thread.

A great use-case for a `post-ready` hook would be when you deploy a service using Helm which (when ready) needs to be registered with a 3rd party to properly receive its license registration.

+1

**Comment by cguethle** [comment]
+1 

I have a post-ready configuration container/Job that needs to run /rest calls against the service backed by a pod in the install. Pod needs to be 1/1 Running before the configuration container/Job runs.

**Comment by nicroto** [comment]
+1

**Comment by shettyh** [comment]
+1

**Comment by sprutner** [comment]
+1

**Comment by bymafmaf** [comment]
+1 `post-ready` would be great. Basically checking all the pods' readiness or giving a custom readiness check on the chart would save a lot of time. Right now, I have to have a custom function to wait everything to be ready and then create a job.

**Comment by etos** [comment]
+1

**Comment by Rene-76** [comment]
+1

**Comment by Stolr** [comment]
+1

**Comment by Stolr** [comment]
@mandrean  , Can you give us a little example of what you are doing to bypass this limitation ?

**Comment by stealthybox** [comment]
@Stolr 
From the docs linked here: https://github.com/helm/helm/issues/3282#issuecomment-359030614
> Tiller loads the resulting resources into Kubernetes. Note that if the --wait flag is set, Tiller will wait until all resources are in a ready state and will not run the post-install hook until they are ready.

This is the only helm native workaround I'm aware of -- it does require that the operator is using `--wait`.

In practice I've also prepended loops to the scripts my Jobs to poll the network or k8s API for pre-conditions to make the approach more resilient in the case that the `--wait` flag is not provided.

**Comment by bacongobbler** [comment]
In the interest of preventing spam to users subscribing to this thread, please add a 👍 to the OP instead of commenting "+1". That way we can keep the conversation relevant to the proposal at hand. I've gone ahead and deleted those comments. Thanks! ❤️

**Comment by abdennour** [comment]
While I would like to support this feature by the Helm itself, I am now satisfied with [Helmfile](https://github.com/roboll/helmfile) as it is the executor of Helm on my behalf , and it supports pre & post events.

> presync
> postsync

**Comment by bridgetkromhout** [comment]
Hi, all - Thank you for your ideas to improve Helm. If you'd like, you can submit a Helm Improvement Proposal so as to work in the community to make these ideas a reality: https://github.com/helm/community/blob/master/hips/hip-0001.md - meanwhile, I will close this issue. Thanks!
