### ISSUE TITLE
Helm doesn't cleanup on unsuccessful deployments

### ISSUE THREAD

**Issue by nmiculinic** [helm/helm#3338]
After encountering an error during install/upgrade helm doesn't clean after itself (that is operation isn't atomic), which forces me to clean manually each time during testing. Also, that deployment name isn't registered, thus I cannot use ```helm delete --purge <name>```

```
~ helm version 
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
```

**Comment by nmiculinic** [comment]
Also this is related to following bug..if the release name has _ in it, things break. (e.g. sss_ss breaks )

**Comment by antoniaklja** [comment]
Would be nice to make helm install/upgrade transactional for entire chart.
Maybe even `--rollback` parameter.

**Comment by nmiculinic** [comment]
/remove-lifecycle stale

Yes, it would be nice. The most common case when an update fails is when cluster IP is changed to NodePort or things like that in services. ((IIRC)). The usual solution is to perform rollback with `--force`

**Comment by dpepper** [comment]
I hit this error frequently. An install fails and then I make some changes to my config and try to install again but hit errors complaining about how many pods/configmaps etc already exist. When you run helm list it doesn't list any failed or successful deployments so then I have to go and cleanup everything manually. If an install fails it should definitely rollback the changes it has already made not leave a half installed helm chart.

**Comment by jibinjohnbabu** [comment]
This issue is frustrating, Why do helm charts gets installed partially ? Any work around commands for this?

**Comment by jibinjohnbabu** [comment]
@ysaakpr 

1. helm install testchart/ --name xyz --> installs with a release name 

if you want to make changes to the release use,

2. helm upgrade xyz testchart/ --> upgrades with the recent changes only

also , below command is useful to delete the full release itself 
3. helm del --purge xyz

--Thanks

**Comment by dpepper** [comment]
@jibinjohnbabu that doesn't work when helm doesn't have a release name and leaves the cluster in an unclean state. Which is what this whole git issue is about.

**Comment by dpepper** [comment]
@bacongobbler why is this labelled as a feature? It's a bug.

**Comment by Stelminator** [comment]
> I hit this error frequently. An install fails and then I make some changes to my config and try to install again but hit errors complaining about how many pods/configmaps etc already exist. When you run helm list it doesn't list any failed or successful deployments so then I have to go and cleanup everything manually. If an install fails it should definitely rollback the changes it has already made not leave a half installed helm chart.

@dpepper is `helm list -a` any better?

**Comment by cleac** [comment]
@michelleN any updates? Have you looked at the [proposal](https://github.com/helm/helm/pull/5143) of resolving this issue? 
I see this one should be implemented for v3 too. So it would great if you give a feedback so I could add possibility of atomic install/upgrade to v3 branch :wink:

**Comment by cleac** [comment]
Well, as far as I understand things, this feature must be ported to `dev-v3` branch. Should it be done related to different issue? Or maybe this one shouls be reopened?

**Comment by thomastaylor312** [comment]
@cleac I think this was more targeted to Helm 2. @adamreese should we put something on the project board?

In the meantime, feel free to work on the port if you were planning on doing so, we won't block opening a PR just because there isn't an issue for it 🙂

**Comment by IdanAdar** [comment]
Can a new status code be added to programmatically know that a chart was reverted? Reporting “1” as before does not provide proper understandings of what that has happened.
