### ISSUE TITLE
Pre-install hook error message. 

### ISSUE THREAD

**Issue by hr1sh1kesh** [helm/helm#3370]
I am trying to develop a Helm chart for an application to ease release management and deployment of the application to kubernetes. In order to do so, i have written a pre-install hook in the Helm chart. 

        apiVersion: batch/v1
    kind: Job
    metadata:
      name: px-etcd-preinstall-hook
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
      annotations:
        "helm.sh/hook": pre-install
        "helm.sh/hook-weight": "-5"
        "helm.sh/hook-delete-policy": hook-succeeded, hook-failed
    spec:
      backoffLimit: 2
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: pre-install-job
            imagePullPolicy: Always
            image: "hrishi/px-etcd-preinstall-hook:v1"
            command: ['/bin/sh']
            args: ['/usr/bin/etcdStatus.sh',"{{ .Values.etcdEndPoint }}"]

This docker container just checks if an ETCD endpoint is accessible or not. Waits for a few seconds and a few tries and then exits 
here is the shell script which runs as part of this container. 

    set -x
    echo "Initializing..."
    svcname=$1
    echo $svcname
    etcdURL=$(echo "$svcname" | awk -F: '{ st = index($0,":");print substr($0,st+1)}')
    echo $etcdURL
    
    response=$(curl --write-out %{http_code} --silent --output /dev/null "$etcdURL/version")
    echo $response
    
    if [[ "$response" != 200 ]]
    then
        echo "Provided etcd url is not reachable. Exiting.."
        exit 1
    fi 

All is well and fine if the ETCD url is accessible, but if the etcd url is inaccessible then I get an error stating `Error: Job failed: BackoffLimitExceeded”`

 I want to check if there is a way of setting a user friendly error message stating that the url isnt accessible or something like that. 
Seems there isnt a way to do it right now, not that i know of. I tried this to just be a `Pod` instead of a `Job` and that doesnt work either. 

Looked up at the docs for Helm but couldnt seem to find any information regarding this.

**Comment by jascott1** [comment]
Hi @hr1sh1kesh 

have you looked into [termination messages](https://kubernetes.io/docs/tasks/debug-application-cluster/determine-reason-pod-failure/) ?

**Comment by hr1sh1kesh** [comment]
@jascott1 i did look into it, but then i am not setting a custom terminationlogpath so it shouldnt matter isnt it? the default is `/dev/termination-log` anyways. What happens in my case is, the error `Error: Job failed: BackoffLimitExceeded”` is not useful.

**Comment by jascott1** [comment]
I have not done it personally but I was hoping you would have success logging to the termination log. Maybe log to stdout and then use kubectl to get pod log?

Essentially its job name with random suffix:
```
$ kubectl get pods -a | grep px-etcd-preinstall-hook
px-etcd-preinstall-hook-psc5l 0/1 Completed 0 7m

$ kubectl logs px-etcd-preinstall-hook-psc5l
```

Checkout
https://github.com/kubernetes/kubernetes/issues/27768

**Comment by dpepper** [comment]
I have the same suggestion. If a pre-installation fails a generic error like: 
Error: timed out waiting for the condition
has no value to a user. We should be able to return an error message from the pre-install hook

**Comment by jascott1** [comment]
@hr1sh1kesh @skuby2 If you have the time can you try canary release? It is supposed to be working in a very recent version of Helm.

**Comment by dpepper** [comment]
@jascott1 When you say "it is supposed to be working" what exactly do you mean? Is there a way to feed back errors from a pre-installation hook so that the install command reports a valid error message?

**Comment by jascott1** [comment]
Sorry @dpepper I got this confused with another issue related to pre-install. Thats what I get for multitasking:/

**Comment by dpepper** [comment]
@jascott1 no problem. You had me excited for a moment because that feature would be really useful for me. Right now I am using a pre-install hook as a sort of pre installation check of the environment, and if the environment is not configured correctly is fails. But unfortunately I have to leave it disabled right now because I can't point the user to how to fix the problem because the error message is generic helm error.

**Comment by skuby2** [comment]
This would be extremely useful for me as well. Without it I'll have to change my hook termination policy so that the pod/job isn't cleaned up on failure, and write some wrappers to query the reason the hook failed.

**Comment by guyos** [comment]
Using post-install hook. I also get `Error: timed out waiting for the condition`, however, the job did complete successfully. Looks to me that the condition has been met but helm didnt get out of the wait status until the timeout was reached.
So in fact Error in my case is misleading - and what I should get it the NOTE.txt output as soon as the post-install job succeeded.
By the way - the job didnt succeed in the first try so a few additional pods were created - one terminated with completion before the timeout was reached

**Comment by rjeberhard** [comment]
Any progress on this one?  We similarly are interested in using a pre-install hook to do some custom validation; however, it's not very usable for our customers if we can only present them with an error that the Job hit the backoff limit or timed-out.  

We need some way to present the user with a message about why the Job/Pod failed.  We're happy to use Pod termination message, but we need a way to present that to the customer using our chart.

**Comment by mdeknowis** [comment]
It would be very helpful to see, which job is failing, currently it's really hard:

```
helm upgrade --install ... mychart
Release "myrelease" does not exist. Installing it now.
Error: Job failed: BackoffLimitExceeded
```

We have a huge helm chart, with many jobs and other k8s resources, so it's not obvious, which job is failing.

**Comment by bacongobbler** [comment]
We have not had the time to focus on this one. Most of the core maintainers' time is spent reviewing PRs from the community. If someone were to PR an enhancement to improve the error message, then we'd consider reviewing it for the next release. Feel like taking a crack at it?

**Comment by bacongobbler** [comment]
The [Contributing Guidelines](https://github.com/helm/helm/blob/master/CONTRIBUTING.md) (specifically the section about [what's considered breaking our semver contract](https://github.com/helm/helm/blob/master/CONTRIBUTING.md#semantic-versioning)) and the [Developers Guide](https://docs.helm.sh/developers/) are two good places to start. Let me know if you have further question.

**Comment by EronWright** [comment]
Design-wise, one option would be to report back the "pod termination message" in the event of failure.
https://kubernetes.io/docs/tasks/debug-application-cluster/determine-reason-pod-failure/

**Comment by fabiosantoscode** [comment]
I also hit this UX issue while using a `post-upgrade` hook to run some functional tests against the environment the chart is deployed in. The use case is for a closed-source app being deployed on our own k8s cluster.

Currently we have to manually inspect the logs out-of-band using Google Stackdriver which isn't very accessible for the junior devs. It would be nicer to have these logs either stream or just be displayed in the `helm upgrade --wait` command's stdout so we can read it directly on the CI.

I'm looking into termination logs as these seem to be the way to go!

**Comment by bacongobbler** [comment]
This feature request has been open for 2 years, and I have not seen any movement from the community to implement this feature. Closing as inactive.
