### ISSUE TITLE
Add ability to pass Capabilities.APIVersions to template and lint

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#3377]
When using the template and lint commands the Capabilities.APIVersions is an empty set because it uses defaults which are currently an empty set. Might be good to provide a set or provide the capability to pass in a set.

Note, lint doesn't let you pass in the version of k8s either. That may also be useful.

**Comment by munnerz** [comment]
I've recently discovered the new `helm template` command (wooo!)

I've used it to automatically generate some 'default' deployment manifests for cert-manager for users that wish to not use Helm. I've also created a verify script, to ensure these manifests are up to date during our CI process.

We use Capabilities to determine whether to use CRDs or TPRs. We could soon remove that check however, but in the meantime it'd be great if I could do *something* to make this return true:

`{{- if .Capabilities.APIVersions.Has "apiextensions.k8s.io/v1beta1" -}}`

**Comment by atopuzov** [comment]
I would also like to see this implemented.
/remove-lifecycle rotten

**Comment by kramvan1** [comment]
+1

**Comment by drewwells** [comment]
@thomastaylor312 this issue also mentions lint. The PR only addressed template

**Comment by genofire** [comment]
Yes linting is still not solved (but needed)

**Comment by avneesh91** [comment]
Is there an alternative for this or making link bypass this?

**Comment by genofire** [comment]
there is #10190 but also closed
