### ISSUE TITLE
`helm dep build` with Homebrew returns x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by bcg62** [helm/helm#3384]
OSX 10.12.6, Currently using 2.8.0 but the behavior is also present on 2.7.X installed via homebrew.

In a corporate environment where ssl inspection is taking place. There are custom CA's in the osx keychain facilitating the ssl termination. Doesn't seem to work with helm. Typically using the env var SSL_CERT_FILE is enough to override the bundle but it has no effect here.

```
$ helm dep build
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
	Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: getsockopt: connection refused
...Unable to get an update from the "stable" chart repository (https://kubernetes-charts.storage.googleapis.com):
	Get https://kubernetes-charts.storage.googleapis.com/index.yaml: x509: certificate signed by unknown authority
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading postgresql from repo https://kubernetes-charts.storage.googleapis.com/
Save error occurred:  could not download https://kubernetes-charts.storage.googleapis.com/postgresql-0.8.3.tgz: Get https://kubernetes-charts.storage.googleapis.com/postgresql-0.8.3.tgz: x509: certificate signed by unknown authority
Deleting newly downloaded charts, restoring pre-update state
Error: could not download https://kubernetes-charts.storage.googleapis.com/postgresql-0.8.3.tgz: Get https://kubernetes-charts.storage.googleapis.com/postgresql-0.8.3.tgz: x509: certificate signed by unknown authority
```

**Comment by SlickNik** [comment]
@bcg62 Thanks for reporting this! :) 

If I understand you correctly, the OSX keychain in your case contains only custom TLS certs and does not have any of the public trusted root CAs available? Or is there a proxy somewhere on the edge network that is doing TLS termination and re-establishment with a completely different cert which is not trusted? Can you elaborate a little more on your particular scenario here?

**Comment by bcg62** [comment]
The OSX keychain has all the public trusted roots, stored in the system roots keychain. In the system keychain we have our internal CA's, and yes that is correct, there is a proxy upstream doing re-establishment using those internal CA's.

Typically we can take the public bundle, add our CA's and use SSL_CERT_FILE (which most things usually support), IE:

`SSL_CERT_FILE=$HOME/cert.pem curl -L https://github.com`

I've seen various other issues around this

https://github.com/golang/go/issues/14311
https://github.com/golang/go/issues/14514
https://github.com/golang/go/issues/18203
https://go-review.googlesource.com/c/go/+/35634

Thanks

**Comment by bacongobbler** [comment]
/remove-lifecycle stale

Hey! Sorry for not following up on this ticket. This might be due to the Homebrew formula [compiling Helm from source](https://github.com/Homebrew/homebrew-core/blob/7ade79f13b4bbcc6126803245594d97b2abbe2fa/Formula/kubernetes-helm.rb), whereas the compiled release binaries are compiled with Go 1.10. Can you try the static binary releases (or [GoFish](https://gofi.sh) via `gofish install helm`)and see if that works instead?

**Comment by sfudeus** [comment]
I observe the same issue with helm 2.9.0 from homebrew. Using the official release binary for 2.9.0 there is no certificate warning.

**Comment by sfudeus** [comment]
Your suggestion to uninstall helm, update go and reinstall helm didn't do the trick for me. I had been at go 1.10.2 already anyway, so there was nothing to upgrade. Additionally, helm seems to be installed as precompiled bottle anyway, and not compiled locally with whatever go version was installed there. 

I'd agree that there isn't much that can be done here. I suppose the issue should be opened with homebrew, with the intent to fix the formula. 

Thanks!

**Comment by bacongobbler** [comment]
Let's keep this open for visibility. I updated the title to reflect the issue at hand. Thanks!

**Comment by kbaegis** [comment]
+1

**Comment by jfrederickson** [comment]
I'm not sure if this is related, but I'm experiencing what appears to be the same issue with the official binary of Helm 2.9.1.

```
$ helm repo add --ca-file <path/to/cacert.pem> helm-virtual https://repo-server.tld/path/to/repo --username k8s-dev --password <password>
Error: Looks like "https://repo-server.tld/path/to/repo" is not a valid chart repository or cannot be reached: Get https://repo-server.tld/path/to/repo: x509: certificate signed by unknown authority
```


`openssl s_client` with the `-CAfile` option, to the same server and with the same CA cert, connects successfully.

```
$ openssl s_client -connect repo-server.tld:443 -CAfile /path/to/cacert.pem
...
Verify return code: 0 (ok)
```

Helm version:
```
(⎈ |dev@linode:dev) applecake:linode-charts jfrederickson$ h version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

If this is related, is there any additional info I can give you that would be helpful in tracking this down? (Apologies for the heavy redaction.)

**Comment by bacongobbler** [comment]
hey @jfrederickson! how did you install the helm client?

If it was installed via Homebrew, we know of one particular issue where helm clients installed via homebrew can get compiled with an older release of Go which didn't respect MacOS's cert keychain.

**Comment by jfrederickson** [comment]
I just put the official binary from the GitHub releases page in my PATH - it's not installed through Homebrew:

```
$ which helm
/Users/jfrederickson/bin/helm
```

**Comment by bacongobbler** [comment]
Ah sorry about that! I missed the "official" part of your comment. :)

I see nothing wrong with your usage, sorry! Let us know if you find out anything.

**Comment by jfrederickson** [comment]
Well, I just compiled a local copy of helm from master, which was able to successfully verify my chart repo's cert. The official binary for `v2.10.0-rc.1` also works, `v2.9.0` also does not. Wonder if something changed on the official build server. (In any case, I _think_ I should be fine using a newer helm binary?)

**Comment by styk-tv** [comment]
So this is happening on mobile to wifi connection tethering for me. Looks like https traffic intercept with a self signed cert?

Do me a fav and lets compare "openssl s_client" to determine?

```
polfilm@Peters-MacBook-2:~$ helm upgrade --install --debug --namespace keycloak --values=/Users/polfilm/.madcore/rendered/values.helm.9100.keycloak.yaml mad stable/keycloak
[debug] Created tunnel using local port: '56057'

[debug] SERVER: "127.0.0.1:56057"

Error: Get https://kubernetes-charts.storage.googleapis.com/keycloak-3.1.0.tgz: x509: certificate signed by unknown authority
polfilm@Peters-MacBook-2:~$ openssl s_client -connect kubernetes-charts.storage.googleapis.com:443
CONNECTED(00000003)
depth=1 C = ES, ST = Madrid, L = Madrid, O = Allot, OU = Allot, CN = allot.com/emailAddress=info@allot.com
verify error:num=19:self signed certificate in certificate chain
---
Certificate chain
 0 s:/CN=*.storage.googleapis.com
   i:/C=ES/ST=Madrid/L=Madrid/O=Allot/OU=Allot/CN=allot.com/emailAddress=info@allot.com
 1 s:/C=ES/ST=Madrid/L=Madrid/O=Allot/OU=Allot/CN=allot.com/emailAddress=info@allot.com
   i:/C=ES/ST=Madrid/L=Madrid/O=Allot/OU=Allot/CN=allot.com/emailAddress=info@allot.com
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIC7jCCAdagAwIBAgIQIvlUWwAAAADtWQAAAAAAADANBgkqhkiG9w0BAQsFADB/
MQswCQYDVQQGEwJFUzEPMA0GA1UECAwGTWFkcmlkMQ8wDQYDVQQHDAZNYWRyaWQx
```

**Comment by spuder** [comment]
I am also running into this on helm 2.12.2 with my local cert present in my OSX keychain. 

Uninstalling 2.12.2 from homebrew and re-installing 2.12.2 from github releases page fixed the issue for me.

**Comment by rhnewtron** [comment]
I am running the chartmuseum via SSL on minishft with a self signed certificate. I was able to add the repo to helm and everything works properly if I have no dependencies when adding the ```--ca-file``` option.

```
helm repo add chartmuseum https://my-museum-with-private-cert/ --ca-file ca.crt
```

```helm install``` and ```helm repo update``` works. 

When I add dependencies to charts on the same chartmuseum, I get an error for downloading: 

```
λ helm dependency update spring-petclinic
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "chartmuseum" chart repository
...
Update Complete. ⎈Happy Helming!⎈
Saving 2 charts
Downloading xxx-build from repo https://my-museum-with-private-cert/
Save error occurred:  could not download https://my-museum-with-private-cert/charts/xxx-0.1.0.tgz: Get https://my-museum-with-private-cert/charts/xxx-0.1.0.tgz: x509: certificate signed by unknown authority
Deleting newly downloaded charts, restoring pre-update state
....
```

So it seems the chart download does not reuse the ca cert settings of the repo:

```
λ cat ~/.helm/repository/repositories.yaml
apiVersion: v1
generated: 2018-05-09T09:55:31.025782+02:00
repositories:
- caFile: c:\tmp\ca.crt
  cache: C:\Users\xxxx\.helm\repository\cache\chartmuseum-index.yaml
  certFile: ""
  keyFile: ""
  name: chartmuseum
  password: ""
  url: https://my-museum-with-private-cert/
  username: ""
```

**Comment by bitsofinfo** [comment]
```
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

Go 10.3+

Same issue, the repo is successfully installed, `helm dependency build` barfs on self signed certs, i've tried REQUESTS_CA_BUNDLE, putting the insecure flag in kube/config etc and still can't find a way to make it work.  Annoying. 

The repo certs are listed in `~/.helm/repository/repositories.yaml` and exist in the proper location.

`x509: certificate signed by unknown authority`

**Comment by bmudda** [comment]
+1

**Comment by gusmat** [comment]
I'm having this same issue on v2.14.0
`Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}`

**Comment by mail2vinay** [comment]
@bitsofinfo : still facing problem with --ca-file.
able to set during "helm repo add"
during download time it gives the following error, Error: failed to download "reponame/chartname" (hint: running `helm repo update` may help)
Using helm v 3.2.4

**Comment by weignerg** [comment]
> @bitsofinfo : still facing problem with --ca-file.
> able to set during "helm repo add"
> during download time it gives the following error, Error: failed to download "reponame/chartname" (hint: running `helm repo update` may help)
> Using helm v 3.2.4

Getting this exact issue still
