### ISSUE TITLE
example .Files.Get from documentation not working

### ISSUE THREAD

**Issue by rubroboletus** [helm/helm#3403]
I need, for my project, read files and combine them to one big value. When trying example from documentation:
_{{ range $path := .Files.Glob "nginx_be_custom_early/*.tpl" }}
{{ $path }}: |
{{ .Files.Get $path }}
{{ end }}_
I'm getting the following error:
_at <.Files.Get>: can't evaluate field Files in type []uint8_
Same results are from helm 2.7.2 and 2.8.0, both on Kubernetes 1.8.2 / 1.8.6.

**Comment by pmaterer** [comment]
I'm getting the same thing. I'm following the current Helm [documentation](https://docs.helm.sh/chart_template_guide/#accessing-files-inside-templates) and using client `v2.8.0`.

I have a sample chart setup:
```
.
├── Chart.yaml
├── static
│   ├── config.json
│   └── dashboard.json
├── templates
│   ├── NOTES.txt
│   ├── _helpers.tpl
│   └── config.yaml
└── values.yaml
```

The static directory has some simple json files:
```
patrick at NY-pmaterer in ~/t/example-app
↪ cat static/*.json
{
	"port": "8080",
	"address": "0.0.0.0"
}
{
	"name": "dashboard"
}
```

Trying:
```
patrick at NY-pmaterer in ~/t/example-app
↪ cat templates/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: "example-app"
  name: "example-app"
data:
{{ range $path, $bytes := .Files.Glob "static/*.json" }}
{{ $path }}: '{{ b64enc $bytes }}'
{{ end }}
```
Results in: 
```
patrick at NY-pmaterer in ~/t/example-app
↪ helm lint
==> Linting .
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: render error in "example-app/templates/config.yaml": template: example-app/templates/config.yaml:9:24: executing "example-app/templates/config.yaml" at <$bytes>: wrong type for value; expected string; got []uint8

Error: 1 chart(s) linted, 1 chart(s) failed
```

and then trying
```
patrick at NY-pmaterer in ~/t/example-app
↪ cat templates/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: "example-app"
  name: "example-app"
data:
{{- range $path := .Files.Glob "static/*" }}
{{ $path | indent 2 }}: |+
{{ .Files.Get $path | indent 4 }}
{{- end }}
```

results in
```
patrick at NY-pmaterer in ~/t/example-app
↪ helm lint
==> Linting .
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: render error in "example-app/templates/config.yaml": template: example-app/templates/config.yaml:9:18: executing "example-app/templates/config.yaml" at <2>: wrong type for value; expected string; got []uint8

Error: 1 chart(s) linted, 1 chart(s) failed
```

Let me know if I can provide any more information. Thanks!

**Comment by veeramarni** [comment]
I'm having a problem with `.Files` with verision `v2.8.0`

```
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sidecar.fullname" . }}
  namespace: "{{ .Release.Namespace }}"
type: Opaque
data:
  foo.txt: {{ b64enc (.Files.Get "foo.txt") }}

```

```
$ cat foo.txt
hwldkfdfkd
```
>helm template example
```
# Source: sidecar/templates/git-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: RELEASE-NAME-sidecar
  namespace: "default"
type: Opaque
data:
  foo.txt:
```

**Comment by prein** [comment]
I'm facing the same problem. The workaround with second argument (thanks @limnick) works if I want to print the path string, like so:
    `{{ $mypath }}`
but still won't work if I want to read the contents of the file
    `{{ .File.Glob $mypath }}`
throwing  `<.Files.Glob>: can't evaluate field Files in type []uint8` error.

**Comment by nelson-onyibe** [comment]
@prein 
something like this 
```
{{ $currentScope := .}}
{{ range $path, $_ :=  .Files.Glob  "**.yaml" }}
    {{- with $currentScope}}
        {{ .Files.Get $path }}
    {{- end }}
{{ end }}
```
will work for you

**Comment by hmacias** [comment]
Thanks @nelson-onyibe!

**Comment by tux-00** [comment]
Still the same on : 
```
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
```

**Comment by przemolb** [comment]
Confirmation - I get the same error with Helm v.2.10 as well:
```
apiVersion: v1
kind: ConfigMap
...
    {{ (tpl (.Files.Glob "files/*").AsConfig . ) | indent 4}}
...

[ERROR] templates/: render error in "mychart/templates/configmap.yaml": template: mychart/templates/configmap.yaml:49:19: executing "mychart/templates/configmap.yaml" at <.Files.Glob>: can't evaluate field Files in type int
```

**Comment by cbanek** [comment]
Just hit this same problem today (trying the example and being confused):

```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

**Comment by stevebail** [comment]
Same problem both with latest Helm 2 and 3
Both .Files.Get and .Files.Glob are not returning any data.
Example:
data:
  config1: |-
{{ (.Files.Glob "/config/*").AsConfig | indent 4 }}
  config2: |-
{{ .Files.Get "data.xml" | indent 4 }}

Results:
data:
  config1: '{}'
  config1: ""

**Comment by mboret** [comment]
Same issue ".Files.Get" and ".Files.Glob" returns nothing. I've also tried the example from the documentation with helm 11.0 and 14.3 and same.

**Comment by toshovski** [comment]
If you want to templatize the content of the file, you can use the following example:

`
{{- range $path, $_ := .Files.Glob "configuration/*" }}
{{ $path | base | indent 2 }}: |
{{ tpl ($.Files.Get $path) $ | indent 4}}
{{- end }}
`

Please note the $ after the tpl.

**Comment by tangzhankun** [comment]
I'm using helm v3.0.3. Encountered the issue of "can't evaluate field Files in type []uint8" when using `.Files.Get`.
Found that this will read files as expected:
`{{- tpl ((.Files.Glob "<config dir>/*").AsConfig) . | nindent 2 }}`

**Comment by manokovacs** [comment]
I am using helm 2.12 I can confirm that using `$` instead of `.` after the value works. The docs only mention "dot":

https://v2.helm.sh/docs/charts_tips_and_tricks/#using-the-tpl-function
https://helm.sh/docs/howto/charts_tips_and_tricks/#using-the-tpl-function

**Comment by marcadella** [comment]
Using v3.1.1 and still have the same issue as @tangzhankun : "can't evaluate field Files in type []uint8"
His solution did not work in my case :(

**Comment by marcadella** [comment]
Somehow it worked with:
````
data:
  {{- range $path, $d := .Files.Glob "templates/**.tpl.*" }}
  {{ $path }}: |-
  {{- $d | toString | nindent 4 }}
  {{ end }}
```

**Comment by theAkito** [comment]
Same issue. No proper official solution, yet? For me, none of the provided examples worked.

**Comment by CarlHeinst** [comment]
Having the same problem .Files.Glob never returns any output, none of the examples listed on line or in the docs seem to work.

Helm Version:"v3.0.0"

**Comment by toshovski** [comment]
within the range, you have only the local context. The global one can be accessed through $.

**Comment by salamovz** [comment]
My solution for looping over files, concatenate their sha and create new sha from concatenated one.
`kind: ConfigMap
metadata:
  annotations:
    checksum/config1: {{- range $path, $bytes := .Files.Glob "files/**" -}} {{- $sha := $.Files.Get $path | sha256sum -}} {{- $shasha := printf "%s%s" $.Values.cmsha $sha -}}{{- $_ := set $.Values "cmsha" $shasha -}} {{- end -}}{{- .Values.cmsha | sha256sum  | indent 2 }}`

**Comment by abuisine** [comment]
The documentation effectively seems wrong in regards to this part : 
```yaml
{{ range $path := .Files.Glob "**.yaml" }}
{{ $path }}: |
{{ .Files.Get $path }}
{{ end }}
```

`.Files.Glob` will return the **content** of the file rather than the **filename**.
As a result, `$path` is typed `[]uint8` which is normal as a file could contain binary information.

You can use `toString` in order to convert `[]uint8` to a `string` which is usable in a template.
It would be cool to explain this in the documentation, next to the example.

**Comment by abuisine** [comment]
Note also that `.Files.Get` will never work in such example as `range` changed the context, you would rather use `$.Files.Get`

**Comment by bacongobbler** [comment]
Please feel free to submit a PR to fix the documentation.

**Comment by serverhorror** [comment]
> Please feel free to submit a PR to fix the documentation.

As you wish :)

**Comment by zhaobei** [comment]
`apiVersion: v1
data:
{{- range .Values.cmName }}
  {{- range $key,$val := . }}
{{ (.Files.Glob $val ).AsConfig | indent 2 }}
  {{- end }}
{{- end}}
kind: ConfigMap
metadata:
  name: fluent-conf


`
I seem to have encountered the same problem and expect to be solved

**Comment by Asgoret** [comment]
Documentation example is still broken.
![image](https://user-images.githubusercontent.com/30697011/149181321-96a6f1c1-3ce8-468f-9da2-b976a4c7bb8e.png)
Code:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.metadata.name }}-configmap
  namespace: {{ .Values.metadata.namespace }}
  labels:
{{ include "alertmanager.labels" . | indent 4 }}
data:
  myvalue: "Hello World"
  {{ range $path, $_ :=  .Files.Glob  "**.yaml" }}
        {{ $.Files.Get $path }}
  {{ end }}
```
Error:
```
Error: INSTALLATION FAILED: YAML parse error on alertmanager/templates/cm.yaml: error converting YAML to JSON: yaml: line 13: did not find expected key
helm.go:88: [debug] error converting YAML to JSON: yaml: line 13: did not find expected key
YAML parse error on alertmanager/templates/cm.yaml
```

**Comment by gongxulei** [comment]
you can use  toString func to convert result (slice) as string.   
if you encountered some errors like "error converting YAML to JSON: yaml", It's a  code indentation issues, you can get a  yamlFile by " helm template test charts/test > test.yaml".  and check this yamlFile get a Indent Count. last, edit you code like me.

{{- range .Files.Glob "casbin/config/*.sql" }}
{{ . | toString | indent 4 }}
{{- end }}

**Comment by beuleal** [comment]
I had the same issue.

Similar to @MuForum. My solution was:
```
  {{- range $path, $_ := .Files.Glob "dashboards/*.*" }}
  {{ $path | base }}: |-
  {{ $.Files.Get $path | toString | nindent 4 }}
  {{- end }}
```

Explaining:
`$path` = dashboard/test.json `| base`, returns just the file `test.json`, not the whole path.
`$.Files.Get $path` = read the file | toString, to fix any possible json error
