### ISSUE TITLE
Allow users to choose a custom scheduler when installing charts

### ISSUE THREAD

**Issue by disrani-px** [helm/helm#3439]
Similar to how users are allowed to choose the namespace in which they install an app, it would be helpful if there is an option to choose a custom scheduler to use.

Without this it requires changing all the charts to add a template for the "schedulerName" and then setting that during install.

**Comment by jascott1** [comment]
Hi @disrani-px 

Thanks for the suggestion for improvement. If you will be contributing a design and/or implementation for this feature, please articulate the problem, proposed solution and what the implementation would look like (e.g. `adding a --scheduler flag`).  Sometimes we cannot accommodate every flag if there is another way to achieve the results (in this case by fixing the chart). Creating flags for all properties would be unwieldy. A proposal will allow the community to take a look and decide what to do. Thanks!

**Comment by disrani-px** [comment]
The proposal is to add a `--scheduler` flag.
Most (if any) charts do not have the schedulerName templated, so it isn't viable to update all the charts.

IMO this falls in the same category as the `--namespace` flag as it needs to be applied for all the apps in the chart.

**Comment by bacongobbler** [comment]
closing as inactive.
