### ISSUE TITLE
Watch hooks logs and log release-checking status in helm install/upgrade

### ISSUE THREAD

**Issue by distorhead** [helm/helm#3481]
There are 2 issues related to logs streaming, that we are experiencing using helm.

## Watch hooks logs

Generally we have a project, that uses helm for deploy (https://github.com/flant/dapp). And in our scheme deploy run as follows:

* run helm install/upgrade in main thread (blocking);
* parse hooks-jobs templates and show logs for jobs with annotation `dapp/watch-logs = true` in separate thread.

It works ok, but we have a strong belief, that it is a job of the helm to show logs.
We have done some work on that in ruby (https://github.com/flant/dapp/blob/master/lib/dapp/kube/dapp/command/deploy.rb#L119) and now we can use that experience to improve helm.

So, there is an idea to use hook-job annotation like `watch-logs = true|false`.
Say, by default none of the hooks is logged, so it is supposed that `watch-logs = false` for all hooks. In that case tiller will stream only logs related to the hooks where `watch-logs = true`.
And as the next step add option to helm client & tiller to log all hooks by default. With that option tiller will suppose `watch-logs = true` for all hooks by default.

And that logs streaming could occur directly in install / upgrade release grpc-action using server-side streaming.

## Check release state and show status during checking

There is related to the logging issue about checking release state (`--wait` in helm). 

Release checking may also log some status info about "what is being checked" and "what we are waiting for". It is not necessary pod's logs, it could be container status, information about replicas count, that needed to be reached and current replicas count for deployment.

Again, in our project we have done some work on Deployment status watching (https://github.com/flant/dapp/blob/master/lib/dapp/kube/kubernetes/manager/deployment.rb#L33). After helm install / upgrade is done the thread that watches hooks logs is also done, we run a deployments-watching procedure.

It is similar to what `--wait` is doing, but it gives interactive info about what is being checked and shows, among other things, pod's logs. That logging is not "ideal", but there is an idea, that release readiness check could work that way: making release checks polling and at the same time give some info to the user.

The main purpose of that logging is to show enough info for the end user during install / upgrade operation, so that user can diagnose the problem and make changes to templates without running kubectl to dig what is wrong.

And again we have a strong belief, that helm in `--wait` mode could do something like that to become a trully end-user kubernetes deployment tool.

---

Also there is a related issue https://github.com/kubernetes/helm/issues/2298, but separate helm command to show logs will not make helm more user-friendly deployment tool, that works out-of-the box.

**Comment by distorhead** [comment]
Another alternative could be some api-version parameter for helm-cli to enable api with some feature-set. In that case: `helm/watch` annotation will simply be ignored till `helm install/upgrade` called with `--api-version SomeVersionId`.

**Comment by distorhead** [comment]
Implemented complex part related to job/pod/container watching. The result is a JobWatchMonitor, PodWatchMonitor primitives.

* Watching is kubernetes-events based.
* Each primitive is a state-machine, that gives to their users higher level events than raw kubernetes events through channels. (https://github.com/kubernetes/helm/pull/3479/files#diff-c60efb0d4712928611d2411d2634fa3fR463)
* JobWatchMonitor could give events: JobLogChunk and JobPodError. It can be extended to give more info, but these two events is enough for now to construct hook-job logs and user-errors streaming.
* Watch procedure for each primitive runs in a separate goroutine.
* WatchContainerLogs procedure for active container runs goroutine for each container. This procedure makes api-call in `follow`-mode and stream back log-lines. (https://github.com/kubernetes/helm/pull/3479/files#diff-c60efb0d4712928611d2411d2634fa3fR151)
* PodWatchMonitor will stream pod-error message on ImagePullBackOff, ErrImagePull and CrashLoopBackOff. There may be more cases to add, these three cases are the most common. (https://github.com/kubernetes/helm/pull/3479/files#diff-c60efb0d4712928611d2411d2634fa3fR221)

On the client side helm prints logs and errors the same way as `tail -f` do on multiple files. If hook-job spawns multiple pods or multiple containers within pods, helm client will toggle log-header and print information chunk related to `(job, pod, container)` in realtime. It is acceptable logging behavior for hook-job, because typically hook-job doing something sequential. But if hook-job is doing something in parallel, that case is supported too, it will give an output as-is.

Overall job-watch procedure is separated from WatchUntilReady into WatchJobsUntilReady (https://github.com/kubernetes/helm/pull/3479/files#diff-73ee28a4d39ab9ab84ba5a6f9dee3867R365), because JobWatchMonitor primitive makes code more specific and focused on the end-goal of sequential watching of hook-jobs. And this primitive should watch job-related events by itself.

Passing logs and events from kube-client to release-server is implemented through WatchFeed interface. Actually it is a simple set of callbacks, because there is really no need to create golang-channels at this level.

For now this feature is works only for install request. "Copy-paste" only needed to add streaming to upgrade and rollback, but it is not the main problem. Annotation `helm/watch=true` is also not implemented yet, but it is not a problem too. Also there is a need to do more debug on cleanup for all spawned monitor-primitive goroutines (WatchContainerLogs could hang now when container remains in Waiting state).

The main problem for now is api-compatibility and I think I need some feedback to make changes to integrate this work properly. What do you think about this feature generally speaking? It is about 80% done and needs some adjustions, maybe something is done wrong.

What about extending install/upgrade/rollback grpc procedures to the server-side streamed versions and give these procedures different names. Helm client could use extended version only if they are available on tiller? What is wrong with that idea?

Also I think some parts of logs streaming can be reused for this PR #2342 too.

**Comment by distorhead** [comment]
@bacongobbler Hey! You set a proposal tag on this, could you answer me? Half a month passed and no reaction.

If this work goes totally against your plans could you say that directly? And whether there are any plans?

**Comment by lawrencejones** [comment]
Really keen on seeing this, it's pretty essential for us to have this debug output.

**Comment by unicell** [comment]
@distorhead I just cherrypicked your patches to latest 2.9 release, and added pre/post upgrade hook support[1]. It works fantastic! Really looking forward seeing the feature incorporated into master.

[1] https://github.com/unicell/helm/tree/upgrade-hook-log-streaming

**Comment by distorhead** [comment]
Cool, thanks for trying out!

Actually jobs watch is only the first step. The next steps could be support for watching for all other resource besides Job. And this watch code is also should be written as to be used not only to [Watch hooks logs](https://github.com/kubernetes/helm/issues/3481#issue-295845116), but also for [Check release state and show status during checking](https://github.com/kubernetes/helm/issues/3481#issue-295845116).

But for the first step current implementation already can be useful for users to watch jobs-hooks-only. Main problems to solve for this step:

* more debug on cleanup for all spawned monitor-primitive goroutines (WatchContainerLogs could hang now when container remains in Waiting state);
* watch only when annotation `helm/watch=true` is set, this experimental code should be optional and non-default;
* make this change api-compatible, maybe use extended install/upgrade/delete grpc requests with server-side streaming (?).

Actually my team is here and we are ready to solve all that, for now any works on this were just frozen before any feedback is received, because someone responsible from helm maintainers should agree or disagree or make corrections for this direction of works.

**Comment by billylindeman** [comment]
Any progress on this? I'd love to see it make it to public release?

**Comment by bacongobbler** [comment]
Apologies for the delay on a response. The core team (including myself) has been focusing solely on getting an alpha release of Helm 3 out the door, so any development on significant contributions to Helm 2 have been much harder to dedicate resources for peer review and design work at this time. We highly suggest bringing proposals/discussions to the weekly public dev calls if you need feedback: https://github.com/helm/community/blob/master/communication.md

> Firstly make api version negotiation between helm-client and tiller in backward-compatible manner. Somehow.

If this endpoint would break existing grpc endpoints, what about holding off until we have an alpha release of Helm 3 available and rebase this work against Helm 3? That way we won't have to write an API negotiation layer between helm and tiller.

**Comment by distorhead** [comment]
Hi, People!

The code from the PR https://github.com/helm/helm/pull/3479 related to this issue has been ported to separate project https://github.com/flant/kubedog.

We need this functionality, so we had to create a separate project and start using it. This code has been debugged more, tested and improved alot (for example now it uses kubernetes informers, which is a reliable primitive from kubernetes library, instead of raw watch kubernetes api).

This kubedog project is mainly the library that provides API to enable resources tracking in some application. There is also cli interface to this tracking functions. Library for now can track Jobs and Deployments. We have plans to support DaemonSets, StatefulSets and other resources tracking.

So if someone needs these functions right now -- try it out, and give some feedback ;)

As for the future of this issue: when Helm 3 will be released we can try to reintegrate these functions.

**Comment by distorhead** [comment]
Happy to announce, that [kubedog library](https://github.com/flant/kubedog) has been improved a lot since last notification. There are some new features which available out of the box right now:

* Track multiple resources at the same time.
* Give user realtime logs and other service messages about all resources being deployed.
* Give periodical "status reports" about overall rollout picture and answers question "what we are waiting for?".
* The output is designed as the simple text stream, so it can be used in any CI/CD or other tools.
* There is so called termination modes configurable for each resource. By default kubedog will wait until resource is ready, optionally kubedog can be configured to track resource only until other resources are not ready (non-blocking mode).
* There is different failure detection modes. By default there is allowed failures count for each resource. And as it is exceeded tracker will fail whole deploy. There is also so called "hope" failure mode in which resource errors will be ignored till all other resources become ready.

**Comment by StupidScience** [comment]
@distorhead @bacongobbler any chances to get this feature in helm 3?

**Comment by michael-bouvy** [comment]
Thanks @distorhead for the great work!

I'm currently using Helm 3 and have no intention switching to Werf (too many changes): what would be the best option to get kubedog's output (removing `--wait` flag from Helm), but still leverage `--cleanup-on-fail` when kubedog times out?

For instance:

```bash
helm upgrade --install my-app chart/
cat kubedog-config.json | kubedog multitrack || helm my-app cleanup # <-- "cleanup" doesn't exist, what may be used?
```

**Comment by distorhead** [comment]
Hi!

I think there may appear possibility to use kubedog with helm 3 by doing some small refactor in helm mainline code: move all resource watching code into some "backend" object, which have a default implementation — current helm --wait implementation (just as example https://github.com/flant/helm/pull/37/files#diff-d18c4d83690679deed0c84f55bf476bdR45).

Then we could add "kubedog" implementation, which will be isolated from the rest of the helm code. And then user can switch to this implementation or some another implementation or use default implmentation on own needs.

**Comment by abdennour** [comment]
Hello @distorhead  please elaborate more about kubedog in this context .

**Comment by dudicoco** [comment]
@distorhead @bacongobbler what is the status regarding porting this PR to work with helm 3?
I think this is an amazing feature that everyone would find beneficial and it's a shame that work has stopped on this PR when it could totally improve the information we get from helm install/upgrade/test.

Thanks!

**Comment by bridgetkromhout** [comment]
Hi, @distorhead - Thank you for your ideas to improve Helm. We now have a defined process so that if you'd like, you can submit a Helm Improvement Proposal so as to work in the community to make these ideas a reality: https://github.com/helm/community/blob/master/hips/hip-0001.md - meanwhile, I will close this issue. Thanks!

**Comment by rafis** [comment]
Any update?
https://github.com/helm/helm/issues/2298

**Comment by nuved** [comment]
Please add this feature at least for pre-install and pre-update jobs, 
 To show a simple  log we have to use other tools and tricks  along side helm and it's not very well.

**Comment by felipecrs** [comment]
I think that unless this goes as a HIP, it's not going to get any attention.

**Comment by felipecrs** [comment]
Just as reference, I created a [script called `helm-upgrade-logs` in my dotfiles](https://github.com/felipecrs/dotfiles/blob/master/home/dot_local/bin/executable_helm-upgrade-logs.tmpl) which does the job for me:

https://user-images.githubusercontent.com/29582865/155039184-0eed4d8e-a6fa-4180-9bc6-0d62afd33a98.mp4

**Comment by SamuelGarratt** [comment]
I needed something also that could show logs of pods associated to a release when testing a helm chart via KIND. 
I made a simple ruby gem at https://github.com/SamuelGarrattIqa/helm_upgrade_logs . 

Basically you can install it with
```
gem install helm_upgrade_logs
```
and then install a chart with the syntax
```
helm_upgrade_logs --install nginx bitnami/nginx --wait --debug --set service.type=ClusterIP
```

You can see it running in a Github action pipeline at https://github.com/SamuelGarrattIqa/helm_upgrade_logs/runs/6049884913

**Comment by flaneur2020** [comment]
any update?

**Comment by yuchao4x** [comment]
any update?

**Comment by felipecrs** [comment]
Some people mentioned `werf` here, but just to provide a quick start:

```bash
# install the werf binary. it comes with helm
wget https://tuf.werf.io/targets/releases/1.2.288/linux-amd64/bin/werf

chmod +x werf

./werf version

./werf helm version

./werf helm upgrade --install --wait jenkins https://github.com/jenkinsci/helm-charts/releases/download/jenkins-5.0.12/jenkins-5.0.12.tgz
```

The outcome is truly amazing:


https://github.com/helm/helm/assets/29582865/e6519d45-52ae-4a44-83c3-790f61d8b54a
