### ISSUE TITLE
build process leaves behind several temporary files and directories 

### ISSUE THREAD

**Issue by adshmh** [helm/helm#3485]
Building helm seems to leave behind multiple temporary files and directories. I am logging this issue to:
- Make sure a) this is true and b) it should be fixed 
- If above checks, then:
  - list all the left-over files and directories
  - I will then submit PR(s) to fix this.

Example:
$ make test
...
$ ls -ltr /tmp
...
drwx------ 3 a b 4096 Feb  9 06:02 helm-create-905124530
drwx------ 3 a b 4096 Feb  9 06:02 helm-create-117744233
...

**Comment by adshmh** [comment]
For the particular directories above, this seems to be the cause:

https://github.com/kubernetes/helm/blob/8009115d3a96653b2c7d97dc119bb665b1c08f9b/cmd/helm/create_test.go#L29-L36

I think `os.Remove` only removes a single file or directory, not a directory that contains files. Perhaps `os.RemoveAll` should be used here.

**Comment by bacongobbler** [comment]
Yes, it would appear that way. On master:

```
><> make test
...
><> ls /tmp/ | grep helm
helm-create-444878250
helm-create-786580225
helm_home348109756
helm_home510078407
helm_home708023816
helm_home-822961395
helm_home923341946
helm-repotest-257410639
helm-repotest-763744996
helm-repotest-874097590
helm-repotest-894370658
```

**Comment by adshmh** [comment]
Thanks for verification, I'll submit a few small PRs to fix this then.

**Comment by jascott1** [comment]
Labeling as a bug since the code intends to remove the artifact.

**Comment by bacongobbler** [comment]
closing as inactive.
