### ISSUE TITLE
How to get CA certificate for Kube cluster where a chart is installed?

### ISSUE THREAD

**Issue by tamalsaha** [helm/helm#3501]
I am trying to create chart that uses the new ValidatioWebHook feature in Kube 1.9 . This requires passing the CA certificate of the Kubernetes api server to the `ValidatingWebhookConfiguration` object . Is there a way to access this data from chart templates?

As a background,  I am using https://github.com/openshift/kubernetes-namespace-reservation/blob/master/artifacts/kube-install/apiserver-list.yaml.template#L132 as a template for building my chart . I am able to register my APIService following the patterns in service-catalog project.  This project detects KUBE_CA using the following logic:

```
KUBE_CA=$(kubectl config view --minify=true --flatten -o json | jq '.clusters[0].cluster."certificate-authority-data"' -r)
```

**Comment by chenrui333** [comment]
Any update on this?

**Comment by pmorie** [comment]
As someone trying to follow the same example, I think it would be useful to have some kind of accomodation here for this use case. I would be most comfortable as a helm user if there were treatment specifically for the kube CA bundle rather than a generalized facility for accessing values in configmaps within charts.

**Comment by donaldguy** [comment]
this seems like not a crazy extension of the existing stuff exposed in `Capabilities`; I ran afoul of this not realizing (cause its not documented ¬_¬) I needed to set a value in e.g. https://github.com/kubevault/operator/blob/0.2.0/chart/vault-operator/values.yaml#L89  (though admittedly the webhook seems to maybe still work without?)

**Comment by tamalsaha** [comment]
@donaldguy , our operators update the validating webhook after it starts to work around this issue.

**Comment by bacongobbler** [comment]
It's been 2 years since this proposal was first opened, and I have not seen any movement from the community to support this use case, so I'm close this as inactive. Please feel free to submit a PR along with a proposal should you need this.
