### ISSUE TITLE
extending a helm chart

### ISSUE THREAD

**Issue by benmathews** [helm/helm#3511]
My problem is in relation to the Prometheus chart, but I think the solution and benefit would be of general use. 

For Prometheus, I want to include a lot of repetitive monitoring and alerting configuration that is custom to my environment. But because it is repetitive, I'd like to template out the repetitive bits. I don't know if there is anything that will currently accommodate this. What I'd imagine is that I could supply both values and template files that would get used in the generation process. 

I'd like to be able to do something like 

    helm install stable/chart -f values.yaml --template new-or-overridden-template.yaml

**Comment by gregdurham** [comment]
I have been thinking similarly, and would like this approach. I am looking into adding istio and k8s' vault integration for secrets, which may be useful in my environment but not in others. As i add these, it appears the easiest method will be to fork community charts, and extend them for my environment. Seems like we could benefit from community updates as well as allow for overloading existing charts.

**Comment by bacongobbler** [comment]
This is one discussion topic in the Helm 3 proposals. See https://github.com/kubernetes-helm/community/blob/master/helm-v3/001-charts.md#the-ext-directory

**Comment by gregdurham** [comment]
Excellent. Thank you for linking this.

**Comment by bacongobbler** [comment]
library charts have been implemented in Helm 3 via https://github.com/helm/helm/pull/5295
