### ISSUE TITLE
Helm CLI doesn't follow redirects only returns a 404

### ISSUE THREAD

**Issue by liamawhite** [helm/helm#3531]
We have a redirect set up for our helm repo but the CLI does not follow it, just 404s.

It would be nice if the CLI follows any redirects to enable this behaviour or at least returns the 301 rather than a 404.

```
Liams-MBP:ansible-deploy liam$ helm repo add test https://registry-dev.stage1.ng.bluemix.net/helm
Error: Looks like "https://registry-dev.stage1.ng.bluemix.net/helm" is not a valid chart repository or cannot be reached: Failed to fetch https://registry-dev.stage1.ng.bluemix.net/helm/index.yaml : 404 Not Found
Liams-MBP:ansible-deploy liam$ curl https://registry-dev.stage1.ng.bluemix.net/helm/index.yaml -vvv
...
> GET /helm/index.yaml HTTP/1.1
> Host: registry-dev.stage1.ng.bluemix.net
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Server: nginx
< Date: Mon, 19 Feb 2018 11:56:14 GMT
< Content-Type: text/html
< Content-Length: 178
< Connection: keep-alive
< Location: https://registry-dev.stage1.ng.bluemix.net/helm/ibm
< X-XSS-Protection: 1; mode=block
< Strict-Transport-Security: max-age=31536000; includeSubdomains;
<
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
* Connection #0 to host registry-dev.stage1.ng.bluemix.net left intact
```

**Comment by snebel29** [comment]
I'm interested to start contributing to `helm` and I think tackling this issue could be a good start, how does that sound?

**Comment by rackeric** [comment]
I think helm is following 301 redirects according to my tests.  It looks like your URL is both returning the index.yaml page and a 404 Not Found error in the header.  I would double check your webserver as to why it is returning a 404.

[root@kube1 helm]# curl https://registry-dev.stage1.ng.bluemix.net/helm/ibm/index.yaml -I
HTTP/1.1 404 Not Found
Server: nginx
Date: Fri, 30 Mar 2018 19:51:28 GMT
Content-Type: text/plain
Content-Length: 18
Connection: keep-alive
X-Request-Id: 1329-1522439488.765-375841

:: My 301 Redirect Test ::
[root@kube1 helm]# curl http://166.78.174.108/index.yaml -I
HTTP/1.1 301 Moved Permanently
Date: Fri, 30 Mar 2018 19:55:51 GMT
Server: Apache/2.4.6 (CentOS)
Location: http://166.78.174.108/newdir/index.yaml
Content-Type: text/html; charset=iso-8859-1

[root@kube1 helm]# curl http://166.78.174.108/newdir/index.yaml -I
HTTP/1.1 200 OK
Date: Fri, 30 Mar 2018 19:56:06 GMT
Server: Apache/2.4.6 (CentOS)
Last-Modified: Fri, 30 Mar 2018 19:48:14 GMT
ETag: "4e8-568a6855650bf"
Accept-Ranges: bytes
Content-Length: 1256

[root@kube1 helm]# bin/helm repo add mytest http://166.78.174.108
"mytest" has been added to your repositories

[root@kube1 helm]# bin/helm repo list
NAME  	URL                                                     
stable	https://kubernetes-charts.storage.googleapis.com        
local 	http://127.0.0.1:8879/charts                            
coreos	https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/
mytest	http://166.78.174.108

**Comment by rehevkor5** [comment]
This problem occurs with the `template` command too. If the server responds with 302 Found and a "Location" header, as github's "Release" links do (redirecting to an S3 URL), `helm` exits with nonzero output and prints a message like:

> Error: stat https://github.com/splunk/splunk-connect-for-kubernetes/releases/download/v1.0.1/splunk-kubernetes-logging-1.0.1.tgz: no such file or directory

**Comment by farnasirim** [comment]
@rehevkor5 This is expected as `$ helm template --help` notes:
Render chart templates **locally** and display the output.

**Comment by rehevkor5** [comment]
@farnasirim Then maybe the wording can be improved to "Render local chart templates". It also says, "locally render templates", not "render local templates". Otherwise, it just sounds like it's saying, "Render templates locally, instead of rendering them on Tiller inside your cluster like normal."

In any case, it would be much more consistent to have this work the way `helm install` works. The docs say, "The install argument must be a chart reference, a path to a packaged chart, a path to an unpacked chart directory or a URL." Why should `helm template` be any different?

**Comment by ishankhare07** [comment]
is this issue still open?
If so i'd like to work on it..

**Comment by bacongobbler** [comment]
Yes. Feel free to work on this. I'd write some unit tests to verify before working on a fix. Some users have reported this already works and others have reported it does not.

**Comment by ishankhare07** [comment]
cool @bacongobbler 
this is going to be my first issue
thanks for the pointer for where to start

**Comment by Shagon94** [comment]
hey @bacongobbler not sure if this is still up for grabs, I'd like to work on this issue since I'd like to start contributing to this project

**Comment by bacongobbler** [comment]
Feel free!

**Comment by Shagon94** [comment]
I've used the following repo for testing - http://technosophos.github.io/tscharts/
I can see that there is a https redirection on it as to test if redirections are an issue:

```curl
$ curl -IL 'http://technosophos.github.io/tscharts/' 2>&1 | egrep 'HTTP|Location'
HTTP/1.1 301 Moved Permanently
Location: https://technosophos.github.io/tscharts/
HTTP/2 200 
```

```
$ ./helm version
version.BuildInfo{Version:"v3.1", GitCommit:"", GitTreeState:"", GoVersion:"go1.14.2"}

$ ./helm repo add test http://technosophos.github.io/tscharts/
status code 200
"test" has been added to your repositories

$ ./helm repo list
NAME	URL                                    
test	http://technosophos.github.io/tscharts/
```

so we can see that the http client follows the redirects. 
The output was a simple

```golang
fmt.Println("status code", resp.StatusCode)
```

 added directly above https://github.com/helm/helm/blob/b21b00978539ea8270e6b672bc1e6bc07af61475/pkg/getter/httpgetter.go#L72-L74

As for the original report https://github.com/helm/helm/issues/3531#issue-298250612
The link is more than 2 years old at this point and is returning a 404 at this point of time:

```
$ curl -I https://registry-dev.stage1.ng.bluemix.net/helm/index.yaml -X GET
HTTP/1.1 404 Not Found
Date: Tue, 21 Apr 2020 06:41:33 GMT
Content-Type: text/plain
Content-Length: 18
Connection: keep-alive
Strict-Transport-Security: max-age=31536000; includeSubDomains
```
___

Taking the other report for the templates https://github.com/helm/helm/issues/3531#issuecomment-405408444

Taking the latest release at this point from [splunk github](https://github.com/splunk/splunk-connect-for-kubernetes/releases)

```yml
$ curl -I 'https://github.com/splunk/splunk-connect-for-kubernetes/releases/download/1.4.0/splunk-connect-for-kubernetes-1.4.0.tgz' 2>&1 | grep 'HTTP'
HTTP/1.1 302 Found

$ ./helm template https://github.com/splunk/splunk-connect-for-kubernetes/releases/download/1.4.0/splunk-connect-for-kubernetes-1.4.0.tgz | head -10
status code 200
---
# Source: splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/serviceAccount.yaml
apiVersion: v1

kind: ServiceAccount
metadata:
  name: RELEASE-NAME-splunk-kubernetes-logging
  labels:
    app: splunk-kubernetes-logging
```

I've also tested the reported version in the comment:

```yml
$ ./helm template 'https://github.com/splunk/splunk-connect-for-kubernetes/releases/download/v1.0.1/splunk-kubernetes-logging-1.0.1.tgz' | head -10
---
# Source: splunk-kubernetes-logging/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: RELEASE-NAME-splunk-kubernetes-logging
  labels:
    app: splunk-kubernetes-logging
    chart: splunk-kubernetes-logging-1.0.1
    release: RELEASE-NAME


$ curl -I 'https://github.com/splunk/splunk-connect-for-kubernetes/releases/download/v1.0.1/splunk-connect-for-kubernetes-1.0.1.tgz' 2>&1 | grep HTTP
HTTP/1.1 302 Found
```

Looks like everything is working by design, the http client is following redirects.
