### ISSUE TITLE
Proposal: requirement conditions should be evaluated on parent chart rather than top-level chart

### ISSUE THREAD

**Issue by jstriebel** [helm/helm#3533]
I have the following charts, that require each other:
* __myapp__
  * requirements: database (condition `database.enabled`)
  * charts:
    * __database__
    * requirements: backup (condition `backup.enabled`)
    * charts:
      * __backup__

The two obvious use-cases work fine: enabling everything, and disabling the database, which also does not import the backup (as intended).
Only disabling the backup (in the level of myapp), however, is currently weird for my understanding. I would have to set the key `backup.enabled` in myapp, but would actually expect it to be `database.backup.enabled`. This behavior is specified in [the docs](https://github.com/kubernetes/helm/blob/master/docs/charts.md#tags-and-condition-fields-in-requirementsyaml), but still puzzling to me.
> If this path exists in the top parent's values …

I was wondering if your are aware of the discrepancy between "normal" values and conditions values when it comes to deep nested charts. I am proposing to use the nested values also for the conditions. This would also resolve potential naming problems (e.g. having 2 databases, that both require the backup chart) quite nicely.

Thanks for considering this!

------------
PS: This behavior was tested using the current helm `v2.8.1`.

**Comment by jstriebel** [comment]
Obviously this breaks compatibility, but would you be interested to adapt this for the next major release (v3)? I could try to provide a PR, even though I'm new to Go.
/cc @bacongobbler

**Comment by jascott1** [comment]
@jstriebel This is important to be fixed for v3 so adding milestone.

**Comment by jstriebel** [comment]
I guess this should also go into the [Upcoming - Major](https://github.com/helm/helm/milestone/29) milestone at some point. Thanks @jascott1 for making sure this does not get overlooked :+1:

**Comment by WarheadsSE** [comment]
Will this ever be addressed?

**Comment by jstriebel** [comment]
Just wanted to check back on the status of this proposal. As the first beta releases for Helm 3 are out there, I am wondering if this is still planned for Helm 3. I'm currently at the Helm Summit in Amsterdam, feel free to ping me in person if you are there @jascott1

**Comment by bacongobbler** [comment]
I believe this is similar to what was asked in https://github.com/helm/helm/issues/3734, which was fixed in Helm 3 via https://github.com/helm/helm/pull/4917. Can you confirm?

**Comment by jstriebel** [comment]
@bacongobbler Yes, exactly! Thanks a ton, wasn't aware of the related issues. This seems to be solved :+1:
