### ISSUE TITLE
[feature request] helm create - test template

### ISSUE THREAD

**Issue by rimusz** [helm/helm#3559]
`helm create` should create `test` template example

**Comment by SlickNik** [comment]
Thanks for suggesting this, @rimusz! 👍 
Is this something that you're working on a PR for, or can I go ahead and label it as "help wanted"?

**Comment by hickeyma** [comment]
Is it OK if I take this?

**Comment by michelleN** [comment]
@hickeyma absolutely

**Comment by hickeyma** [comment]
PR #4524 now ready for review.
