### ISSUE TITLE
Facilitate pushing charts to a registry

### ISSUE THREAD

**Issue by jzelinskie** [helm/helm#3564]
Historically, Helm has treated chart repositories as read-only.
This has immediate benefits in that charts can be hosted directly by any static webserver or object store. The downside to this approach is that it requires manual updating of the index both client-side and server-side in order to synchronize changes. This inability to easily add a new chart has effected the discoverability and sharing of community charts outside of the [official charts repository][k8s/charts].

In order to combat this problem, there are two existing community solutions: [App Registry] and [ChartMuseum]. Both offer a workflow for uploading charts to a remote service that will serve charts.

ChartMuseum strives to match the existing Helm repository model with the addition of [HTTP methods for mutating charts][cm api]. The ChartMuseum server acts a centralized point of generating the Chart repository index after one of the mutating HTTP methods is called. An [example of this workflow][cm workflow] can be achieved using Helm and cURL.

App Registry eschews existing Helm repository design in favor of a model that aligns with existing registries used for container images. App Registry does not create any Helm repositories or indexes, rather it leverages a [docker-style registry protocol][appr api] for uploading, downloading, and discovering charts. Charts are treated as opaque blobs and stored in content addressable storage (CAS). [OCI]-style [JSON manifests][appr manifests] are used to describe the metadata for a collection of blobs. An [example of this workflow][appr workflow] can be achieved using the [Helm App Registry Plugin][appr plugin].

I'm opening this issue as a long-term discussion for how we should potentially move forward with improving Helm core to better support these workflows.

[k8s/charts]: https://github.com/kubernetes/charts
[App Registry]: https://github.com/app-registry
[ChartMuseum]: https://github.com/kubernetes-helm/chartmuseum
[cm api]: https://github.com/kubernetes-helm/chartmuseum/blob/df615f035d43e6d690aa48a937958b1b2445abcc/README.md#api
[cm workflow]: https://github.com/kubernetes-helm/chartmuseum/blob/df615f035d43e6d690aa48a937958b1b2445abcc/README.md#uploading-a-chart-package
[OCI]: https://github.com/opencontainers/image-spec
[appr manifests]: https://github.com/app-registry/appr/tree/9d4370b5eedbd7d0aefce152435bf2e336d41f5a#pull-the-chart
[appr api]: https://github.com/app-registry/appr/blob/master/Documentation/server/appr-api-swagger.yaml
[appr workflow]: https://github.com/app-registry/appr/tree/9d4370b5eedbd7d0aefce152435bf2e336d41f5a#create-and-push-your-own-chart<Paste>
[appr plugin]: https://github.com/app-registry/appr-helm-plugin

**Comment by SlickNik** [comment]
Thanks for kicking off this discussion @jzelinskie! We spoke about this during one of the unconference sessions at the Helm summit (Session 1 - Table 2). I've compiles some notes from that session and have opened a PR at https://github.com/kubernetes-helm/helm-summit-notes/pull/4.

**Comment by bacongobbler** [comment]
closing. See https://helm.sh/docs/topics/registries/#helm, which includes instructions on how to push a chart to an OCI registry via `helm chart push`.

**Comment by tculp** [comment]
I'm not sure that this is satisfied by https://helm.sh/docs/topics/registries/#helm, for a couple of reasons.

First, this question is based around uploading to non-OCI registries, and unless support for non-OCI helm registries is planned to be dropped, that isn't a valid solution.

Second, the OCI support is currently experimental, and is likely to change greatly.

**Comment by bacongobbler** [comment]
@tculp this discussion was about storing charts in OCI registries. App Registry was the first initiative pioneered by CoreOS to store charts in OCI registries. They helped kick off the discussion about moving away from the chart repository model to OCI registries as the backing storage layer.

> App Registry eschews existing Helm repository design in favor of a model that aligns with existing registries used for container images.
