### ISSUE TITLE
[feature request] helm create - uses common chart as template

### ISSUE THREAD

**Issue by depohmel** [helm/helm#3572]
The Common chart (https://github.com/kubernetes/charts/blob/master/incubator/common) has many great helpers. It would be nice to use it as template for new charts.

**Comment by SlickNik** [comment]
@depohmel -- thanks for putting in this feature request! The topic of updating the default template that gets created when you run a `helm create` did come up at the Helm Summit as well, and it seemed like most people at the summit thought it would be good to have a more expansive and instructional default template.

**Comment by bacongobbler** [comment]
closing as inactive.
