### ISSUE TITLE
Feature request: built-in object containing the Tiller namespace

### ISSUE THREAD

**Issue by johngmyers** [helm/helm#3576]
I have a lifecycle hook that needs to run in Tiller's namespace, not Release.Namespace, so as to access credentials therein. So the job template would need a built-in object containing the Tiller namespace.

**Comment by SlickNik** [comment]
Hi @johngmyers -- thanks for putting in this feature request! 

Can you describe what you are trying to achieve with some more detail, (i.e. why you'd like to run the lifecycle hook in the tiller namespace) so that we can understand your use case better?

**Comment by johngmyers** [comment]
My lifecycle hook needs to access a secret in order get a credential to authenticate to an authentication/authorization service so that it can create a new user/credential for the service being deployed (and configure the service to use the newly created user/credential).

The credential with permission to create and authorize new credentials cannot be present in the Release.Namespace as that would expose it to unauthorized identities.

**Comment by bridgetkromhout** [comment]
Hi, @johngmyers - as Helm 3 no longer uses Tiller, the Tiller namespace is no longer used. I'll resolve this feature request now, but if you find you have new needs for Helm 3, please open a new issue. Thanks.
