### ISSUE TITLE
Requirements tag/condition always defaulting to true

### ISSUE THREAD

**Issue by lostmimic** [helm/helm#3587]
In requirements.go the code forces you to have the condition/tag both exist and set to false in order to disable a dependency. For organizations with large number of optional dependencies it is annoying to have to have a big chunk of conditions/tags set to false in the values.yaml file.

Is there a reason why dependencies differ in behavior here (vs the default of blank/nil being false)?

Also you cant even set it to default to false in the child chart as Helm will only look at the top parent's values.

**Comment by jebbench** [comment]
We've also encountered this; our use case for tags is to enable pre-production/test charts on our test environment (`tags.isTest: true`); we've found charts are deployed to production even when the tag is missing.

The docs state: `Tags are evaluated as 'if any of the chart's tags are true then enable the chart'.` but this doesn't seem to be the case.

We can work around this for our use case by setting defaults in our parent chart but as we add other environments (i.e. isE2e, isStaging, isDevelop) we'll have to remember to set defaults.

Is the functionality working as expected and the documentation wrong or the documentation correct and the functionality wrong?

**Comment by jascott1** [comment]
@lostmimic That is inconvenient. The idea is that things must be explicitly set to false to be disabled and just referencing non-existent values as false would lead to confusion. Its pretty rudimentary but originally designed to be non-invasive for existing charts while being expandable some day via operators in the requirements.yaml.

@jebbench Sorry for the confusion but charts are enabled unless explicitly disabled.

From charts.md:

> **All charts are loaded by default.** If tags or condition fields are present, they will be evaluated and used to control loading for the chart(s) they are applied to.

**Comment by derekbassett** [comment]
If I have a chart with the value file listed as the value as false this charts are still enabled.

So requirements.yaml I have 

```
dependencies:
- name: redis
  version:
  repository:
  condition: redis.enabled
```

In my values.yaml file I have

```
redis:
   enabled: false
```

It appears to work in the latest helm 2.9 but does not appear to work in helm 2.8.

**Comment by jascott1** [comment]
@lostmimic Sorry for the confusing docs. Im going to close this now as the behavior has been explained but add a comment if you need further discussion. Docs PR would be greatly welcomed.

@derekbassett I am not aware of the problem in 2.8 but since its fixed for you in 2.9, please open an issue if 2.8 fix back port is important to you. Thanks!

**Comment by corey-aloia-sap** [comment]
@derekbassett I have this same situation, but it is not working for me in helm 2.10. The value is always true, even though the values.yaml has enabled set to false.

**Comment by william-tran** [comment]
@jascott1 
> Its pretty rudimentary but originally designed to be non-invasive for existing charts while being expandable some day via operators in the requirements.yaml.

Is this possible in helm 3?

**Comment by dallasvaughan** [comment]
> The idea is that things must be explicitly set to false to be disabled and just referencing non-existent values as false would lead to confusion

I think it is actually the opposite. It is more confusing and less standard to "assume" that the value is `true` when a value is not present. Pretty much every dynamic language interprets `nil`/`null` as `false`, not `true`. If the intent is to define **optional** dependent charts, it would make more sense to default to _not_ loading them by default when there is a condition specified and it is not set, not the other way around.

**Comment by jascott1** [comment]
Helm already had sub-charts without a mechanism to control which ones were loaded. The implementation was backwards compatible in that if it was not used all charts would continue to be loaded.

**Comment by LessMo** [comment]
If I have only 1 tag, the chart is loaded when tag is missing in values.yaml
```
  - name: hawkeye
    version: 1.0.0
    repository: file://../hawkeye
    tags:
      - tag1
```

When I have 2 tags, the chart is not loaded when 1 tag is false and another tag is missing.

```
  - name: hawkeye
    version: 1.0.0
    repository: file://../hawkeye
    tags:
      - tag1
      - tag2
```

```
tags:
  tag1: false
```

It's really confusing. 🙃

**Comment by japzio** [comment]
https://v2-14-0.helm.sh/docs/chart_best_practices/#conditions-and-tags
