### ISSUE TITLE
Could you please provide extended documentation for path-helper?

### ISSUE THREAD

**Issue by samar1n** [helm/helm#3605]
/docs

**What happened**: 
I was trying to generate helm templates for multiple projects in a single repo based on repo dir structure and got an error

` Error: render error in ... at <dir>: wrong number of args for dir: want 1 got 0`

Documentation provided here 

> https://github.com/kubernetes/helm/blob/master/docs/chart_template_guide/accessing_files.md#path-helpers

 does not clarify what to do.

**What you expected to happen**: I expected to get dir structure to generate helm templates based on it.

**How to reproduce it (as minimally and precisely as possible)**:
Run the example YAML provided below

```
{{ range $i := dir.path "./" }}
{{ .Name }}-{{ $i }}-{{ .Release.Name }}
{{- end }}
```

` Error: render error in ... at <dir>: wrong number of args for dir: want 1 got 0`

**Anything else we need to know?**:
Currently i'm using self made helm generator to handle this logic. And looking for a way to handle it via approach i asked about. Maybe, you can suggest a better way.

**Comment by bacongobbler** [comment]
closing as inactive.

**Comment by rptaylor** [comment]
So what is the right syntax for using the path helpers? The documentation should have examples indeed.
