### ISSUE TITLE
Feature request: helm search should take creation date into account (support commit based versioning)

### ISSUE THREAD

**Issue by bjornmagnusson** [helm/helm#3614]
When searching for chart you get the "latest" chart available. However, this only works if the chart version are strictly <major><minor><patch>.
In our company we version them <major><minor><patch>-<commit-hash>. When doing so the helm search command does not list the latest chart available. Seems to be a bit random which chart get listed.
From some investigation of the index.yaml file of the repository, there is a field _created_ that could be used for truly filtering out the latest built

helm search demo-chart --versions
CHART VERSION   APP VERSION     DESCRIPTION
helm-virtual/demo-chart        0.1.0-ceeabeb   0.1.0-ceeabeb   Demo Chart
helm-virtual/demo-chart        0.1.0-ac79f53   0.1.0-ac79f53   Demo Chart
helm-virtual/demo-chart        0.1.0-7232d1f   0.1.0-7232d1f   Demo Chart
helm-virtual/demo-chart        0.1.0-20f09ca   0.1.0-20f09ca   Demo Chart
In this listing 0.1.0-7232d1f is the latest built chart.

Actual output:
helm search demo-chart
CHART VERSION   APP VERSION     DESCRIPTION
helm-virtual/demo-chart        0.1.0-ceeabeb   0.1.0-ceeabeb   Demo Chart

Expected output:
helm search demo-chart
CHART VERSION   APP VERSION     DESCRIPTION
helm-virtual/demo-chart        0.1.0-7232d1f   0.1.0-7232d1f   Demo Chart

**Comment by bacongobbler** [comment]
closing as inactive.
