### ISSUE TITLE
Proposal: Values injection

### ISSUE THREAD

**Issue by dean-legalone** [helm/helm#3618]
A lof of charts are missing functionalities that we use (i.e. affinity) and it would be nice to be able to inject or override values in the following way:

`[file-name]:path`

usage example:

```
deployment.yaml:spec:template:spec:affinity
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
.....

```

This will save us the need to fork charts and the need to keep track & update them

**Comment by jstrachan** [comment]
another approach would be to create your own chart depending on the underlying chart in question, then add your own PodPresets: https://kubernetes.io/docs/concepts/workloads/pods/podpreset/

**Comment by dean-legalone** [comment]
Of course, but the problem with creating my own chart is that i'll have to keep it updated myself instead of using the latest changes done by the community :)

**Comment by missedone** [comment]
> using the latest changes done by the community :)

May I be little off topic, but, @dean-legalone , please use this strategy with caution, this could be potential failure some day without prediction when the latest change introduce break changes. So in this hand of side, manage your own means stable and predictable.

**Comment by maorfr** [comment]
Hi,

What about creating a binary to do the desired injection and use it with this plugin:
https://github.com/maorfr/helm-inject

**Comment by maorfr** [comment]
@bacongobbler I think this issue can be closed :)
