### ISSUE TITLE
Add custom DNS entries for stable / incubator repos

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#3628]
There has been talk, for a couple of reasons, of reasons for the object storage buckets that hold charts. Right now, the locations are hard coded (e.g., https://kubernetes-charts-incubator.storage.googleapis.com). This doesn't let us move them later.

Example reasons today are more logistical (e.g., who pays for what bucket to host them in – something like Google or CNCF, which hold Kubernetes, and where those buckets reside).

Could we setup DNS from the helm.sh domain for these and use those instead?

**Comment by bacongobbler** [comment]
closing as inactive. Helm hub (and Artifact Hub) is the new direction going forwards anyhoo.
