### ISSUE TITLE
Clean up template error messages

### ISSUE THREAD

**Issue by phemmer** [helm/helm#3629]
Right now error messages emitted by helm are very noisy and hard to read. Lets take look at a common example where a required parameter was left undefined:

```
Foo: {{ required "myfoo is required" .Values.myfoo }}
```
```
# helm template .      
Error: render error in "foo/templates/foo.yaml": template: foo/templates/foo.yaml:1:8: executing "foo/templates/foo.yaml" at <required "myfoo is r...>: error calling required: myfoo is required
```
Is it really necessary to dump the file name 3 times, with all the extra stuff in between, and then repeat the actual error twice, one of them truncated? I think it would be a lot better to have a simple and concise message like:

    Error: myfoo is required (foo/templates/foo.yaml:1:8)

This eliminates the redundancy, and the need to have to mentally parse through the message to find the actual error.

&nbsp;

The `required` use case seems a little special as this is clearly a user error where we don't need to debug anything. However the spammyness exists for other errors as well:
```
Foo: {{ boom }}
```

```
Error: parse error in "foo/templates/foo.yaml": template: foo/templates/foo.yaml:1: function "boom" not defined
```
Perhaps something like this would be better:
```
Error: function "boom" not defined (template: foo/templates/foo.yaml:1)
```

**Comment by bacongobbler** [comment]
Awesome feedback, @phemmer. I totally agree, though we might not be able to tackle this in the 2.0 timeline. hwoever, this would be a fantastic starter issue for Helm 3!

**Comment by drex44** [comment]
is this still open? 
can I work on this?

**Comment by ian-howell** [comment]
So I've taken a quick look at this one, and it seems as though the issue is coming from upstream. Here is the message that [template.ExecuteTemplate](https://github.com/golang/go/blob/master/src/text/template/exec.go#L178) spits out:

```
template: foo/templates/foo.yaml:1:8: executing "foo/templates/foo.yaml" at <required "myfoo is r...>: error calling required: myfoo is required
```

I'll go ahead and take this one, but it'll require parsing the errors from the template library.

**Comment by ian-howell** [comment]
@phemmer @bacongobbler I think this is safe to close?

**Comment by bacongobbler** [comment]
good call. Thanks @ian-howell!
