### ISSUE TITLE
Proposal: sortable manifests (templates)

### ISSUE THREAD

**Issue by phemmer** [helm/helm#3635]
This is a proposal to solve issues such as #2994. I wanted to open this in a separate issue so that this specific implementation could be discussed and potentially declined separately from the problem report.

The proposal is to:
1. Add a `helm.sh/order-weight` annotation to the first object in a manifest (a.k.a template) file. The annotation would sort the files within a chart.
  An alternative here would be a comment header at the top of the file (e.g. `# weight: 123`)
2. Add a `weight` attribute to each dependency in `requirements.yaml`. The attribute would sort the charts as whole units.
  An alternative here would be a `sort: true` in the top level of `requirements.yaml`, which would enable sorting the dependencies in the listed order.

In the event that a subchart is required by multiple charts, the highest level chart's requirements sets the weight of that chart.

Sorting precedence would then become:
(kind sorting) -> (annotation sorting) -> (subchart sorting) -> (chart sorting)

Weight would be a signed integer, with a default of 0. Thus all existing charts would be sorted the exact same way since kind sorting would not be overridden.

&nbsp;

I'd be willing to work on this as this is currently a major blocker for us since we're using object types that helm is not aware of, and thus it applies them in the wrong order.  
However I wanted to get approval that this would be accepted before working on it because the amount of work involved would be moderately sized. Right now manifests are sorted without regard to the chart they came from, and that context is not available at sort time. So the code would have to be restructured a bit.

**Comment by thomastaylor312** [comment]
This is definitely an interesting proposal. I'd be interested in @technosophos' or @adamreese's thoughts on this. We could discuss this in one of the dev calls as well. This next week's call is focused on Helm 3, but we could slot it in after that as well

**Comment by thomastaylor312** [comment]
One more clarification question here, is this purely to solve the CRD use case or is there another use case it would solve for you?

**Comment by phemmer** [comment]
> One more clarification question here, is this purely to solve the CRD use case or is there another use case it would solve for you?

Our use case is actually around openshift. Since helm doesn't recognize any of the openshift resource types, it treats them all as unknown and puts them last. Same thing as the CRD though.
I think there's also another more advanced use case that I ran into the other day with ordering between the charts (a resource in one chart depended on a resource in another chart), but I can't recall what that was.

**Comment by darren-bell-nanthealth** [comment]
Hello. Has there been any progress with this proposal or is there an alternative approach. We are particularly interested in the weighting/ordering of the charts in the requirements.yaml.

**Comment by technosophos** [comment]
The short answer is that the core maintainers are not likely to implement this feature ourselves because we are working on Helm 3. But if someone does a PR with this feature (and it doesn't break compatibility), it is likely to get merged.

**Comment by libesz** [comment]
Hi. As indicated on slack before, we are interested in implementing this, first in helm v2! Hope this is still welcomed 🤞.
I'd like to discuss one notable addition to the specification above which we intend to cover. This is the inter-working with `--wait`. The use-case is to influence the creation/upgrade order not only the administrative/config kind of resources, but also the native workload resources, like Pods of a Deployment or DaemonSet. That means the merged/rendered manifest chunks are (not only sorted, but) splitted based on the given weights. The splitted chunks are pushed to K8S API in different requests and waited per chunk when `--wait` supplied. This enables to properly wait for the controller created components as well. When not using weights, the behavior is naturally BW compatible.
/cc @zadoryzsolt

**Comment by libesz** [comment]
Let me ping this topic.
Could we discuss this on slack and/or next dev call? We already have a prototype.

**Comment by bacongobbler** [comment]
closing as inactive.
