### ISSUE TITLE
Feature Request: end-user API for programmatic management of deployment

### ISSUE THREAD

**Issue by peterloron** [helm/helm#3663]
We currently use Helm for managing things we deploy to Kubernetes. We would like to leverage this in our chatbot and Jenkins CI/CD. Currently the only way to perform these operations is to shell out and call the helm cli tool. This is fragile and hard to catch error cases and status.

Having an "end-user" API would be a fantastic improvement.

**Comment by bacongobbler** [comment]
Hey @peterloron, have you taken a look at pkg/helm? There's one bug I'm aware of in Helm v2.8.2 which I've submitted a bugfix for in #3661, but otherwise you should just be able to interact with Helm using that client.

For example:

```
package main

import (
	"log"

	"k8s.io/helm/pkg/helm"
)

const (
	tillerHost = "127.0.0.1:44134"
)

func main() {

	helmClient := helm.NewClient(helm.Host(tillerHost))
	_, err := helmClient.ListReleases()
	if err != nil {
		log.Fatalf("err: %v", err)
	}
}
```

For languages other than Go, others are working on them as seen in #3031, but there aren't any official "blessed" SDKs from the community.

Hope this answers your question!

**Comment by peterloron** [comment]
Ah! That may work. I'll check it out.

**Comment by t00f** [comment]
Hi there,

Helm is well designed and could be improved to ease its use as a Golang library.

Today, cobra commands are doing some logic that could be done in another package. For instance:
* `helm init` ensures all the directory are available 
* `helm search` is building the index, searching in the index based on the parameters. 

If an application tries to use the search capability, it will have to reimplement the logic of the `run()` method.

We should be able to have a package `helm` that would provide the method `Search(...)` - with all the typed parameters - that the cobra command could call in its `run()` after it has parsed all the parameters.

> See [search](https://github.com/kubernetes/helm/blob/master/cmd/helm/search.go#L73)

That would be awesome !
Chris

**Comment by t00f** [comment]
Hi guys,

Please allow me to follow up on this subject.

Let me try to be more specific with the example of the `create` command as it is very simple.

My suggestion consists of exposing a package named `helmlib` that could be imported in any other external golang code.

### Current Status
In the current state, the command is doing some logic in a `run` method that is private. Sometimes,
it handles a looooot of things like in [search](https://github.com/kubernetes/helm/blob/master/cmd/helm/search.go#L75) or [install](https://github.com/kubernetes/helm/blob/master/cmd/helm/install.go#L216).

(Ref: Extract from [create.go](https://github.com/kubernetes/helm/blob/master/cmd/helm/create.go#L64))
```golang
func newCreateCmd(out io.Writer) *cobra.Command {
	cc := &createCmd{out: out}

	cmd := &cobra.Command{
		Use:   "create NAME",
		Short: "create a new chart with the given name",
		Long:  createDesc,
		RunE: func(cmd *cobra.Command, args []string) error {
			cc.home = settings.Home
			if len(args) == 0 {
				return errors.New("the name of the new chart is required")
			}
			cc.name = args[0]

                         // run is private and sometimes handles a lot of things. 
                         // Take a look at search
                         // or install command for instance...
			return cc.run()
		},
	}

	cmd.Flags().StringVarP(&cc.starter, "starter", "p", "", "the named Helm starter scaffold")
	return cmd
}
```


### Suggestion
Decoupling the command from the logic would help others to use helm as a library.
```golang
func newCreateCmd(out io.Writer) *cobra.Command {

	var starter string

	cmd := &cobra.Command{
		Use:   "create NAME",
		Short: "create a new chart with the given name",
		Long:  createDesc,
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return errors.New("the name of the new chart is required")
			}

			// Call to the library from the CLI
			// This call can be made from any Go code that wants to use helm as a library.
			return helmlib.Create(settings, out, args[0], starter)
		},
	}

	cmd.Flags().StringVarP(&starter, "starter", "p", "", "the named Helm starter scaffold")

	return cmd
}
```
In the suggestion above, `helmlib` is an additional package that handles all the business logic. Something like:
```golang
// createStruct contains any information.
// Not sure if it is still necessary here...
type createStruct struct {
	home    helmpath.Home
	name    string
	out     io.Writer
	starter string
}

// Create allows to create a new chart with the given name.
func Create(settings helm_env.EnvSettings, out io.Writer, name string, starter string) error {
	cc := createStruct{out: out}

	cc.home = settings.Home
	cc.name = name

	chartname := filepath.Base(name)
	cfile := &chart.Metadata{
		Name:        chartname,
		Description: "A Helm chart for Kubernetes",
		Version:     "0.1.0",
		AppVersion:  "1.0",
		ApiVersion:  chartutil.ApiVersionV1,
	}

	if starter != "" {
		// Create from the starter
		lstarter := filepath.Join(cc.home.Starters(), cc.starter)
		return chartutil.CreateFrom(cfile, filepath.Dir(name), lstarter)
	}

	_, err := chartutil.Create(cfile, filepath.Dir(name))
	return err
}
```

In that way, in any project, I can use the official k8s package manager by calling
```golang
import "k8s.io/helm/helmlib"
// ...
helmlib.Create(settings, out, name, starter)
```

I am willing to help, but first I would need your feedback first :)
Is there any plan to move in that direction ?

Thanks,

Chris

**Comment by t00f** [comment]
Found the following statement in [helm v3](https://github.com/kubernetes-helm/community/blob/master/helm-v3/000-helm-v3.md#the-basic-architecture) proposal:
> By design, the Helm library must be usable as a standalone library

**Comment by bacongobbler** [comment]
@rajarajanpsj what @t00f is suggesting is already possible through pkg/helm (see my above comment [here](https://github.com/helm/helm/issues/3663#issuecomment-372436053)). One such project that uses pkg/helm quite extensively is [draft](https://github.com/Azure/draft/) so that project may be a good reference point to also take a look at.

Are there specific parts of the API you're aware of which we need may want to consider pulling out of there and pull them into `pkg/`?

**Comment by t00f** [comment]
@bacongobbler,

Unfortunately, a lot of parameters are handled in the command itself. If you take a look at the [install](https://github.com/helm/helm/blob/master/cmd/helm/install.go#L225) for example, it handles:
* computation of the values
* load the chart and the requirements
* etc.

If I need to create a script that installs a chart, I will need to reproduce what the code of the run command is doing.

**Comment by t00f** [comment]
@bacongobbler Do you see what I am talking about with the example of the install command ? Any news about this ticket ?

**Comment by bacongobbler** [comment]
Does the example in https://github.com/helm/helm/issues/3663#issuecomment help at all?

**Comment by robel-yemane** [comment]
Following @bacongobbler 's example  [here](https://github.com/helm/helm/issues/3663#issuecomment-372436053)
I keep getting : `2019/01/03 16:06:28 error: context deadline exceeded
exit status 1`, am I missing something?

**Comment by bacongobbler** [comment]
is tiller listening on localhost, port 44134?

**Comment by robel-yemane** [comment]
good point, I haven't done anything to expose it. So, while testing you can expose tiller on localhost, but when you deploy your application, would you have to create a service to enable your application to talk to tiller on that port?

**Comment by bacongobbler** [comment]
Either that or use the existing `kubectl port-forward` APIs like how Helm uses it today.

https://github.com/helm/helm/blob/master/pkg/helm/portforwarder/portforwarder.go

See https://github.com/helm/helm/blob/5a404f114e68fcea75ada9499bcc43daceca674a/cmd/helm/helm.go#L185-L206 for an example.

**Comment by robel-yemane** [comment]
cheers @bacongobbler !!!

**Comment by bacongobbler** [comment]
Closing this issue as too generic to reasonably close out. If there are particular sections of the codebase that should be refactored into a package, we'd love a PR in the dev-v3 branch.

See also #5365 for some ongoing efforts in the Helm 3 dev branch.
