### ISSUE TITLE
Helm should safeguard from overwriting successful deployments

### ISSUE THREAD

**Issue by Evesy** [helm/helm#3668]
Hi,

**Helm/Tiller Version:** 2.8.2
**Kubernetes:** 1.8.7-gke.0

Tiller's max history value is observed for all deployments, including successful & failed deployments. As a result of this it's plausible that a succession of failed deployments can completely wipe out any history of a successful release, making it impossible to rollback, and also release forward.

Take for example a simple chart that deploys a single secret:

```
apiVersion: v1
kind: Secret
metadata:
  name: helm-testing-secret
type: Opaque
data:
  key.json: dGVzdHZhbA==
```

I can deploy this successfully:

```
REVISION	UPDATED                 	STATUS  	CHART             	DESCRIPTION
1       	Tue Mar 13 18:12:09 2018	DEPLOYED	helm-testing-0.1.0	Install complete
```

However if I then change the value to something invalid (i.e. a random string that is not base64) and deploy it I get a failure:

```
REVISION	UPDATED                 	STATUS  	CHART             	DESCRIPTION
1       	Tue Mar 13 18:12:09 2018	DEPLOYED	helm-testing-0.1.0	Install complete
2       	Tue Mar 13 18:12:36 2018	FAILED  	helm-testing-0.1.0	Upgrade "helm-testing" failed: failed to create patch: fa...
```

With enough failed deployments (i.e. attempted fixes), you will eventually reach your configured tillers history limit and the initial successful deployment is overwritten:
```
REVISION	UPDATED                 	STATUS	CHART             	DESCRIPTION
2       	Tue Mar 13 18:12:36 2018	FAILED	helm-testing-0.1.0	Upgrade "helm-testing" failed: failed to create patch: fa...
3       	Tue Mar 13 18:12:43 2018	FAILED	helm-testing-0.1.0	Upgrade "helm-testing" failed: failed to create patch: fa...
4       	Tue Mar 13 18:12:46 2018	FAILED	helm-testing-0.1.0	Upgrade "helm-testing" failed: failed to create patch: fa...
5       	Tue Mar 13 18:12:50 2018	FAILED	helm-testing-0.1.0	Upgrade "helm-testing" failed: failed to create patch: fa...
```

I couldn't find in the docs exactly what the procedure is when tackling a failed deployment, whether you should always rollback, or whether it is possible to deploy forward from the last known good state.

There was some discussion (i.e. https://github.com/kubernetes/helm/issues/2437) about adding safeguards (`If a release fails, don't allow an upgrade without first doing a rollback to a known-good version`) however I don't believe there was any conclusion on doing that.

Right now because of this we have resources in Kubernetes that are in a limbo state, as they can no longer be deployed via helm without first purging them.

Any thoughts would be appreciated

**Comment by Stono** [comment]
@bacongobbler any chance you could help us out with this, even if its just some short term mitigating action.

We are in this state:
```
❯ helm history helm-cmp-signals-platform
REVISION        UPDATED                         STATUS  CHART                                   DESCRIPTION
130             Tue Mar 13 13:30:06 2018        FAILED  helm-cmp-signals-platform-0.1.320       Upgrade "helm-cmp-signals-platform" failed: Job.batch "cr...
131             Tue Mar 13 17:05:36 2018        FAILED  helm-cmp-signals-platform-0.1.320       Upgrade "helm-cmp-signals-platform" failed: no ConfigMap ...
132             Tue Mar 13 17:08:17 2018        FAILED  helm-cmp-signals-platform-0.1.320       Upgrade "helm-cmp-signals-platform" failed: no ConfigMap ...
133             Tue Mar 13 17:09:43 2018        FAILED  helm-cmp-signals-platform-0.1.320       Upgrade "helm-cmp-signals-platform" failed: no ConfigMap ...
```

Basically we would be happy to just FORCE 133 or similar to be "DEPLOYED" as we can then forward fix the issue that caused the failure?

**Comment by Stono** [comment]
Be awesome if we could get some sort of response even if it's to say it can't be done....

**Comment by bacongobbler** [comment]
It can be done... But not gracefully.

Unfortunately you're in a bit of a pickle. I was explaining to @Evesy [on Slack yesterday](https://kubernetes.slack.com/archives/C0NH30761/p1520961507000410) that you can run `helm upgrade --install --force` if you're on v2.8.2, or `helm delete` and `helm install --replace` on previous releases, but AFAIK there's no way to gracefully upgrade yourself out of this state. It can't perform a graceful install because a FAILED state means that the deployed state of the application is in an unknown state (and therefore cannot guarantee that upgrades will work), and it can't roll back to a known working state because there are no good states to roll back.

Will that work?

**Comment by Stono** [comment]
We cannot do either of those things as this is a production ELK stack dealing with 10k+ events/sec.  Delete and recreate is a no go.

We know what caused the fail state so we would be OK with the risk of forcefully changing the state, as ungraceful as that may be!

**Comment by Stono** [comment]
Where we are at right now is deploying it to another temporary cluster and copying the configmap back to this one to trick helm.  A hell of a lot of effort (and cost whilst running) considering it is a 15 node, 240vCPU and not even sure it will work.

**Comment by Teddy-Schmitz** [comment]
We just got hit by this as well.  At the very least if this cannot be fixed some kind of warning should be added to make sure people are aware of the risk when enabling this function.

**Comment by bacongobbler** [comment]
This was fixed in more recent versions of Helm. Please upgrade to receive the fix. Thanks.
