### ISSUE TITLE
`make bootstrap` fails

### ISSUE THREAD

**Issue by arschles** [helm/helm#367]
due to a glide error:

```console
ENG000656:helm aaronschlesinger$ make bootstrap
go get -u github.com/golang/lint/golint github.com/mitchellh/gox
glide install
Oops! Lock file does not match YAML configuration. Consider running 'update'
make: *** [bootstrap] Error 1
```

**Comment by technosophos** [comment]
Does running `glide up` fix it?

**Comment by technosophos** [comment]
I think the problem was the broken hash fix that was added to glide 0.8.2

**Comment by mattfarina** [comment]
@arschles If you're not on Glide 0.8.2 can you please update to that. I think that will fix it. Sorry about the inconvenience.

**Comment by arschles** [comment]
@technosophos @mattfarina yep, I was on glide 0.8.2 and `glide up` fixed it. I'll see if I can submit a PR later today

**Comment by Barberrrry** [comment]
I'm using glide 0.8.2 installed by homebrew. I have the same problem: _glide install_ always returns __Oops! Lock file does not match YAML configuration. Consider running 'update'__ even after _glide up_.

**Comment by mattfarina** [comment]
Did a fix for this ever happen? I'm happy to jump on it if needed.

**Comment by mboersma** [comment]
> Did a fix for this ever happen?

Yes...somewhere along the line. It hasn't been an issue in recent memory.

(See also #438 and #436 for some `glide` updates that could use maintainer reviews.)
