### ISSUE TITLE
Annotation "helm.sh/resource-policy: keep" should never delete a resource

### ISSUE THREAD

**Issue by alebsack** [helm/helm#3673]
I noticed that the annotation "helm.sh/resource-policy: keep" on a resource is not honored when the name of the resource is changed.

This is a big problem in my case where I used the annotation on a namespace, and a misconfiguration of the name resulted in the removal of the namespace.

**Comment by pastukhov** [comment]
It also delete resource when ```helm upgrade``` cause

**Comment by jsravn** [comment]
Just got bitten by this. Also if you remove the resource from the helm chart (by accident), helm deletes it! Whoops.

**Comment by jsravn** [comment]
@bacongobbler what are your thoughts on this bug? Would you be open to a contribution to fix this?

**Comment by jsravn** [comment]
I made https://github.com/helm/helm/pull/5225 to try and fix this.

**Comment by mlorenzo-stratio** [comment]
Helm still does delete resources marked with `"helm.sh/resource-policy: keep"` when running `helm uninstall`
I see it was fixed for `Update` method but not for `Delete` method, am I right?
