### ISSUE TITLE
Ability to reference release resource info in NOTES.txt

### ISSUE THREAD

**Issue by stevelipinski** [helm/helm#3676]
Currently NOTES.txt can only reference template Objects (Built-Ins, Values, etc.)

It would be very helpful if there was a way to reference values of the now-deployed chart as well.  For example, if I have a chart that creates a NodePort service without specifying the nodePort (dynamically assigned) - I cannot reference that K8s-assigned port for output in the NOTES.txt.

For example, to have the following in NOTES.txt:
You can reach myservice from outside the cluster via:
somefqdn.for.cluster:{{ .Services.myservice.nodePort }}

Yes, I can output some long, kubectl command instructing the user how to obtain that value, but that is quite cumbersome, especially if trying to do this across multiple resources.

**Comment by bacongobbler** [comment]
closing as inactive.
