### ISSUE TITLE
--kube-context should support completion

### ISSUE THREAD

**Issue by rcorre** [helm/helm#3693]
`kubectl --context=` auto-completes kube contexts. `helm --kube-context=` should offer the same completions.

I'm on `2.6.2`, which I know is a bit old, so please close if this is already implemented.

**Comment by bacongobbler** [comment]
I know there hasn't been any activity on the autocompletion side of things for quite some time. If you'd like to make a PR for this, it would be good to see how kubectl handles their autocompletion stuff! :)

**Comment by rcorre** [comment]
I'd love to contribute this. My company is still working out the legal side of allowing us to sign CLA's for OSS contributions, but hopefully I'll have the green light soon.

**Comment by marckhouzam** [comment]
This is now supported for helm v3 as per #6408 

For helm v2, I can port the fix, but I haven't seen much effort going into v2.
If a maintainer would like to see this feature in v2, please let me know.
