### ISSUE TITLE
Symlinking dependency charts into root charts

### ISSUE THREAD

**Issue by Mikulas** [helm/helm#3700]
/kind bug

### Issue

Symlinking root charts (1️⃣) into chart dependencies (2️⃣) makes helm traverse infinitely, consuming memory until crashing. Users are not presented with any error until the process OOM terminates.

```
.
└── charts 1️⃣
    ├── dep-a
    │   ├── Chart.yaml
    │   ├── templates
    │   │   └── ingress.yaml
    │   └── values.yaml
    └── main
        ├── Chart.yaml
        ├── charts -> ../ 2️⃣
        ├── requirements.yaml
        └── values.yaml

```

Reproduced on v2.8.0 and master. This simple repository contains all the files that trigger this issue https://github.com/Mikulas/helm-symlink-charts-demo

Stack trace of the issue: https://github.com/Mikulas/helm-symlink-charts-demo/blob/master/macos-sample.txt

### The code

The issue is in `pkg/sympath/walk.go`

### The fix

Options that come to mind:
- Keep track of visited symlinks. Halt and notify user if cycle was found. This does not make the symlink usable, but at least the problem terminates correctly instead of consuming memory until there is none.
- Limit symlink traversal to some upper bound. This could have very minimal impact on the current implementation, will not break any projects (because it does currently not work at all) and will support all of the valid use-cases. Has lower memory requirement then keeping track of visited links.
- Rewrite the symlink traversal to lazy invocation. Only evaluating the symlink when file is required by helm bypasses the infinite walk. This is most complex change, but fixes the issue and enables the feature. 

I would be happy to attempt contributing any of those fixes.

**Comment by jascott1** [comment]
Hi @Mikulas 

A simple depth limit might suffice. We look forward to your contribution!

**Comment by OndraZizka** [comment]
Depth limit is not a good solution. You need to use a map of absolute canonical paths and check if the walk has been there.

**Comment by Mikulas** [comment]
I honestly think that the depth limit is very pragmatic. This issue does not warrant a huge refactoring which would be necessary for all the other solutions, as I've already outlined in the original post.

Note that the depth limit only affects symlink nesting and does not break backwards compatibility as symlink nesting does not currently work at all.

**Comment by kwngo** [comment]
Is this still on the roadmap?

**Comment by bacongobbler** [comment]
https://github.com/helm/helm/pull/3726 was closed due to inactivity. If you feel like picking this back up, feel free.

**Comment by bacongobbler** [comment]
closing as inactive.
