### ISSUE TITLE
Install from helm repo by digest

### ISSUE THREAD

**Issue by mradmila** [helm/helm#3723]
Can we add an option to pull down charts by sha256 digest instead of version (which is allowed to change)? Should be a simple fix?

**Comment by dimitarKiryakov** [comment]
Is there any progress on this ?

**Comment by bacongobbler** [comment]
Hi @dimitarKiryakov. This issue was opened nearly two years ago. I don't think anyone has made progress on this feature. Feel like working on something?

**Comment by bacongobbler** [comment]
closing as inactive.
