### ISSUE TITLE
Add Warning when installing or upgrading a deprecated chart

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#3724]
A `Chart.yaml` file has a `deprecated` field. If that is set to true we should tell the end user they are installing or updating a deprecated chart. We shouldn't stop them but a warning would be helpful for end users.

**Comment by kvendingoldo** [comment]
I'll add this to v3.

**Comment by hickeyma** [comment]
@kvendingoldo Thanks for pushing PR #6889 for Helm 3. Do you mind back porting this to Helm 2?

**Comment by kvendingoldo** [comment]
@hickeyma I'll port my change to v2 during the next week

**Comment by bridgetkromhout** [comment]
@mattfarina Do you think this should go into v2 at this point? (Unsure if you agree that it's a bugfix.)

**Comment by jeff-knurek** [comment]
I think with the increase of deprecated charts as the `helm/stable` gets migrated out having this warning in v2 is going to be important for people who are slow to upgrade to v3

@kvendingoldo are you still looking to make the PR for v2?

**Comment by bacongobbler** [comment]
Closing as we are no longer looking at introducing new features for Helm 2.

**Comment by bacongobbler** [comment]
After discussing on the dev call, this seems good to port over to Helm 2. Context has changed as the stable charts repository is slowly deprecating more charts, and the effort to pull this over wouldn't be that large. Net result would be a benefit.

**Comment by bridgetkromhout** [comment]
As the PR has been merged to add this to v2 and it's slated for the next release, and it's already in v3, I'm resolving this issue as complete.
