### ISSUE TITLE
Error: UPGRADE FAILED: pods "..." not found (when "helm upgrade --wait")

### ISSUE THREAD

**Issue by dmaze** [helm/helm#3740]
We have a private chart that contains a half-dozen Deployments, some of which have many replicas (one has 100, one has 45).  Part of our CD pipeline eventually runs a command like:

```sh
helm upgrade --install --recreate-pods --reset-values --wait \
  foo \
  --namespace foo --kube-context ctx \
  --tiller-namespace kube-system \
  --values foo.yaml --values tmp.yaml \
  ./charts/foo
```

We recently upgraded our system from Helm 2.6.0 to Helm 2.8.2.  Since that upgrade, the CD pipeline fails with an error:

```
Error: UPGRADE FAILED: pods "foo-bar-12345678-abcde" not found
```

Running `kubectl describe deployment` shows that the Deployment objects have been correctly updated and the update has progressed successfully.  `kubectl get rs` shows that the `foo-bar-12345678` replica set is the _old_ replica set; there is a newer `foo-bar-2468013579` replica set that has the right number of replicas.

`helm version` reports:

```
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
```

(The CD system is _probably_ running the exact same version, but I can't say that with 100% certainty.)

`kubectl version` reports:

```
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.11", GitCommit:"b13f2fd682d56eab7a6a2b5a1cab1a3d2c8bdd55", GitTreeState:"clean", BuildDate:"2017-11-25T17:51:39Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

(The CD system probably has an older 1.7.x `kubectl`, but I don't think Helm shells out to it.)

Let me know if there's anything else I can provide that can help debug this, including diagnostic flags for running Helm.  I might be able to produce an extract of the chart or the Deployment object YAML, but (up to the level of templating involved) I don't think it's especially complicated.

**Comment by xinzweb** [comment]
+1 got the same error observed on 2.8.2.

```
$ helm version
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by omnilinguist** [comment]
@dmaze did you ever make any more progress on this? I've tried to revive a [discussion|https://kubernetes.slack.com/archives/C0NH30761/p1551159041162200] in the k8s slack about this, where it seems this is somehow correlated with deployments with large replicasets, but also not consistently reproducible?

@bacongobbler might the above correlation give some hints as to what might be going on here?

**Comment by sebglon** [comment]
same for me for 3 of 10 release upgrade with the same chart.
```
helm version
Client: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.6-gke.2", GitCommit:"04ad69a117f331df6272a343b5d8f9e2aee5ab0c", GitTreeState:"clean", BuildDate:"2019-01-04T16:19:46Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by sxnguyen** [comment]
Anyone has a solution for this issue? I'm facing the same thing.  Our helm version is 2.9.1.  Our kubectl version is `v1.12.4`

**Comment by sxnguyen** [comment]
I found the solution for my situation.  I used to run `helm upgrade test . -f upgrade.yaml --recreate-pods --wait --timeout 360`
Now, the solution is to run `helm upgrade test . -f upgrade.yaml --timeout 360`
I have one StatefulSet that does not update without the `--recreate-pods`, so I need to just need to delete the pod manually in our upgrade script.
Hope it helps someone.
Regards,
Scott

**Comment by bacongobbler** [comment]
closing as inactive.
