### ISSUE TITLE
[Helm-Tiller TLS] Avoid Helm reset --force without TLS 

### ISSUE THREAD

**Issue by andresguisado** [helm/helm#3741]
Once TLS configuration is in place and you try to run ``` helm reset ``` you're getting the same error because you need TLS authentication:

```
 $helm reset                                                                                                                   
Error: transport is closing
```

However, there's nothing stopping you to run ```helm reset --force``` and delete Tiller.

Is there any way to lock down TLS with  ```helm reset --force``` command when TLS config is in place?

Thanks!

**Comment by jascott1** [comment]
It does indeed ignore errors from connection setup if `--force` is used.
https://github.com/kubernetes/helm/blob/master/cmd/helm/reset.go#L61

I would think it would (1) have a better error message in your first example and (2) refuse to operate if configured for TLS and not using TLS. 

@SlickNik what do you think?

**Comment by bacongobbler** [comment]
closing as inactive.
