### ISSUE TITLE
[Helm init] Is custom helm installation possible?

### ISSUE THREAD

**Issue by andresguisado** [helm/helm#3749]
Are stable and local helm repositories mandatory?

By the time you run ```helm init --client-only```,  it add the stable and local helm repo by default,  you can change these default helm repos in run time as follows:

```helm init --client-only --stable-repo-url $HELM_STABLE_REPOSITORY_URL --local-repo-url $HELM_LOCAL_ REPOSITORY_URL; ```

What if:

1- I don't want to setup some of those or none of those default helm repos, Can I run something like 
```helm init --client-only --stable-repo-url none --local-repo-url none; ```
to avoid to set any of those defaults repos?

2- I want to custom my helm installation by adding **just one repo** called nor stable nor local, Can I do that in somehow with ```helm init```? 

Trying to avoid the following commands sequence:

* ```helm init --client-only```
* ```helm add repo <my-repo>```
* ```helm delete repo <stable>```
* ```helm delete repo  <local>```

Would be nice to have something like:

```helm init --client-only --stable-repo-url none --local-repo-url none --my-repo $my_repo; ```

**Comment by jascott1** [comment]
Hi @andresguisado 

Im afraid your current workaround is the only way to accomplish this afaik. Unfortunately Im not sure your use case is popular enough to warrant a PR but if we had community support we could have more discussion.

**Comment by wushuzh** [comment]
Hi @jascott1 @andresguisado 

Would you please confirm my init operations of helm (tiller) is correct if my minikube does not have the internet connection but only available with artifactory proxy ?

```
helm init --client-only \
    --stable-repo-url kubernetes-charts-storage-googleapis-com-by-artifactory \
    --local-repo-url artifactory-k8s-chart

helm repo update
helm init --upgrade
```

**Comment by aliasmee** [comment]
+1 @andresguisado 
When running `helm init --client-only`, If can't connect google(kubernetes-charts.storage.googleapis.com) in my network, This will show the following error message:
```bash
Error: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Get https://kubernetes-charts.storage.googleapis.com/index.yaml: dial tcp 172.16.193.22:443: i/o timeout


Error: Couldn't load repositories file (/root/.helm/repository/repositories.yaml).
You might need to run `helm init` (or `helm init --client-only` if tiller is already installed)
```

**Comment by bacongobbler** [comment]
Add the `--skip-refresh` flag for a complete offline `helm init`. :)

So in your example, @aliasmee:

```
helm init --client-only
```

I'm not entirely sure that's what @andresguisado is asking for though.

**Comment by aliasmee** [comment]
hi, @bacongobbler , thanks for your quick reply

I have tried to add the `--skip-refresh` flag, but if I encounter a dependent chart package, when I execute the command `helm package some_chart` there will be another error:
```bash
Error: open /root/.helm/repository/cache/stable-index.yaml: no such file or directory
```

Here is my whole terminal execution history

```bash
/helm_repo_data # helm init --client-only --skip-refresh
$HELM_HOME has been configured at /root/.helm.
Not installing Tiller due to 'client-only' flag having been set
Happy Helming!

/helm_repo_data # helm package staging/optimus/
Error: found in requirements.yaml, but missing in charts/ directory: sidekiq-slow, faktory, sidekiq-sentry, sidekiq

/helm_repo_data # cat staging/optimus/requirements.yaml 
dependencies:

  - name: sidekiq-slow
    version: v0.1.0
    repository: "file://../sidekiq-slow"

  - name: faktory
    version: v0.1.0
    repository: "file://../faktory"

  - name: sidekiq-sentry
    version: v0.1.0
    repository: "file://../sidekiq-sentry"

  - name: sidekiq
    version: v0.1.0
    repository: "file://../sidekiq"

/helm_repo_data/staging/optimus # helm dep update
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
	Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: getsockopt: connection refused
...Unable to get an update from the "stable" chart repository (https://kubernetes-charts.storage.googleapis.com):
	Get https://kubernetes-charts.storage.googleapis.com/index.yaml: dial tcp 172.16.193.22:443: i/o timeout
Update Complete. ⎈Happy Helming!⎈
Error: open /root/.helm/repository/cache/stable-index.yaml: no such file or directory

```

I just want to simply runing a helm private repo. thanks

**Comment by jascott1** [comment]
Hi @aliasmee Sorry for the delayed response. If you are still having an issue and think its a bug with packaging behavior could you please open a new issue so we can track it? Im going to close this as the original request was answered. Thanks!
