### ISSUE TITLE
'helm search' returns names in all lowercase even if they have uppercase characters

### ISSUE THREAD

**Issue by lostmimic** [helm/helm#3751]
running helm search, the name of all charts return in only lowercase but the proper case is needed for things like 'helm install'

Helm version 2.8.2

**Comment by bacongobbler** [comment]
related: #2876

**Comment by JoshCollinsMSFT** [comment]
This is pretty easy to reproduce.  Is there another bug tracking this?  If not can we get some traction?

**Comment by bacongobbler** [comment]
closing as inactive.
