### ISSUE TITLE
`--values` to support a directory of value files

### ISSUE THREAD

**Issue by jstrachan** [helm/helm#3786]
It would be nice to be able to separate out a `values.yaml` into an arbitrary number of separate yaml files for easier maintenance and to work better in GitOps.

We're using helm + GitOps for managing [promotion to environments](http://jenkins-x.io/about/features/#promotion) on [Jenkins X](http://jenkins-x.io/) and its working great so far. 

Each environment (Staging, Production etc) is actually a single helm chart in a git repository with dependent charts in a `requirements.yaml` and environment specific configuration for each app in a single `values.yaml` file. It would be nice to be able to split out the `values.yaml` file into, say, .a file per app/chart (if need be) and so have a `values` directory and point helm at them all.

e.g.

```
$ find . 
Chart.yaml
templates/
requirements.yaml
values/
  app1.yaml
  app2.yaml

$ helm upgrade --install --values values
```

**Comment by bacongobbler** [comment]
This seems like a good candidate for a plugin. While this does sound like it's a solid use case, I'd probably avoid bringing this into core unless there was significant demand from the community.

**Comment by nico-ulbricht** [comment]
I created a plugin to attempt to solve this issue, as I was also heavily in need of this for our infrastructure. In case you urgently need a solution, feel free to use: https://github.com/nico-ulbricht/helm-multivalues

**Comment by embik** [comment]
I'm using symlinks to dynamically link configuration snippets into a "values" folder. IMHO this would be of value (he) in Helm core but I can see this being scripted into our deployment scripts. Just adding my two cents here, "demand from the community" and all that :)

**Comment by velcrine** [comment]
Demand +1

**Comment by yan-zhao-unity** [comment]
Demand +1

**Comment by bacongobbler** [comment]
In the interest of preventing spam to users subscribing to this thread, please add a :+1: to the OP instead of commenting "+1". That way we can keep the conversation relevant to the discussion at hand. I've gone ahead and deleted those comments. Thanks!

**Comment by webdz9r** [comment]
> I created a plugin to attempt to solve this issue, as I was also heavily in need of this for our infrastructure. In case you urgently need a solution, feel free to use: https://github.com/nico-ulbricht/helm-multivalues

this above is still a good solution in 2022 - unless there is an official support for this, it's pretty lightweight and useful

**Comment by CiucurDaniel** [comment]
I still look forward to such a feature. 
I have charts with multiple requirements and a directory `/values` where each app has it's values:
```
values/ 
     app1.yaml
     app2.yaml
      ....
```

Would love to be able to do only `helm install -f values/` as it would make the CI more simple. if I have to specify each file with the -f flag then if I add a new dependency I also have to edit the CI definition.

**Comment by isikdos** [comment]
It would be nice for cases where you have multiple valuesfiles per application, but you don't necessarily want to support a static set of names of valuesfiles for every application. 

For instance: 
- connectionstrings and endpoints
- feature flags
- performance related settings
