### ISSUE TITLE
Inconsistent behavior with invalid semver

### ISSUE THREAD

**Issue by rcorre** [helm/helm#3793]
You can package and index a chart with an invalid semver, yet the index will then claim it doesn't include that chart:

```
package main

import (
	"fmt"

	"k8s.io/helm/pkg/chartutil"
	"k8s.io/helm/pkg/proto/hapi/chart"
	"k8s.io/helm/pkg/repo"
)

func main() {
	c := &chart.Chart{
		Metadata: &chart.Metadata{
			Name:    "foo",
			Version: "0.1.0.1", // invalid semver
		},
	}

	_, err := chartutil.Save(c, ".")
	if err != nil {
		panic(err)
	}

	idx, err := repo.IndexDirectory(".", "http://example.com")
	if err != nil {
		panic(err)
	}

	for _, versions := range idx.Entries {
		for _, ver := range versions {
			fmt.Println(ver.Name, ver.Version) // prints foochart 0.1.0.1
		}
	}

	fmt.Println(idx.Has("foochart", "0.1.0.1")) // prints false
}
```

I think one of the following should be true:

1. `index.Has` can handle invalid semvers
2. `helm repo index` omits invalid semvers
3. `helm package` fails if the version is invalid

I realize that `helm lint` will call this out, but that doesn't prevent people from creating charts that will behave inconsistently. If the index functions won't work properly with such a chart, then it shouldn't be allowed to enter the index in the first place.

Library version: `v2.8.0-rc.1-285-gd32a6ef6`

**Comment by bacongobbler** [comment]
@rcorre do you feel like working on a fix for this?

**Comment by rcorre** [comment]
I'll take a look. Any preference between the 3 options I presented above?

**Comment by bacongobbler** [comment]
closing as inactive.
