### ISSUE TITLE
helm upgrade --reset-values does not reset values not specified in the chart

### ISSUE THREAD

**Issue by nicksnyder** [helm/helm#3798]
Setup
1. I have a chart deployed
2. Using `kubectl edit deployment/myservice` someone adds a dummy/secret environment variable that isn't part of the chart

On the next deploy of the chart, I want to make sure any such edits disappear (without knowing what edits were made a priori).

I tried:
- `helm upgrade`
- `helm upgrade --force`
- `helm  upgrade --reset-values`

But none of these removed the variable added in step 2.

**Comment by bacongobbler** [comment]
Helm cannot currently manage the "live" state of resources managed through `kubectl`. It performs diffs against the previous state of what was requested to install.

See https://github.com/kubernetes/helm/issues/2070 for more background context/ideas

**Comment by nicksnyder** [comment]
That issue when stale so it is unclear to me if helm wants to support the requested use case or not. Using the example there, I would expect replica count to go back to 4 after a deploy.

The whole k8 philosophy is “assert a state on a resource and heal if it diverges from the desired state”. I am perplexed why helm would not support this basic use case for deploys.

**Comment by bacongobbler** [comment]
Fully understood, but when we make a promise to be backwards  compatible, we really mean it. Warts and all. ;)

We're planning on fixing this for Helm 3. Proposals for Helm 3 can be found here: https://github.com/kubernetes-helm/community/tree/master/helm-v3

**Comment by nicksnyder** [comment]
For v2 it would be perfectly fine to make this an opt-in behavior via some new option, but I understand if this is more of a fundamental change that belongs in v3.

Is there a specific proposal that is particularly relevant to this?

**Comment by CarloWakefield** [comment]
Has this improvement been implemented in Helm 3?

**Comment by CarloWakefield** [comment]
> Fully understood, but when we make a promise to be backwards compatible, we really mean it. Warts and all. ;)
> 
> We're planning on fixing this for Helm 3. Proposals for Helm 3 can be found here: https://github.com/kubernetes-helm/community/tree/master/helm-v3

Has this improvement been implemented in Helm 3?

**Comment by bacongobbler** [comment]
Yes. https://v3.helm.sh/docs/faq/#improved-upgrade-strategy-3-way-strategic-merge-patches

**Comment by ruohola** [comment]
I'm I right in that Helm 3 still doesn't touch manually set environment variables that are not in the chart?

Based on my testing, if one has ran:
```
$ kubectl set env deployment/my-deployment testenv=foo
```

And then runs `helm upgrade --reset-values …`, if the chart had no mention of `testenv`, the `testenv=foo` value still stays in the newly booted pods.

Is this the expected behavior and is this documented somewhere?
