### ISSUE TITLE
Delete sub-chart value key from parent-chart

### ISSUE THREAD

**Issue by pribor** [helm/helm#3804]
It seems that it is not possible to delete value key of sub-chart from parent-chart.

```
./values.yaml
name: parent
test.resources: null
```

```
./charts/test/value.yaml
name: child
resurces:
  requests:
    cpu: 500m
    memory: 2Gi
```

I would expect that after the merge the result will be:
```
./charts/test/value.yaml
name: child
```

Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-12T16:29:47Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.8-gke.0", GitCommit:"6e5b33a290a99c067003632e0fd6be0ead48b233", GitTreeState:"clean", BuildDate:"2018-02-16T18:26:58Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}

GKE

**Comment by deitmerit** [comment]
There is a typo in "resurces" in charts/test/values.yaml. If this is really your file's content, that would explain the problem.
