### ISSUE TITLE
Helm test to deploy pods concurrently

### ISSUE THREAD

**Issue by hliu9** [helm/helm#3819]
How can we leverage `helm test` to run tests across multiple pods concurrently?

Use case:
We have a ton of tests that need to run in individual pods. These tests are time-consuming. So we would like to split them up to run across multiple pods in order to reduce the overall test time. 

The problem:
`helm test` seems to deploy one pod at a time. If tests can be isolated into separate containers, they should not depend on one another, and deploying the test containers concurrently can greatly reduce the overall test duration.

**Comment by michelleN** [comment]
hey @hliu9 - great suggestions. We could add a `--concurrent` flag on `helm test` that would create all test pods and keep track of their statuses until they are all complete (or until the timeout specification).
Is that along the lines of what you're looking for?


Sidenote: It'd be cool to build a helm plugin for test that uses brigade under the hood. cc/ @technosophos @adamreese

**Comment by hliu9** [comment]
@michelleN yes, that's precisely what I had in mind!

**Comment by bacongobbler** [comment]
closing as inactive.
