### ISSUE TITLE
Some resources are not deleted, but the release is purged.  #3815

### ISSUE THREAD

**Issue by AlawnWong** [helm/helm#3827]
helm version : 2.7.0  
kubectl version: 1.7.4
 
### The problem details (i not screenshot)：
When I purge the release，some resources are not deleted and some are deleted ,  but the release is purged. 
So some resources remain, and the user have to manual clean these.
Constantly,  the uninstall release cost a long time, because  k8s delete some  resources take a long time.
Then, I find the reason is , the etcd is abnormal, "etcdserver: request timed out" , when I  purge the release.  however , the release's configmap can be deleted.

### Problem of repetition:
Create a k8s cluster, with only 1 master.   
helm purge a release, then stop the etcd, immediately.  
And wait 100s, restart the etcd.
    one input:
           helm delete xxx --purge   
    other input:
           systemctl stop etcd ;  sleep 100s ;  systemctl start etcd ;  

### I proposal : 
   if some resources   are not deleted , the release  cannot be purged.  #3815

**Comment by michelleN** [comment]
hey @AlawnWong - Helm relies on the Kubernetes control plane components to be up and running smoothly (in this case - etcd and the apiserver) in order to carry out its tasks. However, it would be strange to not be able to purge the release once etcd is back up again. Could you give me some more information on the output of Helm when the delete operation fails and can you tell me what the output of `helm list -a` is?

**Comment by AlawnWong** [comment]
@michelleN  
The release is not exist in the output of `helm list -a` . Because the release's configmap is deleted.

**Comment by jody-frankowski** [comment]
I have had more or less the same problem.

I did `helm delete ... --purge` which returned no error. However I could see in the logs that some operation timed out: `[tiller] 2018/04/25 15:54:04 warning: Release jittery-chicken post-delete spinnaker/templates/hooks/delete-jobs.yaml could not complete: timed out waiting for the condition`.
The problem was simply that the delete Job could not complete because of resources limits (the Job's Pod couldn't be scheduled) and later a service account error.
As far as I can tell, the apiserver was running fine, because I was constantly querying it.

**Comment by PetteriVaarala** [comment]
I have same issue when deleting pods takes more than 300s, timeout option does not have an expected effect.

`helm delete --timeout 600 --purge rabbitmq`

Helm version
```
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
```

k8s version
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.11", GitCommit:"1df6a8381669a6c753f79cb31ca2e3d57ee7c8a3", GitTreeState:"clean", BuildDate:"2018-04-05T17:24:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.11", GitCommit:"1df6a8381669a6c753f79cb31ca2e3d57ee7c8a3", GitTreeState:"clean", BuildDate:"2018-04-05T17:16:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

Tiller logs
```
tiller-5977475476-gknvj tiller [kube] 2018/04/26 12:27:32 Doing get for StatefulSet: "rabbitmq"
tiller-5977475476-gknvj tiller [kube] 2018/04/26 12:27:33 get relation pod of object: default/StatefulSet/rabbitmq
tiller-5977475476-gknvj tiller [storage] 2018/04/26 12:27:34 getting release history for "rabbitmq"
tiller-5977475476-gknvj tiller [tiller] 2018/04/26 12:27:35 uninstall: Deleting rabbitmq
tiller-5977475476-gknvj tiller [tiller] 2018/04/26 12:27:35 executing 2 pre-delete hooks for rabbitmq
tiller-5977475476-gknvj tiller [tiller] 2018/04/26 12:27:35 hooks complete for pre-delete rabbitmq
tiller-5977475476-gknvj tiller [storage] 2018/04/26 12:27:35 updating release "rabbitmq.v5"
tiller-5977475476-gknvj tiller [kube] 2018/04/26 12:27:35 Starting delete for "rabbitmq" Service
tiller-5977475476-gknvj tiller [kube] 2018/04/26 12:27:35 Starting delete for "rabbitmq" Service
tiller-5977475476-gknvj tiller [kube] 2018/04/26 12:27:35 Starting delete for "rabbitmq" StatefulSet
tiller-5977475476-gknvj tiller [kube] 2018/04/26 12:27:35 Using reaper for deleting "rabbitmq"
tiller-5977475476-gknvj tiller [storage] 2018/04/26 12:27:47 listing all releases with filter
tiller-5977475476-gknvj tiller 2018/04/26 12:33:26 uninstall: Failed deletion of "rabbitmq": timed out waiting for "rabbitmq" to be synced
```

**Comment by jascott1** [comment]
Hi @AlawnWong 

It sounds like it could be similar to these statefulset related issues:

https://github.com/helm/helm/issues/4248
https://github.com/helm/helm/issues/3889

**Comment by AlawnWong** [comment]
@jascott1  
I think this is tiller's bug.
when delete release with '--purge' ,
If deleting some resources (statefulset) failed, the release's configmap still be deleted.

I think should not delete the release's configmap. 
User should deal the problems and try to delete again.

**Comment by bacongobbler** [comment]
this was fixed in later releases. Please try upgrading to a newer version of helm and kubernetes and you should be good to go as per https://github.com/helm/helm/issues/3889#issuecomment-389443840. Thanks!
