### ISSUE TITLE
helm install --dry-run should output line numbers

### ISSUE THREAD

**Issue by mFarghaly** [helm/helm#3851]
I found it confusing when I get YAML parsing error with reference to line number, especially if there's template expansion. 
It will be helpful if line numbers are printed along with each yaml line.

**Comment by consideRatio** [comment]
Yes this would be great! I have found the errors from helm install to be really hard to debug due to a lack of trace where the error originates from.

**Comment by notque** [comment]
Would save a lot of wasted debug time if we had proper line numbers to the templates.

**Comment by bacongobbler** [comment]
This would be a compatibility breaker, but this would be a good enhancement if hidden behind a feature flag. Many users pipe data from `helm install --dry-run --debug` (AKA `helm template`) to `kubectl apply`. Adding line numbers for the default case would break that assumption.

**Comment by bacongobbler** [comment]
alternatively, you can pipe `helm template` output to `less -N` and achieve the same effect.

**Comment by bacongobbler** [comment]
closing as inactive.
