### ISSUE TITLE
Issue with Non-existing certs on Helm Chart creation

### ISSUE THREAD

**Issue by hertzknight** [helm/helm#3862]
I am unable to install anything from my repo anymore. I am able to find it using helm repo list and see what is inside it using helm search <repo>; however, when i try to install from it, it states it could not find the file (this worked before the weekend). I also would get the following error message when i tried to add the repo or update it. It looks like it is trying to to run it as https instead of http. Is there to ensure it is running with http?

Error message:
Error: Looks like "http://<ip-address>/<repo>" is not a valid chart repository or cannot be reached: Get https://<ip-address>/<repo>/index.yaml: x509: cannot validate certificate for <ip-address> because it doesn't contain any IP SANs

Output of `helm version`:
Client: &version.Version{SemVer:"v2.6.0", GitCommit:"5bc7c619f85d74702e810a8325e0a24f729aa11a", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.0", GitCommit:"5bc7c619f85d74702e810a8325e0a24f729aa11a", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T07:00:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.14-gke.1", GitCommit:"78686f2c9f64430a0a60f90a9b84277c25cab5c0", GitTreeState:"clean", BuildDate:"2018-03-13T17:50:04Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

**Comment by bacongobbler** [comment]
hi @hertzknight! Can you show the output of `helm repo list`?

**Comment by hertzknight** [comment]
@bacongobbler it shows the correct url and repo name.

NAME            URL
stable          https://kubernetes-charts.storage.googleapis.com
local           http://<ip-address>/charts
fgss            http://<ip-address>/fgss-helm
monocular       https://kubernetes-helm.github.io/monocular

I will try a more current version of helm and see if that works.

**Comment by hertzknight** [comment]
I have updated both to v2.8.2; however, it did not fix the issue. A friend tried to do our install scripts, as we kill the server every night. She has to put her ssh-key in manually during the install process and it worked at that point. I would like to say it may be that it won't taking my ssh key anymore, but it works for everything else.
