### ISSUE TITLE
[tiller] failed install perform step: release teq-ns failed: namespaces "teq-ns" not found

### ISSUE THREAD

**Issue by markns** [helm/helm#3863]
Hi, we just had a problem in our GKS cluster where the helm release failed because the "namespace was not found".

```
[tiller] 2018/04/10 12:53:27 preparing install for teq-ns
[storage] 2018/04/10 12:53:27 getting release history for "teq-ns"
[tiller] 2018/04/10 12:53:27 rendering user chart using values
[tiller] 2018/04/10 12:53:27 performing install for teq-ns
[tiller] 2018/04/10 12:53:27 install hooks disabled for teq-ns
[storage] 2018/04/10 12:53:27 getting release history for "teq-ns"
[storage] 2018/04/10 12:53:30 creating release "teq-ns.v1"
[kube] 2018/04/10 12:53:30 building resources from manifest
[kube] 2018/04/10 12:53:30 creating 14 resource(s)
[tiller] 2018/04/10 12:53:30 warning: Release "teq-ns" failed: namespaces "teq-ns" not found
[storage] 2018/04/10 12:53:30 updating release "teq-ns.v1"
[tiller] 2018/04/10 12:53:30 failed install perform step: release teq-ns failed: namespaces "teq-ns" not found
```

The namespace is/should be created as part of the chart, and the chart has been working for several weeks without problem now. Does anyone have an idea what could have caused this? Is it possible to increase the log level on the tiller server?

`Tiller Version`:
[main] 2018/04/04 11:08:27 Starting Tiller v2.8.0 (tls=false)

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKS 	 1.9.6-gke.0

**Comment by bacongobbler** [comment]
A likely cause is Tiller being unable to list namespaces due to RBAC permissions. Can you check and verify that tiller's been properly configured as per https://docs.helm.sh/using_helm/#role-based-access-control?

**Comment by markns** [comment]
Tiller is running with the default service account from the kube-system namespace. I'll look into creating the tiller service account as documented. 

But, is it possible this error would be transient if it was an RBAC permission issue? Because re-running a few minutes later allowed the same configuration to succeed.

**Comment by bacongobbler** [comment]
odd. That's the same behaviour @arcticsnowman noticed in https://github.com/kubernetes/helm/issues/3967#issuecomment-384420402; as soon as he rebooted Tiller, everything worked again.

Do you have an idea on what was the underlying issue causing this particular bug, or did it go unresolved?

**Comment by bacongobbler** [comment]
ping

**Comment by markns** [comment]
Hey, I think this was happening when we had a namespace yaml in the chart. Since we've changed to specifying the namespace at the helm command line we haven't seen the issue reoccur.

**Comment by jascott1** [comment]
Hi @markns Im going to close this as resolved. Please leave a comment if you would like it reopened. Thanks!
