### ISSUE TITLE
--wait (via DeploymentsReady) does not account for failed RS

### ISSUE THREAD

**Issue by helgi** [helm/helm#3875]
`--wait` is naive as it relates to DeploymentsReady. It does not account for RS failing, for various reasons.

https://github.com/kubernetes/helm/blob/master/pkg/kube/wait.go#L250-L258

My scenario is turning on ResourceQuota, deploying a chart without resource limits that k8s will reject (see below), then adding a resource limit to the chart.

There are two problems, first is the limit never gets applied (not sure why and not the scope of the ticket, similar to #1058) and the second is the constant waiting for the RS to be done but a quick introspection tells you that can never happen.

Deployment:
```
Conditions:
  Type             Status  Reason
  ----             ------  ------
  Available        True    MinimumReplicasAvailable
  ReplicaFailure   True    FailedCreate
OldReplicaSets:    magic-service-2229389339 (3/3 replicas created)
NewReplicaSet:     magic-service-3728959033 (0/1 replicas created)
```

On the RS side:
```
Conditions:
  Type             Status  Reason
  ----             ------  ------
  ReplicaFailure   True    FailedCreate
Events:
  Type     Reason        Age                From                   Message
  ----     ------        ----               ----                   -------
  Warning  FailedCreate  10m (x21 over 1h)  replicaset-controller  Error creating: pods "magic-service-3728959033-" is forbidden: failed quota: compute-resources: must specify limits.cpu,limits.memory,requests.cpu,requests.memory
```

Question is if `--wait` should fail fast by introspecting on the failures or if it should just wait until `--timeout` happens due to the simplistic check it does?

We did that before in Deis, and it can be a bit version specific but given how stable the k8s APIs have been I think we can pull it off if there is interest in such a thing.

Happens on the following:
Helm 2.8.2
k8s 1.7.7

**Comment by bacongobbler** [comment]
cc @thomastaylor312. Any insight into why we didn't originally check for failing replicasets, or is that a nice feature we should consider implementing?

**Comment by thomastaylor312** [comment]
Honestly this was implemented before the behavior of all the different components of a `Deployment` were fully locked down and understood, so the implementation is naive. I think that we definitely should implement checking this. If someone would like to take a stab at cleaning up the wait code and checking for more of these types of situations, please feel free to help. I also think it should fail fast by default instead of waiting for timeout. 

@helgi If you do implement this (or anyone else), please ping me with any questions and when you open the PR

**Comment by bacongobbler** [comment]
closing as inactive.

**Comment by janario** [comment]
Just tried again and this still on version 3.3.1

```
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}
```

A simple chart with an invalid image

run helm install, it times out after 5min even when the deployment is already failed in 6s
```
helm install wait-fail --wait -n janario .
Error: timed out waiting for the condition


kubectl -n janario get pods
NAME                         READY   STATUS         RESTARTS   AGE
wait-fail-5fc55b9795-gt2hb   0/1     ErrImagePull   0          6s

```

It would be nice if it could detect the failure and didn't wait for the timeout, 

/reopen

**Comment by janario** [comment]
PR https://github.com/helm/helm/pull/8812
