### ISSUE TITLE
Parent chart should overwrite imported child values

### ISSUE THREAD

**Issue by Tapppi** [helm/helm#3883]
Currently, when using `import-values` in requirements, the child's imported values will overwrite any values in parents `values.yaml`. I cannot come up with a single real-world use case for this strange behaviour. [Even you guys seem to think the parent wins](https://github.com/kubernetes/helm/issues/3498#issuecomment-365701926).

There is no explicit mention of which values win in the docs, [but an example does show imported child values overwriting explicit parent values](https://github.com/kubernetes/helm/blob/master/docs/charts.md#using-the-child-parent-format).

This has been causing some nasty OOM crashes for us. We have a common base chart for microservices, and most of them set their own resource limits in their own `values.yaml`. Those settings haven't been doing anything, because the imported default overwrites them.

Workaround is to rename the defaults in the base chart and use `{{ default .Values.optionADefaults .Values.optionA }}` in the template. This only works for charts authored by us, not 3rd party charts.

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.4-gke.1", GitCommit:"10e47a740d0036a4964280bd663c8500da58e3aa", GitTreeState:"clean", BuildDate:"2018-03-13T18:00:36Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.):
GKE

**Comment by jascott1** [comment]
Hi @Tapppi 

"Currently, when using import-values in requirements, the child's imported values will overwrite any values in parents values.yaml."

Above comment is confusing since that is the point of import-values. Can you explain more of what you expect to see?

**Comment by Tapppi** [comment]
> Above comment is confusing since that is the point of import-values. Can you explain more of what you expect to see?

I expect to see `import-values` pull the values from the child chart but not overwrite explicit configuration in parent's values, i.e. I expect the parent's values to win conflicts during the merge. 

Yes, the point of `import-values` is to pull values from the child, but it makes no sense to me that you can't overwrite them in any way. The parent chart knows what it is going to import (and possibly overwrite) so there should be no confusion about overwriting values accidentally. Is there some reason for *not* allowing overwrites? To me this seems like a missed opportunity for more flexibility.

For a use case, see my original post:

> We have a common base chart for microservices, and most of them set their own resource limits in their own values.yaml

I.E. we have a `base-chart` and other charts import a common set of defaults from the base chart. Currently, these can be overwritten by wrapping the parent in another chart, but not the parent itself which means it cannot provide defaults differing from the common base chart.

**Comment by bacongobbler** [comment]
closing as inactive.

**Comment by guoyiang** [comment]
This issue seems still persist on latest helm 2.16, while not observed on helm 3. Is there any plan to fix it in helm 2?
Thanks!

**Comment by messiahUA** [comment]
I'm also confused by this behavior. This is a case in v3 as well since v2.16.4 (https://github.com/helm/helm/commit/42941797f394d94800f17ea84566f0a838ec55dc). Currently imported values overwrite parent values and I have the same story as @Tapppi 

Mentioned in https://github.com/helm/helm/issues/7045
