### ISSUE TITLE
Possible duplication in tests of tiller release update

### ISSUE THREAD

**Issue by adshmh** [helm/helm#3887]
There seems to be some duplication in tests of tiller release update, e.g.:

https://github.com/kubernetes/helm/blob/ad714fe704724195e6a8566ad44ead1e4c9ac36b/pkg/tiller/release_update_test.go#L38-L47

and 

https://github.com/kubernetes/helm/blob/ad714fe704724195e6a8566ad44ead1e4c9ac36b/pkg/tiller/release_update_test.go#L111-L121

**Comment by bacongobbler** [comment]
closing for the same reasons stated in #3888: the code refactor introduces the same amount of code in return, so it's no cleaner than the original. Additionally, this part of the codebase was removed in Helm 3 so this can be closed.
