### ISSUE TITLE
post-upgrade hook pod terminates prematurely

### ISSUE THREAD

**Issue by eranreshef** [helm/helm#3910]
I have a pod that I annotated as a post-install, post-upgrade and post-rollback hook.
I want this pod to be deleted once it completes successfully so I added 
`"helm.sh/hook-delete-policy": hook-succeeded` .
The problem is that the pod is being terminated before its even starting:
```
default   api-gw-apireg-vvpnd   0/1       Pending   0         <invalid>
default   api-gw-apireg-vvpnd   0/1       Pending   0         <invalid>
default   api-gw-apireg-vvpnd   0/1       ContainerCreating   0         <invalid>
default   api-gw-apireg-vvpnd   0/1       Terminating   0         <invalid>
```
When I remove the delete policy annotation, pod is running successfully (but doesn't get deleted after finishing).

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.11", GitCommit:"1df6a8381669a6c753f79cb31ca2e3d57ee7c8a3", GitTreeState:"clean", BuildDate:"2018-04-05T17:24:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.10", GitCommit:"044cd262c40234014f01b40ed7b9d09adbafe9b1", GitTreeState:"clean", BuildDate:"2018-03-19T17:44:09Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS

**Comment by eranreshef** [comment]
Any news on this issue?

**Comment by enver** [comment]
Still issue with v2.14.1.
I'm running pre-install hook and when I specify `"helm.sh/hook-delete-policy": "hook-succeeded"` pod is created and immediately terminated (without running hook task)

**Comment by bacongobbler** [comment]
closing as inactive.

**Comment by 3rmack** [comment]
Same issue with v2.15.2
