### ISSUE TITLE
Default tiller namespace for a kube context?

### ISSUE THREAD

**Issue by clux** [helm/helm#3911]
Is it possible to define a default tiller namespace for a kube context somewhere? If we are following a standard RBAC setup of having a tiller per namespace, then the tiller namespace likely matches the namespaces in the `kube config get-contexts`, or has a 1-1 mapping to it.

It's not a huge problem, it just means that everyone has to also set the `TILLER_NAMESPACE` evar as part of swapping contexts before using helm (without it being annoying).

**Comment by Damien-DeZurik** [comment]
I'm all for this but, from what I understand tiller is going away so I guess this feature would be of no use.

**Comment by bacongobbler** [comment]
Yes, but we'll still need to connect to a kube cluster so the context is still necessary. ;)

This sounds like a good feature if someone wants to tackle this. We have previous work that ties into the kube context's configured namespace via #2808 and #1400 so there's some historical context (ha) here.

**Comment by TBBle** [comment]
This feature request only applies to Helm v2, and that's closed for new features.
