### ISSUE TITLE
Improve `with` doc: it does `if` + change context

### ISSUE THREAD

**Issue by thomas-riccardi** [helm/helm#3919]
Current `with` documentation at https://docs.helm.sh/chart_template_guide/#modifying-scope-using-with says:
> (Note that we removed the `if` conditional from the previous exercise)

It only implicitly says that the `if` conditional is not needed anymore because `with` does `if` + context change.

I had to experiment to be sure it did that. It would be better to have an explicit documentation.

**Comment by bacongobbler** [comment]
closing as inactive.
