### ISSUE TITLE
docs clarifying how helm search --regexp

### ISSUE THREAD

**Issue by michelleN** [helm/helm#3927]
see #3890 for more context
This may come in the form of docs and/or further clarification in help/flag description

**Comment by ian-howell** [comment]
Suggestion: why not add a new flag `--regexp-whole-word` which simply adds the vertical tabs in the search? This would blackbox the implementation. Maybe an idea for Helm 3?

**Comment by ian-howell** [comment]
It would also fall immediately after the current `--regexp` flag, giving it high visability

**Comment by hphde** [comment]
Super helpful to know about `\v` - made my day
