### ISSUE TITLE
Return structured resources status from gRPC

### ISSUE THREAD

**Issue by seaneagan** [helm/helm#3943]
Currently the `resources` section of the status returned from gRPC is unstructured text:

```
==> v1/Job
NAME                 DESIRED  SUCCESSFUL  AGE
...

==> v1/Pod(related)
NAME                            READY  STATUS     RESTARTS  AGE
...

==> v1/Secret
NAME                   TYPE    DATA  AGE
...

==> ...
...

```  

This is useful information for a more nuanced understanding of the health of the release, but it is not currently machine readable.

From #3190:

> Note, the status text is generated within tiller so it it not nicely formatted JSON to be sent around.
> This would need to be Helm 3 work as it would be API breaking.

But would it need to be breaking?  What about adding a new field, maybe `resourcesStatus`, and just deprecate the old one (`resources`) until helm 3?  I may be interested in making a PR for this if it is a viable option.

**Comment by technosophos** [comment]
It is considered a compatibility breaker. Though someone could add a separate gRPC call to get a status object instead of the text, and even rewire the client to use that new endpoint.

**Comment by seaneagan** [comment]
It looks like in helm 3 the plan is to link resources to their Release CRD via kubernetes ownerReferences:

https://github.com/kubernetes-helm/community/blob/master/helm-v3/003-state.md

In helm 2 it seems the only way to approximate this is via parsing the release manifest yaml blob and extracting resource identifiers.

What about a new gRPC endpoint which just returns the list of resources associated with a release?  Then this list (or a filtered subset) can be passed to kubernetes for any further processing, such as getting the status of the resources.  Could be exposed in the CLI via `helm get resources <release>`?

**Comment by alok87** [comment]
✋ Can i pick this?

**Comment by bacongobbler** [comment]
closing as inactive.
