### ISSUE TITLE
Incorrect import-values override when using external values.yaml with --values

### ISSUE THREAD

**Issue by nicolasgnr** [helm/helm#3964]
I have a chart A with a dependency B

```
dependencies:
  - name: B
    version: 1.0.0
    repository: https://chart-repository/...
    import-values:
      - child: someBasePropInB
        parent: propsOfB
```

A requires B properties. For example, B shares the target port of one service with A, so a single is needed instead of duplicating it.

Chart A default values are the following by default:

```
B:
   someSubPropOfB: someSubValueOfB
```

Chart B default values are the following by default:

```
someBasePropInB:
   someSubPropOfB: someDefaultSubValueOfB
```

When using `helm template` I can see that Chart A ends up having the correct override values as well as Chart B. That means:

Effective values of A:

```
propsOfB:
   someSubPropOfB: someSubValueOfB
```

Effective values of B:

```
someBasePropInB:
   someSubPropOfB: someSubValueOfB
```

That problem is when I used `--values` prop in `helm template` overriding some of the values. Let’s use the following external values file:

```
B:
   someSubPropOfB: someNewSubValueOfB
```

The effective value of B is OK. The problem is with A. It seems that the `import-values` from `dependencies.yaml` is resolved before the external values are applied because:

```
propsOfB:
   someSubPropOfB: someSubValueOfB
```

```
$ helm version
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
```

Also tested with `v2.9.0-rc4`

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): `Minikube`

**Comment by jascott1** [comment]
Hi @nicolasgnr 

Would you know if this behavior matches that of `helm install`?

**Comment by nicolasgnr** [comment]
@jascott1 yes, it does 😞

**Comment by jascott1** [comment]
@nicolasgnr thanks for reporting this. I will look into it.

**Comment by nicolasgnr** [comment]
@jascott1 Shouldn't it be labeled as `bug`?

**Comment by nicolasgnr** [comment]
@jascott1 Any update about this issue? It should be labeled as bug

**Comment by frittentheke** [comment]
I just ran into this issue using Helm 3 rc.2 as well. There the imported values are "just" those of the subchart / child, and not those of the additonally provided override-values.yaml

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
