### ISSUE TITLE
Containerize the build

### ISSUE THREAD

**Issue by krancour** [helm/helm#397]
I notice the builds aren't currently using a containerized dev environment pre-loaded with the necessary dev tools.  I think the latest deis/go-dev image would fit the bill as it includes go 1.6 and the most recent versions of gox and glide.

**Comment by arschles** [comment]
+1 - the most recent version as of this writing is `0.9.0`

**Comment by technosophos** [comment]
Do we think it is a reasonable assumption that users of `helm` will have Docker running locally? Installing Docker is non-trivial on OSX and Windows. So I'd not want to make this a hard requirement if we feel it puts undue burden on the potential contributor.

**Comment by arschles** [comment]
It's probably not _unreasonable_ to say they have docker running locally, but that's pure speculation. Regarding the Docker install experience, I don't know how to define trivial, but I bet it's easier to install glide and the go build tools than docker on those systems rather than Docker.

**Comment by krancour** [comment]
I think I see the combination of Docker + Make becoming the de facto low bar / ubiquitous tool set for most anyone who writes code.  The advantages it offers are numerous, most notably in ensuring a consistent development environment for all contributors and for absolving all contributors from having to install and manage a potentially large set of other languages and tools, many of which may need to be at specific versions (while other things they work on require _different_ specific versions).

We might be ahead of the curve / early adopters in this regard, but we can be trend-setters.

**Comment by technosophos** [comment]
Okay. If someone PRs it, I'll review. I think you guys are right.
