### ISSUE TITLE
Tiller installation fails when restrictive PodSecurityPolicy is configured

### ISSUE THREAD

**Issue by praseodym** [helm/helm#3992]
When running `helm init` targeting a Kubernetes cluster which has a restrictive PodSecurityPolicy configured (i.e. one with `runAsUser: rule: MustRunAsNonRoot`), the Tiller container will fail to start with an error (`Error: container has runAsNonRoot and image will run as root`). This is because Kubernetes has no indication that the pod wants to run as root, and will apply the restrictive pod security policy.

To work around this, the Tiller pod needs to indicate its intention to run as root through its security context:
```yaml
securityContext:
  runAsNonRoot: false
```
This indicates the pod's intention to run as root, and will let Kubernetes decide upon a less restrictive pod security policy if one is available. It thereby avoids the runtime error caused by eagerly applying a too restrictive policy.

**Comment by jheiss** [comment]
Is there any reason that tiller needs to run as root? Could helm init take an option for the user to run tiller?

**Comment by bacongobbler** [comment]
IIRC service account secrets are mounted in with root permissions so we need elevated permissions to read those in the container. I could be wrong

**Comment by praseodym** [comment]
If the container can run as a non-root user that should be the default (not an option). It's as simple as adding a `USER` command with a non-root uid to the Tiller Dockerfile.

**Comment by jheiss** [comment]
Setting USER in the Dockerfile doesn’t fix this for PodSecurityPolicy users. Kubernetes doesn’t know what is set in the container image and requires that you specify runAsUser in the securityContext.

**Comment by jheiss** [comment]
Oh, right, I forgot about that. We have an admission controller that requires runAsUser for other security checks.

**Comment by bacongobbler** [comment]
closing as inactive.
