### ISSUE TITLE
Helm reports that tiller is already installed in the cluster, but it's not deployed

### ISSUE THREAD

**Issue by dazdaz** [helm/helm#3996]
$ helm init
Creating /home/myuser/.helm
Creating /home/myuser/.helm/repository
Creating /home/myuser/.helm/repository/cache
Creating /home/myuser/.helm/repository/local
Creating /home/myuser/.helm/plugins
Creating /home/myuser/.helm/starters
Creating /home/myuser/.helm/cache/archive
Creating /home/myuser/.helm/repository/repositories.yaml
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com
Adding local repo with URL: http://127.0.0.1:8879/charts
$HELM_HOME has been configured at /home/myuser/.helm.
Warning: Tiller is already installed in the cluster.
(Use --client-only to suppress this message, or --upgrade to upgrade Tiller to the current version.)
Happy Helming!
$ kubectl get pods --namespace kube-system | grep tiller
$

Output of `helm version`:

$ helm version
Client: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
<hangs...>

Output of `kubectl version`:
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:26:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.11", GitCommit:"1df6a8381669a6c753f79cb31ca2e3d57ee7c8a3", GitTreeState:"clean", BuildDate:"2018-04-05T17:16:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS 1.8.11

**Comment by bacongobbler** [comment]
What's the status of the tiller pod? Can you check using kubectl?

**Comment by dazdaz** [comment]
The tiller pod is not running, as to why it's not running is not clear.

$ kubectl -n kube-system get po
NAME                                    READY     STATUS    RESTARTS   AGE
heapster-75f8df9884-k8d8w               2/2       Running   0          6d
kube-dns-v20-5bf84586f4-56nh2           3/3       Running   0          6d
kube-dns-v20-5bf84586f4-qm4m7           3/3       Running   0          6d
kube-proxy-b8wmb                        1/1       Running   0          6d
kube-proxy-l5pkd                        1/1       Running   0          6d
kube-svc-redirect-96pm7                 1/1       Running   0          6d
kube-svc-redirect-j9sg6                 1/1       Running   0          6d
kubernetes-dashboard-5977dcf768-lkcst   1/1       Running   0          1d
tunnelfront-584dfdc655-k69ct            1/1       Running   0          6d

**Comment by hh** [comment]
I'm getting the same thing on gce and k8s 1.10.1

```
$ helm version
Client: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
Error: cannot connect to Tiller
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:26:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by hh** [comment]
```

**Comment by hh** [comment]
```
$ helm reset --remove-helm-home --force --debug
Deleting /zfs/home/chris/src/apisnoop/dev/gce/.helm 
Tiller (the Helm server-side component) has been uninstalled from your Kubernetes Cluster.
$ helm init --service-account=tiller --wait --debug  
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: helm
    name: tiller
  name: tiller-deploy
  namespace: kube-system
spec:
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: helm
        name: tiller
    spec:
      containers:
      - env:
        - name: TILLER_NAMESPACE
          value: kube-system
        - name: TILLER_HISTORY_MAX
          value: "0"
        image: gcr.io/kubernetes-helm/tiller:v2.8.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /liveness
            port: 44135
          initialDelaySeconds: 1
          timeoutSeconds: 1
        name: tiller
        ports:
        - containerPort: 44134
          name: tiller
        - containerPort: 44135
          name: http
        readinessProbe:
          httpGet:
            path: /readiness
            port: 44135
          initialDelaySeconds: 1
          timeoutSeconds: 1
        resources: {}
      serviceAccountName: tiller
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: helm
    name: tiller
  name: tiller-deploy
  namespace: kube-system
spec:
  ports:
  - name: tiller
    port: 44134
    targetPort: tiller
  selector:
    app: helm
    name: tiller
  type: ClusterIP
status:
  loadBalancer: {}
...
Creating /zfs/home/chris/src/apisnoop/dev/gce/.helm 
Creating /zfs/home/chris/src/apisnoop/dev/gce/.helm/repository 
Creating /zfs/home/chris/src/apisnoop/dev/gce/.helm/repository/cache 
Creating /zfs/home/chris/src/apisnoop/dev/gce/.helm/repository/local 
Creating /zfs/home/chris/src/apisnoop/dev/gce/.helm/plugins 
Creating /zfs/home/chris/src/apisnoop/dev/gce/.helm/starters 
Creating /zfs/home/chris/src/apisnoop/dev/gce/.helm/cache/archive 
Creating /zfs/home/chris/src/apisnoop/dev/gce/.helm/repository/repositories.yaml 
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com 
Adding local repo with URL: http://127.0.0.1:8879/charts 
$HELM_HOME has been configured at /zfs/home/chris/src/apisnoop/dev/gce/.helm.
Error: could not ping Tiller: context deadline exceeded
````

**Comment by dazdaz** [comment]
I got it fixed, here are the steps which I took.  The tiller container appeared to be stuck in an unknown state.  Let me know if this works for you.

1.
$ kubectl delete service tiller-deploy -n kube-system
service "tiller-deploy" deleted
$ kubectl delete pods tiller-deploy-b6fbf658-57t6t -n kube-system --force=true --timeout=0s
pod "tiller-deploy-b6fbf658-57t6t" deleted
$ kubectl -n kube-system delete deploy tiller-deploy

2
# Deploy Helm 2.6.2 with Kubernetes 1.8.11

3.
$ helm init --service-account default

**Comment by cristian04** [comment]
It's also useful to take a look on the ns events.
```
$ kubectl get events -n kube-system

LAST SEEN   TYPE      REASON              KIND         MESSAGE
3m15s       Warning   FailedCreate        ReplicaSet   Error creating: pods "tiller-deploy-7b45545f56-" is forbidden: error looking up service account kube-system/tiller: serviceaccount "tiller" not found
8s          Warning   FailedCreate        ReplicaSet   Error creating: pods "tiller-deploy-7b45545f56-" is forbidden: error looking up service account kube-system/tiller: serviceaccount "tiller" not found
8m43s       Normal    ScalingReplicaSet   Deployment   Scaled up replica set tiller-deploy-7b45545f56 to 1
49s         Normal    ScalingReplicaSet   Deployment   Scaled up replica set tiller-deploy-7b45545f56 to 1
```
