### ISSUE TITLE
How to add an alias to a Helm plugin?

### ISSUE THREAD

**Issue by tedmiston** [helm/helm#3998]
Hello -

I've created a Helm plugin `delete-all` (source: https://github.com/astronomerio/helm-delete-all-plugin) that is syntactic sugar for `helm list --all --short | xargs -L1 helm delete --purge`.

I'd like to be able to wire it up to support aliases consistent with `$ helm delete`, for example, to be callable with `$ helm del-all` and `$ helm dela`.

I searched the docs for this feature but didn't find anything.  I also tried adding `alias: dela` to my plugin.yaml file.

Is an alias feature available to plugins?

If not, short of installing the plugin 3 times with different names, is there a better workaround today?

Output of `helm version`:

> Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
> Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}

Output of `kubectl version`:

> Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
> Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

> Docker for Mac edge Version 18.03.0-ce-mac58 (23607)

**Comment by bacongobbler** [comment]
Just an FYI there is already a plugin that performs this task called `[helm nuke](https://github.com/adamreese/helm-nuke)`. :)

To answer your question though, there is no aliasing support available for plugins. However, this would definitely be a nice enhancement if someone wanted to contribute!

**Comment by bacongobbler** [comment]
closing as inactive.
