### ISSUE TITLE
Testing Charts on commit

### ISSUE THREAD

**Issue by technosophos** [helm/helm#4]
Stories:

As a contributor, I'd like to have my chart automatically tested when I issue a pull request.

As a Helm Steering Committee member, I'd like to know that any charts I am reviewing have passed CI

**Comment by sgoings** [comment]
Currently have https://travis-ci.org/deis/helm set up to build PRs with smarts (only test charts that have been modified in the PR).

I'll wait to close this issue until we actually are doing the `helm install && helm uninstall` actions

**Comment by technosophos** [comment]
Status?

**Comment by sgoings** [comment]
Closing in preference of helm/charts#43
