### ISSUE TITLE
Docs: The Helm read the docs site doesn't have the template documentation

### ISSUE THREAD

**Issue by mattreyuk** [helm/helm#400]
I noticed the generated "read the docs" site doesn't have the documentation on templates. I think this is just because it's missing in mkdocs.yml. I plan to try and fix this myself and provide a pull request.

**Comment by bacongobbler** [comment]
Good catch. There seems to be a few others missing too, specifically [The Helm Guide to Writing Awesome Charts](https://github.com/helm/helm/blob/master/docs/awesome.md), [Helm Generate and Template](https://github.com/helm/helm/blob/master/docs/generate-and-template.md), and [Helm Plugins](https://github.com/helm/helm/blob/master/docs/plugins.md).

**Comment by mattreyuk** [comment]
I'll make sure to add them in as well.
