### ISSUE TITLE
Helm hook does not return proper failure to standard output.

### ISSUE THREAD

**Issue by dpepper** [helm/helm#4010]
When using a helm hook for a pre-install step I would expect that if the hook fails the user gets an error message from the job indicating what failed. That is not the case, if a pre-install hook fails the only error that is returned is a generic job failure message that the job never completed (Either a backoffLimit or timeout) For example:
helm install <helm-chart>
Error: Job failed: BackoffLimitExceeded

This is not useful since the real reason the helm release failed is because whatever task the pre-install hook tried to complete was unsuccessful. The return message from the helm install command should either be the output of the logs command of that pod or a mechanism is needed in order to return an error from that pod indicating why the pod failed.

**Comment by technosophos** [comment]
Since hooks are completely kind agnostic, there is no inspection of the failure other than what the Kubernetes API offers up as a failure reason. Since a hook can be applied to anything from configmaps to stateful sets, there's no uniform way to inspect a failure beyond what the API tells us. (And keep in mind that many kinds do not have logs attached)

As a feature, this would likely require quite a bit of work. But if someone provides a fix that is maintainable, we'd probably accept it.

**Comment by mdeknowis** [comment]
Is this similar to #3370 ?

**Comment by mdeknowis** [comment]
It would be very helpful to see, which job is failing, currently it's really hard:

```
helm upgrade --install ... mychart
Release "myrelease" does not exist. Installing it now.
Error: Job failed: BackoffLimitExceeded
```

We have a huge helm chart, with many jobs and other k8s resources, so it's not obvious, which job is failing.

**Comment by vdboor** [comment]
Second this. I just spend 30 mins debugging this error:

```
$ helm upgrade --install --tiller-namespace MYSITE --namespace MYSITE ...
Error: UPGRADE FAILED: timed out waiting for the condition
```

journalctl showed the actual issue:

```
Apr 11 13:31:15 ... kubelet[430]: E0411 13:31:15.847166     430 pod_workers.go:190] Error syncing pod 14642dea-5c4d-11e9-a665-5254000919ee ("MYSITE-test-migrate-z62c8_MYSITE(14642dea-5c4d-11e9-a665-5254000919ee)"), skipping: failed to "StartContainer" for "django-migrate" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=django-migrate pod=MYSITE-test-migrate-z62c8_MYSITE(14642dea-5c4d-11e9-a665-5254000919ee)"
```

The kube object is:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}-migrate
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
...
```

**Comment by bacongobbler** [comment]
closing as inactive.
