### ISSUE TITLE
Pods stuck on terminating (Terminated: ExitCode)

### ISSUE THREAD

**Issue by mouradmourafiq** [helm/helm#4019]
**What happened:**

Running the helm command helm del --purge releaseName sometimes deletes volumes before pods, which results in pods stuck in Terminated: ExitCode.

**What you expected to happen:**

I expect the pods to be delete as well without having to manually delete them with --grace-period=0 --force options.

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
`Digital Ocean`

**Comment by technosophos** [comment]
Can you reproduce on a newer version of Helm? 2.7.0 had a few known issues that were resolved in subsequent releases

**Comment by mouradmourafiq** [comment]
@technosophos I upgraded to helm to "v2.9.0"
```
Client: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
```
And now I have 2 problems after the `helm del --purge`  command is finished:

  * Pods with status `Running` 
  * Pods `Terminated: ExitCode:${state.terminated.exitCode}` even without volumes.

Sometimes this could take up to 50 min to have everything related to the release cleaned up.

**Comment by ElijahGlover** [comment]
Also seeing the same problem

`Client: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}`

**Comment by sneko** [comment]
Same as @ElijahGlover

**Comment by Sprinkle** [comment]
Same problem on 2.9.1

**Comment by sebglon** [comment]
We have the same:
```
helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-28T20:16:17Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.3", GitCommit:"9b5b719c5f295c99de68ffb5b63101b0e0175376", GitTreeState:"clean", BuildDate:"2018-05-31T18:32:23Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by alessiopiazza** [comment]
Same on 2.10.0

```
Helm version
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
```

**Comment by ELD** [comment]
The same is happening for us on 2.11.0 with workloads using persistent volume claims, ephemeral volumes, and NFS provisioned storage class and volumes.

```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

Would be great to find the underlying cause of this issue so that purging a Helm chart happens cleanly.

**Comment by walkafwalka** [comment]
Same situation as @ELD. Helm 2.12.1. Kube 1.11.6.

**Comment by ELD** [comment]
In our particular case running into this issue, it seems tied directly to Helm attempting to terminate a PVC that is attached to our pods. If the pods were terminated first and then the PVC was terminated, we probably wouldn't run into this issue as deleting pods at run time and letting the StatefulSet recreate them seems to work without issue.

**Comment by walkafwalka** [comment]
Same for me. @technosophos Any insight on deleting pods before deleting their volume claims?

**Comment by bacongobbler** [comment]
closing as inactive.
