### ISSUE TITLE
Tiller upgrade results in Error: forwarding ports: error upgrading connection: unable to upgrade connection: pod not found ("name-of-pod")

### ISSUE THREAD

**Issue by semiria** [helm/helm#4031]
When trying to upgrade tiller, the upgrade fails with the following message:
`Error: forwarding ports: error upgrading connection: unable to upgrade connection: pod not found ("name-of-pod")`

What we notice is that the pod referred in the error message correspond to the pod of the previous version, not of the version we are trying to upgrade to.

Upon inspection after the error message, we see that `tiller` is up and running to the new expected version.

This upgrade is done from within a Jenkins pipeline, and our current work around is to retry the `init --upgrade` operation until we succeed.

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T23:15:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:27:48Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS

**Comment by louismunro** [comment]
It looks to me like a possible race condition between installer.Upgrade() and ping().

I.e. installer.Upgrade() is called at line 303 in cmd/helm/init.go, which results in a Put to the API for the new deployment. But since that call is not synchronous (i.e. the call does not block while the deployment is replacing the old one) we call watchTillerUntilReady() before setting up a new tunnel to tiller.

Except that we don't make sure the the call to getFirstRunningPod() in portforwarder.go looks for a pod of the new deployment.
There is no guarantee  that the first running pod we will find will be one for the new deployment.
Shutting down the pods for the old deploy is not instantaneous. The old pods have to be de-scheduled, the kubelet must notice it has to kill them etc. 
So it's definitely possible that the first running pod will still be one that is just about to be killed, or will no longer exist by the time setupConnection() is called.

That would explain the symptoms above.

**Comment by glBeatriz** [comment]
Having the same issue right now

**Comment by glBeatriz** [comment]
Just an update. When we re-deployed the same CI pipeline the issue did not repeat.

**Comment by retr0h** [comment]
Our error was slightly different.

```
Error: forwarding ports: error upgrading connection:
```

When inspecting the error object it was erroring with:

```
E0910 13:12:32.345648   10906 portforward.go:331] an error occurred forwarding 49556 -> 44134: error forwarding port 44134 to pod e18be8a93614c1061a41b
c0ab400296030ebc1d7d8a292e301e266091da97ff4, uid : exit status 1: nsenter: cannot open /proc/59258/ns/net: No such file or directory
```

> It looks to me like a possible race condition between installer.Upgrade() and ping().

I have verified this is the case.

When sleeping prior to executing the ping, the error does not occur.

```
[jodewey:~/go/src/k8s.io/helm] master(+10/-0)* ± helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
[jodewey:~/go/src/k8s.io/helm] master(+10/-0)* ± bin/helm init --upgrade --wait --skip-refresh --tiller-image registry.xxx.com/xxx-images/gcr.io/kubernetes-helm/tiller:v2.10.0 --tiller-connection-timeout 900
$HELM_HOME has been configured at /Users/jodewey/.helm.

[patched code]: sleeping

Tiller (the Helm server-side component) has been upgraded to the current version.
Happy Helming!
[jodewey:~/go/src/k8s.io/helm] master(+10/-0)* ± helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
```

**Comment by louismunro** [comment]
I have a PR in the works for this. 
It should be ready in a day or two. I just need to make it "presentable" before unleashing it on the maintainers.

**Comment by retr0h** [comment]
> I have a PR in the works for this.
> It should be ready in a day or two. I just need to make it "presentable" before unleashing it on the maintainers.

Awesome, I was about to tackle this today.  Thanks for doing this.
