### ISSUE TITLE
`helm init` doesn't support `--tls-cert` and related flags

### ISSUE THREAD

**Issue by flimzy** [helm/helm#4050]
When issuing `helm init --wait --tiller-tls`, it may be desirable to use the `--tls-ca-cert`, `--tls-cert` and `--tls-key` flags. At present, this is not supported, requiring that the proper TLS PEM files exist in `~/.helm`.

    $ helm init \
    >     --wait \
    >     --tiller-tls \
    >     --tiller-tls-cert ${tmp}/tiller.cert.pem \
    >     --tiller-tls-key ${tmp}/tiller.key.pem \
    >     --tls-ca-cert ${HELMHOME}/ca.pem \
    >     --tiller-tls-verify \
    >     --tls-ca-cert ${HELMHOME}/ca.cert.pem \
    >     --tls-cert ${HELMHOME}/helm.cert.pem \
    >     --tls-key ${HELMHOME}/helm.key.pem \
    >     --service-account=tiller
    Error: unknown flag: --tls-cert

Output of `helm version`:

    Client: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}

**Comment by andresmgot** [comment]
+1 I am trying to install helm in a CI with TLS so I need the `--wait` to continue the execution

**Comment by bacongobbler** [comment]
Marking this as a good first issue for someone to pick up.

**Comment by cpanato** [comment]
Replied in the chat to @bacongobbler. I will try this one

**Comment by evalsocket** [comment]
@bacongobbler @cpanato i want to work on that issue. Can you explain me what has to be done ?

**Comment by jeff-knurek** [comment]
I think this bug needs the `v2.x` label

@evalsocket the process would be adding a new flag to the init cmd _(and not forgetting to update/add tests like `TestTLSFlags` ;) )_

**Comment by bacongobbler** [comment]
We are no longer accepting new features for Helm 2.
