### ISSUE TITLE
`helm init --wait` doesn't appear to work with TLS

### ISSUE THREAD

**Issue by flimzy** [helm/helm#4051]
When I run:

    helm init \
        --wait \
        --tiller-tls \
        --tiller-tls-cert ${tmp}/tiller.cert.pem \
        --tiller-tls-key ${tmp}/tiller.key.pem \
        --tls-ca-cert ${HELMHOME}/ca.pem \
        --tiller-tls-verify \
        --service-account=tiller

I get the following error:

> Error: could not ping Tiller: x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs

Output of `helm version`:

    Client: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}

Output of `kubectl version`:

    Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.8-gke.0", GitCommit:"6e5b33a290a99c067003632e0fd6be0ead48b233", GitTreeState:"clean", BuildDate:"2018-02-16T18:26:58Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

**Comment by domderen** [comment]
I'm getting the same error with helm `v2.9.1`. I followed the steps described here: https://docs.helm.sh/using_helm/#using-ssl-between-helm-and-tiller to setup TLS cert verification.

**Comment by stevvooe** [comment]
We ran into this issue, as well. It seems to be a problem with the section of code that gets executed when `--wait` is used: https://github.com/kubernetes/helm/blob/aa98e7e3dd2356bce72e8e367e8c87e8085c692b/cmd/helm/init.go#L343.

As a workaround, you can run `kubectl rollout status -n kube-system deploy tiller-deploy -w` to wait on the deployment of tiller before proceeding.

**Comment by bacongobbler** [comment]
good catch @stevvooe. We probably just need to propagate those flags to the helm client when we initiate the connection.
