### ISSUE TITLE
Allow custom Chart.yaml in starters

### ISSUE THREAD

**Issue by s-spindler** [helm/helm#4060]
As per the [docs](https://github.com/kubernetes/helm/blob/master/docs/charts.md#chart-starter-packs) the Chart.yaml in a starter is overwritten:

> The Chart.yaml will be overwritten by the generator.

Is there any reason for this limitation?

The current behaviour is especially confusing as helm _does_ require a Chart.yaml to be present:
```
➜ helm create dinglebop --starter grumbo
Creating dinglebop
Error: could not load /home/glibglob/.helm/starters/grumbo: no Chart.yaml exists in directory "/home/glibglob/.helm/starters/grumbo"
```

Helm version: 2.9.0

**Comment by bacongobbler** [comment]
Yes. Chart.yaml is overwritten through CLI arguments provided via `helm create`. For example, if a user invokes `helm create --starter mystarter foo`, they expect the chart to be named `foo`.

Hope this helps.
