### ISSUE TITLE
helm init --upgrade does not apply entire manifest

### ISSUE THREAD

**Issue by sudermanjr** [helm/helm#4063]
When performing an update of the tiller, only certain fields are updated.  This causes an issue when you want to change some settings in the tiller that were set using the --override or other flags.

Looking here: https://github.com/kubernetes/helm/blob/master/cmd/helm/installer/install.go#L61 it would appear that only the image, pull policy, and service account are checked when doing this operation.  I believe it would be preferable to apply the entire manifest (which I believe is available at this point).  When running helm init --upgrade --debug I do see the changes that I have made in the manifest that is displayed, but it never gets applied.

Output of `helm version`:
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-05-12T04:12:12Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.10", GitCommit:"044cd262c40234014f01b40ed7b9d09adbafe9b1", GitTreeState:"clean", BuildDate:"2018-03-19T17:44:09Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS Kops Cluster

**Comment by Dean-Coakley** [comment]
I'm going to take a look into this. First Time Contributor, so if anyone wants to state the obvious: what explicitly should/shouldn't be updated, etc. That would be appreciated.

**Comment by sudermanjr** [comment]
@Dean-Coakley That's awesome.  I can't think of a reason why we wouldn't just want the entire manifest applied, but perhaps someone else here can think of something else.

**Comment by rchakra3** [comment]
Can I pick this up? Doesn't look like anyone is working on this currently

**Comment by Dean-Coakley** [comment]
@rchakra3 yeah...I'm lacking the confidence to get to PR stage. Feel free to take this one. 

Let me know if you do.

**Comment by rchakra3** [comment]
@Dean-Coakley thanks for the update! 
I'll take a stab at this over the next few days

**Comment by bacongobbler** [comment]
closing as inactive.
