### ISSUE TITLE
Ability to cross reference subcharts

### ISSUE THREAD

**Issue by abhishenator** [helm/helm#4073]
Here are my requirements:
-- I m creating an umbrella chart where subcharts services need to refer each other(eg: Kafka depends on zookeeper). The subcharts are independently developed.
-- I want to refer to the service name created in one subchart in another subchart's "values". (I dont think this is possible as values.yaml cannot be templatized. This enforces us to modify subcharts templates.)
-- I do not want to change subcharts much. If possible, I just want to treat 'values' of a subchart as the "interface" it exposes to parent chart/other subcharts. I think what is really missing in Helm's design is the philosophy of some sort of interface that charts can expose so that we don't have to change subcharts templates to absorb the subcharts cross reference requirement.

One solution I can think of is to use parent's global variables to define service names and ports. This part of global acts like service discovery db. And each subchart uses same service name generation template so that the service names can be easily referenced across subcharts using this standard template. The key part here is some sort of interface is enforced by using this standard template across all subcharts. Unfortunately, this solution breaks the modular way of thinking in software engineering as now the subcharts cannot be used in standalone mode as now they are tied to globals(variables and parent templates).

Is there any good solution to above problem? If there is, can we document it as a potentially common use case? 

Thanks

**Comment by bacongobbler** [comment]
closing as inactive.
