### ISSUE TITLE
Print --debug information before yaml validation

### ISSUE THREAD

**Issue by gintautassulskus** [helm/helm#4097]
When running 
```
helm upgrade chart-release --debug --dry-run chart
```

I receive the following error:

```
Error: UPGRADE FAILED: YAML parse error on deployment.yaml: error converting YAML to JSON: yaml: line 84: mapping values are not allowed in this context
```

The `line 84` provided in the error message most probably points to a line in the final yaml file.
The `deployment.yaml` template file is complex and full of Helm control structures. Therefore `line 84` does not necessarilly correspond to the same line in the template and the final yaml files.
I find it difficult to debug yaml validation errors in such a case.

Am I correct to assume that `--debug` output follows yaml validation? If yes, would it make sense to print the `--debug` output before yaml validation?

At the moment the workaround is to comment out the contents of `deployment.yaml`, re-run the command with --debug --dry-run, capture the output, remove `#`'s and then validate.

**Comment by bacongobbler** [comment]
Implemented in more recent versions of Helm 3. Closing.
