### ISSUE TITLE
Convert docs to gitbook

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#4100]
[gitbook](https://www.gitbook.com/), which we can host on our own, would be a good option to move our docs to for 3 reasons:

1. Search right in the docs
1. Can do multi-lingual (we should head there)
1. We could stop maintianing our custom business logic (like [this example](https://github.com/helm/helm-www/blob/00d09fbe6fcc73096bb6b025584a551a48577e7d/docs.helm.sh/gulpfile.js#L227))

A downside is links into the site might break (I've not tested this yet).

**Comment by unguiculus** [comment]
I'd suggest considering [Antora](https://antora.org/).

* Uses Asciidoc which is much better than Markdown
* Can aggregate documentation from multiple repositories
* Supports versioned documentation

We use it in my current project and aggregate docs across multiple repos. Works nicely.

Antora's own docs are created with Antora itself: https://docs.antora.org/

**Comment by mattfarina** [comment]
@unguiculus I would like to see us have multi-lingual docs. There's an issues for [Antora to support i18n](https://gitlab.com/antora/antora/issues/208) but nothing is implemented as of, yet. Gitbook as support (though weak) for it that we can build on (a slight addition to a custom theme).

I've added this topic to the helm developer call discussions. I'll come back to this after we chat there.

**Comment by bacongobbler** [comment]
moved to helm/helm-www, and it is built using hugo.
