### ISSUE TITLE
Docs: Chart Tables (adding other repos) not covered in docs folder

### ISSUE THREAD

**Issue by mattreyuk** [helm/helm#411]
The docs don't cover chart tables. There's a great writeup of how everything works in #118 but you need to notice that on the Future Plans section of the project readme to be able to find it.
I plan to copy the relevant text from the issue log into a new chart Table markdown doc in the docs directory and add it to the readthedocs mkdocs.yml in a pull request.

**Comment by mboersma** [comment]
Closed by #414. Thanks again @mattreyuk!
