### ISSUE TITLE
Proposal: Add an option for helm test to run in parallel

### ISSUE THREAD

**Issue by frankh** [helm/helm#4118]
At the moment helm tests run in serial, however as each test is a separate pod there seems to be a clear use-case for running them in parallel

I suggest a flag, `--parallel` on `helm test` to run the tests in parallel

**Comment by frankh** [comment]
That's good to hear, I'm not super confident in my go so I thought maybe I'd made some obvious mistakes

**Comment by frankh** [comment]
@michelleN would you mind taking a look at the pr? https://github.com/kubernetes/helm/pull/4144

**Comment by bacongobbler** [comment]
closed via #4144
