### ISSUE TITLE
Proposal: removing "_helpers.tpl"

### ISSUE THREAD

**Issue by wemu** [helm/helm#4126]
Hello

we currently introduce helm to our development teams and constantly see people stumble over the "_helpers.tpl" file.

What we understood from the docs and some talks is that the "values.yaml" file is sort of the API for a chart and everything that needs to be configurable is put in there. Either due to multiple deployments of the chart in the same cluster (Chart release name in tiller) or mutliple deployments of the chart in the same namespace - so resources don't conflict and the right ones communicate with each other.

This has some complexity for charts that work standalone or as sub-chart (requirement).

Since the "values.yaml" is the API of the chart everything should be in there. I understand there is a nameOverride in the default chart - but it seems cumbersome to tweak the _helpers file and the values file to end up with the desired resource names in kubernetes.

Currently if using sub-charts and I want to change some names I copy-paste the template section of that sub-charts _heplers.yaml into my own _helpers.tpl and use the global scope of those defines to override them. And hoping the sub-chart does not change too much.

So my proposal would be to abolish "_helpers.tlp" from the default chart created by "helm create" - (maybe not entirely the whole mechansim with the .tpl files - if someone needs to put functions or utils somewhere). But trying to mostly or only rely on values.yaml.
I'm not complety sure this is possible or what the reason for introducing the _helpers.tpl file is and if the values.yaml behaves well enough in these cases when charts are used standalone or as sub-charts. But there is a global section in values.yaml as well. So it seems possible to achieve.

Let me know your thoughts :)

**Comment by bacongobbler** [comment]
We do not plan on removing _helpers.tpl from `helm create` as it's a convenient standard for chart authors as a placeholder for helper functions. If, however, you do not like the format that `helm create` provides, you can provide your own set of templates via the "starter chart" feature of `helm create`. See https://docs.helm.sh/developing_charts/#chart-starter-packs for more information on starter charts.

Thanks!
