### ISSUE TITLE
Search and Fetch return different versions of the same chart

### ISSUE THREAD

**Issue by maorfr** [helm/helm#4132]
Hello,

We have a chart museum where we store our charts (through gitlab ci pipelines).
When executing 'helm search' it seems the result is the latest chart version, while 'helm fetch' returns the latest stable version (x.x.x, not x.x.x-something).

Is this by design? I would expect search and fetch to return the same chart version.

Here is some example output:

maor@lappy:~/helm$ helm search museum/prometheus -l
NAME           	CHART VERSION	APP VERSION	DESCRIPTION                                       
museum/prometheus	5.0.3-3216   	2.1.0      	Prometheus is a monitoring system and time seri...
museum/prometheus	5.0.3-3212   	2.1.0      	Prometheus is a monitoring system and time seri...
museum/prometheus	5.0.3-3123   	2.1.0      	Prometheus is a monitoring system and time seri...
museum/prometheus	5.0.3-2686   	2.1.0      	Prometheus is a monitoring system and time seri...
museum/prometheus	5.0.2        	2.1.0      	Prometheus is a monitoring system and time seri...
museum/prometheus	5.0.2-2573   	2.1.0      	Prometheus is a monitoring system and time seri...

x-x-x-<gitlab ci pipeline id>
x-x-x - uploaded to museum manually

maor@lappy:~/helm$ helm search museum/prometheus
NAME           	CHART VERSION	APP VERSION	DESCRIPTION                                       
museum/prometheus	**5.0.3-3216**   	2.1.0      	Prometheus is a monitoring system and time seri...

maor@lappy:~/helm$ helm fetch museum/prometheus && ls
prometheus-**5.0.2**.tgz

Thank you all for the good work! :)

Output of `helm version`:
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:26:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS (using kops)

**Comment by bacongobbler** [comment]
closing as inactive.

**Comment by felipecrs** [comment]
I also have this issue:

![image](https://user-images.githubusercontent.com/29582865/95532997-6949aa80-09b8-11eb-8c3d-28c7f7d2f1fd.png)

(latest version of helm to-date)

Please note that I'm also affected by https://github.com/helm/helm/issues/8865
