### ISSUE TITLE
`helm upgrade --install` does not return error code when deployment fails

### ISSUE THREAD

**Issue by ssavrim** [helm/helm#4134]
**`helm version`:** v2.8.2+ga802316
**`kubectl version`:** v1.8.3
**Cloud Provider/Platform (AKS, GKE, Minikube etc.):**  Internal Kubernetes Cluster

`helm upgrade --install ...` returns systematically an exit code to 0 even if the status is FAILURE.
Is there an option to the command which allow returning an error code ? Or do we need to parse the output of the command ? We need this to detect failure on our deployments.

Thanks

**Comment by rmorrise** [comment]
Have you tried using the `--wait` option? Not sure whether this satisfies your need.

**Comment by monika3376** [comment]
--wait didn't work

**Comment by ssavrim** [comment]
I confirm '--wait' didn't work

**Comment by pkrishn6** [comment]
@ssavrim : passing --wait might not return a different return code but will cause a timeout error if you also pass --timeout which definitely returns an error code

I have been using it and seems to work ok.

**Comment by cpanato** [comment]
I can take this issue to try to make a fix and submit a PR

**Comment by cpanato** [comment]
how can I simulate an upgrade failed?

**Comment by cpanato** [comment]
I tested here and it exit 1

```
$ helm upgrade --install minio ../../github.com/kubernetes/charts/stable/minio --namespace test123
Error: UPGRADE FAILED: Deployment.apps "minio" is invalid: spec.template.spec.containers: Required value

$echo $?
1
```

helm version
```
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
```

**Comment by bacongobbler** [comment]
thanks @cpanato for reproducing and verifying this has been fixed in later releases! Closing for now.
