### ISSUE TITLE
Add "namespace" label to configmaps

### ISSUE THREAD

**Issue by rcorre** [helm/helm#4143]
I'm in a situation where I have to migrate tiller and some subset of its releases (specifically, releases within certain namespaces) into a new namespace. For times when you have to dig in to the underlying storage, I think a `namespace` label on configmaps (or secrets) could be an incredibly useful piece of metadata. Right now you have to decode the configmap data to determine the namespace.

In addition, I suspect a `namespace` label could speed up `helm ls --namespace $ns` significantly (just as the `RELEASE` label makes fetching configmaps for a particular release faster). 

Of course, you couldn't write code depending on this right away as you'd have 'legacy' releases without the label, but if it sounds useful, I think we should add the label ASAP.

**Comment by mattjmcnaughton** [comment]
Hi @rcorre ! Thanks for bringing this up.

Currently, `helm` doesn't include configmap/secrets in the template files it creates with `helm create`. So I'm not sure if there's a path (right now) for baking in the use of `namespace` via helm defaults.

However, I wonder if it would make sense to add comments to `helm/docs/chart_best_practices` suggesting the addition of namespaces?

**Comment by rcorre** [comment]
Hi @mattjmcnaughton, sorry for the confusion. I'm not talking about configmaps/secrets in a template, but rather the configmaps/secrets tiller uses as a storage backend.

**Comment by bacongobbler** [comment]
I'm confused. The namespace already part of the metadata of a configmap, and that's given to us through the kubernetes API.

```
><> kubectl --namespace kube-system get configmap example-python.v1 -o jsonpath='{.metadata.namespace}{"\n"}'
kube-system
```

Could you perhaps explain a little more concretely on what you are trying to do so I can better understand the issue at hand? Thanks!

**Comment by rcorre** [comment]
@bacongobbler in your example, what namespace was `example-python` released in to? To answer this question, you have to decode the release data. If instead there was a `NAMESPACE` label on `example-python.v1`, one could determine the release namespace without decoding the configmap data.

Tiller already adds the following labels:

- MODIFIED_AT
- NAME
- OWNER
- STATUS
- VERSION

I'm wondering if a `NAMESPACE` label would help speed up `helm ls --namespace`. Currently the `--namespace` filter is implemented by [fetching all releases](https://github.com/kubernetes/helm/blob/master/pkg/tiller/release_list.go#L35) then [filtering by namespace](https://github.com/kubernetes/helm/blob/master/pkg/tiller/release_list.go#L156). It seems like a `NAMESPACE` label would allow tiller to tell k8s to filter by namespace, rather than fetching a ton of configmaps and filtering them down to a subset within tiller.

I initially started thinking about this because I have to migrate a set of releases to a new tiller instance, but admittedly that's not a common use case. It does seem like useful metadata to expose at the label level, similar to `NAME` (I meant `NAME` when I said `RELEASE` above) and `STATUS`.

**Comment by bacongobbler** [comment]
closing as inactive.
