### ISSUE TITLE
rename DEBUG to HELM_DEBUG

### ISSUE THREAD

**Issue by bacongobbler** [helm/helm#4145]
See conversation in https://github.com/kubernetes/helm/issues/2401

**Comment by csaroff** [comment]
@bacongobbler Looks like maybe this was actually already implemented?
https://github.com/kubernetes/helm/search?q=helm_debug&unscoped_q=helm_debug

**Comment by bacongobbler** [comment]
It's a transitive dependency that's reading DEBUG. I can still reproduce this with v2.9.1.

```
><> DEBUG=foo helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
2018/05/31 08:47:44 (0xc4200f9290) (0xc420326320) Create stream
2018/05/31 08:47:44 (0xc4200f9290) (0xc420326320) Stream added, broadcasting: 1
2018/05/31 08:47:44 (0xc4200f9290) Reply frame received for 1
2018/05/31 08:47:44 (0xc420326320) (1) Writing data frame
2018/05/31 08:47:44 (0xc4200f9290) (0xc4203ac500) Create stream
2018/05/31 08:47:44 (0xc4200f9290) (0xc4203ac500) Stream added, broadcasting: 3
2018/05/31 08:47:44 (0xc4200f9290) Reply frame received for 3
2018/05/31 08:47:44 (0xc4203ac500) (3) Writing data frame
2018/05/31 08:47:44 (0xc4200f9290) Data frame received for 3
2018/05/31 08:47:44 (0xc4203ac500) (3) Data frame handling
2018/05/31 08:47:44 (0xc4203ac500) (3) Data frame sent
2018/05/31 08:47:44 (0xc4200f9290) Data frame received for 3
2018/05/31 08:47:44 (0xc4203ac500) (3) Data frame handling
2018/05/31 08:47:44 (0xc4203ac500) (3) Data frame sent
2018/05/31 08:47:44 (0xc4200f9290) Data frame received for 3
2018/05/31 08:47:44 (0xc4203ac500) (3) Data frame handling
2018/05/31 08:47:44 (0xc4203ac500) (3) Data frame sent
2018/05/31 08:47:44 (0xc4203ac500) (3) Writing data frame
2018/05/31 08:47:44 (0xc4203ac500) (3) Writing data frame
2018/05/31 08:47:44 (0xc4200f9290) Data frame received for 3
2018/05/31 08:47:44 (0xc4203ac500) (3) Data frame handling
2018/05/31 08:47:44 (0xc4203ac500) (3) Data frame sent
2018/05/31 08:47:44 (0xc4203ac500) (3) Writing data frame
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
2018/05/31 08:47:44 (0xc4203ac500) (3) Writing data frame
```

**Comment by jespino** [comment]
Looks like it comes from github.com/docker/spdystream, more concretely from here: https://github.com/docker/spdystream/blob/master/utils.go#L9

**Comment by henrynash** [comment]
I'll take a look at this, fix and submit a pull request

**Comment by henrynash** [comment]
@kidynamit Yes, apologies, was pulled off onto something else - back on it next week

**Comment by henrynash** [comment]
So I have explored this - and it does indeed seem to be the DEBUG in the spdystream code, which is part docker utilities used by the underlying code we pull in. All the debug env references within actual helm code itself seems to use the desired HELM_DEBUG. Therefore I'm not sure what to do here - since presumably many other packages end up using spdystream (e.g. httpstream) and potentially rely on its existing debug functionality.

**Comment by bacongobbler** [comment]
I'd still keep this open. It's a valid issue for helm regardless if it's a downstream issue or not. We can't just say "welp it's downstream's issue" if it affects the project in some way :)

We can probably work around this by PRing an enhancement to spdystream to disable the DEBUG flag on a function call much like how we can selectively change the log level for [logrus](https://github.com/Sirupsen/logrus).

**Comment by bacongobbler** [comment]
Fixed in Helm 3 since Tiller's been removed and spdystream was a dependency of that.

```
><> ./bin/helm version
version.BuildInfo{Version:"v3.0+unreleased", GitCommit:"5eb48f4471ac3aa9a3c87a07ee6f9e5bbc60a0e1", GitTreeState:"clean"}
><> DEBUG=foo ./bin/helm list
NAME	REVISION	UPDATED	STATUS	CHART	NAMESPACE
```
