### ISSUE TITLE
Rename templates directory or make configurable

### ISSUE THREAD

**Issue by christhomas** [helm/helm#4152]
Just looking at helm for some projects where I work and I'm having a hard time understanding why the directory "templates" was used and it's not configurable in any way.

The problem is that "templates" is a really generic name and used for way more things than helm, such as html templates, javascript templates, old websites use "templates" for their php scripts, etc, etc.

It seems like its a name which is asking for trouble. Also for a developer to open a project and see "templates". They don't immediately jump to the conclusion that this is for helm, but for the project. Perhaps its better to choose a more specific name for helm, or allow me to set the templates directory in the Chart.yml file and then I can put "project/helm-templates" or something like that instead.

**Comment by bacongobbler** [comment]
We are not going to do this as it'd break the chart format spec for Helm 2, however it could be a considered talking point for Helm 3. I'm of the opinion that the Chart.yaml is pretty well-known to identify the directory as a Helm chart, and I'd rather restrict the spec to a minimum

**Comment by christhomas** [comment]
So if you had a project. You'd put the charts in a subdir somewhere out of the way?

**Comment by bacongobbler** [comment]
Yes. You can take a look at the community charts as an example :)

**Comment by christhomas** [comment]
My first chart I put it in the root directory and then thought about what if I had templates already? That's where this comes from

**Comment by bacongobbler** [comment]
wontfix.
