### ISSUE TITLE
wrong timestamp when using 'helm package'

### ISSUE THREAD

**Issue by samwelkey** [helm/helm#4158]
!-- If you need help or think you have found a bug, please help us with your issue by entering the following information (otherwise you can delete this text): -->

Output of `helm version`: v2.9.2
Output of `kubectl version`: 1.7.6

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

When using 'helm package my-chart' to pack my chart. The archive seems to be okey. But when I try to unzip that archive, the files in the folder all have the wrong time stamp which is: 1969-12-31 19:00:00.

**Comment by mattjmcnaughton** [comment]
Great catch! You are totally right. I'll work on a pr to fix this :)
