### ISSUE TITLE
Problem expanding in .Files.Glob().AsConfig

### ISSUE THREAD

**Issue by mduft** [helm/helm#4166]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:26:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
kubeadm-dind cluster with 2 nodes.

There is some strange behaviour when expanding config files into a ConfigMap. I have this template:

```
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Release.Name }}-log-config
data:
{{ (tpl (.Files.Glob "cfg/log4j-*").AsConfig . ) | indent 2 }}
```

and this values.yaml:

```
[snip]
system:
  logserver: 31000
[snip]
```

Now in a file `log4j-standard.xml` I have this snippet somewhere

```
[snip]
		<!-- Log Messages will be sent to the central Log Server -->
		<WamasSocket name="socket-appender" host="{{ .Release.Name }}-settings-server" port="{{ .Values.system.logserver }}">
			<SerializedLayout />
		</WamasSocket>
[snip]
```

`helm template .` (and `helm install --dry-run .` the same) always gives me:

```
Error: render error in "wamas-helm/templates/cfg-test.yaml": template: wamas-helm/templates/cfg-test.yaml:6:4: executing "wamas-helm/templates/cfg-test.yaml" at <tpl (.Files.Glob "cf...>: error calling tpl: Error during tpl function execution for [snip] </Loggers>\\n\\n</Configuration>\\n\"\n": parse error in "wamas-helm/templates/cfg-test.yaml": template: wamas-helm/templates/cfg-test.yaml:182: unclosed action
```

If I move the `logserver` definition out of the `system` interface to the top-level of values.yaml and adapt the expansion in the .xml file accordingly, it works as expected.

I have also tried to use `with`, both in the ConfigMap template YAML, as well as directly inside the log4j-standard.xml file to no avail. I also tried to pass a different context than `.` to `tpl`, which results in a different error message (`Error: render error in "wamas-helm/templates/cfg-test.yaml": template: wamas-helm/templates/cfg-test.yaml:7:4: executing "wamas-helm/templates/cfg-test.yaml" at <tpl ($.Files.Glob "c...>: error calling tpl: Cannot retrieve Template.Basepath from values inside tpl function: [snip] </Loggers>\n\n</Configuration>\n"
 (BasePath is not a value)`

**Comment by amanuel6** [comment]
Did you figure out the solution to this? I'm having the same error.

**Comment by mduft** [comment]
Unfortunately not...

**Comment by juv** [comment]
This might be related to the issue I found: https://github.com/helm/helm/issues/5446
Hope this helps.

**Comment by kivagant-ba** [comment]
```
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Release.Name }}-log-config
data:
{{ tpl (.Files.Glob "cfg/log4j-*").AsConfig $ | indent 2 }}
```

Just replace `.` with `$` in the second argument for `tpl`

Also there's one more trick:

- _helpers.tpl
```
{{/* tpl won't work here for each value because global scope is not available inside the template and Template.Basepath can't be recieved, but we can cover the entire result with "tpl" function */}}
{{- define "annotations" -}}
{{- range $k, $v := . }}
{{ $k | quote }}: {{ $v | quote }}
{{- end -}}
{{- end -}}
```
- ingress.yaml
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
  annotations:
    # tpl works here as a wrapper around the entire template
    {{ tpl (include "annotations" .Values.annotations) $ | toYaml | indent 4 }}
```
- values.yaml

```yaml
annotations:
  customLabel.local: "A test long annotation with special characters ~!@#$%^&*(_+."
```

**Comment by bacongobbler** [comment]
Closing as answered. Thanks!
