### ISSUE TITLE
Helm ls of non-existent release from 2.8.2 to 2.9.1 server produces error

### ISSUE THREAD

**Issue by s-rogers** [helm/helm#4169]
Output of `helm version`:

Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-2+231cc32d0a1119", GitCommit:"231cc32d0a111940d45936b3206548c610869df2", GitTreeState:"clean", BuildDate:"2018-04-25T08:09:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

IBM Containers

-----------------------

If you run 

helm ls "something that does not exist"

previously the command has exited with RC0 with no output.  We have code that relies on this,  When running the same command with helm 2.8.2 client to 2.9.1 server you get the following:

Error: EOF

with a RC of 1.

Moving up the client to 2.9.1 reverts to the previous behaviour

**Comment by PureWhiteWu** [comment]
Helm client and tiller server should **ALWAYS** be the same version.

**Comment by PureWhiteWu** [comment]
Because helm client interacts with tiller server using grpc and protobuf.

**Comment by s-rogers** [comment]
I'm sorry - I'm not sure I understand this - so how are upgrades supposed to work?  Are we saying there is NO guarantee that previous client versions work with new server versions, and an outage is to be expected on every release of helm?  Our previous observations are that we can upgrade the server from one point - e.g from our operator systems, and our build systems/deployed apps that use the older helm client continue to work until we upgrade their clients.  This issue was an observation that in such cases there is an error in the backwards compatibility of the server - if we are saying there is no such thing as backwards compatibility then

1) It is incredibly important that we get confirmation that this is the case
2) We need to completely rethink our use of helm if it is only designed to be used from a single point and at a single version

**Comment by PureWhiteWu** [comment]
Yes, helm client's version should be the same as the server's, or it may break.
You can upgrade  in  these steps:
1. upgrade your helm client
2. upgrade your tiller using `helm init --upgrade`
If helm client's version is not the same as tiller's, the protobuf they use may be different, which cause client cannot interact with tiller.

**Comment by s-rogers** [comment]
Thanks for the response, but just to be clear as this is a huge deal for us, are you saying that it is 100% not supported in any situation to run older clients against a new server version?  That there is no consideration for backwards compatability in new server versions whatsoever, and we have just been lucky so far?  Is there somewhere in the docs that confirms this?

We have multiple places all using helm continuously in our automated pipeline and deployed services:

 - CI pipeline installing new charts to various clusters - Jenkins running its own version of helm
 - Operators interacting with clusters from their machines with their own helm versions
 - Pods running helm to dynamically create and delete releases live in the running system

If there is no backwards compatibility at all, then there is no way for us to upgrade the version of helm in these systems without a potential pipeline outage and/or a production outage.

If this is the case, then is it true that the usage pattern helm is designed around is a single client somewhere that controls the version of the server, and it not really designed for multiple independent clients accessing the same tiller deployment, and especially not having running services that use helm?

**Comment by PureWhiteWu** [comment]
If the protobuf model is not changed, I suppose it may work well. For example, you can use v2.8.1 helm client with v2.8.2 tiller server since the protobuf  model is not changed.
If the protobuf model is changed, it will be broken. For example, you cannot use v2.8.2 helm client with v2.9.0 tiller server.
It's suggested that you should use the same version of client and server, or there's no guarantee of backwards compatibility.

**Comment by PureWhiteWu** [comment]
It's not designed to only be used by a single client. It is supposed easy to change the helm client's version in your environments.
Sorry my english is bad. Welcome to ask me if you have further questions.

**Comment by SlickNik** [comment]
Hi @s-rogers. Thanks for reporting this!

Helm is meant to be backwards compatible across minor and patch versions, so you should definitely be able to use a v2.8.1 client against a v2.9.2 server. We follow semver (https://semver.org/) so backwards-incompatible changes are only made across major versions.

That said, I haven't had the change to look into why this issue might be occurring; the change in return code does make it sound like there is a bug somewhere that we need to look at.

**Comment by bacongobbler** [comment]
closing as inactive.
