### ISSUE TITLE
Update where you tell people to download the new version

### ISSUE THREAD

**Issue by jchauncey** [helm/helm#417]
right now when helm is out of date you get the following:

```
[WARN] A new version of Helm is available. You have 0.4.0+9812f90. The latest is 0.5.0
---> Download version 0.5.0 here: https://github.com/helm/helm/releases/tag/0.5.0
```

The problem is that this only contains the source zip/tar.gz which isn't convenient. This should probably point to where they can find the binary.

**Comment by mboersma** [comment]
Closed by #420.
