### ISSUE TITLE
upgrade --force does not work as described

### ISSUE THREAD

**Issue by MichaelPanchenko** [helm/helm#4177]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-05-12T04:12:12Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
minikube version: v0.27.0
```

```helm upgrade --force release chart``` should work as 
```helm delete release && helm install --replace -n release chart``` but it does not - using the former resources are not redeployed if no change happened.

Steps to reproduce: create some dummy helm chart and then:

__INSTALL__
```
helm install -n job-test ./panchenkoinit

NAME:   job-test
LAST DEPLOYED: Tue Jun  5 16:43:27 2018
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/ConfigMap
NAME                DATA  AGE
job-test-configmap  1     0s

==> v1/Job
NAME     DESIRED  SUCCESSFUL  AGE
example  1        0           0s

==> v1/Pod(related)
NAME           READY  STATUS             RESTARTS  AGE
example-bl4db  0/1    ContainerCreating  0         0s
```
__TRY TO FORCE UPGRADE__

```
helm upgrade --force job-test ./panchenkoinit

Release "job-test" has been upgraded. Happy Helming!
LAST DEPLOYED: Tue Jun  5 16:44:46 2018
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/ConfigMap
NAME                DATA  AGE
job-test-configmap  1     1m

==> v1/Job
NAME     DESIRED  SUCCESSFUL  AGE
example  1        1           1m

==> v1/Pod(related)
NAME           READY  STATUS     RESTARTS  AGE
example-bl4db  0/1    Completed  0         1m
```

Note the age of the resources and the fact, that no new pod was started for the job.

__DELETE AND REINSTALL__

```
helm delete job-test
release "job-test" deleted

helm install --replace -n job-test ./panchenkoinit
NAME:   job-test
LAST DEPLOYED: Tue Jun  5 16:46:57 2018
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/ConfigMap
NAME                DATA  AGE
job-test-configmap  1     1s

==> v1/Job
NAME     DESIRED  SUCCESSFUL  AGE
example  1        0           1s

==> v1/Pod(related)
NAME           READY  STATUS             RESTARTS  AGE
example-skzhj  0/1    ContainerCreating  0         1s
```

Now the resources indeed have been re-deployed - see their age and the new pod for the job

**Comment by mattjmcnaughton** [comment]
I think I understand why this is happening - @bacongobbler can you confirm the requested behavior in the issue (i.e. delete and recreate) is preferred? If so, I'll submit a pr :)

**Comment by ieugen** [comment]
I have also encountered this issue with jobs. 
I have a helm chart that has configmap and a job (that is deleted after success). 
The purpose of the job is to download and install some static content filess (web apps) via npm. 

However helm upgrade fails to run the job.

My job definition looks like this.
````
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "ui-apps.fullname" . }}
  labels:
    app: {{ template "ui-apps.name" . }}
    chart: {{ template "ui-apps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
```

I've tried even with --install:
```
helm upgrade --install staging-ui-apps --namespace staging ./ --force --debug
```

kubernetes 1.11.0 

```
helm version 
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

**Comment by bacongobbler** [comment]
To ensure that tiller makes every best effort to do a graceful upgrade, --force first attempts the "gentle" approach first before disrupting services' traffic with an ungraceful upgrade.

If the previous release was in a DEPLOYED state and can be cleanly upgraded, then it will just do a normal `helm upgrade`. the `helm delete && helm install --replace` logic doesn't kick in unless the initial attempt to do a graceful upgrade fails.

Does that help clear things up?

**Comment by ieugen** [comment]
@bacongobbler thanks. 

I think it works and I have been confused. I expected the Job to run longer but it was over and cleaned inb ~4s so for me it works.

**Comment by edwardstudy** [comment]
Hi, @bacongobbler. Can you help to find a way to “reinstall” same release if my resource was broken? I  just tried to use `helm upgrade --force` to “reinstall” same release but it may do a graceful upgrade b/c this reelase didn't have any changes.

**Comment by bacongobbler** [comment]
Closing as answered.
