### ISSUE TITLE
Helm comments broken, greedily eating pre/post whitespace

### ISSUE THREAD

**Issue by bgehman** [helm/helm#4191]
Output of `helm version`:
```
Client: v2.9.1+g20adb27
Server: v2.9.1+g20adb27
```

Output of `kubectl version`:
```
Client Version: v1.9.6
Server Version: v1.9.6
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
docker-edge (Mac)
```

Helm comments, described at: https://docs.helm.sh/chart_best_practices/#comments-yaml-comments-vs-template-comments, are broken.  Example:

```
apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
{{- /*
This is a comment.
*/ -}}
name: test
version: 0.1.0
```

Is being rendered into something like:
```
apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetesname: test
version: 0.1.0
```
Note the: `description: A Helm chart for Kubernetesname: test`
Where the line after the comment, is being tacked onto the end of the line proceeding the comment -- seems the helm-comment style greedily eats all whitespace before/after the comment, which is entirely unexpected and results in difficult to debug errors:

```
$ helm lint
==> Linting .
[ERROR] Chart.yaml: unable to parse YAML
	error converting YAML to JSON: yaml: line 5: could not find expected ':'
[ERROR] templates/: error converting YAML to JSON: yaml: line 5: could not find expected ':'

Error: 1 chart(s) linted, 1 chart(s) failed
```

As an aside: it would also be nice if the linter would actually print the YAML document that was rendered so users can see the corrupted YAML (after the helm processing) that can't be converted to JSON.

**Comment by bgehman** [comment]
Perhaps a clearer example.
```
$ helm create test
```
Edit the pre-generated `deployment.yaml` and add a comment anywhere inside:
```
...
    spec:
{{- /*
This is a comment.
*/ -}}
      containers:
...
```

```
$ helm install --dry-run --debug --namespace test --name test test
```

Shows:
```
...
    spec:containers:
...
```

**Comment by bacongobbler** [comment]
So the syntax behind `{{-` and `-}}` (notice the hyphen) is that they strip any whitespace either before the statement (`{{-`) and after the statement (`-}}`). So, the documentation should probably use the following form:

```
...
    spec:
{{ /*
This is a comment.
*/ -}}
      containers:
...
```

Can you try messing around with removing one of the hyphens and see what you come up with?

**Comment by bgehman** [comment]
@bacongobbler As far as I can tell, the `{{- /* */ -}}` is the required syntax for these style of comments, requiring the `-` for the begin and ending curly braces.

All four permutations: 

```
...
    spec:
{{ /*
This is a comment.
*/ }}
      containers:
...
```
Results in: `Error: parse error in "test/templates/deployment.yaml": template: test/templates/deployment.yaml:22: unexpected "/" in command`

```
...
    spec:
{{- /*
This is a comment.
*/ }}
      containers:
...
```

Results in: `Error: parse error in "test/templates/deployment.yaml": template: test/templates/deployment.yaml:22: unexpected comment ends before closing delimiter in input`

```
...
    spec:
{{ /*
This is a comment.
*/ -}}
      containers:
...
```
Results in: `Error: parse error in "test/templates/deployment.yaml": template: test/templates/deployment.yaml:22: unexpected "/" in command`

And the original example:
```
...
    spec:
{{- /*
This is a comment.
*/ -}}
      containers:
...
```
Results in:
```
...
    spec:containers:
...
```

**Comment by nickarnold** [comment]
@bacongobbler I'm experiencing the exact behavior (using Helm v2.9.1) that @bgehman describes, and was also left confused after adding some template comments per the docs 'best practice' suggestion he noted.

Luckily, after some playing around I've found that the following syntax generates my expected output, which is to say that it removes the comment from the generated manifest without leaving an extra newline in:

```
data:
  {{- /*
  Some comment describing the next key/val
  */}}
  foo: "bar"
  bob: "alice"
```

Generated output:
```
data:
  foo: "bar"
  bob: "alice"
```

Note the lack of `-` and whitespace in the comment closing section. Every other combination I tried generates either an error as was noted above or inserts an extra and undesired newline.

**Comment by krish7919** [comment]
Same issue here; however, I just added an empty blank line after the helm comment to make it work.

**Comment by rdxmb** [comment]
using `-}}` within helm-templates ist mostly not a good idea. 

Within the `_templates.tpl`, where they define some functions, it may be ok. Having it within or at the end the templates-files it will often occur in errors, at least when `helm template` is used - and then concat the output with `cat *`. Then in most cases whitespaces are missing, which ends in errors when using kubectl.

This may not be a typical use case, but it seems to be more clean to end `}}` without `-` whenever it is possible.

**Comment by bacongobbler** [comment]
closing as answered, but please feel free to re-open if there's additional questions here. Thanks

**Comment by bgehman** [comment]
@bacongobbler The best-practices doc (and examples) still need to be reworked: https://helm.sh/docs/chart_best_practices/#comments-yaml-comments-vs-template-comments

Also, note that the suggested solution from @nickarnold (https://github.com/helm/helm/issues/4191#issuecomment-417096290) (which does work BTW, thanks Nick!) violate another part of the best practices document: https://helm.sh/docs/chart_best_practices/#formatting-templates

> Template directives **should have whitespace** after the opening braces and **before the closing braces**

**Comment by rdxmb** [comment]
> feel free to re-open

there are no permissions for the community to re-open, by the way

**Comment by bacongobbler** [comment]
If someone wants to amend the documentation with learnings from this issue, please feel free to do so. Thanks!

**Comment by bacongobbler** [comment]
closing as inactive.

**Comment by vhosakot** [comment]
I hit this too today and wasted many hours debugging errors due to missing whitespace.
https://helm.sh/docs/chart_best_practices/templates/#formatting-templates
> Template directives should have whitespace after the opening braces and before the closing braces
