### ISSUE TITLE
helm create doesn't work with nested template directories

### ISSUE THREAD

**Issue by booninite** [helm/helm#4193]
Output of `helm version`:

Client: v2.9.1+g20adb27
Tiller isn't involved with this issue

Output of `kubectl version`:

`kubectl` isn't involved in this issue.

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

No cloud provider involved in this issue.

Description:

If you create a starter chart that has a `templates/tests` directory containing some test templates, move that starter chart to `helm home`/starters/<name> and then invoke via `helm create test -p <name>`, you will get an error similar to this:

```
➜  ~/code  helm create test -p bcs
Creating test
Error: open test/templates/tests/test-integration.yaml: no such file or directory
```

In order to make sure that my starter chart was correctly set up:

```
➜  ~/code  rm -rf `helm home`/starters/bcs
➜  ~/code  mkdir -p `helm home`/starters
➜  ~/code  cp -r k8s/charts/bcs-starter-chart `helm home`/starters/bcs
➜  ~/code  ls `helm home`/starters/bcs
Chart.yaml               global.food.values.yaml  templates/
README.md                skaffold.starter.yaml    values.yaml
➜  ~/code  ls /Users/shimmerjs/.helm/starters/bcs/te
ls: /Users/shimmerjs/.helm/starters/bcs/te: No such file or directory
➜  ~/code  ls /Users/shimmerjs/.helm/starters/bcs/templates
NOTES.txt        configmap.yaml   secrets.yaml     tests/
_helpers.tpl     deployment.yaml  service.yaml
➜  ~/code  ls /Users/shimmerjs/.helm/starters/bcs/templates/tests
test-integration.yaml
➜  ~/code  helm create test2 -p bcs
Creating test2
Error: open test2/templates/tests/test-integration.yaml: no such file or directory
```

**Comment by bacongobbler** [comment]
Potentially related https://github.com/kubernetes/helm/pull/3567

**Comment by sgandon** [comment]
I believe this is more a bug than a feature. 
Is there any workaround this issue cause this really makes the `helm create` pretty useless.

**Comment by sgandon** [comment]
if it was related to #3567 would'nt it be fixed by it, cause it is not in the latest version.

**Comment by bacongobbler** [comment]
If it wasn't supported in the first place then we consider it a feature as it was not considered during the initial design of the command. :)

**Comment by sgandon** [comment]
I did clone the master and realized that this is partly fixed here https://github.com/helm/helm/pull/4524. 
If you folder is called *tests* then it will be created and this shall be available on the next release.
I wish this implementation was more flexible and could cope with any subfolder.

**Comment by katsew** [comment]
I'm having the same issue ;(
I created my own starter with manifest like `templates/storageclass/standard.yaml`, but this error occurred...
I flatten the dir `storageclass` and put `standard.yaml` into `templates/standard.yaml`, it's fine.

```
helm create foo -p my-starter
Creating foo
Error: open foo/templates/storageclass/standard.yaml: no such file or directory
```

helm version --short:
```
Client: v2.9.1+g20adb27
Server: v2.12.0+gd325d2a
```

kubectl version --short:
```
Client Version: v1.10.7
Server Version: v1.10.7-gke.11
```

cloudprovider: GKE

**Comment by bacongobbler** [comment]
closing as inactive.
