### ISSUE TITLE
string interpreted as float in values.yaml

### ISSUE THREAD

**Issue by bjamet** [helm/helm#4194]
Output of `helm version`: 2.9.1

Hello 
a value this form in a values.yaml file : 
<pre>
tag: 0e1234
</pre>
is interpreted by tiller as the number 0 instead of the string value "0e1234" (in my case this is a git commit ). 
The reason I think is that the version of gopkg.in/yaml.v2 is this one in glide.lock : 
  version: 53feefa2559fb8dfa8d81baad31be332c97d6c77 (date of version 2015-09-24) 
when this issue is corrected in gopkg.in/yaml.v2 in the commit 
4c78c975fe7c825c6d1466c42be594d1d6f3aba6 (date : 2017-01-25), included in version v2.0.0 of yaml.v2

I suppose adding gopkg.in/yaml.v2 with version ^2.0.0 might solve the issue

**Comment by bacongobbler** [comment]
related #1707

**Comment by bacongobbler** [comment]
@bjamet can you use `--set-string` for the time being? Thanks for bringing up the potential fix; I'll see if I have time to test that out today.

**Comment by bjamet** [comment]
Hello
Unfortunately I can't. I'm using helm in a process where the yaml file used for the values is generated. So I had to use the the file as input values, and not --set-string. 
But the problem is not that urgent for me, I just create a dummy git commit as workaround... but It can append again.

**Comment by ryan1894** [comment]
I believe this issue is due to the YAML spec interpreting 0e1234 specifically as a float, specifically [this rule](http://yaml.org/type/float.html)

As a workaround, could you surround that string with quotes?
i.e. `tag: "0e1234"`?

**Comment by bjamet** [comment]
I suppose the workaround would work, but I found this problem on a yaml file which was generated from another program, for which 0e1234 was a string and not a float... 
and I couldn't change this program to use quote.

**Comment by ryan1894** [comment]
That's a bug you should take up with that application then.

**Comment by bjamet** [comment]
the application use the library gopkg.in/yaml.v2 in latest version (at least at the time I opened this issue) for writing the yaml file. As I said in the first post, helm is using an older version of gopkg.in/yaml.v2. In between there is a feature that make the behavior : to turn 0e1234 as a string and not a float... 

So in which version of gopkg.in/yaml.v2 ther is a bug ? the old or the new ? 
So which application should be change the version of the library to be compatible to the other ? 

I just say that if helm doen't confort to the more recent version of yaml.v2, it might force other application to stay stuck to this version.

**Comment by jeff-knurek** [comment]
it looks like if this issue was caused by the old version of `gopkg.in/yaml.v2`, then it's been resolved since version 2.14+ 

@bjamet can you confirm that this problem is now resolved?
