### ISSUE TITLE
Question: Switching between different K8s clusters

### ISSUE THREAD

**Issue by thangbn** [helm/helm#4195]
I'm working with multiple k8s clusters at the same time. To switch helm context to a different cluster, I have to do a **kubetcl config use-context \<context name\>** and then do **helm init** again.

Is there any easier way to do this in Helm? 

Tried to do search through the issues and Google and found nothing.
If no such feature is there already. I think it would be a great thing to be added to helm.

Appreciate all your kind help.
Thanks

**Comment by Damien-DeZurik** [comment]
Hmmm, `helm init ...` isn't what you should use every time you switch contexts...
I agree, though, it is a pain with tiller to have to change $TILLER_NAMESPACE every time you change context.  You could start using `--tiller-namespace xyz` with your `helm` commands and skip changing the environment variable every time.  I suppose you could also make an alias or short script that changes both k8s context and tiller namespace in one swoop.

**Comment by bacongobbler** [comment]
You can use the --kube-context=context-name global flag to switch the context on-the-fly.

**Comment by thangbn** [comment]
@Damien-DeZurik I think the **--tiller-namespace** option is to specify the namespace that tiller will be installed
@bacongobbler yeah, we can do that but it quite cumbersome to include that every command, something like **kubectl use-context** would be awesome

**Comment by bacongobbler** [comment]
okay. Re-marking this as an enhancement proposal since this functionality does not exist.

**Comment by stepanselyuk** [comment]
Modified the script above a bit:

```
#!/usr/bin/env bash
#
# this script is a helpful wrapper for Helm CLI, when using TLS enabled Tiller 
# See https://github.com/helm/helm/blob/master/docs/tiller_ssl.md
#
# save this somewhere in your PATH (e.g. /usr/local/bin/)
# as helm_tls_wrapper.sh
# and add shell alias (so that shell-completion works without any additional changes)
# alias helm=helm_tls_wrapper.sh
#
# save your TLS certificates in ${HELM_HOME}/tls/${K8S_CONTEXT}/
# as ca.pem, cert.pem, and key.pem

: ${HELM_HOME:=~/.helm}

[[ "$(uname)" == "Darwin" ]] && grep="ggrep" || grep="grep"

K8S_CONTEXT_ARG="$(echo "$@" | $grep -Po '(?<=--kube-context=)\S+')"

if [[ -n "${K8S_CONTEXT_ARG}" ]]; then
  K8S_CONTEXT="${K8S_CONTEXT_ARG}"
else
  K8S_CONTEXT="$($grep -Po '(?<=^current-context: ).*$' ~/.kube/config)"
fi

for arg in $@; do
  if [[ "$arg" == "--tls" ]]; then
    export HELM_TLS_CA_CERT="${HELM_HOME}/tls/${K8S_CONTEXT}/ca.pem"
    export HELM_TLS_CERT="${HELM_HOME}/tls/${K8S_CONTEXT}/cert.pem"
    export HELM_TLS_KEY="${HELM_HOME}/tls/${K8S_CONTEXT}/key.pem"
    export HELM_TLS_ENABLE="true"
    # export HELM_TLS_VERIFY="true"
    break
  fi
done

# change home for every k8s context
export HELM_HOME="${HELM_HOME}/${K8S_CONTEXT}"

if [[ ! -d "${HELM_HOME}" ]]; then
  mkdir -p "${HELM_HOME}"
  helm init --client-only
fi

helm $@
```

It creates now a subfolder in `~/.helm/` for every k8s context.
I put it in the system as `/usr/bin/local/helmsh`

**Comment by anapsix** [comment]
@stepanselyuk neat, thanks

**Comment by anapsix** [comment]
updated the script (https://gist.github.com/anapsix/eff8a9248fc5ba446fcb373daae143b9) to auto-download Helm Client version to match Server (tiller) component version

**Comment by bacongobbler** [comment]
closing as inactive.
