### ISSUE TITLE
Install NetworkPolicies after Namespaces

### ISSUE THREAD

**Issue by mgruener** [helm/helm#4199]
Helm should install NetworkPolicy resources after Namespace resources.

Currently the InstallOrder at https://github.com/kubernetes/helm/blob/master/pkg/tiller/kind_sorter.go#L29 does not list the NetworkPolicy resource. If a chart creates a Namespace resource and a NetworkPolicy resource in this Namespace, the deployment of the chart might fail because helm tries to create the NetworkPolicy before the Namespace has been created.

**Comment by bacongobbler** [comment]
Since they are omitted from the known list of objects they should be installed last according to [TestKindSorter](https://github.com/kubernetes/helm/blob/master/pkg/tiller/kind_sorter_test.go#L26). Would you mind adding a unit test to verify that behaviour or by supplying a chart to test this?
