### ISSUE TITLE
Update Copyright

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#4201]
Now that Helm is under the CNCF they are advising we update the copyright to "Copyright The Helm Authors.". This is essentially replacing "Kubernetes" with "Helm" in the copyright statement for code files.

The CNCF is the parent organization for both Kubernetes and Helm. This is the direction coming from them.

**Comment by dankohn** [comment]
Specifically, the recommendation is to change from "Copyright 2016 The Kubernetes Authors All rights reserved." to "Copyright The Helm Authors." The regex to do that will need to take into account different years.

**Comment by mattfarina** [comment]
@dankohn Should the words "All rights reserved" be removed? Or should it be "Copyright The Helm Authors. All rights reserved."?

**Comment by dankohn** [comment]
You're literally not reserving all rights, since the Apache license allows
others to do lots of things. So, I recommend against including it.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com
