### ISSUE TITLE
Switching from CLA to DCO

### ISSUE THREAD

**Issue by michelleN** [helm/helm#4206]
Helm is now part of CNCF. As part of the transition to CNCF, we have been asked to switch to adding [Developer Certificate of Origin (DCO)](https://developercertificate.org/) support. CNCF projects are now required to use DCO. We can also vote to drop the CLA but that is up to the maintainers.

The CNCF has found that the DCO process allows for a lower barrier to entry when it comes to contributing to open source. It just requires the developer to sign their commits using the `-s` flag: `git commit -s`

- [x] I believe we can use this one-click install process to do so:[https://github.com/integration/dco]( https://github.com/integration/dco)
- [x] We'll also need some documentation or do a blog post to let folks now that we've enabled DCO.
- [x] We'll need to update the CONTRIBUTING.md doc
- [x] Vote to drop the CLA and then drop the CLA.

If you'd like to learn more about DCO, check out [this](https://blog.chef.io/2016/09/19/introducing-developer-certificate-of-origin/) post.

I'll leave this here for a week before we make the switch to raise awareness, answer questions, and give folks an opportunity to express concerns/objections.

cc/ @dankohn @technosophos @mattfarina

**Comment by dankohn** [comment]
Note that the maintainers of each CNCF project decide whether they want to
use the CLA or not. You can do CLA + DCO or just DCO. I recommend just DCO
because it's less friction for new contributors, but it's up to you.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

On Mon, Jun 11, 2018 at 11:42 AM, Michelle Noorali <notifications@github.com

**Comment by michelleN** [comment]
Thanks Dan. I updated the original comment with that info as well.

**Comment by bacongobbler** [comment]
>  It just requires the developer to sign their commits using the `-s` flag: `git commit -s`

I LOVE the idea of switching to a DCO, but would this particular requirement make it too high of a barrier to contribute to Helm? I spent weeks figuring out how to properly sign my commits. I would not want to put that burden on every new contributor. :(

**Comment by bacongobbler** [comment]
According to https://github.com/integration/dco, the commit just needs a "Signed-off-by" signature in their commit which can be injected using the -x flag IIRC. If that's the process then I'm OK with that :)

**Comment by bacongobbler** [comment]
Oh wait, I'm conflating two flags:

- --sign is for "Signed-off-by"
- --gpg-sign is for signing your commits with a gpg signature

If it's the former then that sounds good to me!

**Comment by dankohn** [comment]
I think of it as `git commit -sam` instead of `git commit -am`. So, yes,
it's the former.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by mattfarina** [comment]
@dankohn I have a few CLA->DCO questions:

* Since the code has been contributed under the CLA what about the CLA allows us to change things to a DCO? Do we need any kind of sign-off from existing contributors for this switch to happen? I don't completely understand ownership, process, and who is empowered to do what. If you could clarify this is would help.
* If we switched to a DCO how would the process be different if we later wanted to switch to a CLA?
* The CLA contains a grant of patent license that is not there under the DCO. What are the implications of this part going away if a switch were to happen?

**Comment by dankohn** [comment]
See below.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

On Mon, Jun 18, 2018 at 1:37 PM, Matt Farina <notifications@github.com>
wrote:

> @dankohn <https://github.com/dankohn> I have a few CLA->DCO questions:
>
>    - Since the code has been contributed under the CLA what about the CLA
>    allows us to change things to a DCO? Do we need any kind of sign-off from
>    existing contributors for this switch to happen? I don't completely
>    understand ownership, process, and who is empowered to do what. If you
>    could clarify this is would help.
>
> Whether or not a CLA is required to contribute is a choice of the project
maintainers. The upside of requiring it is that some large companies
believe it provides more thorough protection than just having projects
contribute under the Apache license. The downside is that it adds friction
for new contributors.

I encourage you to read the CLA.
https://github.com/cncf/cla/blob/master/corporate-cla.pdf

Section 11(b)  of the CNCF charter says that project maintainers can choose
whether or not to require use of the CLA. https://www.cncf.io/about/charter/

>
>    - If we switched to a DCO how would the process be different if we
>    later wanted to switch to a CLA?
>
> The choice is DCO vs. DCO + CLA. Meaning, you need to have contributors
use the DCO no matter what.

You don't want to cycle back and forth for requiring the CLA. The project
maintainers should make a choice and plan to stick with it, unless some new
law or controversy comes up. If you did stop and then start requiring it,
only code contributed under the CLA would be covered by the CLA. But the
Apache license would still apply to all code no matter what.

>
>    - The CLA contains a grant of patent license that is not there under
>    the DCO. What are the implications of this part going away if a switch were
>    to happen?
>
> The patent grant is very much there under the DCO, it just comes from the
text of the Apache 2.0 license.

I encourage you to think of the CLA as an extra step to ensure that the
signer is really OK with open sourcing their copyright and making available
any patents that are read upon.

For reference, of CNCF's 22 non-Helm projects, only Kubernetes and gRPC
require the CLA.

**Comment by mattfarina** [comment]
Closing this issue as we moved to the DCO a long time ago. This work was completed.
