### ISSUE TITLE
Changing the namespace of a resource results in multiple resources 

### ISSUE THREAD

**Issue by Stono** [helm/helm#4211]
Hey, 
Helm 2.9.1

If you have a resource with:

```
namespace: some-namespace
```

And you change that to:
```
namespace: some-other-namespace
```

you'll end up with a resource in both namespaces, rather than the former being deleted.

**Comment by willfrew** [comment]
Issue still exists in Helm `2.11.0`

**Comment by jmasonISP** [comment]
I can confirm that this issue still exists as of `2.14.3`

**Comment by jeff-knurek** [comment]
this issue is resolved in `v3`, and so could be labelled as a `v2` bug. it is still present in `2.16.7`

**Comment by bacongobbler** [comment]
Given nobody has worked on this, I'm inclined to assume this is known behaviour and has been well documented at this point. Not planning on fixing this for Helm 2 as this has been addressed in Helm 3. Closing.
