### ISSUE TITLE
Add support for rendering objects to TOML strings via template functions

### ISSUE THREAD

**Issue by HT154** [helm/helm#4213]
I have an operator that expects TOML-serialized content of a Secret object. I'd like to be able to use Helm to perform this configuration by translating YAML values into the TOML string (and then base64 encoding it), but currently, I must have a second pass with a custom tool to translate the YAML->TOML and pass it to Helm.

It would be neat to generalize this and extend Helm's plugin interface to support adding new template functions.

**Comment by bacongobbler** [comment]
closing as inactive.
