### ISSUE TITLE
helm not warning before adding large files to deployment and failing in inconsistent state

### ISSUE THREAD

**Issue by lucidNTR** [helm/helm#4215]
When the chart directory contains obvious temp or dev/test files such as the helm binary itself or binary files that are obviously larger than the allowed depl config map. helm starts deploying without a warning and then crashes deployment with the error failed to create: ConfigMap "SOME_NAME.v1" is invalid: []: Too long: must have at most 1048576 characters
this warning is not printed by the helm cli but just in the tiller logs wich makes it even harder to find.

expected behaviour: helm ignores files that are obviously senseless to it by standard. 

or: helm warns "There are large files in the chart directory, that would be bundled into your deployment. Should we add them to the .helmignore file? Y/n"

Output of `helm version`:
v2.9.1
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.2-gke.3", GitCommit:"d2c7a2bd41036f9474287579a725dc54c904e92d", GitTreeState:"clean", BuildDate:"2018-05-23T00:19:39Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
gke

**Comment by bacongobbler** [comment]
marking as a feature
