### ISSUE TITLE
Confusing command naming|pairing: `helm create` & `helm install|delete`

### ISSUE THREAD

**Issue by DazWilkin** [helm/helm#4222]
As a noob, I must resort to reviewing helm's commands because `create`, `install` and `delete` seem inconsistently named:

`helm create`: Creates a helm [chart] directory with template files and directories
`helm install`: Deploys (!) a helm [chart] to a Kubernetes cluster [creating a release?]
`helm delete`: Uninstalls (!) a helm release

Recommend:
Reflecting `kubectl` (and other CLIs') use of `[command] [type] [name]` to aid memorization.
Perhaps `helm [create|delete] [chart|release]`?
Easily extended to the other currently very synonymous names to e.g. `helm [describe|get] [release]`

**Comment by technosophos** [comment]
This will definitely not change for backward compatibility reasons.

During Helm 2's dev cycle, this was the subject of much debate. We analyzed many different tools, and decided (by vote) on what we have now. `kubectl`, incidentally, is far from the norm on their CLI options. The typical pattern is actually CMD NOUN VERB, while kubectl uses CMD VERB NOUN sometimes and CMD NOUN VERB other times.
