### ISSUE TITLE
Proposal: sub-chart should have independent lifecycle from parent-chart

### ISSUE THREAD

**Issue by PureWhiteWu** [helm/helm#4227]
Firstly, sorry for my poor English.
I think sub-chart should have independent lifecycle from parent-chart, since many apps require sub-chart shuold be running before the parent-chart started to run.
At least I think we should give users an option to set if to deploy charts parallelly or not.
And I think maybe we can do this in Helm 3?

**Comment by bacongobbler** [comment]
closing as inactive.
