### ISSUE TITLE
helm template stable/grafana

### ISSUE THREAD

**Issue by remster** [helm/helm#4237]
Output of `helm version`:
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Minikube
`
helm template stable/grafana
Error: stat stable/grafana: no such file or directory
`
whereas
`
helm install stable/grafana
Error: release vocal-worm failed: ClusterRoleBinding.rbac.authorization.k8s.io "vocal-worm-grafana-clusterrolebinding" is invalid: subjects[0].namespace: Required value
`
So clearly i need to debug this, but don't see a way other than cloning stable charts

**Comment by SlickNik** [comment]
Hi @remster -- thanks for posting an issue with your feedback!
You shouldn't need to clone the stable/charts repo in this case. You can use `helm fetch` followed by `helm template`. This would look something like:
```
$ helm fetch stable/grafana
$ helm template grafana-1.11.4.tgz
```
Hope this works for you!
