### ISSUE TITLE
Proposal: Extract sub-chart as a separate release without downtime

### ISSUE THREAD

**Issue by okashino** [helm/helm#4244]
We would like to be able to extract a sub-chart as a separate release without incurring any downtime due to deleting K8s resources.
For example, we have an umbrella chart A that has a sub-chart B. We wanted to extract chart B as a separate release to simplify our CI/CD pipeline. However, in order to do that, we would have to delete chart B from chart A's charts directory which would result in deleting the deployments, services and other K8s resources associated with chart B. Then, create a new release based on chart B. Deleting K8s resources results in downtime for chart B services.
My proposal is to introduce a helm command that would extract/move sub-charts into a separate release without affecting the availability of K8s resources.

**Comment by bacongobbler** [comment]
closing as inactive.
