### ISSUE TITLE
[docs.helm.sh] "related" link broken on "The Helms Plugin Guide" page

### ISSUE THREAD

**Issue by DazWilkin** [helm/helm#4245]
Reference to '[related](https://github.com/kubernetes/helm/blob/master/docs/related.md#helm-plugins)' works from the GitHub [page](https://github.com/kubernetes/helm/blob/master/docs/plugins.md) but not from '[related](https://docs.helm.sh/using_helm/related.md#helm-plugins)' on the companion helm.sh [page](https://docs.helm.sh/using_helm/#the-helm-plugins-guide)

**Comment by technosophos** [comment]
Tracking here: https://github.com/helm/helm-www/issues/133

**Comment by bridgetkromhout** [comment]
Looks like this was resolved via https://github.com/helm/helm-www/pull/168.

**Comment by bacongobbler** [comment]
Good catch @bridgetkromhout! Closing.
