### ISSUE TITLE
Cannot delete pods even after helm delete

### ISSUE THREAD

**Issue by kannanlakshmi** [helm/helm#4260]
Output of `helm version`:
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.8-gke.0", GitCommit:"6e5b33a290a99c067003632e0fd6be0ead48b233", GitTreeState:"clean", BuildDate:"2018-02-16T18:26:58Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Local machine

`helm delete my-release` doesn't seem to actually delete the pods. Below are my instructions to delete `my-release`

`$ helm delete my-release`
Error: the release named "my-release" is already deleted

And then when I run `$ kubectl get pods` looks like they are still running. 

NAME                               READY     STATUS    RESTARTS   AGE
my-release-cockroachdb-0           1/1       Running   0          1h
my-release-cockroachdb-1           1/1       Running   0          1h
my-release-cockroachdb-2           1/1       Running   0          1h

`$ kubectl get statefulsets` results in this: 
NAME                             DESIRED   CURRENT   AGE
my-release-cockroachdb           3         3         1h

**Comment by a-robinson** [comment]
As @kannanlakshmi shared with me separately but forgot to include here, the tiller logs indicate that a delete was attempted but that "the server could not find the requested resource" - https://gist.github.com/kannanlakshmi/476bd3ec7e04b0e29cf88329e2790d08

**Comment by usernameusr** [comment]
In my case  helm install stable/cockroachdb is not at all coming up.


[root@helm ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
[root@helm ~]# helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

**Comment by bacongobbler** [comment]
closing as inactive.
