### ISSUE TITLE
Add to helm: response format

### ISSUE THREAD

**Issue by itye-msft** [helm/helm#4266]
Hi,
In our use case, an internal admin dashboard application is executing helm commands inside the cluster.  Based on input from the dashboard, we need to call a chart, and we supply parameters.
Generally speaking: we are programmatically executing helm.
This was the easy part, and it works nicely. 
Helm, however, return a non-formatted response. It just prints to the stdout some text.

If going with the programmatic approach, the code that executes a helm command should be able to flag the output to be in a machine readable format, such as json or yaml.

**I raise this issue to ask a support for a formatted response.**

For example:
`helm install stable/rabbitmq -output json`

Based on this discussion, if it will be relevant, I would also like to contribute the solution.

Thanks
Itye

**Comment by technosophos** [comment]
Some work was started on this, but not finished for all commands. Take a look at the `--output` flag on `helm list`. We'd love a PR.

**Comment by bacongobbler** [comment]
closing as inactive.
