### ISSUE TITLE
template externalIPs

### ISSUE THREAD

**Issue by kfox1111** [helm/helm#4268]
when creating a new chart with helm create <foo>, the service created is incapable of being bound to external ip's.

please add:
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}

to the template.

**Comment by jascott1** [comment]
@kfox1111 Hey, long time! Are you aware you can make your own 'create' templates?

**Comment by kfox1111** [comment]
hey @jascott1 yeah. been too long. :/ Good to see you again. :)

Yeah, I'm aware of them. Just saying though, out of the box create leaves out an important bit of boilerplate code. I regularly use externalIPs to expose services and in this case and I'm continuously hav,ing to tell users to add that boiler plate after helm create. Its such a small thing creating a whole parallel template set seems like a huge lift. its absence feels like not having nodeSelectors, tolerations, etc.

**Comment by bacongobbler** [comment]
closing as inactive.
