### ISSUE TITLE
Helm does not check CRL TLS certificate revocation

### ISSUE THREAD

**Issue by sprutner** [helm/helm#4273]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-05-12T04:12:12Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-28T20:13:43Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Amazon EKS

---
I have experimented with Helm TLS authentication extensively, and have found a few flaws that are significant issues. I aim to use my own PKI to issue certificates for use with helm, and conversely to revoke them and have helm respect the revocation.

I used Amazon Private CA and was able to issue certificates to individual test users. Helm is using that Private CA to control access to tiller. Any certificate issued by the CA works to access tiller as expected.

When the certificate is revoked, it's serial number is added to the CRL that is on the certificate, as expected. However, when using the now revoked certificate to authenticate to tiller, it still works. It seems to me that while Helm is still validating the certificate is issued by the appropriate CA, it is not providing any revocation checking. This presents a security issue, and the solution of which means issuing short-lived certificate or having revocation checking enabled.

I am curious to hear your plans for supporting this in the future, or if it will not be supported at all.

**Comment by technosophos** [comment]
No updates that I know of, but I will look into it.

I'm assuming that the cert that had the CRL list was also available to Tiller, right?

**Comment by technosophos** [comment]
Also, the original issue says "a few flaws" -- are there others I should check on?

**Comment by pbazydlo** [comment]
sorry I missed that part maybe @sprutner could elaborate on those

the only one we have seen so far is not respecting certificate revocation, in our case CRL list is publicly available
thanks for getting back this quickly

**Comment by pbazydlo** [comment]
Thanks for looking into this

**Comment by bwhaley** [comment]
Hi all, I’m late to the party here, but just a quick clarification: if revocation is not supported, is there any method to revoke access for a client that has a signed cert? Or would tiller need to be reconfigured with a new CA and certs reissued to all desired entities?

**Comment by bacongobbler** [comment]
closing as inactive.
