### ISSUE TITLE
Helm cannot fetch values from within a repository chart

### ISSUE THREAD

**Issue by mumrau** [helm/helm#4275]
Hello everyone,

First of all I wanna apologize in case I missed something crucial or if I didn't find the desired resource.

I set up my own chart repository (through chartmuseum for that matters) and I got it fully working except for one thing (which might not be supported), let's suppose the chart I wanna deploy is really abstract in the sense that it is versatile depending on provided values file.
I cannot deploy that chart with one of the several values file in my remote chart folder (alongside Charts.yaml), even though it is packaged inside the chart archive that I can retrieve using helm fetch.

Finally, this might be a feature that I couldn't find (my bad), or an eventual feature request, because I do believe this would be a pretty valuable feature.

EDIT: I just noticed that #2642 referenced that possibility, I just find it pretty strange that you would have to link remote files while they were already in the chart archive (tgz).

**Comment by jascott1** [comment]
Hi @Mumrau 

Could you clarify the request here? It sounds like you want to have more than one values file and be able to fetch it, is that correct?

**Comment by Mumrau** [comment]
I'll try to be clearer, I apologize.

I would like helm to be able to inject values files that are included withing the chart package, I don't know the operation flow but to the best of my knowledge helm retrieves the tgz completely so the custom values are here somehow. 
Let's assume I have this package (unrelevant files won't be shown):
```
my-chart
    - templates
        - stuff
    - Chart.yaml
    - custom-values.yaml
    - another-one-values.yaml
```
I would like being able to do `helm install repo/my-chart --values custom-values.yaml --values another-one-values.yaml`, the way of referencing these values file could totally differ, like: 
- ` --values repo/chart/custom-values.yaml`
- ` --values chart/custom-values.yaml`


Nonetheless, I am aware that --values can retrieve distant files through an HTTP GET, but it doesn't feel like a smooth flow.

Hope it is clearer.

**Comment by idcmp** [comment]
I too would like this feature. We have a number of different environments, and to simplify the deployment process we include the {dev,test,perf,staging,prod}.yaml files inside the chart. When we do `helm install` we actually do a `helm fetch` first and then explode the .tgz file then run with `helm install -f ${DESIRED_ENV}.yml .....`

I would love to be able to `helm package` everything, then do:

`helm install mychart --version 1.2.3 -f dev.yml`

Where `dev.yml` was already inside the chart.

**Comment by musabmasood** [comment]
+1

**Comment by travishen** [comment]
+1

**Comment by jungopro** [comment]
Hello Everyone
Stumbled upon this issue when trying to do the same...

Is it safe to say that currently, I will have to fetch the chart first and then install from folder?

```console
$ helm fetch mychart --untar
$ helm install -f my-values.yaml .
```

**Comment by edrandall** [comment]
I cannot believe that it is not possible to reference even default values.yaml which are within a packaged chart.

**Comment by bacongobbler** [comment]
You shouldn’t need to reference the default values. They’re used with a `helm install`... hence why they’re called “default”. 😉 why would you need to reference that?

We’re open to community contributions. Please feel free to open a pull request.

**Comment by edrandall** [comment]
> You shouldn’t need to reference the default values. They’re used with a `helm install`... hence why they’re called “default”. 😉 why would you need to reference that?

Thankyou for clearing up my misunderstanding.
Given then that Helm is well able to pick up "values.yaml" from within the packaged chart.tgz, it seems strange that it's unable to detect values-myenv.yaml, also within the same packaged chart.tgz.  I have to write additional script which explodes that to a temporary dir before that --values can work, like this:
`
workDir = 'tmp.work'
os.makedirs(workDir, mode=0o755)
chartUrl = 'https://my.repo.server/path/mychart-1.2.3.tgz'
chartNameVersion = chartUrl.rsplit('/',1)[-1]
chartName = chartNameVersion.rsplit('-',1)[0]
chartDir = os.path.join(workDir, chartName)
values = 'values-myenv.yaml'
valuesFile = os.path.join(chartDir, values)
deploymentName = chartName +'-myenv'

helm pull --untar --untardir {workDir} {chartUrl}
helm upgrade {deploymentName } {chartDir} --install --values {valuesFile } 
`

Wouldn't it be nicer if I didn't have to do all that unpacking and path hacking just to reference my values?

**Comment by michelefa1988** [comment]
Bumped into the same issue. I agree this is a massive big piece of functionality which is missing. 

In my case the flow is I have a common helm chart
 -> A common helm chart values-common.yaml which can be consumed by 1 to many services
-> A values-service.yaml which is configured based on application values
-> A values-user.yaml which can be overridden by the user

I would would like to bundle the values-common.yaml and values-service.yaml inside the helm chart and be able to call both values without extracting etc. This is basic functionality..

**Comment by fadeyev** [comment]
+1
Also need this. It would solve environment overrides nicely.

**Comment by edrandall** [comment]
freshen

**Comment by edrandall** [comment]
<rant>This github-actions bot really is the bane of a developer's life.   Just because an issue has not had attention, does not mean it has gone away!   Who will rid us of this turbulent bot?!</rant>

**Comment by StefanBratanov** [comment]
Hey, bump. Got the same problem. Has this been looked at? Want to reference a values file in the .tgz chart but currently untar and then referencing is the only way.

**Comment by wolf-michl** [comment]
Is therew a solution for this? I would also need this feature.

**Comment by smallbutstrong** [comment]
+1
