### ISSUE TITLE
Wait for old pods to be removed / unaccessible

### ISSUE THREAD

**Issue by sta-szek** [helm/helm#4279]
Hi, 
is there any way to tell helm, that it should wait for old pods to be removed?

My case is:
1. Deploy using `helm upgrade --install --wait ...`
2. Helm waits for new pods
3. After it finish I perform smoke tests => get error due to old pod was not removed yet and traffic was redirected to it.

What I want to achieve:
Before helm finished deployment, make sure that old pod is not accessible, here are few ways to achieve that:
* wait until old pods are removed completely -- it may fail sometimes -- I experienced issues with deleting pods from k8s -- they got stuck somehow and deletion took few hours or we had to delete it by hand (dig into k8s), however Pod was in Terminating state
* wait until old pods are not in Ready state -- ~are we sure that they have been "unregistered" from Service?~ (https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods)
* wait until Service contains endpoint to new Pods only

In addition to have some back gateway I would suggest to add additional flag with timeout if all previous steps will fail.

E.g. solution:
* `helm upgrade --install --ensure-old-pods-removed` -- this actually can do the same as `helm upgrade --install --wait` but with additional step that I proposed.
* `helm upgrade --install --ensure-old-pods-removed --ensure-old-pod-removed-timeout=20` -- the same as above + wait 20s if we cannot ensure because of some reason

**Comment by jwietek** [comment]
Hi, such kind of feature would be very helpful. It would allow synchronize (full) deployment with following it automatic tests.

**Comment by mangirdas77** [comment]
Yes, it would help a lot with automation (pipelines).

**Comment by axsy** [comment]
Same here, checking the version of deployment application in smoke test does not guarantee the pass because `helm --wait` keeps the pipeline blocked until `maxUnavailable` is ready and the pods from old replicaset are still in action.

**Comment by bacongobbler** [comment]
closing as inactive.
