### ISSUE TITLE
--tiller-image support load local image directly

### ISSUE THREAD

**Issue by daixiang0** [helm/helm#4283]
Helm is a very good tool to manage components for k8s.
When install, i think it could be better if --tiller-image can support  load local image directly, just as below:
```
helm init --tiller-image /path/to/tiller-image
```

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-18T23:58:35Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by bacongobbler** [comment]
hey @daixiang0, how are docker images stored on disk? I didn't think this was possible unless it was an OCI image. Even then, `helm init` just renders a Kubernetes manifest and essentially performs a `kubectl apply`, so I don't think feature request could be reasonably tackled unless `kubectl` allowed "uploading" a local image to the cluster.

**Comment by bacongobbler** [comment]
Still marking this as a feature, but I don't think this is something we can reasonably support. Sorry!

**Comment by daixiang0** [comment]
Thanks.
My thought is that for a k8s cluster which can not connect to internet, download tiller image from usb to disk then install. Since use helm to install harbor could be better, so --tiller-image support load local image directly may be cool.

**Comment by stp-bsh** [comment]
Any news on this one?

**Comment by bridgetkromhout** [comment]
Hi, @daixiang0 - Thank you again for this feature suggestion. Helm 3 no longer has Tiller, and we are in bugfix-only mode for Helm 2. So I will close this issue, as we will not be implementing this feature request for `--tiller-image`. Thanks for your interest, and I hope that a migration to Helm 3 works well for you: https://helm.sh/docs/topics/v2_v3_migration/ - please open a new issue if you have questions about Helm 3.
