### ISSUE TITLE
Option to skip chart deployment that resides in charts/

### ISSUE THREAD

**Issue by gintautassulskus** [helm/helm#4287]
Is there a way to skip chart deployment that resides in charts/ similar to `condition:` in requirements.yaml?

**Comment by bacongobbler** [comment]
Hey! I'm not quite sure I fully understand the question. By setting a condition to `false` in your values, [those charts are not loaded and deployed](https://docs.helm.sh/developing_charts/#tags-and-condition-fields-in-requirements-yaml). If that is not what you're looking for, could you explain your use case a little more? Thanks!

**Comment by gintautassulskus** [comment]
Many thanks, @bacongobbler. I thought this works only with charts from remote repos.

**Comment by gintautassulskus** [comment]
@bacongobbler, I think have made a mistake and my question still stands unanswered. Correct me if I am wrong.

I would like to conditionally skip a chart that has been dropped into `charts/` directory as described [here](https://docs.helm.sh/developing_charts/#managing-dependencies-manually-via-the-charts-directory). Not sure how this drop-in can be omitted from deployment.

**Comment by gintautassulskus** [comment]
Ok, I think [rtfm](https://github.com/helm/helm/blob/master/docs/helm/helm_dependency.md#synopsis) can be applied here.
