### ISSUE TITLE
helm install fails with connection timeout

### ISSUE THREAD

**Issue by omyno** [helm/helm#4293]
* Output of `helm version`:
`Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}`
`Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}`

 * Output of `kubectl version`:
 `Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}`

 * Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
 On-Premise, installed via kubeadm with Cilium CNI

Followed the instruction for setting up helm with service acount with cluster-admin role:
```
[...]
kubectl create serviceaccount tiller --namespace kube-system
kubectl create -f rbac-config.yaml
helm init --service-account tiller
helm list
<empty>
```

`helm install stable/kubernetes-dashboard` hangs and exits after some time with the tiller-deploy log saying:

```
[storage/driver] 2018/07/02 06:04:53 create: failed to create: the server was unable to return a response in the time allotted, but may still be processing the request (post configmaps)

[tiller] 2018/07/02 06:04:53 warning: Failed to record release kubernetes-dashboard: the server was unable to return a response in the time allotted, but may still be processing the request (post configmaps)
```

The helm command then stops a few minutes afterwards with:
`warning: Release "kubernetes-dashboard" failed: Get https://10.96.0.1:443/api/v1/namespaces/kube-system: read tcp 10.0.1.130:34744->10.96.0.1:443: read: connection timed out`
10.96.0.1:443 is reachable though.

Then helm does not react anymore (for example when executing `helm list` or `helm version`. The tiller-deploy container needs to be deleted/restarted for helm to react again.

Am I dealing with a RBAC issue?

**Comment by subesokun** [comment]
Same issue here. The Helm timeout is set to 10 minutes as our deployment takes a while but after ~5 minutes the deployment process terminates with a `the server was unable to return a response in the time allotted, but may still be processing the request (get replicasets.extensions)` error. 

I'm guessing this is not the Helm timeout as it would throw the error `timed out waiting for the condition` but instead the k8s request itself times out. Is it possible to increase this timeout as well? With kubectl this could be achieved via `kubectl --request-timeout=600s`.

**Comment by subesokun** [comment]
@omyno What exactly did you change to avoid this MTU issue?

**Comment by omyno** [comment]
Needed to find out the correct MTU size first, then set it the standard way with
`ip link set dev <DEVICE> mtu <NUMBER>`
If using Cilium, you can also use [mtu-update](https://github.com/cilium/mtu-update).

**Comment by subesokun** [comment]
@omyno Thanks a lot for the hint! Unfortunately I can't change the MTU size as we're running on Azure. Would be a good question for the Azure AKS support team...

**Comment by bacongobbler** [comment]
I'm closing this as resolved, but please feel free to re-open if there are further issues. Sorry for not getting back to you!

**Comment by rvgud** [comment]
This might help if anyone facing such issue: -https://medium.com/@ravindrashekhawat5876/helm-tiller-timeout-issue-be5faed6ecea
