### ISSUE TITLE
Feature Request: Allow a chart to override action timeout value

### ISSUE THREAD

**Issue by huang-jy** [helm/helm#4294]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.10-gke.0", GitCommit:"16ebd0de8e0ab2d1ef86d5b16ab1899b624a77cd", GitTreeState:"clean", BuildDate:"2018-03-20T20:21:01Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

This is a sort of a feature request.

For the chart I am working on, I have a long-running hook that generates several disks on GKE prior to the rest of the install kicking in (it's on the pre-install hook) -- however, this hook can take more than the default 5 minutes timeout to complete. I can add the `--timeout` switch to change this, but I would like the chart to be able to say "if you're installing me, make the default timeout to be (e.g.) 10 minutes for any action you take on me" -- meaning for the install, upgrade, and delete on that chart, the timeout (if not explicitly set by the `--timeout` switch) will be 10 minutes.

I cannot find anywhere this can be done other than by the timeout switch. It would be nice to be able to define this in, say `Chart.yaml` or `values.yaml`

This could be implemented as additional annotations on the Job object, e.g. something like this for a hook job to override default timeout (to be added into a job yaml)

```
helm.sh/job-timeout=10m
```

And this to declare a global default timeout (to be added to `Chart.yaml)`
```
helm.sh/chart-default-timeout=5m
```

*OR* call them both the same thing and the timeout from the lowest unit takes priority (e.g. in built tiimeout is overridden by  the timeout in `Chart.yaml` which can then be overridden again by the timeout in the job definition.

**Comment by indiebrain** [comment]
We too have a similar issue as described by @huang-jy. We deploy a Rails app on a local Kuberentes cluster. We run our Rails migrations in a pre-hook. With the size of our database we sometimes exceed our `--timeout` setting - by several 10s of minutes -  when running these migration jobs. Currently we bump the `--timeout` value as a work around, but this has the unintended consequence of prolonging the eventual failure state if, for example, our docker registry is down and subsequent pods fail to pull the image.

Is a feature for which the helm project / community has an appetite to implement an maintain? If so, I'd love to help out any way I can - perhaps even with its implementation once the interface, behavior, and contracts are established.

**Comment by sprutner** [comment]
I was having this issue, and I believe the cause was being very close to the IOPS limit in AWS. I deleted some unused PVCs to give myself some more headroom and it seems to have resolved unmounting and then immediately remounting to another job.

**Comment by huang-jy** [comment]
@sprutner I think that is unrelated to this ticket. This is a feature request, not a bug ticket.

**Comment by huang-jy** [comment]
Nudging this ticket to see if we have any progress on this feature?

**Comment by hickeyma** [comment]
@huang-jy Would you like to create a proposal on solution(s)?

**Comment by huang-jy** [comment]
> @huang-jy Would you like to create a proposal on solution(s)?

Sure, I made some suggestions in the opening post of this issue and this has been tagged as a `feature` since last year, so I'm just wondering if anything has happened since then?

**Comment by hickeyma** [comment]
@huang-jy Looks like no but lots of changes in last year with Helm 3 now GA. Might be a good time to revisit and drive it on if you like?

**Comment by huang-jy** [comment]
Will do.

**Comment by bacongobbler** [comment]
In general terms, we don't usually go out and implement features requested by the community unless we explicitly say we'd like to expedite the feature. If you'd like to see something in Helm, we'd be happy to help you get started so you can implement the feature yourself, and we can help out through the process. :)

For starters: https://helm.sh/docs/community/developers/

**Comment by huang-jy** [comment]
> In general terms, we don't usually go out and implement features requested by the community unless we explicitly say we'd like to expedite the feature. If you'd like to see something in Helm, we'd be happy to help you get started so you can implement the feature yourself, and we can help out through the process. :)
> 
> For starters: https://helm.sh/docs/community/developers/

Well, I'm not that good at Go yet. But at least this gives me a reason to learn it ^_^

**Comment by bacongobbler** [comment]
closing as inactive.

**Comment by sdarwin** [comment]
This comment from @indiebrain exactly describes, not what we are already doing, but definitely what we are planning to do in the near future.  And seems very relevant:

"""
We deploy a Rails app on a local Kubernetes cluster. We run our Rails migrations in a pre-hook. With the size of our database we sometimes exceed our --timeout setting - by several 10s of minutes - when running these migration jobs. Currently we bump the --timeout value as a work around, but this has the unintended consequence of prolonging the eventual failure state if, for example, our docker registry is down and subsequent pods fail to pull the image.
"""

It would be great if timeouts could be set in annotations, Chart.yaml, and/or values.yaml, so they are more customizable.

**Comment by benlangfeld** [comment]
> This comment from @indiebrain exactly describes, not what we are already doing, but definitely what we are planning to do in the near future. And seems very relevant:
> 
> """ We deploy a Rails app on a local Kubernetes cluster. We run our Rails migrations in a pre-hook. With the size of our database we sometimes exceed our --timeout setting - by several 10s of minutes - when running these migration jobs. Currently we bump the --timeout value as a work around, but this has the unintended consequence of prolonging the eventual failure state if, for example, our docker registry is down and subsequent pods fail to pull the image. """
> 
> It would be great if timeouts could be set in annotations, Chart.yaml, and/or values.yaml, so they are more customizable.

For this and other reasons we actually ended up switching from Helm to https://github.com/Shopify/krane for our Rails application deployments.
