### ISSUE TITLE
Empty helm chart is successfully deployed AND returns "Error: no objects visited"

### ISSUE THREAD

**Issue by gintautassulskus** [helm/helm#4295]
I have a chart with a set of conditional dependencies. Under certain circumstances, all of the dependencies may be omitted resulting in an empty chart. 

As expected, this empty chart is successfully deployed but at the very end of the process helm spits out "Error: no objects visited" and my wrapper scripts terminate.

To my understanding Helm should be able to handle empty charts without any errors.

Output of `helm version`: 2.9.1

**Comment by gintautassulskus** [comment]
An update.

This behaviour misleads external tools that the deployment has failed.
For example, it instructs [skaffold](https://github.com/GoogleContainerTools/skaffold) to abort the deployment. The only workaround is to introduce a dummy/filler manifest so that the chart would not be 'empty'.

**Comment by phroiland** [comment]
Do you have an example dummy manifest? It's doing the same thing on Azure.

**Comment by gintautassulskus** [comment]
@phroiland , nothing at hand. First thing that comes to my mind is to deploy a dummy ConfigMap:

```
if 'deploy'
    contents: ....
else 'skip'
    contents: 
       status: skipped
```

**Comment by bacongobbler** [comment]
closing as inactive.
