### ISSUE TITLE
Helm Install fails to download file from github

### ISSUE THREAD

**Issue by justinhauer** [helm/helm#4296]
## Issue and output:
Helm cannot download files from github whether it is in AKS or in my local with Minikube. This is regardless of what file it is. Does github need to be added to the .helm/repositories/repositories.yaml file? Running `helm repo update` does nothing. I am running a fresh install of kubectl, helm, and minikube to try and remove any variance from initial download:

~ helm install --namespace fission --set serviceType=NodePort,routerServiceType=NodePort https://github.com/fission/fission/releases/download/0.8.0/fission-all-0.8.0.tgz
Error: failed to download "https://github.com/fission/fission/releases/download/0.8.0/fission-all-0.8.0.tgz" (hint: running `helm repo update` may help)

## Output of `helm version`:
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

## Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:29:25Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

## Cloud Provider/Platform (AKS, GKE, Minikube etc.):  
AKS and Minikube

**Comment by bacongobbler** [comment]
I did not hit this error:

```
PS C:\Users\mafishe> helm install --namespace fission --set serviceType=NodePort,routerServiceType=NodePort https://github.com/fission/fission/releases/download/0.8.0/fission-all-0.8.0.tgz
NAME:   xrayed-frog
LAST DEPLOYED: Mon Jul  9 09:50:09 2018
NAMESPACE: fission
STATUS: DEPLOYED
```

Perhaps it's a networking error on your end where it cannot download the tarball?

**Comment by suanyi001** [comment]
Have you solved this problem?I have the same problem!!

**Comment by justinhauer** [comment]
I honestly gave up on fission. The whole thing was way too buggy when I was trying it out to ever make it to a production application. You could try openFAAS and see how that one is now, I hear its good. Otherwise AWS lambda is amazing and Azure functions have improved somewhat.
