### ISSUE TITLE
helm dependency build doesn't respect repo credentials

### ISSUE THREAD

**Issue by subesokun** [helm/helm#4299]
I've setup a private Helm repository via the Chartmuseum and enabled Basic Authentication on it. Adding that repo via `helm repo add myrepo https://myrepo.com --username=user --password=pass` worked as expected and I was able to run `helm repo update`. But when I try to build my dependencies via `helm dependency build .` the command exists with a `401 Unauthorized` error when trying to download the `tar.gz` artefacts from the repository.  It seems like the credentials which have been passed in during `helm repo add` are not getting used when downloading the artefacts from the repository.

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:29:25Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  Not relevant

**Comment by bacongobbler** [comment]
cc @eyalbe4

**Comment by steven-sheehy** [comment]
``helm dependency update`` is also affected.

**Comment by bacongobbler** [comment]
Not sure why I labeled this as a feature 😆 fixed the label.

**Comment by agolomoodysaada** [comment]
Also experiencing this...

**Comment by PhiSDev** [comment]
Same here

**Comment by bartvanhoutte** [comment]
+1

**Comment by calebdelnay** [comment]
This issue is blocking a new CI process I'm working on. I'm not a Go developer and I'm not setup for contributions to Helm but I did fix this locally using my own build of Helm. The bug is that there is a path of logic through `ResolveChartVersion()` that results in the credentials not being set.

Here is a patch:
```patch
diff --git a/pkg/downloader/chart_downloader.go b/pkg/downloader/chart_downloader.go
index 92c8f916..5e628729 100644
--- a/pkg/downloader/chart_downloader.go
+++ b/pkg/downloader/chart_downloader.go
@@ -170,8 +170,11 @@ func (c *ChartDownloader) ResolveChartVersion(ref, version string) (*url.URL, ge
                                if err != nil {
                                        return u, nil, err
                                }
-                               getter, err := getterConstructor(ref, "", "", "")
-                               return u, getter, err
+                               g, err := getterConstructor(ref, "", "", "")
+                               if t, ok := g.(*getter.HttpGetter); ok {
+                                       t.SetCredentials(c.Username, c.Password)
+                               }
+                               return u, g, err
                        }
                        return u, nil, err
                }
```

Not sure if that's the best solution but it works. I didn't update any tests.

**Comment by subesokun** [comment]
@bacongobbler Any plans to add the patch from @calebdelnay (or similar)? I'd like to avoid maintaining my own variant of Helm :/

**Comment by steven-sheehy** [comment]
@calebdelnay Why not open a PR with this fix? I'm sure you'll get review feedback if it's not the correct approach or tests are needed.
