### ISSUE TITLE
enable helm to query configmap object to select values.yaml path

### ISSUE THREAD

**Issue by nkkashyap** [helm/helm#4306]
Output of `helm version`:

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

We have a usecase where we are storing the K8S cluster region label in a configmap object. 
Now, I want to maintain multiple `values.yaml`, one for each region. For this, I want to create multiple subfolders and keep a `values.yaml` under a subfolder. 
Depending on the value of the region key in configmap, I want helm to pick a value file from a specific subfolder.

I am aware of the solution like
1. Using `kubectl` fetch Configmap key value 
2. `helm install --values ${subfolder}/values.yaml ...`

Is it possible that helm can query the confimap object and pick the values.yaml?   
If this is not possible can this be taken as new feature request?

**Comment by bacongobbler** [comment]
It might not be useful as a core feature, but it'd probably be a neat plugin! https://docs.helm.sh/using_helm/#the-helm-plugins-guide

If the community thinks it's a good project to move to core then we can discuss it. Generally we're trying to keep new features in Helm 2's core to a minimum.

**Comment by nkkashyap** [comment]
@bacongobbler Thanks
I have implemented a helm-plugin for desired functionality and it is working perfectly for my use case.

**Comment by edwardstudy** [comment]
@nashasha1 Hi. Could you please give me your plugin link? I just wanna the same requirement.
