### ISSUE TITLE
Mark a particular version of Chart as deprecated 

### ISSUE THREAD

**Issue by irajdeep** [helm/helm#4309]
The current deprecating strategy marks the entire chart as deprecated. 
Would be nice if there was an option to mark a particular version of the helm chart as deprecated

**Comment by prydonius** [comment]
I'm curious what the usecase for deprecating a particular chart version would be, and why simply publishing a newer version isn't enough?

**Comment by irajdeep** [comment]
Okay, so we have application chart(s) which have dependency on few sub-charts. 
The sub-charts undergo changes and new versions are released every time and people need to bump the version of the sub-charts in the `requirements.yaml` (application chart).

At times developers forget to bump the version of the subcharts in requirements and continue to use the older versions. We would like to throw a warning when they are still using an old sub-chart version which has been marked deprecated.

**Comment by prydonius** [comment]
@irajdeep interesting, I'm not actually sure if Helm will complain if a particular chart in requirements.yaml is deprecated. @bacongobbler what do you think about this?

**Comment by bacongobbler** [comment]
all for it.

Similar ask for pypa: https://github.com/pypa/warehouse/issues/345
npm package for marking npm packages as deprecated: https://docs.npmjs.com/cli/deprecate
bit of a deeper dive on the sematics of deprecating packages vs. un-publishing packages (for VSTS, but applies to package managers in general): https://docs.microsoft.com/en-us/vsts/package/npm/deprecate-unpublish

**Comment by prydonius** [comment]
@bacongobbler the npm example is interesting, I wonder if it makes sense to extend the deprecation metadata in Helm 3 to support version ranges.

**Comment by bacongobbler** [comment]
cc @jdolitsky

**Comment by brainwane** [comment]
Hi all! [Yanking is now supported on PyPI](https://pypi.org/help/#yanked) (see https://github.com/pypa/warehouse/issues/5837 ) -- does that help?

**Comment by brainwane** [comment]
Consider reopening:

>  [Yanking is now supported on PyPI](https://pypi.org/help/#yanked) (see [pypa/warehouse#5837](https://github.com/pypa/warehouse/issues/5837) ) -- does that help?

**Comment by harryttd** [comment]
A use case I have is transferring a Helm chart repo from one org on Github to another. There are old releases that reference the old org and hence the versions don't exist anymore. Deprecating them would make clear to users that they need to use the new versions existing in the new chart's org's repo.
