### ISSUE TITLE
Prefixing services with release name

### ISSUE THREAD

**Issue by ryandawsonuk** [helm/helm#4318]
A fixed name for a chart resource is regarded as bad practice according to https://docs.helm.sh/chart_template_guide/ But what about a parameterised name like resource.name that can be set in the values.yaml? For the service in particular it can be useful to control this to make discovery simpler for microservices applications where services need to talk to one another (see e.g. https://github.com/jenkins-x/draft-packs/pull/37). I wonder if there's value in defaulting to prefixing with release name and also allowing an override so that the chart consumer can fix a name (and does so at their own risk). I'm wondering if it might be helpful to have a small section in the best practices or developer guide on this.

**Comment by sgandon** [comment]
indeed we have decided to use fixed service names for service that are shared by multiple application so that each Microservices can leverage the K8s service discovery through DNS resolution.
You can also see that many official charts are using a pattern to override the chart name using a *fullnameOverride* value.
https://github.com/helm/charts/blob/cbd5e811a44c7bac6226b019f1d1810ef5ee45fa/incubator/zookeeper/templates/_helpers.tpl#L15
We are using a value called *service.prefixWithHelmRelease* to switch on/off the fixed service name feature.

**Comment by sgandon** [comment]
You proposal makes it impossible to change the name of a service (coming from a third party chart fro instance) and keep the release prefix.

**Comment by ryandawsonuk** [comment]
Happy to help clarify this further if I can @sgandon but not sure I'm following what you have in mind.

**Comment by sgandon** [comment]
I am just saying that if you use this template
```
 apiVersion: v1
 kind: Service
 metadata:
   {{- if .Values.service.name }}
     name: {{ .Values.service.name }}
   {{- else }}
     name: {{ template "fullname" . }}
   {{- end }}
 ```
there is not way to change the service name and keep the helm release prefix for the service. It is either a "custom service name" (.Values.service.name) or the "helm release + chart name" (template "fullname" .). You do not provide the possibility to have "helm release + custom service name".

**Comment by ryandawsonuk** [comment]
Yeah I'd assumed that there was only a single service in the chart as then the [chart name tends to be used for the service name](https://github.com/helm/charts/blob/master/stable/rabbitmq-ha/templates/service.yaml#L8). If there were multiple services then the chart name alone wouldn't be unique and [an additional specific name](https://github.com/helm/charts/blob/71137594371771481dc4ee36fdc5275e60a06077/stable/spinnaker/templates/services/halyard.yaml#L4) would [need to be added to it](https://github.com/helm/charts/blob/master/stable/keycloak/templates/http-service.yaml#L5). That specific name when it is used t[ends to be hard-coded](https://github.com/helm/charts/blob/cbd5e811a44c7bac6226b019f1d1810ef5ee45fa/stable/distributed-tensorflow/templates/service-worker.yaml#L4) but it could be made configurable. Possibly the docs could mention ways to handle naming of resources, especially multiple resources of the same type.
