### ISSUE TITLE
tiller-namespace is doing a shallow string search

### ISSUE THREAD

**Issue by gkarthiks** [helm/helm#4322]
Output of `helm version`:
**Client**: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
**Server**: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}

Output of `kubectl version`:
**Client Version**: v1.10.0
**Server Version**: v1.9.1+a0ce1bc657

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
OpenShift

### What's happening 
When I run `helm list ` with `--tiller-namespace` flag, it just lists what ever namespace is matching the current string that I passed.  Example of the `helm list --tiller-namespace ads` is shown below.

![image](https://user-images.githubusercontent.com/30545166/42476226-19f9ceb0-8382-11e8-8a14-738e53184893.png)

### What I expect?

When I run the `helm list --tiller-namespace ads` command, only the helm installations in the `ads` namespace should be listed not `blk-ads-atp`.

**Comment by technosophos** [comment]
If you set `--tiller-namespace ads`, it will contact the Tiller instance in the namespace `ads` and get all of the releases for that Tiller instance. If you do `--namespace ads`, it will show only the releases in the namespace `ads`. So if you run `helm list --namespace ads`, it should do what you want.

**Comment by gkarthiks** [comment]
@technosophos  That's right. But I have `tiller` server on every namespace and isn't the tiller in this `ads` namespace should be giving only deployments deployed via this tiller?

**Comment by bacongobbler** [comment]
yes, and that's what looks like what the output is showing. If you look at `kubectl -n ads get configmaps`, you should see all of the releases managed by the tiller instance running in namespace `ads`.
