### ISSUE TITLE
Cannot perform helm init behind proxy

### ISSUE THREAD

**Issue by ptylenda** [helm/helm#4326]
Output of `helm version`: v2.10.0-rc.1 (https://github.com/kubernetes/helm/releases/tag/v2.10.0-rc.1)

Output of `kubectl version`: v1.11.0

Cloud Provider/Platform (AKS, GKE, Minikube etc.): bare metal

Description:
When checking the latest RC version (https://github.com/kubernetes/helm/releases/tag/v2.10.0-rc.1) I am unable to perform "helm init" behind proxy:
```
$ ./helm init --node-selectors "beta.kubernetes.io/os"=linux
Creating /home/ubuntu/.helm
Creating /home/ubuntu/.helm/repository
Creating /home/ubuntu/.helm/repository/cache
Creating /home/ubuntu/.helm/repository/local
Creating /home/ubuntu/.helm/plugins
Creating /home/ubuntu/.helm/starters
Creating /home/ubuntu/.helm/cache/archive
Creating /home/ubuntu/.helm/repository/repositories.yaml
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com
Error: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Get https://kubernetes-charts.storage.googleapis.com/index.yaml: dial tcp 216.58.214.80:443: connect: connection timed out
```

My environment is set properly for proxy:
```
$ export
...
declare -x HTTPS_PROXY="http://some-proxy:1234"
declare -x HTTP_PROXY="http://some-proxy:1234"
...
declare -x http_proxy="http://some-proxy:1234"
declare -x https_proxy="http://some-proxy:1234"
```

And downgrading to latest stable release v2.9.1 (https://github.com/kubernetes/helm/releases/tag/v2.9.1) solves the issue:
```
$ ./helm init --node-selectors "beta.kubernetes.io/os"=linux
Creating /home/ubuntu/.helm/repository/repositories.yaml
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com
Adding local repo with URL: http://127.0.0.1:8879/charts
$HELM_HOME has been configured at /home/ubuntu/.helm.

Tiller (the Helm server-side component) has been installed into your Kubernetes Cluster.

Please note: by default, Tiller is deployed with an insecure 'allow unauthenticated users' policy.
For more information on securing your installation see: https://docs.helm.sh/using_helm/#securing-your-helm-installation
Happy Helming!
```

**Comment by bacongobbler** [comment]
I was unable to reproduce using both v2.9.1 and v2.10.0-rc1. I provisioned a squid proxy server to proxy my local network traffic, and in both cases I was able to perform `helm init` behind the proxy.

```
><> env | grep proxy
http_proxy=http://xx.xx.xxx.xxx:3128
```

helm 2.9.1 output:

```
><> rm -rf ~/.helm/
><> helm init
Creating /Users/bacongobbler/.helm
Creating /Users/bacongobbler/.helm/repository
Creating /Users/bacongobbler/.helm/repository/cache
Creating /Users/bacongobbler/.helm/repository/local
Creating /Users/bacongobbler/.helm/plugins
Creating /Users/bacongobbler/.helm/starters
Creating /Users/bacongobbler/.helm/cache/archive
Creating /Users/bacongobbler/.helm/repository/repositories.yaml
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com
Adding local repo with URL: http://127.0.0.1:8879/charts
$HELM_HOME has been configured at /Users/bacongobbler/.helm.
Warning: Tiller is already installed in the cluster.
(Use --client-only to suppress this message, or --upgrade to upgrade Tiller to the current version.)
Happy Helming!
```

helm 2.10.0-rc1 output:

```
><> wget https://storage.googleapis.com/kubernetes-helm/helm-v2.10.0-rc.1-darwin-amd64.tar.gz
--2018-07-30 09:49:17--  https://storage.googleapis.com/kubernetes-helm/helm-v2.10.0-rc.1-darwin-amd64.tar.gz
Resolving storage.googleapis.com (storage.googleapis.com)... 216.58.217.48
Connecting to storage.googleapis.com (storage.googleapis.com)|216.58.217.48|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9708198 (9.3M) [application/x-tar]
Saving to: ‘helm-v2.10.0-rc.1-darwin-amd64.tar.gz’

helm-v2.10.0-rc.1-darwin-amd64.tar.gz                      100%[=======================================================================================================================================>]   9.26M  11.9MB/s    in 0.8s

2018-07-30 09:49:18 (11.9 MB/s) - ‘helm-v2.10.0-rc.1-darwin-amd64.tar.gz’ saved [9708198/9708198]

><> tar xzf helm-v2.10.0-rc.1-darwin-amd64.tar.gz
><> rm -rf ~/.helm/
><> ./darwin-amd64/helm init
Creating /Users/bacongobbler/.helm
Creating /Users/bacongobbler/.helm/repository
Creating /Users/bacongobbler/.helm/repository/cache
Creating /Users/bacongobbler/.helm/repository/local
Creating /Users/bacongobbler/.helm/plugins
Creating /Users/bacongobbler/.helm/starters
Creating /Users/bacongobbler/.helm/cache/archive
Creating /Users/bacongobbler/.helm/repository/repositories.yaml
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com
Adding local repo with URL: http://127.0.0.1:8879/charts
$HELM_HOME has been configured at /Users/bacongobbler/.helm.
Warning: Tiller is already installed in the cluster.
(Use --client-only to suppress this message, or --upgrade to upgrade Tiller to the current version.)
Happy Helming!
```

Because of this I'm going to remove it from the 2.10 list, but if you can provide more information to identify the cause of the issue that'd be great. Thanks!

**Comment by chrzhang727** [comment]
Hi, 

I met the same issue in ubuntu. the helm version is  v2.10.0-rc.2. the older helm versions also have the same issue.  
I set proxy in the env, but for specific application, it also needs proxy setting. wget can works, as I set proxy in the ./wgetrc  

helm init
Creating /root/.helm 
Creating /root/.helm/repository 
Creating /root/.helm/repository/cache 
Creating /root/.helm/repository/local 
Creating /root/.helm/plugins 
Creating /root/.helm/starters 
Creating /root/.helm/cache/archive 
Creating /root/.helm/repository/repositories.yaml 
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com 
Error: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Get https://kubernetes-charts.storage.googleapis.com/index.yaml: dial tcp 172.217.194.128:443: connect: connection timed out


$ env |grep http_proxy
http_proxy=http://xxxxxxx:8080/

$ wget https://kubernetes-charts.storage.googleapis.com/index.yaml
--2018-08-01 10:58:33--  https://kubernetes-charts.storage.googleapis.com/index.yaml
Connecting to 10.144.1.10:8080... connected.
Proxy request sent, awaiting response... 200 OK
Length: 2287613 (2.2M) [application/octet-stream]
Saving to: ‘index.yaml’

index.yaml                            100%[========================================================================>]   2.18M   212KB/s    in 12s     

2018-08-01 10:58:46 (186 KB/s) - ‘index.yaml’ saved [2287613/2287613]

**Comment by basvandenbrink** [comment]
I can confirm the issue with version 2.10.0-rc.2. I had to revert to v2.9.1.

**Comment by bacongobbler** [comment]
If you can provide some steps to reproduce the bug or a patch, that would be very helpful. Thanks!

**Comment by davidkarlsen** [comment]
Same here - but in my case the proxy problem (it does not use it) is when I am attempting to add a repository. I set https_proxy and HTTPS_PROXY and attempt to add:
```
helm repo add kubernetes-charts-incubator https://kubernetes-charts-incubator.storage.googleapis.com/
```

**Comment by floriantraber** [comment]
The following Dockerfile fails for us. Using `v2.9.1` works. 
```
FROM jenkins/jenkins:2.138

USER root 

ENV http_proxy=http://internet:80 \
    https_proxy=http://internet:80 \
    HTTP_PROXY=http://internet:80 \
    HTTPS_PROXY=http://internet:80

ADD "https://storage.googleapis.com/kubernetes-helm/helm-v2.10.0-linux-amd64.tar.gz"  /tmp/helm.tar.gz

RUN cd /tmp && \
    tar -xvzf "helm.tar.gz" && \ 
    cp -a "/tmp/linux-amd64/helm" /bin/ && \
    rm /tmp/* -r

USER jenkins 

# fails here!
RUN helm init --client-only
```

**Comment by Hokwang** [comment]
I have same problem.

I can helm init but can not repo update and install


# helm init --service-account tiller --upgrade
$HELM_HOME has been configured at /root/.helm.

Tiller (the Helm server-side component) has been installed into your Kubernetes Cluster.

Please note: by default, Tiller is deployed with an insecure 'allow unauthenticated users' policy.
To prevent this, run `helm init` with the --tiller-tls-verify flag.
For more information on securing your installation see: https://docs.helm.sh/using_helm/#securing-your-helm-installation
Happy Helming!

# helm version
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}

# helm repo list
NAME  	URL                                             
stable	https://kubernetes-charts.storage.googleapis.com
local 	http://127.0.0.1:8879/charts

# helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Unable to get an update from the "stable" chart repository (https://kubernetes-charts.storage.googleapis.com):
	Get https://kubernetes-charts.storage.googleapis.com/index.yaml: dial tcp 216.58.199.16:443: connect: connection timed out
Update Complete. \u2388 Happy Helming!\u2388

# helm install --name jenkins -f jenkins-values.yaml stable/jenkins --namespace jenkins
Error: failed to download "stable/jenkins" (hint: running `helm repo update` may help)

**Comment by Morl99** [comment]
I have the same problem, my setup

MacOS X 10.13.6
Helm v2.10.0 (installed with homebrew)

http_proxy und https_proxy are set to http://localhost:3128 where I have a working cntlm running
`curl https://kubernetes-charts.storage.googleapis.com` works fine, but
`helm init --client-only` fails with
```helm init --client-only
Creating /Users/carstenchoffmann/.helm/repository/repositories.yaml
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com
Error: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Get https://kubernetes-charts.storage.googleapis.com/index.yaml: dial tcp: lookup kubernetes-charts.storage.googleapis.com: no such host```

Let me know if you need more information.

**Comment by stephan2012** [comment]
Problem still exists for 2.10.0:

```
# http_proxy=http://proxy.company.com:3128 https_proxy=http://proxy.company.com:3128 no_proxy=localhost,127.0.0.1,.int.company.com /usr/local/sbin/helm init --service-account tiller
Creating /root/.helm 
Creating /root/.helm/repository 
Creating /root/.helm/repository/cache 
Creating /root/.helm/repository/local 
Creating /root/.helm/plugins 
Creating /root/.helm/starters 
Creating /root/.helm/cache/archive 
Creating /root/.helm/repository/repositories.yaml 
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com 
Error: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Get https://kubernetes-charts.storage.googleapis.com/index.yaml: dial tcp 172.217.19.208:443: connect: connection timed out
```

No issues for 2.9.1:

```
# http_proxy=http://proxy.company.com:3128 https_proxy=http://proxy.company.com:3128 no_proxy=localhost,127.0.0.1,.int.company.com /usr/local/sbin/helm init --service-account tiller
Creating /root/.helm 
Creating /root/.helm/repository 
Creating /root/.helm/repository/cache 
Creating /root/.helm/repository/local 
Creating /root/.helm/plugins 
Creating /root/.helm/starters 
Creating /root/.helm/cache/archive 
Creating /root/.helm/repository/repositories.yaml 
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com 
Adding local repo with URL: http://127.0.0.1:8879/charts 
$HELM_HOME has been configured at /root/.helm.

Tiller (the Helm server-side component) has been installed into your Kubernetes Cluster.

Please note: by default, Tiller is deployed with an insecure 'allow unauthenticated users' policy.
For more information on securing your installation see: https://docs.helm.sh/using_helm/#securing-your-helm-installation
Happy Helming!
```

**Comment by danielballan** [comment]
I get exactly the same results as @stephan2012.

> If you can provide some steps to reproduce the bug or a patch, that would be very helpful. Thanks!

I'm a helm newcomer, but if you have time to suggest what commands might produce useful debugging information, I'd be happy to run them. :- )

**Comment by neocy** [comment]
Helm v2.10.0 got the same error even use like http_proxy=http://proxy.company.com:3128 https_proxy=http://proxy.company.com:3128 ...
revert to helm-v2.9.1, problem resolved.

**Comment by kfox1111** [comment]
I'm seeing it on helm init -c also.

**Comment by bacongobbler** [comment]
All right so I'll be the first to state that it's quite likely my test did not work as intended, however I'm not sure how to reproduce the bug at this point, given my lack of experience working with them.

We'd love for someone from the community more familiar with proxy settings to take a look into this if possible.

**Comment by Morl99** [comment]
@bacongobbler it is likely, that helm simply connected directly with the internet and ignored the proxy settings. In a real corporate environment, this is not possible, and though it fails.

I am not sure on how to reproduce this without the real need for a proxy. But I am happy to try anything you like on my machine with the problematic Helm version on it. I just need directions on which logs to capture... 

maybe it would also make sense to scan the diff between the two versions, maybe the error is obvious for somebody familiar with the codebase?

**Comment by kfox1111** [comment]
got a link to the test?

**Comment by bacongobbler** [comment]
Did a test, wasn't representative. See my earlier comment: https://github.com/helm/helm/issues/4326#issuecomment-408934503

**Comment by kfox1111** [comment]
oh. one more data point. this was on a centos7 machine. Could be affecting only Linux.

**Comment by Kyrremann** [comment]
Can confirm something is strange with `2.10.0`, and I'm also behind corporate proxy. From both images I can `curl https://nais.io/charts/`. So connection out isn't the problem directly.

With the first image, I had to `ctrl+c` out, as it couldn't contact Tiller.
```
bash-4.4# helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
^C
bash-4.4# helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "nais" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈
```

Here you can see that it just stops Tiller connection at once.
```
bash-4.4# helm version
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Error: Get http://localhost:8080/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: dial tcp 127.0.0.1:8080: connect: connection refused
bash-4.4# helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Unable to get an update from the "stable" chart repository (https://kubernetes-charts.storage.googleapis.com):
	Get https://kubernetes-charts.storage.googleapis.com/index.yaml: dial tcp 216.58.211.144:443: connect: connection refused
...Unable to get an update from the "nais" chart repository (https://nais.github.io/charts):
	Get https://nais.github.io/charts/index.yaml: dial tcp 185.199.110.153:443: connect: connection refused
Update Complete. ⎈ Happy Helming!⎈
```

**Comment by Kyrremann** [comment]
I found a solution! Adding the repo with out self-signed certificate fixed the issue.

```
bash-4.4# helm repo add --ca-file=/usr/local/share/ca-certificates/webproxy.nav.no.cer nais https://nais.github.io/charts
"nais" has been added to your repositories
bash-4.4# helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Unable to get an update from the "stable" chart repository (https://kubernetes-charts.storage.googleapis.com):
	Get https://kubernetes-charts.storage.googleapis.com/index.yaml: dial tcp 216.58.211.144:443: connect: connection refused
...Successfully got an update from the "nais" chart repository
Update Complete. ⎈ Happy Helming!⎈
bash-4.4# helm repo add --ca-file=/usr/local/share/ca-certificates/webproxy.nav.no.cer stable https://kubernetes-charts.storage.googleapis.com
"stable" has been added to your repositories
bash-4.4# helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "nais" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈ 
```

**Comment by bacongobbler** [comment]
For those hitting this issue, can you try the following and paste their output?

```bash
helm init --skip-refresh
helm list
helm repo add foo https://kubernetes-charts.storage.googleapis.com --debug
```

It looks like the regression occurs when refreshing the stable chart. I threw in `helm list` in there just to make sure that it's only when interacting with repositories.

**Comment by sunnychanwork** [comment]
$ helm init --skip-refresh
Creating /home/xxxxxx/.helm/repository/repositories.yaml
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com
Adding local repo with URL: http://127.0.0.1:8879/charts
$HELM_HOME has been configured at /home/xxxxxx/.helm.

Tiller (the Helm server-side component) has been installed into your Kubernetes Cluster.

Please note: by default, Tiller is deployed with an insecure 'allow unauthenticated users' policy.
To prevent this, run `helm init` with the --tiller-tls-verify flag.
For more information on securing your installation see: https://docs.helm.sh/using_helm/#securing-your-helm-installation
Happy Helming!
$ helm list
Error: configmaps is forbidden: User "system:serviceaccount:kube-system:default" cannot list configmaps in the namespace "kube-system"
$ helm repo add foo https://kubernetes-charts.storage.googleapis.com --debug
Error: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Get https://kubernetes-charts.storage.googleapis.com/index.yaml: dial tcp 172.217.24.208:443: connect: connection refused

Notice that our corp policy prevent any direct http connection to the internet, and all web traffic must be directed to the proxy. However it seems that helm repo command doesn't respect the proxy settings.

**Comment by Kyrremann** [comment]
@bacongobbler is this what you wanted?
```
bash-4.2$ sudo docker run --rm -it navikt/naiscaper:11.0.0 bash
bash-4.4# helm init --skip-refresh
$HELM_HOME has been configured at /root/.helm.
Error: error installing: Post http://localhost:8080/apis/extensions/v1beta1/namespaces/kube-system/deployments: dial tcp 127.0.0.1:8080: connect: connection refused
bash-4.4# helm list
Error: Get http://localhost:8080/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: dial tcp 127.0.0.1:8080: connect: connection refused
bash-4.4# helm repo add foo https://kubernetes-charts.storage.googleapis.com --debug
Error: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Get https://kubernetes-charts.storage.googleapis.com/index.yaml: dial tcp 216.58.207.240:443: connect: connection refused
```

**Comment by basvandenbrink** [comment]
Here is the output of running the commands on our cluster:

```
~> helm init --skip-refresh --upgrade
$HELM_HOME has been configured at /home/bas/.helm.

Tiller (the Helm server-side component) has been upgraded to the current version.
Happy Helming!
~> helm list
~> helm repo add foo https://kubernetes-charts.storage.googleapis.com --debug
Error: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Get https://kubernetes-charts.storage.googleapis.com/index.yaml: dial tcp: lookup kubernetes-charts.storage.googleapis.com on <INTERNAL_DNS_IP>:53 no such host
```

Note that I added `--upgrade`. I deployed an older version using Kubespray to let Kubespray setup RBAC (otherwise I get permission errors).

As you can see, `helm list` doesn't have output.

**Comment by derkoe** [comment]
Could this be the reason: bf7e755ef39c436e16681df97334d67c6a63cfa3 - seems to be the only proxy-related change between v2.9.1 and v2.10.0?

**Comment by derkoe** [comment]
Create PR #4579 which should fix this.

**Comment by Kyrremann** [comment]
Yeah, I did that in my Dockerfile.

**Comment by marchowarth** [comment]
For reference, with 2.9.1 my Dockerfile contained:
`RUN helm init --client-only --wait`
With 2.10.0 the workaround is:
```
RUN helm init --client-only --skip-refresh --wait
 && helm repo remove stable
 && helm repo add --ca-file=/etc/ssl/certs/ca-bundle.crt stable https://kubernetes-charts.storage.googleapis.com
 && helm repo update
```

**Comment by andrewshilliday** [comment]
@marchowarth's workaround works for me.  Thanks!

**Comment by qiangli** [comment]
@marchowarth's workaround also worked for me on MacOS. Assuming you have openssl installed, add the repo as follows:
helm repo add --ca-file=/usr/local/etc/openssl/cert.pem stable https://kubernetes-charts.storage.googleapis.com

**Comment by bacongobbler** [comment]
If anyone would be willing to try the v2.11.0-rc.2 release candidates for the fix, that would also be appreciated (and should not require the workaround). :)

**Comment by floriantraber** [comment]
I can confirm that v2.11.0-rc.2 works with the configuration at https://github.com/helm/helm/issues/4326#issuecomment-414351744

**Comment by ptylenda** [comment]
@bacongobbler, yes I also confirm that my original configuration works on v2.11.0-rc.2 properly, thanks a lot!

**Comment by vallard** [comment]
works great for me too.  Thanks for the fix!

**Comment by qiangli** [comment]
v2.11.0-rc.2 fixed the issue (on MacOS).

**Comment by YKWeyer** [comment]
I had the same issue with v2.10.0, can confirm it isn't on the v2.11.0-rc.2.

Perhaps a naive question, but isn't it considered a v2.10 bug? Will it be included in the v2.10.1 (bugfixes) release?

**Comment by bacongobbler** [comment]
It's a good question. Generally speaking, once we go forward with the next minor release we avoid cutting patch releases for prior releases, doubly so if there's a workaround for the patch. That's mostly done to reduce workload constraints on our end since we're a small team maintaining the project. I'll bring it up with the rest of the team and see what they think about cutting another release.

**Comment by tardich** [comment]
From within a Docker container based on ubuntu:16.04 (also tried from ubuntu:18.04), and helm versions 1.9.1, 1.10.0, and 1.11.0-rc.4,, and being behind a corporate proxy with http_proxy, https_proxy, HTTP_PROXY and HTTPS_PROXY variables set, I can<t make helm init work. Always getting this error:

> root@kubectl:/# helm init
Creating /root/.helm
Creating /root/.helm/repository
Creating /root/.helm/repository/cache
Creating /root/.helm/repository/local
Creating /root/.helm/plugins
Creating /root/.helm/starters
Creating /root/.helm/cache/archive
Creating /root/.helm/repository/repositories.yaml
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com
Error: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Get https://kubernetes-charts.storage.googleapis.com/index.yaml: x509: failed to load system roots and no roots provided

>

**Comment by bacongobbler** [comment]
Looks like your error message is unique compared to the rest of the reports. Notice the last bit of the error message:

> Error: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Get https://kubernetes-charts.storage.googleapis.com/index.yaml: x509: failed to load system roots and no roots provided

"failed to load system roots and no roots provided" doesn't look like a connection error, but that Go simply cannot find the system's root cert chain to validate the request against.

**Comment by kfox1111** [comment]
Yeah, that looks like there might be a different chain of trust being used. Are you a grid site by any chance?

**Comment by ReSearchITEng** [comment]
@tardich 
I can tell 2.9.1 does work. I suggest you stick to that version for your tests.
Are you able to  curl or `wget https://kubernetes-charts.storage.googleapis.com/index.yaml` ?
If so, try:
```
helm init --skip-refresh --wait
helm repo remove stable
helm repo add --ca-file=/etc/ssl/certs/ca-bundle.crt stable https://kubernetes-charts.storage.googleapis.com --debug
helm repo update
```
or even try to copy manually the index.yaml (if you wget worked)

**Comment by obitech** [comment]
I'm on Windows 10 behind a proxy and unfortunately the error persists for me. I've tried it with 2.9.1 and 2.11.0:

```
PS C:\Users\xx> helm init
Creating C:\Users\xx\.helm\repository\repositories.yaml
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com
Error: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Get https://kubernetes-charts.storage.googleapis.com/index.yaml: dial tcp 216.58.210.16:443: connectex: : connection refused
```

**Comment by tardich** [comment]
Is your k8s stack able to reach the internet otherwise? If you try to spin up a pod from a remote image, is it able to get it?

**Comment by obitech** [comment]
Yes my cluster performs normally. Also I'm able to `wget` from PowerShell, so the proxy configuration should be fine.

**Comment by tardich** [comment]
Well, not really. Docker needs to be informed about the proxy settings, which is different than the config for wget (at least on Linux)

**Comment by obitech** [comment]
I'm able to pull images and reach the internet from inside Docker images as well as from inside my cluster, if that's what you're asking.

**Comment by tardich** [comment]
Yes, this is what I meant. No clue then.

**Comment by garethmorris78** [comment]
@obitech  v2.11.0 fixed the issue for me with helm not picking up HTTPS_PROXY and HTTP_PROXY environment vars.   I was seeing this issue both on linux and windows. 

However you should also check the following:

1. If your proxy uses authentication have you whitelisted URLs helm needs to contact to not use auth ?

2. If your proxy is using SSL inspection then ensure any certs are in the local trusted cert store used by helm

3. If the above is not the cause then try and confirm that the helm traffic is leaving your network i.e. not being blocked by proxy/firewall. If you have a network team they can assist with this.
