### ISSUE TITLE
addressing authorization when deploying through helm cli and tiller

### ISSUE THREAD

**Issue by shikhasriva** [helm/helm#4330]
As a user with roles, I should be able to deploy charts only to the namespace I have access to 
We are using  Kubernetes User Impersonation to bridge the authorization gap. See the details below

**Comment by nweathe** [comment]
In our environment, we gave Tiller a ServiceAccount with a ClusterAdmin role-binding. 

When a user interacts with Kubernetes via Tiller, Tiller checks the user's role (ClusterAdmin/Admin/Editor/Operator/Viewer). Assuming the user _does_ have the authorization to C/R/U/D via Tiller, Tiller then forwards on the request to Kubernetes _with Tiller's ClusterAdmin ServiceAccount_. 

In most cases, this works well enough. Unauthorized users are stopped at Tiller's credential check. 

Unfortunately this approach is not fool-proof against role elevation. For example, a user with non-ClusterAdmin credentials can elevate his/her role by deploying a chart which then deploys a secondary chart. Tiller's credential check only confirms the user's ability to deploy the first chart, but Tiller's ClusterAdmin credentials sent to Kubernetes allows Kubernetes to deploy both charts. 

We closed this gap by implementing Kubernetes User Impersonation (i.e. pass user credentials to Kubernetes along with Tiller's credentials). Then Kubernetes only C/R/U/D what the user was authorized to C/R/U/D.

User Impersonation required two things: 

1) Tiller must be able to impersonate (Kubernetes verb)

2) Tiller must set K8s user impersonation headers

(1) was handled by virtue of Tiller's ClusterAdmin ServiceAccount. (2) required pulling `kubectl`'s code into Tiller's `pkg` directory, updating `kubectl`'s calls to the Kubernetes API with the impersonation headers, and re-route all Tiller calls through updated `kubectl` code.

After completing both steps, role elevation was no longer possible.

**Comment by michelleN** [comment]
@nweathe @shikhasriva It's awesome that ya'll have this working and thank you for sharing. I know it'll help quite a few people who are looking for something similar. 

We're currently working on Helm v3 which does not include a server-side component. We're not actively adding new features to Helm 2.0. Are you looking to add this to Helm 2.0? If so, we can definitely discuss this as an option at one of the upcoming Helm developer calls. Ya'll are welcome to join. [Here](https://github.com/helm/community/blob/master/communication.md#weekly-meeting) is all the info. [Here](https://github.com/helm/community/blob/master/helm-v3/000-helm-v3.md) is more information about the plan for Helm v3. 

I added a `proposal` label to this issue. Please let me know if that is correct or if this is more of knowledge sharing. Thanks again!

Cheers

**Comment by shikhasriva** [comment]
@michelleN, we can definitely add this to the 2.0. And would love to discuss application of the same to 3.0

**Comment by shikhasriva** [comment]
@michelleN , do you have a recommendation when we can add this topic to the community call? We are on today. It does not seem like the call is happening

**Comment by bacongobbler** [comment]
Hey @shikhasriva! The dev call just ended. Sorry you missed it! They occur every Thursday at 9:30AM PST. Is there an old link somewhere we need to update? The channel topic in #helm-dev on Slack has the most up-to-date information on where the meeting occurs.

**Comment by bridgetkromhout** [comment]
Hi, @shikhasriva - Helm 3 no longer has Tiller, and Helm 2 is now only receiving bugfixes. It's possible that this issue is no longer a problem for you, if you have migrated to Helm 3 (https://helm.sh/docs/topics/v2_v3_migration/). If you would like to propose Helm 3 updates, please open a new issue. Thanks!
