### ISSUE TITLE
Update to Kubernetes recommended labels

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#4335]
A set of recommended labels around applications just landed in the Kubernetes docs. They can be seen at https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/. Helm also has a set of standard labels in the best practices section at https://docs.helm.sh/chart_best_practices/#standard-labels. Many of these are for the same thing but with a different name.

Here's a diff of the two:

| Helm | k8s |
| --- | --- |
| `heritage` | `app.kubernetes.io/managed-by` |
| `release` | `app.kubernetes.io/instance` |
| `chart` | - |
| `app` | - |
| `component` | `app.kubernetes.io/component` |
| - | `app.kubernetes.io/name` |
| - | `app.kubernetes.io/version` |
| - | `app.kubernetes.io/part-of` |

Note, the use of a prefix of `app.kubernetes.io` is because these are not private and we expect machines to do work with these. For those cases k8s uses the notion of namespacing them.

More details on the k8s ones are in the docs. With examples.

How should we handle this for Helm and Charts?

**Comment by technosophos** [comment]
I guess we should update the docs?

**Comment by technosophos** [comment]
I guess we should prefix them with helm.sh/
