### ISSUE TITLE
Configuration in Helm

### ISSUE THREAD

**Issue by jeroenvisser101** [helm/helm#434]
AFAIK, the way to configure environment variables when using helm is to use `helm edit [chart]` and edit the rc's template. I think it would be great if helm would allow (in some way) to change the variables set in the template, possibly doing something like this:

``` bash
# ./postgres.env.dist
POSTGRES_USER=...
POSTGRES_PASSWORD=...
```

...and then run `deis install --with-config=./postgres.env` or similar which would allow to replace/append environment variables without changing the chart itself and also to allow committing `.dist` files in git repositories.

**Comment by bacongobbler** [comment]
this document may be of interest to you :)

https://github.com/helm/helm/blob/master/docs/generate-and-template.md

Some examples on how we generate secrets for workflow's components can be found [here](https://github.com/deis/charts/blob/master/workflow-beta2/tpl/deis-database-secret-creds.yaml).

**Comment by jeroenvisser101** [comment]
@bacongobbler that seems to do it! Thanks!
