### ISSUE TITLE
Access computed values in templates?

### ISSUE THREAD

**Issue by fhemberger** [helm/helm#4343]
I'm new to Go but I learned you can't define functions inside a template. But is there another way to access a once computed value (from a variable or other template) in a different template?

So far I tried:
```
{{- $foo := default "bar" .Values.foo -}}
…
{{- define "mytemplate" -}}
{{- if $foo -}}
{{/* do something and return the result */}}
{{- end -}}
{{- end -}}
```

=> `undefined variable "$foo"`

```
{{- define "valueA" -}}
{{/* do something and return the result */}}
{{- end -}}

{{- define "mytemplate" -}}
{{- $valueA := template "valueA" . -}}
{{/* do something depending on the value of "valueA" */}}
{{- end -}}

=> `unexpected <template> in command`

**Comment by technosophos** [comment]
Unfortunately, there is no good way to do this in Go templates. It _might_ be possible to do something like `{{ set .Values "foo" "bar" }}`, but I haven't tested that. I can't remember if .Values gets cloned or passed by reference.

**Comment by fhemberger** [comment]
Found the solution for the second case, it's not `template`, but `include`:

```
{{- define "mytemplate" -}}
{{- $valueA := include "valueA" . -}}
{{/* do something depending on the value of "valueA" */}}
{{- end -}}
```

Which works fine for my case. 👍

**Comment by E11esh** [comment]
Templates in helm cannot access variables. But can use dictionary passed in context.

Below will throw undefined variable "$variable" because in its context it was not available !

```
{{- $foo := default "bar" .Values.foo -}}
{{- include "mytemplate" $variable -}}
```

But can access dictionary handed in context, below we hand dictionay "$dictionary"
```
{{- $foo := default "bar" .Values.foo -}}
{{ $dictionary := dict "foo" $variable }}
{{- include "mytemplate" $dictionary -}}  
```

Correction in Template, now can access dictionay with key "foo"
```
{{- define "mytemplate" -}}
{{- if .foo -}}
{{/* do something and return the result */}}
{{- end -}}
{{- end -}}
```
