### ISSUE TITLE
With helm history set, if history is all failing deploys, deploy fails with "has no deployed releases"

### ISSUE THREAD

**Issue by andyedwardsdfdl** [helm/helm#4349]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:52:23Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.8-2+af27ab4b096122", GitCommit:"af27ab4b096122049e65b75ee29ac115b1d58f6b", GitTreeState:"clean", BuildDate:"2018-06-14T04:07:19Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
IBM Cloud Container Service

We are using helm with a limit set on the number of releases stored in the history (i.e. we set the `--history-max` flag when installing helm).

In one of our development environments we hit a problem where the deploy was failing (a trivial expired password), but by the time we discovered this, every recorded deployment in the history was for a failed deployment.  At this point, any attempt to run `helm upgrade` would return the error message `Error: UPGRADE FAILED: "your-release-name" has no deployed releases`.  It was then impossible to get out of this situation without running `helm delete --purge`.

We could work around this (longer history, always revert if the deploy fails, don't deploy if history only has 1 success in etc) but should helm knowingly move forward to a point where a deploy can never succeed?  Should the history only count successful deploys, or should it always keep the most recent successful deploy, no mater what the history limit is set to?

**Comment by andyedwardsdfdl** [comment]
Off the top of my head...

- When considering the max history count, only count the number of successful deploys in the total, i.e. ignore failed deploys.  This might end up with a lot of failed deploys in the history, which kinda negates the point of having a history limit.
- Always remember the most recent successful deploy, so there is always something to roll back to.  This would then only ever result in "${MAX_HISTORY} + 1" recorded deploys, but would result in "gaps" in the history (e.g. a history containing `5: SUCCESS`, `8: FAILED`, `9: FAILED`, `10: FAILED`...) 
- Only ever include the last failed deploy in the history.  If I can't successfully roll back to a release that failed to deploy (because I'd just end up in a broken state again) then all I care about is an audit history of releases (is this true?).  If that is true then recording the whole deployment doc for every failed release is only taking up space/config maps.  I don't know enough about the internals of helm to know if that is even possible though (like, is there any list of the release history outside of the config map of an individual release's deployment?).

I don't have a particular favourite, and there are almost certainly other good strategies; it just seems odd that helm allows itself to enter a state where its history _only_ contains failed deploys and roll-back becomes impossible.

**Comment by fbcbarbosa** [comment]
Just hit this same problem as well.

> Always remember the most recent successful deploy, so there is always something to roll back to. This would then only ever result in "${MAX_HISTORY} + 1" recorded deploys, but would result in "gaps" in the history (e.g. a history containing 5: SUCCESS, 8: FAILED, 9: FAILED, 10: FAILED...).

This works, but there is the issue that we only keep one single "useful" release. If, by chance, my single success release actually contains a major bug which does not prevent deploy, I'll have no other options to rollback to.

> Only ever include the last failed deploy in the history. If I can't successfully roll back to a release that failed to deploy (because I'd just end up in a broken state again) then all I care about is an audit history of releases (is this true?). If that is true then recording the whole deployment doc for every failed release is only taking up space/config maps. I don't know enough about the internals of helm to know if that is even possible though (like, is there any list of the release history outside of the config map of an individual release's deployment?).

I like this best for the reasons stated. Seems much safer than the previous as you will always have "MAX_HISTORY" options to rollback to.

**Comment by fbcbarbosa** [comment]
So I decided to try and tackle the issue and came up with a slightly different approach than @andyedwardsdfdl 3rd suggestion (to only ever include the last failed deploy in the history).

Mine is to always start by removing failed releases from the history before everything else. So if ${MAX_HISTORY} is 5 and you have 4 releases, you may have 1 successful release and 4 failed releases no problem. But once you release again, then the algorithm will start deleting the _oldest failed release_, even if the successful is the oldest one. Only when there are no more failed releases to delete, we starting deleting good releases.

So maybe all your latest "${MAX_HISTORY}" were successful so you keep no failed released in the history, which should probably not be a problem to most people. I think this approach has the advantage of being a little more generic.

Here's the code: https://github.com/helm/helm/compare/master...quintoandar:master

No PR because I still need to test and I'm not familiar at all with Helm's codebase so this might break everything as far as I know.

I'll make some tests and if it's good we'll start to use in our environments. We release _a lot_ and sometimes on test environments we can have multiple broken releases until someone patches a fix, and removing the max-history limit will break helm in a couple of weeks with all timeout issues due to configmaps/secrets reaching the thousands... I really need this fix badly :(

**Comment by fbcbarbosa** [comment]
Just to throw some new ideas, maybe it'd be best to leave it more configurable.

For example, [Kubernetes jobs](https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#jobs-history-limits) have `.spec.successfulJobsHistoryLimit` and `.spec.failedJobsHistoryLimit`. This way the user decides whether failed releases are important to them, and Tiller does not need to implement complex and arbitrary rules on which releases to keep.

So maybe split the flags into a `failed-history-max` and `successful-history-max` flag, with sane defaults? Of course, `successful-history-max` would need to be at least one.

**Comment by fbcbarbosa** [comment]
Well, the code works: https://github.com/helm/helm/compare/master...quintoandar:master

```
$ minikube start
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
$ helm init --tiller-image quintoandar/tiller:c118c46 --history-max 3
$ helm upgrade --install db stable/mariadb
$ helm upgrade --install db stable/mariadb
$ helm upgrade --install db stable/mariadb
$ helm upgrade --install db stable/mariadb
$ helm history db                         
REVISION	UPDATED                 	STATUS    	CHART        	DESCRIPTION     
2       	Fri Oct 26 14:51:05 2018	SUPERSEDED	mariadb-4.3.1	Upgrade complete
3       	Fri Oct 26 14:51:29 2018	SUPERSEDED	mariadb-4.3.1	Upgrade complete
4       	Fri Oct 26 14:51:31 2018	DEPLOYED  	mariadb-4.3.1	Upgrade complete
$ helm upgrade --install db stable/mariadb --set service.type=Gibberish
$ helm history db                                                      
REVISION	UPDATED                 	STATUS    	CHART        	DESCRIPTION                                                 
3       	Fri Oct 26 14:51:29 2018	SUPERSEDED	mariadb-4.3.1	Upgrade complete                                            
4       	Fri Oct 26 14:51:31 2018	DEPLOYED  	mariadb-4.3.1	Upgrade complete                                            
5       	Fri Oct 26 15:07:17 2018	FAILED    	mariadb-4.3.1	Upgrade "db" failed: Service "db-mariadb" is invalid: spe...
$ helm upgrade --install db stable/mariadb --set service.type=Gibberish
$ helm history db                                                      
REVISION	UPDATED                 	STATUS    	CHART        	DESCRIPTION                                                 
3       	Fri Oct 26 14:51:29 2018	SUPERSEDED	mariadb-4.3.1	Upgrade complete                                            
4       	Fri Oct 26 14:51:31 2018	DEPLOYED  	mariadb-4.3.1	Upgrade complete                                            
6       	Fri Oct 26 15:08:02 2018	FAILED    	mariadb-4.3.1	Upgrade "db" failed: Service "db-mariadb" is invalid: spe...
$ helm upgrade --install db stable/mariadb
$ helm history db                         
REVISION	UPDATED                 	STATUS    	CHART        	DESCRIPTION     
3       	Fri Oct 26 14:51:29 2018	SUPERSEDED	mariadb-4.3.1	Upgrade complete
4       	Fri Oct 26 14:51:31 2018	SUPERSEDED	mariadb-4.3.1	Upgrade complete
7       	Fri Oct 26 15:08:22 2018	DEPLOYED  	mariadb-4.3.1	Upgrade complete
$ helm upgrade --install db stable/mariadb
$ helm history db                         
REVISION	UPDATED                 	STATUS    	CHART        	DESCRIPTION     
4       	Fri Oct 26 14:51:31 2018	SUPERSEDED	mariadb-4.3.1	Upgrade complete
7       	Fri Oct 26 15:08:22 2018	SUPERSEDED	mariadb-4.3.1	Upgrade complete
8       	Fri Oct 26 15:09:00 2018	DEPLOYED  	mariadb-4.3.1	Upgrade complete
```

Do you find my solution acceptable or would you like to try some other option? I'm open to alternatives and willing to open a PR.

**Comment by fbcbarbosa** [comment]
Hey @andyedwardsdfdl and @technosophos, any thoughts on this?

**Comment by andyedwardsdfdl** [comment]
It certainly addresses the original issue, and the code looked good from a quick scan through.  I defer to the helm maintainers to decide though.

**Comment by fbcbarbosa** [comment]
@andyedwardsdfdl @technosophos v2.12.0 seems to have a fix:
https://github.com/helm/helm/pull/4978

It only saves the last deployed release (I'd like to have a couple more options to rollback to, if possible), but that's good enough to me for now. Maybe we should close this?
