### ISSUE TITLE
minor docs overflow issue

### ISSUE THREAD

**Issue by lukejpreston** [helm/helm#4350]
The following `.container-full` has `overflow-x: hidden` which causes `overflow-y` to always be on (in Chrome anyway). Perhaps, remove `overflow-x`, or make `overflow-y` hidden as well e.g. `overflow: hidden`. If it needs scroll you should change `overflow-y: auto` then it won't have this issue.

The reason this is an issue is when you scroll down you have to select the outer container first, and when you scroll back up it causes some lag as it scrolls to the top of this container.

I was going to see if I could do a PR myself but I can't work out how it has been generated and it looks like it would be a single line change.

**Comment by bacongobbler** [comment]
@lukejpreston see https://github.com/helm/helm-www :)

cc @flynnduism

**Comment by technosophos** [comment]
I believe this is fixed. Please re-open if the problem persists
