### ISSUE TITLE
Helm client automatically detect TLS configuration on the Tiller server and apply the certificates whenever it is required

### ISSUE THREAD

**Issue by winnietsang** [helm/helm#4354]
Feature request:
Helm client automatically detect whether the Tiller server is TLS configured or not. If it is TLS configured, then it will automatically apply the certificates whenever user execute a Helm command that required to access the Tiller server.

Reason for this request:
For any production grade K8s would have RBAC enable therefore Tiller will require to have TLS configured. User will setup the certificates and save them in the $HELM_HOME directory. Whenever a Helm command that require to access the Tiller server the user MUST provide the --tls option. If not the Helm command will failed. If the Helm command doesn't need to access the Tiller server, and the user add in --tls option, the command will failed too. 

If Tiller is TLS configured then every time a Helm command that need to access the Tiller server need to provide the certificates. It is not an option on the user end. May the Helm client automatically apply the certificates for the user instead of required the user to enter the --tls option every time?

**Comment by bridgetkromhout** [comment]
A belated thanks for opening this feature request, @winnietsang. As Helm 3 no longer uses Tiller, hopefully this isn't necessary anymore. If you find that you have new needs with Helm 3, please open a new issue - thanks!
