### ISSUE TITLE
helm init error 

### ISSUE THREAD

**Issue by shehroze37** [helm/helm#4368]
I am running helm init and getting the following error. Have tried running with sudo as well but no luck.

Error: could not get kubernetes client: could not get Kubernetes config for context "": invalid configuration: unable to read client-key ~/.minikube/client.key for minikube due to open ~/.minikube/client.key: permission denied

Anything specific that I need to do in order to fix this?

**Comment by technosophos** [comment]
This indicates that when `helm init` is run, it is reading the `$HOME/.kube/config` file, and that is directing it to load a TLS certificate from the path `$HOME/.minikube/client.key`. However, that file is either not there, or has permissions restrictive enough that `helm` cannot read it.

**Comment by Dhua-v** [comment]
I have this exact issue, with everything latest.
