### ISSUE TITLE
[request] Update k8s.io/* go-dependencies to branch "release-1.11"

### ISSUE THREAD

**Issue by dionysius** [helm/helm#4369]
I have a controller relying on packages for k8s.io/apimachinery release-1.11, but this controller is also using helm packages, which currently [depend on release-1.10](https://github.com/helm/helm/blob/01da56f956329bbfcef14ac164f9ab49081ad108/glide.yaml#L51). No variant can satisfy both apimachinery and helm, so I seem to have no choice than waiting for helms update to depend on release-1.11.
```
mycontroller# dep ensure -update -v
...
(29)  ? attempt k8s.io/kubernetes with 12 pkgs; 441 versions to try
(34)      try k8s.io/kubernetes@v1.11.1
(35)  ✗   k8s.io/kubernetes at v1.11.1 has problem subpkg(s):
(35)    	k8s.io/kubernetes/pkg/kubectl/resource is missing; required by k8s.io/helm@master.
(34)      try k8s.io/kubernetes@v1.11.0
(35)  ✗   k8s.io/kubernetes at v1.11.0 has problem subpkg(s):
(35)    	k8s.io/kubernetes/pkg/kubectl/resource is missing; required by k8s.io/helm@master.
(34)      try k8s.io/kubernetes@v1.10.5
(35)  ✗   k8s.io/kubernetes@v1.10.5 depping on k8s.io/apimachinery at release-1.11 has problem subpkg(s):	k8s.io/apimachinery/pkg/apimachinery/announced is missing	k8s.io/apimachinery/pkg/apimachinery/registered is missing
(34)      try k8s.io/kubernetes@v1.10.4
(35)  ✗   k8s.io/kubernetes@v1.10.4 depping on k8s.io/apimachinery at release-1.11 has problem subpkg(s):	k8s.io/apimachinery/pkg/apimachinery/announced is missing	k8s.io/apimachinery/pkg/apimachinery/registered is missing
(34)      try k8s.io/kubernetes@v1.10.3
...
```
I've currently k8s.io/helm as constraint branch=master.

**Comment by technosophos** [comment]
Is there something specific you are asking us to do?

1.11 support has been in the works for a long time, and is not released because of stability/compatibility issues. But we will get a final release done as soon as we can, though.

**Comment by dionysius** [comment]
Thank you. All good, I wasn't sure you are on track for that.
