### ISSUE TITLE
How to pass keyring password programatically

### ISSUE THREAD

**Issue by quantumlicht** [helm/helm#4376]
I would like to automate the signing process as part of a CI/CD pipeline. However I am faced the problem where the `helm package --sign` command asks for a password prompt (gpg actually prompts).

I know pgp allows to pass the password through the STDIN with:
`pgp --passphrase-fd`, but obviously that option would not be forwarded.

Is there another way to achieve this?

Output of `helm version`: 
```
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): N/A

**Comment by cog-qlik** [comment]
I've never tried the `--sign` option but, as you described, it seems that you're required to insert a password interactively and there's no way of doing programmatically (eg. from a file or env variable).

If that's the case, you could work around this limitation using [expect](https://linux.die.net/man/1/expect).

**Comment by quantumlicht** [comment]
@technosophos, unless I am missing something this does not solve my problem. the `helm-gpg` still prompt me for my password. At least the "happy path" does:
```helm package ...
helm gpg sign myrelease-0.0.1.tgz```
