### ISSUE TITLE
[FEATURE] Support file mode filter - to convert octal to decimal

### ISSUE THREAD

**Issue by ieugen** [helm/helm#4378]
It seems that json/yaml charts don't support octal representation of numbers [1]. This makes it quite cumbersome to mange unix file permissions for files. 

Helm can help simplify things if ti exposes a filter to convert octal form to decimal form.

```
{{ 0777 | toDecimal }} -> 511
```

https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod

**Comment by technosophos** [comment]
I would suggest contributing that to Sprig. github.com/Masterminds/sprig
