### ISSUE TITLE
unable to upgrade connection: Unauthorized

### ISSUE THREAD

**Issue by jingslunt** [helm/helm#4381]
Output of `helm version`:
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): null
```
[root@master helm]# kubectl -n kube-system get pod -l app=helm -o jsonpath='{.items[0].metadata.name}' -o wide
NAME                             READY     STATUS    RESTARTS   AGE       IP          NODE
tiller-deploy-5bfdbfd6f6-l77sn   1/1       Running   0          13m       10.0.77.6   master


[root@master helm]# kubectl -n kube-system port-forward  tiller-deploy-5bfdbfd6f6-l77sn 44134
error: error upgrading connection: unable to upgrade connection: Unauthorized
```

```
[root@master helm]# helm ls
Error: forwarding ports: error upgrading connection: unable to upgrade connection: Unauthorized
```

**Comment by technosophos** [comment]
It appears that your kubectl user account is not allowed to port forward. You'll have to look into why your Kubernetes cluster is configured that way.

**Comment by junsionzhang** [comment]
> It appears that your kubectl user account is not allowed to port forward. You'll have to look into why your Kubernetes cluster is configured that way.

would you mind tell me how to check it ? I met the same problem.
