### ISSUE TITLE
No response from tiller on k8s 1.11.0-gke.1

### ISSUE THREAD

**Issue by consideRatio** [helm/helm#4384]
I apparently fail to get a response from tiller when running `helm version` on fresh GKE clusters when I specify the version `1.11.0-gke.1` during the cluster creation, but everything works if I specify version `1.10.5-gke.2`.

I'm using Helm 2.9.1, and I've confirmed that the tiller deployment is running, and all the steps I've taken is exactly the same but the difference is the k8s version specified.

If you want to try for yourself, you can follow the steps I've outlined in this PR https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/758

**Comment by bacongobbler** [comment]
Helm support for Kubernetes 1.11 has been in the works, but is not available because of stability/compatibility issues w/ 1.11. But we will get a final release done as soon as we can, though.

**Comment by consideRatio** [comment]
I'm hoping to use fresh features with a chart [on a conference in a month](https://conferences.oreilly.com/jupyter/jup-ny/public/schedule/detail/68397). I appreciate the work you do on Helm @bacongobbler ! :heart:

---

In case it is helpful...

The logs from tiller are the following, before and after i run `helm version` locally - no indication of being asked about the version is given.
```
[main] 2018/07/26 06:45:06 Starting Tiller v2.9.1 (tls=false)
[main] 2018/07/26 06:45:06 GRPC listening on :44134
[main] 2018/07/26 06:45:06 Probes listening on :44135
[main] 2018/07/26 06:45:06 Storage driver is ConfigMap
[main] 2018/07/26 06:45:06 Max history per release is 0
```

I tried with `v2.10.0-rc.1` also btw...
```
$ helm version --debug
Client: &version.Version{SemVer:"v2.10.0-rc.1", GitCommit:"aa98e7e3dd2356bce72e8e367e8c87e8085c692b", GitTreeState:"clean"}
Kubernetes: &version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0-gke.1", GitCommit:"0c2ac1bb28512141205e890ffd7708dc747fd405", GitTreeState:"clean", BuildDate:"2018-06-29T23:11:15Z", GoVersion:"go1.10rc2b4", Compiler:"gc", Platform:"linux/amd64"}
```

```
[main] 2018/07/26 06:53:35 Starting Tiller v2.10.0-rc.1 (tls=false)
[main] 2018/07/26 06:53:35 GRPC listening on :44134
[main] 2018/07/26 06:53:35 Probes listening on :44135
[main] 2018/07/26 06:53:35 Storage driver is ConfigMap
[main] 2018/07/26 06:53:35 Max history per release is 0
```

**Comment by jascott1** [comment]
Hi @consideRatio 

Can we close this since we do not yet have Helm support for k8s 1.11 (known issue)?

**Comment by consideRatio** [comment]
Sure @jascott1!

@jascott1 / @bacongobbler - Id love to keep up to date on progress towards 1.11 compability - got any advice? Issue/PR to track, chatroom to join?
