### ISSUE TITLE
Alias in requirements.yaml is ignored for subcharts

### ISSUE THREAD

**Issue by andrenarchy** [helm/helm#4390]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.5-gke.3", GitCommit:"6265b9797fc8680c8395abeab12c1e3bad14069a", GitTreeState:"clean", BuildDate:"2018-07-19T23:02:51Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

I have the following chart structure:
```
charts/
├── paperhive
│   ├── charts
│   │   └── notification-service
│   │       ├── charts
│   │       │   ├── mongodb-replicaset-3.5.2.tgz
│   │       │   └── notification-service-http-server
│   │       │       ├── charts
│   │       │       ├── Chart.yaml
│   │       │       ├── templates
│   │       │       │   ├── deployment.yaml
│   │       │       │   ├── _helpers.tpl
│   │       │       │   ├── NOTES.txt
│   │       │       │   └── service.yaml
│   │       │       └── values.yaml
│   │       ├── Chart.yaml
│   │       ├── requirements.lock
│   │       ├── requirements.yaml
│   │       └── values.yaml
│   ├── Chart.yaml
│   └── values.yaml
```

where `requirements.yaml` contains the following:
```
dependencies:
  - name: mongodb-replicaset
    version: 3.5.2
    repository: '@stable'
    alias: notification-service-mongodb
```

When I run `helm template` (or `update`/`install`), the alias `notification-service-mongodb` is ignored and only the name `mongodb-replicaset` appears in the generated templates. 

Note: the alias works fine if both `requirements.yaml` and `requirements.lock` are under `charts/paperhive` instead of `charts/paperhive/charts/notification-service`.

Possibly this issue is related to https://github.com/helm/helm/issues/4389 where helm also behaves differently in a subchart.

**Comment by technosophos** [comment]
This does sound like a bug, though I'd have to defer to @jascott1 (who, I think, is the original author of the aliases code).

**Comment by jascott1** [comment]
Sorry I didn't write alias feature (I wrote the some of the subchart system). Could it be that alias requires 2 copies of subchart before alias kicks in?

**Comment by Sylordis** [comment]
Little bump on this issue.

```
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```

I just created a `mother-chart` and a `child-chart` (with `helm create <...>`) that I put in `mother-chart/charts/`.
```
mother-chart/
├── charts
│   └── child-chart
│       ├── charts
│       ├── Chart.yaml
│       ├── .helmignore
│       ├── templates
│       │   ├── deployment.yaml
│       │   ├── _helpers.tpl
│       │   ├── ingress.yaml
│       │   ├── NOTES.txt
│       │   └── service.yaml
│       └── values.yaml
├── Chart.yaml
├── .helmignore
├── requirements.yaml
├── templates
│   ├── deployment.yaml
│   ├── _helpers.tpl
│   ├── ingress.yaml
│   ├── NOTES.txt
│   └── service.yaml
└── values.yaml
```

My `requirements.yaml`:
```
dependencies:
  - name: child-chart
    alias: child1
  - name: child-chart
    alias: child2
```

Is this possible to put without repository? Because I do not have any and I'm not getting two children, only the normal one without alias.

**Comment by divoxx** [comment]
This seems to be happening on helm v3 as well.

The alias seems to be ignored completely, and does not replace the name of the chart. In addition, having multiple dependencies on the same chart, using different aliases, does not seem to deploy the chart multiple times.

**Comment by TBBle** [comment]
You shouldn't need multiple entries to make the aliases work. Our project has the same chart used by different charts, all of which set an alias for it to get their own version.

It works fine, but we use packages rather than extracted-source in the charts/ folder, in case that makes a difference.

**Comment by TBBle** [comment]
It appears this issue is still around and attracting duplicate.

**Comment by TBBle** [comment]
It appears this issue is still around and attracting duplicates.
