### ISSUE TITLE
helm ls --output=json returns an empty string for a cluster without releases

### ISSUE THREAD

**Issue by Fabian-K** [helm/helm#4393]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.8+unreleased", GitCommit:"e6f6b1fc13bd1f8f88ff9ec11ab5a6ad8b419cc9", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

Hi,

I set up helm for a new cluster (helm init) and did not yet install any charts to it. The  command `helm ls --output=json` currently returns an empty string. Can this return a valid json with an empty Releases array instead?

`{"Next":"","Releases":[]}`

Thanks,
Fabian

**Comment by nvtkaszpir** [comment]
any progress on this?

**Comment by bacongobbler** [comment]
```
><> helm ls --output json
[]
```

**Comment by nvtkaszpir** [comment]
@bacongobbler any info in which version it was introduced?
