### ISSUE TITLE
docs: per-namespace tiller installation doesn't work

### ISSUE THREAD

**Issue by rvandegrift** [helm/helm#4394]
I'm trying to install tiller to manage a single namespace, following https://docs.helm.sh/using_helm/#example-deploy-tiller-in-a-namespace-restricted-to-deploying-resources-only-in-that-namespace but kubernetes does not allow me to create the indicated role:

```sh
ross@malaclypse:~$ kubectl create namespace tiller-world
namespace/tiller-world created
ross@malaclypse:~$ kubectl create serviceaccount tiller --namespace tiller-world
serviceaccount/tiller created
ross@malaclypse:~$ kubectl apply -f - <<EOF
> kind: Role
> apiVersion: rbac.authorization.k8s.io/v1beta1
> metadata:
>   name: tiller-manager
>   namespace: tiller-world
> rules:
> - apiGroups: ["", "batch", "extensions", "apps"]
>   resources: ["*"]
>   verbs: ["*"]
> EOF
Error from server (Forbidden): error when creating "STDIN": roles.rbac.authorization.k8s.io "tiller-manager" is forbidden: attempt to grant extra privileges: [PolicyRule{APIGroups:[""], Resources:["*"], Verbs:["*"]} PolicyRule{APIGroups:["batch"], Resources:["*"], Verbs:["*"]} PolicyRule{APIGroups:["extensions"], Resources:["*"], Verbs:["*"]} PolicyRule{APIGroups:["apps"], Resources:["*"], Verbs:["*"]}] user=&{ross@kallisti.us  [system:authenticated] map[]} ownerrules=[PolicyRule{APIGroups:["authorization.k8s.io"], Resources:["selfsubjectaccessreviews" "selfsubjectrulesreviews"], Verbs:["create"]} PolicyRule{NonResourceURLs:["/api" "/api/*" "/apis" "/apis/*" "/healthz" "/openapi" "/openapi/*" "/swagger-2.0.0.pb-v1" "/swagger.json" "/swaggerapi" "/swaggerapi/*" "/version" "/version/"], Verbs:["get"]}] ruleResolutionErrors=[]
```
Switching the API from `v1beta1` to `v1` gives the same results.

I have `cluster-admin`, so I don't think this could be an issue with privilege escalation prevention.  But I don't understand how to interpret this response.

Cluster-wide installation works fine but is not appropriate for my use-case.

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.5-gke.3", GitCommit:"6265b9797fc8680c8395abeab12c1e3bad14069a", GitTreeState:"clean", BuildDate:"2018-07-19T23:02:51Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE 1.10.5-gke.3

**Comment by rvandegrift** [comment]
I've found a workaround.  First, add bind your user to the `cluster-admin` role:
```sh
$ kubectl create rolebinding user-admin --role=cluster-admin --user=<identity> --namespace=tiller-world
rolebinding.rbac.authorization.k8s.io/user-admin created
```
Now, creating the role succeeds:
```sh
kubectl apply -f - <<EOF
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-manager
  namespace: tiller-world
rules:
- apiGroups: ["", "batch", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
EOF
role.rbac.authorization.k8s.io/tiller-manager created
```
Next, delete the `cluster-admin` binding:
```sh
$ kubectl delete rolebinding user-admin --namespace tiller-world
rolebinding.rbac.authorization.k8s.io "user-admin" deleted
```
From here, I can continue with the rest of the section and get a working tiller in a separate namespace.

I'm not sure if the docs should be updated to include this.  It feels like a bug - if I shouldn't be able to create this role, then I shouldn't be allowed to make myself an admin and then create it.

**Comment by technosophos** [comment]
On an RBAC-enabled cluster, you would need to create the appropriate roles. So your solution is one of many correct solutions (all of which would require setting up the right roles and rolebindings.

**Comment by juv** [comment]
@technosophos so you are saying that I need to set up the roles and rolebindings with a cluster-admin user and that it will not work with just a admin user? (admin in the namespace where I want to install tiller)
