### ISSUE TITLE
Feature: Access to current release values during update and rollback

### ISSUE THREAD

**Issue by mgorniew** [helm/helm#4395]
For upgrade and rollback operations I would like to have access to values from currently deployed release. I have some hooks which should be run only if some values were changed, so with access to those _old_ values I could decide if I need to render hook template at all.

Those current(/old) values could be exposed under key like `PreviousValues` and this key would be only present if `Release.IsUpgrade` is set to `true`. 

Also current Chart metadata could be exposed under key like `PreviousChart`.

**Comment by bacongobbler** [comment]
closing as inactive.
