### ISSUE TITLE
helm version does not work without tiller

### ISSUE THREAD

**Issue by gintautassulskus** [helm/helm#4398]
`helm version` without a deployed Tiller simply outputs:
`Error: could not find a ready tiller pod`

It should at least output helm client version.

Output of `helm version`: 2.9.1

**Comment by jascott1** [comment]
Hi @gintautassulskus 

Executing `helm version` with version 2.9.1 and without a tiller pod, I do see the client version output. What is the issue you are having?

**Comment by gintautassulskus** [comment]
Hi @jascott1, thanks for the response. You are right, 2.9.1 works fine.
I used a different version of helm due to broken symlinks.

Just checked `v2.10.0-rc.2` and this one does throw: `Error: could not find a ready tiller pod`

**Comment by bacongobbler** [comment]
just checked and confirmed; https://github.com/helm/helm/commit/4efa18a5ec135229e36d3aeaca0f3cfa5a0fdb38#diff-8777a437e784252c14e5d85878dd62de looks like the offending commit that changed this behaviour. Will fix

**Comment by bacongobbler** [comment]
@gintautassulskus if you wouldn't mind testing #4410 that'd be much appreciated. From initial testing that seems to revert to previous behaviour while still adding the fix that @rchakra3 introduced in #4235. Thanks!

**Comment by gintautassulskus** [comment]
@bacongobbler, just checked - it does work. Even better, version reporting not longer gets stuck on the `tiller` part when it is absent.
Not sure why though, the client version is reported as `v2.8+unreleased`.  Shouldn't it be `v2.10.0-rc.2`?

```
Client: &version.Version{SemVer:"v2.8+unreleased", GitCommit:"4ec91f32d51fb83fb26623c097d4d003ea154572", GitTreeState:"clean"}
Error: could not find tiller
```

**Comment by bacongobbler** [comment]
If you compile from source, you'll get that odd versioning scheme :)
