### ISSUE TITLE
Helm required not fail if value is nil

### ISSUE THREAD

**Issue by sebglon** [helm/helm#4405]
Output of `helm version`:
2.9.1

if i set `{{ required ".Values.common.pimMasterUrl" .Values.common.pimMasterUrl }}`
and define on values.yaml
```
common:
  pimMasterUrl: nil
```

Helm install not fail so its' bad, but helm lint is green that's good

How can i have a good lint and a bad install or update if required value is nul or empty?

**Comment by technosophos** [comment]
That would be a `helm lint` bug. A nil value should fail `required`.

**Comment by bacongobbler** [comment]
closing as inactive.
