### ISSUE TITLE
v2.10.0-rc.2: Tiller doesn't start

### ISSUE THREAD

**Issue by floriantraber** [helm/helm#4413]
`helm version`:
helm: `v2.10.0-rc.2`
tiller image: `v2.10.0-rc.2`

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0-rancher1", GitCommit:"e27e2f5a930cfc136b28aa7d509b1d1c8ecb13d7", GitTreeState:"clean", BuildDate:"2018-03-29T00:13:11Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

After running `helm init --upgrade` to upgrade from helm `v2.9.1` to  `v2.10.0-rc.2` tiller doesn't start anymore.
 

Pod error log: 

> container_linux.go:262: starting container process caused "exec: \"/tiller\": stat /tiller: no such file or directory"

**Comment by bacongobbler** [comment]
I'm unable to reproduce. From my machine:

```
><> helm version -c
Client: &version.Version{SemVer:"v2.10.0-rc.2", GitCommit:"56154102a2f25ebf679c791907fd355bb0377f05", GitTreeState:"clean"}
><> helm init
...
><> helm version
Client: &version.Version{SemVer:"v2.10.0-rc.2", GitCommit:"56154102a2f25ebf679c791907fd355bb0377f05", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0-rc.2", GitCommit:"56154102a2f25ebf679c791907fd355bb0377f05", GitTreeState:"clean"}
```

Can you display the output of `kubectl -n kube-system get deploy tiller-deploy -o yaml`?

**Comment by bacongobbler** [comment]
oh, the entrypoint in the docker image was changed from /tiller to /bin/tiller. You'll need to switch over if you've hardcoded the entrypoint.
