### ISSUE TITLE
"See also" Links in html docs are generated incorrectly

### ISSUE THREAD

**Issue by mhuttner** [helm/helm#4421]
Each Helm Command in the web docs contains a "See also" section, but most of the links are broken. 

e.g. "helm completion" links to 
https://docs.helm.sh/helm/#helm_completion
but it should link to:
https://docs.helm.sh/helm/#helm-completion
("_" replaced by "-")

This is the case for all multi word links there.

**Comment by technosophos** [comment]
I filed the issue in the `helm/helm-www` issue queue.

**Comment by bridgetkromhout** [comment]
Thanks again for filing this issue. As @technosophos mentioned at the time, it was worked from the `helm/helm-www` issue queue; we resolved it in https://github.com/helm/helm-www/pull/168. You can see this working in the v2 docs: https://v2.helm.sh/docs/helm/#helm_completion - I'll resolve this now.
