### ISSUE TITLE
Feature request: No helm command to add to existing charts

### ISSUE THREAD

**Issue by guptaNswati** [helm/helm#4425]
There is no helm command to patch an existing chart with new additions or modifications. I wanted to extend [node_exporter](https://github.com/coreos/prometheus-operator/tree/master/helm/exporter-nodenode-exporter) chart to add GPU metrics exporter which involves changing templates/daemonset.yaml and values.yaml with the helm CLI without manually making the changes, but looks like its not possible even with many helm tricks.

`helm install --values=values.yaml` only replaces existing values but cannot add new values. 
`helm upgrade` can apply the changes but still these changes needs to be made manually.

Wont it be good to have such a command?

cc @flx42

**Comment by bacongobbler** [comment]
While no existing system is available in Helm 2, we are looking into adding functionality for Helm 3 called [the sandboxing model](https://github.com/helm/community/blob/master/helm-v3/001-charts.md), which is explained in more detail in the proposal I just linked to.

From the proposal:

> With this construction, the parent chart will (a) have access to the objects in the child charts, and (b) be responsible for initializing child charts. Library support will be provided for simplifying this process

> This design will make it possible for top-level charts to strategically override the behavior of subcharts, or (as above) simply use them as-is.

Is that the type of functionality you're looking for?

**Comment by guptaNswati** [comment]
Some of the new features that you are adding seems to add more flexibility to creating the charts, but I don't think it would solve what I want. I am looking for one command that can change the templates on the fly without doing any changes manually.

Lets say, I have an existing chart with a template/daemonset.yaml:

containers:        
  - name: node-exporter           
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"           
    imagePullPolicy: "{{ .Values.image.pullPolicy }}" 

And I do something like `helm update --template=modified-template` and now my template/daemonset.yaml gets these changes and has:

containers:        
  - name: node-exporter           
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"           
    imagePullPolicy: "{{ .Values.image.pullPolicy }}"
 - name: gpu-exporter 
   image: "{{ .Values.image1.repository }}:{{ .Values.image1.tag }}"

**Comment by bacongobbler** [comment]
closing as inactive.
