### ISSUE TITLE
Unable to use/build helm on scaleway arm server.

### ISSUE THREAD

**Issue by lion24** [helm/helm#4433]
Hi there,

I deploy a Kubernetes cluster with 1 master and 2 nodes on scaleway. I used the following blog to deploy the whole thing using terraform: https://stefanprodan.com/2018/kubernetes-scaleway-baremetal-arm-terraform-installer/

All went, fine, my master and nodes are up and running. 

As a first app, I tried to deploy plex media server in my cluster using:  https://github.com/munnerz/kube-plex which requires helm to be deployed. 

I first try to use a pre-compiled version of helm for my architecture (this one https://storage.googleapis.com/kubernetes-helm/helm-v2.9.1-linux-arm.tar.gz), but when doing `helm init --upgrade`, tiller container crash instantly: 

```
root@arm-master-1:~/linux-arm# kubectl get pods --namespace kube-system
NAME                                   READY     STATUS             RESTARTS   AGE
coredns-78fcdf6894-4sk2z               1/1       Running            0          2d
coredns-78fcdf6894-9gnwp               1/1       Running            0          2d
etcd-arm-master-1                      1/1       Running            0          2d
heapster-6bf94f989-kq4fj               1/1       Running            0          2d
kube-apiserver-arm-master-1            1/1       Running            0          2d
kube-controller-manager-arm-master-1   1/1       Running            0          2d
kube-proxy-4blqx                       1/1       Running            0          2d
kube-proxy-gbsln                       1/1       Running            0          2d
kube-proxy-tn2zg                       1/1       Running            0          2d
kube-scheduler-arm-master-1            1/1       Running            0          2d
kubernetes-dashboard-ccf7f578c-pc7r5   1/1       Running            0          2d
metrics-server-6b47d79649-wgxk5        1/1       Running            0          2d
tiller-deploy-597c48f967-glnwt         0/1       CrashLoopBackOff   1          13s
weave-net-5f8nm                        2/2       Running            0          2d
weave-net-cr5pl                        2/2       Running            1          2d
weave-net-dfsp5                        2/2       Running            0          2d
```
And the logs suggest an exec format error:
```
root@arm-master-1:~/linux-arm# kubectl logs tiller-deploy-597c48f967-glnwt --namespace kube-system
standard_init_linux.go:178: exec user process caused "exec format error"
```

Then I tried to compile by hand helm using the 2.9.1 branch, but I have a compilation issue because it cannot find context package, whereas it is correctly present in the glide.yaml file:
```
root@arm-master-1:/opt/go/src/k8s.io/helm# make build
GOBIN=/opt/go/src/k8s.io/helm/bin go install  -tags '' -ldflags '-w -s -X k8s.io/helm/pkg/version.GitCommit=189aba984990b2279f9513db1a4abd916b933311 -X k8s.io/helm/pkg/version.GitTreeState=clean' k8s.io/helm/cmd/...
vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:20:2: cannot find package "context" in any of:
	/opt/go/src/k8s.io/helm/vendor/context (vendor tree)
	/usr/lib/go-1.6/src/context (from $GOROOT)
	/opt/go/src/context (from $GOPATH)
Makefile:28: recipe for target 'build' failed
make: *** [build] Error 1
```

Output of `helm version`:
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/arm"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/arm"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Scaleway

**Comment by lion24** [comment]
Some extra infos:

docker version:
```
root@arm-master-1:~# docker version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:25:46 2017
 OS/Arch:      linux/arm

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:25:46 2017
 OS/Arch:      linux/arm
 Experimental: false
```
Go environment:
```
root@arm-master-1:~# go env
GOARCH="arm"
GOBIN="/opt/go/bin"
GOEXE=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/opt/go"
GORACE=""
GOROOT="/usr/lib/go-1.6"
GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_arm"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

**Comment by bacongobbler** [comment]
When you run `helm init`, the default tiller image for that release is deployed. In this case, it's a version of tiller that works on amd64 architecture. If you want to run tiller on arm architecture, you'll need to provide the `--tiller-image` flag with `helm init --upgrade` with a docker image compiled for arm support. Currently we don't have one available; see #4055 and #4252 for the issue and some work being done to add arm support to tiller. In the meantime, some community members are maintaining arm64 images over at https://github.com/jessestuart/tiller-multiarch.

**Comment by lion24** [comment]
@bacongobbler Ok, thanks for the fast answer! :) That explain indeed why this is not working due to incompatible arch.. 

Any clue about compilation error? I'm ok to build a tiller image with arm support and maintain it if needed :)

Cheers.

**Comment by bacongobbler** [comment]
`context` is a newer package in the Go stdlib. Helm's compiled against Go 1.10, and I see you're using 1.6 which doesn't have the `context` package available. Sounds like you just need a newer version of Go. ;)

A good point of reference would be to follow the steps our CI pipeline uses to compile helm: https://github.com/helm/helm/blob/master/.circleci/config.yml

**Comment by lion24** [comment]
@bacongobbler Great! Thanks for this helpful feedback. 

I gonna build helm against a more recent version go version, and follow instructions in CircleCI :) 

Will be back with the results :)


Cheers.

**Comment by thelander** [comment]
Hello, did you ever manage to get this to work? I'm trying to do the same on Scaleway. But no luck.

**Comment by bacongobbler** [comment]
@thelander what issues are you running into?

**Comment by thelander** [comment]
@bacongobbler I get `exec user process caused "exec format error"` errors when I try to deploy kubernetes-dashboard, for example. Other deployments such as WordPress will simply get stuck at `Pending`. I'm new to Kubernetes, so I could be doing something terribly wrong.

**Comment by bacongobbler** [comment]
> `exec user process caused "exec format error"`

Usually that means the image backing kubernetes-dashboard was compiled to run on amd64 architectures. it's the same issue @lion24 was having with the Tiller docker image: you'll likely have to modify most charts to use images that were compiled against ARM.

I'm going to close this issue as the original question OP brought up about how to compile Tiller for ARM architectures has been answered and we haven't heard any response since last August:

> Will be back with the results :)

Thanks!

**Comment by lion24** [comment]
@thelander, to be honnest I did not follow and continue to try make the things working on arm servers.. Basically all the charts I was testing were using amd64, so it was really PITA to get things working, I give up..

**Comment by tamsky** [comment]
In case you wanted to continue to try making things work on arm nodes:

https://github.com/rancher/k3s/issues/351#issuecomment-483509965

> Retry installation with an arm64 tiller image
> `helm init --service-account tiller --history-max 200 --tiller-image jessestuart/tiller`
