### ISSUE TITLE
tiller image on isolated environment (Without internet)

### ISSUE THREAD

**Issue by AkshayDubey29** [helm/helm#4435]
Can we have tiller dockerfile so that we can create and push the images to docker local repository, we do not have any access to the internet from k8s and when we are initiating helm it is trying to deploy tiller container which is getting stuck.

Output of `helm version`:
Client: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
Error: cannot connect to Tiller

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Private cloud

**Comment by bacongobbler** [comment]
Dockerfile can be found [here](https://github.com/helm/helm/blob/master/rootfs/Dockerfile), where you'll need to follow the [Developer's Guide](https://github.com/helm/helm/blob/master/docs/developers.md) to use.

Hope that helps!
