### ISSUE TITLE
Help needed: Helm chart error in {} to Yaml

### ISSUE THREAD

**Issue by Neekoy** [helm/helm#4439]
This is most likely really simple but I can't figure it out for 2 hours now. I have the following Consul Ingress that I want to parameterize through a parent chart:

    spec:
      rules:
      {{- range .Values.uiIngress.hosts }}
        - host: {{ . }}
          http:
            paths:
              - backend:
                  serviceName: {{ $serviceName }}
                  servicePort: {{ $servicePort }}
      {{- end -}}
      {{- if .Values.uiIngress.tls }}
      tls:
    {{ toYaml .Values.uiIngress.tls | indent 4 }}
      {{- end -}}
    {{- end }}

I want to parameterize `spec.tls` in the above.

In the `values.yaml` file for Consul we have the following template for it:

    uiIngress:
      enabled: false
      annotations: {}
      hosts: []
      tls: {}

The closest I got to parameterizing it is the following:

      uiIngress:
        tls:
        - hosts:
          - "some.domain.com"
        secretName: "ssl-default"

When I do that I get this error though:

```warning: cannot overwrite table with non table for tls (map[])```

Can someone please help, I tried a million things.

Output of `helm version`:
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}

Output of `kubectl version`: 

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T08:08:00Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS

**Comment by technosophos** [comment]
You declared `tls: {}` and then used it as a list:

```
tls:
- host
```

I think you just need to switch the `tls:` definition to `tls:[]`

**Comment by Neekoy** [comment]
@technosophos Thanks, however that definition is in helm/consul which is the official repository. I kind of wanted to parameterise it without forking it to our own repo, but am hitting on rock.
