### ISSUE TITLE
panic after  delete application

### ISSUE THREAD

**Issue by almerico** [helm/helm#4447]
Output of `helm version`:
Client: &version.Version{SemVer:"v2.10.0-rc.1", GitCommit:"aa98e7e3dd2356bce72e8e367e8c87e8085c692b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0-rc.1", GitCommit:"aa98e7e3dd2356bce72e8e367e8c87e8085c692b", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
docker-for-desktop Macosx

<img width="993" alt="screen shot 2018-08-08 at 4 58 16 pm" src="https://user-images.githubusercontent.com/2116248/43841863-c0af7b6c-9b2c-11e8-9161-b36543fb4027.png">

**Comment by jascott1** [comment]
Hi @almerico 

Sorry you are having trouble. Could you check Tiller to see if there is anything in the logs and post that here? It could be client side only but it would be nice to confirm Tiller isnt reporting anything. Thanks!

**Comment by bacongobbler** [comment]
Would you also mind testing with v2.10.0 rather than v2.10.0-rc.1? That way we can determine if it was fixed through a patch. Thanks!

**Comment by almerico** [comment]
After update to v2.10.0 issue does not reproduced
