### ISSUE TITLE
helm 'uncreate'

### ISSUE THREAD

**Issue by korenlev** [helm/helm#4453]
Created a local gtz with local repo, can see it with:
helm search -l | grep local
local/myapp - version - here

how can i remove it from local repo?

Client: &version.Version{SemVer:"v2.10.0-rc.2", GitCommit:"56154102a2f25ebf679c791907fd355bb0377f05", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0-rc.

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform: local bare-metal

**Comment by aswinkarthik** [comment]
The local results of `helm search` is from `~/.helm/repository/local/index.yaml`
You can just,

- Delete the `myapp.tar.gz` from `~/.helm/repository/local`
- Edit the `index.yaml` from `~/.helm/repository/local` and remove the entry under `.entries.mychart[]` where `name=myapp`

**Comment by korenlev** [comment]
process suggested by Aswin works.
will try to contribute as a new feature in helm...

**Comment by jascott1** [comment]
Hi @korenlev As there is no plans for any tooling around this I will close this as resolved with a workaround. Please let me know if you would like to reopen, thanks!
