### ISSUE TITLE
Quoted integers in (stable/postgresql) chart

### ISSUE THREAD

**Issue by remster** [helm/helm#4455]
Output of `helm version`:
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
minikube

```
helm install --name postgres --debug --dry-run stable/postgresql --set postgresDatabase=relabs,postgresUser=root,postgresPassword=toor --set persistence.enabled=true,persistence.size=3Gi --set persistence.existingClaim=pg-local-pvc
```
generates 
[out.postgres.txt](https://github.com/helm/helm/files/2274807/out.postgres.txt)
I note that integers for initialDelaySeconds and timeoutSeconds are quoted:
```
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready --host $POD_IP
          initialDelaySeconds: "5"
          timeoutSeconds: "3"
          periodSeconds: 
```
kubectl doesn't like that:
```
error: error validating "./helm/postgres.yaml": error validating data: [ValidationError(Deployment.spec.template.spec.containers[0].livenessProbe.failureThreshold): invalid type for io.k8s.api.core.v1.Probe.failureThreshold: got "string", expected "integer", ValidationError(Deployment.spec.template.spec.containers[0].livenessProbe.initialDelaySeconds): invalid type for io.k8s.api.core.v1.Probe.initialDelaySeconds: got "string", expected "integer", ValidationError(Deployment.spec.template.spec.containers[0].livenessProbe.timeoutSeconds): invalid type for io.k8s.api.core.v1.Probe.timeoutSeconds: got "string", expected "integer", ValidationError(Deployment.spec.template.spec.containers[0].readinessProbe.initialDelaySeconds): invalid type for io.k8s.api.core.v1.Probe.initialDelaySeconds: got "string", expected "integer", ValidationError(Deployment.spec.template.spec.containers[0].readinessProbe.timeoutSeconds): invalid type for io.k8s.api.core.v1.Probe.timeoutSeconds: got "string", expected "integer"]; if you choose to ignore these errors, turn validation off with --validate=false
```
and is back to happy when i remove the quotes.

Now the weirdest thing ever is that my colleague is running the same version of helm (down to the commit sha) and his numbers aren't quoted. And for another `helm version` never returns.

**Comment by bacongobbler** [comment]
Hey @remster, sorry to hear you're having issues with the postgres chart.

Looking at the ticket, I can't seem to identify an actual issue with Helm itself, but with the chart and its default values. Can you try posting an issue on the [community charts](https://github.com/helm/charts) repository first and see where that goes? If there's an actual bug in core then we can take a look.

Thanks!

**Comment by remster** [comment]
ok. This cache has not helped:
```
[remek][~/.helm/cache/archive]$ ll
total 64
drwxr-xr-x 2 remek remek  4096 Aug  9 16:47 ./
drwxr-xr-x 3 remek remek  4096 Jun 18 11:03 ../
-rw-r--r-- 1 remek remek  9616 Jun 18 11:39 grafana-1.11.3.tgz
-rw-r--r-- 1 remek remek  7442 Aug  9 17:16 influxdb-0.9.2.tgz
-rw-r--r-- 1 remek remek 12229 Aug  9 17:16 nginx-ingress-0.20.3.tgz
-rw-r--r-- 1 remek remek  8126 Aug  9 17:31 postgresql-0.14.1.tgz
-rw-r--r-- 1 remek remek 13317 Aug  9 17:16 redis-3.4.1.tgz
```

**Comment by remster** [comment]
@bacongobbler it's the issue with my cache. Do you think this is a bug still? Why hasn't my cache refreshed itself?

**Comment by bacongobbler** [comment]
Yeah, that's intentional. We erred on the side of not auto-updating the cache. Make sure to run `helm repo update` if you need the latest version of a chart when installing.

**Comment by remster** [comment]
What was the intention? Or are you trying to say, whatever it was, it was miscalculated?

**Comment by bacongobbler** [comment]
The intention was to not automatically update your cache before a `helm install`. If the user wants to deploy the latest and greatest version of a chart, they must run a `helm repo update`. This was an active choice made by the maintainers during early testing, at least for Helm 2. It's possible we could change this in Helm 3.
