### ISSUE TITLE
Helm upgrade produces : unable to upgrade connection: Unauthorized

### ISSUE THREAD

**Issue by JaroVojtek** [helm/helm#4458]
Hello
I need your help to resolve issue with SSL certificates.
I have produced my own SSL certificates for K8S cluster. Ininitalization of K8S cluster runs without problem and all PODs in kube-system namespaces are up and running, everything seems to work correctly.

But when I am trying to run helm deployment it throws me following error:

```
helm upgrade --install --reset-values prom-helmf-ns-monitoring /tmp/kubernetes/stable/prometheus --namespace monitoring --values /tmp/kubernetes/monitoring/values/values_prometheus_ns_monitoring.yaml --values /tmp/kubernetes/monitoring/values/main_promethus_config_ns_monitoring.yaml --kube-context kubernetes-admin@kubernetes
```
```
Error: forwarding ports: error upgrading connection: unable to upgrade connection: Unauthorized
````
Tiller pod is up and running"

```
tiller-deploy-759cb9df9-rltzf                  1/1       Running   0          14m
```
Thanks
Output of `helm version`: v2.9.1"
Output of `kubectl version`: v1.11.0
Cloud Provider/Platform (AKS, GKE, Minikube etc.): On Premisse

**Comment by vishal49naik49** [comment]
Hi,

What is the fix for this issue?
Please advise!

Thanks,
Vishal

**Comment by JaroVojtek** [comment]
hello @vishal49naik49, I have already resolved issue. The issue was with one wrongly generated SSL certificate. Once it was repaired, everything working as expected. What issue you currently face ? Do yo need to also generate your own SSL certs ?

**Comment by bacongobbler** [comment]
closing as resolved. Thanks for the follow-up.
