### ISSUE TITLE
Which K8S version should I use for helm? I can't find "/pkg/kubectl/resource"

### ISSUE THREAD

**Issue by ks864148379** [helm/helm#4465]

**Comment by bacongobbler** [comment]
master is compiled has support for Kubernetes 1.10. If you're using either v2.9.1 or the canary releases, it's recommended to use Kubernetes 1.10, but we have backwards compatibility for Kubernetes 1.9 as well (and likely earlier versions as well).

Does that help answer your question?

**Comment by ks864148379** [comment]
It is very useful, thank you
