### ISSUE TITLE
[Helm+Tiller TLS configuration] - Error: remote error: tls: bad certificate after a few weeks of working

### ISSUE THREAD

**Issue by brunoban** [helm/helm#4475]
Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.5-gke.4", GitCommit:"6265b9797fc8680c8395abeab12c1e3bad14069a", GitTreeState:"clean", BuildDate:"2018-08-04T03:47:40Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
`GKE`

I'm getting a weird issue with certificates that have been occurring every couple of weeks and I'm not entirely sure of the reason. The issue is that I install Tiller securely on a cluster, but a couple of weeks later tiller stops identifying the key and starts throwing bad certificate errors.

I generate them using this script:

```
openssl genrsa -out keys/ca.key.pem 4096
openssl genrsa -out keys/tiller.key.pem 4096
openssl genrsa -out keys/helm.key.pem 4096
KEYCONFIG=""/C=DE/ST=Berlin/L=Berlin/O=ExampleOrganization/OU=ExampleOrganizationUnit/CN=examplecn.de""
openssl req -key keys/ca.key.pem -new -x509 -days 3650 -sha256 -out keys/ca.cert.pem -extensions v3_ca -subj $KEYCONFIG -config ./pssl.cnf
openssl req -key keys/tiller.key.pem -new -sha256 -out keys/tiller.csr.pem  -subj $KEYCONFIG -config ./pssl.cnf
openssl req -key keys/helm.key.pem -new -sha256 -out keys/helm.csr.pem  -subj $KEYCONFIG -config ./pssl.cnf
openssl x509 -req -CA keys/ca.cert.pem -CAkey keys/ca.key.pem -CAcreateserial -in keys/tiller.csr.pem -out keys/tiller.cert.pem
openssl x509 -req -CA keys/ca.cert.pem -CAkey keys/ca.key.pem -CAcreateserial -in keys/helm.csr.pem -out keys/helm.cert.pem
```

with pssl.cnf being:

```
[ req ]
distinguished_name  = req_distinguished_name

[ req_distinguished_name ]


[ v3_ca ]
basicConstraints = critical,CA:TRUE
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always,issuer:always
```

Anyone has any idea of what is causing the issue or if I'm doing something wrong? It's not the same as #3735 from what I could gather.

Thank you!

**Comment by OscarAyoy** [comment]
Off the top of my head, the default validity date for certs issued with the OpenSSL command line is 30 days.

From looking at the commands you are running above, you are only specifying the lifetime of the CA certificate (keys/ca.cert.pem) by passing `-days 3650` on the first `openssl req` command line, and not the lifetimes of the certificates for either Tiller or Helm. This looks like it would be the cause of the issue. Those certificates will expire after 30 days.

In order to set the lifetime for those certificates as well you can pass the same `-days 3650` (replace the actual numeric value as appropriate) flag to the `openssl x509` commands as well, like so:

```
$ openssl x509 -req -days 3650 -CA keys/ca.cert.pem -CAkey keys/ca.key.pem -CAcreateserial -in keys/tiller.csr.pem -out keys/tiller.cert.pem
Signature ok
subject=/C=DE/ST=Berlin/L=Berlin/O=ExampleOrganization/OU=ExampleOrganizationUnit/CN=examplecn.de
Getting CA Private Key
$ openssl x509 -req -days 3650 -CA keys/ca.cert.pem -CAkey keys/ca.key.pem -CAcreateserial -in keys/helm.csr.pem -out keys/helm.cert.pem
Signature ok
subject=/C=DE/ST=Berlin/L=Berlin/O=ExampleOrganization/OU=ExampleOrganizationUnit/CN=examplecn.de
Getting CA Private Key
```

FYI: If you want to check the expiry date on one of your certificates you can use the following OpenSSL command:

```
$ openssl x509 -enddate -noout < keys/tiller.cert.pem
notAfter=Sep  3 13:56:21 2028 GMT
```

**Comment by brunoban** [comment]
That's exactly what I was doing wrong!

Thank you so much @OscarAyoy !
