### ISSUE TITLE
Idempotent repo add/remove

### ISSUE THREAD

**Issue by ddseapy** [helm/helm#4476]
Currently 'helm repo add' hangs indefinitely if the repo exists and 'helm repo remove' exits with error if the repo exists.

Probably easiest to add flags on 'helm repo add' and 'helm repo remove' similar to how there is an idempotent 'helm upgrade --install'.

**Comment by mattfarina** [comment]
Have you see the `--no-update` flag on `helm repo add`?

What is the error you see on `helm repo remove` when the repo exists?

**Comment by ddseapy** [comment]
Sorry, meant exists with error if the repo doesn't exist.  Message is: `"Error: no repo named "foo" found`
```bash
echo $?
1
```
Which is probably fine, as for that use case I can just do the following (although I don't want to ignore other errors).
```bash
helm repo remove foo || true
```

I apologize, I did not see the --no-update flag.  So I believe that `helm repo add` is ok.  I'm still unsure of the reason for the command hanging, but i'll try to track that down.

Thanks for the help.  I'll close this as the hanging doesn't have to do with the ticket and I can work around the helm repo remove error code.
