### ISSUE TITLE
docs: {{block}} construct defined in the documentation but not explained/used

### ISSUE THREAD

**Issue by ahmetb** [helm/helm#4479]
https://github.com/helm/helm/blob/777d9be04aed9a58aeeb6ab01aec81f0cc2b647a/docs/chart_template_guide/control_structures.md

defines "block" as this:

> ![image](https://user-images.githubusercontent.com/159209/44237932-5a179b00-a167-11e8-813b-8081739893ba.png)

that said:

- no example of this {{block}} in the docs
- I can't find any charts using this {{block}} thing in helm/charts repo.

Does it actually exist?

**Comment by bacongobbler** [comment]
This is part of [text/template](https://golang.org/pkg/text/template/#hdr-Actions), so it exists, yes.
