### ISSUE TITLE
Helm create proposal

### ISSUE THREAD

**Issue by arturictus** [helm/helm#4481]
Hi,
I'm trying to create an standard chart for my team to be able to deploy any application in just few minutes with a pre-made chart.
The intent is to only modifying the `values` file be able to deploy most common types of applications.

If someone is interested in this approach an it may be included in Helm this is the repo I'm working on:
https://github.com/arturictus/helm-multideployment

The approach will be to add all the Kubernetes resource types as templates.

**Comment by bacongobbler** [comment]
closing as inactive.
