### ISSUE TITLE
`helm repo index --merge` not idempotent?

### ISSUE THREAD

**Issue by marshall007** [helm/helm#4482]
I am attempting to configure a CI job that will rebuild and publish the helm repo from source when changes are pushed. I first copy the existing repository `index.yaml` before calling `helm repo index --merge index.yaml`. Unfortunately, it appears that merging the old repository index is not idempotent, causing the `created` date to be bumped on charts where the `digest` has not changed.

Is this expected behavior? Are there any workarounds?

```diff
diff --git a/.build/index-old.yaml b/.build/sync/index.yaml
old mode 100644
new mode 100755
index cb9e0ee..9b80638
--- a/.build/index-old.yaml
+++ b/.build/sync/index.yaml
@@ -33,7 +33,7 @@ entries:
   dat:
   - apiVersion: v1
     appVersion: "1.0"
-    created: 2018-08-17T12:02:25.396690224-05:00
+    created: 2018-08-17T12:31:49.892096308-05:00
     description: A Helm chart for Kubernetes
     digest: f717fb4084fbca73244d413ae1e072c8f9962307003c0711cfa7200f6514ec36
     name: dat
@@ -43,9 +43,9 @@ entries:
   istio:
   - apiVersion: v1
     appVersion: 1.0.0
-    created: 2018-08-17T12:02:25.399560667-05:00
+    created: 2018-08-17T12:31:49.894843747-05:00
     description: Helm chart for all istio components
-    digest: 851aa73ab6e050d2103a67e7c21e483267de41ae5b0cbafcf1c50f7c20c6c51b
+    digest: 53dda163457b3bb170c867257cdb2b66e6e3273e19976296e76016f809895856
     engine: gotpl
     icon: https://istio.io/favicons/android-192x192.png
     keywords:
@@ -65,7 +65,7 @@ entries:
   istio-remote:
   - apiVersion: v1
     appVersion: 1.0.0
-    created: 2018-08-17T12:02:25.400378028-05:00
+    created: 2018-08-17T12:31:49.896217547-05:00
     description: Helm chart needed for remote Kubernetes clusters to join the main
       Istio control plane
     digest: e485ea21f1e279bec62a8883b856bea5f6423328309c9ff919cb440eeee777c9
@@ -80,1 +80,1 @@ entries:
-generated: 2018-08-17T12:02:25.395691227-05:00
+generated: 2018-08-17T12:31:49.887831702-05:00
```

---

Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T15:22:13Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.5", GitCommit:"9b635efce81582e1da13b35a7aa539c0ccb32987", GitTreeState:"clean", BuildDate:"2018-08-02T23:42:40Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform: **GKE/Minikube**

**Comment by zdw** [comment]
@monotek Filesystem dates aren't to be trusted - have limited accuracy depending on the filesystem, and can be changed intentionally or unintentionaly. 

Verifying that the actual chart .tgz files are unchanged would require recalculating the checksum and compare on all of them, which could be costly if there are lots of charts, and the "right" thing to do if the checksums don't match is debatable (update checksum and date? throw an error and fail?).

Additionally, overwriting the index.yaml file in-place seems like it could lead to other problems. 

The current behavior seems correct but could be documented better.

**Comment by monotek** [comment]
Yes, normaly thats true. 
But as a first try i've set my filedates from git log and hoped the times would be recreated.
So it still would be an option for me...

**Comment by monotek** [comment]
Yes, using kind of the same workaround.
Only thing left i have to fix is the case where we updating the ci config and a package is build with the last version again and the original create time is overwritten in the index.yaml.
Some kind of "no overwrite" in helm option would be helpfull here. 
But could be prevented with some workaround too...

**Comment by bacongobbler** [comment]
closing as inactive.

**Comment by MatthiasLohr** [comment]
I never worked with `helm merge`, don't even know what is does. But I'm running into the same problem just using `helm repo index`. Is that really an indented behaviour??
