### ISSUE TITLE
Full helm tarball for download

### ISSUE THREAD

**Issue by daniloegea** [helm/helm#4492]
Hello, I'm maintaining a package of helm for the FreeBSD ports tree.
As we need to check the integrity of the tarballs after the download, I can't use glide to install all the dependencies during the build. To workaround this I'm keeping a complete tarball in a private site, so it can be downloaded and built.

I would like to ask if it would be possible put the complete package (with the vendor directory populated) in the "releases" page here in the github.

It would simplify the build process of all the projects that keep a package of helm, like FreeBSD.

Thanks!

**Comment by technosophos** [comment]
If I'm interpreting this correctly, then what you're asking for is if, during release, we add a source tarball on the release page that contains not only the core source code, but also `vendor/` and all of its contents?

**Comment by daniloegea** [comment]
Yes.

**Comment by bacongobbler** [comment]
no.
