### ISSUE TITLE
syntax style best practice suggestion

### ISSUE THREAD

**Issue by wtayyeb** [helm/helm#4494]
Hi. 
It is not a bug. I have review several helm charts and write some else for my projects. I see this pattern is commonly used in published charts: `{{ toYaml .Values.resources | indent 12 }}` as you can see in below screenshot it is very bad indented!
![image](https://user-images.githubusercontent.com/1420290/44330852-4d53b980-a47d-11e8-9459-c87ec4a0f2d7.png)

also it have one blank line after it. note one empty line before `nodeSelector`
![image](https://user-images.githubusercontent.com/1420290/44331098-e551a300-a47d-11e8-939a-8198a7ea906c.png)

## my suggestion

to solve described problems above, use `<12 spaces >{{ toYaml .Values.resources | indent 12 | trim }}`

the result will be:
![image](https://user-images.githubusercontent.com/1420290/44331368-8f312f80-a47e-11e8-8a9c-231bb0e12840.png)

and in result the extra blank line also disappear
![image](https://user-images.githubusercontent.com/1420290/44331480-c7d10900-a47e-11e8-985f-abb39165a693.png)

**Comment by technosophos** [comment]
What happens if you just do `{{ toYaml .Values.resources | indent 12 -}}`? The trailing `-` should consume the extra newline.

**Comment by wtayyeb** [comment]
no it does not remove that line. because the new line is created via toYaml but `-}}` remove spaces between `{{` and `}}`. I noticed that there is another dash right in next tag starting `{{- with ...` and if the newline could be omitted it will remove it. but it can't! ( newline is generated via toYaml )

however with it only we can't indent the `{{ toYaml` and it must start at the first of line again.

Essentially I suggest `trim` for better indentation of `{{ toYaml`. removing the newline is a good side-effect!

tested and the result is:
![image](https://user-images.githubusercontent.com/1420290/44434248-58aefe00-a5bf-11e8-9648-3cfaf21c1304.png)

![image](https://user-images.githubusercontent.com/1420290/44434253-619fcf80-a5bf-11e8-9838-e8f7b77528d0.png)

**Comment by bacongobbler** [comment]
Use `nindent` if you rely on multi-line input. Closing!
