### ISSUE TITLE
Common charts' "common.util.merge" can't take nil definition of overrides

### ISSUE THREAD

**Issue by txomon** [helm/helm#4495]
In many of the docs of the common chart, the documentation states to use the templates as follows, because everything is taken care of in the common package directly :

```
{{- template "common.persistentvolumeclaim" (list . "pypicloud.persistentvolumeclaim") -}}
{{- define "pypicloud.persistentvolumeclaim" -}}
{{- end -}}
```

However, doing this will make the chart impossible to render, raising the following error `Error: rendering template failed: assignment to entry in nil map`.

I have found that by overriding a known key is enough to overcome the error. I found the best to just override the metadata.name with the common template.

```
{{- template "common.persistentvolumeclaim" (list . "pypicloud.persistentvolumeclaim") -}}
{{- define "pypicloud.persistentvolumeclaim" -}}
metadata:
  name: {{template "common.fullname" .}}
{{- end -}}
```

**Comment by technosophos** [comment]
You might want to file a ticket in https://github.com/helm/charts for that particular chart.
