### ISSUE TITLE
push additional resource files to a post hook container

### ISSUE THREAD

**Issue by MarWestermann** [helm/helm#4502]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```
Output of `kubectl version`: kubernetes v1.9.1+a0ce1bc657

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Self hosted multinode openshift origin 3.9

I use helm to install a bunch of microservices on openshift. Nevertheless I need to feed one of the microservices with default data while installing. To feed the microservice with that data I need to call a rest service and pass the data to that service.

My idea was to create a template in my helm chart as post install hook, which starts a container which then can post the data to the microservice. But here starts my problem. I somehow have to pass the data to the pod which then calls the microservice with that data. But I cannot find a technique to realize my idea.

I think using env vars inside the template is not possible.
The data that I need to push to the service are groovy scripts.

My idea was to have a separate folder inside the chart like servicedata which has files in it. These files needs to be accessable inside my custom pod

Any ideas?

Regards, Marco

**Comment by technosophos** [comment]
I think you want two things in your hook:

- A Job that executes the script
- A ConfigMap that holds the script

Put the groovy script in the ConfigMap, and have that mount to the Job's pod as a volume. Then you can use the Job's command to execute the Groovy script.

You can even keep the script in a separate file, and then inject it into the configmap via templates.

You will want to annotate the job with a hook annotation. You _could_ annotate the config map that way too, but since it's a post hook, it doesn't matter as much.

**Comment by MarWestermann** [comment]
@technosophos: Hi and thank you for your help. But I cannot find any resources how to archive what you suggest.
I like the idea to inject the scripts to the config map via templates but am not sure how to do that.

I already have a job which would operate on the scripts inside the pod.

In my root chart folder I have a folder path resources/scripts which holds my groovy scripts.
how would I inject the scripts to the config map and then mount that config map so the scripts would be mounted e.g. to /data in the job pod?

Thank you for your help.
Regards, Marco

**Comment by MarWestermann** [comment]
Ok after some research I got it working
