### ISSUE TITLE
helm --set values do not allow Spaces

### ISSUE THREAD

**Issue by eduncan911** [helm/helm#4504]
```
helm upgrade --install test ../../zookeeper --debug --tiller-namespace test --namespace test \
--set zookeeper.config.heapOptions="-Xmx3g -Xms3g"
Error: unknown shorthand flag: 'X' in -Xms3g'
```

Doesn't matter if using single or double quotes.

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:16Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Baremetal install on vSphere VMs

**Comment by eduncan911** [comment]
Note that we cannot upgrade to Helm 2.10.0 as this is a very large cluster shared by a dozen or so teams.  Would love to try however we aren't allowed to upgrade yet and I get an error if I try to use the 2.10.0 client with 2.9.1 Tiller version.

So I am unsure if it is fixed in 2.10.0.

**Comment by bacongobbler** [comment]
does it work if you try escaping the hyphen or putting it in values.yaml instead? It looks like cobra is trying to parse `-Xms3g` as a feature flag.

**Comment by bacongobbler** [comment]
We might need to add hyphens to [the documentation on the limitations with --set](https://docs.helm.sh/using_helm/#the-format-and-limitations-of-set) assuming that works.

**Comment by technosophos** [comment]
I believe you need single quotes to escape for shell, and double quotes inside to escape for YAML. (or maybe `\` before the space will do it).

**Comment by eduncan911** [comment]
> @bacongobbler does it work if you try escaping the hyphen or putting it in values.yaml instead? It looks like cobra is trying to parse -Xms3g as a feature flag.

In the default `values.yaml` i have for the charts, it's never complained.  Only the command line has complained.

Ah, I remember `cobra`'s go package.  wonder if it is an issue with Cobra?

> @technosophos I believe you need single quotes to escape for shell, and double quotes inside to escape for YAML. (or maybe \ before the space will do it).

These options are being set in a bash script, like so:

```
export HELM_OPTIONS="--set ... \
--set zookeeper.config.heapOptions='-Xmx3g -Xms3g' \
--set ..."
```

Note the enclosed double-quote, and then single quotes within.  This is what originally generated the stated error in the OP.

I tried escaping with backslash `\` earlier as well, and it didn't help.  Also tried ascii code for space (hey, really reaching here!).

**Comment by a-roberts** [comment]
Is there an accepted solution for this?

I'm hitting this too, want to provide Git options into a Helm chart. Instead I get "this command needs 1 argument: chart name" as the Helm client seemingly takes out the quotes when I try to install with --set global.myCoolOption="foo bar baz".

Is there really no solution for passing in a bunch of options (indeed like Java options)? 

Could provide a listing instead, then iterate over it using `range`, then concatenate, but I want to use it in a Jenkins ConfigMap later and this approach seems ridiculously clunky. I too am stuck not using Helm 2.10: want to use Helm 2.9.1.

**Comment by suonto** [comment]
@a-roberts I've also found issues with `$@` and whitespaces in script wrappers. I've used `$*` (args as one string) into `cut` as a robust way of wrapping args as separate strings into executables in bash. Example:
```
function mvn () {
  docker run -i \
    -v $(pwd):/app:rw \
    -w /app \
    maven:3.3-jdk-8 mvn $(echo $* | cut -d ' ' -f1-) --other --args --here
}
```

**Comment by technosophos** [comment]
helm install --dry-run --debug foo $HELM/docs/examples/alpine --set image.repository="foo\\ bar"

Note I have to double `\\` on zsh (and on bash or sh) because `\` is interpreted by the shell.

**Comment by bacongobbler** [comment]
Closing as answered

**Comment by antoniodesenvolvedor** [comment]
> This seems to work fine for me: `helm install --dry-run --debug foo $HELM/docs/examples/alpine --set image.repository="foo\\ bar"`
> 
> Note I have to double `\\` on zsh (and on bash or sh) because `\` is interpreted by the shell.

That did not work for me. Did it work for someone else?

**Comment by ds0nt** [comment]
Nothing works. FYI

**Comment by ds0nt** [comment]
I tried with like every concievable escaping

**Comment by ds0nt** [comment]
At this point I'm going to resort to using `|` in the place of a space and then using `replace` in the templates. Pretty inconvinient.

**Comment by ds0nt** [comment]
Not even changing IFS works.
