### ISSUE TITLE
Error: no available release name found

### ISSUE THREAD

**Issue by zwhitchcox** [helm/helm#4506]
Output of `helm version`:
`Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}`

Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
kubeadm on digital ocean (see https://mherman.org/blog/2018/08/20/setting-up-a-kubernetes-cluster-on-ubuntu )....I think this approach is called bare metal?

So, like mentioned in #3055, I'm getting the error messages `Error: no available release name found` when I try `helm install stable/mysql`. 

So, I have a brand new installation with kubeadm, and I use `helm init`, and I tried all the suggestions in #3055, but nothing works. That's about all I know.

**Comment by zwhitchcox** [comment]
`helm install stable/mariadb` returns `Error: no available release name found` as well

**Comment by zwhitchcox** [comment]
Yes, with the rbac:

`
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: kube-system
`
I still get the same error, which, I believe gives tiller admin privileges to the entire cluster

**Comment by bacongobbler** [comment]
And you initialized tiller via `helm init --service-account=tiller`? Check the tiller-deploy Deployment object in kube-system and post the YAML output here. :)

**Comment by zwhitchcox** [comment]
Tiller appears to start fine:

```
Name:               tiller-deploy-759cb9df9-fp8sn
Namespace:          kube-system
Priority:           0
PriorityClassName:  <none>
Node:               kube-host1/209.97.156.222
Start Time:         Tue, 21 Aug 2018 19:54:24 -0400
Labels:             app=helm
                    name=tiller
                    pod-template-hash=315765895
Annotations:        <none>
Status:             Running
IP:                 192.168.1.3
Controlled By:      ReplicaSet/tiller-deploy-759cb9df9
Containers:
  tiller:
    Container ID:   docker://3ec4dc4c3ef7683fd2dc9eef39493cd8d8e428ad5a4eb9ac53b20160aad41618
    Image:          gcr.io/kubernetes-helm/tiller:v2.9.1
    Image ID:       docker-pullable://gcr.io/kubernetes-helm/tiller@sha256:417aae19a0709075df9cc87e2fcac599b39d8f73ac95e668d9627fec9d341af2
    Ports:          44134/TCP, 44135/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Running
      Started:      Tue, 21 Aug 2018 19:54:27 -0400
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:44135/liveness delay=1s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:44135/readiness delay=1s timeout=1s period=10s #success=1 #failure=3
    Environment:
      TILLER_NAMESPACE:    kube-system
      TILLER_HISTORY_MAX:  0
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from tiller-token-m62nx (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  tiller-token-m62nx:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  tiller-token-m62nx
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age   From                 Message
  ----    ------     ----  ----                 -------
  Normal  Scheduled  3m    default-scheduler    Successfully assigned kube-system/tiller-deploy-759cb9df9-fp8sn to kube-host1
  Normal  Pulling    3m    kubelet, kube-host1  pulling image "gcr.io/kubernetes-helm/tiller:v2.9.1"
  Normal  Pulled     3m    kubelet, kube-host1  Successfully pulled image "gcr.io/kubernetes-helm/tiller:v2.9.1"
  Normal  Created    3m    kubelet, kube-host1  Created container
  Normal  Started    3m    kubelet, kube-host1  Started container
```

**Comment by zwhitchcox** [comment]
This is the log output

```
[main] 2018/08/21 23:54:27 Starting Tiller v2.9.1 (tls=false)
[main] 2018/08/21 23:54:27 GRPC listening on :44134
[main] 2018/08/21 23:54:27 Probes listening on :44135
[main] 2018/08/21 23:54:27 Storage driver is ConfigMap
[main] 2018/08/21 23:54:27 Max history per release is 0
[tiller] 2018/08/21 23:54:53 preparing install for 
[storage] 2018/08/21 23:54:53 getting release "boiling-quokka.v1"
[storage/driver] 2018/08/21 23:55:23 get: failed to get "boiling-quokka.v1": Get https://10.96.0.1:443/api/v1/namespaces/kube-system/configmaps/boiling-quokka.v1: dial tcp 10.96.0.1:443: i/o timeout
[tiller] 2018/08/21 23:55:23 info: generated name boiling-quokka is taken. Searching again.
[storage] 2018/08/21 23:55:23 getting release "funky-frog.v1"
[storage/driver] 2018/08/21 23:55:53 get: failed to get "funky-frog.v1": Get https://10.96.0.1:443/api/v1/namespaces/kube-system/configmaps/funky-frog.v1: dial tcp 10.96.0.1:443: i/o timeout
[tiller] 2018/08/21 23:55:53 info: generated name funky-frog is taken. Searching again.
[storage] 2018/08/21 23:55:53 getting release "punk-dingo.v1"
[storage/driver] 2018/08/21 23:56:23 get: failed to get "punk-dingo.v1": Get https://10.96.0.1:443/api/v1/namespaces/kube-system/configmaps/punk-dingo.v1: dial tcp 10.96.0.1:443: i/o timeout
[tiller] 2018/08/21 23:56:23 info: generated name punk-dingo is taken. Searching again.
[storage] 2018/08/21 23:56:23 getting release "alternating-maltese.v1"
[storage/driver] 2018/08/21 23:56:53 get: failed to get "alternating-maltese.v1": Get https://10.96.0.1:443/api/v1/namespaces/kube-system/configmaps/alternating-maltese.v1: dial tcp 10.96.0.1:443: i/o timeout
[tiller] 2018/08/21 23:56:53 info: generated name alternating-maltese is taken. Searching again.
[storage] 2018/08/21 23:56:53 getting release "laughing-warthog.v1"
[storage/driver] 2018/08/21 23:57:23 get: failed to get "laughing-warthog.v1": Get https://10.96.0.1:443/api/v1/namespaces/kube-system/configmaps/laughing-warthog.v1: dial tcp 10.96.0.1:443: i/o timeout
[tiller] 2018/08/21 23:57:23 info: generated name laughing-warthog is taken. Searching again.
[tiller] 2018/08/21 23:57:23 warning: No available release names found after 5 tries
[tiller] 2018/08/21 23:57:23 failed install prepare step: no available release name found
```

**Comment by zwhitchcox** [comment]
It looks like it's timing out on the request, which makes sense, because some of them time out, and others just hang for a while

**Comment by zwhitchcox** [comment]
So, I actually created a repo where you can use my exact environment, because I'm creating a script (WIP) that automates the process as I go. You can use my exact same environment here: https://gitlab.com/zwhitchcox/do

**Comment by bacongobbler** [comment]
yes, judging by a few other tickets in the queue that reference switching to calico worked for them. https://github.com/helm/helm/issues/3447

**Comment by zwhitchcox** [comment]
Ok, working on that

**Comment by zwhitchcox** [comment]
Yeah, changing to calico didn't even work

**Comment by zwhitchcox** [comment]
Oh, nevermind, just had it misconfigured!!! THANK YOU SO MUCH

**Comment by zwhitchcox** [comment]
If anyone else runs into the same problem as me, this is the solution:

Remove flannel,

installl calico with the following command:

```
kubectl apply -f https://docs.projectcalico.org/v3.2/getting-started/kubernetes/installation/hosted/etcd.yaml
kubectl apply -f https://docs.projectcalico.org/v3.2/getting-started/kubernetes/installation/rbac.yaml
kubectl apply -f https://docs.projectcalico.org/v3.2/getting-started/kubernetes/installation/hosted/calico.yaml
```

**Comment by vipul-gupta13** [comment]
I am facing the same issue, but none of the mentioned solution is working for me.

I have tried almost all the solutions from [3055](https://github.com/helm/helm/issues/3055) and also installed calico as mentioned in this ticket. 

But nothing seems to work.

helm version:
`$ helm version
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
`

kubectl version
`$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
`

**Comment by vipul-gupta13** [comment]
My above issue got resolved by following the comment in this issue [2464-comment](https://github.com/helm/helm/issues/2464#issuecomment-381229646)

Now "helm install " and "helm list" are working fine.

**Comment by kodelint** [comment]
I found this artical which helped me to resolve the same situation with `minikube` and `helm` setup [easily-install-uninstall-helm-on-rbac-kubernetes](https://medium.com/@pczarkowski/easily-install-uninstall-helm-on-rbac-kubernetes-8c3c0e22d0d7)
**Delete Tiller**
```
 kubectl -n kube-system delete deployment tiller-deploy
 kubectl delete clusterrolebinding tiller
 kubectl -n kube-system delete serviceaccount tiller
```
**Reinstall with RBAC**
```
 kubectl -n kube-system create serviceaccount tiller
 kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller
 helm init --service-account=tiller
```

**Comment by markserrano915** [comment]
> I found this artical which helped me to resolve the same situation with `minikube` and `helm` setup [easily-install-uninstall-helm-on-rbac-kubernetes](https://medium.com/@pczarkowski/easily-install-uninstall-helm-on-rbac-kubernetes-8c3c0e22d0d7)
> **Delete Tiller**
> 
> ```
>  kubectl -n kube-system delete deployment tiller-deploy
>  kubectl delete clusterrolebinding tiller
>  kubectl -n kube-system delete serviceaccount tiller
> ```
> **Reinstall with RBAC**
> 
> ```
>  kubectl -n kube-system create serviceaccount tiller
>  kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller
>  helm init --service-account=tiller
> ```

This worked for me in DigitalOcean.
