### ISSUE TITLE
helm index.yaml with multiple repos

### ISSUE THREAD

**Issue by soma15184** [helm/helm#4507]
how do i create index.yaml with multiple repos.
each repo has its own helm charts, however i want to create one consolidated index.yaml at root repo

any input appreciated.

**Comment by jascott1** [comment]
Hi @soma15184 

This is not my area of expertise but the index.yaml represents the charts available on _that_ repo. Your client has access to multiple repos with each having their own index.yaml. Perhaps you can explain more about what you are trying to accomplish?

**Comment by bacongobbler** [comment]
Hey @soma15184, because this ticket has been waiting on input for a while it's since gone stale. Because of that, I'm going to close this as inactive, but please feel free to re-open when you have more information to share. Thanks!
