### ISSUE TITLE
Setting arrays of maps with --set

### ISSUE THREAD

**Issue by boosh** [helm/helm#4508]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-12T00:45:05Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  Minikube/any

I've got a similar issue as in #1987 which was closed. I keep coming across charts where I need to set lists of maps on the command line, generally to configure TLS ingresses. E.g. [Keycloak](https://github.com/helm/charts/blob/master/stable/keycloak/values.yaml):
```
  ingress:
    tls: []
    # - hosts:
    #     - keycloak.example.com
#   secretName: tls-keycloak
```
How can these be set on the command line? I need to dynamically set the host name depending on my environment but so far can't find a way to do it. I don't want to have to create a `values-<env>.yaml` file for every environment I install in because apart from this most settings can be set on the command line and I want my charts to be portable (e.g. use the same chart for multiple clients, with the domain name parameterised).

I've tried all of the following but they all fail:
```
helm lint --set keycloak.tls.hosts={keycloak.localhost}
helm lint --set keycloak.tls[0].hosts={keycloak.localhost}
helm lint --set keycloak.tls={hosts={keycloak.localhost}}
```

This is quite a common requirement, specifically to dynamically configure ingress TLS. Is it possible to do this? If not, please add it.

Thanks

**Comment by moikot** [comment]
How about this:
helm lint --set keycloak.tls[0].hosts[0]=keycloak.localhost ?

**Comment by boosh** [comment]
No, I get the same error:
```
panic: interface conversion: interface {} is map[string]interface {}, not []interface {}

goroutine 1 [running]:
k8s.io/helm/pkg/strvals.(*parser).key(0xc4201b4860, 0xc420432780, 0xc4209f9278, 0x7) ... (truncated)
```

**Comment by jascott1** [comment]
Hi @boosh 

Looking at the values file, you are missing `ingress` key in your set path. So it would be more like `keycloak.ingress.tls[0].hosts[0]` or similar.

**Comment by idursun** [comment]
@boosh If you are using `zsh`, then you need to escape square brackets like `\[0\]`.
