### ISSUE TITLE
Update package names

### ISSUE THREAD

**Issue by krancour** [helm/helm#451]
Since Go packages are referenced by their URL in source control, the renaming of this repository (see #449) will require packages to be renamed as well.

IMO, packages should be renamed _first_.  This will ultimately result in packages, locally, residing in a home on the `$GOPATH` (e.g. `$GOPATH/src/github.com/helm/helm`) that does _not_ correctly match package names (e.g. `github.com/helm/helm-classic/...`).

The two best options for getting around this are:

1. Pro-actively rename the local repository (e.g. to `$GOPATH/src/github.com/helm/helm-classic`).
2. Use a containerized dev environment.  (See #445.)  The containerized dev environment mounts the local repository into the _correct_ location on the container's `$GOPATH` and the path to the repository on the system hosting the container ends up being irrelevant.

**Comment by kmala** [comment]
if we are need to go with option 2 i think we are making docker a requirement for building helm.should we be doing that?

**Comment by krancour** [comment]
@kmala there was some discussion on it in the original issue #397.  Note that the way #445 has been implemented, a containerized build is an _option_.  A non-containerized build should still be possible.

**Comment by kmala** [comment]
if its an option means we have to go with the first way right?

**Comment by krancour** [comment]
I prefer the second way personally, but it's not merged yet.  At the end of the day, it doesn't matter which approach is used.  We can both use whichever approach we prefer.  I only mentioned the options because the moment we start renaming packages, things wouldn't be compiling unless we take some further action in the form of one of the two suggestions.

**Comment by krancour** [comment]
Altho, it's also possible that renaming packages affects not just compiling locally, but also in Travis.

Options there would be:

1. We go ahead and rename this repo sooner rather than later.
2. Use the containerized build.
