### ISSUE TITLE
Error: could not find a ready tiller pod

### ISSUE THREAD

**Issue by matheus666matheus** [helm/helm#4510]
*Output of `helm version`:*

Client: &version.Version{SemVer:"v2.10.0-rc.3", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}

*Output of `kubectl version`:*

Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

*OS version:*

CentOS 7.4

*Issue:*

My tiller pod is pending forever:

NAME                                           READY     STATUS    RESTARTS   AGE
tiller-deploy-6fd7f5b55-vm4rj                  0/1       Pending   0          18m

There is no log in the pod...and I can't figure it out how to debug it...

**Comment by matheus666matheus** [comment]
I found this: 

**● kubelet.service - kubelet: The Kubernetes Node Agent**
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: active (running) since Qua 2018-08-22 16:24:46 -03; 1h 0min ago
     Docs: https://kubernetes.io/docs/
 Main PID: 5424 (kubelet)
   CGroup: /system.slice/kubelet.service
           └─5424 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --cgroup-driver=systemd --cni-bin-dir=/opt/cni/bin --cni-conf-dir=/etc/cni/net.d --network-plugin=cni

Ago 22 17:24:51 s3797.corenmg.gov.br kubelet[5424]: E0822 17:24:51.845317    5424 summary.go:102] Failed to get system container stats for "/system.slice/kubelet.service": failed to get cgroup stats for "/system.slice/kubelet.service": failed to get container info for "/system.slice/kubelet.service": unknown container "/system.slice/kubelet.service"
Ago 22 17:24:51 s3797.corenmg.gov.br kubelet[5424]: E0822 17:24:51.845352    5424 summary.go:102] Failed to get system container stats for "/system.slice/docker.service": failed to get cgroup stats for "/system.slice/docker.service": failed to get container info for "/system.slice/docker.service": unknown container "/system.slice/docker.service"
Ago 22 17:25:01 s3797.corenmg.gov.br kubelet[5424]: E0822 17:25:01.865406    5424 summary.go:102] Failed to get system container stats for "/system.slice/kubelet.service": failed to get cgroup stats for "/system.slice/kubelet.service": failed to get container info for "/system.slice/kubelet.service": unknown container "/system.slice/kubelet.service"
Ago 22 17:25:01 s3797.corenmg.gov.br kubelet[5424]: E0822 17:25:01.865448    5424 summary.go:102] Failed to get system container stats for "/system.slice/docker.service": failed to get cgroup stats for "/system.slice/docker.service": failed to get container info for "/system.slice/docker.service": unknown container "/system.slice/docker.service"
Ago 22 17:25:11 s3797.corenmg.gov.br kubelet[5424]: E0822 17:25:11.883351    5424 summary.go:102] Failed to get system container stats for "/system.slice/docker.service": failed to get cgroup stats for "/system.slice/docker.service": failed to get container info for "/system.slice/docker.service": unknown container "/system.slice/docker.service"
Ago 22 17:25:11 s3797.corenmg.gov.br kubelet[5424]: E0822 17:25:11.885240    5424 summary.go:102] Failed to get system container stats for "/system.slice/kubelet.service": failed to get cgroup stats for "/system.slice/kubelet.service": failed to get container info for "/system.slice/kubelet.service": unknown container "/system.slice/kubelet.service"
Ago 22 17:25:21 s3797.corenmg.gov.br kubelet[5424]: E0822 17:25:21.899992    5424 summary.go:102] Failed to get system container stats for "/system.slice/docker.service": failed to get cgroup stats for "/system.slice/docker.service": failed to get container info for "/system.slice/docker.service": unknown container "/system.slice/docker.service"
Ago 22 17:25:21 s3797.corenmg.gov.br kubelet[5424]: E0822 17:25:21.900900    5424 summary.go:102] Failed to get system container stats for "/system.slice/kubelet.service": failed to get cgroup stats for "/system.slice/kubelet.service": failed to get container info for "/system.slice/kubelet.service": unknown container "/system.slice/kubelet.service"
Ago 22 17:25:31 s3797.corenmg.gov.br kubelet[5424]: E0822 17:25:31.917327    5424 summary.go:102] Failed to get system container stats for "/system.slice/kubelet.service": failed to get cgroup stats for "/system.slice/kubelet.service": failed to get container info for "/system.slice/kubelet.service": unknown container "/system.slice/kubelet.service"
Ago 22 17:25:31 s3797.corenmg.gov.br kubelet[5424]: E0822 17:25:31.917367    5424 summary.go:102] Failed to get system container stats for "/system.slice/docker.service": failed to get cgroup stats for "/system.slice/docker.service": failed to get container info for "/system.slice/docker.service": unknown container "/system.slice/docker.service"

**Comment by bacongobbler** [comment]
is that node operational?

**Comment by matheus666matheus** [comment]
The messages in log seems to be related with https://github.com/kubernetes/kubernetes/issues/56850#issue-279360383

**Comment by KiranTotad** [comment]
Try this command, tiller pod came to running state when i executed this command.
kubectl taint nodes --all node-role.kubernetes.io/master-

**Comment by loganxavier** [comment]
Having the same error on a fresh machine, opened a question about [here](https://serverfault.com/questions/958912/helm-under-microk8s-giving-error-could-not-find-a-ready-tiller-pod).
