### ISSUE TITLE
What is mean by "destination for annotations is a table. Ignoring non-table value"

### ISSUE THREAD

**Issue by gkarthiks** [helm/helm#4514]
I have a global values.yaml and dependency charts. When I execute, I am getting the following warning message. What does this mean

> destination for annotations is a table. Ignoring non-table value

**Comment by bacongobbler** [comment]
source ref: https://github.com/helm/helm/blob/7cad59091a9451b2aa4f95aa882ea27e6b195f98/pkg/chartutil/values.go#L323-L325

**Comment by philovivero** [comment]
What was the resolution here? What happens if !ok?

**Comment by StianOvrevage** [comment]
I get these warnings(?) as well but it seems to work but it would be nice to get rid of the warnings somehow.

**Comment by hullarb** [comment]
I think table means map in context of yaml and golang.
I had these warnings when in a chart a field had null as default value and in the values it was substituted with a map.  Changing null to empty map `{}` eliminated the warning.

**Comment by bzumby** [comment]
@hullarb damn right! thanks

**Comment by SimonHarrisonSH** [comment]
> I think table means map in context of yaml and golang.
> I had these warnings when in a chart a field had null as default value and in the values it was substituted with a map. Changing null to empty map `{}` eliminated the warning.

Interesting, an empty list works for me, and empty map, yields a similar error.
