### ISSUE TITLE
get-script does not work when used with --version v2.10.0

### ISSUE THREAD

**Issue by broeser** [helm/helm#4521]
Hi there,

I use the get-script to install helm, in this fashion:

curl https://raw.githubusercontent.com/kubernetes/helm/v2.10.0/scripts/get > get_helm.sh
chmod 700 get_helm.sh
./get_helm.sh

The script has a --version parameter, which according to documentation can be set to a specific helm version or to latest (which is the default). The following works fine:
./get_helm.sh --version v2.9.0

However, when using the currently released version v2.10.0, I get an error message (and in general: pretty weird output mentioning a version v2.15.0?)

./get_helm.sh --version latest
or
./get_helm.sh --version v2.10.0

results in this error message:

Helm v2.10.0
v2.15.0 is available. Changing from version v2.10.0.
Downloading https://kubernetes-helm.storage.googleapis.com/helm-v2.10.0
v2.15.0-linux-amd64.tar.gz
curl: (3) Illegal characters found in URL
Failed to install helm with the arguments provided: --version v2.10.0
Accepted cli arguments are:
        [--help|-h ] ->> prints this help
        [--version|-v <desired_version>] . When not defined it defaults to latest
        e.g. --version v2.4.0  or -v latest
        For support, go to https://github.com/helm/helm.

**Comment by broeser** [comment]
Some additional details:
The same issue occurs when retrieving the script from
https://raw.githubusercontent.com/kubernetes/helm/release-2.10/scripts/get
But the problem does not occur when retrieving the script from the master branch.
However, I wanted to make sure that the install script is compatible to the helm version I am trying to install, therefore I want to use the tagged version of the script.

**Comment by danielballan** [comment]
I am seeing the same issue. It occurs for tags `v2.9.1` and `v2.10.0` but not on `master`:

Failure with `v2.9.1`:
```
$ curl https://raw.githubusercontent.com/kubernetes/helm/v2.9.1/scripts/get | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6737  100  6737    0     0  45413      0 --:--:-- --:--:-- --:--:-- 45520
Downloading https://kubernetes-helm.storage.googleapis.com/helm-v2.10.0
v2.15.0-linux-amd64.tar.gz
curl: (3) Illegal characters found in URL
Failed to install helm
	For support, go to https://github.com/kubernetes/helm.
```

Failure with `v2.10.0`:
```
$ curl https://raw.githubusercontent.com/kubernetes/helm/v2.10.0/scripts/get | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6685  100  6685    0     0  56976      0 --:--:-- --:--:-- --:--:-- 57136
Downloading https://kubernetes-helm.storage.googleapis.com/helm-v2.10.0
v2.15.0-linux-amd64.tar.gz
curl: (3) Illegal characters found in URL
Failed to install helm
	For support, go to https://github.com/helm/helm.
```

Success with `master`:
```
$ curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6709  100  6709    0     0  70118      0 --:--:-- --:--:-- --:--:-- 71372
Downloading https://kubernetes-helm.storage.googleapis.com/helm-v2.10.0-linux-amd64.tar.gz
Preparing to install into /usr/local/bin
```

**Comment by bacongobbler** [comment]
There was a bug with the script which was fixed in master. https://github.com/helm/helm/pull/4484 was the fix. Please use the master branch for the get-script moving forward. Thanks! :)

**Comment by danielballan** [comment]
Thanks for your prompt and friendly support, @bacongobbler!

**Comment by karthirm** [comment]
Can someone please tell me the command to install helm in windows ? Do i need to have any prerequisites like kubernetes or something else, please let me know. 

Reason why I want helm is to manually push property files (config maps) into Openshift server as our CI/CD pipeline is not yet ready for our current project. 

I installed helm and the folder contains below, added it to the environmental variables path as well 
![image](https://user-images.githubusercontent.com/41341795/97301731-258ee600-187e-11eb-9275-f60edd6b4f37.png)

![image](https://user-images.githubusercontent.com/41341795/97301674-10b25280-187e-11eb-823c-9db0c19bc53f.png)
