### ISSUE TITLE
helm starter <CHARTNAME> not replaced in all files

### ISSUE THREAD

**Issue by antonosmond** [helm/helm#4525]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```
The docs [here](https://docs.helm.sh/developing_charts/#chart-starter-packs) clearly state that 

> All occurrences of \<CHARTNAME> will be replaced

However that does not appear to be the case. Helm allows a user to specify multiple values files. In my helm starter (which I'm creating for internal use at my company), I have the following 3 files (in the project root):
- values.yaml
- values-staging.yaml
- values-production.yaml

When executing `helm create -p myStarter myChart`, `<CHARTNAME>` is replaced in values.yaml (as I'd expect) however it's NOT replaced in either of the other values files.
I also found that renaming values.yaml to values.yml caused it not be replaced and also found [this issue](https://github.com/helm/helm/issues/4058) before posting stating it's not replaced in dot files either.
I can see how replacing in files outside of the templates dir could be problematic (e.g. .git dir) but couldn't it at least replace in all yaml files in the root or something? At the very least we should update the docs to be clear about where `<CHARTNAME>` is and isn't replaced.

**Comment by dkirrane** [comment]
I also noticed that starter variables defined in `_helpers.tpl` are not replaced as per best practice.
https://docs.helm.sh/chart_best_practices/#names-of-defined-templates

**Comment by bartlettt** [comment]
I know I'm necro'ing a 2 year old issue, but is the official stance still the same? I also use the multiple values files pattern, and the inconsistent templating is frustrating. Should template rules not apply to all files regardless of name or location?

**Comment by bacongobbler** [comment]
yes, the official stance is still the same. Please feel free to work on a patch if this is important for your use case.

**Comment by bridgetkromhout** [comment]
Hi, folks - we now have a path forward for proposals: if you're reading this and thinking "but this should happen!", please file a [Helm Improvement Proposal](https://github.com/helm/community/blob/master/hips/hip-0001.md) to discuss it with the community (or send a pull request if you'd like to implement it). Meanwhile, I'm closing this issue as inactive.
