### ISSUE TITLE
Helm installtion error - Ubuntu 16.0.4 - virtual box

### ISSUE THREAD

**Issue by RajSelv** [helm/helm#4526]
Hi,
  I am trying to install helm on my Ubuntu machine running over Virtual box, during the process i end up with error as follow ,
Would be nice if someone can share your thoughts for resolution !
raja@raja-VirtualBox:~$ sudo snap install helm
[sudo] password for raja:
error: cannot communicate with server: Post http://localhost/v2/snaps/helm: dial unix /run/snapd.socket: connect: connection refused

Output of `helm version`:
raja@raja-VirtualBox:~$ apt list snapd -a
Listing... Done
snapd/bionic-updates,now 2.34.2+18.04 amd64 [installed]
snapd/bionic 2.32.5+18.04 amd64

raja@raja-VirtualBox:~$ snap version
snap    2.34.2+18.04
snapd   unavailable
series  -
raja@raja-VirtualBox:~$ helm version

Output of `kubectl version`:
raja@raja-VirtualBox:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:04:08Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS

**Comment by jascott1** [comment]
Hi @RajSelv 

This appears to be a local problem with Snap.
`error: cannot communicate with server: Post http://localhost/v2/snaps/helm: dial unix `
Have you tried asking in Snap issue queue? If I am mistaken please elaborate on why you think this is a Helm issue. Thanks!

**Comment by RajSelv** [comment]
Hello.

   I am not familiar with neither snap nor helm, what am trying to do here is to install helm on my Ubuntu machine.
Will be good if I can get some help here.

Br,
  Raj
  Digia Oy, Helsinki
  rajasekar.selvaraj@digia.com

**Comment by bacongobbler** [comment]
If you're having trouble with the snap package you can try installing from the releases page as described in the docs. Give that a shot :)

https://github.com/helm/helm/blob/master/docs/install.md#from-the-binary-releases

**Comment by bacongobbler** [comment]
hey @RajSelv, were you able to install Helm? Can we go ahead and close this issue?

**Comment by RajSelv** [comment]
Hei,

     Yes i could able to install Helm, hence this can be closed, Thanks

Br,
  Raj
  Digia Oy, Helsinki
  rajasekar.selvaraj@digia.com
