### ISSUE TITLE
Helm Documentation is broken

### ISSUE THREAD

**Issue by asridharan** [helm/helm#4532]
Output of `helm version`:

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

This is documentation bug.

Looks like none of links in the Quick start guide work. I was looking for links to "Install Helm" and none of the links the documentation page, quick start guide work. I was accessing the Documentation page through Chrome, so not sure if this is Chrome issue vs the Documentation links itself are broken.

For example all these URLs:

https://docs.helm.sh/using_helm/#installing-helm

https://docs.helm.sh/using_helm/#kubernetes-distribution-guide

https://docs.helm.sh/using_helm/#using-ssl-between-helm-and-tiller

All of them seem to just point to:
https://docs.helm.sh/using_helm/#using-helm

**Comment by Dean-Coakley** [comment]
@asridharan Looks fixed to me unless I'm misunderstanding?
