### ISSUE TITLE
RFC: an apparatus to execute a template in a subchart's scope

### ISSUE THREAD

**Issue by intelfx** [helm/helm#4535]
There seems to be a popular demand ([SO#47791971](https://stackoverflow.com/questions/47791971/how-can-you-call-a-helm-helper-template-from-a-subchart-with-the-correct-conte), #4314, #2133 if you de-X-Y it, and some other issues I forgot IDs of) to pass computed values from subcharts to parent charts. Indeed, the use-case is obvious: if we have a chart that depends on a subchart that adheres to the current best practice of scoping its resource names with release name (e. g. the community-maintained [`redis`](https://github.com/helm/charts/tree/master/stable/redis) chart), we quickly run into a problem of referring to the subchart's resources (e. g. services) by their (dynamically generated) names.

Continuing with the redis example, the [redis master service](https://github.com/helm/charts/blob/master/stable/redis/templates/redis-master-svc.yaml#L4) has a name of `{{ template "redis.fullname" . }}-master`, where the [`redis.fullname`](https://github.com/helm/charts/blob/master/stable/redis/templates/_helpers.tpl#L21) template is 11 lines of logic.

* We could merely copy that template into the main chart, adjusting it to run from the parent scope, but this is a glaring violation of DRY and is prone to breakage so we won't do that.
* We could set up a `redis.fullnameOverride` in our `values.yaml`, but if we do this, we won't be able to scope the fullname with the release name (because `values.yaml` is not templateable and will never be), thus breaking the best practice.
* Neither we can simply call it from the parent chart because the `.` of the parent chart is different (e. g. `Chart.Name` is not `redis` anymore).

Therefore, I propose a middle-ground solution: the dot object (`.`) will gain a new key, e. g. `Subcharts`, whose value will be a dictionary containing subcharts' dot objects, keyed by the subcharts' names relative to this chart.

With this change, we will be able to compute a subchart's service name from the parent chart by invoking as follows:
```
{{ template "redis.fullname" .Subcharts.redis }}-master
```

**Comment by intelfx** [comment]
For anyone looking an interim solution, I wrote a meta-template that calls another template in a subchart's ersatz-scope by synthesizing a dot-object. It is **incomplete** (e. g. `.Chart` lacks any fields except `Name`, there is no `.Files` because doing it properly means rescoping to the subchart's directory and I never bothered to do it) but it works for common helper templates:

```
{{- define "call-nested" -}}                                                                                                                                                                                                     
{{- include .Template (dict "Chart" (dict "Name" .Subchart) "Values" (index .Dot.Values .Subchart) "Release" .Dot.Release "Capabilities" .Dot.Capabilities) -}}                                                                            
{{- end -}}
```

Usage:
```
{{ include "call-nested" (dict "Template" "redis.fullname" "Subchart" "redis" "Dot" .) }}
```

**Comment by sebastien-prudhomme** [comment]
@intelfx do you thing a generic hack with more deeper subchart is possible?

**Comment by ariep** [comment]
This isssue is the same as #3920 .

**Comment by bacongobbler** [comment]
Thank you for pointing out the duplicate. Closing in favour of that

**Comment by SailingYYC** [comment]
@intelfx, to support multiple levels of sub-charts:
```
{{- define "call-nested" }}
{{- $dot := index . 0 }}
{{- $subchart := index . 1 | splitList "." }}
{{- $template := index . 2 }}
{{- $values := $dot.Values }}
{{- range $subchart }}
{{- $values = index $values . }}
{{- end }}
{{- include $template (dict "Chart" (dict "Name" (last $subchart)) "Values" $values "Release" $dot.Release "Capabilities" $dot.Capabilities) }}
{{- end }}
```

**Comment by sc250024** [comment]
Anyone tested that same command in Helm 3 ? I get an errors when trying to run `helm lint` against charts that worked previously using the method above:

```
Error: 1 chart(s) linted, 1 chart(s) failed
walk.go:74: found symbolic link in path: /path/to/my/chart/linter_values.yaml resolves to /path/to/my/chart/ci/default-values.yaml
==> Linting /path/to/my/chart
[ERROR] templates/: template: mychart/templates/some-template.yaml:135:35: executing "mychart/templates/some-template.yaml" at <include "distributed.server.deployment" .>: error calling include: template: mychart/templates/some-template.yaml:80:36: executing "distributed.server.deployment" at <include "mychart.deployment" .>: error calling include: template: mychart/templates/some-template.yaml:24:20: executing "mychart.deployment" at <include "mychart.subchart.endpoint" .>: error calling include: template: mychart/templates/_helper-endpoints.tpl:6:3: executing "mychart.subchart.endpoint" at <include "call-nested" (list . "subchart" "fullname")>: error calling include: template: mychart/templates/_helper.tpl:15:4: executing "call-nested" at <include $template (dict "Chart" (dict "Name" (last $subchart)) "Values" $values "Release" $dot.Release "Capabilities" $dot.Capabilities)>: error calling include: template: no template "fullname" associated with template "gotpl"
```

**Comment by Anticom** [comment]
Hi folks, I'm facing the same issue. How the $!§# did the guys over at bitnami do this?

For example their [`bitnami/mongodb`](https://github.com/bitnami/charts/tree/master/bitnami/mongodb) chart [declares a dependency](https://github.com/bitnami/charts/blob/master/bitnami/mongodb/requirements.yaml#L2-L6) to [`bitnami/common`](https://github.com/bitnami/charts/tree/master/bitnami/common). Then they're simply able to [include a definition](https://github.com/bitnami/charts/blob/master/bitnami/mongodb/templates/_helpers.tpl#L15) from the `common` subchart chart found [here](https://github.com/bitnami/charts/blob/master/bitnami/common/templates/_names.tpl#L21-L32).

Can someone explain how they're able to do this?

**Comment by TBBle** [comment]
@Anticom: Bitnami isn't doing anything special. In that case, the `common.names.fullname` is evaluated in the scope of the _mongodb_ chart, so `.Chart.Name` is ["mongodb"](https://github.com/bitnami/charts/blob/master/bitnami/mongodb/Chart.yaml). This ticket was to allow executing a named template is the scope of a _subchart_. In the Bitnami case, this feature would allow you to get `.Chart.Name` in `common.names.fullname` to evaluate as ["common"](https://github.com/bitnami/charts/blob/master/bitnami/common/Chart.yaml), even when called from MongoDB.

The current workaround would be using `call-nested` above instead of `include "common.names.fullname" .`, i.e.,
```
{{- include "call-nested" common "common.names.fullname" . -}}
```

**Comment by sass1997** [comment]
Since this PR: https://github.com/helm/helm/pull/9957

You can define inlcudes in your parent chart like you do in the Subchart but you add the context of your Subchart
`{{- include "keycloak.labels" .Subcharts.keycloak | nindent 4 }}`
For the ones who are struggling with subchart names with dashes like me here is an example how you can solve it
{{- include "nginx-ingress.labels" (index .Subcharts "nginx-ingress") | nindent 4 }}
