### ISSUE TITLE
helm list command doesn't sort by chart name

### ISSUE THREAD

**Issue by spoortiprabhu** [helm/helm#4538]
As the documentation says, helm by default sort by release name and lists only releases that are deployed or failed.

Since there is no option available to sort by chart name. It will be better if there is any attribute which will sort by chart name for example, --sort-by-chart, --chart <chart_name>

Command:
[root@test ~]# helm list
NAME            REVISION        UPDATED                         STATUS          CHART           NAMESPACE
whimsical-fly   1               Mon Aug 27 18:26:09 2018        DEPLOYED        kibana-0.11.0   default

Output of `helm version`:
[root@test ~]# helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

Output of `kubectl version`:
[root@test ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Kubeadm

**Comment by itowlson** [comment]
I think #4340 addresses this.

**Comment by bacongobbler** [comment]
Thanks @itowlson! Yes that was definitely addressed in #4340, which is available in the canary releases and will be out for the 2.11 release. Thanks!
