### ISSUE TITLE
install tiller in isolated/offline environment

### ISSUE THREAD

**Issue by delubi** [helm/helm#4540]
Is there a way to install tiller (helm server) to an isolated kubernetes environment? By isolated I mean there is no connection to Internet from the place where I run kubectl.

I can download an offline copy of helm client and install. But when I ran helm init it gave:

# helm init
Creating /root/.helm
Creating /root/.helm/repository
Creating /root/.helm/repository/cache
Creating /root/.helm/repository/local
Creating /root/.helm/plugins
Creating /root/.helm/starters
Creating /root/.helm/cache/archive
Creating /root/.helm/repository/repositories.yaml
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com
Error: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Get https://kubernetes-charts.storage.googleapis.com/index.yaml: dial tcp: lookup kubernetes-charts.storage.googleapis.com on 10.69.0.153:53: server misbehaving

# kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.11", GitCommit:"1df6a8381669a6c753f79cb31ca2e3d57ee7c8a3", GitTreeState:"clean", BuildDate:"2018-04-05T17:24:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.11-docker-8d637ae", GitCommit:"8d637aedf46b9c21dde723e29c645b9f27106fa5", GitTreeState:"clean", BuildDate:"2018-04-26T16:51:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

Thanks,
Forrest

**Comment by jascott1** [comment]
Hi @delubi 

Offline installation is not explicitly supported but you could try pulling the Tiller image on the cluster first and then installing locally with `helm init -c` for client only. I am not sure this will work but might get you on the right track if you need to solve this.

**Comment by bacongobbler** [comment]
I'd also add `--skip-refresh` to @jascott1's suggestion. That way, helm will not pull down the latest index files from the repositories (which is likely the cause of the error you're seeing).

**Comment by delubi** [comment]
@jascott1 @bacongobbler Thank you both. I've got tiller running on the cluster. Will close the issue.

Forrest

**Comment by Amit-Thawait** [comment]
I wanted to do that same, however all the steps were not listed here, hence listing it down so that others trying to do this can get help.

    helm install --client-only --skip-refresh

This step will install helm locally and not install tiller.

Next step is to upload tiller image to your docker registry tiller image: gcr.io/kubernetes-helm/tiller:v2.11.0

If you don't have a private docker registry set yet, alternatively you can also copy the tiller docker image to all the nodes.

Tiller image's tag depends on the version of helm you are installing. In my case, I was installing helm 2.11.0

Next you need to do

    helm init

This will install tiller in one of the nodes.

Next you need to create a service account for your tiller pod and assign it cluster-admin role :

Create a file rbac_service_account.yaml with below content

    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: tiller
      namespace: kube-system
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: tiller
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: cluster-admin
    subjects:
      - kind: ServiceAccount
        name: tiller
        namespace: kube-system

Next you need to just apply the service account and upgrade tiller pod.

    kubectl apply -f rbac_service_account.yaml

    helm init --service-account tiller --upgrade

**Comment by yijia2413** [comment]
@Amit-Thawait 
change last line to 
```bash
helm init --service-account tiller --upgrade --tiller-image gcr.io/kubernetes-helm/tiller:v2.11.0
```
will be better, otherwise it will pull images with others tags.

following are the logs ...
```
[root@node1 heml]# kubectl get pod -n kube-system|grep tiller
tiller-deploy-8568fc486f-mlp4t         0/1     ErrImagePull   0          37s

[root@node1 heml]# helm init --service-account tiller --upgrade --tiller-image gcr.io/kubernetes-helm/tiller:v2.11.0
$HELM_HOME has been configured at /root/.helm.

Tiller (the Helm server-side component) has been upgraded to the current version.
Happy Helming!
[root@node1 heml]# kubectl get pod -n kube-system|grep tiller
tiller-deploy-59b99695d8-gxhbb         1/1     Running   0          12s

```

**Comment by Amit-Thawait** [comment]
@yijia2413 Sure Yijia.

In my case I was having only one tiller image in my nodes, hence I never got that issue.

Thanks. I have updated my comment.

**Comment by vishalk663** [comment]
> @jascott1 @bacongobbler Thank you both. I've got tiller running on the cluster. Will close the issue.
> 
> Forrest

**Comment by vishalk663** [comment]
@jascott1 @bacongobbler thanks. tiller is installed in my k8-cluster
