### ISSUE TITLE
helm upgrade command with parameter --namespace doesn't upgrade the namespace

### ISSUE THREAD

**Issue by spoortiprabhu** [helm/helm#4545]
helm upgrade command doesn't upgrade the namespaces but successful message is displayed.

[root@test ~]# helm ls
NAME            REVISION        UPDATED                         STATUS          CHART           NAMESPACE
coy-owl         2               Tue Aug 28 12:29:08 2018        DEPLOYED        mariadb-4.4.0   default
dinky-horse     1               Tue Aug 28 12:00:48 2018        DEPLOYED        kibana-0.11.0   default
ideal-garfish   1               Tue Aug 28 11:29:32 2018        DEPLOYED        kibana-0.11.0   default
new-namespace   1               Tue Aug 28 13:25:03 2018        DEPLOYED        mysql-0.10.0    default
osw-namespace   1               Tue Aug 28 13:29:41 2018        DEPLOYED        mysql-0.10.0    osw
ryan-namespace  4               Tue Aug 28 13:23:58 2018        DEPLOYED        mysql-0.10.0    ryan-namespace

[root@test ~]# helm upgrade ryan-namespace stable/mysql --namespace default
Release "ryan-namespace" has been upgraded. Happy Helming!

[root@test ~]# helm ls
NAME            REVISION        UPDATED                         STATUS          CHART           NAMESPACE
coy-owl         2               Tue Aug 28 12:29:08 2018        DEPLOYED        mariadb-4.4.0   default
dinky-horse     1               Tue Aug 28 12:00:48 2018        DEPLOYED        kibana-0.11.0   default
ideal-garfish   1               Tue Aug 28 11:29:32 2018        DEPLOYED        kibana-0.11.0   default
new-namespace   1               Tue Aug 28 13:25:03 2018        DEPLOYED        mysql-0.10.0    default
osw-namespace   1               Tue Aug 28 13:29:41 2018        DEPLOYED        mysql-0.10.0    osw
ryan-namespace  5               Tue Aug 28 14:27:32 2018        DEPLOYED        mysql-0.10.0    ryan-namespace

Output of `helm version`:
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): kubeadm

**Comment by jascott1** [comment]
Hi @spoortiprabhu 

Im not sure we support what you are trying to accomplish. Is there a kubectl equivalent for moving to another namespace?

**Comment by spoortiprabhu** [comment]
@jascott1 Hi, In kubectl there is no command where we can move from one namespace to another. But in helm upgrade --namespace parameter described as "namespace to install the release into".

**Comment by jascott1** [comment]
@spoortiprabhu Please see the rest of the description `namespace to install the release into (only used if --install is set). Defaults to the current kube config namespace`.

**Comment by jascott1** [comment]
Hi @spoortiprabhu Did you get your issue resolved? I should have emphasized that its for determining what namespace to install into but will not migrate into a new namespace.

**Comment by akamdarChewy** [comment]
This issue still exists as is. 
We're using 
Client:v2.12.3
Server:.v2.13.0

**Comment by bacongobbler** [comment]
[as noted earlier](https://github.com/helm/helm/issues/4545#issuecomment-417038930), this is intended by design. It's only meant to be used in tandem with the `--install` flag to ensure it is installed into a particular namespace the first time a release is installed, not to migrate a release from one namespace to another.
