### ISSUE TITLE
Compute the values based on user input and manage the helm chart of percona-xtradb chart in file/node.cnf file

### ISSUE THREAD

**Issue by iambhanuteja** [helm/helm#4551]
In Values.yaml file cpu and mem limits/requests are declared as below. 
cpurequest: 100m
memrequest: 256Mi
cpulimit: 200m
memlimit: 512Mi

In statefulset.yaml file i am calling them as below.
resources:
   limits:
      cpu: {{ .Values.cpulimit }}
      memory: {{ .Values.memlimit }}
 
In files folder i have node.cnf file where i have innodb parameters where the values should be dynamically assigned instead of static.

innodb_buffer_pool_size = {{ .Values.memlimit }}
innodb_write_io_threads = {{ .Values.cpulimit  }}

Above may not work as if user give cpu limit as 10 the value should automatically set to 8 only as that is the recommended value. Same for pool size max should 80% of given Ram. I need a example as how to implement using if/else loop in node.cnf file.

**Comment by jascott1** [comment]
Hi @bhanumalladi 

AFAIK you cannot do any interpolation in files that are not in templates/ folder. You would need to create a configmap template for your node.cnf file. You can use `.Files` in a template to load your node.cnf file dynamically into a configmap but you will not have variable interpolation as I understand it. Once you decide on how to get your node.cnf file into the system, the templating functions are fairly straightforward, see https://github.com/Masterminds/sprig/blob/master/docs/defaults.md and for gotpl if/else see https://golang.org/pkg/text/template/#hdr-Actions.

**Comment by dcherniv** [comment]
@jascott1 i'm working with @bhanumalladi on this. Sounds good. One more question. Is there a way to do simple arithmetic via interpolations?
e.g. ```{{ .Values.cpulimit * 0.8 }}```

**Comment by jascott1** [comment]
@dcherniv Sorry for the late response. You can do some in the template but not in the values afaik. Did you find a solution?

**Comment by ggaurav10** [comment]
i need to do subtraction in the template. Has anyone figured out the solution?
/cc @dcherniv

**Comment by bacongobbler** [comment]
`sub`.

http://masterminds.github.io/sprig/math.html
