### ISSUE TITLE
Dependency issue when deploying Istio VirtualService and DestinationRule resources

### ISSUE THREAD

**Issue by rvora** [helm/helm#4560]
See https://istio.io/help/ops/traffic-management/deploy-guidelines/#503-errors-while-reconfiguring-service-routes for underlying issue.

My helm chart deploys both VirtualService and DestinationRule for a service to manage Istio routing.

As per the above link,

- when adding new subsets, I need to update the DestinationRule, wait few seconds and then  update VirtualService
- when removing subsets, I need to update VirtualService, wait few seconds and then update DestinationRule.

How can I achieve this?

**Comment by bacongobbler** [comment]
@rvora can you open this up on istio's ticket list? Seems more like a question around how to use istio rather than something actionable we can fix in helm. Thanks!

**Comment by rvora** [comment]
@bacongobbler Issue https://github.com/istio/istio/issues/8420 has been opened for tracking.

**Comment by bacongobbler** [comment]
thansk @rvora! Looking more closely at the upstream ticket it does appear that Helm is not the culprit/solution to the problem at hand. Thank you for pointing out the ticket!
