### ISSUE TITLE
v2.10.0 Windows binary reported as Trojan by Windows Defender

### ISSUE THREAD

**Issue by eryabitskiy-acx** [helm/helm#4564]
Hi,

While download of helm release **v2.10.0** binary for **Windows** from link:

https://storage.googleapis.com/kubernetes-helm/helm-v2.10.0-windows-amd64.zip

It is reported and blocked as a Trojan by Windows Defender.

Detected malware is:
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fSpursint.F!cl&threatid=2147717281

Reproduced on 2 independent workstations. Both Windows 10. Different editions.

**Comment by eryabitskiy-acx** [comment]
Hi,
Good news. I have reported this file to Microsoft. And now it is not blocked.
Thank you for attention )

**Comment by bacongobbler** [comment]
Thank you! I was unable to reproduce this but glad you resolved this :)

**Comment by Bnjmn83** [comment]
Blocked again on my system:
**Win10 Enterprise
V. 10.0.17134 Build 17134**

Defender reports:
**Trojan:Win32/Spursint.F!cl**

**Comment by eryabitskiy-acx** [comment]
Hi,
I guess you can report it to Microsoft for investigation.
When they handle it, update Defender database.
Helped me previous time.

But seams to be there is some pattern that triggers Defender scan every time...
Or mb build server is infected... :)

**Comment by bacongobbler** [comment]
I've also heard from others that 2.12.3 has been flagged so I'm re-opening this. If someone could report back when this is no longer an issue, that'd be great. Thanks!

**Comment by bacongobbler** [comment]
It appears this has been fixed overnight. I ran a powershell script against every Helm release sinve v2.0.1 that had a zipfile available for that release. The script used to verify they pass the scanner can be found here: https://gist.github.com/bacongobbler/329c98dec7f8ff4e119341a33b29532b

**Comment by SailingYYC** [comment]
> I've also heard from others that 2.12.3 has been flagged so I'm re-opening this. If someone could report back when this is no longer an issue, that'd be great. Thanks!

I've reported v2.12.3 incorrect detection to Microsoft and they've cleared it:
https://www.microsoft.com/en-us/wdsi/submission/2efd8eca-9c02-4e77-98b5-0a6900fa2686
