### ISSUE TITLE
helm install  inject labels to pod automaticlly?

### ISSUE THREAD

**Issue by berlinsaint** [helm/helm#4567]
Maybe this is a  FeatureRequest.

i know that  when we use helm install xx.chart --namespace , the helm will inject the namespace to every resource that defined in the chart.

however, for instance,   if we don't define the the template labels such as :  release: {{.Release.name}} to the podtemplate, we will not get the pod with the labelselector. so ,how about inject this tag automaticlly like namespace? the chart is a template, and when use this chart to deploy , all the pod/deployment/svc/ingress/pvc..  of this chart should have releasename label.  after that we can list pod by using releasename label selector to get this release's pod or other resources.

**Comment by bacongobbler** [comment]
IIRC way back in helm-classic we used to inject labels into the templates, but users did not want that feature as it was "black magic" that can be handled by chart developers. With that in mind, I don't think we'd accept a PR to re-introduce this so I'm going to close this, but we can revisit this discussion topic if there's enough interest.

**Comment by berlinsaint** [comment]
emmm, i don't think it is a black magic.  just like namespace, it won't be decided util runtime.

labels is the same, wo can't make a label during develop chart template, but when the runtime, it should be made , isn't it ? 
chart is a template, labels are not template, it should be a function of the helm tools when we use helm to deploy chart. 

is there some resources that why users did not want it, i don't think it is a nouse function.
