### ISSUE TITLE
Helm should **FAIL** if the namespace changes, NOT deploy into the original namespace

### ISSUE THREAD

**Issue by saplla** [helm/helm#4568]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-05-12T04:12:47Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  N/A

Just had an outage. I tried to deploy an existing chart into a new namespace for a blue/green deployment. However, Helm detected that I was trying to deploy into a different namespace, and without any warning or confirmation installed my chart into the old namespace, overwriting my stable chart. The new chart wasn't stable, so it caused a production outage.

This behaviour was totally unexpected and is completely absurd. If for some technical reason Helm is unable to install a chart into a different namespace, it should **FAIL** with an error message, **NOT** just install the chart into a namespace the user didn't specify. Please change this behaviour ASAP.

**Comment by saplla** [comment]
It looks related but I wouldn't say it's a dupe. Also, if the fix is to wait for Helm 3 I'd suggest an interim fix is needed to throw an error if the namespaces differ instead of automatically assuming the chart should be installed into the previous namespace. As I discovered, this is potentially very dangerous behaviour.

**Comment by bacongobbler** [comment]
Was this with `helm upgrade --namespace`?

`--namespace` was added to `helm upgrade` for `helm upgrade --install --namespace` so that helm will deploy the chart for the first time in the specified namespace. In every other case, `--namespace` is ignored and upgrades the chart. I understand it's a little awkward, but we cannot make the flag fail with an error message or we'll break users who are relying on this behaviour for their CI scripts.

Does that make sense?

**Comment by saplla** [comment]
Yes we install through CI with `helm upgrade --install --namespace`. Why would failing if the namespace changes break CI scripts? To reiterate, we had originally installed a chart into namespace1 and wanted to install a new version into namespace2. This command ignored my explicit setting of `--namespace namespace2` and upgraded the chart into namespace1. An error would have made me realise that if upgrading into a different namespace wasn't possible that I would have needed to have renamed my chart.

This really comes down to users being in control vs "Helm knows best" and ignoring an explicit command line argument. It should error if the namespace has changed, not just ignore it and install into the previous namespace. I can't imagine when, if the namespace changes, that the user's intent would be for Helm to ignore that change, even if run through CI/CD.

**Comment by bacongobbler** [comment]
closing as inactive.
