### ISSUE TITLE
`include` reusing context between invocations

### ISSUE THREAD

**Issue by andor44** [helm/helm#4569]
Output of `helm version`:
2.9.1
Output of `kubectl version`:
client - 1.11.1
server - 1.10.5

It seems that when you invoke `include <template> <context>` with a given context, any further invocation of that `<template>` will be done as if the first `context` was passed.

To see an example in practice please see helm/charts#6073. In that PR I wanted to invoke a template defined in `_helpers.tpl` twice, once in `deployment.yaml` and once in `service.yaml`, but I wanted them to be slightly different because the `Deployment` object expects the port structure to be slightly different than `Service`. I tried to work around this by passing different contexts to emulate passing an argument to the template, but that made no difference. Whatever context was passed for the first time ended up being passed on any subsequent runs of that template, as if the first result of `include` was being cached.

As a workaround I had to define a ~50 lines template twice, only to change two lines. It'd be nice if I didn't have to repeat it.

**Comment by bacongobbler** [comment]
closing as inactive.
