### ISSUE TITLE
Install order of Custom Resources (not Custom Resource Definitions)

### ISSUE THREAD

**Issue by nphmuller** [helm/helm#4578]
We use the [Sealed Secrets](https://github.com/bitnami-labs/sealed-secrets) project to encrypt our Kubernetes secrets, so they can be stored in the Git repository. This works by adding a Custom Resource, manifest which I would like Tiller to install at the same time as (or before/after) normal Secret manifests.

Is there currently a way for me to define at what stage a Custom Resource (like SealedSecret) will be installed? To be clear, I don't mean the CRD. Just the Custom Resource itself.

I noticed that Tiller uses the order predefined in [this file](https://github.com/helm/helm/blob/7cad59091a9451b2aa4f95aa882ea27e6b195f98/pkg/tiller/kind_sorter.go#L29) when installing manifests. But I didn't really get much further.

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by Ryan-Git** [comment]
I'm not the maintainer of helm, just come into the same question.
The code shows that 'unknown kind is last', which is ok for me. For ur case, pre-install and hook-delete-policy might be better.

**Comment by kbirger** [comment]
I'd like more visibility on this. I'm coming with the exact same use case here. 

@Ryan-Git - I'm not sure what you mean, could you link to an example?

**Comment by bacongobbler** [comment]
If the Kind is unknown, it is at the bottom of the sort list.

See https://github.com/helm/helm/blob/d953c6875cfd4b351a1e8205081ea8aabad7e7d4/pkg/tiller/kind_sorter.go#L138-L159

**Comment by kbirger** [comment]
I'm aware of this behavior. It's just not always desirable, such as in the case presented above. 

I think it has already been proposed, but an annotation that would allow you to assign a rank value to a particular resource might be a nice, flexible solution.

**Comment by bacongobbler** [comment]
I have not seen any movement from the community to implement this functionality since it was opened 2 years ago. Closing as inactive.
