### ISSUE TITLE
Separate CA certificate from tiller-secret in TLS-enabled installation

### ISSUE THREAD

**Issue by mcmathja** [helm/helm#4583]
I would like to secure my Tiller installation with certificates issued and managed by [cert-manager](https://github.com/jetstack/cert-manager).

My original plan was to just pass the [`kubernetes.io/tls`](https://github.com/kubernetes/kubernetes/blob/2d7b92ee743de20d17406003e463a829a0db5a51/pkg/apis/core/types.go#L4419) type secret generated by cert-manager to the `tiller-certs` volume specification in place of the custom `tiller-secret` usually created during initialization. This works fine if I enable TLS without turning on verification. However, when installing with the `--tiller-tls-verify` option, Tiller expects its secret to also contain a `ca.crt` field for the CA certificate. This isn't part of the above type specification and so isn't included in the secrets produced by cert-manager. I didn't see a simple way to combine the cert-manager secret with the CA certificate without manually munging the two together, which defeats the purpose of automating the certificate lifecycle.

That got me thinking that it might make sense to split the Tiller server key pair and the CA certificate into two separate secrets. That would allow the former to be managed separately, and to conform to the `kubernetes.io/tls` secret type if desired. Does that seem like a reasonable solution, or am I barking up the wrong tree?

**Comment by bridgetkromhout** [comment]
Hi, @mcmathja & @dolfim - thanks for your feedback! As Helm no longer has tiller (as of Helm 3), and Helm 2 is only accepting bugfixes now, we don't plan to make this change. If you'd like to read more about the differences from Helm 2 to Helm 3, you can find that info here: https://helm.sh/docs/faq/
