### ISSUE TITLE
Helm update repo not updating version.

### ISSUE THREAD

**Issue by feluxe** [helm/helm#4598]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}

```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
`minikube version: v0.28.2`

### Issue

**Expected behaviour** 

If I push a new  version (`0.0.2`) of `mychart` to a helm repo (hosted on github) and run `helm repo update` afterwards, I would expect `helm search mychart` to show the new version:

```
NAME            CHART VERSION	APP VERSION	DESCRIPTION                
myrepo/mychart	0.0.2           1.0        	My Chart
```

**Actual behaviour** 

If I push a new  version (`0.0.2`) of `mychart` to a helm repo (hosted on github) and run `helm repo update` afterwards, I'm not getting the new version from `helm search mychart`:

```
NAME            CHART VERSION	APP VERSION	DESCRIPTION                
myrepo/mychart	0.0.1           1.0        	My Chart
```

If I wait a couple of minutes and run `helm repo update` and `helm search mychart` again, I get the correct version.

Maybe a caching issue?

### Steps to reproduce

Create a helm chart repo on github.

Update the version of `mychart` from `0.0.0` to `0.0.1`:

```
helm package mychart --version 0.0.1
```
Update the index for the repo:

```
helm repo index .
```
Push the changes to the repo on github via `git push` etc. You can validate the changes on github.com in the browser.

Now run:
```
helm repo update
helm search mychart
```

**Comment by bacongobbler** [comment]
Probably just a caching issue between github pages and github.
