### ISSUE TITLE
helm init fails on a air-gapped network

### ISSUE THREAD

**Issue by EranIsraeli** [helm/helm#4602]
(Using Helm version: 2.10.0)
Hi,
When issuing the 'helm init' command on an air-gapped network, and error is displayed about not being able to connect to Helm's repository. The problem is that the .helm directory isn't being created properly, especially the 'repositories.yaml' file.

Trying to add my own helm repository by using 'helm repo add' failed because it couldn't find the 'repositories.yaml' file.

I had to create the 'repositories.yaml' file manually, then run 'helm repo add' with my own helm repository and then run 'helm init' again.

IMO, 'helm init'  should always create the 'repositories.yml' file, even if there is no helm repository which is accessible. 

Thanks.

**Comment by bacongobbler** [comment]
Try `helm init --client-only --skip-refresh`. That's the canonical invocation when running it in an airgapped network.

**Comment by bacongobbler** [comment]
closing as inactive.
