### ISSUE TITLE
"useTunnel" Plugins and Plugin help

### ISSUE THREAD

**Issue by jkroepke** [helm/helm#4605]
Output of `helm version`: 2.10

Hi,

helm have a great plugin system. With `useTunnel` helm will prepare a tunnel to the tiller server that a helm plugin can just use. This is a cool feature but commands like `helm <plugin> help` just works only if a tiller is available.

It would be awesome if plugins have the ability to blacklist some commands. For blacklisted commands (for example `help`) helm will skip the tunnel creation and just forward the command to the plugin.

**Comment by bacongobbler** [comment]
closing as inactive.
