### ISSUE TITLE
Documentation - Dead link on "related project"

### ISSUE THREAD

**Issue by tgarlot** [helm/helm#4611]
On page https://docs.helm.sh/related/, the link "The Workflow “Umbrella” Helm Chart" (pointing to https://deis.com/blog/2017/workflow-chart-assembly). 

Probably because deis.com does not exist anymore.

Proposal would be to simply remove this link. Happy to PR this one.

**Comment by bacongobbler** [comment]
Sounds good to me. Thanks!
