### ISSUE TITLE
Can't install plugins. Error: Cannot detect VCS

### ISSUE THREAD

**Issue by luisdavim** [helm/helm#4612]
I get `Error: Cannot detect VCS` when trying to install helm plugins:
```
$ helm plugin install diff
Error: Cannot detect VCS
```

Output of `helm version`:
```
$ helm version
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
```
Output of `kubectl version`:
N/A
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
N/A

**Comment by mabushey** [comment]
Did you ever figure this out or just give up?

**Comment by bacongobbler** [comment]
The correct usage is `helm plugin add https://github.com/...` rather than the name of the plugin. `helm plugin add` needs a VCS repository URL to resolve to a plugin.

For @databus23's `helm-diff` plugin, that'd be

```
helm plugin add https://github.com/databus23/helm-diff
```

Hope this helps.

**Comment by rami-foo** [comment]
helm plugin add https://github.com/databus23/helm-diff
Error: Unable to retrieve local repo information: exit status 1
