### ISSUE TITLE
assigment flag --set and --values gives different behavior 

### ISSUE THREAD

**Issue by efahale** [helm/helm#4617]
Hi,

when I set a parameter for example "testArray" using --set testArray={1,2,3}. It works as expected and assign an array to "testArray" but if I set "testArray" with same value in a file and use --values "testArray" get assigned to a map. Is this correct behavior? 

Output of `helm version`:
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"fdf9fd4cc35df7d146f9d34eabd70a85a467f07a", GitTreeState:"clean"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:17:47Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"", BuildDate:"2018-06-27T08:25:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by bacongobbler** [comment]
Yes, this is correct behaviour. YAML's syntax is `testArray: [1, 2, 3]` or

```
testArray:
  - 1
  - 2
  - 3
```

`--set` is a custom string parsing library, and its syntax can be found here: https://docs.helm.sh/using_helm/#the-format-and-limitations-of-set

Hope this answers your question!

**Comment by efahale** [comment]
thank you for your reply and explanation. 
it would be nice if --set also could use [] instead of {} for arrays then it would be consistent.
