### ISSUE TITLE
Helm seems to not use its local charts cache

### ISSUE THREAD

**Issue by mboret** [helm/helm#4618]
Hi, I'm surprise to discover that helm is not using his local cache folder(.helm/cache/archives/) during an install/upgrade process. 

We faced this issue after our chartmuseum repository was unavailable generating an I/O timeout error when we tried to perform an helm upgrade. 

The weird thing is the chart was already in .helm/cache/archives/

I was thinking that in a upgrade/install process, helm looks inside this archives folder, check if the package exists, if yes, use it, otherwise try to download it. 

It seems that the reality is different. Can someone confirme me this behavior and if it's normal?

Thanks.

Output of `helm version`:

Client: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by bacongobbler** [comment]
Yes, that is the current behaviour, but I wouldn't call it normal. :)

As it stands right now, `helm install stable/wordpress` will look up the chart based on what's in `$HELM_HOME/repository/cache/stable-index.yaml`, find the URL of the chart referenced in the repository index (`wordpress` in this example) and fetches it. however, we should probably check if that chart has already been fetched before and it exists in the cache before trying to re-fetch it.

Filing as a good first feature for someone to tackle!

**Comment by mattfarina** [comment]
I was just talking with @technosophos about this. The way the cache works doesn't work with repo/chart uniqueness. So, if I have two charts with the same name and version but different content which one will be in the cache.

Helm charts have a digest. We could use that in a few interesting ways...

1. A cache key where the cache become content addressable (like container images). This would make it safe to pull from while dealing with multiple repos and charts
1. We could look into the digest as an etag and then use `If-None-Match` HTTP request header to get content or return a 304 if they don't need the payload
1. We could go down the road of Merkle trees to look for changes in charts with dependencies.

I removed the good first issue because having valid cache without collisions changes how we address things in there. I've also added this as a discussion topic for the next Helm call.

**Comment by sgandon** [comment]
indeed I came accross the same issue, when traveling or not connected to our vpn we cannot get acces to our registry and then cannot launch a chart that is not reachable.
when you launch one chart you can find way around but when you are relying on other tool like helmfile in which you describe many charts it become more cumbersome.
See : https://github.com/roboll/helmfile/issues/544

**Comment by razor-x** [comment]
Has any work on this been done for Helm 3? I just experimented with moving my charts from local to an http repo. I use the same chart many times. My CI deploy time went from 15 seconds to over a minute. The short deploy times are really important for our work flow.

**Comment by bacongobbler** [comment]
There hasn't been any work on this front. Feel like taking a crack at solving this?

**Comment by razor-x** [comment]
Possibly. Have not done any Go yet, so it's hard to estimate on this. 

I still believe there may be a simpler, smaller scope first approach to solving the caching problem that is more approachable. Given that the charts all have a hash associated with them, why not just store the archives in a flat folder with name equal to it's hash?

**Comment by bacongobbler** [comment]
Yep! That seems like a good first step in the right direction. That's the same proposal @mattfarina [mentioned earlier in the thread](https://github.com/helm/helm/issues/4618#issuecomment-423276636). A digest is just another term for a hash. :)
