### ISSUE TITLE
add tiller binary to the release distro for 2.x until we get to 3.x?

### ISSUE THREAD

**Issue by jstrachan** [helm/helm#4619]
Being able to avoid the server side tiller component is super useful for many reasons:

* better RBAC support (logically run a local tiller in each namespace and use local client RBAC)
* avoid helm version hell between different containers with different helm binaries inside
* allows a tiller per namespace to avoid having to use globally unique release names across all namespaces

When helm 3 is a thing this issue is fixed elegantly. Until we get there something like [helm-local](https://github.com/adamreese/helm-local) plugin looks like an excellent workaround. 

However to use `helm-local` requires a `tiller` binary and currently that means the end user has to grab the source code and build the tiller binary by hand which is a huge UX fail. 

Ideally this command:

    helm plugin install https://github.com/adamreese/helm-local

would even download the tiller binary too.

So it would be lovely to instead include the `tiller` binary inside the tarballs for each operating system so that anyone who downloads helm can get a `helm` and `tiller` binary - either that or create a helm + tiller tarball for each operating system? I figured adding tiller inside helm 2.x tarballs would have the least confusion?

**Comment by bacongobbler** [comment]
this was already implemented in #4443. Thanks

**Comment by jstrachan** [comment]
@bacongobbler humble apologies - forgot to double check the RC release!
