### ISSUE TITLE
Helm Tags

### ISSUE THREAD

**Issue by plokimju** [helm/helm#4621]
Is there a way to Tag a helm chart and search based on tag name?

**Comment by bacongobbler** [comment]
Yes! If you add `keywords` to your Chart.yaml, `helm search` will be able to lookup based on that keyword. For example, `helm search database` will bring up charts such as postgres, mariadb etc. Will that work for you, or was there something else in particular?

**Comment by plokimju** [comment]
I was looking for something which is helm equivalent of release tags in git

**Comment by bacongobbler** [comment]
Oh. In that case, `helm search chartname --versions` will show all available versions for a given chart. Will that help?

**Comment by plokimju** [comment]
Here is the example scenario ,  We have multiple charts generated in dev every day so I want tag the versions of charts which eligible to promote .. eg: version 10 should be tagged  QA

**Comment by plokimju** [comment]
Thanks Matt.. I Think I can use keywords as  you mentioned.. Closing this ticket

**Comment by plokimju** [comment]
Hi,
I tried using keyword. It helps to search the helm repo with keyword. But my requirement is to search through the different versions of a chart with keyword

**Comment by bacongobbler** [comment]
I'm getting a little confused about the use case. As I mentioned above, `helm search <keyword> --versions` allows you to do a lookup based on a keyword, displaying all available versions of a chart that match that keyword. Can you try experimenting with that and see if that solves your use case?

If that doesn't solve your use case, then perhaps could you try writing a [helm plugin](https://docs.helm.sh/using_helm/#the-helm-plugins-guide) to solve that use case and post it here to demonstrate what you're trying to achieve?

**Comment by plokimju** [comment]
Sure Thank you
