### ISSUE TITLE
helm delete removed resources not created by helm (probably a feature request)

### ISSUE THREAD

**Issue by dleute** [helm/helm#4625]
I was helping someone move their kube templates to helm. During the process they launched test versions of the chart which complained that xyz resources already exist. They fixed it in the template (added release name, etc) and launched again. Did this a few times.

That all worked, but then they went back to delete the previously failed releases and the delete removed the pre-existing resources that happened to share the same name.

It does not seem like helm delete should remove resources it did not create.

Flow:

1. helm install new chart
2. helm install fails because ingress of the same name exists (did this for several resource types)
3. helm install chart again with template fix
4. helm install succeeds
5. helm delete failed chart install
6. existing ingress deleted by helm delete command

It would be nice if helm delete was smart enough to not break things from helm install failures.

(Obviously, if the chart had been written correctly in the first place, this would not have happened. Still, it would prevent stupid mistakes)

I wasn't the driver of the incident so I can't provide the helm or kubectl versions. But I imagine, this is more of a feature request than a bug fix, as it would work the same on any version of helm currently.

Thanks!

**Comment by ArcticSnowman** [comment]
Is this related to #4615 ?

**Comment by dleute** [comment]
I believe it is exactly the same issue.

**Comment by bacongobbler** [comment]
closing as a dupe
