### ISSUE TITLE
desktop.ini causes error when updating or installing charts using Helm on Windows

### ISSUE THREAD

**Issue by lanmarti** [helm/helm#4628]
When running Helm on Windows, I regularly run into the following error:
``` error unpacking desktop.ini in [folder-name]: chart metadata (Chart.yaml) missing```

Windows automatically generates the `desktop.ini` files to store information about how to display the folder in programs such as Explorer. While there are claims that this file contains important data, I nor anyone on the internet seems to have experienced any adversary effects by removing these files. On newer versions of Windows 10, it's (near) impossible to stop `desktop.ini` from being generated permanently. 

My current solution is to periodically remove all `desktop.ini` files from my local charts folder through a command. 
While this is technically a problem with Windows and not with Helm, Microsoft is not likely to change this behavior any time soon. Would it be possible to make helm ignore `desktop.ini` files while processing files?

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by michelleN** [comment]
hi @lanmarti - have you tried adding `desktop.ini` to a `.helmignore` file in your chart? Any files inside of a `.helmignore` file in the root of your chart will be ignored when processing the chart. See this [example](https://github.com/helm/charts/tree/fd5497707927e77091f6de53578eda896df604e8/stable/drupal)

**Comment by lanmarti** [comment]
I completely overlooked `.helmignore`. I've added `desktop.ini` to `.helmingore` in each of my charts and everything is going smoothly so far. Thanks!
