### ISSUE TITLE
Minor change to healthcheck url causes error

### ISSUE THREAD

**Issue by magick93** [helm/helm#4634]
I am making the following change in the `deployment.yam` file:
```
livenessProbe:
           httpGet:
-            path: /ignite?cmd=version
+            path: /ignite?cmd=top&attr=false&mtr=true
             port: {{ .Values.service.restSecondPort }} # REST port number.
```
And am getting the following error:

```
helm upgrade -i ignite-dev . --namespace ignite-dev
Error: UPGRADE FAILED: failed to create patch: unable to find api field in struct Container for the json field "httpGet"
```

When I revert, the error disappears.

# Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

# Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

# Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

K8 on baremetal.

**Comment by michelleN** [comment]
At first glance, this looks like an indentation issue on `httpGet`. It should be under the `livenessProbe` key indented two spaces from the left. Let me know if that solves your problem.

The `helm lint <chart>` command can ensure that a chart is well formatted. You may also want to make use of `helm upgrade -i --dry-run --debug`. Those flags (dry-run and debug) will give you an idea of what to expect when running a command without actually running those actions and also output the kubernetes manifests that would be installed.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
