### ISSUE TITLE
multi-arch docker images for Tiller

### ISSUE THREAD

**Issue by paulbsch** [helm/helm#4636]
We currently run a mixed arch (amd64, ppc64le, and eventually arm64) k8s cluster.  So the tiller deployment that 'helm init' creates in the kube-system namespace causes us some issues.  The tiller pod will continually fail if it gets assigned to one of our ppc64le nodes.

The tiller docker images appear to only be built for amd64.  Please build ppc64le and arm64 docker images for tiller and create a multi-arch manifest list so that the tiller deployment will work on all architectures.

A short term hack/fix (until multi-arch Tiller is available) could be to add a "nodeSelector" for "beta.kubernetes.io/arch: amd64" to the yaml for the deployment.

Thanks!

**Comment by bacongobbler** [comment]
related discussion: https://github.com/helm/helm/pull/4200

**Comment by PatrickLang** [comment]
I ran into this deploying on an ODroid device which is `armv7hf`. I patched my deployment to use Jesse's multi-arch image: https://gist.github.com/PatrickLang/28a05cfd6cf4322d519d04cff0996585#deploying-tiller

**Comment by HaveFun83** [comment]
+1

**Comment by bacongobbler** [comment]
Closing for the same reasons in https://github.com/helm/helm/pull/2649. For posterity:

As per [the announcement on the mailing list](https://lists.cncf.io/g/cncf-helm/topic/last_v2_feature_release/34301238), Helm 2.15.0 is the last release where we will be merging new features for Helm 2. Tiller has been removed in Helm 3 so I don't see us moving forward with this proposal, so I'm going to close this as something we do not plan to merge in the 2.15 timeframe.

That being said, the [tiller-multiarch](https://github.com/jessestuart/tiller-multiarch) project has been providing amd64 tiller images for Helm 2, so I'd suggest focusing efforts on that project going forward. Thanks!
