### ISSUE TITLE
add some more documentation around .helmignore file

### ISSUE THREAD

**Issue by michelleN** [helm/helm#4638]
Currently, there are only a few mentions of the `.helmignore` file in the helm docs. We could probably stand to have a little bit more. Let's add an explanation around why someone may want to create and use a `.helmignore` file along with an example.

**Comment by OrthoDex** [comment]
Hi @michelleN, can I take this up?

**Comment by michelleN** [comment]
absolutely @OrthoDex

**Comment by rcorre** [comment]
Can you please include a description of the `.helmignore` syntax? It doesn't seem to be the same as `.gitignore` (`!` negation doesn't work the same, at least), so how exactly does one write a .helmignore?

As a practical example, I'm trying to exclude all `.tgz` files, except those in `charts/`. I have no idea what the syntax for this should be.

**Comment by bacongobbler** [comment]
FYI there's also discussion on the same topic in https://github.com/helm/helm/issues/3622

**Comment by bacongobbler** [comment]
closed via #4966
