### ISSUE TITLE
How to mask sensitive/secret information values in yaml file 

### ISSUE THREAD

**Issue by tanzeelrana** [helm/helm#4642]
Is it possible to mask sensitive or secret information so that ops who have access to the deployment yaml files are unable to see those secrets ?

**Comment by jascott1** [comment]
Hi @tanzeelrana 

Helm does not provide this feature but you could keep a values-password.yaml securely separate and then have it merged in at install time by including it with `helm install mychart -f values.yaml -f values-password.yaml`

**Comment by prestonwrthompson** [comment]
@jascott1 thanks for the answer!

To make sure, is it correct that your suggestion still doesn't protect against secrets in `values-password.yaml` being exposed by `helm get values application`? 

It seems like there was some discussion in the proposals in #2196 and #2695 about managing secrets in a way separate from regular values, but what was actually merged in #2721 did not address that issue and instead added the different storage backend.

Do you have any suggestions for how to get around this problem? Allowing operators/developers to see the currently deployed values via `helm get values` is something we'd like to provide, but it isn't safe to do if it exposes secrets.

**Comment by bacongobbler** [comment]
https://github.com/helm/helm/issues/2196
