### ISSUE TITLE
Is there a way handle variables in .Values?

### ISSUE THREAD

**Issue by yyyyyyyyyg** [helm/helm#4645]
I want to dynamically generate my template file, here is my case:
`{{- $v := (.Files.Get "values-deployment-nginx.yaml") | fromYaml }}

spec:

  {{- range $key, $value := $v.containers }}
  containers:
    name: {{ $value.name }}
    image: {{ .Values.{{ $value.name }}-image }}:{{ .Values.{{ $value.name }}-tag }}`

I want to first get the {{ $value.name }}, it maybe a string like "nginx", then I would like to use the {{ .Values.nginx-image }} to get the right image value in values file.
Is there a way can do this? Thank you very much!

**Comment by ArcticSnowman** [comment]
Any reason you could not do a `$value.image` from the source YAML?

**Comment by ArcticSnowman** [comment]
Here's an idea...  It might be possible to used 'named_template' to achieve this..

You have your value defining the image/tag
```
deployment-nginx-imagerepo: nginx
deployment-nginx-imagetag: latest
```
Now for each one you have template defined:
```
{{- define "nginx.image" -}}
{{ .Values.deployment-nginx-imagerepo}}:{{.Values.deployment-nginx-imagetag }}
{{- end -}}
```
Then in your template:
```
{{- range $key, $value := $v.containers }}
  {{- $template := printf "%s-%s", $value, "image" -}}
containers:
   name: {{ $value.name }}
   image: {{ template $template  }}
...
{{ end -}}
```

Further reading on Helm Templates, which is based on Go Templates and Spring:
- https://godoc.org/text/template
- http://masterminds.github.io/sprig/

**Comment by tomcruise81** [comment]
I believe that Sprig v3 adds this via it's [get](http://masterminds.github.io/sprig/dicts.html#get) function:

`image: {{ get .Values (printf "%s-image" $value.name) }}:{{ get .Values. (printf "%s-tag" $value.name) }}``

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
