### ISSUE TITLE
Add default values per Tiller installation

### ISSUE THREAD

**Issue by Smirl** [helm/helm#4655]
There are often cases where per installation metadata (or other values) are needed in a chart which are linked to the cluster which the chart is being installed into. For example; `region`, `clustername`, `tillername`, `tillerversion`, etc.

Is it possible to have such values in the current Helm?

If not, could we discuss adding, low priority, default `values.yaml` when installing/running Tiller. This could be an option to `tiller`, and therefore `helm init`. These values could either be set with `--set`, `--set-string`, `--set-file`, and/or `--values`. This would match the `helm` command.

The best (or starter) option would be to pass a path to a YAML file (configmap or otherwise) to read default values from for each `helm install` or `helm upgrade`.

My exact use case it to simply have `region` and `clustername` set for each install. I am using Helm with [weaveworks/flux](https://github.com/weaveworks/flux/). This has a compontent called `Helm Operator` which watches for a CRD (`FluxHelmRelease`). A `FluxHelmRelease` can have values supplied, but copy and pasting these for each cluster and AWS region we deploy to would be cumbersome . 

Thanks, Alex

**Comment by bacongobbler** [comment]
potentially related to https://github.com/helm/helm/issues/2055.

**Comment by bacongobbler** [comment]
FYI TillerVersion is available via the `.Capabilities` object. See https://docs.helm.sh/developing_charts#predefined-values for more info

**Comment by Smirl** [comment]
Although `clustername` is useful, it is just an example. In the template we currently have access to the top level variable `.Values`. To make this change explicit we could introduce a new top level variable; for example `.TillerValues`, etc.

An example usage I have in mind is in a chart template:
```
{{ default .TillerValues.Region .Values.Region }}
```

**Comment by Smirl** [comment]
The use case I had for this I have instead implemented in flux.
The general use case for this will go away if there is a tillerless helm.

For those interesting in default values when using flux, take a look at https://github.com/weaveworks/flux/pull/1468
