### ISSUE TITLE
Wrong selector generated when creating a new chart

### ISSUE THREAD

**Issue by qiangli** [helm/helm#4661]
Output of `helm version`: 
Client: &version.Version{SemVer:"v2.11.0-rc.2", GitCommit:"8d408876a059223c9a29d99efb35b3497a53504c", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0-rc.2", GitCommit:"8d408876a059223c9a29d99efb35b3497a53504c", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:16Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS 

In service.yaml, line 19 (last line):
app.kubernetes.io/instancelease: {{ .Release.Name }}

it should be:
app.kubernetes.io/instance: {{ .Release.Name }}

**Comment by bacongobbler** [comment]
thanks for catching this @qiangli!
