### ISSUE TITLE
helm init --upgrade does not upgrade replica count.

### ISSUE THREAD

**Issue by YenTheFirst** [helm/helm#4664]
Output of `helm version`:
```Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}```

Output of `kubectl version`:
```Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T09:56:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS

steps to reproduce:
```
helm init
helm init --upgrade --replicas=3
kubectl get pods -lname=tiller```

Expected output: Lists 3 pods
Actual output: Lists 1 pod.

On quick skim of (https://github.com/helm/helm/blob/7b821dd52fffa135cfe78611299b0491f7f03d39/cmd/helm/installer/install.go#L62), it looks like the tiller upgrade _only_ upgrades the image, pull policy, and service account, it doesn't allow changing any other config overrides.

**Comment by YenTheFirst** [comment]
On further investigation, it's unclear to me whether `--replicas` is actually safe to use, at the moment, anyway.

I'm aware that the intention is to remove Tiller in Helm v3, but it's unclear what kind of timeline that might be occurring on.

**Comment by 27Bslash6** [comment]
Until Helm v3 is released, I'm trying to find ways to circumvent repeatable helm communication timeouts during multiple simultaneous releases.

Is this simply a matter of increasing pods by via `kubectl scale deployment tiller --replicas=X` ?

Any gotchas to watch out for?  I understand race conditions in CRUD operations but this is possibly something I can live with in the interim.

**Comment by bacongobbler** [comment]
Yep, in general it'd be `kubectl -n kube-system scale deployment tiller-deploy --replicas=3`.

The other issue I know about is Helm's portforwarder library (the one that it uses to connect to Tiller). portforwarder connects to [the first running pod in the deployment](https://github.com/helm/helm/blob/7161095f79e2c9a35350d301ad820e57e56182ec/pkg/helm/portforwarder/portforwarder.go#L81-L85), therefore the load is not balanced between multiple Tiller instances by scaling up. Practically speaking, that just means that all connections will only go to a single Tiller instance until it becomes unhealthy, while the others sit there and waste compute resources.

**Comment by bacongobbler** [comment]
closing as inactive.
