### ISSUE TITLE
"failed: no objects visited" error when creating only secrets via helm

### ISSUE THREAD

**Issue by Krishna1408** [helm/helm#4670]
Output of `helm version`:
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.6-gke.2", GitCommit:"384b4eaa132ca9a295fcb3e5dfc74062b257e7df", GitTreeState:"clean", BuildDate:"2018-08-15T00:10:14Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd6
4"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

**Issue Description**
I have a helm template which I am using to create secrets. I created a chart which only creates secrets for my applications. When I run the chart in `--debug --dry-run` mode it works fine and I do not get any error. But when I actually try to create a secret from it I get below error:

> *Error: release test failed: no objects visited*

Below is how i created my chart:
1. helm create test
2. `values.yaml` content:
  ```yaml
     secrets:
        test: YmFzZWw=
  ```
3. helm install --name  test test --debug

This is my helm template to create secret:
```yaml
    apiVersion: v1
    kind: Secret
    metadata:
      name: {{ $.Release.Name }}-secrets
      labels:
        chart:    {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
        release:  {{ $.Release.Name }}
        heritage: {{ $.Release.Service }}
    data:
    {{- range $key, $val := .Values.secrets }}
      {{ $key }}: |-
    {{ $val | indent 4}}
    {{- end }}
```

But When i run `kubectl get secrets` I see that my secret named `test-secrets` was created successfully. And when I use `kubectl describe` I even see the content.

**Comment by bradleyd** [comment]
FWIW,  am seeing the same with a Job instead of secrets.  I am using helm 
```
10:19 $ helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```
I am using hooks

```
  annotations:
    "helm.sh/hook-weight": "100"
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
```

**Comment by Krishna1408** [comment]
HI @bradleyd, this issue happens for : 
1. secrets
2. Configmaps
3. jobs
4. cronjobs

It's not a big issue but it is quite annoying

**Comment by bradleyd** [comment]
@Krishna1408 thanks for the quick response.  Yeah it was failing our jenkins job until i realized it is "harmless".  I just added a `|| true` to the end for now until a fix is in.

**Comment by StephGit** [comment]
@Krishna1408 @bradleyd 
I had the same issue with the error "failed: no objects visited" trying to create secrets by helm.
After removing unused annotations the deployment works with following version:
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```
Annotations removed:
```
annotations:
    "helm.sh/resource-policy": keep
    "helm.sh/hook": pre-install,pre-upgrade
```
`helm upgrade --install ...`

**Comment by Krishna1408** [comment]
As there are not so many people raising this issue it's been neglected till now.. I hope someone sees it and take some action. I'll see if I can do anything to fix it.

**Comment by jesseeichar** [comment]
This is an issue for me as well.  I want to deploy a job to perform some tasks, but since there is no deployment, statefulset, etc...  the deployment fails.  As a work around I'm looking at having to create a deployment that does essentially nothing.

**Comment by delwaterman** [comment]
+1 on this

**Comment by Onlinehead** [comment]
+1 on this

**Comment by norbertbuchmueller** [comment]
+1 on this

**Comment by gazhenko** [comment]
+1 on this as well

**Comment by pamiel** [comment]
+1

**Comment by montaro** [comment]
+1

**Comment by jonstacks** [comment]
+1

**Comment by maberny** [comment]
+1

**Comment by night0wl** [comment]
+1

**Comment by bclouser** [comment]
+1 for me as well.

**Comment by tianhe-oi** [comment]
+1

**Comment by Jean85** [comment]
Can someone re-label this issue as a bug? It renders impossible to use jobs as hooks as documented [here](https://github.com/helm/helm/blob/master/docs/charts_hooks.md#writing-a-hook)

**Comment by bacongobbler** [comment]
This particular error occurs when a chart [does not define any templates](https://github.com/helm/helm/blob/745e772d6469a020179ec124bdb72a516a2addb3/pkg/kube/client.go#L434-L436).

If I'm understanding the reports here, are all the resources within the chart are marked as a hook? Hooks are considered "un-managed" by tiller. If everything is marked as a hook and there are no other objects to install, that would definitely trigger this error.

I'm not sure if that would be considered a bug though given that this was an intentional design decision. What's the use case here for having a chart with only hooks but no resources?

**Comment by bacongobbler** [comment]
After mulling this through I don't think this is a bug from the backend's point of view, but rather a usability issue which we can address with docs or a better understanding of the use cases involved.

**Comment by bacongobbler** [comment]
I just deleted all the "+1" comments in this thread. In the future, please add a :+1: to the OP instead. That way we can keep the discussion moving forward without a bunch of +1 comments flooding the thread. Thanks!

**Comment by Jean85** [comment]
> If I'm understanding the reports here, are all the resources within the chart are marked as a hook?

No, we do not have only hooks. In my case, we have a functioning chart with multiple deployments, and we want to add a single job as a `pre-install,pre-upgrade` hook. And that doesn't work, because Helm needs to wait of its completion.

**Comment by bacongobbler** [comment]
If you wouldn't mind providing an example to use for testing purposes, that would be helpful to identify the issue. Thanks!

**Comment by gianiaz** [comment]
@bacongobbler after deploing on staging we call a job for updating a schema using a symfony command.

```
@bacongobbler after deploing on staging we call a job for updating a schema using a symfony command.

```
apiVersion: batch/v1
kind: Job
metadata:
  name: schemaupdate
  labels:
    app: {{ $.Values.app.name }}
    tier: schemaupdate
  annotations:
    helm.sh/hook: "pre-install,pre-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation"
spec:
  template:
    metadata:
      labels:
        app: {{ $.Values.app.name }}
        tier: schemaupdate
    spec:
      restartPolicy: Never
      imagePullSecrets:
      - name: "{{ $.Values.gitlabRegistrySecret }}"
      containers:
        - name: php
          image: gitlab.myhostedgitlab.it:4567/app/fpm:{{$.Values.app.tag}}
          command: ["bin/console","doctrine:schema:update", "--dump-sql", "--force"]
          imagePullPolicy: Always
          resources:
            requests:
              memory: "{{ $.Values.job.schemaupdate.resources.requests.memory }}"
              cpu: "{{ $.Values.job.schemaupdate.resources.requests.cpu }}"
            limits:
              memory: "{{ $.Values.job.schemaupdate.resources.limits.memory }}"
              cpu: "{{ $.Values.job.schemaupdate.resources.limits.cpu }}"
          env:
{{ include "deployment.mysql-env" . | indent 10 }}
```

After deploying with helm we have the no object visited even if the job was successfull.

We use hooks for delete previous deployment of the job for allowing us to see logs from the pod.

**Comment by Jean85** [comment]
We can simplify that job like this (for debug purposes):

```
apiVersion: batch/v1
kind: Job
metadata:
  name: schemaupdate
  labels:
    app: myapp
    tier: schemaupdate
  annotations:
    helm.sh/hook: "pre-install,pre-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation"
spec:
  template:
    metadata:
      labels:
        app: myapp
        tier: schemaupdate
    spec:
      restartPolicy: Never
      containers:
        - image: alpine:3.8
          command: ["sleep","10"]
```

Obviously you need at least an other working non-hook template to make it testable, but it shouldn't matter which one, it's enough that it's a resource that Helm is able to deploy on its own.

**Comment by pamiel** [comment]
Hi @bacongobbler 

Here is the usage we have of a chart containing hooks only: we got inspired by the documentation on hooks that says `Execute a Job to back up a database before installing a new chart, and then execute a second job after the upgrade in order to restore data.`

So, among others, we built a Job which goal is to backup some data. This Job is to be executed before some other installation stuff.
The reason why we decided to put this into an independent chart, with only hooks in it are the following:
-	A Pre-Hook is convenient for executing the backup “before” the other installation steps; so let's put our Job as a Hook
-	In case the execution of the Job is correct, we don’t want the Job and the corresponding Pod to remain visible in Kubernetes. We want to keep them only in case of error. So the `"helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation` annotation is exactly answering this need
-	Such a backup is required in different situations, and we want to be able to execute the backup independently from the installation steps. So having a dedicated chart is again very convenient as we can helm on it only, or we can helm a set of charts that includes this backup chart (or the chart could even be a dependency of other charts)

I understand your point when you say that hooks are not resources managed by helm, so this is not a bug when helm says that there are no resources in the given chart… but I would argue that even if hooks are not “managed” by Helm, Hooks are _notions defined_ by Helm, so there is not really “no [Helm-defined] objects visited” in such charts because there are hooks!

**Comment by ashwinsmnth** [comment]
What is the recommendation for such use cases where we have to execute a job and delete that after its done without using hook? Because I can't execute it with hook in place since there was no resource for the hook

**Comment by NandoTheessen** [comment]
So, we do have a scencario in which we'd like to run a pre-install hook and not create a resource in the same workload:

During deployment, we're using a chart that gets values from hashicorp vault & creates secrets from them (using vault & consul-template). We do not want to integrate this into the charts themselves as we'd have to use custom charts then, which we'd have to maintain.
So a pre-install hook would be perfect for this as it can execute before anything else and prepare the secrets needed, however we run into this error. If there is a workaround please let me know!

**Comment by NandoTheessen** [comment]
Making this behavior optional, would be great!

**Comment by TonyApuzzo** [comment]
This issue prevents causes the tutorial here: https://helm.sh/docs/chart_template_guide/#a-first-template to fail. 

```
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```

**Comment by rbq** [comment]
Oh, so this error is not actually an error, that's great news. If this can't be fixed, would it be possible to change the message into something that explains that everything is fine?

**Comment by bslota** [comment]
Hi! Could anyone give an update on this topic, please? I have a very similar case to what has already been mentioned. Although the deployment is successful, job finishes, helm states the error. Is there any fix or workaround for this?

**Comment by bacongobbler** [comment]
Thank you everyone for your comments/opinions on this.

A lot of the examples provided deal with firing off a job as a one-off thing. I'm curious to understand why Helm is being used in this way.

As context, Helm was designed to be used as a package manager: it installs and manages an application in a traditional manner, similar to `apt`, `yum` and `brew`.

Chart hooks are quite similar to other package manager's pre-install/post-install hook systems. They're meant to be used as supportive tooling for the package to be installed, but are not meant to be used as a stand-alone object. In other words, they were never designed to be *the* package.

The examples provided above are similar to asking `brew` to fire a pre-install hook, but never install something in the operating system. I'm having a really tough time understanding why a package manager should accommodate this workflow.

Are there previous examples where this workflow has been provided by other package managers?

**Comment by talam** [comment]
@bacongobbler my use case doesn't involve hooks or anything like that so this may be an outlier. I just want to be able to install CRDs individually without any other necessary resources in the `templates` directory as mentioned in #7247. This is part of a work around due to #6581 where I am unable to put new crd versions in the same chart. I would expect this to be possible without an error since a chart can contain arbitrary kubernetes resources. This is occurring with helm3 for additional context.

**Comment by rbq** [comment]
> Are there previous examples where this workflow has been provided by other package managers?

1. I think traditional package repositories often contain meta-packages that only exist to bundle dependencies (or signal some sort of system state).
2. I believe it is usually possible to start developing a package and have working tests and CI right from the start, without making it install any placeholder resources.
3. Packages are often configurable, letting users switch individual components on and off. A combination of settings that results in no resources not being deployed might be the desired initial state—especially when the Chart is used in an automated way, e. g. packaged as an Operator.

**Comment by enver** [comment]
As a workaround just define dummy service i.e.
```kind: Service
apiVersion: v1
metadata:
 name: google
spec:
 type: ExternalName
 externalName: google.com```

**Comment by rushins** [comment]
hello 

i ran into the same issue and i dont see any solution here. can some one provide what needs to be done.

Error: UPGRADE FAILED: "job1-controller"  has no deployed releases

**Comment by smark88** [comment]
This still appears to be happening 
```
{{- range .Values.secrets }}
---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: {{ .secretName }}
  labels:
    {{- include "create-secret-manager-secret.labels" $ | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
  {{- if .nameSpace }}
  namespace: {{ .nameSpace }}
  {{- end }}
spec:
  name: {{ .secretName }}
  keysMap:
    {{- range .vals}}
    {{ .kubeSecretKey }}:
      path: {{ .path }}
      {{- if .encoding }}
      encoding: {{ .encoding }}
      {{- end }}
      key: {{ .vaultKey }}
    {{- end }}
{{- end -}}
```


Error: no objects visited                                                                                                                        
Error: plugin "namespace" exited with error

**Comment by amit17051980** [comment]
Do we have any fix?

**Comment by bacongobbler** [comment]
stop adding `helm.sh/hook: pre-install` if you're only installing secrets.

**Comment by vaishali-prophecy** [comment]
In what all scenarios is this error seen? Because I am not using any hooks like pre-install, but still getting the error as "No objects visited".

**Comment by amit17051980** [comment]
Hi Vaishali,

**My Use Case:**

It is important to note that if you are importing secrets from *.tgz file, then it might work as expected (as long as it was packaged using helm package command). If you are extracting the package using tar -xvf *.tgz, then it doesn't extract the secrets charts properly in MacBook, and if you install from folder, then this cause the error.

My tar looks like this when I print the content, but actually when I try to unpack it, it extracts differently. Could be in Helm2, it is not possible to unpack it easily? I tried various posts to get the right command to extract and update the security as per our need, and install from there.

 _tar -tvf cs-secrets-16.7.1000-0847.tgz_
-rwxr-xr-x  0 0      0         149  1 Jan  1970 cs-secrets/Chart.yaml
-rwxr-xr-x  0 0      0        2320  1 Jan  1970 cs-secrets/values.yaml
-rwxr-xr-x  0 0      0        1089  1 Jan  1970 cs-secrets\\templates\\_helpers.tpl
-rwxr-xr-x  0 0      0        2406  1 Jan  1970 cs-secrets\\templates\\secrets.yaml
-rwxr-xr-x  0 0      0         354  1 Jan  1970 cs-secrets\\.helmignore


Amit

**Comment by bacongobbler** [comment]
> In what all scenarios is this error seen?

@vaishali-prophecy see https://github.com/helm/helm/issues/4670#issuecomment-472896695

**Comment by bacongobbler** [comment]
> My tar looks like this when I print the content, but actually when I try to unpack it, it extracts differently. Could be in Helm2, it is not possible to unpack it easily?

The chart format is the same between Helm 2 and Helm 3... Can you perhaps explain what you are trying to do, and what issues you're running into?

**Comment by amit17051980** [comment]
> > My tar looks like this when I print the content, but actually when I try to unpack it, it extracts differently. Could be in Helm2, it is not possible to unpack it easily?
> 
> The chart format is the same between Helm 2 and Helm 3... Can you perhaps explain what you are trying to do, and what issues you're running into?

Hi Mat,

Our Product Vendor Documentations are asking to install the **secrets.tgz** post modifications of the values in the **values.yaml** file. It would be nice if you could guide us how can I unpack (preserves the directory structure) the secrets.tgz provided by the Product Vendor, and repackage it using Helm2 (supported by Product Vendor). 

As I'm new to the helm, I used tar -xvf secrets.tgz, but it doesn't preserve the directory structure as printed in the **tar -tvf secrets.tgz**. It seems there are other ways to override the secrets without unpacking the secrets.tgz.

Please help!

**Comment by bacongobbler** [comment]
That should work. That's what I use for unpacking and inspecting charts, and [that's how Helm does it](https://github.com/helm/helm/blob/598dc504d634332f955f5e984d1d53696ba07abc/pkg/chartutil/expand.go#L34-L81), too.

**Comment by medined** [comment]
Here is another example if this message:

```
NAMESPACE=sandbox

cat <<EOF > yaml/values.jenkins.yaml
rbac:
  install: true
  apiVersion: v1
EOF

helm install jenkins stable/jenkins \
  -f yaml/values.jenkins.yaml \
  --namespace $NAMESPACE
```

**Comment by adelbertc** [comment]
I am hitting this problem - I have a couple Charts all which share the same Secret and my initial plan was to create a Chart just for those Secrets, but then I hit the error described in the original post. I imagine this must be a common scenario with multiple Pods sharing the same Secret - what is the advised practice for this in Helm 3?

**Comment by vishnu-anil** [comment]
I am having the same issue and no way to troubleshoot the same. When i enter help upgrade it just fails with the message "Release failed: no objects visited". 

When i run with --debug no XRROR is shown. Is there a solution to this?

**Comment by arun007amazon** [comment]
One possible cause is due to pod allocation policy, I have seen this error while deploying more replicas than the number of nodes.

**Comment by invidian** [comment]
I'm hitting the same issue when trying to install a chart, which only installs the CRDs from `crds` directory.

**Comment by Beatus8** [comment]
I'm having the same issue with the Hook for a Job. I need to create a Job and wait for it's completion, but I can't do this with the --wait flag, since it doesn't work for a Job. When I switched to setting a Job with the Hook, I came into this problem. What is the workaround?
P.S. Users are weird sometimes and we need strange use-cases, such as a Job creation in a separate deployment flow. Sorry for that :) But since it is allowed by Helm to have different resources deployed separately, it would be good to have a workaround for such kind of issues.

**Comment by mkoertgen** [comment]
My use case: Have helm execute a job (custom built docker image/pod).
My workaround is to have a deployment with `replicaCount: 0`

Works for me!

**Comment by Koriit** [comment]
Hi, in our case our templates have been guarded with conditions. We forgot to set the values and as a result, no template was rendered. Just letting know.

**Comment by invidian** [comment]
Not stale please.

**Comment by invidian** [comment]
Not stale annyoing bot.

**Comment by invidian** [comment]
Not stale

**Comment by joejulian** [comment]
Helm 2 is no longer supported.

Helm 3:
Per the description I created a chart (`helm create chart foo`). In that chart I removed everything under templates and created a single template file: 

> templates/secret.yaml
```
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-secrets
  labels:
    chart:    {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
    release:  {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
data:
{{- range $key, $val := .Values.secrets }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
```

I set the chart's values.yaml as specified in the issue description:

> values.yaml
```
---
secrets:
  test: YmFzZWw=
```

Then install it

```
helm install foo foo
```

```
NAME: foo
LAST DEPLOYED: Thu Jan 13 10:56:48 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

Is this issue still valid for helm 3?

**Comment by joejulian** [comment]
Also tried with making it a hook with no error:

> templates/secret.yaml
```
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    helm.sh/hook: "pre-install,pre-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation"
  name: {{ $.Release.Name }}-secrets
  labels:
    chart:    {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
    release:  {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
data:
{{- range $key, $val := .Values.secrets }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
```

**Comment by invidian** [comment]
With the following Helm version:
```
$ helm version
version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.17.4"}
```

And following reproducing steps:
```sh
helm create foo
cd foo && rm -r ./templates
mkdir -p ./crds/
cat <<EOF > ./crds/test.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: crontabs.stable.example.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: stable.example.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cronSpec:
                  type: string
                image:
                  type: string
                replicas:
                  type: integer
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: crontabs
    # singular name to be used as an alias on the CLI and for display
    singular: crontab
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: CronTab
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - ct
EOF
helm install test .
```

I no longer get any warnings or errors!

**Comment by joejulian** [comment]
Thanks for confirming. I'll close this issue then.
