### ISSUE TITLE
--debug does not output the template in console

### ISSUE THREAD

**Issue by arthurgustin** [helm/helm#4674]
I've lost time on helm yesterday because I had a badly formatted line and the --debug informations were not relevant without the associated template.

I suggest displaying the template in case of error and success so that people (devOps) can spot the issue in CI logs for instance.

**Comment by bacongobbler** [comment]
marking as low hanging fruit if someone from the community wants to pick this one up.

**Comment by openmohan** [comment]
I would like to work on this.

As I am new to Kube and helm.

**Comment by openmohan** [comment]
Working on it.

**Comment by bacongobbler** [comment]
fixed in Helm 3.
