### ISSUE TITLE
Tiller can't find any preferred addresses

### ISSUE THREAD

**Issue by florianrusch** [helm/helm#4676]
I've installed the `prometheus-adapter` and the `prometheus-operator` with helm in my cluster. After this, I getting the following error message on every helm command (e.g. `helm ls`): `Error: forwarding ports: error upgrading connection: no preferred addresses found; known addresses: [{Hostname xxx}]` The log of the tiller pod shows a similar error: `Error from server: no preferred addresses found; known addresses: [{Hostname xxx}]`

Does someone have an idea whats wrong?

I've removed both(prometheus-adapter & -operator) from the cluster and tried to install tiller multiple times. Nothing changed.

Output of `helm version`:
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Error: cannot connect to Tiller

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.0-rc.1", GitCommit:"3e4aee86dfaf933f03e052859c0a1f52704d4fef", GitTreeState:"clean", BuildDate:"2018-09-18T21:08:06Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
SysEleven (OpenStack)

**Comment by bacongobbler** [comment]
Hmm, not sure. Can you try the following and see if you can nail down whether it's an upstream issue?

```
TILLER_POD=$(kubectl -n kube-system get po | grep tiller | awk '{ print $1 }')
kubectl -n kube-system port-forward $(TILLER_POD) 44134:44134
HELM_HOST=:44134 helm list
```

**Comment by florianrusch** [comment]
I've already tested to forward the port. It doesn't work. But I currently don't know the error message. I have to take a look tomorrow.

**Comment by florianrusch** [comment]
@bacongobbler Here is the output of this commands:
```shell
➜  ~ kubectl -n kube-system get po | grep tiller | awk '{ print $1 }'
tiller-deploy-759cb9df9-c66sm
➜  ~ kubectl -n kube-system port-forward tiller-deploy-759cb9df9-c66sm 44134:44134
error: error upgrading connection: no preferred addresses found; known addresses: [{Hostname kubermatic-sm5gf8vpn4-t6mn8}]
```

**Comment by florianrusch** [comment]
Sorry, this problem is not related to Helm.

The problem is related to kubelet. Kubelet seems to have forgotten his IP addresses (see https://github.com/kubernetes/kubernetes/issues/68270).
A short `sudo systemctl restart kubelet` fixed this issue.
