### ISSUE TITLE
Helm ls does not show all releases

### ISSUE THREAD

**Issue by AmazingTurtle** [helm/helm#4678]
I'm connecting with the default service account from gitlab CI to my cluster and run some `helm upgrade` and `helm ls` which shows this:

```
NAME               	REVISION	UPDATED                 	STATUS  	CHART                    	NAMESPACE 
production-backend 	10      	Wed Sep 12 07:41:48 2018	DEPLOYED	pdf-text-1.0.0           	cheesy
production-backend 	22      	Wed Sep 19 19:49:24 2018	DEPLOYED	cheesy-backend-1.0.0 	cheesy
production-frontend	15      	Wed Sep 19 17:15:07 2018	DEPLOYED	cheesy-frontend-0.1.0	cheesy
```

By the way: as you can see, there are two different charts deployed with the same name (that's strange).
But the main problem is, that if I connect to my cluster from shell and do some `helm ls`, this is what comes out:

```
NAME            REVISION        UPDATED                         STATUS          CHART                   NAMESPACE
bumptious-squid 1               Sun Aug 19 14:36:14 2018        DEPLOYED        openvpn-3.8.0           default
cert-manager    4               Tue Aug 21 21:51:46 2018        DEPLOYED        cert-manager-0.2.10     default
```

Totally different, right? I don't have RBAC enabled. 

```
$ helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

Screenshot of my workloads:

![image](https://user-images.githubusercontent.com/2357438/45816141-15899d00-bcdb-11e8-8459-698523b05ae5.png)

**Comment by bacongobbler** [comment]
Looks like you have two tiller instances, one of which is deploying to the `cheesy` namespace (the first one), and the other deploying to the `default` namespace (the second one). Each tiller instance has its own list of releases it manages, and to switch between them you can either use the TILLER_NAMESPACE environment variable or `helm list --tiller-namespace`.

Does that make sense?

**Comment by AmazingTurtle** [comment]
@bacongobbler makes perfectly sense. Can't believe I've been so blind. Thanks alot, works now!
