### ISSUE TITLE
[Documentation] Add a nice search experience in the website

### ISSUE THREAD

**Issue by clemfromspace** [helm/helm#4679]
Hello there 👋 

I'm working at Algolia on a project called [DocSearch](https://community.algolia.com/docsearch/) which goal is to enhance documentation websites with exhaustive, fast and relevant search. You might have seen DocSearch live already on websites like Bootstrap, ESLint or Babel.

A colleague of mine who is browsing the helm documentation a lot, suggested me to open an issue to ask you if you would like to integrate DocSearch on it.

We put together a [demo](https://docsearch-helm.netlify.com/) of what DocSearch on the Helm documentation website could look like here. Feel free to try it and let us know what you think.

<img width="706" alt="screen shot 2018-09-21 at 12 56 54" src="https://user-images.githubusercontent.com/5702266/45877374-e25c1200-bd9d-11e8-8f59-8c78a08b5b57.png">

Would that be something you'd be interested in? If so, we'd be happy to work on integrating it through a PR.

**Comment by bacongobbler** [comment]
Hey @clemfromspace! Yes, we would love a PR over at https://github.com/helm/helm-www. Let us know if you have any further questions.

**Comment by bacongobbler** [comment]
closing in favour of https://github.com/helm/helm-www/issues/56 to track the issue from the source. @clemfromspace please feel free to continue the conversation over there. :) Thanks!
