### ISSUE TITLE
feature request: option in `helm template` to split output files when using {{ range }}

### ISSUE THREAD

**Issue by fvigotti** [helm/helm#4680]
Hi
When using helm template to generate static yaml files, and when using `--output-dir`  , helm correctly generate multiple files according to source files..

would be useful if in I can add some hints (as  yaml comments  which also may include the output filename maybe ? ) to specify a different filename...
so when using a range to create a list of resources , (in one of my specific use-case it's a job to initialize/destroy resources on specific list of hostname whenre the pv/pvc with local storage would end )  those can be called/created/deleted using `kubectl apply -f` one by one without the "all or nothing" 
because I can create some manteinance jobs/pod with proper configuration using the `range` but then I have to use them separatedly..

I hope to have been clear enough on why it would be useful ;) 

thank you ,
Francesco

**Comment by washtubs** [comment]
It's a bit late but, with nothing official I just decided to make something simple. Took like 10 minutes

As a script:

```
#!/usr/bin/env bash

# helm-fan-out

if [ -z "$1" ]; then
    echo "Please provide an output directory"
    exit 1
fi

awk -vout=$1 -F": " '
   $0~/^# Source: / {
       file=out"/"$2;
       print "Creating "file;
       system ("mkdir -p $(dirname "file"); echo -n "" > "file);
   }
   $0!~/^#/ && $0!="---" {
       print $0 >> file;
   }'

```

Put it in your path and run it with `helm template --dry-run foo ./foo | helm-fan-out out` 

As a one liner:

```
helm template --dry-run foo ./foo | awk -vout=out -F": " '$0~/^# Source: /{file=out"/"$2; print "Creating "file; system ("mkdir -p $(dirname "file"); echo -n "" > "file)} $0!~/^#/ && $0!="---"{print $0 >> file}'
```

you can change the out directory to foo-out by changing `-vout=foo-out`

**Comment by Jean-Baptiste-Lasselle** [comment]
@washtubs like so thank you :)

**Comment by washtubs** [comment]
Glad you like it @Jean-Baptiste-Lasselle . Please note I just updated it. I realized in the old version if there were multiple k8s resources in a file, the last one would clobber all the previous ones (e.g. if you have a service account followed by a deployment in the same template, the deployment would win). Now they are concatenated properly.

**Comment by Jean-Baptiste-Lasselle** [comment]
@washtubs I had a clean one template file / One Kubernetes Ressource Definition, but thank you so much for mentioning, and I want to mention the use case : 

I have to debug a helm chart that's pretty complicated, SO I have to check all generated `*.yaml` components of the whole thing that Helm deploys 

I mean maybe there a subject for a whole set of helm features, on the testing / debugging side... : 

It'd be nice to have like a `helm debug`, wiht a `helm template  --watch`, and `helm --watch` so that you can modify the `values.yaml` of the Helm Chart under analyzis... something like that...

The best, to me, would be something similar to `angular / karma / jasmine` for angular coninuous testing/debugging , also with variables dynamic inspection on the fly etc...

**Comment by Jean-Baptiste-Lasselle** [comment]
@washtubs just to check, does this one-liner actually include your today's update ? 

```bash 
helm template --dry-run jbltest operations/am/ | awk -vout=operations/am/rendering -F": " '$0~/^# Source: /{file=out"/"$2; print "Creating "file; system ("mkdir -p $(dirname "file"); echo -n "" > "file)} $0!~/^#/ && $0!="---"{print $0 >> file}'
```

**Comment by bacongobbler** [comment]
thanks @washtubs for the script. Perhaps that can be turned into a plugin.

Due to the way `helm template` works today, I do not foresee this becoming a feature for Helm. I do see this being a useful plugin, however. Please have a look at https://helm.sh/docs/topics/plugins/ for more details.

Thanks!

**Comment by kamalid** [comment]
> @washtubs just to check, does this one-liner actually include your today's update ?
> 
> ```shell
> helm template --dry-run jbltest operations/am/ | awk -vout=operations/am/rendering -F": " '$0~/^# Source: /{file=out"/"$2; print "Creating "file; system ("mkdir -p $(dirname "file"); echo -n "" > "file)} $0!~/^#/ && $0!="---"{print $0 >> file}'
> ```

This works great until you have multiple object in the same deployment file defined. it will overwrite them and keep the last one only.

**Comment by raelga** [comment]
> This works great until you have multiple object in the same deployment file defined. it will overwrite them and keep the last one only.

That can be solved tweaking the awk script, example:

```shell
rm -fR tmp/cert-manager/; ./bin/helm-v3.8.2 template --set installCRDs=true --include-crds helm-charts/cert-manager | awk -vout=tmp/ -F": " '$0~/^# Source: /{file=out"/"$2; print "Creating "file; system ("mkdir -p $(dirname "file"); echo ""--- >> "file)} $0!~/^#/ && $0!="---"{print $0 >> file}' 
```

**Comment by runejuhl** [comment]
For posterity here's an updated version of the script by @washtubs that puts the document separator (`---`) on the top and uses append (`>>`) to avoid clobbering existing files with the same file name:

```sh
#!/usr/bin/env bash
# Based on https://github.com/helm/helm/issues/4680#issuecomment-613201032
#
# helm-fan-out

if [ -z "$1" ]; then
    echo "Please provide an output directory"
    exit 1
fi

awk -vout="$1" -F": " '
  $0~/^# Source: / {
    file=out"/"$2;
    if (!(file in filemap)) {
      filemap[file] = 1
      print "Creating "file;
      system ("mkdir -p $(dirname "file")");
      print "---" >> file;
    }
  }
  $0!~/^# Source: / {
    if ($0!~/^---$/) {
      if (file) {
        print $0 >> file;
      }
    }
  }'
```

**Comment by marniks7** [comment]
Here is another option how to split:
https://github.com/patrickdappollonio/kubectl-slice
I found it better for my cases then in [comment above](https://github.com/helm/helm/issues/4680#issuecomment-1152289297).
P.s. However in kubectl-slice there could be a problem with result file namings, it doesn't take it from comment '`^# Source: /`

**Comment by hinorashi** [comment]
> 



> It's a bit late, but with nothing official I just decided to make something simple. Took like 10 minutes

> As a one liner:
> 
> ```
> helm template --dry-run foo ./foo | awk -vout=out -F": " '$0~/^# Source: /{file=out"/"$2; print "Creating "file; system ("mkdir -p $(dirname "file"); echo -n "" > "file)} $0!~/^#/ && $0!="---"{print $0 >> file}'
> ```
> 
> you can change the out directory to foo-out by changing `-vout=foo-out`

Thanks, it helps a lot, I change a little bit for my use case, which only get the filename not the absolute path:
```sh
helm template --dry-run foo ./foo | awk -vout=out -F"/" '$0~/^# Source: /{file=out"/"$NF; print "Creating "file; system ("mkdir -p $(dirname "file"); echo -n "" > "file)} $0!~/^#/ && $0!="---"{print $0 >> file}'
```

**Comment by grem11n** [comment]
Keep in mind that the `awk` approach proposed in the comments won't work if you have multi-document templates. In such case, file names in `# Source: ` will be duplicated. Therefore, manifests will override each other.

If this is the case for you, you can use `yq` utility (`v4.x). This utility is YAML-aware, so it will split documents properly. [See the docs](https://mikefarah.gitbook.io/yq/usage/split-into-multiple-files).

Unfortunately, you cannot generate fancy names (or I haven't found how).

```bash
helm template foo ./foo | yq -s '"prefix-" + $index'
```

**Comment by jeroenvermeulen** [comment]
Small bugfix, [this version](https://github.com/helm/helm/issues/4680#issuecomment-1152289297) did in some cases leave out the `---` between multiple resources in one Yaml file.
```bash
#!/usr/bin/env bash
# Based on https://github.com/helm/helm/issues/4680#issuecomment-1152289297
# helm-fan-out

if [ -z "$1" ]; then
    echo "Please provide an output directory"
    exit 1
fi

awk -vout="$1" -F": " '
  $0~/^# Source: / {
    file=out"/"$2;
    if (!(file in filemap)) {
      filemap[file] = 1
      print "Creating "file;
      system ("mkdir -p $(dirname "file")");
    }
    print "---" >> file;
  }
  $0!~/^# Source: / {
    if ($0!~/^---$/) {
      if (file) {
        print $0 >> file;
      }
    }
  }'
```

**Comment by webdz9r** [comment]
why not use [kubesplit ](https://github.com/looztra/kubesplit)

**Comment by rojomisin** [comment]
chatgpt helped escape this into a bash alias
```bash
alias yaml_split='awk -vout=out -F"/" '"'"'$0~/^# Source: /{file=out"/"$NF; print "Creating "file; system ("mkdir -p $(dirname "file"); echo -n "" > "file)} $0!~/^#/ && $0!="---"{print $0 >> file}'"'"''
```

`helm template --dry-run foo . | yaml_split` 

I was kind of surprised helm didn't have this already

**Comment by dwieland** [comment]
We have a similar situation. What worked for us so far:
`helm template foo . --dry-run | yq -s '.kind + "-" + .metadata.name'`

**Comment by Run1e** [comment]
Since none of these did exactly what I wanted (specifically they didn't handle it well when multiple resources were in the same template) here's a hacky bash function that handles it better through some python:

```bash
helm_split() {
	cat | python3 -c '
import sys
from os.path import split
from collections import defaultdict
if len(sys.argv) < 2: raise ValueError("provide an output dir to helm_split")
o = sys.argv[1]
m = defaultdict(list)
for c in filter(bool, sys.stdin.read().split("---\n# Source: ")):
	m[split(c.split("\n")[0])[-1]].append("# " + c)
for f, r in m.items():
	with open("/".join((o, f)), "w") as f:
		f.write("---\n" + "---\n".join(r))
' $1
}
```
Simply copy that bash function and then to emit rendered yaml files to the `rendered` folder, do:
```bash
helm template $RELEASE_NAME $CHART | helm_split rendered
```
Then you can use tools like [yamllint](https://github.com/adrienverge/yamllint) and [kubeconform](https://github.com/yannh/kubeconform) to verify both yaml and manifest correctness:
```bash
yamllint rendered
kubeconform rendered
```
