### ISSUE TITLE
Connecting the local docker image repository to get tiller while using helm init

### ISSUE THREAD

**Issue by mmshaikh88** [helm/helm#4687]
I am using helm 2.9.1 and have the tiller docker manually uploaded to the local docker image repository. My machine is not connected to internet.
I would like to know that while issuing the helm init to deploy the helm and tiller, how do I specify the tiller path to deploy for helm init in cli or config file?

**Comment by mmshaikh88** [comment]
Just wanted to clarify that I have a local image repository where I have uploaded the tiller image? Is there a way to specify the tiller download path like:
helm init --tiller-registry http://10.15.200.11:5000/app/tiller:v2.9.1

**Comment by mmshaikh88** [comment]
I am able to use the dry-run option to generate the yaml file and after changing the image location I am able to get tiller deployed, but I wonder if helm has the option to specify the docker image repo?

**Comment by bacongobbler** [comment]
You can  use `helm init --tiller-image`

**Comment by prakashtp** [comment]
Is there a way to download the tiller image and load into the private docker registry

**Comment by bacongobbler** [comment]
`docker pull gcr.io/kubernetes-helm/tiller:version`. Either that or you can build it from source.

I'm going to close this ticket as answered but please let us know if there are further questions that need addressing. Thanks!

**Comment by mmshaikh88** [comment]
helm init --tiller-image to the local image repository worked, thanks,

**Comment by mmshaikh88** [comment]
> his ticket as answered but please let us know if there are further questions that need addressing. Thanks!

I have done something similar, My kube cluster is not connected to internet and therefore I have followed the steps as:
1. Pulled the docker image using docker pull as specified above.
2. Save the docker image as tgz using docker save command
3. Copied the tgz to the kube cluster machine
4. Upload the image using docker push to the local registry accessible from the private kube cluster.
