### ISSUE TITLE
Upgrade Statefulset with new image:tag fails

### ISSUE THREAD

**Issue by discostur** [helm/helm#4688]
I've installed a redis statefulset via helm in our cluster:

https://github.com/helm/charts/tree/master/stable/redis

Today, the helmchart-version and image-version increased and my CI pipeline fails. normally i do the upgrade like this:

```
helm upgrade --install --recreate-pods redis stable/redis --values values.redis.yaml
```

If the chart is not installed helm will install it - if the chart is already installed, helm does just recreate the pods. Today, after the new helmchart got released i see the following error message:

```
Error: UPGRADE FAILED: Deployment.apps "redis-slave" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"chart":"redis-4.0.1", "release":"redis", "role":"slave", "app":"redis"}: `selector` does not match template `labels` && StatefulSet.apps "redis-master" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden.
```

Shouldn't the upgrade work with the --recreate-pods flag? Shouldn't helm be able to rollout the new version?

Output of `helm version`: 2.10.0
Output of `kubectl version`: 1.10.8

**Comment by jascott1** [comment]
Hi @discostur 

I would think this would work but something appears to be wrong. I would compare the final manifests from each version to see what has changed. Also I noticed this recent change with update strategy, could that be related? https://github.com/helm/charts/pull/7619/files#diff-30e182e3b12b994b9ab3ff39cf0dd42b

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
