### ISSUE TITLE
Can't run helm init

### ISSUE THREAD

**Issue by PFadel** [helm/helm#4689]
Output of `helm version`: 
`Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}`

Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.0-rc.1", GitCommit:"3e4aee86dfaf933f03e052859c0a1f52704d4fef", GitTreeState:"clean", BuildDate:"2018-09-18T21:08:06Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
`minikube version: v0.28.2`

I just installed helm in Ubuntu 18.04 using snap but I can't run `helm init`. The errors are as follows:

```bash
helm init   
$HELM_HOME has been configured at /home/user/snap/helm/common.
Error: could not get kubernetes client: could not get Kubernetes config for context "": Error loading config file "/home/user/snap/helm/common/kube/config": open /home/user/snap/helm/common/kube/config: permission denied
```

```bash
sudo helm init   
$HELM_HOME has been configured at /root/snap/helm/common.
Error: could not get kubernetes client: could not get Kubernetes config for context "": invalid configuration: [unable to read client-cert /home/user/.minikube/client.crt for minikube due to open /home/user/.minikube/client.crt: permission denied, unable to read client-key /home/user/.minikube/client.key for minikube due to open /home/user/.minikube/client.key: permission denied, unable to read certificate-authority /home/user/.minikube/ca.crt for minikube due to open /home/user/.minikube/ca.crt: permission denied]
```

Any help would be appreciated.

**Comment by PFadel** [comment]
UPDATE: After installing with the script `get_helm.sh` it worked.

Helm version is now `v2.10.0` though.

**Comment by bacongobbler** [comment]
If you have further issues with the snap package, can you please [file a ticket here](https://github.com/snapcrafters/helm)? The snap package has been known to have a few issues which aren't present by using more conventional installation methods, such as the get script.

As far as your second comment though,

> Helm version is now `v2.10.0` though.

If you're using the `get_helm` script, you can change the version through the VERSION flag:

```
><> export DESIRED_VERSION=v2.9.1
><> curl https://raw.githubusercontent.com/helm/helm/master/scripts/get | bash
```

Hope this helps
