### ISSUE TITLE
Tiller issue after upgrading : the server could not find the requested resource

### ISSUE THREAD

**Issue by pulpbill** [helm/helm#4699]
Hi, our gitlab-runner updated to latest version, so we updated helm/tiller at k8s but then all deploys of our charts failed with :
`
[tiller] 2018/09/26 13:38:51 warning: Upgrade "some-helm-release " failed: the server could not find the requested resource`

I can't find what's the resource failing. We checked our k8s cluster and everything's working ok. Actually, we manually  deployed some charts with no issue. 
We can't perform helm upgrades of deployed releases.

**Edit:** Works without --wait (which we need in prod)

Any thoughts? 

Thanks!

Output of `helm version`:
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:17:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by pulpbill** [comment]
Quick question, is this really a support issue? shouldn't it be a bug? Because immediately after using 2.11, every chart now fails to upgrade while using --wait. 

Thank you!

**Comment by bacongobbler** [comment]
Generally speaking, until it's been identified as a bug in Helm we mark it as a support ticket. Usually that means providing a reproducible test case that demonstrates the issue which we can verify against. If you can do that we can take a closer look.

Thanks!

**Comment by derekperkins** [comment]
I'm seeing the same issue when trying to deploy the etcd-operator with `create crds`

**Comment by derekperkins** [comment]
On further investigation, the bigger issue was that I couldn't install a chart that used a EtcdCluster CRD. https://github.com/vitessio/vitess/tree/master/helm/vitess

Downgrading to helm 2.10.0 allowed the installation to complete successfully.

**Comment by omegarus** [comment]
Same issue after upgrading to 2.11.0 version.

**Comment by pulpbill** [comment]
> Generally speaking, until it's been identified as a bug in Helm we mark it as a support ticket. Usually that means providing a reproducible test case that demonstrates the issue which we can verify against. If you can do that we can take a closer look.
> 
> Thanks!

Np, I understand, our environment it's quite big and, as you can imagine, we use many values that can't be shared. We are using 2.10 for now for some environments and 2.11 without --wait for others.
Thanks!

**Comment by godhand1607** [comment]
We've encountered this issue as well. Removing the `--wait` flag works as the interim fix.

Note: We're using `helm upgrade --install` on our deployment pipeline

**Comment by pulpbill** [comment]
I'm trying to get the resource that's supposed to be giving us this conflict with no luck so far. helm diff only shows a change of release number. We use` helm upgrade <release-name> <chart-name> '--values=some.global..values.yaml,<chart-name>/some.other.chart.values.yaml' --set 'App.ImageTag=xxx' --timeout 600 --wait`

**Comment by salfand** [comment]
I am getting the same issue. Using helm 2.10 the chart successfully installed however using helm version 2.11.0 it failed. Below the tiller log:

[tiller] 2018/10/11 08:09:58 preparing install for scale-occm
[storage] 2018/10/11 08:09:58 getting release history for "scale-occm"
[tiller] 2018/10/11 08:09:58 rendering occm chart using values
[tiller] 2018/10/11 08:09:58 performing install for scale-occm
[tiller] 2018/10/11 08:09:58 executing 0 crd-install hooks for scale-occm
[tiller] 2018/10/11 08:09:58 hooks complete for crd-install scale-occm
[tiller] 2018/10/11 08:09:58 executing 0 pre-install hooks for scale-occm
[tiller] 2018/10/11 08:09:58 hooks complete for pre-install scale-occm
[storage] 2018/10/11 08:09:58 getting release history for "scale-occm"
[storage] 2018/10/11 08:09:58 creating release "scale-occm.v1"
[kube] 2018/10/11 08:09:58 building resources from manifest
[kube] 2018/10/11 08:09:58 creating 3 resource(s)
[tiller] 2018/10/11 08:09:58 warning: Release "scale-occm" failed: the server could not find the requested resource
[storage] 2018/10/11 08:09:58 updating release "scale-occm.v1"
[tiller] 2018/10/11 08:09:58 failed install perform step: release scale-occm failed: the server could not find the requested resource

**Comment by tasiyo7333** [comment]
we have the same issue after upgrading to v2.11.0.

After we rollbacked to v2.10.0, this issue has not occurred yet.

**Comment by derkoe** [comment]
Same issue here with Helm v2.11.0 - seems `--wait` is broken in this release (2.9.1 and 2.10.0 work)

**Comment by derkoe** [comment]
This commit broke it efadbd88035654b2951f3958167afed014c46bc6 

This finds a deployment with "extensions/v1beta1" and then calls the api with "apps/v1" which results in "the server could not find the requested resource"

**Comment by sgandon** [comment]
We also had the issue of the mysterious `failed: the server could not find the requested resource` because of a typo in a service account manifest.
we had `aapiVersion: v1` instead of `apiVersion: v1` and strangely this typo worked on the previous helm release.

**Comment by stephanyespencer** [comment]
We had a similar issue and the same `failed: the server could not find the requested resource` error.  One of our templates was missing the ApiVersion line altogether. After adding back the line, the chart would install.

**Comment by manuel-sanchez** [comment]
Any news about this issue? We found the same behavior after upgrading --wait flag causes the deploy to fail

**Comment by aleprice** [comment]
Same issue here

We are using this command

helm upgrade <release-name> <chart-name> '--values=some.global..values.yaml,<chart-name>/some.other.chart.values.yaml' --set 'App.ImageTag=xxx' --timeout 600 --wait


Error: UPGRADE FAILED: the server could not find the requested resource

Helm image-> gcr.io/kubernetes-helm/tiller:v2.12.0

**Comment by alice-sawatzky** [comment]
5 months and a minor release later, is this ever going to get fixed?

**Comment by Alien2150** [comment]
Hey guys, we also run into the issue and tried to debug that. But i was only able to track it down to wait.go class. I assume it might be a race-condition.

So when checking those lines: https://github.com/helm/helm/blob/v2.13.0/pkg/kube/wait.go#L50 what would actually happen if the deployment request was sent but its already querying for those new pods? Maybe a small ramp-up wait (or even better provide a parameter could potentially help here). 

Cheers

**Comment by llech** [comment]
I have the same bug trying to deploy the chart https://github.com/HagaiBarel/kube-charts/blob/master/curator/templates/cronjob.yaml

The api is available on the server.

As for me, it's definitely a bug that helm gives no slightest hint what resource could not be found.

**Comment by tylercamp** [comment]
Was just running into this issue, I:

- Ran `helm install --dry-run --debug ...` 
- Copied the YAML output to a file
- Passed that file to `kubectl create -f ...`

... and found there was a syntax error in a a PVC definition in my chart. Something to try if this issue is a complete blocker.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
