### ISSUE TITLE
Feature Request: add stages to fix concurrency/dependency issues

### ISSUE THREAD

**Issue by baptiste-bonnaudet** [helm/helm#4701]
Hi, 

At the moment Helm acts similarly to a `kubectl apply` and all templates are pushed to the k8s api as they come.

It adds lots of complexity when resources depends on one another or when interacting with an external service (like GCP service broker for K8S).

I'd love to see a feature that would add stages to a helm install/upgrade to give the chart developer more flexibility and avoid workaround for race conditions.

Cheers

**Comment by krish7919** [comment]
Is there a roadmap for this?

**Comment by bacongobbler** [comment]
closing as inactive.
