### ISSUE TITLE
reference int value in helm template

### ISSUE THREAD

**Issue by yyyyyyyyyg** [helm/helm#4705]
In template:  {{ $repo }}: {{ $tag }},  tag is a big int, like "1234567890".  
By default, it will be convert to 1.23456789e+09.   
In this issue: https://github.com/helm/helm/issues/1707,  now we can use set-string.   But I did not find how to directly reference "1234567890" to string in template?

**Comment by jascott1** [comment]
Hi @yyyyyyyyyg 

You reference it just like you would from values.yaml `--set-string tag="1234567890"`

**Comment by bacongobbler** [comment]
Closing as answered. Please let us know if you have further questions. Thanks!
