### ISSUE TITLE
Tiller gets restarted during Jaeger deployment

### ISSUE THREAD

**Issue by rajboruah** [helm/helm#4706]
Output of `helm version`: 

Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Ubuntu 16.04 on-prem VM

Issue:
====
While deploying Jaeger with existing ElasticSearch, tiller pod dies and starts again. This makes Jaeger deployment fails. It deploys in the second attempt though.

Jaeger helm chart : https://github.com/helm/charts/tree/master/incubator/jaeger

Jaeger Deployment command:
====================

helm install --name jaeger  helm-charts/jaeger --set provisionDataStore.cassandra=false --set provisionDataStore.elasticsearch=false --set storage.type=elasticsearch --set storage.elasticsearch.host=elasticsearch-logging --set storage.elasticsearch.port=9200 --namespace "$namespace"

Helm error message:
=============

Error: transport is closing

Tiller pod watch:

~$  kubectl get pods tiller-deploy-778f674bf5-t95cf  -n kube-system --watch
NAME                             READY     STATUS    RESTARTS   AGE
tiller-deploy-778f674bf5-t95cf   1/1       Running   0          24s
tiller-deploy-778f674bf5-t95cf   0/1       Running   0         1m
tiller-deploy-778f674bf5-t95cf   0/1       Running   1         2m
tiller-deploy-778f674bf5-t95cf   1/1       Running   1         2m

$ kubectl describe pod tiller-deploy-778f674bf5-t95cf -n kube-system
Name:           tiller-deploy-778f674bf5-t95cf
Namespace:      kube-system
Node:           10.38.180.43/10.38.180.43
Start Time:     Thu, 27 Sep 2018 01:25:53 -0400
Labels:         app=helm
                name=tiller
                pod-template-hash=3349230691
Annotations:    <none>
Status:         Running
IP:             10.42.0.6
Controlled By:  ReplicaSet/tiller-deploy-778f674bf5
Containers:
  tiller:
    Container ID:   docker://c1a1d5be49e5b1658d11e364f7334c131e28b17744848b01b7c620c0ccaf5343
    Image:          gcr.io/kubernetes-helm/tiller:v2.11.0
    Image ID:       docker-pullable://gcr.io/kubernetes-helm/tiller@sha256:f6d8f4ab9ba993b5f5b60a6edafe86352eabe474ffeb84cb6c79b8866dce45d1
    Ports:          44134/TCP, 44135/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Running
      Started:      Thu, 27 Sep 2018 01:28:33 -0400
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Thu, 27 Sep 2018 01:25:55 -0400
      Finished:     Thu, 27 Sep 2018 01:28:31 -0400
    Ready:          True
    Restart Count:  1
    Liveness:       http-get http://:44135/liveness delay=1s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:44135/readiness delay=1s timeout=1s period=10s #success=1 #failure=3
    Environment:
      TILLER_NAMESPACE:    kube-system
      TILLER_HISTORY_MAX:  0
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from tiller-token-thjb2 (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          True
  PodScheduled   True
Volumes:
  tiller-token-thjb2:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  tiller-token-thjb2
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                 Age              From                   Message
  ----     ------                 ----             ----                   -------
  Normal   Scheduled              4m               default-scheduler      Successfully assigned tiller-deploy-778f674bf5-t95cf to 10.38.180.43
  Normal   SuccessfulMountVolume  4m               kubelet, 10.38.180.43  MountVolume.SetUp succeeded for volume "tiller-token-thjb2"
  Warning  Unhealthy              2m (x3 over 2m)  kubelet, 10.38.180.43  Liveness probe failed: Get http://10.42.0.6:44135/liveness: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy              2m (x3 over 2m)  kubelet, 10.38.180.43  Readiness probe failed: Get http://10.42.0.6:44135/readiness: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
  Normal   Pulled                 1m (x2 over 3m)  kubelet, 10.38.180.43  Container image "gcr.io/kubernetes-helm/tiller:v2.11.0" already present on machine
  Normal   Created                1m (x2 over 3m)  kubelet, 10.38.180.43  Created container
  Normal   Killing                1m               kubelet, 10.38.180.43  Killing container with id docker://tiller:Container failed liveness probe.. Container will be killed and recreated.
  Normal   Started                1m (x2 over 3m)  kubelet, 10.38.180.43  Started container
  Warning  Unhealthy              1m               kubelet, 10.38.180.43  Liveness probe failed: Get http://10.42.0.6:44135/liveness: dial tcp 10.42.0.6:44135: getsockopt: connection refused
  Warning  Unhealthy              1m (x6 over 2m)  kubelet, 10.38.180.43  Readiness probe failed: Get http://10.42.0.6:44135/readiness: dial tcp 10.42.0.6:44135: getsockopt: connection refused

$ kubectl logs tiller-deploy-778f674bf5-t95cf -n kube-system
[main] 2018/09/27 05:28:41 Starting Tiller v2.11.0 (tls=false)
[main] 2018/09/27 05:28:41 GRPC listening on :44134
[main] 2018/09/27 05:28:41 Probes listening on :44135
[main] 2018/09/27 05:28:41 Storage driver is ConfigMap
[main] 2018/09/27 05:28:41 Max history per release is 0

$ kubectl get pods -n kube-system
NAME                                      READY     STATUS      RESTARTS   AGE
kube-dns-5ccb66df65-lt4bk                 3/3       Running     0          9m
kube-dns-autoscaler-6c4b786f5-dvsjr       1/1       Running     0          9m
kube-flannel-n456k                        2/2       Running     0          9m
kubernetes-dashboard-7d5dcdb6d9-4xf7q     1/1       Running     2          6m
tiller-deploy-778f674bf5-t95cf            1/1       Running     1          6m

Special Note:
=========
I am a shell script and deploying multiple charts all together sequentially ( EFK, Prometheus/Grafana etc also include and deploying Jaeger at the end) from within that script. In a fresh k8s cluster, while running the script for the first time, Tiller always crashes. Rerunning the script afterwards work though. Tiller never fails for other charts deployments.

**Comment by jascott1** [comment]
Hi @rajboruah 

Does the VM run low on resources? It sounds like the whole system is slowing down to the point where Tiller doesn't pass its checks and gets restarted.

**Comment by rajboruah** [comment]
Hi @jascott1 

You are right. When I increased CPU count, it worked fine. Thanks.
By the way, may I know , from the logs, how did you find resources are low ?

**Comment by jascott1** [comment]
@rajboruah No logs, I have just experienced similar before :| Glad you got it figured out.

**Comment by rajboruah** [comment]
Thank you so much @jascott1 . This was a great help !
