### ISSUE TITLE
Empty helm.sh/resource-policy annotation should not keep the resource

### ISSUE THREAD

**Issue by sebastien-prudhomme** [helm/helm#4713]
Output of `helm version`: v2.10.0

I was surprised that when using the stable/postgresql chart, the PVC was not destroyed when i delete the Helm release.

In this chart, the default value for "helm.sh/resource-policy" annotation is "" and not "keep" so the PVC should be destroyed.

After looking in pkg/tiller/resource_policy.go, seems that the "if resourcePolicyType == keepPolicy" should be complemented by an "else" that adds the manifest in the "remaining" array.

**Comment by technosophos** [comment]
For backward compatibility reasons, we could not make this change in Helm 2 without risking breaking existing implementations (in ways that would result in data loss).

For that reason, an empty `resource-policy` annotation MUST be treated implicitly as `keep`. In other words, `keep` is the default resource policy.
