### ISSUE TITLE
why we need to specify --namespace flag to deploy chart in diff namespace 

### ISSUE THREAD

**Issue by mohitkumarsharmaflux7** [helm/helm#4717]
Output of `helm version`:

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by bacongobbler** [comment]
Hi, would you mind expanding a little more on your question? Not sure I understand.

**Comment by mohitkumarsharmaflux7** [comment]
for example if we have a template in a chart and in that template, I have specified namespace but when I try to deploy the chart, it creates the resources in default namespace, so to deploy in correct namespace I have to specify the --namespace on cli when installing some chart, so is it intentional ?

**Comment by bacongobbler** [comment]
yes, this is the intended use case.

**Comment by mohitkumarsharmaflux7** [comment]
so if someone wants to deploy diff resources in diff namespaces under single chart then how will it work ?

**Comment by hickeyma** [comment]
It would seem that deploying resources into different namespaces using the same chart is due in Helm 3: https://github.com/helm/helm/issues/2060#issuecomment-306847365

@bacongobbler you can probably confirm this

**Comment by bacongobbler** [comment]
There are a few comments under [the proposal](https://github.com/helm/community/blob/master/helm-v3/003-state.md#namespacing-changes) mentioning something about adding the concept of a un-namespaced ClusterRelease which is created for charts that are cross-namespace, but I haven't heard back whether or not we're planning on implementing that ourselves or asking the community to come up with the feature.

**Comment by mohitkumarsharmaflux7** [comment]
if i  want to deploy diff resources in single namespace (non default namespace) using helm chart , i also defined the namespace : non-default  in my template files but if i dont specify the --namesapce on cli then it must create the resources in non-default , but it is creating the resources in default namesapce, so what is the sense to specify the namespace in k8s spec file ?  @bacongobbler @hickeyma

**Comment by hickeyma** [comment]
Do you need to put the namespace  in the chart files or can you just just pass it when calling `install/upgrade`?

**Comment by mohitkumarsharmaflux7** [comment]
I want to provide the namespace as a placeholder in k8s spec files and provide its value using values.yaml.

**Comment by hickeyma** [comment]
Sorry but not sure what you need. 

If you want the cluster default namespace as the default and want the ability to override it on the fly, then there is no need to add it as a placeholder. You can override it with --namespace during install when you need.

**Comment by mohitvitjaipur** [comment]
> Sorry but not sure what you need.
> 
> If you want the cluster default namespace as the default and want the ability to override it on the fly, then there is no need to add it as a placeholder. You can override it with --namespace during install when you need.

ok

**Comment by martinffx** [comment]
I'm having the same confusion.

If I define all resources to be in a namespace i.e. 

```
metadata:
  namespace: my-namespace
```

When I deploy the helm chart, I'd expect it to also be in that namespace, it is quite un-intuitive that it lands in the default namespace. What I'm looking for is a way to specify the namespace for the deployment in a file. 

Having to specify it via the cli every time I call the command seems to defeat the point of codifying everything.

Is there not a way to override the default namespace for the helm deployment to be the same namespace as the resources I've defined in my chart?
