### ISSUE TITLE
Release Helm Template Render stand alone....

### ISSUE THREAD

**Issue by ArcticSnowman** [helm/helm#4718]
The template processing engine used by helm is more that just a combination of GO text/Templates and Sprig.  

I believe that the additional functions/feature that helm has layers on top could well be useful for general template process outside of Helm/Kubernetes 

So I suggest that, if possible, the template engine be split out of core helm and made stand alone..

**Comment by hickeyma** [comment]
AFIK, this is the [architecture](https://github.com/helm/community/blob/master/helm-v3/000-helm-v3.md#the-basic-architecture) for v3. @adamreese, maybe you can confirm?

**Comment by bacongobbler** [comment]
Please see how `helm template` uses `pkg/action` (which uses `pkg/engine`) to run the template engine.
