### ISSUE TITLE
Move to golang modules

### ISSUE THREAD

**Issue by mrueg** [helm/helm#4719]
helm v2 Glide / helm v3 Go Dep should be migrated to make use of https://github.com/golang/go/wiki/Modules 
As far as I got this right, this would drop support for go-1.10 and older.

**Comment by bacongobbler** [comment]
Given that it's an experimental feature I'd hold off on switching over until it's been marked as stable for production use, so I wouldn't switch over any time soon.

**Comment by mrueg** [comment]
Understood, I see more and more projects already switching to it, but I think it's fine to wait since there has been a new glide release that fixed some issues with go 1.10/1.11 https://github.com/Masterminds/glide/releases/tag/v0.13.2

**Comment by prochac** [comment]
I use helm from AUR on Arch and every update is painfully slow because of glide

**Comment by trevex** [comment]
Just to connect this to the existing PR:
https://github.com/helm/helm/pull/5498 is working on this for Helm V3.

**Comment by jlegrone** [comment]
Closed in https://github.com/helm/helm/pull/5498.
