### ISSUE TITLE
What is the best practice for rolling upgrade of deployments with ConfigMap changes?

### ISSUE THREAD

**Issue by richstokes** [helm/helm#4722]
I had been using `helm upgrade` with the `--recreate-pods` option. Problem is this instantly terminates the original pods. It does not wait for new pods to become ready (even with readinessProbes configured), so is not really a rolling upgrade!

The reason I started using this --recreate-pods flag was due to helm not processing upgrades to ConfigMaps without it set.

I'd be interested to know what the correct approach is to be able to handle rolling upgrades when changes to ConfigMaps need to be included in the upgrade.

Output of `helm version`:
helm version                                                      (master)
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS

**Comment by bacongobbler** [comment]
This has been documented at https://docs.helm.sh/developing_charts/#automatically-roll-deployments-when-configmaps-or-secrets-change :)

**Comment by baracoder** [comment]
The linked page is no longer available

**Comment by hickeyma** [comment]
@baracoder Try this: https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
