### ISSUE TITLE
Feature Request: helm repo credentials from env vars

### ISSUE THREAD

**Issue by william-tran** [helm/helm#4723]
For authenticated repositories, the credentials are stored in plaintext in ~/.helm/repository/repositories.yaml. To further improve security, the user should have the option to use environment variables to store credentials, so they could script together their OS's keychain access [(example)](https://www.netmeister.org/blog/keychain-passwords.html) to populate those variables and avoid storing any password in plaintext on their filesystem altogether. 

Given a helm repo that requires authentication, when the user runs `helm repo add fantastic-charts https://fantastic-charts.storage.googleapis.com --username env.FANTASTIC_CHARTS_USERNAME --password env.FANTASTIC_CHARTS_PASSWORD`, then the following entry is added to ~/.helm/repository/repositories.yaml:

```
  name: fantastic-charts
  url: https://fantastic-charts.storage.googleapis.com 
  username: env.FANTASTIC_CHARTS_USERNAME
  password: env.FANTASTIC_CHARTS_PASSWORD
```

Given the above configuration, when helm needs to make a request to the `fantastic-charts` repo, then helm resolves the username and password from the environment variables `FANTASTIC_CHARTS_USERNAME` and `FANTASTIC_CHARTS_PASSWORD` respectively.

**Comment by william-tran** [comment]
For reference, #3206 was the original PR that added authentication for private repositories, and @ankushchadha you might be interested in this one given your comment on https://github.com/helm/helm/issues/3092#issuecomment-378773562.

**Comment by ankushchadha** [comment]
While usage of environment variables avoid exposing the password in the plaintext file and even on the terminal (using cmds like `history`, etc), the `printenv` cmd can still expose sensitive information. One of the ways to avoid this problem can be to use expirable access tokens instead of using actual password value.

**Comment by ankushchadha** [comment]
@eyalbe4, @rimusz  - WDYT?

**Comment by gklp** [comment]
> While usage of environment variables avoid exposing the password in the plaintext file and even on the terminal (using cmds like `history`, etc), the `printenv` cmd can still expose sensitive information. One of the ways to avoid this problem can be to use expirable access tokens instead of using actual password value.

In my humble opinion, if you want to get token from somewhere, you will use (user, pass, key, secret etc.) again. And again you will have to store them in somewhere? @ankushchadha

If someone could execute history or printenv on your OS. That mean you gave access grant permissions to user?

**Comment by granddesigntech** [comment]
Has any movement on the problem of repo passwords being stored in the clear in repositories.yaml happened since Oct 2018?

**Comment by bacongobbler** [comment]
I have not seen any movement from the community on this feature. I'd be happy to see a PR from the community implementing this functionality so that passwords can be fetched from your operating system's keyring.

**Comment by cpaika** [comment]
@bacongobbler Do you think this would be a good beginner project?  I haven't contributed to Helm before, so don't want to bite off more than I can chew, but thinking through this it shouldn't be *that* difficult (famous last words) to implement some sort of integration with the OS X keychain

**Comment by bacongobbler** [comment]
depends on how comfortable you are with Go, I suppose. Docker has a library to interact with the OS keyring. Perhaps that may be worth investigating to see how that can be used within Helm.

**Comment by dol** [comment]
I would prefer a more generic approach to this request. Instead if integrating every possible keychain and encryption method I really like the simple solution of `restic` by reading a password from an external command. https://github.com/restic/restic/pull/2094

I'm aware that restic only requires a password and helm needs username:password combination or a token. The credentials command/store could be referenced/stored in the repositories.yaml like docker is doing this with `credential helpers`: https://docs.docker.com/engine/reference/commandline/login/#credential-helpers
The corresponding command will be searched in the `PATH` folders. A default `read credentials from env vars named XY` helper script could even be provided by the helm project and installed along site to fulfill the most common case reading from environment variables.

**Comment by twellspring** [comment]
Here is a shell based solution to this issue on MacOS using the `security` app to save and pull passwords from the keychain.  History does not contain the password.

Example is uploading a helm chart to a [harbor](https://goharbor.io/) registry)

```
# security add-generic-password -a ${USER} -s harbor -w "$(jq -r '.token' ~/Downloads/robot-test-helm.json)"
# helm push test-chart-1.5.2.tgz https://harbor.aws-dev.irondev.io/chartrepo/testrepo --username  'robot$test-helm' --password  "$(security find-generic-password  -s harbor -w)"
Pushing harbor-1.5.2.tgz to https://harbor.aws-dev.irondev.io/chartrepo/ironnet...
Done.
```

**Comment by granddesigntech** [comment]
How about we just stop the “in the clear” part as a no brainer to start off
with while we all debate the best solution until the end of time huh guys?

**Comment by eyalbe4** [comment]
In case you'd like to adopt a similar approach, JFrog CLI implemented a simple master key mechanism,, which is used for encrypting the passwords. See the details [here](https://www.jfrog.com/confluence/display/CLI/JFrog+CLI#JFrogCLI-SensitiveDataEncryption). The code is open sourced, so it should be easy to adopt it.

**Comment by granddesigntech** [comment]
👍🔥
