### ISSUE TITLE
Please support `-n` as a shorthand for the `--namespace` flag

### ISSUE THREAD

**Issue by bitfield** [helm/helm#4724]
`kubectl` has this shorthand, and I keep mistakenly trying to use it with Helm too!

```
helm upgrade --install demo -n demo k8s/demo
Error: unknown shorthand flag: 'n' in -n
helm upgrade --install demo --namespace demo k8s/demo
```

**Comment by bacongobbler** [comment]
While we cannot do this for Helm 2 due to backwards compatibility reasons with the existing `-n` flag, [this has been fixed in the Helm 3 dev branch](https://github.com/helm/helm/blob/1ce594f4106acc20fb762bb4adbe35b39328146b/pkg/helm/environment/environment.go#L55).

Thanks!
