### ISSUE TITLE
Chart as skeleton and inheritence - use case

### ISSUE THREAD

**Issue by michaelgeorgeattard** [helm/helm#4727]
I have several applications sharing most of the configuration. I created a `skeleton` chart and I override configuration for each application release, something like:

```helm install skeleton --name actual_app_name --values values.yaml```

```helm install skeleton --name another_actual_app_name --values another_values.yaml```

I am storing the `skeleton` charts using chartmuseum.

I was wondering whether I can also store the "final" charts for the applications: including the base skeleton chart and the overridden values. Are subcharts useful for this purpose?

**Comment by hickeyma** [comment]
Would  "helmfile" be of use (https://github.com/roboll/helmfile) ?

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
