### ISSUE TITLE
Can local tiller deploy release configmaps to a specified namespace.

### ISSUE THREAD

**Issue by RudyBone** [helm/helm#4729]
We have a multi-tenant kube cluster.  Our tenants do not have access to the kube-system namespace. If they try to run helm/tller locally using their cluster credentials our RBAC rules prevent tiller from listing the configmaps in kube-system.   Ultimately we would like them to run a Tiller instance in their own namespace, however as of this writing Tiller does not use kube impersonate to make calls to the API server with the credentials of the tenant deploy the chart and we lose some traceablity in our Kube audit logs.

Any thoughts?

**Comment by bacongobbler** [comment]
Tiller instances can be deployed in a different namespace using `helm init --tiller-namespace foo`. Please have a look at the documentation on how to run Tiller in a separate namespace, where release configmaps are stored in the same namespace as Tiller. Note how the documentation doesn't mention anything about giving Tiller read access to `kube-system`.

https://docs.helm.sh/using_helm/#example-deploy-tiller-in-a-namespace-restricted-to-deploying-resources-only-in-that-namespace

Let us know if you have further questions.
