### ISSUE TITLE
Add helm upgrade --name

### ISSUE THREAD

**Issue by Brightside56** [helm/helm#4731]
Currently helm doesn't support name parameter for upgrade command, but I have projects XXX YYY ZZZ with services AAA BBB CCC. And service AAA for example is working for these multiple projects XXX YYY ZZZ using single chart "service-aaa".

**I would like to use:**

helm upgrade --install --name=xxx-aaa --namespace=xyz service-aaa

Please, add --name parameter for upgrade command

**Comment by hickeyma** [comment]
Would this command work for you:
```helm upgrade AAA service-aaa``` ?

**Comment by Brightside56** [comment]
Yes, thank you. Just googled it and opened issue to close it with commentary that it works this way
