### ISSUE TITLE
parent chart not able to get the right template value from the child chart when using --set

### ISSUE THREAD

**Issue by veeramarni** [helm/helm#4735]
Output of `helm version`: 2.10.0

Output of `kubectl version`: 1.10.7

Cloud Provider/Platform (AKS, GKE, Minikube etc.): GCE

Parent chart
---
NOTES.txt

```
8000: https://{{ include "child.app_port_8000_ingress" . }}
```
Child Chart
----

```
{{- define "child.app_port_8000_ingress" -}}
{{- $8000_suffix := printf "%s-%s-%s-%s" "8001-dot" .Values.env.VER "dot" .Release.Namespace | trunc 53 | trimSuffix "-" -}}
{{- printf "%s.%s" $8000_suffix .Values.ingress.domain -}}
{{- end -}}
```
Values.yaml
```
env.VER=test
```

Command:
---
```
helm upgrade -i parent-blue --namespace=blue --set "child.env.VER=yello" parent
```
Output
---

```
8000: https:// 8000-dot-test-dot-blue.domain.com
```

Which suppose to be 
---

```
8000: https:// 8000-dot-yello-dot-blue.domain.com
```

**Comment by hickeyma** [comment]
Could you try the following?

values.yaml:
```
env:
   VER: test
```
```helm upgrade -i parent-blue --namespace=blue --set env.VER=yello parent```

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
