### ISSUE TITLE
associate error message to a chart name to improve traceability

### ISSUE THREAD

**Issue by gintautassulskus** [helm/helm#4736]
I heavily rely on nested carts and the origin of errors such as this:

```
warning: skipped value for resources: Not a table.
```

take a long time to pinpoint. It would be helpful to indicate which chart exactly an error or a warning is originating from.

Output of `helm version`: 2.10

**Comment by jascott1** [comment]
Hi @gintautassulskus 

Sorry about the confusion. I agree that this message should be improved and will mark it as a bug since there is no actionable information.

**Comment by hickeyma** [comment]
I can take this if that's ok.

@gintautassulskus do you have an example chart that I can use for testing?

**Comment by gintautassulskus** [comment]
@hickeyma, thanks for taking this.

```
export CHART_DIR=/tmp/kafka-sample
git clone git@github.com:gintautassulskus/kafka-sample.git $CHART_DIR
helm lint $CHART_DIR
```

should yield you:
```
2018/10/24 14:54:00 warning: destination for resources is a table. Ignoring non-table value <nil>
==> Linting kafka-sample/
Lint OK
```

From this message, it is unclear what is the origin chart and in which line the error has occurred.
Frankly, I have no idea where this error is coming from at the moment.

**Comment by hickeyma** [comment]
@gintautassulskus @jascott1 Sorry about the delay but PR #4974 now created.

**Comment by gintautassulskus** [comment]
Fantastic news, thanks a ton, @hickeyma! 
I will leave it to the PR merge to close this issue.
