### ISSUE TITLE
Need a helm CLI built for s390x

### ISSUE THREAD

**Issue by Bindiy** [helm/helm#4738]
Hi,

Need a helm CLI built for s390x to support in the ICP env.
From the list of binaries available for other architectures, I don't see a helm CLI built for s390x. Can you build and provide a helm CLI?
Or should I work on creating a branch off the master to build a s390x helm CLI(in that case please share the build instructions). Let me know what release I should be using for the same.

**Comment by Bindiy** [comment]
@bacongobbler , I want the Helm CLI 2.9.1 version for s390x. Is that version available or should I build it manually.
If yes, please provide me the instructions with the branch details.

**Comment by Bindiy** [comment]
Closing the issue, as I wanted Helm 2.9.1 built for s390x.

**Comment by bacongobbler** [comment]
you'll need to build it from source. Instructions on building Helm from source can be found in the docs: https://docs.helm.sh/developers/
