### ISSUE TITLE
Should this INFO logs only be displayed when running with --debug

### ISSUE THREAD

**Issue by chentex** [helm/helm#4739]
Hello, I've been running some test in the render engine using the `lintmode` on, for some required values the `INFO` logs are show all the time.

The question is should this be shown all the time or should they be subject to `--debug` flag?

e.g.
https://github.com/helm/helm/blob/2ef61fdf5c46fdc47ac264926e70e0590e7b6f94/pkg/engine/engine.go#L163

**Comment by hickeyma** [comment]
The logic seems like it is an error but does not want to fail on it so the message is prefixed with [INFO] in the string and the message is written to stderr. So, if required values are missing, note it to the user and continue on.

**Comment by hickeyma** [comment]
Because it is `lintmode`, it will not fail but it still wants to inform the user that there is an error. I suppose having '[INFO]' in the string makes it a bit like a debug message.

**Comment by chentex** [comment]
It makes sense, this option is also used when running in `dry-run` I assume?

**Comment by hickeyma** [comment]
Doesn't seem to be. It fails on `--dry-run`.

**Comment by chentex** [comment]
So my next question is should we add a way to silence these warnings?

**Comment by hickeyma** [comment]
Essentially, they are error messages. The code usually fails with the error except when in `lintmode` it logs it and continues. I would therefore think that they should not be silenced.

**Comment by bacongobbler** [comment]
@cmattoon what do you think about this?

For reference, this was introduced recently in https://github.com/helm/helm/pull/4221.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
