### ISSUE TITLE
Helm plugin usage drops kube-context flag

### ISSUE THREAD

**Issue by maorfr** [helm/helm#4744]
Hello,

According to this page, the flag `kube-context` is dropped when using a plugin:
https://github.com/helm/helm/blob/master/docs/plugins.md

Can anyone explain the reason?

Thanks!

**Comment by bacongobbler** [comment]
The context is dropped because with the `useTunnel` flag, a tunnel to Tiller is provided.

Is there a particular use case where this flag might be useful for a Helm plugin?
