### ISSUE TITLE
helm starter ignore Chart.yaml appVersion

### ISSUE THREAD

**Issue by dkirrane** [helm/helm#4745]
I have a Helm starter called default with a `Chart.yaml` containing
```yaml
appVersion: "1.0.0.RELEASE"
```
But `helm create --starter default myChart` will always produce a `Chart.yaml` containing
```yaml
appVersion: "1.0"
```

Output of `helm version`: 
`Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}`

Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  `Minikube`

**Comment by jascott1** [comment]
Hi @dkirrane 

Sorry for the confusion. The starter's Chart.yaml is not used during the install as noted in the [docs](https://github.com/helm/helm/blob/master/docs/charts.md#chart-starter-packs)

**Comment by bacongobbler** [comment]
I'm going to close this answer as resolved, but please feel free to re-open if you need further clarification. Thanks!
