### ISSUE TITLE
build helm for s390x which is statically linked

### ISSUE THREAD

**Issue by champashankar** [helm/helm#4751]
I'm following this link :https://github.com/linux-on-ibm-z/docs/wiki/Building-Helm to build helm on s390x. But this builds dynamically linked helm binary.
Can some one please suggest what changes i need to do in Makefile to build this as statically linked

**Comment by bacongobbler** [comment]
I don't believe anyone out there has got a patch that could point you in the right direction, however there are quite a few articles out there on statically compiling Go binaries. See https://medium.com/@diogok/on-golang-static-binaries-cross-compiling-and-plugins-1aed33499671 for one example.

Let us know if you have any further questions.
