### ISSUE TITLE
CA Certificate issue after upgrade from 2.10.0 to 2.11.0

### ISSUE THREAD

**Issue by sappo** [helm/helm#4758]
Output of `helm version`: Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

After upgrading from 2.10.0 to 2.11.0 I'm unable to update my custom repo:
```
Unable to get an update from the "myrepo" chart repository (https://my-url.net/repository/helmchart):
        Get https://my-url.net/repository/helmchart/index.yaml: x509: certificate signed by unknown authority
```
I added the self signed certificates to my trusted root certificates which worked with 2.10.0. I even tried to pass the ca certificate with `--ca-cert` option which did not work either.

**Comment by bacongobbler** [comment]
Can you describe the command you were using? Is this `helm dep update` or `helm repo update`?

If you downgrade to 2.10 does this still work as expected?

**Comment by sappo** [comment]
It occurs when I run `helm repo update`.

Yes if I downgrade to 2.10 it still works as expected.

Matthew Fisher <notifications@github.com> schrieb am So., 14. Okt. 2018,
19:55:

**Comment by mattfarina** [comment]
@sappo I have a couple questions to try and find the problem.

1. Do you have a proxy set as an environment variable? The variables I'm asking about are HTTP_PROXY, HTTPS_PROXY and NO_PROXY.
2. Is your custom repo signed by a company intermediary or one from the open web? Trying to see if this is a publicly valid certificate or a corporate issued one.

Thanks

**Comment by sappo** [comment]
The problem vansihed, not sure why it works now.
