### ISSUE TITLE
Docs page html has no title

### ISSUE THREAD

**Issue by timthelion** [helm/helm#4760]
If I go to https://docs.helm.sh/chart_template_guide/#the-chart-template-developer-s-guide the page has no title. This means that in google search results the title is listed as the first element on the page, which is "Helm Logo". It also looks weird if I bookmark it.
![no-title](https://user-images.githubusercontent.com/1391608/46821520-3056ab00-cd89-11e8-9818-d295713bfcf4.png)

**Comment by bacongobbler** [comment]
re-opened at the correct repository: https://github.com/helm/helm-www/issues/143
