### ISSUE TITLE
Cannot perform helm init

### ISSUE THREAD

**Issue by PingPongBalls** [helm/helm#4763]
Output of `helm version`: 2.11.0

Output of `kubectl version`: 1.12.1

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  bare metal

```
$ ./helm init
Creating /home/xxxxxxxx/.helm/repository/repositories.yaml
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com
Adding local repo with URL: http://127.0.0.1:8879/charts
$HELM_HOME has been configured at /home/xxxxxxxx/.helm.
Error: error installing: Post https://10.xxx.xx.xx:6443/apis/extensions/v1beta1/namespaces/kube-system/deployments: Forbidden
```

**Comment by hickeyma** [comment]
Looks like an issue with your cluster. What is the status of your nodes: `kubectl get nodes`?

**Comment by bacongobbler** [comment]
ping

**Comment by PingPongBalls** [comment]
Thanks for the support every. Good call from hickeyma.

I am behind the proxy, so i was missing the "no_proxy" env setting....

**Comment by javamutu** [comment]
when I  run `kubectl get nodes`, error is

    The connection to the server localhost:8080 was refused - did you specify the right host or port?

when I run `hlem init `, error is

    Error: error installing: Post http://localhost:8080/apis/extensions/v1beta1/namespaces/kube-system/deployments: dial tcp [::1]:8080: connect: connection refused

**Comment by bacongobbler** [comment]
Probably your kubeconfig is misconfigured (or not configured at all, considering it's attempting to connect to localhost:8080).

**Comment by prateek100489** [comment]
I had the same issue, but running following command resolved it:
on master node:

`export no_proxy=$(hostname -i)`

then 

`helm init ..........................`
