### ISSUE TITLE
Use conventional commits as standard

### ISSUE THREAD

**Issue by ParticleDecay** [helm/helm#4768]
This is more for the helm devs, but looking through the changelogs is a mess of inconsistent commit messages. It would be beneficial to standardize on a proper format, and it seems [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.2/) has become that de facto standard.

I bring this up because multiple devs already seem to use it in this project, but not everyone. One of my teams uses [Conform](https://github.com/autonomy/conform) in our projects to automatically enforce this commit format and ensure that our types and scopes are consistent, so that's a potentially useful option that can be included in CI.

**Comment by bacongobbler** [comment]
We used to enforce this on contributors a long time ago, but found it quite limiting/frustrating for newer users, so we just [made it a suggestion](https://github.com/helm/helm/blob/master/docs/developers.md#git-conventions) but we don't enforce it.

What are your thoughts on this?

**Comment by bacongobbler** [comment]
Okay. I think we've addressed this in documentation and have precedence in place that using the convention is a good practice, but we're not going to enforce it on contributors.

Thanks for your feedback!
