### ISSUE TITLE
`--values` doesn't work with relative path

### ISSUE THREAD

**Issue by adubkov** [helm/helm#4770]
`--values` doesn't work relative path. But it works as expected with full path.

```bash
$ helm upgrade -i --values ./env/values.yaml mychart/

Error: open ./env/values.yaml: no such file or directory
``` 

Output of `helm version`: v2.11.0
Output of `kubectl version`: v1.12.0

Cloud Provider/Platform (AKS, GKE, Minikube etc.): aws

**Comment by gtseres-workable** [comment]
Could you please try the following instead?
`helm upgrade -i mychart/ --values ./env/values.yaml`

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

**Comment by o-shevchenko** [comment]
I faced the same issue. 
Any updates?
