### ISSUE TITLE
Helm status - show more detail about the resources inside the helm

### ISSUE THREAD

**Issue by shay-berman** [helm/helm#4773]
Output of `helm version`:
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.15", GitCommit:"c2bd642c70b3629223ea3b7db566a267a1e2d0df", GitTreeState:"clean", BuildDate:"2018-07-11T17:52:15Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Description**
Hello

I wonder why `helm status <release>` shows the pod status (comes from https://github.com/helm/helm/issues/2319) BUT it doesn't show the status of other resources.

I would expect helm status to show if PV is bounded, the details of deamonset and deployment and others.
So it should print all the helm resources with the output of kubectl get <resource-kine> <name>.

There is similar issue https://github.com/helm/helm/issues/2319, but it was closed without fix.
Is there any plan to improve that?

**Comment by mortent** [comment]
I think this was fixed with #4791
