### ISSUE TITLE
Allow communication via unix socket

### ISSUE THREAD

**Issue by jkroepke** [helm/helm#4774]
Hi!

since running a tiller locally would be more an more popular helm and tiller should allow the communication via sockets.

Otherwise you have always to look for a free port if you run tiller inside a jenkins.

**Comment by bridgetkromhout** [comment]
Hi, @jkroepke - thanks for your feedback! As Helm no longer has tiller (as of Helm 3), and Helm 2 is only accepting bugfixes now, we don't plan to make this change. If you'd like to read more about the differences from Helm 2 to Helm 3, you can find that info here: https://helm.sh/docs/faq/
