### ISSUE TITLE
Fails to evaluating a numeric value for "env:" section in deployment

### ISSUE THREAD

**Issue by rsvenkatesh** [helm/helm#4775]
It seems like there is a Helm/Kubernetes bug when it comes to evaluating a numeric value from the chart. This happens  only to numeric values in the “env:” section of “Dployment” kind ( Others sections of the Deployments are working as expected without issues).  
 
The following constructs are invalid in the value chart if the value be injected to the “env” section of a deployment. (value.yaml)
 
gw_port: !!integer 8001
gw_port: 8001
gw_port: “8001”
gw_port: ‘8001’
 
The above construct produces the below error,
 
“ Deploying XXX xxxx proxy server components...
Error: release vxxxxxxr-xxx-xxxserver failed: Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment: Spec: v1.DeploymentSpec: Template: v1.PodTemplateSpec: Spec: v1.PodSpec: Containers: []v1.Container: v1.Container: Env: []v1.EnvVar: v1.EnvVar: Value: ReadString: expects " or n, but found 8, error found in #10 byte of ...|,"value":8001}],"ima|..., bigger context ...|:"8001"},{"name":"HELM_CHART_TEST","value":8001}],"image":"xxx-docker-xxx-dev-docker.bintra|... “
 
 
And sets up a wild goose chase.. This error is misleading as the deployment didn’t complain when I used the same variable in other sections ( ‘ports’ section of  a Service and Deployment) . Couldn’t locate any reference to this issue in any of the documents on the internet, after various attempts to find a cleaner fix, ended up in a workaround hack which might fail if we upgrade Helm or Deployment versions to the latest.
 
Here are the working constructs ( values.yaml)
 
gw_port: !!integer '"8001"'
gw_port: '"8001"'

Depoyment:
  env:
          - name: HELM_CHART_TEST
             value: {{ .Values.server.service.gw_port }}

I have two vars in values.yaml as below,
 
SESN_SRVC_CRT_PATH: "/opt/xxx/xxxgateway/ssl"
GW_ADMIN_PORT: "8001"
 
The kube yaml is as below,
 
- name: SESN_SRVC_CRT_PATH
  value: {{ .Values.server.service.SESN_SRVC_CRT_PATH }}
 
- name: GW_ADMIN_PORT
  value: {{ .Values.server.service.GW_ADMIN_PORT }}
 
Deployment fails only on the GW_ADMIN_PORT. If Deployment expects "env:" values are to be surrounded by quotes then would fail for the both usages above. There is an in-consistency in the behavior.
 
Output of `helm version`:
Client: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:16Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Local

**Comment by lomluca** [comment]
With `GW_ADMIN_PORT: "8001"` in `values.yaml`, in the env variables write:
```
env:
  - name:  GW_ADMIN_PORT
    value: {{ .Values.GW_ADMIN_PORT | quote }}
```

It should work. [See docs](https://docs.helm.sh/developing_charts#quote-strings-don-t-quote-integers)

**Comment by bacongobbler** [comment]
@rsvenkatesh can you check and verify if @lomluca's suggestion works? If so can we close this?

**Comment by rsvenkatesh** [comment]
Thank you @lomluca @bacongobbler  for your help.  I was trying to say is there some in consistences in the way  the variable values are evaluated if the value happens to be numeric, the evaluation is less forgiving than if the values are non-numeric.

**Comment by bacongobbler** [comment]
Unfortunately there's not much a whole lot we can do as the Pod API schema is defined by Kubernetes. You'll have to convince upstream to make that change. 😄
