### ISSUE TITLE
add documentation around being able to specify HELM_KEY_PASSPHRASE

### ISSUE THREAD

**Issue by michelleN** [helm/helm#4779]
Add to docs around using HELM_KEY_PASSPHRASE environment variable for signing helm charts.
follow up to #4778

**Comment by mattreyuk** [comment]
@michelleN looks like this was covered by the [final commit](https://github.com/helm/helm/pull/4778/commits/bf49d22c14cb21ff19c453167b06624cc9ffc2ac)  to #4778 or is there more required?

**Comment by michelleN** [comment]
yeah thanks for catching that. closing this now. cheers.
