### ISSUE TITLE
cannot validate certificate for xxx because it doesn't contain any IP SANs

### ISSUE THREAD

**Issue by hiscal2015** [helm/helm#4781]
Hi, 

I have a custom kubernetes cluster v1.11.3 with selfsigned certificates, everything looks fine untill install tiller.

tiller can be successfully installed in k8s cluster with helm init but I can do nothing:
```
$ helm list
Error: forwarding ports: error upgrading connection: error dialing backend: x509: cannot validate certificate for 10.10.100.20 because it doesn't contain any IP SANs

$ kubectl cluster-info
Kubernetes master is running at https://10.10.100.20:6443
CoreDNS is running at https://10.10.100.20:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.

$ helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Error: forwarding ports: error upgrading connection: error dialing backend: x509: cannot validate certificate for 10.10.100.20 because it doesn't contain any IP SANs
```
Please help, thanks.

**Comment by bacongobbler** [comment]
Seems like an issue with the self-signed certificates provided with your API server. Go is very strict about certificate validation and will not accept a certificate for an IP address unless its properly listed in the certificate as a Subject Alternative Name (SAN).

**Comment by hiscal2015** [comment]
@bacongobbler Certificate used for kube-apiserver? Looks I have desired SAN defined there:

![image](https://user-images.githubusercontent.com/15604715/47056958-269dcf00-d1f1-11e8-9e68-c5a03619d09c.png)

**Comment by hiscal2015** [comment]
I'm wondering is it saying the kubelet certificate does not contain IP SANs?
```
$ kubectl get pod --namespace kube-system
NAME                            READY     STATUS    RESTARTS   AGE
coredns-69bcbbf897-2gngq        1/1       Running   0          23h
coredns-69bcbbf897-dnscn        1/1       Running   1          23h
tiller-deploy-85cb87cf7-rv4sw   1/1       Running   0          18h
weave-net-j5r7j                 2/2       Running   0          19h
weave-net-n92b8                 2/2       Running   0          23h
weave-net-nr8bl                 2/2       Running   0          19h
$ kubectl logs tiller-deploy-85cb87cf7-rv4sw --namespace kube-system
Error from server: Get https://10.10.100.20:10250/containerLogs/kube-system/tiller-deploy-85cb87cf7-rv4sw/tiller: x509: cannot validate certificate for 10.10.100.20 because it doesn't contain any IP SANs
```

**Comment by hiscal2015** [comment]
@bacongobbler I did a couple of tests and found it was a kubelet certificate issue, now I disabled kubelet https and everything works fine.

**Comment by MarkFreebairn** [comment]
Disabling kubelet https doesn't sound like a good workaround for this? I am seeing this issue too after upgrading to kubernetes v1.11.5 on EKS

**Comment by asloan7** [comment]
Yes, AWS EKS 1.11.5 (1.11.8 master now) throwing same error

**Comment by AnkurJain10** [comment]
@MarkFreebairn @asloan7  I am facing the same issue. How did you guys resolve it?

**Comment by MarkFreebairn** [comment]
@AnkurJain10 I haven't resolved it, I am still using kubernetes v1.10.11 as I can't upgrade because of this issue. I am not sure if it is fair to say it is an issue with helm or if it is an issue with kubernetes.

**Comment by asloan7** [comment]
@AnkurJain10  I started using AWS EKS approved AMI which has the  TLS bootstrap, currently listed here: https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html

**Comment by paqogomez** [comment]
Hey all.  I'm having the same issue.  Based on this thread it seems like the workarounds are:

1. (@yongzhang 's post ) Disable kubelet HTTPS
2. (@asloan7 's post) Use an EKS approved AMI. 
3. Dont upgrade.

I'm not in a position to downgrade and I've re-deployed my AMI to one in Asloan's list and disabling HTTPS is not an option either.
