### ISSUE TITLE
Helm Unable to Find Resource For Upgrade

### ISSUE THREAD

**Issue by ivelichkovich** [helm/helm#4784]
Output of `helm version`: 2.11.0

Output of `kubectl version`: 2.11.0

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  EKS

We had a helm deployment in a FAILED state do to missing quotes in a configmap during an upgrade. Previous upgrades had worked so everything was still running. Upgrades once we reached the failed state failed with
 "Error: UPGRADE FAILED: no PodDisruptionBudget with the name "my-pdb-name" found"

Helm template and apply worked fine at this point. We know we can fix this state by running helm del but that's not viable for a production environment. We fixed it by adding a namespace to the pdb helm yaml template. 

So looks like there's an issue with passing around namespaces in tiller when it's looking for resources to upgrade because we needed to tell it the namespace in the chart template to get the upgrade through. 

Also, if it was unable to find the pdb why would that make the upgrade --install fail? Shouldn't it just create it then?

**Comment by ivelichkovich** [comment]
Actually faced the same issue and this time adding the namespace didn't help, had to rollback to the last successful version

**Comment by edevil** [comment]
I just encountered this problem. Is there a fix? Why was this closed?
