### ISSUE TITLE
Need Helm CLI 2.9.1 for s390x to be included under Download

### ISSUE THREAD

**Issue by Bindiy** [helm/helm#4785]
Need Helm CLI 2.9.1 for s390x to be included under "Installation and Upgrading" section of https://github.com/helm/helm/releases/tag/v2.9.1, so the ICP installer picks it up and starts helm.

Please include s390x helm CLI binary on this page - https://github.com/helm/helm/releases/tag/v2.9.1

**Comment by bacongobbler** [comment]
Hi again @Bindiy!

As I mentioned previously in #4738, unfortunately there is no s390x binary for v2.9.1. s390x releases of Helm are provided from v2.10.0 forwards. If you want a v2.9.1 release of helm compiled against the s390x architecture, you will need to compile it from source yourself. I have provided the relevant documentation to compile Helm from source in the previous issue; please have a look at that and let us know if you have any questions.

PR #4741 will add it to the release notes going forward. In the meantime, I have already updated both the v2.10.0 and v2.11.0 release notes with the s390x download links.

Thanks!

**Comment by bacongobbler** [comment]
No thank you. We only post the official release binaries that our CI pipeline produces in the release notes. The ARM community had their own repository for a while demonstrating how to build helm and tiller for RPis for example.

https://github.com/jessestuart/tiller-multiarch/blob/master/README.md
