### ISSUE TITLE
Work with linkerd2

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#4787]
When `helm install` and `helm upgrade` are run it would be nice to work with linkerd2 out of the box. Here's a snippet from the [getting started guide](https://linkerd.io/2/getting-started/)...

> To get some added visibility into what is going on and see some of the functionality of Linkerd, let’s add Linkerd to emojivoto by running:
> ```
> kubectl get -n emojivoto deploy -o yaml \
>   | linkerd inject - \
>   | kubectl apply -f -
> ```
> This command retrieves all of the deployments running in the emojivoto namespace, runs the set of Kubernetes resources through inject, and finally reapplies it to the cluster. inject augments the resources to include the data plane’s proxies.

To do this in Helm v2 you'd need some kind of wrapper. Would there be a method to add this in Helm v3 that didn't require it to be part of a chart?

cc @adamreese @technosophos

**Comment by mattfarina** [comment]
We have different routes we could pursue this for Helm v3 and v2.

For v2 this would have to route through Tiller, where the yaml is generated and pushed. This would mean a custom rudder to work with linkerd2.

For v3, I think we can look at the event system internally to look for a way to do this. It would likely mean something like a plugin client side.

**Comment by dendle** [comment]
Hello @mattfarina,

Is there no way to allow the auto-inject scenario here? As in: Helm user doesnt care/know about linkerd.  They just create a chart/use a chart from stable, and install it.  If configured, Linkerd would be automatically injected into the pods and all of the linkerd goodness would "just work".

As the folks over at Linkerd2 have just finished (in the edge build) their work on the auto-inject via an admission controller, is it not possible to play nice with this approach?

Admittedly, I do not know what the current obstacles are; I just got the edge build of Linkerd2, and set up auto-injection, and gave it a whirl.  There was a templating error that I will not bore you with.  

I'd love to learn more about the problems are, as this is a space I am very interested in.

Thanks,
Matt

**Comment by maorfr** [comment]
Hey @dendle ,

Can this plugin be of any help to you?
https://github.com/maorfr/helm-inject

**Comment by maorfr** [comment]
@bacongobbler I think this issue can be closed :)

**Comment by bridgetkromhout** [comment]
Hi @mattfarina, do you think this issue is resolved with the suggestion of https://github.com/maorfr/helm-inject from @maorfr? If not, would you like to make a few notes about what you think would be useful at this point? Thanks.
