### ISSUE TITLE
[Feature Request] Provide a way to wait for a release to be fully ready.

### ISSUE THREAD

**Issue by kkimdev** [helm/helm#4810]
I think waiting an installed release should be a common functionality but it looks like there is no easy way to do it yet. I thought about the following line, but unfortunately `kubectl rollout status` doesn't support multiple resources.  

```bash
$ echo "$(helm get manifest my-release)" | kubectl rollout status -f -
error: rollout status is only supported on individual resources and resource collections - 5 resources were found
```

I think we can execute `kubectl rollout status` multiple times for each resource but it becomes kind of tedious.  How about having a Helm command that does it for us?

**Comment by robinkb** [comment]
Have you tried using the `--wait` flag? It is available for `install`, `upgrade`, and `rollback`.
