### ISSUE TITLE
Way to "detach"/unlink a k8s resource from Helm?

### ISSUE THREAD

**Issue by madprogrammer** [helm/helm#4826]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"canary+unreleased", GitCommit:"2ef61fdf5c46fdc47ac264926e70e0590e7b6f94", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2+coreos.0", GitCommit:"b427929b2982726eeb64e985bc1ebb41aaa5e095", GitTreeState:"clean", BuildDate:"2018-01-18T22:56:14Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2+coreos.0", GitCommit:"b427929b2982726eeb64e985bc1ebb41aaa5e095", GitTreeState:"clean", BuildDate:"2018-01-18T22:56:14Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Kubespray

Is there any safe way to make an existing K8s resource previously deployed by Helm (a PersistentVolumeClaim) no longer associated with any deployed release, so that Helm will not try to do anything with it anymore?

In my Helm chart, one of the created entities was a PersistentVolumeClaim, and now I want to move to using `existingClaim` for storage so that storage is not created by the Helm chart, but is pre-created by the cluster administrator. I need the previouly Helm-created PVC to transform into "just a PVC" so that on the next upgrade of the release, or if I decide to `helm delete` the release, the PVC stays intact.

I've removed Helm-related labels (chart, heritage, release) from the PVCs, but I'm not sure that's enough, and I didn't find a way to see what's going to be deleted before executing the actual deletion.

**Comment by wemu** [comment]
The only way I'm aware that exists that prevents tiller to remove somthing if a helm delete is executed is an annotaton mentioned in [Tips and Tricks](https://github.com/helm/helm/blob/master/docs/charts_tips_and_tricks.md#tell-tiller-not-to-delete-a-resource):

```
annotations:
    "helm.sh/resource-policy": keep
```

once you then delete a helm release these resource will remain in kubernetes. But there is (currently in Helm 2.11) no way of re-attaching any existing kubernetes resource into a helm chart or release. So this is "one-way". So you can't re-deploy the same resource with helm and have it adopt it, should it still be there.

**Comment by jlegrone** [comment]
@madprogrammer does this answer your original question?

**Comment by madprogrammer** [comment]
Yes, thanks! Actually I already did it using the mentioned annotation.
