### ISSUE TITLE
Helm 2.9.1 for s390x

### ISSUE THREAD

**Issue by Bindiytm** [helm/helm#4830]
[helm-v2.9.1-linux-s390x.tar.gz](https://github.com/helm/helm/files/2509210/helm-v2.9.1-linux-s390x.tar.gz)

**Comment by bacongobbler** [comment]
As a note to others: this is a compiled binary of helm uploaded by @Bindiytm, and is NOT an official Helm release of v2.9.1. Please see #4785 and #4738 for more context.

**Comment by chenzhiwei** [comment]
[helm-v2.9.1-linux-s390x.tar.gz](https://github.com/helm/helm/files/2537750/helm-v2.9.1-linux-s390x.tar.gz)
