### ISSUE TITLE
Proposal: helm plugins repository

### ISSUE THREAD

**Issue by maorfr** [helm/helm#4831]
Hi guys,

thanks for all the great work!
May I suggest an idea?
Many people write great plugins for helm, and I think it can be helpful if there was a central repository that holds **links** to existing plugins, something along the line of:

Plugin name, description, link

Anyone can add a PR to add a link to their plugin, so that others can go over the list and see if there is a plugin that may be of use for them.
This does not mean that these plugins are "official", more like "use at your own risk".

Currently one needs to rely on their googling abilities :)

Would love to get your thoughts on the subject!

Thanks again, Helm is awesome! :)

**Comment by maorfr** [comment]
Sure, but under the helm umbrella so it is easy to find and share

**Comment by mattfarina** [comment]
What about https://docs.helm.sh/related/? You can PR changes to it at https://github.com/helm/helm/blob/master/docs/related.md

**Comment by maorfr** [comment]
That`s even better :)
