### ISSUE TITLE
The tiller tunnel isn't closed after installing a helm chart

### ISSUE THREAD

**Issue by ahrtr** [helm/helm#4834]
The tillerTunnel is defined in the following file,, 
https://github.com/helm/helm/blob/master/cmd/helm/helm.go 

The tillerTunnel is supposed to be closed in teardown(), but the tunnel created in function setupConnection() isn't saved to the variable tillerTunnel. Accordingly the tiller tunnel will not be closed.

**Comment by bacongobbler** [comment]
will be fixed when #4777 is merged.
