### ISSUE TITLE
How to modify the default source address of helm

### ISSUE THREAD

**Issue by JokerDevops** [helm/helm#4849]
hi
       How to modify the default source address of helm？
       The default source address for helm is https://kubernetes-charts.storage.googleapis.com/, I can't access him. If you change the default source address of the helm. such as:
       When I use the [root@node1 mean]# helm dep build command, he will get the following error.
        [root@node1 mean]# helm dep build
Error: no repository definition for https://kubernetes-charts.storage.googleapis.com/, https://charts.bitnami.com/bitnami. Please add the missing repos via 'helm repo add'
I changed how to modify the default source so that he no longer has to go to https://kubernetes-charts.storage.googleapis.com/. But visit my own

**Comment by mattfarina** [comment]
> The default source address for helm is https://kubernetes-charts.storage.googleapis.com/, I can't access him

Do you know why you cannot access it? Can you share where you are at?

```
[root@node1 mean]# helm dep build
Error: no repository definition for https://kubernetes-charts.storage.googleapis.com/, https://charts.bitnami.com/bitnami. Please add the missing repos via 'helm repo add'
```

Did you try to add the repositories? Did that fix your problem?

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
