### ISSUE TITLE
Securing Helm documentation: add tillerless plugin

### ISSUE THREAD

**Issue by jolson490** [helm/helm#4852]
Hello,

The team I'm on wanted to not have an unauthenticated gRPC endpoint (that has access to change things) in our K8s cluster. We looked into [enabling TLS](https://github.com/helm/helm/blob/master/docs/securing_installation.md#the-tiller-grpc-endpoint-and-tls), but instead ended up using the Tillerless Helm v2 plugin (https://github.com/rimusz/helm-tiller).

FWIW, our opinion was we found it more desirable / easier (at least for us) to use the plugin, vs creating `*.tls` certs and setting up a pipeline to manage them (to store them, and create new ones when current ones expire - and this would've been especially cumbersome if we setup a [separate TLS certificate](https://github.com/helm/helm/blob/master/docs/securing_installation.md#best-practices-for-securing-helm-and-tiller) for each endpoint).
Also, whenever helm v3 comes out, the [proposal](https://github.com/helm/community/blob/master/helm-v3/000-helm-v3.md) calls for going tiller-less.

So I'd like to ask if it would make sense to update [securing_installation.md](https://github.com/helm/helm/blob/master/docs/securing_installation.md) to at least mention the plugin as another (if not the recommended) option (besides enabling TLS) for not having a wide open gRPC endpoint? 
If the answer is yes, I'd be happy to create such a PR to modify `securing_installation.md` - I just wanted to ask first. 
(By the way, currently the only place where this repo mentions the "Tillerless Helm v2" plugin is [docs/related.md](https://github.com/helm/helm/blob/master/docs/related.md).)

Thanks!

**Comment by bacongobbler** [comment]
I'm incredibly wary about recommending users to trust third-party plugins as a security practice.

That being said, I would definitely look forward to an amendment to the documentation that recommended the following:

- fetch the latest helm release tarball from the [GitHub release page](https://github.com/helm/helm/releases)
- extract and move `helm` and `tiller` somewhere on your $PATH
- run `tiller`
- run `export HELM_HOST=:44134`
- run `helm` as usual

It's a lot less clunky to use once it's set up as you can use `helm` commands as usual once $HELM_HOST has been set.

If you're interested in contributing that to the documentation, we'd really appreciate that.

**Comment by mattfarina** [comment]
@jolson490 When ever we talk about security we want to take the more secure, trusted, and conservative approach. For example, the helm-tiller plugin is outside the control of the Helm project and I'm not aware of a security issue reporting mechanism. While it's approach is useful we are trying to be careful when we recommend anything.

As @bacongobbler noted, the approach works. It's even one many of us have used for local development. There's just a difference between recommending or sharing an approach and pointing people to use a 3rd party plugin.

For what it's worth, if I were the author of the plugin I would say this about myself.

But, we would be very open to documentation on the topic.

**Comment by jolson490** [comment]
That all makes sense and sounds good, thank you both for taking the time to respond.
When I get a chance, I'll work on the proposed changes that @bacongobbler described and create a PR for that.

**Comment by rimusz** [comment]
@jolson490 update PR as @bacongobbler suggest and just mention my plugin at the end as an option for automated way :)
