### ISSUE TITLE
helm release fails if tiller namespace does not exist

### ISSUE THREAD

**Issue by rimusz** [helm/helm#4854]
Output of `helm version`: any

Output of `kubectl version`: any 

Cloud Provider/Platform (AKS, GKE, Minikube etc.): any 

Providing `tiller` some namespace which does not exist, the helm release fails:
1) it installs chart without issues, all services get up
2) fails to create helm release as there is no namespace to create it.

It should check if the tiller `namespace` exists before installing the release and fail at the beginning.

**Comment by mattfarina** [comment]
@rimusz Which namespace is this? I don't imagine it's the namespace tiller is running in. If it's the namespace for the chart tiller should be creating it as long as it has permission. Is it the namespace for the chart to live in? Or, it is something else?

**Comment by rimusz** [comment]
That's the namespace specified with `TILLER_NAMESPACE=some_namspace` to store releases information, when the Tiller runs outside the cluster.
If there is no such namespace where is nowhere to store release information, and release it self fails

**Comment by mattfarina** [comment]
Is an error reported?

In the code (configmap example) it reports an example if it can't create the configmap... https://github.com/helm/helm/blob/6452e90f3f3e24740a88c3690d5e89219c13b7e8/pkg/storage/driver/cfgmaps.go#L166-L173

PRs welcome to fix this.

**Comment by bacongobbler** [comment]
https://github.com/helm/helm/pull/4868#issuecomment-538061299
