### ISSUE TITLE
How do I run `init --upgrade --wait` for a TLS enabled tiller ?

### ISSUE THREAD

**Issue by DylanGriffith** [helm/helm#4855]
Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.6", GitCommit:"9b635efce81582e1da13b35a7aa539c0ccb32987", GitTreeState:"clean", BuildDate:"2018-08-16T21:33:47Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform: GKE

I'm trying to run `helm init --upgrade --wait` but can't figure out the command line arguments to use when the server being upgraded already has TLS enabled. I assume I needed client key/cert so I've ensured I've got `ca.pem`, `cert.pem` and `key.pem` in `helm home`. I know they work because `helm ls --tls` works just fine. The problem I have is that `helm init --upgrade --wait` does not seem to accept the `--tls` flag. 

Here is what I've tried:

```
dylan@dgriffith-workstation:~/workspace/gdk-ce/gitlab$ /tmp/linux-amd64/helm init --upgrade --wait --tiller-namespace gitlab-managed-apps
$HELM_HOME has been configured at /home/dylan/.helm.
Error: could not ping Tiller: rpc error: code = Unavailable desc = transport is closing

dylan@dgriffith-workstation:~/workspace/gdk-ce/gitlab$ /tmp/linux-amd64/helm init --upgrade --wait --tiller-namespace gitlab-managed-apps --tls
Error: unknown flag: --tls

dylan@dgriffith-workstation:~/workspace/gdk-ce/gitlab$ /tmp/linux-amd64/helm init --upgrade --wait --tiller-namespace gitlab-managed-apps --tiller-tls
Error: missing required TLS key file

dylan@dgriffith-workstation:~/workspace/gdk-ce/gitlab$ /tmp/linux-amd64/helm init --upgrade --wait --tiller-namespace gitlab-managed-apps --tiller-tls-verify
Error: missing required TLS key file
```
 
I'm not exactly sure what else I can do other than `sleep` in my script if `--wait` is not working for me.

Also I've noticed that the `helm init --upgrade` runs just fine without `--wait` since it seems the client key/cert is not necessary for upgrade:

**Comment by mattfarina** [comment]
When Tiller is upgrade with TLS it's very much the same as when it's installed. The certificate for Tiller to use needs to be passed in using the `--tiller-tls-cert` flag. There is code inside of Helm to check for these things. You can find it at:

https://github.com/helm/helm/blob/1ebbd6989645375abd9268f9b3315e296b52f828/cmd/helm/init.go#L159-L189

When you upgrade Tiller you'll need to pass the certificate in.

**Comment by DylanGriffith** [comment]
@mattfarina this was not the case from my testing. I was able to upgrade tiller just fine without providing the cert and the command succeeded. And the upgrade succeeded. It only stopped working when I added `--wait`.

**Comment by mattfarina** [comment]
@DylanGriffith `--tls` isn't required for an upgrade to Tiller because Helm talks to the Kubernetes API to tell it to run a newer version of the container image. `--wait` makes sure the pod is running. You can see the wait handling [here](https://github.com/helm/helm/blob/d5c183e297aa0c445c4eca4ff4e6ebc3f44bc333/cmd/helm/init.go#L322-L343).

I'm no expert with this code and am learning it as I troubleshoot the problem. Someone like @bacongobbler knows it much better than I.

Is this a new problem that didn't happen before or something you've just started to use? I ask because #4657 recently landed and it added some TLS checking code for every command.

The code path is that when the the init command is run the [prerun](https://github.com/helm/helm/blob/d5c183e297aa0c445c4eca4ff4e6ebc3f44bc333/cmd/helm/helm.go#L85-L101) happens and is then followed by [the code for the init command](https://github.com/helm/helm/blob/d5c183e297aa0c445c4eca4ff4e6ebc3f44bc333/cmd/helm/init.go#L108-L117) which [checks the tls options](https://github.com/helm/helm/blob/d5c183e297aa0c445c4eca4ff4e6ebc3f44bc333/cmd/helm/init.go#L191-L195) and generating the error you're seeing.

I'm not seeing where `--wait` is in the loop on the error.

**Comment by DylanGriffith** [comment]
> Is this a new problem that didn't happen before or something you've just started to use? 

@mattfarina this is something I've just started trying to use so I'm not sure if it worked with previous versions.

**Comment by whereisaaron** [comment]
Thanks for this @DylanGriffith! I was have no luck upgrading a TLS-enabled tiller, based on your report I removed the `--wait` and it immediately worked!

With `--wait` I just get: `Error: could not ping Tiller: remote error: tls: bad certificate`

After removing the `--wait` I get:
```
Tiller (the Helm server-side component) has been upgraded to the current version.
Happy Helming!
```

The command used was:
```
helm init --upgrade \
  --home=$HELM_HOME \
  --override 'spec.template.spec.containers[0].command'='{/tiller,--storage=secret}' \
  --kube-context=$KUBE_CONTEXT \
  --tiller-namespace=$TILLER_NAMESPACE \
  --history-max 20 \
  --service-account=tiller-deploy \
  --tls-ca-cert=$HELM_TLS_CA_CERT \
  --tiller-tls-verify=true \
  --tiller-tls-cert=$HELM_TLS_CERT \
  --tiller-tls-key=$HELM_TLS_KEY \
  --tiller-tls-hostname=tiller \
  --wait    <---- REMOVE THIS to make it work
```

With the same TLS set up, `helm version` works fine.
```
$ helm version --tls-verify
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
```

I fingered the `--wait` was not picking up that the TLS is enabled, but you can't specify `--tls` or `tls-verify` on `helm init`.

**Comment by whereisaaron** [comment]
> @DylanGriffith --tls isn't required for an upgrade to Tiller because Helm talks to the Kubernetes API to tell it to run a newer version of the container image.

Oh, so I can't use `helm init --upgrade` to rotate certificates then @mattfarina 😅
I have to delete and re-install to update the tiller certificate?

**Comment by MrD2** [comment]
Check this: https://github.com/helm/helm/issues/5170

**Comment by hajdukd** [comment]
Also facing the same issue. Initializing with `--wait` does not work with TLS. Removing `--wait` solves the issue but it's counter productive as we have to write custom wait using TLS.

**Comment by bacongobbler** [comment]
closing as inactive.
