### ISSUE TITLE
Help about the 'required' function

### ISSUE THREAD

**Issue by brunohms** [helm/helm#4860]
I've found the **required** function on the link https://github.com/helm/helm/blob/master/docs/charts_tips_and_tricks.md#know-your-template-functions

However I did not found where to put it, could you guys help me with this?

Also for the future, I believe it would be helpful to have at least one example with each section/function of the tips and tricks section.

**Comment by mattfarina** [comment]
The functions in this section are for use within your templates. These are in the template directory.

An example in the docs reads:

```yaml
value: {{required "A valid .Values.who entry required!" .Values.who }}
```

How would you improve on that?

**Comment by brunohms** [comment]
Hi @mattfarina thanks for the answer however it didn't clarify much.
Should it be in a `.yaml` file, or a `.tpl` file? or could it be in both?

A way to improve that would be generating more examples, or using more functions in the examples.
This is usually one of the first places I go looking for stuff because I like to learn by seeing something that works.
I've noticed a buch of functions that aren't listed in the documentation or when they are, there is just a short description, like the case above.

Today, by kind of an accident, I've found the `add` function and `max` function, never noticed them in the documentation.

If there is another documentation, maybe this is all in a Go documentation, could you please point me towards it?

**Comment by mattfarina** [comment]
> Should it be in a .yaml file, or a .tpl file? or could it be in both?

The .yaml files are templates if they are in the templates directory. Helm will process each of them as a template and fill in the variables or handle the logic. .tpl files are usually used for supporting templates that will be injected into other files where the .yaml files typically represent the kubernetes artifacts.

> Today, by kind of an accident, I've found the add function and max function, never noticed them in the documentation.

Helm uses the spig library. All of its functions are not in the Helm documentation. Sprig documentation is at https://masterminds.github.io/sprig/
