### ISSUE TITLE
Does chart support numeric conversion tuple syntax?

### ISSUE THREAD

**Issue by ygqygq2** [helm/helm#4876]
`values.yaml` like this:

```
replica: 3
```

I want a list or tuple between zero and three, then I can use `range` to do someting.
`0 1 2`

How to writer in chart?

**Comment by mattfarina** [comment]
Helm uses the go template syntax. `range` is part of that. You can read about it in the go documentation (e.g., https://golang.org/pkg/text/template/). Does that help?

**Comment by ygqygq2** [comment]
@mattfarina I've read it, but there's no range loop like I said.So I'm here to ask for help.

**Comment by mattfarina** [comment]
Half way through the variables section it touches on range. See https://golang.org/pkg/text/template/#hdr-Variables. Does that not work for you?

**Comment by ygqygq2** [comment]
@mattfarina Thanks.
I mean, if give a number `3`, then can get a list `[0, 1, 2]`.

**Comment by mattfarina** [comment]
I think you want something like a loop. I am not sure of a way to do that today. It might be a good function for [Sprig](https://github.com/Masterminds/sprig), the template function package Helm uses.

**Comment by bacongobbler** [comment]
yeah, bash has a command called `seq` that takes a number and returns a sequence of numbers up to and including that number, starting at 1: http://tldp.org/LDP/abs/html/extmisc.html

You can also define the intervals using three arguments: `seq $BEGIN $INTERVAL $END`. `seq 0 1 2` would return the list `0 1 2`, whereas `seq 0 2 10` would return `0 2 4 6 8 10`.

I think a function that performs similar to `seq` would be a great enhancement to sprig.

**Comment by ygqygq2** [comment]
@mattfarina @bacongobbler Thanks a lot.
Yes, your are right. Waiting for additional functionality. Helm can't use bash directly now.

**Comment by Lentil1016** [comment]
`{{ untilStep 0 3 1 }}` works for now.
```
{{- range untilStep 0 3 1 }}
metadata:
  name: container-{{ . }}
---
{{- end }}
```
will produce 
```
metadata:
  name: container-0
---
metadata:
  name: container-1
---
metadata:
  name: container-2
---
```

I wonder if it's a good idea to add this example to `control_structures.md`. It seems sort of a commonly used looping form to me. 🤔

**Comment by dominik-ba** [comment]
For me it looks like this does not work with values.
This example just prints out `ports:` and nothing else ...
```
ports:
  {{- range untilStep (int .Values.ports.start) (int .Values.ports.end) 1 }}
  - containerPort: {{ . }}
  protocol: TCP
  {{- end }}
```

values.yaml contains this
```
ports:
  start: 6000
  stop: 7000
```
Am I doing something wrong or is this not supported?

**Comment by ygqygq2** [comment]
@dominik-ba 
![image](https://user-images.githubusercontent.com/17672440/63903750-33aa6200-ca41-11e9-891c-3e589a11b2c7.png)

**Comment by dominik-ba** [comment]
Ok that was embarrassing... :D thanks alot!
Maybe it would be good if there was an error instead of nothing printed in this case...
Thanks anyways :)
