### ISSUE TITLE
"Error: error unmarshaling JSON: parsing time" during helm package

### ISSUE THREAD

**Issue by wknapik** [helm/helm#4879]
Got this in a CI job. Don't have a way to reproduce it.
```
$ rm -fr ~/.helm # working around issue #3111 
# multiple charts packaged here, in parallel
$ rm -f foo.tgz; helm package foo --version bar
Successfully packaged chart and saved it to: foo.tgz
Error: error unmarshaling JSON: parsing time ""2018-11-02T02:04:11.670172421Z 2018-11-02T02:04:11.670172421Z"" as ""2006-01-02T15:04:05Z07:00"": cannot parse " 2018-11-02T02:04:11.670172421Z"" as """
$ echo "$?"
1
$
```

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.9", GitCommit:"e6ab4ee54f71e7a403cc733534bab86fd959ecb7", GitTreeState:"clean", BuildDate:"2018-10-16T12:14:47Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.11", GitCommit:"1bfeeb6f212135a22dc787b73e1980e5bccef13d", GitTreeState:"clean", BuildDate:"2018-09-28T21:35:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS

**Comment by mattfarina** [comment]
Can you use the `--debug` flag to provide more output. For example, `helm --debug package foo --version bar`. More detail would help us understand where this is happening.

On the upstream chart repo we run the tests in a container. The `~/.helm` directory is created new for each run. That testing is up at https://github.com/helm/chart-testing. That maybe be why we have not encountered #3111.

**Comment by wknapik** [comment]
Hi @mattfarina, thanks for the quick response.

I'll give `--debug` a try, though it might take a while before the bug is triggered again.

As for #3111 - I also run my pipelines in containers and for every branch, the ~/.helm directory is separate, but I still run `rm -fr ~/.helm` before using helm, because I bind-mount the checkout directory from the host, so my builds can be incremental. With the `rm -fr` in place, #3111 is triggered very rarely, but it still happens from time to time. Quite a nuisance in CI.

Anyhow, my guess is that both issues (and also #2258) are caused by parallel executions of `helm package`, but that is just a guess...

**Comment by wknapik** [comment]
Got
```
Error: error unmarshaling JSON: parsing time ""2018-11-16T10:44:23.087881375Z 2018-11-16T10:44:23.087881375Z"" as ""2006-01-02T15:04:05Z07:00"": cannot parse " 2018-11-16T10:44:23.087881375Z"" as """
```
but I had `--debug` enabled everywhere else, not for that one target ;/ Added `--debug` to that target now, will wait for it to happen again.

**Comment by wknapik** [comment]
Ok, it happened again today, had `--debug` enabled, but it didn't produce any additional output that would be helpful, I'm afraid.

The build included a bunch of charts built in parallel and they all failed with the exact same error message (identical timestamps):
```
[debug] Setting version to v7.7.1-45-gbcbabff9
Successfully packaged chart and saved it to: /some/path/package-v7.7.1-45-gbcbabff9.tgz
Error: error unmarshaling JSON: parsing time ""2019-01-11T10:34:41.761500171Z 2019-01-11T10:34:41.761500171Z"" as ""2006-01-02T15:04:05Z07:00"": cannot parse " 2019-01-11T10:34:41.761500171Z"" as """
```
This is quite a nuisance in CI, because there's no workaround and it just fails the pipeline ;/

**Comment by IppX** [comment]
Hi,

I reproduced the same issue today with parallel `helm dep up && helm deploy && helm test`.
I also get this issue when running the same tests: https://github.com/helm/helm/issues/4463

Any ideas ?

**Comment by wknapik** [comment]
Also, why is this marked "question/support" ? This is a bug.

**Comment by mattfarina** [comment]
@wknapik I may have an idea what's going on and the reason this is "question/support" labeled.

When `helm package` is run is saves the package to a local directory inside of the `.helm` directory (or equivalent if set to be different). You can see this in the code at https://github.com/helm/helm/blob/618447cbf203d147601b4b9bd7f8c37a5d39fbb4/cmd/helm/package.go#L183-L191

In the order of events first the Helm home is deleted

> $ rm -fr ~/.helm # working around issue #3111 

Then  the package is removed and a new package created

> rm -f foo.tgz; helm package foo --version bar

No helm home exists to copy the package into. I wonder if you run `helm init --client-only` (`-c` can be using instead  of `--client-only`, too) between the two steps if this corrects the problem.

What we may need is better output to let you know the Helm Home does not exist.

Can you check if this is what's happening for you?

**Comment by wknapik** [comment]
@mattfarina I'm afraid that's not it. This is built using make and all `helm package` targets have an order-only dependency on `$(HOME)/.helm`, which is created with `helm init -c`.

**Comment by mattfarina** [comment]
@wknapik What are the permissions on that `.helm` folder? The debug command for saving would fire. Did you see that? If not, it looks like it's within the above block the problem would be happening.

Or, do you spot the bug elsewhere?

**Comment by wknapik** [comment]
@mattfarina I've recently switched to using `--save=false` with `helm package` (see: https://github.com/helm/helm/issues/3111#issuecomment-480494831), to work around this and other bugs, like #3111. I haven't seen this happen since, so I can't look at any relevant logs now. But this was rarely triggered regardless.

In any case, this is very unlikely to be about the environment helm is used in. Everything I do is fully automated and containerized. Only one user is used in the pipeline and it deletes ~/.helm at the beginning and creates it with `helm init -c` before any other calls to helm are made. The relevant source of variance is the parallelization, not inconsistencies/issues with the environment.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
