### ISSUE TITLE
ar

### ISSUE THREAD

**Issue by NotSharath** [helm/helm#4892]
Output of `helm version`:

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by bacongobbler** [comment]
hey, I'm going to close this issue because there's nothing to go on here... Likely opened by accident. Please feel free to re-open once you have something written down in this ticket. Thanks.

**Comment by NotSharath** [comment]
to my surprise I am totally not aware of this post - apologies for consuming ur time
