### ISSUE TITLE
Tiller installation

### ISSUE THREAD

**Issue by YuviVenkat** [helm/helm#4893]
helm init --service-account tiller
$HELM_HOME has been configured at /root/.helm.
Error: error installing: Post https://192.168.56.100:6443/apis/extensions/v1beta1/namespaces/kube-system/deployments: Forbidden

This is the error when I try to install tiller. Anyone help me out please.

**Comment by hightoxicity** [comment]
Same issue here

**Comment by kldev** [comment]
First delete:
kubectl -n kube-system delete deployment tiller-deploy and kubectl -n kube-system delete service/tiller-deploy
Then:
kubectl create serviceaccount --namespace kube-system tiller
 
kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
 
helm init --service-account tiller
 
kubectl patch deploy --namespace kube-system tiller-deploy -p '{"spec":{"template":{"spec":{"serviceAccount":"tiller"}}}}'

Source: https://www.digitalocean.com/community/tutorials/how-to-install-software-on-kubernetes-clusters-with-the-helm-package-manager
