### ISSUE TITLE
helm version should be able to return only client version

### ISSUE THREAD

**Issue by neilhwatson** [helm/helm#4899]
Output of `helm version`: 2.11.0

Suppose you have an automatic way to install the helm client. You might want to test whether or not helm is installed with ```helm version```, but this will exit non-zero because it also checks the server version which is not yet available. There should be client only version check.

**Comment by bacongobbler** [comment]
Use `helm version --client-only` to check just the client version.

**Comment by hlascelles** [comment]
It's just `helm version --client`.
