### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by jonbcampos** [helm/helm#4903]
Output of `helm version`:
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Error: Get https://35.224.219.45/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: x509: certificate signed by unknown authority

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Unable to connect to the server: x509: certificate signed by unknown authority

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

-----------------

This issue just started for me. As recently as a few days ago I was able to run my helm commands no problem, now I get this message *Unable to connect to the server: x509: certificate signed by unknown authority*. I am using a self signed certificate however that wasn't an issue before. Anyone with thoughts?

**Comment by jonbcampos** [comment]
this was my own fault, had to re-up keys with kubectl

**Comment by dimhoLt** [comment]
@jonbcampos Could you please explain what "re-up keys" means? Which command did you run?

**Comment by jonbcampos** [comment]
Basically my best recommendation is to delete your helm install and replace with another with new secure keys. Simple task that should only take a moment.

**Comment by dimhoLt** [comment]
Thanks. For the record in this thread, I solved it by running:

    $ kubectl delete deployment tiller-deploy -n kube-system
    $ helm init

From there, the certs were updated.

For others reading, the first command deletes tiller from the server (you won't lose your deployments, or history of them) and the second one creates a new tiller (helm's server-side component).

**Comment by MirtoBusico** [comment]
Sorry, for me i didn't work.
After deleting tiller-deploy helm init gives the X509 error
```
sysop@k3s-master:~/software/istio-1.2.4$ sudo kubectl delete deployment tiller-deploy -n kube-system
[sudo] password for sysop: 
deployment.extensions "tiller-deploy" deleted
sysop@k3s-master:~/software/istio-1.2.4$ sudo helm init --service-account tiller
$HELM_HOME has been configured at /home/sysop/.helm.
Error: error installing: Post https://k3s-master:6443/apis/extensions/v1beta1/namespaces/kube-system/deployments: x509: certificate signed by unknown authority
sysop@k3s-master:~/software/istio-1.2.4$
```
Any hint?

**Comment by MirtoBusico** [comment]
[SOLVED] It was an helm problem

I solved completely eliminating tiller from the cluster

First I removed the helm snap

```
sudo snap remove helm --purge
```

Then I removed tiller compnents from the cluster (awaiting operations completion)

```
sudo kubectl delete deployment tiller-deploy --namespace kube-system
sudo kubectl delete service tiller-deploy --namespace kube-system
sudo kubectl delete clusterrolebinding.rbac.authorization.k8s.io/tiller --namespace kube-system
sudo kubectl delete serviceaccount/tiller --namespace kube-system
```

Then I installed helm from the helm site
Created the tiller service account (created file helm-rbac.yaml)
```
sudo kubectl apply -f helm-rbac.yaml
```
Then installed helm
```
curl -L https://git.io/get_helm.sh | bash
```
Created the ~/.kube/config file
At this point the inizialization worked correctly
```
helm init --service-account=tiller --history-max 200
```
Then I followed the istio upgrade instructions

**Comment by goginenigvk** [comment]
getting the below error. Can someone look into the issue
Error: Get https://100.64.0.1/api/v1/namespaces/helm/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: x509: certificate signed by unknown authority

[UAT:]> helm version
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
[UAT:]> kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"clean", BuildDate:"2020-05-06T05:17:59Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.12", GitCommit:"a8b52209ee172232b6db7a6e0ce2adc77458829f", GitTreeState:"clean", BuildDate:"2019-10-15T12:04:30Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

**Comment by goginenigvk** [comment]
how can we get the tiller-token back if we delete the pod
any ideas?
