### ISSUE TITLE
Deploy specific subchart only

### ISSUE THREAD

**Issue by filipre** [helm/helm#4908]
Hi!

Let's assume I have a huge application that I split up into smaller services and I want to use helm to deploy everything. Obviously, I can create an umbrella chart (parent chart) and each smaller service is a sub-chart. That way, the deployment of *everything* is super easy (`helm install/upgrade ...`) and I could also define some `_myTemplate.tpl` file which I could use within every sub-chart where things are always the same (so I don't have to replicate yaml definitions and stuff like that)

However, what happens if I only want to redeploy (upgrade) a small part of my application without touching the rest? **Is there a way to install/upgrade a sub-chart only?** The `helm` documentation states that

>A subchart is considered “stand-alone”, which means a subchart can never explicitly depend on its parent chart.

If it is stand-alone, how would I deploy a subchart then?

Here is the background of my question: We have a lot of services which uses the same yaml boilerplate to deploy. They all have the same `deployment.yaml`, `service.yaml`, etc. We could write one chart only and then simply pass different `values.yaml` files for each application, but I believe this is against the purpose of a package manager and also makes everything weird and hard to maintain. We would love to aim for something like https://github.com/helm/charts but at the same time be able to include very general named templates to keep boilerplate at a minimum. Charts and Subcharts seem to be the right direction, but we don't always want to redeploy "everything" but only a small part. 

Is there a simple solution? Is it even possible with helm at the moment?

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cheers
René

**Comment by bacongobbler** [comment]
Most users accomplish this by bumping the subchart in their requirements file and call `helm dependency update` before calling `helm upgrade`. Umbrella charts were originally designed around the idea of managing a set of charts as a single application, not as a set of smaller releases. :)

If you want to manage the lifecycle of a subchart independent from the rest of your umbrella chart, it's probably best to maintain that as a separate release.

Does that help answer your initial question?

**Comment by lhb008** [comment]
@filipre  Hi, did you find the right way to resolve your question. I have a helm charts with multiple deployment, but now i want to upgrade only one of the using helm. How could i do?

**Comment by filipre** [comment]
hi @lhb008, 
sadly, I don't really remember anymore. I believe one approach was to use tags/labels, select the right services and then deploy them under the right release name. That way you could either select all your applications and release it under a "global" release name or you could select one specific app and release it under a specific app name. Or you do combinations. Does my explanation make sense?

**Comment by snyderdb** [comment]
Filipre, i am supporting a project that is considering the use of a Helm Chart and we are facing the issue you expressed in your question.   We would like to have the flexibility of being able to deploy services independently of the Umbrella chart.

Is this possible?

**Comment by filipre** [comment]
@snyderdb Did you read the complete thread? I believe I used tags and conditions back then.
