### ISSUE TITLE
--set Object that also has an array

### ISSUE THREAD

**Issue by mitchellmaler** [helm/helm#4923]
Trying to set an object with an array using the cli --set command but it won't render the object. It just skips the secretName key:value under the tls object.

The object should render like:
```yaml
tls:
  - hosts:
    - my.url.net
    secretName: tls-secret
```

```
helm upgrade . \
  --set ingress.tls[0].hosts="{my.url.net}" \
  --set ingress.tls[0].hosts.secretName=tls-secret \
  --debug --dry-run
```

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-22T05:40:33Z", GoVersion:"go1.9.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by mortent** [comment]
Unless you have a string reason for using the `--set` option, I think it would be easier to use the `-f <file.yaml>` option here. It works better for complex values. There is an example in #4807

**Comment by AlexandrSemak** [comment]
I understood that my case is an exception, but We have 8 clusters in different region and deploy prometheus-operator with the same config except of ingress especially hosts our Cloud CLI allow as get ingress for specific cluster and when i try to automate it i have to keep 8 values.yaml only with ingress

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
