### ISSUE TITLE
Capabilities.KubeVersion.* -- filter out junk characters

### ISSUE THREAD

**Issue by gladiatr72** [helm/helm#4929]
Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.2-gke.18", GitCommit:"5796233393d7bc034428de15191ad3d2eaff95fb", GitTreeState:"clean", BuildDate:"2018-11-08T20:49:08Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

GKE

It's a little thing--if there is a trivial solution using a template function/construct/macro I would love to know it--

note the _minor_ version string on the _kubectl_ server output:  *11+*

I wrote a template macro to properly express init-containers depending on whether or not the target is pre-1.8 (init containers are formatted as annotation strings) or post-1.8 (spec format).  Because the init-container problem spanned multiple releases, it is useful to be able to use something like:

```
{{- define "InitMethod" -}}
  {{- $major := .Capabilities.KubeVersion.Major -}}
  {{- $minor := .Capabilities.KubeVersion.Minor -}}
  {{- if and (lt (int $major) 2) (lt (int $minor) 8) }}
    {{- printf "annotation" -}}
  {{- else -}}
    {{- if (eq (int $major) 1) and (ge (int $minor) 8) }}
      {{- printf "spec" -}}
    {{- end -}} {{/* else if */}}
  {{- end -}} {{/* if */}}
{{- end -}} {{/* define */}}
```

to accommodate the different requirements.  Where this fails is when version strings are augmented with non-numeric characters.  `11+` just won't cast to an int! (shocking, eh?)  It would be very useful if helm presented this as `11` for such a situation.

**Comment by jascott1** [comment]
Hi @gladiatr72 

I will label this a feature but Im not sure it could be accommodated without breaking everyone else. IMO it would require a proposal documenting the advantages and impact of such a change. You could probably improve the function to handle it much more quickly and easily.

**Comment by bacongobbler** [comment]
closing as inactive.

**Comment by callowaylc** [comment]
i can't believe no one else has run into this - that plus character has ruined my day, so thanks guys, for the kitchen sink upgrade, the useless doc, and the laughable attempt at backwards compatibility. 

```sh
$ helm version
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
$ cat ./templates/*
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: lolz
  labels:
    minor: {{ .Capabilities.KubeVersion.Minor }}
    cast: "{{ int .Capabilities.KubeVersion.Minor }}"
```

w/template
```sh
$  helm template test . --dry-run
---
# Source: prometheus/templates/server-deployment.yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: lolz
  labels:
    minor: 16
    cast: "16"
```

w/install/ugrade
```sh
 $ helm install test . --dry-run
...
---
# Source: prometheus/templates/server-deployment.yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: lolz
  labels:
    minor: 16+
    cast: "0"
```

are you kidding me!

**Comment by pio2pio** [comment]
still happen with 
```sh
helm version 
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"}

 version --short 
Client Version: v1.18.6
Server Version: v1.17.9-eks-4c6976
```

**Comment by bacongobbler** [comment]
To be totally clear here: this field is populated directly by Kubernetes, and is defined by the cloud provider. We’re fetching this information from the Kubernetes API, and this is what’s returned. So it’s an upstream bug.

Please file issues with EKS/GKE.

**Comment by bacongobbler** [comment]
Another thing here... I don't think it was ever intended for these values to always return an integer. So casting the value from a string to an integer seems like a questionable design choice either way.

What you probably want instead is to treat those values as strings and compare the values alphabetically. So

```
{{- if and (eq major "1") (ge $minor "8") }}
```

That way you don't run into casting issues, and comparing the value "8" to "16+" still works as intended.

**Comment by pio2pio** [comment]
That is not a bad idea. Regarding the difference in the outputs in between template and install this is not an issue really. Because in most times this runs from a pipeline or being Installed manually and the install action has consisten output. Neverless thank you for the idea and the clarification.

**Comment by consideRatio** [comment]
I reported an issue for the EKS distribution of k8s: https://github.com/aws/eks-distro/issues/1128

**Comment by consideRatio** [comment]
For reference for other `helm` chart developers that run into this. This is the kind of data .Capabilities were populated with.

```
.Capabilities.KubeVersion: v1.22.9-eks-a64ea69
.Capabilities.KubeVersion.Major: 1
.Capabilities.KubeVersion.Minor: 22+
```

With that, you can avoid issues either like...

```
{{- if ge (atoi (.Capabilities.KubeVersion.Minor | replace "+" "")) 24 }}
```

Or like this...

```
{{- if semverCompare ">=1.24.0-0" .Capabilities.KubeVersion }}
```
