### ISSUE TITLE
Helm adds lables when creating resources?

### ISSUE THREAD

**Issue by koulq** [helm/helm#4931]
Output of `helm version`:

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Hello, I want to create a resource in helm, the dynamic tagging of the resource, what should I do?

**Comment by koulq** [comment]
The current, helm install command does not have labels

**Comment by jascott1** [comment]
Hi @koulq 

Can you elaborate a little more on what you are trying to accomplish? Typically you would embed anything you need into your templates and populate with values.

**Comment by jascott1** [comment]
Have you looked at existing stable charts? Im still not exactly sure what you are looking for but maybe checkout the Consul chart as an example. https://github.com/helm/charts/blob/master/stable/consul/templates/consul-statefulset.yaml#L5

**Comment by jascott1** [comment]
Hi @koulq 

Were you able to find a solution that fits your needs?

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
