### ISSUE TITLE
Helm is installing the chart to namespace called default. But on that namespace i dont see the tiller pod. The tiller pod is present in the kube-system namespace.

### ISSUE THREAD

**Issue by JosephIND** [helm/helm#4932]
Helm is installing the chart to namespace called default. But on that namespace i dont see the tiller pod. The tiller pod I installed in the `kube-system` namespace. Not sure how the pods part of the helm chart end up in the different namespace. 

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-05-12T04:12:12Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T09:56:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS

**Comment by bacongobbler** [comment]
Tiller installs charts by default to the `default` namespace. You can change that with the `--namespace` flag on `helm install`. It does not install charts based on tiller's current location.

Does that answer your question? :)

**Comment by JosephIND** [comment]
I was actually using the --namespace option. Even then it was installing to `default`. I got it fixed by setting kubectl context with --namespace option
