### ISSUE TITLE
Error: validation failed: unable to recognize "": no matches for kind "Deployment" in version ""

### ISSUE THREAD

**Issue by sebastus** [helm/helm#4935]
Output of `helm version`:
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.4", GitCommit:"bf9a868e8ea3d3a8fa53cbb22f566771b3f8068b", GitTreeState:"clean", BuildDate:"2018-10-25T19:06:30Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS

The problem:
helm upgrade --install --wait --set ** a couple of settings ** dev ** my helm folder **

results in:
Error: validation failed: unable to recognize "": no matches for kind "Deployment" in version ""

The helm folder has a Chart.yaml, values.yaml, templates folder with deployment.yaml. There are a few values referenced in the deployment.yaml, but overall it's a pretty trivial deployment. If I replace the values with hard coded values and run the deployment with kubectl, it works.

Sure would appreciate a pointer or two.

**Comment by bacongobbler** [comment]
Would you mind sharing your chart? I'm mostly interested what's in your deployment.yaml but a full chart example to reproduce the error would be most helpful. Thanks.

**Comment by sebastus** [comment]
[helm.zip](https://github.com/helm/helm/files/2589705/helm.zip)

**Comment by sebastus** [comment]
The problem is the Byte Order Mark bytes in the deployment.yaml file. I removed them and it works.

**Comment by AntonOfTheWoods** [comment]
It appears this is not restricted to BOM bytes - valid YAML comments before `apiVersion:` also show this.
