### ISSUE TITLE
set helm with --client-only 

### ISSUE THREAD

**Issue by zyriuse75** [helm/helm#4937]
i need to move helm to another server, so i follow a tutorial on how to setup helm with `--client-only`
and i ve read the helm doc as well.  :( 
however when i run `helm ls --tls ` i get after few minutes  `Error: context deadline exceeded
` even if i export **HELM_HOST=10.109.0.xx:44134**

how can i say to my helm you must to connect to this till **10.109.0.xx** ?

`helm version : SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710",
tiller version : SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710",`

**Comment by jascott1** [comment]
Hi @zyriuse75 

HELM_HOST is typically used for local development but should work if Tiller is actually available at that IP and port. Helm uses your .kube/config to reach the API server so make sure that kubectl is working too. You shouldn't really have to worry about Tiller location as the client should be using the API server for communication afaik.

**Comment by zyriuse75** [comment]
thanks for the advice . 
Do i've to setup kubectl on the second server ?

**Comment by zyriuse75** [comment]
i've setup kubectl on my server and as well i copy the `.kube/config`
if i try to get some information with the api it's fine 
`curl -k https://chgvas99:6443/api/v1/namespaces
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  }, `

however if i try with 
`helm ls --tls --host=10.109.0.XX --tls-cert .helm/cert.pem --tls-key .helm/key.pem  --debug`

i get  Error: context deadline exceeded

**Comment by zyriuse75** [comment]
it's work !! 

thanks for your help
