### ISSUE TITLE
Is helm designed to obfuscate the rendered config?

### ISSUE THREAD

**Issue by mabushey** [helm/helm#4938]
Bug report

`git clone https://github.com/helm/charts.git` - I find it really stupid that you can render & install a template from the cloud with `helm install`, but if you want only the rendered template (helm template) you have to clone it locally. They should both work one way or the other. Consistency is wonderful.

`helm template -f my-wordpress/values.yaml charts/stable/wordpress`
Error: found in requirements.yaml, but missing in charts/ directory: mariadb

`helm install --namespace wordpress --name my -f ./my-wordpress/values.yaml stable/wordpress` works (well it brings up broken containers anyway). Am I totally missing something or is helm just braindead?

It seems like helm wants to punish you for wanting to see what it's actually doing.

**Comment by bacongobbler** [comment]
closing as inactive.
