### ISSUE TITLE
can't get kubernetes manifest file from an installed release

### ISSUE THREAD

**Issue by jeremyxu2010** [helm/helm#4939]
Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-30T21:39:38Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  Docker for macOS

I installed a chart with custom `values.yaml` file several days ago. Now I found the installed release had a little error of configuration. But I can not found the  custom `values.yaml` file. So I want get k8s manifest file from an installed release, then modify the k8s manifest file and apply the modified k8s manifest file.

So is there any way to get k8s manifest file from an installed release? eg. use `helm export_manifest $releaseName`. maybe helm can save k8s manifest file into release's configmap.

**Comment by maorfr** [comment]
what about `helm get`?

**Comment by jeremyxu2010** [comment]
> what about `helm get`?

yeah, i get the answer:

```bash
helm get $releaseName | sed -n -e '/^MANIFEST:$/,$p'|grep -v 'MANIFEST:'
```

**Comment by bacongobbler** [comment]
You can also use `helm get manifest`. Closing as answered!
