### ISSUE TITLE
Missing documentation of pkg/chartutil/files.go functions

### ISSUE THREAD

**Issue by AssafKatz3** [helm/helm#4942]
Hi,
The functions FromJson, ToJson, FromYaml and ToYaml aren't documented as callable from templates (or at least, I couldn't find it). These functions are very useful for converting values objects to manifests files. fromJson also useful for the functionality of initialization of map inside template:
> {{- $results := fromJson "{}" -}}
> ...
> {{- $results := set $results $key (dict $objectType $value "password" $password "user" $object.user) -}}

Thanks

**Comment by bacongobbler** [comment]
closing as inactive.

**Comment by AssafKatz3** [comment]
@bacongobbler fromJson and toJson are still missing at documentation
