### ISSUE TITLE
environment specific values for helm chart

### ISSUE THREAD

**Issue by manojchandrabss** [helm/helm#4944]
Hi team,

I would like to create environment specific values (dev,stage,prod,int). Could you please help me with best practice documents or sample helm charts. it would be great help. 

How can i get the node affinity details for aws kubernetes AZ details. I didn't understand below syntax. Please help me with highlighted strings. how can i replace the AZ resource information. so that my pods will sit on 2 different AZ's

nodeAffinity:
    preferedDuringSchedulingIgnoredDuringExecution:
    nodeSelectorTerms:
    - matchExpressions:
      - key: kubernetes.io/e2e-az-EastWest
        operator: In
        values:
        - e2e-az-East
        - e2e-az-West

Output of `helm version`:Client: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

Output of `kubectl version`: kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3+coreos.0", GitCommit:"f588569ed1bd4a6c986205dd0d7b04da4ab1a3b6", GitTreeState:"clean", BuildDate:"2018-02-10T01:42:55Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AWS AKS

Thanks for your time.

Regards,
Manoj

**Comment by maorfr** [comment]
sounds like you should read this great document:
https://docs.helm.sh/developing_charts

**Comment by maorfr** [comment]
more specifically:
https://docs.helm.sh/developing_charts/#template-files
https://docs.helm.sh/developing_charts/#values-files

**Comment by manojchandrabss** [comment]
definitely, Thanks :)
