### ISSUE TITLE
template helper for accessing configmaps or secrets?

### ISSUE THREAD

**Issue by bbrewer-pillar** [helm/helm#4953]
I was wondering if this would be of any use to anyone. I have a use case where common, dynamic cluster information is shared by several different charts. At present, we can reference those config map values and inject them into pod containers etc. This tends to get a little verbose with lots of values along with some apps not playing nice with environment variables (helm solves things quite nicely for those with templating, of course, but we lose that with configmaps via env). Additionally, we can't really use those configmap values in other fields, like custom resource spec properties.

So, here is an example of what would be neat to have:
- a configmap called commonStuff in namespace default with  data of `foo: bar`
- a secret called secretStuff in namespace default with data of `foo: <base64 etc.>`
- a template function for bringing that in `{{ fromConfigMap "default" "commonStuff" "foo" }}` and `{{ fromSecret "default" "secretStuff" "foo" }}`
- OR a data structure for it like `{{ .ConfigMap.default.commonStuff.foo }}` and `{{ .Secret.default.secretStuff.foo }}` - NOTE: this would be probably be less useful as it's harder to call this with values.yml or set variables

This could be mostly accomplished today through a plug-in that pulls these into values files for use. Just thought I'd see if it were possible to find a cleaner, first-class way of doing it.

**Comment by bbrewer-pillar** [comment]
Yes, but helpers so I don't have to use those/can use them for things like tags, CRD fields, etc., not just environment variable injection. It's probably outside the scope of what helm should do though, so I'll close.

**Comment by tvalasek** [comment]
I'm 100% with you @bbrewer-papa-x . This is functionality I'm looking for too. Would you mind to re-open this case? My case is I would love to use Service annotation that is dynamic per cluster and its stored in secret. Helm should be able to read from secret and render final Service yaml file accordingly.

**Comment by adurai81** [comment]
Infact I've a similar requirement to. We have a need to set certain values in the ConfigMap that would then be referenced by K8s resources (not within the PODs) during deployment. For example while deploying the istio gateway we would like to pull certain values from the ConfigMap that was set already. Having a first-class support for this would be awesome. Can we pls re-open this as Enhancement request ?

In the mean-time what are my alternatives ? Can it only be achieved via setting the values in the values.yaml before `helm install` ?

**Comment by adurai81** [comment]
Since this issue is marked closed, I doubt if this is going to show-up on the issue list (due to filters). We might have to open new issue to draw attention.
