### ISSUE TITLE
Something went wrong while installing Helm Tiller in Gitlab

### ISSUE THREAD

**Issue by tarunkumard** [helm/helm#4957]
This is happening very specific with Gitlab,I have enterprise gitlab and when trying to set K8 cluster ,i filled out all mandatory information for existing K8 cluster and after integration while trying to install Helm Tiller ,get this strange issue of 

Something went wrong while installing Helm Tiller

No logs at all
 

Output of `helm version`:
vagrant@ubuntu-xenial:~$ helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
vagrant@ubuntu-xenial:~$
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:43:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS

**Comment by bacongobbler** [comment]
Can you perhaps provide a set of instructions you are trying to follow when installing tiller? With no logs and no instructions, I have no information to figure out the issue. Thanks.

**Comment by tarunkumard** [comment]
I have a canonical Kubernetes cluster developed by juju charms which i built using below article

juju deploy kubernetes-core

https://jujucharms.com/kubernetes-core/

Then I connected this cluster to Gitlab by providing below detaills

Kubernetes gitlab integrations steps

https://docs.gitlab.com/ee/user/project/clusters/

API URL, run kubectl cluster-info | grep 'Kubernetes master' | awk '/http/ {print $NF}'.
Token:
List the secrets by running: kubectl get secrets. Note the name of the secret you need the token for.
Get the token for the appropriate secret by running: kubectl get secret <SECRET_NAME> -o jsonpath="{['data']['token']}" | base64 -d
CA certificate, run kubectl get secret <secret name> -o jsonpath="{['data']['ca\.crt']}" | base64 -d.

But Gitlab shows below error with Helm Tiller

![image](https://user-images.githubusercontent.com/29559232/48883519-00adb080-edd5-11e8-9707-6d50dbbcf699.png)

**Comment by bacongobbler** [comment]
Oh... So this is a problem with gitlab itself, not necessarily helm. I'm afraid there's nothing we can do for you here. I suggest following up with the gitlab team directly.

Because this isn't an issue on our end (at least not until more logs can be shown), I'm going to close this and ask that you follow up with the gitlab team. Thanks!

**Comment by BobLamarley** [comment]
Someone had resolve this problem ? I'm facing the same issue, and the error is not detailed enough for me to understand :(

**Comment by bacongobbler** [comment]
@BobLamarley same for us as well. The error is not specific enough to determine the issue, but it's coming from gitlab, not Helm. I'd suggest opening a ticket with the gitlab team. We have no clue what would cause the error.

**Comment by BobLamarley** [comment]
@bacongobbler I was using the certificate .pem but i wasn't including "-----BEGIN CERTIFICATE-----" at the beggining and "-----END CERTIFICATE-----" at the end. Now my error has changed ^^
![image](https://user-images.githubusercontent.com/7857364/52259592-84326480-2923-11e9-83d8-f3883e120d01.png)
I will create a ticket with the gitlab team anymay :)

**Comment by BobLamarley** [comment]
For those wo've the same problem, I've managed the problem with this docs
https://docs.gitlab.com/ee/user/project/clusters/#adding-an-existing-kubernetes-cluster
I was missing a gitlab service account in the default namespace and a cluster role binding to give the gitlab service account cluster-admin privileges :)
