### ISSUE TITLE
negate dependencies.condition

### ISSUE THREAD

**Issue by yehiyam** [helm/helm#4960]
Hi 
This is more of a question. I have an umbrella chart that has two optional dependencies.
I want to install either one of the dependencies or the other but never both.
Is it possible to negate a value in the dependencies.condition?

maybe something like this:
```
dependencies:
  - name: chart1
    condition: global.production
  - name: chart2
    condition: not global.production
```
or 
```
   condition: !global.production
```

thanks in advance

Output of `helm version`:
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T20:55:30Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

**Comment by bacongobbler** [comment]
Unfortunately this functionality does not exist. Dependencies can only be disabled from a value being set to a boolean false.

**Comment by yehiyam** [comment]
Are you open to contribution for this?

**Comment by bacongobbler** [comment]
Yeah, I can see the usefulness in this. However, I'd hold off on writing up this feature until the first alpha of helm 3 is out and we can decide what's best to do there since requirements.yaml no longer exists and now lives inside Chart.yaml.

**Comment by maorfr** [comment]
I think you can achieve what you want using `tags`:
https://docs.helm.sh/developing_charts/#tags-and-condition-fields-in-requirements-yaml

**Comment by bacongobbler** [comment]
closing as inactive.

**Comment by pbarker** [comment]
Guess I'll use Pulumi, where conditional logic isn't crammed into YAML or not supported :)

**Comment by Stevenpc3** [comment]
Is this possible?
