### ISSUE TITLE
Negative conditions - requirements.yaml 

### ISSUE THREAD

**Issue by stephenmoloney** [helm/helm#4964]
Does helm support negative conditions in requirements.yaml?

Eg something like

```
condition: postgresql.enabled, not postgresql.useExternalUrl
```

**Comment by stephenmoloney** [comment]
wait,  someone else opened this issue 2 days, I was looking for this a few days ago and didn't check again for new issues! closing for #4960

**Comment by GUPTAPrashant15** [comment]
Hi

Were you ever able to figure out how to do this?
