### ISSUE TITLE
Helm 3: Let's talk about it

### ISSUE THREAD

**Issue by imroc** [helm/helm#4967]
I am really willing to contribute to Helm 3, I saw the code of the dev-3 branch and the Helm 3 Design Propoal, I think there are still some key refactorings that have been not started yet(e.g. lua engine, library chart), and some designs are still under discussion, not determined. (e.g. repository v2 https://github.com/helm/community/pull/57 https://github.com/helm/community/pull/55)

So I don't know where to start, can we talk about it ?

**Comment by bacongobbler** [comment]
Hey @imroc, we highly suggest discussing topics regarding Helm 3 development at the public dev calls on Thursday. Are you able to attend there?

If not then perhaps the mailing list would be a good place to discuss these topics.

**Comment by bacongobbler** [comment]
Sounds good. Closing!
