### ISSUE TITLE
sha256 file is not understood by sha256sum command

### ISSUE THREAD

**Issue by lwirzenius** [helm/helm#4968]
The sha256 checksum files on the release page, e.g., <https://storage.googleapis.com/kubernetes-helm/helm-v2.11.0-linux-amd64.tar.gz.sha256> have just the checksum. That is OK, but the Linux sha256sum command has the -c option, which allows it to check signatures, which is handy, as it avoids having to manually and visually check the checksum. If the file had two spaces and the filename appended to the line with the checksum, -c would work. Like this:

    02a4751586d6a80f6848b58e7f6bd6c973ffffadc52b4c06652db7def02773a1  helm-v2.11.0-linux-amd64.tar.gz

**Comment by bacongobbler** [comment]
it might be worth to write out a file parallel to the checksum files in [`make checksum`](https://github.com/helm/helm/blob/75b4afaa33a02ff01f041cf58a01535bca770cd6/Makefile#L48). Feel like taking a crack at that?

**Comment by lwirzenius** [comment]
Not sure having a parallel file is worth it. Just having a single file with the checksums of all files seems like the simpler approach, but in any case, adding the following line to the end of the checksum target (as line 52 in the file) should do the trick:

    shasum -a 256 _dist/*.{gz,zip} > SHA256SUM.txt

Then publish SHA254SUM.txt with the other release artifacts.

**Comment by bacongobbler** [comment]
There are CI system tooling out there that rely on the sha256 files so we can't remove them., but I see your point.

**Comment by Jeeppler** [comment]
I actually get the following error message while trying to verify the checksum in Linux using `sha256sum`:

```
sha256sum: helm-v2.11.0-linux-amd64.tar.gz.sha256: no properly formatted SHA256 checksum lines found
```

This is an issue for me.
