### ISSUE TITLE
Options with values now require use of equals sign

### ISSUE THREAD

**Issue by mrobinet** [helm/helm#4969]
**Output of `helm version`:**
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

**Output of `kubectl version`:**
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:20:58Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:36:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Cloud Provider/Platform (AKS, GKE, Minikube etc.):** 
Cluster was deployed into AWS with Kops

**Issue:**
After upgrading from Helm 2.10 to Helm 2.11 specifying TLS options without using equals no longer works.

```
$ helm ls --tls --tls-cert /Users/Mike/.helm/tls/k8s.strelengsb.com/cert.pem --tls-key /Users/Mike/.helm/tls/k8s.strelengsb.com/key.pem

Error: unknown command "/Users/Mike/.helm/tls/k8s.strelengsb.com/cert.pem" for "helm"
Run 'helm --help' for usage.
```

The workaround is to use equals: 
```
$ helm ls --tls --tls-cert=/Users/Mike/.helm/tls/k8s.strelengsb.com/cert.pem --tls-key=/Users/Mike/.helm/tls/k8s.strelengsb.com/key.pem
```

**Expected Result:**
Options values can still be provided without equals, otherwise add a note to the release changelog if this is a desired change.

**Comment by bacongobbler** [comment]
Interesting! I can reproduce this as well.

```
PS C:\Users\me> helm version -c false
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
PS C:\Users\me> helm version -c=false
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

**Comment by rajatjindal** [comment]
spf13/cobra for boolean it always needs = sign for false. refer to this comment from eparis: https://github.com/spf13/cobra/issues/613#issuecomment-357706597

Also I tested with helm version 2.11, and I get different (but expected) output:

`helm ls --tls --tls-cert /Users/Mike/.helm/tls/k8s.strelengsb.com/cert.pem --tls-key /Users/Mike/.helm/tls/k8s.strelengsb.co
m/key.pem
could not read x509 key pair (cert: "/Users/Mike/.helm/tls/k8s.strelengsb.com/cert.pem", key: "/Users/Mike/.helm/tls/k8s.strel
engsb.com/key.pem"): can't load key pair from cert /Users/Mike/.helm/tls/k8s.strelengsb.com/cert.pem and key /Users/Mike/.helm
/tls/k8s.strelengsb.com/key.pem: open /Users/Mike/.helm/tls/k8s.strelengsb.com/cert.pem: no such file or directory`

`helm version -c
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}`

can you please double check @mrobinet and let me know if i misinterpreted something here.

**Comment by mrobinet** [comment]
@rajatjindal Your error is because the cert and private key don't exist on your system. You will need to test by pointing those options to a cert and key that exist for you locally. The equals were optional in 2.10 so this is regression.

**Comment by rajatjindal** [comment]
the equals were/are optional for non-bool flags. also I think the error of "file don't exist" occurs after Cobra is done processing the command line args/flags. 

can you please provide the o/p of "helm version -c"

**Comment by mrobinet** [comment]
I see the same output as @bacongobbler when testing `helm version -c false` vs `helm version -c=false`.

**Comment by rajatjindal** [comment]
i am looking for the version number and git hash info.

can you please paste o/p of "helm version -c"

**Comment by rajatjindal** [comment]
oh one diff i just noted is you are using Windows. wondering if that has to do with something.

**Comment by mrobinet** [comment]
@rajatjindal My helm version output is already listed in the original ticket description. I'm not on Windows, I'm on OS X High Sierra (10.13.6).

**Comment by rajatjindal** [comment]
oh sorry about that @mrobinet , i missed that.

**Comment by mrobinet** [comment]
So I just tried `helm ls --tls --tls-cert /Users/Mike/.helm/tls/k8s.strelengsb.com/cert.pem --tls-key /Users/Mike/.helm/tls/k8s.strelengsb.com/key.pem` again and it works for me now. 🤷‍♂️

Something must have been messed up in my shell after the upgrade when I reported this. The handling of boolean flags as identified by @rajatjindal has changed from 2.10 to 2.11 though. Not sure if that alone is worth a mention in the changelog or not? If not, this issue can just be closed.

**Comment by bacongobbler** [comment]
Yeah, I can see why `-c false` is evaluated as `true`. It's because the presence of `-c` on its own is evaluated as `true`, so `-c false` is kinda ambiguous. I don't think this is worth a mention in the changelog. Thank you for the report though!
