### ISSUE TITLE
Helm client should accept contexts

### ISSUE THREAD

**Issue by bkeroackdsc** [helm/helm#4970]
We use the helm client (`pkg/helm`) in a few of our internal projects. I would like to submit a PR that allows the various client methods (`InstallRelease`, `UpdateRelease`) to accept contexts so the client can cancel long-running requests that use `InstallWait` or `UpgradeWait`.

In terms of making the PR acceptable for upstream merge, would you prefer that I change the method signatures directly (and break backwards-compatibility), or create new methods like `InstallReleaseWithContext`?

Thanks for any input.

**Comment by bkeroackdsc** [comment]
PR #4971 is ready for code review/feedback.

**Comment by bkeroackdsc** [comment]
A new fixed up PR is ready for review: #4985

**Comment by bacongobbler** [comment]
Can the context object be part of the [client options](https://github.com/helm/helm/blob/master/pkg/helm/option.go) instead? That way we don't have to introduce new functions, and any request that relies on `--wait` can pass along that context object (if it's been set).

If you're still interested in this work, it'd probably be better to get this into Helm 3. Currently we're not looking at new features for Helm 2 unless it's a security fix or a bug fix. I'm currently working on refactoring the helm client packages for helm 3 and will have something more substantial to show in the coming weeks.

**Comment by bkeroackdsc** [comment]
If you'd prefer it to be a field on the client options, we can do that. We use my forked version of the client so it would be easier for us to get it merged prior to Helm 3 being released, but if that's not possible I can open a different PR for Helm 3 I guess.
