### ISSUE TITLE
Force helm install/upgrade using --version flags

### ISSUE THREAD

**Issue by LittleWhiteYA** [helm/helm#4980]
Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS

I see the flag when running helm upgrade --help
```
--version string       specify the exact chart version to use. If this is not specified, the latest version is used
```
Can I change this `--version` default to be required.
Because sometimes someone may forget to run `helm repo update` before install/upgrade.
It may cause some problems because it may downgrade chart version.

Thanks for your input !

**Comment by maorfr** [comment]
Sounds like your problem is an automation one rather then an issue with helm ;)

**Comment by bacongobbler** [comment]
You could certainly fork helm to enforce the --version flag, but I don't think we'd ever consider supporting that kind of workflow unless there was a larg demand for it. That definitely sounds like an internal policy thing, as @maorfr puts it :)

**Comment by maorfr** [comment]
You could simply use an alias:

```
function helm() {
    if [[ "$1" == "upgrade" ]] && [[ "$@" != *"--help"* ]] && [[ "$@" != *"--version"* ]]
    then
        echo "--version flag is required"
        return
    fi
    $(which helm) "$@"
}
```

**Comment by maorfr** [comment]
Or better yet:

```
function helm() {
    if [[ "$1" == "upgrade" ]] && [[ "$@" != *"--help"* ]]
    then
        helm repo update
    fi
    $(which helm) "$@"
}
```

**Comment by LittleWhiteYA** [comment]
@bacongobbler @maorfr Thanks for your reply !

We upgrade the staging version automatically, but still upgrade the production manually.
So you guys don't face this problem because you already upgrade production automatically ???
Before doing that automatically, I think I should tell my colleagues to write that script ...

**Comment by bacongobbler** [comment]
closing as inactive.
