### ISSUE TITLE
Error in modifying template variables via assignments

### ISSUE THREAD

**Issue by nuxlli** [helm/helm#4987]
I have been trying to use a feature available in [go1.11](https://golang.org/doc/go1.11#text/template), which basically allows a value to be assigned a declared variable outside the scope of an if:

```yaml
# Svc host
{{- $svcHost := print "." .Release.Namespace ".svc.cluster.local" }}

# Postgresql
{{- $pgUser := default "postgres" .Values.postgresql.postgresUser }}
{{- $pgPassword := .Values.postgresql.postgresPassword }}
{{- $pgDatabase := .Values.postgresql.postgresDatabase }}
{{- $pgHost := .Values.postgresql.postgresHost }}
{{- if not $pgHost }}
{{- $pgHost = print $.Release.Name "-" (default "postgresql" $.Values.postgresql.nameOverride) $svcHost}}
{{- end }}
NOTIFY_API_DATABASE_URL: {{ (print "ecto://" $pgUser ":" $pgPassword "@" $pgHost "/" $pgDatabase) | b64enc | quote }}
```

This works correctly when I try `helm template`, but when I try `helm upgrade` I'm getting the following error:

```
Error: UPGRADE FAILED: parse error in "<chart_name>/templates/secrets.yaml":
template: <chart_name>/templates/secrets.yaml:33: unexpected "=" in operand
```

---

Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

**Comment by hickeyma** [comment]
Seems to be missing the assignment to the variable when you set value again on `pgHost`.
Try changing this line `{{- $pgHost = print $.Release.Name "-" (default "postgresql" $.Values.postgresql.nameOverride) $svcHost}}` --> `{{- $pgHost := print $.Release.Name "-" (default "postgresql" $.Values.postgresql.nameOverride) $svcHost}}`

As an aside, when debugging I tend to use `helm --debug --dry-run`: https://docs.helm.sh/chart_template_guide/#debugging-templates . BTW, this also failed for me when using `helm template [chart]`.

**Comment by nuxlli** [comment]
@hickeyma I understand your suggestion, but it is just the opposite of what I’m trying.
With the `:=` operator, the attribution of the value is limited to the scope of the if. It won’t overwrite the `$pgHost` declared outside of it.

The `=` is a new operator available in the stdlib starting with `golang 1.11`, which allows overwriting the value of a variable in the scope outside the if.

What I wasn’t able to understand is: it works perfectly in `helm template`, but not in `helm upgrade`.

**Comment by hickeyma** [comment]
Ok, I see .. have to think more on this..

BTW, `helm template ` did not work for me with the '=' assignement

**Comment by hickeyma** [comment]
Not sure why this is not working.

You can however rewrite these lines:
`{{- $pgHost := .Values.postgresql.postgresHost }}
{{- if not $pgHost }}
{{- $pgHost = print $.Release.Name "-" (default "postgresql" $.Values.postgresql.nameOverride) $svcHost}}
{{- end }}`

as follows:
`
{{- $pgHost := .Values.postgresql.postgresHost | default (print $.Release.Name "-" (default "postgresql" $.Values.postgresql.nameOverride) $svcHost) }}
`

which removes the need for the `=` assignment.

**Comment by bacongobbler** [comment]
Helm 2.11.0 was [compiled against Go 1.10](https://github.com/helm/helm/blob/2e55dbe1fdb5fdb96b75ff144a339489417b146b/.circleci/config.yml#L7) which is why this feature won't work. You need to use something compiled against https://github.com/helm/helm/pull/4637 (such as [Helm 2.12.0-rc.1](https://github.com/helm/helm/releases/tag/v2.12.0-rc.1)) if you want to use a version of Helm compiled against Go 1.11.

If you try the release candidate, does that work?

**Comment by andresmgot** [comment]
I have found the same issue. I can confirm that the `=` assignment doesn't work with Helm `v2.11.0` but it does with `v2.12.X`.

**Comment by hickeyma** [comment]
@nuxlli As tested and proved, this works with v2.12.x. If you can't use this version then maybe compile against Go 1.11. 
If this solves your issue, can this be closed?

**Comment by nuxlli** [comment]
@hickeyma sorry for the delay in responding to this issue. I tested it with v1.13.0 and it works, thank you for the solution :)
