### ISSUE TITLE
Using helm api

### ISSUE THREAD

**Issue by kbielak** [helm/helm#5004]
I'm trying to utilise helm api from this project to deploy helm package via golang project. For non k8s experts it's incredibly difficult to accomplish the goal - I cannot find any documentation and the logs are not saying much. Anyone struggled with that? Is there any exemplar or documentation? Thanks in advance

**Comment by hickeyma** [comment]
Refer to [here](https://github.com/helm/helm/issues/3663#issuecomment-418888212) for some information on using pkg/helm .

**Comment by bacongobbler** [comment]
Closing as a duplicate of #3663

**Comment by robel-yemane** [comment]
Seconding @kbielak , I have the same issue. I've looked at Issue [#3663](https://github.com/helm/helm/issues/3663) but didn't get any useful examples. If possible, I'm looking at examples of this [sort](https://github.com/kubernetes/client-go/tree/master/examples) .
Thanks
