### ISSUE TITLE
Helm hooks question or feature request

### ISSUE THREAD

**Issue by meysholdt** [helm/helm#5005]
hello!

the application I'm working on makes use of a database and with new versions of the applications, the schema of the database needs to be upgraded. New schemas are usually backwards-compatible in the sense that v1 of an application works also with v2 of the schema. However, 2v of the application needs v2 of the schema.

The application has a container responsible for running schema migrations and database initialisation, since we treat a database without tables like the version zero in the sequence of db migrations. 

So the idea was to run db migrations during `helm install` and `helm upgrade`.

I thought this could be done by creating a Kubernets-Job registered as Helm-Hook on events like `*-install` and `*-upgrade`.

However, the database itself is managed by helm. The chart of the application uses `requirements.yaml` to include [helm/charts/stable/mysql](https://github.com/helm/charts/tree/master/stable/mysql).

For a successful `helm install` the following execution order is needed:
1. deploy mysql chart
2. run db-migrations
3. deploy application

So here is the question: Can this be done with a single call of `helm install myapplication`?

I can't use the helm-hook `pre-install` because this would run db-migrations before the db has been launched.
I can't use the helm-hook `post-install` because this would run db-migrations after the application has been deployed. Thus, while db-migrations runs, the applications sees an invalid database state and it's containers go into a crash-reboot-loop.

Thank you for your help!

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
