### ISSUE TITLE
helm debug ls not showing any additional info

### ISSUE THREAD

**Issue by chrissound** [helm/helm#5007]
```
helm --debug ls
Error: could not find tiller
```

I expect some debug output because tiller is running in the cluster..

```
helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.11", GitCommit:"dc4f6dda6a08aae2108d7a7fdc2a44fa23900f4c", GitTreeState:"clean", BuildDate:"2018-11-10T20:22:02Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd6
```4"}

**Comment by AlexandrSemak** [comment]
You must have KUBECONFIG in your env variables

**Comment by hickeyma** [comment]
It doesn't seem to be. When you do `helm version` you should get the server version also.

Could you try: `helm init --upgrade` ?

Some more info here: https://docs.helm.sh/using_helm#initialize-helm-and-install-tiller

**Comment by hickeyma** [comment]
Is there anything in the logs for the tiller pod?

**Comment by maorfr** [comment]
it seems you are installing `tiller` in `k8s-tiller` namespace.
can you try doing the same and then running `helm version --tiller-namespace k8s-tiller`?

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
