### ISSUE TITLE
Invalid charts causes error message without resource information

### ISSUE THREAD

**Issue by mdeknowis** [helm/helm#5008]
As we try to install a helm release:

```txt
helm upgrade --install --namespace foo --version 1.2.3 bar charts/foobar
```

we experience an error like this

```txt
Error: Secret in version "v1" cannot be handled as a Secret: v1.Secret.ObjectMeta: v1.ObjectMeta.TypeMeta: Kind: Data: decode base64: illegal base64 data at input byte 36, error found in #10 byte of ...|XDdrzjbnbr"},"kind":"|..., bigger context ...|ldsU"},"kind":"Secret","metadata":{"annotations":{"helm|...
```

As we are automate all our steps and use variables, it's not easy to track down the root cause. We would expect, that helm provides some information like

* the resource name
* or resource path

which is invalid. So as a user of helm I've a chance to track down the invalid resource and the root cause.

Output of `helm version`:

```txt
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```
Output of `kubectl version`:

```txt
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.8+IKS", GitCommit:"6e1ad1c45c23e44d15090962f3e738735998687a", GitTreeState:"clean", BuildDate:"2018-09-27T13:44:25Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): IBM Public Cloud

#4430 is addressing a different issue, but shows similar issue in that case the error message was:

```txt
Error: release y failed: Service in version "v1" cannot be handled as a Service: v1.Service.ObjectMeta: v1.ObjectMeta.Labels: ReadString: expects " or n, but found t, error found in #10 byte of ...|release":true},"name|..., bigger context ...|chart":"foo-0.1.0","heritage":"Tiller","release":true},"name":"y-foo","namespace":"default"},"spec":|...
```

**Comment by mdeknowis** [comment]
Also using `--debug` does not provide helpful information:

```txt
[debug] Created tunnel using local port: '37374'

[debug] SERVER: "127.0.0.1:37374"

[debug] Fetched cp-charts/auto-devops to /root/.helm/cache/archive/foobar-1.2.3.tgz

Release "ado-demo" does not exist. Installing it now.
[debug] CHART PATH: /root/.helm/cache/archive/foobar-1.2.3.tgz

Error: Secret in version "v1" cannot be handled as a Secret: v1.Secret.ObjectMeta: v1.ObjectMeta.TypeMeta: Kind: Data: decode base64: illegal base64 data at input byte 36, error found in #10 byte of ...|XDdrzjbnbr"},"kind":"|..., bigger context ...|ldsU"},"kind":"Secret","metadata":{"annotations":{"helm|...
```

**Comment by hickeyma** [comment]
Could you try running this `helm install --debug --dry-run --namespace foo --version 1.2.3 bar charts/foobar` , and post the output?

**Comment by mdeknowis** [comment]
We just "enhanced" our pipelines to allow such changes, but in general it would be great to get more data without exposing the content with credentials and secrets in it into logs of automated executions systems.

**Comment by mdeknowis** [comment]
I assume, the original error messages are k8s error messages, but perhaps can helm wrap it by providing at least resource information.

In a different case, we got this error, which is pretty helpful:

```txt
Error: Secret "my-secret" is invalid: data[.dockercfg]: Invalid value: "<secret contents redacted>": invalid character 'e' looking for beginning of value
```

**Comment by bacongobbler** [comment]
I'm sorry, I can't quite grok what the action item you're requesting for here. Would you mind clarifying what you'd like to see?

**Comment by hickeyma** [comment]
Some updates were done to the messaging around value parsing in #4736 which should help with this and also with chart dependencies.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
