### ISSUE TITLE
Is there any way to render ignored template?

### ISSUE THREAD

**Issue by katsew** [helm/helm#5014]
I use `helm template` to render template locally, and `kubectl apply` to create resources.
However, I do not want to render some of the template like `job`.

I added a directory `job/` to `.helmignore` to ignore it, then I create whole template and it works.
However, this also applied on `-x` option to specify the template, so I can't render specified job manifest to use `helm template`.
I also try naming manifest like `_job.yaml` to ignore, but the result is the same.

Is there any way to do this?
thanks.

**Comment by bacongobbler** [comment]
Some charts achieve this by wrapping the entire `Job` in an `if` block. This is quite commonly used when users want to selectively install `Ingress` resources based on whether or not there is an ingress controller present, for example.

```
{{- if .Values.myjob.enabled -}}
...
{{ endif }}
```

Will that work for you?

**Comment by katsew** [comment]
@bacongobbler 

Thanks for quick response :)
That works when I set value dynamically like `helm template --set job.enabled=true -x templates/job.yaml`.

But I have to write `values.yaml` like:
```
job:
  # This value always set to `false`.
  enabled: false
```

I feel this is a little weird, but it works.
Thank you!
