### ISSUE TITLE
It would be helpful to mention commit signing in the Developer Guide

### ISSUE THREAD

**Issue by henrynash** [helm/helm#5016]
We have a Git Convention section in the Developer Guide docs for helm, which gives the basic outline of the process for working on and submitting a change. While our Contributing doc does mention the fact that we require you to sign the code (and lots of detail on how to do this), it would be helpful just to mention it as part of the Developer Guide outline, e.g. where it currently says:

"When you are ready for us to review, push your branch to GitHub, and then open a new pull request with us."

...perhaps we might say:

"When you are ready for us to review, sign your commit, push your branch to GitHub, and then open a new pull request with us."

**Comment by hickeyma** [comment]
Just wondering out loud what is the need for a developer guide and a contributor doc. Could they be integrated into the one doc?

My thinking here is that there is lots of cross over and the issue with this is that you have to sync-up 2 docs with similar information which can be cumbersome.

**Comment by henrynash** [comment]
@hickeyma I think that is probably a good idea to discuss...although sounds like a much larger (but potentially useful) set of work. Maybe let's consider that as a separate issue?
