### ISSUE TITLE
ImagePullBackOff error when install tiller by `installer.Install`

### ISSUE THREAD

**Issue by edwardstudy** [helm/helm#5023]
Hi, I just import helm package to my project and want ot install tiller with default version(v2.10). So I invoked `installer.Install` without any opts. It meant that generated tiller deployment shuold use default image `gcr.io/kubernetes-helm/tiller:v2.10` which was generated by defaultImage + version.Version`v2.10`. So it cannot pull image because right image tag is v2.10.0 in registry.

So I downloaded helm v2.10.0 binary which also contains version.Version`v2.10` but specfied `v2.10.0` tag when ran `init` command. It disappoinited me.
 
Are I invoking `installer` package wrong? Please help me if you have any idea.

Thanks.

Output of `helm version`:
```
~/journey/ops/helm  version -c
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-05-12T04:12:12Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by bacongobbler** [comment]
At compile time, the [version field is overridden](https://github.com/helm/helm/blob/158d6dbb746f525bad9a0aacb698af7d370ac3f5/versioning.mk#L16-L19) to the tag being deployed. If you're trying to use pkg/version as a third-party package, I would not rely on this variable and instead use `v2.10.0` directly.
