### ISSUE TITLE
Add platform binaries urls to assets

### ISSUE THREAD

**Issue by cpeetersburg** [helm/helm#5026]
To be able to automate the process of downloading and installing Helm on my Linux machines I need to find the download URL for the binaries from the [Github API](https://api.github.com/repos/helm/helm/releases).

Currently the download links for the binaries are stored in the body which makes it very difficult to query for the right URL.

Please add the download URLs for the binaries to the assets. Check the following repositories to better understand the question:
- [Rancher](https://api.github.com/repos/rancher/rancher/releases)
- [RKE](https://api.github.com/repos/rancher/rke/releases)

**Comment by bacongobbler** [comment]
FYI, here's a way to do it today: https://github.com/helm/helm/blob/158d6dbb746f525bad9a0aacb698af7d370ac3f5/scripts/get#L78-L91

**Comment by bacongobbler** [comment]
closing as inactive.
