### ISSUE TITLE
dots in value name is misinterpreted by toYaml

### ISSUE THREAD

**Issue by victornoel** [helm/helm#5027]
If I have the following value:
```
stuff:
  thing.lol: testestest
```

`toYaml` will render:
```
stuff:
  thing:
    lol: testestest
```

I don't think this should happen :)

**Comment by bacongobbler** [comment]
that is actually how the YAML parser works. If you want dots in your name, try encasing it with quotes:

```
stuff:
  "thing.lol": testestest
```

let me know how that works out for you.

**Comment by victornoel** [comment]
@bacongobbler indeed, thanks for the explanation.

And what if I want to set `stuff."thing.lol"` from the command line with the `--set` parameter?

I'm using helmfile's following construct:
```
set:
  - name: files.my-file.txt
    file: my-files/file1.txt
```

But of course it can't work like this…

**Comment by bacongobbler** [comment]
by using escape codes: `--set stuff.thing\.lol="test"`.

**Comment by victornoel** [comment]
@bacongobbler excellent, thank you for your help.

For the record it works like this with helmfile:
```
set:
  - name: "files.my-file\\.txt"
    file: my-files/file1.txt
```

**Comment by bacongobbler** [comment]
See https://docs.helm.sh/using_helm#the-format-and-limitations-of-set for more details

Closing as answered, but please let me know if you have further questions.

**Comment by bacongobbler** [comment]
See also https://docs.helm.sh/using_helm#the-format-and-limitations-of-set for more information.

I'm going to close this as answered but please let me know if you have further questions. Thanks!

**Comment by dalbani** [comment]
For those who might run into the same problem, I personally had to use the following syntax with `helm` on the command line (quotes _and_ backslash):
```--set-file param."file\.extension"=the-file.txt```

**Comment by EronWright** [comment]
I observe that Helm 3 doesn't seem to support this.  For example these two values files seem to be interpreted differently:

```yaml
prometheus.enabled: false
```

```yaml
prometheus:
  enabled: false
```
