### ISSUE TITLE
We should document the process for approval of features/proposals

### ISSUE THREAD

**Issue by henrynash** [helm/helm#5028]
Like any project, we have many new small features (and some larger proposals) that get suggested. Our process for approving these (where approval means: "if you/someone can deliver this, we would be happy to merge it") is one of lazy agreement among the core maintainers unless any one of them violent objects. We should document this (and discuss/amend if required).

**Comment by jascott1** [comment]
We should also add something about requiring a proposal and requiring some sign off from n maintainers. Perhaps super trivial changes could skip a proposal but still require approval in the feature issue.

**Comment by bridgetkromhout** [comment]
Looking at https://github.com/helm/helm/blob/master/CONTRIBUTING.md#issues I think we have a lot more detail now than we had when this issue was opened. I think the topics mentioned here are covered pretty well in that document. Please let us know if there is more missing.
