### ISSUE TITLE
Unclear English in Charts Hooks docs

### ISSUE THREAD

**Issue by AntonOfTheWoods** [helm/helm#5035]
The English in https://github.com/helm/helm/blob/master/docs/charts_hooks.md#automatically-delete-hook-from-previous-release is not very clear. I would have attempted to improve it but as I don't know that much about `helm` yet, I might have introduced further inaccuracies...

**Comment by henrynash** [comment]
I agree this is confusing - I'll take a shot at proposing new wording..
