### ISSUE TITLE
Read-only view of Helm Chart installed on cluster (web access)

### ISSUE THREAD

**Issue by newalp** [helm/helm#5045]
Output of `helm version`: v2.11.0
Output of `kubectl version`: v1.12.0
Cloud Provider/Platform (AKS, GKE, Minikube etc.): EKS

I would like to display via a web page (can develop this bit) the current version of helm charts deployed to my cluster.
This will give visibility to what is currently running on the cluster without having to login to Kubernetes/install helm.
Is there a way to query Tiller API maybe?

**Comment by bacongobbler** [comment]
The [kubeapps](https://github.com/kubeapps/kubeapps) project is one such solution you may want to have a look at.

**Comment by newalp** [comment]
Thanks @bacongobbler, looks like kubeapps looks good.
My use-case is that I would like the development teams to view what is deployed on kubernetes. Basically a web view of the command helm list (with CHART and APP VERSION).
Kubeapps looks like it would give them too much power like the ability to deploy. Not something I am looking to have in Production.
Or is there a read-only view of kubeapps?

**Comment by bacongobbler** [comment]
Not off the top of my head. I'd look at the project's documentation or chst with the maintainers!

**Comment by newalp** [comment]
Looking at coding this myself maybe. Any advice? 
I know that configmaps are used to store the data (but I cannot find the APP VERSION there), would it be the best way to grab the data or would it be best to talk to Tiller directly?

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
