### ISSUE TITLE
helm client  get same ready tiller pod  every time?

### ISSUE THREAD

**Issue by silenceper** [helm/helm#5047]
I have a question about this code：
https://github.com/helm/helm/blob/7b821dd52fffa135cfe78611299b0491f7f03d39/pkg/helm/portforwarder/portforwarder.go#L72-L87
 
 I see that the helm client takes the pod of the first ready state every time. If I have multiple pods, it can be load balanced, avoiding the first pod overload？

**Comment by Stelminator** [comment]
Followup: if helm v3 doesn't have tiller, will there be a locking mechanism to prevent simultaneous deploys to the same release?  Also, is there even anything in the current tiller setup that would does similar locking?

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
