### ISSUE TITLE
Metadata labels mixed across releases deployed concurrently

### ISSUE THREAD

**Issue by carlosjgp** [helm/helm#5053]
Output of `helm version`:
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.11-eks", GitCommit:"6bf27214b7e3e1e47dce27dcbd73ee1b27adadd0", GitTreeState:"clean", BuildDate:"2018-12-04T13:33:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
EKS (eks.3) Ireland

Hi! We are deploying Helm charts through [Landscaper](https://github.com/Eneco/landscaper) into our EKS cluster and this morning, like every morning, we spun up a test environment and deployed ~30 releases and we have ended up in a really strange situation were one of the releases (NodeJs) had metadata labels from another release (Java)... but only the keys

```
  labels:    
    app: my-app-name
    product: my-product
    stack: my-stack
    owner: my-team
    parentVersion: 
    springBootVersion: 
    chart: my-chart-1.0
    release: "my-release-name"
    revision: "1"
    heritage: Tiller
```
this two labels
```
    parentVersion: 
    springBootVersion: 
```
are only present in our Java apps and there is no reference to them on the NodeJs chart and are present and empty on every single resource of this release.

We populate this metadata across all the release resources using a template on a file called `_common_helpers.tpl`

```
{{ define "common.labels" }}
app: {{ template "helm.name" . }}
product: {{ required "meta.product must be specified in values" .Values.meta.product }}
stack: {{ required "meta.stack must be specified in values" .Values.meta.stack }}
owner: {{ required "meta.owner must be specified in values" .Values.meta.owner }}
chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
release: {{ .Release.Name | quote }}
revision: {{ .Release.Revision | quote }}
heritage: {{ .Release.Service }}
{{ end }}
```

the java apps also have a file called `_common_helpers.tpl` with the same template name but different content
```
{{ define "common.labels" }}
app: {{ template "helm.name" . }}
product: {{ required "meta.product must be specified in values" .Values.meta.product }}
stack: {{ required "meta.stack must be specified in values" .Values.meta.stack }}
owner: {{ required "meta.owner must be specified in values" .Values.meta.owner }}
parentVersion: {{ .Values.meta.parentVersion }}
springBootVersion: {{ .Values.meta.springBootVersion }}
chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
release: {{ .Release.Name | quote }}
revision: {{ .Release.Revision | quote }}
heritage: {{ .Release.Service }}
{{ end }}
```

I was wondering if anybody has experienced something similar. I was trying to track the issue down but maybe someone can point me to the right place? I'm just a GoLang beginner

Thanks!

**Comment by maorfr** [comment]
I suggest you open this issue with landscaper first

**Comment by maorfr** [comment]
@carlosjgp 

I have not worked with landscaper in the past. We did write a similar tool which deploys releases in parallel using a single Tiller pod, and things did not get mixed up.

What I would do to debug, is add another step to my pipeline: `helm upgrade ... --dry-run --debug`
Add it right before the actual upgrade (or install) command to see what is going on.

That may help isolate the problem's origin.

Hope this helps!

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
