### ISSUE TITLE
Intermittent failure without changes to values/helm charts

### ISSUE THREAD

**Issue by lostllama** [helm/helm#5056]
Output of `helm version`:

    Client: &version.Version{SemVer:"v2.9.1", 
    GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
    Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

Output of `kubectl version`:

    Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", 
    GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
    Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.11", 
    GitCommit:"dc4f6dda6a08aae2108d7a7fdc2a44fa23900f4c", GitTreeState:"clean", BuildDate:"2018-11-10T20:22:02Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  GKE

The message I'm getting is:

> Error: UPGRADE FAILED: failed to create patch: failed to get versionedObject: unable to convert unstructured object to apps/v1, Kind=Deployment: unrecognized type: string

The only difference between each upgrade is that I'm passing `--set image.web=$IMAGENAME` where `$IMAGENAME` is something like `backgroundworker-shortcommitid`. The image build and upgrade are done through CI (the same CI build).

Scenario:

1. Deploy application - works
2. Change application code (C#) and redeploy application - works
3. Change application code (C#) and redeploy application - doesn't work (message as above).
4. Make insignificant change to repository (e.g. add empty text file or remove newline from code) and redeploy application - works.

Why is this happening?

**Comment by maorfr** [comment]
Not exactly an answer to the question, but why are you not committing the image tag to source control?

**Comment by lostllama** [comment]
> Not exactly an answer to the question, but why are you not committing the image tag to source control?

@maorfr How would I know the commit id in advance? The first step of the CI process is to build a Docker image, tag it like backgroundworker-shortcommitid, and push it to our repo. The second step is to upgrade the helm deployment to update the kubernetes deployment to the latest version of the image.

**Comment by maorfr** [comment]
I don't quite understand the question. If you know how to tag the image, you know what to update in the chart. Push it to source control, and move on from there.

Btw, `set --image.web=...` seems wrong.
Should probably be `--set web.image=...`.

**Comment by lostllama** [comment]
@maorfr I don't understand your line of questioning. I have no issues whatsoever tagging my image or deploying it, except for this intermittent failure.

My question is why I intermittently get this failure:

> Error: UPGRADE FAILED: failed to create patch: failed to get versionedObject: unable to convert unstructured object to apps/v1, Kind=Deployment: unrecognized type: string

The other information was so that I'd covered all bases of things that could change from build to build in my question.

**Comment by mortent** [comment]
@lostllama Do you have a chart you could share here that reproduces the problem? Even if it doesn't fail every time, it would still be useful. I'm happy to look into this cause it seems like an actual bug.

If you can't create an example chart, are you able to share the logs from tiller? That would give a little more information about where in the upgrade process the error happens.

**Comment by lostllama** [comment]
@mortent Sure, I'll try to gather that information on Monday :) Thank you.

**Comment by lostllama** [comment]
I've uploaded the logs. The failure in the logs is from the failing example, and the success is from the subsequent passing example.

[tillerLogs.txt](https://github.com/helm/helm/files/2684569/tillerLogs.txt)
[failingExample.txt](https://github.com/helm/helm/files/2684570/failingExample.txt)
[passingExample.txt](https://github.com/helm/helm/files/2684571/passingExample.txt)

**Comment by lostllama** [comment]
Sorry, I forgot to include the charts themselves. Here they are:
[charts.zip](https://github.com/helm/helm/files/2688428/charts.zip)

**Comment by mortent** [comment]
@lostllama So the problem is actually in your chart. The `build` label needs to be a string, but the value is not inside quotes. This is fine as long as the build value has some non-numeric characters in them so it can't be interpreted as a number, which is the case for your passing example. But if the build can be interpreted as a number, like in your failing example, the deployment manifest is no longer valid.
 
The fix is simple though. Either `build: "{{ $settings.build }}"` (with quotes) or `build: {{ $settings.build | quote }}` should work.

**Comment by bacongobbler** [comment]
Unfortunately the error is coming from the Kubernetes API when submitting the template, so the error message itself can’t be improved in Helm. However, there’s another ticket in the queue to do a schema check against the Kubernetes API prior to submission which would catch issues like using numerical values in a non-numeric context. I’m on my phone so I can’t find it right now but if you search for “schema validation” you should find the ticket :)

**Comment by lostllama** [comment]
OK, thank you. I'll search for that and subscribe.
