### ISSUE TITLE
Helm charts repo: stable not showing `traefik` possibly due to IsTruncated?

### ISSUE THREAD

**Issue by cdancy** [helm/helm#5057]
In trying to setup Artifactory to act as a proxy to your public charts repo I ran into an issue where Artifactory couldn't find the `traefik` chart. I thought that was odd and decided to go poking around the public repo [HERE](https://kubernetes-charts.storage.googleapis.com/) and noticed that indeed `traefik` is not listed. When I remove Artifactory from the picture, and attempt to use the public charts repo, the `traefik` chart is found just fine but I don't see as it's still not listed. Poking through the repo listing itself I see this xml snippet at the top:
```
<Name>kubernetes-charts</Name>
<Prefix/>
<Marker/>
<NextMarker>ghost-6.1.1.tgz</NextMarker>
<IsTruncated>true</IsTruncated>
```
Is there a parameter to pass on the URL path to get a non-truncated listing? Is there something obvious I'm missing here? 

Using the latest helm incase it matters but I think this _may_ be an environment related issue.

**Comment by mortent** [comment]
If you want to see the index for the chart repo, just download the `index.yaml` file:
```
curl https://kubernetes-charts.storage.googleapis.com/index.yaml --output index.yaml
```
You'll find many that many versions of traefik is available.

If you want to list the files in the gs bucket, it is easier to just use the `gsutil` command line tool
```
 gsutil ls gs://kubernetes-charts
```

**Comment by cdancy** [comment]
@mortent yeah I know all of that but it's for other processes outside of my control (e.g. Artifactory) that simply query that URL and are given a truncated list. If there were a URL parameter to pass to get the full list that would be perfect but it doesn't look like that's an option at the moment if I'm not mistaken.

**Comment by cdancy** [comment]
FWIW: Artifactory does not take the raw `index.yaml` file as a valid option and throws a `404` if you attempt to do so. It might be this is an issue on their side? IDK. Just seems weird there is no option to get the full list just by querying the UI.

**Comment by mortent** [comment]
I think I understand the problem now. So there is a `max_keys` parameter you can pass in to `https://kubernetes-charts.storage.googleapis.com` to specify the number of objects you want returned. It is described here: https://cloud.google.com/storage/docs/xml-api/get-bucket-list

Unfortunately the document also says _Cloud Storage does not return lists longer than 1,000 objects_. Passing in values larger than 1000 for `max_keys` still only results in 1000 objects returned. So looks like Artifactory would need to handle pagination for this to work.

**Comment by bacongobbler** [comment]
So if this is an artifactory-specific issue, there's nothing we can do here as this is a vendor's solution. I would follow up directly with JFrog on supporting pagination on Artifactory. Thanks!

**Comment by cdancy** [comment]
Thanks guys. Yup that's what I'm looking for. Now I can attempt to make this work or follow up with those guys. Thanks again.
