### ISSUE TITLE
Recreate Helm Template after made change directly in deployment 

### ISSUE THREAD

**Issue by AlexandrSemak** [helm/helm#5059]
We made some changes directly in our HPA in K8s bypassing NEW Helm Release because have to emergency response and increase number of replicas. After that developers resolve issue and we create NEW Helm Release but HPA.yaml was left without update, because Tiller look at previous Release and didn't see any changes but in K8s HPA don't matched with Helm Release.
I can handling it without making any changes in HPA for Helm Release or deleting???

**Comment by jascott1** [comment]
hi @AlexandrSemak 

It's difficult to know but I suggest replicating in another environment to determine the impact the various upgrade options will have on your particular deployment. You might also have the option of installing another deployment and routing traffic to it after you have tested it. The switch `--recreate-pods` should update but it will cause interruption in service afaik. Also consider the helm slack channel for production issues as there is a good chance someone has had the same issue.
