### ISSUE TITLE
Helm commands after Helm init try to connect to Kubernetes API on wrong port (443 instead of 6443)

### ISSUE THREAD

**Issue by SPayne262** [helm/helm#5064]
I have the same issue as described here: https://github.com/helm/helm/issues/3347 
Helm init seems to work, and the tiller service runs, but then all the helm commands fail, as they are trying to connect to wrong port. I'm using Flannel networking. 

 helm list
Error: Get https://10.96.0.1:443/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%!D(MISSING)TILLER: dial tcp 10.96.0.1:443: connect: no route to host

Output of `helm version`:
Client: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Installed on Centos 7 running as VMs on VMware ESXi

NAMESPACE     NAME                                       READY   STATUS    RESTARTS   AGE
default       nginx-5c7588df-4q28b                       1/1     Running   1          25h
kube-system   coredns-86c58d9df4-8j5zx                   1/1     Running   1          25h
kube-system   coredns-86c58d9df4-9w86v                   1/1     Running   1          25h
kube-system   etcd-devops1.frlab.us                      1/1     Running   1          25h
kube-system   kube-apiserver-devops1.frlab.us            1/1     Running   1          25h
kube-system   kube-controller-manager-devops1.frlab.us   1/1     Running   1          25h
kube-system   kube-flannel-ds-amd64-5h2t6                1/1     Running   1          25h
kube-system   kube-flannel-ds-amd64-k64dr                1/1     Running   2          25h
kube-system   kube-flannel-ds-amd64-r6xfq                1/1     Running   1          25h
kube-system   kube-proxy-2276n                           1/1     Running   1          25h
kube-system   kube-proxy-j8wdb                           1/1     Running   1          25h
kube-system   kube-proxy-rknqs                           1/1     Running   1          25h
kube-system   kube-scheduler-devops1.frlab.us            1/1     Running   1          25h
kube-system   tiller-deploy-c4fd4cd68-bzgrw              1/1     Running   0          33m

**Comment by jascott1** [comment]
Hi @SPayne262 

Can you check the address and port in `.kube/config` file?

**Comment by rabser** [comment]
I'm stuck at the same point after following the howto for Jupyter Hub installation: some hints ?
I believe that the IP/Port are the right ones, as from kubectl get svc:

NAME         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
kubernetes   ClusterIP   10.96.0.1       <none>        443/TCP        81m

but tiller can't contact the ClusterIP: it's a flannel configuration issue ?

**Comment by mosaicwang** [comment]
I meet the same question(k8s v1.13.2+flannel v0.10.0)

I found a solution : shutdown service firewalld,then re-execute `helm init `

**Comment by avarf** [comment]
I am facing this problem. I have a simple cluster with 1 master and 2 workers and I am using Calico. The IP and port are set correctly in `.kube/config` but tiller is using the wrong port of 443 instead of 6443 and while `kubectl` is working, helm commands don't work and I see this error in tiller logs (for `helm ls`):
```
[storage/driver] 2019/10/03 15:27:34 list: failed to list: Get https://10.5.0.1:443/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%3DTILLER: dial tcp 10.5.0.1:443: i/o timeout
```
Any solution?

**Comment by bacongobbler** [comment]
is `10.5.0.1:443` reachable?

What's the output of `kubectl cluster-info -v 5`?

**Comment by avarf** [comment]
```
kubectl cluster-info -v 5

Kubernetes master is running at https://10.4.86.150:6443
KubeDNS is running at https://10.4.86.150:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'
```
When I curl to http://10.5.0.1:6443 or http://10.5.0.1:443 from within one of the components curl just hangs:
```
curl -v http://10.5.0.1:6443
* Rebuilt URL to: http://10.5.0.1:6443/
*   Trying 10.5.0.1...
* TCP_NODELAY set
```

**Comment by avarf** [comment]
I found the problem. The IP of my master node is in the range that I was using for services (both started with `10.5`) and after I changed the range of services problem solved.

**Comment by lanez** [comment]
Hello @avarf - How did you changed the range of services? I having the same problem you had and I'm stuck on changing the range. Can you help me, please?

This is the error I'm getting:

[centos@ip-10-96-7-3 root]$ helm list
Error: Get https://10.96.0.1:443/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%!D(MISSING)TILLER: dial tcp 10.96.0.1:443: i/o timeout

[centos@ip-10-96-7-3 root]$ kubectl cluster-info -v 5
Kubernetes master is running at https://10.96.7.3:6443
KubeDNS is running at https://10.96.7.3:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

my Master IP is 10.96.7.3

Thank you!
