### ISSUE TITLE
Can't use values in template with ${}

### ISSUE THREAD

**Issue by yatanasov** [helm/helm#5068]
Output of `helm version`:

`Client: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}`

Output of `kubectl version`:

 v1.2

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
OpenShift

I have the following value in my values.yaml

`nodeExporterHost: '${1}:9100'
`
But when I deploy the template I see:

`1:9100`

How do I escape the removing of ${ } ?

Tried many ways without success..

**Comment by maorfr** [comment]
Can you share the relevant parts of your resource template and your values file?

**Comment by maorfr** [comment]
That is strange, I'm not able to reproduce.
Anyway, to escape any character, you can use:
```
{{ "<char>" }}
```
In your case, it seems that you need to escape the `{` and `}`, and not the `$`.
So I would try something like:
```
${{ "{" }}1{{ "}" }}:9100
```
Hope this helps!

**Comment by yatanasov** [comment]
Hi thanks for the suggestion!
 
One clarification - the single quotes should be preserved: '${1}:9100'

I tried what you suggested and other similar workaround without success.. 
`${{ "{" }}1{{ "}" }}:9100` results in  `{1{{ "}" }}:9100`
`'${{ "{" }}1{{ "}" }}:9100' ` results in ` {1{{ "}" }}:9100`
`{{ "'${1}:9100'" }}` results in  `error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{\\\"'1:9100'\\\":interface {}(nil)}\\n\"}","rootException":"java.lang.IllegalStateException",`

Any other options would be greatly appreciated! Thank you!

**Comment by avik-so** [comment]
@yatanasov Try 
nodeExporterHost:: "{{ "'${1}:9100'" }}"

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

**Comment by qudongfang** [comment]
@yatanasov Could you share how did you solve this issue? I ran into something similar.
