### ISSUE TITLE
Add flag `--output` to `helm inspect` command

### ISSUE THREAD

**Issue by SuperStevenZ** [helm/helm#5070]
Output of `helm version`: 
```
Client: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.9-gke.5", GitCommit:"d776b4deeb3655fa4b8f4e8e7e4651d00c5f4a98", GitTreeState:"clean", BuildDate:"2018-11-08T20:33:00Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
GKE
```

### Description
This is a kind request to follow up [this comment](https://github.com/helm/helm/issues/1534#issuecomment-396436584). 

I'd love to have `helm inspect` (`helm inspect values` and `helm inspect chart` possibly) take `--output` as a flag and accept `json` as a value, so it might be easier to parse the output in CLI. e.g.

```
helm inspect [CHART] --output json
```

Please close this issue if it's already included in other tickets or `--output` doesn't make sense for `helm inspect`. Thanks!

**Comment by bacongobbler** [comment]
closing as inactive.
