### ISSUE TITLE
Error: could not find a ready tiller pod & my tiller is ImagePullBackOff &Error: incompatible versions client[v2.12.0] server[v2.10.0]

### ISSUE THREAD

**Issue by Umryuan** [helm/helm#5071]
Output of `helm ls`:
Error: incompatible versions client[v2.12.0] server[v2.10.0]

Output of `helm version`:
Client: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
Error: could not find a ready tiller pod

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:59:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.5-tke.3", GitCommit:"53e244be925234190938376fe8637189b6caf125", GitTreeState:"clean", BuildDate:"2018-12-04T04:10:15Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Output of `kubectl -n kube-system get po`:
tiller-deploy-8449ccb84c-j4xqz      0/1       ImagePullBackOff   0          16h

OS version：
Ubuntu 16.04

hello,i'm new to k8s,this seems to be a simple problem,but i 've tried many ways from google and nothing works...

**Comment by bacongobbler** [comment]
What's the output of `kubectl -n kube-system describe po tiller-deploy-8449ccb84c-j4xqz`?

**Comment by Umryuan** [comment]
i don't know what happened but my tiller is running now,
and  output of kubectl -n kube-system describe po tiller-deploy-2269078230-66csq（it suddenly changed） is
Name:           tiller-deploy-2269078230-66csq
Namespace:      kube-system
Node:           10.0.4.10/10.0.4.10
Start Time:     Tue, 18 Dec 2018 10:05:32 +0800
Labels:         app=helm
                name=tiller
                pod-template-hash=2269078230
Annotations:    <none>
Status:         Running
IP:             172.16.6.74
Controlled By:  ReplicaSet/tiller-deploy-2269078230
Containers:
  tiller:
    Container ID:   docker://7c3c0adc2fb4a62fe7fddcbc61ccde9758e16ce350cb3b22eae81d94b58dd947
    Image:          ccr.ccs.tencentyun.com/cloudtrust/tiller:v2.10.0
    Image ID:       docker-pullable://ccr.ccs.tencentyun.com/cloudtrust/tiller@sha256:2a3dd484ecfcf9343994e0f6c2af0a6faf1af7f7e499905793643f91e90edcb3
    Port:           44134/TCP
    State:          Running
      Started:      Tue, 18 Dec 2018 10:05:33 +0800
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:44135/liveness delay=1s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:44135/readiness delay=1s timeout=1s period=10s #success=1 #failure=3
    Environment:
      TILLER_NAMESPACE:  kube-system
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-bfmx7 (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          True 
  PodScheduled   True 
Volumes:
  default-token-bfmx7:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-bfmx7
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     <none>
Events:
  Type    Reason                 Age   From                Message
  ----    ------                 ----  ----                -------
  Normal  Scheduled              40m   default-scheduler   Successfully assigned tiller-deploy-2269078230-66csq to 10.0.4.10
  Normal  SuccessfulMountVolume  40m   kubelet, 10.0.4.10  MountVolume.SetUp succeeded for volume "default-token-bfmx7"
  Normal  Pulled                 40m   kubelet, 10.0.4.10  Container image "ccr.ccs.tencentyun.com/cloudtrust/tiller:v2.10.0" already present on machine
  Normal  Created                40m   kubelet, 10.0.4.10  Created container
  Normal  Started                40m   kubelet, 10.0.4.10  Started container

**Comment by Umryuan** [comment]
└┤  kubectl -n kube-system get po
NAME                                READY     STATUS    RESTARTS   AGE
tiller-deploy-2269078230-66csq      1/1       Running   0          39m
my tiller is ok
now problem is this 
└┤ helm ls
Error: incompatible versions client[v2.12.0] server[v2.10.0]
i think my helm client version is too new

**Comment by bacongobbler** [comment]
Yes, your helm client is too new. You can upgrade tiller to v2.12.0 using `helm init --upgrade` with your v2.12.0 helm client.

**Comment by Umryuan** [comment]
`helm init --upgrade` didn't work as wish
cause i'm in china so i actually use
`helm init --upgrade -i registry.cn-hangzhou.aliyuncs.com/google_containers/tiller:v2.12.0 --stable-repo-url https://kubernetes.oss-cn-hangzhou.aliyuncs.com/charts
$HELM_HOME has been configured at /home/developer/.helm.
`
to upgrade my tiller
now `helm ls`works again ~
thank u for help : )

**Comment by Umryuan** [comment]
p.s.   i need a chinese image to upgrade tiller

**Comment by loganxavier** [comment]
Having the same error on a fresh machine, opened a question about [here](https://serverfault.com/questions/958912/helm-under-microk8s-giving-error-could-not-find-a-ready-tiller-pod).
