### ISSUE TITLE
commented out {{- if }} in templates still working

### ISSUE THREAD

**Issue by YoninL** [helm/helm#5073]
Output of `helm version`:
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

## How to reproduce:
```
test
├── Chart.yaml
└── templates
    └── test.yaml
```

test/Chart.yaml:
```
name: test
```
test/templates/test.yaml:
```
#{{- if eq .Values.foo "bar" }}
     foo: bar
#{{- else }}
#    foo: baz
#{{- end }}
```
`$ helm template test --set foo=bar`
```
---
# Source: test/templates/test.yaml
#
     foo: bar
#
```
`$ helm template test --set foo=sss`
```
---
# Source: test/templates/test.yaml
#
#    foo: baz
#
```

You can see even 'if' 'else' 'end' are commented out, they're still working when render the template based on different value input.

## What I expect:
Always output
```
     foo: bar
```

Am I using the wrong symbol (#) to comment out {{}}? Or it's a bug? I'm not sure.

**Comment by bacongobbler** [comment]
Helm's designed around accepting arbitrary input as a template's, running it through Go's `text/template` rendering engine and spitting out a template to be submitted to Kubernetes. What that means is YAML-style comments simply won't work with text/template. You need to use `text/template`'s comment system.

The correct form should be:

```yaml
{{/* {{- if eq .Values.foo "bar" }} */}}
```

Let me know if you have further questions.

**Comment by YoninL** [comment]
Thanks @bacongobbler for your quick response, {{/* */}} works fine.

test/templates/test.yaml:
```
{{/* {{- if eq .Values.foo "bar" }} */}}
     foo: bar
{{/* {{- else }} */}}
{{/*    foo: baz */}}
{{/* {{- end }} */}}
```

`$ helm template test --set foo=bar`
```
---
# Source: test/templates/test.yaml

     foo: bar
```

`$ helm template test --set foo=sss`
```
---
# Source: test/templates/test.yaml

     foo: bar
```
