### ISSUE TITLE
Proposal: Umbrella chart values per env

### ISSUE THREAD

**Issue by Olefine** [helm/helm#5076]
Hello! 

I have around 10 subcharts(and this number grows..) I'm using in one umbrella chart. Most of these charts has a pretty heavy values file(around 200lines per values file), and I'm dividing my values per env. So, for each chart I have 2 files: values-prod.yaml, values-qa.yaml

Until my SRE asked to create umbrella chart to manage all charts in one, everything was OK. I just deployed my chart and specified `-f values-{$ENV}.yaml`. For now, I need to manage my subcharts deployment under umbrella chart... and ta-da! I'm in trouble.

**Which solutions I could use?**
1) Put content of each values file from each chart to values file of umbrella chart.
2) when doing `helm dep up` to install/update umbrella's chart requirements, copy values-{qa/prod} to file values.yaml.

**Let's discuss each of the solution one by one...**

1) For me, helm chart is a kind of independent building block. If in future I will build new umbrella chart I will need to copy values from prev umbrella's chart values.. Also it's very hard to manage this file, because in my case I have .yaml file with 2000+ lines of code.. 

2) Everything is OK, except I have to write sh/gradlefile/makefile and force my SREs to learn new ways how to deploy k8s based software.

**What is proposal then?**
Ideally it would be great if we could pass `-f` option to `helm dep up` cmd. If this option specified chart will be packaged with chosen values file.(renamed if needed to values.yaml). Firstly I was thinking about adding extra key to requirements.yaml, but it seems like a pretty bad idea..

What do you think?

**Comment by maorfr** [comment]
Hey @Olefine,

I think this is a good idea, and I remember seeing this issue a couple of times in the past.

Until this issue is addressed, there are quite a few tools out there to help you with your situation:

https://github.com/roboll/helmfile
https://github.com/Praqma/helmsman
https://github.com/Eneco/landscaper
https://github.com/nuvo/orca

Hope this helps!

**Comment by bacongobbler** [comment]
closing as inactive.
