### ISSUE TITLE
config map overwritte by helm upgrade

### ISSUE THREAD

**Issue by meran** [helm/helm#5078]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
local installation using kubeadm

HI Have a question that I am wondering if anyone encountered already:
I am installing my charts using helm.
after the installation the deployments will be up and running for a long time.
during that time some of the deployments/config-maps might be changed manually for some reason.
after sometime the chart needs to be upgraded but those manually done chnages will be overwritten after that change. 
the deployments being overwritten is not a big deal for me but the config-map being overwritten creates some big issues for me.

is there a way to for helm not to overwrite those manually config-map changes

many thanks

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
