### ISSUE TITLE
helm upgrade failing because Ingress has wildcard DNS record

### ISSUE THREAD

**Issue by RATIKAdurgade** [helm/helm#5080]
I have EKS cluster running with wildcard DNS setup. I use umbrella charts where environments are separated by env-name.yaml file besides having values.yaml file at the top of the chart.
here is my ingress resource

```apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($http_x_forwarded_proto != 'https') {
        return 301 https://$host$request_uri;
      }
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  creationTimestamp: 2018-12-19T20:54:14Z
  generation: 2
  labels:
    app: nginx
    chart: nginx-0.1.1
    createdBy: helm
  name: nginx
  namespace: env-name
  resourceVersion: "1925687"
  selfLink: /apis/extensions/v1beta1/namespaces/env-name/ingresses/nginx
  uid: 3e99d187-03d0-11e9-b97b-0a7025b0ecae
spec:
  rules:
  - host: '*.XXX.YY.io'
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
  - host: XXX.webhooks.YY.io
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
status:
  loadBalancer:
    ingress:
    - {}
```
I want to upgrade my release (not updating ingress but updating backend service versions) with helm by following cmd 

```helm upgrade -f YY/values.yaml -f YY/config/env-name.yaml YY-subdomain YY --install --namespace=env-name --reuse-values --wait```

now my  env-name.yaml  is 

```
test-api:
  api:
    imageTag: 86.1d733fc
    replicas: 1
    resources:
      limits:
        cpu: 50m
        memory: 64Mi
nginx:
  canvasVersion: 11168.d614e5e
  hostname: '*.XXX.YY.io'
  nodePort: 30060
  webhooksHostname: XXX.webhooks.YY.io
```
I am getting error, I tried few escape characters as 

1. `hostname: \'\*.XXX.YY.io\'`
```Error: UPGRADE FAILED: Ingress.extensions "nginx" is invalid: spec.rules[0].host: Invalid value: "\\'\\*.XXX.YY.io\\'": a wildcard DNS-1123 subdomain must start with '*.', followed by a valid DNS subdomain, which must consist of lower case alphanumeric characters, '-' or '.' and end with an alphanumeric character (e.g. '*.example.com', regex used for validation is '\*\.[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')```

2. `hostname: '*.XXX.YY.io'`
```Error: UPGRADE FAILED: YAML parse error on YY/charts/nginx/templates/ingress.yaml: error converting YAML to JSON: yaml: line 17: did not find expected alphabetic or numeric character```

3. `hostname: \'*.XXX.YY.io\'`
```Error: UPGRADE FAILED: Ingress.extensions "nginx" is invalid: spec.rules[0].host: Invalid value: "\\'*.XXX.YY.io\\'": a wildcard DNS-1123 subdomain must start with '*.', followed by a valid DNS subdomain, which must consist of lower case alphanumeric characters, '-' or '.' and end with an alphanumeric character (e.g. '*.example.com', regex used for validation is '\*\.[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')```

Is there any way I can upgrade?

Output of `helm version`:

`Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}`

Output of `kubectl version`:

`Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-28T20:03:09Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.11-eks", GitCommit:"6bf27214b7e3e1e47dce27dcbd73ee1b27adadd0", GitTreeState:"clean", BuildDate:"2018-12-04T13:33:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS

**Comment by RATIKAdurgade** [comment]
@bacongobbler I found the workaround, this but is not practical. specify wildcard in upgrade command using `--set`
helm upgrade -f YY/values.yaml -f YY/config/env-name.yaml --set nginx.hostname=\'*.XXX.YY.io\' YY-subdomain YY --install --namespace=env-name --reuse-values --wait
I wish there if there any way I could avoid this as I am not able to automate is for multiple environments.

**Comment by anshudutta** [comment]
I am not sure why this is closed. This is a bug in helm client. The wildcard domains should be specified in yaml within quotes - '*.example.com'. But helm runs a regex validation that doesn't allow quotes.
```
Error: rpc error: code = Unknown desc = Ingress.extensions "grafana-oauth2-proxy" is invalid: spec.tls[0].hosts: Invalid value: "'*.alkmi.app'": a wildcard DNS-1123 subdomain must start with '*.', followed by a valid DNS subdomain, which must consist of lower case alphanumeric characters, '-' or '.' and end with an alphanumeric character (e.g. '*.example.com', regex used for validation is '\*\.[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```
I am using helm2 with terraform. This is a blocker. Can this be reopened.
