### ISSUE TITLE
Feature: Charts - Schema for values files

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#5081]
The goal of this to have schema files for `values.yaml` files. This can be used for validation and the generation of forms (e.g., web forms).

The details of this are in [the proposal](https://github.com/helm/community/blob/master/helm-v3/001-charts.md#schematized-values-files)

The implementation would likely leverage json schema. We would need a library to interact with the files. In addition to having them in a chart we should look to generate them from values files.

Any takers for this one?

**Comment by eladiw** [comment]
I will pick it up. talked with @mattfarina  about the details

**Comment by ian-howell** [comment]
@eladiw Are you still working on this one?

**Comment by ian-howell** [comment]
I'm going to go ahead and work on this one until someone tells me otherwise. My work so far is here [5350](https://github.com/helm/helm/pull/5350), although it's still very much a work in progress. I've been using the [specification](https://github.com/helm/community/blob/master/helm-v3/001-charts.md#schematized-values-files) as guidance.

**Comment by ian-howell** [comment]
The proposal mentions being able to generate a JSON schema from a given values file. However, Values are currently stored as `map[string]interface{}`, which means that the only information we can draw from a given property is its type. The types that we can determine are limited to what the [json  library's `Unmarshal`](https://golang.org/pkg/encoding/json/#Unmarshal) uses, which means no integers. Furthermore, if a property is `null`, there's no way to determine its type, and it must be omitted.

I've produced functionality for generating a schema in [this commit](https://github.com/helm/helm/commit/b3766e643085a8309aa21ec7c1a01da15655f565), but given the current limitations, the schemas it generates are very bare. In practice, a user could generate a schema, then modify it with more specific information. Is this the intention for this feature?

**Comment by bacongobbler** [comment]
> In practice, a user could generate a schema, then modify it with more specific information. Is this the intention for this feature?

Yep!
