### ISSUE TITLE
Feature: Plugins - enable platform (OS/arch) specific commands

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#5082]
This is documented in [the proposal](https://github.com/helm/community/blob/master/helm-v3/005-plugins.md#standard-plugins)

The gist is that this enables platform specific plugin commands (e.g., run one command on linux and a different one on Windows).

Whose interested in taking this on?

**Comment by hickeyma** [comment]
I can help with this

**Comment by hickeyma** [comment]
PR merged. Issue can be closed.
