### ISSUE TITLE
Feature: Add library charts

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#5085]
The gist of this is in [the v3 proposal](https://github.com/helm/community/blob/master/helm-v3/001-charts.md#library-charts)

Note, the proposal refers to `requirements.yaml` files. Those files have now been merged into `Chart.yaml` files.

The gist is that library charts, that follow the idea of the [common chart](https://github.com/helm/charts/tree/master/incubator/common), can be used to share and re-use functionality. Library charts are not installable.

**Comment by hickeyma** [comment]
I can pick this up.

**Comment by hickeyma** [comment]
Currently a WIP ..

**Comment by hickeyma** [comment]
@mattfarina In progress. Breaking up into partial PRs per functionality as will be more manageable.

**Comment by hickeyma** [comment]
@mattfarina @prydonius I had a chat yesterday evening with @adamreese about this feature. Following review of the PRs and discussion with other maintainers, @adamreese thinks that this feature can be simplified down as follows: just check during installation if it is a library chart and don't install with a relevant warning message.  The chart can be identified with a property in the metadata. The library charts can be included in the same way as other dependencies and no needs for the distinction when referencing the chart (i.e. `libraries` section and `library/`).
Let me know what your thoughts are.

**Comment by mattfarina** [comment]
@hickeyma I'm reminded a bit of [Composer](https://getcomposer.org/), the package manager for PHP. What people typically do with composer is reference a library that you can lookup in [Packagist](https://packagist.org/), a metadata lookup for distributed repos. While libraries are common, other things can and are distributed.

To make this work there is a `type` field in the `composer.json`, the sister file to our `Chart.yaml` file. You can read about `type` [here](https://getcomposer.org/doc/04-schema.md#type).

I would suggest we try the following:
* Add a `type` field to the `Chart.yaml` with a default of `application` if not present. A second possible value is `library`.
* If someone tries to `helm install` a library chart we don't install it and provide an error letting them know it's a library and not meant to be installed.
* When a library chart is added as a dependency it is not installed. Instead, its assets are made available for the parent chart to use. IIRC, this works today and you can see it in the [common chart](https://github.com/helm/charts/tree/master/incubator/common).

This may serve as a light way to start with libraries.

**Comment by hickeyma** [comment]
@mattfarina Sounds good to me. Will push a new PR for this approach.

**Comment by hickeyma** [comment]
Closed PR #5255 and #5263 following discussion in https://github.com/helm/helm/issues/5085#issuecomment-462385310

PR #5295 opened instead and ready for review.

**Comment by hickeyma** [comment]
@mattfarina PR #5295 now merged. This feature can be closed.

**Comment by prydonius** [comment]
> * IIRC, this works today and you can see it in the [common chart](https://github.com/helm/charts/tree/master/incubator/common).

Just FYI, this only works with the common chart today because it doesn't actually produce any output and only defines Go template blocks for the parent chart to use. I imagine most library charts will follow this approach and not output their own templates, so this should be okay, but it might also make sense to ensure it by skipping any template generated in a library chart.
