### ISSUE TITLE
Error: forwarding ports: error upgrading connection: Upgrade request required

### ISSUE THREAD

**Issue by nagapavan** [helm/helm#5089]
Output of `helm version`: 
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Error: forwarding ports: error upgrading connection: Upgrade request required

Output of `kubectl version`: 1.9.3

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  non-cloud installation

I am new to `helm`. Till now we are using Python K8S client to do remote deployments. We are in process to switch to `helm` way for fully automated CI/CD.  

We have a custom configured K8S, not cloud managed. I am trying to deploy to K8S cluster using `helm`, through Jenkins job.

Command used to deploy:
```bash
helm upgrade --install --namespace services service ./deploy/helm --kubeconfig=./deploy/kube-config --set-string env_name=test,image.repository=${imageName},image.tag=${imageTagName} --debug
```

**Output:**
> Error: forwarding ports: error upgrading connection: Upgrade request required

**Expected output:**
Deploy to happen successfully.

**Steps used to install `helm`:**
```bash
HELM_URL=https://storage.googleapis.com/kubernetes-helm && \
	HELM_TARBALL=helm-v2.11.0-linux-amd64.tar.gz && \
	curl -O $HELM_URL/$HELM_TARBALL && \
	tar xzfv $HELM_TARBALL && rm $HELM_TARBALL && \
	mv linux-amd64/helm /usr/local/bin/helm && \
	# export PATH=usr/bin/linux-amd64/:$PATH && \
	helm init --client-only
```

Have tried replacing with a ELB URL in place of IP address on Kube config. Result is same.

K8S config has been copied from Kuberenetes master node. The same config works with Python client, without a problem. This seems to be a problem with Helm or Tiller.

Any help would be much appreciated.

I have verified other `upgrading connection` issues. They are related to pod connect timeouts and not related to Upgrade request required` issue.

**Comment by maorfr** [comment]
Hey @nagapavan,

If I am not missing anything, it looks like you are missing the Tiller installation.
Read this for more information: https://docs.helm.sh/using_helm/#installing-tiller

Hope this helps!

**Comment by bacongobbler** [comment]
yep; based on the steps provided, `helm init --client-only` was called, but I don't see any tiller instance that was installed. The `--client-only` flag skips installing tiller in your cluster.

I'm going to close this as resolved, but please feel free to re-open if necessary. Thanks!

**Comment by dunefro** [comment]
@bacongobbler  I am facing the similar issue when I am doing helm version
`root@k8s:~# helm version
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Error: forwarding ports: error upgrading connection: Upgrade request required
`
In my case Tiller is already installed and is running fine
`root@k8s:~# kubectl get pods --all-namespaces
NAMESPACE     NAME                                                       READY   STATUS    RESTARTS   AGE
default       nginx-ingress-controller-controller-66889df977-k82gl       1/1     Running   0          2d23h
default       nginx-ingress-controller-default-backend-7df66f64f-2pdqv   1/1     Running   0          2d23h
kube-system   coredns-5c98db65d4-bnxss                                   1/1     Running   0          3d1h
kube-system   coredns-5c98db65d4-bwsh4                                   1/1     Running   0          3d1h
kube-system   etcd-ey-sygmoid-ubu-005                                    1/1     Running   0          3d1h
kube-system   kube-apiserver-ey-sygmoid-ubu-005                          1/1     Running   0          3d1h
kube-system   kube-controller-manager-ey-sygmoid-ubu-005                 1/1     Running   1          3d1h
kube-system   kube-flannel-ds-amd64-z8bwh                                1/1     Running   0          3d1h
kube-system   kube-proxy-xvwbk                                           1/1     Running   0          3d1h
kube-system   kube-scheduler-ey-sygmoid-ubu-005                          1/1     Running   2          3d1h
kube-system   tiller-deploy-8557598fbc-qpdlq                             1/1     Running   0          3d
`

I am new to helm charts so I was directly given the cluster to deploy some applications using helm charts. 
I am currently working on 
`Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco
`
The k8s version is
`root@k8s:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
`
