### ISSUE TITLE
Lists concatenattion

### ISSUE THREAD

**Issue by astorath** [helm/helm#5096]
Hi, how can I join (concatenate) two lists in helm templates? I've found no option in sprig or go templates libs...

**Comment by bacongobbler** [comment]
You can append items to a list, but I don't think there's a way to merge two lists together. That would be a great feature to propose to [sprig](https://github.com/Masterminds/sprig), though!

**Comment by bacongobbler** [comment]
closing as inactive.

**Comment by jakuboskera** [comment]
use `concat`
https://helm.sh/docs/chart_template_guide/function_list/#concat
