### ISSUE TITLE
Error: configmaps is forbidden: User "system:serviceaccount:kube-system:default" cannot list resource "configmaps" in API group "" in the namespace "kube-system"

### ISSUE THREAD

**Issue by a1exus** [helm/helm#5100]
I'm trying to follow [INSTALLING TILLER](https://docs.helm.sh/using_helm/#installing-tiller), yet running into following error:

```
$ helm list
Error: configmaps is forbidden: User "system:serviceaccount:kube-system:default" cannot list resource "configmaps" in API group "" in the namespace "kube-system"
$
```

Output of `helm version`:

```
$ helm version
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
$ 
```

Output of `kubectl version`:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
$ 
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

bare metal, linux

possibly related, I'm also trying to access [Tiller and Role-Based Access Control](https://docs.helm.sh/using_helm/rbac), yet getting 404.

**Comment by varatep** [comment]
New URL for anyone looking: https://helm.sh/docs/rbac/#role-based-access-control

**Comment by m-abramovich** [comment]
> Error: configmaps is forbidden: User "system:serviceaccount:kube-system:default" cannot list

This message says that your tiller acts as "kube-system:default" service account which most likely does not have any sufficient role binding.

What to do:
- check if you have specific **account** for tiller:
`kubectl get serviceaccount [-n kube-system]`
create if not: 
`kubectl create serviceaccount -n kube-system tiller`
- check if you have role or **clusterrole** binding (cluster role is "better" for newbies). If this is not production, you can use highly privileged role "cluster-admin":
`kubectl get clusterrole -n kube-system`
you can check role content via: 
`kubectl get clusterrole cluster-admin -o yaml -n kube-system`
- check if **account** in first clause has a binding to **clusterrole** that you deem sufficient:
`kubectl get clusterrolebinding [-n kube-system]`
if it is hard to figure out based on names, you can simply create new:
`kubectl create clusterrolebinding tiller-cluster-admin --clusterrole=cluster-admin --serviceaccount=kube-system:tiller`
- finally, when you have account, role and binding between them, you can check if you really act as this this account:
`kubectl --namespace kube-system get deploy tiller-deploy -o yaml`

Part of the output most likely will be:
```
dnsPolicy: ClusterFirst
restartPolicy: Always
schedulerName: default-scheduler
securityContext: {}
terminationGracePeriodSeconds: 30
```
if yes, than add account you want tiller to use:
`kubectl --namespace kube-system patch deploy tiller-deploy -p '{"spec":{"template":{"spec":{"serviceAccount":"tiller"}}}}'`
Now you repeat previous check command and see the difference:
```
dnsPolicy: ClusterFirst
restartPolicy: Always
schedulerName: default-scheduler
securityContext: {}
serviceAccount: tiller   <-- new line
serviceAccountName: tiller   <-- new line
terminationGracePeriodSeconds: 30
```

**Comment by snpdev** [comment]
@m-abramovich solution worked for me. 

Note: if using Powershell, the command is:
```
kubectl --namespace kube-system patch deploy tiller-deploy -p '{\"spec\":{\"template\":{\"spec\":{\"serviceAccount\":\"tiller\"}}}}'
```

**Comment by iamaverrick** [comment]
and 2 moths and 1/2 your explanation is still being helpful thank you very much for taking the time out of your busy schedule to be detailed and helpful. @m-abramovich  unlike @bacongobbler

**Comment by marckhouzam** [comment]
> and 2 moths and 1/2 your explanation is still being helpful thank you very much for taking the time out of your busy schedule to be detailed and helpful. @m-abramovich unlike @bacongobbler

The person who closed this issue was the person who opened it. Clearly they felt the issue was resolved.  

Furthermore, the original description asked for the proper link to the  role-based access control documentation, which was provided without closing the issue.

Finally, @bacongobbler took the time to provide the requested information on December 25th, which for many is an important holiday.  I'm sorry @iamaverrick but I find your comment quite inappropriate.

**Comment by bacongobbler** [comment]
Wow. I don't even remember answering to this thread... Been a while.

@marckhouzam's assumption here is correct: the issue was opened on Christmas Day. I happened to be with my family that day, but I saw this quick question from the OP:

> possibly related, I'm also trying to access [Tiller and Role-Based Access Control](https://docs.helm.sh/using_helm/rbac), yet getting 404.

So I figured I'd shoot a quick answer with the correct link and get back celebrating Christmas. The next day, the OP closed the issue, so I assumed no further follow-up was required.

It really upsets me to think my comment was assumed as being terse or unhelpful. I wasn't trying to solve the issue; I was merely providing context while the OP tries to find the solution themselves over the holiday season.

Thank you @m-abramovich and @snpdev for following up and providing answers to OP's issue.

**Comment by hickeyma** [comment]
@iamaverrick To provide a link to documentation is not uncommon when responding to an issue. This is not being unhelpful but a belief in our documentation which we as a community invest a lot of time on. if the documentation is inadequate then the person usually responds and this then give the responder the opportunity to provide more context. It also makes us aware that the doc needs improvement. Without interaction or feedback like this from users, the docs will not improve.

In the long run better documentation helps people more than having to raise issues for non related bugs or features.

On another level, for @bacongobbler to respond during the holiday season at all is quite impressive. Remember we are all people trying to do our best.

**Comment by m-abramovich** [comment]
Guys, please take it easy. 
We're all software developers, share same values in life. We have much more in common that you even can think about. Let's respect each other please.

**Comment by iamaverrick** [comment]
@marckhouzam  inappropriate ? In no shape or form have I disrespected anybody with my comment. I simply stated the facts from my perspective. This comment was directly mentioned @bacongobbler not everybody else who put in there 2 cents. I appreciate @bacongobbler for pasting the link on a holiday.      The original question states he was having issues and needed guidance not a link. Guys if you can’t take constructive criticism then don’t post anything on these threads. We are all software developers trying to become better and provide better information.

**Comment by a1exus** [comment]
I apologize for not proving my answer with greater details as I sort of hinted the answer in my question and then @bacongobbler confirmed my answer, followed by great comment by @m-abramovich 

I really do appreciate everyone's help and/or input and I will try to do better job next time, I promise!

**Comment by pohly** [comment]
My two cents: when following https://helm.sh/docs/intro/quickstart/, there's no mention of RBAC and the instructions there lead to a non-working installation of tiller. A google search then leads to this issue here.

Perhaps it can be reopened as "enhance quickstart guide so that it warns newbies about this pitfall"?

**Comment by pohly** [comment]
There is "Deciding what security configurations to apply to your installation, if any" under prerequisites, but as I was just trying it out on a throwaway cluster, the "if any" implied to me that as I don't care, I don't need to do anything.

Even if I had noticed that I need to do something, there's no link to instructions.

**Comment by m-abramovich** [comment]
> My two cents: when following https://helm.sh/docs/intro/quickstart/, there's no mention of RBAC and the instructions there lead to a non-working installation of tiller. A google search then leads to this issue here.
> 
> Perhaps it can be reopened as "enhance quickstart guide so that it warns newbies about this pitfall"?

@pohly 
Patrick, I believe this is not relevant anymore. 
Helm v3 doesn't use Tiller. So, maybe, all that is worthless now.

**Comment by jragland-cerity** [comment]
@m-abramovich  Thank you! Your detailed walk through helped me get through this issue. I very much appreciate the time you took to write your response up.

**Comment by ivan-caspeta-by** [comment]
This explanation is great! Thanks!

**Comment by jmdoman** [comment]
Hello, 
I'm also having this issue. my helm version: 
Client: &version.Version{SemVer:"v2.15.2", GitCommit:"8dce272473e5f2a7bf58ce79bb5c3691db54c96b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.0+unreleased", GitCommit:"9668ad4d90c5e95bd520e58e7387607be6b63bb6", GitTreeState:"dirty"}
I followed all the steps m-abramovich listed above, and my problem still remains exactly the same. 
when I run kubectl --namespace kube-system get deploy tiller-deploy -o yaml this is the result:
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2022-08-12T14:16:52Z"
  generation: 2
  labels:
    app: helm
    name: tiller
  name: tiller-deploy
  namespace: kube-system
  resourceVersion: "81969"
  uid: 051cbf6d-ed72-42b9-aab3-bdec7e218074
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: helm
      name: tiller
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: helm
        name: tiller
    spec:
      automountServiceAccountToken: true
      containers:
      - env:
        - name: TILLER_NAMESPACE
          value: kube-system
        - name: TILLER_HISTORY_MAX
          value: "0"
        image: gcr.io/kubernetes-helm/tiller:v2.15.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /liveness
            port: 44135
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: tiller
        ports:
        - containerPort: 44134
          name: tiller
          protocol: TCP
        - containerPort: 44135
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readiness
            port: 44135
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: tiller
      serviceAccountName: tiller
      terminationGracePeriodSeconds: 30
      
Is there something I'm missing?
