### ISSUE TITLE
Is there any `helm repo cleanup` -like command to cleanup/delete useless packages in helm repo?

### ISSUE THREAD

**Issue by yangsongx** [helm/helm#5104]
Output of `helm version`: 2.11 

Output of `kubectl version`: 1.22

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

We setup AWS s3 as helm repo storage, everything works fine and cool.

But, after a long time development, we definitely had many many older packages(*.tgz) in both local machine and remote S3. I think it's not safe to directly use `rm *.tgz` to remove these older packages, as there're mapping info stored in the `index.yaml` file.

Is there any formal way to cleanup/delete these older *.tgz files(and remove them from `index.yaml` accordingly)? I knew `helm delete` is actually delete deployment in K8S,  I want to delete some older packages in helm repo. But I failed to find any useful info in the helm doc.

**Comment by bacongobbler** [comment]
I don't believe there is a cleanup command for `helm repo`. ChartMuseum does have that functionality though!

https://github.com/helm/chartmuseum#chart-manipulation

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

**Comment by Dentrax** [comment]
I'd be better to have a `repo purge` or something like that to clean up all the (dangling) repositories. Looking for a simple command to that.

> ChartMuseum does have that functionality though!

Unfortunately, I'm working on my local so didn't use `ChartMuseum` before.
