### ISSUE TITLE
Helm does not work properly with --wait flag and Pods completed below 2s

### ISSUE THREAD

**Issue by mszostok** [helm/helm#5106]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"10ecc6db83fd47a93eb0940e2e4434f2b0a5c3ec", GitTreeState:"clean", BuildDate:"2018-08-15T21:23:47Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
*not-related*

**Description**

When we installing/updating the Helm chart with **--wait** flag and this chart contains the Pods definition and those Pods are completed very quickly (below 2s) then installation is timeouted. 
It happens when Pods restart policy is set to **Never** and Pod finishing they job below 2s, so poll logic missed the Ready state and we had to wait until the installation timeout.

source code: https://github.com/helm/helm/blob/v2.12.1/pkg/kube/wait.go#L52

We cannot use the Job kind because the Helm `wait` functionality support waiting for them only on hooks.

The possible solution is to use the "Hollywood Principle – Don't Call Us, We'll Call You", and rewrite the wait logic to use Informers instead of polling logic.

**Expected result**

Helm handles correctly waiting for Kubernetes resources. 

**Actual result**

When flag **--wait** is specified then Helm timeouts the installation when release contains Pod which is finished very fast (below 2s).

**Comment by bacongobbler** [comment]
closing as inactive.
