### ISSUE TITLE
helm cannot find releases

### ISSUE THREAD

**Issue by abergmeier** [helm/helm#5107]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1+a0ce1bc657", GitCommit:"a0ce1bc", GitTreeState:"clean", BuildDate:"2018-09-08T02:14:55Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
_OpenShift 3.9_

When executing `helm install --replace --name activemq chart`, I get the error message:
```
NAME:   activemq
Error: getting deployed release "activemq": release: "activemq" not found
```

Same is true for all other charts.
In OpenShift, the deployment nevertheless runs fine.

**Comment by abergmeier** [comment]
> Is there a release called activemq when you do a helm list

No there is no such release.
It deploys to Kubernetes not matter whether there is a _activemq_ release or not.

**Comment by michelleN** [comment]
@abergmeier Just to clarify, you ran a `helm install --name activemq` and the kubernetes objects were created but the release was not, correct? and then you did a `helm install --replace --name activemq` and that gave an error because the release was not created?
Let me know if I am getting that correct. Is there are a config map in the `kube-system` namespace that looks like: `activemq.v1`?

I see that you're on Kubernetes 1.9 and using helm v2.12.1. I wonder if this is an issue with using a newer helm/tiller version with an older Kubernetes cluster.

**Comment by kaisawind** [comment]
I find the error from the tiller's log, but I don't know why it can't throw an error from the console.
I forgot to add / in the .helmignore file, when ignore the folder.
Maybe this can help others.

`.git` -> `.git/`

Error from console
```shell
[master@master ]$ helm install . --namespace=iot
NAME:   listless-lambkin
Error: getting deployed release "listless-lambkin": release: "listless-lambkin" not found
```

tiller log
```log
[storage] 2019/03/29 02:32:46 getting release "listless-lambkin.v1"
[tiller] 2019/03/29 02:32:46 rendering bigscreen chart using values
[tiller] 2019/03/29 02:32:46 performing install for 
[tiller] 2019/03/29 02:32:46 executing 0 crd-install hooks for listless-lambkin
[tiller] 2019/03/29 02:32:46 hooks complete for crd-install listless-lambkin
[tiller] 2019/03/29 02:32:46 executing 0 pre-install hooks for listless-lambkin
[tiller] 2019/03/29 02:32:46 hooks complete for pre-install listless-lambkin
[storage] 2019/03/29 02:32:46 getting release history for ""
[storage] 2019/03/29 02:32:46 creating release "listless-lambkin.v1"
[storage/driver] 2019/03/29 02:32:47 create: failed to create: ConfigMap "listless-lambkin.v1" is invalid: []: Too long: must have at most 1048576 characters
[tiller] 2019/03/29 02:32:47 warning: Failed to record release listless-lambkin: ConfigMap "listless-lambkin.v1" is invalid: []: Too long: must have at most 1048576 characters
```

**Comment by huguesalary** [comment]
If you're running into this issue, simply look at your helm chart folder and check that you do not have any heavy binary file laying around.

Helm upload everything in the chart directory and it will fail with this error if there's a file of more than a few megabytes.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
