### ISSUE TITLE
Retrieve a value from subchart

### ISSUE THREAD

**Issue by kferrone** [helm/helm#5108]
I have a chart with some subcharts, kind of like below:

```
- mychart
-- values.yaml (global one)
-- charts
--- backend
---- values.yaml (this is where the port is set to a default)
--- frontend
```

The frontend chart has a container with an environment variable to point to backend URL. In the frontend chart I am trying to get the port I provided to the backend. 

I tried like below in the frontend and it does not work, says the var is basically undefined. 

```
{{ .Values.backend.service.port }}
```

Even if I put the following in the global values, still no luck:

```
backend:
    service:
        port: 8080
```

I do know if put the value in the globals like below, I would definitely get my intended result:

```
global:
    backend:
        service:
            port: 8080
```

However, I don't really want it in the globals, if I could have my way. Is there another way to get another charts values? Or is globals the only way to go?

**Comment by michelleN** [comment]
@kferrone you may want to look at importing/exporting values like it's described [here](https://github.com/helm/helm/blob/master/docs/charts.md#importing-child-values-via-requirementsyaml)

**Comment by kferrone** [comment]
whoa. . . Just what was looking for. I'm thinkin how'd I miss that section.

**Comment by davestephens** [comment]
Probably because you did what I did and googled "helm dependency" and found [this page](https://github.com/helm/helm/blob/master/docs/helm/helm_dependency.md), where there's no mention of it :)

**Comment by SavePointSam** [comment]
For anyone looking for this information now, it's been moved to [here](https://helm.sh/docs/topics/charts/#importing-child-values-via-dependencies).
