### ISSUE TITLE
version `v2.11.0` doesn't support `condition` for chart `requirements.yaml`

### ISSUE THREAD

**Issue by zzxwill** [helm/helm#5113]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:29:25Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
Docker CE 18.06.1-ce-mac73 (26764)
```

BTW, version `v2.2.2` worked.

**Comment by bacongobbler** [comment]
Did you mean to say 2.12.0?

**Comment by zzxwill** [comment]
> Did you mean to say 2.12.0 instead of 2.2.2?

No, I mean `v2.2.2`.

**Comment by bacongobbler** [comment]
Can you please provide an example chart that doesn’t work?

**Comment by michelleN** [comment]
Hey @zzxwill - could you give us some details on how to reproduce this issue. I was unable to reproduce this issue.

These are the steps that I took:
1. Added a requirements.yaml file with a condition specified in the [conditions section of the docs](https://github.com/helm/helm/blob/master/docs/charts.md#tags-and-condition-fields-in-requirementsyaml) to a simple chart with a key that evaluates to false in the values.yaml file

2. ran `$ helm dep up` to get the dependency in the `charts/`

3. ran `$ helm install mychart/ -n example` and I did not see the dependency be installed because the condition evaluated to false in the values.yaml

4. Then I ran `$helm install mychart/ -n example2 --set subchart.enabled=true` to make sure the condition field as expected and my dependency was installed along with the parent chart as expected.

Please let us know if there are different steps we should follow to reproduce the issue you're seeing.
Thank you.

**Comment by zzxwill** [comment]
> Hey @zzxwill - could you give us some details on how to reproduce this issue. I was unable to reproduce this issue.
> 
> These are the steps that I took:
> 
> 1. Added a requirements.yaml file with a condition specified in the [conditions section of the docs](https://github.com/helm/helm/blob/master/docs/charts.md#tags-and-condition-fields-in-requirementsyaml) to a simple chart with a key that evaluates to false in the values.yaml file
> 2. ran `$ helm dep up` to get the dependency in the `charts/`
> 3. ran `$ helm install mychart/ -n example` and I did not see the dependency be installed because the condition evaluated to false in the values.yaml
> 4. Then I ran `$helm install mychart/ -n example2 --set subchart.enabled=true` to make sure the condition field as expected and my dependency was installed along with the parent chart as expected.
> 
> Please let us know if there are different steps we should follow to reproduce the issue you're seeing.
> Thank you.

In `step 4`, changed `subchart.enabled` to be `false`.
1. version v2.2.2 worked.
```
/Users/zhouzhengxi/Downloads/darwin-amd64/helm version
Client: &version.Version{SemVer:"v2.2.2", GitCommit:"1b330722aafcb8123114ae51f69d1e884a326f3e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

✗ /Users/zhouzhengxi/Downloads/darwin-amd64/helm install . --dry-run --debug --set mysqlha.enabled=false
Created tunnel using local port: '61188'
SERVER: "localhost:61188"
CHART PATH: /Users/zhouzhengxi/Programming/github/zzxwill/charts/stable/tomcat
Warning: mysqlha is in requirements.yaml but not in the charts/ directory!
NAME:   vetoed-hare
REVISION: 1
RELEASED: Wed Jan  9 14:43:26 2019
CHART: tomcat-0.1.0
USER-SUPPLIED VALUES:
mysqlha:
  enabled: false

COMPUTED VALUES:
affinity: {}
deploy:
  directory: /usr/local/tomcat/webapps
image:
  pullPolicy: IfNotPresent
  tomcat:
    repository: tomcat
    tag: "7.0"
  webarchive:
    repository: ananwaresystems/webarchive
    tag: "1.0"
ingress:
  annotations: {}
  enabled: false
  hosts:
  - chart-example.local
  path: /
  tls: []
mysqlha:
  enabled: false
nodeSelector: {}
replicaCount: 1
resources: {}
service:
  externalPort: 80
  internalPort: 8080
  name: http
  type: LoadBalancer
tolerations: []

HOOKS:
MANIFEST:

---
# Source: tomcat/templates/appsrv-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: vetoed-hare-tomcat
  labels:
    app: tomcat
    chart: tomcat-0.1.0
    release: vetoed-hare
    heritage: Tiller
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: tomcat
    release: vetoed-hare
---
# Source: tomcat/templates/appsrv.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: vetoed-hare-tomcat
  labels:
    app: tomcat
    chart: tomcat-0.1.0
    release: vetoed-hare
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
      release: vetoed-hare
  template:
    metadata:
      labels:
        app: tomcat
        release: vetoed-hare
    spec:
      volumes:
        - name: app-volume
          emptyDir: {}
      containers:
        - name: war
          image: ananwaresystems/webarchive:1.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: app-volume
              mountPath: /app
        - name: tomcat
          image: tomcat:7.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: app-volume
              mountPath: /usr/local/tomcat/webapps
          ports:
            - containerPort: 8080
              hostPort: 8009
          livenessProbe:
            exec:
              command:
              - cat
              - /usr/local/tomcat/webapps/sample/index.html
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {}

```
2. version v2.10.0 didn't work.
```
✗ helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

✗ helm install . --dry-run --debug --set mysqlha.enabled=false
[debug] Created tunnel using local port: '61013'

[debug] SERVER: "127.0.0.1:61013"

[debug] Original chart version: ""
[debug] CHART PATH: /Users/zhouzhengxi/Programming/github/zzxwill/charts/stable/tomcat

Error: found in requirements.yaml, but missing in charts/ directory: mysqlha
```

**Comment by heptahedron** [comment]
We are also running into this issue with `v2.12.2`. After running `helm dep up`, the `condition` field from the `requirements.yaml` is not present in `requirements.lock`. Can provide instructions to reproduce the issue in a bit

**Comment by bacongobbler** [comment]
closing as inactive.
