### ISSUE TITLE
hooks are ignored when running helm install --wait

### ISSUE THREAD

**Issue by danielezer** [helm/helm#5118]
Output of `helm version`:
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:19Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.9-gke.5", GitCommit:"d776b4deeb3655fa4b8f4e8e7e4651d00c5f4a98", GitTreeState:"clean", BuildDate:"2018-11-08T20:33:00Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

When running helm install --wait for any chart, any hooks defined in the are not created. For example a hook that creates a job doesn't create the job and doesn't create the pod that needs to run. When I remove --wait and run a new helm install without the --wait, the job is created and hook does run.

**Comment by michelleN** [comment]
Thanks for reporting this @danielezer. I'm going to try to reproduce this issue now.

**Comment by michelleN** [comment]
@danielezer I was unable to reproduce this bug using the kubernetes/helm versions provided. For additional context, I tested using the [example nginx chart](https://github.com/helm/helm/tree/master/docs/examples/nginx) in our docs that contains a post-install hook. Would you mind providing some additional context on how to reproduce this issue?

**Comment by danielezer** [comment]
@michelleN it happened to when I tried to install the jfrog/mission-control chart. There's a hook there for creating mongo users and when I ran helm install --wait the hook wasn't created and when I ran helm install without --wait it was created. I was able to reproduce that behaviour multiple times with that chart, to be honest, I didn't try with any other charts but I didn't see anything unusual with the jfrog/mission-control chart so it seemed to me that its a helm issue

**Comment by danielezer** [comment]
@michelleN 
here is how it looks like for me:
![image](https://user-images.githubusercontent.com/32907193/50629273-87ad8700-0f44-11e9-828b-802d226c8be4.png)

this is what I see without --wait, the mission-control-test-create-user-7f649 hook job is created and running
![image](https://user-images.githubusercontent.com/32907193/50629297-a449bf00-0f44-11e9-887f-31aa51d4e739.png)

When I add the --wait flag, the hook job is not created:
![image](https://user-images.githubusercontent.com/32907193/50629367-e96df100-0f44-11e9-8033-cbd1e7be77cc.png)

This is what I see: 
![image](https://user-images.githubusercontent.com/32907193/50629381-f854a380-0f44-11e9-9a88-c1d84be41639.png)


As you can see, the create-user hook job is not created and there's no pod running with that name

**Comment by asaintsever** [comment]
Hi there.
I can repro this issue using helm 2.12.3.

Define one post-install hook where you generate a secret.
Define one deployment manifest where you mount the secret (created by the post-install hook)

Then run `helm install <your chart> --debug --wait` and you will notice that:

- the deployment is loaded into the cluster but not ready as it is waiting for the secret to be here
- helm waits... and fails when timeout has been reached
- post-install hook is never run (and so deployment cannot be ready)

Try same command without `--wait` flag and deployment will be successful.

In my opinion, this is an issue as post-install hooks should be run before entering the wait loop.

**Comment by danielezer** [comment]
Just figured out what the issue is. 
According to the helm documentation:
`Tiller loads the resulting resources into Kubernetes. Note that if the --wait flag is set, Tiller will wait until all resources are in a ready state and will not run the post-install hook until they are ready.`

Closing this issue
