### ISSUE TITLE
add doc around what environment variables we support for configuring helm/tiller

### ISSUE THREAD

**Issue by michelleN** [helm/helm#5121]
I don't remember if there is a doc like this we support. I remember just going through the code to figure this out every time. If we don't already have a doc, we may want to consider adding one.

**Comment by bacongobbler** [comment]
Should be an easy amendment to https://github.com/helm/helm/blob/c82c0b6046b852f449dcaae768ba57331116dc87/cmd/helm/helm.go#L63-L75 if someone wants to take a crack at it.

**Comment by whereisaaron** [comment]
Added PR #5123 to document the HELM_TLS_HOSTNAME environment variable.

**Comment by gordcorp** [comment]
I was just trying to run tiller locally, [restricted to deploy against a specific namespace](https://docs.helm.sh/using_helm/#example-deploy-tiller-in-a-namespace-restricted-to-deploying-resources-only-in-that-namespace), and it took me a little while to realise that `TILLER_NAMESPACE` was also necessary for tiller in this situation, despite not appearing in `tiller --help` - maybe env vars like that could also be documented in tiller help?

**Comment by bacongobbler** [comment]
closing as inactive.
