### ISSUE TITLE
Helm wait not working on centos 7

### ISSUE THREAD

**Issue by sachinphogat** [helm/helm#5126]
Helm wait not working in centos. I am using helm v12 and the same version is working fine on ubuntu, but centos its not waiting for deployments to go in running state.

**Comment by bacongobbler** [comment]
Hey @sachinphogat, would you mind providing more information on the behaviour you're seeing and what the expected behaviour should look like? An example would be really helpful here to better understand the issue. Thanks!

**Comment by sachinphogat** [comment]
We use helm install/upgrade --wait --timeout 120 so that helm wait till pods status is set to running, the same version of helm is working fine in ubuntu with wait command but when I use the same version in centos, helm command doesnot wait for pods to get in running status.

**Comment by bacongobbler** [comment]
closing as inactive.
