### ISSUE TITLE
Feature: add --repo-name to 'helm repo update'

### ISSUE THREAD

**Issue by ArieLevs** [helm/helm#5127]
feature request
---------------

Output of `helm version`: v2.12.0
Output of `kubectl version`: v1.11.0

It would be grate to have `--repo-name` flag when using `helm repo update`
I think there are use cases, to update a specific repository, as sometimes one of the repositories update may fail for all kind of reasons, this is mainly intended to you with `--strict` flag

**Comment by ds-ms** [comment]
I'd like to pick this up.
