### ISSUE TITLE
helm upgrade does not propagate all changes to subchart

### ISSUE THREAD

**Issue by wu105** [helm/helm#5129]
Output of `helm version`:
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-12T16:29:47Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3+2.0.2.el7", GitCommit:"b98649b5bc3127838c2ecce14f3b207e0a3c9382", GitTreeState:"archive", BuildDate:"2018-10-15T23:45:53Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
none. nodes are vmware instances. using nfs-client for dynamic storage.

Test case:
```
git clone https://github.com/goharbor/harbor-helm
cd harbor-helm
git checkout 0.3.0
helm install --name harbor --namespace harbor .
```
# initial status:
several pods have imagePullPolicy: Always
```
helm upgrade harbor --namespace harbor --set redis.image.pullPolicy=IfNotPresent .
```
# final status:
now there are more pods has  imagePullPolicy: Always than delete/re-install would have.  The problem pods are from the subchart redis.  In my run, the harbor-redis-master-0 is not re-started while harbor-redis-slave-... is -- both should have because of the imagePullPolicy change.  I could not see what helm  sends to k8s on the subchart using the --debug flag.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
