### ISSUE TITLE
New CA does not take effect after reset and init with new tls certificates.

### ISSUE THREAD

**Issue by colinhuhu** [helm/helm#5130]
I run helm reset to clean previous installation. Then generate certificates as in page https://docs.helm.sh/using_helm/#using-ssl-between-helm-and-tiller and copy to helm home.
Initialize with the following command,
`helm init --tiller-tls --tiller-tls-cert ./tiller.cert.pem --tiller-tls-key ./tiller.key.pem --tiller-tls-verify --tls-ca-cert ca.cert.pem`
Run list command, but it failed. I tried copying previous .pem files to helm home and list command could work. Is there any command i can run to enable new CA?
```
# helm ls --tls-verify
Error: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "localhost")

```
Output of `helm version`:
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11+IKS", GitCommit:"bc3553bc50320a3af1052ba91736f64b9bcb0500", GitTreeState:"clean", BuildDate:"2018-11-28T18:43:33Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): IBM kubenetes service

**Comment by colinhuhu** [comment]
It could work delete all deployment/service/secret, then run command 
`helm init --tiller-tls --tiller-tls-cert ./tiller.cert.pem --tiller-tls-key ./tiller.key.pem --tiller-tls-verify --tls-ca-cert ca.cert.pem`

**Comment by bacongobbler** [comment]
closing as inactive.
