### ISSUE TITLE
Dynamic component instances at install time like extra aliases

### ISSUE THREAD

**Issue by ryandawsonuk** [helm/helm#5131]
Let's say that you want to compose an app from a set of re-usable components. Think of adding consumers to a streaming application where the consumers share the same structure. The consumers would ideally use the same chart but with different images depending on what they do. So to add a consumer to the app chart then you can add a new entry to the requirements with an extra alias (say consumer2) and then your values file looks like:

```
consumers:
  consumer1:
    image:
      tag: consumer1
  consumer2:
    image:
      tag: consumer2
```

But what if the idea of adding consumers is intrinsic to the way your app works? Think of a tool for data processing pipelines or business process flows (BPM/workflow) where the composition of components is what the tool is trying to provide. Then you ideally don't want to force your user to create their own charts, you want to provide a dynamic one if possible. 

This is possible currently as you can create a chart that loops over the collection in the values file with a range function. So instead of one deployment, service etc as you get with most charts (e.g. see the official charts) you generate one per consumer entry. 

The Activiti project would like to contribute an official chart for Activiti Cloud BPM. We can use[ range-based looping](https://github.com/devspace-cloud/devspace/blob/cc0a04f3e3a12eabb42f5e21f0f19648cc79231f/examples/kaniko/chart/templates/deployments.yaml) if that is the preferred way. We're not alone in wanting to use helm in this way - [there's a good example on SO](https://stackoverflow.com/questions/54035672/hierarchy-of-values-for-dynamic-helm-chart-configuration) (and [other examples](https://stackoverflow.com/questions/52742241/dynamically-accessing-values-depending-on-variable-values-in-a-helm-chart) and [approaches](https://stackoverflow.com/questions/51545829/helm-managing-a-collection-of-services)).

Naturally the range looping will complicate the chart. It would be more like scripting and less like templating. See esp that [SO approach](https://stackoverflow.com/questions/54035672/hierarchy-of-values-for-dynamic-helm-chart-configuration) or a rough-n-ready illustration [here](https://github.com/ryandawsonuk/dynamicchart). 

I wonder if this could be made easier in the future by supporting adding an extra alias at install-time. Something like 'extraAliases="consumer:consumer2"' to include an aliased dependency at install time under a different alias. Just for aliases, not for adding in whole extra chart dependencies (which would always require a full build). Then dynamic applications like this could have canonical helm charts where users would only have to override the values file and supply the correct aliasing arguments. 

Perhaps a more script-heavy approach will become more normal in helm3. I'm hoping that by raising this kind of dynamic components use-case can get more consideration and attention.

**Comment by ryandawsonuk** [comment]
To be clear, you can already add aliases in the requirements.yaml without requiring a new build of the chart so that the same package can be used multiple times. What would nice would be to have a way to add aliases from the command-line or in the values file so that it is exposed to end-users of the chart.

**Comment by ryandawsonuk** [comment]
Or in a new aliases.yaml file, that would just be an extension of the existing aliases feature but for the chart the user is installing it would be available for them to add to at install time.

**Comment by bacongobbler** [comment]
closing as inactive.
