### ISSUE TITLE
Inconsistent Release Name - Namespace appended

### ISSUE THREAD

**Issue by FrenchBen** [helm/helm#5134]
Output of `helm version`: `v2.11.0`
Output of `kubectl version`: `v1.11.5`
Cloud Provider/Platform (AKS, GKE, Minikube etc.): n/a

I've created 2 additional namespaces:
* util
* dev
* default

Tiller is deployed in the `util` namespace, and has access to the `dev` and `default` namespaces (thus can deploy to those namespaces). 
This allows me to have 1 tiller/helm install for multiple namespaces, with the exported ENV var of `TILLER_NAMESPACE=util`

When doing an install to a specific namespace, I tend to either call it out directly via `--namespace=dev` or use `kubectx dev` to switch to a context with that namespace as a default.

During the `install` of a new chart, I specify a name, and specify the namespace to target - What I've noticed is that on upgrade, if the namespace isn't specifically defined in the CLI, there's a chance that a new helm deployment will be created, with the namespace as part of the deployment name.

Say we are in the context of the `default` namespace, and wish to install the bitnami nginx chart:
`$ helm --namespace dev install --name nginx bitnami/nginx --version 2.1.0`

Checking the install went well: (versions are mocked)
```
$ helm list
NAME             	REVISION	UPDATED                 	STATUS  	CHART           	APP VERSION	NAMESPACE
nginx            	1       	Mon Jan  7 15:36:10 2019	DEPLOYED  	nginx-2.1.0     	1.14.0     	dev
```

If we were to then update our context to be in `dev`, so that the `--namespace` flag wasn't needed, but needed to update our helm deployment:
`$ helm upgrade nginx bitnami/nginx --version 2.1.2`

There's a good chance that you will end up with a helm list that looks like:
 ```
$ helm list
NAME             	REVISION	UPDATED                 	STATUS  	CHART           	APP VERSION	NAMESPACE
nginx-dev        1       	Mon Jan  7 15:36:10 2019	DEPLOYED  	nginx-2.1.2     	1.14.2     	dev
nginx            	1       	Mon Jan  7 15:36:10 2019	DEPLOYED  	nginx-2.1.0     	1.14.0     	dev
```

Note that we didn't specify the `--install` flag which would create the release if it didn't exist.
IMHO the namespace shouldn't be appended to the name, unless it's explicitly requested by the user. 

Getting to replicate the above behavior isn't consistent, I only discover it after something failed to update. 
There's a chance that I was passing the `--namespace` flag as part of the upgrade, which according to the docs should have no effect on the name itself:
`--namespace string    namespace to install the release into (only used if --install is set). Defaults to the current kube config namespace`

**Comment by bacongobbler** [comment]
@FrenchBen if you could somehow provide a reproducible example or a unit test to demonstrate this bug, that would be very helpful. Thanks!

**Comment by bridgetkromhout** [comment]
Hi, @FrenchBen - as we do not have enough detail to reproduce this, we'll close this at this time. Helm 3 no longer has Tiller, which may help with some of your concerns; see https://helm.sh/docs/faq/ for more details about the changes from Helm 2 to Helm 3.
