### ISSUE TITLE
custom_resource_definitions.md recommends use of pre-install instead of crd-install

### ISSUE THREAD

**Issue by ethiebaut** [helm/helm#5138]
_doc issue_

The doc in docs/chart_best_practices/custom_resource_definitions.md mentions the use of pre-install instead of the recommended crd-install as per https://github.com/helm/helm/pull/3982
CRDs installed during pre-install aren't  provisioned before resource validation and therefore it would not be possible to provision resources based on CRDs provisioned in pre-install.

**Comment by ethiebaut** [comment]
Pull request https://github.com/helm/helm/pull/5139

**Comment by bacongobbler** [comment]
Thanks for the follow-up.

**Comment by ethiebaut** [comment]
Thanks everyone for the reviews & merge! Martin, we have to catch up, I haven't seen you in ages ;-).

**Comment by hickeyma** [comment]
Sounds like a plan Eric! :)
