### ISSUE TITLE
[Question] Can a shell command be executed in Helm template

### ISSUE THREAD

**Issue by MirzaMerdovic** [helm/helm#5145]
Hi,

I am guessing that this is not supported, but wanted to be sure.

I know that we can do:
```
helm install my-chart --name=my --set global.ip=$(.\getIp.ps1)
```

but is it possible to bind a value to a shell command in *.tpl
Something like this:
```
subsets:
  - addresses:
      ip: {{ $(.\getIp.ps1) }}
```
or
```
subsets:
  - addresses:
      ip: {{ $(kubectl get svc my-service -o jsonpath="{.spec.clusterIP}") }}
```

Thanks,
mirza

**Comment by bacongobbler** [comment]
Closing as answered, but please feel free to re-open if necessary. Thanks!

**Comment by MirzaMerdovic** [comment]
@bacongobbler  thank you! I must admit I am not surprised with your answer. 
I was tweaking things for the purposes of local setup, so I wandered if there might be a way to run a command through some unsafe option.

**Comment by chainhead** [comment]
@MirzaMerdovic  how did you get this working eventually? 

```yaml
subsets:
  - addresses:
      ip: {{ $(kubectl get svc my-service -o jsonpath="{.spec.clusterIP}") }}
```
I have a similar requirement, where I need to pass `kubectl ...  -o jsonpath= ...`.

**Comment by chainhead** [comment]
@bacongobbler any implication of removal of Tiller in Helm 3 on the statement below?

> Additionally, chart templates are rendered by Tiller, so the rendering process occurs server-side rather than client-side.

**Comment by Asmodeusss** [comment]
Yo can we get a good way to actually achieve this or what? I need to be able to access secrets SO OFTEN this this limited functionality becomes quite infuriating. Every time I have a chart that doesn't have an existing secret option, I have to fork it and add it myself. It would be so much more convenient if we have a way to reference already existing kubernetes resources during the creation of the chart.

**Comment by murradkh** [comment]
> @MirzaMerdovic how did you get this working eventually?
> 
> ```yaml
> subsets:
>   - addresses:
>       ip: {{ $(kubectl get svc my-service -o jsonpath="{.spec.clusterIP}") }}
> ```
> 
> I have a similar requirement, where I need to pass `kubectl ... -o jsonpath= ...`.

there is a command in helm3 do what you need is called `lookup`
https://helm.sh/docs/chart_template_guide/functions_and_pipelines/

**Comment by colearendt** [comment]
For anyone looking for arbitrary shell functionality (for secret management and such), [helmfile](https://github.com/roboll/helmfile) has been a helpful tool that we use for the task. Generally speaking, what you may be looking for is a wrapper around helm - I believe there are some similar paid / professional / platformy solutions as well

**Comment by E11esh** [comment]
Now Helm templates seems to provide template function named [lookup](https://helm.sh/docs/chart_template_guide/functions_and_pipelines/) to access `kubectl get` API
