### ISSUE TITLE
document how community members can help review PRs

### ISSUE THREAD

**Issue by michelleN** [helm/helm#5147]
the process right now is community members generally leave a github comment with an LGTM and/or add their feedback (also as a github comment) and tag a core maintainer to get something merged or give additional feedback

Idk if this is ideal but we should at least state publicly somewhere that this is the process at the moment so we can iterate.

**Comment by michelleN** [comment]
inspired by @bridgetkromhout

**Comment by hickeyma** [comment]
@michelleN I can take this one if thats ok?

**Comment by SlickNik** [comment]
@michelleN @bridgetkromhout: 💯 Thanks for this -- it's a great start! 
@hickeyma Sure thing, go for it. Would love to review when you have a PR pushed up.
