### ISSUE TITLE
helm search display wrong format if some repos unreachable

### ISSUE THREAD

**Issue by pytimer** [helm/helm#5148]
Output of `helm version`:

```sh
$ helm version
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
```

Output of `kubectl version`:

```sh
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Use `kubeadm` create Kubernetes cluster.

### Steps to reproduce:

- `helm init --service-account tiller --skip-refresh`
- `helm repo list` has two repos, `stable` and `local`.
- `helm package minio`
- `helm search`

Run `helm search` shows normal if all repos connect successfully. However, if `stable` repo unreachable, the `helm search` display format wrong. The table header format wrong.

```sh
$ helm search
WARNING: Repo "stable" is corrupt or missing. Try 'helm repo update'.NAME               CHART VERSION   APP VERSION                     DESCRIPTION    
local/minio     2.3.1           RELEASE.2018-12-19T23-46-24Z    Minio is a high performance distributed object storage se...
```

### Expected

I hope if some repos unreachable, the search display like below:

```sh
$ helm search
WARNING: Repo "stable" is corrupt or missing. Try 'helm repo update'.
NAME               CHART VERSION   APP VERSION                     DESCRIPTION    
local/minio     2.3.1           RELEASE.2018-12-19T23-46-24Z    Minio is a high performance distributed object storage se...
```

I read the `helm search` code, https://github.com/helm/helm/blob/master/cmd/helm/search.go#L157 use `fmt.Fprintf()`, it's not start a new line if load index file error. Should it be modified?

**Comment by bacongobbler** [comment]
Good catch. Yes, it should probably be modified to fix that error. If you feel like contributing a fix that would be wonderful.

**Comment by ds-ms** [comment]
I'd like to pick this up, if that's okay

**Comment by pytimer** [comment]
@ds-ms, Thanks. My network instability, i fix this in my local develop branch, but i always can't make `helm`, because `glide install` not works.

**Comment by ds-ms** [comment]
@pytimer no worries! :)
