### ISSUE TITLE
Force Helm To Install on specific Node?

### ISSUE THREAD

**Issue by gelinger777** [helm/helm#5149]
Sorry for this maybe simple question, but how I can force Helm to install the deployment on a specific node (where we have dedicated cpus) and not just randomly chosen one.

**Comment by maorfr** [comment]
Check out this doc:
https://kubernetes.io/docs/concepts/configuration/assign-pod-node/

Hope this helps!

**Comment by gelinger777** [comment]
@maorfr  I saw that already. Things work nice when you deploy just a yaml file, but not that clear when it's a helm. Does helm install command has specific option where I can set nodeSelector? what is the syntaxis? Because what I understood (apologies if I am wrong) the helm chart itself should have such an option, or? Lets say we have mariadb/stable helm. How to force it install on specfic nodeSelector ?

**Comment by maorfr** [comment]
Just add it to your deployment template as usual and deloy using helm

**Comment by bacongobbler** [comment]
I think you're asking about installing Tiller on a specific node, not a chart. If that's so, you can use the --override flag to set those parameters. https://docs.helm.sh/using_helm/#using-override

**Comment by pytimer** [comment]
@gelinger777 `helm init` have a `--node-selectors` parameter, you can see. Hope it helps you.

**Comment by Borlay** [comment]
If i want to install elastic search with command:
helm install --name elasticsearch elastic/elasticsearch

Can someone explain how to set nodeSelector? Because i have windows and linux nodes and i need to run it on linux node with node selector:
"beta.kubernetes.io/os"="linux"

If it's some kind of template, where i can find it and change?

**Comment by pytimer** [comment]
@Borlay You can refer to https://github.com/helm/charts/blob/master/stable/chartmuseum/values.yaml, but it require your chart templates support nodeSelector. Hope it can help you.

**Comment by cinterloper** [comment]
this is a terrible answer. its not to much to ask to just get an example of nodeSelector: thats not just '{}'.

**Comment by aadeshrao** [comment]
@Borlay You can use something like this:

helm install --name elasticsearch elastic/elasticsearch --set nodeSelector."beta\.kubernetes\.io/os"=linux

Note: Escaping '.' character! Hope this helps.

**Comment by rbsrafa** [comment]
Worked in my environment, thanks!

**Comment by shiningbridge** [comment]
To extend it a bit, how would the command look like if I have a hierarchy charts and would like all the pods in the parent and child charts be scheduled on a node with --set nodeSelector.xxx=yyy.
given that all the charts have nodeSelector support, like

```
    {{- with .Values.nodeSelector }}
      nodeSelector:
```

or

```
{{- if .Values.nodeSelector}}
      nodeSelector:
{{- toYaml .Values.nodeSelector | trim | nindent 8 }}
```

or not possible at all?
