### ISSUE TITLE
'helm lint' fails on chart packaged with version from output of 'git describe'

### ISSUE THREAD

**Issue by robbie-demuth** [helm/helm#5150]
Given a Git tag `1.0.0`, a commit immediately following the tag is formatted something like `1.0.0-1-g7627627` when calling `git describe <COMMIT>`. If that version, which is a semantic version, is used as the version in a chart's `Chart.yaml` file, `helm lint` executes as expected. If the chart is then packaged via `helm package` or a chart with a different version number in its `Chart.yaml` file is packaged via `helm package --version 1.0.0-1-g7627627`, calling `helm lint` fails with the following error:

```bash
$ helm lint my-chart-1.0.0-1-g7627627.tgz
==> Skipping my-chart-1.0.0-1-g7627627.tgz
No chart found for linting (missing Chart.yaml)

Error: 0 chart(s) linted, 1 chart(s) failed
```

Inspecting the `*.tgz` file, however, reveals that `Chart.yaml` is present:

```bash
$ tar -tf my-chart-1.0.0-1-g7627627.tgz
my-chart/Chart.yaml
my-chart/values.yaml
my-chart/templates/NOTES.txt
my-chart/templates/_helpers.tpl
my-chart/templates/deployment.yaml
my-chart/templates/ingress.yaml
my-chart/templates/service.yaml
my-chart/.helmignore
```

Unpacking the `*.tgz` file and calling `helm lint` also passes, though this is likely expected given that `helm lint` also passes when the version is present in the exploded chart's `Chart.yaml` file.

Though `helm lint --help` doesn't explicitly say that it supports packaged charts, linting the exact same chart works when it has been packaged via `helm package --version 1.0.0`

Output of `helm version`:

```bash
$ helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

Output of `kubectl version`:

```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-30T21:39:16Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS Kops

**Comment by kivagant-ba** [comment]
same problem 
https://github.com/helm/helm/issues/4594

**Comment by kivagant-ba** [comment]
Workaround: don't change Chart version but change only appVersion.

```
export CHART_VERSION=0.0.1 && \
export APP_VERSION=${CHART_VERSION}-3196cc4.1 && \
&& helm package --version=${CHART_VERSION} --app-version=${APP_VERSION} helm/bla -d helm/packages/ \
&& helm lint helm/packages/bla-${CHART_VERSION}.tgz 
```

Of course with this approach it isn't possible to use a registry for charts, so it is not the real solution.
