### ISSUE TITLE
helm dependency build versus update - clarification

### ISSUE THREAD

**Issue by gsexton** [helm/helm#5155]
In the docs for helm dependency build it states:
```
Build is used to reconstruct a chart's dependencies to the state specified in
the lock file. This will not re-negotiate dependencies, as 'helm dependency update'
does.
```
The docs for "helm dependency update" don't really explain how "renegotiates dependencies" works. Could someone explain it to me? I swear I'll do a PR on the docs to incorporate an answers :)

**Comment by gsexton** [comment]
I finally understand the issue. The negotiate part would come into play if the requirements.yaml contains wild-cards. This was the missing piece for me.

**Comment by hickeyma** [comment]
@gsexton ok, do you want to create a PR and update the docs? or do you want me to make the changes shown above?

**Comment by hickeyma** [comment]
PR #5379 opened
