### ISSUE TITLE
Suggestion: Provide a default for maxHistory

### ISSUE THREAD

**Issue by JDiPierro** [helm/helm#5157]
I recently discovered over 100 old release ConfigMaps in my `kube-system` namespace. I stumbled upon #2332 which provided a great explanation of why it was happening and how I could prevent it in the future but I'm left wondering why the default for `maxHistory` is unlimited? Allowing infinite growth in the `kube-system` namespace seems like a very strange design decision; I understand they're there to allow for rollbacks but I feel like most people don't need the ability to roll back to a version from 80+ releases ago.

I think it would be prudent to set a default limit on `maxHistory` to prevent future users from having runaway ConfigMaps and putting the health of their cluster at risk. Even something high like 100 would allow for plenty of selection while rolling back while also preventing infinite growth.

**Comment by bacongobbler** [comment]
Due to backwards compatibility, the default for `maxHistory` has to remain unlimited until Helm 3. I do agree it would be nice to set a limit by default going forward.

**Comment by 0verc1ocker** [comment]
I agree that this feature would be nice. Right now configMaps can grow infinitely on previously deployed releases of Tiller and Helm. The only way to fix this it to purge and delete releases already deployed which can be a big inconvenience if you are dealing with many cluster and releases.

**Comment by ian-howell** [comment]
Is this something we want to add for v3? I can take it if so, shouldn't be too hard

**Comment by bacongobbler** [comment]
Tiller has been removed in Helm 3 so the internals have been refactored a bit. I'd wait until we shake out the internal architecture before tackling this PR as we may have to re-think how we set configuration such as the maximum number of revisions Helm retains.

**Comment by whereisaaron** [comment]
Even if the default isn't changed in code, setting `max-history` could be heavily recommended on the documentation website and github `README.md`? And `max-history` could be added to all the examples `helm init` commands in the helm 2 documentation?

**Comment by 0verc1ocker** [comment]
I agree with @whereisaaron . The fact is that you can change `max-history` after the first time, but it might be too late. Configmaps alone grow at an alarming rate and slow down everything.

**Comment by bacongobbler** [comment]
If someone wants to add that to the documentation, that would be great.

**Comment by 0verc1ocker** [comment]
Thanks @bacongobbler . I'll look into making a PR and add some notes to docs in the next couple days.

**Comment by 0verc1ocker** [comment]
https://github.com/helm/helm/pull/5328

**Comment by bacongobbler** [comment]
Leaving this open to track the work to set this value to a sane default for Helm 3.

**Comment by bacongobbler** [comment]
Fixed in #6421
