### ISSUE TITLE
Support for bearer token and other options in Helm client

### ISSUE THREAD

**Issue by JTG2020** [helm/helm#5159]
Output of `helm version`:
2.12
Output of `kubectl version`:
1.12
Cloud Provider/Platform (AKS, GKE, Minikube etc.): On Prem

I am opening this issue as suggested by @jdolitsky -[here] (https://github.com/helm/community/issues/58).
Helm should support all or most options that kubectl supports with respect to command line. Currently we could not use helm in our organization in spite of its great features because it just works on the existence of kubeconfig files for authentication. We are using multiple Kubernetes clusters and deployments happening through centralize deployment tool which has pool of servers with kubectl and helm installed. As it is centralized pool of servers, we don;t want to have any kubeconfig files on servers, instead we are using bearer token provided by OIDC for authentication. In additional we are passing necessary parameters such as master url, namespace etc to kubectl at runtime to execute deployments.
The bearer token is masked from display as shown in below example -
`kubectl --server=https://xyz.net:8443 --namespace=x-team1 --insecure-skip-tls-verify=true --token **** apply --filename=my-deployment.yaml `
Note that "=" between parameter and value works with space as well e.g.
`kubectl --server https://xyz.net:8443 --namespace x-team1 --insecure-skip-tls-verify true --token **** apply --filename my-deployment.yaml `
With Helm we can not use any of these options and hence can not use helm.
I am hoping that as tiler is being removed from architecture, helm cli should also support options same as kubectl to perform deployments by passing parameters at run time as oppose to static kubeconfig file.
If you need any more information, please let me know. I can also help with testing if needed.

Again more details on issue can be found [here in community issues](https://github.com/helm/community/issues/58)

**Comment by bacongobbler** [comment]
closing as inactive.
