### ISSUE TITLE
Bazel rules

### ISSUE THREAD

**Issue by borg286** [helm/helm#5160]
This is a feature request to add bazel build rules so users can wrap a chart directory in their bazel workspace with some helm rule. This rule, when ran, would feed the chart into the helm binary (tillerless) and create/upgrade the chart.
A very similar feature would be the ability to use the external repo ability of bazel to point to the charts github repo, and then in a single rule you could ingest a user-specified values.yaml file and point to a particular chart in the repo.  By simply running the rule you get the effect of doing
helm install some-chart myvalues.yaml

I realize that this seems like adding unnecessary complexity to a simple command line tool, but with bazel build dependencies this would be a very useful tool to set up dependencies on charts.
Please include the following ability, either as specific build targets, or as parameters that must be included when one runs the target

create
delete
apply (has the same effect as upgrading)
diff
describe

**Comment by rimusz** [comment]
this could be done as helm plugin

**Comment by borg286** [comment]
Let me explain the scenario.

A developer has a bazel workspace and is building docker images that serve as the frontend for his service.  One day he decides that having cassandra as the storage layer would be awesome. Instead of writing some k8s yaml himself, he decides that using helm is better. He wants to ensure that his frontent isn't ran without the cassandra backend running. Currently he has to remember to run helm install cassandra every time that he creates a sandbox stack, and also mentions to the ops folks that you have to install and run helm to set up his cassandra backend so his frontend actually works.
Instead he wants to define some bazel rules that not only spin up his service but also spin up cassandra. When he updates his code and runs apply on his frontend he also wants to "upgrade" his cassandra fleet in case there were any changes to the values.yaml.  Thus in the bazel world there is this dependency with bazel targets can be ran idempotently.  

In today's world this dev would need to create a bazel native.genrule that assumes that helm is installed on the machine.  Note that this is not a new way to run helm, nor some new functionality that he wants helm to do. Only a different path to execute helm and invoke its native capabilities.

Bazel has a way that you can point to a github repo and build the binary, or, point to some binary that bazel downloads and makes that binary available to other rules to use in clever ways.  Pointing to some binary has the drawback that it won't work on another arch, but that is a minor point that can be solved later.
Even pointing to a docker image that holds the helm binary would do wonders.

If we wanted to go even further we could make it easy to point to different charts and no longer need to force the dev to download the chart locally so that helm can run on that local copy.  We do this by having our rule expose a srcs param which we can point to an external repo, namely the helm charts repo.  Bazel will then fetch the whole repo and point helm to operate on a particular folder in there, as well as pointing helm to the values.yaml file the dev wrote and is in their local workspace.

Note this is not some new functionality on top of the helm binary, but rather a way of invoking it and wrapping/pointing to it in a bazel-friendly manner.
I don't expect this to change the way that helm is built currently, only an extra file or 2 in the helm repo that gives instructions to bazel on how to use helm.

**Comment by hickeyma** [comment]
@borg286 I think you have a good use case here but it is not Helm core functionality. As @rimusz mentioned, [helm plugin](https://github.com/helm/helm/blob/master/docs/plugins.md) could be a way to do it.

**Comment by borg286** [comment]
I'm curious how you think a helm plugin would help bazel users define BUILD targets that invoke helm on a local standard chart.
Note that the user is expected to run bazel, which, through some bzl file you wrote, would invoke helm pointing it to a run-of-the-mill local chart.  Let's set aside pulling a chart from the web as either bazel or helm are capable of that.
For reference bazel supports [genrule](https://docs.bazel.build/versions/master/be/general.html#genrule_examples) which is an easy way to let bazel run command line utilities and route inputs to the cli flags.

**Comment by hickeyma** [comment]
Would it be possible to script/code/wrap the necessary steps to setup the configuration/artifacts that bazel would need? If so then this can be called in the plugin command.

**Comment by borg286** [comment]
Yes technically but it completely circumvents the idea behind bazel's ability to pull down github repositories and do stuff. I am curious regarding your understanding of how bazel works.  
Let me explain in other terms.
The helm/helm repo has a file called .gitignore which doesn't make helm act differently. It is just a file that integrates with the git process telling it what files to ignore when pushing to github.  It would be absurd to say that the .gitignore file shoud be generated by the helm binary because it is static and reflects a global (as in everyone in the world with git knowledge would agree that those files should be ignored) statement.
You have a README.md which could be created by a helm plugin, but is really just idly there to allow github to interoperate with your codebase.

There is a build system, bazel, that can be told to go fetch a github repo, pull it down, and let it define rules. For example you could define a rule to take an input string and cat it to an output file.  Then some developer that likes this functionality could put in their WORKSPACE file a reference to this github repo and thus make this rule available to all of the services and libraries in his bazel workspace.  He would create a BUILD file and invoke this rule passing in some string.  WHen the user builds this target bazel would download the github repo with its rule and invoke it on the user's input making that output file an build artifact that could get consumed by other build targets.  Other rules could make executables that bazel then runs after compiling it.
Let's say you create a github repo called helm/helm-rules and in it you have 3 files
WORKSPACE
---
workspace(name="helm-rules")
# nothing more

BUILD
---
# nothing here

helm.bzl
---
```
def helm_chart(name, chart, values_yaml):
  genrule(
    name = name,
    srcs = [chart_ref,  values],
    outs = ["shell_that_invokes_helm.sh"],
    cmd = 'echo helm install ' + chart + ' --values=$(location ' + values_yaml + ') > $@',
  )
```



This github repo simply existing enables all bazel users to pull in this repo, just as the above WORKSPACE pulled in the charts repo.  They could then create build targets like this

WORKSPACE
---
git_repository(
    name = "helm_rules",
    tag = "1.0",
    remote = "https://github.com/helm/helm_rules.git",
)

BUILD
---
load("@helm_rules//:helm.bzl", "helm_chart")
helm_chart(
  name = "myredis",
  chart = "redis-ha",
  values = "my_values.yaml"
)


Then when the user builds this :myredis target bazel would then download this helm_rules repo.  Bazel would run this echo command to construct a shell file that invokes helm. 
When the user does 'bazel run :myredis' it would invoke this shell script.  Helm would then be called and download the chart and told its values are in some file.  Helm would then do go templating and so forth to spin up the redis ha service.  Note that we're not trying to get helm to set up our workspace, rather we configure our workspace to find rules that wrap around helm and use bazel's capacity to download github repos and pipe their locations around.

I'll grant that this seems like quite a round about way to just "run helm" but this design makes it easier to create a service and easily declare a dependency on a helm chart and have bazel understand this dependency and run each dependency recursively.  Each service doesn't need to have helm executed for independently by a human. 

Note that this imaginary helm_rules repo doesn't need to exist in the helm/helm directory as it simply assumes that the bazel user has installed helm natively.  If you wanted to go further you could have this repo try and build helm from scratch, but that seems to be too advanced for this discussion.  The benefit in doing that would be the ability to run helm on arm or whatever arch, and not get tied to x86 which is what the helm binary is fixed to.

Also note that this central helm_rules repo does not get recreated for every bazel user. They simply point to it and pull down the features it provides.  Your team could then enrich this repo to be closer to the rich set of features your binary is capable of.  To align better with the bazel paradigm you could upgrade this helm_rules repo to reference the charts repo and bazel would take care of downloading the repo locally enabling you to point to charts idiomatically rather than downloading them dynamically. This gives you a more idempotent process, which is the bazel way.

To be crystal clear creating a helm plugin to modify the bazel workspace reverses the flow of action. I want helm to provide an authorized repo that they will maintain to allow bazel users to point to it and inherit a bazel-compliant way of invoking helm, and preferably making it easier to declare dependencies on charts.

**Comment by hickeyma** [comment]
@borg286 It was just an alternative when I suggested a means to do this using plugins. It was not meant to be  definitive solution for you. Hope that's ok?

@mattfarina @technosophos could this a feature for Helm?

**Comment by mattfarina** [comment]
@borg286 Thanks for bringing the suggestion here and being willing to discuss it.

Because bazel is a niche tool I know that many are not all that familiar with it. I'm familiar with it only because of my work with Kubernetes. So, thank you for taking the time to explain some details. I'm sure it will be helpful for people who have come along.

As I understand it, Bazel requires the upstream packages to be altered to have bazel files included. This is why a helm plugin would be difficult. For anyone not using the plugin those upstream files would not exist. 

For example, for Kubernetes to be built by bazel it includes bazel files (e.g., [here](https://github.com/kubernetes/kubernetes/blob/76961c517e538206dd121c60a37736df9c328726/build/root/BUILD.root)). They are not in a fork or in local tooling but in the upstream project.

This setup requires (is that too strong of a word?) upstream projects to include bazel files to be pulled in and handled by bazel. I think that's what the ask here is. To include bazel files  in charts by default so bazel can leverage them.

Please correct me if or where I'm wrong.

If this is the ask then I have two questions:
1. How does bazel handle container images today? I ask because of the way we are looking at shifting the repository model for helm v3. Container images in registries is a good corollary for that.
2. Bazel is a niche system. If we are going to start supporting outside toolchain configuration in charts we will need to look into a decision criteria for when to choose to add them. What is the case that makes bazel worth including? I'm curios of something going beyond personal taste as that is debatable (vim vs emacs vs vscode... right).

**Comment by borg286** [comment]
To answer your specific questions
1. Bazel does not nativly provide a way to build artifacts on top of existing docker images. You can define a rule that builds some artifact and use rules_docker to layer that on an existing tar file, but no pulling from the web and building a new image on top of that.  The bazel way is build each layer then compose them into a docker image using rules_docker which, under the hood, just makes a tar file and pushes that to a local docker service.  However when running some target all bets are off and you can access the web, which is what I'm relying on in my example above. I'm simply telling helm to make https queries to kubernetes and it pulls docker images to run your binary.  If you're talking about how to compile helm itself, the binary, then containers are off the table for the reasons above.
2.  Just so we're on the same page, we're talking about making changes to the charts repo so that when a developer configures his workspace to pull in that repo that he can then reference a particular chart folder rather than just a single file.  By referencing this chart (ie. a folder in the charts repo) bazel copies this folder into a build sandbox where building tools (like helm for example) can access it in a more local fashion.  For adding bazel support I suppose you can add a single file called BUILD with the following contents
filegroup(
    name = "chart",
    srcs = glob(["**/*",]),
)

This recursively finds files in that chart folder and wraps them up into a set of files that constitute this :chart build target.  Thus I can pull in all the chart's files by passing in "@helm_rules//redis_ha:chart" and bazel goes into the redis_ha folder, looks for a BUILD file, finds this "chart" target and grabs all the files and copies them into a sandbox and lets whatever rule you define operate on it.  
Alternatively I think it may be possible to define these targets in a single BUILD file in the root of the repo like this.

[filegroup(
    name = chart,
    srcs = glob([chart + "/**/*",]),
) for chart in ["redis_ha", "redis", "cassandra"...]]

This way you would only need a single file and "support" means making sure the chart name is in this list.

There are 3 levels of support I can see.

1. Make a repo like the one I outlined above (separate helm_rules repo with single WORKSPACE, BUILD, and helm.bzl file) with the following pros and cons
Pros: 

- Dead simple, never need to update the repo
- No need to figure out how to build helm with bazel
- Bazel users that also use helm will start pulling in that repo and you can update it later

Cons

- Expects helm to magically exist on the host machine. Not that far fetched to assume people familiar with helm would have the binary installed.
- It is hard to validate that what it is doing is right because you are just telling helm to install whatever it thinks "redis-ha" is.


2. Do (1) but instead of referencing the chart by string, you use that string in a reference to another github repo, namely your charts repo, like in (answer 2) above, and point to some package group that includes all the files of the chart.
Pros:

- You become a bit more hermetic by being able to have the chart's files local.  

Cons:
 
- It only works on x86


3. Fully support building helm using bazel

Pros:

- You nativly support users that want to run helm on non-x86 arch (yeah, not that exciting).
- Developing helm becomes hermetic

Cons:

- This is a really huge migration with not much win
- The nature of helm is in interacting with Kubernetes and managing upgrades, not in producing some target artifact. Thus you are forced to minimal build artifacts that prepare the files needed to run helm on some local files, ie. your build artifacts are a shell script that invoke helm which goes and does the real work.



The real request here is either 1 or 2, not 3.  To be clear I'm not asking you to migrate to a new build system. I'm not asking you to build charts with bazel. I'm not asking you to build a plugin that talks to bazel or writes some configuration. I'm asking you to make it easy to invoke helm by writing a bazel build rule that you write which makes a shell script that invokes helm. This script would simply take the build inputs and pipe them to the different params of helm.

**Comment by bacongobbler** [comment]
I'm going to go ahead and mark this as a "Help Wanted". None of the core maintainers have ever really used Bazel outside of using it as a tool to compile Kubernetes.

My personal take on this feature: is I'm leaning more towards the fact that this may not be something we should introduce to `helm create` unless there was large demand from the community to support this. Even then I'd still consider this outside the "core" of what Helm is supposed to achieve.

Spitballing here, but perhaps there may be a way to introduce a hook system into `helm create` for plugins, where a plugin could then be installed and register itself to `helm create` so that it gets triggered each time `helm create` is called. The use case I'm imagining here is

```
$ helm plugin install https://github.com/borg286/helm-create-bazel-rules
$ helm create mychart
```

Which then `helm create` would execute the plugin shortly after creating the chart.

That would achieve 2 things:

1. The core maintainers aren't maintaining a codebase they're unfamiliar with
1. Users who don't want bazel rules in their Helm charts won't get them by default unless they opt in.

@borg286 would something like this interest you? If so, would you be interested in contributing that feature to Helm 3 to provide this functionality?

**Comment by borg286** [comment]
I'm confused regarding what the "execute the plugin" would do.  I feel like we're going in circles.  You reference "way to introduce a hook system into helm create"  This doesn't make sense given the fact that I'm not talking about new functionality in the way helm does creates. Please elaborate on what would helm be "creating". Obviously creating snippets that are pasted into one bazel WORKSPACE file is wrong.  `helm create` is intended for creating kubernetes services on a kubernetes cluster.  While that is the end result of my feature request, I am proposing that bazel invokes helm, just like if bash were to invoke helm, and provide command line arguments to it.  

Let me put it to you in a different way. Let's say you were using puppet to set up a work environment for a new developer.  You might have some bash script that spins up a local kubernetes cluster, then install helm, then tell helm to install redis, cassandra, wordpress and some other thing.  You'd write a bash script to invoke helm.  It would be absurd to implement this functionality (tell helm to create this chart and that chart) in a helm plugin.  You're starting with puppet calling on a bash script that calls on helm.  You might think that "well it isn't that hard to write a bash script to install redis, cassandra and wordpress"  and that is exactly my point. Just a simple bash script that makes invoking helm a bit easier, only this bash script has a little extra pieces that make working with bazel a bit easier rather than puppet. Bazel and puppet taking the role of "the thing that the user calls on first which calls out to other things"  I hope I've helped you recognize that helm plugins are a solution for a different problem that I don't have.

I'd be happy to make a PR to add a repo under the helm umbrella.  It would however be a repo that a user using bazel could point to in their workspace so that they could make it easier to invoke helm and use its standard chart installation capabilities, plugin-free.  I expect the only kind of maintenance would be to update the list of chart names available.  Does this sound like something that the helm team would accept as authorized by helm?

**Comment by tmc** [comment]
@borg286 perhaps you should propose a change in the charts repo?

**Comment by mattfarina** [comment]
@borg286 I'm sorry for the slow response. I've been a bit swamped and traveling.

I think there is some confusion in this thread around what you are asking for and why. With that in mind, let me try to state what I think you are asking for and you can then correct me so we can work to get on the same page.

1. A bazel file in the helm/helm repo so that when bazel is down about the helm repo location it can go there and figure out what to do with the repo. That could be building from source or downloading the right binary.
2. Add something to charts so that bazel can discover where to get the charts so the end user doesn't need to download the things.

I expect I have something wrong with this since I am only loosely familiar with Bazel. Please be patient and help fill in the gaps.

I will say on point 2, Helm v3 should make this easier because we plan on allowing for charts stored in container repos (we worked with the OCI on this). You can refer to them like you would with containers. Or, that's the idea.

**Comment by bacongobbler** [comment]
This project was just pointed out in Slack. https://github.com/tmc/rules_helm

**Comment by borg286** [comment]
@bacongobbler that project is perfect. It accomplishes the vast majority of this feature request. You can close this bug.

**Comment by abrisco** [comment]
I've also written https://github.com/abrisco/rules_helm/

It's a bit rough around the edges but for my own uses has been pretty useful.
