### ISSUE TITLE
Runtime error / templating crash when using `merge` with empty hash

### ISSUE THREAD

**Issue by kierenj** [helm/helm#5163]
Using `merge` to merge in anything with an empty hash/dictionary/whatever it's called in YAML, causes a runtime error:

`Error: rendering template failed: runtime error: invalid memory address or nil pointer dereference`

See `crash` branch here: https://github.com/kierenj/helm-template-issue-repro/tree/crash

### values.yaml:
```yaml
x:
```

### test.yaml:
```yaml
{{- $p := dict "a" "b" }}
{{- $_ := merge $p .Values }}
```

Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

Output of `kubectl version`: n/a

Cloud Provider/Platform (AKS, GKE, Minikube etc.): n/a

**Comment by bacongobbler** [comment]
IIRC `merge` is a function introduced by the [sprig](https://github.com/Masterminds/sprig) library. See the merge code [here](https://github.com/Masterminds/sprig/blob/544a9b1d90f323f6509491b389714fbbd126bee3/dict.go#L80-L88).

Would you mind filing an issue upstream?

**Comment by kierenj** [comment]
I'm so out of the loop on sprig, the go ecosystem etc - I could raise the same above issue but isn't a bit unfair on the sprig team for me to just provide an example for a product that uses their library?

**Comment by bacongobbler** [comment]
The maintainers of sprig are also core maintainers of Helm (@technosophos and @mattfarina).

A basic `text/template` example using the `merge` function would probably suffice. A PR with [a unit test](https://github.com/Masterminds/sprig/blob/544a9b1d90f323f6509491b389714fbbd126bee3/dict_test.go#L129) would be even better. Have a look at [their README](https://github.com/Masterminds/sprig#load-the-sprig-library) for a usage example. That should get you 90% of the way there to a reproducible example without Helm.

**Comment by hickeyma** [comment]
@kierenj Did you get a chance to raise an issue upstream?

**Comment by kierenj** [comment]
Hi, no I didn't - it's a good suggestion but as it stands I have a workaround and many competing priorities so don't plan to at the moment.

**Comment by bacongobbler** [comment]
closing as inactive.
