### ISSUE TITLE
Templated value keys - .Value[.Value.some_other_key].key?

### ISSUE THREAD

**Issue by rgazaryants** [helm/helm#5167]
I don't think this is supported, but Is there any way do call value keys dynamically?

Say I have:
```
#values.yaml
environment: dev
dev:
  port: 8153
prod:
  port: 8080
```

So I have `.Values.environment` & `.Values.[prod|dev].port`

Anyway to call that in the template directly? like `{{ .Value.{{ .Values.environment }}.prot }}`, effectively giving me `values[environment]['port']` if it were Python? 

Ideally we would just use separate value files & not worry about it, but Kubeapps doesn't support selecting a values file, and we're trying to figure a way to support multiple environments in one chart+values without doing a bunch of edits on deploy (besides changing the environment).

**Comment by bacongobbler** [comment]
Should be able to do it with `{{ index .Values "dev" "port" }}`. Let me know if that works or not.

**Comment by bacongobbler** [comment]
Full example:

```
{{ $environment := .Values.environment }}
{{ index .Values $environment "port" }}
```

**Comment by rgazaryants** [comment]
Thank you!
I ended up with this as a one-liner:
`{{ (index .Values .Values.environment).port }}`
