### ISSUE TITLE
Can a rolling update be done on changes to external files such as conf files?

### ISSUE THREAD

**Issue by SachinHg** [helm/helm#5173]
Output of `helm version`: 2.10
Output of `kubectl version`: 1.10

Cloud Provider/Platform (AKS, GKE, Minikube etc.): docker-edge.

I was looking at https://github.com/helm/helm/blob/master/docs/charts_tips_and_tricks.md#automatically-roll-deployments-when-configmaps-or-secrets-change and I wondered if there is a way to trigger rolling updates on changes to external files. 
For e.g, I have config file which is outside of the templates directory. Whenever I make changes to this file, I want a rolling update similar to the one which happens on editing configmaps or secrets. Is this possible?

**Comment by mattfarina** [comment]
Yes. In the example, the rolling update happens when the spec for the Deployment occurs. An annotation value change would cause that. A checksum change for any external file would cause this.

Note, this process still requires a `helm upgrade` be run to cause the rolling update.

**Comment by hickeyma** [comment]
@SachinHg Did this work for you?

**Comment by hickeyma** [comment]
@SachinHg Any update on the issue?

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
