### ISSUE TITLE
Sprig function fail

### ISSUE THREAD

**Issue by brunohms** [helm/helm#5174]
When I use the function fail show it output:
```
Error: render error in "fix-lang/templates/deployment.yaml": template: fix-lang/charts/common/templates/_deployment.yaml:46:11: executing "common.deployment" at <fail "A valide Value...>: error calling fail: A valide Values resources is required
```

The part that concern me is `error calling fail`, I wanted to produce a more human friendly output in case members from my organization forget to add this field.

I'm using the following code to check this:
```
{{- if not .Values.resources }}
{{ fail "A valid Values resources is required" }}
{{- end }}
```

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.2-gke.26", GitCommit:"25365995b58530998bdcd4ea6383682858a0fb7b", GitTreeState:"clean", BuildDate:"2018-12-11T02:37:25Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

**Comment by mattfarina** [comment]
Instead of the `fail` function I think you want to use the `required` function. See https://docs.helm.sh/developing_charts/#chart-development-tips-and-tricks for more detail.

Does that help?

**Comment by brunohms** [comment]
Hi Matt,

Thanks for the answer, however that does not help.

I changed the code:
```
{{- if not .Values.resources }}
{{ fail "A valid Values resources is required" }}
{{- end }}
```
For:
```
{{ required "A valid Values.resources is required!" .Values.resources }}
```
And it still gave me the following error message:
```
Error: render error in "fix-lang/templates/deployment.yaml": template: fix-lang/charts/common/templates/_deployment.yaml:46:11:: executing "common.service" at <required "A valid.se...>: error calling required: A valid Values.resources is required!
```

Is it the expected behavior? to produce the message `error calling required`

**Comment by hickeyma** [comment]
@brunohms It seems to be the response alright. Here is the message string I got:
```Error: render error in "newchart/templates/configmap.yaml": template: newchart/templates/configmap.yaml:7:12: executing "newchart/templates/configmap.yaml" at <required "A valid Va...>: error calling required: A valid Values.favoriteDrink is required!```

**Comment by brunohms** [comment]
Hi @hickeyma thanks for the answers, the response is indeed alright, I just wanted something more "human readable".
I will be closing this issue as this seems to be the expected behavior.

**Comment by filintod** [comment]
@brunohms something I started using is: `fail "\n\nERROR -> Your error message here" `
At least it separates the lines from the other stuff
