### ISSUE TITLE
Feature Suggestion: Please help add GitCommit ID in chart's metadata

### ISSUE THREAD

**Issue by KasperDeng** [helm/helm#5178]
Output of `helm version`: 2.12

Output of `kubectl version`: 1.12

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  ALL

In current chart's Metadata structure, already have semVer format version for the chart, but I prefer to have one more attribute for the GitCommit ID, similar to the output of `helm version` command shows the GitCommit ID of Helm and Tiller.
As you know, the char development is quit important for the deployment. A GitCommit ID is easy for tracing the source of chart for trouble shooting.
Additional, if any extention attribute in char metadata is preferred.

**Comment by mattfarina** [comment]
A short term solution would be to use build metadata in semver. You can do this today. You can read about it at https://semver.org/#spec-item-10

For the version you could have a value of `1.2.3+[commit id]`. The commit id would be ignored in sorting or resolution but could aide you in tracing it to source.

**Comment by bacongobbler** [comment]
closing as inactive.
