### ISSUE TITLE
handle missing key

### ISSUE THREAD

**Issue by dorsanyvision** [helm/helm#5180]
I'm trying to handle cases when I have **missing key** in my values file with easy solution without insert many if conditions to my helm template files.

why?
I want that ability to override my "global" values.

Example:
I have the following line: ```image: {{ .Values.api.deployment.registry | default .Values.global.deployment.registry }}/api:latest```

file ```values.yml```:
```
global:
  deployment:
    registry: gcr.io/mygcr
```
so when the .Values.api.deployment.registry is not exist I'm getting the error:
```
Error: render error in "chart/templates/api/api-deployment.yaml": template: chart/templates/api/api-deployment.yaml:30:25: executing "chart/templates/api/api-deployment.yaml" at <.Values.api.deployme...>: can't evaluate field deployment in type interface {}
```

but, when I added the missing keys, even if they null it will work:
```
global:
  deployment:
    registry: gcr.io/mygcr

api:
  deployment:
    registry: 
```

I saw that helm support something like: ```template.Options("missingkey=zero")``` [link](https://github.com/helm/helm/blob/master/docs/charts_tips_and_tricks.md)
first, I coldn't find how to set it. is it in the helm cli? in my deployment  template file?
second, it will help me?
any other solution?

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T07:10:00Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by hickeyma** [comment]
Trying to work out what the issue is. So, when you define the value `api.deployment.registry` in the value file,  does this line `image: {{ .Values.api.deployment.registry | default .Values.global.deployment.registry }}/api:latest` work as expected?

**Comment by dorsanyvision** [comment]
yes. because now the key exist even if the value is null

**Comment by hickeyma** [comment]
You would need to add the key to the values file but don't need to set its value. You then have the logic in the template which will use `global.deployment.registry` if the value is not set. 

I am unsure then where you have to use if conditions then?

**Comment by dorsanyvision** [comment]
Hi @hickeyma ,
The thing is that I don't want long and complex ```values.yml`` file. so if one of the developers will want to change a specific value to a specific app, He will just add the override values.
in my example it will be: ```.Values.api.deployment.registry```
actually the the login is not matter. what is really matter is how to handle missing key in the ```values.yml`` file

Thanks!

**Comment by hickeyma** [comment]
It probably has something to do with using nested values. The [docs](https://github.com/helm/helm/blob/master/docs/chart_best_practices/values.md#flat-or-nested-values) explain about having to check nested values at each level, so it must need the existence down through the levels. 

Probably means you need to either add the nested values in the value file or code in the templates.

**Comment by dorsanyvision** [comment]
maybe it can be a feature request?
so we can put a flag (like in the cli) about handle missing nested keys? 
for instance if the key is missing just put it as null...

**Comment by bacongobbler** [comment]
Yeah, this issue has to do with handling nested values. If a value is nested and the prior level does not exist, that error (`can't evaluate field deployment in type interface {}`) will occur.

It'd be nice if there was a way we could handle nested values in text/template. Unfortunately, there's not much we can do to handle nested values properly. The link @hickeyma suggested is the best we've got on the subject.

@dorsanyvision we're open to PRs that could help handle nested keys better! If you can find a solution that could alleviate the situation, we're open to a PR. :)

**Comment by andye2004** [comment]
I've been struggling a little with a similar requirement to the OP and came up with a solution that, while pretty ugly, actually works as required.

What I have done is write a template function, say `_functions.yml`:-

```
{{- define "getOrDefault" }}
  {{- $v := .Values }}
  {{- $found := true }}
  {{- range $value := regexSplit "\\." .Path -1 }}
    {{- if hasKey $v $value }}
      {{- $v = get $v $value }}
    {{- else }}
      {{- $found = false }}
    {{- end }}
  {{- end }}
  {{- if eq $found true }}
    {{- $v }}
  {{- else }}
    {{- .Default }}
  {{- end }}
{{- end }}
```

Then in my actual template I call:-
```
...
key: {{ template "getOrDefault" (dict "Values" .Values "Path" "path.to.nested.value" "Default" "dflt") }}
...
```

If the `value.yml` used in the helm command has the nested `path.to.nested.value` key with value `xyz` then the output of the above would be:

```
...
key: xyz
...
```

If any part of the path is missing the output will be

```
...
key: dflt
...
```

Just posting this here so anyone else looking for a solution can at least get an idea of how it maybe _could_ be done.

**Comment by vladfr** [comment]
Found a nice solution to this, which works in go templates [and has been documented by the fine folks at Hugo](https://gohugo.io/functions/merge/).

You can create a map with defaults, and then use `merge` to have them set. Who knew?

```
{{- $default_params := dict "access" "proxy" "type" "prometheus" "basicAuth" "false" "version" 1 -}}
      {{- range .Values.grafana.datasources }}
      {{- $p := merge $default_params . -}}
      - access: {{ $p.access | quote }}
      [...]
      {{- end }}

```

This works nicely, I've just tested with a small Grafana wrapper chart using Helm 3.

**Comment by nyarly** [comment]
I've submitted https://github.com/Masterminds/sprig/pull/254 which will be a nicer solution to this issue when it's merged. 

For Helm charts, I've found that something like
```
{{- if ne ((.Values.agent | default (dict "mountSecurityMode" "")).mountSecurityMode) "Any" }}
```
works and is a little cleaner for a single layer.
