### ISSUE TITLE
Feature request: CLI command to mark release as unstable

### ISSUE THREAD

**Issue by rmorrise** [helm/helm#5187]
I'd like a helm CLI command to tag a deployed helm release with an "unstable" flag.

**Details**

- Introduce a new helm release flag: "Unstable"
- Introduce a CLI command: `helm unstable my-release-name --message It doesn't work.`
- Always display the Unstable flag in `helm history`, even if it's superceded by another release

**Use case**

I want to write a build automation script that does the following:

1. Install with `helm upgrade --install (release)`
2. Verify deployment with `kubectl rollout status (deployment)`
3. Run a test script (e.g. Postman) against the new release -> Test fails!
4. Mark the release with `helm unstable my-release-name`
5. Fetch the latest stable release from `helm history` and restore it with `helm rollback`

**Comment by bacongobbler** [comment]
closing as inactive.
