### ISSUE TITLE
Feature request: built in `Kind` variable

### ISSUE THREAD

**Issue by eamonnmcevoy** [helm/helm#5193]
If possible, It would be useful to have a variable for `Kind`. I would like to use this in _helpers.tml to generate names.

Something like: 
`{{ .Chart.Name }}-{{ .Values.environment }}-{{ .Something?.Kind }}`

would generate:
`mychart-development-deployment`
`mychart-development-service`
`mychart-development-persistantvolumeclaim`

**Comment by hickeyma** [comment]
This would probably be exposed in the `Template` object: https://docs.helm.sh/chart_template_guide/#built-in-objects

@bacongobbler could this attribute exposed in this way or is there another way to get it?

**Comment by bacongobbler** [comment]
I'm not entirely sure this is possible as during this part of the rendering process we have not rendered the templates and therefore cannot determine its `GroupKind` ahead of time. If someone could prove me wrong, I'd love to see this :)

**Comment by filintod** [comment]
I use this workaround many times and might work for you:

{{/* prints the name expects a list of items (pipeline, kind) */}}
{{ define "mychart.name" }}
{{- $dot := index . 0 }}
{{- if eq (len .) 2 }}{{ $dot.Chart.Name }}-{{ $dot.Values.environment }}-{{ index . 1 -}}
{{- else               }}{{ $dot.Chart.Name }}-{{ $dot.Values.environment }}-ObjectNameNotProvided{{ end -}}
{{ end }}

in your templates you now need to use {{ include "mychart.name" list (. "service") }}

not the cleanest, and you need to change all your "template/includes name" but works with the current limitations.

**Comment by bacongobbler** [comment]
closing as inactive.
