### ISSUE TITLE
Cannot add rook repo

### ISSUE THREAD

**Issue by Nemmo** [helm/helm#5196]
Hi folks!

I'm trying to add rook repo, but got an error 
```
helm repo add rook-stable https://charts.rook.io/stable
Error: Looks like "https://charts.rook.io/stable" is not a valid chart repository or cannot be reached: Get https://charts.rook.io/stable/index.yaml: read tcp 192.168.0.99:57673->13.33.23.106:443: read: operation timed out
```

I've tried to add some another repo and everything is fine
```
helm repo add gitlab https://charts.gitlab.io
"gitlab" has been added to your repositories
```

Output of `helm version`: 
```
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-05-12T04:12:12Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
bare metal
```

**Comment by hickeyma** [comment]
Not sure if I have the correct chart but from this rook charts page, it says: "Rook currently publishes builds to the alpha and master channels. In the future, beta and stable will also be available." (https://github.com/rook/rook.github.io/blob/master/docs/rook/v0.7/helm-operator.md#installing)

If this is correct, maybe you cloud try adding alpha or master?

**Comment by bacongobbler** [comment]
Looks fine to me:

```
PS C:\Users\me> helm repo add rook-stable https://charts.rook.io/stable
"rook-stable" has been added to your repositories
```

Can you try again?

**Comment by hickeyma** [comment]
Can confirm @bacongobbler test, works fine for me on Linux also:
```console
$ helm repo add rook-stable https://charts.rook.io/stable
"rook-stable" has been added to your repositories
```

**Comment by Nemmo** [comment]
I've tried to add another branches (beta, master), but still have the same issue

**Comment by Nemmo** [comment]
The problem automagicaly resolved: today I have tried to add repo again, but got the same timeout error. Then I typed `kubectl logs -f tiller-deploy`, saw nothing. And finally I have tried to add repo again and IT WORKS! Crazy!
