### ISSUE TITLE
"no available release name found" in a dry-run

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [helm/helm#5199]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}
```
Initialized in this way:
```
helm init
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Minikube started in this way:
```
minikube start --vm-driver=none
```

I'm experimenting with my 1st chart:
```
# helm install --dry-run --debug .
[debug] Created tunnel using local port: '41421'

[debug] SERVER: "127.0.0.1:41421"

[debug] Original chart version: ""
[debug] CHART PATH: /home/ema/adm/docker/inst-servision

Error: no available release name found
```

How can I solve this?
Is this a bug or a misconfiguration?

**Comment by hickeyma** [comment]
It looks like you are missing files. Is `inst-servision` your chart? If so can you list out the files and dirs in that chart directory?

**Comment by hickeyma** [comment]
Could you show the content of the `templates` directory? You mentioned that this is a first chart, if so how did you create it? Did you use some chart as a base?

**Comment by hickeyma** [comment]
I am asking because there is good content in the docs in getting started with charts. In case you haven't seen it, have a look at the [chart template guide](https://docs.helm.sh/chart_template_guide/#the-chart-template-developer-s-guide). It show how to create a chart using the `helm create` command.

**Comment by DavidPerezIngeniero** [comment]
Before asking, I always read the docs.
If my chart isn't ok, I expect to see an error message, like Chart.yaml has an error in line xx, not the error:
```
no available release name found
```
More tests:
```
# helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈ 
```
```
# helm install stable/mysql
Error: no available release name found
```

This makes clear, that the error isn't related to my chart.

**Comment by DavidPerezIngeniero** [comment]
Doing `helm reset` and then `helm init` again doesn't help.

**Comment by hickeyma** [comment]
Could you run this command `helm init --canary-image --upgrade` and try a chart install again?

**Comment by hickeyma** [comment]
Also, could you add the tiller log.

**Comment by DavidPerezIngeniero** [comment]
After solving [this problem](https://stackoverflow.com/questions/54289055/exporting-service-via-nodeport/54319874#54319874) with Kubernetes, Helm works ok. :-)

Helm is well documented and easy to understand.
Thanks for your support.
