### ISSUE TITLE
--set name={} produces collection with an empty string

### ISSUE THREAD

**Issue by justanr** [helm/helm#5200]
Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-eks-6bad6d", GitCommit:"6bad6d9c768dc0864dab48a11653aa53b5a47043", GitTreeState:"clean", BuildDate:"2018-12-06T23:13:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  aws eks

Other information: this chart is being invoked by terraform but I've managed to excluded terraform as the cause by testing with helm directly. However terraform will requires the list variable to be set and cause this issues.

Given a template like

```
kind: Service
apiVersion: v1
metadata:
  name: hello
spec:
  type: LoadBalancer
  {{- if .Values.service.allowed_cidrs }}
  loadBalancerSourceRanges:
    {{-  range .Values.service.allowed_cidrs }}
    - {{ . }}
    {{- end }}
  {{- end }}
# omitted ...
```

When I run `helm install --dry-run --debug --set service.allowed_cidrs={}`:

```
USER-SUPPLIED VALUES:
service:
  allowed_cidrs:
  - ""
```

Which is then transformed into:

```
kind: Service
apiVersion: v1
metadata:
  name: hello
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 
# omitted ...
```

Which causes the deploy to fail with: 

```
spec.LoadBalancerSourceRanges: Invalid value: "[]": must be a list of IP ranges. For example, 10.240.0.0/24,10.250.0.0/24 
```

I would expect to see:

```
USER-SUPPLIED VALUES:
service:
  allowed_cidrs: []
```

And:

```
kind: Service
apiVersion: v1
metadata:
  name: hello
spec:
  type: LoadBalancer
# omitted ...
```

Using `--set service.allowed_cidrs={0.0.0.0/0}` produces the expected output:

```
USER-SUPPLIED VALUES:
service:
  allowed_cidrs:
  - 0.0.0.0/0
```

As do multiple values in the collection (e.g. `--set service.allowed_cidrs={1.1.1.1/32,2.2.2.2/32}`).

Supplying an empty list literal in values.yaml produces the expected output:

```
service:
  allowed_cidrs: []
```

**Comment by hickeyma** [comment]
You should be able to run without setting to {} and in this case the cidrs do not exist and therefore it is equivalent to being empty. so just run as `helm install <chart>`.

**Comment by hickeyma** [comment]
From what I can see, the emptiness capability is provided by Go template conditionals. When you set `service.allowed_cidrs={}`, it interprets as being not empty. 

There was an issue #2600 which sent stale which might be applicable about providing an `isset` function in the Sprig library.

**Comment by hickeyma** [comment]
Ping @justanr. Any progress with this?

**Comment by justanr** [comment]
No progress, continuing to use the default value of `0.0.0.0/0` doesn't look like any commits or PRs are attached to this issue either. Not sure what is expected of me in this situation, not familiar enough with Go to confidently attempt to address the issue myself.

**Comment by mattfarina** [comment]
@justanr Have you tried doing a set like, `--set service.allowed_cidrs=`? There is nothing to the right of the `=`.

**Comment by hickeyma** [comment]
Thanks @mattfarina, good suggestion.

**Comment by justanr** [comment]
@mattfarina that would work if I was invoking helm directly. However it's being managed by terraform so I'm not sure it's possible. I'll give it a whack and see but I don't think terraform will be happy getting an empty string when it's expecting a list.

**Comment by DavidLei08** [comment]
Like this one

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
