### ISSUE TITLE
Helm chart install failed when install multiple times with CRDs

### ISSUE THREAD

**Issue by gyliu513** [helm/helm#5201]
We found this issue in federation v2 helm chart at https://github.com/kubernetes-sigs/federation-v2/issues/557

The use case is as following:
1) Federation v2 helm chart include some CRDs.
2) Install the federation v2 helm chart on my k8s cluster in namespace1, install succeed and all CRDs are installed.
3) Install the federation v2 helm chart on my k8s cluster in namespace2, install failed due to CRDs already exist.

Does there are any solutions to make the CRDs can be shared between different releases?

**Comment by gyliu513** [comment]
I was thinking an option as this: Move all of the CRDs out and make a separate chart for CRDs, then use a flag like `crds.enabled` to control install CRD or not, comments?

**Comment by gyliu513** [comment]
Great, thanks @calind , this is exactly what I want to do, I will use this solution as you proposed ;-)

**Comment by gyliu513** [comment]
@calind any comments for how to handle the delete case? For CRD, due to this helm [issue](https://github.com/helm/helm/issues/4440), the CRDs cannot be deleted
when delete helm release, so the end user need to delete all of CRDs manually. But if this bug got fixed, how to handle this cases when multiple helm releases share same CRD?

**Comment by calind** [comment]
Yup, the deletion is manual, but from my experience that is the desired behavior anyway. The lifecycle of the CRD is very sensible (think that deleting a database crd for example would delete the databases themselves) and should be clearly be managed outside the lifecycle of the helm release.

Installing CRDs with helm is very convenient for the end users and so far can be safely achieved in the current helm state.

Updating I think can be hacked away with a Job hook maybe or having controller reconcile it’s crds for example.

For deletion on the other hand, I think it must be made explicit and exposed as a flag like `helm delete --purge-crds`

**Comment by gyliu513** [comment]
@calind thanks! +1000 on `helm delete --purge-crds`, does helm have some plan to enhance helm support this?

**Comment by bacongobbler** [comment]
If the community feels like taking a crack at this we'd love a PR!

**Comment by gyliu513** [comment]
Thanks @calind  OK, let me keep this open to get more comments.

**Comment by ian-howell** [comment]
I can take a shot at this. We want the behavior created by @calind's response to be default?

**Comment by neeraj-laad** [comment]
@calind This solution looks promising, however we are checking for the group (clusterregistry.k8s.io) to be present in .Capabilities.APIVersions. 

Is there a way to check for the specific name (clusters.clusterregistry.k8s.io)?

**Comment by bacongobbler** [comment]
`.Capabilities.APIVersions.Has $version` indicates whether a version (batch/v1) is enabled on the cluster.

Does that help?
