### ISSUE TITLE
Error: This command needs 2 arguments: release name, chart path in helm upgrade command

### ISSUE THREAD

**Issue by kumbamashwin** [helm/helm#5209]
Output of `helm version`: "v2.12.2"
--

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersio n:"go1.11.2", Compiler:"gc", Platform:"windows/amd64"}                                                                                                                                           Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.11-eks", GitCommit:"6bf27214b7e3e1e47dce27dcbd73ee1b27adadd0", GitTreeState:"clean", BuildDate:"2018-12-04T13:33:10Z", Go Version:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
--
Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS

Error: This command needs 2 arguments: release name, chart path

i am running kubernetes and trying to create a test environment and for this changing the command helm upgrade , am getting above error

**Comment by kumbamashwin** [comment]
helm upgrade ./jenkins-helm/''' + serviceName + ''' -f values-test.yaml ''' + serviceName + '''-test --install --namespace ''' + testClusterNamespace + ''' ./jenkins-helm/''' + serviceName + ''' --set image.repository="5339606688788.dkr.ecr.us-east-1.amazonaws.com/con/$SERVICE_NAME" --set image.tag=$BUILD_NUMBER-$COMMIT_ID --set tracing.enabled=true

usng above command i got that error

**Comment by kumbamashwin** [comment]
we are deploying an application, and we need it to do for dev and test environments, and am doing it for test environment now. in this process, the command which i posted was the last one to deploy to eks cluster, but its getting failed with the error mentioned.


>  **helm upgrade ''' + serviceName + ''' --install --namespace ''' + devClusterNamespace + ''' ./jenkins-helm/''' + serviceName + ''' --set image.repository="533960668118.dkr.ecr.us-east-1.amazonaws.com/converse3/$SERVICE_NAME" --set image.tag=$BUILD_NUMBER-$COMMIT_ID --set tracing.enabled=true
>             #echo $?**

above command we are using it to deploy to dev name space, and i want to install to test name space, and i want to use the another values.yaml file called values-test.yaml  file in the same jenkins-helm/backend_adminauthenticationservie  directory to get it run 
 so i am using the command 

**

> helm upgrade ./jenkins-helm/''' + serviceName + ''' -f values-test.yaml ''' + serviceName + '''-test --install --namespace ''' + testClusterNamespace + ''' ./jenkins-helm/''' + serviceName + ''' --set image.repository="5339606688788.dkr.ecr.us-east-1.amazonaws.com/con/$SERVICE_NAME" --set image.tag=$BUILD_NUMBER-$COMMIT_ID --set tracing.enabled=true

**

but i am getting that error.

can some one help

**Comment by kumbamashwin** [comment]
> Hard to understand the upgrade command above.
> 
> If you have installed and when you want to upgrade , set whatever value you want to change and the rest of the values will remain the same from previous. Example where you set the service type: `helm upgrade <realease_name> <chart> --set service.type=NodePort`
> 
> If you could explain more what you are trying to do that might help.

Thanks dear friend, replied with more info,

**Comment by bacongobbler** [comment]
More information can be found here: https://docs.helm.sh/using_helm/#helm-upgrade-and-helm-rollback-upgrading-a-release-and-recovering-on-failure

**Comment by hickeyma** [comment]
@kumbamashwin did you get the upgrade command working?

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

**Comment by Mr-Saikiran** [comment]
for me it was extra spaces with helm upgrade. 

If you are using multi line command with backslash ( \ ), Ensure there are no spaces after the backslash.
