### ISSUE TITLE
Unable to install helm charts with cluster using Flannel; dial tcp 10.96.0.1:443: connect: no route to host

### ISSUE THREAD

**Issue by asachs01** [helm/helm#5211]
Output of `helm version`:
```
$ helm version
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Baremetal
Networking: Flannel

Error output:
```
$  helm install stable/nginx-ingress --name my-nginx --debug
[debug] Created tunnel using local port: '46639'

[debug] SERVER: "127.0.0.1:46639"

[debug] Original chart version: ""
[debug] Fetched stable/nginx-ingress to /home/asachs/.helm/cache/archive/nginx-ingress-1.1.5.tgz

[debug] CHART PATH: /home/me/.helm/cache/archive/nginx-ingress-1.1.5.tgz

Error: Get https://10.96.0.1:443/version?timeout=32s: dial tcp 10.96.0.1:443: connect: no route to host
``` 

Details:
Whenever I attempt to install a helm chart, I receive text similar to what's above. I've attempted this on the k8s master and on a workstation, and both yield the same result. What's curious to me is that helm continues to use 10.96.0.1, rather than the Flannel network. I've tried tearing down and rebuilding the cluster, but I'm at my wit's end. Would anyone happen to have any suggestions?

**Comment by bacongobbler** [comment]
Behind the scenes, Helm is doing a `kubectl port-forward` to Tiller. Once the connection to Tiller has been established, Tiller then talks back to the API to render charts uploaded from Helm.

The error logs here seems to indicate that Helm has obtained a connection to tiller through the Kubernetes API, but from inside the cluster, tiller cannot establish a connection to the API. "No route to host" usually means the DNS resolution is failing or the internal network cannot reach the API. I think this may have something to do with Flannel, so I'd start checking there.

**Comment by asachs01** [comment]
Mmm, good call @bacongobbler . I'll go down that route and see what I can find.

**Comment by mosaicwang** [comment]
I meet the same question. **k8s and tiller version is same as asachs01**.
I installed flannel from 0.9.1 to 0.11, execute `helm ls` all report 
```
Get https://10.96.0.1:443/api/v1/namespaces/kube-system/configmaps?
labelSelector=OWNER%!D(MISSING)TILLER: dial tcp 10.96.0.1:443: connect: no route to host
```

**Comment by asachs01** [comment]
@mosaicwang I did, but it involves _not_ using Flannel for my CNI. Instead, I'm running weave now. This seems to have resolved the problem and definitely confirms what @bacongobbler called out. I'm fairly confident that this is a Flannel issue and will close this one off.

**Comment by panteparak** [comment]
I too agree that this is a flannel related issues, switched to Kube-router and everything works as great

**Comment by VGerris** [comment]
Did anyone fix this or report it to CoreOS / flannel? I have the same issue. WeaveNet had other issues for me, like my nodes not being routable at all. And Calico doesn't even have the dashboard working after simple setup- Flannel worked otherwise and indeed with Helm 3, but I had issues install cert-manager with that. A solution or way to troubleshoot would be appreciated.

**Comment by sadiq1425** [comment]
I removed flannel from kuberenetes and installed weave but still i get the same error . Is there any other thing i am missing .

[root@master ~]# helm install jupyterhub/jupyterhub     --version=v0.6     --name=tiller     --namespace=tiller     -f config.yaml
Error: Get "https://10.96.0.1:443/version?timeout=32s": dial tcp 10.96.0.1:443: connect: no route to host
