### ISSUE TITLE
Feature: better image management

### ISSUE THREAD

**Issue by kfox1111** [helm/helm#5212]
In helm 2, images/tags are just variables that can be overridden.

This means though that users typically have to deal with finding what images are in use, what values are used to define them, update them as needed, etc all in a very manual way.

I think for v3 we need to have some more first class support for images.

I think of there being some kind of image metadata stream that has some details about what versions are available, and possibly some kind of metadata about what kind of update it is. Maybe its trivial and doesn't need automatically applying. maybe its a CVE related fix and should be deployed asap.

Rather then specify an image/tag, perhaps a more pip like requirements pattern for an image can be specified, and, given the helm chart and some image stream metadata, helm can pick an appropriate image/tag to use.

This does for images, what helm does for charts. enables a discoverable upgrade paths. Since two different charts can contain the same image, this makes managing updating all the possible effected charts easier.

This could include some cli tooling around:
 * given a release, check if there are any image updates available
 * flag to go ahead and upgrade it if there are
 * list out image update reasons for release related images
 * upgrade all releases that have image cve related reasons specified.
 * etc

/label v3

**Comment by bacongobbler** [comment]
I don't follow the use case. Can you provide a more concrete example how this would look?

**Comment by kfox1111** [comment]
The idea isn't fully fleshed out. It needs more work. But there is a major unsolved issue with containers currently in that most of the tooling assumes development is happening faster then dependencies are getting updated. This holds true of software that is early in its lifecycle. As it matures though, development slows down and dependencies get updated more frequently then the software. This means relying on developers to push out newer versions becomes less reliable. There is a lot of existing software that works well in kubernetes that is already late in its lifecycle so isn't getting updated frequently.

For a more concrete example... This is a repo I've been building:
https://github.com/pnnl-miscscripts/miscscripts

I released a console chart: 
https://github.com/pnnl-miscscripts/miscscripts/tree/master/charts/charts/console

It needs an up to date container with ipmitool in it.

ipmitool doesn't get updated frequently, and the ssl library is probably the most frequently updated piece of software in the stack.
The container looks like:
https://github.com/pnnl-miscscripts/miscscripts/blob/master/containers/ipmitool/Dockerfile

Today, if you want to ensure that users of the console chart get updated releases, you need the console chart to be updated with a pointer to the new container whenever the container changes. this requires a bunch of plumbing to have ipmitool container drive console chart builds.

I'm thinking one part of it would be to have some kind of repo for image updates.
like, a document that has the list of versions of images the ipmitool container. the helm chart could reference this instead of having an explicit image/tag. Then, the chart wouldn't need to be updated every time a minor update to a referenced image gets updated but helm could still determine and relay to the user that an update to a release is available.

Also, one feature traditional package managers have that helm lacks is a way to upgrade multiple things on the system.

We should have an equivalent of 'yup upgrade'. This would try and upgrade all releases rather then have to manually tell each release to be upgraded.

**Comment by kfox1111** [comment]
Another issue related to this is that of disconnected installs. Certain sites have networks that do not have internet connectivity.  Package managers such as yum/apt make it relatively easy to replicate a repository, take it offline and then install from the replica.

The way helm currently codes this into the charts, makes it difficult to find all instances of images, replicate them, and update them to point to the new repository.

usually this is done via values that are repo/tag. but there is no way to scan through the values file and determine programaticaly which values actually are images. So writing a tool that would replicate images to a repo based on giving it a chart isn't easy/possible.

The chosen two values, repo and tag, also don't have enough info to allow it to be easily updated by a user. say I have an image:
```yaml
repo: docker.io/pnnlmiscscripts/debug-toolbox
tag: 1.0.0-1
```

replicating it should replace the server, in this case docker.io and replace it with the private one. Since this is one key, its not easy for a user to replace just that part of the image without tryign to parse out other parts.

So, I'd recommend these values instead:
```yaml
server: docker.io
prefix:
org: pnnlmiscscripts
repo: ipmitool
tag: 1.0.0-1
```

This would allow a user quickly to move the image to another server, a different org, while keeping the repo name.

You could switch all servers that are docker.io with myprivate.thingy, while overriding prefix to be /sometohterthing/ for just a few images, etc.

**Comment by bacongobbler** [comment]
closing as inactive. See also #7154.
