### ISSUE TITLE
helm inspect --devel missing

### ISSUE THREAD

**Issue by NissesSenap** [helm/helm#5213]
Output of `helm version`: 
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.9", GitCommit:"e6ab4ee54f71e7a403cc733534bab86fd959ecb7", GitTreeState:"clean", BuildDate:"2018-10-16T12:14:47Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.3-1+fee411aca93f0e", GitCommit:"fee411aca93f0e786995cc125cf8f9783484f958", GitTreeState:"clean", BuildDate:"2018-12-04T06:45:24Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  kubernetes self deployed

Found a missing feature.
The chart that i currently install is only available in devel mode and i would like to be able to inspect it before installing it.
helm inspect --devel
Error: unknown flag: --devel

just like i use:
helm install --devel 

Sadly i don't know go so i can't provide a pull request.

**Comment by bacongobbler** [comment]
closing as inactive.
