### ISSUE TITLE
proxyconnect tcp: net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by frosch95** [helm/helm#5220]
Output of `helm version`:
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Error: Get https://xxxxxxxxxxxxxxxx.westeurope.azmk8s.io:443/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: proxyconnect tcp: net/http: TLS handshake timeout

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS

Hi,
I have some difficulties using helm at the company. We are behind a proxy. We started with our own squid proxy and helm worked fine with the windows settings of http_proxy and https_proxy.

Our company switched from our own proxy to a service called zscaler. And now we get these TLS handshake timeout messages with helm, but kubectl works.

**Error: Get https://xxxxxxxxxxxxxxxx.westeurope.azmk8s.io:443/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: proxyconnect tcp: net/http: TLS handshake timeout**

We have no idea what could go wrong and where the error message does come from. --debug does not bring any additional information. 
And why is kubectl working and helm not?

It would be good to improve the logging and differ between own error messages and messages that come from other somewhere else (http client, ...)

Thanks for your help!
Best regards,
Andi

**Comment by frosch95** [comment]
First I should notice that I have changed the path to the kubectl.exe from the above version, which was part of the docker desktop for windows to the newer version, which was installed by azure cli

_Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"windows/amd64"}_

With the newer version at first place in the path, the same error happens.

After that change the IT appartment of my company has found a solution.
I used the **https_proxy** environment variable with **https://** url to our proxy. This works for most of the tools we are using but not for helm or the newer kube. They seem to have some problems with the TLS handshake. We switched from **https://** to a **http://** url (e.g https_proxy=http://myproxy) and now everything works fine.

**Comment by Jefry-nolastname** [comment]
> First I should notice that I have changed the path to the kubectl.exe from the above version, which was part of the docker desktop for windows to the newer version, which was installed by azure cli
> 
> _Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"windows/amd64"}_
> 
> With the newer version at first place in the path, the same error happens.
> 
> After that change the IT appartment of my company has found a solution. I used the **https_proxy** environment variable with **https://** url to our proxy. This works for most of the tools we are using but not for helm or the newer kube. They seem to have some problems with the TLS handshake. We switched from **https://** to a **http://** url (e.g https_proxy=http://myproxy) and now everything works fine.

Thanks!!!!!!!!!
