### ISSUE TITLE
helm install --force fails

### ISSUE THREAD

**Issue by tjerkw** [helm/helm#5221]
Output of `helm version`:
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}

Output of `kubectl version`: 
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
EKS

When running "helm install --force" it complains that i cant delete a chart because its not there. But its there in FAILED state. Its just not deleting it.

```
helm status:
t-test-circleci-branch              	1       	Mon Jan 28 09:48:49 2019	FAILED  	tiqetsweb-0.1.0           	t-test-circleci-branch
```

kubectl install --force

```

Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
 	Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: connect: connection refused
 ...Successfully got an update from the "stable" chart repository
Update Complete. \u2388Happy Helming!\u2388
Saving 2 charts
Downloading postgresql from repo https://kubernetes-charts.storage.googleapis.com/
Downloading redis from repo https://kubernetes-charts.storage.googleapis.com/
Deleting outdated charts
UPGRADE FAILED: Upgrade --force successfully deleted the previous release, but encountered 1 error(s) and cannot continue: release "t-test-circleci-branch": object "" not found, skipping delete

```

But t-test-circleci-branch is the one it shoudl be removing.

**Comment by bacongobbler** [comment]
Hey @tjerkw, can you please provide steps to help reproduce this issue? I cannot understand how the chart got into this state based upon the information laid out in this ticket. A set of instructions/steps on how to reproduce the issue would be helpful. Thanks!

**Comment by grebois** [comment]
same problem here

**Comment by adityaguru149** [comment]
> 
> 
> Hey @tjerkw, can you please provide steps to help reproduce this issue? I cannot understand how the chart got into this state based upon the information laid out in this ticket. A set of instructions/steps on how to reproduce the issue would be helpful. Thanks!

Hey @bacongobbler 

So you could recreate the issue by following:
1 Make a deployment where there is atleast one pod failure (say ImagePullBackOff)
2 Try to helm upgrade --install --force on that release.

You would expect the old release to be removed or updated with versioning(preferably).

**Comment by bacongobbler** [comment]
closing as inactive.
