### ISSUE TITLE
additional feature to roll back to last successful release rather than just last release

### ISSUE THREAD

**Issue by burnettk** [helm/helm#5237]
To roll back to the previous release you can use `helm rollback [RELEASE] 0` as documented [here](https://github.com/bacongobbler/helm/blob/4fd32da617acbc3b613c3e3d52f7df4422753774/docs/helm/helm_rollback.md).

I don't have a strong opinion on the actual command to use. `helm rollback [RELEASE] LAST_SUCCESSFUL` would work.

See some history at https://github.com/helm/helm/issues/1796, where [some](https://github.com/helm/helm/issues/1796#issuecomment-388645454) people [seem](https://github.com/helm/helm/issues/1796#issuecomment-279881672) to really want "last successful" while others are quite satisfied with "last."

Current deployment script pseudocode that could be improved with this feature:

````
# the max=X is here because we were seeing: StdErr: Error: grpc: received message larger than max (5780747 vs. 4194304)
# hopefully the last 10 releases includes a successful release, since we haven't yet implemented pagination
recent_releases = helm history --max=10 [RELEASE] 

last_successful_release = parse_releases_to_find_last_successful(recent_releases)
if helm upgrade --install --wait [RELEASE] [CHART] == EPIC_FAIL {
  helm rollback --wait [RELEASE] last_successful_release
}
````

**Comment by bacongobbler** [comment]
Does https://github.com/helm/helm/pull/5115 solve your use case?

**Comment by srinivasev** [comment]
Hi @bacongobbler,
Can you please check my latest observations regarding helm rollback <release-name> 0 in the below pull request?
https://github.com/helm/helm/pull/5115#issuecomment-825478034
