### ISSUE TITLE
Consider making Helm an opinionated CNAB package builder

### ISSUE THREAD

**Issue by simonferquel** [helm/helm#5242]
Similarly to what is currently happening with github.com/docker/app, it would be very nice for Helm to become an opinionated tool building CNAB packages. This can be done without changing the user-experience of the Helm tool - as the experiments around docker/app + CNAB proved - but it would provide some very interesting benefits:
- Compatibility with the whole CNAB ecosystem (which is obviously sparse for now, but it should grow)
- Composability with projects like Porter: Combine a Helm chart + a terraform installer to provision a cluster + a CNAB deploying managed cloud services like managed databases, Lambdas, etc.)
- Tools/Package versioning consistency (once the CNAB package is built, it comes with its own copy of the Helm runtime, so we don't need to ensure the same degree of Backward compatibility from one version of the tool with existing packages - this is a very huge benefit of the concept of an invocation image)
- Uniform registry support: sharing a Helm Chart would be the same thing as sharing a CNAB package, so we don't have to duplicate the effort on that subject.

Ping @bacongobbler :)

**Comment by jdolitsky** [comment]
@simonferquel could you elaborate a bit on what this might entail? Trying to wrap my head around what this means.

> Compatibility with the whole CNAB ecosystem ... Composability with ...

I thought the whole point of CNAB was to be able to install anything regardless of format?  :)

> Tools/Package versioning consistency ... Uniform registry support ...

IMO - uniform registry support can come in the form of some Go SDK that matches the spec being 
 [discussed on OCI-dev mailing list](https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/oguystbnnw4). Allowing Helm and CNAB to come up with their own media types/layers would actually exercise the spec to work across multiple package types (not just CNAB).

**Comment by bacongobbler** [comment]
Hey @simonferquel, thanks for bringing this discussion topic to the issue queue. I'd like to take a stab at gathering your thoughts on the subject.

> * Compatibility with the whole CNAB ecosystem (which is obviously sparse for now, but it should grow)

> * Composability with projects like Porter: Combine a Helm chart + a terraform installer to provision a cluster + a CNAB deploying managed cloud services like managed databases, Lambdas, etc.)

These use cases certainly could be quite useful for users wanting alternative ways to build a Helm chart. My concern here is exactly what you brought up: the CNAB ecosystem is *very* early and very sparse. The CNAB specification hasn't hit 1.0 yet, and the spec can change many times as the spec is exercised and more use cases come up. This becomes a major concern for a project that is primarily focused on stability (Helm).

For other readers new to the CNAB ecosystem, [Porter](https://porter.sh/) provides a YAML file that understands how to transform actions ("install the Helm CLI", "create a cluster on Azure", "run `helm install`") into a bundle. It's essentially an opinionated `docker build`, but for CNABs.

> * Tools/Package versioning consistency (once the CNAB package is built, it comes with its own copy of the Helm runtime, so we don't need to ensure the same degree of Backward compatibility from one version of the tool with existing packages - this is a very huge benefit of the concept of an invocation image)

I'm not too sure this has ever been a concern for Helm. We've always maintained a backwards compatibility guarantee for Helm Charts all the way from Helm 2.0.0 to today (2.12.3). Ops teams can install a Helm chart that was built using Helm 2.0.0 using Helm 2.12.3.

What other kinds of backwards compatibility concerns do you believe may come up here?

> * Uniform registry support: sharing a Helm Chart would be the same thing as sharing a CNAB package, so we don't have to duplicate the effort on that subject.

I think @jdolitsky already answered this in his earlier comment. The OCI allows anyone to come up with their own media types, so no effort here is being duplicated. The [oras project](https://github.com/deislabs/oras) is the library both CNAB and Helm community members are working on to share that effort of pulling/pushing custom media types.

A few members here from the Helm org (as well as a few CNAB members, myself included 😄) are working with the OCI to [come up with a proposal](https://groups.google.com/a/opencontainers.org/forum/#!msg/dev/oguystbnnw4/mKJK4IzSDAAJ) on how non-Docker tools should pull and push custom media types.

In other words, I believe we're already on track to reducing the duplication of effort between Helm and CNAB (and the Nth project that wants to push their custom media types to an OCI registry).

I'm also going to add my own question to the thread here:

> Who is willing to take the action item?

There have been lots of great feedback on things where Helm could change or improve, however we're finding out there's not a whole lot of contributors willing to work on them. Replacing Helm Charts with CNAB is a *very* large ask, and not something we can take on as a simple TODO. We need someone who is willing to experiment with CNAB, willing to do some experiments, provide feedback to the core maintainers on how the transition would look, write up proposals that detail the implementation and its benefits/tradeoffs WRT Helm 3, and implement the proposed solution.

My feeling is that given the large amount of whiteboarding that'd be required to introduce CNAB to Helm, we should not be building CNABs as part of Helm. However I would love to see this:

> If we had a first class subcommand `helm build` that does exactly that, that would make a Helm-chart a self-installable CNAB package (with the bonus effect to have its installer runtime being exactly the same as the builder toolchain,

`helm build` would be a great fit for a plugin to exercise this experiment, and would be a great way to tie in CNAB into the Helm ecosystem without making any drastic changes to the underlying package format of a Chart. If anyone's interested in doing some dabbling with CNAB, this may be a great first place to start.

**Comment by simonferquel** [comment]
@bacongobbler About backward compatibility, the main advantage, is that you can bring new runtime features (e.g. new hooks, or even a new hook scripting language) without having ops to update their toolchain. You can even introduce runtime breaking-changes without worrying about how existing packages will run (as they embed their own copy of the runtime with them). For Helm, I agree it might not be critical (related to the maturity of the project), but it is a big deal for docker-app.

I agree that to make a less drastic move, having it first introduced as a plugin with commands like `helm cnab bundle` and `helm cnab push` would clearly be a very good option.

**Comment by bacongobbler** [comment]
Closing this as a good plugin proposal for the community to write. We can re-open this discussion if there's more interest from the community, but I haven't heard of any compelling use cases at this time where it'd be useful to consider making it part of the core. Thanks!
