### ISSUE TITLE
Helm deletes secrets too soon

### ISSUE THREAD

**Issue by Jamie-sas** [helm/helm#5247]
Output of `helm version`:

Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

When adding a post-delete hook to a chart, with a secret to pull it from a private repo, the hook cannot run because Tiller has already deleted the secret by the time it tries to pull the post-delete hook image.

Helm should keep secrets around at least until it has loaded all images, including all hook job images.

If this is fixed in a later version of Helm, please say so and I'll see about getting a later version installed.

**Comment by bacongobbler** [comment]
@Jamie-sas would you mind verifying if this is still a bug with a more recent version of Helm?

**Comment by bacongobbler** [comment]
> When adding a post-delete hook to a chart, with a secret to pull it from a private repo, the hook cannot run because Tiller has already deleted the secret by the time it tries to pull the post-delete hook image.

I think this is kind of intended by design, though I can see why it would occur and why this would be frustrating. By design, a `post-delete` hook runs after everything has been deleted, and therefore should not assume that it can access any resources created from the chart itself.

Perhaps a `pre-delete` hook may be better suited here for your use case?

**Comment by Jamie-sas** [comment]
I am attempting to get the OK to install a more recent version of Helm, as it is not entirely my decision.

Yes, switching to a pre-delete hook instead does work, but in my opinion shouldn't be necessary.  If Helm supports pulling images from private repos, it should support that for ALL images.  There is also the question of whether or not everything has quiesced enough for a pre-delete to work, where a post-delete definitely does.  I'm trying to figure out how to check that enough to satisfy my own curiosity.

At the very least, if you don't plan to make this work, it should be very clearly documented as an exception.

**Comment by bacongobbler** [comment]
closing as inactive.
