### ISSUE TITLE
helm install --wait, should wait for the ingress DNS allocation to get complete

### ISSUE THREAD

**Issue by vineetmimrot** [helm/helm#5256]
With current functionality of _helm install --wait_, it waits until all Pods, PVCs, Services, and minimum number of Pods of a Deployment are in a ready state before marking the release as successful or timeout. 
But it doesn't wait for the DNS allocation in case of ingress. Through kubectl I have to specifically run the following command to wait for its completion:
kubectl get ingress -n <namespace> --watch=true

In my opinion _helm install --wait_, should also wait for the ingress DNS allocation to complete.

**Comment by phil-lgr** [comment]
I use Helm to auto deploy builds from branches on my CI and I haven't found a way to wait until the hostname is resolvable (load balancer is set up)
My sequence looks like this:

```bash
helm install --set appVersion=ci-$npm_package_version-$CIRCLE_BUILD_NUM --name deploy-ci-$CIRCLE_BRANCH --namespace erp-app-ci-$CIRCLE_BRANCH --wait config/helm/erp-app

external_ip=""; 
while [ -z $external_ip ]; do echo "waiting for endpoint..."; 
external_ip=$(kubectl get ingress -n erp-app-ci-$CIRCLE_BRANCH -o=jsonpath='{.items[*].status.loadBalancer.ingress[0].hostname}'); [ -z "$external_ip" ] && sleep 10; 
done; 
echo "endpoint ready " && echo $external_ip; export APP_URL=$external_ip

wget --retry-connrefused --no-dns-cache --waitretry=10 --read-timeout=10 --timeout=200 -t 90 http://$APP_URL
```

the wget command fails since the host is not reachable... I'm wondering if someone had encountered the same problem 😬

**Comment by trajakovic** [comment]
Without flag where I'd like to wait for deployment/service (old behaviour), but not for ingress, this feature renders helm pretty useless (and not backward compatible with 2.14.x versions) where I left on purpose "old" ingresses without backing controller (now using ambassador api gw).

Now all builds with --wait fail, since ingress never becomes ready....

**Comment by bacongobbler** [comment]
We removed waiting for ingress objects in #6792. It turns out that there is [no standard for checking the status of ingress objects](https://github.com/helm/helm/issues/6751#issuecomment-546416633), so #5264 had to be pulled out.

**Comment by trajakovic** [comment]
Oh, ok @bacongobbler,  thank you for info.
