### ISSUE TITLE
Helm multiple environments best practices

### ISSUE THREAD

**Issue by ianseyer** [helm/helm#5257]
Hi!

I am wondering what recommended practice is for maintaining values files for several environments with overlapping values.

For example: we have a directly `values/` with each environment's values file [`sandbox`, `prod`, `stage`, `dev`, etc].

There is quite a bit of overlap between the files, and I am looking for a way to 
1. Not have to repeat newly-added configuration values across each environment's values file
2. Avoid duplication of values across multiple values file.

I imagine that I can solve #2 by creating a shared values file that gets overridden by environment-specific values if specified (e.g. `helm install -f shared.yaml -f environment-specific.yaml`.

Is there a best practice I should be using here?

**Comment by hickeyma** [comment]
You could try [helmfile](https://github.com/roboll/helmfile) or [orca](https://github.com/nuvo/orca)

**Comment by maorfr** [comment]
I believe that what you are describing is a best practice.
If you use `values.yaml` as your "shared" values, you will not even have to specify it.

Hope this helps!

**Comment by granite-cloud** [comment]
Yes I have been hunting for some kind of "standard" guidance around a best practice for the very common design of needing to have environmental specific data as well as common data. You can find people doing all kinds of things but it looks to fit a couple standard patterns that look like this:

1) a chart will have a values file per environment. This creates nice separation and is easy to read but creates a lot of "rinse lather repeat" in terms of the overlap that is almost always present to some degree between envs.

2) try to create single values/templates that accounts for type of scenario related to unique parameters per environment  that may be required for a given micro-service..  This seems like it would be a pain and could get more and more difficult depending on your environment.

I am sure there are arguments for both ( I happen to prefer #1) but I would love to know what is the "official" best practice or is there a better way that is a hybrid.  This seems to be something that I see in many different tools where there is a choice between violating DRY principles to create separation or trying to create a catch all for everything but making life easier for the consumer of the service and no "rinse lather repeat" of code..

If anyone can shed some light here on a good potential design to follow or where some documentation may be it would be much appreciated. Unfortunately in my search I cant find anything concrete and only the many different variations of what I mention above that folks are using.

Thanks!

**Comment by adrianmatei-me** [comment]
See [this link](https://github.com/helm/helm/blob/ecef026b68a23f0c1399d98425134ce837126831/docs/using_helm.md#customizing-the-chart-before-installing)

**Comment by ale222** [comment]
I had the same question, until I found this - https://blog.mimacom.com/dry-kubernetes-with-helm/

**Comment by lboclboc** [comment]
> I had the same question, until I found this - https://blog.mimacom.com/dry-kubernetes-with-helm/

Did not really answer the original question did it?

**Comment by jmcgeheeiv** [comment]
CodeFresh published a straightforward approach: https://codefresh.io/helm-tutorial/helm-deployment-environments/

**Comment by fkurz** [comment]
If you don't have a problem with installing YQ, there's a simple way to do this using the merge operator `*`: 

```bash
yq '. *= load("environment-specific.yaml")' shared.yaml \
    | helm install --dry-run mychart . -f -
```

This command will, merge the values in `environment-specific.yaml` into `shared.yaml` overriding any shared properties with the environment-specific ones and then pipe it into `helm install`.

I wrote a blog post about it: https://friedrichkurz.me/blog/2022/06/18/keeping-environment-specific-helm-configuration-dry/ Take a look, if you want.

**Comment by djeang** [comment]
Is it a good practice to put _values-dev.yaml,_ _value-test.yaml_ and _values-prod.yaml_ in the the same directory than values.yaml ?
