### ISSUE TITLE
Centralized require directives

### ISSUE THREAD

**Issue by RikuXan** [helm/helm#5262]
I have a helm chart that necessitates a user supplying certain values, for which there are no sane default values.

While I have found that I can mark certain variables as mandatory to declare, by leaving them empty in my `values.yaml` and then including them in my templates with `required`, I'm still wondering where exactly to declare them as required. Many of these values occur in multiple spots throughout my chart so that declaring them as required everywhere seems unnecessarily verbose, while declaring them in one specific spot seems arbitrary and prone to errors (e.g. the specific part of a chart where the value is declared required gets deleted or restructured and so the value being mandatory is lost as well).

Is there a sensible way to declare the mandatoriness of all relevant values in one spot? I could imagine writing a helper `tpl` file declaring all the required values, but I am unsure on how to include the template and then throwing the results away (as I'd imagine the block of variables cannot be sensibly parsed by Kubernetes)

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
