### ISSUE TITLE
Timeline for secret storage backend to graduate from beta

### ISSUE THREAD

**Issue by tylerstapler-wf** [helm/helm#5265]
The documentation lists the secrets tiller storage backend as beta. https://docs.helm.sh/using_helm/#storage-backends

It goes on to say:
> Currently, if you want to switch from the default backend to the secrets backend, you’ll have to do the migration for this on your own. When this backend graduates from beta, there will be a more official path of migration

I was curious, when this backend will be considered stable?

Thank you!

**Comment by hickeyma** [comment]
This should be supported in [v3 state management](https://github.com/helm/community/blob/master/helm-v3/003-state.md).

**Comment by tylerstapler-wf** [comment]
Thanks @hickeyma!

**Comment by fabianhjr** [comment]
Hi @tylerstapler-wf, per #5695, it looks like tiller secrets storage is about to be deprecated.

**Comment by tylerstapler-wf** [comment]
@fabianhjr, Thanks for the update!

**Comment by bacongobbler** [comment]
It is not planned to be deprecated.

**Comment by fabianhjr** [comment]
> the removal of Tiller

Sorry I misread, it is going to be decoupled from helm?

**Comment by bacongobbler** [comment]
Helm still needs to store release metadata. The removal of tiller just moves the rendering into the Helm CLI itself. It doesn't remove Tiller's functionality.

More info here: https://helm.sh/blog/helm-3-preview-pt2/
