### ISSUE TITLE
Add kind_sorter support for RoleList, ClusterRoleList, RoleBindingList, ClusterRoleBindingList

### ISSUE THREAD

**Issue by sebosp** [helm/helm#5267]
## Background
I have a tiller segregated to kube-system following docs/rbac.md
[example-deploy-tiller-in-a-namespace-restricted-to-deploying-resources-only-in-that-namespace](https://github.com/helm/helm/blob/master/docs/rbac.md#example-deploy-tiller-in-a-namespace-restricted-to-deploying-resources-only-in-that-namespace)

To be able to install Prometheus Operator 1.5.1, I added a lot of permissions to kube-system's Tiller (kube-state-metrics, prometheus node exporter, Grafana's kiwi sidecar watch ConfigMaps, etc).

Eventually the permissions are good enough for PrometheusOperator.
I try to install it:
`helm install -n prometheus-operator --tiller-namespace kube-system --namespace=kube-system stable/prometheus-operator`
Error: release prometheus-operator failed: roles.rbac.authorization.k8s.io "prometheus-operator-prometheus" not found

This Role is part of a RoleList in `charts/stable/prometheus-operator/templates/prometheus/role-specificNamespace.yaml`
If I try the above command multiple times it will eventually work as it seems it adds roles one by one even tho the whole process fails.

Output of `helm version`:
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:39:52Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-eks-6bad6d", GitCommit:"6bad6d9c768dc0864dab48a11653aa53b5a47043", GitTreeState:"clean", BuildDate:"2018-12-06T23:13:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS EKS, but shouldn't be tied to a specific provider.

I suspect this is because the RoleList, ClusterRoleList, RoleBindingList, ClusterRoleBindingList are not part of `pkg/tiller/kind_sorter.go`

**Comment by hickeyma** [comment]
#5748 now merged.
