### ISSUE TITLE
Helm commands return random numbers when run in bash

### ISSUE THREAD

**Issue by declanmc** [helm/helm#5270]
It looks like I have an issue with the Helm client when I am running it in bash on WSL. When I run any helm command all I get back is a series of random numbers

![image](https://user-images.githubusercontent.com/10504666/52355044-7b2bbb00-2a29-11e9-884c-938b1c9f1ba9.png)

The install was previously working, and I have tried to reinstall deleting the existing home directory, downloading the latest binary and moving that to the Helm home dir, but I get the same thing.

I can't provide the output of the helm version command as it will not run

**Comment by bacongobbler** [comment]
Hi @declanmc, would you mind removing that installation of Helm and try re-installing it? If you wouldn't mind posting the instructions you followed to install Helm, that would be helpful to try and reproduce. Thanks!

**Comment by bacongobbler** [comment]
For what it's worth, I just tried installing Helm on WSL and had no issues.

```
bacongobbler@ULTRALISK:~$ wget https://storage.googleapis.com/kubernetes-helm/helm-v2.12.3-linux-amd64.tar.gz
--2019-02-06 08:22:51--  https://storage.googleapis.com/kubernetes-helm/helm-v2.12.3-linux-amd64.tar.gz
Resolving storage.googleapis.com (storage.googleapis.com)... 172.217.14.240, 2607:f8b0:400a:808::2010
Connecting to storage.googleapis.com (storage.googleapis.com)|172.217.14.240|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 22722816 (22M) [application/x-tar]
Saving to: ‘helm-v2.12.3-linux-amd64.tar.gz’

helm-v2.12.3-linux-amd64.tar. 100%[=================================================>]  21.67M  31.7MB/s    in 0.7s

2019-02-06 08:22:52 (31.7 MB/s) - ‘helm-v2.12.3-linux-amd64.tar.gz’ saved [22722816/22722816]

bacongobbler@ULTRALISK:~$ tar xzf helm-v2.12.3-linux-amd64.tar.gz
bacongobbler@ULTRALISK:~$ ./linux-amd64/helm version -c
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
```

**Comment by SlickNik** [comment]
This is very strange. I just tried this and was able to successfully install helm on WSL without any issue.

@declanmc Can you provide any context into how you did the initial install? Perhaps running helm under `strace` may give us a further clue as to what might be going on here. Thanks!

**Comment by declanmc** [comment]
Thanks for the responses guys, I followed the install guide as described here

![image](https://user-images.githubusercontent.com/10504666/52401756-5af80c80-2aba-11e9-944d-15dc717673b7.png)

To uninstall, I deleted the Helm directory and re-ran the `mv linux-amd64/helm /usr/local/bin/helm` command. I can't run the `helm reset` command as I get the above issue when I try to run any helm command

**Comment by declanmc** [comment]
@bacongobbler I just tried your install method and I get the same issue when I run any helm command

**Comment by bacongobbler** [comment]
I'm sorry, but I have not been able to reproduce this issue myself and have not heard of similar reports from other community members. Let us know if you figure out what the issue is, and we can try to assist where we can.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
