### ISSUE TITLE
Deletion of CRD with crd-install and before-hook-creation broken in 2.12.3 (worked on 2.12.1)

### ISSUE THREAD

**Issue by micw** [helm/helm#5278]
On helm 2.12.1 it was possible to annotate a CDR with

```
  annotations:
    helm.sh/hook: crd-install
    helm.sh/hook-delete-policy: before-hook-creation
```

This allowed to use the ressource in the same chart and after deletion/reinstalling the chart, the ressource was deleted and re-created. This worked for only one CRD, for multiple CRDs it failed (#4591).
After upgrading tiller from 2.12.1 to 2.12.3, it also fails for a single CRD:

> Error: object is being deleted: customresourcedefinitions.apiextensions.k8s.io "clusterissuers.certmanager.k8s.io" already exists

After force-downgrading tiller ro 2.12.1 it works again.

Output of `helm version`:
2.12.1 / 2.12.3

Output of `kubectl version`:

v1.11.6

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Bare metal

**Comment by bacongobbler** [comment]
Neither 2.12.2 nor 2.12.3 contain any changes to the behaviour of those hooks, so I'm surprised that downgrading to 2.12.1 would somehow fix this issue.

For the record, here's what was changed from [2.12.1 to 2.12.3](https://github.com/helm/helm/compare/v2.12.1...v2.12.3):


fix: perform extra validation on paths in tar archives c194e4a
fix: use RFC 1123 subdomains for name verification 4268e69
fix: ignore pax header "file"s in chart validation 940400b 

If you can figure out what might've caused the issue that would be great. Thanks.

**Comment by hickeyma** [comment]
@micw Have you had a chance to troubleshoot this and  provide more details on the issue?

**Comment by micw** [comment]
Hello, no I'm currently in vacations. Hope to get some time next week.

**Comment by micw** [comment]
@hickeyma I tried to reproduce this in a minimal example.Iit turned out that the issue was not changing with the helm version, but it just occurs randomly. And in my 1st test, it only occured on the later version ;-)

I'm closing this one and create a new issue.
