### ISSUE TITLE
Feature Request: Force overwrite resources on helm upgrade

### ISSUE THREAD

**Issue by chilicat** [helm/helm#5281]
I noticed if I update Kubernetes resources via kubectl/dashboard that a re-applying of the charts will not overwrite my modifications. Since it is common that Devs or Operators with more Kubernetes experience will make experiments directly on Kubernetes resources I would like to have a "force overwrite" options which allows me any time to enforce the "chart state" on a deployment. 

This feature would make the chart a true source of truth 

First I thought that the "--force" flag might help but I saw no difference.

I use at the moment Helm v2.12.1

**Comment by KetsuN** [comment]
Would love to see this functionality even if it's through a flag on `upgrade`.

**Comment by bacongobbler** [comment]
Fixed in Helm 3. See the FAQ for more info: https://v3.helm.sh/docs/faq/#improved-upgrade-strategy-3-way-strategic-merge-patches

**Comment by fischerman** [comment]
@bacongobbler Doesn't the link that you posted describe this issue, instead of solving it? An out-of-band change will not be reverted by Helm, making the chart **not** the source of truth.

**Comment by fischerman** [comment]
@bacongobbler Can you please reopen this issue?

**Comment by bacongobbler** [comment]
Sorry! Quick update on this one...

`helm upgrade —force` is the equivalent of a `kubectl replace`, which bypasses the three-way merge patch. This ensures out-of-band changes are overridden. #7431 introduces —recreate, which in tandem with —force is equivalent to `kubectl replace —force`, which is slightly more destructive, but it ensures the chart will be installed as-is, deleting and recreating objects to force idempotency.

Given that —force already exists and —recreate is ready for testing (feel free to try it out in #7431), I do not believe there is a need to reopen this one. Please follow up with #7082 instead. Thanks!
