### ISSUE TITLE
helm template: Error: gzip: invalid header

### ISSUE THREAD

**Issue by jordansissel** [helm/helm#5296]
Output of `helm version`:
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.11-gke.1", GitCommit:"5c4fddf874319c9825581cc9ab1d0f0cf51e1dc9", GitTreeState:"clean", BuildDate:"2018-11-30T16:18:58Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): N/A

```
% helm template values.yaml                                        
Error: gzip: invalid header
```

Adding `--debug` does not add any additional output.

This is a user error on my part, but I am left wishing greatly for improved feedback from the tool. The error message is *super* confusing for me as an end user (even though I understand why it is).

Maybe instead of `Error: gzip: invalid header` we could say something like "values.yaml does not appear to be a valid chart"

Thoughts?

**Comment by bacongobbler** [comment]
Sounds like a good feature to tackle.

**Comment by popkevin** [comment]
+1 this error is cryptic and misleading.

**Comment by rclabough** [comment]
+1, one hour spent searching to find this post.

**Comment by edunham** [comment]
+1, it's clear Helm is unhappy with what I'm doing but it would be better to have some guidance on what I could change in order to get the desired results.

**Comment by Anakin-Hao** [comment]
+1, just ran into this bug.

**Comment by djuarezg** [comment]
+1 Facing the same issue

**Comment by gWOLF3** [comment]
why is this issue closed?

**Comment by gWOLF3** [comment]
it's clearly not fixed.

**Comment by gWOLF3** [comment]
@bacongobbler

**Comment by jordansissel** [comment]
@gWOLF3 this issue had an improvement merged into Helm 2 #5298. It was ported to Helm 3 in #6613. From Github, it looks like this was released in Helm 2.15?

**Comment by renepardon** [comment]
I just receive the error `Error: error unpacking common-0.1.0-latest.tgz in myumbrellachart: gzip: invalid header`.

`common` is a dependency of `myumbrellachart`. Since I changed from:

```
dependencies:
- name: common
  repository: file://./dependencies/common
  version: 0.1.0-latest
```

to:

```
dependencies:
- name: common
  repository: https://charts.myumbrelladomain.com/charts
  version: 0.1.0-latest
```

I receive this error. 

https://charts.myumbrelladomain.com/charts/index.yaml is available and contains the proper myumbrellachart values. But running `helm dep list` results in the above error

**Comment by sushmak295** [comment]
any update on this issue?
I am facing the same error when doing helm push
"gzip: invalid header, chart package sent by the client is invalid"
