### ISSUE TITLE
User impersonation at resource level

### ISSUE THREAD

**Issue by hickeyma** [helm/helm#5304]
Install a chart with the ability to assign different persona per Kubernetes resources being created by a single chart.

This is similar to [Kubernetes user impersonation](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#user-impersonation) .

**Comment by hickeyma** [comment]
Related to #5303

**Comment by hickeyma** [comment]
@adamreese As we discussed.

**Comment by bacongobbler** [comment]
Similar to [@adamreese's comment in #5303](https://github.com/helm/helm/issues/5303#issuecomment-463309170), Helm 3 now creates Kubernetes API objects as the user defined in their kube config. I am not sure how a chart would map to a specific user. Can you please describe your use case in a little more detail?

**Comment by hickeyma** [comment]
This issue was brought to my attention by an Istio community member. I have unfortunately been unable to get more concrete details on the use case.

**Comment by mtougeron** [comment]
I can help with a use-case that we have.

By default our users don't have permission to interact with `Secret` and similar resources. In order to do so they must be part of a group that is allowed to impersonate an "admin" user for their namespace. The RBAC rules define who is allowed to impersonate that admin user. e.g., `kubectl get secret -n ns1 --as ns1-admin --as-group ns1_admins`

Currently helm3, as far as I can tell, doesn't support the similar ability to pass along the `--as` and `--as-group` params to the Kubernetes API.

**Comment by hickeyma** [comment]
Thanks @mtougeron, interesting use case. Am I correct in saying you only want the impersonation on that resource at not at chart level for all resources?

**Comment by mtougeron** [comment]
I think at chart level when the command is executed is fine. e.g., `helm upgrade --install foo --as ns1-admin --as-group ns1_admins` (or whatever the appropriate cli args would be)

**Comment by bacongobbler** [comment]
From looking at kubectl's implementation, `--as` and `--as-group` are override flags for fields set in your kubeconfig. In other words, Helm already has the ability to perform user impersonation; just modify your `$HOME/.kube/config` and away you go.



https://github.com/kubernetes/kubernetes/blob/30c7df5cd822067016640aa267714204ac089172/staging/src/k8s.io/cli-runtime/pkg/genericclioptions/config_flags.go#L146-L151

We could probably just instantiate a `genericclioptions.ConfigFlags` object in the `Configuration` object, then add those flags to the global flagset, calling `.ToRawKubeConfigLoader()` to fetch the kube config object. That should allow us to support the flagsets from kubectl.

We will probably want to preface the flags with `--kube-` to match with the current convention (`--kube-context`).

**Comment by hickeyma** [comment]
@bacongobbler Is that more the use case in #5303 which is already supported as @mtougeron said in https://github.com/helm/helm/issues/5304#issuecomment-551302545? Are we interested in this use case about impersonation on a particular resource only? Maybe this is what you are saying?

**Comment by bacongobbler** [comment]
closing as inactive.
