### ISSUE TITLE
helm upgrade resets deployment's rollingUpdateStrategy parameters to default values

### ISSUE THREAD

**Issue by tswift242** [helm/helm#5309]
I have a helm release with a k8s deployment for which I've customized maxSurge and maxUnavailable for the rollingUpdateStrategy. However, when I do a helm upgrade on the release, the rolling update isn't carried out how I expect. The cause seems to be that helm upgrade resets both maxSurge and maxUnavailable to their defaults of 25% (each). This is an issue for me because I've set maxSurge=0 and maxUnavailable=1 specifically becaue I want the rolling update to scale down the old replica set before it scales up the new one. When the parameters reset to 25%, I don't get this behavior.

Reproduction steps:

1) helm install a chart with a deployment with rollingUpdateStrategy.maxSurge=0 and rollingUpdateStrategy.maxUnavailable=1
2) kubectl describe the deployment to confirm maxSurge and maxUnavailable are as expected
3) helm upgrade the deployment. The exact command I'm using is: helm upgrade --namespace <ns> <release_name> <chart_path> --reuse-values -f <config_override_file>
4) kubectl describe the deployment again. maxSurge and maxUnavailable will both be 25%

helm version:

Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

kubectl version:

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider: AWS

**Comment by tswift242** [comment]
Whoops, this was caused by a goof on my part. Sorry about this.

**Comment by athira0809** [comment]
@tswift242 I am also facing the same issue. Could you please tell me how you fixed the issue?
