### ISSUE TITLE
locally running tiller always looks up for configmap in kube-system namespace

### ISSUE THREAD

**Issue by linuxshokunin** [helm/helm#5314]
Hi,

I am running tiller locally and I have a cluster-admin access to specific namespace(e.g. test).
I did following command to create a service account and rolebinding.

```
kubectl create ns test
kubectl create -n test sa user1
kubectl create -n test rolebinding admin --clusterrole=cluster-admin --serviceaccount=default:user1
```

And then I have correctly configure .kube/config. I can create pods/deployment etc in the test namespace. 

Now, I ran ```./tiller``` and open up anther terminal and did ```helm --host localhost:44134 list```, I get the following error.

> Error: configmaps is forbidden: User "system:serviceaccount:test:user1" cannot list resource "configmaps" in API group "" in the namespace "kube-system"

I also tried ```helm --tiller-namespace test --host localhost:44134 list```, I get the same error. 
How can I configure tiller to look for configmaps in the test namespace? Is it even possible?

Output of `helm version`:
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Baremetal

**Comment by hickeyma** [comment]
Here is the documentation for running Tiller in a separate namespace and where release configmaps are stored in the same namespace as Tiller: https://docs.helm.sh/using_helm/#example-deploy-tiller-in-a-namespace-restricted-to-deploying-resources-only-in-that-namespace

I am not sure sure it this can be done running Tiller locally. @bacongobbler Is it possible when running locally?

**Comment by linuxshokunin** [comment]
Thanks @hickeyma 

I know how to deploy tiller in a different namespace but I want to run tiller locally so that tiller uses .kube/config to authenticate with kube-apiserver(I assume).  Besides, I don't want to deploy a bunch of tiller into separate namespaces.

**Comment by bacongobbler** [comment]
There are multiple ways to tell tiller where to store/lookup release metadata:

- [setting the TILLER_NAMESPACE environment variable](https://github.com/helm/helm/blob/ead111dd4f699b3cb0a56f1e6d4585e3363f925b/cmd/tiller/tiller.go#L238-L240)
- [add the namespace to `/var/run/secrets/kubernetes.io/serviceaccount/namespace`](https://github.com/helm/helm/blob/ead111dd4f699b3cb0a56f1e6d4585e3363f925b/cmd/tiller/tiller.go#L242-L247) as the kubelet does

Hope this helps!
