### ISSUE TITLE
Rollback removes resource from different release in case fo conflict

### ISSUE THREAD

**Issue by sjanota** [helm/helm#5315]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Minikube

I've encounter following rollback behaviour I find weird:
1. I installed chart A. 
2. Then I installed chart B which contained my CRD.
3. Because of some refactoring I moved this CRD from chart B to chart A. This was not well thought trough
4. Then I did upgrade of chart A. This failed (as expected) as CRD already exists and belongs to different release. The error is misleading, but it is smaller problem:
```
Error: UPGRADE FAILED: no CustomResourceDefinition with the name "backendmodules.ui.kyma-project.io" found
```
5. As release A is now in FAILED state I rolled it back to previous revision. 

And now the magic begins. Rollback removed the CRD from the cluster along with all its implementations. I would expect that the CRD stays where it was, as it was deployed within different  release. I've tested it also for other resources and it appears that's the case for all types of resources when the conflict occurs, i.e. they are of the same kind with the same name and in the same namespace (if namespaced).

**Comment by bacongobbler** [comment]
closing as inactive.
