### ISSUE TITLE
Helm YAML Parser not handling some regexes

### ISSUE THREAD

**Issue by grahamegee** [helm/helm#5316]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS

I have created a Helm chart with ingress definition for some of our api services which contains rules block as follows:
```
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ . | quote }}
    http:
      paths:
      {{- range $.Values.ingress.paths }}
      - backend:
          serviceName:  {{ $servicename }}
          servicePort: 80
        path: {{ . | quote }}
      {{- end }}
  {{- end }}
```
So that in my values file I can simply specify a list of paths for example:

```
ingress:
  paths:
    - /path1
    - /path2
```

Since version 0.22.0 of the nginx ingress controller helm chart you have to be more explicit with capture groups when you create [re-write rules](https://kubernetes.github.io/ingress-nginx/examples/rewrite/#rewrite-target). So my values file now needs to look something like this in some cases:

```
ingress:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  paths:
    - "/path1/?(.*)"
```

but when I try to install the chart with these values I get `Error: YAML parse error on agrimetrics-api/templates/ingress.yaml: error converting YAML to JSON: yaml: did not find expected ',' or ']'`, which I've narrowed down to the `?`. 

Frustratingly when I run `helm install` with `--debug` and `--dry-run` the ingress file that's generated looks correct but it won't actually install the chart because of the parse error.

A previous [issue](https://github.com/helm/helm/issues/3137) which is now closed suggests that the quotes are stripped, which explains why my `?` is not escaped.

I have a work around which involves creating two rules, but it's not ideal:

```
ingress:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  paths:
    - "/path1($)"
    - "/path1/(.*)"
```

On a related not it's also not possible to escape curly braces so I'm unable to use environment variables in my values files either. for example

```
paths:
  - "${TEST_NAMESPACE}/path1
```

**Comment by bacongobbler** [comment]
Could be related to https://github.com/helm/helm/issues/5301? Try single quotes instead of double quotes to prevent adding escape characters.

**Comment by grahamegee** [comment]
> Related comment on character escaping: [#5301 (comment)](https://github.com/helm/helm/issues/5301#issuecomment-463501075)
> 
> Try single quotes instead of double quotes to prevent adding escape characters.

Thanks for the suggestion, I did try that, but it still didn't work. I probably should have noted that attempt down when I filed the issue 👍

**Comment by hickeyma** [comment]
@grahamegee I have tested this and it seems to work as expected. Comments that follow show details of my investigation.

**Comment by hickeyma** [comment]
```console
$ cat values.yaml 
[....]

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - "/path1/?(.*)"

  tls: []
[.............]

$ cat ingress.yaml 
[....]
spec:
  [...]
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
        {{- end }}
  {{- end }}
```

**Comment by hickeyma** [comment]
Output in `dry-run` as expected:
```console
$ helm install --debug --dry-run mychart/
[debug] Created tunnel using local port: '44359'

[debug] SERVER: "127.0.0.1:44359"

[debug] Original chart version: ""
[debug] CHART PATH: /home/usr1/test/helm-charts/mychart

NAME:   coiled-worm
REVISION: 1
RELEASED: Wed Feb 27 12:30:00 2019
CHART: mychart-0.1.0
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
affinity: {}
fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  repository: nginx
  tag: stable
ingress:
  annotations: {}
  enabled: true
  hosts:
  - host: chart-example.local
    paths:
    - /path1/?(.*)
  tls: []
nameOverride: ""
nodeSelector: {}
replicaCount: 1
resources: {}
service:
  port: 80
  type: ClusterIP
tolerations: []

HOOKS:
---
# coiled-worm-mychart-test-connection
[...]
---
# Source: mychart/templates/service.yaml
[...]
---
# Source: mychart/templates/deployment.yaml
[...]
---
# Source: mychart/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: coiled-worm-mychart
  labels:
    app.kubernetes.io/name: mychart
    helm.sh/chart: mychart-0.1.0
    app.kubernetes.io/instance: coiled-worm
    app.kubernetes.io/managed-by: Tiller
spec:
  rules:
    - host: "chart-example.local"
      http:
        paths:
          - path: /path1/?(.*)
            backend:
              serviceName: coiled-worm-mychart
              servicePort: http
```

**Comment by hickeyma** [comment]
Output for install as expected:
```console
helm install mychart/
NAME:   moldy-peahen
LAST DEPLOYED: Wed Feb 27 12:31:52 2019
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/Service
NAME                  TYPE       CLUSTER-IP    EXTERNAL-IP  PORT(S)  AGE
moldy-peahen-mychart  ClusterIP  10.97.77.103  <none>       80/TCP   0s

==> v1/Deployment
NAME                  READY  UP-TO-DATE  AVAILABLE  AGE
moldy-peahen-mychart  0/1    0           0          0s

==> v1beta1/Ingress
NAME                  HOSTS                ADDRESS  PORTS  AGE
moldy-peahen-mychart  chart-example.local  80       0s

==> v1/Pod(related)
NAME                                   READY  STATUS   RESTARTS  AGE
moldy-peahen-mychart-5777545547-ntbc7  0/1    Pending  0         0s


NOTES:
1. Get the application URL by running these commands:
  http://chart-example.local/path1/?(.*)
```
and cluster afterwards:
```console
$ kubectl get all --all-namespaces | grep "moldy-peahen"
default       pod/moldy-peahen-mychart-5777545547-ntbc7   1/1     Running   0          96m

default       service/moldy-peahen-mychart   ClusterIP   10.97.77.103    <none>        80/TCP          96m


default       deployment.apps/moldy-peahen-mychart   1/1     1            1           96m

default       replicaset.apps/moldy-peahen-mychart-5777545547   1         1         1       96m
$ kubectl get ingress moldy-peahen-mychart
NAME                   HOSTS                 ADDRESS   PORTS   AGE
moldy-peahen-mychart   chart-example.local             80      97m

**Comment by grahamegee** [comment]
> @grahamegee I have tested this and it seems to work as expected. Comments that follow show details of my investigation. I used a scaffold chart (created by `helm create`) and did updates as shown below to match your scenario. AFIk, the only difference is that I did not add quotes to the port in the ingress template (i.e. `path: {{ . | quote }}`).

That isn't the only difference, although admittedly from my post it's not obvious! In my values files `paths` and `hosts` are specified at the same level so that I don't have to rewrites the `paths` when I have multiple `hosts`.

```
[...]
paths:
  - /some-path/?(.*)
hosts:
  - some.host
  - some.other.host
```

So the in order to access the `paths` within the `hosts` loop I have to bring them into scope with:

```
{{- range $.Values.ingress.paths }}
```
And this is where it all goes wrong.

Now you can certainly argue that I should:
*a) not be lazy and specify the paths again
*b) stop adding a layer of indirection by flattening `paths` and `hosts` down which isn't how they are actually represented in the generated manifest.

Having looked through my deployment code I am yet to find a single instance where I've specified more than one host 😂... So I will probably change to my ingress template so that it maintains the nesting as that does seem to work.

I still think it might be worth investigating why bringing the outer scope in with `$` seems to cause problems even though my particular use case is a bit strange.

**Comment by hickeyma** [comment]
@grahamegee Have changed around to flatten hosts and paths as you have done. 
Comments that follow show it still works as expected.

**Comment by hickeyma** [comment]
```console
$ cat values.yaml
[...]
ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - chart-example.local
  paths:
    - "/path1/?(.*)"
[...]

$ cat ingress.yaml
[...]
rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
        {{- range $.Values.ingress.paths }}
          - path: {{ . }}
            backend:
              serviceName:  {{ $fullName }}
              servicePort: 80
        {{- end }}
  {{- end }}
[...]

**Comment by hickeyma** [comment]
Output in `dry-run` as expected:

```console
helm install --debug --dry-run nxtchart/
[debug] Created tunnel using local port: '45037'

[debug] SERVER: "127.0.0.1:45037"

[debug] Original chart version: ""
[debug] CHART PATH: /home/usr1/test/helm-charts/nxtchart

NAME:   juiced-starfish
REVISION: 1
RELEASED: Thu Feb 28 10:51:09 2019
[....]
---
# Source: nxtchart/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: juiced-starfish-nxtchart
  labels:
    app.kubernetes.io/name: nxtchart
    helm.sh/chart: nxtchart-0.1.0
    app.kubernetes.io/instance: juiced-starfish
    app.kubernetes.io/managed-by: Tiller
spec:
  rules:
    - host: "chart-example.local"
      http:
        paths:
          - path: /path1/?(.*)
            backend:
              serviceName:  juiced-starfish-nxtchart
              servicePort: 80

**Comment by hickeyma** [comment]
Output for install as expected:
```console
$ helm install nxtchart/
NAME:   brawny-gnat
LAST DEPLOYED: Thu Feb 28 10:52:37 2019
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1beta1/Ingress
NAME                  HOSTS                ADDRESS  PORTS  AGE
brawny-gnat-nxtchart  chart-example.local  80       0s

==> v1/Pod(related)
NAME                                   READY  STATUS   RESTARTS  AGE
brawny-gnat-nxtchart-5d6b6b7544-9t86v  0/1    Pending  0         0s

==> v1/Service
NAME                  TYPE       CLUSTER-IP      EXTERNAL-IP  PORT(S)  AGE
brawny-gnat-nxtchart  ClusterIP  10.100.254.230  <none>       80/TCP   0s

==> v1/Deployment
NAME                  READY  UP-TO-DATE  AVAILABLE  AGE
brawny-gnat-nxtchart  0/1    0           0          0s
```

and cluster afterwards:

```console
$  kubectl get all --all-namespaces | grep "brawny-gnat"
default       pod/brawny-gnat-nxtchart-5d6b6b7544-9t86v   1/1     Running   0          11m

default       service/brawny-gnat-nxtchart   ClusterIP   10.100.254.230   <none>        80/TCP          11m


default       deployment.apps/brawny-gnat-nxtchart   1/1     1            1           11m

default       replicaset.apps/brawny-gnat-nxtchart-5d6b6b7544   1         1         1       11m
$ kubectl get ingress brawny-gnat-nxtchart
NAME                   HOSTS                 ADDRESS   PORTS   AGE
brawny-gnat-nxtchart   chart-example.local             80      11m
```

**Comment by hickeyma** [comment]
BTW, using quotes for port makes no difference (i.e. `path: {{ . | quote }}`) . I did change `backend` to b part of a path as per the standard ingress file. Not sure this would make any difference either.

**Comment by grahamegee** [comment]
> BTW, using quotes for port makes no difference (i.e. `path: {{ . | quote }}`) . I did change `backend` to b part of a path as per the standard ingress file. Not sure this would make any difference either.

Ah thanks you've helped narrow this down! I've finally managed to reproduce the error using the template generated by `helm create`. It's actually not where I thought it was.

In my ingress template I use the following line at the top to ensure that users provide at least one path in the their values file.
```
value: {{ required "Must supply at least one base resource path for Values.ingress.paths" .Values.ingress.paths }}
```
Can you try adding that at the top of your ingress template and see if you get the same issue as me?

```
$ cat test/templates/ingress.yaml
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "test.fullname" . -}}
value: {{ required "Must supply at least one base resource path for Values.ingress.paths" .Values.ingress.paths }}
apiVersion: extensions/v1beta1
kind: Ingress
[...]

$ helm install --debug --dry-run test
[debug] Created tunnel using local port: '60155'

[debug] SERVER: "127.0.0.1:60155"

[debug] Original chart version: ""
[debug] CHART PATH: /home/grahamegee/tests/helm/test

Error: YAML parse error on test/templates/ingress.yaml: error converting YAML to JSON: yaml: did not find expected ',' or ']'

---
```

**Comment by hickeyma** [comment]
@grahamegee sorry for the delay in replying but got waylaid.

The issue is with the `?` in the path value `/path1/?(.*)`. The [Go YAMl unmarshaler](https://github.com/ghodss/yaml) is called [here](https://github.com/helm/helm/blob/master/pkg/tiller/hooks.go#L131). It would seem that tit is not able to handle the `?` character.

@technosophos can you provide some insight on the  library and if this might be an issue upstream?

**Comment by technosophos** [comment]
I believe that `?` is an "indicator character" in YAML, and has to be escaped with a backslash (`\?`). The YAML parser should strip out the backslash before the `?` is handed back to the calling code.

**Comment by hickeyma** [comment]
@technosophos should have mentioned that I used the backslash but still an issue

**Comment by technosophos** [comment]
My interpretation of the spec is that if a `\?` does not work, and you can reproduce this by passing a YAML doc straight to the parser and having it fail to meet expectations, then this is an error with the parser.

**Comment by grahamegee** [comment]
> My interpretation of the spec is that if a `\?` does not work, and you can reproduce this by passing a YAML doc straight to the parser and having it fail to meet expectations, then this is an error with the parser.

When I get a bit of time I'll have a crack at reproducing it directly with the go YAML unmarshaler. Looks pretty straight forward. Import it, create a yaml string, run yamlToJson.

**Comment by hickeyma** [comment]
@grahamegee Let me know how you get on.

**Comment by grahamegee** [comment]
> @grahamegee Let me know how you get on.

I couldn't reproduce this directly using the unmarshaler.

```console
$ cat test.yaml
paths:
  - path: base(/?some-path)
```

```console
$ cat test-unmarshal-yaml.go
package main

import (
	"fmt"
    "io/ioutil"
	"github.com/ghodss/yaml"
)

type Path struct {
    Path string `json:path`
}

type Person struct {
    Paths []Path
}

func main() {
    dat, err := ioutil.ReadFile("./test.yaml")
    fmt.Print(string(dat))

	var p2 Person
    err = yaml.Unmarshal(dat, &p2)
    if err != nil {
        fmt.Printf("err: %v\n", err)
        return
    }
    fmt.Println(p2)
}
```

```console
$ ./test-unmarshal-yaml
paths:
  - path: base(/?some-path)

{[{base(/?some-path)}]}
```

**Comment by hickeyma** [comment]
Thanks @grahamegee. 

So, it would seem that there is issue is with the `required` function when it is passed a value containing the `?` character.

**Comment by bacongobbler** [comment]
closing as inactive.
