### ISSUE TITLE
Allow Job type for Tests

### ISSUE THREAD

**Issue by dansiviter** [helm/helm#5317]
Only `Pod` types are permitted for `helm test` as it errors within [`client.go#711`](https://github.com/helm/helm/blob/master/pkg/kube/client.go#L711) if a `Job` is used. As a [`Job`](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/) are more suited to running to completion this would be a better fit.

**Comment by bacongobbler** [comment]
closing as inactive.
