### ISSUE TITLE
Helm upgrade output with incorrect values.

### ISSUE THREAD

**Issue by alexandrsemak** [helm/helm#5327]
Output of `helm version`:
2.12.3 server
2.12.3 client
Output of `kubectl version`:
1.12.5
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
IBM

Hello,

We have some question/issue when execute:
`helm upgrade --debug --install -f values.yaml`
and if we have some incorrect values file and helm doing first install it will give detailed Error, but if release have been already in cluster and helm tring do upgrade with incorrect values is doesn't give detailed Error.

Looks like executing `helm install` do lint but not in `helm upgrade`...

**Comment by hickeyma** [comment]
Do you mind providing an example of a values file with incorrect values that I can use for test purposes?

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
