### ISSUE TITLE
Helm Quickstart and Installation URLs Incorrect

### ISSUE THREAD

**Issue by aaronkjones** [helm/helm#5342]
URLs to quickstart and installation are broken in https://github.com/helm/helm/blob/master/README.md.

**Comment by bacongobbler** [comment]
cc @flynnduism

**Comment by flynnduism** [comment]
Hmm, I added redirect rules earlier this morning to handle site structural changes... 
Pointing `docs.helm.sh/* > helm.sh/docs/*`

Those links are route correctly for me now (tested it over vpns and fresh devices).

@aaronkjones can you re-check? I'm hoping you were just unlucky in your timing corresponding with the dns change.

**Comment by bacongobbler** [comment]
I can confirm that the redirect rules are pointing at the right location for me as well, so it must've been a timing issue. I'll go ahead and close this as well as #5343. Thanks!

**Comment by aaronkjones** [comment]
@flynnduism @bacongobbler It redirects fine now. Just bad luck timing :)
