### ISSUE TITLE
docs/helm/helm.md Environment list format broken

### ISSUE THREAD

**Issue by howardjohn** [helm/helm#5344]
https://helm.sh/docs/helm/

The list of environment variables is broken, it is all merged together instead of a list.

**Comment by bacongobbler** [comment]
cc @flynnduism

**Comment by bacongobbler** [comment]
Sorry, wrong person to ping. This doesn't have to do with the site migration that occurred earlier this morning. Disregard! :)

@bridgetkromhout identified this as well earlier this week. There's some discussion in #5339 if you'd like to follow along.

**Comment by howardjohn** [comment]
Still broken
