### ISSUE TITLE
helm - configmap created is misaligned

### ISSUE THREAD

**Issue by Anashaikh** [helm/helm#5351]
**Is this a request for help?**:
Yes

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

**Version of Helm and Kubernetes**:
helm version v2.12.3
tiller version v2.12.3
Kubernetes api v1.12.3

**What happened**:
snippet of server-configmap.yaml
```
...
data: 
{{ range $key, $value := .Values.serverFiles  }}
  {{ $key }}: |-
{{ toYaml $value | default "{}" | indent 4 }}
{{- end -}}
{{- end -}}
```
after adding the below on values.yml file

```
serverFiles:
...
- job_name: 'consul_sd'
  consul_sd_configs:
    - server: 'consul_server:8500'
```
and running helm template .
the configmap shows up as:
```
- consul_sd_configs:
  - server: consul_server:8500
  job_name: consul_sd
```
**What you expected to happen**:

```
- job_name: consul_sd
  consul_sd_configs:
    - server: consul_server:8500
```
 
It seems like the the configmap is saved in alphabetical order.
consul_sd_config comes first and job_name comes underneath it, which causes the app to fail.
is there is any way to stop helm template to stop sorting  (alphabetical order) before it writes to the configmap? or anything i can do to make - job name comes first and consul_sd_configmap underneath it

**Comment by bacongobbler** [comment]
Try using `nindent` instead of `indent`. The former indents all lines, whereas the latter indents only the first line.

**Comment by ashwork** [comment]
Hi Matthew,

I tried using nident but still get the following output when running helm
template .
              - consul_sd_configs:
                - server: 10.79.120.17:8500
                  token: aasas
                job_name: consul_sd


whereas i wanted it to be :
                -  job_name: consul_sd
                   consul_sd_configs:
                    - server: 10.79.120.17:8500

**Comment by ashwork** [comment]
Hi Matthew,
I tried using nident but still get the following output when running helm
template .

              - consul_sd_configs:
                - server: consul_server:8500
                job_name: consul_sd

whereas i wanted the output to be :

              -  job_name: consul_sd
                 consul_sd_configs:
                   - server:  consul_server:8500


somehow toYaml is parsing/formatting it alphabetically.

**Comment by hickeyma** [comment]
The suggestion by @bacongobbler was to fix the indentation in the generated yaml. This is the output I get which tidies it up:
```
 consul_sd_configs:
 - server: consul_server:8500
 job_name: consul_sd
```
If this did not fix the issue and you need the output in a particular order, can you show the template code that needs this order? It might help give an understanding of the issue.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
