### ISSUE TITLE
Helm lint failed with empty value

### ISSUE THREAD

**Issue by 27149chen** [helm/helm#5361]
Similar with https://github.com/helm/helm/issues/1463#issuecomment-256493366
When running helm lint, I got an error:
`[ERROR] templates/: render error in "xxx/templates/xxx-deployment.yaml": template:xxx/templates/xxx-deployment.yaml:7:24: executing "xxx/templates/xxx-deployment.yaml" at <include (print $.Tem...>: error calling include: template: xxx/templates/xxx-secret.yaml:14:74: executing "xxx/templates/xxx-secret.yaml" at <b64enc>: wrong number of args for b64enc: want 1 got 0` 

error lines are:
`username: {{ .Values.username | b64enc | quote  }}`
Note that the param exists, but it is **empty**
It is used in another file in this way:
`checksum/secret: {{ include (print $.Template.BasePath "/xxx-secret.yaml") . | sha256sum }}`

Output of `helm version`:
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Kubernetes

**Comment by hickeyma** [comment]
@27149chen It seems that the `b64enc` function requires a non empty string. You can get around this by checking if the string is non empty, similar to the following:
```
{{ if .Values.username }}
  username: {{ .Values.username | b64enc | quote }}
{{ end }}
```

**Comment by 27149chen** [comment]
@hickeyma  I have tried this way, not working.
My  case is a bit more complex since it is used in a (include (print xxx))

**Comment by hickeyma** [comment]
Ok, trying to reproduce this so to better understand. Is this the line that fails:
`checksum/secret: {{ include (print $.Template.BasePath "/xxx-secret.yaml") . | sha256sum }}` ?
If so what is the contents of `xxx-secret.yam` that causes the error?

**Comment by 27149chen** [comment]
@hickeyma 
the error line is:
`username: {{ .Values.username | b64enc | quote }}`

**Comment by hickeyma** [comment]
is the error caused when `username` in the values object is an empty string?

**Comment by 27149chen** [comment]
@hickeyma 
yes, in this way `usename: `

**Comment by hickeyma** [comment]
> My case is a bit more complex since it is used in a (include (print xxx))

Can you show me then where the complexity is that the ' if statement' suggested in https://github.com/helm/helm/issues/5361#issuecomment-467419275 won't fix the issue with an empty `username` and statement `username: {{ .Values.username | b64enc | quote }}`?

**Comment by 27149chen** [comment]
Did you try to reproduce?
I tried to add an "if", but failed with same error

**Comment by hickeyma** [comment]
This should work. I tested using a very simple chart which I create using `helm create`. I then removed all the template files and just added a 'configmap' template as follows:

```console
$ cat configmap.yaml 
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  {{ if .Values.username }}
  username: {{ .Values.username | b64enc | quote }}
  {{ end }}
```

My values files is as follows:
```console
$ cat values.yaml 
username:
```
I then run 'template' and 'linter' which works as expected:
```console 
$ helm template newchrt/
---
# Source: newchrt/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-configmap
data:

$ helm lint newchrt/
==> Linting newchrt/
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, no failures
```

Then when I add a username value:
```console
$ cat values.yaml 
username: Paul
```

I get the output as expected:
```console
$ helm template newchrt/
---
# Source: newchrt/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-configmap
data:
  
  username: "UGF1bA=="

$ helm lint newchrt/
==> Linting newchrt/
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, no failures
```

**Comment by hickeyma** [comment]
Maybe if you share your template and values file, I get try and see what is going wrong for you?

**Comment by 27149chen** [comment]
@hickeyma 
you forgot this one:
`checksum/secret: {{ include (print $.Template.BasePath "/xxx-secret.yaml") . | sha256sum }}`

**Comment by 27149chen** [comment]
Adding this to your chart:
`
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap2
  annotations:
    checksum/secret: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
data:
  test: test
`

**Comment by hickeyma** [comment]
It might be better if you could explain what are you trying to do? At the moment, we are just over and back with syntax!

**Comment by 27149chen** [comment]
I followed this guide https://github.com/helm/helm/blob/master/docs/charts_tips_and_tricks.md#automatically-roll-deployments-when-configmaps-or-secrets-change to automatically roll deployments When secrets change during upgrage. so I use the include (xxx), while my secret.yaml has this line `username: {{ .Values.username | b64enc | quote }}` which will cause helm lint failure

**Comment by hickeyma** [comment]
```console
$ cat configmap.yaml 
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  {{ if .Values.username }}
  username: {{ .Values.username | b64enc | quote }}
  {{ end }}
  token: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}

$ cat secret.yaml 
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
data:
  {{ if .Values.username }}
  username: {{ .Values.username | b64enc | quote }}
  {{ end }}
```

Output as expected:
```console
$ helm template chart1/
---
# Source: chart1/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
data:
  

---
# Source: chart1/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-configmap
data:
  
  token: 9e2a035f1cb2e85f61df7d5507c93ec5a94c9269120ef85c67474ac337c11380

$ helm lint chart1/
==> Linting chart1/
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, no failures
```

**Comment by hickeyma** [comment]
Another example..

```console
$ cat deployment.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tmpchart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "tmpchart.name" . }}
    helm.sh/chart: {{ include "tmpchart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "tmpchart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "tmpchart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
[...........]
```
`secret.yaml` as in above comment

Output as expected:
```console
$ helm template tmpchart/
---
# Source: tmpchart/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
data:
---
# Source: tmpchart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-tmpchart
  labels:
    app.kubernetes.io/name: tmpchart
    helm.sh/chart: tmpchart-0.1.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tmpchart
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      annotations:
        checksum/secret: 9e2a035f1cb2e85f61df7d5507c93ec5a94c9269120ef85c67474ac337c11380
      labels:
        app.kubernetes.io/name: tmpchart
        app.kubernetes.io/instance: release-name
[.............]
```

**Comment by 27149chen** [comment]
It's strange, I do remember that I tried this way. but now it's working. Thank you for your help @hickeyma
