### ISSUE TITLE
Unable to use Helm: could not find an available port

### ISSUE THREAD

**Issue by joergkiesewetter** [helm/helm#5362]
I'm not able to use helm in our kubernetes cluster. Everytime I want to execute a command, helm tells me, that he cannot find an available port:

```
Error: could not find an available port: listen tcp :0: bind: address already in use
```

This is for every command. When I execute ```sudo helm init```, the tiller pod gets started up. But after that, I cannot communicate with tiller anymore. It worked before, but somehow it stopped working after a while. We were able to install multiple charts but now nothing works.

Previously, we had used version 2.8.2 and updated to version 2.12.3, recently. But it didn't helped.

Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Error: could not find an available port: listen tcp :0: bind: address already in use
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

None/Kubernetes

**Comment by hickeyma** [comment]
@joergkiesewetter What is the output of this command: `kubectl get all -n kube-system | grep "tiller"` ?

**Comment by joergkiesewetter** [comment]
the output is:

```
NAME                                                                  READY     STATUS    RESTARTS   AGE
pod/tiller-deploy-689d79895f-l6mnt                                    1/1       Running   0          21h

NAME                                                                TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
service/tiller-deploy                                               ClusterIP      10.110.185.1     <none>        44134/TCP                    320d

NAME                                                                     DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/tiller-deploy                                            1         1         1            1           21h

NAME                                                                                DESIRED   CURRENT   READY     AGE
replicaset.apps/tiller-deploy-689d79895f                                            1         1         1         21h

```

**Comment by hickeyma** [comment]
Can you get the output of the `tiller-deploy` pod logs?

**Comment by joergkiesewetter** [comment]
yes, the log is:

```
[main] 2019/02/25 16:15:28 Starting Tiller v2.12.3 (tls=false)
[main] 2019/02/25 16:15:28 GRPC listening on :44134
[main] 2019/02/25 16:15:28 Probes listening on :44135
[main] 2019/02/25 16:15:28 Storage driver is ConfigMap
[main] 2019/02/25 16:15:28 Max history per release is 0
```

**Comment by hickeyma** [comment]
What infrastructure (AKS, GKE, Minikube etc.) is your Kubernetes cluster running on? Are you running the `helm` commands remotely to the cluster?

Could you try running the following commands and provide the output:
`helm init --upgrade`
`helm version`

Can you also check the kube config where the `helm` commands are run: `$ kubectl config view`

**Comment by joergkiesewetter** [comment]
The cluster is running on a self-hosted machine, set up with kubeadm. To execute the helm command, I connect to the master via SSH and execute the commands.

```helm init --upgrade``` made the response:
```
$HELM_HOME has been configured at /home/kubernetes/.helm.

Tiller (the Helm server-side component) has been upgraded to the current version.
Happy Helming!
```

```helm version``` made the response:
```
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
```

It seems like the upgrade-command helped. Previously, I was not able to get a list of installed charts via ```helm list```, now it is possible.

Let me check some things...

**Comment by joergkiesewetter** [comment]
Yes, the connection really works, again. Thank you very much for your help.
