### ISSUE TITLE
Include app.kubernetes.io/version as part of the recommended lables

### ISSUE THREAD

**Issue by luisdavim** [helm/helm#5369]
If I create a new chart with `helm create my-chart` the following labels are included:
```
    app.kubernetes.io/name: {{ include "my-chart.name" . }}
    helm.sh/chart: {{ include "my-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
```

I think that `app.kubernetes.io/version: {{ .Chart.AppVersion }}` should also be included.

**Comment by hickeyma** [comment]
@luisdavim I think that this should be added. Do you want to do the PR or will I?

**Comment by luisdavim** [comment]
sure

**Comment by luisdavim** [comment]
I've created #5373
