### ISSUE TITLE
There is a typo here

### ISSUE THREAD

**Issue by Keramblock** [helm/helm#5370]
https://github.com/helm/helm/blob/268695813ba957821e53a784ac849aa3ca7f70a3/pkg/tiller/release_server.go#L198
released named -> release named

**Comment by Keramblock** [comment]
Also in the test:
https://github.com/helm/helm/blob/82d01cb3124906e97caceb967a09f2941d6a392d/pkg/tiller/release_update_test.go#L607

**Comment by hickeyma** [comment]
Do you want to create a PR and fix it?

**Comment by Keramblock** [comment]
With pleasure =)

**Comment by Keramblock** [comment]
Still cant run unittests locally to test if my work is correct, can you please provide me with specific command? I used make test, but only linter started

**Comment by bacongobbler** [comment]
`make test` should run everything. If the linter failed then it stops there. If you want to run the unit tests specifically, use `make test-unit`.

**Comment by hickeyma** [comment]
@Keramblock Were you able to make progress?

**Comment by Keramblock** [comment]
I am trying, but something wrong with my go environment(that is the my first time when I developing something with go). If you need that fix faster - feel free to reassign it on somebody else =)

**Comment by hickeyma** [comment]
That's ok.  Let me know how you get on. It will be good if you can push your PR.

**Comment by Keramblock** [comment]
I am finally fixed my go env and managed to run unit tests.
So i have created a pull request. Will appreciate any comments according to my work and/or potential process violation from my side.
