### ISSUE TITLE
Helm website documentation not up to date

### ISSUE THREAD

**Issue by thomasLeclaire** [helm/helm#5376]
On the main doc webpage https://helm.sh/docs/using_helm, it sounds like at least the first links are broken  :
https://helm.sh/docs/using_helm/#installing-helm
https://helm.sh/docs/using_helm/#quickstart

doc sounds to be correct on github side : https://github.com/helm/helm/blob/master/docs/using_helm.md

**Comment by hickeyma** [comment]
@thomasLeclaire Thanks for finding this. Can you raise an issue in the [web docs](https://github.com/helm/helm-www/issues) project? That is where the issue needs to be fixed.

**Comment by hickeyma** [comment]
@thomasLeclaire Maybe reference the issue your raise in the other project incase someone references this bug in the future.

**Comment by thomasLeclaire** [comment]
new ticket here : https://github.com/helm/helm-www/issues/185

**Comment by hickeyma** [comment]
Great, thanks @thomasLeclaire

**Comment by flynnduism** [comment]
Reviewing the docs, is seems that the Using Helm section hasn't properly generated. Clearing cache and rebuilding the site has restored the proper content:

https://helm.sh/docs/using_helm/#quickstart
https://helm.sh/docs/using_helm/#installing-helm

Thanks for flagging this - it's resolved for now. I'll investigate why this occurred.

**Comment by hickeyma** [comment]
Thanks @flynnduism
