### ISSUE TITLE
StatefulSets deployed after Deployments/ReplicaSets causes deployment issues on tight hardware

### ISSUE THREAD

**Issue by rdzimmer** [helm/helm#5381]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1+icp", GitCommit:"843201eceab24e7102ebb87cb00d82bc973d84a7", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1+icp-ee", GitCommit:"5803c3b1f9422c43a963e0610b3a4cad565e127e", GitTreeState:"clean", BuildDate:"2018-09-04T09:29:02Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1+icp-ee", GitCommit:"5803c3b1f9422c43a963e0610b3a4cad565e127e", GitTreeState:"clean", BuildDate:"2018-09-04T09:29:02Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
`IBM Cloud Private`

https://github.com/helm/helm/blob/release-2.10/pkg/tiller/kind_sorter.go#L29 
```
var InstallOrder SortOrder = []string{
...
	"Service",
	"DaemonSet",
	"Pod",
	"ReplicationController",
	"ReplicaSet",
	"Deployment",
	"StatefulSet",
...
```
I'm wondering if it makes sense to order StatefulSet higher up in the list.  By having it near the end, specifically after Pod/Deployment/ReplicaSet, I can run into randomly occurring issues fitting installs onto tight hardware.  
For example: I have 10 Deployments, each requesting 1 CPU core from kubernetes for a total of 10 cores requested.  I have 2 VMs, each with 8 cores for 16 total.  If I want to run a 4 CPU Cassandra Statefulset, I should be able to because I still have 6 of the 16 total CPUs available.  
However, when Helm/kubernetes installs/allocates the deployments, if 5 go on the first VM and 5 on the second, then each VM only has 3 cores available.  I have 6 cores free in the environment, but only 3 on a single VM.  Therefore, my 4 core Cassandra StatefulSet fails to deploy.  

In my experience, StatefulSets are usually these larger blocks trying to fit onto the hardware.  To me it makes sense to assign the larger StatefulSets first and let the smaller blocks fill in behind them.  Deployments and services also seem to generally depend on Statefulsets for the stateful data they provide.  I realize these statements may or may not be true for all cases and is making some broad generalizations.  
There may be other ways I'm not aware of to prevent these sort of install resource issues that do not rely on changing the order based on the generalizations above.  However, I have not found anything options other than moving services around when this problem happens.

**Comment by bacongobbler** [comment]
I'm having a tough time trying to come up with the right label for this issue. Would you consider this to be a bug, a proposal to change the sort order? Maybe both? :smile:

**Comment by rdzimmer** [comment]
@bacongobbler Proposal works for me!  It's working as designed today, could potentially be enhanced though in my opinion.

**Comment by nvtkaszpir** [comment]
I believe this should be possible to be solved with affinity rules or taints, without any touching of existing code within helm itself.

**Comment by bacongobbler** [comment]
If you wouldn't mind demonstrating an example that solves this issue, that would be fantastic.

**Comment by nvtkaszpir** [comment]
Not having exact example (I rather set anti-affinity rules for now for increased availability), but I see there are some examples at https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity-beta-feature - especially with node affinity.

**Comment by rdzimmer** [comment]
We do not want to prevent all non-statefulsets from being deployed to the nodes by setting anti-affinities, just give the large statefulsets a chance to get assigned first before there isn't space for them.  In our exact use-case, the statefulsets all have affinity to a specific node because of local-storage requirements.  So perhaps the better or more generic proposal would be to add some logic to helm/kubernetes to handle capacity planning?  `Assign/deploy all things that do have affinity to a node first so they are sure to be able to deploy, then fill in the others from largest to smallest.`

I think `preferredDuringSchedulingIgnoredDuringExecution` may work if all of the non-statefulsets are given low weights for the nodes that have the statefulsets, so that they are preferred on another node: but can be deployed there if the others are full:
```
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: ...
```
However, that would require a lot of additional setup planning and work on the user.  It's also not exactly what I was looking for because it could create imbalances in the loads.

**Comment by nvtkaszpir** [comment]
You could also try to use kubernetes taints https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/

**Comment by cgetzen** [comment]
I don't know that modifying install order will always fix this: you can run into a scenario where the resource has been created but not assigned. But it does make sense that InstallOrder goes from largest to smallest.

**Comment by bacongobbler** [comment]
closing as inactive.
