### ISSUE TITLE
tiller pod crashes on k8s cluster

### ISSUE THREAD

**Issue by shilpakarthik** [helm/helm#5384]
Output of `helm version`:
 helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

Output of `kubectl version`:
kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:57:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
OpenStack

Describing tiller pod gives below output

ubectl describe pod tiller-deploy-5978f4c9b8-lnm6v -n kube-system
Name:               tiller-deploy-5978f4c9b8-lnm6v
Namespace:          kube-system
Priority:           0
PriorityClassName:  <none>
Node:               optimusprime-worker-02/192.168.161.186
Start Time:         Fri, 01 Mar 2019 09:50:31 +0530
Labels:             app=helm
                    name=tiller
                    pod-template-hash=5978f4c9b8
Annotations:        kubernetes.io/psp: privileged
Status:             Running
IP:                 192.168.1.28
Controlled By:      ReplicaSet/tiller-deploy-5978f4c9b8
Containers:
  tiller:
    Container ID:   docker://0abd5a02ab87854821fc4c11949e6cbac9b830c096b9af8a09afa24487d3a97f
    Image:          gcr.io/kubernetes-helm/tiller:v2.11.0
    Image ID:       docker-pullable://bcmt-registry:5000/gcr.io/kubernetes-helm/tiller@sha256:f6d8f4ab9ba993b5f5b60a6edafe86352eabe474ffeb84cb6c79b8866dce45d1
    Ports:          44134/TCP, 44135/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Fri, 01 Mar 2019 10:04:51 +0530
      Finished:     Fri, 01 Mar 2019 10:05:21 +0530
    Ready:          False
    Restart Count:  9
    Liveness:       http-get http://:44135/liveness delay=1s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:44135/readiness delay=1s timeout=1s period=10s #success=1 #failure=3
    Environment:
      TILLER_NAMESPACE:    kube-system
      TILLER_HISTORY_MAX:  100
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from tiller-token-cjffc (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  tiller-token-cjffc:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  tiller-token-cjffc
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     <none>
Events:
  Type     Reason     Age                  From                             Message
  ----     ------     ----                 ----                             -------
  Normal   Scheduled  16m                  default-scheduler                Successfully assigned kube-system/tiller-deploy-5978f4c9b8-lnm6v to optimusprime-worker-02
  Normal   Pulled     15m (x3 over 16m)    kubelet, optimusprime-worker-02  Container image "gcr.io/kubernetes-helm/tiller:v2.11.0" already present on machine
  Normal   Killing    15m (x2 over 16m)    kubelet, optimusprime-worker-02  Killing container with id docker://tiller:Container failed liveness probe.. Container will be killed and recreated.
  Normal   Created    15m (x3 over 16m)    kubelet, optimusprime-worker-02  Created container
  Warning  Unhealthy  15m (x7 over 16m)    kubelet, optimusprime-worker-02  Readiness probe failed: Get http://192.168.1.28:44135/readiness: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  15m (x7 over 16m)    kubelet, optimusprime-worker-02  Liveness probe failed: Get http://192.168.1.28:44135/liveness: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Normal   Started    11m (x7 over 16m)    kubelet, optimusprime-worker-02  Started container
  Warning  BackOff    105s (x48 over 12m)  kubelet, optimusprime-worker-02  Back-off restarting failed container

**Comment by bacongobbler** [comment]
What's the current state of the cluster? It looks like the kubelet on the node is failing based on the logs here.

**Comment by shilpakarthik** [comment]
There was some route issue in nodes due to which this issue was happening .
we can close this issue .
