### ISSUE TITLE
helm plugin install status code when plugin is already installed

### ISSUE THREAD

**Issue by SandyChapman** [helm/helm#5387]
This is a general question about the behaviour of `helm plugin install` when a plugin has already been installed. Currently it returns an error code. This isn't intuitive to me. I think it'd be better if the status code from this is 0 and exiting successfully rather than throwing an error. Would the maintainers be open to changing this?

P.S.

Looks like it was added in this commit:

https://github.com/helm/helm/pull/2400/files#diff-0d989b436706dbe332f3428922784674

**Comment by bacongobbler** [comment]
I believe something like this would be considered a breaking change to the CLI, so it would not be accepted for Helm 2. Ref: https://github.com/helm/helm/blob/master/CONTRIBUTING.md#semantic-versioning

**Comment by bacongobbler** [comment]
That being said, this might be a nice and easy enhancement to be made for Helm 3.

**Comment by bacongobbler** [comment]
closing as inactive.

**Comment by mechtron** [comment]
Any way we can re-consider this for Helm 3? I'd like to remove the `|| true` after `helm plugin install` from my automation.

**Comment by bacongobbler** [comment]
At this point making the change would break backwards compatibility.

**Comment by gregbrowndev** [comment]
Could we add a CLI flag to change the behaviour without breaking backwards compatibility, e.g. `--ignore-if-already-exists` or something similar?
