### ISSUE TITLE
Does helm support something like profiles?

### ISSUE THREAD

**Issue by scaratec** [helm/helm#5388]
I'm currently creating a chart with many subcharts. The application is suppose to be deploy in multiple environments like dev, staging and prod. Most of the values will be shared but still many (default) values depend on the environment. 

My preferred way to organized this is to keep the environment specific values in separate files. The only way I know how I could realize this is to create control structures in the template files. 

However, this doesn't feel right. I think these values should come from the values.yaml but I can only provide one file.

What is the recommended way, to organized this? I'm pretty sure I'm not the first one with this challenge.

**Comment by jlegrone** [comment]
@scaratec helm supports passing in multiple values files. Taken from https://helm.sh/docs/helm/#helm-install:

> You can specify the `--values`/`-f` flag multiple times. The priority will be given to the last (right-most) file specified. For example, if both myvalues.yaml and override.yaml contained a key called ‘Test’, the value set in override.yaml would take precedence:
>
> ```cli
> $ helm install -f myvalues.yaml -f override.yaml ./redis
> ```

Remember that whatever is in the chart's top level `values.yaml` will be the default set of values and doesn't need to be passed in explicitly, so you may be able to just keep common configuration there and maintain a single overrides file for each target environment. For example:

```cli
$ helm upgrade --install myapp-staging -f staging-values.yaml ./charts/myapp
```

**Comment by scaratec** [comment]
Thank you very much!! This perfectly solved my issue!
