### ISSUE TITLE
Authentication problem when installing something

### ISSUE THREAD

**Issue by mtltechtemp** [helm/helm#5389]
Hi,

The command fails due to credentials problems, but when you test with `kubectl get nodes` everything looks fine.

Output of `helm install`
```
⋊> ~/t/mtltech on master ⨯ helm install --name nginx-ingress stable/nginx-ingress --set rbac.create=true                                                                                                   00:31:41
Error: the server has asked for the client to provide credentials
```
Output of `kubectl get nodes`
```
⋊> ~/t/mtltech on master ⨯ kubectl get nodes                                                                                                                                                               00:37:41
NAME                                       STATUS    ROLES     AGE       VERSION
gke-mtltech-default-pool-977ee0b2-5lmi   Ready     <none>    7h        v1.11.7-gke.4
gke-mtltech-default-pool-977ee0b2-hi4v   Ready     <none>    7h        v1.11.7-gke.4
gke-mtltech-default-pool-977ee0b2-mjiv   Ready     <none>    7h        v1.11.7-gke.4
```
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.7-gke.4", GitCommit:"618716cbb236fb7ca9cabd822b5947e298ad09f7", GitTreeState:"clean", BuildDate:"2019-02-05T19:22:29Z", GoVersion:"go1.10.7b4", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.):  `Google Cloud`

I've tried to reset it several times with `rm -rf ~/.helm && helm init --service-account tiller` but it doesn't change anything.

Any idea ?
Thanks.

**Comment by mtltechtemp** [comment]
Ping @technosophos

**Comment by bacongobbler** [comment]
How is your cluster set up? What authentication method does kubectl use to authenticate against the API server?

**Comment by bacongobbler** [comment]
To work around this, you could set up a `kubectl port-forward` to tiller, and use that alongside HELM_HOST. Under the covers, that's how Helm initiates a connection to tiller.

**Comment by mtltechtemp** [comment]
@bacongobbler I'm using the default authentication method.
I'm gonna try your workaround thanks.

**Comment by bacongobbler** [comment]
```
kubectl -n kube-system port-forward svc/tiller-deploy 44134:44134
```

And in another terminal:

```
export HELM_HOST=:44134
helm list
```

**Comment by mtltechtemp** [comment]
@bacongobbler I think i'm doing something wrong...
```
⋊> ~ kubectl -n kube-system port-forward svc/tiller-deploy 44134:44134                                                                                                                                              17:41:54
Forwarding from 127.0.0.1:44134 -> 44134
Forwarding from [::1]:44134 -> 44134
Handling connection for 44134
```

```
⋊> ~/D/demo export HELM_HOST=:44134                                                                                                           17:41:42
⋊> ~/D/demo helm list                                                                                                                         17:41:49
Error: Unauthorized
```
What did I miss?

**Comment by bacongobbler** [comment]
Looks like the `tiller` service account might not be able to access the Kubernetes API. Can you please make sure that the service account has the right permissions to access the API server?

**Comment by mtltechtemp** [comment]
@bacongobbler There's no `tiller` in my [IAM](https://console.cloud.google.com/project/_/iam-admin/iam).
Should i make one ?

**Comment by bacongobbler** [comment]
I'm not sure, sorry. You will have to chat with either the GKE folks or the community on how to properly configure RBAC so a pod bound to a particular service account can talk to the Kubernetes API. I'm more familiar with AKS/minikube than GKE/EKS.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
