### ISSUE TITLE
Helm 3: skip any template generated in a library chart

### ISSUE THREAD

**Issue by bacongobbler** [helm/helm#5396]
If a library chart defines any templates, those will still be rendered as part of the release. When a chart is declared as a library chart, any templates it defines should be skipped.

Originally suggested by @prydonius in https://github.com/helm/helm/issues/5085#issuecomment-465276189. Opening the ticket here to track the issue/discussion.

**Comment by hickeyma** [comment]
@bacongobbler I can help with this if thats ok?

**Comment by hickeyma** [comment]
This is the current workflow:
- If library chart and templates not defined, it will not be rendered as part of a release [backwards compatible]
- If library chart and `type: library` it will not be rendered as part of a release
- If library chart, `type: library` and templates defined, it will not be rendered as part of a release
- Regular chart, `type: library` and templates defined, it will not be rendered as part of a release

I am going to open a PR for the following:
- If library chart/regular chart which is a dependency, `type: library` and templates defined, it will not be rendered as part of a release
- Update the docs to mention library charts with templates defined/charts used as library charts

**Comment by hickeyma** [comment]
> If a library chart defines any templates, those will still be rendered as part of the release. 

@bacongobbler do you mean this: "If a library chart defines any templates, those will not be rendered as part of the release. "?

**Comment by bacongobbler** [comment]
> do you mean this

That sentence was written in the current context, so that wording was intentional but I can understand the confusion.

> this should be mostly covered by #5086

Did you mean to link to something else? #5086 refers to `helm lint --version`.

> Let me know if this sounds ok.

Sounds good but just to clarify: we still want to render the library chart so the helper functions are available for other charts. The templates the chart defines should not be installed, however.

**Comment by hickeyma** [comment]
> Did you mean to link to something else?

yes, #5085. Fixed comment above

**Comment by prydonius** [comment]
> If library chart/regular chart which is a dependency, type: library and templates defined, it will not be rendered as part of a release

Yeah, I believe this is the case currently not covered, so a PR to add this behaviour would be great!

**Comment by hickeyma** [comment]
@bacongobbler @prydonius PR #5441 opened

**Comment by bacongobbler** [comment]
fixed in #5441
