### ISSUE TITLE
Incorporate changes made in Helm 3 into the documentation

### ISSUE THREAD

**Issue by bacongobbler** [helm/helm#5397]
Many features have been introduced into Helm 3, but the documentation has been lagging a bit behind. We should take this opportunity to re-write the documentation to capture the new architecture and to provide a landing spot for contributors writing new features/breaking changes in Helm 3.

**Comment by hickeyma** [comment]
Some documentation has been updated during features and also under the following issues:
#5083, #4788

**Comment by bacongobbler** [comment]
Sections that need updating:

- [ ] All information pertaining to Chart Repositories
- [ ] [Developer Guide: "Structure of the Code"](https://github.com/helm/helm/blob/dev-v3/docs/developers.md#structure-of-the-code) needs updating
- [ ] [The History of the Project](https://github.com/helm/helm/blob/dev-v3/docs/history.md#the-history-of-the-project) should include information about Helm 2
- [ ] [Related Projects and Documentation](https://github.com/helm/helm/blob/dev-v3/docs/related.md) should be audited to only contain information related to Helm 3
- [ ] [The Kubernetes Distribution Guide](https://github.com/helm/helm/blob/dev-v3/docs/kubernetes_distros.md) should be re-evaluated

**Comment by bacongobbler** [comment]
@jdolitsky would you be interested in taking on the task of updating the documentation surrounding Chart Repositories and how Helm interacts with OCI registries?

**Comment by jdolitsky** [comment]
@bacongobbler yep, will try to get that out this week!

**Comment by bacongobbler** [comment]
fixed in #5718
