### ISSUE TITLE
Docs: write Helm 2 -> Helm 3 migration docs

### ISSUE THREAD

**Issue by bacongobbler** [helm/helm#5398]
We should have documentation available that provides a smooth migration path for Helm 2 users to familiarize what's been changed in Helm 3.

CC'ing @bridgetkromhout as I know you mentioned this to me during a call about what we should do with the docs.

related: #5397

Partial-Closes: #5892

**Comment by hickeyma** [comment]
I will help out with this.

**Comment by hickeyma** [comment]
Closing this as it is covered by #5892
