### ISSUE TITLE
helm init --listen flag

### ISSUE THREAD

**Issue by kfox1111** [helm/helm#5405]
Due to the security ramifications of tiller, I'd like to do the same trick that the magic-namespace chart does to secure things. Only allow the tiller pod to be accessed directly via port forward by binding it only to 127.0.0.1. Then RBAC can be used to restrict proxying to the pod.

Today you can edit the deployment of helm init with -o json but the --wait flag doesn't work with that model. So there is no simple way to helm init in a secure way, along with waiting for it to come up in a ci pipeline.

So, I propose a new flag --listen be added to helm init that will pass the flag and its argument to tiller in the pods argument property.

**Comment by bacongobbler** [comment]
Given that tiller has been removed in Helm 3, the core maintainers will not likely contribute a patch for this. However, I can see how this may be useful so if you want to contribute a path, feel free!

**Comment by bacongobbler** [comment]
no longer accepting features for helm 2.
