### ISSUE TITLE
tiller flags removed in 2.13.0 are not called out as breaking changes

### ISSUE THREAD

**Issue by iczman** [helm/helm#5408]
There are flags added and removed in 2.13.0 compared to 2.12.3. For example, `-alsologtostderr` is gone in 2.13.0.

Consider calling out flags removed as breaking changes in the changelog? I hit this bug when I upgraded my CI and it can no longer call tiller using `-alsologtostderr`.

**tiller 2.12.3**
```
$ tiller -h
Usage of tiller:
  -alsologtostderr
    	log to standard error as well as files
  -experimental-release
    	enable experimental release modules
  -history-max int
    	maximum number of releases kept in release history, with 0 meaning no limit
  -listen string
    	address:port to listen on (default ":44134")
  -log_backtrace_at value
    	when logging hits line file:N, emit a stack trace
  -log_dir string
    	If non-empty, write log files in this directory
  -logtostderr
    	log to standard error instead of files
  -stderrthreshold value
    	logs at or above this threshold go to stderr
  -storage string
    	storage driver to use. One of 'configmap', 'memory', or 'secret' (default "configmap")
  -tls
    	enable TLS
  -tls-ca-cert string
    	trust certificates signed by this CA (default "ca.crt")
  -tls-cert string
    	path to TLS certificate file (default "tls.crt")
  -tls-key string
    	path to TLS private key file (default "tls.key")
  -tls-verify
    	enable TLS and verify remote certificate
  -trace
    	enable rpc tracing
  -v value
    	log level for V logs
  -version
    	print the version number
  -vmodule value
    	comma-separated list of pattern=N settings for file-filtered logging
```

**tiller 2.13.0**
```
$ tiller -h
Usage of tiller:
  -experimental-release
    	enable experimental release modules
  -history-max int
    	maximum number of releases kept in release history, with 0 meaning no limit
  -listen string
    	address:port to listen on (default ":44134")
  -storage string
    	storage driver to use. One of 'configmap', 'memory', or 'secret' (default "configmap")
  -tls
    	enable TLS
  -tls-ca-cert string
    	trust certificates signed by this CA (default "ca.crt")
  -tls-cert string
    	path to TLS certificate file (default "tls.crt")
  -tls-key string
    	path to TLS private key file (default "tls.key")
  -tls-verify
    	enable TLS and verify remote certificate
  -trace
    	enable rpc tracing
  -version
    	print the version number
```

Output of `helm version`:

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by guizmaii** [comment]
Not only tiller but also helm commands options.

My `helm upgrade -i` doesn't work anymore:

```
++ helm upgrade -i ... stack_name app_name
UPGRADE FAILED
ROLLING BACK
Error: "stack_name" has no deployed releases
Error: UPGRADE FAILED: "stack_name" has no deployed releases
```

**Comment by bacongobbler** [comment]
@guizmaii let's follow up in #5410. That's not a regression :)

Good catch, @iczman. It doesn't look like we ever explicitly added that flag to Tiller, so it was a transitive dependency that made the breaking change.

Here's the flags in 2.12.3: https://github.com/helm/helm/blob/eecf22f77df5f65c823aacd2dbd30ae6c65f186e/cmd/tiller/tiller.go#L77-L87

and the same flags in 2.13.0: https://github.com/helm/helm/blob/79d07943b03aea2b76c12644b4b54733bc5958d6/cmd/tiller/tiller.go#L77-L87

If you can nail down where exactly `--alsologtostderr` came from, we can see what we can do to patch that back in. Perhaps this was related to the gRPC update done in #5210. cc @technosophos

**Comment by bacongobbler** [comment]
From your output, it also looks like the `--log_backtrace_at`, `--log_dir`, `--stderrthreshold` and `--vmodule` flag went poof as well.

**Comment by jlegrone** [comment]
Looks like these may be coming from https://godoc.org/github.com/golang/glog, which was removed in https://github.com/helm/helm/pull/5033.

**Comment by bacongobbler** [comment]
Thanks @jlegrone. That appears to be it.

Please see #5411 for the fix.
