### ISSUE TITLE
Helm Init without any repo

### ISSUE THREAD

**Issue by Jdavid7x** [helm/helm#5409]
Helm version: 2.12.3

We want to execute helm init in client-only without the stable or another repo. 
I saw the option -dry-run but this doesn't create the repository structure and if I try the helm fetch this raise an error because it can't found the repository structure. 

```
Error: Couldn't load repositories file (/root/.helm/repository/repositories.yaml).
You might need to run `helm init` (or `helm init --client-only` if tiller is already installed) 
```

We are removing the repo stable just after execute helm init. I would propose to add some option for initialize the repository structure without any repo definition inside.

**Comment by hickeyma** [comment]
You could specify your own stable repo instead with this flag: `--stable-repo-url <path_to_your_repo>`

[helm init doc](https://helm.sh/docs/helm/#helm-init) for more details

**Comment by bridgetkromhout** [comment]
Hi, @Jdavid7x - `helm init` no longer exists in Helm 3, and we are only accepting bugfixes for Helm 2, so we won't be making a change to `helm init`. (See the migration doc for more details: https://helm.sh/docs/topics/v2_v3_migration/#overview-of-helm-3-changes). More detail about the v2 version can be found at https://v2.helm.sh/docs/helm/#helm-init if you'd prefer to use @hickeyma's workaround. Thanks for reaching out!
