### ISSUE TITLE
Checking for all the values in a template files are defined fails when using helm lint --strict

### ISSUE THREAD

**Issue by walkafwalka** [helm/helm#5417]
It took a bit of digging but there are multiple tickets of users reporting `[ERROR] templates/: render error in ... <.Values.KeyName>: map has no entry for key "KeyName"` when using `helm lint --strict`. It is solved by setting a default value type for empty default values such as `[]`, `{}` or `""`.

It seems that this check was supposed to be disabled based on https://github.com/helm/helm/issues/1463. I think this is confusing because `map has no entry for key` is being treated as a warning and displayed as an error when using `--strict`. I think it should either:
- Be removed completely as desired in https://github.com/helm/helm/issues/1463
- Be treated as an error and cause `helm lint` to fail
- Be treated as a warning and display in `helm lint` with `[WARNING]` and failed in `helm lint --strict`

Helm version: `v2.13.0-rc.2`

**Comment by hickeyma** [comment]
Tested this and it seems to be working as appropriately. Tests as follows:

Created a scaffold chart using `helm create`.  Disabled the `service` map entries:

```console
[.....]
service:
        #type: ClusterIP
        #port: 80
[.....]
```

Tested as follows:

```console
$ helm lint tstchart/
==> Linting tstchart/
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: render error in "tstchart/templates/tests/test-connection.yaml": template: tstchart/templates/tests/test-connection.yaml:17:61: executing "tstchart/templates/tests/test-connection.yaml" at <.Values.service.port>: can't evaluate field port in type interface {}

Error: 1 chart(s) linted, 1 chart(s) failed
$ helm lint --strict tstchart/
==> Linting tstchart/
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: render error in "tstchart/templates/tests/test-connection.yaml": template: tstchart/templates/tests/test-connection.yaml:17:61: executing "tstchart/templates/tests/test-connection.yaml" at <.Values.service.port>: map has no entry for key "service"

Error: 1 chart(s) linted, 1 chart(s) failed
$ helm template tstchart/
Error: render error in "tstchart/templates/tests/test-connection.yaml": template: tstchart/templates/tests/test-connection.yaml:17:61: executing "tstchart/templates/tests/test-connection.yaml" at <.Values.service.port>: can't evaluate field port in type interface {}
```
Can you provide more details of as specific example with the issue?

**Comment by walkafwalka** [comment]
@hickeyma That is a different error. You are looking for `<.Values.KeyName>: map has no entry for key "KeyName"`. Reference a value as `{{ .Values.KeyName }}` and leave the value undefined in values.yaml. It will not display a warning when using `helm lint`, but will fail in `helm --strict` but use the `[ERROR]` tag.

**Comment by hickeyma** [comment]
@walkafwalka Thanks for clarifying. I am able to reproduce now.

Template:
```console
$ cat mychart1/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  drink: {{ .Values.favoriteDrink }}
```

Values:
```console
$ cat mychart1/values.yaml
#favoriteDrink: coffee
```

Tested as follows:
```console
$ helm lint mychart1/
==> Linting mychart1/
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, no failures

$ helm lint --strict mychart1/
==> Linting mychart1/
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: render error in "mychart1/templates/configmap.yaml": template: mychart1/templates/configmap.yaml:7:19: executing "mychart1/templates/configmap.yaml" at <.Values.favoriteDrin...>: map has no entry for key "favoriteDrink"

Error: 1 chart(s) linted, 1 chart(s) failed

$ helm template mychart1/
---
# Source: mychart1/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-configmap
data:
  myvalue: "Hello World"
  drink: 

$ helm install mychart1/
NAME:   excited-manatee
LAST DEPLOYED: Mon Mar 11 09:29:16 2019
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/ConfigMap
NAME                       DATA  AGE
excited-manatee-configmap  2     0s
```

I can see how this would be confusing. I wonder would it make more sense for issues raised by linter in `strict` mode to be "warnings" if they are not an error for rendering and install? @bacongobbler what do you think?

**Comment by walkafwalka** [comment]
@hickeyma Exactly! In addition to being labeled as warnings in strict mode, I think they should also be displayed as warnings by the linter in non-strict mode without failing similarly to informational messages.

**Comment by hickeyma** [comment]
@walkafwalka would you be interested in doing a PR for this?

**Comment by walkafwalka** [comment]
I actually tried to look for the why this was happening but I failed. I am not very familiar with Helm's code. I  found the this line in kubernetes: https://github.com/kubernetes/kubernetes/blob/master/test/cmd/get.sh#L173.

Though I cannot tell how this ties into Helm or why https://github.com/helm/helm/pull/1730 did not fix the issue. I thought that only the errors defined here were caught: https://github.com/helm/helm/blob/master/pkg/lint/rules/chartfile.go

**Comment by hickeyma** [comment]
The linter fails [here](https://github.com/helm/helm/blob/master/pkg/lint/rules/template.go#L83) The error seems to be generated when the linter calls the go template library to render the template[here](https://github.com/helm/helm/blob/master/pkg/engine/engine.go#L278). When this is called in `strict` mode, it requires the value object to be set.

If this is the case then it is working as expected.

**Comment by walkafwalka** [comment]
Oh, I see. I did not expect that there.

Maybe we can move the strict logic out of [renderWithReferences](https://github.com/helm/helm/blob/master/pkg/engine/engine.go#L231) and back into [Templates](https://github.com/helm/helm/blob/master/pkg/lint/rules/template.go#L111) as a warning.

**Comment by walkafwalka** [comment]
Or maybe we should remove the logic from [renderWithReferences](https://github.com/helm/helm/blob/master/pkg/engine/engine.go#L231)?

Should missing keys even a be warning?
- If yes, should we restore the old logic so that it warns on `helm lint` and fails on `--strict`?
- If no, should we remove the error from the renderer?
- Should we downgrade it to an informational message?

**Comment by hickeyma** [comment]
@walkafwalka Do you want to create a PR and give it a go?

**Comment by awprgrmmr** [comment]
Yes, I have something almost complete. Hopefully should have something ready for review by next week.

**Comment by walkafwalka** [comment]
@hickeyma Sure. Do you want me to remove the error or do you want me to change it to a warning?

**Comment by bacongobbler** [comment]
closing as inactive.
