### ISSUE TITLE
Feature Suggestion: Unit Tests

### ISSUE THREAD

**Issue by walkafwalka** [helm/helm#5424]
Unfortunately, https://github.com/lrills/helm-unittest is not being actively maintained anymore but this is something I think would be a good fit for the core project.

**Comment by hickeyma** [comment]
Thanks for the suggestion.

Helm currently has [chart test](https://github.com/helm/helm/blob/master/docs/chart_tests.md) capability. What therefore would be the benefits of integrating [helm-unittest](https://github.com/lrills/helm-unittest ) into core as well?

**Comment by walkafwalka** [comment]
@hickeyma, the chart test capability will "validate that your chart works as expected when it is installed" whereas helm-unittest will validate that a chart is rendered _locally_ correctly using unit tests. Chart repository maintainers can use unit tests to verify specified values result in the correct behavior or contributor changes do not result in incorrect behavior. For example, you could verify that the ingress is disabled when the value `ingress.enabled` is set to false.

**Comment by hickeyma** [comment]
Thanks for the feedback.

@mattfarina what do you think?

**Comment by mattfarina** [comment]
@walkafwalka @hickeyma I like this idea. @michelleN has been working on the testing for Helm v3. It might be good to talk with her about it.

**Comment by jgoeres** [comment]
How is this proposal coming along? We are working on a Helmchart with ever-increasing complexity and the helmunit project (or the fork mentioned by @walkafwalka ) seem a promising approach to run unit tests that do not require an actual cluster to be up and running. IMO, having it as part of the helm core would really strengthen helm's appeal for use in enterprise-grade deployment scenarios.

**Comment by hickeyma** [comment]
@walkafwalka Just wondering if you got a chance to work anymore on the proposal?

**Comment by walkafwalka** [comment]
So the original creator returned so I backed off of this project, but he is gone again.
Now, I do not have time to take up this project. I still actively use Helm and I still think this would be very variable.

**Comment by hickeyma** [comment]
Ok, that would be great if you can work on it @walkafwalka

**Comment by shaikatz** [comment]
Hi @hickeyma, 
I will be happy to help with integrating the helm-unittest which we actively using, into the helm core.
It requires some PR and issues fixes, that I can make sure to be done.

What would be the steps in order to bring it into helm?

**Comment by hickeyma** [comment]
@shaikatz Can you draft a proposal in an issue detailing what you are thinking of integrating? This would help maintainers understand better.

**Comment by quintush** [comment]
> @shaikatz Can you draft a proposal in an issue detailing what you are thinking of integrating? This would help maintainers understand better.

If it will help, my [fork](https://github.com/quintush/helm-unittest) van be used as a base. The code base is a bit more aligned to the current helm code base. Also numerous bugfixes and requested features are implemented, included with unittests and documentation. 

The documentation can even help to cherrypick features, if not all features are preferred.

Greetings @quintush.

**Comment by mik-laj** [comment]
Hello,

In the Apache Airflow project, we made the decision to use [Python tests](https://github.com/lrills/helm-unittest/issues/110) supported by a small function that is used to generate templates. Alternatively, you can use the [terratest](https://blog.gruntwork.io/automated-testing-for-kubernetes-and-helm-charts-using-terratest-a4ddc4e67344) if you prefer Go.

Best regards,
Kamil Breguła

**Comment by crunchtime-ali** [comment]
IMO this should be a core feature. I am with @walkafwalka that one of the forks of lrills/helm-unittest should be included.

**Comment by jgoeres** [comment]
I still think is a very relevant topic for any degree of "enterprise readiness".

**Comment by yariksheptykin** [comment]
See also these relevant discussions on the mailing list:

- https://lists.cncf.io/g/cncf-helm/message/363
- https://lists.cncf.io/g/cncf-helm/message/281

Suggested tools are:

- https://github.com/open-policy-agent/conftest
- https://github.com/instrumenta/helm-conftest
- https://github.com/gruntwork-io/terratest ([Blogpost](https://blog.gruntwork.io/automated-testing-for-kubernetes-and-helm-charts-using-terratest-a4ddc4e67344))
