### ISSUE TITLE
Feature request: `helm install CHART` use the valueFiles inside the chart (other than the default values.yaml)

### ISSUE THREAD

**Issue by dhanvi** [helm/helm#5429]
It would be nice to use the valueFiles inside the helm chart (other than values) so that the only thing required during the deploy time is the chart in tgz format.

**Comment by hickeyma** [comment]
I am not sure that this is a use case of a Helm chart. The concept of the chart is that it can be configured on the fly and default values are provided otherwise.

In your case, this is probably best handled with another tool, for example [helmfile](https://github.com/roboll/helmfile).

**Comment by dhanvi** [comment]
IMHO ability to store and utilize different sets of values.yaml would make the charts truly portable.

Currently we are already storing all the values in the packaged charts (chart.tgz)

May be adding a different flag or reusing the same flag `-f`

**Comment by jeff-knurek** [comment]
> I am not sure that this is a use case of a Helm chart. The concept of the chart is that it can be configured on the fly and default values are provided otherwise

I disagree with the first statement, but I don't think it contradicts the second. 
and you're right @hickeyma, that something like `helmfile` is usually the best approach. 

there is a .helmignore file which allows for excluding files from the packaged chart, but when it comes to values files, it makes the most sense for them to be kept close to the chart, and therefor packaged with the chart. And then being able to access what is packed with the chart with a flag just makes sense to be a feature....

Also, i think when thinking of this problem, the fact that something similar had to be built for the CI tests is an indication that this request wasn't a use case that was thought of in the original idea of helm, but is now required based on usage of the tool: https://github.com/helm/charts/tree/master/test#providing-custom-test-values

----
however, in the end, this is a duplicate of 
https://github.com/helm/helm/issues/4782 and should be closed

**Comment by dhanvi** [comment]
Thank You @jeff-knurek and @hickeyma 

Apologies for opening a duplicate issue.

**Comment by hickeyma** [comment]
> there is a .helmignore file which allows for excluding files from the packaged chart, but when it comes to values files, it makes the most sense for them to be kept close to the chart, and therefor packaged with the chart. And then being able to access what is packed with the chart with a flag just makes sense to be a feature....

@jeff-knurek I think you make a valid point here and I agree with it from a practical point of view. However, imho Helm provides charts which are "a collection of files that describe a related set of Kubernetes resources."  It can be deployed as is OOTB with default values but maybe the idea was that each deployment could be configured differently depending on environments, different users (charts shared in repos) and multiple instances within a cluster. In other words, the ability to be flexible.

I suppose to have the ability to add values files within a package in addition, is also useful capabiliuty to provide. Thanks for the feedback.
