### ISSUE TITLE
Can't evaluate field password in type interface {}

### ISSUE THREAD

**Issue by tashirj** [helm/helm#5435]
I am facing the issue in version 2.12.3
My values YAML structure is like:
values.yaml

```
global:
  configMap:
    properties:
      my:
        services:
          war:
            truststore:
              password: abcxyz
```

Error: can't evaluate field password in type interface {} while accessing the value as: "Values.global.configMap.properties.my.services.war.truststore.password"

helm version

```
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
```

kubectl version

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.5", GitCommit:"51dd616cdd25d6ee22c83a858773b607328a18ec", GitTreeState:"clean", BuildDate:"2019-01-16T18:24:45Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.5", GitCommit:"51dd616cdd25d6ee22c83a858773b607328a18ec", GitTreeState:"clean", BuildDate:"2019-01-16T18:14:49Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
```

Does anybody have any fix for this?

**Comment by hickeyma** [comment]
You will need to structure the content.  You can structure it as follows:
```
global:
  configMap:
    properties:
      my:
        services:
          war:
            truststore:
              password: abcxyz
```
Refer to [value best practices](https://helm.sh/docs/chart_best_practices/#values) for more details. FYI, this is probably way more nested layers than would be common. Maybe look to see if you can simplify it.

**Comment by bacongobbler** [comment]
The original comment contained the right structure, however all leading whitespace was trimmed out so the content was displayed as unstructured. I edited OP's comment to demonstrate the values structure, wrapping backticks around the output.

**Comment by hickeyma** [comment]
Ok, thanks @bacongobbler.

It is working as expected but I will show how I tested it.

Template and value:

```console
$ cat mychart2/values.yaml 
favorite:
  drink: coffee
  food: pizza

global:
  configMap:
    properties:
      my:
        services:
          war:
            truststore:
              password: abcxyz

$ cat mychart2/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
myvalue: "Hello World"
drink: {{ .Values.favorite.drink }}
food: {{ .Values.favorite.food }}
password: {{ .Values.global.configMap.properties.my.services.war.truststore.password }}
```

Output:

```console
$ helm install --debug --dry-run mychart2/
[debug] Created tunnel using local port: '37429'

[debug] SERVER: "127.0.0.1:37429"

[debug] Original chart version: ""
[debug] CHART PATH: /home/usr1/test/helm-charts/mychart2

NAME:   belligerent-swan
REVISION: 1
RELEASED: Tue Mar 12 17:16:37 2019
CHART: mychart2-0.1.0
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
favorite:
  drink: coffee
  food: pizza
global:
  configMap:
    properties:
      my:
        services:
          war:
            truststore:
              password: abcxyz

HOOKS:
MANIFEST:

---
# Source: mychart2/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: belligerent-swan-configmap
data:
myvalue: "Hello World"
drink: coffee
food: pizza
password: abcxyz
```

**Comment by hickeyma** [comment]
@tashirj Let me know if this works for you. If not, can you provide me with more details on how you are accessing the value.

**Comment by tashirj** [comment]
Thanks @bacongobbler for the changes for making it appropriate.
@hickeyma I tested the same and for tests, it is working. But if the same is used in the whole deployment, it doesn't pick the value up somehow. May be I am messing up in the YAML spacing.
Will check it :) 
Thanks a lot :)

**Comment by dkrieger** [comment]
I was getting this same error message, and what caused it in my case was the overrides for a sibling chart in the parent values.yaml . assume subcharts "firstborn" and "secondborn":

```
global:
  foo: bar
firstborn:
  hello: world
secondborn:
- foo
- bar
```

the override for secondborn chart implicitly deletes the global object. This can be avoided by making sure to specify chart value overrides as an object:

```
global:
  foo: bar
firstborn:
  hello: world
secondborn:
  stuff:
  - foo
  - bar
```

**Comment by tashirj** [comment]
@dkrieger , I am not sure if this can be used in deployments as the placeholders used for the deployments will map those to values file and if this overriding has to be done, you will have to change the placeholders accordingly.

**Comment by dkrieger** [comment]
@tashirj the takeaway here is that charts that don't follow this rule are broken.

**Comment by tashirj** [comment]
@dkrieger I am not using any third-party charts, all are mine but I can't modify those at the run time since the mapping used are tightly coupled. 
Thanks for clearing the doubts :)

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

**Comment by tutaidalal** [comment]
I was trying to make a value optional, Like i have only A in the default values.yaml, Now in deployment YAML iwas checking for a optioan value A.B.C and got this error. Solved by adding a dummy value under B, but looks like if the immediate parent is not available in default values.yaml then its a problem. Is there any other way to avoid the dummy value?
