### ISSUE TITLE
Alternatives to helm?

### ISSUE THREAD

**Issue by 0verc1ocker** [helm/helm#5439]
1. Why is helm such trash?

2. What are some alternatives to helm?

**Comment by Stono** [comment]
3. Where's your open source repo contribution doing better?

**Comment by Stono** [comment]
4. Where are your PR's contributing to making the helm better?

**Comment by 0verc1ocker** [comment]
>  4. Where are your PR's contributing to making the helm better?

The more you focus your mind on trash, the more garbage your mind becomes.

**Comment by bacongobbler** [comment]
I'm locking the conversation it is violating the Code of Conduct for inappropriate/unprofessional conduct.
