### ISSUE TITLE
Tiller pod CrashLoopBackoff - exec format error

### ISSUE THREAD

**Issue by diederichm** [helm/helm#5444]
Output of `helm version`:

Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
out of
https://storage.googleapis.com/kubernetes-helm/helm-v2.13.0-linux-s390x.tar.gz

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.5", GitCommit:"51dd616cdd25d6ee22c83a858773b607328a18ec", GitTreeState:"clean", BuildDate:"2019-01-16T18:24:45Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/s390x"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/s390x"}

docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.7
 Git commit:        e68fc7a215d7
 Built:             Wed Dec 19 10:26:55 2018
 OS/Arch:           linux/s390x
 Experimental:      true

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.7
  Git commit:       e68fc7a215d7
  Built:            Tue Aug 21 17:16:31 2018
  OS/Arch:          linux/s390x
  Experimental:     false

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
None

STEPS TO REPRODUCE 
download above git version, unpack, copy helm to /usr/loca/bin

"helm init"
Creating /root/.helm 
Creating /root/.helm/repository 
Creating /root/.helm/repository/cache 
Creating /root/.helm/repository/local 
Creating /root/.helm/plugins 
Creating /root/.helm/starters 
Creating /root/.helm/cache/archive 
Creating /root/.helm/repository/repositories.yaml 
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com 
Adding local repo with URL: http://127.0.0.1:8879/charts 
$HELM_HOME has been configured at /root/.helm.

Tiller (the Helm server-side component) has been installed into your Kubernetes Cluster.

Please note: by default, Tiller is deployed with an insecure 'allow unauthenticated users' policy.
To prevent this, run `helm init` with the --tiller-tls-verify flag.
For more information on securing your installation see: https://docs.helm.sh/using_helm/#securing-your-helm-installation
Happy Helming!

kubectl get pods -n kube-system
...
tiller-deploy-6d6cc8dcb5-nq2hk          0/1     CrashLoopBackOff   3          63s

# kubectl logs tiller-deploy-6d6cc8dcb5-nq2hk -n kube-system
standard_init_linux.go:190: exec user process caused "exec format error"

when run tiller manually - it looks fine
# ./tiller 
[main] 2019/03/14 10:41:35 Starting Tiller v2.13.0 (tls=false)
[main] 2019/03/14 10:41:35 GRPC listening on :44134
[main] 2019/03/14 10:41:35 Probes listening on :44135
[main] 2019/03/14 10:41:35 Storage driver is ConfigMap
[main] 2019/03/14 10:41:35 Max history per release is 0
^C

So even though it is built, there is no image ?

**Comment by hickeyma** [comment]
If you want to install tiller on a Kubernetes cluster running on 390x architecture you'll need to compile tiller from source with support for that architecture, then provide that image name using helm init --tiller-image.  Have a look at the [instructions for building Tiller for z](https://github.com/linux-on-ibm-z/docs/wiki/Building-Helm).

This is a duplicate of #5197. More details in https://github.com/helm/helm/issues/5197#issuecomment-456466600

**Comment by diederichm** [comment]
Well,
tiller is already compiled. There is no need to build it.
(it is in here https://storage.googleapis.com/kubernetes-helm/helm-v2.13.0-linux-s390x.tar.gz)
i can run from the cli just fine.
[main] 2019/03/14 10:41:35 Starting Tiller v2.13.0 (tls=false)
[main] 2019/03/14 10:41:35 GRPC listening on :44134
[main] 2019/03/14 10:41:35 Probes listening on :44135
[main] 2019/03/14 10:41:35 Storage driver is ConfigMap
[main] 2019/03/14 10:41:35 Max history per release is 0

What is missing is the docker image.
I was assuming this was an oversight ?

**Comment by hickeyma** [comment]
AFIK, Tiller is not built for all architectures and sometimes you have to do this manually. It all depends on whether Tiller docker image is multi-arch enabled and even so, is s390x image part of it and most images don't support s390x yet.

@cwsolee Can you provide more details.

**Comment by diederichm** [comment]
Ok, i made this work for me - 
downloaded and extracted https://storage.googleapis.com/kubernetes-helm/helm-v2.13.0-linux-s390x.tar.gz

docker build using this Dockerfile :
```
FROM` alpine:3.7

RUN apk update && apk add ca-certificates socat && rm -rf /var/cache/apk/*

ENV HOME /tmp

COPY helm /helm
COPY tiller /tiller

EXPOSE 44134
USER 65534
ENTRYPOINT ["/tiller"]
```

pushed this into my docker repo
ran 

```
helm init --tiller-image diederichm/helm213:latest
$HELM_HOME has been configured at /root/.helm.

Tiller (the Helm server-side component) has been installed into your Kubernetes Cluster.

Please note: by default, Tiller is deployed with an insecure 'allow unauthenticated users' policy.
To prevent this, run `helm init` with the --tiller-tls-verify flag.
For more information on securing your installation see: https://docs.helm.sh/using_helm/#securing-your-helm-installation
Happy Helming!

```
