### ISSUE TITLE
Authentication for chart package tgz url

### ISSUE THREAD

**Issue by eroji** [helm/helm#5450]
I am trying to host charts using BitBucket repo that requires basic authentication. How do I create the URL entry in index.yaml so that the packaged charts can be retrieved properly?

**Comment by hickeyma** [comment]
@eroji Did you look at the [chart repo docs](https://github.com/helm/helm/blob/master/docs/chart_repository.md)?

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
