### ISSUE TITLE
Different status between helm and kubernetes.

### ISSUE THREAD

**Issue by nihongi** [helm/helm#5467]
I dont know if this is bug or feature request.

kubernetes: v1.11.6
helm: v2.11

how to reproduce:
1. Create deployment chart and pvc chart seperately
2. helm install pvc
3. helm install deployment (which mounts the pvc as a volume.)
4. helm delete pvc (In kubernetes, the pvc remains TERMINATING, because of StorageObjectInUseProtection.)
5. helm list (The release of the pvc is not present.)

Isn't it better to retain the helm release until all related resources are completely deleted ?

**Comment by bacongobbler** [comment]
By default, helm does not wait for all resources to be cleaned up before it exits. You can use the `--wait` flag if you wish to wait for all the resources to be deleted.

**Comment by nihongi** [comment]
Thanks, but it doesn't work for me.

helm delete --tls --tiller-namaspace myspace --wait pvc
Error: unknown flag: --wait

**Comment by bacongobbler** [comment]
We are no longer accepting bug fixes for Helm 2. See https://helm.sh/blog/helm-v2-deprecation-timeline/ for more details.
