### ISSUE TITLE
https://raw.githubusercontent.com/helm/helm/master/scripts/get script fails - SHA1 verification failure - aborts

### ISSUE THREAD

**Issue by Andycharalambous** [helm/helm#5477]
The SHA1 verification of the helm binary downloaded via the script at https://raw.githubusercontent.com/helm/helm/master/scripts/get fails as of today. I'm using this method to install helm on CircleCI build job and it's been working great but now it's failing everytime. I tried it on my own machine and the script aborts as well.

```Downloading https://kubernetes-helm.storage.googleapis.com/helm-tooltipped-s-linux-amd64.tar.gz
SHA sum of /tmp/helm-installer-Nkn4p1/helm-tooltipped-s-linux-amd64.tar.gz does not match. Aborting.
Failed to install helm
	For support, go to https://github.com/helm/helm.```

**Comment by bacongobbler** [comment]
I can confirm this as well. I think it may have to do something with a change in the github release URL that we're scraping to fetch the latest release number. I'll take a closer look.

**Comment by bacongobbler** [comment]
Yep, identified the issue. Patch incoming

**Comment by bacongobbler** [comment]
@Andycharalambous please give #5478 a try. Basically Github's release page was updated which is what the get script relies on to fetch the correct version. I had to add an additional check to the get script to strip out further href links that were added to the releases page.

**Comment by Andycharalambous** [comment]
Still not working on circleci - but I will try the DESIRED_VERSION work around - probably just a stale cache issue on there.

Thanks.

**Comment by rodrigc** [comment]
Instead of scraping the web page, why not use the GitHub API?

https://api.github.com/repos/helm/helm/releases/latest

**Comment by bacongobbler** [comment]
The issue with relying on the GitHub API for a global download script is the issue of being rate limited. Unauthenticated requests to the GitHub API requires the use of an API key, or you will be limited by a global 60 requests per second. It's ideal for CI operators but it is not a good experience for first timers looking for an out of the box experience for installing Helm.

We'd consider supporting a get script that relied on the GitHub API... Assuming someone was interested in contributing that work. Hint hint ;)

**Comment by rodrigc** [comment]
@bacongobbler https://github.com/helm/helm/pull/5479

**Comment by erziasd** [comment]
Another workaround that I'm using is giving the desired version for the script as a parameter, like so:
`curl -fsSL https://raw.githubusercontent.com/helm/helm/master/scripts/get | bash -s -- -v v2.13.0`

**Comment by rodrigc** [comment]
Going with https://github.com/helm/helm/pull/5479 simplifies the parsing logic in the get script, because api.github.com returns JSON.

Although there are API limits, according to https://developer.github.com/v3/#rate-limiting :

```
For unauthenticated requests, the rate limit allows for up
to 60 requests per hour. Unauthenticated requests are associated
with the originating IP address, and not the user making requests.
```

I doubt that more than 60 requests per hour are running the helm get script from the same IP address.   So for an initial solution for helm, I think that https://github.com/helm/helm/pull/5479 is OK.

**Comment by bacongobbler** [comment]
It is NOT okay to rely on api.github.com for general consumption. There are organizations that will hit that rate limit often and frequently (example: in a CI environment run against each push to a PR). We'd be happy to maintain that as a feature flag but not for general use.

**Comment by edwardmabuyo** [comment]
Same issue.
```
Downloading https://kubernetes-helm.storage.googleapis.com/helm-tooltipped-s-linux-amd64.tar.gz
SHA sum of /tmp/helm-installer-qi8WPU/helm-tooltipped-s-linux-amd64.tar.gz does not match. Aborting.
Failed to install helm
	For support, go to https://github.com/helm/helm.
```

**Comment by dkmbw** [comment]
Same issue. Couldn't you make a helm.github.io page mit release data and download links which is easier to parse? that you could generate automatically also...

**Comment by guizmaii** [comment]
Same here

**Comment by rodrigc** [comment]
@bacongobbler you haven't convinced that enough users are downloading the Helm get script to trigger the GitHub API rate limits.

However, if it is a concern, then I would suggest that *after* a Helm release is made,
take the output of https://api.github.com/repos/helm/helm/releases

and saving it as a gist.  That way you would have a well formed file that is easy to parse, and you would not hit the api.github.com rate limits.

The patch you have in https://github.com/helm/helm/pull/5478 is fragile, and will break again if/when Github changes the HTML on their site.

**Comment by guizmaii** [comment]
When the fix will be available ? It's still failing :/

**Comment by bacongobbler** [comment]
The fix was merged in #5478. Please give it another try.

**Comment by guizmaii** [comment]
@bacongobbler It works now. Thanks

**Comment by lrevnic** [comment]
Hi, I have the same issue for 2.8.x Helm versions. Is it just me? 
Thank you

**Comment by frankdavidcorona** [comment]
Our company are using CircleCI, and we're having the same issue:
```
Helm og:image is available. Changing from version v2.16.6.
Downloading https://kubernetes-helm.storage.googleapis.com/helm-og:image-linux-amd64.tar.gz
./get.sh: line 136: openssl: command not found
SHA sum of /tmp/helm-installer-caOBEj/helm-og:image-linux-amd64.tar.gz does not match. Aborting.
Failed to install helm with the arguments provided: -v v2.16.6
```

Add to this, that we're using a custom .sh to download and install this package:
```
downloadFile() {
  HELM_DIST="helm-$TAG-$OS-$ARCH.tar.gz"
  DOWNLOAD_URL="https://kubernetes-helm.storage.googleapis.com/$HELM_DIST"
  CHECKSUM_URL="$DOWNLOAD_URL.sha256"
  HELM_TMP_ROOT="$(mktemp -dt helm-installer-XXXXXX)"
  HELM_TMP_FILE="$HELM_TMP_ROOT/$HELM_DIST"
  HELM_SUM_FILE="$HELM_TMP_ROOT/$HELM_DIST.sha256"
  echo "Downloading $DOWNLOAD_URL"
  if type "curl" > /dev/null; then
    curl -SsL "$CHECKSUM_URL" -o "$HELM_SUM_FILE"
  elif type "wget" > /dev/null; then
    wget -q -O "$HELM_SUM_FILE" "$CHECKSUM_URL"
  fi
  if type "curl" > /dev/null; then
    curl -SsL "$DOWNLOAD_URL" -o "$HELM_TMP_FILE"
  elif type "wget" > /dev/null; then
    wget -q -O "$HELM_TMP_FILE" "$DOWNLOAD_URL"
  fi
}

# installFile verifies the SHA256 for the file, then unpacks and
# installs it.
installFile() {
  HELM_TMP="$HELM_TMP_ROOT/$PROJECT_NAME"
  local sum=$(openssl sha1 -sha256 ${HELM_TMP_FILE} | awk '{print $2}')
  local expected_sum=$(cat ${HELM_SUM_FILE})
  if [ "$sum" != "$expected_sum" ]; then
    echo "SHA sum of ${HELM_TMP_FILE} does not match. Aborting."
    exit 1
  fi

  mkdir -p "$HELM_TMP"
  tar xf "$HELM_TMP_FILE" -C "$HELM_TMP"
  HELM_TMP_BIN="$HELM_TMP/$OS-$ARCH/$PROJECT_NAME"
  TILLER_TMP_BIN="$HELM_TMP/$OS-$ARCH/$TILLER_NAME"
  echo "Preparing to install $PROJECT_NAME and $TILLER_NAME into ${HELM_INSTALL_DIR}"
  runAsRoot cp "$HELM_TMP_BIN" "$HELM_INSTALL_DIR"
  echo "$PROJECT_NAME installed into $HELM_INSTALL_DIR/$PROJECT_NAME"
  if [ -x "$TILLER_TMP_BIN" ]; then
    runAsRoot cp "$TILLER_TMP_BIN" "$HELM_INSTALL_DIR"
    echo "$TILLER_NAME installed into $HELM_INSTALL_DIR/$TILLER_NAME"
  else
    echo "info: $TILLER_NAME binary was not found in this release; skipping $TILLER_NAME installation"
  fi
}
```

**Comment by frankdavidcorona** [comment]
Our company is using CircleCI and get.sh provided by the Helm team, but now after a while without requested updates in our infrastructure, we're getting this error:

```
Helm og:image is available. Changing from version v2.16.6.
Downloading https://kubernetes-helm.storage.googleapis.com/helm-og:image-linux-amd64.tar.gz
./get.sh: line 136: openssl: command not found
SHA sum of /tmp/helm-installer-caOBEj/helm-og:image-linux-amd64.tar.gz does not match. Aborting.
Failed to install helm with the arguments provided: -v v2.16.6
```

**Comment by bobrot** [comment]
> 
> 
> Hi, I have the same issue for 2.8.x Helm versions. Is it just me?
> Thank you

I'm having the same issue as well. Trying to upgrade to the latest 2 version.

**Comment by bobrot** [comment]
What is
HELM_DIST="helm-$TAG-$OS-$ARCH.tar.gz" 

What should be
HELM_DIST="helm-v$TAG-$OS-$ARCH.tar.gz"

**Comment by bacongobbler** [comment]
@bobrot please demonstrate what issue you are seeing.

I just tested in a basic docker container with both `get` and `get-helm-3`. Both worked fine.

```
~ ><> docker run -it ubuntu
root@1ec64581ce19:/# apt update && apt install curl
...
Running hooks in /etc/ca-certificates/update.d...
done.
root@1ec64581ce19:/# curl https://raw.githubusercontent.com/helm/helm/master/scripts/get | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7160  100  7160    0     0  66915      0 --:--:-- --:--:-- --:--:-- 66915
Downloading https://get.helm.sh/helm-v2.16.12-linux-amd64.tar.gz
Preparing to install helm and tiller into /usr/local/bin
helm installed into /usr/local/bin/helm
tiller installed into /usr/local/bin/tiller
Run 'helm init' to configure helm.
```

And for `get-helm-3`:

```
~ ><> docker run -it ubuntu
root@1ec64581ce19:/# apt update && apt install curl
...
Running hooks in /etc/ca-certificates/update.d...
done.
root@1ec64581ce19:/# curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11213  100 11213    0     0  95837      0 --:--:-- --:--:-- --:--:-- 95837
Downloading https://get.helm.sh/helm-v3.3.4-linux-amd64.tar.gz
Verifying checksum... Done.
Preparing to install helm into /usr/local/bin
helm installed into /usr/local/bin/helm
```

**Comment by bacongobbler** [comment]
As for whether `$TAG` vs `v$TAG`... The tag is `v3.3.4` or `v2.16.12`. The `v` is part of the tag.

I think you may be providing the wrong input if that's the case. But again, I cannot help you without some demonstration of the issue you are describing.

**Comment by bobrot** [comment]
Yup, I missed the fact that I'd need to run ./get_helm.sh -v **v**2.16.12. The 2 **v**s seem a little redundant, but I know for next time.

**Comment by alejandro-delgado-garcia** [comment]
Hi, we started to get this issue today around 5pm EST. The script was working fine until today.
```bash
#!/bin/bash -eo pipefail
cd ~ && curl https://raw.githubusercontent.com/helm/helm/master/scripts/get > get_helm.sh && chmod 700 get_helm.sh && ./get_helm.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7163  100  7163    0     0   438k      0 --:--:-- --:--:-- --:--:--  466k
Downloading https://get.helm.sh/helm--linux-amd64.tar.gz
SHA sum of /tmp/helm-installer-QQqNfm/helm--linux-amd64.tar.gz does not match. Aborting.
Failed to install helm
	For support, go to https://github.com/helm/helm.

Exited with code exit status 1
```
As you can see the script can't get the proper version `helm--linux-amd64.tar.gz`

**Comment by andylwelch** [comment]
I too have encountered this SHA issue today

**Comment by andylwelch** [comment]
It appears the version number is not detected again  I fixed by manually setting the version to install:
`./get_helm.sh -v v2.17.0`

**Comment by Jeroen-Beljaars** [comment]
Started receiving this issue as well around the same time. Used to work fine, but suddenly it doesn't anymore.

**Comment by generatz** [comment]
Yeah, just got this:
```
08:23:47 [0mDownloading https://get.helm.sh/helm--linux-amd64.tar.gz
08:23:47 SHA sum of /tmp/helm-installer-qssKqS/helm--linux-amd64.tar.gz does not match. Aborting.
```

**Comment by erwan-b** [comment]
I got the same error,

Just set 
`export DESIRED_VERSION=v2.13.0`  before and you will be all good

**Comment by rajatagarwal** [comment]
> I got the same error,
> 
> Just set
> `export DESIRED_VERSION=v2.13.0` before and you will be all good

Also works for newer version:
`export DESIRED_VERSION=v3.6.0`
