### ISSUE TITLE
ref(scripts/get): follow redirects to fetch the latest version

### ISSUE THREAD

**Issue by bacongobbler** [helm/helm#5480]
Based on a suggestion made by @danyim in https://github.com/helm/helm/issues/5476#issuecomment-474663546:

> Instead of trying to select an HTML value by piping commands together, a better workaround would be to get `curl` or `wget` to follow the redirected URL.
> 
> For instance, Github redirects https://github.com/helm/helm/releases/latest to the latest tagged version: https://github.com/helm/helm/releases/tag/v2.13.0
> 
> I think something like this would work better to grab the latest tag ([source](https://stackoverflow.com/a/3077316/350951)):
> 
> ```
> $ curl -Ls -o /dev/null -w %{url_effective} https://github.com/helm/helm/releases/latest
> https://github.com/helm/helm/releases/tag/v2.13.0% 
> ```
> 
> Doing the above will make the script depend on Github's URL redirection scheme instead of the underlying HTML, which is arguably less likely to change.

**Comment by arief-hidayat** [comment]
Can I work on this issue?
Thanks

**Comment by bacongobbler** [comment]
Sure!

**Comment by arief-hidayat** [comment]
Instead of just fixing the redirect, where there's doubt on wget
https://github.com/helm/helm/issues/5477#issuecomment-474666318

I have slightly different proposal, to call the github API endpoint.

```
  local release_url
  if [ "x$DESIRED_VERSION" == "x" ]; then
    release_url="https://api.github.com/repos/helm/helm/releases/latest"
  else
    release_url="https://api.github.com/repos/helm/helm/releases/tags/$DESIRED_VERSION"
  fi
  
  if type "curl" > /dev/null; then
    TAG=$(curl -SsL $release_url | grep "tag_name" | head -n 1 | cut -d '"' -f 4)
  elif type "wget" > /dev/null; then
    TAG=$(wget -q -O - $release_url  | grep "tag_name" | head -n 1 | cut -d '"' -f 4)
  fi
```
what do you think?

**Comment by bacongobbler** [comment]
Someone already proposed that and I said it wasn't a good idea. Have a look at https://github.com/helm/helm/pull/5479 for more background info.

**Comment by arief-hidayat** [comment]
I see. Thanks
