### ISSUE TITLE
`helm template` only works with local charts

### ISSUE THREAD

**Issue by Morishiri** [helm/helm#5490]
`helm template` command seems to work only with local charts, I've tried to display computed resources of remotely located chart and it fails with message that file doesn't exist.

Examples:
- normal way:
```
$ helm template -f ./my/values.yaml my-repo/my-chart
Error: stat my-repo/my-chart: no such file or directory
```
- with `--repo` command line argument:
```

$ helm template -f ./my/values.yaml --repo my-repo my-chart
Error: unknown flag: --repo
```
I bet this should work the same way as `install` command when it first look if repository with given name exist and search for chart there, then continues to search locally (as described in https://github.com/helm/helm/issues/1158#issuecomment-247135086)

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
but seems irrelevant here

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
`AKS-Engine`, but seems irrelevant here

**Comment by Morishiri** [comment]
Update: Just noticed that another options are also not available (ex. `--version` to specify chart version). I know this command is ported from the plugin, so maybe this task would be good starting point to align this to other helm commands.

**Comment by jlegrone** [comment]
This seems like a duplicate of https://github.com/helm/helm/issues/4401.

What works for me is

```cli
helm fetch my-repo/my-chart --version x.x.x --untar && \
helm template -f ./my/values.yaml my-chart
```

**Comment by Morishiri** [comment]
You're right! Let me close this one as duplicate then. Thanks also for the workaround :)
