### ISSUE TITLE
Helm tests to run at scale with 2k charts?

### ISSUE THREAD

**Issue by krish7919** [helm/helm#5493]
Hi,
Is there any documentation about the scaling scenarios of helm?

I am fed up with `helm` returning `[storage/driver] 2019/03/21 12:22:56 list: failed to list: the server was unable to return a response in the time allotted, but may still be processing the request (get configmaps)`, and we have doubled the number of masters in the cluster to ignore `apiserver` bottlenecks.

How does `helm` behave at scale with 2k-3k charts deployed to the cluster?

Output of `helm version`:
`v2.8.2`
If it helps, we are using an external 3 node `etcd` cluster which has shown a lot of disk reads and writes, but nothing much as an issue there.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
