### ISSUE TITLE
Error: forwarding ports: error upgrading connection: unable to upgrade connection: Forbidden (user=system:anonymous, verb=create, resource=nodes, subresource=proxy)

### ISSUE THREAD

**Issue by mymbrooks** [helm/helm#5494]
Output of `helm version`:
Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
Error: forwarding ports: error upgrading connection: unable to upgrade connection: Forbidden (user=system:anonymous, verb=create, resource=nodes, subresource=proxy)

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Custom binary install, 1 master + 2 node

Steps
1、
kubectl create serviceaccount --namespace kube-system tiller

kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller

kubectl patch deploy --namespace kube-system tiller-deploy -p '{"spec":{"template":{"spec":{"serviceAccount":"tiller"} }} }'

2、
helm init --upgrade --stable-repo-url https://kubernetes.oss-cn-hangzhou.aliyuncs.com/charts --service-account tiller --tiller-image registry.cn-hangzhou.aliyuncs.com/google_containers/tiller:v2.13.0

tiller-deploy is ready but helm version for server is always error
kubectl get pods --namespace kube-system
NAME                             READY   STATUS    RESTARTS   AGE
tiller-deploy-859d476dbb-s6hbk   1/1     Running   0          16s

Error: forwarding ports: error upgrading connection: unable to upgrade connection: Forbidden (user=system:anonymous, verb=create, resource=nodes, subresource=proxy)

Update 2019-03-22:
I tried solution from here
https://github.com/helm/helm/issues/3104
kubectl apply -f ./fix.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: anonymous-logs-role
rules:
- apiGroups: [""]
  resources: ["nodes/proxy"]
  verbs: ["create", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: anonymous-logs-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: anonymous-logs-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:anonymous

now error is helm version:
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
E0322 22:03:45.903164    8796 portforward.go:391] an error occurred forwarding 35261 -> 44134: error forwarding port 44134 to pod bf128e8fdba3fda33b4b840c15a20de44b7a78be69d74096bfbd854887709582, uid : unable to do port forwarding: socat not found.
E0322 22:03:46.910460    8796 portforward.go:391] an error occurred forwarding 35261 -> 44134: error forwarding port 44134 to pod bf128e8fdba3fda33b4b840c15a20de44b7a78be69d74096bfbd854887709582, uid : unable to do port forwarding: socat not found.
E0322 22:03:48.701163    8796 portforward.go:391] an error occurred forwarding 35261 -> 44134: error forwarding port 44134 to pod bf128e8fdba3fda33b4b840c15a20de44b7a78be69d74096bfbd854887709582, uid : unable to do port forwarding: socat not found.
E0322 22:04:21.110457    8796 portforward.go:331] error creating error stream for port 35261 -> 44134: Timeout occured
E0322 22:04:44.846465    8796 portforward.go:353] error creating forwarding stream for port 35261 -> 44134: Timeout occured
E0322 22:05:11.714236    8796 portforward.go:353] error creating forwarding stream for port 35261 -> 44134: Timeout occured
E0322 22:05:43.178922    8796 portforward.go:331] error creating error stream for port 35261 -> 44134: Timeout occured

**Comment by bacongobbler** [comment]
What happens if you run the following?

```
kubectl -n kube-system port-forward svc/tiller-deploy 44134:44134
```

And in another terminal:

```
export HELM_HOST=:44134
helm list
```

Under the covers, Helm initializes a port-forwarded tunnel to tiller through the Kubernetes API. It's possible that `kubectl` (or rather, the Kubernetes API server) is unable to upgrade the connection from an HTTP to a TCP stream. If the `kubectl port-forward` fails, then it's likely something wrongly configured in your cluster that won't upgrade `port-forward` requests.

**Comment by mymbrooks** [comment]
output:
Forwarding from 127.0.0.1:44134 -> 44134
Forwarding from [::1]:44134 -> 44134
Handling connection for 44134
E0323 07:38:15.092161    2797 portforward.go:391] an error occurred forwarding 44134 -> 44134: error forwarding port 44134 to pod ceca3d9a3628c600f3e30ae466ea0f7e367a3c8c82c2938832b9f015fafcb667, uid : unable to do port forwarding: socat not found.
Handling connection for 44134
E0323 07:38:16.165410    2797 portforward.go:391] an error occurred forwarding 44134 -> 44134: error forwarding port 44134 to pod ceca3d9a3628c600f3e30ae466ea0f7e367a3c8c82c2938832b9f015fafcb667, uid : unable to do port forwarding: socat not found.
Handling connection for 44134
E0323 07:38:17.526974    2797 portforward.go:391] an error occurred forwarding 44134 -> 44134: error forwarding port 44134 to pod ceca3d9a3628c600f3e30ae466ea0f7e367a3c8c82c2938832b9f015fafcb667, uid : unable to do port forwarding: socat not found.
Handling connection for 44134
Handling connection for 44134
E0323 07:38:50.265455    2797 portforward.go:331] error creating error stream for port 44134 -> 44134: Timeout occured

I will search for port forward config for cluster, then try again

**Comment by mymbrooks** [comment]
I install socat on 2 node: sudo apt installl socat
now helm version works:
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

thanks, please close.
