### ISSUE TITLE
Unable to delete parent values when specifying multiple values files

### ISSUE THREAD

**Issue by rosskusler** [helm/helm#5495]
We have a chart with a default set of values (in values.yaml) and we supply an override.yaml containing environment specific changes.  I am having trouble deleting values specified in values.yaml though.  In actuality I'm trying to override (delete) the grpc settings that are defined in the stable/dex chart.  However I have put together a toy example that, I think, demonstrates the problem.

$ cat templates/example.yaml
```
{{ toYaml .Values.things }}
```

$ cat values.yaml
```
things:
  colors:
  - green
  - blue

  numbers:
  - one
  - two
```

$ cat overrides.yaml
```
things:
  numbers: null
```

$ helm template -f values.yaml -f overrides.yaml .
```
---
# Source: toychart/templates/example.yaml
colors:
- green
- blue
numbers: null
```

I would expect "numbers" to not show up at all.  I've also tried setting it to "",  [], and including the line "numbers: " by itself.  In each case the "numbers" still shows up in the output.

I've also tried this:
```
$ helm template -f values.yaml --set things.numbers=null .
```
but still get
```
---
# Source: toychart/templates/example.yaml
colors:
- green
- blue
numbers: null
```

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
self-hosted
```

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
