### ISSUE TITLE
Un-quoted "on" and "off" strings evaluated as true/false in values.yaml

### ISSUE THREAD

**Issue by gree-gorey** [helm/helm#5497]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
```

When having keys and/or values like `on` and `off` within `values.yaml` file they are evaluated as `true` and `false`. There is no mention of this behavior in Helm docs. Took me a while to get to the bottom of the issue. When you quote them then everything is ok.

Here is the minimal example to reproduce:
```console
$ cat values.yaml 
key:
  "on": bar
  on: foo
  off: egg
$ helm template . --debug
...
COMPUTED VALUES:
key:
  "false": egg
  "on": bar
  "true": foo
...
```

This should be smth Helm-related because when I am using pure `gomplate` it's rendered as expected:
```console
$ gomplate -d values.yaml -i '{{ (datasource "values").key.off }}'
egg
```

This should be at least in docs. Or if it is, please direct me to it. Thanks

**Comment by bacongobbler** [comment]
As part of the YAML 1.1 specification, `ON | on | OFF | off` are considered valid boolean values. These values were dropped as part of the YAML 1.2 specfication, however go-yaml still supports those keys as part of its YAML 1.1 and 1.2 compatibility matrix.

See https://github.com/go-yaml/yaml/issues/214 for more information.

**Comment by gree-gorey** [comment]
@bacongobbler I see. Thank you for prompt reply and clarifying this!
