### ISSUE TITLE
test before install/upgrade?

### ISSUE THREAD

**Issue by marshallford** [helm/helm#5508]
I'm curious if there is a pattern similar to `helm test` that allows you to run a short lived pod before commiting to a `helm install`. Perhaps use a temporary namespace with the deployment resources swapped out for short lived pod resources? One hacky way to accomplish this might be to have two charts, a "real chart" and a chart that would be deleted after it returned an exit code.

Let me know if what I am asking even makes sense. Thanks.

## Example CICD pipeline with `pretest`

**Test**
* `helm lint`
* `make test`

**Build**
* `docker build ... && docker push ...`

**Integration Test**
* `docker run image echo "test"`
* `helm pretest`

**Deploy**
* `helm upgrade --install ...`

**Comment by bacongobbler** [comment]
Hey @marshallford, what's the use case for running a pod prior to installing a chart? I'm having a tough time determining why would a chart want to "test the waters" before being deployed.

For context, `helm test` was originally designed around the idea of running an acceptance test suite after an installation to ensure it's "all systems nominal".

If you could expand upon your use case, that would be helpful to understand what you're trying to achieve and see if there are alternative approaches first before deciding whether a pre-test hook makes sense. Thanks!

**Comment by marshallford** [comment]
> For context, helm test was originally designed around the idea of running an acceptance test suite after an installation to ensure it's "all systems nominal".

Understood.

The use case that I had in the back of my head when writing up the OP is around applications that by default start a http service but also have a `--test` flag that runs a short test of the environment, configuration, etc and then returns an exit code. The service can be monitored with the standard `livenessProbe` and `readinessProbe` container options but integration tests might be run with an argument or different binary all together. 

One concrete example of what I am getting at is the official ES Logstash image. By default the container starts logstash but if you override the entrypoint/command to run the logstash binary with the `--config.test_and_exit` flag you are able to "Check configuration for valid syntax and then exit."

**Comment by mikebou** [comment]
If the acceptance test is "after" the upgrade, shouldn't the deployment fail? The failure should not complete the deployment which terminates the successfully running container. The result of deploying a container that failed its chart tests in favor of a successfully running container does not seem ideal. 

Alternately, a test failure during an upgrade could allow for a fallback to the container version that was last successfully deployed.

Conversely, being able complete the acceptance testing prior to upgrading would seem a more desirable option. Validating the chart tests pass the defined test prior to upgrading to a container would eliminate the necessity of any fallback options based on test failures.

**Comment by technosophos** [comment]
Closing as `wont fix`, as this has seen a year of inactivity and nobody has put together a complete proposal.
