### ISSUE TITLE
Randomness(less) of randAlphaNum ?

### ISSUE THREAD

**Issue by przemolb** [helm/helm#5510]
Output of `helm version`: v2.13.1

Output of `kubectl version`: v1.13.4 (client), v1.12.6 (server)

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

I have a chart for our internal testing where one of the first step is to create database user account. Because this chart can be run in bulk (many tests at once) the obvious way to create a username and password is to use `randAlphaNum`:
```
{{- $DBUSERNAME     := ( randAlphaNum 10 | toString ) -}}
{{- $DBUSERNAMEPASS := ( randAlphaNum 4  | toString ) -}}
```
The script which creates DB user is triggered in `initContainer` so if it fails (for whatever reason) no other `initContainer` has been created and the whole `Deployment` hangs in `Init:Error` state (which, in this case, is what we need - our app cannot work without existing DB user). I have triggered many deployments at once (in a bash loop) and it turned out many of them are indeed hanging at `initContainers`. The only reason is that our init script reports that it cannot create a user because:
```
user name 'PQBVGTL5IQ' conflicts with another user or role name
```
It happens very, very often - I mean I increased randAlphaNum to 20, triggered in a script around 80 `helm install ...` comands and it didn't help - the DB is reporting that the user has been already created.
Can anyone help me with understanding of randomness (or randomless) of randAlphaNum ?

**Comment by bacongobbler** [comment]
https://github.com/Masterminds/sprig/blob/9f8fceff796fb9f4e992cd2bece016be0121ab74/strings.go#L58-L62

**Comment by przemolb** [comment]
@bacongobbler thanks for the link but ... that doesn't really explain why duplicate values come up so often in my testing.

**Comment by przemolb** [comment]
@bacongobbler this `randAlphaNumeric` is unexported, right ?
