### ISSUE TITLE
"err: context deadline exceeded exit status 1" when using helm golang pkg client

### ISSUE THREAD

**Issue by yunzshi** [helm/helm#5515]
Hi There,

when I tried golang helm pkg, met below error:
2019/03/27 06:21:13 err: context deadline exceeded
exit status 1

package main

import (
	"log"
	"k8s.io/helm/pkg/helm"
)

const (
	tillerHost = "127.0.0.1:44134"
)

func main() {
    helm.ConnectTimeout(60)
	helmClient := helm.NewClient(helm.Host(tillerHost))
	_, err := helmClient.ListReleases()
	if err != nil {
		log.Fatalf("err: %v", err)
	}
}

Output of `helm version`:
Client: &version.Version{SemVer:"v2.13.0-rc.2", GitCommit:"b0d4c9eb82e036c52d130fcb031e788dffe5a5dd", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.0-rc.2", GitCommit:"b0d4c9eb82e036c52d130fcb031e788dffe5a5dd", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Centos 7

**Comment by yunzshi** [comment]
anyone can help?

**Comment by markmssd** [comment]
@yunzshi did you end up finding a solution?

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
