### ISSUE TITLE
HELM_HOME not honoured on helm repo update

### ISSUE THREAD

**Issue by trilitheus** [helm/helm#5517]
Output of `helm version`:

    Client: &version.Version{SemVer:"v2.13.1", 
    GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

    Server: &version.Version{SemVer:"v2.13.1", 
    GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

Output of `kubectl version`:

    Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", 
    GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", 
    BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", 
    Platform:"linux/amd64"}

    Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.7", 
    GitCommit:"65ecaf0671341311ce6aea0edab46ee69f65d59e", GitTreeState:"clean", 
    BuildDate:"2019-01-24T19:22:45Z", GoVersion:"go1.10.7", Compiler:"gc", 
    Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
KOPS on AWS

We manage a test cluster and a production cluster with helm.
To aid this, we have two aliases:

    $ type helmtest
    helmtest is aliased to `helm --home=${HOME}/.helm_test'
    
    $ type helmprod
    helmprod is aliased to `helm --home=${HOME}/.helm_prod'

When performing a helm update repo, the `--home` flag is not honoured:

    $ helmtest repo update
    Hang tight while we grab the latest from your chart repositories...
    ...Skip local chart repository
    ...Unable to get an update from the "coreos" chart repository (https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/):
	    open /home/user/.helm/repository/cache/coreos-index.yaml: no such file or directory
    ...Unable to get an update from the "stable" chart repository (https://kubernetes-charts.storage.googleapis.com):
	    open /home/user/.helm/repository/cache/stable-index.yaml: no such file or directory
    Update Complete. ⎈ Happy Helming!⎈

Happens via the alias or without:

    $ helm --home=${HOME}/.helm_test repo update
    Hang tight while we grab the latest from your chart repositories...
    ...Skip local chart repository
    ...Unable to get an update from the "coreos" chart repository (https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/):
	    open /home/user/.helm/repository/cache/coreos-index.yaml: no such file or directory
    ...Unable to get an update from the "stable" chart repository (https://kubernetes-charts.storage.googleapis.com):
	    open /home/user/.helm/repository/cache/stable-index.yaml: no such file or directory
    Update Complete. ⎈ Happy Helming!⎈
    
We can work around this by updating the updating and copying over but the expectation is that HELM_HOME is honoured and the respective repositories are updated as expected.

**Comment by Hiruma31** [comment]
I have a similar issue trying to setup a common helm config for multiple users
`Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}`

From the same terminal, in sequence:
```
$ echo $HELM_HOME
/etc/helm/conf

$ helm repo update
Error: Couldn't load repositories file (/home/user/.helm/repository/repositories.yaml).

$ helm repo update --home $HELM_HOME
Error: Couldn't load repositories file (/etc/helm/conf/repository/repositories.yaml).

$ HELM_HOME=/etc/helm/conf helm repo update
Error: Couldn't load repositories file (/etc/helm/conf/repository/repositories.yaml).

$ ls /etc/helm/conf/repository/
repositories.yaml
```

For me the --home flag works properly, but despite HELM_HOME variable being set, it is ignored.

**Comment by kav** [comment]
I'm seeing a related issue; when I specify `helm repo update --home ./` I get 
helm reports it can't find
`.helm/repository/cache/.helm/repository/cache/stable-index.yaml`
This repos on v2.14.0 and v3.0.0-alpha.2

My guess is someone tried to fix the pathing issue but missed a double set of the `.helm/repository/cache/.` directory. Happy to investigate and fix if someone else is seeing similar and can confirm my state isn't screwy

**Comment by bacongobbler** [comment]
This should be fixed in beta 2.
