### ISSUE TITLE
helm init --upgrade does nothing

### ISSUE THREAD

**Issue by scphantm** [helm/helm#5521]
Output of `helm version`:
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.0", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}

Output of `kubectl version`:

oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth

Server https://okdmastertest.labtest.panasas.com:8443
openshift v3.11.0+45a695c-151
kubernetes v1.11.0+d4cacc0

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

internal

I installed tiller with this command

`oc process -f https://github.com/openshift/origin/raw/master/examples/helm/tiller-template.yaml -p TILLER_NAMESPACE="${TILLER_NAMESPACE}" -p HELM_VERSION=v2.9.0 | oc create -f -`

from a remote workstation logged in as `cluster-admin`.  Now when i try 

`helm init --upgrade`

i get 

```
$HELM_HOME has been configured at /Users/wslepecki/.helm.

Tiller (the Helm server-side component) has been upgraded to the current version.
Happy Helming!
```
but 

```
helm version
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.0", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}
```

nothing actually happens.  i tried the force-upgrade as well, again, nothing happened.

**Comment by bacongobbler** [comment]
This seems relevant:

> oc process -f https://github.com/openshift/origin/raw/master/examples/helm/tiller-template.yaml -p TILLER_NAMESPACE="${TILLER_NAMESPACE}" -p HELM_VERSION=v2.9.0 | oc create -f -

I wonder if openshift is pinning the deployment to that particular version, so even if `helm init --upgrade` changes the deployment object, openshift will eventually change it back to v2.9.0. We used to have the same issue with clusters installed with the Kubernetes [Addon Manager](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/addon-manager).

Try installing tiller using `helm init` and not `oc`. Does the behaviour change?

**Comment by bacongobbler** [comment]
As a further note, I'd probably ask the Openshift folks directly instead. It looks like the process is totally out of band with a different setup, so perhaps they would be better equipped to inform you how the `oc` tool is intended to be used with Helm.

**Comment by scphantm** [comment]
i deleted everything and was able to get `helm init` to work.  But i can't install anything.  when i try

`helm install stable/nfs-client-provisioner --set nfs.server=mynfs --set nfs.path=/kubernetes`

i get 

`Error: no available release name found`

i found another site that suggested this

```
$ oc create serviceaccount --namespace kube-system tiller
$ oc create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
$ helm init --service-account tiller

```
but that didn't work either

**Comment by bacongobbler** [comment]
Try using a role and role binding that better suits tiller's needs, like the [tiller template openshift creates](https://github.com/openshift/origin/blob/e048ffb193ce10ecdb02c7127245cbf1d515ee02/examples/helm/tiller-template.yaml#L1-L40). A clusterrolebinding may not be the right choice here.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
