### ISSUE TITLE
Assign random value to variable at the init of helm package

### ISSUE THREAD

**Issue by przemolb** [helm/helm#5522]
Hello,
I need to initialize some random value with `randAlphaNum X` which, the same, will be used across all yaml files defined in helm package.
I cannot do that at the top of each yaml with:
```
{{- $myPassword := ( randAlphaNum 10 | toString ) -}}
```
because it has to have the same value for each yaml file (reference).
How do I do that ?

**Comment by przemolb** [comment]
Any help or hint how to achieve this ?

**Comment by przemolb** [comment]
Any help how to solve that ?

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

**Comment by bacongobbler** [comment]
Most users generate a value at runtime and pass that to the templates/values using `--set`.

Hope this helps.

**Comment by przemolb** [comment]
Generating a value at runtime is additional step. It looks simple but ... when you have to deploy more then a few helm charts it becomes tedious to run additional steps before the actual `helm install ...`.

**Comment by studiofrancium** [comment]
As a workaround you could trim the seconds off from timestamp and use it as a basis for your variable.  There is a good chance 1 minute is enough for the whole helm chart to be populated with the generated value.

`{{- define "pvname" -}}
{{- $name := date "20060102150405" .Release.Time | toString | lower | trunc 12 -}}
{{- printf "%s-%s" "pv-claim" $name -}}
{{- end -}}`

**Comment by DhayOfRedox** [comment]
As there is no longer `.Release.Time` in Helm 3, a similar solution will suffice -  getting the current UNIX time and truncating that.

`{{- now | unixEpoch | trunc 8 -}}`
