### ISSUE TITLE
Helm access User Info

### ISSUE THREAD

**Issue by brunohms** [helm/helm#5525]
Is it possible to get any kind of user info when installing/updating a chart?
People in my company are interested in getting to know when/who/what was deployed/installed.

I was thinking of making a hook at the stages of post-install/post-update/post-delete
to make a request in an API to store this data.

Would it be possible/viable to do?

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.7-gke.12", GitCommit:"06f08e60069231bd21bdf673cf0595aac80b99f6", GitTreeState:"clean", BuildDate:"2019-02-25T20:37:10Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

**Comment by bacongobbler** [comment]
https://kubernetes.io/docs/tasks/debug-application-cluster/audit/
