### ISSUE TITLE
Helm version selection rules

### ISSUE THREAD

**Issue by Zero-2** [helm/helm#5526]
Output of `helm version`:
```bash
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

Output of `kubectl version`:
```bash
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-26T12:49:28Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AKS

We have a lot of charts deployed into dev helm repository using CI/CD gitlab pipeline.
The naming convention used for the develop env is X.Y.Z-SHORT_SHA_COMMIT .
When i try to install the chart using the command 
```bash
helm install --devel --name chartname repo-develop/chartname
```
the version installed is, for example, 2.1.0-fa68129e that is not the latest ( date 2019-02-28T10:03:17.075Z )
The real latest chart is 2.1.0-c0821a70 ( date 2019-03-28T11:01:23.177Z) .
But the latest chart version is lexicographically lower than the previous one.

How i can solve this issue without specifiy the version in the install command?

Regards

**Comment by maorfr** [comment]
You should probably change the versioning... as you say, commits are not lexicographicly sorted.
Two alternatives i can think of are the timestamp (choose your format), or gitlab's CI_PIPELINE_ID (which is more traceable).

Hope this helps!!

**Comment by bacongobbler** [comment]
Closing as answered, but please feel free to re-open if @maorfr's answer did not answer your question. Thanks.
