### ISSUE TITLE
Helm plugin install tgz with directory

### ISSUE THREAD

**Issue by steven-sheehy** [helm/helm#5540]
Output of `helm version`: 
```
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:39:52Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
bare metal

As a plugin writer, I want my users to be able to install my plugin in a cross platform way without resorting to hack-ish install scripts that are platform specific. If I package my plugin binaries in a tgz file for various operating systems and architectures, users should be able to install it directly. It should work for http and local plugin installation methods. For example:

```
helm plugin install https://github.com/databus23/helm-diff/releases/download/v2.11.0%2B3/helm-diff-macos.tgz
helm plugin install file:///Users/me/helm-diff-macos.tgz
```

Expected Results:
Plugin installed

Actual Results:
`Error: plugin metadata (plugin.yaml) missing`

**Comment by bacongobbler** [comment]
How do you propose we could rewrite the current architecture to make this work?

For reference, I've been taking a good hard look at the plugin subsystem for Helm 3, in particular the plugin install/upgrade/hook system. PR #5514 is purely exploratory work, but it removes `helm plugin install` from Helm entirely, relying on loading plugins from $PATH, git style.

The assumption there is that Helm plugin maintainers would distribute their content using traditional OS package managers (homebrew, apt, chocolatey etc) to accomplish the same goals as `helm plugin install`. It also removes the concept of a plugin.yaml from the plugin (see the docs in that PR for more info).

Thoughts?

**Comment by steven-sheehy** [comment]
@bacongobbler For Helm 2, I don't think you need to rewrite the architecture. I was going to look into submitting a PR for this.

Concerning Helm 3, I think being able to support arbitrary commands in the PATH without a plugin.yaml is a good idea. Something like `helm plugin register chart-version "cat Chart.yaml | grep '^version: ' | cut -d' ' -f2"`. But per your PR, it only supports files starting with `helm-` so that doesn't seem possible. I do like being able to override existing helm commands though.

I don't think `helm plugin install` should be removed. Have you ever tried to packaging an application for a Linux distribution? It's horrible and there's so many of them. Each distro has a different packaging mechanism and a rigorous approval process that's impossible to get anything through. You'd be asking plugin developers to package their app for many operating systems instead of just for Helm and you'd be asking plugin users to figure out how to install it for their platform.

**Comment by steven-sheehy** [comment]
So it looks like helm plugin install does support tgz for http URIs, as mentioned in the plugins doc. But what's not mentioned is that it only supports tarbombs, not tgz's with a folder inside. Removing the directory from the tgz made it install successfully.

Also, tgz is not supported for local plugin (or for VCS, but not sure it makes sense for VCS).

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

**Comment by jkroepke** [comment]
Hi @bacongobbler ,

Today I test this helm v3, but it still wont work.

```
helm plugin install https://github.com/jkroepke/helm-secrets/archive/v3.1.0.tar.gz
Error: plugin metadata (plugin.yaml) missing
```
Also local archives are affected:

```
jkr@joe-nb helm-secrets % tar tvf helm-secrets.tar.gz | grep plugin.yaml
-rw-r--r--  0 root   root      436 Sep  9 12:07 plugin.yaml
jkr@joe-nb helm-secrets % helm plugin install helm-secrets.tar.gz       
Error: plugin metadata (plugin.yaml) missing
```

Helm version:
```
helm version
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"dirty", GoVersion:"go1.15"}
```

Should I create a new issue?

**Comment by glenjamin** [comment]
Having helm3 support tarballs containing a single top-level directory would be helpful, as that would allow installing the tarballs github generates without needing to install git.

**Comment by jkroepke** [comment]
cool, but still an issue.

**Comment by sanzenwin** [comment]
Two thousand years later, we still facing this issue.

**Comment by sanzenwin** [comment]
Just do this:
```shell
helm version
# version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}

wget https://github.com/databus23/helm-diff/releases/download/v3.1.3/helm-diff-linux.tgz
mkdir -p  /root/.local/share/helm/plugins/helm-diff
tar -zxvf helm-diff-linux.tgz -C /root/.local/share/helm/plugins/helm-diff  --strip-components=1

helm diff --help
```

**Comment by mblaschke** [comment]
Also affected:

```
$ tar tvf release-assets/helm-plugin.tar|grep plugin.yaml
-rw-r--r--  0 mblaschke staff       693 Aug 25 15:32 plugin.yaml

$ helm --debug plugin install release-assets/helm-plugin.tar
Error: plugin metadata (plugin.yaml) missing
helm.go:84: [debug] plugin metadata (plugin.yaml) missing
helm.sh/helm/v3/pkg/plugin/installer.init
	helm.sh/helm/v3/pkg/plugin/installer/installer.go:32
runtime.doInit
	runtime/proc.go:6222
runtime.doInit
	runtime/proc.go:6199
runtime.main
	runtime/proc.go:233
runtime.goexit
	runtime/asm_arm64.s:1263
```

**Comment by ruanbekker** [comment]
I got it to work the manual way:

```bash
wget https://github.com/codacy/helm-ssm/releases/download/3.1.9/helm-ssm-macos.tgz
tar -xvf helm-ssm-macos.tgz
mkdir -p ~/Library/helm/plugins/helm-ssm/
mv helm-ssm ~/Library/helm/plugins/helm-ssm/helm-ssm
mv plugin.yaml ~/Library/helm/plugins/helm-ssm/plugin.yaml 
```

List plugins:

```bash
helm plugin ls
NAME            VERSION DESCRIPTION                                                                         
ssm             3.1.9   Inject AWS SSM parameters into Helm values files     
```

Test:

```bash
helm ssm --help

Usage:
  ssm [flags]

Flags:
  -d, --dry-run                 doesn't replace the file content
  -h, --help                    help for ssm
  -p, --profile string          aws profile to fetch the ssm parameters
  -o, --target-dir string       dir to output content
  -f, --values valueFilesList   specify values in a YAML file (can specify multiple) (default [])
  -v, --verbose                 show the computed YAML values file/s
```

**Comment by jkroepke** [comment]
Thanks @ruanbekker but we all are interested in an automatic solution.
