### ISSUE TITLE
Helm cannot find service during upgrade.

### ISSUE THREAD

**Issue by dick-twocows** [helm/helm#5541]
If I install a chart (with subs) and subsequently upgrade the chart helm reports;

UPGRADE FAILED
ROLLING BACK
Error: no Service with the name "edge-objectstore" found
Error: UPGRADE FAILED: no Service with the name "edge-objectstore" found

Yet if I query the cluster it is clearly there!

kubectl -n edge get service edge-objectstore
NAME               TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
edge-objectstore   ClusterIP   10.96.181.14   <none>        80/TCP    11m

Having been created by the install.

For whatever reason helm or whatever it is calling is unable to determine that the service exists even though it is unmodified since the install.

Is helm losing state because some of the pods are failing to start? That is the issue isn't with the service but somewhere else and helm is reporting incorrectly?

Output of `helm version`:

Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-3+602d21b1679fa5", GitCommit:"602d21b1679fa5f8de2f9a04bbf485f1fa09a973", GitTreeState:"clean", BuildDate:"2019-02-27T16:46:58Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Oracle Cloud

 dick  …  k8s  helm  cell  kubectl -n edge get all
NAME                                                 READY   STATUS              RESTARTS   AGE
pod/edge-compute-56b7f7cb99-lmq9q                    1/1     Running             0          115s
pod/edge-mongodb-arbiter-0                           1/1     Running             0          114s
pod/edge-mongodb-primary-0                           2/2     Running             0          114s
pod/edge-mongodb-secondary-0                         2/2     Running             0          114s
pod/edge-objectstore-192-168-48-4-8465d6944d-dx9h7   1/2     CrashLoopBackOff    3          115s
pod/edge-objectstore-192-168-52-4-794dcb6469-6dhnh   1/2     CrashLoopBackOff    3          115s
pod/edge-objectstore-192-168-56-4-55f588f85-bgh8v    1/2     CrashLoopBackOff    3          115s
pod/edge-user-79455459bf-vmhgt                       1/1     Running             0          114s
pod/edge-zookeeper-0                                 1/1     Running             0          114s
pod/edge-zookeeper-1                                 1/1     Running             0          59s
pod/edge-zookeeper-2                                 0/1     ContainerCreating   0          16s

NAME                                    TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
service/edge-compute                    ClusterIP   10.96.159.165   <none>        80/TCP                       116s
service/edge-mongodb                    ClusterIP   10.96.16.222    <none>        27017/TCP                    115s
service/edge-mongodb-headless           ClusterIP   None            <none>        27017/TCP,9216/TCP           115s
service/edge-objectstore                ClusterIP   10.96.181.14    <none>        80/TCP                       115s
service/edge-objectstore-192-168-48-4   NodePort    10.96.217.48    <none>        443:30216/TCP                115s
service/edge-objectstore-192-168-52-4   NodePort    10.96.82.117    <none>        443:31231/TCP                115s
service/edge-objectstore-192-168-56-4   NodePort    10.96.64.10     <none>        443:30492/TCP                115s
service/edge-user                       ClusterIP   10.96.106.140   <none>        80/TCP                       115s
service/edge-zookeeper                  ClusterIP   10.96.112.162   <none>        2181/TCP                     115s
service/edge-zookeeper-headless         ClusterIP   None            <none>        2181/TCP,3888/TCP,2888/TCP   115s

NAME                                            DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/edge-compute                    1         1         1            1           115s
deployment.apps/edge-objectstore-192-168-48-4   1         1         1            0           115s
deployment.apps/edge-objectstore-192-168-52-4   1         1         1            0           115s
deployment.apps/edge-objectstore-192-168-56-4   1         1         1            0           115s
deployment.apps/edge-user                       1         1         1            1           114s

NAME                                                       DESIRED   CURRENT   READY   AGE
replicaset.apps/edge-compute-56b7f7cb99                    1         1         1       115s
replicaset.apps/edge-objectstore-192-168-48-4-8465d6944d   1         1         0       115s
replicaset.apps/edge-objectstore-192-168-52-4-794dcb6469   1         1         0       115s
replicaset.apps/edge-objectstore-192-168-56-4-55f588f85    1         1         0       115s
replicaset.apps/edge-user-79455459bf                       1         1         1       114s

NAME                                      DESIRED   CURRENT   AGE
statefulset.apps/edge-mongodb-arbiter     1         1         114s
statefulset.apps/edge-mongodb-primary     1         1         114s
statefulset.apps/edge-mongodb-secondary   1         1         114s
statefulset.apps/edge-zookeeper           3         3         114s
 dick  …  k8s  helm  cell  ./upgrade-edge.sh -f ./uk-london-1-preprod-nodes.yaml 
UPGRADE FAILED
ROLLING BACK
Error: no Service with the name "edge-objectstore" found
Error: UPGRADE FAILED: no Service with the name "edge-objectstore" found
 dick  …  k8s  helm  cell  kubectl -n edge get service edge-objectstore
NAME               TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
edge-objectstore   ClusterIP   10.96.181.14   <none>        80/TCP    11m

**Comment by SlickNik** [comment]
Hi @dick-twocows! 

It's hard to tell why you are facing this without knowing the contents of the `./upgrade-edge.sh` script. Can you verify that the right namespace is being passed in to the `helm upgrade` call in there? Sharing the script contents could also be useful. Thanks!

**Comment by dick-twocows** [comment]
Hi, it's a one line wrapper as follows;

helm upgrade edge ./ -f ./edge-values.yaml "${@}"

We words around install and upgrade so that the releases are handled properly.

The nodes file is passed in because our charts need to know what nodes they are being deployed onto.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

**Comment by prein** [comment]
I think this is related to https://github.com/helm/helm/issues/6031 where one can find workaround ideas.
