### ISSUE TITLE
Migrate tiller namespace alongside releases

### ISSUE THREAD

**Issue by mumrau** [helm/helm#5542]
Hello.

I don't know the precise mechanisms, but the storage is relative and bounded to the tiller namespace. If i'm not mistaken, everything is stored in `ConfigMaps`, and hopefully nothing on the `etcd` side.

If I'm right about everything on the above mechanism, I should be able to move my tiller-namespace seamlessly if I duplicate every `ConfigMap` with label `OWNER=TILLER` to the news namespace, and then install tiller there.

I'm basically looking for a confirmation in order to trigger the migration process.
Anyway, I also think the documentation on the `helm` website could be clarified in order to be more explicit about the responsibility and boundaries of components such as the tiller ( this section could probably be more precise: https://helm.sh/docs/architecture/ ).

Thank you in advance.

Output of `helm version`: ```Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
```

Output of `kubectl version`: ```Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Both OVH Managed or on-prems, AKS eventually.

**Comment by maorfr** [comment]
Maybe https://github.com/maorfr/helm-backup can help. But as far as I know, the answer is yes. Still best to test before you migrate :)

**Comment by mumrau** [comment]
Yup I ran some tests and apparently it's all fine.
To be honest I was really scared because the output of `kubectl describe configmap whatever-release.vX` shows data that looks encrypted, and it could have been with a namespace-bound token/secret or anything, but nope.
This brings me to my next question, is there a key to encrypt/decrypt these configmaps?

**Comment by maorfr** [comment]
Take a look at:
https://github.com/helm/helm/blob/master/pkg/storage/driver/util.go#L31
https://github.com/helm/helm/blob/master/pkg/storage/driver/util.go#L57

**Comment by hickeyma** [comment]
@mumrau Some background on persistence: http://technosophos.com/2017/03/23/how-helm-uses-configmaps-to-store-data.html

**Comment by maorfr** [comment]
nice one @hickeyma, and congrats!

**Comment by mumrau** [comment]
Agreed it's perfect documentation. Maybe a link in the `helm` docs itself would help users to benefit from the resource as well.

I don't know the procedures about this, but it's not up to me to decide if we're adding or not.
On my side, with the technosophos link and the helm plugin, we can consider the issue resolved and this can be closed.
