### ISSUE TITLE
Enhancement helm dependencies

### ISSUE THREAD

**Issue by henres** [helm/helm#5546]
Hello everyone,

It would be nice if the requirements.yaml resolved directly the repositories.

I explain why.

Here my use case. I have an ansible that create a gke cluster.
When the cluster is ready to run, still with ansible,  I install a helm charts that boostrap all my necessary dependencies and some other template/config like gitlab-runner, cert-manager, external-dns, etc ...

Cert-manager use https://charts.jetstack.io as repository and gitlab-runner https://charts.gitlab.io.

The charts is on a git repository. Ansible pull the charts repository and apply it.

For now i need to add all the dependencies repositories with ansible before apply the charts.
But if I add a charts dependencies with another repository, I always need to update the charts and the ansible.

In composer for example, when you define a dependencies, it will resolve automatically. It's the composer.json (who manage the dependencies) that manage the different sources:
https://getcomposer.org/doc/articles/handling-private-packages-with-satis.md
https://getcomposer.org/doc/05-repositories.md

So when I installed it from another server i just need to install composer. I don't need to know if this repository or satis is added to composer.

I don't know if its my explanation is easy to understand.

Thanks

**Comment by lindhe** [comment]
Related to #6005 ?

**Comment by bacongobbler** [comment]
Yep, closing
