### ISSUE TITLE
cannot unmarshal string into Go value of type releaseutil.SimpleHead

### ISSUE THREAD

**Issue by Saurabh-16** [helm/helm#5550]
I am getting unmarshal error on simple validation that I am performing from my .tpl file.

I have a function defined in _helpers.tpl like:-

```
{{- define "actionValidate" -}}
  {{ $action := .Values.actions }}
  {{- if or (eq $action "action1") (eq $action "action2") (eq $action "action3") -}}
    true
  {{- end -}}
{{- end -}}

```
I 'm  invoking this function from one of the .tpl file inside templates folder .

`{{ include "actionValidate" .  | required "Action value is incorrect. The valid values are 'action1', 'action2', 'action3' " }}`

On running helm install command , I'm getting following issue:-
'**_error unmarshaling JSON: json: cannot unmarshal string into Go value of type releaseutil.SimpleHead_**'

However helm dry run command does not show any error and is executed successfully.

Output of `helm version`:
 Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

**Comment by Saurabh-16** [comment]
Is this an issue or there is something wrong with the code syntax .

**Comment by hickeyma** [comment]
@Saurabh-16 I am unable to reproduce this issue. Here is the output of my investigation using a scaffold chart (`helm create`):

```console
$ cat chrt-5550/templates/_helpers.tpl 
 [....]
{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "chrt-5550.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{- define "chrt-5550.actionValidate" -}}
{{ $action := .Values.actions }}
{{- if or (eq $action "action1") (eq $action "action2") (eq $action "action3") -}}
true
{{- end -}}
{{- end -}}

{{/*
Common labels
*/}}
[...]

$ cat chrt-5550/templates/configmap.yaml 
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  {{ if include "chrt-5550.actionValidate" . }}
  action: "IsTrue"
  {{ else }}
  action: "IsFalse"
  {{ end }}

$ cat chrt-5550/values.yaml 
[...]
tolerations: []

affinity: {}

#actions: "action1XXX"
actions: "action1"
```

It installed as expected and also `--dry-run` output 'IsTrue' and 'IsFalse'.
```console
$  helm install chrt-5550/
NAME:   cautious-hummingbird
LAST DEPLOYED: Fri May  3 12:31:45 2019
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/ConfigMap
NAME                            DATA  AGE
cautious-hummingbird-configmap  2     1s
[...]
```

Maybe you can provide me with more details or try test chart as shown.

**Comment by Saurabh-16** [comment]
Inside the templates folder , can you create 1 more yaml file say 'testing.yaml' and invoke the actionValidate method like this:-

{{ include "actionValidate" . | required "Action value is incorrect. The valid values are 'action1', 'action2', 'action3' " }}

While dry run was successful for this use case but actual helm install failed with the unmarshaling error.

**Comment by hickeyma** [comment]
@Saurabh-16 I tested the the helper definition as shown in https://github.com/helm/helm/issues/5550#issuecomment-489067231. I was able to install successfully.  The definition named "chrt-5550.actionValidate"" is invoked from the configmap.yaml.

Maybe you could try out what I did to see if that fixes your issue?

**Comment by Saurabh-16** [comment]
It might have worked using config map . But you may want to check why its not working with the reported approach.
Also I tried few other approaches which solved my use case but I was bit curious of the above solution not working.

**Comment by hickeyma** [comment]
@Saurabh-16 Looking at this again I am finding an issue during install when I use required. Output from my investigation as follows.

```console
$ cat chrt-5550/templates/configmap.yaml 
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  action: {{ include "chrt-5550.actionValidate" . | required "Action value is incorrect. The valid values are 'action1', 'action2', 'action3' " }}

$ helm install --name chrt-5550 chrt-5550/ --debug --dry-run
[debug] Created tunnel using local port: '43491'

[debug] SERVER: "127.0.0.1:43491"

[debug] Original chart version: ""
[debug] CHART PATH: /home/usr1/test/helm-charts/chrt-5550

NAME:   chrt-5550
REVISION: 1
RELEASED: Thu Jun 13 16:56:42 2019
CHART: chrt-5550-0.1.0
USER-SUPPLIED VALUES:
[....]

---
# Source: chrt-5550/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: chrt-5550-configmap
data:
  myvalue: "Hello World"
  action: true
---
[....]

$ helm install --name chrt-5550 chrt-5550/
Error: release chrt-5550 failed: ConfigMap in version "v1" cannot be handled as a ConfigMap: v1.ConfigMap.Data: ReadString: expects " or n, but found t, error found in #10 byte of ...|"action":true,"myval|..., bigger context ...|{"apiVersion":"v1","data":{"action":true,"myvalue":"Hello World"},"kind":"ConfigMap","m|...
```

Looks like this might be a bug.

**Comment by arthurgustin** [comment]
Same error here when I create a tls secret like this:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-ssl-secret
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "api-gateway/google/files/tls.crt" | b64enc }}
```

**Comment by theAkito** [comment]
Same issue in my case with that:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "stuff.fullname" . }}-init
  labels:
    app: {{ template "stuff.name" . }}
    chart: {{ template "stuff.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- $files := .Files }}
  {{-  range tuple "init/init.sh" }}
  {{ . }}: |-
    {{ $files.Get . }}
  {{ end }}
```
results in
```
Error: YAML parse error on stuff-chart/templates/init/init.sh: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type releaseutil.SimpleHead
```

Does anyone know a workaround for this or an alternative to achieve the same thing I am trying to do? I am not familiar with Helm Charts and the Helm Documentation is **absolutely atrocious and disgusting**. I would appreciate any help leading me in the right direction.

**Comment by zffocussss** [comment]
same here.when I try to create a configmap from files.
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: xxxx
  namespace: xxxx
data:
  {{- (.Files.Glob "abc/def/src/*").AsConfig | nindent 2 }}
```

**Comment by wtllc** [comment]
+1 same issue with Helm v3.2.1

**Comment by glasswalk3r** [comment]
Same thing here with:

```
$ helm version
version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

I've got an error with the same message... I was able to fix it, but the error message is absolutely not related to the root cause (from my end).

I was using a template to generate ingress configuration based on a values YAML file and originally it was set like this:

```
{{- $values := .Values }}
{{- $namespace := .Release.Namespace }}
{{- $chart := .Chart }}
{{/*the number of applications that expect a virtual service configuration*/}}
{{- $candidates := 0 }}
{{- range $key, $app := $values.app_list -}}
  {{- if ( and $app.enabled $app.has_virtual_service ) }}
      {{- add1 $candidates }}
  {{- end -}}
{{- end }}
```

My intention was to count how many apps would have a ingress to be configured using the `$candidates` variable, but this code is broken because I'm not assigning the value as I should have. This was causing this exact error message:

```
alceu@yggdrasil(dev):~/k8s-charts$ make conf 
helm template foobar ./charts/foobar --debug --namespace=mine > result.yaml
install.go:159: [debug] Original chart version: ""
install.go:176: [debug] CHART PATH: /home/me/k8s-charts/charts/foobar-app-cdc
Error: YAML parse error on foobar-app-cdc/templates/generic-prefix.ingress.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal array into Go value of type releaseutil.SimpleHead
helm.go:84: [debug] error unmarshaling JSON: while decoding JSON: json: cannot unmarshal array into Go value of type releaseutil.SimpleHead
YAML parse error on foobar-app-cdc/templates/generic-prefix.ingress.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
	/home/circleci/helm.sh/helm/pkg/releaseutil/manifest_sorter.go:146
helm.sh/helm/v3/pkg/releaseutil.SortManifests
	/home/circleci/helm.sh/helm/pkg/releaseutil/manifest_sorter.go:106
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
	/home/circleci/helm.sh/helm/pkg/action/action.go:159
helm.sh/helm/v3/pkg/action.(*Install).Run
	/home/circleci/helm.sh/helm/pkg/action/install.go:238
main.runInstall
	/home/circleci/helm.sh/helm/cmd/helm/install.go:229
main.newTemplateCmd.func1
	/home/circleci/helm.sh/helm/cmd/helm/template.go:66
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:83
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357
Makefile:12: recipe for target 'conf' failed
make: *** [conf] Error 1
```

Fixing the code put everything back to a working state:

```
{{- $values := .Values }}
{{- $namespace := .Release.Namespace }}
{{- $chart := .Chart }}
{{/*the number of applications that expect a virtual service configuration*/}}
{{- $candidates := 0 }}
{{- range $key, $app := $values.app_list -}}
  {{- if ( and $app.enabled $app.has_virtual_service ) }}
      {{- $candidates = add1 $candidates }}
  {{- end -}}
{{- end }}
```

Of course, the error was from my broken code, not from Helm itself. The issue seems to be with the error message, since unfortunately it didn't help me at all to identify the problem.

**Comment by caleb15** [comment]
I'm getting this error with helm version 3.5.0. 

**Replication steps:**
1. `helm create foo2`
2. Insert the `required` line from https://helm.sh/docs/howto/charts_tips_and_tricks/ into the start of the deployment yaml file: `sed -i '1s/^/\{\{ required "A valid .Values.who entry required!" .Values.who \}\}\n---\n/' foo2/templates/deployment.yaml`
3. Insert `who: bob` at the end of the values file: `echo "who: bob" >> foo2/values.yaml`
4. `helm template foo2`


@hickeyma can you remove the stale lifecycle please? It might be more than 30 days between reports but this is a persistent issue and is now easily replicable.

**Comment by sparky005** [comment]
Pretty sure I'm hitting this issue as well. Can the issue be reopened?

**Comment by bacongobbler** [comment]
I'll re-open this as an open invitation for someone to look into this issue. I don't have enough time to fix this but contributions are welcome. Thanks for the reproduction case @caleb15.

**Comment by wizbit** [comment]
Using @caleb15 instructions the error occurs in `pkg/releaseutil/manifest-sorter.go` line `145`, the cause is a yaml document that does not match a `SimpleHead` structure:
```yaml
apiVersion: ...
```

Should helm support generating yaml documents that are not Kubernetes Resources or should the error message explain it better?

**Comment by wizbit** [comment]
I've added a [PR ](https://github.com/helm/helm/pull/9941) but the auto linking hasn't worked.

**Comment by mahaffey** [comment]
I've found a workaround. You can comment out the function invocation and helm will still perform the validation, failing if a  truthy value is not returned by the validation function.


`_helpers.tpl`
```
{{- define "actionValidate" -}}
  {{ $action := .Values.actions }}
  {{- if or (eq $action "action1") (eq $action "action2") (eq $action "action3") -}}
    true
  {{- end -}}
{{- end -}}

...
```
 
 `validations.yaml`
 ```
 # Execute Variable Validations.

# NOTE This is a helm hack, the functions for validation are defined in _helpers.tpl
# The validation function invocations must be yaml commented out.
# Otherwise, there will be golang runtime error
# This workaround allows go parser to be happy while still fishing out invalid values

# {{ include "actionValidate" .  | required ".Values.actions value is incorrect. The valid values are 'action1', 'action2', 'action3' "  }}

 ```

**Comment by marksugar** [comment]
i have the same problem
Or am I using the wrong method?

```
data:
  {{- $tfile := .Files }}
  {{- range tuple "1.toml" }}
  {{ . }}: |-
    {{ $tfile.Get . }}
  {{- end }}
```
  
 1.toml
 ```
  test="123"
 ``` 
  
helm version
```
 PS H:\> helm.exe version
version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.17.5"}
```

template 
```
PS H:\k8s-1.20.2\helm> helm.exe template test .\liunuxea\
Error: YAML parse error on linuxea/templates/1.toml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type releaseutil.SimpleHead

Use --debug flag to render out invalid YAML
```

when modified to json
```
{ test="123" }
```
template  as follows
```
data:
  1.toml: |-
---
# Source: linuxea/templates/1.toml
{ test="123" }
```

thanks

**Comment by MadEngineX** [comment]
> Same error here when I create a tls secret like this:
> 
> ```yaml
> apiVersion: v1
> kind: Secret
> metadata:
>   name: api-gateway-ssl-secret
> type: kubernetes.io/tls
> data:
>   tls.crt: {{ .Files.Get "api-gateway/google/files/tls.crt" | b64enc }}
> ```

Hello! Try to do something like that:

```
tls.crt: {{ .Files.Get "api-gateway/google/files/tls.crt" | b64enc | quote  }}
```

or

```
tls.crt: {{ .Files.Get "api-gateway/google/files/tls.crt" | toString | b64enc | quote   }}
```

**Comment by abdennour** [comment]
For me, it's about wrong filename of Notes... Instead of `NOTES.txt`, it was `Notes.txt` 
It's working now after renaming it `mv templates/Notes.txt templates.NOTES.txt`

**Comment by pdmack** [comment]
For other travelers who find themselves here...
This can also be caused by certain unprintable chars/bytes making their way into your YAML, say when going through certain editors. YMMV.

**Comment by kasabov** [comment]
I created my "test.yaml" to test how my named template renders some arbitrary text (i.e. not yaml). I was getting the unmarshalling errors until I used the following code:

    test: >-
      {{ include "my-named-template" . | nindent 2 }}

The use of both `>-` and `| nindent 2` is important here.

**Comment by Treehopper** [comment]
In my case the error was thrown on a json file with a top-level array object (which does qualify as valid json, according to RFC 4627).

**Comment by SOF3** [comment]
fwiw, I was parsing `- {"json": "object"}` with `fromYamlArray` and accidentally forgot the `- ` in front of the line and got this error.
