### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by Batarian711** [helm/helm#5554]
Hello. I design a logo for open source projects voluntarily. Do you want to help?

**Comment by bacongobbler** [comment]
Thanks for your interest! We do have a Helm logo already that can be found at https://helm.sh/, but we're always happy for feedback on the logo, the website design, or any of the material released at conferences. @flynnduism might be particularly interested if you have any feedback on the current logo design, either for Helm or for other Helm-related subprojects.

What do you think?

**Comment by Batarian711** [comment]
I designed a logo that contained the rudder and the initiator of the project. Which one do you like?


![helm](https://user-images.githubusercontent.com/41051393/55664517-e6cab280-5837-11e9-8cb7-916cded0fdc6.jpg)

**Comment by bacongobbler** [comment]
Thank you but we already have a logo. As mentioned earlier please feel free to provide feedback on the existing logo; we're not planning on changing the logo out at this time. Thanks!
