### ISSUE TITLE
Force deletion of a release - when pre-delete hooks fail

### ISSUE THREAD

**Issue by kierenj** [helm/helm#5556]
I'm trying to delete a release I created using a "bad" chart.  The chart has two pre-delete hooks, both turned out to be named exactly the same thing.

`helm del whatever --purge` gives an error that the pre-delete hook already exists, then bails.

I've deleted all the other resources, but the name remains in the helm release list.

How can I clear this up?

Output of `helm version`:

Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.11-gke.1", GitCommit:"5c4fddf874319c9825581cc9ab1d0f0cf51e1dc9", GitTreeState:"clean", BuildDate:"2018-11-30T16:18:58Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

GKE

**Comment by thomastaylor312** [comment]
Oh that is an interesting edge case. I'll mark it as a bug and as a good first issue (should just be a check to see if there is a duplicate name for hooks on install).

As for working around it, you should be able to run `helm delete --purge --no-hooks <release_name>`. If that doesn't work, you can list the config maps in the tiller namespace (likely `kube-system`) and then delete the all the config maps containing the release name if you are sure all the other resources are gone. Let me know if that works for you!

**Comment by thomastaylor312** [comment]
Removing good first issue because it looks like it might be a bit more complex than I thought

**Comment by kierenj** [comment]
The `--no-hooks` did work for me, thanks.  I did look at `helm delete --help` but clearly missed `--no-hooks` ... oops

**Comment by thomastaylor312** [comment]
No problem! You helped find an interesting edge case for us
