### ISSUE TITLE
when killing `helm dep up` the next `dep up` fails

### ISSUE THREAD

**Issue by sgandon** [helm/helm#5567]
when killing the process running `helm dep up` it sometimes leave a temporary folder named `tmpcharts` and this makes the next `helm dep up` fail with the following error.
```
Error: Unable to move current charts to tmp dir: rename /mychart/charts /mychart/tmpcharts: file exists
```
This is easily reproducable by creating a folder named `tmpcharts` inside an helm chart root folder and try to launch `helm dep up`

Of course a workaround is to remove the folder manually before running the `helm dep up` but that would be great that helm did that automatically somehow.

Output of `helm version`:
```
$helm version
Client: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-04T04:48:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): docker for mac

The code handling this is here : https://github.com/helm/helm/blob/53d432fa58748412ff3dc10bc27cbf996d96c3ed/pkg/downloader/manager.go#L190

**Comment by thomastaylor312** [comment]
Good catch on this bug. Let me see if I can hammer out a quick bug fix this week

**Comment by wknapik** [comment]
Ran into this in 2.12.3 on Linux.

**Comment by sgandon** [comment]
I would have proposed a PR to fix this, be the first and only PR I did on this project took one year to get reviewed. So I'll pass.

**Comment by lindhe** [comment]
This is still an issue in 3.0.3.

**Comment by EnziinSystem** [comment]
This is still an issue in v3.1.2+gd878d4d

**Comment by pankaj-akhade** [comment]
My helm version is v3.2.1.

I am running a jenkins job where I do "helm dep update chart/<dir>"
But I am getting the same error.

**Comment by MiaoRachelYu** [comment]
My helm version is v3.2.1. I do not have command "helm dep up" in the script. Every time, I run with a new container, but when I execute "helm dep update chart" with a Jenkins job, it fails with the same error shown above.

**Comment by zak905** [comment]
Any updates on this issue ?

**Comment by zak905** [comment]
To solve this in my case, I had to: `rm -rf charts` and `rm -rf tmpcharts/`

It seems like helm assumes `tmpcharts` should not present, since it deletes it after the dependency updates, if one stops the operation in the middle this can happen.

**Comment by lindhe** [comment]
Sounds to me like `tmpcharts` should instead use some unique directory in `/tmp` similar to what `mktemp` does.

**Comment by bacongobbler** [comment]
`tmpcharts` was introduced to fix a cross-device linking error as seen in https://github.com/helm/helm/issues/1472.

**Comment by bacongobbler** [comment]
like so:

https://github.com/helm/helm/blob/d0422e6d82b9d7ddc9c24f02ed1f7d321f9e2646/pkg/action/lint.go#L87

**Comment by vikkyomkar** [comment]
I would like to contribute to this issue. Pls let me know if its available to pick ?

**Comment by bacongobbler** [comment]
go ahead.

**Comment by tnleeuw** [comment]
I get this error all the time trying to run helm, both with version 2.14.3 (which is what we have installed in our cluster) and when using the latest locally (v3.3.0). It is something with my system perhaps -- but it happens always, even though the directory `tmpcharts` does not exist before I run Helm.
The directory `charts` is created properly when it doesn't yet exist.

Creating a directory with a unique name, instead of assuming that the fixed name `tmpcharts` does not exist, is perhaps a more robust solution.

(Meanwhile I'm looking for the solution to my local issue)

**Comment by deathname** [comment]
Can I work on this issue

**Comment by hickeyma** [comment]
@deathname  Maybe ask  @vikkyomkar if no longer working on it?

**Comment by vikkyomkar** [comment]
> Can I work on this issue

Pls go ahead. I dont have bandwidth for now

**Comment by lindhe** [comment]
I think this should be kept alive.

**Comment by bacongobbler** [comment]
re-opening. I have a PR that I will push up soon that will hopefully address all cases provided in prior PRs without introducing new bugs.

**Comment by lindhe** [comment]
I guess this should stay open until #9889 is merged.

**Comment by shyam-ks** [comment]
> when killing the process running `helm dep up` it sometimes leave a temporary folder named `tmpcharts` and this makes the next `helm dep up` fail with the following error.
> 
> ```
> Error: Unable to move current charts to tmp dir: rename /mychart/charts /mychart/tmpcharts: file exists
> ```
> 
> This is easily reproducable by creating a folder named `tmpcharts` inside an helm chart root folder and try to launch `helm dep up`
> 
> Of course a workaround is to remove the folder manually before running the `helm dep up` but that would be great that helm did that automatically somehow.
> 
> Output of `helm version`:
> 
> ```
> $helm version
> Client: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}
> Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
> ```
> 
> Output of `kubectl version`:
> 
> ```
> kubectl version
> Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-04T04:48:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
> Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
> ```
> 
> Cloud Provider/Platform (AKS, GKE, Minikube etc.): docker for mac
> 
> The code handling this is here :
> 
> https://github.com/helm/helm/blob/53d432fa58748412ff3dc10bc27cbf996d96c3ed/pkg/downloader/manager.go#L190

Same issue coming up in v3.7.2
it should reuse /tmp folder. Getting this error in GitHub hosted runners

**Comment by basvdheijden** [comment]
Where can I manually delete this tmpcharts folder to mitigate the issue? I'm currently unable to deploy without the fix for this.
