### ISSUE TITLE
Command line parsing issues lead to difficult to understand/debug error messages

### ISSUE THREAD

**Issue by wknapik** [helm/helm#5569]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS

E.g.:
```
% helm package --save=false . 
Successfully packaged chart and saved it to: foo/bar-v1.2.3.tgz
% helm package --save false .
Error: chart metadata (Chart.yaml) missing
%
```
The error message has nothing to do with the actual issue.

Using ` ` instead of `=` is something that most command line tools allow, including stuff in coreutils and util-linux, which helm users use daily.

If this is not considered a bug, I think noting that `=` has to be used in `--help` messages might make sense.

**Comment by hickeyma** [comment]
Thanks @wknapik for finding this issue.

As per commands like `helm install`, its flags like ` --name` and `--namespace` don't use the assignment operator (`=`). I think then that the space would be best for consistency.

**Comment by wknapik** [comment]
IMO ` ` and `=` should be interchangeable. And it's the only way to maintain backwards compatibility anyway.

**Comment by hickeyma** [comment]
Good point.

**Comment by bacongobbler** [comment]
This is a behavioural difference from cobra on how they parse string flags vs boolean flags. The same behaviour was noticed in https://github.com/helm/helm/issues/4969. https://github.com/spf13/cobra/issues/613#issuecomment-357706597 explains the behaviour.

If you'd like to write some documentation on how Helm parses option flags, that'd be appreciated.

**Comment by bacongobbler** [comment]
Parsing boolean flags *need* an equals sign as the following is ambiguous from a parser's standpoint:

```
command config set foo --enable-feature-flag false
```

The last argument is ambiguous; is the user setting `--enable-feature-flag` to false, or is false the argument to `config set foo` and `--enable-feature-flag` set to true? In this case, Coreutils specifies that boolean flags NEED an equal sign to set to false, so cobra is parsing the option flags correctly here.

I'm unmarking this as a bug as this is the intended behaviour from cobra's parser's point of view, as multiple issues in cobra's issue queue mention that you need to explicitly add the equals sign to the operation for the boolean to affect the value. Documentation pointing to how Helm parses flags (coreutils style) would be a great enhancement to the docs.

**Comment by wknapik** [comment]
Wow. You guys really think [this](https://github.com/spf13/cobra/issues/613#issuecomment-357706597) and [this](https://github.com/helm/helm/issues/4969#issuecomment-443860216) is ok ? IMO this is just completely b0rken. This should not be documented, it should be nuked from orbit ;]

Seriously, I wouldn't even think to look at any documentation to see what `-c false` [means](https://github.com/helm/helm/issues/4969#issuecomment-443916560) - I would just assume it works the way it does in every other cli tool, that's not written in golang.

This is a massive violation of the [principle of least surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment). The tool ends up doing the opposite of what the user requested. Best case, it returns a cryptic error message (like in this bug report), worst case, it causes some horrible production meltdown.

---

@bacongobbler the ambiguity with boolean values exists only because the argument is optional. A bug in itself if you ask me, because it solves zero problems, while introducing this one.

> Coreutils specifies that boolean flags NEED an equal sign to set to false, so cobra is parsing the option flags correctly here.

Can you please link to that document ? Maybe I'm missing something, but I can't find a single tool in coreutils, that accepts a boolean argument (true/false, yes/no, on/off) to a switch (-x/--long-x). And there's no need for boolean values either. Here's a snippet from `man 1 uniq`:
```
       -i, --ignore-case
              ignore differences in case when comparing
``` 
Pass `-i` and differences in case will be ignored. Don't pass it and they will not be ignored.
If you want to be able to explicitly set both options (true and false), here's an example from `man 1 chcon`:
```
       --no-preserve-root
              do not treat '/' specially (the default)
       --preserve-root
              fail to operate recursively on '/'
```
or from `man 1 chgrp`:
```
       --dereference
              affect the referent of each symbolic link (this is the default), rather than the symbolic link itself
       -h, --no-dereference
              affect symbolic links instead of any referenced file (useful only on systems that can change the ownership of a symlink)
```
Clear, unambiguous and consistent. No functionality is lost and there's no need for special unexpected handling of some specific values.

---

To me this is a high severity usability issue. It produces useless feedback for the user and, more importantly, it may cause the tool to behave in the _opposite_ way to the one the user requested.

It can be fixed in helm without switching away from cobra. Just don't use options that accept boolean values. Or, if cobra allows it, make the values mandatory, thus removing the ambiguity, but I'm guessing cobra can't handle that.

**Comment by wknapik** [comment]
`tl;dr` Don't use options that accept true/false. Use one option for true and one for false.

The old approach would have to be phased out over time, but it's doable.

**Comment by hickeyma** [comment]
@bacongobbler @wknapik Some very good points raised, thanks. Here is my attempt to summarise the problem.

Firstly, @bacongobbler is correct in saying that you need to provide the assignment operator (`=`) with a boolean flag when you want to set true/false. This is a [limitation of pflag](https://github.com/spf13/pflag#command-line-flag-syntax) Go's flag package [used by cobra](https://github.com/spf13/cobra#flags).

@wknapik I think you are correct in saying that this is a usability issue as not everyone would expect having to assign the value using the assignment operator (`--save=false` value as is in this scenario). Also, having to set true/false to a CLI flag is counter-intuitive.

I think the best solution here is that the `save` flag is replaced with `not-save`, which when used on the CLI (`helm package --not-save`), does not save the packaged chart to local chart repository. Unfortunately, this would break backwards compatibility for Helm 2.x.  @bacongobbler suggestion that the documentation should be updated to inform the user how `save` flag is set, applies best until Helm 3. Helm 3 is currently in progress and all boolean flags will not require to be set to true/false value in this next major release. 

From what I can see, there are only one other boolean flag with this issue similar to `save`. It is `automount-service-account-token` in the `helm init` command. This could be updated under the same doc PR

Let me know what what you think.

**Comment by wknapik** [comment]
I would suggest following the well established convention of using `--option`/`--no-option` (rather than `--not-option`).

I also think that in helm 3 there should be no options accepting boolean values - this is probably the only way to avoid this problem without dropping cobra, and to bring helm in line with the most popular cli tools. Since this change would not be backwards compatible, it would have to be a part of a new major version, such as the upcoming v3.

In that case there would be no need for any additional explanation in the docs, but the changes in available options would need to be documented and included in the changelog.

**Comment by bacongobbler** [comment]
We are not going to double the amount of boolean flags in Helm just to handle this case, along with all the logic required to determine which takes precedence depending on which is the default, and what happens when both `--save` and `--no-save` are both present. A simple yes/no boolean flag (i.e. `--save` or `--save=false` is sufficient for most programs.

With regards to the argument about the presence of an equal sign on boolean flags, please file an issue upstream with coreutils or with cobra. There is no action to take here as this behaviour is defined upstream, and as far as I'm aware, the behavior described is correct, [as I explained earlier](https://github.com/helm/helm/issues/5569#issuecomment-480945055).

**Comment by marckhouzam** [comment]
About needing the `=` when setting a boolean value, here is an explanation: https://github.com/spf13/cobra/issues/613#issuecomment-357706597

Basically, since a boolean flags can be used without a value, for example `helm --debug` then it becomes impossible to know if the `false` of `helm --debug false` is an argument to the flag, or a separate argument to the command.  That's why we need to use `=` to set the non-default value of a boolean flag.
