### ISSUE TITLE
helm dependency list shows "too many matches" for helm charts with "-"?

### ISSUE THREAD

**Issue by televi** [helm/helm#5571]
Not sure if this is a bug or expected behavior.

Given a chart with dependencies foo and foo-bar, when doing a helm dependency list, I get "too many matches" for the chart.  What seems to be happening is that at [this line in dependency.go](https://github.com/helm/helm/blob/08dad14e13b1f7b069949bf62fb960a1289e96f2/cmd/helm/dependency.go#L157), filename is set to a glob of dep.Name-*.tgz and that will match any chart that starts with the string dep.Name- and ends in .tgz, so both foo and foo-bar match (which is what I am seeing).

I found a few issues talking about whether a "-" in a chart name is valid or not and it seems it is (in fact the [conventions](https://github.com/helm/helm/blob/master/docs/chart_best_practices/conventions.md) still show examples using it).  Issue [#4400](https://github.com/helm/helm/pull/4400) says this should be valid as well - the only caution there is re: dashes in variable names in Go templates.

If dashes are acceptable, then its not clear to me why dependency.go would glob on them - that seems to essentially say that there can't be two charts with the same prefix, a dash, and some other string before the .tgz (foo-blah, foo-bar, foo-bleck would all seem to match that glob).  Am I missing something?

**Comment by bacongobbler** [comment]
Seems to be a bug in the dependency resolver. Thanks for the report. Do you happen to have a patch and tests available to fix this?

**Comment by televi** [comment]
I'm afraid I don't - I'm not really a Go programmer so creating one will be non-trivial for me.  I can try to take a look at the current code base but it will take me a bit.

**Comment by marrobi** [comment]
I hit this today. Anybody got a work around/solution?

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
