### ISSUE TITLE
how to handle CRD Ingress ressources?

### ISSUE THREAD

**Issue by thewilli** [helm/helm#5574]
Getting a application to work by simply deploying a Helm Chart is great. By having an optional Ingress configuration provided in the default template (and many Chart authors sticking to this) it's easy to publish a newly deployed service as well.

Few Ingress Controllers don't stick to the standard Ingress ressource, though ([Traefik v2](https://blog.containo.us/back-to-traefik-2-0-2f9aa17be305#4b08), [Voyager](https://appscode.com/products/voyager), ...). What is the proposed way to work with them? Especially in a CI/CD context where one want to be as generic as possible?

* One could manually create the Ingress CRDs after a deployment
  * Is there any way to get `Tiller` to at least remove a manually created ressource once the Chart installation is removed?
* A custom Chart per application having the *actual* Chart as Subchart seems overkill.
  * Would it be possible to create a *generic* wrapper Chart? Would require *dynamic* definition of a Subchart, though.

**Comment by mattfarina** [comment]
There is a [chart lifecycle hook](https://helm.sh/docs/developing_charts/#hooks) for `crd-install`. This can be used to install the CRD if Tiller has access to do so in a cluster. Have you tried that?

**Comment by thewilli** [comment]
@mattfarina there might be a misunderstanding. Let me please give an example.

Consider you were using the [Traefik 2](https://docs.traefik.io/v2.0/) Ingress controller for a Kubernetes cluster. The Ingress Controller uses a [CRD](https://docs.traefik.io/v2.0/reference/dynamic-configuration/kubernetes-crd/) to manage Ingress instead of the [Kubernetes-provided one](https://kubernetes.io/docs/concepts/services-networking/ingress/).

Now you want to install and expose some 3rd party applications. Just pick any 10 from the official `stable` repo.

They all seem to follow the default design pattern - which is good. They do not provide a convenient way to create a Traefik Ingress CRD by modifying the settings.

Right now manual installation and maintenance as well as automated deployment and updates of Helm Charts works pretty well. But how can the need to *add* some YAML definitions like the Ingress definition fit into this picture? I'd like to *glue* this ressource on the Chart installation, so it gets removed whenenver I remove the Chart. Even better would be the possibility to provide additional YAML templates that get rendered along with the regular Chart, can make use of itsconfiguration and get deploy amongst it.

My problem is that my automation broke. Previously it didn't take more than the path to a Helm Chart and a YAML file with configuration overrides to deploy any application. Now I am in the need to keep track of the lifecycle in order to add and remove my manually generated CRDs.

Do you get my point?

The Ingress example is only one example for this. Another one could be the [OpenEBS Chart](https://github.com/helm/charts/tree/master/stable/openebs/). In order to use that CAS solution in production, one need to create a custom Storage Class (amongst other (C)RDs). It would be great if I could just configure it to include my custom definitions.

**Comment by mattfarina** [comment]
I see. I think I understand the confusion. When you install the Traefik 2 ingress controller a CRD is installed. Then, each time you want to use it you install a Custom Resource (CR) to use it. The CRD is the definition (installed just once globally) and the CR is used each time. For each application there is a CR. The confusion was around the acronym use.

This would be classified as a feature request. One we'll need to talk about.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity (it's been 15 months since there was last any conversation about this), but please re-open if this still needs to be addressed in Helm 3. Thanks!
