### ISSUE TITLE
helm init --wait | tiller was not found.

### ISSUE THREAD

**Issue by henres** [helm/helm#5580]
I have a weird behavior with `--wait` on helm init:

```shell
$ helm init --service-account tiller --history-max 200 --wait
$HELM_HOME has been configured at /home/henres/.helm.
Warning: Tiller is already installed in the cluster.
(Use --client-only to suppress this message, or --upgrade to upgrade Tiller to the current version.)
Error: tiller was not found. polling deadline exceeded
```

```shell
$ helm init --service-account tiller --history-max 200       
$HELM_HOME has been configured at /home/henres/.helm.
Warning: Tiller is already installed in the cluster.
(Use --client-only to suppress this message, or --upgrade to upgrade Tiller to the current version.)
Happy Helming!
```

And when the version match when I upgrade with `--upgrade` it work again:
```
$ helm init --service-account tiller --history-max 200 --wait --upgrade
$HELM_HOME has been configured at /home/henres/.helm.

Tiller (the Helm server-side component) has been upgraded to the current version.
Happy Helming!

$ helm init --service-account tiller --history-max 200 --wait          
$HELM_HOME has been configured at /home/henres/.helm.
Warning: Tiller is already installed in the cluster.
(Use --client-only to suppress this message, or --upgrade to upgrade Tiller to the current version.)
Happy Helming!
```

Output of `helm version`:
```
$ helm version                                        
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.7-gke.12", GitCommit:"06f08e60069231bd21bdf673cf0595aac80b99f6", GitTreeState:"clean", BuildDate:"2019-02-25T20:37:10Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
The cluster is on GKE.

**Comment by bennya1** [comment]
Encountered the same behavior on AKS, i believe it origins in the latest version of Helm, since nothing has changed except the client version which was automatically updated. 

To resolve in my staging environment i also added `--upgrade` to update tiller automatically. 
For production would probably keep the previous Helm client version (not tested yet).

**Comment by hickeyma** [comment]
If the client version is a later version to the server version (Tiller) this can lead to intermittent problems. It is recommended to have client and server versions the same (ideal situation) or server version later than the client version.

The `--upgrade` flag with `helm init` command will update the server (Tiller).

**Comment by nscozzaro** [comment]
I just wanted to add my datapoint that I started getting this error when I switched on GKE from  
`--machine-type n1-standard-2 --num-nodes 1` to `--machine-type f1-micro --num-nodes 4`. Not sure why that would cause the issue though.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
