### ISSUE TITLE
Clean code: delete commented out code

### ISSUE THREAD

**Issue by ChristianWeissCG** [helm/helm#5584]
Some helm lint rules were disabled in 2016:
https://github.com/helm/helm/issues/1463
https://github.com/helm/helm/issues/1037

Should be removed from code:
https://github.com/helm/helm/blob/master/pkg/lint/rules/template.go#L109
https://github.com/helm/helm/blob/master/pkg/lint/rules/template.go#L113

Clean code.

**Comment by hickeyma** [comment]
@ChristianWeissCG Is this a cleanup you would like to do?

**Comment by amoury** [comment]
@hickeyma Can I open a PR for this?

**Comment by bacongobbler** [comment]
looks like $5614 was already opened to address this.

**Comment by amoury** [comment]
> looks like $5614 was already opened to address this.

Ok thanks for letting me know 👍

**Comment by girishramnani** [comment]
https://github.com/helm/helm/pull/5614 was merged, I think this issue should be closed now

**Comment by hickeyma** [comment]
Thanks @girishramnani for reminding me. Closing as #5614 closed.
