### ISSUE TITLE
What is the intention behind helm lint for metadata namespace?

### ISSUE THREAD

**Issue by ChristianWeissCG** [helm/helm#5585]
From the comment at the beginning of this function one could think that there is a check related to metadata.namespace, but no related ERROR, WARN or INFO is triggered:
https://github.com/helm/helm/blob/master/pkg/lint/rules/template.go#L96

What is the intention?

**Comment by hickeyma** [comment]
It could be an outdated comment. I think this could be included as part of #5584.

**Comment by hickeyma** [comment]
Closing as duplicate of #5584.

**Comment by Fantaztig** [comment]
The comment is still there today :)
