### ISSUE TITLE
New items in failed upgrade stays forever

### ISSUE THREAD

**Issue by henrikb123** [helm/helm#5586]
I have a chart that allows environment variables to be added through values.

Scenario:
1. helm upgrade --install the chart successfully

2. add an environment variable in values.yaml that gets picked up by the chart, also trigger the deploy to fail through timeout / readiness probe 
helm upgrade --install this change
kubectl get deploy -oyaml has value
env:
  - name: FOO
    value: BAR

3. remove the variable from the values.yaml file
helm template shows no trace of the variable
again, helm upgrade --install
kubectl get deploy -oyaml STILL has value
env:
  - name: FOO
    value: BAR

I would expect the variable to be gone after (3).

Output of `helm version`:
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"} 
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.8", GitCommit:"4e209c9383fa00631d124c8adcc011d617339b3c", GitTreeState:"clean", BuildDate:"2019-02-28T18:49:34Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.5", GitCommit:"51dd616cdd25d6ee22c83a858773b607328a18ec", GitTreeState:"clean", BuildDate:"2019-01-16T18:14:49Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
NA / self hosted

**Comment by hickeyma** [comment]
@henrikb123 Could you provide more details like the template and the output when you do a get?

**Comment by henrikb123** [comment]
Hi, with template do you mean the full chart?
Output from get - you mean the "kubectl get deploy..." command?

**Comment by henrikb123** [comment]
[repro-chart.zip](https://github.com/helm/helm/files/3068269/repro-chart.zip)



[command_history.txt](https://github.com/helm/helm/files/3068272/command_history.txt)
[deployment-after-3.txt](https://github.com/helm/helm/files/3068275/deployment-after-3.txt)
[deployment-after-1.txt](https://github.com/helm/helm/files/3068276/deployment-after-1.txt)
[deployment-after-2.txt](https://github.com/helm/helm/files/3068277/deployment-after-2.txt)

Uploading some files

Note
In step 2 for simplicity I did --set env.FOO=BAR on the command line in this example. I get the same result if instead I add it at bottom of values.yaml.

**Comment by hickeyma** [comment]
@henrikb123 sorry for the delay in replying.

I have investigated this and have been unable to reproduce it. I started with the extra env variable in a slight variation to your steps. Here is the output of my findings.

```console
$ cat chrt-5586/values.yaml 
[….]
affinity: {}

env:
  ALIVE_SECONDS: 3600
  FOO: BAR

$ cat chrt-5586/templates/deployment.yaml 
[…]
containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
{{ include "expose.env" . | indent 10 }}
          ports:
[…]

$ helm install --name chrt-5586 chrt-5586/
NAME:   chrt-5586
LAST DEPLOYED: Wed May  1 17:08:23 2019
NAMESPACE: default
STATUS: DEPLOYED
[….]

$ kubectl get deployment chrt-5586 -o yaml
[….]
spec:
      containers:
      - env:
        - name: ALIVE_SECONDS
          value: "3600"
        - name: FOO
          value: BAR
[….]


$ cat chrt-5586/values.yaml
[…]
affinity: {}

env:
  ALIVE_SECONDS: 3600
  #FOO: BAR
[…]

$ helm upgrade chrt-5586 chrt-5586/ --debug --dry-run
[debug] Created tunnel using local port: '44803'

[debug] SERVER: "127.0.0.1:44803"

REVISION: 2
RELEASED: Wed May  1 17:21:25 2019
CHART: chrt-5586-0.1.0
USER-SUPPLIED VALUES:

[….]

COMPUTED VALUES:
affinity: {}
env:
  ALIVE_SECONDS: 3600
fullnameOverride: ""
[….]

---
# Source: chrt-5586/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrt-5586
[….]
 spec:
      containers:
        - name: chrt-5586
          image: "nginx:stable"
          imagePullPolicy: IfNotPresent
          env:
            - name: ALIVE_SECONDS
              value: "3600"
 
          ports:
[….]

$ helm upgrade chrt-5586 chrt-5586/
Release "chrt-5586" has been upgraded.
LAST DEPLOYED: Wed May  1 17:23:18 2019
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:

[….]

$ kubectl get deployment chrt-5586 -o yaml

[….]
spec:
      containers:
      - env:
        - name: ALIVE_SECONDS
          value: "3600"
        image: nginx:stable

[….]
```

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
