### ISSUE TITLE
Helm dep update or Helm update states "successful" when it wasn't

### ISSUE THREAD

**Issue by jbrongtr** [helm/helm#5600]
Output of `helm version`:
2.12.3

Output of `kubectl version`:
1.13.1

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
bare metal on VMware

We are running Kubernetes/Helm in an air-gaped environment. When Running a helm dep update or a helm repo update it goes through the list of repos getting an update. It states a successful update from our artifactory helm repo but errors out when trying to contact local and the stable repo. 

The final error says: Error: open C:\.helm\repository\cache\stable-index.yaml: The system cannot find the file specified.

I take this error as my artifactory repo updated fine but the other two had errors (which i don't care about), but helm didn't update its repo. I removed both local and stable repos from helm and then re-ran 'update', which allowed helm to actually download the updated charts from artifactory.

**Comment by bacongobbler** [comment]
Cna you please try a newer version of Helm? As I recall there was path traversal issues in Windows which was fixed in Helm 2.13.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
