### ISSUE TITLE
configmap with certificate data fails when tried helm lint with the error "converting YAML to JSON: yaml: line: could not find expected ':'"

### ISSUE THREAD

**Issue by lh44** [helm/helm#5602]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Minikube

Example: https://github.com/lh44/helm-configmap-with-cert

`helm lint --debug` on the chart fails with the following error

```
==> Linting .
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/configmap.yaml: unable to parse YAML
	error converting YAML to JSON: yaml: line 13: could not find expected ':'

Error: 1 chart(s) linted, 1 chart(s) failed
```

This is caused by the certificate provided in the values.yaml, this however works as expected when the certificate content is provided in the configmap.yaml directly.

I'm assuming there's some issue when the values are being translated into k8s json/manifests

`helm install --dry-run .` outputs,

```yaml
# Source: cm-certs/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-certs
  labels:
  app: cm-certs
  chart: cm-certs
  release: maudlin-chicken
  heritage: Tiller
data:
  server.cert: |-
    -----BEGIN CERTIFICATE-----
MIIDWjCCAkICCQCp02w1pasYDjANBgkqhkiG9w0BAQUFADBvMQswCQYDVQQGEwJG
UjEPMA0GA1UECBMGQWxzYWNlMRMwEQYDVQQHEwpTdHJhc2JvdXJnMRgwFgYDVQQK
Ew93d3cuZnJlZWxhbi5vcmcxEDAOBgNVBAsTB2xpYmZzY3AxDjAMBgNVBAMTBWFs
aWNlMB4XDTExMDQyODA4MjM0MVoXDTIxMDQyNTA4MjM0MVowbzELMAkGA1UEBhMC
RlIxDzANBgNVBAgTBkFsc2FjZTETMBEGA1UEBxMKU3RyYXNib3VyZzEYMBYGA1UE
ChMPd3d3LmZyZWVsYW4ub3JnMRAwDgYDVQQLEwdsaWJmc2NwMQ4wDAYDVQQDEwVh
bGljZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANibOdleRebXSssm
gg++gB/vpuWyJDpHZnN+0ZNC4kfmnH4JZ1ddKtrHonVL6dWNLbb1xjs6LFJHFlhl
YvB3e/+AyjuJyWLmPsVPEnCqohwPIUv6I2PxG8xLIkMPDQHOej0C28ylGvXiAJmh
SsGDvgLWBBzQU5588/qVdTP3OWLjdYb6LTV22i7vm8ouL8mODOc9vsyM8UrzaGjq
2P/sOchkyUIfTWfUG44ieFUcNZZ7U3Tv4TPvAwU53mO79MonOKcsFdr22YDWMTE4
j/SuHpq7KMDsdqu0keExqx+NJ4bJ/Qk/HeRLL5qqftQaU/UTefYTwwNPGYr35xH7
Hpd56b0CAwEAATANBgkqhkiG9w0BAQUFAAOCAQEAlTEbe2gCNHA1oRXsHOaF4sm/
+fz9zs6VWDukuZdjggnMK+9ZHBioGTUUWHWI53tbvFVr1GwQ6V+hi/iPqFTkdtir
0QErPDqh32MWXG00AItxSFQIfu87MggMnVpBYNBOEu3kmWHGWu/pmQ59cYzLM4j4
s2kpqPhw02gCReN8H6izO0w483foO78V2PSNOPUlQfkY9bM2CQjYLhReR0X/b+1q
MJHdZzY/UyyziXkUplbnuKknRFV0nVwVUdXqGKXgaV6ypfBz1xtDpk30SAx6rn9C
C6ZaXlQkDZ+Sfh4FkYf0VUspJCifVt8LWdQOzRhcODH/PsDVhjssXtKkL7HAcg==
-----END CERTIFICATE-----
```
Which is about right. But `helm install .` fails with the proviously given error.

**Comment by lh44** [comment]
Using nindent 4 fixed it for me. in templates/configmap.yaml

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cm-certs.name" . }}
  labels:
  app: {{ include "cm-certs.name" . }}
  chart: {{ include "cm-certs.name" . }}
  release: {{ .Release.Name }}
  heritage: {{ .Release.Service }}
data:
  server.cert: |-
    {{ .Values.server.certificate | nindent 4 | trim }}
```

nindent 4 did the job, but it was adding a new line at the beginning. So trim fixes it.
However, using indent 4 (which is same as nindent 4 + trim) did not work for me

**Comment by lh44** [comment]
Some debugging steps helped to identify this issue,
* `helm template .`: Outputs the generated YAML, cautiously going through the generated YAML, showed the indentation issues in the certificate content.
So trying different indentation options and running the helm template . until the indentation is proper was the key!

**Comment by theAkito** [comment]
This issue still persists. The indentation is perfect.

Thank you for the workaround, lh44, it indeed works.

But this issue still needs to be fixed.

**Comment by randywatson1979** [comment]
> This issue still persists. The indentation is perfect in my file, however it still throws this error when using `indent 4`, rather than `nindent 4 | trim`, which is stupid.
> 
> Thank you for the workaround, @lh44, it indeed works.
> 
> But this issue still needs to be fixed.

Excellent, this is what I needed to set the contents from an enviroment variable. Thnx.
