### ISSUE TITLE
how to upgrade umbrella-chart's dependency charts one by one

### ISSUE THREAD

**Issue by yunzshi** [helm/helm#5623]
Hi Experts,

I have a problem needs your help, thanks in advance.

we want to separate  our services into into 3 umbrella charts: service-app(includes the services developed by our team, are same type: deployment ), statefulset-app(includes the statefulset services developed by our team) and infra (includes DB/kafka etc. common infrastructure sservice),  these 3 charts are just served for dependency charts upgrade, doesn't include any service itself. 

when trigger a helm upgrade, all the dependency charts will be upgraded at the same time, is there a way to upgrade them one by one?

another issue found that sometimes these services' pod not recreated at all after upgrade

Output of `helm version`:

Client: &version.Version{SemVer:"v2.13.0-rc.2", GitCommit:"b0d4c9eb82e036c52d130fcb031e788dffe5a5dd", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.0-rc.2", GitCommit:"b0d4c9eb82e036c52d130fcb031e788dffe5a5dd", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
bare mental server installed kubernetes

**Comment by bacongobbler** [comment]
The idea with an umbrella chart is to manage the entire suite of dependencies in one package. By upgrading chart dependencies individually, you break the assumption that a chart released as one version will always contain the same dependency tree.

If you want to upgrade dependencies one-by-one, then you'll need to bump them in your umbrella's requirements.yaml and cut a new release with that updated version. You can then upgrade to that new version of the umbrella chart which will upgrade its dependencies.

Alternatively, you can manage the individual dependencies with their own release process by releasing them as a separate chart.

Hope this helps.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
