### ISSUE TITLE
Expected behavior of "helm upgrade --atomic --wait --debug --timeout 300 --version 1.1.0"

### ISSUE THREAD

**Issue by fduyangchao** [helm/helm#5626]
I'm using HELM v2.13.0-rc.2 version. When I use "helm upgrade --atomic --wait --debug --timeout 300 --version 1.1.0", the upgraded services are auto-recreated after cmd execution. While per my observation, the services should not be recreated by default. So may I know the expected behaviour in this scenario? Thanks.

#helm version: 
Client: &version.Version{SemVer:"v2.13.0-rc.2", GitCommit:"b0d4c9eb82e036c52d130fcb031e788dffe5a5dd", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.0-rc.2", GitCommit:"b0d4c9eb82e036c52d130fcb031e788dffe5a5dd", GitTreeState:"clean"}

#kubectl version:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by bacongobbler** [comment]
`--atomic` performs an automatic rollback if the release fails during the upgrade.

`--wait` is already set by `--atomic` so it's redundant

It's not clear to me what you mean by "services being auto-recreated after command execution". Would you mind elaborating a bit? Perhaps by showing an example? Thanks.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
