### ISSUE TITLE
helm get <RELEASE> is different from helm upgrade <RELEASE> <CHART> --dry-run --debug

### ISSUE THREAD

**Issue by LittleWhiteYA** [helm/helm#5629]
Hi everyone, I'm recently facing a strange situation ...
Why values in
`helm get releaseA` USER-SUPPLIED VALUES

is different from

`helm upgrade releaseA chartA --dry-run --debug` USER-SUPPLIED VALUES

I thought both of them are using same latest configmap??

Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.5", GitCommit:"51dd616cdd25d6ee22c83a858773b607328a18ec", GitTreeState:"clean", BuildDate:"2019-01-16T18:14:49Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

AKS

**Comment by bacongobbler** [comment]
helm upgrade --dry-run --debug shows the rendered templates of the chart supplied. helm get displays the current release, so it's expected that the output differs.

**Comment by LittleWhiteYA** [comment]
@bacongobbler thanks for your reply.

But both of them are using same chart version.
Most of the USER-SUPPLIED VALUES are same but only one nested yaml object `a.b.env` is different and missing.
Why does that happen?

**Comment by bacongobbler** [comment]
values are not retained from preious upgrades unless the `--reuse-values` flag is provided. What do you see if you use that?

**Comment by LittleWhiteYA** [comment]
After I add `--reuse-values` flag,
`helm upgrade releaseA chartA --dry-run --debug` USER-SUPPLIED VALUES
is same as
`helm upgrade releaseA chartA --reuse-values --dry-run --debug` USER-SUPPLIED VALUES

By the way, the values from `helm get values releaseA -a` also has wrong values `a.b.env`.
`a.b.env` is an object.

**Comment by LittleWhiteYA** [comment]
@bacongobbler any further comments??
