### ISSUE TITLE
--ca-file ignored when adding repo

### ISSUE THREAD

**Issue by kopf** [helm/helm#5632]
Similar to #3792 , I'm having trouble getting helm to use a custom CA when adding a new repo. #3792 is marked as being fixed in `2.10.0-rc1`, but I've also tested that exact version, and get the same `x509: certificate signed by unknown authority` error. See below.

(fyi, I also did the same test with helm `2.10.0` final release, with the same result)

First some sanity checks:

```
aewalto@CMTCLM2VX0KJHTD:~$ curl --cert ~/certs/client.crt --cacert ~/certs/ca.crt -u USER_REDACTED:PASSWORD_REDACTED https://DOMAIN_REDACTED/artifactory/ATV_helm/
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<html>
<head><title>Index of ATV_helm/</title>
</head>
<body>
<h1>Index of ATV_helm/</h1>
<pre>Name  Last modified      Size</pre><hr/>
<pre>No items found.
</pre>
<hr/><address style="font-size:small;">Artifactory/6.8.7 Server at DOMAIN_REDACTED Port 80</address></body></html>

aewalto@CMTCLM2VX0KJHTD:~$ curl --cert ~/certs/client.crt --cacert ~/certs/ca.crt -u USER_REDACTED:PASSWORD_REDACTED https://DOMAIN_REDACTED/artifactory/ATV_helm/index.yaml
{
  "errors" : [ {
    "status" : 404,
    "message" : "File not found."
  } ]
}
```

So, curl can connect to the server using the CA and client certs, and can access the (empty) chart repository. However, I get an error when trying to do this with helm:

```
aewalto@CMTCLM2VX0KJHTD:~$ helm version
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
aewalto@CMTCLM2VX0KJHTD:~$
aewalto@CMTCLM2VX0KJHTD:~$ helm repo add --debug --ca-file ~/certs/ca.crt --cert-file ~/certs/client.crt --username USER_REDACTED --password PASSWORD_REDACTED athena https://DOMAIN_REDACTED/artifactory/ATV_helm
Error: Looks like "https://DOMAIN_REDACTED/artifactory/ATV_helm" is not a valid chart repository or cannot be reached: Get https://DOMAIN_REDACTED/artifactory/ATV_helm/index.yaml: x509: certificate signed by unknown authority
```

This also happens with `v2.10.0-rc.1`:

```
aewalto@CMTCLM2VX0KJHTD:~$ ./helm-v2.10.0-rc.1 version
Client: &version.Version{SemVer:"v2.10.0-rc.1", GitCommit:"aa98e7e3dd2356bce72e8e367e8c87e8085c692b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
aewalto@CMTCLM2VX0KJHTD:~$ ./helm-v2.10.0-rc.1 repo add --debug --ca-file ~/certs/ca.crt --cert-file ~/certs/client.crt --username USER_REDACTED --password PASSWORD_REDACTED athena https://DOMAIN_REDACTED/artifactory/ATV_helm
Error: Looks like "https://DOMAIN_REDACTED/artifactory/ATV_helm" is not a valid chart repository or cannot be reached: Get https://DOMAIN_REDACTED/artifactory/ATV_helm/index.yaml: x509: certificate signed by unknown authority
aewalto@CMTCLM2VX0KJHTD:~$
```

**Comment by bacongobbler** [comment]
thank you for the report. Your usage of the command looks correct to me, so I'm lead to believe it might be a bug in helm itself.

For curiosity's sake, can you try moving the CA cert and the client cert to ~/.helm/ca.pem and ~/.helm/client.pem respectively, then run `helm repo add` again without the CLI flags? I'd try experimenting different options and see if the flags are being parsed. I attempted to fix them in https://github.com/helm/helm/pull/4657 and wrote unit tests to cover that, but I'd like to see if that didn't fix the CLI flag parsing.

**Comment by kopf** [comment]
> For curiosity's sake, can you try moving the CA cert and the client cert to ~/.helm/ca.pem and ~/.helm/client.pem respectively, then run helm repo add again without the CLI flags?

Interesting - when I do that, I get a slightly different error:

```
aewalto@CMTCLM2VX0KJHTD:~$ cp certs/ca.crt ~/.helm/ca.pem
aewalto@CMTCLM2VX0KJHTD:~$ cp certs/client.crt ~/.helm/client.pem
aewalto@CMTCLM2VX0KJHTD:~$ helm repo add --debug --username USERNAME_REDACTED --password PASSWORD_REDACTED athena https://REDACTED/artifactory/ATV_helm
Error: Looks like "https://REDACTED/artifactory/ATV_helm" is not a valid chart repository or cannot be reached: Get https://REDACTED/artifactory/ATV_helm/index.yaml: remote error: tls: handshake failure
aewalto@CMTCLM2VX0KJHTD:~$
```

It may be worth mentioning that my `ca.pem` contains metadata (i.e. it begins with lines like `Bag Attributes:` and `subject=`), and that my `client.pem` contains both a private key and a certificate, each prefixed with metadata.

**Comment by kopf** [comment]
> #3384

Just read that thread, thanks for linking. 

For the record, I'm using the official binaries in all cases:

```
aewalto@CMTCLM2VX0KJHTD:~$ md5 `which helm`
MD5 (/usr/local/bin/helm) = f925222c726949dc6b44cb56d05b58a1
aewalto@CMTCLM2VX0KJHTD:~$ md5 ./helm-v2.10.0-rc.1
MD5 (./helm-v2.10.0-rc.1) = 62bedb39da4f3770fcd66ecd49121542
aewalto@CMTCLM2VX0KJHTD:~$ md5 ./helm-v2.10.0
MD5 (./helm-v2.10.0) = 9118fb8e5609d46a0d3f657d4d30c95d
```

**Comment by kopf** [comment]
Hi @bacongobbler - is there anything I can do to help here, or is there any other info that might help you guys?

I understand totally that this might not have the highest priority for you at the moment :) So, are there any temporary workarounds you could recommend, e.g. a way of disabling the CA cert validation for `helm repo add` ?

Thanks!

**Comment by bacongobbler** [comment]
I'm just as stumped as you are. I don't have any other temporary workarounds I can suggest at the moment. I recall there being a feature request in the issue queue about allowing the user to bypass cert validation (like `curl -k`) but I can't seem to find that ticket right now. 

Please do let me know if you find further clues as to why it isn't working with the CA cert validation in your case. If I find myself with some free time, I'll see if I can take a look into this. Thanks!

**Comment by kopf** [comment]
Hi,

after looking into this (much) deeper, it came to my attention that I had been using a cert & key pair extracted from an old, obsolete PFX file. Using certs and keys from the newest PFX solved the problem. 

Why the older certs passed my `curl` "sanity test" is another question. But I'm guessing the `x509: certificate signed by unknown authority` error is thrown in more cases than one. 

Thanks for your time on this, and sorry that it turned out to be a case of PEBCAK :(
