### ISSUE TITLE
Helm install with passthrough routes

### ISSUE THREAD

**Issue by Nickuru** [helm/helm#5633]
Output of `helm version`:
2.13

Output of `kubectl version`:
1.11.0

Output of `oc version `:
v3.11.0

Hello. I use helm to deploy my services to OKD and i have a problem. I use the ingress file to create the paths to the service ports and when it comes to http there are no problems, but i need https path with passthrough(!) TLS. 

And i cant find how can i do this. Could you show me where it is described? 
By the way, if you made the possibility to write like this, it would be just amazing.

rules:
  - host: example.com
    http**s**: ...

Thanks.

**Comment by bacongobbler** [comment]
You may want to take a look at examples such as the [elasticsearch chart](https://github.com/helm/charts/blob/b9d61bda41bc08a5ac85b2087d542d2224f48231/stable/elasticsearch/templates/client-ingress.yaml) on how they allow users to configure their ingress routes.
