### ISSUE TITLE
Helm missing a dedicated status code for --atomic operations

### ISSUE THREAD

**Issue by IdanAdar** [helm/helm#5637]
Output of `helm version`:
2.13.1 for both Helm client and Tiller.

Output of `kubectl version`: 
v1.12.7

Cloud Provider/Platform (AKS, GKE, Minikube etc.):
IKS (IBM Cloud Kubernetes Service)

Helm 2.13.x provides the `--atomic` flag to handle rolling back to a previous deployment in case of a failed deployment. This is good, however Helm is not providing a dedicated status code for this operation, and this makes it less robust from a scripting perspective for automation purpose where we need to know to do different things based on the outcome of an operation.

A successful deployment is not the same as a successful deployment that happened due to a rollback with `--atomic`, hence it needs to be differentiated by status code. 

@bacongobbler Would it be possible to add this additional status code?

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
