### ISSUE TITLE
helm delete --purge does not delete a job created with pre-upgrade hook

### ISSUE THREAD

**Issue by pjanuario** [helm/helm#5645]
**Bug Report** 

I created a Job with a pre-upgrade hook, when helm delete is run the job and its completed pod are not deleted from the cluster.

Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-04T07:49:54Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform: Kubernetes @ Digital Ocean

**Comment by bacongobbler** [comment]
this is called out in the docs. See https://helm.sh/docs/developing_charts/#hook-resources-are-not-managed-with-corresponding-releases

> The resources that a hook creates are not tracked or managed as part of the release. Once Tiller verifies that the hook has reached its ready state, it will leave the hook resource alone.

> Practically speaking, this means that if you create resources in a hook, you cannot rely upon helm delete to remove the resources. To destroy such resources, you need to either write code to perform this operation in a pre-delete or post-delete hook or add "helm.sh/hook-delete-policy" annotation to the hook template file.

**Comment by pjanuario** [comment]
@bacongobbler thank you for the response, I didn't seen that in docs, now it's clarified. This issue can be closed.
