### ISSUE TITLE
Does helm test provide the feature that run a single test individually

### ISSUE THREAD

**Issue by AlexPBZhang** [helm/helm#5647]
Hi,
I have a question for helm test.Does helm test provide the feature that run a single test individually?  For example, if I have several tests, can I run one of them based on its name single without running other tests? Looks like if I use the default command ```helm test <realeaseName>```all the tests will run together.
Thanks!

**Comment by bacongobbler** [comment]
I don't believe that functionality exists, though I do think that's a neat use case! cc @michelleN

**Comment by jan25** [comment]
@bacongobbler would you know if someone is looking into this? If not i'd be happy to pick this

**Comment by michelleN** [comment]
Hey @jan25 - this seems like a great idea. Checking out how `helm test` for v3 works in[ this PR](https://github.com/helm/helm/pull/5911) would be a good place to start.  Feel free to take this on. The first step is to come up with a design for this feature. Is this going to be a flag? How do you figure out which tests are available? That sort of thing. Ping me if you wanna chat or need help.

Cheers

**Comment by jan25** [comment]
Hey @michelleN thanks! I went through how we do `helm test` in v3 tag, also your PR was very helpful. Also, came across this https://github.com/helm/community/pull/40 proposal. So, i suppose this feature won't be implemented for helm2, but for v3 only?

Currently, i'm thinking of ways to add this as a new flag(`--name`) to `helm test` command which selects test manifests based on the name in metadata. Also, I think this new flag can be applied to rest of proposed commands. For example, we could have `helm test [run|cleanup|results] <release> --name=<test1>,<test2>`. Should we add this as part of proposal too, or do we see this as one of next steps after proposed steps are released?

**Comment by jlegrone** [comment]
We might be able to use a label selector which would be more flexible than name (helm would need to compute all the labels for test pods/jobs before applying them to the cluster, then use a user-specified label selector to figure out which ones to run).

**Comment by wid** [comment]
I found a easy solution for this:

For each of your separate test create a chart containing only your test and support pod/services for the test. 
then helm install / helm test

**Comment by kieronlangdon** [comment]
> I found a easy solution for this:
> 
> For each of your separate test create a chart containing only your test and support pod/services for the test.
> then helm install / helm test

Hmm I think the idea was to run a select amount of tests on an install at a time, rather than running the install each time the tests are required to run.

**Comment by hxia043** [comment]
hello, thanks for the discussion, may I ask again does it is supported in helm v3?
