### ISSUE TITLE
Helm fails to parse SemVer versions with parts that are larger than 32 bits

### ISSUE THREAD

**Issue by paddycarey** [helm/helm#5648]
Output of `helm version`: 

```
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Docker for Desktop

## Issue

The version of `github.com/Masterminds/semver` used by Helm (1.3.1) supports a max size of 32bits for each part of the SemVer version.

e.g. trying to use the version number `1.0.15562920261` will result in the following error when running `helm lint`:

```
[ERROR] Chart.yaml: version '1.0.15562920261' is not a valid SemVer
```

Or when tested directly with the `semver` package produces the following error:

```
Error parsing version segment: strconv.ParseInt: parsing "15562920261": value out of range
```

The semver package has already merged a fix for this issue (https://github.com/Masterminds/semver/pull/61). I've recompiled helm locally and can confirm it fixes the issue for me.

Would it be possible to have this fix released in a future version of helm?

**Comment by bacongobbler** [comment]
If it's just a matter of bumping Masterminds/semver to a newer release, I don't see why not! Do you feel like contributing a fix to bump that dependency?
