### ISSUE TITLE
Best practices on preventing running helm on a wrong cluster

### ISSUE THREAD

**Issue by grdl** [helm/helm#5651]
Our environment consists of multiple clusters (dev, test, uat, prod). We install/upgrade our apps by switching kubectl context to the correct cluster and running helm with specific values file, eg: 
`helm upgrade -f values-uat.yaml .`

It is possible however to have your kubectl context set to eg. "prod" cluster and still apply the "uat" values with `-f values-uat.yaml` which breaks the production environment and sometimes isn't easy to revert.

Are there any best practices that could prevent this? Something that will check if you're in the "right" k8s context before running helm install/upgrade?

**Comment by hickeyma** [comment]
There is an [enhancement feature](https://github.com/helm/helm/issues/4195) open about better means for switching clusters.  In the meantime, [helmfile](https://github.com/roboll/helmfile) might be worth checking out.

**Comment by cbeav** [comment]
> which breaks the production environment and sometimes isn't easy to revert.

I've had the same problem. Seems like the updated config values get stuck and subsequent revisions continue to use the erroneous `secrets` that `helm` is holding onto. How have you gone about fixing this in the past?

**Comment by hickeyma** [comment]
Closing out as feedback given in https://github.com/helm/helm/issues/5651#issuecomment-487540740 and feature #4195 open.
