### ISSUE TITLE
Helm scaffold chart template errors

### ISSUE THREAD

**Issue by hickeyma** [helm/helm#5659]
An OOTB scaffold chart (`helm create`) has templating errors as follows:

```console
$ helm install mychart
Error: YAML parse error on mychart/templates/deployment.yaml: error converting YAML to JSON: yaml: line 8: mapping values are not allowed in this context

$ helm lint mychart/
==> Linting mychart/
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/deployment.yaml: unable to parse YAML
	error converting YAML to JSON: yaml: line 8: mapping values are not allowed in this context
[ERROR] templates/service.yaml: unable to parse YAML
	error converting YAML to JSON: yaml: line 8: mapping values are not allowed in this context
[ERROR] templates/tests/test-connection.yaml: unable to parse YAML
	error converting YAML to JSON: yaml: line 8: mapping values are not allowed in this context

Error: 1 chart(s) linted, 1 chart(s) failed
```

Output of `helm version`:
From master

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by mattfarina** [comment]
Another way you can validate this is by running...

```sh
$ helm create foo
$ helm link ./foo
```

This will produce the errors as well.

**Comment by mattfarina** [comment]
I wonder if this was my fault when I merged #5373.

**Comment by hickeyma** [comment]
The issue is caused by the following label in scaffold chart helper function:
```
{{- if .Chart.AppVersion -}}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end -}}
```

The minus sign in the `if` and `end` delimiters (`}}`) was resulting in the label appending onto the label before it and the next label appended onto this label, all on the one line.

A template including the label helper definitions would thus render as follows:
```
labels:
    app.kubernetes.io/name: mychart
    helm.sh/chart: mychart-0.1.0
    app.kubernetes.io/instance: wobbling-camelapp.kubernetes.io/version: "1.0"app.kubernetes.io/managed-by: Tiller
```

A workaround until the fix lands, is to update <chart>/templates/_helpers.tpl as follows, before deploying:
```{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}```

**Comment by mattfarina** [comment]
@hickeyma nice work getting on this so fast.
