### ISSUE TITLE
`helm template --output-dir x --name release` renders to colliding path

### ISSUE THREAD

**Issue by nickatsegment** [helm/helm#5664]
Output of `helm version`: `Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}`

Output of `kubectl version`: N/A

For example, say I want to render two releases of nginx, mine1 and mine2:
```
% helm template -n mine1 --output-dir out docs/examples/nginx
wrote out/nginx/templates/pre-install-secret.yaml
wrote out/nginx/templates/configmap.yaml
wrote out/nginx/templates/service.yaml
wrote out/nginx/templates/service-test.yaml
wrote out/nginx/templates/deployment.yaml
wrote out/nginx/templates/post-install-job.yaml
% helm template -n mine2 --output-dir out docs/examples/nginx
wrote out/nginx/templates/pre-install-secret.yaml
wrote out/nginx/templates/configmap.yaml
wrote out/nginx/templates/service.yaml
wrote out/nginx/templates/service-test.yaml
wrote out/nginx/templates/deployment.yaml
wrote out/nginx/templates/post-install-job.yaml
```
The second invocation clobbers the first. I would have expected `out/nginx/templates` to include the release name to avoid such a collision.

**Comment by nickatsegment** [comment]
https://github.com/helm/helm/compare/master...nickatsegment:template-include-release-name fixes the issue, but in a backwards-incompatible way.

```
% bin/helm template -n mine1 --output-dir out docs/examples/nginx
wrote out/mine1/nginx/templates/pre-install-secret.yaml
wrote out/mine1/nginx/templates/configmap.yaml
wrote out/mine1/nginx/templates/service.yaml
wrote out/mine1/nginx/templates/service-test.yaml
wrote out/mine1/nginx/templates/deployment.yaml
wrote out/mine1/nginx/templates/post-install-job.yaml
```

**Comment by hickeyma** [comment]
@nickatsegment Thanks for raising this.

At the moment the output works as expected, using the chart name as the directory after the output root. As you have mentioned, if we change this to use the release name then it would be backward incompatible.

cc @mattfarina @bacongobbler @adamreese what do you think?

**Comment by nickatsegment** [comment]
I wouldn't complain except there's no way to avoid the chart name suffix. I could do 
```
name=mine1
helm template -n $name --output-dir out/$name docs/examples/nginx
```

But that ends up in `out/mine1/nginx/templates`. (The `templates` thing is weird too; not important though.)

**Comment by hickeyma** [comment]
@nickatsegment We discussed this at the weekly dev call yesterday. As the change directly would break backward compatibility, then we would be against this. However, if you added a flag something like `--release-name` then that would be ok. 

If you are interested, do you want to push a PR for review?

**Comment by hickeyma** [comment]
Ping @nickatsegment, are you still interested in doing a PR for this?

**Comment by nickatsegment** [comment]
@hickeyma not really, no. Definitely not any time soon.

**Comment by hickeyma** [comment]
Not a bother @nickatsegment. 

I will try and push a pr when I get a chance.
