### ISSUE TITLE
helm removes "environment" key when using Azure AD backed authentication

### ISSUE THREAD

**Issue by lauriku** [helm/helm#5665]
Output of `helm version`: `2.13.1`

Output of `kubectl version`: `1.14.0`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Self-hosted

We use an Azure AD backed authentication with our Kubernetes clusters. In my `kubeconfig`, I have the following block:

```yaml
users:
- name: azure-ad
  user:
    auth-provider:
      config:
        access-token: ....
        apiserver-id: ....
        client-id: ....
        environment: AzurePublicCloud
        expires-in: "3600"
        expires-on: "1556718695"
        refresh-token: ....
        tenant-id: ....
      name: azure
```

Now, whenever I run a helm command, helm parses and manipulates the config, to refresh the authentication token I assume, which should be fine. However, after running any helm command before a kubectl command, like:

```bash
$ kubectl -n mynamespace get pod mypod
NAME                                                   READY   STATUS    RESTARTS   AGE
mypod                                                  1/1     Running   0          9m46s
$ helm --tiller-namespace=mynamespace history myrelease
REVISION    UPDATED                     STATUS      CHART                       DESCRIPTION
1           Wed May  1 14:14:17 2019    SUPERSEDED  chart-0.0.1                 Install complete
2           Wed May  1 14:22:26 2019    DEPLOYED    chart-0.1.0                 Upgrade complete
$ kubectl get pods
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code <code> to authenticate.
```

The following has happened to kubeconfig:

```diff
--- /Users/lauriku/.kube/config-before-helm-command	2019-05-01 15:26:41.000000000 +0200
+++ /Users/lauriku/.kube/config	2019-05-01 15:26:47.000000000 +0200
@@ -158,7 +158,6 @@
         access-token: ....
         apiserver-id: ...
         client-id: ...
-        environment: AzurePublicCloud
         expires-in: "3600"
         expires-on: "1556720667"
         refresh-token: ....
```

so the key `environment` gets removed by helm, which will cause `kubectl` to prompt for re-authentication:

```bash
$ kubectl get pods                                                                                    I
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code <code> to authenticate.
```

If I manually add the key `environment: AzurePublicCloud` key back to the kubeconfig, `kubectl` will report having a valid session again.

**Comment by hickeyma** [comment]
AFIK, Helm does not write to KubeConfig.

/cc @adamreese @bacongobbler @michelleN would you have any Azure insight on this?

**Comment by cirazuretest** [comment]
I can confirm that helm ( v2.13.1 ) does write to  and change kubeconfig file, and have observed it removing the offending line multiple times.  
chmod 444 kubeconfig hangs helm as well ( my attempt at blocking the string removal attempt ).

Current work-around for my team is to "downgrade" kubectl to 1.13 which also does not require that line for azure auth provider.

**Comment by lauriku** [comment]
Yeah, as far as I understand `environment` was added with client-go 1.14, in this commit https://github.com/kubernetes/client-go/commit/ba28f5cc8eb9738a322628953273802da189e165#diff-ccba71f00b34f4ba0c9297d2f8e5d808

and helm 2.13.1 uses client-go 1.13.1 https://github.com/helm/helm/blob/v2.13.1/glide.yaml#L56

So maybe the "solution" is to always use versions of kubectl and helm with matching client-go library versions?

**Comment by bacongobbler** [comment]
Using a version of kubectl that Helm is compiled against would be the right solution going forward. 1.14 support was merged in https://github.com/helm/helm/pull/5511 so the canary releases should work with the `environment` key. Please test the canary release and see if that works for you.

**Comment by lauriku** [comment]
Tested with the latest canary release (2019-04-30T14:14:09.318Z) , and can confirm, it doesn't remove the `environment` key anymore :)

**Comment by bacongobbler** [comment]
Closing as resolved in master.
