### ISSUE TITLE
Occasionally failing to update env variables

### ISSUE THREAD

**Issue by cazter** [helm/helm#5667]
Output of `helm version`: v2.9.1

Output of `kubectl version`: v1.11.8-gke.6

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  GKE

Helm regularly fails to update existing environmental variables parameters to K8S StatefulSet.

Pipeline grabs different versions of the values files then I have it running the following to merge and upgrade:`helm upgrade mystatefulset-name --kube-context gke_cluster --version 0.4.0 --namespace prod --reuse-values -f /home/mystatefulset/env/prod/values.yaml -f /home/mystatefulset/env/prod/values2.yaml -f .values.yaml path/pod --force --debug --install --wait --timeout 300`

The above works about as often as it fails. When it fails I have to through and manually update env variables.

Are there any known issues with helm + statefulsets + frequently changing env variables?

**Comment by mattfarina** [comment]
@cazter There aren't any _known_ issues with statefulsets. If I understand what you're saying, sometimes the env variables are updated and other times they are not. Is that right?

Is there anything you can share from the debug logs?

The `--reuse-values` flag causes the values from the previous release to be used. The values files passed in via `-f` will override those. Are all the values you need in the two files being passed in via `-f`? That is, are they overriding everything in the existing values. If so, would it make sense to drop `--reuse-values`? If you do, does the issue persist?

Any information you could provide would help us get to the bottom of this. Thanks.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
