### ISSUE TITLE
Can Verification Method be Overridden?

### ISSUE THREAD

**Issue by gsexton** [helm/helm#5670]
Is it possible to supply a plugin that would change the behavior of the provenance file verification? IOW, if I want to sign charts using PKI certificates, could I write my own plugin that would be invoked when helm install --verify is invoked?

I see that I can add my own commands using plugins. For example:

helm do-my-signature-method xxx

but I was wondering about having a plugin installed that would change the behavior.

**Comment by mattfarina** [comment]
@gsexton Thanks for asking about this. The docs for the provenance file specifically call out a [PGP signature](https://helm.sh/docs/developing_charts/#the-provenance-file). A plugin can be used to generate that signature (e.g. [here's an example](https://github.com/technosophos/helm-gpg)).

We've not really talked about PKI certs. For Helm v3, which will be able to store charts in container registries, we have talked about switching to TUF/Notary to use the same method as images.

I'm curious what you think about the TUF/Notary proposed change and for more details on your request for PKI. Specifically the motivations and use case.

**Comment by bacongobbler** [comment]
related plugin: https://github.com/technosophos/helm-gpg

**Comment by radu-matei** [comment]
Hi, @mattfarina!
Regarding the TUF/Notary approach - is there a proposal / document we could have a look at?

Thanks!

**Comment by mattfarina** [comment]
@radu-matei There isn't. We will be talking about the whole container registry thing in more detail soon. It had escaped me that the hash for same container image can be different in different repos. So, signing with notary is only good for an image in a particular repository. This complicates things and we need to dig deeper into it.

**Comment by radu-matei** [comment]
I think a particular registry should generate the same digest for the same content, even if in different repos.

Different registries could generate different digests. 
(That being said, I think registries want to standardize this - I'm looking for this particular conversation, and if I find it I'll post it here - @bacongobbler might also know about this.)

**Comment by radu-matei** [comment]
FYI - I've been playing around with this idea of using TUF - https://github.com/helm/helm/pull/6282

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
