### ISSUE TITLE
Helm del --purge randomly misses a release 

### ISSUE THREAD

**Issue by imriss** [helm/helm#5673]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-12-06T01:33:57Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-eks-d69f1b", GitCommit:"d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7", GitTreeState:"clean", BuildDate:"2019-02-28T20:26:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
`EKS`

What happened (randomly, not all time):
```
$ helm del --purge ncp-cc; sleep 5; helm del --purge ncp-cc; kubectl delete ns ncp; helm install --name ncp-cc --namespace ncp ncp-cc; 
Error: release: "ncp-cc" not found
Error: release: "ncp-cc" not found
Error: a release named ncp-cc already exists.
Run: helm ls --all ncp-cc; to check the status of the release
Or run: helm del --purge ncp-cc; to delete it
```

What was expected (for those random cases):
To do not face the `a release named ncp-cc already exists` error message. 

Note: This happens regardless of the actual release name.

**Comment by bacongobbler** [comment]
Can you check tiller's logs and see if anything was shown there?

**Comment by imriss** [comment]
@bacongobbler , please see below:

```
[storage] 2019/05/05 12:58:48 getting release history for "ncp-cc"
[tiller] 2019/05/05 12:58:48 uninstall: Release not loaded: ncp-cc
[storage] 2019/05/05 12:58:54 getting release history for "ncp-cc"
[tiller] 2019/05/05 12:58:54 uninstall: Release not loaded: ncp-cc
[tiller] 2019/05/05 12:59:00 hooks complete for pre-install ncp-cc
[tiller] 2019/05/05 12:59:00 deleting pre-install hook init-job-ncp for release ncp-cc due to "hook-succeeded" policy
[storage] 2019/05/05 12:59:00 getting release history for "ncp-cc"
[storage] 2019/05/05 12:59:00 creating release "ncp-cc.v1"
[tiller] 2019/05/05 12:59:00 warning: Release "ncp-cc" failed: secrets "docker-hub-secret" is forbidden: unable to create new content in namespace ncp because it is being terminated
[storage] 2019/05/05 12:59:00 updating release "ncp-cc.v1"
[tiller] 2019/05/05 12:59:00 failed install perform step: release ncp-cc failed: secrets "docker-hub-secret" is forbidden: unable to create new content in namespace ncp because it is being terminated
[tiller] 2019/05/05 12:59:40 preparing install for ncp-cc
[storage] 2019/05/05 12:59:40 getting release history for "ncp-cc"
[tiller] 2019/05/05 12:59:40 failed install prepare step: a release named ncp-cc already exists.
Run: helm ls --all ncp-cc; to check the status of the release
Or run: helm del --purge ncp-cc; to delete it
```

**Comment by imriss** [comment]
It seems that this happens when I try to delete the release before it becomes `DEPLOYED`:
```
NAME            REVISION        UPDATED                         STATUS          CHART                           APP VERSION     NAMESPACE   
ncp-cc          1               Mon May  6 08:46:12 2019        PENDING_INSTALL ncp-cc-12.6.6                   1.0             ncp   
```

**Comment by mattfarina** [comment]
I wonder if this is a race condition. When `kubectl delete ns ncp` is called it might not happen immediately. When `helm install --name ncp-cc --namespace ncp ncp-cc` it may be that the delete is not complete so the following error happens:

> warning: Release "ncp-cc" failed: secrets "docker-hub-secret" is forbidden: unable to create new content in namespace ncp because it is being terminated

`kubectl` returns from the delete operation for a namespace before it's complete

**Comment by imriss** [comment]
Thanks @mattfarina , It seems that there are two race conditions:
1. Helm del before the having the release is actually versioned. I am using the following to repeat the delete request till the release is removed:
`ncp_cc_is_there=$(helm list --all | grep -i 'ncp-cc' | wc -l); echo $ncp_cc_is_there; while [ $ncp_cc_is_there -gt 0 ]; do time_seconds=$((5)); while [ $time_seconds -gt 0 ]; do echo -ne "$time_seconds\033[K\r"; sleep 1; : $((time_seconds--)); done; helm del --purge ncp-cc; sleep 10; done; `
2. Start of deployment before the namespace has been fully removed. I am now waiting to the namespace is removed before the re-deployment:
`kubectl delete ns ncp; ncp_ns_there=$(kubectl get ns | grep ncp | awk '{print $1}' | wc -l); echo ${ncp_ns_there}; while [ $ncp_ns_there -ge 1 ]; do time_seconds=$((5)); while [ $time_seconds -gt 0 ]; do echo -ne "$time_seconds\033[K\r"; sleep 1; : $((time_seconds--)); done; ncp_ns_there=$(kubectl get ns | grep ncp | awk '{print $1}' | wc -l); echo ${ncp_ns_there}; done; `

**Comment by mattfarina** [comment]
@imriss over in the chart-testing project we had to handle deleting the namespace, too. You can see the code to delete a namespace at https://github.com/helm/chart-testing/blob/f53c402ee2762c21d0580e16ebd7a4ddf505e968/pkg/tool/kubectl.go#L26-L52

**Comment by imriss** [comment]
@mattfarina thanks. the chart is under development, and I need to quickly redeploy it after every small change.

**Comment by mattfarina** [comment]
@imriss For what it's worth, we do that with the chart-testing toolchain. It creates a new namespace for each run at random. It's safe to run them in parallel that way. Dunno if that would help.
