### ISSUE TITLE
 it's very necessary to be able to execute the hook resources of current version release when you roll back

### ISSUE THREAD

**Issue by ZhuMingang** [helm/helm#5674]
Output of `helm version`: 2.8

Output of `kubectl version`: 1.9

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  HCS

So far, all hook types can only execute hook resources of target version release , but not the hook resources of current version. If you want to perform additional actions when rolls back release, you must require that the hook resource be included in the old version release. In actual production environment, you can't predict the additional actions that need to be performed when you roll back later, and you can't pre-embedded hook resources into the release of the old version, so it's very necessary to be able to execute the hook resources of current version release when you roll back.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
