### ISSUE TITLE
feat: Global `helmignore` file

### ISSUE THREAD

**Issue by igor-karpukhin** [helm/helm#5675]
`helm` tries to process vim temporarily files (`*.swp`, `*.swo`) when running `helm lint`: 
```
[ERROR] templates/: parse error in "istio/charts/kiali/templates/.ingress.yaml.swp": template: istio/charts/kiali/templates/.ingress.yaml.swp:2: unexpected {{end}}
```

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.13.0",
GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.0",
GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-19T22:12:47Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.5", GitCommit:"51dd616cdd25d6ee22c83a858773b607328a18ec", GitTreeState:"clean", BuildDate:"2019-01-16T18:14:49Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by mattfarina** [comment]
I'm guessing you do not have a `.helmignore` file alongside your `Chart.yaml` file with `*.swp` and others ignored.

If you use the `helm create` command to produce an example chart it will generate an example `.helmignore` file alongside the others. This has the values needed to skip the vim files.

The default `.helmignore` file has the following content:

```
# Patterns to ignore when building packages.
# This supports shell glob matching, relative path matching, and
# negation (prefixed with !). Only one pattern per line.
.DS_Store
# Common VCS dirs
.git/
.gitignore
.bzr/
.bzrignore
.hg/
.hgignore
.svn/
# Common backup files
*.swp
*.bak
*.tmp
*~
# Various IDEs
.project
.idea/
*.tmproj
.vscode/
```

Can you try adding this file to your chart and trying again.

**Comment by igor-karpukhin** [comment]
Hey @mattfarina, thanks a lot for your response. Does helm support global `.helmignore` file? Like global `.gitignore` for `git`.

**Comment by ian-howell** [comment]
This is kind of a cool idea though. Could a PR to add a  global `$HELM_HOME/helmignore` be considered?

**Comment by mattfarina** [comment]
> This is kind of a cool idea though. Could a PR to add a global $HELM_HOME/helmignore be considered?

I would guess so. I have not thought about it before.

**Comment by igor-karpukhin** [comment]
That would be really handy. Especially if you have lots of sub-charts each in its own subdirectory. Would be easier to just create one global `.helmignore` file

**Comment by technosophos** [comment]
Re-titled this to reflect the current state.

**Comment by bridgetkromhout** [comment]
A global `.helmignore` file could be interesting! Closing this issue as inactive, but if anyone wants to propose it via the [Helm Improvement Proposal](https://github.com/helm/community/blob/master/hips/hip-0001.md) process, please do.
