### ISSUE TITLE
Helm seems to not inject env properties to all containers in a pod

### ISSUE THREAD

**Issue by smiklosovic** [helm/helm#5687]
Output of `helm version`:
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

my own in 3 VMs on RHEL

The issue is that I have this in my values.yaml

    env:
      - name: MY_POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: MY_POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: MY_POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace

then in template:

    [root@master cassandra]# cat templates/cassandra.yaml 
    apiVersion: stable.instaclustr.com/v1
    kind: CassandraDataCenter
    metadata:
      name: {{ template "cassandra.fullname" . }}
      labels:
        app: {{ template "cassandra.name" . }}
        chart: {{ template "cassandra.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    {{- if .Values.labels }}
    {{ toYaml .Values.labels | indent 4 }}
    {{- end }}
    spec:
      replicas: {{ .Values.replicaCount }}
      sidecarImage: "{{ .Values.image.sidecarRepository }}:{{ .Values.image.sidecarTag }}"
      cassandraImage: "{{ .Values.image.cassandraRepository }}:{{ .Values.image.cassandraTag }}"
      imagePullPolicy: {{ .Values.imagePullPolicy }}
      {{- if  .Values.imagePullSecret }}
      imagePullSecret: {{ .Values.imagePullSecret }}
      {{- else }}
      imagePullSecret: ""
      {{- end }}
      resources:
    {{ toYaml .Values.resources | indent 4 }}
      dataVolumeClaim:
    {{ toYaml .Values.dataVolumeClaim | indent 4 }}
    {{- if .Values.env }}
      env:
    {{ toYaml .Values.env | indent 4 }}
    {{- end }}
    {{- if .Values.restoreFromBackup }}
      restoreFromBackup: {{ .Values.restoreFromBackup }}
    {{- end }}
    {{- if .Values.userConfigMapVolumeSource }}
      userConfigMapVolumeSource:
    {{ toYaml .Values.userConfigMapVolumeSource | indent 4 }}
    {{- end }}
    {{- if .Values.userSecretVolumeSource }}
      userSecretVolumeSource:
    {{ toYaml .Values.userSecretVolumeSource | indent 4 }}
    {{- end }}
      prometheusSupport: {{ .Values.prometheusEnabled }}
      privilegedSupported: {{ .Values.privilegedSupported }}

So I create a pod with two containers in it and in one container these properties are there but in the other one, they are not.

    [root@master ~]# sidecar-shell 
    root@cassandra-cassandra-0:/# env
    HOSTNAME=cassandra-cassandra-0
    KUBERNETES_PORT_443_TCP_PROTO=tcp
    KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
    MY_POD_NAMESPACE=default   <--- these are only in one container but not in the other?
    MY_POD_NAME=cassandra-cassandra-0 <---
    KUBERNETES_PORT=tcp://10.96.0.1:443
    PWD=/
    HOME=/root
    KUBERNETES_SERVICE_PORT_HTTPS=443
    KUBERNETES_PORT_443_TCP_PORT=443
    KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443
    TERM=xterm
    MY_POD_IP=10.244.3.7 <----
    SHLVL=1
    KUBERNETES_SERVICE_PORT=443
    PATH== /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin
    KUBERNETES_SERVICE_HOST=10.96.0.1
    _=/usr/bin/env
    root@cassandra-cassandra-0:/# exit
    exit
    [root@master ~]# cassandra-shell 
    root@cassandra-cassandra-0:/# env
    HOSTNAME=cassandra-cassandra-0
    KUBERNETES_PORT_443_TCP_PROTO=tcp
    KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
    KUBERNETES_PORT=tcp://10.96.0.1:443
    PWD=/
    HOME=/root
    KUBERNETES_SERVICE_PORT_HTTPS=443
    KUBERNETES_PORT_443_TCP_PORT=443
    KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443
    TERM=xterm
    SHLVL=1
    KUBERNETES_SERVICE_PORT=443
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    KUBERNETES_SERVICE_HOST=10.96.0.1
    _=/usr/bin/env

`kubectl describe statefulsets` also show that env properties are set only for one container.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
