### ISSUE TITLE
Helm Installation Failure 

### ISSUE THREAD

**Issue by sunidhi27** [helm/helm#5688]
Output of `helm version`:

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by sunidhi27** [comment]
I installed Helm as per documentation in gihub, in a kubernetes cluster.
wget -cp https://storage.googleapis.com/kubernetes-helm/helm-v2.13.1-linux-amd64.tar.gz
tar -zxvf helm-v2.13.1-linux-amd64.tar.gz
mv linux-amd64/helm /usr/local/bin/helm

But still I am not able to initialize helm - 
helm init 
bash: helm: command not found

Is it the right way to install ? Why is it showing this error ?

**Comment by hickeyma** [comment]
Can you check if the helm binary exists in the `/usr/local/bin` directory? Try running : `ls -al /usr/local/bin/helm`. Check that it is executable.
If it is then check to see if `/usr/local/bin` is on your path? Try running `echo $PATH`.

**Comment by bhaktibhoj** [comment]
You can use following command if not able to find binary at /usr/local/bin/heml

`sudo chmod +x linux-amd64/helm && sudo mv linux-amd64/helm /usr/bin/helm`

**Comment by hickeyma** [comment]
@sunidhi27 Did you manage to get it to install?

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

**Comment by David-Kenkadze** [comment]
@hickeyma I couldn' install.  I think helm binary doesn't exists.
`cannot access '/usr/local/bin/helm': No such file or directory`

**Comment by Ziyauddinshah** [comment]
> You can use following command if not able to find binary at /usr/local/bin/heml
> 
> `sudo chmod +x linux-amd64/helm && sudo mv linux-amd64/helm /usr/bin/helm`

@bhaktibhoj  thanks, It worked for me.

**Comment by harishchavan1993** [comment]
> Can you check if the helm binary exists in the `/usr/local/bin` directory? Try running : `ls -al /usr/local/bin/helm`. Check that it is executable. If it is then check to see if `/usr/local/bin` is on your path? Try running `echo $PATH`.

worked for me my path was /usr/local/sbin
