### ISSUE TITLE
Why is this not part of the documentation?

### ISSUE THREAD

**Issue by loxal** [helm/helm#5691]
Why is this is not part of the Helm documentation?!

> kubectl create serviceaccount --namespace kube-system tiller
> kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
> kubectl patch deploy --namespace kube-system tiller-deploy -p '{"spec":{"template":{"spec":{"serviceAccount":"tiller"}}}}'

**Comment by bacongobbler** [comment]
Please see https://helm.sh/docs/using_helm/#example-service-account-with-cluster-admin-role. Thanks!
