### ISSUE TITLE
Helm upgrade could not pick up the latest image when use the same image name/tag

### ISSUE THREAD

**Issue by zhucebuliaolongchuan** [helm/helm#5696]
Output of `helm version`:
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.9", GitCommit:"16236ce91790d4c75b79f6ce96841db1c843e7d2", GitTreeState:"clean", BuildDate:"2019-03-25T06:40:24Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.9", GitCommit:"16236ce91790d4c75b79f6ce96841db1c843e7d2", GitTreeState:"clean", BuildDate:"2019-03-25T06:30:48Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS

Problem:
When I try to perform an update to the docker image and run helm upgrade, it seems like the helm upgrade job won't be able to pick up the latest image if the name/tag of docker image remains the same.
I have no idea whether this problem is a potential bug or a design problem. But in my opinion, it is normal to use a stable image tag while the program is under developing/testing and helm chart should be able to pick up the latest image instead of comparing the previous name and then not picking up the latest image if the name of it remains the same.

**Comment by mattfarina** [comment]
This is more a Kubernetes thing and a convention but you can set it to always pull. Along with specifying the container you can set the `imagePullPolicy`. `IfNotPresent` will pull from a local cache if it is there. `Always` will always check for changes. You can read more about it at https://kubernetes.io/docs/concepts/containers/images/#updating-images.

When images use tags that have versions people expect them to not change. A change to the image would mean a new version release. This enables a cluster to use caching for image, too. If tags are used, such as `stable` that move you will need to check for updates.

The chart you are using likely defaults to `IfNotPresent`. We would need to know more about the chart to tell you how to switch it to `Always`. Is the chart source public somewhere?

**Comment by zhucebuliaolongchuan** [comment]
@mattfarina Thanks for the follow-up! I thought about that again after submitting the issue and also think it should be more a Kubernetes thing. The chart is not public and created by our team and I already found out the problem. We normally set the imagePullPolicy to Always before but it seems like we don't set that parameter this time. Thanks again.

**Comment by schollii** [comment]
I understand that Kubernetes treats the image tag as first class, rather than the image SHA which it resolves at pod creation time. 

However it is a bit strange to me that if I do `helm install` and "dev" tag of my pod is resolved to SHA 12345, and then I create a new docker image with SHA 67890 and retag that one as "dev", and finally I do `helm upgrade`, helm does not do anything because it only checks the tag not the SHA, so it thinks nothing has changed. It seems like helm should check the image ID and compare it to what it is now, and do the right thing to force kubernetes to update it. 

Helm already does something similar for other use cases, such as 3-way merge of manifests, and force/replace existing resources.

**Comment by DominicRoyStang** [comment]
Could this issue get reopened?
I'd love to get an answer to why it doesn't work as described in @schollii's suggestion.

**Comment by kuc** [comment]
Possible workaround:
```
spec:
  template:
    metadata:
      labels:
        date: "{{ now | unixEpoch }}"
```

Add it to your `Deployment` or `StatefulSet` yaml

**Comment by murugan-techie** [comment]
Possible workaround:

`--recreate-pods` use this flag

**Comment by mcandre** [comment]
When Helm manages Deployment resources with containers featuring image pull policy `Always`, then it would behoove Helm to automatically execute a rolling restart.

**Comment by Rajendraladkat1919** [comment]
I can see one workaround that everytime when we build docker image we can the tag image with some incremental tag.
like rc-0.0.1,rc-0.0.2,rc-0.0.3 wise so when we specify inside deployment.yaml `imagePullPolicy` `always` everytime it will pull new version if docker image.

**Comment by code-is-art** [comment]
This should not be treated as a question but an issue/bug. Helm should take into account the Sha as well as the tag to determine if an image is new.

**Comment by Rajendraladkat1919** [comment]
@code-is-art I am agree with you.

**Comment by TomasTokaMrazek** [comment]
Since the issue is still active and apparently a problem for people (myself included), can it be reopened or marked as duplicate and linked to another relevant issue?

**Comment by SadanandGowda** [comment]
> Possible workaround:
> 
> ```
> spec:
>   template:
>     metadata:
>       labels:
>         date: "{{ now | unixEpoch }}"
> ```
> 
> Add it to your `Deployment` or `StatefulSet` yaml

Hi, this workaround is not allowed for already deployed applications, since it is a change in spec template, any other workaround that would force helm upgrade.

Thanks.

**Comment by GuyYakobov** [comment]
@SadanandGowda from where did you understand thatspec.template cannot be changed?  Arent changes to the labels allowed as long as those who match to the selecotr matchlabels wont be changed?
