### ISSUE TITLE
helm install  Error: gzip: invalid header 

### ISSUE THREAD

**Issue by bharnaya** [helm/helm#5697]
I have created helm package ( my-app-1.0.0.tgz  1264 size)
i added package to repo  using helm add repo command.
When i am trying to install it using repository the above package file size is increased to 10144 bytes , also file is in HTML format.

helm install sample/my-app --dry-run --debug
[debug] Created tunnel using local port: '33513'
[debug] SERVER: "127.0.0.1:33513"
[debug] Original chart version: ""
[debug] Fetched sample/my-app to /home/blwdev/.helm/cache/archive/my-app-0.0.1.tgz
[debug] CHART PATH: /home/blwdev/.helm/cache/archive/my-app-0.0.1.tgz

Error: gzip: invalid header

Please help to resolve this issue.

file my-app-0.0.1.tgz: HTML document, UTF-8 Unicode text, with very long lines

**Comment by mattfarina** [comment]
@bharnaya `helm repo add` adds repositories to helm. It does not add charts to repositories. Anyone can run a repository and adding charts to repositories is different for each one.

My guess is that the HTML page is a 404 file not found rather than the chart.

You can read more about [`helm repo add` here](https://helm.sh/docs/helm/#helm-repo-add).

If you share more about what you're trying to do we may be able to help.

**Comment by bharnaya** [comment]
I have folder called my-app in github . my-app folder  contains Chart.yaml README.md  templates  values.yaml files . I need to create helm package(chart) .Add this chart to repository .
And install this chart from repository.
Please send me the steps to do it  Or Share me the document if you have any ?

**Comment by bacongobbler** [comment]
The docs on [hosting chart repositories](https://helm.sh/docs/developing_charts/#hosting-chart-repositories) should help you get going. Let us know if you have any questions.

**Comment by bharnaya** [comment]
Hi ,
  Please let me know how to create helm repository ?

Thanks and Regards
Bharathi Nayak

**Comment by bacongobbler** [comment]
@bharnaya, please see the link posted above. That document shows you multiple different solutions to create a helm repository. Some are commercial (such as [Azure Container Registry](https://azure.microsoft.com/en-ca/updates/azure-container-registry-helm-repositories-public-preview/)), some are open source (such as [chartmuseum](https://github.com/helm/chartmuseum)).

**Comment by bharnaya** [comment]
Hi ,

 I have created  chart . Chart size is 4735 bytes .File name is 
my-app-1.0.0.tgz  .If would be great if you can help me to resolve this ?

 file my-app-1.0.0.tgz 
 my-app-1.0.0.tgz: gzip compressed data, extra field, has comment.


After helm fetch  file size is getting changed and  file format is changed 
.
I used below command to fetch

helm fetch 
https://github.ibmgcloud.net/blw-msa/helm_repo/blob/master/my-app/my-app-0.0.1.tgz?raw=true

 my-app-1.0.0.tgz file size is 10144 bytes
 file my-app-1.0.0.tgz 
my-app-1.0.0.tgz: HTML document, UTF-8 Unicode text, with very long lines

Do you know why file format is getting changed

Because of this i am not able to install package from  repo


helm install sample/my-app --dry-run --debug
[debug] Created tunnel using local port: '40475'

[debug] SERVER: "127.0.0.1:40475"

[debug] Original chart version: ""
[debug] Fetched sample/my-app to 
/home/blwdev/.helm/cache/archive/my-app-0.0.1.tgz

[debug] CHART PATH: /home/blwdev/.helm/cache/archive/my-app-0.0.1.tgz

Error: gzip: invalid header


Thanks and Regards
Bharathi Nayak
BL-WNeu, Deutsche Telecom
IBM, Bangalore, India
Telephone : 9180 41954886
Mobile: 919980973334

**Comment by bharnaya** [comment]
Hi,

     Please let me know why helm fetch is behaving like this ?

Thanks and Regards
Bharathi Nayak
BL-WNeu, Deutsche Telecom
IBM, Bangalore, India
Telephone : 9180 41954886
Mobile: 919980973334




From:   Bharathi Nayak/India/IBM
To:     helm/helm 
<reply@reply.github.com>
Cc:     helm/helm <helm@noreply.github.com>, Mention 
<mention@noreply.github.com>
Date:   05/10/2019 05:51 PM
Subject:        Re: [helm/helm] helm install  Error: gzip: invalid header 
(#5697)



Hi ,

 I have created  chart . Chart size is 4735 bytes .File name is 
my-app-1.0.0.tgz  .If would be great if you can help me to resolve this ?

 file my-app-1.0.0.tgz 
 my-app-1.0.0.tgz: gzip compressed data, extra field, has comment.


After helm fetch  file size is getting changed and  file format is changed 
.
I used below command to fetch

helm fetch 
https://github.ibmgcloud.net/blw-msa/helm_repo/blob/master/my-app/my-app-0.0.1.tgz?raw=true

 my-app-1.0.0.tgz file size is 10144 bytes
 file my-app-1.0.0.tgz 
my-app-1.0.0.tgz: HTML document, UTF-8 Unicode text, with very long lines

Do you know why file format is getting changed

Because of this i am not able to install package from  repo


helm install sample/my-app --dry-run --debug
[debug] Created tunnel using local port: '40475'

[debug] SERVER: "127.0.0.1:40475"

[debug] Original chart version: ""
[debug] Fetched sample/my-app to 
/home/blwdev/.helm/cache/archive/my-app-0.0.1.tgz

[debug] CHART PATH: /home/blwdev/.helm/cache/archive/my-app-0.0.1.tgz

Error: gzip: invalid header


Thanks and Regards
Bharathi Nayak
BL-WNeu, Deutsche Telecom
IBM, Bangalore, India
Telephone : 9180 41954886
Mobile: 919980973334

**Comment by mattfarina** [comment]
@bharnaya Registries are used for distributing charts. You can install from a directory on the local file system. `helm install path/to/dir`. Do you need to use a registry or will a directory work as well?

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
