### ISSUE TITLE
raw format of file

### ISSUE THREAD

**Issue by bharnaya** [helm/helm#5710]
How do i find raw path of git file ?

**Comment by hickeyma** [comment]
@bharnaya Could you provide more details on what you are trying to do?

**Comment by bharnaya** [comment]
My index.yaml file raw path is showing with token values ? Why 
https://raw.github.ibmgcloud.net/blw-msa/helm_repo/master/my-app/index.yaml?token=AAACHtAvO2oFWHzIJCrkBki9wSV6_9Dvks5c3o4mwA%3D%3D

I am trying to create package and add to  repository .
If you have any simple straight forward document please let me know . 

Thanks and Regards
Bharathi Nayak
BL-WNeu, Deutsche Telecom
IBM, Bangalore, India
Telephone : 9180 41954886
Mobile: 919980973334

**Comment by SlickNik** [comment]
Hi @bharnaya -- some good documentation for Helm Chart Repositories can be found at https://github.com/helm/helm/blob/master/docs/chart_repository.md. This includes a section on the format of the index.yaml file that you may find helpful. Thanks!

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
