### ISSUE TITLE
Helm does not follow uninstall order. 

### ISSUE THREAD

**Issue by HarishHothi** [helm/helm#5721]
**Output of `helm version`:**
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```
**Output of `kubectl version`:**
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Cloud Provider/Platform (AKS, GKE, Minikube etc.):** OPENSTACK

**PROBLEM:** 
Helm does not follow the order while deleting the chart. In My test case, helm first delete the storage class and then go for crd deletion.  but it should be reverse as per
```https://github.com/helm/helm/blob/v2.13.1/pkg/tiller/kind_sorter.go```
```[storage] 2019/04/12 09:12:41 updating release "elastic.v1"
[kube] 2019/04/12 09:12:41 Starting delete for "curator" CronJob
[kube] 2019/04/12 09:12:41 Starting delete for "elastic-cinder-class" StorageClass
[kube] 2019/04/12 09:12:41 Starting delete for "es-custom-config" ConfigMap
[kube] 2019/04/12 09:12:42 Starting delete for "curator-config" ConfigMap
[kube] 2019/04/12 09:12:42 Starting delete for "es-auth" Secret
[kube] 2019/04/12 09:12:42 Starting delete for "es-elastic" Elasticsearch```

ElasticSearch is a CRD.
Any idea what is going wrong??


Ideally First CRD should get deleted then Storage class.

**Comment by SlickNik** [comment]
Hi @HarishHothi. Thanks for submitting this. 

This does seem strange on a first look. Based on the [docs](https://github.com/helm/helm/blob/master/docs/charts.md#operational-aspects-of-using-dependencies) as well as the source, resources for dependent charts should be aggregated into a single set, sorted and then created/deleted based on a defined [sort order](https://github.com/helm/helm/blob/master/pkg/tiller/kind_sorter.go#L26). 

Can you share more information about the chart for which you are seeing this behavior, or better yet, would it be possible to get a minimum working repro of this? 

Thanks!

**Comment by HarishHothi** [comment]
Hi @SlickNik, I am seeing this while I am installing elastic Search using [kubedb Operator.](https://kubedb.com/) Overall flow can be describe as below.

1. Deploy [KubeDB operator](https://kubedb.com/docs/0.12.0/setup/install/)
2. Once Kubedb Installed, it will create ElasticSearch CRDs.
3.  We have custom helm chart which does [CRO creation](https://kubedb.com/docs/0.12.0/guides/elasticsearch/clustering/topology/#create-elasticsearch-with-dedicated-node) of CRD type elasticSearch along with storage class, secrets, configmap and cron job to purge elastic data.
4. Installation works Perfectly and Elastic Search cluster will spinup as per the CRO.
5. While helm purge, I am seeing my storage class will get deleted first then my CRO deletion happens.
6. Kubedb operator has validation hooks and is not able to delete the CRO since storage class is deleted first.
Please let me know any other info is required.

**Comment by HarishHothi** [comment]
Hi Guys any update on this?

**Comment by bacongobbler** [comment]
closing as inactive/stale. If you have more information to share, please feel free to update the ticket.
