### ISSUE TITLE
Tillerless RBAC

### ISSUE THREAD

**Issue by gsemet** [helm/helm#5722]
Hi

I am using Tiller in production now for our internal webservices, but I want to move to a tillerless infra, as [recommended](https://github.com/helm/helm/issues/4852) now in the doc, and rely on our RBAC infra.
The goal is to execute tiller locally from our Gitlab CI runner, and use kube config to connect to the API. This would mimick as best as possible the future behavior with helm v3.

Would like to know if this is something you would like to advocate to prepare to helm v3.

The RBAC part is not met with my solution, but at least we can use a token stored in a private variable in the project to identy the caller.

Here is what I have:
- CI provides the following information: authentication authority `ca.pem`, service account token as `$TILLER_TOKEN`.
- `export KUBECONFIG=${KUBECONFIG:-/etc/deploy/config}`
- `ca.pem` is created inside `/etc/deploy/ca.pem`, and the config is set with:

```bash
kubectl config set-cluster     sa-cluster --server=$CLUSTER_URL --certificate-authority=/etc/deploy/ca.pem
kubectl config set-credentials sa-user    --token=${TILLER_TOKEN}
kubectl config set-context     sa-context --user=sa-user --cluster sa-cluster --namespace ${TARGET_NAMESPACE}
kubectl config use-context     sa-context
```

- Tiller is run locally:

```bash
export HELM_HOST=localhost:44134
tiller --storage=secret --history-max 20 --logtostderr &
```
- one could use tillerless plugin if wanted
- helm is then initialized in client only mode:
```bash
helm init \
      --client-only \
      --debug \
      --history-max 20 \
      --stable-repo-url http://ourinternal.chart/repository

helm repo update

helm dep build Chart/

helm upgrade \
      --install \
      --force \
      ... \
     myappname \
      Chart/
```

Seems pretty cool, do not require to generate self-authenticated certificates, and rely on the service account token like the good old tiller-helm. For me this look like the same among of security, no more, no less, but less complex to setup.

Do you think this might help for preparing migration to helm 3?

**Comment by rimusz** [comment]
hey there, we at Jfrog use `local` tiller for all our kubernetes clusters deployments and happy with the results we have.
If you really want to prep for helm v3 you could set `tiller` namespace to the same as your app gets released, that will mimic v3 setup, but that needs redeployment of your app.

**Comment by gsemet** [comment]
yes that's what we do :)

**Comment by rimusz** [comment]
so you all good there then :)

**Comment by bridgetkromhout** [comment]
Hi, @gsemet - it sounds like you were well on the path to a successful Helm 3 upgrade. Please take a look at https://helm.sh/blog/migrate-from-helm-v2-to-helm-v3/ and let us know if you have further need of support. Thanks!
