### ISSUE TITLE
Get client and server semver only

### ISSUE THREAD

**Issue by eroji** [helm/helm#5731]
This is a quick question. It seems like you can run `helm version --server/--client --short` to get the version of server or client component. It also seems to support a `--template` flag, but there is no documentation of how to construct the string. I assume there is a way to get just the semver value using this flag but can someone provide an example?

**Comment by SlickNik** [comment]
Hi @eroji :

Thanks for your question. The `--template` flag simply accepts a golang `text/template` that is then used to format the output. Using this, you could get just the server/client semvers by running something like the following:

```
$ helm version --template "{{ .Client.SemVer }}"
v2.13.1

$ helm version --template "{{ .Server.SemVer }}"
v2.13.1

```

Hope this helps.

**Comment by SlickNik** [comment]
Closing this issue. Feel free to re-open if things are still unclear. Thanks!
