### ISSUE TITLE
Add lint feature to detect charts that will no longer work in v3

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#5733]
The idea is to add a lint feature (maybe even to v2) to detect elements in charts that will no longer work. For example `.Release.Revision` was removed in https://github.com/helm/helm/commit/aa859e3f88291c94220d26e9d1127c1557c2af98. It would be nice to provide some direction, possibly at the other end of a link, for these as well.

**Comment by waveywaves** [comment]
I would like to work on this. 
Can you assign this to me ?

cc @hickeyma  @mattfarina @bacongobbler

**Comment by johngmyers** [comment]
Removing `.Release.Revision` is definitely going to break us. We have a Helm pre-install,pre-upgrade hook provision a credential for the revision and store it in a secret with `.Release.Revision` in its name. We then have other templates refer to that secret.

With templates still being able to query the time, it looks like the purpose of [aa859e3](https://github.com/helm/helm/commit/aa859e3f88291c94220d26e9d1127c1557c2af98) has not been achieved.

**Comment by bacongobbler** [comment]
Thanks for bringing that to our attention, @johngmyers. @jlegrone had similar concerns with fetching database backups during a rollback in relation to a particular release. `.Release.Revision` is being added back in #6688.

**Comment by thomastaylor312** [comment]
Closed by #6687
