### ISSUE TITLE
Helm template with --namespace doesn't inject metadata: namesace into o

### ISSUE THREAD

**Issue by paulgmiller** [helm/helm#5734]
When provided a --namespace option, helm template doesn't set metadata.namespace in appropriate objects where as helm upgrade/install would. 
If the chart has uses the namespace variable it will populate that but many charts dont.

This is a pain if we want to work around tiller till helm 3.0 comes out. 
Example call. 

C:\Users\pmiller\AppData\Local\Temp\helm-2.13.0.exe template C:\Users\pmiller\AppData\Local\Temp\overprovisioning-1.1.0.tgz --name overprovisioning--shared-overprovisioning --namespace shared-overprovisioning --output-dir C:\Users\pmiller\AppData\Local\Temp\tmpax1q_25j -f C:\Users\pmiller\AppData\Local\Temp\tmp08sw25oj\values

Output of `helm version`:
2.13.0
Output of `kubectl version`:
<note used> 
Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by paulgmiller** [comment]
Looks like helm never adds it but the kube-client's unstructured builder adds it by assing it to to NamespaceParam in unstrucutured builder 
https://github.com/helm/helm/search?q=NamespaceParam&unscoped_q=NamespaceParam
Still looking at how the builder shoves it in.

**Comment by bacongobbler** [comment]
The namespace is injected as part of the runtime. The templates themselves don't need to know what namespace it'll be deployed in ahead of time.

You can test this out with `helm template | kubectl apply --namespace foo`

**Comment by paulgmiller** [comment]
Yep that's pretty much what i needed. Would it be useful for me to add this to the helm of helm template's --namespace arg or am I the only wierdo that didn't know kubectl would sneak in --namespace for you.
