### ISSUE TITLE
The helm template is interpreting something I want copied verbatim

### ISSUE THREAD

**Issue by mgrand-wawa** [helm/helm#5740]
Output of `helm version`: 2.13.1

I have a template where I want to use a variable to insert a YAML/JSON array at the value of a field:
```
spec:
  targets: {{.Values.targetSelectors}}
```
I am setting the value in a parent chart's `values.yaml` file like this:
```
targetSelectors: [{"name":"httpbin"}]
```
When the variable is replaced with its value I want it to look like this:
```
spec:
  targets: [{"name":"httpbin"}]
```
What it is generating instead is this invalid YAML:
```
spec:
  targets: [map[name:httpbin]]
```
How can I get the result that I want?

**Comment by bacongobbler** [comment]
You probably want the `toJson` function. Does that work?

e.g.

```
spec:
  targets: {{ toJson .Values.targetSelectors}}
```

**Comment by mgrand-wawa** [comment]
That was exactly what I needed. Than you!
