### ISSUE TITLE
Validation of existence of parameters

### ISSUE THREAD

**Issue by sarsonj** [helm/helm#5744]
Hi,

i tried to look in docs but didn't found it... It happens to me few times, that I have typo in parameters in the template. Helm now just silently enter empty string.  Is there a way to make alll parameters required (and show error) or show at least warning, that some parameter is missing?

I know about required function, but it doesn't to have sense to write to each parameter required. I prefer to have this as default.

Thanks,

Jindrich

**Comment by jdolitsky** [comment]
@sarsonj values file validation is something that has been brought to Helm 3. Please take a look at this: https://v3.helm.sh/docs/developing_charts/#schema-files

Does this give you what you're looking for?

**Comment by sarsonj** [comment]
Hi,

this seems to me as overkill - I just want to change the default - currently when variable is not defined, empty string is filled. I want to change it (by parameter /  char.yaml option) to display error.

In doc is written: https://helm.sh/docs/developing_charts/#using-the-required-function

> Go provides a way for setting template options to control behavior when a map is indexed with a key that’s not present in the map. This is typically set with template.Options(“missingkey=option”), where option can be default, zero, or error. 

All I want is to be able to change the template.Options(“missingkey=error”)

**Comment by jdolitsky** [comment]
@sarsonj so youre essentially looking for a flag such as `--all-required` which would be the equivalent of adding `required` prefix/function to everything in the template?

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

**Comment by felixhummel** [comment]
Please re-open this! Why should there be **any** `{{ .Values.foo }}` that has no value set for `foo` ever?

Real-world use-case:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fooservice
spec:
  hosts:
  - fooservice.{{ .Values.domain }}
  gateways:
  - fooservice
  http:
  - route:
    - destination:
        host: fooservice
```

Now imagine `domain` not being set. We get no error whatsoever, but obviously a broken configuration.

To make things optional we already have the [default function](https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-default-function).

Ideally, you could specify `all-required` in `$HELM_CONFIG_HOME`...

**Comment by bacongobbler** [comment]
In helm 3, you can now validate your values against a JSONSchema. Refer to the documentation for more info.

**Comment by felixhummel** [comment]
As @sarsonj put it perfectly:

> All I want is to be able to change the template.Options(“missingkey=error”)
