### ISSUE TITLE
helm init hangs after upgrade to 2.14

### ISSUE THREAD

**Issue by kwaazaar** [helm/helm#5745]
"helm init --wait --service-account tiller" now waits a long time, ending with the message "Error: tiller was not found. polling deadline exceeded". 
This was not the case with helm 2.13.1, which I ran just yesterday. The Tiller pod is running fine, with its logs not showing issues.

Output of `helm version`:
Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:41:57Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS (1.12.7)

**Comment by kwaazaar** [comment]
--force-upgrade resolves it: the tiller pod is updated and it works again.

**Comment by hickeyma** [comment]
@kwaazaar It might be that the Tiller pod was unresponsive at the time of initialization and it had a timeout because of it.  It is hard to tell when no errors seem to be available.

 If you have any other details that might help shed light on the issue then that would help to understand the issue.

**Comment by hickeyma** [comment]
Ping @kwaazaar

**Comment by kwaazaar** [comment]
I already fixed it by using the force-upgrade flag. Only then was the tiller pod updated. So no more details here. And since nobody else backed up my story 😬 feel free to close this one
