### ISSUE TITLE
project board for available roles and needs in the helm project

### ISSUE THREAD

**Issue by michelleN** [helm/helm#5747]
People have been asking how to help and get involved. We could have a github project board for “roles” that we need. i.e. “someone to triage helm 2 issues”, “someone to triage helm 3 issues”, someone to help with release management”, “someone to help us figure out a  release planning process”, etc. Kubernetes has a [role board](https://discuss.kubernetes.io/c/contributors/role-board) for this.

**Comment by jdolitsky** [comment]
This sounds good to me.. @adamreese ?

**Comment by hickeyma** [comment]
@michelleN sounds like a good idea.  One thing,  would you add features for v3 release under v3 feature/delivery role?

**Comment by bridgetkromhout** [comment]
Hi, @michelleN! I see that https://github.com/helm/community#how-can-i-help gives some ideas of where people can get started helping. It looks like over the last year we haven't moved forward with a more formal process like the k/k one. Do you (or does anyone) think we should add more to the community doc or do anything else before we resolve this issue? Thanks.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
