### ISSUE TITLE
Extend downloader plugin for values files

### ISSUE THREAD

**Issue by AssafKatz3** [helm/helm#5771]
Hi,
Currently HELM support  [downloader plugins](https://github.com/helm/helm/blob/master/docs/plugins.md#downloader-plugins) only for charts. We have layered values, which are coming from various sources (local, GIT, nexus, etc.), so we need similar functionality for values files. This feature will allow us to use whatever source that we want without adding additional prolog command to download the file (only modify the location).

I suggest to allow plugin.yaml configuration like:
```
valuesDownloaders:
- command: "bin/mydownloader"
  protocols:
  - "myprotocol"
  - "myprotocols"

```
Then command like:
`helm install release chart.tgz -f myprotocol://uri 
`
will passthrough bin/mydownloader and use it standard output as values file.

**Comment by jdolitsky** [comment]
@AssafKatz3 we're still working out some details on values files for Helm 3, but this is likely not something we will add in current Helm (2.14+)

In the meantime you may wish to write a plugin that either wraps "helm install" or fetches values file from your desired source prior to the install

**Comment by AssafKatz3** [comment]
@jdolitsky Not good for us but understandable :disappointed:

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

**Comment by AssafKatz3** [comment]
@bacongobbler I changed a job since I had opened this issue, but it only added more use cases for it (downloading of values.yaml from S3 for example). Moreever, meanwhile more wrappers where created. Therefore this request is still valid :-)

**Comment by bacongobbler** [comment]
Are you planning to implement this? It’s been a year since this ticket was opened.

**Comment by AssafKatz3** [comment]
I don't have the skill to write this code.
