### ISSUE TITLE
Incorrect Helm Chart Generated

### ISSUE THREAD

**Issue by gsexton** [helm/helm#5774]
Output of `helm version`: 

Client: 2.11.0
Server: 2.13.0

Output of `kubectl version`:
N/A

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
N/A

I've run across an issue in helm chart packaging where an incorrect chart is generated. Here are the steps to reproduce it:

Create a chart A where chart B is a dependency. 
Package chart A
Copy chart A to a new directory and unpackage it.
Create an updated version of chart B and publish it to a remote chart-museum.
Change to the unpacked directory for chart A. Update the Chart.yaml version number.
Update the requirements.yaml file to explicitly identify the new version of chart B.
Execute the command "helm dep update".
When you look into the charts directory, you will see B/ and B-X.X.X.tgz.
Repackage chart A. Execute the command: "helm package A".
A new chart with updated version number will be created.

Now, examine the new helm chart:

tar -tzvf A-x.x.x.tgz | sort

what you will see is that the directory charts/B/ is present TWICE, along with all the files.

The behavior when installing this chart can be unpredictable.

I "think" the correct solution should be that if a chart entry is present in requirements.yaml, and it's present in exploded form in the charts directory, then that directory should be removed as part of helm dependency build.

**Comment by jdolitsky** [comment]
I've verified this but hesitant to label it a bug.

Fetching a tarball from remote, unpacking it, and making modifications to it is not the same as making changes in your git source tree. IMO this is a non-standard workflow. Once a chart version is in a chart repo, it should be treated as if it were immutable.

@gsexton make sense?

**Comment by gsexton** [comment]
@jdolitsky I would mostly agree with you. Our workflow is a little odd. Essentially what I'm doing is a CI/CD Pipeline, and when a child chart is built, building the parent chart and deploying it. 

I'm a little bugged about the tar file having the directory contents twice. That's really unexpected, and I think there should be some sort of behavior other than silently ignoring the issue. I've coded my work-around, but it seems like a bug...

**Comment by jdolitsky** [comment]
@gsexton I understand. I would recommend then to release the child charts as tarballs to your chartmuseum, and keep no record of them in the charts/ dir of the parent chart. Simply reference them in requirements.yaml/requirements.lock and run a "dep update" on a clean source tree prior to installation via CI/CD system

**Comment by jdolitsky** [comment]
Unless of course they are stored in same git repo, in which case you may not need to use chart repo at all

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
