### ISSUE TITLE
Helm 3 alpha1: chart list replaces `_` with `:`

### ISSUE THREAD

**Issue by willholley** [helm/helm#5775]
Output of `helm version`:
`version.BuildInfo{Version:"v3.0.0-alpha.1", GitCommit:"b9a54967f838723fe241172a6b94d18caf8bcdca", GitTreeState:"clean"}`

When testing the new `chart push/pull` feature, I noticed that `helm chart list` will render incorrect ref values:

```
helm chart pull us.icr.io/my_registry/mychart:latest
latest: Pulling from us.icr.io/my_registry/mychart
Name: mychart
Version: 1.0.8
Meta: sha256:32e5dd94fcba61d0bc36664fc0f9e908e39552507f7694c21f7a34f19eb82572
Content: sha256:5282241bf2a576f84ab38c681cf325ad6f03d35100f76bfb31be119d86f9d675
Status: Chart is up to date for us.icr.io/my_registry/mychart:latest

helm3 chart list
REF                                       	NAME  	VERSION	DIGEST 	SIZE   	CREATED
us.icr.io/my:registry/mychart:latest	mychart	1.0.8  	5282241	3.1 KiB	26 minutes
```

Note the underscore in the registry path has been replaced with a `:`. It seems like all other `helm chart` commands recognise the original ref, so I think this is just a rendering issue with `chart list`.

**Comment by bacongobbler** [comment]
@jdolitsky can you confirm if this has been fixed in more recent versions?

**Comment by jdolitsky** [comment]
@bacongobbler yes, this substitution has been removed! closing
