### ISSUE TITLE
Helm3 install timeout leaves chart in not installed state but pods running. helm2 was FAILED

### ISSUE THREAD

**Issue by planetf1** [helm/helm#5778]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.0-alpha.1", GitCommit:"b9a54967f838723fe241172a6b94d18caf8bcdca", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1+IKS", GitCommit:"7212ba91727da63ce9cfb2b5eba7f988f0f125d0", GitTreeState:"clean", BuildDate:"2019-05-09T14:28:29Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
IBM Cloud (IKS)

I took a working helm (2) chart and tried helm 3 alpha.

There is currently an issue in the chart whereby sometimes initialization jobs do not complete within the default timeout ( https://github.com/odpi/egeria/issues/826 ) . The EFFECT of this is that charts are reported in FAILED state

However with helm3 helm list shows no charts deployed, whilst the pods are still present, meaning that helm is not correctly reporting what is deployed any more ie:
```
➜  charts git:(helm-v3) helm install egeria vdc -f ~/cloud.yaml                                                                      git:(helm-v3|)
Error: timed out waiting for the condition
➜  charts git:(helm-v3) helm list                                                                                                    git:(helm-v3|)
NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART
➜  charts git:(helm-v3) kubectl get pods                                                                         git:(helm-v3|)
NAME                                                 READY   STATUS      RESTARTS   AGE
vdc-1558515147-atlas-59bb87cf88-fpczc                1/1     Running     1          5h12m
vdc-1558515147-cp-kafka-0                            2/2     Running     3          5h12m
vdc-1558515147-cp-kafka-1                            2/2     Running     0          5h10m
```
(etc)

**Comment by planetf1** [comment]
In comparison with helm 2:
```
➜  charts git:(helm-v3) helm version                                                                                                 git:(helm-v3|)
Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
➜  charts git:(helm-v3) helm install vdc -f ~/cloud.yaml                                                                             git:(helm-v3|)
Error: timed out waiting for the condition
➜  charts git:(helm-v3) helm list                                                                                                    git:(helm-v3|)
NAME          	REVISION	UPDATED                 	STATUS	CHART     	APP VERSION	NAMESPACE
ideal-chipmunk	1       	Wed May 22 16:46:21 2019	FAILED	vdc-0.1.11	           	egeria
```

**Comment by planetf1** [comment]
Note that this issue is to highlight the difference of behaviour, and the impact in terms of resource cleanup. This is not about the chart itself, which needs the issue causing the timeout addressing.

**Comment by bacongobbler** [comment]
This might've been fixed in future refactors. I can see that Helm [should create the release](https://github.com/helm/helm/blob/40572311abd71ba2e2ec0433751ffff312ff9564/pkg/action/install.go#L258-L265) before [invoking `--wait`](https://github.com/helm/helm/blob/40572311abd71ba2e2ec0433751ffff312ff9564/pkg/action/install.go#L281-L286), so this state should not occur, and the release should be marked as FAILED similar to Helm 2.

Can you try and confirm if this is still an issue with helm 3.0.0-beta.4?

**Comment by thomastaylor312** [comment]
@bacongobbler beat me to it. I tried testing and couldn't get this to happen. Please let us know if it is still an issue

**Comment by planetf1** [comment]
will do & reopen if it occurs. Thanks for the update
