### ISSUE TITLE
Error messages don't allow proper debugging

### ISSUE THREAD

**Issue by mattdarwin** [helm/helm#5786]
If I install a chart without supplying some values, I get the following:

`Error: render error in "mychart.yaml": template: mychart.yaml:2:10: executing "mychart.yaml" at <eq .Values.global.en...>: error calling eq: invalid type for comparison`

The value itself which is missing has had its name abbreviated to `.Values.global.en...`, so I can't rectify the problem by specifying it.

This makes it very hard to solve this kind of problem.

Please output the full name of the parameter in this scenario.  Consider also not outputting the chart name 3 times.

Output of `helm version`:
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-26T00:05:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by jdolitsky** [comment]
@mattdarwin thank you. to clarify - you want the error message to contain the full var names correct?

What do you mean by "Consider also not outputting the chart name 3 times" ?

**Comment by mattdarwin** [comment]
thanks for the quick response on this.  Correct, the full var names are essential for debugging.

The chart name "mychart.yaml" appears 3 times in the error message I pasted above- there may be some redundancy here.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
