### ISSUE TITLE
The sha256 checksums of the v2.14.0 release are not correctly documented

### ISSUE THREAD

**Issue by headcr4sh** [helm/helm#5787]
The sha256 checksums that are listed on the Github "Downloads" page are wrong.
Obviously, they have been copy-pasted from the 2.13.1 release... ;-)

* Helm/Tiller release: v2.14.0
* Platforms: all
* Link: https://github.com/helm/helm/releases/tag/v2.14.0

**Comment by jdolitsky** [comment]
cc @bacongobbler @hickeyma

**Comment by mattfarina** [comment]
@headcr4sh Thanks for catching this. It is now fixed.

I cross referenced the SHAs printed in CI (see https://circleci.com/gh/helm/helm/8280) with those we store to make sure they were the same.

**Comment by hickeyma** [comment]
@mattfarina thanks for clearing this up.
