### ISSUE TITLE
Post-deploy not working

### ISSUE THREAD

**Issue by viniciuscoelho** [helm/helm#5791]
Im trying to use the post-deploy, but it is not working.:
      containers:
      - name: {{  template "odoo.fullname" . }}
        image: {{  template "odoo.image" .  }}
        command: ["/bin/sh",  "-c ls > /odoo/1" ]

I get the error:
    Command:
      /bin/sh
      -c ls > /odoo/1
    State:          Terminated
      Reason:       Error
      Exit Code:    2

It seems to be a file not find issue... but I can run this command using kubectl....

**Comment by jdolitsky** [comment]
@PunkSp hi, can you elaborate a bit more on the issue?

**Comment by jdolitsky** [comment]
It could be just that the "-c" needs to be its own item: `command: ["/bin/sh", "-c",  "ls > /odoo/1" ]`

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
