### ISSUE TITLE
Upload helm chart as ConfigMap from another helm chart

### ISSUE THREAD

**Issue by krish7919** [helm/helm#5794]
Our current workflow is to deploy Helm charts from our CI regularly.
However, now we have a requirement to deploy charts dynamically over a period of time from a `Deployment` in k8s - let's call this `DynamicChartDeployer`.

But we would also want to be able to manage the dynamically deployed chart from our CI using helm.

I was planning to use the [helm.Client](https://github.com/helm/helm/blob/master/pkg/helm/client.go#L39) to instantiate a client from the Kubernetes cluster and ensure that Tiller installs the chart. This seems doable and will help me achieve my goal.

The problem I am confused about now is that `DynamicChartDeployer` in the cluster needs to have the chart available to deploy this chart.

And this would mean that, in the `DynamicChartDeployer` deployment Helm chart, I would need to pass the entire Helm chart as a parameter to the `DynamicChartDeployer` Helm chart.

How can I pass a Helm chart as a parameter to another Helm chart to load the entire chart as a ConfigMap in Helm?

Output of `helm version`:
`Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}`

Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-19T22:12:47Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"darwin/amd64"}`

**Comment by mcortinas** [comment]
+1

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

**Comment by krish7919** [comment]
Please reopen this :)

**Comment by bacongobbler** [comment]
@krish7919 can you please give an update on your current thoughts on this ticket? It's been several months since there's been any activity in this ticket, and since this was opened, Helm 3 has been released, and with that there's been a number of improvements to the SDK. Have you had the chance to look at the SDK documentation yet and found anything that answers your question?

https://pkg.go.dev/helm.sh/helm/v3

**Comment by bacongobbler** [comment]
Once again, closing this ticket due to inactivity.
