### ISSUE TITLE
shared dependencies, depending on a release (feature request)

### ISSUE THREAD

**Issue by mildred** [helm/helm#5798]
Some resources are meant to be running only once on a cluster, but many charts may be requiring them. Those includes for example cert-manager resources, issuers, ingress controllers, ...

Instead of manually installing those resources in releases before installing more applicative resources, it would be nice to be able to directly install an applicative chart, and have helm itself create the releases for the shared resources, unless it already exists.

**Comment by jdolitsky** [comment]
@mildred Could this be solved by chart dependencies? https://github.com/helm/helm/blob/master/docs/charts.md#chart-dependencies

**Comment by jdolitsky** [comment]
Or you mean multiple releases may be relying on something such as redis for example? and you dont want to install it twice? You may use something like Helmfile to install baseline services prior to your custom releases https://github.com/roboll/helmfile

**Comment by mildred** [comment]
I believe this is a bit different. Dependencies are meant to be 
instantiated each time they are mentioned, here, I am thinking of 
dependencies that are instanciated once for each release.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
