### ISSUE TITLE
Helm 3 uninstall --purge by default

### ISSUE THREAD

**Issue by arichardet** [helm/helm#5804]
With Helm 3, the decision was made to include `--purge` by default when running `helm uninstall`. I'm curious how the decision was made, and if this was the best option for the default.

**Comment by hickeyma** [comment]
Feedback from the Helm community suggested that people used `--purge` more often than not and people new to the helm were confused that `helm delete` did not remove the history as well. This was the main reason behind the decision and why we thought it was the best option. Refer to #5283 for more details.

**Comment by karuppiah7890** [comment]
Actually, now that I think of it, I have used --purge so many times and the
times I have not used, it was always because I forgot and then got an
"release already exists" error during next installation and had to rerun
delete command with --purge
