### ISSUE TITLE
Helm init tries to deploy tiller on AKS Windows node pool

### ISSUE THREAD

**Issue by patrikulus** [helm/helm#5807]
I'm using AKS with node pools, which is currently in preview. I have one Linux pool and one Windows pool. When I try to initialize helm and deploy tiller, it tries to pull tiller image (which is linux container image) and deploy it into Windows nodes. It fails of course. I'm aware that node pools is a preview feature, but maybe to avoid such situation init command should have node pool parameter, or maybe it should have Linux node selector in the inside?

Output of `helm version`:
Client - 2.14
Server- 2.14
Output of `kubectl version`: 
Client - 1.13.4
Server - 1.14.0
Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

**Comment by patrikulus** [comment]
Ok, there is such option: https://helm.sh/docs/install/#advanced-usage 
Sorry for confusion.

**Comment by kennetherland** [comment]
I'm having same issue, and the link in the solution does not lead to a solution
