### ISSUE TITLE
template for daemonset/statefulset

### ISSUE THREAD

**Issue by daixiang0** [helm/helm#5810]
Hi!

I found that `helm create` always use deployment, i do not find any docs about this limit, also help info say nothing about this.

Did i miss something?
Is there any way to create template for daemonset or statefulset or any else?

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

**Comment by hickeyma** [comment]
@daixiang0 `helm create` creates a simple scaffold chart. Its aim is to show a basic chart with resources that can be installed to demonstrate e2e capability. It is not designed to show all resource types. The chart is described in [docs](https://helm.sh/docs/chart_template_guide/#a-starter-chart).

Re daemonset/statefulset, maybe search for examples of charts with these resources. The [Helm chart repository](https://github.com/helm/charts) is a good starting point.

**Comment by daixiang0** [comment]
It should be better to comment this point in [doc](https://helm.sh/docs/chart_template_guide/#a-quick-glimpse-of-mychart-templates) i think.

**Comment by hickeyma** [comment]
@daixiang0 What point are you referring to?

**Comment by daixiang0** [comment]
comment the limit and main aim of `helm create` and where to learn how to write daemonset/statefulset .

**Comment by hickeyma** [comment]
@daixiang0 Thanks for the feedback. I agree that [helm create command description](https://helm.sh/docs/helm/#helm-create) could do with an update to describe the chart and manifests it creates. I will change this to a doc bug and good first issue to work on.

Re writing daemonset/statefulset, this is Kubernetes layer knowledge and reference docs as follows:
- https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/
- https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/

**Comment by daixiang0** [comment]
need i ask a pr?

**Comment by daixiang0** [comment]
@hickeyma hi, i asked a pr, please review it.

**Comment by hickeyma** [comment]
@daixiang0 Thanks for pushing the PR. In review.
