### ISSUE TITLE
Will re-created pod still on same node after Helm upgrade?

### ISSUE THREAD

**Issue by zhanglijingisme** [helm/helm#5816]
Hi, 
We are using Helm and want to know some details about Helm upgrade.

- During our "helm upgrade", pod will be re-created. We'd like to know if this re-created pod will still on same node, or it may be re-scheduled to other nodes?
- If it may be re-scheduled to other nodes, how should we do (during helm upgrade) to keep it on previous node?

Thanks in advance.

Output of `helm version`:
> Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
> Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

Output of `kubectl version`:
> Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:57:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Kubernetes Vanilla

**Comment by hickeyma** [comment]
The recreation of pods is handled by Kubernetes and not Helm.  Helm asks the Kuberentes API server to perform operation by giving it rendered manifest files from the chart.

From Kubernetes perspective, maybe take a look at [assigning pods to nodes](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/).

**Comment by hickeyma** [comment]
@zhanglijingisme Is there any further information that you need?

**Comment by zhanglijingisme** [comment]
@hickeyma Thanks for yoru help. There is no other question for me, and I'll close this.
