### ISSUE TITLE
How to pass custom yaml file to helm without mentioning its name

### ISSUE THREAD

**Issue by aman1989v** [helm/helm#5817]
I am new to helm chart. As part of the requirement I named my <i>values.yaml</i> to <i>customize.yaml</i> <br>
To tell helm engine that I am using custom yaml file, I used the below command.<br>
<code> helm install mychart -f customize.yaml </code>
<br>but now the question is how should I not pass the name of the yaml <i>(customize.yaml)</i> file as part of the command, so the command should be like this<br> 
<code> helm install mychart </code>
<br>and helm should know that it will get the values from <i>customize.yaml</i>
without explicitly mentioning it in the command. Is there a way to do this?

**Comment by hickeyma** [comment]
For this scenario, you would need to add the values to `values.yaml` and it is picked up automatically (this is your default). When you want to override these values  you would then define override file(s) like `customize.yaml` (or set from the install CLI).

Refer to [values section in docs](https://helm.sh/docs/chart_template_guide/#values-files) for more details.

**Comment by aman1989v** [comment]
Thanks @hickeyma 
Here in my scenario, I would like to make <code> customize.yaml </code> as my default. 
In other words I want to rename <code> values.yaml</code> to <code>customize.yaml</code>.
So that I need not to pass it through install CLI.
Please let me know if it is possible in helm.

**Comment by hickeyma** [comment]
Ibn short, it is not possible. Helm looks for `values.yaml` as the default values file. If you want to use another named file then you need to specify it with the `-f` option.

**Comment by hickeyma** [comment]
If you have any other questions then let us know. I would suggest using the  [Helm users slack channel](https://kubernetes.slack.com/messages/C0NH30761/)  as more convenient way to ask questions. 

Closing as question answered.

**Comment by bhaab01** [comment]
Cann't we enhance Chart.yaml to take name of the value file as input ?

**Comment by hickeyma** [comment]
You can already add new value file(s) and override the default values with `-f` option.  I am not sure of the advantage of being able to change the name of the default values file in this case.

**Comment by boris-fido** [comment]
this is limitation of the helm  ---> are this going to change somehow ?
