### ISSUE TITLE
Helm 3 Proposal: Replace `null` override with a flag

### ISSUE THREAD

**Issue by thomastaylor312** [helm/helm#5834]
When I was reviewing PR #5185 with @adamreese, we realized that the current behavior of using `null` to unset a value has some possible edge cases where you are deleting keys that are null even if you expect them to be there. A safer and more explicit way to do this would be to remove the current behavior and add an `--unset` flag.

This flag would use the same syntax as `--set` and would run against the final computed Values map. Each specified key would be removed before the values are applied to the manifest

**Comment by scottrigby** [comment]
The more I think about this idea the more I like it. This would need no extra explanation the way `null` does now.

PS for fun I've been looking at other general-purpose YAML (JSON/data etc) merge functionality projects. I think the ability to delete a key is important, but again I'm not sure the best way to define that in a generic way (`null` was the best signifier I found in the past, but you're right that omits the ability for a YAML key to have a literal `null` value).

For fun, linking other projects I was looking at, in case there's any value in cross-discussion:
- https://github.com/mikefarah/yq/issues/122#issuecomment-497454447
- https://github.com/imdario/mergo

**Comment by thomastaylor312** [comment]
@hickeyma I think this might be better classified as a feature with breaking changes. Things work right now, but the behavior could be better. Thoughts?

**Comment by bacongobbler** [comment]
I agree. I don't believe this is considered a bug.

I'm curious to hear how `--unset` would work. Is the presence of the key enough to consider it being removed? e.g. would `helm install stable/wordpress --unset ingress` unset all default ingress values provided in the chart?

In a similar vein, what would be the behaviour of `helm install --set foo.bar.car="star" --unset "foo"`? Does `--unset` take precedence here?

How are values unset in a values.yaml file? Would there be an equivalent `--unset-values` flag?

**Comment by bacongobbler** [comment]
Another point: how does this proposal plan to address backwards compatibility concerns here? As far as I can remember, Charts have been using `null` to unset a value since Helm 2.0.0. Making this change could break backwards compatibility with charts that relied on this behaviour.

**Comment by thomastaylor312** [comment]
I actually think it was added a little later, but I am not quite sure. I don't know how many published charts do this in their actual values files. It seems like the most common use case I have seen is people overriding with their _own_ values files or with `--set`. We should talk about this more in the dev call and put the summary of our conversation here.

As for the behavior, I think it would be as you explained. If you use `--unset ingress`, it will unset that whole tree of values. Precedence-wise, `--unset` would have the highest priority. Its purpose would be to unset from the final computed values map. So there is no need for an `--unset-values` flag. So to provide an example if I had this values file:

```yaml
foo: bar
baz:
  blah: bang
```
And if I used `--set baz.foo=again --unset baz`, the final map would be 

```yaml
foo: bar
```

Or if I did `--set baz.foo=again --unset baz.blah`, I would get

```yaml
foo: bar
baz:
  foo: again
```

**Comment by scottrigby** [comment]
Re backwards compatibility info: I just grepped the community charts (for case insensitive `: null` or `: ~`) and no files in stable or incubator this to overwrite a value from their own or another (for example, dependent) chart. The only uses of these are for initial default values, which aren't overwritten. 

I can't speak for people's custom charts or CI - in that case yes it would break backwards-compatibility. Or at least, the commands would be different. From what I can see, `--unset` would be functionally equivalent.

**Comment by thomastaylor312** [comment]
Oh, I also had another thought. We could support both methodologies, but make sure to print a huge warning if people are still using `null` with a deprecation date and add the `--unset` flag to do the same thing

**Comment by mattfarina** [comment]
Here's my concern with this. We could have a features that is only available at the command line and cannot be captured in stored configuration. That limits the ability to store everything in custom values files and just use those. For the times you would want this you would have to know to use a flag.

This limits consistent usage of the tool in automation scripts.

Not really sure what it would mean in practice.

**Comment by scottrigby** [comment]
@mattfarina here was the quick thought I mentioned at the end of the meeting. If someone needs to continue to unset a key without using the CLI - instead of saying you "can't do that", could an option be to include a Lua function to remove the key post-render?

**Comment by Nuru** [comment]
Helm has been allowing `null` to delete a key set as a default value since 2.6.0 in July of 2017. https://github.com/helm/helm/pull/2648

We need a way to delete keys set by default using a values file, not just CLI.

**Comment by thomastaylor312** [comment]
Given that we are past the breaking change phase of Helm 3 and the raised concerns about having functionality that is only available on the CLI, I am fine closing this
