### ISSUE TITLE
Sign all releases

### ISSUE THREAD

**Issue by pixie79** [helm/helm#5835]
It appears full releases do have their checksum files signed however, Alpha and RC releases do not.

Can these please also be signed as it would be good to be able to validate every release as good practice.

Thanks

Mark

**Comment by pixie79** [comment]
Hi,

It also appears that the SHA files are not correctly formatted as they should include the filename after the sha on the same line. If this does not happen then running "sha256sum -c" fails to validate the files which makes checking validity a much more lengthy step.

Thanks

Mark

**Comment by hickeyma** [comment]
Hey @mattfarina. What do you think?

**Comment by bacongobbler** [comment]
See https://github.com/helm/helm/issues/4968 for discussion related to `sha256sum -c`.

The process for signing releases has been manual at this time. Pre-release software such as alphas and RCs aren't intended to be distributed to production systems, so we've gone with the assumption that those releases do not need to be signed, saving us time during the testing process. I'm curious to hear why should there be a process in place for signing alpha and RC releases?

For what it's worth, we have discussed moving to an automated signing process for Helm 3 which would make this ask much simpler to accommodate.

**Comment by pixie79** [comment]
I can see the logic in that, but i prefer the option to follow the same process for all builds. Especially when testing out new dev builds i think it is just important to ensure these are valid and from a trusted source.
There are times when fixes require the use of a dev build for real work and the use of a dev label is less of an issue. But that in itself does not detract from ensuring the source is trusted.
Also i have been caught before where upstream binaries are been repackaged and pushed with no bump in version due to one issue or another, introducing issues downstream with no easy way to notice the difference.

:)

**Comment by bacongobbler** [comment]
Not planning to implement this for non-production software. Closing.
