### ISSUE TITLE
ingress.yaml

### ISSUE THREAD

**Issue by xytnba** [helm/helm#5837]
Output of `helm version`:v1.14.2

Output of `kubectl version`:v1.14.2

Cloud Provider/Platform (AKS, GKE, Minikube etc.): minikube

I installed k8s in my Vmware .Here is a error in helm . The templates has something wrong in default. 
```
annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
```
a "n" is additional in default

**Comment by hickeyma** [comment]
@xytnba Are you using Helm v1.x or is this a copy/paste error? If so, this is [Helm Classic](https://github.com/helm/helm-classic) and is no longer supported?

To get a better understanding of the issue, could you provide more information as follows:
What command are you running? What error is returned by the  command?

**Comment by xytnba** [comment]
I just run the code`helm create hello-helm`,and I found that it should be `indent` there ,not the `nindent` in /hello-helm/templates/ingress.yaml 。
you will find it after you create a default chart .
My helm version is v1.14.2,I think it's a Spelling mistakes in helm’s bottom code.  
Do you know where should I feedback？

**Comment by hickeyma** [comment]
You can get the version by running: `helm version`

**Comment by hickeyma** [comment]
Did `helm create` give an error or was it another Helm command that you ran? Can you provide the error message returned by the command?

**Comment by xytnba** [comment]
It discussed at #3854 ，I figured out .Thanks.

**Comment by hickeyma** [comment]
@xytnba `nident` is a valid function in Helm. Its a sprig function described as follows: "The nindent function is the same as the indent function, but prepends a new line to the beginning of the string."

**Comment by xytnba** [comment]
OK,I get it .THANKS A LOT~
