### ISSUE TITLE
 helm list --debug get a timeout issue

### ISSUE THREAD

**Issue by blackhair3000** [helm/helm#5843]
Error: Get https://10.96.0.1:443/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%!D(MISSING)TILLER: dial tcp 10.96.0.1:443: i/o timeout

my vmware master ip is 192.168.196.128 and I can ping the 10.96.0.1,but the https timeout .

I can't figure out what's the problem , could some body help me?

**Comment by karuppiah7890** [comment]
@blackhair3000 I tried to reproduce the issue. I have kubernetes running using minikube. To reproduce the issue, I stopped k8s and did this 

`$ helm --tiller-connection-timeout 1 --debug ls`

and got this error 

```
Error: Get https://192.168.99.101:8443/api/v1/namespaces/kube-system
/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: dial tcp 192.168.99.101:8443: i/o timeout
```

not exactly the same as your's but a time out issue. Can you give the output of `helm version` , `kubectl config view` and also `kubectl version` ? 

And I am confused about how the master ip is `192.168.196.128` but error has `10.96.0.1` in the request url

**Comment by blackhair3000** [comment]
yesterday, i have found that it was my calico.yaml  CALICO_IPV4POOL_CIDR part configured at a same network with my virtual machines that caused the problem.

so I changed the calico.yaml network part to "172.16.0.0/16" , than kubeadm init --pod-network-cidr 172.16.0.0/16 after the kubeadm reset. it's ok for me now.

there is a link Create a single-host Kubernetes cluster part about it:
https://docs.projectcalico.org/v3.7/getting-started/kubernetes/
