### ISSUE TITLE
Custom helm charts path

### ISSUE THREAD

**Issue by madonius** [helm/helm#5844]
In case the charts, listed as dependencies, are already present on the machine, a way to point helm to this directory would be helpful.
Currently, the only way to use those charts, is to symlink them to the corresponding subdirectory.
I would propose something similar to a environment variable `HELM_CHART_PATH`

**Comment by bacongobbler** [comment]
This is currently possible by specifying a file path in your requirements.yaml. You can specify them by using the following syntax:


```
dependencies:
  - name: foo
    repository: file://../../foo
```

**Comment by madonius** [comment]
The matter is that in that way pulling the dependency properly is not an option. The Environment varaible would allow for a temporary override

**Comment by sfudeus** [comment]
What we are trying to solve is this use-case: 
a) When developing a helm-chart with dependencies, sometimes it is necessary to change the chart and those it depends on (in the git repo structure where they are maintained), local references besides symlinks would be great there. 
b) When using a helm chart with dependencies during production application deployment, we'd like to pull the charts from the official location (helm dependencies build), which does not work, if there requirements.yaml does contain local references, which aren't optional. 
Does that shed some light in the idea?
