### ISSUE TITLE
can we define release name on values.yaml instead on command line ?

### ISSUE THREAD

**Issue by gabrielfsousa** [helm/helm#5846]
Output of `helm version`: 2.14
Output of `kubectl version`: 1.12.7
Cloud Provider/Platform (AKS, GKE, Minikube etc.): Azure

can we define release name on values.yaml instead on command line ?

**Comment by bacongobbler** [comment]
Hi! This is not possible today. Helm accepts a release name through `--name`, or it will auto-generate a name for you if not present.
