### ISSUE TITLE
helm 3: --namespace troubles

### ISSUE THREAD

**Issue by pniederlag** [helm/helm#5851]
Output of `helm version`:

`version.BuildInfo{Version:"v3.0.0-alpha.1", GitCommit:"b9a54967f838723fe241172a6b94d18caf8bcdca", GitTreeState:"clean"}`

Output of `kubectl version`:

`Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
`
Cloud Provider/Platform (AKS):

Whatever way I try, I can't get 'helm install' to add/set a namespace:

`helm install --namespace="akademie-typo3" foo .  
Error: the namespace from the provided object "akademie-typo3" does not match the namespace "default". You must pass '--namespace=akademie-typo3' to perform this operation.`

How am I supposed to set the namespace for deplloying the various kubernetes resources? 

Btw. I can see the namespace as I would expect it when running 'helm template'.

**Comment by bacongobbler** [comment]
See #5628.
