### ISSUE TITLE
Not working: Create configmap with data importing from json file

### ISSUE THREAD

**Issue by shiva075gowda** [helm/helm#5852]
I want to Create a sample configmap with data set from a json file.

**application.json**
[
 {
    "clientName": "sample",
    "protocol": "gmail",
    "Access": "public",
    "clientPolicy": {
                   "Action": ["allow_login"],
     }
  }
]

**templates/sample.yaml**
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-configmap
  Sample: {{ toJson (.Files.Get "application.json") }}

Helm install throwing the following error, unable to figure it out.
chart sample failed to install.
 error converting YAML to JSON: yaml: line 24: did not find expected key

I tried many ways modifying json file (Indentation/Removing List entry/Converting json to yaml), but dint work.

Please let me know how to proceed.

**Output of `helm version**`
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

**Output of `kubectl version**`
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Cloud Provider/Platform**: minikube

**Comment by shiva075gowda** [comment]
@bacongobbler , is it like json files can be imported using .Files extension ?

**Comment by bacongobbler** [comment]
Perhaps this may help: https://helm.sh/docs/chart_template_guide/#accessing-files-inside-templates

**Comment by shiva075gowda** [comment]
Thanks @bacongobbler . These links I already went through and some more issues are filed related to this. But I couldn't find anything useful pertaining to my usecase.
Though plain create configmap command works fine with given file input as json file.

**Comment by shiva075gowda** [comment]
Similar issues:
https://stackoverflow.com/questions/53429486/kubernetes-how-to-define-configmap-built-using-a-file-in-a-yaml
https://github.com/helm/helm/issues/2004

**Comment by shiva075gowda** [comment]
Myself resolved this issue. I was referring this configmap created from above files inside a kubernetes Job by mounting it.
During helm upgrade, if a Job with given name is already present, it was failing with above error which is not correct.
Before every upgrade or a fresh install, If I delete the Job if present, then it would succeed.
Dont no, what is the reason for this kind of behaviour, but it actually worked out for me.
Now, I have added helm hooks to my Job to run during every upgrade also.
