### ISSUE TITLE
Helm - tiller: intermitted communication error

### ISSUE THREAD

**Issue by tedescomicchidev** [helm/helm#5858]
Output of `helm version`:
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}

Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS

Issue:
We installed several Tiller(s) in different namespaces (one in the kube-system). At seemingly random times, running helm commands against those Tillers fail. When we check the Tiller node logs we find the following error (in this case we tried: helm ls –tiller-namespace gceo):

 

[storage] 2019/06/07 08:17:59 listing all releases with filter

[storage/driver] 2019/06/07 08:33:46 list: failed to list: Get https://azr02-k8s--azr02-rg-000-a6d0a7-f664afe5.hcp.westeurope.azmk8s.io:443/api/v1/namespaces/gceo/configmaps?labelSelector=OWNER%3DTILLER: unexpected EOF

This is happening for all Tillers in all namespaces (also kube-system) at really random times. In all cases it looks that Tiller is failing after some kind of 15’47” timeout. Running kubectl commands doesn’t seem to trigger this issue and also “curl”-ing that address never fails. Reinstalling Tiller doesn’t resolve this behavior. Also, in our local cluster this never happened.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
