### ISSUE TITLE
OCI: Not able to push chart to <insert registry>

### ISSUE THREAD

**Issue by karuppiah7890** [helm/helm#5861]
Output of `helm version`:
version.BuildInfo{Version:"v3.0.0-alpha.1", GitCommit:"b9a54967f838723fe241172a6b94d18caf8bcdca", GitTreeState:"clean"}

```
~ $ helm create dummy-chart
Creating dummy-chart

~ $ helm chart save dummy-chart registry.hub.docker.com/karuppiah7890/dummy-chart
Using default tag: latest
Name: dummy-chart
Version: 0.1.0
Meta: sha256:42603b382336019d658ec8c0c71c57be421dc49a471ce6c6b776d7834e54cbec
Content: sha256:2b41efbc14985cd820ef48a2e898ac839559f6b77fd2a49af29dd7d6c4c3004c
latest: saved

~ $ helm chart push registry.hub.docker.com/karuppiah7890/dummy-chart
Using default tag: latest
The push refers to repository [registry.hub.docker.com/karuppiah7890/dummy-chart]
Name: dummy-chart
Version: 0.1.0
Meta: sha256:42603b382336019d658ec8c0c71c57be421dc49a471ce6c6b776d7834e54cbec
Content: sha256:2b41efbc14985cd820ef48a2e898ac839559f6b77fd2a49af29dd7d6c4c3004c
Error: failed commit on ref "manifest-sha256:febab107d93e89faa3926f875441334358562220d47d48230346e9b51fd46500": un
expected status: 400 Bad Request
```

When I tried to debug, the response from Docker Hub said - 

```
{"errors":[{"code":"MANIFEST_INVALID","message":"manifest invalid","detail":{}}]}
```

and digging more, I saw that the manifest json looks like this - 

```
{
    "schemaVersion": 2,
    "config": {
        "mediaType": "application/vnd.oci.image.config.v1+json",
        "digest": "sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a",
        "size": 2
    },
    "layers": [
        {
            "mediaType": "application/vnd.cncf.helm.chart.meta.v1+json",
            "digest": "sha256:42603b382336019d658ec8c0c71c57be421dc49a471ce6c6b776d7834e54cbec",
            "size": 106,
            "annotations": {
                "org.opencontainers.image.title": "chart-meta.json"
            }
        },
        {
            "mediaType": "application/vnd.cncf.helm.chart.content.v1+tar",
            "digest": "sha256:2b41efbc14985cd820ef48a2e898ac839559f6b77fd2a49af29dd7d6c4c3004c",
            "size": 2268,
            "annotations": {
                "org.opencontainers.image.title": "chart-content.tgz",
                "sh.helm.chart.name": "dummy-chart",
                "sh.helm.chart.version": "0.1.0"
            }
        }
    ]
}
```

and layers struct looks like this - 

```
[{MediaType:application/vnd.cncf.helm.chart.meta.v1+json Digest:sha256:42603b382336019d658ec8c0c71c57be421dc49a471ce6c6b776d7834e54cbec Size:106 URLs:[] Annotations:map[org.opencontainers.image.title:chart-meta.json] Platform:<nil>} {MediaType:application/vnd.cncf.helm.chart.content.v1+tar Digest:sha256:2b41efbc14985cd820ef48a2e898ac839559f6b77fd2a49af29dd7d6c4c3004c Size:2268 URLs:[] Annotations:map[org.opencontainers.image.title:chart-content.tgz sh.helm.chart.name:dummy-chart sh.helm.chart.version:0.1.0] Platform:<nil>}]
```

And I tried the same by tagging the chart too, for example `registry.hub.docker.com/karuppiah7890/dummy-chart:v1.0.0` and I still couldn't push the chart.

Docker Hub API is OCI Spec compliant right? Am I missing something here?

**Comment by bacongobbler** [comment]
Most cloud providers whitelist certain media types. Usually that means they only support docker images. The only two that we know that work at this time with `helm chart push` are Azure Container Registry and vanilla docker/distribution, but we're working with the OCI to figure out how to get Helm's published media types to be whitelisted.

cc @jdolitsky

**Comment by karuppiah7890** [comment]
Ah. I did guess if media type might be an issue, but I saw people saying they could push (in a different issue) so excluded it. But yeah, the other issues showed example of pushing to azure.

I just tried with docker/distribution in local, it does work 😄

**Comment by karuppiah7890** [comment]
Should I close this issue? Or keep it open to track whitelisting of Helm's media types ?

**Comment by zioproto** [comment]
This works for me on GCR (Google Cloud Platform, Google Container Registry).

```
$ helm version
version.BuildInfo{Version:"v3.0.0-alpha.1", GitCommit:"b9a54967f838723fe241172a6b94d18caf8bcdca", GitTreeState:"clean"}
```
Here my steps:

```
helm package mychart
helm chart save mychart  gcr.io/my-gcp-project/mychart # creates metadata in local folder ~/.helm/registry/
gcloud auth configure-docker # needed only once, adds some data in ~/.docker/config.json
docker login gcr.io/my-gcp-project/mychart
helm chart push  gcr.io/my-gcp-project/mychart
```

**Comment by towolf** [comment]
@bacongobbler 

> The only two that we know that work at this time with helm chart push are Azure Container Registry and vanilla docker/distribution

Gitlab works too! I've successfully tried it, the only problem is the UI. 

I've opened this issues for that:
https://gitlab.com/gitlab-org/gitlab-ce/issues/65559

**Comment by JulienBreux** [comment]
@zioproto do you have the "exact" procedure?

Because it's a failed for me :(

![Screenshot_2019-09-10_at_11_45_55](https://user-images.githubusercontent.com/964330/64603871-55043a00-d3c1-11e9-944e-b25d593cf63e.png)

**Comment by JulienBreux** [comment]
Ok, I'm sorry, it's because GCP don't create the `appspot` bucket to store containers of this type.
✅

**Comment by liuliqiang** [comment]
In this comment time, neither docker.io or query.io can not use `helm char push` command.

**Comment by willejs** [comment]
> Most cloud providers whitelist certain media types. Usually that means they only support docker images. The only two that we know that work at this time with `helm chart push` are Azure Container Registry and vanilla docker/distribution, but we're working with the OCI to figure out how to get Helm's published media types to be whitelisted with other providers including Docker Hub.
> 
> cc @jdolitsky

@bacongobbler any update on this? Is there any workaround?

**Comment by bacongobbler** [comment]
Docker Hub is not currently supporting alternative content types at this time. Feel free to use one of the listed cloud providers that does support Helm’s content type at this time.

**Comment by guycla** [comment]
@zioproto I successfully reproduced you steps on my local MacOS, but when trying to run the same through gitlab-ci or on a fresh Ubuntu machine I'm not having any luck 😕
Any ideas why?
btw, I was also able to use chart tags when pushing (without having to manually go to GCP and add a tag)

**Comment by percenuage** [comment]
Hi @zioproto, I tried to reproduce your steps and I have this error (like @guycla)

**Comment by jdolitsky** [comment]
"failed to fetch oauth token" seems like the same error as https://github.com/helm/helm/issues/6214

Please see also this issue on oras, the library supporting oci push/pull: https://github.com/deislabs/oras/issues/157

**Comment by percenuage** [comment]
@vears91 Thanks for your response. You're right, it's working on linux/ubuntu !!! But I can't on windows.
With the cmd: `helm env`
```bash
HELM_BIN="helm"
HELM_DEBUG="false"
HELM_KUBEAPISERVER=""
HELM_KUBECONTEXT=""
HELM_KUBETOKEN=""
HELM_NAMESPACE="default"
HELM_PLUGINS="C:\Users\USER\AppData\Roaming\helm\plugins"
HELM_REGISTRY_CONFIG="C:\Users\USER\AppData\Roaming\helm\registry.json"
HELM_REPOSITORY_CACHE="C:\Users\USER\AppData\Local\Temp\helm\repository"
HELM_REPOSITORY_CONFIG="C:\Users\USER\AppData\Roaming\helm\repositories.yaml"
```
I did copy/paste`from .docker/config` to `HELM_REGISTRY_CONFIG` ("C:\Users\USER\AppData\Roaming\helm\registry.json").

**Comment by justincormack** [comment]
Hi, for Docker Hub feature requests please open an issue on the Docker Roadmap so we can know how many people want things https://github.com/docker/roadmap/issues

**Comment by jdolitsky** [comment]
For users seeking Docker Hub support, please see this issue: https://github.com/docker/roadmap/issues/135

**Comment by jdolitsky** [comment]
For users seeking Amazon ECR support, please see this issue: https://github.com/aws/containers-roadmap/issues/308

**Comment by jdolitsky** [comment]
For users seeking GitLab support, please see this issue: https://gitlab.com/gitlab-org/gitlab/-/issues/30669

**Comment by arbus1234** [comment]
Got same problem when trying to push helm chart to DockerHub: 
```
helm chart push docker.io/testttt/test-helm:0.1.0
The push refers to repository [docker.io/testttt/test-helm]
ref:     docker.io/reversinglabs/test-helm:0.1.0
digest:  43a88d28f57d12243e507ba6ba3586c821bc995b1acaa7740137cb8133f00433
size:    3.5 KiB
name:    test-helm
version: 0.1.0
Error: server message: insufficient_scope: authorization failed
```

**Comment by bacongobbler** [comment]
unstale

**Comment by guigomcha** [comment]
no news here? helm CLI still returns insufficient_scope: authorization failed when pushing to a OCI Registry that in integrated with keycloak or similar...
