### ISSUE TITLE
Cannot build helm

### ISSUE THREAD

**Issue by mobsikx** [helm/helm#5864]
build k8s.io/helm/cmd/helm: cannot load k8s.io/cloud-provider/features: cannot find module providing package k8s.io/cloud-provider/features

https://pastebin.com/EETwzS6p

**Comment by hickeyma** [comment]
@mobsikx What command did you run?

**Comment by mobsikx** [comment]
It's cleary visible in the pastebin link https://pastebin.com/EETwzS6p even with the whole log.
Not sure what else can I provide you with.
`glide install --strip-vendor
make build`

**Comment by hickeyma** [comment]
can you try: `make bootstrap build` ?

**Comment by karuppiah7890** [comment]
Also, @mobsikx What changes did you make in the git repo? In the logs I see this log

```
make build
GOBIN=/Users/holym/git/helm/bin go install  -tags '' -ldflags '-w -s -X k8s.io/helm/pkg/version.GitCommit=2ca025d48222d6fa188653e2ca5eda6ed799145c -X k8s.io/helm/pkg/version.GitTreeState=dirty' k8s.io/helm/cmd/...
```

where `GitTreeState` says it's `dirty` which means some changes were made in the repo

**Comment by gitirabassi** [comment]
I'm having the same problems as you, in the pastebin is clear that go mod is enabled and that's most likely the problem

**Comment by karuppiah7890** [comment]
@gitirabassi ah. that makes sense, since it says `go: finding ...` when build runs. To confirm this, @mobsikx can you paster your `go env` here? or just `go env GO111MODULE`?

**Comment by hickeyma** [comment]
Ping @mobsikx, did you manage to build?

**Comment by stylianosrigas** [comment]
I was facing the same issues. Managed to overcome the problem by using dep instead of go mod.
