### ISSUE TITLE
Dependency charts with multiple versions being overridden in tar balls

### ISSUE THREAD

**Issue by jpninanjohn** [helm/helm#5866]
[issue.zip](https://github.com/helm/helm/files/3271903/issue.zip)

Output of `helm version --client`:
```
Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
```

**Actual:**
When trying to install a chart with multiple versions of the same dependency, we see that the tarball created has only one version of the dependency. (The chart used is attached as a zip file).

If we try to install this release only the one dependency is created. 

`helm install --name issue dummy-chart-0.1.0.tgz` -> This only installs the one dependency that is in the tarball. 

**Expected:** 
All the dependencies should be installed with proper versions.

**Additional Info:**
We also tried with the same chart to install the release without creating the tarball and it creates it correctly.
`helm install --name issue <chart-directory>` ->This works and gives expected output.

**Possible Issue:**

https://github.com/helm/helm/blob/2ca025d48222d6fa188653e2ca5eda6ed799145c/pkg/chartutil/save.go#L167-L209

We are thinking that the filename is getting overwritten when creating the tarball. As an experiment, we tried changing the name of the file in the tarball during creation(we appended the chart version) and it worked.
https://github.com/helm/helm/blob/2ca025d48222d6fa188653e2ca5eda6ed799145c/pkg/chartutil/save.go#L168

**Comment by karuppiah7890** [comment]
cc @hickeyma

**Comment by PsyonixBarrett** [comment]
Any movement on this issue? The bug appears in helm v3 beta 3 as well. We have several "service/application" charts that rely on a single "common" chart to build up their components.

The problem we see is that we can't pin the service charts to utilize specific versions of the common chart. This could cause issue for us down the line if we need/want to introduce breaking changes in the common chart.

**Comment by bacongobbler** [comment]
closing as per discussion in #5872.
