### ISSUE TITLE
Potential malicious link in issue

### ISSUE THREAD

**Issue by hco** [helm/helm#5868]
I am currently not on a computer, so sorry if I am wrong about this, but wanted to let you know asap.

I received a notification about this comment on an issue:  https://github.com/helm/helm/issues/3130#issuecomment-500352585

I havent checked the contents of that link, but it somehow felt like it might be something bad. 

Sorry if creating an issue was the wrong way to address this.

**Comment by bacongobbler** [comment]
No problems here. It's a link to a chart repository. Thanks for the report though!

**Comment by phillycheeze** [comment]
Did anyone actually check the contents of the chart repository? It's coming from a fishy domain. Additionally, there is no reason to install tiller from another chart repo for the purposes of that discussion.

**Comment by bacongobbler** [comment]
Yes. I've checked the contents and it's a standard chart repository.

> Additionally, there is no reason to install tiller from another chart repo for the purposes of that discussion.

That invocation does not install tiller from another chart repository. It tells helm to use that URL as an alternative stable chart repository. AWS and Google services are blocked in China, so many users in China have set up unofficial chart repository mirrors.

Please see https://github.com/helm/charts/issues/14607 for more context, where that same chart URL is referenced there as well.

**Comment by phillycheeze** [comment]
Awesome, thanks for the context and reply!
