### ISSUE TITLE
chart.yaml中name和version参数如何做自定义校验

### ISSUE THREAD

**Issue by fengshunli** [helm/helm#5870]
chart包上传的时候,如何控制name和version参数一样会覆盖的问题,目前的解决方案是对tag包进行解压缩,社区这块有针对这块做调整吗

**Comment by bacongobbler** [comment]
If I translate this message, it looks like you are asking about changing the version of a chart once it has already been packaged using `helm package`. Is that right?

The idea of a chart is that once it has been packaged, the manifest should not be tampered with. If you want to update the chart version, you need to have access to the source code. You can then call `helm package --version` to change the version number before it is packaged.

Hope this helps.

**Comment by bacongobbler** [comment]
Can you explain what is the problem you are facing, and why you need to re-tag the package before uploading it?

**Comment by fengshunli** [comment]
通过harbor的api上传chart包的时候,需要对chart包中的name属性以及version做校验,如果重复的话就会覆盖,如果通过吧tag包进行解压缩的话比较麻烦,所以想问下支持chart包中的参数自定义不

**Comment by bacongobbler** [comment]
Once a chart has been packaged, it cannot be modified using Helm. Other tooling may provide this functionality as a plugin, but it's not currently a part of Helm.

Hope this helps!
