### ISSUE TITLE
Best practice question - best way to use a value from different helm deployment?

### ISSUE THREAD

**Issue by arielb135** [helm/helm#5877]
I was wondering, let's say i have 2 helm charts:

- First one is RabbitMQ, which contains an admin user (and password) i'd like to use, and some other parameter i want to reuse across applications.
- Second one, is my app, and i require to use that user to create some queues, and use the other value for my deployment.

Besides making sure the same value exists in all charts, is there anyway or recommended way to reuse the value from the already deployed Rabbitmq?

**Comment by mattfarina** [comment]
Two thoughts come to mind...

1. This is a bit of config management rather than package management (helm's sweet spot)
2. They could share a secret with the credentials. The name of the secret from the RabbitMQ chart could be passed into the apps chart.

**Comment by bacongobbler** [comment]
Closing as answered/inactive. Please re-open if there are follow-up questions here. Thanks!
