### ISSUE TITLE
Helm 3: Cannot build k8s.io/helm w/o helm.sh/helm

### ISSUE THREAD

**Issue by Dare2python** [helm/helm#5882]
Output of `helm version`:
-bash: helm: command not found
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T18:55:03Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
minikube version: v1.1.0

It looks there are still references to old "helm.sh" folder.

go build  -tags '' -ldflags '-w -s -X helm.sh/helm/internal/version.gitCommit=f109b1ba5cb83eb90481b02eaea3c968b181c279 -X helm.sh/helm/internal/version.gitTreeState=clean' -o /Users/serge/go/src/k8s.io/helm/bin/helm helm.sh/helm/cmd/helm
can't load package: package helm.sh/helm/cmd/helm: cannot find package "helm.sh/helm/cmd/helm" in any of:

**Comment by hickeyma** [comment]
@Dare2python Are you building Helm v3? If so then build will fail if not running from the path `$GOPATH/src/helm.sh/helm`. Refer to doc for more details: https://github.com/helm/helm/blob/dev-v3/docs/install.md#from-source-linux-macos

**Comment by Dare2python** [comment]
@hickeyma Thanks! 
Apparently, I've got confused of change to k8s.io in master which still v2
https://github.com/helm/helm/blob/master/docs/developers.md

**Comment by hickeyma** [comment]
Thats ok. Yes, v2 is still and will remain under `k8s.io`.
