### ISSUE TITLE
helm upgrade deletes Deployment causing downtime

### ISSUE THREAD

**Issue by adharmawan** [helm/helm#5883]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-10T11:44:36Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
kube-aws
```

Due to a bug in [yq](https://github.com/mikefarah/yq/issues/245)
```
❯ echo "tag: 123456" > test.yaml
❯ yq w -i test.yaml tag 23560e4
❯ cat test.yaml
tag: 2.356e+08
```

The upgrade command
`helm upgrade staging-api api --install --force --reset-values --namespace staging --values api/staging-values.yaml --wait --debug`     

the `helm upgrade` failed and deletes a `Deployment` resulting in 0 number of `pods` running with an error message of 
                                                                   
```
Upgrade "api" failed: Failed to recreate resource: Deployment.apps "api-v1" is invalid: metadata.labels: Invalid value: "2.356e+08": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```

tiller logs:
```
...
[kube] 2019/06/13 04:06:45 building resources from updated manifest
[kube] 2019/06/13 04:06:45 checking 5 resources for changes
2019/06/13 04:06:45 Cannot patch Deployment: "api-v1" (Deployment.apps "api-v1" is invalid: metadata.labels: Invalid value: "2.356e+08": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?'))
2019/06/13 04:06:45 Deleted Deployment: "api-v1"
[kube] 2019/06/13 04:06:45 error updating the resource "api-v1":
     Failed to recreate resource: Deployment.apps "api-v1" is invalid: metadata.labels: Invalid value: "2.356e+08": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
[kube] 2019/06/13 04:06:45 Looks like there are no changes for DestinationRule "api"
...
```

We found a workaround for the `yq` bug. I know it deletes the `Deployment` because of the `--force` flag. But is there a better way to handle this. If you look at the error, you'd know that destroying and creating it will trigger the same error.

**Comment by hickeyma** [comment]
@adharmawan Can you show the output of the `helm upgrade` command with `--debug --dry-run` flags? This will show the rendered manifest without actually doing the upgrade

I am trying to understand why it deletes the deployment. Is it because the deployment template is removed in the chart when doing the upgrade?

**Comment by adharmawan** [comment]
> I am trying to understand why it deletes the deployment. Is it because the deployment template is removed in the chart when doing the upgrade?

My bad, I accidentally click the `Submit Issue` button without providing all the info

**Comment by adharmawan** [comment]
here's the [gist](https://gist.github.com/adharmawan/4ef5f0c5ff61c4ae71fd0195eeca2317)

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
