### ISSUE TITLE
HELM3: its not possible to install a helm chart with helm upgrade anymore

### ISSUE THREAD

**Issue by CayoM** [helm/helm#5894]
Output of `helm version`:
helm version
version.BuildInfo{Version:"v3.0.0-alpha.1", GitCommit:"b9a54967f838723fe241172a6b94d18caf8bcdca", GitTreeState:"clean"}

Output of `kubectl version`:
 kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-28T10:10:11Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

Im using helm charts since a while to manage our deployments. It was very handy to completely setup a helm chart be using the "helm upgrade" command, instead of having to install and upgrade. Unfortunately its not possible anymore.

```
helm upgrade --set image.tag=0.0.1 mobile-prod ./deployment/mobile-ui
Error: UPGRADE FAILED: "mobile-prod" has no deployed releases
```

This would mean to me, that i would have to implement some sort of validation in the pipelines to check if the helm-chart was already installed and then upgrade it, considering that if it was already installed i need to ignore this error:

```
helm install mobile-ui deployment/mobile-ui
Error: cannot re-use a name that is still in use
```

All this was possible using helm upgrade in helm2. Hopefully some improvements can be made here.

**Comment by mattfarina** [comment]
In both Helm v2 and v3 you need the `--install` flag set to install when using upgrade. Can you try it with that flag.

**Comment by CayoM** [comment]
thanks for pointing it out. I overlooked it.

Works as designed.
