### ISSUE TITLE
HELM3: --atomic flag doesnt exist anymore

### ISSUE THREAD

**Issue by CayoM** [helm/helm#5895]
Output of `helm version`:
 helm version
version.BuildInfo{Version:"v3.0.0-alpha.1", GitCommit:"b9a54967f838723fe241172a6b94d18caf8bcdca", GitTreeState:"clean"}

Output of `kubectl version`:
kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-28T10:10:11Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

I was using the option --atomic to ensure our application keeps running, when things goes wrong while deploying (always rolling back to the latest successful deployment).
Unfortunately this doesn't exist in helm3 anymore.

Would be great if this can be implemented back.

Edit: typos.

**Comment by bacongobbler** [comment]
The --atomic flag is a very recent change to Helm 2, and was not ported over as a patch to Helm 3. We'd appreciate a PR to port it over to Helm 3.

**Comment by bacongobbler** [comment]
cc @cleac

**Comment by cleac** [comment]
@bacongobbler thanks for mentioning me, I can do this in a day or two. Is it ok?

**Comment by bacongobbler** [comment]
closed via #6011.
