### ISSUE TITLE
Ignore some line with function

### ISSUE THREAD

**Issue by Stolr** [helm/helm#5899]
--- Question / help ----

Hey ,

I am trying to create a config file with some gotpl function inside.

Here is the configmap definition :

```
{{- if eq .Values.varnish.useExistingConfigmap "-" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
data:
  default: |-
      vcl 4.0;
      import std;

      # This is a basic VCL configuration file for varnish.  See the vcl(7)
      # man page for details on VCL syntax and semantics.

      #
      # Default backend definition.  Set this to point to your content
      # server.
      #
      backend cluster {
        .host = "{{ getenv "BACKEND_VARNISH" "backend" }}";
        .port = "80";
        .first_byte_timeout = {{ .Values.varnish.backend.timeout.first_byte }};
        .connect_timeout = {{ .Values.varnish.backend.timeout.connect }};
        .between_bytes_timeout = {{ .Values.varnish.backend.timeout.between_bytes }};
```

As you can see in the .host line , I use a function call `getenv`.

This function will be use by my container with a  gotpl bin which allow me to use this getenv function.

I don't want Helm to consider this line and to just put it as is in my config file. But it won't , here is the error 

`Error: parse error in "/configmap.yaml": template: configmap.yaml:21: function "getenv" not defined
`

Which is normal since helm try to find the function definition which is not.

Is there any way to achieve my goal ? Maybe with a "fake" function in the helper ?

Thanks !

**Comment by bacongobbler** [comment]
Try `.host = "{{ "{{" }} getenv "BACKEND_VARNISH" "backend" {{ "}}" }}";`. Encapsulating your angle brackets will escape the evaluation.

**Comment by Stolr** [comment]
Seems to work fine !

Thanks for your support
