### ISSUE TITLE
Show better error when trying to install non-CRDs with crd-install hook

### ISSUE THREAD

**Issue by karuppiah7890** [helm/helm#5900]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```

This is related to the issue - https://github.com/helm/helm/issues/5756 . It's a case where people used `crd-install` hook to install resources which are not CRD. It worked before, but it doesn't work in helm > v2.14.0 as you can see in the above issue. The solution is not use `crd-install` hook to install resources which are not CRD, and we can inform the user about the same when we find such resources and give proper error

**Comment by karuppiah7890** [comment]
@bacongobbler Will a PR be accepted for this ? Considering we are trying to cut the last feature release for v2 soon, will there be time for this one? Let me know what would be the timeline. Like by what time a PR needs to be raised for it to be accepted - that is reviewed, merged, and ready for last v2 feature release

**Comment by bacongobbler** [comment]
We are no longer accepting bug fixes for Helm 2. See https://helm.sh/blog/helm-v2-deprecation-timeline/ for more details.
