### ISSUE TITLE
helm chart pull requires explicit default tag `latest` 

### ISSUE THREAD

**Issue by zioproto** [helm/helm#5906]
Output of `helm version`:
version.BuildInfo{Version:"v3.0.0-alpha.1", GitCommit:"b9a54967f838723fe241172a6b94d18caf8bcdca", GitTreeState:"clean"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

Steps to reproduce:
```
$ helm chart pull gcr.io/myproject/mychart
Using default tag: latest
latest: Pulling from gcr.io/myproject/mychart
Error: object required
```
It should use the default `latest` tag but it actually does not and it fails.

If adding `:latest` it works:

```
$ helm chart pull gcr.io/myproject/mychart:latest
latest: Pulling from gcr.io/myproject/mychart
Name: mychart
Version: 0.1.0
Meta: sha256:xxxxxxx....
Content: sha256:xxxxxx....
Status: Chart is up to date for gcr.io/myproject/mychart:latest
```

**Comment by hickeyma** [comment]
@zioproto This should be covered by #5752. Closing as a duplicate and adding this as a comment to #5752.
