### ISSUE TITLE
apiVersion still v1 in Helm v3

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#5907]
The `apiVersion` in charts for Helm v3 is `v1`. Yet, there have been some chart changes including:

- dependencies moved to the `Chart.yaml` file
- `requirements.lock` is now `Chart.lock`
- annotations added to the `Chart.yaml` file

I understand that Helm v3 works for both the older and newer setups. But, external tools that work with charts don't know about the changes.

Should we move the `apiVersion` to `v2`?

**Comment by bacongobbler** [comment]
slating to get this done before we release the first beta.

**Comment by hickeyma** [comment]
@mattfarina @bacongobbler I can work on this if it is open to be done?

**Comment by bacongobbler** [comment]
Sure!

**Comment by hickeyma** [comment]
Here are the tasks required:

- [ ] Update scaffold chart to be "v2"
- [ ] Update linting to handle new dependencies and annotations
- [ ] Update documentation to specify "v2" as default version and "v1" for specific scenarios

**Comment by bacongobbler** [comment]
Additional TODO:

- [ ] Helm 2 should fail to load a chart with an `apiVersion` field of anything other than `v1` or the empty string (Helm 2 doesn't validate the `apiVersion` field, so those charts are assumed to be compiled against `apiVersion` v1

**Comment by hickeyma** [comment]
Thanks @bacongobbler for the heads up in https://github.com/helm/helm/issues/5907#issuecomment-516963275. I have added it to the task list in https://github.com/helm/helm/issues/5907#issuecomment-516063552.

**Comment by bacongobbler** [comment]
all of the PRs for the tasks have been merged so this can now be closed :)

**Comment by hickeyma** [comment]
Thanks @bacongobbler for the doc PR.
