### ISSUE TITLE
PriorityClass resources should be installed first before any pod-providing resources

### ISSUE THREAD

**Issue by xaka** [helm/helm#5916]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T18:56:36Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.7-3+1a4d39a9763d23", GitCommit:"1a4d39a9763d23548d16e262d6dbe0fb2198a8ce", GitTreeState:"clean", BuildDate:"2019-03-27T01:47:38Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
OKE
```

---

If I've got a DaemonSet that uses a particular PriorityClass, then Helm install/upgrade fails with:
```
2019/06/19 07:36:50 Command returned with exit code: . And error message: Error: UPGRADE FAILED: no PriorityClass with the name "log-collector" found
```

I've checked the source code and PriorityClass isn't part of https://github.com/helm/helm/blob/master/pkg/tiller/kind_sorter.go

**Comment by xaka** [comment]
Given there will be many more of such cases in the future as k8s is being actively developed, I think it might make sense to add a special annotation so users of Helm could specify an order/weight of k8s resources themselves. 

As a workaround, such resource could be converted into a hook, but it's kind of dirty and I'd rather have a more official solution. Problem with hooks is resources aren't deleted after Helm chart is deleted.

**Comment by jaytaylor** [comment]
I've also observed cases where cluster-action is blocked due to priorityClass being absent after a `helm install --upgrade`.

For example:

```Events:
  Type     Reason        Age                  From                    Message
  ----     ------        ----                 ----                    -------
  Warning  FailedCreate  3m (x1405 over 11h)  statefulset-controller  create Pod elasticsearch-data-2 in StatefulSet elasticsearch-data failed error: pods "elasticsearch-data-2" is forbidden: no PriorityClass with name elasticsearch-data was found```

```bash
$ helm version
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}```

```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.7-3+1a4d39a9763d23", GitCommit:"1a4d39a9763d23548d16e262d6dbe0fb2198a8ce", GitTreeState:"clean", BuildDate:"2019-03-27T01:47:38Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.7-3+1a4d39a9763d23", GitCommit:"1a4d39a9763d23548d16e262d6dbe0fb2198a8ce", GitTreeState:"clean", BuildDate:"2019-03-27T01:47:38Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

A manual workaround (temporary) solution is published here: https://gist.github.com/jaytaylor/451c5caf27780ec0009494bf6baf979a

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

**Comment by ThomWilhelm** [comment]
I don't think I can re-open this, but it does seems like PriorityClass isn't even included in the Kind sorter:

https://github.com/helm/helm/blob/release-3.0/pkg/releaseutil/kind_sorter.go

Not familiar with the codebase, but could it be as similar as just adding it somewhere sensible there?

Workarounds are pretty ugly like having a separate helm install for just the PriorityClass first.

**Comment by adamish** [comment]
Still seems to be an issue even in Helm 3.5.2

**Comment by marcgenou** [comment]
Issue yet on 3.9.3 :(
