### ISSUE TITLE
Expand effect of <CHARTNAME> to file names

### ISSUE THREAD

**Issue by zarbis** [helm/helm#5920]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-gke.6", GitCommit:"394ee507d00f15a63cef577a14026096c310698e", GitTreeState:"clean", BuildDate:"2019-03-30T19:31:43Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform: GKE

I'm working on creating starter for applications that are intended to have multiple deployments within  a single release. Intended `values.yaml` for such app looks like this:
```yaml
<CHARTNAME>:
  image:
    repo: foo/bar
    tag: latest
  args: ["--mode", "api"]
<CHARTNAME>-worker:
  image:
    repo: foo/bar
    tag: latest
  args: ["--mode", "worker"]
```

Corresponding templates access those variables just fine: `{{ index .Values "<CHARTNAME>-worker" "args" }}`.
But I want to have coherent chart directory strusture like this:
```
.
├── Chart.yaml
├── requirements.yaml
├── templates
│   ├── <CHARTNAME>
│   │   └── deployment.yaml
│   ├── <CHARTNAME>-worker
│   │   └── deployment.yaml
│   ├── _helpers.tpl
│   ├── NOTES.txt
└── values.yaml
```
It can be either directories as in example above, or just prefixes in file names like `templates/<CHARTNAME>-deployment.yaml`
As of now I'm unable to do so without ad-hoc scripting. So allowing starters to have file or directory names with placeholder and `helm create --starter foo` to detect and rename those files will make this scenario possible.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
