### ISSUE TITLE
Helm installation caught in limbo after pre-install-hook failure

### ISSUE THREAD

**Issue by NandoTheessen** [helm/helm#5923]
Output of `helm version`: 2.14.1 client & server

Output of `kubectl version`: 1.15

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS EKS 

Hi! I've been experimenting with the pre-install hook and encountered a failure during `helmsman apply` (I know this is the helm repo, but I figured it's only a very small abstraction over it).

My hook:
`apiVersion: batch/v1
kind: Job
metadata:
  name: anchore-engine
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: tingeltangelbobsalpine
    spec:
      restartPolicy: Never
      containers:
      - name: pre-install-job
        image: "alpine:3.3"
        command: ["/bin/bash","-c", "sleep 10"]`

After erroring here because bash is not part of alpine, the installation simply did not continue (left it for a good 2 minutes). Cancelling the apply then led to a job & pods related to the chart that are left in the cluster & are not being removed by running `helmsman -destroy`.

It could well be that this is a user error, but I think a failed install should be handled more gracefully.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
