### ISSUE TITLE
Helm v2 detect v3 charts and message it cannot run them

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#5924]
Helm v3 charts are different enough from v2 that v2 cannot run them. We should detect these charts and display a message to the user that they cannot be run with some further instruction. This should also handle the whole dependency tree.

PRs welcome if someone wants to try to write this.

**Comment by bacongobbler** [comment]
We are no longer accepting bug fixes for Helm 2. See https://helm.sh/blog/helm-v2-deprecation-timeline/ for more details.
