### ISSUE TITLE
h3 returns x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by gkarthiks** [helm/helm#5926]
Output of `helm version`: 
> version.BuildInfo{Version:"v3.0.0-alpha.1", GitCommit:"b9a54967f838723fe241172a6b94d18caf8bcdca", GitTreeState:"clean"}

Output of `kubectl version`:
> Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-01-14T00:24:11Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  OpenShift 3.11

This x509 was not an issue with the helm v2. When I started using this, I got this error. So for time being I am setting `--insecure-skip-tls-verify=true` in my kubeconfig file to bypass this issue.

**Comment by bacongobbler** [comment]
Can you please provide more information on your setup? That way community members can try to reproduce the issue for you and see if they can come to the same conclusion. Thanks.

**Comment by gkarthiks** [comment]
@bacongobbler  sure, apologies for the delay.

The step to reproduce is very simple. Have a kubernetes cluster with self-signed certificate. (I have OCP with Self Signed certificate)

From your local machine (i am using Mac), do helm init. When trying execute an install or list command, the x509 error will be thrown.

**Comment by bacongobbler** [comment]
Can you provide your setup instructions? There's 1,000,001 ways to setup a k8s cluster, each potentially ending in different results. If we can provision an identical cluster setup then we can start to nail down the issue.

**Comment by gkarthiks** [comment]
So sorry @bacongobbler. This is our corporate cluster. Unfortunately I have no access/ idea how its been setup. But I think its an playbook installation.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
