### ISSUE TITLE
Chart not recreating rs / pods

### ISSUE THREAD

**Issue by pulpbill** [helm/helm#5927]
Output of `helm version`:
`Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
`
Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T08:56:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
`
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Kops at AWS

I'm deploying an app (that works perfect in another country / cluster / same conf) but now I'm seeing every objects create (deploy, svc, cm, secrets) but there are no rs / pods. I did a helm del --purge many times. Re deploy via gitlab other branches, manuals re deploy, but nothing, and I'm not seeing logs for "kubectl get events".

Any ideas? It's the first time that I see this, I have many clusters and apps. It's weird.

**Comment by bacongobbler** [comment]
Have you tested this against a more recent version of Kubernetes? 1.7 is quite old at this point... It was release in 2017. We can't guarantee compatibility with a version of Kubernetes that old.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
