### ISSUE TITLE
Access issue while accessing kuberntes dashboard

### ISSUE THREAD

**Issue by charuni2018** [helm/helm#5943]
Output of `helm version`: nothing

Output of `kubectl version`:services \"https:kubernetes-dashboard:\" is forbidden: User \"system:anonymous\" cannot get resource \"services/proxy\" in API group \"\" in the namespace \"kube-system\"",
  "reason": "Forbidden",

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by charuni2018** [comment]
I am trying to provide namespace access to the development team hence I am trying to have another config which I can share with them just for the namespace.
Below are the steps I followed.
1. Namespace creation
2. Give default account access performed role binding & cluster binding
3. kubectl describe secret default-token-xXXX --namespace=demo
4. Add user token to .kube/config file and removed the token entry in the config which has cluster level access
5. After this while I am trying to access the Kubernetes-dashboard I am seeing the below error:


"services \"https:kubernetes-dashboard:\" is forbidden: User \"system:anonymous\" cannot get resource \"services/proxy\" in API group \"\" in the namespace \"kube-system\""
--
reason | "Forbidden"


How to access the Kubernetes dashboard in this case?

**Comment by bacongobbler** [comment]
Why is this a Helm issue?

Please open an issue over at https://github.com/kubernetes/dashboard if you're having troubles with the kubernetes dashboard. If you're having troubles with a particular chart, please contact the maintainers of that chart and ask for their assistance. Thanks.
