### ISSUE TITLE
`helm prune`: purge old deleted releases

### ISSUE THREAD

**Issue by alexkreidler** [helm/helm#5944]
It might be nice to have a `helm prune` command to `purge` all your old releases that you've deleted and no longer need. It would be similar to the `docker prune` command, which removes old stopped containers and other resources.

It would effectively do this:
```
helm ls --deleted --short | xargs -L1 helm delete --purge
```

**Comment by alexkreidler** [comment]
[This StackOverflow thread](https://stackoverflow.com/q/47817818) describes multiple methods for deleting (and/or purging) all releases.

Another reason for a `helm prune` command would be that it would encourage a flexible `delete` and `rollback` workflow. It would discourage `helm delete --purge` on the first go by providing an alternative for later. This would allow users to `rollback` deletes if needed and then only `prune` when necessary.

**Comment by hickeyma** [comment]
@alexkreidler Would you like to try a PR for this?

**Comment by alexkreidler** [comment]
Sure, I will if I get some time. Thanks!

**Comment by bacongobbler** [comment]
I think this may be a valuable plugin. It has a niche use case where we may not want to roll it into core, but it is useful enough in certain cases. A plugin similar to helm-diff could be useful.

**Comment by alexkreidler** [comment]
I'm working on this right now, it seems like a very basic implementation that just calls out to other library functions, namely `ListReleases` and `DeleteRelease`, and would not add any technical debt to the core. The basics are adding a `cmd/helm/prune.go` file for the command and adding a `PruneReleases` function to `pkg/helm/client.go`, and then if we wanted to keep the options from the delete command, we would add a `PruneOption` func type (more details below).

I think the point of the command is to encourage a more streamlined workflow and would make more sense in the core. How is it going to be adopted if its not in the core? However, I do understand that currently, the mindset for this use-case/workflow is not commonplace yet, so I am open to any discussion about the workflow and its benefits/drawbacks.

The one question I have is: which options should we keep from the `delete` command? Obviously, `--prune` will always be true and therefore not exposed to the user, and I think `--dry-run` is unecessary because it is effectively the same as `helm list --deleted`, but I'm inclined to keep `--no-hooks` and `--timeout` to pass through to the delete commands, and also obviously keep the TLS options.

I'll submit a PR soon so we can discuss more there.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
