### ISSUE TITLE
give a pdf version for doc :)

### ISSUE THREAD

**Issue by jinleileiking** [helm/helm#5946]
Output of `helm version`:

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by hickeyma** [comment]
@jinleileiking What is the use case for a PDF version of the docs?

**Comment by jinleileiking** [comment]
I want to read all helm things on kindle :)

**Comment by jinleileiking** [comment]
And seems there are a lot of solution to get pdf/mobi from md files.

**Comment by hickeyma** [comment]
@jinleileiking I am not sure that providing the docs in PDF format so you can read them on a kindle is a use case worth pursing. I think the web docs are the best format for everyone to use.

Thanks for raising the request.

**Comment by jinleileiking** [comment]
Thanks too
