### ISSUE TITLE
Helm3 : helm status does not show k8s resource names that were deployed as part of release

### ISSUE THREAD

**Issue by pragyamehta** [helm/helm#5952]
helm status in Helm2 used to show a list of deployed kubernetes objects like deployments/pods/ingresses/services etc. Helm3 does not show that. It does however show the manifest. I was wondering if there are any plans to add the deployed object names like Pods to Helm3's status command

**Comment by hickeyma** [comment]
@pragyamehta Thanks for raising this.

In v2:

```console
$ helm status mychart
LAST DEPLOYED: Fri Jun 28 11:16:50 2019
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/Deployment
NAME     READY  UP-TO-DATE  AVAILABLE  AGE
mychart  1/1    1           1          4m2s

==> v1/Pod(related)
NAME                     READY  STATUS   RESTARTS  AGE
mychart-b9488ff5c-b6xzz  1/1    Running  0         4m2s

==> v1/Service
NAME     TYPE       CLUSTER-IP      EXTERNAL-IP  PORT(S)  AGE
mychart  ClusterIP  10.110.150.104  <none>       80/TCP   4m2s


NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=mychart,app.kubernetes.io/instance=mychart" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl port-forward $POD_NAME 8080:80
```

In v3:

```console
$ helm status mychart
NAME: mychart
LAST DEPLOYED: 2019-06-28 11:09:43.763417029 +0100 IST
NAMESPACE: default
STATUS: deployed

NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods -l "app=mychart,release=mychart" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl port-forward $POD_NAME 8080:80
```

**Comment by pragyamehta** [comment]
I don't think if I'll be able to rely on 
export POD_NAME=$(kubectl get pods -l "app=mychart,release=mychart" -o jsonpath="{.items[0].metadata.name}")

This is because this query relies on the labels app and release which are optional labels that can be removed from the chart.
Is there any plan of Helm3 status command having the same output as that of Helm2 status command?

**Comment by hickeyma** [comment]
@pragyamehta I have raised it as a bug in v3.

**Comment by pragyamehta** [comment]
Thanks Martin!

**Comment by bacongobbler** [comment]
That info should be printed out if it's part of the release info.

https://github.com/helm/helm/blob/2c397b6879ca3ddee955b4f4f349647e6c3791b9/pkg/action/printer.go#L44-L50

Can you check and confirm if this object is empty after calling `helm install`?

**Comment by agolomoodysaada** [comment]
I reproduced this bug in `3.0.0-beta.2`

**Comment by karuppiah7890** [comment]
There's a duplicate issue https://github.com/helm/helm/issues/6194 . Need to close one of them. Either this or that.

**Comment by bacongobbler** [comment]
Given there is a workaround with `helm get manifest`, I think it's safe to punt over from the 3.0 milestone. I found out today that the live state of resources was removed from `helm status` due to poor code quality (I assume this had to do with no clear separation of concerns between the release and the live state), and the fact that there are other avenues to view the same output as @thomastaylor312 has shown above.

The code I referenced above in an earlier comment has since been refactored out. Likely just an oversight.

**Comment by mircohaug** [comment]
> The main reason for this is that by doing this in Helm, it leads to code duplication (we basically end up copying `kubectl` code), possible bugs, and maintenance overhead in the Helm codebase. So I think it would be better to keep it out.
> 
> What are people's thoughts on this?

I agree, that code duplication should be avoided. But the manifest approach hides the related objects like pods or persistent volume claims generated from statefulsets.

**Comment by thomastaylor312** [comment]
Yeah, that does make sense. But the code that looked up related pods was...spaghetti-like to say the least (due to the nature of how to look up those pods in a generic way). The real question though is whether or not an extra step to look up generated resources is a deal breaker for most users. If it is, then we might want to have a further discussion. However, even if people do want it, we'd have to bring back most of the status code anyway because it wouldn't make sense for helm to just print dependent resource status. That would probably be a no go for me

**Comment by marckhouzam** [comment]
I tried creating a `helm status` alias for myself using the workaround `helm get manifest foo | kubectl get -f -` but quickly realized that flags like `--namespace` start making things complicated.  So I wrote a plugin to handle things.

If it can prove useful to others:
https://github.com/marckhouzam/helm-fullstatus

For example, for a release named `nginx_rel` within namespace `nginx_ns`, the command:
```
$ helm fullstatus --namespace nginx_ns nginx_rel
```
will provide the standard helm status output followed by something like:
```
NAME                                         SECRETS   AGE
serviceaccount/nginx-nginx-ingress           1         4h9m
serviceaccount/nginx-nginx-ingress-backend   1         4h9m

NAME                                                        AGE
clusterrole.rbac.authorization.k8s.io/nginx-nginx-ingress   4h9m

NAME                                                               AGE
clusterrolebinding.rbac.authorization.k8s.io/nginx-nginx-ingress   4h9m

NAME                                                 AGE
role.rbac.authorization.k8s.io/nginx-nginx-ingress   4h9m

NAME                                                        AGE
rolebinding.rbac.authorization.k8s.io/nginx-nginx-ingress   4h9m

NAME                                          TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
service/nginx-nginx-ingress-controller        LoadBalancer   10.109.134.220   <pending>     80:31903/TCP,443:31726/TCP   4h9m
service/nginx-nginx-ingress-default-backend   ClusterIP      10.107.14.157    <none>        80/TCP                       4h9m

NAME                                                  READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/nginx-nginx-ingress-controller        1/1     1            1           4h9m
deployment.apps/nginx-nginx-ingress-default-backend   1/1     1            1           4h9m
```

**Comment by iyinoluwaayoola** [comment]
Adding the resource listing to the status command is a very convenient way to monitor releases. The workaround mentioned by @thomastaylor312 works but adds new headers to every displayed item, which makes it ugly to read. 

Besides, the docs is misleading as the example codes show that the resources are listed.

**Comment by thomastaylor312** [comment]
@iyinoluwaayoola That is definitely a docs update we need to make then. Some of those things just slipped through as we updated docs

**Comment by towolf** [comment]
I think realistically Helm needs a command that shows: "What's contained in this chart?"

There's no way around it, and spewing the yaml of the resources is not going to cut it.

**Comment by thomastaylor312** [comment]
@towolf Are you looking more for a "these are the resources contained in the chart" or are you looking for actual resource statuses? I am more inclined to the former because it is pretty easy to print the object kind and type without lots of overhead

**Comment by towolf** [comment]
@thomastaylor312 the former would be ok as it would display the most important infomation, the latter would be better, since it would be even more informative.

**Comment by ppawel** [comment]
With Helm 2 it is very useful to use something like `watch helm status <release>` to basically get the real-time progress of a release with only essential information displayed - no GUI noise (like with k8s Dashboard), no k8s events noise (like with `kubectl get events -w`).

You could say that this functionality is not really in scope for Helm but on the other hand the ability to "monitor" release resources from CLI has the potential of being a killer feature...

**Comment by bacongobbler** [comment]
> You could say that this functionality is not really in scope for Helm but on the other hand the ability to "monitor" release resources from CLI has the potential of being a killer feature...

Here's the crux of the issue:

> But the code that looked up related pods was...spaghetti-like to say the least (due to the nature of how to look up those pods in a generic way).

To add additional context, every time we bumped kubernetes client versions, the code for `helm status` was broken in some form. In fact, [it broke again](https://github.com/helm/helm/issues/6896) when we bumped Helm 2 to Kubernetes 1.16.

I'm not in favour of re-introducing and maintaining a piece of code that constantly breaks backwards compatibility. If there's a piece of code that doesn't happen to break every release cycle, we'd be happy to take a look.

**Comment by sarvaniy** [comment]
Can i work on this task, in order to show up the resources information in "helm status" command

Below is the example to show up the helm status output

example:

helm status chart-1582870419

NAME: chart-1582870419
LAST DEPLOYED: Fri Feb 28 06:13:41 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
RESOURCES:

==> v1/Namespace
NAME      AGE
sample1   161m

==> v1/Service
NAME                         AGE
chart-1582870419-firsthelm   161m

==> v1/Deployment
NAME                         AGE
chart-1582870419-firsthelm   161m


NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=firsthelm,app.kubernetes.io/instance=chart-1582870419" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl port-forward $POD_NAME 8080:80

**Comment by thomastaylor312** [comment]
@sarvaniy Feel free to work on it if you'd like, just keep what @bacongobbler said [here](https://github.com/helm/helm/issues/5952#issuecomment-580399492) in mind when you do it

**Comment by schollii** [comment]
how about just having a command that calls kubectl under the hood? this avoids the duplication and backwards compat problem. Also showing status of all resources in a helm release is a task people need often, so it has to be short and easy to remember, not (the otherwise impressive) `helm get manifest NAME | kubect get -f -`!

**Comment by bacongobbler** [comment]
I'm fairly certain that was how `helm status` worked. It mimicked the output of `helm get -o wide`, and I think that's what @sarvaniy is attempting in #7728. We'll have to re-review upstream's code to check what broke last time. Perhaps by figuring out what's causing #6896 will determine if #7738 is feasible or not.

**Comment by schollii** [comment]
I don't think it is the same as #7728. Sounds like in helm 2 there was a significant portion of k8s code being imported, and this has been removed in helm 3. This means that the logic of kubectl get would have to be re-implemented, this does not sound very maintainable. 

What I was saying is that "helm status" would call a function which in *pseudocode* would look something like this (sorry I know several programming languages but not really Go): 
```
void status(release_name string) {
    manifest_string = get_manifest(release_name);
    system("kubectl get -f -", stdin=manifest_string);
}
```

**Comment by jkroepke** [comment]
unlike helm 2 status

```
helm get manifest <release> | kubectl get -f -
```

does not show related objects (like pods) .

**Comment by bacongobbler** [comment]
see https://github.com/helm/helm/pull/7728

**Comment by whereisaaron** [comment]
@sarvaniy's work on #7728 looks like it will restore this functionality quite cleanly. It has been reviewed but not merged. Is there a target release it will appear in?

**Comment by sarvaniy** [comment]
Hi Aron,

    I don't know any idea on target release. As you said it's reviewed
already,  could you please merge it if it's possible.

Best Regards,
Sarvani.

**Comment by jkroepke** [comment]
unstable.

**Comment by hdiass** [comment]
is this still not resolved, when will this be merged ?

**Comment by schollii** [comment]
@bacongobbler any idea what is holding up the merge?

**Comment by JoarJ** [comment]
> I tried creating a `helm status` alias for myself using the workaround `helm get manifest foo | kubectl get -f -` but quickly realized that flags like `--namespace` start making things complicated. So I wrote a plugin to handle things.
> 
> If it can prove useful to others:
> https://github.com/marckhouzam/helm-fullstatus
> 
> For example, for a release named `nginx_rel` within namespace `nginx_ns`, the command:
> 
> ```
> $ helm fullstatus --namespace nginx_ns nginx_rel
> ```
> 
> will provide the standard helm status output followed by something like:
> 
> ```
> NAME                                         SECRETS   AGE
> serviceaccount/nginx-nginx-ingress           1         4h9m
> serviceaccount/nginx-nginx-ingress-backend   1         4h9m
> 
> NAME                                                        AGE
> clusterrole.rbac.authorization.k8s.io/nginx-nginx-ingress   4h9m
> 
> NAME                                                               AGE
> clusterrolebinding.rbac.authorization.k8s.io/nginx-nginx-ingress   4h9m
> 
> NAME                                                 AGE
> role.rbac.authorization.k8s.io/nginx-nginx-ingress   4h9m
> 
> NAME                                                        AGE
> rolebinding.rbac.authorization.k8s.io/nginx-nginx-ingress   4h9m
> 
> NAME                                          TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
> service/nginx-nginx-ingress-controller        LoadBalancer   10.109.134.220   <pending>     80:31903/TCP,443:31726/TCP   4h9m
> service/nginx-nginx-ingress-default-backend   ClusterIP      10.107.14.157    <none>        80/TCP                       4h9m
> 
> NAME                                                  READY   UP-TO-DATE   AVAILABLE   AGE
> deployment.apps/nginx-nginx-ingress-controller        1/1     1            1           4h9m
> deployment.apps/nginx-nginx-ingress-default-backend   1/1     1            1           4h9m
> ```

awesome, thnx !

**Comment by muffl0n** [comment]
The most annoying thing about this is, that the help text says
```
-> % helm status --help | grep resources
- list of resources that this release consists of, sorted by kind
```

But in fact it does not!

**Comment by jkroepke** [comment]
👍

**Comment by bj1074** [comment]
namespace and state of the deployment also is incorrect

**Comment by saada** [comment]
activity

**Comment by punkstarman** [comment]
+1

**Comment by GreenRover** [comment]
+1

**Comment by dreamerkr** [comment]
+1
