### ISSUE TITLE
objects deleted but helm release still there

### ISSUE THREAD

**Issue by IamGabrielWu** [helm/helm#5954]
I manually deleted some namespaces.
And there were some release installed in those namespaces by helm.
When i do "helm ls" i can see those releases still exist.

Is there a way i can update helm database so that "helm ls" doesn't show the deleted resources ?

**Comment by bacongobbler** [comment]
`helm delete --purge RELEASE_NAME`?

**Comment by IamGabrielWu** [comment]
@bacongobbler No, I mean do it in a batch. 
For example i have thousands of releases in 10 namespaces, and i deleted 10 namespaces now i don't want to run "helm delete --purge RELEASE_NAME" one by one. I want to refresh helm database so that  it's updated to reflect latest status.

**Comment by hickeyma** [comment]
@IamGabrielWu When you are deleting the releases in the first place, use `--purge` flag and they will be removed from the history. Then, you will not need to refresh.

**Comment by IamGabrielWu** [comment]
I didn't delete releases. I mean i deleted namspaces, use "kubectl delete namespace x1, x2, x3". I' seeking a way to also update helm release databases, in a batch .

**Comment by hickeyma** [comment]
Ah, see what you mean. There is no batch delete capability but it is easy to script it using Helm commands. Here is an example using bash:

`helm delete $(helm ls --all --short --namespace <namespace>) --purge`.

Hope this helps.

**Comment by IamGabrielWu** [comment]
@hickeyma wonderful. Thanks very much 👍

**Comment by hickeyma** [comment]
Not a bother.
