### ISSUE TITLE
Need a way to order sub charts deployment specified in requirement.yaml

### ISSUE THREAD

**Issue by Dhananjay-J-P** [helm/helm#5955]
Is there any way we can set order in which subcharts will be deployed. Currently, I have a chart with some subcharts, lets say chart a, chart b, chart c ... chart n. 

can I set order so that unless until chart a's container is up chart b won't be launched?

**Comment by hickeyma** [comment]
Closing as a duplicate of https://github.com/helm/helm/issues/5723.
