### ISSUE TITLE
Best practices: should I keep the "full" version of the values.yaml in my repository or just the changes?

### ISSUE THREAD

**Issue by jonatasbaldin** [helm/helm#5959]
Hey there 👋 

When deploying Helm charts in a private organisation using private repositories, is it a best practice to have a full copy of the provided `values.yaml` file into my private repository (with all options/comments – changing just what I need) or should I create a file with just my changes and commit that?

In one side, having the whole content (even keeping 95% of defaults) is good for documentation, since I can quickly take a look at everything that I can configure. But on the other side, there's a lot of noise in the file.

What do you usually do?

Thanks!

**Comment by bacongobbler** [comment]
hey @jonatasbaldin, have you tried reaching out to the #helm-users channel on Slack? general questions about best practices are probably better served there. Most users are hanging out there rather than reading the issue queue :)

**Comment by jonatasbaldin** [comment]
hey @bacongobbler, thanks for the tip, will reach people there :)

**Comment by jimmy3142** [comment]
Hey @bacongobbler, did you get any feedback on this from the Slack workspace?

**Comment by jimmy3142** [comment]
Hey @jonatasbaldin, did you get any feedback on this from the Slack workspace?
