### ISSUE TITLE
`helm dep build` tries to open my contacts files on Mojave when run in the home folder.

### ISSUE THREAD

**Issue by alexkreidler** [helm/helm#5960]
On MacOS Mojave 10.14.5, I ran `helm dep build` in my `$HOME` folder accidentally. This was not a chart repository, so it did not have a `Chart.yaml` or a `requirements.yaml`.

However, iTerm2/the MacOS privacy system gave me a popup saying that a process was requesting access to my contacts info, which I denied.

This then resulted in `helm dep build` giving the output: `Error: open /Users/alex/Library/Application Support/AddressBook: operation not permitted`.

Although running `helm dep build` in a directory that is not a helm chart is unsupported, I believe that this is still not expected behavior.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
