### ISSUE TITLE
Example in doc  helm/docs/chart_template_guide/values_files.md  return  error

### ISSUE THREAD

**Issue by whmzsu** [helm/helm#5962]
Output of `helm version`:
Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
N/A

I am learning helm from the doc file , and find one prolem while I  am execing the same command from the doc file  located  helm/docs/chart_template_guide/values_files.md  line below 

"""""
However, Kubernetes would then fail because you can not declare more than one livenessProbe handler. To overcome this, you may instruct Helm to delete the `livenessProbe.httpGet` by setting it to null:
```sh
helm install stable/drupal --set image=my-registry/drupal:0.1.0 --set livenessProbe.exec.command=[cat,docroot/CHANGELOG.txt] --set livenessProbe.httpGet=null
```
"""""""""

The cmd  

```sh
helm install stable/drupal --set image=my-registry/drupal:0.1.0 --set livenessProbe.exec.command=[cat,docroot/CHANGELOG.txt] --set livenessProbe.httpGet=null
```
return an error  

```sh
# helm install stable/drupal  --set livenessProbe.exec.command=[cat,docroot/CHANGELOG.txt] --set livenessProbe.httpGet=null
Error: failed parsing --set data: key map "docroot/CHANGELOG" has no value
```
So  is there any thing wrong with the array value set ????

**Comment by bacongobbler** [comment]
Yes. The proper syntax (as per [the format and limitations of --set](https://helm.sh/docs/using_helm/#the-format-and-limitations-of-set)) is `--set livenessProbe.exec.command={cat,docroot/CHANGELOG.txt}`. Can you try that?

**Comment by whmzsu** [comment]
Got another error

```
#  helm install stable/drupal  --set livenessProbe.exec.command={cat,docroot/CHANGELOG.txt} --set livenessProbe.httpGet=null
Error: This command needs 1 argument: chart name
```

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

**Comment by tthomaspax8** [comment]
To baseline, this works but in a specific way; as a baseline file: `mychart/templates/liveness.yaml`

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: liveness-exec
  labels:
    test: liveness
spec:
  containers:
  - name: liveness
    image: k8s.gcr.io/busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
    livenessProbe:
      httpGet:
        path: /user/login
        port: http
      initialDelaySeconds: 45
      periodSeconds: 45
```

Assuming ZSH (macOS default shell) and OMZSH specifically, you would:
1. need to add a `chart name` as the error implies
2. surround your `--set` directives in quotes, like:

```shell
helm install chartest ./mychart --debug --dry-run --set="livenessProbe.exec.command={cat,docroot/CHANGELOG.txt}"
install.go:178: [debug] Original chart version: ""
install.go:195: [debug] CHART PATH: /Users/userName/code/edu/disco-helm-charts/mychart

NAME: chartest
LAST DEPLOYED: Tue Jul 12 14:20:14 2022
NAMESPACE: default
STATUS: pending-install
REVISION: 1
TEST SUITE: None
USER-SUPPLIED VALUES:
livenessProbe:
  exec:
    command:
    - cat
    - docroot/CHANGELOG.txt

COMPUTED VALUES:
favorite:
  drink: coffee
  food: pizza
livenessProbe:
  exec:
    command:
    - cat
    - docroot/CHANGELOG.txt
pizzaToppings:
- mushrooms
- cheese
...
HOOKS:
MANIFEST:
...
# Source: mychart/templates/liveness.yaml
apiVersion: v1
kind: Pod
metadata:
  name: liveness-exec
  labels:
    test: liveness
spec:
  containers:
  - name: liveness
    image: k8s.gcr.io/busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
    livenessProbe:
      httpGet:
        path: /user/login
        port: http
      initialDelaySeconds: 45
      periodSeconds: 45
```

Try it again with quotes and it all falls apart; the issue is Googleable.
