### ISSUE TITLE
--tiller-image unknown location

### ISSUE THREAD

**Issue by IRobL** [helm/helm#5963]
I'm using helm from a k8s cluster that requires all images come from a private docker registry.  It's unclear to me where the "official" tiller images are located so I can cache them privately.  I think I found them here though at [alpine/helm](https://hub.docker.com/r/alpine/helm/tags).  Is that the official spot?  If so, it would seem as though the automation isn't working because gh shows a release version of `v2.14.1` that hasn't been released on helm.  

If anyone knows where the best place is to get the latest tiller image, I'd really appreciate the help.  Also updating docs [here](https://helm.sh/docs/install/#easy-in-cluster-installation) might be generally helpful to Helm users.

**Comment by bacongobbler** [comment]
The images are stored on Google Container Registry. The image name is embedded in the source code [here](https://github.com/helm/helm/blob/8494d133bf1847e246205b005433972c7630c5a9/cmd/helm/installer/options.go#L28). For the lazy, it's `gcr.io/kubernetes-helm/tiller`.

To reference helm 2.14.1, use the tag `gcr.io/kubernetes-helm/tiller:v2.14.0`:

```
><> docker pull gcr.io/kubernetes-helm/tiller:v2.14.0
v2.14.0: Pulling from kubernetes-helm/tiller
Digest: sha256:b78bcc64b530f2e531880f947d7d2b368dc833dd630ee6a2b27a78bcafa93b5f
Status: Image is up to date for gcr.io/kubernetes-helm/tiller:v2.14.0
```

**Comment by IRobL** [comment]
Are those docs I linked managed somewhere in this repo?
