### ISSUE TITLE
“Error: forwarding ports: Upgrade request required” Error in helm of a kubernetes cluster

### ISSUE THREAD

**Issue by AnjanaAK** [helm/helm#5965]
I have a kubernetes cluster in my DC built using **kubespray** and imported to **Rancher**.

The nodes are configured with

- OS: CentOS Linux 7 3.10.0-957.12.1.el7.x86_64
- Docker version : 18.9.5
- Kubelet version : v1.14.1
- Tiller version : v2.14.1 ( got this version from the tiller pod's image gcr.io/kubernetes-helm/tiller:v2.14.1 )

I am running the kubectl commands from my windows local machine. My ~./kube/config contains the kubeconfig of that cluster.

All the tiller resources are working fine:
```

$ kubectl get all -n kube-system | findstr tiller

pod/tiller-deploy-57ff77d846-frtb7             1/1       Running   0          12d

service/tiller-deploy          ClusterIP   10.233.49.112   <none>        44134/TCP                16d

deployment.apps/tiller-deploy             1         1         1            1           16d

replicaset.apps/tiller-deploy-57ff77d846             1         1         1         12d
replicaset.apps/tiller-deploy-69d5cd79bb             0         0         0         16d
```
But when I run the helm commands, I am getting this error:
```

$ helm version

Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Error: forwarding ports: error upgrading connection: Upgrade request required

$ helm ls

Error: forwarding ports: error upgrading connection: Upgrade request required
```
Output of `kubectl version`:

```
$ kubectl version

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

**I tried:**

The tiller version is 2.14.1. So, upgraded the helm client from 2.11.0 to the version 2.14.1. But that doesn't solves the issue.

**Comment by bacongobbler** [comment]
Are you able to use `kubectl port-forward`? Under the hood, Helm starts a `kubectl port-forward` tunneled connection to Tiller. That error typically indicates that the kubernetes API server cannot handle that type of request.

**Comment by bacongobbler** [comment]
See also https://github.com/helm/helm/issues/1455.

**Comment by AnjanaAK** [comment]
> Are you able to use `kubectl port-forward`? Under the hood, Helm starts a `kubectl port-forward` tunneled connection to Tiller. That error typically indicates that the kubernetes API server cannot handle that type of request.

No. I am not able to do a port-forward. It gives the same error.

**Comment by bacongobbler** [comment]
Okay, so something about your Kubernetes cluster's setup is causing that part of the API to fail, resulting in the error. There's not much help we can do here in this situation unfortunately. I would file a support ticket upstream with Kubernetes to see how to resolve your issue. Once the `kubectl port-forward` APIs work for you, Helm should work again.

Because there's no action item for us to take here, I'm going to close this. Thanks!
