### ISSUE TITLE
how to pass chart version from father chart to sub chart

### ISSUE THREAD

**Issue by dorsany** [helm/helm#5984]
There is any way to pass the ```.Chart.version``` from the father chart to my sub chart?
if i'm using in my sub chart inside one of the templates using the variable ```{{ .Chart.Version }}``` I'm getting the Chart version of my sub chart and not of my father chart.
I'm trying to avoid from using a **global** variable with a static version

Output of `helm version`:
v2.14.1

Output of `kubectl version`:
v1.14.3

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
on premise

**Comment by mattfarina** [comment]
I don't believe the information on the parent is currently available.

What is it you're trying to do?

**Comment by dorsany** [comment]
I have a pod which deploy another helm chart that based on the version of the parent chart

**Comment by mattfarina** [comment]
@dorsany I think you will need to pass that in yourself. It is not automatically available.

**Comment by dorsany** [comment]
Got it. Thanks
