### ISSUE TITLE
Getting "can't evaluate field connectors in type interface {}" when using multiple exists check condition using "and"

### ISSUE THREAD

**Issue by imohamedibrahim** [helm/helm#5986]
Hi,
    my values.yaml looks something like this.
```
---
key: 
   key1:
      key2: "value"

```
and my condition looks like :
```
{{- if and .Values.key .Values.key.key1 .Values.key.key1.key2 }}
{{  .Values.key.key1.key2 }}
{{ end }}
```
and this works with above values.yaml 
but when my values.yaml looks like : 
```
---
key:
   key1:
```

"can't evaluate field key2 in interface {}." -> this is the error when tried.
And i tried with multiple if check and it works as expected don't understand why "and" fails here.
i used helm template command to test this.

**Comment by mattfarina** [comment]
For the YAML there is no schema. So, `key2` is entirely unknown. There is no `key2` to be evaluated by the [golang builtin and function](https://golang.org/pkg/text/template/#hdr-Functions). You might need to create a default value when there isn't one or use a different check like empty. See https://masterminds.github.io/sprig/defaults.html

Does this help?

**Comment by imohamedibrahim** [comment]
yes @mattfarina thanks for your explanation.

**Comment by hickeyma** [comment]
Closing as issue is resolved.
