### ISSUE TITLE
Deploy 2 different k8s services 

### ISSUE THREAD

**Issue by beinnova** [helm/helm#5987]
I don't know if this place is the right place to make a question. In case, sorry about that.

I am trying to deploy 2 different services for the same application. The application has got 2 different containers and needs 2 services the 1st as `ClusterIP` and the 2nd as `LoadBalancer`.

Now what I tried so far is to add the second template spec to the `service.yaml` file using an `if`statement and also adding a second file named `public-svc.yml` into the `templates/` folder.
Running ` helm upgrade --debug --install --dry-run <projectName> ./ --set namespace=<namespace>` I can see just one services handled by tiller. Am I doing something wrong?

Thanks in advance

**Comment by mattfarina** [comment]
A chart can contain multiple services. You can use multiple files with a different service in each file. You don't need an if statement unless you have logic that would call for an if. If you want both services deployed all the time you can just include them.

**Comment by beinnova** [comment]
Thanks, @mattfarina for the quick reply. I'll give it a try.
