### ISSUE TITLE
lint vs lint --strict confusing

### ISSUE THREAD

**Issue by schollii** [helm/helm#5992]
Output of `helm version`:

2.11.0

I created a chart and wanted to find out if any of my templates were referring to non-existing values (due to typos). So after I created the chart, I purposely created a typo reference via `{{ .Values.someMap.doesNotExist` and ran helm lint: 
```
helm create test-chart
edit values.yaml etc to create someMap but not someMap.doesNotExist
helm lint 
```
This showed no error: 
```
==> Linting test-application/
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, no failures
```

Then I tried 
```
helm lint --strict  # 
```
and this failed because nameOverride and fullnameOverride are not defined in the values.yaml, because they are used in the `_helpers.tpl`:
```
==> Linting test-application/
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: render error in "test-application/templates/service.yaml": template: test-application/templates/service.yaml:6:31: executing "test-application/templates/service.yaml" at <include "chart.name"...>: error calling include: template: test-application/templates/_helpers.tpl:6:31: executing "chart.name" at <.Values.nameOverride>: map has no entry for key "nameOverride"

Error: 1 chart(s) linted, 1 chart(s) failed
```
Then once I define nameOverride and fullnameOverride the above error disappears and finally the missing key that I purposely referenced in the template causes error: 
```
==> Linting test-application/
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: render error in "test-application/templates/deployment.yaml": template: test-application/templates/deployment.yaml:43:29: executing "test-application/templates/deployment.yaml" at <.Values.http.apiUrl2>: map has no entry for key "apiUrl2"
```
Frankly this is a bit of a mess: 
- firstly there should at least be a warning if keys are not defined, even without strict
- secondly, it doesn't make sense that strict causes failure on the nameOverride and fullnameOverride because there was no warning on those without strict mode
- nameOverride and fullnameOverride should only be needed if the chart name is not defined, therefore they should not cause error even in strict mode since the chart name is defined

I think this behavior is confusing. When I lint source code, I expect that potential problems are warned, and errors show up as errors, and that strict mode would cause warnings to be interpreted as errors. New errors can appear, but not of the sort that should have been warnings (missing keys).

**Comment by hickeyma** [comment]
I agree that there are issues around the 'linting'.  Do you feel like writing a PR to fix this?

**Comment by technosophos** [comment]
This has been changed in Helm 3, but we do not plan on porting the feature to Helm 2 (which is now in bugfix-only mode). I am marking this as closed.

**Comment by schollii** [comment]
Thanks for info that's fine. I will try it in helm 3 to see what looks like there.
