### ISSUE TITLE
helm3: upgrade command does not apply changes 

### ISSUE THREAD

**Issue by ivanfoo** [helm/helm#5993]
Hi there,

We think we've found a big issue while testing helm3. The install command works fine (so far) but the upgrade one is not working properly. Changes made directly to the templates are correctly applied, but modifying parameters into the `values.yaml` file or via `--set` does not take any effect. The template command is working fine, so maybe is some kind of misbehaviour in the parameters preference (?).

**Comment by bacongobbler** [comment]
Are you testing against the latest commit in dev-v3? At first glance this seems like a duplicate of #5792.

**Comment by ivanfoo** [comment]
hey @bacongobbler probably not, let me check if it works fine with the last commit

**Comment by ivanfoo** [comment]
As you said, everything works fine with the last commits. I'm closing this.

Sorry!
