### ISSUE TITLE
About Helm controller and crd

### ISSUE THREAD

**Issue by hangyan** [helm/helm#5994]
Hello, This is a proposal about Helm Controller and the CRDs.

We have implement an example Controller based on the Helm3 code (with a little modification) and define the HelmRequest and Release crd. Here is an example HelmRequest crd

```yaml
apiVersion: app.<group>/v1alpha1
kind: HelmRequest
metadata:
  name: jenkins
  namespace: default
spec:
  chart: in/jenkins
  clusterName: ""
  namespace: h8
  dependencies:
  - nginx
  values:
  - global.namespace=h8
  - aaa=aaa
  version: v2.0-b.3
```

A few notes:
1. most of the spec field is similar to helm cli, for example namespace/chart/values...
2. repo info is stored in a configmap, same format as helm
3. support ClusterRegisty. If clusterName == "", install to the current cluster
4. support a loosely dependencies,  the HelmRequest in  the dependency list will be checked first before install this HelmRequest

Also there is a Release CRD, here is an example:

```yaml
apiVersion: app.<group>/v1alpha1
kind: Release
metadata:
  creationTimestamp: "2019-07-09T07:37:25Z"
  generation: 2
  labels:
    modifiedAt: "1562657845"
    name: dex
    owner: helm
    status: deployed
    version: "1"
  name: dex.v1
  namespace: f10
  resourceVersion: "5519337"
  selfLink: /apis/app.alauda.io/v1alpha1/namespaces/f10/releases/dex.v1
  uid: 6579313f-a21c-11e9-8b67-525400488bfd
spec:
  chartData: <data>
  configData: <data>
  hooksData: <data>
  manifestData: <data>
  name: dex
  version: 1
status:
  Description: Install complete
  deleted: null
  first_deployed: "2019-07-09T07:37:25Z"
  last_deployed: "2019-07-09T07:37:25Z"
  notes: |
    1. Get the application URL by running these commands:
  status: deployed
```

It contains all the information in the old ConfigMap or Secret format , but use separate fields and move some field to status.

The controller we created use helm3 code as a library, besides it, it's a standard controller-manager with webhooks.  i think it's the right direction.

We are considering to open source all the implements and want hear suggestions from the maintainer team and all the developers. Hope our work will help the community

**Comment by mattfarina** [comment]
@hangyan Thanks for reaching out. Would you be interested in demoing this at a [Helm Developer Call](https://github.com/helm/community/blob/master/communication.md#meetings).

If you do make something readily available we have a related projects page this could be listed on at https://helm.sh/docs/related/

I know weaveworks has done some work in this space. I'm not sure. Are you aware of their work? It might be a good place for inspiration, collaboration, or just a way to know what else is out there.

**Comment by hangyan** [comment]
@mattfarina Thanks for you response.  Love to demo it at the developer call. I have checked the schedule and it seems like it's only a few hours left, i will do some preparing before the demo.

We will discuss about open source as soon as possible,  it also require a lot of documenting work.

I haven't heard about from weaveworks's work. But i will check out, surely  we can learn from each other and get some great inspiration.

**Comment by hangyan** [comment]
@mattfarina Sorry to bother you, i have check the meeting time, it's 12:30 wed in Beijing Time, But nobody is online, is the meeting delayed or something?

**Comment by mattfarina** [comment]
@hangyan checkout https://github.com/fluxcd

You don't need to feel pressure to demo this week. This is a regular meeting. You can demo in the future.

**Comment by hangyan** [comment]
@mattfarina  It's ok, i cal the local time wrong..  I will check out the fluxcd project.

**Comment by hangyan** [comment]
I'm on the meeting. Still no one?

**Comment by bacongobbler** [comment]
The meeting was at 9:30AM Pacific Standard.

**Comment by hangyan** [comment]
@bacongobbler I have check to local time is Friday 12:30AM in Beijing, am i cal wrong  again ?

**Comment by hickeyma** [comment]
@hangyan I think the time would be 01:30 am Friday (Beijing)

**Comment by hangyan** [comment]
Yes ,that make more senses. But i didn't know why google give me that answer.

**Comment by hickeyma** [comment]
Possibly didn't take daylight savings into account?

**Comment by hangyan** [comment]
Thanks for pointing it out. Didn't familiar with that before... Guess it will be next week.

**Comment by hangyan** [comment]
Guess i have missed the meeting again, it should be 0:30 am Friday in my local time (Beijing)...Sorry guys, next week...

**Comment by hangyan** [comment]
https://github.com/alauda/captain

I have upload the codes and add some intro docs,  it's welcome you guys can give some thoughts about it

@mattfarina how can add this project to this page https://helm.sh/docs/related/ ?

**Comment by bacongobbler** [comment]
Make a PR against https://github.com/helm/helm/blob/master/docs/related.md

**Comment by hangyan** [comment]
@bacongobbler Ok, thanks very much

**Comment by bacongobbler** [comment]
@hangyan just noticed this was a helm 3 related project. Please check my edit above^

**Comment by hangyan** [comment]
@bacongobbler OK, thanks
