### ISSUE TITLE
Loosing sync

### ISSUE THREAD

**Issue by whyvez** [helm/helm#5995]
I'm using helm in tillerless mode using the `helm-tiller` and in some cases losing sync with my releases. I can see a release in Minikube via k9s but `helm list` doesn't return any releases. 

Where is tiller state saved?

Any suggestions on how I could either troubleshoot this or fix the issue altogether?

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T18:55:03Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Minikube

**Comment by hickeyma** [comment]
I would suggest opening an issues in [Tillerless Helm](https://github.com/rimusz/helm-tiller) as it is independent of Helm.

[How Helm Uses ConfigMaps to Store Data](http://technosophos.com/2017/03/23/how-helm-uses-configmaps-to-store-data.html) provides detailed information on Helm state.

**Comment by hickeyma** [comment]
Closing as Tillerless helm issue.
