### ISSUE TITLE
helm list revision duplicates.

### ISSUE THREAD

**Issue by sboishtyan** [helm/helm#5996]
Output of `helm version`:
{Client: &version.Version{SemVer:"v2.10+unreleased", GitCommit:"118896b07d48cd064fac0a3f0ac902c0b83050c2", GitTreeState:"clean"}
{Server: &version.Version{SemVer:"v2.10+unreleased", GitCommit:"633faf3f74eb961265d5b3687c3e843c2c2ed1ae", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.11", GitCommit:"1df6a8381669a6c753f79cb31ca2e3d57ee7c8a3", GitTreeState:"clean", BuildDate:"2018-04-05T17:16:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

Hello, I have a question.
I made  ```helm ls --output json --date --all -m 100 'avito-site-[a-z]+-'``` 
 last items in output are same.
`{"Name":"name","Revision":1,"Updated":"Mon Jul  8 05:57:03 2019","Status":"DEPLOYED","Chart":"chart","AppVersion":"","Namespace":"namespace"},`
`{"Name":"name","Revision":1,"Updated":"Mon Jul  8 05:57:03 2019","Status":"DEPLOYED","Chart":"chart","AppVersion":"","Namespace":"namespace"}]}'`

Does it normal behavior? What can affect the output to contain duplicates?

**Comment by hickeyma** [comment]
@sboishtyan That seems peculiar and a duplicate as you mentioned.

I have been unable to reproduce using the latest ode in master. Investigation as follows:

```console
$ helm ls --output json --date --all 
{"Next":"","Releases":[{"Name":"mychart","Revision":2,"Updated":"Tue Jul  9 14:36:12 2019","Status":"DEPLOYED","Chart":"mychart-0.1.0","AppVersion":"1.0","Namespace":"default"},{"Name":"chrt-5996","Revision":1,"Updated":"Tue Jul  9 14:37:03 2019","Status":"DEPLOYED","Chart":"chrt-5996-0.1.0","AppVersion":"1.0","Namespace":"default"}]}

$ helm ls
NAME     	REVISION	UPDATED                 	STATUS  	CHART          	APP VERSION	NAMESPACE
chrt-5996	1       	Tue Jul  9 14:37:03 2019	DEPLOYED	chrt-5996-0.1.0	1.0        	default  
mychart  	2       	Tue Jul  9 14:36:12 2019	DEPLOYED	mychart-0.1.0  	1.0        	default 

$ helm version
Client: &version.Version{SemVer:"v2.14+unreleased", GitCommit:"4cbbd1046a97ab437425565006bfb85e3d9cdb01", GitTreeState:"clean"}
Server: &version.Version{SemVer:"canary+unreleased", GitCommit:"66d71811e843dce325feeda0a98d528fd425f92f", GitTreeState:"clean"}
```
Would you be able to upgrade to the latest version of Helm `2.14.1` and see if the issue can be reproduced then?

**Comment by sboishtyan** [comment]
> @sboishtyan That seems peculiar and a duplicate as you mentioned.
> 
> I have been unable to reproduce using the latest ode in master. Investigation as follows:
> 
> ```
> $ helm ls --output json --date --all 
> {"Next":"","Releases":[{"Name":"mychart","Revision":2,"Updated":"Tue Jul  9 14:36:12 2019","Status":"DEPLOYED","Chart":"mychart-0.1.0","AppVersion":"1.0","Namespace":"default"},{"Name":"chrt-5996","Revision":1,"Updated":"Tue Jul  9 14:37:03 2019","Status":"DEPLOYED","Chart":"chrt-5996-0.1.0","AppVersion":"1.0","Namespace":"default"}]}
> 
> $ helm ls
> NAME     	REVISION	UPDATED                 	STATUS  	CHART          	APP VERSION	NAMESPACE
> chrt-5996	1       	Tue Jul  9 14:37:03 2019	DEPLOYED	chrt-5996-0.1.0	1.0        	default  
> mychart  	2       	Tue Jul  9 14:36:12 2019	DEPLOYED	mychart-0.1.0  	1.0        	default 
> 
> $ helm version
> Client: &version.Version{SemVer:"v2.14+unreleased", GitCommit:"4cbbd1046a97ab437425565006bfb85e3d9cdb01", GitTreeState:"clean"}
> Server: &version.Version{SemVer:"canary+unreleased", GitCommit:"66d71811e843dce325feeda0a98d528fd425f92f", GitTreeState:"clean"}
> ```
> 
> Would you be able to upgrade to the latest version of Helm `2.14.1` and see if the issue can be reproduced then?

I can't upgrade helm now. I realized that behavior seems peculiar and happens not in 100%.
All I want to know that behavior is wrong. And I need an update or ad-hoc this before the update.

**Comment by hickeyma** [comment]
Ok, understand. Behaviour seems wrong.
