### ISSUE TITLE
Context Deadline Exceeded Errors when using helm with TLS

### ISSUE THREAD

**Issue by aaronmell** [helm/helm#5997]
After enabled TLS, we are getting random Context Deadline Exceeded Errors. No information in the logs that would help us track down the error either.

Output of `helm version`:
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:19Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-eks-d69f1b", GitCommit:"d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7", GitTreeState:"clean", BuildDate:"2019-02-28T20:26:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
EKS

**Comment by mattfarina** [comment]
Have you tried using the `--debug` flag to get verbose output? Can you share those logs?

**Comment by nerz** [comment]
I'm currently seeing a similar issue on AKS. I have done some troubleshooting as a result and have narrowed it down to the TLS verification. 

When setting the `--tiller-tls-verify` flag I am unable to execute any helm commands such as `helm ls --tls`. Regardless of the command I am seeing the same error (**Error: context deadline exceeded**). When running `--debug ` flag, I am not seeing any useful output such as an issue with the verification of TLS certificates..etc

I am able to get Helm/Tiller TLS working without the `--tiller-tls-verify` flag and have confirmed it is not networking related.

**Error:**

`helm ls \                                                                 
    --tls \
    --tls-ca-cert ca.cert.pem \
    --tls-cert helm.cert.pem \
    --tls-key helm.key.pem \
    --debug
[debug] Created tunnel using local port: '63297'

[debug] SERVER: "127.0.0.1:63297"

[debug] Host="", Key="helm.key.pem", Cert="helm.cert.pem", CA="ca.cert.pem"

Error: context deadline exceeded` 

**Certificate Creation**
- For testing purposes I followed Helm doc: https://helm.sh/docs/using_helm/#using-ssl-between-helm-and-tiller

`openssl verify -CAfile ca.cert.pem tiller.cert.pem
tiller.cert.pem: OK`

`openssl verify -CAfile ca.cert.pem helm.cert.pem
helm.cert.pem: OK`

**General Info for debugging purposes:**
- Tiller is deployed successfully with no errors or issues (as far as I can tell)

**Kubernetes Version**: 1.13.5
**Helm/Tiller Version**: v2.14.1

`kubectl get deployment tiller-deploy -n kube-system                  
NAME            DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
tiller-deploy   1         1         1            1           1h`

`kubectl -n kube-system describe pod tiller-deploy-7b45545f56-l8jh4
Name:               tiller-deploy-7b45545f56-l8jh4
Namespace:          kube-system
Priority:           0
PriorityClassName:  <none>
Node:               aks-agentpool-11466683-1/10.100.2.35
Start Time:         Thu, 11 Jul 2019 09:54:42 -0400
Labels:             app=helm
                    name=tiller
                    pod-template-hash=7b45545f56
Annotations:        <none>
Status:             Running
IP:                 10.100.2.58
Controlled By:      ReplicaSet/tiller-deploy-7b45545f56
Containers:
  tiller:
    Container ID:   docker://757e39981fb4e3fbbd333d6845eb2c61ec52dc55ec5b28023ed5d61d2fd59048
    Image:          gcr.io/kubernetes-helm/tiller:v2.14.1
    Image ID:       docker-pullable://gcr.io/kubernetes-helm/tiller@sha256:f8002b91997fdc2c15a9c2aa994bea117b5b1683933f3144369862f0883c3c42
    Ports:          44134/TCP, 44135/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Running
      Started:      Thu, 11 Jul 2019 09:54:43 -0400
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:44135/liveness delay=1s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:44135/readiness delay=1s timeout=1s period=10s #success=1 #failure=3
    Environment:
      TILLER_NAMESPACE:    kube-system
      TILLER_HISTORY_MAX:  0
      TILLER_TLS_VERIFY:   1
      TILLER_TLS_ENABLE:   1
      TILLER_TLS_CERTS:    /etc/certs
    Mounts:
      /etc/certs from tiller-certs (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from tiller-token-g2wwv (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  tiller-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  tiller-secret
    Optional:    false
  tiller-token-g2wwv:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  tiller-token-g2wwv
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age   From                               Message
  ----    ------     ----  ----                               -------
  Normal  Scheduled  37m   default-scheduler                  Successfully assigned kube-system/tiller-deploy-7b45545f56-l8jh4 to aks-agentpool-11466683-1
  Normal  Pulled     37m   kubelet, aks-agentpool-11466683-1  Container image "gcr.io/kubernetes-helm/tiller:v2.14.1" already present on machine
  Normal  Created    37m   kubelet, aks-agentpool-11466683-1  Created container
  Normal  Started    37m   kubelet, aks-agentpool-11466683-1  Started container`

`kubectl logs tiller-deploy-7b45545f56-l8jh4 -n kube-system
[main] 2019/07/11 13:54:43 Starting Tiller v2.14.1 (tls=true)
[main] 2019/07/11 13:54:43 GRPC listening on :44134
[main] 2019/07/11 13:54:43 Probes listening on :44135
[main] 2019/07/11 13:54:43 Storage driver is ConfigMap
[main] 2019/07/11 13:54:43 Max history per release is 0`

Any assistance in troubleshooting this further would be greatly appreciated!

**Comment by aaronmell** [comment]
It looks like its blowing up most of the time when I call this method.
res, err := client.ReleaseContent(name)

**Comment by gnagel** [comment]
@nerz Did you find any fix for the `context deadline exceeded` error:

**Comment by reco** [comment]
i have the same issue.

**Comment by Swaagie** [comment]
For me setting `export HELM_TLS_ENABLE=true` was required to get helm provide the certificates. Even though it was already getting `HELM_TLS_CA_CERT`, `HELM_TLS_CERT` and `HELM_TLS_KEY`. Not sure what the CLI flag equivalents are...

Helm version: `v2.14.2`

**Comment by vzabawski** [comment]
I have those env variables set, but it doesn't help.
```
/usr/src/app $ env | grep HELM
HELM_TLS_ENABLE=true
HELM_HOME=/tmp/.helm
HELM_TLS_KEY=/usr/src/app/helm_tls_key.pem
HELM_TLS_VERIFY=true
HELM_TLS_HOSTNAME=tiller
HELM_TLS_CA_CERT=/usr/src/app/helm_tls_ca_cert.pem
HELM_TLS_CERT=/usr/src/app/helm_tls_cert.pem
```

**Comment by bacongobbler** [comment]
We are no longer accepting bug fixes for Helm 2. See https://helm.sh/blog/helm-v2-deprecation-timeline/ for more details.
