### ISSUE TITLE
deployment failed while deploying to kuberntes

### ISSUE THREAD

**Issue by eumoh1601** [helm/helm#6003]
error gotten when i tried to deploy a service fails at deployment to Kubernetes through Jenkins CI/CD:
Error: Get https://46FD186CCDF8FB42C11F1F7A6A72B7F8.sk1.eu-west-1.eks.amazonaws.com/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: dial tcp: lookup 46FD186CCDF8FB42C11F1F7A6A72B7F8.sk1.eu-west-1.eks.amazonaws.com on 172.20.0.2:53: no such host
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

ERROR: script returned exit code 1
Finished: FAILURE

Output of `helm ### version`:
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.12", GitCommit:"c757b93cf034d49af3a3b8ecee3b9639a7a11df7", GitTreeState:"clean", BuildDate:"2018-12-19T11:16:52Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.12", GitCommit:"c757b93cf034d49af3a3b8ecee3b9639a7a11df7", GitTreeState:"clean", BuildDate:"2018-12-19T11:04:29Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS/kubernetes

**Comment by hickeyma** [comment]
@eumoh1601 This seems to imply that there is a connection issue to the cluster. Is there a way you can troubleshoot the connection to the cluster? Can you run the deployment manually? Can you run any `kubectl` commands against the cluster?

Trying to narrow down where the issue might be.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
