### ISSUE TITLE
Why Helm release name is a DNS label with max length of 53 characters?

### ISSUE THREAD

**Issue by stevebail** [helm/helm#6006]
Helm documentation states the following:
-1) (k8s) metadata.name is restricted to a maximum length of 63 characters because of limitations to the DNS system
-2) For that reasons, release names are (DNS labels that are) limited to 53 characters

Statement 1) is not correct. 
k8s does not impose a max length of 63 characters on resource names.
The actual max length for a resource name is 253 characters. 
The k8s resource name is in fact a DNS subdomain (that can be made of one or more DNS labels).

Should we make the release name a DNS subdomain?

**Comment by bacongobbler** [comment]
Long ago Kubernetes service names were restricted to 53 characters. More recent versions of Kubernetes allow longer service names, though there was a time that some users were using the older version of Kubernetes so we couldn't relax the constraint. We can probably relax that constraint now.

**Comment by valoricDe** [comment]
Which parts would have to be updated to relax the constrain?

**Comment by JacobHayes** [comment]
Not sure if much has changed since https://github.com/helm/helm/pull/1560, but looks like that bumped it last time.

**Comment by brunohms** [comment]
@bacongobbler shouldn't helm be up to 63 characters as weel?

**Comment by brunohms** [comment]
@bacongobbler shouldn't helm be up to 63 characters as weel?

Because when a chart is create it limits to 63 characters in the `_helpers.tpl` file.

**Comment by bacongobbler** [comment]
See the comment in the code linked above.

> // As of Kubernetes 1.4, the max limit on a name is 63 chars. We reserve 10 for 
> // charts to add data. Effectively, that gives us 53 chars. 
> // See https://github.com/helm/helm/issues/1528

**Comment by vaibhav-si** [comment]
We upgraded to Helm3 but now helm render fails with "release name exceeds max length of 53" error. What is the resolution here? Is Helm planning to increase the character limit?

**Comment by tomcruise81** [comment]
It's not perfect, but we run our release names through a little bash function ahead of time:
```bash
function normalizeHelmReleaseName {
    # See https://github.com/helm/helm/issues/6006#issuecomment-553184466
    if [ ${#1} -gt 53 ]; then
        printf "%s-%s" $(echo -n $1 | cut -c -44) $(echo -n $1 | sha256sum | cut -c -8)
    else
        echo -n $1
    fi
}
```

**Comment by bacongobbler** [comment]
@vaibhav-si we'd welcome PRs to increase the character limit. It's open source! Feel free to contribute.

**Comment by vaibhav-si** [comment]
@bacongobbler I would love to contribute, is there a documented process for contributing? How does the build system work?

**Comment by bacongobbler** [comment]
https://helm.sh/docs/community/developers/

https://github.com/helm/helm/blob/master/CONTRIBUTING.md

**Comment by damodhar22** [comment]
> See the comment in the code linked above.
> 
> > // As of Kubernetes 1.4, the max limit on a name is 63 chars. We reserve 10 for
> > // charts to add data. Effectively, that gives us 53 chars.
> > // See #1528

What is the rationale behind choosing 53 chars for release_name and 10 for chart data

With recent versions of kubernetes supporting 253 characters what should be this ratio now?

**Comment by damodhar22** [comment]
> > See the comment in the code linked above.
> > > // As of Kubernetes 1.4, the max limit on a name is 63 chars. We reserve 10 for
> > > // charts to add data. Effectively, that gives us 53 chars.
> > > // See #1528
> 
> What is the rationale behind choosing 53 chars for release_name and 10 for chart data
> 
> With recent versions of kubernetes supporting 253 characters what should be this ratio now?

@bacongobbler  could you answer this?

**Comment by bacongobbler** [comment]
I think I already answered that question earlier in the thread. https://github.com/helm/helm/issues/6006#issuecomment-510226509

**Comment by renatosuero** [comment]
hi @bacongobbler I'd love to fix that as my first PR here. The goal is change to 243 and keep 10 for chart data,right ?

**Comment by bacongobbler** [comment]
Just to be sure, I would advise doing some testing (and some digging to make sure that assumption still holds true). But assuming that works, then yes, bumping the release name maximum character length to 243 characters should be fine.

**Comment by hickeyma** [comment]
@renatosuero It seems to be 253 alright: https://kubernetes.io/docs/concepts/overview/working-with-objects/names

You would need to take into account that a release is stored as a Secret/ConfigMap in the cluster with the following nomenclature for its name: `sh.helm.release.v1.<release_name>.v1`. This means then it would be 253 -22 (prefix + postfix of name) = 231 characters

**Comment by renatosuero** [comment]
@hickeyma  thanks, I was checking the kubernetes repository and I found that.  
https://github.com/kubernetes/kubernetes/blob/cfc845be63e88451779d209ecebbed81af54cdfa/staging/src/k8s.io/apimachinery/pkg/labels/selector_test.go#L321

https://github.com/kubernetes/kubernetes/blob/aadaa5d6a917fcb354bce80a0bd1830c95cfbcc3/staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go#L202

**Comment by kmindi** [comment]
Pull Request to fix this, is still open. Would really be great to move away from this no longer existing limitation.

**Comment by bacongobbler** [comment]
We’ve been waiting on action from the author on writing up some tests since last month, so if someone wants to go and try to move the work ahead please feel free. But yes, once this is squared away we can remove this limitation.

**Comment by renatosuero** [comment]
Sorry I'm a bit busy the last weeks :( I need first see how k8s to do the tests, so I don't know when I'd finish it :(

**Comment by Stolarskis** [comment]
@bacongobbler I can work on the k8s infrastructure tests assuming @renatosuero is still busy.

**Comment by renatosuero** [comment]
thank you very much @Stolarskis

**Comment by Stolarskis** [comment]
Hi guys! In order to test this, my plan was to use [terratest](https://github.com/gruntwork-io/terratest) to spin up a helm chart that creates some resources using a release name that is 231 characters long. Do you think this would adequately test this change? Or does helm have its own way of running tests such as this?

Couple other questions:

- Where would we store terratests in the helm codebase?
- In the helm docs it says that for helm 3.4.x the oldest version of k8s we support is 1.16.x. Is this the oldest version of k8s you want this change to be tested against?

**Comment by bacongobbler** [comment]
I would suggest using the pre-existing unit tests to validate against Kubernetes' validation suite. Specifically have a look at [pkg/kube/client_test.go](https://github.com/helm/helm/blob/master/pkg/kube/client_test.go) on how Helm validates using the `fakeHTTPClient` from `k8s.io/client-go/rest/fake`. If that isn't possible, there is also the [acceptance-testing](https://github.com/helm/acceptance-testing) project.

**Comment by bacongobbler** [comment]
[pkg/action/install_test.go](https://github.com/helm/helm/blob/master/pkg/action/install_test.go) might be another place well worth looking into.

**Comment by Stolarskis** [comment]
Hey guys! Sorry for the delay, holidays are super busy. Heres what I found!

## Findings Summary

Services have a max of 63 characters for the name attribute. Changing the max release name value will not work if the release name is included in the service name.

To verify this, I wrote some tests [you can view here!](https://github.com/Stolarskis/helm/tree/update-name-max-length)

## Kubernetes Live Tests
In kube/client_test.go, I found some live tests that run requests against a live cluster. Using those tests as an example I created a couple tests that attempt to create a few resources on a local cluster (I used minikube). The version of which is below.

`Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}`

The tests operate by attempting to create a list of resources, each with a metadata:name field that is 231 characters.

### Test Results

Service was unable to be created and the following error message was given.

`--- FAIL: TestRealMaxResourceName (0.02s)
    client_test.go:355: Service "xvl..." is invalid: metadata.name: Invalid value: "xvl...": must be no more than 63 characters`

The other three resources tests (list below) were created successfully!

**Resources tested**
---

- Deployment
- Service
- Config Map
- Secret

---
If anyone would like to know anything else, let me know! Happy New Year!

**Comment by liuming-dev** [comment]
Could we make the max length of the release name a setting property to let user decide to set this value; If not set, default is 53.

I think this will meet the user's needs as well as keeping the backward compatibility.

**Comment by bacongobbler** [comment]
How is a user supposed to know what should be the release name length? Keep in mind that many users do not (or should not) understand the intervals of the chart, so you should not run with the assumption that the user immediately knows what the correct release name length may be.

**Comment by Shahard2** [comment]
Any solution for that ?

**Comment by usefree** [comment]
could someone reopen this issue or provide the solution?

**Comment by s-baier** [comment]
This issue is especially annoying, if you try to do ReviewOps on a Helm Chart via ArgoCD using an ApplicationSet.
... the max Name length for an Application is 253chars, following the K8s max name length.
That name will be used for the release, too -> Helm dies.

**Comment by dlipovetsky** [comment]
Kubernetes identifiers (e.g. name, label key) have restrictions.

When the Chart uses the Release name in some identifier, then a user of that Chart, by using a long enough release name, could cause that identifier to violate some restriction. That would likely be a surprise to the user, because only the Chart maintainers would know where the Release name is used. I think that helm maintainers were doing their best to shield Chart users from this problem.

If helm removes this restriction, the maintainers of each Chart will be responsible for shielding their users from this problem.

That seems like a reasonable responsibility for Chart maintainers to have. However, the responsibility would be new, and they would need sufficient time to prepare.

Helm could help Chart maintainers cope with the new responsibility by documenting some best practices of naming, i.e. when to use a Release name in identifiers, and how to transform it to conform to restrictions.

**Comment by kamaradclimber** [comment]
> Could we make the max length of the release name a setting property to let user decide to set this value; If not set, default is 53.
> 
> I think this will meet the user's needs as well as keeping the backward compatibility.

@dlipovetsky It seems the quoted suggestion could let a helm user be in control of that behavior. It would still encourage public charts maintainer to stay within 53 chars limits to stay compatible with default helm setup, while allowing individual helm users to adopt longer release name if it makes sense for them.

What do you think?

**Comment by dlipovetsky** [comment]
Sure. We can be less strict about the release name.

However, users need a way to validate that the names _derived_ by the chart are valid. I'm not sure helm does that at all today. It may just delegate to the Kubernetes API.

What happens if one of the resources produced by `helm install NAME CHART` has a derived name that's too long? If the install starts, but fails, that's a bad user experience.
