### ISSUE TITLE
Output of helm install --debug not on standard streams

### ISSUE THREAD

**Issue by Sylordis** [helm/helm#6009]
Hi,

I'm running on Debian 9. After running a `helm install mychart --dry-run --debug`, the output is not redirected on consistent streams:
Content of STDOUT:
```
[debug] Created tunnel using local port: '36103'

[debug] SERVER: "127.0.0.1:36103"

[debug] Original chart version: ""
[debug] CHART PATH: /code/myproject/helm-charts/mychart
```
Content of STDERR:
The actual files, operations and errors.

I think that everything which is not an error should be outputed on STDOUT, while all errors should be on STDERR.
Same goes for the exit status of the dry-run debug, which is always 1 (error), when it should be 0 when exiting with a successful dry-run (but I guess that's an another topic).

Cheers,

Output of `helm version`:
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2+coreos.0", GitCommit:"b427929b2982726eeb64e985bc1ebb41aaa5e095", GitTreeState:"clean", BuildDate:"2018-01-18T22:56:14Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Don't know.

**Comment by P1ng-W1n** [comment]
FYI - POSIX defines the standard error stream as "for writing diagnostic output". The GNU C standard library [1] defines it similarly as "used for error messages and diagnostics issued by the program"

[1] https://www.gnu.org/software/libc/manual/html_node/Standard-Streams.html

**Comment by Sylordis** [comment]
In that case shouldn't everything be printed on stderr and not one part on stdout and the other on stderr?

The second part of the message was more of a personal opinion/preference, that stderr should be used for actual important errors/problems.

**Comment by bacongobbler** [comment]
similar issue opened two weeks ago: https://github.com/helm/helm/issues/6461

We should take a look at making those debug messages displayed on stderr, as the output of `--debug` should be there. This should already be the case in Helm 3, but there may be some areas in Helm 2 where debug messages are accidentally displayed on stdout.

**Comment by pkleimann** [comment]
There are issues in the Azure pipelines tasks project that relate to this.
https://github.com/microsoft/azure-pipelines-tasks/issues/11414

Because someone has to solve this problem. Could you please get in contact with the Azure pipelines tasks team to discuss and resolve this?

**Comment by bacongobbler** [comment]
Closing for the same reasons stated in #6461. Helm’s following standard convention here. This is a bug with Azure pipelines triggering an error when something is rendered to stderr. Please follow up with them on how to handle this case properly.
