### ISSUE TITLE
Feature Request: JSON support for helm search

### ISSUE THREAD

**Issue by kbaegis** [helm/helm#6013]
Presently, json is not supported by helm-search. Would like to be able to parse json to select/list versions of a particular chart.

**Comment by prashantyadla** [comment]
@kbaegis I would like to take up this issue!

**Comment by prashantyadla** [comment]
helm search dashboard -v 1.7.1
instead of this do you want something like this?
helm search --json { name: "dashboard", "version": "1.7.1"} 
@kbaegis @bacongobbler

**Comment by bacongobbler** [comment]
No. This is a feature request for `helm search --output json`, in which the output is a JSON object rather than a table.

**Comment by artbegolli** [comment]
Picking this up if it isn't done yet.

**Comment by hickeyma** [comment]
@artbegolli AFIK, @prashantyadla is working on this.

**Comment by artbegolli** [comment]
Any update @prashantyadla?

**Comment by prashantyadla** [comment]
@artbegolli You can take it up. I'm not working on it anymore.

**Comment by ishankhare07** [comment]
what's the status of this issue?
If available i'd like to take it up

**Comment by artbegolli** [comment]
Work was done but helm 2 is not a priority with dev work being focused on helm 3 and therefore unable to test. This comment https://github.com/helm/helm/pull/6204#issuecomment-538075728 explains it fully. You could potentially raise a PR for this in helm 3.

**Comment by bacongobbler** [comment]
Output flags were refactored in Helm 3 since that PR was closed. This has been implemented in Helm 3. Closing!
