### ISSUE TITLE
Have a PGP KEYS file for release verification

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#6015]
Releases of Helm are PGP signed. But, anyone who tries to verify the signatures will have to hunt down the right keys. 

We should follow a model, like Apache, where the keys are readily available. [On the apache project there is a KEYS file with directions on using it ](https://www.apache.org/dev/release-signing.html#keys-policy)and the keys for those who have signed releases. It is easy to import and use. There is an [example file here](https://www.apache.org/dist/ant/KEYS).

We should adopt this method or a similar one to make verification easier.

/cc @hickeyma @bacongobbler @adamreese @technosophos

**Comment by technosophos** [comment]
Agree. I would like to just include the keys file in Git if there isn't a concern about some sort of Git-based attack. Option B might be to host it off of a Keybase web page.

**Comment by jkroepke** [comment]
From: https://www.apache.org/dev/release-signing.html#keys-policy
> Note: this system will be replaced by a better process in the near future. In preparation, please ensure that public keys are connected as strongly as possible to the Apache web of trust and are available from the major public key servers.


If you are using option A your keys should also on major pgp servers.

**Comment by mattfarina** [comment]
@technosophos might I suggest the KEYS file be at helm.sh/KEYS and get.helm.sh/KEYS for someone to fetch. Also, the keys themselves should be in a 3rd party system like keybase and the keyserver network

@jkroepke keybase is different from the keyservers. What are your thoughts on keybase?

**Comment by nce** [comment]
Well in the end we'd like a way to verify the releases. And in some way there is a manual step required in the verification process. 

If we get the keys manually from either git, keybase or helm.sh, we don't care. But i'd strongly recommend to put the keys on a public available keyserver, as it would be possible to automate the keysearch via gpg. And then it would be compliant (for us).
With Keys on 3rd Party Sites, we would be secure from a compromised git repo.

Thanks for your efforts!

**Comment by mattfarina** [comment]
Here's an outline of tasks that need to be accomplished:

- [ ] Create a KEYS file
- [ ] Put the KEYS file in get.helm.sh alongside downloads
- [ ] Have everyone who has signed a release put their public keys in the KEYS file and in the keyserver network
- [ ] In the maintainers guide document how to add a key to the KEYS file and put the key in the keyserver network
- [ ] Document, for consumers, how to verify a helm download with gpg (make it practical)
- [ ] Provide a get verified script (like linux does at https://git.kernel.org/pub/scm/linux/kernel/git/mricon/korg-helpers.git/tree/get-verified-tarball)

**Comment by mattfarina** [comment]
While the consumer docs and scripting to help still need to be written, the foundational pieces are in place. The KEYS are now available at https://get.helm.sh/KEYS and changes are tracked in the Helm git repo.

If anyone wants to start using this stuff now, even before the docs and the rest are in place feel free. If you encounter any issues please let us know.

**Comment by waveywaves** [comment]
> * [ ]  Document, for consumers, how to verify a helm download with gpg (make it practical)
> * [ ]  Provide a get verified script (like linux does at https://git.kernel.org/pub/scm/linux/kernel/git/mricon/korg-helpers.git/tree/get-verified-tarball)

Where does the documentation for this need to be given ?

**Comment by mattfarina** [comment]
@waveywaves Sorry I missed this until now. The docs need to be in the docs on the helm-www repo in the installation section. That's what produces the v3 docs on helm.sh.

**Comment by bacongobbler** [comment]
(it also needs to be under the `dev-v3-docs,` branch, not master)

**Comment by mattfarina** [comment]
Closing as the KEYS file now exists
