### ISSUE TITLE
Ability to duplicate an already installed helm release without the charts? (with different parameters)

### ISSUE THREAD

**Issue by arielb135** [helm/helm#6022]
My use case is as follows:

1. I'm deploying a helm application
2. in some point, the application is stressed, and it needs to be splitted between a duplicate of the helm application - so i want to run a helm install based on the previous chart (with maybe some other parameters).

is it possible to do it? does tiller save enough information to duplicate a deployment?

**Comment by hickeyma** [comment]
@arielb135 `helm rollback` would bring you back to the previous revision alright.  You could do the rollback and then upgrade with the chart version that you deployed the app before it became distressed?

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
