### ISSUE TITLE
Connecting to kubernetes cluster using helm go client

### ISSUE THREAD

**Issue by Saurabh-16** [helm/helm#6024]
I am using helm go client to install the release. The link is https://github.com/helm/helm/tree/55193089e67207363e6f448054113b5a36649d74/pkg/helm

What I didn't get , how can I give my kubeconfig file to this go client so that my client can communicate with the kubernetes cluster. I went through documentation but doesn't has the details on the same.

Is there any other way to connect to cluster from helm go client.

**Comment by thomastaylor312** [comment]
Unfortunately, Helm 2 is not the best to use as a library. You can see how Helm itself is setting things up here: https://github.com/helm/helm/blob/55193089e67207363e6f448054113b5a36649d74/cmd/helm/helm.go#L244

The actual place where the client is created is here: https://github.com/helm/helm/blob/55193089e67207363e6f448054113b5a36649d74/cmd/helm/helm.go#L329

**Comment by Saurabh-16** [comment]
@thomastaylor312 :- I tried using the functions you told in my go file . While I am able to set the path for kubeconfig and name for kubecontext  but after invoking (InstallRelease) https://github.com/helm/helm/blob/master/pkg/helm/client.go#L78 , I am facing an issue with message `'context deadline exceeded' .`

This is coming when a call to this method is invoked https://github.com/helm/helm/blob/a4b1d01283d3240912792ab10cd5782c4d406ad6/pkg/helm/client.go#L313

This method is invoked to create a `grpc connection with tiller` . As a parameter it expects 
 ctx context.Contex which is created internally as ctx := NewContext() (https://github.com/helm/helm/blob/a4b1d01283d3240912792ab10cd5782c4d406ad6/pkg/helm/option.go#L509)

I am not sure , what all settings I need to configure to make use of this particular helm go client.
Also how these test cases have been configured to execute. I mean how is connection establish to tiller. https://github.com/helm/helm/blob/master/pkg/helm/helm_test.go#L103

**Comment by DarkIsDude** [comment]
@Saurabh-16 I have an issue when I try to get dependency `go: finding k8s.io/cli-runtime v0.0.0`.

I think it's this one `"k8s.io/helm/pkg/helm/portforwarder"`

Here:
```
        tillerTunnel, err = portforwarder.New("kube-system", client, config)

	if err != nil {
		return "", err
	}
```

I use go module but maybe it's not the best one.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

**Comment by liuming-tech** [comment]
@Saurabh-16 see #6910
