### ISSUE TITLE
helm repo add sometimes hangs

### ISSUE THREAD

**Issue by imeredith** [helm/helm#6027]
Recently I have been having an issue with the command 

`helm repo add jenkinsx http://chartmuseum.jenkins-x.io` which is being run every time I start an app to make sure it is added I guess.

Probably 4/5 times this command never completes and I end up ctrl-c'ing. 1/5 of the time it completes in about a second. 

I'm using WSL2 to run Debian on windows which possibly is an issue. 

I'm not sure how to debug what is going on.

Thanks

Output of `helm version`:
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.7-gke.25", GitCommit:"d4c79083ab6dea5d26ef4ed8d50b145268349bc3", GitTreeState:"clean", BuildDate:"2019-06-22T16:10:31Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

**Comment by bacongobbler** [comment]
Are there connection issues to the repository? `helm repo add` makes a few GET requests to the server to fetch the index when `helm repo add` is invoked.

**Comment by imeredith** [comment]
I don't think so. I don't have any issues with anything else and I'm seeing this problem from 2 locations on different ISP's.

Is there a way to trace the GET requests?

**Comment by LeiYangGH** [comment]
I met the same issue.
Adding --debug and --tiller-connection-timeout didn't make any difference, there's no vorbose output(I 'm in gitlab ci).

**Comment by mdekoster** [comment]
I have the same thing on the WSL 2 (Windows build 18999). The command never completes. I have access to the outside world. I am able to curl https://helm.goharbor.io.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Please make sure to test with Helm 3 and see if this has been fixed in the latest release. Thanks!

**Comment by adamiprinciples** [comment]
I'm hitting the same issue with WSL2. Had to roll back to WSL1 and it works alright. Shame though as 2 is so much faster

**Comment by jpatokal** [comment]
I just hit this in Helm 3.  Worked fine when I retried though.  &lt;shrug/>

`
$ helm version
version.BuildInfo{Version:"v3.2.0-rc.1", GitCommit:"7bffac813db894e06d17bac91d14ea819b5c2310", GitTreeState:"clean",GoVersion:"go1.13.10"}
$ helm --debug repo add stable https://kubernetes-charts.storage.googleapis.com
`

**Comment by chilicat** [comment]
We use the command as part of an Ansible automation. It hangs 1 of ~15 times. After force killing the process, it works again.

Version:
```
version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

**Comment by lchdev** [comment]
I am also facing this issue, and I think it is probably linked to this WSL2 odd behavior: https://github.com/microsoft/WSL/issues/5806

I have not looked up in Helm source code, but could it be that Helm automatically uses all the servers from the ANSWER section of its DNS queries in a round robin fashion ? This would definitely explain the strange behavior observed when using Helm from WSL2.

**Comment by ibutler-compass** [comment]
We are also experiencing this issue as part of a CircleCI deployment.

**Comment by manugarri** [comment]
still happening with helm v3.9.0

**Comment by djeebus** [comment]
can confirm that, for me, the issue seemed to be related to the built-in dns server that WSL uses (mentioned in the issue linked by @lchdev). i swapped it in `/etc/resolv.conf` from 172.26.192.1 (in my case) to my local router, and now I can `helm dep up` consistently. not sure what value the WSL dns server plays, but everything currently seems to be fine.

**Comment by shadowyman** [comment]
Also having the same issue. --debug flag yields no additional logs. The command just hangs indefinitely.

**Comment by scoady** [comment]
also had an issue on WSL2. Changing resolvers to Google DNS (`8.8.8.8` and `8.8.4.4`) allowed for `helm repo update` to finish successfully.

**Comment by kayx23** [comment]
Struggling with a similar issue in a Debian VM on AWS when `helm repo add bitnami https://charts.bitnami.com/bitnami`. I cannot seem to add the repo anyhow. `--debug` yields no info. I have no issue adding other repos and my machine has access to the public internet.

helm version:

```
version.BuildInfo{Version:"v3.15.0-rc.2", GitCommit:"c4e37b39dbb341cb3f716220df9f9d306d123a58", GitTreeState:"clean", GoVersion:"go1.22.3"}
```
