### ISSUE TITLE
Feature proposal: add plugin source data to plugin environment

### ISSUE THREAD

**Issue by astorath** [helm/helm#6033]
### Problem:

1. I have forked some helm plugin project
2. To test it all over, I want to install a forked version from my own repository
3. Installation script (install/update hook) does not know, which source I'm using

So I have to alter the installation script to use my own repository and later revert it to make a pull request.

### Proposal:

Add two env variables to hook scripts:
* `HELM_PLUGIN_SOURCE` - plugin source path (as defined in install command), e.g.: `https://github.com/user/helm-plugin`
* `HELM_PLUGIN_SOURCE_TYPE` - type of plugin source, e.g.: `git`, `http`...

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
