### ISSUE TITLE
helm3 value.yaml ingress path is a string?

### ISSUE THREAD

**Issue by liuliqiang** [helm/helm#6037]
### Output of `helm version`:

```
helm version
version.BuildInfo{Version:"v3.0.0-alpha.1", GitCommit:"b9a54967f838723fe241172a6b94d18caf8bcdca", GitTreeState:"clean"}
```
### Output of `kubectl version`:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

### Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

- Cluster build with kubeadm

### Problem

Hello, In helm2，i found a pr https://github.com/helm/helm/pull/4703/files which change `ingress.path` in **value.yaml**  from a stirng to list，but in helm3-alpha，https://github.com/helm/helm/blob/dev-v3/pkg/chartutil/create.go#L101， it's also string，should it be changed?

**Comment by bacongobbler** [comment]
Yes, that would be a good patch to port over. Feel like patching that?

**Comment by liuliqiang** [comment]
@bacongobbler  i would like to do that, i will take a patch now.
