### ISSUE TITLE
helm install bash script with "--no-sudo" raises an error

### ISSUE THREAD

**Issue by mozai** [helm/helm#6040]
Helm version: n/a

Steps to reproduce:
- `[ $(id -u) != 0 ] && echo "I Am Not Root"`  #  I Am Not Root
- `curl -LO https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get`
- `chmod 0700 get`
- `./get -h`  # "[--no-sudo]  ->> install without sudo
- `./get --no-sudo`

Expected outcome:
Gets the appropriate "helm" binary for my OS and arch, puts it either in cwd or in the first writable dir in $PATH.  Or reminds me I must provide a destination path if I'm not root.

Seen outcome:
```
Downloading https://get.helm.sh/helm-vX.XX.X-linux-amd64.tar.gz
Preparing to install helm and tiller into /usr/local/bin
cp: cannot create regular file '/usr/local/bin/helm': Permission denied
Failed to install helm with the arguments provided: --no-sudo
```

If I can't use this without being root, why give the option not to use sudo?

Workaround:
- Get the url from the error message
- `cd $(mktemp -d)`
- `curl -L https://get.helm.sh/helm-vX.XX.X-linux-amd64.tar.gz |tar xz`
- copy ./\*/helm and ./\*/tiller to $HOME/.local/bin or wherever is appropriate for your workstation.

Something like this could work (please don't copy-paste this blindly)
```
OS=linux; ARCH=amd64; IFS=':' read -ra paths <<<"$PATH"; for PRG in helm tiller; do
dest=""; for p in ${paths[@]}; do cp "$OS-$ARCH/helm" $p/ && dest="$p/$PRG" && break ;
done; if [ "$dest" ]; then echo "$PRG copied to $dest"; else 
echo "$PRG could not be installed, find it in $(pwd)/$OS-$ARCH/$PRG"; fi; done
```

**Comment by bacongobbler** [comment]
https://github.com/helm/helm/pull/4649 was provided by a community member. If you can figure out the proper way to fix this, that'd be great.

You could also try [setting $USE_SUDO to "false"](https://github.com/helm/helm/blob/88bb48bc6f573e21909147792a16daad7665e45f/scripts/get#L23).

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

**Comment by CDSRV** [comment]
this version is slightly different:
https://github.com/CDSRV/runtime/blob/default/bin/setup/pkg/helm
- same handling of install directory depending on the privileges of the caller and HELM_INSTALL_DIR
- uses/defines HELM_VERSION
> the "version" is the semantic version itself, not including the prefix which is in the tag, eg: KEY=VALUE, not KEY=keyVALUE
- eliminates all input arg processing, since none are needed.

enjoy..

**Comment by mozai** [comment]
Reopen -- this is still a problem.
```
[moses@beatrice tmp]$ [ $(id -u) != 0 ] && echo "I Am Not Root"
I Am Not Root
[moses@beatrice tmp]$ curl -sLO https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get
[moses@beatrice tmp]$ chmod 0700 get
[moses@beatrice tmp]$ ./get --no-sudo
Downloading https://get.helm.sh/helm-v2.17.0-linux-amd64.tar.gz
Preparing to install helm and tiller into /usr/local/bin
cp: cannot create regular file '/usr/local/bin/helm': Permission denied
Failed to install helm with the arguments provided: --no-sudo
Accepted cli arguments are:
	[--help|-h ] ->> prints this help
	[--version|-v <desired_version>]
	e.g. --version v2.4.0  or -v latest
	[--no-sudo]  ->> install without sudo
	For support, go to https://github.com/helm/helm.
```
