### ISSUE TITLE
Error: validation failed: unable to recognize "": no matches for kind "Deployment" in version ""

### ISSUE THREAD

**Issue by rajeshaz203** [helm/helm#6043]
Output of `helm version`:
Client: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.8", GitCommit:"a89f8c11a5f4f132503edbc4918c98518fd504e3", GitTreeState:"clean", BuildDate:"2019-04-23T04:41:47Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS

Problem:
When i execute
helm install charts

i get the following error:
[debug] Created tunnel using local port: '51608'
[debug] SERVER: "127.0.0.1:51608"
[debug] Original chart version: ""
[debug] CHART PATH: C:\Users\akspoc\Downloads\SourceCode\develop-helm\akspoc\charts\akspoc
Error: validation failed: unable to recognize "": no matches for kind "Deployment" in version ""

Attaching my charts for reference
[charts.zip](https://github.com/helm/helm/files/3410579/charts.zip)

**Comment by bacongobbler** [comment]
There appears to be a hidden character in your backend.yaml file. Fix that and your chart should work.

Use this instead:
[charts.zip](https://github.com/helm/helm/files/3412665/charts.zip)

```
><> wget https://github.com/helm/helm/files/3412665/charts.zip
><> unzip charts.zip
><> helm install ./charts/akspoc/
NAME:   prodding-umbrellabird
LAST DEPLOYED: Fri Jul 19 13:39:48 2019
NAMESPACE: cert-manager
STATUS: DEPLOYED

RESOURCES:
==> v1/Deployment
NAME                READY  UP-TO-DATE  AVAILABLE  AGE
backend-deployment  0/1    1           0          0s

==> v1/Pod(related)
NAME                               READY  STATUS             RESTARTS  AGE
backend-deployment-674bb89f-5x4d6  0/1    ContainerCreating  0         0s

==> v1/Service
NAME             TYPE          CLUSTER-IP     EXTERNAL-IP  PORT(S)       AGE
backend-service  LoadBalancer  10.100.29.211  <pending>    80:31007/TCP  0s
```

**Comment by rajeshaz203** [comment]
Thanks its working now.
What was the hidden character in it and am keen to know how did you figured it out?
I am still figuring out the difference between backend.yaml files(one which i sent you and the one which you sent me back)
I compared the two files and I was not able to find any difference as such.

**Comment by bacongobbler** [comment]
Neither was I. `helm template` identified the indentation issue though.
