### ISSUE TITLE
helm should not urldecode urls

### ISSUE THREAD

**Issue by KnicKnic** [helm/helm#6048]
helm --debug repo add t7 "http://localhost/some%2Fpath/test"
Error: Looks like "http://localhost/some%2Fpath/test" is not a valid chart repository or cannot be reached: Failed to fetch http://localhost/some/path/test/index.yaml : 404 Not Found

notice how  "some%2Fpath" gets translated into "some/path"

This is not expected. It is expected that helm leaves the url alone and that "some%2Fpath" gets transferred to the server.

Output of `helm version`:
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

**Comment by karuppiah7890** [comment]
That's a weird URL. But yeah, bug's a bug 😅 I'm working on fixing this

**Comment by karuppiah7890** [comment]
This issue is also present in other versions of helm. I'm fixing it and adding tests for v2.11.0 (for which issue has been raised). I'll also do the same for v2.14.2 and v3

**Comment by karuppiah7890** [comment]
@KnicKnic we are fixing this in the `master` branch and it will get released in a patch version like - `v2.14.x` or in minor version `v2.15.0`

**Comment by bacongobbler** [comment]
I'll be in 2.15.0 - there's no plans to release a 2.14.x at this time. Patches are usually rolled into the next release. We reserve patch releases for when it's a significant bug that affects a large amount of the user base or a security release.

**Comment by hickeyma** [comment]
Closing as #6060 merged.
