### ISSUE TITLE
Incorrect error message "This command needs 2 arguments: release name, chart path"

### ISSUE THREAD

**Issue by suszig** [helm/helm#6058]
HELM version: 2.14.1
Cloud Provider:  AZURE DEVOPS

I have two helm upgrade commands:

this one is failing with error message saying **_"This command needs 2 arguments: release name, chart path"_**
[command]C:\hostedtoolcache\windows\helm\2.14.1\x64\windows-amd64\helm.exe upgrade --namespace ci --install --recreate-pods --reset-values --force --set image.repository=acmedevacr.azurecr.io/build/myacmeapp,image.tag=0.4.0-alpha0939.8,deploymentTag=0.4.0-alpha0939.8,appVersion= 0.4.0-alpha0939.8,configVersion=0.4.0-alpha0925 -f d:\a\r1\a/_acmedevops/Deployment/helm/app-chart/dev-env-common.values.yaml -f d:\a\r1\a/_acmedevops/Deployment/helm/app-chart/myacmeapp.ci.values.yaml --debug ci-myacmeapp d:\a\r1\a\_acmedevops\Deployment\helm\app-chart

this one works
[command]C:\hostedtoolcache\windows\helm\2.11.0\x64\windows-amd64\helm.exe upgrade --namespace es-qa-ci --install --recreate-pods --reset-values --force --set image.repository=acmedevacr.azurecr.io/build/acme.identity.server,image.tag=0.3.1.1,deploymentTag=0.3.1.1,appVersion=0.3.1,configVersion=0.4.0 --wait -f d:\a\r1\a/_acmedevops/Deployment/helm/app-chart/dev-env-common.values.yaml -f d:\a\r1\a/_acmedevops/Deployment/helm/app-chart/acme.identity.server.es-qa-ci.values.yaml --debug es-qa-ci-acme.identity.server d:\a\r1\a\_acmedevops\Deployment\helm\app-chart

I don't see any differences beetween parameters - probably this error message is related to something else!!

**Comment by hickeyma** [comment]
@suszig Cannot see any obvious difference. Maybe you could check the following:
- Did the release upgrade/install regardless of the error?
- Can you run the failing command with `--dry-run` to see if it provides more details on what is failing?

**Comment by suszig** [comment]
I found it - unintentional space :-/
appVersion= 0.4.0

is there a way to output parsed values / parameters to log before running the upgrade ?

**Comment by hickeyma** [comment]
Note sure. `--dry-run` is probably your best option and just parse out to log what you want.
