### ISSUE TITLE
CRDs and data retention

### ISSUE THREAD

**Issue by joejulian** [helm/helm#6065]
I had a user complain that he lost all his records that were associated with a CRD when a release was deleted. We changed his chart and set the `crd-install` hook. Later, this same user complained that he couldn't delete and reinstall the same chart because it failed to create the CRD (it was already there). Deleting the CRD via kubectl was not an option as it would lose all the records associated with the CRD and the user was uncomfortable with using kubectl as he was only familiar with using helm. Further, he wanted multiple releases of his software in other namespaces which, again, caused an error because the CRD was already installed.

In trying to preserve that user experience and, at the same time, that user's data we handled that by adding a value that could be changed to install the CRD (or not). This caused confusion because multiple users may install this chart into their namespace, but one has to install that chart with the CRD installation flag set. Which one? How do they know in advance?

Again, this was a less than happy user experience.

* the user would like to install a chart
* if there is no CRD, they would like it created
* if there is a CRD, they would like the rest of the chart to be installed
* they don't want to have to know in advance to set a flag to disable the creation of the CRD
* they don't want to lose their data when a release is deleted. This data may be assocated with other releases.

Suggestion - since CRDs can only be installed once and don't hold state, I propose:
* if a chart has a CRD defined, and that CRD is identical to the one installed, the installation of that object is skipped and the rest of the objects are installed as normal
* if the CRD differs from the one installed, and no flags are set on install, the installation would fail stating that the CRD is installed and differs from the one in the chart.
* if running helm upgrade with or without the install flag, if the CRD differs from the one installed tiller attempts to upgrade the CRD
* if running helm upgrade with or without the install flag, if the CRD is identical to the one installed the installation of the CRD is skipped

**Comment by hickeyma** [comment]
This seems like a good discussion point for #5871. We are discussing many use cases in that proposal, so I added your description which have are some great points.

I am going to close this issue as a duplicate. I hope you will jump in with your thoughts in #5871.
