### ISSUE TITLE
Helm 3: Registry blob storage to follow OCI Image Layout Spec

### ISSUE THREAD

**Issue by jdolitsky** [helm/helm#6068]
Currently the charts are stored in custom fashion in `${HELM_HOME}/registry`:

```
$ tree ~/.helm/registry
/Users/me/.helm/registry
├── blobs
│   └── sha256
│       ├── 3344059bb81c49cc6f2599a379da0a6c14313cf969f7b821aca18e489ba3991b
│       └── 84059d7403f496a1c63caf97fdc5e939ea39e561adbd98d0aa864d1b9fc9653f
├── charts
│   └── mychart
│       └── versions
│           └── 2.7.1
└── refs
    └── localhost_5000
        └── myrepo
            └── mychart
                └── tags
                    └── latest
                        ├── chart -> /Users/me/.helm/registry/charts/mychart/versions/2.7.1
                        ├── content -> /Users/me/.helm/registry/blobs/sha256/3344059bb81c49cc6f2599a379da0a6c14313cf969f7b821aca18e489ba3991b
                        └── meta -> /Users/me/.helm/registry/blobs/sha256/84059d7403f496a1c63caf97fdc5e939ea39e561adbd98d0aa864d1b9fc9653f
```

Instead, Helm should adhere to the [OCI Image Layout Specification](https://github.com/opencontainers/image-spec/blob/master/image-layout.md):
```
$ find . -type f
./index.json
./oci-layout
./blobs/sha256/3588d02542238316759cbf24502f4344ffcc8a60c803870022f335d1390c13b4
./blobs/sha256/4b0bc1c4050b03c95ef2a8e36e25feac42fd31283e8c30b3ee5df6b043155d3c
./blobs/sha256/7968321274dc6b6171697c33df7815310468e694ac5be0ec03ff053bb135e768
```

cc @jzelinskie @bacongobbler

**Comment by bacongobbler** [comment]
Hye @jdolitsky where are we with this?

**Comment by jzelinskie** [comment]
IIRC @stevvooe mentioned that there is a library in containerd that abstracts this away. I have no idea if it'll work alongside your XDG_HOME/CONFIG PR, though.

**Comment by bacongobbler** [comment]
upstream ticket: https://github.com/deislabs/oras/issues/107

**Comment by bacongobbler** [comment]
Thanks for the heads up @jzelinskie! I'll do some digging in containerd and see what comes up.

**Comment by jdolitsky** [comment]
Hi, hoping to have this land upstream in ORAS early next week.

**Comment by bacongobbler** [comment]
removing from the beta milestone as #6185 has been PR'd, which means this discussion can move forward without blocking the release.

**Comment by jdolitsky** [comment]
closed via https://github.com/helm/helm/pull/6205
