### ISSUE TITLE
Repo added with https reverts to http

### ISSUE THREAD

**Issue by jsmilani** [helm/helm#6071]
I am struggling with a mysterious behavior. I added a private helm repo that requires https but when it comes to running the helm upgrade it seems to revert to http and ultimates gets blocked by our firewall.

    [root@9f0ffe5bdc1d photo-uploader-service]# helm repo add private https://helm.private.ops
    [root@9f0ffe5bdc1d photo-uploader-service]# helm upgrade --debug --timeout 600 --install --wait --values values.yaml photo-uploader-service private/docker-compose
    [debug] Created tunnel using local port: '36857'
    
    [debug] SERVER: "127.0.0.1:36857"
    
    Error: Get http://helm.private.ops/docker-compose-0.0.55.tgz: dial tcp 10.10.10.205:80: connect: connection refused

Note the 'http' and port 80. Why would this change from the add statement?

I tried a few things such as adding a --ca-file:

    [root@9f0ffe5bdc1d photo-uploader-service]# helm repo add --ca-file /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem private https://helm.private.ops

I know this should work using https since this command works:

    [root@9f0ffe5bdc1d photo-uploader-service]# helm upgrade --debug --timeout 600 --install --wait --values values.yaml photo-uploader-service https://helm.private.ops/docker-compose-0.0.55.tgz
    [debug] Created tunnel using local port: '36307'
    
    [debug] SERVER: "127.0.0.1:36307"
    
    [debug] Fetched https://helm.private.ops/docker-compose-0.0.55.tgz to /root/.helm/cache/archive/docker-compose-0.0.55.tgz
    
    REVISION: 4
    RELEASED: Tue Jul 23 22:51:52 2019
    ... (success)

If I do it that way I cannot use the 'latest' version so I prefer not to.

Here is my repositories file:

    apiVersion: v1
    generated: "2019-07-23T22:21:08.295944882Z"
    repositories:
    - caFile: ""
      cache: /root/.helm/repository/cache/stable-index.yaml
      certFile: ""
      keyFile: ""
      name: stable
      password: ""
      url: https://helm.private.ops
      username: ""
    - caFile: ""
      cache: /root/.helm/repository/cache/local-index.yaml
      certFile: ""
      keyFile: ""
      name: local
      password: ""
      url: http://127.0.0.1:8879/charts
      username: ""
    - caFile: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
      cache: /root/.helm/repository/cache/private-index.yaml
      certFile: ""
      keyFile: ""
      name: private
      password: ""
      url: https://helm.private.ops
      username: ""

This one is after I added the --ca-file, but even without it I get the same result. Any Ideas?

Output of `helm version`: 

Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
na

**Comment by jsmilani** [comment]
Oh yeah, helm search seems to work:

    [root@9f0ffe5bdc1d photo-uploader-service]# helm search compose
    NAME                 	CHART VERSION	APP VERSION	DESCRIPTION
    private/docker-compose  0.0.55       	           	           
    stable/docker-compose	0.0.55

Something must be partially working as expected. Is it a bug specific to the upgrade command?

If you are wondering about the 'stable' being the same and private ... I set our private repo to be the 'stable' repo too because we don't use stable at all and I was getting firewall issues with it. I would rather not use stable, but I don't see an option to ignore it.

**Comment by hickeyma** [comment]
I did a quick check against the OOTB installed `stable` repo which uses HTTPS and it is work as expected.

```console
$ helm repo list
NAME     	URL                                                               
stable   	https://kubernetes-charts.storage.googleapis.com                  
local    	http://127.0.0.1:8879/charts                                      

$ helm install --name mariadb stable/mariadb
NAME:   mariadb
LAST DEPLOYED: Wed Jul 24 09:38:05 2019
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/ConfigMap
NAME            DATA  AGE
[.....]
```

Can you try this and see if this works:
`helm install –repo https://helm.private.ops docker-compose`

**Comment by jsmilani** [comment]
@hickeyma Trying the same thing.

    [root@e56387bedfb8 photo-uploader-service]# helm repo list
    NAME  	URL                         
    stable	https://helm.private.ops       
    local 	http://127.0.0.1:8879/charts
    private https://helm.private.ops

    [root@e56387bedfb8 photo-uploader-service]# helm install docker-compose --repo https://helm.private.ops
    Error: failed to download "http://helm.private.ops/docker-compose-0.0.55.tgz" (hint: running `helm repo update` may help)

I just noticed something curious. It seemed to figure out the latest version '0.0.55' and try to download it. Perhaps something on our repo server is listing the paths and using http instead of https.

**Comment by hickeyma** [comment]
@jsmilani That could be the problem. Would you be able to investigate this?

**Comment by jsmilani** [comment]
That was the source of the problem. The index.yml was returning the full URL for each chart/version and they were http instead of https. After updating that to https it started working.

It was obviously a problem on our side. I don't see anything helm could have done better other than call out that the url it was trying was not derived from the repo name but instead pulled from the index.yml. I don't think that is a big enough problem to keep this issue open. Closing. Thanks for the help.
