### ISSUE TITLE
Tiller should, by default, tolerate any taints as a kube-system service

### ISSUE THREAD

**Issue by fbertola** [helm/helm#6074]
Tiller should tolerate any taints on nodes, as other `kube-system` services do. It could be easily accomplished changing the k8s template with these lines:

```
      tolerations:
        - operator: Exists
```

I think that applying any special toleration should be an exception and the default case should be as stated.

**Comment by hickeyma** [comment]
@fbertola Thanks for raising this. Do you mind providing some practical use cases for this capability in Tiller?

**Comment by fbertola** [comment]
Sure! It's common to taint apply taints when the node(s) needs to be reserved for special workloads. This, and given that there is still some confusion between NodeSelectors, Node(Anti)Affinity and Taint and Tolerations, I think this will reduce friction and ensure resiliency.

**Comment by hickeyma** [comment]
@fbertola Would you like to push a PR for this?

**Comment by bacongobbler** [comment]
We are no longer accepting new features for Helm 2, and with helm 3 removing Tiller, this is no longer needed. Thanks!
