### ISSUE TITLE
helm template won't generate output if that yaml is ignored by .helmignore

### ISSUE THREAD

**Issue by vlado-github** [helm/helm#6075]
I have a following case where I am trying to generate single yaml file from a template:
```
helm template ./../ -x ./templates/artifacts/configtx.yaml -f ./../values.yaml --output-dir ./../artifacts
```
I receive an error message:
```
Error: could not find template C:\Projects\deploy\helm\HlfOrg\templates\artifacts in chart
```
And my .helmignore is set so I don't include this yaml in deployment package:
```
# Project files
.ssh/
output/
scripts/
templates/artifacts/
```

However, when I remove templates/artifacts from .hemlignore where this yaml resides, everything works and I receive the output. I expected .helmignore will only ingore those files when packaging but not when I want to run template command.

Output of `helm version`:
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

Minikube: v1.0.0

**Comment by mattfarina** [comment]
@vlado-github The `.helmignore` is doing what it is intended to do. It tells Helm what files to ignore.

`helm template` should create the same output for the same input that Helm does with a `helm install` operation.

If you want differences you can set a value in the `values.yaml` file and check for that when rendering a template using an `if` statement.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
