### ISSUE TITLE
How do Core maintainers get paid?

### ISSUE THREAD

**Issue by karuppiah7890** [helm/helm#6086]
Just curious

**Comment by hickeyma** [comment]
@karuppiah7890 Generally Contributors (which also include core maintainers) are either paid by the company they are employed by to contribute to a community or contribute in their own spare time.

I think a question like this could be asked in one of the Helm channels. It is not an issue.

**Comment by karuppiah7890** [comment]
Ah. My bad. I'll put up questions in the channel! Thanks!

**Comment by hickeyma** [comment]
@karuppiah7890 No need for putting in the channel as well, as the question is answered. I meant in future questions can be just asked in the Slack channels.
