### ISSUE TITLE
helm3 install not working in "amd64" but works well in "darwin"

### ISSUE THREAD

**Issue by beravelli** [helm/helm#6099]
helm install not working in "amd64" but works well in "darwin", while helm search <chart> gives me the output fine in both platforms. Not sure if it is a platform specific issue.

Output of `helm version`:
helm version: v3.0.0-alpha.2+g97e7461

Output of `kubectl version`:

kubectl version: Client Version: v1.13.5

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Native Kubernetes Cluster

**Comment by bacongobbler** [comment]
Hi @beravelli. Can you provide the error output? What kind of behaviour are you observing?

**Comment by beravelli** [comment]
Hi,

while the helm search get me the release versions... and when I issue the same install command on the mac it works, but not in amd64.

Install command used:
helm install --version "0.1.0"  "<chartname>"

Error I get in amd64:

Error: failed to download "<chartname>"

**Comment by beravelli** [comment]
So, I ran it debug and it gives me the below error...

printer.go:84: [debug] Original chart version: "0.1.0"
Error: scheme "local" not supported
helm.go:76: [debug] scheme "local" not supported
helm.sh/helm/pkg/getter.Providers.ByScheme
	/go/src/helm.sh/helm/pkg/getter/getter.go:117
helm.sh/helm/pkg/downloader.(*ChartDownloader).DownloadTo
	/go/src/helm.sh/helm/pkg/downloader/chart_downloader.go:92
helm.sh/helm/pkg/action.(*ChartPathOptions).LocateChart
	/go/src/helm.sh/helm/pkg/action/install.go:679
main.runInstall
	/go/src/helm.sh/helm/cmd/helm/install.go:167
main.newInstallCmd.func1
	/go/src/helm.sh/helm/cmd/helm/install.go:107
helm.sh/helm/vendor/github.com/spf13/cobra.(*Command).execute
	/go/src/helm.sh/helm/vendor/github.com/spf13/cobra/command.go:762
helm.sh/helm/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/go/src/helm.sh/helm/vendor/github.com/spf13/cobra/command.go:850
helm.sh/helm/vendor/github.com/spf13/cobra.(*Command).Execute
	/go/src/helm.sh/helm/vendor/github.com/spf13/cobra/command.go:800
main.main

**Comment by bacongobbler** [comment]
I'm confused. You are providing helm a chart with no name, so the expected output of `helm install --version 0.1.0 ""` should be 'failed to download ""'.

Please provide a full end-to-end example of what you are attempting to do, and what is the expected output. Thanks.

**Comment by beravelli** [comment]
I will reopen it post analysis. Thanks for your time.
