### ISSUE TITLE
Feature Request: Pass username and password to plugin

### ISSUE THREAD

**Issue by xh4n3** [helm/helm#6103]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}
```

Currently helm does not pass username and password to plugins, only certFile, keyFile, caFile are passed.
See https://github.com/helm/helm/blob/master/pkg/getter/plugingetter.go#L67

I'm thinking about adding it. I can adding more args here, or I can pass username and password via environment variables in https://github.com/helm/helm/blob/master/pkg/getter/plugingetter.go#L69

How do you think? Thanks

**Comment by hickeyma** [comment]
@xh4n3 Can you push a PR and we can seen then when reviewing.

**Comment by xh4n3** [comment]
@hickeyma Sure！
Please see https://github.com/helm/helm/pull/6110

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
