### ISSUE TITLE
does helm support nested variable reference?

### ISSUE THREAD

**Issue by junneyang** [helm/helm#6104]
i have 2 enviroment(dev/test):

values.yaml:    
   `     
envType: dev

envs_dev:
    PARAMS_AAA: "123456_dev"
    PARAMS_BBB: "654321_dev"

envs_test:
    PARAMS_AAA: "123456_test"
    PARAMS_BBB: "654321_test"
`     

deployement.yaml:    
`     
        env:
         {{- range $key, $value := .Values.envs_{{ ..Values.envType }} }}
         - name: {{ $key }}
           value: {{ $value | quote }}
         {{- end }}

`

**Comment by bacongobbler** [comment]
Yes, this is a fairly common pattern. I'd suggest looking at the helm/charts repository to determine best practices here. :)

**Comment by junneyang** [comment]
![image](https://user-images.githubusercontent.com/6802322/62124020-cbf6df00-b2fb-11e9-8c76-4c860b345f13.png)
@bacongobbler 
thanks, but i mean if i can ref {{ ..Values.envType }} in {{- range ?
this is netsted reference.

thanks for your help

**Comment by bacongobbler** [comment]
You may want to use the `index` function for that. Usage instructions can be found in the [text/template documentation](https://golang.org/pkg/text/template/#hdr-Functions), and you can find examples in the [helm/charts repo](https://github.com/helm/charts/blob/595f51dda8d6cfee73aff5da3dbe9c7258995f3b/stable/anchore-engine/templates/enterprise_ui_config.yaml#L23).

**Comment by eduardoriveror** [comment]
Hi @junneyang could you find a solution for this? I have several lists for several clusters and depending on which cluster, I need to loop through a different list, so i also need to template the name of the list inside the range block

**Comment by ashutosh-hep** [comment]
Hi @eduardoriveror did you get solution for this?
