### ISSUE TITLE
helm v3.0.0-alpha.2 doesnt support lack of trailing slash in repo url

### ISSUE THREAD

**Issue by InsOpDe** [helm/helm#6113]
Output of `helm version`:
`version.BuildInfo{Version:"v3.0.0-alpha.2", GitCommit:"97e7461e41455e58d89b4d7d192fed5352001d44", GitTreeState:"clean", GoVersion:"go1.12.7"}`

In former versions like `v2.14.2` the missing trailing slash  was supported when executing following command:
`helm fetch tekton --repo https://storage.googleapis.com/chartmuseum.jenkins-x.io`

Now with helm3 I get following error:
`helm fetch tekton --repo https://storage.googleapis.com/chartmuseum.jenkins-x.io
Error: failed to fetch https://storage.googleapis.com/charts/tekton-0.0.42.tgz : 403 Forbidden`
because he seems to dismiss the `repo` flag alltogether. When executing
`helm fetch tekton --repo https://storage.googleapis.com/chartmuseum.jenkins-x.io/` it works.

This gets in conflict with the `jx` binary of Jenkins X which produces repo-urls without the trailing slashes.

It would be nice if missing trailing slashes would be supported again.

**Comment by karuppiah7890** [comment]
I think it's more of required feature than a nice feature. We'll surely fix this. Will raise a PR for this

**Comment by bacongobbler** [comment]
Perhaps we need to port over https://github.com/helm/helm/pull/4956.

**Comment by bacongobbler** [comment]
fixed via #6121.
