### ISSUE TITLE
Helm upgrade fails with ManagedCerts from networking.gke.io/v1beta1

### ISSUE THREAD

**Issue by PsyonixBarrett** [helm/helm#6123]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.0-alpha.2", GitCommit:"97e7461e41455e58d89b4d7d192fed5352001d44", GitTreeState:"clean", GoVersion:"go1.12.7"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-19T22:12:47Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.8-gke.10", GitCommit:"f53039cc1e5295eed20969a4f10fb6ad99461e37", GitTreeState:"clean", BuildDate:"2019-06-19T20:48:40Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  `GKE`

---

### The Issue

* When installing a chart which contains a manifest template for a [ManagedCertificate for a Google Load balancer on GKE](https://cloud.google.com/kubernetes-engine/docs/how-to/managed-certs), everything works perfectly.
* If I attempt to run `helm upgrade` against the same chart with the exact same values it will fail with the following error message...

```
Error: UPGRADE FAILED: unable to decode "": no kind "ManagedCertificate" is registered for version "networking.gke.io/v1beta1" in scheme "k8s.io/client-go/kubernetes/scheme/register.go:65"
```

**Comment by nApucco** [comment]
We seem to have the same issue when using Helm 3 with OpenShift and their CRD for "DeploymentConfig", "Route" and other OpenShift resources.

The error only occures when an existing installation is being upgraded:
```
Error: UPGRADE FAILED: [unable to decode "": no kind "DeploymentConfig" is registered for version "apps.openshift.io/v1" in scheme "k8s.io/client-go/kubernetes/scheme/register.go:65",
```

We don't know if it is related, but in the same error we also get additional ValidationErrors, where Helm seems to have issues validation some optional fields in the custom resource definitions of OpenShift Routes:
```
error validating "": error validating data: [ValidationError(Route.spec): missing required field "host" in com.github.openshift.api.route.v1.RouteSpec, ValidationError(Route): missing required field "status" in com.github.openshift.api.route.v1.Route]]
helm.go:76: [debug] [unable to decode "": no kind "DeploymentConfig" is registered for version "apps.openshift.io/v1" in scheme "k8s.io/client-go/kubernetes/scheme/register.go:65", error validating "": error validating data: [ValidationError(Route.spec): missing required field "host" in com.github.openshift.api.route.v1.RouteSpec, ValidationError(Route): missing required field "status" in com.github.openshift.api.route.v1.Route]]
helm.sh/helm/pkg/kube.scrubValidationError
        /go/src/helm.sh/helm/pkg/kube/client.go:486
helm.sh/helm/pkg/kube.(*Client).Build
        /go/src/helm.sh/helm/pkg/kube/client.go:145
helm.sh/helm/pkg/action.validateManifest
        /go/src/helm.sh/helm/pkg/action/upgrade.go:333
```

Is there an issue with the registration of the schemas of custom resources?
(Does a user need certain permissions for Helms discovery mechanism to find all API resources/schemas of the Kubernetes API server?)
Are optional fields handled properly?

**Comment by bakito** [comment]
I can confirm the comment of @nApucco 
We are facing the same issues with OpenShift Resources DeploymentConfig and Route.

helm3 version: version.BuildInfo{Version:"v3.0.0-alpha.2", GitCommit:"97e7461e41455e58d89b4d7d192fed5352001d44", GitTreeState:"clean", GoVersion:"go1.12.7"}

OpenShift: 
openshift v3.9.68
kubernetes v1.9.1+a0ce1bc657

**Comment by aftouh** [comment]
We are facing the same issue with Istio VirtualService CRD.

`Error: UPGRADE FAILED: unable to decode "": no kind "VirtualService" is registered for version "networking.istio.io/v1alpha3" in scheme "k8s.io/client-go/kubernetes/scheme/register.go:65"`

Helm version: version.BuildInfo{Version:"v3.0.0-alpha.2", GitCommit:"97e7461e41455e58d89b4d7d192fed5352001d44", GitTreeState:"clean", GoVersion:"go1.12.7"}

Gke version: v1.13.7-gke.8

**Comment by bakito** [comment]
I tried with beta v1 and it solves my problems too.
version.BuildInfo{Version:"v3.0.0-beta.1", GitCommit:"f76b5f21adb53a85de8925f4a9d4f9bd99f185b5", GitTreeState:"clean", GoVersion:"go1.12.9"}

**Comment by hickeyma** [comment]
Closing following confirmation in https://github.com/helm/helm/issues/6123#issuecomment-525563269 and https://github.com/helm/helm/issues/6123#issuecomment-525593936. Thanks @ento and @bakito. We can re-open the issue if need be.
