### ISSUE TITLE
Bad error message from helm upgrade force when chart is invalid.

### ISSUE THREAD

**Issue by yashs-dev** [helm/helm#6125]
Adding --force switch in helm upgrade command results in bad error message.

**With --force switch:**
$values | helm upgrade my-release .\Helm\my-release --install **--force** --values - --wait
Error: UPGRADE FAILED: a released named my-release is in use, cannot re-use a name that is still in use

**After removing --force switch:**
$values | helm upgrade my-release .\Helm\my-release --install --values - --wait
Error: UPGRADE FAILED: YAML parse error on my-release/templates/deployment.yaml: error converting YAML to JSON: yaml: line 37: mapping values are not allowed in this context

Output of `helm version`:
v2.11.0

Output of `kubectl version`:
v1.1.5.0

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS Engine

**Comment by bacongobbler** [comment]
Let us know if you can determine what causes this error. I haven't the foggiest.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
