### ISSUE TITLE
Install switch does not work without force switch with helm upgrade command.

### ISSUE THREAD

**Issue by yashs-dev** [helm/helm#6126]
Install switch does not work without force switch with helm upgrade command, when release doesn't exist.

**Without --force switch, upgrade fails to install:**
$values | helm upgrade my-release .\Helm\my-release --install --values - --wait
Error: UPGRADE FAILED: "my-release" has no deployed releases

**With --force switch, upgrade installs successfully:**
$values | helm upgrade my-release .\Helm\my-release --install **--force** --values - --wait
Release "my-release" has been upgraded. Happy Helming!

Output of helm version:
v2.11.0

Output of kubectl version:
v1.1.5.0

Cloud Provider/Platform (AKS, GKE, Minikube etc.):
AKS Engine

**Comment by tyranron** [comment]
Facing the same issue with Helm version:
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

**Comment by bacongobbler** [comment]
Usually that means all releases deployed in your cluster are in a failing state. What's the output of `helm history`?

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
