### ISSUE TITLE
Unable to --set timeZone using helm

### ISSUE THREAD

**Issue by KaLyanRv** [helm/helm#6131]
Unable to set timezone using helm. [BUG]

--set timeZone=Europe/Stockholm (Doesn't work)

I tried adding this parameter explicitly in the helm chart and it didn't work. 

Is it possible to override the timezone of all containers from UTC to CET/Europe/Stockholm

helm version :
Client: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.2", GitCommit:"40665d0724368cb0581288773844b61bdf928791", GitTreeState:"clean"}

kubectl version:
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:26:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-04-03T04:12:37Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by bacongobbler** [comment]
Closing in favour of #6128.
