### ISSUE TITLE
Exit with non-zero error code from template code

### ISSUE THREAD

**Issue by ivanilves** [helm/helm#6148]
Hi guys,

_I know probably it's wrong and it should not be done inside Helm chart, but ..._

**Can I trigger a non-zero exit inside helm template?**

Something like this:
```
{{ if eq .Values.something "bad-value" }}
  {{ exitWithFailure }}
{{ end }}
```

Thank you!!!

**Comment by ivanilvescmp** [comment]
Found it http://masterminds.github.io/sprig/flow_control.html 😄

**Comment by ivanilves** [comment]
Found it: http://masterminds.github.io/sprig/flow_control.html 😄
