### ISSUE TITLE
Helm without internet 

### ISSUE THREAD

**Issue by dhineshbabuelango** [helm/helm#6150]
I am trying to use helm in AWS eks but all the document says to use the below command to install tiller

helm init --service-account tiller

The above command is downloading the package from Internet but in our prod environment we don’t have Internet, I can download the image and put this in ecr but where will u mention the ecr image path as the above command is not an yaml file also is it recommended to run helm offline ?

**Comment by mattfarina** [comment]
@dhineshbabuelango You can use the `--tiller-image` flag on init to set an alternate location to pull the image from. You can use this to set it to your location in ecr. Will that work?

**Comment by dhineshbabuelango** [comment]
@mattfarina thanks for your reply, this will work for us, I can give a try in this. But if there is any update in the tiller image, can we run the same tiller command specifying the new image name ?

**Comment by hickeyma** [comment]
@dhineshbabuelango yes but add the `--upgrade` flag.

**Comment by dhineshbabuelango** [comment]
Thanks mattfarina for your help
