### ISSUE TITLE
Helm eating away newlines when using `--set-file` and deploying to container

### ISSUE THREAD

**Issue by AndrewLvov** [helm/helm#6153]
There is a strange issue with Helm eating away newlines when the file is being imported into variable and then used in volumes to be stored as a file on container being deployed.
Please check repo: https://github.com/AndrewLvov/test-newlines
It has a full reproducible chart and a description.

In short - if you import a file's content via `--set-file` and then put into container as a file using `volumes` functionality, the `\n` is replaced with ` ` (space) and `\n\n` is replaced with a single `\n`.

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Minikube

**Comment by karuppiah7890** [comment]
@AndrewLvov thanks for helping reproduce the issue. I'm able to see the bug too in helm version - 
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```

**Comment by bacongobbler** [comment]
We are no longer accepting bug fixes for Helm 2. See https://helm.sh/blog/helm-v2-deprecation-timeline/ for more details.
