### ISSUE TITLE
Support index.json in addition to index.yaml in repositories

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#6155]
`index.yaml` files that grow large in size can use significant resources to parse. Some time ago I produced some benchmarks at https://github.com/mattfarina/yamlbench. This project was originally showcased by some at jFrog at the first helm summit.

As a feature addition, we could add an `index.json` file alongside the YAML file. JSON uses significantly fewer resources when being parsed. For older helm clients the `index.yaml` would still exist. Helm could check for the json file. If not present fall back to the `index.yaml` file. This would enable helm to work with older repositories.

This could go into both Helm v3 and v2.

**Comment by bacongobbler** [comment]
SGTM. This definitely sounds like a feature addition where we could fallback to the original request.

**Comment by karuppiah7890** [comment]
I would love to give this a try! Are there any special requirements other than what's mentioned above? 

In terms of code, I'm thinking - I'll check every place where index yaml file is used/parsed, and try to add support for json too if json file is present, or fallback to yaml. Write index.json related tests in all places which has tests regarding `index.yaml` files

**Comment by karuppiah7890** [comment]
@bacongobbler @mattfarina Should we consider more options? Since this is an index and it will only be generated by programs and read by programs and not humans, is it possible to checkout other formats to store the index? To make the storage and processing more efficient

**Comment by marckhouzam** [comment]
The completion code would greatly benefit from much faster parsing, although all it needs is the list of chart names. The completion currently uses `helm search repo` which is much too slow (when the stable repo is provisioned) in the context of completion.

I've proposed the creation of another cache file which would only list the charts as part of #6809.

It would be nice to consider this requirement when addressing the current issue, if my proposed new cache file is not approved.

**Comment by karuppiah7890** [comment]
I'm starting off with implementing the creation of a `index.json` file along with `index.yaml` file when we run

`helm repo index .`

**Comment by karuppiah7890** [comment]
what about --merge option?

if index.yaml is given, it will be converted to index object and then used to create both index.json and index.yaml - okay?

what about supporting merging with index.json ?

should we add another option called --merge-json ? or --merge-json-index ?

and how will this option work? as in, do we allow both --merge and --merge-json-index at a time?
or just one at a time?

if we allow both, then we will have to convert both to index object, and then merge
all of them.

thoughts? @bacongobbler @mattfarina

**Comment by karuppiah7890** [comment]
I have raised a PR #7510 . It's still a work in progress. I have added the feature to create an `index.json` and also the `--merge-json-index` feature. All of them create both json and yaml index too. I have added some tests too. And some functions are exported, do check em, naming, comments (docs) and more. 😄 

@hickeyma @bacongobbler @mattfarina

**Comment by karuppiah7890** [comment]
I put a condition that both `--merge` and `--merge-json-index` cannot be used. I thought it wasn't needed, and that we could consider just one index, and it can be in either format

**Comment by karuppiah7890** [comment]
Actually, come to think of it, there could just be one option `--merge` which supports both json and yaml. Considering yaml is a superset of json . But I'm not sure how the implementation will look like - probably no change? as yaml parser can understand yaml, then it can understand json too. So, no need for separate code for that I guess 🤔 

Let me know your thoughts on this!

**Comment by mattfarina** [comment]
I noted this slack and wanted to note it again here.

JSON parsing is faster and uses less ram in general. YAML can have references to other parts of the document. You need to parse the whole document as a whole. JSON does not have this which provides more options for performant parsing. Also, Helm uses the worst case for YAML parsing on performance to make it easier on tooling management. You can see more info at https://github.com/mattfarina/yamlbench

The JSON handling should be parser agnostic. This would allow us to swap out for something more performant if needed. Otherwise we should be able to use the JSON handling in the standard library and see large gains.

cc @karuppiah7890

**Comment by karuppiah7890** [comment]
Understood. So, even though yaml parser can understand json, directly using json parser can be faster, which is the goal of this whole feature - to be very fast. I'll also try this in a repo similar to your benchmark - comparing yaml parser with json input and json parser with json input, using different parsers


And also, about swapping out parser - agreed. I'll see how to implement this. I have some thoughts on some things - like some libraries can provide features that others don't. So, if our implementation is based on some features like that, we will only be able to swap to libraries that provide the same features. For example, usually, in ecoding/json library, you need to parse the whole document, and then get a field's value but looks like some libraries can just parse partially and get the value given a json path.

I'll ping here when I implement that and about what options we have :) Thanks for your suggestion! :)

**Comment by karuppiah7890** [comment]
Since it's been months now, and I haven't worked much on the PR, it's fair to open it for others.
I'm surprised why this hasn't caught much attention. This isn't a very important feature?

**Comment by thernstig** [comment]
@mattfarina could this be re-opened? We are finding this an increasingly large issue with index files that are large (over 50000 lines at least).

I recon most users ever having index files this big will eventually get into this problem.

I noticed you had done also https://github.com/mattfarina/helm-index-json previously, is this somewhat related to this? Should that work you started there be continued?
