### ISSUE TITLE
helm corrupted on mac

### ISSUE THREAD

**Issue by smartpcr** [helm/helm#6157]
I am having the following error when run `helm init`, is there a easy way to fix it? I have tried reinstall helm via `brew` and cleared `./heml/` directory. thanks!

``` txt
Error: error installing: namespaces "8998b851784e4e7162bbfba59a87a890" not found
```

**Comment by bacongobbler** [comment]
Do you have `$TILLER_NAMESPACE` set in your environment somehow? Check the output of `env` and see if anything interesting shows up.

**Comment by bacongobbler** [comment]
If that is indeed the namespace you want to install Tiller into, run `kubectl create namespace 8998b851784e4e7162bbfba59a87a890` first before running `helm init`.

**Comment by smartpcr** [comment]
thanks, unset env fixed the problem.
