### ISSUE TITLE
after helm install expecting to show in helm list

### ISSUE THREAD

**Issue by longility** [helm/helm#6159]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.0-alpha.2", GitCommit:"97e7461e41455e58d89b4d7d192fed5352001d44", GitTreeState:"clean", GoVersion:"go1.12.7"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-20T04:49:16Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AKS

I'm new to helm, and I decided to go straight to v3 alpha.

I did the following:
1. `helm install ingress-nginx stable/nginx-ingress -n ingress-nginx --set rbac.create=true`, which resulted in the installation of the nginx ingress controller. Tested and it is working.
2. `helm list` shows empty list. I am expecting it to show the ingress-nginx that I installed as a row in the list.
2. Ran install again to see what happens. The output is now `Error: cannot re-use a name that is still in use`, which makes me think it is installed.

Am I misunderstanding how list works or how to see installed helm charts, or is there something else going on here?

**Comment by karuppiah7890** [comment]
@longility I think you probably missed the namespace name. According to your `helm install` command, you have installed in `ingress-nginx` namespace. Could you try `helm list -n ingress-nginx` ?

**Comment by longility** [comment]
@karuppiah7890 Perfect! Thank you so much. That was it. This leads me to probably using `helm list --all-namespaces` for convenience.
