### ISSUE TITLE
render error with (tpl .Files.Glob().AsConfig .)

### ISSUE THREAD

**Issue by jc5201** [helm/helm#6161]
I have problem rendering configuration file using tpl function.

Here is 3 files I'm dealing with.

```
templates/configmap.yaml
==================
apiVersion: v1
kind: ConfigMap
metadata:
  name: dummp-configmap 
data:
  {{- (tpl (.Files.Glob "conf/env.sh").AsConfig .) | nindent 2 }}
```
```
values.yaml
==================
create:
  aaaaaaaaa: true

aaaaaaaaa:
  host: ccccc
```
```
conf/env.sh
==================
#!/bin/bash

ABC={{ if .Values.create.aaaaaaaaa }}{{ .Values.aaaaaaaaa.host }} 
  {{- else }}bbbbbbb-aaaaaaaaa-0.aaaaaaaaa.bbbbbbb.svc.cluster.local{{ end }} 
```

when I install this chart, I get this error
```
Error: render error in "dummy/templates/configmap.yaml": template: dummy/templates/configmap.yaml:6:7: executing "dummy/templates/configmap.yaml" at <tpl (.Files.Glob "conf/env.sh").AsConfig .>: error calling tpl: Error during tpl function execution for "env.sh: \"#!/bin/bash\\n\\nABC={{ if .Values.create.aaaaaaaaa }}{{ .Values.aaaaaaaaa.host\n  }} \\n  {{- else }}bbbbbbb-aaaaaaaaa-0.aaaaaaaaa.bbbbbbb.svc.cluster.local{{ end\n  }} \\n\\n\"\n": parse error in "dummy/templates/configmap.yaml": template: dummy/templates/configmap.yaml:1: unclosed action
```

I guess this error comes from '\n' in {{ ... }} block. 
But I don't know why '\n' is generated and this should not change result.

I can place some space in conf/env.sh and supress error, but I don't want to do these meaningless engineering repeatedly.

Here is slightly changed conf/env.sh which do not throw error.
```
#!/bin/bash

ABC={{ if .Values.create.aaaaaaaaa }} {{- .Values.aaaaaaaaa.host}} 
  {{- else }}bbbbbbb-aaaaaaaaa-0.aaaaaaaaa.bbbbbbb.svc.cluster.local{{ end }} 
```

Can anybody reply if this is my mistake or bug of helm?
If this is bug of helm, please fix this bug.

Output of `helm version`:
Client: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
On-premise

**Comment by bacongobbler** [comment]
Were you able to identify and resolve the issue?

**Comment by jc5201** [comment]
As I described in previous message, I think this issue occurs because of '\n' appears in intermediate string. 
But I didn't tried debugging because I don't have go development environment. sorry.

**Comment by corollo** [comment]
Hi, I have the same problem with helm v3.0.2, do you know if the bug will be fixed in a future version ?
Thank you.

**Comment by michael-wirth** [comment]
same issue with helm v.3.1.2

**Comment by urmet** [comment]
I just stumbled on this bug too. Thought I'd drop a workaround for others who might stumble here. Just loop over the glob and do one file at a time:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mychart.fullname" . }}-configs
data:
{{- range $path, $_ := (.Files.Glob "configs/*") }}
  {{ trimPrefix "configs/" $path }}: |{{- tpl ($.Files.Get $path) $ | nindent 4 }}
{{ end }}
```
