### ISSUE TITLE
helm3: deleted in release info has strange default

### ISSUE THREAD

**Issue by Tobag** [helm/helm#6163]
I just did a `helm install wordpress stable/wordpress` with helm3-alpha2.
Then I looked at the release secret `k get secret wordpress.v1 -o jsonpath="{.data.release}" | base64 -D | base64 -D | gzip -d | jq`

`
{
  "name": "wordpress",
  "info": {
    "first_deployed": "2019-08-05T13:52:08.317608+02:00",
    "last_deployed": "2019-08-05T13:52:08.317608+02:00",
    "deleted": "0001-01-01T00:00:00Z",
    "Description": "Install complete",
    "status": "deployed", ...
`

As you can see the deleted timestamp has some strange default value. I think it should be an empty string or something like that.

Best regards,
Tobi

**Comment by thomastaylor312** [comment]
Closed in #6679
