### ISSUE TITLE
Helm seems to apply custom resource before CRD

### ISSUE THREAD

**Issue by benbuzbee** [helm/helm#6165]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.8-eks-a977ba", GitCommit:"a977bab148535ec195f12edc8720913c7b943f9c", GitTreeState:"clean", BuildDate:"2019-07-29T20:47:04Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Amazon EKS

The following mini-repro creates a CRD for Kind=Test2 and then creates an object of type Kind=Test2. When executed in the correct order, the YAML is valid. However, when applied with helm, it appears as if the object is created before the CRD which defines it

The following is output:
```
UPGRADE FAILED
Error: unable to recognize "": no matches for kind "Test2" in version "group.name/v1"
Error: UPGRADE FAILED: unable to recognize "": no matches for kind "Test2" in version "group.name/v1"
```

The repro is as follows (executable in bash):
```
helm create order-test
echo "
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tests2.group.name
spec:
  group: group.name
  versions:
    - name: v1
      served: true
      storage: true
  scope: Cluster
  names:
    plural: tests2
    singular: test2
    kind: Test2
    shortnames: []
  preservedUnknownFields: true
---
apiVersion: group.name/v1
kind: Test2
metadata:
  name: example
spec:
  foo: bar
" > order-test/templates/test.yaml
helm upgrade --install a-test order-test
```

**Comment by archelangelo** [comment]
I'm not sure if helm installs resources according to a particular order. But just to be safe, you might want to use a `crd-install` [hook](https://github.com/helm/helm/blob/master/docs/charts_hooks.md#the-available-hooks). This ensures the CRD definitions be applied prior to its resources.

**Comment by benbuzbee** [comment]
Good pointer archelangelo. 
Order is supposed to be guaranteed here https://github.com/helm/helm/blob/9ad53aac42165a5fadc6c87be0dea6b115f93090/pkg/tiller/kind_sorter.go#L133 

and an unknown resource kind should be ordered last, which makes this repro seem like a bug unless I am missing something. 

Although it does appear crd-install hooks are meant to solve this problem, I am surprised they would be necessary if the only dependency is an unknown kind given the order guarantees.

**Comment by archelangelo** [comment]
Ah! That's interesting. I didn't know this, though it makes perfect sense. I worked with CRD installation in helm couple weeks ago and clearly remember this kind of error are thrown pretty frequently (not to mention `helm delete --purge` doesn't remove CRDs). The only cause I can think of then is that the CRDs won't be ready right after being applied?

**Comment by benbuzbee** [comment]
Im closing this because I think the issues are pretty well covered by #4697 
Really this whole situation seems pretty messy. Will continue there.
