### ISSUE TITLE
Question: Passing values.yaml in a packaged chart

### ISSUE THREAD

**Issue by nicholasrobertm** [helm/helm#6169]
Hi there!

I was wondering if when using helm package to package a version of the chart (let's call this example.tgz) if you could pass a values file that's in that package to helm install. The install looks similar too:

`helm upgrade --install example https://path_to_chart.com/example.tgz`

Right now, but ideally I'd like to be able to have the values file contained in that chart (which is inside the compressed file) so

`helm upgrade --install example https://path_to_chart.com/example.tgz -f values.yaml`

Has anyone come up with a good solution from this other than specifying a local copy or embedding the chart values in? Appreciate any advice!

**Comment by bacongobbler** [comment]
dupe of https://github.com/helm/helm/issues/4782
