### ISSUE TITLE
tiller could not be ready in minikube

### ISSUE THREAD

**Issue by ChaosCodes** [helm/helm#6170]
Output of `helm version`:
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Error: could not find a ready tiller pod

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.9-dispatcher", GitCommit:"e3f5193e8f1091a162af7e17a781e6a3129bcfd0", GitTreeState:"clean", BuildDate:"2019-03-28T18:15:47Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Minikube

the Output of `kubectl get pods --namespace kube-system`

NAME                               READY     STATUS              RESTARTS   AGE
coredns-6967fb4995-g4tnq           1/1       Running             0          23h
coredns-6967fb4995-g8qjr           1/1       Running             0          23h
etcd-minikube                      1/1       Running             0          23h
kube-addon-manager-minikube        1/1       Running             0          23h
kube-apiserver-minikube            1/1       Running             0          23h
kube-controller-manager-minikube   1/1       Running             0          23h
kube-proxy-5lwts                   1/1       Running             0          23h
kube-scheduler-minikube            1/1       Running             0          23h
registry-creds-hhbtb               0/1       ContainerCreating   0          23h
storage-provisioner                1/1       Running             0          23h
tiller-deploy-548fd5dc4f-n8ntf     0/1       ImagePullBackOff    0          26m

it's shown that the tiller can not be ready
I want to use helm to deploy in my laptop. But helm throw a Error that `could not find a ready tiller pod`

Thanks!

**Comment by bacongobbler** [comment]
Can you show the output of `kubectl -n describe pod tiller-deploy-548fd5dc4f-n8ntf`? It should tell you why the image is failing to pull.

**Comment by ChaosCodes** [comment]
> Can you show the output of `kubectl -n describe pod tiller-deploy-548fd5dc4f-n8ntf`? It should tell you why the image is failing to pull.

kubectl describe pod tiller-deploy-548fd5dc4f-n8ntf
Error from server (NotFound): pods "tiller-deploy-548fd5dc4f-n8ntf" not found

~ kubectl get pods
No resources found.

it seems that it can not find the pod

**Comment by bacongobbler** [comment]
Okay. Please check the output of `kubectk get` again and use `kubectl describe` on the tiller pod currently available please.

**Comment by ChaosCodes** [comment]
$ kubectl get

You must specify the type of resource to get. Use "kubectl api-resources" for a complete list of supported resources.

error: Required resource not specified.
Use "kubectl explain <resource>" for a detailed description of that resource (e.g. kubectl explain pods).
See 'kubectl get -h' for help and examples.


$ kubectl api-resources
NAME                              SHORTNAMES   APIGROUP                       NAMESPACED   KIND
bindings                                                                      true         Binding
componentstatuses                 cs                                          false        ComponentStatus
configmaps                        cm                                          true         ConfigMap
endpoints                         ep                                          true         Endpoints
events                            ev                                          true         Event
limitranges                       limits                                      true         LimitRange
namespaces                        ns                                          false        Namespace
nodes                             no                                          false        Node
persistentvolumeclaims            pvc                                         true         PersistentVolumeClaim
persistentvolumes                 pv                                          false        PersistentVolume
pods                              po                                          true         Pod
podtemplates                                                                  true         PodTemplate
replicationcontrollers            rc                                          true         ReplicationController
resourcequotas                    quota                                       true         ResourceQuota
secrets                                                                       true         Secret
serviceaccounts                   sa                                          true         ServiceAccount
services                          svc                                         true         Service
mutatingwebhookconfigurations                  admissionregistration.k8s.io   false        MutatingWebhookConfiguration
validatingwebhookconfigurations                admissionregistration.k8s.io   false        ValidatingWebhookConfiguration
customresourcedefinitions         crd,crds     apiextensions.k8s.io           false        CustomResourceDefinition
apiservices                                    apiregistration.k8s.io         false        APIService
controllerrevisions                            apps                           true         ControllerRevision
daemonsets                        ds           apps                           true         DaemonSet
deployments                       deploy       apps                           true         Deployment
replicasets                       rs           apps                           true         ReplicaSet
statefulsets                      sts          apps                           true         StatefulSet
tokenreviews                                   authentication.k8s.io          false        TokenReview
localsubjectaccessreviews                      authorization.k8s.io           true         LocalSubjectAccessReview
selfsubjectaccessreviews                       authorization.k8s.io           false        SelfSubjectAccessReview
selfsubjectrulesreviews                        authorization.k8s.io           false        SelfSubjectRulesReview
subjectaccessreviews                           authorization.k8s.io           false        SubjectAccessReview
horizontalpodautoscalers          hpa          autoscaling                    true         HorizontalPodAutoscaler
cronjobs                          cj           batch                          true         CronJob
jobs                                           batch                          true         Job
certificatesigningrequests        csr          certificates.k8s.io            false        CertificateSigningRequest
leases                                         coordination.k8s.io            true         Lease
events                            ev           events.k8s.io                  true         Event
daemonsets                        ds           extensions                     true         DaemonSet
deployments                       deploy       extensions                     true         Deployment
ingresses                         ing          extensions                     true         Ingress
networkpolicies                   netpol       extensions                     true         NetworkPolicy
podsecuritypolicies               psp          extensions                     false        PodSecurityPolicy
replicasets                       rs           extensions                     true         ReplicaSet
ingresses                         ing          networking.k8s.io              true         Ingress
networkpolicies                   netpol       networking.k8s.io              true         NetworkPolicy
runtimeclasses                                 node.k8s.io                    false        RuntimeClass
poddisruptionbudgets              pdb          policy                         true         PodDisruptionBudget
podsecuritypolicies               psp          policy                         false        PodSecurityPolicy
clusterrolebindings                            rbac.authorization.k8s.io      false        ClusterRoleBinding
clusterroles                                   rbac.authorization.k8s.io      false        ClusterRole
rolebindings                                   rbac.authorization.k8s.io      true         RoleBinding
roles                                          rbac.authorization.k8s.io      true         Role
priorityclasses                   pc           scheduling.k8s.io              false        PriorityClass
csidrivers                                     storage.k8s.io                 false        CSIDriver
csinodes                                       storage.k8s.io                 false        CSINode
storageclasses                    sc           storage.k8s.io                 false        StorageClass
volumeattachments                              storage.k8s.io                 false        VolumeAttachment

I try but could not find the available tiller pod

**Comment by bacongobbler** [comment]
I meant `kubectl get pods --namespace kube-system`. I want you to figure out the name of the tiller pod and to run `kubectl -n describe pod <name of pod>` against it.

**Comment by ChaosCodes** [comment]
Sorry, but it's weird that I get the name of the tiller pod but it still can not find it. Here are my outout below.

➜ ~ kubectl get pods --namespace kube-system
NAME                               READY     STATUS              RESTARTS   AGE
coredns-6967fb4995-g4tnq           1/1       Running             0          32h
coredns-6967fb4995-g8qjr           1/1       Running             0          32h
etcd-minikube                      1/1       Running             0          32h
kube-addon-manager-minikube        1/1       Running             0          32h
kube-apiserver-minikube            1/1       Running             0          32h
kube-controller-manager-minikube   1/1       Running             0          32h
kube-proxy-5lwts                   1/1       Running             0          32h
kube-scheduler-minikube            1/1       Running             0          32h
registry-creds-hhbtb               0/1       ContainerCreating   0          32h
storage-provisioner                1/1       Running             0          32h
tiller-deploy-548fd5dc4f-n8ntf     1/1       Running             0          9h
➜  ~ kubectl -n describe pod tiller-deploy-548fd5dc4f-n8ntf
Error: unknown command "pod" for "kubectl"

Did you mean this?
	top

Run 'kubectl --help' for usage.
unknown command "pod" for "kubectl"

Did you mean this?
	top

➜  ~ kubectl describe pod tiller-deploy-548fd5dc4f-n8ntf
Error from server (NotFound): pods "tiller-deploy-548fd5dc4f-n8ntf" not found

**Comment by bacongobbler** [comment]
That's because the namespace is missing. Sorry. Use `kubectl -n kube-system describe pod tiller-deploy-548fd5dc4f-n8ntf`.

**Comment by ChaosCodes** [comment]
oho, I get the error message, I seems that I fail to pulling the image

➜  ~ kubectl -n kube-system describe pod tiller-deploy-548fd5dc4f-n8ntf
Name:               tiller-deploy-548fd5dc4f-n8ntf
Namespace:          kube-system
Priority:           0
PriorityClassName:  <none>
Node:               minikube/10.0.2.15
Start Time:         Wed, 07 Aug 2019 13:20:39 +0800
Labels:             app=helm
                    name=tiller
                    pod-template-hash=548fd5dc4f
Annotations:        <none>
Status:             Running
IP:                 172.17.0.11
Controlled By:      ReplicaSet/tiller-deploy-548fd5dc4f
Containers:
  tiller:
    Container ID:   docker://4b64b5e8a8eebedde5048652ff22a72f15b3e579fc93e69d1382f1e91e791a73
    Image:          gcr.io/kubernetes-helm/tiller:v2.14.3
    Image ID:       docker-pullable://gcr.io/kubernetes-helm/tiller@sha256:c09393087c4be55023f86be979a9dfe486c728703eba996344adc9783f261baa
    Ports:          44134/TCP, 44135/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Running
      Started:      Wed, 07 Aug 2019 21:38:21 +0800
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:44135/liveness delay=1s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:44135/readiness delay=1s timeout=1s period=10s #success=1 #failure=3
    Environment:
      TILLER_NAMESPACE:    kube-system
      TILLER_HISTORY_MAX:  200
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-9nbpm (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  default-token-9nbpm:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-9nbpm
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason   Age                From               Message
  ----     ------   ----               ----               -------
  Normal   BackOff  9h (x98 over 9h)   kubelet, minikube  Back-off pulling image "gcr.io/kubernetes-helm/tiller:v2.14.3"
  Warning  Failed   1h (x142 over 9h)  kubelet, minikube  Error: ImagePullBackOff

**Comment by bacongobbler** [comment]
Are you in a region where gcr.io is blocked? For example we've heard reports from people in China that gcr.io is unavailable behind the firewall.

**Comment by ChaosCodes** [comment]
Yeah, the gcr.io is blocked. But I can access part of the Internet outside through my VPN. Do you have any idea about that.

**Comment by ChaosCodes** [comment]
I found a mirror to help me get the image. Thanks for telling me the reason.
And there is my solution:

$ docker pull gcr.azk8s.cn/kubernetes-helm/tiller:v2.14.3

Now it works.
