### ISSUE TITLE
Make `helm search` work against monocular search

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#6186]
When the stable repository was removed from Helm v3, people lost the ability to search out of the box. The idea is to enable default search to use the Helm Hub (an instance of monocular). Options would allow search to be pointed at another instance of monocular or to fall back to repositories stored locally. OCI based storage search isn't known yet as OCI distributions don't provide a standard search API.

The tasks as I think I see them are:

1. Create a monocular client that Helm can use to search
2. Wire up the CLI to search monocular by default or the local store with a flag
3. Figure out OCI repository search

**Comment by bacongobbler** [comment]
slating this for the beta, though we could let it slip into beta.2 if required.

**Comment by waveywaves** [comment]
@mattfarina Can I give my hand at <2> or <3> is that is fine with you. Once #6187 gets merged ?

**Comment by bacongobbler** [comment]
closed via #6211. Let's address OCI search once that's actually a part of the OCI spec. Right now that doesn't exist.
