### ISSUE TITLE
APIServer error when trying to install chart on Openshift

### ISSUE THREAD

**Issue by waveywaves** [helm/helm#6189]
After runing the following on Openshift 3.11 got an error wrt to the APIs.

```
$ ./helm install stable/mysql --generate-name
Error: could not get apiVersions from Kubernetes: unable to retrieve the complete list of server APIs: packages.apps.redhat.com/v1alpha1: the server is currently unable to handle the request, servicecatalog.k8s.io/v1beta1: the server is currently unable to handle the request
```

Output of `helm version`:
version.BuildInfo{Version:"v3.0.0-alpha.2", GitCommit:"97e7461e41455e58d89b4d7d192fed5352001d44", GitTreeState:"clean", GoVersion:"go1.12.7"}                                                                     

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-12-03T05:39:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by bacongobbler** [comment]
Are you able to determine why kubernetes is unable to handle the request?

**Comment by waveywaves** [comment]
Seems like a problem with my api server.
```
[root@shiftnode1 ~]# oc api-resources
error: unable to retrieve the complete list of server APIs: packages.apps.redhat.com/v1alpha1: the server is currently unable to handle the request, servicecatalog.k8s.io/v1beta1: the server is currently unable
to handle the request
```

Thank you for the hint :)
