### ISSUE TITLE
kubernetesVersion doesn't work for kubernetes prereleases

### ISSUE THREAD

**Issue by wongma7** [helm/helm#6190]
Error: Chart requires kubernetesVersion: >=1.13.0 which is incompatible with Kubernetes v1.15.3-beta.0

v1.15.3-beta.0 is newer than 1.13.0. I expected helm to detect this.

Consider using the version code directly from kubernetes when comparing kubernetes versions https://github.com/kubernetes/apimachinery/blob/master/pkg/util/version/version.go#L290 rather than the semver library https://github.com/helm/helm/blob/master/pkg/version/compatible.go

Similar to https://github.com/helm/helm/issues/3810 but not specific to GKE.

Output of `helm version`:
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-07T09:55:27Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.3-beta.0", GitCommit:"7823476aaac5851d51b22020c17777e5684c04c2", GitTreeState:"clean", BuildDate:"2019-08-05T09:36:27Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS

**Comment by wongma7** [comment]
Workaround is to use kubeVersion: ">=1.13.0-0"

**Comment by bacongobbler** [comment]
Working as intended. Pre-releases are masked by `1.13.0`. Adding the prefix modifier allows pre-releases to be evaluated.
