### ISSUE TITLE
Proposal: Integrating test with upgrade

### ISSUE THREAD

**Issue by archelangelo** [helm/helm#6198]
It would be nice to have a command that does `helm test` and `upgrade` only when the test passed. Currently we do a separate step where a temporary release of a new version is installed into a temporary namespace and being tested while the original pods continues providing normal services to the outside. If the test went through we do an upgrade. I'm not sure if there is already such a feature or not but it certainly would be very convenient to combine the two steps into one.

**Comment by waveywaves** [comment]
@archelangelo In this case I suppose the resources would get created and if all of them ARE created and are in the running or healthy state, they would get purged from the test namespace with the output notifying the user if the test release was successful or not.

The command could be something along the lines of 
```
$ helm upgrade --test release-2 stable/testrelease
> Release release-2 SUCCESS !
```
```
or
```
$ helm upgrade --test release-2 stable/testrelease
> Release release-2 FAILED !
```

We should be able to give the resources deployed in the release or a stacktrace in a failed release.

It could also work well for a test install such as 
```
helm install --test release-2 stable/testrelease
```

**Comment by archelangelo** [comment]
@waveywaves Hi Thanks for the response! Yes, but not only that it sees all the resources being successfully deployed, it also does an automatic `helm test` to ensure the new release passes the acceptance test defined by the helm chart developer.

**Comment by archelangelo** [comment]
As @waveywaves suggested, the command could look like `helm upgrade --test release-name chart-path`

More specifically, I think this proposal needs two new features: one to implement a temporary release installation and test, the other to add a new annotation to specify unnecessary resources for the test (such as the ingress, which is not needed for the test job running inside the cluster). Correspondingly, the `helm upgrade --test` life cycle could look like this:
- Install `<release-name>-temp`. Resources (e.g. ingress) annotated `not-for-test` will not be installed
- Test `<release-name>-temp`, by running jobs under `templates/tests/`
- Delete `<release-name>-temp` and do nothing if the test fails, or...
- If the test succeeded, upgrade the original release

**Comment by bacongobbler** [comment]
We are not accepting features that will merge the functionality of two commands into one. This can already be achieved with `helm upgrade --wait && helm test`, anyways, so there's no need to integrate the two.

Regardless, I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
