### ISSUE TITLE
Error: This command needs 2 arguments: release name, chart path

### ISSUE THREAD

**Issue by tretos53** [helm/helm#6206]
Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-eks-2e569f", GitCommit:"2e569fd887357952e506846ed47fc30cc385409a", GitTreeState:"clean", BuildDate:"2019-07-25T23:13:33Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): `AWS`

What am I doing wrong?

Format: `helm upgrade [RELEASE] [CHART] [flags]`

Command: `helm upgrade kube-prometheus local/kube-prometheus -f values.yaml -f prometheus-rules.yaml --namespace monitoring –-dry-run --debug`

Error: `This command needs 2 arguments: release name, chart path`

**Comment by tretos53** [comment]
Unless helm requires release to be upgraded only from a repo that it was installed originally?

I also tried below, but I get the same error:

`helm upgrade --namespace monitoring –-dry-run --debug -f values.yaml -f prometheus-rules.yaml kube-prometheus local/kube-prometheus`

`helm upgrade kube-prometheus ./kube-prometheus-0.0.106.tgz -f values.yaml -f prometheus-rules.yaml --namespace monitoring –-dry-run --debug`

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
