### ISSUE TITLE
Add `helm env` command to get details of the environment

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#6226]
With the move to XDG paths for file locations and the removal (coming soon) of `helm init` there is no method to discover the directories helm is storing files in or other environment details. We should add a command to see these details.

**Comment by waveywaves** [comment]
Please assign this to me @mattfarina I will work on this.

**Comment by adamreese** [comment]
I found this plugin too https://github.com/adamreese/helm-env

**Comment by akashshinde** [comment]
> I found this plugin too https://github.com/adamreese/helm-env

@adamreese Is this compatible with `helm-3` ? since we are using `XDG` paths ?

**Comment by karuppiah7890** [comment]
Actually, currently it shows envs with "HELM" , "TILLER" word in it. Doesn't show XDG ones yet. But it shouldn't be a tough change to make. Just add an extra thing to the grep if you see the code

**Comment by akashshinde** [comment]
@karuppiah7890 @adamreese But I would prefer having `helm env` as internal command over  installing any external plugins.

**Comment by waveywaves** [comment]
@mattfarina can we close this as the PR is merged ? Or do we keep it open for tracking just in case.
