### ISSUE TITLE
helm install Throws Timeout Error

### ISSUE THREAD

**Issue by danchirillo** [helm/helm#6227]
**Output of `helm version`:**
Client: &version.Version{SemVer:"v2.14.3", 
Server:&version.Version{SemVer:"v2.14.3", 

**Output of `kubectl version`:**
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", 
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", 

**Cloud Provider/Platform (AKS, GKE, Minikube etc.):** 
Environment is a 3-node cluster -- built with kubeadm -- of Ubuntu 18.04.3 LTS VMs

**The Symptom**
**`helm install`** throw a timeout a timeout error:
**`$helm install stable/kubernetes-dashboard --name dashboard-demo`**
Error: Get https://10.96.0.1:443/version?timeout=32s: dial tcp 10.96.0.1:443: i/o timeout

But when I **`curl`** that URI I get an immediate response:
$ curl -k  https://10.96.0.1:443/version?timeout=32s                                      {
  "major": "1",
  "minor": "15",
  "gitVersion": "v1.15.2",
  "gitCommit": "f6278300bebbb750328ac16ee6dd3aa7d3549568",
  "gitTreeState": "clean",
  "buildDate": "2019-08-05T09:15:22Z",
  "goVersion": "go1.12.5",
  "compiler": "gc",
  "platform": "linux/amd64"
}

[**tiller pod log**](https://github.com/helm/helm/files/3502726/tiller.log)

**pods**
All pods are reporting healthy

NAMESPACE              NAME                                          READY   STATUS    RESTARTS   AGE    IP                NODE   NOMINATED NODE   READINESS GATES
kube-system            calico-kube-controllers-7bd78b474d-7sdzt      1/1     Running   3          3h2m   192.168.166.212   k8s1   <none>           <none>
kube-system            calico-node-clbm9                             1/1     Running   3          3h2m   192.168.13.130    k8s1   <none>           <none>
kube-system            calico-node-dmw79                             1/1     Running   2          152m   192.168.13.131    k8s2   <none>           <none>
kube-system            calico-node-t4qpr                             1/1     Running   2          139m   192.168.13.132    k8s3   <none>           <none>
kube-system            coredns-5c98db65d4-7jmv7                      1/1     Running   3          3h7m   192.168.166.210   k8s1   <none>           <none>
kube-system            coredns-5c98db65d4-ntz28                      1/1     Running   3          3h7m   192.168.166.211   k8s1   <none>           <none>
kube-system            etcd-k8s1                                     1/1     Running   3          3h6m   192.168.13.130    k8s1   <none>           <none>
kube-system            kube-apiserver-k8s1                           1/1     Running   3          3h6m   192.168.13.130    k8s1   <none>           <none>
kube-system            kube-controller-manager-k8s1                  1/1     Running   3          3h6m   192.168.13.130    k8s1   <none>           <none>
kube-system            kube-proxy-pch58                              1/1     Running   2          139m   192.168.13.132    k8s3   <none>           <none>
kube-system            kube-proxy-qcn4q                              1/1     Running   3          3h7m   192.168.13.130    k8s1   <none>           <none>
kube-system            kube-proxy-vvvxd                              1/1     Running   2          152m   192.168.13.131    k8s2   <none>           <none>
kube-system            kube-scheduler-k8s1                           1/1     Running   3          3h6m   192.168.13.130    k8s1   <none>           <none>
kube-system            tiller-deploy-548fd5dc4f-g2r2j                1/1     Running   2          178m   192.168.109.67    k8s2   <none>           <none>
kubernetes-dashboard   kubernetes-dashboard-5c8f9556c4-l5kvq         1/1     Running   3          3h1m   192.168.166.208   k8s1   <none>           <none>
kubernetes-dashboard   kubernetes-metrics-scraper-86456cdd8f-l92gw   1/1     Running   3          3h1m   192.168.166.209   k8s1   <none>           <none>

**Comment by danchirillo** [comment]
As a workaround, I tried starting over with helm by following this process:
1. ` helm reset -f`
2.  `rm -rf ~/.helm`
3.  Created a tiller service account exactly as shown in [Example: Service account with cluster-admin role](https://helm.sh/docs/using_helm/#example-service-account-with-cluster-admin-role) and re-inited helm
4.  Tried running `helm install `again.  Same symptom.
[tiller2.log](https://github.com/helm/helm/files/3503163/tiller2.log)

**Comment by mjnovice** [comment]
@danchirillo any progress on this one ? I am facing this too, on an arm based cluster

**Comment by gavD** [comment]
I have the same issue on a cluster of three Raspberry Pi 3s.

I am using `jessestuart/tiller:v2.15.0`, which I know isn't the standard Helm one but it runs on the Pi's ARM architecture:

```bash
helm init --service-account tiller --tiller-image=jessestuart/tiller:v2.15.0 --upgrade
# I have also tried --service-account default
```

If I SSH into my tiller pod with `kubectl exec -it -n kube-system  tiller-deploy-69798bdc66-nrfqr  -- /bin/sh` I can see that it can't find that IP address:

```$ wget https://10.96.0.1:443/version
Connecting to 10.96.0.1:443 (10.96.0.1:443)
wget: can't connect to remote host (10.96.0.1): Operation timed out```

that IP belongs to the main K8s API. From my laptop I can verify this:

```
➜ kubectl get service --all-namespaces | fgrep default
default       kubernetes      ClusterIP   10.96.0.1        <none>        443/TCP                  14d```

From the node that is running the pod (i.e. outside of K8s/Docker) I can access this IP:

```pi@blue:~ $ curl https://10.96.0.1:443/version -k
{
  "major": "1",
  "minor": "15",
  "gitVersion": "v1.15.4",
  "gitCommit": "67d2fcf276fcd9cf743ad4be9a9ef5828adc082f",
  "gitTreeState": "clean",
  "buildDate": "2019-09-18T14:41:55Z",
  "goVersion": "go1.12.9",
  "compiler": "gc",
  "platform": "linux/arm"
}```

I picked a random other container on my cluster (`kube-proxy`), installed `curl` on it, and it works fine:

```# curl https://10.96.0.1:443/version -k
{
  "major": "1",
  "minor": "15",
  "gitVersion": "v1.15.4",
  "gitCommit": "67d2fcf276fcd9cf743ad4be9a9ef5828adc082f",
  "gitTreeState": "clean",
  "buildDate": "2019-09-18T14:41:55Z",
  "goVersion": "go1.12.9",
  "compiler": "gc",
  "platform": "linux/arm"
}#```

So this seems to suggest that the container networking isn't present. On the `tiller` container, iptables is absent, I don't know enough about K8s networking yet to know if that is a factor or not, but for whatever reason, it can't see any of the cluster IPs.

**Comment by sywor** [comment]
Any news on this? I'm getting this too now

**Comment by pallinger** [comment]
I have the same error with minikube on debian buster on x86_64:

`# helm install stable/kubernetes-dashboard --name dashboard-demo
Error: Get https://10.96.0.1:443/version?timeout=32s: dial tcp 10.96.0.1:443: i/o timeout
# curl -k https://10.96.0.1:443/version?timeout=32s
{
  "major": "1",
  "minor": "17",
  "gitVersion": "v1.17.0",
  "gitCommit": "70132b0f130acc0bed193d9ba59dd186f0e634cf",
  "gitTreeState": "clean",
  "buildDate": "2019-12-07T21:12:17Z",
  "goVersion": "go1.13.4",
  "compiler": "gc",
  "platform": "linux/amd64"
}`

**Comment by nitesh-sharma-trilio** [comment]
Is there any solution for this ? I am facing this too for helm install as well as CSI

**Comment by felipellrocha** [comment]
Any solutions here? I'm also facing this issue
