### ISSUE TITLE
Surprising inconsistency between helm search and helm install

### ISSUE THREAD

**Issue by krancour** [helm/helm#6242]
The brigade team released a beta release today. The chart is versioned as `1.3.0-beta.1`. When you `helm search brigade`, this is what you see. _You see a pre-release version._

If you then `helm install brigade/brigade`, you get the latest _stable_ version-- `1.2.0`, unless, of course, you also use the `--devel` flag.

The thing that is probably surprising to many users here is that the first search result that they got (the _only_ result they got, unless they used the `-l` flag) is _not_ the thing that will be installed without the use of additional flags.

To repro:

```
$ helm repo add brigade https://brigadecore.github.io/charts 

$ helm search brigade/brigade
NAME                        	CHART VERSION	APP VERSION  	DESCRIPTION                                                 
brigade/brigade             	1.3.0-beta.1 	v1.2.0-beta.1	Brigade provides event-driven scripting of Kubernetes pip...
...

$ helm install brigade/brigade --debug --dry-run | grep "CHART PATH"
[debug] CHART PATH: /Users/kent/.helm/cache/archive/brigade-1.2.0.tgz
```

This is a surprising result that could mislead people into inadvertently installing something older than what they thought they were installing.

What I would propose as a solution is that `helm search` yield no pre-release results unless a `--devel` flag (such as `helm install`'s `--devel` flag) is used. This would make the two commands consistent with one another in that pre-released charts with neither be discovered by searches _nor_ installed unless, in either case, the user explicitly directs so.

This is, of course, a breaking change to the current behavior of `helm search`, so I would further propose that this be fixed in Helm 3 only.

**Comment by thomastaylor312** [comment]
@adamreese Should we bring this in during the beta period? Or would it be too breaking?

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
