### ISSUE TITLE
Helm v3 bindings for other languages

### ISSUE THREAD

**Issue by kamiKAZIK** [helm/helm#6245]
Since Tiller was removed from Helm v3, I have a question how to develop a client for Helm for JVM languages like Java, Scala, Groovy, etc.?

Before I could use Kubernetes Java client to create port-forwarded connection and communicate with Tiller using gRPC, but since Tiller is gone in v3, this is no longer possible. Are there any plans to add support for other languages or any suggestions?

**Comment by karuppiah7890** [comment]
Me and my team wrote an opinionated tool on top of Helm. At first we used NodeJs and used to do execute helm shell commands using nodejs standard libs, to do installs/upgrades. It was okay, things worked good. Whatever output the helm command gave, we bubbled it up to the user. 

But now that we have moved to golang, things are smoother, we have more fine grained control and can reuse the helm packages to do more stuff that we wanted to do. It depends on the kind of use case that you are trying to use Helm for. If it's straight forward and about doing the high level functionality of the helm commands, then shell execution is good I think. What are you trying to build?

**Comment by kamiKAZIK** [comment]
I need to prepare for an upgrade of backend REST API that is used to interact with helm to install and remove predefined chart releases. With Tiller and gRPC all was working splendid, but since Tiller was dropped from v3, I might even consider the worst case scenario - rewrite backend in golang and reuse helm and kubernetes Go packages...

**Comment by karuppiah7890** [comment]
That or for a minimal effort you could do shell exec call from your backend and do installations and deletions. Extra thing is - have helm binary installed with kube config configured.

**Comment by mattfarina** [comment]
There are a few options that could be pursued.

1. Run Helm as a controller in a cluster accessible via an API. There are a couple projects looking to do this
2. Shell out to helm and execute commands. This can be wrapped in an API in other languages
3. We'd need to create a spec for Helm interactions (it's on the todo list) and than create an implementation in another language

I would suggest one of the first two as they will be faster to get working.

**Comment by bacongobbler** [comment]
Closing as answered
