### ISSUE TITLE
Helm3: No --set-file support

### ISSUE THREAD

**Issue by stevebail** [helm/helm#6248]
Hi
Helm2 supports -set-file flag
Helm3 does not. Does anyone know why Helm 3 does not support --set-file?
How do you specify a filename (or path to a filename) as a value with Helm 3?

**Comment by mattfarina** [comment]
This was added to v2 after the v3 development branch was started and it has not been ported for v3, yet. This needs to be ported. PRs welcome to do so.

**Comment by unguiculus** [comment]
Ported over in #6494
