### ISSUE TITLE
helm "and" condition is not working as expected

### ISSUE THREAD

**Issue by abdul-jabbar01** [helm/helm#6250]
If I'm having following code in the `yaml` file, 
```
{{- if and .Values.istio.enabled .Values.istio.xyz.enabled -}}
```
then, **If my first condition is false**, then it **should not check for the second condition**. But here, helm is checking both of the conditions either the first condition is true or false. 

Can you please confirm that i**s it the expected output?** Because normally in all of our programming languages, if first condition is not true, then it don't check for the second one. 

To deal with this issue, I've to update my code as following and it will create a mess in all of my `yaml` files. 

```
{{- if .Values.istio.enabled  -}}
{{- if  .Values.istio.xyz.enabled -}}
```
Any response will be highly appreciated.

**Comment by mattfarina** [comment]
`and` is part of Go templates. You can read about it at https://golang.org/pkg/text/template/#hdr-Functions. You can read the code for Go 1.12 at https://github.com/golang/go/blob/release-branch.go1.12/src/text/template/funcs.go#L309
