### ISSUE TITLE
 Error: UPGRADE FAILED: failed to create patch: unable to find api field in struct HorizontalPodAutoscalerSpec for the json field "metrics"

### ISSUE THREAD

**Issue by kierenj** [helm/helm#6252]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}  Server: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.10-gke.5", GitCommit:"5aa3a95d828fe45aab3611dfc4ebdc0341fe1507", GitTreeState:"clean", BuildDate:"2019-05-29T17:25:39Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

GKE

Template: https://gist.github.com/kierenj/c6862d35eb36fa416f0c2d3fbb09ef0a

I'm trying to do an upgrade, whereby I've changed the `spec.metrics.resource.target.averageUtilization` on a `HorizontalPodAutoscaler` value.

I get:

` Error: UPGRADE FAILED: failed to create patch: unable to find api field in struct HorizontalPodAutoscalerSpec for the json field "metrics"`

The initial creation went fine, but changing this value yields the above.

**Comment by mattfarina** [comment]
Looking at the template you shared, `spec.metrics.resource.target.averageUtilization` is not valid. `spec.metrics` is an array.

How are you trying to do an upgrade?

**Comment by kierenj** [comment]
Humm, just the normal way, via helm upgrade. I dont understand how normal deploy would work but upgrade wouldn’t?

**Comment by mattfarina** [comment]
I see. `metrics` is not available on that resource version.

Take a look at the v2beta1 version of the spec ([here](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#horizontalpodautoscalerspec-v2beta1-autoscaling)) and compare it to the v1 version of the spec ([here](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#horizontalpodautoscalerspec-v1-autoscaling)). The v1 is the one used in the linked template. The links are to the 1.11 API docs as that is the listed server version.

Did you change the `apiVersion`?

**Comment by kierenj** [comment]
No - all I did was install my chart, then change the averageUtilization value and upgrade. Weird!

**Comment by mattfarina** [comment]
@kierenj  I wonder if the extra fields were silently ignored. Did you try changing the `apiVersion` to see if that works?

**Comment by amnk** [comment]
I faced this issue on GKE, where Google apparently modifies hpa with some admission webhook.

**Comment by sudermanjr** [comment]
@amnk  Did you ever find a resolution to this? If not, do you have some reference to the admission webhook in GKE that you are referring to?

**Comment by bacongobbler** [comment]
Closing as the original question raised by the OP has been answered. @sudermanjr feel free to open a new ticket if you're still experiencing issues. Thanks!
