### ISSUE TITLE
The result of command Helm get values don't include comments

### ISSUE THREAD

**Issue by Veitor** [helm/helm#6257]
I have a values file `values-production.yaml` with comments such as:
```yaml
# some other comments
# another comments
image: xxxx
```

And I use command `helm install -n=test --values=values-production.yaml some-chart` to deploy application on my Cluster. But, when I used command `helm get values test`, the result just like this:
```yaml
image: xxx
```
There is no any comments. Where is my comments? How to keep comments?

---

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/
amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-aliyun.1", GitCommit:"8cb561c", GitTreeState:"", BuildDate:"2019-05-23T11:28:17Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
[Alibaba](https://www.alibabacloud.com/en)

**Comment by mattfarina** [comment]
There are a couple things going on here. This may be difficult if not impossible to do.

First, the yaml parsers used by the Go community do not support comments. They are ignored and lost on write. The one golang yaml parser I'm aware of that handles comments is https://github.com/mozilla-services/yaml

Second, when the comments are the same or different above a field how will those be merged into the final output? This is the difficult part. A good UX for this would need to be worked out.

I would be interested in PRs that try to clean this up for Helm v3. For the YAML parsing, it might be good to add comments to the kubernetes yaml library as a start.

**Comment by Veitor** [comment]
I'm using Cloud Provider/Platform called (Alibaba Cloud)[https://www.alibabacloud.com/en](maybe you heard that). 

I deploy application through GUI panel, I can write values content with comments on GUI, then click deploy button and it will do. when I finish deploying, I execute `helm get values` on my localhost, the result is my content with comments written on GUI pannel. That means Tiller stored comments? 

I found that GUI panel as Client and Tiller Server is achieved by Alibaba itself. Their Client is different from Helm official Client, thus comments data can be post to Tiller Server. 

I Guess they did it for that users can edit release values content on GUI panel to upgrade it. It is convenient for users to edit values because they can see comments.

So maybe it is not important to add this feature to Helm v3 unless there are other benefits.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
