### ISSUE TITLE
Can I keep pvc when I execute 'helm uninstall'?

### ISSUE THREAD

**Issue by innerpeacez** [helm/helm#6260]
I want to keep the data when I delete the chart resource, so I set the reclaimPolicy of the storageClass to Retain, then I execute 'helm uninstall', but helm will delete the pvc when the resource is deployment, what should I do to keep the pvc? Could you help me? ,Thank you

Output of `helm version`:
```
{Version:"v3.0.0-alpha.2", GitCommit:"97e7461e41455e58d89b4d7d192fed5352001d44", GitTreeState:"clean", GoVersion:"go1.12.7"}
```
Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.5", GitCommit:"0e9fcb426b100a2aea5ed5c25b3d8cfbb01a8acf", GitTreeState:"clean", BuildDate:"2019-08-05T09:13:08Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}`


```
Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by mattfarina** [comment]
A commend recently left on https://github.com/helm/helm/issues/6261#issuecomment-523472128 provides a possible solution for you.

**Comment by innerpeacez** [comment]
thanks a lot

**Comment by MIHIRAJA-KURUPPU** [comment]
Here even though PVC is in the bound status, the PV is stuck in terminating status. How can I prevent it from getting in to terminating state. ( Since the PVC remains bound it is not getting deleted but stuck in the terminating state)
