### ISSUE TITLE
How to helm uninstall without delete pvc

### ISSUE THREAD

**Issue by fallenangelblog** [helm/helm#6261]
Output of `helm version`: v3.0.0-alpha.2

Output of `kubectl version`:v1.14.0

#### Hey guys. I have these files in my chart. Can I use `helm uninstall` without delete `pvc`? 
├── Chart.yaml
├── README.md
├── templates
│   ├── NOTES.txt
│   ├── _helpers.tpl
│   ├── configmap.yaml
│   ├── deployment.yaml
│   ├── ingress.yaml
│   ├── pvc.yaml
│   ├── service.yaml
│   └── serviceaccount.yaml
└── values.yaml

**Comment by okyspace** [comment]
@aswinkarthik , I tried adding helm.sh/resource-policy: keep for my pvc but when I did helm install, the pvc is still being removed. Is there any other settings required or any values in helm chart that I need to confirm?

helm version: v3.16.4
k8s version: 1.27
