### ISSUE TITLE
How to create ConfigMap from files provided at helm install

### ISSUE THREAD

**Issue by stevebail** [helm/helm#6264]
Hi
I would like to create a ConfigMap from 2 files provided at helm install using the --set-file flag.

This is what I have in my ConfigMap template:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configMap
  labels:
    #Omitted for brevity
data:
  {{- $files := .Files }}
  {{- range list .Values.firstFilename .Values.secondFilename }}
  {{ . }}: |-         #This is line 32
    {{ $files.Get . }}
  {{- end }}
```

Helm 2 is returning the following error:
$ helm install <chart-name> --name <release-name> --set-file firstFilename=abc.xml --set-file secondFilename=cdf.xml

Error: YAML parse error on rc-oam/templates/rc-oam-cm.yml: error converting YAML to JSON: yaml: line 32: could not find expected ':'

Your help is greatly appreciated!

**Comment by mattfarina** [comment]
`--set-file` is a variant of `--set` to handle setting values (e.g. for the values files). This isn't a place to pass in custom files. You'll need to take a different path to import the contents of the file.

**Comment by stevebail** [comment]
Hi Matt
Any suggestions to import instance-specific config files into ConfigMap?

-Steve

**Comment by bacongobbler** [comment]
What you're asking for has been proposed in https://github.com/helm/helm/issues/3276. I'd suggest looking at that ticket for current ideas, and we'd love to see contributions/ideas from the community on this topic.

In your particular example, you can use `.Vaules.firstFilename` in place of `$files.Get` to access the content of the file passed with `--set-file firstFilename=abc.xml`. In other words:

```
data:
  firstFilename: |-         #This is line 32
    {{ .Values.firstFilename }}
  secondFilename: |-         #This is line 32
    {{ .Values.secondFilename }}
  {{- end }}
```

There are likely cleaner ways to DRY up this template, but hopefully that gets you going in the right direction.
