### ISSUE TITLE
[Airflow chart] proper use of git secret for init-container / private git repo

### ISSUE THREAD

**Issue by dylburger** [helm/helm#6269]
Hi y'all,

I'm encountering an issue with the `stable/airflow` chart and was hoping someone may be able to point me in the right direction.

I'm currently using the following `values.yaml` file:

```
dags:
  initContainer:
    enabled: true
  git:
    url: git@github.com:org/repo.git
    secret: airflow-deploy-key
logsPersistence:
  enabled: true
  storageClass: efs
persistence:
  enabled: true
  storageClass: efs
postgresql:
  persistence:
    enabled: true
    storageClass: efs
redis:
  existingSecret: airflow-redis
```

in the attempt to pull DAGs from a private git repo, as noted in [the `init-container` instructions for the chart](https://github.com/helm/charts/tree/master/stable/airflow#use-init-container). I've created an ed25519 key and added a k8s secret with the keys and known_hosts file:

<img width="373" alt="Screen Shot 2019-08-22 at 15 09 17" src="https://user-images.githubusercontent.com/242668/63554218-ba1aed00-c4f1-11e9-939e-acac70a26d5f.png">

but I get the following warning on `helm install`:

```
> helm install --namespace default -f airflow.yaml --name "airflow" stable/airflow
2019/08/22 15:21:15 Warning: Merging destination map for chart 'airflow'. Cannot overwrite table item 'secret', with non table value: map[]
```

and a few of the Airflow pods (flower, scheduler, web, worker) are all stuck in a `Waiting: PodInitializing` state. I get no meaningful logs on my pods, just a single line on each like:

```container "airflow-scheduler" in pod "airflow-scheduler-5bc964468b-492c8" is waiting to start: PodInitializing```

and I see the following events:

<img width="672" alt="Screen Shot 2019-08-22 at 15 26 47" src="https://user-images.githubusercontent.com/242668/63554097-5ee8fa80-c4f1-11e9-888d-cbbd001737fb.png">

Output of `helm version`:

```
$ helm version
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

Output of `kubectl version`:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.10-eks-f12431", GitCommit:"f12431e9d92fa990fbbc2b52006351d381bd4bed", GitTreeState:"clean", BuildDate:"2019-07-26T01:16:21Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

AWS, EKS.

**Comment by mattfarina** [comment]
The warning you received was a YAML merging error:

```
Warning: Merging destination map for chart 'airflow'. Cannot overwrite table item 'secret', with non table value: map[]
```

`secret` has a default value of `{}`. You can see it [here](https://github.com/helm/charts/blob/02f24b0e556af7bcd724b3b2811e6fdeacc8b83a/stable/airflow/values.yaml#L446). In your YAML you have a string.

It looks like the proper format should be a string. You can see the usage [here](https://github.com/helm/charts/blob/02f24b0e556af7bcd724b3b2811e6fdeacc8b83a/stable/airflow/templates/deployments-web.yaml#L203). I would suggest a PR against the airflow chart to fix this.

**Comment by dylburger** [comment]
Great, thank you @mattfarina . Just to confirm, you're saying the default value of `dags.git.secret` should be:

```yaml
secret: ""
```

Is that right?

I can definitely file a PR. Thanks for the quick help.
