### ISSUE TITLE
helm upgrade --wait should fail when pods are still stuck at init state

### ISSUE THREAD

**Issue by ericsuhong** [helm/helm#6270]
For example, I am installing a prometheus chart using this command:

`helm upgrade --install --atomic --wait --timeout 2700 ...`

Sometimes, some pods do not actually finish installing, and they are stuck in "init" state (due to failing to get PVC claim):

kube-system    prometheus-server-bfdc4794-jjkm8               0/3     Init:0/2            0          6m1s

However, helm still thinks the chart installation succeeded!

Ideally, helm should treat this as a failure and rollback to older revision since I am using --atomic and --wait flags.

Output of `helm version`:

Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Azure, using aks-engine

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
