### ISSUE TITLE
Config map from an INI file

### ISSUE THREAD

**Issue by zodraz** [helm/helm#6276]
Hi,

I am trying to create a configmap from an INI file like this:

INI file contents below:

TEST_ENVIRONMENTVARIABLES1=TENV1VAL
TEST_ENVIRONMENTVARIABLES2=TENV2VAL
TEST_ENVIRONMENTVARIABLES3=TENV3VAL

And the configmap on the helm chart is:

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "env.configmap.fullname" . }}
  namespace: {{ .Release.namespace }}
  labels:
    app: {{ template "env.configmap.name" . }}
    chart: {{ template "env.configmap.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    version: {{ .Chart.Version }}

data:
{{ .Files.Get "configs/demo.cfg" | indent 2}}

The problem here is that helm doesn't like not having a property like before data like config.json and the multiple literal after (just like this)
data:
  config.json: |-

And prompts an error like this:

 helm install .\env-configmap-1.0.0.tgz
Error: release looming-mink failed: ConfigMap in version "v1" cannot be handled as a ConfigMap: v1.ConfigMap.Data: ReadMapCB: expect { or n, but found ", error found in #10 byte of ...|","data":"﻿TEST_EN|..., bigger context ...|{"apiVersion":"v1","data":"﻿TEST_ENVIRONMENTVARIABLES1=TENV1VAL TEST_ENVIRO|...

I've tried to use:
{{ (tpl (.Files.Glob "configs/__env__").AsConfig . ) | indent 2 }}

But this gives so mention config.json like property.

Note that this is a total valid kubectl command:

kubectl create configmap env-configmap --from-env-file=demo.cfg

And creates a plain json like object for the configmap.

Thanks

**Comment by zodraz** [comment]
Hi,

I'd like to happen the first scenario. End up in a configmap reformatted as YAML like this:

data:
  a: a
  b: b

Cheers

**Comment by zodraz** [comment]
Hi,

No comments about the issue?Is it possible to do or I must rely on Kubectl?

Thanks

**Comment by mr-falken** [comment]
Same here, workaround using kubectl...but using just helm would be the best solution possible.

**Comment by dexter2305** [comment]
any update on this issue? this issue is still appearing.  I am not able to understand the issue especially when no such errors are reported when --debug --dry-run switches are used along with helm install.  

Can someone explain what exactly is the issue?

**Comment by bacongobbler** [comment]
> Can someone explain what exactly is the cause of the issue?

Poor output formatting resulting in malformed YAML. In other words, the rendered template is invalid YAML, and therefore cannot be installed.

Can you demonstrate your use case and the issue you're running into? Have you tried with helm 3?

**Comment by cradules** [comment]
Hi.  Using helm:

value.yaml
```
config: |-
  [DEFAULT]
  refresh = 0

  [aws/proxyv2]
  image = proxyv2
  tag = 1.7.0
  source-repository = istio
  project = istio

  [aws/mixer]
  image = mixer
  tag = 1.7.0
  source-repository = istio
  project = istio

  [aws/pilot]
  image = pilot
  tag = 1.7.0
  source-repository = istio
  project = istio
```
configmap template:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dmi.fullname" . }}-configuration
data:
{{- range  $val := toStrings .Values.config }}
  config.ini: |-
{{ $val | indent 4}}
{{- end }}
```
