### ISSUE TITLE
Can I run a job pre-deploy?

### ISSUE THREAD

**Issue by Leekao** [helm/helm#6281]
Not really an issue, I'm trying to get helm to run a job in the middle of an install, the job should run after the configmaps were set but before the pods are starting to deploy, is it even possible using current hooks? is there a pre-deploy hook or something like that?

**Comment by towolf** [comment]
That's one of the most common usages of hooks.

Add to both ConfigMap and Job `helm.sh/hook: pre-install`. 

Add to Job `helm.sh/hook-delete-policy: hook-succeeded`.

**Comment by mattfarina** [comment]
You can learn about the hooks at https://helm.sh/docs/charts_hooks/#hooks
