### ISSUE TITLE
Sub-chart deleting order

### ISSUE THREAD

**Issue by ThilinaManamgoda** [helm/helm#6283]
Is there a way to control the sub chart deleting order?. For example lets' assume the chart **A** is a dependency for chart **B**. When we execute `helm del <RELEASE_NAME>`, instead of deleting both charts **A** and **B** at the same time, delete chart **A** before chart **B**. 

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"} 
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.5", GitCommit:"51dd616cdd25d6ee22c83a858773b607328a18ec", GitTreeState:"clean", BuildDate:"2019-01-16T18:24:45Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.8-gke.10", GitCommit:"f53039cc1e5295eed20969a4f10fb6ad99461e37", GitTreeState:"clean", BuildDate:"2019-06-19T20:48:40Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE

**Comment by mattfarina** [comment]
There is not. There are other tools built on top of Helm that allow ordering to be controlled. For example, OpenStack needs ordering controlled and they use Armada that last I looked.

Kubernetes is declarative. In theory order should not matter. This is the case often argued. Some applications do require ordering and some tools have been created to help with that.

**Comment by ThilinaManamgoda** [comment]
@mattfarina Thanks for the response. Although order doesn't matter In Kubernetes we can still control the order with Init containers. For example it is possible to wait until database getting ready before starting the main application. It would be better if we can have the similar approach for deleting the stack(delete database at last).

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!

**Comment by daodennis-ri** [comment]
Is this still the case?

**Comment by joejulian** [comment]
Yes. Kubernetes is a declarative system. When you need imperative processes, that's usually when you want to create an operator.
