### ISSUE TITLE
could not find repository file in helm3.0.0-beta1

### ISSUE THREAD

**Issue by pmkc** [helm/helm#6287]
Error:
```
$ helm repo update                                                                          
Error: couldn't load repositories file (): open : no such file or directory
```

`helm add repo` seems to work fine

I tried deleting ~/.helm, running `helm init`, using an instatllation that I had started with the alpha. nothing worked.

Output of `helm version`:
version.BuildInfo{Version:"v3.0.0-beta.1", GitCommit:"f76b5f21adb53a85de8925f4a9d4f9bd99f185b5", GitTreeState:"clean", GoVersion:"go1.12.9"}

**Comment by monchaio** [comment]
Found same issue.

helm repo update
Error: couldn't load repositories file (): open : no such file or directory

**Comment by rimusz** [comment]
facing the same issue, it breaks usage of `helm3.0.0-beta1`

**Comment by hickeyma** [comment]
Closing as PR #6292 merged.

**Comment by hickeyma** [comment]
Thanks for the fix @akashshinde

**Comment by tleveque** [comment]
I have same issue. 

helm repo update
Error: couldn't load repositories file (): open : no such file or directory

Is there any workaround except waiting for new beta2 release ?
Thanks

**Comment by hickeyma** [comment]
@tleveque You can do a build from the `dev-v3` branch.

**Comment by rimusz** [comment]
we should cut a new release of beta 2 ASAP, as beta 1 is useless as no charts can be installed

**Comment by hickeyma** [comment]
Sure @rimusz, we will look to do it asap.

**Comment by rimusz** [comment]
as we want good UX, and most of the users will not build it themselves :-)

**Comment by hickeyma** [comment]
I agree @rimusz . I was just giving @tleveque a work around in the meantime.
