### ISSUE TITLE
version

### ISSUE THREAD

**Issue by i850899** [helm/helm#6288]
Output of `helm version`:

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by karuppiah7890** [comment]
@i850899 Could you please post more details in the issue ? Like what command was executed and the issue along with the details in the template

**Comment by hickeyma** [comment]
@i850899 What is the output of `helm version`?

**Comment by bacongobbler** [comment]
Closing due to lack of information.
