### ISSUE TITLE
Helm v3 template command  is missing flags that v2 have

### ISSUE THREAD

**Issue by wilmardo** [helm/helm#6290]
Output of `helm version`:

```
# helm version
version.BuildInfo{Version:"v3.0.0-beta.1", GitCommit:"f76b5f21adb53a85de8925f4a9d4f9bd99f185b5", GitTreeState:"clean", GoVersion:"go1.12.9"}
```

Helm 2:

```console
$ helm template --help
[....]

Flags:
  -x, --execute stringArray      Only execute the given templates
  -h, --help                     help for template
      --is-upgrade               Set .Release.IsUpgrade instead of .Release.IsInstall
      --kube-version string      Kubernetes version used as Capabilities.KubeVersion.Major/Minor (default "1.14")
  -n, --name string              Release name (default "release-name")
      --name-template string     Specify template used to name the release
      --namespace string         Namespace to install the release into
      --notes                    Show the computed NOTES.txt file as well
      --output-dir string        Writes the executed templates to files in output-dir instead of stdout
      --set stringArray          Set values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)
      --set-file stringArray     Set values from respective files specified via the command line (can specify multiple or separate values with commas: key1=path1,key2=path2)
      --set-string stringArray   Set STRING values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)
  -f, --values valueFiles        Specify values in a YAML file (can specify multiple) (default [])
```

Helm 3:

```console
$ helm template --help

Flags:
      --atomic                   if set, installation process purges chart on fail. The --wait flag will be set automatically if --atomic is used
      --ca-file string           verify certificates of HTTPS-enabled servers using this CA bundle
      --cert-file string         identify HTTPS client using this SSL certificate file
      --dependency-update        run helm dependency update before installing the chart
      --devel                    use development versions, too. Equivalent to version '>0.0.0-0'. If --version is set, this is ignored.
      --dry-run                  simulate an install
  -g, --generate-name            generate the name (and omit the NAME parameter)
  -h, --help                     help for template
      --key-file string          identify HTTPS client using this SSL key file
      --keyring string           location of public keys used for verification (default "/home/usr1/.gnupg/pubring.gpg")
      --name-template string     specify template used to name the release
      --no-hooks                 prevent hooks from running during install
      --output-dir string        writes the executed templates to files in output-dir instead of stdout
      --password string          chart repository password where to locate the requested chart
      --replace                  re-use the given name, even if that name is already used. This is unsafe in production
      --repo string              chart repository url where to locate the requested chart
      --set stringArray          set values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)
      --set-string stringArray   set STRING values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)
      --skip-crds                if set, no CRDs will be installed. By default, CRDs are installed if not already present.
      --timeout duration         time to wait for any individual Kubernetes operation (like Jobs for hooks) (default 5m0s)
      --username string          chart repository username where to locate the requested chart
      --validate                 establish a connection to Kubernetes for schema validation
  -f, --values strings           specify values in a YAML file or a URL(can specify multiple)
      --verify                   verify the package before installing it
      --version string           specify the exact chart version to install. If this is not specified, the latest version is installed
      --wait                     if set, will wait until all Pods, PVCs, Services, and minimum number of Pods of a Deployment, StatefulSet, or ReplicaSet are in a ready state before marking the release as successful. It will wait for as long as --timeout
```
Use cases:

- With helm v2 it is possible to specify the Kubernetes version when generating templates with `--kube-version`. This flag is missing in Helm v3, is this a design choice? 
Is it possible to set the Kubernetes version to generate for?

Over at ceph/ceph-csi I am working on a PR where the yaml deployments are generated from the Helm charts. So to generate deployment files for 1.13 and 1.14+ are generated by setting `--kube-version`.

- Upon running helm template traefik/ -x templates/deployment.yaml. I get the following output
Error: unknown shorthand flag: 'x' in -x

**Comment by hickeyma** [comment]
The template flags seem to have been removed in 2571dbf82feb2697c9434bd6b2a69c4491b74100. @adamreese any reason why they were removed> Should some/all of them be added back in?

**Comment by wilmardo** [comment]
@hickeyma This is now somewhat of a catchall issue, for example #6305 isn't a dupe, it is related to #5887

**Comment by waveywaves** [comment]
I would like to work on this can you assign this to me ?

**Comment by hickeyma** [comment]
@waveywaves I would like to get feedback first from @adamreese and then can assign it.

**Comment by waveywaves** [comment]
@wilmardo Thanks for that. 
@hickeyma I understand that the piece of functionality does not exist due to https://github.com/helm/helm/pull/5888 and design decisions based off of lua, but it made it convenient for someone like me who works with kustomize and helm together and uses helms templating capabilities for individual file. It makes sense to just block a functionality while the other is executing, removing it.. I dunno. The templating functionality in that case can be moved to actions in that case so that something like a flag doesn't come in between.

**Comment by bacongobbler** [comment]
The `-x` flag was removed intentionally in preparation for the Lua engine as well as Library Chart support. We weren't sure if we wanted to allow partial template execution as it may mess up how the Lua engine depends on certain templates, or that certain templates may rely on others (in terms of library charts).

Apologies for not properly communicating this out. We discussed this earlier in #5365.

**Comment by bacongobbler** [comment]
As for the `--kube-version` flag, that was probably just an oversight when we were consolidating the codepaths for `helm install` and `helm template`. If someone wants to take a crack at implementing that one, that'd be great to get back in.

**Comment by hickeyma** [comment]
@bacongobbler We discussed the flag issue at dev meeting last Thursday. @technosophos would like to review all the flags again and see which flags make sense to be re-introduced.

**Comment by bacongobbler** [comment]
quick update: `helm template --execute` was replaced with `helm template --show-only`. The name was changed, but the expected input/output is identical.

**Comment by illidan80** [comment]
What about template "--name" flag, which is missing in V3? Is there any replacement?

**Comment by bacongobbler** [comment]
--name is now a positional argument.

**Comment by illidan80** [comment]
@bacongobbler

Hi,

I do looking into helm template helm. Here its output:

> Usage:
>   helm template [NAME] [CHART] [flags]
> 
> Flags:
>   -a, --api-versions stringArray   Kubernetes api versions used for Capabilities.APIVersions
>       --atomic                     if set, installation process purges chart on fail. The --wait flag will be set automatically if --atomic is used
>       --ca-file string             verify certificates of HTTPS-enabled servers using this CA bundle
>       --cert-file string           identify HTTPS client using this SSL certificate file
>       --dependency-update          run helm dependency update before installing the chart
>       --devel                      use development versions, too. Equivalent to version '>0.0.0-0'. If --version is set, this is ignored
>       --dry-run                    simulate an install
>   -g, --generate-name              generate the name (and omit the NAME parameter)
>   -h, --help                       help for template
>       --key-file string            identify HTTPS client using this SSL key file
>       --keyring string             location of public keys used for verification (default "/home/digi/.gnupg/pubring.gpg")
>       --name-template string       specify template used to name the release
>       --no-hooks                   prevent hooks from running during install
>       --output-dir string          writes the executed templates to files in output-dir instead of stdout
>       --password string            chart repository password where to locate the requested chart
>       --render-subchart-notes      if set, render subchart notes along with the parent
>       --replace                    re-use the given name, even if that name is already used. This is unsafe in production
>       --repo string                chart repository url where to locate the requested chart
>       --set stringArray            set values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)
>       --set-file stringArray       set values from respective files specified via the command line (can specify multiple or separate values with commas: key1=path1,key2=path2)
>       --set-string stringArray     set STRING values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)
>   -s, --show-only stringArray      only show manifests rendered from the given templates
>       --skip-crds                  if set, no CRDs will be installed. By default, CRDs are installed if not already present
>       --timeout duration           time to wait for any individual Kubernetes operation (like Jobs for hooks) (default 5m0s)
>       --username string            chart repository username where to locate the requested chart
>       --validate                   validate your manifests against the Kubernetes cluster you are currently pointing at. This is the same validation performed on an install
>   -f, --values strings             specify values in a YAML file or a URL(can specify multiple)
>       --verify                     verify the package before installing it
>       --version string             specify the exact chart version to install. If this is not specified, the latest version is installed
>       --wait                       if set, will wait until all Pods, PVCs, Services, and minimum number of Pods of a Deployment, StatefulSet, or ReplicaSet are in a ready state before marking the release as successful. It will wait for as long as --timeout
> 
> Global Flags:
>       --add-dir-header                   If true, adds the file directory to the header
>       --alsologtostderr                  log to standard error as well as files
>       --debug                            enable verbose output
>       --kube-context string              name of the kubeconfig context to use
>       --kubeconfig string                path to the kubeconfig file
>       --log-backtrace-at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
>       --log-dir string                   If non-empty, write log files in this directory
>       --log-file string                  If non-empty, use this log file
>       --log-file-max-size uint           Defines the maximum size a log file can grow to. Unit is megabytes. If the value is 0, the maximum file size is unlimited. (default 1800)
>       --logtostderr                      log to standard error instead of files (default true)
>   -n, --namespace string                 namespace scope for this request
>       --registry-config string           path to the registry config file (default "/home/digi/.config/helm/registry.json")
>       --repository-cache string          path to the file containing cached repository indexes (default "/home/digi/.cache/helm/repository")
>       --repository-config string         path to the file containing repository names and URLs (default "/home/digi/.config/helm/repositories.yaml")
>       --skip-headers                     If true, avoid header prefixes in the log messages
>       --skip-log-headers                 If true, avoid headers when opening log files
>       --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
>   -v, --v Level                          number for the log level verbosity
>       --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging


I'm sorry, but I missing any referring to the "name" flag. What does it means "positional" ?

**Comment by bacongobbler** [comment]
> Usage:
> helm template [NAME] [CHART] [flags]

**Comment by heydonovan** [comment]
Can we add this to the documentation? It caused all our builds to fail :/

https://helm.sh/docs/topics/v2_v3_migration/

**Comment by bacongobbler** [comment]
Which flag in particular?

**Comment by heydonovan** [comment]
@bacongobbler That `--execute` was removed. We receive `Error: unknown flag: --execute`.

**Comment by bacongobbler** [comment]
`--execute` has now been implemented as `--show-only`. https://github.com/helm/helm/issues/6290#issuecomment-557292287

We'd certainly appreciate a PR to add that to the documentation.

**Comment by heydonovan** [comment]
@bacongobbler Thanks! I'll work on that. Missing `Error: unknown flag: --name` too. :v:

**Comment by bacongobbler** [comment]
https://github.com/helm/helm/issues/6290#issuecomment-558184227

**Comment by WarheadsSE** [comment]
@bacongobbler @hickeyma :wave:  ... what ever came of `--kube-version`?
