### ISSUE TITLE
Non working zsh autocompletion script

### ISSUE THREAD

**Issue by izinovik** [helm/helm#6291]
Looks like helms completion script for zsh does not work properly.

```
$ source <(helm completion zsh)
$ helm <TAB>
helm _helm_root_command:12: bad math expression: operand expected at `"del"'
```

```
$ zsh --version
zsh 5.4.2 (x86_64-ubuntu-linux-gnu)
```

Output of `helm version`:
```
$ helm version --client --short
Client: v2.12.3+geecf22f
```

**Comment by hickeyma** [comment]
@izinovik Can you test with the latest version of Helm to see if it is fixed for you?

**Comment by izinovik** [comment]
I installed helm 2.14.3 for Linux and completion script works without any troubles.
