### ISSUE TITLE
"helm get" should show details from Chart.yaml

### ISSUE THREAD

**Issue by regentov** [helm/helm#6304]
[Documentation](https://github.com/helm/helm/blob/master/docs/helm/helm_get.md) on "helm get" states that you can retrieve "The chart used to generate the release".

This is not completely true since the contents of Chart.yaml can not be retrieved (and even is not stored in appropriate TILLER-NAMESPACE's configmap).

The Chart.yaml often contains important info such as "description", "home", "sources" and currently there is no way to retrieve this info about some charts installed with helm.

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}

```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.5", GitCommit:"0e9fcb426b100a2aea5ed5c25b3d8cfbb01a8acf", GitTreeState:"clean", BuildDate:"2019-08-05T09:21:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.5", GitCommit:"0e9fcb426b100a2aea5ed5c25b3d8cfbb01a8acf", GitTreeState:"clean", BuildDate:"2019-08-05T09:13:08Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
baremetal

**Comment by hickeyma** [comment]
It does provide most details of the chart templates that deploy the release. There are probably some fields that could be displayed that are stored but not shown. @regentov  Would you like to work on a PR to extend the output?

**Comment by regentov** [comment]
> There are probably some fields that could be displayed that are stored but not shown. 

As far as I understand, not a single "optional" field from [Chart.yaml docs](https://helm.sh/docs/developing_charts/#the-chart-yaml-file) is stored.

So they should be (1) stored and (2) displayed. 
Cannot do the PR.

**Comment by waveywaves** [comment]
I will be working on this @hickeyma :)
Do assign this to me.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

**Comment by regentov** [comment]
The [fields](https://v2.helm.sh/docs/developing_charts/#the-chart-yaml-file) from Chart.yaml are still absent in helm2's "helm get release". As well as in helm3's "helm get all".
