### ISSUE TITLE
Rendering helm chart locally side-effects its dependencies, preventing re-render of the same chart 

### ISSUE THREAD

**Issue by kdorosh** [helm/helm#6307]
`helm version`: v2.13.0 (from Gopkg.toml)

Using the golang helm client to render charts locally, we see the following behavior:

1. call [render](https://github.com/helm/helm/blob/master/pkg/renderutil/render.go#L45) on a chart with subcharts
1. render loads and checks requirements (compares the provided subcharts to the values in requirements.lock), impl [here](https://github.com/helm/helm/blob/master/pkg/renderutil/render.go#L46-L49)
    1. this passes because we haven't yet pruned subcharts that have been disabled by a provided values.yaml file
1. `render()` prunes subcharts that we aren't using [here](https://github.com/helm/helm/blob/master/pkg/renderutil/render.go#L54)

Chart renders fine, but has been side-effected. The chart's dependencies have been pruned but requirements.lock remains the same.

Now if we repeat the same steps on the same chart, the check dependencies check fails [here](https://github.com/helm/helm/blob/master/pkg/renderutil/render.go#L47). We may want to do this if we want to render and install our helm chart in stages, e.g. filtering out CRDs first and then installing the rest of the chart.

The fix or desired behavior here is either:
- Don't side-effect the provided chart
- When updating the chart dependencies, update requirements.lock to match

**Comment by bacongobbler** [comment]
Have you tested against the Helm 3 SDK by any chance? I wonder if this is still an issue in the dev-v3 branch.

**Comment by kdorosh** [comment]
I have not tested against helm 3 unfortunately :/

**Comment by bridgetkromhout** [comment]
Hi, @kdorosh - thank you again for reaching out. As this report is scoped to Helm v2, and we are no longer accepting changes to Helm v2 (https://helm.sh/blog/helm-v2-deprecation-timeline/), I am closing this issue at this time. If you do notice that it affects Helm v3, please do open a new issue. Thanks!
