### ISSUE TITLE
Helm upgrade with conditional dependencies

### ISSUE THREAD

**Issue by csupi** [helm/helm#6313]
requirements.yaml:
```json
 dependencies:
 - name: "mysql"
   version: "5.7"
   repository: "helm-repo.local"
   condition: "mysql.enabled"
```

values.yaml:
```json
"mysql": {"enabled": false}
```

With `helm install chart --name examplerelease --values values.json` the mysql subchart is not installed.

Then `helm upgrade examplerelease chart --reuse-values` ignores the `mysql.enabled=false` value and installs the mysql subchart which is not the expected behavior.
In contrast, with `helm upgrade examplerelease chart --reuse-values --set mysql.enabled=false` mysql subchart is skipped, but in this case I am forced to set again the `mysql.enabled` value.

Output of `helm version`:
> Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
> Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}

Output of `kubectl version`:
> Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-03-29T12:30:44Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
> OpenShift Origin 3.11

**Comment by bacongobbler** [comment]
did you make sure to run `helm dependency build` or `helm dependency update` before installing? The chart needs to be available in the `charts` subdirectory prior to install for it to be installed. Helm will not resolve dependencies prior to install unless you provide the `--dep-up` flag.

**Comment by csupi** [comment]
The subchart is in the charts directory.

I attached a tiny example. It contains a main chart with a configmap (configmap-main) and a subchart (with `condition: "subchart.enabled"`) also with a configmap (configmap-sub). The `subchart.enabled` is `true` by default in the chart's values.yaml file, but `false` in the used `install-values.yaml`:
```json
subchart:
  enabled: false
```

I Tried the following:

Package the helm chart:
`$> helm package main --version 0.0.1`
`Successfully packaged chart and saved it to: /home/csupi/example/main-0.0.1.tgz`

Install on OpenShift:
`$> helm install main --values install-values.yaml`
`NAME:   piquant-clownfish`
`LAST DEPLOYED: Mon Sep  9 08:13:39 2019`
`NAMESPACE: helm-issue`
`STATUS: DEPLOYED`

`RESOURCES:`
`==> v1/ConfigMap`
`NAME            DATA  AGE`
`configmap-main  1     0s`

Upgrade without any changes:
`$> helm upgrade piquant-clownfish main --reuse-values`
`Release "piquant-clownfish" has been upgraded.`
`LAST DEPLOYED: Mon Sep  9 08:13:53 2019`
`NAMESPACE: helm-issue`
`STATUS: DEPLOYED`

`RESOURCES:`
`==> v1/ConfigMap`
`NAME                DATA  AGE`
`configmap-main      1     14s`
`configmap-subchart  1     0s`

As you can see the upgrade installed the subchart despite it is disabled in the values file and release values:
`$> helm get values piquant-clownfish`
```json
subchart:
  enabled: false
```

[main.zip](https://github.com/helm/helm/files/3588868/main.zip)

Did I miss something?

**Comment by karuppiah7890** [comment]
No @csupi , doesn't look like you missed something. This clearly looks like a bug to me. Will have to check what's causing this behavior

**Comment by karuppiah7890** [comment]
This happens when using `--reuse-values` but it works fine when explicitly using `--values` during the upgrade. We'll check on this 😄

**Comment by karuppiah7890** [comment]
Similar to what I noticed in helm v3 https://github.com/helm/helm/issues/6530#issuecomment-536318742 I'm having suspicion on the processing of chart dependencies before sending to tiller in helm v2 too. And only in tiller existing values is known. Here too I have to confirm the suspicion. This is just a hunch 😅

**Comment by karuppiah7890** [comment]
The hunch for #6530 was correct and I raised a PR for it here #6556 

In v2, since there's a client and a server (tiller), I noticed that on the client side we do processing of conditions over here

https://github.com/helm/helm/blob/9fb9850aca4afab0d38bcd73218098a145b4e7ac/pkg/helm/client.go#L185-L192

I think this has to be done on the server side after getting the values - since the reuse values has been enabled - we get values only in server and then we can do the processing. And I think processing of conditions can be always be done on server side and not just when reuse values is enabled . Have to see how to write a test case for this and then try to fix it

What do you think about this @bacongobbler ? Let me know. As I don't want to put lots of effort (like this #6391) on a wrong / non viable solution and then have the PR closed 🙈 😅 for an alternative PR

**Comment by utay** [comment]
Hi there, I've got the same issue when trying to run `helm upgrade --reuse-values`: the conditional dependencies seem like ignored. Apart from migrating to helm 3, is there any workaround? I'm using helm/tiller `v2.15.2`.

**Comment by karuppiah7890** [comment]
@utay nothing that I know of. If you are interested to work on a PR for this, we can help you with it 😄

**Comment by utay** [comment]
@karuppiah7890 Erf, I'm afraid that it's worth it for us to migrate to helm 3 then... 😛But thank you for the quick response and the proposal!

**Comment by karuppiah7890** [comment]
Haha. And migrating to Helm 3 comes with lots of perks, so it's worth it !! 😄

**Comment by vikrant82** [comment]
I am still seeing this bug in
```
verrsion.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

**Comment by bridgetkromhout** [comment]
@csupi As mentioned above in this issue, we recommend moving to Helm v3, as v2 is being deprecated: https://helm.sh/blog/helm-v2-deprecation-timeline/

Please let us know if you experience problems with v3. Thanks!
