### ISSUE TITLE
Helm v3 beta 2 --debug don't show rendering template

### ISSUE THREAD

**Issue by alexandrsemak** [helm/helm#6314]
Output of `helm version`:

`version.BuildInfo{Version:"v3.0.0-beta.2", GitCommit:"26c7338408f8db593f93cd7c963ad56f67f662d4", GitTreeState:"clean", GoVersion:"go1.12.9"}`

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-26T12:59:46Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6+IKS", GitCommit:"44b769243cf9b3fe09c1105a4a8749e8ff5f4ba8", GitTreeState:"clean", BuildDate:"2019-08-21T12:48:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

Hello,

`helm upgrade --install --debug` don't show rendered template.

```
helm upgrade --install dummy wcp-twc-web-helm-virtual/web-nerf-application \
            --version=1.1.5 \
            --namespace=dev \
            --debug \
            --force
history.go:48: [debug] getting history for release dummy
Release "dummy" does not exist. Installing it now.
install.go:158: [debug] Original chart version: "1.1.5"
install.go:175: [debug] CHART PATH: /Users/osema/Library/Caches/helm/repository/web-nerf-application-1.1.5.tgz

coalesce.go:189: warning: destination for open is a table. Ignoring non-table value <nil>
client.go:68: [debug] creating 4 resource(s)
NAME: dummy
LAST DEPLOYED: 2019-08-29 13:18:30.889382 +0300 EEST m=+4.168260133
NAMESPACE: dev
STATUS: deployed

```

**Comment by karuppiah7890** [comment]
I'm able to reproduce the issue. It exists for `helm install --debug` too. Checking it

**Comment by karuppiah7890** [comment]
@hickeyma I found the issue. It's here - https://github.com/helm/helm/blob/b2d5e41fc768882264af4c0162462fe9c6df21b4/pkg/action/printer.go#L55 

The current behavior is - show manifests only when dry run is enabled. 

Is this the expected behavior? or is it one of these - Show manifests only when debug is enabled? or all the time? 

Helm v2 behavior is - show manifests only when debug is enabled

**Comment by karuppiah7890** [comment]
If manifests have to be show only when debug is enabled, we have to think about how to detect if debug is enabled. Currently `PrintRelease` function isn't aware of the `EnvSettings` settings which contains the `Debug` data. If we have to inject the settings, then we have to add another argument or something and that will break anyone using `PrintRelease` function

**Comment by karuppiah7890** [comment]
cc @bacongobbler @technosophos

**Comment by bacongobbler** [comment]
Yes, that is expected behaviour. Please use `helm upgrade --debug --dry-run` to display the templates to be rendered. [This is how `helm template` works](https://github.com/helm/helm/blob/469bb6b0bd96d7cbd37592e540773ce85c7e9405/cmd/helm/template.go#L58-L61).

**Comment by alexandrsemak** [comment]
But why this behaviour was different in helm 2? with --debug you can see exactly what you apply and if you have wrong config you don't need extra step for rendering and checking

**Comment by bacongobbler** [comment]
My mistake. The templates will render without the --dry-run flag present. This appears to have been fixed in later versions of Helm 3. Both `helm install --debug` and `helm upgrade --debug` render the templates as expected.

**Comment by alexandrsemak** [comment]
thanks
