### ISSUE TITLE
Helm 3: chart created by `helm create` fails to install when enabling the ingress

### ISSUE THREAD

**Issue by rberrelleza** [helm/helm#6319]
Repro steps:
1. `helm create hello-world`
1. `helm install hello-world ./hello-world --set ingress.enabled=true`

Output:
```
Error: apiVersion "networking.k8s.io/v1beta1" in hello-world/templates/ingress.yaml is not available
```

When I manually changed the the value in `apiVersion` of `hello-world/Chart/templates/ingress.yaml` from `networking.k8s.io/v1beta1`  to `extensions/v1beta1` I was able to successfully install the chart.

Output of `helm version`: 
```
version.BuildInfo{Version:"v3.0.0-beta.1", GitCommit:"f76b5f21adb53a85de8925f4a9d4f9bd99f185b5", GitTreeState:"clean", GoVersion:"go1.12.9"}
```

Output of `kubectl version`: 
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-gke.8", GitCommit:"7d3d6f113e933ed1b44b78dff4baf649258415e5", GitTreeState:"clean", BuildDate:"2019-06-19T16:37:16Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  GKE

**Comment by karuppiah7890** [comment]
Current docs shows `networking.k8s.io/v1beta1` - https://docs.kubernetes.io/docs/concepts/services-networking/ingress/

Looks like from k8s v1.14 they changed it to `networking.k8s.io/v1beta1` - https://v1-14.docs.kubernetes.io/docs/concepts/services-networking/ingress/

In v1.13 I can see `extensions/v1beta1` https://v1-13.docs.kubernetes.io/docs/concepts/services-networking/ingress/

Surprisingly `kubectl explain ingress` also shows `extensions/v1beta1` as the `apiVersion`

I think this is more about k8s backward compatibility. @bacongobbler Should we go with `extensions/v1beta1` for the default chart?

**Comment by mattfarina** [comment]
When 1.18 comes out in March 2020 we'll have a version of k8s that does not support `extensions/v1beta1` for `ingress`. The deprecation window is small this time around.

What about a logic statement that sets the API based on Kubernetes version?

**Comment by mattfarina** [comment]
Also, I put the timelines up at https://lists.cncf.io/g/cncf-helm/topic/psa_timelines_for_removing/32519042?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,32519042 for reference.

**Comment by karuppiah7890** [comment]
For some reason this didn't close. The PR #6448 for this got merged. This can be closed 😄
