### ISSUE TITLE
Feature request: a `helm version` option that works consistently across v2 and v3

### ISSUE THREAD

**Issue by itowlson** [helm/helm#6322]
I am consuming Helm programmatically and sometimes need to issue slightly different command syntax according to whether the user has Helm 2 or Helm 3.  I can try to detect this using `helm version` _but_...

* On Helm 2, `helm version` attempts to reach Tiller, which is potentially slow.  I can avoid this with `helm version -c` but...
* On Helm 3, `helm version -c` is an error.
* On Helm 2, `helm version --short` returns a string of the form `Client: v2.14.3+g0e7f3b6` (plus server info which can be suppress with `-c`)
* On Helm 3, `helm version --short` returns a string of the form `v3.0.0-beta.2+g26c7338` (no `Client: ` prefix)

All this makes detecting v2 vs v3 a bit fiddly.  I could issue `helm version -c` and assume v3 if I get an error, but perhaps it would be nice to continue to support `-c` as a hidden flag and have it force the output to the same format as v2?

**Comment by bacongobbler** [comment]
Redirecting the conversation back here.

A number of core maintainers have expressed concern over the design of introducing a flag initially introduced due to Tiller's introduction, which was the reason for #6670's closure.

It sounds like the current resolution is to work around this case by checking the presence of the `-c` flag in `helm version`. I'm curious to hear if this is a reasonable workaround, and if not, how other projects work around this issue

For what it's worth, I might've found another possible solution... If I remove my local kube config (or point Helm at `/dev/null`) and issue a `helm version`, I do see a connection error issued immediately after invoking the command and it returns exit code 1, but it does display the client version. I'm not sure if this addresses your issue with the `helm version` command or not, so I'll leave this ticket open for further discussion of possible solutions.

```
><> /usr/local/bin/helm --kubeconfig /dev/null version
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Error: Get http://localhost:8080/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: dial tcp 127.0.0.1:8080: connect: connection refused
><> ~/bin/helm version
version.BuildInfo{Version:"v3.0+unreleased", GitCommit:"2d5faff6a1b6e06e42ecac0d9a3ee95346635fe6", GitTreeState:"clean", GoVersion:"go1.13"}
```

**Comment by itowlson** [comment]
That's not portable though.  I can detect OS and use the DOS NUL device, but (a) that just moves the detection complexity elsewhere and (b) it doesn't work.

**Comment by hickeyma** [comment]
@itowlson I understand and appreciate the capability that you request.

However, from Helm point of view it doesn't make sense to add capability for something that no longer exists i.e. removal of Tiller and client/server architecture.  It might not be ideal for your scenario but `helm version` provides version information across both v2 and v3. 

The decision is explained in more detail in https://github.com/helm/helm/pull/6670#pullrequestreview-302451189 and https://github.com/helm/helm/pull/6670#issuecomment-542706306.

**Comment by olemarkus** [comment]
There are quite a lot of examples of cli flags that are noop just to preserve backwards compatibility. And I think it is perfectly fine to document this flag as deprecated and remove it in a future version as helm2 fades away. Even better would be if the -c flag returned the version string in helm2 format. 

During the time it takes for us to transition fully to helm 3, I see this as quite essential to our tooling.

**Comment by bacongobbler** [comment]
thanks for the vote of confidence @olemarkus. I've gone ahead and re-opened #6670 as #6868.

**Comment by marckhouzam** [comment]
For documentation purposes, a method that works right now is:
```
if helm version -c --tls &> /dev/null; then
    // v2
else
    //v3
fi
```
Note that I'm using the `--tls` flag so that this piece of code continues to work even if the `-c` flag is added to v3 as this issue is requesting.

**Comment by hickeyma** [comment]
> There are quite a lot of examples of cli flags that are noop just to preserve backwards compatibility.

@olemarkus Could you provide some examples?

**Comment by bacongobbler** [comment]
SDK calls are commonly deprecated/converted into a no-op call when it's made redundant. Have a look at the linux kernel for examples.

CLI flags are a little harder to find concrete examples for, however. I've heard of CLI flags being no-op'd to retain backwards compatibility, but I cannot find any examples at this time, especially during a major version update.
