### ISSUE TITLE
Question: Helm/K8s State Drift

### ISSUE THREAD

**Issue by monobaila** [helm/helm#6328]
I have a general question about Helm which I haven't been able to find out much about after reviewing the official documentation. I'm hoping for some clarification and potentially fixing up the documentation to make this clearer for others.

A couple times I've had issues where for unknown reasons some of the kubernetes objects which form part of a Helm release (e.g. a Deployment) has state differences from Helms view of the world (e.g. a manual `kubectl edit`).

I was surprised to learn that a helm upgrade won't necessarily undo any state differences. I'm fairly new to helm/k8s but my understanding is that helm is often referred to as a "package manager" for k8s, I seem to be struggling with this conceptually compared to traditional package management where you would expect a subsequent package upgrade to  blow away any manual changes to file(s) making up that package.

I did find this comment which quite helpfully described what's going on here - https://github.com/helm/helm/issues/5430#issuecomment-472451791

Is there a way to enforce state with the equivalent of a `kubectl apply --recursive` on each helm upgrade? Would you be able to explain why this is not the default behaviour? I'm assuming there are good reasons they're just not obvious to me! Is there anywhere in the official documentation where this is explained in more details? If not, I think it would be a valuable addition.

Thanks.

**Comment by bacongobbler** [comment]
Does the documentation in https://v3.helm.sh/docs/faq/#improved-upgrade-strategy-3-way-strategic-merge-patches answer your question?

**Comment by monobaila** [comment]
Yup that pretty much explains it! So it looks like this will become part of main documentation once Helm 3 becomes GA? If so, it might not be worth updating the existing documentation. 

Thanks for your help!
