### ISSUE TITLE
Add function to create configuration for actions in pkg

### ISSUE THREAD

**Issue by aaronmell** [helm/helm#6333]
I'm playing around with the v3 beta, and trying to refactor the terraform provider. There doesn't seem to be an easy way to create a configuration, and I feel like I am duplicating a bunch of logic from initActionConfig in cmd/helm. It would be super helpful if there some methods added to build the configuration object in pkg

**Comment by aaronmell** [comment]
Some other issues. There is a wierd dependency issue. The code wants me to import "k8s.io/helm/pkg/action"

When i run go get k8s.io/helm/pkg/release@v3.0.0-beta.2+incompatible
I get this error go build helm.sh/helm/pkg/chart: no Go files in

That leads me into dependency helm. Hoping that https://github.com/helm/helm/pull/5498
will address the dependency problems.

**Comment by bacongobbler** [comment]
If you have suggestions on how we could improve he experience around creating Configuration objects, we'd happy review PRs.

**Comment by hickeyma** [comment]
Closing as #6341 merged
