### ISSUE TITLE
apiVersion missing from v3 Chart.yaml docs

### ISSUE THREAD

**Issue by dastrobu** [helm/helm#6342]
Helm [v2 docs "the chart.yaml file"](https://helm.sh/docs/developing_charts/#the-chart-yaml-file) mention the 
```
apiVersion: The chart API version, always "v1" (required)
```
In the [v3 docs "the chart.yaml file"](https://v3.helm.sh/docs/topics/charts/#the-chart-yaml-file) this line was simply removed. When generating a chart with helm v3.0.0-beta.2 it sets the apiVersion to
```
apiVersion: v2
```
Would be nice to see the updated to v2 documented.

**Comment by bacongobbler** [comment]
https://v3.helm.sh/docs/faq/#chart-yaml-apiversion-bump

**Comment by dastrobu** [comment]
addressed by [PR 343](https://github.com/helm/helm-www/pull/343).
