### ISSUE TITLE
kubeVersion in the chart.yaml docs should be documented more thoroughly

### ISSUE THREAD

**Issue by dastrobu** [helm/helm#6343]
The [Chart.yaml docs](https://v3.helm.sh/docs/topics/charts/#the-chart-yaml-file) mention the kubeVersion property. 
```
kubeVersion: A SemVer range of compatible Kubernetes versions (optional)
```
From the documentation, it is not clear what this field is used for, except that it can be accessed from the `Capabilities` object. 
It should be made clear what a `SemVer range` is, since this is not specified in the [SemVer Spec](https://semver.org) as far as I know. It would be nice if a section on the kubeVerion field could be added, explaining what it is used for (like in [The appVersion field](https://v3.helm.sh/docs/topics/charts/#the-appversion-field)). 
If I would know what the field does, I would be happy to create a PR improving the docs.

**Comment by mattfarina** [comment]
These would be great document additions. PRs are welcome for these.

For reference, `kubeVersion` is the version of Kubernetes such as 1.15.1.

**Comment by dastrobu** [comment]
> These would be great document additions. PRs are welcome for these.

@mattfarina PR is waiting for review - comments are welcome.
