### ISSUE TITLE
Helm package --destination needs to run twice

### ISSUE THREAD

**Issue by towolf** [helm/helm#6344]
When running `helm package` with `--destination ./helm/tarballs` and this directory did not exist before, then the command needs to be run twice to succeed:

```
$ rm -rf helm/tarballs/
$ helm package .  --destination ./helm/tarballs/
Successfully packaged chart and saved it to: 
$ helm package .  --destination ./helm/tarballs/
Successfully packaged chart and saved it to: helm/tarballs/mytest-0.1.0.tgz
```
The chart tarball is only written on the second execution. 

Output of `helm version`: v3.0.0.beta.2

Output of `kubectl version`: v1.15.3

**Comment by bigpigeon** [comment]
I also encountered this problem

**Comment by wxdao** [comment]
Hi I just made a PR(#6360) to address this. It should fix your problem.

**Comment by hickeyma** [comment]
Closing as #6360 merged.
