### ISSUE TITLE
Helm3: --wait flag is not working with helm install/upgrade

### ISSUE THREAD

**Issue by ravindrakmr** [helm/helm#6348]
For me --wait flag is not working when I install or upgrade a chart. It was working with helm version 2.x , but not working with version 3.
Output of `helm version`:
version.BuildInfo{Version:"v3.0.0-alpha.1", GitCommit:"b9a54967f838723fe241172a6b94d18caf8bcdca", GitTreeState:"clean"}
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.8", GitCommit:"a89f8c11a5f4f132503edbc4918c98518fd504e3", GitTreeState:"clean", BuildDate:"2019-04-23T04:41:47Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS

**Comment by bacongobbler** [comment]
This was fixed in later releases, in particular 3.0-alpha.2 if I'm not mistaken. Please use the latest release. Thanks!
