### ISSUE TITLE
FakeClient.Delete purges release, does not match default helm client behaviour

### ISSUE THREAD

**Issue by crdueck** [helm/helm#6355]
I'm using the [FakeClient](https://godoc.org/k8s.io/helm/pkg/helm#DeletePurge) implementation to test some code that depends on a helm client. While writing these tests, I've noticed that the default behaviour of `FakeClient.Delete` method is that of a `helm delete --purge`, while the default behaviour of a real helm client does not purge.

It's clear how the release becomes "purged" from reading the implementation: https://github.com/helm/helm/blob/master/pkg/helm/fake.go#L134

The release is dropped from the FakeClient's internal slice of releases, so I wouldn't be able to query its `ReleaseStatus`, for example.

The behaviour I expected is for a deleted release to exist in a `DELETED` state, unless I provide the [DeletePurge](https://godoc.org/k8s.io/helm/pkg/helm#DeletePurge) option.

I think it would be better for the FakeClient to implement the default behaviour of a helm client, rather than some optional behaviour being enabled by default. I'd be happy to contribute a PR to amend this, but wanted to first ask whether the current FakeClient behaviour is expected/intentional.

**Comment by bacongobbler** [comment]
Can you check and confirm if this is an issue with the Helm 3 client SDK as well?

Amending this to emulate the same behavior as the default client would be a good idea.

**Comment by jabielecki** [comment]
Reviewed, doesn't seem to apply to v3.0. @crdueck please provide reproducible example if you think it is v3 related.

**Comment by bridgetkromhout** [comment]
Hi, @crdueck - thank you for reporting this. As stated above, this does not seem to apply to Helm v3. As Helm v2 is no longer supported (https://helm.sh/blog/helm-v2-deprecation-timeline/) I will close this issue now. If you can reproduce the behavior for Helm v3, please open a new issue - thanks!
