### ISSUE TITLE
Expect a int but got a float64 from values.yaml appear again

### ISSUE THREAD

**Issue by bigpigeon** [helm/helm#6369]
Output of `helm version`:

version.BuildInfo{Version:"v3.0.0-beta.2", GitCommit:"26c7338408f8db593f93cd7c963ad56f67f662d4", GitTreeState:"clean", GoVersion:"go1.12.9"}

what happen:

when I try to range int number , got the flow error

```
{{- range $i, $e := until .Values.replicaCount.nsqlookupd }}
        - -lookupd-tcp-address
        - nsqlookupd-{{$i}}.nsqlookupd:4160
{{- end }}
```

```
Error: template: nsq/templates/nsqd.yaml:57:33: executing "nsq/templates/nsqd.yaml" at <.Values.replicaCount.nsqlookupd>: wrong type for value; expected int; got float64
```

I found same issue that has been closed #4982

why does it appear again

**Comment by lkoniecz** [comment]
got the same problem here

`helm version
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}`

**Comment by andreas-eberle** [comment]
This still is an issue.

**Comment by bacongobbler** [comment]
Can you provide an example?

**Comment by andreas-eberle** [comment]
It's pretty much was initially posted. 

`values.yaml`

```
cluster:
  nodes:
    count: 3
```

`some-template.yaml`
```
{{- range $node_idx := until .Values.cluster.nodes.count }}
...
{{- end }}
```

It only works when I do something like this in the template:
```
{{- $nodeCount := .Values.cluster.nodes.count | int}}
{{- range $node_idx := until $nodeCount}}
...
{{- end }}
```

**Comment by andreas-eberle** [comment]
@bacongobbler: It looks like this still hasn't been fixed. Can you remove the stale tag?

**Comment by VengefulAncient** [comment]
Just ran into this too, used a slightly shorter workaround:
```
{{- range $node_idx := until (int .Values.cluster.nodes.count) }}
...
{{- end }}```
