### ISSUE TITLE
dependency update fails when there is a broken non helm related symlink in chart folder

### ISSUE THREAD

**Issue by mentos1386** [helm/helm#6370]
**Issue:** 

I'm getting the following error when trying to run `helm dependencies update --debug --skip-refresh CHART_PATH`:

> Error: error evaluating symlink /path/to/repo/services/service_name/node_modules: lstat /path/to/repo/build/service_name: no such file or directory

We have a symlink for `node_modules` to some other folder `../../build`, which doesn't exists localy, but dose in docker image. This is bad idea to have this, but for now we have to stick with it for now...

**Expected:**
Helm shouldn't fail if there is a broken link that doesn't affect helm at all.

**Folder structure:**
```
services/service_name
├── bin
│   .........
├── charts
│   .........
├── Chart.yaml
├── src
│   .........
├── node_modules -> ../../build/service_name/node_modules
├── package.json
├── README.md
├── requirements.lock
├── requirements.yaml
├── service.json
├── values.yaml
```

---
Output of `helm version`: 
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

Output of `kubectl version`: `not relevant`

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  `not relevant`

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

**Comment by ties-s** [comment]
I have this problem as well
