### ISSUE TITLE
version 3 beta has no init command anymore

### ISSUE THREAD

**Issue by nilskuhn** [helm/helm#6377]
Last version with `init` command is version `v3.0.0-alpha.2`. The [Quickstart Guide](https://v3.helm.sh/docs/intro/quickstart/) of version 3 beta still contains `helm init` step. And without init, helm cli isn't working correctly. I know it's a beta and initialization isn't the most important part. But if one wants to have a look to the newest version and get stuck in quickstart guide it is a little bit frustrating...

Output of `helm version`:
```
$ helm version  
version.BuildInfo{Version:"v3.0.0-beta.3", GitCommit:"5cb923eecbe80d1ad76399aee234717c11931d9a", GitTreeState:"clean", GoVersion:"go1.12.9"}
```

**Comment by bacongobbler** [comment]
Thank you for raising this. This should just be a quick amendment to the quickstart guide.

**Comment by nilskuhn** [comment]
I get errors using version 3 beta without init (without file `~/.helm/repository/repositories.yaml` to be precise).

**Comment by bacongobbler** [comment]
Can you please describe the behavior you're seeing in more detail? That way I can help determine if it's a usability bug or a documentation issue.

**Comment by nilskuhn** [comment]
helm cli version 3 beta is missing the information about the repo to look for charts, I think:
```
$ helm version                            
version.BuildInfo{Version:"v3.0.0-beta.3", GitCommit:"5cb923eecbe80d1ad76399aee234717c11931d9a", GitTreeState:"clean", GoVersion:"go1.12.9"}

$ helm show stable/mysql                 
Error: failed to download "stable/mysql" (hint: running `helm repo update` may help)

$ helm repo update      
Error: no repositories found. You must add one before updating
```
Curiously it doesn't work with version 3 beta even if local config (from version 3 alpha's `init` command) is present:
 ```
$ tree ~/.helm                                 
/home/nkuhn/.helm
├── cache
│   └── archive
│       └── mysql-1.3.1.tgz
├── plugins
├── repository
│   ├── cache
│   │   └── stable-index.yaml
│   └── repositories.yaml
└── starters
```
With verison 3 alpha it't working:
```
$ helm version
version.BuildInfo{Version:"v3.0.0-alpha.2", GitCommit:"97e7461e41455e58d89b4d7d192fed5352001d44", GitTreeState:"clean", GoVersion:"go1.12.7"}

$ helm show stable/mysql
apiVersion: v1
appVersion: 5.7.14
description: Fast, reliable, scalable, and easy to use open-source relational database
  system.
home: https://www.mysql.com/
icon: https://www.mysql.com/common/logos/logo-mysql-170x115.png
keywords:
- mysql
- database
- sql
maintainers:

...
```

**Comment by nilskuhn** [comment]
Aah, and I'm on Linux. So installation was just a download of tarball and extracting the binary.

**Comment by bacongobbler** [comment]
We removed the `stable` repository by default. See https://github.com/helm/helm/issues/6359#issuecomment-528914720 for more info.
