### ISSUE TITLE
helm-3.0.0-beta.3: unable to return non-zero exit codes other than 1 from helm plugins

### ISSUE THREAD

**Issue by mumoshu** [helm/helm#6384]
While testing [helm-diff](https://github.com/databus23/helm-diff) with helm-3.0.0-beta.3, I found that there's a regression - it is missing the fix for #4170.

`helm-diff` needs to return 1 on errors and 2 on changes detected. helm 2.x had also been returning 1 for all the non-zero exit codes from plugins but it was fixed via #4367.

I've confirmed that it isn't fixed for helm v3 and reading code from the `dev-v3` branch I've also confirmed that it misses changes from #4367.

Can we just cherry-pick the fix into the helm3 dev branch?

---

Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.0-beta.3", GitCommit:"5cb923eecbe80d1ad76399aee234717c11931d9a", GitTreeState:"clean", GoVersion:"go1.12.9"}
```

**Comment by karuppiah7890** [comment]
For some reason this didn't close even though the PR #6385 has been merged
