### ISSUE TITLE
Helm 3 install command Error: gzip: invalid header

### ISSUE THREAD

**Issue by fengye87** [helm/helm#6393]
Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.0-beta.3", GitCommit:"5cb923eecbe80d1ad76399aee234717c11931d9a", GitTreeState:"clean", GoVersion:"go1.12.9"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:09:21Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

On-premise KVM

I'm trying to install Prometheus with a newly installed helm v3-beta.3. Here's the commands I used and their outputs:

```
[root@localhost ~]# helm search hub prometheus
URL                                                     CHART VERSION   APP VERSION     DESCRIPTION                                       
...
https://hub.helm.sh/charts/stable/prometheus            9.1.0           2.11.1          Prometheus is a monitoring system and time seri...
...
[root@localhost ~]# helm install https://hub.helm.sh/charts/stable/prometheus --generate-name
Error: gzip: invalid header
[root@localhost ~]# helm install stable/prometheus --generate-name
Error: failed to download "stable/prometheus" (hint: running `helm repo update` may help)
[root@localhost ~]# helm install prometheus --generate-name
Error: failed to download "prometheus" (hint: running `helm repo update` may help)
```

Now I'm out of clues. Is this a bug or am I using the wrong command?

**Comment by bacongobbler** [comment]
I believe that's the eventual goal. The backend on the hub side hadn't been implemented yet as far as I know.

Cc @mattfarina

**Comment by ejsmith** [comment]
Yeah, I am trying to figure out how to install charts with beta 3 as well. Maybe we need to add a repo for the stable charts to get it to work similar to how it does now until the hub supports installing directly from it?

**Comment by fengye87** [comment]
Glad to know the situation here. I turned into the old repo way instead at last.

**Comment by sebgoa** [comment]
That feels like a UX issue. I ran into the same thing today.

Indeed after searching, I wanted to install the chart the "old way" but the URL shown in the search result does not seem to be a valid chart path.

You need to install the repo that contains that chart and it seems that you can only get that repo URL by going to the Hub UI.

**Comment by mattfarina** [comment]
There is a missing UX part here that needs to be rounded out. Our plan is to have `https://hub.helm.sh/charts/stable/prometheus` detect it's the helm client and redirect to the right place. It's just not implemented yet. PRs welcome.

The goal is that this should work with Helm v2 and v3. We shouldn't need changes in the helm client.

**Comment by karuppiah7890** [comment]
There's already a PR for the above - https://github.com/helm/monocular/pull/643
