### ISSUE TITLE
Use base chart version in subchart template

### ISSUE THREAD

**Issue by matankila** [helm/helm#6394]
Hey,
In base chart i use .Chart.Version as apiVersion(the version is the version of the application..).
Its a decision we made in my company, anyways we have base chart(umbrella) with 11 submodules(subcharts), the base chart has under its dir templates a template named: _deployment-config.yaml there we set a template with {{ define .. }} and all subchart use
{{ include .. }} so they are all 'inherting' it.

I need to get the base chart version in all my sub charts.

my problem is that i cant use
$.Chart.version to get base chart version for every sub chart.

the sub charts under charts arent packged artifacts, but chart dirs.

anything i have tried didnt work, i cant seem to get base chart version in any of its sub chart which including the template in the base chart 
Please let me know if theres a way .

Best regards and thanks alot!! :)

**Comment by hickeyma** [comment]
Global values are an option as sub-chart cannot access the values of a parent.  have a look at the docs and see if that helps: https://github.com/helm/helm/blob/master/docs/chart_template_guide/subcharts_and_globals.md

**Comment by matankila** [comment]
I dont have problem with global value but global chart version

**Comment by hickeyma** [comment]
Agree but not sure how you get at the chart version in the parent otherwise?

**Comment by matankila** [comment]
Supposedly with $ pointing to root dir but that didnt work.. i think its worthy calling a bug..
I hope itll be fixed..

The solution i found and again really sad its not out of the box..

The neeed is: create packaged artifact upload it for the use of other proccess.

The problem: chart version cant be accessed from subchart & i cant use install with set because other proccess doing the installation, which means it needs to be ready chart..

My solution: The packging of the chart is part of jenkins job, In this job before packaging we inject the version from the pipeline job itself to global values then packing it and uploading it to artifactory for the other proccess use.

**Comment by hickeyma** [comment]
It's good that you have found a way to do this.

I don't think that this is a bug though, as it states in docs (https://github.com/helm/helm/blob/master/docs/chart_template_guide/subcharts_and_globals.md#subcharts-and-global-values) that:
"A subchart is considered "stand-alone", which means a subchart can never explicitly depend on its parent chart. For that reason, a subchart cannot access the values of its parent."

**Comment by bridgetkromhout** [comment]
Closing as answered.
