### ISSUE TITLE
Helm local repository to act as a proxy for Chartmuseum

### ISSUE THREAD

**Issue by anthonyrichir** [helm/helm#6395]
Hello,

Is it somehow possible to use the local Helm repository (from `helm serve`) to act as a repository for a Chartmuseum instance ?
This would improve the development workflow. We would be able to package our charts in the local repository during development, then when doing a `helm dep up`, helm would be able to first check in the local repository if anything is available, if so, take it from there, and otherwise, grab it from another repo like a remote chartmuseum.

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-21T15:34:43Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.6", GitCommit:"abdda3f9fefa29172298a2e42f5102e777a8ec25", GitTreeState:"clean", BuildDate:"2019-05-08T13:46:28Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by mattfarina** [comment]
There are a couple things going on here.

First, `helm serve` has been removed from v3 due to lack of use. This is the first time I have personally seen it come up as an option in a long time.

Second, Helm should be able to cache charts locally. If the chart is local it should not need to go over the wire to fetch it. Helm already has hashes and a cache location. It should be able to use that to pull them from a local cache. This is for v3.

Would that work for you?

**Comment by goraxe** [comment]
I was looking for an example workflow for iterating locally on helm charts for v3.  The v3 docs mentioned helm serve (which is how I stumbled on this gh) -> https://v3.helm.sh/docs/topics/chart_repository/.

Having a way to package and use a local chart would be useful

**Comment by goraxe** [comment]
managed to figure it out, helm package and helm install understands tgz

**Comment by bridgetkromhout** [comment]
Thanks, @goraxe. For anyone looking in the future, the docs are https://helm.sh/docs/topics/chart_repository/#managing-chart-repositories and can be updated in https://github.com/helm/helm-www/blob/master/content/en/docs/topics/chart_repository.md#managing-chart-repositories.
