### ISSUE TITLE
Helm3 --generate-name is appended while user defined names are not

### ISSUE THREAD

**Issue by teng1** [helm/helm#6398]
Output of `helm version`:
version.BuildInfo{Version:"v3.0.0-beta.2", GitCommit:"26c7338408f8db593f93cd7c963ad56f67f662d4", GitTreeState:"clean", GoVersion:"go1.12.9"}

Output of `kubectl version`:
version.BuildInfo{Version:"v3.0.0-beta.2", GitCommit:"26c7338408f8db593f93cd7c963ad56f67f662d4", GitTreeState:"clean", GoVersion:"go1.12.9"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS

Hi I have been having the following issue with --generate-name and user specified name behaving inversely to each other, is the following behaviour intentional?

For example:
When naming myself
`helm install 1568044555 squid --dry-run`
Outbut resources are named `1568044554-squid-<resource_name>`

When using `--generate-name`
`helm install --generate-name squid --dry-run`
Output resources are named  `squid-1568044554-<resource_name>`

**Comment by teng1** [comment]
This could just be an issue on my side, I fixed the issues i was having by using 
`{{ template "..fullname" . }}-configmap`
rather than  `{{ .Release.Name }}-configmap` in template references

**Comment by karuppiah7890** [comment]
@teng1 Could you check the user specified release name and the generated name that got created using `helm ls` ?

I created a dummy chart and tried it. Works good for me, and looks like it's working as expected 😄 

[issue-6398-chart.zip](https://github.com/helm/helm/files/3591594/issue-6398-chart.zip)

When I installed and checked, this is what I saw:

```
$ helm install dummy issue-6398-chart/

$ helm ls
NAME 	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART            
dummy	default  	1       	2019-09-09 22:03:05.568145 +0530 IST	deployed	dummy-chart-0.1.0

$ kubectl get configmap
NAME                            DATA   AGE
dummy-dummy-chart               1      11s

$ helm delete dummy

$ helm install --generate-name issue-6398-chart/

$ helm ls
NAME                       	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART            
issue-6398-chart-1568046844	default  	1       	2019-09-09 22:04:04.098471 +0530 IST	deployed	dummy-chart-0.1.0

$ kubectl get configmap
NAME                                      DATA   AGE
issue-6398-chart-1568046844-dummy-chart   1      18s
```

**Comment by teng1** [comment]
Hi @karuppiah7890  I tried your example and got the same output
In  _helpers.tpl, is the behaviour that tripped me up. 
Thanks

```
{{/*
Create a default fully qualified app name.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
If release name contains chart name it will be used as a full name.
*/}}
{{- define "dummy-chart.fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- if contains $name .Release.Name -}}
{{- .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
{{- end -}}
```

**Comment by karuppiah7890** [comment]
Cool, then could you close the issue if it's resolved? 😄 As I don't have permission to close it

**Comment by jshawatsplunk** [comment]
looks great!
