### ISSUE TITLE
helm init -o json

### ISSUE THREAD

**Issue by kfox1111** [helm/helm#6399]
helm init -o json no longer produces valid json. Tested on 2.14.3. May exist before this.

**Comment by mattfarina** [comment]
Confirmed. I ran the output JSON through a validator and got:

```
Parse error on line 74:
...    "status": {}}{    "apiVersion": 
--------------------^
Expecting 'EOF', '}', ',', ']', got '{'
```

The JSON is two back to back objects with no wrapper around them.

**Comment by karuppiah7890** [comment]
@kfox1111 @mattfarina Is this a valid bug? What's the expectation for the correct output here? 

I tried checking both the `-o json` and `-o yaml`. In yaml, for having multiple documents, there's a `---` to show the start of each document, and for end there's a `...`. And that's what is being used here in the yaml output. Not sure what's the equivalent in json. I doubt if it exists. Gotta check. But when I tried `helm init -o json | kubectl apply -f` everything worked fine. I also did `helm init -o json | jq .` , where jq is a JSON querying tool, and it didn't give any error. I do agree that there are two objects, yes. It's an error if we consider it as a single object. They are separate k8s objects. I think we can use the `kind: List` and create a list containing service and deployment. But that will break the existing behavior, and I think it will affect the yaml output too, where only one document will be the output which will contain list of resources (service and deployment). I think the `kubectl apply -f` will still work with them and it works now too. Is there any specific use case we are targeting here? I would like to work on this, but I'm not sure if it's a good idea to change the behavior now

**Comment by kfox1111** [comment]
The problem I had was I could not use jq to actually manipulate the data using jq. Technically it isn't exactly valid json. I don't think there is a standard for multiple document json. So its kind of broken for anyone trying to use json to manipulate the doc before the upload.

That being said, your right, jq is taking it ok... Before, I couldn't get it to select the right things. Doing a bit more reading, I found the -s option to jq. So this does seem to work: helm init -o json | jq -s '.[0]' to select the first doc. So, jq can at least work with it with the right flags.

Your right, kind: List is probably the most compatible way with parsers as it would be proper json. It would be the most change for people trying to use it. One option would be to have another -o option. maybe -o jsonlist or someting to be a kind: List.

All in all though, not sure any of this matters anymore. 3.0 should be out imminently, 2.x has frozen from what I hear, and 3.0 doesn't use tiller.

I can close the issue if you want.

**Comment by jabielecki** [comment]
Yes, please close @kfox1111.

**Comment by hickeyma** [comment]
Closing as issues answered.
