### ISSUE TITLE
helm not listing current release

### ISSUE THREAD

**Issue by cybercorp31** [helm/helm#6401]
Hello

I had deployed an application via Helm. It was working perfectly. I had configured tiller to run locally as was recommended within AWS documentation.

However after few minutes after I logged out and logged in, when I re-ran helm ls, I did not find any output (blank). I can still see all the pods running which were deployed via helm.

I can see that tiller has created various configmaps associated with the release which I had deployed.

I had similar experience within my dev and test environments. 

Can you share why helm ls was showing release name earlier however at the later stage (without any changes), helm is not able to find the release name suddenly. Is this a bug?

Helm Version:  v2.14.3

Commands that I used to start tiller:

tiller -listen=localhost:44134 -storage=secret -logtostderr

**Comment by bacongobbler** [comment]
When ymusing the helm client, did you make sure to set the HELM_HOST environment variable or the --host flag to `localhost:44134`?

**Comment by bridgetkromhout** [comment]
Hi, @cybercorp31 - hopefully @bacongobbler's suggestions above were informative for you. Please let us know if you have additional questions. If your problem continues, please let us know if you set the HELM_HOST environment variable or the --host flag to localhost:44134. Thanks!
