### ISSUE TITLE
helm 3.0-beta 3 tries to reach cluster when --dry-run is used

### ISSUE THREAD

**Issue by avkoperskiy** [helm/helm#6404]
$ helm template /chart_dir --dry-run
Error: Kubernetes cluster unreachable

Output of `helm version`:
version.BuildInfo{Version:"v3.0.0-beta.3", GitCommit:"5cb923eecbe80d1ad76399aee234717c11931d9a", GitTreeState:"clean", GoVersion:"go1.12.9"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

**Comment by karuppiah7890** [comment]
Can confirm the bug. I tried like this - 

```
$ helm create test
$ helm template test/ --timeout 1s --debug --dry-run
install.go:158: [debug] Original chart version: ""
install.go:175: [debug] CHART PATH: /Users/karuppiahn/oss/dummy/test

Error: Kubernetes cluster unreachable
helm.go:81: [debug] Kubernetes cluster unreachable
helm.sh/helm/pkg/kube.(*Client).IsReachable
        /go/src/helm.sh/helm/pkg/kube/client.go:79
helm.sh/helm/pkg/action.(*Install).Run
        /go/src/helm.sh/helm/pkg/action/install.go:150
main.runInstall
        /go/src/helm.sh/helm/cmd/helm/install.go:219
main.newTemplateCmd.func1
        /go/src/helm.sh/helm/cmd/helm/template.go:54
helm.sh/helm/vendor/github.com/spf13/cobra.(*Command).execute
        /go/src/helm.sh/helm/vendor/github.com/spf13/cobra/command.go:762
helm.sh/helm/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        /go/src/helm.sh/helm/vendor/github.com/spf13/cobra/command.go:850
helm.sh/helm/vendor/github.com/spf13/cobra.(*Command).Execute
        /go/src/helm.sh/helm/vendor/github.com/spf13/cobra/command.go:800
main.main
        /go/src/helm.sh/helm/cmd/helm/helm.go:80
runtime.main
        /usr/local/go/src/runtime/proc.go:200
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337
```

I never knew we needed cluster connectivity to do `template` and didn't know `--dry-run` feature existed for `template`! This wasn't present in helm v2. I'll check the docs. But from the help of the command, doesn't look like we need any sort of cluster connectivity. 

```
Render chart templates locally and display the output.

Any values that would normally be looked up or retrieved in-cluster will be
faked locally. Additionally, none of the server-side testing of chart validity
(e.g. whether an API is supported) is done.
```

Also, the bug might be related to this PR https://github.com/helm/helm/pull/6255 which introduced the `Kubernetes cluster unreachable`. Gotta dig more to understand this.

**Comment by bacongobbler** [comment]
It just looks like a bug introduced with #6255. It doesn't take --dry-run into account before checking. Should be an easy fix.

**Comment by karuppiah7890** [comment]
@bacongobbler so normally template connects to cluster? and hence the `dry-run` feature?

**Comment by bacongobbler** [comment]
`helm template` should not require a connection to the cluster for it to work unless the `--validate` flag is set.

Internally, `helm template` is a `helm install --dry-run --replace` (see [here](https://github.com/helm/helm/blob/dev-v3/cmd/helm/template.go#L50-L53)). You could probably reproduce the same issue by calling `helm install --dry-run --replace`.

**Comment by karuppiah7890** [comment]
Cool. I asked to understand what the expected functionality is. 

So, from a user perspective, it looks as though the dry run feature is present because normally there's some cluster connectivity. I think we could get rid of the `--dry-run` flag? Or is there any expected functionality for it? As it also causes confusion for me about what happens when someone uses both `--dry-run` and `--validate`
