### ISSUE TITLE
Shared dependencies with different version requirements

### ISSUE THREAD

**Issue by PsyonixBarrett** [helm/helm#6406]
Output of `helm version`: tested with v2.14.3 and v3.0.0-beta.2

We have the following setup...

* common chart - a library chart / collection of chart standards that is used by our service charts
* service A - a k8s service that uses templates from common chart v 0.1.0 
* service B - another k8s service that uses templates from common chart v 0.5.0
* env - an "environment chart" that brings both service A and B together to install into a single k8s cluster.

The common chart as well as both service charts are all stored in a ChartMuseum installation. When installing the env chart, helm grabs service A chart along with it's required common chart and install correctly. But when it installs service B helm uses version 0.1.0 of the common chart instead of the required version 0.5.0 of the common chart.

Not sure if this is a bug or a feature  :)

**Comment by karuppiah7890** [comment]
Not an exact replica, but I think this is at least related to #5866 . Will try the above too and ping here 😄

**Comment by PsyonixBarrett** [comment]
Sounds about right, thanks @karuppiah7890 ! I'll close this issue in favor of #5866 instead.
