### ISSUE TITLE
binaries not listed in Github Releases Assets

### ISSUE THREAD

**Issue by gliptak** [helm/helm#6411]
Looking at https://github.com/helm/helm/releases there are a number of signature files and two source files for each release, but the actual (platform specific) binaries do not seem to be listed.

Could the binaries also made available from Github Releases (allowing for easier mirroring)?

**Comment by karuppiah7890** [comment]
@gliptak I can see the platform specific tar balls containing binaries . Here's a screenshot: 

<img width="1038" alt="Screen Shot 2019-09-11 at 7 44 39 PM" src="https://user-images.githubusercontent.com/12808424/64704888-9f261200-d4cc-11e9-88c0-c541bb9aa396.png">

The one on the top is the one you are looking for. For example, the links that say "MacOS amd64", "Linux 386" and so on

**Comment by bacongobbler** [comment]
The only objects we host on GitHub pages are the PGP signatures. This is to ensure that should get.helm.sh be compromised, the signatures won't be rewritten as well. In fact, now that we have the KEYS file, we could probably host these signatures on get.helm.sh as well.

We will continue to host the actual release assets on get.helm.sh. Reason being is that we want to gather download metrics on the helm downloads. GitHub releases does not provide that functionality.

**Comment by gliptak** [comment]
@karuppiah7890 thank you for the pointers, but I was hoping to see them directly published to Github, so we do not need to mirror additional locations.

@bacongobbler thank you for the background. I understand the goal of gathering download statistics. But many shops have limitations on external site access (from their servers) hence they will likely mirror these downloads internally (into Artifactory/Nexus/S3/etc.) so downloads stats might not reflect reality ...
