### ISSUE TITLE
`helm test` does not allow output of logs to stdout

### ISSUE THREAD

**Issue by huang-jy** [helm/helm#6412]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.9-2+4a03651a7e7e04", GitCommit:"4a03651a7e7e04a0021b2ef087963dfb7bd0a17e", GitTreeState:"clean", BuildDate:"2019-08-16T18:57:20Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.6-gke.13", GitCommit:"fcbc1d20b6bca1936c0317743055ac75aef608ce", GitTreeState:"clean", BuildDate:"2019-06-19T20:50:07Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

I install a release and run the chart's tests against it.

I want the output of one of the test pods in the console. So right now, I have to do this:

1. Install the chart
2. Run the tests, but without the `--cleanup` switch
3. Run `kubectl logs` on the pod(s) I want to dump the logs to the console
4. Run `helm test --cleanup` again, **which will intentionally fail** since the pods already exist, but will still delete the pods. This is because while I want the logs from a specific pod (or pods) from the tests, there **may** be more pods introduced later on into the tests, so this will ensure those pods are deleted.
5. Run `helm test --cleanup` a **second time** to run the tests again, and cleanup afterwards. This is so that the test history (under `helm status`) of the chart is up to date.

Is there an easier way to do this? I'd be accepting of having all logs from all test pods being dumped.

**Comment by hickeyma** [comment]
@huang-jy I am going to direct this to @jlegrone as he is doing work on test infrastructure in Helm 3.

**Comment by hickeyma** [comment]
Thanks for the clarification @jlegrone. Closing as this is covered by Helm 2 test enhancement proposal #6020.
