### ISSUE TITLE
Docs: Elaborate on complex dependencies 

### ISSUE THREAD

**Issue by OliverEvans96** [helm/helm#6414]
Hi! I'm looking at this section in the docs: https://helm.sh/docs/charts_tips_and_tricks/#complex-charts-with-many-dependencies

I'm very curious about this type of setup, especially the Deis Workflow example, where the "umbrella chart is built from each component, and each component is tracked in a different Git repository".

The Docs say to "Check out the requirements.yaml file to see how this chart is composed by their CI/CD pipeline."

Unfortunately, it seems that the Deis workflow is no longer maintained, and their CI pipeline is no longer active. So I'm not really sure what I'm looking at in their `requirements.yaml`, namely where the `<*-tag>` values are coming from.

I would love to see a little bit more detail in the Helm docs in this section to explain the design pattern that Deis workflow exemplifies.

Thanks a lot!
Oliver

**Comment by hickeyma** [comment]
@bacongobbler Deis workflows!

**Comment by bridgetkromhout** [comment]
Hi, @OliverEvans96 - Apologies for the delayed reply. Much has changed in Helm 3, and you may find that the info in https://helm.sh/docs/topics/library_charts/ and https://helm.sh/docs/chart_template_guide/subcharts_and_globals/ is relevant to your question. Please let us know if you have further questions; thanks!
