### ISSUE TITLE
v3: helm list doesn't throw an error when it can't reach the API

### ISSUE THREAD

**Issue by tongpu** [helm/helm#6419]
Output of `helm version`: `version.BuildInfo{Version:"v3.0.0-beta.2", GitCommit:"26c7338408f8db593f93cd7c963ad56f67f662d4", GitTreeState:"clean", GoVersion:"go1.12.9"}`

Output of `kubectl version`: `Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): n/a

When using `helm list` to list releases in helm v3 no error is thrown and an empty list is being shown when helm can't reach the API. This possibly also affects situations where the user might not have access to secrets created by helm.

It's possibly related to `TODO return error` on line 97 in [cmd/helm/helm.go](https://github.com/helm/helm/blob/2c87d89a80f44764ca5fa10ca61571e6e5ed45da/cmd/helm/helm.go#L97)

Expected output:
```
# helm list
Error: ...
```

Actual output:
```
# helm list
NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART
```

**Comment by karuppiah7890** [comment]
@tongpu Awesome! You can ask for help if you need anything 😄

**Comment by waveywaves** [comment]
@tongpu I agree that there is a difference between the error messages to be given. Do give it a try and get in touch.

**Comment by rishiraaz** [comment]
still facing the issue.
helm version
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
