### ISSUE TITLE
Without Operator Not Working As Expected

### ISSUE THREAD

**Issue by jmlogan** [helm/helm#6420]
Output of `helm version`: version.BuildInfo{Version:"v3.0.0-beta.2", GitCommit:"26c7338408f8db593f93cd7c963ad56f67f662d4", GitTreeState:"clean", GoVersion:"go1.12.9"}

Output of `kubectl version`: n/a

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  n/a

I am trying to remove elements from a list, and it seems like the prescribed way to do this is the without() operator[1]. The following statement I would expect to output an empty list, but it instead returns a list of size one, with the element "a".

`{{ without ((list ("a")) "a") | quote }}`

[1] http://masterminds.github.io/sprig/lists.html

**Comment by hickeyma** [comment]
@technosophos @mattfarina ^^

**Comment by mattfarina** [comment]
@jmlogan I'm sorry I was slow in responding to this. I only saw it now. I have too many notifications.

The issue has to do with all the parentheses.  For example it shouldn't be `list ("a")`. It should be `list "a"`. The `()` are used for grouping not for passing in arguments. This is part of the go template syntax. If the extra parentheses are removed it works. See the example at https://play.golang.org/p/w3u-3bOSVIL
