### ISSUE TITLE
Proposal: Warn about unused values in values file

### ISSUE THREAD

**Issue by kurczynski** [helm/helm#6422]
When using a values file during a chart installation like `helm install --values values.yaml my-chart`, Helm doesn't tell me if I've specified values in `values.yaml` that are not consumed by the installation. For example, if I have the following `values.yaml`:
```
db:
  username: "admin"
```
and my Helm chart is looking for `{{ .Values.db.user }}`, the install continues without using what's in my `values.yaml`. Although this is expected behavior, it's been very difficult for me to track these errors down for charts with larger values files or subcharts.

Having Helm notify me if there were values in my `values.yaml` that were not consumed would help make the error more apparent. Using the example above, outputting something like:
```
Warning: value db.username not consumed
```

It would also be really nice if there was an option to fail the install if there were unused values. Again, using the example above:
```
helm install --strict-consume --values.yaml my-chart
```
would fail the installation.

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS, Minikube

**Comment by kurczynski** [comment]
@karuppiah7890 yes I would! Okay, I'll do it for v3. Awesome, thanks 😃

**Comment by desaintmartin** [comment]
This feature would be really nice. Ideally, it should have a strict mode that makes the command fail instead of just warn.

**Comment by TheodorAtBud** [comment]
Is there any progress here?

**Comment by karuppiah7890** [comment]
@kurczynski Are you working on this? Or someone else could pick it up :)

**Comment by kurczynski** [comment]
I've looked into it but haven't had the time to get started. If anyone would like to work on it, have at it :-D

**Comment by seanhoughton** [comment]
I would have expected the values.schema.json feature to deal with this problem. Unfortunately, it doesn't complain about extra values either - which is very surprising given that unexpected field values should count as a schema violation.

Having configuration accidentally exist at the wrong place in a values.yaml file is a fairly common mistake and without careful inspection of the generated output it's very easy to miss.

Please consider adding this feature to the schema validator and ideally as an option for schema-less values.

**Comment by karuppiah7890** [comment]
@seanhoughton You can use the `values.schema.json` to get errors when some unknown / unexpected / extra fields are provided as input. Example

```json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "affinity": {
            "type": "object"
        },
        "autoscaling": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"

**Comment by karuppiah7890** [comment]
cc @kurczynski

**Comment by seanhoughton** [comment]
Thanks @karuppiah7890 , that's why I edited my post and mentioned that it's a reasonable alternative.

**Comment by karuppiah7890** [comment]
Ah okay. I thought you were proposing something else as an alternative

**Comment by karuppiah7890** [comment]
If user provided schema can help, can you elaborate what feature you want to add to Helm? I didn't get that part

**Comment by seanhoughton** [comment]
Creating a schema is a reasonable solution for helm charts you control. However, there are many existing helm charts that don't have schemas and are used either directly or as dependencies. The external dependencies sometimes contain poor documentation or complex value hierarchies and it's very easy to make mistakes due to unfamiliarity and lack of error checking. It would be helpful to have some basic linting features for these helm charts without schemas. 

One alternative might be to auto-generate a schema for everything internally (or in our CI pipeline somehow) using the existing default `values.yaml` file and lint against that. However, if the author has a lot of commented out or missing example values this won't work well.

Ultimately all charts should get schemas which would make this issue moot.

**Comment by karuppiah7890** [comment]
Makes sense. I'll check more into this. And auto generating schema makes sense but yeah, like you said, it might not be exactly a complete solution depending on the chart. I've worked on schema auto gen before (https://github.com/karuppiah7890/helm-schema-gen) . I'll see if some basic issues can be caught with the help of plugins. But I cannot comment on bringing this feature to the core of helm. I'll let the core maintainers comment on it

**Comment by christarazi** [comment]
This feature would still be useful, without having to generate a schema.

**Comment by drewgonzales360** [comment]
👋 Hey folks. I'm going to try taking a whack at this, but I'll need some help. I'll look for y'all in slack

**Comment by drewgonzales360** [comment]
👋 Hey folks, I have https://github.com/DataDog/k8s-platform-resources/pull/5604 ready for review and was hoping someone in this thread could take a look.

**Comment by sebastiandero** [comment]
Hey guys, just dropping [this germ](https://json-schema.org/understanding-json-schema/reference/object#additionalproperties) for your values.schema.json:

`"additionalProperties": false`

works like a charm for us
