### ISSUE TITLE
Assistance in running a sha256 function that returns bytes?

### ISSUE THREAD

**Issue by arielb135** [helm/helm#6424]
Hello, I've created a kubernetes operator with custom CRD for RabbitMQ that creates objects as specified in the object.
One of my problems is that it expects a password, or a password hash.
Password is obviously not secured enough to supply outside of a secret (i could add it as a secret and make my operator rbac for cluster wide secret read - but it seems too permissive to do)

So i'm trying to replicate the following algorithm: 
https://stackoverflow.com/questions/41306350/how-to-generate-password-hash-for-rabbitmq-management-http-api

- Generate 4 letters and concat it with the password = Possible
- Take the sha256 hash of the above = not possible, as it gives me the string HEX representation, instead of a byte array
- i need to then concat the salt (4 letters) to the byte array from before
- Then turn it into base64

Is there any way i can achieve the above? the biggest problem is that the sha256 function converts the result into a string..
Any way to maybe add a hook that creates the above hashed password?

Thanks

**Comment by mattfarina** [comment]
If this is an operator, can you share the relation to Helm and how you are using Helm. I'm not sure how to provide and guidance without knowing how or where you're using Helm.

**Comment by arielb135** [comment]
Yes, i expect to generate a hash value and then pass it to my application - via environment variable, the issue is that i need to perform the sha256 on bytes, and not to get their hex representation
