### ISSUE TITLE
Helm still convert integer value into a scientific notation of type float64

### ISSUE THREAD

**Issue by zackijack** [helm/helm#6431]
When we set a value of type integer that's more than 6 digits long, Helm will convert the value into a scientific notation of type float64, e.g. 1234567 will be converted into 1.234567e+06.

This issue has been raised before: #1707 . The issue is closed but it's still happening.

Output of `helm version`: 
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:36:28Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.3-gke.11", GitCommit:"cde86d2e1416a0c6c4bb964e1a13e8fa0a83a616", GitTreeState:"clean", BuildDate:"2019-08-12T20:57:47Z", GoVersion:"go1.12.5b4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

**Comment by bacongobbler** [comment]
I don't recall that commit being cherry-picked into the 2.14 release. Can you check and see if it's still an issue on master using the canary release?

**Comment by zackijack** [comment]
@bacongobbler yap, the problem doesn't appear on master.

**Comment by bacongobbler** [comment]
Closing as resolved.
