### ISSUE TITLE
Helm 2 and Helm 3 release version storage can clash

### ISSUE THREAD

**Issue by hickeyma** [helm/helm#6435]
Helm 2 and Helm 3 use the same naming convention for release versions. It is as follows:

`RELEASE-NAME.v1 ..... RELEASE-NAME.vN, where 'N' is the incremental number of versions of the release RELEASE-NAME`

This storage for Helm 2 is as follows:
```console
$ kubectl get configmap/secret -n kube-system -l "OWNER=TILLER"
NAME         DATA   AGE
chrt-v2.v1   1      42s
chrt-v2.v2   1      12s
```

and for Helm 3:
```console
$ kubectl  get secrets -n default
NAME                  TYPE                                  DATA   AGE
chrt-v2.v1            helm.sh/release                       1      15s
chrt-v2.v2            helm.sh/release                       1      15s
```

Helm 2 and Helm 3 can be installed concurrently to manage the same cluster. This works when Helm 2 uses `ConfigMaps` for storage as Helm 3 uses `Secrets` for storage. **There is however a conflict when Helm 2 uses `Secrets` for storage and stores the release in the same namespace as the release.** The conflict occurs because Helm 3 uses different tags and ownership for the secret objects that Helm 2 does. It can therefore try to create a release that it thinks does not exist but will fail then because Helm 2 already has a secret with that name in that namespace. Here is an example of where this can occur: https://github.com/helm/helm-2to3/issues/30#issuecomment-531335572

Additionally, Helm 2 can be migrated to enable Helm 3 to manage releases previously handled by Helm 2: https://github.com/helm/helm-2to3.  This also works when Helm 2 uses `ConfigMaps` for storage as Helm 3 uses `Secrets` for storage. There is a conflict again however when using secrets because of the same naming convention. Refer to following issue for more details: https://github.com/helm/helm-2to3/issues/30

A possible solution around this would be for Helm 3 to use a different naming convention for release versions.

**Comment by rimusz** [comment]
The issue only occurs when `Tiller` releases are stored as secrets in the same namespace as application.

**Comment by hickeyma** [comment]
That is correct @rimusz. So it is an edge case in that scenario.

**Comment by mattfarina** [comment]
To add some context on name...

From [the docs](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/)...

> By convention, the names of Kubernetes resources should be up to maximum length of 253 characters and consist of lower case alphanumeric characters, -, and ., but certain resources have more specific restrictions.

The 253 characters comes from the length of a DNS subdomain. You can read about all of this in [the design proposal](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture/identifiers.md).

I want to suggest two things.

1. We tread the secret type as a versioned type. In Helm v2 the type was not set so it's Opaque. In Helm v2 the type is set to [`helm.sh/release`](https://github.com/helm/helm/blob/9a592e537970f0140cd295111c74a28ee7cc855d/pkg/storage/driver/secrets.go#L237). If we iterate on this in the future we should have a version on this. It would, for example, enable us to list and filter the secrets by their `type`. For example a future update to this could be typed as `helm.sh/release.v2`.
2. To keep name uniqueness we append or prepend the helm type. For example, `sh.helm.release.v1.chrt-v2.v1`. There are 253 characters to deal with and we likely have a little room to play with. This is just an example naming pattern, using reverse DNS, to illustrate the idea.

This would let us avoid problems in future updates as well by establishing a pattern now.

There would be a problem between betas so any change should be made quickly.

Thanks @rimusz and @hickeyma for chasing this down. Upgrades are a great way to find issues like this. Love that you're doing this now so we can fix it before the RCs.

/cc @technosophos @adamreese

**Comment by rimusz** [comment]
I like the `sh.helm.release.v1.chrt-v2.v1` type naming of storing helm releases.

**Comment by hickeyma** [comment]
> I like the sh.helm.release.v1.chrt-v2.v1 type naming of storing helm releases.

Agree. It is a good naming suggestion.

@mattfarina Thanks for the insight and feedback on this.

**Comment by bacongobbler** [comment]
Is someone planning to implement this in time for the next beta release?

**Comment by hickeyma** [comment]
@bacongobbler I will do it.

**Comment by hickeyma** [comment]
Closing as #6500 now merged
