### ISSUE TITLE
Documentation seems broken

### ISSUE THREAD

**Issue by mmatur** [helm/helm#6436]
### Description

The helm documentation seems broken. The link https://helm.sh/docs/using_helm/#installing-helm does not work

It seems there are missing documentation parts:

- [Quickstart](https://helm.sh/docs/using_helm/#quickstart-guide)
- [Installing Helm](https://helm.sh/docs/using_helm/#installing-helm)
- [Kubernetes Distro Notes](https://helm.sh/docs/using_helm/#kubernetes-distribution-guide)
- [Install FAQ](https://helm.sh/docs/using_helm/#installation-frequently-asked-questions)

![image](https://user-images.githubusercontent.com/1776972/64952160-ebcc6d00-d87f-11e9-9c3d-27677c8fbc87.png)

**Comment by karuppiah7890** [comment]
Thanks @mmatur for reporting this. At first glance I didn't feel it was broken. Just noticed that the links always point to the same page. Securing helm link in https://helm.sh/docs/ should have the link as this https://helm.sh/docs/securing_installation/#securing-your-helm-installation . Would you be willing to raise a PR to fix this? It would help everyone 😄

**Comment by mmatur** [comment]
Yes I will create a PR. Thanks @karuppiah7890

**Comment by mmatur** [comment]
@karuppiah7890 To be honest I don't know how to fix this issue. 

When I check the version v2.14.0 https://v2-14-0.helm.sh/docs/using_helm/#quickstart-guide it works

![image](https://user-images.githubusercontent.com/1776972/64957942-51bff100-d88e-11e9-87d8-2d261711d0b6.png)


When the latest version here https://helm.sh/docs/using_helm/#quickstart-guide it does not work
![image](https://user-images.githubusercontent.com/1776972/64958062-89c73400-d88e-11e9-9b88-b18837a5e047.png)


As you can see there are not the same content and it seems that there are no change about that between `v2.14.0` and `v2.14.3` versions https://github.com/helm/helm/compare/v2.14.0...v2.14.3

**Comment by mattfarina** [comment]
Thanks for catching this. The navigation is part of the helm-www repo. The issue over there #284 links back here.

**Comment by mmatur** [comment]
Thanks @mattfarina. 

The correct link is https://github.com/helm/helm-www/issues/284 for the issue.

**Comment by flynnduism** [comment]
Weirdly the last Hugo build didn't correctly render all of the docs pages.

After clearing the netlify cache and rebuilding the site, the proper contents are back in place. (example [Installing Helm](https://helm.sh/docs/using_helm/#installing-helm)

Thanks for flagging this!

**Comment by bacongobbler** [comment]
Working now. Thanks for the report!
