### ISSUE TITLE
Parameter --output in helm3 list function not available

### ISSUE THREAD

**Issue by nieselfriem** [helm/helm#6437]
Hi, 
We plan to use Helm in version 3 in the future and have already tested the current beta version (Beta 3). Unfortunately the parameter --output is not available in the list function to get the data either as json or yaml. Is this function completely removed for the future or will it be available again in the release?

Output of `helm version`:
```
Version.BuildInfo{Version:"v3.0.0-beta.3", GitCommit:"5cb923eecbe80d1ad76399aee234717c11931d9a", GitTreeState:"clean", GoVersion:"go1.12.9"}
```

Greetings niesel

**Comment by mattfarina** [comment]
This was added to v2 after the v3 branch. This feature needs to be ported over. Thanks for pointing it out and helping us catch this. It's been marked as needing to be ported now. The PR for v2 can be found at #3923.

PRs welcome for someone to bring this to v3.

**Comment by thomastaylor312** [comment]
@mattfarina Currently working on a PR as well that is adding all the output stuff to other Helm 2 things and I plan to port it all over to Helm 3. With that said, if anyone else wants output sooner and has the time, feel free to port!

**Comment by Dean-Coakley** [comment]
@thomastaylor312 Looks to me that this work has been completed.

This can be closed?

**Comment by thomastaylor312** [comment]
@Dean-Coakley thanks for the ping. I guess closing the PR didn't close this automatically
