### ISSUE TITLE
Host helm.sh is down

### ISSUE THREAD

**Issue by yunus89** [helm/helm#6438]
I try to install helm in Ubuntu terminal with this 

    curl https://raw.githubusercontent.com/helm/helm/master/scripts/get > get_helm.sh
    chmod 700 get_helm.sh
    ./get_helm.sh

Takes sometime and output following result

    Downloading https://get.helm.sh/helm-v2.14.3-linux-amd64.tar.gz
    curl: (6) Could not resolve host: get.helm.sh
    Failed to install helm
	For support, go to https://github.com/helm/helm.

**Comment by bacongobbler** [comment]
get.helm.sh seems to resolve fine for me in the UK. Can you check your network and ensure there's something local causing the connection issues?

"Could not resolve host" errors indicate a DNS issue, which can sometimes indicate your network is down/unavailable.

**Comment by yunus89** [comment]
True, my network for some weird reasons blocks this domain
