### ISSUE TITLE
release can not found

### ISSUE THREAD

**Issue by 13567436138** [helm/helm#6441]
Output of `helm version`:

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
I install with command ：helm install harbor  .  --namespace harbor
I can not uninstall，reminds me，no such release name。
helm list can see noting。
I use helm 3.0.0.Alpha

**Comment by hickeyma** [comment]
@13567436138 Can you try using the latest, [beta 3](https://github.com/helm/helm/releases/tag/v3.0.0-beta.3) and see if the issue still exists?

**Comment by 13567436138** [comment]
sorry,i was  using the latest

**Comment by 13567436138** [comment]
sorry,i was  using the latest

**Comment by bacongobbler** [comment]
You installed harbor in the "harbor" namespace. So, in order to list it, you'll need to use `helm list --namespace harbor`.

Does that help?

**Comment by hickeyma** [comment]
@13567436138 you can also use following for across namespaces: `helm list --all-namespaces`

**Comment by 13567436138** [comment]
thanks
