### ISSUE TITLE
helm 3.0.0-beta.3: `helm template` missing hook resources

### ISSUE THREAD

**Issue by mumoshu** [helm/helm#6443]
Output of `helm version`: `3.0.0-beta.3`

While we were testing helm 3.0.0-beta.3 in combination with `helm-diff`, @jonasrutishauser found that `helm template` in helm 3 misses hook outputs. That is, `helm template` misses hook resources and `helm template --no-hooks true/false` doesn't change the behavior.

Context: https://github.com/databus23/helm-diff/pull/151

To be extra clear, `helm template` in helm 2 had no `--no-hooks` and hard-coded to output hook-related k8s manifests. In helm 3, we have `--no-hooks` so to (1)to make it backward-compatible I'd like to `helm template` to include hooks in the output and (2)to make it consistent with other helm 3 commands like `install` and `upgrade`, I'd like `helm template --no-hooks` to turn output to include no hooks.

**Comment by costimuraru** [comment]
Can this issue be closed, since https://github.com/helm/helm/pull/6444 got merged?
