### ISSUE TITLE
Helm 3: with beta 3 uninstalling and installing the same plugin version it fails

### ISSUE THREAD

**Issue by rimusz** [helm/helm#6453]
```
$ helm plugin install https://github.com/helm/helm-2to3 --debug
[debug] updating https://github.com/helm/helm-2to3
Error: Unable to update repository: exit status 1
helm.go:81: [debug] Unable to update repository: exit status 1
```

I had to clean `$HOME/Library/Caches/helm/plugins` folder to be able to install `2to3` plugin again

**Comment by hickeyma** [comment]
@rimusz I have tried to reproduce this as follows:

```console
$ helm version
version.BuildInfo{Version:"v3.0+unreleased", GitCommit:"38e41e12c9f696667acf1ec5c560283205c99ff7", GitTreeState:"clean", GoVersion:"go1.12.7"}

$ helm plugin list
NAME	VERSION	DESCRIPTION                                                               
2to3	0.1.2  	migrate and cleanup Helm v2 configuration and releases in-place to Helm v3

$ helm plugin install helm-2to3
Error: plugin already exists

$ rm -rf ${HOME}/.config/helm/;rm -rf ${HOME}/.cache/helm/;rm -rf ${HOME}/.local/share/helm

$ helm plugin install helm-2to3
Downloading and installing helm-2to3 v0.1.2 ...
https://github.com/helm/helm-2to3/releases/download/v0.1.2/helm-2to3_0.1.2_linux_amd64.tar.gz
Installed plugin: 2to3

$ helm plugin install helm-2to3
Error: plugin already exists
```
Would you be able to provide me with more steps to try and reproduce it?

**Comment by rimusz** [comment]
I used `helm plugin remove 2to3` then I got the issue when I tried to install the same version of plugin again

**Comment by hickeyma** [comment]
Ok, tried that again as you suggested but unable to reproduce:

```console
$ helm plugin remove 2to3
Removed plugin: 2to3

$ helm plugin list
NAME	VERSION	DESCRIPTION

$ helm plugin install https://github.com/helm/helm-2to3
Downloading and installing helm-2to3 v0.1.2 ...
https://github.com/helm/helm-2to3/releases/download/v0.1.2/helm-2to3_0.1.2_linux_amd64.tar.gz
Installed plugin: 2to3

$ helm plugin list
NAME	VERSION	DESCRIPTION                                                               
2to3	0.1.2  	migrate and cleanup Helm v2 configuration and releases in-place to Helm v3
```

**Comment by rimusz** [comment]
I was removing it a few times in the last few days, till got this issue today

**Comment by hickeyma** [comment]
Ok, let me know if it happens again and maybe any steps so can reproduce it.

**Comment by rimusz** [comment]
try to install and uninstall a few times, and check that it is gone or not `$HOME/Library/Caches/helm/plugins` folder, in my case it was cashed there after uninstall.

**Comment by ecout** [comment]
I've only installed this plugin:
` helm plugin install https://github.com/hypnoglow/helm-s3.git
Error: Unable to update repository: exit status 1`

Searching for the error above brought me here:
As you can see I'm getting the same problem.

I've tried Helm 3.0.2 from direct download and from homebrew on High Sierra. Behavior is the same.
According to v3 these are the directory locations for local user:

`Local_Users-MacBook-Pro:~ local_user$ helm env
HELM_REPOSITORY_CONFIG="/Users/local_user/Library/Preferences/helm/repositories.yaml"
HELM_NAMESPACE="default"
HELM_KUBECONTEXT=""
HELM_BIN="helm"
HELM_DEBUG="false"
HELM_PLUGINS="/Users/local_user/Library/helm/plugins"
HELM_REGISTRY_CONFIG="/Users/local_user/Library/Preferences/helm/registry.json"
HELM_REPOSITORY_CACHE="/Users/local_user/Library/Caches/helm/repository"`

So for plugins the local_user is owner
`ls -altrh /Users/Local_User/Library/helm/
total 0
drwxr-xr-x   3 Local_User  staff    96B Nov 13 15:08 .
drwxr-xr-x   2 Local_User  staff    64B Nov 14 18:11 plugins
drwx------@ 88 Local_User  staff   2.8K Nov 15 16:41 ..`

But here's the trick, if you switch to ROOT then the install works:
https://github.com/hypnoglow/helm-s3/issues/102

`sudo helm plugin install`

Won't do it

You must `sudo su -` then run `helm plugin install`.

For comparison's sake Helm 2.16 from direct download returns:

`helm plugin install https://github.com/hypnoglow/helm-s3.git
Error: plugin home "$HELM_HOME/plugins" does not exist`

**Comment by dudicoco** [comment]
Any updates on this issue? I wasn't able to resolve it be deleting the cache folder.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
