### ISSUE TITLE
helm secret "invalid option" issue with helm3 

### ISSUE THREAD

**Issue by nomis-rzp** [helm/helm#6459]
With helm3 while running the `helm secret ...` command its giving the following error

Command: `helm secrets install -n myrelease ./mychart-f ./mychart/secrets.yaml`
Error:
```
Error: unknown flag: --client
helm install: unrecognized option `--helm'
Error: plugin "secrets" exited with error
```
Output of `helm version`: 
```version.BuildInfo{Version:"v3.0.0-beta.3", GitCommit:"5cb923eecbe80d1ad76399aee234717c11931d9a", GitTreeState:"clean", GoVersion:"go1.12.9"}```

Could you please let me know if this is a known issue, or if I am missing anything here?

**Comment by bacongobbler** [comment]
Can you re-open this issue over at the helm-secrets plugin repository? `helm secrets` is not a part of core.

It's likely that the plugin isn't compatible with helm 3 just yet.
