### ISSUE TITLE
Thinking/Question around Release concepts and resources that sit outside releases

### ISSUE THREAD

**Issue by no1melman** [helm/helm#6460]
So I got this scenario where i have my app, PointsApp.

I create my first release, Crazy Horse. I `install` that into my cluster, and I specifically also install my `ingress` resource (which is included in that helm chart)

Now my ingress resource is picked up by my load balancer, Traefik in this case.

Simple stuff. One benefit of Traefik is Load Splitting - allows for a/b testing, blue/green deployments. I have to modify this ingress resource to enable Load Splitting.

So the scenario is, I have a new release of PointsApp - Calm Horse. I want to deploy this, and start it at 10% traffic to Calm and 90% traffic to Crazy.

To do this, I need to update one ingress resource that sits out side of the release concept somewhat, as I don't create a new one each release, I just update an existing one. What is the pattern for that? Is that something that Helm caters for, or do I need to start thinking about augmenting Helm with another release tool (like octopus deploy).

Secondly - and this maybe a candidate for another tool - does helm support slowly modifying that resource over time to go from 10% traffic to Calm to 100% traffic to Calm?

I suppose I'm asking, do I need a Helm orchestrator or does Helm have enough functionality as it currently is

**Comment by marckhouzam** [comment]
I may not be understanding your scenario but why don't you include your ingress in your release?  If you modify just the ingress yaml (or if you modify just your app) helm upgrade will only replace the yaml that has changed, leaving the rest alone.

**Comment by no1melman** [comment]
I kinda wanted the two releases to be going through the same ingress so I can use the split traffic ability from traefik.

**Comment by marckhouzam** [comment]
You could create a tiny chart just to deploy the ingress as a third release.

**Comment by no1melman** [comment]
okay cool
