### ISSUE TITLE
helm3: --debug output sent to STDERR - results in pipeline engine marking stage as failed

### ISSUE THREAD

**Issue by hhellbusch** [helm/helm#6461]
When utilizing the ```--debug``` flag with helm3, the output is sent to STDERR.  This will result in most (if not all) pipeline engines deciding "something went wrong!" and marking the stage as failed causing the pipeline to abort.  In actuality, nothing went wrong.

To confirm that debug content is sent to STDERR:

```
$ helm3beta3 upgrade --namespace ns-dev --install --recreate-pods --force --values deployment/helm/values/dev-current.yml --wait --atomic project-ns-dev deployment/helm/chart --debug 2> stderr.txt
NAME: project-ns-dev
LAST DEPLOYED: 2019-09-19 14:42:13.887290836 -0400 EDT m=+5.527301829
NAMESPACE: ns-dev
STATUS: deployed
Release "project-ns-dev" has been upgraded. Happy Helming!
NAME: project-ns-dev
LAST DEPLOYED: 2019-09-19 14:42:13.887290836 -0400 EDT
NAMESPACE: ns-dev
STATUS: deployed

$ cat stderr.txt 
history.go:52: [debug] getting history for release project-ns-dev
upgrade.go:79: [debug] preparing upgrade for project-ns-dev
upgrade.go:88: [debug] creating upgraded release for project-ns-dev
upgrade.go:94: [debug] performing update for project-ns-dev
client.go:140: [debug] checking 29 resources for changes
wait.go:50: [debug] beginning wait for 29 resources with timeout of 5m0s
upgrade.go:101: [debug] updating status for upgraded release for project-ns-dev
``` 

This causes Azure DevOps (ADO) to mark the stage as failed with the message 

```
2019-09-19T18:17:28.6285116Z ##[error]history.go:52: [debug] getting history for release project
```

![image](https://user-images.githubusercontent.com/2072460/65272553-44547200-daed-11e9-8561-63c113c274d5.png)

Have not tested this out with other pipeline engines, but if I remember correctly, they behave similarly.

Should the debug output really be sent to STDERR? 

---

Output of `helm version`:
$ helm3beta3 version
version.BuildInfo{Version:"v3.0.0-beta.3", GitCommit:"5cb923eecbe80d1ad76399aee234717c11931d9a", GitTreeState:"clean", GoVersion:"go1.12.9"}

Output of `kubectl version`:
$ oc version
oc v3.11.0+8de5c34
kubernetes v1.10.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://ocp-console.dev.company.internal:443
openshift v3.11.104
kubernetes v1.11.0+d4cacc0

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
OpenShift on VMWare

**Comment by bacongobbler** [comment]
POSIX defines the standard error stream as "for writing diagnostic output". The [GNU C standard library](https://www.gnu.org/software/libc/manual/html_node/Standard-Streams.html) defines it similarly as "used for error messages and diagnostics issued by the program". So, it's an issue with Azure DevOps reporting incorrectly; output on stderr should not be considered an error.

**Comment by hhellbusch** [comment]
I agree.  Talked with some of my peers and they pointed out the POSIX standards as well.

Cheers!

**Comment by hhellbusch** [comment]
I believe #7409 was in relation to this issue. If using v3.1.0-rc.1 or newer, should have the changes such that ADO does not mark it as failed.  I haven't personally tested this yet, but sharing my follow-up investigation on this issue :)

**Comment by hickeyma** [comment]
@hhellbusch This should have been delivered in [3.0.3](https://github.com/helm/helm/releases/tag/v3.0.3)

**Comment by devedse** [comment]
@hickeyma , what has been delivered in 3.0.3? Since my current build pipeline still fails only when I enable --debug.

I'm using Helm 3.1.0

**Comment by hickeyma** [comment]
The fix #7409 mentioned in https://github.com/helm/helm/issues/6461#issuecomment-584809517 by @hhellbusch was delivered  in [3.0.3](https://github.com/helm/helm/releases/tag/v3.0.3)

**Comment by devedse** [comment]
@hickeyma so the cause for this issue itself is not solved then right (adding --debug causes the build to fail due to writing to STDERR)?

Just that seperate issue was resolved?

**Comment by hickeyma** [comment]
This issue was closed with the description in https://github.com/helm/helm/issues/6461#issuecomment-534122634

**Comment by bacongobbler** [comment]
@devedse there is a feature flag in Azure Devops bash tasks that will prevent builds from failing when there's output present on STDERR. If you enable that feature, the issue will go away.

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/bash?view=azure-devops#yaml-snippet

From that example, you should have

```
- task: Bash@3
  inputs:
    failOnStderr: false
```

**Comment by johnnyhuy** [comment]
Hey @bacongobbler I've tried that on a similar task to skip stderr output. Does that also ignore actual errors?

**Comment by bacongobbler** [comment]
Azure devops should still fail in those cases as Helm will return with a non-zero exit code.
