### ISSUE TITLE
Want to contribute a small bash project to help helm

### ISSUE THREAD

**Issue by mjschmidt** [helm/helm#6471]
Hi helm folks, I wanted to contribute my project to helm. The goal of my project that a few different organizations have found useful pulls every chart from google cloud storage, packages those up, but also generates a list of every container image associated with every single helm/charts repo. In this way enterprises can easily package up all helm charts and deploy them within their data centers. Its been really nice for us, and easy to use. I am happy to make updates to it over time, but it is a project I wanted to give to the helm project so that even more people can use it.

Let me know if this is something that could actually happen, what would have to be involved etc.

Thank you in advance for your consideration!

**Comment by hickeyma** [comment]
@mattfarina What is the process for @mjschmidt to submit a request about contributing his project to the Helm org?

**Comment by bacongobbler** [comment]
If a project wishes to be donated to the helm org, the author can send an email to the org maintainers explaining the project, where it can be found, who uses it etc. Projects need a simple majority vote from the org maintainers before it can be moved over ([source](https://github.com/helm/community/blob/master/governance/governance.md#decision-making-at-the-helm-org-level)).

@mjschmidt feel free to send an email over to cncf-helm-maintainers@lists.cncf.io to kick off the process. Thanks!

**Comment by bacongobbler** [comment]
closing as answered but please feel free to re-open if you have further questions/comments. Thanks!

**Comment by hickeyma** [comment]
Thanks @bacongobbler for answering. I wan't fully sure of process and didn't want to give incorrect info.
