### ISSUE TITLE
Support auto-complete when both Helm v2 and Helm v3 are present

### ISSUE THREAD

**Issue by marckhouzam** [helm/helm#6474]
One of the requirements for Helm v3 as per #5892 is that "Helm 2 and Helm 3 can work concurrently in the same cluster".  This kind of implies that it should be possible for a user to run both the Helm 2 client and the Helm 3 client from the same user's machine.

This issue tracks the effort of making auto-complete work properly for both Helm 2 and Helm 3 at the same time.

An important detail to note is that the auto-completion script is different for helm 2 than for helm 3.  For example, helm 3 completion will suggest the `--namespace` global flag, which does not exist for helm 2.  There are many more differences that require the right version of the script to be used for the corresponding helm version.

Problems:
1. Dynamic auto-completion (e.g., `helm status <TAB>`) blindly uses the binary name `helm`.  With both Helm 2 and Helm 3 installed, this will cause a conflict where auto-completing for helm 2 may call helm 3 or vice versa. 

1. Completion functions generated by Cobra are named `__helm_*` for both Helm 2 and Helm 3, therefore, when sourcing the two generated completion scripts, the second one will overwrite the functions of the first.  After that, auto-completion will follow the logic of the script sourced last independently of if helm 2 or helm 3 is used.  This will cause incorrect completions.

1. The shell needs to be told which completion function should be assigned to the binary named `helm`.  Since the binary of both helm 2 and helm 3 is named `helm`, here too we will have a conflict.

1. If a user renames the helm binary, the shell needs to be told that this new name corresponds to the helm completion function.  For example if the user decides to rename the helm v3 binary to `helm3`, then the following command must be run: `complete -o default -F __start_helm helm3`. A binary rename is likely to be done when users run both helm2 and helm3. 

1. Some documentation to explain how to make auto-completion work when both helm versions are used, if it's not completely transparent.

I believe that if the above problems are addressed, auto-completion can work for both helm 2 and helm 3 at the same time. 

After discussion with the maintainers, it was decided that changes required in v2 to make this work properly would be considered bugs and allowed to go into v2.   

Resolutions:
- [x] Dynamic auto-completion: fix for v3 done in #6472 and for v2 in #6518.

- [x] Function naming collision: To avoid modifying the helm code base, this aspect is addressed by a plugin (https://github.com/marckhouzam/helm-completion2and3).

- [x] Binary name collision between helm2 and helm3: This aspect is addressed by a plugin (https://github.com/marckhouzam/helm-completion2and3)

- [x] Renaming of helm binary: fixed for v3 by #6502. Since the v2 to v3 migration documentation talks about renaming the v3 binary, this fix will not be done for v2.

**Comment by marckhouzam** [comment]
@bacongobbler Can we mark this as partially aimed at the v2 2.15 release?  As discussed, some changes to v2 are required to allow auto-completion to properly work with v2 and v3 at the same time.

**Comment by bacongobbler** [comment]
> One of the requirements for Helm v3 as per #5892 is that "Helm 2 and Helm 3 can work concurrently in the same cluster".

I don't fully believe this is a requirement. The goal of the `helm 2to3` migration project is to transition users over from Helm 2 to Helm 3. Once data has been migrated over, users can solely rely on Helm 3 going forward.

I believe that the only group of users who would benefit from an autocompletion script that works with *both* Helm 2 and Helm 3 would be very limited... Likely just to core maintainers who are testing both versions.

For those users, can't they just run `source $(helm completion bash)` (or, if they have it in their .bashrc, restart/open a new terminal) whenever they switch between Helm 2 and Helm 3? Seems like a lot of work involved to serve what appears to be a very small subset of users.

**Comment by hickeyma** [comment]
@bacongobbler There are 2 migration scenarios or use cases:
1. Migrate over in place Helm 2 to 3 (use the plugin) 
2. Helm 2 and Helm 3 run concurrently with a phased approach of draining off Helm v2 releases when applicable. All new releases are deployed using Helm v3.

We would hope the majority of people would chose to migrate over asap using the plugin. There will however be some people who might not to use the migration tool provided and want to handle it themselves. We should provide this flexibility.

**Comment by bacongobbler** [comment]
Right, but in both of those cases, they are either switching wholesale to Helm 3, or they are in a transition period for a short period of time, in which case the efforts proposed in this PR would be thrown away when users have completed the transition. It's a non-goal for users to run both Helm 2 and Helm 3 in perpetuity since Helm 2 support will eventually end at some point (which is yet-to-be-determined in #6144).

The reason why I ask the question...

> For those users, can't they just run `source $(helm completion bash)` (or, if they have it in their .bashrc, restart/open a new terminal) whenever they switch between Helm 2 and Helm 3?

...Is because that feels like the easier approach that will not incur any performance penalties that @marckhouzam mentioned in the call. Is that the right approach here, or is there an impression that this will be too difficult for users to set up?

**Comment by hickeyma** [comment]
There are many ways around this without the need for auto-complete for Helm v2 and Helm v3 concurrently.

**Comment by hickeyma** [comment]
Auto-complete  was not on the list of requirements for migration.

**Comment by marckhouzam** [comment]
I agree this could be considered a big effort for a small gain, and I hesitated before trying to try to address it.  But it turns out some aspects of these changes remain valuable even after v2 is gone (specifically points 1 and 4 from the description of the issue).  And the changes themselves have a small foot-print code-wise.

In my case, we haven't yet thought about if we would do a migration to helm v3 of all our clusters at once, or if we would gradually migrate one cluster at a time leading up to production.  If it is gradual, then we would need to be able to run helm2 and helm3 at the same time for a couple of weeks probably.

On the technical side:
> For those users, can't they just run `source $(helm completion bash)` (or, if they have it in their .bashrc, restart/open a new terminal) whenever they switch between Helm 2 and Helm 3?

If they set $PATH to the right version of helm an re-source the completion script each time, then everything will be fine for completion.  However, I didn't feel that was likely to happen.  What I think is more likely to happen, is that users will either rename one of the helm binaries (e.g., helm v3 to helm3) or they will alias one or both binaries.  Under that assumption, `source $(helm completion bash)` and/or `source $(helm3 completion bash)` requires point 1 and 4 to be fixed (which is almost done).  Point 2 and 3 don't apply in this case.

So we could stop after point 1 and 4 are taken care of.  Although I feel fixing point 2 is easy and without negative consequences.  Point 3 is the problem due to the performance impact.  This change could be replaced with some doc aimed at users that wants to have v2 and v3 together with completion working.

**Comment by marckhouzam** [comment]
> Auto-completion was not on the list of requirements for migration.

That is very true and this was entirely my own initiative, misdirected as it may have been.

**Comment by marckhouzam** [comment]
To complete this issue, I have written a plugin that generates a shell-completion script that will work with both Helm2 and Helm v3 together.

https://github.com/marckhouzam/helm-completion2and3

For example
```
source <(helm completion2and3 bash helm helm3)
```

**Comment by marckhouzam** [comment]
Everything is now available for completion to work with Helm v2 and Helm v3 at the same time.
