### ISSUE TITLE
Issue matching version stated in requirement.yaml

### ISSUE THREAD

**Issue by pamiel** [helm/helm#6481]
**Output of `helm version`:**
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}

**Output of `kubectl version`:**
Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-eks-fa4c70", GitCommit:"fa4c703fa1706fac99d00d7f1f2080e9d4cc7eed", GitTreeState:"clean", BuildDate:"2019-07-23T03:14:24Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.10-eks-5ac0f1", GitCommit:"5ac0f1d9ab2c254ea2b0ce3534fd72932094c6e1", GitTreeState:"clean", BuildDate:"2019-08-20T22:39:46Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

**Cloud Provider/Platform (AKS, GKE, Minikube etc.):** 
AWS EKS

**Description:**
It looks there is an issue in the matching of the version stated in the `requirements.yaml` file when one of the sub-chart cumulated the following situation:
- The chart is aliased in the `requirement.yaml`
- This chart has a condition
- And the `version` definition is in the form “x.0.0-y” (i.e. a pre-release of a x.0.0 version)

If so, the chart version matching fails.

Let’s have an example to understand it better:
- 2 charts: `a` and `b`. To ease analysis, each of them are “just” creating a fake Network Policy named `a` and `b`
- Each of them have a similar `Chart.yaml` content, with a version 7.0.0-100
```
apiVersion: v1
appVersion: 1.0
description: Service A
engine: gotpl
keywords:
maintainers:
name: a
sources:
version: 7.0.0-100
```

and:

```
apiVersion: v1
appVersion: 1.0
description: Service B
engine: gotpl
keywords:
maintainers:
name: b
sources:
version: 7.0.0-100
```
- `requirements.yaml` file sets conditions and a version matching pattern `7.x.x-x` for each of them. Moreover, `b` is aliased to `c`:
```
dependencies:
- name: a
  repository:
  version: 7.x.x-x
  condition: a.enabled
```
```
- name: b
  alias: c
  repository:
  version: 7.x.x-x
  condition: c.enabled
```

Based on that, running ` helm upgrade --install bug main-chart/ --set a.enabled=true --set c.enabled=false` is supposed to install only `a` because the condition on `c` is not met. However, both `a` and `b` are deployed!
```
Release "bug" has been upgraded.
LAST DEPLOYED: Tue Sep 24 07:42:01 2019
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/NetworkPolicy
NAME  AGE
a     12m
b     14m
```

The following changes produces the following effects:
- If setting `a.enabled` to false and `c.enabled` to true, then only `c` is deployed (correct behavior!): it looks the issue might be linked to the presence of an alias on a chart
- If removing the `c` alias and using the raw `b` name (and back with `--set a.enabled=true --set c.enabled=false`), then only `b` is deployed (correct behavior!): so yes, the issue happens with aliasing! 
- Trying now to play with the `version` of `c` (with the alias situation): setting the version in the `Chart.yaml` to `7.0.1-100` instead of `7.0.0-100`, then only `c` is deployed (correct behavior!): the issue then happens when the version is `x.0.0` but not when it is `x.0.1` or even `x.1.0`. This looks also linked to such version ending with `.0.0`
- And what about the pre-release part? If removing the pre-release from both `requirement.yaml` (so `7.x.x`) and from `Chart.yaml` (so `7.0.0`), then only `c` is deployed (correct behavior!): yes, the issue is also linked to the presence of a pre-release !

So the issue happens in this very specific situation mentioned at the beginning of this post… but this is a very common situation for me :( !

Thanks for your help!

**Comment by mattfarina** [comment]
> 7.x.x-x

Are you using `-x` on the end? `x` is not a wildcard for the prerelease component (the part after the `-`). It is literally using the `x` character and per the semver spec it's using ascii ordering (see http://www.asciitable.com/).

Instead of the `-x` on the end you might try a `-0`. The `-0` trick is used by varying tools across languages. For example, sermver in js used for npm is where I learned it.

If you aren't using the `-x` on the end please let us know.

**Comment by pamiel** [comment]
@mattfarina yes, that was it, thanks a lot!
I was using a final `-x`, and replacing it by `-0` is solving the issue.

My reference for the format of the `version` fields was https://github.com/Masterminds/semver. No real explicit mention of this specific issue, but I now found the 2 following sentences related to `-0`:
>When constraint checking is used for checks or validation it will follow a different set of rules that are common for ranges with tools like npm/js and Rust/Cargo. This includes considering prereleases to be invalid if the ranges does not include one. If you want to have it include pre-releases a simple solution is to include -0 in your range.

> SemVer comparisons using constraints without a prerelease comparator will skip prerelease versions. For example, >=1.2.3 will skip prereleases when looking at a list of releases while >=1.2.3-0 will evaluate and find prereleases.

Thanks again.
