### ISSUE TITLE
map[interface{}]interface{} instead of map[string]interface{} when using fromYaml

### ISSUE THREAD

**Issue by chrisjohnson** [helm/helm#6487]
I've made a reduce go test case showing the issue. I copied helm's approach to injecting `fromYaml`/`toYaml` and sprig. When using `fromYaml`, I get `map[interface{}]interface{}` instead of `map[string]interface{}`. See here: https://play.golang.org/p/nTUEkIaqF0r

The same thing in yaml v3: https://play.golang.org/p/thDdLw5mPoW

fromJson doesn't suffer from this since json only allows for strings as keys. I think the fix is to bump yaml to v3 but I'm not a Go developer and especially not familiar with helm enough to know the far-reaching impacts of a version bump.

Output of `helm version`: `version.BuildInfo{Version:"v3.0.0-beta.3", GitCommit:"5cb923eecbe80d1ad76399aee234717c11931d9a", GitTreeState:"clean", GoVersion:"go1.12.9"}`

Output of `kubectl version`: `Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Docker for Mac

-----

Oh and the reason this matters is it prevents me from later being able to use `merge` on any object that was parsed from yaml. I've worked around it by using JSON as the interchange but given that the rest of hte file is written in yaml it would be nice to skip that step

**Comment by bridgetkromhout** [comment]
Hi, @chrisjohnson - thank you for explaining your use case and desired change. I'm closing this issue because we now have a recommended path forward for proposals: if you'd like to formally propose this idea, please file a [Helm Improvement Proposal](https://github.com/helm/community/blob/master/hips/hip-0001.md) to discuss it with the community. Thanks!
