### ISSUE TITLE
Add --lint and --strict options to helm template

### ISSUE THREAD

**Issue by lukeschlather** [helm/helm#6506]
It would be nice if helm template had --strict and --lint flags which ran the linter when running a template. (--strict might imply --lint --strict)

My main use case is that I'm creating a template and I would like to have fields that must be overridden by the caller of the template, and the template will fail if they aren't set. I want to fail this when compiling the template (which is very much preferable to failing when applying the manifest with kubectl.)

I'm not sure if there's another way to accomplish that that I'm missing.

**Comment by hickeyma** [comment]
If you use the `--strict` flag, does this work for you? cmd: `helm lint --strict`

**Comment by lukeschlather** [comment]
I want a single command invocation that does the equivalent of:

```
helm lint mytemplate --strict --set foo=bar --set thing=one --values overrides.yml
helm template mytemplate --set foo=bar --set thing=one --values overrides.yml
```

Simply doing `helm lint --strict` doesn't do what I want because I could fat-finger the overrides and I want to have a single invocation that checks it and compiles the template.

**Comment by karuppiah7890** [comment]
@lukeschlather Would you be willing to raise a PR for this ? 😄 You can do it for Helm v3 which is under branch `dev-v3` . Here's a small guide - https://v3.helm.sh/docs/community/developers/

**Comment by lukeschlather** [comment]
Sure, I will see what I can do.

**Comment by bacongobbler** [comment]
for posterity from the PR: https://github.com/helm/helm/pull/7660#issuecomment-593608736

> The case to be made for introducing `helm upgrade --install` made sense: users wanted to create the initial release if it didn't already exist.
> 
> The use case for `helm template --lint` provided in #6506 seems much less clear here. `helm template` does not needs to perform a `helm lint` to accomplish its task of templating the manifests. Validation occurs during the rendering process. Linting is performed while developing the chart.
> 
> #6506 just wants a way to share `--set` and `--values` flags with each command. Merging the two commands accomplishes that, but it introduces more design issues. Why stop at `helm template`? One could make the same argument for `helm upgrade` and `helm install`.
> 
> This PR just consolidates one command (`helm lint`) into the other, and it removes that clear separation of concerns each command has.
> 
> Given that assessment, I feel like we should not go forward with this PR. Perhaps a plugin would be better suited here.
> 
> Another approach might be to implement `helm config` where users can set these CLI flags ahead of time, similar to how git uses `git-config`. More info here: https://git-scm.com/docs/git-config/1.8.2
> 
> What do you think?

**Comment by lukeschlather** [comment]
@bacongobbler I think you are suggesting that strict/lint become chart attributes? That would seem like a good interface since it would let people developing charts decide whether or not unset variables is safe.

I'm not sure having a .helmcfg user profile like git is necessarily the right way to go - just putting it in the chart seems like it would meet the use cases @sco11morgan and I want. It also wouldn't require a separate command, it would just mean that during rendering it would check for strict/lint keys in the chart.

That would be ideal, as I think you're saying, because it would ensure that variables are never unset regardless of whether you're just running lint, install, upgrade, or template.

**Comment by bacongobbler** [comment]
I was suggesting a way for users to set flags in a config file, much like how you can tell `git commit` to always sign-off on a commit.

For example, in my .gitconfig, I have the following:

```
[user]
	name = Matthew Fisher
	email = matt.fisher@microsoft.com
	signingkey = *****************
[core]
	editor = vim
	whitespace = fix,trailing-space,cr-at-eol
	excludesfile = ~/.gitignore_global
[commit]
	gpgsign = true
```

Based on the configuration provided in this configuration file, certain feature flags of git are either enabled, disabled, or have certain values set (like what editor I prefer).

You could imagine something similar for Helm:

```
[lint]
    strict = true
    values = [~/.overrides.yaml]
    set = [foo=bar, thing=one]
[template]
    values = [~/.overrides.yaml]
    set = [foo=bar, thing=one]
```

That way, you can perform

```
$ helm lint
$ helm template
```

Without worrying whether those flags are set or not.

An alternative option would be to close this issue as a "wontfix", and instead you could write a plugin that merges these two commands in a bash script, like `helm lint-then-template --strict --set foo=bar,thing=one --values overrides.yaml`. That would be *incredibly* simple to write and should solve your case.

One example from Helm 2 would be `helm nuke`, which iterated through the output of `helm list` and deleted all of the releases from the cluster. https://github.com/adamreese/helm-nuke

See the [Helm plugin guide](https://helm.sh/docs/topics/plugins/) for more details on how to write your own plugin.

from my point of view, merging the functionality from `helm lint` into `helm template` would be a non-starter. I'd like to figure out a way where we can address the use cases described above without globbing all of these verbs - lint, template, etc. - into one command.

Does that help?

**Comment by bacongobbler** [comment]
FYI, `.gitconfig` can also be used per-repository if placed under `.git/config`. We could do the same for Helm, where a file like `.helm/config` could be read from. That would solve your case where you want this configuration to be stored per-chart.

**Comment by lukeschlather** [comment]
Why not add a config section in Chart.yaml?

**Comment by sco11morgan** [comment]
I see your point if you added lint support to `template` that it also leads to discussions on including lint in `upgrade` and `install`.

To me .helm/config doesn't add any value as 90% of our developers interaction with Helm is via our CI/CD pipelines.  We can generate the long series of Helm command needed.  It just makes something (failing fast on missing values) more complicated then it should be.  The commands  go from something like 
```
helm template --lint --strict --repo myrepo --version myversion --values file.yaml
```
to
```
helm pull --repo myrepo --version myversion && helm lint --lint --strict --values file.yaml && helm template --values file.yaml
```

**Comment by bacongobbler** [comment]
What about the alternative proposal?

> An alternative option would be to close this issue as a "wontfix", and instead you could write a plugin that merges these two commands in a bash script, like `helm lint-then-template --strict --set foo=bar,thing=one --values overrides.yaml`. That would be _incredibly_ simple to write and should solve your case.
> 
> One example from Helm 2 would be `helm nuke`, which iterated through the output of `helm list` and deleted all of the releases from the cluster. https://github.com/adamreese/helm-nuke
> 
> See the [Helm plugin guide](https://helm.sh/docs/topics/plugins/) for more details on how to write your own plugin.

**Comment by lukeschlather** [comment]
Again, you're making failing fast on missing values more complicated than it should be. You shouldn't have to install a plugin for "no undefined variables" to break the template.

**Comment by technosophos** [comment]
I do not see a compelling reason to build a compound command here. For the specific needs expressed in this issue, a plugin is ideal. And I don't think we should get into the business of making `--lint`  flag on all of the Helm subcommands.

Helm strives to work similarly to other tools out there. I don't see precedent for this in any other tool that I can find, either. Lint seems to always be a discrete command, not a precondition for completing an operation.

Closing as `wontfix`. if you do build a plugin, please add it to the list of available plugins.

**Comment by lukeschlather** [comment]
In the absence of this feature, how would you suggest going about making a helm template that requires an argument and breaks if you try to run helm install without providing the required argument?

**Comment by bacongobbler** [comment]
`{{ required "A valid foo is required!" .Values.foo }}`
