### ISSUE TITLE
Link to securing_installation.md exists in Helm V3 Quickstart but actual document covers tiller.

### ISSUE THREAD

**Issue by ecout** [helm/helm#6507]
Output of `helm version`:
v 3.0.0 - beta 1
Output of `kubectl version`:
N/A
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS

Documentation:
The Quick Start Guide here:
https://v3.helm.sh/docs/intro/quickstart/

has a broken link to this file: securing_installation.md 
https://v3.helm.sh/docs/quickstart/securing_installation.md

Did a lookup for open and closed issues and couldn't find anything filed for this specific link in Helm V3. Among them:
https://github.com/helm/helm/issues/5342

Update: The document linked lies here: https://github.com/helm/helm/blob/master/docs/securing_installation.md

From its content it looks like it shouldn't apply to Helmv3 as it discusses securing tiller a part of the architecture that was removed in v3.

Thanks!

**Comment by hickeyma** [comment]
@ecout Thanks for finding this bug. The Helm 3 documentation is now in https://github.com/helm/helm-www. Do you mind raising an issue there instead pls.?

**Comment by ecout** [comment]
> @ecout Thanks for finding this bug. The Helm 3 documentation is now in https://github.com/helm/helm-www. Do you mind raising an issue there instead pls.?

Done!
https://github.com/helm/helm-www/issues/298

**Comment by hickeyma** [comment]
Great, thanks. Closing as issue raised helm/helm-www#298
