### ISSUE TITLE
Chart install fails when Tiller installed with defaults in Kubernetes 1.16 cluster

### ISSUE THREAD

**Issue by hickeyma** [helm/helm#6517]
This error was noticed when testing the PR in https://github.com/helm/helm/pull/6462. You need the PR to be able to initialize with Kubernetes 1.16.

Tiller installed with defaults (i.e. no security/RBAC):

```console
$ helm init --upgrade
$HELM_HOME has been configured at /root/.helm.

Tiller (the Helm server-side component) has been installed into your Kubernetes Cluster.

Please note: by default, Tiller is deployed with an insecure 'allow unauthenticated users' policy.
To prevent this, run `helm init` with the --tiller-tls-verify flag.
For more information on securing your installation see: https://docs.helm.sh/using_helm/#securing-your-helm-installation

Warning: You appear to be using an unreleased version of Helm. Please either use the
--canary-image flag, or specify your desired tiller version with --tiller-image.

Ex:
$ helm init --tiller-image gcr.io/kubernetes-helm/tiller:v2.8.2
```

There is however an error when trying to install a scaffold chart (helm create chrt-tst2):

```console
$ helm install --name chrt-tst2 chrt-tst2/
Error: release chrt-tst2 failed: namespaces "default" is forbidden: User "system:serviceaccount:kube-system:default" cannot get resource "namespaces" in API group "" in the namespace "default"
```

Output of `helm version`:
```console
$ helm version
Client: &version.Version{SemVer:"v2.14+unreleased", GitCommit:"525a11682c6110cd275113e74dfe9cb7197eff6a", GitTreeState:"clean"}
Server: &version.Version{SemVer:"canary+unreleased", GitCommit:"01f775d03cb04fd84724da5b1db97c3b9c214c87", GitTreeState:"clean"}
```

Output of `kubectl version`:
```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"archive", BuildDate:"2019-09-27T14:04:34Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by listenerri** [comment]
same issue in v1.18.1

**Comment by bacongobbler** [comment]
I believe this has been fixed and can be closed, right? Is there something we still need to follow up on here?

**Comment by bridgetkromhout** [comment]
@hickeyma Can you confirm if this is fixed and can be closed, or let us know what followup is still needed? Thanks!

**Comment by hickeyma** [comment]
> Error: release chrt-tst2 failed: namespaces "default" is forbidden: User "system:serviceaccount:kube-system:default" cannot get resource "namespaces" in API group "" in the namespace "default"

Looking at this again, I don't think this is an issue caused by Helm. This is an error from the cluster. It is saying that you need to create a service account specifically for Tiller and give it the requisite cluster role. It is in the docs: https://v2.helm.sh/docs/rbac/#tiller-and-role-based-access-control

I think what happened is that I changed tool for creating my cluster at this time and then hit this error.  I must have thought it was related to the K8s 1.16 issues at the time we encountered in Helm.

Closing as not a Helm issue.

**Comment by hickeyma** [comment]
Thanks for ping me @bridgetkromhout
