### ISSUE TITLE
Provide support for accessing ConfigMap values from within yaml

### ISSUE THREAD

**Issue by adurai81** [helm/helm#6520]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:38:36Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.7-3+1a4d39a9763d23", GitCommit:"1a4d39a9763d23548d16e262d6dbe0fb2198a8ce", GitTreeState:"clean", BuildDate:"2019-03-27T01:47:38Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Oracle Cloud Infrastructure

Description :
I've a need to inject certain values , read from ConfigMap, during install of certain K8s resources.

Specifically while deploying the istio gateway we would like to pull certain values from the ConfigMap (which was pre-created) and set it dynamically in the gateway definition. 

Having a first-class support for this would be awesome.

**Comment by adurai81** [comment]
Referencing an earlier issue that was open for the same #4953 

The issue was marked closed, hence opened a new issue.

**Comment by albertocsm** [comment]
+1

**Comment by jacobreid** [comment]
+1

**Comment by bacongobbler** [comment]
In the interest of preventing spam to users subscribing to this thread, please add a :+1: to the OP instead of commenting "+1". That way we can keep the conversation relevant to the discussion at hand. I've gone ahead and deleted those comments. Thanks! :heart:

**Comment by jgreat** [comment]
This would be a really powerful feature.  The ability to set up namespace level values that could be consumed by helm and rendered in places like Ingress and various CRDs would really cut down on the repetitive values required to use Helm templates at this time.

I really liked the pattern I had with the older Rancher Cattle and their catalogs.  I was able to achieve "zero deploy config" applications by setting up cluster level metadata (the who, what and where am I) with node labels and consume them in the Rancher Catalog templates. Between that and setting up cluster secrets, and consistent naming conventions, all my apps and services could programmatically configure themselves.

If helm could consume node, namespace labels/annotations, or a configmap in the target namespace would make getting back to "zero config" applications really easy. If you could extend those values and map them in a values.yaml, even public charts could take advantage of the pre-set values.

If there are any thoughts on how y'all would like to see this implemented, I could take a shot at making a PR for this feature.

**Comment by bacongobbler** [comment]
I think that should also work for the OP. I’m going to close this as resolved. Please let us know if that doesn’t work for your use case. Thanks!
