### ISSUE TITLE
Multiple releases with the same release name in one namespace

### ISSUE THREAD

**Issue by zhming0** [helm/helm#6526]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.0-beta.3", GitCommit:"5cb923eecbe80d1ad76399aee234717c11931d9a", GitTreeState:"clean", GoVersion:"go1.12.9"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.3-gke.11", GitCommit:"cde86d2e1416a0c6c4bb964e1a13e8fa0a83a616", GitTreeState:"clean", BuildDate:"2019-08-12T20:57:47Z", GoVersion:"go1.12.5b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE

Lately I found that one of my namespace contains releases with duplicated names. All releases are referring to the same chart. Only one of them is on `deployed` status. The others have `failed` status.

<img width="885" alt="Screen Shot 2019-09-29 at 3 10 28 pm" src="https://user-images.githubusercontent.com/1054703/65826611-a8382100-e2cb-11e9-87cd-92bc234192e5.png">

I am not sure if this is a bug or intended behavior. 

So my question: should the release name be unique per namespace? Can I clear those failed releases without using release name to locate them (so I don't accidentally remove the healthy release)?

**Comment by karuppiah7890** [comment]
@zhming0 Thanks for reporting this 😄 Yes, it's a bug. Only latest revision of the release in the namespace should be shown. The bug is it was showing old revisions too. It was also reported here #6356 and was fixed by #6479 . It should be available in the next beta release that is beta-4 . This can be closed 😄
