### ISSUE TITLE
appVersion in helm ls

### ISSUE THREAD

**Issue by BhaveshSethi** [helm/helm#6529]
Duplicate of [3903](https://github.com/helm/helm/pull/3903) but for Helm3

Output of `helm version`: 
version.BuildInfo{Version:"v3.0.0-beta.3", GitCommit:"5cb923eecbe80d1ad76399aee234717c11931d9a", GitTreeState:"clean", GoVersion:"go1.12.9"}

Output of `kubectl version`: 
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.7-gke.25", GitCommit:"d4c79083ab6dea5d26ef4ed8d50b145268349bc3", GitTreeState:"clean", BuildDate:"2019-06-22T16:10:31Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE

**Comment by karuppiah7890** [comment]
@BhaveshSethi Would you be willing to port the feature over to Helm 3? 😄

**Comment by BhaveshSethi** [comment]
@karuppiah7890 Sure, I would love to.

**Comment by karuppiah7890** [comment]
@BhaveshSethi awesome, go ahead and let us know if you need any help 😄 Also checkout https://hacktoberfest.digitalocean.com/ if you haven't already. This could be your first PR for this year's Hacktoberfest 😄

**Comment by karuppiah7890** [comment]
This can be closed as PR #6541 has been merged!

**Comment by hickeyma** [comment]
Thanks @karuppiah7890 for heads up. Closing as #6541 merged.

**Comment by karuppiah7890** [comment]
@hickeyma I see that it's a bit of a cumbersome task to find and close out issues that are fixed with merged PRs. I know that GitHub can automatically close an issue if the PR mentioned `Closes #xyz` `Fixes #abc` and similar keywords. Is there some repository wide setting that disables this feature? Or probably GitHub feature is not working properly?

**Comment by hickeyma** [comment]
Not sure. GH seems to have moments.
