### ISSUE TITLE
Helm3: Support .tar.gz files too

### ISSUE THREAD

**Issue by karuppiah7890** [helm/helm#6535]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.0+unreleased", GitCommit:"3fa4465eec27e1a008189a3c22d7367a75cac136", GitTreeState:"clean", GoVersion:"go1.13.1"}
```

Helm3 already supports `.tgz` tar balls for helm charts. It only seems fair to support `.tar.gz` which is the same thing but just a different / extended extension name. I understand `helm package` gives only a `.tgz` as an output. I just felt that they both are the same thing technically, but why does it not work for `.tar.gz`:

```
$ helm create test-dummy-chart
Creating test-dummy-chart

$ helm3 package test-dummy-chart/
Successfully packaged chart and saved it to: /Users/karuppiahoss/go/src/helm.sh/helm/test-dummy-chart-0.1.0.tgz

$ helm3 lint test-dummy-chart-0.1.0.tgz
==> Linting test-dummy-chart-0.1.0.tgz
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, 0 chart(s) failed

$ mv test-dummy-chart-0.1.0.tgz test-dummy-chart-0.1.0.tar.gz

$ helm3 lint test-dummy-chart-0.1.0.tar.gz
==> Linting test-dummy-chart-0.1.0.tar.gz
Error no chart found for linting (missing Chart.yaml)

Error: 1 chart(s) linted, 1 chart(s) failed
```

Just felt it could work for `.tar.gz` too. But if this doesn't seem valid, we can close it 👍

**Comment by karuppiah7890** [comment]
Same thing for Helm v2 too

**Comment by KamalashreeNagaraj** [comment]
I would like to try this for Helm v3!

**Comment by bacongobbler** [comment]
Go for it. :)

**Comment by KamalashreeNagaraj** [comment]
https://github.com/helm/helm/pull/6568
Raised this PR by mistake to the wrong branch. Is there any way to delete it?

Here is the correct one.
https://github.com/helm/helm/pull/6570

**Comment by KamalashreeNagaraj** [comment]
@bacongobbler 
Can you please help me tag my first PR as invalid?
https://github.com/helm/helm/pull/6568

Thank you.

**Comment by bacongobbler** [comment]
The PR was closed :)

**Comment by KamalashreeNagaraj** [comment]
Oh, I closed it. Reopened it. Can you mark it as invalid? Right now it's being tracked as a valid PR on Hacktoberfest.

**Comment by KamalashreeNagaraj** [comment]
I raised a new PR for the same
https://github.com/helm/helm/pull/6829

Followed your updated contribution guidelines. Let me know if something needs to be changed.

**Comment by dspiridon2000** [comment]
Hi,

What happened with support for tar.gz files?

Thanks,
Dana
