### ISSUE TITLE
`helm get values` missing output in v3

### ISSUE THREAD

**Issue by thomastaylor312** [helm/helm#6546]
v3 is currently missing the `--output` flag and code for `helm get values`. This functionality needs to be re-enabled

**Comment by thomastaylor312** [comment]
cc @endzyme

**Comment by karuppiah7890** [comment]
@thomastaylor312 I'm able to run `helm get values release-name` and get the values in `dev-v3` branch latest version. Do you mean only the code for `output` flag is missing?

**Comment by endzyme** [comment]
Yep - what's missing is the availability to output values as json.

**Comment by Dean-Coakley** [comment]
@endzyme Are you working on this or can I give it a try?

**Comment by thomastaylor312** [comment]
Just as an FYI for whoever does work on this, #6550 moves a few of the output things around. Shouldn't impact it too much, just a few line difference

**Comment by endzyme** [comment]
Unfortunately I've not been able to make the time. Feel free! Would love to help review too if you think of it

**Comment by Dean-Coakley** [comment]
Cool, I'll take a shot at this tomorrow or the day after and open a PR if I'm happy.

I'll be sure to request reviews then. That'd be a great help!

**Comment by thomastaylor312** [comment]
Feel free to ping me in the PR @Dean-Coakley! Also, I just merged #6550, so you should be good to go with that

**Comment by bacongobbler** [comment]
fixed in #6625
