### ISSUE TITLE
Helm 3: Docs Home page design

### ISSUE THREAD

**Issue by karuppiah7890** [helm/helm#6553]
I noticed the home page of v3 docs could get more spacing in terms of design. It's all too compact now

<img width="1440" alt="Screen Shot 2019-10-02 at 10 32 33 AM" src="https://user-images.githubusercontent.com/12808424/66019358-a5724180-e500-11e9-95fa-834896488a47.png">

I think the text on the top should not be so close to the water. Felt it could be better. Probably some CSS issue, not sure what

**Comment by hickeyma** [comment]
@karuppiah7890 Helm v3 docs are now in https://github.com/helm/helm-www. Can you raise an issue in that repo instead? Thanks.

**Comment by karuppiah7890** [comment]
Oops. Sorry. Shall I also add this to the Issue template of this repo saying doc issues need to be raised in a different repo?

**Comment by hickeyma** [comment]
Seems like a good idea @karuppiah7890
