### ISSUE TITLE
Proposal: helm plugin ls subcommand

### ISSUE THREAD

**Issue by karuppiah7890** [helm/helm#6558]
Similar to how we have a `ls` alias for `list` subcommand -> `helm ls` = `helm list`, what do you people think about doing the same for plugin list, like -> `helm plugin ls` = `helm plugin list`

I was also thinking the same for `helm plugin remove`, like `rm`. But I wanted to see what you folks think about this one

**Comment by rimusz** [comment]
+1 for those aliases

**Comment by bacongobbler** [comment]
Sounds good to me. Always good to have consistency.

**Comment by karuppiah7890** [comment]
I think we can put a `good first issue` label and `hacktoberfest` label too. And to other similar small issues too!

**Comment by stevenfranks** [comment]
Could I take a look at this issue?

**Comment by bacongobbler** [comment]
Sure! Just one quick note: since this is a feature this would be a Helm 3 feature. WHen writing the PR just make sure to target the `dev-v3` branch, not master :)

There's some starting documentation here to help you get started: https://v3.helm.sh/docs/community/developers/

**Comment by stevenfranks** [comment]
Thank you! I'll check it out now

**Comment by danielthrasher** [comment]
I am new to contributing to opensource projects but just curious.  If I wanted to try this out as well,  would that be an issue?  Just don't want to step on anyone's toes as another user is already looking at it.

**Comment by bacongobbler** [comment]
I'd try taking a look at something else already listed as a good first issue in the queue that someone else hasn't already claimed. That way nobody's stepping on anyone's toes. :)

https://github.com/helm/helm/labels/good%20first%20issue

**Comment by danielthrasher** [comment]
Perfect!  Thanks so much!  I can do that.

**Comment by Efrat19** [comment]
pr submitted and passes all tests! https://github.com/helm/helm/pull/6588
can somebody please go through it and help it get merged before October ends 😆

**Comment by bacongobbler** [comment]
Closed via #6588
