### ISSUE TITLE
Regarding release name after upgrade

### ISSUE THREAD

**Issue by vasusharma1** [helm/helm#6560]
After upgrading chart:
1. Can i change release name ?
2. Can i change chart name or it's version?

Am i missing something or they cannot be changed

**Comment by bacongobbler** [comment]
1. No. You cannot change the release name, as it affects how the templates are rendered.
2. Yes. You can provide a different chart name or version on a `helm upgrade`.

Hope this helps!

**Comment by vasusharma1** [comment]
Thanks for this info, form where can i provide different chart name is it from helm upgrade command itself or manually from Chart.yaml

**Comment by bacongobbler** [comment]
> is it from helm upgrade command itself or manually from Chart.yaml

Chart.yaml

> Also, can i change release name during upgrade?

No. Same reason as before: it affects how the templates are rendered which can cause destructive behaviour.

**Comment by bacongobbler** [comment]
See more at https://helm.sh/docs/using_helm/#using-helm
