### ISSUE TITLE
helm3 upgrade --install creates a release named after the chart and does not permit --generate-name

### ISSUE THREAD

**Issue by teng1** [helm/helm#6562]
Hi, 
I was doing some testing with Helm3 (3rd beta) investigating using one command in a pipeline to deploy or upgrade rather than needing to parse the response of Helm list to decide which command is needed (upgrade or install) to proceed with a deployment.

Helm upgrade --install does work however does not enforce or allow the use of auto-generated release names. 

Thanks

**Comment by teng1** [comment]
clarified the title, this may be expected behavior? Thanks

**Comment by bridgetkromhout** [comment]
Hi, @teng1 - yes, https://helm.sh/docs/helm/helm_install/ lists `--generate-name` and https://helm.sh/docs/helm/helm_upgrade/ does not. So, this is the behavior currently expected; these docs are generated from a recent build of Helm v3. 

We have not seen much demand for this to change, but if you'd like, you could investigate the codebase and determine what would need to be adjusted. Thanks.

**Comment by teng1** [comment]
Hi will close as was quite some time ago and there are several managers now that can work out if an install or upgrade is needed
Thanks!
