### ISSUE TITLE
post-install/post-upgrade hook of sub-chart not working

### ISSUE THREAD

**Issue by marcadella** [helm/helm#6564]
`post-install` (and `post-upgrade`) hooks of sub-chart do not work when used under umbrella chart.
As an example stable/minio has a post-install (and post-upgrade) hook when `defaultBucket.enabled` is set to true. I tested it and it works find when deploying stable/minio chart directly (`helm install stable/minio --set defaultBucket.enabled=true,...`).

However if I now use Minio within an umbrella chart by adding to `requirements.yaml`:
```
- name: minio
    repository: "@stable"
    version: ">= 2.5.x"
```
and deploying my umbrella chart with `minio.defaultBucket.enabled=true` I can see that the hook job is not created whether I deploy with `helm install` or `helm upgrade --install`.

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
minikube version: v1.3.1
commit: ca60a424ce69a4d79f502650199ca2b52f29e631
```

**Comment by marcadella** [comment]
Sorry my bad. Another hook which was dependent on Minio hook was running before because they had the same weight.

**Comment by patsevanton** [comment]
@marcadella  Hello! Could you share you hook of sub-chart? Thanks a lot!
