### ISSUE TITLE
consider making apiextv1beta1.AddToScheme something that can only be called once

### ISSUE THREAD

**Issue by rudoi** [helm/helm#6566]
I'm doing some work on a Kubernetes controller that deploys Helm charts to multiple remote clusters through a CRD. Regularly, I'd have this controller reconcile the Custom Resources concurrently, but there's a race condition caused by concurrent writes to scheme.Scheme.

Taking a look at `kube.New` today: 
https://github.com/helm/helm/blob/5c592dcca685b3e5887e3c241bb2a73a43191f62/pkg/kube/client.go#L62

The call to `AddToScheme`, behind the scenes appends to a slice. This means that attempting to call AddToScheme concurrently can cause a panic. 

The good news is, because that scheme.Scheme is globally available, we only need to add the CRD types once, no matter how many Kube clients we need to create. So, I'd like to propose perhaps wrapping that AddToScheme in a `sync.Once` or something of that nature.

I understand that mine is a pretty specific use case, and I'd be happy to contribute any fixes for making Helm more controller-friendly. Thanks!

**Comment by mattfarina** [comment]
PR welcome to fix this.
