### ISSUE TITLE
Regarding canary upgrade

### ISSUE THREAD

**Issue by vasusharma1** [helm/helm#6572]
Can someone please explain me, how can i implement canary upgrade from version a to b.
It's urgent.

**Comment by bridgetkromhout** [comment]
Hi, @vasusharma1 - as this is a rather old issue, I suspect you've already moved on. If you're still looking for ways to do canary upgrades with Helm, you can look into tools like Flagger: https://docs.flagger.app/tutorials/canary-helm-gitops

Helm is a package manager, and the exact release process you choose is a bit out of scope for Helm.

I'll resolve this issue at this time. If you have further questions, please let us know in details such as version of Helm, Kubernetes version and implementation, chart used, etc. Thanks!
