### ISSUE TITLE
add new CRDs as part of upgrade

### ISSUE THREAD

**Issue by rudoi** [helm/helm#6581]
the `crds` directory is applied on install but not on upgrade because of potential weirdness with upgrading CRDs. however, this means that new CRDs are also not added as part of `helm upgrade`. there should be no conflict in doing this, I believe. 

Output of `helm version`: `version.BuildInfo{Version:"v3.0.0-beta.3", GitCommit:"5cb923eecbe80d1ad76399aee234717c11931d9a", GitTreeState:"clean", GoVersion:"go1.12.9"}`

**Comment by bacongobbler** [comment]
This was discussed in #6243:

> CRDs are not upgraded during helm install or helm upgrade. There is no accepted practice for managing CRD upgrades (again, because they are a global resources, and an upgrade can break things in interesting ways), so we decided not to handle this case. It is up to the operator.

See #5871 for more background on this discussion.

**Comment by rudoi** [comment]
@bacongobbler yeah i saw the discussion. I totally understand the reasoning for not upgrading existing CRDs.

But if I add a new CRD to a chart, why wouldn't we want `upgrade` to install it? As it sits today:
1. I have a chart with n CRDs, `helm install` installs them
2. if i modify the CRDs and update the chart, `helm upgrade` does nothing (I get this part)
3. if I add a new CRD and update the chart, `helm upgrade` still does nothing <- this is the case I'm concerned about

`helm install` already has logic for looping through the CRDs. would it be unreasonable to use that same logic in `upgrade` and only install CRDs that don't yet exist?

**Comment by bacongobbler** [comment]
fair enough. I think it's safe enough to handle the install case, just not the upgrade case. Marking as a feature enhancement

**Comment by munnerz** [comment]
What concerns are there with upgrading CRDs? A proper multi version CRD that undergoes proper management (ie no backward incompatible schema changes) should allow updates just fine.

If upgrades should be left to the operator, IMO installation should be too. This causes a big disconnect and will mean that all helm end-users installing any operator will one day land on this issue, scratching their heads.

Is there a place to gather, discuss and resolve these concerns? If upgrading CRDs is truly this unworkable, we should look at paths to make it easier upstream. But for the most part a user will just “kubectl apply” new CRDs anyway, which makes me think the “updating CRD resources is hard” train of thought may be moot 🙂

**Comment by munnerz** [comment]
Sorry, I see there’s quite a lot of discussion on the linked issues above already 🙈 I’ll try and catch up there and add my feedback!

**Comment by thanhtoan1196** [comment]
Any new updates?

**Comment by bacongobbler** [comment]
No new updates, @thanhtoan1196. But please feel free to contribute.

**Comment by fmarceau-imagia** [comment]
Bump!

**Comment by soumeng09** [comment]
Hello, has there been any progress on this?


> @bacongobbler yeah i saw the discussion. I totally understand the reasoning for not upgrading existing CRDs.
> 
> But if I add a new CRD to a chart, why wouldn't we want `upgrade` to install it? As it sits today:
> 
> 1. I have a chart with n CRDs, `helm install` installs them
> 2. if i modify the CRDs and update the chart, `helm upgrade` does nothing (I get this part)
> 3. if I add a new CRD and update the chart, `helm upgrade` still does nothing <- this is the case I'm concerned about
> 
> `helm install` already has logic for looping through the CRDs. would it be unreasonable to use that same logic in `upgrade` and only install CRDs that don't yet exist?

We're also facing a lot of grief due to helm upgrade not handling scenario #3 here.
My current solution is to iterate all subcharts, pull out their CRD defs and put then as pre-upgrade hooks in my main chart.

**Comment by stefanprodan** [comment]
If you would consider Flux to manager Helm release, we've implemented CRDs upgrades https://fluxcd.io/docs/components/helm/helmreleases/#crds

**Comment by mitchellhuang** [comment]
> Hello, has there been any progress on this?
> 
> > @bacongobbler yeah i saw the discussion. I totally understand the reasoning for not upgrading existing CRDs.
> > But if I add a new CRD to a chart, why wouldn't we want `upgrade` to install it? As it sits today:
> > 
> > 1. I have a chart with n CRDs, `helm install` installs them
> > 2. if i modify the CRDs and update the chart, `helm upgrade` does nothing (I get this part)
> > 3. if I add a new CRD and update the chart, `helm upgrade` still does nothing <- this is the case I'm concerned about
> > 
> > `helm install` already has logic for looping through the CRDs. would it be unreasonable to use that same logic in `upgrade` and only install CRDs that don't yet exist?
> 
> We're also facing a lot of grief due to helm upgrade not handling scenario #3 here. My current solution is to iterate all subcharts, pull out their CRD defs and put them as pre-upgrade hooks in my main chart.

@bacongobbler thanks for linking me to this. Do you know the current status of supporting situation 3? Would upstream accept a PR for this feature enhancement? We have been running into issues with this as well.
