### ISSUE TITLE
Support Translations / internationalization / i18n

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#6592]
This is proposed as a feature addition to v3 after 3.0.0 is released (e.g., in 3.1 or higher).

The idea is to provide for translations/internationalization of the text output by Helm.

My initial idea is to:

* Bundle the translations in the Helm binary. We can use go-bindata to generate it. This simplifies shipping the translations which are relatively small.
* Use gettext. There are many tools that support this. For a package I would suggest using something like https://github.com/leonelquinteros/gotext that does no depend on cgo.
* Add some helper functions to make translations simple.

This is the way kubectl does it (though they depend on cgo and gettext).

**Comment by bacongobbler** [comment]
Might be worth cross-collaborating with helm-www on this as well. I can imagine translations/internationalization of the documentation would be helpful.

Relevant: https://github.com/helm/helm-www/pull/274
