### ISSUE TITLE
Helm v3 generates invalid release name 

### ISSUE THREAD

**Issue by sadysnaat** [helm/helm#6600]
Output of `helm version`:
version.BuildInfo{Version:"v3.0.0-beta.3", GitCommit:"5cb923eecbe80d1ad76399aee234717c11931d9a", GitTreeState:"clean", GoVersion:"go1.12.9"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Docker Desktop 

Running `helm install mongodb-7.3.0.tgz -g`
Error: Service "mongodb-7.3.0.tgz-1570513937" is invalid: metadata.name: Invalid value: "mongodb-7.3.0.tgz-1570513937": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')

I think the issue arise from 
https://github.com/helm/helm/blob/cc450563835088945aa79dbfa0bce0bc031fb390/pkg/action/install.go#L556-L562

As the base = "mongodb-7.3.0.tgz". 

Should we add validation like Helm v2
https://github.com/helm/helm/blob/fb2cbb001986b28dec5303f5acad65390a1a8118/cmd/helm/install.go#L260-L263

**Comment by karuppiah7890** [comment]
@sadysnaat Thanks for reporting this. I see that the base is a problem. I still didn't get how adding a validation that you mentioned would solve it though. I was guessing that name should not have `.tgz` in it and instead could have been `mongodb-7.1.0` or just `mongodb`. It looks like we need to basically handle `.tgz` files while doing installation with generated names. What do you think?

Also, would you like to raise a PR for this issue? 😄

**Comment by sadysnaat** [comment]
Yes Sure I will be happy to work on the fix, here is my understanding 

When base contains `.` in the file name this will fail because the regex `[a-z]([-a-z0-9]*[a-z0-9])?` or `^[a-z]([-a-z0-9]*[a-z0-9])?$` which is used to verify DNS-1035 does not satisfy the base.

Would it be ok to replace `[^-a-z0-9]` characters with `-` so  `mongodb-7.3.0.tgz` becomes `mongodb-7-3-0-tgz` 
or should I make it like `mongodb-7.3.0.tgz` to `mongodb-7-3-0`

**Comment by bacongobbler** [comment]
the latter

> I make it like `mongodb-7.3.0.tgz` to `mongodb-7-3-0`

**Comment by bacongobbler** [comment]
Issue can be reproduced with the following test:

```
><> helm fetch stable/wordpress
><> helm install wordpress-7.5.4.tgz -g
Error: Service "wordpress-7.5.4.tgz-1572464688" is invalid: metadata.name: Invalid value: "wordpress-7.5.4.tgz-1572464688": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')
```

For the time being, this can be worked around by unpacking the archive before installing the chart.

```
><> helm fetch stable/wordpress --untar
><> helm install ./wordpress -g
NAME: wordpress-1572464706
LAST DEPLOYED: Wed Oct 30 12:45:07 2019
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
1. Get the WordPress URL:

  NOTE: It may take a few minutes for the LoadBalancer IP to be available.
        Watch the status with: 'kubectl get svc --namespace default -w wordpress-1572464706'
  export SERVICE_IP=$(kubectl get svc --namespace default wordpress-1572464706 --template "{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}")
  echo "WordPress URL: http://$SERVICE_IP/"
  echo "WordPress Admin URL: http://$SERVICE_IP/admin"

2. Login with the following credentials to see your blog

  echo Username: user
  echo Password: $(kubectl get secret --namespace default wordpress-1572464706 -o jsonpath="{.data.wordpress-password}" | base64 --decode)
```
