### ISSUE TITLE
Drop golang dependency on k8s.io/kubernetes

### ISSUE THREAD

**Issue by howardjohn** [helm/helm#6606]
Helm currently imports k8s.io/kubernetes in a few places. At time of writing:
```
pkg/kube/wait.go
32:     deploymentutil "k8s.io/kubernetes/pkg/controller/deployment/util"

pkg/kube/client.go
58:     "k8s.io/kubernetes/pkg/api/legacyscheme"
59:     "k8s.io/kubernetes/pkg/apis/core"
60:     "k8s.io/kubernetes/pkg/kubectl/cmd/get"
61:     cmdutil "k8s.io/kubernetes/pkg/kubectl/cmd/util"
62:     "k8s.io/kubernetes/pkg/kubectl/validation"

pkg/kube/client_test.go
37:     cmdtesting "k8s.io/kubernetes/pkg/kubectl/cmd/testing"
38:     kubectlscheme "k8s.io/kubernetes/pkg/kubectl/scheme
```

Kubernetes intentionally ships a broken `go.mod` file to discourage people from depending on k8s.io/kubernetes (see https://github.com/kubernetes/kubernetes/issues/79384). As a result, in order to depend on helm, we must go through major hacks to get go modules working.

Is it feasible to drop this dependency?

https://github.com/kubernetes/kubernetes/issues/79384#issuecomment-538740756 indicates it may be possible to move the controller library out of k8s.io/kubernetes, and I think the `api` and `kubectl` ones can already use `k8s.io/api` and `k8s.io/kubectl`

**Comment by bacongobbler** [comment]
Looking at those three files in the `dev-v3` branch, Helm 3 only has one reference to `k8s.io/kubernetes` at this time, and it's in wait.go:

https://github.com/helm/helm/blob/c00890cae1cf756ba0bc6eac82385c6cffeb5001/pkg/kube/wait.go#L39

I'd suggest starting there, as it looks much more feasible to drop the last dependency on k8s.io/kubernetes for Helm 3 than it is for Helm 2.

**Comment by scbizu** [comment]
Hi there , I will have my dependency on helm with `helm.sh/helm/v3/pkg/chart` , but when I go get this package, it says 
```
go get: helm.sh/helm/v3@v3.0.0-beta.5 requires
        k8s.io/api@v0.0.0: reading k8s.io/api/go.mod at revision v0.0.0: unknown revision v0.0.0
```

my Go version is go1.13, I understand that I can do some go mod replacement at my `go.mod`,but are there any other solutions ?

**Comment by bacongobbler** [comment]
It might be due to the stray `k8s.io` inclusions in go.mod. It looks like those were missed in #6609. Would you mind PRing a fix to remove those? That should unblock you.

https://github.com/helm/helm/blob/509a8819b7e8dba86b7982c006fce22628aeea28/go.mod#L45-L51

**Comment by bacongobbler** [comment]
you may want to take a look here and see if something stands out: https://github.com/helm/helm/blob/509a8819b7e8dba86b7982c006fce22628aeea28/go.mod#L71-L96

**Comment by scbizu** [comment]
yep,I finally added(copied) these dependencies into my `go.mod`, and it is worked .(what a hell of k8s's package management XD), THX @bacongobbler

**Comment by salaboy** [comment]
@howardjohn did you manage to get the right dependencies for Helm 2? I am currently struggling with that.. and it looks like you manage to get it working by hacking the deps.

**Comment by karuppiah7890** [comment]
I have done it for Helm 2, including the latest v2.16.1 with Kubernetes 1.16.x . It was one crazy day 🙈😅 but I got it done. I can share the go.mod and go.sum file in a gist if you want. But it will be very specific to what modules we imported from helm v2 and from other projects. But it could serve as a good reference may be :?

**Comment by salaboy** [comment]
@karuppiah7890 thanks a lot for the answer.. but looking around everyone is saying that helm 2 is not good for use as a library because of all that pain and dependencies hell.. so I found another alternative.. which in the end is more appropriate at least for my use case (using Tekton Pipelines to trigger helm installs and helm deletes, and avoiding using the client altogether) . I hope to be able to publish a blog post about that soon.
