### ISSUE TITLE
macOS Catalina error: “helm” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by guitmz** [helm/helm#6615]
Output of `helm version`: `v2.14.3`

Information from https://github.com/hashicorp/terraform/issues/23033 suggests that Apple is requiring applications to be signed with an Apple developer key from now on.

A workaround is also mentioned in the above issue and works but it is not ideal.

**Comment by marckhouzam** [comment]
I can confirm this.  A colleague just upgraded to Catalina and helm won't start anymore.
`kubectl` does not seem to have this problem though...

**Comment by rimusz** [comment]
I'm using macOS Catalina and helm v2 and v3 CLI work for me there.
Under `System Preferences/Security & Privacy/General` in `Allow apps downloaded from:` I have set to `Anywhere`

**Comment by tdensmore** [comment]
@rimusz I do not have that option. My only options are: `App Store` and `App Store and identified developers` 

![image](https://user-images.githubusercontent.com/469399/66484512-1cfe1e80-ea75-11e9-965e-417ba179f6f1.png)

**Comment by rimusz** [comment]
@tdensmore just run `sudo spctl --master-disable`
ref: http://osxdaily.com/2016/09/27/allow-apps-from-anywhere-macos-gatekeeper/

**Comment by tdensmore** [comment]
Thanks @rimus . `sudo spctl --master-disable` works for me.

**Comment by myersg86** [comment]
[Allow apps from anywhere](http://osxdaily.com/2016/09/27/allow-apps-from-anywhere-macos-gatekeeper/) and `sudo spctl --master-disable` disable protections that can potentially leave a Mac vulnerable to malware, and should be avoided if at all possible. This is not an ideal solution.

After taking the following steps, I now seem to have an "Open anyways" option now, allowing running individual applications without disabling secure defaults.

Here's what I did, not sure if all steps are relevant:

- Switch `spctl` off and on:
```bash
sudo spctl --master-disable
sudo spctl --master-enable
```
- Set "Allow apps downloaded from: **App Store**" in Security and Privacy
- Reboot

**Comment by bacongobbler** [comment]
So from [a comment](https://github.com/hashicorp/terraform/issues/23033#issuecomment-539774507) in the terraform issue, it looks like we need a key signed from Apple themselves to have Helm binaries verified.

> Indeed the new version of MacOS is stricter about running software you've downloaded that isn't signed with an Apple developer key. Terraform distributions are signed with a HashiCorp key with signatures distributed out of band on releases.hashicorp.com, but MacOS Catalina is requiring participation in Apple's developer program specifically, and Terraform is currently not built to support that.

Will be keeping an eye on that upstream issue for recommended next steps. What an interesting turn of events.

**Comment by scotthew1** [comment]
as a less dramatic workaround to disabling all protections, you should be able to grant an exception to helm specifically. after you try to open helm and get the error prompt, you can go to System Preferences -> Security & Privacy -> General and it will give you the option to set a special exception for helm:

<img width="560" alt="Xnip2019-10-14_09-58-48" src="https://user-images.githubusercontent.com/5482907/66758163-c1180900-ee6b-11e9-9acd-30c6b7ad6b3c.png">

the next time you try to run helm, you'll get one last warning prompt that now gives you the option to open helm.

**Comment by marckhouzam** [comment]
I haven't upgraded to Catalina yet but I was told kubectl doesn't have this problem. If that is indeed the case, could someone check if kubectl is signed in any particular way?
On my Mac OS Mojave kubectl 1.15 is not signed according to
`codesign -dv --verbose=4 $(which kubectl)`

**Comment by marckhouzam** [comment]
> @marckhouzam macOS Catalina, the latest kubectl downloaded from the kubernetes official install guide (or homebrew) is not signed [...]

Thanks @guitmz. Is Catalina blocking you when you try to use the unsigned kubectl like it does for helm?

**Comment by guitmz** [comment]
For some reason it is not. But perhaps it's because first time I used it, it was the signed binary (from Docker), macOS added it to some sort of whitelist (just a wild guess, not sure how Catalina security works). Now both the official binary and the one from Docker are working fine

**Comment by marckhouzam** [comment]
My colleague was also was blocked for helm but not kubectl, although kubectl seems unsigned.  Maybe a trail to follow...

**Comment by micheas** [comment]
I worked around this by deleting helm and then downloading it with wget.

It seems that it is because the file was downloaded via chrome. I'm guessing you also have this problem if helm has been downloaded via safari or firefox.

**Comment by marckhouzam** [comment]
Wow, @micheas is right!  If I download RC3 with `wget` it works but with chrome it triggers MacOS's security (Gatekeeper).

Googling a bit led me to this info: 
"Additionally, Gatekeeper only monitors files downloaded from the Internet through an Internet browser..."

This is good news as it means installing helm using `brew` will not trigger the security prompt. I have confirmed this.

This explains why it worked for my installation of `kubectl`.

**Comment by sozercan** [comment]
You can run `xattr -d com.apple.quarantine /path/to/file` to whitelist the binary.

**Comment by skrhlm** [comment]
If you try running helm once, then go to `settings > security & privacy`, click the "click the lock to make changes`, authorize, then you will see the text and button where you can click to allow Helm to be run.

**Comment by MinghongGao** [comment]
Enable install from "anywhere" not work for me. But @sozercan 's method did if you want to remotely run some binary via ssh. You save my night.!!

**Comment by vhosakot** [comment]
@scotthew1's reply in https://github.com/helm/helm/issues/6615#issuecomment-541706907 worked for me with macOS Catalina and helm `v3.2.4`.

**Comment by aturetta** [comment]
Found the solution

Do not download the archive with a GUI browser, it will get tainted by macos that will pretend downloaded binaries to be signed.

Just download with wget or curl, and live happy!

Downloaded archives/binaries get some additional attributes on the file system, look at a `ls -l` of your Downloads folder
```
-rw-r--r--@  1 angelo  staff     4089627 26 Aug 12:00 PSTools.zip
```
You see the `@` sign right after the permissions?
that is the extended attribute, and files downloaded by curl will not have it
