### ISSUE TITLE
v3: --kube-context, --kubeconfig and --namespace values are not passed to plugins

### ISSUE THREAD

**Issue by mumoshu** [helm/helm#6631]
## Problem

While upgrading [helm-diff](https://github.com/databus23/helm-diff/pull/151#issuecomment-537679821) to work with helm v3, we noticed that a few settings that formerly passed via the local proxy to Tiller now need to be passed explicitly to plugins:

- --kubeconfig
- --kube-context
- --namespace

// Additional discussion in helm/helm: https://github.com/helm/helm/pull/6508#discussion_r330893957

This is due to that some plugin like helm-diff does need to access release objects normally managed by helm.

More concretely, as of today when a plugin like helm-diff is invoked via `helmv3 --kubeconfig mykubeconfig --kube-context mycontext --namespace myns diff upgrade myrelease mychart`, the plugin needs all the three settings in order to read the release object for `myrelease`, but there's no way to access those from within the plugin.

## Proposed solution

I believe these 3 settings should somehow be propagated to plugins. I'd suggest using envvars as it seems like the primary way to pass contextual settings to plugins today: https://github.com/helm/helm/blob/9bc7934f350233fa72a11d2d29065aa78ab62792/pkg/plugin/plugin.go#L218-L225

---
Output of `helm version`: helm 3.0.0-beta.1~4
Cloud Provider/Platform (AKS, GKE, Minikube etc.): Any

**Comment by mumoshu** [comment]
@bacongobbler Hey! Thanks for confirming this.

Can we consider this as a fix and link the PR for this(#6632) to any of the prereleases of v3.0.0, hopefully, 3.0.0-beta.5?

From a plugin maintainer's perspective, I'm considering this a kind of regression due to the removal of Tiller.

**Comment by bacongobbler** [comment]
Agreed. Now with tiller removed this is the core piece that plugins need to connect to the Kubernetes API. In a way, it's a usability regression. I'll add this into the beta.5 for review.

**Comment by bacongobbler** [comment]
closed via #6632
