### ISSUE TITLE
Concurrent map writes causes a panic once app starts.

### ISSUE THREAD

**Issue by tigrato** [helm/helm#6643]
When tiller starts and tries to synchronize status running in the cluster and the expected status from coming from flux, tiller panics due to concurrent map writing.

This is is the stack trace

```fatal error: concurrent map writes

goroutine 319 [running]:
runtime.throw(0x18f2f0d, 0x15)
	/usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc000e11e00 sp=0xc000e11dd0 pc=0x42f302
runtime.mapassign_faststr(0x16a3d40, 0xc0007b4270, 0xc000fd35d4, 0xc, 0x2a182a0)
	/usr/local/go/src/runtime/map_faststr.go:211 +0x417 fp=0xc000e11e68 sp=0xc000e11e00 pc=0x413427
k8s.io/helm/pkg/kube.(*Client).Get.func1(0xc000fe38f0, 0x4373f6, 0x199fb28)
	/go/src/k8s.io/helm/pkg/kube/client.go:246 +0x79e fp=0xc000e11f88 sp=0xc000e11e68 pc=0x143ba0e
k8s.io/helm/pkg/kube.batchPerform.func1(0xc0006c5c80, 0xc000ef9dd0, 0xc000eeffa0, 0xc000fe38f0)
	/go/src/k8s.io/helm/pkg/kube/client.go:643 +0x30 fp=0xc000e11fc0 sp=0xc000e11f88 pc=0x143cc00
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000e11fc8 sp=0xc000e11fc0 pc=0x45ec51
created by k8s.io/helm/pkg/kube.batchPerform
	/go/src/k8s.io/helm/pkg/kube/client.go:642 +0xb8
``` 

This problem is caused by:
https://github.com/helm/helm/blob/17027a1271345be6de4dfdc1fb3a943e8a3bb20a/pkg/kube/client.go#L220-L258

`perform` function runs the workload in go routines. Line 245 of `client.go` file tries to read and after write into a map that is shared across all goroutines and causes the panic.
https://github.com/helm/helm/blob/17027a1271345be6de4dfdc1fb3a943e8a3bb20a/pkg/kube/client.go#L615-L630

Solution: share a lock in `ResourceActorFunc

Tiller version: canary

Output of `kubectl version`: 
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T23:49:20Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-eks-5047ed", GitCommit:"5047edce664593832e9b889e447ac75ab104f527", GitTreeState:"clean", BuildDate:"2019-08-21T22:32:40Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS

**Comment by sundaram2021** [comment]
I am getting this error:

**Comment by sundaram2021** [comment]
kubectl version
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0
