### ISSUE TITLE
Helm3: list all namespaces not showing multiple releases with same name in different namespaces

### ISSUE THREAD

**Issue by karuppiah7890** [helm/helm#6658]
I created two releases with same name in two different namespaces, and then tried to list releases in all namespaces, but only one of them showed up instead of two showing up

Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.0-beta.4", GitCommit:"7ffc879f137bd3a69eea53349b01f05e3d1d2385", GitTreeState:"dirty", GoVersion:"go1.13.1"}
```

**Comment by karuppiah7890** [comment]
I'm working on this currently. Writing failing tests and trying to make it pass.

Current details:
1. I noticed that memory driver used for the tests doesn't support storing multiple namespaces. I added that feature. But it doesn't look entirely great. We might have to discuss on that
2. I added tests at for the `*List.Run` method. Even here, I'm struggling a bit. I'm able to make it work, but the code doesn't look very great due to some reasons. We can discuss this too once I raise the PR

Overall, I'll be able to make things work, but I feel it could be better. For example, currently, all the interfaces in the storage `driver` - `Creator`, `Updator` and others don't take namespace into consideration. The namespace details and implementation are left to the implementation of the interface. For secrets and configmaps, this looks great, but for memory storage, not so much. But memory storage is only used for tests, so, may be it's okay? I don't know. But if everything has to be clean and should consider namespace, I would say get rid of the namespace field in the driver's implementation struct. Have namespace param in the `Delete` and other methods which need. Some methods can infer the namespace, for example in `Create`, the namespace field present in the release struct could be used. This way, there won't be multiple references to namespace - one at driver level, another at release level. But I'm not sure how easy it is to change the current implementation of secrets and configmaps to change namespaces very dynamically. This is just a thought. If it's not clear, I'm sorry, I could show code which is better. First let me raise PR with what I have. Let's see if that looks good. Then discuss thing

**Comment by hickeyma** [comment]
@karuppiah7890 I tried to reproduce this as follows using an OOTB scaffold chart ands the latest `dev-v3` code:

```console
$ helm install chrt-test chrt-test/
NAME: chrt-test
LAST DEPLOYED: Mon Oct 14 16:15:07 2019
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=chrt-test,app.kubernetes.io/instance=chrt-test" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl port-forward $POD_NAME 8080:80

$ helm install chrt-test chrt-test/ -n test
NAME: chrt-test
LAST DEPLOYED: Mon Oct 14 16:15:16 2019
NAMESPACE: test
STATUS: deployed
REVISION: 1
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace test -l "app.kubernetes.io/name=chrt-test,app.kubernetes.io/instance=chrt-test" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl port-forward $POD_NAME 8080:80

$ helm ls --all-namespaces
NAME     	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART          	APP VERSION
chrt-test	default  	1       	2019-10-14 16:15:07.404097887 +0100 IST	deployed	chrt-test-0.1.0	1.16.0     
chrt-test	test     	1       	2019-10-14 16:15:16.904750992 +0100 IST	deployed	chrt-test-0.1.0	1.16.0     
```

It is working as expected. Would you be able to provide more details to help reproduce this?

**Comment by karuppiah7890** [comment]
Ah. That's weird. I tried the same. It does work for me too now. Will check on what happened before and will also check implementation to see the working. Somehow I overlooked something. 🙈 Will get back !

**Comment by karuppiah7890** [comment]
@hickeyma It's weird, but the issue comes up when you do an upgrade too, that is when you have more than one revision. Do `helm upgrade chrt-test chrt-test -n test` and then `helm ls --all-namespaces`

**Comment by karuppiah7890** [comment]
I have to check how it doesn't come up in the initial install when there's just one release in each. But the issue is still present. I actually wrote test cases in my PR. Will double check that too - the test cases are based on memory storage driver - I implemented namespaces in it. Please do review the PR!

**Comment by hickeyma** [comment]
@karuppiah7890 Ok, so as you mentioned in https://github.com/helm/helm/issues/6658#issuecomment-541796202, the issues appears after an upgrade as follows:

```console
$ helm upgrade chrt-test chrt-test -n test
Release "chrt-test" has been upgraded. Happy Helming!
NAME: chrt-test
LAST DEPLOYED: Mon Oct 14 22:24:35 2019
NAMESPACE: test
STATUS: deployed
REVISION: 2
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace test -l "app.kubernetes.io/name=chrt-test,app.kubernetes.io/instance=chrt-test" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl port-forward $POD_NAME 8080:80

$ helm ls --all-namespaces
NAME     	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART          	APP VERSION
chrt-test	test     	2       	2019-10-14 22:24:35.233031372 +0100 IST	deployed	chrt-test-0.1.0	1.16.0     

$ helm ls
NAME     	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART          	APP VERSION
chrt-test	default  	1       	2019-10-14 16:15:07.404097887 +0100 IST	deployed	chrt-test-0.1.0	1.16.0     
```
