### ISSUE TITLE
[HELM 3] Get Values return all default values of parent object

### ISSUE THREAD

**Issue by LucasBoisserie** [helm/helm#6659]
When we try to get values from a release deployed with one value set, we get the parent object with all this default value.

Steps to reproduce:
```
$ helm install ingress-controller -n ingress stable/nginx-ingress --set controller.replicaCount=5
```

with helm 2
```
$ helm get values
controller:
  replicaCount: 5
```
with helm 3
```
$ helm get values -n ingress ingress-controller
controller:
  addHeaders: {}
  admissionWebhooks:
    enabled: false
    failurePolicy: Fail
    patch:
      enabled: true
      image:
        pullPolicy: IfNotPresent
        repository: jettech/kube-webhook-certgen
        tag: v1.0.0
...
  replicaCount: 5
...
 ```

The issue seems to appear only when the value set has a parent object.
With this, there is no issue:
```
$ helm install ingress-controller -n ingress stable/nginx-ingress --set revisionHistoryLimit=15
```

Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.0-beta.4", GitCommit:"7ffc879f137bd3a69eea53349b01f05e3d1d2385", GitTreeState:"dirty", GoVersion:"go1.13.1"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T23:49:07Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE, Docker-for-desktop

**Comment by karuppiah7890** [comment]
@LucasBoisserie Thanks for reporting this. I'm able to reproduce the issue. And it's weird. I remember seeing this bug and fixing it. Will check on it

**Comment by karuppiah7890** [comment]
Ah. Found the bug. 🙈 I fixed in a basic manner. But there's more to it. This is related to https://github.com/helm/helm/pull/6430 . My guess is, the solution worked only for maps with values at the first level. For nested maps, a deep copy has to be done for it to work properly. Thanks for catching this bug! 😄

**Comment by LucasBoisserie** [comment]
Thanks @karuppiah7890 for your quick answer !

**Comment by karuppiah7890** [comment]
I usually ask the people raising the issue - if they are interested to raise a PR for the fix. This time I didn't do it and with an enthu finished off the PR. Sorry. Next time, would you be interested in contributing to helm? It could be your issue / feature or someone else's too. Would you be interested ? :)
