### ISSUE TITLE
Helm v3 can not template CRD

### ISSUE THREAD

**Issue by anikin-aa** [helm/helm#6665]
Hi there !

Been playing around with helmv3 and found next problem.

i've got a CRD template that locates in `templates` folder and named as `crd.yaml` with next content
```
{{ if .Values.crd.create }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: testservices.test.com
spec:
  scope: Namespaced
  group: test.com
  names:
    kind: testService
    listKind: testServiceList
    plural: testservices
    shortNames:
    - test
    - tests
    singular: testservice
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
{{ end }}
```

Output of `helm version`:
```
$ helm version
version.BuildInfo{Version:"v3.0.0-beta.4", GitCommit:"7ffc879f137bd3a69eea53349b01f05e3d1d2385", GitTreeState:"dirty", GoVersion:"go1.13.1"}
```

Output of `kubectl version`:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-01-29T15:19:24Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

`helm template . --kubeconfig /home/me/.kube/config` fails with next error:
```
Error: apiVersion "apiextensions.k8s.io/v1beta1" in crd.yaml is not available
``` 

`kubectl` says, that i can create CRD on the cluster:
```
$ kubectl --kubeconfig /home/me/.kube/config auth can-i create crd
yes
```
 
templating of non cluster wide resources are working fine

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Openshift 3.11

**Comment by anikin-aa** [comment]
https://github.com/helm/helm/pull/6243

Need to place all of crds under `crds/` folder

**Comment by hickeyma** [comment]
@anikin-aa A re-architecture of CRD support was done in v3.  The background to this is documented in: https://github.com/helm/helm/issues/5871

#6243 is an implementation of the proposal. 

There is a documentation issue open in https://github.com/helm/helm-www/issues/301.

Did you mange to get this working using the `crds` directory?

**Comment by sidharthsurana** [comment]
> helm template . --kubeconfig /home/me/.kube/config fails with next error:
>Error: apiVersion "apiextensions.k8s.io/v1beta1" in crd.yaml is not available

Regarding the above helm template error see https://github.com/helm/helm/issues/6505

**Comment by anikin-aa** [comment]
> Did you mange to get this working using the crds directory?
@hickeyma Yep, its working under `crds/` directory. thx !
But now i'm facing similar error, but for my Custom Resource:
```
Error: apiVersion "test.com/v1" in customresource.yaml is not available
```

**Comment by anikin-aa** [comment]
@sidharthsurana, thanks for pointing out. `--validate` works for me
