### ISSUE TITLE
Deployment does not rolling upgrade when config map change

### ISSUE THREAD

**Issue by plumcraft** [helm/helm#6666]
Hello,

According to helm doc : https://github.com/helm/helm/blob/master/docs/charts_tips_and_tricks.md#automatically-roll-deployments-when-configmaps-or-secrets-change

It should trigger a rolling upgrade when config map content change, but it does not seem to work

In our case, there is a common varnish chart which apply a common configuration which checksum/config annotation :
```
checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
checksum/config-app: {{ include "varnish.globalVarnishConfigmapAppSha" . }}
 ```
 
Inside the helm application chart which has varnish chart as requirement.
```
{{ define "varnish.globalVarnishConfigmapAppSha" -}}
{{ (print $.Template.BasePath "/configmap-varnish.yaml") . | sha256sum}}
{{- end -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  configmap-myapp-varnish
data:
  app.vcl: |-
      backend default {
      .host = "myapp.svc";
      .port = "8080";
      .connect_timeout = 5s;
    }
 ```

And should override the ```checksum/config-app``` annotation if content of ```app.vcl``` change but results of the command ```helm diff``` stay the same, so pods don't rolling upgrade:

version
```
Output of `helm version`: v2.14.1
Output of `kubectl version`: v1.12.10
Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS
```

Thanks for you help

**Comment by hickeyma** [comment]
@plumcraft Can you show your deployment template that references the configmap?

**Comment by emre141** [comment]
Hi,
I have the direct oppsite issue. In the rabbitmq-ha chart pull my locally and I use it my local path.Although I did not change anything under template yaml or values yaml files but following command show me secret and configmap yaml files will change in each execution

```helm install mqttservice ./rabbitmq-ha/  -f rabbitmq-ha/values.yaml -f rabbitmq-ha/values.${Environment}.yaml --namespace $aks_namespace --debug --dry-run```

The helm diff output show me following change although i did not change anything in charts repo
         annotations:
           checksum/config: 6a54697b689ad53cda91584e63057c50f3bee229558b2127381f9cb6f215a7c5
 -         checksum/secret: 85ec045d3834948bc1627858e7a534e80cb409056d08cb48ce21cee8afe85106
 +         checksum/secret: 4ec4d2c5d2eecee75c1fa83c94a46885568d3cddc46191b2d2981b6bd46717ce

   data:
 -   definitions.json: '-------- # (1525 bytes)'
 -   rabbitmq-erlang-cookie: '-------- # (32 bytes)'
 -   rabbitmq-management-password: '-------- # (24 bytes)'
 +   definitions.json: '++++++++ # (1525 bytes)'
 +   rabbitmq-erlang-cookie: '++++++++ # (32 bytes)'
 +   rabbitmq-management-password: '++++++++ # (24 bytes)'
     rabbitmq-management-username: 'REDACTED # (10 bytes)'
     rabbitmq-password: 'REDACTED # (8 bytes)'
     rabbitmq-username: 'REDACTED # (8 bytes)'
   type: Opaque

And then I want to update my chart these will have been applied and rolling update my cluster 

```HELM_NAMESPACE=$aks_namespace  helm diff upgrade mqttservice ./rabbitmq-ha -f  rabbitmq-ha/values.yaml -f rabbitmq-ha/values.${Environment}.yaml --namespace $aks_namespace```

**Comment by hatharom** [comment]
both helm --force and the checksum trick were worthless in my case. 
But what I found that configmaps will be recreated with the new changes when the version of chart is modified.
So right now what I do is increment the chart version everytime I made a change.
