### ISSUE TITLE
Helm3-beta4: long running chart install returns 'Killed' and does not install

### ISSUE THREAD

**Issue by ljckennedy** [helm/helm#6674]
Output of `helm version`:

version.BuildInfo{Version:"v3.0.0-beta.4", GitCommit:"7ffc879f137bd3a69eea53349b01f05e3d1d2385", GitTreeState:"dirty", GoVersion:"go1.13.1"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:55Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Minikube

----

My company's main chart normally takes a few minutes of minutes to deploy.  It is quite complex and contains over 25 subcharts.  It deploys fine with Tiller.  But with helm 3, it returns the string 'Killed' and no other messages.  Running time helm... returns:

**Killed

real    2m50.839s
user    1m2.156s
sys     0m41.436s**

**Comment by bacongobbler** [comment]
Hi @ljckennedy. Thanks for reporting this. As suggested on Slack, if you can provide more information on how to reproduce this particular error, that would be helpful. The `-v 10` flag may also help provide more information.

Let us know if you find anything actionable here.

**Comment by bacongobbler** [comment]
Marking as question/support for the time being until we can nail down whether this is a bug within Helm or something further up the stack.

**Comment by ljckennedy** [comment]
Output is 300k so can't post it here.  I can't see how to add an attachment either.

**Comment by ljckennedy** [comment]
As an aside, the same chart deploys in helm2 much quicker:

real    1m15.720s
user    0m9.712s
sys     0m0.748s

**Comment by thomastaylor312** [comment]
@ljckennedy Did you also try with just the `--debug` flag? That will enable more verbose logging for Helm itself, which will help us identify any Helm issues. Please leave off the `-v 10` when you do to reduce the noise

**Comment by ljckennedy** [comment]
Not much but here is the debug only output:


history.go:52: [debug] getting history for release qse-testing
Release "qse-testing" does not exist. Installing it now.
install.go:148: [debug] Original chart version: ""
install.go:165: [debug] CHART PATH: /home/vagrant/.cache/helm/repository/qliksense-1.13.106.tgz

Killed

**Comment by klauskades** [comment]
Not sure, if this is still a problem, but I had the same error. I realized in my case that the problem was not with Helm but with Kubernetes. When I tried to create a deployment with kubectl apply -f <some-file>.yaml I got the same message "Killed". Since I ran the command in a docker container, I realized that the memory of the container was the problem. Therefore, the error "killed" only appears if there is not "enough" memory available. Scaling up the memory resolved the error with Kubernetes as well as with Helm.

**Comment by tomahawk28** [comment]
Just for record, I'm seeing this issue from helm 3.2.4
```

I0329 15:47:25.609551  937766 round_trippers.go:445] GET https://172.31.0.1:443/openapi/v2?timeout=32s 200 OK in 501 milliseconds
I0329 15:47:25.609577  937766 round_trippers.go:451] Response Headers:
I0329 15:47:25.609583  937766 round_trippers.go:454]     Accept-Ranges: bytes
I0329 15:47:25.609604  937766 round_trippers.go:454]     Audit-Id: b5f8ae45-6b67-42bc-afb8-4b5657c1ccb1
I0329 15:47:25.609610  937766 round_trippers.go:454]     Cache-Control: no-cache, private
I0329 15:47:25.609627  937766 round_trippers.go:454]     Vary: Accept-Encoding
I0329 15:47:25.609631  937766 round_trippers.go:454]     Vary: Accept
I0329 15:47:25.609648  937766 round_trippers.go:454]     X-From-Cache: 1
I0329 15:47:25.609653  937766 round_trippers.go:454]     Content-Type: application/octet-stream
I0329 15:47:25.609658  937766 round_trippers.go:454]     Date: Mon, 29 Mar 2021 15:47:25 GMT
I0329 15:47:25.609663  937766 round_trippers.go:454]     Etag: "101869F0CF72D6AE77F6FC6ABCE8DBCF573AA26501A1EDF287F5A599C9506A444490751B83E93963245E5F57FE18A424D59C085E2A83927B52C5DACB37ABBF93"
I0329 15:47:25.609669  937766 round_trippers.go:454]     Last-Modified: Thu, 18 Mar 2021 10:18:24 GMT
I0329 15:47:25.609674  937766 round_trippers.go:454]     X-Varied-Accept: application/com.github.proto-openapi.spec.v2@v1.0+protobuf
Killed

bash-5.0$ helm version
version.BuildInfo{Version:"v3.5.1", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.7"}
```
