### ISSUE TITLE
helm ls stuck after installing tls on tiller

### ISSUE THREAD

**Issue by httran13** [helm/helm#6675]
During installation of TLS following these instructions here : https://github.com/helm/helm/blob/master/docs/tiller_ssl.md#generating-certificates

After 

`helm init \
--service-account tiller \
--tiller-tls \
--tiller-tls-verify \
--tiller-tls-cert tiller.cert.pem \
--tiller-tls-key tiller.key.pem \
--tls-ca-cert ca.cert.pem \
--history-max 200`

When i try to run a helm ls without --tls, helm gets stuck but when i use the --tls flag as below, I am able to get a response from tiller

Output of `helm version`:
` helm version --tls --tls-ca-cert ca.cert.pem --tls-cert helm.cert.pem --tls-key helm.key.pem 
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}`
helm version w

Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7+IKS", GitCommit:"44d102fa84ebb514e817942f5b1090cf54844445", GitTreeState:"clean", BuildDate:"2019-09-24T06:08:41Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
IKS - ibm kubernetes service

Hello, following the guide to setup tls, i am expecting some sort of response from tiller such as `Error: transport is closing` but any helm cmds are getting stuck

Outout of helm ls --debug :

`helm ls --debug
[debug] SERVER: ":44134"
`

**Comment by bridgetkromhout** [comment]
Hi, @httran13 - please try Helm v3; tiller has been removed, so you should no longer have this problem. Helm 2 will no longer be updated soon: https://helm.sh/blog/helm-v2-deprecation-timeline/ - Thanks!
