### ISSUE TITLE
Helm 3: missing install.md

### ISSUE THREAD

**Issue by timfeirg** [helm/helm#6676]
Hi, I'd like to try out Helm 3 for our company, but https://v3.helm.sh/docs/intro/quickstart/install.md is missing, what's your suggestion on this?

~~Can I just use [the installation guide for Helm 2](https://helm.sh/docs/using_helm/#installing-helm)?~~

Since Helm 3 removes tiller, I don't think I can follow the old guide.

**Comment by bacongobbler** [comment]
https://v3.helm.sh/docs/intro/quickstart/#install-helm

**Comment by bacongobbler** [comment]
Oh... I see what you're trying to fetch. There's an issue with some internal links not working.

I can take a look at this issue this week.

**Comment by bacongobbler** [comment]
For now, use https://v3.helm.sh/docs/intro/install/
