### ISSUE TITLE
Add HelmVersion to Capabilities

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#6689]
In Helm v2 the Capabilities included `TillerVersion` which would allow you to target and work with different minor versions of Helm. When Tiller went away so did the ability to detect the minor version of Helm.

The idea is to add this back as `HelmVersion` and available though Capabilities.

Note, I'm filing this but not expecting to add this until after v3.0.0 is released.

**Comment by mtougeron** [comment]
This would be great so that charts can support features for both helm2 & helm3 during a transition period.

**Comment by EricLemieux** [comment]
Anybody mind if I attempt this?

**Comment by karuppiah7890** [comment]
Go ahead ! :)

**Comment by seaneagan** [comment]
Workaround to determine major Helm version (2 vs 3): `{{- $isHelm2 := hasKey .Capabilities "TillerVersion" -}}`

**Comment by mkmik** [comment]
Perhaps instead of exposing the version helm could expose what are the supported hooks, so that the charts could depend on features rather than version numbers?

E.g. the chart could conditionally render a CRD if the `crd-install` hook is supported, otherwise the CRD present in the `crds/` directory will be used whatever version got rid of that hook (i.e. helm3)

**Comment by bacongobbler** [comment]
With #7005, charts can use `.Capabilities.HelmVersion.Version` to determine which version of Helm is rendering the chart.

For those who need their charts to remain compatible with Helm 2, The workaround @seaneagan should work as well.

**Comment by absoludity** [comment]
FWIW, I wasn't able to use the above workaround as the `.Capabilities` object is not a `map[string]interface`:
```
cat templates/deployment.yaml 
{{- $isHelm2 := hasKey .Capabilities "TillerVersion" -}}
isHelm2: {{ $isHelm2 }}

$ helm3 template .
Error: template: testhelmversion/templates/deployment.yaml:1:23: executing "testhelmversion/templates/deployment.yaml" at <.Capabilities>: wrong type for value; expected map[string]interface {}; got *chartutil.Capabilities
Use --debug flag to render out invalid YAML

$ helm2 template .
Error: render error in "testhelmversion/templates/deployment.yaml": template: testhelmversion/templates/deployment.yaml:1:23: executing "testhelmversion/templates/deployment.yaml" at <.Capabilities>: wrong type for value; expected map[string]interface {}; got *chartutil.Capabilities
```
but after playing around, I was able to do so with `{{- $isHelm2 := regexMatch "\nTillerVersion:\n" (.Capabilities | toYaml) }}` as follows:

```
$ cat templates/deployment.yaml 
{{- $isHelm2 := regexMatch "\nTillerVersion:\n" (.Capabilities | toYaml) }}
isHelm2: {{ $isHelm2 }}

$ helm3 template .
---
# Source: testhelmversion/templates/deployment.yaml
isHelm2: false

$ helm2 template .
---
# Source: testhelmversion/templates/deployment.yaml
isHelm2: true
```
