### ISSUE TITLE
Passing user parameters of the parent chart to the subchart (without using global)

### ISSUE THREAD

**Issue by jgoeres** [helm/helm#6699]
It would be really helpful if it were possible to explicitly pass values from the parent chart to values of the subchart.
My use case is like this:
I have a subchart ("let it be named "mysubchart"), which has a value "image.version".
The parent chart has the same value. Normally, users will want all image versions to be the same, those in pods created by the subchart, and those created by the parent chart.

In order to change the version consistently, the user would now have to set the values
"image.version" and "mysubchart.image.version" to the same value, which is not convenient and error prone.
What I would need is a way to explicitly pass the value that the user set for "image.version" to "mysubchart.image.version". One way this could be done is adding the ability to use simple template directives in values.yaml, e.g., in my example:

    image:
      version: 1.0.0
    mysubchart:
      image: 
        version: {{- .Values.image.version -}}

That way, by default, image.version would also be used for the templates in the subcharts, but could still be overridden by setting "mysubchart.image.version" explicitly.

This is basically the same requirement as https://github.com/helm/helm/issues/2927 which, alas, has long been closed.

**Comment by kdubb** [comment]
We've all heard and used the term DRY... yet helm charts, even in 3.x, require consumers to repeat themselves time and again.  The lack of this feature is very frustrating and is seemingly always the first issue Chart authors encounter when working with sub-charts.

How can we get some movement on this?

**Comment by bacongobbler** [comment]
Would YAML anchors work for this use case?

https://confluence.atlassian.com/bitbucket/yaml-anchors-960154027.html

**Comment by kdubb** [comment]
@bacongobbler Seemingly, _almost_...

I have a chart that includes `postgresql` and `redis` sub-charts. I want to share our  `existingSecret` property with them.  Using the following in `values.yaml`...

```yaml
existingSecret: &sharedExistingSecret a-secret

postgresql:
  existingSecret: *sharedExistingSecret
redis:
  existingSecret: *sharedExistingSecret
```

This works to share the value `a-secret` with both sub-charts but supplying a value via command line (e.g. `helm upgrade --set existingSecret=b-secret`) only changes the explicit value of `existingSecret`.

**Comment by jgoeres** [comment]
I am close to either 
- scrap using subcharts and put everything into one (I am the author of both, so that works for me, but will not work for others), although this goes against many principles of good "software" design
OR
- build a wrapper that generates the effective values.yaml (with duplicate values passed to the subchart(s)) out of my own values.yaml. Basically, it would take an effective values.yaml template as input where all parameters for the subcharts have variable references as values, which values are then substituted in a preprocessing step with those from my own values.yaml.
Users of my helmchart would have to generate the efective values.yaml as a preprocessing step before running helm as normal.

**Comment by kdubb** [comment]
@jgoeres I've thought about a similar wrapper... an uber-helm... to control helm 😬

@bacongobbler Is there any thoughts on a direction to solve this.  I'd rather spend my time contributing to Helm than hacking together a template system above helm.

**Comment by kav** [comment]
Would a minor tweak to set and values overriding to respect existing anchor definitions, the `&sharedExistingSecret` in the above, allow this work? One could override the actual value or even the references to it but `helm upgrade --set existingSecret=b-secret` would lead to existingSecret being `&sharedExistingSecret b-secret` which would leave the rest working

**Comment by jgoeres** [comment]
I think if externally set values (whether it is via --set/--set-string or via a custom values file passed with -f) would respect anchors defined in the chart's values.yaml, that would fulfill this requirement.

e.g., my modified initial example would be

    image:
      version: &version 1.0.0
    mysubchart:
      image: 
        version: *version

If now someone set image.version to e.g., 2.0.0, and the anchor would be resolved after the externally provided value "2.0.0" would be set, so that mysubchart.image.version also resolves to "2.0.0", that would be what we need here.

Ideally, it should also work for entire substructures, e.g.

    image: &image
      version: 1.0.0
      registryUrl: ""      
    mysubchart:
      image: *image

If in this situation I set image.version and/or image.registryUrl, both should also show up in mysubchart.image.version and/or mysubchart.image.registryUrl, respectively.

To be fully flexible it should also be possible to do something like this:

    --set-string image.version=2.0.0,image.registryUrl=myregistry,mysubchart.image.version=1.5.0

in which case image.version resolves to 2.0.0, mysubchart.image.version to 1.5.0, and both image.registryUrl and myhubchart.image.registryUrl resolve to "myregistry"

**Comment by sco11morgan** [comment]
@jgoeres I'm also looking for a good solution to have a common set of base templates that I can use across multiple applications.  The closest I've found is to merge the parent and subchart values in the subchart templates [like this](https://github.com/CodeJjang/helm-microservices-example/blob/master/common/templates/_deployment.yaml#L1-L6).  Then in the parent chart you can pull in templates [as needed](https://github.com/CodeJjang/helm-microservices-example/blob/master/server/server-chart/templates/deployment.yaml).  There used to be a medium article going into more detail but it disappeared.

The drawback so far is that this doesn't work with defining a values.schema.json in the subchart with a set of required fields.

**Comment by tomislater** [comment]
Hmm, but you can do that even now... by `{{ tpl value $ }}`.

For instance we use such mechanism for generating environment variables and save them in `ConfigMap` object.

`values.yaml` file:
```
...
env:
  XHR_SENTRY: https://aaa:bbb@sentry.my.domain/666
  ALLOWED_ORIGINS: "https://one.{{ .Values.global.baseDomain }},https://two.{{ .Values.global.baseDomain }},https://three.{{ .Values.global.baseDomain }}"
...
```

Then, in `ConfigMap`:
```
...
data:
  # variables from Values.env
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ tpl $value $ | quote }}
  {{- end }}
...
```

**Comment by kav** [comment]
That approach assumes you wrote or control the configmap and it isn't in a chart referenced via requirements. Doesn't really help my use case though it may help others here. Seems like being able to use requirements without drastically complicating chart end users lives is the largest issue here.

**Comment by withnale** [comment]
I proposed a fix for this way way back...  you can see the history in  #3242 

Basically adding an export_values to mirror the already present import_values functionality.

I raised a PR for this but it got lost in the move to helm3. Is it worth resurrecting this PR?

**Comment by hickeyma** [comment]
@withnale Go for it.

**Comment by elliottb303** [comment]
was already using jinja-2 to set dynamic vars in values.yaml ( for example different environments). Will just expand job to parse sub-chart values. easy enough. Probably why a fix isn't pushed. keep things simple, don't solve every possible use case that other tools can do

**Comment by ramandeep-singh-1983** [comment]
I was facing the same issue i.e. passing a value set by user using --set to subchart. This came to my rescue:
`helm install --set subchartname.image=version`

And if you want to pass same values to parent as well as subchart:
`helm install --set image=version,subchartname.version=version`

**Comment by dvpierce** [comment]
I would also _really_ like values provided via --set to be respected by the YAML anchors.

We provide certain information at deploy-time to our application charts, such as environment codes, Azure region, logging mode, and whether or not to kick off AATs. We would love to be able to use umbrella charts to describe sets of microservices or ecosystems of applications, but if dependency charts can't receive the deploy-time variables, we're blocked. (Well, unless we rewrite our deployment scripts to rewrite the entire values.yaml at deploy-time instead of using CLI arguments, but that seems slightly inelegant.)

**Comment by chulkilee** [comment]
I'm hitting this problem while wrapping existing charts for customization (e.g. disabling some features by default, etc.).

As helm 3 does not support passing variables down to subcharts programmatically out-of-box, it requires other customization/template tools on the top of helm, which adds significant complexity..

I'm wondering how feasible to teach helm3 to use templates for values (e.g. by adding a step to run helm template before using values).

**Comment by kav** [comment]
@chulkilee can you just use the standard functions for your use case, i.e. https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#overriding-values-from-a-parent-chart for passing values to subcharts? This works in all versions of helm.

**Comment by jgoeres** [comment]
@kav 
What yxou describe of course works fine as long as you want to override subchart parameters to constant values from the parent chart. But if you want parameters of the subchart to be in some way derived from parameters given by the parent chart user, then this won't work. Consider the example I made in my original issue description - assume that during helm install the user specifies, e.g., an image tag, that should be used for pods created by the parent chart and by the subchart. 
Note that the image tag example is really jus that - an example. This could be any parameter that users of the parent chart will be likely to override and that are relevant for the main chart and the subchart. Without the feature request here, they will have to specify the same parameter twice, which is not only annoying, but also highly error prone.

**Comment by kav** [comment]
Oh yes I fully agree @jgoeres there is definitely a missing feature that would drastically improve chart factoring for end users and help get rid of all these slightly modified imported charts every large application ends up with. I specifically mean for @chulkilee though I guess "variables" could mean the same problem the rest of us have...

**Comment by jglick** [comment]
Another example (simplified from a system I am working on) might be helpful in clarifying. The app Alpha has long had a chart whose `values.yaml` has something like

```yaml
MainStuff:
  HostName: null
```

used something like

```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: alpha
spec:
  rules:
  -
{{- if .Values.MainStuff.HostName }}
    host: {{ .Values.MainStuff.HostName }}
{{- end }}
    http:
      paths:
      - path: /alpha
        backend:
          serviceName: alpha
          servicePort: 8080
```

So, you would

```bash
helm install --set MainStuff.HostName=alpha.mycorp.com alpha therepo/alpha
```

Fine so far. Meanwhile, another app Beta has independently developed a chart including

```yaml
ingress:
  host: null
```

with roughly similar usage.

Now I want to combine these apps into one superchart. I am not at liberty to rename values in the original charts. Currently the user must type something like

```bash
helm install --set alpha.MainStuff.HostName=super.mycorp.com --set beta.ingress.host=super.mycorp.com super therepo/super
```

whereas I would prefer `super/values.yaml` to say something like

```yaml
hostname: null
alpha:
  MainStuff:
    HostName: {{ .Values.hostname }}
beta:
  ingress:
    host: {{ .Values.hostname }}
```

so the user could type simply

```bash
helm install --set hostname=super.mycorp.com super therepo/super
```

**Comment by chulkilee** [comment]
@kav I'm already using that to provide default values from parent charts, and then override values with values on parent chart. It works, but it has many drawbacks:

- Expose value structure of subcharts: updating them require knowledge of them, not the parent charts
- Unable to transform values

As others also pointed out... here are some use cases:

- Use different key or structure
- Hide value structure of subcharts
- Transform values and pass them
- Share values across sub charts

Is there any feature request for values templating? If we scope down the available object (e.g. only Values are available - not Release for instance), it could be simpler than fully bootstrapping all objects.

**Comment by jglick** [comment]
Should not be considered stale; this continues to be a major limitation in Helm.

**Comment by jglick** [comment]
@bacongobbler can the stalebot be suppressed?

**Comment by bacongobbler** [comment]
The ticket has been open since October 2019. When a ticket is left open for such a long time, it makes me wonder whether if anyone from the community is planning on implementing this any time soon, or if community members found workarounds over the past two years such that they do not require this functionality (as in, lack of demand because the workaround solves the problem).

We have a "keep open" label available to keep issues from stalling out. But I don't want to add it to tickets when there's little motivation to implement it.

**Comment by chulkilee** [comment]
For the plan - Can helm contributors (who have better understanding of internals) give some assessment of this? e.g. Can this be implemented without breaking changes?

For the demand - I've seen more use of CRD + operator pattern for reusable components instead of reusing helm chart - probably that's why we don't see "enough" vote here? 😄 

On marking this "stale" - If we cannot or do not implement this feature due to fundamental design issues, then it's better to close this ticket and documenting the limitation somewhere. If it's just lacks of demands/work for PR - let's do what the stalebot says :)

**Comment by SoerenHenning** [comment]
Isn't this the same as !6876, which was (unfortunately) closed?

**Comment by tewner** [comment]
For all those following this thread - Our company worked around this issue by implementing [https://github.com/roboll/helmfile]

**Comment by KKatev-reasonance** [comment]
I am trying to solve this exact same problem, I imagined one could define anchored values in a chart and (re)use them to override the values in its sub chart, but was unpleasantly surprised when setting or overriding the values didn't work. Unfortunately I haven't come up with a solution so far, are there any news regarding this issue?

**Comment by hecsalazar** [comment]
Isn't this solved by the `import-values` feature in the Chart.yaml to map subchart values into parent chart?

**Comment by jgoeres** [comment]
As you write, import-values allows to get values from the child chart to the parent. What we would need is a way to derive values for the child chart from one or multiple values passed to the parent chart, maybe transform then a bit (like concatenate what is two dedicated parameters for the parent chart and use the resulting value as ONE value for the child chart).
e.g.

    childchart.image = parentchart.registry +"/" + parentchart.image.name + ":" + parentchart.image.tag

**Comment by hecsalazar** [comment]
> As you write, import-values allows to get values from the child chart to the parent. What we would need is a way to derive values for the child chart from one or multiple values passed to the parent chart, maybe transform then a bit (like concatenate what is two dedicated parameters for the parent chart and use the resulting value as ONE value for the child chart). e.g.
> 
> ```
> childchart.image = parentchart.registry +"/" + parentchart.image.name + ":" + parentchart.image.tag
> ```

thanks for the clarification! in this case I support the proposal to support some sort of `export-values` to pass values from parent to subchart.
I have use-cases where we want to wrap subchart complexities for other development teams like the hostname example mentioned above.

**Comment by KKatev-reasonance** [comment]
Hey @jgoeres 
thanks for the clarification! I came to the same conclusion after playing around with the chart values. I guess I had a false understanding of how Helm sequences and parses values. I have no solution that can be applied to Helm generally, what I did was that I rewrote my charts and implemented a specialized parser to help me with the propagation of required parameters.

Also, what you mentioned above about value transformations would be of course pretty great and would make Helm even more useful.

**Comment by blackwood821** [comment]
I could also use this feature. I'm trying to pass a user value to two subcharts but don't see a good way to do it. I tried using a global variable but it didn't seem to get overridden by the user supplied value. For now I'll have to pass in two different user variables with the same value.

**Comment by blackwood821** [comment]
Please re-open

**Comment by tewner** [comment]
Hi!
You may want to consider using helmfile to organize variables across your hierarchy of helm charts.

**Comment by daniel-jeremia** [comment]
Please re-open, having this issue as well

**Comment by OskiKervinen-MF** [comment]
An interesting potential solution to this was recently suggested: https://github.com/helm/helm/issues/12323

**Comment by JossWhittle** [comment]
Interesting discussions here, thank you for linking @OskiKervinen-MF.

The main thing I wanted to avoid which comes up as an issue in this thread too, is to have a mechanism for doing these sub-chart value templates in a well defined order and avoiding the circular templating pains of the `values.yaml` file using itself as the values input. I think splitting the sub-chart values into their own file is a good way to achieve these goals.

I'd be very keen to get others opinion on it.

I haven't looked into the helm source code much yet, but I'd be grateful if someone could point me in the ballpark of the areas of the codebase responsible for:
- Applying templating to each yaml file and getting back the expanded content
- Passing values through to a sub-chart dependency so that it can also be expanded

**Comment by namtranp** [comment]
> I think if externally set values (whether it is via --set/--set-string or via a custom values file passed with -f) would respect anchors defined in the chart's values.yaml, that would fulfill this requirement.
> 
> e.g., my modified initial example would be
> 
> ```
> image:
>   version: &version 1.0.0
> mysubchart:
>   image: 
>     version: *version
> ```
> 
> If now someone set image.version to e.g., 2.0.0, and the anchor would be resolved after the externally provided value "2.0.0" would be set, so that mysubchart.image.version also resolves to "2.0.0", that would be what we need here.
> 
> Ideally, it should also work for entire substructures, e.g.
> 
> ```
> image: &image
>   version: 1.0.0
>   registryUrl: ""      
> mysubchart:
>   image: *image
> ```
> 
> If in this situation I set image.version and/or image.registryUrl, both should also show up in mysubchart.image.version and/or mysubchart.image.registryUrl, respectively.
> 
> To be fully flexible it should also be possible to do something like this:
> 
> ```
> --set-string image.version=2.0.0,image.registryUrl=myregistry,mysubchart.image.version=1.5.0
> ```
> 
> in which case image.version resolves to 2.0.0, mysubchart.image.version to 1.5.0, and both image.registryUrl and myhubchart.image.registryUrl resolve to "myregistry"
Hi [jgoeres](https://github.com/jgoeres) May I know after you set like above does it work?
Thanks

**Comment by chenlujjj** [comment]
This should definitely by reopened

**Comment by emmeowzing** [comment]
This needs to be reopened.
