### ISSUE TITLE
range, math, type issue not working in 2.15

### ISSUE THREAD

**Issue by dbainbri-ciena** [helm/helm#6704]
I noticed in my template a `range` stopped working. I tried to simplify to get to the key issue and found that if I had this in a template
```
{{- $CCC := 1 | int }}
{{- $CCC = add1 $CCC }}
```

i would get the error
```
Error: render error in "voltha/templates/rw-core.yaml": template: voltha/templates/rw-core.yaml:43:26: executing "voltha/templates/rw-core.yaml" at <$CCC>: wrong type for value; expected int; got int64
```

I think there is a math/type problem at the core of my range problem. my original range statement was a simple iterate 

{{ range $i, $e := until (int .Values.count) }}

Output of `helm version`:
Client: &version.Version{SemVer:"v2.15.0", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.0", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-25T23:41:27Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
KiND

**Comment by bacongobbler** [comment]
closing in favour of #6708 as it includes the error, an explanation, and a workaround. Thanks!
