### ISSUE TITLE
Inconsistency between helm search and helm install

### ISSUE THREAD

**Issue by mszostok** [helm/helm#6712]
In the Service Catalog, one of our users reported inconsistency between the `helm search` and `helm install`: https://github.com/kubernetes-sigs/service-catalog/issues/2725

**TL;DR**

`helm search` shows version 0.3.0-beta.1 (the newest one), but `helm install` installs the 0.2.1 version (the old one).

**How to reproduce**
```
helm repo add svc-cat https://svc-catalog-charts.storage.googleapis.com

helm repo add svc-cat https://svc-catalog-charts.storage.googleapis.com
"svc-cat" has been added to your repositories

helm search service-catalog
NAME                     	CHART VERSION	APP VERSION	DESCRIPTION
svc-cat/catalog          	0.3.0-beta.1 	           	service-catalog webhook server and controller-manager hel...

helm install svc-cat/catalog \
>     --name catalog --namespace catalog

helm list
NAME                	REVISION	UPDATED                 	STATUS  	CHART                         	APP VERSION	NAMESPACE           
catalog             	1       	Mon Oct  7 09:55:27 2019	DEPLOYED	**catalog-0.2.1**                 	           	catalog             
```

**Investigation**

The `helm search` strategy just grabs the 0 entry from the index file:
https://github.com/helm/helm/blob/9668ad4d90c5e95bd520e58e7387607be6b63bb6/cmd/helm/search/search.go#L71-L73

but the `helm install` uses the `"github.com/Masterminds/semver"` lib to check which version should be installed:
https://github.com/helm/helm/blob/9668ad4d90c5e95bd520e58e7387607be6b63bb6/pkg/repo/index.go#L180-L188

the constraint is defined as `semver.NewConstraint("*")` so it will skip prereleases when looking at the list of releases while `>=0.0.0-0` will evaluate and find prereleases.

In `helm install` documentation there is this statement:
> (..)It will install the latest version of that chart unless you also supply a version number with the '--version' flag.

_source: https://github.com/helm/helm/blob/release-2.15/docs/helm/helm_install.md_

**Expected behavior**
The `helm search` and `helm install` should be consistent. Additionally, documentation should be adjusted to clearly say that pre-releases are skipped or alternatively the constraint in source code should be changed to match also the pre-release versions.
 
---

Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
```

Output of `kubectl version`:
`not applicable`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
`not applicable`

**Comment by karuppiah7890** [comment]
What's the expectation here? I mean, I would be expecting a stable release to be installed and the same can show up in search. What do you think @bacongobbler ?

And @mszostok , since you have done all the research, would you be willing to raise a PR for this issue? :)

**Comment by bacongobbler** [comment]
`helm search` should display the latest stable version, so `0.2.1`. If the `--devel` flag is provided, the latest development version should be displayed, so `0.3.0-beta.1`.

This would appear to be a bug for `helm search repo` in Helm 3 as well.

**Comment by mszostok** [comment]
Exactly, this is a bug in both versions ;) 

**Acceptance Criteria:**
- `helm search` shows the latest stable version
- `helm install` installs the latest stable version
- adding `--devel` flag to above command results in showing/installing latest releases which include also prereleases (include development, alpha, beta, and release candidate releases)


is that correct @bacongobbler?, if yes then I can work on it:)
