### ISSUE TITLE
Helm3: Package error for non-existent directory could be more user friendly

### ISSUE THREAD

**Issue by karuppiah7890** [helm/helm#6713]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.0-beta.4", GitCommit:"7ffc879f137bd3a69eea53349b01f05e3d1d2385", GitTreeState:"dirty", GoVersion:"go1.13.1"}
```

Currently, this is what you see when packaging a non-existent directory

```
$ helm package blah-bloo-blee-blee
Error: validation: chart.metadata is required
```

I think it could be more user friendly. It could be like `blah-bloo-blee-blee: No such file or directory`, similar to `ls` command's error. What do you folks think?

**Comment by zdk** [comment]
@karuppiah7890 

Output of helm version:
```
~ ❯❯❯ helm version                                                                                                                                                                                                             
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

Similar message reports on v2.14.3
```
~ ❯❯❯ helm package blah-bloo-blee-blee
Error: chart metadata (Chart.yaml) missing
```
But I would like to work on this if it makes sense to change to `: No such file or directory`

**Comment by karuppiah7890** [comment]
@zdk This issue has been marked as a feature, and you have v2, for which we have stopped accepting feature PRs. You can use v3 and work on the fix, and I think the error message can be tweaked after the PR too, it shouldn't be a big change. You can start off by working on it for v3 (master branch) and raise a PR 😄  do add tests wherever possible, with respect to this issue
