### ISSUE TITLE
Helm3 revisions secrets messy

### ISSUE THREAD

**Issue by jan-schumacher** [helm/helm#6714]
Helm 3 creates a lot of secrets with many releases of many apps and the list of secrets gets very messy.
My first approach would be to change the way helm3 stores release information into secrets.
Wouldn't it be better if each release would be a secret with revisions stored inside of it? 
Instead of each revision is a new secret.

**Comment by bacongobbler** [comment]
etcd (and therefore Kubernetes) has a 1MB size limit on objects. How do you propose we work around that?

**Comment by jan-schumacher** [comment]
> etcd (and therefore Kubernetes) has a 1MB size limit on objects. How do you propose we work around that?

Thats a thing I didn't thought about.
Is there an option to store like the last `X` revisions and get rid of the previous ones after the next release?

**Comment by jan-schumacher** [comment]
> > etcd (and therefore Kubernetes) has a 1MB size limit on objects. How do you propose we work around that?
> 
> Thats a thing I didn't thought about.
> Is there an option to store like the last `X` revisions and get rid of the previous ones after the next release?

Just saw there is an open issue with exactly the same feature going. So nothing to do here, can be closed.
