### ISSUE TITLE
Cannot install helm 2.14.x instead of buggy 2.15 using helm/master/scripts/get

### ISSUE THREAD

**Issue by disparo13** [helm/helm#6716]
curl https://raw.githubusercontent.com/helm/helm/master/scripts/get > gethelm.sh
bash-5.0# bash gethelm.sh -v 2.14.3
Helm 2.14.3 is available. Changing from version v2.15.0.
Downloading https://get.helm.sh/helm-2.14.3-linux-amd64.tar.gz
SHA sum of /tmp/helm-installer-pLBIjL/helm-2.14.3-linux-amd64.tar.gz does not match. Aborting.
Failed to install helm with the arguments provided: -v 2.14.3
Accepted cli arguments are:
	[--help|-h ] ->> prints this help
	[--version|-v <desired_version>] . When not defined it defaults to latest
	e.g. --version v2.4.0  or -v latest
	[--no-sudo]  ->> install without sudo
	For support, go to https://github.com/helm/helm.

Clean install in a case I don't have helm installed doesn't work as well and none of the previous versions can be installed as well.

**Comment by yangzb09** [comment]
Version 'v2.14.x' may work, don't use '2.14.x'
Try 'bash gethelm.sh -v v2.14.3'

**Comment by disparo13** [comment]
> Version 'v2.14.x' may work, don't use '2.14.x'
> Try 'bash gethelm.sh -v v2.14.3'

I did. Just check my log output. Same situation with 2.14.2, 2.14.1 or even 2.14.

**Comment by hickeyma** [comment]
> SHA sum of /tmp/helm-installer-pLBIjL/helm-2.14.3-linux-amd64.tar.gz does not match

It would seem from this error that the integrity check is failing, so maybe something up with SHAs.  Raising it as a bug while investigate further.

**Comment by kneilb** [comment]
The script works perfectly for me. Missing out the "v" gives the error shown in the OP.
```
neil.burningham@neil-burningham-desktop:srt$ ./gethelm.sh -v v2.14.3
Helm v2.14.3 is available. Changing from version v2.14.1.
Downloading https://get.helm.sh/helm-v2.14.3-linux-amd64.tar.gz
Preparing to install helm and tiller into /usr/local/bin
[sudo] password for neil.burningham: 
helm installed into /usr/local/bin/helm
tiller installed into /usr/local/bin/tiller
Run 'helm init' to configure helm.
neil.burningham@neil-burningham-desktop:srt$ helm version
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

**Comment by zffocussss** [comment]
same issue here today. it worked yesterday

**Comment by bacongobbler** [comment]
what issue are you seeing today?

**Comment by zffocussss** [comment]
> what issue are you seeing today?

I can not install helm v2.14.2 by helm.sh --version v2.14.2

curl: (3) URL using bad/illegal format or missing URL
Failed to install helm with the arguments provided: --version v2.14.2
Accepted cli arguments are:
	[--help|-h ] ->> prints this help
	[--version|-v <desired_version>]
	e.g. --version v2.4.0  or -v latest
	[--no-sudo]  ->> install without sudo
	For support, go to https://github.com/helm/helm.

**Comment by zffocussss** [comment]
it may be a network issue.Because I can install helm locally in a same way.but it failed when in a bitbucket pipeline environment

**Comment by hickeyma** [comment]
@zffocussss Let us know when you figure out what is causing your issue.
