### ISSUE TITLE
issue with helm install 

### ISSUE THREAD

**Issue by redDSsun** [helm/helm#6720]
Output of `helm version`:
Client: &version.Version{SemVer:"v2.15.0", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.0", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
k8s cluster, one msater and two work nodes and all is in centos 7

when run helm install aliyun/mysql --debug, the output is following:
`[debug] Created tunnel using local port: '44358'

[debug] SERVER: "127.0.0.1:44358"

[debug] Original chart version: ""
[debug] Fetched aliyun/mysql to /root/.helm/cache/archive/mysql-0.3.5.tgz

[debug] CHART PATH: /root/.helm/cache/archive/mysql-0.3.5.tgz

Error: validation failed: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"
`
and I tried four charts and the results are same and this issue has blocked me for a few days, any one have some ideas? Thanks.

**Comment by bacongobbler** [comment]
Kubernetes 1.16 dropped many workload APIs including extensions/v1beta1 from being supported. Many charts need to be updated to accomodate this change.

See the release announcement for more details. https://kubernetes.io/blog/2019/09/18/kubernetes-1-16-release-announcement/
