### ISSUE TITLE
Helm upgrade fails in 2.15.0

### ISSUE THREAD

**Issue by DanielHabenicht** [helm/helm#6731]
Upon beeing [auto-updated to 2.15.0 ](https://github.com/microsoft/azure-pipelines-tasks/issues/11608)the `helm upgrade` command started to fail. Trying via bash and downgrading back to `2.14.2` resolved the issue.
```
helm upgrade --tiller-namespace kube-public --namespace kube-public --install --recreate-pods --values /home/vsts/work/r1/a/values.yml --set frontend.image.tag=1.31.0 --wait --tiller-namespace kube-system phonebook /home/vsts/work/r1/a/T-Systems-MMS.phonebook/drop/phonebook-0.1.0.tgz
UPGRADE FAILED
Error: timed out waiting for the condition
Error: UPGRADE FAILED: timed out waiting for the condition
```

Output of `helm version`: 
```bash
Client: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.0", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}
```
> Note: On the Server both versions are 2.15.0

Output of `kubectl version`: 
```bash
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.10", GitCommit:"37d169313237cb4ceb2cc4bef300f2ae3053c1a2", GitTreeState:"clean", BuildDate:"2019-08-19T10:44:49Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

Passing Build: https://dev.azure.com/T-Systems-MMS/phonebook/_releaseProgress?_a=release-environment-logs&releaseId=114&environmentId=174
Failing Build: https://dev.azure.com/T-Systems-MMS/phonebook/_releaseProgress?_a=release-environment-logs&releaseId=116&environmentId=178

Deployed Chart: https://github.com/T-Systems-MMS/phonebook/tree/master/Phonebook/phonebook
values: https://github.com/T-Systems-MMS/phonebook/blob/master/Phonebook.Demo/values.yml

**Comment by hickeyma** [comment]
@DanielHabenicht Cannot tell what error you are getting but I think it might be same issue as #6718. Can you take a look and see if it is?

**Comment by DanielHabenicht** [comment]
Oh, blazing fast! 
Sry, the error is: 
```
UPGRADE FAILED
Error: timed out waiting for the condition
Error: UPGRADE FAILED: timed out waiting for the condition
```

**Comment by hickeyma** [comment]
@DanielHabenicht Might be similar to #5939?

**Comment by DanielHabenicht** [comment]
Nope. Already saw this Issue I purged the release beforehand and started clean everytime. 

It also occurs if the release is installed for the first time.

**Comment by DanielHabenicht** [comment]
Isn't there a way of showing which condition actually triggered the error?

**Comment by marcopaga** [comment]
Same here.
We pinned the version of the client and server to 2.14.3 so we are not blocked.

**Comment by Exodus** [comment]
Any chance you folks are using Traefik for your ingress? @marcopaga @DanielHabenicht

**Comment by marcopaga** [comment]
Yes, we are using Traefik.

**Comment by Exodus** [comment]
@marcopaga check my post in the traefik community forums: https://community.containo.us/t/helm-2-15-upgrades-not-working/2530

This might be your case. To sum things up:

helm 2.15 now checks the health of ingresses, to which Traefik only started to update in traefik 1.7 if you enable the publishedService setting. So if the setting isn't enable, the ingresses will appear as if they're not ready.

Check the post linked, there I explain the problem and follow up with a solution.

**Comment by DanielHabenicht** [comment]
@Exodus I am using traefik too. Do you already opened an issue for making the check default in traefik?

**Comment by Exodus** [comment]
@DanielHabenicht I have created https://github.com/helm/charts/issues/18206

If I have some time I'll try to add it to that help chart and send a PR. For now, the link I posted should help clarify a manual fix. If that solves your problem, this issue should be closed maybe?

**Comment by DanielHabenicht** [comment]
Yep, seems like a traefik problem than. But I would still appreciate an answer to my question.

> Isn't there a way of showing which condition actually triggered the error? @hickeyma

**Comment by timja** [comment]
> Yep, seems like a traefik problem than. But I would still appreciate an answer to my question.
> 
> > Isn't there a way of showing which condition actually triggered the error? @hickeyma

agree, we hit this as well and took far too long to see what the issue was 😢 
would be great if the condition could be returned or added to the status of the release

**Comment by DanielHabenicht** [comment]
@timja Well I was told it not a bug, but a feature 😄 Just update to the preview, this will solve all you issues 🤣
