### ISSUE TITLE
Enabled Helm TLS without having to mention the --tls flag

### ISSUE THREAD

**Issue by TanOfAllCodes** [helm/helm#6739]
Hi, 

In the context of using helm with TLS enabled, we can use the "--tls" flag for every command that we use. 

Example: 

`helm ls --tls`

instead we can have something like

`helm tls-set enabled`
`helm ls`

It would be a very nice to have feature if we could enabled this as a variable or a flag, that we can set for a script without having to do it for every command.

**Comment by hickeyma** [comment]
@TanOfAllCodes [Helm 2.15.0](https://github.com/helm/helm/releases/tag/v2.15.0) was the final feature release for Helm 2. It is only bug fixes now being accepted for Helm 2.

TLS is used for securing communication between the Helm client and Tiller. In Helm 3, Tiller is removed. There will therefore be no need then for TLS for securing commands in Helm 3.

Thank you for raising this feature but closing it as it is not applicable to Helm 3.

**Comment by bacongobbler** [comment]
You can also choose to set the environment variable $HELM_TLS_ENABLE.
