### ISSUE TITLE
doc folder is disappeared from master branch

### ISSUE THREAD

**Issue by ivanov-aleksander** [helm/helm#6745]
It was doc folder in master but it disappeared

**Comment by hickeyma** [comment]
@ivanov-aleksander Helm v2 code is now under the `dev-v2` branch.  As a consequence, the docs path is: https://github.com/helm/helm/tree/dev-v2/docs

The v3 docs are in: https://github.com/helm/helm-www/tree/dev-v3-docs/content/docs

**Comment by hickeyma** [comment]
Closing as question is answered.
