### ISSUE TITLE
helm 3 beta 5 list release from another user

### ISSUE THREAD

**Issue by antoineozenne** [helm/helm#6761]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.0-beta.5", GitCommit:"509a8819b7e8dba86b7982c006fce22628aeea28", GitTreeState:"clean", GoVersion:"go1.13.3"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
On-premise platform.

We are a lot of people to work with helm on the same Kubernetes cluster. Each is authenticated via an Active Directory, so each have his own token to use kubectl.
If Bob install a new helm release, so Alice can't list the Bob's release, even if she has a cluster-admin clusterrole. However, Alice can list all Bob's pods via kubectl. Maybe it's normal, so I misunderstand the RBAC logic with helm 3. Is it a bug ? Can we have documentation about that ?

**Comment by bacongobbler** [comment]
Does the documentation under https://v3.helm.sh/docs/intro/rbac/ help here? I presented a talk on how Helm 3 interacts with RBAC, which influenced the documentation. You can find the recording of that talk here: https://www.youtube.com/watch?v=uZ_ihxYZhBo

Hope this helps. Please feel free to suggest changes to the documentation if the existing document is insufficient. Thanks!
