### ISSUE TITLE
Some templating functions broken in latest Helm v2

### ISSUE THREAD

**Issue by sc250024** [helm/helm#6763]
# Description

The latest Helm v2 has issues with some `range` loops for certain charts. As far as I can tell, the problem **does not** exist in Helm v3.

# Details

I am testing against the Bitnami Helm charts repository (https://github.com/bitnami/charts) at commit `407e4f4a978bc2b0ead5504f5e957dc7dd0c0c2e` as a reference.

Basically, the `zookeeper` chart has the following template to generate the `ZOO_SERVERS` environment variable for Zookeeper:

```yaml
- name: ZOO_SERVERS
  {{- $replicaCount := int .Values.replicaCount }}
  {{- $followerPort := int .Values.service.followerPort }}
  {{- $electionPort := int .Values.service.electionPort }}
  {{- $releaseNamespace := .Release.Namespace }}
  {{- $zookeeperFullname := include "zookeeper.fullname" . }}
  {{- $zookeeperHeadlessServiceName := printf "%s-%s" $zookeeperFullname "headless" | trunc 63  }}
  {{- $clusterDomain := .Values.clusterDomain }}
  value: {{ range $i, $e := until $replicaCount }}{{ $zookeeperFullname }}-{{ $e }}.{{ $zookeeperHeadlessServiceName }}.{{ $releaseNamespace }}.svc.{{ $clusterDomain }}:{{ $followerPort }}:{{ $electionPort }} {{ end }}
```

The link to the actual StatefulSet YAML file is [here](https://github.com/bitnami/charts/blob/407e4f4a978bc2b0ead5504f5e957dc7dd0c0c2e/bitnami/zookeeper/templates/statefulset.yaml#L100-L108).

Basically, that template above gets the number of replicas desired, and writes a string that ZooKeeper uses for replication between nodes.

If I run the following command using Helm v2:

```shell
./helm2 install \
--debug \
--dry-run \
--set 'replicaCount'='3' \
/some/local/path/to/bitnami/zookeeper
```

I get the following for the `ZOO_SERVERS` variable:

```yaml
- name: ZOO_SERVERS
  value:
```

Which is **wrong**. When I do the same thing, but using Helm v3 against the local chart:

```shell
./helm3 install \
--debug \
--dry-run \
--generate-name \
--set 'replicaCount'='3' \
/some/local/path/to/bitnami/zookeeper
```

I get the following for the `ZOO_SERVERS` variable:

```yaml
- name: ZOO_SERVERS
  value: zookeeper-1571844177-0.zookeeper-1571844177-headless.hbase-test.svc.cluster.local:2888:3888 zookeeper-1571844177-1.zookeeper-1571844177-headless.hbase-test.svc.cluster.local:2888:3888 zookeeper-1571844177-2.zookeeper-1571844177-headless.hbase-test.svc.cluster.local:2888:3888
```

Which is **correct**.

**Did this get broken with the https://github.com/helm/helm/releases/tag/v2.15.0 release, and upgrade of Sprig?**

# Versions

Output of `helm version` (v3):

```
version.BuildInfo{Version:"v3.0.0-beta.5", GitCommit:"509a8819b7e8dba86b7982c006fce22628aeea28", GitTreeState:"clean", GoVersion:"go1.13.3"}
```

Output of `helm version` (v2):

```
Client: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.0", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}
```

Output of `kubectl version`: **N/A** but it's

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): **N/A**

**Comment by bacongobbler** [comment]
Yes. Please upgrade your Tiller instance to 2.15.1 using `helm init --upgrade`. See #6708 for more context.

Thanks!
