### ISSUE TITLE
Add additional check in PR to check if tests are written

### ISSUE THREAD

**Issue by karuppiah7890** [helm/helm#6765]
In the past I've seen some PRs with no tests. Sometimes maintainers comment and ask folks to write tests. 

My suggestion is - put an extra check in PR along with current test pass check and developer signing check. This extra check will ensure that if at least one go file is part of the PR, then there must be at least one *_test.go file. This way we can support PRs where 
1. Only docs (markdown) could be updated in PRs
2. Just tests can added with no code, for better test coverage
3. If code is written, at least one *_test.go must be there. 

Later maintainers can check what test has been added and if it's relevant and stuff. But they won't have to nudge them to write tests. Nudging will be very minimal, as some people do miss the checks, but that's only some. 

And if some code is not testable or writing test was tough, then that can be discussed. Check will fail, but test could be added with help and making code testable or that could be a separate PR, and PR can still be merged with some manual checking, but yeah, automatic check for tests would have failed. That's okay

So this extra check will act like a nudge for new contributors especially. What do you all think?

**Comment by bacongobbler** [comment]
From my point of view, I don't see an issue with the current system that requires automation. We certainly do strive for good test coverage, but it's one of those things that are handled on a case-by-case basis.

During code review, if we see a pull request that could be improved with test coverage, then we ask for unit tests. There are many cases where unit tests do not make sense. Internal code refactors, PRs that revert changes, Day Zero security releases, bumping revisions, and documentation updates (help strings, READMEs, changes to CONTRIBUTING.md) are a few examples where automation won't help. These are all handled on a case-by-case basis.

> And if some code is not testable or writing test was tough, then that can be discussed. Check will fail, but test could be added with help and making code testable or that could be a separate PR, and PR can still be merged with some manual checking, but yeah, automatic check for tests would have failed. That's okay

Failing checks imply to the developer that it's a mandatory action, so I don't think that's a good first contributor's experience. It also requires administrative privileges on the repository to merge a PR that fails a check.

**Comment by karuppiah7890** [comment]
Of course doc updates should be ignored by the automation. Only when go files change, test file presence needs to be checked.

Didn't think about the refactoring part though 🙈 

And reverts, if actual commit had test, revert will also have revert in test so test file will be there, or else there will be problems, yes. 

Bumping versions - I'm hoping it's only go.mod and go.sum files or glide.yaml and glide.lock files for v2. If code changes, may be tests could change if it's present. Or else it has to be added

 And I didn't know merging failed PR requires admin privileges.

**Comment by karuppiah7890** [comment]
This was just an idea. Or in the PR template, we can mention that tests are good to keep the software robust and that if they wrote code, we could ask them to try to see if they can add tests too

**Comment by bacongobbler** [comment]
Closing as something we don't plan to implement.
