### ISSUE TITLE
`--set` is ignored when `--reset-values` is used during helm3 upgrade

### ISSUE THREAD

**Issue by SeMeKh** [helm/helm#6766]
Issuing a `helm3 upgrade --reset-values --set "someKey=someValue"` command does not set the `someKey` value to `someValue` contrary to `helm2`'s behavior.
The issue looks a lot like #6112 except it is caused by `--reset-values` rather than `--reuse-values`.

Output of `helm version`: 
```
version.BuildInfo{Version:"v3.0.0-beta.5", GitCommit:"509a8819b7e8dba86b7982c006fce22628aeea28", GitTreeState:"clean", GoVersion:"go1.13.3"}
````

**Comment by karuppiah7890** [comment]
Thanks for reporting this @SeMeKh . Feel like taking a crack at this? 😄

**Comment by karuppiah7890** [comment]
Also, I tried to reproduce the issue. I'm not able to. The existing values get reset and new values get set for me. This is what I got

```
$ helm upgrade dummy dummy-chart/ --set yetAnother=yetAnotherValue --set blah=bloo
Release "dummy" has been upgraded. Happy Helming!
NAME: dummy
LAST DEPLOYED: Tue Oct 29 21:36:20 2019
NAMESPACE: default
STATUS: deployed
REVISION: 8
TEST SUITE: None

$ helm get values dummy
USER-SUPPLIED VALUES:
blah: bloo
yetAnother: yetAnotherValue

$ helm upgrade dummy dummy-chart/ --reset-values --set yetAnother=meh
Release "dummy" has been upgraded. Happy Helming!
NAME: dummy
LAST DEPLOYED: Tue Oct 29 21:36:42 2019
NAMESPACE: default
STATUS: deployed
REVISION: 9
TEST SUITE: None

$ helm get values dummy
USER-SUPPLIED VALUES:
yetAnother: meh

$ helm version
version.BuildInfo{Version:"v3.0.0-beta.5", GitCommit:"509a8819b7e8dba86b7982c006fce22628aeea28", GitTreeState:"clean", GoVersion:"go1.13.3"}
```

@SeMeKh Could you probably give the situation where it didn't work for you.

**Comment by SeMeKh** [comment]
@karuppiah7890 You're right. Apparently this was an issue with helm-diff rather than helm itself:
https://github.com/databus23/helm-diff/issues/157
Thanks for investigating it.
