### ISSUE TITLE
Helm 3 Beta 5 SecurityContext DaemonSet fails

### ISSUE THREAD

**Issue by rblaine95** [helm/helm#6776]
**Describe Issue**
When using Helm-3-beta5 and installing a chart that has a DaemonSet that has a pod Security Context and an Update Strategy, the following error gets printed:
```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(DaemonSet.spec.template.spec.containers[0].securityContext): unknown field "fsGroup" in io.k8s.api.core.v1.SecurityContext, ValidationError(DaemonSet.spec.template.spec.containers[1].securityContext): unknown field "fsGroup" in io.k8s.api.core.v1.SecurityContext, ValidationError(DaemonSet.spec.template.spec.securityContext): unknown field "privileged" in io.k8s.api.core.v1.PodSecurityContext, ValidationError(DaemonSet.spec.template.spec): unknown field "updateStrategy" in io.k8s.api.core.v1.PodSpec]
```
The Security Context values are:
```yaml
securityContext:
  privileged: true
  runAsUser: 0
  fsGroup: 0
```
And the UpdateStrategy is:
```yaml
updateStrategy:
  rollingUpdate:
    maxUnavailable: 1
  type: RollingUpdate
```
This worked with Helm-3-beta4
```
$ h3 version
version.BuildInfo{Version:"v3.0.0-beta.4", GitCommit:"7ffc879f137bd3a69eea53349b01f05e3d1d2385", GitTreeState:"dirty", GoVersion:"go1.13.1"}
```

Output of `helm version`: 
```
$ helm version
version.BuildInfo{Version:"v3.0.0-beta.5", GitCommit:"509a8819b7e8dba86b7982c006fce22628aeea28", GitTreeState:"clean", GoVersion:"go1.13.3"}
```

Output of `kubectl version`:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-07-08T19:16:39Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  Local bare metal OKD v3.11
```
$ oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://okd.example.net:443
openshift v3.11.0+01dd962-225
kubernetes v1.11.0+d4cacc0
```

**Comment by bacongobbler** [comment]
3.0.0-beta.5 added OpenAPI validation for resources (see #6599). It's likely that the DaemonSet resource you are trying to install fails validation, which means it does not match the schema provided by Kubernetes.

Looking at the SecurityContext API schema, `fsGroup` does not exist as part of that field. It is part of the Pod Security Policy spec.

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#securitycontext-v1-core
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#podsecuritypolicyspec-v1beta1-extensions

Please check and ensure that the DaemonSet complies with the OpenAPI schema for your version of Kubernetes.

For reference: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11

Closing as resolved.
