### ISSUE TITLE
Can not build using archive tarballs, due to git command used in make process

### ISSUE THREAD

**Issue by kittydoor** [helm/helm#6777]
Steps:
1. Get source archive from https://github.com/helm/helm/archive/v2.15.1.tar.gz
2. Untar and cd
3. Run `make`

Expected:
Package builds successfully

Actual:
Error "fatal: Needed a single revision" due to calls to git in versioning.mk
The archive tarballs don't have the .git folder, thus git can not function

Fix:
Update makefile to find required information elsewhere or fallback to other options if .git folder doesn't exist

**Comment by bacongobbler** [comment]
GitHub provides these tarballs as part of the release, and there is no way to remove them from the release page. The Makefile needs to check which tag is currently checked out to set the version information correctly for the Helm binary.

Please clone the repository from a particular tag instead if you wish to build from scratch. Thanks.
