### ISSUE TITLE
Cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by Nittarab** [helm/helm#6782]
Output of `helm version`: 
```
Client: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-gke.1", GitCommit:"61c30f98599ad5309185df308962054d9670bafa", GitTreeState:"clean", BuildDate:"2019-08-28T11:06:42Z", GoVersion:"go1.12.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

If I try to use a Helm command inside a shell script I get this error:
`./test.sh: line 2: /usr/local/bin/helm: cannot execute binary file: Exec format error`

Step to reproduce: 
1) create script `test.sh`
```bash
#!/bin/bash -e
helm ls
```
2)  `chmod +x test.sh`
3)  `./test.sh`

I have used https://github.com/snapcrafters/helm/

**Comment by bacongobbler** [comment]
This error can occur if your computer architecture is different than the binary that was installed. Can you please check and verify that /usr/local/bin/helm is the linux/amd64 variant? You can do so with `file /usr/local/bin/helm`.

**Comment by Nittarab** [comment]
Thanks @bacongobbler
the output is:
`/usr/local/bin/helm: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, stripped`

If i run `dpkg --print-architecture`
`amd64`

**Comment by bacongobbler** [comment]
Bingo. You have an 64-bit version of Helm that's supposed to work on ARM architectures. Please use a version of Helm that works on AMD architectures.

https://get.helm.sh/helm-v2.15.1-linux-amd64.tar.gz

Can you file an issue with snapcrafters/helm?

**Comment by Nittarab** [comment]
Thank you, I created the issue https://github.com/snapcrafters/helm/issues/48

**Comment by Mornster061** [comment]
everytime i write my token in a terminal of kali , it shows such error
bash: /usr/bin/ngrok: cannot execute binary file: Exec format error
is there anything i can do about it to solve it???????

**Comment by ahsan-khan1999** [comment]
getting same issue while running mongod
