### ISSUE TITLE
helm repo update tries to access wrong windows profile folder

### ISSUE THREAD

**Issue by marcelser** [helm/helm#6789]
Hi I just installed helm on windows 10 into minikube (after downgrading minikube kubernetes version as helm is not yet compatible with kubernetes 1.16) and "helm init" worked well and created in the correct user profile which is C:\ElserM\.helm it's profile.

But when I try to do a "helm repo update" it tries the store it in C:\marc.elser\.helm which is an old inactive profile on this windows machine that wasn't used for months. Here's the complete output
```
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Unable to get an update from the "stable" chart repository (https://kubernetes-charts.storage.googleapis.com):
        open C:\Users\marc.elser\.helm\repository\cache\stable-index.yaml: Das System kann den angegebenen Pfad nicht finden.
Update Complete. ⎈ Happy Helming!⎈
```

my %USERPROFILE% directory is set to:
C:\Users\elserm

I also grepped my whole 'env' for "marc.elser" and didn't found any reference. So where does helm even get this information from and how to fix this 

Even when I try to set HELM_HOME to 'C:\Users\elserm\.helm' I get exactly the same error, it still want's access .helm on a wrong old user profile for whatever reason I don't know and I also don't know how to resolve this issue.

```
Output of `helm version`:
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:51:13Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/386"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:55Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
minikube
```

**Comment by hickeyma** [comment]
@marcelser It might be worth first upgrading to the latest version of Helm 2 which is [v2.15.1](https://github.com/helm/helm/releases/tag/v2.15.1).  There would have been a lot of fixes and capability added since `2.9.1`.

To try and troubleshoot this: Could you also . try setting `HELM_HOME` to something like 'C:\Users\elserm\.helm' and see if that works? Also maybe create the path ` 'C:\Users\elserm` beforehand.

**Comment by marcelser** [comment]
In the end I noticed that I can fix it in 2.9.1 by just editing the paths in repositories.yaml file. But the question remains how helm constructed this paths with wrong user profile dir. But I agress I should upgrade to helm 2.15.1 I guess, it's just that "choco install kubernetes-helm" is very outdated then because it install 2.9.1 which is not good as it's mentioned as one of the install methods on the official docs. I would expect that all installation methods are kept up to date.

**Comment by hickeyma** [comment]
> But the question remains how helm constructed this paths with wrong user profile dir.

Difficult to tell with version that old. If you can try and upgrade, we can better troubleshoot this.

> it's just that "choco install kubernetes-helm" is very outdated then because it install 2.9.1 which is not good as it's mentioned as one of the install methods on the official docs. 

As far as I can see it currently supports `v2.15.1`: https://chocolatey.org/packages/kubernetes-helm

**Comment by marcelser** [comment]
Ok, this is one of the classical cases of user too stupid. I didn't know that chocolatey keeps a local repo so I was assuming that it always installs newest version. I turned out I was very wrong, you have to update chocolatey repo and voila 2.15.1 shows up. So the only person to blame in this case is myself. So I will close this now. Hope I didn't bother you too much.

**Comment by hickeyma** [comment]
@marcelser Not a bother.
