### ISSUE TITLE
v3: Clarify usage of --max and --offset for helm list

### ISSUE THREAD

**Issue by marckhouzam** [helm/helm#6801]
Now that Tiller is gone, `helm list` uses the kubernetes API directly and seems to be pretty fast.  It makes me wonder if the whole `--max` and `--offset` pagination scheme is as valuable as it was for helm v2.

More importantly, I wonder if the default of 256 releases returned is still appropriate.

Looking at the code around the following line
https://github.com/helm/helm/blob/master/pkg/action/list.go#L182
it looks like helm v3 receives the entire list of releases, and then truncates it based on the `--max` and `--offset` flags.

This makes me wonder why helm truncates the list of releases to 256 by default since it has the entire list anyway?

Also, unlike helm v2, setting `--max` to 0 will return all releases (IIUC).
So, I wonder if it would be more appropriate to set `--max` to 0 by default.

And if so, I even wonder when a user would even want to use `--max` and `--offset`?  It would have to be in the case where the user wants to reduce the amount of output from `helm list`, but there are tools to do this such as `tail` and `head`; why even have helm do this truncation?

In looking into this I provisioned over 50,000 namespaces in a Kind cluster and saw that when doing `kubectl get namespaces` all 50,000 namespaces were returned by kubectl.

Also, I provisioned 1000 helm v3 releases and when running `helm list -m 0`, I got the entire 1000 releases in less than one second!

I'm looking for the maintainers opinion and experience on this before possibly making a PR.

Thanks

**Comment by thomastaylor312** [comment]
You bring up a good point here. Not sure if we need max or pagination offset flags anymore, especially if we are pulling the whole list anyway. The only thing I can think of is someone pulling the list of releases for displaying in a web UI, but I feel like that is something you wouldn't use the CLI to do. 

Let me ping some of the other core maintainers to look at this, since it will be a breaking change to the CLI if we remove them. I'll pull this into 3.0 right now so we don't miss it. We can pop it off if we decide it is something we can handle later

**Comment by bacongobbler** [comment]
Helm 2 never really filtered out of paginated results correctly. I think it might've in much older releases, but Tiller fetched and returned all results, which was then filtered client-side. The goal was to restrict the number of calls to the API. I just don't think anyone got around to fixing this behaviour.

This issue became present when your cluster had a particularly high number of release metadata. gRPC had a data streaming limit of 4MB (see #3322). A `helm list` would error out unless you cleaned up older release metadata. 

That error may no longer be present now that gRPC has been removed in Helm 3. However, if Kubernetes has pagination/limit options on the API, it may be worth looking into to prevent excessive server-side load on API requests.

I think it's worth looking into seeing if we can fix this behaviour, especially with things like `helm list --all-namespaces`, `helm list --all` and `helm history` in mind.

**Comment by bacongobbler** [comment]
FWIW, I'm thoroughly impressed by the numbers presented by @marckhouzam. What I'm mostly concerned about are the following scenarios:

- I have a cluster with 1 namespace - one per user. Each namespace has 10,000 releases
- I have a cluster with 10 namespaces - one per user. Each namespace has 1,000 releases
- I have a cluster with 100 namespaces - one per user. Each namespace has 100 releases
- I have a cluster with 1,000 namespaces - one per user. Each namespace has 10 releases
- I have a cluster with 10,000 namespaces - one per user. Each namespace has 1 release

The examples provided by @marckhouzam covers the first scenario quite well - one user fetching all information. The one drawback of that scenario is that the usage of the API is infrequent enough that the server can store that information in memory and serve it as-needed on an infrequent basis.

My concern is without pagination, users in the last few results (where the amount of data required to fetch is low, but the rate of retrieval is high) may suffer from server-side load issues as each request to the API would fetch 10,000 object from memory, causing excessive load on the backend.

Does that make sense?

**Comment by bacongobbler** [comment]
We could consider removing these feature flags for the moment for now and re-assess the use case after 3.0, potentially re-introducing them in a future Helm 3 release. Does that sound reasonable?

**Comment by thomastaylor312** [comment]
@bacongobbler I think it might be safer to remove these and then add them back seeing as they don't actually provide what they intend to right now

**Comment by bacongobbler** [comment]
SGTM

**Comment by thomastaylor312** [comment]
@marckhouzam What do you think? Should we leave this in and then address it more fully after the 3.0 release?

**Comment by marckhouzam** [comment]
Whatever you guys feel is better considering backward compatibility from 3.1 to 3.0.

**Comment by thomastaylor312** [comment]
I think we leave it in with a note that it is a known issue and then we can open a PR after 3.0

**Comment by technosophos** [comment]
Moving to 3.3. Is there any update on this?
