### ISSUE TITLE
MacOS conversion of json.Number to int

### ISSUE THREAD

**Issue by johscheuer** [helm/helm#6803]
Like described in this issue here: https://github.com/istio/istio/issues/18373 it seems like there is a bug in helm (or spring?) when converting a `json.Number` to an `int`.

This is the current input: https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/values.yaml#L376-L384 and this is the conversion method: https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/gateways/templates/_affinity.tpl#L18 like described in the issue above the `| int` results in `0`. 

If I find the time I will take a look if the issues comes from helm or the spring functions.

Output of `helm version`:

I tried to different versions both have the same behaviour:

```bash
helm version
Client: &version.Version{SemVer:"v2.15.0", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}


helm version
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}
```

Output of `kubectl version`:
- not used

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
- not used

**Comment by karuppiah7890** [comment]
This looks like a duplicate of https://github.com/helm/helm/issues/6708 . Would recommend you to try v2.15.1 and see if it works for you

**Comment by karuppiah7890** [comment]
Also, it's weird that you saw the issue in v2.14.3 too, as according to #6708 it works in v2.14.3 🤔

**Comment by johscheuer** [comment]
I just cross-checked it seems like it does work under `v2.14.3` seems like I did a mistake when testing with `v2.14.3`. Also checked that it works in `v2.15.1`.

Thanks for the fast feedback !
