### ISSUE TITLE
Document local charts path in requirements.yml files

### ISSUE THREAD

**Issue by Tazminia** [helm/helm#6804]
Hello,

According to this [thread](https://github.com/helm/helm/pull/1923), it is possible to use some path like file://local/path/to/chart instead of some chart repository URL.

In the [documentation](https://helm.sh/docs/charts/#managing-dependencies-with-requirements-yaml), I do not see any examples or mention for this feature.

Can we add it to the documentation or make it more accessible (if it is already there)

**Comment by bacongobbler** [comment]
Feel like adding this documentation to the site? :)

**Comment by Tazminia** [comment]
@bacongobbler of course. If you would like to point me to the document to change or to a documentation that explains the documentation structure.

**Comment by bacongobbler** [comment]
Helm 2 documentation resides in the `dev-v2` branch, under the `docs/` folder: https://github.com/helm/helm/tree/dev-v2/docs

Helm 3 documentation resides in the `dev-v3-docs` branch in the helm-www project, under the `content/docs` folder:  https://github.com/helm/helm-www/tree/dev-v3-docs/content/docs

**Comment by Tazminia** [comment]
Thank you for the information. I will create a PR as soon as possible

**Comment by Tazminia** [comment]
I found a [mention](https://github.com/helm/helm-www/blob/dev-v3-docs/content/docs/topics/chart_best_practices/dependencies.md) of using local file paths in the documentation of helm 3.
As for helm 2 the same section appears [here](https://github.com/helm/helm/blob/dev-v2/docs/chart_best_practices/requirements.md).

I am not sure if there is a better place in the documentation for explaining this.

**Comment by SamuAlfageme** [comment]
I think this one can be closed since the relevant docs are there:
- https://v2.helm.sh/docs/chart_best_practices/#repository-urls
- https://helm.sh/docs/chart_best_practices/dependencies/#repository-urls

**Comment by hickeyma** [comment]
@SamuAlfageme I think that the documentation could be improved upon. Maybe flesh it out and provide some examples.

@Tazminia Did you get a chance to push PR for this?

**Comment by georgettica** [comment]
I am willing to give it a go will push in a few

**Comment by baijum** [comment]
> Maybe flesh it out and provide some examples.

I can see some examples here: https://helm.sh/docs/helm/helm_dependency/

**Comment by Stolarskis** [comment]
Are any more examples needed? Or should this issue be closed?
