### ISSUE TITLE
No kind "ServiceMonitor" is registered for version "monitoring.coreos.com/v1"

### ISSUE THREAD

**Issue by davidmogar** [helm/helm#6813]
Although I've seen similar problems I think this is slightly different given the kind of deployment.

We have a cluster provided by our cloud team and they deploy several things (common stuff for all the clients) using Helm (v2). Then, my team, deploy our application in this cluster using also Helm (v3).

One of the things pre-installed in the cluster is Prometheus-operator, which defines the `ServiceMonitor` CRD. We define a resource of this kind to monitor our application using the pre-installed Prometheus. The installation works perfectly and everything works as expected. The problems occur when we try to upgrade.

At this moment, Helm not only points all the mistakes we had in our manifests (doesn't do this by default during installation what is quite odd in my opinion) but also complains with the next error:
```
UPGRADE FAILED: unable to decode "": no kind "ServiceMonitor" is registered for version "monitoring.coreos.com/v1" in scheme "k8s.io/client-go/kubernetes/scheme/register.go:65"
```
Nevertheless, the resource exists:
```
$ kubectl explain ServiceMonitor
KIND:     ServiceMonitor
VERSION:  monitoring.coreos.com/v1

DESCRIPTION:
     <empty>
```

We tried to put the `ServiceMonitor` manifest between these tags:
```
{{- if .Release.IsInstall }}
# manifest
{{- end }}
```
The problem with this is that Helm removes the existing resource with every single upgrade, which is not the desired outcome.

What is the appropriate approach to fix this problem?

Output of `helm version`: 3
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"archive", BuildDate:"2019-06-18T20:40:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): OpenStack Magnum

**Comment by bacongobbler** [comment]
Can you test this with 3.0.0-rc.1? This error should have been fixed in more recent versions.

If you can provide the output of `helm version`, that would be helpful. I can't tell which alpha/beta/RC you were testing with.

**Comment by davidmogar** [comment]
I'll try the release as soon as I can. The tests were done with the 5th beta over an older helm home (2nd beta). Is it enough with using the most recent binary or I need to do something else? Do I have to delete the current deployments also?

**Comment by bacongobbler** [comment]
I would suggest re-creating the bug in a new environment. the pre-releases have known backwards compatibility breakers between each release.

**Comment by bacongobbler** [comment]
Closing for now as I believe this has been fixed in later releases. Please feel free to comment here if this is not the case in your testing. Thanks.
