### ISSUE TITLE
pkg/repo.NewChartRepository does not honor HELM_REPOSITORY_CACHE

### ISSUE THREAD

**Issue by joelanford** [helm/helm#6814]
Output of `helm version`: 82a100b0b727bcb58ec8f289b386eec4bb03b9a5

Output of `kubectl version`: 
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T16:51:36Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): minikube

**Description**

In `pkg/chart/chartrepo.go`, we set `CachePath` like this: 

https://github.com/helm/helm/blob/82a100b0b727bcb58ec8f289b386eec4bb03b9a5/pkg/repo/chartrepo.go#L75)

However if we used `cli.EnvSettings.RepositoryCache` it would honor the HELM_REPOSITORY_CACHE envvar:

https://github.com/helm/helm/blob/82a100b0b727bcb58ec8f289b386eec4bb03b9a5/pkg/cli/environment.go#L69

**Comment by bacongobbler** [comment]
This is working as intended. `helmpath` uses the XDG configuration directory specification for path lookups. `pkg/cli` wraps in Helm conventions like HELM_REPOSITORY_CACHE as an override. If you want to rely on the CLI's functionality, you'l want to use `pkg/cli`.
