### ISSUE TITLE
Helm post installation hooks hook-weight is not taken into account during job execution.

### ISSUE THREAD

**Issue by dogruyurek** [helm/helm#6832]
I have two post installation hook jobs which have sequential hook-weight defined in it.
In first hook hook-weight is 6 and in second is 7

those are the annotation parts of post installation hooks

First post installation hook  
annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "6"
    "helm.sh/hook-delete-policy": before-hook-creation 

Second post installation hook
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "7"
    "helm.sh/hook-delete-policy": before-hook-creation 

When I install helm chart, I noticed that both post installation hooks are created at the same time even if I define hook-weight in sequential order. 

First hook is creating DB schema on Cassandra DB, second hook is populating data on Cassandra DB, second hook needs to be run both in post-install and post-upgrade and have to be run after first hook is completed. 

The expected behavior is to create second post installation hook after first one is completed. It was working as like that in v2.12.2

Output of `helm version`:
Client: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:57:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-04-03T04:12:37Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (on-promise):

**Comment by tmirks** [comment]
Anyone know if this has been resolved in 2.16.0?

**Comment by bacongobbler** [comment]
no bugfixes related to chart hooks were addressed in 2.16.0.

**Comment by thomastaylor312** [comment]
So many of these reported hook issues may all be resolved by a recently merged fix #6897. Can anyone give the `dev-2` branch a try and see if it fixes it for them?

**Comment by bacongobbler** [comment]
While I don't have a chart which I can use to verify the behaviour locally, I'm fairly certain this has been fixed in #6897. That patch fixes an issue with the kube client unable to wait for Jobs to run to completion as seen in #6894. Kubernetes 1.16 introduced a breaking change to the legacy schema so we had to update the code to reflect that change.

I'm going to close this as tentatively resolved via #6897, which will be in Helm 2.16.1. Please feel free to report your findings once 2.16.1 has been released with the likely fix mentioned above and we'll re-open if this is still an issue in 2.16.1+. I'm interested to hear your findings!

**Comment by thomastaylor312** [comment]
I am pretty certain that this should be solved by #6907. So what is probably happening is that Helm isn't waiting for jobs to complete (see the explanation in the linked PR). Going to leave this closed for now as the PR is now open. If that PR does not resolve the issue, please let us know
