### ISSUE TITLE
Helm 3.0.0-rc.1 doesn't support downloading charts from a URL containing local

### ISSUE THREAD

**Issue by richardwhiuk** [helm/helm#6833]
With:

```
$ helm version
version.BuildInfo{Version:"v3.0.0-rc.1", GitCommit:"ee77ae3d40fd599445ebd99b8fc04e2c86ca366c", GitTreeState:"clean", GoVersion:"go1.13.3"}
```

If I attempt to install a chart from a URL containing `local`, the install fails with `Error: scheme "local" not supported`

Full debug output

```
$ helm repo add msw https://artifactory.metaswitch.com/helm-local/
"msw" has been added to your repositories
$ helm install bar msw/foo --version "0.1.0-master" --devel --atomic --debug
install.go:148: [debug] Original chart version: "0.1.0-master"
Error: scheme "local" not supported
helm.go:76: [debug] scheme "local" not supported
helm.sh/helm/v3/pkg/getter.Providers.ByScheme
        /home/circleci/helm.sh/helm/pkg/getter/getter.go:117
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo
        /home/circleci/helm.sh/helm/pkg/downloader/chart_downloader.go:92
helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart
        /home/circleci/helm.sh/helm/pkg/action/install.go:665
main.runInstall
        /home/circleci/helm.sh/helm/cmd/helm/install.go:160
main.newInstallCmd.func1
        /home/circleci/helm.sh/helm/cmd/helm/install.go:115
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:75
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1357```
```

However, if I use a URL which doesn't include local in the name, install makes progress:

```
$ helm repo remove msw
"msw" has been removed from your repositories
$ helm repo add msw https://artifactory.metaswitch.com/helm-virtual/
"msw" has been added to your repositories
$ helm install bar msw/foo --version "0.1.0-master" --devel --atomic --debug
install.go:148: [debug] Original chart version: "0.1.0-master"
install.go:165: [debug] CHART PATH: /home/rjw2/.cache/helm/repository/foo-0.1.0-master.tgz

client.go:87: [debug] creating 65 resource(s)
wait.go:51: [debug] beginning wait for 65 resources with timeout of 5m0s
...
```

**Comment by richardwhiuk** [comment]
At the end of that sequence of steps, the repo list is as expected and contains:

```
$ helm repo list
NAME    URL
msw     https://artifactory.metaswitch.com/helm-virtual/
```

Your repo doesn't reflect the bug - the URL of the repo you've added doesn't contain `local` which appears to be relevant.

**Comment by richardwhiuk** [comment]
This is a helm 3 install pointing at a cluster which does have a helm 2 tiller pod running on it.

The local client is a helm 3 install by doing `curl -L https://git.io/get_helm.sh | bash -s -- -v v3.0.0-rc.1`

There is a local helm 2 client installed from snap (`sudo snap install helm`), but that's not being used here.

**Comment by richardwhiuk** [comment]
I added a repo with the world local in the URL:

```
$ helm repo add msw https://artifactory.metaswitch.com/helm-local/
"msw" has been added to your repositories
```

**Comment by mattfarina** [comment]
@richardwhiuk

After you add `https://artifactory.metaswitch.com/helm-local/` can you share your repositories file. It should contain the information on what was added.

**Comment by marckhouzam** [comment]
@richardwhiuk in case it helps, the command `helm env` can help you find the directory where the repository.yaml file is located.

**Comment by jdolitsky** [comment]
This might also have to do with the `requirements.yaml` file in the specified chart. It looks like it's trying to grab a dependency

**Comment by karuppiah7890** [comment]
Looks like somehow the url in the repository index, that is the `index.yaml` says `local://...`, as I just tried to replicate this in my local with dummy data, and was able to successfully do it only when I created an index like this - `helm repo index . --url local://`

I don't think this is a bug in helm, unless there's more data on this to help understand the problem

**Comment by karuppiah7890** [comment]
Surely the word local in the repo url is not causing any issues. Even the repo URL I tried was `http://localhost:5000/dumm-repo-local`. We need to change the issue name as it's misleading

**Comment by hickeyma** [comment]
> Do you mind doing a find/search in your system for the file repository.yaml and output the contents and path of each version you find?

@richardwhiuk If you could provide this information, it would help troubleshoot the problem. Thanks.

**Comment by ehernandez-xk** [comment]
I have the same issue, I tired to rename the repo, but the same issue, I think is related that the chart url is stored as `local://hello-chart/hello-chart-0.1.0.tgz`

```
cat ~/Library/Caches/helm/repository/msw-index.yaml
...
hello-chart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: 2019-12-05T13:41:06.954Z
    description: A Helm chart for Kubernetes
    digest: e4dea1aa6062c5a8b3872dd38b1612c3832bd8bd838f693e037cc158863e1977
    name: hello-chart
    urls:
    - local://hello-chart/hello-chart-0.1.0.tgz
    version: 0.1.0
generated: 2019-12-05T13:41:07.675Z
```
I have no idea how the `local` got there.

**Comment by ehernandez-xk** [comment]
The issue only happens when I add the local-repo and does not happen with virtual-repo
We should use the virtual repo created in the Artifactory

no issue:
```
helm repo add msw  https://artifactory.mycompany.com/artifactory/virtual-helm-charts
```
there is issue:
```
helm repo add msw   https://artifactory.mycompany.com/artifactory/helm-charts
```

**Comment by ehernandez-xk** [comment]
Not sure but I think we should configure 2 repositories, local to push and virtual to get charts

Configure 2 helm repositories
```
helm repo add my-local-repo  https://artifactory.my-company.com/artifactory/helm-charts
helm repo add my-virtual-repo https://artifactory.mycompany.com/artifactory/virtual-helm-charts
```
```
helm repo list
NAME           	URL
stable         	https://kubernetes-charts.storage.googleapis.com/
my-local-repo  	https://artifactory.mycompany.com/artifactory/helm-charts
my-virtual-repo	https://artifactory.mycompany.com/artifactory/virtual-helm-charts
```
Push to the local repo
```
helm push-artifactory hello-chart-0.1.0.tgz my-local-repo --username XXX --password XXX
Pushing hello-chart-0.1.0.tgz to https://artifactory.mycompany.com/artifactory/helm-charts/hello-chart/hello-chart-0.1.0.tgz...
Done.
Reindex helm repository infeng-helm-charts...
Reindex of helm repo infeng-helm-charts was scheduled to run.
```
pull/install the chart using virtual repo
```
helm pull my-virtual-repo/hello-chart
```

**Comment by belitre** [comment]
Hi @richardwhiuk 

Looks like you are using artifactory for your Helm repo, if you are using artifactory then this has nothing to do with helm. 

As @ehernandez-xk commented before this is related with how artifactory manages the helm repositories (local and virtual). If you want to pull charts from artifactory you need to add the virtual repo, the local one won't work, you can read more about this here: https://www.jfrog.com/confluence/display/RTF/Helm+Chart+Repositories

And well, if you want to push you need to push the charts to the local repo, the virtual won''t work for push. I have a plugin to do this using helm https://github.com/belitre/helm-push-artifactory-plugin

:)

**Comment by bacongobbler** [comment]
Thanks everyone for your input and support getting to the bottom of this! Looks like this can now be closed given the amount of in-depth answers provided here. There doesn't appear to be anything on our end; looks like it's a point of confusion on how artifactory local and virtual repositories work with Helm, and these are documented over on their site. Thanks @belitre and @ehernandez-xk for chiming in!

**Comment by kirankumar77** [comment]
I am using helm 3 and i am able to add any repo with  in  the helm container manually but when try to add same repo from Jenkinsfile through Jenkins  Pipeline getting below error.

Below both commands are not working from Jenkinsfile.

helm repo add elastic https://helm.elastic.co 

helm repo add stable https://charts.ost.ai --debug
Error: looks like "https://charts.ost.ai" is not a valid chart repository or cannot be reached: open /.cache/helm/repository/stable-index.yaml: no such file or directory
helm.go:94: [debug] open /.cache/helm/repository/stable-index.yaml: no such file or directory
looks like "https://charts.ost.ai" is not a valid chart repository or cannot be reached
main.(*repoAddOptions).run
	/home/circleci/helm.sh/helm/cmd/helm/repo_add.go:142
main.newRepoAddCmd.func1
	/home/circleci/helm.sh/helm/cmd/helm/repo_add.go:71
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:93
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1373
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
