### ISSUE TITLE
refactor: consolidate the --debug and -v flags together

### ISSUE THREAD

**Issue by bacongobbler** [helm/helm#6844]
A use case was described in https://github.com/helm/helm/issues/6618.

"`helm --debug` is too chatty for me. I'd like to see something more human-readable."

-v is currently constrained to the Kubernetes client's chattiness, where `helm -v 10` will dump raw HTTP request methods, payloads, responses, etc. There may be a way where we can tie into this flag such that `helm --debug` is equivalent to a `helm -v 5`. Users could then use `helm -v 1` for slightly more chatty messages than the current `helm --debug` flag.

**Comment by shubhambhattar** [comment]
How to use `-v` flag? Is it documented anywhere? I am just trying with values from `1` to `10`. Or I can't even figure out if higher numbers are more verbose of the range of numbers which it'll accept?

**Comment by marckhouzam** [comment]
@shubhambhattar I believe level 10 will print the most output.

The `-v` flag is currently only used to increase debug printout when helm talks to kubernetes.  So if you want to see it in action you can try something like `helm list --all-namespaces -v 10`
