### ISSUE TITLE
Helm - get the exact commandline/config used to deploy given existing deployment

### ISSUE THREAD

**Issue by lukaszgryglicki** [helm/helm#6846]
Output of `helm version`:
```version.BuildInfo{Version:"v3.0.0-beta.3", GitCommit:"5cb923eecbe80d1ad76399aee234717c11931d9a", GitTreeState:"clean", GoVersion:"go1.12.9"}```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```Bare metal packet.net server - 4 nodes```

Hi is it possible to retrieve the exact command line used to deploy existing deployment? I have a complex helm chart that allows deploying it via customizing command-line options and `values.yaml` file. The final result is the same chart deployed multiple times and now I want to delete one of the deployments, but I don't know which one exactly should I delete, being able to see each deployment command line will be extremely helpful.

**Comment by lukaszgryglicki** [comment]
At least I know how to delete failed deployment (which attempted to create objects that already exist):
```
k delete secret -n ns-name helm-deployment-name.v1
```
Deleting it via `helm delete` deletes objects that were failed to create when deploying via `helm install`, so a sequence of failed `helm install` and then `helm delete` of that failed install, actually can delete objects created elsewhere :-/

**Comment by bacongobbler** [comment]
This is not currently possible. An "install receipt" stored in your local helm data directory might be a good way to handle this, however. I know Homebrew retains an install receipt when you install a package.

**Comment by lukaszgryglicki** [comment]
OK, thanks, I was searching a lot of time and wasn't able to find that. Thanks for confirmation.

**Comment by lukaszgryglicki** [comment]
Hi, is it possible to see the exact helm command used for install in current Helm 3.x (non-beta)? Just asking again after half of the year passed...

**Comment by bacongobbler** [comment]
No, but feel free to submit contributions! We would happily welcome a patch like this.

**Comment by lukaszgryglicki** [comment]
Actually, I can work on this, but where do you think I should put command line info? Some config map?

**Comment by bacongobbler** [comment]
https://github.com/helm/helm/issues/6846#issuecomment-548243928

**Comment by lukaszgryglicki** [comment]
So I don't have any install receipts stored in `~/.helm/` so basically don't know where should I put installation details.
I'm thinking about something like this:
- I have chart name [here](https://github.com/helm/helm/blob/master/cmd/helm/install.go#L165)
- If everything is OK then chart gets installed [here](https://github.com/helm/helm/blob/master/cmd/helm/install.go#L224) (correct me if I'm wrong)
- I can add defer statement one line before this installation and that defer would just output command line in some file (but which file - my blind shot would be something like `~/.helm/installed.yaml` and the file would contain a mapping from release-name to command line)
- Actually, this would be stored only on the machine where I run `helm install/upgrade` ... this is why I've originally asked about where should I put this data, I was thinking that storing this in Kubernetes - together with the helm chart being deployed is a better idea
- Finally, when I have that data stored *somewhere* I should add a helm subcommand to see given release command line, something like `helm describe-release release-name` or similar.

Does it make sense?
