### ISSUE TITLE
Question - How to update the install order?

### ISSUE THREAD

**Issue by vikas027** [helm/helm#6851]
## Environment
Output of `helm version`:
```
root@d91cfc147be4:/data# helm version 
Client: &version.Version{SemVer:"v2.15.2", GitCommit:"8dce272473e5f2a7bf58ce79bb5c3691db54c96b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.2", GitCommit:"8dce272473e5f2a7bf58ce79bb5c3691db54c96b", GitTreeState:"clean"}
root@d91cfc147be4:/data# 
```
Output of `kubectl version`:

```
root@d91cfc147be4:/data# kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-eks-5047ed", GitCommit:"5047edce664593832e9b889e447ac75ab104f527", GitTreeState:"clean", BuildDate:"2019-08-21T22:32:40Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
root@d91cfc147be4:/data#
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): EKS

## Problem
I have some custom resources (mainly for secrets) which needs to be present before other resources. I can see the install and uninstall order hardlined in the code [here](https://github.com/helm/helm/blob/release-2.15/pkg/tiller/kind_sorter.go#L29). Is there a way to add another `Kind` here through some arguments?

## Related
#5381
#4199

**Comment by bacongobbler** [comment]
This is not currently possible, though we'd be interested in hearing proposals on how users could influence the kind sorter.

**Comment by vikas027** [comment]
I have added my custom `Kind` in the code and recompiled helm, it seems to be working fine. :)

**Comment by tomcruise81** [comment]
Here's a proposal:

1. Create a new command - something like `helm config` or `helm global config`
    1. Include sub-commands - something like `helm config order install` and `helm config order uninstall`
    2. Allow for a YAML configuration format that as an MVP includes (one for `install` & one for `uninstall`, or a combination `orders` file):
        1. An ordered list of `kind` entries
        2. Allowance for each entry to include a list of `apiVersions`, with a sane default
2. Once the new command establishes order, the YAML configuration format could be extended to include:
    1. `completion` for specific `kind` entries
    2. `completion` could be some sort of templated format, with the intent being:
        1. For `install`s and `uninstall`s, completion could be the manifest's status field value that indicates the manifest is fully available/no longer available respectively
    3. For `uninstall`s, some other functionality may be necessary to convey _how_ to uninstall - i.e. for Deployments, `replicas` should be set to 0...

Granted, the new commands could be sub-commands of `helm install` and `helm uninstall`. But I tried to keep them separated to alleviate any concerns for colliding with existing users.

The hope is that externalizing some of this logic into config files/templating might 

- Facilitate:
    - Openshift manifest types
    - Custom Resources (#4578)
    - etc - (#5642, #5916)
- Ease the need for:
    - #3635 
- Enable:
    - Better `-wait` functionality (i.e. to include other manifest types, like Openshift DeploymentConfig)
    - `uninstall -wait` functionality (#5156, #2378)

**Comment by bacongobbler** [comment]
When we look at use cases for modifying the kind sorter, we're usually talking about these for a specific chart's use case. In most cases I have heard that [Application Distributors](https://github.com/helm/community/blob/master/user-profiles.md) want control over how their resources are handled. The users usually do not care as long as the chart is installed correctly.

If I'm understanding your proposal correctly, most of the responsibility is being laid onto the Application Operator through how they "configure" Helm's sort order through commands and confiuguration. If I'm building a chart for someone else (as shown in @vikas027's previous example), how would I inform the user how to determine the install order? Wouldn't we want this "configuration" as part of the chart itself without any user interaction?

**Comment by tomcruise81** [comment]
So my proposal is to provide this information as a global config similar to how the kind sorter is handled now - but allowing for it to be overridden based on the environment someone operates within. i.e. It'd be configurable by the Application Operator.

However, there's no reason that the presence of a new config file type in a chart repo (provided by the Application Distributor) couldn't take precedence over the global values. 

However, if your take is that it makes more sense for it to be at the chart level like in #3635, then so be it. The challenge there is that while that covers sort order, it doesn't encompass the need for per-Kind wait/progress definitions distinct from how they're handed in https://github.com/helm/helm/blob/master/pkg/kube/wait.go. Since the two go hand-in-hand (the list/order of kinds and install/uninstall status/progress for each kind), I was trying to devise an approach that covered both.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

**Comment by tariq1890** [comment]
@bacongobbler Can we re-open this? This is something we'd really like. I understand that this list depends on the GA of a resource. But we use `MutatingWebhookConfigurations` heavily and it definitely needs to be factored in.  A feature where we would specify a customised install order would be great.
