### ISSUE TITLE
[Question]: how to check if value in a list and throw error if not?

### ISSUE THREAD

**Issue by sincerywaing** [helm/helm#6856]
say I have a value `version` defined, there are three possible values `1` `2` `3`

so I can use something like - 

`{{ if and Values.version (or (eq .Values.version "2") (eq .Values.version "1") (eq .Values.version "3") ) }}`
do something

{{ else }}
print error: your version is not supported!!!

**Comment by bacongobbler** [comment]
See http://masterminds.github.io/sprig/reflection.html and http://masterminds.github.io/sprig/lists.html. `has` and `kindIs` should help you in this regard.
