### ISSUE TITLE
Helm Python Client

### ISSUE THREAD

**Issue by ashpreetbedi** [helm/helm#6858]
Hi,

Are there any plans for an officially supported python client? I absolutely love using helm charts, but would like to deploy them through python scripts/code. There are 2 forks of pyHelm, [here](https://github.com/andriisoldatenko/pyhelm) and [here](https://github.com/flaper87/pyhelm) but wanted to check if there are any plans for an officially supported python client.

Thank you!

**Comment by bacongobbler** [comment]
The Helm org is set up to host other subprojects like chartmuseum and monocular. Should the pyhelm project be interested in moving it under the Helm org as an official project, it's certainly something the Helm org maintainers would be open to. There are no plans to write a python client of our own.

It's important to keep in mind that the Helm project is an open source project, and that carries a different level of availability than a company-backed project.

**Comment by bacongobbler** [comment]
Closing as answered. Please feel free to request this issue to be re-opened if you have further questions. Thanks!

**Comment by ashpreetbedi** [comment]
Thank you for the quick and thorough response @bacongobbler, knowing that there are no plans for a python client provides clarity for what I'm working on!

**Comment by davi5e** [comment]
As a side question, I also need to use Helm to install charts in a Python client.

Another way I'm trying to do this is to make a system call and be done with it (if it'd work). The thing is, I can't make the Helm Client ([v2.16.1](https://get.helm.sh/helm-v2.16.1-linux-amd64.tar.gz)) talk to Tiller...

Whenever I use a `python:3.6-alpine` container and use `helm <options> --tls --host tiller-deploy.kube-system:44134`, I get a broken pipe message over in Tiller's Pod logs...

Have anyone tried this approach this? Is there some TLS dependencies I'm missing?

**Comment by hickeyma** [comment]
@davi5e If you use the Helm client (`helm`), what commands are you running  and what is the output/error?

**Comment by davi5e** [comment]
In my current configuration, Tiller is installed in a namespace called `tiller`:
```bash
$ kubectl get svc -n tiller --field-selector metadata.name=tiller-deploy
NAME            TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)     AGE
tiller-deploy   ClusterIP   10.1.13.24   <none>        44134/TCP   23m
```

And I can connect from my machine.
```bash
$ helm version --tls --tls-ca-cert ca.pem --tls-cert cert.pem --tls-key key.pem --tiller-namespace=tiller
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.0", GitCommit:"e13bc94621d4ef666270cfbe734aaabf342a49bb", GitTreeState:"clean"}
```

Now if I do the same from a container, I get a timeout...

```bash
# From session 1
kubectl run --restart=Never --image=python:3.6-alpine python -i --tty -- /bin/sh

# From another session
for CERT in ca.pem cert.pem key.pem ; do kubectl cp $CERT python:/tmp/$CERT ; done

# From inside the container back in session 1
wget --quiet https://get.helm.sh/helm-v2.16.1-linux-amd64.tar.gz -O /tmp/helm-v2.16.1-linux-amd64.tar.gz
tar -xzf /tmp/helm-v2.16.1-linux-amd64.tar.gz -C /tmp \
mv /tmp/linux-amd64/helm /tmp/linux-amd64/tiller /usr/local/bin \
chmod +x /usr/local/bin/helm /usr/local/bin/tiller
helm init --client-only

# Now the command that fails...
$ helm version \
    --tls \
    --tls-ca-cert /tmp/ca.pem \
    --tls-cert /tmp/cert.pem \
    --tls-key /tmp/key.pem \
    --host tiller-deploy.tiller:44134 \
    --tiller-connection-timeout 15 \
    --debug
```

And this is the output
```
[debug] Host="", Key="/tmp/key.pem", Cert="/tmp/cert.pem", CA="/tmp/ca.pem"

Kubernetes: &version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-gke.17", GitCommit:"188432a69210ca32cafded81b4dd1c063720cac0", GitTreeState:"clean", BuildDate:"2019-11-13T20:47:11Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
[debug] context deadline exceeded
Error: cannot connect to Tiller
```

So I'm pretty lost. How would I start to debug and/or trace the connection to check what's wrong?

**Comment by davi5e** [comment]
Well, I made it work... Turns out I was missing `kubectl`. Good news is `kubectl` don't need any configuration if it's running inside a Pod.

I also needed to update the Pod's ServiceAccount to enable [port forwarding to another namespace](https://medium.com/@ManagedKube/kubernetes-rbac-port-forward-4c7eb3951e28) (a ClusterRole) and Helm now works, hence the system call from Python is viable.
