### ISSUE TITLE
Allow a Secret template to include an encrypted binary file and seemlessly decrypt it using sops

### ISSUE THREAD

**Issue by smeierhofer** [helm/helm#6859]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:39:02Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS

The problem is that I have an existing app that reads its configuration settings from many text files. I have experimented with a ConfigMap and a Secret and have found it convenient to place all the configuration files into one folder named "config" and then use code such as ` {{- (tpl (.Files.Glob "config/*").AsConfig . ) | nindent 2 }}` to include all those files in the ConfigMap or Secret. But some of the properties are of a sensitive nature and so they can't live as clear text on disk in the "config" folder.

I've looked at the Helm Secrets plugin and that works very well to store sensitive data in encrypted form in yaml files and then include the data in a Secret. The problem is that this gets cumbersome when dealing with any number of sensitive data or if an entire file contains sensitive application settings or if the file is binary, such as a PKCS 12 keystore.

What I'd like is a function that I can use in the helm template file to use sops to decrypt the file similar to how the b64enc function can do base64 encoding. To deal with several encrypted files all at once it would be nice to support a function with Files.Glob so that can store all sensitive files in a folder named "sensitive" and use code such as this to decrypt them all and include them in the ConfigMap or Secret ` {{- (tpl (.Files.Glob "sensitive/*").Decrypt.AsConfig . ) | nindent 2 }}`.

**Comment by bacongobbler** [comment]
Perhaps this may be well-suited as a feature request for [sprig](https://github.com/Masterminds/sprig). sprig provides functions like `sha256sum` and `decryptAES` to the template language.
