### ISSUE TITLE
Helm still (again) converts integer values into scientific notation

### ISSUE THREAD

**Issue by mltsy** [helm/helm#6867]
This problem has been documented many times before in #6431, #3001 and #1707, but here's a refresher:

Something like `helm install --set tag=20161216` ends up in scientific notation in the template, because `{{ typeOf .Value.tag }}` yields `float64`.

This was fixed at least once (#6010) but that was reverted recently (#6758), due to a new bug caused by the fix.  A new fix is needed.

**Comment by bacongobbler** [comment]
I've gone ahead and re-opened https://github.com/helm/helm/issues/1707.
