### ISSUE TITLE
No repository definition error from dependency build but not update

### ISSUE THREAD

**Issue by mjgallag** [helm/helm#6870]
`helm dependency build` returns 
`Error: no repository definition for https://kubernetes-charts.storage.googleapis.com, https://kubernetes-charts.storage.googleapis.com. Please add the missing repos via 'helm repo add'` but `helm dependency update` succeeds.

Is this expected?

Output of `helm version`:
`version.BuildInfo{Version:"v3.0.0-rc.2", GitCommit:"82ea5aa774661cc6557cb57293571d06f94aff0c", GitTreeState:"clean", GoVersion:"go1.13.3"}`
Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:42:50Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}`
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
`minikube version: v1.5.2
commit: 792dbf92a1de583fcee76f8791cff12e0c9440ad`

**Comment by bacongobbler** [comment]
this is an unexpected error, but this was fixed for `helm dependency update` in https://github.com/helm/helm/pull/6488. Perhaps a similar fix is required for `helm dependency build`.

**Comment by jdamour98** [comment]
I replicated it consistently, use this repo to test: https://github.com/jdamour98/helm3-dependecy-bug

**Comment by maxbrunet** [comment]
Connecting the dots... Looks like this issue was reported again in #8036 and has a proposed fix #7242.

**Comment by bacongobbler** [comment]
Thanks. Closing in favour of #8036 so we can track this issue from one ticket.
