### ISSUE TITLE
Add --render-subchart-notes flag to helm get notes

### ISSUE THREAD

**Issue by mjgallag** [helm/helm#6872]
It would be useful for `helm get notes` to support the `--render-subchart-notes` flag, see https://github.com/helm/helm/commit/26dacf84aabe0e6093ad3f05c0341df9145fb696.

Output of `helm version`:
`version.BuildInfo{Version:"v3.0.0-rc.2", GitCommit:"82ea5aa774661cc6557cb57293571d06f94aff0c", GitTreeState:"clean", GoVersion:"go1.13.3"}`
Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:42:50Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}`
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
`minikube version: v1.5.2
commit: 792dbf92a1de583fcee76f8791cff12e0c9440ad`

**Comment by hickeyma** [comment]
@mjgallag What would be the use case for such a flag with `helm get`? At that stage the chart is installed and you are retrieving the details.

**Comment by mjgallag** [comment]
@hickeyma in my case I was developing a chart and added a `mongodb` subchart. I didn't get the `monogdb` subchart notes when I called `helm upgrade`. I discovered I could add the `--render-subchart-notes` flag to either `install` or `upgrade` to get them but at this point the upgrade was complete. I then found I could call `helm get notes` to get my charts notes but unfortunately this didn't allow me to get the mongodb subchart notes I was looking for, thus this feature request. I worked around this by running `helm upgrade` again. Perhaps I could have avoided the actual upgrade with `--dry-run` but that still feels like a workaround. I'm new to this and just wanted to know how to connect to the `mongodb` instance I just added to my chart :) It seems strange you'd be able to optionally get subchart notes on install/upgrade but only chart notes afterward, thus my feature request.

**Comment by hickeyma** [comment]
@mjgallag While looking at this, I created a scaffold chart and then added a scaffold sub-chart in the `chats` folder. When I did an install with `--dry-run` it did not show the notes of the sub-chart. It did not show it when I did `install` or `upgrade` without the flag either.  

Could you check again that the notes for sub-chart were showing for an `install` or `upgrade`?  I am wondering if they are being rendered at all and would therefore not be stored. That would explain not showing for `helm get notes`.

**Comment by hickeyma** [comment]
@mjgallag When you set `--render-subchart-notes` flag, the sub-chart notes files are rendered. If they are rendered then they will be persisted. Hence, when you do a `helm get notes`, the sub-chart notes will be returned. The issue here is that if you don't set the flag then the sub-charts will not be rendered and therefore are not retrievable as a consequence.

Sorry to say but it is working as expected.

**Comment by mjgallag** [comment]
@hickeyma ah ha, thank you for the explanation!
