### ISSUE TITLE
Helm 3 man pages

### ISSUE THREAD

**Issue by stanislaw55** [helm/helm#6877]
Hello Helm community

In documentation for Helm 2, there's information about building man pages by executing `make docs`.

In master branch (which is AFAIK place for helm v3 development) target `docs` is not present in Makefile (and hence scripts for used to generate man pages).

Is it planned for Helm 3 stable release to have man pages?

**Comment by bacongobbler** [comment]
The manual pages for a given Helm release can be generated locally using `helm docs --type man`. The auto-generated manual pages were removed from the documentation in Helm 3 to ease the development process.

Hope this helps.

**Comment by stanislaw55** [comment]
Thank you @bacongobbler for quick answer.
This answers my question
