### ISSUE TITLE
helm v3.0.0-rc.2 installation error

### ISSUE THREAD

**Issue by get2arun** [helm/helm#6878]
Output of `helm version`:
root@desktop-e470:~/k8s/linux-arm# helm version
ERRO[0000] failure getting variant                       error="getCPUInfo for pattern: Cpu architecture: not found"
version.BuildInfo{Version:"v3.0.0-rc.2", GitCommit:"82ea5aa774661cc6557cb57293571d06f94aff0c", GitTreeState:"clean", GoVersion:"go1.13.3"}

Output of `kubectl version`:
root@desktop-e470:~/k8s/linux-arm# kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
kubernetes is hosted using PKS cluster.

**Comment by get2arun** [comment]
The OS and release information.
cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"

**Comment by get2arun** [comment]
please close this issue, I have downloaded the wrong package, after downloading amd64 version, it working. thanks.

**Comment by karuppiah7890** [comment]
You can close the issue yourself as you are the creator :)

**Comment by hickeyma** [comment]
Closing as the wrong binary used.
