### ISSUE TITLE
Helm init --client-only seems to ignore --history-max

### ISSUE THREAD

**Issue by bmaupin** [helm/helm#6880]
Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-10-10T16:38:01Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-09-12T23:41:09Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
OpenShift 3.11

I'm using GitLab's Auto DevOps to deploy applications to OpenShift. Auto DevOps uses local tiller on the CI runners:

```
export HELM_HOST="localhost:44134"
nohup tiller -listen ${HELM_HOST} -alsologtostderr >/dev/null 2>&1 &
```

Then it runs `helm init --client-only` followed by `helm upgrade --install` to do the deployment.

The problem is that Helm creates a new ConfigMap for each deployment (release) we do. So I was excited to find out about [`helm init --history-max`](https://github.com/helm/helm/pull/2636) and I updated the command to `helm init --client-only --history-max 1`.

However, it doesn't seem to have any effect. Each invocation of `helm upgrade --install` creates another ConfigMap with a new version:

```
$ kubectl get configmaps -l OWNER=TILLER
NAME                                                   DATA      AGE
mysql-appdev-ci-pipeline-review-39-mysql-c-wwnq41.v1   1         27m
mysql-appdev-ci-pipeline-review-39-mysql-c-wwnq41.v2   1         25m
mysql-appdev-ci-pipeline-review-39-mysql-c-wwnq41.v3   1         3m
```

My only guess is it's because we're using `--client-only`. Would that make a difference?

Thanks!

**Comment by bacongobbler** [comment]
`--history-max` modifies the server-side component (Tiller) to retain a certain number of releases, so it makes sense that `--client-only` would ignore that flag as it disables the installation of Tiller.

**Comment by bmaupin** [comment]
That makes sense. Is there another way I can disable the creation of all of these ConfigMaps? Or am I going to have to come up with a way to clean them up manually?

Aside from the wasted resources, our sysadmins have implemented ConfigMap quotas that are quickly being used up.

Thanks!

**Comment by bacongobbler** [comment]
You can `kubectl edit` your tiller deployment to add in the environment variable that `--history-max` would've added for you. Use the output of `helm init --history-max=10 --debug` as a guide.

**Comment by bmaupin** [comment]
I'll check that out. Thanks!

**Comment by bacongobbler** [comment]
closing as answered.

**Comment by bmaupin** [comment]
Setting `export TILLER_HISTORY_MAX=1` before running tiller locally seems to have worked. It seems to actually keep `TILLER_HISTORY_MAX` + 1 ConfigMaps, but it's still much better than unlimited:

```
$ kubectl get configmaps -l OWNER=TILLER
NAME                                                   DATA      AGE
mysql-appdev-ci-pipeline-review-39-mysql-c-wwnq41.v6   1         9m
mysql-appdev-ci-pipeline-review-39-mysql-c-wwnq41.v7   1         1m
```

Thanks again.
