### ISSUE TITLE
Helm v3.0.0-rc.2: Error when install prometheus-operator (missing required field caBundle)

### ISSUE THREAD

**Issue by bood** [helm/helm#6883]
prometheus-operator install with the lastest helm version report following `missing required field "caBundle"` error (I have to use the China version of chart but should be similar):
```bash
bood:k8s$ helm inspect chart apphub/prometheus-operator
apiVersion: v1
appVersion: 0.32.0
bood:k8s$  helm install --namespace monitoring -f prometheus-config.yaml prometheus-operator apphub/prometheus-operator --set prometheusOperator.createCustomResource=false --version 7.1.1
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(MutatingWebhookConfiguration.webhooks[0].clientConfig): missing required field "caBundle" in io.k8s.api.admissionregistration.v1beta1.WebhookClientConfig
```

I tried other helm versions too, the first error version is beta.5.

It may be related to those validation changed in beta.5. I'm not sure this is a bug of helm or bug of the chart though. Looks like the `caBundle` should be auto-generated.

I have to disable admissionWebhooks to install prometheus-operator for now:

```yaml
prometheusOperator:
## Disable admission webhook as helm-v3-beta.5+ report caBundle error
  admissionWebhooks:
    enabled: false
```

Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.0-rc.2", GitCommit:"82ea5aa774661cc6557cb57293571d06f94aff0c", GitTreeState:"clean", GoVersion:"go1.13.3"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-aliyun.1", GitCommit:"01a904e", GitTreeState:"", BuildDate:"2019-02-28T13:54:16Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Aliyun

**Comment by bacongobbler** [comment]
at first glance this appears to be related to #6130, where the admissions webhook requires the CRDs to be installed prior to being installed. The prometheus-operator chart isn't compatible with Helm 3 at this time.

**Comment by bood** [comment]
@bacongobbler Yes, I'm aware of the crd-install hook issue. I forget to mention that I installed prometheus-operator with crd disabled `prometheusOperator.createCustomResource=false` (question edited). I was able to install it successfully with this flag using helm version <= 3.0.0-beta.4. What is new here is the `caBundle` related error.

**Comment by bacongobbler** [comment]
Prior to recent revisions, OpenAPI schema validation was disabled. This was fixed in beta.4. The error is indicative that the rendered resource doesn't comply with the MutatingWebhookConfiguration schema.

**Comment by bacongobbler** [comment]
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/#webhookclientconfig-v1beta1-admissionregistration-k8s-io

**Comment by vsliouniaev** [comment]
The caBundle field being required seems strange, since the Kubernetes docs say it can be omitted

> Here is an example of a mutating webhook configured to call a URL (and expects the TLS certificate to be verified using system trust roots, so does not specify a caBundle)
https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#url

**Comment by bacongobbler** [comment]
Kubernetes 1.12.6 marked the `caBundle` field as a required field. This was fixed in later revisions.

You can check the OpenAPI spec for 1.12.6 yourself here: https://raw.githubusercontent.com/kubernetes/kubernetes/v1.12.6/api/openapi-spec/swagger.json. CTRL + F for "WebhookClientConfig". `caBundle` is under the "required" list for that release.

Mystery solved.
