### ISSUE TITLE
Make namespace accessible from other package

### ISSUE THREAD

**Issue by Mikedu1988** [helm/helm#6884]
We have a micro-service using helm-v3 package.
Recently we upgraded the pkg from dev-v3 branch to v3.0.0.0-rc.2, then we found that "Namespace" of env setting changed to a function and the attribute is not accessible any more other than AddFlags function. But we are not a cli tool, we don't want to construct a flagset when we serving requests.

Is it possible to add a SetNamespace function for integration purpose, after all, not everyone is capable of using helm cli, they need web pages with one click deploy experience. Not able to set "Namespace" other than a cli flag is very inconvenience.

code of pkg/cli/environment.go changed from
`
type EnvSettings struct {
	Namespace string
...
}
`

to

`
type EnvSettings struct {
	namespace string
...
}
`

**Comment by bacongobbler** [comment]
Feel free to submit a PR to expose that field and add tests around how to interact with that field!

**Comment by Mikedu1988** [comment]
I had modified the code on my own fork, but our own project is under intensive development, I'll submit the PR as soon as I get my work at hand done.
