### ISSUE TITLE
helm upgrade fail

### ISSUE THREAD

**Issue by zffocussss** [helm/helm#6886]
Output of `helm version`:
Client: &version.Version{SemVer:"v2.15.2", GitCommit:"8dce272473e5f2a7bf58ce79bb5c3691db54c96b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.2", GitCommit:"8dce272473e5f2a7bf58ce79bb5c3691db54c96b", GitTreeState:"clean"}
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS

I am using helm to deploy on AKS.deployment has affinity/anti-affinity.
when I use helm upgrade.it failed while the new pods created by helm upgrade keep pending.
nodes did not match pod affinity/anti-affinity.I want to know how does helm upgrade work?
first add new pods,then remove old pods? what is the sequence?

**Comment by bacongobbler** [comment]
Helm provides a patch to the API server with what's changed between the two chart releases. It's up to Kubernetes to determine how the update is rolled out according to the workload's specification.

https://github.com/helm/helm/blob/bed80a57f06717061ade3993b6f8224eedac488c/pkg/kube/client.go#L730-L733

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!
