### ISSUE TITLE
Helm v3.0.0-rc2: Package does not include requirements.yaml file

### ISSUE THREAD

**Issue by mcavoyk** [helm/helm#6887]
I'm not sure if this is expected behavior for helm3, but helm3's package command no longer includes the "requirements.yaml" file when packaging a chart. Noticed this as Harbor's helm chart UI expects the requirements.yaml to exist to properly list dependencies.

Helm v3.0.0-rc2
```
helm3 package <chart> 
tar -ztvf <chart>.tgz

<chart>/Chart.yaml
<chart>/values.yaml
<chart>/README.md
<chart>/templates/...
<chart>/charts/...
```

Helm v2.15.2
```
helm2 package <chart> 
tar -ztvf <chart>.tgz

<chart>/Chart.yaml
<chart>/values.yaml
<chart>/README.md
<chart>/Chart.lock
<chart>/requirements.lock
<chart>/requirements.yaml
<chart>/templates/...
<chart>/charts/...
```

Output of `helm version`:
version.BuildInfo{Version:"v3.0.0-rc.2", GitCommit:"82ea5aa774661cc6557cb57293571d06f94aff0c", GitTreeState:"clean", GoVersion:"go1.13.3"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:43:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-eks-5047ed", GitCommit:"5047edce664593832e9b889e447ac75ab104f527", GitTreeState:"clean", BuildDate:"2019-08-21T22:32:40Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"

**Comment by bacongobbler** [comment]
As part of `helm package`, Helm 3 converts the package to the new dependency system.

You can observe the behaviour via the following:

```
><> ./bin/helm fetch stable/wordpress --untar
><> cat wordpress/requirements.yaml 
dependencies:
- name: mariadb
  version: 6.x.x
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: mariadb.enabled
  tags:
    - wordpress-database
><> helm package ./wordpress/
Successfully packaged chart and saved it to: /home/bacongobbler/code/go/src/helm.sh/helm/wordpress-7.6.0.tgz
><> rm -rf wordpress
><> tar xzf wordpress-7.6.0.tgz 
><> cat wordpress/Chart.yaml 
apiVersion: v1
appVersion: 5.2.4
dependencies:
- condition: mariadb.enabled
  name: mariadb
  repository: https://kubernetes-charts.storage.googleapis.com/
  tags:
  - wordpress-database
  version: 6.x.x
description: Web publishing platform for building blogs and websites.
home: http://www.wordpress.com/
icon: https://bitnami.com/assets/stacks/wordpress/img/wordpress-stack-220x234.png
keywords:
- wordpress
- cms
- blog
- http
- web
- application
- php
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: wordpress
sources:
- https://github.com/bitnami/bitnami-docker-wordpress
version: 7.6.0
```

Notice how the `dependencies` field was migrated to Chart.yaml. The same goes for `requirements.lock`; it's converted to the new Chart.lock lockfile.

Unmarking this as a bug. This is a feature!

Hope this helps.

**Comment by bacongobbler** [comment]
More info here on the change: https://helm.sh/blog/helm-3-preview-pt5/

**Comment by mcavoyk** [comment]
Yeah, I wasn't sure if it was a bug or feature. Thanks for explaining 👍 .
