### ISSUE TITLE
v3: Proposal: helm env to show XDG info

### ISSUE THREAD

**Issue by marckhouzam** [helm/helm#6890]
With the use of XDG directories for helm configuration, it has become difficult to find and automate where helm data can be found.  See https://github.com/helm/helm-www/issues/336 for a concrete example where I believe the user may find themselves at a loss.

**Point 1:**
I suggest extending `helm env` to provide the location of the current XDG paths in a machine consumable fashion.  Concretely I propose to add a `--show` (or some other name) flag to `helm env` like so:
```
$ helm env --show <cache|config|data>
```
which would print the corresponding path.
On Linux for example:
```
$ helm env --show data
 /home/marckhouzam/.local/share/helm
```
This would allow to tell users to do such things as:
```
cp ./myStarter $(helm env --show data)/starters
```
which to my knowledge has no other good alternative right now.

**Point 2:**
We could also have `helm env` return all 3 XDG paths in its output like so:
```
$ helm3 env
HELM_NAMESPACE="default"
[...]
XDG_CACHE_HOME="/Users/marckhouzam/Library/Caches"
XDG_CONFIG_HOME="/Users/marckhouzam/Library/Preferences"
XDG_DATA_HOME="/Users/marckhouzam/Library"
```
Note that just to be able to write the proper paths above I had to run `helm -h` and look at the default XDG locations.  This is another example that shows the issue that this proposal aims to address.

I can work on a PR if maintainers agree they find value.

**Comment by marckhouzam** [comment]
Thinking about this some more, I believe that plugins must also suffer from this 'limitation'.  How would a plugin know where to find helm data if the XDG variables are not set in the shell? I guess it would need to figure out the default values itself, based on the current OS.  I think we should improve that.

I see that listing the XDG paths in `helm env` was actually part of the original `helm env` PR: https://github.com/helm/helm/pull/6244 (/cc @waveywaves )

However, it was purposely removed by https://github.com/helm/helm/pull/6362.
From the title of the PR, it makes sense to me that we don't want to "override users xdg directories".  However, I think it is because there was a bug in how 'helm env' would set these variables originally, where it would include the '/helm' suffix in the XDG vars, which is not correct.

I think if we strip that suffix, it would be safe to set the XDG vars in `helm env`.
 /cc @adamreese

**Comment by bacongobbler** [comment]
> Thinking about this some more, I believe that plugins must also suffer from this 'limitation'. How would a plugin know where to find helm data if the XDG variables are not set in the shell?

If the environment variable is not present, then they can just look up the default XDG filepaths as per the spec. `pkg/helmpath` can help in this regard, assuming the plugin is written in Go.

**Comment by marckhouzam** [comment]
> > Thinking about this some more, I believe that plugins must also suffer from this 'limitation'. How would a plugin know where to find helm data if the XDG variables are not set in the shell?
> 
> If the environment variable is not present, then they can just look up the default XDG filepaths as per the spec. `pkg/helmpath` can help in this regard, assuming the plugin is written in Go.

You're right, so they are not stuck.  Plugins in bash would need to hard-coded these paths for now.

**Comment by jonasrutishauser** [comment]
> Thinking about this some more, I believe that plugins must also suffer from this 'limitation'. How would a plugin know where to find helm data if the XDG variables are not set in the shell?

Plugins will get it from the environment: https://github.com/helm/helm/blob/6a98d1f1d209c7a96a0df250e05070a9932e089f/pkg/cli/environment.go#L98-L100

**Comment by bacongobbler** [comment]
That's just for OCI configuration, and that can be managed separately with the `--registry-config`, `--registry-cache` settings. It doesn't include information about the data, cache or configuration directories which are used by the rest of the system.

**Comment by bacongobbler** [comment]
removing from the 3.1 milestone, as there are still unresolved discussions taking place in #6892

**Comment by bridgetkromhout** [comment]
@marckhouzam is this completely resolved like https://github.com/helm/helm/issues/8635 by https://github.com/helm/helm/pull/8638? Or is there more to be done on this issue?

**Comment by marckhouzam** [comment]
Thanks for bringing this up @bridgetkromhout, I would have forgotten.
This is all resolved nicely.
