### ISSUE TITLE
Question about Docs - Dependency Installation Order

### ISSUE THREAD

**Issue by huskysun** [helm/helm#6895]
The example [here](https://helm.sh/docs/developing_charts/#operational-aspects-of-using-dependencies) shows that the install order of chart `A` and `B` is
```
A-Namespace
B-Namespace
A-StatefulSet
B-ReplicaSet
A-Service
B-Service
```
The doc says this is because they are aggregated and then
> sorted by type followed by name.

However, according to the `InstallOrder` in [kind_sorter.go](https://github.com/helm/helm/blob/master/pkg/releaseutil/kind_sorter.go#L27), `Service` is in front of `ReplicaSet`, which is then in front of `StatefulSet`. So I don't know why it's in the order above, instead of
```
A-Namespace
B-Namespace
A-Service
B-Service
B-ReplicaSet
A-StatefulSet
```
Am I missing anything?

Also btw the link to the `kind_sorter.go` in the doc is not working.

**Comment by bacongobbler** [comment]
thanks for identifying this. This might've changed in later versions but the documentation was not updated to reflect that. Feel like fixing that up?

**Comment by huskysun** [comment]
@bacongobbler Thanks for the reply. Sure I'm willing to do that. Could you give me some pointers on where to fix? And I'm assuming I should follow the `CONTRIBUTING.md` as a guideline for making PRs? I'm new to this repo and also have never contributed to an OSS before, so I need some learning on this. Thank you!

**Comment by bacongobbler** [comment]
closing as inactive.
