### ISSUE TITLE
Tiller creating a lot of logs

### ISSUE THREAD

**Issue by alexanderbuhler** [helm/helm#6898]
Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.16.0", GitCommit:"e13bc94621d4ef666270cfbe734aaabf342a49bb", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.2", GitCommit:"8dce272473e5f2a7bf58ce79bb5c3691db54c96b", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:42:50Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):
Metakube/Openstack

Some time ago I was updating fluentd (just a minor patch), looks like after that the tiller logs went through the roof. But also tiller/helm itself was updated that day (to 2.14.3) – so its hard to pinpoint the exact event.

Anyway, I checked logs before that time and found that no `[kube] ...` log output was captured in elasticsearch. Now, `[kube] ...` is almost all I see, producing ~100k log lines per 30 minutes, so almost 5M per day.

```
  | November 7th 2019, 00:15:35.010 | [kube] 2019/11/06 23:15:33 Doing get for ServiceAccount: "cert-manager"

  | November 7th 2019, 00:15:35.010 | [kube] 2019/11/06 23:15:33 get relation pod of object: cert-manager/ServiceAccount/cert-manager

  | November 7th 2019, 00:15:35.009 | [kube] 2019/11/06 23:15:33 Doing get for ServiceAccount: "cert-manager-cainjector"

  | November 7th 2019, 00:15:35.009 | [kube] 2019/11/06 23:15:33 Doing get for ServiceAccount: "cert-manager-webhook"

  | November 7th 2019, 00:15:35.009 | [kube] 2019/11/06 23:15:33 get relation pod of object: cert-manager/ServiceAccount/cert-manager-webhook

  | November 7th 2019, 00:15:35.008 | [storage] 2019/11/06 23:15:33 getting last revision of "cert-manager"

  | November 7th 2019, 00:15:35.008 | [storage] 2019/11/06 23:15:33 getting release history for "cert-manager"

  | November 7th 2019, 00:15:35.006 | [kube] 2019/11/06 23:15:33 get relation pod of object: istio-system/Deployment/flagger

  | November 7th 2019, 00:15:35.005 | [kube] 2019/11/06 23:15:33 Doing get for Deployment: "flagger"

  | November 7th 2019, 00:15:34.910 | [kube] 2019/11/06 23:15:33 Doing get for ClusterRoleBinding: "flagger"

  | November 7th 2019, 00:15:34.910 | [kube] 2019/11/06 23:15:33 get relation pod of object: /ClusterRoleBinding/flagger

  | November 7th 2019, 00:15:34.910 | [kube] 2019/11/06 23:15:32 get relation pod of object: /ClusterRole/flagger

  | November 7th 2019, 00:15:34.909 | [kube] 2019/11/06 23:15:32 Doing get for CustomResourceDefinition: "canaries.flagger.app"

  | November 7th 2019, 00:15:34.909 | [kube] 2019/11/06 23:15:32 get relation pod of object: /CustomResourceDefinition/canaries.flagger.app

  | November 7th 2019, 00:15:34.909 | [kube] 2019/11/06 23:15:32 Doing get for ClusterRole: "flagger"

  | November 7th 2019, 00:15:34.908 | [kube] 2019/11/06 23:15:32 Doing get for ServiceAccount: "flagger"

  | November 7th 2019, 00:15:34.908 | [kube] 2019/11/06 23:15:32 get relation pod of object: istio-system/ServiceAccount/flagger


```
Do you guys have any hint on what could be the issue? I also didn't find any approach to modify the log output of tiller.

Thanks!

**Comment by bacongobbler** [comment]
Those calls occur when someone initiates a gRPC request to tiller. A user (or a bot) has to invoke the equivalent of a `helm status` or other APIs that rely on fetching live state from the cluster, like a `helm install` or a `helm upgrade`.

https://github.com/helm/helm/blob/0ca95341c19fcaf9cecdf50caef1693568835a84/pkg/kube/client.go#L995

**Comment by alexanderbuhler** [comment]
Thanks, I found the source to be flux helm operator. Suprisingly it wasn't creating these logs a couple weeks back. So there's no way to configure what's being logged by tiller yet? I assume helm 3 "fixes" this since there's no tiller anymore?

**Comment by bridgetkromhout** [comment]
Hi, @alexanderbuhler - as @bacongobbler said, those calls are triggered by gRPC requests to tiller, and you've noted that the flux helm operator was the source.

You are correct that Helm 3 has no Tiller, so it won't have this specific behavior. Additionally, we are in bugfix-only mode for Helm 2. So, we won't be changing this Tiller behavior at this point.

Hopefully the GA of Helm 3 means that you're able to use Helm 3 for your needs: https://helm.sh/docs/topics/v2_v3_migration/. If you have further questions or need help with the migration, please let us know; thanks.
