### ISSUE TITLE
Using null to delete a key sets it if it was not already set

### ISSUE THREAD

**Issue by Nuru** [helm/helm#6900]
Since #2648 the [official way](https://helm.sh/docs/chart_template_guide/#deleting-a-default-key) to delete a key set in the default values.yaml was to set it to `null` in your values.yaml.

I don't know if this is new behavior, but it is now a problem that `null` only deletes the key if it already exists. Otherwise it creates the key.
 
I stumbled on this issue as I was trying to fix a problem with [prometheus-operator](https://github.com/helm/charts/tree/master/stable/prometheus-operator) Chart 8.1.2. Setting
```
kubeScheduler:
  service:
    selector:
      k8s-app: "kube-scheduler"
      component: null
```
results in template output of
```
  selector:
    component: null
    k8s-app: kube-scheduler
```
which unfortunately does not work as it does not match something without a `component` label.

The issue here is that older versions of the chart set a default value of  
```
kubeScheduler:
  service:
    selector:
      component: "kube-scheduler"
```
so I was setting the override with `component: null` as required to delete the key.  My settings with the older chart correctly produced
```
  selector:
    k8s-app: kube-scheduler
```
without a `component` key.

Now, however, the `prometheus-operator` chart has been updated so that `component` isn't a default value, but rather a default template output if nothing is set. This is better chart design as it avoids this confusing need to delete a default key. Unfortunately, it also brings up the inconsistent behavior of `helm` in that `component: null`  deletes a key if it exists, but creates the key if it does not.

Do we need to allow the creation of keys with value `null`? I thought we decided we did not when we decided to allow `null` to delete keys rather than override them. 

At the very least, this is inconsistent behavior that should be documented in the documentation about deleting keys (see link above).

Output of `helm version`: seen in v2.16.0 and v2.14.3

Output of `kubectl version`: v1.13.12

**Comment by bacongobbler** [comment]
What's the recommended course of action here? As far as I understand, `null` is a valid value for YAML/JSON, so if it's explicitly listed in the values, that should be treated as a value.
