### ISSUE TITLE
helm test --logs for all containers in a pod

### ISSUE THREAD

**Issue by tanenbaum** [helm/helm#6902]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.16.0", GitCommit:"e13bc94621d4ef666270cfbe734aaabf342a49bb", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.0", GitCommit:"e13bc94621d4ef666270cfbe734aaabf342a49bb", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-17T17:16:09Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Minikube

It would be great if `helm test --cleanup --logs` printed all container logs in each test pod. Currently this works fine for 1 container in a pod.

Rather than run test images that contain all the tools I need, I often create pods with a couple of containers that orchestrate the tests (e.g. redis-cli + python script + shared volume).

`helm test [release] --cleanup --logs` will error with:
RUNNING: my-test
FAILED: my-test, run `kubectl logs my-test --namespace default` for more info
ERROR: error in opening log stream, got: a container name must be specified for pod my-test, choose one of: [container-0 container-1]

I currently use a shell script as a workaround (can't find source of this anymore) like so:

```
helm_release=$1

helm test $helm_release
status=$?

test_pods=$(helm status $helm_release -o json | jq -r .info.status.last_test_suite_run.results[].name)
namespace=$(helm status $helm_release -o json | jq -r .namespace)

for test_pod in $test_pods; do
  echo "Test Pod: $test_pod"
  echo "============"
  echo ""
  kubectl -n $namespace logs --all-containers $test_pod
  kubectl -n $namespace delete pod $test_pod
  echo ""
  echo "============"
done

exit $status
```

Notice that I'm running `kubectl logs --all-containers` to ensure I get all the logs from the pod.

**Comment by Motor-taxi-master-rider** [comment]
+1, It will be helperful if we can get logs from multi contianers.

**Comment by jan25** [comment]
https://github.com/wercker/stern also does tail multi pod, container logs

**Comment by dosten** [comment]
Hi, I want to work in this because actually we need it, WDYT it's the best approach?

- add a new `--logs-container / --container` flag
- allow the `--logs` flag to receive an optional value with the name of the container (`--logs=runner`)

**Comment by dudicoco** [comment]
@dosten I think the behaviour of `--logs` should probably stay the same for backward comparability.
What about something like `--all-logs`?

**Comment by djmcgreal-cc** [comment]
> helm status $helm_release -o json | jq -r .info.status.last_test_suite_run.results[].name

`last_test_suite_run` doesn't seem to exist any more.

**Comment by SebTardif** [comment]
Is that rare to use "helm test" with an environment running Istio?

`Error: unable to get pod logs for beneficiary-registry-ui-microservice-chart-test-connection: a container name must be specified for pod beneficiary-registry-ui-microservice-chart-test-connection, choose one of: [istio-init wget istio-proxy]`

**Comment by EricWangPX** [comment]
Is there any plan to fix the helm test issue for the "a container name must be specified for pod" with the environment running Istio?

**Comment by mueslo** [comment]
> [@dosten](https://github.com/dosten) I think the behaviour of `--logs` should probably stay the same for backward comparability. What about something like `--all-logs`?

Where is the issue with backwards compatibility if something that previously produced an error illogically now does not?

I think `helm test --logs` should fetch logs from all containers by default.
