### ISSUE TITLE
Re-authenticating each time I perform a helm3 command

### ISSUE THREAD

**Issue by aido123** [helm/helm#6903]
Output of `helm version`: version.BuildInfo{Version:"v3.0.0-rc.3", GitCommit:"2ed206799b451830c68bff30af2a52879b8b937a", GitTreeState:"clean", GoVersion:"go1.13.4"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"windows/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

Steps to reproduce:
1. Run the following to generate a kube config file
helm3 list -n adrian
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code [REDACTED] to authenticate.
NAME    NAMESPACE       REVISION        UPDATED STATUS  CHART   APP VERSION

2. Run again and it's ok
helm3 list -n adrian
NAME    NAMESPACE       REVISION        UPDATED STATUS  CHART   APP VERSION

3. Run kubectl command ok
kubectl get pods -n adrian
NAME      READY     STATUS         RESTARTS   AGE
nginx     0/1       Running	   0          3h58m

4. Run helm command again and asked to re authenticate
helm3 list -n adrian
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code [REDACTED] to authenticate.

5. Run kubectl command ok
kubectl get pods -n adrian
NAME      READY     STATUS         RESTARTS   AGE
nginx     0/1       Running	   0          3h58m

Is it possible for helm3 to load the kubeconfig in first before talking to the api server? This ordering is giving me some problems in AKS. As you can see below kubectl seems to load in the config before talking to the api server whereas helm3 is going directly. 

kubectl get pods -n adrian -v 9
I1107 12:11:10.544621    2452 loader.go:359] Config loaded from file .kube/config
I1107 12:11:10.548623    2452 loader.go:359] Config loaded from file .kube/config
I1107 12:11:10.551625    2452 loader.go:359] Config loaded from file .kube/config
I1107 12:11:10.556620    2452 round_trippers.go:386] curl -k -v -XGET  -H "User-Agent: kubectl/v1.11.0 (windows/amd64) kubernetes/91e7b4f" -H "Accept: application/json, */*" 'https://[REDACTED].hcp.eastus2.azmk8s.io:443/apis/metrics.k8s.io/v1beta1?timeout=32s'

helm3 list -n adrian -v 9
I1107 11:38:27.698145   11052 round_trippers.go:423] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: helm3/v0.0.0 (windows/amd64) kubernetes/$Format" 'https://[REDACTED].hcp.eastus2.azmk8s.io:443/version?timeout=32s'
I1107 11:38:27.701150   11052 loader.go:375] Config loaded from file:  c:\Users\Adrian\.kube\config

**Comment by bacongobbler** [comment]
interesting find. If you can identify where in the code base that call is being made, a patch would be appreciated. The kube config file should certainly be loaded before making a call out to Kubernetes.

**Comment by bacongobbler** [comment]
I think I found the culprit. Somewhere in the CLI, we might be calling `IsReachable` prior to loading the kube config file. I'll see if I can find the problem area.

https://github.com/helm/helm/blob/43acbfe86d2228134a5f3478e97cae433ca33fb2/pkg/kube/client.go#L75-L83

**Comment by bacongobbler** [comment]
I had a look through the code base. Everything seems fine from a deep dive; the kubeconfig file is loaded first before fetching server information.

According to client-go, it should be logged if the verbosity level is 6 or higher: https://github.com/kubernetes/client-go/blob/e55a71a3e03e5656a816878524151bd42ad3a25e/tools/clientcmd/loader.go#L375

testing with:

```
><> kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
><> helm version
version.BuildInfo{Version:"v3.0.0-rc.3", GitCommit:"2ed206799b451830c68bff30af2a52879b8b937a", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

```
><> helm list -v 6
I1107 12:31:08.984612    1032 round_trippers.go:443] GET https://192.168.99.153:8443/version?timeout=32s 200 OK in 5 milliseconds
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
wp      default         1               2019-11-07 12:17:55.64773868 -0800 PST  deployed        wordpress-7.6.0 5.2.4
```

Same goes for master:

```
><> ./bin/helm version
version.BuildInfo{Version:"v3.0+unreleased", GitCommit:"43acbfe86d2228134a5f3478e97cae433ca33fb2", GitTreeState:"clean", GoVersion:"go1.13.3"}
><> ./bin/helm list -v 6
I1107 12:32:16.799707    1167 round_trippers.go:443] GET https://192.168.99.153:8443/version?timeout=32s 200 OK in 5 milliseconds
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
wp      default         1               2019-11-07 12:17:55.64773868 -0800 PST  deployed        wordpress-7.6.0 5.2.4
```

I could not see the same log messages you reported here with either version. Can you please verify that you're using the same helm version in your demonstrations?

What seems most interesting to me is how `kubectl` loads the kubeconfig three times in quick succession as shown in your output of `kubectl get pods -v 9`. If you can share details on how you provisioned your cluster, perhaps that could identify the issue.

**Comment by aido123** [comment]
Thanks for the quick turnaround @bacongobbler, I've tried to recreate on a clean linux machine and I cannot.  I'm happy to close, sorry for the trouble.

**Comment by aido123** [comment]
Not reproducible.

**Comment by LeiYangGH** [comment]
it could be bash environment problem.
I encounter the same problem, when using mobaxterm as bash on my windows, and helm3 is a soft link to windows exe.

then i cannot reproduce the problem when i shifted to wsl(ubuntu) and used linux format helm3 binary.
Can anybody expain why?
