### ISSUE TITLE
docs/ directory in 3.0 missing

### ISSUE THREAD

**Issue by laidig** [helm/helm#6916]
Hello!
The docs directory was removed in the 3.0 release and content was moved to `helm.sh`. Many links now 404, so it makes for a poor user experience.

There should at least be a stub page (`docs/index.md`) telling users this. I'm happy to create one and submit a PR if it will be accepted.

**Comment by bacongobbler** [comment]
https://github.com/helm/helm/issues/6768#issuecomment-545695304

**Comment by bacongobbler** [comment]
Please feel free to contribute a PR that includes a README in the docs directory
