### ISSUE TITLE
Helm2: commit sha App Version getting converted to scientific notation

### ISSUE THREAD

**Issue by karuppiah7890** [helm/helm#6922]
Output of `helm version -c`:
`Client: &version.Version{SemVer:"v2.16.0", GitCommit:"e13bc94621d4ef666270cfbe734aaabf342a49bb", GitTreeState:"clean"}`

When app version is a commit sha, it gets converted to a scientific notation when packaging. And package creates a tar ball even though the command errors out with errors in the output.

See below for more details on how to reproduce and about the issue:

```
$ helm create test

$ # change appVersion to 72225e2
$ vi test/Chart.yaml

$ cat test/Chart.yaml
apiVersion: v1
appVersion: 72225e2
description: A Helm chart for Kubernetes
name: test
version: 0.1.0

$ # notice how it errors out but still creates the tar ball
$ helm package test
Successfully packaged chart and saved it to: /Users/karuppiahoss/oss/helm-issues/issue-6833/dummy-repo-local/test-0.1.0.tgz
Error: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal number into Go struct field ChartVersion.entries.appVersion of type string

$ # check Chart.yaml contents in tar ball
$ vi test-0.1.0.tgz
```

`Chart.yaml` contents in the tar ball:
```
apiVersion: v1
appVersion: "7.2225e+06"
description: A Helm chart for Kubernetes
name: test
version: 0.1.0
```

The issue is similar to #6921 (v3 issue), in this case it's present in v2 too

**Comment by bacongobbler** [comment]
The behavior is correct. If you provide `72225e2` as a field value, that should be rendered as a number in scientific notation. To fix this, wrap the string in quotes. That way the YAML parser will treat it as a string.

We should probably ask `helm create` to wrap the string fields in quotes. That way these fields are treated as strings.

In other words, the output of `helm create test`'s Chart.yaml should be changed from this:

```
apiVersion: v2
name: test
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 1.16.0
```

to this:

```
apiVersion: "v2"
name: "test"
description: "A Helm chart for Kubernetes"

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: "application"

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: "0.1.0"

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: "1.16.0"
```

**Comment by bacongobbler** [comment]
Closing in favour of https://github.com/helm/helm/issues/6921 to keep the conversation in one place. The codepaths are identical. Thanks.

**Comment by karuppiah7890** [comment]
@bacongobbler we still need to put a fix in `dev-v2`, which is not exactly identical code path / code base right? Also, I was putting it separate so that when it's fixed, people can already create proper repo index through this linting and packaging errors, for not putting double quotes, way before doing repo index and repo index will just work and helm3 repo add will not give issues. In fact we can close issue #6849 and have this and #6921 open and fix em

**Comment by bacongobbler** [comment]
I closed this issue because it's the same issue. Issues can span multiple versions. Opening multiple tickets describing the same issue only confuses the community, as there will be simultaneous conversations occurring at the same time in two issues. It's best to keep conversations that are closely related in one ticket so the community can all discuss solutions in a single ticket, rather than repeating the same conversation twice.

**Comment by karuppiah7890** [comment]
Makes sense!
