### ISSUE TITLE
Unable to add the namespace flag for `helm install`

### ISSUE THREAD

**Issue by hadrien-toma** [helm/helm#6923]
- Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.0-rc.3", GitCommit:"2ed206799b451830c68bff30af2a52879b8b937a", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

- Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}`
```

- Cloud Provider/Platform (AKS, GKE, Minikube etc.): `minikube` 

- Output of `minikube version`:
```
minikube version: v1.5.2
commit: 792dbf92a1de583fcee76f8791cff12e0c9440ad-dirty
```

- What is working:
```
/usr/bin/helm \
	install \
		my-chart-name \
		.
```

- What is not working:
```
/usr/bin/helm \
	install \
		my-chart-name \
		. \
		--namespace my-namespace
```
- The error is:
```
Error: must either provide a name or specify --generate-name
```

Does someone have any idea of what is going wrong? :persevere:

**Comment by karuppiah7890** [comment]
The error means that you need to provide a release name or give flag to generate one automatically. According to your example it looks like your release name is `my-chart-name`. And I tried your commands and it worked perfectly fine for me. My doubt is on the new lines and slashes, even though they worked for me. Did you try a one liner? And did you try this multiple times? Same issue? If so, please do provide steps 😄

**Comment by hadrien-toma** [comment]
Copy pasting the commands I gave work for me too! So I copy/pasted them into the bugging script and now it is working, I think you were right about special characters issues, thank you @karuppiah7890 :pray: !
