### ISSUE TITLE
[helm3][question] How to render CRDs with helm template?

### ISSUE THREAD

**Issue by mtougeron** [helm/helm#6930]
How do I have `helm3` render the CRDs in the `mychart/crds` directory when running `helm template`? It would be nice if we were able to render all chart files when running `helm template` (even if they are not templated). That would give closer feature parity to running helm install. Is this possible?

edit: I understand that it won't render them as templates but it would be nice if they could be generated/output at all.

Thanks, Mike

Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.0-rc.3", GitCommit:"2ed206799b451830c68bff30af2a52879b8b937a", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:51:13Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:55Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by amuraru** [comment]
@mtougeron Mike, can you post an example with the issue you're seeing?

**Comment by mtougeron** [comment]
An example app could look like:

```
$> tree charts/touge
charts/touge
├── Chart.yaml
├── charts
├── crds
│   └── mycrd.yaml
├── templates
│   ├── NOTES.txt
│   ├── _helpers.tpl
│   ├── deployment.yaml
│   ├── ingress.yaml
│   ├── service.yaml
│   └── serviceaccount.yaml
└── values.yaml

3 directories, 9 files
```

```
$> helm template touge --namespace default --output-dir rendered-charts charts/touge
wrote rendered-charts/touge/templates/serviceaccount.yaml
wrote rendered-charts/touge/templates/service.yaml
wrote rendered-charts/touge/templates/deployment.yaml
```

```
$> tree rendered-charts 
rendered-charts
└── touge
    └── templates
        ├── deployment.yaml
        ├── service.yaml
        └── serviceaccount.yaml

2 directories, 3 files
```

As you can see with `helm template` it didn't output the mycrd.yaml. I'm presuming that this is because of the change to use the `crds` directory and that those are not templates. But I was hoping there was a way to handle that so that our pipeline of committing rendered yaml into git could still be supported.

**Comment by GrahamGoudeau** [comment]
@amuraru I am also interested in having `helm template` output the CRDs. A use case for our product is roughly `helm template | kubectl apply -f -`

**Comment by wpwoodjr** [comment]
I mentioned this to the developer at Kubecon and he was surprised that ```helm3 template``` doesn't output CRDs.  I too would like it to do this.

**Comment by cppforlife** [comment]
+1

**Comment by bacongobbler** [comment]
closed via #7138

**Comment by mtougeron** [comment]
@GrahamGoudeau Thanks for adding this functionality!

**Comment by hlascelles** [comment]
The flag is `--include-crds`. eg:

```
helm template projectcalico/tigera-operator --include-crds
```
