### ISSUE TITLE
Where do i see the sub-chart version when I install umbrella/parent chart in hel3

### ISSUE THREAD

**Issue by himmakam** [helm/helm#6932]

**Comment by bridgetkromhout** [comment]
Hi, @himmakam. You can read about [Importing Child Values via dependencies](https://helm.sh/docs/topics/charts/#importing-child-values-via-dependencies), which looks like it will answer this question.

**Comment by TBBle** [comment]
I don't think `.Chart.Version` is available from subcharts.
