### ISSUE TITLE
Error: forwarding ports: error upgrading connection: error dialing backend: dial tcp xx.xx.xxx.xxx:10250: i/o timeout

### ISSUE THREAD

**Issue by empikls** [helm/helm#6935]
When I install ingress stable/nginx-ingress by terraform  I first of all apply rbac 
kubectl apply -f create-helm-service-account.yml

then add section helm init --service-account tiller --wait

and after all I install nginx-ingress , but I got the same error 

Error: forwarding ports: error upgrading connection: error dialing backend: dial tcp xx.xx.xxx.xxx:10250 i/o timeout .

When I connected to cluster i could install nginx-ingress by helm without error . 

What it can be ?

**Comment by Sammy2005** [comment]
Hi @empikls did you solve the problem. I have the same error on running any helm command such as `helm list`

**Comment by empikls** [comment]
Hi!

Yes, sure . Problem was in temporary inactivity k8s network.
I use terraform and when cluster is created it need more time for create network policy and port forwarding . 
You can add check for ready network plugin and others policies .

**Comment by Siva-R** [comment]
Hi @empikls, we are experiencing the same issue. What exactly do you mean to add a check for ready network plugin and other policies?

**Comment by empikls** [comment]
Hi!

As I mention before terraform used in my case . In one of the steps when I configure tiller was adding check for ready . One of the check was like this : 

while kubectl logs deploy/tiller-deploy -n kube-system; [ $? -gt 0 ]; do echo "Wait access to pod tiller"; done
