### ISSUE TITLE
Release status stuck to "pending-install"

### ISSUE THREAD

**Issue by pablo-ruth** [helm/helm#6939]
Output of `helm version`:
`version.BuildInfo{Version:"v3.0.0-rc.3", GitCommit:"2ed206799b451830c68bff30af2a52879b8b937a", GitTreeState:"clean", GoVersion:"go1.13.4"}`

Output of `kubectl version`:
`oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Openshift 3.11

I'm testing Helm 3.0 rc-3 by installing [this chart](https://github.com/Ouest-France/k8s-vault-webhook/tree/helm3/charts/k8s-vault-webhook) and when I deploy a release with "install" or "upgrade" the "helm status" for this release is stuck to "pending-install"

```shell
$ helm install k8svaultwebhook ouestfrance/k8s-vault-webhook
NAME: k8svaultwebhook
LAST DEPLOYED: Tue Nov 12 15:40:26 2019
NAMESPACE: infrastructure-okd-vaultwebhook
STATUS: deployed
REVISION: 1
TEST SUITE: None
```
```shell
$ helm status k8svaultwebhook
NAME: k8svaultwebhook
LAST DEPLOYED: Tue Nov 12 15:40:26 2019
NAMESPACE: infrastructure-okd-vaultwebhook
STATUS: pending-install
REVISION: 1
TEST SUITE: None
```

But I don't have this behavior when using "--wait" flag
```shell
$ helm install --wait k8svaultwebhook ouestfrance/k8s-vault-webhook
NAME: k8svaultwebhook
LAST DEPLOYED: Tue Nov 12 15:43:03 2019
NAMESPACE: infrastructure-okd-vaultwebhook
STATUS: deployed
REVISION: 1
TEST SUITE: None
```
```shell
$ helm status k8svaultwebhook
NAME: k8svaultwebhook
LAST DEPLOYED: Tue Nov 12 15:43:03 2019
NAMESPACE: infrastructure-okd-vaultwebhook
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

**Comment by bacongobbler** [comment]
Was an error reported during the install? I can't see a case where the release would be stuck in "pending-install" without reporting an error back to the user.

https://github.com/helm/helm/blob/946aa19d28f5dc849a20c23596d6d40727a91e97/pkg/action/install.go#L226-L293

**Comment by bacongobbler** [comment]
also possibly related to #6934 and #5595.

**Comment by bacongobbler** [comment]
Weird... I can reproduce this issue locally using the chart provided.

```
><> helm repo add ouestfrance https://charts.ouest-france.fr/
"ouestfrance" has been added to your repositories
><> helm install k8svaultwebhook ouestfrance/k8s-vault-webhook
NAME: k8svaultwebhook
LAST DEPLOYED: Tue Nov 12 12:22:54 2019
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
><> helm status k8svaultwebhook
NAME: k8svaultwebhook
LAST DEPLOYED: Tue Nov 12 12:22:54 2019
NAMESPACE: default
STATUS: pending-install
REVISION: 1
TEST SUITE: None
```

**Comment by bacongobbler** [comment]
Found the error that was not being reported back to the user:

> Error: update: failed to update: Internal error occurred: failed calling webhook "secrets.k8s-vault-webhook.webhook": Post https://k8svaultwebhook-k8s-vault-webhook.default.svc:443/secret?timeout=29s: dial tcp 10.99.182.40:443: connect: connection refused

Appending the `--wait` flag works as expected, as the release is recorded and updated after the webhook has been registered.

Will supply the patch.

**Comment by pablo-ruth** [comment]
Yes, it's a very specific issue. Reporting the error seems the better idea. Detecting the registering of a webhook to force wait flag doesn't resolve the issue if the webhook still doesn't reply correctly after the release installation, so alerting the user if a release recording fails seems the better approach.

**Comment by pablo-ruth** [comment]
Thanks for the fix, is merged now so I close this issue.

**Comment by deepakthaman** [comment]
Similar issue still with v3.2.1

**Issue even after using --wait and timeout flags on helm3**

**The timeout never happens** 

```
helm3 install ...... --wait --timeout 2h

helm3 version --short

v3.2.1+gfe51cd1
```


**Chart goes into pending-install no timeouts happening** 

```
date
Thu May 21 19:33:38 UTC 2020

helm3 history my-chart -n my_namespace
REVISION        UPDATED                         STATUS          CHART                                           APP VERSION     DESCRIPTION
1               Thu May 21 10:47:19 2020        pending-install my-chart                                        1.0             Initial install underway

date
Thu May 21 19:33:56 UTC 2020
```


**The chart has a Post-Install Hook which never got started**.

```
"helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
```

Any ideas where to look for any error logs for hook start issues ?

**Comment by hferentschik** [comment]
I have the same/similar issue and think it was never really properly resolved. I opened issue #10023 to follow up. 

> Detecting the registering of a webhook to force wait flag doesn't resolve the issue if the webhook still doesn't reply correctly after the release installation, so alerting the user if a release recording fails seems the better approach.

I think what needs to happen is that the update operation for the release Secret should get retried in order to capture the cases where for example validating webhooks get installed and there is time windows for the webhook to properly respond.
