### ISSUE TITLE
Proposal: Include release name and chart name in value files

### ISSUE THREAD

**Issue by zzq889** [helm/helm#6954]
I think helm need to persist all state(release name, chart name, etc.) in the values file so I can simply do:
```
helm apply -f values.yaml
```
which is more friendly with GitOps flow.

**Comment by hickeyma** [comment]
@zzq889 Do you mind explaining what you mean by state? Are you looking for help do save this state to your values file? Also, what version of helm are you using?

**Comment by zzq889** [comment]
I use both helm2 and helm3.
For kubernetes resources in a folder, I can simply do `kubectl apply` and everything will be updated. 
```
// kubectl apply -f .
a.yaml
b.yaml
c.yaml
```
For helm command, I have to specify `release-name` and `chart-name/path`. When I do continuous deployment, it's hard to know the chart name in a mixed folder like this:
```
// helm upgrade -i [release-a] [chart-a] -f a-values.yaml
a-values.yaml -> chart-a
b-values.yaml -> chart-b
c-values.yaml -> chart-c
```

what I want to do is:
```
helm apply -f a-values.yaml
```
without any additional args

**Comment by zzq889** [comment]
@hickeyma any update?

**Comment by hickeyma** [comment]
@zzq889 I am not sure we want to put the chart name and release name in the values file. `helm get` should be able to give the information that you need.

**Comment by zzq889** [comment]
@hickeyma Based on infra as code principle, anything should be persisted in a repo. The values.yaml file has less info we need to reproduce the CD workflow. I think we need a mechanism to achieve this.

**Comment by hickeyma** [comment]
@zzq889 Maybe I am missing something here but I don't see a good reason for this proposal. What is the use case that is not already covered by Helm already?

**Comment by zzq889** [comment]
@hickeyma for example, batch apply of apps: Multiple values with different chart deployed within a simple helm apply cmd which is capable in kustomize or kubectl apply.

**Comment by hickeyma** [comment]
@zzq889 Maybe your requirement could be related to #5276?

**Comment by bridgetkromhout** [comment]
@zzq889 Thank you for your ideas to improve Helm. If you'd like, you can submit a Helm Improvement Proposal so as to work in the community to make your ideas a reality: https://github.com/helm/community/blob/master/hips/hip-0001.md - meanwhile, I will close this issue. Thanks!
