### ISSUE TITLE
helm concurrent install questions

### ISSUE THREAD

**Issue by magicLian** [helm/helm#6955]
helm version : 2.15.1
tiller version : 2.15.0

command :  `helm upgrade --install `

10 concurrent per second , it takes 12s to finish
20 concurrent per second ,it takes 24-25s 
50 concurrent per second, it takes almost 60s 

It looks like a linear increase, but i wonder that how can  be more  faster? The test result is a little slow for me .

**Comment by xlixlixli** [comment]
How did you solve the problem?
I have the same question now.
