### ISSUE TITLE
How to upgrade specified resource when I use helm upgrade 

### ISSUE THREAD

**Issue by hillbun** [helm/helm#6956]
Output of `helm version`:
v2.15.1

Output of `kubectl version`:
v1.15.3

values.yalm

abc:
    tag: abc111

xyz:
    tag: xyz111

deployment.yaml
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: test
  name: abc
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: abc
    spec:
      containers:
      - name: abc
        image: docker.domain.com:5000/abc:{{.Values.abc.tag}}
        imagePullPolicy: Always
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: test
  name: xyz
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: xyz
    spec:
      containers:
      - name: xyz
        image: docker.domain.com:5000/xyz:{{.Values.xyz.tag}}
        imagePullPolicy: Always

deploy steps:

1. helm install -f project/values.yaml ./project --name project
abc.tag=abc111
xyz.tag=xyz111

2. helm upgrade project -f project/values-prod.yaml  ./project  --set abc.tag=production
abc.tag=production
xyz.tag=xyz111

3. helm upgrade project -f project/values-prod.yaml  ./project  --set xyz.tag=production
abc.tag=abc111
xyz.tag=production

How to keep abc.tag previous value of production, but but reset to abc111 defined in values file?

My purpose is:
abc.tag=production
xyz.tag=production

**Comment by hillbun** [comment]
I try in step 3:
helm upgrade project -f project/values-prod.yaml ./project --set xyz.tag=production --reuse-values

abc.tag=production is not used.

**Comment by hillbun** [comment]
I remove -f project/values-prod.yaml , and issue solved

**Comment by hickeyma** [comment]
@hillbun I think this is working as expected. Value files take precedent over value being set: https://helm.sh/docs/topics/chart_template_guide/values_files/
