### ISSUE TITLE
crd-install apiextensions.k8s.io/v1 does not work

### ISSUE THREAD

**Issue by strainovic** [helm/helm#6958]
After upgrade to 2.16.1 bug is still here :(

Helm version: 2.16.1
```
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```
Kubernetes version: 1.16.2
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
Kubernetes distribution: Canonical Microk8s

I've tried to deploy CRD with new apiextensions.k8s.io/v1 API but once I add "helm.sh/hook": crd-install installation failed with error "unable to convert to CRD type...".
```
Error: unable to convert to CRD type: no kind "CustomResourceDefinition" is registered for version "apiextensions.k8s.io/v1" in scheme "k8s.io/client-go/kubernetes/scheme/register.go:67"
```

Actually, CRD got installed but there is no helm release.

**Comment by jimmidyson** [comment]
I'm hitting this too. What can I do to help get this fixed?

**Comment by bacongobbler** [comment]
It's likely that the new CRD api needs to be registered with the schema like we had to with the `apiextensions.k8s.io/v1beta1` API.

https://github.com/helm/helm/blob/0ca95341c19fcaf9cecdf50caef1693568835a84/pkg/kube/client.go#L84-L87

**Comment by bacongobbler** [comment]
slating for Helm 3.1.0 because this issue appears to be present there as well.
