### ISSUE TITLE
Helm create default template

### ISSUE THREAD

**Issue by kfox1111** [helm/helm#6960]
Just tried out helm 3.0.0. Each version of helm seems to get a little better at the default "helm create foo". But every one of the charts it creates gets stuck in time making it hard to fix issues with older charts. In 3.0.0, there is mention of library charts. I think we should start using them in the default templates and providing a standard one?

For example, newer generated templates have this in ingress:
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1

this could be replaced by:
{{ include "stdlib.ingress.apiVersion.v1" . }}

Then when new functionality like this is added (say when its no longer v1beta1 but v1) then the library chart can be easily extended. existing charts can update their library chart and gain the new feature without regenerating the chart from scratch or having to patch it in.

**Comment by Fradulentus** [comment]
Как именно будут образовываться новые функции?

**Comment by kfox1111** [comment]
Assuming that translates to:
```
How exactly will new features be formed?
```

New features would be new macros in the library chart. They would be additions so wouldn't break older charts. Sticking to semver versioning of the library would let users know they can upgrade their library chart without breaking their main chart.

**Comment by Fradulentus** [comment]
Скажите,чем отличается график от диаграммы?

**Comment by kfox1111** [comment]
Google translates that to:
```
Tell me, what is the difference between a chart and a chart?
```
Which I assume you mean a regular chart and library chart?

The idea being that helm create generates the regular chart code, but then the user is responsible from then on to maintain everything in the regular chart. Any new features need to be added explicitly by the end user. With a library chart, the helm maintainers can update the library chart and the user can just consume a new version of it without having to merge in new code.

For example, take the service that the template creates today. Every chart that needs to support externalIP specifications (technically, all of them) isn't in the template today. If a library chart was added, the feature could be added to the library chart and existing charts can update the library chart and then the feature works. Today everyone would have to manually merge in all the code themselves.

**Comment by kfox1111** [comment]
Another example in the same file... there is no way for an end user to specify any annotations on the service. If metadata was a function then that feature could be added in the library chart.

**Comment by Fradulentus** [comment]
Перевод Bing Microsoft Translator:
<<<Другой пример в том же файле... конечный пользователь не может указать какие-либо аннотации на службе. Если метаданные были функцией, то эта функция может быть добавлена в библиотечную диаграмму.>>>
К чему все это приведет?

**Comment by kfox1111** [comment]
```
> What will all this lead to?
```

Less maintenance for chart maintainers, better feature support for end users.

**Comment by Fradulentus** [comment]
Возможно я отклонюсь от общей темы.
При условии стабильно работающего модификатора поведения потребляющих узлов цепи и всех взаимодействующих выходных велечин в рамках отдельных независымых субъектов,не приведет ли конечного пользователя системы к абсолютному бессилилию в цифровой проекции мира?И в какой степени сейчас внутренняя среда разработки доступна человеку?
(Если возникнут трудности с переводом,я попробую перефразировать свой вопрос)

**Comment by kfox1111** [comment]
Sorry. Google Translate is having a problem with that question.

**Comment by Fradulentus** [comment]
Можешь мне в почту написать?

**Comment by Fradulentus** [comment]
Fradulentus@outlook.com

**Comment by Fradulentus** [comment]
Бот не смей тут открывать рот.Вопросы акктуальны,хочешь мод?
