### ISSUE TITLE
Bad documentation or helm help is missing topics

### ISSUE THREAD

**Issue by ryan-dyer-sp** [helm/helm#6961]
Output of `helm version`:
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}

https://helm.sh/docs/faq/#pushing-charts-to-oci-registries indicates at the bottom to run ```helm help registry``` or ```helm help charts```
Neither work.

**Comment by bacongobbler** [comment]
Hi @ryan-dyer-sp. Before running those commands, did you make sure to set the environment variable `HELM_EXPERIMENTAL_OCI=1`? These commands are disabled by default, and the documentation mentions setting that environment variable before interacting with those commands.

Let us know how you get along.

**Comment by ryan-dyer-sp** [comment]
That was it.  Though I find it odd I need to enable a feature flag to get help on a command even if that command is hidden behind the ff.  Thanks.  

Know if anyone has tested this against artifactory?  I am able to login to one of our artifactory repos, but am unable to push.  I get a 404.

```
> helm chart save helm/ company-repo.jfrog.io/prometheus-oprator:test
ref:     company-repo.jfrog.io/prometheus-oprator:test
digest:  9841cf9910c892207a2fa9e15ef4a0722ae640d3ea33b1113a1d5029cf7ef4a1
size:    124.5 KiB
name:    prometheus-operator
version: 4.3.5
test: saved
> helm chart push alienvault-docker-releases-dockerv2-local.jfrog.io/prometheus-oprator:test
The push refers to repository [company-repo.jfrog.io/prometheus-oprator]
ref:     company-repo.jfrog.io/prometheus-oprator:test
digest:  9841cf9910c892207a2fa9e15ef4a0722ae640d3ea33b1113a1d5029cf7ef4a1
size:    124.5 KiB
name:    prometheus-operator
version: 4.3.5
Error: failed commit on ref "unknown-sha256:c558b64654f544ca6b20f56e5835336578de93fb1ae068db04e7a0b08edbfd84": unexpected status: 404 Not Found
```

**Comment by bacongobbler** [comment]
I haven't heard of anyone test it with artifactory at this time. I'd reach out to the artifactory folks and see what they think the error might be.

closing as answered.
