### ISSUE TITLE
v3 s390x release checksum busted

### ISSUE THREAD

**Issue by andrewrothstein** [helm/helm#6962]
curl https://get.helm.sh/helm-v3.0.0-linux-s390x.tar.gz.sha256
yields "Blob not found" sadness

**Comment by bacongobbler** [comment]
Good catch. It looks like we don't cross-compile for  s390x builds of Helm 3. I recall that only being PR'd against Helm 2 so it wasn't picked up. I'll remove it from the release notes in the meantime.

Would you like to add it back? Link is https://github.com/helm/helm/blob/master/Makefile#L3
