### ISSUE TITLE
[Helm v3][OpenShift] User cannot "get" on "/swagger-2.0.0.pb-v1"

### ISSUE THREAD

**Issue by placaze** [helm/helm#6964]
We can't deploy on the OpenShift of our company since *v3.0.0-beta.5*. Same problem with v3 finale.  
*v3.0.0-beta.4* and before were working fine.

Output of `helm version`:
```
$ /mnt/c/Users/Arthur/Téléchargement/helm-v3.0.0-beta.4.exe version
version.BuildInfo{Version:"v3.0.0-beta.4", GitCommit:"7ffc879f137bd3a69eea53349b01f05e3d1d2385", GitTreeState:"dirty", GoVersion:"go1.13.1"}
```
```
$ /mnt/c/Users/Arthur/Téléchargement/helm-v3.0.0-beta.5.exe version
version.BuildInfo{Version:"v3.0.0-beta.5", GitCommit:"509a8819b7e8dba86b7982c006fce22628aeea28", GitTreeState:"clean", GoVersion:"go1.13.3"}
```
```
$ /mnt/c/Users/Arthur/Téléchargement/helm.exe version
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

Output of `oc version`:
```
$ /mnt/c/Users/Arthur/Téléchargement/oc.exe version
oc v3.7.2+282e43f
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth

Server https://REDACTED:443
openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
```

Deployment:
```
$ /mnt/c/Users/Arthur/Téléchargement/helm-v3.0.0-beta.4.exe upgrade -i -f envs/dev1.yaml -n our_namespace ms-template-dev1 .
Release "ms-template-dev1" has been upgraded. Happy Helming!
NAME: ms-template-dev1
LAST DEPLOYED: Thu Nov 14 10:44:25 2019
NAMESPACE: our_namespace
STATUS: deployed
REVISION: 11
```
```
$ /mnt/c/Users/Arthur/Téléchargement/helm-v3.0.0-beta.5.exe upgrade -i -f envs/dev1.yaml -n our_namespace ms-template-dev1 .
Error: UPGRADE FAILED: User "Arthur" cannot get path "/swagger-2.0.0.pb-v1": User "Arthur" cannot "get" on "/swagger-2.0.0.pb-v1"
```

**Comment by hickeyma** [comment]
@placaze Have a few questions to help better understand what the problem.

Are you able to install any chart using Helm 3? For example, can you create a scaffold chart (`helm create foo`) and try and install that?

**Comment by placaze** [comment]
It was easier than I originally thought.

Here are the results (comparing v3.0.0-beta4, v3.0.0-beta5 and v3.0.1):
```
C:\helm>C:\Users\Arthur\Téléchargement\helm-v3.0.0-beta.4.exe upgrade -i -n our_namespace test foo
Release "test" does not exist. Installing it now.
Error: apiVersion "apps/v1" in foo/templates/deployment.yaml is not available

C:\helm>C:\Users\Arthur\Téléchargement\helm-v3.0.0-beta.5.exe upgrade -i -n our_namespace test foo
Release "test" does not exist. Installing it now.
Error: apiVersion "apps/v1" in foo/templates/deployment.yaml is not available

C:\helm>C:\Users\Arthur\Téléchargement\helm-v3.0.1.exe upgrade -i -n our_namespace test foo
Release "test" does not exist. Installing it now.
Error: unable to build kubernetes objects from release manifest: User "Arthur" cannot get path "/swagger-2.0.0.pb-v1": User "Arthur" cannot "get" on "/swagger-2.0.0.pb-v1"
```

**Comment by hickeyma** [comment]
@bacongobbler @thomastaylor312 Would you be able to test this on a Windows environment?

**Comment by thomastaylor312** [comment]
@placaze So I was just looking at this. It looks like you are running a fairly old version of Kubernetes and Openshift. The Kubernetes version is well outside of our supported version range. Is there any way you can test this on a more recent Kubernetes version to see if you have the same problem? I am guessing this has something to do with a new API endpoint for discovery in more recent versions of k8s

**Comment by placaze** [comment]
Thanks for the reply.

What is the current supported version range of Kubernetes for Helm v3?  
Kubernetes v1.6 is mentionned in the docs: https://helm.sh/docs/intro/quickstart/

My company will slowly switch to vanilla Kubernetes next year.
Here is the OpenShift version we are currently using:
![image](https://user-images.githubusercontent.com/57751243/71017979-dfaeb080-20f7-11ea-8c33-df0185788a2d.png)

We have this issue since **v3.0.0-beta.5**. It was OK with **v3.0.0-beta.4**.
Commits: https://github.com/helm/helm/compare/v3.0.0-beta.4...v3.0.0-beta.5

And it's not Windows exclusive. The behaviour is the same with Linux binaries.

**Comment by bacongobbler** [comment]
It's best to try something a little more recent, like Kubernetes 1.16 or 1.17. You're about 10 releases behind the current stable release. :)

**Comment by placaze** [comment]
These two commits introduced my issue: https://github.com/helm/helm/commit/572b92dc8aa4adf90337578a108ee5f4c501e3c6 & https://github.com/helm/helm/commit/1e20ebae35d17c94e77051044fee79913c2719ff

I made a quick build and I don't have the error anymore if I switch `true` to `false` on this 3 lines:
* https://github.com/helm/helm/blob/release-3.0/pkg/action/install.go#L229
* https://github.com/helm/helm/blob/release-3.0/pkg/action/upgrade.go#L197
* https://github.com/helm/helm/blob/release-3.0/pkg/action/upgrade.go#L376

I know the version of Kubernetes we are using is outdated but I can't upgrade it. It's maintained for the whole company, and they won't touch it until the vanilla Kubernetes internal offer is running (next year).

Kubernetes v1.6 is mentioned in the docs, and Kubernetes v1.7 doesn't seem supported. What's the policy here?

Is it possible to add a `--no-openapi-validation` flag so we can keep using an up-to-date version of Helm?

**Comment by bacongobbler** [comment]
We don’t support k8s 1.7. If you can point out the line in the documentation where we call that out, we would be happy to remove it.

As for disabling OpenAPI validation, see https://github.com/helm/helm/pull/6819. It’s not recommended for this use case, however.

I think you’re looking at the problem the wrong way though... From the original error message, it appears that you are trying to install a workload that isn’t supported by that version of Kubernetes. In other words, because your version of Kubernetes is so old and unsupported, it cannot install deployments using the “apps/v1” API. That workload API was introduced some time much later, so it’s unsurprising you’re cluster does not recognize that API type.

**Comment by bridgetkromhout** [comment]
>We don’t support k8s 1.7. If you can point out the line in the documentation where we call that out, we would be happy to remove it.

Hi, @placaze - thanks for mentioning the confusing reference to Kubernetes version 1.6. I have put in a documentation update to clarify the supported versions of Kubernetes: https://github.com/helm/helm-www/pull/781

> because your version of Kubernetes is so old and unsupported, it cannot install deployments using the “apps/v1” API. That workload API was introduced some time much later, so it’s unsurprising your cluster does not recognize that API type (and therefore, cannot install it).

We sympathize with having clusters one cannot upgrade, and while a workaround to disable validation is available (https://github.com/helm/helm/pull/6819), we recommend encouraging both Red Hat and your employer to backport fixes and update versions.

As there is no more action we can take on this issue, I'll resolve it now. Please do let us know if there is anything else the helm project can do for you.
