### ISSUE TITLE
can `helm status` show namespace?

### ISSUE THREAD

**Issue by jianzzz** [helm/helm#6965]
We can deploy some services in different namespaces through an helm instance. So, can we show the namespace when we run `helm status xxx`?

**Comment by EricLemieux** [comment]
AFAIK helm 2 does include the namespace in the status output, and helm 3 releases are now scoped to the namespace, so you would need to know the namespace before you can query the status of the release.

https://helm.sh/docs/faq/#release-names-are-now-scoped-to-the-namespace

**Comment by jianzzz** [comment]
> AFAIK helm 2 does include the namespace in the status output, and helm 3 releases are now scoped to the namespace, so you would need to know the namespace before you can query the status of the release.
> 
> https://helm.sh/docs/faq/#release-names-are-now-scoped-to-the-namespace

I'm talking about the services/deployments/statefulsets that release contains.
f.g.
```
# helm status case

NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/Deployment
NAME                      READY  UP-TO-DATE  AVAILABLE  AGE
default-case             2/2        1                    0                 10d
```
Yes, release `case` is deployled with namespace `default`, but deployment default-case  may be deployed in namesapce `public`, or other namespace.
