### ISSUE TITLE
helm test --logs errors out when tests include non-Pod resources

### ISSUE THREAD

**Issue by jlegrone** [helm/helm#6968]
Output of `helm version`: 3.0.0

The `helm test --logs` implementation assumes that tests are always defined as Pods, which is no longer the case in Helm 3. We should support getting logs for Jobs, and not return an error when we encounter a resource that is neither a Pod nor a Job.

Relevant PR: https://github.com/helm/helm/pull/6693

**Comment by deneuv34** [comment]
Hi @jlegrone, can I try solve this issue? 😃
