### ISSUE TITLE
Helm3 list must specify the flag --all-namespaces

### ISSUE THREAD

**Issue by lhb008** [helm/helm#6971]
Output of `helm version`: v3.0.0

Output of `kubectl version`: v1.13.8

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  IBM Kubernetes Service.

Hi team, i tried the helm v3 version, after i migrated the v2 to v3 using 2to3 plugin, i must specify the flag --all-namespaces to check the deployed release, otherwise, there is nothing to show:

```
helm-3 ls -a
NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART	APP VERSION
$ helm-3 ls
NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART	APP VERSION
$ helm-3 ls --all-namespaces
NAME   	NAMESPACE   	REVISION	UPDATED                                	STATUS  	CHART            	APP VERSION
helm-test	helm-test	9       	2019-11-14 01:22:09.174909324 +0000 UTC	deployed	helm-0.1.0	1.0
```
But the docs said ```helm-3 ls``` will work fine.

**Comment by karuppiah7890** [comment]
Is helm-test your default namespace? I'm asking as `helm ls` will take your default k8s namespace and show list of releases in that namespace. In this case, I think helm-test might not be your default namespace. And that's why it didn't show up. But it showed up when you used all namespaces. 

Could you check if that's the case? Or else we will have to dig into it further with more details

**Comment by lhb008** [comment]
@karuppiah7890  Sorry, i think i make a mistake, i know that `helm3` must specify the namespace to list the release under that `namespace`, i follow the docs on ```https://helm.sh/blog/migrate-from-helm-v2-to-helm-v3/```,  i think there is a little mistake,
```
$ helm list
NAME    	REVISION	UPDATED                 	STATUS  	CHART           	APP VERSION	NAMESPACE
postgres	1       	Wed Sep 11 14:52:32 2019	DEPLOYED	postgresql-6.3.5	11.5.0     	postgres
redis   	1       	Wed Sep 11 14:52:57 2019	DEPLOYED	redis-9.1.7     	5.0.5      	redis

$ helm3 list
NAME    	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART
postgres	postgres 	1       	2019-09-11 12:52:32.529413 +0000 UTC	deployed	postgresql-6.3.5
```
for `v3` `helm list` can not list the `release` under namespace `postgres` i think.  Now i will close this issue(this is my mistake not  a issue), sorry again.
