### ISSUE TITLE
helm3 change the deployed timezone and time

### ISSUE THREAD

**Issue by kevinsingapore** [helm/helm#6972]
how to change the deployed timezone and time?
![image](https://user-images.githubusercontent.com/39163739/68914177-be754000-0798-11ea-99b3-ffdea3f4eff0.png)

**Comment by kevinsingapore** [comment]
how to solve？

**Comment by hickeyma** [comment]
@kevinsingapore Are you looking for `helm list` to show the time in the timezone of the system?

**Comment by jan25** [comment]
Also, the date-time shown can be shortened to `YYYY-MM-DD HH:MM:SS TZ`.

And, I think we can always show the date-time in users timezone(which would become default behavior for `helm list`). Thoughts?

**Comment by IRobL** [comment]
I just made the upgrade to Helm 3 today, and while I love the new release, this issue jumped out at me as well.  The new long-form of date is quite an eyeful and I too think making the default view of `helm list` should be considered for emphasizing human readability.  Knowing the moment of the release up to the seconds is plenty.

**Comment by jan25** [comment]
Cool! I'll try to open a preliminary PR when i find some time, we can discuss more in it.

**Comment by hickeyma** [comment]
You could open a pr as might be best to understand where to go with this. At moment, UTC works and is standard. So, lets discuss this more in the PR.
