### ISSUE TITLE
helm 3 doesn't list my release

### ISSUE THREAD

**Issue by thesufian** [helm/helm#6973]
Output of `helm version`: version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:02:12Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

commands I ran:
1. helm repo add stable https://kubernetes-charts.storage.googleapis.com/
2. helm repo update
3. helm install stable/nginx-ingress --set controller.replicaCount=2 --set controller.nodeSelector."beta\.kubernetes\.io/os"=linux --set defaultBackend.nodeSelector."beta\.kubernetes\.io/os"=linux --namespace kingress-basic --generate-name

output of command 3
NAME: nginx-ingress-1573801662
LAST DEPLOYED: Fri Nov 15 13:07:46 2019
NAMESPACE: ingress-basic
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
The nginx-ingress controller has been installed.
It may take a few minutes for the LoadBalancer IP to be available.
You can watch the status by running 'kubectl --namespace ingress-basic get services -o wide -w nginx-ingress-1573801662-controller'

4. helm list 
NAME    NAMESPACE       REVISION        UPDATED STATUS  CHART   APP VERSION

command 4 displays empty list as above

**Comment by fengxsong** [comment]
`helm list -n $namespace`

**Comment by thesufian** [comment]
sorry, my bad. I'm a beginner and didn't know it. thanks! I'm closing the issue.
