### ISSUE TITLE
How to identify which k8s version is supported by which helm version?

### ISSUE THREAD

**Issue by deiga** [helm/helm#6981]
Does a support matrix exist somewhere currently? I wasn't able to find it

**Comment by karuppiah7890** [comment]
I think the easiest way for the user to find out would be for `helm version` to show this information. This will also lead to a good UX, instead of searching for matrices in docs

I think this can be added in v3, as a feature. v2, not so sure, but it would be nice to have it in v2 too, even though usually there are no plans for new features in v2 😅 as v3 is the way forward.

**Comment by deiga** [comment]
@karuppiah7890 To be honest that is probably the worst way I could think of. As an administrator of our k8s cluster I need to know beforehand what helm version supports my k8s cluster version.

**Comment by karuppiah7890** [comment]
Umm, even my team takes care of clusters. I think before doing anything in the main cluster, the tendency is to try it in local, in minikube or something where you can play. In this case, `helm version -c` can work even without a cluster. So you can still install it in your local and run `helm version -c`. And if that shows information about which kubernetes version(s) it supports - How does that user experience sound?

**Comment by karuppiah7890** [comment]
If we want to add it to v2 too, something to consider is, in case of Helm v2, there's also a tiller component (server side). And tiller is the one that talks to kubernetes usually. Client side, I think `helm init` alone talks to kubernetes to install tiller. I think it makes sense only for tiller to show what kubernetes cluster version(s) it supports and talks to, while telling version. But I guess may be both client and tiller can tell what version of kubernetes they both support? 

We can discuss further about v2, once we agree if we need it for v2 or not and get opinions from core maintainers too.

**Comment by deiga** [comment]
@karuppiah7890 Can we please stop talking about adding a feature to the helm client?
Adding a "Supported Versions" matrix document to the README or something similar is all that is required here.
It takes the least time, it's the most accessible and does not discriminate how other people might operate their clusters.

Asking Helm users to "to try it in local, in minikube or something where you can play" to find out if the next Helm version supports your cluster is a really good way to disrespect the time of your users.

**Comment by karuppiah7890** [comment]
I'm sorry if this came out wrong. I understand you are asking for a doc. I was just inclined to think about the different ways to solve the problem and have a solution that is maintainable. And also look at how some solutions / features are already present in helm and how they help. 

To give an example, Helm is written in Golang and uses the Golang standard template library. And if there's an issue in the library or a missing feature, it wouldn't be present in Helm too. But how would a user find out which version of Golang the particular Helm version was built / compiled with? One way is checking a matrix, another I can think of is, show the Golang version when showing Helm version. And Helm v3 does that. Maintaining a supported versions matrix is also a thing, according to me. 

But I'll let the core maintainers reply as they are the final decision makers

**Comment by bacongobbler** [comment]
I agree with both viewpoints here.

We just need to provide a document similar to the distro guide, informing users what versions of Kubernetes work with certain Helm versions.

I could also see us adding the version of the Kube client Helm is compiled against in `helm version`, but that seems orthogonal to @deiga's ask here. It's only helpful information for core maintainers. It isn't very useful for the user, and could confuse them into thinking that they can only use that version of Kubernetes with a certain version of Helm. We can discuss that in a separate ticket, but I believe a document is what the OP's asking for.

@deiga if you want to start working on a doc, please feel free. Officially, Kubernetes only supports n-1 releases back, but we know that's not always the case. I've heard one user running Helm 2.12 on a k8s 1.6 cluster, for example.

**Comment by bacongobbler** [comment]
For reference https://helm.sh/docs/topics/kubernetes_distros

**Comment by karuppiah7890** [comment]
I agree about the user getting confused about them only being able to use a particular Kubernetes version. My take on this : whatever we do, Kubernetes is the source of truth when it comes to kubectl or kube client and kube API server compatibility related information. So, I would say, we should info about what Kubernetes client version we use. The user can check what API servers are supported themselves. Or else we will be doing a duplicate info of what's possibly already present in a Kubernetes doc. The client version can be shown in doc, and CLI too

**Comment by karuppiah7890** [comment]
I say this as Kubernetes version is a ambiguous term. It can mean client version or server version. As Kubernetes has both of these components among multiple others. So the doc needs to be clear on that too

**Comment by karuppiah7890** [comment]
Actually, one question, when you say supported, what do you mean here? Maintenance kind of support? Or helm's compatibility with Kubernetes?

**Comment by deiga** [comment]
@karuppiah7890 "Our k8s server version is X.Y.Z, does Helm A.B.C function with this server version" i.e. "can we upgrade to helm v3" 😂

**Comment by bacongobbler** [comment]
> what do you mean here?

What versions of Kubernetes should a particular version of Helm expect to work again. From 3.0 onwards, the core maintainers agreed to support the n-3 versions of Kubernetes for any given version of Helm. For 3.0.0, that'd be 1.13.x - 1.16.x.

**Comment by desmatz** [comment]
+
For example, kubectl has version skew policy: https://kubernetes.io/docs/setup/release/version-skew-policy/#kubectl
Does helm3 have such skew policy or smth else to determine that I can safely upgrade k8s clusters or helm?

**Comment by bacongobbler** [comment]
Not in writing, though that's a good document to adapt into our docs. Thanks for the link!

**Comment by bacongobbler** [comment]
see https://github.com/helm/helm-www/pull/481

**Comment by Bruce-Qi** [comment]
just refer 
https://helm.sh/docs/topics/version_skew/#:~:text=As%20of%20Helm%203%2C%20Helm,n%2D1%20versions%20of%20Kubernetes.
