### ISSUE TITLE
Custom Helm Chart Istio CRD Wrong Plural name

### ISSUE THREAD

**Issue by BailyTroyer** [helm/helm#6984]
I'm trying to install a custom helm chart with Istio custom resources. However, I run into the following error in the logs of tiller: 

    failed: the server could not find the requested resource (post gatewaies.networking.istio.io)

I'm not sure how or why the plural is `gatewaies` instead of `gateways` because the CRD installed on my cluster is the following:

    status:
      acceptedNames:
        categories:
        - istio-io
        - networking-istio-io
        kind: Gateway
        listKind: GatewayList
        plural: gateways
        shortNames:
        - gw
        singular: gateway

**Note:** I am able to manually install a Gateway separately with no issue. 

Output of `helm version`:

    Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
    Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

Output of `kubectl version`:

    Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
    Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-eks-afa464", GitCommit:"afa464ce9760bd08a53a207f505b133b93366ea3", GitTreeState:"clean", BuildDate:"2019-10-22T21:42:57Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
EKS

**Comment by bacongobbler** [comment]
were you able to determine what caused the issue?

**Comment by BailyTroyer** [comment]
For anyone that stumbles upon this, it ended up being a versioning issue with k8s and Istio. I created and eventually answered my own question also for [reference](https://stackoverflow.com/questions/58867859/istioctl-install-error-unable-to-recognize-stdin-no-matches-for-kind-in-versi).
