### ISSUE TITLE
Proposal: Add values schema json for chart created using `helm create`

### ISSUE THREAD

**Issue by karuppiah7890** [helm/helm#6985]
Output of `helm version`:
`version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}`

Now that Helm v3 supports schema for `values.yaml`, in the form of `values.schema.json` file. I think it would be great to have the schema file as part of the chart created using `helm create` command. This way, the users are educated about the feature - as they will get curious about this new file

Also, honestly, I struggled to find the docs about values schema. Then I grepped the docs repo locally and found it out. 🙈 I think we need to make our docs better in terms of discoverability? introduce search or something? And we need to clearly have all the new features advertised and explained. Or else awareness will be less 😅 I could create a separate issue in docs repo itself to discuss the same

**Comment by karuppiah7890** [comment]
Ah. Looks like the search feature was not working 🙈 https://github.com/helm/helm-www/issues/377

**Comment by karuppiah7890** [comment]
I can work on a PR for this feature if it's accepted :smil

**Comment by bacongobbler** [comment]
Why does the default chart require a JSON schema? In my mind, validating values using a JSON schema is an advanced topic that only a small subset of chart maintainers want to opt into. I don't feel like it's something that should be pushed onto newcomers especially given that it's an optional feature.

**Comment by karuppiah7890** [comment]
Hmm. Makes sense. How does a optional flag sound? Something like `--with-values-schema`. People who are aware of it and are advanced users and want to try it out, can get a sample file may be? But yeah, there's one thing. The default values.yaml for the chart is just too big. Writing a schema for all that, it will be too big and might be complex too

Just a thought. If we feel flag also won't be helpful, I think we can close this issue :)

**Comment by hickeyma** [comment]
I agree with @bacongobbler in https://github.com/helm/helm/issues/6985#issuecomment-557684234. I think it is not needed for the scaffold chart.

**Comment by karuppiah7890** [comment]
Consider the flag. Or else we can close 👍

**Comment by hickeyma** [comment]
I would suggest to close.
