### ISSUE TITLE
[helm3] Show Template File Name in Error Message

### ISSUE THREAD

**Issue by meysholdt** [helm/helm#6986]
I got the error:
```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.securityContext): unknown field "privileged" in io.k8s.api.core.v1.PodSecurityContext
```
It's an error in my helm chart and I know how to fix it. 

I'm filing this issues, because It would be awesome if the error message could tell me which template file caused the error. 

Right now, I needed to grep for the word `privileged` and check every of the 20+ occurrences, which feels like a waste of time. 

Output of `helm version`: 
```
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
vanilla kubernetes

**Comment by jan25** [comment]
These errors seem to be originating in the kubeClient lib dependency. I think the charts are rendered successfully but the kubeClient validations failed on a certain resource, and the validation error is too generic to pin point to a specific template file

To fix this we may need to pass metadata about templates from helm to the kubeClient and back

**Comment by rudolphjacksonm** [comment]
@jan25 am I right in assuming the errors I'm seeing on #7091 is coming from the same lib dependency? Is that pinned to a specific version on Helm v2 and thus why we don't see it on that version?

**Comment by bbeausej** [comment]
This is very problematic indeed. Validation phase seems also to come before the `debug` (verbose) output runs, preventing any kind of inspection.

Would it be possible to at least still output the verbose debug output when the validation fails?
