### ISSUE TITLE
[helm3] helm list not showing anything although chart install using helm3

### ISSUE THREAD

**Issue by alialshamali** [helm/helm#6992]
After installing a chart successfully using helm3 updated by homebrew. helms list doesn't display anything. I used the migration plugin, and the chart was installed fresh with helm3.

```
helm ls
NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART	APP VERSION
```

Output of `helm version`: version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:29Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:09:21Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Baremetal

**Comment by karuppiah7890** [comment]
Sorry, I'm not sure I understand. Could you give more specific details?

You mentioned it was fresh installed using helm3 and you also mentioned you used migration plugin. Migration plugin is needed only if installation happened with v2 and you want to move to v3. And if only fresh install was done, could you tell what command you used to install? And have you checked all namespaces and all statuses? You can check it with `helm ls --all-namespaces --all`

**Comment by alialshamali** [comment]
Hi,

I deployed a fresh chart using helm3 after migrating from v2 using the plugin. The upgrade to v3 was done by homebrew upgrade. I checked all namespaces and all statuses using the command same result it's not listing anything, although it successfully deployed on cluster.

**Comment by karuppiah7890** [comment]
What did you migrate from v2 using the plugin? releases information? or configurations?

And could you do `kubectl get secret,configmap -n <namespace>` in your cluster and see if any release information is present? It will be present in a particular form, with helm release name, and release revision number, and for helm v3, there's also a prefix `sh.helm.release.v1`, like the one in this PR #6500

**Comment by alialshamali** [comment]
Hi @karuppiah7890 

I check the namespace and release information is present
```
secret/sh.helm.release.v1.cert-manager.v1    helm.sh/release.v1                    1      21h
```
but not displaying on helm ls
```
helm ls
NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART	APP VERSION
```

**Comment by alialshamali** [comment]
@karuppiah7890 I ran the 2to3 plugin cleanup, and suddenly everything start showing.
```
NAME        	NAMESPACE   	REVISION	UPDATED                             	STATUS  	CHART               	APP VERSION
cert-manager	cert-manager	1       	2019-11-17 19:00:06.805211 +0300 +03	deployed	cert-manager-v0.11.0	v0.11.0
```

Thanks so much for you help.

**Comment by amribrahim** [comment]
Dears i have same issue i use helm3 and try to connect to previous cluster which has tiller installed so do you know anything can i do to get all thing for example "helm ls" did not return anything

**Comment by hickeyma** [comment]
@amribrahim Can you raise a new issue specifying details of your issue and env?

**Comment by bikramnehra** [comment]
> Dears i have same issue i use helm3 and try to connect to previous cluster which has tiller installed so do you know anything can i do to get all thing for example "helm ls" did not return anything

Try specifying namespace maybe: `helm ls -n <namespace>`

**Comment by axozoid** [comment]
> Try specifying namespace maybe: `helm ls -n <namespace>`
That worked for me. Thanks @bikramnehra .

P.S. I've got Helm2 in my cluster and was installing a chart that supports Helm3 only.

**Comment by ryanwangJC** [comment]
> Dears i have same issue i use helm3 and try to connect to previous cluster which has tiller installed so do you know anything can i do to get all thing for example "helm ls" did not return anything

Maybe try ` helm ls -A` it worked for me.

**Comment by davi5e** [comment]
In my case, I notice `helm ls` do not show the chart while `helm upgrade` takes place. I also suspect some broken upgrade in my side is the cause for the missing chart information, even if all namespaces are listed.

The secrets are still there

```sh
$ kubectl get secrets --field-selector type=helm.sh/release.v1
NAME                                 TYPE                 DATA   AGE
sh.helm.release.v1.app.v1   helm.sh/release.v1   1      8d
sh.helm.release.v1.app.v2   helm.sh/release.v1   1      6d2h
sh.helm.release.v1app.v3   helm.sh/release.v1   1      8h
sh.helm.release.v1.app.v4   helm.sh/release.v1   1      5h20m
sh.helm.release.v1.app.v5   helm.sh/release.v1   1      18m
```

But nothing gets listed....

```sh
$ helm ls
NAME    NAMESPACE       REVISION        UPDATED STATUS  CHART   APP VERSION
```

Is there a way to import the secrets back to Helm v3?

**Comment by bacongobbler** [comment]
Have you tried `helm ls -A` like the previous commenter suggested?

**Comment by davi5e** [comment]
Of course, that's why I suspect some error occurred during `helm upgrade` and now the chart is missing...

Note the error was not with `helm upgrade --atomic` itself, I think my system went down during the process.

**Comment by davi5e** [comment]
Oh, I tried deleting the last secret shown in my previous message and now the release is back!

I still don't understand why `helm ls` stops listing releases during the upgrade process, but in my case I'll just try again.

**Comment by graned** [comment]
> Oh, I tried deleting the last secret shown in my previous message and now the release is back!
> 
> I still don't understand why `helm ls` stops listing releases during the upgrade process, but in my case I'll just try again.

This worked for me like a charm, thanks a lot

**Comment by ansilh** [comment]
If the number of charts is more than 256 in the namespace, then you have to page through the entries. 
```
helm list --offset=256 -n namespace
```
You may use the below command to check how many charts are there in the namespace
```
kubectl get secret -n namespace  |grep helm.sh/release.v1| awk -F "." '{print $5}' | sort | uniq
```

**Comment by scardena** [comment]
as per the `helm ls` help page:
> By default, up to 256 items may be returned. To limit this, use the '--max' flag.
Setting '--max' to 0 will not return all results. Rather, it will return the
server's default, which may be much higher than 256. Pairing the '--max'
flag with the '--offset' flag allows you to page through results.
for me:
```
helm ls -n namespace --max 1000
```
showed the correct number.

**Comment by pallasathena92** [comment]
I am not very understand why `helm ls -A` can list all my helm release rather than `helm ls -a`. -a should be list all right?

**Comment by hickeyma** [comment]
@pallasathena92 From help:

```
-a, --all                  show all releases without any filter applied
  -A, --all-namespaces       list releases across all namespaces
```

**Comment by pallasathena92** [comment]
> @pallasathena92 From help:
> 
> ```
> -a, --all                  show all releases without any filter applied
>   -A, --all-namespaces       list releases across all namespaces
> ```

-A will list more releases than -a, that is expected, right?

**Comment by pradeepnnv** [comment]
JFYI...we observed a similar issue when the helm upgrade failed and status was `pending-upgrade`.
We were able to identify this by running below command.

` helm history -n NAMESPACE  RELEASE_NAME`

We fixed the issue by rolling back to the previous version.
