### ISSUE TITLE
Helm 3 binary for linux not available at standard location

### ISSUE THREAD

**Issue by pguimaraes** [helm/helm#6993]
The Helm 2 binary for linux can be downloaded with the command below:

% curl -I https://storage.googleapis.com/kubernetes-helm/helm-v2.16.1-linux-amd64.tar.gz
HTTP/1.1 200 OK
...

But the Helm 3 binary for linux is not available at the same location, as you can see below:

% curl -I https://storage.googleapis.com/kubernetes-helm/helm-v3.0.0-linux-amd64.tar.gz
HTTP/1.1 404 Not Found
...

Has the URL for downloading Helm binaries changed for Helm 3?

**Comment by bacongobbler** [comment]
https://helm.sh/blog/get-helm-sh/#where-are-we-now

**Comment by bacongobbler** [comment]
New download link is https://get.helm.sh/helm-v3.0.0-linux-amd64.tar.gz. Helm 2 downloads can also be fetched from there, reaching all the way back to 2.0.0-alpha.1.

**Comment by pguimaraes** [comment]
Thank you!
