### ISSUE TITLE
go get "helm.sh/helm/v3/pkg/chart" returns invalid version error

### ISSUE THREAD

**Issue by jakkaj** [helm/helm#6994]
I'm attempting to consume the "helm.sh/helm/v3/pkg/chartutil" from my go project and receiving an error:

`"github.com/docker/docker@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000"`

Output from go version `go version go1.13.1 linux/amd64`

Full command output:

```
go get "helm.sh/helm/v3/pkg/chart"
go get: helm.sh/helm/v3@v3.0.0 requires
        github.com/deislabs/oras@v0.7.0 requires
        github.com/docker/docker@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

Have replicated this across two computers. 

Any pointers?

**Comment by fengxsong** [comment]
`replace github.com/docker/docker => github.com/moby/moby v0.7.3-0.20190826074503-38ab9da00309`

**Comment by jakkaj** [comment]
That worked - thank you very much!

**Comment by zeusro** [comment]
replace (
	github.com/docker/distribution => github.com/distribution/distribution v2.7.1+incompatible
	github.com/docker/docker => github.com/moby/moby v0.7.3-0.20190826074503-38ab9da00309

)
