### ISSUE TITLE
[helm3]  helm3 ls -o json ,return without "next" or "total" field.

### ISSUE THREAD

**Issue by magicLian** [helm/helm#6995]
`helm3 ls -o json ` return has no field "next" or "total"

but helm2 ls --output json has.

**Comment by bacongobbler** [comment]
Helm 2 relied on the gRPC API, so the results were paginated. In Helm 3, the results come directly from the Kubernetes API and require no pagination.

related: #6801

**Comment by hickeyma** [comment]
Closing as answered.
