### ISSUE TITLE
helm init is not recognized

### ISSUE THREAD

**Issue by prashanthh** [helm/helm#6996]
Output of `helm version`:
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:20:58Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Kubeadm install on Centos 7. 

On my mac 10.13.6, tried installing help using brew, then using binary. Also, tried the binary install on a Linux client. Helm init gives the same response on all, as if the 'init' is unrecognised. 

$ helm init
The Kubernetes package manager

Common actions for Helm:

- helm search:    search for charts
- helm pull:      download a chart to your local directory to view
- helm install:   upload the chart to Kubernetes
- helm list:      list releases of charts

Environment variables:

+------------------+-----------------------------------------------------------------------------+
| Name             | Description                                                                 |
+------------------+-----------------------------------------------------------------------------+
| $XDG_CACHE_HOME  | set an alternative location for storing cached files.                       |
| $XDG_CONFIG_HOME | set an alternative location for storing Helm configuration.                 |
| $XDG_DATA_HOME   | set an alternative location for storing Helm data.                          |
| $HELM_DRIVER     | set the backend storage driver. Values are: configmap, secret, memory       |
| $HELM_NO_PLUGINS | disable plugins. Set HELM_NO_PLUGINS=1 to disable plugins.                  |
| $KUBECONFIG      | set an alternative Kubernetes configuration file (default "~/.kube/config") |
+------------------+-----------------------------------------------------------------------------+

Helm stores configuration based on the XDG base directory specification, so

- cached files are stored in $XDG_CACHE_HOME/helm
- configuration is stored in $XDG_CONFIG_HOME/helm
- data is stored in $XDG_DATA_HOME/helm

By default, the default directories depend on the Operating System. The defaults are listed below:

+------------------+---------------------------+--------------------------------+-------------------------+
| Operating System | Cache Path                | Configuration Path             | Data Path               |
+------------------+---------------------------+--------------------------------+-------------------------+
| Linux            | $HOME/.cache/helm         | $HOME/.config/helm             | $HOME/.local/share/helm |
| macOS            | $HOME/Library/Caches/helm | $HOME/Library/Preferences/helm | $HOME/Library/helm      |
| Windows          | %TEMP%\helm               | %APPDATA%\helm                 | %APPDATA%\helm          |
+------------------+---------------------------+--------------------------------+-------------------------+

Usage:
  helm [command]

Available Commands:
  completion  Generate autocompletions script for the specified shell (bash or zsh)
  create      create a new chart with the given name
  dependency  manage a chart's dependencies
  env         Helm client environment information
  get         download extended information of a named release
  help        Help about any command
  history     fetch release history
  install     install a chart
  lint        examines a chart for possible issues
  list        list releases
  package     package a chart directory into a chart archive
  plugin      install, list, or uninstall Helm plugins
  pull        download a chart from a repository and (optionally) unpack it in local directory
  repo        add, list, remove, update, and index chart repositories
  rollback    roll back a release to a previous revision
  search      search for a keyword in charts
  show        show information of a chart
  status      displays the status of the named release
  template    locally render templates
  test        run tests for a release
  uninstall   uninstall a release
  upgrade     upgrade a release
  verify      verify that a chart at the given path has been signed and is valid
  version     print the client version information

Flags:
      --add-dir-header                   If true, adds the file directory to the header
      --alsologtostderr                  log to standard error as well as files
      --debug                            enable verbose output
  -h, --help                             help for helm
      --kube-context string              name of the kubeconfig context to use
      --kubeconfig string                path to the kubeconfig file
      --log-backtrace-at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log-dir string                   If non-empty, write log files in this directory
      --log-file string                  If non-empty, use this log file
      --log-file-max-size uint           Defines the maximum size a log file can grow to. Unit is megabytes. If the value is 0, the maximum file size is unlimited. (default 1800)
      --logtostderr                      log to standard error instead of files (default true)
  -n, --namespace string                 namespace scope for this request
      --registry-config string           path to the registry config file (default "/Users/prXX/Library/Preferences/helm/registry.json")
      --repository-cache string          path to the file containing cached repository indexes (default "/Users/prXX/Library/Caches/helm/repository")
      --repository-config string         path to the file containing repository names and URLs (default "/Users/prXX/Library/Preferences/helm/repositories.yaml")
      --skip-headers                     If true, avoid header prefixes in the log messages
      --skip-log-headers                 If true, avoid headers when opening log files
      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
  -v, --v Level                          number for the log level verbosity
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging

Use "helm [command] --help" for more information about a command.

**Comment by marckhouzam** [comment]
Helm init has been removed from helm 3.0 :-). You don't need it anymore. There is no more Tiller and the client directories are initialised automatically when you start using helm.

**Comment by jgschmitz** [comment]
I get that it has been removed by when I do a helm list I got no charts listed

**Comment by bacongobbler** [comment]
did you install those charts into a namespace other than `default` or what your current kube context is pointing at?

You can use `helm list --namespace foo` to list charts installed in that particular namespace, and `helm list --all-namespaces` to get a global view of the cluster (assuming you have cluster admin privileges).

More info here: https://helm.sh/docs/faq/#release-names-are-now-scoped-to-the-namespace

**Comment by malinich** [comment]
> don't need it anymore.

In official site need update documentation, use the _helm init_ there.(

**Comment by bacongobbler** [comment]
Can you point out where it’s listed in the docs? We can make edits to that section if necessary. Thanks.

**Comment by zackbrown** [comment]
Just bumped myself on this too; here's where `init` is listed in the docs signifying it's part of 3.x  https://helm.sh/docs/helm/helm_init/ (found via the left-nav under `Helm Commands`)

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/2100885/73777174-daf09b00-473d-11ea-8127-7cde4f0cf864.png">

**Comment by bacongobbler** [comment]
thanks. We'll go ahead and remove that from the documentation.

**Comment by zackbrown** [comment]
Hey @bacongobbler I went ahead and tried my hand at a PR to resolve this: https://github.com/helm/helm-www/pull/484

Hopefully crossed all the `t`s, no worries if this needs to be resolved differently.

**Comment by bacongobbler** [comment]
Thanks @zackbrown. I went ahead and re-generated the whole documentation for the helm commands in helm/helm-www#485. There's a few more spots that were missing.

**Comment by inallib** [comment]
there are more docs talks about the `helm init` and **Tiller**

**Comment by bacongobbler** [comment]
That is the Helm 2 documentation.
