### ISSUE TITLE
Support reading values from STDIN for `upgrade` command

### ISSUE THREAD

**Issue by brew** [helm/helm#7002]
#2709 introduced support for using STDIN with the "-" character for `install`. However, I don't think this works with the `upgrade` command. 

My example usecase is decrypting a sops file and using the output in the `helm upgrade` command:

```sh
# I can do this and values in secrets.sops.yaml are available to the release:
sops -d secrets.sops.yaml | helm install -f - -f values.yaml my-release release/my-chart 

# but this doesn't work:
sops -d secrets.sops.yaml | helm upgrade -f - -f values.yaml my-release release/my-chart 
```

**Comment by giggio** [comment]
This used to work for `help upgrade` on Helm 2. I'm upgrading to v3, and it seems it does not work anymore.

**Comment by giggio** [comment]
Upaste: reading from stdin works, but only it is an upgrade. If it is a first install (with `upgrade --install`) it seems to not work.

I did this in the mean time:

````bash
INSTALL_ACTION='install'
if [ "$(helm list --namespace=$ns --filter=$name -q)" == "$name" ]; then
  INSTALL_ACTION='upgrade --install'
fi
cat <<EOF | helm $INSTALL_ACTION $name $chart --namespace $ns --version $VERSION --wait --values -
...
EOF
````

**Comment by stefansedich** [comment]
Bit by this too, thanks @giggio will try out your solution to get us by, was interesting as the install just worked tooked me a bit to figure things out.

**Comment by matti** [comment]
my workaround:
```
    if [ "$(helm list --filter=ingress -q)" = "" ]; then
      printf "$values" | helm install --values - ingress stable/nginx-ingress
    else
      printf "$values" | helm upgrade --values - ingress stable/nginx-ingress
    fi
```

**Comment by gungorugur** [comment]
+1

It works with "helm install --values -" or "helm install --values -" but not works with "helm upgrade --install"

Helm version:
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

**Comment by yinzara** [comment]
Confirmed. This breaks our current build process with Helm 3.

**Comment by yinzara** [comment]
This will be fixed when we get a release after #7640 is merged

**Comment by vitaliy-zinchenko** [comment]
Tested on versions 3.2.4 and 3.3.0-rc.1 and still see this issue.

**Comment by yinzara** [comment]
Please provide reproduction steps. The PR includes test cases that pass related to this functionality.

**Comment by thavlik** [comment]
For all concerned, I can confirm this feature is now working at least as of v3.12.2
