### ISSUE TITLE
Distribute Helm as a Debian/Fedora package

### ISSUE THREAD

**Issue by remcohaszing** [helm/helm#7003]
In the Helm [faq](https://helm.sh/docs/faq/#why-aren-t-there-debian-fedora-native-packages-of-helm) is stated:

> ### Why aren’t there Debian/Fedora/… native packages of Helm?
>
> We’d love to provide these or point you toward a trusted provider. If you’re interested in helping, we’d love it. This is how the Homebrew formula was started.

Why not ask if Google wants to include Helm as part of their Google Cloud SDK? As documented in their [installation options](https://cloud.google.com/sdk/install#installation_options), they already support `apt-get` and `yum`. I would love to just simply `apt-get install helm` instead of grabbing every release from GitHub. For example `kubectl` can also be installed this way.

**Comment by bacongobbler** [comment]
I'm confused. Is this an ask for a debian repository that can be consumed with apt, or for this to be included in the Google Cloud SDK?

The former is something we can do, and I believe there may be a similar ticket that was opened long ago. The latter is up to the Google Cloud SDK maintainers so there's nothing we can do on our end to fix that.

**Comment by remcohaszing** [comment]
The issue for me is I would like to have a trusted debian repository I could consume using apt.

Tools included by the Google Cloud SDK are also available through their apt and yum repositories. This would be a solution. This is also how `kubectl` and `skaffold` are available using apt. ([kubectl installation instructions](https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-using-native-package-management))

I created an issue for the Google Cloud SDK as well [here](https://issuetracker.google.com/issues/144887164)

**Comment by mattfox** [comment]
I'd like to contribute Deb and RPM packages for Helm.

There's two parts- building the package itself, and constructing the trusted repository that offers the package.

I can write up some basic scripts that make a Debian and RPM package containing the binaries offered at https://github.com/helm/helm/releases .

As for the repositories, these need to be structured in the proper format and then hosted somewhere. I'd like to contribute a service I'm building (https://www.getbalto.com/) that will sign and structure the repositories and offer a friendly frontend (think the idea behind packages.debian.org). For hosting the repository and package files, is it possible to host them at get.helm.sh where the existing files are already offered? This would probably be the easiest in terms of minimal maintenance and offering the same speed, reliability, and cost as the current situation.

There are a few issues that would need decisions. All these choices could be changed later.

1. Where to build the packages. Is there a preferred CI environment? Or should I provide something?
1. Where should the package building scripts live? I'd recommend in this repo with the Helm source, but that's not required.
1. Is there demand for repositories that offer release candidate builds?

**Comment by mattfarina** [comment]
I noted this on the Helm dev call today... I think the Helm project should only take on the packaging scripts and operation of a repo if the current maintainers are interested in doing that and feel capable of it. Otherwise, I would suggest a 3rd party handle the scripts and operation of the repository and the Helm docs point to this 3rd party. When issues come up with it the Helm project can point people to the 3rd parties code and issue queue where people who have direct control can handle it.

If no current helm maintainers emerge we could handle things in a similar way to the way we handle Homebrew today.

**Comment by mattfox** [comment]
No current Helm maintainers have emerged so I've prepared Debian packages for Helm 3 and 2 at https://helm.baltorepo.com/stable/debian/, and updated the installation documentation in PRs referenced above.

My simple packaging scripts are at https://github.com/BaltoRepo/helm-linux-packages, and at the moment I'll plan to stay notified of new Helm releases by Github notifications and update packages manually.

This issue probably can't be closed, as I haven't provided Fedora packages yet, but I'll plan to do that some time in the future.
