### ISSUE TITLE
Add custom labels to helmv3 release secret

### ISSUE THREAD

**Issue by ggarson** [helm/helm#7007]
Hello,

Is there a way to add a specific label to the helm release secret created by Helmv3 ? I read all the docs and browsed issued without success.

My use case is really simple, I use Velero to backup all my stuff, project by project (1 project = 1 helm deployment), every day according specific labels. If I can add specific labels, I can backup helm information at the same time.

I can do a workaround with a hook I know but I thing that feature could be useful for others.

**Comment by ramrodo** [comment]
Hi @ggarson,

I'm facing the same problem and it looks like this feature will take a while to be included.

I'm interested in the workaround you mention. How it could look like? It could be great to have this workaround for anyone who is facing this problem too.

**Comment by ggarson** [comment]
Hi,

I noticed #8532 that added the support of helm list with specific label selector but I didn't find a way to add "this" label as I asked here. 

@liuming-dev's PR is not merged and validated yet if i'm correct.

**Comment by ggarson** [comment]
> Hi @ggarson,
> 
> I'm facing the same problem and it looks like this feature will take a while to be included.
> 
> I'm interested in the workaround you mention. How it could look like? It could be great to have this workaround for anyone who is facing this problem too.

@ramrodo Sorry for the huge delay, you can probably do it with helm hook in a job. I did it globally in my case with a cronjob waiting for that feature.

**Comment by lawliet89** [comment]
Not stale. Also facing this issue.

**Comment by lawliet89** [comment]
Still relevant.

**Comment by ggarson** [comment]
There were lot of PR but if I'm not wrong still relevant.

**Comment by ThomasSteinbach** [comment]
Not stale, sill relevant. Else Helm metadata is not included in label selected velero backups.

**Comment by artemkoru** [comment]
Still relevant.

**Comment by dm3ch** [comment]
FYI: I just created new PR with the implementation of this functionality - https://github.com/helm/helm/pull/10533

Actually, it's a 4th PR with this functionality. But I hope at least this one would be merged?

**Comment by jeremysprofile** [comment]
Not stale, sill relevant.

**Comment by inveon-muhammedkahrimanoglu** [comment]
Any progress? I need this feature.

**Comment by m18unet** [comment]
Any progress? I need this feature.

**Comment by dm3ch** [comment]
Still waiting for review of https://github.com/helm/helm/pull/10533 by maintainers.  :(

**Comment by jeremysprofile** [comment]
not stale, still relevant

**Comment by atcvetkov** [comment]
we also need this option!

**Comment by killwing** [comment]
also need custom annotations

**Comment by joejulian** [comment]
Folks, if you've come down this far just to say "me too", please just add your :+1: to the initial description instead. Thanks!

**Comment by yxxhero** [comment]
@dm3ch adding labels support for the tempalte subcommand will be better.

**Comment by dm3ch** [comment]
> @dm3ch adding labels support for the tempalte subcommand will be better.

Sorry, I haven't understood what you mean.
The initial idea that was discussed here as far as I remember was labeling the helm releases and filtering them during listing.
So I don't understand how adding support of labeling in template command can help that (cause during helm template as far as I know release is not created, so It's not possible to label the release)

**Comment by yxxhero** [comment]
@dm3ch My mistake. sorry.
