### ISSUE TITLE
have play support used crd manage helm resource ?

### ISSUE THREAD

**Issue by swqmaven** [helm/helm#7011]
used crd replace helm cli manage resource?
found opensource project https://github.com/alauda/captain .
what's the community plan?

**Comment by bacongobbler** [comment]
Hi @swqmaven.

The [Helm 3 design proposals](https://github.com/helm/community/blob/master/helm-v3/008-controller.md) describe how the community could use Helm's Go client SDK to write a "Helm 3 controller". This is to accommodate use cases that relied on the Tiller model in Helm 2.

As per the document:

> However, defining the specifics of this controller was deemed outside of the scope of this proposal, which focuses on the reference implementation of the Helm CLI.

There are no plans to officially support something that resembles Tiller. We've shared information on how to build one should the community decide to build one themselves.

That being said, https://github.com/helm is set up to host other subprojects. chartmuseum and monocular started as external projects then was eventually moved under the Helm org. Should a project maintainer be interested in donating their project to the CNCF, we would be open to host it as a standalone project.

Hope this helps.
