### ISSUE TITLE
[helm3] doc error, wrong/duplicate link

### ISSUE THREAD

**Issue by SLepUbIn** [helm/helm#7015]
Go to https://helm.sh/docs/ for v3
At the bottom of the page in quicklinks, both "Deploying to Kubernetes" and "CI/CD for Kubernetes" point to the same destination  : https://daemonza.github.io/2017/02/20/using-helm-to-deploy-to-kubernetes
despite the latter being labeled as "via Hackernoon"

**Comment by karuppiah7890** [comment]
Thanks for reporting this! We need to move this issue to github.com/helm/helm-www repo though. That's the repo for docs for v3. And would you like to fix this issue? 😄

**Comment by SLepUbIn** [comment]
Ok, I opened the same issue there
https://github.com/helm/helm-www/issues/397

and issued a PR to fix the link 
https://github.com/helm/helm-www/pull/398

**Comment by karuppiah7890** [comment]
Awesome! Thanks! 😄 Then in that case, we can close this issue and track helm/helm-www#397
