### ISSUE TITLE
Helm 3 on OpenShift without cluster-admin?

### ISSUE THREAD

**Issue by bentterp** [helm/helm#7017]
Output of `helm version`:
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-01-14T00:24:11Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
OpenShift 
```
bent:/tmp$ oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://openshift.##################.com:443
openshift v3.11.69
kubernetes v1.11.0+d4cacc0
bent:/tmp$
```

Is Helm intended to be used without cluster-admin privs?
```
bent:/tmp$ helm create foo
Creating foo
bent:/tmp$ helm install foo --generate-name
Error: could not get apiVersions from Kubernetes: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: Unauthorized
bent:/tmp$
```

Is this is as intended and we need to reconfigure OpenShift for this, are there many RBAC changes required?

Debug output:
bent:/tmp$ helm install foo --generate-name --v 6 
I1119 12:10:46.040741    1406 round_trippers.go:443] GET https://openshift.###############.com:443/version?timeout=32s 200 OK in 147 milliseconds
I1119 12:10:46.118454    1406 round_trippers.go:443] GET https://openshift.###############.com:443/version?timeout=32s 200 OK in 33 milliseconds
I1119 12:10:46.152831    1406 round_trippers.go:443] GET https://openshift.###############.com:443/api?timeout=32s 200 OK in 33 milliseconds
I1119 12:10:46.187331    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis?timeout=32s 200 OK in 33 milliseconds
I1119 12:10:46.230824    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/authentication.k8s.io/v1?timeout=32s 200 OK in 32 milliseconds
I1119 12:10:46.231114    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/authorization.k8s.io/v1beta1?timeout=32s 200 OK in 33 milliseconds
I1119 12:10:46.231288    1406 round_trippers.go:443] GET https://openshift.###############.com:443/api/v1?timeout=32s 200 OK in 32 milliseconds
I1119 12:10:46.231514    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/quota.openshift.io/v1?timeout=32s 200 OK in 32 milliseconds
I1119 12:10:46.262075    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/project.openshift.io/v1?timeout=32s 200 OK in 63 milliseconds
I1119 12:10:46.262163    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/policy/v1beta1?timeout=32s 200 OK in 62 milliseconds
I1119 12:10:46.262643    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/servicecatalog.k8s.io/v1beta1?timeout=32s 200 OK in 64 milliseconds
I1119 12:10:46.263979    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/autoscaling/v2beta1?timeout=32s 200 OK in 64 milliseconds
I1119 12:10:46.265335    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/authorization.openshift.io/v1?timeout=32s 200 OK in 64 milliseconds
I1119 12:10:46.265606    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/batch/v1?timeout=32s 200 OK in 66 milliseconds
I1119 12:10:46.265668    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/autoscaling/v1?timeout=32s 200 OK in 65 milliseconds
I1119 12:10:46.265757    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/apiregistration.k8s.io/v1?timeout=32s 200 OK in 66 milliseconds
I1119 12:10:46.265894    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/apps/v1beta2?timeout=32s 200 OK in 67 milliseconds
I1119 12:10:46.265998    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/networking.k8s.io/v1?timeout=32s 200 OK in 67 milliseconds
I1119 12:10:46.266060    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/apps/v1beta1?timeout=32s 200 OK in 67 milliseconds
I1119 12:10:46.266114    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/apps.openshift.io/v1?timeout=32s 200 OK in 64 milliseconds
I1119 12:10:46.293372    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/events.k8s.io/v1beta1?timeout=32s 200 OK in 92 milliseconds
I1119 12:10:46.293739    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/apiregistration.k8s.io/v1beta1?timeout=32s 200 OK in 93 milliseconds
I1119 12:10:46.293956    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/authentication.k8s.io/v1beta1?timeout=32s 200 OK in 94 milliseconds
I1119 12:10:46.294023    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/scheduling.k8s.io/v1beta1?timeout=32s 200 OK in 93 milliseconds
I1119 12:10:46.294196    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/batch/v1beta1?timeout=32s 200 OK in 95 milliseconds
I1119 12:10:46.294502    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/extensions/v1beta1?timeout=32s 200 OK in 93 milliseconds
I1119 12:10:46.296632    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/build.openshift.io/v1?timeout=32s 200 OK in 95 milliseconds
I1119 12:10:46.297622    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/apps/v1?timeout=32s 200 OK in 96 milliseconds
I1119 12:10:46.297703    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/automationbroker.io/v1alpha1?timeout=32s 200 OK in 96 milliseconds
I1119 12:10:46.297757    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/oauth.openshift.io/v1?timeout=32s 200 OK in 95 milliseconds
I1119 12:10:46.297808    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/rbac.authorization.k8s.io/v1?timeout=32s 200 OK in 95 milliseconds
I1119 12:10:46.297935    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/certificates.k8s.io/v1beta1?timeout=32s 200 OK in 97 milliseconds
I1119 12:10:46.298007    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/authorization.k8s.io/v1?timeout=32s 200 OK in 97 milliseconds
I1119 12:10:46.325007    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/storage.k8s.io/v1?timeout=32s 200 OK in 123 milliseconds
I1119 12:10:46.325106    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/image.openshift.io/v1?timeout=32s 200 OK in 122 milliseconds
I1119 12:10:46.326108    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/pxc.percona.com/v1alpha1?timeout=32s 200 OK in 122 milliseconds
I1119 12:10:46.326193    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/network.openshift.io/v1?timeout=32s 200 OK in 124 milliseconds
I1119 12:10:46.326267    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/apiextensions.k8s.io/v1beta1?timeout=32s 200 OK in 123 milliseconds
I1119 12:10:46.327027    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/mysql.presslabs.org/v1alpha1?timeout=32s 200 OK in 123 milliseconds
I1119 12:10:46.328203    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/flux.codesink.net/v1alpha1?timeout=32s 200 OK in 125 milliseconds
I1119 12:10:46.328287    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/user.openshift.io/v1?timeout=32s 200 OK in 124 milliseconds
I1119 12:10:46.329694    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/security.openshift.io/v1?timeout=32s 200 OK in 126 milliseconds
I1119 12:10:46.326330    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/admissionregistration.k8s.io/v1beta1?timeout=32s 200 OK in 123 milliseconds
I1119 12:10:46.326395    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/route.openshift.io/v1?timeout=32s 200 OK in 124 milliseconds
I1119 12:10:46.326449    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/storage.k8s.io/v1beta1?timeout=32s 200 OK in 124 milliseconds
I1119 12:10:46.330464    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/rbac.authorization.k8s.io/v1beta1?timeout=32s 200 OK in 128 milliseconds
I1119 12:10:46.330541    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/metrics.k8s.io/v1beta1?timeout=32s 401 Unauthorized in 127 milliseconds
I1119 12:10:46.330608    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/template.openshift.io/v1?timeout=32s 200 OK in 127 milliseconds
I1119 12:10:46.330664    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/comcast.github.io/v1?timeout=32s 200 OK in 127 milliseconds
I1119 12:10:46.330717    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/pxc.percona.com/v1?timeout=32s 200 OK in 126 milliseconds
I1119 12:10:46.330819    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/helm.integrations.flux.weave.works/v1alpha2?timeout=32s 200 OK in 127 milliseconds
I1119 12:10:46.331827    1406 round_trippers.go:443] GET https://openshift.###############.com:443/apis/monitoring.coreos.com/v1?timeout=32s 200 OK in 127 milliseconds
I1119 12:10:46.336956    1406 cached_discovery.go:78] skipped caching discovery info due to Unauthorized
Error: could not get apiVersions from Kubernetes: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: Unauthorized
bent:/tmp$

**Comment by bacongobbler** [comment]
In the future, you may refer to the documentation on role-based access control: https://helm.sh/docs/topics/rbac/

#6908 should fix the issue referenced here, and it will be available in 3.1.0. Closing!
