### ISSUE TITLE
Symlinks produce noise in templated output

### ISSUE THREAD

**Issue by asthasr** [helm/helm#7019]
Output of `helm version`: ```version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}```

I am wanting to use a local library chart without needing to do `helm dependency update`. I have a structure like this:

```
overall-concern/
  charts/
    cloudformation-chart/
    kubernetes-chart/
    shared-library/
```

I can put a symlink to `shared-library` in `cloudformation-chart/charts`, but when I run helm template it has what seems like either debugging output or an unclear deprecation warning:

```
walk.go:74: found symbolic link in path: ... (paths elided) ...
```

It was introduced by [this commit](https://github.com/helm/helm/commit/5a7d4f1f748afcbe9c714c1ce35cef7395a157f8#diff-5bd89f2e733a8bb8d60a9cb4947cf0f0R74). Should this output be removed? Should it be an error? If the latter, is there an "official" solution to my use case?

**Comment by karuppiah7890** [comment]
I think the symbolic link output is to prevent any security issues, check this - https://helm.sh/blog/2019-10-30-helm-symlink-security-notice/ . 

And could you tell what's the use case? Why not use `helm dependency update` ? 🤔

**Comment by asthasr** [comment]
The output is still generated from `helm template`, it just has the error message in `stdout`, so it's not preventing security issues.

The use case is that I have two charts that share a third chart, the `shared-library` in the structure above.

If I use `helm dependency update` on each one, then if I edit `shared-library` (which will only ever be internally available, never published), it "vendors" the thing into each of the other charts, as `charts/shared-library-chart-0.1.0.tgz`. Thus, every change I make to that shared library requires two commands to update it in each of the other charts.

It also raises the question of whether to check the archive into git. If I check it in, then it runs the risk of becoming stale in one or the other, not to mention simply duplicating the content that's already checked in as the chart itself. If I don't check it in, then every new checkout requires two more `helm dependency update` commands.

**Comment by bacongobbler** [comment]
We should probably display that error message on stderr so the output can be filtered through a pipe.

**Comment by asthasr** [comment]
It's now actually displaying on `stderr`, and isn't showing up when I pipe it through `less` or `pbcopy`. I'm not sure what the difference is, as my installed version of `helm` hasn't changed. I _have_ restarted my shells; could it have been configuration that was not picked up when I upgraded from Helm 2 to 3 and still had shells open? In any case, given that it's filterable now, I will close this issue and, given the lack of other blessed solutions, will continue to use the symlink strategy.

**Comment by woodcockjosh** [comment]
To ignore the stderr
```bash
helm install myrelease . 2>/dev/null
```

**Comment by tmshort** [comment]
This should really be considered a bug. Using symlinks shouldn't be considered an error or a warning. And you don't want to dump stderr to /dev/null, or you'll potentially lose real errors.

**Comment by bacongobbler** [comment]
To clarify, we had the Helm codebase undergo a security audit by Cure53, sponsored by the CNCF. The end result of that audit was that this IS considered a warning and it should be reported to the user, as an attacker can use this feature to trigger a DOS. This was intentionally put in place to mitigate that security issue.

You can read up on the report here (page 12 for the report on HLM-01-001): https://github.com/helm/community/blob/master/security-audit/HLM-01-report.pdf

**Comment by tmshort** [comment]
That is what I meant by "I understand the blog post". If we know our charts are referencing good content; it would be nice to be able to suppress this warning.
