### ISSUE TITLE
Regression for numeric Value type in Helm v3.0 breaking templates

### ISSUE THREAD

**Issue by OskarFromSpain** [helm/helm#7023]
Output of `helm version`:
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}

Output of `kubectl version`:
server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
OnPremise Kubernetes-Cluster

Hello everybody,
it seems, that this bug (https://github.com/helm/helm/issues/6708) is also available in helm v3.

Trying to install Redis from the hub.helm.sh with the chart version 9.5.0 (https://hub.helm.sh/charts/bitnami/redis)

The securityContext-Values hasn´t been changed.

error-message:
prod-redis                                                       failed to install chart release [prod-redis]: template: redis/templates/redis-slave-statefulset.yaml:87:18: executing "redis/templates/redis-slave-statefulset.yaml" at <eq .Values.securityContext.runAsUser 0.0>: error calling eq: incompatible types for comparison   31m

best Regards
OskarFromSpain

**Comment by rgl** [comment]
This is also happening to me, it seems https://github.com/helm/helm/issues/6708 also exists in helm 3:

```
Error: template: rancher/templates/deployment.yaml:76:7: executing "rancher/templates/deployment.yaml" at <gt .Values.auditLog.level 0.0>: error calling gt: incompatible types for comparison
```

Happens when installing with:

```
rancher_helm_chart_version="2.3.3"
rancher_server_domain="server.rancher.test"
kubectl create namespace cattle-system
helm install \
    rancher \
    rancher/rancher \
    --namespace cattle-system \
    --version $rancher_helm_chart_version \
    --set "hostname=$rancher_server_domain" \
    --set ingress.tls.source=secret \
    --set privateCA=true \
    --set auditLog.level=3 \
    --set replicas=1
```

**Comment by patvdleer** [comment]
Can confirm:

```
$ helm version
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}

$ kubectl version
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"clean", BuildDate:"2019-12-04T07:33:18Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

```
err 1: failed processing release redis: helm exited with status 1:
  Error: template: redis/templates/redis-slave-statefulset.yaml:87:18: executing "redis/templates/redis-slave-statefulset.yaml" at <eq .Values.securityContext.runAsUser 0.0>: error calling eq: incompatible types for comparison
```

**Comment by pevers** [comment]
I tried to come up with a fix @carrodher: https://github.com/helm/charts/pull/19832

**Comment by bacongobbler** [comment]
closing as stale.
