### ISSUE TITLE
Helm: tiller: command not found

### ISSUE THREAD

**Issue by ganeshmuralidhar** [helm/helm#7029]
Output of `helm version`: 
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:34Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.10-eks-7f15cc", GitCommit:"7f15ccb4e58f112866f7ddcfebf563f199558488", GitTreeState:"clean", BuildDate:"2019-08-19T17:46:02Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS EKS

 I just followed all the steps provided by AWS on their 'Using Helm with Amazon EKS' doc and could not proceed with Helm. Steps followed:

Step 1. brew install aws-iam-authenticator
Step 2. aws eks --region <region> update-kubeconfig --name <cluster_name>
Step 3: kubectl get svc (to validate the access and I can see the services on my cluster)
Step 4: brew install kubernetes-helm
Step 5: kubectl create namespace tiller
Step 6: export TILLER_NAMESPACE=tiller
Step 7: tiller -listen=localhost:44134 -storage=secret -logtostderr
This step 7 throws an error "-bash: tiller: command not found"
Also, any commands that I run like 'helm init' gives me a help usage documentation and doesn't show me any traces of helm initiation.

Note: All steps executed on my local mac

**Comment by bacongobbler** [comment]
Tiller was removed in helm 3. The documentation was written for helm 2. Please refer to https://helm.sh/docs/ for documentation on helm 3. Thanks!
