### ISSUE TITLE
Guidance on continuing a deploy with transient hook error

### ISSUE THREAD

**Issue by hlascelles** [helm/helm#7030]
Given a hook that is configured to perform, say, database migrations:

```
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
```

This usually works fine, and cleans the Job up after itself. However, if the migration fails transiently (DB connections run out or similar) the Job will retry a set number of times then cease. As far as I am aware there is no way to tell a Job that has reached its retry limit to start up again.

We could make the db migration retry forever, but that might cause problems. Let's imagine that we  were happy to have dev intervention to step in after the problem has been fixed, and we still have the failed Job. It would be best to have an action that the dev could take with minimal permissions.

What is the best practice in this situation? Is there a `helm` way to say "try again (delete that job and start a new one)", or "I've fixed it for you, you can delete that job and proceed with the upgrade", or do we revert to Kubernetes to "delete that job and create a clone" and if so does `helm` get confused? 

Output of `helm version`: Any latest builds at least 2.14 and up
Output of `kubectl version`: ANy recent version 1.13 and up
Cloud Provider/Platform (AKS, GKE, Minikube etc.): EKS, minikube, all etc...

**Comment by bacongobbler** [comment]
https://helm.sh/docs/topics/charts_hooks/#automatically-uninstall-hook-from-previous-release

**Comment by hlascelles** [comment]
OK, so, pushing though another deploy with that attribute enabled looks like it will work. In our scenario, that would mean adding a "foo" ENV to our Deployment so the deploy system "sees" it as a new version (we don't let devs perform `helm` commands like upgrade to the cluster directly). 

Great, thank you, that will work for us.
