### ISSUE TITLE
helm chart save --app-version?

### ISSUE THREAD

**Issue by mathieu-benoit** [helm/helm#7032]
I'm trying to replicate what's possible to do with `helm package --app-version` but with the new OCI experimental commands `helm chart save`. My understanding is that's not possible today, but is it possible to accomplish this at some point?

I'm finding https://github.com/helm/helm/pull/3196 very useful especially in a CI/CD pipeline where the `appVersion` doesn't reside in the `Chart.yaml` and has to be dynamically injected while building the chart package. There is maybe more flags to take into consideration which are available today via the `helm package -h` command too.

Alternatively, could we use first `helm package --app-version` and then use `helm chart save` with the generated `.tgz` file?

Note: I have also seen this thread https://github.com/helm/helm/pull/3196 where it's mentioned that adding `--app-version` while doing `helm install|updgrade` is not possible by design.

Thanks for any thought and guidance here.

- Output of `helm version`: 3.0.0
- Output of `kubectl version`: N/A
- Cloud Provider/Platform (AKS, GKE, Minikube etc.): N/A

**Comment by mathieu-benoit** [comment]
Otherwise, alternatively with the commands and options today, this flow could allow to achieve what I'm looking for:
```
# Push without appVersion notion:
helm chart push...

# Pull and deploy:
helm chart pull...
helm chart export...
helm package --appVersion...
helm upgrade|install...
```
I'm just wondering if that `helm package` could be avoided...

Thoughts?

**Comment by jdolitsky** [comment]
@mathieu-benoit I think it probably makes sense for several of the flags on `helm package` to make their way into `helm chart save`

**Comment by btwiuse** [comment]
You can use `helm chart save` to load the chart archive generated by `helm package`:
```
$ cd $CHART_DIR
$ export HELM_EXPERIMENTAL_OCI=1
$ helm chart save $(helm package --app-version demo --version 0.0.0 . | grep -o '/.*.tgz') chart:demo
$ helm chart list
```
and you'll see `chart:demo` in your local registry cache

**Comment by salanfe** [comment]
Hi all,
I'm successfully to pushing/pulling charts to/from GCR. Tags are also working fine 👍 
However could someone explain me what this local cache is all about ? Why do we need to `helm chart save` before being able to `helm chart push` ?

The pattern is obviously similar to docker, whereas
docker: build --> tag --> push
helm: save (with tag) --> push

but the naming, and workflow, is a bit misleading in my opinion. 

second question: why isn't helm chart able to list charts from the registry ? Luckily, `gcloud` can be used to achieve it, e.g.

```sh
gcloud container images list --repository="$GCR_PATH"
gcloud container images list-tags "$GCR_PATH"/my-helm-chart
```

Furthermore, I would expect `helm chart list` to read from the Registry, not this local cache. In the CI pipeline, this cache would be empty.

**Comment by fredgate** [comment]
The `--version` and `--appVersion` present in `helm package` command are missing a lot in `helm chart save` command.

**Comment by kinzleb** [comment]
> You can use `helm chart save` to load the chart archive generated by `helm package`:
> 
> ```
> $ cd $CHART_DIR
> $ export HELM_EXPERIMENTAL_OCI=1
> $ helm chart save $(helm package --app-version demo --version 0.0.0 . | grep -o '/.*.tgz') chart:demo
> $ helm chart list
> ```
> 
> and you'll see `chart:demo` in your local registry cache

This saved my butt, thanks!

**Comment by TBBle** [comment]
Based on https://github.com/helm/community/pull/136, `helm chart save` is likely to be going away. It's a misfeature that it works like `helm package` without the full feature set, the usage should probably have been limited to how @btwiuse showed it in https://github.com/helm/helm/issues/7032#issuecomment-625100794

> $ helm chart save $(helm package --app-version demo --version 0.0.0 . | grep -o '/.*.tgz') chart:demo

If the OCI cache is not removed (seems likely it will be) then `helm chart save` would be turend into `helm package --cache-oci`.
