### ISSUE TITLE
"helm install --description" flag not available

### ISSUE THREAD

**Issue by juanmatias** [helm/helm#7033]
Output of `helm version`:
`version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}`

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-eks-5876d6", GitCommit:"5876d6b7429820450950ade17fe7b4bf5ccada7f", GitTreeState:"clean", BuildDate:"2019-09-24T20:54:25Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
any of them

**Steps to reproduce the issue**
Just run:

`helm install ... --description "your description" ...`

**Actual behavior**
I get this error:
`Error: unknown flag: --description`

**Expected behavior**
As for Helm2 I need to add a description to my release.

**Additional**

I don't know if there is an equivalent flag on Helm 3. I couldn't find anything on the internet.

If there is a command to add description please let me know. If there is not, isn't it a desirable feature?

Thanks.

**Comment by bacongobbler** [comment]
It shouldn't be all that difficult to port https://github.com/helm/helm/pull/3825 over to Helm 3. Feel like taking this one on?

**Comment by juanmatias** [comment]
@bacongobbler I can give it a try... I'm not a go developer but I have the will... so, any advice is welcome.

**Comment by bacongobbler** [comment]
The developer guide should be a helpful resource. https://helm.sh/docs/community/developers/

Let us know how you get along.

**Comment by juanmatias** [comment]
Ok, I did it, added flag to install, upgrade and delete.

Hope it is ok. :)
