### ISSUE TITLE
[helm 3]Misleading documents about local chart repository

### ISSUE THREAD

**Issue by randmonkey** [helm/helm#7039]
In helm3, `helm serve` command is already removed, but the documents for helm3 is still talking about using `helm serve` to start a local server for a chart repository, which is misleading.  
Open this page https://helm.sh/docs/topics/chart_repository/  and search for `helm serve`, contents about using `helm serve` is stiil there.
In my thought, those misleading parts should be deleted. Maybe a paragraph about using `chartmuseum` could be added.

**Comment by bridgetkromhout** [comment]
Thanks, @randmonkey! This was resolved in https://github.com/helm/helm-www/pull/453.
