### ISSUE TITLE
Helm 2 - Helm requirement dependencies are loaded before condition is evaluated

### ISSUE THREAD

**Issue by patrickc91** [helm/helm#7044]
This is a duplicate of a stale issue from 2018 (#3386) , but there was never any resolution.

In Helm 2.16.1 any dependencies listed in the `requirements.yaml` are required to be downloaded, even if the dependency's conditional value is false.

We currently use a single chart for the following environments: local dev, AKS Dev and AKS Prod.
In the AKS environments our dependencies are not required, as we have external DBs and Redis instances. But for local dev, we want those DBs and Redis instances created locally.

As it is, when deploying on AKS with charts, we are required to download dependencies that will never be used. It would be extremely useful if conditional statements were evaluated before requiring the chart to download dependencies.

Is this true of Helm 3? Or is it only handled this way in Helm 2?

Output of `helm version`: v2.16.1

Output of `kubectl version`: 1.14

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS and Docker for Mac/Windows

**Comment by patrickc91** [comment]
I've upgraded to Helm 3 to see if requirements still have to be downloaded, even if the requirement is disabled. Sadly, this is still the case.

I don't know about everyone else, but I think if a requirement isn't enabled, then it shouldn't need to be downloaded. It would go a long way with multi environment deployments.

**Comment by vazhem** [comment]
should be a bug. Still relevant for Helm 3. Very annoying.
If requirements.yaml has a condition for specific dependency - the dependency should not be checked in charts/ folder.

**Comment by bacongobbler** [comment]
can you demonstrate an example that exemplifies the bug? That way we have a case to test against and verify. Thanks.

**Comment by vazhem** [comment]
requirements.yaml
{code}
dependencies:
  - name: doesnotexist
    repository: "file://../doesnotexist"
    condition: nevertrue
    version: 0.0.1
{code}

helm install test ./test  --dry-run --debug
{code}
install.go:148: [debug] Original chart version: ""
install.go:165: [debug] CHART PATH: mypath

Error: found in Chart.yaml, but missing in charts/ directory: doesnotexist
helm.go:76: [debug] found in Chart.yaml, but missing in charts/ directory: doesnotexist
helm.sh/helm/v3/pkg/action.CheckDependencies
	/home/circleci/helm.sh/helm/pkg/action/install.go:608
main.runInstall
	/home/circleci/helm.sh/helm/cmd/helm/install.go:188
main.newInstallCmd.func1
	/home/circleci/helm.sh/helm/cmd/helm/install.go:115
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:75
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357
{code}

**Comment by bacongobbler** [comment]
As I understand it, the design of the `condition` flag was not to determine if the dependency should be included or not in the chart when being packaged, but whether or not it should be rendered. The chart still has to be present regardless of the condition's output.

Of course, that could be changed, but hopefully that provides some more context around how this flag was designed.

Note that I am only trying to relay this information as best as I can remember; the maintainer who originally worked on the dependency subsystem stepped down a few years ago.

**Comment by bacongobbler** [comment]
re-labelling as a feature.

**Comment by vazhem** [comment]
Thanks, I understand that if all charts are in some public repo - it is not a big problem.
When charts for different subsystem reside in different private repos worked by different teams - it makes much more sense for 'condition' to mean not only 'not render' but also 'not expect to be available'.

**Comment by bacongobbler** [comment]
closing as stale.
