### ISSUE TITLE
no created key in application/vnd.cncf.helm.config.v1+json media type

### ISSUE THREAD

**Issue by hswimelar** [helm/helm#7046]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

We're encountering an [issue](https://gitlab.com/gitlab-org/gitlab/issues/30669) which is partially caused by the absence of a `created` key/value pair in the configs of helm charts pushed to our container registry. 

Is this the expected behavior and if so, would there be be a way to include this metadata in a future release?

For reference, here's an example of a helm chart config generated by the reproducer steps in the linked issue:

```
{
  "name": "foo",
  "version": "0.1.0",
  "description": "A Helm chart for Kubernetes",
  "apiVersion": "v2",
  "appVersion": "1.16.0",
  "type": "application"
}
````

**Comment by bacongobbler** [comment]
As far as I understand [the distribution spec](https://github.com/opencontainers/distribution-spec/blob/master/spec.md), it is not required for a media type to contain a `created` key/value pair in the manifest.

Reading through [the distribution source code](https://github.com/docker/distribution/blob/749f6afb4572201e3c37325d0ffedb6f32be8950/manifest/schema2/builder_test.go#L107), this looks like an implementation detail of Docker's "image layer" media type, AKA `application/vnd.docker.image.rootfs.diff.tar.gzip`. It's not a required field as per the distribution spec.

For what it's worth, `helm chart push` works great against an OCI registry that complies with the distribution spec (`docker/distribution`).

cc @jdolitsky as he may possibly have more context around this particular field.

**Comment by hswimelar** [comment]
Thanks @bacongobbler!

For what it's worth, our registry does fine with helm OCI images, but right now that metadata is expected by and useful to the GitLab app. I figured it might also be useful to other's people's projects.

**Comment by jdolitsky** [comment]
@hswimelar when you have a moment, can you share a sample of metadata that is valid w/ GitLab?

We're trying to closely follow the OCI spec, and not necessarily using all the same metadata and fields as a typical "docker push" would.

**Comment by hswimelar** [comment]
@jdolitsky We're discussing supporting helm charts (and OCI images) more broadly issue here, but we haven't settled on a solution yet: https://gitlab.com/groups/gitlab-org/-/epics/2281

Right now though, it looks like we access, `digest`, `blobSum`, `mediaType`, `size`, and `created`:
```
lib/container_registry/blob.rb:      config['digest'] || config['blobSum']
lib/container_registry/blob.rb:      config['mediaType']
lib/container_registry/blob.rb:      config['size']
lib/container_registry/tag.rb:        DateTime.rfc3339(config['created'])
```
