### ISSUE TITLE
[helm3] bug with JSON schema when using subcharts

### ISSUE THREAD

**Issue by sco11morgan** [helm/helm#7048]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

We have a subchart specifying required fields in its JSON schema.  The parent chart supplies all the required values but the subchart still fails both linting and templating.

This is not the expect behaviour given the [docs](https://v3.helm.sh/docs/topics/charts/#schema-files):

>  if a subchart has a requirement that is not met in the subchart’s values.yaml file, the parent chart must satisfy those restrictions in order to be valid.

example: https://github.com/sco11morgan/helm-schema-bug

**Comment by karuppiah7890** [comment]
@sco11morgan When giving values to sub charts, you need to use the sub chart's alias or name (if alias is not there) as a key and then provide the values within that. In your case, this line

https://github.com/sco11morgan/helm-schema-bug/blob/master/parent/values.yaml#L1

should become:

```
sub:
  color: red
```

I tried it out and it works. We can close this issue. Thanks for reporting though! We never know about any possible weird bugs until users report to us. Keep the bug reports and weird issues coming! 😄

**Comment by sco11morgan** [comment]
I see.  That makes sense, just doesn't work for me use case (trying to define a subchart that can be shared across multiple applications.  With the subchart having a schema with a list of required fields.) Looks like I'm not the only one trying to figure this out.  https://github.com/helm/helm/issues/6699#issuecomment-557556368

**Comment by apanagiotou** [comment]
Hey @sco11morgan. Have you managed to make schema work across charts? I have a similar case where I have a library chart that other charts use as a dependency. I want to have some validations inside the library chart so I've put the `values.schema.json` file in it but the validation doesn't work when trying to install the service charts.

**Comment by adberger** [comment]
@apanagiotou Could you solve this problem? I still experience this issue (on Helm v3.6.3)
@bacongobbler Should I open a new issue or can this issue be reopened?
