### ISSUE TITLE
helm list with short option -A does not list releases in all namespaces.

### ISSUE THREAD

**Issue by mojochao** [helm/helm#7049]
When running the `helm list --help` command, the output does not show the `--all-namespaces` long option as having the `-A` short option, even though it seems to be available by looking at the source code at https://github.com/helm/helm/blob/master/cmd/helm/list.go#L103. 

Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:34Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-eks-b7174d", GitCommit:"b7174db5ee0e30c94a0b9899c20ac980c0850fc8", GitTreeState:"clean", BuildDate:"2019-10-18T17:56:01Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

`AWS EKS`

**Comment by marckhouzam** [comment]
The helm list -A option did not make it into the 3.0.0 release. As you found, it is in the master branch though, so it will be in the next release.

**Comment by deiga** [comment]
@marckhouzam It seems like `-A` still didn't make it into the release. When can we expect this to be released?

**Comment by marckhouzam** [comment]
@deiga Looking at #6848 it is aimed at the 3.1 release. There's no official date for 3.1 but I've seen someone suggest some time in January.
