### ISSUE TITLE
SHA sum of /tmp/helm-installer-EEUAhM/helm-v2.16.1-linux-amd64.tar.gz does not match. Aborting.

### ISSUE THREAD

**Issue by magick93** [helm/helm#7050]
I'm trying to download and install helm using the guide on https://v2.helm.sh/docs/using_helm/#installing-helm

When I run `./get_helm.sh` I get the following:
```
Downloading https://get.helm.sh/helm-v2.16.1-linux-amd64.tar.gz
SHA sum of /tmp/helm-installer-EEUAhM/helm-v2.16.1-linux-amd64.tar.gz does not match. Aborting.
Failed to install helm
	For support, go to https://github.com/helm/helm.
```

**Comment by karuppiah7890** [comment]
Weird. When I install it in an ubuntu machine, it says this

```
$ ./get_helm.sh
Downloading https://get.helm.sh/helm-v2.16.1-linux-amd64.tar.gz
Preparing to install helm and tiller into /usr/local/bin
helm installed into /usr/local/bin/helm
tiller installed into /usr/local/bin/tiller
Run 'helm init' to configure helm.
```

I think we need to put in some debugging capabilities to see what were the mismatching checksums, like what was expected and what was the actual 😅

**Comment by karuppiah7890** [comment]
Is this error coming repeatedly ? And could you do this - check the sha256sum of the temp file - /tmp/helm-installer-EEUAhM/helm-v2.16.1-linux-amd64.tar.gz

**Comment by magick93** [comment]
I found the problem.

There was no tmp file.

I'm operating within a corp environment, and needed to get https://get.helm.sh whitelisted.

**Comment by karuppiah7890** [comment]
Weird that no error came up for downloading then, hmm

**Comment by magick93** [comment]
Yes, agree. It would have helped in the troubleshooting if there was a relevant error.

**Comment by karuppiah7890** [comment]
@magick93 So, when you say whitelist, previously the domain wasn't reachable at all? or gave a bad response? Could you tell what the behavior was? So that it can be replicated

**Comment by magick93** [comment]
@karuppiah7890 - I'm away from the office so I cant check, but from memory, requesting a blocked url will result in a html page that has a 'page restricted' notice (from the firewall). And I think the http status is 302. Its definitely not 200.

**Comment by ccmcbeck** [comment]
In case anyone finds this issue, I was able to solve this issue by specifying the exact version

    curl -L https://git.io/get_helm.sh > helm.sh
    chmod +x helm.sh 
    ./helm.sh --version v2.16.2

**Comment by NMTechie** [comment]
> In case anyone finds this issue, I was able to solve this issue by specifying the exact version
> 
> ```
> curl -L https://git.io/get_helm.sh > helm.sh
> chmod +x helm.sh 
> ./helm.sh --version v2.16.2
> ```

This works for me
