### ISSUE TITLE
Restricting access on the helm

### ISSUE THREAD

**Issue by sandeepk1210** [helm/helm#7051]
We have got helm client installed and wanted not to give access any access to any of the group/user expect a specific group/user.  Can this be done?

This is because even without any sudo permission, a user has helm list or other permissions and we wish to restrict this in production environment.

Output of `helm version`:
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}

Output of `kubectl version`:
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-eks-b7174d", GitCommit:"b7174db5ee0e30c94a0b9899c20ac980c0850fc8", GitTreeState:"clean", BuildDate:"2019-10-18T17:56:01Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS

**Comment by Mikedu1988** [comment]
helm cli dose not do authentication, you need to find a way of combining helm cli, kubernetes RBAC and system user authentication.
* create a kubernetes service account for each user that will be logged on the system
* create a kubeconfig file for each user
* make helm use the kubeconfig file when a user log in
* a blank kubeconfig file for any user that's not allowed to use helm

Thats my advise for you, you can refer to a video "Securing helm v3" on youtube, maybe you'll come up with some good idea.

**Comment by bacongobbler** [comment]
https://helm.sh/docs/topics/rbac/ is based on the video @Mikedu1988 referenced (I gave the talk).

**Comment by bacongobbler** [comment]
For reference: https://youtu.be/uZ_ihxYZhBo

**Comment by bridgetkromhout** [comment]
Hi, @sandeepk1210 - as @bacongobbler said, https://helm.sh/docs/topics/rbac/ has information relevant to your question. Please let us know if you have further questions. Thanks!
