### ISSUE TITLE
helm init --service-account tiller produces Error: unknown flag: --service-account

### ISSUE THREAD

**Issue by JFercan** [helm/helm#7052]
I'm trying to install Tiller on an AKS Cluster but I get the following error with the downloaded Windows executable

Error: unknown flag: --service-account

helm version
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}

Is the command different?

Thank you

**Comment by bacongobbler** [comment]
Tiller was removed in helm 3. See https://helm.sh/docs/faq/#removal-of-tiller

**Comment by SumanGitHub** [comment]
helm init not working with version 3. I tried with 2.14.2 and it did work. 
**use 2.14.2 :**
```
choco install kubernetes-helm --version=2.14.2 -y 
helm init --upgrade  --service-account tiller 
```

**Comment by hickeyma** [comment]
@SumanGitHub `helm init` is deprecated in Helm 3. Refer to https://github.com/helm/helm/issues/7052#issuecomment-557554311

**Comment by hickeyma** [comment]
@SumanGitHub The docs are also updated for Helm 3, for example: https://helm.sh/docs/intro/quickstart/

**Comment by SumanGitHub** [comment]
I need the particular version , so used 2.14.2 @hickeyma  . Thanks
