### ISSUE TITLE
helm package returns "Error: Version segment starts with 0"

### ISSUE THREAD

**Issue by paulbsch** [helm/helm#7063]
Output of `helm version`:
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:57:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

This is very strange.  The above error suddenly started happening despite not changing the helm v3 binary or the helm chart.  I'm not seeing this issue with helm v2.

**Comment by bacongobbler** [comment]
#7064
