### ISSUE TITLE
set new image tag don't work on helm 3

### ISSUE THREAD

**Issue by jinglei1208** [helm/helm#7067]
cat Chart.yaml  | grep -v '#'| grep -v ^$
    apiVersion: v2
    name: test3
    description: A Helm chart for Kubernetes
    type: application
    version: 1.1.1
    appVersion: old-tag

cat values.yaml 
    image:
      repository: nginx
      pullPolicy: IfNotPresent

cat templates/deployment.yaml | grep image | grep -v "#" | grep -v ^#
      imagePullSecrets:
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

I want set new tag use this command, but all don't work!
  helm install my-test . --set appVersion=new-tag --dry-run --debug
  helm install my-test . --set Chart.appVersion=new-tag --dry-run --debug

command all result is :
>   image: "nginx:old-tag"

Please help me! ^_^ 

Output of `helm version`:
v3.0.0
Output of `kubectl version`:
v1.14.8
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
k8s v1.14.8

**Comment by bacongobbler** [comment]
the application version cannot be changed on-the-fly. Some users have an `overrideAppVersion` value which can be used with `--set` to work around this.

Closing as a duplicate request for #3555.
