### ISSUE TITLE
Odd error message with unknown flag

### ISSUE THREAD

**Issue by richardwhiuk** [helm/helm#7068]
```
$ helm delete --namespace core --name core
Error: unknown flag: --name11 service
```

This is really odd - I'm not sure where the `11` or the `service` have come from.

Versions:

```
$ helm version
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.9", GitCommit:"500f5aba80d71253cc01ac6a8622b8377f4a7ef9", GitTreeState:"clean", BuildDate:"2019-11-13T11:21:43Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

CentOS 7 Linux VM running on Microsoft Azure with manual Kubernetes install

**Comment by mattfarina** [comment]
I just tried to reproduce and my output ended after `Error: unknown flag: --name` which is what I expected.

Can you share how you installed this version of helm. What OS is helm itself running in? Is that CentOS 7 running in Azure?

**Comment by karuppiah7890** [comment]
I'm also doubting a possibility of some weird shell behavior.  @richardwhiuk were you able to reproduce the issue consistently a few times? Could you confirm that? 

Also the command is wrong, so please do try the right one and let us know if that doesn't work, as that should work as expected

**Comment by mustela** [comment]
Having the same issue: 
```
helm install --name metabase stable/metabase
Error: unknown flag: --name
```

Version: `version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}`

**Comment by bridgetkromhout** [comment]
Hi, @richardwhiuk - we're closing this issue as we are unable to reproduce the error; if you have further information, please let us know - thanks.
