### ISSUE TITLE
Suddenly My releases disappeared when I did helm list

### ISSUE THREAD

**Issue by zeroshree** [helm/helm#7070]
Output of `helm version`:

version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.10", GitCommit:"7a578febe155a7366767abce40d8a16795a96371", GitTreeState:"clean", BuildDate:"2019-05-01T04:05:01Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

AWS-KOPS

it's really weird, I upgraded my helm 4 days back from 2.16.1 to 3.0.0 .

please let me know how can i restore my previous releases

Can downgrade will help into this  ?

**Comment by Jabbo16** [comment]
You need to use the `--all-namespaces` flag now, for deletion for example you also need to specify the release's namespace (if not using default namespace).

**Comment by zeroshree** [comment]
$ helm list --all-namespaces
NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART	APP VERSION

@Jabbo16 it is still giving me empty sir

**Comment by karuppiah7890** [comment]
Can you check the secrets and configmaps in all namespaces? Using `kubectl get secrets,configmaps -A` those are where usually releases information is stored, based on your installation. Do check it out and look for release names and versions in the secret or confimap names.

And how were these releases installed? Using Helm v2 or v3?

**Comment by zeroshree** [comment]
I did  `kubectl get secrets,configmaps -A` and i got as shown below

kube-system            configmap/dev-notification-dispatch.v200                                       1      2d
kube-system            configmap/dev-notification-dispatch.v201                                       1      2d
kube-system            configmap/dev-notification-dispatch.v202                                       1      2d
kube-system            configmap/dev-notification-dispatch.v203                                       1      2d
kube-system            configmap/dev-notification-dispatch.v204                                       1      2d
kube-system            configmap/dev-notification-dispatch.v205                                       1      2d
kube-system            configmap/dev-notification-dispatch.v206                                       1      2d
kube-system            configmap/dev-notification-dispatch.v207                                       1      1d
kube-system            configmap/dev-notification-dispatch.v208                                       1      1d
kube-system            configmap/dev-notification-dispatch.v209                                       1      3h

which indicates the last one happened 3 hours ago.

And how were these releases installed?
helm install repo-name --name release-name --namespace NAMESPACE --set-string timestamp=dev-random-generated-number

after that i always uses upgrade for new deployment

helm upgrade repo-name  release-name --namespace NAMESPACE --set-string timestamp=dev-random-generated-number

Using Helm v2 or v3?
If you are asking about helm version , so previous one was v2.14.3

**Comment by karuppiah7890** [comment]
Okay, switching from v2 to v3 needs some small effort as the release information is stored differently. 

I'm assuming `helm ls` works for you with version 2.14.3 and even 2.16.1 ( latest v2 version ). To move to v3 you need to use the 2to3 plugin  https://github.com/helm/helm-2to3 then `helm ls` will work with helm version 3.0.0 :) but not with helm v2 anymore. Both are incompatible. But you can get rid of tiller in v3, for good :) ;)

**Comment by zeroshree** [comment]
@karuppiah7890 

suppose I don't want to go v3.0.0 right now, it is my production setup.  I want to my previous setup back as it was working fine for me. 

So what should i do ?

Thanks


If not then i will have to go v3 without any reason.

**Comment by karuppiah7890** [comment]
You can just keep using v2.14.3 and there should be no problems. 

And the latest in v2 is 2.16.1 . You could update to v2.16.1 for some features and support for kubernetes v1.16 if you want that

**Comment by bacongobbler** [comment]
Yep. Looks like nothing has changed on the backend. This system hasn't been migrated to the new storage backend for Helm 3. Continue to use it as normal, and use the helm-2to3 plugin when you're ready to migrate.

Closing as answered. Thanks!

**Comment by zeroshree** [comment]
@karuppiah7890 Thanks a lot. It got fixed. In my kube-system tiller version was v2.16.0, so same i installed helm in my deployment server by downgrading.


Thanks

**Comment by zhenyulin** [comment]
I'm having the same issue, and instead, I want to migrate to v3 following the guide.

I notice in the prerequisite of the docs that:
```
Helm v2 client installed on a system which manages releases on one to many clusters
Helm v3 client with 2to3 plugin installed on the same system```

Both v2 and v3 clients are required, while I installed helm via homebrew. Does anyone have experience on how to get both versions at the same time?
