### ISSUE TITLE
RFE: Add to kind_sorter.go: two types: ImageStream and BuildConfig

### ISSUE THREAD

**Issue by Andrei-Stepanov** [helm/helm#7072]
Hello, please add to https://github.com/helm/helm/blob/484d43913f97292648c867b56768775a55e4bba6/pkg/releaseutil/kind_sorter.go

Two types: **ImageStream** and **BuildConfig**

These are two primary native types in OpenShift.

ImageStream goes first, next goes BuildConfig
I would put them after RoleBindingList

Thank you.

**Comment by hickeyma** [comment]
I think only Kubernetes types are added to the list. @mattfarina @bacongobbler is that correct?

**Comment by mattfarina** [comment]
Helm supports compliant Kubernetes clusters. If `ImageStream` and `BuildConfig` are CRDs that can lead to a conversation on CRD ordering. But, if these are custom add-ons baked into OpenShift we need to have a larger conversation on support for platforms that are extended through non-CRD means.

@Andrei-Stepanov Can you fill us in on how those two types work so we can have a little more information?

**Comment by bacongobbler** [comment]
closing as stale.
