### ISSUE TITLE
Support Overrides

### ISSUE THREAD

**Issue by zendril** [helm/helm#7076]
Feature Request: Ability to provide a template to override one from chart.

Scenario: I pull a vendor chart and something isn't supported in one of the templates. For example, many charts do not have securityContext which is required for running as non-root on many k8s clusters.

I would like to take a copy of the existing template, modify it and use it as an override at install time.

This could be used in a couple of scenarios:

- While waiting for the feature to get merged back upstream in the chart
- Supporting a feature that may be bespoke to our installation (doesn't belong upstream)

Currently I have a folder called /manifest/overrides that is in the same structure as the chart, I run a helm fetch, copy the overrides on top and then run helm template.  

The goal of this issue is to have the discussion about options for accomplishing this in a supported or well known paradigm.

**Comment by zendril** [comment]
@michelleN This is one of the issues that I brought up at the KubeCon table last week. Mind pulling in the right folks to noodle on this one please?

**Comment by bacongobbler** [comment]
potentially related: https://github.com/helm/helm/issues/5276

**Comment by marckhouzam** [comment]
I wonder if the (planned?) `ext` directory aims to allow this?
https://github.com/helm/community/blob/master/helm-v3/001-charts.md#the-ext-directory

**Comment by bacongobbler** [comment]
closing as stale.
