### ISSUE TITLE
Support Extras

### ISSUE THREAD

**Issue by zendril** [helm/helm#7077]
Feature Request: Ability to provide a template to add extra functionality to a chart.

Scenario: I pull a vendor chart and a feature isn't supported. For example, we might run additional deployments or a different ingress. 

These are usually things that are extra and bespoke to our running of this chart.

Similar to https://github.com/helm/helm/issues/7076 except that usually means a small modification to the templates of the vendor chart, mostly until those changes get merged upstream. In this case, it is adding completely new functionality, but is driven by the same values.yaml in most cases (otherwise we would just create another chart for these).

Currently I have a folder called /manifest/extras that is in the same structure as the chart, I run a helm fetch, copy the extras on top and then run helm template.

The goal of this issue is to have the discussion about options for accomplishing this in a supported or well known paradigm.

**Comment by zendril** [comment]
@michelleN Here is the other scenario I brought up at the KubeCon table last week. Mind pulling in the right folks to noodle on this one as well?

**Comment by bacongobbler** [comment]
potentially related: https://github.com/helm/helm/issues/5276

**Comment by bridgetkromhout** [comment]
Hi, @zendril - I'm closing this issue because we now have a recommended path forward for proposals: if you'd like to formally propose this idea, please file a [Helm Improvement Proposal](https://github.com/helm/community/blob/master/hips/hip-0001.md) to discuss it with the community. Thanks!
