### ISSUE TITLE
Helm ls returns none

### ISSUE THREAD

**Issue by djklim87** [helm/helm#7081]
Bug, `helm ls` returns none.

I was trying to migrate from 2v3, and when I runs
```
helm 2to3 convert --dry-run kafka
2019/11/26 18:55:28 NOTE: This is in dry-run mode, the following actions will not be executed.
2019/11/26 18:55:28 Run without --dry-run to take the actions described below:
2019/11/26 18:55:28 
2019/11/26 18:55:28 Release "kafka" will be converted from Helm v2 to Helm v3.
2019/11/26 18:55:28 [Helm 3] Release "kafka" will be created.
2019/11/26 18:55:30 [Helm 3] ReleaseVersion "kafka.v1" will be created.
```
For non-deployed releases I got error
```
helm 2to3 convert --dry-run nondeployed
2019/11/26 19:05:00 NOTE: This is in dry-run mode, the following actions will not be executed.
2019/11/26 19:05:00 Run without --dry-run to take the actions described below:
2019/11/26 19:05:00 
2019/11/26 19:05:00 Release "nondeployed" will be converted from Helm v2 to Helm v3.
2019/11/26 19:05:00 [Helm 3] Release "nondeployed" will be created.
Error: nondeployed has no deployed releases

```
So helm see the release but `LS` don't show it

Output of helm version:
`version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}`

Output of kubectl version:
`Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-18T14:56:51Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
`Hetzner cloud`

**Comment by dark4rest** [comment]
I am install chart, but "helm ls" returns none, if i run "helm ls --all --all-namespaces" - return all reliases. But "helm uninstall chartname" returns Error: uninstall: Release not loaded: chartname: release: not found

**Comment by marckhouzam** [comment]
With helm 3, the release information is part of the namespace. Therefore for any command referencing a release you must specify the correct namespace using the `--namespace` flag. This applies to `helm ls` and `helm uninstall`, and all other helm commands referencing a release.

**Comment by bacongobbler** [comment]
Closing as answered. This information is also part of the FAQ. Closing
