### ISSUE TITLE
Unnecessary chart source files in the backing secret object in v3

### ISSUE THREAD

**Issue by asyncmax** [helm/helm#7084]
In v3.0.0, it appears that Helm client stores all source files from a chart, except subchart files under `charts`, in a secret object created per each release.

If I understood correctly, these source files are not required for Helm's operations. Would you teach me why these seemingly unnecessary files are saved in the cluster?

Please forgive me if I am wrong. I am not super familiar with Helm's internals.

Thanks in advance!

**Comment by bacongobbler** [comment]
During an upgrade, Helm compares the old release, the live state (what's in the cluster), and the proposed changes (what was provided with `helm upgrade`). The source files are required to re-build the objects when they were first provided to Helm for this comparison to work.

Does that make sense?

**Comment by asyncmax** [comment]
Thanks for your explanation.

Do we need to rebuild the objects even if the generated objects are saved already in the `manifest` section?

Also, because source templates from subcharts are not stored, I am wondering how we can rebuild a whole set of k8s objects from the data - apparently, it seems impossible anyway.

Did I miss something?

**Comment by bacongobbler** [comment]
https://github.com/helm/helm/blob/456eb7f4118a635427bd43daa3d7aabf29304f13/pkg/chart/chart.go#L49

**Comment by bacongobbler** [comment]
The fullly rendered manifest (including templates rendered from subcharts) should be available through the `Manifest` object. This is how Helm peforms the comparison.

https://github.com/helm/helm/blob/456eb7f4118a635427bd43daa3d7aabf29304f13/pkg/release/release.go#L33

**Comment by asyncmax** [comment]
Yes, I know the fully rendered manifest is available through the `Manifest` for performing the comparison. We don't need to rebuild it from the source files every time we upgrade, right?

My question was, why do you serialize the entire `Chart` object, especially with `Chart.Templates` and `Chart.Files`, which potentially can be very large.

As you know, [etcd is not designed for storing large blobs](https://etcd.io/docs/v3.3.12/dev-guide/limit/).

**Comment by bacongobbler** [comment]
closing as stale.
