### ISSUE TITLE
Helm 3 unable to reach cluster

### ISSUE THREAD

**Issue by pageanengineer** [helm/helm#7086]
Output of `helm version`:
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS kops cluster

I am trying to install a helm chart that is publically available and when doing do I get an error `Error: Kubernetes cluster unreachable` which is preventing me from installing said chart.

Chart I am trying to install: https://hub.helm.sh/charts/architectminds/aws-ecr-credential

Steps to reproduce:
```
Install Helm 3 using install script
helm repo add architectminds https://architectminds.github.io/helm-charts/
helm repo update
helm install  aws-ecr-credential architectminds/aws-ecr-credential --set targetNamespace=development --set-string aws.account=<account ID> --set aws.region=us-east-1 --set aws.accessKeyId=base64== --set aws.secretAccessKey=base64==  --dry-run
```

Error message: `Error: Kubernetes cluster unreachable`

Same error message is produced when appling directly without dry run.

**Comment by marckhouzam** [comment]
Can you run `kubectl cluster-info`?  Can it reach the cluster?

**Comment by particledecay** [comment]
I'm having the same issue here. It doesn't seem to be looking at my current context.
![Selection_628](https://user-images.githubusercontent.com/685255/71737390-83e76580-2e21-11ea-8c7a-1965e8678ba9.png)
You can see that helm doesn't reach the cluster until I explicitly provide the config file that contains my current context.

If it helps, I have multiple files within the `~/.kube` directory and my `$KUBECONFIG` contains all of them (i.e. `/path/to/first.conf:/path/to/second.conf:/path/to/third.conf`).

**Comment by FredM** [comment]
Same here with multiple kubeconfig files. As soon as I set `$KUBECONFIG` to one specific file Helm works perfectly

**Comment by particledecay** [comment]
For those interested, I got tired of the quirky surprises of working with multiple kubeconfigs, so I wrote a tool to manage many kubeconfigs at once and this bug doesn't appear anymore: https://github.com/particledecay/kconf

**Comment by kevupton** [comment]
After install `helm` on `ubuntu` i was also experiencing this issue. 
I just reran 
```
kubectl config set-context <context>
```

And it worked

**Comment by hickeyma** [comment]
@particledecay @FredM @kevupton
 
From [Organizing Cluster Access Using kubeconfig Files](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/):
"By default, kubectl looks for a file named config in the $HOME/.kube directory. You can specify other kubeconfig files by setting the KUBECONFIG environment variable or by setting the --kubeconfig flag."

Helm works pretty much the same as `kubectl` wrt cluster access. 

When you have multiple kubeconfig files specified in `$KUBECONFIG`, then the first file is used by default. You therefore need to set the context if you want to use another file instead. With `kubectl`, you can use command: `kubectl config use-context`.
Alternatively, you can also use tools like `kubectx` for this: https://github.com/ahmetb/kubectx. Or use `--kube-context` flag when running the Helm command.

[Organizing Cluster Access Using kubeconfig Files](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/) provide details on the cluster access.

**Comment by hickeyma** [comment]
@pageanengineer Is this still an issue for you or can this issue be closed?
