### ISSUE TITLE
Cannot list charts in the local registry cache with helm3

### ISSUE THREAD

**Issue by ywk253100** [helm/helm#7087]
Got error when trying to list the charts:
```
root@ubuntu16:/tmp# helm chart list
Error: manifest does not contain a layer with mediatype application/tar+gzip
```
helm version:
```
root@ubuntu16:/tmp# helm version
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

**Comment by jdolitsky** [comment]
@ywk253100 - if I recall correctly, you were an early adopter of the registry features. Several weeks ago we made a breaking change, switching from a custom layer mediatype to `application/tar+gzip`

My assumption is that you've upgraded from some v3-beta to 3.0 and are using the same cache. The simple solution is to simply remove the cache:
```
rm -rf $(helm env | grep HELM_REPOSITORY_CACHE | sed 's/.*"\(.*\)repository"/\1registry/')
```
(we should add a `HELM_REGISTRY_CACHE` value to `helm env` to make this more straightforward)

If you absolutely need to retrieve charts in the cache, I would suggest re-installing the beta version temporarily, and running a `helm chart export` for whichever charts you want. Afterwards, you can use Helm 3.0 to do `helm chart save` to get these back in the cache.

Sorry for the inconvenience. Let us know if this works.

**Comment by ywk253100** [comment]
@jdolitsky Removing the cache directory works for me, thanks.

**Comment by hickeyma** [comment]
@ywk253100 Closing this issue as @jdolitsky has explained that it is because of a breaking change from Helm 3 beta version and not an issue in Helm 3 GA. Josh also provided a workaround so that you can progress.
