### ISSUE TITLE
No able to download helm modules in a go program

### ISSUE THREAD

**Issue by trinoy** [helm/helm#7100]
I am trying to access the Helm API in a go program. Please check code below 
package main

```
import (
    "fmt"
    "os"
    "helm.sh/helm/v3/pkg/action"
    "helm.sh/helm/v3/pkg/chart/loader"
    "helm.sh/helm/v3/pkg/kube"
    _ "k8s.io/client-go/plugin/pkg/client/auth"
)

func main() {
    fmt.Println("Successfully started")
    chartPath := "/tmp/my-chart-0.1.0.tgz"
    chart, err := loader.Load(chartPath)
    if err != nil {
        panic(err)
    }

    kubeconfigPath := "/tmp/my-kubeconfig"
    releaseName := "my-release"
    releaseNamespace := "default"
    actionConfig := new(action.Configuration)
    if err := actionConfig.Init(kube.GetConfig(kubeconfigPath, "", releaseNamespace), releaseNamespace, os.Getenv("HELM_DRIVER"), func(format string, v ...interface{}) {
        fmt.Sprintf(format, v)
    }); err != nil {
        panic(err)
    }

    iCli := action.NewInstall(actionConfig)
    iCli.Namespace = releaseNamespace
    iCli.ReleaseName = releaseName
    rel, err := iCli.Run(chart, nil)
    if err != nil {
        panic(err)
    }
    fmt.Println("Successfully installed release: ", rel.Name)
}
```
I tried to create a folder and create a file helmdemo.go with the above code. 
I then did go mod init so that when i run the go code it would download the dependent modules.

But when i do go run helmdemo.go I get the below error
go: finding helm.sh/helm/v3 v3.0.0
go: finding helm.sh/helm v2.16.1+incompatible
go: finding k8s.io/client-go v11.0.0+incompatible
go: downloading helm.sh/helm/v3 v3.0.0
go: downloading helm.sh/helm v2.16.1+incompatible
go: downloading k8s.io/client-go v11.0.0+incompatible
go: extracting helm.sh/helm/v3 v3.0.0
go: extracting helm.sh/helm v2.16.1+incompatible
go: extracting k8s.io/client-go v11.0.0+incompatible
go: helm.sh/helm/v3@v3.0.0 requires
        github.com/deislabs/oras@v0.7.0 requires
        github.com/docker/docker@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000

Could you please let me know how to resole it. Thanks

**Comment by bacongobbler** [comment]
https://github.com/helm/helm/blob/8f87900860f7c1474fd07fe9a97fefd31bca7d09/go.mod#L80

**Comment by trinoy** [comment]
I found a similar issue. Should the replace directive be removed ?
https://github.com/fluxcd/flux/pull/2590/files

**Comment by ls-tait-clarridge** [comment]
I believe updating the dependency of oras to `v0.8.0` should fix the issue since it was updated in deislabs/oras#132

**Comment by hickeyma** [comment]
@ls-tait-clarridge PR #6862 in progress

**Comment by povils** [comment]
Do we have a workaround for that?

**Comment by hickeyma** [comment]
@povils See https://github.com/helm/helm/issues/7100#issuecomment-559310344

**Comment by bacongobbler** [comment]
closing as stale.
