### ISSUE TITLE
HowTo not working

### ISSUE THREAD

**Issue by Roadrunner67** [helm/helm#7102]
Being new to Helm, I followed the guide on https://docs.bitnami.com/kubernetes/how-to/create-your-first-helm-chart/

I think my issues are related to having installed Helm v3.0.0.

--name in the helm install examples was invalid - that was an easy catch though.

When trying to do the todo exercise in Step 3, I ran into a problem:

Although clearly defining tag 1.0.0 for image prydonius/todo, the installation trie to download prydonius/todo:1.16.0 which is nonexistent.

in ./mychart/templates/deployment.yaml there is this line:

`image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"`

...and AppVersion in Chart.yaml is 1.16.0

Should Appversion really be used for image tags?

**Comment by hickeyma** [comment]
@Roadrunner67 The scaffold chart example deploys an `nginx` server of a particular version. The change introduced in #5662 was to use the `AppVersion` to correspond to the version of the app being deployed. In this case it is `nginx` version `1.16.0`. This is working as expected.

The issues you are encountering is that the guide you are following is unfortunately not in sync with Helm 3.

The Helm docs are also worth taking a look: https://helm.sh/docs/

**Comment by hickeyma** [comment]
Closing as working as expected.

**Comment by Roadrunner67** [comment]
So you could never have an app pulling multiple images, or you expect all images to be the same version as your app?

**Comment by hickeyma** [comment]
No necessarily. Its just in the scaffold example it is `nginx` server being deployed and makes sense to set the `AppVersion` in this scenario to it.
