### ISSUE TITLE
Improve docs regarding helm chart name and release name

### ISSUE THREAD

**Issue by stefankip** [helm/helm#7104]
I had some issues and talked on the slack channel with @hickeyma.
In the end the problem was me, not understanding the helm chart name and the release name.

So I had the following situation:
I didn't know in the beginning that the release name had to be unique within a namespace. I used the helm chart name as component name (copy, content, seo, orders etc.) and the release name *initial* for those different charts.
Now I'm using the product name of the app as helm chart name and the release name is now the component name.
So I had 3 different helm charts called **initial** and they kept replacing eachother.

So I thought the chart name was identifying the chart and the release name was identifying a release, while there are also versions and revisions.
The documentation can be improved regarding this, imo.

**Comment by NargiT** [comment]
Is this not enough ?
FAQ: https://helm.sh/docs/faq/#release-names-are-now-scoped-to-the-namespace
Charts: https://v3.helm.sh/docs/topics/charts/#the-chart-file-structure

**Comment by bacongobbler** [comment]
Yes, that should be enough. Closing as inactive/answered.
