### ISSUE TITLE
Helm doesn't work with local mirror of stable repo

### ISSUE THREAD

**Issue by revkovvi** [helm/helm#7105]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

I've configured JFrog Artifactory as a mirror of stable helm repo https://kubernetes-charts.storage.googleapis.com
Helm client was configured to work with that mirror and I can successfully search charts there.
Unfortunately, I can't fetch any charts and install them because when I try to do so helm behaves like he wants to get this chart not from our mirror, but from https://kubernetes-charts.storage.googleapis.com.

```
helm repo list
NAME            URL
helm-remote     https://artifactory.domain.local/kubernetes-charts-google-helm-remote
```
```
helm search repo redis
NAME                                    CHART VERSION   APP VERSION     DESCRIPTION
helm-remote/prometheus-redis-exporter   3.2.0           1.0.4           Prometheus exporter for Redis metrics
helm-remote/redis                       10.0.1          5.0.7           Open source, advanced key-value store. It is of...
helm-remote/redis-ha                    4.1.1           5.0.5           Highly available Kubernetes implementation of R...
helm-remote/sensu                       0.2.3           0.28            Sensu monitoring framework backed by the Redis ...
```
```
helm fetch helm-remote/redis
Error: Get https://kubernetes-charts.storage.googleapis.com/redis-10.0.1.tgz: dial tcp 64.233.162.128:443: connect: connection refused
```

While I interact with Artifactory using curl I can get index.yaml and even to download charts.
```
curl -I https://artifactory.domain.local/kubernetes-charts-google-helm-remote/index.yaml
HTTP/1.1 200 OK
Date: Thu, 28 Nov 2019 14:44:17 GMT
Content-Type: text/plain; charset=utf8
Content-Length: 7160555
Connection: keep-alive
Server: Artifactory/6.9.5
X-Artifactory-Id: 0af5613e476674d9:2fb567f1:16eaefca7fc:-7ffd
Last-Modified: Thu, 28 Nov 2019 13:27:57 GMT
Accept-Ranges: bytes
X-Artifactory-Filename: index.yaml
Content-Disposition: attachment; filename="index.yaml"; filename*=UTF-8''index.yaml
Cache-Control: no-store
Docker-Distribution-Api-Version: registry/2.0
```
```
curl -I https://artifactory.domain.local/kubernetes-charts-google-helm-remote/redis-10.0.1.tgz
HTTP/1.1 200 OK
Date: Thu, 28 Nov 2019 14:44:53 GMT
Content-Type: application/x-gzip
Content-Length: 28127
Connection: keep-alive
Server: Artifactory/6.9.5
X-Artifactory-Id: 0af5613e476674d9:2fb567f1:16eaefca7fc:-7ffd
Last-Modified: Thu, 28 Nov 2019 13:58:51 GMT
ETag: 2600b05691b492ea39557a3b00efc76953eb7017
X-Checksum-Sha1: 2600b05691b492ea39557a3b00efc76953eb7017
X-Checksum-Sha256: ef320c86d9862db0e16a550e8f233ddd705e04fc414b4044e7ebd63dc94163eb
X-Checksum-Md5: 4699520604e5959d65bc9c0ec6b0ea73
Accept-Ranges: bytes
X-Artifactory-Filename: redis-10.0.1.tgz
Content-Disposition: attachment; filename="redis-10.0.1.tgz"; filename*=UTF-8''redis-10.0.1.tgz
Docker-Distribution-Api-Version: registry/2.0
```

At Artifactory logs, I see that it's connected to https://kubernetes-charts.storage.googleapis.com and downloads charts which I get using curl.
I've tried to use the latest version of Helm 2 instead of Helm 3, but it behaves the same way.
What could be a problem?

**Comment by bacongobbler** [comment]
Was the index.yaml updated to reflect the new URLs as well?

helm install fetches down the index, looks up the chart name in that index which returns a URL to fetch. I’m nearly certain it’s because those URLs were not updated.

https://helm.sh/docs/topics/chart_repository/

**Comment by jonasrutishauser** [comment]
You must use a virtual Repository in Artifactory (see https://www.jfrog.com/confluence/display/RTF/Helm+Chart+Repositories#HelmChartRepositories-ResolvingHelmCharts).

**Comment by revkovvi** [comment]
> Was the index.yaml updated to reflect the new URLs as well?
> 
> helm install fetches down the index, looks up the chart name in that index which returns a URL to fetch. I’m nearly certain it’s because those URLs were not updated.
> 
> https://helm.sh/docs/topics/chart_repository/

And your supposition was right.
Artifactory actually doesn't update these URLs for some reason.

> You must use a virtual Repository in Artifactory (see https://www.jfrog.com/confluence/display/RTF/Helm+Chart+Repositories#HelmChartRepositories-ResolvingHelmCharts).

Yes, with a virtual repository it works correctly.

Thanks for the help!
