### ISSUE TITLE
How to configure cluster url?

### ISSUE THREAD

**Issue by heckad** [helm/helm#7106]
I use minik8s and it uses 16443 port for Kubernetes cluster. How to tell helm to use 16443 port instead of 8080? Thanks

Output of `helm version`:
 ```
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

Output of `kubectl version`: 
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by bacongobbler** [comment]
Similar to kubectl, Helm uses your local Kubernetes config to load connection information.

See https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/ for more information.

Does this help?

**Comment by heckad** [comment]
Unfortunately not. minik8s  doesn't have a config(`~/.kube/` contains only 2 folders). Mybe I didn't find it. Are you planning to add another configuration method?

**Comment by heckad** [comment]
I made `microk8s.kubectl config view > $HOME/.kube/config` and now IP address ok, but the error remained. 
Verbose log
```
I1128 20:44:41.881358   31960 round_trippers.go:423] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: helm/v0.0.0 (linux/amd64) kubernetes/$Format" -H "Authorization: Basic YWRtaW46ZWtKWGMwaE1PVmhPYURodWFEUXdkbnBMZWl0NGVrdzBWRmx6VFU5SU5rMXRObTVUVjBka05GWllTVDBL" 'https://127.0.0.1:16443/version?timeout=32s'
I1128 20:44:41.888607   31960 round_trippers.go:443] GET https://127.0.0.1:16443/version?timeout=32s  in 7 milliseconds
I1128 20:44:41.888661   31960 round_trippers.go:449] Response Headers:
Error: Kubernetes cluster unreachable
```

If evaluate curl command then all ok. Why helm got the error?

**Comment by hickeyma** [comment]
Can you run a `kubectl` commands ? What is the output to the following commands:
- `kubectl config view`
- `kubectl get all --all-namespaces`

**Comment by heckad** [comment]
I found solution in my another [question](https://github.com/ubuntu/microk8s/issues/833#issuecomment-559615751). Thank you all for your help.
