### ISSUE TITLE
question: is there some samples on how to configure dependencies

### ISSUE THREAD

**Issue by WeihanLi** [helm/helm#7108]
Output of `helm version`:

helm 3.0.0

version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}

**Comment by bacongobbler** [comment]
Hey @WeihanLi. Have you checked the documentation on this subject? https://helm.sh/docs/topics/chart_best_practices/dependencies/

**Comment by WeihanLi** [comment]
yeah, I'd checked for the document first, but seemed not so helpful for me, I'd like to add some dependencies(like redis/mysql etc) for my app chart, but I don't know how to add a dependency and 
add custom config for the dependency(like specific port etc), could you please share me with a simple sample with helm v3?

**Comment by WeihanLi** [comment]
Hi @bacongobbler , I'd made a helm chart here <https://github.com/WeihanLi/ActivityReservation/tree/dev/k8s/reservation-server> 
That's an asp.net core application depends on redis/mysql, but for now, the application would start without waiting for the mysql ready, 
so is there some methods to let the application chart start not before all child charts started?
