### ISSUE TITLE
Question : About Security in helm3

### ISSUE THREAD

**Issue by gogovan-vincentngai** [helm/helm#7109]
I am using GKE , and i am using jenkins as cicd tools 
I have a question about helm3 security, while as i know the one key point migrate from v2 to v3 is about security improvement 

while helm 2 ---->tiller --->service account----> target actions
while helm 3 --- > your account /service account ---> target actions

if it is local user deployment via local machine trigger helm3 cmd 
then it should record the user information action from GCP/GKE audit level
but when we are using jenkins as our cicd tools 
somehow i think it still need a service account to access object inside the cluster
then will still go back to a situation 

from **GCP** side will it still cannot record whom via the **jenkins account** did **what** in my cluster

**Comment by hickeyma** [comment]
In Helm 3, security is on a per user basis. It is delegates to K8s user cluster security. It will work similar to using `kubectl` authentication and authorization..

A good reference is a talk at Helm summit by @bacongobbler on securing Helm:  https://sched.co/S8tr

**Comment by marckhouzam** [comment]
We use Jenkins as well. You are right that Jenkins needs some account to connect to your GKE cluster. If you use a service account for Jenkins then as you say the audit will only know about the Jenkins account, not the user who triggered Jenkins.

You could define a way to use a specific user kubeconfig file for their Jenkins build. 
Or you could add annotations to your deployments indicating the user that triggered the build. I'm sure there are other tricks to achieve this too.

**Comment by bacongobbler** [comment]
Closing as answered
