### ISSUE TITLE
pkg/chartutil: LoadDir and LoadFile has been removed since Helm3 ?

### ISSUE THREAD

**Issue by scbizu** [helm/helm#7110]
Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.0-rc.2", GitCommit:"82ea5aa774661cc6557cb57293571d06f94aff0c", GitTreeState:"clean", GoVersion:"go1.13.3"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:02:12Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

MiniKube

Hi there, I read the [draft](https://github.com/Azure/draft) codebase for some helm-based dev inspiration these days , but I find that some useful chart operation function has been removed from Helm 3, such as `LoadDir` or `LoadFile`. I wonder that if there is any replacement of these functions or am I missing something in the current `chartutil` pkg?  

Thanks in advance ~

**Comment by hickeyma** [comment]
@scbizu There has been a lot of refactoring under the hood in Helm 3 from Helm 2. These functions should be equivalent to Helm 2 functions your are looking for:

- `pkg/chart/loader/archive::LoadFile()`: load archive file
- `pkg/chart/loader/load::LoadFiles()`: load files
- `pkg/chart/loader/directory:LoadDir()`: for charts from directory

**Comment by scbizu** [comment]
Thanks ~
