### ISSUE TITLE
Error: forwarding ports: error upgrading connection: error sending request: 

### ISSUE THREAD

**Issue by KaushikRout** [helm/helm#7112]
Error: forwarding ports: error upgrading connection: error sending request: Post https://<ip:port>/

Output of `helm version`:
Client: &version.Version{SemVer:"v2.13.1", ...
Error: forwarding ports: error upgrading connection: error sending request: Post https://<ip:port>/api/v1/namespaces/kube-system/pods/<pod-name>/portforward: unexpected EOF

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7+1.2.3.el7", GitCommit:"cfc2012a27408ac61c8883084204d10b31fe020c", GitTreeState:"archive", BuildDate:"2019-05-23T20:00:05Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1+2.1.5.el7", GitCommit:"ea4c95b07dd46d5563e4f6851ede13157bf04266", GitTreeState:"archive", BuildDate:"2018-03-23T02:54:15Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Linux, Kube

**Comment by hickeyma** [comment]
Can you connect with the Kubernetes cluster using `kubectl`?  What is the output to the following commands:
- `kubectl config view`
- `kubectl get all --all-namespaces`

**Comment by KaushikRout** [comment]
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://xx.xxx.xxx.xxx:xxxx
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
bash-4.2$ kubectl get all --all-namespaces
NAMESPACE     NAME                                        READY   STATUS    RESTARTS   AGE
kube-system   pod/etcd-slc16liq                           1/1     Running   0          30h
kube-system   pod/kube-apiserver-slc16liq                 1/1     Running   0          30h
kube-system   pod/kube-controller-manager-slc16liq        1/1     Running   0          30h
kube-system   pod/kube-dns-855949bbf-t2ndh                3/3     Running   0          30h
kube-system   pod/kube-flannel-ds-474jk                   1/1     Running   0          30h
kube-system   pod/kube-flannel-ds-kzvv9                   1/1     Running   0          30h
kube-system   pod/kube-flannel-ds-p9whd                   1/1     Running   0          30h
kube-system   pod/kube-proxy-bnjl9                        1/1     Running   0          30h
kube-system   pod/kube-proxy-d7qbg                        1/1     Running   0          30h
kube-system   pod/kube-proxy-m7chm                        1/1     Running   0          30h
kube-system   pod/kube-scheduler-slc16liq                 1/1     Running   0          30h
kube-system   pod/kubernetes-dashboard-7c966ddf6d-5h5h2   1/1     Running   0          30h
kube-system   pod/tiller-deploy-78dfcfd45d-ftxxm          1/1     Running   0          3h20m

NAMESPACE     NAME                           TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)         AGE
default       service/kubernetes             ClusterIP   xx.xx.x.x        <none>        443/TCP         30h
kube-system   service/kube-dns               ClusterIP   xx.xx.x.xx       <none>        53/UDP,53/TCP   30h
kube-system   service/kubernetes-dashboard   ClusterIP   xx.xxx.xxx.xxx   <none>        443/TCP         30h
kube-system   service/tiller-deploy          ClusterIP   xx.xxx.xx.xx     <none>        44134/TCP       6h8m

NAMESPACE     NAME                                   DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                   AGE
kube-system   daemonset.extensions/kube-flannel-ds   3         3         3       3            3           beta.kubernetes.io/arch=amd64   30h
kube-system   daemonset.extensions/kube-proxy        3         3         3       3            3           <none>                          30h

NAMESPACE     NAME                                         DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.extensions/kube-dns               1         1         1            1           30h
kube-system   deployment.extensions/kubernetes-dashboard   1         1         1            1           30h
kube-system   deployment.extensions/tiller-deploy          1         1         1            1           3h20m

NAMESPACE     NAME                                                    DESIRED   CURRENT   READY   AGE
kube-system   replicaset.extensions/kube-dns-855949bbf                1         1         1       30h
kube-system   replicaset.extensions/kubernetes-dashboard-7c966ddf6d   1         1         1       30h
kube-system   replicaset.extensions/tiller-deploy-78dfcfd45d          1         1         1       3h20m

NAMESPACE     NAME                             DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                   AGE
kube-system   daemonset.apps/kube-flannel-ds   3         3         3       3            3           beta.kubernetes.io/arch=amd64   30h
kube-system   daemonset.apps/kube-proxy        3         3         3       3            3           <none>                          30h

NAMESPACE     NAME                                   DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.apps/kube-dns               1         1         1            1           30h
kube-system   deployment.apps/kubernetes-dashboard   1         1         1            1           30h
kube-system   deployment.apps/tiller-deploy          1         1         1            1           3h20m

NAMESPACE     NAME                                              DESIRED   CURRENT   READY   AGE
kube-system   replicaset.apps/kube-dns-855949bbf                1         1         1       30h
kube-system   replicaset.apps/kubernetes-dashboard-7c966ddf6d   1         1         1       30h
kube-system   replicaset.apps/tiller-deploy-78dfcfd45d          1         1         1       3h20m
bash-4.2$

**Comment by KaushikRout** [comment]
> apiVersion: v1
> clusters:
> 
> * cluster:
>   certificate-authority-data: DATA+OMITTED
>   server: https://xx.xxx.xxx.xxx:xxxx
>   name: kubernetes
>   contexts:
> * context:
>   cluster: kubernetes
>   user: kubernetes-admin
>   name: kubernetes-admin@kubernetes
>   current-context: kubernetes-admin@kubernetes
>   kind: Config
>   preferences: {}
>   users:
> * name: kubernetes-admin
>   user:
>   client-certificate-data: REDACTED
>   client-key-data: REDACTED
>   bash-4.2$ kubectl get all --all-namespaces
>   NAMESPACE     NAME                                        READY   STATUS    RESTARTS   AGE
>   kube-system   pod/etcd-xxxxxxx                           1/1     Running   0          30h
>   kube-system   pod/kube-apiserver-xxxxxx                 1/1     Running   0          30h
>   kube-system   pod/kube-controller-manager-xxxxxx        1/1     Running   0          30h
>   kube-system   pod/kube-dns-855949bbf-t2ndh                3/3     Running   0          30h
>   kube-system   pod/kube-flannel-ds-474jk                   1/1     Running   0          30h
>   kube-system   pod/kube-flannel-ds-kzvv9                   1/1     Running   0          30h
>   kube-system   pod/kube-flannel-ds-p9whd                   1/1     Running   0          30h
>   kube-system   pod/kube-proxy-bnjl9                        1/1     Running   0          30h
>   kube-system   pod/kube-proxy-d7qbg                        1/1     Running   0          30h
>   kube-system   pod/kube-proxy-m7chm                        1/1     Running   0          30h
>   kube-system   pod/kube-scheduler-xxxxxxx                 1/1     Running   0          30h
>   kube-system   pod/kubernetes-dashboard-7c966ddf6d-5h5h2   1/1     Running   0          30h
>   kube-system   pod/tiller-deploy-78dfcfd45d-ftxxm          1/1     Running   0          3h20m
> 
> NAMESPACE NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE
> default service/kubernetes ClusterIP xx.xx.x.x 443/TCP 30h
> kube-system service/kube-dns ClusterIP xx.xx.x.xx 53/UDP,53/TCP 30h
> kube-system service/kubernetes-dashboard ClusterIP xx.xxx.xxx.xxx 443/TCP 30h
> kube-system service/tiller-deploy ClusterIP xx.xxx.xx.xx 44134/TCP 6h8m
> 
> NAMESPACE NAME DESIRED CURRENT READY UP-TO-DATE AVAILABLE NODE SELECTOR AGE
> kube-system daemonset.extensions/kube-flannel-ds 3 3 3 3 3 beta.kubernetes.io/arch=amd64 30h
> kube-system daemonset.extensions/kube-proxy 3 3 3 3 3 30h
> 
> NAMESPACE NAME DESIRED CURRENT UP-TO-DATE AVAILABLE AGE
> kube-system deployment.extensions/kube-dns 1 1 1 1 30h
> kube-system deployment.extensions/kubernetes-dashboard 1 1 1 1 30h
> kube-system deployment.extensions/tiller-deploy 1 1 1 1 3h20m
> 
> NAMESPACE NAME DESIRED CURRENT READY AGE
> kube-system replicaset.extensions/kube-dns-855949bbf 1 1 1 30h
> kube-system replicaset.extensions/kubernetes-dashboard-7c966ddf6d 1 1 1 30h
> kube-system replicaset.extensions/tiller-deploy-78dfcfd45d 1 1 1 3h20m
> 
> NAMESPACE NAME DESIRED CURRENT READY UP-TO-DATE AVAILABLE NODE SELECTOR AGE
> kube-system daemonset.apps/kube-flannel-ds 3 3 3 3 3 beta.kubernetes.io/arch=amd64 30h
> kube-system daemonset.apps/kube-proxy 3 3 3 3 3 30h
> 
> NAMESPACE NAME DESIRED CURRENT UP-TO-DATE AVAILABLE AGE
> kube-system deployment.apps/kube-dns 1 1 1 1 30h
> kube-system deployment.apps/kubernetes-dashboard 1 1 1 1 30h
> kube-system deployment.apps/tiller-deploy 1 1 1 1 3h20m
> 
> NAMESPACE NAME DESIRED CURRENT READY AGE
> kube-system replicaset.apps/kube-dns-855949bbf 1 1 1 30h
> kube-system replicaset.apps/kubernetes-dashboard-7c966ddf6d 1 1 1 30h
> kube-system replicaset.apps/tiller-deploy-78dfcfd45d 1 1 1 3h20m
> bash-4.2$

**Comment by hickeyma** [comment]
On system that you ran `kubectl`, can you run: `helm init --upgrade` or equivalent that suits your security setup.

**Comment by KaushikRout** [comment]
bash-4.2$ helm init --upgrade
bash-4.2$ helm init --upgrade
$HELM_HOME has been configured at /home/xxxxx/.helm.

Tiller (the Helm server-side component) has been upgraded to the current version.
Happy Helming!

After runnig this also the, I see the same issue

**Comment by KaushikRout** [comment]
Just to add.. This was working fine a few days back on another box/setup. Today I setup a new box with the same user and it stopped working on the older setup as well. (the directory /home/xxxx/ is common for a given user)

**Comment by bacongobbler** [comment]
Behind the scenes, helm initialized a `kubectl port-forward` to tiller. Can you try establishing a connection to tiller manually using `kubectl port-forward -n kube-system NAME-OF-TILLER-POD 44134:44134`? Sometimes the cluster hasn’t been properly configured to handle those requests.

**Comment by hickeyma** [comment]
something like this: `kubectl -n kube-system port-forward $(kubectl -n kube-system get pod -l app=helm -o jsonpath='{.items[0].metadata.name}') 44134 `

**Comment by KaushikRout** [comment]
> Behind the scenes, helm initialized a `kubectl port-forward` to tiller. Can you try establishing a connection to tiller manually using `kubectl port-forward -n kube-system tiller-deploy-78dfcfd45d 44134:44134`? Sometimes the cluster hasn’t been properly configured to handle those requests.

Its just hung there now. No output...

**Comment by KaushikRout** [comment]
> something like this: `kubectl -n kube-system port-forward $(kubectl -n kube-system get pod -l app=helm -o jsonpath='{.items[0].metadata.name}') 44134 `

bash-4.2$ kubectl -n kube-system port-forward $(kubectl -n kube-system get pod -l app=helm -o jsonpath='{.items[0].metadata.name}') 44134
error: error upgrading connection: error dialing backend: dial tcp xx.xxx.xx.xxx:xxxxx: getsockopt: connection timed out
bash-4.2$

**Comment by bacongobbler** [comment]
Okay. It would appear that the backend supporting the `kubectl port-forward` APIs is not configured properly. You’ll have to look into Kubernetes’ troubleshooting documentation and see if there’s anything to help diagnose this issue. There’s nothing on our end that we can do here, unfortunately.

Once you have that fixed, helm should work again.

**Comment by KaushikRout** [comment]
Could it be because I am on VPN connection... by any chance

**Comment by bacongobbler** [comment]
I can’t say that for certain, but it could be a factor.

Let us know how you fixed the issue once it’s resolved. Thanks!

**Comment by KaushikRout** [comment]
> I can’t say that for certain, but it could be a factor.
> 
> Let us know how you fixed the issue once it’s resolved. Thanks!

Okay .. thanks for your time.

**Comment by bridgetkromhout** [comment]
Hi, @KaushikRout - if you're still experiencing issues, please try Helm v3; tiller has been removed, so you should no longer have this problem. Helm 2 will no longer be updated soon: https://helm.sh/blog/helm-v2-deprecation-timeline/ - thanks!

**Comment by kayleyang** [comment]
unset you proxy

**Comment by gw0** [comment]
> unset you proxy

Confirmed. Kubectl port-forwarding does not work if you set environment vars `http_proxy`/`https_proxy` or set `proxy-api` in `~/.kube/config`. Other commands work correctly.

Steps to reproduce (first open a Socks5 proxy on 172.17.0.1:1080):

```bash
## other commands work with proxy
$ https_proxy=socks5://172.17.0.1:1080 kubectl version --short=true
Client Version: v1.23.1
Server Version: v1.21.6-gke.1500

## port-forwarding fails with proxy
$ https_proxy=socks5://172.17.0.1:1080 kubectl port-forward svc/my-server 8080:80
error: error upgrading connection: error sending request: Post "https://1.2.3.4/api/v1/namespaces/argocd/pods/my-server-bc59fd78c-59knp/portforward": EOF
```

Has anyone found the relevant upstream bug?
