### ISSUE TITLE
Helm version does not return server version in v3.0.0

### ISSUE THREAD

**Issue by VincentDehaye** [helm/helm#7113]
Hi, I was surprised not to get the error message 

> Error: incompatible versions client[vX.X.X] server[vX.X.X]

when running ```helm version``` on my client. It actually only returned the client version (cf. output below). 

Is this the expected behaviour? Downgrading helm back to 2.16 fixed the problem, so it was indeed a version incompatibility issue, and it would have been informative to get the error message.

<details>
<summary>Output of helm version:</summary>

```
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}

```

</details>

<details>
<summary>Output of kubectl version:</summary>

```
Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-eks-5876d6", GitCommit:"5876d6b7429820450950ade17fe7b4bf5ccada7f", GitTreeState:"clean", BuildDate:"2019-09-25T21:45:11Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-eks-b7174d", GitCommit:"b7174db5ee0e30c94a0b9899c20ac980c0850fc8", GitTreeState:"clean", BuildDate:"2019-10-18T17:56:01Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```EKS```

**Comment by zwwhdls** [comment]
Hi, tiller in Helm v3 is deleted.

**Comment by hickeyma** [comment]
As @zwwhdls mentioned, Tiller is removed and from Helm 3 onwards, it is a client only architecture. You will get more details in the docs and differences from Helm 2 in https://helm.sh/docs/faq/#changes-since-helm-2. It is worth checking out the docs because of the changes from Helm 2.

**Comment by hickeyma** [comment]
Closing as issue answered. FYI @VincentDehaye re questions, it is probably worth asking in the `helm-users` slack channel first.
