### ISSUE TITLE
`helm status` does not display the same thing in version 3 and version 2

### ISSUE THREAD

**Issue by olivierchatry** [helm/helm#7121]
Helm 2 use to display a list of what is deployed on the cluster when using `helm status` in 'table' mode. 
Helm 3 just displays deployment status now. ( it does return information in YAML or JSON mode ).

Would be cool if helm 3 can display the same informations as helm 2 ( or have an output mode to do so ).

**Comment by marckhouzam** [comment]
Thanks for the report.
Duplicate of #5952 where you can find information on the reasons behind this change.

**Comment by olivierchatry** [comment]
Thanks a lot. I guess my search skills are becoming dull :(. Sorry for the duplicate, closing this one. Make sense to remove the code of it is duplicate.
