### ISSUE TITLE
Upgrading a non-Helm resource into Helm (without deleting)

### ISSUE THREAD

**Issue by phillycheeze** [helm/helm#7129]
### Summary

Currently, there is no way to take existing resources and "import" or "map" them into a Helm release. The workaround for version 2 of Helm was to try and initially install or upgrade the release. In this workaround, you would get an error (resource conflict) error on the first try but then it would work on the second try. This was due to a release being created after the error but being in a failed state, and the second time it would usually adopt the conflicting resources.

With Helm 3, this workaround no longer works. A failed helm install of a chart where existing resources exist does not create the release, so simply running the command again results in the same error.

### Reasoning

For organizations that currently manage a release via kubectl commands, it is very difficult to migrate the release process to use helm charts instead. The only ways of doing it currently are to create the chart in a new namespace or force the creation of the release which deletes the old resources first. The first method makes migration a pain once many resources outside of the chart are configured for a particular namespace, and the second method causes downtime (and fingers crossed the release installs correctly after it deletes the old resources).

### Related Issues
https://github.com/helm/helm/issues/2730 
https://github.com/helm/helm/issues/1999
and others.

Output of `helm version`:
`version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}`

Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:29Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.12-eks-c500e1", GitCommit:"c500e11584c323151d6ab17526d1ed7461e45b0c", GitTreeState:"clean", BuildDate:"2019-10-22T03:11:52Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): EKS

**Comment by dastrobu** [comment]
I cannot provide an answer, but currently we discuss the same issue with our team: how to migrate form a non-helm-managed release into a helm managed one without downtime. Any hint how to do this in a proper way would be welcome. 
@paddycarey can you explain your second method, how do you "force the creation of the release" and tell Helm to delete and create objects?

**Comment by paddycarey** [comment]
@dastrobu think you've tagged the wrong person perhaps?

**Comment by bacongobbler** [comment]
Hi @phillycheeze, because this issue has been raised before and is still open as #2730, I'm going to go ahead and close this as a duplicate. Let's keep the conversation going on in the same ticket so we're not having the same conversation twice. Thanks!

**Comment by bacongobbler** [comment]
See also https://github.com/helm/helm/issues/7082.

**Comment by dastrobu** [comment]
> @dastrobu think you've tagged the wrong person perhaps?

autocompletion fooled me. I corrected it (thanks for letting me know).
