### ISSUE TITLE
Does helm do verification before CRDs install

### ISSUE THREAD

**Issue by daixiang0** [helm/helm#7131]
Refer to [doc](https://helm.sh/docs/topics/charts_hooks/), after CRDs create, helm do verification then renders templates.

Is it right or missing in docs?

**Comment by daixiang0** [comment]
@hickeyma Hi, mind have a look?

BTW, i find that if still put crds under `template` and no `crds` dir, crd still can be created/deleted, my helm version:
```
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}

```

**Comment by bacongobbler** [comment]
Yes, this is true. Resources are validated against Kubernetes' OpenAPI validation. See https://github.com/helm/helm/blob/f388224186dd22f402622541c65cf977626722ee/pkg/kube/client.go#L126

**Comment by daixiang0** [comment]
@bacongobbler is it normal:
i find that if still put crds under `template` and no `crds` dir, crd still can be created/deleted, my helm version:
```
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

**Comment by bacongobbler** [comment]
Yes

**Comment by daixiang0** [comment]
So the `crds` dir is recommended not necessary?
