### ISSUE TITLE
crds directory can create any resources

### ISSUE THREAD

**Issue by invidian** [helm/helm#7132]
It seems that `helm` allows to create any kind of resources using `crds` directory, which will be created, but won't be part of the release. That for example, allows to put a **`Namespace`** and RBAC resources there, which allows to actually create a namespace for the release when doing `helm install`. I'm pretty sure this is unintended behavior.

Attaching example chart which can be used to reproduce the issue. Install it with `helm install --namespace bar foo ./foo/`.

[foo.tar.gz](https://github.com/helm/helm/files/3915494/foo.tar.gz)

Output of `helm version`: `version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}`

**Comment by bacongobbler** [comment]
I know @technosophos had a conversation with a community member at Helm Summit EU about this behaviour in a hallway discussion, but I cannot remember if the conversation resolved to determine if this behaviour was intentional or not. I'll defer to the other maintainers on this one.

**Comment by technosophos** [comment]
It was intended behavior, with side benefits being that you could create namespaces as well. We debated naming the directory `unmanaged/`, but decided that since the base case was CRDs, and we didn't really want to encourage people to put namespaced things in there, we would just label it `crds/`.
