### ISSUE TITLE
If statement is executed despite being commented

### ISSUE THREAD

**Issue by doandzhiFt** [helm/helm#7134]
**Output of `helm version`:**

Client: &version.Version{SemVer:"v2.16.0", GitCommit:"e13bc94621d4ef666270cfbe734aaabf342a49bb", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.0", GitCommit:"e13bc94621d4ef666270cfbe734aaabf342a49bb", GitTreeState:"clean"}

**Output of `kubectl version`:**

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", 
Platform:"linux/amd64"}

**Cloud Provider/Platform (AKS, GKE, Minikube etc.):** 

Minikube

**Actual problem:**

Despite being commented with '#' the following if statement is being executed:

{{- if ne .Values.something "something else" }}
some configuration
{{- end }}
some other configuration

Is this the expected behaviour?

**Comment by bacongobbler** [comment]
Helm uses Go’s text/template library for template execution. I think this may be a better question for upstream.

https://golang.org/pkg/text/template/

**Comment by hickeyma** [comment]
@doandzhiFt Did you get a chance to ask upstream in Go’s text/template about its behaviour?

**Comment by bridgetkromhout** [comment]
Hi, @doandzhiFt - as this is not a Helm-specific issue we pointed you to https://golang.org/pkg/text/template/. I see this on that page:
```
{{/* a comment */}}
{{- /* a comment with white space trimmed from preceding and following text */ -}}
	A comment; discarded. May contain newlines.
	Comments do not nest and must start and end at the
	delimiters, as shown here.
```

Hopefully that helps. Please let us know if you have further Helm questions; thanks!
