### ISSUE TITLE
Namespace flag of the Install/Upgrade action not working correctly on the sdk

### ISSUE THREAD

**Issue by Sh4d1** [helm/helm#7135]
Helm sdk version: 3.0.0

Currently the `Namespace` https://github.com/helm/helm/blob/master/pkg/action/install.go#L78 flag is not passed down to the kube client. So when specifying it on a `Install` action and then running this action, all the object without specified namesapce will be created either in the `default` namespace or in the namespace retrieved by the `RESTClientGetter`. 

One solution is to always set the right namesapce when using the `RESTClientGetter`; however a new client has to be instanciated for each namespace. 
The other solution is to allow the `Namespace` flag to override the kubernetes namespace

**Comment by bacongobbler** [comment]
Were you able to identify the issue? Helm correctly passes the namespace parameter to the kubernetes client such that resources are installed in the specified namespace. I'd look inot how Helm initializes the kube client to see where the issue arises.

If you can provide a sample, that would be useful to identify the issue you are trying to point out. Thanks!

**Comment by Sh4d1** [comment]
@bacongobbler yes, issue identified, PR done to fix it. doesn't have the code right now but it's due to the fact that `--namespace` only works via the cli. Via the SDK, the kube namespace in only get from the kube client, and can't be changed (without changing the kube client). And when there is no kubeconfig, it's very easier juste to pass the `Namespace` flag to the action

**Comment by magicLian** [comment]
THX @Sh4d1 I mentioned this issue 2 months ago. Here is the slack https://kubernetes.slack.com/archives/C51E88VDG/p1574920728380400
