### ISSUE TITLE
Adding the service protocol with same port during a helm upgrade

### ISSUE THREAD

**Issue by koreansh4632** [helm/helm#7137]
I only use TCP as port 80, then add UDP to port 80 and do helm upgrade.
But when I check svc, I can only see either TCP or UDP.
If I do a new delete / install, I can see all TCP and UDP protocols for port 80.
Why can't I see two ports when upgrading?

ex)

> apiVersion: v1
kind: Service  
metadata:
  name: my-service
spec:
  selector:
    app: MyApp
  ports:
    - name: tcp
      protocol: TCP
      port: 80

> helm install chart --name myapp
> kubectl get svc 
i can see the TCP

> apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: MyApp
  ports:
    - name: tcp
      protocol: TCP
      port: 80
    - name: udp
      protocol: UDP
      port: 80

> helm upgrade myapp chart
> kubectl get svc
Still I can only see either TCP or UDP.

Output of `helm version`:
2.14.3
Output of `kubectl version`:
1.14.3
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
On-Premise

**Comment by zwwhdls** [comment]
Hi, "helm upgrade" calls PATCH resource api of apiServer. I have another try for it. When I use command "kubectl edit svc " to add a UDP port with the same port of TCP, I can still only see either TCP or UDP.

**Comment by koreansh4632** [comment]
Thank you for the reply !
Do you know any workaround or solution?
If not, Should I need to delete and re-install?

**Comment by zwwhdls** [comment]
Deleting svc with kubectl and reinstalling your chart will help.
