### ISSUE TITLE
helm repo update doesnt respect --repository-cache

### ISSUE THREAD

**Issue by trondhindenes** [helm/helm#7141]
Output of `helm version`:
`version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}`
Output of `kubectl version`:
N/A
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
N/A

Running `helm repo update` with the `--repository-cache` parameter seems to still fill the "default" cache path, and not the one specified in the parameter.

**Comment by marckhouzam** [comment]
I can confirm this.
I believe it's because the cache path is semi hard-coded here:
https://github.com/helm/helm/blob/a626f279ba227886bb94bd77b0fb1e3a994e051f/pkg/repo/chartrepo.go#L75

@trondhindenes do you want to take a stab at fixing this?

**Comment by trondhindenes** [comment]
thanks for confirming. I'm not a go dev, but let me poke around a bit. I'll report back if/when I give up :-)

**Comment by trondhindenes** [comment]
Tricky. This is probably not the place for me to learn go. I see that I can add a `cachePath` parameter like so, and fill it from `repo_update.go`:

`func NewChartRepository(cfg *Entry, getters getter.Providers, cachePath string) (*ChartRepository, error) {`, 
but that breaks all other kinds of functionality so I think I'd better leave it to the pros. Giving up :-)

**Comment by trondhindenes** [comment]
so, I goofed around a bit. It works, but I have no idea if its the "correct" way to implement things.
