### ISSUE TITLE
v3.0.0 SHA sum error while installation on eks cluster

### ISSUE THREAD

**Issue by SripriyaMenon** [helm/helm#7145]
Hi,
I have seen multiple issues with this error and all of them mentioned to use export DESIRED_VERSION ( which i have rightly used here). But still I keep getting these errors. I am not sure what is it that i am doing wrong. I am trying to install this on my kubernetes cluster. It already had a tiller installed for v2, that i have now uninstalled. 

Is there an easier wary to upgrade v2 to v3 on the kubernetes cluster?

$ export DESIRED_VERSION=V3.0.0
$ curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > get_helm.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  6617  100  6617    0     0  35767      0 --:--:-- --:--:-- --:--:-- 35767
$ chmod 700 get_helm.sh
$ ./get_helm.sh
Downloading https://get.helm.sh/helm-V3.0.0-linux-amd64.tar.gz
SHA sum of /tmp/helm-installer-JkChcT/helm-V3.0.0-linux-amd64.tar.gz does not match. Aborting.
Failed to install helm
	For support, go to https://github.com/helm/helm.

**Comment by bacongobbler** [comment]
Please change DESIRED_VERSION to use a lowercase "v". `export DESIRED_VERSION=v3.0.0` should work for you. Thanks!
