### ISSUE TITLE
[Helm 3] helm package requires argument

### ISSUE THREAD

**Issue by james-r-smith** [helm/helm#7155]
According to the description for `helm package`:

> If no path is given, this will look in the present working directory for a
Chart.yaml file, and (if found) build the current directory into a chart.

But this is not the case, shown by running `helm package`:
```
Error: need at least one argument, the path to the chart
```

Recommended solution, rather than throwing an error if no args are provided, append to `args`:
```
if len(args) == 0 {
  args = append(args, ".")
}
```

Should be an easy enough PR. 😉 Only one change to the tests should be needed. I don't have `golangci-lint`, so I couldn't run the tests locally.

Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

Output of `kubectl version`: N/A

Cloud Provider/Platform (AKS, GKE, Minikube etc.): N/A

**Comment by zwwhdls** [comment]
Hi, 

As "helm template" and "helm template ." did, I think it's better to update the cmd "helm package" description instead of appending the default arg to follow cmd behavior continuity.

Besides, whatever recommends are accepted, I would like to create a pr to fix it. 😺

**Comment by bacongobbler** [comment]
A change to the help string to fix this inconsistency in the docs would be much appreciated. Thanks!

**Comment by james-r-smith** [comment]
My reasoning for the suggested fix is because `helm lint` behaves the same way with no arguments. Is there any reasoning for not adding this functionality? I think a default path of current directory isn't a bad option, but again, it's just a recommended solution. 😊 👍

**Comment by anshulvermapatel** [comment]
I think we should change the lint command to have atleast 1 argument rather than taking the current directory. The reason is that a directory represents a chart which has all the required file in it, so suppose a user working on multiple Charts and has untared the charts may be to modify the Chart.yaml, and he/she don't have to cd into the directory and this is how any other project behaves.

I can work on whetever suggested. Please do let me know.

**Comment by technosophos** [comment]
We are stuck with the current behavior of `helm lint` until Helm 4 (because of our backward compatibility requirements).

I added #8051 to capture the requirement for Helm 4.
