### ISSUE TITLE
helm3  install error

### ISSUE THREAD

**Issue by Dlarmor** [helm/helm#7156]
$ helm install jenkins https://hub.helm.sh/charts/stable/jenkins --version lts
Error: file '/home/ubuntu/.cache/helm/repository/jenkins' does not appear to be a gzipped archive; got 'text/html; charset=utf-8'

$ helm install kanister-mysql  kanister/kanister-mysql --version 0.22.0
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1", unable to recognize "": no matches for kind "Blueprint" in version "cr.kanister.io/v1alpha1"]

$ helm install stash-mysql-8.0.14 appscode/stash-mysql  --version=8.0.14
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Function" in version "stash.appscode.com/v1beta1", unable to recognize "": no matches for kind "Task" in version "stash.appscode.com/v1beta1"]

Output of `helm version`: v3.0.0

Output of `kubectl version`:  1.16

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by marckhouzam** [comment]
For the installation of Jenkins error, you cannot install directly from helm hub. The maintainers are working to allow that but I don't believe it's ready. You should instead use `stable/jenkins` (after adding the standard stable repo).

For the other two failures, it looks like the charts use custom resource definitions (crds), which were not installed yet.  I know helm 3 handles crds differently so maybe these two charts need to be updated to work with helm 3?
