### ISSUE TITLE
[Helm 3] Rollback to last successful release fails with --atomic flag in helm3

### ISSUE THREAD

**Issue by GaykarSanket** [helm/helm#7158]
Output of `helm version`: helm version
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}

Output of `kubectl version`: kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3+coreos.0", GitCommit:"f96beb2e925b0bb4e6ac0de746c7155dcd8fdc10", GitTreeState:"clean", BuildDate:"2017-11-13T10:18:37Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3+coreos.0", GitCommit:"f96beb2e925b0bb4e6ac0de746c7155dcd8fdc10", GitTreeState:"clean", BuildDate:"2017-11-13T10:18:37Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  GCP

Deployed one of the helm chart successfully.
`helm list -n helm-test`
<img width="597" alt="helm1" src="https://user-images.githubusercontent.com/29541659/70209299-ed5a5280-1755-11ea-91df-76fdba274f2e.PNG">

`helm history tag-manager-api -n helm-test`
<img width="521" alt="helm2" src="https://user-images.githubusercontent.com/29541659/70209491-678ad700-1756-11ea-90d8-a8ee530d211f.PNG">

`Issue:`
After upgrading the release with newer changes with --atomic flag it fails to upgrade with following error
`helm upgrade tag-manager-api ./ --install --namespace helm-test --atomic`
`Error: UPGRADE FAILED: an error occurred while rolling back the release. original upgrade error: the server could not find the requested resource: release tag-manager-api failed: the server could not find the requested resource`

Release should be rolled back to previous version after failed upgrade which didn't happened...
`helm history tag-manager-api -n helm-test`
<img width="781" alt="helm3" src="https://user-images.githubusercontent.com/29541659/70209883-59898600-1757-11ea-8e6f-bf3cb547fcb1.PNG">

Seems like there is some bug here.....

**Comment by bacongobbler** [comment]
Hey @GaykarSanket, can you please provide a reproducible test case where we can test this?

A contributing factor may be your version of Kubernetes. It's unclear whether this could be a bug due to the cluster's current state. 1.8 is currently unsupported, so it's possible there may be an interaction with Helm and Kubernetes that we cannot predict here. Helm currently supports n-3 releases back, which would be Kubernetes 1.13. Can you please re-test this behaviour with a more recent version of Kubernetes?

**Comment by GaykarSanket** [comment]
Thanks @bacongobbler. I've tested this behavior on minikube with kubernetes version 1.14.1 and it's working fine. Release gets rolled back to previous successful release after a failed upgrade.

<img width="647" alt="helm4" src="https://user-images.githubusercontent.com/29541659/70407830-d4121880-1a6b-11ea-8edf-7eef63fd67cd.PNG">

Steps to reproduce this error:

1.  Login to kubernetes cluster with following version
`Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3+coreos.0", GitCommit:"f96beb2e925b0bb4e6ac0de746c7155dcd8fdc10", GitTreeState:"clean", BuildDate:"2017-11-13T10:18:37Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3+coreos.0", GitCommit:"f96beb2e925b0bb4e6ac0de746c7155dcd8fdc10", GitTreeState:"clean", BuildDate:"2017-11-13T10:18:37Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}`

2. Install stable version of Helm i.e. v3
`version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}`

3. Create default helm chart of nginx 
`helm create nginx`

4. Change apiVersion of deployment to **extensions/v1beta1** as **apps/v1** is not supported in v1.8
Update the deployment file: `vim nginx/templates/deployment.yaml` 

5. Now install nginx helm chart:
`helm upgrade nginx-test --install ./nginx/`

6. Check status of deployed release:
`helm history nginx-test`

7. Now update the values file and set image repository value to something which doesn't exists e.g. nginx123. So that upgrade will fail....
`vim nginx/values.yaml`

8. Upgrade the release with latest changes adding --atomic flag:
`helm upgrade nginx-test --install --atomic ./nginx/`
Above command gives output like: `Error: UPGRADE FAILED: an error occurred while rolling back the release. original upgrade error: the server could not find the requested resource: release nginx-test failed: the server could not find the requested resource`

9. Check history of release:
`helm history nginx-test`

![helm6](https://user-images.githubusercontent.com/29541659/70409349-72ed4380-1a71-11ea-88ab-58dcbcac7513.png)

Seems like --atomic flag has some issue while finding resources to roll back with kubernetes version 1.8...

**Comment by bacongobbler** [comment]
All right. Given that our support contract is for support 3 versions back from the latest, we urge you to upgrade to a newer version of Kubernetes. No action to take on our end here. Thanks.
