### ISSUE TITLE
Add --dependency-update flag to the helm upgrade command

### ISSUE THREAD

**Issue by damodhar22** [helm/helm#7162]
Output of `helm version`:v3.0.0

Output of `kubectl version`:v1.15.0

Cloud Provider/Platform (AKS, GKE, Minikube etc.): EKS

**Comment by hickeyma** [comment]
@damodhar22 Can you provide more context and details on the feature you are requesting/

**Comment by damodhar22** [comment]
@hickeyma helm install has an option --dependency-update, which can download all the dependencies 
provided in Charts.yaml without explicitly running helm dep update command. 

I am using the below command to both install and update helm charts 
helm upgrade --install myrelease mychart
Here I had to run  helm dep update command as the helm upgrade command do not have --dependency-update option.

**Comment by DocX** [comment]
@hickeyma I've just run to the same thing, we use `helmfile` which internally uses `helm upgrade` which causes the error on dependencies when I do not have them installed locally. It took me some time to understand it. It would be great if upgrade can accept the option to just do it internally. WDYT?

**Comment by hickeyma** [comment]
@DocX It is an open feature if you would like to work on it.

**Comment by janario** [comment]
PR https://github.com/helm/helm/pull/8810

**Comment by jaksky** [comment]
Guys how do you updadate dependecies when chart is from remote repository? e.g. stable/xxx

**Comment by janario** [comment]
@jaksky 
When you try to package a chart to update to the remote and it has requirements that were not resolved it will complain

```
helm package .
Error: found in Chart.yaml, but missing in charts/ directory: mysql
```

helm package provides a flag to help with that

```
helm package --dependency-update .
Successfully packaged chart and saved it to: /home/janario/Projects/my-chart-0.0.1.tgz
```

so I suppose all the remote charts will always have its dependencies

**Comment by jaksky** [comment]
@janario I am new to helm but wondering as I am installing/upgrading stuff via `helm upgrade --install prometheus. stable/prometheus ...` 
Locally I see manifests rendered correctly but latter on getting an error.

Can helm package even remote charts? I am struggling with stable/prometheus  with dependant kube-state-metrics which is dependency from that chart.

**Comment by janario** [comment]
@jaksky not sure but I guess it goes a bit out of the scope of this issue

Try to ask some help at slack or some other community channel 

https://github.com/helm/community/blob/master/communication.md#slack
