### ISSUE TITLE
Godoc badge link broken

### ISSUE THREAD

**Issue by rbren** [helm/helm#7165]
The godoc badge on the readme leads to a 404.

I'd like to use Helm programmatically from a Golang app, was hoping to find some docs there.

**Comment by mattfarina** [comment]
Godoc does not know how to handle Go modules so we should switch to pkg.go.dev. A link for that is https://pkg.go.dev/helm.sh/helm/v3. PR's welcome.

**Comment by rbren** [comment]
Thanks for the pointer, PR opened!
