### ISSUE TITLE
Proposal: Mention about Helm slack channels first thing in the readme

### ISSUE THREAD

**Issue by karuppiah7890** [helm/helm#7167]
If there's a focus on building the community to discuss and talk about helm more then we could do something that https://github.com/instrumenta/conftest repo does. They put their slack channel as the first thing in the readme. Inspired by this, we could do something similar, if not exactly the same. Just a thought 😄

**Comment by bacongobbler** [comment]
Good suggestion. We mention them in the [CONTRIBUTING doc](https://github.com/helm/helm/blob/master/CONTRIBUTING.md#support-channels), but higher visibility in the project README is good too.

**Comment by karuppiah7890** [comment]
We do mention it in the readme, at the end https://github.com/helm/helm#community-discussion-contribution-and-support , I just wanted to say we could mention it as the first thing

**Comment by hickeyma** [comment]
@karuppiah7890 The README is quite small and the slack channel information seems obvious enough. Also, I would think its best to give an overview of the project first.  I am happy enough with the flow of the doc also as its is pretty concise and succinct.

What do other people think?

**Comment by marckhouzam** [comment]
I believe the Helm README currently follows standard README formats.

Wanting to help the community find the slack channels is a good goal but we also have many newcomers looking to the README for information about what Helm is about.

Personally, I think that if someone has reached the point of wanting to communicate with the project, they will take the time to read the README far enough to find the slack channels.  So I wouldn't change the format, at the expense of the many, to accommodate the few that don't make that effort.

**Comment by karuppiah7890** [comment]
I'm all into standards. I just wanted to put it as the first thing so that people don't have to search much. I wouldn't put a lot of burden on a user trying to join the community 😅 anyways, just upvote or downvote on the issue. 

Let's close it soon. I'm okay with either options. Was just proposing. 

Also, it rings a bell for me that recently we had someone join our Helm developer call (idk how they found out about the call, readme?) And asked how to join our slack. For me that's enough reason to just put it on the top. To increase community interaction. :)

**Comment by karuppiah7890** [comment]
Considering that we felt that the current README is good enough, I'm going to close this issue to reduce the number of issues we have 😛
