### ISSUE TITLE
No more installation instructions in Helm 2 doc 

### ISSUE THREAD

**Issue by phcollignon** [helm/helm#7169]
Hello,

There is no more installation instructions in the default Helm 2 documentation for latest Helm 2 release
(https://v2.helm.sh/docs/using_helm/#installing-helm)

It is still there for 2.14 but not for 2.16.

Regards,

**Comment by bacongobbler** [comment]
Hi @phcollignon. I'm confused about your question. Can you please point out the specific area in the documentation you are raising an issue about? I don't see anything specific about 2.16 or 2.14. The installation instructions for both should be the exact same: install helm using your favourite package manager.

**Comment by phcollignon** [comment]
Hi @bacongobbler 
The Installation section in v2.16.1 doc has dissapear : https://v2.helm.sh/docs/using_helm/#installing-helm
In v2.14.0 it is still available : https://v2-14-0.helm.sh/docs/using_helm/#installing-helm

**Comment by bacongobbler** [comment]
rebuilding the site seemed to do the trick. https://v2.helm.sh/docs/using_helm/#installing-helm now works. Thanks for raising this.
