### ISSUE TITLE
helm3: repo add no longer interactively asks for password 

### ISSUE THREAD

**Issue by erpel** [helm/helm#7174]
Output of `helm version`: version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}

With helm v2, passing --username myname to helm repo add caused helm to interactively ask for a password which is positive for security reasons (not having a password show up in process lists and shell histories, the password being shadowed while entering).

helm v3 seems to have lost this ability, which looks like a regression to me.

**Comment by bacongobbler** [comment]
This was likely introduced to helm 2 after the fork. It shouldn’t be too difficult to port over to helm 3. Want to take a crack at porting it over?

**Comment by erpel** [comment]
I'm not opposed but it might be a while before I get the time to look at even setting up a dev environment for helm.

**Comment by bacongobbler** [comment]
FYI: https://helm.sh/docs/community/developers/

**Comment by strainovic** [comment]
It would be nice if we can have back this feature as at the moment password can be found in .bash_history file etc.

**Comment by bridgetkromhout** [comment]
@bacongobbler I noticed a build failure in the PR that closed this issue: https://app.circleci.com/pipelines/github/helm/helm/995/workflows/f92278eb-ff0a-4794-b50a-45fdab708fba/jobs/12524/steps

`cmd/helm/repo_add.go:121:41: cannot use syscall.Stdin (type syscall.Handle) as type int in argument to terminal.ReadPassword`

**Comment by bacongobbler** [comment]
fixed in #8432.
