### ISSUE TITLE
Helm fetch untar needs conflict management

### ISSUE THREAD

**Issue by clintmoyer** [helm/helm#7182]
Fetching and extracting charts to the local system does not currently warn the user when the chart name conflicts with an existing file or directory. Instead it has ambiguous behavior depending on the conflict.

Two ambiguous conflicts:

1. File exists in `$PWD` with same name

   Download fails with error message
   ```
   $ echo test > velero
   $ helm fetch stable/velero --untar
   Error: open velero/Chart.yaml: not a directory
   $ cat velero 
   test
   ``` 

2. Directory exists in `$PWD` with same name

   Download succeeds but gets merged into existing directory

   ```
   $ mkdir velero
   $ echo test > velero/test.txt
   $ helm fetch stable/velero --untar
   $ ls velero/
   Chart.yaml	OWNERS		README.md	ci		crds		templates	test.txt	values.yaml
   $ cat velero/test.txt 
   test
   ```

Output of `helm version`:

```
$ helm version --client
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

Output of `kubectl version`:

```
$ kubectl version --client
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

AWS

**Comment by karuppiah7890** [comment]
I think we should stop the command immediately and show the error that a file or directory with that name already exists and that we cannot proceed further

**Comment by karuppiah7890** [comment]
The same issue occurs even with helm v3

`version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}`

We can mark this as both v2 and v3 issue. I also see this as a bad UX as the error that shows up is not clear as to what's the problem when there's already a file in that name. And the latter - existing directory with same name, it's problematic as it's possible that user might not be aware that there's already a directory in that name and it's all getting merged. One such example is when let's say I'm trying out multiple versions of the same chart using untar 

```
$ helm fetch stable/redis --untar
$ ls redis
Chart.yaml              ci                      values-production.yaml  values.yaml
README.md               templates               values.schema.json
$ cat redis/Chart.yaml
...
...
version: 10.2.1
$ helm fetch stable/redis --untar --version 10.2.0
$ # same redis directory gets modified because of the merge
$ ls redis
Chart.yaml              ci                      values-production.yaml  values.yaml
README.md               templates               values.schema.json
$ cat redis/Chart.yaml
...
...
version: 10.2.0
```

**Comment by mattfarina** [comment]
I agree that we should stop with an error immediately if a file or directory with that name already exists. Does someone want to create a PR for this?

**Comment by zwwhdls** [comment]
@mattfarina Hi, I think we should distinguish the existed file and directory. I would like to take the chance to create a PR for this. 😁

**Comment by karuppiah7890** [comment]
@zwwhdls I see you raised a PR against `master` branch for Helm v3, could you also raise a PR for Helm v2 in `dev-v2` branch? 😄

**Comment by zwwhdls** [comment]
@karuppiah7890 of course! I'd like to do this!

**Comment by mumrau** [comment]
Sorry to bring this up again, but I believe a flag like `--erase``or something else should provide the capacity to override a previous untar-ed bundle. This owuld bring idempotency to many processes.

**Comment by guneemwelloeux** [comment]
> Sorry to bring this up again, but I believe a flag like `--erase``or something else should provide the capacity to override a previous untar-ed bundle. This would bring idempotency to many processes using helm cli.

I agree with this proposal. We use helm cli in one of our automated build processes, and some processes broke when I upgraded from helm 2.12 to 2.16.9

**Comment by porterfc** [comment]
This fix broke several of our deployments that count on pull --untar going into an existing directory that has additional components we want to add to the deployment.
I know we could split it out into separate pull and untar steps, but fixes should not break existing processes.
