### ISSUE TITLE
More issue templates.

### ISSUE THREAD

**Issue by cdrage** [helm/helm#7190]
To elaborate on PR: https://github.com/helm/helm/pull/7181 this is the discussion issue with regards to adding multiple issue templates.

I propose that we add the following issue templates:

- Bug report template
- Documentation template
- Enhancement template
- Support template

The benefits include:

- Automatic labeling, so no need for maintainers to get involved.
- Directing the user to appropriate channels before opening up a support issue
- Added more information required with regards to bug report to help determine the issue.

**Comment by bacongobbler** [comment]
closing as stale.
