### ISSUE TITLE
helm3: metadata.name Invalid value

### ISSUE THREAD

**Issue by faizanbashir** [helm/helm#7191]
I was following the article on [helm](https://helm.sh/docs/intro/getting_started/) section 'A FIRST TEMPLATE' and when I ran the command `helm install ./chartone --generate-name`, I got this error:
`Error: create: failed to create: Secret "sh.helm.release.v1.chartOne.v1" is invalid: metadata.name: Invalid value: "sh.helm.release.v1.chartOne.v1": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')`

I am new to Helm, any help is appreciated.

Output of `helm version`: `version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}`

Output of `kubectl version`: `Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:34Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-eks-b8860f", GitCommit:"b8860f6c40640897e52c143f1b9f011a503d6e46", GitTreeState:"clean", BuildDate:"2019-11-25T00:55:38Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  EKS

**Comment by bacongobbler** [comment]
What is the content on your Chart.yaml?

**Comment by faizanbashir** [comment]
> What is the content in your Chart.yaml? Make sure the `name` is all lowercase.

`apiVersion: v2
name: chartone
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 0.1.0`

**Comment by bacongobbler** [comment]
Can you identify where in your chart “chartOne” is being used? That capital “O” in your chart name is what’s causing the issue.

**Comment by hickeyma** [comment]
@faizanbashir It could be in one of the template files in the chart directory `chartone`. Might be worth doing a search for it?

**Comment by faizanbashir** [comment]
Couldn't find the capital "O". I deleted and re-created the chart, it's working fine now.

**Comment by RonNewcomb** [comment]
The reason this error is so confusing is because it isn't pulling the dislike value out of any file whatsoever.  The uppercased value its complaining about is in the `helm install` command line itself:

`helm install -f .helm/values.dev.yaml  chartOne  ./.helm/`
