### ISSUE TITLE
Helm 3.0.1 wrongly insists on StatefulSet having serviceName defined

### ISSUE THREAD

**Issue by youurayy** [helm/helm#7207]
1. according to https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-network-id:
"... A StatefulSet **can** use a Headless Service to control the domain of its Pods. ... "

2. the https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#statefulsetspec-v1-apps:
..does not explicitly state that the field is Optional, but,

3. `kubectl apply` (as well as prevoius Helm 3 versions) are perfectly happy with a `StatefulSet` without a `serviceName` defined, and in many (most) cases, this services is not needed.

Therefore, Helm 3 should not make it mandatory to use this field:
`Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StatefulSet.spec): missing required field "serviceName" in io.k8s.api.apps.v1.StatefulSetSpec`

Output of `helm version`:
`version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}`

Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:51:13Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}`
`Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:55Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
EKS, Hyper-V

**Comment by bacongobbler** [comment]
Coming straight from the OpenAPI spec itself for 1.15.4:

```
 "required": [
        "selector",
        "template",
        "serviceName"
      ],
```

https://raw.githubusercontent.com/kubernetes/kubernetes/v1.15.4/api/openapi-spec/swagger.json

**Comment by bacongobbler** [comment]
Closing as this is correct from upstream's point of view. Please open a ticket upstream if a `serviceName` should be considered optional.

**Comment by Nindaleth** [comment]
Upstream ticket: https://github.com/kubernetes/kubernetes/issues/69608

**Comment by blaghed** [comment]
From reading the upstream ticket, I interpret the result as "serviceName is optional".
Should that be reflect here now? Is there a different ticket for it, or should this one be re-opened?

**Comment by joejulian** [comment]
Helm doesn't validate resources. That error is coming from kube-apiserver.

**Comment by blaghed** [comment]
> Helm doesn't validate resources. That error is coming from kube-apiserver.

Odd... much like the original description in this ticket, if I make use of `kubectl` or use the UI directly, then they simply accept the input; I could only see it happening with helm.
Is there a particular API call that helm does that requests for validation from kube-apiserver, or how can there be difference in this behaviour?

**Comment by joejulian** [comment]
I was mistaken. This comes from the kubectl validator that checks resources against the openapi spec.

https://github.com/helm/helm/blob/269dd247d092ebc8f3ed486a4468aac2b48e6aaa/pkg/kube/client.go#L193-L216

https://github.com/kubernetes/kubectl/blob/4da03973dd2fcd4645f20ac669d8a73cb017ff39/pkg/cmd/util/factory_client_access.go#L145-L166

**Comment by blaghed** [comment]
> I was mistaken. This comes from the kubectl validator that checks resources against the openapi spec.
> 
> https://github.com/helm/helm/blob/269dd247d092ebc8f3ed486a4468aac2b48e6aaa/pkg/kube/client.go#L193-L216
> 
> https://github.com/kubernetes/kubectl/blob/4da03973dd2fcd4645f20ac669d8a73cb017ff39/pkg/cmd/util/factory_client_access.go#L145-L166


Ok, could confirm that, I just had the validation turned off when I ran the `kubectl` commands.
How can I disable this validation from helm side?

**Comment by joejulian** [comment]
Use the `--disable-openapi-validation` flag: https://helm.sh/docs/helm/helm_template/#options

**Comment by git-ajena** [comment]
I am using microk8s 1.21v in wiindows 10. I was getting an error "Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StatefulSet.spec): missing required field "serviceName" in io.k8s.api.apps.v1.StatefulSetSpec".
I upgraded the microk8s version to 1.26v/stable by login into the microk8s-vm shell. using cmd multipass shell your <microk8s vm name>. run a cmd in the ubuntu shell "sudo snap refresh microk8s --channel=1.26/stable". do according to your needs and required version. Hope it helps someone. @joejulian the flag worked for me but i opt to upgrade my microk8s version. And everything started working. Thanks .
