### ISSUE TITLE
Helm upgrade command is throwing an error

### ISSUE THREAD

**Issue by KevinHaisol** [helm/helm#7212]
Output of `helm version`:
Client: &version.Version{SemVer:"v2.14+unreleased", GitCommit:"fb2cbb001986b28dec5303f5acad65390a1a8118", GitTreeState:"clean"}
Server: &version.Version{SemVer:"canary+unreleased", GitCommit:"7ca75251d60995f866c7f77a41ae8f258fb8ab53", GitTreeState:"clean"}

Output of `kubectl version`:
Client: &version.Version{SemVer:"v2.14+unreleased", GitCommit:"fb2cbb001986b28dec5303f5acad65390a1a8118", GitTreeState:"clean"}
Server: &version.Version{SemVer:"canary+unreleased", GitCommit:"7ca75251d60995f866c7f77a41ae8f258fb8ab53", GitTreeState:"clean"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AKS

When running an upgrade command on our charts we are getting the error below.  I'm not sure whats causing the error or what line the error is on.  The dry run works without error.

UPGRADE FAILED
Error: failed to create patch: failed to create two-way merge patch: unable to find api field in struct ServiceSpec for the json field "nodeSelector" && failed to create patch: failed
to create two-way merge patch: unable to find api field in struct ServiceSpec for the json field "nodeSelector" && failed to create patch: failed to create two-way merge patch: unable
to find api field in struct ServiceSpec for the json field "nodeSelector" && failed to create patch: failed to create two-way merge patch: unable to find api field in struct ServiceSpec for the json field "nodeSelector" && failed to create patch: failed to create two-way merge patch: unable to find api field in struct DeploymentSpec for the json field "nodeSelector"Error: UPGRADE FAILED: failed to create patch: failed to create two-way merge patch: unable to find api field in struct ServiceSpec for the json field "nodeSelector" && failed to create patch: failed to create two-way merge patch: unable to find api field in struct ServiceSpec for the json field "nodeSelector" && failed to create patch: failed to create two-way merge patch: unable to find api field in struct ServiceSpec for the json field "nodeSelector" && failed to create patch: failed to create two-way merge patch: unable to find api field in struct ServiceSpec for the json field "nodeSelector" && failed to create patch: failed to create two-way merge patch: unable to find api field in struct DeploymentSpec for the json field "nodeSelector"

**Comment by bridgetkromhout** [comment]
Hi, @KevinHaisol - it's possible you've already sorted this out. In general, that kind of problem is often yaml-related (whitespace, quoting, indent level), and the linter in Helm 3 is much improved, so that may help. Please do let us know if problems persist! (If you have not yet moved to Helm 3, you will want to do that now: https://helm.sh/blog/helm-v2-deprecation-timeline/) - thanks.
