### ISSUE TITLE
helm install not validating if version of the dependency in Chart.yaml and the dependency in /chart folder is same

### ISSUE THREAD

**Issue by damodhar22** [helm/helm#7213]
Output of `helm version`:v3.0.0

Output of `kubectl version`:v15.0.0

Cloud Provider/Platform (AKS, GKE, Minikube etc.): EKS

**Comment by hickeyma** [comment]
@damodhar22 Do you mind adding an example of this so show how to reproduce?

**Comment by damodhar22** [comment]
> Output of `helm version`:v3.0.0
> 
> Output of `kubectl version`:v15.0.0
> 
> Cloud Provider/Platform (AKS, GKE, Minikube etc.): EKS

Steps to reproduce
Create a chart with the below dependency
dependencies:
- name: kube-state-metrics
  version: ~**2.2.3**
  repository: https://kubernetes-charts.storage.googleapis.com/

In the charts folder of your chart place the different version of dependency chart 
helm/charts/kube-state-metrics**-2.4.1**.tgz
       /Charts.yaml
      /Charts.lock

now execute helm install myrelease ./helm

Expectation: fail with mismatch of dependency version
Actual: the deployment is successful

**Comment by bacongobbler** [comment]
closing as stale.
