### ISSUE TITLE
helm 3 does not ship default repo

### ISSUE THREAD

**Issue by dns2utf8** [helm/helm#7215]
Hi all

I am new to helm but I noticed, that `helm install stable/...` does not work because the repo is not installed by default (anymore?)

A simple fix is to add it by hand:
```bash
helm repo install stable https://kubernetes-charts.storage.googleapis.com/ 
```

Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"clean", BuildDate:"2019-11-13T11:20:18Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
kubernetes on ubuntu 18.04.3 LTS

**Comment by hickeyma** [comment]
> I am new to helm but I noticed, that helm install stable/... does not work because the repo is not installed by default (anymore?)

Yes, that is correct. This is inline with Helm chart repository deprecation timeline: https://github.com/helm/charts#status-of-the-project

> `helm repo install stable https://kubernetes-charts.storage.googleapis.com/`

As you mentioned, this is the command to add the Helm chart repository.

The Helm docs cover adding the repo also: https://helm.sh/docs/intro/quickstart/#initialize-a-helm-chart-repository

**Comment by hickeyma** [comment]
Closing as answered.

**Comment by dns2utf8** [comment]
Ah, I see.

Do you think it is a good idea to add it to the [install instructions](https://helm.sh/docs/intro/install/)?

**Comment by hickeyma** [comment]
@dns2utf8 That might be a good idea. Would you like to push a PR to https://github.com/helm/helm-www (repo with docs for Helm 3) for the update?

**Comment by scottrigby** [comment]
We're also addressing it on the Hub: https://github.com/helm/hub/issues/210

**Comment by nenad** [comment]
Just an update for people looking for quick copy paste from Google. The command to add a repo is `helm repo add stable https://kubernetes-charts.storage.googleapis.com/` for Helm 3.

**Comment by thetestlabs** [comment]
> Just an update for people looking for quick copy paste from Google. The command to add a repo is `helm repo add stable https://kubernetes-charts.storage.googleapis.com/` for Helm 3.

The repo "https://kubernetes-charts.storage.googleapis.com/" is no longer available, so the correct command is now `helm repo add stable https://charts.helm.sh/stable` for Helm 3.
