### ISSUE TITLE
Regression with `helm package`

### ISSUE THREAD

**Issue by Hiruma31** [helm/helm#7220]
Hello,

There seem to be a bug that was reintroduced in Helm3

Running `helm package mychart/ -d ./` produces a .tgz archive. However, when extracting it...
`tar -xzf mychart.tgz` I get warning such as
`tar: mychart/Chart.yaml: implausibly old time stamp 1969-12-31 19:00:00`

This is happening in both 3.0.0 and 3.0.1.
It also seem to have been fixed last year
https://github.com/helm/helm/issues/4158
https://github.com/helm/helm/pull/4161/files

I guess [this comment](https://github.com/helm/helm/pull/4161#issuecomment-395656423) was forgotten ^^

Output of `helm version`:
version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}
Output of `kubectl version`: NA

Cloud Provider/Platform (AKS, GKE, Minikube etc.): NA

**Comment by karuppiah7890** [comment]
@Hiruma31 Would you be willing to get to the bottom of this issue and fix it ? 😄

**Comment by waveywaves** [comment]
@karuppiah7890 I will take this up

**Comment by karuppiah7890** [comment]
I don't have permissions to assign anyone. 

And let's wait for  @Hiruma31 to reply. Let's encourage more first time contributions to increase the number of contributors for the future :) this is good for sustainability

**Comment by waveywaves** [comment]
@karuppiah7890 Got it ! :)

**Comment by Hiruma31** [comment]
@karuppiah7890  Sure, I opened this issue as a faster mean to mention it so it could make it to the next bugfixes batch. I would have done it right away but I was at work and backed off when I saw how long it would take me to figure out the initial setup and contrib part.
I will get to it in a few days.

**Comment by karuppiah7890** [comment]
Cool! Let us know if you need any help 😄

**Comment by Hiruma31** [comment]
#7272 PR opened

**Comment by mattfarina** [comment]
Closing as this was fixed with #4161. Will be in an upcoming release.
