### ISSUE TITLE
Helm3 warning in case of missing values.yaml

### ISSUE THREAD

**Issue by PumpkinSeed** [helm/helm#7222]
**Problem**

It's mostly my own stupidity, but maybe it can help the future users of helm. So I renamed my `values.yaml` to `values-old.yaml`, and I created a value.yaml. Then I run `helm template .` and it's throw me issues it can't find the .Values.xxx however I double check the variable many times and they must correct. As a new helm user I thought something with my layout of the value.yaml. Than I read there is a command `helm lint .` and this told me there isn't `values.yaml` at all.

**Solution**
It make sense to me adding a warning in that case, something like _Anyway we are lack of values.yaml_. 

Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

Output of `kubectl version`: **not related**
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): **not related**

**Comment by bacongobbler** [comment]
closing as per the response laid out in #7234.
