### ISSUE TITLE
Helm install command cannot open file passed with -f flag.

### ISSUE THREAD

**Issue by Blokje5** [helm/helm#7224]
Output of `helm version`: 
```console
version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

Output of `kubectl version`:
```console
(base) base ❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-26T00:04:52Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.10-eks-c22454", GitCommit:"c22454b8cc52025eeff2d7f1d5549f6583f38ad0", GitTreeState:"clean", BuildDate:"2019-10-22T19:11:58Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
EKS

## Issue
When running Helm command of a new chart I get a no such file or directory error using the `-f` flag and passing a file. As you can see in the screenshot below, the file should be available for the install command.
![Cannot find values](https://user-images.githubusercontent.com/26072918/70808639-66921f00-1dc0-11ea-989a-7ac7c3b69508.png)

**Comment by marckhouzam** [comment]
You typed `values.yaml` but your file is named `values.yml` without the a.

**Comment by Blokje5** [comment]
My bad, completely missed that typo. I will close this issue. Thanks @marckhouzam.
