### ISSUE TITLE
Unintuitive error message when incorrectly specifying `--set` flag

### ISSUE THREAD

**Issue by Blokje5** [helm/helm#7225]
Output of `helm version`: 
```console
version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

Output of `kubectl version`:
```console
(base) base ❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-26T00:04:52Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.10-eks-c22454", GitCommit:"c22454b8cc52025eeff2d7f1d5549f6583f38ad0", GitTreeState:"clean", BuildDate:"2019-10-22T19:11:58Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
EKS

## Issue
After upgrading to Helm v3 I specified the `--set` flag still in the old manner, which lead to an error that did not point to the issue: `Error: must provide a name or specify --generate-name`. It would be nice if this could actually point to the invalid flag. See also the attached screenshot.
![Incorrect set flag specification](https://user-images.githubusercontent.com/26072918/70808937-16678c80-1dc1-11ea-8f9b-5be66002c64f.png)

**Comment by marckhouzam** [comment]
Your `--set` flag is actually correct 😁
The problem is that you need to specify a extra parameter for the name of the release.  Helm 2 used to generate one for you but helm 3 requires you to provide that parameter or to use the `--generate-name` flag.

Clearly the error message did not help you sufficiently. I wonder how the error message should be phrased to be more useful. Any suggestion @blokje5 ?

**Comment by waveywaves** [comment]
@marckhouzam The release name has already been provided here which is `metabase` and `stable/metabase` being the chart

**Comment by marckhouzam** [comment]
Thank you @waveywaves, you are right.  And apologies to @Blokje5 for misreading the command-line.

I can reproduce this too.  The missing `=` sign seems to be causing problems.

**Comment by Blokje5** [comment]
Yeah, indeed after fixing the `--set` syntax and using the new stringlist approach (e.g. `--set database.host=$HOST,database.password=$PW`) this command worked properly, but the error indeed does not indicate that this is the issue.

**Comment by marckhouzam** [comment]
The parameter validation seems to be done here https://github.com/helm/helm/blob/357d265de0e72f02c493701cdbee9ecc6eb0a016/pkg/action/install.go#L547

@Blokje5 do you want to take a stab at fixing it and providing a PR?

**Comment by Blokje5** [comment]
@marckhouzam I would love to give it a go. I'll pick it up.
