### ISSUE TITLE
Helm install with --verify flag without having the public key ring shows misleading error.

### ISSUE THREAD

**Issue by openmohan** [helm/helm#7226]
Installing a chart from helm hub (bitnami/mariadb) works fine.
 But when installilng with --verify flag (without having public keyring), the client fails with 
```Error: failed to download "bitnami/mariadb" (hint: running `helm repo update` may help)```.  

Shouldn't it should throw error like 
```Error: failed to load keyring: open /home/user/.gnupg/pubring.gpg: no such file or directory```

Output of `helm version`: `version.BuildInfo{Version:"v3.0+unreleased", GitCommit:"", GitTreeState:"", GoVersion:"go1.13.5"}`

Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform :  Minikube

**Comment by openmohan** [comment]
I will work on this bug. Thanks

**Comment by bacongobbler** [comment]
closing as stale.

**Comment by fholzer** [comment]
Also encountered this. Seems like whatever helm calls under the hood relies on the legacy GnuPG v1 key DB, which is no longer present on newer systems. You can export your GnuPG2 key DB to the old path as a workaround: `gpg --output ~/.gnupg/pubring.gpg --export` (This only exports public keys)

**Comment by pb4162** [comment]
I'm using the workaround currently but it would be ideal if helm could natively handle newer `.kbx` DBs, especially with helm 4 requiring cryptographic verification by default for helm plugins.
