### ISSUE TITLE
Proposal: a way to mark charts as Helm 3 incompatible

### ISSUE THREAD

**Issue by krancour** [helm/helm#7239]
I understand that, generally speaking, Helm 2 charts are meant to remain compatible with Helm 3 and that in cases where there are incompatibilities between existing charts and Helm 3, charts (at least those in helm/charts stable and incubator) are meant to remediate any incompatibilities, however...

@scottrigby and I have identified a chart (magic-namespace; of which I am the original author) that has exposed an edge case where a chart:

* Cannot become Helm 3 compatible wtihout undermining its usefulness to Helm 2 users
* Is _only_ useful for Helm 2 to begin with
    * Can therefore be sunset on the same schedule as Helm 2

I want to propose that there _should_ be some mechanism for authors of such charts to convey explicitly in their `Charts.yaml` that the chart is not and can not / will not ever be Helm 3 compatible. i.e. A way to say, "this is the end of the line for me."

**Comment by rimusz** [comment]
+1

**Comment by openmohan** [comment]
If helm verions is v.3.x.x and if `isVersion3Supported` key is set to `false`, we can stop processing the chart/release and return an appropriate error.

please let me know your thoughts @bacongobbler and maintainers?

**Comment by bacongobbler** [comment]
I have not seen any consistent demand from the community on a proposal. In general, Helm 2 charts are compatible with Helm 3. And I imagine this issue will go away once Helm 2 is no longer supported 2 months from now.

However, for those who wish to continue pursuing this idea and want to propose a solution, please feel free to submit a Helm Improvement Proposal (HIP). We are using that mechanism going forward for significant Helm features. The process is documented in HIP 1: https://github.com/helm/community/blob/master/hips/hip-0001.md

Thank you for your feedback.
