### ISSUE TITLE
Jobs with hook annotations of the same weight should run in parallel

### ISSUE THREAD

**Issue by strainovic** [helm/helm#7241]
We are using Jobs with hook annotations to run SQL migration scripts before our Pods start. It works fine except the fact that each of Jobs run only after previous complete successfuly. Is it possible to run Jobs in parallel? We have more then 50 microservices and we have to wait all 50 Jobs to complete before actual services can start.

Thanks!

**Comment by dastrobu** [comment]
This might break a few existing charts that rely on a certain order of hooks. Parallelism should be optional and controllable e.g. via an additional hook annotation. In general, I would welcome this feature. 

Relates to https://github.com/helm/helm/issues/7416

**Comment by Warxcell** [comment]
@dastrobu I agree, but isn't reasonable for hooks with same WEIGHT to run parallel ?

**Comment by dastrobu** [comment]
@Warxcell probably the strategy for parallel hook runs just needs a bit more of refinement. 

First, I think only hooks of the same kind should run in parallel. E.g. a serviceaccount required by a hook pod should always be created before the pod starts (see #7416). Still if all pods (or jobs) run in parallel we will still gain a huge improvement on install times. 

Second, there can be still cases where chart authors rely on the alphabetical sorting of hooks with same weight (e.g. two pods that should be executed in order). Given that weights should be preferred over relying on alphabetical sorting, I guess it would be acceptable if those charts break. 

So I would adjust this proposal to "hooks of same weight and same kind should run in parallel".
