### ISSUE TITLE
 --history-max option not working

### ISSUE THREAD

**Issue by smekkley** [helm/helm#7244]
With helm v3.0.1  `helm upgrade --history-max 1` option is not respected.
If you remove a resource from your chart, with debug option, you'll see it tries to delete the old resource even though the resource was deleted more than 1 release ago.

**Comment by marckhouzam** [comment]
Can you give more details on how to reproduce the problem you are seeing?

**Comment by smekkley** [comment]
I'll write a step later but you just need to create a template with 2 deployment, for example and apply it. Delete one deployment. And then add history max option to one with debug again and again. You'll see that helm is trying to delete the deployment that's been already deleted by helm previously.
#7243 might be related. 
I always add reset-values option as well.

**Comment by PavelSosin-320** [comment]
Freshly installed helm 3.0.1 for windows doesn't recognize init at all with any flag

**Comment by hickeyma** [comment]
@PavelSosin-320 Can you provide more details on what is not recognized?

**Comment by PavelSosin-320** [comment]
Actualy, I installed helm 3 and according some posts(?) it doesn't need **init** at all. So init is obsolete. Sorry, it is my fault ! But I didn't find any script which installs very basic things using Helm 3, like Grafana, ingresses, etc. So I am not the only person which is not informed yet. Developers of many basic Kubernetes components still work with Helm 2.
Maybe, somebody can update documentation for Docker desktop, Ingresses, etc.
I work with Docker Desktop which based on WSL 2.0 and would like to use Linux version of Helm - it looks very convinient and simple in handling.

**Comment by bacongobbler** [comment]
Thank you for your suggestion. With the [removal of tiller](https://helm.sh/docs/faq/#removal-of-tiller), `helm init` was no longer required and was removed. I couldn't find anywhere in the documentation that explicitly calls out that `helm init` is no longer required.

I'm confused what you mean by 

> But I didn't find any script which installs very basic things using Helm 3, like Grafana, ingresses, etc.

Is this something that is not covered by the [Quickstart Guide](https://helm.sh/docs/intro/quickstart/)?

Would you like to submit a pull request against the documentation with your learnings? It's always best to get someone unfamiliar with the code base to contribute documentation; they have the "first learner's advantage" that many of the core maintainers do not have :)

Source code for the FAQ can be found here: https://github.com/helm/helm-www/blob/master/content/docs/faq.md

We're getting slightly off-topic from the OP here so if you want to open a new ticket with your findings, that would be great as well. That way we can have a conversation without bothering @smekkley and others who are having troubles with the `--history-max` flag.

**Comment by PavelSosin-320** [comment]
I think that such incompatible changes as withrowal init has to be communicated with users before the new version release via regular feature lifecycle warning. Even when the new version is released helm has to emit meaningfull error message with link to corresponding release note. For those Cloud companies employees and partners who work with big Cloud companies with very tough minor  release cycle breaking development pipeline is very unpleasant especialy if they are supported by DevOps teams. I hope Helm developers don't intend to publish Quick start document for every release because DevOps has no time to read it. They prefer to run new Installation procedure version, bash script, PS script, IDE plugin, Helm design time Docker image for Cloud development environment  or Ansimble operator  to provide new Helm version for every developer weaponised and forget about old one.

**Comment by marckhouzam** [comment]
Am I reading this issue wrong or did we completely digress from the OP's issue? 😬

@PavelSosin-320, about the removal of init: you have to remember that moving to helm 3 is a major version change and should not be done transparently as one would do for a minor or patch release. At my place of work we planned a full migration strategy of our kube clusters with corresponding CICD changes.

**Comment by hickeyma** [comment]
@smekkley Any update on this issue? Did you fins steps to reproduce it?

**Comment by bacongobbler** [comment]
closing as stale.
