### ISSUE TITLE
Installing single CRD resource without other resources returns error

### ISSUE THREAD

**Issue by talam** [helm/helm#7247]
I have a chart with a single with a `crd.yaml` in the `crds` folder and an empty `templates` directory. Running a ` helm upgrade --install` produces the below error.
```
$ helm upgrade --install test-crd test-crd --wait
Release "test-crd" does not exist. Installing it now.
Error: no objects visited
```

Is this the expected behavior? I would have expected this to succeed. The CRD is installed, but the returned error is misleading.

Output of `helm version`:
```
$ helm version
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```
Output of `kubectl version`:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:34Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"clean", BuildDate:"2019-06-06T01:39:30Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.):  `AKS`

**Comment by bacongobbler** [comment]
Yes. This is the same result as #4670: if there are no templates to render (i.e. only chart hooks and CRDs are installed), a `helm install` has no objects to track, so it considers that as an error condition.

**Comment by talam** [comment]
Thanks, closing this issue out.
