### ISSUE TITLE
`helm repo update` does not create cached indexes in non-default cache location (when overridden by env or CLI) flag; more broadly `helmpath` package helpers don't account for any such overrides

### ISSUE THREAD

**Issue by donaldguy** [helm/helm#7248]
Output of `helm version`:
`version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"`}

(but also like:
`version.BuildInfo{Version:"v3.0", GitCommit:"0edb09e4faaed3c7ed5b1f843815f625fa3b7c06", GitTreeState:"dirty", GoVersion:"go1.13.1"}`)

---

**TL;DR** running `helm repo update --repository-config /some/dir/that/exists` writes downloaded indexes into (on mac) `~/Library/Caches/helm/repository` anyway - ditto with `HELM_REPOSITORY_CACHE` set in environment

---
0. I encountered this problem initially when trying to use a build of terraform-providers/terraform-provider-helm#378 in Terraform Cloud, but that's not exceedingly relevant, beyond how there's not a normal $HOME dir in action.
1. During a `helm install` I received an unexpected 
    ``` 
    failed to download "$repo/$chart" (hint: running `helm repo update` may help)
    ```
2. With HELM_DEBUG enabled I got rather:
    ```
    no cached repo found. (try 'helm repo update'): open /$VALUE_OF_HELM_REPOSITORY_CACHE/$repoName-index.yaml: no such file or directory
    ````
3. Manually copying these repo-index.yaml files into my repo-local cache fixed the problem.

4. I tried to write a helper to at least update these directly before comitting. It called `helm repo update` and it did not work.

5. I read source code (woo).

so. We/y'all have:

https://github.com/helm/helm/blob/0edb09e4faaed3c7ed5b1f843815f625fa3b7c06/cmd/helm/repo_update.go#L47-L57

which calls 

https://github.com/helm/helm/blob/0edb09e4faaed3c7ed5b1f843815f625fa3b7c06/cmd/helm/repo_update.go#L66-L75

into

https://github.com/helm/helm/blob/0edb09e4faaed3c7ed5b1f843815f625fa3b7c06/cmd/helm/repo_update.go#L79-L94

looks good. Except,

https://github.com/helm/helm/blob/0edb09e4faaed3c7ed5b1f843815f625fa3b7c06/cmd/helm/repo_update.go#L68

goes over to 

https://github.com/helm/helm/blob/0edb09e4faaed3c7ed5b1f843815f625fa3b7c06/pkg/repo/chartrepo.go#L60-L77

where, most notably for this issue

https://github.com/helm/helm/blob/0edb09e4faaed3c7ed5b1f843815f625fa3b7c06/pkg/repo/chartrepo.go#L75

falls into ~ the whole of https://github.com/helm/helm/blob/0edb09e4faaed3c7ed5b1f843815f625fa3b7c06/pkg/helmpath/home.go

which since #6272 only provides the defaults, 100% of the time.

In my immediate case you could bubble down the cache value into the update function and do a local override, but the correct behavior seems like for `helmpath` to account for the env var and cli settings

... and I was gonna pose a PR to that effect, but like ... without maybe digging into pre #6272 state – I'm not sure how exactly helmpath can or should reach over to the main package to suck that stuff in. Like... I would maybe just add a `RegisterOverrides` to `helmpath` and populate a package level struct?

but that is inelegant and I'm not sure I know the codebase well enough to understand the ramifactions.

Halp tho.

Also hi ex-coworkers :wave:

**Comment by donaldguy** [comment]
Heres a workaround after a fashion

`helm-repo-update.sh`:

```bash
#!/bin/bash

set -eu

src="$(unset HELM_REPOSITORY_CACHE && eval "$(helm env)" && echo $HELM_REPOSITORY_CACHE)"
LOCAL_UPDATE_OUTPUT_FILE="$(mktemp)"

helm repo update | tee $LOCAL_UPDATE_OUTPUT_FILE

echo "Copying updated indexes into repo"

for repo in $(grep Successfully "$LOCAL_UPDATE_OUTPUT_FILE"  | perl -ne 'm/the "([^"]+)" chart/; print "$1\n"'); do
    echo "${src}/${repo}-index.yaml -> ${HELM_REPOSITORY_CACHE}/${repo}-index.yaml"
    cp ${src}/${repo}-index.yaml ${HELM_REPOSITORY_CACHE}/
done
```

**Comment by marckhouzam** [comment]
Could this be a duplicate of #7141 or maybe very similar?

**Comment by donaldguy** [comment]
Yes.

I totally searched most relevant things on issues in search of an open
issue and somehow didn’t find it :-(

Arguably per my second sentence this issue is a superset of that.

But mostly yeah

**Comment by bacongobbler** [comment]
closing as a duplicate of #7141. Thanks for finding that @marckhouzam!

**Comment by marckhouzam** [comment]
> Arguably per my second sentence this issue is a superset of that.

I think @donaldguy might be right that this issue is a superset as it includes limitations with the handling of `--repository-config` while #7141 only mentions `--repository- cache`. Although I haven't confirmed the problems with `--repository-config` myself

**Comment by hickeyma** [comment]
@marckhouzam Should #7141 be closed then in favour of this issue?

**Comment by marckhouzam** [comment]
@hickeyma There's a PR associated with #7141 . But if that's not a problem, it should be fine to close it in favor of this one. I'll let you decide about the PR situation, I'm ok with closing.

**Comment by hickeyma** [comment]
@marckhouzam My bad, used wrong number. Lets start again! Does #7248 supersede #7166?

**Comment by marckhouzam** [comment]
@hickeyma  well #7166 is a PR so I'm not sure we can say #7248 which is an issue, supercedes it 😄.  I think until we have a PR for #7248, #7166 still improves the situation, so we could try to merge it.

**Comment by hickeyma** [comment]
@marckhouzam Sorry, I seem to have got tangled up in knots. All good here! :)

**Comment by bacongobbler** [comment]
closing as stale.
