### ISSUE TITLE
Helm3 cleanup tiller deploy doesnot work with Openshift Cluster

### ISSUE THREAD

**Issue by rkamisetti792** [helm/helm#7250]
Output of `helm version`: helm v3.0.0

Output of `kubectl version`: v1.16.3

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Openshift Container Platform Cluster in AWS

In Openshift DeploymentConfig name is tiller
By default helm execute the command background to delete the tiller deploy
kubectl delete -n <tiller namespace> deploy/tiller-deploy (not found in oc cluster)

Any workaround?

**Comment by hickeyma** [comment]
It would help to get more information to better understand the issue.

Can you provide some background on what you are trying to do? Are you trying to remove Tiller?
What namespace is Tiller deployed in?

Command to remove Tiller (service and deployment):
```
kubectl delete -n <tillerNamespace> deploy/tiller-deploy
kubectl delete -n <tillerNamespace> service/tiller-deploy
```

**Comment by bridgetkromhout** [comment]
Hi, @rkamisetti792 - As we have not heard back with more detail, we are closing this issue now. You said you used Helm 3 but also you mentioned tiller, so I want to ensure you know that Helm 2 (which had tiller) is ending support: https://helm.sh/blog/helm-v2-deprecation-timeline/ - please let us know if you need anything else. Thanks.
