### ISSUE TITLE
Error: create: failed to create: Request entity too large: limit is 3145728

### ISSUE THREAD

**Issue by Endofunctor** [helm/helm#7264]
I suddenly started experiencing the following error when using Helm 3.0.1 to install a new release on GCP:

```
Error: create: failed to create: Request entity too large: limit is 3145728
helm.go:76: [debug] Request entity too large: limit is 3145728
create: failed to create
helm.sh/helm/v3/pkg/storage/driver.(*Secrets).Create
	/private/tmp/helm-20191206-15945-o5deut/src/helm.sh/helm/pkg/storage/driver/secrets.go:160
helm.sh/helm/v3/pkg/storage.(*Storage).Create
	/private/tmp/helm-20191206-15945-o5deut/src/helm.sh/helm/pkg/storage/storage.go:66
helm.sh/helm/v3/pkg/action.(*Install).Run
	/private/tmp/helm-20191206-15945-o5deut/src/helm.sh/helm/pkg/action/install.go:261
main.runInstall
	/private/tmp/helm-20191206-15945-o5deut/src/helm.sh/helm/cmd/helm/install.go:209
main.newInstallCmd.func1
	/private/tmp/helm-20191206-15945-o5deut/src/helm.sh/helm/cmd/helm/install.go:115
github.com/spf13/cobra.(*Command).execute
	/private/tmp/helm-20191206-15945-o5deut/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
	/private/tmp/helm-20191206-15945-o5deut/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
	/private/tmp/helm-20191206-15945-o5deut/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
	/private/tmp/helm-20191206-15945-o5deut/src/helm.sh/helm/cmd/helm/helm.go:75
runtime.main
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/proc.go:203
runtime.goexit
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/asm_amd64.s:1357
``` 

From reading the code around the exception it looks like helm is trying to create a secret that is greater than 3MB to store the release information. 

There were no changes to any of the values or templates that Helm uses. I can checkout earlier commits and the error still persists. I also wiped my .helm and recreated the cluster but neither action fixes the issue. The helm install for the same commit works on a different machine for the same cluster.

Before I wake up and dig through the Helm codebase a little more tomorrow, is there anything that would be accumulating information somewhere and incorporating it into the helm release secret?

---
**Update**

Minimal example to reproduce:
```
helm create test
cd test
dd if=/dev/urandom bs=100000000 count=5 of=largefile
helm install test .

Error: create: failed to create: Request entity too large: limit is 3145728
```

Helm info (OS X):
```
version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

**Comment by bacongobbler** [comment]
Check the chart for any stray files that may have crept in there. Usually this can occur because there may be some files that are being included as part of the chart.

See also #3512.

**Comment by Endofunctor** [comment]
Thanks! I had a large targz file I temporarily copied into the chart directory and this in a configmap template too:
```
  {{- $files := .Files }}
  {{- range tuple "server.key" "server.crt" }}
  {{ . }}: |-
    {{ $files.Get . | nindent 4 | trim }}
  {{- end }}
{{ end }}
```

Removing the targz file fixes the issue but it's not actually being included in anything so it doesn't seem like this error should happen. Also removing the above template does not fix the issue.

Here's the minimal example needed to reproduce:
```
helm create test
cd test
dd if=/dev/urandom bs=100000000 count=5 of=largefile
helm install test .

Error: create: failed to create: Request entity too large: limit is 3145728
```

**Comment by ben-schumacher** [comment]
Having same problem.  Any update here?  My intention was to include a utility file/tool in the chart that is a little over 3MB in size.

**Comment by andylholloway** [comment]
I just had the same issue. My entire chart with dependencies was only slightly over 2Mb. 
To fix the issue I deleted all tgz files and ran:
`helm dependency update`
`helm package [pkg name] .`

After doing that `helm install` ran without error.

**Comment by jasonmimick** [comment]
Can report same issue - package archive ~ 2.2MB.
And always 
`helm template foo foo-0.0.1.tar.gz | kubectl apply -f -`
works

**Comment by kjozsa** [comment]
What worked for me is to put any unrelated stuff in the helm chart's directory into `.helmignore`. I hope it helps someone here..

**Comment by bacongobbler** [comment]
Closing as answered. Thanks everyone.

**Comment by drekle** [comment]
If anyone stumbles here and makes the same mistake I did I was able to resolve after removing some packaged charts that were placed in the chart directory:

```
$ helm install v1alpha1 .
Error: create: failed to create: Request entity too large: limit is 3145728
```
```
rm -f *.tgz
```
```
$ helm install v1alpha1 .
NAME: v1alpha1
LAST DEPLOYED: Fri Jun 26 15:11:07 2020
NAMESPACE: ...
STATUS: deployed
REVISION: 1
```

**Comment by sohel2020** [comment]
delete .git helps

**Comment by Nazi12345** [comment]
Where

**Comment by ldemailly** [comment]
Stepped on this as well trying to avoiding needing an extra chart/ directory... basically helm install/helm package (seems to) pick up _all_ the files in the directory of Chart.yaml and not just templates/ values.yaml etc

**Comment by aryazen** [comment]
![Request entity too large: limit is 3145728](https://github.com/helm/helm/assets/69396823/83f3f24b-ea27-4045-bb5f-4c2ebc0172b4)

**Comment by atrakic** [comment]
> Stepped on this as well trying to avoiding needing an extra chart/ directory... basically helm install/helm package (seems to) pick up _all_ the files in the directory of Chart.yaml and not just templates/ values.yaml etc

This was was exactly what experianced in local chart without .helmignore. Thx
