### ISSUE TITLE
How to use value as other value's key?

### ISSUE THREAD

**Issue by Moshem123** [helm/helm#7267]
I want to know if it's possible to use a value like this?
`{{ .Values[.Release.Namespace].replicas }}`
When my `values.yaml` is like:
```
production:
  replicas: 2
staging:
  replicas: 1
```
And I install like this:
```
helm install --namespace production my-release .
```
If not, is there any other way to achieve this?

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:34Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.8", GitCommit:"a89f8c11a5f4f132503edbc4918c98518fd504e3", GitTreeState:"clean", BuildDate:"2019-04-23T04:41:47Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS

**Comment by bridgetkromhout** [comment]
Hi, @Moshem123 - does https://helm.sh/docs/intro/using_helm/#customizing-the-chart-before-installing help? If you are not yet on Helm v3, please be sure to migrate: https://helm.sh/blog/helm-v2-deprecation-timeline/

As this issue has been inactive for some time I'll resolve it, but please let us know if you have additional questions.

**Comment by Moshem123** [comment]
Thanks @bridgetkromhout , I solved it using the `index`:
```
{{ index (index .Values .Release.Namespace) "replicas" }}
```

**Comment by fditolla** [comment]
> Thanks @bridgetkromhout , I solved it using the `index`:
> 
> ```
> {{ index (index .Values .Release.Namespace) "replicas" }}
> ```

Thanks, for me it was not clear since the documentation of that function refers only to list.
