### ISSUE TITLE
Multiple revisions in `DEPLOYED` state.

### ISSUE THREAD

**Issue by avarabyeu** [helm/helm#7274]
Multiple revisions in `DEPLOYED` state.
The issue appeared after upgrade to Helm 3. Tried complete re-installation of the chart with deleting all helm-related secrets, but after some number of deploys, the issues appears again

![image](https://user-images.githubusercontent.com/1565439/71205625-ce120800-22b3-11ea-9de3-23fad6ba48db.png)

Output of `helm version`:
`version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}`
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T11:52:32Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-gke.12", GitCommit:"188432a69210ca32cafded81b4dd1c063720cac0", GitTreeState:"clean", BuildDate:"2019-11-07T19:27:01Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
Cloud Provider/Platform (AKS, GKE, Minikube etc.):  GKE

**Comment by bacongobbler** [comment]
Hi @avarabyeu. Can you demonstrate how one can reproduce this locally?

**Comment by jason-liew** [comment]
```
kubectl get secret -l owner=helm,status=deployed,name=test
```
In my case, there are  4 revisions in `deployed` state.

**Comment by avarabyeu** [comment]
@bacongobbler unfortunately, i do not have exact steps to reproduce it locally, but it definitely happens on concurrent upgrade with `--wait` flag enabled

**Comment by svcua** [comment]
I have caught the same bug.
@avarabyeu `--wait` does not affect
@bacongobbler To reproduce try run `helm upgrade` on the different environments(in my case it is gitlab-ci runner's pods) in one time to upgrade the same release

**Comment by cristiklein** [comment]
I believe the users in #6031 stumbled across the same root cause (albeit in Helm 2). In certain cases, multiple Releases may show up as DEPLOYED, which may cause various problems.

**Comment by cristiklein** [comment]
I managed to reproduce this bug with Helm (v3.0.2) as follows:

```
helm create foo
cd foo
helm upgrade foo . --install --wait
sed -i -e 's/^replicaCount: .*/replicaCount: 3/' values.yaml
helm upgrade foo . --install --wait
```

While the last command executes, in a different terminal, wait for `pending-upgrade` status, then type:

```
helm upgrade foo . --install --wait
```

The two `helm upgrade` commands must run in parallel. `helm history foo` will look as follows:

```
$ helm history foo
REVISION	UPDATED                 	STATUS         	CHART    	APP VERSION	DESCRIPTION      
1       	Wed Jan  1 23:28:25 2020	deployed       	foo-0.1.0	1.16.0     	Install complete 
2       	Wed Jan  1 23:30:23 2020	pending-upgrade	foo-0.1.0	1.16.0     	Preparing upgrade
$ helm history foo
REVISION	UPDATED                 	STATUS         	CHART    	APP VERSION	DESCRIPTION      
1       	Wed Jan  1 23:28:25 2020	deployed       	foo-0.1.0	1.16.0     	Install complete 
2       	Wed Jan  1 23:30:23 2020	pending-upgrade	foo-0.1.0	1.16.0     	Preparing upgrade
3       	Wed Jan  1 23:30:28 2020	pending-upgrade	foo-0.1.0	1.16.0     	Preparing upgrade
$ helm history foo
REVISION	UPDATED                 	STATUS    	CHART    	APP VERSION	DESCRIPTION     
1       	Wed Jan  1 23:28:25 2020	superseded	foo-0.1.0	1.16.0     	Install complete
2       	Wed Jan  1 23:30:23 2020	deployed  	foo-0.1.0	1.16.0     	Upgrade complete
3       	Wed Jan  1 23:30:28 2020	deployed  	foo-0.1.0	1.16.0     	Upgrade complete
```
