### ISSUE TITLE
Can't install prometheus-nats-exporter

### ISSUE THREAD

**Issue by emailtovamos** [helm/helm#7278]
I am trying to install `prometheus-nats-exporter` in my Kubernetes cluster using the command given in this [link](https://github.com/helm/charts/tree/master/stable/prometheus-nats-exporter) so that I can follow the steps given [here](https://github.com/nats-io/prometheus-nats-exporter/tree/master/walkthrough) to see metrics of my `nats-server` in `grafana`.

But I am getting this error when I run the command:
```
helm install incubator/prometheus-nats-exporter --generate-name
Error: failed to download "incubator/prometheus-nats-exporter" (hint: running `helm repo update` may help)
```

The given hint doesn't help. Please help. 

Output of `helm version`:
version.BuildInfo{Version:"**v3.0.1**", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}

Output of `kubectl version`: 
Client Version: v1.16.1
Server Version: **v1.12.10-gke.17**

Cloud Provider/Platform (AKS, GKE, Minikube etc.): **GKE**

**Comment by bacongobbler** [comment]
hi @emailtovamos. What is the output of `helm repo list`? Do you have the incubator repository added to the list?

**Comment by bacongobbler** [comment]
closing as stale.
