### ISSUE TITLE
OCI registry login failed, tries to access certs from docker

### ISSUE THREAD

**Issue by dzoeteman** [helm/helm#7280]
Output of `helm version`:
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS

Trying out the experimental OCI feature, I run into the following error when trying to login to ECR:

` helm registry login -u AWS -p [password] https://[account id].dkr.ecr.eu-central-1.amazonaws.com`

```
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error: open /etc/docker/certs.d/[account id].dkr.ecr.eu-central-1.amazonaws.com: permission denied
```

It seems like the `certs.d` directory doesn't actually exist.

I used the args from the `aws ecr get-login --region eu-central-1 --no-include-email` command that's normally used to authenticate docker.

**Comment by jdolitsky** [comment]
Just as you cannot use `docker login` directly for ECR, the same would be true for `helm registry login`

What you can likely do is run the `aws ecr get-login` command and just replace "docker" with "helm"

That being said, ECR does not yet support helm charts last I checked: https://github.com/aws/containers-roadmap/issues/308

**Comment by rpnguyen** [comment]
ECR support for helm charts is being worked on right now. Once that lands, you may also be interested in the new [`get-login-password`](https://docs.aws.amazon.com/cli/latest/reference/ecr/get-login-password.html) command which pairs with the helm cli like so:
```
aws ecr get-login-password --region eu-central-1 | helm registry login --username AWS --password-stdin <account id>.dkr.ecr.eu-central-1.amazonaws.com
```

**Comment by zurvan2** [comment]
I'm seeing this with harbor installed on the same machine. This could be an issue for multi-user machines where someone is trying to use helm to access a registry running on the same machine, but without root access. Helm should not need to access the server's private key.

**Comment by eduardocorral** [comment]
Still an issue in 3.9.3, unrelated to AWS. E.g. attempting to login to Oracle's OCIR
```
helm.go:84: [debug] open /etc/docker/certs.d/phx.ocir.io: permission denied
```
with
```
helm registry login phx.ocir.io --registry-config /path/to/config.json --username [*******] --password-stdin
```

**Comment by bobh66** [comment]
I found that using the `--insecure` flag on `helm registry login` fixed the problem with trying to access /etc/docker/certs.d
