### ISSUE TITLE
Unable to install prometheus-operator

### ISSUE THREAD

**Issue by sharkwsk** [helm/helm#7282]
I want to install - prometheus, alertmanager & grafana

**Output of `helm version`:**
version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}

**Output of `kubectl version`:**
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

**Cloud Provider/Platform (AKS, GKE, Minikube etc.):** 
Minikube

**Comment by bacongobbler** [comment]
hi @sharkwsk. Can you please provide more information about the issues you are seeing that is preventing you from installing those charts?

**Comment by sharkwsk** [comment]
Sorry I am a newbie on this...
Below are the repos
helm repo list
NAME    URL
charts  https://kubernetes-charts.storage.googleapis.com/
coreos  https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/

When I attempt install
helm install stable/prometheus-operator --namespace monitoring prometheus-operator
Error: failed to download "prometheus-operator" (hint: running `helm repo update` may help)

I am not sure if I have all necessary repos

**Comment by bacongobbler** [comment]
It looks like you have the stable chart repository named as "charts". The quickstart guide refers to the chart repository as the "stable" chart repository, and as such uses `helm repo add stable https://kubernetes-charts.storage.googleapis.com/` instead of `helm repo add charts https://kubernetes-charts.storage.googleapis.com/`.

You can install the prometheus-operator chart with `helm install charts/prometheus-operator`.

Hope this helps!

**Comment by sharkwsk** [comment]
Thanks for the help, Just tried, still the same

C:\WINDOWS\system32>helm repo list
NAME    URL
charts  https://kubernetes-charts.storage.googleapis.com/
coreos  https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/

C:\WINDOWS\system32>helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "coreos" chart repository
...Successfully got an update from the "charts" chart repository
Update Complete. ⎈ Happy Helming!⎈

C:\WINDOWS\system32>
C:\WINDOWS\system32>
C:\WINDOWS\system32>helm install charts/prometheus-operator --namespace monitoring prometheus-operator
Error: failed to download "prometheus-operator" (hint: running `helm repo update` may help)

**Comment by sharkwsk** [comment]
Looks like the local repository index file has localhost URLs

install.go:148: [debug] Original chart version: ""
Error: Get **http://127.0.0.1:8879/charts/prometheus-operator-0.0.6.tgz**: dial tcp 127.0.0.1:8879: connectex: No connection could be made because the target machine actively refused it.
helm.go:76: [debug] Get http://127.0.0.1:8879/charts/prometheus-operator-0.0.6.tgz: dial tcp 127.0.0.1:8879: connectex: No connection could be made because the target machine actively refused it.

**Comment by sharkwsk** [comment]
Finally made it to work, had to change the repo to this and the arguments in this order

helm repo add stable https://kubernetes-charts.storage.googleapis.com
helm repo update

helm install prometheus-operator --namespace monitoring stable/prometheus-operator --debug

**Comment by bacongobbler** [comment]
yep, just looks like you had the arguments in the wrong order. For reference, `helm help install` mentions the argument list as

```
helm install NAME CHART [options]
```
