### ISSUE TITLE
Helm 3.0.2 upgrade error

### ISSUE THREAD

**Issue by JohanJermey** [helm/helm#7289]
Output of `helm version`:

3.0.2

Output of `kubectl version`:

1.15.7

Cloud Provider/Platform (AKS, GKE, Minikube etc.):
aws 

I was able to deploy chart of Prometheus operator successfully however when trying to upgrade I got the following issue? 

`Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: kind: PodSecurityPolicy, namespace: , name: po-kube-state-metrics`

this error happen on other entities also,   any idea how can I avoid such error , any workaround ?

**Comment by thomastaylor312** [comment]
@JohanJermey was there a PSP resource that already existed before you tried to upgrade your chart? Want to rule that out before anything else.

**Comment by jason-liew** [comment]
[#6850 comment](https://github.com/helm/helm/issues/6850#issuecomment-566032294) may be helpful

**Comment by alexandrsemak** [comment]
Same issue when try update already existing resources with new apiVesrion

**Comment by alexandrsemak** [comment]
Helm v3 can't also recreate resources if you change immutable field with `--force` flug as for helm v2 when can't patch resources helm v2 recreate resources if you use `--force` flug

**Comment by bacongobbler** [comment]
closing as stale.
