### ISSUE TITLE
does helm handle RBAC objects by kubectl auth reconcile?

### ISSUE THREAD

**Issue by Naitreey** [helm/helm#7294]
This is just a question regarding Helm's handling of RBAC object manifests.

As pointed out by [kubernetes RBAC doc](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#controller-roles) and `kubectl auth reconcile -h`, `kubectl auth reconcile -f` is a better way to create RBAC objects such as Role, RoleBinding, etc.

So I'd like to know how helm handles RBAC objects? Does it use something equivalent to `kubectl apply -f` or better `kubectl auth reconcile -f`?

Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): bare metal

**Comment by TBBle** [comment]
Per the source it appears to do creation with the [equivalent of `kubectl create`](https://github.com/helm/helm/blob/master/pkg/kube/client.go#L314), and updates with the [equivalent of `kubectl patch` unless specifically told to `kubectl replace`](https://github.com/helm/helm/blob/master/pkg/kube/client.go#L400).

**Comment by bacongobbler** [comment]
@TBBle's assumption is correct. We handle all objects the same.

Is there a difference in the way `kubectl auth reconcile` works compared to `kubectl patch`? Let us know what you find out @Naitreey. Thanks.

**Comment by FabioAntunes** [comment]
@bacongobbler according to the official documentation the reconcile has a couple of flags that make handling changes to the RBAC easier

> Reconciles rules for RBAC Role, RoleBinding, ClusterRole, and ClusterRole binding objects.
> 
> Missing objects are created, and the containing namespace is created for namespaced objects, if required.
> 
> Existing roles are updated to include the permissions in the input objects, and remove extra permissions if --remove-extra-permissions is specified.
> 
> Existing bindings are updated to include the subjects in the input objects, and remove extra subjects if --remove-extra-subjects is specified.
> 
> This is preferred to 'apply' for RBAC resources so that semantically-aware merging of rules and subjects is done.
