### ISSUE TITLE
Feature request: Warn users for known bugs/regressions 

### ISSUE THREAD

**Issue by oguzyildiz1991** [helm/helm#7300]
Hi, I thought of this after spending many hours because of this:
https://github.com/helm/helm/issues/6708 (I'm new at helm, so I just assumed I did something wrong, instead of looking for known helm issues)

I thought, it would be nice if helm had some kind of scripts that warns people that have the problematic versions for this kind of stuff when there's a case that will reproduce the bug. It could fetch a Javascript code daily from helm for the used version. So that when you discover a bug, you could warn people on their terminal, instead of so many people wasting hours trying to debug and then finally realizing it's a helm issue.

For example, when you discover #6708 , you would update the script for 2.15, and when people run helm on their computer, helm would fetch the script belonged to its version, and warn the people that convert a json.Number to int. Maybe it sounds like a farfetched idea, but imagine the hundreds/thousands of combined hours you save! :)

**Comment by bacongobbler** [comment]
how do you propose we support this from a technical standpoint? Are you actively looking into this, or just interested in the thought experiment? Are there prior projects where this has been proven to work?

**Comment by oguzyildiz1991** [comment]
I was just thinking about it, I thought you folks would probably come up with a good way to achieve this. I'm not familiar with this product that much 🤷‍♂

**Comment by bridgetkromhout** [comment]
Hi, @oguzyildiz1991 - Thank you for your idea to improve Helm. If you'd like, you can submit a Helm Improvement Proposal so as to work in the community to make your idea a reality: https://github.com/helm/community/blob/master/hips/hip-0001.md - meanwhile, I will close this issue. Thanks!
