### ISSUE TITLE
Feature request: `helm list --updated +7d`

### ISSUE THREAD

**Issue by unacceptable** [helm/helm#7301]
It would be nice if we could sort updated charts by date of creation or date updated.

Some examples would be:

```
helm list --updated +7d # list charts updated over 7 days ago
```

```
helm list --installed -24h # list charts updated in the last 24 hours.
```

I can provide use cases if desired.

**Comment by bridgetkromhout** [comment]
Hi, @unacceptable - I'm closing this issue because we now have a recommended path forward for proposals: if you'd like to formally propose this idea, please file a [Helm Improvement Proposal](https://github.com/helm/community/blob/master/hips/hip-0001.md) to discuss it with the community. Thanks!
