### ISSUE TITLE
Feature Request : Allow scripts to generate YAML instead of limiting to templates.

### ISSUE THREAD

**Issue by chainhead** [helm/helm#7303]
# Current installation mechanism
The installation of a chart follows these steps:

1. Use values and templates to generate YAML specific for that installation.
2. Pass the generated YAML to `kubectl`.

To generate the YAML, Go templates are used. Personally, I think, a package management tool, such as Helm, should focus on the management of installation/uninstallation, dependency management, package repository management, hooks to billing systems for proprietary packages, etc. The mechanism of generating the YAML should be kept as 'wide' as possible. One option of generating the YAML would be to use a high level language such as Python, etc. Indeed, one may use [Kubernetes clients](https://github.com/kubernetes-client) in written in different languages to generate the YAML!

# Proposed installation mechanism
I propose a new directory structure for packaging and a new installation flow as described below.

## Directory structure
```bash
awesome/                
  Chart.yaml            # A YAML file containing information about the chart
  LICENSE               # OPTIONAL: A plain text file containing the license for the chart
  README.md             # OPTIONAL: A human-readable README file
  values.yaml         # The default configuration values for this chart
  values.schema.json  # OPTIONAL: A JSON Schema for imposing a structure on the values.yaml file
  charts/               # A directory containing any charts upon which this chart depends.
  scripts/              # A directory containing scripts that will generate YAML for installation.
    shell/              #   A directory of shell scripts.
      ${OS}/            #     A directory corresponding to the platform where helm will be run.
        install.sh      #       The entry-point to installation.
        ...             #       Other supporting files for install.sh 
    python/             #   A directory of Python scripts.
      ${OS}/            #     A directory corresponding to the platform where helm will be run.
        install.py      #       The entry-point to installation.
        ...             #       Other supporting files for install.py
    go/                 #   A directory of Go scripts.
      ${OS}/            #     A directory corresponding to the platform where helm will be run.
        install.go      #       The entry-point to installation.
        ...             #       Other suporting files for install.go
  generated/            # A directory containing the generated YAML files. It should be empty when packaging.
```

### Notes on directory structure

1. The `values.yaml` will be read by an install script - see 5 below.
2. The installation script will live inside a directory corresponding to the language of the script in the `scripts` directory.
3. The languages could be shell (e.g. `bash`), Python, Go or any other language that can be supported.
4. Only one language directory should be present in `scripts` directory. 
5. Inside the language directory, there should be a install script (e.g. `install.sh` in `bash`, `install.py` in `python`, etc.)
6. Inside the language directory, there may be additional folders for different OS, if any OS specific actions exist.
7. The install script will write the generated YAML in the `generated` directory.

## Installation
The command to install `helm install ...` would not change. However, the flow will change as follows.

1. Launch `scripts/${language}/${install_script}`. For example, if the installation script language is shell script, then `scripts/shell/install.sh` would be launched, etc.
2. The launched script will write YAML, ready for installation, to the `generated` directory. Those YAML are passed on to `helm` for installation.

Keen to hear feedback!

**Comment by bacongobbler** [comment]
If I'm understanding correctly, this basically sidesteps all of Helm's template logic in favour of shell scripts. This sounds like a completely different model than what users have been asking for: new alternative template engines, or new ways to tie pre-render and post-render steps into the rendering process.

How do we protect against remote shell execution? If a user fetches the chart from a remote repository, they're effectively granting the chart author remote shell execution access. In the current model, Helm is intentionally sandboxed to prevent cases where a malicious chart author would be granted shell access.

Have you looked at alternative proposals such as https://github.com/helm/helm/pull/7259 yet?

**Comment by chainhead** [comment]
> If I'm understanding correctly, this basically sidesteps all of Helm's template logic in favour of shell scripts. 
'sidesteps'....I think, I will use the word 'adds on'. :) 

Shell scripts, high level languages are options. I could have an API end-point that takes in a payload and returns a YAML. The option of API end-point can also handle payment related requirements too.

> How do we protect against remote shell execution?
Would this be considered remote shell execution too? `curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash`

> Have you looked at alternative proposals such as #7259 yet?
Browsing now.

**Comment by chainhead** [comment]
I read through the proposal #7260 (referred to in #7259).  

That proposal refers to a Helm template as an input.

> Helm will then render the charts using the standard Go template language and the
specified user values. Once this is done, but before parsing the manifests into
Kubernetes objects, helm will execute the binary and pass the charts on STDIN.
It will expect a 0 exit code with valid Kubernetes manifests on STDOUT. 

My request is about to generating YAML through options _other_ than templates e.g. shell scripts, high level languages, API end-points, etc.

**Comment by chainhead** [comment]
Well ?

**Comment by hickeyma** [comment]
@thomastaylor312 You might have some input on this?

**Comment by thomastaylor312** [comment]
@chainhead So I think #7260 would solve this use case if I am understanding correctly. Using post render, you could actually have 0 go templating in your chart and then add/generate additional YAML in your post-render steps to your heart's desire. However, I don't know if you can have a completely empty manifest and then generate it completely out of band. 

The other option here is this sounds like an advanced use case that may be a good candidate to use the Go SDK for. You could generate your YAML by calling an API, pull back that buffer and then use it to set the `Manifest` in the release. Then you could get the benefits of having Helm manage your releases, but generate the YAML out of band

**Comment by chainhead** [comment]
> Then you could get the benefits of having Helm manage your releases, but **generate the YAML out of band**.
That is the use case I am interested in. In other words, I do not want to start with templates _at all_. 

It is also mentioned in the preamble of my proposal.

> To generate the YAML, Go templates are used. Personally, I think, a package management tool, such as Helm, should focus on the management of installation/uninstallation, dependency management, package repository management, hooks to billing systems for proprietary packages, etc. **The mechanism of generating the YAML should be kept as 'wide' as possible.** One option of generating the YAML would be to use a high level language such as Python, etc. Indeed, one may use Kubernetes clients in written in different languages to generate the YAML!

**Comment by chainhead** [comment]
Thoughts?

**Comment by thomastaylor312** [comment]
I would be interested to see how this could be implemented without breaking how Helm works. Part of the whole premise of Helm is that there is a package to be installed. Starting with nothing and having it being able to build from something completely freeform and without some sort of agreed upon format feels like a tall order. I know the agreed format you are arguing for is "YAML," but that would invalidate a whole ecosystem of prebuilt packages and be doing it without some sort of a spec/common API, which in this case is the go templated Chart package

It is definitely not impossible though, but probably something outside of the scope of things the maintainers would want to maintain. Like I mentioned before, this kind of workflow could be built with the Go SDK and published as a plugin, which we be more than willing to point people to

**Comment by chainhead** [comment]
> be doing it without some sort of a spec/common API, which in this case is the go templated Chart package

My proposal is about generating YAML corresponding to k8s objects directly; without going via templates. Then, the generated YAML is handed over to Helm for actual deployment.

Also, it is not my intention to make my proposal an either-or kind of proposal. That is, the current way of using templates should remain as is.

**Comment by thomastaylor312** [comment]
Makes sense. I think the best path forward for something like this is to implement it using the Go SDK (particularly `pkg/action`) and then writing the logic that loads your "templates" from scripts and sets them as a release manifest. It would allow you to reuse everything from Helm while still passing things in from a script as you desire

**Comment by squillace** [comment]
From my perspective, this reworks what Helm **is**, opening holes for new users to do things the ramifications of which they have no idea. That you can do this using the Go SDK is the perfect solution, I would think -- by definition, it will do a custom thing that you control for you and your environment. That's a great way to do this.

**Comment by thomastaylor312** [comment]
@chainhead if you are ok with the path forward, I think we are going to close the issue. If you do open source what you create, please drop a link here for anyone else who may come across this and be interested!
