### ISSUE TITLE
bash completion:  tail: cannot open ‘+2’ for reading: No such file or directory

### ISSUE THREAD

**Issue by finkr** [helm/helm#7304]
When using bash completion feature, I get the error:

    tail: cannot open ‘+2’ for reading: No such file or directory

The bash completion ( https://github.com/helm/helm/pull/6730 ) has an issue because it uses "tail +2" which isn't supported by coreutils-8.22-24.el7 (RHEL/CentOS) implementation of the command tail. The tail [specification](https://pubs.opengroup.org/onlinepubs/009695399/utilities/tail.html) requires using using `-n` prefix, so use `tail -n +2`

Two lines should be fixed in [cmd/helm/root.go](https://github.com/helm/helm/blob/v3.0.2/cmd/helm/root.go#L72):

    eval $(__helm_binary_name) repo list 2>/dev/null | \tail +2 | \cut -f1
    ..
    if out=$(eval $(__helm_binary_name) plugin list 2>/dev/null | tail +2 | cut -f1); then

As a workaround, one can load bash completion this way to _patch_ the completion code:

     . <(helm completion bash| sed -e 's/tail +2/tail -n +2/g')

(ping @marckhouzam )

**Comment by marckhouzam** [comment]
I was afraid some shell differences would start showing up to cause trouble.

@finkr would you be interested in posting a PR?

**Comment by finkr** [comment]
Yes, i will

**Comment by marckhouzam** [comment]
@finkr To be transparent: I'm working on a proposal that will completely remove the code affected.  However your PR would still be useful for the bug releases leading up to helm 3.1 and, of course, in the case my proposal is not accepted.

**Comment by marckhouzam** [comment]
Thanks @finkr for reporting and fixing this bug!

**Comment by marckhouzam** [comment]
I've created a PR to the https://github.com/helm/acceptance-testing repo to make sure completion continues to work as expected on centos: https://github.com/helm/acceptance-testing/pull/67
