### ISSUE TITLE
All helm installations create pods that are pending and never get ready

### ISSUE THREAD

**Issue by Sammy2005** [helm/helm#7306]
Output of `helm version`: 
`version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}`

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Digital ocean.

I have tried installing jenkins on my vm with helm but everytime the pod never gets ready. Am not able to describe the pod as well though the installation says that it was successfull

I also tried installing nginx-controller and had the same issue 

on running `kubectl get all -n jenkins`
```
NAME                           READY   STATUS    RESTARTS   AGE
pod/jenkins-84c4dfff9d-drrnp   0/1     Pending   0          17m

NAME                    TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
service/jenkins         NodePort    10.96.197.66   <none>        8080:30200/TCP   17m
service/jenkins-agent   ClusterIP   10.96.95.79    <none>        50000/TCP        17m

NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/jenkins   0/1     1            0           17m

NAME                                 DESIRED   CURRENT   READY   AGE
replicaset.apps/jenkins-84c4dfff9d   1         1         0       17m
```

**Comment by bacongobbler** [comment]
You can inspect your pod’s status with `kubectl describe pod jenkins-84c4dfff9d-drrnp -n jenkins`. Does the pod status show why it’s in a pending state?

Helm does not directly manage the state of the pod - it just supplies patch sets to Kubernetes and leaves the reconciliation to Kubernetes.

**Comment by Sammy2005** [comment]
The command shows nothing with an error that the pod doesn't exist

**Comment by Sammy2005** [comment]
I have installed helm 2 as a quick fix only to land to this problem [#6935](https://github.com/helm/helm/issues/6935)

**Comment by bacongobbler** [comment]
If the pod no longer exists, it's likely flapping. The Deployment resource manages and re-creates new pod to try and bring the workload into a working state.

Check the status of the deployment managing those pods using `kubectl -n jenkins describe deployment jenkins`.

**Comment by Sammy2005** [comment]
I had tried that as well it also says that the pod does not exists

**Comment by Sammy2005** [comment]
This is the error I get 
```
root@master-node:~# kubectl describe jenkins-78bbc8776-sgd29 -n jenkins
error: the server doesn't have a resource type "jenkins-78bbc8776-sgd29"
```

**Comment by Sammy2005** [comment]
I solved the issue by following this guidline https://github.com/kubernetes/kubernetes/issues/39557#issuecomment-271944481
turns out it was a network issue with flannel
