### ISSUE TITLE
Helm Wrong error on bad permission

### ISSUE THREAD

**Issue by assafridman** [helm/helm#7311]
**helm version:** v2.12.3

**kubectl version:** Client: v1.12.2 , Server: v1.12.8

**Cloud Provider/Platform:** AWS / KOPS

**Issue**: Wrong error message when bad permissions on chart files

while running : 

> helm install -f myValuesFile.yaml chartname mycopmany/chartname

i got an error: 

> Error: failed to download "mycopmany/chartname" (hint: running `helm repo update` may help)

Running the same command with debug gave the following insight:

> Error: open /home/user/.helm/cache/archive/chartname.tgz: permission denied

this is because the file was owned by the CI user .

Expected behaviour:
Error: failed to download "mycopmany/chartname" (hint: running `helm repo update` may help) Permissions denied writing to XXX" or something similar .

**Comment by bacongobbler** [comment]
marking as a feature enhancement to improve the error message in this particular case.

**Comment by bridgetkromhout** [comment]
Hi, @assafridman and others who are interested, we now have a path forward for proposals: if you're reading this and thinking "but this should happen!", please file a [Helm Improvement Proposal](https://github.com/helm/community/blob/master/hips/hip-0001.md) to discuss it with the community (or send a pull request if you'd like to implement it). Meanwhile, I'm closing this issue as inactive.
