### ISSUE TITLE
Backport three-way merge patch into helm 2?

### ISSUE THREAD

**Issue by sukhong** [helm/helm#7315]
I found out that a fix for using three-way merge patch strategy (https://github.com/helm/helm/pull/6124) was only included for helm 3.

Can we backport this fix into helm 2 as well for those who cannot upgrade to helm 3?

**Comment by bacongobbler** [comment]
We are no longer accepting new features for Helm 2. The code involved to introduce a three-way merge patch strategy would be considered a breaking change to the current behaviour anyways. Sorry!
