### ISSUE TITLE
Allow deploy secrets without list  permission for it

### ISSUE THREAD

**Issue by fenixam** [helm/helm#7317]
Output of `helm version`:
v3.0.0
Output of `kubectl version`:
oc v3.11.135
kubectl v1.11.0
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
OpenShift 3.11 on premise

Acccording to company policy it is not allowed to list/describe secrets but it is allowed to create/edit/delete.

In that scenario helm deployments with secrets is failing due to missing list RBAC permission:
helm upgrade --install ...
Error: UPGRADE FAILED: query: failed to query with labels: secrets is forbidden: User "system:serviceaccount:[redacted]-deployer" cannot list secrets in the namespace " -prod": no RBAC policy matched

Please allow helm to handle this exception and process deployment of  secrets.

**Comment by bacongobbler** [comment]
In order for Helm to determine the next release version, it needs to perform a lookup in its backend for the latest deployed version. This is required to generate the merge patch between the source and the target release.

https://github.com/helm/helm/blob/38670ebe3dfa5e8f61f58a0bd66098b7a0e9da77/pkg/action/upgrade.go#L122-L123

If you don't have the capability to list secrets, then Helm will be unable to function properly. An alternative solution would be to switch to an alternative storage backend using `export HELM_DRIVER=configmap`.

Hope this helps.
