### ISSUE TITLE
Helm 3 alternative namespace for Release

### ISSUE THREAD

**Issue by alexandrsemak** [helm/helm#7318]
Hi guys,

Is it possible to save release not in the same namespaces with deployment.. etc.. ?
We have 50 services installer via helm in dev/stage which also has own service's secret and now it is looks messy.

Can we optionally save release(secrets) in specific namespace ?

**Comment by hickeyma** [comment]
@alexandrsemak Unfortunately not as it is designed to save the release data as a secret in the namespace of the deployment.

The only way that I can see around it would be to organize the installation of the services into different namespaces. This might not be feasible for your use case.

**Comment by alexandrsemak** [comment]
@hickeyma gotcha, thank you for your answer. I understood that is possible to install each service in uniq namespace not sure if we able follow this approach.

**Comment by hickeyma** [comment]
Hope you can use this approach. Will close out the issue as answered. If you have any other questions, raise an issue or ask out in the helm-users Slack channel: https://github.com/helm/helm#community-discussion-contribution-and-support
