### ISSUE TITLE
helm3.0.0 fetch command produces waste

### ISSUE THREAD

**Issue by jianzzz** [helm/helm#7325]
Output of `helm version`:
3.0.0

`helm fetch xxx` produces temporary index.yaml under ~/.cache/helm/repository/, and there was no automatic cleaning of it.

**Comment by bacongobbler** [comment]
Can you demonstrate a set of commands to run to reproduce what you are seeing?

**Comment by bridgetkromhout** [comment]
Hi, @jianzzz - we need further information before we can try to reproduce this problem. Closing due to lack of reply.
