### ISSUE TITLE
(feat): helm 3 template is missing --kube-version flag

### ISSUE THREAD

**Issue by tamalsaha** [helm/helm#7326]
helm 2 template has --kube-version flag. But helm 3 seems to be missing it. This flag is necessary to optionally remove features from old version of Kubernetes. 

Can this flag be added back?

**Comment by bacongobbler** [comment]
Feel free to port this feature over.

**Comment by bacongobbler** [comment]
closing as stale.

**Comment by afirth** [comment]
it's fixed! in >= 3.6.0 I believe
https://github.com/helm/helm/pull/9040
