### ISSUE TITLE
Helm 2: plugins directory must be created manally

### ISSUE THREAD

**Issue by ecout** [helm/helm#7328]
Output of `helm version`: `Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}`

Output of `kubectl version`:  `Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): EKS - AWS

When installing a plugin the $HELM_HOME/plugins directory does not get created. It must be created manually.

> Local_User-MacBook-Pro:.helm local_User$ helm plugin install https://github.com/hypnoglow/helm-s3.git
Error: plugin home "$HELM_HOME/plugins" does not exist
Local_User-MacBook-Pro:.helm local_User$ mkdir plugins
Local_User-MacBook-Pro:.helm local_User$ helm plugin install https://github.com/hypnoglow/helm-s3.git
Downloading and installing helm-s3 v0.9.0 ...
Checksum is valid.
Installed plugin: s3

**Comment by bacongobbler** [comment]
Hi @ecout. You are correct in that the directory must be created before running `helm plugin install`. You can run `helm init --client-only` to create this directory for you.

In Helm 3, we were able to refactor a large portion of the backend that allows Helm to create the plugin directory if it does not already exist when calling `helm plugin install`. Unfortunately, the work involved to backport it would involve breaking changes to the API, so we cannot port it back to Helm 2.

Let me know what you think.

**Comment by bridgetkromhout** [comment]
Hi @ecout - thanks again for reaching out. Please let us know if you have additional questions; please do note that support for Helm 2 is ending: https://helm.sh/blog/helm-v2-deprecation-timeline/
