### ISSUE TITLE
Unable to install helm on Ubuntu Subsystem for Linux

### ISSUE THREAD

**Issue by restlessankyyy** [helm/helm#7330]
Hi I am unable to install helm on Ubuntu Subsystem for Linux. Please help

Below is the error. 

 **curl -L https://git.io/get_helm.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.**

Output of `helm version`: 2

Output of `kubectl version`: 1.14

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AWS EKS

**Comment by bacongobbler** [comment]
Can you try the download URL recommended in the documentation?

**Comment by restlessankyyy** [comment]
I tried this already 

 wget  https://git.io/get_helm.sh | bash
--2020-01-03 15:16:52--  https://git.io/get_helm.sh
Resolving git.io (git.io)... ::ffff:146.112.252.226, ::ffff:146.112.56.222, ::ffff:146.112.56.186, ...
Connecting to git.io (git.io)|::ffff:146.112.252.226|:443... connected.
ERROR: cannot verify git.io's certificate, issued by ‘CN=Cisco Umbrella Secondary SubCA lon-SG,O=Cisco’:
 Unable to locally verify the issuer's authority.

**Comment by bacongobbler** [comment]
Can you please try the instructions following the documentation: https://helm.sh/docs/intro/install/#from-script

Is there a place where git.io is recommended in the documentation? It’s not a URL I’ve used before. That’s a github asset, right?

Try the raw github URLs listed in the documentation and see if you see an improvement.

**Comment by bacongobbler** [comment]
Also check and ensure you have the proper CA certificates installed on your machine. Should be `apt install ca-certificates`.

**Comment by restlessankyyy** [comment]
Dope @bacongobbler .. It works .. Thank you so very much..

helm version
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
