### ISSUE TITLE
Can we install helm using terraform in Azure? If yes can you please connect to reference document

### ISSUE THREAD

**Issue by pranay123111** [helm/helm#7333]
Output of `helm version`:

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by bacongobbler** [comment]
like this? https://www.terraform.io/docs/providers/helm/index.html

**Comment by bridgetkromhout** [comment]
Hi, @pranay123111 - we believe we have answered this question, above. If you have further questions please let us know.
