### ISSUE TITLE
regex for chart version

### ISSUE THREAD

**Issue by Sushama-pan** [helm/helm#7335]
Output of `helm version`:
3
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
vagrant

My chart versions are like 3.0.0+build.123 , 3.0.0-alpha.123.
I am able to push chart but while pull how to specify chart version? I am trying to add regex in:
helm pull --version 3.0.0\+build.* chartmuseum/simplechart

The above command gives output as improper constraint: 3.0.0+build.* 

Regex not working any idea?
Please help. Thank you!!

**Comment by Sushama-pan** [comment]
> Output of `helm version`:
> 3
> Cloud Provider/Platform (AKS, GKE, Minikube etc.):
> vagrant
> 
> My chart versions are like 3.0.0+build.123 , 3.0.0-alpha.123.
> I am able to push chart but while pull how to specify chart version? I am trying to add regex in:
> helm pull --version 3.0.0+build.* chartmuseum/simplechart
> 
> The above command gives output as improper constraint: 3.0.0+build.*
> 
> Regex not working any idea?
> Please help. Thank you!!

**Comment by thomastaylor312** [comment]
So helm fetch/pull is currently only meant to be used to pull a specific chart with a given server constraint. It doesn't support fetching multiple charts using a regex. So in your case, to pull the chart you want, you'll need to do `helm pull --version 3.0.0-alpha.123 chartmuseum/simplechart`. If you want to pull multiple, you'll want to probably script it. Does that make sense?

**Comment by Sushama-pan** [comment]
I do not want to fetch multiple charts but the latest one. For example, I have below charts:
3.0.0-alpha.10,3.0.0-alpha.11, 3.0.0-alpha.12
When I do: helm pull --version 3.0.0-alpha.*
It will pull the latest i.e. 3.0.0-alpha.12 from the repo.

Is this possible?

**Comment by bacongobbler** [comment]
If you wish to pull the latest version, omit the -version flag.

**Comment by bridgetkromhout** [comment]
Hi, @Sushama-pan - as explained above, command-line options for [helm pull](https://helm.sh/docs/helm/helm_pull/) are available to modify which version is pulled. I will now resolve this issue; please open a new issue if you have further questions! Thanks.
