### ISSUE TITLE
Templating can't evaluate field .Release.Name

### ISSUE THREAD

**Issue by Xcess** [helm/helm#7337]
Output of `helm version`: `version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}`

Output of `kubectl version`: `Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"archive", BuildDate:"2019-12-13T07:34:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Kubeadm

---
using .Release.Name to define variables does non-consistent behaviour and doesn't work as expected.
I use it in templates/_helpers.tpl like this:
```
{{- define "cdnapi.elasticsearch.fullname" -}}
{{- printf "%s-%s-client" .Release.Name "elasticsearch" | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{- define "cdnapi.mariadb.fullname" -}}
{{- printf "%s-%s" .Release.Name "mariadb" | trunc 63 | trimSuffix "-" -}}
{{- end -}}
```

and reference it from my configmap.
while rendering template or installing it, I always get error:
```
oad.go:112: Warning: Dependencies are handled in Chart.yaml since apiVersion "v2". We recommend migrating dependencies to Chart.yaml.
Error: template: cdnapi/templates/_helpers.tpl:66:34: executing "cdnapi.elasticsearch.fullname" at <.Release.Name>: can't evaluate field Release in type string
```

I tried changing the name to something else, moving it before the other one. each time one of them fails (always Elasticsearch unless I change the name to mariadb2 then mariadb fails!). I think it is clearly a bug in template behaviour.

**Comment by thomastaylor312** [comment]
Hey @Xcess! So could you upload your chart or snippets of the chart where you are calling these templates? That error seems like a string is being passed to it instead of the full object. So seeing the chart would help diagnose things

**Comment by Xcess** [comment]
I did not know what part may be of use, so i uploaded the whole chart. (redacted and changed some parts for security)
I have uploaded it here:
https://file.io/cTuIFH  (api.tar.gz)

**Comment by thomastaylor312** [comment]
Sorry for the delay getting back to this. The link is giving me a 404. Can you please upload that tarball in another comment in this issue?

**Comment by thesayyn** [comment]
I'm having this problem as well.

**Comment by bacongobbler** [comment]
That’s an intentional design decision from text/template. From the docs:

```
{{range pipeline}} T1 {{end}}
	The value of the pipeline must be an array, slice, map, or channel.
	If the value of the pipeline has length zero, nothing is output;
	otherwise, dot is set to the successive elements of the array,
	slice, or map and T1 is executed. If the value is a map and the
	keys are of basic type with a defined order, the elements will be
	visited in sorted key order.
```

https://golang.org/pkg/text/template/

**Comment by thesayyn** [comment]
I must have missed it. Thank you for the clarification.

**Comment by bridgetkromhout** [comment]
Hi, @thesayyn - looks like your question was answered, so I'm resolving this issue now. Please let us know if you have further questions; thanks!

**Comment by ansromanov** [comment]
This is because you lose global scope when entering the range function.
The following snippet should work for you:
```
{{- define "database.connection-uri" -}}
    {{- $uri := "mongodb://" -}}
    {{- range $index := until (.Values.database.replicas | int) -}}
        {{- $namespace := printf "%s-database" $.Release.Name -}}
        {{- $node := printf "%s-%d.mongo.%s.svc.cluster.local," $namespace $index $.Release.Namespace -}}
        {{- $uri = printf "%s%s" $uri $node -}}
    {{- end -}}
    {{- printf $uri | trimSuffix "," | quote -}}
{{- end -}}
```
