### ISSUE TITLE
Helm produces no output

### ISSUE THREAD

**Issue by DrissiReda** [helm/helm#7338]
I downloaded the binaries of the last 3 versions (v 3.0.0 through 3.0.2) of helm and they all give the same output, which is literally nothing.

I tried:

`helm`
`helm help`
`helm repo`

`helm plzgimmesomething`

It just doesn't display anything, no errors no results nothing.

Output of `ldd helm`

```bash
	linux-vdso.so.1 (0x00007ffe2bcd0000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f325d1aa000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f325cfb9000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f325d1e7000)
```

md5sum `f33f6dbdd892054d48ff6127cfd372dfe189f8d2ddaf3f79fb734de044df77b9`

sha256sum `1d737be9c4cf46d40410f6a1943960e9`

**Comment by bacongobbler** [comment]
What happens if you append the `—debug` flag?

**Comment by DrissiReda** [comment]
I had an issue with permissions of ~/.kube. Thank you, the debug flag revealed it. But shouldn't you at least have the help displayed without the need for any parameters?
