### ISSUE TITLE
Consider supporting cryptographic signatures for plugins

### ISSUE THREAD

**Issue by antevens** [helm/helm#7342]
The current plugin installation and subsequent execution is risky at best since it allows arbitrary code to be downloaded from any URL and executed without the end user realizing that plugins might not be associated with the helm project. Further more there is no verification that the plugin code originates from the URL specified.

We should consider setting up a signature system similar to how we sign and verify helm charts and give an error if  an attempt is made to install an unsigned plugin then provide a flag to override this behavior but making it clear to the end user that they are assuming the verification responsibility manually (--insecure).

If a plugin/chart is signed then we should validate against the trusted GPG keys in the users trust store and refuse to install if the signature check fails.

**Comment by bacongobbler** [comment]
closing as stale.
