### ISSUE TITLE
Consider supporting TLS re-negotiation

### ISSUE THREAD

**Issue by antevens** [helm/helm#7344]
See related Gobug: https://github.com/golang/go/issues/5742

Error: looks like "https:/helm.example.com/pulp/Default_Organization/Library/custom/sde/sde-helm/" is not a valid chart repository or cannot be reached: Get https://helm.example.com/pulp/Default_Organization/Library/custom/sde/sde-helm/index.yaml: local error: tls: no renegotiation

Output of `helm version`:
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

**Comment by thomastaylor312** [comment]
Since this is supported in the main go crypto library, I think it would be fine to add this. Marking as a feature. Anyone who wishes to work on it, please let us know here!

**Comment by bacongobbler** [comment]
closing as stale.
