### ISSUE TITLE
values.Table does not support valuse as an array of object 

### ISSUE THREAD

**Issue by CodeDing** [helm/helm#7347]
## Example

**pkg/chartutil/values.go**

https://github.com/helm/helm/blob/ad07bb690dbf34e7067171235861a3c0fb9897b6/pkg/chartutil/values.go#L87

if the values.yaml has a key and value like below, then I use the `values.Table("chartKey1")`, it will return the error `no table name "chartKey1"`. I am confused with it whether it is a bug or a forbidden for chart value to set the key-value which looks similar to below format.

```
chartKey1:
   -  key11: value11
       key12: value12
```

**Comment by bacongobbler** [comment]
I don't believe that is a table. A dash is YAML syntax for an array.

Have you tried the following instead?

```
chartKey1:
  key11: value11
  key12: value12
```

**Comment by bacongobbler** [comment]
closing as stale.
