### ISSUE TITLE
--registry-config flag is not honored

### ISSUE THREAD

**Issue by EItanya** [helm/helm#7351]
Currently, the helm registry commands look in a hardcoded place for the docker config file:
https://github.com/helm/helm/blob/2eab781b35019ce452738012092f9df4ce9fdf00/cmd/helm/root.go#L416
There is a flag which is supposed to do this, `--registry-config` but as shown in the above code, it is not honored. 
This brings up 2 issues
1) The default spot it checks for the config file is slightly unintuitive.
2) There is currently no way to instruct helm to use a different location

Happy to do a PR

**Comment by bacongobbler** [comment]
Thanks for identifying this. Feel free to work on a fix.

**Comment by EItanya** [comment]
@bacongobbler PR as mentioned above.

**Comment by bacongobbler** [comment]
fixed in #7356.
