### ISSUE TITLE
Unable to deploy two different namespaces due to resource conflict

### ISSUE THREAD

**Issue by JiandongRuan** [helm/helm#7359]
Repro steps:
1. deploy nginx ingress controller (or jetstack/cert-manager) to one namespace
2. deploy the same chart to another namespace
    helm upgrade --namespace private --install --wait --version 0.12.0 cert-manager jetstack/cert-manager

    This will fail due to resource conflict. The error message is "Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: kind: ClusterRole, namespace: , name: cert-manager-cainjector"

Output of `helm version`:
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.12", GitCommit:"524c3a1238422529d62f8e49506df658fa9c8b8c", GitTreeState:"clean", BuildDate:"2019-11-14T05:26:24Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

**Comment by hickeyma** [comment]
@JiandongRuan The error seems to be saying that the chart you are deploying contains a cluster wide resource. This means that the resource in conflict is not specific to the namespace and therefore cause a conflict when it tries to deploy the chart in the 2nd namespace, as it already exists.

Can you check in your chart and deployment for resource: `cert-manager-cainjector`? This seems to be causing the conflict.

**Comment by JiandongRuan** [comment]
Can Helm handle cluster wide resources in a more elegant way? Chart "stable/nginx-ingress" and "jetstack/cert-manager" deploys many cluster wide resources. cert-manager-cainjector is just one of them. I need to delete them before deploying into a 2nd namespace.

**Comment by hickeyma** [comment]
@JiandongRuan The issue encountered might be due to chart installation/design or configuration issue rather than with Helm. What I mean by this is, why are conflicts occurring when installing more than one instance of a chart? If the chart explicitly declares a cluster wide resource to be created then does this mean that the chart is designed to be installed only once in a cluster?  Or do you need to change configuration that enables it to be installed more than once i.e. cluster wide resource name change?

It would be worth checking with chart docs and chart maintainers of the charts to understand if it is possible to deploy more than one instance.

**Comment by JiandongRuan** [comment]
Thanks for the help. I found the needed information from the charts documentation.

**Comment by mathieu-benoit** [comment]
Out of curiosity @JiandongRuan, did you resolve this by using this flag `controller.scope.enabled=true`?

**Comment by JiandongRuan** [comment]
@mathieu-benoit , I used controller.scope.enabled=true to resolve the issue with "stable/nginx-ingress". For cert-manager, it is supposed to be *globally* deployed.
