### ISSUE TITLE
docs: Better Description of Release / ReleaseVersion CRDs for helm 3

### ISSUE THREAD

**Issue by ichtestemalwieder** [helm/helm#7362]
Hello, 

I have read that helm 3 stores (instead of using Tiller) this information in CRDs (Release / ReleaseVersion) in the current Namespace of the "install". But I was not able to "find" these CRDs in my cluster: 

```
kubectl api-resources 
kubectl get all --all-namespaces 
```
Neither shows any of these CRDs? How can I inspect these CRDs and `kubectl describe` them? This should be documented as it is important for developers to better understand the internals/architecture/working of helm. Thanks!

Update: 
I have found in the docs a hint to secrets: https://helm.sh/docs/faq/#secrets-as-the-default-storage-driver. Does this mean Release and ReleaseVersion are not "offical CRDs" and are always stored in a secret?

**Comment by bacongobbler** [comment]
After discussing the design further, the proposal was dropped from Helm 3 due to existing design issues with CRDs. Instead, the existing secret storage layer from Helm 2 became the default.

Use `kubectl get secrets` to access that information.

Hope this helps.
