### ISSUE TITLE
[helm create] Add autoscaling(hpa) boilerplate

### ISSUE THREAD

**Issue by naseemkullah** [helm/helm#7369]
Elasticity is an important feature for cloud native stateless apps such as the one deployed out of the box with helm create.  Allowing users to easily autoscale newly created apps would be beneficial.

I propose we add a disabled by default hpa, with default values of 1 to 100 replicas and 80% cpu utilization threshold.

cc @helm/chart-maintainers

**Comment by scottrigby** [comment]
@naseemkullah I'm sure this is on your radar already, but just want to note here for others that any PR to address this issue should be sure to add a Helm 3 "Horizontal Pod Autoscaler requires condition" (the third use case described here: https://github.com/helm/charts/issues/19008).

**Comment by naseemkullah** [comment]
Yep, I plan to implement it as such upon hereby agreement from chart maintainers.

**Comment by scottrigby** [comment]
Not sure why that CC link didn't work - maybe you need specific repo perms to do it.

☝️ CC @helm/charts-maintainers

**Comment by naseemkullah** [comment]
Thanks @scottrigby

**Comment by naseemkullah** [comment]
https://github.com/helm/helm/pull/7381 created. Please take a look 🙏

**Comment by hickeyma** [comment]
PR #7381  merged.
