### ISSUE TITLE
Helm Library packages shouldn't include dependencies

### ISSUE THREAD

**Issue by guice** [helm/helm#7371]
Built a helm library chart. It has dependency on a "common" chart.  But this is a _library_ chart, i.e. not a deployable chart.

`helm package library-chart` shouldn't grab dependencies. Those should be done at the parent chart (type: application), example setup:

##### Charts:
- Library chart "common", type: Library.
- Library chart "nginx", type: library.
- Application chart "my-app", type: application

##### Links:
* "common" has no dependencies.
* "nginx" depends on "common"
* "my-app" depends on "nginx" 

#### Expected behavior:
* helm package nginx - should not get "common" because it's a library chart. 
* helm package my-app should coalesce all the dependencies from itself and sub-charts, and pull in all dependencies, i.e. pull in "nginx" and "common" to "my-app/charts"

Why we shouldn't pull in dependencies for library charts: Add new chart "php" that depends on "base"

* If dependencies are pulled in: you now have duplicates -- "common" will reside in "php" and "nginx". 
* If "my-app" added "common" dependency, now there's a third in "my-app/charts"
* If you coalesce dependencies: "common" is only pulled in once within "my-app" (type: application) chart.

Since developers are pretty firm on SemVer - use SemVer comparisons to insure compatibility across the board.

Output of `helm version`: v3.x
Output of `kubectl version`: n/a
Cloud Provider/Platform (AKS, GKE, Minikube etc.):  n/a

**Comment by hickeyma** [comment]
@guice This is a very good scenario that you raise, thanks.

Thinking about this off top of my head. A library chart is a type of chart and follows the flow of how chart is processed, apart for not being installable.  This means it is the same as an application chart with regard to how it is packaged and included as a dependency. From quick glance, it looks difficult to separate this in a nice fashion.

Hmm, not sure of a solution around the dependency inclusions. Maybe someone could jump in and provide an insight to the issue?

**Comment by bacongobbler** [comment]
closing as stale.
