### ISSUE TITLE
Error :invalid argument "1800" for "--timeout" flag :time : missing unit in duration 1800

### ISSUE THREAD

**Issue by kohithms** [helm/helm#7375]
Ho Team,

Issue: When we are using the Option --wait --timeout 1800 during Helm Upgrade.  The system is throwing an error message "Error :invalid argument "1800" for "--timeout" flag :time : missing unit in duration 1800" 

We have tried in helm V3.0.0 and V3.0.2 but end up with the same error.

As per Public documentation, V3.0.0 should be able to work with the tag --timeout int

**Reference link:** https://helm.sh/docs/intro/using_helm/#helpful-options-for-install-upgrade-rollback

Output of `helm version`: V3.0.0 and V3.0.2

Output of `kubectl version`: NA

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AKS

Kindly let me know in case of any additional info required. 

<<Need ASAP attention on the issue !! **Impacting the Production Environment** >>

**Comment by hickeyma** [comment]
@kohithms Can you try using the flag as follows: `--timeout 1800s`?

**Comment by kohithms** [comment]
Hey @hickeyma , I have tried ** --timeout 1800s ** still we are experiencing the issue.

**Comment by hickeyma** [comment]
@kohithms That looks like  an issue with the upgrade command. It seems as if you passed a release name of `<Environemnt_Name>` which doesn't exist.

Here is output of when I use the command with `--timeout` on a Helm build from master:
```console
$ helm3 install --wait --timeout 1800s chrt-7375 chrt-7375/
NAME: chrt-7375
LAST DEPLOYED: Wed Jan 15 07:44:46 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=chrt-7375,app.kubernetes.io/instance=chrt-7375" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace default port-forward $POD_NAME 8080:80
```

**Comment by kohithms** [comment]
Hello @hickeyma ,

Thanks for your inputs. we have verified that the <Environment> is up and available. Post making few changes we end up in having the below error "

2020-01-17T13:00:37.3803047Z ##[error]Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Ingress.spec): unknown field "affinity" in io.k8s.api.extensions.v1beta1.IngressSpec

**Comment by santmcodes** [comment]
Is there any workaround on this ? I am having the same issue on v3.0.2

**Comment by hickeyma** [comment]
@kohithms This looks like an issue with the api field and the k8s version of the cluster. Some apis are deprecated by k8s 1.16: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

**Comment by hickeyma** [comment]
What is your issue @santmcodes?

**Comment by santmcodes** [comment]
Same as others- it was expecting unit for --timeout 600
helm install charts/x-sn -f ~/b.yaml --set images.x-sn.tag=b-n x-service --wait --timeout 600

I tried 600s and 600m but didnt work.
Finally stepped back and uninstalled it.
Installed an older version "v2.11.0" and the same command worked like charm.

Please fix it as it blocks us and creates bad impression.

I have informed others not to upgrade your newer versions.

/san

**Comment by hickeyma** [comment]
@santmcodes In Helm 3 you need the unit. It works as described in https://github.com/helm/helm/issues/7375#issuecomment-574537817

**Comment by kohithms** [comment]
Thanks @hickeyma @scudelletti @muffix  for the inputs.
