### ISSUE TITLE
Feature: migration between charts

### ISSUE THREAD

**Issue by mitar** [helm/helm#7379]
I would like to have a "lite" version of the chart (public/open source) and and "enterprise" version of the chart (private/licensed/payed for). I would like that people can try out and install lite version of a chart for themselves. If they decide to upgrade to "enterprise", I would want to provide them with chart (repository) to install this new chart. But I would also want to make this upgrade process smooth by reusing data from the "lite" version. So how can enable that users can have "lite" versions of the app (and multiple chart versions through time, if they decide to stay with just the "lite" version), but also to migrate to "enterprise" version and then have multiple chart versions there through time.

**Comment by bridgetkromhout** [comment]
Hi, @mitar - as this use case is not one requested by many users, we should gather more detail of how it's proposed to work before considering it. If you are interested in proposing this with the supporting information, please take a look at the Helm Improvement Proposal process (https://github.com/helm/community/blob/master/hips/hip-0001.md) and submit a HIP - thanks!
