### ISSUE TITLE
Customize the default nginx chart

### ISSUE THREAD

**Issue by USER0308** [helm/helm#7384]
Hello, when I typed `helm create XXX`, I got a chart which image is `nginx:stable`. I was confused that is there any method to change the default image like `hub.myprivate/nginx:stable`? Or is there any method to customize the default chart, so that when I type `helm create XXX`, it use my customized chart ranther than the default nginx one?

**Comment by fenngwd** [comment]
You could customize your chart before installing it.

Just like this [ https://helm.sh/docs/intro/using_helm/#customizing-the-chart-before-installing](https://helm.sh/docs/intro/using_helm/#customizing-the-chart-before-installing).

**Comment by bacongobbler** [comment]
see also https://helm.sh/docs/chart_template_guide/getting_started/#a-starter-chart
