### ISSUE TITLE
Chart.lock doesn't update 

### ISSUE THREAD

**Issue by botjaeger** [helm/helm#7386]
Output of `helm version`:
`version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}`
Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  EKS

When dependencies are removed in a Chart.yaml file, doing `helm dep update` does not update the Chart.lock and it doesn't remove the subcharts/.tgz on charts/ directory

**Comment by bacongobbler** [comment]
It is entirely possible that a user would switch from a managed chart to something they manage themselves. In those cases, helm takes a defensive approach: rather than deleting someone's work, helm does not clean up the `charts/` directory.

That being said, perhaps an informational message to inform the user that there is still stray charts in the `charts/` directory that they may wish to remove manually would seem like a good option. Will that work for you?

**Comment by botjaeger** [comment]
> It is entirely possible that a user would switch from a managed chart to something they manage themselves; i.e. a forked version of the chart, directly managing the dependency, etc. In those cases, helm takes a defensive approach: rather than deleting someone's work, helm does not clean up the `charts/` directory when a dependency is removed from the tree.
> 
> That being said, perhaps an informational message to inform the user that there is still stray charts in the `charts/` directory that they may wish to remove manually would seem like a good option. Will that work for you?

thank you for response.

that will do, but can you also add an option like `helm dep update --clean` to automatically rebuild the `Chart.lock` and remove outdated subcharts in `charts/` ?

**Comment by bacongobbler** [comment]
feel free to work on a PR! I don't have the time to work on new features, but I'd happily review PRs from the community.

**Comment by botjaeger** [comment]
I don't have any Go lang knowledge, but I'll try 

thanks

**Comment by bridgetkromhout** [comment]
Hi, @botjaeger and others interested. We now have a path forward for proposals: if you're reading this and thinking "but this should happen!", please file a [Helm Improvement Proposal](https://github.com/helm/community/blob/master/hips/hip-0001.md) to discuss it with the community (or send a pull request if you'd like to implement it). Meanwhile, I'm closing this issue as inactive.
