### ISSUE TITLE
Best practice for deploying dependent components (subcharts vs multiple helm calls)

### ISSUE THREAD

**Issue by AlexEPetrov** [helm/helm#7390]
Hi All. Probably stupid question and hope it's right place to ask - I have concern what is best practice to deploy dependent components into k8s. I understand that Helm suggests clear way using dependencies (subcharts), but looking at this issue for example - https://github.com/helm/helm/issues/6850, I feel not quite comfortable to deploy critical thing (say, message broker or database) and supporting components (like Prometheus or Grafana) in one chart/bundle since possible error in supporting components deployment may lead to failure of the whole chart deployment including new version of the main (sql) component. To avoid this - is it probably better practice to deploy individual components separately into k8s using multiple helm upgrade commands (helm upgrade my-sql, then helm upgrade Prometheus, then helm upgrade grafana, etc.)? In this case possibly failed grafana release does not affect sql release at all. Is it safer approach? Thanks!

**Comment by bacongobbler** [comment]
closing as stale.
