### ISSUE TITLE
how to print the middle result when i dry-run a chart

### ISSUE THREAD

**Issue by zh-jn** [helm/helm#7396]
I am a newbie to helm,  I found it is hard to find the syntax error of helm chart through the output of the command `helm install --dry-run --debug XXX -g`.

How can i get the middle result which is the direct output of evaluation of templates, but not the output of k8s.

**Comment by hickeyma** [comment]
@williamjnzhang Are you looking for the `helm template` command? The following docs should provide more context:

- Helm 3: https://helm.sh/docs/chart_template_guide/

- Helm 2: https://v2.helm.sh/docs/chart_template_guide/

**Comment by bacongobbler** [comment]
closing as stale.
