### ISSUE TITLE
Rest Based API for helm 

### ISSUE THREAD

**Issue by akshaysharama** [helm/helm#7398]
Helm version 
- 2.8.1
kubectl version
- 1.9.1

we are building some application(in go), which needs to interact with tiller using rest api's .

Is there any rest-api document for helm or helm supports any rest based api?

**Comment by hickeyma** [comment]
Communication to Tiller is through gRPC. There is no supported REST API.
You could try using Helm as a Go SDK. Take a look in `https://github.com/helm/helm/tree/dev-v2/cmd/helm` for patterns the CLI uses.
Alternatively, have a look online. Some info in blogs like https://banzaicloud.com/blog/helm-rest-api/ about working around this.
