### ISSUE TITLE
Helm Status Command has no all Namespace option

### ISSUE THREAD

**Issue by rishiraaz** [helm/helm#7403]
Output of `helm version`:
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2019-12-11T12:42:56Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2019-12-11T12:34:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AWS

Helm status command should have an option for all namespaces

**Comment by hickeyma** [comment]
@rishiraaz Just wondering why you need all namespace flag on the `helm status` command? I am asking because you run the command for a `RELEASE_NAME` which is specific to a namespace.

**Comment by rishiraaz** [comment]
There may be a need where someone wants to check the status of all the releases. @hickeyma

**Comment by hickeyma** [comment]
The status command requires a release name. Are you asking to extend the command to get status for all releases when the release name is not specified?

**Comment by bacongobbler** [comment]
closing as stale.
