### ISSUE TITLE
Cannot disable validation during helm 3 install

### ISSUE THREAD

**Issue by muvaf** [helm/helm#7404]
In Kubernetes 1.14 and below, there is no validation mechanism for CRD fields like the following:
```
maxUnavailable:
  anyOf:
  - type: integer
  - type: string
  x-kubernetes-int-or-string: true
```
It's been added in 1.15 with https://github.com/kubernetes/kubernetes/pull/78815

It's still possible to install CRDs with that validation block but you have to turn off the validation. `kubectl` has `--validate=[true,false]` flag for this but Helm 3 doesn't have a way to disable the validation. Currently, our users with Kubernetes version 1.14 and lower cannot install our controller with Helm 3; they either have to fall back to Helm 2 or do something like:
```
helm3 template crossplane-alpha/crossplane --validate=false | kubectl --validate=false apply -f -
```
which works but obviously they don't get an actual helm release deployed to the cluster.

It'd be great if we could simply tell users with K8s 1.14 and below to use `--validate=false` together with `heml3 install`.

Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2019-12-11T12:42:56Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.9", GitCommit:"500f5aba80d71253cc01ac6a8622b8377f4a7ef9", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:04Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): `minikube v1.6.1 on Darwin 10.15.2`

**Comment by bacongobbler** [comment]
see https://github.com/helm/helm/pull/6819
