### ISSUE TITLE
Helm 3 - Uses the default values file without informing you of an error in your custom values file

### ISSUE THREAD

**Issue by PipTurner** [helm/helm#7406]
We have found that if you run the following command:

helm upgrade --install my-release --values ./my-values.yaml ./charts/my-chart --namespace dev

and there is an error in your my-values.yaml the error is suppressed and the default values file in the chart is used instead without any notifications. I can understand the behaviour of using the default values.yaml but it would be best if the error is still presented on screen.

Note in our case the error in our custom values file was simply an incorrectly named root value.

**Output of `helm version`:** 

version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}

**Output of `kubectl version`:** 

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**Cloud Provider/Platform (AKS, GKE, Minikube etc.):** AWS

**Comment by bacongobbler** [comment]
closing as stale.
