### ISSUE TITLE
Minio installation error in GKE related to chart name

### ISSUE THREAD

**Issue by Shriyut** [helm/helm#7407]
I'm trying to setup spinnaker in GKE 

For this purpose when I run the command 

helm install minio --namespace spinnaker --set accessKey="myaccesskey" --set secretKey="mysecretkey" --set persistence.enabled=false stable/minio

It throws the following error on my screen

Error: This command needs 1 argument: chart name

I'm not sure why since the command seems to be correct

**Comment by hickeyma** [comment]
@Shriyut What version of Helm are you using? If Helm 2, you need to specify `--name` flag when you add a release name. Can you try this: `helm install --name minio --namespace spinnaker --set accessKey="myaccesskey" --set secretKey="mysecretkey" --set persistence.enabled=false stable/minio`?

**Comment by bacongobbler** [comment]
closing as stale.
