### ISSUE TITLE
Helm broken after installation (Helm 3)

### ISSUE THREAD

**Issue by KrustyHack** [helm/helm#7408]
Output of `helm version`:

Can't output, `helm version` return nothing.

Output of `kubectl version`:

Not needed, Helm seems not working even when just typing `helm` in my console.

```
(base) krustyhack@KrustyMSI:~/linux-amd64$ ls
helm  LICENSE  README.md
(base) krustyhack@KrustyMSI:~/linux-amd64$ ./helm version
(base) krustyhack@KrustyMSI:~/linux-amd64$ echo $?
1
(base) krustyhack@KrustyMSI:~/linux-amd64$
```

Did I missed something ? I'm on Ubuntu 18.04 and up to date.

**Comment by bacongobbler** [comment]
does `--debug` display anything?

**Comment by KrustyHack** [comment]
Fixed. I switched to a new GKE cluster and now `helm` work nicely.

Is it normal that we can't even do a `helm version` without a K8S cluster ready ?

**Comment by bacongobbler** [comment]
it's a bug that was addressed in master. The next Helm 3 release will have that patch available. See #6863 for more information.
