### ISSUE TITLE
helm install xxx stable/mariadb failed!!!

### ISSUE THREAD

**Issue by XiaoGe2030** [helm/helm#7412]
helm verison : 3.0.2
k8s version :1.17.0
![image](https://user-images.githubusercontent.com/22184388/72534201-5da9d700-38b1-11ea-883e-85f65d0d924c.png)

when I install stable/mariadb by helm ,There's always “Access denied” with the  slave , detail info like this:

![image](https://user-images.githubusercontent.com/22184388/72534506-e45eb400-38b1-11ea-8ae3-a3e356b8ffcd.png)

That's why?

**Comment by XiaoGe2030** [comment]
I just follow the example on the Helm website.  https://helm.sh/docs/intro/using_helm/

**Comment by bacongobbler** [comment]
Looking more closely at the logs, it appears that your cluster is showing signs that it is in an unhealthy state. Have you tried resolving that first?

**Comment by ReSearchITEng** [comment]
To me it looks more of an issue related to mariadb parameters: https://github.com/helm/charts/tree/master/stable/mariadb

You may want to try a more simple example of chart to test helm (without pvs, etc).
If you are sure you've put the right params, maybe it's a good idea to open a defect to the helm chart itself, here: https://github.com/helm/charts/issues

**Comment by bacongobbler** [comment]
closing as stale.
