### ISSUE TITLE
helm search hub should optionally return the repo URL as part of the results

### ISSUE THREAD

**Issue by omkensey** [helm/helm#7419]
It would be nice if `helm search hub` could give the URL of the repo (not necessarily by default, but as an optional column/JSON key), so as to avoid a roundtrip to the Hub description page for the actual repo URL if I can tell from the search listings which chart repo I want.

**Comment by bacongobbler** [comment]
This is a great suggestion, @omkensey. I think adding another field to the table output displaying the repository URL would be a welcome change.

A little bit of context here: The idea with `helm search hub` returning that URL was that the chart repository maintainers were looking to add support to use that URL as input to `helm install`, like so:

```
><> helm search hub wordpress --max-col-width 0 | tail -n 1
https://hub.helm.sh/charts/bitnami/wordpress           	9.1.1        	5.3.2      	Web publishing platform for building blogs and websites.
```

then:

```
><> helm install wordpress https://hub.helm.sh/charts/bitnami/wordpress
```

cc'ing @mattfarina as he may have more context on where we are with that particular feature.

**Comment by SimonHeimberg** [comment]
> A little bit of context here: ...
Thank you. I did not see this in the doc. Now I found it in `content/docs/intro/using_helm.md` since I knew what to look for.

**Comment by tharun208** [comment]
I like to work on this

**Comment by mattfarina** [comment]
I like the idea of adding the column. I would also like to see `><> helm install wordpress https://hub.helm.sh/charts/bitnami/wordpress` work. This might be something to add into the Artifact Hub as well.
