### ISSUE TITLE
helm template rendering should ignore swap/temp files

### ISSUE THREAD

**Issue by omkensey** [helm/helm#7420]
A common issue when working locally with charts is that an editor crashes (or the user is still in it) and a swap file is left in the template directory, causing duplicate rendering of resources.  This can cause anything from annoying but harmless errors about duplicate names to unwanted multiple resource creation.  `helm package` already ignores these files via `.helmignore` (see #989) and IMHO `helm install/upgrade/template/etc.` should ignore them too (either just using `.helmignore` or a new file specific to template rendering).

**Comment by Cweiping** [comment]
It seems to me that this logic is universal. If it is dir, it will be ignored during parsing. https://github.com/helm/helm/blob/master/pkg/chart/loader/load.go#L43   
https://github.com/helm/helm/blob/master/pkg/chart/loader/directory.go#L87

**Comment by bacongobbler** [comment]
closing as stale.
