### ISSUE TITLE
(feat): Support --hook-mode for helm template command

### ISSUE THREAD

**Issue by tamalsaha** [helm/helm#7421]
`helm template` command supports `--no-hooks` flag. But I would like to pass a flag `--mode=install` to only render install hooks. Similarly for uninstall. Can this feature be supported in helm ?

**Comment by tamalsaha** [comment]
This feels like a simple change like 
https://github.com/helm/helm/blob/master/cmd/helm/template.go#L80-L84

I am happy to send a pr, if this feature is acceptable.

**Comment by bridgetkromhout** [comment]
Hi, @tamalsaha - thank you for your idea. If you'd like, please file a [Helm Improvement Proposal](https://github.com/helm/community/blob/master/hips/hip-0001.md) to discuss it with the community (or send a pull request if you'd like to implement it). Meanwhile, I'm closing this issue as inactive.
