### ISSUE TITLE
Helm3 install --atomic hangs forever

### ISSUE THREAD

**Issue by andresmgot** [helm/helm#7426]
Hi,

I am trying to install a release using the `--atomic` flag but it seems that it hangs forever:

```
▶ helm3 install bar stable/mariadb -n default --atomic
Error: release bar failed, and has been uninstalled due to atomic being set: timed out waiting for the condition
```

The chart resources get actually installed in the cluster but the command eventually times out and the release gets deleted:

```
▶ helm3 ls
NAME           	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART               	APP VERSION            
```

Is this a bug or am I missing something?

Output of `helm version`:
```
▶ helm3 version
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```
Output of `kubectl version`:
```
▶ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T21:04:32Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-16T01:01:59Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): `kind`

**Comment by hectoralicea** [comment]
I have the same issue.  
```
$ helm3 install nss-prod-ingress stable/nginx-ingress --atomic --wait -f /tmp/nginx-ingress-values.yml --kubeconfig /tmp/tf-enttestaks05/kubeconfig.yml --kube-context enttestaks05 --namespace nss-prod --log-dir /tmp/nginx-ingress/
Error: release nss-prod-ingress failed, and has been uninstalled due to atomic being set: timed out waiting for the condition

$ helm3 version
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:34Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"1da9875156ba0ad48e7d09a5d00e41489507f592", GitTreeState:"clean", BuildDate:"2019-11-14T05:19:20Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

$ helm3 ls
NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART	APP VERSION

**Comment by bacongobbler** [comment]
Have you been able to identify the issue? No clue on my end, sorry. Let us know if you find anything.

**Comment by lindhe** [comment]
I'm not able to replicate the issue.

**`helm version`**
```
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

**`kubectl version`**
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-21T22:17:28Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by andresmgot** [comment]
oh, I see the issue here. For some reason, my deployments were failing and the `wait` flag is automatically enabled when using `atomic`:

https://github.com/helm/helm/blob/e84b61b2db719be7c08e461fcb1f9c61bd03513f/pkg/action/install.go#L196

That's unexpected, I don't really need to wait when using the atomic flag. I just want to clean up the installation in case there is something wrong with the installation (e.g. an invalid manifest) just like it was for Helm 2. What do you think @bacongobbler ?

cc/ @thomastaylor312 as the author

**Comment by thomastaylor312** [comment]
So you aren't the first person to run into this @andresmgot, which makes me think we need to make the documentation clearer. So in order to use `--atomic`, you need to have `--wait`, which is why it automatically enables it. The reasoning behind this is you can't tell if the release has succeeded or failed unless you are getting signal from the things you installed. 

This is is actually how it worked in Helm 2 as well. If you have something like an invalid manifest, you shouldn't actually need any cleanup. Helm doesn't actually create the new "upgraded" release in storage until after validation is complete.

Does that make sense? Let me know if I need to clarify anything

**Comment by andresmgot** [comment]
Thanks for the reply and the reasoning!

> This is is actually how it worked in Helm 2 as well

You are right, I didn't notice because I was using a different approach (not using the `helm` cli code).

> If you have something like an invalid manifest, you shouldn't actually need any cleanup. Helm doesn't actually create the new "upgraded" release in storage until after validation is complete.

Well, the release is kept if the manifest is invalid, that's what I want to clean:

```
▶ helm install my-wp stable/wordpress --set image.pullPolicy=foo 
Error: Deployment.apps "my-wp-wordpress" is invalid: spec.template.spec.containers[0].imagePullPolicy: Unsupported value: "foo": supported values: "Always", "IfNotPresent", "Never"

▶ helm ls
NAME      	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART               	APP VERSION
my-wp     	default  	1       	2020-01-29 17:15:35.53203344 +0100 CET 	failed  	wordpress-8.1.2     	5.3.2      

▶ helm install my-wp stable/wordpress
Error: cannot re-use a name that is still in use
```

In any case, it's true that this is not an issue but a misunderstanding from my side so closing the issue.
