### ISSUE TITLE
Helm V2 - 'required' function in a local scope evaluates & prints true

### ISSUE THREAD

**Issue by trinityXmontoya** [helm/helm#7428]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:34:27Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.12", GitCommit:"a8b52209ee172232b6db7a6e0ce2adc77458829f", GitTreeState:"clean", BuildDate:"2019-10-15T12:04:30Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): N/A, locally

I used the [`required` function](https://v2.helm.sh/docs/charts_tips_and_tricks/#using-the-required-function) from within a `with` block. If I didn't provide the value it threw an error as expected. If I *did* provide the value, it evaluated to true, which gets included in the output. The docs don't specify it should only be declared in the global scope and it was reasonable to assume it would work in a local scope because you may have values that are only required based on another condition.

stripped example:
```yaml
{{- with .Values.favorite }}
{{ required "Value flavor is required!" .Values.flavor }}
drink: {{ .drink | default "tea" | quote }}
flavor: {{ .Values.flavor }}
{{- end }}
```
->
```
truedrink: "tea"
flavor: "green"
```

**Comment by hickeyma** [comment]
@trinityXmontoya This might be because within the `with` action, the variable scope changes. In your `with` action above, the scope is now set to `.Values.favorite`. This means that `.Values.flavor` is not inside of the restricted scope for `.`.  Refer to docs for more information: https://v2.helm.sh/docs/chart_template_guide/#modifying-scope-using-with

You could assign a variable outside of the action as follows: `{{- $flavor := .Values.flavor -}}`
and then reference it similar to the following: `flavor: {{ $flavor }}`

**Comment by trinityXmontoya** [comment]
I appreciate you taking the time but I think you misunderstood / did not look at my example. The issue is not with accessing variables & I understand the scope of “with” as laid out in the docs. The issue is that the “required” function when used within a scope evaluates & prints true. This is unexpected behavior & the docs give no indication it should only be used in the global scope.

**Comment by bridgetkromhout** [comment]
Thanks, @trinityXmontoya. As Helm v2 is moving out of support, and no longer recommended for use, we are not conducting further updates to its docs. Please migrate to Helm v3 for the best experience; thanks! https://helm.sh/blog/helm-v2-deprecation-timeline/
