### ISSUE TITLE
helm upgrade handles CrashLoopBackOff scenarios poorly

### ISSUE THREAD

**Issue by Bajix** [helm/helm#7429]
In the event of a CrashLoopBackOff scenario, helm upgrade simply hangs and either times out or in my case at least, a context deadline exceeded error will occur. It would be more useful for in this scenario to have helm upgrade to fail loudly and to output error logs.

**Comment by bridgetkromhout** [comment]
Hi, @Bajix and others interested - we now have a path forward for proposals. If you're reading this and thinking "but this should happen!", please file a [Helm Improvement Proposal](https://github.com/helm/community/blob/master/hips/hip-0001.md) to discuss it with the community (or send a pull request if you'd like to implement it). Meanwhile, I'm closing this issue as inactive.
