### ISSUE TITLE
[Question] How to access helm programatically

### ISSUE THREAD

**Issue by adamgajzlerowicz** [helm/helm#7433]
Is there a way to access deployed Helm charts programmatically?

I'd like to make web interface which will allow manual chart manipulation.

I found pyhelm but it supports only Helm 2. I looked on npm, but nothing there. I wrote a bash script but if I try to use it's output I get just a string really so it's not really useful.

Are there any packages for any of the languages I can use please?

Thanks!

**Comment by bacongobbler** [comment]
https://pkg.go.dev/helm.sh/helm/v3

**Comment by adamgajzlerowicz** [comment]
I will have a look - Thank you!

**Comment by adamgajzlerowicz** [comment]
@bacongobbler 
I never used go lang before and I am trying to load the module from the link above.

I tried number of variations of `go get xxxx` and nothing installed any usefull module. Can you please give me some pointers on what to install specifically?

Many thanks!

**Comment by stefanprodan** [comment]
@adamgajzlerowicz here is how Helm Operator uses helm v2/v3 as packages: https://github.com/fluxcd/helm-operator/blob/master/go.mod

**Comment by bacongobbler** [comment]
Thanks @stefanprodan for the pointers. There are a few issues with certain packages. The Go community is still trying to migrate over to Go modules, which has been a pain for some time. #6862 should help alleviate some of those pains, but it's best to look at Helm's `go.mod` file to pick up on any `replace` statements you may need to inject into your go.mod.

Hope this helps.
