### ISSUE TITLE
CRD's in helm

### ISSUE THREAD

**Issue by eilonk** [helm/helm#7437]
Greetings,
I'm trying to create a helm configuration for kong, and I'm having trouble understanding some values concept-wise.
If kong comes with CRD's built in (Kong Ingress,plugin, consumer and credential) - where do these fit inside the value file?
I can't seem to find any example for configuring these resources through this type of file (only shorter examples)
for context, i am using the files supplied by kong and am obviously missing something..
would love to see an example and understand it better.
Thanks in advance for any help!

**Comment by hickeyma** [comment]
@eilonk It might be worth asking in Kong about the chart(s) you are having issues with: https://github.com/kong/charts

**Comment by eilonk** [comment]
i accidently opened it here, thanks :)
