### ISSUE TITLE
Allow recursion in templates

### ISSUE THREAD

**Issue by petr-buchin** [helm/helm#7439]
PR https://github.com/helm/helm/pull/7114 made a BC-breaking change by closing the possibility to use recursion in templates. We use a lot of recursion in our templates, and having this PR backported to Helm v2, we are not able to update neither to the newest minor version of Helm v2, nor to Helm v3.

Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:02:12Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS EKS / Docker for Mac

**Comment by zwwhdls** [comment]
I will fix this case soon. Sorry for the trouble because of that pr.

**Comment by petr-buchin** [comment]
@zwwhdls thank you very much!
