### ISSUE TITLE
Cannot update a service's labels with Helm v3

### ISSUE THREAD

**Issue by mikemowgli** [helm/helm#7444]
Whenever a basic chart is deployed, an object of kind Service with type ClusterIP is created. As the spec.clusterIP is not defined, Kubernetes assigns an IP to this service. Now, if the service's labels or annotations are update, and helm upgrade is run, Helm 3-way merge patch strategy will try to replace the existing clusterIP with an empty string. As this is an immuatable field, the upgrade fails.

```
helm upgrade --install --wait --force --atomic chart1 test-chart
Error: UPGRADE FAILED: an error occurred while rolling back the release. original upgrade error: failed to replace object: Service "chart1-test-chart" is invalid: spec.clusterIP: Invalid value: "": field is immutable: failed to replace object: Service "chart1-test-ingress-chart" is invalid: spec.clusterIP: Invalid value: "": field is immutable
```

This bug was noticed for the Service's spec.clusterIP field, but the same behavior would happen for any immutable field that the Kubernetes controller filled itself.

Please advice on the recommended approach.

Output of `helm version`: 3.0.2
Output of `kubectl version`: 1.11
Cloud Provider/Platform (AKS, GKE, Minikube etc.):  OpenShift

**Comment by bacongobbler** [comment]
have you had a chance to look at https://github.com/helm/helm/issues/6378, specifically https://github.com/helm/helm/issues/6378#issuecomment-557746499?

**Comment by bacongobbler** [comment]
I just noticed you include the `--force` flag in your example. That will bypass the three-way merge patch strategy altogether. It is akin to `kubectl replace`, which will also result in the same error.

**Comment by mikemowgli** [comment]
> have you had a chance to look at #6378, specifically [#6378 (comment)](https://github.com/helm/helm/issues/6378#issuecomment-557746499)?

Yes, but this is not a solution. And I tested all possible combinations from that comment.
What is the proper solution though is to drop the '--force' flag.

Thank you!
