### ISSUE TITLE
In Helm 3 'repo add' does not pass username.  Results in 401 Unauthorized.

### ISSUE THREAD

**Issue by rextca** [helm/helm#7445]
Doing 'helm repo add [name] [url] --username admin'
The username is not passed to the repo server and as a result the server returns '401 Unauthorized.  This worked in Helm v2.14.3.

Output of `helm version`:
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-10T03:03:57Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  None

Attempting to add a Nexus 3 repository with command above, Nexus logged this incoming request:
Request: Request{action='GET', path='/index.yaml', parameters={}, payload=HttpRequestPayloadAdapter{contentType='null', size=-1}, multipart=false}
Request headers:
  User-Agent: Helm/3.0.2
  Host: xxx.eastus.cloudapp.azure.com
  Accept-Encoding: gzip
Request attributes: ...etc...

Nexus rejects the request as 401 Unauthorized. Harbor also rejects such requests.

Using Helm 2, the request was logged:
Request: Request{action='GET', path='/index.yaml', parameters={}, payload=HttpRequestPayloadAdapter{contentType='null', size=-1}, multipart=false}
Request headers:
  User-Agent: Helm/2.14.3
  Host: xxx.eastus.cloudapp.azure.com
  ****Authorization: Basic YWRtaW46YWRtaW4hMTIzNA==****
Request attributes: ...etc...

...and was successful.

**Comment by mattfarina** [comment]
Before I try looking further for a bug I have a question and a comment.

Are you using either a `http` or `https` scheme or is it another url scheme?

The code for `http` and `https` that uses basic auth requires both a username and a password in both Helm [v2](https://github.com/helm/helm/blob/63e1c9bc7f6a88efe40f5badcc0766e6748283c9/pkg/getter/httpgetter.go#L59-L61) and [v3](https://github.com/helm/helm/blob/5e3c7d7eb86a9fe6aad9174434415b9c42e78478/pkg/getter/httpgetter.go#L58-L60). Are you providing both a username and password?

**Comment by rextca** [comment]
Matt,
Thanks for looking at this.  I'm using an https URL.  

It doesn't matter if I specify the password in the command.  In Helm 2 if I put the username but not the password in the command, it prompts me for the password and after I enter it, it adds the repo.  In Helm 3, I specify the username in the command, but whether I include the password in the command or not, it fails immediately (doesn't prompt).

Rex

**Comment by cedricarnoult** [comment]
I have the exact same issue, using helm 3.1.0.

**Comment by Amit-Thawait** [comment]
@rextca @cedricarnoult 
Have you guys tried the command with --password option. The below command works for me.

    helm repo add <my-repo-name> http://my-repo-url --username <myusername> --password <mypassword>

**Comment by rextca** [comment]
Hi Amit-Thawait.  I tried it both with and without the --password flag.  It fails either way.  

What version of Helm are you using when it works?

Rex

**Comment by Amit-Thawait** [comment]
@rextca I am using Helm 3.1.0 and Harbor 1.3.0

**Comment by catchups** [comment]
I have a separate proxy server and manage it. Separate authorizations are possible if all authentication is handled by the proxy server.

**Comment by rextca** [comment]
I just tried this on Helm 3.1.2 and it works, so I'm closing the issue.
