### ISSUE TITLE
Exception thrown when nesting > 4 levels in command line values

### ISSUE THREAD

**Issue by v-lealli** [helm/helm#7446]
Output of `helm version`:  
**version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}**

Output of `kubectl version`:
**Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:02:12Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}**

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
**Docker Desktop Community**

Hi, I found that using more than 4 levels of nesting in command line values is making Helm fail and raise an error. You can reproduce de scenario by doing this:

1. Create a basic Chart.yaml file with some data like the following
```
apiVersion: v2
appVersion: "1.0"
description: Helm Lvl5 Test
name: helm-lvl5-test
version: 0.1.0
```
2. Create a values.yaml file and leave it empty

3. Create a test.yaml file in ./templates/ folder with the following content
```
apiVersion: v1
data:
  configmapvalue: {{ .Values.lvl1.lvl2.lvl3.lvl4.lvl5 | quote }}
kind: ConfigMap
metadata:
  name: {{ .Values.lvl1.lvl2.lvl3.lvl4 | quote }}
```

4. Run the following command
`helm template lvltest . --set lvl1.lvl2.lvl3.lvl4="value4lvls" --set lvl1.lvl2.lvl3.lvl4.lvl5="value5lvls"`

5. As a result I get the following message
```
panic: interface conversion: interface {} is string, not map[string]interface {}

goroutine 1 [running]:
helm.sh/helm/v3/pkg/strvals.(*parser).key(0xc0000057c0, 0xc00054a7b0, 0xc0006ff508, 0x4)
        /home/circleci/helm.sh/helm/pkg/strvals/parser.go:211 +0xdf1
helm.sh/helm/v3/pkg/strvals.(*parser).key(0xc0000057c0, 0xc00054a750, 0xc0006ff6a8, 0x4)
        /home/circleci/helm.sh/helm/pkg/strvals/parser.go:215 +0x1b4
helm.sh/helm/v3/pkg/strvals.(*parser).key(0xc0000057c0, 0xc00054a6f0, 0xc0006ff848, 0x4)
        /home/circleci/helm.sh/helm/pkg/strvals/parser.go:215 +0x1b4
helm.sh/helm/v3/pkg/strvals.(*parser).key(0xc0000057c0, 0xc00054a660, 0x153ef64, 0x17d60a0)
        /home/circleci/helm.sh/helm/pkg/strvals/parser.go:215 +0x1b4
helm.sh/helm/v3/pkg/strvals.(*parser).parse(0xc0000057c0, 0xc00054a660, 0x0)
        /home/circleci/helm.sh/helm/pkg/strvals/parser.go:133 +0x3f
helm.sh/helm/v3/pkg/strvals.ParseInto(0xc000036360, 0x23, 0xc00054a660, 0x0, 0x0)
        /home/circleci/helm.sh/helm/pkg/strvals/parser.go:70 +0xc5
helm.sh/helm/v3/pkg/cli/values.(*Options).MergeValues(0xc0000f85a0, 0xc000005700, 0x1, 0x1, 0x0, 0x0, 0x0)
        /home/circleci/helm.sh/helm/pkg/cli/values/options.go:62 +0x232
main.runInstall(0xc0006dc360, 0x2, 0x6, 0xc000176ea0, 0xc0000f85a0, 0x1b7eca0, 0xc000006018, 0xc0006a0230, 0x31, 0x30)
        /home/circleci/helm.sh/helm/cmd/helm/install.go:168 +0x338
main.newTemplateCmd.func1(0xc000624000, 0xc0006dc360, 0x2, 0x6, 0x0, 0x0)
        /home/circleci/helm.sh/helm/cmd/helm/template.go:63 +0x11e
github.com/spf13/cobra.(*Command).execute(0xc000624000, 0xc0006dc2a0, 0x6, 0x6, 0xc000624000, 0xc0006dc2a0)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x467
github.com/spf13/cobra.(*Command).ExecuteC(0xc0004b8000, 0x1bbc1e0, 0xc0000e0420, 0x1925a70)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x302
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:75 +0x20b
```

6. Now remove the dot in "lvl4.lvl5" to make it look like this "lvl4lvl5", both in the file test.yaml and in the command, and run it again. The result is now this.
```
---
# Source: helm-lvl5-test/templates/test.yaml
apiVersion: v1
data:
  configmapvalue: "value5lvls"
kind: ConfigMap
metadata:
  name: "value4lvls"
```

Is this a bug or is there a limit for nesting levels in the values coming from the command line arguments?
Also, if the problem is the nesting, then the error message could be changed to better reflect this.

Thanks.

**Comment by mattfarina** [comment]
I have confirmed this on the tip of master.

**Comment by anshulvermapatel** [comment]
@v-lealli , this does not seems to be a level issue.

>$ ls -R chart 
chart:
Chart.yaml  templates  values.yaml
chart/templates:
test.yaml

>$ helm version
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

>\$ helm template lvltest ./chart --set lvl1.lvl2.lvl3.lvl4.lvl5="value4lvls"
\---
\# Source: helm-lvl5-test/templates/test.yaml
apiVersion: v1
data:
  configmapvalue: "value4lvls"
kind: ConfigMap
metadata:
  name: "map[lvl5:value4lvls]"

As you can see above I used 5 levels, still it did not throw the error.

But when I execute 
`$ helm template lvltest ./chart --set lvl1.lvl2.lvl3.lvl4="value4lvls" --set lvl1.lvl2.lvl3.lvl4.lvl5="value5lvls"`

The error message is coming from 

> https://github.com/helm/helm/blob/master/pkg/strvals/parser.go#L212-L217

To me this seems to be because, value of `lvl1.lvl2.lvl3.lvl4` is `"value4lvls"` and `lvl1.lvl2.lvl3.lvl4` whose value is a string, would be treated as its value is map[string]interface{} and `lvl1.lvl2.lvl3.lvl4` which is a string is being tried to put into a variable of type map[string]interface{} there this error comes.

To me this should not be a bug, but we can handle this panic and give a proper error message.
Since I am a noob I may be wrong, but if anyone gives some pointer on this, I would really appreciate.

**Comment by v-lealli** [comment]
I think you are right, the YAML equivalent to those values paths wouldn't be well formed:

```
lvl1:
  lvl2:
    lvl3:
      lvl4: "value4lvls"
        lvl5: "value5lvls"
```

**Comment by bacongobbler** [comment]
Is there something we need to address in the code, or can we close this? It's unclear what is the requested action item for this ticket. Thanks!

**Comment by v-lealli** [comment]
@bacongobbler, the main issue which was the levels of nesting for values in the command line is not a bug, there's nothing to address there now except for the panic, you can add logic to provide a proper error message or leave as it is and close this, that's up to you I guess.

Thanks

**Comment by anshulvermapatel** [comment]
@bacongobbler  , Can I work on this, to just handle the panic and provide a proper error message rather than just giving the panic.

**Comment by technosophos** [comment]
@anshulvermapatel any progress on this?

**Comment by NickMetz** [comment]
Same issue happens to me when accidentally values.yaml and cmd line arg --set use same levels and mismatch types

**Comment by technosophos** [comment]
Feel free to contribute a patch that traps the panic and returns a proper error. I don't think anyone is working on it.

**Comment by bacongobbler** [comment]
closing as stale.
