### ISSUE TITLE
what is {{ tpl . $ }} in template file?

### ISSUE THREAD

**Issue by zffocussss** [helm/helm#7448]
Hi:
   I want to know,what is the meaning of {{ tpl . $ }}.
what is $ used for?

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.15.2", GitCommit:"8dce272473e5f2a7bf58ce79bb5c3691db54c96b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.2", GitCommit:"8dce272473e5f2a7bf58ce79bb5c3691db54c96b", GitTreeState:"clean"}
```

Output of `kubectl version`:
v1.14.8

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS

**Comment by bacongobbler** [comment]
It isn’t explained very well in Go’s documentation, but `$` is a variable that refers to the “root” of the dot (`.`) variable. It’s used commonly to pass the entire context available from the rendering engine to the template.

Does that make sense?

https://golang.org/pkg/text/template/#hdr-Arguments

**Comment by technosophos** [comment]
Closing as resolved
