### ISSUE TITLE
Bad Keybase key by technosophos

### ISSUE THREAD

**Issue by SamyCoenen** [helm/helm#7450]
```
Downloading: https://keybase.io/technosophos/pgp_keys.asc?fingerprint=aba2529598f6626c420d335b62f49e747d911b60.asc
gpg: directory '/root/.gnupg' created
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: key 62F49E747D911B60: 9 signatures not checked due to missing keys
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: bad data signature from key 1970FFF1FA7792DA: Wrong key usage (0x19, 0x2)
gpg: key 62F49E747D911B60: public key "Matt Butcher <matt.butcher@microsoft.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no ultimately trusted keys found
gpg: no valid OpenPGP data found.
gpg: verify signatures failed: Unexpected error
```

**Comment by hickeyma** [comment]
@technosophos Do you mind looking at this?

**Comment by technosophos** [comment]
Yes. I will check.

**Comment by mattfarina** [comment]
@SamyCoenen I have been unable to reproduce this. Can you share the OS, tools (including versions), and commands you are running.

**Comment by SamyCoenen** [comment]
@mattfarina 

I have been testing this while building a container image, underneath you can find the Dockerfile.

I tried it with both https://keybase.io/technosophos/pgp_keys.asc?fingerprint=aba2529598f6626c420d335b62f49e747d911b60.asc and https://keybase.io/technosophos/pgp_keys.asc

Inside the image, the gpg version is:

> gpg (GnuPG) 2.2.9
> libgcrypt 1.8.3

```
FROM registry.access.redhat.com/ubi8/ubi-minimal:8.0-213 as build

ARG HELM_VERSION=3.0.2
ARG HELM_DOWNLOAD_HOST='https://get.helm.sh'
ARG HELM_PGP_KEY_HOST='https://keybase.io' 
ARG REPO_HOST='https://github.com/repository/github.com/'

WORKDIR /tmp

RUN microdnf -y install --nodocs wget tar gzip

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN export HELM_TAR_FILENAME="helm-v${HELM_VERSION}-linux-amd64.tar.gz" && \
    export HELM_TAR_URL="${HELM_DOWNLOAD_HOST}/${HELM_TAR_FILENAME}" && \
    export HELM_TAR_CHECKSUM_FILENAME="${HELM_TAR_FILENAME}.sha256" && \
    export HELM_TAR_CHECKSUM_URL="${HELM_DOWNLOAD_HOST}/${HELM_TAR_CHECKSUM_FILENAME}" && \
    export REPO_RELEASE_PATH="helm/helm/releases/download/v${HELM_VERSION}" && \
    export HELM_PGP_KEY_FILENAME='pgp_keys.asc' && \
    export HELM_TAR_CHECKSUM_KEY_URL="${REPO_HOST}/${REPO_RELEASE_PATH}/${HELM_TAR_FILENAME}.asc" && \
    export HELM_TAR_KEY_URL="${REPO_HOST}/${REPO_RELEASE_PATH}/${HELM_TAR_CHECKSUM_FILENAME}.asc" && \
    echo "Downloading: ${HELM_TAR_URL}" && wget -q "${HELM_TAR_URL}" && \
    echo "Downloading: ${HELM_TAR_CHECKSUM_URL}" && wget -q "${HELM_TAR_CHECKSUM_URL}" && \
    # TODO https://github.com/helm/helm/issues/7450
    echo "Downloading: ${HELM_PGP_KEY_HOST}/technosophos/${HELM_PGP_KEY_FILENAME}" && wget -q "${HELM_PGP_KEY_HOST}/technosophos/${HELM_PGP_KEY_FILENAME}" && \
    # echo "Downloading: ${HELM_TAR_CHECKSUM_KEY_URL}" && wget -q "${HELM_TAR_CHECKSUM_KEY_URL}" && \
    # echo "Downloading: ${HELM_TAR_KEY_URL}" && wget "${HELM_TAR_KEY_URL}" && \
    gpg --version && gpg --import "${HELM_PGP_KEY_FILENAME}"
```

You can execute this by creating a Dockerfile with the content from above and then building an image.

For example:
`podman build -t helm .`

**Comment by mattfarina** [comment]
I've discovered a couple things...

1. When I use `ubuntu` instead of `registry.access.redhat.com/ubi8/ubi-minimal:8.0-213` as the base image (I do need to use apt to install gpg and wget) the line `bad data signature from key 1970FFF1FA7792DA: Wrong key usage (0x19, 0x2)` goes away.
2. I can't get the error in ubuntu (I have a workstation) or a Mac
3. Inside the container there is no gpg-agent running by default. You can either bind to one on the parent OS or run with in the container with a command like `gpg-agent --daemon && \`. When I do this I can use `gpg -k` after importing the cert in both the Dockerfile here and the one I made with ubuntu and see the imported key.

I think #3 might be the problem with the container. Does this help?

**Comment by SamyCoenen** [comment]
When using the ubuntu image instead of ubi, you can also notice that there are differences in versions, ubuntu is running behind in this aspect.

> gpg (GnuPG) 2.2.4
> libgcrypt 1.8.1

with both images, when doing `gpg -k` to list the keys, they both work without needing a gpg-agent daemon for me?

Using ubuntu importing the keys does work and verifying the signature does also, but you can expect ubuntu to upgrade their libraries as well in the future so this issue will come up again.

I've also used ubi with other binaries and signatures like terraform and packer and those worked without issues.

**Comment by SamyCoenen** [comment]
upgrading to 2.2.9 on ubuntu or Mac will result in having the same error, more information can be found here https://superuser.com/questions/1344523/how-to-resolve-the-error-gpg-bad-data-signature-from-key-wrong-key-usage-0x1 @mattfarina

**Comment by mattfarina** [comment]
Using gnupg 2.2.10 and importing @technosophos key I get the following message...

```
± gpg --import pgp_keys.asc
gpg: bad data signature from key 0x21DD8DC880EBB474: Wrong key usage (0x19, 0x2)
gpg: bad data signature from key 0x21DD8DC880EBB474: Wrong key usage (0x19, 0x2)
gpg: bad data signature from key 0x21DD8DC880EBB474: Wrong key usage (0x19, 0x2)
gpg: bad data signature from key 0x1970FFF1FA7792DA: Wrong key usage (0x19, 0x2)
gpg: key 0x62F49E747D911B60: public key "Matt Butcher <matt.butcher@microsoft.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: bad data signature from key 0x21DD8DC880EBB474: Wrong key usage (0x19, 0x2)
gpg: bad data signature from key 0xE8D304D0483E4CC0: Wrong key usage (0x19, 0x2)
gpg: bad data signature from key 0xF5D07DC2E8C0065A: Wrong key usage (0x19, 0x2)
gpg: bad data signature from key 0xEC3803FD748579E4: Wrong key usage (0x19, 0x2)
gpg: bad data signature from key 0xC0997882C5611D4D: Wrong key usage (0x19, 0x2)
gpg: bad data signature from key 0x5065DCBA074351EA: Wrong key usage (0x19, 0x2)
gpg: bad data signature from key 0xC24FC619B0262003: Wrong key usage (0x19, 0x2)
gpg: bad data signature from key 0xEF92630B07171AA9: Wrong key usage (0x19, 0x2)
gpg: bad data signature from key 0x118A552924F2FF1F: Wrong key usage (0x19, 0x2)
gpg: bad data signature from key 0x2E0205895C66444E: Wrong key usage (0x19, 0x2)
gpg: bad data signature from key 0x1970FFF1FA7792DA: Wrong key usage (0x19, 0x2)
gpg: depth: 0  valid:   1  signed:   1  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: bad data signature from key 0x21DD8DC880EBB474: Wrong key usage (0x19, 0x2)
gpg: bad data signature from key 0xE8D304D0483E4CC0: Wrong key usage (0x19, 0x2)
gpg: bad data signature from key 0xF5D07DC2E8C0065A: Wrong key usage (0x19, 0x2)
gpg: bad data signature from key 0xEC3803FD748579E4: Wrong key usage (0x19, 0x2)
gpg: bad data signature from key 0xC0997882C5611D4D: Wrong key usage (0x19, 0x2)
gpg: bad data signature from key 0x5065DCBA074351EA: Wrong key usage (0x19, 0x2)
gpg: bad data signature from key 0xC24FC619B0262003: Wrong key usage (0x19, 0x2)
gpg: bad data signature from key 0xEF92630B07171AA9: Wrong key usage (0x19, 0x2)
gpg: bad data signature from key 0x118A552924F2FF1F: Wrong key usage (0x19, 0x2)
gpg: bad data signature from key 0x2E0205895C66444E: Wrong key usage (0x19, 0x2)
gpg: depth: 1  valid:   1  signed:   0  trust: 1-, 0q, 0n, 0m, 0f, 0u
```

Prior to deleting and re-importing I would get the following next to @technosophos key when I listed the keys...
```
gpg: bad data signature from key 0x5065DCBA074351EA: Wrong key usage (0x19, 0x2)
```

The superuser link @SamyCoenen shared may hold an answer. Thanks.

**Comment by technosophos** [comment]
The tl;dr is that GnuPG decided that one of the fields on my key is not valid, though the spec does not require or suggest erroring out on that field. So I needed to generate new signing keys for my Helm package signatures.

**Comment by SamyCoenen** [comment]
@technosophos I can confirm that v3.0.2 works now with signatures!

```sh
Primary key fingerprint: ABA2 5295 98F6 626C 420D  335B 62F4 9E74 7D91 1B60
     Subkey fingerprint: FB2B A64C F4ED 0684 9245  DFE3 DCD5 F5E5 EF32 C345
helm-v3.0.2-linux-amd64.tar.gz: OK

```
Updating the version to anything above that doesn't work unfortunately but maybe they haven't been signed with the valid key?

**Comment by bacongobbler** [comment]
3.1.0, 3.1.1 and 3.1.2 were all signed by another core maintainer, so it’d make sense the signature verification would fail unless you added the other maintainer’s key.

Is this good to close, or is there something else?

**Comment by SamyCoenen** [comment]
@bacongobbler indeed, changing the signing key to https://keybase.io/mattfarina works with the new releases, thanks!

```shell
Primary key fingerprint: 672C 657B E06B 4B30 969C  4A57 4614 49C2 5E36 B98E
     Subkey fingerprint: 711F 28D5 10E1 E0BC BD5F  6BFE 9436 E80B FBA4 6909
helm-v3.1.2-linux-amd64.tar.gz: OK
```
