### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by gusennan** [helm/helm#7454]
The "Next Steps" page:

https://helm.sh/docs/chart_template_guide/wrapping_up/

has numerous broken links. For example, the "Helm Chart Guide" and "Chart Hooks Guide" are broken.

**Comment by mattfarina** [comment]
Thanks for filing the issue. These are docs bugs that are now on the website repo. I filed an issue there to point back to this at https://github.com/helm/helm-www/issues/473

**Comment by bridgetkromhout** [comment]
Thanks for this report, @gusennan! @flynnduism has resolved the issue @mattfarina filed in the docs repo, and the links are now corrected on the website.
