### ISSUE TITLE
Helm dep build does not download remote dependencies within a local dependency in a umbrella chart

### ISSUE THREAD

**Issue by agill17** [helm/helm#7456]
I have an umbrella chart with dependencies. Most of the dependencies are remote and few are local ( so they are being fetched from `helm-charts` directory ). 
The local dependency has a remote dependency within.
So when I run `helm dep build <myUmbrellaChart>`, I see all the umbrella dependencies ( including the local one ) inside the charts directory.

However when I extract the local dependency tarball file from within charts directory to see if the nested remote dependency got downloaded, I do not see the nested remote dependency, therefore the local dependency chart fails to install.

Output of `helm version`:
```version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:02:12Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS ( kops )

**Comment by richardwhiuk** [comment]
Basically, `helm dep build` doesn't act recursively, even across local dependencies.
