### ISSUE TITLE
how to get value from online helm repo

### ISSUE THREAD

**Issue by Hokwang** [helm/helm#7457]
Hello.

I want to know some default value of helm chart.

For example, I want to know .Values.master.tag of stable/jenkins. Is there a way to get this?

For now, I think that I do `helm pull stable/jenkins` and then unzip tar and find out from values.yaml file.

Thanks,

**Comment by hickeyma** [comment]
@Hokwang  This is a good way to do it or else read the documentation for the chart.

**Comment by hickeyma** [comment]
Closing as question is answered.

**Comment by Hokwang** [comment]
Please do not close.
If there's no easy way for this. I will edit this to proposal.
/reopen

**Comment by hickeyma** [comment]
ok, re-opening

**Comment by bacongobbler** [comment]
Have you looked at `helm get values` for this use case?

**Comment by Hokwang** [comment]
yeah, `helm get values` command can get values from installed release.

@hickeyma 
Why I think this feature needed is that 
I do continuous integration, so many commits are compiled and run docker build when it succeed,
so now I have lots of tag in docker registry.

I need to remove/retain unuseful or short-live tags, I think that is, not specified tag in whole version of helm chart.

so if I have 10 versions of helm chart, and each version has specific image tag,
I can remove docker image tags without that.

How do you think about my thought (this way), I wonder how other company make a deal with this problem.

**Comment by bacongobbler** [comment]
Oh, right. Apologies. I meant `helm show values`.

**Comment by Hokwang** [comment]
@bacongobbler OMG, that's it! Many thanks!! I will close this.
