### ISSUE TITLE
helm 3: render error with (tpl .Files.Glob().AsConfig .) 

### ISSUE THREAD

**Issue by corollo** [helm/helm#7459]
Hi, I have problem rendering configuration file using tpl function.

Here, the configuration of my chart (here the [repo](https://github.com/corollo/render-error-with-tpl) on github)

templates/configmap.yaml
==================
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-example  
data:
{{ ( tpl (.Files.Glob "confs/*").AsConfig . ) | indent 2 }}
```

values.yaml
==================
```
hosts:
  gateway: test-host.com
```

confs/carbon.xml
==================
[carbon.xml](https://github.com/corollo/render-error-with-tpl/blob/master/confs/carbon.xml)

When i try to execute the rendering of the chart (for ex: helm template .) i get this error:
```
Error: template: render-error-with-tpl/templates/configmap.yaml:6:5: executing "render-error-with-tpl/templates/configmap.yaml" at <tpl (.Files.Glob "confs/*").AsConfig .>: error calling tpl: error during tpl function execution for "carbon.xml: \"<?xml version=\\\"1.0\\\" encoding=\\\"UTF-8\\\"?>\\n<!--\\n Copyright ... 
...</APIManagement>\\n</Server>\\n\"": parse error at (render-error-with-tpl/templates/configmap.yaml:17): unclosed action
```

Thanks.
L.

Output of `helm version`:
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
On-premise

**Comment by bacongobbler** [comment]
Looking at common Go error codes, this looks as though the template is not rendering correctly, causing the text/template engine to render incorrectly.

Please use the suggested example in the documentation, under "Accessing Files Inside Templates": https://helm.sh/docs/chart_template_guide/accessing_files/#configmap-and-secrets-utility-functions

Here is the sample code, modified to fit your example:

```
{{ (.Files.Glob "confs/*").AsConfig | indent 2 }}
```

Using your example and changing line 6 in your configmap, I was able to render the chart as expected.

Hope this helps.

**Comment by corollo** [comment]
Hello,
  Thank you very much for your reply.
 
Sorry, maybe I didn't explain myself well, my intent is to use the external file (confs/carbon.xml) as a template.

Inside the file there are some placeholders (ex: <HostName> {{.Values.hosts.gateway}} </HostName>) that i want to replace with the correct value.

Does the {{tpl ...}} function not serve this purpose?

If I eliminate the call to tpl, the result obtained is not the desired one

$ helm template. | grep ".Values.hosts.gateway"
    \ services deployed on this server instance. \ n -> \ n <HostName> {{.Values.hosts.gateway
    \ -> \ n <MgtHostName> {{.Values.hosts.gateway}} </MgtHostName> \ n <! - \ n The

I can't understand why in some external files I can insert variables while in others I get the error reported...

How could I investigate the problem?

Thank you very much for your time,
Luigi.

**Comment by corollo** [comment]
mmm  i replace the space in the external file:
 

`{{ .Values.hosts.gateway }}  -to-> {{.Values.hosts.gateway}}`

And it works!

`$ helm template . | grep "MgtHostName"
    \ \n  <MgtHostName>test-host.com</MgtHostName>\n
`

I don't understand...

**Comment by bacongobbler** [comment]
Looks like you're using it correctly as per https://helm.sh/docs/howto/charts_tips_and_tricks/#using-the-tpl-function. I'd investigate further why Go would complain there's an unclosed action in the template. Characters like `$` may need to be escaped for the file to pass through the template engine correctly.

https://golang.org/pkg/text/template/
