### ISSUE TITLE
Offer to add build command feature

### ISSUE THREAD

**Issue by AlexPaskhin** [helm/helm#7460]
I have just recently come with solution that improves e Helm CI Kubernetes production deployment process.
I found the well engineering Helm has a small gap. You always need kubectl to be involved.
There is absence of the **build** feature for air gapped environments and build systems. 
It is not possible to build from chart templates deployment files, verify and test them, then sing and form a package and deploy it into production.
I'd got the latest master branch and found out that it was possible to implement new "build" feature.
I did it locally and it works fine for me.

 Use:"build [NAME][CHART][--output-dir BASE-DIR]"

I guess, is it would be interested for a team to add this feature in a future releases?
If it is Ok. I can add test cases then and I will be ready to support issues regarding this feature. But, I have a spare time at weekends only.
I cannot find the way how to do so over the web.
I don't have repo branch or membership or some like that, or access.
Let me know.

**Comment by marckhouzam** [comment]
Could you describe what the proposed `build` command would do specifically?

Helm has the `template` command which will generate the final yaml files, or the `package` command which will create an archive from the chart.

Do these address your needs?

**Comment by AlexPaskhin** [comment]
Command "template" has addressed needs , but only only 95%. 
The "values.yaml", that has been used for template's rendering, is not presented.
It will be nice to have it for review verification process.
In any case Thanks.
