### ISSUE TITLE
helm 3.0.2 dependency update builds requirements.lock instead of Chart.lock file

### ISSUE THREAD

**Issue by azizea** [helm/helm#7464]
Output of `helm version`: version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-15T15:50:38Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

Recently upgraded to helm 3.0.2 from 3.0.1, 3.0.1 was generating `Chart.lock` file, now with helm 3.0.2 `helm dependency update ... ` builds `requirements.lock `file and not Chart.lock file

Steps to reproduce with helm 3.0.2 :

1. Remove chart.lock file if you have, in case if you have requirements.lock file remove that too
2. Execute: $`helm dependency update ...`

Results in creating requirement.lock file instead of Chart.lock file

**Comment by hickeyma** [comment]
@azizea The chart that your are performing a `dep update`, does it have a `requirements.yaml` file in it?

This might be relate to issues fixed in https://github.com/helm/helm/pull/7009.

**Comment by technosophos** [comment]
What is the chart version in Chart.yaml? Is it v1, v2, or not set?

**Comment by bridgetkromhout** [comment]
Hi, @azizea - as mentioned above, we think this issue may be resolved. If it recurs, please let us know which version of helm and which chart version you're using. Thanks.
