### ISSUE TITLE
Helm 3.0.2 on alpine does break the binary (or c or whatever)

### ISSUE THREAD

**Issue by buehler** [helm/helm#7469]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

Output of `kubectl version`:
does not matter.

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
does not matter.

When one creates a docker image based on alpine:3.9. Then uses the get helm script to actually install helm locally in that image, the command `helm dep build` will break _something_ that hard, that the binary just returns an exit code 1 and all further calls to the helm binary just don't do anything. You can event call things like `helm lol` and there is nothing going on.

To reproduce, build a dockerfile like this:

```Dockerfile
FROM alpine:3.9

RUN apk update && \
    apk add curl bash openssl && \
    curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
```

In this image, take a chart and try `helm dep build`.

After this is done, the helm binary is screwed.

When using the `alpine/helm` image, the error is not occuring. So my guess is, that something in the get helm script is not quite right with alpine distributions.

Regards

**Comment by mattfarina** [comment]
@buehler I followed the directions here and was unable to reproduce the problem. Can you please provide some more detail such as the chart you used and the commands you ran.

**Comment by buehler** [comment]
Hey @mattfarina hmmm... I can't reproduce it as well. There were some special conditions maybe.
Since it did not happen again, I guess we can close this issue. If it happens again, I'll reopen the issue.

Thank you anyway!
