### ISSUE TITLE
Helm release stuck with status "pending-upgrade"

### ISSUE THREAD

**Issue by slashr** [helm/helm#7476]
Output of `helm version`:
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:29Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:02:12Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS

I had installed [Prometheus Operator](https://github.com/helm/charts/tree/master/stable/prometheus-operator) around a month ago. 

* `helm list --all-namespaces -a`
> NAME       NAMESPACE       REVISION       UPDATED       STATUS       CHART       APP VERSION

> spw-test       monitoring       27       2019-12-20 07:24:19.770034 +0100 CET       pending-upgrade       prometheus-operator-8.1.8       0.34.0

The status is stuck on `pending-upgrade and I can't seem to do anything about this. 

---
* `helm upgrade test . --namespace monitoring`
> Error: UPGRADE FAILED: "spw-test" has no deployed releases

---

* `helm list`
> NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART	APP VERSION

---
* `helm delete spw-test`
> Error: uninstall: Release not loaded: spw-test: release: not found

---
* `helm install spw-test . -n monitoring`
> Error: cannot re-use a name that is still in use

I'd like to either get rid of this release and create a new one. Or somehow fix this so that I can do `helm upgrade` on the release

**Comment by bacongobbler** [comment]
Have you tried `helm delete -n monitoring spw-test`? It looks like you forgot to add the namespace parameter to the `helm delete` example.

**Comment by bacongobbler** [comment]
As for the release being stuck in "pending upgrade", we've seen that occur when the connection times out mid-upgrade or mid-rollback. I believe others have worked around this by manually marking the release as DEPLOYED, usually by editing the secret Helm creates to track the release ledger.

**Comment by slashr** [comment]
@bacongobbler 

Thank you. Still finding it hard to believe that I did not enter the namespace.

**Comment by gitumarkk** [comment]
This also happened to me because my help upgrade process was interrupted. After some trial and error, a helm rollback restored my helm state i.e.  `helm rollback <name> <revision>` hope it helps anyone in the same situation.

**Comment by tamasbege** [comment]
I stumbled upon an older thread with the same issue... Apparently it is more common...
https://github.com/helm/helm/issues/4558

**Comment by kitos9112** [comment]
Yet another one who stumbles upon this issue! During a helm upgrade from a CD system there could be a multitude of events that might end up interrupting the upgrade process. A manual rollback should be a no-go in a zero-touch environment

**Comment by fouadsemaan** [comment]
> This also happened to me because my help upgrade process was interrupted. After some trial and error, a helm rollback restored my helm state i.e. `helm rollback <name> <revision>` hope it helps anyone in the same situation.

Manual intervention across hundreds of automated deployments is risky.

https://github.com/helm/helm/issues/7476#issuecomment-1018635708

**Comment by fouadsemaan** [comment]
> Yet another one who stumbles upon this issue! During a helm upgrade from a CD system there could be a multitude of events that might end up interrupting the upgrade process. A manual rollback should be a no-go in a zero-touch environment

Hear, hear!

**Comment by vasilevp** [comment]
> Yet another one who stumbles upon this issue! During a helm upgrade from a CD system there could be a multitude of events that might end up interrupting the upgrade process. A manual rollback should be a no-go in a zero-touch environment

One way to avoid manual rollbacks in a CI/CD setting is to run upgrade with the `--atomic` flag, if you can afford the wait. That way you can automatically roll back after a timeout which, at least in our case, works just fine.

**Comment by kitos9112** [comment]
> > Yet another one who stumbles upon this issue! During a helm upgrade from a CD system there could be a multitude of events that might end up interrupting the upgrade process. A manual rollback should be a no-go in a zero-touch environment
> 
> One way to avoid manual rollbacks in a CI/CD setting is to run upgrade with the `--atomic` flag, if you can afford the wait. That way you can automatically roll back after a timeout which, at least in our case, works just fine.

That's fair enough if you are lucky your CD job does not fail for whatever other reason (e.g., underlying compute issue, network failure, etc...) - We've not gotten around this issue just yet, and I still see this issue occurring in 1% of our deployments.

**Comment by johnib** [comment]
How come the `timeout` setting doesn't help in this case? My helm upgrade was stuck in this state for almost 2 weeks.
Eventually we manually rolled it back using `helm rollback` -- however that is not a good solution for automated systems.

What I'm trying to figure out is what does the `timeout` setting do, if not terminating long-running `pending-upgrade` operations? isn't it the sole purpose of this setting?

**Comment by zchenyu** [comment]
Bump. Can this issue be re-opened? It seems to be still occurring.

**Comment by 0054** [comment]
This problem is relevant for us too
sometimes when `helm upgrade ...` failed with an error, the release status **does not change** to Failed and stays in Pending-upgrade

**Comment by sourcehawk** [comment]
This happens far too often for helm to be a reliable automation tool. Sometimes not even a rollback will work and the only other option is to completely delete the helm chart or the namespace which is just plain out unacceptable for zero downtime production workloads.

**Comment by meredrica** [comment]
We just observed this again with fully automated builds.
We run this command: `helm upgrade --atomic --cleanup-on-fail --install --set some.value=foo --set other.value=bar releasename path/to/chart` followed by a `helm test releasename`
I'm aware that there are some workarounds like editing the secret etc, we opted fir deleting the charts since it was our dev instance, but this situation is not ideal.
I think this bug should be reopened and investigated again.

My best guess is that one deployment interrupted another during `helm upgrade` and this causes the problems. The deployment job right before the first problematic one was cancelled mid-flight, I can't see any relevant logs of helm being run, but the job might have been cancelled right during the `helm deploy`, not providing logs (I don't know the gitlab specifics for log collection)

**Comment by CharlesB2** [comment]
In our use case, we do `helm upgrade --install` in our CD pipeline for dynamic branch deployment. These jobs can be interrupted, which leaves the helm release in `pending-upgrade` and blocks later ones

So I came up with this script for cleaning up dangling `pending-install|upgrade` status, which handles this situation until helm provides a better way to handle this.

Use it at your own risk!
```bash
#!/bin/bash
set -eo pipefail

# Delete helm secrets in pending-(upgrade|install) so that subsequent helm upgrades don't fail

[[ -z "$1" || -z "$2" ]] && ( echo "Usage: $0 <namespace> <context>"; exit 1 )

namespace=$1
context=$2

pending_release_secret=$(kubectl get secrets --context "$context" -n "$namespace" \
                        -l 'status in (pending-upgrade, pending-install)' -o name \
                        | grep 'sh.helm.release' || true)
if [ -n "$pending_release_secret" ]; then
  echo "Deleting pending $pending_release_secret"
  kubectl delete --context "$context" -n "$namespace" "$pending_release_secret"
fi
```

**Comment by seankane-msft** [comment]
Hey @bacongobbler and Helm team,

We've encountered an issue where Helm releases get stuck in a `pending-upgrade`, `pending-rollback`, or `pending-install` state during automated CI/CD workflows. This requires manual intervention to resolve, which introduces delays and adds operational overhead.

I propose adding a flag like `--overwrite-pending` to automatically resolve this situation. If a release is in a pending state, this flag could either roll back to the previous release or mark the current release as failed, allowing the upgrade to proceed. This would help avoid getting stuck in a pending state and ensure that the deployment continues smoothly.

Example usage:

```sh
overwrite_pending="true"
echo "Upgrading Helm release ${release} in namespace ${namespace} from folder ${charts}"
( set -x
  helm3 upgrade ${release} ${charts} --install
) || {
  if [[ "${overwrite_pending}" == "true" ]]; then
    echo "Upgrade failed, checking for pending operations..."
    local status
    status=$(helm3 status ${release} -n ${namespace} -o json | jq -r .info.status)
    case "${status}" in
      pending-install|pending-upgrade|pending-rollback)
        echo "Found pending status ${status}, retrying with --overwrite-pending flag"
        ( set -x
          helm3 upgrade ${release} ${charts} --install --overwrite-pending ${flags}
        )
        ;;
      *)
        echo "Upgrade failed with status ${status}, not retrying"
        ;;
    esac
  else
    echo "Upgrade failed, not retrying"
  fi
}
```

This would provide a more resilient upgrade flow and reduce the need for manual intervention in CI/CD pipelines.

I'm happy to take on the work and submit a pull request for this feature if the maintainers are open to it. Would love to hear feedback or thoughts on the implementation before proceeding.

Thanks!

**Comment by robertsirc** [comment]
Hello @seankane-msft, 

Thank you for your idea. We are currently working on Helm 4 as we speak and changes like this would require a HIP or Helm Improvement Proposal. If you care to help write one up we would love to consider it. 

Thank you again,

R

**Comment by aviadshimoni** [comment]
Hi @robertsirc @sabre1041 @mattfarina, I was asking about the behavior of this in KubeCon London 2025, currently we implement the workaround like this:
```bash
# Check and rollback if Helm release is in a pending state
echo "Getting Helm release status..."
status=$(helm status my-release --namespace my-namespace --output json | jq -r '.info.status' || true)

# Pending statuses to check
pending_statuses=("pending-upgrade" "pending-rollback" "pending-install")

if [[ " ${pending_statuses[@]} " =~ " ${status} " ]]; then
  echo "Release is in '$status' state, performing rollback..."
  release_version=$(helm status my-release --namespace my-namespace --output json | jq -r '.version')
  helm rollback my-release $release_version --namespace my-namespace --wait --timeout 5m
  echo "Rollback performed."
fi
```

similar to how @seankane-msft, we can implement the same logic with `--overwrite-pending` flag.

any chance we can push it to Helm 4?
