### ISSUE TITLE
Feature: linter specific values

### ISSUE THREAD

**Issue by micw** [helm/helm#7482]
Output of `helm version`:
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

This is a feature request to solve common issues with linter. Currently having values not defined breaks helm lint. But for some values, it's dangerous to add defaults and the template designer wants the template to fail unless the user has reviewed and set this particular values.

I suggest that helm should read a special values file (e.g. "values-lint.yaml") in addition to values.yaml only if running helm lint to solve this.

**Comment by micw** [comment]
Additional info: with https://github.com/helm/helm/pull/5889, require returns an empty string when running in lint mode. Unfortunately that won't work if the value is expected to be a list or a dict. The following construct still would need special values for linting (expecting hostnames to be a list):

```
{{ first (required "hostname" .Values.hostnames) }}
```
The current solution would fail with "Cannot find first on type string"

**Comment by technosophos** [comment]
Here's my understanding of this feature request:

1. values.yaml should be loaded first
2. lint-values.yaml should be loaded second, and merged over `values.yaml`
3. The `-f` values should be loaded third, merged over the set above
4. `--set`-style values should be merged after that

1, 3, and 4 exist already. So this would be adding 2. The danger here is that if `lint-values.yaml` overloads `values.yaml`, it may obscure problems with `values.yaml` (thus marking it as successful even if `values.yaml` is broken). So I will experiment with inverting that order.

**Comment by technosophos** [comment]
This is blocked until #7984 is merged (since that has all the supporting code necessary for this PR)

**Comment by bacongobbler** [comment]
closing as stale.
