### ISSUE TITLE
nil pointer evaluating interface {}.value

### ISSUE THREAD

**Issue by mraliagha** [helm/helm#7485]
I am trying to use helm to template my application config. For some reason, I am not able to pass nil pointer issue. I don't understand why helm complains that the `Values.secret.registeryCredentials` is null!

`registry.url: {{ printf "https://%s@%s" .Values.secret.registeryCredentials.value (trimPrefix "https://" .Values.application.registryAddress) }}`

Values file:

```
secret: # property key to be set on the helm command
  registeryCredentials:
    name: "Registry_Credentials"
    value: "xxxx"
```

Output of `helm version`:

`version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}`

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Minikube and EKS

**Comment by mraliagha** [comment]
I changed the property prefix name from `secret` to something else and it worked. Then, I thought perhaps `secret` is a reserved word. However, when I changed it back again to `secret`, now it's working. So I assume I have hit a bug that only gets triggers if this is the first time you are deploying the service and after that, it works just fine! Am I missing something here?

**Comment by kirtiapte** [comment]
can you attach the PR?

**Comment by technosophos** [comment]
This issue appears to be closed. Nobody has reported being able to reproduce. Please re-open iif you can re-produce, and provide a complete template and values.YAML.

**Comment by mraliagha** [comment]
Sounds good. I couldn't reproduce it as well. Whatever it was, it's fixed. Thanks

**Comment by bluehawk27** [comment]
when I flipped on debug mode i saw `: secrets.go:132: [debug] query: failed to decode release: parsing time """" as ""2006-01-02T15:04:05Z07:00"": cannot parse """ as "2006"` somehow the GKE configuration for the release was missing a timestamp deleting everything and starting fresh got me around the issue.
