### ISSUE TITLE
Error after helm3 upgrade

### ISSUE THREAD

**Issue by momon** [helm/helm#7489]
Hello, I've been successful in upgrading from helm 2 to helm3 thanks to your guide.  All seems dandy except for this error which I get when I try to do a repo update:

```
momon@DESKTOP-D8J28R5:~$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
        Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: connect: connection refused
...Successfully got an update from the "jetstack" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈
momon@DESKTOP-D8J28R5:~$
```

**Comment by bacongobbler** [comment]
Do you have a chart repository running on your machine? If not, you can safely remove it with `helm repo remove local`. Helm 2 set that up as a convenient helper, but it was eventually removed as it proved to be more confusing to first-timers.

Let us know if that works.

**Comment by momon** [comment]
Had a feeling that was the case but not being very familiar with helm yet other than installing very specific resources I was not sure if that would break something.

Have done so now after understanding what it was and that sorted it:

```
momon@DESKTOP-D8J28R5:~$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "jetstack" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈
momon@DESKTOP-D8J28R5:~$
```

Thank you for the lightning fast response!

**Comment by hickeyma** [comment]
FYI for others you might read this, some doc on this in the plugin: https://github.com/helm/helm-2to3#readme-after-configuration-migration
