### ISSUE TITLE
How to update default templates  as I am not able to update server-configmap.yaml 

### ISSUE THREAD

**Issue by DevAlokK** [helm/helm#7490]
I have modified server-config map as I need to mention alerting target server there(which I am not able to do using values.yaml) . I am running this command(here server-configmap.yaml is my version of the file) - 
**helm install --name xyprometheus  stable/prometheus --tiller-namespace kub**** -f values.yaml -f server-configmap.yaml**

but that's not updating server-configmap in my kubernetes cluster namespace configmaps .
as I ran this command but don't see the changes reflecting -
**helm get manifest xyprometheus  --tiller-namespace kub********
I would be a great help if you guide me on this..thanks !

**Comment by bacongobbler** [comment]
Hi @DevAlokK. There's not much information provided here. With the information provided, I'm not sure how to reproduce the issue or how to help you.

As per the [github issue template](https://github.com/helm/helm/blob/master/.github/issue_template.md):

```
<!-- If you need help or think you have found a bug, please help us with your issue by entering the following information (otherwise you can delete this text): -->

Output of `helm version`:

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```

Some steps to help reproduce the issue would be helpful as well. Thank you.

**Comment by omkensey** [comment]
If i understand correctly @DevAlokK, you're trying to make a local copy of a single template file in the stable prometheus chart, then substitute your changed file for the corresponding file in the upstream chart at install time.  To the best of my knowledge, this isn't possible -- but you can download the entire chart, make your necessary changes to the template file locally, and then either use it from your local disk or repackage and rehost it somewhere.

**Comment by DevAlokK** [comment]
Thanks guys!
Sorry I could not reply earlier ..I got this.
I fetched the file then made a local copy of the template then ran this command-
kubectl apply -f alertmanager-configmap.yaml
this worked.
Thanks a lot!
