### ISSUE TITLE
Question: Is there a way/tool to generate changelogs for charts?

### ISSUE THREAD

**Issue by missylbytes** [helm/helm#7515]
I just have a general question. Is there a way to generate a changelog from one version of charts to the other?

**Comment by bacongobbler** [comment]
Hi @missylbytes!

I have not heard of such a tool, and there doesn't look to be one under the [Related Projects and Documentation](https://helm.sh/docs/community/related/) section. [helm-diff](https://github.com/databus23/helm-diff) is about as close as it gets to a changelog tool.

Let us know if you find any!

**Comment by missylbytes** [comment]
Thanks! Will look into it. 
I know there is the idea of using something like commitizen, but I have found issues with trying to make changelogs per-helm-chart in repositories with multiple charts.

**Comment by tegioz** [comment]
Just in case it helps :)

https://twitter.com/cncfartifacthub/status/1321424066943877121
