### ISSUE TITLE
Helm 3 throwing warning but successful

### ISSUE THREAD

**Issue by dhineshbabuelango** [helm/helm#7520]
We use helm to install istio, but after we started using helm3, we are continuously getting this below warning, can someone please help me to solve  this

Warning: Dependencies are handled in Chart.yaml since apiVersion "v2". We recommend migrating dependencies to Chart.yaml

**Comment by mattfarina** [comment]
This is a good question. Sorry to catch you off guard.

In helm v2 there was a `requirements.yaml` and `requirements.lock` file that listed dependencies. In Helm v3 the content of the `requirements.yaml` file was moved to the `Chart.yaml` file. The `requirements.lock` file was replaced by a `Chart.lock` file.

Helm v3 will use the `requirements.yaml` and `requirements.lock` file if they are present. It is just warning people of the change. In some future release of Helm (not soon but in a future major release) the old method will be removed.

**Comment by hickeyma** [comment]
Refer to docs for more details: https://helm.sh/docs/faq/#consolidation-of-requirements-yaml-into-chart-yaml

**Comment by hickeyma** [comment]
Closing as answered,
