### ISSUE TITLE
Provide standard url to get latest release of Helm

### ISSUE THREAD

**Issue by kittydoor** [helm/helm#7521]
Projects that use github releases have a standardized path to grab the latest binary or archive from, provided the binary/archive name does not change from release to release.

`https://github.com/<user>/<repo>/releases/latest/download/<file name>`

A lot of projects, such as distributions, tend to provide a standardized url for the latest version, often split by major releases.

`http://<mirror url>/centos/7/isos/x86_64/<file name>`
`http://<mirror url>/centos/7.7.1908/...`
`http://<mirror url>/centos/8/...`

However, so far I haven't succeeded at finding such a way to grab the latest helm package. I have automated them via curling the latest github release, regexing out the version number, and injecting it into the get.helm.sh path to get the file. However, it would be great if helm would provide either split versioned latest releases (preferable), or at least a master url for the latest version.

Is this already possible, and I've just missed it? Or perhaps, is it something you would be interested in providing?

This seems to have been explored in #2274 and closed after being added to the list in #1968. However, I was unable to find any information on this after that point.

**Comment by mattfarina** [comment]
This would be fantastic and has long been on my "wants" list.

**Comment by bacongobbler** [comment]
Same here. I was trying to fiddle with Azure CDN redirection rules to see if I could make a canonical “latest stable” URL like https://get.helm.sh/helm-latest-Linux-amd64.tar.gz that would resolve to 3.0.3 (current latest).

I would love suggestions on how to beat accomplish this.

For context: https://helm.sh/blog/get-helm-sh/

**Comment by sudolibre** [comment]
FYI the azure pipelines (build system) will pull `https://github.com/helm/helm/releases/latest` by default when installing helm. Prior to last week this would install a v3 version of helm by default. Recently a 2.16 build was tagged as latest breaking all build scripts that were relying on the latest build being a v3 version of helm. 

reference: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/helm-installer?view=azure-devops

**Comment by bacongobbler** [comment]
@sudolibre see https://github.com/helm/helm/issues/7597#issuecomment-586424552 for more information. tl;dr Azure DevOps is using Github's API incorrectly, and they need to fix it on their end.

**Comment by bridgetkromhout** [comment]
As the 2.x versions will soon stop receiving updates, this problem may become less of an issue.

**Comment by bacongobbler** [comment]
While true, this may resurface should we choose to release patches for 2 minor versions, or release Helm 4. I think this is worth the effort in the long haul.
