### ISSUE TITLE
client image

### ISSUE THREAD

**Issue by kfox1111** [helm/helm#7522]
I'm wondering if it would be a good idea to have an official container image with helm 3 in it. This would be useful in things like ci/cd pipelines where you could run helm directly by specifying the image.

**Comment by mattfarina** [comment]
I just looked at Docker Hub and there are a lot of Helm images there now. I had no idea.

Lachie, one of the charts maintainers, has long had an image listed that we point people to at https://hub.docker.com/r/lachlanevenson/k8s-helm. I think it's getting lost among so many options now. This could be good for the Helm project to take on.

@lachie83 thoughts?

**Comment by kfox1111** [comment]
Ok, cool. I'll use @lachie83's image for now. But yeah, I was lost as to which to pick. An official one would be nice. But maybe just a link in the releases that point to his repo would help.

**Comment by technosophos** [comment]
Should I close this? No core maintainers seem to have expressed a desire to maintain an official image.

**Comment by kfox1111** [comment]
Do the helm maintainers think its a good idea that someone with possibly nefarious intent could post an official looking image?

If nothing else, maybe take the helm org so no one else grabs it?

**Comment by bacongobbler** [comment]
> If nothing else, maybe take the helm org so no one else grabs it?

We claimed [the helmpack account](https://hub.docker.com/u/helmpack) on DockerHub back in November 2017.

**Comment by technosophos** [comment]
I think the Helm org was taken when I first got helmpack. Is it now available?

**Comment by kfox1111** [comment]
https://hub.docker.com/u/helm 404's. So looks like its available.

**Comment by lachie83** [comment]
I would be happy to donate (or work on) and deprecate the container repo that I'm currently maintaining (https://hub.docker.com/r/lachlanevenson/k8s-helm) in favor of an official project repo. There is 2.2M pulls on that container so there is clearly a need.

**Comment by lachie83** [comment]
The https://hub.docker.com/r/lachlanevenson/k8s-helm container is built and published from a Github Action via this repo - https://github.com/lachie83/k8s-helm

**Comment by bacongobbler** [comment]
After multiple years of maintenance hassle required with the tiller image, no core maintainers have expressed any interest in maintaining a Helm 3 docker image. [Taking @technosophos's earlier advice](https://github.com/helm/helm/issues/7522#issuecomment-617441691), I'm going ahead and closing this as something we do not plan to support. We're more than happy to list images owned by the community in the documentation.
