### ISSUE TITLE
Under what circumstances does helm upgrade not replace a deployment

### ISSUE THREAD

**Issue by Bajix** [helm/helm#7524]
I have a helm chart with multiple sub charts that's deployed via a CircleCI workflow. If one of my sub charts has no changes and the image has the same SHA, will helm upgrade skip deploying that?

**Comment by bacongobbler** [comment]
Hi @Bajix. Have you read the FAQ on how the upgrade strategy works? https://helm.sh/docs/faq/#improved-upgrade-strategy-3-way-strategic-merge-patches

Let us know if you have further questions after reading that document.

**Comment by Bajix** [comment]
@bacongobbler Thanks for getting back to me; that was in fact very helpful! To expand on my previous question, if a manifest has different image tags but those tags have the same SHA, is that considered for there to be no changes? As all of my sub chart images share the same Tag for that specific workflow, it'll always be the case that the manifest points to a different image even when that image has the same SHA as the current live image. Can you confirm the manifest diff comparison uses the image SHA for comparison and not the tag?

**Comment by bacongobbler** [comment]
the comparison uses the content of the rendered template as-is for the comparison. It does not inspect the manifest and resolves an image's tag to its digest.

Here is the code in question:

https://github.com/helm/helm/blob/7ce29e12fa8ac7195613ffa1a76b2914150ff756/pkg/kube/client.go#L346-L353

Does that help answer your question?

**Comment by Bajix** [comment]
@bacongobbler I think that it would be extremely useful for Helm to start resolving image tag digests before making a comparison as then this could enable mono repos to skip unnecessary partial deployments when individual images haven't changed. When I tried making a workaround for this before, I could not get this to load an ECS image by it's SHA at all and thus there was no viable workaround to prevent unnecessary deployments.
