### ISSUE TITLE
[docs] Info on Chart.yaml indents some properties wrongly

### ISSUE THREAD

**Issue by davidmichaelkarr** [helm/helm#7525]
I may be confused about YAML syntax, but https://helm.sh/docs/topics/charts/#the-chart-yaml-file , I see the following:
![image](https://user-images.githubusercontent.com/5566419/73799867-038f8980-476c-11ea-812b-d19103d2bb70.png)

I haven't tried to find anything like a schema, but I have a feeling that the only properties in each dependency are "name", "version", and "repository".  At least that's what the detailed docs mention.  The properties that come after that at the same indent level, like "condition", "tags", "enabled", "import-values", and "alias" most likely apply to the entire chart, not a specific dependency, so they should be de-indented one level.

**Comment by davidmichaelkarr** [comment]
It appears that "alias" is allowed both in a dependency and the main chart, but I have a feeling the "alias" in this picture was supposed to refer to the main chart, not the dependency.

**Comment by davidmichaelkarr** [comment]
And now I see that "tags", "condition", and "import-values" can also apply to a dependency.  It appears that only "enabled" is definitely wrong indented here, but reading the comments on those other properties in this image makes me think those other properties were intended to refer to the main chart, not the dependency.

**Comment by mattfarina** [comment]
The properties like `condition`, `tags`, `enabled`, etc are per dependency. This is the same for both Helm 2 and 3. For example, the wordpress chart in the stable charts repository has:

```
dependencies:
- name: mariadb
  version: 7.x.x
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: mariadb.enabled
  tags:
    - wordpress-database
```

In the `values.yaml` file there is a section that has:

```
mariadb:
  ## Whether to deploy a mariadb server to satisfy the applications database requirements. To use an external database set this to false and configure the externalDatabase parameters
  enabled: true
```

When `mariadb.enabled` is set to `false` the dependency is not installed.

**Comment by technosophos** [comment]
I don't think there is any Helm bug here, though there is possibly a documentation error that should be filed in the docs project: https://github.com/helm/helm-www/issues
