### ISSUE TITLE
Support $XDG_DATA_DIRS

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#7529]
The [XDG Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) has an environment variable known as `$XDG_DATA_DIRS`. This variable can have multiple data directories to look for things (e.g., plugins). The spec notes:

> $XDG_DATA_DIRS defines the preference-ordered set of base directories to search for data files in addition to the $XDG_DATA_HOME base directory. The directories in $XDG_DATA_DIRS should be seperated with a colon ':'. 

A docker container or something else could system wide data in here (e.g., plugins).

**Comment by waveywaves** [comment]
@mattfarina can you assign me to this ? 
I just want to understand one thing, might be very elementary. Why do we follow the XDG Specification ? Is there any particular reason ? How is it different from having `HELM_` env vars ?

**Comment by adamreese** [comment]
To clarify... The feature request to allow an order precedented lookup for plugins.

For example if running the plugin `helm foo` the first plugin found in `$XDG_DATA_HOME:$XDG_DATA_DIRS:{{os default xdg}}` that is named foo would be selected.

XDG_DATA_DIRS would only be used for path lookup and not exposed

**Comment by bacongobbler** [comment]
closing as stale.
