### ISSUE TITLE
getting Error: provider.helm: : invalid or unknown key: namespace and service_account

### ISSUE THREAD

**Issue by vrathore18** [helm/helm#7534]
suddenly I started getting this error:
I am using this base image
hashicorp/terraform:0.11.13

```
===> terraform plan

Error: provider.helm: : invalid or unknown key: namespace



Error: provider.helm: : invalid or unknown key: service_account
```

**Comment by mattfarina** [comment]
The Helm project does not maintain the Helm terraform code. You might get better support from the terraform community.

**Comment by bacongobbler** [comment]
Agreed. There's nothing we can do on our end here. Please open a ticket with the [terraform-provider-helm](https://github.com/terraform-providers/terraform-provider-helm) project. Thanks!

**Comment by kaijparo** [comment]
i know this isn't you're problem, but i ran into this too.

my emergency fix was to update the helm provider with the version restriction:

provider "helm" {
  version = "< 1.0.0"
  kubernetes {
    config_context = "${var.clusterName}"
  }
  service_account = "${kubernetes_service_account.tiller.metadata.0.name}"
}

i'm still on an older helm version
