### ISSUE TITLE
Error/panic when installing/deleting chart with only CRDs

### ISSUE THREAD

**Issue by carlpett** [helm/helm#7537]
A chart with only CRDs fails to install, and if running with `--debug`, also panics.

Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.6"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.17", GitCommit:"bdceba0734835c6cb1acbd1c447caf17d8613b44", GitTreeState:"clean", BuildDate:"2020-01-17T23:10:13Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

Installation/deletion:
```
$ helm install crd-test . --debug
install.go:149: [debug] Original chart version: ""
install.go:166: [debug] CHART PATH: <redacted>

client.go:88: [debug] creating 1 resource(s)
client.go:88: [debug] creating 1 resource(s)
client.go:88: [debug] creating 1 resource(s)
client.go:88: [debug] creating 1 resource(s)
client.go:88: [debug] creating 1 resource(s)
install.go:139: [debug] Clearing discovery cache
wait.go:51: [debug] beginning wait for 5 resources with timeout of 1m0s
client.go:88: [debug] creating 0 resource(s)
Error: no objects visited
helm.go:75: [debug] no objects visited
helm.sh/helm/v3/pkg/kube.init
        /home/circleci/helm.sh/helm/pkg/kube/client.go:50
runtime.doInit
        /usr/local/go/src/runtime/proc.go:5222
runtime.doInit
        /usr/local/go/src/runtime/proc.go:5217
runtime.doInit
        /usr/local/go/src/runtime/proc.go:5217
runtime.main
        /usr/local/go/src/runtime/proc.go:190
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1357
```

If I then delete the release, same:
```
$ helm delete crd-test --debug
uninstall.go:91: [debug] uninstall: Deleting crd-test
uninstall.go:124: [debug] purge requested for crd-test
Error: uninstallation completed with 1 error(s): object not found, skipping delete
helm.go:75: [debug] uninstallation completed with 1 error(s): object not found, skipping delete
helm.sh/helm/v3/pkg/action.(*Uninstall).Run
        /home/circleci/helm.sh/helm/pkg/action/uninstall.go:132
main.newUninstallCmd.func1
        /home/circleci/helm.sh/helm/cmd/helm/uninstall.go:53
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:74
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1357
```

**Comment by Hedingber** [comment]
This bug is really painful !
It is becoming a common use case to use the helm chart to install CRDs as an administrative action, before installing the application that uses it, and due to this bug it's impossible with helm v3.
Note that the docs (https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-2-separate-charts) are also pointing to have separate charts, one only for the CRDs and another one for the application... impossible

**Comment by omesser** [comment]
Hey helm folks, Is anyone looking at this?
This is a real regression in handling of CRDs

**Comment by waveywaves** [comment]
@carlpett @omesser @Hedingber I am working on this currently. We are facing the same issue with our Operators.

/assign

**Comment by juliohm1978** [comment]
Just hit the same issue today. I was able to workaround this by having the CRD chart create a dummy resource, ie: some empty configmap.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}-dummy-resource
  namespace: {{.Release.Namespace}}
data:
```
It's dumb, but it gets around it.

However!

This issue sounds less important, given there are other unresolved issues with helm handling of CRD lifecycle. Namely: https://github.com/helm/helm/issues/4840 and  https://github.com/helm/helm/issues/4697.

Even if you get your CRDs installed from a dedicated chart, a `helm delete` won't delete them.

**Comment by Hedingber** [comment]
@juliohm1978 Definitely !
What I did to overcome this was to make the CRDs to be just regular templates e.g. not putting them in the `crds` directory and not adding them the `crd-install` hook (as it was suggested in helm 2).

This makes the CRD a resource so no `no objects visited` problems, and also the CRD will be deleted when doing `helm delete/uninstall`.

This is totally against best practices both for helm 2 and 3, but... it works :-)

If you want an example you can take a look at a helm chart we did to install [dex's](https://github.com/dexidp/dex) CRDs - https://github.com/v3io/helm-charts/tree/development/stable/dex-crds
