### ISSUE TITLE
"More complex SemVer 2" not supported by helm v3

### ISSUE THREAD

**Issue by jopfeffe** [helm/helm#7538]
Output of `helm version`:
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.6"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-21T22:17:28Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
RKE

Create a chart with following Chart.yaml
```
apiVersion: v1
appVersion: v0.8.15
name: foo
version: 1.2.3-alpha.1+ef365
```
(version number is copied from helm docu: https://helm.sh/docs/topics/charts/#charts-and-versioning)
Package and upload the chart to helm repo - in my case chart museum.

helm repo add test <url>
helm repo update
helm search repo foo -l

Result: 
Chart is not listed as search result.

Expected: 
Chart is listed. 

Additional stuff:
 - chart is listed when using helm v2. 
 - chart is listed if version is set to "1.2.3.4" - but i can't be installed (download error)
 - chart is listed and can be installed if version is set to "1.2.3"

**Comment by mattfarina** [comment]
By default `helm search repo` only lists stable releases. In the example the `-alpha.1` means this is a pre-release version. To view this the `--devel` flag needs to be used. For example,

```
$ helm search repo --devel foo
```

Does that help?

**Comment by bacongobbler** [comment]
Closing as answered; please feel free to reopen if you have further questions. Thanks!
