### ISSUE TITLE
error passing no_proxy parameter

### ISSUE THREAD

**Issue by publicocean0** [helm/helm#7540]
helm version
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.6"}

I want pass the no_proxy variable to the container ...

`helm install rancher rancher-latest/rancher --namespace cattle-system --set hostname=rancher.comune.intranet   --set no_proxy='localhost,127.0.0.1,.localhost,.comune.intranet'`

Error: failed parsing --set data: key "1" has no value (cannot end with ,)

**Comment by mattfarina** [comment]
Helm and Kubernetes don't let you pass variables at the command line this way. Instead, they need to be declared. It's not like [running a docker command for this](https://rancher.com/docs/rancher/v1.6/en/installing-rancher/installing-server/#launching-rancher-server-behind-an-http-proxy).

The `no_proxy` option needs to be exposed in the Kubernetes templates and in the `values.yaml` of the chart for Helm to have access to set it. That does not appear to be the case for the rancher chart. You should reach out to the Rancher folks for help with this.

**Comment by publicocean0** [comment]
thanks i solved :)
