### ISSUE TITLE
Use in-memory cache instead of filesystem HELM_REPOSITORY_CACHE

### ISSUE THREAD

**Issue by sbose78** [helm/helm#7545]
Hi,
As part of `helm install ...` ( and other flows ), the chart tgz gets written to HELM_REPOSITORY_CACHE. 
Any thoughts on doing that in-memory ?

I'm using the Helm Golang APIs from a service running in a container and I would want to avoid writing to the filesystem altogether.

**Comment by mattfarina** [comment]
I have some questions to try to better understand what you're asking for.

- Are you using the Helm `pkg` directory within your application (the API) or are you using the Helm binary to run commands? I see you have both listed here and I just wanted to clarify
- Are you looking to have an option for in-memory or a system to be pluggable? I ask because if I were writing a service I might want to use object storage for some form of shared cache. Just thinking aloud.

**Comment by waveywaves** [comment]
@mattfarina from what I have understood, we need an inmemory cache apart from the object storage cache when we are using helm as a service. This would mean that we would have only single chart in the cache for a single helm request. @sbose78 is this what you would like to do ?

What I would propose is ..
1> Have a flag which would set helm to disable repository cache. `--disable-repo-cache`
```
```

**Comment by waveywaves** [comment]
@mattfarina from what I have understood, we need an inmemory cache apart from the object storage cache when we are using helm as a service. This would mean that we would have only single chart in the cache for a single helm request. @sbose78 is this what you would like to do ?

What I would propose is ..
- Have a flag which would set helm to disable repo-cache. `--disable-repo-cache`
```
$ helm install <name> <chart> --disable-repo-cache
```
- Once the repo-cache is disabled, we can use `groupcache` to cache in-memory.
- Incase the user wants to have repo-cache disabled for all their requests, we can set env `HELM_DISABLE_REPOSITORY_CACHE=true`.

We would be avoiding writing to fs this way.

**Comment by sbose78** [comment]
> Are you using the Helm pkg directory within your application (the API) 

Yes, I'm using the Golang APIs


> Are you looking to have an option for in-memory or a system to be pluggable? 


Right. I could go for a shared cache ( and use object storage ), but initially I'm Okay with not having a cache at all. All that a request needs is to do is 'write' the tgz file to some location, use it, and then clean it up when the request handling is complete.

**Comment by mattfarina** [comment]
Here's what I would propose based on this discussion.

1. The Helm CLI commands stay the way they are for now. This is about the Go APIs so we can focus on those.
2. We see if there is a way to make the cache pluggable in v3. The method we use MUST be API backwards compatible. The Helm CLI would use the existing method. Others could set their own to anything that implements an interface.

Does that sound acceptable? If so, I would be happy to review PRs on it but don't personally have time in the immediate future (next few months).

**Comment by technosophos** [comment]
Should I close this? The issue seems to have lost momentum, but @mattfarina 's suggestion seems to be the proper way forward.

**Comment by marckhouzam** [comment]
PR #7601 aims to fix this but is still going through review.

**Comment by mattfarina** [comment]
From the meeting on 5/7

The goal of this request is to be able to install charts while running Helm on a system with a read-only file system.

Expect Kubernetes configuration to be passed in via a volume mount. For example, when run in a pod.

In these cases we would need a full URL to a package. This was discussed.

**Comment by pedjak** [comment]
thanks @mattfarina for the summary. Besides install - upgrade/template should work as well on read-only filesystem.

**Comment by bacongobbler** [comment]
closing as stale.
