### ISSUE TITLE
k8s 1.17+helm3.0.3 : Error: [::1]:6443: connect: cannot assign requested address

### ISSUE THREAD

**Issue by ReSearchITEng** [helm/helm#7548]
All is ok in k8s 1.16, but in k8s 1.17.2, helm install gives error:

```Error: create: failed to create: Get https://[::1]:6443/api/v1/namespaces/kube-system/resourcequotas: dial tcp [::1]:6443: connect: cannot assign requested address```

Output of `helm version`:
3.0.3
Output of `kubectl version`:
1.17.2 (w/ ipvs), **no ipv6 dualstack** or anything related to ipv6

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
On Prem
Ubuntu 18.04, with **ipv6 fully disabled** at kernel level

**Comment by bacongobbler** [comment]
Hi @ReSearchITEng. What does your kube config (~/.kube/config) look like? Can you reach your cluster normally with `kubectl cluster-info`?

**Comment by ReSearchITEng** [comment]
Hi,
yes of course. Cluster is working fine, kubectl command, etc.
And again, for k8s 1.16 all is good, issue starts from k8s 1.17.

**Comment by avarf** [comment]
We are facing this issue but we are using K8s 1.15.

We had some network problem and because of that we disabled IPv6 at the kernel level and now `helm inistall` is generating this error:
```bash
helm install stable/nginx-ingress --namespace=147
Error: release calico-platypus failed: Get https://[::1]:6443/api/v1/namespaces/147/resourcequotas: dial tcp [::1]:6443: connect: cannot assign requested address
```
But both kubectl and `helm ls` are working.

How we can solve this without enabling IPv6 again?

**Comment by avarf** [comment]
This is a known problem https://github.com/helm/helm/issues/2634

**Comment by VF-mbrauer** [comment]
Do we have a new status here? Also the #2634 is already closed.

**Comment by technosophos** [comment]
Why do you think this is the same problem as #2634? Have you checked your hosts file? Does it have an IP v6 address there?

Somewhere along the line, something external to Helm is telling Helm to use the IPv6 address. If you can find that and fix it, all should work.

**Comment by bacongobbler** [comment]
closing as stale.

**Comment by rstoermer** [comment]
Got this again:

```
Error: UPGRADE FAILED: create: failed to create: Get "https://[::1]:6443/api/v1/namespaces/nextor-dependencies/resourcequotas": dial tcp [::1]:6443: connect: cannot assign requested address
helm.go:81: [debug] Get "https://[::1]:6443/api/v1/namespaces/nextor-dependencies/resourcequotas": dial tcp [::1]:6443: connect: cannot assign requested address
```
kubectl on the same cluster works without problems, helm ls as well

**Comment by JoostvdB94** [comment]
> Why do you think this is the same problem as #2634? Have you checked your hosts file? Does it have an IP v6 address there?
> 
> Somewhere along the line, something external to Helm is telling Helm to use the IPv6 address. If you can find that and fix it, all should work.

I've got the same issue. After disabling ipv6, the `helm upgrade --install` command fails with the error:
`Error: UPGRADE FAILED: create: failed to create: Get \"[https://[::1]:6443/api/v1/namespaces/operators/resourcequotas\"](https://[::1]:6443/api/v1/namespaces/operators/resourcequotas/%22): dial tcp [::1]:6443: connect: network is unreachable`

Things i've done to disable IPv6:
- Put the following inside `/etc/sysctl.d/10-disable-ipv6.conf`
  ```
  net.ipv6.conf.all.disable_ipv6=1
  net.ipv6.conf.default.disable_ipv6=1
  net.ipv6.conf.lo.disable_ipv6=1
  ```
- Reloaded systctl
- Checked the following files to ensure ipv6 was disabled (content should be `1`):
  - `/proc/sys/net/ipv6/conf/default/disable_ipv6`
  - `/proc/sys/net/ipv6/conf/all/disable_ipv6`
  - `/proc/sys/net/ipv6/conf/lo/disable_ipv6`
- Remove `::1`-entry pointing to `localhost` from `/etc/hosts` file
- Restarted kubelet

Still, Helm tries to locate the apiserver via `::1`

Only if I restart the entire (controlplane) node, the command succeeds.

Is there any way to make this work without restarting the control plane nodes?

**Comment by JoostvdB94** [comment]
The last lines of the helm install output is below. 
`<URL>` was redacted, but is the correct URL from the kubeconfig

```
I1222 13:28:10.663838   20098 loader.go:372] Config loaded from file:  /root/.kube/config
I1222 13:28:10.703026   20098 round_trippers.go:553] GET https://<URL>:6443/api/v1/namespaces/operators/secrets?labelSelector=name%3Dtigera-operator%2Cowner%3Dhelm 200 OK in 38 milliseconds
I1222 13:28:11.585579   20098 round_trippers.go:553] POST https://<URL>:6443/api/v1/namespaces/operators/secrets 500 Internal Server Error in 74 milliseconds
Error: UPGRADE FAILED: create: failed to create: Get "https://[::1]:6443/api/v1/namespaces/operators/resourcequotas": dial tcp [::1]:6443: connect: network is unreachable
```` 

It seems that the Internal Server Error when POST-ing secrets logs the ERROR.
Any ideas on where to look next?
