### ISSUE TITLE
How to apply condition to dependency charts in the charts/ directory.

### ISSUE THREAD

**Issue by tuxknight** [helm/helm#7550]
Dependencies in Chart.yaml have a field `condition` to control loading for the charts. But what about charts in the charts/ directory ? How to control loading for these charts.

**Comment by mattfarina** [comment]
This is a great question. The [chart dependencies documentation](https://helm.sh/docs/topics/charts/#chart-dependencies) is a good place to start. You should use the `dependencies` listing in the `Chart.yaml` or `requirements.yaml` for Helm v2. Even if the chart is in the `charts/` directory. Running commands like `helm dependency update` will even pull down a copy of a remote chart to the `charts` directory. The `condition` from the configuration will still apply.

**Comment by tuxknight** [comment]
Thank you very much. It helps a lot !
