### ISSUE TITLE
multiline parsing values error.

### ISSUE THREAD

**Issue by lucaspouzac** [helm/helm#7551]
Hi, 

With helm 3.0.3, I try to use multiline variables, but if I have a second line that starts with at least 3 minus (---), such as a public key, a parsing error is raised.

**deployment.yaml**
```
spec:
  template:
    spec:
      containers:
        - env:
            - name: PUBLIC_KEY
              value: "{{ .Values.app.publicKey }}"
```

**values.yaml**
```
app:
  publicKey: |
    -----BEGIN PUBLIC KEY-----
    ...
    -----END PUBLIC KEY-------
```

```
helm template charts --values charts/values.yaml

Error: YAML parse error on templates/deployment.yaml: error converting YAML to JSON: yaml: line 95: found unexpected end of stream
```

If the last line starts with less than 3 minus, it works.

**Comment by bacongobbler** [comment]
Hi @lucaspouzac. Can you check and confirm if this might be due to a YAML parser error? It's possible that a YAML parser may treat that as an escape ending. Have you looked into possible workaround?

**Comment by bacongobbler** [comment]
An alternative option may be to use `.Files.Get` instead: https://helm.sh/docs/chart_template_guide/accessing_files/#scrollpane

**Comment by lucaspouzac** [comment]
I try also 
```
{{- $publicKey := printf "%s%s" .Values.app.publicKey "-----END PUBLIC KEY-----" -}}
```
with values.yaml
```
app:
  publicKey: |
    -----BEGIN PUBLIC KEY-----
    ...
```
And I have the same error. 

I just tested it right now with .Files.Get, and I have the same problem.

**Comment by technosophos** [comment]
The error comes from the YAML parser, which lazily sees `---` as a stream separator. Can you please post the results of using `.Files.Get`? It may be that injecting this into Kubernetes is where the parse error is occurring, in which case we will need to figure out what the right escape sequence is. This should be documented somewhere in the YAML 2 spec. https://yaml.org/spec/

**Comment by lucaspouzac** [comment]
With .Files.get, I have the same problem.

public.key file

`
-----BEGIN PUBLIC KEY-----
abcd
abcd
-----END PUBLIC KEY-------
`

secret.yaml

`
apiVersion: v1
kind: Secret
metadata:
  name: test-pub-key
type: Opaque
stringData:
  PUB_KEY: {{ .Files.Get "public.key" }}
`

Result:
`
Error: YAML parse error on templates/secret.yaml: error converting YAML to JSON: yaml: line 8: could not find expected ':'
`

**Comment by lucaspouzac** [comment]
If I use data instead of stringData, it seems to work.

**Comment by bacongobbler** [comment]
closing as stale.

**Comment by edwbuck** [comment]
This problem still persists, and the lack of multiline support for 2 years it troublesome.

The problem is not embedded within the values.yaml, or the rendering of the value in the template; but rather, in the template having a pipe "|" character in the plain text portion of the template.  Multi-line values where the template uses a ">" work fine.

For this reason this is probably a bug.

Any template, containing
    key: | 

Will fail,  even if typing in the value directly

   key: |
      -----STUFF-----

And I have working examples of passing the values into the templates from mulitline (with the | ) values.yaml files.  Dry run rendering works 100%, but the output YAML is invalid due to the missing pipe character.

**Comment by edwbuck** [comment]
The files approach is an ugly hack that is unnecessary.  The better approach, that works for muliline values needing a |

(values.yaml)
path:
  value: |
    asdf
    asdf
  value2: yes

(some template)

   value: {{ toYaml .Values.path.value | indent 4 }}

the indentation value will have to be adjusted to ensure your multiline value is under the rendered tag indentation.  The toYaml directive will add a pipe character "|" and a newline before the value.

**Comment by dberardo-com** [comment]
any solution here ... i am so annoyed by this really ..

**Comment by adoraisa** [comment]
I had the similar problem of `Error: YAML parse error on templates/route.yaml: error converting YAML to JSON: yaml: line 19: could not find expected ':'`

The values (tls_crt and tls_key) was base64 encoded and decoded before updating into values.yaml
and adding `quote` has solved the problem.
```
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
    certificate: {{ .Values.tls_crt | quote }}
    key: {{ .Values.tls_key | quote }}
```
