### ISSUE TITLE
Cant upgrade my helm chart - getting "existing resource - PersistentVolume"

### ISSUE THREAD

**Issue by itaydj** [helm/helm#7564]
Hi,
I was trying to update my deployment using the following command:
`helm upgrade grid-services-reporter ./k8s/my-service-name --install  --wait --kube-context=${ENV} `

but for some reason I am getting the following error:
`Error: UPGRADE FAILED: rendered manifests contain a new resource that already exists. Unable to continue with update: existing resource conflict: kind: PersistentVolume, namespace: , name: my-service-name`

Not sure why it fail to upgrade...
Any pointers will help

my persistentvolume.yml:
`{{- if .Values.volume.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "grid-services-reporter.fullname" . }}-pv
  labels:
{{ include "grid-services-reporter.labels" . | indent 4 }}
spec:
  capacity:
    storage: {{ .Values.volume.size }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    server: {{ .Values.volume.server }}
    path: {{ .Values.volume.path }}
  {{- end }}`

Output of `helm version`:
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

**Comment by pho-enix** [comment]
Hi @itaydj could you please check if the `apiVersion` changed?

Probably a dup of #6850

**Comment by itaydj** [comment]
Hi @pho-enix,
Thanks for the reply - seems like my issue is indeed a dup of #6850 
Thanks
