### ISSUE TITLE
helm template output split when using {{ range }}

### ISSUE THREAD

**Issue by xUnholy** [helm/helm#7572]
Usecase:

Given I want to create a template for a given Kubernetes resource and use a GitOps tool to deploy my resources to the Kubernetes cluster, it's expected that namespace specific resources would be in their respective namespace dir hierarchy. This is true for ACM ("Anthos Config Management") as mentioned in their design docs 

https://cloud.google.com/anthos-config-management/docs/concepts/repo#example_repo

Ideally, a keyword should indicate that a given {{ range }} keyword may output a unique file on output so that resources unique to namespaces may be output individually whilst using the same range.

**Comment by hickeyma** [comment]
@xUnholy Do you mind expanding more on the use case. Maybe show an example on the template command and the output expected? It will help get a better understanding of the request.

**Comment by xUnholy** [comment]
@hickeyma An example might be the following where we're creating a destination rules resource which is used via Istio. These resources may be unique per namespaces, hence namespace is parameterized.

If I were to run `helm template` it will output all my template files, however, due to the nature of using the {{ range }} it will output a single file for this template such as: `destinationrules.yaml` and have all unique namespace scoped YAML files, however, the GitOps tools we're using require that namespace specific resources exist in their respective namespace dir hierarchy. Thus we'd like to be able to output our {{ range }} template into unique files for each iteration of the range.

Example:

`{{ if .Values.destinationRules }}
{{ range .Values.destinationRules }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name:  {{ .name | quote }}
{{ if not $.Values.namespace.labels.parentNamespace }}
  namespace: {{ $.Values.namespace.name | quote }}
{{- end }}
{{ if .namespaceSelector }}
{{ if .namespaceSelector.name }}
  annotations:
      configmanagement.gke.io/namespace-selector: {{ .namespaceSelector.name }}
{{- end }}
{{- end}}
spec:
{{ toYaml . | nindent 2}}
{{ end }}
{{ end }}`

**Comment by xUnholy** [comment]
@hickeyma bump.

**Comment by hickeyma** [comment]
@xUnholy I am not sure how you would implement this in Helm and if it is within the remit of Helm. The more I think  about this the more I think that this is better suited to a tool around Helm rather than Helm core capability.  It might be worth implementing it as a [Helm plugin](https://helm.sh/docs/topics/plugins/).

Let me know what you think.

**Comment by technosophos** [comment]
This is outside of the core feature set of Helm, which is a package manager. Your best bet is to implement this as a Helm plugin.

**Comment by afcollins** [comment]
@xUnholy Also interested in this. Did you find a working solution?

**Comment by xUnholy** [comment]
Unfortunately no I didn't, I've become a lot more familiar with kustomize and it has been a lot more flexible and in my specific implementation it became a non-issue.
