### ISSUE TITLE
Helm3 charts are getting installed via Helm2 version

### ISSUE THREAD

**Issue by avinashkumar1289** [helm/helm#7573]
I have two versions of helm installed in my client.I have created a chart using helm3 and as i can see that the apiVersion in Chart.yaml is v2.
I also have a helm2 version installed as well below is the version details.
```
Client: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```
But when i try to install the Helm3 chart using this Helm2 client, the charts are getting installed.
I don't think this is a valid scenario.Helm3 charts should only be getting installed via helm3 version.

**Comment by hickeyma** [comment]
@avinashkumar1289 I am unable to reproduce this.  When I try to install a Helm chart with `apiVersion` `v2` it fails as expected:

```console
$ cat mychart-v3/Chart.yaml 
apiVersion: v2
name: mychart-v3
description: A Helm chart for Kubernetes
[......]

$ helm2 install --name mychart-v3 mychart-v3/
Error: apiVersion 'v2' is not valid. The value must be "v1"
```

It might be worth looking at the `CHART` field of the `helm list` output for Helm 2. Just to make sure of the chart that you installed.

**Comment by avinashkumar1289** [comment]
@hickeyma Basically my chart.yaml looks like this 
```
apiVersion: v2
name: meeting-app
description: A Helm chart for Kubernetes
version: 1.0.3
type: application
```
And when i deploy this using helm2 
```
helm ls --namespace jfrog
NAME 	REVISION	UPDATED                 	STATUS  	CHART            	APP VERSION	NAMESPACE
testz	1       	Wed Feb 12 18:15:34 2020	DEPLOYED	meeting-app-1.0.3	v0.1.004   	jfrog
 helm version
Client: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```

**Comment by hickeyma** [comment]
@avinashkumar1289 Can you show the command that you are using to install it?

**Comment by avinashkumar1289** [comment]
@hickeyma  I have used this command to install
```
helm install meeting-app/ --name testz --namespace jfrog
```
This is my kubernetes version

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-gke.33", GitCommit:"2c6d0ee462cee7609113bf9e175c107599d5213f", GitTreeState:"clean", BuildDate:"2020-01-15T17:47:46Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```
If you can let me know what other details you need , will be happy to provide the same.

**Comment by hickeyma** [comment]
@avinashkumar1289 It might be because your Helm 2 client version is `v2.12.2` and does not contain the check for apiVersion.  If you can upgrade to the latest version and then retest it should work as expected?

**Comment by avinashkumar1289** [comment]
Yeah i also think so..Thanks
