### ISSUE TITLE
`helm upgrade --install --values -` not working when not installed

### ISSUE THREAD

**Issue by dplusic** [helm/helm#7574]
`helm upgrade --install --values -` not working when not installed.

Output of `echo "userkey: uservalue" | helm install --dry-run --debug --values - mysql stable/mysql 2>/dev/null | head -n 7`:
```
NAME: mysql
LAST DEPLOYED: Wed Feb 12 16:45:37 2020
NAMESPACE: default
STATUS: pending-install
REVISION: 1
USER-SUPPLIED VALUES:
userkey: uservalue
```

Output of `echo "userkey: uservalue" | helm upgrade --install --dry-run --debug --values - mysql stable/mysql 2>/dev/null | head -n 8`:
```
Release "mysql" does not exist. Installing it now.
NAME: mysql
LAST DEPLOYED: Wed Feb 12 16:46:45 2020
NAMESPACE: default
STATUS: pending-install
REVISION: 1
USER-SUPPLIED VALUES:
{}
```

Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.6"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T21:04:32Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
EKS

**Comment by hickeyma** [comment]
This is a reproducible bug with the chart mentioned in description or with the scaffold chart. The value is not being set as described on `upgrade --install`.

**Comment by anshulvermapatel** [comment]
$ helm version
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

It does work as I see here in my test machine.

> $ echo "userkey: uservalue" | helm upgrade --install --debug --values - mysql stable/mysql 2>/dev/null | head -n 8 
Release "mysql" does not exist. Installing it now.
NAME: mysql
LAST DEPLOYED: Tue Feb 18 22:44:14 2020
NAMESPACE: test
STATUS: deployed
REVISION: 1
USER-SUPPLIED VALUES:
{}

You have added `--dry-run` because of which it is not being installed.
Please remove the `--dry-run` option, it should get installed.

Please do let me know if I did not understand your correctly.

**Happy Helming**.

**Comment by bacongobbler** [comment]
@anshulvermapatel the title of the ticket is misleading. The issue being described is in relation to the `USER-SUPPLIED VALUES` field being null in certain cases (`helm upgrade --install` vs `helm install`).

**Comment by anshulvermapatel** [comment]
@bacongobbler , ohh, sorry, let me check this again.

**Comment by dplusic** [comment]
Duplicate of https://github.com/helm/helm/issues/7002
