### ISSUE TITLE
Helm 3 upgrade failure. If pre-hook fails, then change is not applied in the next upgrade

### ISSUE THREAD

**Issue by TomasKohout** [helm/helm#7577]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-21T22:17:28Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
`AWS`

---

Hi guys,

I think that this may be a correct behavior, but it feels strange to me.

We have a pre-hook which may fail. If it fails and some change occured in the upgrade (eg. Istio route weight change) and I run a new upgrade command then the changes from previous upgrade are not applied (route is not changed).

I feel that this may be an issue. What do you think?

**Comment by TomasKohout** [comment]
I think that maybe it could be related to me, because I've killed the upgrade once I knew it would fail anyway. So the secret ended in `pending-upgrade`. Could this be the reason of it?

**Comment by bacongobbler** [comment]
it's hard to determine the behaviour without a case to test against. Would you mind providing an example that we can use to demonstrate what you're seeing?

**Comment by TomasKohout** [comment]
I'm not able to reproduce this, so I'll close this. :)
