### ISSUE TITLE
undefined: newRootCmd

### ISSUE THREAD

**Issue by 13567436138** [helm/helm#7579]
Output of `helm version`:

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

# command-line-arguments
src\helm.sh\helm\v3\cmd\helm\helm.go:68:9: undefined: newRootCmd
src\helm.sh\helm\v3\cmd\helm\helm.go:77:8: undefined: pluginError

I use goland to run latest helm3 code ，got this error

**Comment by latermonk** [comment]
I  use git bash on windows, met the same error message:
go build -ldflags="-s -w" -o helm.exe cmd/helm/helm.go
# command-line-arguments
cmd\helm\helm.go:66:14: undefined: newRootCmd

**Comment by droppingin** [comment]
for someone who came here as me from google, here is the hint:
open the makefile and see how it should be executed.
`go build ./cmd/helm` workend on my windows pc
