### ISSUE TITLE
In what order are custom resources (in templates directory) deployed by Helm

### ISSUE THREAD

**Issue by vaishali-prophecy** [helm/helm#7580]
As we know that the install order of Kubernetes types is given by the enumeration InstallOrder in kind_sorter.go [Helm v2 source file](https://github.com/helm/helm/blob/9ad53aac42165a5fadc6c87be0dea6b115f93090/pkg/tiller/kind_sorter.go#L29)

Where do the custom resources defined by an operator fit in here and how the dependency among these resources is taken care of?

**Comment by mattfarina** [comment]
I am not entirely sure what you are asking about. If I get something wrong then more details might help.

CRDs in Helm v2 are installed using the `crd-install` hook. You can [read more about hooks in the v2 docs](https://v2.helm.sh/docs/developing_charts/#hooks). These are installed first. That is, before the manifests in the file you linked.

Does that help?

**Comment by vaishali-prophecy** [comment]
@mattfarina  Consider this yaml - https://github.com/banzaicloud/logging-operator/blob/master/charts/logging-demo/templates/output_elasticsearch.yaml

This deploys a resource of kind "Output" which is a custom resource. When does this get deployed?  If you see other files here - https://github.com/banzaicloud/logging-operator/blob/master/charts/logging-demo/templates, in what order would each of these resources be created?

**Comment by mattfarina** [comment]
Ah, I understand the question now. CRDs are installed prior to other resource. But, in what order are custom resources (CRs) installed compared to each other and everything else. This is a good question.

Kinds that are not in the InstallOrder come after those listed in the InstallOrder. You can see this in the tests for the kind sorter and in the comments in the sorter itself.

**Comment by technosophos** [comment]
I believe the question was answered, so am marking this as closed.
