### ISSUE TITLE
[feat] implement `make release-notes` feature to improve release process

### ISSUE THREAD

**Issue by paulczar** [helm/helm#7581]
In the release docs (https://helm.sh/docs/community/release_checklist/#8-write-the-release-notes) it talks about a bunch of copy pasting of the release notes with some inline substitutions and a command to load up the changelog.

There's no reason this couldn't be automated further to increase the reliability of the process and be less human error prone (copy/paste, etc).

**Comment by marckhouzam** [comment]
I'd like to suggest the creation of a "NEWS" file in the helm repo (or some other name like that).

With helm benefiting from such a strong community, I find that the person in charge of a release cannot always have all the info required to describe new features.

When a PR introduces a new feature, the author would add a short description to the NEWS file as part of the review.  This description would be aimed at users. The release notes could then be based on the accumulated descriptions from the NEWS file dive the last release.

Just a thought, but I've seen this work well in other projects.

**Comment by bridgetkromhout** [comment]
Instead of requiring each PR to edit the same NEWS file (with possible merge conflicts and inconsistent formatting/follow-through) we could look at doing notes generation more like k8s/k8s: https://github.com/kubernetes/release/blob/master/cmd/release-notes/README.md

**Comment by bacongobbler** [comment]
another tool that could be used for inspiration: https://github.com/deis/deisrel

**Comment by bacongobbler** [comment]
closed with #7636
