### ISSUE TITLE
Practical Contributing Guide

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#7585]
The current contributing guide provides technical details on what one needs to know. Especially if you think about PRs. What it doesn't do is deal with the human and community aspect of that.

For example, someone has been using Helm and wants to provide feedback on their experience. I know we have captured these through interviews in the past. Is that something that could be documented now?

We could write a guide on this kind of thing. Maybe it even lives on the Helm site. Just thinking out loud.

**Comment by mattfarina** [comment]
Some things that might help (from Helm dev call)....

* Some more documentation on the difference between the `cmd/helm` and `pkg` directories.
* Docs on the entry points for the application

**Comment by bacongobbler** [comment]
closing as stale.
