### ISSUE TITLE
Helm does not handle template errors

### ISSUE THREAD

**Issue by invidian** [helm/helm#7593]
### Steps to reproduce

```sh
helm create bar
echo '{{ .Values.bad.doh }}' > bar/templates/foo.yaml
helm template ./bar/
```
### Expected result
Helm should return error and exist with non-zero exit code, as in previous versions:
```
1 ✗ (43.5ms) 09:45:19 invidian@dellxps15mateusz /tmp $ ./foo/linux-amd64/helm version
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.6"}
0 ✓ (52.6ms) 09:47:39 invidian@dellxps15mateusz /tmp $ ./foo/linux-amd64/helm template ./bar/
Error: template: bar/templates/foo.yaml:1:10: executing "bar/templates/foo.yaml" at <.Values.bad.doh>: nil pointer evaluating interface {}.doh
1 ✗ (52.0ms) 09:47:41 invidian@dellxps15mateusz /tmp $
```

### Actual output
Helm does not print any warning and exits gracefully:
```
1 ✗ (52.0ms) 09:47:41 invidian@dellxps15mateusz /tmp $ helm version
version.BuildInfo{Version:"v3.1.0", GitCommit:"b29d20baf09943e134c2fa5e1e1cab3bf93315fa", GitTreeState:"clean", GoVersion:"go1.13.7"}
0 ✓ (49.1ms) 09:47:53 invidian@dellxps15mateusz /tmp $ helm template ./bar/

0 ✓ (49.6ms) 09:47:55 invidian@dellxps15mateusz /tmp $
```

Output of `helm version`:
```
version.BuildInfo{Version:"v3.1.0", GitCommit:"b29d20baf09943e134c2fa5e1e1cab3bf93315fa", GitTreeState:"clean", GoVersion:"go1.13.7"}
```

**Comment by invidian** [comment]
From bisecting, it seems to be caused by https://github.com/helm/helm/commit/8e088fc4a2a616354872b21d9ceb84e9d55a40de.

**Comment by hickeyma** [comment]
@invidian Looking at this I am not fully understanding why `foo` chart is created but you are creating a template in `bar`. Maybe you could explain this to better understand the issue.

FYI, I tested as follows with the latest in master:

```console
$ helm2 create chrt-7593
Creating chrt-7593

$ echo '{{ .Values.bad.doh }}' > chrt-7593/templates/foo.yaml

$ cat chrt-7593/templates/foo.yaml
{{ .Values.bad.doh }}

$ helm template chrt-7593 -s ./templates/foo.yaml 
Error: template: chrt-7593/templates/foo.yaml:1:10: executing "chrt-7593/templates/foo.yaml" at <.Values.bad.doh>: nil pointer evaluating interface {}.doh

$ helm template chrt-7593 chrt-7593/
Error: template: chrt-7593/templates/foo.yaml:1:10: executing "chrt-7593/templates/foo.yaml" at <.Values.bad.doh>: nil pointer evaluating interface {}.doh
```

**Comment by invidian** [comment]
>@invidian Looking at this I am not fully understanding why foo chart is created but you are creating a template in bar. Maybe you could explain this to better understand the issue.

Oops, it's a typo. My intention was of course to create chart `bar`. Fixed now.

**Comment by invidian** [comment]
@hickeyma I can't reproduce the commands you posted either. Why do you use `helm` and `helm2` binaries? Can you post output of `version` subcommand for both binaries?

**Comment by hickeyma** [comment]
@invidian Cab you see any differences between our test (bar the output)?

**Comment by hickeyma** [comment]
Good catch.  I am running different versions of Helm on a system.

I can reproduce this now when I run the latest Helm version from master (was running old version in previous comment):

```console
$ helm version
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

$ helm template chrt-7593 chrt-7593/
Error: template: chrt-7593/templates/foo.yaml:1:10: executing "chrt-7593/templates/foo.yaml" at <.Values.bad.doh>: nil pointer evaluating interface {}.doh

$ helm3 version
version.BuildInfo{Version:"v3.1+unreleased", GitCommit:"722042e85256dfded5d80c5fa29ed252c433cd5b", GitTreeState:"clean", GoVersion:"go1.13.4"}

$ helm3 template chrt-7593 chrt-7593/

```

Setting this as a bug.

**Comment by hickeyma** [comment]
Working on a fix. Will push when ready.

**Comment by hickeyma** [comment]
@invidian PR #7596 ready for review

**Comment by hickeyma** [comment]
Closed as PR #7596. Try it out @invidian and see if it works for you. Thanks for finding this bug.

**Comment by invidian** [comment]
It works well now, thanks @hickeyma for fixing it quickly! When do you plan next release, which will include this fix?

**Comment by hickeyma** [comment]
@invidian Not sure but will discuss it this week with other maintainers.
