### ISSUE TITLE
[help] passing env variable to container.

### ISSUE THREAD

**Issue by fanlix** [helm/helm#7610]
need help, 
how can i pass an env varialbe directly from helm cmdline to pod? 
or not supported?

and this variable not pre-defined in charts/deployment.yaml.

from cmdline (or else):
`helm install abc xxx/abc --set VAR=123`
`helm install abc xxx/abc --set env.VAR=123`

result:
```
deployment.template.container:
env:
  -- name: VAR
      value: 123
```

**Comment by pho-enix** [comment]
Usually there is a `env:` section in Kubernetes Deployments, etc.

For those to be accessible and changeable the Chart has to support that.

An example can be found here:
https://github.com/helm/charts/blob/master/stable/nginx-ingress/templates/controller-deployment.yaml#L137

You can then add additional environment variables with: `controller.extraEnvs`.

**Comment by fanlix** [comment]
ok, thanks @pho-enix. I understand now:
- There is no official helm method to pass env.variables to container directly.
- And the best practice is: chart writers should/may put an extraEnvs in chart.deployment.container.env,  just in case.

but unluckily, the chart i want to use does not support this.

Maybe, this should become a helm builtin feature, for exposing container env outside.
We cannot expect chart makers copy-paste all container options.

**Comment by fanlix** [comment]
for future users come here,
- pull the chart, edit templates/deployment.yaml
  - add the variable you need.
  - or add a extra turnnel, like @pho-enix 's advise.

**Comment by mdgreenwald** [comment]
Use double dollar signs:
```yaml
var: $$VAR_HERE
```
