### ISSUE TITLE
having issue with hosted chartmuseum

### ISSUE THREAD

**Issue by venkatesh-phenompeople** [helm/helm#7615]
Output of `helm version`:
v3.1.0
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-21T22:17:28Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS

I have hosted a private chartmuseum repository and I have uploaded a package to the repository.
But whe
![Screenshot from 2020-02-18 13-59-46](https://user-images.githubusercontent.com/60699852/74717770-f936ba80-5256-11ea-82e8-28940a35d130.png)
n I try to install the same from hosted chartmuseum repository it is getting failed.
Error: no objects visited

**Comment by hickeyma** [comment]
Hey @jdolitsky. Is this a Helm or ChartMuseum issue?

**Comment by venkatesh-phenompeople** [comment]
@jdolitsky  it looks like combination of both I have raised an issue in chartmuseum repo as well can you please help me in fixing the same.

Duplicate Issue Url:
https://github.com/helm/chartmuseum/issues/312

**Comment by hickeyma** [comment]
@venkatesh-phenompeople Why have you raised the same issue in both repos?

**Comment by venkatesh-phenompeople** [comment]
@hickeyma  I mean I didn't knew under which bucket this issue would go that's why I tried to raise on both issue lists.

**Comment by hickeyma** [comment]
Ok, going to close this in favour of defect in ChartMuseum. We can re-open of need be.
