### ISSUE TITLE
helm-3.1.0 ls -A shows nothing if (at least) one namespace with releases exists with no permissions to read secrets

### ISSUE THREAD

**Issue by stefanandres** [helm/helm#7616]
Output of `kubectl version`:
```
 $ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:08:14Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

```
$ helm version
version.BuildInfo{Version:"v3.1.0", GitCommit:"b29d20baf09943e134c2fa5e1e1cab3bf93315fa", GitTreeState:"clean", GoVersion:"go1.13.8"}
$ helm ls -A
NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART	APP VERSION
$ helm ls -n appleid
NAME   	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART        	APP VERSION
appleid	appleid  	8       	2020-02-17 10:57:54.260458196 +0000 UTC	deployed	appleid-1.0.0	1.0
```

We have clusters with multiple namespaces.
This user only read secrets in the appleid namespace, but no others. This seems to create the issue that `helm ls -A` does not even show the helm releases of the namepace that the user has access to.

**Comment by hickeyma** [comment]
@stefanandres what does `helm ls` return?

**Comment by stefanandres** [comment]
@hickeyma This depends on the current context of kubectl.

* kubens appleid && helm ls
  * appleid release is returned
* kubens appleid && helm ls -A
  * nothing is returned (this should not happen)
* kubens <other_ns> && helm ls
  * nothing is returned (as expected)

**Comment by hickeyma** [comment]
@stefanandres yes if not specified with flags in the command, Helm will use kubeconfig file and context.

I have tried to reproduce this as follows:

```console
$ helm create chrt-7616
Creating chrt-7616

$ helm install chrt-7616 chrt-7616
NAME: chrt-7616
LAST DEPLOYED: Tue Feb 18 14:21:48 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=chrt-7616,app.kubernetes.io/instance=chrt-7616" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace default port-forward $POD_NAME 8080:80

$ kubectl create ns test
namespace/test created

$ helm install chrt-7616 chrt-7616 -n test
NAME: chrt-7616
LAST DEPLOYED: Tue Feb 18 14:23:51 2020
NAMESPACE: test
STATUS: deployed
REVISION: 1
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace test -l "app.kubernetes.io/name=chrt-7616,app.kubernetes.io/instance=chrt-7616" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace test port-forward $POD_NAME 8080:80

$ helm ls -A
NAME     	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART          	APP VERSION
chrt-7616	default  	1       	2020-02-18 14:21:48.950349735 +0000 UTC	deployed	chrt-7616-0.1.0	1.16.0     
chrt-7616	test     	1       	2020-02-18 14:23:51.364884903 +0000 UTC	deployed	chrt-7616-0.1.0	1.16.0     
```

I am using the latest version of Helm (from master).

It might be worth checking your kube context to make sure it is not looking at different cluster?

**Comment by stefanandres** [comment]
Thank you for debugging. Did you also reproduce to have a user that has only access to *some* namespaces? With cluster-admin permission I can also see all releases, but users with restrictions do not.

**Comment by hickeyma** [comment]
RBAC will come into play so depends if the user has access to the namespace, as you specified above. In my example, I was using cluster-admin privileges. If you don't have the rights for a namespace, then you won't see the releases in that namespaces. It differs from Helm 2 when it was just the Tiller namespaces the releases were stored in.

Some details on this in the Helm docs: https://helm.sh/docs/topics/rbac/

**Comment by stefanandres** [comment]
As user I'd expect `helm ls -A` to show all releases from all namespaces that the user has access to. Am I wrong with this assumption?

**Comment by hickeyma** [comment]
It should work that way.  The `helm ls` output should be similar to this output (when run by the user) except the release versions are summarised into the release:
`kubectl get secret --all-namespaces -l "owner=helm"`

**Comment by stefanandres** [comment]
Ah, this brings us closer to the problem.

```
kubectl get secret --all-namespaces -l "owner=helm"
Error from server (Forbidden): secrets is forbidden: User "MYUSERNAME" cannot list resource "secrets" in API group "" at the cluster scope
```

Kubernetes seems to use cluster scope secret viewing - which the user is not allowed - for this command, even though namespace scoped secret getting would actually work.

**Comment by hickeyma** [comment]
I agree @stefanandres. The command when not scoped to do so, should return an error informing the user that it doesn't have required access.

Thanks for finding this bug. If you are interested feel free to push a fix.

**Comment by hickeyma** [comment]
Thanks @sshukun for the fix in #7464 

@stefanandres Can you try it out and see if it fixes the issue?

**Comment by stefanandres** [comment]
Yes, this throws the correct message now. But sad that it it does not show the releases the user has access to. I guess they'll have to loop over the namespaces then.

**Comment by hickeyma** [comment]
@stefanandres I think the idea here is that the user does not have access to all namespaces. The user should therefore be checking the namespaces they have access to.

**Comment by stefanandres** [comment]
Yeah, from a technical point of view I totally understand this :)
