### ISSUE TITLE
tiller: failed to prepare update, Could not get apiVersions from Kubernetes: unable to retrieve the complete list of server API's: admissionregistration.k8s.io/v1alpha1: the server could not find the requested resource

### ISSUE THREAD

**Issue by steve19922** [helm/helm#7621]
Output of `helm version`:
"v2.15.1"

Output of `kubectl version`:

version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2" } 

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS version: 1.14.8; after upgrading to this version, this issue appeared.

Steps to reproduce:
helm upgrade --install xxxx --force

This results in : 
failed update prepare step: a release named xxxx is in use, cannot re-use a name that is still in use error at helm.

Steps tried:
-deploy in different namespace
-purge the release 
-tried with helm 2.16.3 and 2.14.0 - still the same error.

What seemed to work is helm 2.14.3.

**Comment by prateek1192** [comment]
I see a similar kind of issue

**Comment by bacongobbler** [comment]
Can you demonstrate your issue with an example? It's unclear how to reproduce the issue here. Uninstalling a chart with `helm delete --purge` allows me to re-use the name.

**Comment by steve19922** [comment]
For anyone encountering this, I figure out the issue. During the cluster upgrade from 1.13.x to 1.14.x AKS didn't restart it's api server, therefore this alpha admission registration was not part of 1.14. The fix is to delete the unused api.
