### ISSUE TITLE
Verify chart digest on download if possible

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#7623]
`index.yaml` files provide a `digest` with a sha256 hash of the chart archive. Packages in OCI registries are content addressable (meaning we have a hash). When `helm pull` does it's work it should be possible to check what was downloaded against the hash for the version for the cases where a hash is available.

Thoughts?

**Comment by jdolitsky** [comment]
> it should be possible to check what was downloaded against the hash for the version for the cases where a hash is available

Just want to clairfy what you mean by this. The hash is available where? The sha of the chart tarball blob?

**Comment by Jean-Baptiste-Lasselle** [comment]
> of

Hi kind of smiling here because : 
* I don't think it is what is the issuer talking about
* I have the same problem that seem to you have :smile: : sha256sums of downloadable released binaries are corrupted or not managed : 

```bash
jbl@poste-devops-jbl-16gbram:~/siecle$ curl -LO https://get.helm.sh/helm-v2.16.5-linux-amd64.tar.gz.sha256
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    65  100    65    0     0     86      0 --:--:-- --:--:-- --:--:--    86
jbl@poste-devops-jbl-16gbram:~/siecle$ cat helm-v2.16.5-linux-amd64.tar.gz.sha256 
7cd54f56f787d62fd7311d5ae2c26e31310d37d27e3622014e5c769bec008cab
jbl@poste-devops-jbl-16gbram:~/siecle$ cat checksumsjbl 
7cd54f56f787d62fd7311d5ae2c26e31310d37d27e3622014e5c769bec008cab ./helm-v2.16.5-linux-amd64.tar.gz.sha256
jbl@poste-devops-jbl-16gbram:~/siecle$ sha256sum 
^C
jbl@poste-devops-jbl-16gbram:~/siecle$ sha256sum -c ./helm-v2.16.5-linux-amd64.tar.gz
sha256sum: ./helm-v2.16.5-linux-amd64.tar.gz: no properly formatted SHA256 checksum lines found
jbl@poste-devops-jbl-16gbram:~/siecle$ sha256sum -c ./checksumsjbl 
./helm-v2.16.5-linux-amd64.tar.gz.sha256: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
jbl@poste-devops-jbl-16gbram:~/siecle$ ls -allg
total 24708
drwxr-xr-x  2 jbl     4096 Mar 29 17:43 .
drwxr-xr-x 97 jbl    12288 Mar 29 17:36 ..
-rw-r--r--  1 jbl      106 Mar 29 17:41 checksumsjbl
-rw-r--r--  1 jbl 25273394 Mar 29 17:41 helm-v2.16.5-linux-amd64.tar.gz
-rw-r--r--  1 jbl       65 Mar 29 17:43 helm-v2.16.5-linux-amd64.tar.gz.sha256
jbl@poste-devops-jbl-16gbram:~/siecle$ 
```

So I opened an issue : https://github.com/helm/helm/issues/7838

**Comment by TBBle** [comment]
@jdolitsky The SHA is available in the index.yaml of a [Helm chart repository](https://helm.sh/docs/topics/chart_repository/), and in the [metadata of an OCI registry](https://helm.sh/docs/topics/registries/).

@Jean-Baptiste-Lasselle Based on this and #7838, I think you're looking at a different issue, about the digest of a binary release of Helm itself, not of the charts?

**Comment by TBBle** [comment]
@bacongobbler #8254 takes care of testing the repository case, but a cursory search with GitHub suggests that apart from unit tests, the SHA digest in the index.yaml is never verified in Helm, as nothing accesses the `Digest` member of `ChartVersion` that I can see. Provenance checking doesn't seem to use it, as it relies on testing the .prov against the downloaded file itself, and index.yaml is no longer involved at that point.

**Comment by TBBle** [comment]
Repeating my earlier GitHub-based search, nothing appears to be accessing `ChartVersion`'s `Digest` field, so I believe we are not checking the digest for a downloaded chart against the digest from the index.yaml in the chart repository.

There's also [this TODO](https://github.com/helm/helm/blob/467bd49bb0cb0d613e802c738a0e38225eec054a/pkg/repo/chartrepo.go#L192), when adding a chart to index.yaml, which is the closest we come to ever caring about the Digest field for flows like `helm install`.
> // TODO: If a chart exists, but has a different Digest, should we error?

Separately, I think the answer to the TODO is probably "No". Replacing a chart in-place is not kind to users, but shouldn't be a tooling failure. Perhaps logging a warning? I suspect there's a bug here, as if the chart already existed in the index.yaml, it won't be re-added here, which means the Digest field won't be updated. Since we never _check_ the index.yaml's Digest field, no one has ever noticed this.

**Comment by TBBle** [comment]
Thank you github-actions, but this issue still exists.

**Comment by TBBle** [comment]
Thank you github-actions, but this issue still exists.

**Comment by TBBle** [comment]
Thank you github-actions, but this issue still exists.

**Comment by bacongobbler** [comment]
This may be addressed by the reference implementation available in [HIP 13](https://github.com/helm/community/pull/185), which proposes a new chart cache mechanism.

**Comment by TBBle** [comment]
I finally got around to _skimming_ [HIP 13](https://github.com/helm/community/pull/185), and in its current state, I think it indeed intrinsically resolves this issue by making all charts (whether from OCI registry and Helm Chart Repository) go through a content-addressable cache, so hash mismatches from the index.yaml will be detected as correctness failures when populating into or consuming from the cache.

That would make the possible index.yaml update issue I speculated on [above](https://github.com/helm/helm/issues/7623#issuecomment-695946214) quite visible though, assuming I analysed it correctly, but better to have a visible bug failing correctness checks than a silent bug giving insidious behaviour failures.
