### ISSUE TITLE
Fix output when --verify flag used

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#7624]
Output of `helm version`: 3.1.0

Here's some example output...
```
$ helm pull --verify --keyring foo.pgp demo-repo/foo
Verification: &{0xc0008c80a0 sha256:f8a4e6e3ebf8a3fac95396b698f5517d43e0f5275bac3c484b6f38428b90b578 foo-0.1.0.tgz}
```

Don't think this is what we expect to see.

**Comment by mattfarina** [comment]
Doing more digging I found that the UI output pattern was explicitly put in this way. It looks like it was via the commit 593718d74910c6d180b05b52e97cc20c8bb18d66. Later commits around this just updated it or added tests to show it.

Because this is a UI change it would be considered breaking to change this. We might need to put this off to Helm v4. Unless this was an unintended bug that's lasted a long time. Paging @technosophos 

Prior to this change more useful information, such as who signed, was provided.

**Comment by mattfarina** [comment]
Doing more research... Here's how it works when things fail...

The case where the sha's do not match
```
$ helm pull --verify --keyring foo.pgp demo-repo/foo
Error: sha256 sum does not match for foo-0.1.0.tgz: "sha256:892f11be3dfbe09079da5e7bdfb23701e8df8b6919a0cd39c7e3fff51ab4a86c" != "sha256:a5611acf74b0372a36de0a49cb17985fdb1260b5dd4ed25fbfe3bb55a10239f6"
```

When the key is not in the keychain used for verification...
```
$ helm pull --verify --keyring foo2.pgp demo-repo/foo
Error: openpgp: signature made by unknown entity
```

And, when the signature is from some known and the hash listed matches the file but the sig is for something else...
```
$ helm pull --verify --keyring foo.pgp demo-repo/foo
Error: openpgp: invalid signature: hash tag doesn't match
```

The issue is with the information when the verification passes.

**Comment by technosophos** [comment]
This was most definitely a bug that I introduced.
