### ISSUE TITLE
Global context not reachable from template

### ISSUE THREAD

**Issue by xdsxc** [helm/helm#7626]
Output of `helm version`:
`version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.7"}`
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-19T13:57:45Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
N/A (on-prem)

The global context does not seem reachable from a template definition when the root context is not passed in.

For example, given this template in `_helpers.tpl`
```
{{- define "my_template" -}}
{{ $.Release.Name }}-foo
{{- end -}}
```

Try doing something like
```
{{ $dummyCtx := dict "k1" "v1" }}
{{ include "my_template" $dummyCtx }}
```

Results in the following error
`executing "my_template" at <$.Release.Name>: nil pointer evaluating interface {}.Name`

**Comment by bacongobbler** [comment]
The second argument for `include` is the scope. In your example, you passed the root context as `$dummyCtx`. In other words, your function is trying to evaluate `$dummyCtx.Release.Name`.

If you want the root context to be passed along to the function, use `{{ include "my_template" $ }}`.

https://helm.sh/docs/howto/charts_tips_and_tricks/#using-the-include-function

Does that help?

**Comment by xdsxc** [comment]
Yeah that would work. I was expecting the behavior to be accessible within the helper though given this documentation: https://helm.sh/docs/chart_template_guide/variables/

Specifically

> Variables are normally not “global”. They are scoped to the block in which they are declared. Earlier, we assigned $relname in the top level of the template. That variable will be in scope for the entire template. But in our last example, $key and $val will only be in scope inside of the {{ range... }}{{ end }} block.
However, there is one variable that is always global - $ - this variable will always point to the root context. This can be very useful when you are looping in a range need to know the chart’s release name.

The issue came around because I have a helper that is used several times with different contexts that have the same structure (e.g. `.secrets` `.default` and `.override`). So I'll call this helper in many locations with a different context. However, the helper itself needs to know the release name and I was hoping that I could reference it with `$`. 

My workaround so far is this (adapted the example above):

```
{{ $ctx := dict "k1" "v1" }}
{{ $ctx = merge $ctx $ }}
{{ include "my_template" $ctx
```

**Comment by bacongobbler** [comment]
Fair enough. The behaviour of function blocks are slightly different than the root context of the template. When you call a function, it is invoked with its own root context passed along, so the usual rule of "$ == root context" doesn't apply in that particular case.

Closing as answered. Let us know if you have further questions.

**Comment by tduverge** [comment]
Hi,

I had a similar problem and solving it with something like :

```
{{- define "my_template" -}}
{{ "{{" }} $.Release.Name {{ "}}" }}-foo
{{- end -}}
```

```
{{ $dummyCtx := dict "k1" "v1" }}
{{ tpl (include "my_template" $dummyCtx) $ }}
```

**Comment by ayushin** [comment]
This is quite ugly and undocumented. Why not keep global context global everywhere in the chart?
