### ISSUE TITLE
helm upgrade --atomic etcdserver: leader changed

### ISSUE THREAD

**Issue by Antiarchitect** [helm/helm#7637]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.1.0", GitCommit:"b29d20baf09943e134c2fa5e1e1cab3bf93315fa", GitTreeState:"clean", GoVersion:"go1.13.7"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"be3d344ed06bff7a4fc60656200a93c74f31f9a4", GitTreeState:"clean", BuildDate:"2020-02-11T19:34:02Z", GoVersion:"go1.13.
6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"be3d344ed06bff7a4fc60656200a93c74f31f9a4", GitTreeState:"clean", BuildDate:"2020-02-11T19:24:46Z", GoVersion:"go1.13.
6", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): `Baremetal`

Problem:
```
uninstall.go:129: [debug] purge requested for xxx
Error: release xxx failed, and has been uninstalled due to atomic being set: rpc error: code = Unavailable desc = etcdserver: leader changed
helm.go:75: [debug] rpc error: code = Unavailable desc = etcdserver: leader changed
release xxx failed, and has been uninstalled due to atomic being set
```

I think it started somewhere between helm 3.0.2 and 3.1.0

**Comment by bacongobbler** [comment]
An error from etcd would indicate an issue with your Kubernetes cluster. Can you check your cluster’s health and see what state your etcd backend is in?

To be clear: this is an error coming from Kubernetes directly. Helm does not communicate with etcd.

**Comment by Antiarchitect** [comment]
I suppose that this error comes directly from K8s. But changing the leader should not affect the deployment process, am I right?

**Comment by technosophos** [comment]
The error comes from Kubernetes. So we don't know why Kubernetes errored out because of a leader change -- only that it did, and that the error prevented Helm from completing its operation.

**Comment by kabakaev** [comment]
Would it make sense to retry kubernetes API operations in case they failed? 

Usually, network APIs are designed to fail. Depending on the HTTP response code, it's a job of a client to [retry a few times with a delay](https://cloud.google.com/storage/docs/exponential-backoff).

I'd suggest to retry at least on HTTP 409 and 5xx. But it may worth to retry on all HTTP codes higher than 404 or all kubernetes requests.

HDYT, @technosophos?

**Comment by pauljamm** [comment]
We have the same issue.

It's kinda strange to rollback release due etcd leader change.
Helm should retry in case of error. I think kubectl rollout status does so.

**Comment by JohnJAS** [comment]
We've got the same issue while using `--wait` option. Once helm calling k8s api failed, the `helm upgrade --wait` will exit. I suggest to have some re-trys while helm calling the k8s apis

wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready

Error: etcdserver: leader changed
helm.go:94: [debug] etcdserver: leader changed
2021-03-18T04:58:52.564831549+08:00 DEBUG exit_code: 1

**Comment by dims** [comment]
related to https://github.com/helm/helm/issues/9502
