### ISSUE TITLE
How to handle an object created by operator

### ISSUE THREAD

**Issue by woohhan** [helm/helm#7642]
Output of `helm version`:
version.BuildInfo{Version:"v3.1.0", GitCommit:"b29d20baf09943e134c2fa5e1e1cab3bf93315fa", GitTreeState:"clean", GoVersion:"go1.13.7"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Minikube

I'm curious how to handle an object which is created by an operator. My application is installed with helm, and after that, the application deploys other deployments itself. I'd like to wait for these deployments, however, `helm install --wait` command does not wait for my deployment because they don't know the deployment. How can I wait for this deployment? Thanks.

**Comment by bacongobbler** [comment]
I'm not sure there is a reasonable way Helm can be made aware of this resource and wait for its readiness. Because Helm only knows about objects it creates (and the children of those resources, i.e. Pods created by a ReplicaSet), I'm not sure there's a way this can reasonably achieved given the current architecture.

Have you had a chance to look at how `--wait` is implemented?

**Comment by bacongobbler** [comment]
for reference: https://github.com/helm/helm/blob/master/pkg/kube/wait.go

**Comment by woohhan** [comment]
> I'm not sure there is a reasonable way Helm can be made aware of this resource and wait for its readiness. Because Helm only knows about objects it creates (and the children of those resources, i.e. Pods created by a ReplicaSet), I'm not sure there's a way this can reasonably achieved given the current architecture.
> 
> Have you had a chance to look at how `--wait` is implemented?

Thanks for your reply! I took a quick check for your reference, and I agree with you there's no way to helm knows what he did not make. But still, many operators create their own objects. For example, in [rook/rook](https://github.com/rook/rook) project, there's an operator that deploys a ceph cluster, and toolbox to control the ceph cluster. But the toolbox should be deployed after the ceph cluster is come up. In the current helm chart, there's no way to wait for this. Is it a matter of changing the implementation of the operator itself? or I think we can add some hook (not a yaml) but a shell file or just executing some binaries.

**Comment by R-omk** [comment]
@woohhan  You can try using hooks (post-upgrade post-install ) for this.

**Comment by woohhan** [comment]
> @woohhan You can try using hooks (post-upgrade post-install ) for this.

Thanks for the suggestion, I found some example that executes a kubectl command in a container. however, is it the only solution for this? I'm not comfortable with executing a kubectl command in a container...
