### ISSUE TITLE
Ignore a subchart during helm install

### ISSUE THREAD

**Issue by tutaidalal** [helm/helm#7650]
I have a composite helm package which internally deploy 4 sub helm. For example I have a video management system, where recorder, streamer, storage manager, event notification... etc multiple helm. For a particular requirement  I don't need the event notification utility to be installed. So customer/deployment engineer should feel very easy to deploy the entire system without a particular sub helm. Could someone please help me the best approach to achieve the feature ?  

**Output of `helm version`:**

Client: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}

**Output of `kubectl version`:**

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
K8S on ubuntu.

**Comment by R-omk** [comment]
Maybe this is what you need.
https://helm.sh/docs/topics/charts/#tags-and-condition-fields-in-dependencies

https://github.com/helm/helm/issues/1585

**Comment by mattfarina** [comment]
@tutaidalal The documentation @R-omk highlights is what I would start with. Does that work?

**Comment by tutaidalal** [comment]
> 
> 
> Maybe this is what you need.
> https://helm.sh/docs/topics/charts/#tags-and-condition-fields-in-dependencies
> 
> #1585

In my case I do not have any option to change or build the master helm. It is being suplied by different vendor and I only use the below command to install. There is no such condition provided .

Command I run:

 helm upgrade --install  <release-name> <helm-repo> --namespace <my namespace> -f values.yaml --devel

I have the sample values.yaml where i do not see  any such condition.

I guess you are expecting something like - 

dependencies:
      - name: subchart1
        repository: http://localhost:10191
        version: 0.1.0
        condition: subchart1.enabled, global.subchart1.enabled


is there any command or way to skip some sub-chart during installation/upgrade ?

**Comment by technosophos** [comment]
No, there is no such command. If the chart author has not marked a subchart as optional, we assume it is required.
