### ISSUE TITLE
When trying to upgrade a release with no changes, the revision number is incremented

### ISSUE THREAD

**Issue by nij4t** [helm/helm#7652]
Output of `helm version`:
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:09:21Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by mattfarina** [comment]
@nij4t What would you expect to happen here? I understand the part where the release is not incremented but there needs to be messaging around it and the rest of the user experience needs to be taken into account.

**Comment by bacongobbler** [comment]
This is partially intentional behaviour. As part of helm 3, we now take into consideration the live state as part of the release. If someone were to `kubectl edit` a bunch of live resources and choose to revert back to their original state, they can do so now with `helm rollback‘ or `helm upgrade`. The chart might’ve never changed, but it’s possible that a patch was generated with the three-way merge patch.

**Comment by nij4t** [comment]
Helm v3 introduced a nice feature of 3 way merge, which works well when doing upgrade/rollback. However, when  trying to upgrade/rollback using `--dry-run` flag, the life state of the release is not being taken into account, hence no release needed to be done, even if the state of resources are changed.

That creates difficulties for GitOps systems that rely upon helm. For example, fluxcd's *helm-operator* performs dry-run upgrade before rolling out new release. This way the release is out only when the release in fluxcd's CRD and cluster's latest release differ. So, if, let's say, someone changed the image of a deployment, it's there until the release itself is not changed, which makes the GitOps implementation incomplete

**Comment by bacongobbler** [comment]
The dry-run flag shouldn’t be recording a release in the cluster. Can you demonstrate an example?

**Comment by nij4t** [comment]
> The dry-run flag shouldn’t be recording a release in the cluster. Can you demonstrate an example?

It does not

**Comment by bacongobbler** [comment]
Okay. I'm a little confused by your previous statement...

> when trying to upgrade/rollback using `--dry-run` flag, the life state of the release is not being taken into account, hence no release needed to be done, even if the state of resources are changed.

Specifically this line:

> hence no release needed to be done

Which implies that the `--dry-run` flag records a release.

Would you mind demonstrating an example of what you are trying to achieve?

**Comment by nij4t** [comment]
@bacongobbler, let's assume that I have 3 relicas of a deployment in the latest release. I changed the replicaCount of a deployment to one using kubectl. Then when preforming `helm diff upgrade`<sup>1</sup> using the same values (that had the replicaCount of 3) the output was empty. Which makes sense when comparing current and latest releases. And which is bad in the world of GitOps.

<sup>1</sup>Helm Diff - Community plugin that requires helm ^3.1.0

**Comment by nij4t** [comment]
> Okay. I'm a little confused by your previous statement...
> 
> > when trying to upgrade/rollback using `--dry-run` flag, the life state of the release is not being taken into account, hence no release needed to be done, even if the state of resources are changed.
> 
> Specifically this line:
> 
> > hence no release needed to be done
> 
> Which implies that the `--dry-run` flag records a release.
> 
> Would you mind demonstrating an example of what you are trying to achieve?

By that I mean that the *helm-operator* tries to do a dry-run upgrade first to check whether the release is needed to be rolled out. If it detects changes it does another upgrade but this time without dry-run which records a release.

**Comment by nij4t** [comment]
@bacongobbler, how would you know whether a rollback is needed without doing the rollback? Now imagine that an automated systems does those checks within defined interval before committing any action. This is needed to eliminate the state drifts by resetting the state to its release declaration.

**Comment by bacongobbler** [comment]
> how would you know whether a rollback is needed without doing the rollback?

Helm has logic within it to determine if no update is required or not: https://github.com/helm/helm/blob/7f3339cb4eec9800cb09a46512050fb509480f7e/pkg/kube/client.go#L402-L410

> Then when preforming helm diff upgrade1 using the same values (that had the replicaCount of 3) the output was empty.

It's important to keep in mind that helm-diff was created with the intent of comparing the changes between the chart installed in the cluster and what you are proposing to change. It does not include the live state into its consideration.

If you need to consider the live state, old and new chart, that sounds like either a new feature for helm-diff, or perhaps another tool (such as the gitops tool you are alluding to).

**Comment by nij4t** [comment]
@bacongobbler, thank you for clarification! 
My concern is that the gitops tool [uses helm package](https://github.com/fluxcd/helm-operator/blob/95c993a515059790a422a49155bd643baae455ab/pkg/helm/v3/upgrade.go#L41-L43) to do [upgrades with dry-run](https://github.com/fluxcd/helm-operator/blob/95c993a515059790a422a49155bd643baae455ab/pkg/release/release.go#L361-L366) and yet the live state is not considered anyway.

**Comment by bacongobbler** [comment]
it looks like it's only performing a two-way diff. For a gitops tool, that may be their intention. Have you asked the authors of flux whether this was an intentional design decision or a bug? Either way it seems like there isn't anything actionable on our end here. It sounds more like a design question for flux.

**Comment by bacongobbler** [comment]
As I understand, the JSON patch is not something we record in the release, and that's intentional by design. Each upgrade's patch can change as the live objects are updated. It is up to the implementer (in this case flux) to compute the patch themselves. They have the tools required to do so, now they need to go and generate the patch :)

Here is how Helm generates the patch: https://github.com/helm/helm/blob/7fd30581b6455243e6508d50c978694c503bff70/pkg/kube/client.go#L340

Hope this helps!

**Comment by nij4t** [comment]
Thank you very much, @bacongobbler!
