### ISSUE TITLE
helm v3 cannot show pre-release info

### ISSUE THREAD

**Issue by jimmy-wei** [helm/helm#7658]
Output of `helm version`:

version.BuildInfo{Version:"v3.1.0", GitCommit:"b29d20baf09943e134c2fa5e1e1cab3bf93315fa", GitTreeState:"clean", GoVersion:"go1.13.7"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:23:21Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Rancher

`helm show` removed `--devel` flag in helm v3. `helm inspect` supported in helm v2.

Is it possible add it back in helm v3?

**Comment by mattfarina** [comment]
This was added to v2.16.0 right around the time v3.0.0 came out. This does need to be ported to v3. Thanks for catching it.

**Comment by hickeyma** [comment]
I can port this if that's ok?

**Comment by mattfarina** [comment]
@hickeyma sgtm

**Comment by hickeyma** [comment]
PR #7744 pushed.

**Comment by hickeyma** [comment]
PR #7744 merged.
