### ISSUE TITLE
  Error: Timeout: request did not complete within requested timeout 30s

### ISSUE THREAD

**Issue by jurgenweber** [helm/helm#7664]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:08:14Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"1bea6c00a7055edef03f1d4bb58b773fa8917f11", GitTreeState:"clean", BuildDate:"2020-02-11T20:05:26Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Secetel.ru

I am receiving this error:

```
  Error: Timeout: request did not complete within requested timeout 30s
```

every time I try to deploy my application. I can see no other signs, my application works on EKS and Alibaba k8s 1.14 without issue.

I have tried disabling as much as I can and I have disabled all hooks without any change in behaviour. You can see the new pods and deployments come up but after 30 seconds helm dies. Not sure what it is waiting for/timeing out on. `--timeout` is set to 300 seconds.

 I am super stuck. A have successfully installed a bunch of mainstream charts, like cert-manager, ingress-nginx, prometheus-operator without issue. My application is a lot simpler than all of those (its just a few deployments) and various bits and pieces. 

Any ideas?

**Comment by AlexsJones** [comment]
Have you tried looking at why the deployment is actually timing out?
This doesn't immediately indicate a problem with Helm at all.
Check your deployments have access to their charts, init containers are completing and operators are finishing.

Please post your rendered templates, some snippets of rollout status as well if you cannot proceed further with this issue.

**Comment by jurgenweber** [comment]
well, thats it.. Nothing is timing out.  I feel you implying that some resource has an issue?

All pods come up and are 'running'.
init pods work. All images download (hence, the pods are running).
Everything looks good and helm times out.

Checking other resources, ConfigMaps are there, Secrets are there. All in all it looks like the perfect release.

As mentioned, it works fine in other clusters but they are all 1.14.

**Comment by jurgenweber** [comment]
ok, soooo cloak and dagger:

```
  Warning  FailedScheduling  38s (x11 over 9m44s)  default-scheduler  0/2 nodes are available: 2 node(s) didn't match pod affinity/anti-affinity, 2 node(s) didn't satisfy existing pods anti-affinity rules.
```

so my hook to do my db migrations is in the same chart with the same name as the same label as the primary application and affinity rules are banging against each other. This only pop'd up because I disabled the ingresses as I noticed they were missing... and then I finally saw the db migration hook job coming up.... and then saw the error. :\ I replicated this a few times and confirmed the behaviour.

A better error could of helped here, even something as simple as 'hook failed' to give you an idea where the timeout is occuring. Thank you for the clues @AlexsJones .

**Comment by jurgenweber** [comment]
Where can I increase this timeout?
After turning all my parts back on, I now get:

```
  Error: UPGRADE FAILED: failed to create resource: Timeout: request did not complete within requested timeout 30s
```

I have `helm --timeout 300`...... this is clearly saying 30s.. Where can I increase this?

**Comment by hickeyma** [comment]
try `--timeout 30s`

**Comment by AlexsJones** [comment]
> Where can I increase this timeout?
> After turning all my parts back on, I now get:
> 
> ```
>   Error: UPGRADE FAILED: failed to create resource: Timeout: request did not complete within requested timeout 30s
> ```
> 
> I have `helm --timeout 300`...... this is clearly saying 30s.. Where can I increase this?

I think you're missing `300s`

Also enable verbosity to see what resource is failing to generate.

**Comment by jurgenweber** [comment]
in the end, this clusters API doesn't seem to be able to contact any admission or validating webhook... So I had the ingress validation webhook enabled and this was timing out.
