### ISSUE TITLE
Exclude Duplicates entry from values.yaml while creating k8s resource.

### ISSUE THREAD

**Issue by Mishra-Akash** [helm/helm#7666]
I need help where I can avoid duplicate from values.yaml.

My requirement is to take  input from user for port/protocol and create a network policy accordingly. I need to add a check too in my np.yaml to avoid  duplicate entry by user. 

Example from values.yaml 
```
   Ingress:
     ports:
      - protocol: TCP
       port: 10012
     - protocol: TCP
       port: 10012
```

If there is a duplicate input given by user as in above example, network policy resource must be created without duplicate entry.

Output of `helm version`:
Server: &version.Version{SemVer:"v2.14.2", GitCommit:"524294565799aba901a242fb7a12cef454c9cb10", GitTreeState:"clean"}

 kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-20T11:45:27Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-20T11:40:58Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Baremetal. OS is Sles 15

**Comment by mattfarina** [comment]
Have you tried the `uniq` template function? It performs a deep equal of values and can make a list unique.

**Comment by Mishra-Akash** [comment]
can u please share some reference link for uniq template function. I haven't got in Helm documentation.

**Comment by mattfarina** [comment]
https://masterminds.github.io/sprig/lists.html#uniq-mustuniq. The functions starting with `must` are only available in Helm v3.

**Comment by technosophos** [comment]
The question appears to have been answered. Marking closed.
