### ISSUE TITLE
Is there any list of exit codes from helm ?

### ISSUE THREAD

**Issue by przemolb** [helm/helm#7669]
We use internally helm v2 (still ...). Our internal requirement while developing any software is to  handle errors correctly (surprise ...). Is there any list of exit error codes from helm so I could handle them correctly ?

**Comment by bacongobbler** [comment]
As far as I understand, there are only two exit codes [cobra](https://github.com/spf13/cobra/) (and therefore helm) use as a convention:

- exit code "zero" for success
- exit code "non-zero" for failure

There are no specific exit error codes used by Helm. There are helpful error messages displayed on standard error output, however, and many projects interpret these errors to determine how to handle certain scenarios.

If you CTRL + F for `log.Fatal`, `fmt.Sprintf`, or `type Err` across the project, you should find the vast majority of custom error messages Helm produces. However, there are also error messages that are passed along from upstream dependencies, like Kubernetes. Those can be found looking for `return err` and the like.

Hope this helps!

**Comment by mattfarina** [comment]
This is a great question and raised some issues for me when I started poking at it.

First, the context... Exit codes can have special meanings, for example there is [a list of reserved ones for shell scripting](https://www.tldp.org/LDP/abs/html/exitcodes.html). In this example a 127 is for command not found.

Which leads me to my issue...
```
$ helm foobar
...
$ echo $?
0
```

A 0 exit code means the things worked. I think I found a bug (i'll file that elsewhere).

Helm itself does 2 things for error codes:

1. returns the exit code of the plugin if a plugin was executed
2. returns an exit code of 1 if there was an issue or a 0 if everything worked

**Comment by technosophos** [comment]
Closing, as the original question was answered

**Comment by davi5e** [comment]
Anyone knows what `-9` means?

Sometimes, `helm install` is failing with `-9` when I use it from inside the Kubernetes cluster...

This never happens in case I use Helm from a Bastion host or from my own machine...

**Comment by oscartrullols** [comment]
> Anyone knows what `-9` means?
> 
> Sometimes, `helm install` is failing with `-9` when I use it from inside the Kubernetes cluster...
> 
> This never happens in case I use Helm from a Bastion host or from my own machine...

I know it's an old thread but I hope it helps others that like me reach this Issue trying to understand why  are we getting this error.
In my case it was due to a lack of resources in the container where I was running helm, increasing these solved the issue.

**Comment by davi5e** [comment]
@oscartrullols makes sense, the same application that used to run `helm` from inside the cluster can't handle multiple `helm upgrades` at once.

Off topic: Is there a way to limit CPU/RAM usage using Helm CLI?

**Comment by benoittgt** [comment]
>In my case it was due to a lack of resources in the container where I was running helm, increasing these solved the issue.

We have this issue on two of our hosted deployment mechanism. 

> Off topic: Is there a way to limit CPU/RAM usage using Helm CLI?

I have the same question.
