### ISSUE TITLE
chart.lock not part of "helm package" tar

### ISSUE THREAD

**Issue by pintosh** [helm/helm#7670]
Output of `helm version`:
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-eks-1861c5", GitCommit:"1861c597586f84f1498a9f2151c78d8a6bf47814", GitTreeState:"clean", BuildDate:"2019-09-24T22:12:08Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  EKS

I switched to Helm 3.1.1 and moved my chart dependencies from requirements.yaml to Chart.yaml. When I do a "helm dep up", I see the Chart.lock being created but it isn't part of the "helm package " archive. With Helm 2.16, the requirements.lock was part of the tar.

Steps to reproduce:

1. Run helm dep up on a chart that has dependencies in Chart.yaml
2. Observe that a chart.lock has been generated.
3. Run "helm package"

Expected behavior: Chart.lock is part of the tar created by helm package

**Comment by bacongobbler** [comment]
in your Chart.yaml, what is the value of the `apiVersion` field? When migrating from requirements.yaml to Chart.yaml, did you make sure to update the field to `v2`?

**Comment by pintosh** [comment]
yes, apiVersion is set to v2.

contents of Chart.yaml

apiVersion: v2
appVersion: "1.0"
description: App Deploy
name: app-deploy
version: 0.1.0
dependencies:
- name: postgresql
  repository:  https://kubernetes-charts.storage.googleapis.com
  version: 8.1.4
  tags:
    - postgres
- name: nginx-ingress
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 1.29.1
  tags:
    - nginxIngress

contents of Chart.lock

dependencies:
- name: postgresql
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 8.1.4
- name: nginx-ingress
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 1.29.1
digest: sha256:6f8c29470ed5671ebb4e0ed772a7463988fb2dfe52ae9b9d27306e4ba84bd0bf
generated: "2020-02-24T14:00:10.751281522-05:00"

Run helm package, and noticed that Chart.lock isn't part of the package.

**Comment by mattfarina** [comment]
I just verified this on the tip of master. Thanks for catching it.

**Comment by pintosh** [comment]
The bigger issue seems to be that the Chart.lock ( or requirements.lock if apiVersion: v1 ) generated with Helm 3.1.1 does not have the "locked in" versions.

Chart.lock with Helm 3.1.1

`dependencies:
- name: nginx-ingress
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 1.29.0 - 1.29.99
digest: sha256:49dddfefca7fc07ac67b7eed2d55e029b6f5899c0e14fcf5a98f8d39df34d2c2
generated: "2020-02-25T06:55:09.224185875-08:00"`

requirements.lock with Helm 2.16

`dependencies:
- name: nginx-ingress
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 1.29.7
digest: sha256:bb954849f496c80418bcb567e1e1c70872dfd76eb0801012aeb44753431c75b9
generated: "2020-02-25T06:52:12.797241433-08:00"`
