### ISSUE TITLE
Helm returns 0 exit code when command not found

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#7671]
Output of `helm version`:
v3

Here's an example with 3.1.1...
```
$ helm foobar
...
$ echo $?
0
```

When a command isn't found that should return a non-zero exit code, right. [Shell scripting even has a special code for that case](https://www.tldp.org/LDP/abs/html/exitcodes.html).

**Comment by marckhouzam** [comment]
Duplicate of #6998 with PR awaiting review here #7040

**Comment by hickeyma** [comment]
Duplicate of #6998

**Comment by hickeyma** [comment]
Closing as a duplicate of #6998.
