### ISSUE TITLE
Annotation "helm.sh/resource-policy: keep" is ignored on helm upgrade

### ISSUE THREAD

**Issue by jgoeres** [helm/helm#7677]
I use the annotation "helm.sh/resource-policy": keep to protect some PVCs from deletion on helm uninstall, which works fine. Alas, on helm upgrade, the PVCs are deleted, taking my data with them.
Observed on Helm 3.0.3 and Helm 3.1.1.

This seems to be a regression, as I found this issue:
https://github.com/helm/helm/issues/3673

**Comment by mattfarina** [comment]
Thanks for catching this. The fix for v2 was merged after the v3 branch had been created and we missed pulling the fix over.

**Comment by derverzweifler** [comment]
This is very serious and leads to data loss / corruption. Please merge ASAP.

**Comment by midestefanis** [comment]
I was having the same problem with helm v3.1.2. Please I need this solution. Thank you

**Comment by jgoeres** [comment]
Works with Helm 3.2.0, thank you. :-)

**Comment by zze326** [comment]
The problems still exist in the latest version.

**Comment by shreben** [comment]
Hello guys,
the issue still exists in the latest helm
`version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"clean", GoVersion:"go1.19"}`

Could you please take a look. Thanks in advance.
