### ISSUE TITLE
Can not deploy Openshift SCC

### ISSUE THREAD

**Issue by yaroslavkasatikov** [helm/helm#7680]
```
$ helm version
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}

$ oc version
Client Version: openshift-clients-4.2.2-201910250432-12-g72076900
Server Version: 4.2.14
Kubernetes Version: v1.14.6+b294fe5

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0+724e12f93f", GitCommit:"7207690010f08f2ae526ee3300d4a18ea65997fe", GitTreeState:"clean", BuildDate:"2020-01-06T18:32:40Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6+b294fe5", GitCommit:"b294fe5", GitTreeState:"clean", BuildDate:"2020-01-06T18:46:07Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

Hello team.
I'm unable to deploy Openshift SCC with helm. 
Let's take an example of SCC and put it into templates: 

```apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: vault
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegedContainer: true
allowedCapabilities: null
defaultAddCapabilities:
  - IPC_LOCK
fsGroup:
  type: RunAsAny
groups:
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities: null
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- '*'
supplementalGroups:
  type: RunAsAny
users:
volumes:
- '*'
```

Run helm and got an error:

```
$ helm install --debug --dry-run test-release .
install.go:158: [debug] Original chart version: ""
install.go:175: [debug] CHART PATH: /home/centos/helm/andromeda

Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(SecurityContextConstraints): missing required field "allowedCapabilities" in io.openshift.security.v1.SecurityContextConstraints, ValidationError(SecurityContextConstraints): missing required field "priority" in io.openshift.security.v1.SecurityContextConstraints, ValidationError(SecurityContextConstraints): missing required field "requiredDropCapabilities" in io.openshift.security.v1.SecurityContextConstraints]
helm.go:75: [debug] error validating "": error validating data: [ValidationError(SecurityContextConstraints): missing required field "allowedCapabilities" in io.openshift.security.v1.SecurityContextConstraints, ValidationError(SecurityContextConstraints): missing required field "priority" in io.openshift.security.v1.SecurityContextConstraints, ValidationError(SecurityContextConstraints): missing required field "requiredDropCapabilities" in io.openshift.security.v1.SecurityContextConstraints]
helm.sh/helm/v3/pkg/kube.scrubValidationError
        /home/circleci/helm.sh/helm/pkg/kube/client.go:542
helm.sh/helm/v3/pkg/kube.(*Client).Build
        /home/circleci/helm.sh/helm/pkg/kube/client.go:149
helm.sh/helm/v3/pkg/action.(*Install).Run
        /home/circleci/helm.sh/helm/pkg/action/install.go:245
main.runInstall
        /home/circleci/helm.sh/helm/cmd/helm/install.go:223
main.newInstallCmd.func1
        /home/circleci/helm.sh/helm/cmd/helm/install.go:117
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:74
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1357
unable to build kubernetes objects from release manifest
helm.sh/helm/v3/pkg/action.(*Install).Run
        /home/circleci/helm.sh/helm/pkg/action/install.go:247
main.runInstall
        /home/circleci/helm.sh/helm/cmd/helm/install.go:223
main.newInstallCmd.func1
        /home/circleci/helm.sh/helm/cmd/helm/install.go:117
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:74
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1357

```

I may use  [] for allowedCapabilities and requiredDropCapabilities, but it's unable for 'priority'. Also "null" or 'null' aren't accepted by  CRD, because there is boolean or integers variable required.

Could you please suggest how to pass null value to helm?

**Comment by mattfarina** [comment]
@yaroslavkasatikov According to [the docs on this manifest](https://docs.openshift.com/container-platform/4.2/authentication/managing-security-context-constraints.html#security-context-constraints-example_configuring-internal-oauth):

> An empty list means that none of capabilities can be requested while the special symbol * allows any capabilities.

In the example an empty list is `[]`. Does this help?

**Comment by bal0s** [comment]
I have same problem.

I can confirm that `[]` is working with `allowedCapabilities` and `requiredDropCapabilities`, but not with `priority`.

**Comment by bacongobbler** [comment]
According to the docs, “nil” is considered a 0 priority. What happens if you set priority to 0?

**Comment by bal0s** [comment]
With `priority: 0` it is successfully deployed.

**Comment by yaroslavkasatikov** [comment]
Well we solved partical case, but for example when I try to install this yaml through helm:

https://raw.githubusercontent.com/jetstack/cert-manager/v0.13.1/deploy/manifests/00-crds.yaml

I got a mistake again:

`$ helm install --debug andromedav8 ..
install.go:158: [debug] Original chart version: ""
install.go:175: [debug] CHART PATH: /home/centos/helm/andromeda

Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(CustomResourceDefinition.spec): unknown field "preserveUnknownFields" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionSpec
helm.go:75: [debug] error validating "": error validating data: ValidationError(CustomResourceDefinition.spec): unknown field "preserveUnknownFields" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionSpec
helm.sh/helm/v3/pkg/kube.scrubValidationError
        /home/circleci/helm.sh/helm/pkg/kube/client.go:542
helm.sh/helm/v3/pkg/kube.(*Client).Build
        /home/circleci/helm.sh/helm/pkg/kube/client.go:149
helm.sh/helm/v3/pkg/action.(*Install).Run
        /home/circleci/helm.sh/helm/pkg/action/install.go:245
main.runInstall
        /home/circleci/helm.sh/helm/cmd/helm/install.go:223
main.newInstallCmd.func1
        /home/circleci/helm.sh/helm/cmd/helm/install.go:117
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:74
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1357
unable to build kubernetes objects from release manifest
helm.sh/helm/v3/pkg/action.(*Install).Run
        /home/circleci/helm.sh/helm/pkg/action/install.go:247
main.runInstall
        /home/circleci/helm.sh/helm/cmd/helm/install.go:223
main.newInstallCmd.func1
        /home/circleci/helm.sh/helm/cmd/helm/install.go:117
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:74
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1357
`

**Comment by zhangguanzhang** [comment]
```
defaultAddCapabilities: []
...
priority: 0
```
