### ISSUE TITLE
helm v3 list can not list installed charts

### ISSUE THREAD

**Issue by ygqygq2** [helm/helm#7682]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.1.0", GitCommit:"b29d20baf09943e134c2fa5e1e1cab3bf93315fa", GitTreeState:"clean", GoVersion:"go1.13.7"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T16:51:36Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
kubeadm v1.16.1

`helm list` can not list many installed charts. The truth is, it's already up and running.

![image](https://user-images.githubusercontent.com/17672440/75322971-df2c5600-58ae-11ea-9169-9e30cc67cb23.png)

![image](https://user-images.githubusercontent.com/17672440/75323017-01be6f00-58af-11ea-9afd-6ac9c4443e8b.png)

**Comment by bacongobbler** [comment]
Do you see the releases when you add `-n monitoring` to `helm list`?

**Comment by ygqygq2** [comment]
> Do you see the releases when you add `-n monitoring` to `helm list`?

Oh, you are ringht. It need add `-n NAMESPACE`.
