### ISSUE TITLE
 Helm3 : Error: no objects visited

### ISSUE THREAD

**Issue by sylvainmouquet** [helm/helm#7685]
Hello,

I deploy 2 applications.
The one all is correct

The second is deployed in 2 environment.
The first is `helm install `and the second is `helm upgrade  --force`

I have only a error with `helm install` : 

```
 client.go:98: [debug] creating 0 resource(s)
 Error: no objects visited
 helm.go:75: [debug] no objects visited
 helm.sh/helm/v3/pkg/kube.init
 	/home/circleci/helm.sh/helm/pkg/kube/client.go:51
 runtime.doInit
 	/usr/local/go/src/runtime/proc.go:5222
 runtime.doInit
 	/usr/local/go/src/runtime/proc.go:5217
 runtime.doInit
 	/usr/local/go/src/runtime/proc.go:5217
 runtime.main
 	/usr/local/go/src/runtime/proc.go:190
 runtime.goexit
 	/usr/local/go/src/runtime/asm_amd64.s:1357 
```
Any idea of what's happen?

**Comment by mattfarina** [comment]
The problem appears to be that Helm has no resources (i.e. Kubernetes manifests) to install into the cluster. Rendering the chart is not producing any Kubernetes resources.

**Comment by sylvainmouquet** [comment]
Yes i have just found the source of the problem.
I use helm lint but it returns a warning when the folder templates is not present.
The problem was the folder templates is not present but the Chart.yaml it present 
I close the issue
