### ISSUE TITLE
Pretty printed Go objects in templated YAML should probably be errors?

### ISSUE THREAD

**Issue by wallyqs** [helm/helm#7687]
Noticed that when not being careful it is possible to result with pretty printed objects

```yaml
stan:
   nats:
    url:
```

```yaml
    {{- with .Values.stan.nats }}
    ns: {{ . }}
    {{- end }}
```

Then when doing: 

```
helm install my-stan stan --set stan.nats.url=nats 
```

You get the map in the templated YAML:

```yaml
    ns: map[url:nats]
```

Output of `helm version`:
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.7"}

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-20T04:49:16Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-eks-aae39f", GitCommit:"aae39f4697508697bf16c0de4a5687d464f4da81", GitTreeState:"clean", BuildDate:"2019-12-23T08:19:12Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
EKS

**Comment by mattfarina** [comment]
This is a great suggestion. I'm just not sure how we could easily do that. Let me explain...

Helm uses the [template system in the Go standard library](https://golang.org/pkg/text/template/). In this case, where the object is being rendered with the details, it's the Go templating package that's doing that.

For Helm to do this I think there would need to be a custom template package that handles all the rendering that does so differently. Any other ideas on ways to implement this?

This is also enough of a change it would be breaking and need to wait for a Helm v4. Someone might be relying on this (though I don't know of any cases).

**Comment by bacongobbler** [comment]
I dont know of any cases where users rely on this particular case, however there have been cases before where we “fix” something, but break someone’s chart, like what happened with https://github.com/helm/helm/issues/3981.

I agree this might have to be considered a breaking change to the template system, unfortunately. As we’ve discovered in the past, any changes in the behaviour of the template system has been prone to break *something* or *someone*.

**Comment by wallyqs** [comment]
Thanks @mattfarina @bacongobbler agree that is fair for another major version, not sure either but per [Hyrum's Law](https://www.hyrumslaw.com/) maybe somebody depends on it...

**Comment by mattfarina** [comment]
Does anyone have a suggestion of how we would do this without replacing the Go template system with something we need to maintain?

**Comment by bacongobbler** [comment]
This could be caught in the values if the chart were to use JSON schema validation that was introduced in Helm 3. Would that work here?

https://helm.sh/docs/topics/charts/#schema-files

**Comment by mattfarina** [comment]
@bacongobbler If the input values are valid to a schema does not tell us how a template author puts those values into a template. A valid schema could still result in this case, right?

**Comment by technosophos** [comment]
I do not think this is a tractable problem. Solving it breaks compatibility, and requires knowledge of how a user thinks the object "ought" to look. If anyone is interested, feel free to file a Helm 4 proposal for how the new feature would work. For now, I am closing this issue because there is nothing actionable on it for Helm 3.
