### ISSUE TITLE
set

### ISSUE THREAD

**Issue by dfinninger** [helm/helm#7688]
Output of `helm version`:

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by bacongobbler** [comment]
Hi @dfinninger. There’s not much information on this ticket. Can you please edit this ticket with more information? Otherwise we should probably close this. Thanks!

**Comment by jdolitsky** [comment]
Going to close for now, @dfinninger please re-open in necessary

**Comment by dfinninger** [comment]
Oh geez, sorry. I must have started tying and hotkeys opened an issue.
https://help.github.com/en/github/getting-started-with-github/keyboard-shortcuts#issue-and-pull-request-lists

No issues here, sorry for the noise!
