### ISSUE TITLE
Helm Install DeploymentConfig on Open shift cluster takes time to create ReplicaSet even if the helm install command exits

### ISSUE THREAD

**Issue by yogesh-chauhan** [helm/helm#7693]
Output of `helm version`:Client: v2.16.0+ge13bc94
Server: v2.16.0+ge13bc94

Output of `kubectl version`:Client Version: v1.17.3
Server Version: v1.11.0+d4cacc0

Cloud Provider/Platform (AKS, GKE, Minikube etc.): open shift

**Comment by yogesh-chauhan** [comment]
I am installing https://github.com/jim-minter/nodejs-ex/raw/helm/helm/nodejs-0.1.tgz chart through helm on an open shift cluster. I have a steady state check that runs immediately after the helm install command exits. The steady state check first gets the list of controllers to perform a steady state check on. However, I am observing that the replication controller is not created after the helm install command exits and takes some time. Is it a known issue ?

**Comment by yogesh-chauhan** [comment]
helm install <chart> && oc get rc <replication_controller_name> this command would fail

**Comment by bacongobbler** [comment]
What happens if you append the `--wait` flag to `helm install`? Helm doesn’t wait for resources to become ready by default unless you ask it; it just reports that kubernetes accepted the manifests.

**Comment by bridgetkromhout** [comment]
Hi, @yogesh-chauhan - hopefully the suggestion of `--wait` was helpful for you. If you continue to have issues, please test with Helm v3; Helm v2 is no longer supported. You can read more at https://helm.sh/blog/helm-v2-deprecation-timeline/ - thanks!

**Comment by dylanpiergies** [comment]
@bacongobbler @bridgetkromhout I wouldn't consider this issue resolved... I'm seeing the same thing. Whilst `helm install --wait` does wait until Pods created by the standard Kubernetes controllers (e.g. `Deployment` via `ReplicaSet`, or `StatefulSet`) are ready, it does _not_ wait for Pods created by a `ReplicaSet` from a `DeploymentConfig`, which is an OpenShift CRD. Presumably this is because Helm doesn't know that a `DeploymentConfig` is a controller that will create Pods?

**Comment by bridgetkromhout** [comment]
Hi, @dylanpiergies - can you let us know which version of Helm you're using?
Also, here's the link @bacongobbler added in k8s Slack: https://github.com/helm/helm/blob/master/pkg/kube/wait.go

**Comment by obaranov** [comment]
@bridgetkromhout, We also have similar problem with the DeploymentConfig resource type and "--wait" method. Looks like helm does NOT wait for pods created by a ReplicaSet from a DeploymentConfig.  Running `helm upgrade -i .... --wait` reports success even when a Pod has failed to start. 

I checked the https://github.com/helm/helm/blob/master/pkg/kube/wait.go and from what I see, the DeploymentConfig from the openshift.io/v1 api group is not supported. Is that correct?

**Comment by bacongobbler** [comment]
Yes, that is correct. `--wait` does not support OpenShift resources. I would suggest looking at https://github.com/helm/helm/issues/8768 which proposes pulling the `--wait` control loop out of Helm. That could be the start of a plugin implementing wait support for non-Kubernetes resources (such as the ones from OpenShift).
