### ISSUE TITLE
Helm v3 inspect nil pointer stacktrace

### ISSUE THREAD

**Issue by zkutasi** [helm/helm#7696]
Output of `helm version`:
`version.BuildInfo{Version:"v3.1.0", GitCommit:"b29d20baf09943e134c2fa5e1e1cab3bf93315fa", GitTreeState:"clean", GoVersion:"go1.13.7"}`

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-16T08:00:38Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Company-internal distribution based on SLES15

Issue:
I work on a private project, so I will not disclose any info about it, but...
I have an umbrella helm-chart in the packaged format (tgz file), where I get the following stacktrace:

```
helm3 inspect CHARTNAME
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x1296a9c]

goroutine 1 [running]:
helm.sh/helm/v3/pkg/chart/loader.LoadFiles(0xc00018a000, 0x9b, 0x100, 0x9b, 0x100, 0x0)
	/home/circleci/helm.sh/helm/pkg/chart/loader/load.go:126 +0xa9c
helm.sh/helm/v3/pkg/chart/loader.LoadArchive(0x1be8a60, 0xc00000f650, 0xc00000f650, 0x0, 0x0)
	/home/circleci/helm.sh/helm/pkg/chart/loader/archive.go:193 +0x87
helm.sh/helm/v3/pkg/chart/loader.LoadFile(0xc000380140, 0x40, 0x0, 0x0, 0x0)
	/home/circleci/helm.sh/helm/pkg/chart/loader/archive.go:65 +0x221
helm.sh/helm/v3/pkg/chart/loader.FileLoader.Load(...)
	/home/circleci/helm.sh/helm/pkg/chart/loader/archive.go:43
helm.sh/helm/v3/pkg/chart/loader.Load(0xc000380140, 0x40, 0x6, 0x7030102, 0x1bbd1f6)
	/home/circleci/helm.sh/helm/pkg/chart/loader/load.go:62 +0x79
helm.sh/helm/v3/pkg/action.(*Show).Run(0xc00018f9a0, 0xc000380140, 0x40, 0xc0001e9d60, 0xc000380140, 0x40, 0x0)
	/home/circleci/helm.sh/helm/pkg/action/show.go:63 +0x67
main.newShowCmd.func4(0xc0002aca00, 0xc0004b91b0, 0x1, 0x1, 0x0, 0x0)
	/home/circleci/helm.sh/helm/cmd/helm/show.go:124 +0xd3
github.com/spf13/cobra.(*Command).execute(0xc0002aca00, 0xc0004b9180, 0x1, 0x1, 0xc0002aca00, 0xc0004b9180)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000e9680, 0x1c28c20, 0xc0000c29a0, 0x197e2fe)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:74 +0x1e2
```

I also have a newer version, where I do not get a stacktrace...
So I started to look into the code, and what is the difference here...
The code shows at https://github.com/helm/helm/blob/master/pkg/chart/loader/load.go at line 126 that the requirements.lock file is parsed, and we get a nil pointer. This file shows that there are a few initializations of c.Metadata, like this
```

if c.Metadata == nil {
				c.Metadata = new(chart.Metadata)
}
```

But this is not done in every place.
I have checked, and
- The tgz package of the faulty file has the requirements.lock file earlier in the package than the Charts.yaml and others
- The tgz package of the correct file has the Charts.yaml first

So I conclude that the issue here is the ordering of the files in a Chart package. If the files' ordering is not the expected one, the code has a nil pointer exception. This part of the code seems a bit fishy to me, with full of nil pointer issues.

Let me know if you need more info (and sorry for not providing examples, due to my work I cannot do this), to me this is clearly a bug.

**Comment by mattfarina** [comment]
@zkutasi Thanks for reporting the issue. We understand that there are times people cannot share exact details of what they are doing due to the nature of the work.

**Comment by janotav** [comment]
I think I got hit by the same. What confuses me is that I am not aware of any change in my development flow and things worked until yesterday. I had to revert to Helm2 to do things like package because Helm3 now fails constantly and consistently for me:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x12be92e]

goroutine 1 [running]:
helm.sh/helm/v3/pkg/chart/loader.LoadFiles(0xc0012c9800, 0xef, 0x100, 0xef, 0x100, 0x0)
	/home/circleci/helm.sh/helm/pkg/chart/loader/load.go:126 +0xa7e
helm.sh/helm/v3/pkg/chart/loader.LoadArchive(0x1c9ef40, 0xc001ac2d20, 0x23, 0x1, 0x15)
	/home/circleci/helm.sh/helm/pkg/chart/loader/archive.go:195 +0x87
helm.sh/helm/v3/pkg/chart/loader.LoadFiles(0xc001176000, 0x137, 0x200, 0x0, 0x0, 0xc000f02840)
	/home/circleci/helm.sh/helm/pkg/chart/loader/load.go:162 +0x1682
helm.sh/helm/v3/pkg/chart/loader.LoadDir(0xc00062a0c0, 0x33, 0xc00083c280, 0x47, 0x0)
	/home/circleci/helm.sh/helm/pkg/chart/loader/directory.go:119 +0x2a1
helm.sh/helm/v3/pkg/action.(*Package).Run(0xc000818f00, 0xc00062a0c0, 0x33, 0xc000345650, 0x0, 0x0, 0x0, 0x0)
	/home/circleci/helm.sh/helm/pkg/action/package.go:58 +0x3c
main.newPackageCmd.func1(0xc000346000, 0xc000721680, 0x3, 0x4, 0x0, 0x0)
	/home/circleci/helm.sh/helm/cmd/helm/package.go:103 +0x3a3
github.com/spf13/cobra.(*Command).execute(0xc000346000, 0xc0007215c0, 0x4, 0x4, 0xc000346000, 0xc0007215c0)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000c8b00, 0xc0007244e0, 0x1, 0x1)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:93 +0x258
```
I'm using currently latest version, but older fail too:
```
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}
```

**Comment by bacongobbler** [comment]
@janotav if you can provide a chart that can reproduce the issue, that would be most helpful. Thanks!

**Comment by rcjsuen** [comment]
@bacongobbler Just got hit by this using the 7.5.0 release of the `stable/airflow` chart. Looks like the `airflow.extraEnv.AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG` bit is bad...?

```
helm upgrade --dry-run nmr-airflow stable/airflow \
    --namespace "${NAMESPACE}" \
    --install \
    --timeout 15m \
    --atomic \
    --version 7.5.0 \
    --set "airflow.extraEnv.AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG=${VERSION}" \
    --values -
```

**Comment by rcjsuen** [comment]
`VERSION` should be set to `dev-dc57db661c251eb14d9a840f139e09d6423ef6fb`.

**Comment by janotav** [comment]
@bacongobbler unfortunately the chart that is failing is not public domain. realistically there is no chance I would get approval for making it public. if I find time I will try to isolate this into a reproducible test case. but to be honest that might take some time (as this is clearly data driven in some very subtle way)

**Comment by sebastianblunt** [comment]
We encountered this issue, and discovered it was because a given chart had a `Chart.yml` instead of `Chart.yaml`.
