### ISSUE TITLE
Resource ownership model does not guarantee exclusivity

### ISSUE THREAD

**Issue by jlegrone** [helm/helm#7699]
In typical usage, Helm's safeguards to prevent creation of an existing resource will prevent shared ownership of a resource between multiple releases. However, if the release metadata of two or more releases come to contain references to the same resource, there is no mechanism to prevent these releases from acting on that resource. This will become a more likely occurrence if #2730 (or other tools like it) are implemented.

Also related to https://github.com/helm/helm/issues/2388.

**Comment by jdolitsky** [comment]
@jlegrone how would we approach this? Do we need to iterate over all releases and owned references?

**Comment by jlegrone** [comment]
> how would we approach this? Do we need to iterate over all releases and owned references?

In #7649 we add release metadata to each resource via an annotation. This will allow newer Helm clients to error out before attempting to act on a resource owned by a different release (as indicated by these annotations), and wouldn't require any additional API calls.

**Comment by seaneagan** [comment]
i think this issue is only solved for create/update of resources. without #12683 being fixed, both old and new helm releases are still owning the resource from a deletion perspective.
