### ISSUE TITLE
"Unexpected unclosed action in template clause" when trying to render templated string from values.yaml

### ISSUE THREAD

**Issue by DaveOHenry** [helm/helm#7704]
Many charts currently support Prometheus Operator by optionally adding "prometheusRule" objects to the cluster. A user can then just add the rules in his "values.yaml". The supplied values can be templated strings and will be used by a "prometheusrule.yaml" template. This works for simple rules, but in most cases the chart will just refuse to render properly. The funny thing is, that even the example alerts that can be found in the values.yaml files of many charts are not working. 

I don't know where the problem exactly is, but it looks like something is trying to pretty print the values by inserting a "\n" at a position where it should not be and this breaks the template in most cases (see `"{{ template \"test.fullname\"\n    . }}` in the complete error message below). I already tried all kinds of workarounds like removing whitespaces, playing with single and double quotes, yaml multiline ... nothing seems to work.

values.yaml:
```
prometheusRule:
  enabled: true
  additionalLabels: {}
  namespace: "monitoring"
  rules:
    - alert: MyTestAlert
      expr: my_test_alert_with_a_long_name_kjlgnkjfdg{service="{{ template "test.fullname" . }}-mymetricsservice"} / 3600 > 1
      for: 1m
      labels:
        severity: critical
      annotations:
        description: |-
          The {{ template "test.fullname" . }} has a problem. The value is {{ "{{ $value }}" }}
        summary: Something {{ "{{ $value }}" }}
```

prometheusrule.yaml:
```
{{- if .Values.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ template "test.fullname" . }}
{{- with .Values.prometheusRule.namespace }}
  namespace: {{ . }}
{{- end }}
  labels:
    app: {{ template "test.name" . }}
    chart: {{ template "test.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
{{- with .Values.prometheusRule.additionalLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- with .Values.prometheusRule.rules }}
  groups:
    - name: {{ template "test.name" $ }}
      rules: {{ tpl (toYaml .) $ | nindent 8 }}
{{- end }}
{{- end }}
```

Output of `helm template .`:
```console
Error: template: test/templates/prometheusrule.yaml:21:16: executing "test/templates/prometheusrule.yaml" at <tpl (toYaml .) $>: error calling tpl: error during tpl function execution for "- alert: MyTestAlert\n  annotations:\n    description: The {{ template \"test.fullname\" . }} has a problem. The value is\n      {{ \"{{ $value }}\" }}\n    summary: Something {{ \"{{ $value }}\" }}\n  expr: my_test_alert_with_a_long_name_kjlgnkjfdg{service=\"{{ template \"test.fullname\"\n    . }}-mymetricsservice\"} / 3600 > 1\n  for: 1m\n  labels:\n    severity: critical": parse error at (test/templates/prometheusrule.yaml:6): unexpected unclosed action in template clause
```

Output of `helm version`:
```console
version.BuildInfo{Version:"v3.1.1",` GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```
```console
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```

**Comment by jdolitsky** [comment]
The issues is certainly with the line 
```
      rules: {{ tpl (toYaml .) $ | nindent 8 }}
```

in `prometheusrule.yaml`

Could you try removing the `expr: ` field and see if you still get this error? I suspect thats the piece causing the error, and would be helpful to isolate it.

**Comment by jdolitsky** [comment]
* expr field in values.yaml

**Comment by DaveOHenry** [comment]
Yes. This is the problematic piece. Everything else renders fine. The "bad linebreak" is inserted as soon as the line is longer than 70-80 characters.
    


-------- Ursprüngliche Nachricht --------
Von: Josh Dolitsky <notifications@github.com> 
Datum: 28.02.2020  21:24  (GMT+01:00) 
An: helm/helm <helm@noreply.github.com> 
Cc: David Heinrich <David.Heinrich@cortado.com>, Author <author@noreply.github.com> 
Betreff: Re: [helm/helm] "Unexpected unclosed action in template clause" when trying to render templated string from values.yaml (#7704) 


The issues is certainly with the line
      rules: {{ tpl (toYaml .) $ | nindent 8 }}

in prometheusrule.yaml
Could you try removing the expr: field and see if you still get this error? I suspect thats the piece causing the error, and would be helpful to isolate it.
—
You are receiving this because you authored the thread.
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.

**Comment by DaveOHenry** [comment]
Found this in the go-yaml repo:
https://github.com/go-yaml/yaml/issues/166
There is also a pull request mentioned that could potentially solve this issue.

But even if this PR makes it into upstream it would still not be available in HELM, would it? As far as I understand Helm v2 uses https://github.com/ghodss/yaml (=go-yaml/v2 v2.2.2) and Helm v3 uses https://sigs.k8s.io/yaml (=go-yaml/v2 v2.2.8).

**Comment by technosophos** [comment]
The linebreak above should not have an impact. I'm actually wondering if this is a case of nested `{{}}` characters. Can you get this down to a minimal template that just shows the issue without the rest of the template code?

**Comment by DaveOHenry** [comment]
Well, the linebreak is the main problem. See also https://github.com/go-yaml/yaml/issues/166. Under normal circumstances the linebreak "should" not have an impact, because it is valid yaml in any case. Unfortunately this does not take into account that certain strings (see https://godoc.org/text/template) cannot be split. 

However. When using something like this ...
values.yaml:
```something:
  - foo: test1
    foo2: test2
    foo3: foo_foo_foo_foo_foo_foo_foo_foo_foo_foo_foo_foo_foo_bar="{{ "something is here" }}"
```

templates/test.yaml:
```
{{- with .Values.something }}
  something2:
    - name: yes
      issue: {{ tpl (toYaml .) $ | nindent 8 }}
{{- end }}
```

The error message is:
```console
Error: render error in "foo/templates/test.yaml": template: foo/templates/test.yaml:4:16: executing "foo/templates/test.yaml" at <tpl (toYaml .) $>: error calling tpl: Error during tpl function execution for "- foo: test1\n  foo2: test2\n  foo3: foo_foo_foo_foo_foo_foo_foo_foo_foo_foo_foo_foo_foo_bar=\"{{ \"something is\n    here\" }}\"\n": parse error in "foo/templates/test.yaml": template: foo/templates/test.yaml:3: unexpected unterminated quoted string in command
```

It's a different error message, but the underlying problem is the same.


As a workaround I am currently using yaml literal style for all templated strings. At least in my case it works as expected:
```
something:
  - foo: test1
    foo2: test2
    foo3: |
      foo_foo_foo_foo_foo_foo_foo_foo_foo_foo_foo_foo_foo_bar="{{ "something is here" }}"
```

**Comment by DaveOHenry** [comment]
https://github.com/go-yaml/yaml/pull/571

As far as I understand this PR could solve the issue. It was merged into go-yaml:v2 and go-yaml:v3, but is not released yet.

**Comment by gothrek22** [comment]
@DaveOHenry It has been released as part of v2.3.0 on 7th of May 😃

**Comment by DaveOHenry** [comment]
Unfortunately Helm v2 uses https://github.com/ghodss/yaml (=go-yaml/v2 v2.2.2) and Helm v3 uses https://sigs.k8s.io/yaml (=go-yaml/v2 v2.2.8) :confused:

**Comment by laverya** [comment]
So thankfully you can update subdependencies without that dependency itself being updated - I've made a PR that does this, and a unit test demonstrating the fix!

**Comment by tshaiman** [comment]
using Helm v3.3.4 , issue still exists.

**Comment by sanjukta-maji** [comment]
what is the solution for this one ? I am having same issue with Helm v3.4.1. Please help !

Error: parse error at (mulesoft-probe/templates/PrometheusRule.yaml:28): unclosed action

spec:
  groups:
    - name: {{ template "mulesoft-probe.name" $ }}
      rules: {{ tpl (toYaml .Values.monitoring.rules) $ | nindent 8 }}

**Comment by tshaiman** [comment]
For us it was Linux/Windows compatible issues.
open the file in VS Code and Select "LF" as the file format , not "CRLF"

**Comment by sanjukta-maji** [comment]
still no luck . its failing when i add   avg_over_time () in the expr

- alert: Mulesoft probe is responding slow
    expr: avg_over_time( probe_duration_seconds{ instance="{{$.Values.monitoring.instance }}" }[2m] ) > 1
    for: 1m

**Comment by DaveOHenry** [comment]
The expression is too long. Unfortunately Helm splits the line and this breaks the Go template. Use yaml literal style for templated string like:
```
expr: |
  avg_over_time( probe_duration_seconds{ instance="{{$.Values.monitoring.instance }}" }[2m] ) > 1
```

**Comment by sanjukta-maji** [comment]
Thanks ! This worked for me .

**Comment by adasari** [comment]
Any update on this ? i am using helm2. tpl function on templates from values yaml is not working.
Eg: 
1. values.yaml - 
```
initContainers:
  - name: "template-setup"
    image: "{{ include "my-test.name" . }}"  
```
deployment yaml -
```
initContainers: 
        {{- tpl (.Values.initContainers | toYaml) $ | nindent 8}}
```
2. Values yaml - 
```
initContainers:
  - name: "template-setup"
    image: "{{ .Values.image.registry }}{{ .Values.image.repository }}:{{ .Values.image.tag }}"
```
deployment yaml -
```
initContainers: 
        {{- tpl (.Values.initContainers | toYaml) $ | nindent 8}}
```

tpl is works with simple Values/Release objects.

Values yaml - 
```
initContainers:
  - name: "template-setup"
    image: "{{ .Values.image.tag }}"
```
deployment yaml -
```
initContainers: 
        {{- tpl (.Values.initContainers | toYaml) $ | nindent 8}}
```

**Comment by DaveOHenry** [comment]
@adasari : Did you try the workaround by changing your values to yaml literals?
```
initContainers:
  - name: "template-setup"
    image: |
      "{{ include "my-test.name" . }}"  
```
```
initContainers:
  - name: "template-setup"
    image: |
      "{{ .Values.image.tag }}"
```

**Comment by adasari** [comment]
@DaveOHenry literals working. I have confirmed in my original comment.

**Comment by ramanNarasimhan77** [comment]
I hit this issue while trying to create a configmap from a file using 
`{{ ( tpl (.Files.Glob "files/myconfig.yaml").AsConfig . ) | nindent 2 }}`

Workaround that I used to get around this issue was to use helm variables because I was referring to the same variable from Values in more than one place.


```
{{- $imageTag := ( index .Values "image" "tag" -}}
{{ printf "\n" }}
initContainers:
  - name: "template-setup"
    image: {{ $imageTag }}
```

**Comment by DaveOHenry** [comment]
ping

**Comment by andreimosteoru** [comment]
can this issue reopened again? it is not fixed yet.
