### ISSUE TITLE
Add raw template output option

### ISSUE THREAD

**Issue by paulbdavis** [helm/helm#7709]
When working on templates, you sometimes get unhelpful messages about context errors from the yaml when trying to render them with `helm template`

It would be helpful to have a way to inspect the raw yaml output from the render go template process *before* it tries to parse them as JSON and sort the manifests for display. This way these errors can be debugged more easily when creating templates.

**Comment by hickeyma** [comment]
@paulbdavis Does `helm install --dry-run --debug` help?

**Comment by paulbdavis** [comment]
I found just doing some rendering under a block worked fine for debugging with the `template` command

```yaml
rendered: |
{{ include "my-bad-template" . | nindent 2 }}
```
