### ISSUE TITLE
Issue with go 1.14.0, Helm, 3.1.1

### ISSUE THREAD

**Issue by nicholasjackson** [helm/helm#7711]
Hi,

I am using Helm as a package from within my application (https://github.com/shipyard-run/shipyard/blob/master/pkg/clients/helm.go). When I upgraded Go to 1.14.0 I started to get the following error message.

```
2020-03-01T10:57:43.033Z [ERROR] Unable to apply blueprint: error="Error running chart: template: consul/templates/client-daemonset.yaml:121:23: executing "consul/templates/client-daemonset.yaml" at <(.Values.client.join) and (gt (len .Values.client.join) 0)>: can't give argument to non-function .Values.client.join"
```

I have tried to debug this but currently stumped, downgrading to Go 1.13.8 fixes the issue. Wondering if this is something to do with Go mod changes?

```
go version go1.13.8 linux/amd64
```

**Comment by bacongobbler** [comment]
> The text/template package now correctly reports errors when a parenthesized argument is used as a function. This most commonly shows up in erroneous cases like {{if (eq .F "a") or (eq .F "b")}}. This should be written as {{if or (eq .F "a") (eq .F "b")}}. The erroneous case never worked as expected, and will now be reported with an error can't give argument to non-function.

From https://golang.org/doc/go1.14

**Comment by mattfarina** [comment]
@nicholasjackson Can you make sure the chart your using doesn't have any issues with it. This may be your problem.

**Comment by nicholasjackson** [comment]
Thank you so much,

This is exactly what is going on, I am no expert on go template and would never have spotted that as an error.

```
{{- if (.Values.client.join) and (gt (len .Values.client.join) 0) }}
```

Will report the issue to the template maintainer. 

BTW, great work on Helm 3, I am loving the ability to embed it into my code as well as use from the CLI.

Kind regards,

Nic
