### ISSUE TITLE
(feature): --values flag does not work with value files inside chart archive

### ISSUE THREAD

**Issue by tamalsaha** [helm/helm#7715]
Output of `helm version`:
v3.0.2+g19e47ee

Currently --values | -f file can't be loaded from inside a chart archive. This file can be loaded from local filesystem or remote urls. 

Works:
```
helm template wordpress stable/wordpress -f ./values-production.yaml
```

Does NOT Work:
```
helm template wordpress stable/wordpress -f values-production.yaml
```

Here values-production.yaml should be extracted from the chart.tgz archive and used. Can this feature be added?

**Comment by bacongobbler** [comment]
duplicate of https://github.com/helm/helm/issues/4782.
