### ISSUE TITLE
How can I copy a file generated during pod startup to another pod in helm?

### ISSUE THREAD

**Issue by amitbhat-ct** [helm/helm#7716]
We have a requirement where we have to copy a file which is generated during container startup to another container running in different pod.
As of now, we are using kubectl cp to copy the file from the source pod to local first and then from local to the destination pod.
What are the ways to achieve this in helm?
Helm Version:"v3.0.0-beta.5"

**Comment by mattfarina** [comment]
Helm does not provide a features targeted at this.

The Kubernetes community wants things done in a declarative way. You tell the API what you want and it makes it work. [kubectl may be dropping the cp command, too](https://github.com/kubernetes/enhancements/blob/master/keps/sig-cli/20190920-future-of-kubectl-cp.md).

A method you could use for this is to setup a shared storage location. The file is copied in there by one pod and copied out by another pod.

**Comment by amitbhat-ct** [comment]
Thanks Matt for the answer.

And sorry for the delay in closing the issue.
