### ISSUE TITLE
how to add description to upgrade on helm 3?

### ISSUE THREAD

**Issue by horacimacias** [helm/helm#7717]
I've been using helm 2 and the description flag when upgrading.
I now see helm 3 does not have such flag and I get a _Error: unknown flag: --description_

Is there any way to specify some description/message on a helm upgrade so that it shows on the _helm history_ command?

**Comment by hickeyma** [comment]
Duplicate of #7033

**Comment by hickeyma** [comment]
This was fixed in #7074 and released in [Helm 3.1.0](https://github.com/helm/helm/releases/tag/v3.1.0)

**Comment by horacimacias** [comment]
thanks! 

sorry, for some reason I couldn't find the previous issue although I searched ¬_¬'
