### ISSUE TITLE
Not reporting User-Agent to Kubernetes calls

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#7719]
Over on #7718 I noticed logging output of:

```
I0302 18:06:53.261189  452176 round_trippers.go:431]     User-Agent: helm/v0.0.0 (linux/amd64) kubernetes/$Format
```

The User-Agent here is being generated by client-go because we aren't telling it what to use. It is possible for us to set this to the proper version.

**Comment by donggangcj** [comment]
The package `pkg/kube`  use `Factory` struct to communicate with `kubernetes APIServer` and the `Facotry` interface is copied from `cli-runtime` package.   so it is hard to build `client-go` `config` struct .

**Comment by donggangcj** [comment]
@mattfarina   Could you please reivew the pr #7732  and give me some advice?
