### ISSUE TITLE
Since Helm 3.1.0 we got a lot of warnings from awscli that too much clients are created.

### ISSUE THREAD

**Issue by TomasKohout** [helm/helm#7722]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.1.0", GitCommit:"b29d20baf09943e134c2fa5e1e1cab3bf93315fa", GitTreeState:"clean", GoVersion:"go1.13.7"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-12T13:43:46Z", GoVersion:"go1.13.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
`AWS`

When we run install or upgrade then a lot of 
```
W0303 09:43:12.111352    8329 exec.go:201] constructing many client instances from the same exec auth config can cause performance problems during cert rotation and can exhaust available network connections; 1961 clients constructed calling "aws"
```
occur. We use 1 prehook and 1 posthook. It was not happening with Helm 3.0.x. Does anybody know if this is ok or not? :-)

**Comment by jdolitsky** [comment]
This appears to be some issue in using client-go to auth against AWS. This is the source of error:
https://github.com/kubernetes/client-go/blob/master/plugin/pkg/client/auth/exec/exec.go#L202

I'm wondering if there was some environmental issue with the "aws" plugin (which I'm assuming means the aws-iam-autheticator). I'm wondering if that needs to be updated.

**Comment by TomasKohout** [comment]
I'll check out if we are outdated. I suppose that my PC is updated, but will check it out tomorrow. :-)

**Comment by TomasKohout** [comment]
`aws-iam-authenticator version`

```
{"Version":"v0.4.0","Commit":"c141eda34ad1b6b4d71056810951801348f8c367"}
```

It's installed from https://docs.aws.amazon.com/eks/latest/userguide/install-aws-iam-authenticator.html

**Comment by TomasKohout** [comment]
@jdolitsky would you know what PR could cause this? Older version of Helm 3 was doing fine and only Helm was updated to 3.1.x

**Comment by jdolitsky** [comment]
@TomasKohout do you have a previous version of helm (specific 3.x version) that works?

**Comment by TomasKohout** [comment]
3.0.3 was without thouse warnings. I've tried all rc versions of 3.1.0. Those warnings occur on all of them.

**Comment by TomasKohout** [comment]
I think that this is actually a regression so it should be labeled accordingly. Also creating 3000 clients is not a very good practice. Why does Helm needs so much clients?

**Comment by TomasKohout** [comment]
Looks like for every kubernetes object new client is created. @jdolitsky could you verify this? :)

**Comment by bacongobbler** [comment]
That should not be the case. The kubernetes client is created once per invocation and is shared for the entire install operation. 

See https://github.com/helm/helm/blob/59447f850c88251afcca9a67b8ce44131a73c46a/pkg/action/action.go#L225

**Comment by TomasKohout** [comment]
Well, here are logs from upgrade action. 
[helm3-0-3.log](https://github.com/helm/helm/files/4477213/helm3-0-3.log)
[helm3-1-2.log](https://github.com/helm/helm/files/4477214/helm3-1-2.log)

**Comment by TomasKohout** [comment]
I do not know guys. Maybe new version of kubernetes package? :-)

**Comment by bacongobbler** [comment]
Thank you for the logs.

I found the [source of the log message](https://github.com/kubernetes/client-go/blob/1be5940d0dd4d7109f11d70994b01a33085829e8/plugin/pkg/client/auth/exec/exec.go#L202-L204). That is definitely code which the EKS authenticator would traverse.

Based on the information provided here, I can only see this as an issue coming from the EKS authenticator, which is outside of Helm's control.

I noticed you are running an older version of Kubernetes: 1.14. Have you considered upgrading?

I would highly suggest looking at [the developer guide](https://helm.sh/docs/community/developers/) to see if you can try to nail the issue down yourself. I have not seen a similar report from another user, and I have not observed this behaviour before. This is why I'm asking to please let us know if you find anything.

> I do not know guys. Maybe new version of kubernetes package? :-)

Helm 3.1.2 uses Kubernetes 1.17 core libraries, and HEAD uses 1.18. As far as Helm's concerned, we are keeping up to date with Kubernetes here.

Hope this helps.

**Comment by SapientGuardian** [comment]
I didn't want to add a "me too" reply, but because you said " I have not seen a similar report from another user"...

I'm on EKS 1.15 with Helm 2.11 upgrading to 3.2.1. I needed to update some of my helm packages to address deprecations in Kubernetes 1.16, and in order to do _that_ I needed to upgrade Helm and figured I'd go all the way to 3.2.1. I'm migrating my packages using https://helm.sh/blog/migrate-from-helm-v2-to-helm-v3/ . During the final step of the conversion process (`helm3 2to3 cleanup`) I got the same warnings, with the final one being `W0515 16:20:25.464868     541 exec.go:201] constructing many client instances from the same exec auth config can cause performance problems during cert rotation and can exhaust available network connections; 3034 clients constructed calling "aws"`. That _does_ seem like a lot of clients :-) .

I haven't seen any adverse effects from this, just wanted to chime in to say that it isn't just that one guy running into it.

**Comment by bacongobbler** [comment]
Found the upstream issue: https://github.com/kubernetes-sigs/aws-iam-authenticator/issues/308. Please follow up there. There's no action to take here on our end.

**Comment by janario** [comment]
I've just had a similar scenario while using helm in a go app

Getting more details

[kube.(*Client).IsReachable](https://github.com/helm/helm/blob/master/pkg/kube/client.go#L92) always asks for a new client and then eventually it reaches 1000 and starts to warn

https://github.com/kubernetes/client-go/blob/master/plugin/pkg/client/auth/exec/exec.go#L202

Stacktrace:

```
k8s.io/client-go/plugin/pkg/client/auth/exec.(*Authenticator).UpdateTransportConfig at exec.go:203
k8s.io/client-go/rest.(*Config).TransportConfig at transport.go:100
k8s.io/client-go/rest.TransportFor at transport.go:42
k8s.io/client-go/rest.RESTClientFor at config.go:295
k8s.io/client-go/kubernetes/typed/certificates/v1beta1.NewForConfig at certificates_client.go:47
k8s.io/client-go/kubernetes.NewForConfig at clientset.go:444

k8s.io/kubectl/pkg/cmd/util.(*factoryImpl).KubernetesClientSet at factory_client_access.go:83
helm.sh/helm/v3/pkg/kube.(*Client).IsReachable at client.go:91
```

In my scenario, I have one go app that interacts with multiple namespaces and helm releases

Would it be possible to cache and reuse the kube client?
