### ISSUE TITLE
Chart pull from GitLab OCI registry: failed to authorize

### ISSUE THREAD

**Issue by MisterTimn** [helm/helm#7723]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Bare metal

### Problem
I'm storing charts from a monorepo on a private GitLab instance inside the GitLab OCI registry.
Having no problem storing these charts whatsoever.

When I try to pull a chart from this registry I do run into trouble.

First I use `helm registry login` to log in to the registry, this succeeds.
Then when I try to pull a chart I run into a 403.

```bash
$> helm chart pull gitlab.ilabt.imec.be:4567/ibcndevs/obelisk/obelisk-ci-testing/charts/pub-streaming-service:0.1.14
0.1.14: Pulling from gitlab.ilabt.imec.be:4567/ibcndevs/obelisk/obelisk-ci-testing/charts/pub-streaming-service
Error: failed to authorize: failed to fetch anonymous token: unexpected status: 403 Forbidden
```

Might be missing something trivial here but the docs are kind of light on the details atm since these features are all still experimental. I'm not entirely sure but I think this feature worked fine a while ago. I pulled some charts from that registry 4 weeks ago.

**Comment by jdolitsky** [comment]
Hello, please see this existing issue: https://github.com/helm/helm/issues/7046#issuecomment-562616422

There is still not full support in GitLab for charts in registries as far as I know

**Comment by MisterTimn** [comment]
Thing is, it used to work in previous Helm versions. Things broke somewhere between v3.0.x and v3.1.x. I'm gonna check different helm version to see where things broke.

GitLab offers a regular secure OCI registry, the compatibility lacks on the UI side but thats not an issue for us.

**Comment by MisterTimn** [comment]
Just found out it's working when I execute these commands as root after using `sudo su`
So probably something off with my installation after recent updates.

**Comment by jdolitsky** [comment]
@MisterTimn - thanks for the update!
