### ISSUE TITLE
Sub-Charts without parent deployment files

### ISSUE THREAD

**Issue by bikashkumars** [helm/helm#7724]
**We need your suggestion:**
We are working on a solution which required multiple sub-charts.
We wanted to maintain multiple sub-charts but without actual parents deployment file. So we have kept parent chart templates folder as empty, so that nothing will be deployed from parent. 
Is this correct way to do ? (multiple sub-charts without parent)

**2nd question:**
How we can define order of sequence of execution of each child/sub chats. We want to deploy sub-chart-1 first then other sub-charts.

We are using helm 2.x, If this is ok, can we expect same will work in Helm 3.x.

Output of `helm version`:
Client: &version.Version{SemVer:"v2.16.0", GitCommit:"e13bc94621d4ef666270cfbe734aaabf342a49bb", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.0", GitCommit:"e13bc94621d4ef666270cfbe734aaabf342a49bb", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:39:02Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Windows 10, developer Machine. But it will be deployed to RedHat os Kubernetes cluster.

**Comment by jdolitsky** [comment]
Hi @bikashkumars - this is a perfectly valid use case, and I've done this myself. You can use the parent chart to define things like ingress and other things that apply to your entire application.

Another option is to use tools that allow you to group multiple charts together in a single deployment. Check out projects like Helmfile: https://github.com/roboll/helmfile

**Comment by technosophos** [comment]
It appears to me that the question has been answered. Marking this as closed. Feel free to re-open if there is more.
