### ISSUE TITLE
Cannot upgrade a release with Job

### ISSUE THREAD

**Issue by wasker** [helm/helm#7725]
Output of `helm version`: 3.1.1

Output of `kubectl version`: 1.16.0 client / 1.15.7 server

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

We're deploying a chart that deploys batch/v1/Job and batch/v1beta1/CronJob amongst other things. We needed to update a tag of the container that's deployed as Job/CronJob, and during `update --install --atomic` we're getting this error:

```
Error: UPGRADE FAILED: release X failed, and has been rolled back due to atomic being set: cannot patch "X" with kind Job: Job.batch "Y" is invalid: spec.template: Invalid value: [skipped]: field is immutable
```

The only difference between the two deployments is the value of a container tag.

**Comment by jdolitsky** [comment]
@wasker from first glance, seems an issue with kubernetes api versions. If possible, can you try editing the container image tag directly using `kubectl edit job <name>`  and see if you get the same result?

**Comment by catchups** [comment]
Can I see a more detailed log?

**Comment by wasker** [comment]
Yep, sorry for delay, working on getting more info.

**Comment by wasker** [comment]
[Here's the job YAML](https://pastebin.com/UAhEVjJM).

I'm attempting to change "some_label" to "another_label" in `spec.template.spec.containers.image`. This does break with `kubectl edit job` as well.

I sort of understand that helm depends on k8s APIs, however, my expectations are that helm is smart enough to work this around somehow (e.g., delete existing release, deploy a new one, with some way of preserving previous release's data, to rollback, if new deployment fails).

**Comment by hugoboos** [comment]
I'm experiencing the same issue. Update the Chart AppVersion which is used as an image tag. Running `helm upgrade` gives:

`Error: UPGRADE FAILED: cannot patch "my-job" with kind Job: Job.batch "my-job" is invalid: spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{ ... }: field is immutable`

Helm version: `3.1.2`
Kubectl version: client `v1.18.0`, server `v1.17.4`

**Comment by remiuz** [comment]
I have exactly the same issue when trying to update a chart that contains a Job definition.
I tested with Helm 3.0.3 and 3.1.1 and it fails with both.

A bug fix would be really appreciable for this issue :crossed_fingers:

**Comment by technosophos** [comment]
The issue is that certain things are considered _by Kubernetes_ to be immutable. You cannot upgrade certain values on certain types of Kubernetes objects. However, Helm doesn't know which values those are, because they are not exposed by the schema. So Helm sends the manifest to Kubernetes, which responds back with a list of fields that are immutable. The deployment fails because the objects cannot be upgraded.

The solution is for your charts to not attempt to modify immutable fields. You can find more information in the Kubernetes documentation https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/ (though you may have to go to the Kubernetes YAML API docs to find out exactly which fields are immutable)

FWIW, many of the Kubernetes controllers will not let you change certain things in the spec template metadata because Kubernetes uses that info to find things you have deployed.

**Comment by wasker** [comment]
If helm bills itself as a "package manager for Kubernetes", shouldn't it be a bit more helpful in cases like that? Whenever I run into this situation, I have to do uninstall of the release, then reinstall the chart anew. Seems like helm could do that for me with a flag on helm install...

**Comment by bacongobbler** [comment]
As mentioned earlier,

> However, Helm doesn't know which values those are, because they are not exposed by the schema. So Helm sends the manifest to Kubernetes, which responds back with a list of fields that are immutable.

If you know of a way to improve the situation, please feel free to submit a patch.

**Comment by technosophos** [comment]
@wasker There are a variety of flags, including `--force`, `--replace`, and `--atomic`, which can help with specific cases. There are also a number of best practices documented in the charts documentation that provide guidance on naming for things like jobs. But at the end of the day, chart authors will have to know a little about how Kubernetes works and design their charts accordingly.

**Comment by wasker** [comment]
According to the [documentation](https://helm.sh/docs/helm/helm_upgrade/), "--force - force resource updates through a replacement strategy".

`helm upgrade blah ../../helmchart/blah --install --atomic --force --other-args` doesn't attempt to replace anything, simply fails when I attempt to upgrade a release with Job resource.

> But at the end of the day, chart authors will have to know a little about how Kubernetes works and design their charts accordingly.

Where the "package management" comes into picture?

**Comment by technosophos** [comment]
I'm not sure what you are looking for as far as an answer goes. Kubernetes does not let you alter the label selectors on Jobs. If you want to write a chart that does this, you'll need to figure out ways to do this.

I understand that you wish Helm did this for you, but we don't have a way to do this. If you would like write a detailed proposal and post it, we'd be happy to discuss.

**Comment by bacongobbler** [comment]
Apologies for the confusion on the docstring, by the way. `--force` submits a PUT request against the Kubernetes API, as opposed to the PATCH request typically submitted by Helm on an upgrade. PUT operations are typically described as an HTTP request to replace that object, but it's up to Kubernetes to respect that PUT request or not. And in some cases (as you have observed), it doesn't.

Please feel free to carry on the discussion over in #7082.

**Comment by wasker** [comment]
@technosophos I think, #7082 is what I'm looking for (thanks, @bacongobbler!). I thought that `--force` _is_ that, but it looks like the actual "replacement strategy" is missing from helm as it is currently.

Thanks for the pointers, I subscribed to #7082 and will follow up there.

**Comment by RookieCodeMan** [comment]
You cannot upgrade certain values on certain types of Kubernetes objects. You can add random number in job name, such as:
```
name: xxxx-{{ randAlphaNum 5 | lower }}
```
So when upgrade this chart, new job can update a tag of the container.

**Comment by distnie** [comment]
The existing job need to be deleted, because the template section in the job is immutable or not updatable. so you have 2 following options.

1. Always create a new job with a unique name, so it leaves the old jobs and creates a new one - every time if you include the version of image would be sensible.
2. Automatic cleaning of jobs (more info [check here][1]) - The job property `ttlSecondsAfterFinished` allows helps to delete the job automatically after a sepecified period. 
for eg:
 
```
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: pi-with-ttl
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          containers:
          - name: pi
            image: perl
            command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
          restartPolicy: Never
```

  [1]: https://kubernetes.io/docs/concepts/workloads/controllers/job/#clean-up-finished-jobs-automatically

**Comment by darth-sb** [comment]
To anyone that came looking for similar use cases on upgrading immutable resources, the pre-deploy section in the docs may address it.
From https://fluxcd.io/docs/use-cases/running-jobs/
> Setting spec.force to true will make Flux recreate the Job when any immutable field is changed, forcing the Job to run every time the container image tag changes.

**Comment by verovec** [comment]
Hi everyone,
In addition to all of the above responses you can check in the side of helm-hooks : https://helm.sh/docs/topics/charts_hooks/
I solved my issue thanks to @distnie and its second point which suggests to use `ttlSecondsAfterFinished`. The purpose of my job was to fill the database with seeds and in addition I have covered all potential issues by only allow job running with `post-install` hook
