### ISSUE TITLE
Helm3 on concourse fails to initialize

### ISSUE THREAD

**Issue by Timtech4u** [helm/helm#7726]
I built a Docker image for Helm3 that is expected to work within a concourse pipeline (as I'd previously used in Helm2), however when I run the pipeline, I get the following error:

![Screenshot from 2020-03-04 07-47-41](https://user-images.githubusercontent.com/11256481/75852571-94e63000-5dec-11ea-8edc-53db0c1d1753.png)

```
Initializing helm...
Error: unknown shorthand flag: 'c' in -c
```

**Comment by bacongobbler** [comment]
Perhaps a good question to pose to the concourse folks? Not sure how their pipeline is set up.

**Comment by bacongobbler** [comment]
What version of helm 3 is in that image?

**Comment by Timtech4u** [comment]
> What version of helm 3 is in that image? Do you have an example that can reproduce the issue?

Thanks @bacongobbler , I would reach out to the concourse folks.
I'm using version `3.0.0-beta.3` , I confirmed the image works fine by building and running the helm3 image the following command which seems to work.
```
 docker container run helm3 -c 'helm version'
```

My pipeline is based on this https://github.com/linkyard/concourse-helm-resource

**Comment by hickeyma** [comment]
@Timtech4u Re Helm version . It would be best to us GA version of Helm 3. Current version is [3.1.1](https://github.com/helm/helm/releases/tag/v3.1.1)

**Comment by Timtech4u** [comment]
I was able to get this working using https://github.com/Typositoire/concourse-helm3-resource

**Comment by bacongobbler** [comment]
Yeah. It looks like that image uses helm 3.0.2 when the -c flag was reintroduced.

Please use a stable version of helm 3. Closing!
