### ISSUE TITLE
Feature Request/Question: Given a chart file can I list all the images that will be needed?

### ISSUE THREAD

**Issue by paul-nelson-baker** [helm/helm#7730]
My current use case is this: my team and I have been developing some charts for a client and we've found out recently that our requirements are 100% bare-metal and isolated from the outside world.

This isn't a blocking issue, because we can deploy to any arbitrary cluster and run:
```bash
kubectl get pods --all-namespaces -o jsonpath="{..image}" | tr " " "\n" | sort --unique
```
and we now know what images we need to [docker save](https://docs.docker.com/engine/reference/commandline/save/) and then later [docker load](https://docs.docker.com/engine/reference/commandline/load/).

To create a more performant build process for our final deploy, is there a way we can have helm spit out all the images that are required for a chart (including subcharts) so we can automate this without having to deploy to a cluster first?

**Comment by bacongobbler** [comment]
I'm sure this would be a useful plugin if someone were to parse the output of `helm template` and show what images are used in the chart. This functionality is not available as Helm, though.

**Comment by paul-nelson-baker** [comment]
AH! I had no idea Helm had a plugin system! I may be able to implement this myself, thank you!
