### ISSUE TITLE
Meaningless uninstall command output when annotated with "helm.sh/resource-policy:keep"

### ISSUE THREAD

**Issue by donggangcj** [helm/helm#7733]
if  a resource annotated with "helm.sh/resource-policy:keep", the output is meaningless when excuting uninstall command.
```
➜  myappone helm uninstall myapp1
manifest-1  # keeped resource name which is  generated by program

release "myapp1" uninstalled
```
Obviously,that's not what we want need. output like this will be fun:
```
➜  myappone helm uninstall myapp1
service/myapp1-service

release "myapp1" uninstalled
```

Output of `helm version`:
version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T14:25:20Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by bridgetkromhout** [comment]
Hi, @donggangcj -  I'm closing this issue because we now have a recommended path forward for proposals: if you'd like to formally propose this idea, please file a [Helm Improvement Proposal](https://github.com/helm/community/blob/master/hips/hip-0001.md) to discuss it with the community. Thanks!
