### ISSUE TITLE
Chocolately install of 3.1.1 is producing 3.0.0=beta.3

### ISSUE THREAD

**Issue by namloc2001** [helm/helm#7737]
Hello, I've just downloaded the latest version from chocolately and despite it being 3.1.1-windows-amd64.zip, the version is v3.0.0-beta.3 and this is stopping 'template' from working as it is trying to reach an external cluster (unnecessarily).

Output of `helm version`:
version.BuildInfo{Version:"v3.0.0-beta.3", GitCommit:"5cb923eecbe80d1ad76399aee234717c11931d9a", GitTreeState:"clean", GoVersion:"go1.12.9"}

Output of `kubectl version`: N/A

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  N/A

**Comment by bacongobbler** [comment]
Hi @namloc2001! The chocolatey package is owned by a community member. Have you reported it to the maintainer of that package?

**Comment by namloc2001** [comment]
Hi @bacongobbler no I haven't. How do I do that?

**Comment by bacongobbler** [comment]
https://chocolatey.org/packages/kubernetes-helm

cc @synax

**Comment by namloc2001** [comment]
Scrap that. I found I had an old version installed in a different directory and it wasn't getting picked up by a chocolately uninstall. Resolved now. Version is correct.
