### ISSUE TITLE
Create a new "pre-ready" hook

### ISSUE THREAD

**Issue by rainest** [helm/helm#7740]
This is similar to #3282, but from the opposite direction: I'd like a hook that always uses the behavior of the `post-install` hook when `--wait` is not used, i.e. hook resources are always created immediately after installation, without waiting to determine if installation succeed.

My main use case for this is handling a database initialization task: [our chart](https://github.com/Kong/charts/tree/master/charts/kong) spawns both the main application and database (via a subchart) during install along with a `post-install` job that initializes the database schema. The main application fails to start until schema initialization completes. This works fine without `--wait`, since both the application and job are effectively created at the same time, but with `--wait`, the job isn't created until the application starts, creating a circular dependency.

I don't believe there's any way to use `pre-install` here, as I'm not aware of a way to spawn a subchart in `pre-install`. Doing so would create several other complications, as it'd probably necessitate creating and then deleting the database pod during `pre-install` to then re-create it during install, as it wouldn't be managed as part of the release otherwise--this may work, but seems a bit cumbersome.

Unlike `post-ready`, this shouldn't introduce additional complications related to returning the prompt; it should be possible with a new hook handler at https://github.com/helm/helm/blob/v3.1.1/pkg/action/install.go#L297

**Comment by rainest** [comment]
This primarily comes up for us in the context of CI, so I'd previously [filed a similar report to chart-testing](https://github.com/helm/chart-testing/issues/202). However, it doesn't appear there's any way for it to function without `--wait`, locking it into that `post-install` behavior.

**Comment by bacongobbler** [comment]
How does this differ from hook weights? https://helm.sh/docs/topics/charts_hooks/#writing-a-hook

As an FYI, we're asking new proposals to first write up a Helm Improvement Proposal, also known as a HIP. This gives the maintainers an opportunity to consider the design of the proposal and iron out any design kinks before a reference implementation is provided. This saves both you and us time in the long run.

Please have a read through https://github.com/helm/community/blob/master/hips/hip-0001.md and let me know if you have any questions.

**Comment by rainest** [comment]
I think it would still differ in that we wouldn't to change the order of events within hook phases, but rather that we don't have any way to start tasks after an install but before the install is known to be ready--neither a pre-install hook with positive infinity weight nor a post-install hook with negative infinity weight would run it at the correct step in our deployment (at least assuming `--wait`): this task needs to happen after the install is instantiated (i.e. non pre-install), but before the install becomes ready (i.e. not post-install).

I may be missing something from my reading of the weights feature, but as best I can tell it only allows explicit ordering of events within existing hook phases, not pushing hook work earlier/later than the hook would normally run with regards to the rest of the install lifecycle. Am I missing something where hook weights would allow that?

Can take a look at rewriting this in HIP format--the original request predates it (damn, March 2020 seems so recent and yet also soooooooooo far, but that's neither here nor there), though if #8676 looks viable and the re-stated rationale works as a soft justification as to why weight wouldn't help here, it may make sense to review that as-is.

**Comment by vdweij** [comment]
Any updates? That proposed hook appears to me more elegant than having (and relying) to specify the --wait flag.
