### ISSUE TITLE
how to specify namespace in values.yaml

### ISSUE THREAD

**Issue by argunasekhar** [helm/helm#7745]
Output of `helm version`:v2.x

Output of `kubectl version`:1.15.1

Cloud Provider/Platform (AKS, GKE, Minikube etc.): on-premise

Hi - 
I'm trying to install couchbase database along with its operator in k8s env, using helm charts.
and i want my depployment to be deployed in separate namespace, How can i specify namespace in values.yaml rather than specifying in cli (helm install -n crdldb <package name> --namespace <namespace_name>)

_**Regards,
Gunasekhar.**_

**Comment by bacongobbler** [comment]
it is not possible to specify the namespace parameter other than with the `--namespace` field. It cannot be passed along from values.yaml.

Hope this helps.
