### ISSUE TITLE
helm v3 packaging charts differently on windows and linux (breaks artifactory)

### ISSUE THREAD

**Issue by meurig** [helm/helm#7748]
I'm trying to package a helm chart and deploy it to a private helm repo on artifactory 6.18.0.

This works fine if I package the chart on linux, but fails if the chart is packaged on windows.

It also works fine with charts packaged on windows with a v2 helm client, so it appears to be an issue introduced in helm v3.

I can also see that the resultant tgz files are different by listing their contents with tar (note the backslashes):

Good (linux or windows v2):
```
$ tar -tvf tds-proxy-1.0.0.tgz
-rwxr-xr-x 0/0             129 2020-03-09 11:47 tds-proxy/Chart.yaml
-rwxr-xr-x 0/0             195 2020-03-09 11:47 tds-proxy/values.yaml
-rwxr-xr-x 0/0            1033 2020-03-09 11:47 tds-proxy/templates/deployment.yaml
-rwxr-xr-x 0/0             547 2020-03-09 11:47 tds-proxy/templates/service.yaml
-rwxr-xr-x 0/0             364 2020-03-09 11:47 tds-proxy/.helmignore
```

Bad (helm v3 on windows):
```
$ tar -tvf tds-proxy-1.0.0.tgz
-rw-r--r-- 0/0             129 2020-03-09 11:57 tds-proxy\\Chart.yaml
-rw-r--r-- 0/0             195 2020-03-09 11:57 tds-proxy\\values.yaml
-rw-r--r-- 0/0            1033 2020-03-09 11:57 tds-proxy\\templates\\deployment.yaml
-rw-r--r-- 0/0             547 2020-03-09 11:57 tds-proxy\\templates\\service.yaml
-rw-r--r-- 0/0             364 2020-03-09 11:57 tds-proxy\\.helmignore
```

This has been [raised as an issue with artifactory](https://www.jfrog.com/jira/browse/RTFACT-21145), but I feel it's up to helm to package consistently irrespective of where helm package is run. This looks like a bug in the helm v3 windows client.

Output of `helm version`:
`version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}`

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
not relevant (bare metal ish)

**Comment by mattfarina** [comment]
Thanks for catching this issue. The path issue causes other problems as well. For example, you can't decompress the archive properly on linux (which may be the artifactory problem).

**Comment by mattfarina** [comment]
Also, I verified the issue in the latest release.

**Comment by mattfarina** [comment]
@meurig I think this will fix it. If you have time to verify it's working for you it would be great.

**Comment by meurig** [comment]
Thanks @mattfarina, sounds great!

I'm having some trouble building helm behind our corporate firewall, but once I've got those issues sorted I'll give this a go.

**Comment by meurig** [comment]
I've tested your fix and it works great, thanks Matt! :+1:
