### ISSUE TITLE
Listing releases (helm list) with short listing format (--short) and json output (--output json) gives unexpected results.

### ISSUE THREAD

**Issue by git-enzo** [helm/helm#7749]
Output of `helm version`:
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"c83d931fb9bece427bc63a02349755e0f8696d3e", GitTreeState:"clean", BuildDate:"2020-01-31T20:09:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS, Minikube

Hello,

When I try to list all releases for a specified namespace with json output and short (quiet) listing format, then output is no json.

It seems that combination of these two parameters breaks specified output in helm3. If these parameters are used separately, then it works as expected (either json output or short listing). This behavior is correct in helm2.

Below examples, assuming that we have 2 releases named 'test1' and 'test2' in 'test' namespace.

_Helm 3:_

Command:
`helm list --namespace test --short --output json` or `helm list --namespace test -q -o json` or other combinations

Output:
```
test1
test2
```
there is only short listing format (missing json output)

_Helm 2:_

Command:
`helm list --namespace test --short --output json`

Output:
`["test1","test2"]` as expected, short listing format with json output

**Comment by mattfarina** [comment]
Thanks for the report. I have replicated the issue.

**Comment by anshulvermapatel** [comment]
@mattfarina , I too replicated the issue and am working on a PR, give me some more time.

**Comment by mattfarina** [comment]
@anshulvermapatel great. please ping me to review when you have it.

**Comment by anshulvermapatel** [comment]
@mattfarina , Raised a PR, please review it once you get time.
Thank You, do let me know if there is any change required.

**Comment by mattfarina** [comment]
#7753 was merged with a fix for this.
