### ISSUE TITLE
Helm lint (v3) doesn't take values files into account during schema validation

### ISSUE THREAD

**Issue by sean-krail** [helm/helm#7756]
Edit: Steps to reproduce: https://github.com/helm/helm/issues/7756#issuecomment-617889123

I have a bunch of charts with `values.schema.json` files that won't pass schema validation without passing in necessary, environment-specific values. I don't want these values in the base `values.yaml` file because they are environment-specific, but should fail at install/upgrade time.

When running `helm lint ${chart} --values ./lint-values.yaml` I'm getting errors like below **even though these values are provided in `./lint-values.yaml`**:
```
==> Linting ${chart}
[ERROR] values.yaml:
- ingress.hosts: Array must have at least 1 items
...

Error: 1 chart(s) linted, 1 chart(s) failed
```

Important to note that `helm template ${chart} --values ./line-values.yaml` does not throw any schema validation errors. When I run `helm template ${chart}` I see the same errors as above:
```
Error: values don't meet the specifications of the schema(s) in the following chart(s):
agent-services:
- ingress.hosts: Array must have at least 1 items
...
```

I think this is a bug. `helm lint` should run values schema validation against the final `.Values` object like the docs say:
> Note that the schema is applied to the final `.Values` object, and not just to the `values.yaml` file. This means that the following `yaml` file is valid, given that the chart is installed with the appropriate `--set` option shown below.

Source: https://helm.sh/docs/topics/charts/#schema-files

---

Output of `helm version`:
```
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

Output of `kubectl version`: not relevant

Cloud Provider/Platform (AKS, GKE, Minikube etc.): not relevant

**Comment by donggangcj** [comment]
I have replicated the issue. I am trying to fix:)

**Comment by sean-krail** [comment]
Either it’s a bug or the docs need to be reworded because https://helm.sh/docs/topics/charts/#schema-files gives the impression that `helm lint` applies schema validation to the final `.Values` object.

If it’s not a bug, how are chart owners supposed to validate values schemas that include API keys, usernames, passwords, and other environment-specific configs but aren’t (shouldn’t be) included in the default values file?

**Comment by sean-krail** [comment]
@bacongobbler I don't think this is a question/support, I think it's a bug.

**Comment by cylewitruk** [comment]
Also ran into this, but I'm not sure (at least in my case) that it has to do with values files not being taken into account.  It looks like there's two passes and provided values are only being used in one of them.

I'm trying json schema validation for the first time on a new chart and I'm seeing that it's outputting errors _twice_.  I've also tossed in a "bug" (`{{ asdf }}`) in one of the templates which should output a failure.

```
$ helm lint test/
==> Linting test/
[INFO] Chart.yaml: icon is recommended
[ERROR] values.yaml: - app.baseUri: Does not match pattern '^(https|http|)://'
- app.baseUri: Does not match format 'uri'
- oidc.authority: Does not match pattern '^(https|http|)://'
- oidc.authority: Does not match format 'uri'
- appVersion: Does not match pattern '^\d((\.\d+)?)+'
- api.baseUri: Does not match pattern '^(https|http)://.+'
- api.baseUri: Does not match format 'uri'

[ERROR] templates/: values don't meet the specifications of the schema(s) in the following chart(s):
test:
- appVersion: Does not match pattern '^\d((\.\d+)?)+'
- api.baseUri: Does not match pattern '^(https|http)://.+'
- api.baseUri: Does not match format 'uri'
- app.baseUri: Does not match pattern '^(https|http|)://'
- app.baseUri: Does not match format 'uri'
- oidc.authority: Does not match pattern '^(https|http|)://'
- oidc.authority: Does not match format 'uri'


Error: 1 chart(s) linted, 1 chart(s) failed
```
Note that the errors are spit out twice, and no template validation error.

Now if I specify a values file (or specify them all via the command line with `--set`, same result):
```
$ helm lint test/ -f .testvalues.yaml 
==> Linting test/
[INFO] Chart.yaml: icon is recommended
[ERROR] values.yaml: - appVersion: Does not match pattern '^\d((\.\d+)?)+'
- api.baseUri: Does not match pattern '^(https|http)://.+'
- api.baseUri: Does not match format 'uri'
- app.baseUri: Does not match pattern '^(https|http|)://'
- app.baseUri: Does not match format 'uri'
- oidc.authority: Does not match pattern '^(https|http|)://'
- oidc.authority: Does not match format 'uri'

[ERROR] templates/: parse error at (test/templates/deployment.yaml:98): function "asdf" not defined

Error: 1 chart(s) linted, 1 chart(s) failed
```

Here the errors are only printed once, and it looks like in what I'm assuming is a "second validation pass", schema validation succeeded and it went on to validate the templates, showing the `function "asdf" not defined` error.  So, it seems the values file was only taken into account in the second pass, but not the first.

Ideally we would only have one pass, based on the final values object.  It would also be great if the linting didn't stop if any schema validations occur, and proceeded with validating the chart - I didn't see that behavior described in documentation, and the reason why I'm using a `.testvalues.yaml` to provide valid values so that I can see the template validation errors.

**Comment by technosophos** [comment]
There is not enough information in this ticket to reproduce. Please provide an example.

**Comment by sean-krail** [comment]
@technosophos here's a chart that reproduces the problem: [helm-7756.zip](https://github.com/helm/helm/files/4517493/helm-7756.zip)

In the root chart directory run:
```bash
# fails as expected
helm template .

# fails as expected
helm lint .

# works as expected
helm template . --values ./lint-values.yaml

# this fails, but I expect it to work
helm lint . --values ./lint-values.yaml
```

`template` works but `lint` doesn't. The chart has a JSON schema that expects two properties `username` and `password`. `username` is set with a default value in `values.yaml`, `password` is set in `lint-values.yaml`.

**Comment by technosophos** [comment]
Excellent! I just reproduced with the chart above. Thank you.

**Comment by jandubois** [comment]
@technosophos Something is still weird though:

I've used the repro chart helm-7756.zip provided above, but changed `values.yaml` from:

```
$ cat values.yaml
username: my_username
# password: my_password
```

to:

```
$ cat values.yaml
username: my_username
password: ~
```

Now linting still fails when I try to override the `nil` value:

```
$ helm lint . --values lint-values.yaml
==> Linting .
[INFO] Chart.yaml: icon is recommended
[ERROR] values.yaml: - (root): password is required


Error: 1 chart(s) linted, 1 chart(s) failed

$ helm lint . --set password=my_password
==> Linting .
[INFO] Chart.yaml: icon is recommended
[ERROR] values.yaml: - (root): password is required


Error: 1 chart(s) linted, 1 chart(s) failed

$ helm version
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.6"}
```

Is there an explanation for this, or is this still a bug?

**Comment by technosophos** [comment]
Would you mind opening this as a new issue, @jandubois ?
