### ISSUE TITLE
Dynamically give .cluster.local DNS in environment variables in sts

### ISSUE THREAD

**Issue by aknakshay** [helm/helm#7759]
I want to create an environment variable in the pod created by my sts which would consist of its FQDN. As the dns domain - ".cluster.local" can be different for various clusters, like '.cluster.abc', or '.cluster.def', I want to populate that dynamically based on the cluster settings. I checked that .fieldRed.fieldPath doesn't consist of anything like it.

Is there any other option to do that?

Output of `helm version`: "v2.16.1"

Output of `kubectl version`: 1.16

**Comment by bacongobbler** [comment]
Were you able to determine how to resolve this? This seems like something that would be provided through the Kubernetes API. Let us know if you find out anything.
