### ISSUE TITLE
Add a flag to execute chart hooks in parallel

### ISSUE THREAD

**Issue by akhilles** [helm/helm#7763]
Currently, all chart hooks are executed serially. For some use cases (such as running `helm test` in CI environments), this is just too slow. In Helm v2, the `helm test` command supports the `--parallel` and `--max` flags which enable and limit parallel execution of tests, respectively. This functionality wasn't ported to Helm v3 due to test infrastructure changes.

Adding a `--parallelism` flag to Helm v3 that allows for hooks to be executed in parallel (while still respecting `"helm.sh/hook-weight"` annotations) would be really useful.

**Comment by akhilles** [comment]
I'd like to take a shot at implementing this if there are no immediate objections.

**Comment by hickeyma** [comment]
Go for it @akhilles

**Comment by strainovic** [comment]
Same thing as https://github.com/helm/helm/issues/7241
