### ISSUE TITLE
helm repo index command behavior with created field. ( In version 2.9.1 created field do not have double quote and in 2.14.3 it has double quote) Why this change. and in which version this got change 

### ISSUE THREAD

**Issue by shaijain** [helm/helm#7766]
Output of `helm version`:

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by shaijain** [comment]
Output (version 2.9.1 created field  in index.yaml):
    **created: 2020-03-12T18:05:51.925375703+02:0**
Output (version 2.14.3 created field  in index.yaml):
  **created: "2020-03-13T11:31:32.251959715+02:00"**

**Comment by bridgetkromhout** [comment]
Hi, @shaijain - I'm not sure what problem you're trying to solve, but as Helm v2 is no longer being updated, I hope that you are able to move to Helm v3 soon. 

This is what the output of `helm repo index chartname` looks like with Helm v3:
```
apiVersion: v1
entries: {}
generated: "2020-09-18T19:21:00.635121-05:00"
```

Please check https://helm.sh/blog/helm-v2-deprecation-timeline/ for details to help you move to Helm v2. Thanks.
