### ISSUE TITLE
Helm should be able to detect if the deployments were created by helm from elsewhere.

### ISSUE THREAD

**Issue by sureshpalemoni** [helm/helm#7768]
- If the helm chart is deployed from cloud service or market place to the kubernetes cluster, people should be able to list chart from there local machines on the same cluster.

- This would be easy to get the chart information or status or a provision to download the deployed chart.

**Comment by jdolitsky** [comment]
This could be done today with labels or deploying into different namespaces.

Are you suggesting any changes in terms of changes from Helm UX perspective? Change in `helm list`?

**Comment by sureshpalemoni** [comment]
Change in helm list. I know by providing labels we can get the objects.

For example: my private cloud has the option to install helm charts from its market place. However, if I really want to do  "helm list" from my local against the same cluster I cannot see those charts installed from UI(private cloud marketplace).

**Comment by mattfarina** [comment]
@sureshpalemoni There are a couple reasons this could be happening:

1. If you are using one major version of Helm and the cloud provider is using another. `helm list` is targeted at the same major version.
2. The cloud provider could be storing releases in a manner that is not the default. For example, they could be storing release information in an SQL database. This would make it inaccessible to you.

You could contact the cloud service support for more details. If their software is open source I could take a quick look and see if there is an obvious reason.

**Comment by bridgetkromhout** [comment]
Hi, @sureshpalemoni - without further detail about your cloud provider, we cannot test what they are doing. As suggested above, you could ask their support team for more info. 

If the suggestions of labels and namespaces do not provide you enough latitude to accomplish your goals, you could file a [Helm Improvement Proposal](https://github.com/helm/community/blob/master/hips/hip-0001.md) detailing your preferred changes to `helm list`.

Thanks for your feedback! I'll close this issue now and look forward to a future HIP if desired.
