### ISSUE TITLE
Empty result after template error deletes deployments

### ISSUE THREAD

**Issue by micw** [helm/helm#7769]
On Helm3, error handling seems to be seriously broken. On issues in templates (e.g. referencing a non-declared variable like `{{ xyz }}`) no error is raised. Instead, the resulting template is empty, helm continues the deployment end removes every deployed resource!

Output of `helm version`:

version.BuildInfo{Version:"v3.1.0", GitCommit:"b29d20baf09943e134c2fa5e1e1cab3bf93315fa", GitTreeState:"clean", GoVersion:"go1.13.8"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"archive", BuildDate:"2020-02-29T16:37:45Z", GoVersion:"go1.14", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Bare metal (Rancher2)

**Comment by bacongobbler** [comment]
Have you tested with a more recent version, like 3.1.2? I’m fairly certain this was patched and fixed in 3.1.1.

**Comment by sstock** [comment]
It is a bug in 3.1.0, fixed by #7593.
