### ISSUE TITLE
Please provide an equivalent of the "kubectl create [configMap | secret] --from-env-file.."

### ISSUE THREAD

**Issue by titou10titou10** [helm/helm#7772]
Helm provides a way to mimic the`"--from-file"`option for the`kubectl create [configMap | secret]...`command via the`"Files.AsConfig()"`or`"Files.AsSecrets()"`stanzas

But there is no equivalent of the`"kubectl create  [configMap | secret] --from-env-file"`command

Please provide a way to mimic `"kubectl create [configMap | secret] --from-env-file.."`

Of course in case of secrets, only the "values" of the "properties" should be base64 encoded

Q: in the meantime, is there workaround to achieve the same result?

**Comment by bridgetkromhout** [comment]
Hi, @titou10titou10 - I'm closing this issue because we now have a recommended path forward for proposals: if you'd like to formally propose this idea, please file a [Helm Improvement Proposal](https://github.com/helm/community/blob/master/hips/hip-0001.md) to discuss it with the community. Thanks!
