### ISSUE TITLE
Speed up helm in CI/CD pipelines by caching repo updates

### ISSUE THREAD

**Issue by cep21** [helm/helm#7773]
My company has lots of helm charts that we build and lint inside our CI/CD pipelines.  Currently, one of those steps is `helm dep build  .`.  This step is very slow because each time it executes for each helm chart, it also refreshes chart repositories `Hang tight while we grab the latest from your chart repositories...`.

I understand this has to happen once, but ideally we would be able to refresh once and then not refresh again in our CI/CD pipelines.  This would greatly speed up how fast we can deploy helm charts.

**Comment by cep21** [comment]
Would you accept a pull request for a flag to disable the refresh step during `helm dep build` ?

**Comment by technosophos** [comment]
Yes

**Comment by bridgetkromhout** [comment]
Hi, @cep21 - as we stated, we would accept a pull request for a flag to disable the refresh step during `helm dep build`. As this issue is inactive, we're closing it at this time. If you decide to send such a pull request, you can reference this issue and we'll re-open it. Thanks!

**Comment by shapeofarchitect** [comment]
@bridgetkromhout @cep21  Just checking if this is still a request to open pull request for this feature ? It's really becoming a requirement for us now .

**Comment by cep21** [comment]
I didn't get to it.  Would love to see it get merged in!

**Comment by Ornias1993** [comment]
This would be a significant upgrade for bigger chart repo's tbh...
