### ISSUE TITLE
Incorrect RegistryConfig location and expose RegistryCache location via envVar

### ISSUE THREAD

**Issue by waveywaves** [helm/helm#7776]
Output of `helm version`:
version.BuildInfo{Version:"v3.1+unreleased", GitCommit:"26830942d275b3a70edfdc32474230f3499a18e4", GitTreeState:"dirty", GoVersion:"go1.13.4"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}                                                 
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

Output of `helm env` provides the following output.
```
$ helm env 
...
HELM_REGISTRY_CONFIG="/home/vbobade/.config/helm/registry.json"
...
```
I wasn't able to find the registry config and am guessing that this isn't created and also noticed that the registry location isn't exposed via an envVar. This should be done via env var.

The registry cache is located on my system at `/home/vbobade/.cache/helm/registry/cache`

**Comment by bacongobbler** [comment]
> I wasn't able to find the registry config and am guessing that this isn't created and also noticed that the registry location isn't exposed via an envVar. This should be done via env var.

If present, ~/.docker/config.json is read as the default. After which, Helm falls back to the filepath listed in `HELM_REGISTRY_CONFIG`. This is to allow Helm to read login credentials provided from `docker login`, `az acr login`, etc.

We don't allow explicitly changing the registry cache. Users can change the cache directory by changing the value of `$XDG_CACHE_HOME`.

For example:

```
$ XDG_CACHE_HOME=/tmp helm env
HELM_BIN="helm"
HELM_DEBUG="false"
HELM_KUBECONTEXT=""
HELM_NAMESPACE="default"
HELM_PLUGINS="/home/bacongobbler/.local/share/helm/plugins"
HELM_REGISTRY_CONFIG="/home/bacongobbler/.config/helm/registry.json"
HELM_REPOSITORY_CACHE="/tmp/helm/repository"
HELM_REPOSITORY_CONFIG="/home/bacongobbler/.config/helm/repositories.yaml"
```

The only value that can be changed is the value of `HELM_REPOSITORY_CACHE`, and that's due to legacy concerns from Helm 2. I don't believe we should be exposing another environment variable to change the cache path unless there's a compelling reason to do so.

**Comment by waveywaves** [comment]
Okay, thanks for the clarification @bacongobbler wrt registry config.

When using the experimental `helm chart` feature, seems that the config being used is from `/home/vbobade/.cache/helm/registry/cache` 

If not an env var this should be easily locatable with a function under `helmpath`.

**Comment by bridgetkromhout** [comment]
Hi, @waveywaves! Thanks for looking into this; as your question has been answered, I'll resolve this issue now. If you'd like to open a [Helm Improvement Proposal](https://github.com/helm/community/blob/master/hips/hip-0001.md) with your ideas about how configs should work, that could be a useful discussion in the community.
