### ISSUE TITLE
Helm list did not show dependency release

### ISSUE THREAD

**Issue by liuyangc3** [helm/helm#7778]
Output of `helm version`:  
```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```
Output of `kubectl version`: 
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-aliyun.1", GitCommit:"51888f5", GitTreeState:"", BuildDate:"2019-10-16T08:29:13Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AliCloud managed k8s

I added  `dependencies` in Chart.yaml, after install this chart, run `helm list` only shows current chart release, but not dependency release. but I can see the dependency pods through `kubectl`, they are deployed too.

**Comment by bacongobbler** [comment]
Did you remember to run `helm dependency update` first?

**Comment by bacongobbler** [comment]
Dependencies are not deployed as a separate release. When you include a dependency in your chart, you are including all of that dependency’s templates, rendering all at once. The result is one release object.

Hope that helps.
