### ISSUE TITLE
Cannot add helm repository

### ISSUE THREAD

**Issue by mojochao** [helm/helm#7781]
I am trying to add a helm repository as follows:

    $ helm repo add traefik-helm-chart "git+https://github.com/containous/traefik-helm-chart@?ref=master"
    Error: unknown command "home" for "helm"
    Run 'helm --help' for usage.
    Error: looks like "git+https://github.com/containous/traefik-helm-chart@?ref=master" is not a valid chart repository or cannot be reached: plugin "helm-git" exited with error

I understand that this problem may be in the [helm-git](https://github.com/aslafy-z/helm-git) plugin, but my version of that plugin has not changed, and this used to work up until quite recently.

I don't see any `helm home` command, so I'm assuming this is coming from the plugin.  Since this used to work, did `helm` recently remove a `home` subcommand? 

Output of `helm version`:

    $ helm version
    version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}

    $ helm plugin list
    NAME    	VERSION	DESCRIPTION
    diff    	3.1.1  	Preview helm upgrade changes as a diff
    helm-git	0.5.0  	Get non-packaged Charts directly from Git.
    registry	0.7.0  	This plugin provides app-registry client to Helm.
        	       	usage:
        	       	  $ helm reg...

Output of `kubectl version`:

    $ kubectl version
    Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T23:41:24Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
    Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

AWS EKS 1.14

**Comment by bacongobbler** [comment]
From the sounds of it, the helm-git plugin is not compatible with Helm 3.

closing in favour of https://github.com/aslafy-z/helm-git/issues/77. Please follow up with the plugin maintainer. Thanks.
