### ISSUE TITLE
helm install return Error: no available release name found

### ISSUE THREAD

**Issue by xiaolixi** [helm/helm#7783]
I created a cahrt, and type 

> helm install mychart
Error: no available release name found

It doesn't seem to be due to RBAC authority. What shall I do? 

helm version
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```
helm version
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by hickeyma** [comment]
@xiaolixi It looks like to have a type on the command. It should be: `helm install mychart`

Can you try that and see if it works?

**Comment by xiaolixi** [comment]
> @xiaolixi It looks like to have a type on the command. It should be: `helm install mychart`
> 
> Can you try that and see if it works?

Thank you. I can't find the reason. I used helm3 instead

**Comment by hickeyma** [comment]
ok, you description showed Helom v2 for some reason.

If you are using Helm v3, then you need to specify the release name.
e.g. `helm install mychart chart/`

You can add flag `--help` for details on a command or checkout  [Helm docs](https://helm.sh/docs/)

**Comment by hickeyma** [comment]
Closing as question answered
