### ISSUE TITLE
Cannot get namespace resource in API group

### ISSUE THREAD

**Issue by TRIPTI2110** [helm/helm#7784]
I am trying to deploy zenko on Google Kubernetes Engine Cluster.

I have used "helm dependency build zenko/" to build the zenko dependency from "https://github.com/scality/Zenko". 
When I implement the following command on the cloud shell: 
helm install --name zenko --set ingress.enabled=true zenko

This error is encountered "Error: release zenko failed: namespaces "default" is forbidden: User "system:serviceaccount:kube-system:tiller" cannot get resource "namespaces" in API group "" in the namespace "default"

How can I proceed?

**Comment by hickeyma** [comment]
@TRIPTI2110 This sounds like Helm is not set-up correctly for GKE. Did you follows these [guidelines](https://v2.helm.sh/docs/using_helm/#gke) when setting up Helm?

**Comment by mattfarina** [comment]
@TRIPTI2110 What version of Helm are you using?

There is a known issue with Tiller in GKE. I plan to release a version of Helm v2 today with a fix in it. I'll circle back and comment here when it's out. That _may_ provide some help.

**Comment by bridgetkromhout** [comment]
Hi, @TRIPTI2110 - as mentioned above, we released fixes for the Helm v2 issue we think you were running into.

As Helm v2 support is ending, hopefully you are moving to v3. Please look at https://helm.sh/blog/helm-v2-deprecation-timeline/ and plan your migration.
