### ISSUE TITLE
`helm show values` should have a way to specify what values to show

### ISSUE THREAD

**Issue by user-name-is-taken** [helm/helm#7787]
`Helm show values` doesn't have a way to specify which values you want to output. It would be nice to have this because  tools like bash don't have a yaml parser natively so to get a specific value from a chart I have to download a yaml parser. I believe helm should have this integrated because helm seems to be using something like this for `helm install --set` already.

**Comment by bacongobbler** [comment]
Hmm... A new jsonpath output format similar to Kubernetes might be useful for this use case.

**Comment by bacongobbler** [comment]
@waveywaves we do appreciate the help. But, you've assigned yourself to multiple tickets in the queue at this point. Before assigning yourself to another ticket, can you please address the first few tickets you assigned yourself to?

I'm looking specifically at https://github.com/helm/helm/issues/assigned/waveywaves and noticed there are several issues you've assigned yourself to, but haven't addressed.

**Comment by waveywaves** [comment]
@bacongobbler I working on clearing all the issues I have picked up on priority. Will do that next time I pick up issues.
