### ISSUE TITLE
I want to access to depenency context

### ISSUE THREAD

**Issue by Samet-MohamedAmin** [helm/helm#7790]
I'm using helm version 3. In one of my charts I'm using postgresql as dependencies.
I want to access to its properties from the parent chart.
How can I change the context to the dependency chart?

**Comment by bacongobbler** [comment]
In the parent chart, you may modify a dependency’s values through its name.

Here’s an example from the stable charts repository: https://github.com/helm/charts/blob/master/stable/wordpress/values.yaml#L343

In your case, it would be

```
postgresql:
  foo: bar
```

If you want to access those values from within the context of the template, use `.Values.postgresql.foo`.

Does that answer your question?

**Comment by Samet-MohamedAmin** [comment]
I need to access to the value of `{{- define "postgresql.username" -}}` which is defined inside postgresql `_helpers.tpl` file.

**Comment by bacongobbler** [comment]
`define` declares a function call. Have you tried calling that function? The documentation should have examples demonstrating how to call a helper function.
