### ISSUE TITLE
dealing with failed releases when upgrade/install

### ISSUE THREAD

**Issue by schollii** [helm/helm#7793]
Output of `helm version`:

2.11

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.10", GitCommit:"37d169313237cb4ceb2cc4bef300f2ae3053c1a2", GitTreeState:"clean", BuildDate:"2019-08-19T10:44:49Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

AWS + kops

Issue: it is not clear (from the `upgrade --help` or the upgrade docs) what is the recommended way of dealing with prior failed releases when upgrading. It appears based on #3353 and #3208 that the recommended logic should be something like: 

1. attempt `helm upgrade --install`
2. if that fails with error message saying there are no deployments, do a `delete` + `install --replace`; if that fails, give up
3. if failed for some other reason, then print error and give up

Here is why I have not suggested the use of the following flags: 

1. `--force`: It seems that `upgrade --install --force` will do `delete` + `install --replace` *even* if the error is not about "no deployments exist"; this is not desired behavior (I suspect it is not desired in general, as the failure to upgrade might be legitimate, eg maybe a pvc is misconfigured and cannot be acquired). 
2. `--atomic`: if upgrade/install fails because of a legitimate problem in my chart (say a pv cannot be claimed, or even a timeout because didn't reaching READY state took longer than timeout time), it will automatically rollback, whereas I want to be able to investigate

With the above strategy, the following scenarios would work: 

1. first upgrade (which is in fact an install) fails because something wrong with chart: release is FAILED
2. second upgrade: attempt fails because first release is FAILED, and step 2 will be executed ie the first release will be automatically deleted (but not purged) and then replaced by a "third" upgrade release; 
2a) if this attempt succeeds, the final release of this "second" upgrade will be DEPLOYED
2b) whereas if it fails, second upgrade remains FAILED and the next upgrade will be a repeat of this logic 
3. third upgrade: if the previous releases are all FAILED, the same as second upgrade will happen; otherwise the most recent non-FAILED release will be used by helm to determine the diff and decide what to update

Is this correct? Any gotchas?

**Comment by bacongobbler** [comment]
If I'm not mistaken, this particular case was resolved with https://github.com/helm/helm/pull/7653, which will be in Helm 3.2.1. A `helm upgrade --install` should just work in this case. Let us know if this does not answer your question.
