### ISSUE TITLE
validation failed errors after upgrading to 2.16.4

### ISSUE THREAD

**Issue by amalucelli** [helm/helm#7797]
👋I upgraded to the recently `2.16.4` and now I'm getting this kind of error when I try to upgrade/install some chart:

```sh
Release "foo-elasticsearch" does not exist. Installing it now.
Error: validation failed: [services "elasticsearch" not found, services "elasticsearch-headless" not found, statefulsets.apps "elasticsearch" not found]
```

This was using the official `elasticsearch` chart, but I tried with different charts, even from the official channel and got the same error. I also tried in a `k3d` cluster and got the same problem.

Output of `helm version`:

```sh
Client: &version.Version{SemVer:"v2.16.4", GitCommit:"5e135cc465d4231d9bfe2c5a43fd2978ef527e83", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.4", GitCommit:"5e135cc465d4231d9bfe2c5a43fd2978ef527e83", GitTreeState:"clean"}
```

Output of `kubectl version`:

```sh
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.12", GitCommit:"4dde8f42b43042db3e662cdd2e707c0f922cae6e", GitTreeState:"clean", BuildDate:"2020-02-13T18:39:12Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  GKE

**Comment by terrych0u** [comment]
Same with me, I'm running AWS EKS 1.15 and upgrade my helm to 2.16.4, one of my charts also got the same issue. 

but, if I downgrade helm back to 2.16.3, and everything works again.

**Comment by jijeesh** [comment]
You can downgrade the helm version by using below steps

curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get > install-helm.sh
chmod u+x install-helm.sh
./install-helm.sh --version v2.16.3 
helm init --service-account tiller --wait --upgrade  --force-upgrade

**Comment by bacongobbler** [comment]
seeing an increased number of cases this morning reporting the same issue. Will look into this today.

**Comment by karuppiah7890** [comment]
My wild guess is this - commit - fe4ffcfa0b872c29df0fbe802ae2c60b7442e1fd . Still digging to understand the commit and how it broke only now. Also, this line is another guess - https://github.com/helm/helm/blame/c35b2b1cce5d14462aee04880f64ac3f09797630/pkg/kube/client.go#L211

**Comment by bacongobbler** [comment]
https://github.com/kubernetes/cli-runtime/blob/c5a29d532eb1b2cb01eabc7b67be1fb984579c65/pkg/resource/builder.go#L673-L677

**Comment by karuppiah7890** [comment]
Seems to me like the latest should be enabled only when it's an upgrade. For install - it will give an error saying object doesn't exist

**Comment by karuppiah7890** [comment]
I still didn't get the entire meaning or the feature of the latest. What it means by it will fetch the latest copy, then what's the usual? The only things I found out was the below in `vendor/k8s.io/cli-runtime/pkg/resource/builder.go`

```golang
if b.latest {
	// must set namespace prior to fetching
	if b.defaultNamespace {
		visitors = NewDecoratedVisitor(visitors, SetNamespace(b.namespace))
	}
	visitors = NewDecoratedVisitor(visitors, RetrieveLatest)
}
```

and the below in `vendor/k8s.io/cli-runtime/pkg/resource/visitor.go`

```golang
func RetrieveLatest(info *Info, err error) error {
	if err != nil {
		return err
	}
	if meta.IsListType(info.Object) {
		return fmt.Errorf("watch is only supported on individual resources and resource collections, but a list of resources is found")
	}
	if len(info.Name) == 0 {
		return nil
	}
	if info.Namespaced() && len(info.Namespace) == 0 {
		return fmt.Errorf("no namespace set on resource %s %q", info.Mapping.Resource, info.Name)
	}
	return info.Get()
}
```

**Comment by mattfarina** [comment]
`Latest()` was added in error. I spent a fair amount of time and trials making changes to figure out how to list resources and their status for the linked PR. `Latest()` was accidentally added to `Validate`. #7810 should fix it and did so in my testing.

**Comment by mattfarina** [comment]
Once we get this fix I can quickly get another release out.

**Comment by pbronneberg** [comment]
One issue which might be related (let me know, otherwise I'll post a new bug): when upgrading tiller to 2.16.4 we got the following messages when installing / upgrading deployments:
```bash
> helm upgrade myrelease . --install --dry-run -f values.secrets.yaml --namespace mynamespace

Release "myrelease" does not exist. Installing it now.
Error: namespaces "mynamespace" not found
```

This was solved when rolling back to tiller 2.16.1 (still have to try 2.16.3)

**Comment by htplbc** [comment]
2.16.3 worked for me. Thanks

**Comment by mattfarina** [comment]
Merged the fix. Release coming shortly.

**Comment by mattfarina** [comment]
2.16.5 is out with the fix.

**Comment by amalucelli** [comment]
All good here with `2.16.5`, thanks a lot @mattfarina!
