### ISSUE TITLE
helm default values nil pointer evaluating interface

### ISSUE THREAD

**Issue by jubeergon** [helm/helm#7802]
I try to use as many default values as possible in my helm chart to keep the values file as small as possible but still have as many configuration options as possible. 

For example: `port: {{ .Values.loadbalancer.port | default 80 }}`

But if I try to set all values of the same object via default I get an error. 
But as soon as I define a single value of this object in the Values file there is no more error. 

For example the object "Loadbalancer": 
```
  - protocol: {{ .Values.loadbalancer.protocol | default "TCP" }}
    port: {{ .Values.loadbalancer.port | default 80 }}
    targetPort: {{ .Values.loadbalancer.targetPort | default 8080}}
```
If no values for loadbalancers are defined in the values file I get the following error:
`  Error: template: x/templates/ext-loadbalancer.yaml:12:24: executing "x/templates/ext-loadbalancer.yaml" at <.Values.loadbalancer.protocol>: nil pointer evaluating interface {}.protocol
`
But if I add for example the following entry in the values file the chart can be installed without problems: 
```
loadbalancer: 
  protocol: TCP
```
What is the reason for this and what do I have to do to fill in all these values with defaults?

helm version:
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}

kubectl version:
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}

Cloud Provider/Platform: AKS

**Comment by bacongobbler** [comment]
When a template is being rendered, Helm takes the values file as input to generate a Values structure. Go's template system then takes that object as input.

In most cases, Go's template system understands when a root value like `.Values.restartPolicy` does not exist. However, when dealing with nested values (like the one in your example), the parent object (`.Values.loadbalancer`) was not present in the values file. Therefore, when Helm passed your values file to the rendering engine, the template system only knew about `.Values`, but `.Values.loadbalancer` was a `nil` object. In Go, calling a function on `nil` results in the error described above.


To fix this, either use a flat values structure, or place this in your values file to ensure the parent tree is present:

```
loadbalancer: {}
```

Hope this helps.
