### ISSUE TITLE
delete result ok

### ISSUE THREAD

**Issue by kfox1111** [helm/helm#7803]
I'm trying to script a deletion but continue on if the release doesn't exist. Currently if the release is not found, helm delete returns an error. Compounding this, there is no command to specifically look for the existence/non existence of a particular release. This makes it difficult to script/ci helm

My current work around is this which returns the proper error codes:
(! helm get values --namespace xxx yyy) || helm delete --namespace xxx yyy
But this is rather awkward.

Can we add a flag to delete called --not-exists-ok ? that returns 0 if the release does not exist?
Also, can we add a new subcommand
helm release-exists <releasename> that returns 0 if it exists and 1 otherwise?

**Comment by bacongobbler** [comment]
> Compounding this, there is no command to specifically look for the existence/non existence of a particular release.

`helm list`?

**Comment by bacongobbler** [comment]
> Also, can we add a new subcommand
> helm release-exists that returns 0 if it exists and 1 otherwise?

That use case could be handled as a simple plugin: https://helm.sh/docs/topics/plugins

In general, these small one-off features like the one suggested here are well-suited to be made as Helm plugins. That way we can reduce the maintenance burden on our end, but the community can extend Helm for their own specific use cases.

Hope this helps.

**Comment by kfox1111** [comment]
> > Compounding this, there is no command to specifically look for the existence/non existence of a particular release.
> 
> `helm list`, specifically `helm list --all-namespaces`?

helm ls and grepping out the release name is error prone to get correct. It does not make it easy to use helm in a CI/CD pipeline or shell script. Just mentioning it as CI/CD is one of the things Helm really enables and filing off that rough edge would help the use case.

> > Also, can we add a new subcommand
> > helm release-exists that returns 0 if it exists and 1 otherwise?
> 
> That use case could be handled as a simple plugin: https://helm.sh/docs/topics/plugins
> 
> In general, these small one-off features like the one suggested here are well-suited to be made as Helm plugins. That way we can reduce the maintenance burden on our end, but the community can extend Helm for their own specific use cases.
> 
> Hope this helps.

Again, if one of helm's primary use cases is ci/cd, making it as easy as possible to get into without needing to add lots of extra tools in order to get a basic workflow going would be beneficial. We are not talking about a significant amount of code being added to helm. Its basically a simpler version of 'helm get values 2&>/dev/null >/dev/null' as it doesn't actually need to fetch values and the cli isn't as ugly looking. Adding a few more lines of code in helm to eliminate to need to juggle plugins would be a win in my book. Its also much more obvious to the user how to actually do the task. It took me a while to settle on helm get values as a viable test instead of trying to grep it out of helm ls. This would save the user time making helm more valuable to the user.

There are other usability problems with plugins that we can get into, but probably not the right place to have the discussion.

**Comment by bacongobbler** [comment]
> Again, if one of helm's primary use cases is ci/cd

I think that's an unfair assessment to make here. Helm is a package manager. It is not a configuration management tool like Chef or Puppet. Helm certainly does provide certain features that are shared with such systems, though.

In other words, Helm is more focused to model similar package managers like brew, apt, yum, pacman, etc. It is not modeled against configuration management or ci/cd tools like Chef/Puppet.

**Comment by kfox1111** [comment]
Fair. I made an assumption. Sorry. I don't actually know how many folks use helm within CI/scripts. But I just know that the vast majority of the users here are using it through CI. I believe its also considered as a best practice in the K8s general community to use CI to load in workload. Generally helm has worked very well in CI to do that.

Anyway, its just feedback on how to potentially make it easier for a set of users of helm.Your free to not utilize it.
