### ISSUE TITLE
Install flag of the Upgrade action is not working on the sdk

### ISSUE THREAD

**Issue by Nitive** [helm/helm#7807]
### Not working code example

**Code**
```go
upgrade := action.NewUpgrade(actionConfig)
upgrade.Install = true

upgrade.Run("release", chart, values)
```

**Expected result:** chart deployed
**Actual result:** `Error: release has no deployed releases`

It's a rough example, but it seems to be enough for understanding the problem.
Happy to provide repository with minimal but complete code needed for reproduction if there is need for it.

### Cause of bug

This happens because install flag logic implemented in “main” package and tightly coupled with cli:
https://github.com/helm/helm/blob/193850a9e2c509acf1a499d98e8d23c12c134f11/cmd/helm/upgrade.go#L93-L97

---

Helm sdk version: 3.1.2

**Comment by liuming-tech** [comment]
> Actual result: `Error: release has no deployed releases`
this message tells us that the release exists, but status is not deployed.

`helm upgrade --install` install flag will work when no release exists.

**Comment by Nitive** [comment]
@liuming-tech cli is working fine, the issue is with go sdk usage

**Comment by technosophos** [comment]
The `Install` flag on `action/upgrade.go` does not do an install if the release is not present. See `cmd/upgrade.go` to see how `helm upgrade --install` works.

The `action`'s `Upgrade.Install` flag could definitely use some documentation. That is confusing.

**Comment by Nitive** [comment]
@technosophos, I can see that it works that way but there is two problems with that

1. To make `upgrade --install` from go sdk I have to repeat `cmd/upgrade.go` logic in my application
2. Like you said, current behavior is confusing and do not align with other actions

I could change the code to respect Install flag and create a PR, but it would be a breaking change. Minor one, but still. If I do create a PR, would it be considered to be a part of helm v3 or it have to be postponed until helm v4?

**Comment by bridgetkromhout** [comment]
Hi, @Nitive - as you may have seen, we added an inline explanation in https://github.com/helm/helm/pull/7834. 

The Helm project does follow strict SemVer so if we are going to make a breaking change, it will be in Helm v4. I'll resolve this issue at this time, and if you decide that working on v4 is something you'd like to do, we'd welcome your participation. Thanks!
