### ISSUE TITLE
OSX: Add repo failing with "net/http: TLS handshake timeout" for https://kubernetes-charts.storage.googleapis.com

### ISSUE THREAD

**Issue by inistor** [helm/helm#7808]
When running **helm 3.1.2** on macOS, adding the 'stable' main helm repo (https://kubernetes-charts.storage.googleapis.com) fails with error "net/http: TLS handshake timeout".
**macOS** version is **10.15.3**

```
ion@IN-MBP ~ % helm repo add stable https://kubernetes-charts.storage.googleapis.com 
Error: looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Get https://kubernetes-charts.storage.googleapis.com/index.yaml: net/http: TLS handshake timeout

```

Output of `helm version`:
```
% helm version 
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```
Output of `kubectl version`:
```
% kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Self-hosted K8S v1.17.4

**Comment by inistor** [comment]
Quick note, from the same machine, I can connect fine via TLS to the repo:
```
ion@IN-MBP ~ % openssl s_client -connect kubernetes-charts.storage.googleapis.com:443      
CONNECTED(00000005)
depth=2 OU = GlobalSign Root CA - R2, O = GlobalSign, CN = GlobalSign
verify return:1
depth=1 C = US, O = Google Trust Services, CN = GTS CA 1O1
verify return:1
depth=0 C = US, ST = California, L = Mountain View, O = Google LLC, CN = *.storage.googleapis.com
verify return:1
---
Certificate chain
 0 s:/C=US/ST=California/L=Mountain View/O=Google LLC/CN=*.storage.googleapis.com
   i:/C=US/O=Google Trust Services/CN=GTS CA 1O1
 1 s:/C=US/O=Google Trust Services/CN=GTS CA 1O1
   i:/OU=GlobalSign Root CA - R2/O=GlobalSign/CN=GlobalSign
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIHRjCCBi6gAwIBAgIRANodB+wBrIxYCAAAAAAyClkwDQYJKoZIhvcNAQELBQAw
QjELMAkGA1UEBhMCVVMxHjAcBgNVBAoTFUdvb2dsZSBUcnVzdCBTZXJ2aWNlczET
MBEGA1UEAxMKR1RTIENBIDFPMTAeFw0yMDAzMDMwOTQzMDVaFw0yMDA1MjYwOTQz
MDVaMHIxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH
Ew1Nb3VudGFpbiBWaWV3MRMwEQYDVQQKEwpHb29nbGUgTExDMSEwHwYDVQQDDBgq
LnN0b3JhZ2UuZ29vZ2xlYXBpcy5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw
ggEKAoIBAQC0gDG+/zDqZKf1gZaCrFqQ24QPZNpxJL6exvMt+Vcr/ja7cMxEs3Rx
vrQsZUO1PKj2MyxT6HoAgQUyYkNlYINgVhR9g3J0Gi/y7O76IPbTem/bE2F7VGT9
ywQ/W978jhPxxEQ+m6ppP0+tH5mnu1eL9eFjwa+i42U6R7Z5L6zaevZBAR8B3qh2
yffAYQvmJiEqfeIIB59mBokNj0oZIn6wvFLsFkTAhueWekUNrZn3tHFjpPmKQhvh
0ny+CzFYrDP6eu7oWjY2/bou2ZFj9adK7tUERgV86qYkW5A6hsrrDS/s3qhqshKL
pH5P+Yhyy2xYJCC/SnWI7mVWwLRH+uWlAgMBAAGjggQFMIIEATAOBgNVHQ8BAf8E
BAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADAdBgNVHQ4E
FgQUsAMqAqVWSc2Qoqfdf8pZroGgeVwwHwYDVR0jBBgwFoAUmNH4bhDrz5vsYJ8Y
kBug630J/SswZAYIKwYBBQUHAQEEWDBWMCcGCCsGAQUFBzABhhtodHRwOi8vb2Nz
cC5wa2kuZ29vZy9ndHMxbzEwKwYIKwYBBQUHMAKGH2h0dHA6Ly9wa2kuZ29vZy9n
c3IyL0dUUzFPMS5jcnQwggHIBgNVHREEggG/MIIBu4IYKi5zdG9yYWdlLmdvb2ds
ZWFwaXMuY29tgiQqLmFwcHNwb3QuY29tLnN0b3JhZ2UuZ29vZ2xlYXBpcy5jb22C
IiouY29tbW9uZGF0YXN0b3JhZ2UuZ29vZ2xlYXBpcy5jb22CKSouY29udGVudC1z
dG9yYWdlLWRvd25sb2FkLmdvb2dsZWFwaXMuY29tgicqLmNvbnRlbnQtc3RvcmFn
ZS11cGxvYWQuZ29vZ2xlYXBpcy5jb22CICouY29udGVudC1zdG9yYWdlLmdvb2ds
ZWFwaXMuY29tghAqLmdvb2dsZWFwaXMuY29tgiEqLnN0b3JhZ2UtZG93bmxvYWQu
Z29vZ2xlYXBpcy5jb22CHyouc3RvcmFnZS11cGxvYWQuZ29vZ2xlYXBpcy5jb22C
Hyouc3RvcmFnZS5zZWxlY3QuZ29vZ2xlYXBpcy5jb22CIGNvbW1vbmRhdGFzdG9y
YWdlLmdvb2dsZWFwaXMuY29tghZzdG9yYWdlLmdvb2dsZWFwaXMuY29tgh1zdG9y
YWdlLnNlbGVjdC5nb29nbGVhcGlzLmNvbYIPdW5maWx0ZXJlZC5uZXdzMCEGA1Ud
IAQaMBgwCAYGZ4EMAQICMAwGCisGAQQB1nkCBQMwLwYDVR0fBCgwJjAkoCKgIIYe
aHR0cDovL2NybC5wa2kuZ29vZy9HVFMxTzEuY3JsMIIBBAYKKwYBBAHWeQIEAgSB
9QSB8gDwAHUAsh4FzIuizYogTodm+Su5iiUgZ2va+nDnsklTLe+LkF4AAAFwn/32
3gAABAMARjBEAiAQr+Ynq1F6qatLKzT5eqLAT5wrvSAlW9QIdZjp9Flp4AIgTRZe
RhI8Pycd9Cuah4oQMilzDzLOxmhDB9osXqSIit0AdwBep3P531bA57U2SH3QSeAy
epGaDIShEhKEGHWWgXFFWAAAAXCf/fbIAAAEAwBIMEYCIQDDlbHk5sIdwnI/XDIQ
l4m39rd7FpYy3JG+vAMPfx2nIgIhAL8KKACEQPvxQ4wcYDeAg4DpTen96J0A9JUQ
Duap1MzMMA0GCSqGSIb3DQEBCwUAA4IBAQBSChbGGmAB0ZsRUwRfqcpk1QGaWDhk
7QFEL6X3b5iz+/mJbiKGacyGqNeQ/tBxYiBZOcGiKJqfcVBpDHcRTOXUn0qyjvLm
sUA7odV7+yIlosJdF9cIOTHUJZAbdZUuk7/xHBFXc8hDGe8mKhT23RrruHpdWTj7
wQ8Se0/suZCVZ+uTcy6gano5GaLWPQrtOx75X2Nt5Qxo/W/LqF5wUxLhPXUNcNLx
ybGU6L2Z1M+ZGrguHTxceew5r5dlmbDyvFwia+YUnMu0RKGbBXK7JERw8XRFVPpZ
CG1KTQUS1csCIEMbbkrvQIlYWC5SKx7xVWnyrEsLp0tpuxG4XmHr8ptz
-----END CERTIFICATE-----
subject=/C=US/ST=California/L=Mountain View/O=Google LLC/CN=*.storage.googleapis.com
issuer=/C=US/O=Google Trust Services/CN=GTS CA 1O1
---
No client certificate CA names sent
Server Temp Key: ECDH, X25519, 253 bits
---
SSL handshake has read 3643 bytes and written 281 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-CHACHA20-POLY1305
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-CHACHA20-POLY1305
    Session-ID: 496A54733F144C5BE3714A2263BACCA49379CF7860B3580B13FE0BEA486D5AE5
    Session-ID-ctx: 
    Master-Key: 0CC44214CB11BD40AE9E47A91E11513A0842FF2AA65F081CC4DA5D16860D977633E103E604E5FA7B6CA26C3117B1D8BF
    TLS session ticket lifetime hint: 100800 (seconds)
    TLS session ticket:
    0000 - 01 45 c4 2b 22 84 a0 6b-f8 a1 73 f7 1f d4 82 04   .E.+"..k..s.....
    0010 - a8 8d f5 07 46 b8 a8 4a-91 86 4c 57 46 e7 eb 24   ....F..J..LWF..$
    0020 - 06 be 13 f6 81 d4 55 a2-57 08 eb 43 a6 66 6c 3e   ......U.W..C.fl>
    0030 - ca b9 2c f0 fd 3e 95 62-6a 3e 0a bd 26 14 02 03   ..,..>.bj>..&...
    0040 - a5 8c 47 46 c3 83 35 67-b4 9f 64 8d 9a 70 67 5a   ..GF..5g..d..pgZ
    0050 - 86 a5 f4 d1 89 57 2d 15-99 42 dd f9 00 51 34 cb   .....W-..B...Q4.
    0060 - 49 dd 7a 28 0b de a6 9e-0b e2 30 93 47 2b 12 3a   I.z(......0.G+.:
    0070 - 95 74 8f 77 56 4a e7 4c-43 1c 57 0a a5 dc 20 ef   .t.wVJ.LC.W... .
    0080 - 9f 39 ec 56 46 f5 47 d6-50 7d e1 44 26 d5 67 89   .9.VF.G.P}.D&.g.
    0090 - 45 8c 69 e8 66 2d d2 6c-ea 2d 63 a0 ea 7b b3 23   E.i.f-.l.-c..{.#
    00a0 - ca 93 1e 29 db e2 5d 02-c1 3e 80 d7 a9 d0 b1 4a   ...)..]..>.....J
    00b0 - 0d cb 21 92 a3 2b 56 2a-70 2e 74 87 5c 22 8d a7   ..!..+V*p.t.\"..
    00c0 - f4 50 d0 01 14 e7 0e 1e-cb 03 7d 88 da 39 4a 9c   .P........}..9J.
    00d0 - 99 0b 23 21 37 f8 3a 86-42 72 90 22 86            ..#!7.:.Br.".

    Start Time: 1585131866
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
---
```

**Comment by mattfarina** [comment]
@inistor what version of macOS are you on?

**Comment by inistor** [comment]
@mattfarina macOS 10.15.3 (Catalina)

**Comment by inistor** [comment]
Interestigly enough, on a colleague's OSX, same version, with the same helm binary, the issue does not appear. So, it's likely a local (my os configuration) issue

**Comment by inistor** [comment]
Further info:
```
ion@IN-MBP % helm --debug search hub wordpress
search_hub.go:79: [debug] Get https://hub.helm.sh/api/chartsvc/v1/charts/search?q=wordpress: net/http: TLS handshake timeout
Error: unable to perform search against "https://hub.helm.sh"
helm.go:75: [debug] unable to perform search against "https://hub.helm.sh"
```

**Comment by bacongobbler** [comment]
hmm... Both work for me on my Macbook.

If you cannot verify the TLS cert for both Helm Hub (https://hub.helm.sh) and the charts repo (https://kubernetes-charts.storage.googleapis.com), I would tend to agree with your initial assessment about it being a localized issue.

Let us know what you find out.

**Comment by inistor** [comment]
Thanks, I'll check further. It would help if you could assist with instruction on a lower leved debug mode, so that I may trace, in the go code, where the problem may be.

**Comment by bacongobbler** [comment]
All I can offer is the developer guide: https://helm.sh/docs/community/developers/

If you compile helm from scratch, you can try to dig further into the issue. This may be further down the stack, however, likely somewhere in Go's [crypto/tls](https://golang.org/pkg/crypto/tls/) package.

**Comment by inistor** [comment]
Great, thanks; will follow-up if I find anything.

**Comment by inistor** [comment]
Something very peculiar: the one compiled from sources (v3.1.2 tag) works like a charm.
```
ion@IN-MBP helm % git status
HEAD detached at v3.1.2
nothing to commit, working tree clean

ion@IN-MBP helm % sudo cp bin/helm /usr/local/bin/helm.src

ion@IN-MBP helm % ls -la /usr/local/bin/helm.*
-rwxr-xr-x@ 1 root  wheel  42855848 Mar 12 20:39 /usr/local/bin/helm.dist
-rwxr-xr-x  1 root  wheel  42935484 Mar 25 23:34 /usr/local/bin/helm.src

ion@IN-MBP helm % helm.dist repo add stable https://kubernetes-charts.storage.googleapis.com 
Error: looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Get https://kubernetes-charts.storage.googleapis.com/index.yaml: net/http: TLS handshake timeout

ion@IN-MBP helm % helm.src repo add stable https://kubernetes-charts.storage.googleapis.com  
"stable" has been added to your repositories
```

**Comment by bacongobbler** [comment]
Interesting. How did you install helm initially?

If it was installed with homebrew, we have had situations arise where the version of helm compiled with homebrew had differing results as the “official” helm release binaries for macOS. Because homebrew chooses to recompile packages from source, this can lead to cases where helm is compiled with a different version of Go than what we targeted against.

**Comment by inistor** [comment]
Nope, I've downloaded the helm binary directly from releases tarball (https://github.com/helm/helm/releases). See md5sum below (helm.dist)
```
ion@IN-MBP helm % shasum -a 256 /usr/local/bin/helm.*
c619602190c014d507632c5873f9561817a31ed2bcabd019fbc6f98eb9e5e21c  /usr/local/bin/helm.dist
0b62e6f648113ef15bc45394512b8fe8569c2aee503a786d3c78d5f0f8f50526  /usr/local/bin/helm.src
```

**Comment by inistor** [comment]
Anyway, for me, the problem is solved (the sources-built binary is working fine). But I'm available to further verify the issue with the distribution binary - in case you feel it helps (maybe others may run into the same issue).

**Comment by hickeyma** [comment]
> But I'm available to further verify the issue with the distribution binary - in case you feel it helps (maybe others may run into the same issue).

@inistor That would be great if you can investigate it further. Lets leave it open until you return with some feedback.

**Comment by inistor** [comment]
Hi,

No progress - and I really don't see how I could make some, since, as I told you, the one built from the source is working fine. The binary downloaded from github (which causes the aforementioned error), however, does not have debug info so I can't dig into it.

What I've noticed, however, is that running the downloaded binary with "sudo" is working just fine.

Today I've also tried v3.2.0 - exactly the same outcome: the one downloaded exhibits the same behaviour while the one built from sources is working fine.

At this point, I'm helpless, so, if you consider this issue to be important enough for you (once again, my problem is solved, I have the one built from sources), I need a debug binary built by you - one that I can run with delve. Otherwise, we can close the issue.

Thanks again!

**Comment by bacongobbler** [comment]
Let's close for now. If other community members start raising the same issue, we can re-open this ticket and investigate further. I cannot reproduce this issue locally, so let's assume it's isolated to your local setup for now. Thanks!

**Comment by inistor** [comment]
Agreed, thanks again!

**Comment by sagarraob4u** [comment]
I am seeing below error:
Error: looks like "https://dl.bintray.com/pegasystems/pega-helm-charts" is not a valid chart repository or cannot be reached: Get https://dl.bintray.com/pegasystems/pega-helm-charts/index.yaml: net/http: TLS handshake timeout

helm version: v3.1.3.
tried with version v3.2.0 and v3.2.1 as well. same error.
Running on Mac OS: 10.3.6 (High Sierra)

**Comment by inistor** [comment]
Could you please try running the command with 'sudo'? Just to see that it's the same issue I've encountered.
Also, in my case, a build from source worked just fine - you may want to try that as well.

**Comment by sagarraob4u** [comment]
Thank you. Running with sudo user worked.

**Comment by inistor** [comment]
Another try, in debug mode:
```
ion@IN-MBP helm % helm.dist --debug repo add stable2 https://kubernetes-charts.storage.googleapis.com/
h2_bundle.go:8880: http2: Transport failed to get client conn for kubernetes-charts.storage.googleapis.com:443: http2: no cached connection was available
Error: looks like "https://kubernetes-charts.storage.googleapis.com/" is not a valid chart repository or cannot be reached: Get https://kubernetes-charts.storage.googleapis.com/index.yaml: net/http: TLS handshake timeout
helm.go:75: [debug] Get https://kubernetes-charts.storage.googleapis.com/index.yaml: net/http: TLS handshake timeout
looks like "https://kubernetes-charts.storage.googleapis.com/" is not a valid chart repository or cannot be reached
main.(*repoAddOptions).run
	/home/circleci/helm.sh/helm/cmd/helm/repo_add.go:131
main.newRepoAddCmd.func1
	/home/circleci/helm.sh/helm/cmd/helm/repo_add.go:67
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:74
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357
```
`GODEBUG=http2debug=1` is also set (see the first line).

The exact commit (to match the source lines in the stack trace) is d878d4d45863e42fd5cff6743294a11d28a9abce (v3.1.2).

The problem clearly originates in net/http, and is OSX related.
The report [here](https://discussions.agilebits.com/discussion/99219/error-net-http-tls-handshake-timeout) looks very similar. MacOS as well, certificate related.
In their case, it appears a '*' certificate was the culprit; for me, there is no such case.

The only difference between the binary compiled by me and the one downloaded from github could be the go compiler version.
@bacongobbler, could you please let me know what go version is helm using?

Thanks.

**Comment by christian-korneck** [comment]
I'm seeing the same issue with the latest helm3 version (v3.2.1) from github releases on macOS version 10.15.4 (= the latest stable macOS version).

**without** `sudo` any repo operations **fails** (i.e. adding/updating/etc a repo):

```
helm repo add stable https://kubernetes-charts.storage.googleapis.com --debug
Error: looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Get https://kubernetes-charts.storage.googleapis.com/index.yaml: net/http: TLS handshake timeout
helm.go:84: [debug] Get https://kubernetes-charts.storage.googleapis.com/index.yaml: net/http: TLS handshake timeout
[...]
```

**with** `sudo` these repo operations just **work** fine:

```
sudo helm repo add stable https://kubernetes-charts.storage.googleapis.com --debug
Password:
"stable" has been added to your repositories
```

As you usually want to run helm unprivileged I guess this is a bug?

**Comment by samkon** [comment]
It can be all about DNS configuration you're using as I use google dns. Reset your DNS configurations and try it again.

**Comment by inistor** [comment]
Well, that may be correct, but I've noticed in the latest version:
```
 ~ % helm version
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

The issue no longer appears:
```
~ % helm repo add stable https://charts.helm.sh/stable
"stable" has been added to your repositories
```

I must admit, I have no idea why the issue is gone; maybe it's related to the change from https://kubernetes-charts.storage.googleapis.com to https://charts.helm.sh/stable, maybe to the upgrade to Big Sur.

Nevertheless, in summary, on BigSur with helm 3.4.1, the problem no longer appears.

**Comment by inistor** [comment]
> It can be all about DNS configuration you're using as I use google dns. Reset your DNS configurations and try it again.

Could you please indicate what you mean by `reset your DNS configurations`?

**Comment by christian-korneck** [comment]
> on BigSur with helm 3.4.1, the problem no longer appears

same for me

**Comment by samkon** [comment]
> > It can be all about DNS configuration you're using as I use google dns. Reset your DNS configurations and try it again.
> 
> Could you please indicate what you mean by `reset your DNS configurations`?

I was facing the same issue. And removing DNS configuration on my network has just resolved the issue. With google dns I was not able to reach googleapis, weird one.
