### ISSUE TITLE
Render only manifests in given directory

### ISSUE THREAD

**Issue by avorima** [helm/helm#7809]
It would be nice if the `-s/--show-only` flag of `helm template` could understand `*` or directories. Currently it just returns `Error: could not find template ... in chart`.

Output of `helm version`:
```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2020-01-14T00:09:19Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  `kind`

**Comment by technosophos** [comment]
Fixing this would largely be a matter of writing regular expressions in `cmd/template.go` (Look for `showFiles`). I am marking it `good first issue` because I think someone new to Helm could probably give that a shot.
