### ISSUE TITLE
latest helm version is now 2.16.4 and no more 3.1.2

### ISSUE THREAD

**Issue by sdib** [helm/helm#7813]
Hi,

I had my CI/CD pipeline running last week (03/18) using an helm installer task configured to download latest version.
To find the latest, the task is gathering information from https://api.github.com/repos/helm/helm/releases/latest.

Today it returns 2.16.4 but last week it was 3.1.2. 

Is it expected ? 

Thanks,
Best regards

**Comment by bacongobbler** [comment]
Yes. Github’s API describes “latest” as the most recently released version of that repository. It does not correlate to the newest version of helm 3. We have no control over this API.
