### ISSUE TITLE
Helm deploying job with "helm.sh/hook": test hook annotation when installing release

### ISSUE THREAD

**Issue by EladioRodriguezVeve** [helm/helm#7818]
Output of `helm version`: v3.0.2

Output of `kubectl version`: 
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Docker for Desktop for Mac

So I was following the instruction from https://helm.sh/docs/topics/chart_tests/ but after I ran 'helm install my-release /path/to/helm/chart' and then 'kubectl get all' I could see that the job for the helm test was deployed even though it had the annotation "helm.sh/hook": test
I also tried the same annotation with the key without quotes like helm.sh/hook: test but it still deployed the job.

**Comment by bacongobbler** [comment]
Is this reproducible with a more recent version of Helm 3?

**Comment by EladioRodriguezVeve** [comment]
@bacongobbler I upgraded Helm to version 3.1.2 and still see that its deploying the job with the test hook annotation.

**Comment by donggangcj** [comment]
I can not repeat this issue, everything is ok and a resource will not be installed  when it  was annotated with `"helm.sh/hook": test`. can you provide the test chart?

**Comment by hickeyma** [comment]
I concur with @donggangcj, I am unable to reproduce this @EladioRodriguezVeve. When you upgrade to the latest Helm version, can you try repeating using a scaffold chart (`helm create`).  You will need to edit `templates/tests/test-connection.yaml`  to make the following change before the install:
`"helm.sh/hook": test-success` --> `"helm.sh/hook": test`

**Comment by bridgetkromhout** [comment]
Hi, @EladioRodriguezVeve - as we are not able to reproduce this, we are closing the issue. If you would like to provide a test chart that allows us to reproduce the issue, then we can investigate further. Thanks.
