### ISSUE TITLE
On release upgrade, values.yaml has to be explicitly added or changes will not be applied

### ISSUE THREAD

**Issue by strainovic** [helm/helm#7819]
If I want to upgrade the deployed app and I change something in values.yaml file, I have to specify it with --values values.yaml or changes will not be applied.

On the first install, I don't have to specify --values values.yaml if the file is in the same directory where the helm chart is.

Is this a bug or expected behavior?

Thanks!

Output of `helm version`:

`version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}`

Output of `kubectl version`:

`Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T21:04:32Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-16T16:36:25Z", GoVersion:"go1.12.14", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

CDK

**Comment by jdolitsky** [comment]
Hi there, the values.yaml file should not have to be specified on the command line. It is used as the baseline of values no matter what.

Could you try doing the upgrade without referencing the file? i.e. make a modification in values.yaml and do an upgrade, validating the change occurs as desired

**Comment by strainovic** [comment]
@jdolitsky Yes, that's right.

Unfortunately, I'm unable to reproduce this problem. Maybe I forgot to save values.yaml before I ran upgrade.

I'm closing this issue now. If it happens again, I'll re-open it.

Thanks!

**Comment by strainovic** [comment]
I think it is related to this:

https://medium.com/@kcatstack/understand-helm-upgrade-flags-reset-values-reuse-values-6e58ac8f127e

If I change something in values.yaml and I want to upgrade my release, I have to add --reset-values or --values values.yaml (this will implicitly add --reset-values flag). Otherwise, changes in values.yaml will be ignored.
