### ISSUE TITLE
Issue with looping through an array of maps in helm

### ISSUE THREAD

**Issue by jamesla** [helm/helm#7823]
I am trying to loop through a secrets and add them dynamically using helm templates 

I have the following values:
```
---
mySecret:
- myKey: myValue
- otherKey: otherValue
- AnotherKey: anotherValue
...
```

Originally I tried this:
```
---
apiVersion: v1
kind: Secret
metadata:
  name: mySecret
type: Opaque
data:
  {{- range $key, $value := .Values.mySecret }}
  {{ $key }} : {{$value | base64enc}}
  {{- end }}
```

However this doesn't work as the key was actually the index rather than the key and the value was the entire object rather than the value for that iteration of the loop.

I'm sure I am just missing something simple. Does anybody know how I can do this in helm?

**Comment by jdolitsky** [comment]
@jamesla - does this work for you?
```
---
apiVersion: v1
kind: Secret
metadata:
  name: mySecret
type: Opaque
data:
{{- range $k, $v := .Values.mySecret }}
{{- range $kk, $vv := $v }}
  {{ $kk }}: {{ $vv | b64enc }}
{{- end }}
{{- end }}
```

**Comment by jamesla** [comment]
Yup that was it thanks @jdolitsky
