### ISSUE TITLE
helm3 - error when deleting a deployment

### ISSUE THREAD

**Issue by hezise** [helm/helm#7825]
Output of `helm version`:
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Kubespray

when deleting a deployment I'm getting an error

helm3 delete adcc-infra-rook 
Error: uninstall: Release not loaded: adcc-infra-rook: release: not found

here is the output when I installed
Release "adcc-infra-rook" has been upgraded. Happy Helming!
NAME: adcc-infra-rook
LAST DEPLOYED: Thu Mar 26 13:24:40 2020
NAMESPACE: rook-ceph
STATUS: deployed
REVISION: 2
TEST SUITE: None

**Comment by hickeyma** [comment]
@hezise It might be because it is in namespace `rook-ceph`. Helm v3 releases are namespace based. Does this work: `helm3 delete adcc-infra-rook --namespace rook-ceph`?

**Comment by hezise** [comment]
that helped 
thank you
