### ISSUE TITLE
Helm installs the ingress-nginx problem

### ISSUE THREAD

**Issue by pptfz** [helm/helm#7826]
Kubeamd install kubernets1.17.4 helm2.16.3
Helm install stable/nginx-ingress --set controller.hostnetwork =true, rbac.create=true
Error: validation failed: spotted to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"

Say You just need change Deployment and StatefuSet apiVersion to apiVersion: apps/v1.
How exactly?

**Comment by mattfarina** [comment]
The `stable/nginx-ingress` chart detects your Kubernetes version. For 1.17.4 is should set the `apiVersion` to `apps/v1`. Somehow this is broken.

Can you run `kubectl version` to get the version of your Kubernetes cluster? And, can you run `helm repo update` to make sure you have the latest version of the chart.

You can find the source of the chart [here](https://github.com/helm/charts/tree/master/stable/nginx-ingress). Look for `deployment.apiVersion` in it to see what's happening.

**Comment by pptfz** [comment]
I have identified the need to change the apiVersion to apps/v1
I implemented the helm fetch stable/nginx-ingress and downloaded a nginx-ingress.tgz package. After unzipping, I modified the apiversion in the deployment. Yaml file
I just don't know how to apply my locally modified files
For example, how do I specify the application of my local files when I perform helm install

**Comment by pptfz** [comment]
i have identified the need to change the apiVersion to apps/v1
I implemented the helm fetch stable/nginx-ingress and downloaded a nginx-ingress.tgz package. After unzipping, I modified the apiversion in the deployment. Yaml file
I just don't know how to apply my locally modified files
For example, how do I specify the application of my local files when I perform helm install

Because if it is not specified, helm install will still use the default online warehouse. I want to specify the file that I modify locally

**Comment by technosophos** [comment]
`helm install` can take a path to a local file. (e.g. on mac: `helm install ./mychart`

**Comment by bridgetkromhout** [comment]
Hi, @pptfz - it looks like your questions were answered. One more thing to know before we resolve this issue: you were asking about Helm v2. Hopefully you have migrated to Helm v3. If you have not yet moved to version 3, please be aware that Helm v2 support will end very soon. More details: https://helm.sh/blog/helm-v2-deprecation-timeline/
