### ISSUE TITLE
Proposal: Provide DIFF column in `helm history`

### ISSUE THREAD

**Issue by waveywaves** [helm/helm#7828]
Currently we show the following output for `helm history <RELEASE>`.
```
$ helm history angry-bird
REVISION    UPDATED                     STATUS          CHART             APP VERSION     DESCRIPTION
1           Mon Oct 3 10:15:13 2016     superseded      alpine-0.1.0      1.0             Initial install
2           Mon Oct 3 10:15:13 2016     superseded      alpine-0.1.0      1.0             Upgraded successfully
3           Mon Oct 3 10:15:13 2016     superseded      alpine-0.1.0      1.0             Rolled back to 2
4           Mon Oct 3 10:15:13 2016     deployed        alpine-0.1.0      1.0             Upgraded successfully
```
We can also show a more verbose output with a DIFF column, which shows, the part (template or values.yaml) where the changes were made. Considering it is only a column we can keep the info minimal. Even though it would be minimal it would provide useful information to the users on the difference in Revisions.

**Comment by mattfarina** [comment]
@waveywaves How would you fit something like that into a column? For example, take a look at the [helm-diff plugin](https://github.com/databus23/helm-diff). There is far too much information to fit into a table like this. Can you mock up what you're thinking?

**Comment by waveywaves** [comment]
@mattfarina yes I can do that. Please assign this to me.

**Comment by technosophos** [comment]
Note that to add a column, you must add a flag (e.g. `--diff`) because changing default output formatting is considered a breaking change (since scripts parse and use this).

I went ahead and assigned this to you. Thanks!

**Comment by bridgetkromhout** [comment]
Hi, @waveywaves - Thank you for proposing an improvement to Helm. If you'd like, you can submit a Helm Improvement Proposal so as to work in the community to make your ideas a reality: https://github.com/helm/community/blob/master/hips/hip-0001.md - meanwhile, I will close this issue. Thanks!
