### ISSUE TITLE
[helm3] helm template with --output-dir doesn't write template with a hook to file

### ISSUE THREAD

**Issue by obolobova** [helm/helm#7836]
Output of `helm version`:
3.1.2

Output of `kubectl version`:
1.18.0

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
CentOS Linux release 7.7

The same problem still persists in Helm 3.1.2.
[https://github.com/helm/helm/issues/7001](url)

If a template contains hook annotation `helm template --output-dir mydir` works incorrectly.
It does not write generated text for template with a hook to the file.
Instead it prints the output to the console.

**Example**
```
cat init-job.yaml

apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  name: init
  ...

helm template --debug --output-dir /test/out -f values-my.yaml

install.go:158: [debug] Original chart version: ""
install.go:175: [debug] CHART PATH: /test/mychart

wrote /test/out/secret.yaml
wrote /test/out/service.yaml
...

---
# Source: init-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  name: init
  ...
```

**Comment by mattfarina** [comment]
I've replicated this bug on the tip of master. The linked issue that previously reported this and was closed does not appear to have a PR in 3.1.0 where it says it was fixed.

@obolobova thanks for reporting this.

**Comment by donggangcj** [comment]
Hi @ware you still interested in working on this issue?

**Comment by donggangcj** [comment]
@hickeyma  could you please review the PR ? thanks!😄

**Comment by donggangcj** [comment]
@bacongobbler  could you please review the PR if you are fee.
