### ISSUE TITLE
helm upgrade is better to respect the live spec.replicas value

### ISSUE THREAD

**Issue by tianchengli** [helm/helm#7837]
we use helm to upgrade a release, usually, the change is just the app version, and keep others same as before. `spec.replicas` is a required field for `statefulset`, so we must include it in the Chart, or it will have a default value of `1` if we delete it from the Chart.

the current `helm upgrade` will overwrite the live `spec.replicas` which is dynamically updated by `horizontalpodautoscaler`, for example, the value of `spec.replicas` in the Chart was 2, but it was eventually updated to 4 by the `horizontalpodautoscaler`. if we deploy a new version using helm upgrade, (we keep the original `spec.replicas` in the Chart, it is still `2`), the `spec.replicas` is changed back to 2, and kubenets  will terminate pod-3, pod-2, pod-1 once(, only keep pod-0), which is very dangerous. we want `helm upgrade` can respect the live `spec.replicas` in the cluster and ignore the value in the Chart, thus it can maintain the necessary pods to serve the current loads.

**Comment by DanOfir** [comment]
https://github.com/helm/helm/issues/7090#issuecomment-605682145

**Comment by hickeyma** [comment]
@tianchengli Is this answered in https://github.com/helm/helm/issues/7090#issuecomment-605759355 by @naseemkullah ?

**Comment by tianchengli** [comment]
remove `replicas` field completely, it will respect the replicas number managed by HPA.

**Comment by tianchengli** [comment]
@hickeyma yes, the workaround there works for me. thanks.
