### ISSUE TITLE
Binary releases content trust

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [helm/helm#7838]
Output of `helm version`: `2.16.5`

Output of `kubectl version`: no need of any `kubectl` infos to accurately describe my issue, plus it would not make sense to.

Cloud Provider/Platform (AKS, GKE, Minikube etc.): same as for `kubectl`

> of

Hi Helm Team, my issue is about installing helm, sha256sums of downloadable released binaries are corrupted or not managed : 

```bash
jbl@poste-devops-jbl-16gbram:~/siecle$ curl -LO https://get.helm.sh/helm-v2.16.5-linux-amd64.tar.gz.sha256
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    65  100    65    0     0     86      0 --:--:-- --:--:-- --:--:--    86
jbl@poste-devops-jbl-16gbram:~/siecle$ cat helm-v2.16.5-linux-amd64.tar.gz.sha256 
7cd54f56f787d62fd7311d5ae2c26e31310d37d27e3622014e5c769bec008cab
jbl@poste-devops-jbl-16gbram:~/siecle$ cat checksumsjbl 
7cd54f56f787d62fd7311d5ae2c26e31310d37d27e3622014e5c769bec008cab ./helm-v2.16.5-linux-amd64.tar.gz.sha256
jbl@poste-devops-jbl-16gbram:~/siecle$ sha256sum 
^C
jbl@poste-devops-jbl-16gbram:~/siecle$ sha256sum -c ./helm-v2.16.5-linux-amd64.tar.gz
sha256sum: ./helm-v2.16.5-linux-amd64.tar.gz: no properly formatted SHA256 checksum lines found
jbl@poste-devops-jbl-16gbram:~/siecle$ sha256sum -c ./checksumsjbl 
./helm-v2.16.5-linux-amd64.tar.gz.sha256: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
jbl@poste-devops-jbl-16gbram:~/siecle$ ls -allg
total 24708
drwxr-xr-x  2 jbl     4096 Mar 29 17:43 .
drwxr-xr-x 97 jbl    12288 Mar 29 17:36 ..
-rw-r--r--  1 jbl      106 Mar 29 17:41 checksumsjbl
-rw-r--r--  1 jbl 25273394 Mar 29 17:41 helm-v2.16.5-linux-amd64.tar.gz
-rw-r--r--  1 jbl       65 Mar 29 17:43 helm-v2.16.5-linux-amd64.tar.gz.sha256
jbl@poste-devops-jbl-16gbram:~/siecle$ 
```

So now I am bound to build helm from source to get a production grade secure installation of Helm.

Additionnaly, the build from source documentation is not obviously found. That is really unfriendly, if not surprising. 

As far as I can get, it looks like you are at the "just get the source and check my GPG signature on commits and or tags" level. 

I would gladly propose my contribution on providing documentation management into helm project, if desired.

**Comment by Jean-Baptiste-Lasselle** [comment]
Worth mentioning, I _had_ to open this issue to be able to justify additional workload due to this issue, to my management, plus to justify opening an entire pipeline infra so server costs etc...  : 

Without that, to explain, my management would go completely crazy : How can it cost so many servers to just deploy _one_ software to production ...???

**Comment by Jean-Baptiste-Lasselle** [comment]
What I propose : same signature on both binaries and not on binaries, but on the checksum files of binaries, as it is the case for example for `kubeone`.

**Comment by Jean-Baptiste-Lasselle** [comment]
Also what I want to mention to the Helm Team, is that I opened an issue related to this mechanism ont the `terraform` project, that you might want to take in considerations when dealing with this security feature, see https://github.com/hashicorp/terraform/issues/24498

**Comment by mattfarina** [comment]
@Jean-Baptiste-Lasselle The existing Helm v2 digest can be a bit difficult to work with. You are absolutely right. In Helm v3 we now have `.sha256sum` files for each download that is compatible with `shasum` and `sha256sum`. You can see an example [here](https://get.helm.sh/helm-v3.1.2-darwin-amd64.tar.gz.sha256sum). The new files already follow [the format you suggested](https://github.com/helm/helm/issues/7838#issuecomment-605659581).

In the original post I was not able to get a different hash. Here is what I did...

```sh
$ curl -LO https://get.helm.sh/helm-v2.16.5-linux-amd64.tar.gz.sha256
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    65  100    65    0     0     32      0  0:00:02  0:00:02 --:--:--    32

$ curl -LO https://get.helm.sh/helm-v2.16.5-linux-amd64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 24.1M  100 24.1M    0     0  9555k      0  0:00:02  0:00:02 --:--:-- 9558k

$ shasum -a 256 helm-v2.16.5-linux-amd64.tar.gz
7cd54f56f787d62fd7311d5ae2c26e31310d37d27e3622014e5c769bec008cab  helm-v2.16.5-linux-amd64.tar.gz

$ cat helm-v2.16.5-linux-amd64.tar.gz.sha256
7cd54f56f787d62fd7311d5ae2c26e31310d37d27e3622014e5c769bec008cab
```

The who hashes match.

Is there issue here that Helm v2 does not have `.sha256` files that are compatible with `shasum` and that all of this is not documented clearly enough?

Also note, on the [Helm releases listing](https://github.com/helm/helm/releases) you'll find the details needed for PGP verification of the downloads. Trust is more than hashes.

**Comment by Jean-Baptiste-Lasselle** [comment]
HI @mattfarina 
A quick first msg to say I very much appreciate the time and attention payed to this issue, so quickly : I indeed do care about bringing helm with the highest trust standards to my customers.

I will work with all informations you gave, and give you a feedback asap.

**Comment by Jean-Baptiste-Lasselle** [comment]
Hi @mattfarina To follow up the issue, until I close it : 
* Thank you so much for mentioning the checksums files format change in Helm v3, I indeed checked it : 

```bash
curl https://get.helm.sh/helm-v3.1.2-darwin-amd64.tar.gz.sha256sum

```
* Now let's check signature of either the binary, or the checksum file : 
  * The release mentions a public PGP key, claimed to be the one used to signed the releases assets. So we are looking for the signature, of any file in the release, so lets grab and import it, to be able to verify the signature : 

```bash
# --- # 
curl https://keybase.io/mattfarina/pgp_keys.asc?fingerprint=672c657be06b4b30969c4a57461449c25e36b98e > matts.pgp.key

gpg --import matts.pgp.key


```
  * there are `*.asc` signatures files for every binary and checksum files too.
  *  So I'll bet for the binary file having that endowed signature, let's test it out : 

```bash
export HELM_VERSION=3.1.2

# download the signatures first : 
curl -LO https://github.com/helm/helm/releases/download/v${HELM_VERSION}/helm-v${HELM_VERSION}-linux-amd64.tar.gz.sha256.asc
curl -LO https://github.com/helm/helm/releases/download/v${HELM_VERSION}/helm-v${HELM_VERSION}-linux-amd64.tar.gz.asc

# download the signed files then : 
curl -LO https://github.com/helm/helm/releases/download/v${HELM_VERSION}/helm-v${HELM_VERSION}-linux-amd64.tar.gz.sha256
curl -LO https://github.com/helm/helm/releases/download/v${HELM_VERSION}/helm-v${HELM_VERSION}-linux-amd64.tar.gz

# verify checksum file
gpg --verify ./helm-v${HELM_VERSION}-linux-amd64.tar.gz.sha256.asc ./helm-v${HELM_VERSION}-linux-amd64.tar.gz.sha256 || exit 1

# verify binary
gpg --verify https://github.com/helm/helm/releases/download/v${HELM_VERSION}/helm-v${HELM_VERSION}-linux-amd64.tar.gz.asc https://github.com/helm/helm/releases/download/v${HELM_VERSION}/helm-v${HELM_VERSION}-linux-amd64.tar.gz

```

**Comment by mattfarina** [comment]
@Jean-Baptiste-Lasselle Thank you for pointing out the bad signature. I have verified the issue. I am working to correct the problem.

**Comment by Jean-Baptiste-Lasselle** [comment]
@mattfarina I am the one thanking you for your brilliant work on Helm, and the entire Helm Team, and we are thousands thanking you all

**Comment by mattfarina** [comment]
@Jean-Baptiste-Lasselle I figured it out. The files themselves are not on GitHub. The downloads and signatures are on two different domains. The files and shas you can get by:

```
# download the signed files then : 
curl -LO https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz.sha256
curl -LO https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz.sha256sum
curl -LO https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz
```

When I got them from there verification worked.

**Comment by Jean-Baptiste-Lasselle** [comment]
> sha256sum

@mattfarina ok, thank you so very much, I'll check that asap and feed back.

**Comment by Jean-Baptiste-Lasselle** [comment]
@mattfarina 

Right : 

* I note that there is no signature distributed through the `get.helm.sh` distribution endpoint : 

```bash
jbl@poste-devops-jbl-16gbram:~/farina$ curl https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz.sha256sum.asc
<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:14773f1c-d01e-006f-4e96-0e47fd000000
Time:2020-04-09T17:41:30.3806310Z</Message></Error>jibl@poste-devops-jbl-16gbram:~/farina$ 
jbl@poste-devops-jbl-16gbram:~/farina$ 
```

* But assuming the `*.asc` from gtihub, do stand for the get.helm.sh endpoint, we have : 

```bash
jbl@poste-devops-jbl-16gbram:~/farina$ curl https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz.sha256sum.asc
<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:14773f1c-d01e-006f-4e96-0e47fd000000
Time:2020-04-09T17:41:30.3806310Z</Message></Error>jibl@poste-devops-jbl-16gbram:~/farina$ 
jbl@poste-devops-jbl-16gbram:~/farina$ curl -LO https://github.com/helm/helm/releases/download/v${HELM_VERSION}/helm-v${HELM_VERSION}-linux-amd64.tar.gz.sha256.asc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   652  100   652    0     0   2174      0 --:--:-- --:--:-- --:--:--  2173
100   833  100   833    0     0   1164      0 --:--:-- --:--:-- --:--:--  1164
jbl@poste-devops-jbl-16gbram:~/farina$ gpg --verify ./helm-v${HELM_VERSION}-linux-amd64.tar.gz.sha256.asc ./helm-v${HELM_VERSION}-linux-amd64.tar.gz.sha256sum
gpg: Signature made Thu 12 Mar 2020 07:44:01 PM CET
gpg:                using RSA key 711F28D510E1E0BCBD5F6BFE9436E80BFBA46909
gpg: BAD signature from "Matthew Farina <matt@mattfarina.com>" [ultimate]
jbl@poste-devops-jbl-16gbram:~/farina$ curl -LO https://github.com/helm/helm/releases/download/v${HELM_VERSION}/helm-v${HELM_VERSION}-linux-amd64.tar.gz.sha256sum.asc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   655  100   655    0     0   1800      0 --:--:-- --:--:-- --:--:--  1799
100   833  100   833    0     0   1055      0 --:--:-- --:--:-- --:--:--  1055
jbl@poste-devops-jbl-16gbram:~/farina$ gpg --verify ./helm-v${HELM_VERSION}-linux-amd64.tar.gz.sha256sum.asc ./helm-v${HELM_VERSION}-linux-amd64.tar.gz.sha256sum
gpg: Signature made Thu 12 Mar 2020 07:44:08 PM CET
gpg:                using RSA key 711F28D510E1E0BCBD5F6BFE9436E80BFBA46909
gpg: Good signature from "Matthew Farina <matt@mattfarina.com>" [ultimate]
jbl@poste-devops-jbl-16gbram:~/farina$ 

```
* So okay, now I know how to find the signature of Helm distributed signed binaries, on github.com. 
* I think you will now agree that : 
  * Yes, the documentation is far from cler on the subject, and needs an update.
  * Probably many will appreciate having github.com distributed binaries signed as well
  * Anyone would expect to fetch the signatures, from the same endpoint they dowloaded the bianries from. Because then, trusting the endpoint TLS Cert issuer / CA , is trusting the signature comes from the same person/organisation, than the binaries. 
  * So I agree we all have split personalities between work and github.com today, never the less,  TLS does not support schyzophrenia mode (fun idea though) :)  .

Thank you so very much for giving me at least one way to check signatures, and feed back so quickly, those will matter in the next weeks on a project I currently work.
