### ISSUE TITLE
Support to keep resources during `helm upgrade`

### ISSUE THREAD

**Issue by adamko147** [helm/helm#7839]
When working with service mesh systems (e.g. istio), it's often common practice you have multiple versions of service deployed (e.g. istio bookinfo sample app has 3 deployments of reviews app named reviews-v1, reviews-v2, reviews-v3). In real life the versions are not deployed at the same time, of course. If the deployment name in chart includes version (e.g. reviews-v1) it's not possible to deploy reviews-v2 and keep reviews-v1 from the same chart, unless you keep "reviews-v1" in the chart templates (that could be a bit complicated as the template might have version value and many other values set by CI/CD tools) or annotate the resource with `helm.sh/resource-policy: keep`, which would also prevent the resource being deleted during `helm uninstall`

I would suggest to introduce `helm.sh/resource-policy: retain` which would indicate that the resource should be kept during `helm upgrade`, but also deleted during `helm uninstall`.

**Comment by hickeyma** [comment]
The `helm.sh/resource-policy: keep` hook is currently available in Helm: https://helm.sh/docs/topics/charts_hooks/#hook-resources-are-not-managed-with-corresponding-releases

It is implemented both for `upgrade` and `delete` in Helm v2. PR #5225 might need to be ported to v3 (for `upgrade`).

Does this support your use case?

**Comment by adamko147** [comment]
@hickeyma potentially yes, however I would like to keep the resources managed by helm, so I can take advantage of helm actions like `delete`, `rollback` etc ...
The desired behavior would be sth like
```
$ helm install chart chart-v1.tgz
$ helm list
NAME    REVISION  STATUS    CHART
chart   1         deployed  chart-v1
$ kubectl get deployments
NAME
deployment-v1
```
during upgrade, I would like to keep the deployment-v1, so
```
$ helm upgrade chart chart-v2.tgz
$ helm list
NAME    REVISION  STATUS    CHART
chart   2         deployed  chart-v2
$ kubectl get deployments
NAME
deployment-v1
deployment-v2
```
Also, helm rollback and delete would work as the deployment is part of the chart
```
$ helm rollback chart
$ helm list
NAME    REVISION  STATUS    CHART
chart   3         deployed  chart-v1
$ kubectl get deployments
NAME
deployment-v1
```
and 
```
$ helm delete chart
$ helm list
No resources found
$ kubectl get deployments
No resources found
```

I've already tried to play with helm3 from latest master which has support for  `helm.sh/resource-policy: keep`, and seems that `keep` policy works for upgrade, however there is another issues around `helm rollback`, which give me and error in rollback scenario

``` 
$ helm install chart chart-v1.tgz
NAME: chart
STATUS: deployed
REVISION: 1
$ helm upgrade chart chart-v2.tgz
NAME: chart
STATUS: deployed
REVISION: 2
 $ helm rollback chart
Error: no Deployment with the name "chart-v1" found
```
but that might be different issue. I will follow up on this with new issue after digging into what's causing that  I will try to simulate the rollback error with and open an issue if I don't find the problem in my chart

**Comment by hickeyma** [comment]
If I understand this correctly @adamko147, does `helm.sh/resource-policy: keep` retain resources for all your use cases except `rollback`?

**Comment by adamko147** [comment]
> If I understand this correctly @adamko147, does `helm.sh/resource-policy: keep` retain resources for all your use cases except `rollback`?

Seems yes, investigation the rollback now.

**Comment by hickeyma** [comment]
Resources will be deleted if the keep is removed.

**Comment by adamko147** [comment]
so for delete I need `pre-delete` hook to exec `kubectl annotate deployments -l "part-of: chart" helm.sh/resource-policy-`... That could work. Thanks!

**Comment by hickeyma** [comment]
I think it would be beneficial to update the issue to better describe the issue to the community.  What do you think about calling it a feature with title of "Add support to keep resources during `helm rollback`"?

**Comment by adamko147** [comment]
I think the `helm rollback` is another issue. So far it seems to me that resource annotated with "helm.sh/resource-policy: keep" fails the rollback. the debug log from `helm rollback` is
```
rollback.go:60: [debug] preparing rollback of backend-app
rollback.go:108: [debug] rolling back backend-app (current: v2, target: v1)
rollback.go:67: [debug] creating rolled back release for backend-app
rollback.go:73: [debug] performing rollback of backend-app
client.go:166: [debug] checking 2 resources for changes
rollback.go:166: [debug] warning: Rollback "backend-app" failed: no Deployment with the name "backend-r1" found
Error: no Deployment with the name "backend-r1" found
helm.go:95: [debug] no Deployment with the name "backend-r1" found
helm.sh/helm/v3/pkg/kube.(*Client).Update.func1 
...
```
deployment `backend-app-r1` was created during install `v1`, but I would expect the `rollback` to delete `backend-app-r2` as that is what was deployed by second release `v2`.
I will create a separate issue for that

**Comment by adamko147** [comment]
> @adamko147 I think it would be beneficial to update the issue to better describe the issue to the community. What do you think about calling it a feature with title of "Add support to keep resources during `helm rollback`"?

I think if the rollback found the resources from v1 and wouldn't stop exception, `v2` would be kept anyway due to "keep" policy, at least I think that `KubeClient.Update` is used in rollback as well

**Comment by yelhouti** [comment]
I was wondering why I couldn't do this, and here you are asking for the same thing. This quit useful for storing a database password in a secret and having the database and it's dependents keep working on upgrade (without hard coding the password in the config)
I would love having this features +1

**Comment by hickeyma** [comment]
@yelhouti Did you try using the `helm.sh/resource-policy: keep` (hook)[https://helm.sh/docs/topics/charts_hooks/#hook-resources-are-not-managed-with-corresponding-releases]?

**Comment by yelhouti** [comment]
@hickeyma it is actually not what I want, I want it the secret to be delete if I uninstall the chart, but not changed if I upgrade...

**Comment by bridgetkromhout** [comment]
Hi, @adamko147 & @yelhouti - it seems you may have some remaining features you would like. Thank you for your ideas to improve Helm. If you'd like, you can submit a Helm Improvement Proposal so as to work in the community to make your ideas a reality: https://github.com/helm/community/blob/master/hips/hip-0001.md - meanwhile, I will close this issue. Thanks!
