### ISSUE TITLE
go get helm.sh/helm/pkg/action faild

### ISSUE THREAD

**Issue by OojaxoO** [helm/helm#7842]
Output of `helm version`: 3.1.2

Output of `kubectl version`: 1.13.5

Cloud Provider/Platform (AKS, GKE, Minikube etc.): centos

$go get helm.sh/helm/pkg/action
package helm.sh/helm/v3/internal/experimental/registry: unrecognized import path "helm.sh/helm/v3/internal/experimental/registry" (parse https://helm.sh/helm/v3/internal/experimental/registry?go-get=1: no go-import meta tags ())
package helm.sh/helm/v3/pkg/chart: unrecognized import path "helm.sh/helm/v3/pkg/chart" (parse https://helm.sh/helm/v3/pkg/chart?go-get=1: no go-import meta tags ())
package helm.sh/helm/v3/pkg/chart/loader: unrecognized import path "helm.sh/helm/v3/pkg/chart/loader" (parse https://helm.sh/helm/v3/pkg/chart/loader?go-get=1: no go-import meta tags ())
package helm.sh/helm/v3/pkg/chartutil: unrecognized import path "helm.sh/helm/v3/pkg/chartutil" (parse https://helm.sh/helm/v3/pkg/chartutil?go-get=1: no go-import meta tags ())
package helm.sh/helm/v3/pkg/cli: unrecognized import path "helm.sh/helm/v3/pkg/cli" (parse https://helm.sh/helm/v3/pkg/cli?go-get=1: no go-import meta tags ())
package helm.sh/helm/v3/pkg/downloader: unrecognized import path "helm.sh/helm/v3/pkg/downloader" (parse https://helm.sh/helm/v3/pkg/downloader?go-get=1: no go-import meta tags ())
package helm.sh/helm/v3/pkg/engine: unrecognized import path "helm.sh/helm/v3/pkg/engine" (parse https://helm.sh/helm/v3/pkg/engine?go-get=1: no go-import meta tags ())
package helm.sh/helm/v3/pkg/getter: unrecognized import path "helm.sh/helm/v3/pkg/getter" (parse https://helm.sh/helm/v3/pkg/getter?go-get=1: no go-import meta tags ())
package helm.sh/helm/v3/pkg/kube: unrecognized import path "helm.sh/helm/v3/pkg/kube" (parse https://helm.sh/helm/v3/pkg/kube?go-get=1: no go-import meta tags ())
package helm.sh/helm/v3/pkg/kube/fake: unrecognized import path "helm.sh/helm/v3/pkg/kube/fake" (parse https://helm.sh/helm/v3/pkg/kube/fake?go-get=1: no go-import meta tags ())
package helm.sh/helm/v3/pkg/lint: unrecognized import path "helm.sh/helm/v3/pkg/lint" (parse https://helm.sh/helm/v3/pkg/lint?go-get=1: no go-import meta tags ())
package helm.sh/helm/v3/pkg/lint/support: unrecognized import path "helm.sh/helm/v3/pkg/lint/support" (parse https://helm.sh/helm/v3/pkg/lint/support?go-get=1: no go-import meta tags ())
package helm.sh/helm/v3/pkg/postrender: unrecognized import path "helm.sh/helm/v3/pkg/postrender" (parse https://helm.sh/helm/v3/pkg/postrender?go-get=1: no go-import meta tags ())
package helm.sh/helm/v3/pkg/provenance: unrecognized import path "helm.sh/helm/v3/pkg/provenance" (parse https://helm.sh/helm/v3/pkg/provenance?go-get=1: no go-import meta tags ())
package helm.sh/helm/v3/pkg/release: unrecognized import path "helm.sh/helm/v3/pkg/release" (parse https://helm.sh/helm/v3/pkg/release?go-get=1: no go-import meta tags ())
package helm.sh/helm/v3/pkg/releaseutil: unrecognized import path "helm.sh/helm/v3/pkg/releaseutil" (parse https://helm.sh/helm/v3/pkg/releaseutil?go-get=1: no go-import meta tags ())
package helm.sh/helm/v3/pkg/repo: unrecognized import path "helm.sh/helm/v3/pkg/repo" (parse https://helm.sh/helm/v3/pkg/repo?go-get=1: no go-import meta tags ())
package helm.sh/helm/v3/pkg/storage: unrecognized import path "helm.sh/helm/v3/pkg/storage" (parse https://helm.sh/helm/v3/pkg/storage?go-get=1: no go-import meta tags ())
package helm.sh/helm/v3/pkg/storage/driver: unrecognized import path "helm.sh/helm/v3/pkg/storage/driver" (parse https://helm.sh/helm/v3/pkg/storage/driver?go-get=1: no go-import meta tags ())
package helm.sh/helm/v3/pkg/time: unrecognized import path "helm.sh/helm/v3/pkg/time" (parse https://helm.sh/helm/v3/pkg/time?go-get=1: no go-import meta tags ())

**Comment by hickeyma** [comment]
@OojaxoO Can you try this instead:  `go get helm.sh/helm/v3`?  You might need to do the following replacement also:

```
replace (
        github.com/Azure/go-autorest => github.com/Azure/go-autorest v13.3.2+incompatible
        github.com/docker/distribution => github.com/docker/distribution v0.0.0-20191216044856-a8371794149d
)
```

**Comment by OojaxoO** [comment]
I want to write an http interface for helm, so i want to run "go get helm.sh/helm/v3/action", but it's faild: 'package helm.sh/helm/v3/internal/experimental/registry: unrecognized import path "helm.sh/helm/v3/internal/experimental/registry" (parse https://helm.sh/helm/v3/internal/experimental/registry?go-get=1: no go-import meta tags ())'

you say replace something  but i don't quite see your point.

**Comment by hickeyma** [comment]
@OojaxoO What is the output when you run `go get helm.sh/helm/v3`?

**Comment by OojaxoO** [comment]
package helm.sh/helm/v3/internal/experimental/registry: unrecognized import path "helm.sh/helm/v3/internal/experimental/registry" (parse https://helm.sh/helm/v3/internal/experimental/registry?go-get=1: no go-import meta tags ())

**Comment by OojaxoO** [comment]
now   it's ok
