### ISSUE TITLE
action.Install installs chart in Namespace, but deploys in kubecontext namespace.

### ISSUE THREAD

**Issue by Freyert** [helm/helm#7845]
I'm using the Go SDK. It's way easier to use now that we're not establishing tunnels to Tiller and everything appears much tidier. It seems though there might be some leaks in the abstraction to plug up though?

So I'm setting the Namespace like so:

```
installAction.Namespace = d.Namespace()
values := map[string]interface{}{}
_, err = installAction.Run(chartRequested, values)
```
My chart is registered in the Namespace I specify, but the resources are all deployed in the `default` namespace.

I've read some other issues that seem to indicate the kubecontext is used to deploy resources and the namespace setting only tells helm where to store its configuration.

The chart I'm using also probably has not been modified to work with helm3, but when I deploy it using the command line and specifying `-n` it works fine.

I'm assuming this means that the CLI is modifying the kubecontext to compensate via the EnvSettings.

Output of `helm version`: v3.1.2

Output of `kubectl version`:

Output of `go version`: `go version go1.13.4 darwin/amd64`

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by Freyert** [comment]
So it looks like the reason helm installs the chart config in the namespace I specify comes from here:
https://github.com/helm/helm/blob/v3.1.2/pkg/action/action.go#L223

Which I am doing.
```
	if err := actionConfig.Init(helmEnvSettings.RESTClientGetter(),
		d.Namespace(),
		helmDriver, debug); err != nil {
		return err
	}
```

**Comment by Freyert** [comment]
Logging the release indicates that the `Namespace` is not being added to the rendered documents.

```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: mongodb-replicaset
    chart: mongodb-replicaset-3.9.5
    heritage: Helm
    release: mongodb-integration
```

**Comment by mattfarina** [comment]
I'm glad the client experience works better for you.

The Helm CLI uses the SDK. Have you looked at how that's working? If not I would look at two places. First, there is the code where the install command happens. You can find it at https://github.com/helm/helm/blob/v3.1.2/cmd/helm/install.go. Then there is where action config is initialized. You can find that at https://github.com/helm/helm/blob/v3.1.2/cmd/helm/helm.go#L64

Helm has the capability to store the release in a different namespace from kubernetes objects. There are some who need to leverage that though it's not the most common case by far.

If your code is open source I would be happy to take a quick look and see if there is an obvious reason for your issue.

**Comment by Freyert** [comment]
@mattfarina I think I'm getting close to fixing this using the debugger. I've been following what the CLI does and with the debugger when it comes into `renderResources` the `Release` object in `chartutil.Values` has an empty `Namespace`.

![image](https://user-images.githubusercontent.com/449155/78034526-da3b4600-7335-11ea-896a-6351a3f7d73f.png)

**Comment by karuppiah7890** [comment]
Looks like namespace is not properly exposed to be set 😅 I think the main field to look over here is this one

https://github.com/helm/helm/blob/v3.1.2/pkg/cli/environment.go#L41

and I can see that it gets set by the `-n` flag here 

https://github.com/helm/helm/blob/v3.1.2/pkg/cli/environment.go#L64

and how it's accessed over here 

https://github.com/helm/helm/blob/v3.1.2/pkg/cli/environment.go#L113

But it's still `namespace` and not `Namespace`.

**Comment by hickeyma** [comment]
@Freyert The 2to3 plugin sets it as follows: https://github.com/helm/helm-2to3/blob/master/pkg/v3/connect.go#L42

**Comment by Freyert** [comment]
More debugger findings:

from `action.Install.Run`
![image](https://user-images.githubusercontent.com/449155/78035942-b973f000-7337-11ea-87e6-07e68aeac015.png)

**Comment by Freyert** [comment]
So from watching the debugger the namespace isn't being passed correctly here:

https://github.com/helm/helm/blob/master/pkg/chartutil/values.go#L144-L151

![image](https://user-images.githubusercontent.com/449155/78037099-191ecb00-7339-11ea-9814-3789ef71023f.png)

**Comment by bacongobbler** [comment]
One note to add here: it’s intentional that the namespace is not added to the manifests. It’s not required; you just need to set the kube client’s namespace parameter and the resources will be installed in the intended namespace: https://github.com/helm/helm/blob/master/pkg/kube/client.go#L136

In your code, how is your `kube.Client` initialized?

https://github.com/helm/helm/blob/master/pkg/cli/environment.go#L137

**Comment by Freyert** [comment]
I might be trimming some stuff out here from what I followed the CLI doing.

First initialize the settings the way the CLI is doing it because I don't really care to invent a new and nifty way to get config.

```
var (
	helmEnvSettings = cli.New()
)
```

Another pretty much straight rip from the CLI code.
```
	if err := actionConfig.Init(helmEnvSettings.RESTClientGetter(),
		d.Namespace(),
		helmDriver, debug); err != nil {
		return err
	}
```

**Comment by bacongobbler** [comment]
Try setting this parameter...

https://github.com/helm/helm/blob/master/pkg/kube/client.go#L61

**Comment by Freyert** [comment]
Looks like the reason those values are undefined in my screenshots from the debugger is because it can't properly evaluate the interface. So that's probably not the problem.

I'll try setting this parameter will have to dig around and figure out how.

**Comment by Freyert** [comment]
So quickest hackiest way to do it with my current setup which tries to emulate the CLI is to add:

`os.Setenv("HELM_NAMESPACE", "mongodb-integration")` before every re-initializing the envConfig which would have to be done on every new release deployed.

**Comment by Freyert** [comment]
I would expect setting the `Release` namespace to be respected in this case though as that variable is used in the chart as seen [here](https://github.com/helm/charts/blob/master/stable/mongodb-replicaset/templates/_helpers.tpl#L83-L93).

And why would you set `client.Namespace = settings.Namespace()` if it doesn't do anything?

https://github.com/helm/helm/blob/3706aa7ca666fda6d8301c55118fa1c092f124a2/cmd/helm/install.go#L223

**Comment by Freyert** [comment]
Seems like there's a lot to unpack here and the gist of it is it's probably not good to use the CLI's EnvironmentSettings function when driving the SDK. It seems to have a `run once` approach which works well for an invoked CLI, but not great from an SDK standpoint. That's just the perception I'm developing though.

**Comment by bacongobbler** [comment]
> And why would you set `client.Namespace = settings.Namespace()` if it doesn't do anything?

The namespace parameter is used in a few places across the install action. The kubernetes client is a separate client that needs to be initialized separately, which is probably why there's a bit of confusion over what that parameter does in this case since the kube client is initialized prior to calling the install action.

For example:

- we use it to set the in-memory driver's namespace on `--dry-run`: https://github.com/helm/helm/blob/783be10aef396150f8f5c0fbdd1d41751557e11e/pkg/action/install.go#L199
- it's used for `--create-namespace`: https://github.com/helm/helm/blob/783be10aef396150f8f5c0fbdd1d41751557e11e/pkg/action/install.go#L288
- it's used to create the release secret in the correct namespace: https://github.com/helm/helm/blob/783be10aef396150f8f5c0fbdd1d41751557e11e/pkg/action/install.go#L433

Your assessment is correct here though, the `cli` package is really meant to be used for the Helm CLI. If there are parts that can be refactored out of that package and turned into a more SDK-friendly  action config package, we'd be open to suggestions.

**Comment by Freyert** [comment]
@bacongobbler looks like it's in my best interest do explore that :D). Thank you for all this detail and opening the floor for a PR.

My personal feeling is that whatever the solution for the SDK is should also be leveraged by the CLI since that is currently the best way for new SDK users to understand how to use the SDK.

My very narrow vision here is to add a `Namespace(n string)` function to the EnvSettings, but I see this having a lot of issues if you want to run concurrently.

_Ideally_, install would respect `Release.Namespace` and inject that into the rendered templates as it was done in the past (is this right)? This seems to be the missing piece because helm deploys the release configuration into the directory I specify, but I have no knob to tell it where to deploy the kubernetes resources.

**Comment by Freyert** [comment]
I will close this one as a new issue to have a better configuration setup for the SDK is more appropriate.
