### ISSUE TITLE
YAML merge key not working in helm 2.15

### ISSUE THREAD

**Issue by nokia-t1zhou** [helm/helm#7855]
hi,

in the helm 2.15 version , the YAML merge key can't working, i used it in value.yaml, but --dry-run is failed
YAML merge key definition refer to:
https://yaml.org/type/merge.html

such as 
```
default: &default
  value1: 1
  value2: 2

hoge:
  <<: *default
  value3: 3
```
but in helm 2.13 version, this value.yaml can working, so please help me

Output of `helm version`:
2.15

**Comment by technosophos** [comment]
I have tested in both Helm 2 and Helm 3, and it seems to work in both.

How I did my test case:

1. `helm create issue7855`
2. Delete everything in `issue7855/templates/`
3. Create a template in `issue7855/templates/example.yaml`

```yaml
output: {{ .Values.outside.inside }}
data: {{ .Values.outside.value3 }}
```

Next, I created a `values-7855.yaml` file with this content:

```yaml
default: &default
  value1: 1
  inside: 2

outside:
  <<: *default
  value3: 3
```

Next, I did `helm template issue7855 -f values-7855.yaml`. It produced this:

```yaml
---
# Source: issue7855/templates/example.yaml
output: 2
data: 3
```

I tested with Helm 2 (`dev-v2` branch) and Helm 3 (`master` branch).

Can you either:
1. Test the process I just did, and respond with the error
2. Provide more information about your failure

I have verified that this works with Helm 2 `helm install --dry-run` by updating the `example.yaml` to the following:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: issue7855
data:
  output: {{ .Values.outside.inside }}
  data: {{ .Values.outside.value3 }}
```

The full output of `helm template` is:

```console
$ helm2 install --dry-run issue7855 -f values-7855.yaml -n test  --debug
[debug] Created tunnel using local port: '63629'

[debug] SERVER: "127.0.0.1:63629"

[debug] Original chart version: ""
[debug] CHART PATH: /Users/technosophos/Code/Go/src/helm.sh/helm/_scratch/issue7855

NAME:   test
REVISION: 1
RELEASED: Mon Apr  6 18:03:31 2020
CHART: issue7855-0.1.0
USER-SUPPLIED VALUES:
default:
  inside: 2
  value1: 1
outside:
  inside: 2
  value1: 1
  value3: 3

COMPUTED VALUES:
affinity: {}
autoscaling:
  enabled: false
  maxReplicas: 100
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
default:
  inside: 2
  value1: 1
fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  repository: nginx
imagePullSecrets: []
ingress:
  annotations: {}
  enabled: false
  hosts:
  - host: chart-example.local
    paths: []
  tls: []
nameOverride: ""
nodeSelector: {}
outside:
  inside: 2
  value1: 1
  value3: 3
podSecurityContext: {}
replicaCount: 1
resources: {}
securityContext: {}
service:
  port: 80
  type: ClusterIP
serviceAccount:
  annotations: {}
  create: true
  name: null
tolerations: []

HOOKS:
MANIFEST:

---
# Source: issue7855/templates/example.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: issue7855
data:
  output: 2
  data: 3
```

**Comment by nokia-t1zhou** [comment]
> I have tested in both Helm 2 and Helm 3, and it seems to work in both.
> 
> How I did my test case:
> 
> 1. `helm create issue7855`
> 2. Delete everything in `issue7855/templates/`
> 3. Create a template in `issue7855/templates/example.yaml`
> 
> ```yaml
> output: {{ .Values.outside.inside }}
> data: {{ .Values.outside.value3 }}
> ```
> 
> Next, I created a `values-7855.yaml` file with this content:
> 
> ```yaml
> default: &default
>   value1: 1
>   inside: 2
> 
> outside:
>   <<: *default
>   value3: 3
> ```
> 
> Next, I did `helm template issue7855 -f values-7855.yaml`. It produced this:
> 
> ```yaml
> ---
> # Source: issue7855/templates/example.yaml
> output: 2
> data: 3
> ```
> 
> I tested with Helm 2 (`dev-v2` branch) and Helm 3 (`master` branch).
> 
> Can you either:
> 
> 1. Test the process I just did, and respond with the error
> 2. Provide more information about your failure
> 
> I have verified that this works with Helm 2 `helm install --dry-run` by updating the `example.yaml` to the following:
> 
> ```yaml
> apiVersion: v1
> kind: ConfigMap
> metadata:
>   name: issue7855
> data:
>   output: {{ .Values.outside.inside }}
>   data: {{ .Values.outside.value3 }}
> ```
> 
> The full output of `helm template` is:
> 
> ```
> $ helm2 install --dry-run issue7855 -f values-7855.yaml -n test  --debug
> [debug] Created tunnel using local port: '63629'
> 
> [debug] SERVER: "127.0.0.1:63629"
> 
> [debug] Original chart version: ""
> [debug] CHART PATH: /Users/technosophos/Code/Go/src/helm.sh/helm/_scratch/issue7855
> 
> NAME:   test
> REVISION: 1
> RELEASED: Mon Apr  6 18:03:31 2020
> CHART: issue7855-0.1.0
> USER-SUPPLIED VALUES:
> default:
>   inside: 2
>   value1: 1
> outside:
>   inside: 2
>   value1: 1
>   value3: 3
> 
> COMPUTED VALUES:
> affinity: {}
> autoscaling:
>   enabled: false
>   maxReplicas: 100
>   minReplicas: 1
>   targetCPUUtilizationPercentage: 80
> default:
>   inside: 2
>   value1: 1
> fullnameOverride: ""
> image:
>   pullPolicy: IfNotPresent
>   repository: nginx
> imagePullSecrets: []
> ingress:
>   annotations: {}
>   enabled: false
>   hosts:
>   - host: chart-example.local
>     paths: []
>   tls: []
> nameOverride: ""
> nodeSelector: {}
> outside:
>   inside: 2
>   value1: 1
>   value3: 3
> podSecurityContext: {}
> replicaCount: 1
> resources: {}
> securityContext: {}
> service:
>   port: 80
>   type: ClusterIP
> serviceAccount:
>   annotations: {}
>   create: true
>   name: null
> tolerations: []
> 
> HOOKS:
> MANIFEST:
> 
> ---
> # Source: issue7855/templates/example.yaml
> apiVersion: v1
> kind: ConfigMap
> metadata:
>   name: issue7855
> data:
>   output: 2
>   data: 3
> ```

i had test in my env with your example,
value.yaml:
```
default: &default
  value1: 1
  inside: 2

outside:
  <<: *default
  value3: 3
```
example.yaml:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: issue7855
data:
  output: {{ .Values.outside.inside }}
  data: {{ .Values.outside.value3 }}
```
but in the different helm version, the result is different, in helm 2.13.1(Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}), the  output is:
```
[debug] Created tunnel using local port: '34676'

[debug] SERVER: "127.0.0.1:34676"

[debug] Original chart version: ""
[debug] CHART PATH: /home/sysadmin/zhoutong/helm_test

NAME:   vehement-hedgehog
REVISION: 1
RELEASED: Wed Apr  8 01:33:36 2020
CHART: aaa-1.0.0
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
default:
  inside: 2
  value1: 1
outside:
  inside: 2
  value1: 1
  value3: 3

HOOKS:
MANIFEST:

---
# Source: aaa/templates/example.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: issue7855
data:
  output: 2
  data: 3
```
but in helm version 2.15.2(Server: &version.Version{SemVer:"v2.15.2", GitCommit:"", GitTreeState:"clean"}), command failed with below error text:
```
[root]$ helm install --dry-run --debug ./ > debug
Error: render error in "aaa/templates/example.yaml": template: aaa/templates/example.yaml:6:20: executing "aaa/templates/example.yaml" at <.Values.outside.inside>: nil pointer evaluating interface {}.inside
```

**Comment by technosophos** [comment]
I was testing against 2.16 (well, the candidate for what will either be the next 2.16 or 2.17). Would you mind testing that?

**Comment by nokia-t1zhou** [comment]
> I was testing against 2.16 (well, the candidate for what will either be the next 2.16 or 2.17). Would you mind testing that?

i will testing it in the new version when the new helm is ready in my lab env.

**Comment by technosophos** [comment]
I just looked at the previous error output, and I think there might have been another issue involved. The nil pointer doesn't look right. I see you closed, and am assuming that you've found a satisfactory working case. Let me know if this comes up again.

**Comment by nokia-t1zhou** [comment]
> I just looked at the previous error output, and I think there might have been another issue involved. The nil pointer doesn't look right. I see you closed, and am assuming that you've found a satisfactory working case. Let me know if this comes up again.

the root cause is the anchor must be defined before which used,  this usage is right:
```
default: &default
  value1: 1
  inside: 2
outside:
  <<: *default
  value3: 3
```
but this is error in helm 2.15(it can working in helm 2.13):
```
outside:
  <<: *default
  value3: 3
default: &default
  value1: 1
  inside: 2
```

**Comment by technosophos** [comment]
Oh! Thank you for the investigation!

I think it must have been the YAML parser that changed. Each time we upgrade for a new Kubernetes version, it upgrades the YAML library.
