### ISSUE TITLE
Helm chart with test for helm 2 as well as helm 3.

### ISSUE THREAD

**Issue by alf009** [helm/helm#7856]
Is there a way to create a  helm chart which (includes the tests) and it works in both helm v2 and helm v3. 

Helm 2 officially support only `helm.sh/hook: test-success` or `helm.sh/hook: test-failure`
 however
Helm 3 changed and it officially supports only hook to `helm.sh/hook: test`.
  See doc: https://v2.helm.sh/docs/developing_charts/#chart-tests

I do not see any way how to check which version of helm renders the templates to generate the helm specific hook.
 
---
Would it be possible to officially support also the helm 2 hooks?

**Comment by bacongobbler** [comment]
`helm.sh/hook: test-success` should continue to work for backwards compatibility reasons. Can you check and confirm?

**Comment by bacongobbler** [comment]
https://github.com/helm/helm/blob/193850a9e2c509acf1a499d98e8d23c12c134f11/pkg/releaseutil/manifest_sorter.go#L65-L66

**Comment by alf009** [comment]
And would it be possible to officially document that it is supported e.g., in the docs, i.e., chart authors may rely on this fact?

**Comment by bacongobbler** [comment]
Feel free

**Comment by alf009** [comment]
Ok, will try

**Comment by technosophos** [comment]
The place to contribute is here: https://github.com/helm/helm-www

**Comment by bridgetkromhout** [comment]
Hi, @alf009 - thanks for your documentation suggested. We have added it in https://github.com/helm/helm-www/pull/782 and I'm resolving this issue now. Please let us know if you have any more input!
