### ISSUE TITLE
Helm 3 is not possible to install dependent charts by executing `helm install` with `--dependent-update` on a local chart file

### ISSUE THREAD

**Issue by ryu-sato** [helm/helm#7857]
Output of `helm version`: 
```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2020-01-14T00:09:19Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): kind

----

# What happens

With helm 3.1.2, when run `helm install` with `--dependent-update` on a local chart file, it install target chart but **does not install dependent charts**.

If you run `helm install` after running `helm dependency update` it will install all the resources which include dependent charts. So, I think this is a bug of `--dependent-update` option.

# How to reproduce

1. Create chart files locally
    * ex. run `helm create sample`
    * It doesn't matter chart's apiVersion (v1 or v2 either is fine)
2. Set at least one dependency
    * When using helm v2, add dependencies into requirements.yaml
    * When using helm v3, add dependencies into Chart.yaml
3. Run `helm install` with `--dependency-update` using helm v3
    * ex. run `helm install --dependency-update sample ./sample`
    * When run `helm install`, it is needed to be in a state of unresolved dependency
    * The point is that the `requirements.lock` and `Chart.lock` does not exist

# Workaround

Update dependency before install chart.

1. Run `helm dependency update`
2. Run `helm install`

# log

Using [this](https://github.com/ryu-sato/helm-charts-sample) sample chart.

This chart is created by `helm create` and add requirement.txt manually.

[log.txt](https://github.com/helm/helm/files/4422665/log.txt)

**Comment by technosophos** [comment]
Are you suggesting that Helm 2 and Helm 3 behave differently, or that both are doing something you did not expect?

**Comment by ryu-sato** [comment]
I'm suggesting that Helm 2 and Helm 3 behave differently.

With Helm 2, running `helm install --dep-up .` installs all charts, including charts those depend on.
However, with Helm 3, running `helm install --dependency-update test .` does not install the dependent charts.

I'm expecting that Helm 3 will install all the charts, including charts those depend on, just as Helm 2 did.

**Comment by technosophos** [comment]
Thank you for the clarification. I will look into this.

**Comment by technosophos** [comment]
I'm working on reproducing this. I seem to be getting an error, but it is still not working as desired:

```console
$ helm3 install --dependency-update issue7857 _scratch/issue7857
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "brigade" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Error: directory /Users/technosophos/Code/Go/src/helm.sh/helm/_scratch/issue7857/charts/stable/chartmuseum not found
```

I'll continue working on this.

**Comment by technosophos** [comment]
Okay, spoke too soon. The above error was a typo on my part.
