### ISSUE TITLE
Proposal: Support for Specifying Chart Version in values.yaml

### ISSUE THREAD

**Issue by julianwilkinson** [helm/helm#7859]
When using CD tools like ArgoCD the Helm chart version can be specified in a deployment's configuration. _However_, when using GitOps and not trying to interact with the CD tool aside from updating the chart or the values.yaml, the version of the chart cannot be specified. This brings issues of fine grained control with multiple values.yamls between environments, like if you want to release an update of the chart itself to one environment and not to others. I acknowledge that using sub charts in some way could probably mitigate this issue but that seems like unnecessary added complexity.

My proposal is a field in values.yaml that could specify a version of a Helm chart to use (much like the same feature that the packaging tool _Kustomize_ offers with its overlays). The interaction with the already existing version flag in helm would have to be considered.

**Comment by technosophos** [comment]
This proposal is not detailed enough. You would need to specify the specific behavior with use cases, and explain how it would work.

**Comment by bridgetkromhout** [comment]
Hi, @julianwilkinson - Thank you for your ideas to improve Helm. If you'd like, you can submit a Helm Improvement Proposal so as to work in the community to make your ideas a reality: https://github.com/helm/community/blob/master/hips/hip-0001.md - meanwhile, I will close this issue. Thanks!
