### ISSUE TITLE
K8s v1.18 support?

### ISSUE THREAD

**Issue by derailed** [helm/helm#7860]
Do you have a timeline on when helm support for k8s v1.18 will be released? 
I understand quiet a bit have changed in the k8s server apis, would be good to have an idea since I have a strong dependency on helm.sh/helm/v3/pkg/action

Thank you!

Output of `helm version`:
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-26T06:16:15Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
All

**Comment by bacongobbler** [comment]
see #7831

**Comment by derailed** [comment]
@bacongobbler Thank you for the update! Thought this might be in the works already...

**Comment by technosophos** [comment]
Closing this, as #7831 was merged.
