### ISSUE TITLE
Helm is creating a space in front of my yaml file, causing apiVersion not set.

### ISSUE THREAD

**Issue by Sakkyoku-Sha** [helm/helm#7861]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.11", GitCommit:"25074a190ef2a07d8b0ed38734f2cb373edfb868", GitTreeState:"clean", BuildDate:"2019-09-18T14:34:46Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AKS

I have the following yaml file.

```
apiVersion: v1
kind: Service
metadata:
  name: tf-ui-client-app-service
spec:
  selector:
    app: tf-ui-client-app
  ports:
    - protocol: TCP
      port: 80

```

Which when trying to run helm upgrade or install I get the following error: 

```C:\Users\ryan.anderson\Desktop\helm-test>helm upgrade --install --dry-run tf-dev --set dockerImageVersion=10451 ./tf-helm
Release "tf-dev" does not exist. Installing it now.
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: apiVersion not set

```

When using helm template I see the following output. 

![image](https://user-images.githubusercontent.com/10360237/78312577-81c0a000-7511-11ea-86df-28de2312573b.png)

This random character prevents me from installing. Do you think there is a work around? 

Weirdest part is that it's not every file that does this.

![image](https://user-images.githubusercontent.com/10360237/78313064-e5979880-7512-11ea-8764-573e78080da7.png)

**Comment by bacongobbler** [comment]
Do you think it’s possible that the file might contain that special character? I cannot appear to reproduce with a `helm create foo && helm template foo`.

**Comment by Sakkyoku-Sha** [comment]
Unfortunately it is not the case. I was able to figure out a work around, so perhaps it was just an corrected file, I'm just going to close the issue. Not much worth looking into it.
