### ISSUE TITLE
`helm init --force-upgrade` does not upgrade

### ISSUE THREAD

**Issue by pmichna** [helm/helm#7865]
Output of `helm version`:
```
$ helm version
Client: &version.Version{SemVer:"v2.16.5", GitCommit:"89bd14c1541fa93a09492010030fd3699ca65a97", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T11:51:44Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.9", GitCommit:"500f5aba80d71253cc01ac6a8622b8377f4a7ef9", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:04Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Minikube

I've installed Tiller using Helm 2.13.1 with `helm init`. Then I've updated Helm to 2.16.5 and wanted to update Tiller with `--force-upgrade`:

```
$ helm init --force-upgrade
$HELM_HOME has been configured at /Users/pmichna/.helm.
Warning: Tiller is already installed in the cluster.
(Use --client-only to suppress this message, or --upgrade to upgrade Tiller to the current version.)
```

Looks like `--force-upgrade` option does not do what `helm init --help` says it does:
> Force upgrade of Tiller to the current helm version

Is it needed then?

**Comment by bacongobbler** [comment]
Have you tried `helm init --upgrade` instead? `--upgrade` is the flag that will upgrade Tiller. `--force-upgrade` overrides any warnings, such as downgrading Tiller to an older version.

https://v2.helm.sh/docs/using_helm/#upgrading-tiller

**Comment by pmichna** [comment]
Yes, I have tried `helm init --upgrade` and it indeed works.
I was confused about the `--force-upgrade` option. I was not aware it has to be used together with `--upgrade` - I haven't seen such information in the documentation. If that's the case, I guess the issue can be closed.
