### ISSUE TITLE
Reuse the Notes?

### ISSUE THREAD

**Issue by kferrone** [helm/helm#7866]
Is it possible to reuse the output of the NOTES.txt? I am using Helm to build the [k8s Application CRD](https://github.com/kubernetes-sigs/application). A lot of the info in the Application CRD can come directly from Helms `.Chart` object.  The only info I could not easily reuse is the notes to put in the Applications `descriptor.notes`.  

The only options I can think of is either make the entire notes one helper function or simply copy paste the notes contents. Is there another way? Maybe I can do something like `{{ .Notes }}`?

Output of `helm version`: v3
Output of `kubectl version`: Any
Cloud Provider/Platform (AKS, GKE, Minikube etc.): Any

**Comment by technosophos** [comment]
I'm not clear about the context in which you want to get the notes. You can get the notes from an installation using `helm get notes.` If you're thinking more at the API level, you can look how we do that in `pkg/action/get.go`.

In the chart, the notes file is a template, and thus is an output of the template engine (not an input). That is why you do not find it on the `.Chart` object. So if you wanted the same content to go to both the Notes file and some other place in the chart, you would have to put the note content in a file, and import it into both the Notes template and whatever the other location is.

If you're talking about pre-rendering the notes, you can do that with `helm template`.

**Comment by kferrone** [comment]
I just put all the notes in a tpl function to use them twice. It works fine.
