### ISSUE TITLE
Specify a Default Namespace in Chart.yaml

### ISSUE THREAD

**Issue by defreng** [helm/helm#7882]
Hi guys,

It would be great to have an option to specify a _default_ namespace for deployment within the `Chart.yaml` file. Specifying it in there would have the same effect as the `--namespace` CLI option, but can be overridden by the latter.

This feature would be especially valuable for creating 'environment' (prod, staging, test) umbrella-charts, when the complete configuration of a certain environment must be source-controlled in a Git repository.

These umbrella-charts (For example 'prod') depend on all the sub-charts of services that need to run in prod and hold their configuration values. 

Having a default namespace feature would simplify the deployment command
* from `helm upgrade -n prod-namespace deployment ./prod`
* to `helm upgrade deployment ./prod`

**Comment by bacongobbler** [comment]
While this isn't available as a feature in a chart, you can set the default namespace for your current kube context using `kubectl config set-context --current --namespace=<insert-namespace-name-here>`.

You also can change the default namespace by setting the `$HELM_NAMESPACE` environment variable.

We have avoided adding namespace-specific fields to the chart before. The assumption is that the chart should be able to be deployed to any namespace, and it is up to the user to determine where that chart will be deployed to, defaulting to the `default` namespace.

By allowing the chart author to specify a namespace in the chart, we break that assumption: the user now has to inspect the chart to determine which namespace is the default, and therefore which namespace they have to create before deploying the chart.

Does that help?

**Comment by defreng** [comment]
Thanks for the detailed response, @bacongobbler !

You're making a good point there, that the user should not be forced to look into the chart implementation to understand basic behaviour of the helm command.

I'll go ahead and therefore close this issue.
