### ISSUE TITLE
Helm list shows app deployed to `default` namespace, but was deployed to a different namespace

### ISSUE THREAD

**Issue by isaachui** [helm/helm#7884]
I deployed an app using helm:
`helm install --kubeconfig /Users/me/.kube/config django-app-dev -f dev.yaml .`
Inside all 4 of my template yaml files I have specified:
```
# django-app/templates/*.yaml
metadata:
  namespace: {{ required "specify namespace with env:" .Values.env }}
```
```
# django-app/dev.yaml

env: dev

```

Running `helm list` gives:
```
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
django-app-dev  default         1               2020-04-06 19:24:31.842245 -0700 PDT    deployed        django-app-0.1.0      1.16.0
```

Running `kubectl get pods -n dev`
```
NAME                                  READY   STATUS              RESTARTS   AGE
django-app-dev-6458fcb556-vj9d4   2/2     Running   0          21m
```

Running `kubectl get pods -n default` show nothing

Output of `helm version`:
```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Rancher v2.3.5

**Comment by hickeyma** [comment]
@isaachui Looking at your description it seems that you have:
- Set an explicit namespace `dev` on each of the k8s resources in the templates
- You then install the chart without passing a namespace, so it will use your current namespace which seems to be `default`

The behaviour then will be:
- The k8s resources will be created in the `dev` namespace in the cluster
- The Helm release metadata will be a secret crated in the `default namespace in the cluster

In general, adding namespaces to k8s resources should be avoided. The assumption is that the chart should be able to be deployed to any namespace, and it is up to the user to determine the namespace, defaulting to the current namespace.

Some more context in #5465 and #7882.

**Comment by isaachui** [comment]
@hickeyma 
Thanks for the response! The expected behavior seems a little odd, but it seems like you know exactly what's going on. I guess I expected that the Helm release metadata would have caught that there was a namespace specified in the k8s resources.

I looked briefly at the issues you posted and it seems like there's definitely still some discussion. The goal for me in specifying namespaces was so that I could set up `production.yaml`, `staging.yaml`, `dev.yaml`, etc. for each different environment that I would deploy to. Is there a better "best practices" way in doing this? I'm trying to keep production safe just in case someone runs `helm install -f staging.yaml . --namespace production` on accident.

**Comment by hickeyma** [comment]
I would say don't put the namespace in the templates or  set it is as follows: `namespace: {{ .Release.Namespace }}`

This will use the namespaces passed by Helm when deploying.

**Comment by isaachui** [comment]
So in conclusion, I should always specify `--namespace` for helm if I want helm's metadata to show up under `helm list`. If `namespace` is specified in the manifest files it will deploy to the specified `namespace` but `helm list` will show `default`

**Comment by hickeyma** [comment]
When no namespace specified, it will use your current namespace context.
