### ISSUE TITLE
Use command line arguments programmatically

### ISSUE THREAD

**Issue by finaldzn** [helm/helm#7885]
Output of `helm version`: 3.1.2

Output of `kubectl version`: 1.15.5

Cloud Provider/Platform (AKS, GKE, Minikube etc.): local

Hello,
I'm trying to convert a bash deployment script into golang. To do that I'm using the helm library.
I managed to install a chart but I know want to add arguments to my installation. (password for postgresql).

What I'm trying to is this : 
`userVals := map[string]interface{}{
		"postgresql-password": "test",
	}
	rel, err := iCli.Run(chart, userVals)`
With the chart being a postgresql chart. How can I specify the postgresql-password when installing the chart ?
**TL,DR** : how to get this line `helm` --namespace mynamespace \
      install pg stable/postgresql \
      --set postgresqlPassword=mypassword \
      `--wait` programmatically. 

I'm still relatively new to helm so I might have missed something important.
Thanks and feel free to ask for anything I might have forget that could help me fix this issue.

**Comment by hickeyma** [comment]
@finaldzn It is set in the cli [here](https://github.com/helm/helm/blob/master/cmd/helm/install.go#L154)
and passed to the library code [here](https://github.com/helm/helm/blob/master/cmd/helm/install.go#L224)

**Comment by hickeyma** [comment]
Let me know if that helps

**Comment by finaldzn** [comment]
Oh okay, so you advice me to use cmd rather than pkg to use helm programmatically ?

**Comment by hickeyma** [comment]
No, I am just showing you how the cli passes the values to the library. You can use some of this pattern to do the same.

**Comment by finaldzn** [comment]
Okay so following up, 
Instead of using the flags I went like this : 
`userVals := map[string]interface{}{
		"global": map[string]interface{}{
			"postgresql": map[string]interface{}{
				"postgresqlPassword": "test",
			},
		},
	}
	rel, err := iCli.Run(chart, userVals)`

It does the same but I bypass the flag system completly because I couldnt figure out how to use the flags without using cobra.

Hopefully it can help someone, thanks for your help anyway @hickeyma
