### ISSUE TITLE
helm status (v3) not showing the k8s endpoint etc info like helm v2 did 

### ISSUE THREAD

**Issue by phakkarainen** [helm/helm#7890]
I guess that comes from the missing tiller. Is there a workaround in v3?

**Comment by hickeyma** [comment]
@phakkarainen What do you mean by the k8s endpoint? Could you show the Helm v2 status output that you are talking about?

**Comment by phakkarainen** [comment]
Ah, it must be SUSE Cloud Foundry spesific then. :)

When you run 
helm status suse-scf
it displays:

The endpoint for use by the `cf` client is
        https://api.apps.example.com

    To target this endpoint run
        cf api --skip-ssl-validation https://api.apps.example.com

and bunch of other stuff I do not currently see
with helm 3 and kubecf.

**Comment by hickeyma** [comment]
@phakkarainen It might be worth raising the issue then with the SUSE CF environment.

Going to close this as not Helm core issue.
