### ISSUE TITLE
Helm hooks: post-rollback not working.

### ISSUE THREAD

**Issue by singh-brajesh247** [helm/helm#7893]

**Comment by liuming-tech** [comment]
cc #7677 #7714

**Comment by hickeyma** [comment]
@singh-brajesh247 Do you mind providing details about this issue in the description. The title is not enought information to help with it.

**Comment by technosophos** [comment]
I am closing this. There is not enough information for us to reproduce or test. This doesn't even specify whether the issue is Helm 2 or Helm 3.

**Comment by singh-brajesh247** [comment]
@technosophos: This issue with Helm3. While installing a new release in kubernetes. post-rollback jobs not creating. Here is a sample of my post-rollback Job

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "nginx.fullname" . }}-rollback
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "nginx.name" . }}
  annotations:
    "helm.sh/hook": post-rollback
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation

spec:
  template:
    metadata:
      name: {{ template "nginx.fullname" . }}
      labels:
        release: {{ .Release.Name }}
        app: {{ template "nginx.name" . }}
    spec:
      restartPolicy: {{ .Values.restartPolicy }}
      containers:
        - name: post-rollback-job
          image: "alpine:3.3"
          command: ["/bin/sh", "-c"]
          args: ["echo 'Rollback test'; sleep 5; exit 1"]

**Comment by technosophos** [comment]
Re-opened now that we have some more information. Can you paste teh output of `helm version` and `kubectl version`? Thanks.

**Comment by bacongobbler** [comment]
I'm also confused by this statement:

> While installing a new release in kubernetes

Which to me implies a `helm install` rather than a `helm rollback`, which is when the job is executed. Can you please provide a set of steps that we can use to reproduce the error you see? Thanks!

**Comment by bacongobbler** [comment]
Testing with the sample gave me the following error:

```
><> helm rollback foo 1
Error: warning: Hook post-rollback foo/templates/postrollback.yaml failed: Job.batch "foo-rollback" is invalid: spec.template.spec.restartPolicy: Unsupported value: "Always": supported values: "OnFailure", "Never"
```

I also noticed that the post-rollback intentionally posted above fails with a non-zero exit code. Why?

Here's what I tested:

```
$ helm create foo
$ cat << EOF > foo/templates/postrollback.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "foo.fullname" . }}-rollback
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "foo.name" . }}
  annotations:
    "helm.sh/hook": post-rollback
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation

spec:
  template:
    metadata:
      name: {{ template "foo.fullname" . }}
      labels:
        release: {{ .Release.Name }}
        app: {{ template "foo.name" . }}
    spec:
      restartPolicy: Never
      containers:
        - name: post-rollback-job
          image: "alpine:3.3"
          command: ["/bin/sh", "-c"]
          args: ["echo 'Rollback test'; sleep 5; exit 0"]
EOF
$ helm install foo ./foo
$ helm upgrade foo ./foo
$ helm rollback foo 1
Rollback was a success! Happy Helming!
```

I saw the post-rollback job execute and run to completion.

```
$ kubectl get jobs
NAME           COMPLETIONS   DURATION  AGE
foo-rollback   1/1           6s        22s
```

Is there some other issue you're experiencing?

**Comment by singh-brajesh247** [comment]
**@technosophos : Below are the kubectl and Helm version details**

root@master:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

root@master:~# helm version
version.BuildInfo{Version:"v3.1.0-rc.1", GitCommit:"0977ded29a00383db5cbfd91ae220d30457f6ddb", GitTreeState:"clean", GoVersion:"go1.13.7"}

**Comment by singh-brajesh247** [comment]
**@bacongobbler : Thanks for testing and providing the output.**

I was testing post-rollback job with `exit code 1`. Actually, this post-rollback hook can execute a script
(for example - script will check web application HTTP response code 200, if any other response code, hook can initiate auto rollback to last successful revision). 
Also, i wanted to avoid manual interaction to perform rollback  `helm rollback release-name revision`

**Comment by singh-brajesh247** [comment]
Also, couple of time i try to create pre/post-rollback hooks but did't created. Is this feature are disabled ? if Not, can you share some example ?
