### ISSUE TITLE
Error: rendered manifests contain a resource that already exists. - extend to include the resource name

### ISSUE THREAD

**Issue by namloc2001** [helm/helm#7894]
When I run: `helm install my-defectdojo DefectDojo` I get:
`Error: rendered manifests contain a resource that already exists.`

However I cannot find anything via `kubectl get all --all-namespaces` that is related.

If Helm knows there is a resource that already exists, it would be really helpful if it told me what it was so that I knew where it was to remove it. Can this information please be provided in the output message?

Output of `helm version`:
```
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2020-02-03T19:39:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): OCP on Azure

**Comment by liuming-tech** [comment]
LGTM

**Comment by hickeyma** [comment]
@namloc2001 This is strange that it doesn't show the resource conflict error msg from the k8s Go library. Do you mind checking with the latest [v3.1.2](https://github.com/helm/helm/releases/tag/v3.1.2) to see if the issue shows in it?

We can then look to see how to repeat this as its not showing for me.

**Comment by namloc2001** [comment]
Hi, tried it following upgrade to 3.1.2:

`helm install my-defectdojo DefectDojo`
```
Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: namespace: default, name: defectdojo-mysql-specific, existing_kind: /v1, Kind=Secret, new_kind: /v1, Kind=Secret
```

helm version
```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

So that's better. Thanks.
