### ISSUE TITLE
Can helm render other types of files (non-yaml)?

### ISSUE THREAD

**Issue by LvBay** [helm/helm#7899]
I want to use helm to render some shell script files ... so i create a test chart and only write a script into the templates dir, like this:

tree
.
├── Chart.yaml
├── charts
├── templates
│   └── mytest.sh
└── values.yaml

the content of templates/mytest.sh is : 
`echo {{.Values.Hello}}`

When excute command 
`helm template test ./ --debug --dry-run`

Error: YAML parse error on test/templates/mytest.sh: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type releaseutil.SimpleHead
helm.go:76: [debug] error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type releaseutil.SimpleHead
YAML parse error on test/templates/mytest.sh
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
	/private/tmp/helm-20191116-899-upx3o9/src/helm.sh/helm/pkg/releaseutil/manifest_sorter.go:129
helm.sh/helm/v3/pkg/releaseutil.SortManifests
	/private/tmp/helm-20191116-899-upx3o9/src/helm.sh/helm/pkg/releaseutil/manifest_sorter.go:98
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
	/private/tmp/helm-20191116-899-upx3o9/src/helm.sh/helm/pkg/action/install.go:455
helm.sh/helm/v3/pkg/action.(*Install).Run
	/private/tmp/helm-20191116-899-upx3o9/src/helm.sh/helm/pkg/action/install.go:214

**Comment by jdolitsky** [comment]
@LvBay - currently this is not supported. Just curious - what is your intended usage of this script? In order to run within the context of Kubernetes, it would need to be in the format of a ConfigMap which Helm can template

**Comment by pappist** [comment]
You should move out the bash script from the template/ folder. template folder must contain only manifest files ( yaml or json )!

**Comment by ilicmilan** [comment]
Thanks, @pappist, that's the answer!

**Comment by ttk** [comment]
I am interested in this feature.  I am trying to generate a ConfigMap and template it's data.  It isn't uncommon for the data is be something other than yaml, such as an ini config, or xml.  In order to have a good developer experience, it would be great to have a separate file with the proper file extension to reflect the underlying template data language of the configuration file so that the IDE can offer proper syntax highlighting.  For example:
```
apiVersion: v1
kind: ConfigMap
data:
  config.xml: |-
{{ include "_config.goxml" . | indent 4}}
```

where `_config.goxml` would be:
```
<config>
  <key>{{ .Values.myValue }}</key>
</config>
```

Currently this doesn't work because `_config.goxml` isn't yaml.

**Comment by vvotekeb** [comment]
+1
we need this feature as well

**Comment by davidmichaelkarr** [comment]
We actually do something like this, although there is a small problem with it that I wouldn't mind fixing if possible.

We render an entire directory of plain text files of any type into configmap entries with a construct like this:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.msname_wr }}-configs
  namespace: {{ .Values.kube_namespace }}
data:
{{ tpl (.Files.Glob "configs/*").AsConfig . | indent 2 }}
```

The files in the configs directory can also have "{{}}" references, but this has some limitations.  This ends up creating file entries like:
```
  system.properties: "...<entire file>"
```
Instead of rendering it with the multiline operator.  Functionally, this works fine in the rendered configmap, except that I recently discovered that if any of the "{{}}" references in the configs files use filter functions, it won't work to use any filter function that uses quotes, like "default". This fails in Helm, saying that "\\\" was unexpected. I have another issue asking about this behavior.

**Comment by chris13524** [comment]
I desire the ability for Helm to template other types of files. This would be useful to maintain the values, chart dependency features, and everything else that Helm provides. But support templating other file types, for example, docker-compose or configuration files that are used outside of Helm.

**Comment by rimusz** [comment]
> I desire the ability for Helm to template other types of files. This would be useful to maintain the values, chart dependency features, and everything else that Helm provides. But support templating other file types, for example, docker-compose or configuration files that are used outside of Kubernetes.

Helm cannot be a tool for everything, but you can expand its functionality with Helm plugins :-)

**Comment by bhass1** [comment]
If someone else is looking for a hacky workaround, `helm template` will happily template as long as it's producing a valid YAML file.

Given `chart/templates/nonyaml.conf` with the following body:
```
nonyaml.conf: |
 json {
   key = "value"
   {{- if eq .Values.aCustomHelmValue "some_string" }}
   key2 = {{  .Values.aCustomHelmValue2 | quote }}
   {{- end }}
 }
```
_Note: Make sure each line is indented by at least 1 space so it retains valid YAML [literal block scalar](https://yaml.org/spec/1.2.2/#literal-style) syntax_

Then we can generate nonyaml.conf and strip out the forced YAML with the following sed incantation (sorry):
```
helm template chart --set aCustomHelmValue=some_string --set aCustomhelmValue2=value2 \
  | sed '/---/d' | sed '/#.*/d' | sed '/nonyaml.conf: |/d' | sed "s|^ ||g"
```

Results in:
```
json {
  key = "value"
  key2 = "value2"
}
```

**Comment by ashneo76** [comment]
> You should move out the bash script from the template/ folder. template folder must contain only manifest files ( yaml or json )!

And do what instead? This isn't a valid answer. I can't find documentation aanywhere on how to do this.

**Comment by davidmichaelkarr** [comment]
Typically, you use helm to generate the k8s object descriptions, which can include the specification of environment variables which would be set in the context of a container within a k8s pod.  We typically have script code that references the environment variables set by the helm template.

If you focus on just generating yaml or json from helm, you will eventually arrive at a solution to let your scripts use that generated data.  If using environment variables isn't practical, you could pipe generated json files into "jq" to extract values from.

**Comment by zhangguanzhang** [comment]
```
rawData: |
  echo {{.Values.Hello}}
```

```
helm template test ./ | sed -rn '/^rawData:/{:a;n;p;ba}'
```

**Comment by on2e** [comment]
> Instead of rendering it with the multiline operator. Functionally, this works fine in the rendered configmap, except that I recently discovered that if any of the "{{}}" references in the configs files use filter functions, it won't work to use any filter function that uses quotes, like "default". This fails in Helm, saying that "\" was unexpected. I have another issue asking about this behavior.

One workaround for this error is to manually iterate over each file, apply `tpl` to its contents and build the key-value map of the ConfigMap:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: {{ include "mychart.namespace" . }}
data:
  {{- range $path, $_ := .Files.Glob "config/*" }}
  {{ base $path }}: |-
    {{- tpl ($.Files.Get $path) $ | nindent 4 }}
  {{- end }}
```

If you need to populate multiple ConfigMaps with external templated files you can make this a helper template in `_helpers.tpl`:

```tpl
{{- define "mychart.tplFilesAsConfig" -}}
{{- $dst := dict -}}
{{- range $path, $_ := .context.Files.Glob .glob -}}
{{- $_ := set $dst (base $path) (tpl ($.context.Files.Get $path) $.context) -}}
{{- end -}}
{{ $dst | toYaml }}
{{- end -}}
```

and include it in your ConfigMaps:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: {{ include "mychart.namespace" . }}
data: {{- include "mychart.tplFilesAsConfig" (dict "glob" "config/*" "context" .) | nindent 2 }}
```
Templating and rendering arbitrary external configuration files with `helm template` is a valid use case. Consider a Java application with multiple large .properties files that rely on the chart's values:

```ini
# application.properties
server.port={{ .Values.containerPorts.http }}
spring.datasource.url={{ include "mychart.database.url" . }}
spring.datasource.username={{ include "mychart.database.username" . }}
```

Maintaining such file contents directly in a ConfigMap template as multiline strings can be really annoying.
