### ISSUE TITLE
link URL of helm plugin list page is redirected

### ISSUE THREAD

**Issue by liuming-dev** [helm/helm#7901]
the plugin wiki page [Downloader-Plugins](https://github.com/helm/helm/wiki/Downloader-Plugins)，url: https://docs.helm.sh/using_helm/#downloader-plugins is redirected，could not find the known plugin list page.

**Comment by bacongobbler** [comment]
https://helm.sh/docs/topics/plugins/#downloader-plugins

**Comment by liuming-dev** [comment]
> https://helm.sh/docs/topics/plugins/#downloader-plugins

it seems that no plugin list info here.

**Comment by bacongobbler** [comment]
https://helm.sh/docs/community/related/#helm-plugins

**Comment by liuming-dev** [comment]
> https://helm.sh/docs/community/related/#helm-plugins

thanks
