### ISSUE TITLE
should we group command for easy read? 

### ISSUE THREAD

**Issue by zgfh** [helm/helm#7903]
if we can group command like `kubectl`,it will easy to read,like this
```
Release Commands:
  get         download extended information of a named release
  history     fetch release history
  install     install a chart
  list        list releases
  test        run tests for a release
  rollback    roll back a release to a previous revision
  status      displays the status of the named release
  template    locally render templates
  uninstall   uninstall a release
  upgrade     upgrade a release

Chart Commands:
  create      create a new chart with the given name
  dependency  manage a chart's dependencies
  pull        download a chart from a repository and (optionally) unpack it in local directory
  show        show information of a chart
  lint        examines a chart for possible issues
  package     package a chart directory into a chart archive
  repo        add, list, remove, update, and index chart repositories
  search      search for a keyword in charts
  verify      verify that a chart at the given path has been signed and is valid

Other Commands:
  completion  Generate autocompletions script for the specified shell (bash or zsh)
  env         Helm client environment information
  plugin      install, list, or uninstall Helm plugins
  version     print the client version information

Use "helm <command> --help" for more information about a given command.

```

**Comment by waveywaves** [comment]
@zgfh This is a good proposition. Currently there is a issue open with Cobra for this https://github.com/spf13/cobra/issues/836
Helm uses Cobra for it's cli, it would be nice to support this after Cobra releases support themseleves.

**Comment by zgfh** [comment]
@waveywaves  if you allow use package: k8s.io/kubectl/pkg/util/templates for now, I like to make  a PR。 Then when cobra release we can replace it

**Comment by waveywaves** [comment]
@zgfh Please do so if you can.

**Comment by zgfh** [comment]
@waveywaves  done

**Comment by bacongobbler** [comment]
re-opening as #7917 was reverted in #8153.

**Comment by bridgetkromhout** [comment]
Hi, @zgfh - thanks again for starting this work. As you may have seen, #7917 was reverted in #8153. To move forward now, the next step would be to address those concerns. 

 I'll resolve this issue now due to inactivity. If you or someone else would like to start a broader discussion about command grouping and get buy-in from the community on the approach, you could file a Helm Improvement Proposal: https://github.com/helm/community/blob/master/hips/hip-0001.md
