### ISSUE TITLE
Use Helm 3 for existing resources deployed with kubectl

### ISSUE THREAD

**Issue by meniem** [helm/helm#7907]
Output of `helm version`:
3.2
Output of `kubectl version`:
1.18
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
EKS

Hi everyone,

We used to deploy kubernetes resources using the normal kubectl command for services, deployments, configmap...etc. Now we need to start using Helm 3 and integrate it to our pipelines, but when I try to run the helm upgrade command, it's giving the below error:
`Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: namespace: default`

So, these resources were never created with helm as it was created normally with kubcetl apply command. 

Just need to know how to used Helm in the pipeline without re-create the k8s resources. As the only workaround I found to get it working was to delete the resources and re-deploy them using Helm.

Below is the command I tried:
`helm upgrade --atomic --debug --install --force test .`

Thanks,
Aly

**Comment by waveywaves** [comment]
@meniem resources created based on a Release in Helm contain information wrt the revision and the `heritage: Helm` label which allows Helm to distinguish them apart from normal Kubernetes resources. 

The solution space to me looks like the following
- allow `--force` to delete the resources to be replaced  on the users behalf and create new ones with the right labels to track the resource as a part of the revision.
- introduce a flag which does the above eg:  `--replace-original`
- introduce a flag which overrides (labels the necessary resources) eg: `--override-original` the resources to be considered as a Helm listed resource.

**Comment by liuming-dev** [comment]
Same situation to me

**Comment by towolf** [comment]
https://github.com/helm/helm/pull/7649 is supposed to solve this.

You would add some annotations and a label beforehand, and then Helm 3 will not refuse to adopt the objects from the cluster anymore.

**Comment by hickeyma** [comment]
@meniem Your use case should be solved by #7649 and will be available in the Helm 3.2 release.
If you need the capability in the meantime, you can build from master or use a canary build.

Let us know if this is sufficient. If not, we can re-open the PR.

**Comment by bacongobbler** [comment]
See also #2730.

**Comment by meniem** [comment]
> @meniem Your use case should be solved by #7649 and will be available in the Helm 3.2 release.
> If you need the capability in the meantime, you can build from master or use a canary build.
> 
> Let us know if this is sufficient. If not, we can re-open the PR.

@hickeyma yes this is fine. thanks a lot :)
