### ISSUE TITLE
Proposal: Add Linter rule for making sure subcharts have `dependencies` in Chart.yaml

### ISSUE THREAD

**Issue by technosophos** [helm/helm#7910]
This is a proposal to add a new linting rule to `helm lint`. This rule would warn the user on cases where a subchart exists in `charts/` but is not declared in `Chart.yaml`.

Background:

In Helm 2, we added `requirements.yaml` after the major release, and thus had to keep things backward compatible until Helm 3. For that reason, it was possible to add a chart to the `charts/` folder without adding it in `requirements.yaml`.

In Helm 3, we removed most of the backward compatibility code, making it _required_ to add all subcharts to the `dependencies` section of Chart.yaml.

However, this was not enforced in code, and it is still possible to put subcharts into the chart without declaring them as dependencies, and get _some_ of the desired behavior. While we should find and fix those cases, in the meantime we should add a linter rule warning that this is not expected behavior.

Proposed Rule:

The rule should check all of the charts in the `charts/` directory and make sure they are present in the `dependencies` section of Chart.yaml.

**Comment by mattfarina** [comment]
I think the docs need to be updated to clearly state how dependencies need to work, as well.
