### ISSUE TITLE
'helm list' command output inserting excess whitespace after "CHART" column

### ISSUE THREAD

**Issue by minelminel** [helm/helm#7911]
Output of `helm version`: 
```
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

Output of `kubectl version`: 
```Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T16:51:36Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): n/a, on-prem datacenter

Currently experiencing issues with the printed output of `helm list` inside the Windows Terminal on WSL1. Issue only arises with the default output formatting `-o=table`. No matter the size of the terminal window, the `APP VERSION` column is forcibly wrapped to a new row, making the table incredibly difficult to read. What's especially odd, is that no matter the width of the window, the line break occurs at the same point, that being after the first `A` of `APP VERSION`. The remaining text `PP VERSION` is forced to the next line down. Similarly, the first character of the app version number follows the same behavior, where the remaining characters are forced to the next row.

I can confirm that this behavior is present in both of the following terminals
- Windows Terminal (Preview) Version: 0.9.433.0
- Ubuntu WSL native terminal (20190521 build of Ubuntu 18.04 LTS)

![image](https://user-images.githubusercontent.com/46664545/79148844-340b2980-7d94-11ea-9ddc-d5662caf110b.png)

However, when testing in ComEmu (191012 Preview) the output displays as expected.

![image](https://user-images.githubusercontent.com/46664545/79148788-1938b500-7d94-11ea-8ab1-5c2639c41110.png)

When using the `-o=json` or `yml` flags, everything displays fine, ie. it is not an issue with hidden characters in an actual resource name.

Another interesting point: when I drag the window to enlarge the size *after* running the command, the table will be properly formatted since the width of the window now exceeds the width of the row.
![image](https://user-images.githubusercontent.com/46664545/79149001-75033e00-7d94-11ea-8efa-a1270ad61e5e.png)

I understand this is potentially a very difficult bug to fully document, so if there is any additional information I can provide regarding system settings or the likes, I can address them in the comments or update this initial post. Part of my intent in filing this issue is simply to provide anyone else who is encountering this bug a place to monitor for crowdsourced solutions, since as far as I can tell this has not been previously described anywhere.

Cheers

**Comment by bacongobbler** [comment]
hi @minelminel! Can you first try with a newer version of Helm first to see if it's been resolved in a newer version, like v3.1.2?

The table output formatting comes from another project called [uitable](https://github.com/gosuri/uitable). The code can be found here: https://github.com/helm/helm/blob/22344063d2171d24d08ff8baef32fd3218e0911e/cmd/helm/list.go#L171-L178

Let us know if you find any more information that may help resolve this issue for you.

**Comment by minelminel** [comment]
Thanks for the quick reply, I have just upgraded to v3.1.2 and am experiencing the same behavior.
Output of `helm version`: 
```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
````
Out of curiosity, when I display all invisible characters it does not appear that there is any difference between the 'normal' spacing and the misbehaving one, so I honestly don't even think there's anything to be done on your part...

![image](https://user-images.githubusercontent.com/46664545/79160586-09c36700-7da8-11ea-997c-17e2eb249134.png)

Just very odd. Feel free to close if this falls out of scope.

**Comment by minelminel** [comment]
Somewhere upstream a character encoding issue was being introduced independent of this, and I am able to resolve the issue by running `stty sane` at the end of my `.bashrc`

![image](https://user-images.githubusercontent.com/46664545/79257533-c1638200-7e57-11ea-9da1-64c67b301ef3.png)

Hopefully someone else might be able to use this because this haunted me for *weeks*....
