### ISSUE TITLE
Is there a way to fix the release status without helm delete release, when helm upgrade --install --timeout --wait timeout

### ISSUE THREAD

**Issue by zhb127** [helm/helm#7914]
`helm version`: v3.1.1

`kubectl version`: v1.14.8-aliyun.1

Cloud Provider/Platform (AKS, GKE, Minikube etc.): alicloud

![image](https://user-images.githubusercontent.com/5210208/79178217-370b2600-7e37-11ea-8daf-f4992b649872.png)

- we use: `helm upgrade --install xxx chartName --timeout 300s --wait`
- it happen timeout, but we did not execute: `helm delete xxx`, just fix timeout problem
- now, `helm release xxxx.status = failed but service is ok`
- when we execute again:   `helm upgrade --install xxx chartName --timeout 300s --wait`
- it happen: `Error: UPGRADE FAILED: "xxx" has no deployed releases`
- problem: `we can't execute helm delete xxx, because it's production env`
- how can we fix  helm release xxx status manually

**Comment by technosophos** [comment]
Currently, once `--wait` has marked it `failed`, there is no way to fix it short of directly editing the release secret (which is not recommended).

Try using `--atomic` instead of `--wait`.

**Comment by zhb127** [comment]
> Currently, once `--wait` has marked it `failed`, there is no way to fix it short of directly editing the release secret (which is not recommended).
> 
> Try using `--atomic` instead of `--wait`.

Thank you very much for your reply.

`Try using --atomic instead of --wait` still need to exec `helm delete release`, but due to the production env problem, i cannot use `helm delete` to recreate `helm release`.

I'm trying to edit the release secret on my minikube, but the release secret is not base64 encode. Do I need to use the go program to parse or Is there a tool that can be used?

**Comment by hickeyma** [comment]
Returns release object: `kubectl get secrets <secret_name> -n <namespace> -o jsonpath='{.data.release}' | base64 -d | base64 -d | gunzip`

Its base64 encoded twice and zipped.

**Comment by zhb127** [comment]
> @zhb127 Returns release object: `kubectl get secrets <secret_name> -n <namespace> -o jsonpath='{.data.release}' | base64 -d | base64 -d | gunzip`
> 
> Its base64 encoded twice and zipped.

Thank you very much.

I tested the parse successfully.

**Comment by hickeyma** [comment]
@zhb127 Does this resolve your issue?

**Comment by zhb127** [comment]
> @zhb127 Does this resolve your issue?

Not yet, I'm stll trying, change the secret, `helm list` does not recognize it any more. Maybe something is wrong.

- `kgsec sh.helm.release.v1.echo-server-br-master-20200408.v1 -o jsonpath='{.data.release}' | base64 -D | base64 -D | gunzip > echo-server-br-master.json`
- change the status => deployed
- `cat echo-server-br-master.json | gzip | base64 | base64 > echo-server-br-master.yaml`
-`kubectl apply echo-server-br-master.yaml`
- `helm list` has no the release any more

**Comment by hickeyma** [comment]
What is the output to: `kubectl get secret sh.helm.release.v1.echo-server-br-master-20200408.v1 -o yaml`?  Is the release in your current context namespace?

**Comment by zhb127** [comment]
> What is the output to: `kubectl get secret sh.helm.release.v1.echo-server-br-master-20200408.v1 -o yaml`? Is the release in your current context namespace?

It's ok now. I make a mistake before.

- `kgsec sh.helm.release.v1.echo-server-br-master-20200408.v1 -o jsonpath='{.data.release}' | base64 -D | base64 -D | gunzip > echo-server-br-master.json`
- change the status => deployed
- `cat echo-server-br-master.json | gzip -cf | base64 | base64` **this is error before**

I found,  just fix the secret API object `label.status: failed => label.status: deployed`, the next time, `helm upgrade --install` can be ok.

![image](https://user-images.githubusercontent.com/5210208/79345542-d594a580-7f63-11ea-91e3-edd3db60c64c.png)

**Comment by zhb127** [comment]
> What is the output to: `kubectl get secret sh.helm.release.v1.echo-server-br-master-20200408.v1 -o yaml`? Is the release in your current context namespace?

Thanks again for your help

**Comment by zhb127** [comment]
> Currently, once `--wait` has marked it `failed`, there is no way to fix it short of directly editing the release secret (which is not recommended).
> 
> Try using `--atomic` instead of `--wait`.

Thanks again for your help
