### ISSUE TITLE
$ does not point to the root in named templates

### ISSUE THREAD

**Issue by jorgecarleitao** [helm/helm#7915]
Consider the following template

```
# templates/bla.yaml
{{- define "baseLabels" -}}
app.kubernetes.io/instance: {{ $.Release.Name }}
app.kubernetes.io/part-of: {{ .name }}
{{- end -}}

{{- with .Values }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
    {{- include "baseLabels" . | nindent 4 }}
{{- end }}
```

that is templated with `helm template release . --set name=foo`.

I would expect `$.Release.Name` to be interpolated to `release`, and `.name` to be interpolated to `foo`. However, this yields the error:

```
Error: template: templates/bla.yaml:11:8: executing "templates/bla.yaml" at <include "baseLabels" .>: 
error calling include: template: templates/bla.yaml:2:32: executing "baseLabels" at <$.Release.Name>: nil pointer evaluating interface {}.Name
```

Specifically, even though, in the macro, I am using `$.Release.Name` to point to the root, this root is not the root that I was expecting it to be (the root of the project), but is instead the root of the named template (we can check this by removing the offending line and using `$.name`)

There are two questions here:

1. Isn't this against the statement we make [in the docs](https://helm.sh/docs/chart_template_guide/variables/)

    ```However, there is one variable that is always global - $ - this variable will always point to the root context. [...]```

2. How do we define a named template that receives some scope (e.g. `.name` above) but also uses the root scope (`$.Release.Name`)?

Note that if we use `{{- include "baseLabels" $ | nindent 4 }}`, we lose the `.name` assigned by the `with` statement.

Output of `helm version`: `version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}`

**Comment by jorgecarleitao** [comment]
I believe that this may be related to the fact that we implement `include` as `ExecuteTemplate`, in [line 122](https://github.com/helm/helm/blob/3129b5323c3794e402d4a5621de88f17979311b9/pkg/engine/engine.go#L122), which uses whatever data was passed in the include. As such, the root will be `data`, and not the actual root (as in other parts of the templating in go).

**Comment by bacongobbler** [comment]
If you change your invocation to `include "baseLabels" $.`, what happens?

Because you invoked this call from within a `with` function call, the value of the dot variable changed to use `.Values` as the root.

**Comment by jorgecarleitao** [comment]
> If you change your invocation to `include "baseLabels" $.`, what happens?
> 
> Because you invoked this call from within a `with` function call, the value of the dot variable changed to use `.Values` as the root.

That leads to an `Error: parse error at (templates/bla.yaml:12): unexpected <.> in operand` (line 12 is the line with `{{- include "baseLabels" $. | nindent 4 }}`)

**Comment by bacongobbler** [comment]
Ah sorry, typo on my end. Try passing just `$`?

**Comment by jorgecarleitao** [comment]
That compiles, but the `.name` is not interpolated.

One (hackish) solution for this is to add `{{- $_ := set $ "name" .name }}` to after the `with` statement, but this defeats the purpose of a `with` statement.

**Comment by bacongobbler** [comment]
In your `define`, change `.name` to `.Values.name`. By passing `$` you are passing along the root context, which means you'll have to traverse the tree once more to see that value.

**Comment by Sytten** [comment]
@bacongobbler IMO this is not a good answer.
In the simple case presented this might work, but in the case of a range where you want both complex data from the root values and the current element this won't work.
You can obviously pass a merged dict, but this is really not intuitive and it should at the very least be mentioned as an exception in the documentation.

**Comment by vincentbesanceney** [comment]
@bacongobbler can you reopen this issue?
As mentioned by @jorgecarleitao, if we define a named template that receives some scope, then $ no longer points to the root context. The documentation says just the opposite. So, this is either a bug or a wrong statement in the documentation. Thanks for your support.

**Comment by tculp** [comment]
@bacongobbler I agree that this seems counter to every other usage of $ to refer to the root context, and is very counter-intuitive. I just spent the last half hour trying to find out why I was getting `<$.Files.Get>: nil pointer evaluating interface {}.Get`.

**Comment by ckyoog** [comment]
@tculp Yes, me too! I wasted my time on this counter-intuitive design.

From the [documentation](https://helm.sh/docs/chart_template_guide/variables/),
> However, there is one variable that is always global - $ - this variable will always point to the root context. This can be very useful when you are looping in a range and you need to know the chart's release name.

We've been educated that we can use `$` to retrieve such as `$.Values`, `$.Release`, `$.Chart`, etc.

So here is what usually happens in a `with` statement.
```
{{- with .Values }}
...
{{ $.Release.Name }}      # NO PROBLEM!
{{- end }}
```

But just put it in a `define` (named template), the `$` loses its effect for no reason.
```
{{- define "namedTemplate" -}}
... {{ $.Release.Name }}     # NO WORKING!
{{- end -}}

{{- with .Values }}
...
{{- include "namedTemplate" . }}
{{- end }}
```


@bacongobbler  what you suggested IS a solution. But as @Sytten said, it is not a good answer. Please reopen this issue!

**Comment by bacongobbler** [comment]
When execution begins, $ is set to the data argument passed to the function. That is, to the starting value of dot.

The scope of $ changes when execution switches context to another function (`define`). This is explained more in https://pkg.go.dev/text/template.

**Comment by bacongobbler** [comment]
Please feel free to contribute to the documentation repo. I’m not actively working on helm any more.

https://github.com/helm/helm-www

**Comment by ckyoog** [comment]
@bacongobbler you are not actively working on helm any more, and you just actively closed [another helm issue](https://github.com/helm/helm/issues/10876). I wouldn't know it if I were not the OP.

**Comment by bacongobbler** [comment]
This is getting off-topic, but triaging tickets is not the same as actively contributing code. I’m winding down from active maintainership. I continue to contribute to the project by volunteering a few hours per month triaging tickets in my spare time.

Bringing the subject back on-topic… If you have time to test and document this behaviour, we’d appreciate the help.

https://github.com/helm/helm-www

**Comment by rehevkor5** [comment]
In case it wasn't noticeable, my PR https://github.com/helm/helm-www/pull/1353 above attempts to improve various associated wording in the documentation. Hoping to get some feedback or approval!

**Comment by nuno-caro-feedzai** [comment]
Can we get a bump on the priority of updating the documentation? It is clearly misleading and people waste time on a silly thing.

**Comment by rehevkor5** [comment]
@nuno-caro-feedzai Feel free to upvote https://github.com/helm/helm-www/pull/1353 if you think that helps.
