### ISSUE TITLE
Override path for helm data

### ISSUE THREAD

**Issue by Xartos** [helm/helm#7919]
The only way to specify the path to where data (same for cache and config) are suppose to live is either using the default path (that uses the $HOME variable) or by setting the XDG_DATA_HOME.
This is a problem if you not want to use the default path and can't use the XDG_DATA_HOME override (e.g. because of some dependency that uses the same variable)

Suggestion:
Add a second way of overriding the default path. A new variable (something like `HELM_DATA_HOME`) that overrides both the default path AND the XDG_DATA_HOME variable.

This would be useful in github workflow which overwrites the HOME variable and attaches a volume to that path when executing a container such that plugins installed in the home folder at build time will be lost.

**Comment by hickeyma** [comment]
> This is a problem if you not want to use the default path and can't use the XDG_DATA_HOME override (e.g. because of some dependency that uses the same variable)

What would be the scenario where one would be unable to use this variable? It is a defined variable of the XDG Base Directory Specification which Helm uses.

**Comment by Xartos** [comment]
Let's say that you want to have the location of the helm data to be on a completely separate path (to a mounted volume or something) but you have applications that use the XDG_DATA_HOME that is pointing somewhere else.

**Comment by hickeyma** [comment]
Ok, so you would like to add a variable when set, overrides the the XDG Base Directory Specification and uses this as the base directory for Helm cache, config and data?

**Comment by Xartos** [comment]
Exactly, either that or one variable for each

**Comment by waveywaves** [comment]
I am currently working on https://github.com/helm/helm/pull/7755 . Does this solve your issue ?

**Comment by Xartos** [comment]
@waveywaves Yes, that looks like it could be a solution actually.
