### ISSUE TITLE
helm template rendering wrong output

### ISSUE THREAD

**Issue by vivisidea** [helm/helm#7920]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:41:57Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  bare metal

How to reproduce

1. helm create test
2.  open test/templates/ingress.yaml add a comment in front of the file
```
# comment
{{- if .Values.ingress.enabled -}}
```
3. helm template --set ingress.enabled=true test | less
4. search for the Ingress section
```
# Source: test/templates/ingress.yaml
# commentapiVersion: networking.k8s.io/v1beta1 <-- THIS LINE SHOULD NOT BE HERE
kind: Ingress
```

**Comment by vivisidea** [comment]
I test helm-v3.1.2 this bug still exist

**Comment by technosophos** [comment]
The `{{- ` is removing the newline between your `if` statement and the `# comment`. Switch it to `{{ ` (no `-`) and you will be fine.

**Comment by bacongobbler** [comment]
closing as documented in https://golang.org/pkg/text/template/#hdr-Text_and_spaces
