### ISSUE TITLE
Helm 3 upgrade overwrite the patched value for endpoint resource.

### ISSUE THREAD

**Issue by Telzeng** [helm/helm#7935]
Output of `helm version`:
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:57:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-16T08:00:38Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

**Issue description:**

- Helm install use the following yaml. And the subsets is set null list.

#####################################
apiVersion: v1
kind: Endpoints
metadata:
  name: database-pg
  labels:
    app.kubernetes.io/version: "xxx"
    app.kubernetes.io/instance: "ft3"
  annotations:
    product-name: " Database PG"
subsets: []
#####################################

- After install, do the patch as following.

#####################################
apiVersion: v1
kind: Endpoints
metadata:
  name: database-pg
  labels:
    app.kubernetes.io/version: "xxx"
    app.kubernetes.io/instance: "ft3"
  annotations:
    product-name: " Database PG"
subsets:  
\- addresses:
  \- ip: 192.168.200.208
  ports:
  \- name: metrics
    port: 9187
    protocol: TCP
  \- name: postgresql
    port: 5432
protocol: TCP

#####################################

- Take the helm upgrade with following chart. 

#####################################
apiVersion: v1
kind: Endpoints
metadata:
  name: database-pg
  labels:
    app.kubernetes.io/version: "xxx"
    app.kubernetes.io/instance: "ft3"
  annotations:
    product-name: " Database PG"
subsets: []
#####################################

After upgrade, the subsets of endpoint overwrite to patched value with null list as above yaml. Could you confirm if this behavior is right. According to helm3 new feature about 3-way Strategic Merge Patches, it should keep the patched value after upgrade.

**Comment by bacongobbler** [comment]
The behaviour described above is correct.
