### ISSUE TITLE
Helm 3 ignores the output format for empty repos list

### ISSUE THREAD

**Issue by joncnet** [helm/helm#7939]
Dear team,

The command `helm repo list` returns an error when there are no repositories.
Due to this behaviour, the `-o json` flag is ignored and the same error is returned instead of an empty list `[]`

The expected behaviour would be the same of `helm list` when no installed charts are present

Output of `helm version` (I have tried with both):
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
version.BuildInfo{Version:"v3.2.0-rc.1", GitCommit:"7bffac813db894e06d17bac91d14ea819b5c2310", GitTreeState:"clean", GoVersion:"go1.13.10"}

Thanks

**Comment by mattfarina** [comment]
I'm going to label this as a bug. It's a behavior change from Helm v2 and I believe it's unintentional. I'm going to poke some of the other maintainers to see if they concur.

**Comment by technosophos** [comment]
Agreed. If the output is _supposed_ to be JSON and is not, it is a bug. Consequently, there is no compatibility maintenance issue here.
