### ISSUE TITLE
get-helm-3 script download by default the release-candidate

### ISSUE THREAD

**Issue by ahurtaud** [helm/helm#7941]
Hello,

The get-helm-3 script download the latest v3. tags even if they are in release candidate state.
I would expect it to download only the stable releases.

curl -s https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

Downloading https://get.helm.sh/helm-v3.2.0-rc.1-linux-amd64.tar.gz

What do you guys think?
Alban

**Comment by mattfarina** [comment]
@ahurtaud thanks for catching this.

It appears this was introduced by 0087d838073abcc93fb9ea694256e0b93238ae23. This is the first time we've had a release candidate since then.
