### ISSUE TITLE
Install script should have a way to verify release signatures

### ISSUE THREAD

**Issue by jdolitsky** [helm/helm#7943]
Related to conversation in https://github.com/helm/helm/issues/7838

**Comment by bacongobbler** [comment]
How do you verify a pgp signature you haven’t trusted yet?

This might make sense as a feature flag, as the user would first need to add all of the core maintainer’s public keys to their keyring. I can’t see this being the default without breaking every user that hasn’t added the core maintainers’ public keys to their chain of trust (basically everyone).

**Comment by Jean-Baptiste-Lasselle** [comment]
hi @bacongobbler , interested n the content of the pukk request, I faéll on your question.

> How do you verify a pgp signature from a source you haven’t trusted yet?

What does "to trust a key " means ? 

The answer in 12345 : what does it mean to trust a key at level 3, and what does it means to trust it at level 5?

Answer : Nothing, it is non-sense. 
* You do not trust a key, you import it into your keyring.
* level of trust from 1 to 5 ois : Hey Linux, you can trust ar level 3 all binaries signed with that key" .
* oh wow great now linux can refine permissions related to : 
  *  how deep into the system the installation process goes
  * what the binary can, or cannot do (resources used)

I like t guess based on behavior, black box testing, and then I guess : wy oh, wy, has he coded it like that ?

So I am absolutely asking anyone to correct , contradict me, I have read very litlle on the subject, I just understand math a little,  and like proving, crypto, and above all, guessing.

So I might be saying complete rubbish. But I will learn, for sure, I know whee I stand.
