### ISSUE TITLE
Proposal: Graceful Handling of Permission Denied

### ISSUE THREAD

**Issue by jmlogan** [helm/helm#7946]
We are running on a multi-tenant cluster, with users restricted generally by namespaces, with some users having a large set of namespaces.

We would like the ability for users to run a `helm list --all-namespaces` to see what is running on their namespaces, but Helm fails, due to having insufficient permission on other namespaces. We have given users a blanket GET on most resources, such as namespaces, but Helm is attempting to read secret data out of other namespaces, which I feel like is an untenable permission solution on a multitenant cluster.

I think it would be much better if the `helm list --all-namespaces` command were to return the listing of Helm charts in the namespaces the user has permission to, and perhaps flag a warning on other namespaces.

**Comment by bacongobbler** [comment]
Similar to kubectl's `--all-namespaces` flag, `helm list --all-namespaces` is a cluster-level request, and as such it [requires cluster-level scope](https://helm.sh/docs/topics/rbac/#example-grant-a-user-read-only-access-at-the-cluster-scope) to view those resources. Because of that, the user can either be granted cluster scope access to view releases at the cluster scope, or view releases at the namespace scope.

Hope this helps answer your question with regards to the scope of `--all-namespaces`.

**Comment by jmlogan** [comment]
I understand the implementation, but am just expressing concern that the permissions required for that are simply unworkable in a shared-tenant cluster. I don't believe the permissions are necessary to provide reasonable functionality if they are not available (ie. don't error, but just show what you can, with a warning that not all namespaces were readable).

Secrets are designed to hold sensitive data, and giving all users on our cluster blanket access to Secrets just for this seems like an untenable position from a security perspective.

**Comment by bacongobbler** [comment]
Fair enough.

If you're interested in investigating this idea further, I'd suggest [writing a plugin](https://helm.sh/docs/topics/plugins/) to try and see if this idea is feasible. We'd be interested to see what you come up with.

Let us know if you run into any issues.

**Comment by bridgetkromhout** [comment]
Hi, @jmlogan - as suggested above, a plugin is likely the right path forward. Another option if you believe a change to helm is correct is to submit a Helm Improvement Proposal so as to work in the community to make your ideas a reality: https://github.com/helm/community/blob/master/hips/hip-0001.md - meanwhile, I will close this issue. Thanks!
