### ISSUE TITLE
Helm 3. Chart.ApiVersion unavailable in templates

### ISSUE THREAD

**Issue by ViktorFefilov** [helm/helm#7951]
Dear Team,
I tried to use `.Chart.ApiVersion` and got error.

Output of `helm version`: version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}

How to reproduce: 
1. `helm create mychart`
1.  Add `{{.Chart.ApiVersion}}` in some place. For example `name: {{ include "mychart.fullname" . }}-{{.Chart.ApiVersion}}` in metadata in deployment.yaml file
1. Run `helm template ./mychart/`
1. Result: `Error: template: mychart/templates/deployment.yaml:4:51: executing "mychart/templates/deployment.yaml" at <.Chart.ApiVersion>: can't evaluate field ApiVersion in type interface {}`

Addition info: 
* All's ok with `{{.Chart.AppVersion}}`
* All's ok with helm version 2

Thanks

**Comment by hickeyma** [comment]
@ViktorFefilov The field is defined internally as `APIVersion`. So you would access it as follows: `{{ .Chart.APIVersion }}`

**Comment by ViktorFefilov** [comment]
@hickeyma thank you now it's working! But I have to notice this change from v2 is bit unexpected

**Comment by hickeyma** [comment]
Not sure the reason why.

@adamreese Could you shed some light on why this changed from v2? It seems to have been this way since the v3 branch started.

**Comment by bacongobbler** [comment]
The convention for CamelCasing is to capitalize an acronym. We do this everywhere else in the code, such as with `.Capabilities.APIVersions.Has`. `.Chart.APIVersion` was the odd one out here and was corrected for Helm 3. I think it just got lost in the mix while we were documenting what changed.
