### ISSUE TITLE
Proposal: improve exposed APIs to better support using Helm as a package

### ISSUE THREAD

**Issue by hiddeco** [helm/helm#7958]
First of all, thanks for caring about third parties utilizing Helm as a package and not the full fledged `helm` binary by merging #7401. 

I have two additional proposals, both aimed at making it easier to consume Helm packages for third party dependents:

- [x] Extend the `getter` package with a timeout option to allow finer grain control over the request when utilizing it (outside an e.g. `downloader` context) to download charts from Helm repositories.

- [ ] Introduce the proper usage of a `context.Context` in the `action` package (and downward calls). This again, would allow third parties to utilize Helm functionalities without using the `helm` binary, but while making it possible to pass along an e.g. `context.WithTimeout` to stay in control over the long running action.

I am open to alternative proposals and/or questions.

**Comment by bacongobbler** [comment]
Hi @hiddeco. Thank you for sharing.

The timeout feature seems fairly straightforward. On the other hand, I'm curious how that will translate to a new Helm feature. As far as I understand #7950 only introduces it to the package, but it's not integrated with the rest of the CLI. Why is that?

In regards to your second proposal, that might be a harder pill to swallow. Kubernetes 1.18 just introduced contexts to their client, effectively breaking userspace during the upgrade process. We may have to hold off until Helm 4 unless there's a way we can do it in a backwards-compatible fashion.

In the future, can you please open one ticket for each work item? That way we can track those discussions separately. Thanks.

**Comment by hiddeco** [comment]
> On the other hand, I'm curious how that will translate to a new Helm feature. As far as I understand #7950 only introduces it to the package, but it's not integrated with the rest of the CLI. Why is that?

I ran across the lack of control on the timeout while utilizing the `getter` package to fetch and store Helm charts as an artifact for later usage, and not while using `helm` itself. This is something I would expect more projects to do given Helm is a packaging solution, and it seemed thus more useful to me to try to patch it upstream than to copy and modify the `HTTPGetter` (times `n` as I would need this modified getter in multiple projects).

I would be happy to hook it up to some CLI flag if that would help justify the change and be useful to `helm` binary users, but I do not think adding a knob for the sake of knobs is something to strive for.

> In regards to your second proposal, that might be a harder pill to swallow. Kubernetes 1.18 just introduced contexts to their client, effectively breaking backwards compatibility for everyone (including Helm) during the upgrade process.

I was not expecting this to happen soon given these exact reasons but nonetheless wanted to make the proposal for a future version. One way I can imagine making it backwards compatible would be to introduce new context allowing methods and backport the old ones using `context.TODO()`, but I am saying this without knowing the ins-and-outs of the Helm core.

> In the future, can you please open one ticket for each work item? That way we can track those discussions separately. Thanks.

:heavy_check_mark:, also happy to move one of the list items to a separate issue.

**Comment by technosophos** [comment]
I would prefer to merge the PR as-is and then evaluate adding it to the Helm client. I have been working with Helm users on various issues with timeouts in `--wait`, and I am _really_ nervous about adding more timeouts right now. I think we'll get there... but I want to play it safe for a bit longer. In the meantime, adding this to API usage would mean that experienced developers will be able to use it (and consequently test it) before we use it more broadly.

That's my 0.2, but I could definitely be talked out of this if you think it is important to add to the CLI right away, @bacongobbler

**Comment by bkeroackdsc** [comment]
Lack of context support in the `action` package is a deal-breaker for upgrading to v3 from the old v2 `helm` package.

**Comment by bacongobbler** [comment]
We'd be happy to look at proposals which introduce `context` to the action package in a backwards-compatible fashion, @bkeroackdsc. Feel like taking that one on?

**Comment by bacongobbler** [comment]
> That's my 0.2, but I could definitely be talked out of this if you think it is important to add to the CLI right away, @bacongobbler

Nope! I was just curious if this feature was also requested at the CLI level too. It seems like an easy feature to support in the SDK.

**Comment by bkeroackdsc** [comment]
>  Feel like taking that one on?
@bacongobbler I'll see what I can do in the next week or so.

**Comment by bridgetkromhout** [comment]
Hi, @hiddeco - thank you for your detailed proposals! If you'd like to submit the remaining item as a formal proposal, we now have a documented process: https://github.com/helm/community/blob/master/hips/hip-0001.md - meanwhile, I will close this issue. Thanks!

**Comment by bkeroackdsc** [comment]
Hi! After circling back to this and digging into the code a bit, this is more complex than it was with Helm v2, due to the internal use (in `pkg/kube`) of the kubernetes `cli-runtime` package. Specifically, [Helper](https://pkg.go.dev/k8s.io/cli-runtime/pkg/resource@v0.20.1#NewHelper). Even though the internal k8s client version supports contexts, the cli-runtime Helper data structure methods do not. After a superficial search I found no issues or proposals in the upstream k8s project to add context support to this package.

Thus we are left with a few options to allow cancellation in Helm `pkg/actions` via contexts:

1. Vendor the `cli-runtime` package, add context support the Helper methods. Add a note to explore upstream changes in the future so we can remove the vendor copy.
2. Refactor 'pkg/kube' to not use cli-runtime.Helper. This looks like this would be a large change.
3. Implement wrapper functions in `pkg/kube` around any k8s primitive calls, allowing early return if the context is cancelled. There's a small chance this could result in leaked goroutines or swallowed errors from k8s, but may be acceptable to minimize code changes.

@bacongobbler any guidance or feedback? My preferences (in order) would be 3, 1, 2.

**Comment by hiddeco** [comment]
$0.02

From a maintainer perspective, I would avoid vendoring `cli-runtime` at all cost. Forking it and using a replace in `go.mod` would be better, but still not optimal.
