### ISSUE TITLE
Wrong image variables in default deployment.yaml

### ISSUE THREAD

**Issue by crisfrusu** [helm/helm#7964]
This is for Helm 3, while creating the default chart template.  In the "templates/deployment.yaml" I have this:

template:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"

It should be this:

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

When I try to deploy an app from the Helm catalog, it fails because the image does not exist in the repo.

**Comment by mattfarina** [comment]
Using the appVersion landed in d3f0ac934349d19af364297dfdf62608d1e9b8d7. In the just released 3.2.0 the behavior changed a little. Now it does..

```
image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
```

If the image tag is set that will be used. Otherwise, it uses the app version. I believe this would fix the issue.

**Comment by crisfrusu** [comment]
Thank you for your reply.  I believe it solves the issue.  I will close the ticket after I test the new release.

**Comment by bacongobbler** [comment]
Thank you for the response. Let's go ahead close this one out. If the solution in Helm 3.2.0 does not work for you, we can re-open the ticket and investigate further. Thanks.

**Comment by crisfrusu** [comment]
Sounds good, thanks.
