### ISSUE TITLE
How do I pass multiple image pull secrets to a chart?

### ISSUE THREAD

**Issue by tamalsaha** [helm/helm#7965]
I created a chart using `helm create demo-chart`. Now, I want to pass multiple image pull secret to that using `--set` flag. How do I do that? I tried 

```
helm template . --set imagePullSecrets={"name":"s1"} --set imagePullSecrets={"name":"s2"}
```

That does not work. Here is my repo: https://github.com/tamalsaha/demo-chart

Output of `helm version`:
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by bacongobbler** [comment]
[As per the documentation](https://helm.sh/docs/intro/using_helm/#the-format-and-limitations-of---set), you can use `--set imagePullSecrets[0].name=s1,imagePullSecrets[1].name=s2`.

Closing as answered. if there is a topic missing in the documentation, please feel free to contribute to the helm-www repo. Thanks.

**Comment by tamalsaha** [comment]
Thanks a lot!
