### ISSUE TITLE
kubeconfig mapping

### ISSUE THREAD

**Issue by Roninchen** [helm/helm#7966]
In My values.yaml:
--------------------------------
kubecoonfig: |-
  apiVersion: v1
  clusters:
  - cluster:
      certificate-authority-data: *****
      server: https://***:6443
    name: ***
  contexts:
  - context:
      cluster: ***
      user: ***
    name: ***
  current-context: ***
  kind: Config
  users:
  - name: ***
    user: ***
      token: ***
-------------------------
In my template/configmap.yaml:
-----------------------------
  config: |-
  {{ .Values.kubeconfig }}
-----------------------------

when I helm install --dry-run --debug --generate-name  .

it return  errors:
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(ConfigMap): unknown field "clusters" in io.k8s.api.core.v1.ConfigMap, ValidationError(ConfigMap): unknown field "contexts" in io.k8s.api.core.v1.ConfigMap, ValidationError(ConfigMap): unknown field "current-context" in io.k8s.api.core.v1.ConfigMap, ValidationError(ConfigMap): unknown field "users" in io.k8s.api.core.v1.ConfigMap]
helm.go:75: [debug] error validating "": error validating data: [ValidationError(ConfigMap): unknown field "clusters" in io.k8s.api.core.v1.ConfigMap, ValidationError(ConfigMap): unknown field "contexts" in io.k8s.api.core.v1.ConfigMap, ValidationError(ConfigMap): unknown field "current-context" in io.k8s.api.core.v1.ConfigMap, ValidationError(ConfigMap): unknown field "users" in io.k8s.api.core.v1.ConfigMap]
helm.sh/helm/v3/pkg/kube.scrubValidationErro

what should I do?

Output of `helm version`:

version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by bacongobbler** [comment]
Have you tried using `quote` or `nindent`?

**Comment by Roninchen** [comment]
> Have you tried using `quote` or `nindent`?

kubectl or go client not allow “” in kubeconfig file

**Comment by Roninchen** [comment]
> Have you tried using `quote` or `nindent`?

nindent  works, thank you
