### ISSUE TITLE
deletion of requirements.yaml alters template rendering behaviour

### ISSUE THREAD

**Issue by gerrnot** [helm/helm#7968]
Output of `helm version`:

Client: &version.Version{SemVer:"v2.16.5", GitCommit:"89bd14c1541fa93a09492010030fd3699ca65a97", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.5", GitCommit:"89bd14c1541fa93a09492010030fd3699ca65a97", GitTreeState:"clean"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

minikube version: v1.6.2
commit: 54f28ac5d3a815d1196cd5d57d707439ee4bb392

### Defect Description

I am getting a different installation templating output of the subcharts when I delete the requirements.yaml of the parent chart vs not deleting it, even though the subcharts are downloaded to the charts directory already. Imo the output should be the same.

### Steps to reproduce

[umbrella-chart.zip](https://github.com/helm/helm/files/4516785/umbrella-chart.zip)
Download attached zip file and run the following commands:

`
unzip umbrella-chart.zip

helm install -n chart --dry-run --debug umbrella-chart | grep "config.without.subconfig" # does not produce any output!

rm umbrella-chart/requirements.yaml

helm install -n chart --dry-run --debug umbrella-chart | grep "config.without.subconfig" # now, for the same command as above, we get two lines of output:
    config.without.subconfig.first: null
    config.without.subconfig.second: null
`

Hint: The template code that produces the output that is being grepped for resides in file 'umbrella-chart/charts/sub-chart/templates/NOTES.txt'

**Comment by bacongobbler** [comment]
I'm sorry, but I cannot make sense of the issue described here. What is the expectation? How does this affect you? Can you please provide a clearer explanation of the issue at hand, and perhaps use a more succinct example?

Thanks.

**Comment by bacongobbler** [comment]
I was able to reproduce the same behaviour with Helm 3 as well, for what it's worth.

**Comment by gerrnot** [comment]
Thanks for reproducing the issue with also with helm 3!

In our ci systems we have the following behaviour:

On jenkins we are both building and deploying (to a dev stage) the umbrella helm chart. As we have the umbrella chart available locally for build we are also deploying the chart from local - yes it has dependencies which we fetch before with dependency update from artifactory. Building means we are replacing certain strings and are editing the requirements.yaml file according to our needs. After the build we deploy the chart to artifactory.

On rundeck we are using the deployed chart from artifactory to deploy to higher stages (test, preprod etc).

The problem that we are facing is simply the inconsistent behaviour: The jenkins job vs the rundeck job produce different output which alters the business behaviour of our app. It should not matter if the requirements.yaml is there to produce a different output. As long as the subcharts are in the charts directory and no helm dependency commands are executed, the requirements.yaml should be ignored.

Deleting the requirements yaml file was the easiest way to reproduce/pin down the issue to get the exact same behaviour in inconsistent template rendering. It is my hope that due to a fix of this inconsistency this also fixes our inconsistent behaviour - because we actually do not delete our requirements.yaml - we only modify it.

So consistency is my #1 concern.

I consider the behaviour described in comment: "# now, for the same command as above, we get two lines of output:" the correct behaviour.
My arguments for this:
- according to helm lint and some online yaml linting tools it is valid to have a key with a null value as in our values.yaml:
```
configs:
  ...
  config.without.subconfig.first:
  config.without.subconfig.second:
```
- the range function that we use to iterate over key and value of the items in config is the revealing culprit (the root cause might be earlier: in the code that translates the values.yaml and passes it to the range function), as it sometimes interprets the non-existing values for a given key as null (and thereby as result: a valid key: null pair) and sometimes it says oh I have a key without a value, not doing anything!

So my #2 concern is that the range function should be ok with the null values and produce the output if there is no value assigned to a key. (And that in the presence or absence of the requirements.yaml file)

**Comment by bridgetkromhout** [comment]
Hi, @gerrnot! Thank you for your ideas to improve Helm. If you'd like, you can submit a Helm Improvement Proposal so as to work in the community to make your ideas a reality: https://github.com/helm/community/blob/master/hips/hip-0001.md - meanwhile, I will close this issue. Thanks!
