### ISSUE TITLE
Feature request: ignore part of a resource in upgrade

### ISSUE THREAD

**Issue by max-rocket-internet** [helm/helm#7971]
In Helm2, it was possible to use it together with a separate CD system because it would only apply the diff since the last Helm release. But with Helm3, due to the 3-way merge process, this is not possible. For example, if you use a tool like Spinnaker or any other CD tool that is effectively running `kubectl set image xxxxx container=nginx:latest`, now Helm3 will undo this change on the next chart upgrade.

Is there any way around this?

Would a reasonable feature request be to allow the user to ignore a specific attribute from a resource during an upgrade? For example:

```
helm diff upgrade ingress01 stable/nginx-ingress --reuse-values --ignore deployment.ingress01.spec.template.spec.containers[0].image
```

The only other option is to include Helm in the CD process. While this sounds trivial and a lot of people do it, in many cases this is too cumbersome. For example we have many values files, complicated charts, helm-secrets encrypted with AWS KMS etc. To include these toolsets and dependencies in our CD would be a huge pain where right now we essentially just call the k8s API to change the image.

Or any other ideas would be appreciated 🙂

**Comment by bacongobbler** [comment]
Have you tried setting the value to `null`, or by matching the current value present in your live state?

https://helm.sh/docs/faq/#improved-upgrade-strategy-3-way-strategic-merge-patches

**Comment by max-rocket-internet** [comment]
> Have you tried setting the value to null,

I have not. So I would install the chart with a dummy value, set it to `spec.template.spec.containers[0].image=null`, upgrade the chart, then this key can be managed outside of Helm? I'll try it 🙂

> or by matching the current value present in your live state?

So we would get the current image, and then add this as a value like: `helm upgrade ingress01 stable/nginx-ingress --values path/to/my/values.yaml --set controller.image.tag=0.29.0`?

Could do this but would be prone to error if it's left to a user. We would have to automate something here I think.

**Comment by max-rocket-internet** [comment]
@bacongobbler thanks for the reply. Regarding that link "Improved Upgrade Strategy: 3-way Strategic Merge Patches", it says there in the example about sidecar containers:

> but live state contains a sidecar container

How does Helm decide to let that sidecar remain after the 3 way merge? Is there specific logic for sidecar containers? Or it just allows extra items to remain when they are in an array, like `containers`?

**Comment by bacongobbler** [comment]
the latter. As the documentation suggested, live state was not considered in Helm 2, so helm had no idea there was a sidecar container. When the PATCH request comes in, it effectively removed the sidecar. In Helm 3, we have knowledge of that sidecar and can allow that extra item to remain in the array, as the update (the chart from `helm upgrade` does not care about modifying the state of the sidecar.

**Comment by max-rocket-internet** [comment]
Using `null` doesn't work as it's rejected by the k8s API (or a local check), for example:

```
Error: UPGRADE FAILED: cannot patch "el-k8s-event-logger" with kind Deployment: Deployment.apps "el-k8s-event-logger" is invalid: spec.template.spec.containers[0].image: Required value
```

I thought I could pre-create the deployment and then install the chart with no `image` set but then I get `existing resource conflict`

@bacongobbler is there another way to manage a deployment with Helm but not the image? Could I manually remove `spec.template.spec.containers[0].image` from the release by editing the release secret data?

**Comment by max-rocket-internet** [comment]
@bacongobbler do you think this is a valid feature request then?

**Comment by cablespaghetti** [comment]
I have the same issue but with HorizontalPodAutoscaler minReplicas. I have automation which tweaks this value but every Helm deploy it is reset back to the number in Git. I presume this also happens with the replicas count for a deployment, which might have been modified by a HPA but I haven't confirmed this second case.

**Comment by max-rocket-internet** [comment]
It's not stale. I would still like to see some idea of a solution here as this is still a major problem for us.

> I have automation which tweaks this value

This is exactly what I'm talking about. We have automation for deployments.

**Comment by lindhe** [comment]
:smiley:

**Comment by darjisanket** [comment]
We are also facing similar problem with HPA and we want HPA to be ignored by Helm.

**Comment by max-rocket-internet** [comment]
Not stale 😢

**Comment by jinnerbichler** [comment]
We are facing the same problem and have not found a solution yet.

**Comment by kevin-lindsay-1** [comment]
It'd be really nice to be able to do special customizations alongside helm and not have helm override it with a specific resource.

Personally, I'd be fine with something like `--ignore-resource=<resource name>.yaml`, and I could just apply my own version of that resource next to it, or in a different helm chart.

**Comment by khakunin** [comment]
this is not stale and we are facing similar issue. Please let us know how to ignore a specific yaml

**Comment by max-rocket-internet** [comment]
@bacongobbler can you change this issue tag to `feature`?

**Comment by sidpremkumar** [comment]
Can confirm not stale as well, and we are also interested in a possible solution to this.

**Comment by amartin-isp** [comment]
not stale, experiencing same issues as mentioned previously.

**Comment by philomory** [comment]
You could _almost_ solve this problem using Helm's `lookup` function, except, the `lookup` function breaks a bunch of _other_ automation tools because it's [unusable in a dry-run](https://github.com/helm/helm/issues/8137), which means things like `helm diff` and `helmfile apply` don't function correctly if you've got a call to `lookup` anywhere in your code.

For people who _don't_ make any use of `helm template`, `helm upgrade --dry-run`, `helm diff`, or any similar tool, here's a snippet that should solve this for you:

```yaml
{{- define "example.image" }}
{{- $existing := lookup "apps/v1" "Deployment" .Release.Namespace (include "example.fullname" .) }}
{{- $containers :=  dig "spec" "template" "spec" "containers" (list dict) $existing }}
{{- $container := index $containers 0 }}
{{- dig "image" (include "example.default-image" .) $container }}
{{- end }}
```

This isn't _perfect_: it assumes your container of interest is `spec.template.spec.containers[0]`, since Helm doesn't have easy support for anything like jsonpath's `spec.template.spec.containers[?(@.name == 'app')]`. But if that's a problem for you, you can find a given container by name using some complicated `range`-based workarounds.

The bigger problem, as noted above, is that there is _no_ method in Helm to preview what this function will do prior to actually running the install/upgrade, because all preview functions like `template` and `upgrade --dry-run` [refuse to contact the remote cluster](https://github.com/helm/helm/issues/8137) and will _always_ fall back to the designated default image.

**Comment by ravijkyada** [comment]
I am also Stuck with the same feature, Please Update if any feature or Work Around is available for the same,

I Want to ignore HPA While. we do helm upgrade in the CI/CD

**Comment by max-rocket-internet** [comment]
I don't think it's possible to reopen an issue closed by the stale bot unless you're a maintainer. The issue was open for almost 2 years with no resolution anyway.

**Comment by morremeyer** [comment]
This is also nothing helm is made for. Helm in my eyes is a tool to template resource definitions (and apply them).

For complex use cases like that, I deem tools like ArgoCD the much better option.

**Comment by ebuildy** [comment]
This is tricky because most of people will use Helm with argocd:

1) argocd get raw manifests via `helm template`
2) argocd apply manifests

So even if the solution is done on helm side, this will not work with argocd (or git'ops tools).

 As a (dirty) workaround, but used on production, we generate "mutable ressources" with a kube Job and right RBAC:

```yaml
# Create the configMap
apiVersion: batch/v1
kind: Job
spec:
  template:
    spec:
      serviceAccountName: patcho
      containers:
      - name: work
        image: bitnami/kubectl:1.24
        command: ["sh", "-c"]
        args:
        - |
          echo "Create status configMap"

          kubectl create configmap \
            my-status \
            --from-literal=status=todo
```

```yaml
# To modify the configMap
kubectl patch cm \
            my-status \
            --patch \
            '{"data" : {"status" : "done", "result" : "232 items processed"}}'
```

**Comment by umialpha** [comment]
We faced a similar issue.  IIUC, when helm supports server-side apply(https://github.com/helm/community/pull/312). we can set different ownership for different fields.

**Comment by cyclinder** [comment]
Same issue here, see https://github.com/helm/helm/issues/13506
