### ISSUE TITLE
plugin install returns success even the installation failed

### ISSUE THREAD

**Issue by pc-jedi** [helm/helm#7973]
The following error occurred in a CI Pipeline so I cannot reproduce it, but I it happen while GitHub had issues with connections timing out.

Below some printout:
 
```
helm plugin install https://github.com/hayorov/helm-gcs
Installing helm-gcs 0.3.1 ...
tar: invalid magic
tar: short read
helm-gcs 0.3.1 is correctly installed.
...
/root/.local/share/helm/plugins/helm-gcs/scripts/pull.sh: line 3: /root/.local/share/helm/plugins/helm-gcs/bin/helm-gcs: not found
Error: looks like "gs://xxxxxxxxxxx/" is not a valid chart repository or cannot be reached: plugin "scripts/pull.sh" exited with error
```

The interesting part is `tar: invalid magic`. This usually indicates a corrupted tar-file.
I think this "error" should be caught the same way as 504:
```
helm plugin install https://github.com/hayorov/helm-gcs
Error: Unable to get repository: Cloning into '/root/.cache/helm/plugins/https-github.com-hayorov-helm-gcs'...
fatal: unable to access 'https://github.com/hayorov/helm-gcs/': The requested URL returned error: 504
```

Output of `helm version`: 3.1.2
Output of `kubectl version`: 1.18.0

**Comment by bacongobbler** [comment]
Are you sure this isn’t coming from the install script that helm-gcs supplies? If so, it would indicate an issue with the plugin not reporting an error code back to helm.

https://github.com/hayorov/helm-gcs/blob/master/scripts/install.sh#L43

**Comment by pc-jedi** [comment]
Looks like you're right. I'll create an issue on there side.
