### ISSUE TITLE
Add automation to notify when KEYS file modified

### ISSUE THREAD

**Issue by jdolitsky** [helm/helm#7979]
The KEYS file contains public keys for maintainers who have signed a Helm release. If that file is compromised things could be bad.

We should add some automation to send an email to the security team if this file is modified.

Apprehensive to do this in GitHub or Circle since a modification of KEYS file indicates some write-level access to the repo, which could mean removing this automation prior to modifying KEYS ..

cc @bacongobbler @mattfarina

**Comment by jdolitsky** [comment]
Possible solutions if we use GitHub actions:

- https://github.com/marketplace/actions/get-changed-files
- https://github.com/marketplace/actions/send-email

**Comment by mattfarina** [comment]
@jdolitsky GitHub actions looks like a great way to do this. Make sure to pin to a version (or maybe a revision) if you do a PR for this.

**Comment by jdolitsky** [comment]
@mattfarina I dont think GitHub actions is actually appropriate for this. If I'm attacking, I'm disabling the workflow in the same commit I modify KEYS. Anything relying on receiving a webhook probably poses the same level of risk. Should be checked on a system that doesnt use GitHub credentials for login.

**Comment by jdolitsky** [comment]
(unstale-ify)
