### ISSUE TITLE
Validation for IP given in values.yaml

### ISSUE THREAD

**Issue by Mishra-Akash** [helm/helm#7989]
Hi Experts,

We need some help where I need to do the validation  for IP given in values.yaml.

Is there any function or way where I can validate the given IP is in correct format.
So  in values.yaml IP format is not correct, helm install get failed for complaining the same. 

Output of `helm version`:
Client: &version.Version{SemVer:"v2.14.2", GitCommit:"524294565799aba901a242fb7a12cef454c9cb10", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-20T11:45:27Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-20T11:40:58Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Platform -  HP Blader
OS- SUSE 15

**Comment by bacongobbler** [comment]
Not that I’m aware of, no.

**Comment by omkensey** [comment]
In Helm 2 this isn't subject to validation but could the JSON Schema capability in Helm 3 provide this?

**Comment by Mishra-Akash** [comment]
I haven't found in helm3 as well.

**Comment by Mishra-Akash** [comment]
I tried to define a variable to validate IPv4.  And meantime, its working for me.

{{- define "validateIPv4" -}}
{{ $error := "Must be a valid IPv4 address!" }}
{{- range $_, $myIPv4 :=  .Values.systemIPs }}
  {{- if (empty $myIPv4) true }}
    {{ fail ( cat "[" $myIPv4 " ]" $error ) }}
  {{- end }}
  {{- $octetsList := splitList "."  $myIPv4 }}
  {{- if ne ( $octetsList | len ) 4 }}
    {{ fail ( cat "[" $myIPv4 "]" $error ) }}
  {{- end }}
  {{- range $_, $octet:=  $octetsList }}
    {{- if eq ( regexMatch "^[0-9]{0,}$" $octet) false }}
      {{ fail ( cat "[" $myIPv4 "]" $error ) }}
    {{- else if gt (int $octet) 255 }}
      {{ fail ( cat "[" $myIPv4 "]" $error ) }}
    {{- else if and ( eq (int $octet) 0 )  ( eq $_ 0 ) }}
      {{ fail ( cat "[" $myIPv4 "]" $error ) }}
    {{- else if (empty $octet) true }}
      {{ fail ( cat "[" $myIPv4 "]" $error ) }}
    {{- end -}}
  {{- end -}}
{{- end -}}
{{- end -}}

And calling in yaml via {{ include "validateIPv4" . }}.

I am not sure if there is some other better way to achieve this via predefined function.

**Comment by technosophos** [comment]
Use a JSON schema in Helm 3. I'm sure you could write a Go function and contribute it to Sprig for inclusion as a template function. But there is no out-of-the-box support for that currently.

**Comment by Mishra-Akash** [comment]
Any help or doc to use a JSON schema in Helm 3. I will check this.

**Comment by Mishra-Akash** [comment]
Also one more thing if u can suggest from security point of view, can we do the password complexity verification for the value passed in values.yaml?

**Comment by bacongobbler** [comment]
https://helm.sh/docs/topics/charts/#schema-files

**Comment by Mishra-Akash** [comment]
Ok. Thanks

**Comment by bridgetkromhout** [comment]
Hi, @Mishra-Akash - we think your issues can be solved with https://helm.sh/docs/topics/charts/#schema-files as described above. If you have further questions, please let us know; thanks!
