### ISSUE TITLE
.Capabilities.KubeVersion should indicate it's fabricated when helm template isn't validating against the cluster

### ISSUE THREAD

**Issue by omkensey** [helm/helm#7991]
When I dump the root context in a debugging template with `toYaml $`, I see the following for .Capabilities.KubeVersion:

```
    KubeVersion:
      Major: "1"
      Minor: "16"
      Version: v1.16.0
```

However, the actual running cluster is microk8s running 1.18.1 (see kubeversion info below).

Output of `helm version`: 

```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

Output of `kubectl version`: 

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:30:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): microk8s

**Comment by omkensey** [comment]
Ah, something occurred to me and I see that using either `template --validate` or `install --dry-run --debug` gives the correct Kubernetes version of my actual cluster.  Can the version given when running `template` without validation indicate explicitly (maybe by appending a SemVer-compliant build metadata tag, e.g. "v1.16.0+helm-template-kubeversion") that it's fake somehow?  It's documented that `template` fakes all cluster data client-side but a reminder would be useful.  (#2898 added a `--kube-version` flag to `template` so users can specify the version as whatever they want, but that doesn't seem to exist in Helm 3's version of `template`.)

**Comment by technosophos** [comment]
`helm template` _always_ fakes its data in the following categories:

- Kubernetes version: It is supposed to report the version of Kubernetes that it is compiled for
- Capabilities: It fakes all of this
- Anything that users discovery client: It uses the default discovery set
- `lookup`: It always returns an empty list of objects

I don't really have strong feelings about whether we should munge the data... but this is a documented feature of Helm.

**Comment by omkensey** [comment]
One case beyond just reinforcing "this is faked data" would be allowing charts to detect and react to being rendered as part of a `template` run (for example, by putting out diagnostic or explanatory comments) vs. an `install` run.

**Comment by bridgetkromhout** [comment]
> One case beyond just reinforcing "this is faked data" would be allowing charts to detect and react to being rendered as part of a template run (for example, by putting out diagnostic or explanatory comments) vs. an install run.

Hi, @omkensey! This is an interesting idea, and if you want to explore it, it would be nice if you could open a [Helm Improvement Proposal](https://github.com/helm/community/blob/master/hips/hip-0001.md) as then the community could discuss the details and arrive at the best implementation. I'll close this issue but a HIP would be a good place to talk about these design considerations.

As for documentation about how `helm template` operates, https://helm.sh/docs/helm/helm_template/#synopsis does say "Any values that would normally be looked up or retrieved in-cluster will be faked locally" but we welcome documentation PRs that add more detail as well as proposals to (re)add more CLI flags.
