### ISSUE TITLE
Helm dependency handling needs cleanup?

### ISSUE THREAD

**Issue by omkensey** [helm/helm#7993]
(Filing subsequent to 4/23 developer call)

Helm dependency handling and the documentation thereof needs a comprehensive look and maybe some code/doc cleanup.

The immediate issue is that when I ran `helm dep up` in my home directory by accident rather than a chart directory, it ate a CPU core and all free memory.  I think this was because it's traversing every directory in sight; using strace on a test system revealed that it recursed through the entire directory it was invoked in, plus: 

```
/proc
/usr/local/bin/pass
/usr/bin/pass
/usr/local/sbin/pass
/usr/sbin/pass
/var/lib/snapd/snap/bin/pass
/usr/local/bin/docker-credential-secretservice
/usr/bin/docker-credential-secretservice
/usr/local/sbin/docker-credential-secretservice
/usr/sbin/docker-credential-secretservice
/var/lib/snapd/snap/bin/docker-credential-secretservice
```

As I understand it:

1) `helm dep up` when invoked in (or at) a local chart directory should only touch two things: `Chart.yaml` and the `charts` subdirectory.  If `Chart.yaml` doesn't exist we should get an error (in fact we do, when the directory tree isn't so deep and complex as the one that choked my other system: `Error: validation: chart.metadata is required`)

2) `helm dep up` is intended not to be recursive (although I can't currently find the documentation that I recall stating that), which leads me to believe that the recursive search is an error even with a valid chart directory as the target for `dep up`.

3) Incidental to the above, during discussion of the foregoing on the dev call, I mentioned that I had read that dependencies are not required to be declared in `Chart.yaml` and somebody stated that they understood that the intent currently was that that was indeed required.  Currently this text exists in the output of `helm dep up --help`:

   `Dependencies are not required to be represented in 'Chart.yaml'.`

   The same statement of course appears on helm.sh in the autogenerated doc for `helm dependency update`.  If these are not the case then the CLI might need a doc update.

Output of `helm version`:  `version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}`

**Comment by technosophos** [comment]
I added the bug label since we don't seem to have a better label for this sort of meta issue.

**Comment by bridgetkromhout** [comment]
Hi, @omkensey - Thank you for your ideas to improve Helm. If you'd like, you can submit a Helm Improvement Proposal so as to work in the community to make your ideas a reality: https://github.com/helm/community/blob/master/hips/hip-0001.md - meanwhile, I will close this issue. Thanks!
