### ISSUE TITLE
Helm does not see a later version of a chart in a repo that moves the chart apiVersion from v2 back to v1

### ISSUE THREAD

**Issue by omkensey** [helm/helm#7994]
In writing a stub chart for some debugging I initially wrote it with `version: 0.1.0` and `apiVersion: v2`.  After I was done and pushed it to the GitHub repo I was using as a Helm repo for it I realized a) I needed a fix to the chart syntax and b) there was nothing Helm-3-specific about the chart, so it wasn't necessary to restrict it to v2 chart API.  I pushed a new version with `version: 0.1.1` and `apiVersion: v1` along with a new index, ran `helm repo update` locally and still saw 0.1.0 as the latest available.  When I manually commented out the 0.1.0 version from the index and re-pushed just that file, the 0.1.1 version showed up as the latest after another `update`.

Intuitively it seems like it's not unreasonable that a chart might regress its API version in this way for a later version, since besides the above scenario, it's plausible that a chart developer might initially develop a chart for new deployments and later update it to be compatible with older ones as well.  However, I understand there might be issues with this kind of API regression when it comes to updating releases, so if this behavior is intentional, it might be good to call it out in docs (unless it already is -- I didn't see it anywhere though).

Output of `helm version`: `version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}`

**Comment by technosophos** [comment]
This is definitely a path that we have not tested. However, I am unsure why it would have failed to show the new chart. It _should_ show any apiVersion chart equally.

I am marking this as a bug. Can you provide me with steps to reprduce? Is it as simple as `helm create, repo update, edit version, repo update"?

**Comment by omkensey** [comment]
Pretty much.  If you look at https://omkensey.github.io/helm-contextdump/, that's the repo that the stub chart is in, and index.yaml currently has the 0.1.0 version commented out.  You should be able (I think) to reproduce by putting index.yaml and the two package files in an empty repo with the 0.1.0 version uncommented in the index.

**Comment by bridgetkromhout** [comment]
Hi, @omkensey - while none of us have yet looked into this, I am going to remove the Stale label as I think this may be something we can get to in the upcoming <undefined period of time>.
