### ISSUE TITLE
Helm test continue on failure

### ISSUE THREAD

**Issue by tomassatka** [helm/helm#8004]
Is there a way how to define that all tests provided in /template/tests are executed? 
At the moment after first failure other tests wont be executed. So looking for some flag as continue on failure.

Use case: With tests i am validating all egress routes required by installed application and would like to get full status

**Comment by omkensey** [comment]
To the best of my knowledge it's intentional that any exit status other than success of a container in the test pod causes the test to be considered failed.  If you want some tests to be run but success to be optional, you probably want to write it to emit a warning message so you can see it in the logs, but still exit with result code 0.

**Comment by tomassatka** [comment]
I am really ok with success/failed status of individual test (pod). What concerns me is the fact that in case of multiple tests they are executed in order and first failure will stop the execution so helm test command provide only limited view. Either all tests are working or first failure was found. IMHO feature to execute other tests after first failure was found would be helpful. Fixing a single test can be time consuming task like requesting an exception in enterprise firewall so iterating over them one by one is not efficient process.

**Comment by bridgetkromhout** [comment]
Hi, @tomassatka! Thank you for your ideas to improve Helm. If you'd like, you can submit a Helm Improvement Proposal so as to work in the community to make your ideas a reality: https://github.com/helm/community/blob/master/hips/hip-0001.md - meanwhile, I will close this issue. Thanks!

**Comment by freegnu** [comment]
use the --filter strings to run individual tests one at a time or in parallel

**Comment by AniekanAkai** [comment]
@freegnu 
> use the --filter strings to run individual tests one at a time or in parallel

Thanks for that suggestion. How in helm v3 do you make the tests run in parallel with --filter flag? The --parallel flag was removed and I cannot find enough examples online of helm test with --filter flag.
