### ISSUE TITLE
version  flags is ignored when installing release with "helm upgrade --install"

### ISSUE THREAD

**Issue by arnonki** [helm/helm#8005]
Output of `helm version`:
version.BuildInfo{Version:"v3.1.0", GitCommit:"b29d20baf09943e134c2fa5e1e1cab3bf93315fa", GitTreeState:"clean", GoVersion:"go1.13.8"}
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

**Comment by technosophos** [comment]
I do not understand this issue. More information is needed.

Please describe your problem in detail, providing example helm commands and an example Helm chart if applicable.

**Comment by yonatankahana** [comment]
If I understand correctly, you use the `helm upgrade --install` command to perform install\upgrade. You also specify `--version` to get a particular version. But helm ignores the version you requested and falls to the default. 
That could be related to https://github.com/helm/helm/pull/7640 that already available in v3.2.0.
I couldn't reproduce the bug with the latest version, hopefully I understood you correctly..

**Comment by technosophos** [comment]
I am testing on `master` (3.2+unreleased).

```console
$ helm search repos -l stable/chartmuseum 
NAME              	CHART VERSION	APP VERSION	DESCRIPTION
stable/chartmuseum	2.10.0       	0.12.0     	Host your own Helm Chart Repository
stable/chartmuseum	2.9.0        	0.11.0     	Host your own Helm Chart Repository
stable/chartmuseum	2.8.0        	0.11.0     	Host your own Helm Chart Repository
stable/chartmuseum	2.7.1        	0.11.0     	Host your own Helm Chart Repository
stable/chartmuseum	2.7.0        	0.11.0     	Host your own Helm Chart Repository
stable/chartmuseum	2.6.1        	0.11.0     	Host your own Helm Chart Repository
stable/chartmuseum	2.6.0        	0.11.0     	Host your own Helm Chart Repository
stable/chartmuseum	2.5.0        	0.10.0     	Host your own Helm Chart Repository
stable/chartmuseum	2.4.1        	0.8.2      	Host your own Helm Chart Repository
stable/chartmuseum	2.4.0        	0.8.2      	Host your own Helm Chart Repository
stable/chartmuseum	2.3.3        	0.8.2      	Host your own Helm Chart Repository
... more omitted
```

Install 2.4.0:

```console
$ helm upgrade --install --version 2.4.0 cm stable/chartmuseum
Release "cm" does not exist. Installing it now.
NAME: cm
LAST DEPLOYED: Mon May  4 14:31:52 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
** Please be patient while the chart is being deployed **

Get the ChartMuseum URL by running:

  export POD_NAME=$(kubectl get pods --namespace default -l "app=chartmuseum" -l "release=cm" -o jsonpath="{.items[0].metadata.name}")
  echo http://127.0.0.1:8080/
  kubectl port-forward $POD_NAME 8080:8080 --namespace default
```

Check to make sure 2.4.0 is installed:

```console
$ helm ls
NAME	NAMESPACE	REVISION	UPDATED                            	STATUS  	CHART            	APP VERSION
cm  	default  	1       	2020-05-04 14:31:52.96412 -0600 MDT	deployed	chartmuseum-2.4.0	0.8.2
```

Use `upgrade --install` to go to 2.4.1 (still behind the latest):

```
$ helm upgrade --install --version 2.4.1 cm stable/chartmuseum
Release "cm" has been upgraded. Happy Helming!
NAME: cm
LAST DEPLOYED: Mon May  4 14:36:14 2020
NAMESPACE: default
STATUS: deployed
REVISION: 2
TEST SUITE: None
NOTES:
** Please be patient while the chart is being deployed **

Get the ChartMuseum URL by running:

  export POD_NAME=$(kubectl get pods --namespace default -l "app=chartmuseum" -l "release=cm" -o jsonpath="{.items[0].metadata.name}")
  echo http://127.0.0.1:8080/
  kubectl port-forward $POD_NAME 8080:8080 --namespace default
```

Check again:

```console
$ helm ls
NAME	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART            	APP VERSION
cm  	default  	2       	2020-05-04 14:36:14.518717 -0600 MDT	deployed	chartmuseum-2.4.1	0.8.2
```

I tried the above a few more times, and all seems to work correctly. Can you either try again with Helm 3.2.0 or provide me more info so I can try to reproduce?

**Comment by arnonki** [comment]
Hey Matt,

I really appreciate your help with this,
I will try to upgrade my helm and update you on this one.

Unfortunately I am super busy with other stuff going on so I cannot commit
to a prompt response.
I know that the issue quality is poor but I still decided to open it so
that if there is a real bug it would be a  shame to support the project but
not to report it. (maybe it was wrong decision)

If you can put it on hold in the meantime, please do...

Sorry again

**Comment by bridgetkromhout** [comment]
Hi, @arnonki  - as we cannot reproduce this bug with the latest helm version, and we have no further details to help us, we will close this issue at this time. If at some point you are able to help us reproduce it, then we can try to troubleshoot. Thanks!
