### ISSUE TITLE
helm dep up getting failed - x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by atotala** [helm/helm#8009]
I am facing the issue with the command 'helm dep up' .. every other command related to helm is working but not the above one. I know there are many issues open similar to this one but Haven't found solution in anyone of them so opening a new one.
Below are the details of configuration. Let me know if anything else is needed for resolving the problem.

Error:

 helm dep up
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "chart" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 7 charts
Downloading vault from repo http://some-repo
Save error occurred:  could not download https://some-chart.com/chartrepo/dev/charts/vault-0.5.0.tgz: Get hthttps://some-chart.com/chartrepo/dev/charts/vault-0.5.0.tgz: x509: certificate signed by unknown authority
Deleting newly downloaded charts, restoring pre-update state
Error: could not download https://some-chart.com/chartrepo/dev/charts/vault-0.5.0.tgz: Get https://some-chart.com/chartrepo/dev/charts/vault-0.5.0.tgz: x509: certificate signed by unknown authority
ubuntuserver-18-x8664:~$

Output of `helm version`:
version.BuildInfo{Version:"v3.2.0-rc.1", GitCommit:"7bffac813db894e06d17bac91d14ea819b5c2310", GitTreeState:"clean", GoVersion:"go1.13.10"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  Minikube.

**Comment by bacongobbler** [comment]
> Downloading vault from repo http://some-repo
Save error occurred: could not download https://some-chart.com/chartrepo/dev/charts/vault-0.5.0.tgz: Get hthttps://some-chart.com/chartrepo/dev/charts/vault-0.5.0.tgz: x509: certificate signed by unknown authority

In this log message, I notice two things:

1. The first repository URL uses http:// in the name
2. The last URL uses the scheme hthttps://

Can you please check your settings and see if they are correct? Also, please post the output of your requirements.yaml, Chart.yaml, and the output of `helm repo list`.

**Comment by atotala** [comment]
@bacongobbler : 
ubuntuserver-18-x8664:$ helm repo list
NAME    URL                                                
chart https://some-chart.com/chartrepo/dev
ubuntuserver-18-x8664:$

Output of Chart.yml.
============================
apiVersion: v2
name: chart-umbrella
description: A Helm chart for Kubernetes
dependencies:
- name: vault
  version: 0.5.0
  repository: https://some-repo.com/chartrepo/dev
version: 0.1.0
appVersion: 1.16.0
icon: http://pngimg.com/uploads/umbrella/umbrella_PNG69167.png

================================ 
Not using requirement.yaml
the URL in point 1 you mentioned is a type

**Comment by technosophos** [comment]
You can try using `curl -vvv  https://some-chart.com/chartrepo/dev/charts/vault-0.5.0.tgz` to fetch the chart from the command line. It should give you information about whether the TLS certificate is indeed invalid. But that is probably the error.

It may simply be the case that you do not have the root certificates for SSL installed locally. On most Linux distros, this is an extra package to install (though on Mac and Windows this comes pre-bundled with the operating system).

**Comment by bridgetkromhout** [comment]
Hi, @atotala - hopefully your question was resolved, perhaps by installing the root certificates for SSL. We'll resolve this issue now; if you are still experiencing issues, please let us know.

**Comment by b0nete** [comment]
I use MacOS, helm version 3.5.3 and have my self-hosted chartmuseum behind a LB with a custom certificate.
`version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.16"}`

I added my repo successfully specifying the pem certificate (helm repo add name https://url --ca-file /path/ca.pem) and even i do a "helm repo update" and "helm search repo" without problems.

The problem was generated when use "helm dependency update" getting the follow error 
`x509: certificate signed by unknown authority`

Then, i go to Keychain Access app and trust in your certificate.
![image](https://user-images.githubusercontent.com/11648772/114773764-d4987e80-9d45-11eb-951c-a1138d9e3a9e.png)

**Comment by udipl** [comment]
@b0nete were you able to get `helm dependency update` to succeed?
