### ISSUE TITLE
Cannot disable openapi validation during helm upgrade

### ISSUE THREAD

**Issue by Gl4di4torRr** [helm/helm#8010]
**Output of `helm version`:**
`$ helm version
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}`

**Output of `kubectl version`:**
`$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-19T22:12:47Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6+999bb21", GitCommit:"999bb21", GitTreeState:"clean", BuildDate:"2020-02-17T18:41:39Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}`

**Cloud Provider/Platform:**
I am using OpenShift 4.2
`$ oc version
Client Version: version.Info{Major:"4", Minor:"1+", GitVersion:"v4.1.0+b4261e0", GitCommit:"b4261e07ed", GitTreeState:"clean", BuildDate:"2019-07-06T03:16:01Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6+999bb21", GitCommit:"999bb21", GitTreeState:"clean", BuildDate:"2020-02-17T18:41:39Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}`

**The Problem:**
1. I install the chart with the disable openapi validation.

```
$ helm install -f charts/values.yaml enterprise-pipeline ./charts/ --disable-openapi-validation
NAME: enterprise-pipeline
LAST DEPLOYED: Mon Apr 27 14:45:15 2020
NAMESPACE: mynamespace
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

2. I try to upgrade my chart with the disable openapi validation
```
$ helm upgrade -f charts/values.yaml enterprise-pipeline ./charts/ --disable-openapi-validation
Error: unknown flag: --disable-openapi-validation
```

3. I remove the disable openapi validation. Now I am back to where I started. That is, trying to make each OpenShift objects compliant with the openapi validation, which does not seem possible right now.

```
$ helm upgrade -f charts/values.yaml enterprise-pipeline ./charts/
Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(BuildConfig.spec): missing required field "nodeSelector" in com.github.openshift.api.build.v1.BuildConfigSpec, ValidationError(BuildConfig): missing required field "status" in com.github.openshift.api.build.v1.BuildConfig]
```

**Comment by bacongobbler** [comment]
Is this still an issue with helm 3.2.0?

**Comment by Gl4di4torRr** [comment]
@bacongobbler Looks like that did the trick :) 3.2.0 came out 5 days ago. When I was working on this last week, I checked to see if there was an update. Should have checked today :)

```
$ helm upgrade -f charts/values.yaml enterprise-pipeline ./charts/ --disable-openapi-validation
Release "enterprise-pipeline" has been upgraded. Happy Helming!
NAME: enterprise-pipeline
LAST DEPLOYED: Mon Apr 27 15:33:47 2020
NAMESPACE: mynamespace
STATUS: deployed
REVISION: 2
TEST SUITE: None
```
