### ISSUE TITLE
toToml converstion

### ISSUE THREAD

**Issue by ranjith-ka** [helm/helm#8014]
Output of `helm version`: version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.10", GitCommit:"37d169313237cb4ceb2cc4bef300f2ae3053c1a2", GitTreeState:"clean", BuildDate:"2019-08-19T10:44:49Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Minikube/AWS

`{{ define "mychar.toml" }}
    {{ range $section, $settings := .Values.env.testing -}}
    {{ printf "[%s]" $section }}
    {{ range $key, $value := $settings -}}
    {{ $key }}: {{ $value | toToml }}
    {{ end }}
    {{ end }}
{{ end }}`

`toml: top-level values must be Go maps or structs`

Why i am not able to convert the Value as toToml ? may be something i am missing

**Comment by bacongobbler** [comment]
Hi @ranjith-ka. There’s not enough information in this ticket to understand what you are trying to convey. Please provide a more concrete example (with source code and steps provided) to reproduce and demonstrate your use case/issue. Thanks.

**Comment by ranjith-ka** [comment]
config:   
  kafka:
      listenaddr: "vnext-kafka-headless.kafka.svc.cluster.local:9092"
      topics: "awesome, testorder"

I need to print the  topics values in toToml, but i need to loop over the root values for toToml ? 
`{{ printf "%s = %v" $key ($value | quote ) }}` 
Now i dow like this to print on my configmap.

**Comment by mattfarina** [comment]
I see. This is a feature request for a `toToml` template function.

**Comment by bridgetkromhout** [comment]
Hi, @ranjith-ka - Thank you for your ideas to improve Helm. If you'd like, you can submit a Helm Improvement Proposal so as to work in the community to make your ideas a reality: https://github.com/helm/community/blob/master/hips/hip-0001.md - meanwhile, I will close this issue. Thanks!
