### ISSUE TITLE
HELM delete the post-hook directly rather than waiting it to be finished 

### ISSUE THREAD

**Issue by zhangmingld** [helm/helm#8016]
Output of `helm version`: 
Client: &version.Version{SemVer:"v2.15.1", GitCommit:"bf1a9adb587795da9a165ef411c3b6e1eeca6ffe", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.1", GitCommit:"bf1a9adb587795da9a165ef411c3b6e1eeca6ffe", GitTreeState:"clean"}

Output of `kubectl version`:
node-0-10:~ # kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-28T19:00:13Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-28T18:54:53Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
N/A

Here is the log

```
[tiller] 2020/04/26 08:12:19 executing 23 post-delete hooks for egress-1.2.0-58-zm
[tiller] 2020/04/26 08:12:19 deleting post-delete hook appManager-postgres-hook-cleanup for release egress-1.2.0-58-zm due to "before-hook-creation" policy
[kube] 2020/04/26 08:12:19 Starting delete for "appManager-postgres-hook-cleanup" Job
[kube] 2020/04/26 08:12:19 jobs.batch "appManager-postgres-hook-cleanup" not found
[kube] 2020/04/26 08:12:19 Waiting for 60 seconds for delete to be completed
[kube] 2020/04/26 08:12:22 building resources from manifest
[kube] 2020/04/26 08:12:22 creating 1 resource(s)
[kube] 2020/04/26 08:12:22 Watching for changes to Job appManager-postgres-hook-cleanup with timeout of 5m0s
[kube] 2020/04/26 08:12:22 Add/Modify event for appManager-postgres-hook-cleanup: ADDED
[kube] 2020/04/26 08:12:22 appManager-postgres-hook-cleanup: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
[kube] 2020/04/26 08:12:22 Add/Modify event for appManager-postgres-hook-cleanup: MODIFIED
[kube] 2020/04/26 08:12:22 appManager-postgres-hook-cleanup: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
[kube] 2020/04/26 08:12:34 Add/Modify event for appManager-postgres-hook-cleanup: MODIFIED
[tiller] 2020/04/26 08:12:34 deleting post-delete hook identity-database-pg-hook-cleanup for release egress-1.2.0-58-zm due to "before-hook-creation" policy
[kube] 2020/04/26 08:12:34 Starting delete for "identity-database-pg-hook-cleanup" Job
[kube] 2020/04/26 08:12:34 jobs.batch "identity-database-pg-hook-cleanup" not found
[kube] 2020/04/26 08:12:34 Waiting for 60 seconds for delete to be completed
[kube] 2020/04/26 08:12:36 building resources from manifest
[kube] 2020/04/26 08:12:36 creating 1 resource(s)
[kube] 2020/04/26 08:12:36 Watching for changes to Job identity-database-pg-hook-cleanup with timeout of 5m0s
[kube] 2020/04/26 08:12:36 Add/Modify event for identity-database-pg-hook-cleanup: ADDED
[tiller] 2020/04/26 08:12:36 hooks complete for post-delete egress-1.2.0-58-zm
[tiller] 2020/04/26 08:12:36 deleting post-delete hook appManager-postgres-hook-cleanup for release egress-1.2.0-58-zm due to "hook-succeeded" policy
[kube] 2020/04/26 08:12:36 Starting delete for "appManager-postgres-hook-cleanup" Job
[kube] 2020/04/26 08:12:36 Waiting for 60 seconds for delete to be completed
[tiller] 2020/04/26 08:12:38 deleting post-delete hook identity-database-pg-hook-cleanup for release egress-1.2.0-58-zm due to "hook-succeeded" policy
[kube] 2020/04/26 08:12:38 Starting delete for "identity-database-pg-hook-cleanup" Job
[kube] 2020/04/26 08:12:38 Waiting for 60 seconds for delete to be completed
[tiller] 2020/04/26 08:12:40 purge requested for egress-1.2.0-58-zm
[storage] 2020/04/26 08:12:40 deleting release "egress-1.2.0-58-zm.v1"
```

According to the log, for identity-database-pg-hook-cleanup
it shows

```
[kube] 2020/04/26 08:12:34 Starting delete for "identity-database-pg-hook-cleanup" Job
[kube] 2020/04/26 08:12:34 jobs.batch "identity-database-pg-hook-cleanup" not found
[kube] 2020/04/26 08:12:34 Waiting for 60 seconds for delete to be completed
[kube] 2020/04/26 08:12:36 building resources from manifest
[kube] 2020/04/26 08:12:36 creating 1 resource(s)
[kube] 2020/04/26 08:12:36 Watching for changes to Job identity-database-pg-hook-cleanup with timeout of 5m0s
[kube] 2020/04/26 08:12:36 Add/Modify event for identity-database-pg-hook-cleanup: ADDED
[tiller] 2020/04/26 08:12:36 hooks complete for post-delete egress-1.2.0-58-zm
[tiller] 2020/04/26 08:12:36 deleting post-delete hook appManager-postgres-hook-cleanup for release egress-1.2.0-58-zm due to "hook-succeeded" policy
[kube] 2020/04/26 08:12:36 Starting delete for "appManager-postgres-hook-cleanup" Job
[kube] 2020/04/26 08:12:36 Waiting for 60 seconds for delete to be completed
[tiller] 2020/04/26 08:12:38 deleting post-delete hook identity-database-pg-hook-cleanup for release egress-1.2.0-58-zm due to "hook-succeeded" policy
[kube] 2020/04/26 08:12:38 Starting delete for "identity-database-pg-hook-cleanup" Job
[kube] 2020/04/26 08:12:38 Waiting for 60 seconds for delete to be completed
[tiller] 2020/04/26 08:12:40 purge requested for egress-1.2.0-58-zm
```

From the start to end, only 2 senconds are given for post-hook operation.

Notes:
 egress-1.2.0-58-zm is the top level chart, and identity-database-pg is its dependency

**Comment by bacongobbler** [comment]
Hi @zhangmingld. Based on the information provided, I cannot understand what you are trying to convey here. Can you please provide more information about the behaviour you are describing and what issues you see. I'm not sure what I'm supposed to be looking at.

In addition, please check and make sure this is still an issue with the latest version of Helm 2. Helm 2.16.5 is the latest release.

Thanks.

**Comment by zhangmingld** [comment]
Hi @bacongobbler , Sorry for my late reply.
 "identity-database-pg-hook-cleanup" is the hook of dependency chart(post-delete egress-1.2.0-58-zm is the father chart),
 when delete, the whole chart did not wait it to finished

`[kube] 2020/04/26 08:12:34 Starting delete for "identity-database-pg-hook-cleanup" Job
[kube] 2020/04/26 08:12:34 jobs.batch "identity-database-pg-hook-cleanup" not found
[kube] 2020/04/26 08:12:34 Waiting for 60 seconds for delete to be completed
[kube] 2020/04/26 08:12:36 building resources from manifest
[kube] 2020/04/26 08:12:36 creating 1 resource(s)
[kube] 2020/04/26 08:12:36 Watching for changes to Job identity-database-pg-hook-cleanup with timeout of 5m0s
[kube] 2020/04/26 08:12:36 Add/Modify event for identity-database-pg-hook-cleanup: ADDED
[tiller] 2020/04/26 08:12:36 hooks complete for post-delete egress-1.2.0-58-zm
[tiller] 2020/04/26 08:12:36 deleting post-delete hook appManager-postgres-hook-cleanup for release egress-1.2.0-58-zm due to "hook-succeeded" policy
`

look at the log here, 
`[kube] 2020/04/26 08:12:34 Starting delete for "identity-database-pg-hook-cleanup" Job
[kube] 2020/04/26 08:12:34 jobs.batch "identity-database-pg-hook-cleanup" not found
[kube] 2020/04/26 08:12:34 Waiting for 60 seconds for delete to be completed
[kube] 2020/04/26 08:12:36 building resources from manifest
[kube] 2020/04/26 08:12:36 creating 1 resource(s)`

the hook identity-database-pg-hook-cleanup Job  are created .

Then helm begin to monitor it to be finished.
`[kube] 2020/04/26 08:12:36 Watching for changes to Job identity-database-pg-hook-cleanup with timeout of 5m0s
[kube] 2020/04/26 08:12:36 Add/Modify event for identity-database-pg-hook-cleanup: ADDED`

until here, it is normal.

but then, the job has not been finished yet, it is deleted by helm( helm say the father hook has been finished and delete the dependency hook directly , did not wait it to be finished)
`[tiller] 2020/04/26 08:12:38 deleting post-delete hook identity-database-pg-hook-cleanup for release egress-1.2.0-58-zm due to "hook-succeeded" policy`

let` s look at the time :
08:12:34 the dependency hook job are created 
08:12:38 the dependency hook job are deleted.
4 seconds is not enough for a job to be finished

**Comment by bridgetkromhout** [comment]
Hi, @zhangmingld - Helm v2 is now deprecated; please try Helm v3. If problems exist in Helm v3 we will accept issues and pull requests, but we are no longer accepting bug fixes for Helm v2. Thanks.  https://helm.sh/blog/helm-v2-deprecation-timeline/
