### ISSUE TITLE
Load file as dictionary

### ISSUE THREAD

**Issue by tamalsaha** [helm/helm#8020]
Is it possible to load a file as `dict` so that I can apply [dictionary](https://github.com/Masterminds/sprig/blob/master/docs/dicts.md) functions? An example usage will be:

```
get (.Files.Glob "data.yaml").AsDict "key1"
```

If not, can this feature be supported in Helm 3 ?

**Comment by tamalsaha** [comment]
Looks like it is possible using something like below:

```
get (.Files.Get "data.yaml" | fromYaml) "key"
```

**Comment by himmakam** [comment]
can you please let me know if you are able to load file as dict and do the functions.

**Comment by tamalsaha** [comment]
@himmakam , it worked . Here is an example: https://github.com/kubedb/profile-charts/blob/master/charts/mongodb/templates/db.yaml#L6

**Comment by himmakam** [comment]
@tamalsaha Thanks a lot for your quick response and udpate.

**Comment by himmakam** [comment]
@hickeyma Thanks for referring me to the other issue

**Comment by himmakam** [comment]
@tamalsaha For some reason I am getting empty map even the yaml had contents. 

{{- $filedict := .Files.Get "files/data.yaml" | fromYaml -}}

**Comment by tamalsaha** [comment]
All the functions are defined here: https://github.com/helm/helm/blob/master/pkg/engine/funcs.go#L49 . May be dig around and see if you can find the problem.

**Comment by himmakam** [comment]
No am exactly using your data.yaml only just to cross-check. somehow am getting empty map.

**Comment by himmakam** [comment]
lets say my data.yaml is like this 

foo: bar

and in configmap.yaml, am using 

{{- $filedict := .Files.Get "data.yaml" | fromYaml -}} where data.yaml is in root directory. 
When I see this filedict has empty contents.

**Comment by tamalsaha** [comment]
Check if the  `.Files.Get` is actually getting the file. May be pass it to a configmap or label to see if it is showing up.

**Comment by himmakam** [comment]
hey..pls ignore. am checking in wrong chart. It worked thanks a lot.
