### ISSUE TITLE
Liveness / Readiness probe output

### ISSUE THREAD

**Issue by techdragon157** [helm/helm#8023]
Output of `helm version`: 
v3.1.2

Output of `kubectl version`:
v1.16.2

is it possible for Helm debug to output the status of readiness and liveness probes during an upgrade? reason being we are running upgrades using the `atomic` and `debug` flag enabled. 

Sometimes the deployment fails as our readiness probes have failed for some reason, at the moment we need to go into the cluster to see why it failed. It would be really good to just look at the output from Helm to see why.

is this possible?

**Comment by tech-dragon157** [comment]
Is this something that is possible from Helm? or a feature that could be added in?
