### ISSUE TITLE
nil pointer evaluating interface when upper level doesn't exist prevents usage of default function

### ISSUE THREAD

**Issue by michael-todorovic** [helm/helm#8026]
Hello,
I'll take an example template but the issue is more global than that I think.

I define a simple Service template:
```
apiVersion: v1
kind: Service # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#service-v1-core
metadata:
  name: MyService
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: alt-http
```
In my `values.yaml`, when I define 
```
service:
  type: somevalue
```
Everything goes well. It does also when I define the following:
```
service: {}
```
But if I don't define `service` at all, I get an error:
```
╰ helm template . --debug
install.go:159: [debug] Original chart version: ""
install.go:176: [debug] CHART PATH: /home/mtodorovic/git/helm-issue/helm-chart


Error: template: helm-chart/templates/service.yaml:6:18: executing "helm-chart/templates/service.yaml" at <.Values.service.type>: nil pointer evaluating interface {}.type
helm.go:84: [debug] template: helm-chart/templates/service.yaml:6:18: executing "helm-chart/templates/service.yaml" at <.Values.service.type>: nil pointer evaluating interface {}.type
```

As soon as the parent value doesn't exist, templating fails and totally ignores the default function. I expected that if anything goes wrong in `.Values.service.type` evaluation, we'll go to `default "ClusterIP"` but it doesn't.

We workaround the issue with the following but it wouldn't work as easily for big dicts (like `dict.bigkey.subkey.key`)
```
{{- $service := .Values.service | default dict -}} # workaround for https://github.com/helm/helm/issues/8026
apiVersion: v1
kind: Service # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#service-v1-core
metadata:
  name: MyService
spec:
  type: {{ $service.type | default "ClusterIP" }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: alt-http
```

I didn't deep dive into the code yet, is it something that looks like fixable?

Thanks and keep the nice work with Helm :tada: 

Output of `helm version`:
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}

**Comment by theAkito** [comment]
I experience this error, even when the value is defined, when trying to expand it in a named template.

**Comment by hamzabll5858** [comment]
Any updates on this issue. Getting this issue on pulsar helm charts.

**Comment by bacongobbler** [comment]
This occurs because the `.Values` tree is populated based on the input provided through values.yaml, `--values`, `--set`, etc. It is not populated based on how the templates consume the input. If a value is not set, `.Values` has no knowledge of this sub-tree, and therefore it is evaluated as a `nil` object when rendered through `text/template`.

There are two ways to mitigate this particular issue:

- use a flat tree, where each leaf node is at the first level (i.e. `.Values.serviceType` rather than `.Values.service.type`).
- populate the tree with empty values, so that the `.Values` object can be properly populated (as @michael-todorovic mentions in their workaround)

**Comment by hamzabll5858** [comment]
I was using open source helm chart which was gigantic. I cant fix this right now to have flat tree values.
This issue was not occuring in helm 3.0.2 so I downgraded.

**Comment by kraney** [comment]
Prior to 3.3 this seemed to be addressable by taking advantage of order of operations, e.g.
`if (and .Values.service .Values.service.type)`

**Comment by bacongobbler** [comment]
@kraney I'm not sure that would address the issue, if ever. That syntax has always been invalid `text/template` syntax, and likely never rendered correctly.

**Comment by bacongobbler** [comment]
Adding additional context here...

This particular error message is returned from text/template when the templates are being rendered. While we may not be able to address the root cause of the issue (as this is - according to the Go team - working as intended), improvements to make the error message more useful to the end-user would be helpful.

**Comment by viorelflorian** [comment]
The inability to go beyond 1 level deep in the usage of **dafault** is a big limitation to what you can do and kind of limits the intention of the "default" function.

From the documentation of **default**
> This function allows you to specify a default value inside of the template, in case the value is omitted

There is no mention of depth here.

Fixing this would be a great benefit to chart devs and users.

**Comment by cppcode1** [comment]
hi, I have the same issue 
```
# helm version
Client: &version.Version{SemVer:"v2.16.7"
```
I thought 'if ' operator checks whether a value is defined ,but now I am not sure. it seems to me that 'if value ' checks if the value is empty. I don't know

**Comment by thernstig** [comment]
Wouldn't this be beautifully solved if the parse could handle optional chaining similar to Javascript in latest standard ECMAScript 2020? See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

It would basically look like this:

```
spec:
  type: {{ .Values.service?.type | default "ClusterIP" }}
```

This could be used in other cases, such as:

```
spec:
  {{- if .Values.global?.internalIPFamily }}
  ipFamily: {{ .Values.global.internalIPFamily }}
  {{- end }}
```

**Comment by absoludity** [comment]
Workaround which I'm using (using the example from the previous comment):

```
spec:
  {{- $global := .Values.global | default dict }}
  {{- if $global.internalIPFamily }}
  ipFamily: {{ $global.internalIPFamily }}
  {{- end }}  
```

**Comment by thernstig** [comment]
> Wouldn't this be beautifully solved if the parse could handle optional chaining similar to Javascript in latest standard ECMAScript 2020? See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining
> 
> It would basically look like this:
> 
> ```
> spec:
>   type: {{ .Values.service?.type | default "ClusterIP" }}
> ```
> 
> This could be used in other cases, such as:
> 
> ```
> spec:
>   {{- if .Values.global?.internalIPFamily }}
>   ipFamily: {{ .Values.global.internalIPFamily }}
>   {{- end }}
> ```

I wrote an issue for this: https://github.com/helm/helm/issues/9209

**Comment by viorelflorian** [comment]
this issue has been delegated to https://github.com/golang/go/issues/43608, it seems.

**Comment by saiskee** [comment]
I created a very hacky way to evaluate dictionaries without having to worry about NPE being thrown. Here is the template:

```yaml
{{- define "common.util.safewalk" -}}
{{- $top := first . -}}
{{- $string := (index . 1) -}}
{{- $matches := (splitList "." $string ) -}}
{{- $stop := false -}}
{{- range $index, $elem := $matches -}}
{{- if not $stop -}}
{{- if gt (len $elem) 0 }}
{{- $output := slice $matches 0 (add1 $index) | join "." -}}
{{- $test := (cat "{{ or (empty " $output ") (not (kindIs \"map\"" $output ")) }}") -}}
{{- $testRes := tpl $test $top }}
{{- if and (eq $testRes "true") (ne (add1 $index) (len $matches)) }}
{{- $stop = true -}}
{{ end -}}
{{ end -}}
{{ end -}}
{{ end -}}
{{- if $stop }}
{{- else }}
#{{ tpl (cat "{{ toYaml " $string "}}") $top }}
{{- end }}
{{- end -}}
```

Let's say you have a values yaml:
```
foo:
  bar: some text
```

Then you can use this to get the value of `foo.bar`
```{{ include "common.util.safewalk" (list . ".Values.foo.bar") -}}```

if you were to do 
```
{{ include "common.util.safewalk" (list . ".Values.foo.baz") -}}"
```
it would return empty rather than throwing an error.

**Comment by saiskee** [comment]
Looks like sprig added the new `dig` function, so in  helm v3.5.0, you can now use `dig`.

**Comment by bacongobbler** [comment]
Good catch, @saiskee.

From [the documentation](http://masterminds.github.io/sprig/dicts.html):

> Dig can be very useful in cases where you’d like to avoid guard clauses, especially since Go’s template package’s `and` doesn’t shortcut. For instance `and a.maybeNil a.maybeNil.iNeedThis` will always evaluate `a.maybeNil.iNeedThis`, and panic if `a` lacks a `maybeNil` field.)

Looks like `{{ dig "service" "type" "ClusterIP" .Values }}` should solve OP's original issue.

**Comment by michael-todorovic** [comment]
I just tested and using `dig` works fine :+1: I did

```yaml
enable: {{ dig "nodeAutoScaling" "enable" "false" $daDict }}
```

Thanks for the tip @saiskee

**Comment by mc-zact** [comment]
Got the same issue, but dig is not working for me due to:
```
at <dig "one" "two" "three" "name" "default_name" .Values>: error calling dig: interface conversion: interface {} is chartutil.Values, not map[string]interface {}
```

**Comment by thernstig** [comment]
@bacongobbler @michael-todorovic aren't there some docs that should be updated to show/recommend `dig`?

**Comment by bacongobbler** [comment]
We'd welcome contributions.

**Comment by mc-zact** [comment]
The link mentioned above has info on syntax, and there's a couple samples here, but its seems for some cases this is still not a solution, I believe I'm bumping into https://github.com/helm/helm/issues/9266.

I suppose for such cases I'll have to use conditionals

**Comment by kenaniah** [comment]
Safe nesting can be achieved through the use of parenthesis:

```
spec:
  type: {{ ( .Values.service | default dict ).type | default "ClusterIP" }}
```

**Comment by thernstig** [comment]
> Safe nesting can be achieved through the use of parenthesis:
> 
> ```
> spec:
>   type: {{ ( .Values.service | default dict ).type | default "ClusterIP" }}
> ```

That is quickly becoming ugly with multiple levels of nesting.

**Comment by danielkucera** [comment]
this has worked for me:
```
{{ (((.Values.abc).def).ghi).jkl }}
```

**Comment by thernstig** [comment]
> ```
> {{ (((.Values.abc).def).ghi).jkl }}
> ```

Does that works in all Helm 3.X versions? And is it documented somewhere?

**Comment by sxyandapp** [comment]
> service



> this has worked for me:
> 
> ```
> {{ (((.Values.abc).def).ghi).jkl }}
> ```

虽然有很多括号，但这是目前看来最好的办法了

**Comment by MartinGolding515** [comment]
Thanks sxyandapp, that works for me too.

**Comment by seanmcconkey** [comment]
I've hit this same issue while creating a helper to grab registry & repo, what is bizarre from other examples I've seen in trying to debug this lots of other people should be having the same issue.

```
helm.go:88: [debug] template: Project/templates/_helpers.tpl:94:28: executing "registry.repo.tag" at <.Values.image.registry>: nil pointer evaluating interface {}.image
```

Helm Version 
```version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}
```

The helper.
```
{{/*
This allows us to not have image: .Values.xxxx.ssss/.Values.xxx.xxx:.Values.ssss
in every single template.
*/}}
{{- define "registry.repo.tag" -}}
{{- $registryname := .Values.image.registry -}}
{{- $repoimage := .Values.image.repository -}}
{{- $tag := .Chart.AppVersion | toString -}}
{{- if .Values.image }}
{{- printf "%s/%s:%s" $registryname $repoimage $tag -}}
{{- end -}}
{{- end -}}
```

The values.

```image:
  registry: "index.docker.io"
  repository: "myrepo/myimage"
```

The template referencing the helper.

```
image: {{ template "registry.repo.tag" . }}
```

I get the error if using a flat tree value or using a sub-tree as per my example. I've tried various permutations with and without the `if` statement, which I think is redundant in this case anyway. 

Here's an example that I referenced to try and fix this, so I know my code is correct.

https://github.com/helm/charts/tree/master/stable/mariadb

In a word, help! :)

**Comment by seanmcconkey** [comment]
My issue was I had a range in one of the templates that was causing the issue so I need to change

`image: {{ template "registry.repo.tag" . }}`

to

`image: {{ template "registry.repo.tag" $root }}`

**Comment by LQss11** [comment]
Since I am referring to a key that doesn't exist in `values.yaml`, I needed to check whether that key exists or not first using `hasKey` like this:

{{ if hasKey .Values "chartx"  -}}
{{ if .Values.chartx.enabled  -}}
# YOUR CODE HERE
{{- end -}}
{{- end -}}

**Comment by cm0s** [comment]
> My issue was I had a range in one of the templates that was causing the issue so I need to change
> 
> `image: {{ template "registry.repo.tag" . }}`
> 
> to
> 
> `image: {{ template "registry.repo.tag" $root }}`

Thank you for your insight. I also had a range. Using the $ instead of . in order to use the global scope solved the problem:
metadata:
  name: {{ include "common.fullname" $ }}

**Comment by marko-curlin** [comment]
> this has worked for me:
> 
> ```
> {{ (((.Values.abc).def).ghi).jkl }}
> ```

This worked for me as well, but can someone explain what is happening here?

**Comment by thernstig** [comment]
@marko-curlin https://stackoverflow.com/a/68807258/1853417 explains it:

**Comment by QkiZMR** [comment]
> > Safe nesting can be achieved through the use of parenthesis:
> > ```
> > spec:
> >   type: {{ ( .Values.service | default dict ).type | default "ClusterIP" }}
> > ```
> 
> That is quickly becoming ugly with multiple levels of nesting.

This only works if you have only one type of object. If you have more Services defined on Helm only the last one receives values.

**Comment by Sheikh-Abubaker** [comment]
I'm also experiencing this error when I upgraded the loki app dependency version to use loki v2.9.3 in `requirements.yaml` of lack-stack.
```
Error: template: loki-stack/templates/tests/loki-test-pod.yaml:24:24: executing "loki-stack/templates/tests/loki-test-pod.yaml" at <.Values.loki.service.port>: nil pointer evaluating interface {}.port
```
You can see my loki-stack values.yaml below:

```
test_pod:
  enabled: true
  image: bats/bats:1.8.2
  pullPolicy: IfNotPresent

loki:
  enabled: true
  isDefault: true
  url: http://{{(include "loki.serviceName" .)}}:{{ .Values.loki.service.port }}
  readinessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
  livenessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
  datasource:
    jsonData: "{}"
    uid: ""
```

I'm not being able to understand how come loki-stack was functioning all this time in production ? why didn't the lint test failed before but it is failing for my PR when I upragded the dependeny version in `requirements.yaml` of loki-stack

**Comment by BigCat3997** [comment]
> this has worked for me:
> 
> ```
> {{ (((.Values.abc).def).ghi).jkl }}
> ```

It worked perfectly but can I ask why ?

**Comment by thernstig** [comment]
@BigCat3997 https://github.com/helm/helm/issues/8026#issuecomment-1437016015

https://pkg.go.dev/text/template#hdr-Actions

**Comment by vladimirf7** [comment]
> > this has worked for me:
> > ```
> > {{ (((.Values.abc).def).ghi).jkl }}
> > ```
> 
> This worked for me as well, but can someone explain what is happening here?

Unfortunately this does not help if a property name is stored in a variable, when you have to use the `index` function. So the original issue remains. For example:
```
{{ $propName := "def" }}
{{index .Values "abc" $propName "ghi" }}
```
