### ISSUE TITLE
Unable to use merged kubeconfig

### ISSUE THREAD

**Issue by sadovnikov** [helm/helm#8027]
This issue is similar to #3378, but for Helm 3.2.0 

Output of `helm version`:
`version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}`

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2019-12-11T12:34:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

We deal with many clusters and therefore use merged kubeconfig (below is the shortened version of $KUBECONFIG)

```
vs86957@devbox:~> echo $KUBECONFIG
/home/vs86957/.kube/config.cluster-merge:/home/vs86957/.kube/config.k8slab:/home/vs86957/.kube/config.beagle
```

Helm 3 fails to connect to the cluster, unless `--kubeconfig` is passed explicitly

```
vs86957@devbox:~> helm version
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}

vs86957@devbox:~> helm list -n reference-apps
Error: Kubernetes cluster unreachable: Get https://k8slabkube.xxxxx.xxxxx.xxxxx:443/version?timeout=32s: failed to refresh token: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2019-09-04T11:36:10.3964671Z and was inactive for 90.00:00:00...................."}

vs86957@devbox:~> helm list -n reference-apps --kubeconfig ~/.kube/config.k8slab
NAME                                            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
cbdp-k8s-sample-feature-helm-3-preemptible      reference-apps  1               2020-04-29 06:19:11.763978384 +0000 UTC failed          cbdp-k8s-sample-0.2.2
js-project-feature-helm-3-preemptible           reference-apps  1               2020-04-28 15:51:47.246366665 +0000 UTC deployed        js-project-0.0.1
```

With the same setup Helm 2 and Tiller plugin work just fine, although Helm 2 does not see releases installed by Helm 3.

```
vs86957@devbox:~> helm version
Client: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
Error: could not find tiller

vs86957@devbox:~> helm tiller run reference-apps -- helm ls --all
Installed Helm version v2.15.1
Installed Tiller version v2.15.1
Helm and Tiller are the same version!
Starting Tiller...
Tiller namespace: reference-apps
Running: helm ls --all

Stopping Tiller...
```

**Comment by vladfr** [comment]
Hi, tried this with helm 3.2.3 and 3.1.3 and it works. I only have two files in my KUBECONFIG. I think you may have an issue with `current-context`. Have you checked that you are indeed connecting to the correct cluster via `kubectl config current-context`?

**Comment by sadovnikov** [comment]
Hi, yes, the cluster is the correct one. And there is no problem with listing helm releases without `--kubeconfig` if my token is fresh. However, if it requires refreshing, I need to either specify `--kubeconfig` in `helm` command or to use a `kubectl` command to refresh the token. 
I'll repeat tests tomorrow to confirm.

**Comment by bridgetkromhout** [comment]
> And there is no problem with listing helm releases without --kubeconfig if my token is fresh. However, if it requires refreshing, I need to either specify --kubeconfig in helm command or to use a kubectl command to refresh the token.

Based on this statement, it seems like this is a problem external to helm: it has to do with having a valid token. It sounds like you have a resolution (ensure token is valid before invoking helm commands). As this seems to be answered, I'm resolving this issue now. Please let us know if this issue continues.
