### ISSUE TITLE
The --insecure-skip-tls-verify flag does not work with --cert-file and --key-file flags

### ISSUE THREAD

**Issue by alexmt** [helm/helm#8031]
The `--insecure-skip-tls-verify` flag of `helm repo add` command supposed to disable TLS verification. However, the flag does not work if `--cert-file` and `--key-file` flags are specified.

The `--cert-file` and `--key-file` are used to verify HTTPS client. So it makes sense to use these flags together with `--insecure-skip-tls-verify` if server requires client verification but client does not need to verify server.

## To reproduce

* Configure Helm repo using HTTPS server which requires client verification and uses self-signed certificate
* Try to add repo using the following command:

```
helm repo add --insecure-skip-tls-verify \
  --cert-file <path> \
  --key-file <path> \
  testrepo <https://url>
```

Command fails with the following error:
```
x509: certificate signed by unknown authority
```

Output of `helm version`:
```
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

**Comment by bacongobbler** [comment]
I believe @technosophos identified this issue earlier as well. Your assumption is correct here. Do you feel like working on a patch to fix this for the next release?

**Comment by bacongobbler** [comment]
For reference, here is where it's set up. https://github.com/helm/helm/blob/c0edc586c55d57bc4a288a17c628ca943e1d5ef1/pkg/getter/httpgetter.go#L116-L124

**Comment by alexmt** [comment]
Thank you for response @bacongobbler! Sure, I can work on fix this weekend. 

What do you think about introducing the `--insecure-skip-tls-verify` option to `helm fetch`/`helm pull` command ? It has the same set of flags as `helm repo add` except `--insecure-skip-tls-verify`.

**Comment by bacongobbler** [comment]
I see no problem with that.

**Comment by xvzf** [comment]
@alexmt Working on it, just couldn't find time. https://github.com/helm/helm/issues/7875

**Comment by alexmt** [comment]
sorry, as usual, something got me distracted. still planning to work on it.

**Comment by alexmt** [comment]
The bug is fixed by https://github.com/helm/helm/commit/93b0eee0dff2849081f16b47f4693fd8b25115bc#diff-fde6e3b05a1f149234e259f7821472c5 .
