### ISSUE TITLE
helm lint: [WARNING] templates/: directory not found

### ISSUE THREAD

**Issue by SimonAlling** [helm/helm#8033]
Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

Some charts don't need a `templates` directory; we have real-world examples in our project. Nevertheless, these cause `helm lint` to display a warning in our CI pipeline. One might think the solution is simple enough: just add a `templates` directory. But empty directories can't be added in Git, so one would have to employ some kind of hacky ad-hoc workaround with an empty `.gitignore` or something. Not very practical.

I don't know what solution to suggest, but this is a bit of an issue for us, so I'll post it here and see where the discussion takes us.

**Comment by hickeyma** [comment]
@SimonAlling If it is a warning only then is that ok? I would read the logic as:

Warning: There is no template directory which means possibly no k8s resource artefacts to deploy
Question to user: Are you aware of this and is that ok?

**Comment by SimonAlling** [comment]
> @SimonAlling If it is a warning only then is that ok? I would read the logic as:
> 
> Warning: There is no template directory which means possibly no k8s resource artefacts to deploy
> Question to user: Are you aware of this and is that ok?

When running `helm lint` interactively on the command line, absolutely. But in the pipeline, it's annoying to get warnings one can't even do anything about, and over time it also makes one less inclined to consider warnings at all.

It seems a little bit strange to me that the absence of `templates` always issues a warning when we have charts where it doesn't seem necessary (or even reasonable). Since I haven't found any overview of errors and warnings that `helm lint` could issue (like [Hadolint's list](https://github.com/hadolint/hadolint#rules)), it's somewhat hard for me to assess the importance of warnings in general, but I do think we want them, and we'd rather not parse them to filter out specific ones.

How about bumping the severity down to `INFO`? There's already for example `[INFO] Chart.yaml: icon is recommended`, which seems to be of about the same severity as absence of `templates`.

**Comment by mattfarina** [comment]
Warnings provide information but still have a 0 exit code. If `helm lint --strict` is used the warnings will cause a non-0 exit code. Warnings have wiggle room one can use in CI to break out of it.

I was recently doing a demo that pulled in sub-charts to show something. The parent chart did not need any templates because of my funny case. What I ended up doing was creating a `templates` directory and adding an empty `.gitkeep` file to it. This meant the directory was empty and checked into Git. Using a `.gitkeep` is a pretty common pattern for keeping an emptry directory in Git. This fixed my linter issue.

**Comment by technosophos** [comment]
The code marking a this as a warning is four years old. Is there a compelling reason to change the expectations around this?

As I see it, if the `templates` directory is optional, it does seem weird to issue a warning for its absence. On the reverse side, I know that part of the motivation for this was people naming their directories wrong (like `template`), and then being surprised when their templates were not rendered.

Also, we haven't discussed whether linter rule changes like this qualify as breaking changes. Escalating a "warning" to an "error" would have to be done with more care. But is demoting a rule from "warning" to "info" something we think of as breaking?

**Comment by hickeyma** [comment]
@SimonAlling I agree with @technosophos about the compelling reason to remove the warning. I would totally agree to remove it, if it was an error. As a warning, it maybe because originally Helm expected all charts to contain templates.

**Comment by SimonAlling** [comment]
@hickeyma What do you think about demoting the severity to `INFO`? It would still show up on the command-line, but not in a CI setup where `helm lint` warnings are shown as CI warnings.

**Comment by lindhe** [comment]
Interesting question. I've also thought about posting an issue about this. To my mind, either `templates/` should be considered required and cause a lint error if missing, or it's fine to not have the `templates/` directory and then it should never cause any lint error or warning.

So I guess it's currently neither required nor optional. I think that's what bothers me. When something is recommended but not required, why recommend it?

**Comment by hickeyma** [comment]
@SimonAlling @lindhe I think you have very good points on not needing the warning from your perspectives. Looking at this again I then tried the scenario as follows:

```console
$ helm create issue-8033
Creating issue-8033 

$ rm -rf issue-8033/templates/

$ rm issue-8033/values.yaml

$ ls -al issue-8033/
total 20
drwxr-xr-x  3 root root 4096 May  6 09:01 .
drwxr-xr-x 46 root root 4096 May  6 09:01 ..
-rw-r--r--  1 root root  349 May  6 09:01 .helmignore
-rw-r--r--  1 root root 1101 May  6 09:01 Chart.yaml
drwxr-xr-x  2 root root 4096 May  6 09:01 charts

$ helm install issue-8033 issue-8033/
Error: no objects visited

$  helm list
NAME        	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART            	APP VERSION
issue-8033  	default  	1       	2020-05-06 09:02:46.87316188 +0000 UTC 	failed  	issue-8033-0.1.0 	1.16.0 
```

Maybe we need instead some login in Helm which checks for an application chart with nothing to deploy?

**Comment by lindhe** [comment]
> Maybe we need instead some login in Helm which checks for an application chart with nothing to deploy?

That sounds like it would make a lot of sense. My most common use-case for not having `templates/` is when I put together an umbrella chart (with dependencies) that doesn't have any template files of its own. And it sounds like that would be correctly handled by your suggestion! And not creating a release without anything to deploy sounds like an error case...

All in all, I like it!

**Comment by hickeyma** [comment]
> My most common use-case for not having templates/ is when I put together an umbrella chart (with dependencies) that doesn't have any template files of its own. 

Yes, meant to add that to https://github.com/helm/helm/issues/8033#issuecomment-624534020 to show when it is ok to have no `template` directory

**Comment by dntosas** [comment]
we got the same question ^^ if this validation rule should trigger when it comes for charts with just dependencies and values definitions.

any news on this people? we are thinking of opening a PR to address this but we wanted first to understand if we are missing something as an essential behavior on mentioned scenarios

**Comment by lindhe** [comment]
@hickeyma We settled on your suggestion, right?

**Comment by hickeyma** [comment]
@lindhe @dntosas This should be fixed by changes in PR #7970 which will be in 3.4.0 release. You can test against main branch to see if it works. It is also similar to issue #8418.

I am therefore going to close this issue and we can re-open if need be.

**Comment by lindhe** [comment]
Strange. I tried it now with `v3.4.0-rc.1` and the warning is still there. What am I missing?


## Setup

**Chart.yaml:**
```yaml
apiVersion: v2
name: a
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.16.0
icon: https://artifacthub.io/image/681732c0-8168-4b95-8600-894449c02b79@1x.png
dependencies:
- name: nginx
  version: 7.1.3
  repository: "https://charts.bitnami.com/bitnami"
```

**Commands:**
```console
$ h version
version.BuildInfo{Version:"v3.4.0-rc.1", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"}

$ h dep update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading nginx from repo https://charts.bitnami.com/bitnami
Deleting outdated charts

$ h lint .
==> Linting .
[WARNING] templates/: directory not found

1 chart(s) linted, 0 chart(s) failed

$ tree
.
├── Chart.lock
├── charts
│   └── nginx-7.1.3.tgz
├── Chart.yaml
└── values.yaml

1 directory, 4 files
```

**Comment by hickeyma** [comment]
Thanks for raising again @lindhe. I mis-read issue #8418 and even though it has similarities to this, they are different issues. I am going to re-open this issue and raise it at the dev weekly meeting today on how best to proceed.

**Comment by lindhe** [comment]
Hello bot. Please keep it open, thank you.

**Comment by lindhe** [comment]
Keeping this open. If I get time, I'd love to look into it. But no promises. If anyone gets to do it before me, awesome! :D

**Comment by solarist** [comment]
Still a nice-to-have fix.

**Comment by solarist** [comment]
bot please still keep it open, thank you!

**Comment by Startouf** [comment]
Any updates on this ?

**Comment by lindhe** [comment]
Not from my side. I've been swamped with other things to do, and have had no time neither during working hours nor in my free time to look into it all fall. :/ Wish I had, though, because I think this is very fixable.

**Comment by joejulian** [comment]
So if I'm reading through all the comments correctly, the expected outcome of this issue is:

If there are no `dependencies` in Chart.yaml and no `requirements.yaml` is configured, only then should a missing `templates` directory be a warning.

Right?

**Comment by lindhe** [comment]
I think there could be chart dependencies without the need for a `templates/` directory. If I only use the chart as an umbrella chart, then I think it should only create a `charts/` directory (where the dependencies are stored), not a `templates/` directory, unless I want to have something additional besides the dependencies...

Is `requirements.yaml` still a thing, or was that removed when the `dependencies` field in `Chart.yaml` was introduced?

**Comment by joejulian** [comment]
`requirements.yaml` can still be a thing. iirc, it goes away in helm 4

**Comment by bacongobbler** [comment]
> `requirements.yaml` can still be a thing. iirc

Yep: https://github.com/helm/helm/blob/65d8e72504652e624948f74acbba71c51ac2e342/pkg/chart/loader/load.go#L113-L139

**Comment by lindhe** [comment]
Alright, thanks for filling me in on `requirements.yaml`! :)

I do not see a single scenario where an error or warning for missing `templates/` would be helpful.

When are `templates/` required? AFAICT, it is a completely optional (albeit exceedingly common) directory.

* We may have dependencies without rendering our own custom templates.
* We may have a values.yaml to provide configuration only to the dependency charts, so that's not an indicator of needing `templates/` either.
* We may have a schema file without `templates/`
* We may have a README and other misc files
* ...

_Perhaps_ it would be nice with a warning for a _completely empty chart_ (no templates to render from, neither from dependencies nor from `templates/`). But I think that error should say something else.

**Comment by joejulian** [comment]
@lindhe Are there conditions under which an empty chart is desired where the default values produce no output, but enabling certain values will create output?

**Comment by lindhe** [comment]
It depends on what you mean with an empty chart. If there are no dependencies _and_ `templates/` is empty, surely Helm has nothing to render (regardless of what Values are set).

**Comment by solarist** [comment]
Bot, please.

**Comment by jmhbnz** [comment]
Hey Team - I've had a go at resolving this issue via #11586.  There are some test failures coming back from CircleCI due to golden test data comparisons and just removing the warning from the golden test data doesn't resolve it as further differences are emerging.

Before I go to much further I'm definitely keen for any gentle guidance on the preferred way of addressing those  🙏🏻
