### ISSUE TITLE
helm3 upgrade --install fail if there is a failed release

### ISSUE THREAD

**Issue by Shobhit29** [helm/helm#8037]
Output of `helm version`: `version.BuildInfo{Version:"v3.2.0"`

Output of `kubectl version`: `Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.12", GitCommit:"a8b52209ee172232b6db7a6e0ce2adc77458829f", GitTreeState:"clean", BuildDate:"2019-10-15T12:04:30Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Kubernetes 1.13 on-premise

I tried to upgrade the release, and due to some reason it unable to upgrade.  Since I am using 
--atomic flag it rolled back to the previous version. 

Once I fix the issue, I tried to upgrade again and it showing me that `UPGRADE FAILED: "master-ci" has no deployed releases`  but release exist in place.

`helm3 --namespace dcs-dev history master-ci
REVISION        UPDATED                         STATUS          CHART           APP VERSION     DESCRIPTION                                                                                                        
521             Thu Apr 30 21:07:28 2020        superseded      dcs-0.0.1                       Upgrade "master-ci" failed: cannot patch "translation-master-ci" with kind Service: Service "translation-master-ci" is invalid: spec.ports[1].name: Duplicate value: "http"
522             Thu Apr 30 21:07:31 2020        failed          dcs-0.0.1                       Rollback "master-ci" failed: no Service with the name "imaging-master-ci" found`

From the release notes it seems that this issue has been fixed in 3.2.0, but the bug is still there

**Comment by liuming-dev** [comment]
```helm upgrade -h```, find the `--install` usage

```
  -i, --install                      if a release by this name doesn't already exist, run an install
```

From helm 3.2.1, it will support upgrade from a failed release.

see #7653

**Comment by bacongobbler** [comment]
Fixed on master. As @liuming-dev mentioned, it will be made available in the next release. Feel free to test it out with the helm canary releases. Links are in the documentation.
