### ISSUE TITLE
helm3 repo add needs permissions to .config

### ISSUE THREAD

**Issue by 7AC** [helm/helm#8038]
Looks like `helm3 repo add` blindly tries to `mkdir ~/.config/helm`, which doesn't work if the directory is mounted in a container (and `.config` is not). It would be nice if it could check for existence and permissions before attempting to do so.

**Comment by yonatankahana** [comment]
I'd love to take this on myself as a first issue.
Can you provide more information about the permissions that cause this?
When I try to reproduce what you described I get an error: "Error: mkdir /home/xxx/.config/helm: permission denied". 
Is that also what you get? What is the desired behavior @bacongobbler?

**Comment by liuming-dev** [comment]
cc #7990, How is this going?

**Comment by 7AC** [comment]
@yonatankahana yes that's exactly the error. I do have `/home/xxx/.config/helm` and write access to it, which presumably is all helm needs. I don't have write access to `/home/xxx/.config` so `mkdir` fails, though the dir is there and accessible.

**Comment by yonatankahana** [comment]
@7AC 
I created `~/.config/` folder without write permissions for my user, then `~/.config/helm/` folder with full read-write permissions for my user -- But I get no error, everything works.

I will need some more information, would be happy if you could provide me with the output for the following commands:
```bash
$ helm version
$ ll ~/.config/helm/
```

This will give me more information about the permissions in the `.config` and `helm` folders and your helm version to test with.

**Comment by 7AC** [comment]
You're right I can't reproduce with docker and helm alone, our config also involves Jenkins with several nested images I need to debug on our end more. Closing for the time being, sorry for the noise.

**Comment by rishi7c** [comment]
Getting the same issue with Helm 3 repo add when running on a container.

Helm needs to write `/.config/helm/repositories.yaml`
but as the container is not run as root and does not have write access fails with 

`Error: mkdir /.config: permission denied`

 `$HELM_PATH_CONFIG` is not set, so as per `lazypath_unix.go`  it tries to create config in 
`$HOME/.config` which evaluates to` /.config`.

If it does not have write access to that folder, it fails. 

However this works if run as root user, in which case it is able to create that dir and file.

**Comment by yonatankahana** [comment]
can you provide me the output of:
```bash
$ ll /.config/helm/
```

**Comment by yonatankahana** [comment]
> However this works if run as root user, in which case it is able to create that dir and file.

since Helm v3, Helm follows the XDG Base Directory Specification, which defines:
```
$XDG_DATA_HOME defines the base directory relative to which user specific data files should be stored. If $XDG_DATA_HOME is either not set or empty, a default equal to $HOME/.local/share should be used.

$XDG_CONFIG_HOME defines the base directory relative to which user specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used. 
```
if not specified otherwise - helm will setup the config files relative to $HOME directory. since $HOME is empty, the `/` folder will be used. the XDG specification does not define what to do when $HOME is unset, probably because by the single unix specification, $HOME should be defined. i think the problem you are experiencing is the desired result in this situation.

just set the environment variables and point helm to a valid directory which it can store all it's files. 
take a look at the the defaults of helm, plus the list of the environment variables you should set - all here: https://helm.sh/docs/helm/helm/

**Comment by rishi7c** [comment]
The Helm documentation states :

> set an alternative location for storing Helm configuration

 which does not ask for it to be explicitly set.

Would it not be better if the error message asks to set variable(s) if defaulted path `\` is not writable. This applies to all 3 XDG env variables.
