### ISSUE TITLE
Question: Best practice, packages or monolith?

### ISSUE THREAD

**Issue by atrauzzi** [helm/helm#8050]
I spoke with some people recently who are using a boolean flag in a monolith-like `Chart.yaml` to bake in some switches to control what their deployments do. Particularly around when targeting different infrastructure. Say, for an oversimplified example: Deciding whether to deploy postgres or not because the targeted infrastructure offers managed postgres.

Assuming let's say **> 2** destinations for infrastructure, to me, this seems like a missed opportunity to split the chart into packages of core service definitions, and then fringe orchestration charts.  The orchestration charts _authoritatively_ reference the separately source-controlled and versioned core chart and then mix in their own specifics from other sources in a similar way.

(Basically a conventional package setup!)

With a scenario like this in mind, I'm trying to understand what the current state of the art is in helm when it comes to repositories and packages vs. monolithic charts. The challenge is that I want to separate state of the art from defacto "haven't thought much about it".

> note: My apologies for asking a support-style question here.  I attempted to join the k8s slack to ask there, but it appears to not be working? I have also been trying to dig online, but I feel like this is guidance that I don't feel is well documented or tracked via anecdotes anywhere?

**Comment by bacongobbler** [comment]
In general, If you want to deploy all of the resources as one product, use an umbrella chart. If you want to manage each product separately, deploy them as separate entities and loosely couple them through services, endpoints or other means.

This was the model [Deis Workflow](https://github.com/deis/charts) used while it was an active project: we did both. Each project was released as its own chart (like `deis/controller`, `deis/postgres`, `deis/monitor` etc), and the product that amalgamated them all into one was the umbrella chart: `deis/workflow`. This gave our clients the flexibility to either use the product as a package deal (`deis/workflow`) or swap out components entirely, replacing them with their own products (many people swapped out `deis/postgres` with Amazon RDS or `deis/monitor` with their own monitoring stack, for example).

> note: My apologies for asking a support-style question here. I attempted to join the k8s slack to ask there, but it appears to not be working?

You can register for the Kubernetes Slack channel at https://slack.k8s.io/.

Hope this helps!

**Comment by atrauzzi** [comment]
@bacongobbler - Thanks!  Just one quick clarification... So you're saying the umbrella chart would use packages/registries?  Both internal and from community sources?

**Comment by bacongobbler** [comment]
Yes, but please feel free to have a look at the project I linked above to check that. The documentation is quite extensive and it describes the process as well as the architecture in great detail.

**Comment by atrauzzi** [comment]
@bacongobbler - For sure, I had a look through them and I noticed that in the [`deis-workflow` charts](https://github.com/deis/charts/tree/master/workflow-v2.9.0), I couldn't see any kind of [dependency references](https://helm.sh/docs/chart_best_practices/dependencies/) in `Chart.yaml`.  Is this correct?

My overall goal is to avoid repetition of templates by storing them in separate repositories rather than everything in a single one and then duplicating charts per "umbrella".

**Comment by bacongobbler** [comment]
Oh! I apologize. Those were charts built with helm-classic (Helm 1). Big giveaway: https://github.com/deis/charts/blob/master/workflow-v2.9.0/tpl/generate_params.toml#L1

You probably want https://github.com/deis/workflow/blob/master/charts/workflow/requirements.yaml, which is at deis/workflow.

**Comment by atrauzzi** [comment]
Ahh, much better.  Thought I was losing my mind! :wink:

**Comment by bacongobbler** [comment]
Closing as answered. Let's keep these discussions going on either in slack or in the helm-users mailing list. Thanks!
