### ISSUE TITLE
strange behaviour with $.Release inside a range loop.

### ISSUE THREAD

**Issue by dlfoo** [helm/helm#8052]
I'm creating a hash of the below ConfigMap (snippet 2) in my deployment yaml (snippet 4), and my deployment yaml is encapsulated in a range loop. IIUC I should use $. instead of . to access Values or Release in the ConfigMap

Interestingly $.Release produced a map (snippet 1), but when trying to access the map values e.g: $.Release.Namespace it produced a nil pointer error. So the map is there I just can't use the values. However I found a workaround to declare at the start shown in (snippet 3)

Is this intended ?

Note: I'm fully aware that the sha256sum is of the unrendered ConfigMap which is ok with me.

1. """apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfig
  namespace: map[IsInstall:true IsUpgrade:false Name:RELEASE-NAME Namespace:default Revision:1 Service:Helm]"

2. """
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfig
  namespace: {{ $.Release.Namespace }}
"""

3. """
{{ $r := $.Release }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfig
  namespace: {{ $r.Namespace }}
"""

4."""
{{- range $deployment := .Values.deployments }}
apiVersion: apps/v1
kind: Deployment
</snip>
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
{{- end }}
"""

Output of `helm version`: version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
N/A

**Comment by bacongobbler** [comment]
Hi @dlfoo. I'm not sure what to make of the output provided here. Can you please provide a sample chart or a set of steps we can use to reproduce the issue you are experiencing? Thanks.

**Comment by dlfoo** [comment]
https://gist.github.com/dlfoo/be9ed0c435d2a0066204720d5ad2bd7b
The following error is produced, when accessing the map values in bla-configmap.yaml

`Error: template: issue8052/templates/mytemplate.yaml:2:8: executing "issue8052/templates/mytemplate.yaml" at <include (printf "%s/%s-configmap.yaml" $.Template.BasePath $job.config) .>: error calling include: template: issue8052/templates/bla-configmap.yaml:5:17: executing "issue8052/templates/bla-configmap.yaml" at <$.Release.Namespace>: nil pointer evaluating interface {}.Namespace`

Removing .Namespace and .interval in bla-configmap.yaml I get the following:

`---
# Source: issue8052/templates/bla-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfig
  namespace: map[IsInstall:true IsUpgrade:false Name:RELEASE-NAME Namespace:default Revision:1 Service:Helm]
data:
  config.yaml: |-
      interval: map[interval:1s jobs:map[myjob:map[config:bla interval:1s name:myjob]]]
---
# Source: issue8052/templates/mytemplate.yaml
sum: 5a5fbce56ac5c714e005ad7021518fce3c4b7fd6591b158622ebccb37a12ea2f`
