### ISSUE TITLE
helm test / daemonset / test not working

### ISSUE THREAD

**Issue by AndyAstrand** [helm/helm#8058]
Seems easy to reproduce working from the standard helm template example:

```
#> helm create example
Creating example
#> cd example
#> helm install --namespace test example -f values.yaml .
NAME: example
LAST DEPLOYED: Tue May  5 15:24:28 2020
NAMESPACE: test
STATUS: deployed
REVISION: 1
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace test -l "app.kubernetes.io/name=example,app.kubernetes.io/instance=example" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace test port-forward $POD_NAME 8080:80
#> kubectl get pods --namespace test
NAME                       READY   STATUS    RESTARTS   AGE
example-5474f549d5-szhj8   1/1     Running   0          2m6s
#> helm test example --namespace test --logs
Pod example-test-connection pending
Pod example-test-connection pending
Pod example-test-connection pending
Pod example-test-connection succeeded
NAME: example
LAST DEPLOYED: Tue May  5 15:24:28 2020
NAMESPACE: test
STATUS: deployed
REVISION: 1
TEST SUITE:     example-test-connection
Last Started:   Tue May  5 15:26:55 2020
Last Completed: Tue May  5 15:27:16 2020
Phase:          Succeeded
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace test -l "app.kubernetes.io/name=example,app.kubernetes.io/instance=example" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace test port-forward $POD_NAME 8080:80

POD LOGS: example-test-connection
Connecting to example:80 (10.98.190.118:80)
saving to 'index.html'
index.html           100% |********************************|   612  0:00:00 ETA
'index.html' saved

```
The above commands work correctly, I can see a single pod and when the test runs the displayed logs show the test successfully downloading index.html from the nginx server installed.

So I then delete the deployment and clear down the orphaned test container.

Now edit example/templates/deployment.yaml and change the kind from "Deployment" to "DaemonSet" and comment out the replicas line.

```
#> helm install --namespace test example -f values.yaml .
NAME: example
LAST DEPLOYED: Tue May  5 15:29:43 2020
NAMESPACE: test
STATUS: deployed
REVISION: 1
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace test -l "app.kubernetes.io/name=example,app.kubernetes.io/instance=example" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace test port-forward $POD_NAME 8080:80

#> kubectl get pods --namespace test
NAME            READY   STATUS    RESTARTS   AGE
example-7d2zz   1/1     Running   0          22s
example-brdxs   1/1     Running   0          22s
example-dvx49   1/1     Running   0          22s
example-fvlwg   1/1     Running   0          22s
example-swq7l   1/1     Running   0          22s
example-w7wpg   1/1     Running   0          22s

#> helm test example --namespace test --logs
Pod example-test-connection pending
Pod example-test-connection pending
Pod example-test-connection pending
Pod example-test-connection pending
NAME: example
LAST DEPLOYED: Tue May  5 15:29:43 2020
NAMESPACE: test
STATUS: deployed
REVISION: 1
TEST SUITE:     example-test-connection
Last Started:   Tue May  5 15:31:04 2020
Last Completed: Tue May  5 15:31:04 2020
Phase:          Succeeded
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace test -l "app.kubernetes.io/name=example,app.kubernetes.io/instance=example" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace test port-forward $POD_NAME 8080:80

Error: unable to get pod logs for example-test-connection: pods "example-test-connection" not found

```
The install is fine, I have pods running on the 6 nodes in my cluster. But the test is broken.

I would expect the test to work, it should do it from a random one of the nodes running the DaemonSet but I feel it should work. It is very important that it works for my use case where we are creating a chart/test to verify the capabilities of a cluster pre-installation. 

But we see very different behaviour. The 4 pod pending lines are output almost simultaneously, the test runs far, far quicker. No hanging test pod is left at the end. No logs are available. There is no indication that the test pod was successfully created.

Furthermore if I change the test to access the nginx server from a different port which should force the test to fail, it still "succeeds".

It appears that 'helm test' is currently bugged when testing a 'DaemonSet' but Googling has thrown up little to no information.  

Output of `helm version`:
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-11T12:32:32Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**Comment by bacongobbler** [comment]
`test-connection` is a very simple test. It checks to see if the service created by the chart responds with a 200-399 status code.

Source: https://github.com/helm/helm/blob/54e5088a500bde62a84eeba89d39abd6d7f28daa/pkg/chartutil/create.go#L454-L469

The issue you are experiencing is because the DaemonSet is matching for specific labels on the node. The test pod uses the same labels as the deployment, and therefore is never scheduled because the DaemonSet prevents it from scheduling. This isn't an issue with Deployments because it doesn't block the pod from scheduling; it just notes a temporary burst.

https://github.com/helm/helm/blob/54e5088a500bde62a84eeba89d39abd6d7f28daa/pkg/chartutil/create.go#L458-459

If you remove those two lines, everything works for a DaemonSet.


```
><> helm test test-8058 --logs
Pod test-8058-test-connection pending
Pod test-8058-test-connection pending
Pod test-8058-test-connection pending
Pod test-8058-test-connection succeeded
NAME: test-8058
LAST DEPLOYED: Tue May  5 09:04:58 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE:     test-8058-test-connection
Last Started:   Tue May  5 09:05:06 2020
Last Completed: Tue May  5 09:05:10 2020
Phase:          Succeeded
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=test-8058,app.kubernetes.io/instance=test-8058" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace default port-forward $POD_NAME 8080:80

POD LOGS: test-8058-test-connection
Connecting to test-8058:80 (10.106.208.173:80)
saving to 'index.html'
index.html           100% |********************************|   612  0:00:00 ETA
'index.html' saved
```

Closing as answered. The output of `helm create` is only tested to work for itself and is meant to be used as an example. If you modify the templates, then changes (like the one mentioned here) is up to the chart maintainer to change.

Hope this helps.

**Comment by AndyAstrand** [comment]
Thank's for that. That internal behaviour of the DaemonSet was unknown to me. Should the incorrect test still have returned this though:

```
NAME: example
LAST DEPLOYED: Tue May  5 15:29:43 2020
NAMESPACE: test
STATUS: deployed
REVISION: 1
TEST SUITE:     example-test-connection
Last Started:   Tue May  5 15:31:04 2020
Last Completed: Tue May  5 15:31:04 2020
Phase:          Succeeded
```

That seems to indicate success when it should be failure?
