### ISSUE TITLE
OCI registry cache becomes corrupted

### ISSUE THREAD

**Issue by jdolitsky** [helm/helm#8059]
Related to conversation in https://github.com/helm/helm/issues/7981

In some scenarios (which are yet to be determined), users get the following error:
```
> helm chart pull private-reg.comp.name/project/mychart:0.1.0
Error: blob sha256:355a6550ed5ec3bca56caac650ef0229f274ea7f4b47e29425b39d0f8cfe254e expected at /home/ant/.cache/helm/registry/cache/blobs/sha256/355a6550ed5ec3bca56caac650ef0229f274ea7f4b47e29425b39d0f8cfe254e: not found
```

Currently the only fix is to wipe the cache:
```
rm -rf /home/ant/.cache/helm/registry/cache
```

Need to figure out what scenario causes this, and perhaps Helm can check for this and auto-purge problematic blobs from the cache.

**Comment by jdolitsky** [comment]
This will be closed if we remove the cache, see https://github.com/helm/community/pull/136

**Comment by ErikUmhoe** [comment]
When attempting to pull from an azure container registry, I am still encountering this error.

`helm.exe : Error: blob sha256:90659bf80b44ce6be8234e6ff90a1ac34acbeb826903b02cfa0da11c82cbc042 expected at 
C:\Users\ERIK~1.UMH\AppData\Local\Temp\helm\registry\cache\blobs\sha256\90659bf80b44ce6be8234e6ff90a1ac34acbeb826903b02cfa0da11c82cbc042: not found
At line:26 char:1
+ & helm chart pull myazurecontaineregistry.azurecr.io/hello-world:latest
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error: blob sha...c042: not found:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 `

Oddly enough, that directory  in the error does not even exist.

**Comment by hxalid** [comment]
This issue happens on "Ubuntu 20.10" and removing the cache does not help. 

Helm version v3.5.4,  GitCommit: "1b5edb69df3d3a08df77c9902dc17af864ff05d1", GoVersion: "go1.15.11"

The Helm command below was run in a Docker container that runs with the above mentioned OS.

The exact same command runs with no issue on MacOS 19.6.0 with the exact same Helm version built for Darwin.

```
helm chart pull <my-image> --debug

Error: blob sha256:3861bd20dfcf48438e80e544fb3cf43c427fa4acbc2e5bb6827bd6f7dc68a692 expected at /home/argocd/.cache/helm/registry/cache/blobs/sha256/3861bd20dfcf48438e80e544fb3cf43c427fa4acbc2e5bb6827bd6f7dc68a692: not found
helm.go:81: [debug] not found
github.com/containerd/containerd/errdefs.init
                /go/pkg/mod/github.com/containerd/containerd@v1.4.3/errdefs/errors.go:45
runtime.doInit
                /usr/local/go/src/runtime/proc.go:5652
runtime.doInit
                /usr/local/go/src/runtime/proc.go:5647
runtime.doInit
                /usr/local/go/src/runtime/proc.go:5647
runtime.doInit
                /usr/local/go/src/runtime/proc.go:5647
runtime.doInit
                /usr/local/go/src/runtime/proc.go:5647
runtime.doInit
                /usr/local/go/src/runtime/proc.go:5647
runtime.doInit
                /usr/local/go/src/runtime/proc.go:5647
runtime.main
                /usr/local/go/src/runtime/proc.go:191
runtime.goexit
                /usr/local/go/src/runtime/asm_amd64.s:1374
blob sha256:3861bd20dfcf48438e80e544fb3cf43c427fa4acbc2e5bb6827bd6f7dc68a692 expected at /home/argocd/.cache/helm/registry/cache/blobs/sha256/3861bd20dfcf48438e80e544fb3cf43c427fa4acbc2e5bb6827bd6f7dc68a692
github.com/containerd/containerd/content/local.(*store).ReaderAt
                /go/pkg/mod/github.com/containerd/containerd@v1.4.3/content/local/store.go:140
helm.sh/helm/v3/internal/experimental/registry.(*Cache).fetchBlob
                /home/circleci/helm.sh/helm/internal/experimental/registry/cache.go:356
helm.sh/helm/v3/internal/experimental/registry.(*Cache).FetchReference
                /home/circleci/helm.sh/helm/internal/experimental/registry/cache.go:102
helm.sh/helm/v3/internal/experimental/registry.(*Client).PullChartToCache
                /home/circleci/helm.sh/helm/internal/experimental/registry/client.go:206
helm.sh/helm/v3/pkg/action.(*ChartPull).Run
                /home/circleci/helm.sh/helm/pkg/action/chart_pull.go:43
main.newChartPullCmd.func1
                /home/circleci/helm.sh/helm/cmd/helm/chart_pull.go:43
github.com/spf13/cobra.(*Command).execute
                /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850
github.com/spf13/cobra.(*Command).ExecuteC
                /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958
github.com/spf13/cobra.(*Command).Execute
                /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main
                /home/circleci/helm.sh/helm/cmd/helm/helm.go:80
runtime.main
                /usr/local/go/src/runtime/proc.go:204
runtime.goexit
                /usr/local/go/src/runtime/asm_amd64.s:1374

```

**Comment by tompatib** [comment]
Same here on Windows, the mentioned blob doesn't exist, although it got downloaded a day before on the same agent. It turned out that in the meantime the tag got changed in the OCI registry (like 1.0.0 -> 1.0.0-X as we had the docker image besides with 1.0.0) and the pull was still referring the old tag.
I would expect to return a message like tag not found or such.

**Comment by lindhe** [comment]
I have a scenario that causes this. We had a name collision when a Helm OCI chart lives along Docker images in a repository.

```console
$ helm chart push registry.example.com/foo/bar:0.1.0
# The blob now exists in the registry with the tag 0.1.0

$ docker push registry.example.com/foo/bar:0.1.0
# As a "wholly unrelated event", someone pushed a Docker image with the same name.
# This is clearly a name collision, but the registry accepts it and now it's the Docker image that has the tag 0.1.0 and our Helm OCI chart loses it.

$ helm chart pull registry.example.com/foo/bar:0.1.0
# Everything is now broken, since the object fetched has the right name but is not a Helm OCI chart.
```

Removing `bar:0.1.0` from the lists of manifests in `~/.cache/helm/registry/cache/index.json` fixes it.

First of all I suggest we create a subcommand `helm chart purge` to clean out the cache.

Secondly, perhaps we should validate that the blob is indeed a valid OCI chart. Can we perhaps inspect the media type of the blob when downloading, or something like that?

**Comment by bacongobbler** [comment]
#9782 removes the cache mechanism from Helm entirely, and in doing so fixes this issue.
