### ISSUE TITLE
Error: create: failed to create: Request entity too large: limit is 3145728

### ISSUE THREAD

**Issue by dhirajsurve** [helm/helm#8062]
Output of `helm version`:
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
minikube

command : helm upgrade --install .....--set-file =input.xml(more than 100mb)
-->Error: create: failed to create: Request entity too large: limit is 3145728

I am getting this error while  helm upgrade , I have one xml file in the input which  is more than 100mb , is there any way to increase max limit of helm ? 
I cant reduce the size of file , it must be passed . Any solution to fix this error will be helpful .

**Comment by liuming-dev** [comment]
> kube-apiserver: a request body of a CREATE/UPDATE/PATCH/DELETE resource operation larger than 100 MB will return a 413 "request entity too large" error. (#73805, @caesarxuchao)

cc https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.14.md

**Comment by hickeyma** [comment]
@dhirajsurve There is a limit of 1M limit storage on etcd which means that a Helm release cannot exceed 1M. The `input.xml` file is too large. Similar to #7264.

**Comment by dhirajsurve** [comment]
thanks for response . I am trying to build image with my big file instead of passing through helm .

**Comment by jasonmimick** [comment]
I needed to put `.git` in `.helmignore` - and lots more. I kept running `helm package .` and then `tar tvf xxx.tar.gz` and figure out what junk in my repo was bloating the helm package. 
There was alot, including a previous tarball from running helm package.

**Comment by hickeyma** [comment]
>  I am trying to build image with my big file instead of passing through helm .

Ok, let us know how you get on @dhirajsurve

**Comment by hickeyma** [comment]
I will close this as question is answered @dhirajsurve. Let us know if we need to re-open.

**Comment by dhirajsurve** [comment]
I added my big file into docker image and installed with helm (without passing it )  , that helped me .
