### ISSUE TITLE
Helm upgrade with hooks

### ISSUE THREAD

**Issue by OpusMeum** [helm/helm#8063]
Hey. I have a question about the algorithm of the "helm upgrade" command in conjunction with hooks.

Without hooks, the "helm upgrade" command works as expected. Pod is updated only if changes have been made to the Deployment resource:

apiVersion: apps / v1
kind: Deployment
metadata:
  name: {{include "testchart.fullname". }}
  labels:
    {{- include "testchart.labels". | nindent 4}}
...

When hooks are added, the "helm upgrade" command is updated Pod even if no changes have been made to the Deployment resource:

apiVersion: apps / v1
kind: Deployment
metadata:
  name: {{include "testchart.fullname". }}
  labels:
    {{- include "testchart.labels". | nindent 4}}
  **annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "50"**

So it was originally conceived?

**Comment by bridgetkromhout** [comment]
Hi, @OpusMeum - I am trying to understand your question, but I am not sure what you mean by `the "helm upgrade" command is updated Pod` or by `So it was originally conceived?` - but you are correct that hooks will show up in the resources after being defined.

More detail about the release lifecycle and hooks can be found in the docs; perhaps that will help, or you can let us know what is missing: https://helm.sh/docs/topics/charts_hooks/#hooks-and-the-release-lifecycle
