### ISSUE TITLE
helm options  doesn't all have the --output flag

### ISSUE THREAD

**Issue by survivant** [helm/helm#8064]
the option to output to json is not available for helm dep

$ helm dep list
NAME VERSION REPOSITORY STATUS
tomcat 6.3.6 https://charts.bitnami.com/bitnami ok

$ helm dep list --output json
Error: unknown flag: --output

is it possible to add the --output option to all commands ?

**Comment by bacongobbler** [comment]
Please feel free to work on a patch to provide this.

**Comment by yonatankahana** [comment]
I'd love to take this on myself as a first issue.

**Comment by survivant** [comment]
go go go :)

**Comment by survivant** [comment]
@yonatankahana thanks for your help. there is another issue : https://github.com/helm/helm/issues/8066 that I open yesterday (more complicated.. it you like challenge)

**Comment by yonatankahana** [comment]
@survivant I thought you'd like to work on it yourself, if you're not then of course I'd be happy. Let me know what you decide, for now I'll concentrate on this issue.

**Comment by survivant** [comment]
Go, take it please.

Le ven. 8 mai 2020 17 h 22, yonatankahana <notifications@github.com> a
écrit :

**Comment by survivant** [comment]
> 
> 
> @survivant I thought you'd like to work on it yourself, if you're not then of course I'd be happy. Let me know what you decide, for now I'll concentrate on this issue.

yes you can take it.  Please do :)

**Comment by survivant** [comment]
keep open

**Comment by survivant** [comment]
still valid

**Comment by survivant** [comment]
Still valid
