### ISSUE TITLE
feature request: `helm dependency list`

### ISSUE THREAD

**Issue by survivant** [helm/helm#8066]
I installed Wordpress using this command : 

helm install test-word bitnami/wordpress

helm list

`test-word       default         1               2020-05-06 11:05:05.772662027 -0400 EDT deployed        wordpress-9.0.4         5.3.2
`

kubectl get pods
``test-word-mariadb-0                             0/1     Pending   0          6m46s
test-word-wordpress-68df8bf4f4-k8g8c            0/1     Pending   0          6m46s
``

root@test-pcl114:~# helm dep list bitnami/wordpress
Error: stat bitnami/wordpress: no such file or directory

root@test-pcl114:~# helm dep list test-wordpress
Error: stat test-wordpress: no such file or directory

root@test-pcl114:~# helm dep list wordpress
Error: stat wordpress: no such file or directory

root@test-pcl114:~# helm version
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}

root@test-pcl114:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

**Comment by survivant** [comment]
with Helm v3.2.0

**Comment by bacongobbler** [comment]
`helm dependency list` was not originally designed to work with charts in remote repositories. From https://helm.sh/docs/helm/helm_dependency_list/#synopsis:

> This can take chart archives and chart directories as input.

If you want to determine the chart dependency list, use `helm pull` before `helm dep list` to fetch the chart locally to inspect.

Hope this helps.

**Comment by survivant** [comment]
the logic in helm is to check the dependencies in Chart.yalm and dependencies.yaml  from the untar chart ?  instead of parsing the file.  Could helm parse the output of : helm show chart "releasename"  ?

**Comment by bacongobbler** [comment]
A `helm show dependencies` might be possible. Feel like working on a pull request to implement that functionality?

**Comment by survivant** [comment]
I'll have to learn go  first.  I don't say no.  I can try, but it will take a little time, and how should I start to setup my env to build and test ?  (intellij on Windows can work ?  )

**Comment by bacongobbler** [comment]
https://helm.sh/docs/community/developers/

**Comment by survivant** [comment]
and there is a way to know which charts were deployed under the main chart ?

I can find the dependencies of wordpress (in my example), but if I do helm list  ,  I only see wordpress not the charts under it.   I can get that information using kubectl.. but from helm is there a way ?  

because  helm show dependencies  could return what was deployed too (with another command  like helm dependencies status  )

**Comment by yonatankahana** [comment]
Because Sebastian asked me to take it, I would love to implement his idea.

@bacongobbler I am wondering how the output should look like if it comes from `helm show` since this command usually return file contents. 
Would not be more convenient to extend the command `helm dep list` with extra flag `--all` (or similar) that will show all dependencies from the lockfiles in the currently existing format?

Here's an example of what I am proposing:
```bash
$ helm dep list example/
NAME     	VERSION	REPOSITORY                                      	STATUS
wordpress	5.0.2  	https://kubernetes-charts.storage.googleapis.com	ok    

$ helm dep list example/ --all
NAME     	VERSION	REPOSITORY                                      	STATUS
wordpress	5.0.2  	https://kubernetes-charts.storage.googleapis.com	ok    
mariadb		5.2.5	https://kubernetes-charts.storage.googleapis.com	transitive
```

**Comment by bacongobbler** [comment]
@yonatankahana that makes sense. After re-reviewing the OP, that would solve his use case.

I was confused with the original ask because it was implied he wanted to look at the list of dependencies available from a release that was already deployed to the cluster, not one that was fetched locally.

Feel free to work on a PR.

**Comment by bacongobbler** [comment]
I've renamed the title to reflect the ask. https://github.com/helm/helm/issues/8081 now tracks the discussion around `helm show dependencies`.

**Comment by yonatankahana** [comment]
@bacongobbler excellent. i'll start working on that.

**Comment by Prims47** [comment]
Oh boy, I've already started working on that feature 😢

**Comment by survivant** [comment]
still valid

**Comment by survivant** [comment]
Still valid
