### ISSUE TITLE
helm can't see racnehr2 isntlalation to perform upgrde

### ISSUE THREAD

**Issue by Cobra1978** [helm/helm#8068]
Output of `helm version`:
 bin/helm version
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}

Output of `kubectl version`:
bin/kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Self hosted Cluster

Hi, i have this problem, as i try to upgrade Rancher2 using helm i reveive this error:
`bin/helm get values rancher
Error: release: "rancher" not found`

tiller is present on the cluster, and the tiller account is also present and configured as per documentation.

How could i solve this?

There is any other information i can wirte here to help debugging the problem?

**Comment by hickeyma** [comment]
What is the output of `helm list -a`? Can you see release `rancher` in this output?

**Comment by Cobra1978** [comment]
No output 

On other installation
 bin/helm list -a
NAME            REVISION        UPDATED                         STATUS          CHART                   APP VERSION     NAMESPACE
cert-manager    1               Mon Aug 26 11:33:51 2019        DEPLOYED        cert-manager-v0.5.2     v0.5.2          kube-system
rancher         9               Thu May  7 08:32:26 2020        DEPLOYED        rancher-2.4.3           v2.4.3          cattle-system

**Comment by hickeyma** [comment]
@Cobra1978 You need a release first before you can upgrade it. The error message is saying that `rancher` release does not exist, hence you can't upgrade it. You would need to install it first.

**Comment by Cobra1978** [comment]
Sorry but this is an alreardy installed and running rancher cluster, if i reinstall it i think i will break it, or am ai wrong?

**Comment by Cobra1978** [comment]
![image](https://user-images.githubusercontent.com/33548070/81274821-1e1a1d00-9051-11ea-97f4-fc9d75065ea5.png)

**Comment by hickeyma** [comment]
Can you show the full install command that you are trying to run?

**Comment by Cobra1978** [comment]
The one on the documentation: bin/helm upgrade rancher rancher-stable/rancher

**Comment by bacongobbler** [comment]
Did you install it with Helm 3, perhaps? That would be the only reason why Helm 2 would not be able to see the release history. Either that or you deleted the release ledger, or restricted Tiller's access to read configmaps in kube-system.

**Comment by Cobra1978** [comment]
Unfortunately i've installed it with Helm2, and i've not changed anything in the management clauster after the installation

**Comment by bacongobbler** [comment]
Okay. I’m sorry, I don’t have any further tips I can provide. Let us know what you find out.

**Comment by Cobra1978** [comment]
Honestly i don't know hat to do, and i can't take any action that can caus emajor disruption because this is a production service.

If the release ledger get accidentaly deleted there is any way i can erecover it?

**Comment by Cobra1978** [comment]
People please, i realy need to recover this situation,

**Comment by bacongobbler** [comment]
I'm not sure I can provide more help here given the information that has been provided. If you can provide more information about how you got yourself into this situation, we may be able to determine a root cause. But based on what's been described here, we're unsure what would cause this and cannot help you further.

**Comment by Cobra1978** [comment]
As said i've installed Rancher2 as per documentation, and as iv'e made on the develop cluster, and the first time i've tried to upgrade this production gluster i've got the error described.

If you tell me what other logs, files, or any other thing i can check to give you more information i will do that.

**Comment by Cobra1978** [comment]
I don't know if it's relevant, but in the cluster that i cant'upgrade i have thie secret sh.helm.release.v1.rancher.v1 that is not present on the working cluster.


![image](https://user-images.githubusercontent.com/33548070/83043450-332c0f80-a043-11ea-902c-f1349f2488cb.png)

**Comment by bridgetkromhout** [comment]
Hi, @Cobra1978 - as mentioned before, we do not have specific knowledge of Rancher, so perhaps the folks over in https://github.com/rancher/rancher/issues would have more ideas. I'm going to resolve this issue here as we are no longer providing Helm v2 support.

It is very important for you to migrate your production workloads off this Helm v2 system. Helm v2 is no longer getting bugfixes, and in November it will no longer get security patches. So please take a look at https://helm.sh/blog/helm-v2-deprecation-timeline/ and migrate to Helm v3. Thanks!
