### ISSUE TITLE
'helm repo update {REPO} ' feature

### ISSUE THREAD

**Issue by carrodher** [helm/helm#8071]
Some `helm repo` commands accept the repository name as parameter, that is not the case of `helm repo update`, this command doesn't receive any extra parameter, updating all the installed repos.

There are some cases where it would be useful to just update one specific repository, for example, if I am working with one specific repository, I don't need to update all of them, just the one I want to obtain the latest changes.

With the "new" approach of distributed repositories, it will be more habitual to have a larger list of repositories. Do you think something like this feature is useful? Is it a good option for a first-contribution PR?

```console
$ helm repo list
NAME             	URL
bitnami          	https://charts.bitnami.com/bitnami
stable           	https://kubernetes-charts.storage.googleapis.com
azure-marketplace	https://marketplace.azurecr.io/helm/v1/repo

$ helm repo update bitnami
Hang tight while we grab the latest from your chart repository...
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈ Happy Helming!⎈
```
instead of
```console
$ helm repo list
NAME             	URL
bitnami          	https://charts.bitnami.com/bitnami
stable           	https://kubernetes-charts.storage.googleapis.com
azure-marketplace	https://marketplace.azurecr.io/helm/v1/repo

$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "azure-marketplace" chart repository
...Successfully got an update from the "bitnami" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈
```

**Comment by mattfarina** [comment]
@carrodher Is the issue due to the performance and growing about of time an update takes? Why not update all the things? I'm curious is there is more depth to the reason. Trying to understand a little better.

**Comment by carrodher** [comment]
Hi, not at all, of course, the time is higher updating six repos than one, but it is not significant, at least for me.

The idea was oriented to share the information with other people, for example when replying to a GH issue or a meetup/talk. I can have private repositories added to my helm client but I don't want to show this information to others, so at this moment I don't have a way to only update one repository (and in parallel only see the logs for that repository) instead of all the installed ones.

For example:

> Hey, we just fixed the issue in this new version. It is already released, you can find it by running
> ```
> $ helm repo update
> Hang tight while we grab the latest from your chart repository...
> ...Successfully got an update from the "bitnami" chart repository
> Update Complete. ⎈ Happy Helming!⎈
> 
> $ helm search repo bitnami/elasticsearch
> NAME                 	CHART VERSION	APP VERSION	DESCRIPTION
> bitnami/elasticsearch	12.0.2       	7.6.2      	A highly scalable open-source full-text search ...
> ```

Now, to provide this kind of answer without showing other repositories I need to "edit" the `helm repo update` output removing other lines.

I know it is not a big feature but maybe a good way to a first contribution to the repo on my side.

**Comment by technosophos** [comment]
Note that if anyone attempts to change this behavior, you will need to solve the case where a chart in Repo A references a chart in Repo B, and Repo A gets locally updated but Repo B does not.

**Comment by pio2pio** [comment]
> Note that if anyone attempts to change this behaviour, you will need to solve the case where a chart in Repo A references a chart in Repo B, and Repo A gets locally updated but Repo B does not.

Not dying for this feature, but if someone decides to update one repo, its the operator decision to do so. If such dependency exists it's up to the operator to update both.

My use case is, to have simple pipelines with separate bash files doing standard `helm install`, to make them self contained I do use `helm repo update`, but over a few installs this get staggered and unnecessary to update repos that just got updated.

**Comment by wi1dcard** [comment]
Hi there, after #8777, helm seems not to update the repo when using `helm repo add`, even with the URL in the command arguments and existing repo is the same.

Although we can just use `helm repo add --force-update`, which will update the repo if it exists without checking the URL, it leaves potential vulnerabilities as the release notes described.

So I'm wondering if there's any chance we can get the feature of updating a single repo, or adding an option like `--update` but perform the verification of the URLs. I personally prefer the first implementation.

Also, I'm constructing the PR roboll/helmfile#1542, in a common use case, we might want to:

1. adding the repo if it was specified in `helmfile.yaml` and doesn't exist on local
2. update the repo to the latest as possible if it was specified in `helmfile.yaml`

I don't think updating all the repos, including the repos not defined in `helmfile.yaml`, is a good option, as it might be already existent and managed by users or other tools.

**Comment by LeiYangGH** [comment]
for me it is **indeed** due to the performance and growing about of time an update takes. in my company our local network is slow connecting to artifactory, so we like to ssh to a public virutal machine to do helm things, but there are various repos added by others. it takes me about 30s to update all 6 repos.

**Comment by survivant** [comment]
I have few custom Helm charts that include other custom helm charts.   I have a script to update the dependencies.. but it take l lot of time  to do a helm repo update for all the repositories.  I need to update all of them when the script starts.. but after that I only need to update my private repository for each of my custom charts.

````
helm repo update private-repository
````

should do the job.

**Comment by wi1dcard** [comment]
Any update?

**Comment by carrodher** [comment]
Thanks for implement this suggestion!
