### ISSUE TITLE
helm package: --set flag removed

### ISSUE THREAD

**Issue by datosh** [helm/helm#8079]
In Helm Version 3.0.3 the `--set` argument for `helm package` was removed. The merge request states [this flag was never used and was a no-op.](https://github.com/helm/helm/commit/50dcd39ba5a3c50bd046b5b539c2c7e6ac68aea1) This is not true, as one can see [here](https://github.com/helm/helm/commit/50dcd39ba5a3c50bd046b5b539c2c7e6ac68aea1#diff-8d77fde9f090ba83cde5e567247c5649L63) the removed code also removed an update to `values.yml` file.

I was dependent on this behavior, since I used `helm package --set` to dynamically set default values for my Helm Chart in my CI/CD pipeline.

Can we bring back this behavior? Or am I using `helm` wrong and there is a different approach to achieve the same goal?

Cheers,
datosh

**Comment by hickeyma** [comment]
@bacongobbler Can you shd some light on the changes in #7201 and removal of the this flag?

**Comment by bacongobbler** [comment]
#7201 reverted a commit that was never intended to be shipped. It was removed in the Helm 2 branch, but accidentally made its way into Helm 3. https://github.com/helm/helm/pull/3471#issuecomment-381779783

If someone wants to work on re-implementing #3471 that retains comments, we'd be happy to look at PRs.

See https://github.com/helm/helm/issues/3141 for the current discussion. Thanks!

**Comment by royalsarkis** [comment]
You can use "helmer", a script that provides functionality similar to the helm package command, with the added benefit of allowing you to override the values.yaml file
https://github.com/royalsarkis/helmer
