### ISSUE TITLE
Updating service of previous version

### ISSUE THREAD

**Issue by rakkum** [helm/helm#8080]
Hello,

I am using helm 3.2.0 `version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}` and want to new releases use the same name of a service definition.

Reason behind that is that we are using Ocelot as an API gateway and there you have to specify the service name for traffic redirection. So if the service name has to be different for each update, it will not work. When just doing `helm upgrade --install --values /home/vsts/work/1/helmvalues/file.values.yaml --wait 2020.05.32 repository/file.service`
I get the following error: `Service "file-service" in namespace "XXX" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "2020.05.32": current value is "2020.05.27"`

Is there any flag when upgrading to integrate the existing resource to allow the overwrite? Or any way to rename the service after?

Sorry if that is a stupid question but I couldn't find any information about a use case like this.

**Comment by bacongobbler** [comment]
Have you tried changing the label described in the error to the expected value?

**Comment by rakkum** [comment]
Is it possible to do that automatically when installing a new release? I can fix it now manually but i want a general solution when upgrading.

**Comment by mattfarina** [comment]
@rakkum If I read your `helm upgrade` and the associated error correctly, you are not upgrading but rather installing a new version. The previous instance of the chart was "2020.05.27" The new instance of the chart is named "2020.05.32". So, you have two instances of two different versions of the same chart. Is that right?

**Comment by rakkum** [comment]
@mattfarina Yes, I want to install a new version of the same chart. I started with the helm template where it uses this for the service:
```
apiVersion: v1
kind: Service
metadata:
  name: {{ include "file.fullname" . }}
  namespace: {{ .Values.namespace }}
```
fullname then uses the _helpers.tpl to generate the instance name which is .Release.Name-.Chart.Name per default.

Am i doing something wrong there? Because since I am using upgrade --install i cannot specify the release name. So it should be something like `helm upgrade --install --values XXX --version myspecificVersion file.service repository/file.service` in case my release name is called file.service?

**Comment by hickeyma** [comment]
@rakkum Can you show the `_helpers.tpl ` file? Also, do you mind showing the output of the `upgrade` command using `--dry-run` flag? It would better help understand the issue.

**Comment by rakkum** [comment]
Ok i solved it. It was as i expected a silly thing. I was treating the release name as the release version that should change every time. Instead its meant as an installation identifier that you install once and dont change after. When changing the release name to the chart name it worked.
