### ISSUE TITLE
proposal: helm get dependencies

### ISSUE THREAD

**Issue by survivant** [helm/helm#8081]
One problem with helm list  is that it show the main chart that was deployed but we don't know if there are dependencies deployed too.

helm list
`wordpress       default         1               2020-05-06 10:59:24.0373954 -0400 EDT   deployed        wordpress-9.0.3         5.3.2`

kubectl get pods
```
NAME                                            READY   STATUS    RESTARTS   AGE
wordpress-7b7b8d7cf6-52chl                      0/1     Pending   0          45h
wordpress-mariadb-0                             0/1     Pending   0          45h
```

we should be able to get that kind of information

**Comment by mattfarina** [comment]
@survivant Are you asking for a list of the dependent charts or all the resources a chart deployed?

**Comment by survivant** [comment]
all resources deployed for the chart.

like if I deploy this chart : stable/elastic-stack   under name "k"

helm list
`k               default         1               2020-05-08 09:22:08.9069397 -0400 EDT   deployed        elastic-stack-2.0.0     6
`

but I want to know if the was others charts( dependencies that were deployed too)

like

kubectl get pods --show-labels

```
k-elasticsearch-client-7796d6569c-pfqr8         0/1     Running   0          126m   app=elasticsearch,component=client,pod-template-hash=7796d6569c,release=k
k-elasticsearch-client-7796d6569c-shh4j         0/1     Running   0          126m   app=elasticsearch,component=client,pod-template-hash=7796d6569c,release=k
k-elasticsearch-data-0                          0/1     Pending   0          126m   app=elasticsearch,component=data,controller-revision-hash=k-elasticsearch-data-9cdb89448,release=k,role=data,statefulset.kubernetes.io/pod-name=k-elasticsearch-data-0
k-elasticsearch-master-0                        0/1     Pending   0          126m   app=elasticsearch,component=master,controller-revision-hash=k-elasticsearch-master-787985d74f,release=k,role=master,statefulset.kubernetes.io/pod-name=k-elasticsearch-master-0
k-kibana-797f75695d-842xm                       1/1     Running   0          126m   app=kibana,pod-template-hash=797f75695d,release=k
k-logstash-0                                    0/1     Pending   0          126m   app=logstash,controller-revision-hash=k-logstash-85c7d6dcb6,release=k,statefulset.kubernetes.io/pod-name=k-logstash-0
```

**Comment by Prims47** [comment]
Hello :)

I can take this features 😊 .
Can you assign me ? Thanks

**Comment by Prims47** [comment]
I have little question about dependencies. For Helm3 we must have apiVersion with `v2` and declare dependencies in `Chart.yaml` ? Because i see many repo without v2 and with requirements.yml.

I see [this](https://helm.sh/docs/topics/charts/#the-apiversion-field)

Like:

* https://github.com/helm/charts/blob/cbd5e811a44c7bac6226b019f1d1810ef5ee45fa/incubator/keycloak/requirements.yaml

* https://github.com/helm/charts/blob/cbd5e811a44c7bac6226b019f1d1810ef5ee45fa/stable/artifactory/requirements.yaml

* ...

**Comment by Prims47** [comment]
@survivant  I try this:

```
NAME                                                           	NAMESPACE	REVISION	UPDATED                      	STATUS         	CHART          	APP VERSION
            drax                                                           	default  	1       	2016-01-16 00:00:01 +0000 UTC	uninstalling   	chickadee-1.0.0	0.0.1
            fuegoPepito                                                    	default  	1       	2016-01-16 00:00:01 +0000 UTC	pending-install	benArfa-1.0.0  	0.0.1

            Deps NAME	Deps Home                 	Deps Version	Deps APP VERSION
            prims47  	https://charts.com/prims47	4.7.7       	0.0.1
            prims47  	https://charts.com/prims47	4.7.7       	0.0.1

            gamora                                                         	default  	1       	2016-01-16 00:00:01 +0000 UTC	superseded     	chickadee-1.0.0	0.0.1
            groot                                                          	default  	1       	2016-01-16 00:00:01 +0000 UTC	uninstalled    	chickadee-1.0.0	0.0.1
            hummingbird                                                    	default  	1       	2016-01-16 00:00:03 +0000 UTC	deployed       	chickadee-1.0.0	0.0.1
            iguana                                                         	default  	2       	2016-01-16 00:00:04 +0000 UTC	deployed       	chickadee-1.0.0	0.0.1
            rocket                                                         	default  	1       	2016-01-16 00:00:02 +0000 UTC	failed         	chickadee-1.0.0	0.0.1
            starlord                                                       	default  	2       	2016-01-16 00:00:01 +0000 UTC	deployed       	chickadee-1.0.0	0.0.1
            thanos
```

**Comment by Prims47** [comment]
@survivant .

I try something like that

```
NAME                                                                          	NAMESPACE	REVISION	UPDATED                              	STATUS  	CHART          	APP VERSION
wordpress                                                                     	default  	1       	2020-05-20 17:36:22.903309 +0200 CEST	deployed	wordpress-9.2.4	5.4.1
======== DEPENDENCIES ========
NAME                          	Version	Repository                        	Enabled
mariadb                       	7.x.x  	https://charts.bitnami.com/bitnami	true
================
```

**Comment by bacongobbler** [comment]
So, what OP is actually looking for is a way to list the dependencies of a chart that was already deployed to a cluster.

As mentioned in https://github.com/helm/helm/pull/8170#issuecomment-632236005, the output here would be incompatible with `helm list`, so the output demonstrated in the OP doesn't make much sense. You cannot manage `mariadb` as a separate release if it's deployed as a dependency of another chart.

From `helm help list`:

> This command lists all of the releases for a specified namespace (uses current namespace context if namespace not specified).

In this context, `mariadb` is not a release. It is a dependency of the `wordpress` release.

However, there is another command that handles similar use cases: `helm show`. We already have `helm show chart`, `helm show readme`, and `helm show values`. `helm show dependencies` would fit in nicely here.

I'll rename the title to reflect the ask.

**Comment by survivant** [comment]
keep open

**Comment by survivant** [comment]
still valid

**Comment by survivant** [comment]
Still valid
