### ISSUE TITLE
helm release label missing from parent chart

### ISSUE THREAD

**Issue by survivant** [helm/helm#8083]
I'm trying to find the pods that were installed when I deployed a chart with dependencies like wordpress.  

I found that in the chart mariadb, there is a label : release=wordpress

so if I do that

kubectl get pods -l release=wordpress
```
NAME                  READY   STATUS    RESTARTS   AGE
wordpress-mariadb-0   0/1     Pending   0          45h
```

I was expecting to find the pod wordpress too, because they were deployed together, but the label is not present when wordpress was deployed

kubectl describe pod wordpress
```
Name:           wordpress-7b7b8d7cf6-52chl
Namespace:      default
Priority:       0
Node:           <none>
Labels:         app.kubernetes.io/instance=wordpress
                app.kubernetes.io/managed-by=Helm
                app.kubernetes.io/name=wordpress
                helm.sh/chart=wordpress-9.0.3
                pod-template-hash=7b7b8d7cf6
```

```
kubectl describe pod wordpress-mariadb-0
Name:           wordpress-mariadb-0
Namespace:      default
Priority:       0
Node:           <none>
Labels:         app=mariadb
                chart=mariadb-7.3.12
                component=master
                controller-revision-hash=wordpress-mariadb-fc99f458f
                release=wordpress
                statefulset.kubernetes.io/pod-name=wordpress-mariadb-0

```

there is a way to add the label if it's not present in the charts ?

**Comment by omkensey** [comment]
If the chart supports it, you should be able to add the label in the values and `helm upgrade`.  If not, you can use [`kubectl label`](https://kubernetes.io/docs/concepts/cluster-administration/manage-deployment/#updating-labels).  The `kubectl` docs imply that the pods don't need to be restarted or recreated to accomplish this, but I'm not certain if that's true, or if it is, if it's true for the `helm upgrade` as well.

**Comment by survivant** [comment]
I did some testing and some of them support it. so I can rely on that.  I wanted to add my own label with that, I'll be sure to find the pods.  But I need to know which pods were installed to be able to add the label with kubectl later.  

I think that I have a workaround,  I install the charts, use kubectl to get all the pods (jsonpath regex doesn't work for that : https://github.com/kubernetes/kubernetes/issues/72220) .  Filter each nodes name that startWiths the release name.

like that, I'll have the dependencies that were installed  (ugly but with that.. I don't need to put labels).

**Comment by mattfarina** [comment]
I can add some detail to this.

Helm doesn't alter the Kubernetes manifests generated by a chart. It's up to the chart author to add the labels as part of their chart. The chart automatically created by `helm create` will add them and we guide people to use them but we can't force them to and we want to give the chart authors full creative control.

In the [documentation on labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/) there is a note that say:

> If the prefix is omitted, the label Key is presumed to be private to the user. Automated system components (e.g. kube-scheduler, kube-controller-manager, kube-apiserver, kubectl, or other third-party automation) which add labels to end-user objects must specify a prefix.

To facilitate cross tool labels for common things there are [recommended labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/). `helm create` uses these when it creates a chart by default.

Some public charts have not done this well or were first created prior to the current labels names that came out of a Kubernetes working group a couple years ago.

If there are inconsistent labels somewhere it's worth filing an issue to the chart.

**Comment by survivant** [comment]
yep.. still the far-west :)

**Comment by TBBle** [comment]
Since Helm 3.2.0 (via #7649), we now automatically add two annotations in `meta.helm.sh/` and a label `app.kubernetes.io/managed-by: Helm`.

Would it make sense for Helm to automatically add _all_ the recommended labels, where not already defined by the chart? Apart from `app.kuberntes.io/name`, [they](https://github.com/helm/helm-www/blob/master/content/en/docs/chart_best_practices/labels.md) all seem to have reasonably well-defined values.

I'd definitely like this. I have one meta-chart that has third-party sub-charts which predate the current label definitions, and so similar to the original poster, I have to do label-searches for some subset of `app.kubernetes.io/instance` and `app` and `k8s-app` and `release` when trying to find Pods which have not come up for some reason.

I can see it might have downsides though, although none come to mind. I'm unsure if I'd expect to see these labels in `helm template` output; I don't know if the current automatic labels/annotations appear there.

**Comment by survivant** [comment]
I have chart that have dependances.. they are probably not the latest version, but I can't choose to upgrade them without a good reason.  

Those charts are using 

release=xxx
app=chartname

so in my code, I have to look for resources with

app.kubernetes.io/instance=xxx

and other call for  release=xxx

would be nice if Helm could add those if they are not present 

      app.kubernetes.io/name: {{ include "app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
