### ISSUE TITLE
helm plugin install <url>.tar.gz results in a tar error

### ISSUE THREAD

**Issue by jkroepke** [helm/helm#8084]
Output of `helm version`:
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}

OS: mac OS 10.15.4

Running `helm plugin install` on a tar.gz archive (generated by github) results into a error:

```
Error: unknown type: 1100111 in pax_global_header
```

How to reproduce:
```
# Install a specific version
helm plugin install https://github.com/jkroepke/helm-secrets/archive/v3.1.0.tar.gz
```

I can confirm by running

```
curl -Ls https://github.com/jkroepke/helm-secrets/archive/v3.1.0.tar.gz | tar xzf -
```

the archive is extracted successfully.

While google it, I found the same issue on an other project. Here is the PR: https://github.com/mholt/archiver/pull/76

**Comment by mattfarina** [comment]
I've duplicated the bug. It is in the plugin http installer package. A similar fix to archiver will likely work.

Thanks for reporting this @jkroepke

**Comment by mattfarina** [comment]
Note, this is likely in both Helm v2 and v3.

**Comment by jkroepke** [comment]
Looks like helm has some handling already at an another point: https://github.com/helm/helm/pull/5198

**Comment by mattfarina** [comment]
Helm handle archives in a couple places. In the handling of chart archives this was fixed but not in the handling of plugin archives.
