### ISSUE TITLE
Feature request: --reset-then-reuse flag for upgrade

### ISSUE THREAD

**Issue by omkensey** [helm/helm#8085]
Currently Helm implements two ways of handling values when updating an existing release: reusing the existing user-supplied values if new ones are not supplied, or not reusing them if new ones are supplied.  However, the way these are implemented and the way `--reuse-values` and `--reset-values` change that default behavior is sometimes confusing; see, for example:

https://medium.com/@kcatstack/understand-helm-upgrade-flags-reset-values-reuse-values-6e58ac8f127e

(And see one of the commenters pointing out that even after this article-length treatment of the subject, the writer missed an important subtlety!)

What I think would be nice for users is a flag that means "take the existing chart's values, merge these new values I am giving you explicitly, and do not update values from the chart unless they are new to the chart since the version stored in the target release".  (Alternately one can think of this as "`--reset-values` followed by `--reuse-values` followed by user-supplied `--set*`values")

This seems like it would be less confusing in the majority of cases: if I give a value, it is updated; if I don't give it and it exists in the release, it is reused; if I don't give it and it doesn't exist in the release, it is set from the updated chart.  It would eliminate the case of "I did not specify this value as part of my upgrade but it changed anyway" which appears to be where much of the confusion strikes.

**Comment by Envek** [comment]
Possibly related issue: https://github.com/helm/helm/issues/3957

---

Here is my big **+1** for this. Frequent use case for which `--reuse-values` works very counter-intuitive is **adding new features to the chart**.

It is very annoying that when I add new templates and default values into application's chart, **`--reuse-values` uses new templates, but doesn't use new values** which leads to templates errors at best and to partial upgrades at worst.

For example, if I add following snippet to some deployment's definition:
```diff
+           ports:
+             - containerPort: {{ .Values.metrics.port }}
+               name: metrics
```

And values for it:
```diff
+ monitoring:
+   port: 8001
```

And then execute `helm upgrade ./helm-chart --reuse-values --wait --atomic`

Then I get following error:
```
Error: UPGRADE FAILED: template: cool-app/templates/deployment.whatever.yaml:19:39: executing "cool-app/templates/deployment.whatever.yaml" at <.Values.metrics.port>: nil pointer evaluating interface {}.port
```

While expected result is to perform upgrade using new default values.

At the same time all testing commands like `helm template` and `helm lint` works perfectly and uses values from local `values.yaml`.

**Comment by zaro** [comment]
@Envek very well put. That's exactly my biggest problem when developing charts.

This option sounds much friendlier, than getting the values, and then passing them to upgrade.

**Comment by bacongobbler** [comment]
As mentioned in https://github.com/helm/helm/issues/3957#issuecomment-384685681, an alternative way to accomplish this today without needing to introduce a new feature to Helm would be

`helm get values foo > values.yaml && helm upgrade foo ./foochart -f values --set ...`

I could see future use cases where users may want to tweak the values from `helm get values` (e.g. coercing some values to strings and some values to integers to fix an issue from a previous release). I'm concerned about adding "yet another value merge strategy flag" to Helm, and I'm curious why the workflow described earlier cannot handle this use case, or that a plugin cannot handle this case.

```
      --reset-values                 when upgrading, reset the values to the ones built into the chart
      --reuse-values                 when upgrading, reuse the last release's values and merge in any overrides from the command line via --set and -f. If '--reset-values' is specified, this is ignored
      --set stringArray              set values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)
      --set-file stringArray         set values from respective files specified via the command line (can specify multiple or separate values with commas: key1=path1,key2=path2)
      --set-string stringArray       set STRING values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)
  -f, --values strings               specify values in a YAML file or a URL (can specify multiple)

**Comment by zaro** [comment]
I can try to explain from my workflow. For my workflow the current implementation of '- - reuse-values' is absolutely pointless.

We deploy using chart that we have developed, and we use the same chart, for our production., staging and feature branch deployment. This means that sometimes we need to change the chart also, and here is where things break with --reuse-values. Becuase when the chart was modified, you need to know whether reuse values makes sense or not. Right now we always use the workaround you've described with get values. But I really can't wrap my head why this is not the default behaviour of reuse values instead of the current one.

**Comment by bacongobbler** [comment]
Does `helm get values foo > values.yaml && helm upgrade foo ./foochart -f values --set ...` not work for you?

**Comment by Envek** [comment]
`helm get values foo > values.yaml && helm upgrade foo ./foochart -f values --set ...` definitely works but there is always a little chance that someone or something else will do `helm upgrade` between these steps.

**Comment by Envek** [comment]
It is still pain in the ass, to be honest and should be kept open, IMO.

`helm get values && helm upgrade` is just a workaround and doesn't feel right.

Some new flag with non-nonsense behavior for helm end users should be considered, I believe.

**Comment by Envek** [comment]
No, please keep it open.

**Comment by bacongobbler** [comment]
I've marked this as "keep open" for the time being. But without anyone stepping up to actually implement said feature, I am going to assume that either

a) a workaround (like [the ones suggested earlier](https://github.com/helm/helm/issues/8085#issuecomment-674190314)) works well enough and solves the use case, or
b) this is a non-issue for most folks

In which case we should close this.

@Envek are you planning on implementing this, or are you waiting for someone to pick up the work? This ticket's been open for nearly a year, and https://github.com/helm/helm/issues/3957 has just celebrated its third birthday. We have documentation available to [help you get started](https://helm.sh/docs/community/developers/).

Let me know how I can help.

**Comment by Envek** [comment]
I believe that https://github.com/helm/helm/pull/9516 can fix that

**Comment by bacongobbler** [comment]
_sigh._

Once again, we are NOT accommodating changes to `--reuse-values`'s behavior. We have stated our reasons for this decision _multiple times_. #9516 completely disregards that decision and changes it anyways. So I closed it.

Please stop asking us to change the behavior of a flag. It's not going to happen.

**Comment by sevetseh28** [comment]
I also wanna jump in the train here and request a new flag with the desired behaviour. It is a super common and important use case for deployments of charts that contain multiple environments or canary releases in one chart.

**Comment by rkul** [comment]
Hello everyone!
Could some tell why #9653 is still not accepted? It does the job, doesn't it?

**Comment by christian-kreuzberger-dtx** [comment]
Would love to get this feature, as it is really important for us.

Main use-case: We have certain user-supplied values that we want the user to overwrite, but we also maintain internal values in the helm chart. We regularly release a new version of our chart, and when we upgrade the chart using `--reuse-values` we get in a situation where not all internal values are upgraded/merged.

**Comment by bitjson** [comment]
@bacongobbler it looks like you've been merging some PRs today – I think https://github.com/helm/helm/pull/9653 would solve this issue, would you mind taking a look?

As silly as it seems, this is probably the most significant barrier I've had in introducing Helm to users. Most expect the `--reset-then-reuse-values` behavior, and are blindsided when the accidentally wipe their existing configuration. Even just having the additional flag would help to make the behavior of `--reset-values` and `--reuse-values` more understandable.

Is there anything anyone else can do to move this PR forward?

**Comment by rinormaloku** [comment]
PING. 

This flag `--reset-then-reuse-values` would make the other (IMHO stupid) flag `--reuse-values` almost make sense. But still, not, as it's really a silly flag.

**Comment by holyspectral** [comment]
For anyone waiting for that https://github.com/helm/helm/pull/9653 being merged, I hit this issue today and https://github.com/helm/helm/issues/8085#issuecomment-674190314 's method works perfectly.

**Comment by bitjson** [comment]
@bacongobbler earlier mentioned:
>  I'm concerned about adding "yet another value merge strategy flag" to Helm [...]

I stumbled across this nice resource today: https://shipmight.com/blog/understanding-helm-upgrade-reset-reuse-values (thanks @codeclown)

It includes some good infographics, and this summary of Helm's `value` management is excellent:

![helm-upgrade-article table](https://user-images.githubusercontent.com/904007/214683292-665f46c8-751e-4159-bc8e-40863a664a11.png)

But I think this visualization makes it clear that Helm is really only missing one `helm upgrade` value merging strategy. Reorganized as a binary table: 

| Binary | Command                                     | Chart defaults | Previous values | --set |
| :----: | ------------------------------------------- | :------------: | :-------------: | :---: |
| 0b000  | n/a (no values)                             |       -        |        -        |   -   |
| 0b001  | `helm upgrade --set foo=bar`                |       -        |        -        |  ✅   |
| 0b010  | n/a (no change)                             |       -        |       ✅        |   -   |
| 0b011  | `helm upgrade --set foo=bar --reuse-values` |       -        |       ✅        |  ✅   |
| 0b100  | `helm upgrade --reset-values`               |       ✅       |        -        |   -   |
| 0b101  | `helm upgrade --set foo=bar --reset-values` |       ✅       |        -        |  ✅   |
| 0b110  | `helm upgrade`                              |       ✅       |       ✅        |   -   |
| 0b111  | **`helm upgrade --MISSING --set foo=bar`**  |       ✅       |       ✅        |  ✅   |

So it seems that this is not just another merging strategy, it is actually **the only missing merge strategy**. 

This also seems to be the expected default for a non-trivial subset of new Helm users. E.g. a web search for `helm reuse values` turns up dozens of blog posts, help docs, and stackoverflow posts that describe this missing strategy as "surprising":

- [Understand helm upgrade flags — reset-values & reuse-values](https://medium.com/@kcatstack/understand-helm-upgrade-flags-reset-values-reuse-values-6e58ac8f127e)
- [Understanding Helm upgrade flags (with infographics)](https://shipmight.com/blog/understanding-helm-upgrade-reset-reuse-values)
- [Understanding the "Reset Values" option in the Helm Chart step](https://help.octopus.com/t/understanding-the-reset-values-option-in-the-helm-chart-step/27132)
- [Upgrade via Helm :: StackGres Documentation](https://stackgres.io/doc/1.1/install/helm/upgrade/) `Important note: Do not use the --reuse-values option from Helm, this prevent the new operator resources and the new values needed to be set. [...]`
- [How do I upgrade a helm chart with a new values.yaml and keep the previous deployments data?](https://stackoverflow.com/questions/52634741/how-do-i-upgrade-a-helm-chart-with-a-new-values-yaml-and-keep-the-previous-deplo)
- and many more.

My interest in this feature: I [maintain a helm chart](https://github.com/bitauth/chaingraph) used primarily by users who are new to both Kubernetes and Helm. 

**Having this option available would make my setup/upgrade instructions a lot less confusing/error-prone for new users.**

**Comment by joejulian** [comment]
@bacongobbler asked earlier, "I'm curious why the workflow described earlier cannot handle this use case, or that a plugin cannot handle this case." Though he's no longer active in the project I do have an answer.

When running `ct install --upgrade` [1](https://github.com/helm/chart-testing) the upgrade is run with `--reuse-values`. 

This means if you add a new defaulted value to your chart, the upgrade test will fail. The new chart value will not be included. There is no way in ct to tell it to run some script as part of the upgrade.

It's also been stated that the `--reuse-values` flag behavior will not be changed, and it's also been stated that he's against adding "yet another value merge strategy flag" to Helm". I disagree.

The _default_ strategy for the reuse-values flag cannot be changed. That's true. If the flag is set without options, the behavior should remain the same. If the flag is reset, that behavior should not change either.

We _can_, however, change the flag from a Boolean to a String - similar to what kubectl did with the dry-run flag, changing from a boolean to "client" or "server", ie. `--reuse-values=merge` (or something like that). If the flag is specified without arguments, it would default to (eg.) "replace" which would be the same as "true". This would not break any existing usage, but would extend the flag to accommodate additional behavior.

**Comment by joejulian** [comment]
For an example of another PR taking this approach, see https://github.com/helm/helm/pull/9426#issuecomment-1407259188
