### ISSUE TITLE
helm chart pull --> Error: tag explicitly required

### ISSUE THREAD

**Issue by mathieu-benoit** [helm/helm#8090]
I'm getting an error while doing `helm chart pull myregistry.azurecr.io/myapp:13546`: `Error: tag explicitly required`.

I was able previously to successfully run `helm chart push myregistry.azurecr.io/myapp:13546`, so I'm confirming that my chart resides in my registry.
Furthermore, if I'm trying with a Tag `X.X.X` or `vX` it's working well.

Output of `helm version`: `version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}`

Output of `kubectl version`: N/A

Cloud Provider/Platform (AKS, GKE, Minikube etc.): with Azure Container Registry (ACR) with the OCI experimental support: https://docs.microsoft.com/azure/container-registry/container-registry-helm-repos#use-the-helm-3-client

**Comment by bacongobbler** [comment]
I think this may be a bug in the tag resolver. It's likely interpreting the tag as a port number rather than a tag. I've seen a number of bugs similar to this come up. cc @jdolitsky

You could start to verify this behaviour by writing a test against [`ParseReference`](https://github.com/helm/helm/blob/af52d35fb6abdbb3bc170281f95e27a3c1d6d4ab/internal/experimental/registry/reference.go#L47-L77) then working on a fix.

**Comment by jdolitsky** [comment]
I think this is the case. @mathieu-benoit - can you try prefixing your tag with a letter?

**Comment by mathieu-benoit** [comment]
Yep like mentioned on the description of the issue above, I could confirm that if the tag is in those formats: `X.X.X` or `vX`, it's working fine.

**Comment by jdolitsky** [comment]
@mathieu-benoit - thanks for verifying. We need to improve the code for parsing references.

Related to https://github.com/helm/helm/issues/6977

**Comment by mathieu-benoit** [comment]
JFYI, in case that could help, I was able to successfully run the 3 commands below without any issues and with the same `tag` / `helmchart version`:
- `helm package`
- `helm save`
- `helm push`

So looks like there is a verification (`ParseReference` mentioned earlier in this thread) during `helm pull` but not with the 3 mentioned above? Don't know if that's on purpose?

**Comment by Prims47** [comment]
Hi 😊 ,

I try to fix this via unit test with:

```
s = "myrepo/mychart:1222222"
	ref, err = ParseReference(s)
	is.NoError(err)
	is.Equal("myrepo/mychart", ref.Repo)
	is.Equal("1222222", ref.Tag)
	is.Equal("myrepo/mychart:1222222", ref.FullName())

	s = "myrepo/mychart:5000:1222222"
	ref, err = ParseReference(s)
	is.NoError(err)
	is.Equal("myrepo/mychart:5000", ref.Repo)
	is.Equal("1222222", ref.Tag)
	is.Equal("myrepo/mychart:5000:1222222", ref.FullName())
```

It's work 😄 

I can push P.R. if nobody work on it?

**Comment by bridgetkromhout** [comment]
Hi, @Prims47 - we closed the PR https://github.com/helm/helm/pull/8199 due to inactivity and failure to address comments.

So this bug still exists, but the current work on it is (as far as I can tell) stalled and should be resumed.

**Comment by Haim-Bi** [comment]
Hi,
I think the bug still occures. 
i have image xxx.azurecr.io/helm/schema-service:0.1.0
and get the same error.
`.\environment-executables\helm.exe version
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
`
`.\environment-executables\helm.exe dependency update .\install\clipper\
Getting updates for unmanaged Helm repositories...
...Unable to get an update from the "oci://xxx.azurecr.io/helm" chart repository:
        tag explicitly required
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "kubernetes-dashboard" chart repository
...Successfully got an update from the "traefik" chart repository
...Successfully got an update from the "grafana" chart repository
...Successfully got an update from the "bitnami" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading schema-service from repo oci://xxx.azurecr.io/helm
0.1.0: Pulling from xxx.azurecr.io/helm/schema-service
Deleting outdated charts`
![image](https://user-images.githubusercontent.com/65607826/117779677-93619480-b247-11eb-9bd8-856dacfe74ff.png)

**Comment by bacongobbler** [comment]
This should be fixed in Helm 3.7+ with the recent changes to the OCI getter implementation. `helm chart pull` has been removed entirely in favour of Helm's `getter` mechanism. Now you can pull charts from an OCI registry similar to a chart repository.

To fetch the latest release:

```
helm fetch oci://myregistry.azurecr.io/myapp
```

To fetch v1.0.0:

```
helm fetch oci://myregistry.azurecr.io/myapp --version v1.0.0
```

See https://helm.sh/docs/topics/registries/ for more information.

**Comment by SteveLasker** [comment]
@bacongobbler, as the use of `--version`, vs. `:version` has caused a bit of confusion for users, can we capture here why `helm pull oci://myregistry.com/myapp:v1.0.0` doesn't work and why --version is required?

**Comment by jdolitsky** [comment]
Please see https://helm.sh/docs/topics/registries/#other-subcommands

> In all cases, the --version flag is strictly required, since we are not yet able to reliably determine the latest semantic version for a given chart from a registry.

This does not address the `:` vs. `--version`, that is better described in HIP 6: https://github.com/helm/community/blob/main/hips/hip-0006.md#3-chart-versions--oci-reference-tags

**Comment by SteveLasker** [comment]
Thanks @jdolitsky 
Does the helm team have a list of these types of issues that might be addressed in a future version? Or, a list of dependencies it might need to be supported within the OCI or ORAS specs?

**Comment by jdolitsky** [comment]
@SteveLasker - not that I know of, but we may wish to capture this in a new issue.

This issue, as well as arbitrary tags, and digest validation are top of mind

**Comment by jdolitsky** [comment]
* and version/semver resolution

**Comment by SteveLasker** [comment]
The search api is another. I'm wondering if the _tags API can be used to get a list of chart versions.
Although, _catalog was moved to reserved as not all registries support it.
I do wonder if the extensions proposal can provide the flexibility needed to add a helm extension, or hopefully just a generic extension for a list of repos or `artifactTypes`
Anyway, capturing a list of "what's needed next in OCI support" would be super helpful to point users to, and help others figure out what/how they can contribute.

**Comment by jdolitsky** [comment]
@SteveLasker please see https://github.com/helm/helm/issues/10312 and share with others
