### ISSUE TITLE
helm repo add --repository-cache not considered 

### ISSUE THREAD

**Issue by cridam** [helm/helm#8100]
helm3 (tested with 3.1.3 or 3.2.1)

helm3 repo add test https://xxxx --repository-config /tmp/test/repositories.yaml  --repository-cache /tmp/test/repository

repo correctly added into the  fresh repositories.yaml into in /tmp/test
but cache is not copied under /tmp/test/repository , but still created under $XDG_CACHE_HOME
PS: even if directory /tmp/test/repository does exist before.
Also tested with sub directories of XDG_CACHE_HOME. it fails too.

**Comment by bacongobbler** [comment]
transferring to helm/helm.

**Comment by technosophos** [comment]
Verified that it is a duplicate. There is an open PR that is stalled, but will hopefully make it into 3.3.0. Closing this so that all discussion can continue on #7141. Thanks!
