### ISSUE TITLE
Helm sometimes fails to delete post-install/post-upgrade job

### ISSUE THREAD

**Issue by jabdoa2** [helm/helm#8101]
Similar to #1769 we sometimes cannot upgrade charts because helm complains that a post-install/post-upgrade job already exists:

```
ERROR: Failed to install helm chart on namespace: xxxxx
Reason: Error: UPGRADE FAILED: post-upgrade hooks failed: warning: Hook post-upgrade build/charts/minio/templates/post-install-create-bucket-job.yaml failed: jobs.batch "minio-make-bucket-job" already exists
```

Chart used: https://github.com/helm/charts/blob/master/stable/minio/templates/post-install-create-bucket-job.yaml:

```
apiVersion: batch/v1
kind: Job
metadata:
  # [...]
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
  # [...]
```

The job successfully ran though but we get the error above on update:

```
$ kubectl describe job minio-make-bucket-job -n xxxxx
Name:           minio-make-bucket-job
Namespace:      xxxxx
Selector:       controller-uid=23a684cc-7601-4bf9-971e-d5c9ef2d3784
Labels:         app=minio-make-bucket-job
                chart=minio-3.0.7
                heritage=Helm
                release=xxxxx
Annotations:    helm.sh/hook: post-install,post-upgrade
                helm.sh/hook-delete-policy: hook-succeeded
Parallelism:    1
Completions:    1
Start Time:     Mon, 11 May 2020 15:28:52 +0200
Completed At:   Mon, 11 May 2020 15:40:46 +0200
Duration:       11m
Pods Statuses:  0 Running / 1 Succeeded / 0 Failed
Pod Template:
  Labels:  app=minio
           controller-uid=23a684cc-7601-4bf9-971e-d5c9ef2d3784
           job-name=minio-make-bucket-job
           release=xxxxx
```
There is no running pod for that job. It is just the job which exists in the cluster.

Output of `helm version`:
`version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}`

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T11:52:47Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"1bea6c00a7055edef03f1d4bb58b773fa8917f11", GitTreeState:"clean", BuildDate:"2020-02-11T20:05:26Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Kubernetes 1.15.10 installed using KOPs on AWS

Is there a workaround for this except manually deleting the job?

**Comment by bacongobbler** [comment]
Hooks are considered un-managed by Helm. Once a hook is created, it is up to the cluster administrator to clean those up.

That being said, there are hook deletion policies available to help assist in some regards. Have a look at the documentation for more options. https://helm.sh/docs/topics/charts_hooks/#hook-deletion-policies

Hope this helps.

**Comment by jabdoa2** [comment]
The deletion policy is set inside the chart. It just does not always work in helm 3. It definitely did work fine in helm 2. We got this bug repeatedly every other day
