### ISSUE TITLE
Azure AD authentication adds excessive 'spn:' to `apiserver-id:` value in kubeconfig.yaml

### ISSUE THREAD

**Issue by joelrbrandt** [helm/helm#8104]
Each time I run a helm command that interacts with my cluster (e.g. `helm list`) helm prepends the string `spn:` to the value of the `users[n].user.auth-provider.config.apiserver-id` property in my kubeconfig.yaml

After enough `spn:`s are added, I eventually get an authentication error, and have to go remove all of them.

I believe this is identical to this (now resolved) kubectl issue:
https://github.com/kubernetes/kubernetes/issues/89672

I have confirmed that I am using the latest versions of helm (v3.2.1) and kubectl (v1.18.2)

Output of `helm version`:
```
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a17149e1a189050796ced469dbd78d380f2ed5ef", GitTreeState:"clean", BuildDate:"2020-04-16T11:36:15Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

**Comment by joelrbrandt** [comment]
Downgraded to helm v3.1.3 and issue does **not** reproduce.

Output of `helm version`:
```
version.BuildInfo{Version:"v3.1.3", GitCommit:"0a9a9a88e8afd6e77337a3e2ad744756e191429a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

Output of `kubectl version` (same as before):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a17149e1a189050796ced469dbd78d380f2ed5ef", GitTreeState:"clean", BuildDate:"2020-04-16T11:36:15Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by bacongobbler** [comment]
I wonder if the recent upgrade to kubectl 1.18 caused this.

https://github.com/helm/helm/pull/7831

If you modify the kubectl dependencies to 1.18.2 and re-compile Helm, does anything change?

https://github.com/helm/helm/blob/bf12ae39344aef012927ab391eb26ddd3a30ae30/go.mod#L37-L43

**Comment by bacongobbler** [comment]
Can you test https://github.com/helm/helm/pull/8112 and see if that fixes your issue?

**Comment by bacongobbler** [comment]
I'm going to assume this was fixed after merging https://github.com/helm/helm/pull/8112. Please test the canary release and let us know if this is not the case. Thanks!

**Comment by joelrbrandt** [comment]
@bacongobbler thanks for jumping on this so quickly!

**Comment by joelrbrandt** [comment]
@bacongobbler just tested with canary build @ decab8ea2e6ea4b31560aff50abb2676a67ec8ba on macOS and can confirm the issue is resolved. Thank you!

```
$ ./helm version
version.BuildInfo{Version:"v3.2+unreleased", GitCommit:"decab8ea2e6ea4b31560aff50abb2676a67ec8ba", GitTreeState:"clean", GoVersion:"go1.14.2"}
```

**Comment by GarrettGeorge** [comment]
@bacongobbler Is this fix contained in any of the newest stable releases?
