### ISSUE TITLE
[code review] helm/pkg/plugin/plugin.go#LoadAll function

### ISSUE THREAD

**Issue by liuming-dev** [helm/helm#8105]
https://github.com/helm/helm/blob/bf12ae39344aef012927ab391eb26ddd3a30ae30/pkg/plugin/plugin.go#L174-L199

https://github.com/helm/helm/blob/bf12ae39344aef012927ab391eb26ddd3a30ae30/pkg/plugin/plugin.go#L161-L172

---

*Here we have already get every plugin's `plugin.yaml` absolute path.*
https://github.com/helm/helm/blob/bf12ae39344aef012927ab391eb26ddd3a30ae30/pkg/plugin/plugin.go#L181

*I wonder why we not use the already known variable `yaml ` that is the `plugin.yaml` absolutely path directly? why we have to compute the path again in function `LoadDir` again? it seems cumbersome in code implementation.*
https://github.com/helm/helm/blob/bf12ae39344aef012927ab391eb26ddd3a30ae30/pkg/plugin/plugin.go#L190-L192

Therefore, is it possible to extract the main logic from `LoadDir` to a new function `LoadFile` with parameters`(pluginDir, pluginYaml string)`, `pluginDir` is the concrete plugin dir, `pluginYaml` is the concrete plugin's `plugin.yaml` absolute path.

**Comment by bacongobbler** [comment]
Is this just a code refactor? I'm having a hard time understanding what this is intended to fix, if anything. Is this just a quality-of-life improvement for this section of the codebase, or is there an actual issue here?

**Comment by liuming-dev** [comment]
> Is this just a code refactor? I'm having a hard time understanding what this is intended to fix, if anything. Is this just a quality-of-life improvement for this section of the codebase, or is there an actual issue here?
yes, this is just a code refactor for qualify-of-life improvement.
