### ISSUE TITLE
helm template --output-dir issue with nested template directory

### ISSUE THREAD

**Issue by vishaltak** [helm/helm#8107]
Output of `helm version`: version.BuildInfo{Version:"v3.1.0", GitCommit:"b29d20baf09943e134c2fa5e1e1cab3bf93315fa", GitTreeState:"clean", GoVersion:"go1.13.7"}

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"1bea6c00a7055edef03f1d4bb58b773fa8917f11", GitTreeState:"clean", BuildDate:"2020-02-11T20:05:26Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Self-hosted cluster on AWS using KOPS

There seems to be an issue with `helm template` while saving charts with nested templates like [ingress-nginx](https://github.com/kubernetes/ingress-nginx/tree/master/charts/ingress-nginx). The templates for this chart are placed in multiple nested directories, namely, `templates`, `templates/admission-webhooks` and `templates/admission-webhooks/job-patch`. The templates are rendered properly, however only the templates within `templates` and `templates/admission-webhooks` are saved when using the option `--output-dir`. The templates within `templates/admission-webhooks/job-patch` are not saved but rendered to the `stdout`. This causes issues as we are rendering the template through helm and performing a `kubectl apply` and since the templates within `templates/admission-webhooks/job-patch` are not saved, they don't get applied.

When I do a helm upgrade directly(had to upgrade another company chart with ingress-nginx where we use helm install/upgrade directly, unlike above), all the templates are installed/upgraded properly. There seems to a problem only while saving the nested templates to the output directory.

`helm template --output-dir` is already supporting 1 level of nested directory. Can we extend it further? Can we also document it somewhere and showcase it in `lint` commands that the maximum allowed nested directories within `templates` is `x`.

**Comment by M3t0r** [comment]
I think this is a duplicate of #7836. I encountered a similar problem with the Prometheus Operator chart, which had a subdirectory exclusively for templates with hooks which weren't rendered. The fix was released with Helm 3.3.0.

If you still have this project, make sure you are using 3.3.0 or the files in your subdirectory don't have hooks like this:
```yaml
metadata:
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "before-hook-creation"
```

**Comment by vishaltak** [comment]
Hey, I'm occupied until next week. I'll install 3.3.0 and verify it ASAP. Thanks.

**Comment by vishaltak** [comment]
Apologies for the delayed response. I can confirm that it has been fixed. Tried the following command with 2 different version of Helm for [ingress-nginx](https://github.com/kubernetes/ingress-nginx/tree/master/charts/ingress-nginx) chart
```
helm template test ./ --output-dir ./boo
```
Issue present in the following version
Criteria: no folder `boo/ingress-nginx/templates/admission-webhooks/job-patch`
```
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

Issue solved in the following version
Criteria: files are present in the folder `boo1/ingress-nginx/templates/admission-webhooks/job-patch`
```
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}
```

Thank you
