### ISSUE TITLE
fix: `Storage`should be init with Log function having concrete logic rather than a empty body

### ISSUE THREAD

**Issue by liuming-dev** [helm/helm#8108]
https://github.com/helm/helm/blob/bf12ae39344aef012927ab391eb26ddd3a30ae30/pkg/storage/storage.go#L254-L263

`Storage` is init with Log function with empty body that do nothing, and the caused result is that helm will never record log messages of  `Storage` functions, we will lost these helped messages.

Therefore, `Storage` should be init with a concrete log function to record there messages.

**Comment by bridgetkromhout** [comment]
Hi, @liuming-dev - as noted in https://github.com/helm/helm/pull/8082#pullrequestreview-489827882 your approach needs some redesign. As you do appear to be actively working on it, I'll remove the "Stale" marker on this issue.

It may be a good idea to talk through more of the implementation in this issue, so you can implement something that avoids the previous design constraints - thanks.
