### ISSUE TITLE
helm .Capabilities.KubeVersion giving unexpected results

### ISSUE THREAD

**Issue by gaurav34065** [helm/helm#8113]
Not sure if anyone faced the same issue before, While getting the kube version in helm chart using `{{ .Capabilities.KubeVersion.Minor }}` , It's not resolving it correctly. Always output value as 16.

As per my kube server version, i am expecting it to resolve as 18.

Output of `helm version`:
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}

Can someone point me in the right direction here on what's missing.
Please let me know if you need any more info.

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.10", GitCommit:"37d169313237cb4ceb2cc4bef300f2ae3053c1a2", GitTreeState:"clean", BuildDate:"2019-08-19T10:52:43Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:30:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS cloud
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"

**Comment by bacongobbler** [comment]
Hi @gaurav34065. Not enough information is provided here. Please provide a sample chart to reproduce the issue. Thanks.

**Comment by bacongobbler** [comment]
We will also require the commands you used to demonstrate this issue. I can't tell if this is with `helm template`, `helm install`, `helm install --dry-run`, `helm upgrade` or something else.

**Comment by gaurav34065** [comment]
@bacongobbler  You can use [this](https://github.com/gaurav34065/helm-gauth) chart to reproduce.
`helm template gauth-proxy --debug --kubeconfig myconfig.conf` will result in 
---
# Source: gauth-proxy/templates/deployment.yaml
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: "gauth-proxy-gaurav-deployment"

But expected is 

---
# Source: gauth-proxy/templates/deployment.yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: "gauth-proxy--deployment"

It should use the if condition since my kubeversion is 18.

When we try to print the value it results in 16 thus else condition gets executed.
I print it like below 

> kind: Deployment
{{- if and ( eq (int .Capabilities.KubeVersion.Major) 1) ( gt (int .Capabilities.KubeVersion.Minor) 16 ) }}
apiVersion: apps/v1
{{- else }}
apiVersion: apps/v1beta2  {{ .Capabilities.KubeVersion.Minor }}
{{- end }}

Result:
> ---
# Source: gauth-proxy/templates/deployment.yaml
kind: Deployment
apiVersion: apps/v1beta2 16
metadata:
  name: "gauth-proxy-gaurav-deployment"

**Comment by gaurav34065** [comment]
Also, helm upgrade command fails due to the same issue. Since it  couldn't find apiVersion: apps/v1

**Comment by bacongobbler** [comment]
See #8115.

**Comment by bacongobbler** [comment]
FYI,

> As per my kube server version, i am expecting it to resolve as 18.

If you want `helm template` to resolve to your current cluster's version, use the `--validate` flag. This will tell Helm to fetch available API versions from the Kubernetes cluster set in your current context. Otherwise it uses a mock version.

Using your example,

```
><> helm template ./gauth-proxy --validate --show-only templates/deployment.yaml | head -n 4
---
# Source: gauth-proxy/templates/deployment.yaml
kind: Deployment
apiVersion: apps/v1
```

**Comment by bacongobbler** [comment]
Closing as answered, as the original requirements were to match the current cluster's confguration, which can be performed with the `--validate` flag. PR #8115 will make the mocked kube version match what is used as the current kubernetes libraries, but it does not resolve the issue described here, as once updates occur to the kubernetes cluster and you're on k8s 1.19, the same issue will present itself again. For your use case, please use the `--validate` flag. Thanks.

**Comment by consideRatio** [comment]
Related EKS issue opened now: https://github.com/aws/eks-distro/issues/1128

**Comment by consideRatio** [comment]
For reference, this is the kind of corrupt data .Capabilities were populated with.

```
.Capabilities.KubeVersion: v1.22.9-eks-a64ea69
.Capabilities.KubeVersion.Major: 1
.Capabilities.KubeVersion.Minor: 22+
```

But even with such data, you can avoid issues with...

```
{{- if semverCompare ">=1.24.0-0" .Capabilities.KubeVersion }}
```
