### ISSUE TITLE
helm command error, dyld: Symbol not found

### ISSUE THREAD

**Issue by luxuze** [helm/helm#8119]
![image](https://user-images.githubusercontent.com/35137889/81885036-0b14c900-95cc-11ea-89b8-befa5a45def4.png)

<img width="681" alt="image" src="https://user-images.githubusercontent.com/35137889/81885088-28e22e00-95cc-11ea-9a59-09a3c67f311c.png">

**Comment by bacongobbler** [comment]
Hi @luxuze. I don't have enough information here to determine what you expect us to fix. Please provide more information.

**Comment by luxuze** [comment]
I had fix this problem by brew install helm. thanks.
