### ISSUE TITLE
wait parameter: deployment error not detected when pv claim exceeds quota

### ISSUE THREAD

**Issue by gerrnot** [helm/helm#8121]
Output of `helm version`:
Client: &version.Version{SemVer:"v2.16.6", GitCommit:"dd2e5695da88625b190e6b22e9542550ab503a47", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.6", GitCommit:"dd2e5695da88625b190e6b22e9542550ab503a47", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
minikube version: v1.6.2
commit: 54f28ac5d3a815d1196cd5d57d707439ee4bb392

### Introduction

According to documentation the --wait parameter should make the helm command wait till all pods are in a ready state. Undocumented in the --help string is the behaviour that the helm command fails with a non-zero exit code if the pods are not in ready state within the period the is passed via the --timeout parameter. This is all good - but I found a defect, where the deployment error is not detected.

In particular the error happens if a statefulset is requesting more storage than what is provided by the kubernetes cluster quota. Then the pods are not even able to be started but helm thinks everything is fine.

### Steps to reproduce

[reproduce.zip](https://github.com/helm/helm/files/4626754/reproduce.zip)

Extract attach zip file and run reproduce.sh (e.g. against minikube version listed above).

### Expected Result

helm installation fails with non-zero exit code. This should be the case because subchart-2 requests `size: 10000Gi`, which is not allowed per quota (quota definition is part of umbrella-chart). Anyhow - the pods are not even started and therefore the deployment should not succeed.

### Actual Result

helm installation succeeds with following output:
```
helm upgrade --install --wait --atomic --timeout 60 umbrella-chart umbrella-chart-202009.28.0.tgz
Release "umbrella-chart" does not exist. Installing it now.
NAME:   umbrella-chart
LAST DEPLOYED: Thu May 14 09:26:56 2020
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/Pod(related)
NAME          READY  STATUS   RESTARTS  AGE
subchart-1-0  1/1    Running  0         40s
subchart-1-1  1/1    Running  0         40s
subchart-1-0  1/1    Running  0         40s
subchart-1-1  1/1    Running  0         40s

```
notice that the two replicas of subchart-1-1 are listed TWICE above!

**Comment by jdolitsky** [comment]
cc @thomastaylor312

**Comment by gerrnot** [comment]
@thomastaylor312 : I saw you were referenced by @jdolitsky, so there seems having been some interal coordination already - just asking if there is maybe already a status update.

**Comment by thomastaylor312** [comment]
Nope, nothing here on my end. Definitely looks like an unhandled edge case, so any PRs welcome!

**Comment by bridgetkromhout** [comment]
Hi, @gerrnot - thanks for reporting this issue. Can you let us know if you can reproduce this issue with Helm 3? We are no longer providing support for Helm 2 as of today: https://helm.sh/blog/helm-2-becomes-unsupported/
