### ISSUE TITLE
HELM_DRIVER secret and rbac

### ISSUE THREAD

**Issue by mraszplewicz** [helm/helm#8122]
Output of `helm version`:
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"1bea6c00a7055edef03f1d4bb58b773fa8917f11", GitTreeState:"clean", BuildDate:"2020-02-11T20:13:57Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Minikube, EKS

Hi!

I am trying to restrict credentials using RBAC. I realized that every time I deploy a new release helm adds a new secret with suffix vX (v1, v2...). I don't think it is possible to restrict permissions using resource names (https://github.com/kubernetes/kubernetes/issues/56582), so if user needs to use helm, I have to grant full secret permissions in a given namespace. Is it possible to use secret storage backend without adding full permissions for all secret in a namespace?

Thanks for help!

**Comment by bacongobbler** [comment]
As far as I'm aware, there is not a machanism available in Kubernetes to restrict RBAC to a particular subset of resources based on their name, labels, etc. It's all or nothing.

https://helm.sh/docs/topics/rbac/
https://kubernetes.io/docs/reference/access-authn-authz/rbac/

Let us know if you find out anything.

**Comment by mraszplewicz** [comment]
@bacongobbler thanks for your answer.

The issue which I've mentioned (https://github.com/kubernetes/kubernetes/issues/56582) is exactly about adding some capability to Kubernetes RBAC, to be able to restrict permissions by name pattern or label. It is closed without resolution. So yes it is not possible in Kubernetes and probably will not be.

My question is more about Helm - is it possible to not grant user to read/write all secrets in a namespace to use helm? Maybe secret names without incrementing suffix or secrets in some other namespace?

I am asking this question because I think that secrets contain most of the time some sensitive information and I consider it unsecure to grant to much permissions to them.

**Comment by bacongobbler** [comment]
Helm inherits role-based access controls from Kubernetes, so if Kubernetes does not provide a way for users to restrict visibility to a certain subset of secrets in a given namespace, then helm cannot either. This is something that has to be handled upstream as it affects all tooling that relies on Kubernetes' access controls, not just Helm.

Hope this helps.

**Comment by mraszplewicz** [comment]
I am aware that helm uses Kubernetes RBAC and nothing more and I really like it (it was somehow problematic in helm 2).

I can have multiple secrets in my namespace which are not helm related like api keys, database passwords etc. I know the names of all of these secrets and I can restrict permissions using rbac by name. Helm is generating new secret names all the time so I can't restrict permissions by name. For example: if I want to allow my user X to use helm in namespace A, I also have to grant user X permissions to read and write api keys and database passwords in namespace A.

**Comment by bacongobbler** [comment]
> Don't you think it is I a quite serious security issue?

No. Most users segregate read/write permissions based on the namespace, not based on some string prefix. That has been good enough for 99% of users.

**Comment by mraszplewicz** [comment]
Maybe most users do not think about security. I have never written that I want to segregate permissions based on string prefix. I want to do it exactly by name. With helm I can't because it is generating new names all the time.

**Comment by mraszplewicz** [comment]
In other words:
I want to be able to do ```helm ls```
Do I really need permissions to read all secrets?
