### ISSUE TITLE
helm upgrade failed when k8s object version changed.

### ISSUE THREAD

**Issue by Shobhit29** [helm/helm#8126]
Output of `helm version`: helm 3.2.1

Output of `kubectl version`: `Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.12", GitCommit:"a8b52209ee172232b6db7a6e0ce2adc77458829f", GitTreeState:"clean", BuildDate:"2019-10-15T12:04:30Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  On premise k8s cluster

I changed the k8s object version for my **deployment object** from `apiVersion: extensions/v1beta1` to `apiVersion: apps/v1`. I tried to upgrade my release and it failed with the error saying

`helm3 upgrade master-ci Chart --namespace dev --install --timeout 15m0s --debug --history-max 2 -f my-values.yaml 
 history.go:52: [debug] getting history for release master-ci
 upgrade.go:121: [debug] preparing upgrade for master-ci
 upgrade.go:129: [debug] performing update for master-ci
 Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. Unable to continue with update: Deployment "chart-master-ci" in namespace "dev" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "master-ci"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "dev"
 helm.go:84: [debug] Deployment "chart-master-ci" in namespace "dev" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "master-ci"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "dev"
 rendered manifests contain a resource that already exists. Unable to continue with update`

**Comment by bacongobbler** [comment]
Have you tried applying the annotations to the objects described in the error?

**Comment by Shobhit29** [comment]
No

**Comment by bacongobbler** [comment]
Kubernetes treats apiVersions separate from each other, and therefore a resource cannot be upgraded from one to another. There are closed tickets in the Helm queue that go into more detail about this behaviour, and why Helm cannot upgrade resources from one api version to the next.

Hope this helps.

**Comment by bacongobbler** [comment]
for example: #7219
