### ISSUE TITLE
Tests not updated with upgrade

### ISSUE THREAD

**Issue by alexgeek** [helm/helm#8128]
Hi there,

It seems like changing the command of a test job doesn't update the job spec after running helm upgrade. I can probably do the the annotation with a random number to get around that (not tried yet) but I'm assuming this is a bug and thought I would report it.

Thanks,
Alex

Output of `helm version`:
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}

Output of `kubectl version`:
lient Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.5-gke.0", GitCommit:"96891985a805dc058939eaddd98601988512add9", GitTreeState:"clean", BuildDate:"2020-04-16T23:58:08Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

**Comment by bacongobbler** [comment]
Can you please provide more information? There's not enough information here to determine what may be causing the issue. Thanks.

**Comment by alexgeek** [comment]
If I change the command on job specification with the helm test hook it does not update the configuration of that job. 

E.g. 

Before with: (run helm upgrade --install && helm test)

```
command: [ "/bin/bash", "-c", "echo hello" ]
```

After with: (run helm upgrade --install && helm test)

```
command: [ "/bin/bash", "-c", "ls /this/should/fail" ]
```

If i do a `kubectl describe job` the command hasn't changed. No errors in upgrade and the test still succeeds.

**Comment by bacongobbler** [comment]
@alexgeek thank you. I'm looking for a specific test case we can use to reproduce the issue locally.

**Comment by alexgeek** [comment]
> @alexgeek thank you. I'm looking for a specific test case we can use to reproduce the issue locally. A sample chart with a set of steps would be helpful.

Unfortunately  the chart I'm working is closed source. Let me see if I can repro in a new blank chart.

Side note, addding the annotation `rollme: {{ randAlphaNum 5 | quote }}` doesn't fix it.

**Comment by alexgeek** [comment]
I can't repro in a blank chart so assume it's something weird and specific to mine. I'll close for now. Thanks for replying though.
