### ISSUE TITLE
helm tpl question

### ISSUE THREAD

**Issue by vignesh-v-nutanix** [helm/helm#8129]
/p/t/test  helm version --short                                                                                                                  16.1s  Thu May 14 23:52:10 2020
Client: v2.16.7+g5f2584f
Server: v2.16.1+gbbdfe5e

 /p/t/test  kubectl version --short                                                                                                              3553ms  Thu May 14 23:52:19 2020
Client Version: v1.16.9
Server Version: v1.16.8

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AWS

What does L8,9,14 does?
tried to read up this https://helm.sh/docs/chart_template_guide/accessing_files/

But still cannot understand.. I don't have any file by name .secret in the path and also the person who wrote have moved on. Hence need to get this

```     1	{{/*
     2	    Name: trucCommon.secrets
     3	    Params:
     4	        .namespace: namespace for this app
     5	        .secrets: a listing of sercrets
     6	*/}}
     7	{{- define "trucCommon.secrets" -}}
     8	{{- $namespace := .namespace -}}
     9	{{- $secrets := .secrets -}}
    10	{{- range $sec := $secrets }}
    11	apiVersion: v1
    12	kind: Secret
    13	metadata:
    14	  name: {{ $sec.name }}
    15	  namespace: {{ $namespace }}
    16	type: {{ $sec.type }}
    17	data:
    18	  {{- if eq $sec.type "kubernetes.io/dockerconfigjson" }}
    19	  .dockerconfigjson: {{ printf "\"%s\"" (include "trucCommon.imagePullSecret" $sec.data) }}
    20	  {{- else if or (eq $sec.type "Opaque") (eq $sec.type "generic") }}
    21	  {{- range $key, $val := $sec.data }}
    22	  {{ $key }}: {{ $val | b64enc }}
    23	  {{- end }}
    24	  {{- else }}
    25	    error: {{ .unsupported_secret_type }}
    26	  {{- end }}```

**Comment by bacongobbler** [comment]
I tried searching for the template you referenced and cannot find it on the page you linked to. Can you please point out where you found this template? Thanks.

**Comment by bacongobbler** [comment]
lines 8 and 9 assign the value to a variable. Line 14 uses that variable.

You might have better luck reading up on named templates, which can be found here. https://helm.sh/docs/chart_best_practices/templates/#names-of-defined-templates

**Comment by bacongobbler** [comment]
Good luck!

**Comment by vignesh-v-nutanix** [comment]
@bacongobbler Hi, My question is what are the values.. what does .secret and .namespace refer to or have as values?
Many question in slack channels don't get answered. thank you

**Comment by bacongobbler** [comment]
Without a link to the chart, I cannot help you.

**Comment by vignesh-v-nutanix** [comment]
hi @bacongobbler , this was written by one of our peers but as i said earlier he has moved on. 

the above file is referenced i think as
```{{ template "sherlockCommon.secrets" (dict "namespace" .Values.global.cloud_namespace "secrets" .Values.secrets) }}```

But still my question is what does .secrets and .namespace have in L8 and L9

**Comment by bacongobbler** [comment]
The output of [`dict`](http://masterminds.github.io/sprig/dicts.html) is a dictionary. In your case, `.secrets` is equivalent to the output of `.Values.secrets`, and `.namespace` will be the output of `.Values.global.cloud_namespace`. Have a look in your values file to determine what those fields are set to.

https://helm.sh/docs/chart_template_guide/values_files/
