### ISSUE TITLE
Same Chart Different Release

### ISSUE THREAD

**Issue by reidlai** [helm/helm#8133]
With Helm 2, I can deploy same chart with different release name with --name parameter
When i try to use same method to deploy using Helm 3 I got this error 

```
helm install nginx-ingress-internet nginx-stable/nginx-ingress --namespace=nginx-ingress --set controller.name="nginx-ingress-internet" --set controller.electionID="nginx-ingress-internet" --set controller.ingressClass="nginx-internet" --set controller.service.type="NodePort"

Error: rendered manifests contain a resource that already exists. Unable to continue with install: CustomResourceDefinition "transportservers.k8s.nginx.org" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "nginx-ingress-internet": current value is "nginx-ingress-intranet"
```

**Comment by bacongobbler** [comment]
The error points out the fact that a resource with the same name already exists in the cluster. Helm cannot "adopt" resources that already existed in the cluster.

In your case, you have a CustomResourceDefinition named `transportservers.k8s.nginx.org` that has already been installed and is being managed by the `nginx-ingress-intranet` release. Another chart cannot install the same CRD twice.

With the arrival of Helm 3, we removed the old `crd-install` hooks for a more simple methodology. There is now a special directory called `crds` that you can create in your chart to hold your CRDs. These CRDs are not templated, but will be installed by default when running a `helm install` for the chart. If the CRD already exists, it will be skipped with a warning. If you wish to skip the CRD installation step, you can pass the `--skip-crds` flag.

More info can be found [in the docs](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you).

Hope this helps.

**Comment by reidlai** [comment]
thx....let me think how to implement two ingress controller with different name then

**Comment by bacongobbler** [comment]
closing as answered. Please let us know if you have any further questions.

**Comment by nick-cromwell** [comment]
@reidlai I'm having this issue as well with nginx on v3 - worked with Helm v2. Did you find a quick solution?

**Comment by nick-cromwell** [comment]
Just a quick mention of how I got around this today. Based on my understanding of the Nginx TransportServer CR it is not yet production ready and only available as a preview.

[Transport Server reference](https://docs.nginx.com/nginx-ingress-controller/configuration/transportserver-resource/#)

So I just removed it and the other Virtual Server CRs installed by the nginx-stable/nginx-ingress chart like so:

`kubectl delete crd transportservers.k8s.nginx.org`
`kubectl delete crd virtualservers.k8s.nginx.org`
`kubectl delete crd virtualserverroutes.k8s.nginx.org`

Doing this resolved any conflict and allowed me to install my second Ingress Controller with a different release name. However, I have not yet tested it.

I believe this is an issue with the Nginx chart, I even set `--skip-crds` on my ingress install. I don't think the CRs are honoring the release name correctly but this is not my area of expertise. I'll follow up with an issue at Nginx.

**Comment by reidlai** [comment]
> @reidlai I'm having this issue as well with nginx on v3 - worked with Helm v2. Did you find a quick solution?

I may try to create different namespace....not sure if it works

**Comment by ufcurmcginty** [comment]
I'm having a similar issue on helm v3.7.0 using ingress-nginx/ingress-nginx instead of stable. 

The Virtual Server CRs aren't installed by ingress-nginx it would appear, so I can't use the workaround of deleting them. 

full error: 
Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: IngressClass "nginx" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "ingress-web-test": current value is "ingress-api-test"

**Comment by fableforester** [comment]
@ufcurmcginty wow, where did you even find this new parameter? I adapted our scripts and now it works with the current version. It was necessary to add the new parameters and adapt the spec of the Ingress Resource itself as well (removing the annotation "kubernetes.io/ingress.class", setting the "ingress_class_name" parameter in the spec instead).

Our release for the ingress controller now looks something like this (the four ingressClass-Parameters I took from the [documentation](https://kubernetes.github.io/ingress-nginx/)):

````
resource "helm_release" "nginx_ingress" {
  name       = var.module.name
  namespace  = var.module.namespace
  repository = "https://kubernetes.github.io/ingress-nginx"
  chart      = "ingress-nginx"

  set {
    name  = "controller.watchNamespace"
    value = var.module.namespace
  }

  set {
    name  = "controller.ingressClassResource.name"
    value = var.module.namespace
  }

  set {
    name  = "controller.ingressClassResource.controllerValue"
    value = "k8s.io/${var.module.namespace}"
  }

  set {
    name  = "controller.ingressClassResource.enabled"
    value = true
  }

  set {
    name  = "controller.ingressClassByName"
    value = true
  }

  set {
    name  = "controller.nodeSelector.\\beta\\.kubernetes\\.io/os"
    value = "linux"
  }
}
````

**Comment by FanerYedermann** [comment]
@fableforester & @ufcurmcginty 
I can't begin to tell you how helpful your last few comments were. 
Had the same issue with a version bump of nginx on a cluster, and this solved it. 

Thank you!

**Comment by mattduguid** [comment]
@fableforester & @ufcurmcginty solved it for me as well thanks, definitely required the combo of the 3 changes

**Comment by Krebsmar** [comment]
@fableforester Terraform Configration change worked for me. I have chart version 4.0.13 in use.
