### ISSUE TITLE
Feature: Add flag-gated solution for upgrading CRDs

### ISSUE THREAD

**Issue by frodopwns** [helm/helm#8139]
CRDs maintained with proper version compatibility can generally be upgraded safely.

https://book.kubebuilder.io/multiversion-tutorial/conversion-concepts.html

The Hub and Spoke model mentioned in the Kubebuilder project's documentation details a path to version compatibility that would allow CRDs to be upgraded in a safe manner. This would require all maintainers of CRDs to get on board for the best experience, so I am suggesting we add a flag that would let users who are confident in their solution bypass the current CRD functionality in order to get updates.

Suggested change:

Add this flag to `helm upgrade`

`--upgrade-crds`

which would perform the same sort of merging that `kubectl apply` currently does

This would allow users with CRD based solutions to have a smoother helm experience without having to use kubectl or kustomize to handle updates to CRDs.

**Comment by frodopwns** [comment]
I may have bandwidth to look at this. Wanted to put it up here for discussion first.

**Comment by bacongobbler** [comment]
hi @frodopwns. Have you had a chance to look at #5871 yet and how this proposal may be affected by that discussion?

You might also find this comment interesting: https://github.com/helm/helm/issues/7735#issuecomment-617795653

**Comment by frodopwns** [comment]
@bacongobbler there is an awful lot to catch up on

What I think I picked up on...

The main problems preventing the implementation of an upgrade or deletion solution appears to be about protecting users from other users. Ie. Chart/Operator consumers from the developers of those charts. This is problematic for users not in multi-tenant situations or users with fully compatible versioning solutions.

The outcome of this is that users are leaving helm in favor of straight kubectl/kustomize alternatives.

**Comment by frodopwns** [comment]
Actually I guess I see another issue with the ordering.

The operator has to be serving webhook endpoints in order for CRDs to be converted when the stored version is updated.

The way kustomize handles this...

Deploys CRDs with conversion.strategy = "none"

Then it updates the CRDs with conversion.strategy = "webhook" at the time it deploys the operator.

Not quite as straight-forward as I would like it to be.

**Comment by frodopwns** [comment]
I will read up and see if I still think I have a suitable solution in mind.

**Comment by bridgetkromhout** [comment]
Hi, @frodopwns - as the CRD discussion is being clarified in https://github.com/helm/community/pull/138 and this issue is inactive, I'm resolving it now. Thanks for your interest, and please weigh in on the ongoing discussion in https://github.com/helm/helm/issues/5871 if desired.
