### ISSUE TITLE
Update `heml version` documentation for `SemVer v3.x.y`

### ISSUE THREAD

**Issue by dazza-codes** [helm/helm#8144]
https://helm.sh/docs/helm/helm_version/ documentation for helm3 has a version string from helm2, i.e.

```
version.BuildInfo{Version:"v2.0.0", GitCommit:"ff52399e51bb880526e9cd0ed8386f6433b74da1", GitTreeState:"clean"}
```

```
$ snap info helm | grep installed
installed:          3.2.1             (232) 10MB classic

$ helm version
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

Whatever release process is building the documentation could be tweaked to update that version.

**Comment by bacongobbler** [comment]
https://github.com/helm/helm/blob/3779d959667095e03308a2e49480748f7911b228/cmd/helm/version.go#L36

**Comment by bacongobbler** [comment]
Thanks for pointing that out. I linked to the docstring in `helm help version` where that is located. Would you like to submit a patch for that?>

**Comment by bacongobbler** [comment]
We'll also need to point out the significance of `GoVersion`, as that was added for Helm 3.
