### ISSUE TITLE
Suppot scheme "local"

### ISSUE THREAD

**Issue by atsaur** [helm/helm#8145]
Some index.html of charts repo using relative path with "local://" scheme.  
Need to change normalizeURL() in pkg/downloader/manager.go.  Insert some code like:
func normalizeURL(baseURL, urlOrPath string) (string, error) {
	u, err := url.Parse(urlOrPath)
	if err != nil {
		return urlOrPath, err
	}
       //// Add local scheme support /////
	if u.Scheme == "local" {
		return baseURL + strings.TrimPrefix(u.String(), "local:/"), nil
	}
       //////////////////////////////////////////
       ...
}
 
Output of `helm version`: 
3.2.1

Output of `kubectl version`:
Not related

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
All

**Comment by bridgetkromhout** [comment]
Hi, @atsaur - we already support using a local path like `file://`; see https://github.com/helm/helm/issues/2103. If you're thinking about external files, then the issue you want to look at is https://github.com/helm/helm/issues/3276. 

Please let us know if you have further questions; thanks.
