### ISSUE TITLE
[Question/Support] pre-upgrade hook proceeds further when Job object is deleted

### ISSUE THREAD

**Issue by lukipro** [helm/helm#8146]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.16.3", GitCommit:"1ee0254c86d4ed6887327dabed7aa7da29d7eb0d", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.3", GitCommit:"1ee0254c86d4ed6887327dabed7aa7da29d7eb0d", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-11T12:41:00Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.7", GitCommit:"65ecaf0671341311ce6aea0edab46ee69f65d59e", GitTreeState:"clean", BuildDate:"2019-01-24T19:22:45Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):
```
Kops cluster on AWS
```

**Issue description**

We are using pre-upgrade hooks to do database migration and related tasks before we update our Deployements.

Today I encountered a situation where the pre-upgrade hook got into a "stuck state" where there was to chance for it to complete successfully. I could have either waited for it to timeout, or somehow "fail" it manually.
I decided to delete the pre-upgrade Job via `k delete -n xyz job app-stg01-pre-sync`.

I was surprised that the upgrade went along as if the pre-upgrade hook completed successfully.
Please see associated tiller logs:
```
[kube] 2020/05/16 09:56:53 Watching for changes to Job app-stg01-pre-sync with timeout of 1h0m0s
[kube] 2020/05/16 09:56:53 Add/Modify event for app-stg01-pre-sync: ADDED
[kube] 2020/05/16 09:56:53 app-stg01-pre-sync: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
[kube] 2020/05/16 09:56:53 Add/Modify event for app-stg01-pre-sync: MODIFIED
[kube] 2020/05/16 09:56:53 app-stg01-pre-sync: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
[kube] 2020/05/16 10:11:37 Deleted event for app-stg01-pre-sync.  # AT THIS POINT I DELETED THE JOB
[tiller] 2020/05/16 10:11:37 hooks complete for pre-upgrade xyz-app-stg01
[kube] 2020/05/16 10:11:37 building resources from updated manifest
```
 
Could someone please confirm if this is the desired behavior when deleting a pre-upgrade Job?
I couldn't find it anywhere in the docs.

Also, is there a proper way to manually invalidate a running pre-upgrade Job so that the upgrade fails?

Thanks!

**Comment by bacongobbler** [comment]
If I'm understanding correctly, you're asking if it's the intended behaviour that a hook "succeeds" if a pre-upgrade hook is manually deleted before running to completion. Is that correct?

**Comment by lukipro** [comment]
Yes, that is precisely what I meant.

**Comment by bridgetkromhout** [comment]
Hi, @lukipro -

Can you let us know if you can reproduce this issue with Helm 3? We are no longer providing support for Helm 2 as of today: https://helm.sh/blog/helm-2-becomes-unsupported/
