### ISSUE TITLE
Global flags no longer shown

### ISSUE THREAD

**Issue by marckhouzam** [helm/helm#8147]
I'm opening this issue to make sure this get properly tracked and fixed before the next release.

With #7917, global flags are no longer being shown in the main help text (running `helm` or `helm -h`).  This was first reported here https://github.com/helm/helm/pull/7917#issuecomment-626189561
This may be a good thing, as long as there is a way to see the global flags, which there isn't right now. 

Furthermore, the help text of each sub-command refers to a non-existant `helm <sub-command> options`.

For example:
```
$ helm status -h
[...]
Usage:
  helm status RELEASE_NAME [flags] [options]

Use "helm status options" for a list of global command-line options (applies to all commands).
```
but `helm status options` does not exist.

PR #8095 aims to fix that.

Output of `helm version`:
version.BuildInfo{Version:"v3.2+unreleased", GitCommit:"3779d959667095e03308a2e49480748f7911b228", GitTreeState:"dirty", GoVersion:"go1.13.7"}

**Comment by mattfarina** [comment]
@marckhouzam I see the global commands now. I've not looked but I wonder if merging #8153 fixed it.

**Comment by bacongobbler** [comment]
Yes. Sorry for not closing this. #8153 did indeed fix this and we confirmed yesterday on the dev call. Closing!

**Comment by marckhouzam** [comment]
I should have followed-up on closing to issues.  Sorry.
