### ISSUE TITLE
Proposal: `--dry-run` supports both helm-side and kubernetes-side dry-run

### ISSUE THREAD

**Issue by liuming-dev** [helm/helm#8148]
This is a proposal to support kubernetes-side `dry-run` when `install`, `upgrade` if `--dry-run` flag is specified.

**Background**

`dry-run` gives us the ability to know wether the yaml files are valid or not before we truely want to  change persistent  storage data. `helm install` and `helm upgrade` with `--dry-run` only run helm-side `dry-run` logic, this can avoid  lots of risks especially in production. 

However, even though helm dose it's side `dry-run`, it will be better to do kubernetes-side `dry-run`, this will help users find more potential problems of the yaml files, enhance user's confidence to install/upgrade a release.

When diving into the source code, it will make a breaking change to support this feature. If it could be supported, its's reasonable to support this in Helm 4, but is it possible to support in Helm 3?

**Comment by bridgetkromhout** [comment]
Hi, @liuming-dev - Thank you for proposing an improvement to Helm. If you'd like, you can submit a Helm Improvement Proposal so as to work in the community to make your ideas a reality: https://github.com/helm/community/blob/master/hips/hip-0001.md - meanwhile, I will close this issue. Thanks!
