### ISSUE TITLE
Revision flag missing in help for helm status

### ISSUE THREAD

**Issue by marckhouzam** [helm/helm#8149]
With the changes of #7917 , the help text for `helm status` no longer shows the `revision` flag.

My guess is that this is caused because helm status creates its revision flag as a PersistentFlag:
https://github.com/helm/helm/blob/3779d959667095e03308a2e49480748f7911b228/cmd/helm/status.go#L77

However, the kubectl package used to group commands, I'm guessing shows persistent flags in a `helm <subcommand> options`.

I think there is no need to use a persistent flag for `helm status --revision` (a persistent flag is a flag that is inherited by sub-commands).  Note that the `--revision` flags of the different `helm get` commands are not persistent.

Output of `helm version`:
version.BuildInfo{Version:"v3.2+unreleased", GitCommit:"3779d959667095e03308a2e49480748f7911b228", GitTreeState:"clean", GoVersion:"go1.13.7"}

/cc @zgfh

**Comment by mattfarina** [comment]
@marckhouzam I created #8183 to move it to a flag. I also noticed that the revision flag is showing up on the tip of master right now. Is this PR or issue still needed?

**Comment by marckhouzam** [comment]
> @marckhouzam I created #8183 to move it to a flag. I also noticed that the revision flag is showing up on the tip of master right now. Is this PR or issue still needed?

Since  #7917 was reverted, the bug has disappeared.  However, I think we might as well make the change to the revision flag anyway, as you have done in #8183, to remove the risk of this problem re-appearing.

**Comment by marckhouzam** [comment]
The revert was done in #8153

**Comment by marckhouzam** [comment]
> The revert was done in #8153

I'm closing this issue as the problem is gone, irrespective of what we decide to do about #8183.
