### ISSUE TITLE
Logic to identify if the POD is created first time/coming up due to manul delete or helm upgarde 

### ISSUE THREAD

**Issue by Mishra-Akash** [helm/helm#8154]
Hi Experts,

I have one scenario where I need to execute a few scripts only when I am applying my Upgrade to the pod(image change) via helm. And I don't want to run that script when there is a new POD creation or restart due to the manual deletion of the pod. 
Do we have any standard way to know either pod is getting coming up due to upgrade or it's due to newly install or manual delete?  

I don't want to use any flag-like the creation of files inside the pod and putting condition accordingly, 

If there is something that helm can notify so I can to decide whether I need to run the scrip tor not?

I am using Helm 2.

Thanks
    Akash

**Comment by bacongobbler** [comment]
This is not possible. Your hook will need to check your cluster’s state if you want some conditional logic.
