### ISSUE TITLE
Override env variables when packaging the chart

### ISSUE THREAD

**Issue by HoussemDellai** [helm/helm#8168]
Feature Request:
In most CI/CD pipelines, we update the image Tag. We use a step/task to replace the old tag with a new one. Then we create the package.
The idea would be to remove that intermediate step/task and override the tag when running the command package:
`$ helm package --set image.tag=2.0`
and output would be the package tgz with image tag 2.0.

**Comment by bacongobbler** [comment]
duplicate request of https://github.com/helm/helm/issues/3141. Please make sure to search for open issues before opening a new one. Thanks!
