### ISSUE TITLE
Add repo failing with "net/http: TLS handshake timeout"

### ISSUE THREAD

**Issue by sagarraob4u** [helm/helm#8172]
I am seeing below error:
Error: looks like "https://dl.bintray.com/pegasystems/pega-helm-charts" is not a valid chart repository or cannot be reached: Get https://dl.bintray.com/pegasystems/pega-helm-charts/index.yaml: net/http: TLS handshake timeout

helm version: v3.1.3.
tried with version v3.2.0 and v3.2.1 as well. same error.
Running on Mac OS: 10.3.6 (High Sierra)

_Originally posted by @sagarraob4u in https://github.com/helm/helm/issues/7808#issuecomment-631785225_

**Comment by hickeyma** [comment]
@sagarraob4u  Feedback from @inistor in https://github.com/helm/helm/issues/7808#issuecomment-631883144:

> Could you please try running the command with 'sudo'? Just to see that it's the same issue I've encountered.
Also, in my case, a build from source worked just fine - you may want to try that as well.

**Comment by sagarraob4u** [comment]
Thank you running with sudo seems working.
