### ISSUE TITLE
how to find files under a directory with helm-browse-project?

### ISSUE THREAD

**Issue by littlehome-eugene** [helm/helm#8180]
This is a question

https://emacs.stackexchange.com/questions/56161/how-to-find-files-under-a-directory-with-helm-browse-project

>  (helm-browse-project ARG)
> 
>  Preconfigured helm to browse projects.  Browse files and see status
> of project with its vcs.  Only HG and GIT are supported for now.  Fall
> back to ‘helm-browse-project-find-files’  if current directory is not
> under control of one of those vcs.  With a prefix ARG browse files
> recursively, with two prefix ARG  rebuild the cache.

So I tried c-u and helm-browse-project but it finds files for the root project. 
Is there a way to find files under a current directory where buffer is in?

**Comment by bacongobbler** [comment]
Wrong project - you’re looking for emacs-helm. This is the ticket queue for helm, the kubernetes package manager.
