### ISSUE TITLE
Panic in case of error other than "not exist"

### ISSUE THREAD

**Issue by MaxNosov** [helm/helm#8181]
https://github.com/helm/helm/blob/master/pkg/chartutil/save.go#L109

Throws panic if the error other than "not exist".
Stats returned as nil in case of error occurred but IsNotExist returned false.
In this case all other errors are ignored and dereferencing of stat throws panic.

Output of `helm version`: develop

Output of `kubectl version`: any

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  any

**Comment by bacongobbler** [comment]
It’s unclear what is the issue here as well as what’s the suggested action item to take here. Can you provide a use case where this becomes an issue? Thanks.

**Comment by MaxNosov** [comment]
The helm was used inside the pod with mounted PVC (network storage).
When mounted PVC failed (some problems with network or storage provider) the helm failed also with panic:
```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0xc0016bc3e0 addr=0x4e6fb7 pc=0x92a65b]
goroutine 125 [running]:
helm.sh/helm/v3/pkg/chartutil.Save(0xc002cec0a0, 0xc006019280, 0x1f, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/my-project/helm-repo/vendor/helm.sh/helm/v3/pkg/chartutil/save.go:110 +0x644
```
because os.Stat call returned error other than "not exist" (e.g. "input/output error")
and stat variable got nil value. So stat.IsDir() call throws panic.

Currently I cannot create fix and PR
but would like to propose next fix as solution to avoid panics:
```
        dir := filepath.Dir(filename)
	if stat, err := os.Stat(dir); err != nil {
		if os.IsNotExist(err) {
			if err := os.MkdirAll(dir, 0755); err != nil {
				return "", errors.Wrapf(err, "make dir %s", dir)
			}
		} else {
			return "", errors.Wrapf(err, "stat %s", dir)
		}
	} else if !stat.IsDir() {
		return "", errors.Errorf("is not a directory: %s", filepath.Dir(filename))
	}


```

**Comment by mattfarina** [comment]
@MaxNosov If there is an error other than `IsNotExist` the internal `else` is called returning the error. If there is an error `IsDir` is not reachable.

If this is happening it looks like stat is returning without an error. This could be because the filesystem cache allows `Stat` to return a non-error response.

**Comment by MaxNosov** [comment]
Please, take a look:
[https://play.golang.org/p/raSQU1MRcWE](https://play.golang.org/p/raSQU1MRcWE)

**Comment by mattfarina** [comment]
Oh, I see what you mean.
