### ISSUE TITLE
Helm v2 CI failing on caching issue

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#8184]
When `make bootstrap` is run in environments that already have a Glide cache there's now the error:

```
[ERROR]	Update failed for google.golang.org/genproto: The Remote does not match the VCS endpoint
[ERROR]	Failed to install: The Remote does not match the VCS endpoint
```

This is affecting caching in the CI system as well (example [here](https://circleci.com/gh/helm/helm/12220)).

This is because the source for google.golang.org/genproto moved from https://github.com/google/go-genproto to https://github.com/googleapis/go-genproto. It it now hosted on a different GitHub org.

**Comment by darkdefender27** [comment]
> This is because the source for google.golang.org/genproto moved from https://github.com/google/go-genproto to https://github.com/googleapis/go-genproto. It it now hosted on a different GitHub org.

@mattfarina Where did you confirm this information from

**Comment by bacongobbler** [comment]
Click on the first link. It will redirect to the latter.

**Comment by darkdefender27** [comment]
@bacongobbler Thanks. 😅

**Comment by JennyLi90** [comment]
@mattfarina  how you fix this issue? change the glide.lock file?
