### ISSUE TITLE
Necessary requirements for helmChart detection

### ISSUE THREAD

**Issue by vsvipul** [helm/helm#8191]
Can you please let me know the absolute necessary things for helm chart detection ? Currently I am considering values.yaml, Chart.yaml and a templates/ directory as the necessary conditions for a directory to be considered a helmChart.

Is there something I should change? Thanks.

Output of `helm version`:
3.2
Output of `kubectl version`:
1.18
Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by bacongobbler** [comment]
https://helm.sh/docs/topics/charts/#the-chart-file-structure

**Comment by vsvipul** [comment]
@bacongobbler  I have gone through the above link earlier as well and nowhere does it state that what are the absolute neccesities for helmChart. Some sources say that templates/ is nto required. some say values.yaml is not required. Can you please let me know what is actually required?

**Comment by bacongobbler** [comment]
templates and values are optional. The only mandatory file is the Chart.yaml.

**Comment by vsvipul** [comment]
@bacongobbler  Thanks.
