### ISSUE TITLE
helm strict linting error evaluating labels w default

### ISSUE THREAD

**Issue by baboune** [helm/helm#8192]
Output of `helm version`: `version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"} `

Output of `kubectl version`: `N/A`

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  `N/A

Expressions like the following lead to errors during `helm lint --strict`:
```
{{- $component := .componentLabel | default $parent | default $file }}
```

The Go template code checks for .componentLabel, but if it doesn't exist, it falls back to something that does. 

It seems `helm lint --strict` will spot that we even asked what the value of .componentLabel outside of a if statement, and that made us run into an error.

Expected behavior: No error.

Chart example: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/tree/master/jupyterhub

**Comment by bridgetkromhout** [comment]
Hi, @baboune - In [Helm v3.3.0](https://github.com/helm/helm/releases/tag/v3.3.0) we made a number of linting fixes. When I test your chart now, it does not fail, so I will resolve this issue. Please let us know if any problem persists. 

```
$ cat Chart.yaml 
apiVersion: v1
name: jupyterhub
version: 0.0.1-set.by.chartpress
appVersion: 1.1.0
description: Multi-user Jupyter installation
home: https://z2jh.jupyter.org
sources:
  - https://github.com/jupyterhub/zero-to-jupyterhub-k8s
icon: https://jupyter.org/assets/hublogo.svg
kubeVersion: '>=1.11.0-0'
tillerVersion: '>=2.11.0-0'
$ helm version
version.BuildInfo{Version:"v3.3.3", GitCommit:"55e3ca022e40fe200fbc855938995f40b2a68ce0", GitTreeState:"dirty", GoVersion:"go1.15.2"}
$ helm lint --strict
engine.go:167: [INFO] Missing required value: Proxy token must be a 32 byte random string generated with `openssl rand -hex 32`!
engine.go:167: [INFO] Missing required value: Proxy token must be a 32 byte random string generated with `openssl rand -hex 32`!
engine.go:167: [INFO] Missing required value: Proxy token must be a 32 byte random string generated with `openssl rand -hex 32`!
==> Linting .

1 chart(s) linted, 0 chart(s) failed
$ 
```
