### ISSUE TITLE
Compare 2 helms

### ISSUE THREAD

**Issue by doribd** [helm/helm#8193]
Hi,

What is the best way if there is one, or tool to compare 2 helm charts. 
Why i need it ? 
I have two versions of my application, there were changes. i want help one, understand them quickly.

Best regards,
Dor

**Comment by hickeyma** [comment]
@doribd This [Helm Diff plugin](https://github.com/databus23/helm-diff) might be the way to do this.

**Comment by doribd** [comment]
> @doribd This [Helm Diff plugin](https://github.com/databus23/helm-diff) might be the way to do this.

thanks, already familiar with this tool. But do we have other option ?

**Comment by hickeyma** [comment]
@doribd There might be other tools that I am not aware of. I would think using a basic diff tool would be useful (as essentially a chart is a directory).

**Comment by doribd** [comment]
thanks everyone.
