### ISSUE TITLE
How to helm into selected server?

### ISSUE THREAD

**Issue by Alwyn-Teh** [helm/helm#8196]
Hello,

I am a newbie to OpenShift, Docker and Kubernetes. I am in an environment with many OpenShift servers (e.g. INTegration, UAT and PROD) with different URLs.

I just downloaded helm 3 but don't know how to target a specific server with my commands. I need to be able to upload a helm chart to the INT environment eventually.

How do I do that please?

Thanks.

**Comment by hickeyma** [comment]
@Alwyn-Teh Helm accesses a cluster similar to `kubectl` access using [kubeconfig files](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/). You can also override on the fly using args described in [helm command)[https://helm.sh/docs/helm/helm/].

**Comment by bacongobbler** [comment]
Hi @Alwyn-Teh. Does @hickeyma's comment answer your question?

**Comment by Alwyn-Teh** [comment]
Yes, thank you @hickeyma. I will look into it later. I imagine that I should set up some kubectl config files (?) so Helm can find and interact with the cluster. Meanwhile, I have created a pod from a Helm 3 tools template, and I am able to use the Terminal there for running helm commands.

I've just watched your KubeCon YouTube video, and I have another question which I'll post in a few minutes.

**Comment by Alwyn-Teh** [comment]
Yes, thank you @hickeyma. I will look into it later. I imagine that I should set up some kubectl config files (?) so Helm can find and interact with the cluster. Meanwhile, I have created a pod from a Helm 3 tools template, and I am able to use the Terminal there for running helm commands.

I've just watched your KubeCon YouTube video, and I have another question which I'll post in a few minutes.
