### ISSUE TITLE
Helm 3.2.1 Windows 10 Azure AKS "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached

### ISSUE THREAD

**Issue by neil-n-brown** [helm/helm#8201]
**Unable to Add Stable Repo  using Helm 3.2.1 Windows 10** 

**Output of `helm version`:**
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}

**Output of `kubectl version`:**
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"1bea6c00a7055edef03f1d4bb58b773fa8917f11", GitTreeState:"clean", BuildDate:"2020-02-11T20:13:57Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"059c666b8d0cce7219d2958e6ecc3198072de9bc", GitTreeState:"clean", BuildDate:"2020-04-03T15:17:29Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**Cloud Provider/Platform (AKS, GKE, Minikube etc.):** 
Azure AKS

**OS / Access Level:** 
Windows 10 Version 1809 (OS Build 17763.1192)
Non-Administrator privileges

**Command:**
helm repo add stable https://kubernetes-charts.storage.googleapis.com --debug

**Error**
Error: looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Get https://kubernetes-charts.storage.googleapis.com/index.yaml: dial tcp XXX.XXX.XXX.XXX:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
helm.go:84: [debug] Get https://kubernetes-charts.storage.googleapis.com/index.yaml: dial tcp XXX.XXX.XXX.XXX:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached
main.(*repoAddOptions).run
        /home/circleci/helm.sh/helm/cmd/helm/repo_add.go:134
main.newRepoAddCmd.func1
        /home/circleci/helm.sh/helm/cmd/helm/repo_add.go:68
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:83
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1357

**What I Have Tried:**
1) I can curl the repo without isssue. 
2) I have tried to manually setting https proxy but I get the same result. This does not affect me reaching other repos for other apps only helm.
3) I can access "https://kubernetes-charts.storage.googleapis.com/index.yaml" without issue 
4) I have verified that by helm is pointing to the correct kube config file.
5) Importing GTS CA 1O1 certificate to Trusted CA Certs

**Comment by rishi7c** [comment]
Hi,

Does it work for you if you run it using admin privileges ?
Have you set the XDG env variables as stated on Helm docs?

If you have not, does the equivalent of / path in your environment have write access ?

Regards,
Rishi
[https://github.com/helm/helm/issues/8038](url)

**Comment by bacongobbler** [comment]
> A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

Hmm. That error would appear to indicate that you cannot establish a connection with Google Cloud Storage, but this statement

>     3\. I can access "https://kubernetes-charts.storage.googleapis.com/index.yaml" without issue


Suggests otherwise. My first thought would be a firewall/networking related issue.

Let us know what you find out.

**Comment by neil-n-brown** [comment]
Okay all,

I hope this post is useful for other because I spent around 3/4 days trying to resolve this.

After checking with my network team and confirming no issues that side I tried more trial and error. 

If you are behind corp proxy you need to specify the proxy settings in your environment variables. nothing new there - expect there appears that Helm is interpreting https_proxy variable as the http_proxy and vice versa.

So to resolve I switched them round:

https_proxy=http://username:password@yourproxyserver:port
http_proxy=https://username:password@yourproxyserver:port

The downside to this is that I have to change back when i need to use other applications.
