### ISSUE TITLE
How do I generate a custom initialization file ？

### ISSUE THREAD

**Issue by Bryce-huang** [helm/helm#8202]
Output of `helm version`:
3.2.1
Output of `kubectl version`:
1.16.5
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
openshift

Deer helm team:
How do I generate a custom initialization file when i use the command `helm create`.
For example,I am using openshift platform，the route is not ingress，how can i use the route.yaml of openshift to instead of ingress.yml of k8s in templates directory?

**Comment by bacongobbler** [comment]
https://helm.sh/docs/topics/charts/#chart-starter-packs

**Comment by Bryce-huang** [comment]
very thanks
