### ISSUE TITLE
Add Helm to Winget 

### ISSUE THREAD

**Issue by vasilvestre** [helm/helm#8203]
Windows just created their own 'chocolatey' https://github.com/microsoft/winget-pkgs and Helm isn't actually one of them. No PR is open atm.

**Comment by hickeyma** [comment]
@bridgetkromhout @bacongobbler @technosophos @thomastaylor312 You might have some insider info on this! :) ^^

**Comment by bacongobbler** [comment]
It was recently announced at //build last week. I can look into this

**Comment by bacongobbler** [comment]
Not currently possible. winget-cli only supports .exe, .msi, and .msix as installer types. It does not support unpacking from zip files, as far as I'm aware.

In order to add support for Helm to winget, we'll need to package Helm using an executable installer, or add zipfile support to winget-cli.

Here's what I have:

```
$ cat manifests/CNCF/Helm/3.2.1.yaml
Id: CNCF.Helm
Version: 3.2.1
Name: Helm
Publisher: Cloud Native Computing Foundation
License: Copyright The Helm Authors. All Rights Reserved. Licensed under the Apache License, Version 2.0
LicenseUrl: https://github.com/helm/helm/blob/master/LICENSE
AppMoniker: helm
Tags: helm, kubernetes
Description: The Kubernetes Package Manager
Homepage: https://helm.sh
Installers:
  - Arch: x64
    Url: https://get.helm.sh/helm-v3.2.1-windows-amd64.zip
    Sha256: dbd30c03f5ba110348a20ffb5ed8770080757937c157987cce59287507af79dd
    InstallerType: zip
```

See https://github.com/microsoft/winget-pkgs/issues/174.

**Comment by bacongobbler** [comment]
unstale

(https://github.com/helm/helm/pull/9042 will fix the issue where "keep open" labels are being ignored)

**Comment by anton-dealmeida** [comment]
Please can we have helm added to winget? Would be amazing!

**Comment by bacongobbler** [comment]
@anton-dealmeida I would also be interested in winget support.

If you know how to package Go CLIs into a .msi package, we'd welcome the help.

**Comment by ssrahul96** [comment]
@bacongobbler , I ve made a inno script that generates the helm installer, i ve added github actions to that, you can get the installer from artifact. It is not signed.

https://github.com/ssrahul96/helm-windows-installer

**Comment by Haegi** [comment]
Any updates on this topic?
It seems like winget now supports zip, see https://github.com/microsoft/winget-cli/pull/2500

**Comment by ssrahul96** [comment]
> Any updates on this topic? It seems like winget now supports zip, see [microsoft/winget-cli#2500](https://github.com/microsoft/winget-cli/pull/2500)

Oh cool, let me check it out

**Comment by ssrahul96** [comment]
added upstream to winget https://github.com/microsoft/winget-pkgs/pull/86104

**Comment by ssrahul96** [comment]
i have submitted the package name as `Helm.helm`, is this correct or it should be `Kubernetes.helm` ?

**Comment by dermoritz** [comment]
i would appreciate addition to winget but it seems not there yet: 


```
PS C:\Users\moritz\Documents\PowerShell> winget search helm
Name        ID                       Version Quelle
----------------------------------------------------
Helm        MattTytel.Helm           0.9.0.0 winget
8GadgetPack HelmutBuhler.8GadgetPack 35.0.0  winget
```

**Comment by Hadi-94** [comment]
I just happen to see that helm can be installed using `winget` after I ran `winget seach helm`

![Screenshot_20230221_044239](https://user-images.githubusercontent.com/47055090/220293558-9c6a9ca8-7f39-473b-a250-9fe06c11c479.png)

I'm a little bit confused since Helm Docs don't mention anything about `winget` installation option for windows.

**Comment by vasilvestre** [comment]
> I just happen to see that helm can be installed using `winget` after I ran `winget seach helm`
> 
> ![Screenshot_20230221_044239](https://user-images.githubusercontent.com/47055090/220293558-9c6a9ca8-7f39-473b-a250-9fe06c11c479.png)
> 
> I'm a little bit confused since Helm Docs don't mention anything about `winget` installation option for windows.

I think you should try to discuss it here https://github.com/helm/helm-www
I'm closing this since there's helm in winget now :)

**Comment by dave-yotta** [comment]
Hey we tried to add this at work but maybe doesnt work for non-admin accounts?

![Image](https://github.com/user-attachments/assets/996802ed-bbce-421e-9b8b-01febe71785d)

the winget Links folder is accessable but the binary in the winget packages folder I dont have permissions for.

**Comment by mdenhoedt** [comment]
Running `winget install Helm.Helm --version 3.19.2` doesn't actually add `helm` to your PATH. After uninstalling and installing it from a terminal with Administrator rights, I was able to get it working.
