### ISSUE TITLE
pre-install hook finished successfully even helm install timeout

### ISSUE THREAD

**Issue by yanshao373** [helm/helm#8206]
Output of `helm version`:
Client: &version.Version{SemVer:"v2.16.3", GitCommit:"1ee0254c86d4ed6887327dabed7aa7da29d7eb0d", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.3", GitCommit:"1ee0254c86d4ed6887327dabed7aa7da29d7eb0d", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Minikube 

I sleep 180s in my pre-install hook command, and  helm3 install --timeout=60s  to figure out how does helm kill hook when timeout happened, but I found that even the helm install timed out after 60s, but the hook still finished sleep 180, and the state of hook is completed. Anyone could give some advice?

  command: ['sh', '-c', 'trap "echo INT" INT; trap "echo QUIT" QUIT; trap "echo HUP" HUP; trap "echo ABRT" ABRT; trap "echo TERM" TERM;  trap "echo FPE" FPE; trap "echo EMT" EMT; trap "echo TRAP" TRAP; trap "echo ILL" ILL;sleep 180']

**Comment by bacongobbler** [comment]
Hooks are considered un-managed resources. Once installed, they are not modified. In other words, they are not terminated when the timeout finishes. `--wait` and other flags only report on the status of said hooks, but they do not directly manage their end state due to a connection timeout.

Does that answer your question?

**Comment by yanshao373** [comment]
Yes, thanks a lot.
