### ISSUE TITLE
Use helm install --set to override map value

### ISSUE THREAD

**Issue by LoofahBu** [helm/helm#8207]
I try to install `prometheus-operator` and it has a configurable parameters `prometheus.prometheusSpec.externalLabels` which default value is `{}`.

I want to override `prometheus.prometheusSpec.externalLabels` by below command

>helm install prom-op stable/prometheus-operator --set prometheus.prometheusSpec.externalLabels={ monitor: test }

But the result always show 
>Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Prometheus.spec.externalLabels): invalid type for com.coreos.monitoring.v1.Prometheus.spec.externalLabels: got "array", expected "map"

Is there any method to solve this problem? Thanks!

**Comment by bacongobbler** [comment]
Hi @LoofahBu. This appears to be an issue with how the prometheus chart expects its input. This does not appear to be a bug/action item to take action over in Helm itself.

Please open a new ticket over at helm/charts, or reach out to the prometheus chart maintainers directly. If you think you've found a bug in Helm, please try to reproduce the issue with a sample chart.

For more information on --set and its syntax, please refer to the documentation: https://helm.sh/docs/intro/using_helm/#the-format-and-limitations-of---set

Thanks.
