### ISSUE TITLE
helm not using the updated values.yaml

### ISSUE THREAD

**Issue by Arjunkrisha** [helm/helm#8208]
Hi,
     I am facing an issue with helm upgrade where it is not picking up the latest values in values.yaml unless i pass it via --values flag. 

- I deployed my app using helm upgrade --install baster helm/ --values helm/values.yaml initially
- The values.yaml basically has many variable details along with the value for image to be used in our application
- The image is build and stored in image registry for every commit i make and so the image value changes in values.yaml.
- Since I felt `helm upgrade --install baster helm/ --values helm/values.yaml` is lengthy and anyway helm pics up the values.yaml by default, i changed it to  `helm upgrade --install baster helm/`
- What surprised me was it did not pick the new image that the values.yaml had, instead it kept using the old values that was used previously when i manually fed it with command line.

The values.yaml should be picked by helm everytime right or does it saves some state at the backend ?

Any help would be appreciated. Thanks!

Output of `helm version`:
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a17149e1a189050796ced469dbd78d380f2ed5ef", GitTreeState:"clean", BuildDate:"2020-04-16T11:44:51Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a17149e1a189050796ced469dbd78d380f2ed5ef", GitTreeState:"clean", BuildDate:"2020-04-16T11:36:15Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
We deployed k8s using kubespray over openstack VMs.

**Comment by Arjunkrisha** [comment]
The dir structure:
helm:
-  Chart.yaml
-  templates/
     - ....
-  values.yaml

**Comment by Arjunkrisha** [comment]
`grep -vi image helm/values.yaml` (built a new image and generated values.yaml with latest image tag)
- image: containers.cisco.com/ngcs/baster_api:836ddb4d
- image: containers.cisco.com/ngcs/baster_collector:836ddb4d

`helm upgrade --install baster helm/ --dry-run --debug | grep -vi image` (this just pics the old image)
- image: containers.cisco.com/ngcs/baster_api:39b0a00f
- image: containers.cisco.com/ngcs/baster_collector:39b0a00f

`helm upgrade --install baster helm/ --values values.yaml --dry-run --debug | grep -vi image` (only if i feed in manually i get the latest image)
- image: containers.cisco.com/ngcs/baster_api:836ddb4d
- image: containers.cisco.com/ngcs/baster_collector:836ddb4d

**Comment by hickeyma** [comment]
@Arjunkrisha If you want to reuse values already set when first run and then set a particular value then use `--set` `--reuse-values` flags.  Some details in the docs: https://helm.sh/docs/intro/using_helm/#the-format-and-limitations-of---set and https://helm.sh/docs/chart_best_practices/values/#consider-how-users-will-use-your-values

**Comment by Arjunkrisha** [comment]
@hickeyma Thanks for the quick response. 

- My question is why `helm upgrade` is not using the values.yaml.
- From my experience i am understanding that helm is saving the values only during installation.
- Next time when i do a upgrade it is not picking values from the values.yaml present in the chart directory, instead it is just uses the values that it saved initially.
- So the users are forced to feed the `values.yaml` using `--values` or `-f` flag.

Personally i believe helm should be dynamically able to pic up the values present in values.yaml during each upgrade. Do you think this could be a new feature helm team can work on ?
Or probably there is a reason behind this behaviour which i am not aware of. I

**Comment by hickeyma** [comment]
@Arjunkrisha Values are saved during an upgrade. You however need the `--reuse-values` flag in conjunction with `--set` or `--values` flag to use the previous values. Otherwise, it uses the default values from the default values file in `<chart>/values.yaml`.

**Comment by Arjunkrisha** [comment]
@hickeyma  I think then what i understand is, i should be running upgrade as `helm upgrade  --install --values values.yaml baster helm/` everytime.
Because in my case values.yaml is generated dynamically. 
So if i just run `helm upgrade  --install baster helm/` then helm will not pick up my dynamically generated values.yaml. Because it looks like, it just takes the saved values from the previous run.

**Comment by hickeyma** [comment]
Yes, sounds right. Give it a go and see if that works for you.

**Comment by Arjunkrisha** [comment]
Thanks @hickeyma 

It does work when i send the values using --values.. 

I was actually thinking this as a bug from helm for not picking the values.yaml dynamically rather than us sending it in command line..

After you comments in sounds like helm is designed in such a way. But still i am not sure why it was designed to store and reuse values even though a values.yaml is dynamically created in the correct directory path.

**Comment by hickeyma** [comment]
Looking at it again, I have noticed that you are specifying using the `--values` flag for the default values file: `--values helm/values.yaml`. I initially thought this was in a different directory to the default chart root.

I am thinking because you are specifying it using the `--values` flag that it is treating as a non default values file. Can you try it again without the `--values` flag ?

**Comment by Arjunkrisha** [comment]
Correct, values.yaml is on the right folder. If i don't give the --values flag, even if i make any changes to the values.yaml file it is no reflected. That is the reason i created this issue.

**Comment by ankitjain28may** [comment]
I am having the same issues, do we have any updates here?

**Comment by abhijeetka** [comment]
facing the same issue.

**Comment by sylvain-combe-sonarsource** [comment]
same

**Comment by frreynal** [comment]
me too, helm doesn't take into account the values i've just changed

**Comment by elgur** [comment]
Try incrementing the version of the chart in the Chart.yaml file.
