### ISSUE TITLE
Use of HELM_KEY_PASSPHRASE to pass passphrase to helm package

### ISSUE THREAD

**Issue by patrickgardella** [helm/helm#8210]
In Helm v2, we had the ability to set an environmental variable to pass in the passphrase to the GPG private key using $HELM_KEY_PASSPHRASE. (Added in [pull 4778](https://github.com/helm/helm/pull/4778/files/b0a32d089e5fa91594cdba8b62ecae8ed5294751))

In Helm v3, that feature does not appear to exist. The only passphraseFetcher implemented is in [helm/pkg/action/package.go](https://github.com/helm/helm/blob/d0422e6d82b9d7ddc9c24f02ed1f7d321f9e2646/pkg/action/package.go) on line 136.

Without this option, we can't make use of `helm package --sign` from CI/CD tools (like Azure DevOps, which I'm currently using), because the `terminal.ReadPassword` does not take place in a TTY, which results in an error `inappropriate ioctl for device`.

I'm open to other options as well.

**Comment by bacongobbler** [comment]
Passing along a pass phrase with environment variables in plain text seems like a very bad way to send that data in a secure fashion. A process running in the background reading from /proc or your bash_history file could easily swipe that password. I wouldn’t be surprised if it was removed due to security concerns.

Let’s revisit the base case here though: how do other package managers pass along pass phrases for private keys in a ci/cd environment? How are packages signed in a secure manner?

**Comment by patrickgardella** [comment]
From my experience, you have four ways of passing a passphrase in a non-interactive manner:

1. on command line as a parameter
1. in a file
1. from STDIN
1. from an environmental variable

I did a short search of some of the various tools and package managers out there. It's certainly not comprehensive, but gives an idea of what could be done.

**Java** in their `jarsigner`, uses the passphrase as 1) a command line parameter, 2) a file, or 3) and environmental variable. (See --keypass and --storepass in the [docs](https://docs.oracle.com/javase/8/docs/technotes/tools/windows/jarsigner.html))

**Nuget** uses signing certificates

**Gradle** uses 1) the gradle.properties file where it is plaintext or 2) an environmental variable. [docs](https://docs.gradle.org/current/userguide/signing_plugin.html)

**npm** uses OpenPGP

**pip** uses GPG

**cpan** uses GPG

**GPG** allows for passphrase to be passed in using a 1) file,  2) file descriptor or STDIN, or 3) on the command line [docs](https://gnupg.org/documentation/manpage.html) 

_Note_: In this case, the environmental variable is set by Azure DevOps and is encrypted at REST, and they "suggest that you map your secrets into environment variables." [docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables)
