### ISSUE TITLE
how to adapter sourcecode on mips64le

### ISSUE THREAD

**Issue by duchuanLX** [helm/helm#8214]
Output of `helm version`:3.2.1

Output of `kubectl version`: 1.18.3

Cloud Provider/Platform (AKS, GKE, Minikube etc.): all

How to continue to support mips64le in subsequent versions

**Comment by duchuanLX** [comment]
@johnw188 
I urgently need your help, thank you。

**Comment by bacongobbler** [comment]
Hi @duchuanLX. Was there ever a time where we supported mips64le? Your comment implies that we did at some point.

Are you looking to add support for this?

**Comment by duchuanLX** [comment]
> Hi @duchuanLX. Was there ever a time where we supported mips64le? Your comment implies that we did at some point.
> 
> Are you looking to add support for this?

we want use helm on kubernetes platfrom on mips64le，and we want add mips64le on support archlist。
what do I need to do，Please guide me。

-TARGETS           ?= darwin/amd64 linux/amd64 linux/386 linux/arm linux/arm64 linux/ppc64le linux/s390x windows/amd64

**Comment by duchuanLX** [comment]
the last version support mips
