### ISSUE TITLE
Error installing app that includes Prometheus

### ISSUE THREAD

**Issue by kaplandani** [helm/helm#8215]
I get this error when running:
helm install myapp-api --set EnvType=dev --set BuildVersion=0.1.0-1590642144668 --namespace=api-dev .

I get this error: 

Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"

the service monitor is defined in a templates folder (service_monitor.yaml: 

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "myapp.name" . }}-api
  labels:
    monitored: "true"
spec:
  selector:
    matchLabels:
      app: {{ template "myapp.name" . }}-api
  endpoints:
  - port: {{ template "myapp.name" . }}-api
    interval: 15s

How can I fix this ?

Output of `helm version`:
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-dispatcher", GitCommit:"f5757a1dee5a89cc5e29cd7159076648bf21a02b", GitTreeState:"clean", BuildDate:"2020-02-06T03:33:34Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:23:21Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

(this is my dev env, this code runs in docker built by jenkins, I hope it's the same)

**Comment by bacongobbler** [comment]
At first glance it looks like the chart is relying on an API version (monitoring.coreos.com/v1) that does not exist in a vanilla kubernetes cluster; the CRD must be registered first.

**Comment by bacongobbler** [comment]
https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#install-a-crd-declaration-before-using-the-resource
