### ISSUE TITLE
Proposal: use defaults from values.schema.json as chart default values

### ISSUE THREAD

**Issue by stoiev** [helm/helm#8218]
### Problem
Automatized Chart document generation must consider two files, `values.schema.json` and `values.yaml`, even with a proper location (`default` entry) for defaults on schema.

### Propose
Use `default` optional entry on `values.schema.json` as default Chart values. For being back-compatible, `values.yaml` could be used as a second layer of default values, overwriting values just like `--set` does.

In Charts with `values.schema.json` only, `values.yaml` could be generated from `values.schema.json` when it's necessary, using description/title as head commentaries of each entry, and default values. (same for `helm show values`)

**Comment by bacongobbler** [comment]
Hi @stoiev. Thanks for the proposal. Have you looked into the feasibility of this yet?

**Comment by stoiev** [comment]
It seem that Chart values are calculated [here](https://github.com/helm/helm/blob/9b42702a4bced339ff424a78ad68dd6be6e1a80a/pkg/cli/values/options.go#L42).

Extracting `defaults` entries of `values.schema.json` attribute definitions  (if this file/entry exists) and using it as `base` map seems the easiest approach that I could figure out.

Since defaults in json schema could be spread through multiple levels, we need to assume some rule to use it in `values.schema.json`, and the problem here (as it seem to be in helm journey) are list values. 

Using `defaults` from first-level-only entries seems to catch most of use cases automatically, and it is easier to communicate, but could be misleading since it seems more natural that multi-level objects are multi-level defaulted.

If we try to use multi-level default values, we must stop fetching at lists and go no more deeper, since list default itself is the only way to default its inner elements.

One way or another, schema writers must to be aware of those rules.

**Comment by bridgetkromhout** [comment]
Hi, @stoiev - thank you for your ideas. We now have a structure for considering proposals, so if you'd like to submit this idea as a [Helm Improvement Proposal](https://github.com/helm/community/blob/master/hips/hip-0001.md), please do so! Thanks. I'll resolve this issue now.

**Comment by omniproc** [comment]
Has there been any work on this? TBH I don't get why this was closed. If now any discussion about a new feature has to be started by submitting a HIP about 90% of all open issues would need to be closed.

By closing this issue a meaningful discussion about a useful feature was shut down and thus no progress has been seen for 2 years.

**Comment by Ornias1993** [comment]
> Has there been any work on this? TBH I don't get why this was closed. If now any discussion about a new feature has to be started by submitting a HIP about 90% of all open issues would need to be closed.
> 
> By closing this issue a meaningful discussion about a useful feature was shut down and thus no progress has been seen for 2 years.

That's because by pushing things into HIPs, the super-inactive maintainers have less things to look at.
With more issues open, it would be even more obvious how inactive they are and increasing the, already significant, chance they get kicked out of the CNCF for being inactive.
