### ISSUE TITLE
Any way to confirm if a PV/PVC exists before create

### ISSUE THREAD

**Issue by yanshao373** [helm/helm#8222]
Output of helm version:
Client: &version.Version{SemVer:"v2.16.3", GitCommit:"1ee0254c86d4ed6887327dabed7aa7da29d7eb0d", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.3", GitCommit:"1ee0254c86d4ed6887327dabed7aa7da29d7eb0d", GitTreeState:"clean"}

Output of kubectl version:
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):
Minikube

We need some support during pre-install hook:
Any way to create a PVC during pre-install hook phase by helm3 install command automatically since the hook image will need to use the PVC?
Any way to give a check before PVC creation if this PVC exist or  not?

Really thanks for your time!

**Comment by mattfarina** [comment]
There is not a way in Helm v2. In Helm v3 there is the [lookup](https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-lookup-function) function. This function enables you to lookup resources in a cluster.

Note, if you use `helm template` or perform a dry run Helm will not interact with the cluster and will return no results for a lookup. It will only perform the lookup when installing or upgrading.

**Comment by yanshao373** [comment]
Hi, thanks for your reply. 
But how to create PVC before pre-install during helm install command since pre-install hook is executed before any resources are created in Kubernetes?

**Comment by bacongobbler** [comment]
I don’t think a pre-pre-install hook exists if that’s what you’re looking for.

**Comment by yanshao373** [comment]
Okay, thanks for your help.
