### ISSUE TITLE
Unable to get an updae from the "stable" chart repo.

### ISSUE THREAD

**Issue by 2020testuser** [helm/helm#8223]
Summary

Installing JenkinsX using jx boot and unable to fetch the velero chart repo. 
Steps to reproduce the behavior
Fetch the velero chart repo. durig JenkinsX install.
Install JenkinsX on top of an on-prem remote Kubernetes cluster using the jx boot command from a local MAC OS machine.

Expected behavior

Successful install of JenkinsX using jx boot command.
Actual behavior

Installation fails with the below error msg.
`
STEP: install-velero command: /bin/sh -c jx step helm apply --boot --remote --no-vault --name velero in dir: /Users/myid/Documents/jx/jenkins-x-boot-config/systems/velero

error: failed to build the dependencies of chart '/var/folders/4g/prh490450fv3hf_zjt31dzjrjyv20j/T/jx-helm-apply-071077216/velero': failed to run 'helm dependency build' command in directory '/var/folders/4g/prh490450fv3hf_zjt31dzjrjyv20j/T/jx-helm-apply-071077216/velero', output: 'Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:portno/charts):
Get http://127.0.0.1:portno/charts/index.yaml: dial tcp 127.0.0.1:portno: connect: connection refused
...Successfully got an update from the "jenkins-x" chart repository
...Unable to get an update from the "stable" chart repository (https://kubernetes-charts.storage.googleapis.com):
open /Users/myid/.helm/repository/cache/~/.helm/repository/cache/stable-index.yaml: no such file or directory
Update Complete. ⎈Happy Helming!⎈
Error: velero chart not found in repo https://kubernetes-charts.storage.googleapis.com'
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step helm apply --boot --remote --no-vault --name velero' command in directory 'systems/velero', output: ''
`
Versions

The components versions are

NAME               VERSION
helm - 2.1.x
Kubernetes cluster v1.16.8 (on-prem remote cluster)
kubectl            v1.16.6-beta.0
git                2.20.1 (Apple Git-117) 

Running jxboot from local MAC machine.

Thanks!

**Comment by bacongobbler** [comment]
> /Users/myid/.helm/repository/cache/~/.helm/repository/cache/stable-index.yaml: no such file or directory

I’d check your local environment to see why an absolute and a relative path are used in the same file path. That seems like a good first step to determine a root cause here.

**Comment by 2020testuser** [comment]
@bacongobbler - Thanks! Could you please let me know in which file the helm related settings are set? I can go and remove them. I uninstalled and reinstalled helm and no luck.
Thanks in advance!

**Comment by bacongobbler** [comment]
Use `helm env`.

**Comment by bridgetkromhout** [comment]
Hi, @2020testuser - hopefully the `helm env` suggestion enabled you to solve this issue. We'll resolve it at this time, due to inactivity.
