### ISSUE TITLE
[question] Should you package CRD resources into helm chart?

### ISSUE THREAD

**Issue by milosgajdos** [helm/helm#8224]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

Output of `kubectl version`:
```
Client Version: openshift-clients-4.2.1-201910220950
Server Version: 4.4.4
Kubernetes Version: v1.17.1
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
On-prem

I have not found this anywhere, so I'm asking here. I suspect Helm was originally designed to package only the "primitive" k8s resources, but I'm curious if anyone packages CRD resources into their charts, as well. Or if it should be done at all!

I'm not talking about the CRDs but rather CRD resources i.e. instances of the CRD definition/template (or whatever you call it).

I can see the con of doing this: it can create inconsistencies in installed charts since once you delete the CRD all CRD resources are deleted as well which can leave the installed chart in a somewhat inconsistent state.

I made a simple test by "packaging" a CRD resource into a sample chart and I noticed two things:
1. Helm hooks don't seem to be honored on the CRDs packaged into helm chart
2. When listing the helm release resources (`helm get manifest ...`) the packaged CRD resource does not get listed in the output which makes me think Helm does not track it?

**Comment by bacongobbler** [comment]
I have heard of charts including CRD instances in their charts, yes. There are examples available in the helm/charts repository. For example, here's one in the prometheus-operator chart: https://github.com/helm/charts/blob/d5bcb3c872505e41232db4f9716aa73a056ab4fc/stable/prometheus-operator/templates/grafana/servicemonitor.yaml#L2-L3

Hope this helps.
