### ISSUE TITLE
feature request: pretty print variant of toJson function

### ISSUE THREAD

**Issue by anapsix** [helm/helm#8229]
Output of `helm version`: `version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}`

Output of `kubectl version`: `Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:06:54Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): `minikube`

---

`toJson` function is awesome, and super helpful in converting YAML data to JSON. I'm using it to customize and generate JSON application config from chart's values. Being able to pretty print JSON output is not a requirement, but would be nice.
Thus, it would be awesome to have a variant of `toJson` to pretty prints JSON.

**Comment by bacongobbler** [comment]
Use `toPrettyJson`.

**Comment by anapsix** [comment]
indeed, there are many helpful functions, as found in https://github.com/Masterminds/sprig/blob/master/functions.go#L222, including `toPrettyJson`, which seems to work just fine
TODO: update documentation, with reference to the motherload of helpful functions
