### ISSUE TITLE
How to ignore errors on helm dry-run?

### ISSUE THREAD

**Issue by dudicoco** [helm/helm#8232]
Hi,
When running `helm upgrade --install --dry-run` is it possible to make helm exit with exitcode 0 even if there were errors during the dry run?

**Comment by bacongobbler** [comment]
No. What would be the use case for this?

**Comment by dudicoco** [comment]
@bacongobbler I am using `helmfile` with hooks to add annotations and labels which allows importing existing k8s resources into a release:
https://github.com/roboll/helmfile/issues/1281#issuecomment-636494016

Helm dry run would fail since the resources already exist, but running `helm install --upgrade` would finish with success since the hooks would run prior to the command, adding the proper annotations and labels to the resources.

**Comment by bacongobbler** [comment]
I'm not sure how to solve your use case, but the base case here to ignore errors during a dry run doesn't seem like something we want to support. Programs that silently ignore errors is considered by most to be a bug, or unintended behaviour at the very least.

**Comment by bridgetkromhout** [comment]
As stated above, Helm does not plan to support silently ignoring errors during a dry run.

**Comment by pfredeli** [comment]
I think there's a misunderstanding what errors we are talking about. Mostly when I run dry run I care if the templates are correct but I don't care if they are compatible with the current cluster state. I just want to know what the output of the template looks like.
