### ISSUE TITLE
Proposal: arbitrary hooks

### ISSUE THREAD

**Issue by batiati** [helm/helm#8233]
**Motivation**
Helm hooks are the most valuable tools to ensure the quality and desired state of a chart release. In my opinion, it is what makes Helm really different from any other templating/packing tool.

Some applications eventually needs to executes life-cycle tasks as Jobs. It would take advantage to trigger those jobs as "arbitrary hooks", something as powerfull as an **operator**, but much simpler to implement.

**Proposal**
Example of an arbitrary hook named "clear-log", intended to do some application's life-clycle task.
```
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    "helm.sh/hook": clear-log
    "helm.sh/hook-delete-policy": hook-succeeded
```

Using it from command line, following the same `helm test` behavior and command structure
```
helm exec my-release-name clear-log
```
Likewise any other hook, it will be rendered using values.yaml presented during the install/upgrade.

The new `helm exec` command would allow the user to run (or re-run) any existent hook, like `pre-install`, `post-install`, etc. It would be very convenient when the chart is installed or upgraded using `--no-hooks` flag.

**Comment by bacongobbler** [comment]
How does this differ from `kubectl run` or another command to run pods in the cluster?

> The new `helm exec` command would allow the user to run (or re-run) any existent hook, like `pre-install`, `post-install`, etc.

Why would you wan to run pre-install hooks post-install? THat seems like incredibly dangerous behaviour. This would break current assumptions that pre-install or post-install hooks will only run once during a `helm install` or `helm upgrade`.

**Comment by batiati** [comment]
Hi Matthew,

> How does this differ from `kubectl run` or another command to run pods in the cluster?

The command `kubectl run` can be used to run any pod, but not with all chart's logic managed by Helm.

The proposed `helm exec` command should be able to run the entire hook (jobs and all resources marked with the same `helm.sh/hook` annotation) but not restricted only to the pre-defined events.

For example, an arbitrary `foo` hook shoud be executed by `helm exec my-release foo`.

```
  annotations:
    "helm.sh/hook": foo
```

I think it shoud behave in the same way the `helm test` command works: 
- Run manually by the user
- Run anytime the user needed it

> Why would you wan to run pre-install hooks post-install? That seems like incredibly dangerous behaviour. This would break current assumptions that pre-install or post-install hooks will only run once during a `helm install` or `helm upgrade`.

Agreed ... it was a bad example. But in the same way `--no-hooks` flag will break this assumption too; I think that both resources should be used only for strict maintenance purposes.

On the other hand, `helm test` can be invoked many times as needed, without side efects; The same concept must be valid for "arbitrary hooks".

**Comment by bacongobbler** [comment]
Accepting a list of arbitrary hooks means that we cannot reserve any hook names for future use without breaking backwards compatibility. For example, there’s been proposals discussing the introduction of a post-ready hook. If we implemented arbitrary hook names and a chart defined their arbitrary hook name as “post-ready”, the behaviour of that hook may change when they upgrade helm.

How do you suggest we fix that?

**Comment by mattfarina** [comment]
A couple thoughts...

First, I noticed the command would need to be altered to be:

```
helm exec my-release-name clear-log repo/chart
```

The chart package would need to be available to have the asset to render.

This leads to issues of version compatibility. What if the chart package is for a different version from the one currently running? Is there an error? Is there a `--force` feature to run anyway? How does compat work?

Encapsulating these sorts of things could be a way to enable more from operation systems like KUDO. I wonder what the KUDO devs or others think of this?

**Comment by mattfarina** [comment]
@bacongobbler A hook might not be the right terminology for this. A hook is a way to hook into the install process. These are more like npm scripts.

Might it make more sense to have a new thing similar to hooks but separate? That way hooks don't run into backwards compat issues and the name is more befitting what is being executed.

**Comment by batiati** [comment]
Hi folks, 

> @bacongobbler 
> Accepting a list of arbitrary hooks means that we cannot reserve any hook names for future use without breaking backwards compatibility.

That is true, we could create another annotation for arbitrary hook's name and use the reserved word `arbitrary` only for the hook type. 

For example:
```
  annotations:
    "helm.sh/hook": arbitrary
    "helm.sh/hook-name": clear-log
```


> @mattfarina 
> First, I noticed the command would need to be altered to be:
> 
> ```
> helm exec my-release-name clear-log repo/chart
> ```

All rendered hooks are stored on the release's secret, you don't need the chart again to get them.
For example using the command `helm get hooks my-release`



> @mattfarina 
> Encapsulating these sorts of things could be a way to enable more from operation systems like KUDO. I wonder what the KUDO devs or others think of this?

Exactly, it is very like an operator, but the action performed is only related to an specif chart release. 

> @bacongobbler A hook might not be the right terminology for this. A hook is a way to hook into the install process. These are more like npm scripts.
> 
> Might it make more sense to have a new thing similar to hooks but separate? That way hooks don't run into backwards compat issues and the name is more befitting what is being executed.

I agree, it would be even better ... maybe we could add more "operator like" behavior, without care about compatibility issues.

I was trying reuse all hook's behavior in something more like a `test`, that is a hook but does not run into the install process.

**Comment by batiati** [comment]
To exemplify my use case, where did I get this proposal from:

I have an application packed into a Helm Chart, all install/upgrade/rollback tasks done by hooks. 
It works really great and my Ops team loves it.

Many releases of the same Chart are deployed on my cluster (one release per customer), and eventually the Ops team needs to perform some maintenance tasks on a specific customer, like clear-log or compact-data.

So I had those options to solve the problem:

1. Starting a Job, but I have to manually create the correct manifest for each target release (including correct secrets, volumes, configMaps, etc)
Too complex to operate.
	
2. Running `kubectl exec` into the desired container and execute the command
Very simple, but not suitable for long running tasks.
	
3. Packing all the maintenance tasks into another Chart (this one was my choice)
It's not so bad, but I had to get the same values.yaml from the target application release to install the maintenance chart.  
I managed to create a simple `helm plugin` to take care of it.
The Ops team just run `helm clear-log my-relese-name` where `clear-log` is the plugin name, on background it gets the values.yaml and install the maintenance chart.

4. Creating an Operator (using KUDO or OLM)
I started in that way, but it's sounded like overkill.
I could even replace Helm and deploy my application using the operator, but something wasn't right for me, is was just too complex to solve a much simpler problem.

**Comment by bridgetkromhout** [comment]
Hi, @batiati - it sounds like you are trying to use Helm to carry out tasks that might be better carried out with [Brigade](https://brigade.sh/) - perhaps you will want to consider looking at that option?

If you do want to move forward with this proposal, please file a [Helm Improvement Proposal](https://github.com/helm/community/blob/master/hips/hip-0001.md) so we can work through all the use cases and constraints - thanks!
