### ISSUE TITLE
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Config" in version "v1"

### ISSUE THREAD

**Issue by chpq95** [helm/helm#8241]
Output of `helm version`:
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:34:25Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Minikube

I do get this error when run helm install my-project ./helm. can anyone explain to me what this error is and how can I solve it?

**Comment by bacongobbler** [comment]
As the error would suggest, there are no matches for a Kubernetes object (known as a “kind”) called "Config" found for the “v1” schema (the `apiVersion`). These objects are defined in your templates/ folder. Have a look in there.

Perhaps you meant to use a `ConfigMap` instead?

**Comment by chpq95** [comment]
Hi @bacongobbler, thanks for your response. I do define "Config" in my kubeconfig file.

**Comment by bacongobbler** [comment]
I'm not sure what you mean. Can you please provide more information?

**Comment by chpq95** [comment]
Oh sorry, I mean I already define "Config" in my kubeconfig.yaml. this is my kubeconfig.yaml

apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: my-certificate-authority-data
    server: my-endpoint
  name: cluster-name

users:
- name: developer
  user:
    as-user-extra: {}
    client-key-data: my-client-key-data
    token: my-token

contexts:
- context:
    cluster: my-cluster
    namespace: staging
    user: developer
  name: staging

current-context: staging

**Comment by bacongobbler** [comment]
Okay. That’s not exactly what I meant earlier though.

From my previous comment:

> These objects are defined in your templates/ folder. Have a look in there. Perhaps you meant to use a ConfigMap instead?

I want you to look in your helm chart for a template that defines a “Config” type. Not in your kubeconfig file.

**Comment by chpq95** [comment]
oh, sorry. I'm still new with k8s and helm. there is no "Config" type other than the kubeconfig file.  Actually i store kubeconfig in my templates/ folder.

**Comment by bacongobbler** [comment]
> Actually I store kubeconfig in my templates/ folder.

Therein lies your problem. You are effectively asking Kubernetes to install a kubeconfig in the cluster, which is not allowed, hence the error.

> or just store it in ~/.kube ?

Yes.

**Comment by bacongobbler** [comment]
So, then resolution here: please remove your kube config from your helm chart. Once that's done, your chart should install.

Closing as resolved. Let us know if you run into further issues. I highly recommend giving the documentation a read-through as well. A lot of the basic concepts around Kubernetes and Helm are explained in the documentation. https://helm.sh/docs/

Thanks!
