### ISSUE TITLE
helm ls output very bizarre spacing

### ISSUE THREAD

**Issue by gboor** [helm/helm#8242]
Output of `helm version`: version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.26", GitCommit:"525ce678faa2b28483fa9569757a61f92b7b0988", GitTreeState:"clean", BuildDate:"2020-03-06T18:47:39Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): GCS

The formatting of the helm 3 output is really strange, mangling columns on the terminal;

![tty](https://user-images.githubusercontent.com/7305315/83491204-b325ff80-a4b1-11ea-859d-77f9df37a288.PNG)

The issue seems to be that the columns are extremely wide. I am not sure if this is helm specific, but the output of other commands - like `kubectl get pods` - is just fine, so it seems to be. I checked various terminal settings, like $COLUMNS, `stty size` and `tput cols` and they all return the correct width of the terminal.

**Comment by bacongobbler** [comment]
Hmm. Not sure what would be causing this. What terminal are you using, and what operating system?

**Comment by gboor** [comment]
I realize it's a weird one, thanks for looking into it.

I just had to change something on an older cluster that still uses Helm v2 and the output is mangled in the same way! So this may not be an issue with Helm, specifically, but rather with whatever lib it uses to format its output.

I'm using Bash on Ubuntu, running on top of Windows 10 (using WSL).

**Comment by bacongobbler** [comment]
Weird. That’s was the same setup I was using to reproduce the issue.

Let us know if you find out anything interesting.

**Comment by gboor** [comment]
I found something interesting alright... After a lot of digging, I came across a registry setting;

HKCU\Console\VirtualTerminalLevel

This value is normally not present, or set to 0. You need to set it to 1 in order to enable ANSI color sequences on Windows CLI. I had it set to 1 for that reason. Setting it back to 0 fixes the issue in Bash on Ubuntu using WSL.

This means that Ubuntu/WSL still uses the same Windows console subsystem to render its screens. It also means that something in that output, in combination with VirtualTerminalLevel 1, causes the whole the spacing to mess up.

This is not the case with Kubectl and various other commands. I only ran into it with Helm so far, but there might be other affected tools depending on the library used to render the tables.

What lib is that (if any)? Is it worth issuing a ticket there?

**Comment by mattfarina** [comment]
That's a great catch. Helm uses https://github.com/gosuri/uitable for its tables. If I remember correctly, Kubernetes is using something custom.

**Comment by gboor** [comment]
I created an issue here; https://github.com/gosuri/uitable/issues/18

Let's see what they make of it.

**Comment by bridgetkromhout** [comment]
Hi, @gboor! Thanks for your detective work. As you have opened https://github.com/gosuri/uitable/issues/18 (and as we cannot fix this directly in Helm), I'll close this issue now.
