### ISSUE TITLE
When using annotation "helm.sh/resource-policy": "no-upgrade-existing", the resource is not deleted on helm uninstall

### ISSUE THREAD

**Issue by jgoeres** [helm/helm#8245]
I use the annotation 

    "helm.sh/resource-policy": no-upgrade-existing 

on a secret with randomly generated passwords to preserve these passwords on "helm upgrade". This works nicely. Alas, on "helm uninstall", the secret is not deleted, a subsequent "helm install" fails with "Error: rendered manifests contain a resource that already exists."
Is this behavior intentional? I would expect a resource with this annotation to not be touched during "helm upgrade", but still be deleted on "helm uninstall". If I want to preserve a resource on "helm uninstall", I would use "helm.sh/resource-policy": keep. 
If I want both behaviors, I would use both annotations.

**Comment by bacongobbler** [comment]
I don't see any resource policy that exists with the name `no-upgrade-existing`. Just `keep`. Are you sure that feature exists?

https://github.com/helm/helm/blob/03ccd5dea2516e5da275653aa4485064377a7fd5/pkg/kube/resource_policy.go#L26

https://github.com/helm/helm/pull/5290 was never merged into master. We are not providing support for features that were never merged.
