### ISSUE TITLE
Restoring with velero

### ISSUE THREAD

**Issue by alexgeek** [helm/helm#8247]
Hi there,

I have a helm chart that I've added a velero schedule to and have tested backup and restore. This works fine, all the configuration and volumes come back. However I can no longer list/upgrade the release with helm. Are there additional configurations I need to specify to backup with velero so that after restoring I can continue to upgrade as normal? 

Thanks,
Alex

Output of `helm version`: 

```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.5-gke.9", GitCommit:"85b5c9fa8d766613bef894d0850eb6617863cfc0", GitTreeState:"clean", BuildDate:"2020-05-29T01:22:16Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  GKE

**Comment by hickeyma** [comment]
Do you see it when you run `helm list --all-namespaces`?

**Comment by alexgeek** [comment]
> Do you see it when you run `helm list --all-namespaces`?

I don't. What resource does helm query to produce the list of releases?

**Comment by hickeyma** [comment]
`kubectl get secret --all-namespaces -l "owner=helm"` returns all Helm release version/revision data.

**Comment by alexgeek** [comment]
I see, thank you. Looks like velero doesn't pickup that secret, not sure why.

**Comment by bacongobbler** [comment]
Let us know if you have further questions. Perhaps this would be a good question for the velero folks at this point.

More info on helm’s architecture from a high level can be found here: https://helm.sh/docs/topics/architecture/#implementation

Thanks!

**Comment by alexgeek** [comment]
I see its because of my label selector is using app.kubernetes.io/name which isn't in the release secret. I'll just need to adjust that, thanks,
