### ISSUE TITLE
RFE: Should helm install  --create-namespace be smart enough to create OpenShift projects

### ISSUE THREAD

**Issue by tylerauerbeck** [helm/helm#8250]
Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```
Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0-4-g38212b5", GitCommit:"2576e482bf003e34e67ba3d69edcf5d411cfd6f3", GitTreeState:"clean", BuildDate:"2020-04-26T19:58:26Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.1", GitCommit:"b9b84e0", GitTreeState:"clean", BuildDate:"2020-04-26T20:16:35Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  OpenShift

When trying to install a helm chart and having helm create the namespace for it via `--create-namespace`, a normal OpenShift user will receive the following error:

```
Error: namespaces is forbidden: User "my-user" cannot create resource "namespaces" in API group "" at the cluster scope
```

In general, most clusters allow normal users to create projects and project-requests. With helm now being able to create namespaces for its projects, it would be useful to also be able to create projects/projectrequests if it is running on top of OpenShift.

**Comment by bacongobbler** [comment]
What's the difference between a namespace and a project? My initial reaction would be no, but I'd like to know why this should be part of `--create-namespace`.

**Comment by bacongobbler** [comment]
To clarify: why should a flag like `--create-namespace` create something other than a namespace?

**Comment by hzliangbin** [comment]
@bacongobbler projects are namespaces with additional security annotations in OpenShift.
