### ISSUE TITLE
time out error while connecting to kubernetes api

### ISSUE THREAD

**Issue by mehmetekici** [helm/helm#8253]
Hello,
I  am trying to set up a new Azure Kubernetes Cluster but straingly I got a time out error on half of "helm ls" or deployment commands. It is very slow responding as well.

22:44 $ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"e2d9f8479783020904aba3de7499a49be6c75ebd", GitTreeState:"clean", BuildDate:"2020-04-09T02:31:15Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
✔ ~/noo/portfolio/network-infrastructure [master L|●2✚ 18…11] 
22:46 $ helm version
Client: &version.Version{SemVer:"v2.16.6", GitCommit:"dd2e5695da88625b190e6b22e9542550ab503a47", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.6", GitCommit:"dd2e5695da88625b190e6b22e9542550ab503a47", GitTreeState:"clean"}

helm ls
https://ggyzxcvadrqwerqweaxvnecentraluasdfamk8s.io:443/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%!D(MISSING)TILLER: dial tcp: i/o timeout

Here are the tiller pod's logs 

storage] 2020/06/04 19:33:25 listing all releases with filter
[storage] 2020/06/04 19:35:24 listing all releases with filter
[storage] 2020/06/04 19:36:16 listing all releases with filter
[storage] 2020/06/04 19:37:46 listing all releases with filter
[storage/driver] 2020/06/04 19:38:16 list: failed to list: Get https://gyzxcvadrqwerqweaxvnecentraluasdfamk8s.io:443/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%3DTILLER: dial tcp: i/o timeout
[storage] 2020/06/04 19:41:26 listing all releases with filter
[storage/driver] 2020/06/04 19:41:47 list: failed to list: Get https://gyzxcvadrqwerqweaxvnecentraluasdfa.io:443/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%3DTILLER: dial tcp: lookup gavnets.azmk8s.io on 10.0.0.10:53: read udp 10.244.1.6:54995->10.0.0.10:53: i/o timeout
[storage] 2020/06/04 19:44:07 listing all releases with filter
[storage/driver] 2020/06/04 19:44:37 list: failed to list: Get https://gyzxcvadrqwerqweaxvnecentraluasdfas.azmk8s.io:443/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%3DTILLER: dial tcp: i/o timeout

you can see that some call succeeds but some are not.

Thanks in advance.

**Comment by mattfarina** [comment]
@mehmetekici I have a couple questions to help diagnose the problem:

* Did it work and then stop working?
* Are you using RBAC in the cluster? If so, is Tiller setup to work with RBAC?

**Comment by bridgetkromhout** [comment]
Hi, @mehmetekici - You are using Helm 2. As explained in the AKS docs, AKS allows you to start using Helm 3: https://docs.microsoft.com/en-us/azure/aks/kubernetes-helm#verify-your-version-of-helm - and if you check out https://helm.sh/blog/helm-v2-deprecation-timeline/ you will see instructions to migrate to Helm 3.

As we don't have more information to help diagnose, I will resolve this issue now. If you can give us additional information about your situation, we can help with Helm 2 questions until mid-November. Thanks.
