### ISSUE TITLE
How to remove a resource from helm without deleting it

### ISSUE THREAD

**Issue by nicholasrobertm** [helm/helm#8256]
**Output of `helm version`:**
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}

**Output of `kubectl version`:**
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**Cloud Provider/Platform (AKS, GKE, Minikube etc.):** 
AWS (Non managed node groups)

Hi there! I've ran into a scenario I couldn't find documented. Previously we had namespaces as part of helm releases. Due to the danger of this (removing a namespace, even by accident wipes everything in it), we're wanting to move namespaces out of helm. However, despite removing any labels from the namespace resource that tie it to the helm release, and additionally trying to use something like helm edit to edit the release in place, resources are still deleted.

Is there a way to remove these from being managed by helm while keeping the resource? We're not purging the release as there are other things in there and are looking for ways to prevent an outage without migrating clusters.

Appreciate any help!

**Comment by liuming-dev** [comment]
try `helm.sh/resource-policy: keep` annotation

links:
- [Hook resources are not managed with corresponding releases](https://helm.sh/docs/topics/charts_hooks/#hook-resources-are-not-managed-with-corresponding-releases)
- [Tell Helm Not To Uninstall a Resource](https://helm.sh/docs/howto/charts_tips_and_tricks/#tell-helm-not-to-uninstall-a-resource)

**Comment by bacongobbler** [comment]
closing as answered in the documentation.
