### ISSUE TITLE
helm 3 dependency update - Error: directory charts/keycloak not found

### ISSUE THREAD

**Issue by TDesai10** [helm/helm#8258]
Hello,
I am trying to deploy the keycloak helm chart from codecentric, details below, however when trying to perform a 'helm dependency update' it gives me an error 'Error: directory charts/keycloak not found"

### Chart.yaml
apiVersion: v2
name: keycloak
description: Keycloak Helm chart
type: application
version: 0.1.0
appVersion: 8.0.2
dependencies:
  - name: keycloak
    version: 7.0.0
    repo: https://codecentric.github.io/helm-charts

I am still new to helm and trying to figure out if/what am i doing wrong.

Output of `helm version`: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Minikube

**Comment by bacongobbler** [comment]
The correct key is `repository`, not `repo`.

Changing your example to this works:

```
><> cat Chart.yaml
apiVersion: v2
name: keycloak
description: Keycloak Helm chart
type: application
version: 0.1.0
appVersion: 8.0.2
dependencies:
- name: keycloak
  version: 7.0.0
  repository: https://codecentric.github.io/helm-charts
```
