### ISSUE TITLE
Description is ignore when installed with upgrade

### ISSUE THREAD

**Issue by brianharwell** [helm/helm#8264]
Output of `helm version`: 
```
version.BuildInfo{Version:"v3.2.2", GitCommit:"a6ea66349ae3015618da4f547677a14b9ecc09b3", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

Output of `kubectl version`: 
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"
gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:35:47Z", GoVersion:"go1.13.9", Compiler:"
gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): Kubernbetes in Rancher on vSphere

I installed an application using the upgrade command...
```
helm upgrade toggleservice .\ToggleService-1.0.30.tgz --install --wait --description "Manual deploy"
```
And after if I view the history the description was ignored...
```
REVISION        UPDATED                         STATUS          CHART                   APP VERSION     DESCRIPTION
1               Sun Jun  7 10:18:58 2020        deployed        ToggleService-1.0.30    1.0.133         Install complete
```

If I use the install command like so...
```
helm install toggleservice .\ToggleService-1.0.30.tgz --wait --description "Manual deploy"
```
The description is not ignored...
```
REVISION        UPDATED                         STATUS          CHART                   APP VERSION     DESCRIPTION
1               Sun Jun  7 10:19:54 2020        deployed        ToggleService-1.0.30    1.0.133         Manual deploy
```

What I expect to happen is when a description is provided to the upgrade command it is used. It works fine for subsequent upgrades but not the initial install.

**Comment by mattfarina** [comment]
I found the bug. When upgrading and it's an install the install code path is followed but the Description is not passed into it like the over information. You can find it in https://github.com/helm/helm/blob/8ea6b970ecd02365a230420692350057d48278e5/cmd/helm/upgrade.go#L80-L112.

**Comment by wawa0210** [comment]
@mattfarina 
Is anyone looking at this issue? If not, I am willing to try this fix
