### ISSUE TITLE
v3.2.2 does not contain fixes from v3.2.1

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#8265]
The patch level fixes pulled into v3.2.1 do not appear to be in v3.2.2. Investigating the reason for this. Details to follow on this issue.

**Comment by mattfarina** [comment]
v3.2.3 has been released and it contains the commits from v3.2.1 and v3.2.2.

**Comment by mattfarina** [comment]
The following is my postmortem analysis on why this happened and what we are going to do about it in the short term.

**What happened?**
The release process for patches starts with the release branch. Changes to be included in the patch release are cherry-picked on to that branch. Once this is done the branch needs to be pushed where it is tested in CI. Once that passes a tag can be created and pushed for the release process.

When v3.2.1 was released the tag was pushed but the release-3.2 branch wasn't. When v3.2.2 release process started it began on the release-3.2 branch that did not contain the changes from v3.2.1.

The release process documentation fails to document the need to push the branch for patch releases and the person executing the release followed the process as documented.

**The Fix**
The  short term solution was to release v3.2.3. This release cherry-picked the changes from v3.2.1 on to the release-3.2 branch in the order they were originally picked in to v3.2.1. This did not unwind the change from v3.2.2. Rather, it picked them on top of it.

The mid term solution involves fixing the current documentation to include the push in the patch step (issue https://github.com/helm/helm-www/issues/674). The documentation on the release process isn't great. https://github.com/helm/helm-www/issues/675 has been created to fix that process.

The long term solution is to automate more of the process to remove the possibility for human error.

**Comment by marckhouzam** [comment]
> When v3.2.1 was released the tag was pushed but the release-3.2 branch wasn't. When v3.2.2 release process started it began on the release-3.2 branch that did not contain the changes from v3.2.1.

Nice find!

> The long term solution is to automate more of the process to remove the possibility for human error.

👍
