### ISSUE TITLE
Helm v3 go library can't reuse same history, install, and upgrade clients for multiple namespaces

### ISSUE THREAD

**Issue by sean-krail** [helm/helm#8269]
Go mod:
```go.mod
module jitterbit.com/functions/deploychart

go 1.13

require (
	helm.sh/helm/v3 v3.2.1
	k8s.io/cli-runtime v0.18.0
	k8s.io/client-go v0.18.0
	rsc.io/letsencrypt v0.0.3 // indirect
)
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Helm v3 go client on GCP Cloud Function that connects to GKE

---

I'm trying to reuse the same history, install, and upgrade clients that will be invoked multiple times across different namespaces. It seems that this isn't possible? In the below example, the releases are always deployed to the `default` namespace.

```go
package deploychart

import (
	"fmt"
	"os"
	"time"

	"helm.sh/helm/v3/pkg/action"
	"helm.sh/helm/v3/pkg/chart"
	"helm.sh/helm/v3/pkg/chart/loader"
	"helm.sh/helm/v3/pkg/cli"
	"helm.sh/helm/v3/pkg/storage/driver"

	// Not really sure if this is needed
	_ "k8s.io/client-go/plugin/pkg/client/auth/gcp"
)

// Default values for chart
var defaultValues = map[string]interface{}{
	// ...
}

var actionConfig = new(action.Configuration)
var historyClient *action.History
var installClient *action.Install
var upgradeClient *action.Upgrade

var chartRef *chart.Chart

// Setup the Helm History, Install, and Upgrade clients
func setup() error {
	stdout.Println("Setting up Helm client...")

	// Initialize Helm action configuration
	settings := cli.New()
	err := actionConfig.Init(settings.RESTClientGetter(), settings.Namespace(), os.Getenv("HELM_DRIVER"), stdout.Printf)
	if err != nil {
		stderr.Panic(err)
	}

	// Test connectivity to Kubernetes client
	err = actionConfig.KubeClient.IsReachable()
	if err != nil {
		stderr.Panicf("The function is unable to reach the Kubernetes cluster.\n%s\n", err.Error())
	}
	stdout.Println("The function is able to reach the Kubernetes cluster.")

	// Initialize Helm's history client
	historyClient = action.NewHistory(actionConfig)

	// Initialize Helm's install client
	installClient = action.NewInstall(actionConfig)

	// Initialize Helm's upgrade client
	upgradeClient = action.NewUpgrade(actionConfig)

	// ...
}

// Deploy the Helm chart
func deploy(namespace string, releaseName string) error {
	values := map[string]interface{}{
		// ...
	}

	mergedValues := mergeMaps(defaultValues, values)

	// If a release does not exist, install it
	historyClient.Max = 1
	_, err := historyClient.Run(releaseName)
	if err == driver.ErrReleaseNotFound {
		stdout.Printf("Release %q does not exist. Installing it now in namespace %q.\n", releaseName, namespace)
		installClient.Namespace = namespace
		installClient.ReleaseName = releaseName
		rel, err := installClient.Run(chartRef, mergedValues)
		if err != nil {
			stderr.Printf("Release %q failed to install in namespace %q: %s\n", releaseName, namespace, err.Error())
			return err
		}
		stdout.Printf("Release %q has been installed successfully in namespace %q!\n", rel.Name, rel.Namespace)
		return nil
	} else if err != nil {
		stderr.Printf("Failed getting release history for release %q in namespace %q: %s\n", releaseName, namespace, err.Error())
		return err
	}

	// If a release exists, upgrade it
	stdout.Printf("Release %q exists. Upgrading it now in namespace %q.\n", releaseName, namespace)
	upgradeClient.Namespace = namespace
	rel, err := upgradeClient.Run(releaseName, chartRef, mergedValues)
	if err != nil {
		stderr.Printf("Release %q failed to upgrade in namespace %q: %s\n", releaseName, namespace, err.Error())
		return err
	}
	stdout.Printf("Release %q has been upgraded successfully in namespace %q!\n", rel.Name, rel.Namespace)
	return nil
}
```

Something's that I've noticed with the above:
1. I'm using the default release storage driver (`secrets`) which is setup once on the call to `actionConfig.Init` using the `default` namespace ([source code](https://github.com/helm/helm/blob/524150c662f9c030d2caa9ad8f79d2ff9521c431/pkg/action/action.go#L364-L374)). The releases are always stored/retrieved in this namespace. The `historyClient` has no option to specify which namespace to check and the `installClient` and `upgradeClient` do not use their properties `installClient.Namespace` and `upgradeClient.Namespace`, respectively. I would expect this to be able to be dynamic, but I was wrong.
2. Calls to `installClient.Run` and `upgradeClient.Run` do not deploy to the namespaces `installClient.Namespace` and `upgradeClient.Namespace`, respectively. They adhere to what was set on `actionConfig.Init`. This is not what I would expect.

It seems that I have no option but to instantiate a new `action.Configuration` for each call to `func deploy`. Is there a better way?

**Comment by bacongobbler** [comment]
As I understand it, the kube client needs to switch namespaces as well. You can change the namespace parameter of the kubeclient by setting `actionConfig.KubeClient.Namespace = namespace` in your example. Otherwise it will use the namespace set in your kubeconfig.

https://github.com/helm/helm/blob/8ea6b970ecd02365a230420692350057d48278e5/pkg/kube/client.go#L60-L61

https://github.com/helm/helm/blob/8ea6b970ecd02365a230420692350057d48278e5/pkg/kube/client.go#L129-L137

**Comment by sean-krail** [comment]
@bacongobbler Thanks for the quick response. That worked for the install and upgrade clients, but doesn't work for the history client since the namespace gets baked into the release store on init.
https://github.com/helm/helm/blob/524150c662f9c030d2caa9ad8f79d2ff9521c431/pkg/action/action.go#L364-L374

Also, I'm new to golang so it wasn't clear to me but I had to cast `actionConfig.KubeClient` to `*kube.Client` since it's type is the interface `kube.Interface`:
```go
	// Update KubeClient's namespace
	if kc, ok := actionConfig.KubeClient.(*kube.Client); ok {
		stdout.Printf("Updated KubeClient's namespace to %q\n", namespace)
		kc.Namespace = namespace
	} else {
		stderr.Printf("Failed to update KubeClient's namespace to %q. Expected \"actionConfig.KubeClient\" to be \"*kube.Client\", got \"%T\". Release will be deployed to the \"default\" namespace.\n", namespace, actionConfig.KubeClient)
	}

	// Use installClient and upgradeClient
```

**Comment by mattfarina** [comment]
@sean-krail thanks for the feedback. We will keep it in mind when we start work on Helm v4.
