### ISSUE TITLE
Improve tracking for rollback revisions

### ISSUE THREAD

**Issue by batiati** [helm/helm#8275]
### Problem

Tracking information about rollbacks is difficult because the actual rollback revision is only presented as string, as part of the "DESCRIPTION" column of `helm history` command.

Example of `helm history` command
```
1  Sun Jun  7 22:45:11 2020        superseded      mychart-1.0.0   Install complete
2  Tue Jun  9 11:49:23 2020        superseded      mychart-1.0.0   Upgrade complete
3  Tue Jun  9 11:50:19 2020        superseded      mychart-1.0.0   Upgrade complete
4  Tue Jun  9 11:50:34 2020        superseded      mychart-1.0.0   Rollback to 2
5  Tue Jun  9 11:50:58 2020        superseded      mychart-1.0.0   Upgrade complete
6  Tue Jun  9 11:52:01 2020        deployed        mychart-1.0.0   Rollback to 4
```

### Proposal

Put the "rollback to revision number" in a separated column (or as JSON when using `-o json`), allowing external tools to properly read this information without need to parse the description message.

The `.Release.Revision` field is no enough to do such tracking. In the example above, both "rev6" and "rev4" has `.Release.Revision` equals 2

**Comment by mattfarina** [comment]
@batiati thanks for the feature request. Is there a particular situation or use case this would be used in? We'd like to understand the broader context of the need.

**Comment by batiati** [comment]
@mattfarina 

It's mainly because I'm managing a stateful application from a Helm Chart, using upgrade/rollback hooks to backup and restore some application data during its maintenance.

- pre-upgrade => take a backup of the app data (saves it as rev_xx.bak where xx is the current rev number)

- pre-rollback => take the same backup performed by pre-upgrade **and then** restore the rev_yy.bak file, where yy is now the rollback revision number.

As the hook manifest is already rendered during the rollback, I see that is not possible to access this value from `{{ .Release.Revision }}`, so I had to read it from api/command line.

Those jobs rely on the "rollback to ..." description message to identify which revision was ordered  by the user during the `helm rollback` command, but it's fragile, because this message can change in any future release. 

Besides that, I have a little tracking tool that that uses this information to create reports for my team.

**Comment by wawa0210** [comment]
If we need to support this feature, we should need to adjust

https://github.com/helm/helm/blob/master/pkg/release/release.go#L22 
https://github.com/helm/helm/blob/master/cmd/helm/history.go#L86

From the perspective of kubernetes, this information is independent. Is there any special reason for helm to combine Description and previousVersion?

@mattfarina @bacongobbler 

I personally think that separate display may be more user-friendly and have more clear semantics. I look forward to your reply, if ok, I can try to contribute pr
