### ISSUE TITLE
Need to use Helm in Airgapped environment

### ISSUE THREAD

**Issue by shashank-k** [helm/helm#8276]
I have a K8S cluster setup in an airgapped environment which is making difficult to download the public charts and associated docker images.

We also use harbor and by using [helm-mirror](https://github.com/openSUSE/helm-mirror) I can do download the public charts to harbor. Also I can download the docker images, tag it and push it to our repository.

The problem is needing to add the Harbor credentials to these charts and it is extremely time consuming to complete all these steps which I have mentioned (even with some scripts in place 😢 )

I am looking here for guidance if there are any easier ways to use public helm charts to be used in airgapped environments.

**Comment by bacongobbler** [comment]
I think this is a use case https://github.com/helm/helm/issues/7754 is attempting to solve. Can you please weigh in on that ticket? Thanks!
