### ISSUE TITLE
helm upgrade --install does not allow setting description if release did not previously exist

### ISSUE THREAD

**Issue by nwohlgemuth** [helm/helm#8278]
Output of `helm version`:
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Azure

I am in process of upgrading from helm v2 to helm v3 and noticed an issue with helm upgrade --install. In v2, the --description option always worked as expected. In v3, it works as expected if the release already exists. But if the release does not already exist, the description is always 'Install complete' (ignoring whatever was given for the --description option),

**Comment by bacongobbler** [comment]
Fixed in #8274.

**Comment by nwohlgemuth** [comment]
What version of helm3 will include this fix? It seems that the latest stable (3.2.4) does not.

**Comment by bacongobbler** [comment]
it'll be in Helm 3.3.0.
