### ISSUE TITLE
Helm 2 and 3 not able to deal with large releases

### ISSUE THREAD

**Issue by vsliouniaev** [helm/helm#8281]
* Output of `helm version`: 3.2.1
* Output of `kubectl version`: 1.18.2
* Cloud Provider/Platform: kind 

Helm install fails with
```
Error: create: failed to create: Request entity too large: limit is 3145728
```

I don't have junk in my directory, I simply have a large chart where multiple people are managing their dashboards and this has grown beyond helm's current ability to manage them. This issue has existed since helm version 2.

Previously reported in:
- #8062
- #7264
- #6711
- #5107
- #4574
- #4215
- #1996
- #1413

**Comment by tculp** [comment]
What about adding an annotation to the release secret, such as "continued-in: sh.helm.release.v1.<release>.v1.part2". A solution like this seems like it would be reverse-compatible, requiring no changes for releases that fit within a single object.

**Comment by diepes** [comment]
We also managed to hit the limit.  Probably due the use of secrets plugin, and adding multiple certificates in secrets.yaml etc.

In our case we dont require all the advanced features of helm (maybe in future),  as we use **helm as a templating tool** and a **release pipeline to deploy and rollback**(redeploy old version)

For us adding a way to just disable the history, or just keep a simple summery in the history (e.g. command line used) would probably be a solution.

As to loosing 3way merge, this has caused of regular deployment failures for us with immutable fields, and we now just delete objects (sometimes namespace) and re-deploy to fix helm deployment failures, so disabling/loosing this could also be a benefit.

**Comment by HamzaZo** [comment]
+1  to re-open this issue. 

cc @mattfarina any update about this issue ? Thanks

**Comment by hickeyma** [comment]
Could it be that the cluster cannot deploy any more secrets when it hits a limit? In other words, the error limit is not necessarily for the Helm release secret but for the cluster limit?

Some context with a similar issue in https://github.com/helm/helm-2to3/issues/171#issuecomment-721690255.

**Comment by tculp** [comment]
+1 to re-open this issue.

**Comment by prab2014** [comment]
+1 as i am getting the error when deploying prometheus-stack on cluster using helm
Error: create: failed to create: the server responded with the status code 413 but did not return more information (post secrets)

**Comment by Guidonet** [comment]
+ 1 same issue with prometheus-stack, 15.4.4

**Comment by bacongobbler** [comment]
@prab2014 and @Guidonet, that error is a little different than the one posted by the OP. Can you do a bit of investigation and report back with your findings?

As noted earlier, Kubernetes' etcd backend cannot handle large charts. Have you tried using the database backend instead?

**Comment by prab2014** [comment]
> @prab2014 and @Guidonet, that error is a little different than the one posted by the OP. Can you do a bit of investigation and report back with your findings?
> 
> As noted earlier, Kubernetes' etcd backend cannot handle large charts. Have you tried using the database backend instead?

What do you mean by database backend? kindly specify. 
When I tried with different chart (having less data -for e.g. only Prometheus chart instead of kube-prometheus-chart),it installs it successfully. 
Looks like issue with charts having more memory. I am not sure here and suggestions would be appreciated.

**Comment by bacongobbler** [comment]
https://helm.sh/docs/topics/advanced/#storage-backends

**Comment by MurzNN** [comment]
Current etcd version have 1.5mb limit already, with ability to increase it: https://etcd.io/docs/v3.5/dev-guide/limit/

> By default, the maximum size of any request is 1.5 MiB. This limit is configurable through --max-request-bytes flag for etcd server.

Does this mean, that we can increase this limit in fresh k8s versions too?

**Comment by FingerLiu** [comment]
Any updates?
