### ISSUE TITLE
I don't want to use go templates

### ISSUE THREAD

**Issue by chinazj** [helm/helm#8290]
go templates likes this.
```
{{/*
Create a default fully qualified app name.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
If release name contains chart name it will be used as a full name.
*/}}
{{- define "manager.fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- if contains $name .Release.Name -}}
{{- .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
{{- end -}}
```
Disadvantages
No 

- indentation
- have to modify not only `values.yaml`, but also `_helper.tpl`
- I think this is two syntax, `yaml` and `template`

**Comment by bacongobbler** [comment]
So, some context here.

We have always said we are open to alternative template engine implementations. There even was support in helm’s rendering engine to support multiple template engines for Helm 2. This has been discussed across multiple threads, the largest being https://github.com/helm/helm/issues/2577. See also https://github.com/helm/helm/issues/2577#issuecomment-341548308 for more information.

Nobody from the community has been willing to put the time into writing one. So, that’s where we stand today.
