### ISSUE TITLE
Helm v3 should ignore global variables in sub-charts - why a subchart can define a global value on the integration charts' level?

### ISSUE THREAD

**Issue by P1ng-W1n** [helm/helm#8298]
This issue seems to affect HELM v3 only: I can reproduce it with any HELM v3 versions, but not with HELM v2.
For this report I'll use the latest versions from both branches (HELM v2 and v3)

```
$ helm.3.2.3 version
version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"}
$ helm.2.16.8 version
Client: &version.Version{SemVer:"v2.16.8", GitCommit:"145206680c1d5c28e3fcf30d6f596f0ba84fcb47", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"c19362d3a76093e4fbc0ca7f00121eff839f2a01", GitTreeState:"clean"}
```

Issue description:
I was playing with HELM v3 and global variables and found that something has changed between HELM v2 and v3 that I can't explain.

The setup is the following:
- Two sub-charts (deployment1 and deployment2) integrated as part of an integration chart
- Each subchart defines it's own global variables and relies on the .Values.global.registry.url to allow registry overrides 
- Each subchart has it's own registry by default (private.registry1 and perviate.registry2, defined as a global value internally), interpreted by the _helper.tpl
    // NOTE: I do agree that this implementation is suboptimal / stupid, but bear with me, you'll see my point in a minute
- An integration HELM chart integrates the two sub charts, using the version 1 API  
- Important: On the integration chart's level I have a values.yaml file with one value defined in it, which is .Values.global.registry.foo

Files I used:
```
$ find . -type f
./charts/deployment2/templates/deployment.yaml
./charts/deployment2/templates/_helpers.tpl
./charts/deployment2/values.yaml
./charts/deployment2/Chart.yaml
./charts/deployment1/templates/deployment.yaml
./charts/deployment1/templates/_helpers.tpl
./charts/deployment1/values.yaml
./charts/deployment1/Chart.yaml
./requirements.yaml
./values.yaml
./Chart.yaml
```

Content of those files:
```
$ find . -type f -ls -exec cat {} \;
      191      4 -rw-rw-r--   1 user  user       385 jún 11 22:18 ./charts/deployment2/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment2
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: {{ template "deployment2.registryUrl" . }}/nginx:1.14.2
        ports:
        - containerPort: 80

      192      4 -rw-rw-r--   1 user  user       221 jún 11 22:18 ./charts/deployment2/templates/_helpers.tpl
{{- define "deployment2.registryUrl" -}}
{{- if .Values.imageCredentials.registry.url -}}
{{- print .Values.imageCredentials.registry.url -}}
{{- else -}}
{{- print .Values.global.registry.url -}}
{{- end -}}
{{- end -}}

       44      4 -rw-rw-r--   1 user  user        87 jún 11 22:19 ./charts/deployment2/values.yaml
global:
  registry:
    url: private.registry2
imageCredentials:
  registry:
    url:

      190      4 -rw-rw-r--   1 user  user        67 jún 11 22:18 ./charts/deployment2/Chart.yaml
apiVersion: v1
appVersion: 0.1.0
name: deployment2
version: 0.1.0

      184      4 -rw-rw-r--   1 user  user       385 jún 11 22:17 ./charts/deployment1/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment1
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: {{ template "deployment1.registryUrl" . }}/nginx:1.14.2
        ports:
        - containerPort: 80

      186      4 -rw-rw-r--   1 user  user       221 jún 11 22:13 ./charts/deployment1/templates/_helpers.tpl
{{- define "deployment1.registryUrl" -}}
{{- if .Values.imageCredentials.registry.url -}}
{{- print .Values.imageCredentials.registry.url -}}
{{- else -}}
{{- print .Values.global.registry.url -}}
{{- end -}}
{{- end -}}

      187      4 -rw-rw-r--   1 user  user        87 jún 11 22:19 ./charts/deployment1/values.yaml
global:
  registry:
    url: private.registry1

imageCredentials:
  registry:
    url:
    
      189      4 -rw-rw-r--   1 user  user        67 jún 11 22:15 ./charts/deployment1/Chart.yaml
apiVersion: v1
appVersion: 0.1.0
name: deployment1
version: 0.1.0

      227      4 -rw-rw-r--   1 user  user        89 jún 11 22:20 ./requirements.yaml
dependencies:
- name: deployment1
  version: 0.1.0
- name: deployment2
  version: 0.1.0

      229      4 -rw-rw-r--   1 user  user        33 jún 11 22:21 ./values.yaml
global:
  registry:
    foo: bar
    
      226      4 -rw-rw-r--   1 user  user        73 jún 11 22:21 ./Chart.yaml
apiVersion: v1
appVersion: 0.1.0
name: integration-chart
version: 0.1.0
```

Now the fun part: with Helm version 2, the manifests are generated as such:
```
$ helm.2.16.8 template . | grep image:
        image: private.registry1/nginx:1.14.2
        image: private.registry2/nginx:1.14.2
```

// Please pay attention to the image locations, and the used private registries (private.registry1 and private.registry2)

With HELM version 3 the output is slightly different:
```
$ helm.3.2.3 template . | grep image:
        image: private.registry1/nginx:1.14.2
        image: private.registry1/nginx:1.14.2
```

// In this case both manifests have the same registry definition

This gets better if I change the order of the subcharts in the requirements.yaml and place deployment2 before deployment1:

```
$ cat requirements.yaml
dependencies:
- name: deployment2
  version: 0.1.0
- name: deployment1
  version: 0.1.0
```

With HELM v3 this returns the following:
```
$ helm.3.2.3 template . | grep image:
        image: private.registry2/nginx:1.14.2
        image: private.registry2/nginx:1.14.2
```

// This time both registries changed to private.registry2

Clearly, the first subchart's registry becomes a global variable, although that variable is not defined on the integration chart's global level. 

To move one step forward, I was wondering what happen if I wouldn't have any values.yaml on the integration chart's level ; funnily this seems to solve the problem:

```
$ rm values.yaml 
$ helm.3.2.3 template . | grep image:
        image: private.registry1/nginx:1.14.2
        image: private.registry2/nginx:1.14.2
```

So to summarize:
- In HELM v3, if the integration chart defines the same (global) structure (Values.global.registry in my case) variables in there could be inherited from subchart(s), provided that they're not defined on the integration chart's level. This is not the case with HELM v2.
    - In that case, the order of the subcharts in the requirements.yaml (in case of API v1) matters, as the first one will be inherited globally.
- If the structure is not in place, each subchart would interpret global values in its own domain 

Now.. I know that defining global variables in a subchart is a stupid idea, and probably should be done on the integration chart's level only - from that point of view ignoring the global values in the subcharts would make more sense in my opinion (thus the $SUBJECT).
However, the fact that subcharts could define values globally should not be an expected behavior in my opinion, especially as the order of charts do matter (in case both implement the same global variable)

**Comment by jdolitsky** [comment]
Globals are supported in subcharts, but perhaps the issue is just the order of precedence

Here is where globals are parsed out of subcharts: https://github.com/helm/helm/blob/6aefbdcf38e14998d0bcb24030061822b1e8888d/pkg/chartutil/coalesce.go#L71

**Comment by P1ng-W1n** [comment]
Hi @jdolitsky 
That might be part of the issue, although I'm not sure if that's the only one:
- If the global value is defined on an integration chart level, the correct value is merged into the map
- If the global value and structure are not defined, each subchart would use its own "global" (local?) value
- If the global value .Values.global.registry.url) is not defined, but the structure is (.Values.global.registry), the merge function will use the first sub chart where that value is defined.

**Comment by Cweiping** [comment]
Once I had similar puzzles with you, but according to the actual use of the project, sharing a global map is a very convenient way. When we expect to use sub-chart variables in the integration chart, we need to do so.
I think it's a good choice to use different variable names if we don't expect to use this operation.

**Comment by P1ng-W1n** [comment]
Hi @Cweiping 

Don't get me wrong, I'm not against the global map there. But the fact that the map can be influenced this way should not be the expected behavior in my opinion.
Stating that "you shouldn't do that" defeats the purpose of a bug report..
Also, since my report I also checked an other use case, where there's no values.yaml specified on the integration chart's level, but the global value is configured with --set:

```
$ helm.3.2.3 template . |grep image:
        image: private.registry1/nginx:1.14.2
        image: private.registry2/nginx:1.14.2
$ helm.3.2.3 template --set "global.registry.url=something" . |grep image:
        image: something/nginx:1.14.2
        image: something/nginx:1.14.2
$ helm.3.2.3 template --set "global.registry.foo=bar" . |grep image:
        image: private.registry1/nginx:1.14.2
        image: private.registry2/nginx:1.14.2
```
What's interesting here is that:
- without anything configured, the sub-chart specific "global" values are not merged together
- when the global.registry.url is specified, the map is updated accordingly
- when the global.registry.foo is specified (similar the way I did originally in the values file) the map contains the right values. 

The 3rd use case actually shows the opposite behavior that I described in the bug report as you can see, meaning that only values specified in the values.yaml are affected by this issue (map inherits a global value from the sub-chart's "global" values)

**Comment by bacongobbler** [comment]
I tried using your example posted in the original comment. I ran into a template error.

```
><> helm template . | grep image:
Error: template: integration-chart/charts/deployment1/templates/_helpers.tpl:2:14: executing "deployment1.registryUrl" at <.Values.imageCredentials.registry.url>: nil pointer evaluating interface {}.registry

Use --debug flag to render out invalid YAML
```

I have [attached a zipfile](https://github.com/helm/helm/files/4828055/integration-chart.zip) with the sample code being used here. I also changed the helper functions to use `default` instead of a bunch of `if/else` statements.

```
{{- define "deployment1.registryUrl" -}}
{{- print (default .Values.global.registry.url .Values.imageCredentials.registry.url) -}}
{{- end -}}
```

Using the following for deployment1's values.yaml worked:

```yaml
global:
  registry:
    url: private.registry1
imageCredentials:
  registry:
    url:
```

From the behaviour described here, it looks as though first chart wins:

```
><> cat requirements.yaml 
dependencies:
- name: deployment2
  version: 0.1.0
- name: deployment1
  version: 0.1.0
><> helm template . | grep image:
        image: private.registry2/nginx:1.14.2
        image: private.registry2/nginx:1.14.2
><> helm template . | grep image:
        image: private.registry1/nginx:1.14.2
        image: private.registry1/nginx:1.14.2
><> cat requirements.yaml 
dependencies:
- name: deployment1
  version: 0.1.0
- name: deployment2
  version: 0.1.0
><> helm template . | grep image:
        image: private.registry1/nginx:1.14.2
        image: private.registry1/nginx:1.14.2
><> cat requirements.yaml 
dependencies:
- name: deployment2
  version: 0.1.0
- name: deployment1
  version: 0.1.0
><> helm template . | grep image:
        image: private.registry2/nginx:1.14.2
        image: private.registry2/nginx:1.14.2
```

This looks like a misuse of global flags here. Both charts are setting and relying on a global flag, and it cannot be determined which chart should be used to set the global flag.

I'm not sure I fully understand what you're asking us to change here.

**Comment by P1ng-W1n** [comment]
Hi @bacongobbler 

I tried to use your attached zipfile, but it contains a single directory only..
You can check the one I'm using here: [helm3-global-test-0.1.0.tar.gz](https://github.com/helm/helm/files/4836321/helm3-global-test-0.1.0.tar.gz)

NOTES:
- I incorporated your changes in the helper function and tried to slim down the chart as much as I can
- In this chart I don't have any values.yaml specified on the integration chart's level

Using that integration chart I get the following behavior:
```
$ helm.3.2.3 template . |grep image:
        image: private.registry1/nginx:1.14.2
        image: private.registry2/nginx:1.14.2
$ helm.3.2.3 template --set global.registry.url=foo . |grep image:
        image: foo/nginx:1.14.2
        image: foo/nginx:1.14.2
$ helm.3.2.3 template --set global.registry.foo=bar . |grep image:
        image: private.registry1/nginx:1.14.2
        image: private.registry2/nginx:1.14.2
```
Here both subcharts do get the proper "global" (local) values from their own values.yaml and setting the global.registry.foo value has no affect (as  .Values.global.registry.foo is not used in the templates) as expected

The issue starts when a values.yaml is introduced with this content:
```
$ cat << EOF > values.yaml
> global:
>   registry:
>     foo: bar
> EOF
$ helm.3.2.3 template . |grep image:
        image: private.registry1/nginx:1.14.2
        image: private.registry1/nginx:1.14.2
```
Unlike previously configuring the global.registry.foo now has an affect, although global.registry.url is still not configured.
What I would expect in this scenario is both sub charts to keep using their own registries from their own values.yaml

**Comment by P1ng-W1n** [comment]
Hi @bacongobbler 

Have you had a chance to review the provided chart / issue? 
Is my explanation sufficient to understand the reported issue, or would you like further clarification?

**Comment by bacongobbler** [comment]
no. I have not had enough time to look further into this issue since the last time I looked into this.

**Comment by P1ng-W1n** [comment]
bump

**Comment by bacongobbler** [comment]
Hi there! As this is an open source project, please feel free to work on a fix. I do not have the time to work on a fix for you. Thanks!
