### ISSUE TITLE
Add shell completion for --version flag

### ISSUE THREAD

**Issue by marckhouzam** [helm/helm#8300]
This proposal is to add shell completion for the `--version` flag.  As an example
```
helm show all stable/fluentd --version <TAB>
helm pull stable/fluentd --version <TAB>
helm install myfluentd stable/fluentd --version <TAB>
helm upgrade myfluentd stable/fluentd --version <TAB>
```
would suggest
```
1.0.0   1.10.0  1.2.0   1.4.0   1.5.1   1.7.0   1.9.1   2.0.1   2.0.3   2.2.0   2.3.0   2.3.2   2.4.0
1.1.0   1.10.1  1.3.0   1.5.0   1.6.0   1.9.0   2.0.0   2.0.2   2.1.3   2.2.1   2.3.1   2.3.3   2.4.1
```
This improvement is not as much about saving users some typing as it is about helping users figure out which versions are available.

**Comment by mattfarina** [comment]
@marckhouzam how would this perform if someone had hundreds of releases? I'm thinking about CI scenarios.

**Comment by marckhouzam** [comment]
> @marckhouzam how would this perform if someone had hundreds of releases? I'm thinking about CI scenarios.

It's not as much a question of the number of releases but the size of the index file. A large index file takes time to parse to extract the versions needed for the completion. Performance is already poor for this completion (in my preliminary tests) when the chart is on the 'stable' repo because the yaml parsing of that giant index file is slow. 

We've optimized this for completing chart names by adding a `charts.txt` cache file for each repo which contains a flat list of chart names.  See https://github.com/helm/helm/pull/6809#issuecomment-560977848

I didn't feel this`--version` completion was a common scenario, so I didn't focus on optimizing.

Let me take this opportunity to ask: do we consider the `charts.txt` cache file format an API? If it's not, it could be enhanced to also cache the list of versions.

But all this performance is during user interaction doing completion.  What do you mean by CI scenarios?
