### ISSUE TITLE
Please make tag v3.2.3 show as latest release

### ISSUE THREAD

**Issue by edrandall** [helm/helm#8304]
Currently the [Github release URL](https://github.com/helm/helm/releases) is showing v2.16.8 as the latest, it's not obvious that the 3.x series exists at all unless one scrolls down substantially.  

(Use-case: I'm writing internal documentation for developers starting off,  they immediately assumed 2.16.8 was the latest version)

URL:  https://github.com/helm/helm/releases

**Comment by bacongobbler** [comment]
Github’s API describes “latest” as the most recently released version of that repository. It does not correlate to the newest version of helm 3. We have no control over this API.

Helm 2.16.8 was released earlier this week, hence why it is now considered “latest”.

Hope this clears things up.

**Comment by axel3rd** [comment]
When you are using https://api.github.com/repos/helm/helm/releases in automation to retrieve which last Helm (client) to install, retrieving the v2.x could occur some disappointment 😁.

In Ansible, an update like that should be done:

```
  - name: Get versions for Helm client
    environment: '{{ proxy_env_if_necessary }}'
    uri:
      url: https://api.github.com/repos/helm/helm/releases
      user: foo
      password: bar
      force_basic_auth: true
    register: helm_releases_json
  - name: Get last version for Helm client
    set_fact:
      helm_last_version: '{{ helm_releases_json | json_query(''json[*].tag_name'') | sort | reverse | first }}'
  - debug:
      msg: '{{ helm_last_version }}'
```
