### ISSUE TITLE
CRL revocation list is not verified

### ISSUE THREAD

**Issue by gokulpotluri** [helm/helm#8308]
Output of `helm version`:
```
$ ./helm  version
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

Output of `kubectl version`:
```
$ oc version
oc v3.7.72
kubernetes v1.7.6+a08f5eeb62
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.):
Openshift

I have been evaluating Helm v3.0.0 for our organization usage.
In our environment Helm will be interacting with Artifactory and openshift environment, while doing so, it uses Organization provided CA certs but in the process it is not verifying revocation list provided as CRL URL.
 After doing some research, I found an issue [#4273](https://github.com/helm/helm/issues/4273) raised two years back, but this issue is closed due to inactivity without any solution.

Is this fixed?

**Comment by hickeyma** [comment]
Helm 3 no longer needs the Tiller service running in the cluster. The Helm client (`helm`) now talks directly to the Kubernetes API service similar to `kubectl`. Issue #4273 would therefore apply to Helm 2 only.

I hope this helps answer your question.

FYI, the latest Helm 3 version is [3.2.3](https://github.com/helm/helm/releases/tag/v3.2.3). It is recommended where possible to use the latest version especially as 3.0.0 was released in November 2019.

**Comment by gokulpotluri** [comment]
@hickeyma Thanks for putting this.
We are looking for CRL revocation verification for certificates used by artificatory and Kubernetes (Openshift) environment while tryint to pull the charts from Artifictory and deploy them in Kubernetes environment.

**Comment by hickeyma** [comment]
@mattfarina This might be of interest to you ^^

**Comment by mattfarina** [comment]
I didn't realize how complicated this would be when I started looking into this. I wanted to add some context to the issue...

* It does not appear that CRL checking is built into the Go packages that do the work for us. The author of a bunch of this for the Go package has an opinion on CRL... https://www.imperialviolet.org/2014/04/19/revchecking.html
* Helm would need to add a layer around the HTTP client to add support for this

I've not looked but I wonder if anyone has done this in Go, yet.

**Comment by gokulpotluri** [comment]
@mattfarina do you think, can it be do able?
If so, how much time it may take?

**Comment by mattfarina** [comment]
@gokulpotluri Someone would need to make a case for it and counter the points from the Go package author. Then a PR would need to be crafted that implements this.
