### ISSUE TITLE
report original file for errors from building k8s objects from manifests

### ISSUE THREAD

**Issue by tdyas** [helm/helm#8309]
**Issue**: I had a template that due to whitespace trimming issues had merged an `apiVersion` attribute into a comment. Attempting to install this chart of course failed, but Instead of telling me which file had the issue, Helm reported: `Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: apiVersion not set`.

**Request**: Helm should report which file has the manifest with the issue.

I tried to see if this would be easy to solve. The error appears to be generated at https://github.com/helm/helm/blob/a28d695c43ad5b889923c5cf0e7694503bdb47df/pkg/action/install.go#L254-L257. I assume `rel.Manifest` contains all of the k8s manifests for the chart regardless of which file they originated from.

Moving down in the call stack, https://github.com/helm/helm/blob/master/pkg/kube/client.go calls into the k8s client and passes `""` as the name of the source for the manifests to create k8s objects from. https://github.com/helm/helm/blob/a28d695c43ad5b889923c5cf0e7694503bdb47df/pkg/kube/client.go#L157

This would need to change to be the filename from which a manifest originated, except that if `rel.Manifest` is all of the chart's manifests, then passing any individual filename there makes no sense if an error is in another file.

Potential solutions:

1. Upstream a change to https://github.com/kubernetes/cli-runtime/blob/master/pkg/resource/builder.go to add a method that can take a function that vends each manifest and its source together to the k8s client. Then use that function eventually in Helm. Maybe some variant of the code in https://github.com/kubernetes/cli-runtime/blob/b80690895f035c6fc9e8871fda07fea9cbaebe1a/pkg/resource/visitor.go since the k8s client uses multiple `StreamVisitor`s internally.

2. Process `rel.Manifest` into a map from filename to list of resources. Then construct k8s objects by calling into the k8s client for each filename (instead of once for all manifests). This would allow passing the filename as the source to the `Stream` method of the builder, and would link an error back to the originating file.

Solution 2 would not require upstream work. I am willing to work on a PR to solve this issue. I just need to know what the preferred solution here is (whether those above or something else).

**Comment by bacongobbler** [comment]
I think we need to preserve the second case. We need to validate everything all at once. Some templates may rely on the presence of others being present as they're being applied or they will fail validation. Volume mounts, for example.
