### ISSUE TITLE
Helper chart different versions

### ISSUE THREAD

**Issue by strainovic** [helm/helm#8315]
Hi all,

I have multiple charts that share one "helper" chart which contains _helper.tpl functions.

If some of them are using a different (older) version of the helper chart, the installation may fail.

In case I specify the "helper" chart in my implementation chart (umbrella chart), will that version override all other "helper" charts in sub-charts or not?

- umbrella-chart

  - helper-v0.1.3

  - chart-1
    - helper-v0.1.1
  - chart-2
    - helper-v0.1.2

During deploy, will I have helper-v0.1.3 overriding all other helper versions as it is specified in parent chart or result is not predictable?

Thanks!

**Comment by jdolitsky** [comment]
@strainovic - the helper charts should work independently, meaning you could have multiple versions. Using an older version as one chart's subchart will not be overridden by the most recent version (helper-v0.1.3)

Maybe I can help guide if I can better understand what you're trying to accomplish.

**Comment by bacongobbler** [comment]
ping.
