### ISSUE TITLE
helm `create` command: too much boilerplate generated

### ISSUE THREAD

**Issue by gWOLF3** [helm/helm#8316]
this issue is pretty self explanatory. 

this is a personal complaint about the amount of boilerplate which is generated by the helm `create` command, with no available flag to not generate it. I find this to be annoying. Maybe other people agree. 

If approved, I would like to submit a PR which adds an optional flag for helm create command to only create the minimal config. 

ie: 

```
helm create --no-boilerplate
```

**Comment by gWOLF3** [comment]
knock knock. anyone home?

**Comment by bacongobbler** [comment]
What would be your suggested minimal level of boilerplate?

**Comment by mattfarina** [comment]
@gWOLF3 To add some context...

* The `helm create` command isn't required for people to use. I've created numerous charts without using it.
* `helm create` can be passed a starter that will scaffold out a different starter chart. Starters are not included with the Helm install
* The chart scaffolded out by `helm create` shows a lot of good practices and parts. That includes labels for k8s, tests, and more. This is helpful in showing people what they can do. Especially when they are newer

With that being said, what would you suggest specifically and why?

**Comment by bridgetkromhout** [comment]
Hi, @gWOLF3 - thanks again for offering your views. We've replied with more context and options, so we're closing this issue as answered. Thanks.
