### ISSUE TITLE
helm lint --with-subcharts verifying global variables is not supported

### ISSUE THREAD

**Issue by Cweiping** [helm/helm#8324]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"2cc6e0a70a", GitTreeState:"clean", BuildDate:"2020-03-26T04:33:27Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
open resource k8s

Make a template containing sub chart package, define the global variable in the template package, use the variable in sub chart, and cannot use `helm lint --with-subcharts` to pass the verification.

Does this feature support? Or open a new feature to improve it.

If I think about perfection, I am willing to complete it.

**Comment by hickeyma** [comment]
Thanks for raising this @Cweiping. Can you provide more details showing the issue with an example? By showing the output it makes it more clear for people to understand the issue.

**Comment by Cweiping** [comment]
Sorry, we just tried to replicate locally, but we found that there was a problem with the logic of template writing. Thank you for your support.
