### ISSUE TITLE
helm subchart requirements are ignored

### ISSUE THREAD

**Issue by m1o1** [helm/helm#8325]
This is probably a feature request rather than a bug report. I thought that putting subcharts in the "charts" directory would allow me to vendor full helm charts inside, including the `requirements.yaml` file. However, when I `helm install` my chart, the subchart's dependencies (`requirements.yaml`) is ignored - and `helm dep up` in my chart doesn't acknowledge it either.

**Reason for making a subchart:**
The subchart I want to install is [prometheus-operator](https://github.com/helm/charts/tree/master/stable/prometheus-operator). I want to vendor it inside `charts` so that I can make modifications. There is a hack script that generates some of the templates that I want to "hook" into / modify. However, I want to keep my modifications completely separate from this chart to make updates easier. This is why I want it to be a subchart as opposed to just forking the helm chart and modifying it. Also if I fork it, it becomes tedious to override values in its `values.yaml` and upgrading becomes a pain (2000 lines of yaml) - though I guess I could supply a separate `values.yaml` and just specify both when helm installing...

One of the requirements of prometheus-operator is grafana. If I move the requirements up a level into my chart, I am unable to set values on grafana through the subchart. It would have the default values of the grafana chart, and anything the prometheus-operator overrides would not be applied.

I was expecting subcharts in the "charts" directory to be able to specify requirements, and a helm install of my chart would aggregate the requirements of subcharts plus the requirements of my "main" chart.

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2019-12-11T12:42:56Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2019-12-11T12:34:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Minikube

**Comment by bacongobbler** [comment]
You are correct: sub-subcharts are ignored. Helm only considers the first level of dependencies. The maintainer who was working on the dependency subsystem stepped down a few years ago, so it's been that way since he left.

However, this is a duplicate feature request of #2247, so I am going ahead and closing this as a duplicate.
