### ISSUE TITLE
helm upgrade is not updating the charts in the cluster

### ISSUE THREAD

**Issue by GloriaPG** [helm/helm#8327]
Hi,
I'm working with helm v2.14.2, we currently have a pipeline that runs this command:

```
helm tiller run tiller - helm upgrade my-release. --set global.cpVersionTag =v1  --set global.baseRepository = private-repository.example
```

The command finishes without errors, the problem is that he doesn't make an update.

I executed this command :
```
helm tiller run tiller - helm get  my-release
```
 I can see my change here, but the deployment and pod running in the cluster aren't update.

I'm not allowed me to paste the YAML but my change is this  (as an example):

```
# A new env var to a container:

            - name: MY_NEW_ENV_VAR 
              value: "https://example/addAsset"

# A new argument to container command:
          command: ["/opt/keycloak-gatekeeper"]
          args: [ "--listen", ":13001", "--upstream-url", "http://127.0.0.1:3001", "--discovery-url",  "https://keycloack.example/auth/realms/example", "--add-claims", "MY-NEW-CHANGE"   ]
```
And as said, I can see the change in output helm tiller run tiller - helm get  my-release  but not into the cluster, in the pod and deployment.

Output of `helm version`:
```
helm tiller run tiller -- helm version
Installed Helm version v2.14.2
Installed Tiller version v2.14.2
Helm and Tiller are the same version!
Starting Tiller...
Tiller namespace: tiller
Running: helm version

Client: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}
Stopping Tiller.
```

Output of `kubectl version`:
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"059c666b8d0cce7219d2958e6ecc3198072de9bc", GitTreeState:"clean", BuildDate:"2020-04-03T15:17:29Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
If someone had this problem before, how did you solve it? I know that using helm upgrade is not the best maybe but right now I can't change that quickly. I will try to move to  Helm 3 and use a template or kubectl apply but I can't migrate now.

Thanks so much!

**Comment by rimusz** [comment]
it looks the Tillerless plugin communicates with your cluster fine.
Can you add `--debug` flag and try to run:
```
helm tiller run tiller - helm upgrade my-release. --set global.cpVersionTag=v1  --set global.baseRepository=private-repository.example --debug
```

**Comment by GloriaPG** [comment]
Hello! After all, the cluster was reinstalled just like helm and triller, at the moment everything seems to be working fine, we couldn't wait to find the problem with helm, so the environment rebooted. I will be watching if this happens again, I will try to find a pattern.

@rimusz I put the debug flag and no problem appears to me, everything seemed to be going well, however, in this new implementation I have left it to have more information about the deployments.

Thanks!

**Comment by bacongobbler** [comment]
Closing for now as there's no action item on our end here. Please re-open if the issue persists. Thanks.
