### ISSUE TITLE
cannot load irregular file it has file mode type bits set 

### ISSUE THREAD

**Issue by witchbutter** [helm/helm#8328]
Output of `helm version`: 
```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-18T02:59:13Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.):  EKS

For some reason I can no longer run `helm dependency update` because it produces a strange error related to a gpg key:
```
Error: cannot load irregular file /Users/username/.gnupg/S.gpg-agent as it has file mode type bits set
```
There do not seem to be any issues regarding gpg otherwise, nor was I expecting helm to interact with GPG in any way.

Here is the directory in question (MacOS 10.15.5):
```
username@computer> ls -la ~/.gnupg/
drwx------  13 username  staff     416 Jun 18 18:27 .
drwxr-xr-x+ 56 username  staff    1792 Jun 18 18:34 ..
srwx------   1 username  staff       0 Jun 18 18:13 S.gpg-agent
srwx------   1 username  staff       0 Jun 18 18:13 S.gpg-agent.browser
srwx------   1 username  staff       0 Jun 18 18:13 S.gpg-agent.extra
srwx------   1 username  staff       0 Jun 18 18:13 S.gpg-agent.ssh
-rw-------   1 username  staff      34 Mar 31 11:50 dirmngr.conf
-rw-------   1 username  staff      41 Mar 31 11:50 gpg-agent.conf
-rw-------@  1 username  staff      34 Jun  9 18:39 gpg.conf
drwx------   2 username  staff      64 Mar 31 11:50 private-keys-v1.d
-rw-------   1 username  staff  228475 Jun  9 18:39 pubring.kbx
-rw-------   1 username  staff  224596 Mar 31 11:50 pubring.kbx~
-rw-------   1 username  staff    1200 Jun  9 18:39 trustdb.gpg
```
I verified the file in the error has no macos extended attributes either.  

What does this error mean?

**Comment by bacongobbler** [comment]
source code for the error can be found here:

https://github.com/helm/helm/blob/2139e82c68e160a713cf19eb3ac55e91aef21cde/pkg/chart/loader/directory.go#L98-L103

Is it possible that your chart may be symlinking to files outisde of the chart directory, including something from your `.gnupg directory?

**Comment by witchbutter** [comment]
That is the right idea, I was at my profile directory rather than in the chart directory I was working on.  Once I cd to the chart, `helm dependency update` works normally.  Pretty ambiguous error.
