### ISSUE TITLE
Helm Chart 2.15 - Upgrade is not doing rolling update for existing Docker image tag

### ISSUE THREAD

**Issue by bikashkumars** [helm/helm#8329]
Application is deployed in Kubernetes using helm Chart v2.15. Here docker image name was **example-image:1.0.0**
Here in the deployment, we have also configured ConfigMap, Secrets.

Now we are rebuilding Application with same docker Image name and tag as **example-image:1.0.0**

Now using Helm Upgrade we want to upgrade configMap, Secrets and Application Rolling upgrade. But we don't want to change the Docker imageName and Tag.
Note - We don't want to Pass helm upgrade --recreatepod

**Requirement:**
1. --recreatepod  -> this creates Application downtime
2. Requirement is, without downtime, we want to upgrade Application Image/Pod, ConfigMap and Secrets

Output of `helm version`: v2.15.0-rc.1

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  We are using Docker for windows based Kubernetes (not minikube)

**Comment by bikashkumars** [comment]
Do to some special requirement, we can't change the docker tag.
Also In helm chart Image pull is set to "Always"

**Comment by bacongobbler** [comment]
Hi @bikashkumars. I can't fully understand what you are trying to convey here. Can you please elaborate a little more? Perhaps by demonstrating your issue with an example would help.

Also, please make sure to test against the latest version of Helm 2 (as of today, Helm v.2.16.9 is the latest).

**Comment by bacongobbler** [comment]
ping.

**Comment by bikashkumars** [comment]
@bacongobbler my question was - Without changing docker tag, how we can force helm chart for rolling update. My intention was to force pull docker image with same tag and redeploy as pod again with rolling update.

I dont want to use --recreatepod during helm install, as it creates downtime
