### ISSUE TITLE
install from repo fails if repo alias name contains '/'

### ISSUE THREAD

**Issue by liuming-dev** [helm/helm#8333]
Output of `helm version`: `version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}`

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

**Case description**:

```bash
helm repo add [NAME] [URL] [flags]
```
When the repo `NAME` contains `/`, install chart from this repo will fail.

For such cases, the following codes cannot work as expected, we could not get `repoName` and `chartName` correctly.

https://github.com/helm/helm/blob/561cc4280830af4a40f2e60c5f17fb3ee69b4e39/pkg/downloader/chart_downloader.go#L197-L205

And a very special case is that the repo name is a absolute URL, such as `https://docker-reg.sogou-inc.com/chartrepo/publish-dev`

**How to reproduce**

```bash
# apple @ liuming-dev in ~/.kube [16:29:26]
$ helm repo add docker-reg.sogou-inc.com/chartrepo/publish-dev https://docker-reg.sogou-inc.com/chartrepo/publish-dev
"docker-reg.sogou-inc.com/chartrepo/publish-dev" has been added to your repositories

# apple @ liuming-dev in ~/.kube [16:29:36]
$ helm repo list
NAME                                          	URL
docker-reg.sogou-inc.com/chartrepo/publish-dev	https://docker-reg.sogou-inc.com/chartrepo/publish-dev

# apple @ liuming-dev in ~/.kube [16:29:41]
$ helm install test docker-reg.sogou-inc.com/chartrepo/publish-dev/thanos-deployment --kubeconfig ./dev -n testzy
Error: failed to download "docker-reg.sogou-inc.com/chartrepo/publish-dev/thanos-deployment" (hint: running `helm repo update` may help)

```

**Possible solutions**

- solution one: do not allow to add a repo with name containing `/`, and add some check when `helm add repo`
- solution two: change the code logic of getting `repoName` and `chartName`

For me, I prefer to the solution two, and I need to know which solution you support, or another possible solution.

I would like to fix this, and I need some feedback.

**Comment by akashshinde** [comment]
@liuming-dev I would prefer allowing `/` in the repo name, not sure if there was any reason behind now allowing it.

**Comment by hickeyma** [comment]
@liuming-dev I have updated the title to better describe the issue. I think he issue is because the alias name for the repo contains a `/` and not the repo URL that you add.

This seems to be working as designed because when you install a chart using a repo alias, the command is as follows: `helm install <repo_alias_name>/chart`. The code is written to check for the `/` and separate the repo alias name from the chart. It can then resolve the repo from the alias.

You can specify the repo URL directly also (not using an alias) and this would contains the `/` separators. More details in: https://helm.sh/docs/helm/helm_install/

**Comment by liuming-dev** [comment]
> The code is written to check for the / and separate the repo alias name from the chart. It can then resolve the repo from the alias.

It seems the code is not working correctly when the repo alias name contains `/`.
> For such cases, the following codes cannot work as expected, we could not get `repoName` and `chartName` correctly.


Quick way to reproduce:

```bash
# apple @ liuming-dev in ~/.kube [17:10:20]
$ helm repo list
NAME                                    	URL
mirror_azure_cn__stable                 	http://mirror.azure.cn/kubernetes/charts/
mirror.azure.cn/kubernetes/charts/      	http://mirror.azure.cn/kubernetes/charts/

# apple @ liuming-dev in ~/.kube [17:10:30]
$ helm install redis mirror.azure.cn/kubernetes/charts/redis
Error: failed to download "mirror.azure.cn/kubernetes/charts/redis" (hint: running `helm repo update` may help)

# apple @ liuming-dev in ~/.kube [17:10:38] C:1
$ helm install redis mirror_azure_cn__stable/redis
WARNING: This chart is deprecated
NAME: redis
LAST DEPLOYED: Mon Jun 22 17:10:55 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
This Helm chart is deprecated

...
```

**Comment by mattfarina** [comment]
We can update the docs to improve this by listing the allowed characters for a repo name.

Using `/` in the name is likely not going to happen. It isn't as simple as updating a few internals. There are a significant number of internal changes that would need to happen and it would introduce some places where collisions could, in theory, happen. This would need to be dealt with and tested.

If someone wants to attempt to make it possible to use `/` as a character in a repo name I am supportive. I just know it's going to take some work and will require a bit of testing.

**Comment by bacongobbler** [comment]
+1 to what @mattfarina said. Assuming we start to accept `/` in the repository name is likely going to bring up a lot of deeply-engrained business logic in helm's internals assuming that there's no slashes in the repository name. The easier solution would be to reject repository names with a slash.

If someone wants to do a deeper dive into figuring out how to accept slashes in repository names, feel free. I do not expect it to be easy work, and we will need it to be well-tested.
