### ISSUE TITLE
Is Support for "apiVersion=v1" Charts Included in the Long-Term Plan

### ISSUE THREAD

**Issue by Xtigyro** [helm/helm#8336]
- From https://helm.sh/docs/topics/v2_v3_migration/:

> Helm 2 charts (apiVersion=v1) are still installable

- From https://helm.sh/docs/topics/charts/#the-apiversion-field:

> Charts supporting previous Helm versions have an apiVersion set to v1 and are still installable by Helm 3.

Are there plans for changing this in the future? And could we mention that in more details in the docs?

**Comment by hickeyma** [comment]
@Xtigyro Yes, there are supported for Helm 3. This may change for Helm 4.

**Comment by Xtigyro** [comment]
@hickeyma Thank you for the precise and swift reply! I appreciate it.

**Comment by hickeyma** [comment]
Not a bother @Xtigyro. If this answers your question, will I close the issue?

**Comment by Xtigyro** [comment]
@hickeyma I have no further questions. 

It's up to you whether the official docs should be updated with a bit more details (a few links pasted in the first post).

**Comment by hickeyma** [comment]
Ok, thanks. I think the docs are sufficient. Closing as answered.
