### ISSUE TITLE
How to load file contents into a dict in helm

### ISSUE THREAD

**Issue by himmakam** [helm/helm#8337]

**Comment by hickeyma** [comment]
@himmakam Some suggestions in https://github.com/helm/helm/issues/8020 and https://stackoverflow.com/questions/55345358/convert-yaml-string-to-dict-in-helm-template that might be worth trying.

**Comment by hickeyma** [comment]
@himmakam Example from @tamalsaha in https://github.com/helm/helm/issues/8020#issuecomment-648272488:

```yaml
{{- $res := .Values.resources -}}
{{- $machines := .Files.Get "data/machines.yaml" | fromYaml -}}
{{- if and .Values.machine (hasKey $machines .Values.machine) }}
  {{- $res := get (get $machines .Values.machine) "resources" }}
{{- end }}
```

**Comment by mattfarina** [comment]
There is a page in the docs on this at https://helm.sh/docs/chart_template_guide/accessing_files/. Does that help?

**Comment by hickeyma** [comment]
@himmakam Did you get this working as per the thread in #8020?

**Comment by bridgetkromhout** [comment]
Closing as answered.
