### ISSUE TITLE
pre-install hook not being executed

### ISSUE THREAD

**Issue by tibcoplord** [helm/helm#8339]
Output of `helm version`: 

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0-4-g38212b5", GitCommit:"2576e482bf003e34e67ba3d69edcf5d411cfd6f3", GitTreeState:"clean", BuildDate:"2020-05-12T06:50:39Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

```
docker for desktop with kubernetes installed on mac
```

The attached chart attempts to install the nexus operator via a pre-install hook.  Once done, the Nexus CRD should get loaded.  The docs (https://helm.sh/docs/topics/charts_hooks/#hooks-and-the-release-lifecycle) indicate that the pre-install hook should get executed before the Nexus CRD is loaded into kubernetes.

However I see an error pretty quickly -

```
$ sh -x run.sh 
+ helm package test
Successfully packaged chart and saved it to: /Users/plord/workspace/reproductions/helm/test-1.0.0.tgz
+ helm install test test-1.0.0.tgz
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Nexus" in version "apps.m88i.io/v1alpha1"
```

So the pre-install hook wasn't called first.

If I remove the Nexus CRD from the template, then I do see the nexus operator created ... but not a useful work-around since I want both in the same chart.

[repo.zip](https://github.com/helm/helm/files/4820662/repo.zip)

**Comment by bacongobbler** [comment]
When the chart is loaded, it renders *all* of the templates, then they are all validated in one step by Kubernetes. This occurs before any hooks are run. That is why your chart is failing validation prior to the pre-install hook executing.

If your chart requires a particular CRD to be registered, you need to create that CRD either [beforehand with kubectl](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#create-a-customresourcedefinition) or by [placing them in the `crds/` directory](https://helm.sh/docs/topics/charts/#custom-resource-definitions-crds). Using a pre-install hook to register a CRD will not work here. This is why the `crds/` directory (and the `crd-install` hook for Helm 2) were introduced to work around some of Kubernetes' validation logic.

Hope this helps.

**Comment by tibcoplord** [comment]
Maybe the docs need clarify ?  

Step 5 tells us that only the pre-install hooks are loaded into kubernetes

**Comment by bacongobbler** [comment]
I beileve this is explained in the documentation under step 3 ("CRDs in the `crds/` directory are installed"). Further clarification is provided in the section under [CRDs](https://helm.sh/docs/topics/charts/#custom-resource-definitions-crds:):

> When Helm installs a new chart, it will upload the CRDs, pause until the CRDs are made available by the API server, and then start the template engine, render the rest of the chart, and upload it to Kubernetes.

If you feel like there's something missing from the documentation that I explained above, please feel free to send a pull request.
