### ISSUE TITLE
Range syntax applies variables, unable to render the problem

### ISSUE THREAD

**Issue by qixiang-liu** [helm/helm#8341]
{{- range $value := .Values.env.configMapKV }}
            - name : {{ $value }}
              valueFrom:
                configMapKeyRef:
                  name: {{ template "mod-chart.fullname" . }}
                  key: {{ $value }}
          {{- end }}

Output of `helm version`:
3.2.4

helm template -f ./values.yaml  .

Error: 
template: helm-chart/templates/_helpers.tpl:15:14: executing "mod-chart.fullname" at <.Values.fullnameOverride>: can't evaluate field Values in type string
helm.go:84: [debug] template: helm-chart/templates/_helpers.tpl:15:14: executing "mod-chart.fullname" at <.Values.fullnameOverride>: can't evaluate field Values in type string

**Comment by qixiang-liu** [comment]
range语法里面套用其他变量，导致无法渲染；
Other variables are used in the range syntax, so it cannot be rendered

**Comment by mattfarina** [comment]
Inside of a range loop the value of `.` is set to be the value. You can use `$` instead. `$` is aliased to the root data object and does not change through execution.

**Comment by bridgetkromhout** [comment]
Closing as answered.

**Comment by RajGondalia7** [comment]
@mattfarina, is it something like {{- range $value := $.Values.env.configMapKV }} instead of {{- range $value := .Values.env.configMapKV }}
