### ISSUE TITLE
Make Tiller Image Available on Docker Hub

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#8346]
When [Helm v2 hits it's end of life](https://github.com/helm/helm/issues/8343) the container repository hosted in gcr is likely going to be garbage collected. So that people can continue to get Tiller as an image since some will not migrate yet, I propose we:

1. Make the Tiller images available in Docker Hub in addition to GCR
2. Make Helm use the image in Docker Hub starting v2.17.0

This way people can get their images and things continue to keep working.

On Docker Hub we can use the helmpack arg (we already have that, I think).

**Comment by mattfarina** [comment]
All of the tagged images are now available on Docker Hub. You can see them at https://hub.docker.com/repository/docker/helmpack/tiller/tags?page=1

We still need to:
- [ ] automate putting new images here
- [ ] Have helm use the new location
- [ ] Document the location on Docker Hub so that people know what's going on

**Comment by mattfarina** [comment]
This is complete. closing

**Comment by rafis** [comment]
Also here:
docker pull ghcr.io/helm/tiller:v2.16.12
