### ISSUE TITLE
how to make use of helm install in offline mode (servers are not internet enabled)

### ISSUE THREAD

**Issue by argunasekhar** [helm/helm#8347]
Hi - 

i've a server, which is not internet enabled (offline)
i'm trying to install couchbase in my k8s cluster through helm charts , and i have loaded docker images of couchbase already, but still my helm is looking for images and throwing below error

```
[root@k8s-master-1 ~]# kubectl logs -f deployment/crdl-couchbase-operator  --namespace crdl
Error from server (BadRequest): container "couchbase-operator" in pod "crdl-couchbase-operator-6d4565594c-96gz4" is waiting to start: image can't be pulled
```

**Comment by bacongobbler** [comment]
Hi @argunasekhar. Were you able to resolve your issue? I notice this has been open for a few months now so I wanted to check in and see if you found a solution.

**Comment by bacongobbler** [comment]
Given that this is a support question related to a chart we don't know about, it's hard to determine how we can help out here. My gut feeling is that you should probably go and ask the authors of the couchbase-operator chart about your question. This seems like a question related to how this chart can be used in an offline scenario, and they would be better suited to answer your question.

**Comment by bridgetkromhout** [comment]
Hi, @argunasekhar - we cannot provide further assistance without being able to see the chart. I'm closing this issue for that reason. If you would like to return and let us know more details, we can try to help. Thanks.
