### ISSUE TITLE
helm package --sign throws "Error: private key not found" (GPG)

### ISSUE THREAD

**Issue by dbafromthecold** [helm/helm#8353]
Hi, I'm having a similar issue to 
https://github.com/helm/helm/issues/7631
https://github.com/helm/helm/issues/4975

However the fixes detailed in those issues are not working for me.

I'm trying to sign a Helm chart but no matter what I use to identify my key I keep getting: -
`Error: private key not found`

The steps I'm running through are: -

`gpg --full-generate-key`
(Accepting the defaults, 4096 bit key, have tried with and without passphrase)

`gpg --list-secret-keys `
```
--------------------------------------------------------
sec   rsa4096/6C596A1AC0EC12C0 2020-06-26 [SC]
      64DDE0D8F1DD007E94FBD7B36C596A1AC0EC12C0
uid                 [ultimate] Andrew Pruski (key to sign Helm Charts) <andrew.pruski@example.com>
ssb   rsa4096/5E000DE0ABD5D6A5 2020-06-26 [E]
--------------------------------------------------------
```
`gpg --export-secret-keys > secring.gpg`

`helm package --sign --key 'Andrew Pruski' --keyring secring.gpg mychart`

No matter how I try to identify the key I keep getting the same error. Am I doing something wrong here?

Thanks in advance,

Andrew

Output of `winver`:
Version 2004 (OS Build 19041.329)

Output of `helm version`:
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Docker Desktop with WSL 2 enabled

**Comment by bacongobbler** [comment]
Hey @dbafromthecold.

First off, you might want to rotate your private key... General rule of thumb is that you should avoid posting any information related to your private key in a public forum. Use `gpg --list-keys` in the future to list your public key. :)

Does anything pop up if you try to sign the package with `gpg --sign`? It's possible there's some underlying issue with your pgp setup causing the issue.

https://www.gnupg.org/gph/en/manual/x135.html

For reference, here's the place in Helm where that issue is propagated, which would indicate the private key entity was not loaded into Helm properly.

**Comment by dbafromthecold** [comment]
Thank you for the rely.

The key listed is only used to highlight the issue that I'm seeing, it'll be deleted once I get this resolved.

I've run through the signing process on another instance of Windows 10 and am getting the same issue.

`gpg --sign` isn't coming back with any errors, it seems to be working.

**Comment by dbafromthecold** [comment]
Still trying with this but no luck so far. Anyone else seen this issue?
