### ISSUE TITLE
Helm dependency update 0.0.0+x pulls a random chart with 0.0.0 tag

### ISSUE THREAD

**Issue by parthpower** [helm/helm#8356]
Hi,

We publish our charts in `x.y.z+metadata` format and non-tagged versions have `0.0.0` as the semver version. However, when I try to add a dependency for let's say `0.0.0+x`, the `helm dependency update` pulls a random `0.0.0+y`. The `y` here keeps changing every time I do the  `helm dependency update`

Is this expected behavior? and Is there a way to get around this? 

Thanks,
Parth

Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

**Comment by mattfarina** [comment]
This has to do with semantic version. You can read the spec at https://semver.org/.

The metadata section of the version is not used for sorting. So, `0.0.0+a` and `0.0.0+b` are equivalent versions. This is per the spec. Specifically, the spec says:

> Build metadata MUST be ignored when determining version precedence.

Versions are essentially [major].[minor].[patch]-[optional pre-release]+[optional metadata]. The pre-release part means it comes before the patch. This can be used for sorting. But, the spec notes that the API may not be the same between the release or pre-release.

In this case, Helm is performing to the spec.

**Comment by parthpower** [comment]
Thank you for the explanation. @mattfarina
