### ISSUE TITLE
Error: Kubernetes cluster unreachable

### ISSUE THREAD

**Issue by wuchenyanghaoshuai** [helm/helm#8358]
![image](https://user-images.githubusercontent.com/39818267/85936490-f303c980-b92d-11ea-81c0-a41d9c56ba53.png)
i don't know how to do the next
help me please

**Comment by liuming-dev** [comment]
It seems that client cannot connect to kubernetes cluster, please check the kubeconfig file in the $HOME/.kube first

**Comment by hickeyma** [comment]
@wuchenyanghaoshuai Helm should connect to the cluster like `kubectl` does. Using [kubeconfig file](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/) as @liuming-dev mentioned above.

**Comment by mattfarina** [comment]
@wuchenyanghaoshuai welcome to the Helm project. Helm uses your existing kubeconfig file. kubectl and many other projects use this same configuration when interacting with a cluster. You will typically get this configuration from your cloud provider or whom ever set up your Kubernetes cluster. If you are using something like Minikube or Docker Desktop it will automatically be set.

**Comment by wuchenyanghaoshuai** [comment]
> @wuchenyanghaoshuai欢迎您加入Helm项目。Helm使用您现有的kubeconfig文件。与集群交互时，kubectl和许多其他项目使用相同的配置。通常，您将从云提供商或设置Kubernetes集群的人那里获得此配置。如果您使用的是Minikube或Docker Desktop之类的东西，它将自动设置。

thank you

**Comment by wuchenyanghaoshuai** [comment]
> It seems that client cannot connect to kubernetes cluster, please check the kubeconfig file in the $HOME/.kube first

thank you

**Comment by wuchenyanghaoshuai** [comment]
> @wuchenyanghaoshuai Helm should connect to the cluster like `kubectl` does. Using [kubeconfig file](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/) as @liuming-dev mentioned above.

thank you

**Comment by wuchenyanghaoshuai** [comment]
export KUBERNETES_MASTER=http://127.0.0.1:8080
use this command to solve it

**Comment by hickeyma** [comment]
@wuchenyanghaoshuai It is good that your issue has been resolved.

I am going to close as the issue has been resolved.

**Comment by vagdevik** [comment]
Make sure your cluster is connected with Kubernetes configuration file: [https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl#generate_kubeconfig_entry](https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl#generate_kubeconfig_entry)

**Comment by olevezinho** [comment]
Had a similar issue. The following export solved it:
`export KUBECONFIG=~/.kube/config`

**Comment by SuzukiHonoka** [comment]
> export KUBERNETES_MASTER=http://127.0.0.1:8080 use this command to solve it

bullshit, proxy is not the actuall reason, are you using helm controls the remote cluster??
