### ISSUE TITLE
Add suggestive self-examination to abnormal situations and use general error mechanism

### ISSUE THREAD

**Issue by Cweiping** [helm/helm#8359]
Issue:
There is no doubt that the group of helm users is becoming more and more popular, but we just intuitively throw out problems and do not give empirical suggestions for users to self-check. Whether we consider adding a general prompt mechanism to provide some common errors to guide users to self-check. To some extent, this method solves many problems of [question/support](url) type in the issue list.

How to:
Filter all command errors, and show some solutions to match errors.

Goal:
Accumulate wrong solutions, and let helm be used by more people who don't understand k8s or code.

Note:  The above are just some immature suggestions of my own. Welcome to discuss them together.If the proposal is not considered, it can be closed directly.

**Comment by bridgetkromhout** [comment]
Related to https://github.com/helm/helm/pull/8357

**Comment by bridgetkromhout** [comment]
Hi, @Cweiping - Thank you for your ideas. Helm currently has the auto-generated docs (found in the CLI as well as at https://helm.sh/docs/helm/), which have links to some related commands. If you would like to add to the CLI docs, that would be helpful. You can find that command output in https://github.com/helm/helm/tree/master/cmd/helm.

It sounds like you may be suggesting training a model to suggest good troubleshooting steps. That sounds intriguing, but also fairly complex. I'm going to close this issue in favor of you proposing your improvement ideas with the formal [Helm Improvement Proposal](https://github.com/helm/community/blob/master/hips/hip-0001.md) process, if you like. That would allow the community to help shape what this new approach could be. Thanks!
