### ISSUE TITLE
Unable to read files using common library

### ISSUE THREAD

**Issue by florentvaldelievre** [helm/helm#8360]
I am suspecting a bug when trying to use a file from a library chart. Helm fails when I try to access a file from the library. I have followed the example from the [library_charts documentation](https://helm.sh/docs/topics/library_charts/).

Everything is the same as the documentation except two parts: I have added the file mylibchart/files/foo.conf and this file is referenced in mylibchart/templates/_configmap.yaml's data key (in the documentation, data is an empty object):

```
├── mychart
│   ├── Chart.yaml
│   └── templates
│       └── configmap.yaml
└── mylibchart
    ├── Chart.yaml
    ├── files
    │   └── foo.conf
    └── templates
        ├── _configmap.yaml
        └── _util.yaml
```

```
cat mylibchart/templates/_configmap.yaml
{{- define "mylibchart.configmap.tpl" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name | printf "%s-%s" .Chart.Name }}
data:
  fromlib: yes
{{ (.Files.Glob "files/foo.conf").AsConfig | nindent 2 }}
{{- end -}}
{{- define "mylibchart.configmap" -}}
{{- include "mylibchart.util.merge" (append . "mylibchart.configmap.tpl") -}}
{{- end -}}
```
When you run  `helm template .`  from mychart, an error occurs because helm is looking for mychart/files/foo.conf and it does not exist. If I create it, it does not crash, but contains mychart/files/foo.conf's content instead of mylibchart/files/foo.conf's content. The file foo.conf does exist inside the file generated by `helm dependency update` (mychart/charts/mylibchart-0.1.0.tgz).
This issue prevents me to use common files to multiple charts. 

Is it possible to use the file from the library on a chart or is it a limitation, or a bug ? The fact that the file is present in 'mychart/charts/mylibchart-0.1.0.tgz' makes me think that this is rather a bug

You can easily reproduce the issue by cloning the project: https://github.com/florentvaldelievre/helm-issue

Helm version:

`version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"}`

**Comment by bacongobbler** [comment]
It is not possible to use files from a library chart. When it is marked as a library, all files are ignored and omitted from the rendering process. Only the functions it provides are included.

**Comment by florentvaldelievre** [comment]
Thank you for gettting back to me. If its not possible to use files from library chart,

1. Why files are included in the tar.gz ? They could simply be discarded from the archive
2. A simple note in the documentation saying that it's not possible to use files in the library would be nice. I am not the only one in this case. See [here](https://github.com/helm/helm/issues/8200) and [here](https://stackoverflow.com/questions/61732678/helm-3-access-files-of-library-chart)
