### ISSUE TITLE
helm upgrade --install --wait --force says UPGRADE FAILED

### ISSUE THREAD

**Issue by lapolonio** [helm/helm#8362]
```
helm upgrade --install --wait --force --debug \
    --version=8.15.6 \
    --namespace=$NAMESPACE \
    $RELEASE_NAME \
    stable/prometheus-operator
```
> Installing prometheus-operator
> namespace: monitoring
> cloud: ibm
> history.go:52: [debug] getting history for release prometheus-operator
> upgrade.go:121: [debug] preparing upgrade for prometheus-operator
> Error: UPGRADE FAILED: "prometheus-operator" has no deployed releases
> helm.go:84: [debug] "prometheus-operator" has no deployed releases
> UPGRADE FAILED
> main.newUpgradeCmd.func1
>         /private/tmp/helm-20200619-73670-pk36oo/cmd/helm/upgrade.go:146
> github.com/spf13/cobra.(*Command).execute
>         /private/tmp/helm-20200619-73670-pk36oo/.brew_home/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
> github.com/spf13/cobra.(*Command).ExecuteC
>         /private/tmp/helm-20200619-73670-pk36oo/.brew_home/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
> github.com/spf13/cobra.(*Command).Execute
>         /private/tmp/helm-20200619-73670-pk36oo/.brew_home/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
> main.main
>         /private/tmp/helm-20200619-73670-pk36oo/cmd/helm/helm.go:83
> runtime.main
>         /usr/local/Cellar/go/1.14.3/libexec/src/runtime/proc.go:203
> runtime.goexit
>         /usr/local/Cellar/go/1.14.3/libexec/src/runtime/asm_amd64.s:1373

Output of `helm version`:
```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-18T02:59:13Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12+IKS", GitCommit:"6e45cfa419b622aaa927ca3fe39a7da8691306e0", GitTreeState:"clean", BuildDate:"2020-06-12T00:11:55Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
IBM Cloud (IKS)

**Comment by hickeyma** [comment]
@lapolonio Thanks for raising the issue. I have tried to reproduce it from `master` as follows:

```console
$ helm ls
NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART	APP VERSION

$ helm upgrade --install --wait --force --debug --version=8.15.6 prom1 stable/prometheus-operator
history.go:52: [debug] getting history for release prom1
Release "prom1" does not exist. Installing it now.
install.go:172: [debug] Original chart version: "8.15.6"
install.go:189: [debug] CHART PATH: /root/.cache/helm/repository/prometheus-operator-8.15.6.tgz

client.go:108: [debug] creating 1 resource(s)
client.go:108: [debug] creating 1 resource(s)
client.go:108: [debug] creating 1 resource(s)
client.go:108: [debug] creating 1 resource(s)
client.go:108: [debug] creating 1 resource(s)
client.go:108: [debug] creating 1 resource(s)

[....]

NOTES:
The Prometheus Operator has been installed. Check its status by running:
  kubectl --namespace default get pods -l "release=prom1"

Visit https://github.com/coreos/prometheus-operator for instructions on how
to create & configure Alertmanager and Prometheus instances using the Operator.

$ helm ls
NAME 	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART                     	APP VERSION
prom1	default  	1       	2020-06-29 08:27:41.735744595 +0000 UTC	deployed	prometheus-operator-8.15.6	0.38.1   
```

It is working as expected.  I remember an issue with this previously but can find the issue # at the moment.

Would you be able to test this against `master` branch?

**Comment by lapolonio** [comment]
it actually turns out it was due to an unclean state
