### ISSUE TITLE
Helm template doesn't properly parse EKS clusters versions.

### ISSUE THREAD

**Issue by asherf** [helm/helm#8365]
I have a chart with the following constraint in the chart.xml file:
```yaml
kubeVersion: ">=v1.16.8-0,<v1.19-0"
```
running `helm install` or `helm upgrade` to that chart works just fine.
However, running `helm template <my-chart> ` results in an error, I think the underlying issue is not properly parsing the helm version that the AWS EKS cluster reports (`Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311"`).

The error is as follows:
```
Error: chart requires kubeVersion: >=v1.16.8-0,<v1.19-0 which is incompatible with Kubernetes v1.16.0
helm.go:84: [debug] chart requires kubeVersion: >=v1.16.8-0,<v1.19-0 which is incompatible with Kubernetes v1.16.0
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
        /private/tmp/helm-20200508-23207-1ycgb97/src/helm.sh/helm/pkg/action/action.go:110
helm.sh/helm/v3/pkg/action.(*Install).Run
        /private/tmp/helm-20200508-23207-1ycgb97/src/helm.sh/helm/pkg/action/install.go:238
main.runInstall
        /private/tmp/helm-20200508-23207-1ycgb97/src/helm.sh/helm/cmd/helm/install.go:229
main.newTemplateCmd.func1
        /private/tmp/helm-20200508-23207-1ycgb97/src/helm.sh/helm/cmd/helm/template.go:66
github.com/spf13/cobra.(*Command).execute
        /private/tmp/helm-20200508-23207-1ycgb97/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
        /private/tmp/helm-20200508-23207-1ycgb97/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
        /private/tmp/helm-20200508-23207-1ycgb97/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
        /private/tmp/helm-20200508-23207-1ycgb97/src/helm.sh/helm/cmd/helm/helm.go:83
runtime.main
        /usr/local/Cellar/go@1.13/1.13.10_1/libexec/src/runtime/proc.go:203
runtime.goexit
```

Output of `helm version`:
`version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}`
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T14:51:23Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

AWS EKS 
<img width="948" alt="Screen Shot 2020-06-28 at 7 38 32 PM" src="https://user-images.githubusercontent.com/1268088/85967275-f66f7300-b976-11ea-928c-4439af527ebf.png">

**Comment by mattfarina** [comment]
The `helm template` command is meant to be run apart from a Kubernetes cluster. For security reasons, running `helm template` does not attempt to interact with a Kubernetes cluster. The Kubernetes version it uses is a default value stored internally within Helm.

The help text for the template command notes:

> Any values that would normally be looked up or retrieved in-cluster will be faked locally.

The default capabilities are in the code at https://github.com/helm/helm/blob/fbdda53585b3ba69be515a45b0eeea45c930d353/pkg/chartutil/capabilities.go#L32-L37.

Does this help explain what's going on?

**Comment by asherf** [comment]
> The `helm template` command is meant to be run apart from a Kubernetes cluster. For security reasons, running `helm template` does not attempt to interact with a Kubernetes cluster. The Kubernetes version it uses is a default value stored internally within Helm.
> 
> The help text for the template command notes:
> 
> > Any values that would normally be looked up or retrieved in-cluster will be faked locally.
> 
> The default capabilities are in the code at
> 
> https://github.com/helm/helm/blob/fbdda53585b3ba69be515a45b0eeea45c930d353/pkg/chartutil/capabilities.go#L32-L37
> 
> .
> Does this help explain what's going on?

@mattfarina thanks for the reply!
I don't follow, from looking at the code,  it seems to me that helm does call a cluster API to get the version, as the helm template command uses the helm install command in dry run mode.
Looking at the 3.2 branch/tag:
https://github.com/helm/helm/blob/0ad800ef43d3b826f31a5ad8dfbb4fe05d143688/pkg/action/install.go#L216
the call to `i.cfg.getCapabilities()` 
which then calls an [API on the k8s rest client](https://github.com/helm/helm/blob/0ad800ef43d3b826f31a5ad8dfbb4fe05d143688/pkg/action/action.go#L243) that returns the server version.
This is the behavior in the 3.2.1 release that I have... looking at the current code in this repo, things seem to have changed..

**Comment by mattfarina** [comment]
There's a little more to the code. When `helm template` is typically run it's in client only mode. That causes the following to run...

https://github.com/helm/helm/blob/561cc4280830af4a40f2e60c5f17fb3ee69b4e39/pkg/action/install.go#L194-L203

This sets some default capabilities. When those are set `getCapabilities` returns them instead of calling out to the cluster...

https://github.com/helm/helm/blob/561cc4280830af4a40f2e60c5f17fb3ee69b4e39/pkg/action/action.go#L235-L237

If you don't mind me asking, why does the kubeVersion need such precise setting?

**Comment by asherf** [comment]
Ah that makes sense... since if there was an actual issue with the version parsing, install would have probably failed too.
And you are correct... in our case, we don't need such a precise constraint on KubeVersion, it is just something I inherited.
I'll go ahead and relax the constraint. 
Thanks for the help & guidedance!
