### ISSUE TITLE
Helm 3 remove(already exist) patched resources 

### ISSUE THREAD

**Issue by alexandrsemak** [helm/helm#8372]
Output of `helm version`:
v3.2.4
Output of `kubectl version`:
v1.16.11

Helm 3 allow you patching already exist resources but after uninstall helm chart patched resources also deleted

**Comment by mattfarina** [comment]
@alexandrsemak Are you suggesting that Helm v3, on install of an application, is taking over existing resources because the name matches those that are already in the cluster? Then on delete is removing them.

Could you provide a more detailed example.

**Comment by alexandrsemak** [comment]
@mattfarina I already have ConfigMap for app which was installed by Helm 3 and by chance install second app by Helm 3 with the same ConfigMap name and namespace so second map patching this ConfigMap which was installed by first app and after uninstall second app helm also delete ConfigMap which was patched but install by first app.
both were installed by `helm upgrade --install --force`

**Comment by bacongobbler** [comment]
can you demonstrate this with an example? In order to test and confirm this behaviour, we need to be able to reproduce the issue. Thanks.

**Comment by liuming-dev** [comment]
I could not reproduce this case

```bash
# apple @ liuming-dev in ~/.kube [18:07:07]
$ helm upgrade configmap1 ./helm-chart-sample --install --force
Release "configmap1" does not exist. Installing it now.
NAME: configmap1
LAST DEPLOYED: Tue Jun 30 18:08:03 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None

# apple @ iuming-dev in ~/.kube [18:08:03]
$ kubectl get configmap configmaptest -o yaml
apiVersion: v1
data:
  kubernetesServiceHost: dev.master.thanos.sogou
  kubernetesServicePort: "6443"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: configmap1
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2020-06-30T10:08:03Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: configmaptest
  namespace: default
  resourceVersion: "1841664"
  selfLink: /api/v1/namespaces/default/configmaps/configmaptest
  uid: 43f85836-883e-42d4-aa88-759f0d37faf4

# apple @ iuming-dev in ~/.kube [18:08:14]
$ vi helm-chart-sample/templates/configmap.yaml

# apple @ liuming216448 in ~/.kube [18:08:36]
$ helm upgrade configmap2 ./helm-chart-sample --install --force
Release "configmap2" does not exist. Installing it now.
Error: rendered manifests contain a resource that already exists. Unable to continue with install: ConfigMap "configmaptest" in namespace "default" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "configmap2": current value is "configmap1"
```

**Comment by bridgetkromhout** [comment]
Hi, @alexandrsemak - thank you for reaching out. As you may have seen, we've been unable to reproduce this issue, which is why we're closing it now. We'd be happy to look at an issue with a reproducible test case so that we can diagnose and fix. Thanks.
