### ISSUE TITLE
Skip JSON Schema validation during the install /upgrade of a Chart

### ISSUE THREAD

**Issue by Moser-ss** [helm/helm#8375]
Hey.

We are building our templates in Helm, and we are using the Schema Files. This file is useful when we are using the command template, but when we are installing our upgrading a chart, we would like to skip the schema validation.

Do you think it is possible/make sense to do that?

**Comment by hickeyma** [comment]
@Moser-ss The current design is to perform schema validation for some Helm operations when the schema file is present in the chart root. Could you describe in more detail your use case for wanting validation on `template` but not `install/upgrade`?

**Comment by Moser-ss** [comment]
After some experiments, I understand why I have this issue. So when I try to install the chart and use the flag --set it looks that cleans all the object Values, that means it is not using any value from the values.yaml that was packaged with the chart.
In other words, when I do `helm install mypackage private-repo/mypackage` it uses the values in values.yaml, but when I do helm install mypackage private-repo/mypackage --set foo=bar` doesn't use any values from values.yaml.  I know this is already another question, but is this an expected behavior?
