### ISSUE TITLE
Is this not enough ?

### ISSUE THREAD

**Issue by Bob9098-source** [helm/helm#8376]
Is this not enough ?
FAQ: https://helm.sh/docs/faq/#release-names-are-now-scoped-to-the-namespace
Charts: https://v3.helm.sh/docs/topics/charts/#the-chart-file-structure
it is also consider bad practice to hard code the name of the releases: https://v3.helm.sh/docs/chart_template_guide/getting_started/#adding-a-simple-template-call

_Originally posted by @NargiT in https://github.com/helm/helm/issues/7104#issuecomment-592746523_

**Comment by bacongobbler** [comment]
Please continue to comment on the original issue. That way we can track the discussion in one place. Thanks.
