### ISSUE TITLE
pkg/downloader: latest version is not actually correct (as for chartmuseum)

### ISSUE THREAD

**Issue by scbizu** [helm/helm#8378]
### Output of `helm version`:
<details>
<summary>$ helm version </summary>
<code>version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}</code>
</details>

### Output of `kubectl version`:
<details>
<summary> $ kubectl version</summary>
<code>Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}</code>
</details>

### Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

minikube

### Description

Hi there ! I found a little confusing problem these days : When I push new chart to my remote chart registry (self-deployed [chartmuseum](github.com/helm/chartmuseum) in my case) , all works fine . However, when I pull the chart without `--version` (just run `helm pull reg/repo` ), it always pull the old version of my chart , and is not the latest version which I expect for.

Then , I jump into the both helm and chartmuseum's  codebase , And found something maybe incompatible : 

* In chartmuseum, the first chart is not the latest one , but the oldest one (as well as the local cache after run `helm repo update`), as I commented in [chartmuseum issue#311](https://github.com/helm/chartmuseum/issues/311#issuecomment-630982348).

* In helm , `helm pull` will pull the first chart in `HELM_REPOSITORY_CACHE` , but I found a TODO in the [related code](https://github.com/helm/helm/blob/master/pkg/downloader/chart_downloader.go#L242).

Therefore, I think the solution for both side is ok , chartmuseum can sort the charts via `created` field  and  helm do not have any changes or helm can fix the TODO , and uses the really latest version of the chart .

Sorry for opening an issue here if it is not helm-related bug 🙏

**Comment by scbizu** [comment]
I just realized the chart is already ordered by semantic version , but what about the non-semantic version chart (since the chartmuseum support non-semantic or bad semantic version) ?

**Comment by mattfarina** [comment]
@scbizu Helm chart versions are expected to be semantic versions. It might be worth a feature request over there to do some form of validation. `helm lint` should catch the non-semantic versions.

You can see the code Helm uses to find the matching version [here](https://github.com/helm/helm/blob/97774ee13cf9289918555a46948532f8ae313c9d/pkg/repo/index.go#L152-L192). If Helm runs into an issue parsing a particular version it skips it.

Does that help?

There are ways you can modify your scheme to fit within semver. If you share it we might be able to help.

**Comment by scbizu** [comment]
@mattfarina Hi, thanks for you reply . I missed the `Get` function when I post the issue , and I see it when I secondly read the code, thanks . But here is the other question,  if we have a list of charts , for example:

* 0.0.1-beta+hash_tag
* 0.0.1-beta+other_hash_tag
* And so on

They are valid semantic version , and if we only do the semantic version  comparison , we can not distinguish from these charts which one is  the latest version ?

And I self-implement it by adding the `createTime` comparison when the semantic version is the same .
