### ISSUE TITLE
Add info subcommand to helm plugin command

### ISSUE THREAD

**Issue by developer-guy** [helm/helm#8383]
Its was a nice feature if we have info subcommand to display details for example downloaded URL, installed path etc. of the installed plugin like the following:
```
$ helm plugin list
NAME            VERSION         DESCRIPTION
2to3            0.2.1           migrate and cleanup Helm v2 configuration and releases in-place to Helm v3
$ helm plugin info 2to3
NAME            URL                                       PATH
2to3            https://github.com/helm/helm-2to3.git     $HOME/Library/helm/plugins/helm-2to3  
```

**Comment by developer-guy** [comment]
If you like this idea, I am willing to do it. @hickeyma

**Comment by hickeyma** [comment]
@developer-guy What is the use case for a feature like this?

**Comment by developer-guy** [comment]
when I issued helm plugin list command it gives me only the name of the plugin but sometimes I can not remember the URL that I downloaded this plugin and maybe I want to know path simply where those plugins installed.

**Comment by marckhouzam** [comment]
Personally, I like the idea.  It would also help remember if a plugin was installed from a URL or from a local clone.

**Comment by developer-guy** [comment]
Any update about the issue ?

**Comment by marckhouzam** [comment]
@developer-guy As you mentioned, I suggest you post a PR implementing your suggestion, and we can review and discuss the details in there.

**Comment by developer-guy** [comment]
Ok @marckhouzam thank you 🙏 I will try to implement it soon .
