### ISSUE TITLE
helm rollback/upgrade is not working for statefulset pod with multiple containers

### ISSUE THREAD

**Issue by akshaysharama** [helm/helm#8386]
We are trying to do a helm upgrade of a statefulset pod with two containers running in it.

Test scenarios:
positive test case
   1) if trying to upgrade pod with working image, helm upgrade is working fine.
failure test case
  1) If trying to upgrade pod with faulty image/wrong image tag, helm upgrade happened and pod went into crashloopback 
      off. after if again doing helm upgrade with the working image. helm upgrade is not happening and pod is still into 
      crashloopback off.

How to reproduce:
1) Bring up pod with two containers.
2) helm upgrade running pod with some faulty image(basically try to fail upgrade)
3) And do helm upgrade or helm rollback or kubectl rollout.

Output of `helm version`:
v2.16.1

Output of `kubectl version`:
{Major:"1", Minor:"16", GitVersion:"v1.16.3"}

Os
ubuntu 16.04.5 server version

**Comment by akshaysharama** [comment]
question/support

**Comment by bacongobbler** [comment]
Can you provide an example manifest to reproduce the issue?

**Comment by akshaysharama** [comment]
@bacongobbler 

below is the helm templates/charts we are using.

# Source: logstash/templates/pv.yaml
kind: PersistentVolume
apiVersion: v1
metadata:
  name: logstash-pv
  labels:
    type: local
spec:
  storageClassName: logstashdata
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce

  local:
    path: "/mnt/data/logstash/data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 'ubuntu'
---
# Source: logstash/templates/pv2.yaml
kind: PersistentVolume
apiVersion: v1
metadata:
  name: logstash-pv2
  labels:
    type: local
spec:
  storageClassName: logstashconfig
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce

  local:
    path: "/mnt/data/logstash/config"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 'ubuntu'
---
# Source: logstash/templates/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: logstash-pv-claim
spec:
  storageClassName: logstashdata
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# Source: logstash/templates/pvc2.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: logstash-pv-claim2
spec:
  storageClassName: logstashconfig
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# Source: logstash/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: "default"
  labels:
    app: logstash
spec:
  publishNotReadyAddresses: false
  type: "ClusterIP"
  selector:
    app: logstash
  ports:
  - name: logstash
    port: 5044
    targetPort: 5044
    protocol: TCP
---
# Source: logstash/templates/deployment.yaml
#apiVersion: extensions/v1beta1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: "default"
  labels:
    app: logstash
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: logstash
    spec:
      initContainers:
      - name: init-myservice
        image: "docker-registry.com:5000/busybox:latest"
        imagePullPolicy: "IfNotPresent"
        volumeMounts:
        - name: pipeline
          mountPath: /usr/share/logstash/pipeline/logstash.conf
          subPath: logstash.conf
        - name: configmnt
          mountPath: /usr/share/logstash/config/
        - name: tz-config
          mountPath: /etc/localtime
        securityContext:
          runAsUser: 1000
          runAsNonRoot: true
          fsGroup: 1000
        command: ['sh', '-c', 'cp /usr/share/logstash/pipeline/logstash.conf /usr/share/logstash/config/']

      containers:
      - image: "docker-registry.com:5000/logstash:6.6.1"
        name: logstash
        imagePullPolicy: "IfNotPresent"
        ports:
        - name: logstash
          containerPort: 5044
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /usr/share/logstash/config/logstash.yml
          subPath: logstash.yml
          readOnly: false
        - name: configmnt
          mountPath: /usr/share/logstash/config/
        - name: lg-pv-store
          mountPath: "/usr/share/logstash/data"
        - name: tz-config
          mountPath: /etc/localtime
        livenessProbe:
          exec:
            command:
            - bash
            - live_check.sh
          initialDelaySeconds: 11
          periodSeconds: 5
          failureThreshold: 1
        securityContext:
          runAsUser: 0
          fsGroup: 0
        args:
        - -f
        - /usr/share/logstash/config/logstash.conf

      - image: "docker-registry.com:5000/logmgr:tag"
        name: logstash-manager
        imagePullPolicy: "IfNotPresent"
        livenessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 30
          failureThreshold: 3
          successThreshold: 1
        volumeMounts:
        - name: configmnt
          mountPath: /usr/share/logstash/config/
        - name: tz-config
          mountPath: /etc/localtime
        securityContext:
          runAsUser: 0
          fsGroup: 0
        env:
        - name: REMOTE_SYSLOG_ADDR
          value: "xx.xx.xx.xx"
        - name: KAFKA_SERVICE
          value: "kafka-service-name"
        - name: LOGGER_TOPIC
          value: "topic"
        - name: DB_HOST
          value: "etcd-service-name"
        - name: DB_PORT
          value: "2379"
        - name: LOGSTASH_CONF_PATH
          value: "/usr/share/logstash/config/logstash.conf"
      volumes:
      - name: tz-config
        hostPath:
            path: /usr/share/zoneinfo/UTC
      - name: pipeline
        configMap:
          name: logstash
          items:
          - key: logstash.conf
            path: logstash.conf
      - name: config
        configMap:
          name: logstash
          items:
          - key: logstash.yml
            path: logstash.yml
      - name: lg-pv-store
        persistentVolumeClaim:
         claimName: logstash-pv-claim
      - name: configmnt
        persistentVolumeClaim:
         claimName: logstash-pv-claim2

**Comment by tariq1890** [comment]
Can we re-open this issue? I can confirm that this indeed happens in our clusters; esp when the StatefulSet pods run with Istio-injected sidecars.

**Comment by stefanomart** [comment]
It would be useful to open again this issue. Rollback works correctly for all Deployment pods; however, this doesn't work for StatefulSet pods in our cluster.

**Comment by piratf** [comment]
Exactly the same problem. 

```
helm version:
version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.5"}
```

**Comment by joejulian** [comment]
Crashing pods after an upgrade is not something that helm can predict or solve. This seems like it's either a chart problem or it's something to do with how the sidecars are injected, based on the very limited descriptions. There's not enough information to consider reopening this issue.
