### ISSUE TITLE
Cannot reach global context from deeply included template.

### ISSUE THREAD

**Issue by Antiarchitect** [helm/helm#8389]
Output of `helm version`:
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}

Linter is enough.

Here is the repo with minimal helm app to reproduce: https://github.com/Antiarchitect/helm-include-bug

deployment.yaml:
```
{{ include "myapp.deployment" (dict "name" "cloud") }}
```
_deployment.tpl:
```
{{- define "myapp.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp.fullname" $ }}-{{ .name }}
  labels:
    {{- include "myapp.labels" $ | nindent 4 }}
spec:
{{- if not $.Values.autoscaling.enabled }}
  replicas: {{ $.Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "myapp.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
    {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "myapp.selectorLabels" $ | nindent 8 }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "myapp.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $.Chart.Name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
```
Linter error:
```
[ERROR] templates/: template: myapp/templates/deployment.yaml:1:3: executing "myapp/templates/deployment.yaml" at <include "myapp.deployment" (dict "name" "cloud")>: error calling include: template: myapp/templates/_deployment.tpl:5:11: executing "myapp.deployment" at <include "myapp.fullname" $>: error calling include: template: myapp/templates/_helpers.tpl:15:14: executing "myapp.fullname" at <.Values.fullnameOverride>: nil pointer evaluating interface {}.fullnameOverride
```

**Comment by bacongobbler** [comment]
```
{{ include "myapp.deployment" (dict "name" "cloud") }}
```

In your first invocation call, you passed a dictionary to the function. `include` uses the second argument as the root context for the function's invocation, which is why `.Values` cannot be accessed.

If you want to have access to other values, you need to pass in either `$` or `.`.

**Comment by Antiarchitect** [comment]
But `$` should be always a root context just for such cases - there are plenty examples with range cycle, what is wrong with my case.
I want to move out boilerplate code into myapp.deployment and it uses external templates inside. Why _deployment.tpl sees global context through `$` but _helpers.tpl inside of it don't?

**Comment by bacongobbler** [comment]
> what is wrong with my case.

When you call a function, the root scope is modified. This is different from a call to `range` or `with` because they change the *local* scope, not the global scope.

Consider the following python code:

```
def myfunc():
    i = 1
    for i in range(5, 8):
        print(i)
    myotherfunc(i)

def myotherfunc(i):
    print(i)

myfunc()
```

If you ran that, you'd get the following output:

```
5
6
7
7
```

Notice that the local scope of `i` was modified in the `for` loop, and the global scope of `myotherfunc` was given the value of `i`. This is identical to your case: you passed a dictionary with one value (`name: "cloud"`) to a function call, and nothing else. The global scope changed to the root of that dictionary.

Hope this helps.

**Comment by Antiarchitect** [comment]
Okay, I see the mechanics, is there any solution to my case, if I want to use a specific set of variables on each `_deployment.tpl` include? Maybe it is possible to pass variables in some other way to include or merge them in `.` context? When I tried to pass `.` as a context to include - I cannot see the variables declared before the include in deployment.yaml

**Comment by bacongobbler** [comment]
You could try `{{ include "myapp.deployment" (dict "name" "cloud" "Values" .Values "Chart" .Chart) }}`.

**Comment by Antiarchitect** [comment]
Worked like a charm, added .Release and .Template.
@bacongobbler Thank you so much for your patience!
