### ISSUE TITLE
checking variable type and break in helm range/loop

### ISSUE THREAD

**Issue by sunchill06** [helm/helm#8391]
Output of `helm version`:
Client: &version.Version{SemVer:"v2.14.2", GitCommit:"524294565799aba901a242fb7a12cef454c9cb10", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.2", GitCommit:"524294565799aba901a242fb7a12cef454c9cb10", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-20T11:45:27Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-20T11:40:58Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

**Issue:**
Is there any way in helm to check if a variable is integer or string? e.g. type(var) or isStr(), isInt() etc.

Also, is there any option to break the range/loop ?

**Comment by bacongobbler** [comment]
https://helm.sh/docs/chart_template_guide/function_list/#reflection-functions

I do not believe there is a way to break a for loop in text/template. You can look for ideas here: https://golang.org/pkg/text/template/
