### ISSUE TITLE
 Bearer token auth when pull chart from private repo

### ISSUE THREAD

**Issue by lemonli** [helm/helm#8392]
Private repos  use `Bearer Token` rather than `Basic Auth` (eg. chartmuseum support auth with bearer token).
Like this:
```
helm repo add sample-repo --token <token>
helm install/upgrade xxx --token <token>
helm pull xxx --token <token>
```
I can give it a try if it make sense

**Comment by hobbytp** [comment]
@lemonli thanks for this commit, it is very useful. 
BTW, have you considered to support **helm push xxx --token <token>**  :)

**Comment by lemonli** [comment]
> @lemonli thanks for this commit, it is very useful.
> BTW, have you considered to support **helm push xxx --token **, and we still need to use "helm push" plugin to do bearer auth?

`helm push` is a plugin and the code is `out-of-tree`. I think https://github.com/chartmuseum/helm-push#token maybe useful for you.
