### ISSUE TITLE
resources with pre-install hook never install on upgrade

### ISSUE THREAD

**Issue by woodcockjosh** [helm/helm#8401]
Output of `helm version`:
`version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}`

Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-27T00:38:11Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.11", GitCommit:"436254b798f772bcb8e67dcfe122e46500eeb254", GitTreeState:"clean", BuildDate:"2020-06-17T11:41:28Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Metal

I have tried to install the bitnami/metallb chart. In it there is a pre-install hook on the secret for the memberlist. That secret is never installed even though it is rendered correctly with the `--debug` flag. I can install the output from the `--debug` result. If I remove the `pre-install` hook then the secret is created correctly so I can only assume this is some issue with the helm cli itself. 

```text
client.go:222: [debug] Deleting "infrastructure-metallb-memberlist" in infrastructure...
client.go:225: [debug] Unable to get obj "infrastructure-metallb-memberlist", err: secrets "infrastructure-metallb-memberlist" not found
client.go:239: [debug] Attempted to delete "infrastructure-metallb-memberlist", but the resource was missing
```

I am using metallb as a dependency for the infrastructure chart and installing with `helm upgrade`

**Comment by bacongobbler** [comment]
Let us know if you find anything. This is the first case I've heard about pre-install hooks not working, which leads me to believe it might be isolated to the chart in question.

If there were other reports we would've heard about it shortly after 3.2.4 was released - pre-install hooks are quite common.

**Comment by woodcockjosh** [comment]
What reason could there be for a pre-install hook not to run? Like I said its rendering correctly with `--debug` option

**Comment by woodcockjosh** [comment]
Here's the cases where pre-install hook works fine:

1. Install chart as standalone release
2. Chart with pre-install hook is a dependency for a release that was never installed

Here's the cases where pre-install hook is failing:
1. Chart with pre-install hook is added as a dependency to another chart that has already been installed. 

So the `pre-install` hook only fails when running `helm upgrade`

**Comment by bacongobbler** [comment]
pre-install hooks are intended to be run prior to `helm install` installing the requested resources. If you need the hook to run prior to an upgrade as well, add the `pre-upgrade` annotation:

```
annotations:
  "helm.sh/hook": pre-install,pre-upgrade
```

There are several examples of this [in the charts repository](https://github.com/helm/charts/blob/cbd5e811a44c7bac6226b019f1d1810ef5ee45fa/stable/sumokube/templates/secrets.yaml#L11), and [in the documentation](https://helm.sh/docs/topics/charts_hooks/#writing-a-hook).

Working as intended.

**Comment by woodcockjosh** [comment]
@bacongobbler but why does the resource just not install at all??? That is the point

**Comment by woodcockjosh** [comment]
https://github.com/helm/charts/issues/5167
