### ISSUE TITLE
Cannot specify OCI registry for dependency

### ISSUE THREAD

**Issue by atrauzzi** [helm/helm#8402]
Running on helm `3.2.4` with `export HELM_EXPERIMENTAL_OCI=1` set, calling `helm dependency update` doesn't appear to be aware of the OCI repositories I've configured:

```
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "MYREPO" chart repository (https://MYREPO.azurecr.io/helm/v1/repo):
	failed to fetch https://MYREPO.azurecr.io/helm/v1/repo/index.yaml : 401 Unauthorized
Update Complete. ⎈Happy Helming!⎈
Error: dependency "MYORG/MYPROJECT" has an invalid version/constraint format: improper constraint: 
```

Although [the current documentation mentions that the functionality is available](https://helm.sh/docs/chart_best_practices/dependencies/):

![image](https://user-images.githubusercontent.com/115199/86602250-00413980-bf68-11ea-8134-492e7af699aa.png)

**Comment by jdolitsky** [comment]
@atrauzzi - apologies that you've been misled. This functionality is not yet in Helm. I will take care of removing from documentation so that this is more clear. More info here https://github.com/helm/helm-www/pull/623#issuecomment-628589643

**Comment by atrauzzi** [comment]
Not a problem :smile: 

I'm just stoked to be getting it, hopefully soon!

**Comment by jdolitsky** [comment]
PR to revert the docs: https://github.com/helm/helm-www/pull/746
