### ISSUE TITLE
How can i assign .Values.xxx a default value if it's not defined in Values.yaml

### ISSUE THREAD

**Issue by zhb127** [helm/helm#8406]
How can i assign .Values.xxx a default value if it's not defined in Values.yaml, like:

```
{{ if not $.Values.xxx }}
{{ $.Values.xxx := "test value" }}
{{ end}}
```

Output of `helm version`: v3.2.4

Output of `kubectl version`: v1.18.3

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  Minikube

**Comment by bacongobbler** [comment]
`{{ default “test value” .Values.xxx }}`

More information available in the documentation. https://helm.sh/docs/chart_template_guide/function_list/

**Comment by softKarma** [comment]
I want to use an empty string as the default value when _.Values.xxx_ is not present so I added the following code:

`{{ default “” .Values.xxx }} `

However, this doesn't work. Is this the intended behavior or am I doing something wrong here?
