### ISSUE TITLE
Failed to list: couldn't get version/kind; json parse error

### ISSUE THREAD

**Issue by tingeltangelthomas** [helm/helm#8409]
Hi,

since some days we get some json parse errors during execution of "helm ls" command.
We are using openshift and it occures randomly and not every time.

Has somebody an idea what can cause this issue?
Is this the full error message or is there a chance to get more information what's happening here?

Versions:
```
helm helm-v3.2.1-linux-amd64
oc v3.11.0+62803d0-1
kubernetes v1.11.0+d4cacc0
openshift v3.11.219
kubernetes v1.11.0+d4cacc0
```

Error:
```
helm3 ls --namespace ${RUNTIME_PROJECT_NAME} --debug

Error: list: failed to list: couldn't get version/kind; json parse error: invalid character 'T' after top-level value
helm.go:84: [debug] couldn't get version/kind; json parse error: invalid character 'T' after top-level value
list: failed to list
helm.sh/helm/v3/pkg/storage/driver.(*Secrets).List
	/home/circleci/helm.sh/helm/pkg/storage/driver/secrets.go:87
helm.sh/helm/v3/pkg/action.(*List).Run
	/home/circleci/helm.sh/helm/pkg/action/list.go:154
main.newListCmd.func1
	/home/circleci/helm.sh/helm/cmd/helm/list.go:80
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:83
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357
```

Regards and many thanks for your help!
Thomas

**Comment by bacongobbler** [comment]
Looking at the stack trace it looks as though it occurs while reading helm’s release secrets in the given namespace. It looks as though there are invalid characters in the resource manifest.

Let us know what you find out.

**Comment by tingeltangelthomas** [comment]
Thanks for your response.
It was like a temporary issue and it's working again. 
Seems like a timeout while calling the kubernetes api.
But this is only a guess, because the original response of the api is hidden. Even if I execute helm with --debug.
Would it be possible to add the original output in such cases?

**Comment by tingeltangelthomas** [comment]
Hi @bacongobbler 
some news from my side...

I got the real error by executing:
`helm3 ls --namespace ${RUNTIME_PROJECT_NAME} --v 10`
This will cause an output of ~70MB.

```
I0714 12:44:44.637659    1285 round_trippers.go:443] GET https://xxx:8443/api/v1/namespaces/xxx/secrets?labelSelector=owner%3Dhelm 200 OK in 507 milliseconds
I0714 12:44:44.637701    1285 round_trippers.go:449] Response Headers:
I0714 12:44:44.637715    1285 round_trippers.go:452]     Audit-Id: 6338dde9-8065-4476-b891-2eccc09eb294
I0714 12:44:44.637727    1285 round_trippers.go:452]     Cache-Control: no-store
I0714 12:44:44.637739    1285 round_trippers.go:452]     Content-Type: application/json
I0714 12:44:44.637751    1285 round_trippers.go:452]     Date: Tue, 14 Jul 2020 12:44:44 GMT

This request caused apiserver to panic. Look in the logs for details.
Error: list: failed to list: couldn't get version/kind; json parse error: invalid character 'T' after top-level value`
```

Amount of secrets (helm history stores 10 releases)
```
$ oc get secret -l owner=helm --no-headers | wc -l 
1846 
```

- Would it be possible to add this message to the normal helm output in such cases?
- Is there a way to force helm not to get all secrets?
- We try to find out which problem our api server has sometimes
