### ISSUE TITLE
Inconsistent state after uninstallation if a custom resource definition is not available anymore

### ISSUE THREAD

**Issue by pepov** [helm/helm#8413]
Given a chart that installs or works with custom resources can leave an inconsistent state after deletion.

Example chart: stable/prometheus 11.6.1

To reproduce:
```
helm install prometheus-operator stable/prometheus-operator
kubectl delete crd prometheuses.monitoring.coreos.com
helm delete prometheus-operator
```

Then the output of the final command is:
```
Error: uninstallation completed with 1 error(s): unable to build kubernetes objects for delete: unable to recognize "": no matches for kind "Prometheus" in version "monitoring.coreos.com/v1"
```

The problem is that none of the actual resources in the release have been removed, although the release itself is gone.

Running the last command once again:
```
helm delete prometheus-operator
Error: uninstall: Release not loaded: prometheus-operator: release: not found
```

Although resources are still available:
```
kubectl get po
NAME                                                      READY   STATUS    RESTARTS   AGE
alertmanager-prometheus-operator-alertmanager-0           2/2     Running   0          105s
prometheus-operator-grafana-77d5b9b8b8-sxwf6              2/2     Running   0          118s
prometheus-operator-kube-state-metrics-69fcc8d48c-5mjkb   1/1     Running   0          118s
prometheus-operator-operator-6ff4d9f5c-5fjgw              2/2     Running   0          118s
prometheus-operator-prometheus-node-exporter-mbg88        1/1     Running   0          118s
```

I am opinionated about this and would suggest that Helm should not fail, but remove resources that does not have a matching kind available, since it could then conclude the resource is already gone. The following PR is about to fix that:
https://github.com/helm/helm/pull/8151

With helm2 I beleive this worked differently in that resources had been built and removed one-by-one instead in two seperate phases. 

If there is an issue in the [first phase](https://github.com/helm/helm/blob/3c9099290b75ee2dd74f1751dc5b454b7b60af7e/pkg/action/uninstall.go#L199) the [second phase](https://github.com/helm/helm/blob/3c9099290b75ee2dd74f1751dc5b454b7b60af7e/pkg/action/uninstall.go#L204) will never get executed, but the release will still be [removed](https://github.com/helm/helm/blob/3c9099290b75ee2dd74f1751dc5b454b7b60af7e/pkg/action/uninstall.go#L130) regardless of the errors.

I'm not sure how you would want to address this, but I guess it's nontrivial if you consider existing clients may already build/depend on this behaviour. However I would consider [omitting "no matches for kind"](https://github.com/helm/helm/pull/8151) errors much lower risk.

Output of `helm version`:
```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T14:51:23Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
kind v0.8.1 go1.14.2 darwin/amd64
```

**Comment by mattfarina** [comment]
I'm moving this to 3.4.1. It's a bug so we can work on it for a patch release.

**Comment by bacongobbler** [comment]
removing from 3.4.1 as #8151 is not in a mergeable state at this time.

**Comment by mhio** [comment]
I've run into this on helm 3.7.1.

Deleting an app from k8s 1.22 that was installed on k8s 1.16, `Ingress` has changed API's. helm deletes the release, but all resources are left in place.

**Comment by JohnJAS** [comment]
Same issue on hem v3.7.3.

**Comment by benjaminxie** [comment]
Perhaps a similar issue on helm v3.11.2 . I had an Istio EnvoyFilter in my chart and if I uninstalled Istio (using `istioctl`) and then `helm uninstall` my chart, it would fail with
```
uninstall: Failed to delete release: [unable to build kubernetes objects for delete: resource mapping not found for name: "<resource name>" namespace:
"" from "": no matches for kind "EnvoyFilter" in version "networking.istio.io/v1alpha3"
```
