### ISSUE TITLE
Feature Request: `helm deploy` subcommand

### ISSUE THREAD

**Issue by dcow** [helm/helm#8415]
Reading through https://github.com/helm/helm/issues/3353# there was an interesting suggestion by @whereisaaron https://github.com/helm/helm/issues/3353#issuecomment-362497951 and https://github.com/helm/helm/issues/3353#issuecomment-469109854:

>I am not sure why we need the install and upgrade commands, I only ever use the upgrade --install command and is seems like a lot of people do the same. I just need one command that does upgrade --install and doesn't trip over a failed run. Can we just rename upgrade --install to deploy, make it truly idempotent, and ditch the other two?
>
>With helm currently, you don't know which helm command+options combination to use without inspecting the current state. And for a given helm command you don't know what you are going to get, because it depends on what the current state is. That's not really the declarative desired state dream :cloud: :zzz: :smile:

Via text reply and emoji-analysis the suggestion received solid support. Discussion in the thread indicated it would be an interesting addition to helm 3. 

>In helm 3 we can potentially deprecate install / upgrade / --replace / --upgrade / --force and replace them all with an idempotent helm deploy that either achieves the desired state, or leaves the state unchanged. Maybe using an algorithm similar to above, which if helm deploy fails, rolls back (revision > 1) or deletes+purges (revision = 1), to leave the state as it was before. The failed manifest would still be available via helm history/get. And there could even be a '--no-rollback' option for people who want to preserve the deployment in a failed state for investigation
>
>The option of helm upgrade --install --force is getting close, except that rather than rolling back and upgrading, it deletes and replaces failed releases (even for revisions >1), which makes some people angry over on #3208... open_mouth zap boom
>
>For right now we can use wrapper scripts or meta-tools like helmsman whose feature list is in part to employ helm but mitigate this issue:
>
> * Idempotency: As long your desired state file does not change, you can execute Helmsman several times and get the same result. [...regardless of the current state]
> * Continue from failures: In the case of partial deployment due to a specific chart deployment failure, fix your helm chart and execute Helmsman again without needing to rollback the partial successes first.

After a short while working with helm myself, I agree a `deploy` sub-command that attempts to achieve the desired state declared by the helm chart makes a lot of sense. Philosophically, sure, but also simply by virtue of supporting a super simple operator/developer workflow where you've got a helm chart and you just want to `helm deploy` it into whatever cluster you're pointed at pointed at rather than having to do `helm upgrade --install `. Imagine a dev working on a chart needing to constantly deploy changes as they're made. And, as someone new to helm, I am not even aware of all the nuances of when to use which helm command depending on the state of a deployment. I'm a little worried after reading this that I may have been overlooking something important since I've been more or less operating under the assumption that I can just use helm upgrade --install whenever and helm takes care of the rest (more so how it sounds like people expect a deploy sub-command would work).

I asked and @hickeyma suggested that I open an issue to pick up discussion. Thoughts?

**Comment by bacongobbler** [comment]
What would be the difference of implementing this in core vs someone from the community taking what’s already in helm and writing a plugin? If this is just a command alias for features that already exist in helm as feature flags, why should we re-package what’s already been shipped?

**Comment by hickeyma** [comment]
@dcow I think it could be useful but I tend to agree with @bacongobbler that is is essentially just a wrapper around `helm upgrade --install` in core.  I therefore think that a plugin is the best approach and something you could do easily enough if you want.

**Comment by dcow** [comment]
I guess my main question is, "why are there two commands in the first place?" Is there not an opportunity to merge the two into one and simplify the workflow? Or is it simply that the UI as implemented is rather flexible and it would take a lot of effort to collapse the two commands into one since doing so may ultimately remove access to functionality people depend upon?

**Comment by Jokero** [comment]
I'd agree with @dcow. First time I worked with helm I was confused a little bit about what should I use to deploy a chart especially taking into account that I was just experimenting with k8s and different providers of it and created/updated a cluster multiple times a day. Of course instead of using both `helm install` and `helm upgrade` I switched just to `helm upgrade --install` as it required fewer lines in my shell file and worked for both creation and update of a cluster. From my perspective `helm install` is quite useless and `helm upgrade --install` looks a bit awkward and cumbersome and can be replaced to something more intuitive like `helm deploy`

**Comment by bacongobbler** [comment]
> From my perspective `helm install` is quite useless

There are flags in `helm install` that are not present in `helm upgrade` that does not make it useless for many users. Many users rely on `--create-namespace`, for example.

**Comment by bacongobbler** [comment]
> Or is it simply that the UI as implemented is rather flexible and it would take a lot of effort to collapse the two commands into one since doing so may ultimately remove access to functionality people depend upon?

Bingo. Collapsing the two into one command will ultimately result in the removal of certain functionality, or at the very least an incredibly confusing user story. Consider how flags like `--reset-values`, `--force`, `--atomic` and `--reuse-values` would work in these scenarios. Some of the user base will want them enabled. Some will not.

This is where helm plugins shine best. Users can take advantage of what's already in helm and craft their own opinions and write their own tools based on their opinions.

Hope that helps explain the situation.

**Comment by abdennour** [comment]
Idempotency is critical for ci/cd. 
We understood that release engineering science differentiates between first install & subsequent upgrade(s).
However, this is not an excuse to not provide a such feature.

**Comment by squillace** [comment]
uh, yeah it is. Release science says it's so. But, hey, you're free to knock out a plugin that does this. It'll work fine. If everyone starts using it, that would be the very best argument it should be a core feature.
