### ISSUE TITLE
Subcharts templates not linted if parent chart doesn't have templates directory

### ISSUE THREAD

**Issue by wolf99** [helm/helm#8418]
I have seen a linting issue in sub chart templates that only is only detected by lint when the parent chart has a templates directory.
Looking at the Helm source it seems (I am not familiar with Go) like linting is only performed on templates if the parent directory has a templates directory.

Previous to the this point the parent chart did not need any templates so our issue is only discovered now.

Have I understood the Helm source correctly?
Is this intentional behaviour for the lint of templates? (It was not the _expected_ behaviour)

https://github.com/helm/helm/blob/bf9c64f48ee8f799c89de6cfbd44302f798b3531/pkg/lint/rules/template.go#L56

**Comment by bridgetkromhout** [comment]
Hi, @wolf99 - a number of changes to linting are pending in the upcoming 3.3.0 release; can you let us know if your testing is using the pre-release in https://github.com/helm/helm/releases/tag/v3.3.0-rc.1, or if not, can you let us know what version you're using? Thanks.

**Comment by wolf99** [comment]
Hey @bridgetkromhout 
You're here too! (I follow you on Twitter but hadn't realised the Helm connection 😄 ).

We are using 2.12 in our pipelines but due to step up to >=2.16, and potentially onto 3.x.
Seems like the referenced logic is present in all of those versions (incl. 3.3.0-rc1).

The issue we have experienced is not caused by this logic, but it was hidden by it.
We had sub-chart templates using `mergeOverwrite` which is not valid in 2.12 (only >=2.16), but it was not caught because there were no templates (and hence no templates directory) in the top-level chart which meant that lint didn't run.

**Comment by hickeyma** [comment]
@wolf99 This looks like a bug alright. I also tested it manually off the Helm main branch as follows:

```console
$ helm3 lint issue-8418
==> Linting issue-8418
[INFO] Chart.yaml: icon is recommended
[INFO] values.yaml: file does not exist
[ERROR] templates/: error unpacking subchrt-1 in issue-8418: validation: chart.metadata.version is required

Error: 1 chart(s) linted, 1 chart(s) failed

$ ls issue-8418
Chart.yaml  charts  templates

$ rm -rf issue-8418/templates

$ helm3 lint issue-8418
==> Linting issue-8418
[INFO] Chart.yaml: icon is recommended
[INFO] values.yaml: file does not exist
[WARNING] templates/: directory not found

1 chart(s) linted, 0 chart(s) failed
```

**Comment by wawa0210** [comment]
/assign

I can try to fix this issue

**Comment by wawa0210** [comment]
From the code 

https://github.com/helm/helm/blob/bd09f1fbecea88e16299b60f42f266d9f6923813/pkg/action/lint.go#L113-L117

The verification code here does not check whether the `templates` folder exists

At the same time 

https://github.com/helm/helm/blob/bd09f1fbecea88e16299b60f42f266d9f6923813/pkg/lint/rules/template.go#L49-L58

It is judged here whether this file exists, but no exception is thrown, and the return is directly made.

**Comment by wolf99** [comment]
Hi @wawa0210  thanks for working on this.
My knowledge of Go and Helm is not great, looking at #7970 I couldn't see how it solves this problem. Are you able to explain it a little here?
Much appreciated.

**Comment by wawa0210** [comment]
>looking at #7970 I couldn't see how it solves this problem. Are you able to explain it a little here?



In this pr, a new inspection item is added
https://github.com/helm/helm/blob/d6708667da5c79ab4a093ea7473e96b93be5f1f7/pkg/lint/lint.go#L35

This check item will check whether templates exist

**Comment by wolf99** [comment]
I guess this implies that linting _requires_ the templates directory to be present, is that correct?

**Comment by hickeyma** [comment]
@wolf99 It should work without the `template` directory being present.
