### ISSUE TITLE
helm install --dry-run failed for existing object

### ISSUE THREAD

**Issue by Shobhit29** [helm/helm#8419]
Output of `helm version`:  3.2.1

Output of `kubectl version`: 1.13

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  On-Premise

It seems that when I run helm3 install CHART --dry-run --generate-name failed if the object of the same name exist. Basically I have a chart consist of deployment object and a service object. My service object is a static name called serviceA in a namespace test. When I try to `helm install CHART --dry-run --generate-name` throws an error saying 

```rendered manifests contain a resource that already exists. Unable to continue with install: Service "serviceA" in namespace "test" exists and cannot be imported into the current release```

Is it a bug or there is any way I can bypass it

**Comment by mattfarina** [comment]
@Shobhit29 This is intentional and for safety purposes. Helm prioritizes not breaking what you have running. It will not overwrite a manifest it is not managing as part of a release so something isn't accidentally deleted.
