### ISSUE TITLE
helm del --purge <release_name> is throwing error if the release is already deleted. 

### ISSUE THREAD

**Issue by alokvk1234** [helm/helm#8422]
Hi,

helm del --purge <release_name> is throwing error if the release is already deleted. 
Before i used to use kubectl which has flag --ignore-not-found which would ignore the deployment if already deleted and proceed to next step in cicd. Do we have similar flag in helm which does same function as --ignore-not-found, as i am getting invalid flag when used with helm.

**Comment by hickeyma** [comment]
@alokvk1234 This is expected behaviour. For example:

```console
$ helm del mychart-v2-1 --purge
release "mychart-v2-1" deleted

$ helm del mychart-v2-1 --purge
Error: release: "mychart-v2-1" not found
```

There is no `--ignore-not-found ` flag supported.

**Comment by alokvk1234** [comment]
Hi,

i am running this script in gitlab cicd pipeline.If no release is found then helm delete --purge <release_name> will fail the pipeline. Do we have any other ways to resolve the issue.

**Comment by alokvk1234** [comment]
It should skip it and proceed to installing the fresh release.

**Comment by hickeyma** [comment]
You could check if the release exists before deleting?

**Comment by bacongobbler** [comment]
This is its intended behaviour. We will not be changing this as doing so would break backwards compatibility.
