### ISSUE TITLE
helm install wait if the release to be installed is currently in the process of deletion

### ISSUE THREAD

**Issue by alokvk1234** [helm/helm#8424]
In pipeline first will run helm delete --purge <release_name> and later helm install. But release fails Error: release <release_name> failed: object is being deleted: services <release_name> already exists.
So do we have any solution, so that helm install has to wait until the release is completely deleted and later proceed installing the new fresh release

**Comment by hickeyma** [comment]
@alokvk1234 Are you looking for Helm to wait for all Kubernetes resources to be deleted before returning from a `helm delete` command?

**Comment by alokvk1234** [comment]
correct..helm should wait untill helm deletes the release completely and next proceed to next step which is install.

**Comment by asitaru** [comment]
We would also need this for pipelines. A way to do what is asked in https://github.com/helm/helm/issues/8601 could solve this problem.

**Comment by bacongobbler** [comment]
this is a duplicate request of #2378, so I am closing in favour of that ticket.
