### ISSUE TITLE
Feature Request - Moniker Template Function

### ISSUE THREAD

**Issue by rarick** [helm/helm#8428]
# Reason for Request
I think this would be a nice template function to have available, and I don't think it should be too much work. My current use case:

I have a chart which brings up a simple temporary website for internal usage by a user at my company. I'll be generating a username/password which is given to the user upon installation of the chart, which they can then distribute at their discretion.

This way, the user is able to restrict access to the site they deploy.

It would be nice if this auto-generated username (or password) was a moniker, using the same algorithm that is used when using the `helm install --generate-name ...`. (Security isn't very important in this scenario, more to just give internal users a slight access control against other internal users)

In this use-case it's pretty pointless, but I'm sure other people out there have better use cases for a moniker. Maybe for a default ingress hostname?

# Potential Usage/Features
It would be nice if a moniker length could be chosen, but looking at the library (github.com/technosophos/moniker) it looks like that's not directly supported.

`{{ moniker 2 }}` for example, could produce output such as `eating-iguana-old-whale`. 

It would also be useful to be able to set the string separator. In the case above, the separator string would be `-`, which could be a candidate for the default separator. However, `{{ moniker 2 " " }}` could produce `eating iguana old whale` if this is deemed useful.

Side note: would `moniker` returning a list be helpful? I don't think this would be as useful, but would like to hear more opinions.

**Comment by bacongobbler** [comment]
For feature requests on new template functions, please open a ticket over at https://github.com/Masterminds/sprig. That is the project that provides any helper-related function calls. We've typically introduced functions that are Helm-specific, such as `tpl`.

Thanks!

**Comment by rarick** [comment]
Will do, thanks!
