### ISSUE TITLE
helm metrics in the non-tiller world?

### ISSUE THREAD

**Issue by withnale** [helm/helm#8430]
We'd like to be able to monitor certain aspects of our helm releases. 

I've no direct experience of it but I have found https://github.com/Kubedex/exporter as a solution for this (although the level of metrics from it seem to be fairly limited). However, this is a helm2 solution which relies on tiller being present.

Is there any method or third party application that can provide a metrics source for prometheus in the helm3 world?

**Comment by bacongobbler** [comment]
Sorry for the lateness on a response.

We are unaware of any tools to help provide metrics to prometheus at this time. However, I'm sure there could be a way to read release secret metadata from the cluster and provide that data out to a dashboard. https://helm.sh/docs/topics/advanced/#storage-backends has more details on the available storage backends for Helm 3.
