### ISSUE TITLE
helm list shows only those installed in that specific helm version.

### ISSUE THREAD

**Issue by BhavishyaR** [helm/helm#8433]
1)  I installed helm 2.11.0  in machine "M1" and deployed an application called "A" to my namespace say "xyz" 
o/p of helm version :
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"

2) later I installed helm 3.2.1 in another machine"M2" pointing to the same cluster that I used in 2.11. And deployed another application "B" to "xyz" namespace.
o/p of helm version :
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}

3) Now when I login to Machine1 and use $helm ls ,  I'm able to see only application "A" and not "B" in the list
4) Now when I login to Machine2 and use $helm ls ,  I'm able to see only application "B" and not "A".

Is this an expected behavior to see the helm installation only in that particular version? Why can't I see the list of both the applications?
Note : I have NOT upgraded the helm .

**Comment by bacongobbler** [comment]
This is expected behaviour. Helm 2 cannot read helm 3 release data and vice versa. This is because the storage drivers are incompatible with each other.

See https://helm.sh/docs/faq/ and https://helm.sh/docs/topics/v2_v3_migration/ for more info.
