### ISSUE TITLE
helm upgrade returns errors

### ISSUE THREAD

**Issue by hillbun** [helm/helm#8435]
helm install abc-dev /abc -f /abc/values-dev.yaml

runs successfully

But 
helm upgrade abc-dev /abc -f /abc/values-dev.yaml

returns errors:
Error: UPGRADE FAILED: failed to create patch: map: map[] does not contain declared merge key: name && failed to create patch: map: map[] does not contain declared merge key: name

Output of `helm version`:

v3.2.4

Output of `kubectl version`:

v1.18.5

**Comment by liuming-dev** [comment]
Could you please provide an example to reproduce this case?

**Comment by hillbun** [comment]
maybe something error in templates yalm files.

but can not get  more details from error output.

**Comment by bacongobbler** [comment]
Please provide an example we can use to reproduce the issue. Thank you.

**Comment by hillbun** [comment]
Maybe I lost codes that cause  this error.

I will try to reproduce.
