### ISSUE TITLE
Deployment container image updated incorrectly when running `helm upgrade`

### ISSUE THREAD

**Issue by dcow** [helm/helm#8442]
I may be experiencing https://github.com/helm/helm/issues/5915 but I'm not 100% sure so I'm opening a new issue until we figure out whether that's the case or not.

My workflow is:

1. `helm install myapp .`, chart version `1.0.0`, appVersion `1`, image: `us.gcr.io/steplabs/myapp:1`
    * deployment template image is untouched from initial helm create command `{{ .Values.image.repository }}:{{ .Chart.AppVersion }}`
2. work on application, build a new image, push with tag `us.gcr.io/steplabs/myapp:feedbeef  <-(commit hash)`, repodigest `myapp@sha256:<sha>`
3. patch deployment using the repodigest to ensure the pod is rolled
    ```
    kubectl patch deployment.apps/myapp \
        -p '{"spec":{"template":{"spec":{"containers":[{"name":"myapp","image":"us.gcr.io/steplabs/myapp@sha256:[sha]"}]}}}}'
    ```
3. test out new image. if tests fail, goto 2, else changes work, goto 5
4. update helm chart version to 2.0.0 (because for example I add a configmap), update app version to 2 (to support new config map), publish new image `us.gcr.io/steplabs/myapp:2`
5. `helm upgrade myapp .`
6. `kubectl get deployment.apps/myapp -o yaml` -> `image: us.gcr.io/steplabs/myapp@sha256:[sha]:2` <-wat?

What I'm seeing is that the image *repository* remains as what the live version is (myapp@sha256). However, the image *version* from helm is tacked on to the `repo@sha:[sha]` portion (the full repo:version). So now the image is effectively `repo:version:helm-version`. Whether this type of merge is intentional or not, the image spec/name generated by helm is incorrect and results in kuberenetes reporting such: 
```
myapp-6b8fcd55df-jhfgs        1/2     InvalidImageName   0          62m
```
As a chart author/dev, I would expect the result of helm upgrade to be: `us.gcr.io/steplabs/myapp:2` since the image version has changed in my latest chart, irrespective of the patched image as deployed in the cluster. I'm using image refs when iterating in development because it's the only way to ensure that (a) I get a fresh image and (b) the container uses the image I just published (that someone didn't overwrite my tag). It's probably also worth noting that `helm template` correctly renders the deployment while `helm upgrade --dry-run myapp .` shows the incorrect version.

If there is some workflow that requires helm allow the image name to be patched live but delegates to the helm chart for the image version, I at least need to be able to work around this issue by explicitly telling helm how to proceed during a 3-way merge on the `image` key (I want it to take the new chart version unconditionally). However, I suspect this is is more of a bug or at least uncertainty in how to parse image names of the form `<repo>@sha:<version>` rather than the expected `<repo>:<version>` when performing a merge.

---
Output of `helm version`:
```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.9-gke.6", GitCommit:"14bc8ad5f8c245f1240a8e4eab128c4d51bfeffe", GitTreeState:"clean", BuildDate:"2020-05-30T02:07:03Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE

**Comment by bacongobbler** [comment]
Hi @dcow. If you would like help from the community, we kindly ask ticket authors to please submit a test case that can be used to reproduce the issue. For example, a zipped or pre-packaged helm chart. It helps us expedite the triage process and provides us a testbed we can use to ensure we're all testing against the same steps. Writing out a test case manually takes a significant amount of time, and multiply that by the number of open issues in the queue...

Appreciate your help filing the ticket. Let us know if you figure out anything in the meantime.

**Comment by dcow** [comment]
@bacongobbler my first question is whether this behavior expected/known or not. I am unsure whether this is a bug to begin with or if e.g. `helm` simply doesn't support upgrades against deployments patched with a repo digest instead of traditional image name. Or perhaps there's a flag or annotation I don't know about to help hint helm on the correct behavior when merging in the image to patch the deployment. It sounds like this is probably a bug, though?

In that case, I'm absolutely happy to work on packaging up some scripts to help repo it and dig in further. I just wanted to confirm first.

For posterity, my chart is rather simple--essentially just a `helm create foo`. Repo steps simplified from above are:

1. publish a `foo:1` docker image
2. `helm install foo .`
3. publish a `foo:f00df001` docker image, upload to a repo and observe the repo digest (sha of the published image+tag)
4. patch the helm deployment using `kubectl patch -p {... "image": "$repodigest" }`
5. make a change to the chart and code, bump the version numbers in `Chart.yaml`
6. publish a `foo:2` docker image
7. upgrade to the updated chart via `helm upgrade foo .`
