### ISSUE TITLE
Add support for ordering of resources within a chart for Custom Resources

### ISSUE THREAD

**Issue by ashokponkumar** [helm/helm#8446]
Similar to how we have an ordering requirement for known resources in the [InstallOrder](https://github.com/helm/helm/blob/release-3.0/pkg/releaseutil/kind_sorter.go), users want the capability to order custom resources too. For example a custom resource like SCC need to be applied before creation of any pods as discussed in #8439 

To enable this capability we can follow the same approach we use for hooks. Essentially add a annotation "helm.sh/order-weight" which can take an integer value (+ve or -ve). This will behave the same way as "helm.sh/hook-weight", but for resources not covered by hooks. 

Here is how it will work: 
1. The first resources to be installed will be all resources that have negative weights, and then those with zero or no weights, and then those with positive weights. All in ascending order.
1. For resources which have same weight, Install order is preserved for known resources.

**Comment by hickeyma** [comment]
@ashokponkumar Is this separate to #8439 or is it part of the issue?

**Comment by ashokponkumar** [comment]
> @ashokponkumar Is this separate to #8439 or is it part of the issue?

The main discussion on #8439 was around only SCC's. This is an attempt to generalise it and target all CRs as per the discussions in #8439.

**Comment by hickeyma** [comment]
I would suggest then maybe merging the 2 into the 1 issue so to keep the conversation in one place. So maybe, update #8439 to be CRD based and in the description you have a specific use case around scc. What do you think?

**Comment by ashokponkumar** [comment]
@hickeyma, Closed #8439, and the usecase is captured in the description of this issue.

**Comment by ashokponkumar** [comment]
@hickeyma Won't this issue quality as a feature or a proposal instead of a quesion/support?

**Comment by hickeyma** [comment]
I have updated #8439 as this issue contains some good feedback in the comments. I have updated it as a proposal also. I am therefore going to close this issue in favour of #8439.
