### ISSUE TITLE
helm upgrade --instrall => Error: unknown flag: --create-namespace

### ISSUE THREAD

**Issue by iWangJiaxiang** [helm/helm#8454]
The command

```
helm upgrade --namespace=xxxx --install  --create-namespace --wait --timeout 15m -f answer.yaml xxxx .
```

caused the error

```
Error: unknown flag: --create-namespace
```

---

My DevOps CI ran helm commands within container [dtzar/helm-kubectl:3.1.2 ](https://hub.docker.com/r/dtzar/helm-kubectl). The env is below

Output of `helm version`:

helm v3.1.2

Output of `kubectl version`:

kubectl v1.17.3

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by hickeyma** [comment]
@iWangJiaxiang The `--create-namespace` flag is only available for the `helm install` command.

**Comment by iWangJiaxiang** [comment]
@hickeyma Thank you for quick reply.

According to [Helm | Helm Upgrade](https://helm.sh/docs/helm/helm_upgrade/)

>       --create-namespace             if --install is set, create the release namespace if not present

![image](https://user-images.githubusercontent.com/19409802/87521122-81aa7180-c6b6-11ea-9309-ac958527d977.png)

**Comment by iWangJiaxiang** [comment]
From: https://stackoverflow.com/a/60817927/8144350

>This feature is implemented in helm >= 3.2 (Pull Request)
>Use --create-namespace in addition to --namespace <namespace>

**Comment by hickeyma** [comment]
Sorry, my bad @iWangJiaxiang. I got slightly confused with something else.

I just tested off the current main branch and it works as follows:

```console
$  helm upgrade --install --namespace=foo-ns --create-namespace mychart mychart/
Release "mychart" does not exist. Installing it now.
NAME: mychart
LAST DEPLOYED: Wed Jul 15 08:58:06 2020
NAMESPACE: foo-ns
STATUS: deployed
REVISION: 1
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace foo-ns -l "app.kubernetes.io/name=mychart,app.kubernetes.io/instance=mychart" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace foo-ns port-forward $POD_NAME 8080:80
```

Just checked and it was introduced in [3.2.0](https://github.com/helm/helm/releases/tag/v3.2.0) as you mentiuoned. In the description, you specified you are using 3.1.2. Is that correct?

**Comment by donggangcj** [comment]
Maybe you should consider an version upgrade.

**Comment by iWangJiaxiang** [comment]
Thank you all.
