### ISSUE TITLE
How to automate Helm  3x package --sign passphrase prompt using CI or command line

### ISSUE THREAD

**Issue by binititpro** [helm/helm#8455]
I am trying to package sign with pgp steps with link below. helm 2x have provision to set export HELM_KEY_PASSPHRASE=$password. which is working but helm 3x not have option. please help to automate paspharase option in helm 3x.
https://docs.github.com/en/github/authenticating-to-github/generating-a-new-gpg-key
 
helm package --sign --key bixxx@xxxxx.com --keyring ./privatekey.gpg ./security --debug
Password for key "xxxx<bxxx@xxxxxx.com>" >

Output of `helm version`:  3.2.4

Output of `kubectl version`: 1.18.5

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

**Comment by bacongobbler** [comment]
As I understand it, Helm calls `gpg` directly, which in turn invokes the `gpg-agent` to prompt for the password. This is input provided on stdin.

You can pass stdin to a command with bash via `<<< "your variable"`. Have you tried that?

**Comment by binititpro** [comment]
Thanks for update. I am new, kindly provide the some command for pass stdin as example.

**Comment by bacongobbler** [comment]
This is your opportunity to find out for your own research. I don’t pretend I know the answers for everything. :)

I’m sure there are plenty of examples available on the internet.
