### ISSUE TITLE
Per subchart namespaces

### ISSUE THREAD

**Issue by agniveshadhikari** [helm/helm#8456]
Is there a way to specify per subchart namespaces during `helm install`?

My chart depends on a third party chart that needs to be installed in a specific namespace. Is there a way to specify this somewhere?

**Comment by bacongobbler** [comment]
there is no way to specify a namespace for a sub-chart. This goes against the design principles of the helm chart, where all of the resources should reside in the same namespace.

If you're looking for more advanced use cases like managing multiple releases across separate namespaces, please look into helmfile.

Thank you.
