### ISSUE TITLE
Update test hook for created chart

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#8457]
When `helm create` is used to create a new chart it creates a test, by default. The test hook is set to `test-success`. This is for legacy purposes as this was the hook in Helm v2. The chart created by Helm v3 is set to `apiVersion: v2` but uses the legacy hook. Internally to the Helm code the legacy hook name is an alias to the new name.

At some point we should update the hook name to `test` in the scaffolded chart.

**Comment by bacongobbler** [comment]
this looks like an easy task for someone interested in contributing code to an open source project.

For reference: https://github.com/helm/helm/blob/e31818f2efd3e1e0867d9c189507c25c8102264a/pkg/chartutil/create.go#L460
