### ISSUE TITLE
Installation failed due to timeout. Possibly due to unreachable api-server? 

### ISSUE THREAD

**Issue by bhandari8sujit** [helm/helm#8459]
`helm version`: version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}

`kubectl version`: Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Baremetal using Kubeadm

Steps taken:

`kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/release-0.38/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml -n monitoring

kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/release-0.38/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml -n monitoring

kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/release-0.38/example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml -n monitoring

kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/release-0.38/example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml -n monitoring

kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/release-0.38/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml -n monitoring

kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/release-0.38/example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml -n monitoring`

**Installation command**
`helm install prometheus-operator stable/prometheus-operator -n monitoring --set prometheusOperator.createCustomResource=false --atomic --wait --debug`

The output of `kubectl logs prometheus-operator-admission-create-fmqdj -n monitoring` is:

`{"err":"Get https://10.96.0.1:443/api/v1/namespaces/monitoring/secrets/prometheus-operator-admission: dial tcp 10.96.0.1:443: i/o timeout","level":"fatal","msg":"error getting secret","source":"k8s/k8s.go:104","time":"2020-07-15T16:22:02Z"}`

Installation logs from using --debug flag:

install.go:159: [debug] Original chart version: ""
install.go:176: [debug] CHART PATH: /home/worker17/.cache/helm/repository/prometheus-operator-8.15.14.tgz

client.go:108: [debug] creating 1 resource(s)
install.go:140: [debug] CRD alertmanagers.monitoring.coreos.com is already present. Skipping.
client.go:108: [debug] creating 1 resource(s)
install.go:140: [debug] CRD podmonitors.monitoring.coreos.com is already present. Skipping.
client.go:108: [debug] creating 1 resource(s)
install.go:140: [debug] CRD prometheuses.monitoring.coreos.com is already present. Skipping.
client.go:108: [debug] creating 1 resource(s)
install.go:140: [debug] CRD prometheusrules.monitoring.coreos.com is already present. Skipping.
client.go:108: [debug] creating 1 resource(s)
install.go:140: [debug] CRD servicemonitors.monitoring.coreos.com is already present. Skipping.
client.go:108: [debug] creating 1 resource(s)
install.go:140: [debug] CRD thanosrulers.monitoring.coreos.com is already present. Skipping.
client.go:258: [debug] Starting delete for "prometheus-operator-admission" PodSecurityPolicy
client.go:108: [debug] creating 1 resource(s)
client.go:258: [debug] Starting delete for "prometheus-operator-admission" ServiceAccount
client.go:287: [debug] serviceaccounts "prometheus-operator-admission" not found
client.go:108: [debug] creating 1 resource(s)
client.go:258: [debug] Starting delete for "prometheus-operator-admission" ClusterRole
client.go:108: [debug] creating 1 resource(s)
client.go:258: [debug] Starting delete for "prometheus-operator-admission" ClusterRoleBinding
client.go:108: [debug] creating 1 resource(s)
client.go:258: [debug] Starting delete for "prometheus-operator-admission" Role
client.go:287: [debug] roles.rbac.authorization.k8s.io "prometheus-operator-admission" not found
client.go:108: [debug] creating 1 resource(s)
client.go:258: [debug] Starting delete for "prometheus-operator-admission" RoleBinding
client.go:287: [debug] rolebindings.rbac.authorization.k8s.io "prometheus-operator-admission" not found
client.go:108: [debug] creating 1 resource(s)
client.go:258: [debug] Starting delete for "prometheus-operator-admission-create" Job
client.go:287: [debug] jobs.batch "prometheus-operator-admission-create" not found
client.go:108: [debug] creating 1 resource(s)
client.go:467: [debug] Watching for changes to Job prometheus-operator-admission-create with timeout of 5m0s
client.go:495: [debug] Add/Modify event for prometheus-operator-admission-create: ADDED
client.go:534: [debug] prometheus-operator-admission-create: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:495: [debug] Add/Modify event for prometheus-operator-admission-create: MODIFIED
client.go:534: [debug] prometheus-operator-admission-create: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
install.go:382: [debug] Install failed and atomic is set, uninstalling release
uninstall.go:92: [debug] uninstall: Deleting prometheus-operator

**Comment by bacongobbler** [comment]
Hi @bhandari8sujit. As this issue relates to a very specific chart (prometheus-operator), please open a ticket against the prometheus-operator chart. This does not appear to be an issue on helm's side. Thank you.
