### ISSUE TITLE
Lookup secrets and create if doesnt exist?

### ISSUE THREAD

**Issue by Ajay250496** [helm/helm#8461]
I'm trying to create a secret via helm only if it does not exists. I found the [lookup](https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-lookup-function) function and it seems to be the solution. I figured I'd just assign this value to a variable and use if to decide if to create secret like this:

```
{{ $secrets := lookup "v1" "secrets" "{{ .Values.client_id }}" "supersecretsecret" }}
{{- if gt (len $secrets) 0 -}}
apiVersion: v1
kind: Secret
metadata:
  name: supersecretsecret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end -}}
```
However this does not work. Is there a way to do this? I can't find much documentation on lookup

Few notes:
-  I've been trying to debug the output of lookup with printf, but can't even get it to print result so im not sure if the function is event working. So far i've tried: 
{{ printf (lookup "v1" "secrets" "{{ .Values.client_id }}" "supersecretsecret").data.auth }}
{{ printf (lookup "v1" "secrets" "{{ .Values.client_id }}" "supersecretsecret").metadata.name }}
{{ printf (lookup "v1" "secrets" "{{ .Values.client_id }}" "supersecretsecret").data}}
..and much more
- I'm trying to set the namespace from a variable (but have also tried just string)

Output of `helm version`:
`version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}`

Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.10-eks-bac369", GitCommit:"bac3690554985327ae4d13e42169e8b1c2f37226", GitTreeState:"clean", BuildDate:"2020-02-21T23:37:18Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  EKS

**Comment by bacongobbler** [comment]
Hi @Ajay250496. I see you found the correct link. Did you try the example provided in the documentation?

For reference:

> When lookup returns a list of objects, it is possible to access the object list via the `items` field:

```
{{ range $index, $service := (lookup "v1" "Service" "mynamespace" "").items }}
    {{/* do something with each service */}}
{{ end }}
```

Looking at your example, I do not see any reference to the `.items` variable, which may be the cause why your code does not work.

**Comment by Ajay250496** [comment]
> `{{ if lookup "v1" "Secret" .Values.client_id "supersecretsecret" }}`

Hey @bacongobbler 

Yeah sorry about the typos and careless mistakes, should've copied that properly. 
I tried your suggestion and it doesnt error out, but also doesnt skip the secrets creations:

Secrets.yaml:
```
{{ if lookup "v1" "Secret" .Values.client_id "supersecretsecret" }}
apiVersion: v1
kind: Secret
metadata:
  name: supersecretsecret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{ end }}
```

I also tried specifying the namespace as a string to test the if statement itself, but that was ignored as well. 

My error is:
Error: rendered manifests contain a resource that already exists. Unable to continue with install: Secret "supersecretsecret" in namespace "othernamespace" exists and cannot be imported into the current release.

**Comment by Ajay250496** [comment]
So I got this working by fixing my typos/formatting as well as changing gt to eq (not sure how i missed that initially..)

```
{{ $secrets := lookup "v1" "Secret" .Values.client_id "supersecretsecret" }}
{{- if eq (len $secrets) 0 -}}
apiVersion: v1
kind: Secret
metadata:
  name: supersecretsecret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{ end }}
```

**Comment by bacongobbler** [comment]
The one problem I foresee with this branch logic: if no secret exists, `helm install` will create the secret. Once you call `helm upgrade`, `lookup` will recognize that the secret exists, and will not template out the secret. This will result in `helm upgrade` removing the secret. That is probably not the desired outcome here.

What you probably want instead is a pre-install hook, along with the `before-hook-creation` deletion policy.

More info available here. https://helm.sh/docs/topics/charts_hooks/#writing-a-hook

**Comment by Ajay250496** [comment]
> 
> 
> The one problem I foresee with this branch logic: if no secret exists, `helm install` will create the secret. Once you call `helm upgrade`, `lookup` will recognize that the secret exists, and will not template out the secret. This will result in `helm upgrade` removing the secret. That is probably not the desired outcome here.
> 
> What you probably want instead is a pre-install hook. More info available here. https://helm.sh/docs/topics/charts_hooks/#writing-a-hook

I added it as a pre-install hook and it works great. Thanks!
