### ISSUE TITLE
OCI: does helm support delete chart from docker registry

### ISSUE THREAD

**Issue by hustclf** [helm/helm#8463]
Output of `helm version`:
v3.1.0
Output of `kubectl version`:
v1.12.4

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
private cloud, without provider

I store charts in docker registry,  and there are many old versions exists as time going on.
Does helm support delete charts from docker registry using oci,  or has a plan to support it?

**Comment by hickeyma** [comment]
@jdolitsky You might be best placed to answer this.

**Comment by jdolitsky** [comment]
@hustclf Helm does not support this currently, but there are ways to achieve this.

How do you picture this w working from a UX perspective?

**Comment by bacongobbler** [comment]
Ref: https://github.com/deislabs/oras/issues/171

**Comment by karlkfi** [comment]
```
crane delete "${IMAGE}@$(crane digest "${IMAGE}:${IMAGE_TAG}")"
```

It would be nice if helm had a `helm chart delete` but it doesn't, likely because historically charts were in git repos and could not be deleted.
