### ISSUE TITLE
Helm3 throwing error validating data: [ValidationError(DaemonSet.spec) ,while helm2 works ok on the same chart

### ISSUE THREAD

**Issue by digeler** [helm/helm#8466]
Output of `helm version`:
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.10", GitCommit:"89d8075525967c7a619641fabcb267358d28bf08", GitTreeState:"clean", BuildDate:"2020-06-23T02:52:37Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS

uploading chart ,that is used with helm2 and stopped working on helm3 
[templates.zip](https://github.com/helm/helm/files/4930366/templates.zip)
when i run with helm2 : all is ok : 
> helm install C:\Users\digeler\AppData\Local\Temp\prom-mdm-converter-chart-132393603271225669 --values C:\Users\digeler\AppData\Local\Temp\prom-mdm-converter-chart-132393603271225669\values0.yaml --values C:\Users\digeler\AppData\Local\Temp\prom-mdm-converter-chart-132393603271225669\values1.yaml --dry-run
NAME:   callous-hamster

when running the same chart with helm3 : 

 helm3 install converter-pod  C:\Users\digeler\AppData\Local\Temp\prom-mdm-converter-chart-132393603271225669 --values C:\Users\digeler\AppData\Local\Temp\prom-mdm-converter-chart-132393603271225669\values0.yaml --values C:\Users\digeler\AppData\Local\Temp\prom-mdm-converter-chart-132393603271225669\values1.yaml
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(DaemonSet.spec): unknown field "replicas" in io.k8s.api.apps.v1.DaemonSetSpec, ValidationError(DaemonSet.spec): unknown field "strategy" in io.k8s.api.apps.v1.DaemonSetSpec, unknown object type "nil" in DaemonSet.spec.template.spec.containers[0].resources.limits.memory, unknown object type "nil" in DaemonSet.spec.template.spec.containers[0].resources.requests.memory]

can you please help me understand why /what have change ,do i have to do changes in my chart or this is a bug in yaml rendering.

**Comment by mattfarina** [comment]
The DaemonSet spec (in the deployment.yaml file) has a `replicas` property set. This is a property on Deployment objects. Deployments and DaemonSet spec do not have the same schema. You can read more about DaemonSets [here](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/) and [here](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#daemonset-v1-apps).

In this case, Helm v3 has caught you trying to use an invalid schema on a Kubernetes resource.

**Comment by digeler** [comment]
got it thanks for the help closing this issue.
