### ISSUE TITLE
Cannot build dependencies (no repository definition / Save error occurred:  could not find : no matching version)

### ISSUE THREAD

**Issue by jarkt** [helm/helm#8469]
Currently I cannot build the dependencies. Crazy is, that it worked already. Don't know what changes have led to this situation.

```
$ helm version
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

Chart.yaml:
```
dependencies:
  - name: mysql
    version: ~6.14.4
    repository: "https://charts.bitnami.com/bitnami/"
  - name: redis
    version: ~10.7.9
    repository: "https://charts.bitnami.com/bitnami/"
```

```
$ helm dependency build ./chart
Error: no repository definition for https://charts.bitnami.com/bitnami/, https://charts.bitnami.com/bitnami/. Please add the missing repos via 'helm repo add'

$ helm repo add bitnami https://charts.bitnami.com/bitnami/
"bitnami" has been added to your repositories

$ helm dependency build ./chart
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "bitnami" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 2 charts
Save error occurred:  could not find : no matching version
Deleting newly downloaded charts, restoring pre-update state
Error: could not find : no matching version
```

As you can see, after I add the repository with the name "bitnami" (which is never referenced!), I only get another error. If I reference "@bitnami" as repository value in Chart.yaml, I get the same output.

**Comment by jarkt** [comment]
After hours of searching and swearing, I found out that I had only to remove the Chart.lock file. Maybe you can rethink helms error handling/output... don't know the real problem.

**Comment by mattfarina** [comment]
@jarkt Thanks for filing the issue. Do you happen to have a copy of the lockfile? Specifically, the entries for these. The error may be due to information that was in that.

`helm dependency build` uses the lockfile if it is present. If not it performs a dependency update which uses a different code path. Somewhere something was causing an error. The following error isn't right...

```
Save error occurred:  could not find : no matching version
```

The "could not find" portion should be followed by a name. This name, if I remember right, comes from the lockfile if it's present.

**Comment by jarkt** [comment]
Chart.lock:
```
dependencies:
- name: mysql
  repository: https://charts.bitnami.com/bitnami/
  version: ~6.14.4
- name: redis
  repository: https://charts.bitnami.com/bitnami/
  version: ~10.7.9
digest: sha256:960e0941b229ac4250063384b4f5d8ca39bed4e69b7d9ac897b2ca40a65da2df
generated: "2020-07-12T20:47:06.865230992Z"
```

**Comment by donggangcj** [comment]
@mattfarina  As you say in issue #8449 ,  lock file should lock to a specific version.
https://github.com/helm/helm/issues/8449#issuecomment-658823990

The `v1`  variable is ~6.14.4  in this case and `v2` is a specific version, so they're never going to be equal. 
https://github.com/helm/helm/blob/6a536661fcf1dc0315798ece70bbf193e725945c/pkg/downloader/manager.go#L607

**Comment by mattfarina** [comment]
@jarkt Two things...

1. #8478 is a PR to fix this issue. Could you take a look?
2. A short term fix is to add any repositories using `helm repo add` before doing `helm dep up` so that it can lock to versions rather than using the version range in the lockfile.

**Comment by jarkt** [comment]
I can test my case against this version. But I've no Computer available before Tuesday.

Am 17. Juli 2020 21:47:27 MESZ schrieb Matt Farina <notifications@github.com>:
>@jarkt Two things...
>
>1. #8478 is a PR to fix this issue. Could you take a look?
>2. A short term fix is to add any repositories using `helm repo add`
>before doing `helm dep up` so that it can lock to versions rather than
>using the version range in the lockfile.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/helm/helm/issues/8469#issuecomment-660306051

-- 
Jark Tonnätt
 -Softwareentwickler im Webbereich-
Eisenacher Str. 46, 12109 Berlin
+49 176 625 65 385
