### ISSUE TITLE
Helm upgrade release with dependecies from getRelease metadata results in removing dependecies

### ISSUE THREAD

**Issue by nirroz93** [helm/helm#8480]
Bug description
--------------
helm install foo  (example chart is below) with dependency for chart bar then upgrade it with golang GetRelease upgrade release  (golang pseudo-code example in the end) results in deleting all dep manifests.

The reason behind  the bug is that dependencies are not saved in release meta data (by design to save space as etcd key value limits objects size).

However, this is a real non-intuitive behaviour, the expected behaviour should result in leaving the chart as it is (maybe add a param to action.Upgrade to skip dependencies objects?). Hopefully there is a way to identify these manifests it without exceeding the 1MB limit .

Actual behaviour 
--------------
Something like (assuming release foo in the example below is already installed) :

```
getRelease := action.NewGet(cfg) 
res, err := getRelease.Run(e.release)
upgrade := action.NewUpgrade(cfg)
res, err := upgrade.Run(
			res.Name,
			res.Chart,
                        res.Config)
```

will result in:
```
2020/07/18 12:32:12 preparing upgrade for foo
2020/07/18 12:32:13 performing update for foo
2020/07/18 12:32:13 creating upgraded release for foo
2020/07/18 12:32:13 checking 3 resources for changes
2020/07/18 12:32:13 Looks like there are no changes for ServiceAccount "foo"
2020/07/18 12:32:13 Looks like there are no changes for Service "foo"
2020/07/18 12:32:13 Looks like there are no changes for Deployment "foo"
2020/07/18 12:32:13 Deleting "foo-bar" in default...
2020/07/18 12:32:13 Deleting "foo-bar" in default...
2020/07/18 12:32:13 Deleting "foo-bar" in default...
2020/07/18 12:32:13 Deleting "foo-bar-test-connection" in default...
2020/07/18 12:32:13 Deleting "foo-test-connection" in default...
2020/07/18 12:32:13 updating status for upgraded release for foo
```

Example chart
---------------------
```
helm create foo
cd foo/charts
helm create bar
helm install foo ..
```

Helm/Kubectl versions
---------------------
Output of `helm version`:
`version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}`
(checked also with 3.3.0-rc1)
Output of `kubectl version`:
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

_Update (mattfarina): added code blocks for formatting._

**Comment by mattfarina** [comment]
@nirroz93 if I understand it right... you're trying to get the chart off the release and then use that for upgrades.

I wonder how this impacts rollback. There are some possible bugs in here.

**Comment by nirroz93** [comment]
@mattfarina You understand correctly.

I don't understand how this would impact the rollback (rollback is done base on the manifest that are saved per version, isn't it?).

**Comment by bacongobbler** [comment]
I'm not sure if this is something we plan to support given the same reasons stated earlier. How would you propose we could support this use case?

@mattfarina this would not affect `helm rollback` - `helm upgrade` saves all rendered manifests in the chart release metadata. We just don't save extra information like the pre-rendered templates necessary for a use case like this one.

**Comment by bacongobbler** [comment]
marking as a use case as we have not seen this case come up before.

**Comment by nirroz93** [comment]
I don't really know/understand how the release metadata is saved (I need to drill down more to understand it), but in helm get manifest the output has "# Source: " prefix, and get manifest includes the sub-chart manifests. So from this I guessed that the manifests metadata includes the original template file path (and therefore it shouldn't be hard to get subcharts objects from the current release and add them to a ~~blacklist~~ deny list in upgrade).

**Comment by bacongobbler** [comment]
`helm get manifest` displays the manifests, post-render. Those are saved in the release object, and those are the same manifests used during `helm rollback`. We just don't include the pre-rendered templates as there's no need for them after the manifests have been rendered - we're keeping them around to help `helm rollback` to revert back to that release's state, but we don't need the place the templates back through the rendering engine.

Hope that helps clarify things.

**Comment by nirroz93** [comment]
Yes, but I dont suggest to re-template them. I just want the objects to stay as they are (don't delete them)

**Comment by bacongobbler** [comment]
I’m confused... What you’re describing is how `helm rollback` works. If you’re re-using the post-rendered manifests to perform an “upgrade”, you’re performing a rollback. A rollback is effectively an upgrade to a previously known state. It even bumps the release version when you invoke it.

How would your use case differ from just calling `helm rollback` instead?

**Comment by nirroz93** [comment]
My case is just using upgrade. I simplified it to a "rollback" with upgrade demonstrate the problem, so the code above really really a weird rollback but lets say that I want to upgrade the current release values (not touching values related to "bar" release) - Currently the only option is to have bar release on local.  

Upgrade should do the same as rollback in this case (or at least should have a flag to do it same as rollback) - not deleting the release dependencies.
