### ISSUE TITLE
Using Github Pages to host a Helm Repository gives error in Helm install

### ISSUE THREAD

**Issue by avinashkumar1289** [helm/helm#8490]
I am trying to set up Private Helm repositories using Github Pages .I have followed the instructions mentioned here https://helm.sh/docs/topics/chart_repository/  
I am able to add chart in the repository and generate the index.yaml file .  
Once I have added my new repository using ``` helm repo add ``` and then ```helm repo update```
I can also pull the helm chart using ```helm pull testrepo/testchart``` 
But I cannot install the chart using ```helm install test123 test/repo```
Getting the below error message.
```helm install test123 testrepo/testchart
Error: file '/Users/avinash/Library/Caches/helm/repository/testchart-0.1.0.tgz' does not appear to be a gzipped archive; got 'text/html; charset=utf-8'
```
I even tried to clear the Caches but it didnt help.

Output of `helm version`: v3.0.0

Output of `kubectl version`: v1.18.2

**Comment by yxxhero** [comment]
where is your github pages address?

**Comment by avinashkumar1289** [comment]
So i am kind of trying with the Private repository.But let me repeat the steps in a public and send you the address

**Comment by mattfarina** [comment]
@avinashkumar1289 If you are trying it on a private repository, that may be part of your problem.

Private repositories are protected. Helm cannot access their material. If you inspect the file at _/Users/avinash/Library/Caches/helm/repository/testchart-0.1.0.tgz_ do you find the contents are a 404 page?

**Comment by avinashkumar1289** [comment]
@mattfarina So the content is not 404 but its an error page from microsoft 
```https://login.microsoftonline.com/cookiesdisabled``` something with this
![image](https://user-images.githubusercontent.com/39315791/87955315-32f04380-cacb-11ea-94f5-2d6a5de40277.png)

Looks like its not able to authenticate.

**Comment by mattfarina** [comment]
@avinashkumar1289 hosting a repository on GitHub is only useful for public repositories. If you are going to do it as a private repo you could use object storage, chart museum, or something else.

**Comment by bacongobbler** [comment]
It sounds like this question has been answered. Please use a service like the ones @mattfarina listed above if you're looking for chart repositories that can be backed by some form of an auth mechanism.

Thanks.

**Comment by avinashkumar1289** [comment]
@bacongobbler  @mattfarina  Yeah actually using a different branch gh-pages in github actually solved my problem.I am not sure why stuff wont work on master but on a different branch.But glad its working
