### ISSUE TITLE
Proposal: Sub-releases

### ISSUE THREAD

**Issue by nirroz93** [helm/helm#8495]
I was wondering why there aren't sub-release (created by chart dependecies). 

I think sub-release is pretty self-explanatory  but I the idea is that a release can be splitted into a parent release and sub-releases (so metadata will say what the sub releases are and the sub-releases metadata will be saved separately).

Some of the pros that I see:

1. Order: It is easier for the user to have an option to see only small and separate part of a big chart (helm get values sub-release, helm get manifests sub-release). It's also easier to see that no changes were made for the release in the upgrade, listing umbrella charts components (without checking what was enabled/disabled in the deployment itself) and more.
2. Option to save all the metadata of the sub releases, no risk of getting to 1MB limit
3. Option to upgrade sub-release separately from the whole release (I just want to change a small value, effecting only the non-critical component in the sub-sub-chart, why do I need to upgrade to whole release?)
4. Option to set release name for sub charts. Currently sub-sub-sub-sub charts will have long-long-long-long name by default (so override is needed)

Probably many more pros (and cons) that I don't think about now (and many major changes and difficulties in doing it).

However,  I don't know if this change is worth the work needed for it . I was just surprised that I didn't find a feature request for this (even in the close issues).

**Comment by jdolitsky** [comment]
@nirroz93 I'm wondering if some of the issues you're having could be solved by breaking your chart into multiple, and having multiple top-level releases. Such a proposal would be a large shift in the way that things currently work. It also raises questions of, what does it mean to delete a subrelease? etc.

I do see the benefit of 1MB limit, but maybe this can be fixed transparently to the user by sharding the release object somehow.

**Comment by bridgetkromhout** [comment]
Hi, @nirroz93 - thank you for your idea. As suggested, you could use multiple charts with multiple releases. And as you also pointed out, this is a large change which could have many implications. We now have a process for proposing large changes and discussing them in the community before you start implementation; please take a look at https://github.com/helm/community/blob/master/hips/hip-0001.md and if that's of interest, you can file a Helm Improvement Proposal to start thinking through this.

I will close this issue in favor of the HIP process (if desired). Thanks.
