### ISSUE TITLE
Hidden 'helm docs' command VS. norwoodj/helm-docs plugin

### ISSUE THREAD

**Issue by bcollard** [helm/helm#8500]
Hi,

I've just discovered this [norwoodj/helm-docs](https://github.com/norwoodj/helm-docs) tool, making easy the README.MD update task, via go templates, with the chart's metadata.

By using a `readme.md.tmpl` template, you can pick values from the Chart metadata and then generate some consistent documentation. Also, you can document values by adding comments next to them in the values.yaml.

I think this is super great tool and it really makes sense in a CI pipeline, supposing you have a job checking that your README.md was updated with newest variables made available - or new default values.

IMHO, Helm users would appreciate such tooling when simply running the `helm docs` command in their chart directory; instead of the [current undocumented behavior](https://git.k2software.com.cn/go/helm/commit/aca9f86df62f6ff13fdade755ece70d25bdfe079).

Output of `helm version`: Version:"v3.2.1"

What do you think?

**Comment by bacongobbler** [comment]
The plugin you mentioned generates markdown from a chart. `helm docs` generates markdown files for `helm help`. The use cases are very dissimilar in design.

**Comment by bacongobbler** [comment]
In general, it is up to the community member to determine whether they’d like their code to be contributed to helm or not. You would also need to build consensus from the community to determine if this is a popular feature or not. We generally do not want to bake in every single feature the community comes up with - just the ones that are used by the broader community. We try to stick to the UNIX philosophy of doing one thing well.

I would reach out to the maintainer of said plugin and see what they think.
