### ISSUE TITLE
Github releases/latest URL return Helm 2 version

### ISSUE THREAD

**Issue by grailsweb** [helm/helm#8502]
I use this URL to get the latest helm binary https://github.com/helm/helm/releases/latest, today it gives helm 2 binary version. I expect to get helm 3 latest version

Output of `helm version`:

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

```
curl -sSk https://github.com/helm/helm/releases/latest
<html><body>You are being <a href="https://github.com/helm/helm/releases/tag/v2.16.9">redirected</a>.</body></html>
```

**Comment by bacongobbler** [comment]
This has been reported multiple times, and closed for the same reason:

- #8304
- #7813
- #7606
- #7603
- #7598
- #7597
- #7594
- #7592
- #7590

Github’s API describes “latest” as the most recently released version of that repository. It does not correlate to the newest version of helm 3. We have no control over this API.

Helm 2.16.9 was the most recent to be released, hence why it is now considered “latest”.

Hope this clears things up.

Please search for existing issues before opening a new one.
