### ISSUE TITLE
proposal: add Chart Version to helm list output

### ISSUE THREAD

**Issue by nicktrav** [helm/helm#8503]
We have a use case for determining the Chart Version of a chart installed in to a cluster, as distinct from the App Version, which can already be inferred / discovered.

I'd like to request / propose that Chart Version be added as a column to the output of `helm list`.

For example, here's the current output:

```
NAME                    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
...
prometheus-operator     prometheus      1               2020-07-21 23:32:48.402769335 +0000 UTC deployed        prometheus-operator-8.5.12      0.34.0
```

Interestingly, the Chart Version is already encoded into the Chart field. Under the hood, this is generated by concatenating the `Metadata.Name` and `Metadata.Version` fields:

https://github.com/helm/helm/blob/0ad800ef43d3b826f31a5ad8dfbb4fe05d143688/cmd/helm/list.go#L158

Perhaps these two individual fields could be printed, separately, in addition to the concatenated form.

**Comment by nicktrav** [comment]
@bacongobbler - happy to take this one on if it seems reasonable?

**Comment by bacongobbler** [comment]
Seems reasonable.

**Comment by Cweiping** [comment]
I checked that this would cause some users using `-o json` and `-o yaml` flag not to work.
If you are sure of this change, can I do it? @bacongobbler @nicktrav

**Comment by nicktrav** [comment]
> I checked that this would cause some users using -o json and -o yaml flag not to work.

@Cweiping - could you clarify what you mean here? The intention was for this change to be purely additive. One new field in the output would be added for the chart version. This should not affect the existing fields. I would not expect it to impact YAML or JSON formatting.

> If you are sure of this change, can I do it?

I was planning on picking this up in the next day or so.

**Comment by bacongobbler** [comment]
@Cweiping, @nicktrav has already asked to implement this. As he originally brought this up it would be fair for him to implement it.

I'm not sure what @Cweiping means by this feature would cause the output flags to not work. As long as this is implemented correctly and covered with unit tests, the output flags should continue to work as expected.

**Comment by Cweiping** [comment]
HAHA! Nevermind. 

Outdate:
```bash
helm ls -o json
```
```
[{"name":"dao-2048","namespace":"default","revision":"1","updated":"2020-07-24 01:37:35.026479393 +0000 UTC","status":"deployed","chart":"dao-2048-0.1.1","app_version":"0.1.2"}]
```
Now:
```bash
helm ls  -o json
```
```
[{"name":"dao-2048","namespace":"default","revision":"1","updated":"2020-07-24 01:37:35.026479393 +0000 UTC","status":"deployed","chart_name":"dao-2048","chart_version":"0.1.1","app_version":"0.1.2"}]
```
If the user completes the function integration based on it, it may require the user to complete the adaptation.It's just a tip.
