### ISSUE TITLE
Possiblly memory leak when installing chart with Helm v3 SDK

### ISSUE THREAD

**Issue by feicun** [helm/helm#8504]
Helm SDK version: v3.1.3

kubectl version output:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.9", GitCommit:"500f5aba80d71253cc01ac6a8622b8377f4a7ef9", GitTreeState:"clean", BuildDate:"2019-11-13T11:21:43Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-49202c", GitCommit:"49202cb0a6d5e481319ba21f0b068f112a29a4e5", GitTreeState:"clean", BuildDate:"2020-05-23T20:16:40Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

go mod:
```
module helm-service-operator

go 1.14

require (
	github.com/Masterminds/semver v1.5.0 // indirect
        ......
	gopkg.in/yaml.v2 v2.2.8
	helm.sh/helm/v3 v3.1.3
	k8s.io/api v0.17.4
	k8s.io/apimachinery v0.17.4
	k8s.io/cli-runtime v0.17.4
	k8s.io/client-go v0.17.4
)
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

--------------

I'm running a helm service operator in a pod. The operator has a reconcile loop to watch for helm chart install/upgrade request, if an installation request come in, the operator will call Helm V3 client to perform an installation.

I have a script to send install request every 10 seconds, which means the helm chart install operation will be performed every 10 seconds. After my script runs for few days, I can see the memory usage of operator pod is trending up. For every 6 hours, the memory usage increased about 4 MB. And after few days, the operator pod reached OOM status and be killed and re-created by Kubernetes.

Not sure if I misunderstood something, but I expect the memory usage of my operator pod should be stable rather than slightly trending up.

Here is my code for perform the chart installation:
```
import (
        .....
	"helm.sh/helm/v3/pkg/chart/loader"
	"helm.sh/helm/v3/pkg/chartutil"
	helmV3Release "helm.sh/helm/v3/pkg/release"
)

func Install(chartPath, namespace, releaseName string, mergedValues map[string]interface{}) (*helmV3Release.Release, error) {
    chart, err := loader.Load(chartPath)
    if err != nil {
        return nil, err
    }

    cachedClient, err := GetCachedClient(actionInstall, namespace)
    if err != nil {
        return nil, err
    }
    installCli, ok := cachedClient.(*helmAction.Install)
    if !ok {
        return nil, errors.New("type assertion failed for an object in Install Client Cache")
    }

    installCli.Namespace = namespace
    installCli.ReleaseName = releaseName
    installCli.DryRun = opts.DryRun
    installCli.Timeout = time.Duration(GetHelmActionsTimeOut()) * time.Second
    installCli.Wait = helmInstallWait
    rel, err := installCli.Run(chart, mergedValues)
    if err != nil {
        return nil, err
    }
    return rel, nil
}
```

I also have a sync map as cache for storing install client for each of namespace, because I don't want to create a install client for each of installation request. The key of sync map is namespace, value is installation client object. The `GetCachedClient()` function is the helper function to fetch the cached clients.

**Comment by bacongobbler** [comment]
Thanks for the report.

Do you have a sample main.go file we can use to reproduce the issue? It’s a little difficult to determine where a memory leak may occur from a code snippet. Thanks!
