### ISSUE TITLE
How to pass multiple parameters to "tpl" function?

### ISSUE THREAD

**Issue by alwaysastudent** [helm/helm#8506]
I am trying to pass multiple parameters to the `tpl` function, how is it possible?

```
#values
env: {{- .Env -}} 


# template
{{ tpl .Values.env dict "Values" .Values "Env" "foo" }}


#output
Error: cannot load values.yaml: error converting YAML to JSON: yaml: did not find expected node content

```

I was trying this and but it does not work. 

Can anyone please advice on how to pass multiple arguments to the `tpl` function ?

**Comment by bacongobbler** [comment]
The first argument to `tpl` is the name of the template, then the variable passed in.

https://helm.sh/docs/howto/charts_tips_and_tricks/#using-the-tpl-function

It’s unclear here how you intended to use the function. I cannot tell what is the name of the function (I don’t see a `define` here), and which values are to be passed to the function. But you seem to be on the right track.

Have a look at the documentation first and let us know if you run into any issues along the way.

**Comment by bacongobbler** [comment]
My first thought might be to try wrapping your arguments to `dict` in parentheses.

**Comment by alwaysastudent** [comment]
> My first thought might be to try wrapping your arguments to `dict` in parentheses.

Thank you for the suggestion. I am trying to pass in multiple parameters to the `tpl` function. The documentation only shows how to transfer the current context to the function with the `.`, but I would like to pass in a string for example. I found we can use a dictionary if it were an `include`/`template`. But for `tpl` function I would like to know if that would work.

```
#template
{{ tpl .Values.env (dict "Values" .Values "Env" "foo") . }}

#values
env: {{ .Env }}

#output
Error: cannot load values.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".Env":interface {}(nil)}

#desired output should be foo
```

**Comment by bacongobbler** [comment]
I think you need to remove the dot operator from the end of your `tpl` call:

```
{{ tpl .Values.env (dict "Values" .Values "Env" "foo") }}
```

As `tpl` only accepts three arguments.

I'm not sure what might be causing your issue with the "invalid map key" error, but please let us know if you happen to find a bug. If I were to take a guess, that error would appear to indicate invalid input to the function call.

If you can provide a sample chart that we can use to reproduce the issue, we can look into it further. Without a sample case to reproduce your issues, ll we can do is try to interpret the results.

**Comment by alwaysastudent** [comment]
@bacongobbler - seems like it does not work as expected. 

Please find the chart for testing this out under https://github.com/alwaysastudent/scrapy

**Comment by mattfarina** [comment]
I think we have a bug. I tried the example at https://helm.sh/docs/howto/charts_tips_and_tricks/#using-the-tpl-function and am getting the error...

```
Error: YAML parse error on sample/templates/applications.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type releaseutil.SimpleHead

Use --debug flag to render out invalid YAML
```

**Comment by wawa0210** [comment]
> #values
> env: {{ .Env }}

After testing, if you include special characters in values.yaml, such as `{{`,`}}`, errors will occur during json conversion

**Comment by wawa0210** [comment]
> I think we have a bug. I tried the example at https://helm.sh/docs/howto/charts_tips_and_tricks/#using-the-tpl-function and am getting the error...

It seems that the examples provided in the official website documents can no longer run successfully, you need to convert the values ​​to json format to run normally

![image](https://user-images.githubusercontent.com/7907809/89419759-5cb09800-d764-11ea-8688-42e191511e2d.png)

if we change the `conf/app.conf` to 

```
{
  "firstName": {{ .Values.firstName }},
  "lastName": {{ .Values.lastName }}
}
```
This can run successfully, do we need to update the official website documents or let helm support this scenario?

if ok, i can fix that

**Comment by wawa0210** [comment]
@alwaysastudent 

 It had to be a string ,if we use like this ,every thing is ok   

```

# values 
Env: |
  - production
  - staging
  - development
  - null

# template 
{{ tpl .Values.Env . }}
```
ref https://github.com/helm/charts/issues/7633

**Comment by ebuildy** [comment]
`tpl` function requires the "root" context as second parameter.

See the solution from https://github.com/helm/helm/issues/5979 to add variable into the root context:

``` 
{{- range $key, $value := .Values.list }}
{{- $_ := set $ "key" $key }}
{{- $_ := set $ "value" $value }}
{{- tpl ($.Files.Get "sub.yaml") $ }}
{{- end }}
```

**Comment by r351574nc3** [comment]
What worked for me is this:
```
{{- tpl .Values.template (merge $ (dict "foo" .Values.foo "bar" .Values.bar)) }}
```
