### ISSUE TITLE
helm template --create-namespace does not include namespace manifest

### ISSUE THREAD

**Issue by fredleger** [helm/helm#8509]
Output of `helm version`: 3.2.1

Output of `kubectl version`: kubectl 1.18.2

Cloud Provider/Platform (AKS, GKE, Minikube etc.): any

I think that most people would wait for the namespace definition to be included in the output if --create-namespace is supported when doing an `helm template` command.

AMHO the choices are:
- either clearly refuse `--create-namespace` with `helm template` subcommand (which is ok but peaople will then rely to other tooling or issues kubectl commands)
- or add the manifests creation of the namespace in output (which is better if you rely on helm to generate your manifests)

**Comment by bacongobbler** [comment]
This might be related to https://github.com/helm/helm/issues/8268, where invalid subcommands are being silently accepted as valid input by cobra. This could be extending towards invalid feature flags as well.

I would argue that the first case is preferred here. The namespace should not be part of the output - `helm template`'s only job is to display the output from rendering the templates.

**Comment by fredleger** [comment]
hi @bacongobbler 

ok it make sense it's related to this cobra bug. thanxs for pointing that out.

i understand the point of helm template being tied to rendering templates. The only reason that would made me prefer the 1st choice is that will enable end users to leverage on helm3 to create manifests in a gitops style approach. There is currently no direct way to do that except some crapy bash tooling. But i guess you are right on the perimeter of helm template and i was more formulating something like `helm dump`, but i guess this is another enhancement issue.

**Comment by bacongobbler** [comment]
Closing in favour of #8268.
