### ISSUE TITLE
Does helm uninstall delete pvcs?

### ISSUE THREAD

**Issue by aditya1808** [helm/helm#8515]
Output of `helm version`:
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:47:40Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:37:43Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Hi, This is more of a question than an issue.

After going through the already reported issues, i understood that helm delete doesnot remove the PVCs.

Although i have two questions.
1) Does helm uninstall remove the PVCs??
2) If helm delete --purge doesnt remove pvcs and i install the helm chart again with same name, does it try to use the same pvc again??

Some one please clarify this. Any help is much appreciated.

**Comment by rblaine95** [comment]
Helm will delete PVCs if those PVCs were created by Helm
As in:
```yaml
# mychart/templates/pvc.yml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mychart.fullname" . }}-pvc0
[...]
```
Just like Helm will delete other resources specified in the `templates/` directory.

Helm will **not** delete PVCs if they were created by a StatefulSet which has a `volumeClaimTemplate` config.
This is the same behaviour as with `kubectl`.

If you create a Statefulset which generates PVCs, then the PVCs are created by the Statefulset and not by Helm.
These PVCs will live outside of the Helm Lifecycle.

If you created a StatefulSet with Helm.
And that StatefulSet creates its own PVCs (with the [StatefulSet `volumeClaimTemplates` config](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#components)).
Then the PVCs are not controlled by Helm.
If you then do `helm delete myChartWithAStatefulSet`, then the StatefulSet will be deleted, the PVCs will not.
If you then do `helm install myChartWithAStatefulSet` (without deleting the PVCs), then the StatefulSet will check if any PVCs exist with the correct name (as named in [`volumeClaimTemplates`](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#components)) and will then automatically mount the already existing PVCs.

**Comment by mattfarina** [comment]
To add to @rblaine95, if you want to keep a PVC after uninstalling a chart you can put the `"helm.sh/resource-policy": keep` on it.

**Comment by bacongobbler** [comment]
@aditya1808 did the answers provided above clarify your question?

**Comment by aditya1808** [comment]
@bacongobbler Yes this is exactly the explanation i was looking for. Thanks @rblaine95 , @mattfarina .
Closing the issue.
