### ISSUE TITLE
helm upgrade --install --namespace  this command doesn't work correctly

### ISSUE THREAD

**Issue by thefuckingcode** [helm/helm#8517]
helmVersin: v3.2

if the namespace in k8s doesn't exist , this command wont create namespace as help manul described:
```
--create-namespace             if --install is set, create the release namespace if not present
```
or do i just misunderstand the meaning of *--create-namespace*?

**Comment by mattfarina** [comment]
You need to use the command `helm upgrade --install --create-namespace --namespace foo` where `foo` is the name of the new namespace. This tells Helm to install if it's not already installed, to use the namespace `foo`, and to create the namespace if now present. Did you run this?

I tried to replicate the problem but was unable to with the full command. If you are still experiencing it could you provide the operating system and full command you are running to help us diagnose the source of the issue.

**Comment by thefuckingcode** [comment]
> You need to use the command `helm upgrade --install --create-namespace --namespace foo` where `foo` is the name of the new namespace. This tells Helm to install if it's not already installed, to use the namespace `foo`, and to create the namespace if now present. Did you run this?
> 
> I tried to replicate the problem but was unable to with the full command. If you are still experiencing it could you provide the operating system and full command you are running to help us diagnose the source of the issue.

helm upgrade --install  \
    choerodon-cluster-agent-cluster2 \
    --repo=http://chart.choerodon.com.cn/hzero/c7ncd/ \
    --namespace=choerodon \
    --version=0.22.3 \
    --set config.connect=ws://explae.com \
    --set config.token=be53522c-246 \
    --set config.email=o10@qq.com \
    --set config.clusterId=4 \
    --set config.choerodonId=ac34bec00 \
    --set rbac.create=true \
    choerodon-cluster-agent

**Comment by thefuckingcode** [comment]
> You need to use the command `helm upgrade --install --create-namespace --namespace foo` where `foo` is the name of the new namespace. This tells Helm to install if it's not already installed, to use the namespace `foo`, and to create the namespace if now present. Did you run this?
> 
> I tried to replicate the problem but was unable to with the full command. If you are still experiencing it could you provide the operating system and full command you are running to help us diagnose the source of the issue.
![image](https://user-images.githubusercontent.com/23526448/88556022-1d46c500-d05b-11ea-80cb-5ee2dda6d69b.png)

should it be like this? What i expected was this command would create a namespace named 'choerodon',but it failed

**Comment by bacongobbler** [comment]
Given the command you provided: no, the namespace will not be created for you, as you did not provide the `--create-namespace` flag.

If you want the namespace to be created, use the following:

```
helm upgrade --install
choerodon-cluster-agent-cluster2
--repo=http://example.repo.cn
--namespace=choerodon
--create-namespace
--version=0.22.3
--set config.connect=ws://explae.com
--set config.token=be53522c-246
--set config.email=o10@qq.com
--set config.clusterId=4
--set config.choerodonId=ac34bec00
--set rbac.create=true
choerodon-cluster-agent
```

**Comment by thefuckingcode** [comment]
> Given the command you provided: no, the namespace will not be created for you, as you did not provide the `--create-namespace` flag.
> 
> If you want the namespace to be created, use the following:
> 
> ```
> helm upgrade choerodon-cluster-agent-cluster2
> --install
> --repo=http://example.repo.cn
> --namespace=choerodon
> --create-namespace
> --version=0.22.3
> --set config.connect=ws://explae.com
> --set config.token=be53522c-246
> --set config.email=o10@qq.com
> --set config.clusterId=4
> --set config.choerodonId=ac34bec00
> --set rbac.create=true
> choerodon-cluster-agent
> ```

```
 helm upgrade --help
...

Flags:
     --create-namespace             if --install is set, create the release namespace if not present
  ...
```
this is what i get from *helm upgrade --help*

 the usage for 'create-namespace',it tells me if --install is set, create the release namespace if not present.so i think if i provide --install ,this command will create namespace automatically without *--create-namespace*.am i wrong?

**Comment by bacongobbler** [comment]
I think you're interpreting the help string wrong. What it is trying to say is that `--create-namespace` only applies when `--install` is provided. If you did not provide `--install` (e.g. `helm upgrade --create-namespace`), the flag is ignored.
