### ISSUE TITLE
post renderes don't work when helm template writes to a file

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#8520]
Output of `helm version`: v3.3.0-rc.1

In the function `renderResources` the post renderer is run after the files have been written to disk and does not affect the files.

**Comment by mattfarina** [comment]
@donggangcj You may want to hold off on this. @technosophos is going to rewrite this section of code. It's mixing concerns. He's the one who put the comment on needing to refactor `renderResources` at the top of it. His rewrite will affect any work on this and may correct the issue.

**Comment by donggangcj** [comment]
ok！I am very in favor of rewriting this part of the code . 👍

**Comment by unguiculus** [comment]
Just stumbled upon this myself. Any chance we can get a quick fix before doing a bigger rewrite in this area? @technosophos @mattfarina

**Comment by technosophos** [comment]
This is the fix so far: #8573 It is non-trivial.

**Comment by unguiculus** [comment]
Any progress on this?
