### ISSUE TITLE
Heml3: Upgrade of secret with immutable field fails

### ISSUE THREAD

**Issue by whitecolor** [helm/helm#8524]
Output of `helm version`: 3.3

Output of `kubectl version`: v1.16.6-beta.0"

I changed/set type of secret after it was created in release, and helm faild to upgrade release.

> Error: UPGRADE FAILED: cannot patch "gcr-cred" with kind Secret: Secret "gcr-cred" is invalid: type: Invalid value: "kubernetes.io/dockerconfigjson": field is immutable

So probaly in such cases helm should recreate resource, but not throw the error?

**Comment by hickeyma** [comment]
@whitecolor Can you provide some details around "changed/set type of secret after it was created in release"? It would help to better try and troubleshoot the issue.

**Comment by whitecolor** [comment]
I first created release with chart containing named secret that didn't have `type` field, then I changed it (added to chart resource), and tried to upgrade the release.

**Comment by hickeyma** [comment]
The error is being returned from Kubernetes and it is saying that the type field of the secret object cannot be updated. You should get the same error if you try to update it using Kubernetes directly e.g. using `kubectl`.

If you can, it maybe best to remove the release and re-install with the correct secret type.

**Comment by whitecolor** [comment]
> If you can, it maybe best to remove the release and re-install with the correct secret type.

I did this. I'm telling that probably heml itself could handle this by fully removing resource and recreating it.

**Comment by hickeyma** [comment]
Helm calls the Kubernetes API to apply updates. It is therefore working as expected and returning the expected error.

You can use the `--force` flag but that pretty much destroys the resources and recreates them. So, similar to doing it as a user.

Hope this answers your question.

**Comment by whitecolor** [comment]
Ok, I belive, thanks)
