### ISSUE TITLE
helm v3.3.0-rc.1 package is stripping comments from values.yaml

### ISSUE THREAD

**Issue by SrikanthSrinivasamurthy** [helm/helm#8526]
In Helm 3.3.0-rc.1 , helm package appears to be stripping the comments out of the values file. 
.
Output of `helm version`:  version.BuildInfo{Version:"v3.3.0-rc.1", GitCommit:"5c2dfaad847df2ac8f289d278186d048f446c70c", GitTreeState:"dirty", GoVersion:"go1.14.4"}

Output of `kubectl version`:  Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  windows 10 docker-edge 2.3.3.2
values.yaml before package
`
    
    
    #### Specifies database type, either mariadb or oracle
    smp:
      database:
        type: mariadb

    dmaProperties: |
      #########################
      #
      # HAZELCAST
      #
      #########################
      adapter.name=hazelcast
      ### hazelcast client configurations
    
      ### Mode can be IN_VM or OUT_VM.
      ### IN_VM mode honours hazelcast.xml if provided in config or uses hazelcastconfig.properties
      hz.mode=IN_VM
    
      ### Client configuration not required in IN_JVM mode. Mandatory to provide a valid client xml in OUT_JVM mode
      hz.client_xml=NONE
    
    
      #########################
      #
      # REDIS - Redisson Client Library
      #
      #########################
    
      #adapter.name=REDIS_REDISSON
      #Redis mode can be standalone,sentinel,masterslave
      #redis.mode=sentinel
    
`

values.yaml after package

`
    
    
    smp:
      database:
        type: mariadb

    dmaProperties: "\n#### Adapter settings\n\n#########################\n#\n# HAZELCAST\n#\n#########################\nadapter.name=hazelcast\n###
    hazelcast client configurations\n\n### Mode can be IN_VM or OUT_VM.\n### IN_VM
    mode honours hazelcast.xml if provided in config or uses hazelcastconfig.properties\nhz.mode=IN_VM\n\n###
    Client configuration not required in IN_JVM mode. Mandatory to provide a valid
    client xml in OUT_JVM mode\nhz.client_xml=NONE\n\n\n#########################\n#\n#
    REDIS - Redisson Client Library\n#\n#########################\n\n#adapter.name=REDIS_REDISSON\n#Redis
    mode can be standalone,sentinel,masterslave\n#redis.mode=sentinel\n\n
    
`

**Comment by hickeyma** [comment]
@SrikanthSrinivasamurthy Thanks for raising the issue. To help troubleshooting your issue, do you mind showing the commands you are running and the output?

**Comment by mattfarina** [comment]
I've attempted to reproduce this on both Mac and Windows and have not been able to. I think we need the specific commands.

**Comment by SrikanthSrinivasamurthy** [comment]
@hickeyma we are using com.kiwigrid 5.5 maven plugin for packing, so we are using `mvn clean install` command.
attached the **mvnOutput.txt** and after package attached  **values.txt** from extracted smp-core-200.0.0-202007281212.tgz
renamed values.yaml to values.txt for file uploading to this github issue

[mvnOutput.txt](https://github.com/helm/helm/files/4988967/mvnOutput.txt)


[values.txt](https://github.com/helm/helm/files/4988971/values.txt)

**Comment by hickeyma** [comment]
To try and understand this better, are you saying that:

1) You package a chart into a gzipped tarball using `com.kiwigrid 5.5 maven plugin`
2) When you extract the tarball (what command are you using?), the `values` no longer contain comments

**Comment by hickeyma** [comment]
Or are you then installing the chart using the tarball. and you see the output incorrect?

**Comment by SrikanthSrinivasamurthy** [comment]
@hickeyma yeah for we are using com.kiwigride 5.5 plugin to package. 
and for extract the tarball, i am using 7zip GUI in windows system. if you see the values.yaml commented lines are completely removed.

**Comment by hickeyma** [comment]
ok, then this is probably an issue with com.kiwigride 5.5 plugin. Do you mind raising this issue with the plugin instead? You can reference the issue #  here if you like.

**Comment by SrikanthSrinivasamurthy** [comment]
@hickeyma  yeah its issue with helm-maven-plugin , when i ran `**helm packge mychart\**` and check values.yaml file inside tgz file its correct having commented line and maintained format.
 raised the issue in helm-maven-plugin [https://github.com/kiwigrid/helm-maven-plugin/issues/90](https://github.com/kiwigrid/helm-maven-plugin/issues/90)

**Comment by bacongobbler** [comment]
closing as this is an issue with a community plugin. No action to take here on our end.

**Comment by hickeyma** [comment]
ok, thats great @SrikanthSrinivasamurthy. Hope it is sorted shortly for you.
