### ISSUE TITLE
Helm library chart working example

### ISSUE THREAD

**Issue by pratapagiri** [helm/helm#8528]
Can someone point me to working example of a helm library chart? I tried to follow the documentation and it didn't work.

Output of `helm version`: n/a

Output of `kubectl version`: n/a

Cloud Provider/Platform (AKS, GKE, Minikube etc.): n/a

**Comment by hickeyma** [comment]
Is this the [library docs](https://helm.sh/docs/topics/library_charts/) you are referring to? If so, what is not working?

**Comment by pratapagiri** [comment]
@hickeyma Thanks for your reply.

I'm getting below error-
`Error: template: mychart/templates/service.yaml:3:4: executing "mychart/templates/service.yaml" at <include "common.service" (list . .Values.service)>: error calling include: template: mychart/charts/common/templates/_service.yaml:22:4: executing "common.service" at <include "common.utils.merge" (append . "common.service.tpl")>: error calling include: template: mychart/charts/common/templates/_utils.tpl:22:6: executing "common.utils.merge" at <include $tplName $args>: error calling include: template: mychart/charts/common/templates/_service.yaml:9:6: executing "common.service.tpl" at <include "common.metadata" (list $top)>: error calling include: template: mychart/charts/common/templates/_metadata.tpl:34:4: executing "common.metadata" at <include "common.utils.merge" (append . "common.metadata.tpl")>: error calling include: rendering template has a nested reference name: common.utils.merge: unable to excute template`

It would be great if you can point me to an example. Thanks for help.

**Comment by hickeyma** [comment]
To help troubleshoot the error, are you using an example from the the [library docs](https://helm.sh/docs/topics/library_charts/)? If so, can you specify which part is failing?

**Comment by pratapagiri** [comment]
I followed the example from [library docs](https://helm.sh/docs/topics/library_charts/) and able to figure out the "common" is missing. After downloading  common from repo https://kubernetes-charts-incubator.storage.googleapis.com/  it's working fine. Thanks

**Comment by hickeyma** [comment]
Ok, that's great that you got sorted @pratapagiri.
