### ISSUE TITLE
Proposal: Execution process log

### ISSUE THREAD

**Issue by lingsamuel** [helm/helm#8530]
### Motivation
When installing or upgrading charts, users and programs (like kubeapps, a helm web UI) using helm SDK actually know nothing about the process. The only choice seems to be kubectl.

This problem is very annoying especially if the chart contains many hooks and the execution takes a very long time.    
In my situation, I use CI to automatically generate hooks to execute sql, import Consul config. And the final chart may have many dependencies, leads the chart contains 10+ hooks to run. Every time I install/upgrade them, I have to use kubectl to ensure if the install/upgrade process works as intended.    

Programs using helm SDK suffer this more. For example, kubeapps. Kubeapps is a helm web UI, but it knows nothing about the hooks running status when installing/upgrading releases. It stuck at a loading screen until the release success or fails.
Kubeapps users may not have CLI to use, makes it impossible to debug hooks error caused by wrong config or something else. 
What's more, the purpose to use a web UI is avoiding using CLI.

### Proposal
Provides some command line options, such as `--hooks-process`, `--hooks-log`.

The `--hooks-process` only logs the hook's creation and finish status, the `--hooks-log` also prints the job logs, or k8s events if job creation failure.

Example log:
```
===> Executing hooks
===> Pre-install hook sql-init # Format: <hook type> hook <hook metadata.name>
# logs goes here if enabled --hooks-log
===> Pre-install hook consul-init 
Job not running, event: # Display nothing if created normally
Type     Reason   Age                   From               Message
----     ------   ----                  ----               -------
Normal   BackOff  31m (x5923 over 22h)  kubelet, minikube  Back-off pulling image "dduportal/bats:0.4.0"
Warning  Failed   75s (x6056 over 22h)  kubelet, minikube  Error: ImagePullBackOff
===> Pre-install hook other-job
Creation failed, error: jobs.batch "other-job" already exists.
===> Pre-install hook error-job
# logs goes here if enabled --hooks-log
Job failed, retrying x1. # Annotate error retry explicitly
# logs goes here if enabled --hooks-log
Job failed, retrying x2. # Annotate error retry explicitly
===> All hooks completed # Display this if all hooks completed without error
```

Also, the SDK API should provide a stream that contains such messages too (and should be backward compatible).

Potential problem: if helm supports running hooks parallelly further, the log implementation needs to change too.

I am wondering if we need to add options to log other resources (such as Service, Deployment) creation processes? Creating these resources is quick, so I think logs the status of hooks are enough.

**Comment by mattfarina** [comment]
This affects both the library (pkg) and the client (helm binary). I wish there was a standard logging format for Go with levels.
