### ISSUE TITLE
Should helm respect InstallOrder/UninstallOrder when upgrading release?

### ISSUE THREAD

**Issue by liuming-dev** [helm/helm#8534]
When upgrading release, there might be some newly resources to be created, some existed resources to be updated and some existed resources to be deleted.

The present upgrade logic of Helm: 
1. renders the templates in a chart to get the target manifests, and sort the manifests by the order `InstallOrder`
  https://github.com/helm/helm/blob/94438b67221d4af3c9993945a42275be7ffc6baa/pkg/action/action.go#L164
  https://github.com/helm/helm/blob/94438b67221d4af3c9993945a42275be7ffc6baa/pkg/action/upgrade.go#L225
2. iterate every resource in the target manifests
a. if the resource dose not exist in k8s, it is to be created
b. if the resource exist in k8s, it is to be updated
3. diff the current release manifests with the target release manifests to get the resources need to be deleted

https://github.com/helm/helm/blob/94438b67221d4af3c9993945a42275be7ffc6baa/pkg/kube/client.go#L162-L243

All the options follow the order of  the resources in the target release manifests, should the upgrade option respects InstallOrder/UninstallOrder, especially for resources to be created or deleted?

I post this issue because I face an error when upgrading a release, some resources need to be deleted but deleting order is not the same as introduced in https://github.com/helm/helm/blob/master/pkg/releaseutil/kind_sorter.go.

**Comment by bacongobbler** [comment]
In general, yes, Helm should follow the install and uninstall order during an upgrade. This prevents cases where deleting an object will cause an uninstall of another to report an error because it's already been deleted from another resource's cascading delete (e.g. deleting a namespace before deleting a deployment in that namespace).

In the install case, it's important to ensure secrets and configmaps are installed before deployments to ensure the deployment has all of the expected environment variables populated.

What error are you facing?

**Comment by liuming-dev** [comment]
This is the case I met:

**Prerequisites**

- We have two CRD `NginxVhost` and `Registration`, `Registration depends on `NginxVhost`.
- We make a patch to helm v3.2.4 to add this two CRDs to`InstallOrder`/`UninstallOrder` as the follwing:

```go
var InstallOrder KindSortOrder = []string{
	...
        "NginxVhost",
        "Registration",
        ...
}

// UninstallOrder is the order in which manifests should be uninstalled (by Kind).
//
// Those occurring earlier in the list get uninstalled before those occurring later in the list.
var UninstallOrder KindSortOrder = []string{
	...
        "Registration",
        "NginxVhost",
        ...
}
```

- Admin controller will deny the request if deleting `NginxVhost` but related `Registration` exists

**The case**

After upgrade, `NginxVhost`  and `Registration` resources are removed and should be deleted, but the deleting order is not as `UninstallOrder`, so an error returned.

**Comment by liuming-dev** [comment]
remove /Stale
