### ISSUE TITLE
uninstall on windows : helm uninstall v2.8.2

### ISSUE THREAD

**Issue by inarayana** [helm/helm#8536]
Output of `helm version`:
>helm version
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

>helm uninstall v2.8.2
Error: unknown command "uninstall" for "helm"

**Comment by bacongobbler** [comment]
`helm uninstall` is `helm delete` for Helm 2.

```
><> helm help delete

This command takes a release name, and then deletes the release from Kubernetes.
It removes all of the resources associated with the last release of the chart.

Use the '--dry-run' flag to see which releases will be deleted without actually
deleting them.

Usage:
  helm delete [flags] RELEASE_NAME [...]

...
```
