### ISSUE TITLE
Postinstall not waiting for pods in STS to become Ready (Running)

### ISSUE THREAD

**Issue by aditya1808** [helm/helm#8538]
Output of helm version:
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}

Output of kubectl version:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:47:40Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:37:43Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

I am trying to deploy a stateful set with 3 pods and i want to run a postinstall job.

I have used below hooks   in postinstall yaml file
annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded

As soon as statefulset is deployed (i.e none of the pods are in ready. Only 1 pod is in initializing state), postinstall job is already running. Shouldnt it wait for all pods in STS to get to running state before starting the postinstall job?

I tried using --wait argument in helm install, still its the same. Post install is triggered as soon as STS is deployed.
Can someone throw some light on this behaviour please.

**Comment by bacongobbler** [comment]
Can you try to reproduce with a more recent version of Helm? 2.16.9 is the latest Helm 2 release.

It's important to note here that Helm 2 will no longer accept bug fixes after August 13th, so if you identify a bug, please submit a patch soon before the patch window has closed. See [this blog post](https://helm.sh/blog/covid-19-extending-helm-v2-bug-fixes/) for more details.

**Comment by aditya1808** [comment]
@bacongobbler Unfortunately , im restricted to this version for now. But im just looking for answer, if its  a known bug in earlier versions of helm 2. Im not looking for a solution.

**Comment by bacongobbler** [comment]
We are no longer accepting bug fixes for Helm 2. See https://helm.sh/blog/helm-v2-deprecation-timeline/ for more details.
