### ISSUE TITLE
Can’t Upload Index.yaml into VMWare Harbor 2.1.0 Chart Museum

### ISSUE THREAD

**Issue by snyderdb** [helm/helm#8547]
I am using VMWare Harbor 2.1.0. I have a set of child charts that I will push to ChartMuseum. I also have an index.yaml file that was created as a result of running helm repo index. 

I have read that I should upload the index.yaml file to Chart Museum. But, Chart Museum will only support uploading of .tgz files. 

Can someone advise how I can upload the index.yaml to the Chart Museum repo?

Thank you

**Comment by bacongobbler** [comment]
Hi @snyderdb. Given this seems like a support issue with harbor, can you please open a ticket over there? The harbor folks would likely be able to help you more as they’re more familiar with the product.

Thank you.
