### ISSUE TITLE
helm3 install command will execute post-upgrade hook

### ISSUE THREAD

**Issue by zbing0203** [helm/helm#8548]
Is this expected behavior in helm3? at least, in helm2, helm install command will not execute any pre/post-upgrade hook.

Output of `helm version`:
version.BuildInfo{Version:"v3.3.0-rc.1", GitCommit:"5c2dfaad847df2ac8f289d278186d048f446c70c", GitTreeState:"dirty", GoVersion:"go1.14.4"}
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"archive", BuildDate:"2019-11-12T15:46:42Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"archive", BuildDate:"2019-11-12T15:47:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

**Comment by marckhouzam** [comment]
My guess is that this is a duplicate of #8527

**Comment by zbing0203** [comment]
Got it, thank you.
