### ISSUE TITLE
Wrong values used during rendering chart

### ISSUE THREAD

**Issue by eugenekainara** [helm/helm#8553]
Hi!

I'm use umbrella chart with global section to pass same annotations for every dependency(like kubernetes.io/ingress.class) and <chart_dependency_name>.ingress.annotations to set annotations directly if needed. 
Inside of helm template - I'm using merge to merge global vs direct annotations.

The problem is - that when I'm passing both global & direct annotations to dependency 1 and dependency2 - I've see that both annotations blocks are same for both dependencies 1 and 2 - but I'm passing different direct annotations.

See https://github.com/eugenekainara/helm-umbrella-issue for chart examples and command to reproduce locally.

This issue affect both latest versions 3.2.4 and 3.3.0-rc1

**Comment by donggangcj** [comment]
Thanks! I reproduce this issue on in version `version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}`

/assign

**Comment by eugenekainara** [comment]
@bacongobbler can you look at https://github.com/helm/helm/pull/8556 ? I'm still waiting for the fix.

**Comment by eugenekainara** [comment]
Found a workaround to fix annotations merge - https://github.com/eugenekainara/helm-umbrella-issue/commit/307b6fa7fcf4ef68d35b41a0c79443720eb70a32
but I'm have no idea how it works :(
