### ISSUE TITLE
Helm 3.2.4 installed with brew is bad

### ISSUE THREAD

**Issue by tculp** [helm/helm#8555]
Output of `helm version`:

version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}

Output of `kubectl version`: 

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

AWS EKS

The version of helm 3.2.4 (latest) when installed with brew does not work properly. A common error received is:

`Error: template: <redacted> executing "<redacted>/templates/persistentVolumes.yaml" at <(len $volumeDict.accessModes) gt 0>: can't give argument to non-function len $volumeDict.accessModes`

This exact chart works file with the helm version downloaded from the 3.2.4 release page, and the error has been replicated for many people on many different Mac computers.

**Comment by bacongobbler** [comment]
@tculp this is an error from Go 1.14 reporting that your template syntax is wrong. Use `(gt (len $volumeDict.accessModes) 0)` instead.

> The text/template package now correctly reports errors when a parenthesized argument is used as a function. This most commonly shows up in erroneous cases like {{if (eq .F "a") or (eq .F "b")}}. This should be written as {{if or (eq .F "a") (eq .F "b")}}. The erroneous case never worked as expected, and will now be reported with an error can't give argument to non-function.

From https://golang.org/doc/go1.14

See also https://github.com/helm/helm/issues/8311 and #7711.

**Comment by tculp** [comment]
Interesting, thanks
