### ISSUE TITLE
Issue intalling bitnami/magento with Helm on AWS EKS 

### ISSUE THREAD

**Issue by topeawolwo** [helm/helm#8563]
I am trying to install magento on AWS EKS with  helm install eks bitnami/magento

having this issue :

This deployment will be incomplete until you configure Magento with a resolvable
host. To configure Magento with the URL of your service:

1. Get the Magento URL by running:

  NOTE: It may take a few minutes for the LoadBalancer IP to be available.
        Watch the status with: 'kubectl get svc --namespace default -w eks-magento'

  export APP_HOST=$(kubectl get svc --namespace default eks-magento --template "{{ range (index .status.loadBalancer.ingress 0) }}{{ . }}{{ end }}")
  export APP_PASSWORD=$(kubectl get secret --namespace default eks-magento -o jsonpath="{.data.magento-password}" | base64 --decode)
  export APP_DATABASE_PASSWORD=$(kubectl get secret --namespace default eks-mariadb -o jsonpath="{.data.mariadb-password}" | base64 --decode)

2. Complete your Magento deployment by running:

  helm upgrade eks bitnami/magento \
    --set magentoHost=$APP_HOST,magentoPassword=$APP_PASSWORD,mariadb.db.password=$APP_DATABASE_PASSWORD

My environment:  OS : Windows

  
![Capture](https://user-images.githubusercontent.com/31287837/89454217-4c92bb80-d758-11ea-8cf2-37a4d6085b75.PNG)

![image](https://user-images.githubusercontent.com/31287837/89454294-67653000-d758-11ea-8623-f078feff32ea.png)

**Comment by bacongobbler** [comment]
Hi @topeawolwo. As this appears to be an issue with Magento, can you please either follow up with the chart maintainers (bitnami), or the Magento maintainers? I'm afraid there's nothing on our end we can do here to help fix your issue.

Thank you.
