### ISSUE TITLE
Memory leak while using go helm client

### ISSUE THREAD

**Issue by polskikiel** [helm/helm#8564]
I have a simple [application](https://github.com/polskikiel/hb-test) that only installs a simple helm chart and deletes it in the loop. It contains only the helm client [implementation](https://github.com/polskikiel/hb-test/blob/master/internal/helm/client.go). I noticed that memory usage on this application is increasing from ~20Mi on start to ~100Mi and then it stays at this level. I tested it deployed on the k8s cluster with `secrets` driver to store releases' history.

In the above client, I even set the `maxHistory` to `1` to be sure that history is not consuming memory, but it still grows. The memory usage chart looks as follows:

<img width="1593" alt="Screenshot 2020-08-03 at 00 14 20" src="https://user-images.githubusercontent.com/21159554/89519885-5c081800-d7dd-11ea-8632-4cb9158f1483.png">

Using pprof it looks as follows: 

![profile001](https://user-images.githubusercontent.com/21159554/89519831-4561c100-d7dd-11ea-95d1-4e72aaebc7f7.png)
**5min** later:
![profile002](https://user-images.githubusercontent.com/21159554/89519827-4397fd80-d7dd-11ea-9bba-cd3d204dca8c.png)
**20min** later:
![profile003](https://user-images.githubusercontent.com/21159554/89519821-40047680-d7dd-11ea-8b6b-f23a3275d5a1.png)

It looks like reflect.New percentage of memory usage is growing but I cannot find a root cause.

Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T14:51:23Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.1", GitCommit:"688c6543aa4b285355723f100302d80431e411cc", GitTreeState:"clean", BuildDate:"2020-07-21T02:37:26Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE

**Comment by mattfarina** [comment]
This looks like it's happening within protobuf handling. Helm doesn't directly deal with this. Instead, it's likely from an import of a Kubernetes package used for interactions with Kubernetes. I suspect something is happening in there.
