### ISSUE TITLE
Accessing values of the subchart with dash in the name

### ISSUE THREAD

**Issue by agniveshadhikari** [helm/helm#8565]
Continuation of this since that issue is years old at this point. https://github.com/helm/helm/issues/2192

What is the thinking on this?

**Comment by bacongobbler** [comment]
please post comments in #2192.

I'm not sure what more there is to add here. https://github.com/helm/helm/issues/2192#issuecomment-293739257 explains a workaround, and there is documentation in https://helm.sh/docs/ around this practice.
