### ISSUE TITLE
Best practice: don't override imagePullPolicy

### ISSUE THREAD

**Issue by bgehman** [helm/helm#8567]
It is a [Kubernetes Best Practice](https://kubernetes.io/docs/concepts/configuration/overview/#container-images) to not override defaults, including `imagePullPolicy`.  Using `helm create ...` to create a sample chart, the generated sample is explicitly setting the `imagePullPolicy`, making it _appear_ as if it is a Best Practice to do such a thing.

I would like to note that `imagePullPolicy` has **a dynamic default** in Kubernetes -- the default is different depending on the docker image tag being used (tag omitted, or set to `:latest` the default is `Always`, otherwise it defaults to `IfNotPresent`).  

The sample chart (from "helm create ...") should not explicitly override the imagePullPolicy, but it should _allow_ someone to override the default Kubernetes behavior.

I would suggest the `values.yaml` to have something like this (see where I commented out the `pullPolicy`):
```(yaml)
image:
  repository: nginx
  # pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
```

and the `deployment.yaml` to have:
```
{{ if .Values.image.pullPolicy }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
{{ end }}
```

With these changes, the default/sample helm chart is more closely aligned with Kubernetes' inbuilt defaults and best practices:

> Don't specify default values unnecessarily: simple, minimal configuration will make errors less likely.

---------

Output of `helm version`: same behavior in helm2 and helm3

Output of `kubectl version`: na

Cloud Provider/Platform (AKS, GKE, Minikube etc.): na

**Comment by bacongobbler** [comment]
PRs welcome.

**Comment by bmarwell** [comment]
I'm still interested in this.

**Comment by bmarwell** [comment]
@bgehman any news?
