### ISSUE TITLE
Hashicorp Vault Support

### ISSUE THREAD

**Issue by srirammageswarank** [helm/helm#8568]
Hi ,

Is there a plan to support Hashicorp Vault Support out of the box with helm ? 

Thanks

**Comment by cr4igo** [comment]
There is Helm secrets Plugin. Using mozilla/sops under the hood.

Sops supports hashicorp vault, but also other kms or e.g. PGP / AGE as like
a fallback mechanism. I would personally recommend that way to go to you.
If you use two KMS at the same time, e.g. hashicorp can go down and you
still are able to operate. If you rely only on one mechanism (kms) than
your whole secrets could be lost.

Personally I will use helmfile, for also fully supporting binaries to get
en-/decrypted in a well working way.
If you have only secrets.yaml/json you can stick with native Helm secrets.

Also to remark is that getting sops and so on work on Windows is currently
a mess. As a solution I just recommend that you use a docker container with
Unix for all those tasks or local developers Unix/mac.

Besteht regards and hopefully I could help you,
Markus


Sriram Mageswaran <notifications@github.com> schrieb am Do., 6. Aug. 2020,
23:48:

**Comment by mattfarina** [comment]
@srirammageswarank In what way would you want Helm to support Vault? Can you provide more details?

**Comment by srirammageswarank** [comment]
Hi @mattfarina ,

More like a lookup Integration. 

{{ (lookup_hvault "VAULT_ADDR" "VAULT_SECRET_PATH" "VAULT_TOKEN") }}

We can start with VAULT_TOKEN and later try integration with all the other Authentication Engine.

**Comment by srirammageswarank** [comment]
Hi @mattfarina / @cr4igo ,

Do you think having an product specific integration in helm would be good ? I have had requirements in the past to use helm with Vault to create secrets and configmaps with secrets and it has been painful[I am still going through SOPS].

The Hashicorp vault sidecar pattern solves it for pods but not for static objects.

Thanks
Sriram Mageswaran.

**Comment by mattfarina** [comment]
@srirammageswarank I don't expect we will put a product specific capability right into Helm. If we do it for one we have to do it for all or have criteria on who is in and out. But, Helm does have some mechanisms to extend it. If we understand the issue there may be a case for an extension point that many tools can use.
