### ISSUE TITLE
[Question] Documentation old vs new ?

### ISSUE THREAD

**Issue by emirot** [helm/helm#8569]
Hi There,

What is the difference between https://helm.readthedocs.io/en/latest/ and https://helm.sh/docs/
The  first one looks to be deprecated but could you please confirm and or mark it as deprecated.
Only in I can find a reference of the heritage label here: https://helm.readthedocs.io/en/latest/using_labels/ is it deprecated or is this still relevant ? Knowing that I'm now using helm3.

Thanks

**Comment by bacongobbler** [comment]
That read the docs link references helm-classic, or Helm v1. Use the helm.sh link for all documentation regarding Helm 3.

Thanks!
