### ISSUE TITLE
RFE: Expanded --create-namespace Functionality

### ISSUE THREAD

**Issue by thecrazyrussian** [helm/helm#8570]
Currently
With helm version 3.2.x the `--create-namespace` flag was added to the install command, flagging whether to generate the release namespace ahead of the HelmChart installation that requires it.

This supports the vanilla Kubernetes use case where namespaces are not flagged using annotations and labels with special functionality.

The Issue
This does not support use cases where namespace labels or annotations are needed for admission control, management, or deployment permissions.

At least OpenShift and Rancher run into this issue due to their use of namespace annotations.
OpenShift: https://github.com/helm/helm/issues/8250
Rancher: Here 

Possible Solution
Convert --create-namespace to optionally support labels and annotations, reverting to boolean functionality when no options are present.

Something like 
`helm install release mikhail/app --create-namespace "annotations:projected:1,something:else;labels:something:new"`
or
`helm install release mikhail/app --create-namespace "annotations=projected:1" --create-namespace "annotations=something:else:1" --create-namespace "labels=something:new"`

Happy to write/pr if approved.

**Comment by marckhouzam** [comment]
Originally, helm v3 (unlike v2) did not support the `--create-namespace` flag.  The idea was that creating a namespace was not Helm's responsibility but should instead be done by another tool.  For example `kubectl` won't automatically create a namespace for you, you have to explicitly create it.

More details starting here: https://github.com/helm/helm/issues/5753#issuecomment-502163585

For helm 3.2 `--create-namespace` was added as a compromise where a namespace would not be created automatically but only if that creation was explicitly requested by the user.

One of the reasons Helm wanted to stay away from creating namespaces was that people always wanted to add more features to the namespace creation 😉.  As creating a namespace is not Helm's "core business", would it be possible in your case to use another tool (maybe `kubectl`) to create your namespace first with the labels you need?

**Comment by mattfarina** [comment]
@thecrazyrussian Can you share your use case adding this to Helm? What's the situation and environment (e.g., it's happening in CI testing)?
