### ISSUE TITLE
Support for Mosaic browser was removed from Emacs source - helm should follow

### ISSUE THREAD

**Issue by cjk** [helm/helm#8575]
Emacs removed [Mosaic-support](https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=3e39aa6cfa6822b535d597b3e59abfea38610a48) from it's sources, which is / will be causing errors in helm, specifically `helm-net`, which has many references to Mosaic like this:

```
/home/cjk/.emacs.d/straight/build/helm/helm-net.el
278:    (,browse-url-mosaic-program . browse-url-mosaic)
```

These should be cleaned up ASAP to stay compatible with future releases of Emacs.

**Comment by cjk** [comment]
OMG... I posted this to the wrong repo, I'm very sorry for the noise!

**Comment by Idrek** [comment]
@cjk Which repo did you post it to? I would like to follow it as i have found a similar problem in my system recently.

**Comment by Idrek** [comment]
Thanks anyway.
