### ISSUE TITLE
Add merge function

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#8578]
The [`merge`](https://github.com/helm/charts/blob/master/incubator/common/templates/_util.tpl) function from the common chart is essential when creating library charts. It lets you merge two templates together. The Helm docs even include it in the library chart examples.

This function could be brought into Helm itself so that it doesn't need to be copy and pasted from library chart to library chart.

**Comment by hickeyma** [comment]
I think this is a good idea Matt. If you haven't started this, I can push a PR to include it?

**Comment by donggangcj** [comment]
+1! and there is a bug https://github.com/helm/helm/issues/8553 related `merge`.

**Comment by mattfarina** [comment]
@donggangcj this is talking about a different merge function.

**Comment by mattfarina** [comment]
@hickeyma I've not started it and won't have time for a bit.

**Comment by hickeyma** [comment]
Ok @mattfarina, would you like me to start it then?

**Comment by mattfarina** [comment]
@hickeyma sure
