### ISSUE TITLE
Option 1: Install with Helm via helm template wrong option

### ISSUE THREAD

**Issue by zioalex** [helm/helm#8583]
I was just trying to install istio with the info provided [here](https://istio.io/v1.3/docs/setup/install/helm/#option-1-install-with-helm-via-helm-template)

I tried to run the help template command but I get the follow error:
`
helm template istio.io/istio --name istio-init --namespace istio-system
Error: unknown flag: --name
`
It seems that the --name option is not anymore available. Therefore what would be an equivalent option, if available?

 
Output of `helm version`:
`version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}`

Output of `kubectl version`:
`
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-49202c", GitCommit:"49202cb0a6d5e481319ba21f0b068f112a29a4e5", GitTreeState:"clean", BuildDate:"2020-05-23T20:16:40Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS

**Comment by bridgetkromhout** [comment]
The Istio docs you linked are for Helm v2 (without and with Tiller). Helm v2 uses this syntax: `helm template [flags] CHART`
In Helm v3, the syntax looks like this: `helm template [NAME] [CHART] [flags]` - see https://helm.sh/docs/helm/helm_template/#helm-template for more detail.

**Comment by bridgetkromhout** [comment]
Hi, @zioalex - I hope those docs I linked helped you solve this. Please let us know if the problem persists.
