### ISSUE TITLE
PVC claim for GKE helm chart

### ISSUE THREAD

**Issue by suvsap** [helm/helm#8584]
Pvc.yaml:- https://gist.github.com/suvsap/3ec0ab8f0cd04baa8d043d5eb77bec4b

values.yaml: https://gist.github.com/suvsap/1eb5b79cb4c7fc3d520da7bbd64b2851
deployment.yaml:- https://gist.github.com/suvsap/d1d0305b06dce5bf00076c3543ff070b

I want to configure PVC claim for GKE in a helm chart. I am not sure if the above configuration is correct. I will need some help on this.

**Comment by bacongobbler** [comment]
Hi @suvsap. I would suggest reaching out to the #helm-users slack channel for general support questions on how to write a chart. Alternatively, I'd refer to Kubernetes' documentation on how to configure a PVC with a deployment as described here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/

Hope this helps.
