### ISSUE TITLE
Issues while linting or templating with IF statement when Value is NIL

### ISSUE THREAD

**Issue by danmx** [helm/helm#8585]
I just tried to run `helm template` and `helm lint` with my charts and I ran into an issue with `_helpers.tpl` templates generate by older versions of helm.

It failed at standard:

`name: {{ include "xxx.fullname" . }}`

when `fullnameOverride` was not set (`nil`) or am empty string (`""`).

```console
helm lint internal/xxx --debug
==> Linting internal/xxx
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: template: xxx/templates/kmskey.yaml:6:11: executing "xxx/templates/object.yaml" at <include "xxx.fullname" .>: error calling include: template: xxx/templates/_helpers.tpl:15:14: executing "xxx.fullname" at <.Values.fullnameOverride>: nil pointer evaluating interface {}.fullnameOverride

Error: 1 chart(s) linted, 1 chart(s) failed
helm.go:94: [debug] 1 chart(s) linted, 1 chart(s) failed
main.newLintCmd.func1
        /private/tmp/helm-20200811-17131-1m461y0/cmd/helm/lint.go:113
github.com/spf13/cobra.(*Command).execute
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
        /private/tmp/helm-20200811-17131-1m461y0/cmd/helm/helm.go:93
runtime.main
        /usr/local/Cellar/go/1.14.6/libexec/src/runtime/proc.go:203
runtime.goexit
        /usr/local/Cellar/go/1.14.6/libexec/src/runtime/asm_amd64.s:1373
```

Helm documentation still states that `IF/ELSE` will fail when value is `nil`.

Output of `helm version`:

`version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.6"}`

**Comment by bacongobbler** [comment]
can you post the failing template here?

From what I can tell, your template is trying to evaluate a nulled value. This is normal behaviour with Go's text/template package: if a null value is being evaluated, it will return an error.

See more here: https://golang.org/pkg/text/template/

If it is expected that `.Values` can be null, what you probably want to add is a check before consuming the value. A common solution is to use the `with/else` function, like the following:

```
{{ with .Values}}
  {{ .fullnameOverride }}
{{ else }}
  {{ $myvar }}
{{ end }}
```

As defined in text/template's documentation:

> If the value of the pipeline is empty, dot is unaffected and T0 is executed; otherwise, dot is set to the value of the pipeline and T1 is executed.

Hope this helps.

**Comment by danmx** [comment]
Standard snippet from the helpers:
```
{{- define "xxx.fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
{{- end -}}
```

Usage:

```yaml
metadata:
  name: {{ printf "%s-%s" (include "xxx.fullname" .) $extraName | trunc 63 | trimSuffix "-" }}
```

**Comment by danmx** [comment]
ok, the problem is `{{- range $issuer := .Values.issuers }}`. This breaks all `define` helpers

**Comment by danmx** [comment]
Solution: https://helm.sh/docs/chart_template_guide/variables/

```yaml
  labels:
    # Many helm templates would use `.` below, but that will not work,
    # however `$` will work here
    app.kubernetes.io/name: {{ template "fullname" $ }}
```
