### ISSUE TITLE
Issues while linting templates empty

### ISSUE THREAD

**Issue by midestefanis** [helm/helm#8586]
My linting pipeline give me this outputs:
==> Linting ./logs/
```
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/configmap.yaml: object name does not conform to Kubernetes naming requirements: ""
[ERROR] templates/cronjob.yaml: object name does not conform to Kubernetes naming requirements: ""
[ERROR] templates/secrets.yaml: object name does not conform to Kubernetes naming requirements: ""
[ERROR] templates/service.yaml: object name does not conform to Kubernetes naming requirements: ""
```

I think that is because my templates are emptys. They activate and receive values from outside.

Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}
```

Output of `kubectl version`:
```                
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.8-gke.17", GitCommit:"cd7ca396c79d2e8f3fdb06c6865549770091d431", GitTreeState:"clean", BuildDate:"2020-07-20T22:12:03Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE

**Comment by bacongobbler** [comment]
If your chart expects values to be present at the time the chart is being rendered, you can pass values to `helm lint` via `--values`. More information can be found in the documentation.

https://helm.sh/docs/helm/helm_lint/

Does that help?

**Comment by midestefanis** [comment]
I don't know how to explain it clearly, anyway I think you will understand.

I solved it by putting the division: `---` inside the IF.

The problem was with the empty templates. This is because I have a POD with 3 containers (three microservices). The values, cronjob and configuration of each microservice come from 3 different projects and pipelines that end up in the same helm chart as a base.

**Comment by bacongobbler** [comment]
glad you found a solution. Can we consider this closed now? It's unclear to me what assistance you're asking for here at this point.
