### ISSUE TITLE
helm v3 does not remove serviceAccountName during upgrade if removed in template

### ISSUE THREAD

**Issue by m1o1** [helm/helm#8589]
If I make a Deployment that has a serviceAccountName in the spec in its template, then later remove that field and do an upgrade, helm does not remove it. The helm install (upgrade) fails because the pod tries to mount a secret that does not exist (the service account token).

Script to reproduce:
```bash
#!/bin/bash

set -euxo pipefail

# set up charts with apiVersion 1
helm2 create testbug
cat <<EOF > ./testbug/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: testbug-service-account
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "testbug.labels" . | indent 4 }}
EOF
sed -i -e '/\s*containers/i \ \ \ \ \ \ serviceAccountName: testbug-service-account' ./testbug/templates/deployment.yaml

# now use helm v3 to install it
cd ./testbug
helm3 upgrade --install testbug "." \
    -n default \
    -f ./values.yaml \
    --wait

sleep 10

# now remove the serviceaccount stuff from the chart
rm ./testbug/templates/serviceaccount.yaml
sed -i -e '/serviceAccountName/d' ./templates/deployment.yaml
# add a label to pod spec so it gets updated
sed -i -e '/      labels/a \ \ \ \ \ \ \ \ mylabel: hi' ./templates/deployment.yaml

# try to upgrade again
helm3 upgrade --install testbug "." \
    -n default \
    -f ./values.yaml \
    --wait
```

Output of `helm version`:
```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.7", GitCommit:"b4455102ef392bf7d594ef96b97a4caa79d729d9", GitTreeState:"clean", BuildDate:"2020-06-17T11:39:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.7", GitCommit:"b4455102ef392bf7d594ef96b97a4caa79d729d9", GitTreeState:"clean", BuildDate:"2020-06-17T11:32:20Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS and minikube

**Comment by m1o1** [comment]
Nevermind - I had to use `--reset-values`

**Comment by m1o1** [comment]
Nevermind I thought that fixed it but it doesn't. Still an issue with `--reset-values` too.

**Comment by bacongobbler** [comment]
I was unable to reproduce the issue. Here's how I tested.

```
$ helm create testbug
$ cat <<EOF > ./testbug/templates/serviceaccount.yaml
> apiVersion: v1
> kind: ServiceAccount
> metadata:
>   name: testbug-service-account
>   namespace: {{ .Release.Namespace }}
>   labels:
> {{ include "testbug.labels" . | indent 4 }}
> EOF
$ sed -i -e '/\s*containers/i \ \ \ \ \ \ serviceAccountName: testbug-service-account' ./testbug/templates/deployment.yaml
$ helm install testbug ./testbug
$ rm ./testbug/templates/serviceaccount.yaml
$ sed -i -e '/serviceAccountName/d' ./testbug/templates/deployment.yaml
$ helm upgrade testbug ./testbug/
$ k get deploy
NAME      READY   UP-TO-DATE   AVAILABLE   AGE
testbug   1/1     1            1           80s
$ k get sa
NAME      SECRETS   AGE
default   1         4m53s
```

Notice that the service account no longer exists, the upgrade succeeded, and the service account name was removed from the deployment.

I changed a few things in your script, as they weren't necessary for the test environment:

1. I used Helm 3 to create the chart (the difference between which `apiVersion` is used is irrelevant here)
1. I did not add `mylabel: hi` to the deployment, as the removal of the service account name triggered a change in the template
1. `sleep 10` was not necessary for the test case
1. `--wait` and `--install` were not used as they were irrelevant to the test case

**Comment by bacongobbler** [comment]
ping.

**Comment by m1o1** [comment]
Sorry for the wait - we actually ran into this again yesterday, this time without using helm v2 at all. I'll change my script up to try to make it reproducible for you.

**Comment by m1o1** [comment]
Strange. If I do not add the label:
* the Deployment is never updated (its "generation" is still 1 and the serviceAccountName is still there in the template).
* the helm upgrade succeeds, but only because it did not trigger a rolling upgrade

If I do add the label, it does trigger the rolling upgrade and fails.

The `--wait` is not needed but makes it more obvious that the 2nd upgrade failed, since it otherwise finishes the deployment seemingly successfully, but meanwhile a pod is stuck in ContainerCreating since it cannot mount the service account token (since the service account does not exist).

Here are the exact scripts I'm using to test (just fixed a path error in the script above, and removed some things that were not used):
bug.sh:
```
#!/bin/bash

set -euxo pipefail

# set up charts with apiVersion 1
helm3 create testbug
cat <<EOF > ./testbug/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: testbug-service-account
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "testbug.labels" . | indent 4 }}
EOF
sed -i -e '/\s*containers/i \ \ \ \ \ \ serviceAccountName: testbug-service-account' ./testbug/templates/deployment.yaml

# now use helm v3 to install it
cd ./testbug
helm3 upgrade --install testbug "." \
    -n default \
    -f ./values.yaml

sleep 10

# now remove the serviceaccount stuff from the chart
rm ./templates/serviceaccount.yaml
sed -i -e '/serviceAccountName/d' ./templates/deployment.yaml
# add a label to pod spec so it gets updated
sed -i -e '/      labels/a \ \ \ \ \ \ \ \ mylabel: hi' ./templates/deployment.yaml

# try to upgrade again
helm3 upgrade --install testbug "." \
    -n default \
    -f ./values.yaml \
    --wait
```

And to clean up everything (to try testing this again):
```
#!/bin/bash

if [ -d "./testbug" ]; then
    rm -rf ./testbug
fi
helm uninstall testbug
```

**Comment by m1o1** [comment]
@bacongobbler have you had a chance to run my script? Let me know if it doesn't reproduce it  for you. It does for me consistently on my end
