### ISSUE TITLE
Misleading error "ref may only contain a single colon character (:)"

### ISSUE THREAD

**Issue by tacf** [helm/helm#8591]
Context:
- Storing Charts on Azure Container Registry (HELM_EXPERIMENTAL_OCI=1 enabled)

Simple numeric tags with 5 digits throws "ref may only contain a single colon character (:)"

`$ helm chart save . chart:99999` throws the above error

Any of the following does not
`$ helm chart save . chart:9999`
`$ helm chart save . chart:99999.1`
`$ helm chart save . chart:99999m`

Output of `helm version`:
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}

Not sure if this an actual bug, but the error message is not clear at all.

**Comment by bacongobbler** [comment]
`helm chart save` is going to be refactored, and the fourth argument will be removed which will resolve this issue. See https://github.com/helm/community/pull/136 for more information.
