### ISSUE TITLE
Please make a relase with fix for kubernetes#91615 (CRD hang)

### ISSUE THREAD

**Issue by james-w** [helm/helm#8594]
Hi,

cert-manager users are having lots of problems with the 0.16 release due to 

https://github.com/kubernetes/kubernetes/issues/91615

(https://cert-manager.io/docs/installation/upgrading/upgrading-0.15-0.16/)

It would be great if you could make a point release using kubectl 1.18.8 to fix this problem now.

Waiting to release with kubectl 1.19 will increase the number of users who have a very tricky
bug affect them in the time before that release.

Thanks,

James

**Comment by james-w** [comment]
Thanks. Do you have an ETA for 3.3.1?

**Comment by bridgetkromhout** [comment]
Hi, @james-w - as you may have seen, we released 3.3.1; hopefully that helps! https://github.com/helm/helm/releases/tag/v3.3.1

**Comment by james-w** [comment]
That's great, thanks.
