### ISSUE TITLE
Helm 3 doesn't accept null values for ports

### ISSUE THREAD

**Issue by cetiberiojr** [helm/helm#8598]
Hi all,

Before the upgrade to Helm 3 (Helm 2.x), we have some values at our umbrella chart like that:

```
chartOne:
  port: ""
chartTwo:
  port: ""
```

and the Services where receiving those values and we were ok, as when we pass nothing the ports are generated randomly.

Now, with Helm 3 validations, I'm getting the issue:

`Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Service.spec.ports[0]): missing required field "port" in io.k8s.api.core.v1.ServicePort`

How can I explain to Helm 3 to generate random values for those or I need to use a new function?

**Comment by bacongobbler** [comment]
As the error suggests, the manifest being provided to Kubernetes is failing validation. As per the Kubernetes spec, the `port` field is considered mandatory.

You may use `randAlphaNum` or some other value to generate a random value. But You need to provide a kubernetes deployment with a port number.

See https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#service-v1-core for more details.

**Comment by cetiberiojr** [comment]
Yes, I know that (that kube needs values for this port and so on).

My question remains without answers...

Why using Helm 2 I didn't get any error (meaning I could install the chart without issues) and now this is being throw?

Should be something on Helm 3, right?

**Comment by bacongobbler** [comment]
Helm 3 now validates your chart against the Kubernetes API. Helm 2 would not validate, which would cause undetermined results. So it is correct for Helm 3 to perform this check and ensure your manifest is correct against the Kubernetes API.
