### ISSUE TITLE
Delete running job on helm upgrade

### ISSUE THREAD

**Issue by MichaelMedvedskiy** [helm/helm#8599]
Output of `helm version`:  version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", , GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

I have a cronjob in my chart. It can fail, but the pod will not fail - it will persist in Running state indefinitely. (the concurrencyPolicy is Forbid, and must stay that way). I cannot get the name of the job in runtime. I want to kill the indefinitely running  job's pod on `helm upgrade`

Currently, I'm using keys --install --recreate-pods --force --atomic --reset-values, and the job still persists.

If I haven't supplied sufficient info, please call me out on it, I will be glad to plenish.

Thank you for your attention.

**Comment by bacongobbler** [comment]
hi @MichaelMedvedskiy. Please provide a test case to demonstrate this behaviour. Thanks.

**Comment by MichaelMedvedskiy** [comment]
> hi @MichaelMedvedskiy. Please provide a test case to demonstrate this behaviour. Thanks.

hey. Do you mean a cronjob example?
say, here:

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: name
  labels:
    target-app: name
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 99999
  jobTemplate:
    metadata:
      labels:
        target-app: name
    spec:
      template:
        metadata:
          labels:
            target-app: name
        spec:
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: secrets-name
          containers:
            - name: "app"
              image: app-image
              imagePullPolicy: Always
              resources:
                limits:
                  cpu: "100m"
                  memory: "512Mi"
                requests:
                  cpu: "50m"
                  memory: "256Mi"
              envFrom:
                - secretRef:
                    name: secret-variables
              command:
                - java
                - -jar
                - i-will-run-infinitelly.jar

when it's run I do
`helm --kubeconfig SOME_CONFIG upgrade --install --recreate-pods --force name ./path/to/file.tgz --atomic --reset-values`

**Comment by bacongobbler** [comment]
I need a way to run this locally. In your example, you reference a file `./path/to/file.tgz` that I do not have access to, so I cannot test your issue.

Generally we ask users to start with the output from `helm create test-8599`, add some templates to demonstrate the issue, upload the chart as a zip file to your ticket and document the steps necessary to test with that chart with a script.

Thanks.

**Comment by MichaelMedvedskiy** [comment]
all of this is run on a remote server I only have access through Gitlab pipeline. I do not think I can provide such extensive information. Could I ask you for a generic advice on killing a running job with helm upgrade?

**Comment by bacongobbler** [comment]
`kubectl delete`? If a job cannot be removed with that command, I'm not sure `helm upgrade` will fare any better.

**Comment by MichaelMedvedskiy** [comment]
> `kubectl delete`? If a job cannot be removed with that command, I'm not sure `helm upgrade` will fare any better.

that would require me to have the name of the job, which is generated, so that option got canceled, when was proposed. But still thank you. If there is any more possible solutions, please do propose. I will consult my teamlead over the statements requested by you, and then will reply to your message, where they were requested, will this be acceptable?

**Comment by bacongobbler** [comment]
ping. Following up here to see if there are any additional questions, or is this can be closed.

**Comment by MichaelMedvedskiy** [comment]
> ping. Following up here to see if there are any additional questions, or is this can be closed.

I guess, but I never got a comprehensive answer tbh. Could I do anything to help you help me? The situation is as simple as: I have a cronjob. It runs a job. While the job is running, I do `helm upgrade`. I want the running job down on helm upgrade.

**Comment by bacongobbler** [comment]
Have you tried removing the template from the chart and calling `helm upgrade`? When a template is removed from a chart, Helm marks that resource for deletion.

I would suggest referring back to the documentation for more ideas.

**Comment by MichaelMedvedskiy** [comment]
> Have you tried removing the template from the chart and calling `helm upgrade`? When a template is removed from a chart, Helm marks that resource for deletion.
> 
> I would suggest referring back to the documentation for more ideas.

Thank you for the advice, I have nothing to say at this point, and if you need to close this issue, please do. But if it is possible, I would have it opened until I have more information over the specific requirements for the command expression for removing the running job.
