### ISSUE TITLE
Use helm cli to delete the release. How can I watch this operation to facilitate my business processing

### ISSUE THREAD

**Issue by Cweiping** [helm/helm#8601]
For example, I use `helm delete` to delete the application, and I expect to monitor the user's modification. Does helm support this feature?

At present, the operation I know is to monitor helm's comfigmap or sectorsFor example, I use helm delete to delete the application, and I expect to monitor the user's modification. Does helm support this feature?

At present, the operation I know is to monitor helm's ConfigMap or Secrets.

Output of `helm version`:
```
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"2cc6e0a70a", GitTreeState:"clean", BuildDate:"2020-03-26T06:42:04Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dc73548d265", GitTreeState:"clean", BuildDate:"2020-07-28T08:17:21Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by mattfarina** [comment]
@Cweiping What are you looking to monitor? I am not sure what you want to see.

**Comment by Cweiping** [comment]
@mattfarina Listen to the delete operation of Release, and complete the additional resource cleaning operation after executing `helm delete`

**Comment by asitaru** [comment]
This is a feature that we would also need, for pipelines.

**Comment by bacongobbler** [comment]
is this a duplicate request for #2378, or something else? I am having a hard time determining what it is you'd like to monitor, @Cweiping.

Could you please explain your case more clearly, or if this is indeed a duplicate request of #2378, can we close this in favour of that ticket?

> and complete the additional resource cleaning operation after executing `helm delete`

Now I'm really confused. You need the release object to determine what needs to be deleted. You cannot delete the release object then attempt to delete the resources it was bound to. If there's a timeout or data loss between the time the release object has been deleted and the time it takes to delete the resources it was tied to, that could lead to your cluster entering an unknown state.

Perhaps a more concrete explanation of the user case you are trying to solve would be more helpful. That way we can determine the best path forward here

Thanks.

**Comment by bacongobbler** [comment]
ping.
