### ISSUE TITLE
Cannot install dependent packages for helm.sh/helm/v3/pg/action and cli

### ISSUE THREAD

**Issue by beckyjmcdabq** [helm/helm#8605]
I have a simple "helm_list.go" file in ~/golang

This is the example given to us helm.sh/helm/v3/pkg/action and helm.sh/helm/v3/pkg/cli to use the helm client to do a "NewList" (equivalent of helm ls) in a go program.

From ~/golang, I run:
go get -d ./...

and it proceeds to pull down several packages but then it reaches a point where it begins complaining about packages in "kustomize".  For example:

package sigs.k8s.io/kustomize/pkg/ifc: cannot find package "sigs.k8s.io/kustomize/pkg/ifc" in any of:
	/usr/local/go/src/sigs.k8s.io/kustomize/pkg/ifc (from $GOROOT)
	/ascldap/users/bmcderm/golang/src/sigs.k8s.io/kustomize/pkg/ifc (from $GOPATH)
package sigs.k8s.io/kustomize/pkg/types: cannot find package "sigs.k8s.io/kustomize/pkg/types" in any of:
	/usr/local/go/src/sigs.k8s.io/kustomize/pkg/types (from $GOROOT)

and there are many more.

If I go into ~/golang/src/sigs.k8s.io/kustomize and do an "ls", there is NO "pkg" directory.

How can I download the "kustomize" dependencies so I can get the example code to run?

Output of `helm version`:  
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):   GKE (Rancher)

**Comment by mattfarina** [comment]
@beckyjmcdabq Go deals with dependencies a little differently depending on whether the project is in your GOPATH or not and depending on which version of Go you are using. What version of Go are you using? Have you set any environment variables to control dependencies? Have you previously downloaded kustomize into your GOPATH?

I would suggest moving your custom code out of your GOPATH, using one of the last two minor versions of Go, and trying again... as a first step.
