### ISSUE TITLE
Helm Fails silently when `/.config` isn't owned appropriately

### ISSUE THREAD

**Issue by addyess** [helm/helm#8606]
Output of `helm version`:  version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T14:19:25Z", GoVersion:"go1.13.13", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  ???

-------------------------------
```bash
helm        # produces no output
echo $?   # produces 1
```
At least the rc status was 1.  

It turns out the issue is that my ~/.config/ directory was owned by root:root rather than myself.  

As a work around:

```bash
sudo chown -R $USER:$USER ~/.config/
helm  # produces help
```

**Comment by mattfarina** [comment]
I'm going to mark this as a bug. If there is a permission issue the Helm client can provide a better error message.

**Comment by yxxhero** [comment]
@addyess You can use: 
```shell
export HELM_DEBUG=1
```
It will show the error meessage.

**Comment by addyess** [comment]
try setting permissions on /home/chris/.config to 700 (only the owner can read/write)

this works
```
drwx------ 3 addyess addyess 4096 Aug 13 19:29 .config
```

this fails
```
drwx------ 3 root root 4096 Aug 13 19:29 .config
```

**Comment by liuming-dev** [comment]
I also cann't repoduce this case

```bash
# apple @ liuming-dev in ~/.kube [16:52:14] C:1
$ ll
total 144
-rwx------    1 daemon  daemon    49K  9  2 15:09 config

# apple @ liuming-dev in ~/.kube [16:52:37]
$ ll /usr/local/bin/helm
lrwxr-xr-x  1 apple  admin    29B  9  2 09:56 /usr/local/bin/helm -> ../Cellar/helm/3.3.1/bin/helm

# apple @ liuming-dev in ~/.kube [16:52:58]
$ helm list --kubeconfig ./config
Error: Kubernetes cluster unreachable: error loading config file "./config": open ./config: permission denied
```

**Comment by yxxhero** [comment]
> I also cann't repoduce this case
> 
> ```shell
> # apple @ liuming-dev in ~/.kube [16:52:14] C:1
> $ ll
> total 144
> -rwx------    1 daemon  daemon    49K  9  2 15:09 config
> 
> # apple @ liuming-dev in ~/.kube [16:52:37]
> $ ll /usr/local/bin/helm
> lrwxr-xr-x  1 apple  admin    29B  9  2 09:56 /usr/local/bin/helm -> ../Cellar/helm/3.3.1/bin/helm
> 
> # apple @ liuming-dev in ~/.kube [16:52:58]
> $ helm list --kubeconfig ./config
> Error: Kubernetes cluster unreachable: error loading config file "./config": open ./config: permission denied
> ```
```shell
Your file is named config, it should be named .config
```
