### ISSUE TITLE
Documentation / New package built for python to use helm

### ISSUE THREAD

**Issue by zbrookle** [helm/helm#8609]
Hello!

I just finished creating a package that makes it very easy to use Helm using python objects which get translated to a Helm chart. I was wondering if it would be possible for my package to be listed under Additional Tools so that it's easy for others to find.

For reference the package is called [avionix](https://github.com/zbrookle/avionix) and you can also find the documentation [here](https://avionix.readthedocs.io/en/latest/)

**Comment by bacongobbler** [comment]
Certainly. PRs are welcome over at https://github.com/helm/helm-www
