### ISSUE TITLE
Request: Add Slack app to repo

### ISSUE THREAD

**Issue by david-kirby** [helm/helm#8610]
I was wondering if the Slack app could be added to this project so folks can subscribe to issue/release/comment activity via the Github app in their own Slack workspaces?

Relevant links:
https://slack.github.com/
https://github.com/apps/slack/installations/new

**Comment by mattfarina** [comment]
Thanks for the request. I've added it to the Helm meeting agenda so we can discuss.

**Comment by bacongobbler** [comment]
> via the Github app in their own Slack workspaces?

As I understand it, the Slack app needs to be installed into each workspace. We'd need administrative access from the Kubernetes Slack maintainers to allow access there, for example.

**Comment by bacongobbler** [comment]
Perhaps I may be mis-reading the documentation. It looks as though it's just an install link and users can then subscribe to events from that app. I guess it's just a matter of what permissions we're comfortable delegating to Slack.

https://slack.com/intl/en-ca/help/articles/232289568-GitHub-for-Slack

**Comment by david-kirby** [comment]
> users from arbitrary workspaces can subscribe to issues/events. I guess it's just a matter of what permissions we're comfortable providing to Slack.

It is this, yes. Currently we have the Github app installed in our Slack workspace, but I am unable to subscribe to Github events for `helm/helm` because this project doesn't have the Slack App installed, which would be done here: https://github.com/apps/slack/installations/new by a maintainer
