### ISSUE TITLE
Helm3 upgrade cant read the latest data without '--recreate-pods' option

### ISSUE THREAD

**Issue by zwangsh** [helm/helm#8614]
Hi, 

Actually i met some problems when using Helm3 to upgrade, and this problem can be solved in Helm2.

Helm2 has '--recreate-pods' option to allow recreate pods, but Helm3 doest has this funtionnally, since 'helm upgrade' will terminating the old pod and create a new one, in fact, i found the new pod will be running state immediately, skip the containercreating state, i suspect the new pod will reuse the old pod configuration or data without '--recreate-pods' option, so sometimes new pod cant read the latest data, but with '--recreate-pods' option always work, so is there any solution for helm3? thanks in advance.

The following is some of my Deployment configuration:

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "test.labels" . | nindent 4 }}
spec:
  {{- if .Release.IsInstall }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "test.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "test.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "test.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "kill -2 `cat /redis.pid`"]

Since our redis database will not write the data to disk immediately, so need this command to force write, so we need ensure this command work before new pod running.

**Comment by mattfarina** [comment]
This is a good question. The `--recreate-pods` flag requires the chart consumer to do some work rather than adding in logic to the chart to recreate the pods. This can lead to inconsistency. There is a way to add the pod recreation right into the chart. It is documented at https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments

Does that help?

**Comment by zwangsh** [comment]
hi @mattfarina, i've check the document you send and tried the new method in helm3 which instead of '--recreate-pods', but it still cant reach my requirements.

'rollme: {{ randAlphaNum 5 | quote }}' this method not work for my situation, i found that the new method cause the new pod will be running state immediately and the old pod will be Terminating state, they are at the same time.

But if you used '--recreate-pods' options, the new pod will be containercreating state, then running, and old pod will be Terminating state, althrough '--recreate-pods' options has been marked as deprecated in Helm 3, but still can use it in helm3, and it can reach my requirements, but will show a deprecate message and seems not good.

**Comment by zwangsh** [comment]
Hi, i also tried the checksum method, but show so many errors, actually i want deployment resource refresh everytime, is there other solution for it?

**Comment by mattfarina** [comment]
@zwangsh What errors did the checksum method cause? It should not be causing errors as it is an annotation.
