### ISSUE TITLE
Helm3 Type error while resolving dependencies | Can't resolve dependencies it keeps looking for dir which is not present in latest packages.

### ISSUE THREAD

**Issue by ak89224** [helm/helm#8616]
Hi fellas,

Running a helm 3 go script which uses kustomize as one of its dependencies. Kustomize along with all other dependencies are present on GOPATH.

But somehow it can't find the "pkg" directory inside the kustomize.
`package sigs.k8s.io/kustomize/pkg/ifc: cannot find package "sigs.k8s.io/kustomize/pkg/ifc" in any of:
/usr/local/go/src/sigs.k8s.io/kustomize/pkg/ifc (from $GOROOT)
/ascldap/users/bmcderm/golang/src/sigs.k8s.io/kustomize/pkg/ifc (from $GOPATH)
package sigs.k8s.io/kustomize/pkg/types: cannot find package "sigs.k8s.io/kustomize/pkg/types" in any of:
/usr/local/go/src/sigs.k8s.io/kustomize/pkg/types (from $GOROOT)`

Checked the repo but there also is no "pkg" directory in kustomize.
So, i did some digging then i found that `kubernetes` also uses the kustomize as a dependency. When i looked into the vendor of the same then i found a kustomize with a pkg directory (https://gitlab.dev.cncf.ci/kubernetes/kubernetes), so i fetched it and put it under my kustomize dependency.

Finally it solved the multiple dependency issues but now it start throwing some type error as below :

`# sigs.k8s.io/kustomize/pkg/transformers/config
sigs.k8s.io/kustomize/pkg/transformers/config/factorycrd.go:71:47: cannot use api.Schema.SchemaProps.Properties (type spec.SchemaProperties) as type myProperties in argument to looksLikeAk8sType`

**go version** : `go version go1.13.9 linux/amd64 `

**helm version:**  `version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"} `

**kubectl version :**  `Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"} `

---------
Thanks in Advance if anyone can  provide a consolidate steps to setup a go client for helm 3 !

**Comment by mattfarina** [comment]
kustomize is a transitive dependency for Helm. Helm does not directly use it. Rather a dependency that Helm does use happens to have a dependency on kustomize.

In any case, using Helm as a package import should work without issue. It happens regularly.

Can you share the code you are working on? I might be better able to point out the issue.

Is the code you are trying to build in the `GOPATH` or outside of the `GOPATH`? I would suggest moving the code outside of the `GOPATH` so that go modules can function without attempting to resolve code in the `GOPATH`. This way it will use module versions. Does using having the codebase outside the `GOPATH` work?

**Comment by ak89224** [comment]
@mattfarina , Thanks Man i get it working. Your questions set me on right path.

**For future reference debugging and solution:**
From earlier debugging it was  evident to me that this is due to some dependencies versions mismatch.

We are still not moved to `go mod` for production builds and my feature code was a part of microservice for platform development. So, my code inside the `GOPATH`.

What i did :

- Moved the feature code outside of `GOPATH` in xxx directory and initiated it with `go mod init github.com/feature-xxx/`.
- It downloaded some required dependencies.
- Then build the go code `go run main.go`
- Here met with another issue : 
`build command-line-arguments: cannot load github.com/Azure/go-autorest/autorest: ambiguous import: found github.com/Azure/go-autorest/autorest in multiple modules:
        github.com/Azure/go-autorest v10.8.1+incompatible (/root/GO/pkg/mod/github.com/!azure/go-autorest@v10.8.1+incompatible/autorest)
        github.com/Azure/go-autorest/autorest v0.9.0 (/root/GO/pkg/mod/github.com/!azure/go-autorest/autorest@v0.9.0)
`

- Did some debugging and again found k8s.io/client-go dependencies version incompatibility. Found the answer  [here](https://github.com/kubernetes/client-go/issues/628#issuecomment-508487691)

- **solution:** updated the `go.mod` file with `require github.com/Azure/go-autorest v12.2.0+incompatible`
- Again build the code but now met with another one : 
```
`# k8s.io/client-go/rest
../GO/pkg/mod/k8s.io/client-go@v11.0.0+incompatible/rest/request.go:598:31: not enough arguments in call to watch.NewStreamWatcher
        have (*versioned.Decoder)
        want (watch.Decoder, watch.Reporter)

# k8s.io/client-go/tools/clientcmd/api/v1
../GO/pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/clientcmd/api/v1/conversion.go:29:15: scheme.AddConversionFuncs undefined (type *runtime.Scheme has no field or method AddConversionFuncs)
../GO/pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/clientcmd/api/v1/conversion.go:31:12: s.DefaultConvert undefined (type conversion.Scope has no field or method DefaultConvert)

# k8s.io/client-go/scale/scheme/appsv1beta1
../GO/pkg/mod/k8s.io/client-go@v11.0.0+incompatible/scale/scheme/appsv1beta1/conversion.go:32:15: scheme.AddConversionFuncs undefined (type *runtime.Scheme has no field or method AddConversionFuncs)
# k8s.io/client-go/scale/scheme/appsv1beta2
../GO/pkg/mod/k8s.io/client-go@v11.0.0+incompatible/scale/scheme/appsv1beta2/conversion.go:32:15: scheme.AddConversionFuncs undefined (type *runtime.Scheme has no field or method AddConversionFuncs)
# k8s.io/client-go/scale/scheme/autoscalingv1
../GO/pkg/mod/k8s.io/client-go@v11.0.0+incompatible/scale/scheme/autoscalingv1/conversion.go:32:15: scheme.AddConversionFuncs undefined (type *runtime.Scheme has no field or method AddConversionFuncs)
# k8s.io/client-go/scale/scheme/extensionsv1beta1
../GO/pkg/mod/k8s.io/client-go@v11.0.0+incompatible/scale/scheme/extensionsv1beta1/conversion.go:32:15: scheme.AddConversionFuncs undefined (type *runtime.Scheme has no field or method AddConversionFuncs)

```
- Found that `go mod` is detecting the k8s client-go version in `go.mod` file. Then after some debugging i tried a couple of versions for client-go and after looking in some docs i tried with `v1.18`  and resolved the version as :

`curl -s https://proxy.golang.org/k8s.io/client-go/@v/kubernetes-1.18.0.info | jq -r .Version
`
`v0.18.0`

- Then add replace directives in your go.mod file to pin to that versions:

`replace k8s.io/client-go => k8s.io/client-go v0.18.0`

**Voila ! now my code builds successfully.**

Then to integrate code back in the microservice, i vendor all my versioned module dependencies using :
`go mod vendor`
Then moved the vendor sub-directories to my module vendor.

**Hope this helps others in future !**
