### ISSUE TITLE
Errors related to values and templating are TERRIBLE

### ISSUE THREAD

**Issue by max-rocket-internet** [helm/helm#8632]
I'm not new to Helm or Kubernetes and I like to think I'm not an idiot but even after all these years with these tools I still find debugging templating issues in Helm painful.

There is countless issues from both new and seasoned Helm users: https://github.com/helm/helm/issues/7593 https://github.com/helm/helm/issues/6275 https://github.com/helm/helm/issues/6936 https://github.com/helm/helm/issues/1311 https://github.com/helm/helm/issues/897 https://github.com/helm/helm/issues/7841 https://github.com/helm/helm/issues/6251 https://github.com/helm/helm/issues/7088 https://github.com/helm/helm/issues/6125 https://github.com/helm/helm/issues/5659

Do you think there's any room for improvement in this area? I think it would help both new and existing users alike 💖

### Example 1: a simple typo in key name in values.yaml

I don't think this message is informative:

```
Error: UPGRADE FAILED: template: test-chart/templates/serviceaccount.yaml:1:14: executing "test-chart/templates/serviceaccount.yaml" at <.Values.serviceAccount.create>: nil pointer evaluating interface {}.create
```

**Idea**: Maybe we could print something like this?

```
Values key "serviceAccount.create" used at templates/serviceaccount.yaml:5 not found in values
```

### Example 2: part of deployment YAML is indented wrong

The main problem with this is that the line number is of the rendered template and NOT the template file we are editing. If you add for loops, included values and some conditionals then sometimes the template file and the rendered template are worlds apart.

```
Error: UPGRADE FAILED: YAML parse error on test-chart/templates/deployment.yaml: error converting YAML to JSON: yaml: line 35: did not find expected '-' indicator
```

**Idea**: Perhaps we could print +/- 10 lines of the rendered template to show where the problem is?

### Example 3: some typo in values.yaml

Error is not really specific at all:

```
Error: cannot load values.yaml: error converting YAML to JSON: yaml: line 23: did not find expected key
```

**Idea**: Print something more informative

### Example 4: Accidentally using `-}}` in templating without knowing what it does

I don't even know what this means but it's SUPER common:

```
Error: UPGRADE FAILED: YAML parse error on test-chart/templates/deployment.yaml: error converting YAML to JSON: yaml: line 24: mapping values are not allowed in this context
```

**Idea**: Same as example 2

**Comment by technosophos** [comment]
Is there a reason to keep this issue open? It seems to be editorial, and points to existing issues that are more specific. As pointed out in the comments, most of these issues come from external libraries.

**Comment by max-rocket-internet** [comment]
> We're open to suggestions on how to show the lines of code around an issue. I like that idea.

Shall I create a specific issue for this then if this issue is too "editorial"?

> Is there a reason to keep this issue open?

Is there likely to be any improvement in this area if it's closed?

> points to existing issues that are more specific.

They are all also closed.

**Comment by technosophos** [comment]
Specific issues for specific errors would be fine. What we need to be able to do is link a specific PR with a specific issue (one-to-one, not one-to-many). Likewise, a specific _solution_ to the problem would be a good issue as well. The reason I am inclined to close the present issue  is that it's a mixed complaint about lots of different messages from lots of different libraries, with no clear way of addressing the problem.

Basically, though, if the error is merely bubbled up from another library, like the YAML parser, and there's nothing we can do about that to make it better (short of something drastic like writing our own YAML parser), we're likely to close-won't-fix it. There are just too few of us to be able to drive upstream fixes for a bunch of different libraries (especially Go itself, where it takes years to push issues through).

Hope that clarifies yesterday's comments.

**Comment by max-rocket-internet** [comment]
> The response Helm gets back from the Go template parser is "error converting YAML to JSON: yaml: line 35: did not find expected '-' indicator" This is a string.

Yes, I've seen the same errors in other golang tools also.

> The underlying parser doesn't provide a line number in the error.

Well it does, just in a string 😅

> This means that Helm would need to have a parsing capability for the errors from Go in order to extract things like line numbers

That's a great idea! I'll create an issue for that 🎉

> In general, the Go team does make changes to the error messages so that parsing the text of messages can be brittle

Of course but we have go modules now, the versions are pinned, we can add a tests and/or fall back to just printing the ugly error messages if the string is not parsable right?

> We're open to suggestions on how to show the lines of code around an issue. I like that idea.

🎉

> Some of the other errors could be more easily improve. Example 3 is one of those.

Cool. This is also the least problematic error as it it's just a problem parsing a YAML file (the values file) that has no templating inside it.

> Is there a reason to keep this issue open? It seems to be editorial

I guess it's more of a rant, but I did provide examples, suggested solutions and previous issues.

> like the YAML parser, and there's nothing we can do about that to make it better (short of something drastic like writing our own YAML parser

You could parse the string without writing your own YAML parser 🙂

**Comment by max-rocket-internet** [comment]
> Specific issues for specific errors would be fine. What we need to be able to do is link a specific PR with a specific issue

Your wish is my command:

https://github.com/helm/helm/issues/8657
https://github.com/helm/helm/issues/8656
https://github.com/helm/helm/issues/8655
https://github.com/helm/helm/issues/8654

Thanks for taking the time to reply @mattfarina @technosophos 💙

**Comment by azelezni** [comment]
For anyone looking for a way to see the malformed YAML with `error converting YAML to JSON` errors, just put your template in `NOTES.txt` and run `helm template test . --dry-run --debug` to get the malformed YAML.
