### ISSUE TITLE
Helm should inject its version into the context dict

### ISSUE THREAD

**Issue by misberner** [helm/helm#8641]
There currently is no way to check in a template with what version of Helm it is being rendered/installed. As a consequence, it is not possible to safely (without breaking certain users installations) use the `lookup` function, which was added in Helm 3.1 -- the `apiVersion` field in the chart metadata only allows marking a chart as "requiring 3.x", and there is no possible way to differentiate Helm 3.1 from Helm 3.0. Also, Go templates do not allow checking if a function is defined.

I understand reservations regarding having templates render differently depending on the version of Helm being used, regarding reproducibility and all. However, in that case the original sin was to change the template API by adding a builtin function without incrementing the required `apiVersion` of the chart. I also think that way more egregious best practice violations are possible in the current state, and strongly recommending against doing something is a better way than making it impossible. Checking the version could be done to accomplish something as harmless as printing a _meaningful_ error message that this chart requires at least Helm 3.1, instead of erroring out with an obscure error that will require some googling by the user to find out what went wrong.

That ship obviously has sailed for `lookup`/3.0->3.1, but maybe `lookup` wasn't the last function to be added to the templating interface.

**Comment by mattfarina** [comment]
Helm 3.3.0 shipped with the ability to get the Helm version. The PR is at #7005.

Does that suffice?

**Comment by misberner** [comment]
Perfect, thank you and apologies for the noise - I had Helm 3.2 installed and didn't realize there was a more recent version. I'll close this.
