### ISSUE TITLE
Helm3.3 lint strict fails for apiextensions.k8s.io/v1beta1

### ISSUE THREAD

**Issue by pchugh79** [helm/helm#8642]
Helm lint strict fails on custom resource definition using deprecated apiVersion:  apiextensions.k8s.io/v1beta1
whereas this apiVersion is supported by kubernetes until version 1.19. 
This fails only on linux but no failures on windows.

Helm version 3.3

Helm lint --strict <chart>
Chart with CRD and apiVersion: apiextensions.k8s.io/v1beta1

**Comment by technosophos** [comment]
I am marking this as  "bug" based on ongoing discussions in #8608 and #8596. I think we would likely accept a PR that downgrades this particular version/kind to a warning.

**Comment by hickeyma** [comment]
Duplicate of #8596

**Comment by hickeyma** [comment]
Closing as a duplicate of #8596
