### ISSUE TITLE
Starter management commands

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#8648]
Helm has commands to make plugin management easier. You can run commands like `helm plugin install`. The management scheme has made it easier for people to create, manage, and install plugins.

Starters have not seen the same level of adoption. The idea is to make them easier to find, install, and manager. If there were commands to install and otherwise manage starters, like plugins, it could enable a better ecosystem of them.

**Comment by technosophos** [comment]
When we first designed starters, one of the things I had pondered was whether we could just package starters as regular charts, then use a special fetch-like command to get a starter chart and drop it into the right location. That idea might be worth reviving, as it would be much easier create and integrate.
