### ISSUE TITLE
After helm install some services do not exist

### ISSUE THREAD

**Issue by spacem** [helm/helm#8652]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.7", GitCommit:"4a1514f7dbb15bf5047b349d2599d23756ed75b8", GitTreeState:"clean", BuildDate:"2020-07-15T03:33:19Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS

Sorry I don't know if this is an issue with helm or kubenetes, aks, or just my understanding and I'm not sure how to track down the issue. It only seems to happen since we upgraded to kubenetes 1.17.1 and helm 3.4 (previously used helm 2 with tiler).

On my build server I do a `helm delete` followed by `helm install`. This runs with no error but when I look some of the new services are not there. If I `helm delete` then wait a while then `helm install` the services create fine. I cannot find how to see the error but these services are all ones with specific load balancer IP addresses. I expect maybe AKS thinks the load balancer IP is still in use so it is not able to create the service. I was expecting helm install might error?

Please any advice on tracking down the error and if there is a way to get helm to wait or error or if this might be a bug in helm or another service or some other thing I can try.

Here is an extract from our helm template:
```
apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  type: LoadBalancer
  loadBalancerIP: {{.Values.AZ_AKS_OUTBOUND_IP}}
  ports:
  - port: 8080
  selector:
    app: myapp
```

When I run `kubectl get services` some services are there but not this one.

**Comment by bacongobbler** [comment]
Interesting error case. If you can try to create a test case we can use to reproduce the issue, that would be appreciated. I have not heard of Kubernetes losing track of a given service after a hard re-install (`helm uninstall && helm install`).
