### ISSUE TITLE
helm lint fails if file contains only yaml comments

### ISSUE THREAD

**Issue by dastrobu** [helm/helm#8653]
helm lint fails with a not so helpful error message when there is only yaml comments in the rendered template file. 

Steps to reproduce: 

```
helm create foo 
echo '
# a yaml comment
{{ if 0 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "foo.fullname" . }}
  labels:
    {{- include "foo.labels" . | nindent 4 }}
data:
  foo: |
    hello world!
{{ end }}
' > foo/templates/configmap.yaml
helm lint foo
```
which gives
```
==> Linting foo
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/configmap.yaml: object name does not conform to Kubernetes naming requirements: ""

Error: 1 chart(s) linted, 1 chart(s) failed
```

Once one has understood the error message, there is an easy workaround. Either remove the comment, convert it to a go template comment or make sure it is only rendered if there is a valid resource rendered as well. 
Nevertheless, a comment should not cause linting to fail, as empty files are totally valid. 

Output of `helm version`:
`version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}`

**Comment by mattfarina** [comment]
Note, This was captured in another ticket that I cannot find at the moment.

**Comment by dastrobu** [comment]
Seems to be a duplicate of #8621.
