### ISSUE TITLE
Show line numbers when rendering YAML

### ISSUE THREAD

**Issue by max-rocket-internet** [helm/helm#8654]
Many of the templating errors that Helm produces mention line numbers but these line numbers are from the rendered YAML. For example:

```
Error: YAML parse error on test-chart/templates/deployment.yaml: error converting YAML to JSON: yaml: line 44: did not find expected '-' indicator
```

But then when we run helm with `--debug` to get the rendered YAML, there are no line numbers shown in the rendering. Some of our charts render out to over 3000 lines of YAML it would be helpful to have the line numbers shown and perhaps some colours 😃

**Comment by bacongobbler** [comment]
PRs from the community to improve this functionality would be most welcome.

**Comment by roy-work** [comment]
> But then when we run helm with `--debug` to get the rendered YAML

Running `helm template` with `--debug`, for me, doesn't output the YAML? If it did, it'd probably get me most of the way there, but every time I hit this issue, I'm essentially fumbling in the dark for what is actually wrong w/ the input, since the line numbers are completely divorced from anything in my editor…

**Comment by ebuildy** [comment]
You can use grep for that!

```
helm template -s templates/deployment.yaml . --debug | grep -n '^'
```

Will print:

```
install.go:192: [debug] Original chart version: ""
install.go:209: [debug] CHART PATH: /Users/tdecaux/dev/charts/xxxxx

Error: YAML parse error on xxxxx/templates/deployment.yaml: error converting YAML to JSON: yaml: line 34: mapping values are not allowed in this context
1:---
2:# Source: templates/deployment.yaml
3:apiVersion: apps/v1
4:kind: Deployment
5:metadata:
6:  name: release-name
7:  labels:
8:    helm.sh/chart: xxxxx0.1.0
9:    app.kubernetes.io/name: xxxx
10:    app.kubernetes.io/instance: release-name
11:    app.kubernetes.io/version: "0.9.3"
12:    app.kubernetes.io/managed-by: Helm
...
```

**Comment by max-rocket-internet** [comment]
> You can use grep for that!

Indeed, your suggestion is very helpful 💖 But this would still be a total pain with complex charts with many templates and involves running a second command. This feature should be in Helm itself IMO.

**Comment by max-rocket-internet** [comment]
Possible fix in https://github.com/helm/helm/pull/8699 but there is some dependencies 🙏
