### ISSUE TITLE
"Use --debug flag to render out invalid YAML" but it does not render out the YAML

### ISSUE THREAD

**Issue by max-rocket-internet** [helm/helm#8655]
I get this error:

```
$ helm template stable/test-chart
Error: template: test-chart/templates/serviceaccount.yaml:1:14: executing "test-chart/templates/serviceaccount.yaml" at <.Values.serviceAccount.create>: nil pointer evaluating interface {}.create

Use --debug flag to render out invalid YAML
```

Cool, I can use `--debug` but it doesn't render anything extra, just repeats the error twice 😅

```
$ helm template --debug stable/test-chart
install.go:172: [debug] Original chart version: ""
install.go:189: [debug] CHART PATH: /Users/max.williams/git/helm-charts/stable/test-chart


Error: template: test-chart/templates/serviceaccount.yaml:1:14: executing "test-chart/templates/serviceaccount.yaml" at <.Values.serviceAccount.create>: nil pointer evaluating interface {}.create
helm.go:94: [debug] template: test-chart/templates/serviceaccount.yaml:1:14: executing "test-chart/templates/serviceaccount.yaml" at <.Values.serviceAccount.create>: nil pointer evaluating interface {}.create
```

**Comment by bacongobbler** [comment]
In your particular case, the values you provided as input to the template were invalid, so the rendering engine failed prior to actually render the template. This is why no output was available.

To fix this particular case, check to see why `.Values.serviceaccount` was nulled out. As mentioned in previous tickets, this cannot be fixed as explained in https://github.com/helm/helm/issues/8026#issuecomment-677851638, but we're welcome to PRs from the community to address this case or make the error message more clear to the user.

To clarify further, `--debug` only works in cases where fields are invalid, such as when you provide a template that is supposed to render a Deployment, but contains fields that are not considered part of the Deployment manifest [as per the spec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/).

Hope this helps.

**Comment by bacongobbler** [comment]
because there's nothing we can do to address this case, I'm going to close this and ask you to follow #8026 for further updates on this particular case. Thanks.

**Comment by max-rocket-internet** [comment]
>  so the rendering engine failed prior to actually render the template. This is why no output was available.

Can we not detect that situation and then NOT print "Use --debug flag"?

**Comment by azelezni** [comment]
For anyone looking for a way to see the malformed YAML with `error converting YAML to JSON` errors, just put your template in `NOTES.txt` and run `helm template test . --dry-run --debug` to get the malformed YAML.

**Comment by rajan123456** [comment]
> For anyone looking for a way to see the malformed YAML with `error converting YAML to JSON` errors, just put your template in `NOTES.txt` and run `helm template test . --dry-run --debug` to get the malformed YAML.

This should be part of documentation related to debugging/troubleshooting tips. Such an awesome hack!

**Comment by PureRaidenCloud** [comment]
> For anyone looking for a way to see the malformed YAML with `error converting YAML to JSON` errors, just put your template in `NOTES.txt` and run `helm template test . --dry-run --debug` to get the malformed YAML.

Your suggestion is good, however, there's a crucial aspect that seems to be overlooked. The `helm template` command does not render and output the contents present in NOTES.txt. To achieve this, you would need to use the `helm <install / upgrade> test ./your-chart --dry-run --debug` command, but this necessitates a connection to a Kubernetes cluster.

There's an ongoing discussion related to this topic on this thread: https://github.com/helm/helm/issues/6901

It would be beneficial if Helm could support an additional command like `--render-notes` in the future.
