### ISSUE TITLE
Try to parse "YAML parse" string errors from text template package, fall back if not

### ISSUE THREAD

**Issue by max-rocket-internet** [helm/helm#8657]
I made my case to improve the errors relating to templating in https://github.com/helm/helm/issues/8632 and now I would like to suggest an ambitious solution for a specific error.

I know the errors are returned as strings to Helm from the `text/template` package, I've seen the same errors in other golang tools also.

When there's a tonne of templating, conditions, loops etc in use, it's very difficult to debug. I think my worst example was trying to debug a PR for [this file](https://github.com/helm/charts/blob/0a1d70d5d4350d2a88a64f1f6638ea612f44c4e9/stable/prometheus/templates/server-configmap.yaml):

```yaml
{{- $root := . -}}
{{- range $key, $value := .Values.serverFiles }}
  {{ $key }}: |
{{- if eq $key "prometheus.yml" }}
    global:
{{ $root.Values.server.global | toYaml | trimSuffix "\n" | indent 6 }}
{{- end }}
{{- if and (eq $key "alerts") (empty $value.groups) }}
    groups:
{{- range $ruleKey, $ruleValue := $value }}
    - name: {{ $ruleKey -}}.rules
      rules:
{{ $ruleValue | toYaml | trimSuffix "\n" | indent 6 }}
{{- end }}
{{ else }}
{{ toYaml $value | indent 4 }}
{{- end }}
{{- if eq $key "prometheus.yml" -}}
{{- if $root.Values.extraScrapeConfigs }}
{{ tpl $root.Values.extraScrapeConfigs $root | indent 4 }}
{{- end -}}
{{- if $root.Values.alertmanager.enabled }}
    alerting:
{{- if $root.Values.alertRelabelConfigs }}
{{ $root.Values.alertRelabelConfigs | toYaml  | trimSuffix "\n" | indent 6 }}
{{- end }}
```

### Example error

```
YAML parse error on test-chart/templates/deployment.yaml: error converting YAML to JSON: yaml: line 35: did not find expected '-' indicator
```

### My suggested solution

I know it's a string but there's enough information there to get the template file and the rendered line number where the problem is. Could we do this?

1. Parse the string error for the file name and line numbers
2. If it is not parsable, just print the error like we do now
3. Render the template with the error, +/- 10 lines at the line number

**Comment by mattfarina** [comment]
I like the idea of presenting better output. An improved ability to debug these errors would be great.

The Go team changes errors messages from time to time. An error message change is not considered an API change. With that in mind, I wonder how often this error has changed in the past. Is the format is fairly stable a parsing package could be created for these strings. I imagine other tools would like to use it as well.

This could be done as a 3rd party package that many can consume or within helm. Pull requests welcome.

**Comment by jsoref** [comment]
Does this cover:
> cannot load values.yaml: error converting YAML to JSON: yaml: line 49: did not find expected key

specifically, it would be immensely helpful if instead of saying `values.yaml`, it gave a full path to `values.yaml` -- some of us don't have a working `strace` -- which makes it hard to divine which `values.yaml` file is in question and whether it even exists (I can't tell!)

**Comment by max-rocket-internet** [comment]
Not stale. This is still massive time waster when using/debugging Helm.

**Comment by jsoref** [comment]
Reopen?

**Comment by azelezni** [comment]
For anyone looking for a way to see the malformed YAML with `error converting YAML to JSON` errors, just put you're template in `NOTES.txt` and run `helm template test . --dry-run --debug` to get the malformed YAML.
