### ISSUE TITLE
Helm manage chart take the exists resources over k8s's management

### ISSUE THREAD

**Issue by haojingma** [helm/helm#8658]
Output of `helm version`:
3.3.0

Output of `kubectl version`:
1.13

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
etc.

hi，my request is to enhance the ops.

Image this situation, i have some exists resources in k8s. now i wanna develop a chart to manage this resources. when the chart is done, i try to online this, but i wanna know the different between the chart and exists resources. If the difference is not big, i will take over the resources from k8s to chart. If the difference is too big, i will not apply the chart.

So turely, the enhancement function is:
1. helm interface: install chart, take the exists resources over k8s, and put it into chart_instances.
2. helm interface: dry run chart, show the difference between the current and the willingness.

now helm can cover the above requests? or it is arranged?

**Comment by bacongobbler** [comment]
This sounds like an opportunity for a plugin. Helm does not have support for this, but an assistive tool similar to `helm diff` might be useful.

See also #2730 for discussions around adopting resources not managed by helm into a release.

**Comment by bacongobbler** [comment]
I'm going to close this in favour of #2730 to keep the conversation around adopting existing resources into a release in one ticket. Please post your thoughts and comments there. Thanks!

**Comment by haojingma** [comment]
Got it. But #2730 this plugin is not maintained almostly 3 years. And i try to install it, but some errors occured. So does it used by anyone?
I know helm will validated the annotations and labels, and i have used it. #7649 But edit every resources manually is so terrible, So i try to find some easy way out, #2730 is not my answer, So do someone can give some opinions?

**Comment by bacongobbler** [comment]
`helm commandeer` does not exist yet. There is no solution available to solve your current problem. Someone has to go and implement it.:)
