### ISSUE TITLE
--set-file adding newline

### ISSUE THREAD

**Issue by ronaldpetty** [helm/helm#8666]
For some reason it seems --set-file adds a newline to variables in question.

% helm version
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}

% kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-14T11:09:22Z", GoVersion:"go1.14.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

EKS 1.17

I am trying to load files via --set-file, which does work, however when using in _helper, I see the variables include a newline which is not in the file itself.

```
% cat dh.username 
myusername
%
```

```
helm template $NAME --set namespace=$NAME -f jakku-values.yaml \
--set-file=imageCredentials.username=dh.username \
--set-file=imageCredentials.password=dh.password \
--set=imageCredentials.email=my@email.com\
--set-file=admin.password=ch.password \
--set-file=admin.username=ch.username \
.
```

In the helper:

```
{{/*
Provide Docker registry information
*/}}
{{- define "imagePullSecret" }}
{{- with .Values.imageCredentials }}
{{- printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" (.registry | trim) .username .password .email (printf "%s:%s" .username .password | b64enc) | b64enc }}
{{- end }}
{{- end }}
```

This produces output where each 'with' variable has a newline (which breaks docker registry format).  I had to use trim to work around this.

```
{{/*
Provide Docker registry information
*/}}
{{- define "imagePullSecret" }}
{{- with .Values.imageCredentials }}
{{- printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" (.registry | trim) (.username | trim) (.password | trim) (.email | trim) (printf "%s:%s" .username .password | b64enc) | b64enc }}
{{- end }}
{{- end }}
```

I don't see anything about the newline in the docs.  Any thoughts what my misstep is?

**Comment by bacongobbler** [comment]
For reference, the full implementation for `--set-file` can be found here:

https://github.com/helm/helm/blob/9b42702a4bced339ff424a78ad68dd6be6e1a80a/pkg/cli/values/options.go#L74-L82

I think this may have more to do with your Go template than `--set-file`. All `--set-file` does is set the value to the contents of the file.

From https://golang.org/pkg/text/template/#hdr-Text_and_spaces

> By default, all text between actions is copied verbatim when the template is executed. For example, the string " items are made of " in the example above appears on standard output when the program is run.

> However, to aid in formatting template source code, if an action's left delimiter (by default "{{") is followed immediately by a minus sign and ASCII space character ("{{- "), all trailing white space is trimmed from the immediately preceding text. Similarly, if the right delimiter ("}}") is preceded by a space and minus sign (" -}}"), all leading white space is trimmed from the immediately following text. In these trim markers, the ASCII space must be present; "{{-3}}" parses as an action containing the number -3.

> For instance, when executing the template whose source is

    "{{23 -}} < {{- 45}}"

> the generated output would be

    "23<45"

> For this trimming, the definition of white space characters is the same as in Go: space, horizontal tab, carriage return, and newline.

Have you tried modifying your template? I notice in some places you're using `{{-`, and in others you're using `}}`. The former will strip all preceding newline characters, while the latter will not. Try playing around with your template a bit and see if you can find a workable solution that way.
