### ISSUE TITLE
Allow `helm template --app-version`

### ISSUE THREAD

**Issue by MOZGIII** [helm/helm#8670]
Allow passing `--app-version` flag when running `helm template`.

Output of `helm version`:
```
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}
```

```shell
$ helm template \
  vector \
  distribution/helm/vector \
  --values scripts/generate-kubernetes-yaml/values.yaml \
  --version master \
  --app-version latest

Error: unknown flag: --app-version
```

**Comment by bacongobbler** [comment]
depends on https://github.com/helm/helm/issues/8194.

**Comment by bacongobbler** [comment]
closing as a duplicate feature request, as any flags introduced to `helm install` will appear for `helm template`. The former has to be implemented before the latter can be introduced.
