### ISSUE TITLE
Add option to supress output for helm template

### ISSUE THREAD

**Issue by ankitm123** [helm/helm#8672]
Output of `helm version`: 3.3.0

Output of `kubectl version`: 1.16.0
Cloud Provider/Platform (AKS, GKE, Minikube etc.): EKS

Executing `helm template <chart-directory> --output-dir=<random-location>` prints endless lines of this form:
```
wrote ...
wrote ...
wrote ...
.
.
```

Seems like these lines are coming from here: 
https://github.com/helm/helm/blob/master/pkg/action/install.go#L504

Would be nice to have an option to disable printing these lines. They make debugging hard for projects with many charts.

I can make a PR, if it makes sense.

**Comment by marckhouzam** [comment]
Thanks for the report.
I think this printout was simply forgotten during development and should not be there at all.

Go ahead and make a PR removing it.  Thanks!

**Comment by ankitm123** [comment]
cool, created a PR @marckhouzam

**Comment by bacongobbler** [comment]
FYI, the PR that introduced this line of code came from https://github.com/helm/helm/pull/5762, which does appear to be a debug statement that wasn't removed during review. Thanks for catching this.

**Comment by marckhouzam** [comment]
After discussion in #8673, we decided that the output could be useful and that using grep would be the best solution when needing to ignore that output.
