### ISSUE TITLE
StatefulSet never ready on no-op deployment with partitions.

### ISSUE THREAD

**Issue by behos** [helm/helm#8674]
Hi,

We're running into an issue where our StatefulSets are never considered ready when using `partition` in the `updateStrategy.rollingUpdate`.

The scenario is as follows:

* A StatefulSet with 3 replicas is set to `partition: 3`.
* A chart is applied which doesn't cause a change to the statefulSet.
* When waiting for the statefulset, this message appears:
```
StatefulSet is not ready: namespace-example/statefulset-example. 3 out of 0 expected pods have been scheduled
```

In the StatefulSet's status, the `currentRevision` matches the `updateRevision` and both the `currentReplicas` and `updatedReplicas` are set to `3`.

The related code here: https://github.com/helm/helm/blob/662090a37e977922828779d249f9cc4f8fc7ed1d/pkg/kube/wait.go#L321-L331 also matches the behaviour

`expectedReplicas := replicas - partition` (equals 0)

and `int(sts.Status.UpdatedReplicas) != expectedReplicas` since `UpdatedReplicas` is 3.

Getting a StatefulSet in this state can happen when updating the partition attribute after a rolling update:

* Start with a STS partition: 3
* Deploy a change.
* Rolling update by setting partition 0.
* Set partition back to 3.

I'm not sure if this would catch other cases, but it seems like taking the revisions into account would work:

```
expectedReplicas := replicas
if (sts.Status.UpdateRevision != sts.Status.CurrentRevision) {
   expectedReplicas -= partition
}
```

Output of `helm version`: 

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-11T12:41:00Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-11T12:32:32Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): N/A

**Comment by seaneagan** [comment]
For context here are how other libraries handle this:

kubectl rollout status: https://github.com/kubernetes/kubectl/blob/18e781fa774127786b5a2092ed2dc0351dafdb87/pkg/polymorphichelpers/rollout_status.go#L119-L152
kstatus: https://github.com/kubernetes-sigs/cli-utils/blob/master/pkg/kstatus/status/core.go#L77-L152

**Comment by technosophos** [comment]
What is the Helm command you ran?

**Comment by behos** [comment]
We're directly calling `Install.Run`

https://github.com/helm/helm/blob/94438b67221d4af3c9993945a42275be7ffc6baa/pkg/action/install.go#L172

We're currently on `v3.0.0-beta.4.0.20200320140559-9dfda5437505` but it seems that the same path is still on master.

It's not simple to do an upgrade to test this right now, but I'll keep you posted if you can try out 3.3.1

**Comment by behos** [comment]
I'm not sure there's been a resolution for this.

**Comment by bacongobbler** [comment]
If you can reproduce the issue with a more recent version of helm 3 then we can reopen and investigate further. We cannot provide support for beta pre-releases of helm 3. That is why we asked if you can reproduce with helm 3.3.1.

The most recent release now is helm 3.4.2. I would start there.

**Comment by iSignal** [comment]
I can reproduce this issue with helm 3.4.2. I tried this with both minikube (kubernetes 1.20.0, docker driver) and against GKE. I have also been able to reproduce this with previous versions of helm.

The steps I used were:
1. 
  ``` 
kubectl create namespace tmp-2 && helm3 install yb-demo  ~/code/charts/stable/yugabyte/ --set
resource.master.requests.cpu=0.25,resource.master.requests.memory=0.35Gi,resource.tserver.requests.cpu=0.25,resource.tserver.requests.memory=0.35Gi --namespace tmp-2 --wait
# code/charts/stable/yugabyte comes from https://github.com/yugabyte/charts/stable/yugabyte
# this step succeeds
```
2. Add a partition field set to the above chart
  ```
  helm3 upgrade yb-demo  ~/code/charts/stable/yugabyte/ --set partition.master=1,resource.master.requests.cpu=0.25,resource.master.requests.memory=0.35Gi,resource.tserver.requests.cpu=0.25,resource.tserver.requests.memory=0.35Gi --namespace tmp-2 --wait
# this step hangs indefinitely. partiton.master defaults to 0 and maps to rollingUpdate.partition https://github.com/yugabyte/charts/blob/57aad61c947cafee4df8ef8d2b15255c0465095a/stable/yugabyte/templates/service.yaml#L162
```
The status of the stateful set looks as follows:
```
status:
  collisionCount: 0
  currentReplicas: 3
  currentRevision: yb-master-5d5844777d
  observedGeneration: 2
  readyReplicas: 3
  replicas: 3
  updateRevision: yb-master-5d5844777d
  updatedReplicas: 3
```

**Comment by kopwei** [comment]
I am facing the same issue with "helm upgrade --wait" command, where the Statefulset's replica count target can never be archived. The Statefulset's replicaCount is set to 2 but Helm keeps complains about it and timeout eventually in upgrade.

Error Message:
```log
wait.go:348: [debug] StatefulSet is not ready: isp-flux/flux-stolon-keeper. 2 out of 0 expected pods have been scheduled
```

Stateful status:
```yaml
status:
  collisionCount: 0
  currentReplicas: 2
  currentRevision: flux-stolon-keeper-59f7ddfbd6
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
  updateRevision: flux-stolon-keeper-59f7ddfbd6
  updatedReplicas: 2
 ```

**Comment by kopwei** [comment]
This issue occurs when the Statefulset's update strategy is set to "RollingUpdate".
The error occurs at function "statefulSetReady" in pkg/kube/wait.go file
 During upgrade. the partition is equal to replicas. Thus values of "expectedReplicas" is calculated to 0 and can never be equal to Status.UpdatedReplicas. And it will stuck here and ends up in upgrading time out eventually.
