### ISSUE TITLE
Format files command in Helm

### ISSUE THREAD

**Issue by PrzemyslawSwiderski** [helm/helm#8680]
Hi, 
I would like to ask if there are any plans to add some format command to helm.
It would be great if there would be possibility to format `yaml` or `tpl` files by executing single helm command for a specific chart.
I think it could be similar to a Terraform [`fmt`](https://www.terraform.io/docs/commands/fmt.html) command.
Please let me know if there are some plans or maybe there is some plugin to helm to do that.

ps.
Thanks for great work with Helm tool :)

**Comment by bacongobbler** [comment]
I do not believe there is a specification that describes how a `text/template` should be formatted. Given that text/template substitutes variables as input, whitespace and indentation is important, so any re-formatting of a template could cause a change in the output.
