### ISSUE TITLE
Output from "helm create XXX" does not follow array item indentation convention

### ISSUE THREAD

**Issue by max-rocket-internet** [helm/helm#8687]
We use `helm create my-new-chart` as it's a nice and convenient way to create a chart that follows the latest Helm style and conventions. But the output from this command indents array items, for example:

https://github.com/helm/helm/blob/91094186ebbfb608a19d34212cfa46cd3d065666/pkg/chartutil/create.go#L277-L280

I know this indentation doesn't functionally matter, it's only cosmetic, but all the current Kubernetes documentation shows array items without this indentation. And if you use a tool like [helm-diff](https://github.com/databus23/helm-diff), this creates unnecessary diff output when the indentation is mixed.

I can make a PR, would it be accepted?

Output of `helm version`: 3.3.0

**Comment by bacongobbler** [comment]
Whitespace is significant. Therefore, the indentation level for the array is correct. Please refer to the YAML specification.

**Comment by max-rocket-internet** [comment]
> Whitespace is significant

I think you mean insignificant?

> Please refer to the YAML specification.

I've read the spec, I said it was cosmetic and gave a reason why in this case the cosmetic matters. But OK, thanks for the lovely reply.

**Comment by bacongobbler** [comment]
I meant what I said. Whitespace is significant when it comes to the YAML specification.

Consider the following:

```
image:
    pullPolicy: always
    tag: latest
```

compared to

```
image:
    pullPolicy: always
tag: latest
```

When parsed as JSON (as YAML is a superset of JSON), they result in two different JSON structures:

```
{
    "image": {
        "pullPolicy": "always",
        "tag": "latest"
    }
}
```

vs

```
{
    "image": {
        "pullPolicy": "always"
    },
    "tag": "latest"
}
```

Therefore, whitespace and indentation is significant.

You can test this yourself with [an online converter tool](https://www.convertjson.com/yaml-to-json.htm).

**Comment by HamzaMasood1** [comment]
@bacongobbler What is your reply to this? I need this style of indentation on my template files as well. Any help would be appreciated.
