### ISSUE TITLE
Add a way to detect out of sync Chart.lock files

### ISSUE THREAD

**Issue by andytom** [helm/helm#8689]
It is possible for a chart writer to add a dependency to the `Chart.yaml` but to forget to run `helm dependency update` before committing the change to version control. It would be useful to have a quick way to detect these mismatches.

```bash
❯ cd $(mktemp -d)
❯ helm create test
❯ cat <<EOT >> test/Chart.yaml
dependencies:
- name: zookeeper
  version: "2.0.0"
  repository: https://kubernetes-charts-incubator.storage.googleapis.com/
EOT
❯ helm dependency build test
...
# Bump the zookeeper version to 2.1.0 in the Chart.yaml
❯ vim test/Chart.yaml 
❯ helm dependency build test
Error: the lock file (Chart.lock) is out of sync with the dependencies file (Chart.yaml). Please update the dependencies
```

It would be nice to have a command to run that could be used to detect this mismatch.

**Comment by bacongobbler** [comment]
While I agree that some way to check that the Chart.yaml and Chart.lock are in-sync, I don't believe `helm lint` is the right place for this. `helm lint` runs a series of tests to verify that the chart is well-formed. It is supposed to catch errors that will cause the chart to fail a `helm install` due to missing or malformed fields. As an example, is not the responsibility of `go lint` to make sure that go.mod and go.sum are in sync, either.

Perhaps a `helm dependency check` is more aligned with your suggestion, similar to `go mod verify`.

For reference:

```
><> go help mod verify
usage: go mod verify

Verify checks that the dependencies of the current module,
which are stored in a local downloaded source cache, have not been
modified since being downloaded. If all the modules are unmodified,
verify prints "all modules verified." Otherwise it reports which
modules have been changed and causes 'go mod' to exit with a
non-zero status.
```

**Comment by andytom** [comment]
> While I agree that some way to check that the Chart.yaml and Chart.lock are in-sync, I don't believe `helm lint` is the right place for this. `helm lint` runs a series of tests to verify that the chart is well-formed. It is supposed to catch errors that will cause the chart to fail a `helm install` due to missing or malformed fields. As an example, is not the responsibility of `go lint` to make sure that go.mod and go.sum are in sync, either.
> 
> Perhaps a `helm dependency check` is more aligned with your suggestion, similar to `go mod verify` or `cargo check`.
> 
> For reference:
> 
> ```
> ><> go help mod verify
> usage: go mod verify
> 
> Verify checks that the dependencies of the current module,
> which are stored in a local downloaded source cache, have not been
> modified since being downloaded. If all the modules are unmodified,
> verify prints "all modules verified." Otherwise it reports which
> modules have been changed and causes 'go mod' to exit with a
> non-zero status.
> ```

That makes a lot more sense, I've updated the issue description to represent that.

**Comment by joemiller** [comment]
This would be a nice feature to have. Are there any tools outside of Helm that already implement this?
