### ISSUE TITLE
Helm3 not working on OSX 10.15.5/6 - X509 certificate complaints doing repo update

### ISSUE THREAD

**Issue by richard-fairthorne** [helm/helm#8698]
Attempting to run

```
helm update repo
```

results in this:

```
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "ibm-charts" chart repository (https://raw.githubusercontent.com/IBM/charts/master/repo/stable/):
	Get https://raw.githubusercontent.com/IBM/charts/master/repo/stable/index.yaml: x509: failed to load system roots and no roots provided; exit status 49
...Unable to get an update from the "stable" chart repository (https://kubernetes-charts.storage.googleapis.com):
	Get https://kubernetes-charts.storage.googleapis.com/index.yaml: x509: failed to load system roots and no roots provided; exit status 49
...Unable to get an update from the "bitnami" chart repository (https://charts.bitnami.com/bitnami):
	Get https://charts.bitnami.com/bitnami/index.yaml: x509: failed to load system roots and no roots provided; exit status 49
...Unable to get an update from the "nginx-stable" chart repository (https://helm.nginx.com/stable):
	Get https://helm.nginx.com/stable/index.yaml: x509: failed to load system roots and no roots provided; exit status 49
...Unable to get an update from the "jetstack" chart repository (https://charts.jetstack.io):
	Get https://charts.jetstack.io/index.yaml: x509: failed to load system roots and no roots provided; exit status 49
Update Complete. ⎈ Happy Helming!⎈ 

```

The same type of errors are occuring with kubectl and many unrelated programs that use "go get"

I have tried binaries from brew, and the official binaries of the latest 3.2 and 3.3 versions.

Output of `helm version`:

version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

N/A -- bare metal.

**Comment by bridgetkromhout** [comment]
Hi, @richard-fairthorne - I think this may be a `go` issue, not specific to Helm. There are some ideas for solving it in https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/341 and even in a very old post here: https://groups.google.com/g/golang-nuts/c/gyL_jeOyxQA

I can't replicate the problem so I cannot test solutions, but I suspect it is something to do with how your `go` is installed and what your macOS system has in the keychain.

**Comment by richard-fairthorne** [comment]
I am using a pre-built binary from the helm website. Would this use my system "go"? I got the impression from the version strings that helm is compiled in advance.

**Comment by richard-fairthorne** [comment]
The problem began after upgrading helm, but I cannot recall what version I had earlier :(

**Comment by richard-fairthorne** [comment]
```
Richards-MacBook-Pro:~ rich$ sudo rm -rf /usr/local/go
Richards-MacBook-Pro:~ rich$ sudo rm /etc/paths.d/go
Richards-MacBook-Pro:~ rich$ go
-bash: go: command not found
Richards-MacBook-Pro:~ rich$ which go
Richards-MacBook-Pro:~ rich$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "ibm-charts" chart repository (https://raw.githubusercontent.com/IBM/charts/master/repo/stable/):
	Get "https://raw.githubusercontent.com/IBM/charts/master/repo/stable/index.yaml": x509: failed to load system roots and no roots provided; exit status 49
...Unable to get an update from the "stable" chart repository (https://kubernetes-charts.storage.googleapis.com):
	Get "https://kubernetes-charts.storage.googleapis.com/index.yaml": x509: failed to load system roots and no roots provided; exit status 49
...Unable to get an update from the "bitnami" chart repository (https://charts.bitnami.com/bitnami):
	Get "https://charts.bitnami.com/bitnami/index.yaml": x509: failed to load system roots and no roots provided; exit status 49
...Unable to get an update from the "nginx-stable" chart repository (https://helm.nginx.com/stable):
	Get "https://helm.nginx.com/stable/index.yaml": x509: failed to load system roots and no roots provided; exit status 49
...Unable to get an update from the "jetstack" chart repository (https://charts.jetstack.io):
	Get "https://charts.jetstack.io/index.yaml": x509: failed to load system roots and no roots provided; exit status 49
Update Complete. ⎈Happy Helming!⎈
```

**Comment by bacongobbler** [comment]
> Doesn't the error originate from the golang that the binary is build against?

Yes, that is correct.

> x509: failed to load system roots and no roots provided; exit status 49

A similar error reported in https://github.com/kubeless/kubeless/issues/748 seems to suggest that /etc/ssl is not present on your machine. Have you tried installing your operating system's default root chain certificates? An `apt install ca-certificates` ought to do the trick.

**Comment by richard-fairthorne** [comment]
@bacongobbler Thanks for your reply.

My system does have /etc/ssl -- but most importantly, it is a mac running OSX. I believe the command "apt install ca-certificates" is intended for debian derivative linux distributions. It certainly won't run on my system.

Reverting to older binaries, I still have the same problem. I have found the same problem with kubectl when trying to apply yaml files from https locations. But it seems like everything not relying on GO works just fine.

I'm very stuck with this, and cannot support my cluster from my own laptop anymore.

All help is appreciated.

**Comment by richard-fairthorne** [comment]
I have solved the problem! This is an OSX specific problem cause by a corrupted or somehow broken keychain.

I was able to solve the problem by resetting to my default keychain.

Keychain Access -> Preferences... -> Reset my Default Keychains

Thank you for your time and consideration.
