### ISSUE TITLE
Helm package code

### ISSUE THREAD

**Issue by thynquest** [helm/helm#8700]
Hello there

Actually this ticket is not related to a specific issue but it concerns the source code of the helm package command. 
I am currently working on a helm plugin related to the `helm package` command and when I looked at the code of that command I realized that on the method `Run` the formal parameter `vals map[string]interface{}` is declared but never used; 

so my question is, have you already spotted this or it has been done in purpose just to satisfy an interface ? here is the code below

````golang
// Run executes 'helm package' against the given chart and returns the path to the packaged chart.
func (p *Package) Run(path string, vals map[string]interface{}) (string, error) {
	ch, err := loader.LoadDir(path)
	if err != nil {
		return "", err
	}

	// If version is set, modify the version.
	if p.Version != "" {
		if err := setVersion(ch, p.Version); err != nil {
			return "", err
		}
	}

	if p.AppVersion != "" {
		ch.Metadata.AppVersion = p.AppVersion
	}

	if reqs := ch.Metadata.Dependencies; reqs != nil {
		if err := CheckDependencies(ch, reqs); err != nil {
			return "", err
		}
	}

	var dest string
	if p.Destination == "." {
		// Save to the current working directory.
		dest, err = os.Getwd()
		if err != nil {
			return "", err
		}
	} else {
		// Otherwise save to set destination
		dest = p.Destination
	}

	name, err := chartutil.Save(ch, dest)
	if err != nil {
		return "", errors.Wrap(err, "failed to save")
	}

	if p.Sign {
		err = p.Clearsign(name)
	}

	return name, err
}

````
thank you for your help.

**Comment by hickeyma** [comment]
@thynquest Well spotted. The `vals map[string]interface{}` parameter is not used as you mentioned. You can push a PR if you would like.

**Comment by thynquest** [comment]
@hickeyma  there is the PR

**Comment by hickeyma** [comment]
This breaks the API and in Helm we support backwards compatibility between minor/path releases. Hence, this cannot be  changed until Helm 4.  Sorry @thynquest but this will have to be pushed out until Helm 4 dev commences.

**Comment by thynquest** [comment]
Ah too bad .. but I understand the backward compatibility problem. so we can close this issue

**Comment by bacongobbler** [comment]
For further clarification, the `vals map[string]interface{}` is currently unused. However, it was put in place to support #3141 in a backwards-compatible manner. We just don't have a working implementation of that yet.

**Comment by thynquest** [comment]
Thank you @bacongobbler  for the precision. 
Speaking of working implementation, why can't we give the opportunity to set values when packaging ? (`helm package . --set myprop=myval`); suppose that  a dev team work on an app and when they push code, it triggers a pipeline which creates a docker image with a version(eg: `v1.2.3`), but also in addition to create a docker image with a tag version the dev pipeline triggers another pipeline by sending the image version, which will  package the helm chart using the image version and push it to a chart repository. In that case it could be useful to have the ability to set some property when packaging so we can define, for example the kind of docker image we associate to a given chart (but we can think about something else); without forgetting that we can still override it if necessary during install. sorry if I am not clear enough :sweat_smile: . I could be more specific I you want

**Comment by david-l-riley** [comment]
Honestly, if the solution for #3141 can be revived once the upstream dependency issues are resolved (I sure hope so), it seems better to keep this in for now.
