### ISSUE TITLE
Unable to reference global scope in named template

### ISSUE THREAD

**Issue by astropuffin** [helm/helm#8702]
Output of `helm version`: `version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}`

Setup:
```
> cat values.yaml 
topLevelVariable: "want this value"
example:
  foo:
    uno: 1
  bar:
    dos: 2
```
```
> cat templates/file.yml 
{{- define "app.localScope" -}}
{{ . }}
{{- end }}

{{- define "app.globalScope" -}}
{{ $ }}
{{- end }}

{{- with .Values.example -}}
local: {{ include "app.localScope" . }}
global: {{ include "app.globalScope" . }}
---
{{- end -}}
```
Expected behavior:
When running `helm template`, the local and global scope output would be different.

Observed behavior:
When running `helm template`, the local and global scope output are the same.

In effect, the "global scope" is limited to the scope passed to the named template, which is unexpected. The [official documentation](https://helm.sh/docs/chart_template_guide/named_templates/#setting-the-scope-of-a-template) makes no mention of this, whereas it claims ["there is one variable that is always global - $"](https://helm.sh/docs/chart_template_guide/variables/). This is clearly not true.

**Comment by bacongobbler** [comment]
"global scope" is a bit of a misnomer in this case. In actuality, the dollar sign operator refers to the *root* scope. In a named template, the root scope changes into the form of the input.

In this context, you changed it via 

```
{{- with .Values.example -}}
local: {{ include "app.localScope" . }}
global: {{ include "app.globalScope" . }}
---
{{- end -}}
```

By using the dot operator.

As defined in [text/template's documentation](https://golang.org/pkg/text/template/):

> If the value of the pipeline is empty, no output is generated;
> otherwise, dot is set to the value of the pipeline and T1 is
> executed.

If you want to pass along the root scope to the named template, use the following instead.

```
{{- with .Values.example -}}
local: {{ include "app.localScope" $ }}
global: {{ include "app.globalScope" $ }}
---
{{- end -}}
```

Hope this helps.

**Comment by bacongobbler** [comment]
> The [official documentation](https://helm.sh/docs/chart_template_guide/named_templates/#setting-the-scope-of-a-template) makes no mention of this, whereas it claims ["there is one variable that is always global - $"](https://helm.sh/docs/chart_template_guide/variables/). This is clearly not true.

We would appreciate any efforts to document this behaviour. Marking as such.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

**Comment by pablochacin** [comment]
How is this issue closed if the documentation is still missing this important clarification regarding the meaning of `$` in the context of named templates.

**Comment by caruccio** [comment]
this misleading doc took alway 6 hours of my life ... sigh

**Comment by sxyandapp** [comment]
the  $   is  not  fucking  global

**Comment by thernstig** [comment]
@bacongobbler could this be re-opened? I also got struck by this and it is clearly a huge time sink if missing the key point about global vs root. I think the docs could be clearer as well.

**Comment by joejulian** [comment]
The docs are in the [helm-www](https://github.com/helm/helm-www/issues) repo. Please file an issue there.

**Comment by thernstig** [comment]
Done: https://github.com/helm/helm-www/issues/1399
