### ISSUE TITLE
Get specific variable from helm env

### ISSUE THREAD

**Issue by jkroepke** [helm/helm#8708]
Hi!,

it looks like `helm env` is a great way to get the location of helm plugin directory without any pre-existing knowledge. That's great for shell automation.

In additionally it would be nice to add a parameter to `helm env` to get a value of a specific variable without doing grep or pass the output to an shell interpreter. 

Case:

Right now I have to document different installation method each operation system. This includes a limitation, since this commands will only work, if the variable HELM_PLUGINS is not touched.

Example:
```
# MacOS
curl -LsSf https://github.com/jkroepke/helm-secrets/archive/v3.3.0.tar.gz | tar -C "$HOME/Library/helm" -xzf-

# Linux
curl -LsSf https://github.com/jkroepke/helm-secrets/archive/v3.3.0.tar.gz | tar -C "$HOME/.local/share/helm" -xzf-
```

This could be simply by:
```
# *nix
curl -LsSf https://github.com/jkroepke/helm-secrets/archive/v3.3.0.tar.gz | tar -C "$(helm env HELM_PLUGINS)" -xzf-
```

Output of `helm version`:
```
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"dirty", GoVersion:"go1.15"}
```

**Comment by bacongobbler** [comment]
See https://github.com/helm/helm/pull/8638 and #8635.
