### ISSUE TITLE
Completed pod should be considered ready?

### ISSUE THREAD

**Issue by nirroz93** [helm/helm#8715]
Hi, I installed helm chart including a small pod ("echo hello world!" restartPolicy never) with --wait.

The pod is completed almost instantly ("hello world!" :-) ) and helm stuck in
wait.go:181: [debug] Pod is not ready:

BTW, I added the pod becuase I have a pvc for CronJob and the storage class has waitForFirstConsumer - so the helm wait stucked in wait.go:216: [debug] PersistentVolumeClaim is not bound.

As a workaround for me, I just added sleep to my hello world pod - but maybe it's a bug as the pod already finished to run (it was ready for few ms).

Output of `helm version`:
```
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"clean", BuildDate:"2020-05-06T05:09:48Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by nirroz93** [comment]
@bacongobbler 
To reproduce:
```bash
helm create foo

cat > foo/templates/pod.yml << EOF
kind: Pod
apiVersion: v1
metadata:
  name: mypod
spec:
  containers:
  - name: mycontainer
    image: busybox
    resources:
      limits:
        cpu: "100m"
        memory: 100Mi
      requests:
        cpu: "50m"
        memory: 20Mi
    command: ["/bin/echo"]
    args: ["'hello world!'"] # Helm wait for pod to be ready and if it's completed in an instant
  restartPolicy: Never
EOF

(helm install foo foo/ --wait --debug; ) & ( kubectl get pods -w; helm uninstall foo) 
```

output is:
```
install.go:172: [debug] Original chart version: ""
install.go:189: [debug] CHART PATH: /tmp/helm/foo

client.go:108: [debug] creating 4 resource(s)
NAME    READY   STATUS    RESTARTS   AGE
mypod   0/1     Pending   0          0s
mypod   0/1     Pending   0          0s
mypod   0/1     ContainerCreating   0          0s
wait.go:53: [debug] beginning wait for 4 resources with timeout of 5m0s
foo-65ddb5dff8-zhks2   0/1     Pending             0          0s
foo-65ddb5dff8-zhks2   0/1     Pending             0          0s
foo-65ddb5dff8-zhks2   0/1     ContainerCreating   0          0s
mypod                  0/1     Completed           0          2s
foo-65ddb5dff8-zhks2   0/1     Running             0          2s
wait.go:181: [debug] Pod is not ready: default/mypod
foo-65ddb5dff8-zhks2   1/1     Running             0          3s
wait.go:181: [debug] Pod is not ready: default/mypod
wait.go:181: [debug] Pod is not ready: default/mypod

... <UNTILL TIMEOUT>
```

**Comment by davinchia** [comment]
Hi, I'm also running into this. We have a setup pod that loads some metadata when deploying airbyte.io. It's strange that Helm doesn't consider a complete pod successful.

**Comment by davinchia** [comment]
Hi, I'm also running into this. We have a setup pod that loads some metadata when deploying airbyte.io. It's strange that Helm doesn't consider a complete pod successful.

@bacongobbler is it possible to reopon this?

**Comment by davinchia** [comment]
I'm forced to use the Kube Job abstraction as a result. I typically avoid this as the Kube Job abstract has lax concurrency guarantees and isn't suitable for mission critical applications.

**Comment by jeremysprofile** [comment]
@bacongobbler , I also have a use case where I would like a completed pod to count as successful for helm wait. We are currently just running the pod as a "test" so we check success that way, but it's not intuitive.
