### ISSUE TITLE
Resources not getting injected through template

### ISSUE THREAD

**Issue by imyashvinder** [helm/helm#8721]
I have the following defined in helper file:

```
{{- define "resource.less" }}
resources:
  limits:
    cpu: "300m"
    memory: "500Mi"
  requests:
    cpu: "300m"
    memory:" 500Mi"
{{- end }}
```

I am trying to get the whole block in my deployment file as below:

```
spec:
      containers:
      - image: xxxxxxxxxxxxxxx:{{ .Values.tag }}
        name: xxxxxx
        imagePullPolicy: Always
        {{- if .Values.resource.limits }}
        {{- if .Values.usage.less }}
        {{- template "resource.less" }}
        {{- end }}    
        {{- end }}
```
It throws below error:

Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment): unknown field "resources" in io.k8s.api.apps.v1.Deployment

**Comment by bacongobbler** [comment]
Have you checked the output to see if the indentation level is correct? The `{{-` could be stripping all proceeding whitespace, causing the output of the function to be at the root level of the manifest and therefore causing a validation error.

**Comment by imyashvinder** [comment]
I tried that too but no luck but if i remove those templates and try to fetch from value file directly it works:

```
    spec:
      containers:
      - image: xxxxxxxxxxxxxxxxx:{{ .Values.tag }}
        name: account
        imagePullPolicy: Always
        {{- if .Values.resource.limits }}
{{ toYaml .Values.defaultresource | indent 8 }}    
        {{- end }}
```

where values.yaml looks like below:

```
defaultresource:
  resources:
    limits:
      cpu: "100m"
      memory: "100Mi"
    requests:
      cpu: "100m"
      memory: "100Mi"
```
