### ISSUE TITLE
Golang API: how to use `engine.RenderWithClient` in with `Strict` enabled

### ISSUE THREAD

**Issue by object88** [helm/helm#8725]
The `Strict bool` flag is public in the `engine.Engine` struct, but `client *rest.Client` is not.  The `RenderWithClient` func sets the `client`, but does not provide an opportunity (as far as I can see) to enable `Strict`.

Perhaps I am missing something?  Or can we change the struct to make the client reference public?

Thanks!

**Comment by bacongobbler** [comment]
https://github.com/helm/helm/blob/5b42157335d6e52551d246f233dd66972d5fda09/pkg/engine/engine.go#L40

You should be able to instantiate an `e := Engine{Strict: true, config: config}` then call `e.Render(chrt, values)`. That will enable the `Strict` flag.

> Or can we change the struct to make the client reference public?

Can you clarify further what this would accomplish?

**Comment by object88** [comment]
If the code is within the `engine` package, you can set `config`, but as a consumer of the package, I cannot:

```
cfg, _ := i.settings.RESTClientGetter().ToRESTConfig()
e := engine.Engine{
	Strict: true,
	config: cfg,
}
```
This gets me...
```
apps/tugboat-controller/pkg/helm/helm.go:113:3: cannot refer to unexported field 'config' in struct literal of type engine.Engine
```

Or am I overlooking a Go fundamental?

**Comment by bacongobbler** [comment]
Ah yes. Good point.

Feel free to file a PR to help expose this parameter. I'd imagine the simplest would be a function called `NewWithClient(config *rest.Config)` to instantiate an Engine with a rest config.

**Comment by object88** [comment]
Fantastic, thank you.  I will send off a PR later today or tomorrow.

**Comment by object88** [comment]
PR is still ready for review.
