### ISSUE TITLE
helm2 can't get correct hook result cause install chart failed

### ISSUE THREAD

**Issue by ddljdd** [helm/helm#8726]
helm version:
Client: &version.Version{SemVer:"v2.15.2", GitCommit:"", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.2", GitCommit:"", GitTreeState:"clean"}

kubectl version:

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"archive", BuildDate:"2019-11-12T15:46:42Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"archive", BuildDate:"2019-11-12T15:47:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
private cloud platform.

issue:
in the chart file we have two hooks, one is preinstall hook, another one is preupgrade hook.
see below information (I replace senstivie information as ***)
-------------------------
$ kubectl get jobs
NAME                        COMPLETIONS   DURATION   AGE
***-preinstalljob   0/1           8s         8s
***-preupgradejob   0/1           46m        46m
[cranuser1@controller-1 aic-vdu]$ kubectl get pod
NAME                              READY   STATUS                       RESTARTS   AGE
***-preinstalljob-6hkts   0/1     Completed            0          20s
***-preupgradejob-dvg2w   0/1     Error                        0          46m
----------------------------
When preupgradejob failed with BackoffLimitExceeded, and we install new same release, the helm will report error immediately. like below:
$ helm install ./ --name  *** -f values-override.yaml  --debug
[debug] SERVER: "***"

[debug] Original chart version: ""
[debug] CHART PATH: ***

Error: Job failed: BackoffLimitExceeded
---------------
Actually the pre-install hook is running at this time and finally it exit with 0.

**Comment by bacongobbler** [comment]
Hi @ddljdd. We are no longer accepting bug reports for Helm 2. At this time, only issues related to security are being considered. See https://helm.sh/blog/helm-v2-deprecation-timeline/ for more information.

If you can reproduce the issue with helm 3, please file a new ticket. Thank you!
