### ISSUE TITLE
Feature: add --restrict-namespace command line argument to restrict to which namespaces objects are deployed

### ISSUE THREAD

**Issue by mitar** [helm/helm#8732]
Background: This is a proposal for backwards compatible version of https://github.com/helm/helm/issues/5953 (see https://github.com/helm/helm/pull/6046). See also [this comment](https://github.com/helm/helm/issues/5465#issuecomment-573147280).

I would suggest that helm has a `--restrict-namespace` command line argument added to `helm install` (and maybe few others). If provided, objects can be created only in this namespace, it does not influence template rendering, can be provided multiple times to allow multiple namespaces per call. (Exception would be cluster level objects which would anyway deploy to cluster level.)

I am opening this issue to gain any design input on this proposal and feedback, and once approved I can try to get a PR draft.

**Comment by bacongobbler** [comment]
I'm trying to determine the user profile that would like to restrict a chart to a specific namespace. When we talk about introducing new features to Helm, we talk about [user profiles](https://github.com/helm/community/blob/master/user-profiles.md) as it helps us understand who we're trying to write the feature for and how it'd be useful for them. It also helps us determine if the feature is in scope or not.

For example, an Application Distributor knows the internals of the chart, how the package is architected, and how it's supposed to be laid out when installed into Kubernetes. On the other side, the Application Operator knows nothing about the internals of the package. They fetch the package from a repository and install it. Keep in mind this role is not to be confused with the role of a Kubernetes cluster operator.

My question to you is - given the assumptions stated above - who is this useful for, and how would they use it?

**Comment by mitar** [comment]
Yes, this is indented for Application Operator.

So my use case is that I have a multi-tenant hosting for apps and I would like to deploy each app into its own namespace (as controlled by me) for resource management, accounting, billing. So my requirement for apps is that they have to use only one namespace and I want to be able to assure that this is really so and that things really get deployed to the namespace me as an operator want. Not that I have to parse charts and investigate them to see how they deal with namespaces. I just want deployment to fail if chart is not compliant with my requirements.

**Comment by mitar** [comment]
Unstale.

**Comment by mitar** [comment]
Unstale.

**Comment by mitar** [comment]
Unstale.

**Comment by mitar** [comment]
Unstale.

**Comment by mitar** [comment]
Unstale.

**Comment by jwenjian** [comment]
> Unstale.

You may need a unstale bot. 😄

Anyway, I think this proposal would be helpful.

**Comment by mitar** [comment]
Unstale.

**Comment by mitar** [comment]
Unstale.

**Comment by mitar** [comment]
Unstale.

**Comment by joejulian** [comment]
This falls outside of the realm of what's feasible in helm. To restrict namespaces, use kustomize as a post-renderer, or dry-run and pipe to kubectl -n namespace. This won't really solve your problem though as charts can still have non-namespaced resources and your admin privileges will not prevent them from being installed.

The more secure and manageable way would be to use the role of the user you're installing for, either pipe it through kubectl and use the `--as` flag to impersonate the user, or create a ServiceAccount and attach it to the intended role, using its auth token.

Since this isn't really feasible in helm (at least not before helm 4), I'm going to close this.

**Comment by mitar** [comment]
I think you should note that this is still a pain for many users as seen in #5465.
