### ISSUE TITLE
Common shared helper functions

### ISSUE THREAD

**Issue by strainovic** [helm/helm#8734]
Hi all,

Suppose I have multiple helm charts that include (require) library chart with some common helpers (eg. fullname, image, etc.).

If I then create an umbrella chart and require all the above charts and in templates/_helper.tpl define a function with the same name as I have in the library chart (eg. "common.fullname") that other charts include, will that function overwrite all others with the same name required in other charts or not? As I understand, those helper names are global and we can use them in all sub-charts as log as one chart requires it?

**Comment by bacongobbler** [comment]
@strainovic let us know what you find out.

**Comment by strainovic** [comment]
@bacongobbler I think I've found PR that fixes this odd behavior.

https://github.com/helm/helm/pull/7702

It is released in version v3.3.0-rc1.

If you agree with me, you can close this issue.

Thanks!

**Comment by bacongobbler** [comment]
I don't have the time to look into this. but if you believe that this has been fixed in a later release, let's go ahead and close this. If this reappears with more recent versions of Helm, we can re-open. Thanks.
