### ISSUE TITLE
--kube-token flag on install command with GKE cluster

### ISSUE THREAD

**Issue by AdarShaked** [helm/helm#8735]
Output of `helm version`: version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE

im trying to install release on my gke cluster using --kube-token flag.
--kube-token should be Kubernetes service account token 
or OAuth 2.0 token ?

**Comment by bacongobbler** [comment]
From https://kubernetes.io/docs/reference/access-authn-authz/authentication/#option-2-use-the-token-option:

> The kubectl command lets you pass in a token using the --token option. Simply copy and paste the id_token into this option:

```
kubectl --token=eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL21sYi50cmVtb2xvLmxhbjo4MDQzL2F1dGgvaWRwL29pZGMiLCJhdWQiOiJrdWJlcm5ldGVzIiwiZXhwIjoxNDc0NTk2NjY5LCJqdGkiOiI2RDUzNXoxUEpFNjJOR3QxaWVyYm9RIiwiaWF0IjoxNDc0NTk2MzY5LCJuYmYiOjE0NzQ1OTYyNDksInN1YiI6Im13aW5kdSIsInVzZXJfcm9sZSI6WyJ1c2VycyIsIm5ldy1uYW1lc3BhY2Utdmlld2VyIl0sImVtYWlsIjoibXdpbmR1QG5vbW9yZWplZGkuY29tIn0
```

Which would imply it's a JWT bearer token from your service account.
