### ISSUE TITLE
Unable to install kafka-minion with TLS,getting following error

### ISSUE THREAD

**Issue by kalpita28** [helm/helm#8737]
Error: template: kafka-minion/templates/tls-secret.yaml:19:59: executing "kafka-minion/templates/tls-secret.yaml" at <b64enc>: invalid value; expected string

**Comment by kalpita28** [comment]
{{- if and (.Values.kafka.tls.enabled) (not .Values.kafka.tls.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kafka-minion.tlsSecretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "kafka-minion.name" . }}
    chart: {{ include "kafka-minion.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    {{- if .Values.extraLabels }}
    {{ toYaml .Values.extraLabels | nindent 4 }}
    {{- end }}
type: Opaque
data:
  tls.ca: {{ .Values.kafka.tls.certificates.ca | b64enc }}
  tls.key: {{ .Values.kafka.tls.certificates.key | b64enc }}
  tls.crt: {{ .Values.kafka.tls.certificates.certificate | b64enc }}
  passphrase: {{ .Values.kafka.tls.certificates.passphrase | b64enc }}
{{- end -}}

**Comment by bacongobbler** [comment]
Hi @kalpita28. As this issue pertains to a particular helm chart, please open an issue with the chart maintainers of kafka-minion. There's no action we can take here on our end.

Thanks.
