### ISSUE TITLE
Helm CLI completely ignores SemVer2 metadata when using --version for install and upgrade commands

### ISSUE THREAD

**Issue by WrzocHoo** [helm/helm#8739]
Hi,

I am experiencing weird behavior with `helm install/upgrade --version`. Looks like it does not support completely exact match on versions with provided metadata, example: `chart-0.1.2+v1` 

If there will be any other chart with the same _major.minor.patch_ version one of them will be picked **randomly**.
This is really weird and inconsistent behavior. 

With the following versions of chart in the repo: 
```
chart-0.1.2
chart-0.1.2+v1
chart-0.1.2+v2
```
when I execute `helm search --versions chart` couple times in a row, then I see that list is ordered randomly, and ordering differs between the calls.

Also if I supply version with metadata I would expect this exact one to be picked for installation and error about missing version if not exists, however:
- I could pass anything after `+` sign (even non-existing one), then helm will pick randomly one of the `X.Y.Z(|\+.*)` version for upgrade/install. This is weird.
- When I pass `X.Y.Z` version to `--version` it will also pick randomly one of the `X.Y.Z(|\+.*)`. This also is not normal.

Would it be possible to:
a) get constant ordering (alphabetical or whatever) on `helm search --versions` which will at least guarantee that using `helm upgrade chart repo/chart` command will not randomly pick some chart version.
b) if not `--version` maybe some other parameter `--strict-version` or whatever which will take into consideration `+metadata` part too.

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.16.10", GitCommit:"bceca24a91639f045f22ab0f41e47589a932cf5e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.10", GitCommit:"bceca24a91639f045f22ab0f41e47589a932cf5e", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2020-08-18T05:38:34Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2020-08-18T05:38:34Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
OpenShift 3.11

**Comment by bacongobbler** [comment]
I noticed that you’re using helm 2. At this point, we are no longer fixing bug reports for helm 2; only security fixes are accepted at this time.

That being said, if you can reproduce this issue with helm 3, we can start investigating further.

Thanks!

**Comment by bacongobbler** [comment]
On another note, this appears to make some sense. As per the Semver v2 specification on build metadata:

> Build metadata MUST be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence. Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85, 1.0.0+21AF26D3—-117B344092BD.

From https://semver.org/#spec-item-10.

So this appears to be correct behaviour. Neither version has precedence over the other.

That being said, I do know that there have been patches provided in the past for Helm to compare the version identifier exactly if no semver range is provided (like in your case with `helm install/upgrade --version chart-0.1.2+v1`).

However, because this is a duplicate of https://github.com/helm/helm/issues/7563, I'm going ahead and closing this as we've already got another ticket in the queue describing this bug, and we want to keep related discussions in one ticket.

Thank you for your report.
