### ISSUE TITLE
[Feature Req]: Add ignore resources flag to helm delete and upgrade

### ISSUE THREAD

**Issue by Champ-Goblem** [helm/helm#8740]
When upgrading or deleting a chart with `helm upgrade` or `helm uninstall` respectively it would be useful to have a flag to exclude either a set of resources or resource names from deletion. This is especially useful if perchance the chart created its own PVC/PV and you wish to retain the data for either use with another deployment or a change in the charts template values.

**Comment by bacongobbler** [comment]
https://helm.sh/docs/howto/charts_tips_and_tricks/#tell-helm-not-to-uninstall-a-resource?

**Comment by Champ-Goblem** [comment]
Ah thats perfect, thank you!
