### ISSUE TITLE
helm plugin blocked writing to /tmp/

### ISSUE THREAD

**Issue by mozai** [helm/helm#8743]
Output of `helm version`:
  This happens with both helm v2.14.3 and v3.3.0

Output of `kubectl version`:
  irrelevant

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
  irrelevant.

Steps to reproduce:
*  `touch /tmp/helm-diff.tgz`
*  `chmod 000 /tmp/helm-diff.tgz`
*  `helm plugin install https://github.com/databus23/helm-diff`

Expected results:
*  helm downloads the appropriate tarball, unpackages it, puts the contents in their places in $HOME/.helm/
*  helm removes the temporary file that was downloaded after using it

Seen instead:

    Warning: Failed to create the file /tmp/helm-diff.tgz: Permission denied
    curl: (23) Failed writing body (0 != 16360)
    Failed to install helm-diff

The "Steps to reproduce" are a contrived scenario, but I encountered it naturally when working on a machine I share with other users.  In my case, another user launched `helm plugin install` weeks before I did.

**Comment by mozai** [comment]
after removing /tmp/helm-diff.tgz I had more errors:

    tar: diff/LICENSE: Cannot open: File exists
    tar: diff/bin: Cannot utime: Operation not permitted
    tar: diff/plugin.yaml: Cannot open: File exists
    tar: diff/README.md: Cannot open: File exists
    tar: diff/bin/diff: Cannot open: File exists
    tar: diff: Cannot utime: Operation not permitted
    tar: Exiting with failure status due to previous errors
    Failed to install helm-diff

Similar cause as the original problem: it successfully downloaded to /tmp/helm-diff.tgz (preventing anyone else from doing the same on this machine) and it untars to /tmp/helm-diff/ which is still left-over from another user.

**Comment by bacongobbler** [comment]
This looks to be part of the helm-diff install script. Please open a ticket over at databuse23/helm-diff for support.

https://github.com/databus23/helm-diff/blob/0882d8c63d782cd5ac325fe3b4e00342ae30f6a1/install-binary.sh#L89
