### ISSUE TITLE
Helm repo add fails with some repositories

### ISSUE THREAD

**Issue by mate-szalai** [helm/helm#8761]
`helm repo add` fails with certain repositories when using Helm v3.3.2. The issue does not occur with v3.3.1 or earlier versions.

Example:

```
helm repo add jetstack https://charts.jetstack.io 
Error: looks like "https://charts.jetstack.io" is not a valid chart repository or cannot be reached: error unmarshaling JSON: while decoding JSON: json: unknown field "serverInfo"
```
The issue does not occur with every repository. For example, `https://kubernetes-charts.storage.googleapis.com/` can still be added:

```
helm repo add stable https://kubernetes-charts.storage.googleapis.com/
"stable" has been added to your repositories
```

Output of `helm version`:
```
version.BuildInfo{Version:"v3.3.2", GitCommit:"e5077257b6ca106d1f65652b4ca994736d221ab1", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-20T00:20:54Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

The issue was observed on both KIND and OpenStack clusters.

**Comment by bacongobbler** [comment]
Hey @mate-szalai. This is unfortunately one of the side effects of one of the security fixes.

In order to address one of the security issues, Helm now has to validate that the index.yaml file does not contain any extra fields, which chartmuseum does appear to add.

We're looking into this right now.

**Comment by bacongobbler** [comment]
See https://github.com/helm/helm/pull/8762.

**Comment by HaveFun83** [comment]
`helm repo update` is also effected on 3.3.2
```
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "grafana" chart repository
...Successfully got an update from the "codimd" chart repository
...Successfully got an update from the "ceph-csi" chart repository
...Successfully got an update from the "prometheus-community" chart repository
...Unable to get an update from the "jetstack" chart repository (https://charts.jetstack.io):
	error unmarshaling JSON: while decoding JSON: json: unknown field "serverInfo"
...
```

**Comment by hickeyma** [comment]
@HaveFun83 That is to be expected. PR #8762 will fix this also.

**Comment by jkroepke** [comment]
Helm 2.16.11 is affected, too.

**Comment by hickeyma** [comment]
@jkroepke Good call. I will push a backport PR for Helm 2 shortly.

**Comment by hickeyma** [comment]
@jkroepke #8764 pushed for Helm v2 fix.

**Comment by jkroepke** [comment]
Thanks

**Comment by antonsmelyanskiy** [comment]
This also fails now for Azure Container Registry helmcharts with: 
error unmarshaling JSON: while decoding JSON: json: unknown field "acrMetadata"

**Comment by mjrepo2** [comment]
I am experiencing this as well with both:
```
version.BuildInfo{Version:"v3.3.2", GitCommit:"e5077257b6ca106d1f65652b4ca994736d221ab1", GitTreeState:"clean", GoVersion:"go1.14.9"}

&

Client: &version.Version{SemVer:"v2.16.11", GitCommit:"73b28bab84490d18ab1b71489a574ee18e229eea", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.11", GitCommit:"73b28bab84490d18ab1b71489a574ee18e229eea", GitTreeState:"clean"}

```
Does anything need to be done on my side once a fix is pushed?

**Comment by hickeyma** [comment]
@mjrepo2 No, just the fix

**Comment by JamesLaverack** [comment]
Which change caused this issue? https://github.com/helm/helm/pull/8762 just refers to "A recent change merged into Helm fixes a number of security issues related to parsing malformed index files."

**Comment by mattfarina** [comment]
_Chart.yaml_ files have an `annotations` field. Would it make sense to add that to other places, such as the _index.yaml_ files so that people can have key/value pairs of their own?

**Comment by bridgetkromhout** [comment]
Hi, @SteveLasker-

Looks like ACR users are seeing unexpected side effects of a Helm security fix. We’ll want to get a change into ACR’s manifests to mitigate that.

*Why did this happen?*

Per the recent CNCF-sponsored security audit, the Helm maintainers needed to apply a security fix that enabled strict handling of YAML data in the Helm client.

*What is ACR doing right now that needs to be fixed?*

ACR is using an "acrMetadata" field Helm doesn't know about, instead of using the annotations field:

```
apiVersion: v1
entries:
 wordpress:
 - acrMetadata:
     manifestDigest: sha256:08ef434162070bba4256414c80b001d15b7503ef2a1a4fa1f60bab174f80d4d7
   appVersion: 5.1.0
   created: "2019-03-06T16:59:25.8892193Z"
```
 
*How can ACR fix things for users?*

Happily, Helm already has a provision for this kind of data: annotations is a set of string/string key value pairs. So the change required looks like this:

``` 
apiVersion: v1
entries:
 wordpress:
 - annotations
     acrMetadata: "manifestDigest: sha256:08ef434162070bba4256414c80b001d15b7503ef2a1a4fa1f60bab174f80d4d7"
   appVersion: 5.1.0
   created: "2019-03-06T16:59:25.8892193Z"
```

**Comment by bridgetkromhout** [comment]
Re-opening to track until ACR fix is in place.

**Comment by SteveLasker** [comment]
Looks like this is Helm 2 functionality. 
We'll see what we can do, but there's also a move to depreciate Helm 2 in lieu of Helm 3 registry support.

**Comment by bridgetkromhout** [comment]
Hi @SteveLasker - it appears this is also a problem in Helm 3, based on user reports.

**Comment by SteveLasker** [comment]
Based on the info, it's Helm 3, using the Helm 2 repo behavior that depends on charts.yaml which has lots of scalability problems. 
We'll take a look, but we'd really guide developers to move away from Helm 2 repo persistence as depending on how many charts they push for automated builds, they'll eventually fall over as everything is attempted to be represented in a single .yaml file. It was a great idea when there were a limited set of public charts. For users private usage, it's not a very scalable solution.

**Comment by squillace** [comment]
Hi Steve, it appears to be that ACR is/was rewriting an invalid index at some point (per https://github.com/helm/helm/issues/8761#issuecomment-694962864). `Per the recent CNCF-sponsored security audit, the Helm maintainers needed to apply a security fix that enabled strict handling of YAML data in the Helm client.` 

So I think what we're saying here is that ACR was invalidly munging indexes, and whereas before the security fix Helm was lax about it, now Helm is catching that invalid entry. Does that make sense? it's not immediately clear whether all or only some indexes are invalid and will bonk.... I think dapr is seeing this, for example (https://github.com/dapr/dapr/issues/2073).

**Comment by thomastaylor312** [comment]
I think @jdolitsky had an example of this. What I got from him in an offline chat: 

```
apiVersion: v1
entries:
  wordpress:
  - acrMetadata:
      manifestDigest: sha256:08ef434162070bba4256414c80b001d15b7503ef2a1a4fa1f60bab174f80d4d7
    appVersion: 5.1.0
    created: "2019-03-06T16:59:25.8892193Z"
```

That `acrMetadata` field isn't supposed to be in there and should be part of the `annotations` in a chart

**Comment by bacongobbler** [comment]
Quick update: for those using chartmuseum. charts.jetstack.io, codefresh, etc. Helm v3.3.3 is now available with a fix. Please upgrade to receive the fix.

https://github.com/helm/helm/releases/tag/v3.3.3

I've re-titled the issue to reflect the current state of things. We've tested v3.3.3 against a number of chart repositories, and they all sem to be working now. The only one that does not work currently is ACR.

**Comment by SteveLasker** [comment]
> Per the recent CNCF-sponsored security audit, the Helm maintainers needed to apply a security fix that enabled strict handling of YAML data in the Helm client.

It's a little unfortunate that this security fix didn't go through an embargo period to understand the impact and fix before it got rolled out. But, we are looking into it now as we do have a lot of usage. That said, to roll out a change to all Azure regions will take some time.

The `helm repo` behavior impacted here was an experiment that led to the [OCI Artifacts](https://github.com/opencontainers/artifacts) work.

As noted in our [ACR Roadmap](https://github.com/Azure/acr/blob/main/docs/acr-roadmap.md#acr-helm-ga), we do suggest users move to [Helm 3 Registry](https://helm.sh/docs/topics/registries/) support as it provides more scalability & reliability as all OCI compliant registries support this approach.

**Comment by SteveLasker** [comment]
A quick update.
Over the weekend, we've identified the issue and are evaluating the performance impact of options. 

- The impacted data is in `index.yaml` which is maintained by the registry as charts are pushed.
- We can either update the entire `index.yaml` for each registry or process the fix on request. As customers are automating their deployments, we see some customers with very large `index.yaml` files.

We recognize that customers use ACR for their private deployments of charts, and may not be able to simply re-push their charts.

We will have an update out shortly on our next steps. 
As with all software, testing a new version before deploying it is a best practice, so we hope this little "test" was a means for customers to recognize "friends don't let friends use `:latest` for any production workload :(
But, we recognize this is a real issue and we're doing what we can to solve it ASAP.
The most immediate solution is to not upgrade Helm until we identify when we can get this rolled out.

Apologies for issues this has caused customers,
Steve

**Comment by mattfarina** [comment]
> It's a little unfortunate that this security fix didn't go through an embargo period to understand the impact and fix before it got rolled out.

Last Friday I kicked off a conversation on creating an embargo period setup for security releases.

@SteveLasker if you want a project to have an embargo setup for security releases the appropriate way to discuss it is to request it. Complaining that it doesn't exist or that you are not on the list is an approach that usually doesn't win favor with open source project maintainers.

I would also suggest that the next time y'all are going to extend something with Helm it may be useful to ask about patterns in doing so upstream. We could provide some guidance and hopefully avoid issues like this in the future.

>  The most immediate solution is to not upgrade Helm until we identify when we can get this rolled out.

This is a somewhat scary option. ACR extended the `index.yaml` file rather than use the built-in `annotations` field at the same level as the extension. So, to avoid breaking the experience for your users due to a custom extension that no longer works (when there were other ways to approach this) you are suggesting people don't install a security update.

In the future, we are happy to help with Helm extension points (either in explaining them or discussing adding them). We would like to see ACR not end up in a broken situation where you're telling people not to apply a Helm security release.

**Comment by SteveLasker** [comment]
@mattfarina, the security notification process is a good one.
In this case, the maintainers of Helm knew there were usages of helm repos and we had worked with the team on the incubation of acr helm support, and ultimately the creation of the OCI Artifact approach, now supported in multiple cloud providers. To say the team didn't know is disingenuine. To engage in a CNCF security audit, have an outcome that requires a change, and not proactively reach out to various cloud providers who have security processes and other implementors of the technology is big miss.
We're all human, and we learn from our mistakes. Are we willing to recognize that?

The fact that we used an annotation that was malformed is a bug, and we're actively working to fix it, but this [behavior has been in place and working for 2 years](https://azure.microsoft.com/en-us/blog/azure-container-registry-public-preview-of-helm-chart-repositories-and-more/). Being a bit more proactive on testing and understanding the impact of a security change is something to consider.

The situation customers are in is:
- helm rolled out a change without testing or notifying known usages
- Customers are now broken. They have a choice to roll back to a stable version, compatible with their environment or remain broken until we can get the fix rolled out to all regions. Should customers be blocked from doing deployments, which may have other security fixes?

We have a fix and will roll out following [Azure Safe Deployment Practices](https://azure.microsoft.com/en-us/blog/advancing-safe-deployment-practices/). 
As we have precise timelines, we'll post here.

**Comment by SteveLasker** [comment]
Hey folks,
An official update, with some learnings applied:
- The ACR engineering team is validating a fix that has been deployed for canary testing on September 22, 2020
- Assuming testing goes as expected, following Azure safe deployment practices, regional deployments will start September 23, 2020
- Deployments should complete by the start of business, Monday, September 28, 2020 - please check [here](https://aka.ms/acr/advisories) for final confirmation and status updates.

## Learnings:
- We have provided full insight into the issue and learnings we're applying to an [ACR Advisories](https://aka.ms/acr/advisories) page
- We also encourage the Helm community to [weigh in on your views on how security notifications should be handled by Helm](https://github.com/helm/community/issues/128) and other CNCF projects.

**Comment by SteveLasker** [comment]
A quick update for those tracking.

### ACR Helm Repo Security Advisory

|Date | Status |
|-|-|
| September 24, 2020| Active - in-deployment |
| September 22, 2020| Active - testing solution |
| September 18, 2020 | Identified |

Full details at: [ACR Helm Repo Security Advisory](https://github.com/Azure/acr/edit/main/notifications/helm-repo-failure-20200918-.md)

**Comment by Dunning-Kruger** [comment]
> Full details at: [ACR Helm Repo Security Advisory](https://github.com/Azure/acr/edit/main/notifications/helm-repo-failure-20200918-.md)

@SteveLasker Broken link, since it's `/edit`

**Comment by SteveLasker** [comment]
Woops, thanks DK. Fixed now. 
I'll confirm the rollout is complete for Azure Commercial cloud regions shortly.

**Comment by SteveLasker** [comment]
Engineering has confirmed Azure Public/Commercial is complete.
Azure China and Azur Gov clouds will rollout over the next two days.
I'll update the [ACR Helm Repo Security Advisory](https://github.com/Azure/acr/blob/main/notifications/helm-repo-failure-20200918-.md) shortly

**Comment by SteveLasker** [comment]
@mate-szalai, I believe this issue should be closed as rollouts are complete. 
I'd also respectfully ask the title be changed back to "Helm repo add fails with some repositories" as this was unique to ACR, but did help users find the issue to track the status. 

Thanks,
Steve

**Comment by mate-szalai** [comment]
@SteveLasker, I changed the title back and closing this now. 

If the Helm maintainers wish the make changes to the issue, please feel free to do so.
