### ISSUE TITLE
Feature: add values deprecation management to helm

### ISSUE THREAD

**Issue by olivier-jobert** [helm/helm#8766]
In our use of helm, we have created a chart that use values that can be **modified** and/or **deleted** during chart development. This happens because we can be led to modify the functioning of our chart or because values are no longer necessary for example.

We would therefore like to have the possibility to warn the users of our chart that some of the values used are deprecated and will be deleted in the near future.

For the moment we have put this information in the NOTES.txt for the user to have direct feedback. This has also required the addition of value checking to display the message only if deprecated values are used. In fact, we are not sure it's the best place to put these informations and users could miss them.

Would it be possible to add a native deprecated value management mechanism to helm allowing:
* to indicate for each dict value if its deprecated
* to inform the user by stdout ([WARN]) during helm install/upgrade if some deprecated values were used
* to customize displayed message to invite the user to update its values

Thanks

**Comment by bacongobbler** [comment]
I think a combination of notes and a JSON Schema to validate values would go a long way here. You can use the `description` fields in the JSON Schema to also note which fields plan to be deprecated in future iterations.

https://helm.sh/docs/faq/#validating-chart-values-with-jsonschema
http://json-schema.org/learn/getting-started-step-by-step.html

**Comment by olivier-jobert** [comment]
Thanks, we also already use JSON schema validator, we will take a look at `description` field

**Comment by ohkinozomu** [comment]
It would be useful to be able to detect "deprecated" annotations that have appeared since draft 2019-09.
http://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.9.3

Perhaps one of the barriers is that xeipuuv/gojsonschema does not support draft 2019-09.
https://github.com/xeipuuv/gojsonschema/issues/289

**Comment by reitzig** [comment]
I opened #10732 for this.
