### ISSUE TITLE
helm repo add now fails in v3.3.2 and v3.3.3

### ISSUE THREAD

**Issue by darkn3rd** [helm/helm#8771]
### Description

The command **`helm repo add <name> <url>`** fails as it is no longer idempotent.  This worked fine in version `v3.3.1` and earlier.  It now fails in `v3.3.2` and `v3.3.3`.  This is a breaking change that has broken automation relying on `helm` and tools `helmfile`.

### Steps  to Reproduce

```bash 
helm repo add jaegertracing https://jaegertracing.github.io/helm-charts
helm repo add jaegertracing https://jaegertracing.github.io/helm-charts
```

### Expected Results

```
"jaegertracing" has been added to your repositories
```

I expected that the command would be idempotent and would not fail.  As the repository was already added, it would not need to be added again, and thus should to exist with an error.

### Actual Results

Despite the repository already in the desired state, helm exits with an error, even though there is no error.  `helm` will exit with `1` indicated an error.  This destroys any automation scripts and tools like `helmfile` to function correctly.

```
Error: repository name (jaegertracing) already exists, please specify a different name
```

Output of `helm version`:
```
version.BuildInfo{Version:"v3.3.3", GitCommit:"55e3ca022e40fe200fbc855938995f40b2a68ce0", GitTreeState:"dirty", GoVersion:"go1.15.2"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T23:30:39Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

* EKS (K8S `v1.17.9-eks-4c6976`)

**Comment by yxxhero** [comment]
@darkn3rd 
```
You can add --force-update option when run helm repo add.
```

**Comment by bridgetkromhout** [comment]
Hi, @darkn3rd - as explained in https://github.com/helm/helm/releases/tag/v3.3.2: 

> One breaking change was made: The default behavior of helm repo add was changed: It no longer overwrites repositories by default. The flag --force-update was added to helm repo add to allow a repo to be overwritten. The flag --no-update still exists, but does nothing. This change accords with the Helm policy for allowing minor breaking changes in the name of security.

**Comment by darkn3rd** [comment]
@bridgetkromhout I saw that comment shortly after I wrote this.  This can be both secure and idempotent at the same time.  Both of these are not mutually exclusive.  Simply, if the repo exist, don't do anything, don't error when there is no error, as this breaks things.  

Upstream automation and tools, such as `helmfile`, now fail.

**Comment by darkn3rd** [comment]
@yxxhero Thanks for the tip.  I can do that to return to the behavior, but then in `v3.3.1` and earlier, doing that will cause this:
```bash
$ helm repo add --force-update jaegertracing https://jaegertracing.github.io/helm-charts
Error: unknown flag: --force-update
```
This will break upstream automation and tools like `helmfile`, as now they'll have to test the version of helm and mutate the behavior.

Helm should just not do anything if the repo already exists, not create an error where no error.  If it was idempotent, it would also be secure in that manner, and the behavior as far as being in the desired state, would be similar.  The behavior would not break things.  The `--force-update` for other use cases, but for my use case, I just need the *not updating a repo* to not exit with an error, because there's no error.

**Comment by darkn3rd** [comment]
Just wanted to add this behavior violates the principal of least surprise, as it diverges from the behavior inherent with countless other package managers that are idempotent in this aspect: chocolatey, homebew, apt-get, yum, emerge, ports, aur, pacman, etc.

**Comment by Xtigyro** [comment]
Absolutely agree with @darkn3rd - it was even released as a bug-fix. We can do better!

**Comment by bacongobbler** [comment]
Hmm... We could just return exit code zero if the same repo is attempted to be added twice. Since it isn’t changing the information that’s already there, that should resolve the issue without working around the security controls we had to put in place

What do you think about that?

**Comment by darkn3rd** [comment]
That would work.

**Comment by bacongobbler** [comment]
Noted. Thanks for the feedback.

**Comment by mattfarina** [comment]
First, let me apologize for the lack of breaking change being bubbled up. It was noted on the pull request to fix the security issue (the only time we will intentionally make a breaking change is security issues) but we missed bubbling it up.

Second, I put up a PR to fix this issue at #8777. Can you please take a look and see if this will work.

**Comment by mattfarina** [comment]
I am tentatively marking this as a bug.

**Comment by darkn3rd** [comment]
Thank you all for supporting this. ❤️
