### ISSUE TITLE
`make test` failed: "t.Cleanup undefined"

### ISSUE THREAD

**Issue by lemonli** [helm/helm#8774]
Output of `helm version`:
master branch, last commit is https://github.com/helm/helm/commit/467bd49bb0cb0d613e802c738a0e38225eec054a

make test output
`WARN [runner] Can't run linter goanalysis_metalinter: deadcode: analysis skipped: errors in package: [/Users/davinli/go/src/helm.sh/helm/v3/cmd/helm/dependency_build_test.go:27:2: could not import helm.sh/helm/v3/pkg/repo/repotest (/Users/davinli/go/src/helm.sh/helm/v3/pkg/repo/repotest/server.go:42:4: t.Cleanup undefined (type *testing.T has no field or method Cleanup))]
WARN [runner] Can't run linter unused: buildssa: analysis skipped: errors in package: [/Users/davinli/go/src/helm.sh/helm/v3/pkg/repo/repotest/server.go:42:4: t.Cleanup undefined (type *testing.T has no field or method Cleanup) -: could not load export data: no export data for "helm.sh/helm/v3/pkg/repo/repotest"]
ERRO Running error: buildssa: analysis skipped: errors in package: [/Users/davinli/go/src/helm.sh/helm/v3/pkg/repo/repotest/server.go:42:4: t.Cleanup undefined (type *testing.T has no field or method Cleanup) -: could not load export data: no export data for "helm.sh/helm/v3/pkg/repo/repotest"]
make: *** [test-style] Error 3
`

My Go version is 1.13

While T.CleanUp is new in Go v1.14 https://tip.golang.org/pkg/testing/#T.Cleanup,  https://github.com/helm/helm/blob/master/go.mod#L3 is outdated?

**Comment by bacongobbler** [comment]
Please update to a more recent version of Go. t.Cleanup is a feature introduced in Go 1.14.

See https://github.com/helm/helm/blob/master/.circleci/config.yml#L8

Good catch on the go.mod file. I assume we can update that. But based on the outcome of CI, that field does not appear to affect anything.

**Comment by mattfarina** [comment]
@lemonli FYI, Go 1.13 is no longer a supported version of Go by the Go community. Helm should compile against all the supported versions of Go.
