### ISSUE TITLE
Warning after upgrading to 3.3.3

### ISSUE THREAD

**Issue by pieterv-icloud-com** [helm/helm#8776]
Output of `helm version`:

version.BuildInfo{Version:"v3.3.3", GitCommit:"55e3ca022e40fe200fbc855938995f40b2a68ce0", GitTreeState:"dirty", GoVersion:"go1.15.2"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Rancher

After upgrading to helm 3.3.3 we are getting the following warning when doing the following helm upgrade:

helm upgrade --namespace cib-k8-magic-dev --install --values /workspace/3/s/dotnet-core/deployment/charts/hello-world-api-values.yaml --set replicaCount=3,support.contact=Support Contact,support.url=Support Email,snowCorrelationId=SNOWCORRELATIONID,smoketest.repository=harbor.intra.absa.co.za/base/appropriate/curl,image.repository=harbor.intra.absa.co.za/k8-magic/hello-world-api,image.tag=0.0.513,ingress.enabled=true,ingress.hosts[0].host=hello-world-api.cib-k8-magic-dev.cib-fx.sdc-nonprod.caas.absa.co.za,connectionstring=*** --wait --version 0.0.513 hello-world-api hello-world-api/hello-world-api --version 0.0.513

The upgrade works, but there appears to be a YAML Exception:

2020-09-21T09:09:27.4439528Z WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /workspace/_temp/helmTask/1600679351732/config
2020-09-21T09:09:27.4441316Z WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /workspace/_temp/helmTask/1600679351732/config
2020-09-21T09:09:27.4448265Z Release "hello-world-api" has been upgraded. Happy Helming!
2020-09-21T09:09:27.4449053Z NAME: hello-world-api
2020-09-21T09:09:27.4449483Z LAST DEPLOYED: Mon Sep 21 09:09:13 2020
2020-09-21T09:09:27.4450244Z NAMESPACE: cib-k8-magic-dev
2020-09-21T09:09:27.4450650Z STATUS: deployed
2020-09-21T09:09:27.4450998Z REVISION: 396
2020-09-21T09:09:27.4451239Z TEST SUITE: None
2020-09-21T09:09:27.4451431Z NOTES:
2020-09-21T09:09:27.4451685Z 1. Get the application URL by running these commands:
2020-09-21T09:09:27.4452239Z   http://hello-world-api.cib-k8-magic-dev.cib-fx.sdc-nonprod.caas.absa.co.za
2020-09-21T09:09:27.8731222Z ##[warning]Capturing deployment metadata failed with error: YAMLException: incomplete explicit mapping pair; a key node is missed at line 1, column 85:
     ... able. This is insecure. Location: /workspace/_temp/helmTask/1600 ...

**Comment by mattfarina** [comment]
The warning is to fix a security finding that will be shared in the coming weeks. We are giving people time to upgrade before we release the report from the recent security analysis.

I don't know if you can share but, I'm wondering if this helm command is being run in CI tooling. This looks similar to azure pipelines. If you can share, are you using that or GitHub Actions? I'm curious if the warning at the bottom is due to one of those systems.

**Comment by ndegory** [comment]
The warnings are welcome, but they break any code that was parsing the helm version output. It can now include extra warning lines in the stdout. Moving them to stderr would make it easier to handle.

**Comment by bacongobbler** [comment]
@ndegory would you mind pointing out which error messages are being displayed on stdout? We'd be happy to fix that up.

**Comment by bacongobbler** [comment]
I found the kube config error messages were displayed on stdout. See https://github.com/helm/helm/pull/8779 for the fix.

**Comment by jkopacze** [comment]
I can confirm this warning are being appended to stdout with rest of the tamplate, which is currently breaking or CI flow displaying `helm diff`.

Result looks like this:

`   ...
    - host: xxxx.com
      http:
        paths:
          - path: /
            backend:
              serviceName: xxxx-com
              servicePort: 8080

WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/xxx/.kube/xx-xxx.yaml
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/xxxx/.kube/xx-xxx.yaml
Error: plugin "diff" exited with error
`

**Comment by mattfarina** [comment]
@jkopacze I expect #8779 to fix this, be merged, and released this week. There are a few things we'll release in a patch fix to get people moving. Sorry for the inconvenience. Fixing up security issues to come out of a security analysis, where there are numerous things, isn't always easy and straight forward.

**Comment by pieterv-icloud-com** [comment]
So this is occcurring on a Azure DevOps YAML pipeline, we had to implement code to strip out the warning messages.

Just a note on running these pipelines in diagnostic mode, a --debug is then added to the helm command and the output is written to error, when the helm task evaluates the output it will always fail.

**Comment by xolott** [comment]
I'm also finding this warnings on my ansible playbook (using helm module from community-kubernetes plugin) . This playbook retrieves the credentials from AKS and save it in the current folder (NTFS partition, so no UNIX permissions are possible).

This warning is catch up by ansible as an error, so the playbook is stoped.

This is breaking my CI/CD pipeline.

**Comment by mattfarina** [comment]
I apologize for the issues people are seeing. I expect a release with this issue fixed within the next 24 hours.

**Comment by MrAmbiG** [comment]
We have the version 3.3.4, all our pipelines are in trouble and local usage of helm too is breaking.

**Comment by bacongobbler** [comment]
Hi @MrAmbiG. So sorry to hear that. Please open a new ticket with a report on the issues you are seeing as well as a way we can attempt to reproduce the issue. Thanks.

**Comment by bacongobbler** [comment]
To close out this ticket...

Your `~/.kube/config` should only be readable by the current user, not the group/world. Use `chmod` to change the file's read/write permissions.

A good set of permissions would be to only allow the current user read/write permissions. `chmod u=rw ~/.kube/config` will accomplish that.

```
><> ls -al ~/.kube/
total 20
drwxr-xr-x  3 bacongobbler bacongobbler 4096 Dec  1 09:43 .
drwxr-xr-x 23 bacongobbler bacongobbler 4096 Dec  9 13:18 ..
drwxr-x---  4 bacongobbler bacongobbler 4096 Nov 10 10:32 cache
-rw-------  1 bacongobbler bacongobbler 5514 Dec  1 09:43 config
```

To demonstrate, I'll make the file group-readable, then world-writeable. Then show how to remove those permissions.

```
><> chmod g+r ~/.kube/config
><> helm version
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/bacongobbler/.kube/config
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
><> chmod o+r ~/.kube/config
><> helm version
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/bacongobbler/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/bacongobbler/.kube/config
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

Notice the change in permissions:

```
><> ls -al ~/.kube/config
-rw-r--r-- 1 bacongobbler bacongobbler 5514 Dec  1 09:43 /home/bacongobbler/.kube/config
```

To remove those permissions, use the inverse:

```
><> chmod o-r ~/.kube/config
><> chmod g-r ~/.kube/config
```

A more compact version would be

```
><> chmod go-r ~/.kube/config
```

Hope that helps.

**Comment by nick4fake** [comment]
@bacongobbler this obviously wouldn't work for cases where you can't change permissions (like ntfs volumes with WSL) or any network fs mounts. Is there a real work-around to completely disable this warning? Like --ignore-permissions

**Comment by whereisaaron** [comment]
This version is unusable on WSL as @nick4fake says due to these faulty warning. NTFS user permissions are not visible to `helm` so it can't accurately work out that the `config` file is indeed restricted to only the user (which it is). `helm` thus gets it wrong and constantly displays incorrect information to the user or logs false positives on every invocation. If `helm` is not filesystem aware, then there should be a config file option to disable this erroneous warning.

**Comment by whereisaaron** [comment]
For others getting false positives from these warnings, I checked [the patch](https://github.com/helm/helm/commit/82398667dfe208407be9fe499ac96240aa8ce54b) and it appears to has no configuration file option to disable it. Right now your only option is to downgrade to 3.3.1 or 3.2.4 (latest 3.2.x) until there is a fix for the false positives. It is sensible to have checks like this, but if they are not reliable there also needs to be a way to disable them.

**Comment by Imunhatep** [comment]
Well thanks, but no..  I didn't asked for security advice! Mind your (helm) business please.

**Comment by deesejohn** [comment]
@nick4fake and @whereisaaron, did either of you ever find a good work around for WSL?

**Comment by bacongobbler** [comment]
To be clear, will not accept PRs to suppress the security warning. This issue was pointed out by a security audit sponsored by the CNCF, and the warning was the security team’s recommendation.

However, if there are ways where we can identify that a) the kubeconfig is mounted in an NTFS drive, and b) permissions are indeed restricted to the user, we would welcome PRs that would address this case to remove the warning.

**Comment by elkbullwinkle** [comment]
Kube config does not always contain sensitive credentials, for example in case where authenticating using aws cli. Besides kubectl itself does not produce a warning.

**Comment by mrsiejas** [comment]
How to suppress this warning? I'm using AWS CDK with Lambda and getting this error which causes the CDK stack deployment to fail. 

```1:40:52 PM | UPDATE_FAILED        | Custom::AWSCDK-EKS-HelmChart          | FluentBit/Resource/Default
Received response status [FAILED] from custom resource. Message returned: Error: b'WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /tmp/kubeconfig\nWARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /tmp/kubeconfig\nError: release name is in
valid: fluent/fluent-bit\n'

Logs: /aws/lambda/integration-eks-cluster-awscdkawse-Handler886CB40B-1BNX6NZIHY5GW

at invokeUserFunction (/var/task/framework.js:95:19)
at process._tickCallback (internal/process/next_tick.js:68:7) (RequestId: 8d08f560-71b7-4bab-be15-1d2396ccf745)
1:40:54 PM | UPDATE_ROLLBACK_IN_P | AWS::CloudFormation::Stack            | integration-elasticsearch
The following resource(s) failed to update: [FluentBit532C5947].
```

**Comment by mrsiejas** [comment]
@bacongobbler warning also causes AWS CDK to fail stack deployments via Lambda. We should be able to suppress this warning message.

```
7:34:35 AM | CREATE_FAILED        | Custom::AWSCDK-EKS-HelmChart          | FluentBit/Resource/Default
Received response status [FAILED] from custom resource. Message returned: Error: b'WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /tmp/kubeconfig\nWARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /tmp/kubeconfig\nError: UPGRADE FAILED:...```

**Comment by manju4d90** [comment]
changing permissions for kubeconfig in .kube dir to readonly will solve this warning.

**Comment by mrsiejas** [comment]
> changing permissions for kubeconfig in .kube dir to readonly will solve this warning.

It won't if someone is using CDK or other higher level tools. I mentioned CDK which uses Lambda to run `kubectl` on clusters, we should not change the CDK defaults and want to avoid dirty hacks to bypass this questionable warning.

Working with CDK team to fix this on their side:
https://github.com/aws/aws-cdk/issues/14560

**Comment by rayfoss** [comment]
Got this error in a gitlab.com runner... Obviously it was misleading, and not the actual cause of the exit code and pipeline fail. The real error was all the way at the bottom, a yaml validation error.

```
EXIT STATUS
  1
STDERR:
  WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /builds/tdps/learn-cluster.tmp/KUBECONFIG
  WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /builds/tdps/learn-cluster.tmp/KUBECONFIG
  Error: Failed to render chart: exit status 1: WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /builds/tdps/learn-cluster.tmp/KUBECONFIG
  WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /builds/tdps/learn-cluster.tmp/KUBECONFIG
  Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Service.spec.ports[0]): missing required field "port" in io.k8s.api.core.v1.ServicePort
  Error: plugin "diff" exited with error
COMBINED OUTPUT:
  WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /builds/tdps/learn-cluster.tmp/KUBECONFIG
  WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /builds/tdps/learn-cluster.tmp/KUBECONFIG
  Error: Failed to render chart: exit status 1: WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /builds/tdps/learn-cluster.tmp/KUBECONFIG
  WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /builds/tdps/learn-cluster.tmp/KUBECONFIG
  Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Service.spec.ports[0]): missing required field "port" in io.k8s.api.core.v1.ServicePort
  Error: plugin "diff" exited with error
```

**Comment by white-hat** [comment]
By forcing these warnings you actually degrade security in many use cases. For example, K8s for some reason does not allow to mount secrets as non-root user, and with this "security feature" of yours you are forcing us to run containers as root only to suppress this warning message.

**Comment by white-hat** [comment]
I quick workaround
```bash
#!/bin/bash

helm "${@}" 2> >(grep -v 'This is insecure' >&2)
```

usage:
```
~/.../k8s/helm-janitor > helm ls -ojson
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: k8s/janitor-1
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: k8s/janitor-1
[{"name":"traefik","namespace":"kube-system","revision":"1","updated":"2021-12-15 06:51:47.500771 +0000 UTC","status":"deployed","chart":"traefik-9.18.201","app_version":"2.4.8"},{"name":"traefik-crd","namespace":"kube-system","revision":"1","updated":"2021-12-15 06:51:45.8324199 +0000 UTC","status":"deployed","chart":"traefik-crd-9.18.201","app_version":""}]
~/.../k8s/helm-janitor > ./better_helm ls -ojson
[{"name":"traefik","namespace":"kube-system","revision":"1","updated":"2021-12-15 06:51:47.500771 +0000 UTC","status":"deployed","chart":"traefik-9.18.201","app_version":"2.4.8"},{"name":"traefik-crd","namespace":"kube-system","revision":"1","updated":"2021-12-15 06:51:45.8324199 +0000 UTC","status":"deployed","chart":"traefik-crd-9.18.201","app_version":""}]
```
