### ISSUE TITLE
svc type loadbalancer of redis-cluster helm deployment is getting duplicate IP from different cluster

### ISSUE THREAD

**Issue by goal86sg** [helm/helm#8783]
We are noticing, when we deploy a redis-cluster using this helm chart (https://hub.helm.sh/charts/bitnami/redis-cluster) we see a duplicate set of IP occurrence on 2 different k8s cluster

Cluster1
default       redis-ryan-redis-cluster            ClusterIP      10.100.200.214   <none>         6379/TCP                                                                                                   4d
default       redis-ryan-redis-cluster-0-svc      LoadBalancer   10.100.200.79    xx.x.202.34    6379:31122/TCP,16379:31330/TCP                                                                             4d
default       redis-ryan-redis-cluster-1-svc      LoadBalancer   10.100.200.60    xx.x.202.35    6379:31854/TCP,16379:30880/TCP                                                                             4d
default       redis-ryan-redis-cluster-2-svc      LoadBalancer   10.100.200.220   xx.x.202.33    6379:31676/TCP,16379:30743/TCP                                                                             4d
default       redis-ryan-redis-cluster-3-svc      LoadBalancer   10.100.200.195   xx.x.202.36    6379:30540/TCP,16379:30045/TCP                                                                             4d
default       redis-ryan-redis-cluster-4-svc      LoadBalancer   10.100.200.17    xx.x.202.37    6379:31245/TCP,16379:30785/TCP                                                                             4d
default       redis-ryan-redis-cluster-5-svc      LoadBalancer   10.100.200.85    xx.x.202.32    6379:32281/TCP,16379:31363/TCP                                                                             4d
default       redis-ryan-redis-cluster-headless   ClusterIP      None             <none>         6379/TCP,16379/TCP  

2nd cluster
default         redis-cluster                                  ClusterIP      10.100.200.184   <none>        6379/TCP                         20h
default         redis-cluster-0-svc                            LoadBalancer   10.100.200.169   xx.x.202.31   6379:31894/TCP,16379:31207/TCP   20h
default         redis-cluster-1-svc                            LoadBalancer   10.100.200.74    xx.x.202.34   6379:31479/TCP,16379:30005/TCP   20h
default         redis-cluster-2-svc                            LoadBalancer   10.100.200.200   xx.x.202.35   6379:32531/TCP,16379:32375/TCP   20h
default         redis-cluster-3-svc                            LoadBalancer   10.100.200.145   xx.x.202.33   6379:30955/TCP,16379:30108/TCP   20h
default         redis-cluster-4-svc                            LoadBalancer   10.100.200.104   xx.x.202.32   6379:32037/TCP,16379:30051/TCP   20h
default         redis-cluster-5-svc                            LoadBalancer   10.100.200.153   xx.x.202.26   6379:31305/TCP,16379:32287/TCP   20h
default         redis-cluster-headless                         ClusterIP      None             <none>        6379/TCP,16379/TCP               20h

Installation steps
helm install redis-cluster harbor/redis-cluster --set "cluster.externalAccess.enabled=true,global.redis.password=entityMS,networkPolicy.enabled=true"

helm upgrade redis-cluster --set "cluster.externalAccess.enabled=true,cluster.externalAccess.service.type=LoadBalancer,cluster.externalAccess.service.loadBalancerIP[0]=xx.x.202.33,cluster.externalAccess.service.loadBalancerIP[1]=xx.x.202.30,cluster.externalAccess.service.loadBalancerIP[2]=xx.x.202.34,cluster.externalAccess.service.loadBalancerIP[3]=xx.x.202.35,cluster.externalAccess.service.loadBalancerIP[4]=xx.x.202.32,cluster.externalAccess.service.loadBalancerIP[5]=xx.x.202.27,password=entityMS" harbor/redis-cluster

Any idea why? issit an issue with helm deployment or ncp with k8s? We further isolate the issue by doing a normal svc deployment using https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/ and there are no ip duplication of type loadbalancer object

Output of `helm version`:
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"be3d344ed06bff7a4fc60656200a93c74f31f9a4", GitTreeState:"clean", BuildDate:"2020-02-11T19:34:02Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
on prem PKS 1.7 with vSphere / NSXT 2.5.1

**Comment by bacongobbler** [comment]
Hi @goal86sg. As this relates to a particular chart, please open an issue with the maintainers of the redis-cluster chart (bitnami). This does not appear to be an issue with the Helm client. Thanks.
