### ISSUE TITLE
Potential unintended consequence of "use warning function" writing to stderr

### ISSUE THREAD

**Issue by danquah** [helm/helm#8793]
So not really a bug, more of a heads up.

When running one of our Azure DevOps Pipeline this morning, we suddenly got a failed pipeline where no code had changed. When looking in detail we discovered that the pipeline had picked up the latest version (3.3.4) of Helm. The release included an update in behaviour where warnings are now printed to stderr instead of std out: e5bd79f 

In our case, we started seeing this error:
```
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/<redacted>
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/<redacted>
```

The reason our task failed (The details of the particular task is not important in this context but its source is here for reference](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/HelmDeployV0/src/helm.ts)), was that the default in Azure DevOps pipeline tasks is to interpret output on stderr as errors and subsequently to fail the pipeline.

I'm not to say whether warnings from Helm should actually go to stderr or out. In our case the fix was just a matter of introducing a `failOnStderr: false` input into the task to change its behaviour when encountering stderr messages (the task is running in a sandbox where the group/world readable file is not a problem).

I suspect that devs out there running in to similar issues can work around it quite easily, and writing warnings to std-err is probably the way to got so that we don't get warning-messages mixed into the "real" output of Helm.

Just wanted to get the word out there quickly in case other people runs in to this issue and wonders about the cause.

**Comment by cherubic** [comment]
I meet the same problem today, finally I use specific version: 3.3.3 instead latest version, I don't want to close the failOnStderr option. 
I hope it will be fixed in next version.

**Comment by bridgetkromhout** [comment]
Hi, @danquah - yes, these messages were moved from stdout to stderr (discussed in https://github.com/helm/helm/issues/8776, which is why that commit you linked was made).

For others who may be looking at this, I noticed that https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/bash?view=azure-devops#arguments says:

```
failOnStderr               (Optional) If this is true, this task will fail if any errors are written to stderr.
Fail on standard error.    Default value: false
```

So I am very interested in where you found that the default is to fail, as that is not reflected in the docs? Thanks.

**Comment by mattfarina** [comment]
@danquah Thank you for raising this to us. This is useful to know about. I'm a little surprised that writing to stderr without a non-zero exit code would cause pipelines to exit with an error by default.

stderr, [as documented on Wikipedia](https://en.wikipedia.org/wiki/Standard_streams#Standard_error_(stderr)), is:
> Standard error is another output stream typically used by programs to output error messages or diagnostics. It is a stream independent of standard output and can be redirected separately.

It's not just for errors but also for diagnostics.

On to the issue at hand...

Trail of Bits performed a security analysis of Helm. The full report will be available in a few weeks. We are giving people an opportunity to upgrade Helm prior to the release of the report.

In this analysis one of the issues found was that Helm didn't warn users of file permission issues on important files. kubeconfig files provide sensitive information. ssh will refuse to work if its sensitive config has permission issues. [StackRox first chapter on protecting against Kubernetes threats](https://www.stackrox.com/post/2020/06/protecting-against-kubernetes-threats-chapter-1-initial-access/) deals with initial access. Getting access to ones credentials is a vector of attack. This is a security issue.

Helm writing this information to stdout doesn't follow the convention of diagnostics to stderr and it causes issues with features, like `helm template`. It should be written to stderr.

I'm open to suggestions. But, Helm needs to handle the security well, follow conventions like the use of stderr, and work for its features in general like `helm template` and piping.

**Comment by bacongobbler** [comment]
See https://github.com/microsoft/azure-pipelines-tasks/issues/13594 for the upstream bug report.

**Comment by danquah** [comment]
@bridgetkromhout you are 100% correct, I extrapolated just a bit too far from the task I encountered the problem with and now that I look more into it I have no idea why it failed in the first place. The documentation for the HelmDeploy task says nothing about `failOnStderr` but as far as I can tell from the sources it should have defaulted the field to false. 

@mattfarina 100% agree, warnings and error should go to stderr in order to keep the output clean and "pipeable". It's the exitcode that signfies whether the execution was successful or not.

I mostly opened this issue to inform others that went hunting for an explanation for errors they ran in to over their morning-beverage, so I'm good with just closing the "issue" for now?

**Comment by bridgetkromhout** [comment]
Hi, @danquah - I was looking at https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/HelmDeployV0/task.json#L433 and I think that's where the default is set. (My previous link was to a bash pipeline which I don't think is what you're using.) As mentioned above, we do have a bug report upstream, and I've commented with this detail: https://github.com/microsoft/azure-pipelines-tasks/issues/13594#issuecomment-697968904.

**Comment by danquah** [comment]
Ahhh, that explains why that one task (it's HelmDeploy) behaved differently from what I've seen with other tasks. Thanks for digging it up @bridgetkromhout!

I'll keep an eye on the upstream fix :)
