### ISSUE TITLE
Print shorter date notations when using helm ls

### ISSUE THREAD

**Issue by remcohaszing** [helm/helm#8794]
`helm ls` gives the following output:

```
$ helm ls
NAME                NAMESPACE  REVISION  UPDATED                                  STATUS    CHART              APP VERSION
review-1292-vq6732  review     1         2020-09-10 16:04:41.646382274 +0000 UTC  deployed  appsemble-0.13.13  0.13.13    
review-1359-i2leh9  review     1         2020-09-22 12:38:16.73325296 +0000 UTC   deployed  appsemble-0.13.15  0.13.15    
review-1373-0y7trv  review     1         2020-09-23 13:51:08.30934844 +0000 UTC   deployed  appsemble-0.13.15  0.13.15
```

At first I wanted to report an issue to not omit trailing zero’s in the updated datetime value, as the inconsistent clumn output triggers me. Then I concluded the information is not relevant. Helm deployments tend to take much longer than a nanosecond. I think it’s fair to round the time value to seconds. Also AFAIK the time zone is always `+0000 UTC`.

I propose to omit decimals from the seconds in the time format and omit `+0000` from the time zone offset, as `UTC` is clear enough. So the output of `helm ls` given the situation above would become:

```
$ helm ls
NAME                NAMESPACE  REVISION  UPDATED                  STATUS    CHART              APP VERSION
review-1292-vq6732  review     1         2020-09-10 16:04:41 UTC  deployed  appsemble-0.13.13  0.13.13    
review-1359-i2leh9  review     1         2020-09-22 12:38:16 UTC  deployed  appsemble-0.13.15  0.13.15    
review-1373-0y7trv  review     1         2020-09-23 13:51:08 UTC  deployed  appsemble-0.13.15  0.13.15
```

This fixes the weird looking column caused by rounding the second decimals, and makes the rows shorter, meaning they are more usable on smaller screens.

Alternatively the `UTC` part could be moved into the `UPDATED` label, making the output even narrower.

```
$ helm ls
NAME                NAMESPACE  REVISION  UPDATED (UTC)        STATUS    CHART              APP VERSION
review-1292-vq6732  review     1         2020-09-10 16:04:41  deployed  appsemble-0.13.13  0.13.13
review-1359-i2leh9  review     1         2020-09-22 12:38:16  deployed  appsemble-0.13.15  0.13.15
review-1373-0y7trv  review     1         2020-09-23 13:51:08  deployed  appsemble-0.13.15  0.13.15
```

**Comment by bridgetkromhout** [comment]
Related: https://github.com/helm/helm/issues/8352

**Comment by bacongobbler** [comment]
See also https://github.com/helm/helm/pull/7024.

**Comment by mattfarina** [comment]
@remcohaszing Thanks for the feedback. There are few things I can share...

First, in Helm v3 we can't change these date stamps as a default. Helm follows SemVer and the output from the Helm CLI is parsed and used by other scripts. That includes date parsing. A change by default would break them. We treat the output as an API.

Second, we want to change the dates for Helm v4.

Third, theoretically a data format flag could be passed to allow customizing the date.
