### ISSUE TITLE
helm test command has multiple problems

### ISSUE THREAD

**Issue by liubog2008** [helm/helm#8796]
Output of `helm version`: 3.2

Output of `kubectl version`: 1.19.2

Cloud Provider/Platform (AKS, GKE, Minikube etc.): local

Now `helm test` command has multiple problems

- [ ] Test hook kind can only be `Pod`. If `Job` is used, `--logs` will not work
- [ ] `--logs` is not realtime
- [ ] If delete policy is set to `hook-succeeded`, `--logs` will failed
- [ ] Have no way to cleanup test hook even manually
- [ ] Can't create some temp resources for test, e.g. Role, RoleBinding, ConfigMap

Related issues
#8342
#8018 
#6968
#8396

**Comment by bacongobbler** [comment]
Hi @liubog2008. Can you please comment on existing issues or create new issues if those don’t exist. Generally we try to avoid creating “meta” issues unless there’s one item of work that would solve multiple issues at once. From the looks of each issue listed here, they all appear to be related, but individual units of work.
