### ISSUE TITLE
helm cli '-v' option values undocumented and not sanity checked

### ISSUE THREAD

**Issue by schpliz** [helm/helm#8802]
I can find no documentation on what the possible set of values of the '-v' / '--v' option is or how those values are interpreted.
Only description is "number for the log level verbosity".  The -v option seems to accept any 32-bit integer (see below).
Is there a discrete set of **meaningful** values?

Output of `helm version`:
bash-3.2$ helm -v 2147483647 version
I0924 09:32:33.016840   56491 loader.go:375] Config loaded from file:  /Users/schpliz/.kube/config
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"dirty", GoVersion:"go1.15"}
bash-3.2$ helm -v -2147483648 version
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"dirty", GoVersion:"go1.15"}
bash-3.2$ helm -v 2147483648 version
Error: invalid argument "2147483648" for "-v, --v" flag: strconv.ParseInt: parsing "2147483648": value out of range
bash-3.2$ helm -v -2147483649 version
Error: invalid argument "-2147483649" for "-v, --v" flag: strconv.ParseInt: parsing "-2147483649": value out of range

Output of `kubectl version`:
N/A

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
N/A

**Comment by bacongobbler** [comment]
This flag is provided by kubectl. I do not see any documentation from Kubernetes documenting the verbosity levels. General rule of thumb is `-v 1` for regular verbosity (the default), and `-v 10` for HTTP-level traces.

We'd welcome documentation to provide more information as you discover its values.

**Comment by bacongobbler** [comment]
https://github.com/kubernetes/klog/blob/4f12f780d4781eb828bc6520ae87d7516f30f0b2/klog.go#L433

**Comment by schpliz** [comment]
Verbosity level (at least for this command) seems to change at  -v value > 5.
(I still don't think accepting any 32-bit integer value (especially negative) is good practice.)
```
bash-3.2$ ((i=0))
bash-3.2$ while (( $i < 13 )) ; do
> echo -ne "$i\t" ; helm -v $i version
> ((i++))
> done
0	version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"dirty", GoVersion:"go1.15"}
1	version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"dirty", GoVersion:"go1.15"}
2	version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"dirty", GoVersion:"go1.15"}
3	version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"dirty", GoVersion:"go1.15"}
4	version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"dirty", GoVersion:"go1.15"}
5	version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"dirty", GoVersion:"go1.15"}
6	I0924 10:02:29.126033   57627 loader.go:375] Config loaded from file:  /Users/schpliz/.kube/config
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"dirty", GoVersion:"go1.15"}
7	I0924 10:02:29.172078   57628 loader.go:375] Config loaded from file:  /Users/schpliz/.kube/config
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"dirty", GoVersion:"go1.15"}
8	I0924 10:02:29.217404   57629 loader.go:375] Config loaded from file:  /Users/schpliz/.kube/config
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"dirty", GoVersion:"go1.15"}
9	I0924 10:02:29.262338   57630 loader.go:375] Config loaded from file:  /Users/schpliz/.kube/config
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"dirty", GoVersion:"go1.15"}
10	I0924 10:02:29.307222   57631 loader.go:375] Config loaded from file:  /Users/schpliz/.kube/config
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"dirty", GoVersion:"go1.15"}
11	I0924 10:02:29.355061   57632 loader.go:375] Config loaded from file:  /Users/schpliz/.kube/config
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"dirty", GoVersion:"go1.15"}
12	I0924 10:02:29.401876   57633 loader.go:375] Config loaded from file:  /Users/schpliz/.kube/config
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"dirty", GoVersion:"go1.15"}
bash-3.2$ 
```

**Comment by bacongobbler** [comment]
@schpliz as noted earlier, this flag is provided by klog, which is an upstream Kubernetes project. So any fixes or enhancements to the verbosity flag will have to be made there.

https://github.com/helm/helm/blob/9b90e848ca659e147cae66dde9c16dcda578f113/cmd/helm/helm.go#L64-L70

As mentioned before, we are happy to document its behavior. But changes or improvements to the flag must be made upstream before we can observe those enhancements.

If you're looking to fix these issues, I'd urge you to open a ticket with the klog maintainers.

**Comment by schpliz** [comment]
Thanks, @bacongobbler.  I was just trying to "discover" if the value 10 that you suggested had any special significance, at least in this case.  (per your comment: "We'd welcome documentation to provide more information as you discover its values.")

Perhaps the documentation could differentiate between CLI options that apply to the `helm` command itself vs. those that are just "passed through" to sub process(es) - similar to how GCC offers -Wa, -Wp, -Wl, options for passing options directly to the assembler, preprocessor, linker and documents these accordingly.  That way users would have some indication that they need to look elsewhere.

Is there a way to get more info about what `helm` is doing as opposed to what K8s is doing?  Does `--debug` apply to `helm` or K8s ?

**Comment by bacongobbler** [comment]
`--debug` applies to Helm.

For the most part, Helm flags and kubectl flags are distinguished with a `--kube-` prefix. The flags provided by klog are the only exception to the rule I'm aware of.

**Comment by bacongobbler** [comment]
@schpliz is this something you're interested in documenting?
