### ISSUE TITLE
Cannot remove chart from list because of sliced ref name and ... added at the end

### ISSUE THREAD

**Issue by diwap** [helm/helm#8805]
__Helm version__: ```version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}```

__Kubectl version__: ```Client Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T19:00:19Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}```

__Helm Client installed OS__: Centos 7

Cloud Provider/Platform : EKS

I accidentally created a chart with character longer than 61. Now I want to remove that chart from the list but just cannot do that.
For example:
```
REF                                                             NAME    VERSION DIGEST  SIZE    CREATED 
/home/centos/sample_chart_example/kubernetes/eks_tested/l...    elk     1.0.0   12345a7 959 B   21 hours
```

Now to delete this chart, I ran command `helm chart rm /home/centos/sample_chart_example/kubernetes/eks_tested/l...` which obviously won't work and will send error `Error: Chart not found`. I don't know the full directory path cause I have already deleted chart.

Looking around for a little while, I got the full ref name from registry cache which is located in `~/.cache/helm/registry/cache/index.json` in CentOS [(reference for other)](https://helm.sh/docs/helm/helm/). Using that name I deleted the chart which worked for me.
However, I still think this is an issue that should be fixed and I should have some solution to get full ref name instead of sliced one.

**Comment by mattfarina** [comment]
@diwap Thanks for bringing this up. I wanted to let you know that there is a redesign effort for the chart with OCI registries underway. You can find the design details at https://github.com/helm/community/pull/136. Once this is in and tested I expect we can drop the experimental flag. Wanted to let you know that this area is likely going to change.
