### ISSUE TITLE
Introduce verbose output

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#8809]
Helm currently has it's normal output and output with `--debug` messages. This is a proposal to introduce another level between normal and debug output.

kubectl, using klog, has the ability to set a verbosity level. This level is not clearly defined so users have to work it out. But, there are multiple levels. I wouldn't recommend we have that experience.

Homebrew, the mac package manager, has two levels. `--verbose` and `--debug` that can be layered on to the normal output. Verbose prints more information about what's happening while debug prints details you'd need if you want to debug something.

This feature request suggests the same idea for Helm. For example, if you used `--verbose` on `helm install` it would tell you what's happening as it locates the chart, downloads it, renders the templates, pushes them, etc. I wouldn't need to give lots of internal values and details that debug should supply.

Thoughts?

**Comment by ibuildthecloud** [comment]
The level of output I'd like to see is for helm to log any action it specifically takes.  For example, CRUD resource, run hook, wait for objects.  The specific use case I would need this for is building UIs around helm in which I'm installing a chart and want to give some level of output to the user to indicate things are progressing.  Right now, correct me if I'm wrong, nothing it printed until the chart is installed and then notes are outputted.  So if --wait is passed this is a long delay of no output.

**Comment by object88** [comment]
Seems like a step in the right direction.  I have a project that deploys an "umbrella" chart, and (by no fault of helm) it takes a long time to complete.  It would be helpful for helm to share information along the lines of "found the chart", "kubernetes has updated the resources, just waiting for them to align", and "yep, all done, thanks".

**Comment by Aiosa** [comment]
I would welcome `--verbose` too. It is also the first argument I try before running into 'help' failure output and consulting the docs. A lots of user-irrelevant content. If it printed the line it finds error on, it would help a lot too since line numbers usually do not match with bigger projects that use some advanced templating...
