### ISSUE TITLE
What's the best solution for sub-charts get access to overridden values applied to the parent charts using flags --values values.yaml

### ISSUE THREAD

**Issue by Saewo0** [helm/helm#8820]
Output of `helm version`: version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}

Currently, my chart has a structure like this:

service-A/
    charts/
        service-B/
            templates/
                service-b-deployment.yaml
            service-b-values.yaml
    service-a-values.yaml

the command I am using to deploy service-A is:

`helm3 upgrade --debug service-A --values values_overridden.yaml`

```
service-b-deployment.yaml:
...
    containers:
      - name: {{ .Chart.Name }}
         image: {{  .Values.common.imageRepository }}/prometheus-adapter
...

values_overridden.yaml:
common:
  imageRepository: localhost
```
The problem is that subcharts cannot get access to any values defined in `values_overridden.yaml`.

I know I can set a section in `service-a-values.yaml` to push values to subcharts like:
```
service-a-values.yaml:
service-B:
  common:
    imageRepository: localhost
```
but how can I reference overridden values in `service-a-values.yaml`?

I have gone through many resources talking about the solutions for this problem, but none of them gives an accurate and functional way. Does anyone have any suggestions?

**Comment by mattfarina** [comment]
Did you see https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#overriding-values-from-a-parent-chart in the documentation? Does that help?

**Comment by Saewo0** [comment]
No, it doesn't help.
Just as I said, I know I can set a section for a sub-chart in its parent's value.yaml to push these values to child charts. However, my problem is not overriding values from a parent chart, I am trying to override child chart values using --values flag while installing the parent chart.

**Comment by bacongobbler** [comment]
Hi @Saewo0. I'm having a difficult time trying to understand what you are attempting to achieve. More specifically:

> The problem is that subcharts cannot get access to any values defined in `values_overridden.yaml`.

> I am trying to override child chart values using --values flag while installing the parent chart.

That sounds a lot like what @mattfarina mentioned. Perhaps there's some miscommunication occurring here and you're looking for some other answer?

With the following `values_overridden.yaml`:

```
service-B:
  common:
    imageRepository: localhost
```

That will override child chart values using the `--values` flag. It will not override values in the parent chart.

> but how can I reference overridden values in service-a-values.yaml?

This is a separate, discrete, problem. There is no way to look up values set at different levels. You are just passing a set of values, which are all merged in a particular order, and the template engine is left to render the templates using the merged set of values. You cannot "look up" prior values set a few levels lower. Have a look at the reasoning provided in 

Does https://helm.sh/docs/topics/charts/#importing-child-values-via-dependencies or the proposal in #7477 help at all? Those are in the opposite direction (from child to parent), but I thought I'd bring it up in case it helps.

Perhaps if you could re-iterate the issue you are trying to solve, that might help us better understand how we can help.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
