### ISSUE TITLE
Need a way to make crds selectively be installed via helm3

### ISSUE THREAD

**Issue by irisdingbj** [helm/helm#8821]
Hi Dear helm experts,

 I want to get benefit from helm3's `/crd`( means put all my crds under `/crd`) . I have multiple crds and need to use flag to control which crd will be installed. In the past when I put crd under /templates these flags works well. Now since we do not allow template under /crd, how should I make my crds selectively be installed?

Thanks!

**Comment by irisdingbj** [comment]
@hickeyma In case you can share some lights, Thanks!

**Comment by hickeyma** [comment]
@irisdingbj Thanks for raising this as it is an interesting use case.

Unfortunately, manifests only apply in the `/crds` directory and you would not have the templating for adding the enable/disable logic. You could put the CRDs in the template directory as long as there are no resources that use these CRDs in the chart. This may however circumvent API validation and not sure if it is an approved way to do it.  You would also need to test this method against your chart to make sure it works as expected.

/cc @technosophos

**Comment by irisdingbj** [comment]
@hickeyma Thanks a lot for this help!

**Comment by mattfarina** [comment]
@irisdingbj In the CRD docs it talks about [using a separate chart for them](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-2-separate-charts). The idea goes, the CRD needs to be installed though a chart that does not use any custom resources defined in the CRDs. In those situation you can use the `templates` directory and Helm will treat them like any other resource.

Note, there are many potential dangers with CRDs. For example, if you delete the instance of the chart it will delete the CRDs causing Kubernetes to delete all of the Custom Resources based on the CRDs. A PR to work on the documentation around this is at https://github.com/helm/community/pull/138. You may want to [tell Helm to not uninstall the CRDs](https://helm.sh/docs/howto/charts_tips_and_tricks/#tell-helm-not-to-uninstall-a-resource).

**Comment by hickeyma** [comment]
@irisdingbj Does this answer you question?

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!
