### ISSUE TITLE
[Q] Atomic flag for install/upgrade: What is considered failure?

### ISSUE THREAD

**Issue by agniveshadhikari** [helm/helm#8826]
Do we have thorough documentation for `helm install/upgrade --atomic` somewhere? I understand if the op fails, it'll auto roll back. Wanted to understand what exactly is checked by helm to determine success/failure.

**Comment by mattfarina** [comment]
The documentation on the `--atomic` flag is fairly limited. It is lightly documented for two commands:

* `helm install`: "if set, the installation process deletes the installation on failure. The --wait flag will be set automatically if --atomic is used"
* `helm upgrade`: "if set, upgrade process rolls back changes made in case of failed upgrade. The --wait flag will be set automatically if --atomic is used"

I can share a little more on how this works. After Helm generates the Kubernetes resources and validates them it sends them to Kubernetes. The atomic flag has no effect until the resource are sent to Kubernetes. If Helm is unable to create, update, or wait for the resources to come online it will either uninstall (if the action was an install) or roll back (on upgrade).

Does that help?

**Comment by agniveshadhikari** [comment]
Thanks @mattfarina. About this part 
> wait for the resources to come online
So helm does a get call on the kubernetes resources and checks the status?
How does it work for Jobs? Completed and Running are the 'good' states?

**Comment by mattfarina** [comment]
You can read the source of what wait does for different resources [here](https://github.com/helm/helm/blob/6aa54eacc52db045e82faa6b256678863e325a20/pkg/kube/wait.go#L52). It doesn't handle every Kubernetes resource.

**Comment by bacongobbler** [comment]
closing as answered. Let us know if you need further assistance.
