### ISSUE TITLE
[Q] Usage of values

### ISSUE THREAD

**Issue by Cyldei** [helm/helm#8832]
Hi!

I've got repository with structure like this:
```
├── Chart.yaml
├── charts
├── templates
│   ├── my-template.yaml
[...]
│   └── _helpers.tpl
├── values
│   ├── values-prod.yaml
│   └── values-stage.yaml
└── values.yaml
```

I'd like to install chart from repository without actually fetching it:
`helm install name my/repo --values=values/values-prod.yaml`

Is it possible to overwrite default values with my values file without having  that values-prod.yaml locally?

---------------------------------------------
If it's impossible, I've came with idea to set this line in each template:
`{{ $env := (index .Values .Values.env) }}` 
and to use
`{{ $env.myValue }}` instead of `{{ .Values.myValue }}`
Values files will be also modified to have all values from different files like this:
```
env: dev
dev:
  foo:
    bar: 
...
stage:
  foo:
    bar:
... 
etc
```
this workaround will allow me to install with different values without having them locally using this command:  ```helm install [ or upgrade ] name  my/repo --set env=stage``` 

Is there any easier way to achieve this?

**Comment by mattfarina** [comment]
This is an interesting question and one I'd not thought of before. You can't do it using the `--values` flag to tell it about a file in the chart. But, there is a method you can use.

You could create a template function that takes in an environment set as a value. Then based on that you could load the content of one of those files, parse the yaml into a dict (map[string]interface{} like values), and then return this. You could use that in your templates. You can parse the yaml with the [fromYaml](https://github.com/helm/helm/blob/e17500018edfede7a96bebd455d99fb26789ae91/pkg/engine/funcs.go#L98-L105) function. I'm pointing you to the source because I can't find docs on it.

Does this make sense?

**Comment by Cyldei** [comment]
I've created an function in helpers like this:
```
{{- define "values" -}}
{{- if (eq .Values.env "develop") -}}
    {{ toYaml .Values.develop }}
{{- end -}}
{{- end -}}
```
My call to this function, located in template looks like this:
```` 
{{ template "values" . }}
```
This returns all my variables located under "develop". When I want to recieve .Values.develop.foo, seems that it doesn't work as it should be. I've got an error `executing "values" at <eq .Values.env "develop">: error calling eq: incompatible types for comparison`. Below I provide how I call my variables while trying to filter:
```
{{ template "values" .mongodb }}
```

I've also tried to return from helpers map instead of yaml and using my call to variables like this:
```
{{ template "values" .mongodb | fromYaml }}
```

**Comment by mattfarina** [comment]
I was thinking you could access the other files from within the template. There are docs on that [here](https://helm.sh/docs/chart_template_guide/accessing_files/). You can conditionally load the content of a develop or prod configuration, parse it to yaml, attach it to a new variable, and reference that. Does that make sense?

**Comment by Cyldei** [comment]
Isn't it easier to use it like I tried to? Creating new files and then using variables located there makes sense, but developer have to come through more steps... Isn't there a way to include only one variable from helpers like:  `{{ template "values" .foo}}` 

I've also thought about using `with ` statement, but I don't really know how can I select file (with this statement) depending on what variable is set in values.

**Comment by Cyldei** [comment]
I can do it like this:
```
{{ template values/values-(index .Values .Values.env).yaml .
```
But... This way is inconvinient. It's easier to inculde another file with `with` statement and use $.Values where we really need something from global values file.

**Comment by mattfarina** [comment]
@Cyldei If that works for you please let us know.

**Comment by Cyldei** [comment]
Yeah, I've made this quick summary to show how I resolved my problem. Thank you for help! :)
