### ISSUE TITLE
Feature request: Built-in variable for the Helm version

### ISSUE THREAD

**Issue by rjeberhard** [helm/helm#8834]
Surprisingly, none of the built-in objects: https://helm.sh/docs/chart_template_guide/builtin_objects/ provides the Version of Helm itself.

We recently updated a chart to use the "lookup" function, which was introduced in Helm 3.1; however, we had no mechanism to validate that our customers were using at least this Helm version. Therefore, many customers, such as those still using Helm 3.0.1, received errors about "lookup not existing" rather than a helpful message about not having a sufficient Helm version.

Perhaps this could be provided under .Capabilities? Thanks.

**Comment by mattfarina** [comment]
It looks like you found a gap in the docs. The capabilities do now have the helm version. See https://github.com/helm/helm/blob/fbdda53585b3ba69be515a45b0eeea45c930d353/pkg/chartutil/capabilities.go#L32-L39

But, this was introduced in Helm 3.3 so it's not going to help you.

I have tried several different things in an effort to come up with a method to detect this feature and have not come up with something, yet. I've added this to the Helm weekly meeting agenda. Someone else may have an idea of what to do.

**Comment by bacongobbler** [comment]
You *might* be able to check for the presence of `.Capabilities.TillerVersion` via `if (index "Capabilities" "TillerVersion")`... The presence of that variable in the capabilities object could determine whether Helm 2 is being used or not.

https://github.com/helm/helm/blob/0d9779c4f12b1fcf2abf8f61596c07b2bd858210/pkg/chartutil/capabilities.go#L52

For more info on `index`: https://golang.org/pkg/text/template/#hdr-Functions

**Comment by mattfarina** [comment]
@bacongobbler unfortunately, .Capabilities is a struct instead of a map[string]interface{}. So, index won't work. You'll get an error like...

```
Error: template: helmversion/templates/deployment.yaml:7:40: executing "helmversion/templates/deployment.yaml" at <.Capabilities.TillerVersion>: can't evaluate field TillerVersion in type interface {}
```

This will happen for any property not present on the struct.

**Comment by bacongobbler** [comment]
@rjeberhard have you found any form of workaround available for Helm versions prior to Helm 3.3? We'd be happy to document workarounds for those versions, but since  `.Capabilities.HelmVersion` has been introduced, it looks like we've taken steps to address this gap for more recent versions.

**Comment by rjeberhard** [comment]
No, I found no workaround. I'm happy to close this and use the Helm 3.3 feature when we can reasonably make this our minimum supported version. Thanks for your help.

**Comment by FredericLeroy** [comment]
Hello, 
We have some charts which works with helm version 3.4.1 but not 3.3. 
We have been hitted several times by this problem of having a corresponding helm for a chart.
And there is no way to have the helm version.
This is really a feature we should have.
Do I need to reopen a FR ?

**Comment by bas2k** [comment]
{{- if hasKey (.Capabilities|toJson|fromJson) "HelmVersion" }}
