### ISSUE TITLE
How do I update dependency for remote chart?

### ISSUE THREAD

**Issue by jaksky** [helm/helm#8836]
Output of `helm version`: 2.16.7

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-26T06:17:09Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.12-gke.20", GitCommit:"0ac5f81eecab42bff5ef74f18b99d8896ba7b89b", GitTreeState:"clean", BuildDate:"2020-09-09T00:48:20Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE

I am using stable/prometheus chart - which has dependencies. I already installed the chart to K8s. I did update configuration which needs a dependency. How do I update dependencies that I can upgrade?

I noticed that helm install has --dep-up option but helm upgrade doesn't have such. What is the recommended approach? I haven't found a way how to achieve what I need.

**Comment by bacongobbler** [comment]
Hi @jaksky. As an FYI, Helm 2 is being deprecated in November. We'd urge you to upgrade to Helm 3 as soon as possible. More info here: https://helm.sh/blog/helm-v2-deprecation-timeline/

Have you tried `helm dependency update` before calling `helm upgrade`?

**Comment by jaksky** [comment]
Thx. I did try to call that but was complaining when cart was remote like stable/prometheus.

**Comment by mattfarina** [comment]
In order to update the dependencies you need to pull the chart down to an environment. This can be locally or with CI.

You can use a set of commands like...

```
helm fetch stable/prometheus --untar
helm dependency update ./prometheus
helm install ./prometheus
```

Note, I didn't test these but they are the theory of it.

Does that help?

**Comment by jaksky** [comment]
Yea, I endup doing the same. Was more curious about if there is possibility to do remote repos. Thanks for confirmation
