### ISSUE TITLE
Feature Request: Condition Expression

### ISSUE THREAD

**Issue by stevefan1999-personal** [helm/helm#8838]
In some services I'd like to provide managed services, e.g. databases. However I want to aggregate them into one `type` field and select different dependencies whichever is requested. That is seemingly impossible in the Helm today because `dependencies[...].condition` requires it to be a YAML boolean -- meaning it shouldn't be possible to write `condition: managed.database.type == Redis` because it is not YAML boolean (but an expression that evaluates to boolean)

And such, I will then have to find out all that possible types and then expose them into `redis.enabled`, `postgres.enabled`, `mongo: enabled`, which is quite verbose.

Also, I'd want to point out that this kind of "type" thingy should be implemented as a variant enum, is it possible in Helm too?

**Comment by mattfarina** [comment]
There is already something that does this today called `tags`. You can read about it at https://helm.sh/docs/topics/charts/#tags-and-condition-fields-in-dependencies. With tags you can group related things together. Does this help?

**Comment by bacongobbler** [comment]
closing as answered. Let us know if you have further questions.

**Comment by HoustonPutman** [comment]
There are other use cases for expressions in `condition` beyond `tags`.

For example if a user passes a connection string to a database, then don't create the dependent database chart. If the connection string is empty, then create it. That provides a better user experience than requiring the user manage two fields that serve the same purpose, `database.connectionString` and `database.create`.

```yaml
# parentchart/Chart.yaml

dependencies:
  - name: database
    repository: http://localhost:10191
    version: 0.1.0
    condition: !database.connectionString
```

**Comment by justincorrigible** [comment]
> That provides a better user experience than requiring the user manage two fields that serve the same purpose

As suggested by @HoustonPutman, this would be a better dev experience.
Implementing that exact same scenario, we've resorted to adding `tags.external` which adds cognitive burden that could (should) be abstracted for someone reusing my team's chart.

Any chance this ticket can be reopened for further discussion? @bacongobbler?
