### ISSUE TITLE
Deployment does not rollingupdate when I upgrade 

### ISSUE THREAD

**Issue by brichou** [helm/helm#8839]
Hello,

When I deployed a new version with helm3 (helm upgrade --install <release> <chart dir>) all pods are stopped in the same time and I generated a downtime :-(
This works in helm v2, is there any way to resolve this issue?

thanks in advance!

My rollingupdate parameters : 
    maxSurge: 2
    maxUnavailable: 1 

Output of `helm version`: 3.3.4

Output of `kubectl version`: 1.15.11

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

**Comment by mattfarina** [comment]
@brichou I'm sorry to hear you had a problem like this.

Helm delivers the payload to Kubernetes. It doesn't start or stop pods. This is all determined by the contents of the Kubernetes manifests generated from the templates. There is something in the content of the chart that's causing this. Without seeing that detail, I cannot point to the cause.

One thing that did change from Helm v2 to Helm v3 is that Helm takes into account changes to resources that occurred between releases. For example, if a sidebar is attached by a service mesh. It uses a three way strategic merge patch (from Kubernetes). If Helm v2 was blowing away an old change it might carried over now.

I hope this helps give you a couple places to look

**Comment by diwap** [comment]
@brichou check this faq.
https://helm.sh/docs/faq/#improved-upgrade-strategy-3-way-strategic-merge-patches

**Comment by brichou** [comment]
thanks for your reply!

I'm going to check my charts but if your expert eyes can find what is wrong I will be happy ! :-)
[charts.zip](https://github.com/helm/helm/files/5316699/charts.zip)

thanks

**Comment by mattfarina** [comment]
I don't see anything in the chart that would cause it to go offline. Do all the replicas come online when it is running? Or, are only 1/3 normally running?

**Comment by brichou** [comment]
hi,
Thanks for your help on this subjet but i found what was wrong, the deploiment worked with another chart version (not the version I uploaeded), and this version contained an error with replicas parameter :-( 
All works fine now with helm v3 and rolling update :-)

Thanks a lot for your time!
