### ISSUE TITLE
Can not redirect output of helm template to a file in bash

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [helm/helm#8842]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```
I'm on Ubuntu 20.04.

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.401", GitCommit:"eb94c181eea5290e9da1238db02cfef263542f5f", GitTreeState:"clean", BuildDate:"2020-09-09T00:57:35Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): none/localhost

I'm trying to render [this helm template](https://github.com/keptn/keptn/tree/master/installer/manifests/keptn) using `helm template installer/manifests/keptn` and store the output in a file, e.g.:

```console
helm template installer/manifests/keptn > test.txt
```

Using helm 3.3.4 the file `test.txt` is empty, while using helm 3.2.4 the file contains the content that I was expecting.

However, if I don't redirect the output to a file everything works as expected, e.g.:
```console
helm template installer/manifests/keptn | grep kind
```

```
kind: ServiceAccount
kind: ServiceAccount
kind: ServiceAccount
kind: ServiceAccount
kind: Secret
kind: Secret
kind: Secret
kind: ConfigMap
kind: ConfigMap
...
```

I believe there is some weird bug that prevents me from redirecting the output to a file.

**Comment by mattfarina** [comment]
I can imagine that's a frustrating problem.

I have tried to replicate this using the chart in question using both Helm v3.3.4 and the tip of master. I've done this on Ubuntu 20.04. I have not been able to reproduce the problem. When I send it to a file it works.

Note, in Helm v3 the template command can (and should) have two argument. It works with just one but it should have two. You can find the details with `helm help template`.

Is there some other detail about the situation? I've looked through the code path and I don't see anything that would cause this.

**Comment by christian-kreuzberger-dtx** [comment]
I swear to all gods that are known to the people on this planet, that I've tried the command 5 times, then tried it using helm 3.2.4, and then again using helm 3.3.4. The problem persisted with 3.3.4, and vanished with 3.2.4.

Anyway, the problem came up because I'm piping the output of helm template to [pluto](https://github.com/FairwindsOps/pluto), using
```
helm template installer/manifests/keptn | pluto detect-files -
```
and this also did not work with helm 3.3.4, but with 3.2.4 it did.

It is working now, without any change to the code-base, nor a reboot or anything on my machine. I've never seen a behaviour like this, but I'm going to blame full moon.

The only other thing I can think about is that helm 3.2.4 has changed something in my local helm config, and with that change helm 3.3.4 works fine again.

**Comment by mattfarina** [comment]
I'm glad it's working now.

There shouldn't have been any changes between Helm 3.2.4 and 3.3.4 to the local config. None that I can think of.

My best guess is gremlins. Good luck with them.
