### ISSUE TITLE
helm does not work without proxy prefix

### ISSUE THREAD

**Issue by tvvignesh** [helm/helm#8845]
Hi. I recently upgraded to v1.19.2 of kubectl and added the `proxy-url` flag (https://github.com/kubernetes/client-go/issues/351) to my kubeconfig to enable proxying to the cluster.

Now, kubectl works great without any issues as expected. 

But helm says `Kubernetes cluster unreachable: Get "https://10.0.0.2/version?timeout=32s": dial tcp 10.0.0.2:443: i/o timeout` and it works only if I add the `HTTPS_PROXY` env prefix to the `helm upgrade` command.

My understanding/expectation is that it should work without prefix since `proxy-url` is already added to the kubeconfig and kubectl works without any env vars since the proxy url is in config.

Output of `helm version`:
`version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}`

Output of `kubectl version`:

`Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.6-gke.4801", GitCommit:"bd8e5ba9d65ac06f6abd076a44f195668631a536", GitTreeState:"clean", BuildDate:"2020-09-10T00:12:32Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
`GKE 1.18.6-gke.4801`

**Comment by mattfarina** [comment]
Can you test if this is happening in the canary builds of Helm. You can find directions for installing those at https://helm.sh/docs/intro/install/#from-canary-builds.

Helm 3.3 does not use 1.19 client libraries. That will come in Helm 3.4.

**Comment by tvvignesh** [comment]
@mattfarina Hi. Just downloaded canary and tested it out. It works great in canary. You can close this.
