### ISSUE TITLE
proposal: enhance helm lint / helm --debug reporting on "missing" / misspelled variable values

### ISSUE THREAD

**Issue by xaxa06** [helm/helm#8847]
**Helm version**
```
>helm version
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

**Disclaimer**
I'm new to Helm so sorry in advance if :
- this doesn't make sense or if I missed something, in which case feel free to redirect me to appropriate documentation / guidelines
- it's not as concise /precise as it could have been if reported from someone with more experience

**Context:** 
I just spent significant amount of time troubleshooting a Helm install that was failing with below error: 
```
>helm install -f values.yaml demo .
Error: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource: resource name may not be empty
```

Turned out the culprit was a missing variable definition in my `values.yaml` for a kube service name (for which of course kube couldn't returned a meaningful error message): 
```yaml
cat templates/service.yaml
---
kind: Service
apiVersion: v1
metadata:
  # demo.serviceName was not defined in values.yaml
  name: {{ .Values.demo.serviceName }} 
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: {{ include "appName" . }}
```
Looking up online for how to troubleshoot this kind of issues, I ended up trying those unhelpful approaches: 

**Dry-run + debug**
```
>helm install --dry-run --debug -f values.yaml demohelm .
install.go:172: [debug] Original chart version: ""
install.go:189: [debug] CHART PATH: .

Error: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource: resource name may not be empty
helm.go:94: [debug] resource name may not be empty
could not get information about the resource
helm.sh/helm/v3/pkg/action.existingResourceConflict.func1
        /home/circleci/helm.sh/helm/pkg/action/validate.go:54
helm.sh/helm/v3/pkg/kube.ResourceList.Visit
        /home/circleci/helm.sh/helm/pkg/kube/resource.go:32
helm.sh/helm/v3/pkg/action.existingResourceConflict
        /home/circleci/helm.sh/helm/pkg/action/validate.go:43
helm.sh/helm/v3/pkg/action.(*Install).Run
        /home/circleci/helm.sh/helm/pkg/action/install.go:273
main.runInstall
        /home/circleci/helm.sh/helm/cmd/helm/install.go:242
main.newInstallCmd.func2
        /home/circleci/helm.sh/helm/cmd/helm/install.go:120
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:93
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1373
rendered manifests contain a resource that already exists. Unable to continue with install
helm.sh/helm/v3/pkg/action.(*Install).Run
        /home/circleci/helm.sh/helm/pkg/action/install.go:275
main.runInstall
        /home/circleci/helm.sh/helm/cmd/helm/install.go:242
main.newInstallCmd.func2
        /home/circleci/helm.sh/helm/cmd/helm/install.go:120
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:93
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1373
```
-> nothing pointing to the missing variable

**Lint and Lint --strict**
```
> helm lint . -f values.yaml
==> Linting .
[INFO] Chart.yaml: icon is recommended
[INFO] values.yaml: file does not exist

1 chart(s) linted, 0 chart(s) failed

> helm lint . -f values.yaml --strict
==> Linting .
[INFO] Chart.yaml: icon is recommended
[INFO] values.yaml: file does not exist

1 chart(s) linted, 0 chart(s) failed
```
-> nothing pointing to the missing variable

**Already available solution(s):**
From my research so far, the currently available solutions to avoid running after undefined variables that produce invalid YAML/JSON files are either to : 
- flag the variable as "required" in the values.yaml: this seems overly tedious, as the accompanying message is mandatory, and variable name has to be repeated explicitly in the accompanying error message for it to be useful, ie: 
```yaml
value: {{ required "A valid .Values.who.foo.bar entry required!" .Values.who.foo.bar }}
# have to do that for basically all values if all we ask is a meaningful hint when helm install/upgrade is failing...
```
- the "range" approach mentioned in [this thread](https://stackoverflow.com/questions/53866196/how-best-to-say-a-value-is-required-in-a-helm-chart) which also seems overly tedious for that purpose

**Proposals**
The aim would be to provide non-tedious way(s) of helping users troubleshoot this kind of missing/misspelled variable issues, at least at validation time (ie, helm lint command), and optionally at helm install time. 
By analogy, I see it as when a compilation error occurs on a missing / badly spelled variable: the compiler usually have the decency to point the programmer to what is the call point of that missing variable, and not having to find it by himself throughout the code base.

- have `helm lint` reporting the missing variables, even the ones that are not flagged as required. If needed (depending on the semantics of the "required" variables), this could be done by an additional flag (ex: `helm lint . -f values.yaml --report-also-missing-non-required-variables`)

- have helm lint printing the variable name / call point when "required" function doesn't contain an accompanying error message. To illustrate with an example: 
```yaml
# currently
name: {{ required "I'm too lazy to make this for all my variables." .Values.service.name }}

> helm lint . 
engine.go:159: [INFO] Missing required value: I'm too lazy to make this for all my variables.. 
==> Linting .
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, 0 chart(s) failed

# proposal
name: {{ required .Values.service.name }}
anotherName: {{ required "I'm evil and you'll never find me" .Values.service.anotherName}}
> helm lint . 
[INFO] Missing required value: service.name (required in file <filename> at line <line number>)
[INFO] Missing required value: I'm evil and you'll never find me
```

WDYT ?

**Comment by mattfarina** [comment]
@xaxa06 thank you for putting so much effort into writing up this request. I've not had a chance to check the code path and our use of the `test/template` package in the Go standard library to see if this is possible. But, I think it is an idea worth looking into.

**Comment by mueller-ma** [comment]
Any progress on this?
