### ISSUE TITLE
Document mitigation solutions to Docker Hub image pull limits

### ISSUE THREAD

**Issue by daaain** [helm/helm#8849]
I tried searching Helm docs and couldn't find any information on this.

As [Docker Hub is introducing rate limiting on image pulls](https://docs.docker.com/docker-hub/download-rate-limit/) I was wondering how is that going to affect Helm charts which reference images from their container registry and what possible solutions there are to stop pulls from failing.

I couldn't really figure out if there's a generic way to authenticate Kubernetes with Docker Hub looking at the Kubernetes documentation: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/

Am I right thinking that unless a chart which references a Docker Hub image exposes `image` and `imagePullSecrets` as values possible to override it won't be possible to use them as is?

Somewhat related to #8848

**Comment by bacongobbler** [comment]
HI @daaain. Thanks for bringing this up. Yes, this seems like a massive issue that is going to bite the Helm community come November 1st.

One feature that was introduced in Helm 3.1 that could address this is [the post-renderer](https://helm.sh/docs/topics/advanced/#post-rendering).

Post rendering gives chart installers the ability to manually manipulate, configure, and/or validate rendered manifests before they are installed by Helm. This allows users with advanced configuration needs to be able to use tools like `kustomize` to apply configuration changes without the need to fork a public chart or requiring chart maintainers to specify every last configuration option for a piece of software. There are also use cases for injecting common tools and side cars in enterprise environments or analysis of the manifests before deployment.

In this scenario, you could provide a custom post-renderer that inject image pull secrets into charts which do not expose these values. That could be one way to work around this.

cc'ing @thomastaylor312 here to ask if he knows of any examples with `kustomize` that may help out here.

In the meantime, let us know what you find out!

**Comment by daaain** [comment]
Thanks for picking it up!

So far what I found is that as a [Helmfile](https://github.com/roboll/helmfile) user it's possible to do ad-hoc customisation using `strategicMergePatches` which doesn't look bad: https://github.com/roboll/helmfile/blob/63c8df98739489014eb3bf2c67119f77f43309d3/docs/advanced-features.md#adhoc-customization-of-helm-charts

I'll post an update if I have a concrete example which worked for this particular use case.

**Comment by thomastaylor312** [comment]
I don't have a concrete example of image pull secrets + Helm, but I assume it is easily doable with kustomize. Helmfile is also a great option

**Comment by bacongobbler** [comment]
@daaain is this something you're wiling to put in the time for?

**Comment by daaain** [comment]
Hey @bacongobbler, sorry for the silence, yes, I can give it a go today.

I have written a draft up below, I was thinking of briefly outlining the options and pointing people to details via links. Let me know if this sounds like a good approach. Also, not sure yet what would be the best place in the documentation to put this into.

_________________

## Problem statement

Briefly explain the issue around pull rate limits and probably mention image retention policies coming later so people can weigh in options knowing both.

https://www.docker.com/blog/docker-hub-image-retention-policy-delayed-and-subscription-updates/

## Options in detail

### No code changes – use Docker Hub accounts

The simplest and quickest way to solve the issue is to pay up. You'd still need to make some configuration changes in a few places to make sure container runtimes are authenticated Docker Hub. 

NB: this will not solve the issue with Docker Hub's image retention policies coming next year which means less used images might be deleted.

Actions needed in different environments:
* Development machines – authenticate Docker with an account (a free one will be enough for most people)
* CI server – authenticate Docker with an account (will need a paid one due to possible heavily shared IP)
* Kubernetes cluster – authenticate Docker with an account (for clusters with public Node IPs and `imagePullPolicy` generally `IfNotPresent` the free tier _might_ be enough, but to prevent deploys potentially blocked for hours, it'd be recommended to authenticate with a paid account)

Authentication methods for these various environments linked in: https://docs.docker.com/docker-hub/download-rate-limit/#how-do-i-authenticate-pull-requests

### No code changes – set up Docker image mirror

Another option could be to add registry mirror locations to the container runtime configuration. For popular images this could solve the issue, but images from less known Helm charts could still fail to pull.

https://cloud.google.com/container-registry/docs/pulling-cached-images
https://circleci.com/docs/2.0/docker-hub-pull-through-mirror/

Actions needed in different environments:
TBC

### Replace image locations

If you don't want to authenticate to Docker Hub, you can push the images you use to an alternative registry which doesn't rate limit or to one which you're already authenticated with.

Also, keep in mind that you'll need to have a copy of both base images from Dockerfiles so you can build your own images and images from Helm charts you use.

Possible fixes:
* If the Helm chart wired up variables for `image` (and `imagePullSecrets` if the registry needs authentication) you can set these to point to an alternative registry
* With Helmfile it's possible to do ad-hoc customisation of Helm charts to update these using `strategicMergePatches`, see: https://github.com/roboll/helmfile/blob/63c8df98739489014eb3bf2c67119f77f43309d3/docs/advanced-features.md#adhoc-customization-of-helm-charts 
* It's also possible to apply customisations to Helm chart using `kustomize`, see:
https://jfrog.com/blog/power-up-helm-charts-using-kustomize-to-manage-kubernetes-deployments/
