### ISSUE TITLE
Reproducible chart dependency archives

### ISSUE THREAD

**Issue by MOZGIII** [helm/helm#8850]
Currently (as of `3.3.4`), `helm dependency build` doesn't produce reproducible `.tgz` archives at `charts/` dir.

We're using `file://` only dependencies, and expect two runs of the `helm dependency build` to generate the same `charts/*.tgz` files, however the sha256 sums are different.

This prevents us from using git lfs to store the `charts/*.tgz` dir.

**Comment by bacongobbler** [comment]
This may be a symptom of https://github.com/helm/helm/issues/3612 as `helm dependency build` calls the same APIs as `helm package` to package the `file:://` dependencies.

**Comment by MOZGIII** [comment]
Sounds very much like it.

I'm thinking about a workaround -if we copy-over/symlink the contents of the `file://` dependencies to `charts/`, unarchived - this should allow us to both omit the lfs and work around this issue.

Does this sound like a good idea? Any hidden issues with this approach?

**Comment by mattfarina** [comment]
If someone wants to fix this issue... we would be happy to look at it.
