### ISSUE TITLE
Release.IsInstall is false for new deployment with helm upgrade --install

### ISSUE THREAD

**Issue by zaphod72** [helm/helm#8852]
For a new deployment. Running `helm upgrade --install ...`
Expect: `Release.IsInstall` to be true.
Actual: `Release.IsInstall` is false

Output of `helm version`:
version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-23T14:21:54Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.42", GitCommit:"42bef28c2031a74fc68840fce56834ff7ea08518", GitTreeState:"clean", BuildDate:"2020-06-02T16:07:00Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

**Comment by mattfarina** [comment]
@zaphod72 Can you test this against the latest code ([you can try a canary release here](https://helm.sh/docs/intro/install/#from-canary-builds))? I am unable to reproduce this issue in either v3.2.3 or in the latest code.
