### ISSUE TITLE
Using helm in a go-lang project can result in many kube-clients

### ISSUE THREAD

**Issue by janario** [helm/helm#8854]
Similar as reported at https://github.com/helm/helm/issues/7722#issuecomment-700672163

When using helm project into a go-lang application and executing some operations in the cluster it can result in warns about the number of connections 

> W0303 09:43:12.111352    8329 exec.go:201] constructing many client instances from the same exec auth config can cause performance problems during cert rotation and can exhaust available network connections; 1961 clients constructed calling "aws"

As commented in the other issue some more details of why this happens

[kube.(*Client).IsReachable](https://github.com/helm/helm/blob/master/pkg/kube/client.go#L92) always asks for a new client and then eventually it reaches 1000 and starts to warn

https://github.com/kubernetes/client-go/blob/master/plugin/pkg/client/auth/exec/exec.go#L202

Stacktrace:

```
k8s.io/client-go/plugin/pkg/client/auth/exec.(*Authenticator).UpdateTransportConfig at exec.go:203
k8s.io/client-go/rest.(*Config).TransportConfig at transport.go:100
k8s.io/client-go/rest.TransportFor at transport.go:42
k8s.io/client-go/rest.RESTClientFor at config.go:295
k8s.io/client-go/kubernetes/typed/certificates/v1beta1.NewForConfig at certificates_client.go:47
k8s.io/client-go/kubernetes.NewForConfig at clientset.go:444

k8s.io/kubectl/pkg/cmd/util.(*factoryImpl).KubernetesClientSet at factory_client_access.go:83
helm.sh/helm/v3/pkg/kube.(*Client).IsReachable at client.go:91
```

Output of `helm version`: helm.sh/helm/v3 v3.3.4

Output of `kubectl version`: k8s.io/cli-runtime v0.18.8

Cloud Provider/Platform (AKS, GKE, Minikube etc.): EKS

**Comment by bacongobbler** [comment]
Thanks for the report. Any suggestions (in the form of a PR) on how we can improve this is welcome.

**Comment by janario** [comment]
PR https://github.com/helm/helm/pull/8855

So the idea is to lazy create the kube-client and reuse if it was already created

**Comment by mattfarina** [comment]
Closing as the fix was merged.
