### ISSUE TITLE
Helm test inherit podAntiAffinity

### ISSUE THREAD

**Issue by oleg-filiutsich** [helm/helm#8856]
Then I run 'helm test' the test pod assign to deployment object and inherit deployment's podAntiAffinity and the test pod can't run in cluster cause all nodes busy by app replicas/
How turn off the inherit ? 

Output of `helm version`:
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-09-30T19:31:27Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.12-gke.20", GitCommit:"0ac5f81eecab42bff5ef74f18b99d8896ba7b89b", GitTreeState:"clean", BuildDate:"2020-09-09T00:48:20Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

**Comment by mattfarina** [comment]
This is a good question. It is a Kubernetes question rather than a Helm question. Helm test runs additional resources during the time period. A Kubernetes forum may give you better help in solving this problem.

**Comment by bacongobbler** [comment]
closing as answered. Please follow up in the appropriate forum. Thanks.
