### ISSUE TITLE
helm lint: Lost functionality since 3.2.4

### ISSUE THREAD

**Issue by Antonboom** [helm/helm#8857]
Hello!

**Before:**
```
version.BuildInfo{
     Version:"v3.2.4",
     GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688",
     GitTreeState:"dirty",
     GoVersion:"go1.14.3"}
```
```
$ helm lint --strict .cicd/deploy/k8s/helm/
==> Linting .cicd/deploy/k8s/helm/
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: template: spgw/templates/configmap.yaml:42:21:
executing "spgw/templates/configmap.yaml" at <.Values.cfgSportcast.Redis>: map has no entry for key "Redis"

Error: 1 chart(s) linted, 1 chart(s) failed
```

**After:**
```
version.BuildInfo{
    Version:"v3.3.4",
    GitCommit:"a61ce5633af99708171414353ed49547cf05013d",
    GitTreeState:"dirty",
    GoVersion:"go1.15.2"}
```

```
$ helm lint --strict .cicd/deploy/k8s/helm/
==> Linting .cicd/deploy/k8s/helm/
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, 0 chart(s) failed
```

No changes except for updating the helm were made.

<img width="909" alt="Screenshot 2020-10-07 at 17 55 57" src="https://user-images.githubusercontent.com/17127404/95348104-5bb3f800-08c6-11eb-8066-60e46d29bad6.png">

**Comment by mattfarina** [comment]
The `--strict` flag is for "fail on lint warnings". This was the documented expectation of that feature.

Due to a bug, it invoked another strict check. You were essentially using the bug.

What I would suggest is that this check is returned as a feature with a new flag. Would that be ok?

**Comment by Antonboom** [comment]
I didn't get it. The fact that my config did not pass validation before is a helm bug that has been fixed now?

**Comment by mattfarina** [comment]
@Antonboom I understand the confusion.

The flag you used was supposed to cause `helm lint` to exit with a non-zero exit code. That's it. It was documented that way.

A bug caused the flag to change the way the YAML was handled in addition to the non-zero exit code. This change to YAML handling is what you were relying on.

I'm going to add this as a feature. We can likely add it back with an additional flag.

**Comment by Antonboom** [comment]
OK, but how can I make it so that the lint does not pass in the new version? :)
