### ISSUE TITLE
creating repository of helm chart using helm version 3

### ISSUE THREAD

**Issue by abhiranjeet** [helm/helm#8858]
I have started working on writing helm charts and it has been amazing working on it.
However, I am unable to create repositories for the helm charts which I created for my application. 
I did find instructions on how to do that using **helm version 2**, but I am unable to do the same using **helm version 3**

Output of `helm version`:`version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}`

Output of `kubectl version`:`Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by bacongobbler** [comment]
Does https://helm.sh/docs/topics/chart_repository/#hosting-chart-repositories help?

**Comment by abhiranjeet** [comment]
Yes. It helped. Thank You very much !

**Comment by hickeyma** [comment]
Closing as answered.
