### ISSUE TITLE
Feature request: support --context as an alias to --kube-context

### ISSUE THREAD

**Issue by tculp** [helm/helm#8859]
When switching back and forth between kubectl commands and helm commands, it is common for me to accidentally keep or type --context instead of --kube-context for my helm commands.

As helm doesn't have a --context flag, I think it would make sense if that worked just like --kube-context.

**Comment by hickeyma** [comment]
@tculp This is a good point to raise. Not sure the reason for the difference bar maybe trying to distinguish that it is kube context. Going to add this as a feature.

**Comment by bacongobbler** [comment]
counter-argument: some users are getting confused about whether `--verbose`, `--ca-cert`, `--logtostderr`, `--insecure-skip-tls-verify`, etc. affect Helm or some other component, so the clear separation of concerns helps clarify what those flags affect. I would argue against this change and keep the separation of concerns clear.

**Comment by tculp** [comment]
@bacongobbler Several of those options do have multiple effects that would make sense (does --insecure-skip-tls-verify affect the kubectl connection or helm chart pulling). However there is no concept of a context in helm other than kubectl's, so there is only one possible effect a --context option could have.

As for the cobra part, uh... that sucks

**Comment by tculp** [comment]
@bacongobbler With helm 4.0 on the horizon I think this could be re-opened
