### ISSUE TITLE
helm install/upgrade sometimes return timeout when secret not found

### ISSUE THREAD

**Issue by isaactl** [helm/helm#8866]
Output of `helm version`:
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:23:26Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-eks-2ba888", GitCommit:"2ba888155c7f8093a1bc06e3336333fbdb27b3da", GitTreeState:"clean", BuildDate:"2020-07-17T18:48:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
EKS

there is a inconsistency behavior when install a chart or upgrade a release if a secret is missing: sometime helm report the error like **secret 'xx' is not found**, while sometime, it just wait for a long time and then report **timed out waiting for the condition**. if i execute ```kubectl get event```, i'll see a secret not found error.

My question is like why do i get timeout when the error is already happened? shouldn't it just return the error and stop waiting? is there any way to force helm exit and print the error?

Any help will be appreciated!

**Comment by hickeyma** [comment]
@isaactl This sounds like a sporadic network issue with your cluster. Helm talks directly to the Kubernetes API service like `kubectl`. There is no other magic in between. 

Not sure why this would be happening like this especially if you are running `helm` and `kubectl` from the same system. Have you ever had any issue with the `kubectl` command?

**Comment by isaactl** [comment]
@hickeyma thanks for the info!
no, i didn't had any issue before with kubectl. but as you said, it could be a random issue. i'll dig more on possible network issue

**Comment by isaactl** [comment]
after few times of testing, it looks like the issue is related to the flag ```--atomic```.
if i remove this flag, helm will install and exit without error in few seconds. same behavior as kubectl
while adding this flag, i'll get lots of logs from **wait.go** until timeout
```
client.go:108: [debug] creating 2 resource(s)
wait.go:53: [debug] beginning wait for 2 resources with timeout of 1m0s
wait.go:225: [debug] Deployment is not ready: default/xxxx. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: default/xxxx. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: default/xxxx. 0 out of 1 expected pods are ready
....
```
still it looks to me, helm is not aware of the secret not found error in this run, but keep waiting for pod status to be ready. but in some run, it gives the secret not found error immediately.

**Comment by hickeyma** [comment]
@isaactl Thanks for investigating this further and proving more info. I wonder is this related to #8675?

**Comment by isaactl** [comment]
in my case, i don't have issue to do the rollback.

**Comment by bacongobbler** [comment]
@isaactl were you able to determine the cause of this issue?
