### ISSUE TITLE
Update Helm v2 docs

### ISSUE THREAD

**Issue by hickeyma** [helm/helm#8869]
The Helm v2 docs are out of date.

**Comment by bacongobbler** [comment]
Hi @hickeyma. Can you please provide more information on what's required to close out this ticket? Not sure what's the call to action here.

**Comment by marckhouzam** [comment]
Assuming there is an extra "not" in the issue description 😄 , I believe what @hickeyma meant was that the helm.sh docs for v2 haven't been updated to the latest available versions, as can be seen in this screenshot taken from https://v2.helm.sh/docs/:

<img width="231" alt="Screen Shot 2020-10-25 at 5 44 17 PM" src="https://user-images.githubusercontent.com/414402/97119896-bed8c380-16e9-11eb-8181-23255c88a308.png">

While the latest releases are 3.3.4 and 2.16.12.
I've never dealt with v2 docs, so I'm not sure how to fix that.

**Comment by bacongobbler** [comment]
![image](https://user-images.githubusercontent.com/1360539/97330548-978f0d00-1835-11eb-9a02-4e615705ce9f.png)

**Comment by bacongobbler** [comment]
Oh, my bad. This is for v2.helm.sh.

Feel free to PR a fix here: https://github.com/helm/helm-www/blob/d0035599b9c4f682001e9cea79b78b0cdd6ea7b8/config.toml#L30-L43
