### ISSUE TITLE
Does helm support make `service account delete action` executed last?

### ISSUE THREAD

**Issue by ningyougang** [helm/helm#8870]
Output of `helm version`:
```
# helm version
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"1bea6c00a7055edef03f1d4bb58b773fa8917f11", GitTreeState:"clean", BuildDate:"2020-02-11T20:05:26Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
 
My local k8s cluster managed by helm

My Question:
when `helm delete <release> --purge`, it seems all resources are deleted parallel.
Does helm support `service account delete action` executed last?

**Comment by bridgetkromhout** [comment]
Hi, @ningyougang - Helm v2 support is ending very soon (https://helm.sh/blog/helm-v2-deprecation-timeline/), so we suggest you change to use Helm v3. Much behavior is different in v3. The `helm delete` command has been renamed to `helm uninstall`. You can read more about it here: https://helm.sh/docs/helm/helm_uninstall/

**Comment by ningyougang** [comment]
@bridgetkromhout thanks for you reply.
