### ISSUE TITLE
Error: grpc: received message larger than max (22988949 vs. 20971520)

### ISSUE THREAD

**Issue by bizso** [helm/helm#8871]
Output of `helm version`:

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by bizso** [comment]
helm install local/onap --name dev --namespace onap
Output of helm version:2.16.6

**Comment by hickeyma** [comment]
Duplicate of #7799

**Comment by hickeyma** [comment]
@bizso Check if there is any artefacts in your chart directory that shouldn't be there. Your chart size is exceeding the limit.

There are many more such issues like #3512

**Comment by hickeyma** [comment]
Closing as a duplicate.
