### ISSUE TITLE
Feature Request: Disable escaping HTML in toPrettyJSON (add toPrettyRawJson?)

### ISSUE THREAD

**Issue by wallyqs** [helm/helm#8872]
Currently using toJSON functions in the Helm templates escapes HTML:

```yaml
      {{- with .Values.store.limits }}
      store_limits: {{ toPrettyJson . | indent 6 }}
      {{- end }}
```

```yaml
  limits:
    channels:
      foo.>:
```

Results in:

```json
      store_limits:       {
        "channels": {
          "bar.\u003e": null
        }
      }
```

I'd say that since this function is used outside of the content of generating HTML, maybe escaping HTML should be disabled?  

Output of `helm version`:

```
helm version
version.BuildInfo{Version:"v3.3.2", GitCommit:"e5077257b6ca106d1f65652b4ca994736d221ab1", GitTreeState:"dirty", GoVersion:"go1.15.2"}
```

Output of `kubectl version`:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:21Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.15", GitCommit:"2a313bf59aa0e1c98bbee2aea6ae727d3f6da6fd", GitTreeState:"clean", BuildDate:"2020-09-03T05:20:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AKS

**Comment by hickeyma** [comment]
@wallyqs Thanks for raising the issue. For clarification, are you saying the `toPrettyJSON` function is removing HTML escape characters?

**Comment by mattfarina** [comment]
The HTML escaping is a product of the default setting for the Go JSON encoder.

If you want to avoid it you can use `toRawJson` instead. That explicitly disables HTML escaping.

**Comment by wallyqs** [comment]
I know that it is due to Go JSON encoder defaults ;) `toRawJson` is not pretty though so would become a long string

```
store_limits:       {"channels":{"bar.>":null}}
```

instead of 

```
      store_limits:       {
        "channels": {
          "bar.>": null
        }
      }
```

I think helm would likely never be used to output HTML so ok to disable as with toRawJSON? Or maybe have `toPrettyRawJson`?

**Comment by bacongobbler** [comment]
Are there concerns of breaking backwards compatibility if we were to change the default JSON encoder settings? In other words, are there charts out there using `toPrettyJson` or `toJson` expecting this behaviour?

If we were to output raw strings, what would be the use of `toJson` vs `toRawJson`?

**Comment by wallyqs** [comment]
I'd say that there are actually a lot of charts using it out there unintentionally outputting JSON with escaped html (which is a very common format for automated still readable configuration), since it is a time saver over having to implement the complete schema: https://github.com/search?l=YAML&q=toPrettyJson&type=Code

**Comment by mattfarina** [comment]
@bacongobbler changing the default encoder would break backwards compat. This is part of sprig and it won't make that backwards breaking change. This is why `toRawJson` was introduced in the first place.

**Comment by wallyqs** [comment]
That's fair, sounds like `toPrettyRawJson` would fit better

**Comment by wallyqs** [comment]
Closing since stale, thanks!

**Comment by a-thomas-22** [comment]
If you run across this, here is a hacky equivalent of toPrettyRawJson I think:

`{{- .Values.configmap.data | toPrettyJson | replace "\\u0026" "&" | replace "\\u003c" "<" | replace "\\u003e" ">" | nindent 4 }}`

**Comment by piotrlaczykowski** [comment]
PR #31964 implements this fix by overriding `toPrettyJson` and `mustToPrettyJson` in the engine FuncMap with `json.Encoder` + `SetEscapeHTML(false)`. Backward compatible — preserves 2-space indentation. Tests included.
