### ISSUE TITLE
Umbrella chart bump version

### ISSUE THREAD

**Issue by tomassatka** [helm/helm#8877]
When i have umbrella chart with given structure:

C:.
├───charts
│   ├───activemq
│   │   └───templates
│   ├───chart1
│   │   ├───configmaps
│   │   └───templates
│   ├───chart2
│   │   └───templates
│   ├───mariadb
│   │   └───templates
│   ├───chart3
│   │   └───templates
│   └───chart4
│       └───templates
└───templates
    └───tests

When executing `helm package --version 1.0.1 .` this will bump only the parent chart. 

1/ Is there a way how can i propagate bump on subcharts chart1, chart2, chart3, chart4 ?

2/ Or the other way around. Can subcharts read parent Chart.Version when this is bupmed?

**Comment by mattfarina** [comment]
> 1/ Is there a way how can i propagate bump on subcharts chart1, chart2, chart3, chart4 ?

The short answer is, not in a single command. The charts in the _charts_ directory are dependencies. Those are managed using the `helm dependency` set of commands and metadata from the `Chart.yaml` and `Chart.lock` files. Something that modified their versions is going outside the standard path.

If you wanted to pursue this path you could write a script that did something like you're asking for. It doesn't really fit with Helm as a package manager for Kubernetes and well known package manager workflows.

> 2/ Or the other way around. Can subcharts read parent Chart.Version when this is bupmed?

No.

**Comment by bacongobbler** [comment]
closing as answered. Let us know if you have further questions. Thanks!
