### ISSUE TITLE
Using github as helm repo throws error

### ISSUE THREAD

**Issue by santosh-hegde** [helm/helm#8878]
I'm trying to use GitHub as Helm repo for my project. When I try to do `helm install some_name repo/chart`, I get below error
`Error: file '/Users/home/Library/Caches/helm/repository/chart-1.0.0.tgz' does not appear to be a gzipped archive; got 'text/html; charset=utf-8'`

Output of `helm version`:
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}

**Comment by yxxhero** [comment]
Can you offer the github repo for testting? @santosh-hegde

**Comment by hickeyma** [comment]
@santosh-hegde This seems like an issue with the chart package. How was `chart-1.0.0.tgz` created?

**Comment by santosh-hegde** [comment]
`helm package chartName -d=.deploy -u`
When I run `file .deploy/*` I get back 
`.deploy/chart-1.0.0.tgz: gzip compressed data, extra field, has comment, original size modulo 2^32 121344`

**Comment by mattfarina** [comment]
Helm will use the same credentials when fetching the chart archive from the repository. If you were on a newer version of Helm I would tell you to use the `helm env` command to find the repositories config file where you'll see some info on that. If Helm can fetch the _index.yaml_ file it should be able to get any charts next to it.

Is the relative path listed in the _index.yaml_ right for the chart archive compared to the location of the _index.yaml_ file? Or, is it using a full static URL?

**Comment by bacongobbler** [comment]
Okay. Can you please provide a set of steps we can use to reproduce your testing environment. That way we can better understand the issues that are arising, as well as provide some actionable feedback for you. Thank you.

**Comment by santosh-hegde** [comment]
@mattfarina It worked when I use relative URL in index.yaml. When I mention full URL in index.yaml it won't work.
Thank you for your help.
