### ISSUE TITLE
No --skip-refresh option in "helm dep build"

### ISSUE THREAD

**Issue by wi1dcard** [helm/helm#8882]
It seems only `helm dep update` has the option `--skip-refresh` from the help, the command `helm dep build` doesn't:

```
Usage:
  helm dependency update CHART [flags]

Aliases:
  update, up

Flags:
  -h, --help             help for update
      --keyring string   keyring containing public keys (default "/Users/wi1dcard/.gnupg/pubring.gpg")
      --skip-refresh     do not refresh the local repository cache
```

```
Usage:
  helm dependency build CHART [flags]

Flags:
  -h, --help             help for build
      --keyring string   keyring containing public keys (default "/Users/wi1dcard/.gnupg/pubring.gpg")
      --verify           verify the packages against signatures
```

However, I found that in the source code, both of these commands checked the option `--skip-refresh`:

<https://github.com/helm/helm/blob/fc9b46067f8f24a90b52eba31e09b31e69011e93/pkg/downloader/manager.go#L182-L188>

<https://github.com/helm/helm/blob/fc9b46067f8f24a90b52eba31e09b31e69011e93/pkg/downloader/manager.go#L134-L139>

Also found the commit add `--skip-refresh` option: <https://github.com/helm/helm/commit/f185103b602645ddabbd27107fb1df9478159910>

Is this something we missed or the `if !m.SkipUpdate` for `helm dep build` should be removed?

Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}
```

Output of `kubectl version`:

Not relevant.

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Not relevant.

**Comment by mattfarina** [comment]
@wi1dcard This is a good catch. Thanks for reporting it.

At first, I considered this a feature because it's easily possible to add as a feature. Not updating when doing a build could be useful. But, `helm dep build` will run `helm dep update` if there is no lockfile. So, it should have the same options as `helm dep update` for that.

In either case, this should be straight forward if someone wants to create a PR.
