### ISSUE TITLE
Helm incorrectly shows upgrade failed status

### ISSUE THREAD

**Issue by hatharom** [helm/helm#8889]
When using helm install/upgrade in some percentage of the time I get this failure:

`Failed to install app MyApp. Error: UPGRADE FAILED: timed out waiting for the condition`

This is because the app sometimes needs a bit more time to be up and running.

When I get this message helm doesn't stop the install/upgrade, but still works on it, which will be succeed by the end. And my whole cluster will be fully functional.
However helm still shows this failed status for the release.
On one hand it is pretty annoying, on the other hand it can mess up a correctly installed release.

How to remove this false error and get into a 'deployed' state(without a new install/upgrade)?

(kubernetes 1.17,  helm2, helm3 both have this behaviour)

**Comment by bridgetkromhout** [comment]
Hi, @hatharom - does using `--wait` help? See https://helm.sh/docs/intro/using_helm/#helpful-options-for-installupgraderollback for more details.

**Comment by hatharom** [comment]
> 
> 
> Hi, @hatharom - does using `--wait` help? See https://helm.sh/docs/intro/using_helm/#helpful-options-for-installupgraderollback for more details.

It doesn't, same issue. 
Even if I set the timeout to a big amount like 2hour , the app still gets deployed in ~15min. Every kubernetes resource is running but the erro message is there.
`kubectl get events` shows only normal events.

The worst of it when I try an upgrade(without any changes to the catalog) after the installation,  the expected behaviour would be to do nothing. Because nothing has been changed. However helm starts to delete every kubernetes resource and reinstall it from the scratch.

**Comment by mattfarina** [comment]
@hatharom Can you share some detail about the Kubernetes resources (group/version/kind included) that take a long time to come up and are affecting this.

**Comment by bacongobbler** [comment]
ping.

**Comment by bacongobbler** [comment]
Closing as inactive after asking for more details. Please re-open when more details are available. Thanks.
