### ISSUE TITLE
Convert zsh completion to GenZshCompletion

### ISSUE THREAD

**Issue by knrt10** [helm/helm#8893]
Cobra released their new version yesterday https://github.com/spf13/cobra/releases/tag/v1.1.1 which included `ValidArgsFunction` for zsh completion. This means all the code needed for zsh here https://github.com/helm/helm/blob/master/cmd/helm/completion.go#L147 can be removed and converted to `GenZshCompletion`

Output of `helm version`: `version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}`

Output of `kubectl version`: `Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by hickeyma** [comment]
Thanks for raising @knrt10. Letting @marckhouzam know.

**Comment by knrt10** [comment]
I can work on this if no one takes this up.

**Comment by hickeyma** [comment]
FYI, dependabot push PR #8894 so can use that PR.

@knrt10 Sure, go for it.

**Comment by marckhouzam** [comment]
> I can work on this if no one takes this up.

@knrt10 that would be great!

A couple of hints of I may.

Cobra 1.1 changes the version of gopkg.in/yaml.v2 to v2.3.0 which contains a possibly breaking change in his or handles long lines.
We need to figure this out first through #8890.

Once we're on Cobra 1.1 and moved to native zsh completion, you can also remove this function: https://github.com/helm/helm/blob/8667aa4f98574008947ee39c2e583e359fd687c1/cmd/helm/search_repo.go#L380

I'm looking forward to this change very much!

**Comment by marckhouzam** [comment]
Oh and I recommend we wait after 3.4 is out (any day now) to avoid last minute surprises.

**Comment by knrt10** [comment]
Sure, thanks for the info, will try working on this over weekend

**Comment by marckhouzam** [comment]
Cobra 1.1.1 had been released to address a breaking change.  We should move to that version instead @knrt10

**Comment by bacongobbler** [comment]
relevant: https://github.com/helm/helm/pull/8916

**Comment by marckhouzam** [comment]
@knrt10 we'll use #8916 to actually move to Cobra 1.1.1. How about refocusing and renaming the current PR to take care of the improved zsh completion changes you have mentioned?

**Comment by knrt10** [comment]
Done

**Comment by marckhouzam** [comment]
The 3.4 branch has been created so the master branch is ready for your upcoming PR, whenever you are ready.

**Comment by knrt10** [comment]
Thanks, will do it ASAP.

**Comment by marckhouzam** [comment]
> Thanks, will do it ASAP.

Oh but I got ahead of myself, we still need #8916 first, for Cobra 1.1.1... sorry

**Comment by marckhouzam** [comment]
Ok @knrt10 #8916 is merged.

**Comment by knrt10** [comment]
Great, will open PR soon

**Comment by knrt10** [comment]
@marckhouzam should I wait for #8890 to get merged? Also is there any estimation on 3.4 release?

**Comment by marckhouzam** [comment]
> @marckhouzam should I wait for #8890 to get merged? Also is there any estimation on 3.4 release?

@knrt10 I don't expect #8890 to get merged because it has a breaking change; also Cobra 1.1.1 has moved back to using yaml.v2 2.2.8.  For your PR you don't need to worry about that anyway since helm is already using Cobra 1.1.1 on the master branch.

The 3.4 release should be out this week but you don't need to wait for it because the master branch is now open for changes aimed at 3.5.
