### ISSUE TITLE
`helm template` does not work with library charts

### ISSUE THREAD

**Issue by zx8** [helm/helm#8895]
```sh
$ helm version
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}
```

I'm trying to debug a library chart, but an unable to render it for debugging purposes. I am not trying to install it.

Simple repro:

```sh
$ mkdir foo

$ cd foo/

$ echo "apiVersion: v2
  type: library
  name: foo
  version: 0.0.1" > Chart.yaml

$ mkdir templates

$ echo "{{ toYaml .Values }}" > templates/values.tpl

$ helm template --set foo=bar .
Error: library charts are not installable
```

Any chance we can enable this workflow?

**Comment by hickeyma** [comment]
Thanks for raising this @zx8. This is an interesting request. At the time we were primarily concerned with not making library charts installable. The code changed later with template code refactored to share install code because of duplication.  

I would like to get feedback from the community to see if this is capability we should provide.

**Comment by zx8** [comment]
@hickeyma I appreciate waiting for the community's response here, but from a pure "correctness" standpoint, it really just seems wrong to not be able to template out library charts.

I was bitten by this again today while developing a library chart. I had to temporarily comment out the chart type, run `helm template` to debug the issue, then uncomment it.

I'd be more inclined to consider this a bug than a feature request. 😀

**Comment by bacongobbler** [comment]
I’m confused - library charts are not supposed to contain any templates. It’s the same reason why the cannot be installed. Why would you want to be able to run `helm template` against a chart with no templates?

**Comment by bacongobbler** [comment]
From https://helm.sh/docs/topics/library_charts/:

> A library chart is a type of Helm chart that defines chart primitives or definitions which can be shared by Helm templates in other charts. This allows users to share snippets of code that can be re-used across charts, avoiding repetition and keeping charts DRY.

> The library chart was introduced in Helm 3 to formally recognize common or helper charts that have been used by chart maintainers since Helm 2. By including it as a chart type, it provides:

> - A means to explicitly distinguish between common and application charts
> - Logic to prevent installation of a common chart
> - **No rendering of templates in a common chart** which may contain release artifacts

Emphasis in bold.

**Comment by zx8** [comment]
Ahh, fair enough, I missed that in the docs.

I guess the type chart I'm trying to develop isn't what I understood a library chart to be – thanks for the clarification. 👍
