### ISSUE TITLE
GitHub's releases links for 2.x checksums are broken

### ISSUE THREAD

**Issue by szymonpk** [helm/helm#8899]
I have tried to download checksums from the repo's releases page, link for 3.x checksums work but for 2.x I am getting 404, for example:

https://get.helm.sh/helm-v2.16.12-linux-amd64.tar.gz.sha256sum
https://get.helm.sh/helm-v2.16.11-linux-amd64.tar.gz.sha256sum

I have not checked older versions.

**Comment by bacongobbler** [comment]
Apologies for that. The correct links for helm 2 use .sha256 as the extension. Just replace “sha256sum” with “sha256”. I’ll fix up the release notes in the morning.

**Comment by hickeyma** [comment]
Good catch @szymonpk. Thanks for finding this.

2.10 is ok.
