### ISSUE TITLE
Helm upgrade --install thinks a release still exists after deleting

### ISSUE THREAD

**Issue by kashline-ae** [helm/helm#8900]
Output of `helm version`:
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
EKS

I'm attempting to update a Deployment object with the correct apiVersion required due to a kubernetes upgrade, but helm is complaining it's unable to perform the diff:

`Error: UPGRADE FAILED: current release manifest contains removed kubernetes api(s) for this kubernetes version and it is therefore unable to build the kubernetes objects for performing the diff. error from kubernetes: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"
helm.go:84: [debug] unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"`

So I tried to delete the release and the history so it wouldn't need to perform any diff, but for some reason I'm continuing to get the above error.  I can't find the history for this release either, but it's clearly still keeping it somewhere.

`helm -n dev3 history pcs-frontend-dev3
Error: release: not found`

Attempts to create a new release results in a failure due to resources associated with the previous release still existing:

`Error: rendered manifests contain a resource that already exists. Unable to continue with install: ConfigMap "pcs-frontend" in namespace "dev3" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "pcs-frontend-test": current value is "pcs-frontend-dev3"`

The first time I tried to create a new release the CM actually did exist so I deleted it.  Subsequent runs resulted in the same error, despite the fact `kubectl -n dev3 get cm` does not return any cm associated with the `pcs-frontend-dev3` helm release.

To reproduce, I suppose you would need an eks cluster capable of having a deployment using `extensions/v1beta1` apiVersion managed by a helm release.  You would then need to upgrade the cluster so `extensions/v1beta1` is no longer a valid deployment apiVersion, then follow the steps above.

**Comment by mattfarina** [comment]
I think I see the problem. This isn't saying the Helm release is present but that there's a Kubernetes manifest (resource) in the cluster that has the same name as one of the generated ones. If Helm were to install it an existing Kubernetes resource would be overwritten so it is bailing out with an error.

Does that make sense?

**Comment by kashline-ae** [comment]
My specific situation was due to PEBKAC.

However in order to redeploy the chart I had to delete the helm release and all manifests.
