### ISSUE TITLE
deployment / replicaset issue helm / terraform-helm

### ISSUE THREAD

**Issue by FLavalliere** [helm/helm#8904]
gke 1.17
helm 3.3.4
terraform-helm (latest)

https://github.com/hashicorp/terraform-provider-helm/issues/606

somehow when upgrading via terraform helm / helm the  current replicaset pods are terminated and new ones are created for the previous 'replicaset'.

At the same time the new replicaset also creates new pods. 

The beavior should be identical to kubectl edit deployment but it seems that via Helm 3.3.4 the deploymentupdate screw up the replicaset? Not too sure why...

**Comment by FLavalliere** [comment]
It looks like using an older helm provider,  ie: hashicorp/helm v1.2.0

Basically an older version it seems better.....

with 3.3.4 if i used force_update = true it seems to do rolling update but chrashes on kind: Services  cannot set clusterIP to "" which is related to another bug i've seen in this helm repo

**Comment by mattfarina** [comment]
I'm not entirely sure if what you're seeing is a Kubernetes issues, terraform-helm issue, a Helm issue, or something in the chart itself. So, it might take a little bit to figure out.

When the application was last installed, was Kubernetes at version 1.17 or was it an older version? What was the api version on the Deployment at that time? Is there just one deployment and replicaset or is there more than one of those after the upgrade?

**Comment by FLavalliere** [comment]
This always been Kubernetes 1.17

the kubectl edit of deployment works like a charm, and follow the rollingUpdate Strategy.

When I use latest helm and force_update = true  vs force_udpate = fasle

One of them behave properly but fails due to the following bug https://github.com/helm/helm/issues/7956

**Comment by FLavalliere** [comment]
I believe it also have something to do with the revisionHistoryLimit. 

The use of 
```
  revisionHistoryLimit: 0
```

Seems to have huge impact / correct the issue. IF set > 0 it seems to have problems

**Comment by bacongobbler** [comment]
@FLavalliere were you able to determine the issue? Trying to determine if there's a bug in Helm or if this is a chart issue, in which case a ticket should be filed against the chart.

**Comment by FLavalliere** [comment]
I'd be surprised its a chart issue. I mean the chart works well...

If we manually edit the k8s 'deployment' to update something such as the docker image it works well, ie: perform the rolling update as needed.

But either terraform or helm recreate the 'old replicaset' which terminates all the existing pods with the OLD image and then recreate with the OLD image. Then perfom the creation of new replicaset with the new IMAGE doing rolling update.

I'm not too sure what changes in the old replicaset that would tell kubernetes to terminate all running pods...
