### ISSUE TITLE
Where do I find helm 3 charts?

### ISSUE THREAD

**Issue by hatharom** [helm/helm#8908]
As helm2 is deprecated I started to look for helm 3 charts instead of my currently used helm2 ones.
Where should I find those? 

I only have encountered helm2 charts with apiversion 1.

Even on the helm hub: https://artifacthub.io/   I randomly search for a chart and it will be helm2 guaranteed.
Rancher's repo : https://github.com/rancher/helm3-charts    ,  no.. they are not helm3 but helm 2.

So where are the corresponding helm3 charts for the deprecated ones (for common public projects like psql,kafka,elasticsearch..etc)?

**Comment by hickeyma** [comment]
Helm v2 charts can also be installed in Helm v3.  A chart does not need to be updated to `apiVersion: v2` unless it uses [CRDs](apiVersion: v1) which changed in Helm v3. Additionally, a chart can also be updated if the chart maintainer wishes to use the latest capabilities in Helm v3.

**Comment by hickeyma** [comment]
To clarify, it depends on the chart and chart maintainer if a chart with `apiVersion: v2` is provided.

Hope this answers your question.

**Comment by mattfarina** [comment]
@hatharom It will likely be awhile before people switch to Helm v3 only charts. The reason for that is Helm v2 is still widely used and people want to support both for now. Helm v2 is going to hit the end of life for support and we are working to help people transition. I would hope that 6 months from now we see far more Helm v3 only charts.

**Comment by bacongobbler** [comment]
closing as answered.

**Comment by hatharom** [comment]
Thanks the responses.
I am aware of that chart version is depends on the chart maintainers.

But as I stated above I dig up the whole the web and couldn't find any Helm 3 chart.
Pretty strange..

**Comment by hickeyma** [comment]
@hatharom Here is a notice from Bitnami about updating to `apiversion: v2`: https://github.com/bitnami/charts#important-notice-helm-v2-eol-warning
