### ISSUE TITLE
[Feature] --delete-namespace option for helm uninstall

### ISSUE THREAD

**Issue by dfang** [helm/helm#8911]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

```
Docker for mac
```

There is a `--create-namespace` option for `helm install`, why no `--delete-namespace` option for `helm uninstall` ?

I will try to send a PR if this feature is acceptable  ?

**Comment by marckhouzam** [comment]
Thanks @dfang for the idea.  It does sound logical. However unlike creating a namespace which is a relatively safe operation, deleting a namespace is destructive.

The namespace containing a helm release could contain many other releases or kubernetes resources, so a particular helm uninstall trying to remove the entire namespace could have undesired consequence on the cluster.

**Comment by dfang** [comment]
how about add some notes to command help or make use answer "yes" ?

**Comment by marckhouzam** [comment]
Considering how easy it is to run `kubectl delete namespace` after a `helm uninstall` command, I think adding a `--delete-namespace` flag would introduce more risk and mistakes than the added value.

**Comment by bacongobbler** [comment]
I also would have to agree with @marckhouzam on this one. Just use `kubectl delete namespace` after a `helm uninstall` if you want to remove the namespace. -create-namespace is just there for convenience as it’s a risk-free operation. Deleting the namespace introduces an increased level of risk to the user and could lead to unintended consequences. For that reason, I do not believe this should be introduce to helm.
