### ISSUE TITLE
Argument issue

### ISSUE THREAD

**Issue by kkso3838** [helm/helm#8914]
Output of `helm version`: v3.3.1
ubuntu@ubuntu-vm:~$ h version
version.BuildInfo{Version:"v3.3.1", GitTreeState:"clean", GoVersion:"go1.14.7"}

Output of `kubectl version`:v1.19.0
ubuntu@ubuntu-vm:~$ k version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", 
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", 

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Hyper-V

I find the following error for .Files.Get "scripts/wait_database_init.sh": <(.Files.Get "scripts/wait_database_init.sh") . | nindent 12>: can't give argument to non-function .Files.Get "scripts/wait_database_init.sh"

Would you please shed some light on this error. The .yaml worked fine in previous version of kube and helm.

**Comment by mattfarina** [comment]
The value of `.` can change depending on context. This happens inside of functions like `with`. Without seeing the whole template I can't say why this might be happening.

`$` points to the initial `.` in a template. Have you tried `$.Files.Get` to see if that works?

**Comment by kkso3838** [comment]
Thank you very much for your suggestion! But I get the same error:
"scripts/wait_database_init.sh": <($.Files.Get "scripts/wait_database_init.sh") . | nindent 12>: can't give argument to non-function .Files.Get "scripts/wait_database_init.sh"

I suspect the new version of helm has some changes in synthax check which I am not too familiar with.

**Comment by bacongobbler** [comment]
`.Files.Get` accepts only one argument: the name of the file. It looks as though you are passing a second argument: the dot operator. Remove dot from the argument list and it should work.

`$.Files.Get "scripts/wait_database_init.sh" | nindent 12`

**Comment by bacongobbler** [comment]
See also #7711.

**Comment by bacongobbler** [comment]
closing as answered/inactive. Let us know if you need further assistance.
