### ISSUE TITLE
Helm template function

### ISSUE THREAD

**Issue by shahriak** [helm/helm#8917]
How do I create a template function to create an expiry date that is in the format "2021-10-19T01:55:50Z", I have tried the following but it does not seem to give me the proper output.  Any help would be appreciated!

{{.Values.identity.issuer.crtExpiryAnnotation}}: {{now | date_modify "+8760h" | date "YYYY-MM-DDT'hh:mm:ss'Z" | toDate "YYYY-MM-DDT'hh:mm:ss'Z"}}

Reference: https://masterminds.github.io/sprig/

**Comment by mattfarina** [comment]
The input to the `date` function is in the wrong format. This is a product of it using Go template. There are directions at https://helm.sh/docs/chart_template_guide/function_list/#date. You might want a section like `{{now | date_modify "+8760h" | date "2006-01-02T'15:04:05'Z" }}`.

**Comment by shahriak** [comment]
Thanks a lot for your answer, This seems to almost work except I am seeing the quotes in the date 2021-10-19T'11:41:29'Z which needs to be escaped. I tried this but it doesn't seems to work 2021-10-19`'T`'11:41:29`'Z`'

**Comment by mattfarina** [comment]
@shahriak The quotes you are seeing are in your original pattern. If you want those remove you can remove them from the pattern.... like `date "2006-01-02T15:04:05Z"`. If you want to keep them you could put a `| quote` on the end to wrap the output in double quotes.

Doe that help?

**Comment by bacongobbler** [comment]
Hi @shahriak. It looks as though the comments provided by @mattfarina should resolve your issue. As such I am closing out this issue. If you require further assistance please don't hesitate to reach out. Thanks!
