### ISSUE TITLE
Parameterize placeholder

### ISSUE THREAD

**Issue by probenx** [helm/helm#8919]
Hey, 

How could I parameterize this?

`{{ .Values.secrets.amqpUsername | b64enc }}`

I need the "amqp" part to be a placeholder. 
I have tried many variations

The furthest this seems to get: 
`{{ ".Values.secrets.{{ .Release.Name }}Username" | b64enc }}`

But this gives the following error:

`timed out waiting for the condition`

**Comment by mattfarina** [comment]
This can be done but I learned that two of the template functions needed for this are not documented.

```
{{ printf "secrets.%sUsername" .Release.Name | .Values.PathValue | b64enc }}
```

The `printf` function will let you set a parameter to be replaced in a string. `%s` tells the function it is a string. `.Values.PathValue` provides a ways to pass a string as a path for a key and to get the value out.

Hope that helps.

**Comment by probenx** [comment]
Thank you!
