### ISSUE TITLE
helm repo search finds versions with dashes in them

### ISSUE THREAD

**Issue by thernstig** [helm/helm#8924]
Output of `helm version`:
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-06-03T10:06:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

Doing a `helm repo search test` gives:
```sh
$ helm search repo test
NAME                    CHART VERSION   APP VERSION     DESCRIPTION
repoA/test              1.17.0-0565674  0565674         A Helm chart for test
```

I thought that only chart versions that had the form `x.x.x` would be shown and not `x.x.x-x`. The latter should only be found if using `--devel`. Did I misunderstand this, or is this a bug?

**Comment by mattfarina** [comment]
I've tried to replicated the problem and have been unable to. I tried on both mac and linux using downloaded releases and building Helm myself. Using v3.3.4 and the latest unreleased code.

You're understanding that you need to use the `--devel` flag to list pre-releases (form of `x.x.x-x`) is right.

I've tentatively marked this as question/support as we try to figure out why this is happening.

How many versions of the chart are in your Helm repository? Are there a lot for this particular chart? Are there any other details you can share?

**Comment by thernstig** [comment]
Could it be due to the fact that the first character after the dash is a 0 (zero)? I am definitely just doing a `helm search repo test` and get the result I show above. Which I should not, as the chart version is `1.17.0-0565674`, right?

**Comment by mattfarina** [comment]
First, the leading 0 is causing this issue. I just reproduced it with that.

Second, a leading 0 in a pre-release of a semantic version is not allowed. See https://semver.org/#spec-item-9 which says:

> Numeric identifiers MUST NOT include leading zeroes.

This is in reference to pre-releases.

This is likely why it has not come up before or often. We should still handle the situation.

**Comment by thernstig** [comment]
Yes, I do realize that a leading 0 is not correct, it is an old release that had this problem. But the fact then remains that if there was ever such a problem with such a build, that would show up such as in our scenario. Great that you will still look into fixing it.

**Comment by wawa0210** [comment]
Is anyone following this issue, if not, I am willing to try to fix it

**Comment by mattfarina** [comment]
@wawa0210 That would be great. If you have questions while trying please feel free to ask.
