### ISSUE TITLE
helm fetch/pull and search return different results

### ISSUE THREAD

**Issue by felipecrs** [helm/helm#8925]
This is a follow-up of https://github.com/helm/helm/issues/8865#issuecomment-706278516.

> I wonder why the `helm fetch` behaves differently than `helm search` when finding the latest version:
> 
> ![image](https://user-images.githubusercontent.com/29582865/95608185-9c6c5800-0a11-11eb-87db-cfc989abe57d.png)
> 
> ![image](https://user-images.githubusercontent.com/29582865/95608592-30d6ba80-0a12-11eb-98ac-4d3d8102e097.png)
> 
> The mismatch between `fetch` and `search` should be considered a problem, I think.

Related to https://github.com/helm/helm/issues/4132.

**Comment by bacongobbler** [comment]
What is the expected result? Even if we fixed this, helm fetch would still result in a random build metadata version. How would that solve your issue?

**Comment by felipecrs** [comment]
That would not solve the issue I had regarding build metadata. But this is something else. I believe the behavior between then should be equal, since both are calculating the latest version, so they should calculate the latest version using the same technique.

**Comment by mattfarina** [comment]
I'm not sure the best way to handle this process wise.

First, I looked and here is an explanation.

On fetch/pull the index is loaded and the chart versions are sorted. If no version is passed to helm for the command, it will look for the highest release (not pre-release) using the `*` constraint. If a version is passed something different happens. It first looks to see if that exact version exists for a chart. If it does it will use that. If not a constraint is created and the highest version to match it is found.

Search, which hasn't changed in 4 years, uses a different mechanism to handle sorting. It is using more rudimentary functions on the semver package.

This different set of sorting methods is what likely has an impact.

I'm marking it as a feature that they should be the same. We could try to work this out for 3.5 if someone wants to try to change it.

**Comment by bacongobbler** [comment]
@felipecrs is this something you were looking to fix?

**Comment by felipecrs** [comment]
I really would like to, but I'm actually more interested in https://github.com/helm/helm/issues/8479 (which seems to be very advanced already in the implementation, and simpler for a newbie). I have no experience with Go though, so I can't commit to doing anytime soon.
