### ISSUE TITLE
Helm Lint prints one error and then ends

### ISSUE THREAD

**Issue by meh98943** [helm/helm#8934]
This may or may not be a feature request, but it would be really nice if running the command `helm lint` would print more than one error at a time. The behavior I'm seeing currently is that the lint ends upon first error detected. Is that by design, and/or am I missing something?

Output of `helm version`: version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T18:49:28Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Mac OS

**Comment by bacongobbler** [comment]
IIRC `helm lint` is designed to report all errors, though we'd welcome changes to if there were bugs in the system that only reported those errors one at a time.

https://github.com/helm/helm/blob/11077a4991a9501e2d056c32eb6cb0c69212b287/pkg/lint/support/message.go#L38

**Comment by bacongobbler** [comment]
updating to a bug after an initial code review of pkg/lint.

**Comment by donggangcj** [comment]
If possible, I am willing to fix this bug.

**Comment by mattfarina** [comment]
@donggangcj Go ahead. We look forward to your PR.

**Comment by bacongobbler** [comment]
@meh98943 can you please provide a test case we can use to verify this issue?

**Comment by meh98943** [comment]
[test-chart.zip](https://github.com/helm/helm/files/5466506/test-chart.zip)
See attached. You should be able to do `helm lint` in that top level directory and see numerous values unknown.

Below is an example of the first error I see when running that cmd. 
```
==> Linting .
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: template: test-chart/templates/tests/test-connection.yaml:14:63: executing "test-chart/templates/tests/test-connection.yaml" at <.Values.service.port>: nil pointer evaluating interface {}.port
```

**Comment by meh98943** [comment]
I see, so the errors I'm getting aren't a part of the lint'ing yet, just the preparation for lint'ing. 
At this time I don't have any further information or an example of multiple errors not printing during the lint'ing process.

**Comment by donggangcj** [comment]
> Okay. That error case makes sense here... text/template is effectively telling you that it cannot continue parsing the template, so it stops rendering due to a missing value. There's not much we can do in this case.
> 
> The linter runs against valid template outputs and reports any invalid rulesets... But if it can't render the templates at all, then it can't get to the linter.
> 
> To clarify, there's a few steps involved during `helm lint`:
> 
> 1. Fetch the chart
> 2. Unpack the chart
> 3. Render the chart
> 4. Run the linter rulesets
> 
> So based on the error output, it's failing on step 3 before it's even hit the ruleset. So I'm not sure there's a way we can fix that.
> 
> Let us know if you find out anything else.

Yes, so far, this is in line with the design.

**Comment by bacongobbler** [comment]
Closing for now. This appears to be intentional behaviour.

Let us know if you run into further issues. Thanks!
