### ISSUE TITLE
go panic with plugin downloader

### ISSUE THREAD

**Issue by jkroepke** [helm/helm#8935]
Today I saw that helm does support downloader plugins. -> https://helm.sh/docs/topics/plugins/#downloader-plugins

The documentation of helm described how it works together with charts.

Looking at source, downloader plugins should also able to work with value files, but they don't:

```
jkr@joe-nb helm-secrets % helm template test -f sops:///tests/assets/values/sops/secrets.yaml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x22a1867]

goroutine 1 [running]:
bytes.(*Buffer).Bytes(...)
        /usr/local/Cellar/go/1.15.2/libexec/src/bytes/buffer.go:54
helm.sh/helm/v3/pkg/cli/values.readFile(0xc000044840, 0x2d, 0xc00099a340, 0x2, 0x2, 0x3854108, 0x0, 0x1, 0xc00038e470, 0xc000493da0)
        /private/tmp/helm-20200923-64956-rldbbk/pkg/cli/values/options.go:120 +0x167
helm.sh/helm/v3/pkg/cli/values.(*Options).MergeValues(0xc0006b0a80, 0xc00099a340, 0x2, 0x2, 0x1, 0x1, 0x1)
        /private/tmp/helm-20200923-64956-rldbbk/pkg/cli/values/options.go:48 +0x115
main.runInstall(0xc0003a26c0, 0x1, 0x3, 0xc0002aa640, 0xc0006b0a80, 0x28942a0, 0xc000130008, 0xc00053da88, 0x11, 0x33cfbb8)
        /private/tmp/helm-20200923-64956-rldbbk/cmd/helm/install.go:192 +0x325
main.newTemplateCmd.func2(0xc0006a8dc0, 0xc0003a26c0, 0x1, 0x3, 0x0, 0x0)
        /private/tmp/helm-20200923-64956-rldbbk/cmd/helm/template.go:70 +0x12b
github.com/spf13/cobra.(*Command).execute(0xc0006a8dc0, 0xc0003a2690, 0x3, 0x3, 0xc0006a8dc0, 0xc0003a2690)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002cf600, 0xc000130e90, 0x1, 0xc000939f60)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /private/tmp/helm-20200923-64956-rldbbk/cmd/helm/helm.go:93 +0x24d
```
Note: Chart doesn't matter. In this case, I create `test` via `helm create test`.

Plugin Code:
https://github.com/jkroepke/helm-secrets/tree/downloader (Branch: downloader)

Source Code: https://github.com/helm/helm/blob/9b42702a4bced339ff424a78ad68dd6be6e1a80a/pkg/cli/values/options.go#L107-L121

I would like to use this to hook into reading value files without creating a whole wrapper for the helm command. 

Output of `helm version`:
```
helm version
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}
```

**Comment by mattfarina** [comment]
There is a bug here because there should not be a panic if there is an issue working with the downloader.

The reason for the panic is because of an error in the plugin. There are two issues right now...

1. In the `plugin.yaml` the section on downloaders should be...

```
downloaders:
  - command: "scripts/downloader.sh"
    protocols:
      - "sops"
      - "secret"
```

The wrong location was causing an underlying error of:

```
fork/exec /path/to/helm/plugins/helm-secrets/$scripts/downloader.sh: no such file or directory
```

2. `downloader.sh` isn't working. Not for the passed in location.

**Comment by jkroepke** [comment]
Thanks for figure out my bugs. that helps a lot. I couldn't see them since helm just panic here. I guess report a panic is always valid.

Like you said, this issue is just about the panic.

**Comment by bacongobbler** [comment]
HELM_PLUGIN_DIR should be available for install hooks. https://github.com/helm/helm/blob/82f739072cb3c94f26e3103e4524a1f74526342d/cmd/helm/plugin.go#L63

**Comment by bacongobbler** [comment]
If you find an issue, PRs and bugfixes with test cases are always welcome.

**Comment by bacongobbler** [comment]
this line may be causing the issue where plugin settings are not being passed to the downloader plugin.

https://github.com/helm/helm/blob/9b42702a4bced339ff424a78ad68dd6be6e1a80a/pkg/getter/plugingetter.go#L73-L74

Feel free to write a unit test surrounding `pluginGetter.Get()` to verify this issue.

**Comment by jkroepke** [comment]
Right now everything works fine in my enviroment except the plugin raises an error. Then helm will panic as initial described.

**Comment by wawa0210** [comment]
Is anyone already following up? If not, I am willing to fix

**Comment by bacongobbler** [comment]
nope, feel free

**Comment by jkroepke** [comment]
Unstale

**Comment by jkroepke** [comment]
Unstale
