### ISSUE TITLE
Dependency template overrride

### ISSUE THREAD

**Issue by gerasym** [helm/helm#8937]
Output of `helm version`:
`version.BuildInfo{Version:"v3.1.0", GitCommit:"b29d20baf09943e134c2fa5e1e1cab3bf93315fa", GitTreeState:"clean", GoVersion:"go1.13.7"}`

Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
`kops with aws`

Could not find the answer not on the internet or in the issues. Is it possible to set a dependency in your chart and override templates in dependency? For example i want to override the https://github.com/helm/charts/blob/master/stable/oauth2-proxy/templates/configmap.yaml in my chart. I create the same file in my chart's templates and change it the way i need it.

when i run `helm install --debug --dry-run proxy proxy/ | less` i see in the output 2 ConfigMaps are rendered: one from dependency chart and one from local. And this leads to error when i run it without --dry-run complaining `Error: configmaps "oauth2-proxy" already exists`

**Comment by aramhakobyan** [comment]
+

**Comment by bacongobbler** [comment]
It is not possible to override a template within a dependency. However, you can modify the output using a post-renderer like kustomize. See https://helm.sh/docs/topics/advanced/#post-rendering for more details.

**Comment by bacongobbler** [comment]
closing as answered.
