### ISSUE TITLE
Not able to give custom Config file for Prometheus Adapter Helm Chart

### ISSUE THREAD

**Issue by pulkitsapra** [helm/helm#8943]
I am using this Prometheus Adapter to expose` celery_tasks_total` as a custom metric from Prometheus.
This adapter is installed using Helm 3 as follows :

`helm install --generate-name prometheus-community/prometheus-adapter`

I want to provide my custom Config-Map to this adapter. I have tried the way instructed in the Readme for the Prometheus Adapter repository. But I am unable to do so.

- I tried using `--config` argument which is not a valid argument in Helm 3.

- I also tried giving it as follows `helm install --generate-name prometheus-community/prometheus-adapter --set-file config='/home/user/path_to_config.yaml'` but when I check the Config-Map in the Kubernetes Dashboard, I still see this default Config-Map that gets shipped with the prometheus adapter helm chart.

Can anyone help me with the process of supplying a custom config map manifest to this Helm Chart?

**Comment by bacongobbler** [comment]
Please open issues with the prometheus adapter chart with the Prometheus adapter maintainers. They would know more information to answer your question.

**Comment by pulkitsapra** [comment]
They say to open in helm.. you guys say to open in theirs.. Can you help me out on how to give config file to any helm chart in gen ?

**Comment by bacongobbler** [comment]
I assume you're referring to https://github.com/DirectXMan12/k8s-prometheus-adapter/issues/326.

> Please open an issue in the helm repository itself.

What the author meant was to open an issue with the k8s-prometheus-adapter **chart** maintainers. Not the Helm maintainers.

https://github.com/prometheus-community/helm-charts

**Comment by pulkitsapra** [comment]
Thanks A Ton! I ll open it there
