### ISSUE TITLE
Are helm ownership label/annotations applied to hook resources as well?

### ISSUE THREAD

**Issue by james64** [helm/helm#8944]
Versions
 * Helm `version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}`
* Kubectl `Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}`
* Cloud provider is Digital Ocean

Helm applies label `app.kubernetes.io/managed-by: Helm` and annotations `meta.helm.sh/release-name`, `meta.helm.sh/release-namespace` automatically to every resource it creates. Is this the case for resource created as hook? It looks like it does not so I would like to confirm this and also to understand if there is any good reason for this.

*My usecase*

I am installing [sentry](https://sentry.io) using [this helm chart](https://github.com/sentry-kubernetes/charts/tree/develop/sentry). The chart is handling order in which various components goes up by using hooks. On initial fresh install subset of resources is created as hooks (`.Values.asHook=true`) while later upgrades are supposed to be installed as regular resource objects (`.Values.asHook=false`). In my exprience this upgrade is failing with this error:

```
"Error: UPGRADE FAILED: rendered manifests contain a resource that already exists.
Unable to continue with update: Deployment "sentry-relay" in namespace "infra-sentry" exists and cannot
be imported into the current release: invalid ownership metadata; label validation error: missing key
"app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key
"meta.helm.sh/release-name": must be set to "sentry"; annotation validation error: missing key
"meta.helm.sh/release-namespace": must be set to "infra-sentry"
```

After digging around a bit I think this is because helm is not annotating hook objects as described above. A possible way out of this for me is to add these label/annotations manually [as part of chart](https://github.com/sentry-kubernetes/charts/issues/217) and call it a day. However I wonder cannot Helm add these metadata to hook resources as well? It looks like all semantics would hold. It certainly is managed by helm, present in the namespace and part of the release. Maybe "part of the release" is debatable. On the other hand going through [source code](https://github.com/helm/helm/blob/593fec6868d7a239032cf234b530aee6f5d52708/pkg/action/validate.go#L40) it looks like helm is using these "only" to ensure it will not mess up with resources created by somebody else which would be ok here as well.

What do you think?

**Comment by bacongobbler** [comment]
As described in the documentation, Helm does not control the lifecycle of hooks, so yes this is to be expected.

**Comment by james64** [comment]
Thanks. One more thing I still wanted to ask. The error above (cannot be imported) is not occuring all the time. In fact usually it is ok but not always. Any idea of why this might be the case?

**Comment by bacongobbler** [comment]
That error occurs when a resource is already present in the cluster that a helm install is attempting to overwrite.
