### ISSUE TITLE
how to decode configmap of helm using kubectl 

### ISSUE THREAD

**Issue by plusices** [helm/helm#8951]
Output of `helm version`:2.14.3

Output of `kubectl version`:14.8

Cloud Provider/Platform (AKS, GKE, Minikube etc.): aks

I want to use kubectl command to get helm information ,just like 
 kubectl get cm my-service-develop.v443 -n kube-system -o jsonpath='{.data.release}' | base64 -D | gzip -d 
and This is part of the information it returns :

my-service-develop�
"�1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace develop -l "app.kubernetes.io/name=my-service-develop,app.kubernetes.io/instance=my-service-develop" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl port-forward $POD_NAME 8080:80

�������
      ��������*Upgrade complete��
D
my-service"1.0.0*my-serviceRv1j1.0.0�

There are a lot of garbled code in the returned results, which is not what I expected.How to decrypt to get the result without garbled code?The reason why I don't use helm command is that I want to use Python program to read the configmap about helm release.Who can help me solve this problem? Thank you!

**Comment by bacongobbler** [comment]
Helm 2 stores release metadata as grpc protocol buffers. You’ll need to use a tool like `protoc` to decode the release metadata.

**Comment by plusices** [comment]
@bacongobbler  OK, I got it. I'll look up somethings about grpc in python. Thanks very much for your reply.
