### ISSUE TITLE
Feature: Sign Helm package that is a .tgz

### ISSUE THREAD

**Issue by xrow** [helm/helm#8956]
The helm package --sign command only allows to sign a package if it is untared. I am currently working on a resign process and i figured out that it is help full to sign a package if a tgz also exists. I believe that the SHA will change if I would untar and package again. Since I want a consistent SHA it would be help full to have something like skopeo has which is a `helm sign-standalone chart-0.0.0.tgz` command. https://github.com/containers/skopeo/blob/master/docs/skopeo-standalone-sign.1.md 

An alternative would be to allow helm package to have a .tgz as arg instead of a dir. But this would not make much sense from the semantics.

**Comment by mattfarina** [comment]
@xrow In the short term you could use a plugin like https://github.com/technosophos/helm-gpg to do it.

**Comment by xrow** [comment]
This for the tip and thanks for considering this feature.

**Comment by bacongobbler** [comment]
I could see this as a useful standalone plugin:

```
$ helm resign ./mychart-0.1.0.tgz
```

@xrow have a look at the documentation for "Writing a Plugin". Let u sknow if you run into any issues.

https://helm.sh/docs/topics/plugins/#helm
