### ISSUE TITLE
Helm list -A doesn't show charts that are in `pending-install` status

### ISSUE THREAD

**Issue by pamido** [helm/helm#8959]
Output of `helm version`:
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): OCI

helm  list -A --kube-context ... 

shows only the charts that their status is deployed.

It would be helpful to show also charts that are in `pending-install` or `failed` or any other status.

Thank you

**Comment by mattfarina** [comment]
There are a couple of flags that will help you with this. The `--failed` and `--pending` flags. Or you can use the `-a`/`--all` flag to see all status.

Looking at the history my guess for why this happens is that Helm uses SemVer and that includes for output strings. Changing strings in some ways will break tools that use the output of Helm as input to them. When Helm v2 launched it didn't show all status. This was added shortly after using a flag for backwards compatibility. This has been carried along.

I wonder if Helm v4 should show these by default.

**Comment by bacongobbler** [comment]
In the past we excluded certain release statuses from showing up in `helm list`. Some cases like the DELETED state was something we did not want to display. but I think it'd be worth considering for Helm 4 now that the release ledger is purged by default on `helm uninstall`.
