### ISSUE TITLE
I want be able to install charts from the Azure Container Registry

### ISSUE THREAD

**Issue by bplasmeijer** [helm/helm#8962]
Output of `helm version`: version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"}

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

Hi,

I try to get my head around Helm, and the [Azure Container Registry](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-helm-repos)

The goal,  I want to store images and charts on my public and private [ACR](https://azure.microsoft.com/en-us/services/container-registry/).

On experimental at the moment: ```export HELM_EXPERIMENTAL_OCI=1```
## I can do
-  I can push my chart to ACR
-  I can pull my chart from ACR to the local cache
-  I can export the chart to a local folder
-  I can install my chart from the local folder, ```helm install NAME path_to_helm_chart```
-  I can query my ACR  helm charts using the [Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) ```az acr repository show --name mycontainerregistry --repository helm/hello-world```, and ```az acr repository show-manifests --name mycontainerregistry --repository helm/hello-world --detail```
## I cannot do
- I can not add my ACR registry with ```helm repo add ACR```
- I can not run ```helm install NAME ACR/my_chart```
- I can not run ```helm repo update```
- I can not use [Helm Dependency](https://v3.helm.sh/docs/helm/helm_dependency/), I am limited to the ```helm chart export``` to local cache.

I found a [HIP](https://github.com/helm/community/blob/master/hips/hip-0006.md) on the Helm community repository.

cc: @SteveLas @jdolitsky

**Comment by bacongobbler** [comment]
These action items are tracked as part of the HIP and are yet to be implemented. The HIP is just the proposal; now we have to actually put in the work.

In response to your asks:

- `helm repo add` - `helm repo` is tied to the chart repository API. It is irrelevant to OCI registries. There is no plan to implement `helm repo add` for OCI registries. The syntax will be quite similar to Docker's `docker run myrepo/myimage`, but with `helm install NAME myrepo/mychart`. More information will be shared in the documentation when this feature is more stable.
- `helm install NAME acr/my_chart` - https://github.com/helm/helm/pull/8843
- `helm repo update` - also https://github.com/helm/helm/pull/8843
- using `helm dependency` - #8443.

I'm going ahead and closing this as there are other existing tickets in the queue tracking this work. Thank you.

**Comment by bplasmeijer** [comment]
> These action items are tracked as part of the HIP and are yet to be implemented. The HIP is just the proposal; now we have to actually put in the work.
> 
> In response to your asks:
> 
> * `helm repo add` - `helm repo` is tied to the chart repository API. It is irrelevant to OCI registries. There is no plan to implement `helm repo add` for OCI registries. The syntax will be quite similar to Docker's `docker run myrepo/myimage`, but with `helm install NAME myrepo/mychart`. More information will be shared in the documentation when this feature is more stable.
> * `helm install NAME acr/my_chart` - #8843
> * `helm repo update` - also #8843
> * using `helm dependency` - #8843.
> 
> I'm going ahead and closing this as there are other existing tickets in the queue tracking this work. Thank you.

thanks for the heads up @bacongobbler
