### ISSUE TITLE
Use /latest to get just the latest release

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [helm/helm#8967]
Right now we are using `https://github.com/helm/helm/releases` which returns all the releases:
https://github.com/helm/helm/blob/9aa0fbee6c118dfb0a32fa7026b27eebd0e74fb6/scripts/get-helm-3#L107

If we use `https://github.com/helm/helm/releases/latest` it will give us the page with only the latest release.

**Comment by bacongobbler** [comment]
“Latest” relates to the release that was most recently released. When a new version of Helm 2 is released, this version becomes “latest”. So we cannot use the “latest” release page for this reason.
