### ISSUE TITLE
How to access other sub-chart template file in sub-chart. 

### ISSUE THREAD

**Issue by himmakam** [helm/helm#8971]
I have two sub-charts A and global. In chart A/templates/deployment.yaml, I wanted to refer to another sub-chart global/templates/somesecret.yaml. How can I do this. I need this so that I can add annotation to have the deployment triggered whenever this secret changes.

**Comment by mattfarina** [comment]
There are a few things that might help

- If you want to use [a change in a config file to cause an update you can use a checksum](https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments).
- You can have [global values shared by a chart and its subcharts](https://helm.sh/docs/chart_template_guide/subcharts_and_globals/).
- A parent chart can pull values from dependencies. You can read about it [here](https://helm.sh/docs/topics/charts/#importing-child-values-via-dependencies).

**Comment by himmakam** [comment]
Actually I am trying to use the 1st option where change in configfile causes update with checksum as below - 
checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}

Here the configmap.yaml stays in its own chart/sub-chart templates folder. But if I want to use the same to refer to another configmap.yaml which is in another sub-chart folder, how do I tweak $.Template.BasePath "/configmap.yaml"

I tried $.Template.BasePath "/../../other-subchart/templates/configmap.yaml" etc. but of no use. Could you please help here,

**Comment by bacongobbler** [comment]
You could try using `.Files.Get` instead to pull files from the `charts` directory. I'm not sure if this will work or if the `charts` directory is excluded for security purposes, but you could try there.

https://helm.sh/docs/chart_template_guide/accessing_files/#basic-example

**Comment by bacongobbler** [comment]
checking in here to see if you found a solution, @himmakam.
