### ISSUE TITLE
helm upgrade do not create new CRD in new chart.

### ISSUE THREAD

**Issue by hustclf** [helm/helm#8972]
**Describe the bug**
helm upgrade do not create new CRD in new chart.

**To Reproduce**
I have a chart with two version `v1` and `v2`, `v2`  add a new CRD compared with `v1`

1. install with chart version  v1
```
helm install {release_name} --version v1
```
2. upgrade with chart version v2.  add a new CRD compared with `v1`.
```
helm upgrade --install {release_name} --version v2
```

**Expected behavior**
new CRD created after helm upgrade.

**Versions (please complete the following information):**
 - Ambassador: [e.g. 0.32.1]
 - Kubernetes environment [bare metal v1.16.2]
 - Version [3.2.4]

**Additional context**
Because release v1 has existed, so `action/upgrade.go` will  be executed finally, which seems not create new CRD.

**Comment by mattfarina** [comment]
This is on purpose. Changing a CRD can easily break a cluster. There is a good write-up at https://github.com/helm/community/blob/f9e06c16d89ccea1bea77c01a6a96ae3b309f823/architecture/crds.md. It explains why upgrades of CRDs are a manual step.
