### ISSUE TITLE
Helm function 'fail' should not fail when doing 'helm lint'

### ISSUE THREAD

**Issue by thernstig** [helm/helm#8973]
When executing `helm lint` directives such as this fail the linting:

```yaml
failure: {{ fail "this is a failure!" }}
```

The same problem was already fixed for the `required` function: https://github.com/helm/helm/pull/4221
An issue had already been written on `failure` but was closed due to inactivity: https://github.com/helm/helm/issues/3026

In order to lint charts using `fail` this needs to be fixed.

Reference: https://helm.sh/docs/chart_template_guide/function_list/#fail

**Comment by mattfarina** [comment]
PR welcome

**Comment by wawa0210** [comment]
Is anyone following up? If not, I can try to fix

**Comment by thernstig** [comment]
I'd like to note that both `required` and `fail` does not work either when doing a `helm template --debug <chart>`. I assume that is related.

**Comment by wawa0210** [comment]
@thernstig 

I can’t reproduce this issue, can you upload your helm chart

**Comment by thernstig** [comment]
@wawa0210 There is a simple repro here: https://github.com/helm/helm/issues/3026

**Comment by wawa0210** [comment]
> @wawa0210 You are still working on this, right? The issue got stale.

https://github.com/helm/helm/pull/9035

Another contributor mentioned a pr

**Comment by hickeyma** [comment]
Changing this to a bug because it should not fail the linting.
