### ISSUE TITLE
can not upgrade a chart when appVersion contains semVer build metadata 

### ISSUE THREAD

**Issue by andrascz** [helm/helm#8975]
Output of `helm version`: 
```
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.15.3"}
```

Output of `kubectl version`: 
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"archive", BuildDate:"2020-10-16T20:58:56Z", GoVersion:"go1.15.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"4fb7ed12476d57b8437ada90b4f93b17ffaeed99", GitTreeState:"clean", BuildDate:"2020-07-15T16:10:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Kubernetes 1.17.9 on AWS

When upgrading a helm chart where appVersion has build metadata in it:
```
ARGS:
  0: helm (4 bytes)
  1: upgrade (7 bytes)
  2: --install (9 bytes)
  3: --reset-values (14 bytes)
  4: citadel (7 bytes)
  5: development/citadel (30 bytes)
  6: --version (9 bytes)
  7: 99.99.99+bug-DIE-235-use-redis-sentinel (39 bytes)
  8: --create-namespace (18 bytes)
  9: --namespace (11 bytes)
  10: brandtegrity (12 bytes)
  11: --values (8 bytes)
  12: /tmp/values622990503 (20 bytes)
  13: --history-max (13 bytes)
  14: 10 (2 bytes)
ERROR:
  exit status 1
EXIT STATUS
  1
STDERR:
  Error: UPGRADE FAILED: cannot patch "citadel" with kind Service: Service "citadel" is invalid: metadata.labels: Invalid value: "99.99.99+bug-DIE-235-use-redis-sentinel": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?') && cannot patch "citadel" with kind Deployment: Deployment.apps "citadel" is invalid: metadata.labels: Invalid value: "99.99.99+bug-DIE-235-use-redis-sentinel": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?') && cannot patch "citadel" with kind VirtualService: VirtualService.networking.istio.io "citadel" is invalid: metadata.labels: Invalid value: "99.99.99+bug-DIE-235-use-redis-sentinel": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```

The chart was generated with helm 3.3.4

The culprit is in _helpers.tpl:
```
{{/*
Common labels
*/}}
{{- define "citadel.labels" -}}
helm.sh/chart: {{ include "citadel.chart" . }}
{{ include "citadel.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
```

This is how Chart.yaml looks like:
```
apiVersion: v2
appVersion: 99.99.99+bug-DIE-235-use-redis-sentinel
description: A Helm chart for Kubernetes
name: citadel
type: application
version: 99.99.99+bug-DIE-235-use-redis-sentinel
```

According to the [docs](https://helm.sh/docs/topics/charts/): `appVersion: The version of the app that this contains (optional). This needn't be SemVer.`, but it is even semVer as it is the same as the chart version.

**Comment by mattfarina** [comment]
This is a difficult one to handle. It might be worth putting together some documentation on it.

First, the `app.kubernetes.io/version` label is recommended by the community. But, it is not required. So, the `helm create` command has it built in.

A version with build metadata that has uppercase letters is valid for a version but it is not valid as a value for a Kubernetes label.

So, there is a mismatch and no perfect solution.

If Helm changes the default chart to force lowercase letters it's changing the version. I'm not sure if we should do that by default. A chart author could stick a [`lower`](https://helm.sh/docs/chart_template_guide/function_list/#lower) call in there and change it themselves if they are comfortable with it. Then it would be opt-in.

```
app.kubernetes.io/version: {{ .Chart.AppVersion | lower | quote }}
```

We want end-users of Helm to have a simple experience but we are willing to put more expectations on to chart creators. Is this one of those times?

I'm curious of others opinions and reasons.

**Comment by andrascz** [comment]
The problem is not the capital letter but the '+' sign. As stated in the error the regex used for validation is: `(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?`

**Comment by mattfarina** [comment]
Good catch. Suggestions are welcome.

**Comment by andrascz** [comment]
```
app.kubernetes.io/version: {{ regexReplaceAll "[^-A-Za-z0-9_.]" .Chart.AppVersion "-" | quote }}
```
I would argue that the above although would change the version, but the original version could not be deployed anyways so I wonder why should it be opt-in?

**Comment by f18m** [comment]
Hi,
I hit the same issue today. I think this bug should be re-opened... using semver (and build metadata) for Chart versioning is an important use case in my opinion...
