### ISSUE TITLE
helm strips out trailing 0 for a float with no fractional value

### ISSUE THREAD

**Issue by pguduru** [helm/helm#8978]
Output of `helm version`:
Client: &version.Version{SemVer:"v2.16.9", GitCommit:"8ad7037828e5a0fca1009dabe290130da6368e39", GitTreeState:"clean"}
( also see the same behavior with 3.4.0 )

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

I have a bunch of keys in helm values that make it into a config file ( as a configmap), eventually consumed by service/app as it starts up.  The value of the key for ex: is 3.0 , but helm although it says the type is float, will only print/output 3 ( instead of 3.0 ). This seems to be causing some issues for the app, which expects a float instead of an int/long.  

Right now, we're working around by using values like 3.0001, which render as expected. 

Here's how the my test values file looks like
```
plain_int: 3
plain_float: 3.0
plain_float_as_string: "3.0"
```

Here's my template

```
Type of plain_int as seen by heml: {{- typeOf .Values.plain_int }}
Type of plain_float as seen by helm: {{- typeOf .Values.plain_float }}
Type of plain_float_as_string by helm: {{- typeOf .Values.plain_float_as_string }}

Value of plain_int: {{- .Values.plain_int  }}
value of plain_float: {{- .Values.plain_float }}
Value of plain_float_as_string: {{- .Values.plain_float_as_string }}
```

Here's the output  of `helm template .`

```
Type of plain_int as seen by heml:float64
Type of plain_float as seen by helm:float64
Type of plain_float_as_string by helm:string

Value of plain_int:3
value of plain_float:3
Value of plain_float_as_string:3.0
```

I was expecting value of plain_float to be 3.0.

**Comment by hickeyma** [comment]
@pguduru A answer was provided by @mattfarina in https://github.com/helm/helm/issues/8799#issuecomment-698379753. Can you see if that helps? Otherwise, need to wrap as a string to maintain the fractional part.

**Comment by hickeyma** [comment]
Duplicate of #8799

**Comment by pguduru** [comment]
> @pguduru A answer was provided by @mattfarina in [#8799 (comment)](https://github.com/helm/helm/issues/8799#issuecomment-698379753). Can you see if that helps? Otherwise, need to wrap as a string to maintain the fractional part.

that does not work. 

`value of plain_float: {{-  .Values.plain_float | float64 }}
`
or

`value of plain_float: {{-  .float64 Values.plain_float }}`

both still give 3.

**Comment by mattfarina** [comment]
This is complicated and it will depend on what you are trying to do. This has to do with YAML, types, type conversions, and how they are used.

Here is something you can do. In your _values.yaml_ put:

```
foo: "3.0"
```

This will be handled as a string.

In your template put {{ .Values.foo }}. This will insert `3.0`. When the Kubernetes toolchain sees it the value will be seen as a float not a string.

You may run into similar parsing and rendering issues in the Kubernetes toolchain as Helm uses the same YAML library.

Does this help?

**Comment by pguduru** [comment]
@mattfarina  thank you. 

Both the below work if defined as a single variables in the values yaml

```
plain_float: !!float64 3.0
plain_float_as_string: "3.0"

```
{{ .Values.plain_float }} or {{ .Values.plain_float_as_string }} result in 3.0 


However, we have something like this 

```
appconfig:
  someval: 3.001
  someval1: 3.0
  someval2: 3.1
  someval3: !!float64 3.0
  someval4: "3.0"
```


and we use toPrettyJson to have the above become part of a configmap and eventually be mounted as appconfig.json. 

And toPrettyJson ( or other tojson alternatives ) never give out 3.0. they either give 3 or "3.0". 

this is what we get when we use toPrettyJson

```
{
  someval:3.001
  someval1:3
  someval2:3.1
  someval3:"3.0"
  someval4:"3.0"
}

```

the app that consumes appconfig.json expected one the key to be providing a floating point value and it runs into exception, when it get either a 3 or  "3.0". Additional casting/conversion capabilities will need to be added to the app libraries.

I am trying to find if there is a way we can avoid that and provide a float as resultant value. 

thanks

**Comment by mattfarina** [comment]
The cause of this is happening in the underlying YAML parser. Take a look at https://play.golang.org/p/xgP3PLspUwI.

**Comment by mattfarina** [comment]
I took it a step further with https://play.golang.org/p/i6DQpntZjbb. This uses the same method to product the pretty JSON that Helm does.

YAML and JSON both use exponential notation. So, something like `3e1` works. But, this is `3e0` which just gives you 3.

In JSON there is no difference between an integer and a float. There is just a number. So, `3 === 3.0` in JavaScript. There may be some JSON logic in the Go serializer that simplifies the output.

**Comment by bacongobbler** [comment]
Thank you for that test case @mattfarina.

Based on the information provided here, it does appear that this is an upstream bug with the underlying YAML parser. @pguduru can you please follow up with upstream to report this issue and work on a fix there?

**Comment by pguduru** [comment]
> Thank you for that test case @mattfarina.
> 
> Based on the information provided here, it does appear that this is an upstream bug with the underlying YAML parser. @pguduru can you please follow up with upstream to report this issue and work on a fix there?

Opened this issue - https://github.com/go-yaml/yaml/issues/671

**Comment by pguduru** [comment]
[https://github.com/go-yaml/yaml/issues/671](url)

**Comment by bridgetkromhout** [comment]
Hi, @pguduru - thanks for opening that issue with the YAML parser! If you can reproduce this issue with Helm 3, then when the upstream parser is corrected, we should see the benefit of that. However I do see that you may be using Helm v2.16.9, so please be aware we are no longer providing support for Helm 2 as of today: https://helm.sh/blog/helm-2-becomes-unsupported/

**Comment by pguduru** [comment]
> Hi, @pguduru - thanks for opening that issue with the YAML parser! If you can reproduce this issue with Helm 3, then when the upstream parser is corrected, we should see the benefit of that. However I do see that you may be using Helm v2.16.9, so please be aware we are no longer providing support for Helm 2 as of today: https://helm.sh/blog/helm-2-becomes-unsupported/

@bridgetkromhout  I see the issue with helm 3 as well. I mention it somewhere up in my original description of this issue above.

**Comment by philomory** [comment]
I think this is trickier than people are giving it credit for. Helm, when parsing YAML, doesn't convert floats to ints; quite the contrary, it converts _all_ numeric values to `float64`. It's only when rendering the data back out to a string that the `.0` suffix is dropped, probably in a somewhat misguided attempt to allow _actual_ integers to round-trip successfully. For example, given this values file:

```yaml
int: 1
float1: 1.0
float2: 1.2
```

And this template:

```
typeOf values int: {{ typeOf .Values.int }}
typeOf values float1: {{ typeOf .Values.float1 }}
typeOf values float2: {{ typeOf .Values.float2 }}
typeOf literal int : {{ typeOf 1 }}
typeOf literal float1: {{ typeOf 1.0 }}
typeOf literal float2: {{ typeOf 1.2 }}

toString values int: {{ toString .Values.int }}
toString values float1: {{ toString .Values.float1 }}
toString values float2: {{ toString .Values.float2 }}
toString literal int : {{ toString 1 }}
toString literal float1: {{ toString 1.0 }}
toString literal float2: {{ toString 1.2 }}

bare values int: {{ .Values.int }}
bare values float1: {{ .Values.float1 }}
bare values float2: {{ .Values.float2 }}
bare literal int: {{ 1 }}
bare literal float1: {{ 1.0 }}
bare literal float2: {{ 1.2 }}

valuesPrettyJson: |
  {{- .Values | toPrettyJson | nindent 2 }}

literalsPrettyJson: |
  {{- (dict "int" 1 "float1" 1.0 "float2" 1.2) | toPrettyJson | nindent 2 }}

valuesYaml: |
  {{- .Values | toYaml | nindent 2 }}

literalsYaml: |
  {{- (dict "int" 1 "float1" 1.0 "float2" 1.2) | toYaml | nindent 2 }}

valuesToml: |
  {{- .Values | toToml | nindent 2 }}

literalsToml: |
  {{- (dict "int" 1 "float1" 1.0 "float2" 1.2) | toToml | nindent 2 }}
```

Helm will render the following results:
```
typeOf values int: float64
typeOf values float1: float64
typeOf values float2: float64
typeOf literal int : int
typeOf literal float1: float64
typeOf literal float2: float64

toString values int: 1
toString values float1: 1
toString values float2: 1.2
toString literal int : 1
toString literal float1: 1
toString literal float2: 1.2

bare values int: 1
bare values float1: 1
bare values float2: 1.2
bare literal int: 1
bare literal float1: 1
bare literal float2: 1.2

valuesPrettyJson: |
  {
    "float1": 1,
    "float2": 1.2,
    "int": 1
  }

literalsPrettyJson: |
  {
    "float1": 1,
    "float2": 1.2,
    "int": 1
  }

valuesYaml: |
  float1: 1
  float2: 1.2
  int: 1

literalsYaml: |
  float1: 1
  float2: 1.2
  int: 1

valuesToml: |
  float1 = 1.0
  float2 = 1.2
  int = 1.0


literalsToml: |
  float1 = 1.0
  float2 = 1.2
  int = 1
```

So you can see, the problem isn't that the YAML parser transforms floats to integers, quite the opposite; the YAML parser transforms _integers_ to _floats_; then down the line, the _renderer_ tries to "fix" this by assuming that any float with no fractional component should be rendered in an "integer-ish" way. 

As you can see, the `toYaml` and `toJson` functions (as well `toString` and bare interpolation) render a float with no fractional part as just the whole-number part. The `toToml` function, on the other hand, renders exactly the data-type it received. This means it's impossible to get an TOML integer in data coming from a values file, because anything from a Helm values file will _always_ be a `float64`.

So, fixing this is a lot more complicated than it initially appears, requiring fixes to multiple components.

**Comment by philomory** [comment]
This is definitely not stale.

**Comment by HerrDerb** [comment]
Just ran into this again...
