### ISSUE TITLE
method get of HTTPGetter type can not get Helm chart from ACR

### ISSUE THREAD

**Issue by fredgate** [helm/helm#8980]
I use Flux Toolkit to install Helm charts from a repository hosted on Azure Container Registry.  
The source controller of Flux Toolkit use the `HTTPGetter` type to download the chart from its URL like `https://contoso.azurecr.io/helm/v1/repo/_blobs/cdn-1.0.0.tgz` using credentials.  

But it fails with the following error message :
`
{"level":"error","ts":"2020-11-03T13:10:01.741Z","logger":"controller","msg":"Reconciler error","reconcilerGroup":"source.toolkit.fluxcd.io","reconcilerKind":"HelmChart","controller":"helmchart","name":"default-cdn","namespace":"cd","error":"failed to fetch https://contoso.azurecr.io/helm/v1/repo/_blobs/cdn-1.0.0.tgz : 500 Internal Server Error","errorVerbose":"failed to fetch https://contoso.azurecr.io/helm/v1/repo/_blobs/cdn-1.0.0.tgz : 500 Internal Server Error\nhelm.sh/helm/v3/pkg/getter.(*HTTPGetter).get\n\t/go/pkg/mod/helm.sh/helm/v3@v3.3.4/pkg/getter/httpgetter.go:73\nhelm.sh/helm/v3/pkg/getter.(*HTTPGetter).Get\n\t/go/pkg/mod/helm.sh/helm/v3@v3.3.4/pkg/getter/httpgetter.go:41\ngithub.com/fluxcd/source-controller/internal/helm.(*ChartRepository).DownloadChart\n\t/workspace/internal/helm/repository.go:175\ngithub.com/fluxcd/source-controller/controllers.(*HelmChartReconciler).reconcileFromHelmRepository\n\t/workspace/controllers/helmchart_controller.go:312\ngithub.com/fluxcd/source-controller/controllers.(*HelmChartReconciler).Reconcile\n\t/workspace/controllers/helmchart_controller.go:148\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:244\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:218\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:197\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.9/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.9/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.9/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.9/pkg/util/wait/wait.go:90\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374"}
`

I got this result when I curl the chart URL :
`curl -u xxxxx:secret -v https://contoso.azurecr.io/helm/v1/repo/_blobs/cdn-1.0.0.tgz`

```
* Server auth using Basic with user 'xxxxxxxx'
> GET /helm/v1/repo/_blobs/cdn-1.0.0.tgz HTTP/1.1
> Host: contoso.azurecr.io
> Authorization: Basic xxxxxxx==
> User-Agent: curl/7.66.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 307 Temporary Redirect
< Server: openresty
< Date: Tue, 03 Nov 2020 14:01:32 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 401
< Connection: keep-alive
< Access-Control-Expose-Headers: Docker-Content-Digest
< Access-Control-Expose-Headers: WWW-Authenticate
< Access-Control-Expose-Headers: Link
< Access-Control-Expose-Headers: X-Ms-Correlation-Request-Id
< Docker-Distribution-Api-Version: registry/2.0
< Location: https://frcmanaged82.blob.core.windows.net/99999999aaaaaaa9999999aaaaaa9999-artifact-abcdefghij//docker/registry/v2/blobs/sha256/c1/a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9/data?se=2020-11-03T14%3A18%3A18Z&sig=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX%2BXXXXXXXXXXXX%3D&sp=r&sr=b&sv=2016-05-31&regid=99999999aaaaaaa9999999aaaaaa9999
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< X-Content-Type-Options: nosniff
< X-Ms-Correlation-Request-Id: xxxxxxxxx
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< 
<a href="https://frcmanaged82.blob.core.windows.net/99999999aaaaaaa9999999aaaaaa9999-artifact-abcdefghij//docker/registry/v2/blobs/sha256/c1/a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9/data?se=2020-11-03T14%3A18%3A18Z&amp;sig=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX%2BXXXXXXXXXXXX%3D&amp;sp=r&amp;sr=b&amp;sv=2016-05-31&amp;regid=99999999aaaaaaa9999999aaaaaa9999">Temporary Redirect</a>.
```

Next if I curl the URL of the location header without passing credentials, I then download the chart.  
But if I curl the URL of the location header by passing credentials (as initial request), I got a 400 HTTP response.

**Comment by fredgate** [comment]
Corresponding issue from Flux Toolkit: https://github.com/fluxcd/source-controller/issues/193

The concerned method is: https://github.com/helm/helm/blob/master/pkg/getter/httpgetter.go#L68-L74

**Comment by mattfarina** [comment]
The HTTP response code from Azure is "500 Internal Server Error". That's a generic error that something went wrong on the server side.

When you used curl you got a "307 Temporary Redirect" along with a new location to redirect to. If Helm had gotten that it would have followed the redirect.

Without more information it will be hard to detect. Note, if this were something like an authentication issue I would have expected a different HTTP response code from Azure. 500 codes are usually internal errors to the server.

**Comment by bacongobbler** [comment]
@fredgate any update here? I concur with @mattfarina that this would appear to be an internal error coming from ACR. I'm curious if you were able to get to the bottom of this.

**Comment by fredgate** [comment]
I still have the problem. But I don't know the cause.
- i never had errors when I used Flux v1
- i regularly have errors with Flux v2

I also wrote this small program that I execute in the same pod as Fux v2 :
```
repoURL := "https://contoso.azurecr.io/helm/v1/repo"
var options []getter.Option
options = append(options, getter.WithBasicAuth("username", "password"))
options = append(options, getter.WithTimeout(60*time.Second))

c, _ := getter.NewHTTPGetter()
data, err := c.Get(repoURL+"/index.yaml", options...)
if err != nil {
	fmt.Println("Can not download index " + err.Error())
}
fmt.Printf("Index: %d Ko\n", len(data.String())/1024)

c, _ := getter.NewHTTPGetter()
data, err := c.Get(repoURL+"/_blobs/cdn-1.0.0.tgz", options...)
if err != nil {
	fmt.Println("Can not download chart " + err.Error())
}
chart, err := loader.LoadArchive(data)
if err != nil {
	fmt.Println("Can not load chart " + err.Error())
}
fmt.Println("Chart: " + chart.Name() + " " + chart.Metadata.Version)
```
I never had error even when I call this many times in a long loop (but may be that the loop demonstrates nothing more as there is a cache somewhere).

I also exposed my problem to Microsoft and they are looking on their side. I hope to have some answers.

I'll keep you informed as soon as I have a return.

**Comment by fredgate** [comment]
The error was caused by an new line character at end of the username. The secret containing the credentials was filled with values base 64 encoded with command like `echo <username> | base64` when it should have been done `echo -n <username> | base64`.
Azure Container Registry returns a 401 response if the user name is invalid, but returns a 500 response if the user name is valid with a `\n` character at end.
