### ISSUE TITLE
Feature Request: `helm lint --debug` similar to `helm template --debug`

### ISSUE THREAD

**Issue by JasonWhall** [helm/helm#8982]
Currently when using `helm lint` this will fail if for example an invalid default value is set in a template. This then prints out an error similar to below:

```
[ERROR] templates/deployment.yaml: unable to parse YAML: error converting YAML to JSON: yaml: line 37: did not find expected key
```

However to debug this issue I then need to run `helm template --debug` to print out the invalid yaml to identify this line. 

It would be useful if we could pass the `--debug` flag to `helm lint` to render the invalid yaml, similar to the template command, rather than adding additional logic to only run `helm template --debug` if linting fails.

**Comment by bacongobbler** [comment]
Updated the title to reflect the feature request.

@JasonWhall is this something you're interested in contributing?

**Comment by JasonWhall** [comment]
@bacongobbler thanks. Sure, had a stab at it! #8995 🤞
