### ISSUE TITLE
Combining variable values in default function

### ISSUE THREAD

**Issue by aleksf** [helm/helm#8983]
Output of `helm version`: 
`version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}`

Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): n/a

Is it currently possible to combine variable values with **default** function? I would like to achieve similar to below (example is set for reference and does not work)
`
vault.hashicorp.com/role: {{ .Values.vault.k8s_role | default {{ .Release.Name }}-{{ .Release.Namespace }}-{{ .Chart.Name }} | quote }}
`

Single variable works fine:
`
vault.hashicorp.com/role: {{ .Values.vault.k8s_role | default .Release.Name | quote }}
`

Is there a different way how to combine multiple variables in **default** function? I am favouring **default**  construct instead of using numerous if's

**Comment by mattfarina** [comment]
You need to combine functions to achieve this. Something like...

```
vault.hashicorp.com/role: {{ .Values.vault.k8s_role | default (printf "%s-%s-%s" .Release.Name .Release.Namespace .Chart.Name) }} | quote }}
```

`printf` is used to generate the string used as the default.

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!
