### ISSUE TITLE
Helm 3 generates incomplete index.yaml with helm repo index

### ISSUE THREAD

**Issue by groundnuty** [helm/helm#8984]
Helm 3 gives drastically different (dare I say incorrect) results when generating `index.yaml` - basically omitting most of the packages when building the index.

How to reproduce with:

```bash
echo "Cloning helm registry..."
TMP_DIR=$(mktemp -d)
echo 'git clone -b gh-pages git@github.com:onedata/charts.git "$TMP_DIR"'
git clone -b gh-pages git@github.com:onedata/charts.git "$TMP_DIR"
helm repo index .  --url https://onedata.github.io/charts/```
cd $TMP_DIR
yq '.entries[][] | select(.name=="cross-support-job-3p").version' index.yaml
```

With Helm v3.4.0 the resulting list of version has just a few entries:
```
"0.2.17"
"0.2.3"
"0.2.2"
"0.2.1"
"0.2.0"
```

The correct result with Helm v2.16.9:
```bash
"0.2.17"
"0.2.17-rc7"
"0.2.17-rc6"
"0.2.17-rc5"
"0.2.17-rc4"
"0.2.17-rc3"
"0.2.17-rc2"
"0.2.17-rc1"
"0.2.16"
"0.2.15-rc7"
"0.2.15-rc6"
"0.2.15-rc57"
"0.2.15-rc56"
"0.2.15-rc55"
"0.2.15-rc53"
"0.2.15-rc51"
"0.2.15-rc5"
"0.2.15-rc48"
"0.2.15-rc47"
"0.2.15-rc46"
"0.2.15-rc45"
"0.2.15-rc44"
"0.2.15-rc43"
"0.2.15-rc42"
"0.2.15-rc41"
"0.2.15-rc40"
"0.2.15-rc4"
"0.2.15-rc39"
"0.2.15-rc36"
"0.2.15-rc35"
"0.2.15-rc34"
"0.2.15-rc33"
"0.2.15-rc32"
"0.2.15-rc30"
"0.2.15-rc3"
"0.2.15-rc29"
"0.2.15-rc28"
"0.2.15-rc27"
"0.2.15-rc26"
"0.2.15-rc25"
"0.2.15-rc22"
"0.2.15-rc21"
"0.2.15-rc20"
"0.2.15-rc2"
"0.2.15-rc19"
"0.2.15-rc16"
"0.2.15-rc15"
"0.2.15-rc14"
"0.2.15-rc13"
"0.2.15-rc12"
"0.2.15-rc11"
"0.2.15-rc10"
"0.2.15-rc1"
"0.2.14"
"0.2.14-alpha-1"
"0.2.13"
"0.2.13-rc2"
"0.2.13-rc1"
"0.2.12"
"0.2.11"
"0.2.10"
"0.2.10-wip-4"
"0.2.10-wip-1"
"0.2.10-wip"
"0.2.9"
"0.2.8"
"0.2.7"
"0.2.6"
"0.2.5"
"0.2.4"
"0.2.3"
"0.2.2"
"0.2.1"
"0.2.0"
```

I've tried to find a flag that would compensate this behaviour but failed.

The complete diff of `index.yaml` generated with Helm3 and Helm2: https://termbin.com/dyjc

**Comment by mattfarina** [comment]
I've reproduced the bug.

**Comment by mattfarina** [comment]
I think I know what's going on here. I pulled apart the chart archive _cross-support-job-3p-0.2.17-rc7.tgz_. If you run `helm show chart cross-support-job-3p-0.2.17-rc7.tgz` with Helm v3.4.0 you get an error...

```
Error: error unpacking onedata-3p in cross-support-job-3p: error unpacking oneprovider in onedata-3p: cannot load values.yaml: error converting YAML to JSON: yaml: unknown anchor 'nfs-exports' referenced
```

When Helm looks at a directory to generate an index it loads each of the chart archives to get the metadata in the _Chart.yaml_ file. In this case it's unable to load the chart due to an issue with the _values.yaml_ file.

In the oneprovider _values.yaml_ file the anchor is on line 337 and the alias is on line 234. Per the YAML spec, the anchor needs to come before the alias. This is in section 3.2.2.2. of the spec (I had to look). So, there is a problem with this YAML file.

_Sidebar, the anchor coming prior to the alias is important for high performance readers. It will enable them to read the document as a stream rather than loading the whole document into memory._

Why does this chart work in Helm v2 but not Helm v3. This is a good question. Helm v2 and Helm v3 have different code paths to load a chart. Helm v3 parses the _values.yaml_ file as part of the process to populate internal objects. Helm v2 stored the raw bytes on an internal property but did not parse the YAML for the _values.yaml_ file.

It might be useful to have some debug output that can be opted into to display the loading error if it looks like a chart archive.

**Comment by groundnuty** [comment]
@mattfarina that is all true.
In charts, we have a complex configuration and we use yaml anchors extensively. In many cases, it's not possible to have an anchor definition prior to its usage. Helm upgraded it's yaml go parser around version `2.14.1` at that point our charts stopped working. I've been stuck with `2.14.1` ever since and recently I made an effort to find a path for our *rich in anchors* configs to work with Helm 3.

To do that I've created a workaround and in our build scripts, before executing `helm [package, lint, dep update...]` I temporarily convert a `values.yaml` file with forward anchors (using the same go yaml parser helm used to use in 2.14.1) to it's *unanchored* version. The result is a valid packaged chart.

As you pointed out, it seems that Helm 3 tries load not only `Chart.yaml` but also `values.yaml`. (I'm not sure why it should do that?) to validate the charts before it gets indexed. The result is omission of most of the charts I've created using Helm2 :-(

Anyway, I'm sure what should be fixed is `helm --debug repo index .` silently failing while returning success and giving no logs about problems you described.

Allow me to a small offtopic:
Yaml has pretty limited expressiveness when you enforce anchors as they are described in the spec it gets even worse... there was a talk about helm supporting different formats of values files (possibly via plugin?) but I guess this discussion died at some point?

**Comment by mattfarina** [comment]
@groundnuty I can respond two of the things...

> As you pointed out, it seems that Helm 3 tries to load not only Chart.yaml but also values.yaml. (I'm not sure why it should do that?) to validate the charts before it gets indexed. 

Helm has to load information from the Chart for varying tasks. In Helm v2 when the chart was loaded the raw data was stored for things like the values. When it was later needed it would be unmarshaled. In Helm v3 the loading process was changed to also unmarshal the data. This enabled the central unmarshaling for simpler logic.

When an index is created the chart needs to be read. The common loading function is used and only what's needed is pulled from the details. This is how both Helm v2 and v3 worked. v3 has just centralized some functionality.

> In many cases, it's not possible to have an anchor definition prior to its usage.

Helm uses the same parser that Kubernetes does. This allows Helm to limit the number of YAML parsers in the binary and keep in step with Kubernetes.

In this case, it's a spec issue. That's something Kubernetes and Helm do not control.

In your case, even if Helm ignored the loading errors when creating the index, the errors would later show up when someone tried to use the chart. So, problems would still happen.

I would suggest trying to follow the YAML spec. I understand the limitations. If you want, you can create a [Helm Improvement Proposal](https://github.com/helm/community/tree/master/hips) to support an alternative.

**Comment by groundnuty** [comment]
> In your case, even if Helm ignored the loading errors when creating the index, the errors would later show up when someone tried to use the chart. So, problems would still happen.

I fully agree. The situation above arose, as we are in a transition period where pipelines are using Helm 2 and I'm moving charts and repositories to Helm 3 first. We can assume it's pretty unique.

Still, It possible if would be nice to fix `helm --debug repo index .` to throw some warning/errors at atm. fails silently and the result is quite unexpected.
