### ISSUE TITLE
Helm v3.4 Error: UPGRADE FAILED: another operation (install/upgrade/rollback) is in progress

### ISSUE THREAD

**Issue by jlcrow** [helm/helm#8987]
Upgraded from Helm 3.3 to Helm 3.4, existing charts started failing the upgrade with the message:
Error: UPGRADE FAILED: another operation (install/upgrade/rollback) is in progress

At the same time a helm list -n myns the chart disappeared and didn't show up in the list at all

This is a chart that's been upgraded over 800 times successfully, only change was the helm version bump, chart failed twice in an attempt to deploy with the command:

```
helm upgrade --install --namespace myns --timeout 1800s --atomic mychart charts/app/standalone --values values-override.yaml
```

Once I rolled back to 3.3 I was able to upgrade the chart successfully.

Output of `helm version`: 

```
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"dirty", GoVersion:"go1.15.3"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.13", GitCommit:"39a145ca3413079bcb9c80846488786fed5fe1cb", GitTreeState:"clean", BuildDate:"2020-07-15T16:18:19Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.401", GitCommit:"eb94c181eea5290e9da1238db02cfef263542f5f", GitTreeState:"clean", BuildDate:"2020-09-09T00:57:35Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE

**Comment by bacongobbler** [comment]
Hi @jlcrow.

We ask to please provide a test case or some way for the maintainers to test and reproduce the error you are experiencing. This way we can better help understand the issue and determine if there's a fix we can apply to the next release.

Thanks.

**Comment by mattfarina** [comment]
@jlcrow Yikes. While I wouldn't ask you to do this in production could you do an upgrade while using the `--debug` and `-v 6` flags set. This will provide more diverse output that can help us find the problem.

**Comment by jlcrow** [comment]
> @jlcrow Yikes. While I wouldn't ask you to do this in production could you do an upgrade while using the `--debug` and `-v 6` flags set. This will provide more diverse output that can help us find the problem.

Thanks @mattfarina, I'm pushing up a branch for deployment and will test with both versions of helm to see if I can reproduce

**Comment by Skaronator** [comment]
I have the same issues. I'll try to get a debug output if possible.

I noticed this issue usually happens when you upgrade a helm chart with --wait and the upgrade clearly fails (like a crashloopbackoff or something like that) and helm is waiting until it reaches the timeout but the user does CTRL+C before reaching the timeout. After that I'll get the same error as posted above:
```
STDERR:
  Error: UPGRADE FAILED: another operation (install/upgrade/rollback) is in progress
```

I'm using helmfile, not helm directly, maybe its another problem with helmfile not sending the SIGTERM correctly.

**Comment by bacongobbler** [comment]
@Skaronator and @jlcrow can you check and see if the same symptoms and workarounds described in https://github.com/helm/helm/issues/4558 help with your cases?

**Comment by Skaronator** [comment]
Hi @bacongobbler, the described workaround did indeed works!
```
$ helm history kyc-api
REVISION	UPDATED                 	STATUS         	CHART             	APP VERSION	DESCRIPTION             
1       	Mon Nov  9 14:57:36 2020	pending-install	generic-base-0.2.1	0.1.0      	Initial install underway

$ helm rollback kyc-api 1
Rollback was a success! Happy Helming!

 $ helm history kyc-api
REVISION	UPDATED                 	STATUS         	CHART             	APP VERSION	DESCRIPTION             
1       	Mon Nov  9 14:57:36 2020	pending-install	generic-base-0.2.1	0.1.0      	Initial install underway
2       	Mon Nov  9 15:06:15 2020	deployed       	generic-base-0.2.1	0.1.0      	Rollback to 1  
```

Looking at the werf/helm PR pretty much confirms that CTRL+C breaks the helm installation on 3.4.0.

**Comment by bacongobbler** [comment]
Thanks for following up. Closing as a duplicate of #4558.

**Comment by jlcrow** [comment]
@bacongobbler I don't understand how this was determined to be the same issue?  There's no ctrl+c running in my pipeline.

**Comment by Skaronator** [comment]
I still think there is a regression in 3.4.0 since I never had this issue before.

**Comment by jlcrow** [comment]
I've tried to reproduce this in a branch of my project and have been unable to at this point.

**Comment by bacongobbler** [comment]
Okay. Have either of you been able to reproduce this issue?

I know that this particular error can occur when the previous release is in a PENDING_UPGRADE or some other transitional state - usually occurs due to a timeout or someone interrupting the upgrade midway through (hence why I linked to #4558). I have not heard of a regression in Helm 3.4.0 causing an upgrade to enter a transitional state other than through the ticket I linked earlier... Which isn't isolated to just Helm 3.4.

**Comment by jlcrow** [comment]
@bacongobbler  I haven't had luck reproducing the issue, I've just bumped to 3.4.1 and upgraded the same deployment that previously failed under 3.4.0, will just assume the issue is resolved unless I see something else.  Thanks for everything.

**Comment by jlcrow** [comment]
@bacongobbler I ran into this again this morning in one of our pipelines and did confirm that it appears to be a duplicate  of  https://github.com/helm/helm/issues/4558, it seems to be a bad timing issue where the pipeline kills the previous deployment while it's in the middle of a deploy, I'm surprised we haven't run into this before.  I confirmed the workaround was successful, I ran a rollback to the last successful deployment in the history and then followed up with the new deployment and everything is back to normal.

**Comment by bacongobbler** [comment]
thanks for the update.

**Comment by batazor** [comment]
my out:

`helm upgrade shortlink-api ops/Helm/shortlink-api  --install --wait --namespace=shortlink --set deploy.image.tag=0.7.0.16 --debug -v 6`

```
history.go:53: [debug] getting history for release shortlink-api
upgrade.go:121: [debug] preparing upgrade for shortlink-api
Error: UPGRADE FAILED: another operation (install/upgrade/rollback) is in progress
helm.go:81: [debug] another operation (install/upgrade/rollback) is in progress
helm.sh/helm/v3/pkg/action.init
        /home/circleci/helm.sh/helm/pkg/action/action.go:62
runtime.doInit
        /usr/local/go/src/runtime/proc.go:5474
runtime.doInit
        /usr/local/go/src/runtime/proc.go:5469
runtime.main
        /usr/local/go/src/runtime/proc.go:190
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1373
UPGRADE FAILED
main.newUpgradeCmd.func2
        /home/circleci/helm.sh/helm/cmd/helm/upgrade.go:156
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:80
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1373
```

`helm ls --all`

```
NAME    NAMESPACE       REVISION        UPDATED STATUS  CHART   APP VERSION
```

GitLab CI Pipeline Job https://gitlab.com/shortlink-org/shortlink/-/jobs/879030237

**Comment by jlcrow** [comment]
Run ‘helm history —all’, job is probably pending, you’ll have to rollback to last successful deployment.

**Comment by matti** [comment]
why is this issue still closed? repro: on empty cluster

```
helm upgrade --install --version=3.13.0 --create-namespace --namespace ingress-nginx-2 --set controller.kind=DaemonSet --set controller.service.type=LoadBalancer --set controller.service.loadBalancerIP=127.0.0.1 ingress-nginx-2 ingress-nginx/ingress-nginx
```

and ^C it

**Comment by kvaps** [comment]
I guess this proposal could solve this issue
https://github.com/helm/helm/issues/8040

**Comment by jorgeclaro** [comment]
I also have the same issue described on this thread with v3.4.1

`helm rollback` can be a workaround for development machines, but unacceptable on production CI/CD pipelines

The issue is not fixed yet and should be open again for further research

**Comment by matti** [comment]
"fixed" by deleting all helm secrets

**Comment by vasili439** [comment]
> "fixed" by deleting all helm secrets

you don't need to delete all helm secrets but only the last one. it sounds like a workaround but not like fix.

**Comment by Dimpison** [comment]
on v3.3.4 such case handled fine (see a picture attached). Using helm in GitLab CI and job cancelation became a problem after upgrading to 3.4.0.
v3.5.1 has the same issue too.
![image](https://user-images.githubusercontent.com/23451773/106264134-f2b60e80-622d-11eb-9cb7-a05136bccf7e.png)

**Comment by pantelis-karamolegkos** [comment]
I am having the same issue without even the chart being initially present..

```
▶ helm3 ls -A | grep -i cert
▶ helm3 upgrade cert-manager --install --set installCRDs=true --namespace extra-services --version v1.1.0 jetstack/cert-manager
Error: UPGRADE FAILED: another operation (install/upgrade/rollback) is in progress
```

`cert-manager` chart (the one I am trying to install) does not even exist on my cluster.

**Comment by pantelis-karamolegkos** [comment]
I just tried it with 

```
▶ helm3 version --short
v3.5.1+g32c2223
```

the end result is the same.

Why was this issue closed?

**Comment by bacongobbler** [comment]
The OP determined his issue was a duplicate of #4558. As #4558 describes, there are a few cases where a `helm upgrade` can enter the PENDING_UPGRADE state in the event of a timeout. A `helm rollback && helm upgrade` resolves the issue; hence why it was closed as a duplicate of #4558 (the symptoms and the workaround is identical).

If you do not believe you are experiencing the same issue as the OP, please open a new ticket.

**Comment by ahmadalli** [comment]
the problem is that `helm rollback && helm upgrade` is not a suitable solution for production deployments

**Comment by icelynjennings** [comment]
Experienced this on Helm `v3.5.2` caused by CTRL+C pressed during upgrade.
Workaround: `kubectl delete secret sh.helm.release.v1.<RELEASE_NAME>.v<LATEST_REVISION>`

**Comment by monotek** [comment]
I've seen this for helm installs too so no working history where one could rollback to.

Issue was dying k8s api so helm controller of flux2 was dying while installing the chart, what's likely has the same effect as ctrl+c.

**Comment by balibebas** [comment]
Had this issue because I tried to cancel a helm deployment from the command line. The [workaround suggested](https://github.com/helm/helm/issues/8987#issuecomment-724036145) by @Skaronator using a `rollback` got me past the error. Helm `history` looks like this now:

```
35              Thu Mar 18 10:09:15 2021        superseded      wordpress-0.1.6 5.4.2           Upgrade complete 
36              Thu Mar 18 10:32:16 2021        superseded      wordpress-0.1.6 5.4.2           Rollback to 34   
37              Thu Mar 18 10:42:48 2021        pending-upgrade wordpress-0.1.6 5.4.2           Preparing upgrade
38              Thu Mar 18 10:48:11 2021        superseded      wordpress-0.1.6 5.4.2           Rollback to 36   
39              Thu Mar 18 10:49:02 2021        deployed        wordpress-0.1.6 5.4.2           Upgrade complete 
```

**Comment by Cretezy** [comment]
One additional thing, ideally in our CD, with the `--wait` option, we'd like to wait until the current ongoing rollout to be finished.

Use case is:
- User pushes commit A
- CD starts
- User pushes commit B
- CD starts
- A starts Helm upgrade
- B starts Helm upgrade shortly after

Expected:
- B waits for A to be done, then runs

Current:
- B fails it's upgrade since A is still upgrading

**Comment by fgheysels** [comment]
We experience the same issue.
We have a pipeline which installs services on kubernetes cluster that is running on a vessel.   The connection to the vessel is not always optimal, so it might happen that the deploy fails due to a timeout / network problem.  When this happens, we've also encountered situations where a next run of the pipeline fails because helm reports `UPGRADE FAILED: another operation (install/upgrade/rollback) is in progress`.    

(We also specify the --wait flag in the helm upgrade command)

**Comment by AlexZhenWang** [comment]
same issue here. so why is this issue closed?

**Comment by AdiGhidel** [comment]
same issue, go-library

**Comment by sachet-synapsefi** [comment]
based on the above statements - we changed the version to `v3.3.4` and it worked out just fine.
we got the version using the following
```
curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
chmod 700 get_helm.sh
./get_helm.sh --version v3.3.4
```

**Comment by LuckySB** [comment]
this is simple problem with lock.

helm process change status to `pending-update` and SHOULD update timestamp of status every N seconds.
if this helm process failed, next `helm upgrade -i` found stale lock status and grub it.

easy work

**Comment by bacongobbler** [comment]
If you know how to fix it, we’d welcome a pull request. There’s instructions in the documentation for getting started.

**Comment by ahmadalli** [comment]
> If it were that easy it would’ve been fixed by now.
> 
> But by all means, if you know how to fix it, we’d welcome a pull request. There’s instructions in the documentation for getting started.

I wonder what happened from v3.3 to v3.4 that caused this issue

**Comment by bacongobbler** [comment]
I haven't seen anyone in the thread determine potential regressions in Helm 3.3 that would cause this issue. See my earlier comment: https://github.com/helm/helm/issues/8987#issuecomment-726337763

> I know that this particular error can occur when the previous release is in a PENDING_UPGRADE or some other transitional state - usually occurs due to a timeout or someone interrupting the upgrade midway through (hence why I linked to #4558). I have not heard of a regression in Helm 3.4.0 causing an upgrade to enter a transitional state other than through the ticket I linked earlier... Which isn't isolated to just Helm 3.4.

If you can determine the cause, we'd welcome a fix.

**Comment by VengefulAncient** [comment]
Curiously, the way we currently fix it in our cluster is by running the same upgrade command with Helm v3.2.1 (the Helm plugin for our CI uses `3.6.2`, previous `3.2.4` which had no such issues). Not only it goes through just fine, but after that it works again with the current version.

**Comment by MaxWinterstein** [comment]
`v3.6.3` brought me here, same behavior.

**Comment by okunc** [comment]
same on `v3.5.4`, fixed by
```
kubectl delete secret sh.helm.release.v1.asdf.v1 -n asdf
```

**Comment by igorbrigadir** [comment]
> same on `v3.5.4`, fixed by
> 
> ```
> kubectl delete secret sh.helm.release.v1.asdf.v1 -n asdf
> ```

Thank you, deleting the last secret in the list fixed it in my case too. I'm also on helm `v3.5.4`. Also using fluxcd helm-controller - and to bring it back completely, after deleting that secret i also had to run:

```
flux resume helmrelease asdf -n asdf
```

And now all the failed / stuck releases are working again!

**Comment by hellojack123** [comment]
helm history -n <ns> xxx
helm rollback -n <ns>   xxx  <num>

**Comment by djhaskin987** [comment]
Workaround:

1. Write the secret representing the release out to memory
```
kubectl get secret -n <whatever> sh.helm.release.v1.<name>.v<version>    -o yaml > release.yaml
```
2. Unpack the secret so you can manually edit it
```
cat release.yaml | yq .data.release | base64 -d | base64 -d | gunzip > release-contents.json
```
3. Edit the JSON document that is unpacked, changing the "description" key to "Deployed" and the "status" key to the value "deployed"
4. Repack the json document
```
cat release.json | gzip | base64 -w 0 > newreleasevalue
```
5. Edit the file `release.yaml`, changing the label `status` to `deployed` and the `data.release` key to have as its value the contents of the file `newreleasevalue` created in step 6
6. Update the secret using the file `release.yaml` which you just updated:
```
kubectl apply -n <whatever> -f release.yaml
```
7. Run `helm list` to verify that your release shows up in the list of deployed stuff
8. Now you can re-run your helm command and it won't die.

**Comment by Nolij** [comment]
> Workaround:
> 
> 1. Write the secret representing the release out to memory
> 
> ```
> kubectl get secret -n <whatever> sh.helm.release.v1.<name>.v<version>    -o yaml > release.yaml
> ```
> 
> 2. Unpack the secret so you can manually edit it
> 
> ```
> cat release.yaml | yq .data.release | base64 -d | base64 -d | gunzip > release-contents.json
> ```
> 
> 3. Edit the JSON document that is unpacked, changing the "description" key to "Deployed" and the "status" key to the value "deployed"
> 4. Repack the json document
> 
> ```
> cat release.json | gzip | base64 -w 0 > newreleasevalue
> ```
> 
> 5. Edit the file `release.yaml`, changing the label `status` to `deployed` and the `data.release` key to have as its value the contents of the file `newreleasevalue` created in step 6
> 6. Update the secret using the file `release.yaml` which you just updated:
> 
> ```
> kubectl apply -n <whatever> -f release.yaml
> ```
> 
> 7. Run `helm list` to verify that your release shows up in the list of deployed stuff
> 8. Now you can re-run your helm command and it won't die.

Getting this error when running kubectl apply after following those steps:
```
Warning: resource secrets/sh.helm.release.v1.nextcloud.v11 is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
The Secret "sh.helm.release.v1.nextcloud.v11" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

Also, the command you provided for repacking the release contents only encodes it once, I believe it should be doing that twice.

**Comment by chance2021** [comment]
> same on `v3.5.4`, fixed by
> 
> ```
> kubectl delete secret sh.helm.release.v1.asdf.v1 -n asdf
> ```

This works for me. Thanks! @[okunc](https://github.com/okunc)

**Comment by matti** [comment]
same in 3.8.1, still when killing helm install --upgrade hard enough

**Comment by matti** [comment]
delete all release versions: `kubectl delete secret --field-selector type=helm.sh/release.v1 -l owner=helm`

**Comment by azr** [comment]
Years later, a tf apply failed, but I manually changed things in k8s, because prod and we can't wait for tf, and to get the state back right:

1/

> ```
> kubectl delete secret sh.helm.release.v1.<????>.v1 -n <?????>
> ```

2/

```
tf apply
```

All went fine, because the end k8s config ended up being just the same.
Could be nice if helm had an option for this case: 'hey look it's a pending update, but the deployed stuff is exactly what it should be so I'll just replace that release'.
