### ISSUE TITLE
Multi-line values with --set

### ISSUE THREAD

**Issue by pierreyves-lebrun** [helm/helm#8988]
Output of `helm version`:
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
N/A

Given the following values.yaml:
```
redis.configmap: |
  maxmemory 1gb
  maxmemory-policy allkeys-lru
```

How can I override `maxmemory` and `maxmemory-policy` with `--set` option?

Helm documentation goes through a [few examples](https://helm.sh/docs/intro/using_helm/#customizing-the-chart-before-installing) but this case isn't mentioned.

Is the only available option to provide a value file?

**Comment by mattfarina** [comment]
In this case you can't override `maxmemory` or `maxmemory-policy` directly. `redis.configmap` has a value that's a multi-line string rather than sub-structures in YAML. You need to replace the whole value for `redis.configmap`

I don't believe it's possible to pass a multi-line string in via `--set`

**Comment by pierreyves-lebrun** [comment]
> In this case you can't override `maxmemory` or `maxmemory-policy` directly. `redis.configmap` has a value that's a multi-line string rather than sub-structures in YAML. You need to replace the whole value for `redis.configmap`
> 
> I don't believe it's possible to pass a multi-line string in via `--set`

That’s what I thought, thanks for confirming!

**Comment by abelal83** [comment]
Convert the value to base64 and then you can use --set
