### ISSUE TITLE
Feature Request: move or duplicate chart metadata to a ConfigMap

### ISSUE THREAD

**Issue by rbren** [helm/helm#8991]
I manage a couple different Helm auditing tools, including [Nova](https://github.com/FairwindsOps/nova/).

Sadly these tools need RBAC permission to access secrets, even though they're only looking for things like chart name and version. That limits adoption of tools that can audit and manage Helm charts due to (very reasonable) security concerns.

Would it be possible to start making chart metadata available in a less-sensitive way?

**Comment by bacongobbler** [comment]
Hi @rbren. Thanks for reaching out.

What kind of metadata are you looking for?

**Comment by rbren** [comment]
Thanks for the quick response! Off the top of my head:
* chart name
* app version
* chart version
* installed date
* last updated date
* number of releases

Pretty much anything you'd get from Chart.yaml or `helm ls`

As a side note, Helm doesn't seem to track the source repository within the release. That'd be very useful information - currently we just use the chart name and some other data to scan through all known repositories looking for a match.

**Comment by bacongobbler** [comment]
Most of that information can already be fetched from the chart manifest. `helm get manifest` demonstrates how one can fetch that information which is fetched from the secret metadata.

See #4256 to track the discussion surrounding source repository URLs.

**Comment by rbren** [comment]
👍 thanks for the tip.

I think my request would then be to have the Chart manifest data stored outside the secret (that shouldn't contain any sensitive info, right?), so that projects like Nova can see the installed version without needing access to secrets.

**Comment by rbren** [comment]
Would still love a solution here. I'm happy to implement if y'all think it's a reasonable request

**Comment by rbren** [comment]
@bacongobbler FWIW we'd still love to see this feature.

Currently we need to ask folks for access to _all_ secrets in _all_ namespaces just so we can tell them if their Helm charts have updates available 😬 Allowing people/tools to scan Helm chart metadata without needing to grant them access to Secrets would be a big win security-wise.
