### ISSUE TITLE
clarification about cmd/helm/require/args.go

### ISSUE THREAD

**Issue by mahmud2011** [helm/helm#8993]
As spf13/cobra already has [argument validation](https://github.com/spf13/cobra/blob/master/args.go) is it necessary to maintain a separate argument validation [here](https://github.com/helm/helm/blob/master/cmd/helm/require/args.go)?

**Comment by mattfarina** [comment]
@nodeIntegration Good question. If you look at the functionality in Helm and that in Cobra you'll see that different output is generated. For example, in Helm if someone provides arguments to a function that doesn't take args it will respond by telling you the usage of the command. Cobra does not do that. Helm is trying to provide a better user experience than the default cobra one.

Does that help?

**Comment by bacongobbler** [comment]
Did that answer your question, @mahmud2011?

**Comment by bacongobbler** [comment]
Looking at spf13/cobra#1276, I think it did. I'm going to go ahead and close this as answered. Let us know if there was some action item we need to address and we can re-open this. Thanks.
