### ISSUE TITLE
Helm Upgrade fails when changing Env Var value to valueFrom

### ISSUE THREAD

**Issue by lersouza** [helm/helm#8994]
When changing a Deployment that has an Environment Variable bound to a container as `name`/`value` key-pair to `name`/`valueFrom` construct, `helm upgrade` command fails with:

```
Error: Deployment.apps "my-deploy" is invalid: spec.template.spec.containers[0].env[2].valueFrom: Invalid value: "": may not be specified when `value` is not empty
Error: UPGRADE FAILED: Deployment.apps "my-deploy" is invalid: spec.template.spec.containers[0].env[2].valueFrom: Invalid value: "": may not be specified when `value` is not empty
```

I followed these steps:

1. Create a deployment 
2. Update the deployment manually to add and Environment var to the container using `name`/`value` key-pair
3. Change the Chart to add the same Environment var, but as `name`/`valueFrom` construct, adding a secret as well.
4. Run helm upgrade for the chart

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): Kubernet on-premise

**Comment by mattfarina** [comment]
The error you're seeing is coming back from Kubernetes when it processes the YAML. It looks like something is wrong with the generated manifest from the template in the chart.

**Comment by lersouza** [comment]
@mattfarina , I thought that at first. Then I ran in --debug mode, got the manifest and applied it successfully. I also tried to run `helm template ... | kubectl apply -f -` and I got it successfully too. It seems that helm is trying to do some sort of merge in the current state of installed chart and the chart to come.

**Comment by mattfarina** [comment]
Ah, yes. Helm uses a [3-way strategic merge patch](https://helm.sh/docs/faq/#improved-upgrade-strategy-3-way-strategic-merge-patches). This is the same functionality that [kubectl uses for patching](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch/).

The reason for this is that tools that mutate resources, like a service mesh, will have their configuration removed if you just upload a new version of the resource. So, Helm takes into account the current state that is live in the cluster.

While I have not tried this, Helm is using Kubernetes packages so this may work... there is a way [to specify the patching strategy to use](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch/#notes-on-the-strategic-merge-patch) in the resource.

**Comment by bridgetkromhout** [comment]
Hi, @lersouza - to clarify, the 3-way strategic merge patch mentioned by @mattfarina is used in Helm 3, and I see you may be using v2.14.2.

Can you let us know if you can reproduce this issue with Helm 3? We are no longer providing support for Helm 2 as of today: https://helm.sh/blog/helm-2-becomes-unsupported/

**Comment by lersouza** [comment]
Thanks @bridgetkromhout and @mattfarina . Currently, I'm not able to reproduce in Helm 3, but I'll check on that, for sure.
Anyway, thanks a lot for the clarification. In fact, the way it is implemented is safer. I'll just fix this one manually, but look for a cluster upgrade (HELM + Tiller) in order to make it more flexible.

Thanks a lot.

**Comment by cforce** [comment]
Seems to be back with helm 3.6.1
Unable to "upgrade --install" (without force) from 
```
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
```

to


```
            - name: DD_VERSION
              value: "XXXXXXXXXXXX"
```

spec.template.spec.containers[?].env[?].valueFrom: Invalid value: "": may not be specified when `value` is not empty

**Comment by david0** [comment]
I ran into the same error. I would vote for re-opening this ticket. 

Is there a way to disable the strategic merge? I really would prefer if helm always deploys what I specified, removing other changes.

**Comment by andreisaikouski** [comment]
Ran into same error. Please re-open ticket

**Comment by mgacamedica** [comment]
we are also facing this issue on v3.2.4. Please reopen this issue.

**Comment by aiuto-matematica** [comment]
I'm seeing same issue in 
version.BuildInfo{Version:"v3.8+unreleased", GitCommit:"dff9ade9d6b10ad871a5be5319d04bd436a17a44", GitTreeState:"clean", GoVersion:"go1.17.5"}

**Comment by XA21X** [comment]
Hit this while deploying Authentik using Argo CD (latest versions), when I switched to _valueFrom_ in order to load the Postgres username and password from the PostgresUser CRD (from movetokube/postgres-operator).

The workaround was to sync using replace mode.

**Comment by JoseRamonGarcia** [comment]
It happened to me. My workaround was: Move the affected env to another position in the list. After that, the helm upgrade command did not fail anymore.

**Comment by lawrence-ironclad** [comment]
> It happened to me. My workaround was: Move the affected env to another position in the list. After that, the helm upgrade command did not fail anymore.

This worked for me!!

**Comment by MarttiR** [comment]
This error can happen if you try to manually set an envvar which is automatically provided by a chart. 

Charts export envvars by using `valueFrom` to extract the appropriate value from the chart values, but the manually set envvar also adds a `value` clause under the same envvar, which leads to an invalid chart.

**Comment by delebota** [comment]
Just ran into this issue myself, the solution mentioned by @JoseRamonGarcia didn't work for me. I ended up deleting the value from my deployment and deploying that, then re-adding it and deploying again.

**Comment by therapy-lf** [comment]
Please, re-open... We faced with the same issue even using latest helm version.

**Comment by aleksey-perplexity** [comment]
I just ran into this... I can also reproduce this issue with `kube diff` alone.  I reckon this is k8s issue, not a helm issue.
