### ISSUE TITLE
helm upgrade does not pick up NEW default values if --reuse-values is set

### ISSUE THREAD

**Issue by vladimirtiukhtin** [helm/helm#9000]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-eks-aae39f", GitCommit:"aae39f4697508697bf16c0de4a5687d464f4da81", GitTreeState:"clean", BuildDate:"2019-12-23T08:19:12Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS EKS

Steps to reproduce:
- install a chart
- add new resource to the chart and corresponding default values
- upgrade the chart adding --reuse-values=true

**Comment by mattfarina** [comment]
This is working as expected. The docs on the flag read:

```
when upgrading, reuse the last release's values and merge in any overrides from the command line via --set and -f. If '--reset-values' is specified, this is ignored
```

This flag causes Helm to not pull in the `values.yaml` file but instead use the values from the previously installed release.

**Comment by vladimirtiukhtin** [comment]
Thanks for the prompt response @mattfarina. I understand this, it is just don't feel right as it causes issues during upgrade. Why not simply put values.yaml at the very left of values precedence and then merge/override using other sources?

**Comment by jglick** [comment]
Duplicate of #3957?

**Comment by Envek** [comment]
While `--reuse-values` is working as documented, it is behavior has no sense for application chart developers and completely misunderstood by Helm users. So it is a frequent reason for errors during chart updates as was multiple times noted in multiple issues like https://github.com/helm/helm/issues/3957#issuecomment-630285060 or https://github.com/helm/helm/issues/8085#issue-614852176

Unfortunately, the only non nonsense way to upgrade chart is two step `helm get values > file` and `helm upgrade -f file` workflow.

**Comment by Envek** [comment]
Oh no, it is not stale, it is still a pain.

**Comment by vladimirtiukhtin** [comment]
I had to switched to terraform as this is not getting addressed along with other issues

**Comment by bacongobbler** [comment]
Hi @vladimirtiukhtin, sorry to hear that your issue wasn't addressed. Generally speaking Helm is a community project. If you'd like to see something fixed, we have a [Developer Guide](https://helm.sh/docs/community/developers/) to help you get started.

As @mattfarina mentioned earlier though, this feature was intentionally designed in this manner as stated in its doc string. So we will not be addressing this issue with this feature flag specifically.

If you'd like to propose an alternative, I would suggest following the CONTRIBUTING guide on [proposing an idea](https://github.com/helm/helm/blob/main/CONTRIBUTING.md#proposing-an-idea). See also #8085 - others are trying to come up with alternative solutions as well, so it would be good to collaborate together on a solution.

**Comment by bacongobbler** [comment]
In the meantime, I'm going to close this as a duplicate feature request of both #8085 and #3957. As other members have pointed out, this discussion is already being tracked in other issues. Please contribute to the discussion there. Thanks.
