### ISSUE TITLE
proposal: pkg/repo: support remove chart entry from repo cache 

### ISSUE THREAD

**Issue by scbizu** [helm/helm#9001]
I read the most code of the pkg/repo ,  and can not find any mechanism to delete the chart entry from the local cache file (AKA helmpath.RepositoryCache/repo-index.yaml) , but this method is really the indeed one for only deleting the specific chart which is already deleted from remote chart repo rather than removing the whole repo by `helm repo remove`(`f.Remove(repo)`).

## Use Case

Mainly for API users , I do not find the apposite point to integrate with the helm cmd . With this API implemented , we now can **also delete the local chart cache** after we delete the chart from the remote chartmuseum , and ensure our local cache is always up-to-date.

Maybe I can provide the PR if you guys approve this new method .

**Comment by mattfarina** [comment]
If you run `helm repo update` it will update the cache and you should see the chart is removed if it is no longer available in the repo.

**Comment by scbizu** [comment]
I know it , but it rebuild the whole cache file rather than just delete the desired entry .

And our project directly use the helm lib instead of the helm cmd , but  pkg/repo do not provide a way to do so XD

**Comment by jdolitsky** [comment]
related to https://github.com/helm/chartmuseum/issues/316
