### ISSUE TITLE
Forbidden issue with helm chart having nslookup

### ISSUE THREAD

**Issue by Anil-YadavK8s** [helm/helm#9002]
Error when deploying helm chart : 

user@myserv:~ helm3 install chart-preinstall /tmp/dss-chart-install-roles-0.1.0.tgz --namespace=test-system
Error: template: dss-chart-install-roles/templates/install-secrets.yaml:1:12: executing "dss-chart-install-roles/templates/install-secrets.yaml" at <lookup "v1" "Secret" "{{ .Release.Namespace }}" "data-distributed-coordinator-creds">: error calling lookup: secrets "data-distributed-coordinator-creds" is forbidden: User "test-user" cannot get resource "secrets" in API group "" in the namespace "{{ .Release.Namespace }}"

test user has admin right in the namespace: test-system.

user@myserv:~ kubectl --kubeconfig=test-user-k8s-config auth can-i get secret
yes
user@myserv:~kubectl --kubeconfig=test-user-k8s-config auth can-i list  secret
yes

Output of `helm version`: helm3 version
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"}

Output of `kubectl version`: kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-16T17:51:57Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  Vmware

**Comment by mattfarina** [comment]
This looks like an issues with RBAC permissions. Can the user `test-user` get `secrets` in the namespace `test-system`? That specific namespace.

In the `helm` command you did not pass in a `--kubeconfig` but in the `kubectl` example you did. Are they using the same configuration? You can pass a `--kubeconfig` to `helm`. Does that change anything?

**Comment by Anil-YadavK8s** [comment]
@mattfarina  Yes it do.

user@myserv:~> kubectl auth can-i get secrets -n=test-system --as test-user
yes

user@myserv:~> helm3 install chart-preinstall /tmp/dss-chart-install-roles-0.1.0.tgz --namespace=test-system --kubeconfig=test-user-k8s-config
Error: template: dss-chart-install-roles/templates/install-secrets.yaml:1:12: executing "dss-chart-install-roles/templates/install-secrets.yaml" at <lookup "v1" "Secret" "{{ .Release.Namespace }}" "data-distributed-coordinator-creds">: error calling lookup: secrets "data-distributed-coordinator-creds" is forbidden: User "test-user" cannot get resource "secrets" in API group "" in the namespace "{{ .Release.Namespace }}"

**Comment by mattfarina** [comment]
Can you run the Helm command again with `--debug -v 9` added to it. This will tell both Helm and the underlying Kubernetes libraries to share more debugging information.

Helm uses Kubernetes packages to communicate with Kubernetes.

**Comment by Anil-YadavK8s** [comment]
Not much info...

user@myserv:~> helm3 install /tmp/dss-chart-install-roles-0.1.0.tgz --namespace=test-system --kubeconfig=test-user-k8s-config --debug -v 9
install.go:172: [debug] Original chart version: ""
install.go:189: [debug] CHART PATH: /tmp/dss-chart-install-roles-0.1.0.tgz

Error: template: dss-chart-install-roles-0.1.0.tgz/templates/install-secrets.yaml:1:12: executing "dss-chart-install-roles-0.1.0.tgz/templates/install-secrets.yaml" at <lookup "v1" "Secret" "{{ .Release.Namespace }}" "data-distributed-coordinator-creds">: error calling lookup: secrets "data-distributed-coordinator-creds" is forbidden: User "test-user" cannot get resource "secrets" in API group "" in the namespace "{{ .Release.Namespace }}"
helm.go:81: [debug] template: dss-chart-install-roles/templates/install-secrets.yaml:1:12: executing "dss-chart-install-roles/templates/install-secrets.yaml" at <lookup "v1" "Secret" "{{ .Release.Namespace }}" "data-distributed-coordinator-creds">: error calling lookup: secrets "data-distributed-coordinator-creds" is forbidden: User "test-user" cannot get resource "secrets" in API group "" in the namespace "{{ .Release.Namespace }}"

**Comment by Anil-YadavK8s** [comment]
There was an issue with helm template lookup.
