### ISSUE TITLE
Is there any way to use helm chart with --image flag ?

### ISSUE THREAD

**Issue by rjshrjndrn** [helm/helm#9008]
Is there any way to do `helm create myapp --image myapp:latest --type statefulset` ?
This will be super helpful for somuch of boilerplating ...

**Comment by mattfarina** [comment]
That's a good question. The answer is no, Helm does not currently have that feature.

This is not an easy feature to create. For example, a StatefulSet can be setup many ways. How should this one be setup? Does it need a service, too?

Helm has the concept of starter packs. Where a starter can be used for different things. Not just types but different variations. Starters can be created by anyone and shared.

**Comment by rjshrjndrn** [comment]
> This is not an easy feature to create. For example, a StatefulSet can be setup many ways. How should this one be setup? Does it need a service, too?

Why can't we have one openionated way? it's better to have a starting point, and let the user customize. It'll be super helpful to atleast have some basic boiler plate flags like 
```
--image
--port
```

> Helm has the concept of starter packs. Where a starter can be used for different things. Not just types but different variations. Starters can be created by anyone and shared.

Didn't know such a thing existed. Thanks for pointing that out.

**Comment by bacongobbler** [comment]
This is covered through starter charts. We do not plan on implementing this or accept PRs that introduce this functionality as it’s covered via other means.
