### ISSUE TITLE
Unable to install helm - Azure 

### ISSUE THREAD

**Issue by psakamoori** [helm/helm#9010]
Output of `helm version`:
$ helm version
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"}

Output of `kubectl version`:
$sudo kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Trying to connect kubernetes cluster to Azure-Arc

LOGS:

$sudo az connectedk8s connect --name 'MyK8SCluster' --resource-group 'MyArc-k8s-Clusters' --location 'eastus'
Command group 'connectedk8s' is in preview. It may be changed/removed in a future release.
Ensure that you have the latest helm version installed before proceeding.
This operation might take a while...

Please check if the azure-arc namespace was deployed and run 'kubectl get pods -n azure-arc' to check if all the pods are in running state. A possible cause for pods stuck in pending state could be insufficient resources on the kubernetes cluster to onboard to arc.
_**_Unable to install helm release: W1110 10:30:02.197250   21584 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition_**_

Azure part maybe irrelevant as issue is seen on Edge device (on k8s custer master node)

**Comment by bacongobbler** [comment]
The error suggests that the chart you are attempting to install a chart that utilizes a deprecated API. However, Helm only reports it as a warning message. It is not treated as an error condition.

Based on the error message it would seem that this is caused by the CI pipeline you are utilizing to install the Helm chart. We've had issues in the past where Azure Pipelines would fail if helm reported any warning messages (see https://github.com/microsoft/azure-pipelines-tasks/issues/13594).

Can you please check with the azure Arc team and see if this is a result of an issue on their end?

**Comment by psakamoori** [comment]
Thanks @bacongobbler  for quick reply.
Yes - here is the azure-arc issue tracker [https://github.com/microsoft/azure_arc/issues/152](url)

But not update since few days on that..

QQ: Does this " apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition" Error indicates that Azure-arc pipeline trying to use v1beta1 CustomResoruceDefinition unsupproted version to install helm? and hence the reason for error?  If so, how I can make the pipeline to use V1 CRD instead of v1beta1.. Sorry, I am beginner in kubernetes--tried to set APIVersion to V1 - But, not sure how to set that...

**Comment by bacongobbler** [comment]
I cannot tell nor know how one would go about fixing that. Sorry.
