### ISSUE TITLE
helm template errors suppressed with --debug

### ISSUE THREAD

**Issue by tobiash** [helm/helm#9012]
I have an issue with `helm template` not returning an exit code 1 for a chart with render errors as soon as I add `--debug` to capture the YAML output. I believe https://github.com/helm/helm/blob/44212f83dc9c893d962fe48648320e7b7b66950c/cmd/helm/template.go#L94 is probablye the reason for that, as it reassigns the `err` value that is returned all the way down at the end of the function.
Replacing `=` with `:=` might suffice to fix this, but I guess would make more sense to refactor this code to prevent such bugs in the future.

Output of `helm version`:
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"dirty", GoVersion:"go1.15"}

**Comment by wawa0210** [comment]
Can you use the latest helm test? I use the helm template command to test an error chart, and the error code returns 1. as expected

```
➜  failchart helm template .
Error: template: failchart/templates/deployment.yaml:4:20: executing "failchart/templates/deployment.yaml" at <{{template "fullname111" .}}>: template "fullname111" not defined

Use --debug flag to render out invalid YAML
➜  failchart echo $?
1
➜  failchart
```
