### ISSUE TITLE
Issue upgrading tomcat 0.3.0 to 0.4.x

### ISSUE THREAD

**Issue by hickeyma** [helm/helm#9014]
On Kubernetes 1.15, when installing  `stable/tomcat` version (v0.3.0) it deploys as expected with one pod. However, when upgrading to `stable/tomcat` version (v0.4.1) an additional pod is deployed which remains in a `pending` state.

The `Deployment` template for v0.3.0:

```yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "tomcat.fullname" . }}
  labels:
    app: {{ template "tomcat.name" . }}
[...]
```

and `Deployment` template for v0.4.1:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "tomcat.fullname" . }}
  labels:
    app: {{ template "tomcat.name" . }}
```

have different `APIVersion`. Kuberentes 1.15 should be able to handle both the deprecated `apps/v1beta2` and supported `apps/v1` APIs as the deprecated API are not removed in this k8s version.

It can be reproduced as follows:

```console

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"clean", BuildDate:"2020-09-14T08:06:34Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}

$ helm3 install tomcat stable/tomcat --version 0.3.0
NAME: tomcat
LAST DEPLOYED: Fri Oct  9 13:53:30 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
1. Get the application URL by running these commands:
     NOTE: It may take a few minutes for the LoadBalancer IP to be available.
           You can watch the status of by running 'kubectl get svc -w tomcat'
  export SERVICE_IP=$(kubectl get svc --namespace default tomcat -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
  echo http://$SERVICE_IP:

$ kubectl get pods
NAME                      READY   STATUS    RESTARTS   AGE
tomcat-7dcf5886c9-mntpr   1/1     Running   0          100s

$ helm3 upgrade tomcat stable/tomcat --version 0.4.1
Release "tomcat" has been upgraded. Happy Helming!
NAME: tomcat
LAST DEPLOYED: Fri Oct  9 13:55:33 2020
NAMESPACE: default
STATUS: deployed
REVISION: 2
TEST SUITE: None
NOTES:
1. Get the application URL by running these commands:
     NOTE: It may take a few minutes for the LoadBalancer IP to be available.
           You can watch the status of by running 'kubectl get svc -w tomcat'
  export SERVICE_IP=$(kubectl get svc --namespace default tomcat -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
  echo http://$SERVICE_IP:

$ kubectl get pods
NAME                      READY   STATUS    RESTARTS   AGE
tomcat-569ff5bf4d-9hgdm   0/1     Pending   0          7s
tomcat-7dcf5886c9-mntpr   1/1     Running   0          2m10s

$ kubectl get deployments --all-namespaces
NAMESPACE            NAME                     READY   UP-TO-DATE   AVAILABLE   AGE
default              tomcat                   1/1     1            1           13m
kube-system          coredns                  2/2     2            2           15d
kube-system          tiller-deploy            1/1     1            1           15d
local-path-storage   local-path-provisioner   1/1     1            1           15d
```

A few things that stabd out are:

- It didn't replace the previous deployment/pod. I would have expected Kubernetes to handle this on the fly.
- The new pod is in a `pending` state and remains in that state
- The deployment is `APIVersion` `extensions/v1beta1` (which is neither `APIVersion` specified in the templates) as follows:

```console
$ kubectl get deployment tomcat -o yaml | more
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    meta.helm.sh/release-name: tomcat
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2020-10-09T13:53:31Z"
[..]
```

If I clean the previous deployment, install fresh with version `0.4.0` and then do an upgrade, it works as expected:

```console
$ helm3 upgrade tomcat stable/tomcat --version 0.4.1
Release "tomcat" has been upgraded. Happy Helming!
NAME: tomcat
LAST DEPLOYED: Fri Oct  9 18:03:09 2020
NAMESPACE: default
STATUS: deployed
REVISION: 2
TEST SUITE: None
NOTES:
1. Get the application URL by running these commands:
     NOTE: It may take a few minutes for the LoadBalancer IP to be available.
           You can watch the status of by running 'kubectl get svc -w tomcat'
  export SERVICE_IP=$(kubectl get svc --namespace default tomcat -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
  echo http://$SERVICE_IP:

$ kubectl get pods
NAME                      READY   STATUS    RESTARTS   AGE
tomcat-569ff5bf4d-qb6rr   1/1     Running   0          3h12m
``` 

I tried reproducing this installing a scaffold chart with `apps/v1beta2` API and then upgrading using `apps/v1` API. It worked as expected however

This issue was discovered in https://github.com/helm/helm-2to3/issues/162.

Output of `helm version`:
version.BuildInfo{Version:"v3.4+unreleased", GitCommit:"b5c74cafc24cd2036f95422f2db66fe16642dc73", GitTreeState:"clean", GoVersion:"go1.14.4"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"clean", BuildDate:"2020-09-14T08:06:34Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Kind

**Comment by hickeyma** [comment]
@Nuru Are you able to reproduce this issue with other charts in addition to `stable/tomcat`?

**Comment by joejulian** [comment]
We encountered about half a dozen charts that did this. We worked around it by marking them as needing to be deleted and reinstalled instead of being converted. After Kubecon I'll see if I can find another repro.

**Comment by hickeyma** [comment]
I tried reproducing this installing a scaffold chart with apps/v1beta2 API and then upgrading using apps/v1 API. It worked as expected however.

I am going to try and get hold of 1.15 cluster which I can upgrade easily to do some investigations. I am trying to make sure that the issue is avoided by updating the APIs in place using [mapkubeapis plugin](https://github.com/hickeyma/helm-mapkubeapis), then upgrading the cluster to version where APIs are removed and then upgrading with the latest chart version. I am fairly sure it is because Kubernetes during the cluster upgrade will upgrade all existing APIs the latest supported API.

**Comment by mattfarina** [comment]
The first thing to note is that the change from `apps/v1beta2` to `extensions/v1beta1` is something Kubernetes does not Helm. If you use `helm template` to generate the manifests (with `apps/v1beta2`) and then use `kubectl` to put them into Kubernetes you'll see the exact same change.

There is an [issue with a comment that explains the deletion process](https://github.com/kubernetes/kubernetes/issues/83672#issuecomment-543482873) well when someone filed a similar bug over there. [Helm explicitly sets a background deletion to happen](https://github.com/helm/helm/blob/d675b9c810e7fb4f198486d8dd082dcf35cb118d/pkg/kube/client.go#L371-L376). There is [a page in the k8s docs on garbage collection](https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/).

If you are looking for Kubernetes 1.15 you can use Minikube. Running `minikube start --kubernetes-version v1.15.12` will give you the last patch version of 1.15.

**Comment by hickeyma** [comment]
> If you are looking for Kubernetes 1.15 you can use Minikube. Running minikube start --kubernetes-version v1.15.12 will give you the last patch version of 1.15.

Yes you can use Kind as well. Do you know how to upgrade to k8s 1.16?

**Comment by hickeyma** [comment]
> The first thing to note is that the change from apps/v1beta2 to extensions/v1beta1 is something Kubernetes does not Helm. If you use helm template to generate the manifests (with apps/v1beta2) and then use kubectl to put them into Kubernetes you'll see the exact same change.

Sure Matt. I am raising this so we can highlight the issue nd see if we can find a way around it.

> There is an issue with a comment that explains the deletion process well when someone filed a similar bug over there. Helm explicitly sets a background deletion to happen. There is a page in the k8s docs on garbage collection.

This is interesting, thanks.

**Comment by mattfarina** [comment]
tomcat is an interesting example. The reason the new pod does not start is `0/1 nodes are available: 1 node(s) didn't have free ports for the requested pod ports.`. It has to do with the chart and what it's trying to do. Not something with Helm.

The thing to focus on is why the resource isn't being deleted. In this case it's the replicaset managed by the deployment and its pod children. When `helm delete` is run the replicaset and pod are deleted.

**Comment by hickeyma** [comment]
> tomcat is an interesting example. The reason the new pod does not start is 0/1 nodes are available: 1 node(s) didn't have free ports for the requested pod ports.. It has to do with the chart and what it's trying to do. Not something with Helm.

That would make sense as when you install a second release of tomcat, its pods never gets started.

**Comment by hickeyma** [comment]
@joejulian Has mentioned about 1/2 dozen other charts with a similar issue in https://github.com/helm/helm/issues/9014#issuecomment-726138977. It will be good to get an idea what they charts are, so we can take a look at them.

**Comment by mattfarina** [comment]
@hickeyma if you use minikube to start with 1.15, then stop it, then start it with 1.16 (e.g., `minikube start --kubernetes-version v1.16.15`) then it will upgrade it. The same resource will be running.

**Comment by hickeyma** [comment]
Great, thanks @mattfarina. Using kind and haven't touched minikube in a long time.

**Comment by mattfarina** [comment]
OK, I did some work to figure the things out. This is an issue with k8s.

Here's how you can reproduce this.

1. Start with Kubernetes 1.15 (you can use the command with minikube I shared earlier).
2. Get the tomcat chart at 0.3 and 0.4 in two directories (i.e. tomcat-3 and tomcat-4).
3. Use helm to generate template (i.e. `helm template tc tomcat-3 > tc.yaml` and `helm template tc tomcat-4 > tc2.yaml`)
4. Use kubectl to apply these. (i.e. `kubectl apply -f tc.yaml`, then wait for pods to come up, then `kubectl apply -f tc2.yaml`)

You'll see the same problem as Helm.

The reason is that the resource isn't being delete but rather updated to a new api version. The controller doesn't appear to be handling this properly. A second replicaset is created and pods created for it.

This isn't a helm bug because I can reproduce with kubectl under the same circumstances.

**Comment by Nuru** [comment]
> OK, I did some work to figure the things out. This is an issue with k8s.
> ...
> This isn't a helm bug because I can reproduce with kubectl under the same circumstances.

@mattfarina Did you use `kubectl 1.16.15` ? You have to [match `kubectl` to the version of Kubernetes you are using](https://kubernetes.io/docs/setup/release/version-skew-policy/#kubectl). I think @hickeyma has this particular issue because of `kubectl` 1.18 being used on a 1.15 cluster. 

In any case, this is a separate issue from https://github.com/helm/helm-2to3/issues/162 in that the `helm-2to3` conversion issue is about `helm` v3 refusing to delete the resources created by `helm` v2 and scheduled to be deleted by the new release of the chart.

**Comment by hickeyma** [comment]
I installed tomcat (v0.3.0) with Helm 2 on Kubernetes 1.15.12 as follows:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"clean", BuildDate:"2020-05-06T05:09:48Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}

$ helm2 install --name tomcat stable/tomcat --version 0.3.0
NAME:   tomcat
LAST DEPLOYED: Thu Nov 12 21:46:59 2020
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/Pod(related)
NAME                     READY  STATUS    RESTARTS  AGE
tomcat-7dcf5886c9-bnc7j  0/1    Init:0/1  0         1s

==> v1/Service
NAME    TYPE          CLUSTER-IP      EXTERNAL-IP  PORT(S)       AGE
tomcat  LoadBalancer  10.100.120.190  <pending>    80:30792/TCP  0s

==> v1beta2/Deployment
NAME    READY  UP-TO-DATE  AVAILABLE  AGE
tomcat  0/1    1           0          0s


NOTES:
1. Get the application URL by running these commands:
     NOTE: It may take a few minutes for the LoadBalancer IP to be available.
           You can watch the status of by running 'kubectl get svc -w tomcat'
  export SERVICE_IP=$(kubectl get svc --namespace default tomcat -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
  echo http://$SERVICE_IP:

$ helm2 ls
NAME  	REVISION	UPDATED                 	STATUS  	CHART       	APP VERSION	NAMESPACE
tomcat	1       	Thu Nov 12 21:46:59 2020	DEPLOYED	tomcat-0.3.0	7.0        	default  

$ kubectl get pods -n default
NAME                      READY   STATUS            RESTARTS   AGE
tomcat-7dcf5886c9-bnc7j   1/1     Running   0          2m11s

$ kubectl get replicaset -n default
NAME                DESIRED   CURRENT   READY   AGE
tomcat-7dcf5886c9   1         1         1       2m56s
```

I then updated the `tomcat` release to the supported APIs (this does not change the Kubernetes resource in the cluster, only the release metadata)  before upgrading to Kubernetes 1.16 as follows:

```console
$ helm2 mapkubeapis tomcat --v2
2020/11/12 21:53:44 Release 'tomcat' will be checked for deprecated or removed Kubernetes APIs and will be updated if necessary to supported API versions.
2020/11/12 21:53:44 Get release 'tomcat' latest version.
2020/11/12 21:53:44 Check release 'tomcat' for deprecated or removed APIs...
2020/11/12 21:53:44 Found deprecated or removed Kubernetes API:
"apiVersion: apps/v1beta2
kind: Deployment"
Supported API equivalent:
"apiVersion: apps/v1
kind: Deployment"
2020/11/12 21:53:44 Finished checking release 'tomcat' for deprecated or removed APIs.
2020/11/12 21:53:44 Deprecated or removed APIs exist, updating release: tomcat.
2020/11/12 21:53:44 Set status of release version 'tomcat.v1' to 'superseded'.
2020/11/12 21:53:44 Release version 'tomcat.v1' updated successfully.
2020/11/12 21:53:44 Add release version 'tomcat.v2' with updated supported APIs.
2020/11/12 21:53:44 Release version 'tomcat.v2' added successfully.
2020/11/12 21:53:44 Release 'tomcat' with deprecated or removed APIs updated successfully to new version.
2020/11/12 21:53:44 Map of release 'tomcat' deprecated or removed APIs to supported versions, completed successfully.
```

I then upgraded the cluster to Kubernetes 1.16 and you can see that Kubernetes on the upgrade started pod with latest supported API `apps/v1` as API `apps/v1beta2` is no longer supported on Kubernetes 1.16:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.15", GitCommit:"2adc8d7091e89b6e3ca8d048140618ec89b39369", GitTreeState:"clean", BuildDate:"2020-09-02T11:31:21Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

$ helm2 ls
NAME  	REVISION	UPDATED                 	STATUS  	CHART       	APP VERSION	NAMESPACE
tomcat	2       	Thu Nov 12 21:53:44 2020	DEPLOYED	tomcat-0.3.0	7.0        	default  

$ kubectl get pods -n default
NAME                      READY   STATUS    RESTARTS   AGE
tomcat-7dcf5886c9-bnc7j   1/1     Running   1          16m

$ kubectl get replicaset -n default
NAME                DESIRED   CURRENT   READY   AGE
tomcat-7dcf5886c9   1         1         1       16m

$ kubectl get deployment tomcat -o yaml
apiVersion: apps/v1
kind: Deployment
metadata:
[...]
```

I then converted Helm 2 `tomcat` release to Helm 3:

```console
$ helm3 2to3 convert tomcat
2020/11/12 22:13:33 Release "tomcat" will be converted from Helm v2 to Helm v3.
2020/11/12 22:13:33 [Helm 3] Release "tomcat" will be created.
2020/11/12 22:13:33 [Helm 3] ReleaseVersion "tomcat.v1" will be created.
2020/11/12 22:13:33 [Helm 3] ReleaseVersion "tomcat.v1" created.
2020/11/12 22:13:33 [Helm 3] ReleaseVersion "tomcat.v2" will be created.
2020/11/12 22:13:33 [Helm 3] ReleaseVersion "tomcat.v2" created.
2020/11/12 22:13:33 [Helm 3] Release "tomcat" created.
2020/11/12 22:13:33 Release "tomcat" was converted successfully from Helm v2 to Helm v3.
2020/11/12 22:13:33 Note: The v2 release information still remains and should be removed to avoid conflicts with the migrated v3 release.
2020/11/12 22:13:33 v2 release information should only be removed using `helm 2to3` cleanup and when all releases have been migrated over.

$ helm3 ls --all-namespaces
NAME  	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART       	APP VERSION
tomcat	default  	2       	2020-11-12 21:53:44.589998739 +0000 UTC	deployed	tomcat-0.3.0	7.0        
```

I then upgrade the newly converted release to `tomcat` version 0.4.1 and it upgraded without error:

```console
$ helm3 upgrade tomcat stable/tomcat --version 0.4.1
Release "tomcat" has been upgraded. Happy Helming!
NAME: tomcat
LAST DEPLOYED: Thu Nov 12 22:14:16 2020
NAMESPACE: default
STATUS: deployed
REVISION: 3
TEST SUITE: None
NOTES:
1. Get the application URL by running these commands:
     NOTE: It may take a few minutes for the LoadBalancer IP to be available.
           You can watch the status of by running 'kubectl get svc -w tomcat'
  export SERVICE_IP=$(kubectl get svc --namespace default tomcat -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
  echo http://$SERVICE_IP:
```

However upon inspection, there is still an issue in the cluster where after upgrade a new pod is trying to be deployed.:

```console
$ helm3 ls --all-namespaces
NAME  	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART       	APP VERSION
tomcat	default  	3       	2020-11-12 22:14:16.866102518 +0000 UTC	deployed	tomcat-0.4.1	7.0        

$ kubectl get pods -n default
NAME                      READY   STATUS    RESTARTS   AGE
tomcat-6ff7cb7674-88svr   0/1     Pending   0          45s
tomcat-7dcf5886c9-bnc7j   1/1     Running   1          28m

$ kubectl get replicaset -n default
NAME                DESIRED   CURRENT   READY   AGE
tomcat-6ff7cb7674   1         1         0       52s
tomcat-7dcf5886c9   1         1         1       28m
```

**Comment by hickeyma** [comment]
> has this particular issue because of kubectl 1.18 being used on a 1.15 cluster.

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"clean", BuildDate:"2020-05-06T05:09:48Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

One is the `kubectl` version which is `1.18.5`, the other is the cluster/server version which is `1.15.12`.  I need to test with 1.15 as this is the last Kubernetes version which supports the old deprecated deployment APIs like `apps/v1beta2`. 
You are correct in saying that you should keep your client version in line with your backend/cluster. That is when you are running `kubectl` commands. In this case, we are looking at Helm mostly and it talks directly to the Kubernetes API server in the cluster.

**Comment by hickeyma** [comment]
Tested on Kubernetes 1.16 installing `tomcat` version 0.4.0 and then upgrading to version 0.4.1 using Helm. The 2nd `pending` pods is happening in this upgrade as well. This seems to point to some issue with the `tomcat` chart and how Kubernetes is handing the upgrade/patch request. This is a straight test which does NOT involve deprecated APIs or Helm 2to3 conversion. Test output:

```console
$ helm3 install tomcat-inst1 stable/tomcat --version 0.4.0
NAME: tomcat-inst1
LAST DEPLOYED: Fri Nov 13 11:24:35 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
[...]

$ kubectl get deployment tomcat-inst1 -o yaml | more
apiVersion: apps/v1
kind: Deployment
metadata:
[...]

$ kubectl get pods -n default
NAME                            READY   STATUS    RESTARTS   AGE
tomcat-inst1-778967b875-69lxr   1/1     Running   0          2m8s

$ kubectl get replicaset -n default
NAME                      DESIRED   CURRENT   READY   AGE
tomcat-inst1-778967b875   1         1         1       2m10s

$ helm3 upgrade tomcat-inst1 stable/tomcat --version 0.4.1
Release "tomcat-inst1" has been upgraded. Happy Helming!
NAME: tomcat-inst1
LAST DEPLOYED: Fri Nov 13 11:27:07 2020
NAMESPACE: default
STATUS: deployed
REVISION: 2
[...]

$ kubectl get pods -n default
NAME                            READY   STATUS    RESTARTS   AGE
tomcat-inst1-5c4fb5cd76-xsz92   0/1     Pending   0          46m
tomcat-inst1-778967b875-69lxr   1/1     Running   0          48m

$ kubectl get replicaset -n default
NAME                      DESIRED   CURRENT   READY   AGE
tomcat-inst1-5c4fb5cd76   1         1         0       46m
tomcat-inst1-778967b875   1         1         1       48m
```

**Comment by mattfarina** [comment]
@hickeyma If you use `kubectl describe` you'll see that the new pod is pending because the old one has grabbed ahold or a port. The new pod is waiting for a port to become available to be scheduled. You need more nodes than pods for tomcat to work appropriately. This is all because a host port is in use.

**Comment by hickeyma** [comment]
Missed that about the host port, thanks @mattfarina. It works when tested with multiple nodes.
