### ISSUE TITLE
Request to add a new deployment by helm CLI

### ISSUE THREAD

**Issue by dingmeng** [helm/helm#9015]
Is there a way to create a new kubernetes deployment  by  helm CLI

I already run the helm install  test  xxx.tgz -n ns  , and create a series of deployments.
After run this several days,  I want to create a new deployment to this running kubernetes . 
How to do it by Helm CLI?

**Comment by bacongobbler** [comment]
Hi @dingmeng. Have you had a chance to read through the documentation yet?

https://helm.sh/docs/chart_template_guide/getting_started/

**Comment by bacongobbler** [comment]
Closing as unresponsive. Let us know if you require more information after reading through the docs.

Thanks.
