### ISSUE TITLE
logstash-2.4.3.tgz : 404 Not Found

### ISSUE THREAD

**Issue by rengan2017** [helm/helm#9021]
Hi

I tried to pull the stable logstash but I am getting 404 error code. It looks like file is missed during repo migration. Please check and fix.

[root@centos ~]# helm pull stable/logstash
Error: failed to fetch https://charts.helm.sh/stable/logstash-2.4.3.tgz : 404 Not Found

**Comment by mattfarina** [comment]
Thanks for pointing this out. It's now been fixed. Please to a `helm repo update`. The URL to the chart was pointing to the wrong location. This has now been fixed.
