### ISSUE TITLE
helm upgrade doesnt pick values from default values.yaml when installed with -f flag values.yaml

### ISSUE THREAD

**Issue by rahulroshan-kachchap** [helm/helm#9031]
Here is my helm chart (just the relevant part to this issue)
test/values.yaml:
```
name: failed
MyValue: |
   10.10.10.10 test1
```

test/templates/config.yaml:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
data:
  hosts: {{ .Values.MyValue | quote }}
```

Ran: `helm install test ./test -n spaceX -f test/values.yaml'

```
$ helm describe test -n spaceX
Name:         test
Namespace:    spaceX
Labels:       app.kubernetes.io/managed-by=Helm
Annotations:  meta.helm.sh/release-name: test
              meta.helm.sh/release-namespace: spaceX

Data
====
hosts:
----
10.10.10.10 test1
 ```

Changed test/values.yaml:
```
name: failed
MyValue: |
   10.10.10.10 test1
   20.20.20.20 test2
```

Ran ` helm upgrade test ./test -n spaceX `
```
Release "test" has been upgraded. Happy Helming!
NAME: test
LAST DEPLOYED: Tue Nov 17 06:32:02 2020
NAMESPACE: spaceX
STATUS: deployed
REVISION: 2
TEST SUITE: None
```

**Actual** Description doesn't shows the upgraded values
```
$ helm describe test -n spaceX
Name:         test
Namespace:    spaceX
Labels:       app.kubernetes.io/managed-by=Helm
Annotations:  meta.helm.sh/release-name: test
              meta.helm.sh/release-namespace: spaceX

Data
====
hosts:
----
10.10.10.10 test1
```
**Expected** output with upgraded values
```
$ helm describe test -n spaceX
Name:         test
Namespace:    spaceX
Labels:       app.kubernetes.io/managed-by=Helm
Annotations:  meta.helm.sh/release-name: test
              meta.helm.sh/release-namespace: spaceX

Data
====
hosts:
----
10.10.10.10 test1
20.20.20.20 test2
```

The updated values reflect when i run upgrade command with -f flag 
`helm upgrade test ./test -f test/values.yaml`

Tested below scenarios:
_Scenario1:_ 
Installed helm chart without -f flag for values.yaml
Upgraded helm chart without -f flag for values.yaml -- **Working**

_Scenario2:_
Installed helm chart without -f flag for values.yaml
Upgraded helm chart with -f flag for values.yaml -- **Working**

_Scenario3:_
Installed helm chart with -f flag for values.yaml
Upgraded helm chart without -f flag for values.yaml -- **Not Working**

_Scenario4:_
Installed helm chart with -f flag for values.yaml
Upgraded helm chart with -f flag for values.yaml -- **Working** 

Output of `helm version`: 
version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**Comment by jdolitsky** [comment]
Wondering if the basename of `values.yaml` is the issue here.. What happens if you change the name to something else?
