### ISSUE TITLE
Helm v3 - helm chart pull throws Error: EOF

### ISSUE THREAD

**Issue by pimoens** [helm/helm#9032]
Since yesterday, I've noticed that I am no longer able to pull or export charts hosted on our private chart repository (GitLab).
When executing the following commands:
```
export HELM_EXPERIMENTAL_OCI=1
helm registry login <gitlab>
helm chart pull <gitlab>/<chart>:<version> --debug
```
I receive an error that doesn't provide much information about the source of the problem..
```
Error: EOF
helm.go:81: [debug] EOF
```

The first time this error occurred was when using Helm v3.1.0, I have since then attempted to completely uninstall Helm and re-installed the lastest version v3.4.1, but the issue remains.

Output of `helm version`:
```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by jdolitsky** [comment]
Possibly related to https://github.com/helm/helm/issues/7046

**Comment by pimoens** [comment]
I might add that this setup has worked in the past with exactly the same chart registry hosted on GitLab and that I am unable to replicate the issue on another device.

**Comment by pimoens** [comment]
I resolved the issue by completely deleting the cache `sudo rm -r ~/.cache/helm`. Apparantly the cache wasn't removed when reinstalling Helm using apt
