### ISSUE TITLE
Waiting for *what* condition? 

### ISSUE THREAD

**Issue by symbiont-ji** [helm/helm#9034]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.13-gke.2001", GitCommit:"00c919adfe4adf308bcd7c02838f2a1b60482f02", GitTreeState:"clean", BuildDate:"2020-11-06T18:24:02Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

GKE

During a `helm upgrade`, I get the rather unhelpful message `Error: UPGRADE FAILED: pre-upgrade hooks failed: timed out waiting for the condition`. This isn't even English. Waiting for *what* condition? Even looking at the source code (`git grep 'waiting for the condition`) returns nothing.

Lots of SO hits, no real answer.

**Comment by bacongobbler** [comment]
This error comes from upstream (Kubernetes), so any enhancements to improve the error message will have to be made upstream.

**Comment by bacongobbler** [comment]
After looking at the code, it is indeed an error that is reported from an upstream library, so there's no action we can take here in helm to improve this error message. Please file an issue upstream with Kubernetes. Once a fix is introduced, we'll receive it in the next release.

https://github.com/kubernetes/kubernetes/blob/dde6e8e7465468c32642659cb708a5cc922add64/staging/src/k8s.io/client-go/tools/watch/until_test.go#L211
