### ISSUE TITLE
Feature Request: Add CLI flag to read install/upgrade values from existing ConfigMap

### ISSUE THREAD

**Issue by dhiltgen** [helm/helm#9039]
It would be quite useful if it was possible to install/upgrade a helm chart and pass values to the chart that are persisted in another ConfigMap already existing in the cluster.  Here's a hypothetical UX to demonstrate:

```
% kubectl create configmap mychart-settings --from-literal=global.foo=bar --from-literal=dosomething=true
% helm install --values-configmap=mychart-settings mychart --generate-name
```

This allows a cluster (or namespace) to be "self describing" for a given chart.

This would enable use cases where environment specific settings can be persisted in a commonly named ConfigMap so charts can be installed across different environments and get their specializations from the cluster itself.

**Comment by TBBle** [comment]
This seems like a subset of the behaviour of https://github.com/fluxcd/helm-controller and its stand-alone predecessor, https://github.com/fluxcd/helm-operator.

See [`spec.valuesFrom`](https://toolkit.fluxcd.io/components/helm/helmreleases/#values-overrides) from Helm Controller to get a sense of what a ConfigMap or Secret used in this way might look like, and some interesting interaction possibilities, e.g. `targetPath`.

(For this use-case, I'd probably try to use helm-controller anyway, but if Helm supported something like this natively, then perhaps helm-controller could _use_ it)
