### ISSUE TITLE
Still facing image pull rate limit issue using helm install after paid to upgrade

### ISSUE THREAD

**Issue by fans3210** [helm/helm#9043]
Hi, I've already paid and tested that I'm able to pull images in my local machine and also in minikube by using : docker pull busybox.

However, I'm still facing the image pull rate limit exceed issue when using helm install.

**Comment by hickeyma** [comment]
@fans3210 Do you mind showing the Helm command and the output which includes the error?

**Comment by fans3210** [comment]
@hickeyma The helm command I use is nothing special. Eg: helm upgrade --install gitlab gitlab/gitlab --timeout 600s -f infra/others/helm-gitlab-minimum.values.yaml. The err I'm having is 'exceed pull rate limit' when pulling busybox.

I can confirm this is not helm's issue. I think dockerhub blocks ip from making more pulling after exceed the pull limit. After paid, I still have to wait for some time. Now the issue is resolved after upgrade. Thanks
