### ISSUE TITLE
Feature Request: Let downloader plugin be aware of Chart and Release information

### ISSUE THREAD

**Issue by jBouyoud** [helm/helm#9044]
It could be nice to let downloader plugin be aware of Chart and Release information, especially when the plugin is used to download value files.
This let the availability for plugin to fetch config files that depends of chart name or release name. 
This already be supported the case for the kubeContext and the installation namespace. 

Theses informations can be exposed through [environment variables](https://helm.sh/docs/topics/plugins/#environment-variables)  like actual ones.

Maybe something like : 
* `HELM_CHART_NAME` : The chart name given to the helm command (only when downloading values files).
* `HELM_RELEASE_NAME` : The release name given to the helm command (only when downloading values files).
* Maybe there is others relevant informations that depends of Chart & Release, that I don't see.

For now, there is a workaround to do that, only when the user specify these information in the helm command. 
The plugin can get the parent process and re-parse all commands args ; this is not ideal and it's not works with `--generate-name` and `--name-template` flags.

I'll be glad to make a PR on that subject, if you think this is relevant.

**Comment by mattfarina** [comment]
Can you provide a use case for adding this functionality?

To provide some context, Helm is a package manager like apt, yum, homebrew, etc. Making decisions about what package to install in what situation is usually something a higher level tool would do. Something like helmfile or one of the Helm based operators.

With that in mind, what is the use case and how do you see this fitting in with Helm?

**Comment by jBouyoud** [comment]
Yes of course.

**Context:** 

I've installed a plugin that implement the [Downloading plugin part](https://helm.sh/docs/topics/plugins/#downloader-plugins); to handle a scheme. 
For exemple: 
   * https://github.com/jkroepke/helm-secrets
   * https://github.com/aslafy-z/helm-git  

**When**

I run some chart lifecycle commands like : `helm template|install|upgrade`, with a value file that will be handled by a downloader plugin
Eg.
```
helm template . -f config://config-name
helm template . -f git+https://github.com/jetstack/cert-manager@contrib/charts/values.yaml?ref=v0.5.2
helm template . --generate-name -f secrets://my-secrets.yaml
```

**Actual state**

These plugins receives some information form the helm command :
* All positional arguments of downloader plugin : `command certFile keyFile caFile full-URL`
* All plugin environment variables : described in [this section](https://helm.sh/docs/topics/plugins/#environment-variables)

On these information there for exemple the namespace where the helm command is currently operate in.

**Expected**

Give the availability to these plugin when acting to download a value file, to know some relevant information about the Chart and the Release currently proceed by the Helm command.
As I propose below, there as least two relevant information that are relevant in theses cases : 
* The chart name given to the helm command 
* The release name given to the helm command 

**Possible Solutions**

* Add theses information though environment variables
* Add theses information as optional positional argument of the downloader plugin. For exemple : `command certFile keyFile caFile full-URL [charName] [releaseName]`

I hope this was understandable.
I'll be glad to complete my purpose if needed.

I've start something more specific to my personal use case here: https://github.com/jBouyoud/helm-config-scheme/.

**Comment by jBouyoud** [comment]
@mattfarina anything that i can do to help you ?

**Comment by jBouyoud** [comment]
@mattfarina could you please find my answers in the previous post. How can I help to get a response ?

**Comment by jBouyoud** [comment]
@mattfarina any chance to continue the discussion ? 

I'll be glad to make a PR on that subject, if relevant. 

According to your comment : 
> To provide some context, Helm is a package manager like apt, yum, homebrew, etc. Making decisions about what package to install in what situation is usually something a higher level tool would do. Something like helmfile or one of the Helm based operators.

This change only expose new information (chart-name and release-name) to your downloader plugin interface. Helm doesn't make any new decisions. That's why I convince that's relevant.
