### ISSUE TITLE
Upgrading Helm charts with ingresses may delete the connected LoadBalancer

### ISSUE THREAD

**Issue by liarco** [helm/helm#9050]
This issue is related to: https://github.com/digitalocean/digitalocean-cloud-controller-manager/issues/363

Here is a possible scenario:
- a cluster with a [ingress-nginx/ingress-nginx](https://github.com/kubernetes/ingress-nginx/tree/master/charts/ingress-nginx) chart installed _(no fancy values)_
- we need to upgrade the chart and this process involves deleting and recreating the LoadBalancer resource _(I'm not sure why this happens sometimes, but it does, maybe the new version has some breaking changes?)_

With many providers (e.g. DigitalOcean) deleting a LoadBalancer results in losing it forever with possible unwanted side-effects such as losing the public IP attached to it.

DigitalOcean is providing a [workflow](https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/bbce3f4d89a7c5549b5a0d5f12bceae6b02439d3/docs/controllers/services/examples/README.md#changing-ownership-of-a-load-balancer-for-migration-purposes) to avoid this issue, but while updating the LoadBalancer resource manually doesn't require deleting it, doing it using Helm requires running `helm upgrade ...` so it may lead to the same result.

Is there any best practice to follow or do we miss a feature that allows us to update values without risking to delete a resource? (I'm aware of [`"helm.sh/resource-policy": keep`](https://helm.sh/docs/howto/charts_tips_and_tricks/#tell-helm-not-to-uninstall-a-resource) but I don't know if it can be helpful here...)

Thank you for your time.

**Comment by bacongobbler** [comment]
Yes. The "keep" option for a resource policy is one option to retain an object after a `helm uninstall`.

Does that help address your issue?

**Comment by liarco** [comment]
Hi @bacongobbler,
Thank you for your feedback, my lack of experience with Helm is scaring me when dealing with this kind of situations.

Here are my concerns about using "keep":
1. would it work with `helm upgrade`? I mean, will it allow the upgraded chart to inherit the old resource?
   The doc says:
   > However, this resource becomes orphaned. Helm will no longer manage it in any way. This can lead to problems if using helm install --replace on a release that has already been uninstalled, but has kept resources.
1. how can I use it with a third-party chart? Must the vendor include this option into his chart?

**Comment by bacongobbler** [comment]
If you're curious about the behaviour of a particular feature, my suggestion would be to write a few test scenarios and observe their behaviour in a staging environment. If you have questions/concerns about a particular feature, please feel free to share here after testing them out.
