### ISSUE TITLE
Downgrading helm version 

### ISSUE THREAD

**Issue by faizananwar532** [helm/helm#9053]
Is it possible to uninstall helm latest version that is 3.4 and install specific version like 3.2 or 3.0....if possible how can we do it?

**Comment by bacongobbler** [comment]
Depending on which package manager you used to install Helm, you can also follow their documentation to determine how to upgrade/downgrade to a prior version. But @marckhouzam listed where to find specific release versions to fetch from the release page. You can use that link to fetch a specific version.

Closing as answered. Let us know if you have further questions. Thanks!
