### ISSUE TITLE
get_helm.sh broken

### ISSUE THREAD

**Issue by bpatton00** [helm/helm#9055]
as of a few hours ago it appears that the get_helm.sh script is broken when trying to verify available versions.  I'm not sure if github changed their paging or if the url the script is using is broken.

We are using an older version 2.14.3 and 2.16.7 respectively and both are listed as unavailable via the default script.  I ended up figuring out a super hacky way to get around it in the meantime so our builds can resume.

I had to change release_url to https://github.com/helm/helm/releases?after=v2.15.0 as an example to get 2.14.3.

As I said the summary of it is that https://github.com/helm/helm/releases data is coming back with limited releases so the parsing fails when looking for something not on the first page now.

**Comment by bacongobbler** [comment]
Reverted in https://github.com/helm/helm/pull/9056. Sorry for the trouble.
