### ISSUE TITLE
Upgrade does not revert custom changes

### ISSUE THREAD

**Issue by brianharwell** [helm/helm#9063]
Output of `helm version`: v3.4.1
Output of `kubectl version`: v1.19.1
Cloud Provider/Platform (AKS, GKE, Minikube etc.): On Prem

1. I deploy an application with environment variables using helm.
1. I edit the deployment (`kubectl edit deployment`) and add an environment variable
1. I deploy the application again using helm.

The custom environment should be removed after the helm deployment but it is still there.

This behavior exists with volumes too.

**Comment by bacongobbler** [comment]
This is intended behaviour. Unless the upgrade changes or removes the environment variable, any changes made to the live resource is preserved on upgrade.

If you want to revert back to the previous state, use `helm rollback`.

More information on this behaviour can be found in the [FAQ](https://helm.sh/docs/faq/#improved-upgrade-strategy-3-way-strategic-merge-patches)

**Comment by brianharwell** [comment]
Thanks for the clarification
