### ISSUE TITLE
Can the configmap mount code be implemented in the chart?

### ISSUE THREAD

**Issue by ziyou434** [helm/helm#9071]
I want to add my customer plugin into api-gateway.  Can Range function achieve my mind?
I tried to use map , but the result is not satisfactory.
```yaml
values.yaml
......
code:
  - auth.lua: "xxxxx"
.....
configmap.yaml
......
{{- range $key,$value := .Values.code }}
  {{ $key }}: {{ $value }}
{{- end}}
```
result not match yaml.
```
0: map[auth.lua:xxxxx]
```
It's my anticipation.
```yaml
  auth.lua: "xxxxx"
```
”xxxxx" is escape character of my code.
Can you give me some advice.

**Comment by bacongobbler** [comment]
If you remove the hyphen from values.yaml, does it work as expected?

**Comment by bacongobbler** [comment]
Effectively, you're iterating over a list of key/value dictionaries. What you want is just a key/value dictionary.

Have a read through the YAML specification for more information.

**Comment by ziyou434** [comment]
> 实际上，您正在遍历键/值字典的列表。您想要的只是一个键/值字典。
> 
> 通读YAML规范以了解更多信息。

In fact, I may have multiple files, so I used list.
