### ISSUE TITLE
helm v3.4.1 install and pull can't use custom repository 

### ISSUE THREAD

**Issue by potester** [helm/helm#9078]
hi ，I tried used custom repository to install and pull the stable operating this repository （“http://mirror.azure.cn/kubernetes/charts/” ）every chart used repository redirected https://charts.helm.sh  should be use "http://mirror.azure.cn/kubernetes/charts/"

### version

helm cli version is v3.4.1 and kubectl version is v1.18.10 

```
root@DESKTOP-9KVS0V7:/mnt/d/go_work/src/k8s# helm version
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}


root@DESKTOP-9KVS0V7:/mnt/d/go_work/src/k8s# kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeS
tate:"clean", BuildDate:"2020-10-15T01:52:24Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeS
tate:"clean", BuildDate:"2020-10-15T01:43:56Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

### add one chart repository is  

```
helm repo add stable http://mirror.azure.cn/kubernetes/charts/
```

```
root@DESKTOP-9KVS0V7:/mnt/d/go_work/src/k8s# helm repo list
NAME    URL
stable  http://mirror.azure.cn/kubernetes/charts/
```

#### update

root@DESKTOP-9KVS0V7:/mnt/d/go_work/src/k8s# helm  repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈

#### install 
root@DESKTOP-9KVS0V7:/mnt/d/go_work/src/k8s# helm install stable/tomcat --generate-name
Error: failed to download "stable/tomcat" (hint: running `helm repo update` may help)

#### pull

root@DESKTOP-9KVS0V7:/mnt/d/go_work/src/k8s# helm pull stable/tomcat
Error: failed to fetch https://charts.helm.sh/stable/tomcat-0.4.3.tgz : 404 Not Found

helm used stable repository is "https://charts.helm.sh" not custom repository " http://mirror.azure.cn/kubernetes/charts/"

**Comment by bacongobbler** [comment]
I'm unable to reproduce the issue.

```
~ ><> helm repo add stable https://charts.helm.sh/stable
"stable" has been added to your repositories
~ ><> helm pull stable/tomcat
~ ><> ls
tomcat-0.4.3.tgz
```

**Comment by bacongobbler** [comment]
I can, however, reproduce the issue using the mirrored repository.

```
~ ><> helm repo add mirror http://mirror.azure.cn/kubernetes/charts
"mirror" has been added to your repositories
~ ><> helm pull mirror/tomcat
Error: failed to fetch https://charts.helm.sh/stable/tomcat-0.4.3.tgz : 404 Not Found
```

I have a hunch that the mirror is still pointing at the old storage URL location which suffers from the same issue. Please ask the mirror maintainers to update their upstream URL to https://charts.helm.sh/stable.

As this is something out of our control (it's maintained by someone in the community), there's nothing we can do here to help. Please reach out to the maintainer of this mirror. Thanks.

**Comment by potester** [comment]
thank you

**Comment by potester** [comment]
thanks，it's  mirrored repository's problem I tried  change repository , helm is ok?

Sincerely, Thanks
