### ISSUE TITLE
helm plugin install

### ISSUE THREAD

**Issue by iasha102** [helm/helm#9080]
There are situations where would be necessary to install a plugin from a private Git Repo. 
These includes also CI/CD use cases.

The only available option which I figured out is to use
`helm plugin install https://<token>@github.com/namecpace/name/`
in my case is more specific 
`helm plugin installhttps://$SYSTEM_ACCESSTOKEN@dev.azure.com/orgname/project/_git/helm-update-chart`

Now any token would be identified as an user and **helm** will try to create a cache directory with the token name in it,
which would be saved as directory name and exposed to many apps. 
Second issue is that if token is too long Linux won't be able to handle this install. 

https://github.com/helm/helm/blob/2be0d141a631969374b3c5a84e90f3f4f01ee816/pkg/plugin/cache/cache.go#L42

Output Helm: 
```
error: Unable to get repository: fatal: could not create work tree dir '/home/***/.cache/helm/plugins/https-***-dev.azure.com-***-****-_git-helm-update-chart': File name too long
```

Proposal:
1. to create a verification if username is a username or a token and if token to remove from name of the cache directory. 
2. to remove username from name of the cache directory

**Comment by bacongobbler** [comment]
If you think you’ve found a security issue, please disclose these issues responsibly by following the security process. Please don’t discuss security issues in public.

https://github.com/helm/community/blob/master/SECURITY.md

Closing and editing the OP’s ticket to scrub any information.
