### ISSUE TITLE
`helm chart export` does not restore Chart.lock from cache

### ISSUE THREAD

**Issue by tompizmor** [helm/helm#9086]
Not sure if it is an issue or the behavior is the expected one, but with the experimental support for OCI I have observed that if you export a chart from the local cache it does not restore the original Chart.lock file.

## Steps to reproduce

Get an API V2 chart with dependencies (for example the following one from bitnami repo)

Add Bitnami repo and fetch chart
```
$ helm repo add bitnami https://charts.bitnami.com/bitnami
$ helm repo update
$ helm fetch bitnami/mariadb --version 9.0.1
```

Enable experimental support for OCI
```
$ export HELM_EXPERIMENTAL_OCI=1
```

Save the downloaded chart into the cache
```
$ helm chart save mariadb-9.0.1.tgz my-oci-reference/mariadb:9.0.1
```

Export chart from cache to deploy from local folder
```
$ helm chart export my-oci-reference/mariadb:9.0.1
$ ls mariadb/
Chart.yaml             README.md              charts                 ci                     templates              values-production.yaml values.schema.json     values.yaml
```

You can see how after exporting the chart, there is no Chart.lock. However, this file is present in the original chart downloaded from the Bitnami repo.

I've been checking the code and I see that specific file (`Chart.lock`) is not being restored in the [SaveDir()](https://github.com/helm/helm/blob/master/pkg/chartutil/save.go#L40) function

If you consider this should be fixed I am willing to prepare a PR.

Thanks!

------------

Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

Output of `kubectl version`: Does not apply

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Not apply

**Comment by bacongobbler** [comment]
The code itself is planned to be ripped out, so I wouldn't attempt to fix it.
