### ISSUE TITLE
helm repo add is sensitive to trailing slash in repo URL

### ISSUE THREAD

**Issue by AurelienGasser** [helm/helm#9092]
Running the same `helm repo add` command twice, with and without a trailing slash in the repo URL, gives an error:

```sh
$ helm repo add owkin https://owkin.github.io/charts
"owkin" has been added to your repositories
```

```sh
$ helm repo add owkin https://owkin.github.io/charts/
Error: repository name (owkin) already exists, please specify a different name
```

This can be problematic especially since the second `helm repo add` returns a non-0 exit code. As a result, some of our automated scripts fail. This could easily be avoided if the URLs with and without trailing slash were treated as identical (see also: https://github.com/helm/helm/issues/1588 https://github.com/helm/helm/issues/1664)

Another way to address this problem would be to provide guidance as to whether or not trailing slashes SHOULD be used in URLs. I couldn't find such guidance in the current helm documentation.

Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

Output of `kubectl version`:

Not applicable

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Not applicable

**Comment by sagar-jadhav** [comment]
@AurelienGasser The reason behind `Error: repository name (owkin) already exists, please specify a different name` error is    this line https://github.com/helm/helm/blob/976d668dec032f7ce309f31f65a50cebb9b0be95/cmd/helm/repo_add.go#L163

As the repo name is the same but the URL is different code identifies that configurations are changed and throws an error here.

Use `--force-update` to avoid the error.

**Comment by mattfarina** [comment]
@AurelienGasser I understand what you're saying. If you add the exact same repo twice you get a message of:

```
"owkin" already exists with the same configuration, skipping
```

You want that with and without the /.

PRs welcome for this.
