### ISSUE TITLE
Helm3 filter isn't working properly; large deployments timeout before filter is in place. 

### ISSUE THREAD

**Issue by hunkeelin** [helm/helm#9100]
# Problem
As title said and anyone who uses helm, large deployment `helm ls` will result in timeout. I understand it's trying to read and parse all the secrets and revision. In order to actually fix it we will have to change how data is stored. Helm's filter function filter the results after it got query. 

# Solutions
**Long term solution (helm 4)**: Change how data is stored so large deployments won't get bottlenecked.

**Short term solution (helm 3)**: Current helm make use of `k8s.io/apimachinery/pkg/apis/meta/v1` library to retrieve secrets. We should use `labelselector` when calling `List` to filter results instead of querying all secrets and apply custom regex filter.  

```
 82 func (secrets *Secrets) List(filter func(*rspb.Release) bool) ([]*rspb.Relea    se, error) {
 83     lsel := kblabels.Set{"owner": "helm"}.AsSelector()
 84     if os.Getenv("helm-serviceName") != "" {
 85         lsel = kblabels.Set{
 86             "owner": "helm",
 87             "name":  os.Getenv("helm-serviceName"),
 88         }.AsSelector()
 89     }
 90     opts := metav1.ListOptions{LabelSelector: lsel.String()}
 91
 92     list, err := secrets.impl.List(context.Background(), opts)
 93     if err != nil {
 94         return nil, errors.Wrap(err, "list: failed to list")
 95     }
```
The above code is a workaround by using environment variables. In line 87 one can specify labels so the query results will be more specific. As of now, implementation of this functionality is difficult. That is because there is no way to change the behavior of the driver's output base on input.  More info in [this pull request](https://github.com/helm/helm/pull/9101)

**Comment by mattfarina** [comment]
Can you provide a range for what you mean by large? Helm has used ConfigMaps (previously the default - before Secrets were possible) and now Secrets and rarely has this been an issue. Some data on what large means would be helpful in understanding the problem. Also, how that size relates to namespaces. Is it all in one namespace or spread among many.

The size will also relate to the history of releases you can store. Are you using the default history length for a release of a chart or are you extending that to be longer?

For these more complicated storage needs, Helm has [an SQL storage back-end](https://helm.sh/docs/topics/advanced/#sql-storage-backend) that can be used instead. This is an option for the large deployments.

If you have a suggestion on storing information differently, please consider writing a [Helm Improvement Proposal](https://github.com/helm/community/tree/master/hips). Note, when it comes to storage we aren't to use CRDs and are wary of server side components being installed by default. There are many Kuberentes users who do not have access to install CRDs and cannot install a cluster wide controller. They use Helm and we do consider their experience.

**Comment by bacongobbler** [comment]
> Current helm make use of `k8s.io/apimachinery/pkg/apis/meta/v1` library to retrieve secrets. We should use `labelselector` when calling `List` to filter results instead of querying all secrets and apply custom regex filter.

It's also important to note that a flag already exists today providing this functionality. It is not used as the default because it only works for the configmap and secret drivers. It does not support other drivers because there is no notion of a "label selector" for other storage drivers. You're looking for `helm list --selector`.

**Comment by hunkeelin** [comment]
> Can you provide a range for what you mean by large? Helm has used ConfigMaps (previously the default - before Secrets were possible) and now Secrets and rarely has this been an issue. Some data on what large means would be helpful in understanding the problem. Also, how that size relates to namespaces. Is it all in one namespace or spread among many.
**Things start getting slow when we have 100 helm releases of history of 4**
> 
> The size will also relate to the history of releases you can store. Are you using the default history length for a release of a chart or are you extending that to be longer?
**The default size was 10, it was we got timed out so we change the size to 4. It worked for a while and now it's timing out.** 
> 
> For these more complicated storage needs, Helm has [an SQL storage back-end](https://helm.sh/docs/topics/advanced/#sql-storage-backend) that can be used instead. This is an option for the large deployments.
**Ok, i'll follow this suggestion**
> 
> If you have a suggestion on storing information differently, please consider writing a [Helm Improvement Proposal](https://github.com/helm/community/tree/master/hips). Note, when it comes to storage we aren't to use CRDs and are wary of server side components being installed by default. There are many Kuberentes users who do not have access to install CRDs and cannot install a cluster wide controller. They use Helm and we do consider their experience.

**I did some performance testing, the main time sink is the `k8s.io/client-go/kubernetes/typed/core/v1` `list` function** being called  in `pkg/storage/driver/secrets.go`'s ` list, err := secrets.impl.List(context.Background(), opts)`.  For people who uses eks with large releases. I have 100x releases with revision of 4. It's trying to do 400ish api calls resulting in getting throttled. My suggestion is instead of storing each revision as a secret, restructure in a way that each secrets correspond to it's release and all its revisions.**

**Comment by bacongobbler** [comment]
@mattfarina pointed this out earlier. Before discussing any further, I would suggest writing out your thoughts and suggestions in a [Helm Improvement Proposal](https://github.com/helm/community/tree/master/hips). The HIP process is what we are suggesting to new contributors looking to re-architect sections of the Helm codebase. It helps answer many of the cases maintainers need to address when considering a new feature... Filtering release objects in the storage backend via a label selector would be considered by many to be a feature. Backwards compatibility, documentation, security issues, etc. are all aspects that need to be discussed and addressed during the design process.

Hope that helps.

**Comment by hunkeelin** [comment]
I"ll write up an HIP. Closing this issue now.
