### ISSUE TITLE
 How to Ignore Semver Check with helm package

### ISSUE THREAD

**Issue by Vastyjoy** [helm/helm#9102]
There is a need to pack helm chart under the snapshot version.
How can i do this?

It turned out to use "1.0.0-snapshot", but I would like "develop-snapshot"
Many versions are compiled from parallel branches
Output of `helm version`: 3.4.1

**Comment by mattfarina** [comment]
Helm not only follows semver but some things will not work right if a non-semver version were used. Helm expects semver.

I am not sure what you mean by snapshot. You might want to look at [the semver spec](https://semver.org/) and the section on prereleases. The spec has examples.

**Comment by grazius** [comment]
A snapshot is a maven version notation that says it's not a it's a version where you prepare your next version iteration (it's not a release).

@Vastyjoy semver global format is `<version core> "-" <pre-release> "+" <build>` so in your case you normally can do "1.0.0-develop+snapshot"
