### ISSUE TITLE
rendered manifests contain a resource that already exists

### ISSUE THREAD

**Issue by ruanjianxuetu** [helm/helm#9104]
i have a chart, which will delete secret "xxx" that already exists in k8s , and deploy my own secret "xxx" to k8s, using helm hook  "helm.sh/hook": "pre-install".  it worked in helm2 ,bu get error in helm3 .
is it by design, or there is something I missed?

**Comment by bacongobbler** [comment]
Hi @ruanjianxuetu. I transferred this issue to helm/helm. Please file bug reports over there in the future. helm/community is for discussions around high-level org things like mailing lists, governance, communication, meetings, etc.

When opening a ticket, we also ask that you provide an example which can be used to reproduce the issue on our end. Please provide an example. Thanks.

**Comment by bacongobbler** [comment]
At first glance however, yes this does look to be by design. If your chart is attempting to install a resource that already exists in the cluster, Helm will not "commandeer" that resource, and instead returns an error.

**Comment by ruanjianxuetu** [comment]
thanks for your reply.
here is the situation I met. the pre-existing secret is the configfile of alertmanager, which is maintained by our paas team. I need to customize the config without manual intervention.  If the pre-install hook can not work under this situation, do you have any suggestion what I can do

**Comment by bacongobbler** [comment]
Sounds like you're looking for a tool that provides configuration management. The tooling and use cases are different than a package manager. Something like terraform might be helpful here. Helm is meant to be used as a tool to package your software and deploy it to Kubernetes. It is not intended for use to manage resources managed by another "package" or maintained by another piece of software.
