### ISSUE TITLE
Issue with `helm chart save` and fully numeric tags

### ISSUE THREAD

**Issue by julien-sugg** [helm/helm#9112]
Hi, 

I am not sure whether it is a bug or an expected behavior, but I am facing some weird behaviors with the experimental support for OCI (`HELM_EXPERIMENTAL_OCI=1`) and `helm chart save`.

I noticed that when I perform a `helm chart save` using a numeric only tag (being a git short sha for my particular automation use-case), I end up with an error:

```shell
# simplified stdi/o from my CI pipeline
$ helm chart save "./helm/charts/my-chart" myregistry.com/mymonorepo/helm-branches/microservice-1-develop:64875383
Error: ref may only contain a single colon character (:) unless specifying a port number
```

# Current Configuration

Output of `helm version`:

```shell
$ helm version
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

Output of `kubectl version`: Not Applicable

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Not Applicable

# How to reproduce

- Fetch any chart or use any local chart
- Enable experimental support for OCI
```shell
$ export HELM_EXPERIMENTAL_OCI=1
```
- Save the chart into the cache
```shell
$ helm chart save <THE_CHART> myregistry.com/the-chart:64875383
```
- Exit code `1` with the following stderr `Error: ref may only contain a single colon character (:) unless specifying a port number`

Please let me know if you need any additional information.

**Comment by mattfarina** [comment]
I just want to give you a warning that parts of Helm depend on the version being semver. A purely numerical number is technically a major semver. This may cause you issues in the future.

**Comment by wawa0210** [comment]
It seems to be in line with expectations. The chart.yaml in the charts already contains the version number. At this time, the name specified by save contains ":", and helm will try to join the specified name with the version in the chart.yaml, and found two ":" matches, so an error is throw

**Comment by julien-sugg** [comment]
Thanks for the clarification @mattfarina . I believe I amprobably  not correctly using the command for my review apps.

Does that mean that when I do a `helm chart save myChart myregistry.com/myChart:64875383`, the version number specified in `Chart.yaml` is in fact completely ignored instead of being used as a prefix (as I might have falsely assumed) and would have ended up with a ref similar to `myregistry.com/myChart:64875383`  if no error occurred ?

> Note that for my release pipeline, I perform a basic `helm chart save myChart myregistry.com/myChart` which works like a charm and properly uses the `version` information from my `Chart.yaml` file.

**Comment by jdolitsky** [comment]
@julien-sugg in the future, the registry publishing will use the version in Chart.yaml as the registry tag to prevent issues like this. Please see this document for the roadmap: https://github.com/helm/community/blob/master/hips/hip-0006.md

**Comment by darobs** [comment]
Hi @jdolitsky  

I discovered this issue accidentally, I understand that this implementation is not final, but I may have a use case which the design doc may have not considered:

We generally run regular image builds, usually on a commit to master.  These are not release builds, and the version number does not update. These images are tagged by date.  The Helm chart images may have been updated, and I'd like to test the charts from my specific build.  In this circumstance, I don't want chart images tagged by chart semver.


The image name processing seems incorrect regardless.  This is what I found (names have been changed):

```sh
$ helm chart save /tmp/charts/mychart acr.azurecr.io/test1/my-chart:1
ref:     acr.azurecr.io/test1/my-chart:1:0.2.10
digest:  685afaabadade66236bd92a5a147d7d01a58b98ac11ed248a8aa5f9a720aa413
size:    734 B
name:    my-chart
version: 0.2.10
0.2.10: saved
```

Shouldn't the format be "\<repo\>:**\<port\>**/\<namespace\>/\<image\>:\<tag\>"?  The ref above is ""\<repo\>/\<namespace\>/\<image\>:**\<port\>**:\<tag\>". 
When I tried to push the image I created, I received `unexpected status: 404 Not Found`.

Other results:
```sh
$ helm chart save /tmp/charts/mychart acr.azurecr.io/test1/my-chart:20210304
Error: ref may only contain a single colon character (:) unless specifying a port number

$ helm chart save /tmp/charts/mychart acr.azurecr.io/test1/my-chart:202103.01
ref:     acr.azurecr.io/test1/my-chart:202103.01
digest:  2f8fc475e58b551c15c120472a50996436bbf16b173aaf1c4c6f268876b27829
size:    731 B
name:    my-chart
version: 0.2.10
202103.01: saved
```

The `202103.01` tag is a build number.  `20210304` is how I mistakenly wrote it to discover this bug.

Other results:
```sh
$ helm chart save /tmp/charts/mychart acr.azurecr.io/test1/my-chart:20
ref:     acr.azurecr.io/test1/my-chart:20:0.2.10
digest:  b14ec9ed7ba5349a0a4ce1c28683b3254bb6a0b0ecd31917d9186c9897a1237c
size:    735 B
name:    my-chart
version: 0.2.10
0.2.10: saved

$ helm chart save /tmp/charts/mychart acr.azurecr.io/test1/my-chart:20210
ref:     acr.azurecr.io/test1/my-chart:20210:0.2.10
digest:  66ac416cb3becae61caa159c08e02929a1cac756f55ff69b0b252bfa7c150866
size:    734 B
name:    my-chart
version: 0.2.10
0.2.10: saved
$ helm chart save /tmp/charts/mychart acr.azurecr.io/test1/my-chart:202103
Error: ref may only contain a single colon character (:) unless specifying a port number

$ helm version
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

**Comment by roitalpaz** [comment]
This occurred to me too, is a fix possible?

**Comment by jdolitsky** [comment]
Hello, while this issue is still present, the entire `helm chart` subcommand will soon be removed. OCI-support will still exist, just in a different form. For more info, please see https://github.com/helm/community/blob/main/hips/hip-0006.md

**Comment by darobs** [comment]
@jdolitsky I still don't like the tag==chart idea, and the explanation in the document is inadequate to explain how a person running a CI pipeline might manage the Helm chart produced for a pre-release build.
