### ISSUE TITLE
Helm upgrade: during the upgrade, it's possible that no record of a "deployed" status release exists in the storage

### ISSUE THREAD

**Issue by mikeshng** [helm/helm#9113]
During the helm upgrade, it seems like there is a gap in time where no "deployed" status release exists in the storage or from my testing no release exists at all. See possible lines:

https://github.com/helm/helm/blob/v3.4.2/pkg/action/upgrade.go#L301-L302
https://github.com/helm/helm/blob/v3.4.2/pkg/action/upgrade.go#L345-L346
https://github.com/helm/helm/blob/v3.4.2/pkg/action/upgrade.go#L136-L137

To reproduce (might have to try a few times to see the result due to the nature of this timing issue):
- In one terminal keep the following running:
` while true; do helm ls; done`
- In another terminal kick off a helm upgrade like:
`helm upgrade nginx-ingress nginx-ingress-1.36.3.tgz `

then observe the output of `helm ls` and see that 
```
NAME         	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART               	APP VERSION
nginx-ingress	default  	4       	2020-12-09 11:01:37.140162288 -0500 EST	deployed	nginx-ingress-1.36.3	0.30.0     
NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART	APP VERSION <------------ SEE HERE no release found
NAME         	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART               	APP VERSION
nginx-ingress	default  	5       	2020-12-09 11:01:43.634790609 -0500 EST	deployed	nginx-ingress-1.36.3	0.30.0     
NAME         	NAMESPACE	REVISION	UPDATED   
```

Output of `helm version`:

`version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}`

Output of `kubectl version`:

`
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2020-01-14T00:09:19Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
`kind`

**Comment by bacongobbler** [comment]
Hi @mikeshng. What issues arise from this behaviour? Without performing some form of an atomic update, I don't see a way around this. We've had to work around issues where two releases ended up in a DEPLOYED state, so I do not believe we can change this behaviour unless there's some form of transactional update system in Kubernetes.

**Comment by mikeshng** [comment]
Hi @bacongobbler the practical usage is building an operator around helm and need to have a reliable way of telling if an app is deployed or not. Ie: https://sdk.operatorframework.io/docs/building-operators/helm/quickstart/

If you have a few cycles, could you please clarify the release records state transition or "lifecycle" behind the upgrade? Thanks.

**Comment by mikeshng** [comment]
I think the status transition is:

current release: deployed
upgrade release: pending upgrade

=>

current release: superseded
upgrade release: pending upgrade

=> 

current release: superseded
upgrade release: deployed

If the last transition fails then we are left with the middle state but all the real work has been done.

Do you think it will be helpful to add something like `helm storage reconcile` or `helm storage sync` that looks at situations like this and set the release into the right state?
