### ISSUE TITLE
WARNING: Kubernetes configuration file is group/world-readable

### ISSUE THREAD

**Issue by ydekel6** [helm/helm#9115]
* Output of `helm version`:
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
Output of `kubectl version`:
* Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
* Platform: ubuntu 20.4 (latest through microsoft store as to 10/12/2020) on windows 10 pro (clean install of build 19042.662) through wsl2.

when doing any `helm` command you always these lines:
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/username/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/username/.kube/config

pretty new to the wsl2/helm/k8s but I couldn't find any way to remove those  warnings. probably a duplicate of #8776

**Comment by bacongobbler** [comment]
Your `~/.kube/config` should only be readable by you. Use `chmod` to change the file's read/write permissions.

```
><> ls -al ~/.kube/
total 20
drwxr-xr-x  3 bacongobbler bacongobbler 4096 Dec  1 09:43 .
drwxr-xr-x 23 bacongobbler bacongobbler 4096 Dec  9 13:18 ..
drwxr-x---  4 bacongobbler bacongobbler 4096 Nov 10 10:32 cache
-rw-------  1 bacongobbler bacongobbler 5514 Dec  1 09:43 config
```

To demonstrate, I'll make the file group-readable, then world-writeable. Then show how to remove those permissions.

```
><> chmod g+r ~/.kube/config
><> helm version
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/bacongobbler/.kube/config
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
><> chmod o+r ~/.kube/config
><> helm version
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/bacongobbler/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/bacongobbler/.kube/config
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

Notice the change in permissions:

```
><> ls -al ~/.kube/config
-rw-r--r-- 1 bacongobbler bacongobbler 5514 Dec  1 09:43 /home/bacongobbler/.kube/config
```

To remove those permissions, use the inverse:

```
><> chmod o-r ~/.kube/config
><> chmod g-r ~/.kube/config
```

A more compact version would be

```
><> chmod go-r ~/.kube/config
```

Hope that helps.

**Comment by ydekel6** [comment]
thanks a lot! this fixed everything

**Comment by deflorator1980** [comment]
> Your `~/.kube/config` should only be readable by you. Use `chmod` to change the file's read/write permissions.
> 
> ```
> ><> ls -al ~/.kube/
> total 20
> drwxr-xr-x  3 bacongobbler bacongobbler 4096 Dec  1 09:43 .
> drwxr-xr-x 23 bacongobbler bacongobbler 4096 Dec  9 13:18 ..
> drwxr-x---  4 bacongobbler bacongobbler 4096 Nov 10 10:32 cache
> -rw-------  1 bacongobbler bacongobbler 5514 Dec  1 09:43 config
> ```
> 
> To demonstrate, I'll make the file group-readable, then world-writeable. Then show how to remove those permissions.
> 
> ```
> ><> chmod g+r ~/.kube/config
> ><> helm version
> WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/bacongobbler/.kube/config
> version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
> ><> chmod o+r ~/.kube/config
> ><> helm version
> WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/bacongobbler/.kube/config
> WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/bacongobbler/.kube/config
> version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
> ```
> 
> Notice the change in permissions:
> 
> ```
> ><> ls -al ~/.kube/config
> -rw-r--r-- 1 bacongobbler bacongobbler 5514 Dec  1 09:43 /home/bacongobbler/.kube/config
> ```
> 
> To remove those permissions, use the inverse:
> 
> ```
> ><> chmod o-r ~/.kube/config
> ><> chmod g-r ~/.kube/config
> ```
> 
> A more compact version would be
> 
> ```
> ><> chmod go-r ~/.kube/config
> ```
> 
> Hope that helps.

May by `chmod 600 ~/.kube/config` would be easier?:)

**Comment by bacongobbler** [comment]
Yes, whichever floats your boat. The end result is the same.

**Comment by minaairsupport** [comment]
to summary the solution just run these two commands 

```
chmod o-r ~/.kube/config
chmod g-r ~/.kube/config
```

**Comment by hashimyousaf1** [comment]
> > Your `~/.kube/config` should only be readable by you. Use `chmod` to change the file's read/write permissions.
> > ```
> > ><> ls -al ~/.kube/
> > total 20
> > drwxr-xr-x  3 bacongobbler bacongobbler 4096 Dec  1 09:43 .
> > drwxr-xr-x 23 bacongobbler bacongobbler 4096 Dec  9 13:18 ..
> > drwxr-x---  4 bacongobbler bacongobbler 4096 Nov 10 10:32 cache
> > -rw-------  1 bacongobbler bacongobbler 5514 Dec  1 09:43 config
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > To demonstrate, I'll make the file group-readable, then world-writeable. Then show how to remove those permissions.
> > ```
> > ><> chmod g+r ~/.kube/config
> > ><> helm version
> > WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/bacongobbler/.kube/config
> > version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
> > ><> chmod o+r ~/.kube/config
> > ><> helm version
> > WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/bacongobbler/.kube/config
> > WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/bacongobbler/.kube/config
> > version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Notice the change in permissions:
> > ```
> > ><> ls -al ~/.kube/config
> > -rw-r--r-- 1 bacongobbler bacongobbler 5514 Dec  1 09:43 /home/bacongobbler/.kube/config
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > To remove those permissions, use the inverse:
> > ```
> > ><> chmod o-r ~/.kube/config
> > ><> chmod g-r ~/.kube/config
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > A more compact version would be
> > ```
> > ><> chmod go-r ~/.kube/config
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Hope that helps.
> 
> May by `chmod 600 ~/.kube/config` would be easier?:)

Way easier!

**Comment by jamescanady** [comment]
Is there a way to disable this warning when using it within a WSL layer?

**Comment by jetersen** [comment]
@jamescanady this is how I resolved it:

On WSL Linux create a `etc/wsl.conf`
```
[automount]
enabled = true
options = "metadata,umask=22,fmask=11"
```

Reboot windows

Once rebooted you should be able to run `chmod 700 /mnt/c/Users/joseph/.kube/config` on your symlinked `~/.kube/config` file

```
$ ls -la /mnt/c/Users/joseph/.kube/config
.rwx------ 29k joseph 24 May 09:47 /mnt/c/Users/joseph/.kube/config
```

Credit to this: https://www.turek.dev/posts/fix-wsl-file-permissions/

**Comment by OddKMS** [comment]
@jetersen you absolute legend!
Came here for the same WSL-issue, thank you so much :)

**Comment by mayankrkhunt** [comment]
`chmod 600 ~/.kube/config` will work perfect.

**Comment by YunanJeong** [comment]
`chmod 600 ~/.kube/config` is so good.
But, If you use `600`, `the config file's owner and group must match your current user.`

```
# Check owner and group
ls -l ~/.kube/config

# Change owner and group.  # 'ubuntu' is my current user. Change the name to yours
sudo chown ubuntu:ubuntu ~/.kube/config

# 600
sudo chmod 600 ~/.kube/config
```
---
On `K3s`, `root` is the default value. show this below.

```
$ ls -l /etc/rancher/k3s/k3s.yaml
rw------- 1 root root 2953 Apr  1 17:31 /etc/rancher/k3s/k3s.yaml

$ sudo chown myuser:myuser /etc/rancher/k3s/k3s.yaml

$ ls -l /etc/rancher/k3s/k3s.yaml
rw------- 1 myuser myuser 2953 Apr  1 17:31 /etc/rancher/k3s/k3s.yaml

$ sudo chmod 600 /etc/rancher/k3s/k3s.yaml
```
