### ISSUE TITLE
Helm 3 install for MacOS 

### ISSUE THREAD

**Issue by mihaela202** [helm/helm#9117]
hello, i need to install the Helm 3 in to my MacOS and when i run sudo ./get_helm.sh it gives me this error. Please help

tar: Error exit delayed from previous errors.
Failed to install helm
	For support, go to https://github.com/helm/helm. 

Output of `helm version`:

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by marckhouzam** [comment]
Hi @mihaela202.  Did you manage to get your installation working?

With the info provided, it is hard to know what the problem can be. You could activate debug logs in the hopes of seeing what command triggers the error.  So you can do:
```
DEBUG=true ./get-helm-3
```

**Comment by marckhouzam** [comment]
Closing for lack of feedback. Feel free to reopen if the problem persists.
