### ISSUE TITLE
Is it possible to move filterselector into the `list` function 

### ISSUE THREAD

**Issue by hunkeelin** [helm/helm#9122]
Functionality: `helm ls`
File: https://github.com/helm/helm/blob/master/pkg/action/list.go

I see `filterselector` being called on [line 187](https://github.com/helm/helm/blob/master/pkg/action/list.go#L187). Is it possible to move `filterselector`'s logic to [the List function](https://github.com/helm/helm/blob/master/pkg/action/list.go#L158)? The reason for this is because one could set `labels` filter when calling the kubernetes api to significantly reduce wait time for larger deployments. The way the code is written, it's querying all the secrets regardless of the labels; return the result, then run `filterselector` on it. It seems `--selector` is just a weaker version of `--filter`.

**Comment by bacongobbler** [comment]
I believe that's what I proposed in https://github.com/helm/helm/issues/9100#issuecomment-741048676, wasn't it?

Have you opened a HIP yet?

**Comment by hunkeelin** [comment]
> I believe that's what I proposed in [#9100 (comment)](https://github.com/helm/helm/issues/9100#issuecomment-740732095), wasn't it?
> 
> Have you opened a HIP yet?

#9100 is me attempting to do it but failed. I was wondering is it possible to put the logic in the `list` function. It seems the list function is designed in a way that it's not possible to input parameter and I think I might be wrong. The HIP is regarding storing data in a different way which is not related to this question at the moment.
