### ISSUE TITLE
May named template be intentionally overwritten by top-level named template?

### ISSUE THREAD

**Issue by kkujawa-sumo** [helm/helm#9129]
I would like to overwrite named template which is defined in sub chart. Reading [this](https://helm.sh/docs/chart_template_guide/named_templates/) I see that template names are global.
I'm able to overwrite named template by redefining it in top-level chart but I'm curious if it deterministic behaviour. 
Are there any side-effects of redefining named templates in top-level chart?

**Comment by bacongobbler** [comment]
I think this would be a wonderful use case as a new topic in the docs. Let us know what you find out.

**Comment by ajdergute** [comment]
I can confirm that described scenario will work. I plan to use this for placeholder templates been overwritten in parent chart.
If you want to access parent values three simplest, maybe only, way is to make them global. The template seems to be executed in context of the subchart.
If anyone is able to confirm, if this behaviour is intentionally I'm also very happy.

**Comment by ajdergute** [comment]
I'm willing to contribute a documentation for this. @bacongobbler can you assist me were it should be located at best. May it: https://github.com/helm/helm-www/blob/master/content/en/docs/chart_template_guide/subcharts_and_globals.md ?

Also is it necessary to open an issue at helm-www?
