### ISSUE TITLE
how to set proxy?

### ISSUE THREAD

**Issue by myhellone** [helm/helm#9133]
Hi! 
How to set http/https proxy for helm_v3?

**Comment by bacongobbler** [comment]
Hi @myhellone. I believe this question has been asked before. Have you had a chance to look through the ticket queue archive and see if this hasn't been answered already?

For example: https://github.com/helm/helm/issues/5220#issuecomment-464642930

**Comment by myhellone** [comment]
@bacongobbler 
Thanks for your replay,
I want to see simple answer how to setup proxy for helm_3

I watch other issue and I don't see simple answer.

**Comment by uqix** [comment]
How to set proxy in a way like in CentOS yum.conf?

**Comment by mattfarina** [comment]
@myhellone Are you talking about communications with Kubernetes or for communications with Helm repositories and when Helm communicates with container registries?

Each of these has a different method.

For Helm communicating to Helm repos and container registries you can set the environment variables of `HTTP_PROXY`, `HTTPS_PROXY`, and `NO_PROXY`. Helm will see and use these.

Kubernetes has gone a different route. You need to use Helm v3.4 or newer for this feature as that is the version that pulls in the Kubernetes 1.19 packages with the feature. You will also need kubectl 1.19 to manage your Kubernetes configuration.

I don't see any docs for this but the PR is [here](https://github.com/kubernetes/kubernetes/pull/81443). I think the Kubernetes project would like docs if someone wants to write them.

**Comment by myhellone** [comment]
@mattfarina 
Thank you
