### ISSUE TITLE
While saving chart.Chart in a directory using the chart.Chart.Values and not the file data

### ISSUE THREAD

**Issue by debarshibasak** [helm/helm#9137]
Output of `helm version`: v3.4.1

Output of `kubectl version`: >1.18.0

Cloud Provider/Platform (AKS, GKE, Minikube etc.): ALL

chart.Chart is allows manipulating the values map. However on chartutil.Save, the values is picked up from c.Raw, thus all the mutations in the chart.Chart.Values are not picked up.

Solution,

while saving values.yaml, convert chart.Chart.Values.ToYaml() and then save it.

I am not sure if the issue clear enough. If you agree with the argument, I can created a pull request.

**Comment by debarshibasak** [comment]
I would do something like this 

```
	for _, f := range c.Raw {
		if f.Name == ValuesfileName {
			var  values Values = c.Values
			if err := writeToTar(out, filepath.Join(base, ValuesfileName), values.YAML()); err != nil {
				return err
			}
		}
	}
```

In line https://github.com/helm/helm/blob/bed1a42a398b30a63a279d68cc7319ceb4618ec3/pkg/chartutil/save.go#L187

**Comment by bacongobbler** [comment]
This is intentional. Re-calculating the chart values causes comments in the original values file to be purged. There’s a ticket in the queue asking for —set and —values for `helm package`. I’d suggest following that thread for further information. (On mobile so can’t look it up right now)

**Comment by bacongobbler** [comment]
https://github.com/helm/helm/issues/3141

**Comment by debarshibasak** [comment]
Thank you.
