### ISSUE TITLE
kubernetes-charts.storage.googleapis.com missing rabbitmq chart

### ISSUE THREAD

**Issue by bobanda87** [helm/helm#9140]
Output of `helm version`:
2.13.0
Output of `kubectl version`:
1.10.11
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Hi all,

I am experiencing issues with rabbitmq not being able to be fetched from https://kubernetes-charts.storage.googleapis.com/

I have this defined for rabbitmq:

```
- name: rabbitmq
    version: 0.6.17
    repository: https://kubernetes-charts.storage.googleapis.com/
```

It seems like it is not possible to fetch rabbitmq from this storage. Anyone can suggest some other storage URL that I can use instead?

**Comment by bacongobbler** [comment]
https://helm.sh/blog/helm-2-becomes-unsupported/
