### ISSUE TITLE
helm3 repo add is returning Error `Permission Denied`

### ISSUE THREAD

**Issue by Arsen-Uulu** [helm/helm#9144]
`helm version`: v3.2.4

`kubectl version`: v1.18.0

Cloud Provider/Platform (AKS, GKE, Minikube etc.): EKS

Running helm3 in a docker container `alpine:3`. When running command `helm repo add <repo-name> <repo-url>`
Getting an error: `Error: mkdir /.config: permission denied`. why is trying to create that folder under `/.config`that's owned by root, when helm is executed by the user that owns the container and not create it like this `~/.config`? 

I used 
```
--registry-config /var/jenkins_home/.config/ 
--repository-cache /var/jenkins_home/.cache
```
and still Helm is trying to create `/.config` folder.

**Comment by mattfarina** [comment]
`helm repo add` will add a repository and store that configuration on the local filesystem. The location it stores this information by default is based on a number of factors including who the user is running helm and the platform its on. Helm tries to store the data in the system default location (e.g., app data on Windows and Library on mac).

Something about the containers setup is causing the `.config` directory to be in an odd location. Without knowing more about it I couldn't say.
