### ISSUE TITLE
Variable interpolation for control flow

### ISSUE THREAD

**Issue by a0s** [helm/helm#9146]
Hi! I believe that my question is not new, but i did't find it here.. I want to interpolate variable into control flow. 

I tried this:
```yaml
{{ $tier := "background" }}
{{- if .Values.tiers.$tier.readinessProbe }}
readinessProbe:
{{- end }}
```
result: `bad character U+0024 '$'`

Also i tried this:
```yaml
{{ $tier := "background" }}
{{- if .Values.tiers.{{ $tier }}.readinessProbe }}
readinessProbe:
{{- end }}
```
result: `bad character U+007B '{'`

Also i tried `print` but its always evaluate as `true`, so it doesn't have sense
```yaml
{{ $tier := "background" }}
{{- if print ".Values.tiers." $tier ".readinessProbe" }}
readinessProbe:
{{- end }}
```

So the question is
1) How to interpolate the variable in a right way
2) OR How to convert (or evaluate)`print ".Values.tiers." $tier ".readinessProbe"` to a value
```yaml
{{ $tier := "background" }}
{{- if ( print ".Values.tiers." $tier ".readinessProbe"  | CONVERT_TO_VARIABLE ) }}
readinessProbe:
{{- end }}
```

**Comment by mattfarina** [comment]
The template syntax does not have a specific way of handling that. But, there is the [`get` template function](https://helm.sh/docs/chart_template_guide/function_list/#get). Does that help?

**Comment by sudhakarreddyambati** [comment]
any solution to this?
