### ISSUE TITLE
Helm value file paths cannot contain more than 1 slash lol

### ISSUE THREAD

**Issue by YourPsychiatrist** [helm/helm#9161]
Output of `helm version`:

3.4.1

Issue:

Cannot run `helm template [..] --values a/b/c.yaml` because values that are burried deeper than one folder are just not considered. 

In [loader/loag.go](https://github.com/helm/helm/blob/master/pkg/chart/loader/load.go#L184) you are just skipping filenames that contain more than 1 slash. What on earth? We spent 3 hours debugging this.

Will gladly fix this myself if nobody else wants to take care of it. Would be a good first issue for this repo.

**Comment by mattfarina** [comment]
I'm not sure what caused your problem but helm can handle multiple folders of depth here.

The function `LoadFiles` is used to load content within a chart directory or archive. The values file passed in at the CLI is handled through a different code path.

In the code to run `helm template` you'll find [`runInstall`](https://github.com/helm/helm/blob/ba9cad9379f33d909bff8e85a85c935ab727482b/cmd/helm/template.go#L70) is executed. The `valueOpts` passed in there has a property for the values you pass in via `--values`. Inside `runInstall` the values passed in are [merged with those provided as a default by the chart itself](https://github.com/helm/helm/blob/ba9cad9379f33d909bff8e85a85c935ab727482b/cmd/helm/install.go#L193). [`--values` is mapped to the `ValuesFiles` property](https://github.com/helm/helm/blob/ba9cad9379f33d909bff8e85a85c935ab727482b/cmd/helm/flags.go#L42). That is [processed first](https://github.com/helm/helm/blob/ba9cad9379f33d909bff8e85a85c935ab727482b/pkg/cli/values/options.go#L45-L58) in the order of merging values together. The file is read in using a function named [`readfile`](https://github.com/helm/helm/blob/ba9cad9379f33d909bff8e85a85c935ab727482b/pkg/cli/values/options.go#L108). In this function it first tests for `-` which checks for stdin. It then looks to see if it can use a downloader. These are used to provide custom schemes for downloading (e.g., for things like s3 behind auth). It if fails to find a downloader it uses `ioutil.ReadFile` which can handle subdirectories.

I did try to reproduce the issues you're seeing and was unable to.

**Comment by YourPsychiatrist** [comment]
I will see if I get to investigate further. We ran helm with the `--debug` flag which showed us the code path in the first place. Quickly skimming over the tests for LoadFiles I also couldn't find any tests that contain multiple directory separators but maybe I skimmed it _too quickly_. I might be able to do some further investigation on the weekend.

**Comment by mattfarina** [comment]
`LoadFiles` is what is used for handling chart source. The portion you pointed to deals with handling of sub-charts. This does not have to do with the `values.yaml` files passed in through `--values`.

**Comment by bacongobbler** [comment]
Until this can be reproduced, I am closing this. Please reopen once you can provide a reproducible test case. As @mattfarina pointed out, Helm can handle multiple directory depths and has been able to for a very long time. [We even have test cases](https://github.com/helm/helm/blob/1cd749359c354b622a3016bde8c105d23dba9159/cmd/helm/template_test.go#L41) to verify this.
