### ISSUE TITLE
Helm values not parsed correctly

### ISSUE THREAD

**Issue by CLNRMN** [helm/helm#9162]
We generate random tags in our ci/cd pipeline. Today we had a problem that an image was not deployable. When I looked at the tag, I noticed that a part was missing. I did some tests and found that a certain combination of characters leads to problems. We can't explain it yet, but it seems more like a bug. 

How to reproduce the problem:

Chart.yaml (created with helm create test-chart):
```apiVersion: v2
name: test-chart
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.16.0
```
values.yaml:
```
var_a: 72044e0
var_b: "72044e0"
var_c: 72044e011
var_d: "72044e011"
var_e: 72044e07d2
var_f: "72044e07d2"
var_g: 82h2532
```

templates/test.yaml:
```
# No quotes in values.yaml
var_a: {{ .Values.var_a }}
# Quotes
var_b: {{ .Values.var_b }}

# No quotes in values.yaml
var_c: {{ .Values.var_c }}
# Quotes
var_d: {{ .Values.var_d }}

# No quotes in values.yaml
var_e: {{ .Values.var_e }}
# Quotes
var_f: {{ .Values.var_f }}

# No quotes in values.yaml
var_g: {{ .Values.var_g }}
```

Templating:
```shell
helm template . -f values.yaml 
---
# Source: test-chart/templates/test.yaml
# No quotes in values.yaml
var_a: 72044
# Quotes
var_b: 72044e0

# No quotes in values.yaml
var_c: 7.2044e+15
# Quotes
var_d: 72044e011

# No quotes in values.yaml
var_e: 72044e07d2
# Quotes
var_f: 72044e07d2

# No quotes in values.yaml
var_g: 82h2532
```

As you can see in the example, an unquoted _72044e0_ is templated to _72044_, _72044e011_ towards _7.2044e+15_

Output of `helm version`:

```shell
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}
```

Output of `kubectl version`: - 

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  -

**Comment by bacongobbler** [comment]
Unquoted, values are parsed into their native YAML types. The YAML parser is interpreting “e0” and “e011” as scientific notation. This is intentional behaviour from the YAML spec’s definition. This is also the same reason why “ON” and “NO” are treated as Boolean values.

to fix this, wrap your values in quotes. It will be interpreted as a string.

**Comment by CLNRMN** [comment]
Hi @bacongobbler Thank you for your explanation. Of course this makes sense. We will adjust our templates.
