### ISSUE TITLE
helm chart list truncates long name - unable to see

### ISSUE THREAD

**Issue by dod-ttruong** [helm/helm#9168]
Output of `helm version`:
ersion.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:41:22Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Cloud Provider/Platform (AKS, GKE, Minikube etc.):   AWS

Running `helm chart list` truncates long names:
```
REF                                                             NAME            VERSION         DIGEST  SIZE    CREATED
108814174974.dkr.ecr.us-west-2.amazonaws.com/charts/abc...    ebill-uat       1.0.0           f3b3ac9 5.8 KiB 9 minutes
```

There doesn't seem to be a way to see what the actual names are.

**Comment by bacongobbler** [comment]
`helm chart list` will soon be going away in a future update, therefore fixing this issue by means of removal.

**Comment by chrisfarnham** [comment]
What is the recommended way of listing charts going forward if `helm chart list` will be removed?
