### ISSUE TITLE
Can Helm lint verify input parameters

### ISSUE THREAD

**Issue by iyuenan3** [helm/helm#9172]
Can Helm lint verify input parameters in values-override.yaml?

**Comment by bacongobbler** [comment]
Hi @iyuenan3. I’m not sure I understand the question. Can you please provide a more concrete example to demonstrate the issue/question you are trying to ask?

**Comment by bacongobbler** [comment]
https://github.com/helm/helm/issues/6422

**Comment by iyuenan3** [comment]
Hi @bacongobbler .  I have a values-override.yaml like that:
`
    ippool:
      ipv4:
        start: "10.71.175.202"
        end: "10.71.175.202"
        subnet: "10.71.175.200/29"
`
Obviously, users need to fill in an ip address in the start or end. But if they input a string or some garbled characters, can helm link check these garbled characters and report errors?

**Comment by bacongobbler** [comment]
Yes; see https://helm.sh/docs/topics/charts/#schema-files

**Comment by iyuenan3** [comment]
Oh, I'll checck it, thank you!
