### ISSUE TITLE
Inconsistent uninstall with `--atomic`

### ISSUE THREAD

**Issue by lindhe** [helm/helm#9173]
When investigating #8040 I experimented with killing `helm install` commands, and I think I found a bug with the `--atomic` flag. It seems like an interrupted install sometimes will mark a release as already uninstalled even when it's not. I am able to reproduce it reliably (see section below).

I admit that cancelling an installation like this is a bit brutal, but it's just a `SIGINT` so I think it should be possible to handle it gracefully.

## Reproduce

Create a bash script `setup.sh` with the following content:
```bash
#!/usr/bin/env bash
helm repo add bitnami https://charts.bitnami.com/bitnami
helm install my-release bitnami/nginx --atomic &
HELM_PID=$!
sleep 10
kill -SIGINT ${HELM_PID}
```

Now run the script and inspect the release to see that it does exist (albeit not ready).
```console
$ bash ./setup.sh
$ helm list -a
NAME      	NAMESPACE	REVISION	UPDATED                               	STATUS         	CHART      	APP VERSION
my-release	default  	1       	2020-12-28 13:25:53.20270033 +0100 CET	pending-install	nginx-8.2.3	1.19.6
```

And now I can reproduce it like so:
```console
$ helm uninstall my-release
release "my-release" uninstalled
Error: an error occurred while uninstalling the release. original install error: services "my-release-nginx" not found: uninstall: Release not loaded: my-release: release: not found

```

To my surprise, I was unable to reproduce it by simply running the commands – I had to put it into a script. Could it have something to do with bad forking of Helm, or a lingering lock file or something similar? Just a wild guess...

**EDIT:** I just realized that `Error: an error occurred while uninstalling the release. [...]` was almost certainly printed by the `helm install` process, not `helm uninstall`. This can be verified by running the `helm uninstall` in another terminal than the one with the script.

## System

Output of `helm version`:
```
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-23T02:22:32Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Minikube

**Comment by bacongobbler** [comment]
`--atomic` only ensures that a `helm rollback` is triggered should the installation fail. It does not guarantee that an installation is an atomic transactional update if that's what you're looking for.

**Comment by bacongobbler** [comment]
```
><> helm help install | grep atomic
      --atomic                       if set, the installation process deletes the installation on failure. The --wait flag will be set automatically if --atomic is used
```

**Comment by bacongobbler** [comment]
From what I can tell the steps provided above look like intentional behaviour. An install was interrupted and left in a `pending-install` state. Uninstalling the release reports a few resources that were expected to be installed in the cluster that were not found, but the uninstall succeeded. Those were just warnings.

Can you please clarify the issue you are attempting to imply here?

**Comment by sbose78** [comment]
Thank you for your report @lindhe .

If you had do a `$ helm uninstall my-release`, would you see the following from the interrupted `helm install` ? 

```
Error: an error occurred while uninstalling the release. original install error: services "my-release-nginx" not found: uninstall: Release not loaded: my-release: release: not found
```

I suppose the `$ helm uninstall my-release` did the job correctly but the SIGINT handling wasn't quick enough ?
