### ISSUE TITLE
Helm create accepts uppercase characters

### ISSUE THREAD

**Issue by kaspernielsen** [helm/helm#9179]
> helm create MyChart

Creates a chart called MyChart. The expected behavior would be failing with an "Uppercase characters in chart name not supported" message.

**Comment by wawa0210** [comment]
https://helm.sh/docs/chart_best_practices/conventions/#chart-names

From the official documentation, Chart names must be lower case letters and numbers,The verification logic is missing here

I can try to fix

**Comment by bacongobbler** [comment]
this seems like a regression.

**Comment by technosophos** [comment]
Are uppercase letters not supported? I see where it says that in the documentation, but have never checked to see if that is true. We should definitely render the two consistent.

Release names are lowercase because of the DNS requirements of Kubernetes. I am not sure if this holds true for chart names. (Same with things like non-ASCII letters)

**Comment by sbose78** [comment]
Apart from consistency reasons, does it hurt if we continue to allow uppercase characters ? There is a potential to cause backwards compatibility issues if we stop supporting upper case characters.

Maybe we could just update the docs for now, and reconsider this for v4?

**Comment by kaspernielsen** [comment]
I don't really see any backward compatibility issues. There is no way to install a chart that is created via "helm create UpperCase" unless people afterwards updates the name in Chart.yaml.

**Comment by wawa0210** [comment]
This change should not break backward compatibility. If charts are installed, it will verify that the chart name complies with this rule, but if the charts have already been installed and need to be updated, it will not have any effect.

**Comment by sbose78** [comment]
Sorry I wasn't clear :
If folks have scripts / tooling which do a "helm create UpperCase", those scripts/tools will break :) 

I don't think it's a big issue, though.

**Comment by wawa0210** [comment]
Yes, it is not a serious issue. Perhaps the best way is to correct the document and note the ideal format，the existing format will be depreacted in V4 and  the code will be fixed in V4.

**Comment by bacongobbler** [comment]
We do not have enough consensus to determine if this will break compatibility for some users. The safe option is to hold off on merging any PRs that will enforce this behaviour until Helm 4.
