### ISSUE TITLE
`helm history` table output format has misleading date information

### ISSUE THREAD

**Issue by juniorz** [helm/helm#9186]
Release information seems to store dates in the user's location (as they include a timezone):

```
$ helm history some-release -o yaml
- app_version: 0.0.26
  chart: foo-0.0.26
  description: Upgrade complete
  revision: 20
  status: superseded
  updated: "2020-12-23T14:44:54.781116759Z"
- app_version: 0.0.27
  chart: foo-0.0.27
  description: Upgrade complete
  revision: 21
  status: superseded
  updated: "2020-12-29T16:20:08.327576952Z"
- app_version: 0.0.26
  chart: foo-0.0.26
  description: Rollback to 20
  revision: 22
  status: superseded
  updated: "2020-12-29T17:50:11.373491+01:00"
- app_version: 0.0.25
  chart: foo-0.0.25
  description: Rollback to 19
  revision: 23
  status: superseded
  updated: "2020-12-29T17:59:46.693336+01:00"
- app_version: 0.0.29
  chart: foo-0.0.29
  description: Upgrade complete
  revision: 24
  status: deployed
  updated: "2020-12-30T12:13:48.100739915Z"
```

Note the two rollbacks (performed from an operator's machine) had their times stored in a different timezone than the upgrades (performed from a CI machine). However, due to the use of `time.ANSIC` layout in the `table` output format, the timezone information is lost:

```
$ helm history some-release
REVISION	UPDATED                 	STATUS    	CHART           APP VERSION	DESCRIPTION
20      	Wed Dec 23 14:44:54 2020	superseded	foo-0.0.26	0.0.26     	Upgrade complete
21      	Tue Dec 29 16:20:08 2020	superseded	foo-0.0.27	0.0.27     	Upgrade complete
22      	Tue Dec 29 17:50:11 2020	superseded	foo-0.0.26	0.0.26     	Rollback to 20
23      	Tue Dec 29 17:59:46 2020	superseded	foo-0.0.25	0.0.25     	Rollback to 19
24      	Wed Dec 30 12:13:48 2020	deployed  	foo-0.0.29	0.0.29     	Upgrade complete
```

This output is misleading: it suggests revisions 21 and 22 are ~90 minutes apart when they are in fact only 30m apart.

I would expect `helm history` to (a) display dates consistently in the same timezone and (b) use a layout that contains timezone information. I assume (b) might be a breaking change (unless the `table` output format provides no API compatibility guarantees) and for this reason, I propose displaying dates in the local timezone and keep the `time.ANSIC` layout.

The same happens with the output of `helm status`: the timezone information is lost due to the use of `time.ANSIC`

### Version information

Output of `helm version`: `version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"dirty", GoVersion:"go1.15.5"}`

Output of `kubectl version`: 

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-19T08:38:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.5+k3s2", GitCommit:"746cf4031370f443bf1230272bc79f2f72de2869", GitTreeState:"clean", BuildDate:"2020-12-18T01:41:55Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): EKS

**Comment by sbose78** [comment]
If the timestamps belong to different timezones and the default output doesn't show the timezones, this is definitely a bug, I feel :) 

I like @bacongobbler 's [suggestion](https://github.com/helm/helm/pull/9187#issuecomment-754087080) to use `--format-time` but it feels like a workaround to me since I, as a user could easily be mislead into thinking that I'm reading the timestamps right.

So, I agree, we could do either of the two:

1. Default output ( without `--format-time` should have tz ), Or,
2. Default output should convert all timestamps to the local/cli's timestamp.

(1) would be a breaking change and should be considered for v4
(2) should be do-able in v3.

**Comment by juniorz** [comment]
Thank you for reviewing this so promptly.

The currently proposed fix in #9187 changes the `table` output in a way that is not backward compatible.

The comment in the mentioned PR makes me believe that the current policy is to keep the default output for `table` format unchanged even if it is broken for human users, then introduce a `--time-format` that can fix the confusion IFF the human user opts-in to using a format that displays timezones AND is able to do the timezone math while looking at the list.

I am trying to understand the trade-offs here, and why human users experience is compromised at the expense of not breaking backward compatibility in an output format that is not intended for machine-reading (which is where backward compatibility is critical).

**Comment by sbose78** [comment]
Agreed.

> why human users experience is compromised at the expense of not breaking backward compatibility in an output format that is not intended for machine-reading (which is where backward compatibility is critical).

I do see what you are saying - totally makes sense to me. Even though the table output is meant for humans only, folks would have still have built tooling around it. 

And to be fair, it's not just human users experience, the information when placed in context is inaccurate :(

**Comment by invertigo** [comment]
I feel like adhering to RFC 3339 would pretty much resolve this issue.

**Comment by bacongobbler** [comment]
While I agree that switching to following standard conventions is the intended goal, we must move forward with compatibility in mind. Helm is used in many automated CI systems - introducing something that is perceived as a bug can (and has in the past) broken someone's pipeline.

Helm is downloaded approximately 4 million times per month. That is why we must be cautious when breaking compatibility.

That is why I suggested introducing this in a feature flag for the time being. That way users can opt into this behaviour if they choose, or they can use the incorrect-but-still-working system while they migrate to the new behaviour.

When we start developing Helm 4, we can switch this over to become the default. Until then, we must maintain compatibility.

**Comment by wuchuxiong** [comment]
It seems this issue isn't still fixed 
```
[root@myhost ~]# helm history myapp -n demo
REVISION UPDATED                  STATUS        CHART                  APP VERSION     DESCRIPTION
1        Thu May 25 23:10:56 2023 superseded    myapp-1.24.0+1.2.0.30  2023.11         Install complete
2        Thu May 25 15:30:46 2023 deployed      myapp-1.24.0+1.2.1.35  2023.11         Upgrade complete
```
