### ISSUE TITLE
Override or update values of variables defined in values.yaml in _helpers.tpl

### ISSUE THREAD

**Issue by ramaraosrikakulapu** [helm/helm#9198]
I am using helm3 for defining the kubernetes configuration and I have defined the variable in values.yml like

values.yaml --
```
random-var-name: randome-val
```
As per requirement, I have to override/update the value of ```random-var-name``` variable programmatically in _helpers.tpl file. I tried to follow the technique with assignment operator ```:=```. But looks like, this is only for assigning a value to local variable and can't be used for overriding the value in values.yaml file.

Can anyone suggest how to override the variables defined in values.yaml file

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Minikube

**Comment by bacongobbler** [comment]
Hi @ramaraosrikakulapu. Values that are injected into the template engine cannot be reassigned. Your only course of action is to assign it to a local variable. https://golang.org/pkg/text/template/ provides more context around the template engine used by Helm.

Perhaps you could try explaining your use case. That way others from the community can chime in here and discuss how they handled that situation.

Hope that helps.
