### ISSUE TITLE
Helm uninstall: consider force an uninstall even if it's release record is already marked uninstalled

### ISSUE THREAD

**Issue by mikeshng** [helm/helm#9201]
Using the `--keep-history` flag, in the current Helm uninstall implementation, if the release record is already marked with status uninstalled then another Helm uninstall will only purge the release record and won't proceed with the actual resources delete. See: https://github.com/helm/helm/blob/v3.4.2/pkg/action/uninstall.go#L81-L91

I think Helm should consider forcing the uninstall (delete resources) even if it's release record is already marked uninstalled.

The primary reason is the current Helm uninstall implementation is marking release record as uninstalled even if Helm detected errors during the uninstall process. See: 
https://github.com/helm/helm/blob/v3.4.2/pkg/action/uninstall.go#L122-L127
https://github.com/helm/helm/blob/v3.4.2/pkg/action/uninstall.go#L144-L150

If the initial Helm uninstall contains errors, it will be useful for scripts and other automated tools, to retry the Helm uninstall. But in the current implementation, the retry uninstall only purges the record and doesn't actually do resource cleanup. 

Output of `helm version`:
```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2020-01-14T00:09:19Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
$ kind version
kind v0.7.0 go1.13.6 linux/amd64
```

**Comment by sbose78** [comment]
Thank you @mikeshng for the report!
I do think this would be valuable.

Do we know if there was a specific design thinking associated with the current approach?

**Comment by bacongobbler** [comment]
In order for Helm to uninstall a resource, it must first know that Helm owns that resource via a release record. How would you suggest we infer an orphaned resource is under Helm's ownership and wasn't intentionally left over?

It's important to keep in mind that many users have asked us whether they can delete the release record to "release" Helm's ownership on the resource without uninstalling it. Others still use the `keep` deletion policy to retain resources after a `helm uninstall`. In those cases, a `helm uninstall` forcing deletion of those resources would break that contract.

That is why we've proposed that users should manually inspect and clean up those resources in cases of conflict.

**Comment by bacongobbler** [comment]
It's also worth noting that since this is codified, intentional behaviour, we cannot make any changes to this functionality until at least Helm 4, as doing so would break compatibility for those that rely on its current behaviour.

**Comment by mikeshng** [comment]
@bacongobbler thank youfor your in depth explanation. I think if there is a new `--force` flag (or something similar) to uninstall and not change the current default behaviour would satisfy the use case I described in the original issue.

**Comment by bacongobbler** [comment]
How would —force work with resources with a “keep” policy? It can be argued that —force either means “delete everything regardless of their deletion policy” or “attempt to delete everything, but respect their deletion policy”. I’m concerned there’s a mismatch between the intent of this proposal and the name of the flag. Perhaps a different name would clarify its intent.

Also what happens when —force fails to delete a resource, like when etcd is experiencing network issues or there’s a connection timeout? Is there an expectation that it’ll retry until all resources are deleted?

If possible, I would suggest writing out your thoughts into a Helm Improvement Proposal. That way you can try to garner interest from other community members to weigh in on this topic. More information on the process can be found in the helm/community repository.

**Comment by mikeshng** [comment]
Hi @bacongobbler thank you for your great feedback. I thought about this some more and I think the crux of the problem is actually Helm marking the release record as uninstalled even with errors. So I think forcing the uninstall to do something on an uninstalled record is actually just a workaround for the original problem.

Following your HIP guideline, I made a post to the mailing list https://lists.cncf.io/g/cncf-helm/message/351 to talk about introducing a new flag `--fail-on-error` to helm uninstall as well as a new release status `failed-uninstall`. Thanks.

**Comment by mikeshng** [comment]
@mladedav No I haven't, I was waiting for more feedback. I will try to write something up tomorrow.

**Comment by mikeshng** [comment]
Looks like I didn't get much feedback from notable members/maintainers from the Helm project. I am going to hold off on the HIP until I gather some more feedback.

I read that the Helm project is focusing on maintaining a solid and stable API so extra param such as the one I am proposing are usually not going to be implemented unless there is an overwhelming consensus from the community.
