### ISSUE TITLE
Is there a way to add a label in all the k8s resources (including the resources which are there in the dependency charts) specified in the helm chart 

### ISSUE THREAD

**Issue by abhishekdialpad** [helm/helm#9202]
Wanted to know if there is a helm command to achieve this, or if not do we plan to have this feature in near future?

**Comment by sbose78** [comment]
Not in the way Kustomize does it. However, this is how you would do it today explicitly https://helm.sh/docs/chart_template_guide/named_templates/

**Comment by abhishekdialpad** [comment]
Hi @sbose78 , Thanks for the reply. 
I understand how named templates work. Let me explain to you my use case. Let's suppose our Chart A has 2 chart dependencies (let's suppose grafana and prometheus). Now both grafana and prometheus might have their own k8s resources and other dependencies chart (they also might have their own resources and so on...). Is there a way to add the label in all the resources that are being installed with the chart without explicitly editing the resource file or using include statement in those files. 

Let me know if I missed something. Apologies in advance :)

**Comment by bacongobbler** [comment]
You could attempt to achieve that using the post-renderer: https://helm.sh/docs/topics/advanced/#post-rendering

**Comment by abhishekdialpad** [comment]
Thanks, folks for the suggestions. 
I see that we can use post-renderer with the install, upgrade, and template command. Is there any way to do it before pushing the helm chart to the helm chart repository maybe during `helm dependency update`. Say, we could be using some different CD tool to deploy helm chart which is not using helm commands to deploy applications. In this scenario, it might be handy if we can inject a common label into all the dependencies before packaging the chart.
