### ISSUE TITLE
Installing charts from repository URL with params fails when repository is provided with --repo flag

### ISSUE THREAD

**Issue by topikettunen** [helm/helm#9204]
Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"dirty", GoVersion:"go1.15.5"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T18:49:28Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

I stumbled upon in this issue when setting up a custom Helm chart repository to Azure Storage Account that was intended to be connected with the SAS token, e.g. `https://repo-url.com/charts?<SAS-TOKEN>`

Example output:

```
$ HELM_DEBUG=1 helm install --repo https://repo-url.com/charts?<SAS-TOKEN> test cert-manager
install.go:172: [debug] Original chart version: ""

Indicates that the supposed SAS token went missing somewhere. --> **Error:** failed to fetch https://repo-url.com/charts/cert-manager-v0.16.1.tgz : 409 Public access is not permitted on this storage account.
Indicates that the supposed SAS token went missing somewhere. --> helm.go:81: [debug] failed to fetch hhttps://repo-url.com/charts/cert-manager-v0.16.1.tgz : 409 Public access is not permitted on this storage account.

helm.sh/helm/v3/pkg/getter.(*HTTPGetter).get
	/private/tmp/helm-20201209-72230-gqtdqr/pkg/getter/httpgetter.go:73
helm.sh/helm/v3/pkg/getter.(*HTTPGetter).Get
	/private/tmp/helm-20201209-72230-gqtdqr/pkg/getter/httpgetter.go:41
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo
	/private/tmp/helm-20201209-72230-gqtdqr/pkg/downloader/chart_downloader.go:97
helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart
	/private/tmp/helm-20201209-72230-gqtdqr/pkg/action/install.go:669
main.runInstall
	/private/tmp/helm-20201209-72230-gqtdqr/cmd/helm/install.go:184
main.newInstallCmd.func2
	/private/tmp/helm-20201209-72230-gqtdqr/cmd/helm/install.go:120
github.com/spf13/cobra.(*Command).execute
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
	/private/tmp/helm-20201209-72230-gqtdqr/cmd/helm/helm.go:80
runtime.main
	/usr/local/Cellar/go/1.15.5/libexec/src/runtime/proc.go:204
runtime.goexit
	/usr/local/Cellar/go/1.15.5/libexec/src/runtime/asm_amd64.s:1374
```

## Notes

Installation works when repo is added to Helm before hand with `helm repo add`

**Comment by topikettunen** [comment]
Fix:  https://github.com/helm/helm/pull/9205

Although I need support in testing it since the test repository provided doesn't contain parameters.

**Comment by sbose78** [comment]
That feels like a reasonable expectation to me @topikettunen . Thank you for the fix.

**Comment by bacongobbler** [comment]
Is this really the safest way to inject query metadata into the URL? After `helm repo add`, this SAS token can be queried by `helm repo list`. It would be stored on-disk in Helm's cache. It would also be viewable in a user's bash history. This seems like a HUGE security leak.

I'm really concerned about the security design concerns related to storing secure information in plain text.

**Comment by bacongobbler** [comment]
Re-marking as a proposal as this introduces a new kind of scenario that needs a proper design review to ensure secrets are not unintentionally leaked.

**Comment by topikettunen** [comment]
> Is this really the safest way to inject query metadata into the URL? After `helm repo add`, this SAS token can be queried by `helm repo list`. It would be stored on-disk in Helm's cache. It would also be viewable in a user's bash history. This seems like a HUGE security leak.
> 
> I'm really concerned about the security design concerns related to storing secure information in plain text.

Agree completely on this not being the safest way to inject this data, but unfortunately in this use case (see: https://feedback.azure.com/forums/217298-storage/suggestions/40085299-pass-sas-token-in-authorization-header which is a shame), the only way to do it. Sure I'm speaking more from the Azure point of view on how they utilize these tokens, so cannot say if other solutions have some other options regarding this. But quite a few solutions work the same way.

Sure other options to do the same stuff and this issue can be mitigated with some different solution, but in this case, if the user wants to go this route, isn't it up to the user to grant only limited access to these tokens to mitigate the security issues it might cause?

**Comment by topikettunen** [comment]
@bacongobbler Any updates or thoughts on this?
