### ISSUE TITLE
--atomic --cleanup-on-fail with leftover objects from original release leads to rollback failure

### ISSUE THREAD

**Issue by vadasambar** [helm/helm#9207]
Output of `helm version`: 
`
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}`

Output of `kubectl version`:
`
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-gke.4300", GitCommit:"7ed5ddc0e67cb68296994f0b754cec45450d6a64", GitTreeState:"clean", BuildDate:"2020-10-28T09:23:22Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE

Take any helm chart (I tried it on [helm guestbook](https://github.com/argoproj/argocd-example-apps/tree/master/helm-guestbook)). Follow these steps
1. `helm install guestbook helm-guestbook`
2. Add `nameOverride: foo_bar` in the values.yaml
3. Run `helm upgrade --atomic --cleanup-on-fail guestbook helm-guestbook`
4. Upgrade fails and throws the following error
`Error: UPGRADE FAILED: an error occurred while rolling back the release. original upgrade error: failed to create resource: Service "guestbook-foo_bar" is invalid: metadata.name: Invalid value: "guestbook-foo_bar": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?'): no Service with the name "guestbook-helm-guestbook" found`

To be specific, `no Service with the name "guestbook-helm-guestbook" found` is the error thrown when rollback is attempted. This is because, when the upgrade fails, resources from the older release were still present and when helm attempts to rollback, it comes to this piece of code
https://github.com/helm/helm/blob/5d08a0d00e4f0d31d6db55e71bccbcd665366c9a/pkg/kube/client.go#L215

Helm expects that the objects from the older release would be present in the failed release but they aren't which leads to the above error. We could modify the code slightly to `continue` if it comes across a scenario where the objects from the older release are present but are not a part of the failed release. Helm can safely ignore them. However, since this change would be in a generic piece of code which is also used for upgrade, I don't have the complete idea of its impact on other pieces of code. 

Another thing we could do is, add some documentation around this scenario so the user is aware of what's happening in case they run into the above issue because the error is not very helpful (since the object from the old release exists)

**Comment by bacongobbler** [comment]
Hi @vadasambar. Can you please test and verify this is still an issue with a newer version of Helm? Helm v3.5.0 is the latest release. I do recall there was some patches to the upgrade/rollback resource resolution recently. It is possible that this behaviour has already been fixed in a more recent release.

**Comment by vadasambar** [comment]
Hey @bacongobbler , sorry for the late reply. Ran into the same issue for both master and `3.5.0`. 

With `master` (6c010ec6)
```
Error: UPGRADE FAILED: an error occurred while rolling back the release. original upgrade error: failed to create resource: Service "guestbook-foo_bar" is invalid: metadata.name: Invalid value: "guestbook-foo_bar": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?'): no Service with the name "guestbook-helm-guestbook" found
```

With [3.5.0](https://github.com/helm/helm/releases/tag/v3.5.0) commit ID, 
```
Error: UPGRADE FAILED: an error occurred while rolling back the release. original upgrade error: failed to create resource: Service "guestbook-foo_bar" is invalid: metadata.name: Invalid value: "guestbook-foo_bar": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?'): no Service with the name "guestbook-helm-guestbook" found
```

With the PR fix
```
Error: UPGRADE FAILED: release guestbook failed, and has been rolled back due to atomic being set: failed to create resource: Service "guestbook-foo_bar" is invalid: metadata.name: Invalid value: "guestbook-foo_bar": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')
```
