### ISSUE TITLE
Feature: Support for optional chaining

### ISSUE THREAD

**Issue by thernstig** [helm/helm#9209]
It would be beautiful if Helm could support optional chaining. Similar to JavaScript in latest standard ECMAScript 2020. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

It would basically look like this:

```
spec:
  type: {{ .Values.service?.type | default "ClusterIP" }}
```

If service is not defined, it would short-circuit to undefined/false and thus default to "ClusterIP".

This could be used in other cases, such as:

```
spec:
  {{- if .Values.global?.internalIPFamily }}
  ipFamily: {{ .Values.global.internalIPFamily }}
  {{- end }}
```

It solves a few things.
1. `default` not working when parent values does not exist in a chain, giving errors, see https://github.com/helm/helm/issues/8026.
2. It would be able to get rid of the, in my opinion, not great best practice for nested or flat values, see https://helm.sh/docs/chart_best_practices/values/#flat-or-nested-values. Optional chaining would instead still make the code more readable (one-liner) not caring about value depth. It would also in my opinion make it easier to read YAML files with the nested structure, clearly separating levels, than to use camelCase.

**Comment by mattfarina** [comment]
@thernstig let me say, this is a great idea.

This part of the templates is something handled by [text/template in the Go standard library](https://golang.org/pkg/text/template/). It isn't something Helm can add on top of that. The feature request would need to be filed over on the [Go project](https://github.com/golang/go).

**Comment by thernstig** [comment]
Thanks @mattfarina, I submitted https://github.com/golang/go/issues/43608. Should we close this then, or keep it open for tracking purposes? If the feature is implemented, documentation for Helm should be updated.

**Comment by thernstig** [comment]
The unstale bot should skip to automatically close threads that has X amounts of upvotes 😆

**Comment by AndiDog** [comment]
For whoever reads about this missing feature later:

```
{{- if .Values.global.cluster.vpcId }}
```

may give `nil pointer evaluating interface {}.vpcId`.

**The solution is to use parentheses ([explanation on StackOverflow](https://stackoverflow.com/a/68807258/245706)):**

```
{{- if (.Values.global.cluster).vpcId }}
```

You can use [multiple parentheses](https://xkcd.com/297/), e.g. if `global` in the above example could also be `nil`.
