### ISSUE TITLE
Windows PowerShell - Helm commands hanging

### ISSUE THREAD

**Issue by whgibbo** [helm/helm#9210]
Output of `helm version`: 
**version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}**

Output of `kubectl version`:
**Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}**

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
**Windows 10 - 1909
Running Docker Desktop 2.3.0.5**

Helm was installed using https://chocolatey.org/packages/kubernetes-helm.  Using a Windows Powershell I having been using the helm commands, but every now and then they do not complete.  It just sits there.

I open another powershell command and sometimes it will work and other times again it will just sit there.. never returning.

Any thoughts or logs I should be looking at ?

Thanks

**Comment by bacongobbler** [comment]
Hi @whgibbo. I'd first start by using both the `--debug` and `-v 10` for more informative logging. The first enables debug logging from Helm's end. The latter adds verbose logging from the underlying kubernetes client connection.
