### ISSUE TITLE
helm3 repo list: returns error if no repos configured

### ISSUE THREAD

**Issue by uniqueck** [helm/helm#9215]
Output of `helm version`: version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}

The command helm repo list returns an error, if no repositories are configured. It would be nicer if it return an empty list and based on output format equal to table a warning message.

This would it make easier to use helm repo list command to remove all configured helm repos without to analyze the error message.

**Comment by bacongobbler** [comment]
Due to Helm's [backwards compatibility guarantees](https://github.com/helm/helm/blob/master/CONTRIBUTING.md#semantic-versioning), this is not something that we can change for Helm 3. We can consider this for Helm 4 however.

**Comment by uniqueck** [comment]
That's ok for me.

**Comment by uniqueck** [comment]
bump up
