### ISSUE TITLE
helm exits without comment, when ~/.config exists but is not accessible

### ISSUE THREAD

**Issue by piskernik** [helm/helm#9216]
If helm does not have appropriate right to access `~/.config` it exits without comment. (I had a previous npm installation, which generated the .config, but only with root access).

Proposal:
`helm.go:65: [debug]` should output in any case, that permission is not granted (not only when debug flag is set). `helm` can obviously not start, if the permission is not granted.

**Comment by bacongobbler** [comment]
Thanks for the report. Have you looked into the feasibility of this fix?

**Comment by piskernik** [comment]
Instead of `debug(...)` in line 65 helm should at least call `warning(...)` or `log.Fatal(...)`. I don't know, which one is more appropriate.

**Comment by bacongobbler** [comment]
Some commands like `helm help` do not require access to `~/.config` at all to work. Changing it from `debug` to `log.Fatal` would cause those commands to fail. However changing it to a warning message might be a feasible solution.

Feel like working on a patch?

**Comment by wawa0210** [comment]
Is anyone following up on this issue, if not, I can try to patch
