### ISSUE TITLE
Add ChartLoader for golang 1.16 fs.FS

### ISSUE THREAD

**Issue by howardjohn** [helm/helm#9217]
With the new fs.FS interface in golang 1.16, it would be useful to have an implementation of ChartLoader accepting this interface. The primary use case is to `//go:embed` a helm chart and then use helm as a library to render the charts.

The primary alternative is to read into BufferedFile and then call `LoadFiles(files []*BufferedFile)`, but this is tedious and I think results in multiple copies of all the files

**Comment by bacongobbler** [comment]
Thanks for raising this to our attention. Have you looked into the feasibility of this request? Happy to look at PRs.

**Comment by howardjohn** [comment]
I think its pretty easy, you can basically use the same function that takes a directory as a string and replace os.WalkDir with fs.WalkDir. The same implementation can be shared as well by requiring users to wrap the directory string with `os.DirFS(directoryString)` which returns an equivalent fs.FS, this could have a wrapper of course to preserve the same interface.

I put together a pretty simple one at https://github.com/istio/istio/pull/29963/files#diff-0022c251d601f64fd41b9ba32d3586495712d615425f3ecf7d328e372a85782eR93, but that is using BufferedFile.

I think the main pain will be the interfaces are only around in golang 1.16, so you would probably need to make some build tag craziness.

**Comment by nikpivkin** [comment]
I'm also interested in this feature, but I think it's not possible to implement it yet as `io.FS` doesn't support SymlinkFS, but a [proposal](https://github.com/golang/go/issues/49580) to add SymlinkFS has been accepted and is in development.
