### ISSUE TITLE
"-v, --v Level" flags have disappeared from "helm --help"

### ISSUE THREAD

**Issue by sraillard** [helm/helm#9219]
Output of `helm version`:
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.5+k3s2", GitCommit:"746cf4031370f443bf1230272bc79f2f72de2869", GitTreeState:"clean", BuildDate:"2020-12-18T01:41:55Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.5+k3s2", GitCommit:"746cf4031370f443bf1230272bc79f2f72de2869", GitTreeState:"clean", BuildDate:"2020-12-18T01:41:55Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
k3s v1.19.5+k3s2

**Issue:**

When typing `helm --help`, older version like 3.1.3 shows in the "Flags:" section the verbose level flag:
```
  -v, --v Level                          number for the log level verbosity
```
But, in last version 3.4.2, this flag still work but doesn't appear anymore in the `helm --help` output.

**Comment by sraillard** [comment]
Also, the option `--insecure-skip-tls-verify` isn't listed for upgrade `helm upgrade --help` and it is supported.

**Comment by bacongobbler** [comment]
This was accepted and introduced in https://github.com/helm/helm/pull/8067.

**Comment by sraillard** [comment]
Ok, I have just look like at #8067 and I clearly disagree with removing the debug flags from the command line.
Helm doesn't have so much technical documentation, so I don't see the point to remove flags because they are not developers friendly.

**Comment by sraillard** [comment]
Is the discussion is closed about showing all supported flags by helm? Honestly from a Linux sysadmin point of view, this is kind of disturbing!

**Comment by sraillard** [comment]
The only documentation about the -v (and not even mentioning the other flags) is at the end of the FAQ page (https://helm.sh/docs/faq/): 
![image](https://user-images.githubusercontent.com/32952986/104517059-af388f00-55f5-11eb-8be9-3129b57116ec.png)
I would not say this is easy to find and that is providing a lot of help.

**Comment by bacongobbler** [comment]
Enahancements to document this flag would be acceptable. Please feel free to submit suggestions in the form of a PR.
