### ISSUE TITLE
Using helm in disconnected envs

### ISSUE THREAD

**Issue by jax79sg** [helm/helm#9223]
Hi, how can i use Helm in a totally disconnected environment? I tried to find resources for it for Helm v3 but couldn't find any. Or should i use helm to install in a connected env and then analyse the svc,deployment...etc on Kubernetes and write my own yaml after that?

Output of `helm version`: v3

Output of `kubectl version`: v1.19

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  Vanilla Kubernetes

**Comment by mattfarina** [comment]
@jax79sg That's a good question. Helm will working in disconnected environments but there are some things you'll need to do.

- If you are using a helm repository (`helm repo` based commands) then the repository will need to be available in that environment. If you aren't using a helm repository you can use a chart source or chart archive locally.
- The charts you are using need to either A) have their image point to those available in that environment or B) you need to override the images (pass in a custom location) to point to a location available in the environment. This may mean copying the images from an outside location to one in the disconnected environment.

Does that help?

**Comment by sbose78** [comment]
> you need to override the images (pass in a custom location) to point to a location available in the environment.

I've been exploring this for a while as well and would like to brainstorm:

There are two options for override:

1. values.yaml : Though this would make users be able to deploy almost anything if the image is modify-able.
2. Would we encourage a pattern where the manifests get overwritten with newer image references ?
