### ISSUE TITLE
provide a way to sanitize / check  helm strvals options (e.g. --set=" image.tag=123")

### ISSUE THREAD

**Issue by dnozay** [helm/helm#9224]
(currently using helm 3.3.4)

# problem

```
helm install [...] --set=" image.tag=123"
``` 

```
helm install [...] --set="image .tag=123"
``` 
we all make typos ...

# current behavior

It is very unlikely that a chart will consume a `<space>image` or `image<space>` as a template variable.
So the chart value provided on the command line gets silently ignored.

# possible solutions

- we could provide an error, similar to other parsing errors `--set="a.=1"`

- we could print warnings

- we could have a checker that ensures all keys are used (pretty much like go compiler checks declared but unused variables)

**Comment by sbose78** [comment]
I would say, we should definitely error out, I don't think that would impact backward compatibility at all.

**Comment by bacongobbler** [comment]
I am concerned there may be backwards compatibility concerns here with keys which are padded with spaces, which is considered valid YAML according to the specification. For example, this is valid:

```
"my foo": "bar"
```

I believe those values can be set via `--set "my\ foo=bar"`, but we still need to keep that use case in mind.

As long as we can still set those types of values in compliance with https://helm.sh/docs/intro/using_helm/#the-format-and-limitations-of---set, any improvements in this area is most welcome. Please feel free to submit patches.

**Comment by bacongobbler** [comment]
It would appear that this is considered valid YAML:

```yaml
a:
    "": 1
```

The JSON equivalent is

```json
{
  "a": {
    "": 1
  }
}
```

in other words, `--set "a.=1" could be considered valid syntax.

**Comment by dnozay** [comment]
anyone to review? @bacongobbler is there something you could do to get more visibility?
