### ISSUE TITLE
SecurityContextConstraint fails validation in chart due to missing field 'priority'

### ISSUE THREAD

**Issue by daisleyj** [helm/helm#9227]
**Output of `helm version`:** version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}

**Output of `kubectl version`:** Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2-0-g52c56ce", GitCommit:"3f6a83f", GitTreeState:"clean", BuildDate:"2020-10-01T23:24:40Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.3+616db59", GitCommit:"616db59", GitTreeState:"clean", BuildDate:"2020-11-26T04:52:21Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS

When deploying a helm chart which includes the creation of a security context constraint, the chart fails to deploy and returns the message:

```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(SecurityContextConstraints): missing required field "priority" in com.github.openshift.api.security.v1.SecurityContextConstraints
```
However the chart template does include the `priority` field that is mentioned in the error.

Chart Template:
```apiVersion: v1
kind: ServiceAccount
metadata:
  name: spm-efs-sa
  namespace: spm
  annotations: 
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-17" 
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
---
apiVersion: v1
kind: SecurityContextConstraints
metadata:
  name: sg-anyuid
  namespace: spm
  annotations: 
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-16" 
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities:
- MKNOD
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:spm:spm-efs-sa
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities: []
defaultAddCapabilities: []
fsGroup:
  type: RunAsAny
groups:
- system:cluster-admins
```

I have tested the same yaml using `oc create -f` and it validates and deploys correctly.

**Comment by bacongobbler** [comment]
For context, these validation errors are propagated through the Kubernetes validation APIs. Helm takes the rendered manifests and validates them against Kubernetes' manifest schemas. So any validation errors are coming directly from upstream.

Looking at https://docs.openshift.com/online/pro/rest_api/security_openshift_io/securitycontextconstraints-security-openshift-io-v1.html, it would appear that the `priority` field MUST contain an integer. `null` is an invalid value.

In the documentation for the `priority` field, "An unset value is considered a 0 priority" (which is odd considering it's a mandatory field...), so perhaps try setting it to zero instead of `null`.

**Comment by bacongobbler** [comment]
As to why `oc create -f` works while `helm install` doesn't... I'm not sure. Based on the documentation it can be assumed that `oc create -f` provides a default value if none was set by the user, whereas Helm takes the literal value.

**Comment by sbose78** [comment]
@daisleyj Could you try `oc create -f` with the flag `--validate` set to `true` to see if that blocks creation of resources ? If yes, we can safely assume that the behaviour is consistent.

**Comment by daisleyj** [comment]
Thank you @bacongobbler 

Looks like it is a required value but what confused me was when you do `oc get scc -o wide` to review the built in SCC's in Openshift it shows `priority` as being set to `<no value>` for all but one of them and if you output the yaml it shows `priority: null` 

```
[john@oc7055273428 containerised-spm]$ oc get scc -owide
NAME               PRIV    CAPS                                                                                              SELINUX     RUNASUSER          FSGROUP     SUPGROUP    PRIORITY     READONLYROOTFS   VOLUMES
anyuid             false   <no value>                                                                                        MustRunAs   RunAsAny           RunAsAny    RunAsAny    10           false            [configMap downwardAPI emptyDir persistentVolumeClaim projected secret]
hostaccess         false   <no value>                                                                                        MustRunAs   MustRunAsRange     MustRunAs   RunAsAny    <no value>   false            [configMap downwardAPI emptyDir hostPath persistentVolumeClaim projected secret]
hostmount-anyuid   false   <no value>                                                                                        MustRunAs   RunAsAny           RunAsAny    RunAsAny    <no value>   false            [configMap downwardAPI emptyDir hostPath nfs persistentVolumeClaim projected secret]
hostnetwork        false   <no value>                                                                                        MustRunAs   MustRunAsRange     MustRunAs   MustRunAs   <no value>   false            [configMap downwardAPI emptyDir persistentVolumeClaim projected secret]
node-exporter      true    <no value>                                                                                        RunAsAny    RunAsAny           RunAsAny    RunAsAny    <no value>   false            [*]
nonroot            false   <no value>                                                                                        MustRunAs   MustRunAsNonRoot   RunAsAny    RunAsAny    <no value>   false            [configMap downwardAPI emptyDir persistentVolumeClaim projected secret]
privileged         true    [*]                                                                                               RunAsAny    RunAsAny           RunAsAny    RunAsAny    <no value>   false            [*]
restricted         false   <no value>                                                                                        MustRunAs   MustRunAsRange     MustRunAs   RunAsAny    <no value>   false            [configMap downwardAPI emptyDir persistentVolumeClaim projected secret]
``` 

I used a built in scc definition as a template for creating my own!! Perhaps I should have been less lazy and wrote it all myself :man_technologist: 

Adding an integer value for `priority` rather than null fixes the issue :+1: 

@sbose78 Forcing oc to validate by adding `--validate=true` to the oc create statement does indeed return the same error.

Thank you 

:smile:
