### ISSUE TITLE
helm package behavior difference between helm2.16.0 and helm3.2.4 (permission 755 vs 644)

### ISSUE THREAD

**Issue by ycui** [helm/helm#9238]
Observed file permission differences in the packaged charts from 2.16.0 vs 3.2.4

https://github.com/helm/helm/blob/v3.2.4/pkg/chartutil/save.go#L232
In helm 3.2.4, the permission is 644.
 
https://github.com/helm/helm/blob/v2.16.0/pkg/chartutil/save.go#L216
In helm 2.16.0, the permission is 755.
 
This has caused some files which are originally executable to be non-executable after the helm package process, should there be an option to preserve the original file permissions instead of using hardcoded permissions of 644 or 755 ?

Thanks.

**Comment by ycui** [comment]
@adamreese 

https://github.com/helm/helm/commit/b6fdd8783bff827ef0598eb709a30492fbafeeec

**Comment by technosophos** [comment]
A security audit prompted that change. You can read the audit here: https://github.com/helm/community/tree/master/security-audit

**Comment by ycui** [comment]
re-opening.... just wondering would you guys consider a PR for preserving the permissions with helm package CLI flag (instead of hardcode 644) ? this way the permission security would be up to the user instead of helm.
