### ISSUE TITLE
Trouble building 3.5.0

### ISSUE THREAD

**Issue by yurrriq** [helm/helm#9239]
I'm trying to update [the Nix package](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/cluster/helm/default.nix), which uses [`buildGoModule`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/go-modules/generic/default.nix), from 3.4.2 (builds fine) to 3.5.0, and have run into this error. I don't have time to dig into it just now, so I figured I'd at least report it.

```
go: downloading github.com/xeipuuv/gojsonpointer v0.0.0-20180127040702-4e3ac2762d5f
  helm.sh/helm/v3/cmd/helm imports
       k8s.io/client-go/plugin/pkg/client/auth imports
        k8s.io/client-go/plugin/pkg/client/auth/azure imports
          github.com/Azure/go-autorest/autorest imports
          github.com/Azure/go-autorest: module github.com/Azure/go-autorest@latest found (v14.2.0+incompatible, replaced by github.com/Azure/go-autorest@v13.3.2+incompatible), but does not contain package github.com/Azure/go-autorest
```

**Comment by Chili-Man** [comment]
I ran into this issue yesterday trying to update the package; I posted an issue about this in the Nix discourse site: https://discourse.nixos.org/t/unable-to-build-helm-3-5-0/10996

**Comment by bacongobbler** [comment]
How odd. Looking at the release history from the master branch, CI seems to be building the package just fine: https://github.com/helm/helm/commits/master

Let us know what you find out.

**Comment by Chili-Man** [comment]
Indeed; I'm able to build it locally just fine using the provided Makefile. The only way I was able to reproduce that error outside of Nix, was by running `go mod tidy`. I'm investigating how Nix's **buildGoModule** works to see if I can debug it better.

**Comment by yurrriq** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/112314
