### ISSUE TITLE
Helm Uninstall Deletion Protection with Pre-Delete Hooks

### ISSUE THREAD

**Issue by deweya** [helm/helm#9241]
I'm working with a client interested in adding a "deletion protection" feature in their Helm chart. On `helm uninstall`, the workflow would be:

```
if <some condition>:
  Do not uninstall. Reset Helm release status to 'deployed'
else:
  Uninstall the release
```

We tried implementing this with a `pre-delete` hook, where the hook would exit 1 in attempt to fail the deletion if necessary, but this instead keeps the release stuck in the `uninstalling` state and cannot be upgraded. I thought about `helm rollback` if the release is stuck, but this won't work if there's only 1 revision (the one stuck uninstalling).

Is there a way to cancel a Helm uninstall, whether it be through a hook or some other means? If not, can the Helm release status be reverted to `deployed` if a pre-delete hook fails?

**Comment by ssheth1** [comment]
This will be beneficial where pre-delete hook can verify if the delete conditions are met then attempt delete, else reject delete.

**Comment by ertanhasani** [comment]
+1. I think it would really be beneficial if there would be an annotation for something like `/hook-stop-on-fail` so if the hook is `pre-...` and it fails, it would stop whatever command user has typed.

**Comment by sprenge** [comment]
Any progress on this issue ?  I will encounter the same problem because I want to delete external resources at un-install.  The problem comes if they cannot be deleted because dependencies have to be removed from the external resources.

**Comment by bacongobbler** [comment]
No progress has been made as far as I'm aware, however I will drop this link here if someone wants to follow up and propose ideas:

https://github.com/helm/helm/blob/main/CONTRIBUTING.md#proposing-an-idea
