### ISSUE TITLE
.Release.IsInstall not set properly during "helm test" of first revision when displaying NOTES

### ISSUE THREAD

**Issue by stevelipinski** [helm/helm#9242]
Output of `helm version`:

    version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}

Output of `kubectl version`:

    Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-23T02:22:32Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

    Kubernetes - non-cloud, Nokia platform

When using helm to provide any kind of one-time credentials, generated by install, using the NOTES implementation in helm2 was a nice way to convey those generated credentials to the user in a one-time fashion at install.  However, now with helm3, we have noticed that helm test outputs the NOTES - which is different behavior from helm2.  This would not be an issue, however, the .Release.IsInstall is not properly honored by a helm test immediately performed after helm install (before a release upgrade).

This causes our credentials to be dumped to the screen again on helm test, undesirably.

So, it seems that the .Release.IsInstall is more equivalent to a .Release.IsFirstRevision rather than IsInstall, which is unexpected behavior.  Per the helm docs:

> Release.IsInstall: This is set to true if the current operation is an install.

However, helm test renders NOTES content wrapped in `{{ if .Release.IsInstall }} .. {{ end }}`.  A helm test operation is not an install operation, and thus one expects the .Release.IsInstall to be False.

Here is a snippet from our NOTES:
```
{{- if .Release.IsInstall }}
Initial Passwords
=================
The following are the initial built-in passwords for the database.
They are only displayed this one-time.
  {{- printf " %-15s | %s" "User" "Password" | nindent 0 }}
  {{- printf "-----------------|-----------------------------------------------------------------" | nindent 0 }}
...
```

Output from helm test on revision 1:

    Initial Passwords
    =================
    The following are the initial built-in passwords for the database.
    They are only displayed this one-time.
    
     User            | Password
    -----------------|-----------------------------------------------------------------
     metrics-user    | kC8Y4ekxVlLDqlWE4donlXe2ZgYol0KNtblAYCbmuyUHxtta857ZrNVnft7BeR2f
    ...

After an upgrade to revision 2, helm test no longer shows the above content.

**Comment by bacongobbler** [comment]
Good catch. Feel like contributing a patch to fix this behaviour?

**Comment by stevelipinski** [comment]
> Good catch. Feel like contributing a patch to fix this behaviour?
Would love to, but unfortunately I am not equipped - I don't know Go beyond gotpl.

If I find some cycles, I can give it a try, but it won't be pretty :).  
However, if someone else (who is a more adept in Go) sees this issue and can fix quickly - by all means.

**Comment by stevelipinski** [comment]
I think this is still needed

**Comment by stevelipinski** [comment]
Keep alive

**Comment by itay1213141** [comment]
Im also trying to use .Release.IsInstall but it outputs true when running helm template, i assume its the same problem. anyone has any idea?
