### ISSUE TITLE
Usage of --repo and --version flag ignored when a local folder is named as the chart in current working dir

### ISSUE THREAD

**Issue by consideRatio** [helm/helm#9244]
If your current working directory contains a folder named `my-chart`, and you do `helm install my-release --repo <url> my-chart --version 1.2.3` the --version flag and --repo flags are silently ignored, because helm will tunnel vision on the existence of a local folder.

I consider this a undesired behaviour, where the desired behavior would be to not even try to look for a local chart with --repo passed.

The --repo flag discussion aside, I also think its undesired to not even emit a warning that --version is ignored if a local chart is passed.

---

Output of `helm version`: 3.5.0
Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.13-gke.2600", GitCommit:"fc4bf3b03703b51c48ba123e8abc53b3051ba8a7", GitTreeState:"clean", BuildDate:"2020-11-11T09:20:10Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

# Reproduction

```
git clone https://github.com/jupyterhub/zero-to-jupyterhub-k8s
cd zero-to-jupyterhub-k8s

echo "This command is run from a folder, with a chart in the folder named jupyterhub"
helm template my-release --repo https://jupyterhub.github.io/helm-chart/ jupyterhub --version 1.0.0 | grep -m1 chart

echo "This command is run from a folder, without a chart in the folder named jupyterhub"
cd doc
helm template my-release --repo https://jupyterhub.github.io/helm-chart/ jupyterhub --version 1.0.0 | grep -m1 chart

helm version
```

## Output

```
This command is run from a folder, with a chart in the folder named jupyterhub
    chart: jupyterhub-0.0.1-set.by.chartpress
This command is run from a folder, without a chart in the folder named jupyterhub
    chart: jupyterhub-1.0.0
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

**Comment by bacongobbler** [comment]
This is intentional. `--version` and `--repo` are only used when fetching a remote chart. They are short-circuited when a local folder is declared. The local folder is always preferred over a remote chart lookup to prevent accidental lookups.

That being said, we certainly could output a warning when those flags are ignored. Please feel free to contribute a patch to do so.

**Comment by consideRatio** [comment]
Providing a warning makes sense.

**Comment by consideRatio** [comment]
I added steps to reproduce the issue quickly - still a relevant issue.

**Comment by consideRatio** [comment]
Still relevant and an well described issue.
