### ISSUE TITLE
Helm vs breaking change migration

### ISSUE THREAD

**Issue by bozaro** [helm/helm#9245]
I got strange issue and can't find good solution.

I have two chart versions:
 - 0.1:
   - Deployment with gRPC service listen port 8443
   - Service with `ClusterIP` map port 8443 to 443
 - 0.2:
   - Deployment with gRPC service listen port 443
   - Service without `ClusterIP` (headless) for port 443
Service used outside chart by name.
 
In this way there are no way to create migration without downtime: `ClusterIP` field is immutable and I must recreate Service.

On upgrade 0.1 -> 0.2 I have:
 - Deployment is upgraded successfully and listen port 443;
 - Service upgrade failed and try to use container port 8443.
As result I have downtime until somebody resolve broken update.

In this situation I want to have way to fail on 0.1 -> 0.2 upgrade with some human friendly message after chart render, but before some changes happens.

**Comment by bacongobbler** [comment]
Your assumption is correct. There is no way to upgrade from 0.1 to 0.2 in this case, as Kubernetes prevents upgrades to immutable fields such as the `clusterIP` field in a Service.

Your only recourse is to delete the service prior to the upgrade.

> In this situation I want to have way to fail on 0.1 -> 0.2 upgrade with some human friendly message after chart render, but before some changes happens.

You could use the `fail` function to fail early.

https://helm.sh/docs/chart_template_guide/function_list/#fail

**Comment by bozaro** [comment]
I can't use `fail` function, because I can't get previously installed version number.
So I can't tell upgrade `0.1` -> `0.2` from upgrade `0.2` -> `0.2`.

**Comment by bozaro** [comment]
For your information: `--force` flag can't apply `clusterIP` chage by recreate `Service`.
