### ISSUE TITLE
helm 3  upgrading vault chart fails : Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. 

### ISSUE THREAD

**Issue by muralindia** [helm/helm#9247]
Output of `helm version`: v3.4.2

Output of `kubectl version`: v1.20.1

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AWS v1.18.9-eks-d1db3c

I am trying to upgrade vault v1.5.4 to latest using helm upgrade but it fails.

 $ helm upgrade vault154   hashicorp/vault -n vaultawsmt -f override-values.yml 

Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. **Unable to continue with update: ClusterRoleBinding "vault154-server-binding" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "vault154";** annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "vaultawsmt"

**Comment by bacongobbler** [comment]
As the error suggests, your cluster already contains a ClusterRoleBinding with the same name. Helm cannot "adopt" an existing resource into a release, so it fails during the installation.
