### ISSUE TITLE
[Apple Silicon]Helm prints an error: "getCPUInfo for OS darwin: not implemented"

### ISSUE THREAD

**Issue by kuzaxak** [helm/helm#9248]
Output of `helm version`:
```
helm version
ERRO[0000] failure getting variant                       error="getCPUInfo for OS darwin: not implemented"
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"dirty", GoVersion:"go1.16beta1"}
```
Output of `kubectl version`:
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Local MacOs ARM (Apple Silicone)

For each command helm prints an error:
`ERRO[0000] failure getting variant                       error="getCPUInfo for OS darwin: not implemented"`

It broke `helmfile` but generally `helm template` and other commands works fine.

**Comment by bacongobbler** [comment]
https://github.com/helm/helm/pull/9076
