### ISSUE TITLE
How to upgrade CRD-based resources without them all being immediately shut down?

### ISSUE THREAD

**Issue by barankyle** [helm/helm#9249]
I've got a question about using `helm upgrade` with custom resources, namely if there's a way to run upgrade without CRD-based pods getting shut down straight away.

We're using Agones to manage gameserver fleets in K8s. Agones' Helm chart defines various custom resources, such as 'gameserver', 'fleet', etc. We install this Chart once before any other charts are being applied. In brief, Agones manages tagged gameservers/a fleet of gameservers, doing things like keeping X number of gameservers ready for provisioning, removing gameservers that have been shut down, etc.

Our project has a separate Chart for all of its various servers. One of the server types is gameserver, which starts up our backend server in gameserver mode and adds labels to those pods so that Agones can manage them.

We run `helm upgrade` whenever a new version of the codebase is committed to our dev branch, applying a new tag of our Docker image to all of the front- and backend servers. What should happen is that Agones incrementally spins up a new gameserver with the new codebase and shuts down an old gameserver when the new one is ready, and keep doing that until all gameservers have been replaced. Any gameservers that are in the 'Allocated' state are left as-is until they are empty of users and shut down as normal.

What's happening in practice is that, as soon as `helm upgrade` goes into effect, all of the gameservers, including ones that are Allocated, are immediately shut down, and only ~2 minutes later are the new ones finished spinning up and ready. This leaves us with a short window of time where no one can really use our platform since there are no gameservers available. Booting users on active gameservers is also pretty bad.

This is definitely something to do with `helm upgrade`. I've tried doing kubectl apply -f on the 'fleet' configuration file in our Helm chart (which, again, does not contain any CRDs itself, just uses existing CRDs), and I do not see this issue. The gameservers are gradually replaced as expected, and active gameservers are left alone.

I've [read](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/) how `helm upgrade` doesn't work on CRDs. That page seems to be suggesting that `helm upgrade` only does not work for CRD definitions, but maybe I'm interpreting it wrong. Is it expected that `helm upgrade` wipes all existing pods made from a CRD straight off the bat?

**Comment by bacongobbler** [comment]
There is a well-written writeup on CRDs and how upgrades to a CRD can cause unintentional cascading failures to the cluster in the helm/community repo. I would highly suggest giving that a read.

https://github.com/helm/community/pull/138

**Comment by bacongobbler** [comment]
> Is it expected that `helm upgrade` wipes all existing pods made from a CRD straight off the bat?

The short answer is yes. An upgrade to a CRD causes all resources relying on that CRD to be deleted. That is Kubernetes' expected behaviour when upgrading a CRD.

**Comment by barankyle** [comment]
But I'm not upgrading the CRD itself. I'm upgrading a chart that uses a CRD.

**Comment by barankyle** [comment]
It looks like my problem was caused by a service dependency issue.

Our gameservers connect to a redis cluster inside our K8s cluster. Our Helm chart installed redis, and was reinstalling it on every helm upgrade. I think the gameservers were erroring out due to the lost connection. I made redis a separate installation, and Agones is behaving as expected.
