### ISSUE TITLE
Error installing large charts

### ISSUE THREAD

**Issue by neilmcgibbon** [helm/helm#9251]
### Encountered Error
After upgrading Helm, when I attempt to install a large chart (~400 resources), Helm exits with an error. Before the upgrade, an install on the same chart worked without errors. The new error is: (Redacted full hostname, namespace and deployment name):

```
Error: rendered manifests contain a resource that already exists. 
Unable to continue with install: could not get information about the resource: 
Get "https://<redacted>.eks.amazonaws.com/apis/apps/v1/namespaces/<redacted>/deployments/<redacted>": 
dial tcp: lookup <redacted>.eks.amazonaws.com: no such host
```

This error happens after around ~250 _successful_ calls to the EKS cluster (when validating resources).  It always dies on the validation for this **specific** resource (which does not exist, it's a clean cluster).

### Error Source

> Note: I am not a seasoned Go vet, nor am I well versed in the lower level C/CGO DNS implementation, nor do I know much about file system and file descriptors. The following is the result of some digging, but my understanding might very well be incorrect...!

Looking into this error, it turns out the error is poorly reported; the resource does _not_ exist in the EKS cluster, and the host _is_ reachable - there are successful requests between client <> server up until this error is encountered.  

The encountered error stems from a golang built-in source [`net/cgo_unix.go#L177`](https://github.com/golang/go/blob/master/src/net/cgo_unix.go#L177) and is raised as `EAI_NONAME`.  When this type is encountered, Golang returns `err = errNoSuchHost`. This error type is a known misnomer (as described in [`net/lookup_unix.go#L331`](https://github.com/golang/go/blob/master/src/net/lookup_unix.go#L331)) when encountered on some systems, including Darwin (MacOS).

After more investigation into this, it turns out that the error is raised when the system runs out of file descriptors which are used when making DNS requests with the C implementation of `getaddrinfo` in the Go `cgo` net package. Looking at my system (`ulimit -n`) it turns out that the default setting for this on a Macbook Pro (2019, running Big Sur) is set to `256`.

### Workaround
When I increased this (`ulimit -n 512`), the Helm chart installation is successful.  Essentially, out-the-box, Helm `v3.5.0` can't install charts of more than 256 resources when using system defaults (at least for MacOS/Big Sur).  

### Other Findings
However - as mentioned before - using a previous version of Helm worked. So I rolled back versions and discovered that the "break", occurred in `v3.4.2`. Versions prior to that _were_ able to install my Helm chart without errors. This change was not a big change ([comparison](https://github.com/helm/helm/compare/v3.4.1...v3.4.2)) and the piece of interest I think is the dependency update for the `k8s.io` libraries. 

In particular  the `k8s.io/client-go` changes ([comparison](https://github.com/kubernetes/client-go/compare/v0.19.3...v0.19.4)) version bump concerned two main updates; leader election (not relevant to this issue) and transport caching.  It seems as of this update, requests from Helm (using the k8s client) are no longer cached on a transport level, meaning (a) Helm runs _much_ slower, and (b) running into the DNS / max file descriptors issue described above. To prove my theory, I made a local change to `k8s.io/client-go@v0.19.4` (simply set the `canCache` variable to `true` [here](https://github.com/kubernetes/client-go/blob/master/transport/cache.go#L64) as it was effectively in previous versions), recompiled Helm and ran the chart install. This time the install was quicker, and also completed successfully. I am not sure of the relevance here (if any!) but it might be some useful background.

### System Info (as requested)

Output of `helm version`:

`version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"dirty", GoVersion:"go1.15.6"}`

Output of `kubectl version`:

`Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-14T05:15:04Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

AWS EKS

**Comment by bacongobbler** [comment]
Thanks for the report! So from your report it sounds like there is a bug that was introduced in a newer version of client-go. If that is correct, would you mind filing an issue or look at providing a patch for client-go? Any fixes to client-go will propagate down to Helm in the next available release.

**Comment by neilmcgibbon** [comment]
@bacongobbler I am not sure its a bug on the `k8s.io/client-go` library.  The removal of caching these request types is very intentional, looking at the commit.  I am more thinking that perhaps Helm is either doing too many concurrent requests (resulting in too many DNS lookups), or perhaps some kind of garbage collection has been overlooked?

**Comment by bacongobbler** [comment]
Okay. Let us know if you determine the root cause.

**Comment by neilmcgibbon** [comment]
@bacongobbler I believe the root cause is that too many requests are being made concurrently (or at least too quickly) by Helm, resulting in running out of file descriptors.

On one hand, a revert in the imported `client-go` library to re-introduce caching would solve this, but my guess is that the removal of caching for certain transport types is intentional and good design.

I don't have a good understanding of Helm internals, but when Helm ["visits" each resource in the validation step ](https://github.com/helm/helm/blob/master/pkg/action/validate.go#L43) is it possible here that file descriptors are being created too quickly or concurrently?

**Comment by gotshub** [comment]
I experienced the same issue as @neilmcgibbon running a MacBook Pro and trying to install ~250 resources to an EKS cluster. Setting `ulimit -n 1024` solved this for me, too. Thank you for that!

Is it possible to add a hint to the error message when this happens? Displaying `no such host` was confusing and it would help if the user knows about ran out file descriptors.

**Comment by neilmcgibbon** [comment]
@gotshub  - Can I ask if you're installing into AWS EKS, and if so, are you using the `aws-iam-authenticator` tool? I took a deeper dive into the `client-go` package and was wondering if the problem is with the third party authentication?

**Comment by gotshub** [comment]
@neilmcgibbon - No, we are using the AWS CLI for that. If I understand it correctly, the `aws-iam-authenticator` is [not needed when using AWS CLI](https://docs.aws.amazon.com/eks/latest/userguide/install-aws-iam-authenticator.html) starting from 1.16.156.

**Comment by tculp** [comment]
@bacongobbler @neilmcgibbon This is still an issue on version 3.7.1

**Comment by jastBytes** [comment]
This is still an issue with v3.9.1.
