### ISSUE TITLE
Helm template returns incorrect revision

### ISSUE THREAD

**Issue by david92rl** [helm/helm#9252]
**Output of** `helm version`:
```
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}
```

**Output of** `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
```

**Cloud Provider/Platform**: 
EKS

**Description**:
When running `helm template` all references to `.Release.Revision` result in 1

This is because [the template command uses the install method](https://github.com/helm/helm/blob/master/cmd/helm/template.go#L53) to render templates which [sets the revision to 1](https://github.com/helm/helm/blob/ab12382ddcd3a27a974b45ed96e47697de221244/pkg/action/install.go#L228) as it's supposed to be the first deployment of the release.

My question here is:
Could we use the upgrade method to initialise the client with the [right revision number](https://github.com/helm/helm/blob/ab12382ddcd3a27a974b45ed96e47697de221244/pkg/action/upgrade.go#L197)? Both methods have the same call format ([Install](https://github.com/helm/helm/blob/master/cmd/helm/template.go#L53) vs [Upgrade](https://github.com/helm/helm/blob/master/cmd/helm/upgrade.go#L65))

**Comment by bacongobbler** [comment]
You could try using `helm upgrade --dry-run --debug` if you're looking to see how an upgrade will look. There's also `helm template --validate` which will populate the `.Capabilities` object with the cluster's current resources, though that's not what you're looking for here.

In this case, `helm template` is working as intended - it renders the templates locally and displays the output. In other words, `helm template` does not have *any* context about the cluster's current state. It is not intended for use as a "dry run" prior to an upgrade.

I could see your proposal as a [plugin](https://helm.sh/docs/topics/plugins/).

**Comment by david92rl** [comment]
Thanks @bacongobbler 

The main reason I was asking this is because diff plugin relies on the template command to generate the new templates, so it always shows the [wrong revision number](https://github.com/databus23/helm-diff/issues/253).

I guess making the plugin use `upgrade --dry-run` instead of template should do the job.

**Comment by david92rl** [comment]
Closing as it works as intended
