### ISSUE TITLE
Change the deprecated charts repo URL in release notes

### ISSUE THREAD

**Issue by wi1dcard** [helm/helm#9253]
Current helm GitHub releases still include the URL to helm/charts repo which is obviously deprecated. Should we remove the link or change it to the relocating charts issue helm/charts#21103?

Release: https://github.com/helm/helm/releases/tag/v3.5.0
Related codes here: https://github.com/helm/helm/blob/ab12382ddcd3a27a974b45ed96e47697de221244/scripts/release-notes.sh#L73

Output of `helm version`:

Not relevant.

Output of `kubectl version`:

Not relevant.

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Not relevant.

**Comment by bacongobbler** [comment]
It's probably a good idea to replace that link with [ArtifactHub](https://artifacthub.io/).

**Comment by jwhitt3r** [comment]
I would be more than happy to make this change, aslong as @wi1dcard is happy for me to do so.

**Comment by wi1dcard** [comment]
> I would be more than happy to make this change, aslong as @wi1dcard is happy for me to do so.

@jwhitt3r  It would be great if you can submit a PR for this!

**Comment by jwhitt3r** [comment]
Thanks @wi1dcard, I have submitted a PR, however, CircleCI has some how failed. Would it be possible some assistance?
