### ISSUE TITLE
Wrong namespace in action.Install

### ISSUE THREAD

**Issue by nmiculinic** [helm/helm#9256]
The output of `helm version`:
v3.5.0

https://github.com/helm/helm/blob/v3.5.0/pkg/action/install.go#L256

In here the resource namespace is wrongly set to RestConfig default namespace, versus the `i.Namespace` or `options.Namespace`

This in practice means:
* I giver helm restConfig which has `default`  as configured namespace
* I create an install action with `i.Namespace = "something-else"`
* I run `i.Run()`
* The resources are created in "default" namespace, and not in the "something-else" namespace

Since I'm using install action with `i.CreateNamespace` the "something-else" namespace is created as expected. Likewise, helm release is created in "default" namespace, and not in "something-else" namespace.

**Comment by bacongobbler** [comment]
As I understand it, the `pkg/kube.Client` needs to switch namespaces as well. You can change the namespace parameter of the kubeclient by setting the action config's `KubeClient.Namespace`. Otherwise it will use the namespace set in your kubeconfig.

https://github.com/helm/helm/blob/8ea6b970ecd02365a230420692350057d48278e5/pkg/kube/client.go#L60-L61

https://github.com/helm/helm/blob/8ea6b970ecd02365a230420692350057d48278e5/pkg/kube/client.go#L129-L137

**Comment by bacongobbler** [comment]
See also https://github.com/helm/helm/issues/8269, which was opened for the same reason.

**Comment by nmiculinic** [comment]
I'm using the following code for setting up the action configuration:

```go
	actionConfig := new(action.Configuration)
	helmInterface, err := newRESTClientGetterWrapper(discoveryCacheDir, kubeconfig)
	if err != nil {
		return nil, err
	}
	if err := actionConfig.Init(helmInterface, namespace, os.Getenv("HELM_DRIVER"), func(format string, v ...interface{}) {
           ... logging setup 
        }
```

And I put the same namespace in here as well (the "some-namespace"). 

Looking at `action.Configuration.KubeClient` it's an interface, thus I cannot change it easily after it's been initialized via `actionConfig.Init`

**Comment by manuelmazzuola** [comment]
I solved doing that

```

type RESTClientGetter struct {
    clientconfig clientcmd.ClientConfig
}

func NewRESTClientGetter(bytes []byte) (*RESTClientGetter, error) {
    clientconfig, err := clientcmd.NewClientConfigFromBytes(bytes)
    if err != nil {
        return nil, err
    }

    rawconfig, err := clientconfig.RawConfig()
    if err != nil {
        return nil, err
    }

    clientconfig = clientcmd.NewDefaultClientConfig(rawconfig, &clientcmd.ConfigOverrides{
        Context: api.Context{
            Namespace: namespace,
        },
    })

    return &RESTClientGetter{clientconfig}, nil
}
````

**Comment by mtt0** [comment]
According to https://github.com/helm/helm/blob/43853ea772e779b617b011a8d4e69205636fa4f9/pkg/cli/environment.go#L91

Simple workaround:

```golang
func newActionConfig(namespace string, settings *cli.EnvSettings) (cfg *action.Configuration, err error) {
	cfg = new(action.Configuration)
	err = cfg.Init(newRESTClientGetter(namespace, settings), namespace, os.Getenv("HELM_DRIVER"), s.debug())
	if err != nil {
		return
	}
	return
}

func newRESTClientGetter(namespace string, settings *cli.EnvSettings) *restClientGetter {
	return &restClientGetter{&genericclioptions.ConfigFlags{
		Namespace:        &namespace,
		Context:          &settings.KubeContext,
		BearerToken:      &settings.KubeToken,
		APIServer:        &settings.KubeAPIServer,
		CAFile:           &settings.KubeCaFile,
		KubeConfig:       &settings.KubeConfig,
		Impersonate:      &settings.KubeAsUser,
		ImpersonateGroup: &settings.KubeAsGroups,
	}}
}

func DoWhatYouWant() (err error) {
	actionConfig, err := newActionConfig("your-namespace", cli.New())
	if err != nil {
		return
	}
	list := action.NewList(actionConfig)
        // ...
	_, err = list.Run()
	return
}
```

**Comment by ynnt** [comment]
By the way, it;s also accomplishable using this code

```
	if err := os.Setenv("HELM_NAMESPACE", *config.Namespace); err != nil {
		return nil, err
	}
	
	// create EnvSettings with cli.New() 

```
