### ISSUE TITLE
Helm gRPC max message size limit reached due to using docker bridge

### ISSUE THREAD

**Issue by krish7919** [helm/helm#9257]
Output of `helm version`:
```
$ helm version
WARNING: "kubernetes-charts.storage.googleapis.com" is deprecated for "stable" and will be deleted Nov. 13, 2020.
WARNING: You should switch to "https://charts.helm.sh/stable"
Client: &version.Version{SemVer:"v2.17.0", GitCommit:"a690bad98af45b015bd3da1a41f6218b1a451dbe", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.17.0", GitCommit:"a690bad98af45b015bd3da1a41f6218b1a451dbe", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a17149e1a189050796ced469dbd78d380f2ed5ef", GitTreeState:"clean", BuildDate:"2020-04-16T11:44:51Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.12-eks-31566f", GitCommit:"31566f851673e809d4d667b7235ed87587d37722", GitTreeState:"clean", BuildDate:"2020-10-20T23:25:14Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AWS EKS

I am looking at a very cryptic issue with respect to Helm/Tiller communication in 2 of our clusters - cluster 1 and cluster 2  - one works fine and the other does not.

Error message from cluster 1:

```
$  helm --kube-context cluster1 list --namespace my-namespace --max 1500
Error: trying to send message larger than max (20971838 vs. 20971520)
```

This cluster has a lower number of releases than cluster 2, but still reaches the gRPC maximum message size consistently; `helm list` works fine in cluster 2 even though there are more releases in cluster 2 than cluster 1.

The change in cluster 1 is that we have deployed a `hardened` AMI that follow the [CIS CAT hardening guidelines](https://www.cisecurity.org/cis-hardened-images/). We hit this error as soon as we upgraded the AMIs.

I have compared the configs, deployments, releases, etc. in both the cluster wrt helm and tiller, and they are identical.

To verify if the hardening is at fault, I dug into how the gRPC protocol works and if that might be affected due to hardening. Since gRPC issues would be an application level issue, I discarded it after some time.

Closely comparing the docker daemon setup in both the clusters, cluster 1 has:

```
[ec2-user@ip-10-1-15-134 ~]$ cat /etc/docker/daemon.json 
{
  "bridge": "none",
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "10m",
    "max-file": "10"
  },
  "live-restore": true,
  "max-concurrent-downloads": 10
}
```

whereas cluster 2 has:

```
[ec2-user@ip-10-11-61-53 ~]$ cat /etc/docker/daemon.json 
{
  "debug" : false
}
```

This issue might not be truly related to Helm/Tiller,  but I was wondering if anyone has seen gRPC acting up like this wrt Helm when Tiller is used over a `bridged` network vs a non-bridged network. Also, the `docker0` bridge interface in cluster 1 has an MTU of 1500 bytes, if that matters. Cluster 1 also has IPv6 disabled, whereas cluster 2 has it enabled.

The only literature that I came across on google is [this one](https://www.civo.com/learn/fixing-networking-for-docker) and the statement I could relate to was: `The effect of this is that you may get timeouts when connecting to internet services (such as package updates/downloads, Ruby gem installation, etc) or even that files download but don't have the correct size/contents.`

This incorrect size thing in the comment above resonated with me and maybe this is causing an issue?
Puttin this out there for the community to help as I am quite unsure what is going wrong here - Tiller, gRPC, the networking configs on the host, docker daemon, etc.

EDIT:

More literature from online: https://github.com/moby/moby/issues/12565

**Comment by bacongobbler** [comment]
Hi @krish7919. As of last November, we no longer provide support for issues related to Helm 2. Please test with Helm 3. Thanks.

https://helm.sh/blog/helm-2-becomes-unsupported/

**Comment by krish7919** [comment]
I will close this then, thanks :)

I had hoped that someone would have already faced this wrt networking configs in k8s, as this issue does not seem to be Helm/Tiller per se
