### ISSUE TITLE
helm lint (3.3.2+) fails with (un-named) v1.List objects

### ISSUE THREAD

**Issue by DazWilkin** [helm/helm#9258]
Recent (`3.3.2`+) versions of Helm appear to fail with un-`name`'d `v1.List` objects:

Similar: #9019 

In versions <`3.3.2`, the following (attempt at a minimal `v1.List`) is permitted;

```YAML
apiVersion: v1
kind: List
```

But >`3.3.2`, this results in the unclear error:

```console
object name must be between 0 and 253 characters: ""
```

Although `List` is an uncommon resource type, when it is used, it is rarely named, e.g. [example](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#create-custom-objects) but Helm `3.3.2`+ fails **unless** the `List` has a `metadata.name`:

```YAML
apiVersion: v1
kind: List
metadata:
  name: x
```

### Example

```bash
HELM_VERSION="3.5.0-rc.1" # Fails with `3.3.2` but succeeds with `3.2.4`
docker run \
--rm --interactive --tty \
--volume=${PWD}:/apps \
--entrypoint=sh \
alpine/helm:${HELM_VERSION}

helm create test

helm3 link test
==> Linting test
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, 0 chart(s) failed

echo '
apiVersion: v1
kind: List
' > ./test/templates/list.yaml

helm lint test
==> Linting test
[INFO] Chart.yaml: icon is recommended
[WARNING] templates/list.yaml: object name must be between 0 and 253 characters: ""

1 chart(s) linted, 0 chart(s) failed

echo '
metadata:
  name: x
' >> ./test/templates/list.yaml

helm lint test
==> Linting test
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, 0 chart(s) failed
```

### Propose

+ Confirming the error
+ Relaxing the requirement for `Lists` to be `name`'d or making the error more clear
+ Making the error clearer; even with `--debug`, there's no context provided with this error

**Comment by bacongobbler** [comment]
In more recent versions of Helm, this linter error has been reduced to a warning.

https://github.com/helm/helm/blob/ab12382ddcd3a27a974b45ed96e47697de221244/pkg/lint/rules/template.go#L142

A type check on the resource being linted is worth looking into. I know there are several other types that do not allow 253 characters in their name.

https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names

**Comment by bacongobbler** [comment]
However I am going to close this in favor of https://github.com/helm/helm/issues/9019. That way we can track the same discussion in one ticket, rather than having the same discussion twice.
