### ISSUE TITLE
Upgrade fails due to unable to create patch

### ISSUE THREAD

**Issue by curtisr7** [helm/helm#9259]
I've recently moved to helm3 and found that my application has some bad data in it charts. The net is that I have a bunch of charts that are installed, but I can't fix as `helm upgrade` fails with `failed to create patch: map: map[] does not contain declared merge key: name` if I try to modify these fields.

As far as I can tell helm3 uses `strategicpatch.CreateThreeWayMergePatch` on upgrade and that function validates data that has already been persisted in a prior install/upgrade. This is a problem as that same validation never occurred upon putting the data into the store.  

 I was able to recreate using a basic helm template application[1]

[1]
```
$ helm create test && \
sed -i 's/{{- toYaml . | nindent 8 }}/- {}/g' test/templates/deployment.yaml && \
sed -i 's|imagePullSecrets: \[\]|imagePullSecrets: asdf|g' test/values.yaml && \
helm install test ./test/ --values ./test/values.yaml && \
helm upgrade test ./test/ --values ./test/values.yaml
Creating test
NAME: test
LAST DEPLOYED: Wed Jan 20 21:09:58 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=test,app.kubernetes.io/instance=test" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace default port-forward $POD_NAME 8080:80
Error: UPGRADE FAILED: failed to create patch: map: map[] does not contain declared merge key: name
```

Output of `helm version`: version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-19T08:38:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): minikube

**Comment by curtisr7** [comment]
I've done a bunch more digging today and it seems that vanilla k8s has a similar problem. If you create a deployment that has invalid `imagePullSecrets`, `kubectl apply` will allow it to go through. If you then try to edit that deployment it'll fail with the same problem noted above. I found that if I update the deployment via `kubectl patch deploy --type=merge` I am able to get things fixed up. I'm seeing something similar-ish if I fix the helm deploy via `kubectl` except that I can ONLY do that if I fixup before issuing a `helm upgrade` that fails. 

Not sure sure what to make of it yet.

**Comment by jdolitsky** [comment]
When you say "I have a bunch of charts that are installed" - were these installed using Helm 2?

If its OK to have downtime, I'd suggest deleting them, and re-installing with Helm 3. Or, you may have luck using the helm 2to2 plugin which attempts to perform the release upgrade in place: https://github.com/helm/helm-2to3

**Comment by curtisr7** [comment]
> When you say "I have a bunch of charts that are installed" - were these installed using Helm 2?

Yes they were installed via helm2 but that doesn't really matter here. You can recreate this issue using only helm3 (as shown in my testcase above). 

> If its OK to have downtime,

Downtime is a no-go, we have hundreds of customers in production with this issue.

Really this is a bug in k8s that is really annoying for helm users. Where can I open a ticket to make a suggestion for an improvement?

Give the recreate I posted above a go. You'll see that k8s allows you to create a deployment and it doesn't validate the input. Later when you/helm try to create a patch via `strategicpatch.CreateThreeWayMergePatch` the original input is validated and the update fails. 

In my case I have a bad `imagePullSecret`(similar to the recreate above) and the workaround was to entirely remove the `imagePullSecret` section from my deployment template(rather than update to the correct value) and then the `helm upgrade` succeeded.

**Comment by jdolitsky** [comment]
kubernetes/kubernetes would be the proper place. Does this describe your issue? https://github.com/kubernetes/kubernetes/issues/58477

**Comment by curtisr7** [comment]
I've opened a bug against k8s for this issue -- https://github.com/kubernetes/kubernetes/issues/98963

Even if k8s gets fixed I'm pretty sure that helm has the same problem as it stores the old/bad data as the source for when creating a patch on `helm upgrade`
