### ISSUE TITLE
[REQUEST] helm daemon

### ISSUE THREAD

**Issue by rolaca11** [helm/helm#9262]
Helm is of course a really useful tool to deploy and manage complex installations on kubernetes, but it's limited to mostly manual use, from CLI as far as I could tell.

In my opinion, a much greater potential of this tool could be unlocked by implementing a layer inbetween the appplication logic and CLI, which could enable enhanced usability from other applications. For example, given a usecase, where a website wants to allow its users to spin up a new service at a click of a button, invoking the console interface from the backend is kind of gimmicky. 

If there was, for example, a docker-like interface, where the application can send a json text to either a unix, or a tcp socket, it would suddenly mean that the developers have much better control over their infrastructure of deploying helm charts, without all the assumptions to be made about the CLI approach and prevent a lot of possible mistakes.

Please, if there is a standard practice for the scenario I painted above, let me know. I mainly use Java, so a solution with that language in mind is prefered.

**Comment by debarshibasak** [comment]
Helm running in server mode with REST or gRPC interface might be a nice idea. I wonder what would be the side effects of it.

**Comment by bacongobbler** [comment]
> Helm running in server mode with REST or gRPC interface might be a nice idea. I wonder what would be the side effects of it.

I think you just described Tiller, which we removed in Helm 3 due to a number of poor default security settings.

I know of a few third party projects out there using the Helm SDK to implement a “helm operator”. You could write your own “helm daemon” using the Go SDK.

https://pkg.go.dev/helm.sh/helm/v3

**Comment by jdolitsky** [comment]
You might also take a look at the Flux Helm Operator: https://github.com/fluxcd/helm-operator

At Matt mentioned, this describes Tiller, which was intentionally removed in Helm 3. Closing this issue for the time being.

**Comment by rolaca11** [comment]
What I described is Helm 3, where the input is a TCP socket instead of STDIN. As far as I can tell, this isn't what Tiller was. 
It wouldn't even run on the k8s cluster, but on the client side.

**Comment by jdolitsky** [comment]
This is not something Helm will implement. I do think I understand what you are describing.

Few options to achieve this: 
- Create a simple web server in your favorite language, which executes Helm CLI directly as a subprocess
- Create a web server in Go (golang), that imports Helm pkg/actions and runs the same code as the CLI
