### ISSUE TITLE
Sprig `dig` doesn't dig into chartutil.Values

### ISSUE THREAD

**Issue by wingsofovnia** [helm/helm#9266]
For `values.yaml`:
```
smth:
  deep:
    here: "servus"
```

A new `dig` func coming from sprig 3.2.0 in Helm 3.5 doesn't work with scope variables.
```
{{ dig "Values" "smth" "deep" "there" "default" . }}
# or
{{ dig "smth" "deep" "there" "default" .Values }}
```
Outputs: `error calling dig: interface conversion: interface {} is chartutil.Values, not map[string]interface {}`

but this works:
```
{{ dig "deep" "there" "default" .Values.smth }}
```

As a workaround, this also works:
```
{{ dig "smth" "deep" "there" "default" (.Values | merge (dict)) }}
```

Expected behaviour: `dig` can dig into `.Values` at least.

Output of `helm version`:
`version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}`

Output of `kubectl version`:
`not relevant`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
`not relevant`

**Comment by jdolitsky** [comment]
Issue confirmed. I'm not sure the intended behavior of this function... Maybe we can force`chartutil.Values` into a `map[string]interface {}` prior to running a `dig`? Or can some fixes be made in sprig? cc @mattfarina

**Comment by tn185070** [comment]
`{{ dig "probes" "liveness" "initialDelaySeconds" "default" .Values }}` is working with version:
 `version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}`

**Comment by nmlccc** [comment]
Same error on `version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"dirty", GoVersion:"go1.16.3"}`

**Comment by faroukellouze** [comment]
Same error on `version.BuildInfo{Version:"v3.6.1", GitCommit:"61d8e8c4a6f95540c15c6a65f36a6dd0a45e7a2f", GitTreeState:"clean", GoVersion:"go1.16.5"}`

**Comment by faroukellouze** [comment]
@wingsofovnia why did you use the `merge` function in here

> As a workaround, this also works:
> 
> ```
> {{ dig "smth" "deep" "there" "default" (.Values | merge (dict)) }}
> ```

Why not just calling the `dict` function like this `{{ dig "smth" "deep" "there" "default" ( .Values | dict ) }}`

**Comment by DmitryTravyan** [comment]
> @wingsofovnia why did you use the `merge` function in here
> 
> > As a workaround, this also works:
> > ```
> > {{ dig "smth" "deep" "there" "default" (.Values | merge (dict)) }}
> > ```
> 
> Why not just calling the `dict` function like this `{{ dig "smth" "deep" "there" "default" ( .Values | dict ) }}`

Because `{{ dig "smth" "deep" "there" "default" ( .Values | dict ) }}` in helm 3.6.3 make map like this:
```
[map[map[smth:map[deep:map[there: default] ] ] ] :]
```

**Comment by deiga** [comment]
Isn't that Stale bot a bit aggressive? This issue was confirmed by a contributor and still the bot was allowed to close it. That seems a bit rash for an unfixed issue

**Comment by TSASM** [comment]
I'm experiencing this issue too

values.yaml
```
nginx:
  AppName: some-app-name
```

when I do either of the following
- `{{- $nginxAppName := dig "nginx" "AppName" "" .Values }}`
- `{{- $nginxAppName := dig  "AppName" "" .Values.nginx }}`

I get the same error
`error calling dig: interface conversion: interface {} is chartutil.Values, not map[string]interface {}`

helm version: 
`version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.8"}`

Is this intended or is it a bug?

**Comment by jouve** [comment]
same here.

can an maintainer advice if this is intended ?

**Comment by ziqianggeoffreychen** [comment]
I would like to know when will the fix be released? https://github.com/minio/operator/pull/1142 Thanks.

**Comment by bstrdsmkr** [comment]
I would also like to see this reopened. Perhaps @bacongobbler ?

**Comment by ziqianggeoffreychen** [comment]
This issue is still there in Helm 3.12.0. Please fix it. Merge https://github.com/minio/operator/pull/1142 can be an option. Thanks. @bacongobbler

**Comment by peergynt** [comment]
Values can easily be converted to a map: https://github.com/helm/helm/blob/v3.12.1/pkg/chartutil/values.go#L70
So why not use something like this:

`{{ dig "smth" "deep" "there" "default" .Values.AsMap }}`

instead of the _dict_ hack

`{{ dig "smth" "deep" "there" "default" (.Values | merge (dict)) }}`

**Comment by kasabov** [comment]
Because it still throws the below error:
`<dig "percona" "truststore" false .Values.asMap>: error calling dig: interface conversion: interface {} is nil, not map[string]interface {}`

My helm version is: `version.BuildInfo{Version:"v3.12.1", GitCommit:"f32a527a060157990e2aa86bf45010dfb3cc8b8d", GitTreeState:"clean", GoVersion:"go1.20.5"}`

I prefer using `default` instead of `| merge (dict)`: `if dig "truststore" false (default dict .Values.percona) ...`.

**Comment by peergynt** [comment]
@kasabov I don't think that the error you mentioned has anything to do with using `.Values.AsMap`
I assume that you got this error because you have a key in your chart with no value, such as:
```
percona:
```

You could run into the exact same error with your method if you dig one level deeper:
```
percona:
  truststore:
```
and try:
`{{ dig "truststore" "somekey" false (default dict .Values.percona) }}`

**Comment by kasabov** [comment]
My yaml (snippet) looks like this:

    percona:
      truststore: /u3+7QAAAAI...[base64]

Let's recap.

This `{{ dig "percona" "truststore" false .Values }}` throws this `... at <dig "percona" "truststore" false .Values>: error calling dig: interface conversion: interface {} is chartutil.Values, not map[string]interface {}`. 

This `{{ dig "percona" "truststore" false .Values.Map }}` throws this `... at <dig "percona" "truststore" false .Values.asMap>: error calling dig: interface conversion: interface {} is nil, not map[string]interface {}`. 

This `{{ .Values.percona.truststore }}` works. Should I be looking for another key in the `.Values` map that might be `null` and thus causing the NPE? Dumping `{{ .Values | quote }}` doesn't reveal any. Even if there's any nil value, it defeats the purpose of `dig` imho. That's exactly the tool I thought it is: to scan through a map, with or without nil keys and return a match.

**Comment by deiga** [comment]
@kasabov I think you might have a typo, the correct case of the words is important `.Values.AsMap`

**Comment by leoskyrocker** [comment]
`dig "key-level-1" key-level-2" .Values.AsMap` works for me.

**Comment by kasabov** [comment]
> @kasabov I think you might have a typo, the correct case of the words is important `.Values.AsMap`

@deiga  You're right, that was indeed the issue. Looking at my code now, I still suggest that `dig` (checks for, say a `Mappable` interface and) calls `.AsMap` for me internally.

**Comment by kasabov** [comment]
FWIW I've stopped using `dig` and `.AsMap` in favour of (nested) parentheses, e.g. `((.Values.percona).passwords).root`. It provides safety against missing dict, dict's key and/or dict's key's value. I find more concise and idiomatic.

**Comment by damaru-inc** [comment]
> FWIW I've stopped using `dig` and `.AsMap` in favour of (nested) parentheses, e.g. `((.Values.percona).passwords).root`. It provides safety against missing dict, dict's key and/or dict's key's value. I find more concise and idiomatic.

This works for me, Thanks! It looks like the best solution for my problem, which is how to run a subchart on its own, that uses global values. Now I can write something like:
`imagePullPolicy: {{ default "IfNotPresent" (((.Values.global).image).pullPolicy) }}`
Very nice!

**Comment by kasabov** [comment]
@damaru-inc Great! FYI, you shouldn't need the last pair of parentheses because that check is covered by `default`. I.e. this should be enough:

    imagePullPolicy: {{ default "IfNotPresent" ((.Values.global).image).pullPolicy }}

Possibly the parentheses around `.Values.global` is also superfluous.

**Comment by kasabov** [comment]
@kreempuff Unfortunately, there's not much info on this. For example, if you google "helm parenthesis" you'll get to this SO answer https://stackoverflow.com/a/68807258/410939 which points to https://pkg.go.dev/text/template#hdr-Actions.

It explains that the use of parenthesis in go templates (hence helm) is for grouping/pipelining and that a nil pipeline will produce no output. However, there's no clear text in the docs saying that you can access a member from a nil-pipeline without getting a nil error. And this is what we're (ab)using here.
