### ISSUE TITLE
Convert yaml to map

### ISSUE THREAD

**Issue by kotyara85** [helm/helm#9270]
Hello,
I read yaml files using .Files.Glob
Is there a way to convert them to maps to further processing?
Thanks

**Comment by jdolitsky** [comment]
Hello, yes it is possible. You must run a `.Files.Get` on the path, then pipe to `toYaml`.

Here is an example:
```
$ cat x.yaml
a:
  b:
    c: d
```

in a template:
```
env:
  - name: ISSUE_9270
    {{ range $path, $_ := .Files.Glob "x.yaml" }}
    value: {{ with ($.Files.Get $path | fromYaml) }}{{ .a.b.c }}{{- end }}
    {{- end }}
```

result:
```
env:
  - name: ISSUE_9270
    value: d
```

Closing issue for now, please re-open if this does not fix the problem. Thanks!

**Comment by kotyara85** [comment]
ty!
