### ISSUE TITLE
SemVer 2 version number breaks helm package for internal builds using commit short SHA version

### ISSUE THREAD

**Issue by ambye85** [helm/helm#9271]
At some point between Helm version 3.3.1 and 3.5.0, the `helm package` command started erroring when packaging a chart with a non-SemVer 2 version number in `Chart.yaml`. Defining this in the `Chart.yaml` file was a bit of a workaround for `helm package --version x.y.z` which has needed a SemVer 2 version number for a while.

This change has consequently broken our internal build pipelines, which use git commit short SHA's as version numbers. We do not increase a chart's SemVer for every change; this is done when we manually decide to make a release. It does not make sense for us to take the latest released version and add the commit SHA as pre-release or build information since that does not conform to SemVer. Equally, it would be inappropriate to arbitrarily decide to bump a patch, minor or major version just so that we could use pre-release/build information.

Why is the version number restricted to SemVer? It is a well known versioning scheme but by no means are any others invalid: CalVer is popular and I'm sure we're not the only teams using git short SHA's as unique internal versions either.

Can the SemVer 2 version numbering requirement be relaxed to allow other versioning schemes?

**Comment by ambye85** [comment]
I see from https://github.com/helm/helm/issues/9102 that it was suggested to use pre-release metadata. This means having to decide on a next version before even the first commit is made.

If Helm's internals are so tied to SemVer that this is not going to change, what are the alternatives?

**Comment by jdolitsky** [comment]
> This means having to decide on a next version before even the first commit is made.

Is there any issue using the next patch version as the next version, prior to the version being bumped?

Does something like this work for you?

```
$ helm create mychart
Creating mychart
$ CHART_PATH="./mychart/"
$ NEXT_PATCH_VERSION="$(cat ${CHART_PATH}/Chart.yaml | grep ^version: | cut -d ' ' -f 2 | awk -F. '{print $1 "." $2 "." $3+1}')"
$ GIT_SHORT_COMMIT="$(git rev-parse --short HEAD)"
$ helm package "${CHART_PATH}" --version "${NEXT_PATCH_VERSION}-rc-${GIT_SHORT_COMMIT}"
Successfully packaged chart and saved it to: /myrepo/mychart-0.1.1-rc-ab12382d.tgz
```

**Comment by ambye85** [comment]
That could work, thanks for the suggestion. I was thinking I could actually just use `0.0.0-${GIT_SHORT_COMMIT}`, but that's a reasonable approach too.
