### ISSUE TITLE
Pods not getting created when using resourcequota with namespace (helm installation)

### ISSUE THREAD

**Issue by georgebency** [helm/helm#9272]
I am facing the following issue related to specifying resourcequota for namespace .

I have helmified a simple wordpress application from the below page.
https://kubernetes.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/

My helmified code attached here-in
[chart-3.zip](https://github.com/helm/helm/files/5863957/chart-3.zip)

If the above chart-3 is deployed, then for some reason the pods are not getting created
No issue is observed for the creation of "Services" or "PVC", issue is just with the PODs not coming up

However if the "namespace-quota" module is removed then PODs are getting created.
The namespace-quota here is used to assign resource-quota for namespace.

Output of few kubectl command below
[george charts]$ kubectl get resourcequota -n geo-test
NAME                            AGE      REQUEST                                                                                                                              LIMIT
gke-resource-quotas    3h25m    count/ingresses.extensions: 0/100, count/ingresses.networking.k8s.io: 0/100, count/jobs.batch: 0/5k, pods: 0/1500, services: 2/500   
namespace-quota         25s         requests.cpu: 0/3, requests.memory: 0/8Gi                                                                                            limits.cpu: 0/6, limits.memory: 0/12Gi

[george charts]$ kubectl get pod -n geo-test
No resources found in geo-test namespace.
[george charts]$ 

[george charts]$ kubectl get svc -n geo-test
NAME                    TYPE                CLUSTER-IP    EXTERNAL-IP    PORT(S)            AGE
wordpress              LoadBalancer   10.124.x.xx       34.71.xxx.xxx     80:31172/TCP    114s
wordpress-mysql    ClusterIP           None                <none>               3306/TCP           114s
[george charts]$

[george charts]$ kubectl get pvc -n geo-test
NAME             STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
mysql-pv-claim   Bound    pvc-a8564c9a-d6d2-45dd-8a29-23a25d611dc3   20Gi       RWO            standard       2m54s
wp-pv-claim      Bound    pvc-5b8323ed-619a-4f05-a403-b10fce51d734   20Gi       RWO            standard       2m54s
[george charts]$ 

helm version
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

**Comment by jdolitsky** [comment]
I believe this is a Kubernetes issue vs. Helm.

Upon setting a namespace quota, you may need to set the pod's resources explicitly. On your wordpress deployment, try adding a `resources` section, such as:

```
  containers:
  - image: wordpress:4.8-apache
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
```

Please let us know if this fixes the issue.

**Comment by georgebency** [comment]
Thanks a ton @jdolitsky 
I made the check and it works fine.
Can you also let us know on how to troubleshoot such issue or view relevant logs on why the pods are not getting created, because it does not prompt any error during deployment.

**Comment by bacongobbler** [comment]
https://kubernetes.io/docs/tasks/debug-application-cluster/debug-application/ is a good general resource for troubleshooting issues related to your application.

Looks like this can be closed. Let us know if you have any further questions.

**Comment by georgebency** [comment]
@jdolitsky @bacongobbler 
Another issue i observed for my application when using namespace is that my PVC is not getting created when using namespace quota.
Do i need to specify the storageClass or PVC too.

[george@test chart-1]$ kubectl get pvc -n geo-test
NAME                STATUS    VOLUME            CAPACITY   ACCESS MODES   STORAGECLASS                    AGE
volsolr-solr-0      Pending                                                                                    privachart1-store-solrcluster   10s

[george@test chart-1]$ kubectl describe pvc volsolr-solr-0 -n geo-test
Name:          volsolr-solr-0
Namespace:     geo-test
StorageClass:  privachart1-store-solrcluster
Status:        Pending
Volume:        
Labels:        app=solr-app
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Mounted By:    <none>

Events:
  Type    Reason                Age                 From                         Message
  ----    ------                ----                ----                         -------
  Normal  WaitForFirstConsumer  32s (x42 over 10m)  persistentvolume-controller  waiting for first consumer to be created before binding

**Comment by georgebency** [comment]
I will have to figure this out later.
Please feel free to close this ticket.
Thanks a ton for your help.
