### ISSUE TITLE
<no-value> stripped from the rendered 'yaml'

### ISSUE THREAD

**Issue by shamil** [helm/helm#9273]
Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:52:24Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"89182bdd065fbcaffefec691908a739d161efc03", GitTreeState:"clean", BuildDate:"2020-12-18T12:02:35Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

`kOps` on `AWS`  

The line (https://github.com/helm/helm/blob/master/pkg/engine/engine.go#L257) causing `<no-value>` to be stripped from the rendered `yaml`. We have a configmap of shell script that needs to check for this value

```
get_node_label() {
    local label="$1" value

    [ -z "$label" ] && return 1
    value=$(kubectl get node $NODE_NAME -o 'go-template={{index .metadata.labels "'$label'"}}')

    [ "$value" == '<no value>' ] && return 1
    echo $value
}
```

I don't think that helm should touch anything which is not part of `go-template`brakets.

**Comment by jdolitsky** [comment]
Sorry you're having issues with this. Looking through commit history, it appears this has been the case since Helm 3.0. What version of Helm were you using previously where this worked?

What if this function was modified to be something like:
```
[ "$value" == '<no value>' ] && return 1
[ "$value" == '' ] && return 1
```
?

**Comment by shamil** [comment]
@jdolitsky as I mentioned in the issue description, I use helm  `3.4.1`. 

> What if this function was modified to be something like:
> 
> ```
> [ "$value" == '<no value>' ] && return 1
> [ "$value" == '' ] && return 1
> ```

This exactly what happens, helm removed the `<no value>` and it becomes `''` empty string.
I can't modify the function, I'm running `kubectl` command which can return `<no value>` which I need to handle, but helm rendering not allowing me to :(

Currently my workaround is to not look for exact `<no value>` string, I changed the script to look for `no value` instead. But this doesn't change the fact that `helm` manipulates original (**non templated**) text, which can potentially lead to bad outcome, such as I saw, and took me a lot of time to understand that `helm` is to blame here, before I did this workaround.  So I think we should take care of this.

**Comment by bacongobbler** [comment]
I'm pretty sure this has been Helm's intended behaviour since Helm 2. I don't recall a time when `<no value>` strings were rendered by the template engine. These string values have been suppressed since we first started using text/template in helm-classic IIRC.

From the described use case, it appears that you are checking for `<no value>` in the template output, returning a non-zero exit code if there was a failure. `pkg/engine` emits errors if the template engine's `Strict` value is set to `true`. This is currently used for `helm lint --strict`, though I'm sure you could re-use that functionality in your own project.

https://github.com/helm/helm/blob/715a0d6ef4ff09f6c1f655c5af6a23d70bd3dab9/pkg/engine/engine.go#L206-L212

**Comment by bacongobbler** [comment]
You could alternatively use the `default` or `fail` functions instead. More info can be found here: https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#helm

**Comment by shamil** [comment]
I'm not sure how it related, I'm not talking about how `helm` should handle values. I'm saying that changing/altering/manipulation text outside go-template is not good thing to do.

imaging I've the following `configmap` template in `templates/configmap.yml`

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-with-no-value
  labels:
    indication-label: '<no value>'
data: |
    This is my text that I would like to not be touched, 
    even when there is '<no value>' string in it
```

As you can see I don't have any `go-template` related markup here, this is pure text only `configmap`
Helm will render it as below:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-with-no-value
  labels:
    indication-label: ''
data: |
    This is my text that I would like to not be touched, 
    even when there is '' string in it
```

Do you think this is intended behaviour, if yes, was it documented anywhere that `<no value>` string will be stripped, regardless if this part of the non templated text, like shown above?

**Comment by bacongobbler** [comment]
The ability to output an empty value when it is not found is a documented, publicly available feature of text/template. So I’m not sure how you can make the argument that we’re somehow manipulating the output of text/template.

https://github.com/helm/helm/blob/715a0d6ef4ff09f6c1f655c5af6a23d70bd3dab9/pkg/engine/engine.go#L211

https://golang.org/pkg/text/template/#Template.Option

**Comment by shamil** [comment]
Well @bacongobbler this is frustrating, you closing this issue without even trying understand what is my issue. You point me to the code which has nothing to do with my problem. As I said `<no value>` I get is not returned as a result of the helm template rendering, it was a static text in my yaml file, which happens here:

https://github.com/helm/helm/blob/37c7bb4684b2c664f3a31122240b599b80674684/pkg/engine/engine.go#L254-L257

But, I won't argue, your project, close issues as you wish...

**Comment by bacongobbler** [comment]
Thank you for clarifying. It wasn't clear what was the issue. I'll re-open the ticket.

The documentation in that comment clarifies the workaround. Long ago there were certain versions of Go where setting `missingkey=zero` would still emit those values. That specific line of code was introduced back in Helm 2.0.0-alpha.3 - a little over 5 years ago. See https://github.com/helm/helm/pull/888 and https://github.com/helm/helm/issues/887 for more context. And `<no value>` is such a text/template thing that nobody up to this point has encountered the issue where their own templates have this string present in their files.

I think we can remove that workaround at this point. Please feel free to submit a PR to remove the workaround.

**Comment by shamil** [comment]
@bacongobbler thanks for re-opening.
I can sumit PR, but this is going to fail some tests (which I can adopt), since non exsting values will have `<no value>` in the rendered template. Will this be sufficient?

**Comment by bacongobbler** [comment]
In general, changes to the tests are fine so long as it doesn't break backward compatibility. If the change will break backwards compatibility, then perhaps we need to address the issue some other form.
