### ISSUE TITLE
It doesn't work about setting arrays of maps with --set using curly braces.

### ISSUE THREAD

**Issue by fanliquan** [helm/helm#9281]
Output of `helm version`:
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-21T13:03:39Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

It doesn't work to set arrays with --set using curly braces. 
**` helm template mychart  -n mynamespace --set foo={a,b,c}`**
The output of the command is as below:

> Error: expected at most two arguments, unexpected arguments: foo=c
> helm.go:81: [debug] expected at most two arguments, unexpected arguments: foo=c
> helm.sh/helm/v3/pkg/action.(*Install).NameAndChart
>         /home/circleci/helm.sh/helm/pkg/action/install.go:541
> main.runInstall
>         /home/circleci/helm.sh/helm/cmd/helm/install.go:178
> main.newTemplateCmd.func2
>         /home/circleci/helm.sh/helm/cmd/helm/template.go:70
> github.com/spf13/cobra.(*Command).execute
>         /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
> github.com/spf13/cobra.(*Command).ExecuteC
>         /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
> github.com/spf13/cobra.(*Command).Execute
>         /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
> main.main
>         /home/circleci/helm.sh/helm/cmd/helm/helm.go:80
> runtime.main
>         /usr/local/go/src/runtime/proc.go:203
> runtime.goexit
>         /usr/local/go/src/runtime/asm_amd64.s:1373

But It works if I use the command like this:
**` helm template mychart  -n mynamespace --set foo="{a,b,c}"`**

Is it a bug in this helm version? Thanks!

**Comment by bacongobbler** [comment]
Seems to work just fine with the default chart via `helm create`.

```
><> helm template test-9281/ --set "imagePullSecrets={foo,bar}" --show-only templates/deployment.yaml
---
# Source: test-9281/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME-test-9281
  labels:
    helm.sh/chart: test-9281-0.1.0
    app.kubernetes.io/name: test-9281
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: test-9281
      app.kubernetes.io/instance: RELEASE-NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test-9281
        app.kubernetes.io/instance: RELEASE-NAME
    spec:
      imagePullSecrets:
        - foo
        - bar
      serviceAccountName: RELEASE-NAME-test-9281
      securityContext:
        {}
      containers:
        - name: test-9281
          securityContext:
            {}
          image: "nginx:1.16.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
```

Can you share your template?

**Comment by bacongobbler** [comment]
Try wrapping `foo={a,b,c}` in quotes, like so: `--set "foo={a,b,c}"`. Your terminal emulator might be interpreting that as bash syntax.

**Comment by fanliquan** [comment]
Hi Matthew,
Thanks a lot for your answer. It works by using `--set "foo={a,b,c}"`.  
If the parameter has only one array value, we can use the command  `helm template mychart -n mynamespace --set foo={a}`.
But if the parameter has multiple values. It doesn't work by the command `helm template mychart -n mynamespace --set foo={a,b,c}`. That will make confuse to set value by the same way.  Thanks!

Best Regards,
Liquan

**Comment by bacongobbler** [comment]
Nothing we can do here; just bash doing bash things.
