### ISSUE TITLE
Helm 3.5.0 releases disappear if timed out

### ISSUE THREAD

**Issue by guy-microsoft** [helm/helm#9282]
**How to reproduce:**
1. Do `helm upgrade` command, and set `--timeout` (with some value) and `--wait` flags.
2. Press CTRL+C to terminate the helm upgrade operation.
2. The `helm upgrade` command will fail.
3. Do `helm ls` command, and now you won't be able to see the release.
4. Try to do `helm upgrade` command again for this release.
5. You will get the following error: `another operation (install/upgrade/rollback) is in progress`.

**What I would expect:**
I would expect that the release will be in a "failed" state, and won't disappear from the releases list. In addition, I would expect that the second helm upgrade would work, and fix the release to the desired state.

**Why I would expect that:**
Releases may fail from time to time due to timeouts or abruptions, and retrying `helm upgrade` command is the desired solution in these cases.

**A workaround:**
If you get `another operation (install/upgrade/rollback) is in progress` error, you can rollback/delete the release, and then do `helm upgrade` command again. However, as I stated, I don't think this is the desired behavior.

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

**Comment by bacongobbler** [comment]
Can you check the status of the release with `helm history`?

**Comment by guy-microsoft** [comment]
@bacongobbler, yes:
![image](https://user-images.githubusercontent.com/50947884/105959060-18071900-6084-11eb-8912-c9f9d7bd3b72.png)
I checked it more deeply, and I think that the issue happens when the helm client closes the connection with the cluster (for example, when you press CTRL+C during helm upgrade with wait).
I'm updating my issue with a more accurate description.

**Comment by Alien2150** [comment]
Also noticed that behavior on my side. The worst thing that happens that the deployment is not longer listed.

**Comment by Alien2150** [comment]
My history looks like this: 

```
817     	Fri Jan 29 03:10:43 2021	superseded	middleware-1.0.0	           	Upgrade complete
818     	Fri Jan 29 10:23:58 2021	failed    	middleware-1.0.0	           	Upgrade "middleware-master" failed: timed out waiting for the condition
819     	Fri Jan 29 10:46:01 2021	deployed  	middleware-1.0.0	           	Upgrade complete
```

**Comment by guy-microsoft** [comment]
@Alien2150 `helm rollback` worked for me as an alternative to deleting the secret.

**Comment by Alien2150** [comment]
Will try next time @guy-microsoft. Was not seeing the release anymore

**Comment by guy-microsoft** [comment]
You're right @Alien2150, it disappears, but if know the name of the missing release, rolling it back will restore it. It's not the ideal solution, but it's the best we can do until the issue is fixed.

**Comment by jdemeyer** [comment]
I fixed this with `helm delete $RELEASE`. Still, annoying that these broken releases don't show up in `helm list`.

**Comment by Alien2150** [comment]
Some news on this?

**Comment by juliangovender** [comment]
still having this issue on helm v3.6.3

**Comment by Donnie** [comment]
This issue is still there with 3.7.0
