### ISSUE TITLE
Minor documentation issue in code

### ISSUE THREAD

**Issue by krish7919** [helm/helm#9283]
https://github.com/helm/helm/blob/master/cmd/helm/list.go#L129 states that:

`f.IntVar(&client.Offset, "offset", 0, "next release name in the list, used to offset from start value")`

This was fine with Helm 2 as we provided the name of the next release as a `strung` which was the next offset.

For Helm 3, the text should be changed to `next release index in the list, used to offset from start value`, as we provide the actual offset index, which is an `int`.

**Comment by bacongobbler** [comment]
Thanks for finding this. Feel free to provide patches to clear up this documentation issue.

**Comment by krish7919** [comment]
That's the weekend job, @bacongobbler  :)

https://github.com/helm/helm/pull/9301
