### ISSUE TITLE
Accessing CLI flags and parameters in helm templating

### ISSUE THREAD

**Issue by SimonBaeumer** [helm/helm#9286]
Hey Helm-Team,
what do you think about making CLI flags (and parameters) available in the helm-charts, i.e. accessing the value of `--reuse-values` vià a built-in object like `CliFlags.ReuseValues`?

**Comment by bacongobbler** [comment]
Hi @SimonBaeumer. Can you please explain your use case for this?

Keep in mind that these flags were designed to help the user determine which values are injected into the rendering engine. The chart is not intended to know or understand _how_ those flags were presented. The assumption being that the chart should know know (and care) about the values presented by the user, and render the templates accordingly.

**Comment by SimonBaeumer** [comment]
Hey @bacongobbler,
thanks for the response!
Yes, you are right. I was thinking about checking if `--reuse-values` was used, but it did not make sense at all because all values are provided anyways.
So this can be closed.
