### ISSUE TITLE
Helm 2.17 is not supported on ARM64. Please, fix the build!

### ISSUE THREAD

**Issue by zoonman** [helm/helm#9289]
Output of `helm version`: v2.17.0

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.1-34+97978f80232b01", GitCommit:"97978f80232b0141732accadfd29444095bcd54f", GitTreeState:"clean", BuildDate:"2021-01-11T12:20:27Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.1-34+97978f80232b01", GitCommit:"97978f80232b0141732accadfd29444095bcd54f", GitTreeState:"clean", BuildDate:"2021-01-11T12:29:09Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/arm64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): microk8s, raspberry PI

You have moved off from docker hub I understood. But it broke old platforms.

**Comment by zoonman** [comment]
Guys, please, at least make one-off build.

**Comment by bacongobbler** [comment]
Hi @zoonman. We officially dropped support for Helm 2 last November. We announced in several locations, including the mailing lists, dev calls, twitter accounts, and on our blog: https://helm.sh/blog/helm-2-becomes-unsupported/

Because of this, we will not be providing support for this request. Thank you for understanding.

**Comment by bacongobbler** [comment]
If you wish for an ARM64 build of Helm, please consider upgrading to Helm 3. We have ARM64 builds available for that release.

https://helm.sh/docs/topics/v2_v3_migration/#helm

**Comment by zoonman** [comment]
You could at least make the last 2.x version to be build on arm64. And introduce new build and repos in v3.
It would be right decision.

**Comment by bacongobbler** [comment]
If you wish to use Helm on ARM64 devices, please migrate to Helm 3.
