### ISSUE TITLE
helm registry: helm chart save on the same tgz package generates a different digest (sha)

### ISSUE THREAD

**Issue by dsaydon90** [helm/helm#9292]
I'm trying to add **additional** `tag` to my helm registry chart. I have tried to save the helm chart again, but it didn't work because `helm chart save` on the same `tgz` package generates a different digest (sha) 

```
user@laptop:/tmp/helm$ helm chart save foo-1.0.0.tgz foo:test
ref:     foo:test
digest:  c0c0aa3bc107d5efb15e9403ca04557477175b5df937459e1082211d04a381e2
size:    1.8 KiB
name:    foo
version: 1.0.0
test: saved

user@laptop:/tmp/helm$ helm chart save foo-1.0.0.tgz foo:test
ref:     foo:test
digest:  2bf0a03f2962ccb3ed93a6e7eaa0e8f28627ef25236be5d788f403e9331c8c5b
size:    1.8 KiB
name:    foo
version: 1.0.0
test: saved
```

any other way to add **additional** `tag` to my helm registry chart just like docker?

Output of `helm version`:
```
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
eks

**Comment by wawa0210** [comment]
https://github.com/helm/helm/blob/6297c021cbda1483d8c08a8ec6f4a99e38be7302/internal/experimental/registry/cache.go#L288-L306

Helm calcuate chart digest by tmpFile()
`contentBytes, err := ioutil.ReadFile(tmpFile) `

The helm chart save's temporary package file is recreated each time, so the byte of each file change obtained will be inconsistent

If we use the real data of helm chart every time, this problem will be resolved

such as

```

// saveChartContentLayer stores the chart as tarball blob and returns a descriptor
func (cache *Cache) saveChartContentLayer(ch *chart.Chart) (*ocispec.Descriptor, bool, error) {
	destDir := filepath.Join(cache.rootDir, ".build")
	os.MkdirAll(destDir, 0755)
	tmpFile, err := chartutil.Save(ch, destDir)
	defer os.Remove(tmpFile)
	if err != nil {
		return nil, false, errors.Wrap(err, "failed to save")
	}
	var contentBytes []byte
	for _, raw := range ch.Raw {
		contentBytes = append(contentBytes, raw.Data...)
	}
	contentExists, err := cache.storeBlob(contentBytes)
	if err != nil {
		return nil, contentExists, err
	}
	descriptor := cache.memoryStore.Add("", HelmChartContentLayerMediaType, contentBytes)
	return &descriptor, contentExists, nil
}
```

Do you have any other suggestions? If there is no problem I will mention a p'r accordingly 
@bacongobbler

**Comment by jdolitsky** [comment]
This was found a while ago: https://github.com/helm/helm/issues/8212

Ultimately related to https://github.com/helm/helm/issues/3612

The `helm chart` commands (including `helm chart save`) will be soon removed. Instead .tgzs will be pushed directly. It does not make sense to add a fix for this at this point
