### ISSUE TITLE
Helm upgrade/rollback command doesn't upgrade/rollback the resource when ImagePullBackOff error

### ISSUE THREAD

**Issue by murugan-kannan** [helm/helm#9295]
Steps: 
1. helm install with the right image
2. helm upgrade with the wrong image
3. helm upgrade with the right image  - not working
                              or 
    helm rollback - also not working

Output of `helm version`:
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  docker-desktop

**Comment by mattfarina** [comment]
Are you referring to the wrong container image specified to the chart or the wrong chart? What kind of state does the Helm release and kubernetes objects get into?

**Comment by murugan-techie** [comment]
I specified the wrong container image in the helm chart.

NAME                        READY   STATUS                RESTARTS   AGE
pod/demo-app-0       0/1     ImagePullBackOff        0            3h6m

Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  3h8m                  default-scheduler  Successfully assigned default/demo-app-0 to docker-desktop
  Normal   Pulling    3h6m (x4 over 3h8m)   kubelet            Pulling image "app:14.0.2"
  Warning  Failed     3h6m (x4 over 3h8m)   kubelet            Failed to pull image "app:14.0.2": rpc error: code = Unknown desc = Error response from daemon: pull access denied for hod-one-server, repository does not exist or may
require 'docker login': denied: requested access to the resource is denied
  Warning  Failed     3h6m (x4 over 3h8m)   kubelet            Error: ErrImagePull
  Normal   BackOff    11m (x186 over 3h8m)  kubelet            Back-off pulling image "app:14.0.2"
  Warning  Failed     97s (x228 over 3h8m)  kubelet            Error: ImagePullBackOff

**Comment by yacinelazaar** [comment]
Im also experiencing the exact same issue described  as @murugan-kannan.
Here is the release history after attempting upgrade of a successful release with a non existing image.
![image](https://user-images.githubusercontent.com/1111396/115226871-a0d3a500-a107-11eb-8b17-28aad5fed44e.png)
Rollback does not happen, neither do any successive upgrade with the right image.

**Comment by srinivasev** [comment]
Hi @murugan-kannan,
Is the question somewhat similar to this - https://github.com/helm/helm/issues/9633

I see the helm doesn't check for the pod status if there is no change in the deployment object. So, in step-2, you already upgraded to some chart (I think you explicitly made sure the image is not available). Again while performing step-3, you made the image available referred in the chart. So, both step2 and step3 are using the same deployment manifest, and the only missing is the image from the repo between the steps.

Your expectation is, the `demo-app-0` should have terminated and re-created freshly in step-3 which was in ImagePullBackOff 
state?.

**Comment by murugan-kannan** [comment]
> Hi @murugan-kannan,
> Is the question somewhat similar to this - #9633
> 
> I see the helm doesn't check for the pod status if there is no change in the deployment object. So, in step-2, you already upgraded to some chart (I think you explicitly made sure the image is not available). Again while performing step-3, you made the image available referred in the chart. So, both step2 and step3 are using the same deployment manifest, and the only missing is the image from the repo between the steps.
> 
> Your expectation is, the `demo-app-0` should have terminated and re-created freshly in step-3 which was in ImagePullBackOff
> state?.

look like yes
