### ISSUE TITLE
Request: Fail out when helm install [NAME] [CHART] is given a bad chart value

### ISSUE THREAD

**Issue by joestringer** [helm/helm#9299]
From the `/tmp` directory with no local `cilium` directory:

```
$ helm upgrade -i cilium cilium --namespace cilium --version=v1.7.13 --set global.nodeinit.enabled=true --set nodeinit.reconfigureKubelet=true --set nodeinit.removeCbrBridge=true --set nodeinit.restartPods=true --set global.cni.binPath=/home/kubernetes/bin --set global.gke.enabled=true --set config.ipam=kubernetes --set global.nativeRoutingCIDR=10.0.0.0/14
Release "cilium" does not exist. Installing it now.
Error: failed to download "cilium" at version "1.7.13" (hint: running `helm repo update` may help)
```

Cilium seems to be there:
```
$ helm repo list  | grep cilium
cilium          https://helm.cilium.io/
```

However because I passed a variant on `helm install cilium cilium`, the `[CHART]` value to the CLI is `cilium`, but that is neither a real directory for a local chart nor a fully-qualified repository chart path.

The error is misleading because it suggests that the version is wrong, but it's really the chart that cannot be found (because it's neither a local directory named `cilium` and also the actual chart path for the repository would be `cilium/cilium`).

**Comment by mattfarina** [comment]
Do you have a suggestion for a different error message that would be more descriptive and handle the varying formats a chart could be in?

**Comment by joestringer** [comment]
My suggestion would be something like:

* Try to look for a directory
* If a directory is not present, try to parse the `[CHART]` as a `repo/chart`. If that is not present, error out with "There is no such chart directory or repo/chart named <user-input>".
* If one of the above *is* present, then continue with the current logic and start reaching out over the network to figure out whether the resource is actually available. For the case where the version is wrong (because it's not available), the current error message (newly changed in one of the recent maybe 3.4.x/3.5.x versions) seems like it is quite useful.
