### ISSUE TITLE
helm lint performance does not scale well with increases in dependencies

### ISSUE THREAD

**Issue by richgerrard** [helm/helm#9303]
`helm version`:
```
$ helm version
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"dirty", GoVersion:"go1.15.6"}
```

I have a helm chart recently converted to apiVersion: v2
In the Chart.yaml file, we package 63 other charts as dependencies.

Running `helm lint` on this chart takes longer than our CI checks allow, and leads to unwanted delays in our release pipeline.

I tabulated the timings for `helm lint` adding 3 chart dependencies at a time, until I had built all 63 again.
Here are the results:
```
0 charts: 0 seconds
3 charts: 7s
6 charts: 28s
9 charts: 60s
12 charts: 85s (1m25s)
15 charts: 115s
18 charts: 136s
21 charts: 168s
24 charts: 198s (3m18s)
27 charts: 246s
30 charts: 314s
33 charts: 372s
36 charts: 417s (6m57s)
39 charts: 485s
42 charts: 633s
45 charts: 745s
48 charts: 793s (13m13s)
51 charts: 975s
54 charts: 1146s
57 charts: 1340s
60 charts: 1559s (25m59s)
63 charts: 1786s (29m46s)
```
![LintDuration](https://user-images.githubusercontent.com/44039305/106371467-b7513800-6332-11eb-9154-2c845d476c6b.jpg)

You can see that the time it took to complete the lint runs roughly doubled with the addition of every 12 charts.
At 75 charts, I project `helm lint` to take 1 hour at a minimum.

As a contrast, after a `helm dep update`, running `helm lint *` on just the packaged dependencies in the `charts` folder takes 44 seconds.  This is an acceptable amount of time to lint 63 chart dependencies, and should be the goal for linting the parent chart as well.

**Comment by bacongobbler** [comment]
Thanks for the report. Were you able to determine what might be causing it to take that long?

We've seen one case in the past with charts that use the `template` function excessively (`template` takes a string and re-runs it through the template engine). I can't recall whether a community member fixed that issue.

Let us know what you find out.

**Comment by richgerrard** [comment]
> Were you able to determine what might be causing it to take that long?
> 
Not yet; templating is on my list of checks.  In the graph there's one data point between 45 and 48 charts that was a little faster than expected, and one of those dependencies I included there was atypical: it was on the simplistic side, compared to the other charts in my project.

**Comment by richgerrard** [comment]
We've halted development on this particular project, and I won't be able to provide any more updates on debugging efforts for the scale issue here.  It remains real, it's just not something I can assist with at present. Sorry!

**Comment by bacongobbler** [comment]
No worries. If you can share more information on how to reproduce this issue, then we can attempt to reproduce it and see if there's something we can address. Without that I'm afraid there's not much we can do other than speculate.
