### ISSUE TITLE
Can helm upgrade run faster in my case? How to determine the bottleneck?

### ISSUE THREAD

**Issue by fabriciojs** [helm/helm#9304]
Running `helm upgrade` takes ~3 minutes o a small application - with 3 services. The only change in the deployment is the image for one of the services. **Can or should that be faster in a general sense**?

Worth mentioning the chart handles ServiceAccount/Role for later restrict access to that namespace, as well as some post-release hooks for the application's housekeeping.

With the `--debug` flag I see the output:

```
helm upgrade --install --debug --atomic --cleanup-on-fail --create-namespace --namespace=my-namespace app /path/mychart --values=/path/values.yaml --timeout=10m
...
[2021-01-31 05:43:39] [err] history.go:56: [debug] getting history for release app
[2021-01-31 05:43:39] [err] upgrade.go:123: [debug] preparing upgrade for app
[2021-01-31 05:44:12] [err] W0131 05:44:12.391886     429 transport.go:260] Unable to cancel request for *exec.roundTripper
[2021-01-31 05:47:21] [err] upgrade.go:131: [debug] performing update for app
```

So [prepareUpgrade](https://github.com/helm/helm/blob/f5ef87b96e791ca9971231699fc5af687f748bae/pkg/action/upgrade.go#L148-L242) takes all the time, and indeed it does a lot of things:

- fetch releases
- check pending/deployed release statuses
- check reusing values
- process dependencies
- parses values / render resources
- validate manifest

Some of these steps should have bottlenecks linked to the chart complexity itself, and others to the cluster state/performance or network. My question is - how to tell where time is allocated here? In order to determine if there are any measures to speed it up.

- Would be reasonable to add more logs within `prepareUpgrade`?
- Is my concern valid - as in, is correct my assumption that this procedure should be faster?
- The warning `Unable to cancel request for *exec.roundTripper` suggests that maybe there is something timing out/failing to request in some step, and that could be the bottleneck?

---

Metadata:

Output of `helm version`: `v3.5.1`
Output of `kubectl version`: `Major:"1", Minor:"18", GitVersion:"v1.18.15"`
Cloud Provider/Platform:  EKS cluster

---
Other than that I would just like to say I am starting with Helm and loving it, thanks for the great work here.

**Comment by bacongobbler** [comment]
`--atomic` sets the `--wait` flag, which waits until all resources are ready. Depending on how long it takes for said services to come online, 3 minutes is not a whole lot of time.

**Comment by fabriciojs** [comment]
@bacongobbler thank you for the response!

We dug a bit further and identified a bottleneck - CPU. This `helm upgrade` was taking place in a container deployed in our K8S cluster, in a deployment that didn't have reserved capacity on that service. When we changed it to explicitly reserve 2 vCPUs we gained **more than 60%** on that initial ~3 minutes time.

We believe this is related to other reports on slowness in some commands like `helm ls -A` (we could confirm that in our old container with no CPU reservation, this took really long due to CPU exhaustion). Now after resources are reserved it takes a couple of seconds.

Is that some `json.Unmarshall` performance issue? Please let me know if you have any work in progress or investigation on this intensive resource usage, some profiling; I would be glad to try helping out given the right directions.

Thank you again!

**Comment by bacongobbler** [comment]
Nope! No profiling work is planned at this time. Feel free to post your findings and report back if you can determine a root cause.

**Comment by fabriciojs** [comment]
For the record - I started digging further into the elevated CPU usage.

Listing releases is indeed a CPU intensive task given that:

- My driver is `*driver.Secrets`
- Kubernetes API will fetch and parse the JSON secrets - decode of the full k8s.io `v1.Secret` struct (presumably using JSON, and not Protobuf)
- After that, Helm will parse each of the returned secrets by `decodeRelease` which will:
    - Decode base64 serialized string
    - G-unzip the decoded string
    - json.Unmarshall the resulting slice of bytes

I generated the profiling of a `helm ls -A` on my cluster from my Mac Pro 2018 (i7) - it shows the CPU weight to list releases: 
[cpu-profile-helm-ls-A.pdf](https://github.com/helm/helm/files/5908832/cpu-profile-helm-ls-A.pdf)

The command returns 110 releases. The total number of secrets parsed by `decodeRelease` is **395** with lengths ranging from 2KB to 800KB (Base64 encoded), with a lower average. All the base64 encoded `len(data)` received by `decodeRelease`:

<details><summary>View all the `len(data)`</summary>
<p>
```
1.58 KB
613.69 KB
102.96 KB
102.98 KB
102.89 KB
11.08 KB
11.09 KB
5.77 KB
5.79 KB
5.80 KB
5.79 KB
5.79 KB
4.14 KB
4.16 KB
4.15 KB
3.22 KB
3.23 KB
3.26 KB
3.25 KB
2.00 KB
2.01 KB
2.01 KB
2.02 KB
2.02 KB
2.02 KB
2.02 KB
2.02 KB
2.00 KB
2.00 KB
1.97 KB
1.99 KB
2.02 KB
2.32 KB
2.33 KB
2.32 KB
2.28 KB
2.28 KB
2.35 KB
2.32 KB
2.31 KB
2.32 KB
2.32 KB
2.32 KB
2.31 KB
2.31 KB
2.34 KB
2.32 KB
6.26 KB
6.26 KB
6.25 KB
6.25 KB
6.25 KB
6.25 KB
6.25 KB
6.26 KB
6.61 KB
6.61 KB
2.05 KB
2.05 KB
2.05 KB
2.05 KB
2.05 KB
2.05 KB
2.05 KB
2.34 KB
2.34 KB
2.34 KB
2.92 KB
2.95 KB
2.87 KB
3.10 KB
2.93 KB
2.96 KB
2.95 KB
2.95 KB
2.80 KB
2.97 KB
2.80 KB
2.83 KB
2.82 KB
2.82 KB
2.82 KB
2.82 KB
2.86 KB
2.92 KB
3.10 KB
2.92 KB
2.95 KB
2.94 KB
2.94 KB
3.14 KB
2.82 KB
3.00 KB
2.82 KB
2.85 KB
2.84 KB
2.84 KB
2.84 KB
2.86 KB
3.12 KB
2.95 KB
2.98 KB
2.96 KB
2.96 KB
2.84 KB
3.10 KB
2.93 KB
2.96 KB
2.95 KB
2.95 KB
2.92 KB
3.12 KB
2.95 KB
2.97 KB
2.96 KB
2.96 KB
3.14 KB
2.86 KB
2.93 KB
3.10 KB
2.93 KB
2.96 KB
2.95 KB
2.95 KB
2.85 KB
2.87 KB
2.86 KB
3.09 KB
2.92 KB
2.95 KB
2.94 KB
2.94 KB
2.87 KB
2.89 KB
3.14 KB
2.92 KB
3.02 KB
2.86 KB
2.89 KB
2.88 KB
2.88 KB
3.14 KB
2.84 KB
3.10 KB
2.93 KB
2.95 KB
2.94 KB
2.95 KB
3.08 KB
2.91 KB
3.10 KB
2.94 KB
2.96 KB
2.96 KB
2.96 KB
2.86 KB
2.88 KB
2.98 KB
2.88 KB
2.90 KB
2.84 KB
3.10 KB
2.94 KB
2.96 KB
2.95 KB
2.95 KB
2.91 KB
2.94 KB
2.91 KB
3.03 KB
2.86 KB
2.88 KB
2.88 KB
2.88 KB
2.92 KB
3.03 KB
2.86 KB
2.89 KB
2.88 KB
2.88 KB
2.86 KB
3.10 KB
2.93 KB
2.95 KB
2.95 KB
2.95 KB
2.86 KB
2.88 KB
2.94 KB
2.96 KB
3.26 KB
3.16 KB
3.14 KB
2.92 KB
2.95 KB
2.87 KB
2.89 KB
3.16 KB
2.84 KB
3.04 KB
2.88 KB
2.90 KB
2.90 KB
2.90 KB
3.15 KB
3.14 KB
3.15 KB
2.91 KB
2.94 KB
2.86 KB
3.04 KB
2.88 KB
2.87 KB
2.90 KB
2.89 KB
2.89 KB
3.15 KB
3.14 KB
3.22 KB
2.86 KB
3.04 KB
2.87 KB
2.90 KB
2.88 KB
2.89 KB
2.81 KB
2.83 KB
2.86 KB
3.04 KB
2.86 KB
2.89 KB
2.88 KB
2.89 KB
2.86 KB
2.87 KB
2.87 KB
2.93 KB
2.94 KB
3.11 KB
2.94 KB
2.96 KB
2.96 KB
2.96 KB
2.95 KB
2.97 KB
3.15 KB
3.14 KB
3.10 KB
3.11 KB
2.82 KB
3.10 KB
2.93 KB
2.96 KB
2.95 KB
2.95 KB
3.16 KB
2.93 KB
2.96 KB
2.95 KB
6.79 KB
6.80 KB
7.21 KB
7.21 KB
7.21 KB
7.22 KB
7.22 KB
7.22 KB
7.22 KB
7.22 KB
1.98 KB
2.00 KB
2.56 KB
2.59 KB
2.59 KB
2.59 KB
2.58 KB
5.36 KB
5.37 KB
5.37 KB
5.36 KB
5.37 KB
5.36 KB
4.93 KB
4.93 KB
4.94 KB
5.26 KB
1.86 KB
1.91 KB
5.39 KB
5.39 KB
5.39 KB
5.40 KB
5.40 KB
5.40 KB
4.70 KB
4.83 KB
4.84 KB
4.69 KB
4.92 KB
4.95 KB
4.94 KB
5.25 KB
5.28 KB
5.43 KB
5.43 KB
5.43 KB
5.45 KB
5.28 KB
43.20 KB
43.30 KB
43.22 KB
43.32 KB
44.21 KB
77.51 KB
16.26 KB
17.84 KB
62.48 KB
12.57 KB
12.57 KB
12.57 KB
12.57 KB
12.57 KB
12.57 KB
12.57 KB
12.57 KB
12.57 KB
12.60 KB
3.35 KB
34.03 KB
34.52 KB
2.98 KB
27.94 KB
37.40 KB
25.33 KB
25.40 KB
808.08 KB
808.82 KB
808.98 KB
809.03 KB
809.25 KB
809.02 KB
809.11 KB
22.10 KB
15.94 KB
13.52 KB
10.48 KB
21.28 KB
21.79 KB
10.50 KB
12.74 KB
12.74 KB
12.74 KB
12.73 KB
12.73 KB
12.74 KB
12.74 KB
12.74 KB
12.74 KB
12.73 KB
4.94 KB
4.95 KB
5.05 KB
4.95 KB
5.42 KB
4.96 KB
5.08 KB
4.95 KB
4.77 KB
4.81 KB
4.85 KB
4.79 KB
4.90 KB
4.89 KB
4.95 KB
5.03 KB
4.81 KB
4.82 KB
4.88 KB
4.84 KB
4.82 KB
4.98 KB
4.94 KB
5.12 KB
5.18 KB
5.05 KB
4.97 KB
4.96 KB
4.91 KB
4.94 KB
4.92 KB
2.54 KB
11.88 KB
5.14 KB
65.75 KB
66.62 KB
```
</p>
</details>

---

Tomorrow I will try profiling my actual `helm upgrade` mentioned in the beginning to confirm the cause is the same, but having checked the API calls used by `prepareUpgrade` fetching the release history, that is a safe bet at this point.

**Comment by fabriciojs** [comment]
@bacongobbler given the data gathered above, it aligns with reports of degraded performance as the cluster have many and many releases. With time, everyone will face it.

I can only **brainstorm** some fun measures:

- Since `k8s.io.v1.Secret` got annotations for Protobuf make it use that instead of JSON (not sure how, or if possible)
- As for Helm `driver.Secrets` what comes to mind:
    - Should I be using some other driver?
    - For json.Unmarshall on `driver.Secrets`, could we optimize the target struct to have only the strict necessary fields for usage in that case, with `json.RawMessage` for lazy parsing slices if needed.
    - Could we think about changing serialization to Protobuf or Cap'n'Proto or something else? Or maybe BSON, anything supposedly cheaper?
    - Can we think about changing compressing algorithm to snappy or something else putting performance over compression ratio? (or maybe even something funkier like smaz or other specialist algorithms)


Overall the storage of Helm's owned secrets in the cluster could be improved for a better preliminar filter, reducing the total number of records that we need to parse for any situation (like in the `prepareUpgrade` where we get the history to then get the last deployed status). Maybe having specific secrets to "index" utils like this could solve it already.

**Comment by fabriciojs** [comment]
Hello @bacongobbler - I would just like to get to your attention a small implementation I made attempting to help in another issue:

Diff: https://github.com/helm/helm/compare/v3.5.2...kool-dev:v3.5.2-profiling?expand=1

Issue context: https://github.com/helm/helm/issues/9322#issuecomment-783452212

Do you think this profiling feature is worth being promoted to mainline with a new `--debug-profile` flag option? I am guessing it will be very helpful for everyone complaining about performance.

**Comment by benoittgt** [comment]
Hello

I would be interested to return at the end a profile log line with the cumulated time of few operations, like the time waited if you had set `--wait`. The time spent waiting deletion. For example `"wait 465ms to deleted 8 ressources", etc.

I know they could be many factors but I would like to better understand why our upgrade are sometimes much slower, even when we remove `--wait` flag.
