### ISSUE TITLE
Is it possible to reuse the same uninstall client for different namespaces?

### ISSUE THREAD

**Issue by lyxk** [helm/helm#9305]
`helm version`: v3.4.0
`kubectl version`: Client v1.19.3, Server v1.19.1
`golang version`: 1.13

I am trying to programmatically delete the helm releases from different namespaces. Currently, I'm using the following code snippet to perform this task.

```golang 
kubeConfig := kube.GetConfig("myKubeConfigFile", "", "")
helmDriver := os.Getenv("HELM_DRIVER")
logfunc := func(format string, v ...interface{}) {
	log.Printf(format, v)
}
for _, rel := range releases {
    actionConfig = new(action.Configuration)
    err := actionConfig.Init(kubeConfig, rel.Namespace, helmDriver, logfunc)
    uninstallClient := action.NewUninstall(actionConfig)
    uninstallClient.Run(rel.Name)
}
```

In this way, I have to create a new action configuration and an uninstall client for every release.  

After reading thread #8269 I tried changing the namespace of the Kube client, as shown below:

```golang
kubeConfig := kube.GetConfig("myKubeConfigFile", "", "")
helmDriver := os.Getenv("HELM_DRIVER")
logfunc := func(format string, v ...interface{}) {
	format.Printf(format, v)
}

actionConfig = new(action.Configuration)
err := actionConfig.Init(kubeConfig, "", helmDriver, logfunc)
uninstallClient := action.NewUninstall(actionConfig)

for _, rel := range releases {
    if kc, ok := actionConfig.KubeClient.(*kube.Client); ok {
        log.Printff("Updated KubeClient's namespace to %q\n", namespace)
        kc.Namespace = namespace
        uninstallClient.Run(rel.Name)
    } else {
        log.Errorf("Failed to update KubeClient's namespace to %q. Expected \"actionConfig.KubeClient\" to be \"*kube.Client\", got \"%T\". Release will be deployed to the \"default\" namespace.\n", namespace, hc.actionConfig.KubeClient)
    }
} 
```

I got the following error:
`uninstall: Failed to purge the release: get: failed to get \"sh.helm.release.v1.my-apple-chart.v1\": an empty namespace may not be set when a resource name is provided"`

I am wondering if there is a way to create one action configuration and uninstall client and reuse them to delete releases from different namespaces.

**Comment by bacongobbler** [comment]
I'm unsure what would be causing the issue. Let us know what you find out.

**Comment by lyxk** [comment]
@bacongobbler I found that the error is caused by the `purgeRelease` function which uses the release store for deletion:
https://github.com/helm/helm/blob/46d80f68c11d8107b688b9c8299fa02bccba312f/pkg/action/uninstall.go#L154-L161
 I'm not sure if this is issue is caused by the namespace getting baked into the release store on init.
https://github.com/helm/helm/blob/46d80f68c11d8107b688b9c8299fa02bccba312f/pkg/action/action.go#L369-L379
https://github.com/helm/helm/blob/46d80f68c11d8107b688b9c8299fa02bccba312f/pkg/action/action.go#L416
If so, is it possible to reuse the same uninstall client and action config to uninstall releases from different namespaces?
