### ISSUE TITLE
helm chart pull returns ref may only contain a single colon character (:) unless specifying a port number

### ISSUE THREAD

**Issue by eaf-josephportello** [helm/helm#9307]
Output of `helm version`:

version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}

Output of `kubectl version`:

Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-16T20:43:08Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Any

Issue:

**Running:** 

helm chart pull https://charts.yugabyte.com/yugabytedb/yugabyte:2.5.1 

**Returns the error:** 

Error: ref may only contain a single colon character (:) unless specifying a port number

This is happening in the cluster, locally, etc... Am I doing something incorrectly?

**Comment by bacongobbler** [comment]
`helm chart pull` cannot pull from a chart repository. It can only pull from an OCI registry.

From https://charts.yugabyte.com/:

> Add the charts repository by running the below command

>     helm repo add yugabytedb https://charts.yugabyte.com


Because charts.yugabyte.com is a chart repository, use `helm fetch` instead.

**Comment by eaf-josephportello** [comment]
Thanks, the issue I am experiencing is related to how ArgoCD pulls them down, this is the command it is attempting to run. I will open an issue with them. Thanks!
