### ISSUE TITLE
Range Until function with set licences keys

### ISSUE THREAD

**Issue by kenotsolutions** [helm/helm#9308]
Hi,
Let's assume we have several licences keys in the values.yaml file and we would like to create configMaps from them. Can we do that with range function? If so How?
Something like that?
values.yaml
```
TestLicences:
    0Lic: "abc"
    1Lic: "def"
    2Lic: "geh"
    3Lic: "fab"
```

configMap
```
apiVersion: v1
data:
  {{- range $i := until ( atoi .Values.TestLicences.count() ) }}
  {{$i}}Lic: {{.Values.TestLicences.{{$1}}Lic |indent 2 }}
  {{- end }}  
kind: ConfigMap
metadata:
  name: licenses
```

Thanks in advance

**Comment by bacongobbler** [comment]
https://golang.org/pkg/text/template/#hdr-Variables

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: licenses
data:
  {{- range $i, $license := .Values.TestLicences }}
  license-{{ $i}}: {{$license }}
  {{- end }}
```

Alternatively use `toYaml` If you just want to dump the data as is.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: licenses
data:
  {{ toYaml .Values.TestLicenses }}
```

**Comment by bacongobbler** [comment]
Examples can be found in the helm/charts repo. https://github.com/helm/charts/search?q=toyaml

Closing as answered.
