### ISSUE TITLE
Is lookup function working?

### ISSUE THREAD

**Issue by tahmmee** [helm/helm#9309]
Basic usage of `lookup` function is no longer returning an object.
```
namespace: {{ (lookup "v1" "Namespace" "" "") }}
```

renders as empty map:
```
namespace: map[]
```

Used to return results in 3.1.  Has this changed? 

Output of `helm version`: **3.4.x and 3.5.1**
version.BuildInfo{Version:"v3.5.1", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.7"}

Output of `kubectl version`: **1.18**
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:56:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15", GitCommit:"73dd5c840662bb066a146d0871216333181f4b64", GitTreeState:"clean", BuildDate:"2021-01-13T13:14:05Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AKS

**Comment by mattfarina** [comment]
I just tested the `lookup` function and it is working.

How are you using the `lookup` function? It only works when using commands that interact with a cluster. For example, it does not work with `helm template` which is designed to work without being connected to a cluster.

**Comment by tahmmee** [comment]
Ah thanks that's what it is!  Tried `helm upgrade` with `--dry-run --debug`
