### ISSUE TITLE
Helm package does not generate a valid Chart.yaml file

### ISSUE THREAD

**Issue by dudicoco** [helm/helm#9311]
Hi,

We have a chart with a dependency on another chart. We pre-populate the charts dir within the dependant chart as follows:
```
├── Chart.yaml
├── charts
│   └── base
│       ├── Chart.yaml
│       └── files -> ../../files
├── files
│   └── example-config
│       └── example.yaml.tpl
├── requirements.yaml
├── values.yaml
```

We do this in order to be able to read the files dir via a symlink.

`./charts/base/Chart.yaml` contains the following:
```
apiVersion: v1
appVersion: "1.0"
description: base Helm chart for Kubernetes
name: base
version: 1.0.0
```

We need this file to preexist, otherwise helm package will fail.

When running `helm package -u .` the chart package version from the `requirements.yaml` file gets download into the `./charts/base` dir and the `./charts/base/Chart.yaml` file gets overridden with the correct version, for example:
```
apiVersion: v1
appVersion: "1.0"
description: base Helm chart for Kubernetes
name: base
version: 2.1.1
```

However, in some cases the file does not get overridden, which basically corrupts the chart and causes resources to get deleted from the cluster if the corrupted chart is deployed.

This happens randomly, sometimes the `Chart.yaml` gets overridden as expected, and sometimes it doesn't.

Output of `helm version`: `version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}`

**Comment by mattfarina** [comment]
This is an unusual setup so I am not immediately able to spot what's going on. I have questions.

- How many requirements are in the requirements.yaml file? Can you share that file?
- If you run `helm package --debug -u`, what do you see?
- Is the `./charts/base/Chart.yaml` being updated because Helm is updating packages or is there anything else going on here?
- Is this a public chart we can get a look at?

**Comment by dudicoco** [comment]
@mattfarina

```
$ cat requirements.yaml
dependencies:
  - name: base
    version: ^2.0.0
    repository: "@dy-helm"
    alias: example
```

```
$ helm package --debug -u .
walk.go:74: found symbolic link in path: /example/chart/charts/base/files resolves to /example/chart/files
walk.go:74: found symbolic link in path:/example/chart/charts/base/files resolves to /example/chart/files
Successfully packaged chart and saved it to:/example/chart/example-1.0.0.tgz
```

The `./charts/base/Chart.yaml` is being updated by Helm, no magic going on:
```
$ tar -xvf example-1.0.0.tgz
x example/Chart.yaml
x example/values.yaml
x example/.helmignore
x example/files/example-config/example.yaml.tpl
x example/requirements.lock
x example/requirements.yaml
x example/values_example.yaml
x example/charts/base/Chart.yaml
x example/charts/base/files/example-config/example.yaml.tpl
x example/charts/base/Chart.yaml
x example/charts/base/values.yaml
x example/charts/base/templates/NOTES.txt
x example/charts/base/templates/_helpers.tpl
x example/charts/base/templates/apiservice.yaml
x example/charts/base/templates/application.yaml
x example/charts/base/templates/clusterrole.yaml
x example/charts/base/templates/clusterrolebinding.yaml
x example/charts/base/templates/configmap.yaml
x example/charts/base/templates/cronjob.yaml
x example/charts/base/templates/daemonset.yaml
x example/charts/base/templates/deployment.yaml
x example/charts/base/templates/externalsecret.yaml
x example/charts/base/templates/hpa.yaml
x example/charts/base/templates/ingress.yaml
x example/charts/base/templates/pdb.yaml
x example/charts/base/templates/prometheusrule.yaml
x example/charts/base/templates/role.yaml
x example/charts/base/templates/rolebinding.yaml
x example/charts/base/templates/service.yaml
x example/charts/base/templates/serviceaccount.yaml
x example/charts/base/templates/serviceheadless.yaml
x example/charts/base/templates/statefulset.yaml
x example/charts/base/templates/tests/pod.yaml
x example/charts/base/.helmignore

$ cat example/charts/base/Chart.yaml
apiVersion: v1
appVersion: "1.0"
description: base Helm chart for Kubernetes
name: base
version: 2.1.2
```

The chart is not public.

Let me know if you need any other information.

Thanks

**Comment by mattfarina** [comment]
@dudicoco Is the alias the same name as the parent chart? It is in your example and I'm wondering if it is actually that way.

**Comment by dudicoco** [comment]
@mattfarina yes.
