### ISSUE TITLE
3.5.1 gives segmentation fault, 3.5.0 works fine

### ISSUE THREAD

**Issue by JeroenVanOort** [helm/helm#9315]
We're using the [alpine/helm](https://hub.docker.com/r/alpine/helm) image to do deployments in Gitlab. Today I noticed that deployments are failing, with `Segmentation fault (core dumped)` as the message. Since nothing has really changed in our code, I suspected a new version of Helm (or the image) to be the problem. And indeed, when I lock the version of the image to 3.5.0, all  works just fine.

I'm afraid I don't have much debugging information to offer at this time. Just this: it concerns a `helm upgrade` command with the `--install` and `--atomic` options set. Other than that, there are just a bunch of `--set-string`'s.

**Comment by mattfarina** [comment]
Could you run `helm --debug -v 10 upgrade` to get more debugging information? Is there a backtrace or any other information you could provide?

The only difference between `3.5.0` and `3.5.1` is the version of Go used for building Helm. It was incremented one patch version for a security release. Any detail would be helpful.

**Comment by JeroenVanOort** [comment]
It seems that `--debug` doesn't add any output. And when I add `-v 10` (or `-v 1`), the command succeeds and there is no segfault. I did check that the output of `helm version` is the same each time:

`version.BuildInfo{Version:"v3.5.1", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.7"}`

**Comment by technosophos** [comment]
You might consider filing a bug with the Alpine project that maintains the image.

**Comment by JeroenVanOort** [comment]
Haven't had the problem since 3.5.2
