### ISSUE TITLE
Helm dep up takes a very longtime

### ISSUE THREAD

**Issue by ngarg-panw** [helm/helm#9321]
My requirement is just to make sure that helm templates are of correct format. I am running "helm lint" but if dependencies are there, it needs them to validate the helm templates.
When i run "helm dependencies update" command, it takes forever with only 3 dependencies. Its almost like hanged.
This is the result i get after waiting for 15 mins and its still in progress:
```
efk > ../../.helm.versions/helm_3.5.0 dependency update
load.go:120: Warning: Dependencies are handled in Chart.yaml since apiVersion "v2". We recommend migrating dependencies to Chart.yaml.
Getting updates for unmanaged Helm repositories...
...Successfully got an update from the "https://charts.helm.sh/stable" chart repository
...Successfully got an update from the "https://charts.helm.sh/stable" chart repository
...Successfully got an update from the "https://charts.helm.sh/stable" chart repository
```

Is there a way i can just validate the templates without dependencies or to expedite the response of the command.

**Comment by fabriciojs** [comment]
@ngarg-panw just for the sake of gathering information - can you tell if during this *hanged* state the helm process is using a lot of either CPU or memory? Can you check the response time/routing to `https://charts.helm.sh/stable`?

**Comment by technosophos** [comment]
There is not enough information for us to troubleshoot this. But you might try turning on Helm's verbose output with `--debug` to see where it is actually "hanging."

It is not possible to validate templates without dependencies because dependencies must be resolved (and their templates compiled) before the template engine can be run. This, in turn, is because templates can call each other across dependencies.

**Comment by Aransh** [comment]
Having the same issue now, it's taking a long time and is taking substantial CPU (shows up as 143%), causing my CI build to fail...

**Comment by Aransh** [comment]
@fabriciojs Having the same issue now, it's taking a long time and is taking substantial CPU (shows up as 143%), causing my CI build to fail...
