### ISSUE TITLE
Helm upgrade allocates insane amount of memory

### ISSUE THREAD

**Issue by chrisvdb** [helm/helm#9322]
Goal was to upgrade Prometheus which we installed on EKS using Helm. I ran the following command:

```
# helm upgrade prometheus . -n monitoring
Killed
```

This allocated ~11.7GB of memory before it crashed (or got killed). Retrying yields the same result.

System information:

Output of `helm version`: version.BuildInfo{Version:"v3.5.1", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.7"}

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-17T02:13:01Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS EKS

**Comment by chrisvdb** [comment]
I tried `helm --debug -v 10 upgrade . -n monitoring` to get some more information, but the only output was:

`$ helm --debug -v 10 upgrade prometheus . -n monitoring
I0204 16:31:01.253173   31534 loader.go:379] Config loaded from file:  /home/chrisvdb/.kube/config
I0204 16:31:01.253846   31534 loader.go:379] Config loaded from file:  /home/chrisvdb/.kube/config
Killed
`

**Comment by mattfarina** [comment]
Thanks for using `--debug -v10` and sharing the results. That really helps.

You may know this but `-v 10` tells Kubernetes logging to provide extra information. This is for work inside of Kubernetes libraries/packages that Helm uses.

The two log entries you have are from Kubernetes packages. There should be more from these packages for things like certs. This leads me to wonder if the issue is somewhere in the kubernetes packages or interaction with kubernetes.

I'm unable to reproduce the problem, unfortunately.

**Comment by chrisvdb** [comment]
Any ideas on how I could get more information to debug the issue?

Kubernetes itself has been working perfectly fine thus far.

**Comment by fabriciojs** [comment]
@chrisvdb your scenario here seems similar to my performance issues - I started debugging it and placed some findings here (https://github.com/helm/helm/issues/9304#issuecomment-771378885)

I guess would be great to have some `--profile` hidden flag or in a debug build that could allow us easily to obtain such information, so you will be able to see where all those resources are being allocated. My bet is that secrets parsing is to blame, but we need to profile to verify it.

How long does it take before it crashes?

Let me know if you would like to attempt profiling it and I may give you a hand.

**Comment by chrisvdb** [comment]
@fabriciojs happy to help debug...

Note that I have a very small cluster (3 nodes, 10-20 pods, 5-10 services, handful of users). So, would be surprised if it's the same issue!

I think the crashing is purely related to memory usage. The time it takes before a crash varies... from 30 seconds to a few minutes (perhaps varies because of download speed or caching).

**Comment by chrisvdb** [comment]
Tested again with v3.5.2 and got the same result. Helm was killed after allocating 11+GB of memory.

Anybody any idea on how to get useful debugging data? ```--debug -v10``` does not provide any usable insights.

**Comment by chrisvdb** [comment]
hi @fabriciojs that was very helpful! Please find the resulting profile data attached: [profile-data.zip](https://github.com/helm/helm/files/6023530/profile-data.zip). I unfortunately did not manage to generate the PDFs.

Please note:

- behavior between your Helm version and the standard Helm version was slightly different... normally Helm gets killed after 30s to a few min, but your version ran for 10+ min (and my laptop was even less usable during that time)
- you mentioned that profile files would be generated every 2s, but only ~30 were generated in 10+ min

**Comment by fabriciojs** [comment]
@chrisvdb great!

here is the PDF for the 30th generated: 
[mem-profile-chrisvdb-30.pdf](https://github.com/helm/helm/files/6023674/mem-profile-chrisvdb-30.pdf)

The output here was different than what I expected (that was happening on my case, loading secrets was a consuming too much resources).

The vast majority os memory in your case was coming from this: https://github.com/helm/helm/blob/master/pkg/chart/loader/directory.go#L47-L120

In your case it seems there is some very large file in your chart local directory, that is not in `.helmignore`. Please can you take a look at the current folder for large files? And make sure that they are in the proper local, and it really needs to be there?

```
du | sort -nr | head
```

See, `helm upgrade` will attempt to load into memory every file in the current working directory as it assumes they will all be read/parsed to actually deploy the Chart.

Maybe you have some local chart, cloned from somewhere, with a large `.git` history folder; or maybe there is a recursive symlink causing an infinite loop (although the code seems to verify for regular files only, so this last option probably could not happen).

**Comment by chrisvdb** [comment]
That was very useful and solved my problem... thank you!

Root cause: I misunderstood how ```helm upgrade``` works... I assumed that ```helm upgrade prometheus . -n monitoring``` would download the latest helm chart from the repo it was originally installed from and upgrade the cluster. Instead it seems to expect the chart to be in the working directory.

When I run the command in my homedir with ~800G in ~2M files Helm does not throw an error, but simply consumes that much memory that it gets killed by the OS.

Somehow this behavior could probably be improved... can I leave it up to you to decide if this issue should be closed or kept open for UX improvement?

**Comment by fabriciojs** [comment]
@mattfarina any history on this - people running helm from within an inadverted folder? Maybe add a counter and a throttle on the eager files reading/loading to indicate the problem, at least?

**Comment by bacongobbler** [comment]
Any enhancements/bugfixes to the project are most welcome. Please feel free to open a PR to improve this behaviour.

**Comment by etlfg** [comment]
> @mattfarina any history on this - people running helm from within an inadverted folder? Maybe add a counter and a throttle on the eager files reading/loading to indicate the problem, at least?

I ran a forked chart and put garbage in it (my bad) as you can see :
```
❯ du -sh *
4.0K    Chart.yaml
4.0K    OWNERS
12K     README.md
8.0K    ci
9.7G    data
4.0K    requirements.lock
4.0K    requirements.yaml
60K     templates
16K     values.yaml
```

The solution here is obvious : getting rid of that intrusive folder or adding it to a helmignore file.
Thanks to @fabriciojs for helping @chrisvdb to profile It's problem as I encountered the same.
