### ISSUE TITLE
feature request: --generate name from a template

### ISSUE THREAD

**Issue by moosecanswim** [helm/helm#9327]
It would be nice to be able to generate a release name from a specified template.  Ex: my chart is `firetruck` and i would like the release name to be of the form `firetruck-<randomly generated>`.

**Comment by bacongobbler** [comment]
`helm install --name-template` already exists for this purpose. It's been there since Helm 2.0.0 if I'm not mistaken.

For example: 

```
helm install --name-template "{{ printf "%s-%s" . (randalphanum 10) }}"
```

**Comment by moosecanswim** [comment]
You sir are great! Thanks!!!
