### ISSUE TITLE
For more information section only uses examples

### ISSUE THREAD

**Issue by rd-matthias-jambor** [helm/helm#9329]
Hey folks,

the security advisory at https://github.com/helm/helm/security/advisories/GHSA-c38g-469g-cmgx has a section called "For more information".
The repo link  and the email address both points to example addresses.
A solution could be to delete that question or to fill in valid addresses.

I do not have further questions or comments about the advisory.

Thanks for your work,
Matthias

**Comment by technosophos** [comment]
Thanks for the heads-up. We have to wait until the CVE is issued before we can update that document. In the meantime, the SECURITY doc for the project is the best source of information. https://github.com/helm/community/blob/master/SECURITY.md

**Comment by technosophos** [comment]
The CVE was just issued and the notice was unlocked. So I have fixed the document.

Thanks again.
