### ISSUE TITLE
reuse configmaps between multiple helm chart releases

### ISSUE THREAD

**Issue by gowrisankar22** [helm/helm#9330]
I want to reuse config maps between multiple helm chart releases. After googling i got to know about the annotation "helm.sh/resource-policy": sharable but this not seem to work. Can you someone help here, how to make this work ?

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-sharable-configmap
annotations:
  "helm.sh/resource-policy": sharable

```

**Comment by fabriciojs** [comment]
@gowrisankar22 we have been using https://github.com/emberstack/kubernetes-reflector to achieve sharing or resources like you want. I am not familiar with Helm native support for it, but in case you don't find support on it, `kubernetes-reflector` may come to the rescue.

**Comment by technosophos** [comment]
The most common usage pattern is to control the config map with one chart (or via a bare manifest), and inject the name of the config map into a chart via Values.

**Comment by gowrisankar22** [comment]
@technosophos that's the only option I also assumed.  thanks for your opinion.

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!
