### ISSUE TITLE
Strange case of VAR being parsed in values.yaml correctly, but for the last case 

### ISSUE THREAD

**Issue by ondrej-ivanko** [helm/helm#9334]
Hi,

I noticed currently an unexplainable behavior of helm3 parsing VARIABLES in values.yaml.
Situation is this.
I have telegraf chart, for which I'm overrding values in different environments. The name of the environment is saved in ENVIRON variable in name_of_overrding_file.yaml.
example:
```
telegraf:
  env:
    - name: ENVIRON
      value: "name of environ"
    - name: HOSTNAME
      value: "${ENVIRON}-telegraf"
```
This either overrides or injects new values to values.yaml of the chart.
Deployment of this chart uses these definitions in values.yaml like this:
```
        env:
{{ toYaml .Values.env | indent 8 }}
```
I presume that these ENVIRON variables are created after the instance of the pod is deployed.
In name_of_overrding_file.yaml. I also have these key: values
```
url: "http://${ENVIRON}-influx:80"
url: "http://${ENVIRON}-kapacitor:9092"
url: "http://${ENVIRON}-kapacitor:9092"
url: "http://${ENVIRON}-redis:6379"
```
For some reason, the first three urls are parsed correctly like http://ENVIRON_VAR_VALUE-service:port.
The last one fails the parse to ENVIRON correctly and returns: 
`invalid character "{" in host name`
It's always the last one that fails the parsing no matter how many urls are there.

Can you help me with this please. It's possible bug.

Output of `helm version`:
```
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.1-34+e7db93d188d0d1", GitCommit:"e7db93d188d0d12f2fe5336d1b85cdb94cb909d3", GitTreeState:"clean", BuildDate:"2021-01-11T23:48:42Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
---

**Comment by technosophos** [comment]
Where are you seeing that failure message? Is that the output of Helm or is it coming from the container?

**Comment by ondrej-ivanko** [comment]
Hi Matt,

thanks for such a swift reaction. 

The error is displayed in the logs of the kubernetes pod. The telegraf app is sending it's debug logging information to STDERR.

I just discovered that if I remove this part of code from name_of_overrding_file.yaml:
```
    - name: HOSTNAME
      value: "${ENVIRON}-telegraf"
```
the ENVIRON variable is suddenly parsed correctly in all of the urls metioned above.
The error I was having might actually be Kubernetes related and might have to do something with how ENV variables are propagated/set during pod creation. I couldn't find any informating forbidding the syntax I used previously, where one env variable depended on value of the other. 

I cannot be sure thought if it's Kubernetes related.

**Comment by technosophos** [comment]
Okay. It makes sense that it would be related to Kubernetes. When it injects values into the pod, I am not sure what the order is there.

**Comment by bacongobbler** [comment]
Hi @ondrej-ivanko. Is there further information you'd like at this time, or do you have enough information here? Is there a particular action item we should address, or are you happy with the answers provided earlier?

**Comment by ondrej-ivanko** [comment]
Hello @bacongobbler. I didnt solve the problem. Right now, it' s not an issue for me, so I'm closing this issue.
