### ISSUE TITLE
Helm 2.17 deepCopy supported?

### ISSUE THREAD

**Issue by kevin-shelaga** [helm/helm#9336]
Is deepCopy supported with helm 2.17?

More specifically for rendering charts from Go.

```go
	helm2chartutil "k8s.io/helm/pkg/chartutil"
	helm2chartapi "k8s.io/helm/pkg/proto/hapi/chart"
	helm2renderutil "k8s.io/helm/pkg/renderutil"
```

Currently getting the following error, but same chart renders fine with Helm 3.5.2 packages

```sh
function \"deepCopy\" not defined
```

**Comment by yxxhero** [comment]
https://github.com/helm/helm/blob/a690bad98af45b015bd3da1a41f6218b1a451dbe/glide.yaml#L21-L22


In helm 2.17, It depend on github.com/Masterminds/sprig v2.20.0, In sprig v2.20.0, It has no  deepCopy function.

see it: https://github.com/Masterminds/sprig/blob/v2.20.0/dict.go

**Comment by kevin-shelaga** [comment]
@yxxhero Thank you very much, is there a way for me to bump this dependency? I am not referencing this package directly, so its used by helm 2.17 internally?

**Comment by yxxhero** [comment]
Yes,  its used by helm 2.17 internally.

**Comment by kevin-shelaga** [comment]
@yxxhero ok, thank you. So no real work around for this right now?

**Comment by yxxhero** [comment]
In helm v2.17 code, you can  change the depends version, and  rebuild  it.

**Comment by kevin-shelaga** [comment]
@yxxhero Thanks again, I really appreciate your help.
