### ISSUE TITLE
Helm does not validate release name during install, but validates it during uninstall

### ISSUE THREAD

**Issue by krish7919** [helm/helm#9339]
Output of `helm version`:
`helm.sh/helm/v3 v3.5.0` (from `go.mod`)

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Local

Scenario:

1. While writing a UT to test `helm install` and `helm uninstall` from my Go program, I repeatedly hit the error: `'uninstall: Release name is invalid: testNamespace-chart-name-id1-id2`.

2. The install went fine with no errors.

3. Looking at the source for `helm uninstall`, I see [here](https://github.com/helm/helm/blob/master/pkg/action/uninstall.go#L66-L68) that Helm validates the release name to [conform to the regex](https://github.com/helm/helm/blob/master/pkg/chartutil/validate_name.go#L30) `[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*`.

4. A similar check is present during an `upgrade` and `rollback`, but absent during an `install`.

5. I removed the camel-casing in my release name and things work fine.

Expected behaviour:

If the release name is invalid, an error should be encountered immediately while installing the release and not while uninstalling it.

**Comment by bacongobbler** [comment]
I was unable to reproduce the issue.

```
><> helm install testNamespace-chart-name-id1-id2 ./test-9339
Error: create: failed to create: Secret "sh.helm.release.v1.testNamespace-chart-name-id1-id2.v1" is invalid: metadata.name: Invalid value: "sh.helm.release.v1.testNamespace-chart-name-id1-id2.v1": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

In other words, Kubernetes could not create a Secret for the release ledger due to the invalid name.

Can you please provide a concrete test case to help confirm this bug?

**Comment by krish7919** [comment]
I will post an example soon, am busy with some other things since I moved past this; hang on for some time please :)

**Comment by krish7919** [comment]
> In other words, Kubernetes could not create a Secret for the release ledger due to the invalid name.

Do not use Kubernetes and use an in-memory storage drive. In your example, you are banking on kubernetes to do the name validation.

**Comment by krish7919** [comment]
I also think that this went unnoticed so far is because the chart.Name() is returned from the install function as a part of release.Release, whereas we take that as user input diring upgrade, rollback and delete.

**Comment by bacongobbler** [comment]
Okay, so this bug is present when handling storage drivers other than the default. Thank you for clarifying.

**Comment by mengjiao-liu** [comment]
I have submitted a PR to try to fix this.

/assign

**Comment by derTobsch** [comment]
bump!

**Comment by shashijais789** [comment]
Do we have fix for this?

**Comment by mengjiao-liu** [comment]
Can anyone look at this PR #9536? This has been sitting for a long time. I'm not sure who's responsible for this part.

**Comment by hickeyma** [comment]
Currently under review

**Comment by procheeseburger** [comment]
why is this closed? seems like its still an issue

**Comment by stroypet** [comment]
bump
