### ISSUE TITLE
Error: UPGRADE FAILED: no resource with the name "anything_goes" found (regression?)

### ISSUE THREAD

**Issue by furkanmustafa** [helm/helm#9340]
We had an extremely similar case of an error dating back to helm 2 ages. https://github.com/helm/helm/issues/3275

In our case, the "anything_goes" resource was a `CronJob`.

And same [solution suggested](https://github.com/helm/helm/issues/3275#issuecomment-594494212) there worked. rollbacking to the same version.

Output of `helm version`:
```
version.BuildInfo{Version:"v3.3.0-rc.1", GitCommit:"5c2dfaad847df2ac8f289d278186d048f446c70c", GitTreeState:"dirty", GoVersion:"go1.14.4"}
```

Output of `kubectl version`: 
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.13", GitCommit:"30d651da517185653e34e7ab99a792be6a3d9495", GitTreeState:"clean", BuildDate:"2020-10-20T16:22:33Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Azure AKS

**Comment by bacongobbler** [comment]
Hi @furkanmustafa. It's unclear how or what happened to cause this situation. In addition, it looks like you're using a pre-release candidate. Can you please test and verify using a known stable version of Helm 3, and please provide a test case so that we can investigate further. Thanks.

**Comment by furkanmustafa** [comment]
It happened in one of the team members setup. It is also unclear how this could happen. The same operation was being done lots of times with no problems, this time it happened randomly.

The scenario was like this;

1) `helm upgrade my-release-1 --set maintenance=true ...`; this removes/stop some workloads, including a CronJob.
2) some maintenance got done manually..
3) `helm upgrade my-release-1 --set maintenance=false ...`; this restores stopped workloads, and re-creates previously deleted CronJob.

In the step 3, CronJob resource was created successfully, but Helm kept saying "Error: UPGRADE FAILED: no CronJob with the name "xxxxxxxxxx" found". The release status was set to `failed`.

We couldn't understand anything out of this, and later on found the solution;

```sh
helm list # to check the current (failed) revision (which was 50)
helm rollback my-release-1 50 # not actually a "rollback", just applying the latest revision again.
```

this changed nothing on the cluster, and accepted the changes.

As you mentioned, this could be due to helm/kubectl versions (more likely the former). We will keep an eye on this and report back.
