### ISSUE TITLE
Helm template generate RoleBinding with wrong namespace in Gitlab CI

### ISSUE THREAD

**Issue by SaigyoujiYuyuko233** [helm/helm#9341]
Output of `helm version`: 
```
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"}
```

Output of `kubectl version`: 
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Local

When I use ``helm template -n namespace name chart`` to generate a k8s yaml file, I found the RoleBinding resources have wrong namespace using Gitlab CI.
![image](https://user-images.githubusercontent.com/39913604/107193334-b0f54700-6a29-11eb-95c0-27bcad0939f9.png)
Left one is manual generated
Right one is generate by Gitlab CI

#### Solution
I use a script to wrap the command up and add ``env -i`` before helm command
helm.sh
```bash
helm template -n namespace name chart
```
```bash
env -i bash helm.sh
```
Hope this can help people who have no idea what happend.
any help would be appreciated :)

**Comment by bacongobbler** [comment]
Hi @SaigyoujiYuyuko233. It looks as though this might be related to the chart you're using rather than Helm itself.

May I please ask that you provide a chart that demonstrates this behaviour? A test chart attached as a zip file would be great. Thanks!

**Comment by SaigyoujiYuyuko233** [comment]
> Hi @SaigyoujiYuyuko233. It looks as though this might be related to the chart you're using rather than Helm itself.
> 
> May I please ask that you provide a chart that demonstrates this behaviour? A test chart attached as a zip file would be great. Thanks!

Yeah! Thanks. I'm using chart for argo-cd in <https://github.com/argoproj/argo-helm> and there is no modification I made :)
