### ISSUE TITLE
Built in helm diff functionality

### ISSUE THREAD

**Issue by kfox1111** [helm/helm#9344]
Helm template being built in has proven quite useful.  I constantly use helm diff and its painful at times to get installed. Could the helm diff functionality please be included in helm itself?

**Comment by bacongobbler** [comment]
Please see https://github.com/databus23/helm-diff/issues/211.

**Comment by kfox1111** [comment]
Including the diff plugin implementation is one way to include the functionality into helm itself but not the only way. Re-implementing it is another. If its not possible for the helm-diff plugin team to come to a consensus on migrating the existing code, I don't think that should preclude the functionality from being implemented in helm itself. That would mean this issue should remain open?

**Comment by bacongobbler** [comment]
It would be a non-trivial effort to re-implement the work that the community's already done. Not to mention the amount of legal due diligence involved. We can't just grab code from others and claim it as our own.

That is why I'm suggesting you reach out to the maintainers of the helm-diff plugin.

**Comment by kfox1111** [comment]
I think the ball is rolling now. What would need to happen on the helm side to get a helm/helm-diff repo transfer going?
