### ISSUE TITLE
Helm dep update is not respecting the "version" stipulated in the requirements.

### ISSUE THREAD

**Issue by mdebarros** [helm/helm#9348]
Helm dep update is not respecting the "version" stipulated in the parent requirements file. 

Parent chart's requirement.yaml example:
```
- name: child-chart
  version: 1.0.1
  repository: "file://../child-chart"
  condition: child-chart.enabled
```

Child chart's chart.yaml example:
```
apiVersion: v1
description: child-chart
name: child-chart
version: 1.0.0
appVersion: "1.0"
```

When running `helm dep up`, the parent chart will include the child chart in the charts folder, i.e.

parent/charts/child-charts-1.0.0.tgz <-- This should not happen, and the `helm dep up` should respect the version stipulated in the requirements.yaml `v1.0.1` and thus should fail. When using helm v2.17.0, and helm v3.3.0, the `helm dep up` would fail in this manner.

When running `helm install parent`, the Installation will excluding the missing child-chart as there is no `parent/charts/child-charts-1.0.1.tgz` available. There is no way to easily identify if there is a missing dependency as the installation is "successful" even though one of the dependencies are missing.

Output of `helm version`:

Experienced this issues originally with v3.4.2:
```
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"dirty", GoVersion:"go1.15.5"}
```

Upgraded to latest stable via Brew and experienced same issue:
```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T18:49:28Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Rancher v2.4.4

**Comment by bacongobbler** [comment]
I can reproduce the same issue.

```
><> helm create test-9348
><> helm create child-chart
><> cd test-9348
><> cat Chart.yaml
apiVersion: v2
name: test-9348
description: A Helm chart for Kubernetes
type: application
version: "1.0.0"
appVersion: "1.16.0"
dependencies:
  - name: child-chart
    version: 1.0.1
    repository: "file://../child-chart"
```

With Helm 3.5.2:

```
><> helm dep up
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "mirantis" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Deleting outdated charts
```

And with Helm 3.0.0:

```
><> ./linux-amd64/helm dep update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "mirantis" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Save error occurred:  can't get a valid version for dependency child-chart
Deleting newly downloaded charts, restoring pre-update state
Error: can't get a valid version for dependency child-chart
```

@mdebarros were you able to determine what might've caused this change in behaviour? A link to a PR or a commit would be helpful to identify and investigate further.

**Comment by mdebarros** [comment]
> I can reproduce the same issue.
> 
> ```
> ><> helm create test-9348
> ><> helm create child-chart
> ><> cd test-9348
> ><> vim Chart.yaml
> ><> cat Chart.yaml
> apiVersion: v2
> name: test-9348
> description: A Helm chart for Kubernetes
> type: application
> version: "1.0.0"
> appVersion: "1.16.0"
> dependencies:
>   - name: child-chart
>     version: 1.0.1
>     repository: "file://../child-chart"
> ```
> 
> With Helm 3.5.2:
> 
> ```
> ><> helm dep up
> Hang tight while we grab the latest from your chart repositories...
> ...Successfully got an update from the "mirantis" chart repository
> Update Complete. ⎈Happy Helming!⎈
> Saving 1 charts
> Deleting outdated charts
> ```
> 
> And with Helm 3.0.0:
> 
> ```
> ><> ./linux-amd64/helm dep update
> Hang tight while we grab the latest from your chart repositories...
> ...Successfully got an update from the "mirantis" chart repository
> Update Complete. ⎈Happy Helming!⎈
> Saving 1 charts
> Save error occurred:  can't get a valid version for dependency child-chart
> Deleting newly downloaded charts, restoring pre-update state
> Error: can't get a valid version for dependency child-chart
> ```
> 
> @mdebarros were you able to determine what might've caused this change in behaviour? A link to a PR or a commit would be helpful to identify and investigate further.

@bacongobbler I will have a look and see what I can find/do.

**Comment by cndoit18** [comment]
I tried to fix it, please assign it to me.
