### ISSUE TITLE
helm migration is failing 

### ISSUE THREAD

**Issue by priyadesai23** [helm/helm#9352]
Output of `helm version`: 2.16.1

Output of `kubectl version`: v1.18.3+2cf11e2

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  Openshift 

Getting below error while migrating helm version helm 2 to 3 

2021/02/10 15:05:04 Release "amd-apigw-pre-requisites-stack" will be converted from Helm v2 to Helm v3.
2021/02/10 15:05:04 [Helm 3] Release "amd-apigw-pre-requisites-stack" will be created.
2021/02/10 15:05:04 [Helm 3] ReleaseVersion "amd-apigw-pre-requisites-stack.v4" will be created.
Error: release: already exists
Error: plugin "2to3" exited with error

Is there any way to migrate only specific charts in given NS ?

Thanks
Priya

**Comment by bridgetkromhout** [comment]
Hi, @priyadesai23 - what version of Helm 3 are you migrating to? I ask because there have been similar errors in the past which may be resolved in a later version: https://github.com/helm/helm-2to3/issues/30
