### ISSUE TITLE
go get is failing

### ISSUE THREAD

**Issue by cyberbeast** [helm/helm#9354]
When running `go get helm.sh/helm/v3`, I am getting the following error,

`go: helm.sh/helm/v3@v3.5.2 requires
        github.com/deislabs/oras@v0.10.0 requires
        github.com/docker/distribution@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000`

Any ideas?

**Comment by bacongobbler** [comment]
https://github.com/helm/helm/blob/master/go.mod#L51-L54

**Comment by laszlocph** [comment]
The linked replace statements solved it for me.

Before that, `go get` was filling my 32gigs of memory and got killed :scream_cat:

**Comment by cyberbeast** [comment]
The replace statements fixed it for me too, but this can't be a final fix right?  Found more information here, for those who stumble here for the first time.

https://github.com/deislabs/oras/issues/211#issuecomment-775904476

**Comment by jawnsy** [comment]
I'm hitting this problem too, though interestingly v3.5.1 seems fine. I don't quite understand the problem or whether it's possible to fix this in Helm rather than in everyone downstream of it?

**Comment by bacongobbler** [comment]
It’s being fixed in https://github.com/helm/helm/pull/9492. It’s due to a downstream repository’s usage of docker/distribution.

**Comment by jawnsy** [comment]
@bacongobbler Awesome, thanks so much for the update!
