### ISSUE TITLE
Helm 3.5.2 is adding additional semver validation for chart versions compared to 3.5.2

### ISSUE THREAD

**Issue by lapellaniz** [helm/helm#9356]
Output of `helm version`: 

```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"c7c4f6ce84bf8535a782b67465807651a4bd649b", GitTreeState:"clean", BuildDate:"2021-01-18T09:49:05Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

Running `helm dep up` or `helm package ...` using v 3.5.2 v 3.5.1 now validates chart versions differently. Some older existing charts have 1.0.0.0 for example and fail. Others are said to be invalid but are skipped which is written to stderr and causes scripts to fail.

```sh
$ helm dep up
Hang tight while we grab the latest from your chart repositories...
index.go:339: skipping loading invalid entry for chart "couchbase-operator" "2.0.2-01" from https://couchbase-partners.github.io/helm-charts/: validation: chart.metadata.version "2.0.2-01" is invalid
index.go:339: skipping loading invalid entry for chart "couchbase-operator" "2.0.1-001" from https://couchbase-partners.github.io/helm-charts/: validation: chart.metadata.version "2.0.1-001" is invalid
```

**Comment by bacongobbler** [comment]
Hi @lapellaniz. This is expected as part of the security advisory shared last week with the release. See https://github.com/helm/helm/security/advisories/GHSA-c38g-469g-cmgx for more information.

**Comment by bacongobbler** [comment]
See also https://github.com/helm/helm/issues/9342.

**Comment by mattfarina** [comment]
@lapellaniz This is something we talked about while working on the security advisory.

Helm has always said the `version` MUST be semver. This is the chart version. For application versions there is the `appVersion` property that can be any format.

`2.0.2-01` and `2.0.1-001` are not valid semantic versions. In [the section on of the spec on prereleases](https://semver.org/#spec-item-9) it says:

> Numeric identifiers MUST NOT include leading zeroes.

The documented grammar does not allow for a leading 0, either.

**Comment by lapellaniz** [comment]
Closing issue as per the documented standard.
