### ISSUE TITLE
Customize output logs during install and upgrade - request

### ISSUE THREAD

**Issue by tstraley** [helm/helm#9359]
**Enhancement request:**

Currently, when executing `helm upgrade --install --atomic` (or `--wait`) there is no information or detail about what is going on, unless you go run kubectl commands elsewhere against the cluster. This is especially painful when running in CI/CD, as you cannot tell if the rollout is hung or progressing.

I have found that the `--debug` flag is incredibly useful for all of the relevant information one might want to have while an install or upgrade is rolling out: including the resources that helm is managing and whether it found any changes to make or not, as well as what resource(s) kubernetes is currently reporting as not ready, preventing successful completion of the task.

The issue with `--debug`, though, is that it also forces the entire manifest, as well as the user values and calculated values to be output to stdout. These items can often contain sensitive information (secrets) or are just overly verbose, which is also painful for CI/CD logs.

Unless I am mistaken, this means the current support for output logging during a rollout consists of:
1. Nothing, just a process that works silently and hopefully completes, and no info on what it changed
or
2. Every single detail anyone could want, including overly verbose and sensitive information, and things that can be grabbed other ways (eg. `helm get manifest`)

It would be fantastic to see helm get some better output options for different capability in this regard.

**Proposal ideas:**

These are just some options to base some discussions on.

1. A `--follow` flag which can be used with (or implies) `--wait` to signal that the output for resources being updated and resources waiting to become ready should be logged to stdout (effectively `--debug` without the extra cruft).
2. Split the current `--debug` output into `--debug` for the current logging that is actually `[debug]` logs following the useful things noted in option 1, and `--verbose` to include the other objects (values, manifests, etc.)
3. Revamp / revise the existing `--output` format options to be able to take a stringArray of output objects to include (eg. `--output debug,user_values,hooks,manifest`)
4. Flags to squash / remove the specific output objects (eg. `--suppress manifest,computed_values`)

I'd personally prefer options 1 or 2, but depending on implementation overhead or expected extensibility maybe you think other ideas are more worthwhile?

**Comment by mattfarina** [comment]
@tstraley Thank you for the request. This is not the first time I've heard this.

I think we need a [HIP](https://github.com/helm/community/tree/master/hips) to move this forward. It is not a straight forward request when we look at backwards compatibility in Helm v3 and in what we could do for Helm v4.

Overall, I like the high level idea.

**Comment by RyPeck** [comment]
@mattfarina anyone can write a HIP and submit via PR? I have an interest in this feature. Would first ask @tstraley if they'd prefer to turn this issue into one.
