### ISSUE TITLE
helm breaking frequently or not working with  tcp connection errors to kube api server

### ISSUE THREAD

**Issue by uvwild** [helm/helm#9360]
Since I can work normally with  kubectl, but observe a highly increased error rate with helm commands, in particular `helm uninstall` I am posting this issue.

`error copying from remote stream to local connection: read from tcp4 127.0.0.1:20001->127.0.0.1:58244: write tcp4 127.0.0.1:20001->127.0.0.1:58244: write: broken pipe
E0214 15:56:26.155481   57342 request.go:1011] Unexpected error when reading response body: read tcp 192.168.43.221:36548->80.158.3.109:443: read: connection reset by peer
`
Since I dont see such problems with kubectl itself. I would presume it is a timing issue in the local helm controller. Its a proper challenge to handle jittery connections well enough to maintain the connection.
And I am sure this has to do with my current particular network situation.

However, since the interaction issues are not evenly distributed between the different CRUD operations, there must be some variance in the code handling the connection delays. 
Jittery connections are more common than we would like. ( I just noticed moving out of the city)

So I am happy to have a look myself, Since I have currently the right test setup, I could examine the behaviour more closely. There should be some form of `CRUD controller `processing the objects read from the chart somewhere. That's where i would start looking. 

**But would need some pointers into the code to know where to start looking. ** 

Output of `helm version`:
Version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):    Gardener on OTC

**Comment by uvwild** [comment]
currently none of the helm commands are working.
I get a ping repsonse to the kube api server from 100-200 m.  that's not so bad.
The kubectl commands are still working.
is there any good way  to debug helm connections?

**Comment by mattfarina** [comment]
I'm sorry to hear about the issues you are having.

Helm is built using the same packages as kubectl to interact with the cluster. That includes packages like client-go and kubectl (the package that is used by the console app). Helm 3.5.2 is using the version of those packages from Kubernetes 1.20.2. It is also built against Go 1.15.7 (the latest security release version of Go).

It looks like you are using kubectl 1.19.2.

There are a couple things you can do to try to help narrow down the problem.

1. Use the `--debug -v 10` flags. These flags will tell helm to share debug output (that is the `--debug` flag) and for the underlying Kubernetes packages to share their debug output (`-v 10` is the most verbose level for them).
2. Try using Helm 3.4 which is based on Kubernetes 1.19 and try using kubectl 1.20. See if the issues go away in Helm for 3.4 and if there are kubectl issues present in 1.20. This will help narrow down if there was a version change.

**Comment by uvwild** [comment]
!Thanks!

**helm --debug -v 10 list**
But also with  helm v3.4.2, k8s client v1.19.2, k8s server v1.18.8
`E0216 22:48:02.236626  257897 request.go:1001] Unexpected error when reading response body: read tcp 192.168.43.221:50262->80.158.3.109:443: read: connection reset by peer`
Well now I know its the go `request.go` code around line 1000 :D

I compared this to the output of
**kubectl --v=8 get pods**

What I can see is that during the response for a  helm request often breaks into 
`E0216  connection reset `

my first Glimps into the logs show massively bigger http reponses for the helm commands, a possible explanation for less tolerance regarding a bad connection quality. 
But not that bad! Except for some sluggishness everything else works!
LTE line -  ping 100ms  / jitter 8ms Down14MB/s UP 10MB/s
Browser, streaming, terminal interaction....

However, this still feels like a bug since, I was told previously  that TCP does error checking and resends packets  in case of error. So why a full RESET of the tcp connection?
At this stage i would like to look into  the server side logs.  

`k logs -f kube-apiserver-c88fd7779-hwxgh -c kube-apiserver`
and found lots of TLS handshake errors:   https://github.com/kubernetes/kubernetes/issues/70411

and even a fix might come up  https://github.com/kinvolk/lokomotive/pull/297

**One explanation I found there is that the TLS error comes from how the load balancer are dealing with the TLS connections  in front of the clusters.**
I have to follow up on that. But it sounds like a possible explanation. Not a satisfying one though.
So this is still a bug until further confirmation of the causes. fairly enough not so much a helm bug.
When I find a better suited place I move it there.

**The repeatedly breaking connections are severely limiting my work with the cluster using helm. <br>Its not really an issue with kubectl commands! **
<br>Maybe because they are shorter and fit better into  transport  buffers on the way (e.g. LB)?!?
In that case its either an "unsupported" use of the API and the helm client should break down the command into smaller requests.
Or we have to wait for the kube-api code to solve the TLS issues ( which are cloud provider dependent)

**Comment by mattfarina** [comment]
Thanks for such detailed notes on your investigation, @uvwild

Helm does sometimes use large k8s resources and lists but they are all within the bounds and spec of Kubernetes API. If there is something we can do in helm to help fix this please let us know.

**Comment by uvwild** [comment]
To shed even more light on the failures:
When the network is more busy its impossible here  to use helm. 
When the network is not overloaded I can repeat the command N times to finally arrive at the server. and get the tcp connection reading my command.

`git` operations and `kubectl` operations are not limited locally - only helm.
One Exception - long log outputs from `kubectl logs`  - are  disconnected after a few pages.
 `kubectl exec -ti $pod -- bash`  is also doomed. 

**The workaround:**
Opening a terminal using SSH on a VM in the cluster and run it from there.
That connection will also not fast. But  its good enough to work.

I am surprised that nobody ever noticed that before.
 **It's a systematic failure**.
Or are all helm users working in places with fast cables????

**Comment by bacongobbler** [comment]
> Or are all helm users working in places with fast cables????

Quite likely. Helm's been in production for over 4 years. This is the first ask I've seen where the client is on a consistently slow connection.

If you can determine what might be causing the difference in behaviour, please do let us know.

**Comment by uvwild** [comment]
I am pretty convinced its about the  request size.
This size is the most significant difference to all the other remote  commands I am using. 
(including simple kubectl against the same api server)

And related to the TLS error I mentioned before

**Comment by uvwild** [comment]
I found those errors on many loadbalancer on my cluster. so its an provider/installation issue.
however, I could imagine a more robust implementation but this is not in this scope.
