### ISSUE TITLE
Atomic Parameter not working on Rerun of failed job 

### ISSUE THREAD

**Issue by widdix123** [helm/helm#9373]
Output of `helm version`: v3.4.2 

output for `helmfile version`: v0.136.0

Output of `kubectl version`: 1.18

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AWS EKS 1.17 

There is something strange about setting `atomic true` in helmfile .  On the first run when i set the image tag to an invalid tag (expecting the rollback to happen) , the deployment did not go through and upgrade failed . This seems to be the correct behaviour. 

```
  Error: UPGRADE FAILED: release fluent-bit failed, and has been rolled back due to atomic being set: timed out waiting for the condition
+ '[' 1 '!=' 0 ']'
+ echo 'Helmfile apply Failed!'
+ stop_ssh_tunnel
+ '[' -n '' ']'
+ ssh -p 422 -T -O exit -oControlPath=/home/app/.ssh_sock ********************************************************
Helmfile apply Failed!
Exit request sent.
```

However, when i reran the command again expecting the same behaviour as above . The helmfile went ahead with the deployment and deployed the invalid image making the pods in ImagePullBackOff .

```
UPDATED RELEASES:
NAME         CHART                                   VERSION
opa          ../releases/opa                           1.5.2
fluent-bit   ../releases/fluent-bit-kinesis-stream     0.1.0

+ '[' 0 '!=' 0 ']'
Success!
+ echo 'Success!'
+ stop_ssh_tunnel
+ '[' -n '' ']'
+ ssh -p 422 -T -O exit -oControlPath=/home/app/.ssh_sock ********************************************************
Exit request sent.
+ '[' false == true '
```

**Parameters in helmfile defaults:**

```
helmDefaults:
  timeout: 60
  createNamespace: false
  atomic: true
  cleanupOnFail: true
```

**Comment by mattfarina** [comment]
@widdix123 thanks for asking the question. Can you reproduce the issue with helm itself. When you aren't using helmfile?

**Comment by widdix123** [comment]
@mattfarina  - I checked the helm upgrade works as expected .  The rollback happens everytime 

```
helm upgrade --install --atomic cluster-autoscaler cluster-autoscaler my_rel test/ --namespace test-stage
```

**Comment by mattfarina** [comment]
If everything works as expected with Helm but the issue happens with helmfile I would try the helmfile issue queue.

**Comment by widdix123** [comment]
@mattfarina  - I think the rollback is happening for deployment but it does not rollback a deamoset or statefulset

**Comment by yacinelazaar** [comment]
@widdix123 Im also experiencing the same issue.
Rollbacks to successful releases fail. Also upgrades to the same state as a successful release (Im testing this by deploying with the right/wrong image name).
https://user-images.githubusercontent.com/1111396/115226871-a0d3a500-a107-11eb-8b17-28aad5fed44e.png
