### ISSUE TITLE
feat req: ability to set version and appVersion on helm chart save

### ISSUE THREAD

**Issue by krancour** [helm/helm#9382]
This is with respect to the experimental support for OCI registries.

When you package up a chart the old-fashioned way using `helm package`, there are `--version` and `--app-version` flags that can be used to specify that information.

There are no analogous options with `helm chart save`, so in practice, something like this needs to happen:

```console
$ sed -i "s/^version:.*/version: ${VERSION}/" Chart.yaml
$ sed -i "s/^appVersion:.*/appVersion: ${APP_VERSION}/" Chart.yaml
$ helm chart save ...
$ helm chart push ...
```

Obviously, that's pretty clunky and something like the following would be much more elegant:

```
$ helm chart save --version ${VERSION} --appVersion ${APP_VERSION} ...
$ helm chart push ...
```

**Comment by jdolitsky** [comment]
As part of [HIP 6](https://github.com/helm/community/blob/master/hips/hip-0006.md), the `helm chart` commands will soon be deprecated. Instead, the flow will be something like the following:

```
$ helm create mychart
Creating mychart

$ helm package mychart/
Successfully packaged chart and saved it to: /home/user/mychart-0.1.0.tgz

$ helm push mychart-0.1.0.tgz oci://example.com/some/root/namespace
The push refers to repository [oci://example.com/some/root/namespace/mychart]
ref:     oci://example.com/some/root/namespace/mychart:0.1.0
digest:  1b251d38cfe948dfc0a5745b7af5ca574ecb61e52aed10b19039db39af6e1617
size:    2.4 KiB
name:    mychart
version: 0.1.0
0.1.0: pushed to remote (1 layer, 2.4 KiB total)
```

Since the `helm package` supports custom version and app version, I believe what you're asking for will be supported.

**Comment by krancour** [comment]
@jdolitsky that looks fantastic!

Thanks for the prompt response.
