### ISSUE TITLE
helm on terraform for GKE

### ISSUE THREAD

**Issue by ggmartins** [helm/helm#9388]
hey there,

I'm trying to get terraform to install a helm chart after cluster provisioning. I know this may be outside helm's team scope, so wonder if there's anyone out there who had fixed a similar problem and willing to share. The problem seems to be terraform releasing the kube cluster in "RECONCILING" status (not RUNNING), with that, I think helm chart iac code is unable to "kick in" and finish chart installation. Code and output are at:

https://stackoverflow.com/questions/66148709/helm-release-terraform-install-has-no-effect-on-gke-cluster

Thanks a lot,
G

Output of `helm version`:
v3.4.2 (terraform provider 2.0.2)

Output of `kubectl version`:
v1.17

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

**Comment by mattfarina** [comment]
@ggmartins I would suggest using a newer version of Helm and kubectl. Neither of those have been supported in a long time (years). Did you share the right versions?

**Comment by ggmartins** [comment]
thanks, Matt, indeed, the version for helm is actually 3.4.2.

**Comment by bacongobbler** [comment]
Looking at your code sample, you requested for “binderhub” to be installed in the “kube-system” namespace, which would explain why `helm list` won’t pick it up.

Try using `helm list -all -namespace kube-system`.

**Comment by ggmartins** [comment]
@bacongobbler thanks, but that syntax is giving me:
`helm list -all -namespace kube-system`
```
Error: "helm list" accepts no arguments

Usage:  helm list [flags]
```
and `helm ls -all `
```
NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART	APP VERSION
(empty)
```

**Comment by bacongobbler** [comment]
Sorry, was on mobile. The correct invocation is `helm list --all --namespace kube-system`.

**Comment by bacongobbler** [comment]
Hi @ggmartins. Were you able to resolve your issue?

**Comment by ggmartins** [comment]
Yes, it totally did. Thanks a lot @bacongobbler !
