### ISSUE TITLE
Implement "helm watch" for development, specific layout to define state of whole cluster and "helm deploy" to recover full state of cluster

### ISSUE THREAD

**Issue by oleksiyp** [helm/helm#9389]
Hi,

I'd like to suggest a way to greatly improve productivity.
I put my helm charts in the following structure:
```
namespace1/
  chart1/
    templates
    Chart.yaml
    values.yaml
  chart2/
    ...
namespace2/
  chart3/
    ...
  chart4/
    ....
```
and set up a watch script to install them automatically upon change.

Also at work, I have a bit of a more advanced setup that allows not only to place charts in place 
but via a special file with reference "Helm.yaml" to download them from the registry.

I mean way to use chart from registry  following way:
```
namespace1/
  chart1/
    Helm.yaml 
    values.yaml
  chart2/
    ...
namespace2/
  chart3/
    ...
  chart4/
    ....
```

I also commit to git such a structure and apply it to clusters.

For specific clusters I have special values files:
```
namespace1/
  chart1/
    Helm.yaml 
    values.yaml
    values-all.yaml
    values-<cluster1>.yaml
    values-<cluster2>.yaml
  chart2/
    templates
    Chart.yaml
    values.yaml
    values-all.yaml
    values-<cluster1>.yaml
    values-<cluster2>.yaml
namespace2/
  chart3/
    ...
  chart4/
    ....
```

Here is a watch shell script you can try, it already makes development a lot more convenient:
```
time_buffered_uniq () {
   delay=$1
   prev_line=""
   while read line; do
       printf "%d %s\n" "$(date +%s)" "$line"
   done | while read ts line; do
       now=$(date +%s)
       if [[ "$prev_line" != "$line" ]]; then
         if (( now - ts < delay)); then
           sleep $(( delay - (now - ts) ))
           echo "$line"
         fi
       elif (( now - ts > delay)); then
         echo "$line"
       fi
   done
}

filter_junk() {
   while read path; do
     if [ -n "${path##*.swp}" ]; then
        echo $path
     fi
   done
}

split() {
   while IFS=/ read dot module artifact rest; do
     if [[ "$artifact" != "" ]]; then
       echo "$module $artifact"
     fi
   done
}

loop_helm_update() {
   while read module artifact; do
     echo "validating $module/$artifact"
     helm lint $module/$artifact > lint-$module-$artifact.log
     CODE=$?
     if [[ $CODE -eq "0" ]]; then
       kubectl create namespace $module 2> /dev/null
       echo "installing $module/$artifact"
       helm upgrade -i $module-$artifact -n $module $module/$artifact > $module-$artifact.log
     fi
   done
}

inotifywait -q --format "%w%f" -m -r -e close_write . |\
  filter_junk |\
  split |\
  time_buffered_uniq 3 |\
  loop_helm_update
```
(it uses 3 seconds debounce)

What I want to say that such a layout might be standardized.

Few cases:

1. clone repo & setup the whole cluster at one command, like `helm deploy`, no parameters needed
2. copy ready to use charts to the directory corresponding to namesapce and get automatically installed
3. `helm watch` development mode, no arguments, after run whatever you change on FS is automatically applied
4. recover the cluster in one go, so same `helm deploy`

Besides that, I use `helm template` and do kubectl with injecting/pruning labels "helm.artifact=<artifact>,helm.namespace=<namespace>", so I don't need zillions of configmaps for state (but that's another story)

**Comment by bacongobbler** [comment]
Hi @oleksiyp. Have you checked out the Helm Plugins guide yet? This seems like a good opportunity to write a plugin that will cater to your needs. It's unclear whether this workflow would be useful for others, which is why it'd be great to incubate this idea as a plugin and see if it gains traction with the broader Helm community before proposing it as a core feature.

https://helm.sh/docs/topics/plugins/

**Comment by bacongobbler** [comment]
I'd also suggest looking at [helmfile](https://github.com/roboll/helmfile) as the use case described here aligns well with that tool's use case.

**Comment by oleksiyp** [comment]
Yes, but helmfile already has incompatible layout and not really convenient. So we need "one more tool", which is hard

**Comment by mattfarina** [comment]
Thanks for the suggestion.

Helms primary purpose is as a package manager. Package managers service a purpose and deal with certain concerns. For example, if I use apt, yum, or zypper to install PostgreSQL onto a server I don't need to know the configuration setup, where to put files, or any of that for PostgreSQL. I can use it without being very experienced with the linux distro or the app.

Package managers are also really useful as building blocks. I remember years ago when I used Chef to manage apt packages running in a fleet of servers. The same idea could be used for Puppet and Ansible. Those 3 tools were a separate concern that used packages and package managers to do some of the work.

Helm is focused on package management and leaving the way they are managed in a cluster up to a layer above the package management. This is where helmfile, the flux helm operator, fleet, and other tools come in. Helm isn't trying to compete with those tools.

I like your layout. I know not everyone will and there are competing ideas. I would suggest it would be a great tool to build as a layer above Helm.

**Comment by oleksiyp** [comment]
Thanks, I understand all points, let's see if it is possible to craft plugin or tool.

**Comment by AssafKatz3** [comment]
Hi @oleksiyp,
I reached this issue since I have same problem. Helmfile doesn't support this use case (we already use it) and I couldn't find any useful plugin for it. Did you manage to find some tool for it?
Thanks,
Assaf
N.B. I tend to agree with the points here

**Comment by oleksiyp** [comment]
@AssafKatz3 not really. Have somewhere far in a personal backlog to create own tool

**Comment by AssafKatz3** [comment]
@debdutdeb We are still waiting for it, but it will probably take some time to implement, 10x
