### ISSUE TITLE
Helm is not creating the crds during helm install

### ISSUE THREAD

**Issue by saurabhumathe** [helm/helm#9395]
Helm install command is not creating the crds resources in chart and is resulting in below error, 

helm install demo ./ -f values.yaml 

**Error**: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "KubernetesEndpointResolver" in version "getambassador.io/v2", unable to recognize "": no matches for kind "Mapping" in version "getambassador.io/v2"]

Output of `helm version`: version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.15-gke.800", GitCommit:"fa6f8f9671a3ba4b1790bac677bb72b04204e8fc", GitTreeState:"clean", BuildDate:"2020-12-21T09:19:13Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  GKE

**Comment by mattfarina** [comment]
Can you share where the CRDs are being generated from? Are they in the _templates_ directory or the _crds_ directory? This is important because the templates are all sent to Kubernetes at the same time. But, CRDs need to be installed before any custom resources that use them are sent.

**Comment by saurabhumathe** [comment]
Hi,
Thanks for your response.
CRDs are located in  separate crds directory.

**Comment by mattfarina** [comment]
Is the chart you are using publicly available? I just tried the ambassador chart at https://artifacthub.io/packages/helm/datawire/ambassador and was unable to duplicate your error.

**Comment by saurabhumathe** [comment]
Thanks for confirmation.
we have customized charts for ambassador. It could be an issue in our customizations which we are checking in parallel. For now marking it closed,  If required I will reopen this.
