### ISSUE TITLE
Helm upgrade with install flag does not create CRDs like helm install

### ISSUE THREAD

**Issue by vzabawski** [helm/helm#9397]
I'm deploying a chart that uses Velero Helm chart as a dependency. Velero chart contains CRDs located in a separate directory.
Running `helm install -f values.yaml` installs all necessary charts and the deployment is finished with success.
Running `helm upgrade --install` does not create CRDs before dependent resources are deployed and it results into error:
```
$ helm upgrade --install --atomic --timeout 5m jenkins . --namespace jenkins --values secrets.yaml --values values.yaml
Error: UPGRADE FAILED: release jenkins failed, and has been rolled back due to atomic being set: post-upgrade hooks failed: unable to build kubernetes object for deleting hook nft-jenkins/charts/velero/templates/backupstoragelocation.yaml: unable to recognize "": no matches for kind "BackupStorageLocation" in version "velero.io/v1"
```

I'm aware that Helm does not handles CRDs upgrade and deletion, but `--install` flag adds a tricky moment here: should `helm upgrade --install` be treated as install operation or not?

Output of `helm version`:
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:47:40Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

**Comment by bacongobbler** [comment]
`helm upgrade --install` should be treated as an install. Not sure why it wouldn't... If no releases are present, [it invokes `helm install` ](https://github.com/helm/helm/blob/85794cfc6eb7216c987f544ceb871c94dbec6a7f/cmd/helm/upgrade.go#L93-L119) the first time it is called.

**Comment by bacongobbler** [comment]
If you can provide a simple example we can use to test and verify this bug, that would be wonderful. Preferably a chart that does not contain anything but a CRD and a dependent resource (i.e. something that does not require additional setup like Velero).

**Comment by vzabawski** [comment]
I tried to create a chart with crd example and use it as dependency for another chart, but in that case I wasn't able to reproduce the behavior. I even tried to reproduce my steps: deploy chart without dependencies, then try to upgrade it with added dependencies. It all works great. Then I thought it might be because of Helm hooks, but still no. So, I assume it might be the problem of Velero chart I'm using.
