### ISSUE TITLE
Add homebrew formula for helm

### ISSUE THREAD

**Issue by sgoings** [helm/helm#94]
After #93 is done we should be able to easily install `helm` through our friend project `homebrew`.

**Comment by technosophos** [comment]
It seems only right.

**Comment by mattfarina** [comment]
Are you thinking of pulling the proper build from bintray or of using the build/bottle system in homebrew?

**Comment by sgoings** [comment]
Binary retrieval only.

**Comment by mattfarina** [comment]
@sgoings that's because homebrew will build and cache the appropriate binary for the major versions of OS X. It's not just per platform but even per major OS X version.

Should this be done for the 0.1 release of wait for the 0.2 one?

**Comment by mboersma** [comment]
I'm going to close this because at this point I'm sure if `brew install helm` works we will want it to put next-gen [`helm`](https://github.com/kubernetes/helm) on Mac OS X boxen. 👾
