### ISSUE TITLE
'helm test --filter' doesn't filter test report or logs

### ISSUE THREAD

**Issue by dwaynebailey** [helm/helm#9404]
Output of `helm version`: 
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"dirty", GoVersion:"go1.15.6"}

Current behaviour:
If using `helm test --filter` you still see what looks like run tests even though they have not been run such as this:

```console
$ helm test -n demo demo --filter 'name=demo-app2-test-db-credentials'
NAME: qc-demo
LAST DEPLOYED: Wed Feb 24 09:56:14 2021
NAMESPACE: demo
STATUS: deployed
REVISION: 55
TEST SUITE:     demo-app1-test-db-credentials
Last Started:   Wed Feb 24 09:56:27 2021
Last Completed: Wed Feb 24 09:56:36 2021
Phase:          Succeeded
TEST SUITE:     demo-app1-test-app2-connection
Last Started:   Wed Feb 24 09:56:36 2021
Last Completed: Wed Feb 24 09:56:44 2021
Phase:          Succeeded
TEST SUITE:     demo-app1-test-external-ingress
Last Started:   Wed Feb 24 09:56:45 2021
Last Completed: Wed Feb 24 09:56:53 2021
Phase:          Succeeded
TEST SUITE:     demo-app2-test-db-credentials
Last Started:   Wed Feb 24 10:13:20 2021
Last Completed: Wed Feb 24 10:13:28 2021
Phase:          Succeeded
```

Expected behaviour:
Either:
1. Skipped tests are shown as skipped, such as:
```console
TEST SUITE:     demo-app1-test-db-credentials
Last Started:   Wed Feb 24 09:56:27 2021
Last Completed: Wed Feb 24 09:56:36 2021
Phase:          Skipped
```
2. Any tests that don't match are simply not reported in the output

To me Option 2 makes the most sense.

*Update:*
The same applies to logs.  If you use filter you get the logs from all tests that have been run, not just the test that you are running.

**Comment by mattfarina** [comment]
I can see how the output can be confusing. Helm does not change the output of strings to the commands without making a major version revision. Other tools parse the output of the strings and we don't want to break their integration. So, any change to the output we would be looking to make in Helm v4. If you have suggestions we would be interested in them.

If you look at the last started and last completed for each of the tests you will see different times. When a test is run against a revision (in your case 55) the result is stored on the release record. When you run `helm status`, for example, you will see the results of past tests on this release version. I think this is what you are seeing here.

The only new test that is being run is the one specified by filter. The others are from previous runs for this release version and you are seeing those stored records.

**Comment by dwaynebailey** [comment]
@mattfarina I will defer to the Helm maintainers, not sure how to convey any v4 suggestions apart from via this bug.

But to be honest this sounds more like an actual bug than a Helm v4 feature request.  It isn't confusing it's just plain wrong.

If we consider the `--filter` as a contract `specify tests by attribute (currently "name") using attribute=value syntax or '!attribute=value' to exclude a test (can specify multiple or separate values with commas: name=test1,name=test2)` then when I get:

1. Selected tests run
2. All the test results
3. All the logs

Then to any sane person the actual `--filter` is not working according to the stated contract.  You kinda want to ask yourself what is the purpose of `--filter` then anyway?

For the life of me I can't think of anyone filtering and then expecting the output to not be filtered.  For a full output they can get from `helm status` anyway.

**Comment by dwaynebailey** [comment]
Happy to raise a different issue with this one but yip `helm test --filter`is pretty much broken.

This is a failure when combining `--filter` and `--log`

Slightly redacted.

```console
~/dev/qc/chart (all_tests)$ helm test release --logs --filter 'name=testB,name=testC'
...
STATUS: deployed
REVISION: 88
TEST SUITE:     testB
Last Started:   Thu Feb 25 11:30:51 2021
Last Completed: Thu Feb 25 11:31:04 2021
Phase:          Succeeded
TEST SUITE:     testC
Last Started:   Thu Feb 25 11:31:04 2021
Last Completed: Thu Feb 25 11:31:17 2021
Phase:          Succeeded
...
Error: unable to get pod logs for testA: pods "testA" not found
```

I didn't want `testA` or its logs.  And where are the logs for `testB`, `testC`?
