### ISSUE TITLE
Helm install don't to install crds, worked before, possible regression?

### ISSUE THREAD

**Issue by hatzhang** [helm/helm#9405]
I got a RabbitmqClusterOperator crd put into crds folder. Helm installed it before, but now it only create a namespace.
```bash
$ tree crds/
crds/
└── cluster-operator.yml

$ k -n rabbitmq-system get all
No resources found in rabbitmq-system namespace.

$ helm version
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"clean", GoVersion:"go1.15.7"}
```

**Comment by hickeyma** [comment]
@hatzhang Can you see the crd if you run: `kubectl get crds `?

**Comment by mattfarina** [comment]
To add some context, CRDs are not in namespaces and extend the Kubernetes API. They remind me of kernel extensions to some extent. They are not like normal resources. `kubectl get all` doesn't display CRDs.

**Comment by hatzhang** [comment]
While, the Rabbitmq's cluster-operator contains more than CRD itself, when apply it we can got these:
```bash
$ k -n rabbitmq-system get all
NAME                                             READY   STATUS    RESTARTS   AGE
pod/rabbitmq-cluster-operator-7bbbb8d559-phv7g   1/1     Running   1          14h

NAME                                        READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/rabbitmq-cluster-operator   1/1     1            1           14h

NAME                                                   DESIRED   CURRENT   READY   AGE
replicaset.apps/rabbitmq-cluster-operator-7bbbb8d559   1         1         1       14h
```
I first encountered this issue when letting fluxcd manage my helmrelease, then tried with helm install, got the same problem. And both worked before. And i do did some upgrades just recently.  
Using get crds get the following result. The createtime of rabbitmqcluster crd is weird though. Maybe i didn't clean it clearly?
```
$ k get crds
NAME                                             CREATED AT
alerts.notification.toolkit.fluxcd.io            2021-02-24T10:12:19Z
buckets.source.toolkit.fluxcd.io                 2021-02-24T10:12:19Z
gitrepositories.source.toolkit.fluxcd.io         2021-02-24T10:12:19Z
helmcharts.source.toolkit.fluxcd.io              2021-02-24T10:12:19Z
helmreleases.helm.toolkit.fluxcd.io              2021-02-24T10:12:19Z
helmrepositories.source.toolkit.fluxcd.io        2021-02-24T10:12:19Z
imagepolicies.image.toolkit.fluxcd.io            2021-02-24T10:12:19Z
imagerepositories.image.toolkit.fluxcd.io        2021-02-24T10:12:19Z
imageupdateautomations.image.toolkit.fluxcd.io   2021-02-24T10:12:19Z
kustomizations.kustomize.toolkit.fluxcd.io       2021-02-24T10:12:20Z
providers.notification.toolkit.fluxcd.io         2021-02-24T10:12:20Z
rabbitmqclusters.rabbitmq.com                    2021-02-10T08:57:23Z
receivers.notification.toolkit.fluxcd.io         2021-02-24T10:12:20Z
```

**Comment by hatzhang** [comment]
I think i made two mistakes here, one is that how to clean crd, one is that how fluxcd handles crds intallation.  
Before, i remove crd by using ```k delete -f crds.yaml```, and for rabbitmqclusteroperator, ```k delete ns rabbitmq-system``` seemed work too. But fluxcd installed those rabbitmq cluster operator in default namespace together with my helm release. So the delete ns approach will not work.  
With new created cluster, there is no problem.  
Thanks.
