### ISSUE TITLE
Dynamically create configmaps using multiple files external to charts.

### ISSUE THREAD

**Issue by rao2100** [helm/helm#9413]
I am migrating my deployments to helm right now. For one of our deployments the user would be able to provide custom scripts. 

The previous steps were:
kubectl create configmap scripts -n <namespace> --from-file=./scripts
and then i can mount this as volume in the deployment.

Using helm, i can use --set-file to set a variable to a single file and the use that to create a configmap.

Is there a way to set multiple files dynamically to a variable?
Is there a way to create multiple configmap dynamically when  the files are external to the chart?

Thanks in  advance =)

**Comment by mattfarina** [comment]
`--set-file` can accept multiple paths being passed to it. If you run `helm help install` you will see some help text explaining it for the flag. Does that work?

**Comment by rao2100** [comment]
@mattfarina Thank you for the reply,

I guess I am actually waiting for:
https://github.com/helm/helm/pull/8841

I have chart that can deploy multiple instances with different configuration and mount different set of files. the files for each instance will be provided by users external to the chart.
