### ISSUE TITLE
.Capabilities.FeatureGates

### ISSUE THREAD

**Issue by rafis** [helm/helm#9419]
As a helm chart developer I want to be able to check what FeatureGates are enabled on the Kubernetes cluster I'm deploying onto to make different output in manifests depending on whenever FeatureGate enabled or not. For example, `.Capabilities.FeatureGates.StartupProbe`.

Output of `helm version`:
v3.5.1

Output of `kubectl version`:
From v1.12 up to v1.20

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
VMWare vCloud, Manually installed Google Kubernetes

**Comment by mattfarina** [comment]
I like this idea. This type of thing requires a Helm Improvement Proposal. Could you create one at https://github.com/helm/community/tree/master/hips
