### ISSUE TITLE
Helm V2 package command provides execute permission to ".sh" file automatically but Helm V3 package command doesn't.

### ISSUE THREAD

**Issue by SantoshNGitHub** [helm/helm#9423]
I am migrating from helm version 2.14.3 to version 3.2.4. 
I first packaged a sample chart with helm2 package command and then untarred it. I find that the `helm2 package` command provides execute permission to the .sh file which was inside the chart.
I did the same thing using `helm3 package` command and found that it does not give execute permission to the .sh file.

### Steps to reproduce the above issue/bug/feature

**Environment Details:**
Output of `helm version --short`: 
Client: v2.14.3+g0e7f3b6
Server: v2.14.3+g0e7f3b6

Output of `kubectl version --short`:
Client Version: v1.15.3
Server Version: v1.15.3

Output of `minikube version`: 
minikube version: v1.5.1
commit: 4df684c4cc2bd9dc9979cd5dbb44bdfa410850b4

1. Create a sample helm: `helm2-sample` chart and create a script file: `hello-script.sh` in it
s4kumars@host-40-1-0-15:/test/helm2-test$ helm create helm2-sample
Creating helm2-sample
s4kumars@host-40-1-0-15:/test/helm2-test$ cd helm2-sample/
s4kumars@host-40-1-0-15:/test/helm2-test/helm2-sample$ ls
charts	Chart.yaml  templates  values.yaml
s4kumars@host-40-1-0-15:/test/helm2-test/helm2-sample$ mkdir scripts
s4kumars@host-40-1-0-15:/test/helm2-test/helm2-sample$ cd scripts/
s4kumars@host-40-1-0-15:/test/helm2-test/helm2-sample/scripts$ vim hello-script.sh

2. See the initial permission of the script file. The file does not have execute permission
s4kumars@host-40-1-0-15:~/test/helm2-test/helm2-sample/scripts$ ls -lart hello-script.sh 
**-rw-rw-r-- 1 s4kumars s4kumars 78 Feb 27 12:45 hello-script.sh**

3. Package the chart
s4kumars@host-40-1-0-15:~/test/helm2-test$ helm package helm2-sample/
Successfully packaged chart and saved it to: /home/s4kumars/test/helm2-test/helm2-sample-0.1.0.tgz

4. Untar the file and see the `hello-script.sh`'s permission. We find that the execute permission is now added to it
s4kumars@host-40-1-0-15:/test/helm2-test$ tar -xvzf helm2-sample-0.1.0.tgz 
helm2-sample/Chart.yaml
helm2-sample/values.yaml
....................................
....................................
....................................
helm2-sample/scripts/hello-script.sh
s4kumars@host-40-1-0-15:~/test/helm2-test$ ls -lart helm2-sample/scripts/
total 12
**-rwxr-xr-x 1 s4kumars s4kumars   78 Feb 27 13:40 hello-script.sh**
drwxr-xr-x 5 s4kumars s4kumars 4096 Feb 27 13:40 ..
drwxrwxr-x 2 s4kumars s4kumars 4096 Feb 27 13:40 .

Now follow the above steps for Helm3 and see the difference in permissions.

**Environment Details:**
Output of `helm version --short`: v3.2.4+g0ad800e

Output of `kubectl version --short`:
Client Version: v1.18.13
Server Version: v1.18.13

Output of `minikube version`: 
minikube version: v1.14.2
commit: 2c82918e2347188e21c4e44c8056fc80408bce10

1. Create a sample helm: `helm3-sample` chart and create a script file: `hello-script.sh` in it
s4kumars@host-40-1-0-15:/test/helm3-test$ helm create helm3-sample
Creating helm3-sample
s4kumars@host-40-1-0-15:~/test/helm3-test$ 
s4kumars@host-40-1-0-15:/test/helm3-test/helm3-sample$ ls
charts	Chart.yaml  templates  values.yaml
s4kumars@host-40-1-0-15:/test/helm3-test/helm3-sample$ mkdir scripts
s4kumars@host-40-1-0-15:/test/helm3-test/helm3-sample$ cd scripts/
s4kumars@host-40-1-0-15:/test/helm3-test/helm3-sample/scripts$ touch hello-script.sh
s4kumars@host-40-1-0-15:/test/helm3-test/helm3-sample/scripts$ vim hello-script.sh 

2.  See the initial permission of the script file
s4kumars@host-40-1-0-15:~/test/helm3-test/helm3-sample/scripts$ ls -lart
total 12
drwxr-xr-x 5 s4kumars s4kumars 4096 Feb 27 12:22 ..
**-rw-rw-r-- 1 s4kumars s4kumars   78 Feb 27 12:24 hello-script.sh**
drwxrwxr-x 2 s4kumars s4kumars 4096 Feb 27 12:24 .

3. Package the chart:
s4kumars@host-40-1-0-15:/test/helm3-test$ helm package helm3-sample/
Successfully packaged chart and saved it to: /home/s4kumars/test/helm3-test/helm3-sample-0.1.0.tgz

4. Untar the file and see the permission. The permissions remain same.  
s4kumars@host-40-1-0-15:/test/helm3-test$ tar -xvzf helm3-sample-0.1.0.tgz 
helm3-sample/Chart.yaml
helm3-sample/values.yaml
.....................................
......................................
helm3-sample/scripts/hello-script.sh
s4kumars@host-40-1-0-15:/test/helm3-test$ ls -lart helm3-sample/scripts/
total 12
**-rw-r--r-- 1 s4kumars s4kumars   78 Feb 27 12:27 hello-script.sh**
drwxr-xr-x 5 s4kumars s4kumars 4096 Feb 27 12:28 ..
drwxrwxr-x 2 s4kumars s4kumars 4096 Feb 27 12:28 .

We can see above that `helm2 package` command gives execute permission to `.sh` file but `helm3 package` command doesn't.
But I do not see this bug/issue/feature documented anywhere. Can anyone confirm this? Please comment if more details are required.

Attachments:
**Helm2 Package Command Observation**
<img width="1000" alt="helm2-package-cmd-test" src="https://user-images.githubusercontent.com/15448042/109385178-f4035580-7917-11eb-88fd-3ca9479d6273.PNG">

**Helm3 Package Command Observation**
<img width="1000" alt="helm3-package-cmd-test" src="https://user-images.githubusercontent.com/15448042/109385186-04b3cb80-7918-11eb-91be-8d008dc81f15.PNG">

**Comment by mattfarina** [comment]
First, let me say that I can confirm the difference. I found the lines of code that changes which cause this. Then the files are added to the archive the permissions in v2 were 655 and in v3 are 644. The execute mask has been removed for group and world.

I have not encountered this until now and didn't realize it changed.

Can you share a bit about your use case so we can better understand it.

**Comment by SantoshNGitHub** [comment]
Hi @mattfarina 

Thanks for replying!!

We first execute script file  create directories in our machine. These directories are used by kubernetes PV as mount path. We have put this script file in the helm chart named xyz. As per standards we first create PV separately and then install xyz chart to create PVC.

Basically, the script file is packaged with the chart.

**Comment by SantoshNGitHub** [comment]
The doubt is cleared.
