### ISSUE TITLE
how to use helm3 go sdk out side a k8s cluster

### ISSUE THREAD

**Issue by zziawan** [helm/helm#9428]
i use usename and password  but failed with error: 
**failed to list: configmaps is forbidden: User "system:anonymous" cannot list resource "configmaps" in API group "" in the namespace "kube-system"**  .It seem the config not use by the kube client.  anyone kowns how to use it? thanks!

      apiServer := "the apiserver host and port"
       kubeConfig.APIServer=&apiServer
	k8sUser := "kube"
	kubeConfig.Username = &k8sUser
	k8sPassword := "some password"
	kubeConfig.Password = &k8sPassword
	nameSpace := "kube-system"
	kubeConfig.Namespace = &nameSpace
	trust := true
	kubeConfig.Insecure = &trust

       er := actionConfig.Init(kubeConfig, nameSpace, os.Getenv("HELM_DRIVER"), log.Printf)
	if er != nil{
		log.Print(er)
	}
	listAction := action.NewList(actionConfig)
	r,e := listAction.Run()
	if e != nil{
		log.Println(e)
	}

**Comment by hickeyma** [comment]
@zziawan The SDK uses [kubeconfig files](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/) for connecting to the k8s API server. 

Have a look in the [Helm doc](https://helm.sh/docs/topics/advanced/#go-sdk) for more details.  Example of getting the `action.Config` is in https://github.com/hickeyma/helm-mapkubeapis/blob/master/pkg/v3/connect.go#L34-L52.

Hope this helps.

**Comment by zziawan** [comment]
> @zziawan The SDK uses [kubeconfig files](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/) for connecting to the k8s API server.
> 
> Have a look in the [Helm doc](https://helm.sh/docs/topics/advanced/#go-sdk) for more details. Example of getting the `action.Config` is in https://github.com/hickeyma/helm-mapkubeapis/blob/master/pkg/v3/connect.go#L34-L52.
> 
> Hope this helps.

 thanks! it means  we must use config file to connect? but we can not get the config file out side the cluster...

**Comment by hickeyma** [comment]
The config file resides outside the cluster. It is what enables you to authenticate with a particular cluster or clusters. It is what all clients (like `kubectl` and `helm`) of the k8s cluster use. It is explained in [kubeconfig files doc](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/).

**Comment by zziawan** [comment]
@hickeyma  thanks ! i copy the config to local , list release  still forbidden. do you have any idea ? thanks!

        settings = cli.New()
	actionConfig := new(action.Configuration)
	settings.KubeConfig = "D:\\GoData\\cache\\k8s\\config"
	//settings.KubeContext = kubeConfig.Context
	var namespace = ""
	// check if the namespace is passed by the user. If not get Helm to return the current namespace
	if namespace == "" {
		namespace = settings.Namespace()
	}

	err := actionConfig.Init(settings.RESTClientGetter(), namespace, os.Getenv("HELM_DRIVER"),log.Printf )
	if err != nil {
		log.Print(err)
	}
	listAction := action.NewList(actionConfig)
	r,e := listAction.Run()

error is: **secrets is forbidden: User "system:anonymous" cannot list resource "secrets" in API group "" in the namespace "registry"**

**Comment by hickeyma** [comment]
What is the output when you run: `kubectl get secrets -n registry`?

**Comment by zziawan** [comment]
@hickeyma  i found the reason, when i config the apiServer start with http，when building k8s client all the auth config has been discard. so the  "system:anonymous" error appeared!   

**// only try to read the auth information if we are secure
	if restclient.IsConfigTransportTLS(*clientConfig) {
		var err error
		var persister restclient.AuthProviderConfigPersister
.....
}

func IsConfigTransportTLS(config Config) bool {
	baseURL, _, err := defaultServerUrlFor(&config)
	if err != nil {
		return false
	}
	return baseURL.Scheme == "https"
}**
when i use k8s client alone, i can set the auth infomation as follow, it does work!

**config, ConfigErr := clientcmd.BuildConfigFromFlags("http://172.20.245.45:8443","")
config.Username = username
config.Password = password**

i can not found other init helm method to replace the k8s config, mybe helm should let user costom k8s client config .
