### ISSUE TITLE
Detect helm template is executed

### ISSUE THREAD

**Issue by SimonBaeumer** [helm/helm#9431]
Hey Helm-Team,

is it possible to detect if a helm template is rendered with the `helm template` command?

From my observation `helm template` defaults to kubernetes version `1.18`. In our use-case this is problematic because we would like to default to a lower version if `helm template` is used, otherwise relying on `Capabilities.KubeVersion`.

```
$ helm version
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}
```

Thanks in advance,
Simon

**Comment by mattfarina** [comment]
The version of Kubernetes used as the default in Helm for commands like `helm template` and `helm install --dry-run` changes depending on the minor version of Kubernetes to match the supported version. v3.4.x and v3.5.x support different versions of Kubernetes.

It would be possible to make the Kubernetes version a flag that was passed in if someone wants to work on that as a new feature.

**Comment by SimonBaeumer** [comment]
Thanks for your answer @mattfarina, did not know about that and found the corresponding page.
Do you may know if helm template uses the k8s libraries if helm has no active connection to a cluster?
