### ISSUE TITLE
.helmignore file not ignored by helm package

### ISSUE THREAD

**Issue by mattops** [helm/helm#9436]
When using `helm package [directory]` I would have expected that the `.helmignore` file itself would be ignored.  
 However the `.helmignore` file gets included in the packaged`.tgz` file.  I can not think why this would be a good idea and can only assume that it is pointless including it, or is there a reason?

Output of `helm version`:
`version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"dirty", GoVersion:"go1.15.5"}`

**Comment by marckhouzam** [comment]
I guess you can put `.helmignore` in the .helmignore file?

**Comment by mattops** [comment]
> I guess you can put `.helmignore` in the .helmignore file?
 
yes that is one solution that works thanks.   But if there is no logical reason to include it in the packaged artefact - I think the behaviour of `helm package` should be to not to include it.

**Comment by marckhouzam** [comment]
@mattops you're probably right. The only reason I can think of is that once you start pre-ignoring certain files then it opens the door to other such request; it may have been simpler to leave the entire responsibility to the user.

Note for example that `.dockerignore` does not auto-exclude itself either (at least it didn't used to).

You can wait a couple of days to see if anyone has a better justification, and if not, you can always try getting a PR in.

**Comment by mattfarina** [comment]
I have 2 thoughts on this to provide some context....

1. Making a change in apiVersion v2 charts to start ignoring the _.helmignore_ file in the chart archive would be a backwards compatibility breaking change. We couldn't do that until the major version was incremented. Some people may rely on this behavior and we don't want to remove it without following proper semver.
2. The _.helmignore_ file is used for more than packaging. For example, when a chart is loaded into memory the _.helmignore_ file is consulted and listed files are skipped. This impacts numerous workflows. For example, someone downloads a chart archive, unpacks it, forks it, and installs it. The _.helmignore_ file will tell the chart to not load certain files when doing installing.

If this only impacted the behavior of packaging it would make sense to not include it.
