### ISSUE TITLE
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: unknown object type "nil" in Deployment.spec.template.metadata.annotations.iam.amazonaws.com/role

### ISSUE THREAD

**Issue by vrathore18** [helm/helm#9438]
I just updated helm 2 to 3. Ever since I updated the helm version I keep getting this validation error. I read somewhere that the previous helm was not validating the schema but now it does and that is why people are facing the issue.

But This error is not at all help full. I have so many deployment yaml file in the chart. How would I check which deployment file is having the issue?

`Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: unknown object type "nil" in Deployment.spec.template.metadata.annotations.iam.amazonaws.com/role`

Output of `helm version`: `version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}`

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.15", GitCommit:"2adc8d7091e89b6e3ca8d048140618ec89b39369", GitTreeState:"clean", BuildDate:"2020-09-02T11:40:00Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): EKS

P.S I am running below helm command

`helm upgrade --install test ./app/ -f "client-values.yaml"`

**Comment by bridgetkromhout** [comment]
Hi, @vrathore18 - does `helm lint` show you any errors? That may help you find where you need to set default values. You may find `--strict` useful. And there are more debugging tips on https://helm.sh/docs/chart_template_guide/debugging/.
