### ISSUE TITLE
how to convert string to chartutils.Values

### ISSUE THREAD

**Issue by drewwells** [helm/helm#9439]
Output of `helm version`: 3.2.4

Output of `kubectl version`: N/A

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  n?A

I am trying to render helm from within a helper template. We take different set of values files and send them through a rendering tpl. This is so `{{ tpl }}` can be resolved before sending to an actual helm chart.

We ran into an issue with trying to cast types. We want to render a template that converts a list to a map. I came up with something like this. The problem is that .Values.list is not the same as a string ".Values.list", the former is a special type chartutils.Values. How can I take a string ".Values.list" and lookup the chartutils.Values?

```
{{- define "render.expend" -}}
{{- if kindIs "string" .current }}
            {{- if hasPrefix "include" .current }}
                {{- $parseInclude := (regexSplit " " (trimPrefix "include " .current) -1) }}
                // input: include "render.mapfromlist" .Values.list
                // parsed:
                // {{ tpl "render.mapfromlist" ".Values.list"
                {{ tpl (first $parseInclude) (tpl (last $parseInclude) .) }}
            {{- else }}
            {{- end }}
{{- end }}
{{- end }}

{{- define "render.mapfromlist" -}}
... code to convert to list
{{- end }}
```

**Comment by drewwells** [comment]
Relevant code https://github.com/helm/helm/blob/6297c021cbda1483d8c08a8ec6f4a99e38be7302/pkg/chartutil/values.go#L106-L113

**Comment by bacongobbler** [comment]
Have you tried looking at the reflect functions like `kindOf` or `kindIs`?

https://helm.sh/docs/chart_template_guide/function_list/#reflection-functions

**Comment by drewwells** [comment]
Can you give a code snippet? I'm not following. I want to be able to create a chartutils.Values with templating code.

```
ctx := {{ tpl ".Values.list" . }}
{{ tpl "render.mapfromlist" $ctx }}
```

**Comment by bacongobbler** [comment]
> How can I take a string ".Values.list" and lookup the chartutils.Values?

```
{{ range $index, $element := index . "Values" "list" }}
{{ end }}
```

You can use `regexSplit` and split the string by periods if you need to split the literal string ".Values.list".

I'm not entirely sure what you're looking for, but hope that helps.

**Comment by drewwells** [comment]
I got it now, that's what I was asking for. Thank you!
