### ISSUE TITLE
Unable to add repo - "error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type repo.IndexFile"

### ISSUE THREAD

**Issue by DevatDxc** [helm/helm#9440]
I have prepared helm charts and no issues in that. Able to deploy those charts using "helm install <chart-dir> ...." Now wanted to create package and add it into the repository so that user can add them in helm repo from gitrepo and start using helm deploy <package name>.

So far was able to create packages using "helm package <chart-dir> --destination <dest-folder>" for the charts i had. Created the tar files (tgz)
![snapshot3](https://user-images.githubusercontent.com/66685734/110020651-d7b84c00-7d4f-11eb-90c0-1cd0d130efc5.JPG)

when i tried to add them to helm repo from github - getting error:

github.dxc.com/healthcare-ohc/ohc-helm-charts.git" is not a valid chart repository or cannot be reached: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type repo.IndexFile

Please advise why the error, what am i missing here.

Output of `helm version`:

version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"14f897abdc7b57f0850da68bd5959c9ee14ce2fe", GitTreeState:"clean", BuildDate:"2021-01-22T17:29:38Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

AKS

![snapshot1](https://user-images.githubusercontent.com/66685734/110019730-ccb0ec00-7d4e-11eb-847b-d22f811682f6.JPG)
![snapshot2](https://user-images.githubusercontent.com/66685734/110019732-cde21900-7d4e-11eb-94d7-be425f741fdc.JPG)

**Comment by bacongobbler** [comment]
Git repositories are git repositories. They are not Helm repositories.

To explain further... https://helm.sh/docs/topics/chart_repository/

> A chart repository is an HTTP server that houses an index.yaml file and optionally some packaged charts. When you're ready to share your charts, the preferred way to do so is by uploading them to a chart repository.

The key words there are "HTTP server that houses an index.yaml file".

If you would like to serve your charts from a git repository, there are several projects that help you serve it over HTTP, including an example on [serving it via github pages(https://helm.sh/docs/topics/chart_repository/#github-pages-example).

Hope this helps.
