### ISSUE TITLE
helm dependencies update pulls wrong version

### ISSUE THREAD

**Issue by MartinKirchner** [helm/helm#9445]
I have a chart with a dependency.

**Chart.yaml**
```
apiVersion: v2
name: smartwedev
type: application
version: 5.9.0
appVersion: 5.9.0

dependencies:
- name: smartwe-testdb-maria
  alias: smartweDb
  version: 5.9.0
  condition: smartweDb.enableTestDb
  repository: http://registry.swecluster.cas-it.cas.de/chartrepo/smartwedev
```

However, when I call `helm dependencies update` in the projects folder helm downloads the version `5.9.0.SUBCHARTS-SNAPSHOT` into the `/charts` subfolder.

In my harbor registry there are several versions of my chart:
```
$ helm search repo harbor/smartwedev --version=5.9.0 -l
NAME                    CHART VERSION                           APP VERSION                             DESCRIPTION
harbor/smartwedev       5.9.0+BERND-SNAPSHOT                    5.9.0.BERND-SNAPSHOT                    Deploys SmartWe as a development setup with two...
harbor/smartwedev       5.9.0+HELMDEPENDENCIES-SNAPSHOT         5.9.0.HELMDEPENDENCIES-SNAPSHOT         Deploys SmartWe as a development setup with two...
harbor/smartwedev       5.9.0+SALUTATION-SNAPSHOT               5.9.0.SALUTATION-SNAPSHOT               Deploys SmartWe as a development setup with two...
harbor/smartwedev       5.9.0+NATIVETOKENSSO-SNAPSHOT           5.9.0.NATIVETOKENSSO-SNAPSHOT           Deploys SmartWe as a development setup with two...
harbor/smartwedev       5.9.0+HELMLIB-SNAPSHOT                  5.9.0.HELMLIB-SNAPSHOT                  Deploys SmartWe as a development setup with two...
harbor/smartwedev       5.9.0+COUNTRYPRESELECTION-SNAPSHOT      5.9.0.COUNTRYPRESELECTION-SNAPSHOT      Deploys SmartWe as a development setup with two...
harbor/smartwedev       5.9.0+STJAVA11-SNAPSHOT                 5.9.0.STJAVA11-SNAPSHOT                 Deploys SmartWe as a development setup with two...
harbor/smartwedev       5.9.0+SUBCHARTS-SNAPSHOT                5.9.0.SUBCHARTS-SNAPSHOT                Deploys SmartWe as a development setup with two...
harbor/smartwedev       5.9.0+HELMLIBFUNC-SNAPSHOT              5.9.0.HELMLIBFUNC-SNAPSHOT              Deploys SmartWe as a development setup with two...
harbor/smartwedev       5.9.0                                   5.9.0                                   Deploys SmartWe as a development setup with two...
harbor/smartwedev       5.9.0+TRIALINFO-SNAPSHOT                5.9.0.TRIALINFO-SNAPSHOT                Deploys SmartWe as a development setup with two...
```

Output of `helm version`:
`version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}`

Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platf
orm:"windows/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
not relevant

**Comment by mattfarina** [comment]
I think I see the problem. For the chart version (not the app version), Helm follows semantic versioning. The `+` starts the build metadata. The [build metadata section of the spec](https://semver.org/#spec-item-10) notes:

> Build metadata MUST be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence.

According to semver, all of your items tagged with `5.9.0` are going to resolve to be the same.

**Comment by MartinKirchner** [comment]
@mattfarina Thank you for your support
