### ISSUE TITLE
Helm rollback command

### ISSUE THREAD

**Issue by yeplaa** [helm/helm#9447]
Hello,

I would like know if possible to prevent the helm rollback execution with a specific Chart configuration? 
Is it possible or is this an update planned ? 

Thanks for your help

Output of `helm version`: 
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2-0-g52c56ce", GitCommit:"6082e941e6d62f3a0c6ca8ba52927100948b1d0d", GitTreeState:"clean", BuildDate:"2021-01-30T06:29:35Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0+f173eb4", GitCommit:"f173eb4a83e55734ee6808a1ed7674be9a4cd0bf", GitTreeState:"clean", BuildDate:"2021-02-11T22:10:37Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  Internal Caas

**Comment by bacongobbler** [comment]
No, there is no way to prevent the execution of a `helm rollback`. It is not something the community has considered, and I have not heard of this use case before.

Can you please provide more information about your particular use case?

**Comment by yeplaa** [comment]
Thanks @bacongobbler for your reply. My use case is about the crd (without using the crds directoty). The purpose will prevent the rollback and also to prevent the delete of crd file if the user launch the uninstall command. 
Is it possible for the deleting or is it not implemented? 

Thanks
