### ISSUE TITLE
Does Helm support retrieving files within the project subtree for sub-charts?

### ISSUE THREAD

**Issue by pedro93** [helm/helm#9450]
Hello,

I have a helm chart deployment that is composed of several components, each being a sub-chart. This is a system that I want to ultimately package such that the final user needs only to touch the top-level `values.yaml` to deploy the project.

A requirement of this system (which I find is quite common) is that a couple of these sub-charts require configuration files that must currently all sit in the top-level `templates` folder.

This leads to a not so great file structure:
```
.
├── Chart.lock
├── charts
│   ├── <component-1>.tgz
│   ├── <component-2>.tgz
│   ├── <component-3>.tgz
│   ├── <component-4>.tgz
│   ├── <component-5>.tgz
│   ├── <external_dependency_1>
│   ├── <external_dependency_2>
│   ├── <external_dependency_3>
│   ├── <external_dependency_4>
├── Chart.yaml
├── helm-charts
│   ├── <component-1>
│   ├── <component-2>
│   ├── <component-3>
│   ├── <component-4>
│   ├── <component-5>
├── README.md
├── templates
│   ├── <dozens of different resources here between configmaps and secrets>
└── values.yaml
```

Something that I've trying to do is to automatically, via templates generate these resources by asking the user to simply point to the path of the config file from which I will generate all required configMaps and secrets. The aim is to have something like this:
```
.
├── Chart.lock
├── charts
│   ├── <component-1>.tgz
│   ├── <component-2>.tgz
│   ├── <component-3>.tgz
│   ├── <component-4>.tgz
│   ├── <component-5>.tgz
│   ├── <external_dependency_1>
│   ├── <external_dependency_2>
│   ├── <external_dependency_3>
│   ├── <external_dependency_4>
├── Chart.yaml
├── README.md
├── configs/
│   ├── <component-1>
│   │   ├── secrets.properties
│   │   ├── config.properties
│   ├── <component-2>
.....
└── values.yaml
```

The idea would be that a `configmap.yaml` template in component-1 could read the content of `configs/component-1/config.properties` and inject that information.

This does not currently work and there is work to address it in the command line https://github.com/helm/helm/pull/8841 but it does that seems limiting from a user perspective what is reason for not allowing this particular case?
I understand that there is a security concern with allowing Helm to search for any file in the filesystem, but could helm be allowed to search for files starting from the top-level folder of the overall chart?

**Comment by bacongobbler** [comment]
Charts are self-contained. Siblings (two charts declared as depenendencies of an "umbrella" chart) cannot share files or templates with one another. However, a parent chart has access to its own resources and all of its children.

A common pattern is to write an "adapter" chart: an umbrella chart that takes two charts and bridges the two together. For example, you could write an umbrella chart that coordinates the connection between a mysql and a web application chart. This is used commonly when writing separate discrete components, but then you want to join them all together to make one homogeneous product.

Hope that helps.

**Comment by pedro93** [comment]
Just wanted to say, thank you for replying! I was unaware of the adapter pattern.
