### ISSUE TITLE
No Error Response when using Validating Admission Webhooks

### ISSUE THREAD

**Issue by Shamim56** [helm/helm#9453]
Hello All,
 
I setup a validating admission webhook in kubernetes to deny all pods, and I am getting the response that what I expect using kubectl (denial) e.g.
 
```
kubectl run elasticsearch --image elasticsearch:7.1.0 -n mynamespace
Error from server: admission webhook "com.site.admission-webhook" denied the request: Not Allowed
```
 
but when using helm to deploy the pod
 
```
helm install elastisearch charts/elasticsearch/ -n mynamespace
NAME: elastisearch
LAST DEPLOYED: Mon Mar  8 01:37:51 2021
NAMESPACE: mynamespace
STATUS: deployed
REVISION: 1
TEST SUITE: None
```
 
I checked after helm install and the admission controller had denied it, but helm did not spit out an error code like how kubectl did
 
 
 
Output of `helm version`:
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}
 
 
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

**Comment by bacongobbler** [comment]
Helm's goal is simple: render the templates with the provided values, then send it to kubernetes via the `kubectl apply` API. Unless Kubernetes returns an error during the API operation, there's not much Helm can do here to report back that an admission webhook denied the request.

If you can determine how Helm can bubble up admission webhook denials to the end-user via the `kubectl apply` API, we're all easr.

**Comment by bacongobbler** [comment]
https://github.com/helm/helm/blob/543364fba59b0c7c30e38ebe0f73680db895abb6/pkg/kube/client.go#L377-L383
