### ISSUE TITLE
Helm upgrade will remove resources that is under if not (lookup)

### ISSUE THREAD

**Issue by sureleo** [helm/helm#9455]
Hello,

I need to install releases across different namespaces, and my Helm Chart contains clusterrole and clusterrolebinding.

In order to avoid the conflict when creating clusterrolebinding in different namespaces, I added the following statement:

```
{{ if not (lookup "rbac.authorization.k8s.io/v1" "ClusterRoleBinding" "" "my-crb") }}
{{end}}
```

It works fine with the first installation. However, the second time when I was trying to do ```helm upgrade RELEASE_NAME -n NAMESPACE --install```, Helm will remove this clusterrolebinding.

Is this expected or a bug? If it is expected, what is the recommendation for a cluster level object that can be shared by multiple namespaces and multiple Helm release?

Output of `helm version`:
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"clean", BuildDate:"2020-05-06T05:09:48Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): vanilla kubeadm

**Comment by bacongobbler** [comment]
This is expected. To explain a bit further, Helm installs any templates that are rendered by the chart. When those templates are removed from the chart, Helm assumes the next chart version wishes to delete the resource. So it uninstalls it.

To handle your use case, you would have to make the chart look up the ClusterRoleBinding, as you did. But then you'd have to re-render that template each time on an upgrade. One way to handle this would be to check a label on the resource on lookup, or some unique identifier to know you rendered that resource.

Hope that helps.

**Comment by sureleo** [comment]
Thanks!

I made it work by adding a bunch of code but it meets the requirement. Sharing it just in case anybody else has the problem:

```
{{ define "crb" }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crb
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    helm.sh/resource-policy: "keep"
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: User
  name: {{ required "Please set the value of ObjectId of CustomLocation Resource Provider AAD App." .Values.aad.customLocationObjectId }}
{{ end }}

{{ $clusterRoleBinding := (lookup "rbac.authorization.k8s.io/v1" "ClusterRoleBinding" "" "crb") }}

# Create the customlocation cluster role binding if cluster role binding is not present.
{{ if (not $clusterRoleBinding) }}
{{- template "crb" }}
{{ end }}

# Do not remove custom location cluster role binding during upgrade.
{{ if $clusterRoleBinding }}
{{ if $clusterRoleBinding.metadata }}
{{ if $clusterRoleBinding.metadata.annotations }}
{{ if (and (eq (get $clusterRoleBinding.metadata.annotations "meta.helm.sh/release-name") .Release.Name) (eq (get $clusterRoleBinding.metadata.annotations "meta.helm.sh/release-namespace") .Release.Namespace)) }}

{{- template "crb" }}

{{ end }}
{{ end }}
{{ end }}
{{ end }}
```
