### ISSUE TITLE
Inconsistency between documentation and actual behavior

### ISSUE THREAD

**Issue by gy-lehel** [helm/helm#9459]
Helm version 3.4.1+ 3.5.x

Documentation here
https://helm.sh/docs/topics/charts/
lists the "requirements" field in a dependency chart as a mandatory item.
The following changes:
https://github.com/helm/helm/issues/8955
https://github.com/helm/helm/issues/8940
have changed the behavior, and no it seems to be non-mandatory, so there is now an inconsistency between the documentation, and the actual working of helm.

**Comment by bacongobbler** [comment]
I cannot find what section you are referring to when you mention “the requirements field”. Did you mean the “dependencies” field?

Any PRs or suggestions to the documentation are always welcome. If you find any issues, please feel free to submit a PR and we can take a look.

**Comment by aspel** [comment]
@bacongobbler 
The repository section in dependencies could be optional
