### ISSUE TITLE
Should `helm lint` display warnings in stderr ?

### ISSUE THREAD

**Issue by antoineozenne** [helm/helm#9464]
Output of `helm version`:
`version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}`
Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.17", GitCommit:"f3abc15296f3a3f54e4ee42e830c61047b13895f", GitTreeState:"clean", BuildDate:"2021-01-13T13:21:12Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.17", GitCommit:"f3abc15296f3a3f54e4ee42e830c61047b13895f", GitTreeState:"clean", BuildDate:"2021-01-13T13:13:00Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}`

Helm currently displays warnings in stdout when linting a chart. Should `helm lint` display warnings in stderr ?

**Comment by bacongobbler** [comment]
No. In this case it is intentional that linter warnings are displayed on standard out. The warnings will not cause the linter to fail (unless `--strict` is set), however it is important to bubble these warnings up to the caller running `helm lint`.

**Comment by antoineozenne** [comment]
Ok, thanks !
