### ISSUE TITLE
Any flag to have only succesful releases in helm history and query on max history supported

### ISSUE THREAD

**Issue by nknkgithub** [helm/helm#9468]
Output of `helm version`:
```
helm version
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

Hi,
a) I want to know how much entries will helm history support by default and how it can be overwritten?
(via --max in helm history or via  --history-max ). And what is difference between them?

b) And if there is no change in manifest of old release and new release then pods will not restart (when same external yaml is mentioned both times)?
c) Is there any flag using which we can have only successful revisions in helm history?
d) If I have 1 successful release and 12 failed releases, then will helm history have 1 successful release (i.e. 13 entries) and that successful release is deleted only when new successful release comes?
e) Is there any flag with which we can  delete old resources (like pod) and then try to bring up new resources during upgrade or rollback ? (instead when new pod comes up , old pod will get deleted)?

**Comment by bacongobbler** [comment]
`--history-max` is set to 10 by default. You can determine the default value using `helm --help`. That flag is what Helm uses to determine whether a release should be removed during an upgrade. If you set `--history-max` to 10 and you upgrade 11 times, only the last 10 releases will be stored in Kubernetes.

`--max` determines the maximum number of releases to render on the terminal screen at one time. If you have `--history-max` set to a higher value or you have a bunch of failing releases, that is when you might want to use the `--max` flag. It is also useful if you only want to display a small number of releases, e.g. `helm history foo --max 3` to show the last 3 releases.

> Is there any flag using which we can have only successful revisions in helm history?

There is no way to filter the release ledger by its current state. However we do have something similar for `helm list`: `helm list --all`, `helm list --failed`, `helm list --pending`, and `helm list --filter` are some examples.

> d) If I have 1 successful release and 12 failed releases, then will helm history have 1 successful release (i.e. 13 entries) and that successful release is deleted only when new successful release comes?

Correct. That way Helm always has one known "good" state to use when calculating its upgrade logic.

> e) Is there any flag with which we can delete old resources (like pod) and then try to bring up new resources during upgrade or rollback ? (instead when new pod comes up , old pod will get deleted)?

No. Though a similar ask was requested in #7431.
