### ISSUE TITLE
How can I upgrade the client-go on which helm v3.3.3 depends from v0.18.8 to v0.19.0?

### ISSUE THREAD

**Issue by rov-lw** [helm/helm#9469]
Our Kubernetes version depends on client-go v0.19.0. Therefore, we hope that the client-go on which helm v3.3.3 depends also uses v0.19.0. However, after the client-go version on which helm depends is changed from v0.18.8 to v0.19.0, the communication between helm and kubernetes is abnormal. How can I use client-go v0.19.0 without upgrading the helm version?

**Comment by bacongobbler** [comment]
Let us know if you figure this out. Resolving dependency issues with Kubernetes has never been easy.
