### ISSUE TITLE
Missing Supported Kubernetes Versions details for 3.5.x

### ISSUE THREAD

**Issue by vhnguyenae** [helm/helm#9470]
Hello,
Not really an issue but I can't find the supported Kubernetes versions for 3.5.x on this page
https://helm.sh/docs/topics/version_skew/#:~:text=As%20of%20Helm%203%2C%20Helm,n%2D1%20versions%20of%20Kubernetes
Can someone update it?
Thanks in advance for your support :)
Vu Hai

**Comment by marckhouzam** [comment]
Thanks for the report @vhnguyenae.  I believe it was an oversight.  We'll fix it.

**Comment by marckhouzam** [comment]
Oh and the supported versions are `1.20.x - 1.17.x`

**Comment by marckhouzam** [comment]
If this happens again and you know what the versions should be, feel free to post a PR on helm-www.
https://github.com/helm/helm-www/pull/1039

**Comment by marckhouzam** [comment]
Closing as the change will be tracked by helm/helm-www#1039

**Comment by vhnguyenae** [comment]
great, thanks for your help :)
