### ISSUE TITLE
Use the helm library without a kubeconfig file on the FS

### ISSUE THREAD

**Issue by manuelmazzuola** [helm/helm#9473]
Hi,
I'm writing a rest api that leverages on the helm library to provision new charts on the target k8s cluster.

I read the kubeconfig content from a DB, and I don't want to persist the content to the filesystem and then pass the path to the rest client configurator.

Is it possible to initialise the rest client configuration using the content instead of the path of the kubeconfig?
Something that replace 

```go
actionConfig.Init(kube.GetConfig(KUBECONFIG_PATH, "", releaseNamespace), releaseNamespace, "configmap", func(format string, v ...interface{}) {
        fmt.Sprintf(format, v)
    })
```

**Comment by bacongobbler** [comment]
Hi @manuelmazzuola. This question has been asked and answered before. Have you looked up similar support questions in the issue queue?

For example https://github.com/helm/helm/issues/9428.

**Comment by bacongobbler** [comment]
Closing as a duplicate. Please follow up in those tickets I referenced earlier - we try to keep conversations in one ticket so there's no cross-talk between multiple tickets. Thanks.
