### ISSUE TITLE
helm upgrade fails after upgrade from 3.3.1 to 3.5.3

### ISSUE THREAD

**Issue by vbr-cts** [helm/helm#9474]
Hi.
I tried upgrading helm today, and our CI scripts are failing. This is the debug output:

```
helm3 -n noscit-production upgrade -i astraia-production chart -f values_astraia.yaml  --debug
history.go:56: [debug] getting history for release astraia-production
upgrade.go:123: [debug] preparing upgrade for astraia-production
upgrade.go:131: [debug] performing update for astraia-production
upgrade.go:303: [debug] creating upgraded release for astraia-production
Error: UPGRADE FAILED: encountered 24 deletion errors. First is: release: not found
helm.go:81: [debug] encountered 24 deletion errors. First is: release: not found
helm.sh/helm/v3/pkg/storage.(*Storage).removeLeastRecent
	/home/circleci/helm.sh/helm/pkg/storage/storage.go:216
helm.sh/helm/v3/pkg/storage.(*Storage).Create
	/home/circleci/helm.sh/helm/pkg/storage/storage.go:64
helm.sh/helm/v3/pkg/action.(*Upgrade).performUpgrade
	/home/circleci/helm.sh/helm/pkg/action/upgrade.go:304
helm.sh/helm/v3/pkg/action.(*Upgrade).Run
	/home/circleci/helm.sh/helm/pkg/action/upgrade.go:132
main.newUpgradeCmd.func2
	/home/circleci/helm.sh/helm/cmd/helm/upgrade.go:155
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:80
runtime.main
	/usr/local/go/src/runtime/proc.go:204
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374
UPGRADE FAILED
main.newUpgradeCmd.func2
	/home/circleci/helm.sh/helm/cmd/helm/upgrade.go:157
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:80
runtime.main
	/usr/local/go/src/runtime/proc.go:204
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374

```

My Chart.yaml looks like this:
```
apiVersion: v1
name: astraia
version: 1.3.0
engine: gotpl # The name of the template engine (optional, defaults to gotpl)
appVersion: 1.3.x
```

`helm status`, `helm list`, and `helm history` can see the chart properly.

Downgrading back to 3.3.1 works, and the chart does get properly upgraded.

I'm at a loss what might be causing this, and how to move forward on the issue. The number of errors (`24` on the output above) seems to increase after a successful deployment, so I am guessing it might be linked to the number of versions that I have (28 currently).

Output of `helm version`:
```
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  bare metal k8s (kubeadm)

**Comment by vbr-cts** [comment]
It works when setting `--history-max=50`.

It appears the naming convention for the secrets has changed from `astraia-production.v28` to `sh.helm.release.v1.astraia-production.v29` and that the secret's `type` has changed from `helm.sh/release` to `helm.sh/release.v1`.

What is the proper upgrade path ? Should I simply remove the old secrets ?

**Comment by bacongobbler** [comment]
If the naming convention has changed, you are upgrading releases that used to be installed via helm 2. We changed the naming scheme during the alpha releases of helm 3 if I recall.

have you gone through the helm 2 to helm 3 migration guide yet?

**Comment by vbr-cts** [comment]
I have. The 2to3 plugin fails, saying there are no deployed releases for my release. I've also been using helm3 since the pre-release stage. I believe Tiller was never used on this cluster.

Is it safe to simply delete the old secrets ?

**Comment by bacongobbler** [comment]
If you're comfortable with removing those old secrets, you can attempt to do so, yes. Though I would recommend trying to reproduce your issue in a staging cluster and see if you can try to both reproduce the issue and test solutions there first before doing something destructive in production.

**Comment by vbr-cts** [comment]
Okay, thanks.

It looks like first upgrading the charts with `--history-max=0`, and then removing the old secrets works fine.
