### ISSUE TITLE
3.5.3 build fails on linux

### ISSUE THREAD

**Issue by xaocon** [helm/helm#9479]
Output of `helm version`:
```
% bin/helm version
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.16.1"}
```
Output of `kubectl version`:
```
% kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.12-gke.1210", GitCommit:"199a41188dc0ca5d6d95b1cc7e8ba96e05f9dd0a", GitTreeState:"clean", BuildDate:"2021-02-05T18:03:16Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
N/A

Building with `make build` fails for 3.5.3 in some situations. I know virtually nothing about go but following the directions from the compiler seemed to fix the problem and update `go.sum` (hence "dirty" above). I noticed this while trying to install with linuxbrew and found Homebrew/linuxbrew-core#22543. While this may be related to something in linuxbrew, it seems unlikely to me since the fix was known by the compiler and changed `go.sum` (which I'm guessing is something like a library lock file) and looking at the formula it's just calling `make build` which seems to be the usual instructions.

Here's the error msg I get trying to build:
```
% make build
GO111MODULE=on go build  -tags '' -ldflags '-w -s -X helm.sh/helm/v3/internal/version.version=v3.5.3 -X helm.sh/helm/v3/internal/version.metadata= -X helm.sh/helm/v3/internal/version.gitCommit=041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622 -X helm.sh/helm/v3/internal/version.gitTreeState=dirty -X helm.sh/helm/v3/pkg/lint/rules.k8sVersionMajor=1 -X helm.sh/helm/v3/pkg/lint/rules.k8sVersionMinor=20 -X helm.sh/helm/v3/pkg/chartutil.k8sVersionMajor=1 -X helm.sh/helm/v3/pkg/chartutil.k8sVersionMinor=20' -o '/tmp/helm-20210312-108426-19uzocz/bin'/helm ./cmd/helm
/home/<USER>/.cache/Homebrew/go_mod_cache/pkg/mod/github.com/moby/moby@v17.12.0-ce-rc1.0.20200618181300-9dc6525e6118+incompatible/pkg/system/path.go:9:2: missing go.sum entry for module providing package github.com/containerd/continuity/pathdriver (imported by github.com/docker/docker/pkg/system); to add:
        go get github.com/docker/docker/pkg/system@v1.4.2-0.20200203170920-46ec8731fbce
make: *** [Makefile:78: /tmp/helm-20210312-108426-19uzocz/bin/helm] Error 1
``` 

Simply running `go get github.com/docker/docker/pkg/system@v1.4.2-0.20200203170920-46ec8731fbce` as instructed allowed it to build and it seems ok but I didn't do much testing.

If you think this is a env problem related to linuxbrew please just let me know (though it would be great if you had any insight into what the problem could be) and I'll try to adjust the brew formula instead.

**Comment by bacongobbler** [comment]
The latest builds on CircleCI seem to be passing, which runs on a linux machine: https://app.circleci.com/pipelines/github/helm/helm/2296/workflows/2fac5573-76a7-415f-8155-722883bce9a2/jobs/13863

Let us know what you discover.

**Comment by bacongobbler** [comment]
Might be relevant: https://github.com/helm/helm/blob/543364fba59b0c7c30e38ebe0f73680db895abb6/go.mod#L51-L54

**Comment by dbro86** [comment]
I don't know if this problem came up only with the new Go version 1.16.2 (released on 11/03).
Anyway, with an additional 'go mod tidy' the build problem is fixed.

**Comment by hickeyma** [comment]
@dbro86 @bacongobbler Tidy up of dependencies pushed in #9486
