### ISSUE TITLE
Pre-defined "soft" and "hard" `podAntiAffinity` in default starter ?

### ISSUE THREAD

**Issue by antoineozenne** [helm/helm#9487]
In kube-prometheus-stack chart, we can see "soft" and "hard" pre-defined `podAntiAffinity` in [prometheus.yaml](https://github.com/prometheus-community/helm-charts/blob/8318ce1d92e8c3dd487d89066d0f7b2405c65653/charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml#L199). I've seen this in several charts before. Is it possible to have this in default helm starter (`helm create`) ? It would be useful because generally, `podAntiAffinity` use the same labels as `selectorLabels`, so we could use `_helpers.tpl` to template the default "hard" and "soft" `podAntiAffinity` with the `app.kubernetes.io/name` and `app.kubernetes.io/instance` default selector labels. Without that, the selector labels could be changed but not the `podAntiAffinity`.

Maybe define a "ready to custom" chart is not the default starter goal. I can see the probes are hard-coded in the default `deployment.yaml`. So maybe my question doesn't make sense.

**Comment by jdolitsky** [comment]
This may be useful. Perhaps if the default values disable this by default

**Comment by bacongobbler** [comment]
In general, the default chart that is generated by `helm create` is there to serve as a good launch point for users new to the Kubernetes ecosystem. It is not intended to be the "ultimate starter chart" that will handle everyone's use case. For that we have starter charts: https://helm.sh/docs/topics/charts/#chart-starter-packs

The resources in the default starter chart intend to provide sane defaults for someone looking to build their first chart. Think "hello world". If it doesn't fit the case where a first-time user of Helm needs to set pod anti-affinity to create their first app, I would avoid adding it to the default starter chart.

**Comment by antoineozenne** [comment]
Thank you for your reply. Hope there is an "ultimate starter chart" somewhere. :) Anyway, I will do my own starter chart.
