### ISSUE TITLE
Same values file leads to different results

### ISSUE THREAD

**Issue by PascalTurbo** [helm/helm#9489]
Hi all,

we've observed a strange behavior of our application that was not running because a value from sub chart should be overwritten explicitly with "nothing" (by setting the value '~') by our values.yaml but that didn't happen.
So after some investigation I found out that helm renders different results based on the way we provide the input values.

I've rendered with the following methods:

1. `helm install --dry-run --debug minimalexample`
2. `helm install -f values.yaml --dry-run --debug minimalexample`
3. `helm install -f values-name.yaml --dry-run --debug minimalexample`

In the last example I've renamed values.yaml to values-name.yaml

My expectation was that at least first and second example result in the same output. But it didn't. The relevant line in our minimal example renders to:

1. `application.properties: "\nservice.other.value=Override value"` (https://github.com/PascalTurbo/helm-minimal-example/blob/8ad0fe0c266e93011efd83cb4bbe13fef28c329c/output-with-values_yaml.yaml#L164)
2. `application.properties: "\nservice.backend.endpoint-path=/sub1/original/path\n\nservice.other.value=Override value"` (https://github.com/PascalTurbo/helm-minimal-example/blob/8ad0fe0c266e93011efd83cb4bbe13fef28c329c/output-with-explicit_values_yaml.yaml#L201)
3. `application.properties: "\nservice.other.value=Override value"` (https://github.com/PascalTurbo/helm-minimal-example/blob/8ad0fe0c266e93011efd83cb4bbe13fef28c329c/output-with-values_name_yaml.yaml#L200)

You can find the whole minimal example here: https://github.com/PascalTurbo/helm-minimal-example

Output of `helm version`: `version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}`

Output of `kubectl version`: `Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Kubernetes

**Comment by jdolitsky** [comment]
possibly related to https://github.com/helm/helm/issues/9136 / https://github.com/helm/helm/issues/9136
