### ISSUE TITLE
Add the ability to refer to runtime values (service's IP) in dependent resources.

### ISSUE THREAD

**Issue by madhusudancs** [helm/helm#949]
For example, I would like to start a service and use it's IP address in another pod. Dependencies have been discussed before in other contexts. Ref: issues #53 #54. This is very useful and simplifies handling dependent charts.

**Comment by technosophos** [comment]
Isn't this solved by the Kubernetes environment variable and service discovery protocols? http://kubernetes.io/docs/user-guide/connecting-applications/#accessing-the-service

Since templates are rendered before resources are loaded into Kubernetes, templates cannot find out at render time what the IPs are. But you could use label selectors, Downward API, Kubernetes environment variables, and skydns queries to find this information out.

**Comment by bacongobbler** [comment]
> I would like to start a service and use it's IP address in another pod.

Indeed, isn't this just a re-implementation of http://kubernetes.io/docs/admin/dns/? Sounds to me this has already been solved upstream. can you supply a use case where this would be required?

**Comment by madhusudancs** [comment]
@technosophos @bacongobbler Both the service discovery methods (environment variables and DNS) within Kubernetes clusters return the cluster local IP addresses, but not the external addresses for LoadBalancer services. Also, I don't think Downward API exposes the service IP address.

Here is a more concrete use case. I am considering converting "Cluster Federation" components to helm charts. Here is the federation-apiserver pod template spec - https://github.com/kubernetes/kubernetes/blob/master/federation/manifests/federation-apiserver-deployment.yaml#L25. The `--advertise-address` flag value is parametrized and should be substituted with the external address of the `type: loadBalancer` service created for the `federation-apiserver`. Look at the current code to do this - https://github.com/kubernetes/kubernetes/blob/master/federation/cluster/common.sh#L127

To convert these to helm, I see three options. Let me know if you have any other recommendations.

1. Put the service and deployment charts into separate helm packages. Submit the service chart and poll until the external IP is assigned and then submit the deployment chart with the IP address.
2. Build the service polling logic into the apiserver container or into the apiserver itself.
3. Use the new, in-alpha, `init container` feature and put the polling logic there.

None of these options are any better than what we have today, which in my opinion is already unnecessarily complicated and could be much simplified if there is a tool that can handle dependencies. And among the tools we have today I think helm is the closest.

Btw, this is just one concrete use case.

**Comment by technosophos** [comment]
Ah! I understand much better now. Thanks.

In today's Helm, you could use `pre-install` hooks to do some of the things you were thinking of. But again, I'm not sure that that would decrease the complexity of the logic.

It sounds like what would really solve the problem for you is for some way to say to Helm: "At the time that this manifest (or resource) is loaded, do a lookup for me and inject the results here." Does that sound accurate?

I'm not sure how to best express that in Helm right now. If you had an ideal way, what would it look like? Would it be a template directive? Want to mock that out and see if we can get some ideas going?

**Comment by technosophos** [comment]
We are still tossing around some ideas on how to do this. /cc @adamreese

**Comment by thomastaylor312** [comment]
@technosophos or @adamreese Is there still ongoing discussion/plans for this on a minor release or should be bump it to the "major" milestone?

**Comment by pierreozoux** [comment]
I'm actually working on a public chart for jitsi, and it needs to know it's public IP.
What is the way to solve this today?

**Comment by bacongobbler** [comment]
https://github.com/kubernetes/charts/blob/master/stable/drupal/templates/NOTES.txt shows some examples on how you can fetch a chart's public IP address depending on what service type was deployed. Essentially if you need the public IP at runtime, you'll have to check with the kubernetes apiserver.

**Comment by sabbour** [comment]
This is a needed feature. Another use case:
Web frontend running in a service talking to multiple microservices over the internet (Javascript calls) deployed in their own services.

I need a way to be able to find out what's the public IP of a specific service from within the container.

Currently DNS exposes the service.namespace (which is internal), and the environment variables expose the internal load balancer IP (which won't be routable from Javascript).

**Comment by bacongobbler** [comment]
If someone would write up a design document with a reference implementation on how this could be solved, that would be incredibly helpful. We're not sure how to best express this in Helm, so perhaps someone from the community may know more.

**Comment by benc-uk** [comment]
@sabbour I have the same use-case. My front-end pod and service needs to know the **external IP** of the backend API service, as it is passed to Angular app, which is all client side. Clients will obviously access via the public external IP

Getting the internal cluster IP or DNS is no help with any modern JavaScript single page app

**Comment by kierenj** [comment]
I think I want this too.. I'm trying to create a post install hook to set up a subdomain A record to point to the public IP.  It seemed a very obvious use of the post install hook: get some information that can only be gotten after install has finished?  I would welcome any workaround to this at all: is there some command I can run within the hook's container to get a service's public IP by name, for instance?

**Comment by korenlev** [comment]
this is still open since 2016 ? still no option to refer tu runtime IP of a service ?
how people using services  able to tell thier pods pre deployment which value to use at runtime ?

**Comment by scottlindner** [comment]
I wrote a shell script that runs at container startup that talks to the cluster to get those values and drops them in environment variables.

**Comment by SachinHg** [comment]
Can someone please help with this feature?

**Comment by AlexShemeshWix** [comment]
+1

**Comment by gazhenko** [comment]
+1

**Comment by SlickNik** [comment]
@viane Unfortunately, I don't think this is possible in a pre-install hook since the resources haven't been created in Kubernetes yet. Essentially, the only way I can think of doing this is checking with the Kubernetes API server (like @bacongobbler mentions above) once the resources have been created -- either in a post-install hook, or once the pod container comes up at runtime.

**Comment by kierenj** [comment]
Is there some reason this approach - getting the public IP in a script - is no good?

https://github.com/RedRiverSoftware/sql-azure-firewall-opener/blob/master/azsqlfirewall.sh

**Comment by viane** [comment]
in my case its only available thru k8s resource, a worker node ip inside the cluster... And I still couldn't find a clean way to get this resource. But the label and node's ip was already exist inside k8s, why can't helm retrieve it ....

**Comment by archelangelo** [comment]
One use case would be setting up the upstream DNS service for `kube-dns` using the `stubDomains` configuration. The `stubDoamins` destinations can only be IP addresses of upstream DNS services. It would be great if the IP address assigned to a service can be referred to during the helm installation so that this `stubDomains` configuration can be done in the same helm chart. See [here](https://kubernetes.io/blog/2017/04/configuring-private-dns-zones-upstream-nameservers-kubernetes/) and [here](https://github.com/kubernetes/dns/issues/82).

**Comment by aturco41** [comment]
Bump.

**Comment by dshakey** [comment]
> Bump.

**Comment by bacongobbler** [comment]
closing as #6752 has been merged and will be available in 3.1.0.
