### ISSUE TITLE
Support for different output formats for `helm test`

### ISSUE THREAD

**Issue by agilgur5** [helm/helm#9491]
### Current Behavior

`helm test` only supports one kind of output, which may not be compatible with all test output readers, loggers, CI systems, etc.

### Desired Behavior

`helm test` to have a flag for output formats, say `--output junit` or something.

### Suggested Solution

A converter/parser within `helm test` that can change the output based on a flag. I'm still a novice at Go so can't quite recommend a library for that

### Who does this impact? Who is this for?

Folks using CI systems that require a certain type of test output. One of the systems I'm using requires JUnit for instance.

### Describe alternatives you've considered

Writing a parser _on top of_ `helm test`, but I figure it makes more sense and is more useful inside of `helm test`.

Currently we run `Job`s outside of Helm, and then parse out `status.succeeded` when the `Job` completes and those are basically the tests that we then output as JUnit (currently in Bash with `osht`).

### Additional context

Couldn't find any issues about `junit` etc and the [Chart tests doc](https://helm.sh/docs/topics/chart_tests/) doesn't mention different output formats

**Comment by jdolitsky** [comment]
Can you describe the types of things you're running upon `helm test`? Is it either pass vs. fail, or are you running multiple tests? Trying to come up with how junit output might look like.

**Comment by agilgur5** [comment]
Thanks for the quick response @jdolitsky ! For the most part we're just running several `Job`s to ensure things work. Each of those is pass/fail. So the existing output works, but just isn't in JUnit.

**Comment by agilgur5** [comment]
This issue was never resolved...
