### ISSUE TITLE
I am wondering how to replace this logic about deprecated method

### ISSUE THREAD

**Issue by kyuPrivate** [helm/helm#9493]
hello this is kyu jin

I want to know how do I replace deprecated method (helm.sh/helm/helm/v3/kube GetConfig) :(
(https://github.com/helm/helm/blob/master/pkg/kube/config.go)

Please let me know if you need more information
thanks in advance

**Comment by jdolitsky** [comment]
Hello, please see the commit where this was deprecated: https://github.com/helm/helm/commit/4a0dfbe53b2191e09a7034ce97e4caf84989d6db

Need to do something like the following:
```
	env.config = &genericclioptions.ConfigFlags{
		Namespace:   &env.namespace,
		Context:     &env.KubeContext,
		BearerToken: &env.KubeToken,
		APIServer:   &env.KubeAPIServer,
		KubeConfig:  &env.KubeConfig,
	}
```

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!
