### ISSUE TITLE
Be able to use chart version constraint as stated in Masterminds/semver

### ISSUE THREAD

**Issue by Schildkroete23** [helm/helm#9495]
With the `version` flag for installing or upgrading a helm chart I can set a specific version of the helm chart to be installed. When the version flag is omitted the latest version of a chart will be installed. When I install a chart I often want the newest patches and minor version upgrades. But not the major version upgrades as this could break my deployment. So, it would be nice to be able to specify a range for the version flag.

For getting the version specified with the version flag Helm uses [Masterminds/semver](https://github.com/Masterminds/semver) (if I understand it correctly, I'm a noob in Go). In the [documentation](https://github.com/Masterminds/semver) it is stated that specifying a range for the version constraint is possible. I tried it. But unfortunately it did not work.

Before I have a deeper look at the code: Is there any specific reason why this is not working? Is it on purpose?

**Comment by jdolitsky** [comment]
I dont believe what you are asking is supported.

To calirfy, your hoping to do something like:
```
helm install mychart myrepo/mychart --version ^0.2.3
```
?

**Comment by Schildkroete23** [comment]
Exactly. I think it would be a great enhancement. More than happy to contribute:)

**Comment by Schildkroete23** [comment]
Again I had a deeper look into the code and tested it now correctly. It actually works already. Awesome!! It seems like it is possible to use al the Version constraints documented [here](https://github.com/Masterminds/semver#checking-version-constraints).

**Comment by Schildkroete23** [comment]
Can we add this to the documentation?

**Comment by bacongobbler** [comment]
Please feel free to do so. The documentation is hosted at https://github.com/helm/helm-www

**Comment by Schildkroete23** [comment]
Thanks! As far as I understand the documentation for the flags is generated automatically. So, I tried to improve the description in the code.
