### ISSUE TITLE
Parsing only failing when it matches on last line of a conditional when it should fail for all.

### ISSUE THREAD

**Issue by toddlross** [helm/helm#9498]
I'm seeing an issue where a template only fails when it matches on the last line of a conditional.  It should fail for all of them.
Example yaml:
```
kind: Endpoints
apiVersion: v1
metadata:
  name: test-data
subsets:
- addresses:
  {{- if eq .Values.env "dev" }}
  - ip: 1.2.3.4
  {{ else if eq .Values.env "qa" }}
  - ip: 1.2.3.5
  {{ else if eq .Values.env "uat" }}
  - ip: 1.2.3.6
  {{ else if eq .Values.env "dr" }}
  - ip: 1.2.3.7
  {{ else if eq .Values.env "prod" }}
  - ip: 1.2.3.8
  {{- end -}}
  ports:
  - port: 8080
```

that {{- end -}} should be {{ end -}}, but this chart succeeds for "dev", "qa", "uat", and "dr", but will fail when passed "prod".  This should really fail all the time.

When it fails you get the following error:
Error: YAML parse error on test-data.yaml: error converting YAML to JSON: yaml: line 7: mapping values are not allowed in this context
helm.go:81: [debug] error converting YAML to JSON: yaml: line 7: mapping values are not allowed in this context

Output of `helm version`:
**tested on 3.4.2:**
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}
**and 3.5.3:**
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCom                       mit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:                       "2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd                       64"}

**Comment by bacongobbler** [comment]
Issues relates to the `text/template` engine should be submitted to golang/go. Any changes/foxes made there will be picked up by Helm when we update to a newer version of Go.

https://github.com/golang/go
