### ISSUE TITLE
helm does not fully implement the XDG specification (XDG_DATA_DIRS not supported)

### ISSUE THREAD

**Issue by bitdancer** [helm/helm#9500]
Output of `helm version`: `version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}`

This was previously reported in #7529, which was closed as stale.  I'm opening a new issue in order to provide additional information and background.

The requirement for full xdg support originates with #7528.  In order to install plugins globally, helm must check a sequence of directories for its data (here, plugins).  helm currently only supports specifying a single directory.  If one were to set one of the supported environment variables (HELM_DATA_HOME, XDG_DATA_HOME) to the global directory, then the individual user would be unable to install additional plugins (since they would not have write access to the plugin directory.

The XDG spec anticipates this need.  XDG_DATA_DIRS may contain a list of directories in PATH format (eg: `/usr/local/share:/usr/share`, which is its default value).  When looking for data files, an XDG compliant application should look first in the directory specified by XDG_DATA_HOME, and then in the directories in XDG_DATA_DIRS in order.  If helm followed this part of the spec, then plugins would be looked for first in the user's local location (`$HOME/.local/share` by default, which helm does correctly use by default), and then in the global default directories `/usr/local/share` and `/usr/share`.  This would allow global install of common plugins, while allowing individual accounts to install other plugins or override the existing global plugin version, while still having access to the remaining globally installed plugins.

To demonstrate the current lack of support, I have plugins installed in `/usr/share/helm/plugins`, and none in my local directory tree:

```console
rdmurray:~[master]>HELM_DATA_HOME=/usr/share/helm helm3 plugin list
NAME    VERSION DESCRIPTION                                                                  
diff    3.1.3   Preview helm upgrade changes as a diff                                       
gcs     0.3.9   Manage repositories on Google Cloud Storage                                  
secrets 3.5.0   This plugin provides secrets values encryption for Helm charts secure storing
servecm 0.1.0   Start a ChartMuseum web server                                               
rdmurray:~[master]>XDG_DATA_HOME=/usr/share helm3 plugin list 
NAME    VERSION DESCRIPTION                                                                  
diff    3.1.3   Preview helm upgrade changes as a diff                                       
gcs     0.3.9   Manage repositories on Google Cloud Storage                                  
secrets 3.5.0   This plugin provides secrets values encryption for Helm charts secure storing
servecm 0.1.0   Start a ChartMuseum web server
rdmurray:~[master]>helm3 plugin list
NAME    VERSION DESCRIPTION      
rdmurray:~[master]>XDG_DATA_DIRS=/usr/share helm3 plugin list     
NAME    VERSION DESCRIPTION
```

As you can see, neither the default value for XDG_DATA_DIRS, nor setting it explicitly, are supported by helm.  The same thing would apply to configuration (XDG_CONFIG_DIRS)...I haven't checked that but I assume it has the same issue.

I realize that this isn't a trivial request, since it requires merging multiple data sources/configs.  I haven't looked at the helm source yet, nor am I a go programmer, so I'm not sure if I'll be able to offer a PR or not.

**Comment by mattfarina** [comment]
First, you are correct that Helm does not provide full XDG support.

PRs welcome to finish adding it.

**Comment by bitdancer** [comment]
It's still an issue, but I haven't found any time to try working on it yet.

**Comment by eikooc** [comment]
Is anyone working on this, or can I pick it up?

**Comment by hickeyma** [comment]
@eikooc If @bitdancer is ok with you working on it, then go for it.

**Comment by bitdancer** [comment]
I have not found time to even start on it yet, so by all means please go ahead :)

**Comment by hron84** [comment]
I see this as completed, was it because the asked feature is implemented or it is still not supported? I cannot find any documentation about this but "completed" state suggests this is supported in some way.

**Comment by benoittgt** [comment]
> I see this as completed, was it because the asked feature is implemented or it is still not supported? I cannot find any documentation about this but "completed" state suggests this is supported in some way.

If you check the story you will see it was closed by Github Action because the issue was stale and without any activity.
