### ISSUE TITLE
Issue: Upgrade.go:367: [debug] warning: Upgrade "myapp" failed: could not get information about the resource

### ISSUE THREAD

**Issue by emirot** [helm/helm#9501]
**Stacktrace**:
```
Upgrade.go:367: [debug] warning: Upgrade "myapp" failed: could not get information about the resource: the server was unable to return a response in the time allotted, but may still be processing the request (get deployments.apps myapp)
Error: UPGRADE FAILED: could not get information about the resource: the server was unable to return a response in the time allotted, but may still be processing the request (get deployments.apps myapp)
helm.go:94: [debug] the server was unable to return a response in the time allotted, but may still be processing the request (get deployments.apps myapp)
could not get information about the resource
```

**Question** 
How can I solve that issue ? And how to find that resource creating the issue ?

**Version**
Output of `helm version`: 3.3.0
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  could provider AWS via kops.

**Comment by bacongobbler** [comment]
The error message here is coming from Kubernetes directly. Helm is issuing API requests to Kubernetes, requesting information about a particular resource.

I would check the state of your Kubernetes cluster and ensure it is in a healthy condition. From the sounds of it, you could also have a slow connection to your cluster.

**Comment by emirot** [comment]
@bacongobbler 
Thank you for the help !! I finally noticed the same...
I got it wrong as I could deploy to another namespace and use kubectl, it looks like it's intermittent.
