### ISSUE TITLE
helm upgrade --wait command failded because of `etcdserver: leader changed`

### ISSUE THREAD

**Issue by JohnJAS** [helm/helm#9502]
I used `--wait` option during helm upgrade but found while waiting for the deployment ready, once a failure return from k8s api happened, helm will exit immidiately. 

Since a chart may contain various of resources, it is not so good to exit immidiately once a failure API calling happened while waiting for them to be ready

I think there should be some retrys while calling APIs since network APIs are designed to fail. 

logs attached:

wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
Error: etcdserver: leader changed
helm.go:94: [debug] etcdserver: leader changed

Output of `helm version`:
v3.3.0

Output of `kubectl version`:
v1.20.4

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
kubeadm

**Comment by bacongobbler** [comment]
PRs or fixes to help improve cases where the cluster is experiencing service degradations are most welcome.

**Comment by JohnJAS** [comment]
> Thank you for providing an example. PRs or fixes to help improve cases where the cluster is experiencing service degradations are most welcome. Have you looked into the feasibility of your proposal?
> 
> As noted in your `--wait` output, it does look as though Helm looked up the status of the resource multiple times before failing due to upstream service degradations, so unless I'm misunderstanding your request, it appears Helm already has some retry logic built into pkg/wait. If the upstream server closes the connection, that's a separate classification of work which may need to [be proposed as a HIP](https://github.com/helm/helm/blob/master/CONTRIBUTING.md#proposing-an-idea) as changing the default behaviour could lead to breaking changes for some users.
> 
> If you can please clarify how you expect this to work with either a patch or a test case, that would be welcome.

Thanks for your reply. 

I've checked the code associated with the --wait option. 

Package `pkg/util/wait/wait.go` works well with retrys but I think the `ConditionFunc` written in `pkg/kube/wait.go` should be enhanced. 

Since `func Poll(interval, timeout time.Duration, condition ConditionFunc)` function claims that `Poll tries a condition func until it returns true, an error, or the timeout is reached.` But when `waitForResources` code the `ConditionFunc`, it throw out the error immidiately without any retry while calling a k8s api. 

I don't know if i have explain it well because I'm not a native english speaker. But I have created a PR https://github.com/helm/helm/pull/9513 for this issue. You can have a review. I think the code can clarify more clearer then I said.

**Comment by dims** [comment]
related to https://github.com/helm/helm/issues/7637
