### ISSUE TITLE
【helmv3 back-compatibility】inconsistency validate rules in helmv3 lint process

### ISSUE THREAD

**Issue by popozy** [helm/helm#9503]
Output of `helm version`:
`helmv3.4.2`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
self-build  kubernetes cluster

Hi! I'm confused about the back-compatibility of the helmv3 with helmv2.

I found that  a error following  would be raised if I run `helm lint  xxx(helmv2).tgz`
``` shell
==> Linting xxx-0.1.0.tgz
[INFO] Chart.yaml: icon is recommended
[ERROR] Chart.yaml: chart type is not valid in apiVersion 'v1'. It is valid in apiVersion 'v2'

Error: 1 chart(s) linted, 1 chart(s) failed
```
So I dig to the lint code, finding a confusing implementation.
Fisrtly, it seems that helm v2 helmv3 packages are both supported
https://github.com/helm/helm/commit/4d47052395b3ac946350e37cd8dd6bf2c47364f7#diff-e2a52c01750822e579afbed8d7d7b69f252dcbdd820b1306cad79750b5494e39R92
```
func validateChartAPIVersion(cf *chart.Metadata) error {
	if cf.APIVersion == "" {
		return errors.New("apiVersion is required. The value must be either \"v1\" or \"v2\"")
	}

	if cf.APIVersion != chart.APIVersionV1 && cf.APIVersion != chart.APIVersionV2 {
		return fmt.Errorf("apiVersion '%s' is not valid. The value must be either \"v1\" or \"v2\"", cf.APIVersion)
	}

	return nil
}
```

However, helmv2 is not supported according to the judgement.
https://github.com/helm/helm/commit/4d47052395b3ac946350e37cd8dd6bf2c47364f7#diff-e2a52c01750822e579afbed8d7d7b69f252dcbdd820b1306cad79750b5494e39R171
``` golang
func validateChartType(cf *chart.Metadata) error {
	if len(cf.Type) > 0 && cf.APIVersion != chart.APIVersionV2 {
		return fmt.Errorf("chart type is not valid in apiVersion '%s'. It is valid in apiVersion '%s'", cf.APIVersion, chart.APIVersionV2)
	}
```

**Is there any consideration about the inconsistency between these two validate function in one lint operation?**

**Comment by hickeyma** [comment]
In Helm 3, changes were made to charts and as a consequence the `apiVersion` was changed from `v1` to `v2`. One of the changes was the addition of the `type` field. See the [Helm docs](https://helm.sh/docs/topics/charts/#the-apiversion-field) for more details. 

In your `Chart.yaml`, what is your `apiVersion` and does it contain the `type` field?

**Comment by popozy** [comment]
> In Helm 3, changes were made to charts and as a consequence the `apiVersion` was changed from `v1` to `v2`. One of the changes was the addition of the `type` field. See the [Helm docs](https://helm.sh/docs/topics/charts/#the-apiversion-field) for more details.
> 
> In your `Chart.yaml`, what is your `apiVersion` and does it contain the `type` field?

Thanks for your explaination. The Chart.yaml of mine turns out like the following one:
``` yaml
apiVersion: v1
appVersion: 1.16.0
description: A Helm chart for Kubernetes
name: xxxx
type: application
version: 0.1.0
```
So, I re-read the document once again, guessing that  you mean the `type` field only should exists in helmv3 package? Because no `type` filed could be found in [helmv2 Chart.yaml](https://v2.helm.sh/docs/developing_charts/#the-chart-yaml-file)

**Comment by hickeyma** [comment]
That is correct. It is an `apiVersion: v2` construct.

**Comment by popozy** [comment]
Thanks a lot~~
