### ISSUE TITLE
new built-in: Release.IsDryRun

### ISSUE THREAD

**Issue by benjamin-wright** [helm/helm#9504]
I'd like to propose an addition to the `.Release` built-in object to include a new `IsDryRun` property, to indicate whether the current render is being performed in a context where a cluster should be expected to be available.

My specific use-case: use lookup to grab a secret from a different namespace and copy the data into the release namespace

I want to conditionally `fail` if the lookup returns `nil`, to avoid silent failures if the source secret is missing, but obviously that will completely stop me being able to use `template` or `--dry-run`.

**Comment by bacongobbler** [comment]
There have been ongoing discussions whether `--dry-run` should allow lookups in a cluster. For example https://github.com/helm/helm/pull/9426.

I'm concerned that codifying `if .Release.DryRun` branches in a chart's templates is more of a code smell than something we should encourage. Authors should not be changing the behaviour of the chart based on whether it's a dry run vs a wet run... The output and expectation should be the same.

I'd highly recommend looking at #9426 and see if that will work for your use case instead.

**Comment by benjamin-wright** [comment]
Hi @bacongobbler 

Thanks, I'd not realised that was where the discussion had ended up! Yes, if helm were updated such that lookup behaves the same for dry and wet runs then my use-case will be covered :-)

**Comment by benjamin-wright** [comment]
Will close this in favour of #9426
