### ISSUE TITLE
feature: Flag "--dependency-update" is not available in command "upgrade"

### ISSUE THREAD

**Issue by ozbillwang** [helm/helm#9517]
### Output of `helm version`:
```
$ helm version
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.6"}
```
### Output of `kubectl version`:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-14T05:14:17Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"14f897abdc7b57f0850da68bd5959c9ee14ce2fe", GitTreeState:"clean", BuildDate:"2021-01-22T17:29:38Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
### Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

AKS

### problem

When run `helm upgrade --install` with flag `--dependency-update`, got below error:
```
Error: unknown flag: --dependency-update
```

Helm has two commands `helm install` and `helm upgrade`, it supposes you would run with `install` to install the chart, then `upgrade` it.  In real cases, I use `helm upgrade --install`, because with it, **especially in CICD pipeline**, I don't need write a condition to check if the chart is a new installation or exist already.

but there are several flags (or options) are not same between the commands. Other differences are fine, but could you add feature to support flag `--dependency-update` in command `upgrade` as well?

Currently I have to workaround with two commands

```
helm dependency update <chart>
helm upgrade --install <chart ....>
```

**Comment by mladedav** [comment]
This seems to be already being worked on in #9399.
I believe the code is waiting for a review now

**Comment by ozbillwang** [comment]
Thanks for the updates @bacongobbler . Waiting for this feature. 👍
