### ISSUE TITLE
Feature request: Assuring immutable helm releases

### ISSUE THREAD

**Issue by mapdegree** [helm/helm#9518]
Output of `helm version`: 3.5.2

Output of `kubectl version`: 1.20.2

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS, EKS

__

I have been thinking of writing my own kubernetes admission controller, but then I thought let's post this first on the Helm GitHub repository. 

Objective:
- assure that no resources of the Helm release have been tempered with after performing helm install or helm upgrade manually outside the control of the Helm utility (e. g. operations like kubectl edit / patch deployment, replicaset, etc.)
- assure helm releases are fully immutable natively in helm

Expectations:
- I expected helm verify to perform that operation on a release as well

Challenges:
- what should helm perform, if the Helm release is tempered? 
- stop the operation that was attempted (e. g. helm upgrade) and report back to the Helm UI that the release has been tempered and that it needs to be removed and deleted 

I really hope this functionality can be introduced natively in helm, so I can avoid building my own complexities.

**Comment by mattfarina** [comment]
This is an interesting idea. To test the idea, lets look at service meshes like linkerd and istio. Linkerd has [automatic proxy injection](https://linkerd.io/2.10/features/proxy-injection/). That means, linkerd users aren't going to want immutability. It would break their experience.

One way to think about this is that Helm is a package manager. If someone wants to run those packages in an immutable manner or if they want them to be mutable for cases like linkerd... that's an operational detail at a different level of the stack. Someone can use tools with a package manager to have both setups.

I like the idea of having an opt-in for immutability. We have a page to list related projects if someone were to make a tool to help with immutability.

**Comment by mapdegree** [comment]
Hi @mattfarina,

Thank you for your  comment, defenitely need to do more research and better define the minimal immutable part of 'a release'. 

Just as an example, know of a CD tool (e. g. Spinnaker) that has been assuring immutablility with adding annotations to Kubernetes resources, but Spinnaker is not the choice of tool.

Agree with opting in/out of assuring immutable release. As well I would really like to keep helm (v3) not introducing / repeating its past dependencies within the K8S cluster (aka tiller). 

Any other recommendation on the architecture would be appreciated. Feature proposal might need time and discussion to mature. A page to continue a discussion would be a great start. 

Thank you

**Comment by bacongobbler** [comment]
For reference, we have a process to help gather thoughts and try to answer some of the more common questions like backwards compatibility, how it works, who's the target audience etc: https://github.com/helm/helm/blob/master/CONTRIBUTING.md#proposing-an-idea

Hope that helps!
