### ISSUE TITLE
Feature request: Skip chart download in helm dep update if it's already present 

### ISSUE THREAD

**Issue by mgorsk1** [helm/helm#9519]
This PR is a proposal to add additional flag `--skip-chart-refresh` to helm dep cli so only dependent charts with new versions are downloaded to charts.

### Current State

`helm dep update ./helm-chart` command re-downloads all dependent charts present in `requirements.yaml` or `Chart.yaml`. While it's not lengthy process for charts having small number of dependencies, it is quite a long one for charts combining tens of subcharts. And it's redundant when downloading charts of the exact same version that are already present in `charts` directory.

### Why we would want to have this feature ?

We have a deployment consisting of 35 subcharts (every service is developed separately but we have one god repository serving as deployment repo) and helm dep update takes forever even when only 1 chart is updated. This is, because `helm dep update` command does not take into the account that the chart file already exists in `charts` dir and re-downloads everything every time.

### Environment Details

Output of `helm version`: 3.5.0

Output of `kubectl version`: n/a

Cloud Provider/Platform (AKS, GKE, Minikube etc.): n/a

**Comment by bacongobbler** [comment]
You could probably implement a cache lookup to determine if the shasums between what's available in the chart repository and what's present locally match. If so then we can assume the package does not require an update.

That would solve your issue without having to introduce a feature flag for this.

We've talked about this before in https://github.com/helm/helm/issues/9561 as well.
