### ISSUE TITLE
helm.sh/helm/v3 should use custom errors

### ISSUE THREAD

**Issue by manuelmazzuola** [helm/helm#9521]
In a perspective of a not supervised usage of the library, for example in an unattended flow where I would like to achieve idempotency, that is multiple calls to the application leads to the same result, the helm library should use custom errors, otherwise, I can't tell the difference between a network error or a release name conflict error.

For example, I would like to call multiple times `helm.sh/helm/v3/pkg/action.Run` with the same args, and then catch and manage this error `cannot re-use a name that is still in use`, since it is a built-in error all I can do is

```
helmDuplicateReleaseNameError := errors.New("cannot re-use a name that is still in use")
if _, err := myCallToActionRun(); err != nil || err.Error() == helmDuplicateReleaseNameError.Error() {
  // go ahead, do nothing bru, the chart is already installed
}
```

and that is really awful.

**Comment by bacongobbler** [comment]
Enhancements to improve the SDK's usage in the form of a PR are always welcome. In this case it should be simple to create a concrete `NameError` similar to [`chart.ValidationError`](https://github.com/helm/helm/blob/d55c53df4e394fb62b0514a09c57bce235dd7877/pkg/chart/errors.go#L20-L21).

https://github.com/helm/helm/blob/f5ef87b96e791ca9971231699fc5af687f748bae/pkg/action/install.go#L435
