### ISSUE TITLE
Only upgrade helm chart if the version is not the same 

### ISSUE THREAD

**Issue by pcurewitz** [helm/helm#9522]
it would be nice if helm was smart enough to know when the chart is already running latest and not upgrade/create another revision when nothing changed and vise versus. If a chart app version or chart version is newer it updates.  this way you can do the below command it would be smart enough to know whether or not to upgrade. If it is the same version print output upgrade not needed same version 

helm upgrade (name) (chart location) 

Output of `helm version`:3.5.3-1

Output of `kubectl version`:v1.19.7

Cloud Provider/Platform (AKS, GKE, Minikube etc.): kubeadm

**Comment by mattfarina** [comment]
How would you handle the case where someone wants to change the values but not the app or chart version?

One example is the Bitnami WordPress chart. The name of the blog (a big of application information) is captured as a value. You can change that by upgrading the chart but to the same chart/app version with just a new value.

**Comment by bergerx** [comment]
https://github.com/helm/helm/issues/9220 seems like a similar issue, but approaching from a slightly different angle.

I believe "creating a new revision only if a change is applied" is the key.
