### ISSUE TITLE
would be nice to have ability to have install/uninstall setup/removal script 

### ISSUE THREAD

**Issue by pcurewitz** [helm/helm#9524]
It would be nice to run setup bash commands on the kubemaster through helm. Example for a particular deployment I want to have the volume mount created. variables populated,  etc.
this way if I run the helm install command it does everything and I don't have run a separate script to do setup stuff first 

Output of `helm version`:

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by pcurewitz** [comment]
I did and I an not sure if that will work I am looking to run these directly on the kubemaster that I am running the helm install command on. I thought helm hooks are only run in the cloud.

**Comment by mattfarina** [comment]
The hooks are run in the cluster just like other workloads. They are run on the nodes where ever those may be.

When you say kubemaster, what do you mean?
