### ISSUE TITLE
Error: "helm upgrade" requires 2 arguments

### ISSUE THREAD

**Issue by mrwalters1988** [helm/helm#9525]
Output of `helm version`:

version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS

When running the following command, I get the following error: 

`helm upgrade twistlock /tmp/hc-exports-XXXXlNHbbK/export-twistlock/twistlock-defender/ --install --namespace ***** --set cluster=***** --set admission_cert=******* --set admission_key=******* --set client_cert=******* --set client_key=******* --set ca_cert=******* --set service_parameter=*******

Error: "helm upgrade" requires 2 arguments`

The two arguments are present. This same command works elsewhere. I'm not sure why this is failing here.

**Comment by bacongobbler** [comment]
It is possible that one of your `--set` arguments is being interpreted as a positional argument. I would try removing them all and testing them in order to see if one of them reintroduces the error. Then we can determine next steps.

**Comment by bumarcell** [comment]
I looked again into it and tried with another Jira project. The problem was that my first project didn't have the field 'Labels' in its screen; Good to know that it's mandatory
Sorry for bothering :)

**Comment by sleeyax** [comment]
I was having the same issue when trying to override values with `--set` using environment variables. But then dumb me realized I misspelled one variable (`$PROD` instead of `$PRODUCTION`), which caused my environment to insert an empty string resulting in this behavior. Maybe your issue is something similar.

**Comment by mrwalters1988** [comment]
Hey all, bacongobbler has the correct idea. Stepped through and figured out the issue.
