### ISSUE TITLE
[Feature]: Add extra .values.yaml files in a Helm chart which can be used when using helm install

### ISSUE THREAD

**Issue by thernstig** [helm/helm#9528]
Normally we have one `values.yaml` file in the chart directory. I would like to add an extra values file such as `small-deployment.values.yaml`. When a user installs my chart, the could opt to use a flag like `--bundled-values-file small-deployment.values.yaml` to install with that one instead of the default `values.yaml`.

Extra: Or it could be a comma-separated list to use both (specified in the order the user wish, where the first specified takes precedence over the second etc.).

The reasoning is that the only way to achieve this today is for the user to use a `helm pull --untar` and then use `--values small-deployment.values.yaml` which is annoying.

This could also be great in development. If I have a private helm chart I could add a `development.values.yaml` that users easily can use to e.g. turn of authentication (in case of an webapp) and other things that might be problematic if you want something running quickly.

Output of `helm version`:
```sh
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"}
```

Output of `kubectl version`:
```sh
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:52:24Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-06-03T10:06:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Custom cloud.

**Comment by mattfarina** [comment]
This topic has come up in the past and it's where the separation of concerns comes in.

Helm is a package manager (like apt, yum, etc) and we try to keep the scope constrained to just this area. Other tools (e.g., helmfile, flux and their Helm operator) deal with other layers in the stack. They can use Helm and charts while taking on the multi-environment management. There are other tools, too.

If you really want this capability, it's possible to add it as a template function. A value in the normal `values.yaml` file can have the name and then you load the other yaml file and merge the values together. I think there is an example in the issue queue somewhere.

**Comment by antaloala** [comment]
I agree with @mattfarina. [Helmfile ](https://github.com/roboll/helmfile) adds declarative (i.e. manifest driven) handling of a (set of) Helm chart(s), additionally supporting the "environments" concept to allow to define and apply different values.yaml for each enviornment/flavor, all in a declarative way.
Flux v2 and its helm-controller (part of the new GitOps toolkit) is also providing support for this.
 
Keeping the "[Do One Thing and Do it Well](https://en.wikipedia.org/wiki/Unix_philosophy#Do_One_Thing_and_Do_It_Well)" UNIX principle and being able to connect all these pieces is what allows to get this set of great technologies where ones are based from and enrich the others.
