### ISSUE TITLE
Error: unable to write YAML output: error converting JSON to YAML: yaml: control characters are not allowed

### ISSUE THREAD

**Issue by eeijlar** [helm/helm#9532]
Output of `helm version`
version.BuildInfo{Version:"v3.2.2", GitCommit:"a6ea66349ae3015618da4f547677a14b9ecc09b3", GitTreeState:"clean", GoVersion:"go1.13.12"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:43:56Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Rancher/GKE

When I run `helm install`, I get the following error message:

```
LAST DEPLOYED: Wed Mar 24 10:58:44 2021
NAMESPACE: johnl
STATUS: deployed
REVISION: 1
TEST SUITE: None
USER-SUPPLIED VALUES:
Error: unable to write YAML output: error converting JSON to YAML: yaml: control characters are not allowed
helm.go:84: [debug] error converting JSON to YAML: yaml: control characters are not allowed
unable to write YAML output
helm.sh/helm/v3/pkg/cli/output.EncodeYAML
        /home/circleci/helm.sh/helm/pkg/cli/output/output.go:110
main.statusPrinter.WriteTable
        /home/circleci/helm.sh/helm/cmd/helm/status.go:138
helm.sh/helm/v3/pkg/cli/output.Format.Write
        /home/circleci/helm.sh/helm/pkg/cli/output/output.go:56
main.newInstallCmd.func1
        /home/circleci/helm.sh/helm/cmd/helm/install.go:122
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:83
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1357
```

It is not possible to know which file contains the offending control characters. Is it possible to add the line number, and yaml file to this error message?

**Comment by eeijlar** [comment]
Actually this looks very like https://github.com/helm/helm/issues/9532

**Comment by mattfarina** [comment]
Figuring out the exact location where a problem occurred is not so easy. Pull requests welcome to figure out how to do it.

Helm uses the same YAML parsing/writing library as Kubernetes. It appears it has encountered a YAML control character in the data which is causing issues.

**Comment by artemlops** [comment]
Hi! I was surprised that `helm template` can't simply render the template *before* parsing it as a YAML file -- therefore the difficulty to work with it. Related [stackoverflow question](https://stackoverflow.com/questions/59564379/how-to-debug-helm-chart-errors-like-error-converting-yaml-to-json-yaml-mappin) with no generic solution.

Question to the maintainers of Helm: would you welcome such a functionality like `helm template --render-only` that will just print the constructed YAML-like output before it is tried to be parsed?

**Comment by bacongobbler** [comment]
> Question to the maintainers of Helm: would you welcome such a functionality like `helm template --render-only` that will just print the constructed YAML-like output before it is tried to be parsed?

I believe that's what `helm template` does today, no? It renders the templates and displays the output without any parsing. [Just a straight string dump to standard output](https://github.com/helm/helm/blob/43853ea772e779b617b011a8d4e69205636fa4f9/cmd/helm/template.go#L86).

The issue OP raised was with `helm install`. Can you clarify what issue you're experiencing? If it's separate from OP's issue, can you open a separate ticket?

**Comment by artemlops** [comment]
Hi @bacongobbler, here's the separate issue for the behaviour I experienced: https://github.com/helm/helm/issues/9663
Please feel free to close it if it's a duplicate.

**Comment by SilverTux** [comment]
> > Question to the maintainers of Helm: would you welcome such a functionality like `helm template --render-only` that will just print the constructed YAML-like output before it is tried to be parsed?
> 
> I believe that's what `helm template` does today, no? It renders the templates and displays the output without any parsing. [Just a straight string dump to standard output](https://github.com/helm/helm/blob/43853ea772e779b617b011a8d4e69205636fa4f9/cmd/helm/template.go#L157-L159).
> 
> The issue OP raised was with `helm install` - more specifically with the default output format (`--output table`).
> 
> Can you clarify what issue you're experiencing? If it's separate from OP's issue, can you open a separate ticket?

Hi,

You are right you can use helm template but sometimes it fails with the same error message as helm install --dry-run.
I've tried to create a test chart for this and my experience is that 1 out of 50 helm template command fails too.
On our production helm chart this problem appears more frequently if we introduce some indentation errors accidentally.

SilverTux

**Comment by eeijlar** [comment]
On further investigation, we discovered that removing the `--debug` option to helm made the error go away.
