### ISSUE TITLE
[v3] helm template fails looking for local-index.yml when specifying --repo

### ISSUE THREAD

**Issue by matticala** [helm/helm#9533]
Output of `helm version`:
`version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.16"}`

Errors:
```sh
❯ helm template traefik --repo https://helm.traefik.io/traefik
Error: failed to download "https://helm.traefik.io/traefik/traefik-9.18.0.tgz" (hint: running `helm repo update` may help)
```

```sh
❯ helm template traefik --repo https://helm.traefik.io/traefik --version 9.18.0
Error: failed to download "https://helm.traefik.io/traefik/traefik-9.18.0.tgz" at version "9.18.0" (hint: running `helm repo update` may help)
```

```sh
❯ helm template traefik --repo https://helm.traefik.io/traefik --version 9.18.0 --debug
install.go:173: [debug] Original chart version: "9.18.0"
Error: no cached repo found. (try 'helm repo update'): open /Users/***/Library/Caches/helm/repository/local-index.yaml: no such file or directory
helm.go:81: [debug] open /Users/***/Library/Caches/helm/repository/local-index.yaml: no such file or directory
no cached repo found. (try 'helm repo update')
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).scanReposForURL
	/private/tmp/helm-20210310-51670-30olmy/pkg/downloader/chart_downloader.go:352
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).ResolveChartVersion
	/private/tmp/helm-20210310-51670-30olmy/pkg/downloader/chart_downloader.go:175
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo
	/private/tmp/helm-20210310-51670-30olmy/pkg/downloader/chart_downloader.go:89
helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart
	/private/tmp/helm-20210310-51670-30olmy/pkg/action/install.go:675
main.runInstall
	/private/tmp/helm-20210310-51670-30olmy/cmd/helm/install.go:185
main.newTemplateCmd.func2
	/private/tmp/helm-20210310-51670-30olmy/cmd/helm/template.go:73
github.com/spf13/cobra.(*Command).execute
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850
github.com/spf13/cobra.(*Command).ExecuteC
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958
github.com/spf13/cobra.(*Command).Execute
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main
	/private/tmp/helm-20210310-51670-30olmy/cmd/helm/helm.go:80
runtime.main
	/usr/local/Cellar/go/1.16/libexec/src/runtime/proc.go:225
runtime.goexit
	/usr/local/Cellar/go/1.16/libexec/src/runtime/asm_amd64.s:1371
```

This causes IaC solutions like Pulumi to fail unless a manual `helm repo add` has been executed.

**Comment by cndoit18** [comment]
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"dirty", GoVersion:"go1.16.3"}

I have not found this problem in the current version I am using

**Comment by matteocalabro-tomtom** [comment]
![image](https://user-images.githubusercontent.com/66773159/119782735-d6b93580-becc-11eb-9975-cd33db4d9b3f.png)

Hello @cndoit18, are you able to run `template` with --repo?

**Comment by cndoit18** [comment]
> ![image](https://user-images.githubusercontent.com/66773159/119782735-d6b93580-becc-11eb-9975-cd33db4d9b3f.png)
> 
> Hello @cndoit18, are you able to run `template` with `--repo`?

![image](https://user-images.githubusercontent.com/55286565/119783443-ca9a9b80-beff-11eb-9178-51d4012347bf.png)
Yes, I can.

**Comment by cndoit18** [comment]
I can reproduce it now, when I empty the data in the cache folder, it goes wrong
![image](https://user-images.githubusercontent.com/55286565/119783866-3c72e500-bf00-11eb-95fb-51c89ccf82ff.png)

**Comment by cndoit18** [comment]
I will spend some time trying to deal with this issue and can assign it to me

**Comment by bacongobbler** [comment]
I cannot reproduce the original issue with Helm 3.6.0.

```
><> helm template traefik --repo https://helm.traefik.io/traefik --version 9.18.0 | head -n 5
---
# Source: traefik/templates/rbac/serviceaccount.yaml
kind: ServiceAccount
apiVersion: v1
metadata:
```

Can you please try again using the latest version.

**Comment by cndoit18** [comment]
> I cannot reproduce the original issue with Helm 3.6.0.
> 
> ```
> ><> helm repo list
> Error: no repositories to show
> ><> helm template traefik --repo https://helm.traefik.io/traefik --version 9.18.0 | head -n 5
> ---
> # Source: traefik/templates/rbac/serviceaccount.yaml
> kind: ServiceAccount
> apiVersion: v1
> metadata:
> ```
> 
> Can you please try again using the latest version.

![image](https://user-images.githubusercontent.com/55286565/120525085-56359000-c40a-11eb-9caf-0966b5ccdd0e.png)
I tried and it was a failure

**Comment by cndoit18** [comment]
> when I empty the data in the cache folder, it goes wrong

@bacongobbler  You can take a look at this

**Comment by bacongobbler** [comment]
Can you please verify whether https://helm.traefik.io/traefik/index.yaml is unreachable via `curl` on your machine?

**Comment by cndoit18** [comment]
> repopulated

Sorry, I didn't get it, is the execution of `helm init` a prerequisite to executing `helm template traefik --repo https://helm.traefik.io/traefik --version 9.18.0 | head -n 5`?
