### ISSUE TITLE
Jack -segmentation fault

### ISSUE THREAD

**Issue by phil123456** [helm/helm#9544]
Hi,

as I try to plug helm output to the system output in jack, I get a segmentation fault

I use linux (raspberry pi 4)

```
> helm -v
Helm 0.9.0
```

also
- I have to click on jack in the setup properties, is there no way to do this automaticaly ? 
- doing this does not display helm in jack graph, I have to use A2J which means Helm never really runs as a jack device

thanks for helping me on this

**Comment by bacongobbler** [comment]
I’m not sure this is the right project you’re looking for. This is Helm, the package manager for Kubernetes. The latest version is v3.5.3.
