### ISSUE TITLE
Join slack discussion channel

### ISSUE THREAD

**Issue by sirkubax** [helm/helm#9546]
it is stated in the Readme (https://github.com/helm/helm)
![image](https://user-images.githubusercontent.com/3442120/112818854-43a67f80-9084-11eb-9f8d-ca141e82935b.png)

but I cannot join the slack cannel
![image](https://user-images.githubusercontent.com/3442120/112818778-2c679200-9084-11eb-8f47-6fbb4aa47c77.png)

What is the procedure that allows you to access this channel and have a live discussion?

```
Don’t have an @get-an-invite-at.slack.kubernetes.io email address?
Contact the workspace administrator at Kubernetes for an invitation.
```

**Comment by sirkubax** [comment]
BTW, I was going to ask a lame question :) 
Where are now located charts that were previously published https://github.com/helm/charts (stable and incubator).
I was looking for a new place of that source code for helm, eg this one https://artifacthub.io/packages/helm/twuni/docker-registry and I guess I did not spot the place to click, I guess it is somewhere, but probably not that intuitive as former helm/charts/stable on github...

**Comment by hickeyma** [comment]
@sirkubax Re Helm Slack channels, they are part of the Kubernetes Slack workspace. When you go to [Kubernetes Slack workspace](https://kubernetes.slack.com/), you should see "Create an account" in the top right-hand side as shoen

![Screenshot 2021-03-29 at 11 15 43](https://user-images.githubusercontent.com/14892004/112822670-25d71b80-9080-11eb-8634-c1d29b802467.png)


When you create an account you should be able to login to the workspace. You can then browse the Helm channels and add them.

**Comment by hickeyma** [comment]
> Where are now located charts that were previously published https://github.com/helm/charts (stable and incubator).

Some details on depreaction of the repo: https://helm.sh/blog/charts-repo-deprecation/

If you search [Artificat Hub](https://artifacthub.io/) fr a chart you will get link to where it is now hosted. You can also check the README of the charts in the old repo and they will have a link to the now hosted and supported version of the chart.

**Comment by sirkubax** [comment]
Could you point me to a place where the link to source code is presented for this chart:
https://artifacthub.io/packages/helm/twuni/docker-registry
I see a link to a sourcecode to Docker image definition https://github.com/docker/distribution-library-image and in the 'original' deprecated chart I do not see a link to the new chart version
https://github.com/helm/charts/tree/master/stable/docker-registry
I believe it is https://github.com/twuni/docker-registry.helm, bu this one has closer name
https://artifacthub.io/packages/helm/phntom/docker-registry

I believe I'm missing the note of the new chart placement in the archived chart https://github.com/helm/charts/tree/master/stable/docker-registry
and missing a link to the source code (https://github.com/twuni/docker-registry.helm) of the current chart on this page
https://artifacthub.io/packages/helm/twuni/docker-registry

there is a link to the author
![image](https://user-images.githubusercontent.com/3442120/112853887-9a747f00-90ad-11eb-9dbd-5edfb8a566e7.png)
but it does not even redirect you to the github page, and there is a link to the homepage
![image](https://user-images.githubusercontent.com/3442120/112854041-bc6e0180-90ad-11eb-9078-54ce27b2fb8b.png)
 but also not the chart source code

**Comment by hickeyma** [comment]
@sirkubax Good catch on these, thanks.

This seems to be where the chart repo is: https://github.com/twuni/docker-registry.helm

For the other things, it would be worth raising issues as follows:

- In https://github.com/helm/charts, about adding the link in the chart README to the new repo
- In https://github.com/artifacthub/hub, to fix the links in the chart metadata

Hope this helps.

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!

**Comment by jwenjian** [comment]
Go to http://slack.kubernetes.io/ and input your email, you will get the invitation link in your email inbox
