### ISSUE TITLE
How to disable the 3-way Merge on upgrade

### ISSUE THREAD

**Issue by dsaydon90** [helm/helm#9547]
If I'm  changing manually some value (by using `kubectl edit`) in my `Deployment` workload (like: `command: ["sleep"]`) and then perform helm upgrade to my chart which doesn't has any `command` on the same `Deployment` workload  , it will use the 3-way Merge and will keep the old `command: ["sleep"]`

I couldn't find any **flag** to disable the 3-way Merge on `helm upgrade` so in my case I don't want that the helm upgrade will keep the manual change , in this case the `command: ["sleep"]` on my `Deployment` workload.

command: `helm -n <name space> upgrade --reset-values --install --atomic --wait --timeout 15m0s <release name> <chart path>`

note: I'm trying to avoid from using the `--force` command. In addition, the `--reset-values` didn't work.

Output of `helm version`: `version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}`

**Comment by bacongobbler** [comment]
https://helm.sh/docs/faq/#improved-upgrade-strategy-3-way-strategic-merge-patches

Let me know if you have any further questions after reading through the FAQ.

> I couldn't find any **flag** to disable the 3-way Merge on `helm upgrade` so in my case I don't want that the helm upgrade will keep the manual change , in this case the `command: ["sleep"]` on my `Deployment` workload.

To remove a value, you must provide a "null" value. i.e. `command: []` or `command: null`.

**Comment by bacongobbler** [comment]
Furthermore, `--force` changes the request from a PATCH to a PUT, effectively bypassing the 3-way merge patch strategy. It's not recommended unless

a) you understand the difference between the two operations,
b) you understand that this affects EVERY resource that the helm chart manages, and
c) a `--force` is indeed your intended operation (as in, you agree that a strategic merge patch over the live resources is not needed)

**Comment by dsaydon90** [comment]
Thank you @bacongobbler , I'll go with the the **empty** values

However, it might be a FR to handle this scenario
