### ISSUE TITLE
Config map values are not updated when running `helm upgrade CHART`

### ISSUE THREAD

**Issue by kkirilov91** [helm/helm#9556]
Hi guys. I'm having a chart that includes a config map. When I change the config in the `values.yaml` and run `helm upgrade CHART`, the value in the config map volume are not changed. I have to uninstall/install the chart in order to get the new configs passed to the pod.
The things looks even stranger as we do have other services, which are following the same chart template and everything's fine there.

Have you guys heard of such issues before and do you know how we can debug it to see why the configs are not reset? Or can you propose any workaround, other than reinstalling the chart?

Output of `helm version`:
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Self-hosted Kubernetes cluster on AWS

**Comment by mattfarina** [comment]
From your comment I'm going to assume the pod (or deployment, statefulset, etc) is not changing. If that changed it would automatically pick up the new configmap version.

If this is your situation, there is a documented method for handling it at https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments

If it isn't, please let us know some more details.

**Comment by kkirilov91** [comment]
Thanks for the quick response. We've already tried those option, but unfortunately it doesn't change anything. When I run `helm upgrade ... --dry-run`, i'm able to see the new annotation in deployment, but the configs are still not changed.
![image](https://user-images.githubusercontent.com/6529147/113253833-82c81100-92ce-11eb-818c-a5bb31a9a6c3.png)

Here are some more details about our setup. We are using a library chart which provides templates for our services. The config map template looks like this:
```
{{- define "template-service.configmap" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
{{- range $key, $val := .Values.configMap }}
{{ $key | indent 2}}: |-
{{ $val | indent 4 }}
{{- end}}
{{- end -}}
```

The values.yaml contains the following section:
```
configMap:
  application.yml: |-
    property1: 1
    property2:
      property3: 3
```

This template is used in all of our older services and it works fine, recently we introduces a new service, which is using the same template, but the configmap doesn't change when values.configMap is changed and helm upgrade is executed.

![image](https://user-images.githubusercontent.com/6529147/113256564-01727d80-92d2-11eb-9d80-8bcb7ae65fdf.png)
![image](https://user-images.githubusercontent.com/6529147/113256336-b9ebf180-92d1-11eb-87be-8c932fe3d74b.png)

**Comment by kkirilov91** [comment]
Ok, we've managed to find out what is actually happening. The new services was install using the following command:
`
helm install CHART **-f values-dev.yaml** --set ...
`
which reflected into saving the values-dev.yaml's content into the chart's values. Then subsequent helm upgrades was using the initial values-dev.yaml content, because of the --reuse-values flag(which is true by default). And since the configmap values are inside the values-dev.yaml, they never get re-applied.
