### ISSUE TITLE
Cache and use cache of charts

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#9561]
Helm has a cache of the `index.yaml` files and it puts a copy of the Helm chart in the cache but it does not use the file from the cache (as it can't). So, it downloads the file every time.

**Why it can't use the file in the current cache**

If two repositories have a chart with the same name and version it will be seen as the same in the current cache. Even if the content is different. So, it cannot be used on the grounds of security and safety.

**What could be used for a cache?**

A content addressable cache could be used. `index.yaml` files contain a digest for the chart. Caching by digest would allow two charts from different repos with the same name and version to not collide. And, if the same chart is copied from one repo to another it would only need one entry in the cache.

This is, overall, a placeholder issue for this caching feature.

**Comment by mattfarina** [comment]
This generally seems to make sense. Given the conversation in the Helm developer call, I think this needs to have a HIP. There are some things the HIP should cover such as clearing the cache and skipping the cache.

**Comment by dragonchaser** [comment]
I am currently working on an implementation of this at https://github.com/dragonchaser/helm/tree/add_download_cache atm I have a base implementation and I am adapting the tests. Will PR as soon as I am done (to start a discussion).

**Comment by Ornias1993** [comment]
It still a feature that is relatively important for bug chart repo's.
Bump stale.

**Comment by enesunal** [comment]
This would be really helpful. Is there any update?

**Comment by dragonchaser** [comment]
There is an ongoing discussion in https://github.com/helm/community/pull/185 about the cache in general. If you want to see this maybe contribute there.
