### ISSUE TITLE
Could not resolve host: https://get.helm.sh/ 

### ISSUE THREAD

**Issue by traviscrist** [helm/helm#9563]
It seems that https://get.helm.sh/ is unreachable right now. 

```sh
curl https://get.helm.sh/helm-v3.4.0-linux-amd64.tar.gz
curl: (6) Could not resolve host: get.helm.sh

curl https://get.helm.sh/
curl: (6) Could not resolve host: get.helm.sh
```

Locally and in our CI (CircleCI) it seems that we cannot reach https://get.helm.sh/. Is this occurring for anyone else?

**Comment by bacongobbler** [comment]
Can confirm. https://portal.azure.com appears to be down right now as well.

https://status.azure.com/en-us/status

> We are currently investigating reports of an issue affecting Azure DNS. More information will be provided as it is known.

This message was last updated at 21:59 UTC on 01 April 2021

**Comment by leandroluk** [comment]
I'm also having problems with the helm !!!

**Comment by traviscrist** [comment]
This seems to have resolved itself, closing it out since this was an Azuze issue as pointed out above. Thanks!
