### ISSUE TITLE
helm template validation failure without --output-dir

### ISSUE THREAD

**Issue by Jean-Daniel** [helm/helm#9565]
When generating a template, validation may fails when `--output-dir` is not specified because of `invalid ownership metadata` errors. When generating the same template into an output dir, everything works fine.

```
# add cilium repo
helm repo add cilium  https://helm.cilium.io/
helm repo update
# generate and install cilium
helm template --validate -n kube-system -f ../components/cluster/cilium/values.yaml  cilium cilium/cilium | kubectl apply -f -

# generate the template again (using validate) -> failure
helm template --validate -n kube-system -f ../components/cluster/cilium/values.yaml  cilium cilium/cilium
Error: rendered manifests contain a resource that already exists. Unable to continue with install: ServiceAccount "cilium" in namespace "kube-system" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "cilium"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "kube-system"

# generate the same template into an output-dir -> success
helm template --validate -n kube-system -f ../components/cluster/cilium/values.yaml --output-dir test cilium cilium/cilium
coalesce.go:163: warning: skipped value for eni: Not a table.
wrote test/cilium/templates/cilium-agent-serviceaccount.yaml
wrote test/cilium/templates/cilium-operator-serviceaccount.yaml
…
```

Output of `helm version`:
```
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.16"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.0-rc.0", GitCommit:"6b526c57934f310f9039309098afaf7fc96a63c5", GitTreeState:"clean", BuildDate:"2021-03-26T21:44:24Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Self hosted.

**Comment by bacongobbler** [comment]
At first glance, this appears to be an issue with the cilium chart's templates. Can you please open a ticket with the cilium maintainers so they can look further into this?

If it determined that an issue is present in Helm, we can follow up after the issue has been isolated with a simple example. However since this is the first report of its kind I believe this is an isolated incident with the cilium chart.

https://github.com/cilium/cilium/issues

Thanks!

**Comment by bacongobbler** [comment]
If you can reproduce the issue with another chart, we can reopen this and look into the issue at-hand.

**Comment by bacongobbler** [comment]
That being said, as the error suggests it does appear that you already have a serviceaccount already installed. Please make sure to purge your cluster of any existing resources from prior installations before attempting to reinstall a chart. In this case, `kubectl delete -n kube-system cilium` ought to do the trick.

**Comment by Jean-Daniel** [comment]
The service account is created by helm on the first invocation.
That's why I consider it being a bug that helm does report this error on second invocation.

Moreover, the inconsistency between invocation with and without --output-dir is also suspicious.

**Comment by Jean-Daniel** [comment]
> If you can reproduce the issue with another chart, we can reopen this and look into the issue at-hand.

Reduce test case attached here. 

[mychart.zip](https://github.com/helm/helm/files/6290680/mychart.zip)

```
helm template --validate -n default mychart ./mychart/ | kubectl apply -f -

# Generate the template into a dir works fine:
helm template --validate -n default --output-dir output mychart ./mychart/

# Generate the template without output dir fails:
helm template --validate -n default mychart ./mychart/
Error: rendered manifests contain a resource that already exists. Unable to continue with install: ServiceAccount "mychart" in namespace "default" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "mychart"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "default"
```

**Comment by bacongobbler** [comment]
Thank you. It was unclear from your first comment that you were specifically pointing out the inconsistency in behaviour between `--validate` and `--validate --output-dir`.

Re-opening. Please feel free to work on afix.

**Comment by bacongobbler** [comment]
https://github.com/helm/helm/blob/a499b4b179307c267bdf3ec49b880e3dbd2a5591/pkg/action/action.go#L105

**Comment by kevwil** [comment]
I've just run into this error as well. The template output has previously been applied to the cluster, so `--validate` performs the same checks as `helm install` would, and throws this "invalid ownership metadata" error. When using the `--output-dir` argument, the error is not thrown.

I'm curious how to fix this ownership metadata issue. It seems perhaps an inconsistency between the validation behavior and the templates in the output of `helm create` which do not create the annotations that seem to be required.
