### ISSUE TITLE
helm plugin install fails if branch inside local cache does not exists anymore

### ISSUE THREAD

**Issue by jkroepke** [helm/helm#9567]
Output of `helm version`:
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.16"}

Hi!

I recently change my default branch for a plugin from master to main.

All user running `helm plugin install https://github.com/jkroepke/helm-secrets` before the branch rename, getting an error now while running `helm plugin install`

```
% helm plugin install https://github.com/jkroepke/helm-secrets --debug
[debug] vcs_installer.go:162: updating https://github.com/jkroepke/helm-secrets
Error: Unable to update repository: exit status 1
```
Look at the local cache, a `git pull` is failing, too.

```
% git -C ~/Library/Caches/helm/plugins/https-github.com-jkroepke-helm-secrets status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
% git -C ~/Library/Caches/helm/plugins/https-github.com-jkroepke-helm-secrets pull
Your configuration specifies to merge with the ref 'refs/heads/master'
from the remote, but no such ref was fetched.
```

Workaround:

Clear the local cache

```bash
rm -rf "$(helm env HELM_CACHE_HOME)"
```

Reference: https://github.com/jkroepke/helm-secrets/issues/98

**Comment by bacongobbler** [comment]
This is because helm's plugin system relies on `git pull` to fetch updates from the upstream repository. Because you switched the branch name, `git pull` can no longer find the `master` branch to pull from.

To fix this you will have to either go into your existing plugin directory and update the remote branch to `main`, or uninstall and reinstall the plugin to fetch the new default branch.

Hope this helps.

**Comment by bacongobbler** [comment]
`git fetch origin main && git checkout main` from the plugin directory ought to do the trick.

**Comment by jkroepke** [comment]
@bacongobbler 

Sure.

I but I didn't not expect to run such command from a cache directory, that why I raise a issue here.

**Comment by bacongobbler** [comment]
What are you suggesting?

By changing the branch name and deleting the old branch in your repository, a plugin has no way to determine how to fetch its updates. I would argue the system is working as expected: the source is missing, so the plug-in cannot fetch updates and returns an error.

This is effectively the same as deleting a package from a package repository. The user now has to intervene and point the plug-in at the corrected source.

**Comment by jkroepke** [comment]
> What are you suggesting?

I have two suggestions:

1. Clear cache if helm tries to run update on a cache that fails, then do a clean install
2. Do not use a cache in general for installing plugins.
