### ISSUE TITLE
Helm Dependency Update handshake failure

### ISSUE THREAD

**Issue by DJoliet** [helm/helm#9568]
Output of `helm version`: version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}

Nexus Version: 3.20.3-01

I run this to add a nexus configured for certificate login:
`helm repo add nexus https://{hostname}/repository/{repo} --ca-file {path to ca file} --cert-file {path to cert file} --key-file {path to key file}`
It succeeds.
Then I run this:
`helm repo update`
It succeeds.
Then I run this:
`helm pull nexus/{chart name} --version {chart version}`
It succeeds.
However when I have an umbrella chart like this:
```
apiVersion: v2
name: {chartname}
description: A Helm Chart for Kubernetes
icon: {url to icon}
type: application
version: {version}
appVersion: {version}
dependencies:
  - name: {service}
     repository: "@nexus"
     version: ">= 0.0.0-0"
```
And I run this:
`helm package -u {location of umbrella chart}`
It returns this:
```
Error: could not download https://{hostname}/repository/{repo}/{chart name}-{chart version}.tgz: Get "https://{hostname}/repository/{repo}/{chart name}-{chart version}.tgz": remote error: tls: handshake failure
helm.go:94: [debug] Get "https://{hostname}/repository/{repo}/{chart name}-{chart version}.tgz": remote error: tls: handshake failure
could not download https://{hostname}/repository/{repo}/{chart name}-{chart version}.tgz
helm.sh/helm/v3/pkg/downloader.(*Manager).downloadAll
             /home/circleci/helm.sh/helm/pkg/downloader/manager.go:310
helm.sh/helm/v3/pkg/downloader.(*Manger).Update
            /home/circleci/helm.sh/helm/pkg/downloader/manager.go:172
main.newPackageCmd.func1
            /home/circleci/helm.sh/helm/cmd/helm/package.go:99
github.com/spf13/cobra.(*Command).execute
            /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
            /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
            /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
           /home/circleci/helm.sh/helm/cmd/helm/helm.go:93
runtime.main
           /usr/local/ho/src/runtime/proc.go:203
runtime.goexit
          /usr/local/go/src/runtime/asm_amd64.s:1373
```
Can't do anything to get it working. My workaround has been a script that pulls down all of the charts to a local directory and then using the file:// dependency setting. This is having issues of its own so I would like this fixed.

**Comment by bacongobbler** [comment]
You will need to add the ca file as well as the cert file to your dependency tree. These are the `certFile` and `keyFile` properties in your dependency subtree.

https://github.com/helm/helm/blob/c9fe3d118caec699eb2565df9838673af379ce12/pkg/repo/chartrepo.go#L41-L51

**Comment by bacongobbler** [comment]
To give some background context... The dependency system has been unmaintained for several years now, as the maintainer who worked on the dependency system stepped down a few years back. It's probably due for a rewrite to fix issues such as this.
