### ISSUE TITLE
Helm doesn't update 'adopted' custom resource

### ISSUE THREAD

**Issue by FNaughton** [helm/helm#9570]
I've a CRD created by a script prior to helm chart install. Up to now the associated custom resource (CR) was also created manually. Going forward I want to manage the CR as part of the helm chart.
Following description here - https://github.com/helm/helm/pull/7649 - I annotated and labelled the CR. I also added the CR to the templates directory of the helm chart, with some value changes.
When I run `helm upgrade --install --namespace app-deploy-namespace-name myhelm ./path/to/helmchart/`, the helm chart deploys successfully, but the CR is not updated as expected.

For comparison, I've done the same with a config map in place of the CR and it updates as expected.
Looking for confirmation that this should work for a CR, and if so, suggestions as to what I'm missing.

Output of `helm version`: version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"}

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0+7070803", GitCommit:"70708036fc265771f8d0a45598209018a8b9bd3e", GitTreeState:"clean", BuildDate:"2020-12-05T12:01:07Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Openshift 4.6.9

**Comment by FNaughton** [comment]
Originally posted on slack - https://kubernetes.slack.com/archives/C0NH30761/p1617356958332000

**Comment by FNaughton** [comment]
Steps taken to test:

1. Create CRD
2. Manually create CR
3. Annotate/label CR as per post above
4. Run helm upgrade --install --namespace app-deploy-namespace-name myhelm ./path/to/helmchart/

Note testcr custom resource in templated folder in chart has different values
Expectation:
The testcr will be updated to contain values in helm chart
Actual:
testcr remains unchanged

**Comment by bacongobbler** [comment]
Hi @FNaughton. The workflow you are describing is not something we officially support or recommend, so performing these actions are not officially something we provide support for. However, it is interesting to hear that the CR will not be updated after being recognized as a resource.

Let us know what you find out.

**Comment by FNaughton** [comment]
Thanks for the info @bacongobbler. I understood that this was the intended purpose of this feature - https://github.com/helm/helm/pull/7649? It's not clear however, if it applies to native k8s resources only, or if it should work if Helm also manages the CRD in question.
 
Aside from that, is there an alternative approach to adopting a CR as described above? Deleting the resource isn't an option in production.

**Comment by just1900** [comment]
still valid
Same issue here, this seems like a bug since #7649 is trying to adopt resources with specific annotation and labels.
