### ISSUE TITLE
helm package drops quotes in Chart.yaml

### ISSUE THREAD

**Issue by wingsofovnia** [helm/helm#9571]
`helm package` drops quotes in `Chart.yaml` that may lead to invalid charts.

For example, `Chart.yaml` allow optional `annotations`, a list of annotations keyed by name. These must be string key-values. In most cases Helm dropping quotes doesn't cause any issues, but sometimes it can lead to invalid values, not caught by `helm lint` and other checks.

```
apiVersion: v2
name: "my-app"
version: "1.0.0"

annotations:
  revision: "26424981a4"
```

After running `helm package`, quotes get stripped.
```
❯ helm package .
Successfully packaged chart and saved it to: my-app-0.0.1.tgz
❯ tar -axf my-app.tgz my-app/Chart.yaml -O | grep annotations -A 2
annotations:
  revision: 26424981a4
```

As you may guessed, revision contains a git hash. In rare cases, they have `e` on length-2 position, for example, `26424981e4` and this is being parsed incorrectly as a scientific notation. Such a chart cannot be uploaded to a helm repository.

It can be related to the underlying yaml library. This may be related: https://github.com/helm/helm/issues/4262

Output of `helm version`:
```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

Output of `kubectl version`:
_irrelevant_

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
_irrelevant_

**Comment by bacongobbler** [comment]
also relevant: https://github.com/helm/helm/issues/9541

**Comment by wingsofovnia** [comment]
@bacongobbler shouldn't it be categorised as a `(bug)`?
