### ISSUE TITLE
helm uninstall garbage collection PropagationPolicy

### ISSUE THREAD

**Issue by bolsunovskyi** [helm/helm#9572]
It would be great to have ability to set PropagationPolicy during helm uninstall. 
I'm talking about this hardcoded value here https://github.com/helm/helm/blob/main/pkg/kube/client.go#L386 
I need to have ability to set PropagationPolicy to Foreground so helm will wait until all child references will be deleted.

I can implement this behavior with additional flag to uninstall command and send a pull request. What do you think ?

**Comment by bacongobbler** [comment]
How would flags like `--wait` handle the change in deletion propagation policies? Why not implement `helm delete --wait` as recommended in #2378? Or would

I would suggest going through the HIP process if this is something you are interested in tackling. 

https://github.com/helm/helm/blob/main/CONTRIBUTING.md#proposing-an-idea
