### ISSUE TITLE
A cat function without the extra space between the parameters.

### ISSUE THREAD

**Issue by gaojx** [helm/helm#9574]
The function cat adds an space between the parameters. This is very unusual for programming languages, and caught lots of developers by suprise.

I have this nice code:

 args: "ARGS='bind-name={{ .name }} {{ $.Values.args }} {{ empty .port | ternary "" cat("port=" .port) }}'"

Except that the extra space in "port= 123". So here we need to have a cat function without adding the extra spaces.

BTW, without using the {{ if }}, anyone has a elegant solution to my problem?

**Comment by bacongobbler** [comment]
Please file issues related to the output of specific template function calls to [sprig](https://github.com/Masterminds/sprig). That is the library which provides these functions.

Thanks.

**Comment by bacongobbler** [comment]
Looking at the code this appears to be by design.

https://github.com/Masterminds/sprig/blob/3ac42c7bc5e4be6aa534e036fb19dde4a996da2e/strings.go#L103-L107

**Comment by bacongobbler** [comment]
To give you some suggestions... Use `join` or `printf` instead. `printf` is more likely relevant as you're trying to format a string.

```
printf "port=%d" .port
```
