### ISSUE TITLE
Helm 3 behind a proxy on Windows 10

### ISSUE THREAD

**Issue by cospeedster** [helm/helm#9576]
# Problem
I'm trying to get __Helm 3__ running behind a proxy on a __Windows 10__ Client. First of all you can print an set your proxy by using this commands in __PowerShell__:

```powershell
# Show proxy configuration
netsh winhttp show proxy

# Set proxy configuration
netsh winhttp set proxy proxy-server="truncated" bypass-list="truncated"
```

When I try to add an external repo I got the following error:
```powershell
helm repo add elastic-external https://helm.elastic.co
Error: looks like "https://helm.elastic.co" is not a valid chart repository or cannot be reached: Get "https://helm.elastic.co/index.yaml": dial tcp 34.120.127.130:443: connectex: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat.
```

Powershell itself uses the proxy configuration already. I checked the connectivity to the repo with the following command:
```powershell
Write-Host (Invoke-WebRequest https://helm.elastic.co/index.yaml).StatusCode
200
```

Can anybody help me?

# Additional Information
Output of `helm version`:
```
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.12", GitCommit:"7cd5e9086de8ae25d6a1514d0c87bac67ca4a481", GitTreeState:"clean", BuildDate:"2020-11-12T09:11:15Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
on prem [RancherOS](https://rancher.com/docs/os/v1.x/en/)

**Comment by bacongobbler** [comment]
Hi @cospeedster. Have you looked at prior support tickets that discuss how to use Helm in a proxied environment? I believe this question has been asked and answered many times before. For example #9133.

**Comment by cospeedster** [comment]
Hi @bacongobbler,

thank you for your reply. I just thought that the environment variables `HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY` only works on linux hosts.

Now, when I set the environment variables in PowerShell on Windows 10 it works:

```powershell
# Set proxy via environment
$env:HTTP_PROXY="truncated"
$env:HTTPS_PROXY="truncated"

# Add external repository
helm repo add elastic-external https://helm.elastic.co
"elastic-external" has been added to your repositories
```

Best Regards
