### ISSUE TITLE
mergeOverwrite with undefined values, breaking change in helm 3.5.x

### ISSUE THREAD

**Issue by labarje** [helm/helm#9587]
Output of `helm version`: version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.16"}

Output of `kubectl version`: this is not relevant here, as I am reporting a pure templating issue.

Cloud Provider/Platform (AKS, GKE, Minikube etc.): MacOS catalina (version 10.15.7)

The `mergeOverwrite` method in version 3.4.x of helm had the following behavior regarding boolean values, right to left:
- A `false` value would override a `true` one.
- A non-defined value would not override a `true` one.

The behavior has changed in version 3.5.x, as a non-defined value now overrides `true` and produces a `null` in the result of the operation.

This [dummy chart (zipped)](https://github.com/helm/helm/files/6288732/dummy-0.0.1.tgz.zip) allows to reproduce the above with the following bash commands:
```bash
$ helm version
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.16"}
$ helm template dummy dummy-0.0.1.tgz --debug 2>/dev/null
---
# Source: dummy/templates/dummy.tpl
Explicit false value overrode, as expected.
An undefined value should not override (result is null)!

$
$ helm3.4.2 version
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}
$ helm3.4.2 template dummy dummy-0.0.1.tgz --debug 2>/dev/null
---
# Source: dummy/templates/dummy.tpl
Explicit false value overrode, as expected.
Undefined value did not override, as expected.
```

I cannot find any log (in the helm release notes or in the sprig library release notes) documenting this change, which is definitely breaking. My opinion is that the 3.4.x behavior makes a lot more sense, as undefined should not mean `null` (overriding with `null` should only happen if `null` is explicitly specified).

If some limitation prevents to make the distinction between undefined and `null`, and the community decision is to keep the current behavior over the 3.4.x one because some prevalent use cases call for it, I'd say it at least should be documented...

**Comment by bacongobbler** [comment]
If you can determine

1) what caused the regression, and
2) how to fix it

We'd welcome a patch.

**Comment by labarje** [comment]
My apologies, but I am only a helm user. I do not program in golang (yet?), so I am not going to be able to figure out the exact location of the code change that caused the regression nor how to fix it.

However, I understand things a bit better since I entered the issue:
* It seems that the main purpose of `mergeOverwrite` is to provide a merge method that does overwrite with 'falsy' values (something the `merge` method does not). In both the previous version and the current one, it is doing that with booleans (`false` overwrites `true`). On the other hand, in the previous version, it was not doing it with `null` (an explicitly set `null` in the argument on the right did not overwrite a non-null value in the argument on the left); my best guess is that somebody figured out this was inconsistent and fixed it (somewhere...). 
* The regression I am experiencing is a side-effect, caused by the fact that golang does not differentiate between `null` and `undefined`. I don't know enough about the language or the sprig or helm implementation to know how difficult it would be to work around that (seems to me the best fix would be to fix the language itself, because differentiating the two *is* useful).
* I was able to fix my charts relatively easily, by removing the value entirely in the overriding map, _i.e._ going from:
```yaml
defaults:
  shouldOverride: true
  shouldNotOverride: true
overrides:
  shouldOverride: false
  shouldNotOverride:
```
to:
```yaml
defaults:
  shouldOverride: true
  shouldNotOverride: true
overrides:
  shouldOverride: false
```
in the values file from the dummy example I included in the original post.

In my actual charts, the defaults are in a library chart pulled by a bunch of application charts. So, what I am losing with this change is the ability to show values that it may make sense to override in the values file of the application charts (using the values file as a way to document useful command line options). Of course, I can always comment the line instead of removing it, but if I end up with an empty `overrides` map, I need to set it as `{}` to avoid nil pointer exceptions, like this:
```yaml
overrides: {}
  # comment out the next line and remove the {} above if you need to override
  # possibleOverride: true
```

I feel it's a bit clunkier, but it's certainly not something for which I would have requested a change if I had been able to figure it out from the `mergeOverwrite` documentation (or if the current behavior had been the one implemented from the beginning).

So, all this to say, I think this issue could be closed by simply clarifying the `mergeOverwrite` documentation. But, before you ask, I don't think I am invested enough to take the time to learn how to contribute to the sprig library repository, even if it's just for documentation :-) ...

**Comment by anthony-pastor** [comment]
[We're also impacted.](https://github.com/helm/helm/issues/9583)
Any track on this @bacongobbler?
