### ISSUE TITLE
Install subchart after based on a coniditon

### ISSUE THREAD

**Issue by shahriak** [helm/helm#9589]
Hello,

I have a requirement where I need to install a subchart but need to wait for some crds to be installed before installing the subchart. How can i achieve this?

Is it possible to sleep for some seconds before installing a subchart?

Output of `helm version`:
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"5de7fd1f9555368a86eb0f8f664dc58055c17269", GitTreeState:"clean", BuildDate:"2021-01-18T09:31:01Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS, linux

**Comment by bridgetkromhout** [comment]
Hi, @shahriak - please look at https://helm.sh/docs/intro/using_helm/#helpful-options-for-installupgraderollback - I think that the `--timeout` or `--wait` flags may help in the case you describe. Please let us know; thanks!
