### ISSUE TITLE
Sub chart of sub chart is don't care

### ISSUE THREAD

**Issue by karimiehsan90** [helm/helm#9593]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

Hi! I have an umbrella chart named my project name. In the Chart.yaml file, I added a dependency to another chart named zookeeper-exporter.
The zookeeper-exporter chart is provided in another one and has been deployed to a helm repository. The zookeeper-exporter chart depends on another chart named zookeeper. In the values.yaml file of the zookeeper-exporter chart, a variable introduced to make a condition for the zookeeper dependency. The variable is in this style:

```yaml
zookeeper:
  enabled:
```

When I am installing the umbrella chart, I set these values:

```yaml
zookeeper-exporter:
  zookeeper:
    enabled: false
```

But it installs objects in the zookeeper chart too.

**Comment by bacongobbler** [comment]
I think I explained this in another issue... But as far as the dependency resolver is concerned, sub-subcharts are on the same subtree level as a subchart.

In other words, try this instead in your values.yaml:

```
zookeeper:
  enabled: false
```

Hope this helps.

**Comment by karimiehsan90** [comment]
Thank you for your response. I tried your solution as well and it didn't solve my problem. Even if it solves my problem, it isn't a good solution. Suppose that we have a chart in the umbrella chart named Hadoop that depends on the zookeeper too. And the umbrella chart directly depends on the zookeeper chart. In this case, if I wanna disable the zookeeper for my local environment (Hadoop in my local environment isn't HA.) or disable the zookeeper of the zookeeper-exporter in all environments or disable the zookeeper of the hadoop in all environments, I have a solution:

```
zookeeper:
  enabled: false
```

So it's ambiguous.
