### ISSUE TITLE
Please include a flag to ignore values.yaml

### ISSUE THREAD

**Issue by xaocon** [helm/helm#9597]
Output of `helm version`:
`version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.16"}`

Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15", GitCommit:"73dd5c840662bb066a146d0871216333181f4b64", GitTreeState:"clean", BuildDate:"2021-01-13T13:22:41Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}`

I don't think this is available from looking in help but I could be wrong. I'm hoping for the ability to specify that `values.yaml` not be used as the base when upgrading / installing. Sometimes I track helm repos with git and add bits where needed and it's nice to not have to either remove things from the default values file or try to keep merging changes. I don't expect this to change the default behavior at all but some kind of flag to skip it would be nice. #3689 is similar but seems to have been opened for v2 and never brought forward.

**Comment by bacongobbler** [comment]
What is the expected user experience here? You'd still need to provide a values file to re-populate all of the values that were just nulled out.

https://github.com/helm/helm/blob/main/CONTRIBUTING.md#proposing-an-idea

**Comment by xaocon** [comment]
I've run into problems with this in a couple of charts and for me it's usually related to merged lists but it could come up with dictionaries as [well](https://helm.sh/docs/chart_template_guide/values_files/#deleting-a-default-key). It seems a common enough issue to have its own documentation. Usually the chart maintainer has some sensible default that we don't want/need in our values. It seems to me like a reasonable way to work with certain charts and less awkward than keeping track of all the values you need to null.

I'm going to go ahead and close since it's easy enough to come up with workarounds. It just seemed like pretty basic functionality that wouldn't break anyones workflow.
