### ISSUE TITLE
Create helm lint command

### ISSUE THREAD

**Issue by sgoings** [helm/helm#96]
In order to help people create new charts and maintain a high standard of quality within the charts repo, I'd like to see a `lint` command within `helm`. The exact specifics of what "linting" mean are up for discussion but at this point @gabrtv and I have discussed:

- is the Chartfile well formed?
- are the manifests well-formed?
- do the Docker images exist?
- is the heritage of the Docker images trusted?
- do the dependencies exist, and are the version constraints possible to match?

`helm lint` would then be run on charts that are submitted via PRs.

**Comment by technosophos** [comment]
And "are the manifests well-formed"

**Comment by technosophos** [comment]
"Do the dependencies exist, and are the version constraints possible to match?"

**Comment by michelleN** [comment]
:+1:

**Comment by sgoings** [comment]
Added both of @technosophos suggestions.

**Comment by michelleN** [comment]
Some of the criteria in this issue have been moved to https://github.com/helm/helm/issues/300
