### ISSUE TITLE
helm uninstall doesn't signal process like kubectl delete

### ISSUE THREAD

**Issue by jasonatball** [helm/helm#9600]
I'm trying to understand the helm uninstall process. I have a deployment which creates a Ruby microservice that dynamically creates other kubernetes deployments using [kubecclient](https://github.com/abonas/kubeclient) and thus are not "known" by helm. When I manually delete this deployment using kubectl my ```at_exit``` Ruby hook is called and shuts down all these dynamically created deployments. However when I ```helm uninstall``` they do not get deleted.

What does ```helm uninstall``` do to delete a deployment such that a pod process does not receive a signal to shutdown when calling ```kubectl delete deployment XXX``` causes the signal to be called?

Output of `helm version`:
```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Kind

**Comment by bacongobbler** [comment]
The code for Helm's uninstall logic can be found in `pkg/kube`. You can review the code yourself here: https://github.com/helm/helm/blob/a499b4b179307c267bdf3ec49b880e3dbd2a5591/pkg/kube/client.go#L273-L307

**Comment by jasonatball** [comment]
It looks like ```deleteResource``` eventually calls ```resource.NewHelper(info.Client, info.Mapping).DeleteWithOptions(info.Namespace, info.Name, opts)```. I can't find reference to DeleteWithOptions. Is this directly calling the kubernetes API server?

**Comment by bacongobbler** [comment]
The code for `DeleteWithOptions` can be found in Kubernetes' cli-runtime package. But in effect, yes, Helm is issuing API calls directly to Kubernetes to request that the resource be deleted.

https://github.com/kubernetes/cli-runtime

**Comment by jasonatball** [comment]
This may be related to how Ruby handles signals and how at_exit works but it's still a little confusing that kubectl and helm uninstall were different. It must be something different in the APIs vs what kubectl is using. I'm going to go in a different direction. Sorry for the noise. Thanks for helm!
