### ISSUE TITLE
Error: manifest does not contain exactly

### ISSUE THREAD

**Issue by Ruimingwang** [helm/helm#9606]
Output of `helm version`: 3.5.0

Output of `kubectl version`: v1.19.9

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by Ruimingwang** [comment]
I execute helm3 chart list ,resoult error :  **Error: manifest does not contain exactly**   ,but sometimes other server without this error

**Comment by bacongobbler** [comment]
Hi @Ruimingwang. In order to determine next steps we actually need some way to test and verify this error. That way we can determine a cause and a possible fix. Please provide more information necessary to reproduce the error. Thanks.
