### ISSUE TITLE
Standardize the default directories between Linux/MacOS and use a ".helm" ancestor folder

### ISSUE THREAD

**Issue by cmoulliard** [helm/helm#9608]
## Improvement

The convention followed to manage the default directories between the different OS is not consistent and should be improved

```
The defaults are listed below:

| Operating System | Cache Path                | Configuration Path             | Data Path               |
|------------------|---------------------------|--------------------------------|-------------------------|
| Linux            | $HOME/.cache/helm         | $HOME/.config/helm             | $HOME/.local/share/helm |
| macOS            | $HOME/Library/Caches/helm | $HOME/Library/Preferences/helm | $HOME/Library/helm      |
| Windows          | %TEMP%\helm               | %APPDATA%\helm                 | %APPDATA%\helm          |
```

Suggestions:
- I propose to use the same convention for Linux or MacOS users and not `$HOME/Library` for MacUsers
- I propose that we use `~/.helm` as common folder ancestor of the config/cache or data
```
$HOME/.helm/cache
$HOME/.helm/config
$HOME/.helm/data
```
in order to simplify the process to cleanup/delete helm locally, to look under the folders, ....

### Version
```
helm version
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.16"}
```

**Comment by marckhouzam** [comment]
Thanks @cmoulliard for the report.
Helm follows the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)
You can refer to #5443 as a starting point of when this was brought in.

**Comment by bacongobbler** [comment]
See also

https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPFileSystem/Articles/WhereToPutFiles.html

For information on Apple's documentation, which closely resembles the XDG Base Directory spec.

`%APPDATA%` and `%TEMP%` are the two that closely resemble the XDG base directory specification on Windows.

**Comment by bacongobbler** [comment]
Closing as a wontfix. As @marckhouzam pointed out, this was the old style convention we moved away from due to a number of issues with its design. We do not plan on moving back.

If you wish to inform Helm where to place its configuration, you may set the environment variables described in `helm env` to change these locations to suit your needs. You can also change your XDG_DATA_HOME, XDG_CONFIG_HOME, and XDG_CACHE_HOME environment variables to suit your needs.

Thank you for your question.

**Comment by mattfarina** [comment]
First, if you need to get a location for something on an operating system you can use `helm env` or `helm env [VAR]` to get it on a particular system. We made this a consistent point.

For a little background...

Helm used to be consistent across operating systems. But, there were some things that caused us to change.

- There were requests for XDG support on systems that support it
- Windows and Mac have specifically documented locations to put things. To be consistent on the platform the apps there should follow that... per the docs.

We end up with a question of... is helm consistent across platforms in its location while breaking from the OS handling or does Helm use the platform specific locations? We chose to follow the platform specific locations.

**Comment by cmoulliard** [comment]
> For information on Apple's documentation, which closely resembles the XDG Base Directory spec. It also describes where _not_ to put files... It describes that applications should not place files under `/Users`, which means conventions like `~/.helm` is generally discouraged in macOS.

All the Developers that I know use on Mac the `~/` folder and all the applications deployed adopt as convention to store the files here:
```
 ls -la ~/
total 2104
drwxr-xr-x+ 105 cmoullia  staff    3360 Apr 16 09:06 .
drwxr-xr-x    5 root      admin     160 Jan  1  2020 ..
-rw-r--r--@   1 cmoullia  staff   38916 Apr 16 08:00 .DS_Store
drwx------    2 cmoullia  staff      64 Apr 14 18:06 .Trash
drwxr-xr-x    4 cmoullia  staff     128 Apr  8 20:16 .android
drwxr-xr-x    7 cmoullia  staff     224 Feb  4 11:12 .ansible
-rw-r--r--    1 cmoullia  staff     109 Jun 25  2020 .ansible.cfg
-rw-r--r--    1 cmoullia  staff      23 Apr 16 08:42 .auth.txt
drwxr-xr-x    3 cmoullia  staff      96 Oct 13  2020 .aws
drwxr-xr-x    3 cmoullia  staff      96 Jun 30  2020 .bosh
drwxr-xr-x    3 cmoullia  staff      96 Oct  5  2020 .bundle
drwx------    3 cmoullia  staff      96 Jun 18  2020 .cache
drwx------    4 cmoullia  staff     128 Mar 18 19:19 .cf
drwx------   10 cmoullia  staff     320 Feb 18 17:58 .config
drwxr-x---    7 cmoullia  staff     224 Feb 18 09:19 .crc
drwxr-xr-x    3 cmoullia  staff      96 Nov  9 20:47 .credentials
drwxr-xr-x   11 cmoullia  staff     352 Apr  9 12:04 .docker
drwxr-xr-x   14 cmoullia  staff     448 Jun  9  2020 .dropbox
drwxr-xr-x    4 cmoullia  staff     128 Oct  5  2020 .gem
drwx------@  49 cmoullia  staff    1568 Apr 16 08:54 .gnupg
drwxr-xr-x    8 cmoullia  staff     256 Jan 20 10:09 .gradle
drwxr-xr-x    3 cmoullia  staff      96 Jan 14 11:44 .groovy
drwxr-xr-x   33 cmoullia  staff    1056 Apr  7 16:57 .jenkins
drwxr-xr-x    3 cmoullia  staff      96 Oct 21 09:36 .k3d
drwxr-xr-x    3 cmoullia  staff      96 Jun 12  2020 .k9s
drwxr-xr-x    6 cmoullia  staff     192 Mar  3 15:50 .krew
drwxr-xr-x   10 cmoullia  staff     320 Apr  8 17:50 .kube
drwxr-xr-x    4 cmoullia  staff     128 Sep 28  2020 .m2
drwxr-xr-x   17 cmoullia  staff     544 Oct 14  2020 .minikube
drwxr-xr-x    7 cmoullia  staff     224 Mar  5 12:22 .npm
drwxr-xr-x   27 cmoullia  staff     864 Jun 10  2020 .nvm
drwxr-xr-x   22 cmoullia  staff     704 Apr 13 08:53 .oh-my-zsh
drwxr-xr-x    4 cmoullia  staff     128 Mar 30 16:07 .pack
drwx------    3 cmoullia  staff      96 Apr 12 20:15 .password-store
-rw-r--r--    1 cmoullia  staff     236 Mar 18 11:21 .profile
drwxr-xr-x   30 cmoullia  staff     960 Mar 18 11:21 .rvm
drwxr-xr-x   11 cmoullia  staff     352 Mar 24 15:20 .sdkman
drwxr-xr-x   11 cmoullia  staff     352 Apr  9 16:56 .vagrant.d
drwxr-xr-x    3 cmoullia  staff      96 Jan 19 18:19 .vim
drwx------    5 cmoullia  staff     160 Jan 21 13:20 .vnc
drwxr-xr-x    5 cmoullia  staff     160 Jun 19  2020 .vscode
-rw-r--r--    1 cmoullia  staff    3902 Apr  6 18:57 .zshrc
```
**REMARK**: From this point of view, helm is more than an exception ;-)

**Comment by cmoulliard** [comment]
> Closing as a wontfix. As @marckhouzam pointed out, this was the old style convention we moved away from due to a number of issues with its design. We are not planning on moving back

To be fair, this a bas decision choice you made. Sorry to say that guys !!!
