### ISSUE TITLE
helm chart list could not show all messages

### ISSUE THREAD

**Issue by jingzhao-self** [helm/helm#9614]
Output of `helm version`:
helm version
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-eks-49a6c0", GitCommit:"49a6c0bf091506e7bafcdb1b142351b69363355a", GitTreeState:"clean", BuildDate:"2020-12-23T22:10:21Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
EKS

Because of [here](https://docs.aws.amazon.com/AmazonECR/latest/userguide/ECR_on_EKS.html#using-helm-charts-eks), i need to create a long name for a chart cache, but "helm chart list" couldn't show all names and i couldn't use "helm chart remove <cache-name>".
![image](https://user-images.githubusercontent.com/60691314/114993483-734fe700-9ece-11eb-8d7c-997201faf63d.png)

**Comment by jingzhao-self** [comment]
right now i can guess out the really name from NAME and VERSION messages, but if the name is long enough, it will fail out.

**Comment by bacongobbler** [comment]
Hi @jingzhao-self!

Looking internally at the implementation, you can see that the maximum column width of `helm chart list` is hard-coded to 60 characters.

https://github.com/helm/helm/blob/43853ea772e779b617b011a8d4e69205636fa4f9/internal/experimental/registry/client.go#L282

Unfortunately, there does not appear to be a way to work around this through using `helm chart list`.

However, you could try to determine the full name of the chart by looking under Helm's data directory and look under the OCI directory to determine the full name. You can look this up using `helm env`.

Looking longer term at this issue, [HIP 6](https://github.com/helm/community/blob/main/hips/hip-0006.md#6-helm-chart-is-removed-integrated-into-rest-of-cli) describes that at some point we will remove `helm chart list`. So at some point this command will be removed.

Hope this helps!

**Comment by jingzhao-self** [comment]
@bacongobbler thanks, it works.

helm env                                          #find HELM_CACHE_HOME value
cd path_to_cache  
cat registry/cache/index.json | jq  #could see the result
