### ISSUE TITLE
Latest tags are missing signatures

### ISSUE THREAD

**Issue by Foxboron** [helm/helm#9616]
The two last tags from helm has been missing signatures from @mattfarina. We use them for authenticating the releases in Arch Linux and this has kept back two minor updates in helm. 

It would be great to get signed tags again or signed tarballs among the release artifacts.

**Comment by bacongobbler** [comment]
Hi @Foxboron. Looking at the tags in git, it does appear that both have been PGP signed.

Here's v3.5.4:

```
><> git show v3.5.4
tag v3.5.4
Tagger: Matt Farina <matt@mattfarina.com>
Date:   Wed Apr 14 16:52:17 2021 -0400

Helm release v3.5.4
-----BEGIN PGP SIGNATURE-----

iQIzBAABCAAdFiEEyrqo1E36yhR5H76YksRKPUIf9/kFAmB3VgEACgkQksRKPUIf
9/kIWA/9HnJiS01xVISMQPo918ueGS+CTBL5jE6LQPF4CAuTfQvouK4ij0unbdCW
WCN6UpijEkvg5pYRxQAkmrP3xu9LdZFutaosbjf9fw7WUPD4y1fQP7iD6ZBgESGH
qgiD2tcV1RlUlvJlVZGtvk4n1T3Hoo2OMLjZjKu0h3bvBXAzpsrY7BSHLMrgpsXZ
3HxtApvyxMXMii7t/adJMcaU87JpfHh4M0pFn+tasRMsk2yHVUfSx41ANBWRpxnG
tHNP0LoPZRYWlW3dWVoo3ARaM/yvMhcEcXOL7d8J3Sho7fTK0JWUst0zRqPf6YQF
+W/hHmC4JCP6t5B5bY0RqQhr4QdV18LiqOQMGZiJUb5P8mgn0aSazJe24leWU3hu
VSApqLTL5BPhIERmWsAn8RfhoyMEDAsdrk657TmA6ibYX6r/Uv7D3LY2anLVm3Jt
AdDwOC3QufbenirqgcNDBYrVlMzdhmXOB4t2VOijAxqUPWIpzg232xCbM7N+n1n3
scXfbao9HJE8omEyRnPI4K4tuKzbilyU+XlKBX6C5ssq53urwG51uPwmnkHP1X8U
8E0thdv2i+09b3nkz7gg9o79/sbfFj8EPFtxhxGaZcq6FGXBCJvPyQsnE0Y2mS31
zs0CWJ/6Uc0aAeDu8MNTerMWHDE68zcoxCZl8n5BdubSbtWyEgI=
=mmgc
-----END PGP SIGNATURE-----
```

And v3.5.3:

```
><> git show v3.5.3
tag v3.5.3
Tagger: Matt Farina <matt@mattfarina.com>
Date:   Wed Mar 10 11:51:12 2021 -0500

Helm release v3.5.3
-----BEGIN PGP SIGNATURE-----

iQIzBAABCAAdFiEEyrqo1E36yhR5H76YksRKPUIf9/kFAmBI+QAACgkQksRKPUIf
9/m+hBAAgiRa3tn/rT4zJ9g6RJDYoP0sFXH33jHU5wb5NgiXHjY7BOx9bwPajCxb
srnOKkrslS3eJdNjuPY1H95tyCn7Xorztn9eYFIKR4+L/FO86toG+v7t8tlB6q+T
7F2FyodDjEOS8o0AnZst0QpOeO9Vsl/kWTl1OwAjqKXBsRStfuNuOyvbOysOo0+S
mv2uwa2m/PcFz5Atu+hJvq//skyNXma5habTl/aOFapxxxSGsYeaUpNsP7f5wwji
4MSIrDQS/MttmpDucLjyTRKZGBKlWrJyrYbd2cY349pbjnYu0k9m9MSgMOmCpm/j
+98o5OMWAe45GuldsIhFYdmG+8p7wo3qDyha5cTITE8pNWOXUobUYNhwEdLbl4i0
mjfLof0Nj5cyGAleqMsneNdWDqD4sFkt6Fb6cYHymcAqimOtL2JEaI/DEjo0G/8a
BAIrrDFkeewJCLyyaVW36vFMToV4wFzYH6KXOSzOUxqSfKURia7HuvUy/NntEm+w
AXByxsqP40Ebu7y2VlMPXkOhAp7do3l7YDf7VyHnAUzOE6uqdmhsg4HA17ZGdbvb
u+OjRrCKvga6P3K7raLJifoFi/M4pg2k4cEj//bfjlpdo9EuxqLfNzoqb0OvOXfm
n4WaYjHCK/HDJ2ureNQH4rHMDkrfQMePcoPhjMzHuD6fI1zpA8Q=
=HOYc
-----END PGP SIGNATURE-----
```

I signed v3.0.0 and it appears identical to mine, save for the change in signature.

```
><> git show v3.0.0
tag v3.0.0
Tagger: Matthew Fisher <matt.fisher@microsoft.com>
Date:   Wed Nov 13 05:35:15 2019 -0800

Helm release v3.0.0
-----BEGIN PGP SIGNATURE-----

iQIzBAABCgAdFiEEln+KxeIhb59P0nCtkqp4PLqujjsFAl3MBpMACgkQkqp4PLqu
jjuSLg/+NLjPCRL1wjfcgRUDcsH4zZGjaHMuIg3bXOJn1WcxfuebtkiqRMYafyT0
PQOSbJ7cLJObvMWSbzWkdu0ZJyYmma2KnoddGUqd7RURelKwKa6XyrSdxt2FRvD8
ohguynx0DTK8nj1tUzbpGaFJ1MU9KnYeI6OUFOAGXVpX0G+vE0QTbLihImwhgQxL
tIvcedsi3u9f2nDuGYVAApeJ3LfE2h6hAgl2B0MO/lnZrwA7BVGseoPnit75L4JE
mGoRJY891RjOAmGEPRNrD0vYOovfpOkgn1mtuUGtpOYVPoaW77xY7fAitLP7pgVP
H4haf0/SEMyXtDsuud/Y1aDYHW1qZizfhxVKIb85f2yEMoeUQZIvrsgZcUiLoC2u
zKTQQJVBn+PBfeluZk6s+EKJsPBpNaNyDz2ehcg5AviBs6RE5sOE7HZNwl4ccue2
5pNlmCs+WKi9rlE5pM3dEZacwVFT4eC+ku2sMBq5r2ggy1cV/7boxBA3qe6RtEP8
yJW7KYXUT2wWQ6ekB4NDctOOTEaOLzZPkE7Gp3uj2/mhvpYOaLefBZhjW11kfrcV
pozIDkiJBQKUURglpj06ekgm99GyOsCcAH3G4yliGzbLjcbb2+4SQyQf2eWLy1Ii
mMVgylMtFIjG36xHfODdHxTR1BwVS2GutuBOpGxgFlx8pb8igZ0=
=9XQw
-----END PGP SIGNATURE-----
```

Can you determine what method you are using to determine why the signatures appear to be missing?

**Comment by bacongobbler** [comment]
> or signed tarballs among the release artifacts.

FYI, we release a signature for every released artifact. You can verify each release tarball yourself using the signatures found on the release page.

https://github.com/helm/helm/releases/tag/v3.5.4

This can also be replicated if you're using the `get-helm-3` flag with `VERIFY_SIGNATURES=true`.

https://github.com/helm/helm/blob/a499b4b179307c267bdf3ec49b880e3dbd2a5591/scripts/get-helm-3#L24

Hope this helps.

**Comment by Foxboron** [comment]
Argh. The signature verification failure was from the packaging tooling. I also assumed it was correct because the tags on the release page is missing the `Verified` tag on the two latest releases. 

>FYI, we release a signature for every released artifact, and there are signatures for both v3.5.3 and v3.5.4. You can verify each release tarball yourself using the ascii-armored signatures found on the release page.

The release artifacts are all pre-built binaries which (probably) can't be reproduced properly to the point where the signature would apply when building from source. This is not something you can work with as a downstream distribution packagers. 

In practice the tarballs would be great to have since currently the only way to get authenticated source is through git. But I don't think this is an actual issue :)

**Comment by bacongobbler** [comment]
Fair enough.

> I also assumed it was correct because the tags on the release page is missing the Verified tag on the two latest releases.

@mattfarina is it possible that the pgp public key used for singing off on your commits have not been added to your GitHub profile page? That's the only reaon I can think of where a pgp key may not show up as verified.

**Comment by Foxboron** [comment]
I suspect Matt has changed his email in github and/or the gnupg which makes the signatures `Unverified`.

**Comment by Foxboron** [comment]
Signed tags are back, closing the issue.
