### ISSUE TITLE
Data races in the chartutil package

### ISSUE THREAD

**Issue by devzx** [helm/helm#9618]
Hello there!

Firstly let me preface this by saying a massive thank you to everyone who works on this fantastic project.

To add a bit of background context on this particular issue:
At work we utilize `helm` for all our kubernetes deployments, as such we have bit a fair amount of tooling around analyzing our releases before carrying out the actual deployment. One of those tools makes use of various helm packages to essentially run a `helm template` to generate the would be release manifest we use that data to parse out various bits we are interested in such as the image to perform further checks e.g the image passes vulnerability scans etc. This tool runs on every PR raised to our deployment repository as such its very likely that the code is executed concurrently.

I've created a repository https://github.com/devzx/helm-data-race which provides code to recreate the data race as well as the code I have written in an accompanying PR (modified in the fix/vendor folder for convenience) that aims to resolve the issue.

The actual issue seems to occur when https://github.com/helm/helm/blob/main/pkg/chartutil/capabilities.go#L37-L40 these two defaults are called the same time (my assumption on why this hasn't been flagged before is because helm is usually used to execute a single command and then exits). Because they are package level variables that are pointers subsequent calls either retain data from the previous call (I noticed this in the tests, api version data from a previous test was persisted for the following tests leading to incorrect golden files) or data races occur when `APIVersions` are modified concurrently here https://github.com/helm/helm/blob/a499b4b179307c267bdf3ec49b880e3dbd2a5591/pkg/action/install.go#L200

```==================
WARNING: DATA RACE
Read at 0x000004123f90 by goroutine 20:
  helm.sh/helm/v3/pkg/action.(*Install).Run()
      /Users/eli/go/pkg/mod/helm.sh/helm/v3@v3.5.3/pkg/action/install.go:200 +0x249
  main.template()
      /Users/eli/git/helm-data-race/main.go:84 +0x67b

Previous write at 0x000004123f90 by goroutine 22:
  helm.sh/helm/v3/pkg/action.(*Install).Run()
      /Users/eli/go/pkg/mod/helm.sh/helm/v3@v3.5.3/pkg/action/install.go:200 +0x337
  main.template()
      /Users/eli/git/helm-data-race/main.go:84 +0x67b

Goroutine 20 (running) created at:
  main.main()
      /Users/eli/git/helm-data-race/main.go:25 +0xed

Goroutine 22 (running) created at:
  main.main()
      /Users/eli/git/helm-data-race/main.go:25 +0xed
==================
```

Thank you for taking the time to look at this and please let me know if you need any more information.
Accompanying PR https://github.com/helm/helm/pull/9619

Many thanks
Eli

**Comment by bacongobbler** [comment]
Hi @devzx! Thank you for taking the time to write up an issue and an accompanying PR. I will take a closer look later this week when I find some free time.
