### ISSUE TITLE
Templating and upgrade support for CRDs in Helm3

### ISSUE THREAD

**Issue by SrishT** [helm/helm#9620]
I have a use-case wherein my CRDs needs certain templating and I wish to install them with proper rendering along with the `helm install`  command. Is there any way to achieve this with helm3, wherein CRDs are required to be placed within the `crds` folder? Also is there any plan to add upgrade support for CRDs along with helm upgrades? This seems to be an essential requirement since the new version of the resource might include some fields which might not be part of the older CRD.

**Comment by bacongobbler** [comment]
Hi @SrishT!

I believe another issue discusses the same idea: https://github.com/helm/helm/issues/6581. Have you had a chance to read through that one yet?

As far as templating CRDs go, we've discussed this at length and haven't found a good solution to resolve this problem. We laid out some design issues in [HIP 11](https://github.com/helm/community/blob/main/hips/hip-0011.md). If you have a chance to read through that document and discover a solution to this problem, we are open to ideas and suggestions.

Thanks!
