### ISSUE TITLE
Helm 2 scripts/get no longer works

### ISSUE THREAD

**Issue by msg555** [helm/helm#9622]
Minor issue but the scripts/get script for Helm 2.x no longer works do to there being no 2.x releases on the first page of releases on github. See https://github.com/helm/helm/blob/43853ea772e779b617b011a8d4e69205636fa4f9/scripts/get#L83

It just fails to find an approriate TAG and proceeds with it unset resulting in failures later on in the script.

**Comment by bacongobbler** [comment]
#9607.
