### ISSUE TITLE
dependency list should show aliases

### ISSUE THREAD

**Issue by lorenzleutgeb** [helm/helm#9624]
### Preconditions

My `Chart.yaml` lists multiple dependencies. Some are aliased:

```console
$ yq -y '.dependencies' < Chart.yaml
- name: ingress-nginx
  version: 3.25.0
  repository: https://kubernetes.github.io/ingress-nginx
- name: cp-helm-charts
  version: 0.5.0
  repository: https://confluentinc.github.io/cp-helm-charts
  alias: cp
- name: postgresql
  version: 10.3.17
  repository: https://charts.bitnami.com/bitnami
  alias: a-postgresql
- name: postgresql
  version: 10.3.17
  repository: https://charts.bitnami.com/bitnami
  alias: b-postgresql
```

### Actual

When I run `helm dependency list`, I cannot identify aliased dependencies easily:

```console
$ helm dependency list
NAME            VERSION REPOSITORY                                     STATUS
ingress-nginx   3.25.0  https://kubernetes.github.io/ingress-nginx     ok
cp-helm-charts  0.5.0   https://confluentinc.github.io/cp-helm-charts  ok
postgresql      10.3.17 https://charts.bitnami.com/bitnami             ok
postgresql      10.3.17 https://charts.bitnami.com/bitnami             ok
```

### Expected

IMO, if there is at least one dependency with a defined alias, there should be an "ALIAS" column in the output.

```console
$ helm dependency list
NAME            VERSION  REPOSITORY                                     ALIAS       STATUS 
ingress-nginx   3.25.0   https://kubernetes.github.io/ingress-nginx     n/a         ok
cp-helm-charts  0.5.0    https://confluentinc.github.io/cp-helm-charts  cp          ok
postgresql      10.3.17  https://charts.bitnami.com/bitnami             a-postgres  ok     
postgresql      10.3.17  https://charts.bitnami.com/bitnami             b-postgres  ok     
```

### Implementation

Should probably be around

https://github.com/helm/helm/blob/43853ea772e779b617b011a8d4e69205636fa4f9/pkg/action/dependency.go#L181-L190

I can PR, but first need to know how you want to handle dependencies that have no alias. I used "n/a" above, but we all know that representing absence/emptiness is always tricky. What's the convention in helm here?

---

Output of `helm version`:
```
version.BuildInfo{Version:"v3.2.1", GitCommit:"", GitTreeState:"", GoVersion:"go1.14.4"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"archive", BuildDate:"1980-01-01T00:00:00Z", GoVersion:"go1.16.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:23:04Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Irrelevant.

**Comment by bacongobbler** [comment]
Thanks for the suggestion. I do agree that providing more visibility as to why a chart would be listed twice under `helm dependency list` (as an alias) would be beneficial to the end user.

> but first need to know how you want to handle dependencies that have no alias. I used "n/a" above, but we all know that representing absence/emptiness is always tricky. What's the convention in helm here?

Good question. I know that dependencies can come from local files and not from a remote repository. Can you look at that use case and see what's the output there? I believe it should be an empty string.

I would also look at [EncodeTable](https://github.com/helm/helm/blob/43853ea772e779b617b011a8d4e69205636fa4f9/pkg/cli/output/output.go#L130-L140) and check its output when provided an empty string as input for a table column.

Hope this helps!

**Comment by lorenzleutgeb** [comment]
Please reopen.
