### ISSUE TITLE
helm--linux-amd64.tar.gz SHA sum does not match

### ISSUE THREAD

**Issue by karancode** [helm/helm#9625]
Output of `helm version --client`: cannot install (previously installed : 
```
Client: &version.Version{SemVer:"v2.17.0", GitCommit:"a690bad98af45b015bd3da1a41f6218b1a451dbe", GitTreeState:"clean"}
```

Output of `kubectl version --client`: 
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS Ec2

I am installing helm on my aws ec2 instances (ubuntu 18.04) as part of my instance user-data. Installation script: 

```sh
#!/bin/bash
# Install Helm
curl -L https://raw.githubusercontent.com/helm/helm/master/scripts/get | bash
```
It was working fine until couple of days ago but today it is failing with following error 
```
   Downloading https://get.helm.sh/helm--linux-amd64.tar.gz
   SHA sum of /tmp/helm-installer-9c27ke/helm--linux-amd64.tar.gz does not match. Aborting.
   Failed to install helm
   For support, go to https://github.com/helm/helm.
```

I searched couple of issues which said using install script from master should fix the issue. But I think it isn't in this case.
I am now going to try with setting `DESIRED_VERSION` as `2.17.0`. (This is the one which was installed previously when this script was working).

Could you please help here? Thanks!

**Comment by bacongobbler** [comment]
#9607
