### ISSUE TITLE
helm v3-confused with default storage

### ISSUE THREAD

**Issue by ArenaSu** [helm/helm#9629]
Output of `helm version`: version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): openstack vm

`# helm env
HELM_BIN="helm"
HELM_CACHE_HOME="/root/.cache/helm"
HELM_CONFIG_HOME="/root/.config/helm"
HELM_DATA_HOME="/root/.local/share/helm"
HELM_DEBUG="false"
HELM_KUBEAPISERVER=""
HELM_KUBEASGROUPS=""
HELM_KUBEASUSER=""
HELM_KUBECAFILE=""
HELM_KUBECONTEXT=""
HELM_KUBETOKEN=""
HELM_MAX_HISTORY="10"
HELM_NAMESPACE="default"
HELM_PLUGINS="/root/.local/share/helm/plugins"
HELM_REGISTRY_CONFIG="/root/.config/helm/registry.json"
HELM_REPOSITORY_CACHE="/root/.cache/helm/repository"
HELM_REPOSITORY_CONFIG="/root/.config/helm/repositories.yaml"`

`# helm list --all-namespaces
NAME      	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART       	APP VERSION

redis-test	default  	1       	2021-04-20 12:31:49.221386998 +0000 UTC	deployed	redis-10.5.7	5.0.7 `

HELM_DATA_HOME dir is not exist.
`# ls /root/.local/share/helm

ls: 无法访问/root/.local/share/helm: 没有那个文件或目录`

Qestion 1： What's the problem？

Question 2： So what storage driver does helm select by default？

Question 3：If storage driver is configmap，i see LabelSelector setting  "owner"="helm" in source code below，but  i can not find the label by kubectl get confimap?
`helm.sh/helm/v3/pkg/storage/driver
func (cfgmaps *ConfigMaps) List(filter func(*rspb.Release) bool) ([]*rspb.Release, error) {
	lsel := kblabels.Set{"owner": "helm"}.AsSelector()
	opts := metav1.ListOptions{LabelSelector: lsel.String()}
        ...
`

`# kubectl get cm redis-test -o yaml
apiVersion: v1
data:
...
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: redis-test
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-04-20T12:31:49Z"
  labels:
    app: redis
    app.kubernetes.io/managed-by: Helm
    chart: redis-10.5.7
    heritage: Helm
    release: redis-test
  name: redis-test
  namespace: default
  resourceVersion: "591669"
  uid: 4ad3b7e1-42d6-4581-a186-4972d58091e8`

**Comment by bacongobbler** [comment]
https://helm.sh/docs/topics/advanced/#storage-backends

**Comment by ArenaSu** [comment]
> https://helm.sh/docs/topics/advanced/#storage-backends

`
#  kubectl get secrets redis-test -o yaml
apiVersion: v1
data:
  redis-password: amtic0w5R0ZZTg==
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: redis-test
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-04-20T12:31:49Z"
  labels:
    app: redis
    app.kubernetes.io/managed-by: Helm
    chart: redis-10.5.7
    heritage: Helm
    release: redis-test
  name: redis-test
  namespace: default
  resourceVersion: "591667"
  uid: 09b6d7c4-f5af-4187-a53f-4da61ee26f98
type: Opaque
`
I can not find label with key = "owner", it's ok ？
`// List fetches all releases and returns the list releases such
// that filter(release) == true. An error is returned if the
// secret fails to retrieve the releases.
func (secrets *Secrets) List(filter func(*rspb.Release) bool) ([]*rspb.Release, error) {
	lsel := kblabels.Set{"owner": "helm"}.AsSelector()
	opts := metav1.ListOptions{LabelSelector: lsel.String()}
...
`

**Comment by ArenaSu** [comment]
@bacongobbler
