### ISSUE TITLE
helm search hub wordpress behind proxy TLS : handshake timeout

### ISSUE THREAD

**Issue by karamba-brgs** [helm/helm#9631]
Hi,
When we launch this command behind a proxy (behind cntlm service) :
helm search --debug hub wordpress

We have this message :

helm search --debug hub wordpress

search_hub.go:87: [debug] Get "https://hub.helm.sh/api/chartsvc/v1/charts/search?q=wordpress": net/http: TLS handshake timeout
Error: unable to perform search against "https://hub.helm.sh"
helm.go:81: [debug] unable to perform search against "https://hub.helm.sh"

curl https://hub.helm.sh command works fine 

a tcpdump show that helm send "hello" in tls 1.0 version and this version is not permitted

how can we force the use of a less permissive tls version ?
Thank you for your help

Serveur centos 7.7
uname -a
Linux xc001xlx 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Output of `helm version`:
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}

**Comment by bacongobbler** [comment]
TLS protocols are hardcoded in Go's crypto/tls package. I am fairly certain that TLS 1.0 support was dropped long ago and is recognized by the industry as deprecated/unsupported due to the number of issues involved with the protocol. Please upgrade to a more recent version of the TLS protocol like 1.3.

From https://golang.org/pkg/crypto/tls/:

> Package tls partially implements TLS 1.2, as specified in RFC 5246, and TLS 1.3, as specified in RFC 8446.

**Comment by bacongobbler** [comment]
And for what it's worth, I cannot reproduce the issue locally.

```
><> helm search hub wordpress
URL                                                     CHART VERSION   APP VERSION     DESCRIPTION

https://artifacthub.io/packages/helm/groundhog2...      0.3.1           5.7.0-apache    A Helm chart for Wordpress on Kubernetes
https://artifacthub.io/packages/helm/bitnami/wo...      10.10.8         5.7.1           Web publishing platform for building blogs and ...
https://artifacthub.io/packages/helm/seccurecod...      2.6.1           4.0             Insecure & Outdated Wordpress Instance: Never e...
https://artifacthub.io/packages/helm/presslabs/...      0.11.0-alpha.1  0.11.0-alpha.1  Presslabs WordPress Operator Helm Chart
https://artifacthub.io/packages/helm/presslabs/...      0.11.0-rc.1     v0.11.0-rc.1    A Helm chart for deploying a WordPress site on ...
https://artifacthub.io/packages/helm/phntom/bin...      0.0.3           0.0.3           www.binaryvision.co.il static wordpress
https://artifacthub.io/packages/helm/gh-shessel...      1.0.15          5.7.0           Web publishing platform for building blogs and ...
https://artifacthub.io/packages/helm/wordpress/...      0.2.0           1.1.0           Wordpress for Kubernetes

https://artifacthub.io/packages/helm/seccurecod...      2.6.0           latest          A Helm chart for the WordPress security scanner...
https://artifacthub.io/packages/helm/presslabs/...      0.11.0-rc.1     v0.11.0-rc.1    Open-Source WordPress Infrastructure on Kubernetes
https://artifacthub.io/packages/helm/wordpressm...      0.1.0           1.1
```

**Comment by bacongobbler** [comment]
ArtifactHub does appear to be using TLS 1.3. Not sure what would cause it to use TLS 1.0 on your end. I took a screenshot confirming this.

![image](https://user-images.githubusercontent.com/1360539/115580840-51fb4c00-a27c-11eb-818a-a87207202815.png)

**Comment by karamba-brgs** [comment]
Hi Matthew,
Thanks for the time spent for my issue.

Actually, I don't understand this issue because I used the standard helm install describe on the helm site :

$ curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
$ chmod 700 get_helm.sh
$ ./get_helm.sh

1 year ago I had already used the same setup to install rancher and it was working fine.
helm repo list
NAME            URL
rancher-stable  https://releases.rancher.com/server-charts/stable

I recently tried to update my rancher charts and  it failed

tcpdump capture show a TLSv1 negociation

do you propose to compile the helm binary?

**Comment by bacongobbler** [comment]
Here's the code where Helm invokes the request for `helm search hub`: https://github.com/helm/helm/blob/43853ea772e779b617b011a8d4e69205636fa4f9/internal/monocular/search.go#L117-L129
