### ISSUE TITLE
helm3 uninstall

### ISSUE THREAD

**Issue by forestuser** [helm/helm#9632]
Output of `helm version`:
Version:"v3.5.3"
Output of `kubectl version`:
version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0"16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Cloud Provider/Platform (AKS, GKE, Minikube etc.): none

Good afternoon! I run a cluster on kubernetes, install my template, everything works. But when I perform an uninstall, Helm removes only the services, not all the deployments that I installed. Tell me, is this normal or am I missing something?

**Comment by bacongobbler** [comment]
Hi @forestuser. Sorry to hear you're running into issues. No, it is not normal for deployments to not be removed after a `helm uninstall` if it was installed via `helm install`. However we're going to need more information before we can help determine the root cause of the issue.

Can you provide a sample chart that reproduces the same issue? That way we can help determine a root cause for the issue and determine next steps.

**Comment by forestuser** [comment]
helm un battler -n battler --debug
uninstall.go:93: [debug] uninstall: Deleting battler
client.go:282: [debug] Starting delete for "worker" Service
client.go:282: [debug] Starting delete for "gateway" Service
client.go:282: [debug] Starting delete for "channelserver" Service
client.go:282: [debug] Starting delete for "app" Service
client.go:282: [debug] Starting delete for "register" Service
client.go:282: [debug] Starting delete for "mysql" Service
client.go:282: [debug] Starting delete for "arena" Service
client.go:282: [debug] Starting delete for "rabbitmq" Service
uninstall.go:134: [debug] purge requested for battler
release "battler" uninstalled


helm install battler battler_helm -n battler --debug
install.go:173: [debug] Original chart version: ""
install.go:190: [debug] CHART PATH: /home/data/battler_helm

client.go:282: [debug] Starting delete for "configmap-mysql" ConfigMap
client.go:122: [debug] creating 1 resource(s)
client.go:282: [debug] Starting delete for "secretuser" Secret
client.go:122: [debug] creating 1 resource(s)
client.go:282: [debug] Starting delete for "pv" PersistentVolume
client.go:311: [debug] persistentvolumes "pv" not found
client.go:122: [debug] creating 1 resource(s)
client.go:282: [debug] Starting delete for "pvc" PersistentVolumeClaim
client.go:311: [debug] persistentvolumeclaims "pvc" not found
client.go:122: [debug] creating 1 resource(s)
client.go:282: [debug] Starting delete for "geoipupdate" Deployment
client.go:311: [debug] deployments.apps "geoipupdate" not found
client.go:122: [debug] creating 1 resource(s)
client.go:282: [debug] Starting delete for "mysql" Deployment
client.go:311: [debug] deployments.apps "mysql" not found
client.go:122: [debug] creating 1 resource(s)
client.go:282: [debug] Starting delete for "app" Deployment
client.go:311: [debug] deployments.apps "app" not found
client.go:122: [debug] creating 1 resource(s)
client.go:282: [debug] Starting delete for "register" Deployment
client.go:311: [debug] deployments.apps "register" not found
client.go:122: [debug] creating 1 resource(s)
client.go:282: [debug] Starting delete for "channelserver" Deployment
client.go:311: [debug] deployments.apps "channelserver" not found
client.go:122: [debug] creating 1 resource(s)
client.go:282: [debug] Starting delete for "rabbitmq" Deployment
client.go:311: [debug] deployments.apps "rabbitmq" not found
client.go:122: [debug] creating 1 resource(s)
client.go:282: [debug] Starting delete for "gateway" Deployment
client.go:311: [debug] deployments.apps "gateway" not found
client.go:122: [debug] creating 1 resource(s)
client.go:282: [debug] Starting delete for "worker" Deployment
client.go:311: [debug] deployments.apps "worker" not found
client.go:122: [debug] creating 1 resource(s)
client.go:282: [debug] Starting delete for "arena" Deployment
client.go:311: [debug] deployments.apps "arena" not found
client.go:122: [debug] creating 1 resource(s)
client.go:122: [debug] creating 8 resource(s)
NAME: battler
LAST DEPLOYED: Wed Apr 21 22:43:59 2021
NAMESPACE: battler
STATUS: deployed
REVISION: 1
TEST SUITE: None
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:

**Comment by forestuser** [comment]
tree battler_helm/
battler_helm/
├── charts
├── Chart.yaml
├── templates
│   ├── app
│   │   ├── configmap-mysql.yml
│   │   ├── deploy-app.yml
│   │   ├── deploy-arena.yml
│   │   ├── deploy-channelserver.yml
│   │   ├── deploy-gateway.yml
│   │   ├── deploy-geoipupdate.yml
│   │   ├── deploy-mysql.yml
│   │   ├── deploy-rabbitmq.yml
│   │   ├── deploy-register.yml
│   │   ├── deploy-worker.yml
│   │   ├── name-battler.yml
│   │   ├── pvc.yml
│   │   ├── pv.yml
│   │   ├── secretuser.yml
│   │   ├── service-app.yml
│   │   ├── service-arena.yml
│   │   ├── service-channelserver.yml
│   │   ├── service-gateway.yml
│   │   ├── service-mysql.yml
│   │   ├── service-rabbitmq.yml
│   │   ├── service-register.yml
│   │   └── service-worker.yml
│   ├── network
│   │   └── kube-flannel.yml
│   ├── nginx
│   ├── quota
│   └── traefik
└── values.yaml

**Comment by forestuser** [comment]
I'm sorry, but I can't give you more information

**Comment by bacongobbler** [comment]
From the logs it appears that the deployments cannot be found in the cluster:

> deployments.apps "geoipupdate" not found

Can you share those templates? Can you also share where those deployments are deployed.

**Comment by forestuser** [comment]
for example

cat deploy-mysql.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: battler
  labels:
    tier: backend
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: backend
  template:
    metadata:
      labels:
        app: mysql
        tier: backend
    spec:
      securityContext: {}
      volumes:
      - name: volumes-database
        persistentVolumeClaim:
          claimName: pvc
      - name: config
        configMap:
          name: configmap-mysql
          items:
          - key: config
            path: tf8mb4.cnf
      containers:
      - name: mysql
        image: mysql:5.7
#        ports:
#        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.mysqlRootPassword | quote }}
        - name: MYSQL_DATABASE
          value: {{ .Values.mysqlDatabase | quote }}
        - name: MYSQL_USER
          value: {{ .Values.mysqlUser | quote }}
        - name: MYSQL_PASSWORD
          value: {{ .Values.mysqlPassword | quote }}
        securityContext:
          privileged: true
        volumeMounts:
        - name: config
          mountPath: /etc/mysql/conf.d/
        - name: volumes-database
          mountPath: /var/lib/mysql
          subPath: battler_mysql_data/_data

**Comment by forestuser** [comment]
cat deploy-mysql.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: battler
  labels:
    tier: backend
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: backend
  template:
    metadata:
      labels:
        app: mysql
        tier: backend
    spec:
      securityContext: {}
      volumes:
      - name: volumes-database
        persistentVolumeClaim:
          claimName: pvc
      - name: config
        configMap:
          name: configmap-mysql
          items:
          - key: config
            path: tf8mb4.cnf
      containers:
      - name: mysql
        image: mysql:5.7
#        ports:
#        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.mysqlRootPassword | quote }}
        - name: MYSQL_DATABASE
          value: {{ .Values.mysqlDatabase | quote }}
        - name: MYSQL_USER
          value: {{ .Values.mysqlUser | quote }}
        - name: MYSQL_PASSWORD
          value: {{ .Values.mysqlPassword | quote }}
        securityContext:
          privileged: true
        volumeMounts:
        - name: config
          mountPath: /etc/mysql/conf.d/
        - name: volumes-database
          mountPath: /var/lib/mysql
          subPath: battler_mysql_data/_data

**Comment by forestuser** [comment]
I use annotation, but it shouldn't affect it...
annotations:
helm.sh/hook: pre-install
helm.sh/hook-weight: "1"

**Comment by forestuser** [comment]
> From the logs it appears that the deployments cannot be found in the cluster:
> 
> > deployments.apps "geoipupdate" not found
> 
> Can you share those templates? Can you also share where those deployments are deployed? Which namespace were they deployed to?

Matthew, why does he ask? This is an installation, not an update

**Comment by bacongobbler** [comment]
> Matthew, why does he ask? This is an installation, not an update

I am asking because you asked why the deployments were not being deleted during a `helm uninstall`. The root cause may be that the `helm install` is attempting to uninstall existing deployments instead of installing them. As a result, the release is not managing any deployments within the cluster, which would explain the situation.

Unfortunately, based on the information provided here I cannot help you. There is not enough information provided to reproduce a similar scenario, so all I can do here is help interpret the logs and hopefully provide you with the tools to debug this issue on your own.

Please report back to us when you determine the issue. Thanks.

**Comment by bacongobbler** [comment]
> I use annotation, but it shouldn't affect it...
> annotations:
> helm.sh/hook: pre-install
> helm.sh/hook-weight: "1"

Another thing to keep in mind is that chart hooks are no longer managed by Helm after they have been invoked. So they cannot be uninstalled by `helm uninstall`. The documentation has more information on this subject.

**Comment by forestuser** [comment]
> > I use annotation, but it shouldn't affect it...
> > annotations:
> > helm.sh/hook: pre-install
> > helm.sh/hook-weight: "1"
> 
> Another thing to keep in mind is that chart hooks are no longer managed by Helm after they have been invoked. So they cannot be uninstalled by `helm uninstall`. That could be another reason why your deployments are not being uninstalled. The documentation has more information on this subject.

Thank you for your help. I reread the helm documentation on hooks and have disabled them so far, now the install and uninstall work as needed.
