### ISSUE TITLE
helm rollback fails to identify the failed deployments when re-triggered

### ISSUE THREAD

**Issue by srinivasev** [helm/helm#9633]
My scenario is like below.

I have two releases - Release-A and Release-B.

Currently, I am on Release-A and need an upgrade of all the microservices to Release-B.
I tried performing the helm upgrade of microservice - "mymicroservice" with the below command to deliver Release-B.

`helm --kubeconfig /home/config upgrade --namespace testing --install --wait mymicroservice mymicroservice-release-b.tgz`

Because of some issue, the deployment object got failed to install and went into an error state.

Observing this, I perform the below rollback command.
`helm --kubeconfig /home/config --namespace testing rollback mymicroservice`

Due to bad luck, the Release-A's deployment object also went into failed/Crashloopbackoff state because of some reason.(may be an intermittent system failure or user behavior). Although this will result in helm rollback success, the deployment object is still not entered the running state.

Once I made the necessary corrections,  I will retry the rollback. As the deployment spec is already updated with helm, it never attempts to re-install the deployment objects even if it is in the failed state.

Is there any option with Helm to handle the above scenarios ?.

Tried with --force flag, but there are other errors related to Service object replace in the microservice when used the --force flag approach.
Rollback "mymicroservice -monitoring" failed: failed to replace object: Service "mymicroservice-monitoring" is invalid: spec.clusterIP: Invalid value: "": field is immutable

Output of `helm version`: `version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"}`

Output of `kubectl version`: `Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by bacongobbler** [comment]
Hi @srinivasev. I notice you’re using an older version of Helm 3. Can you try again using a recent version of Helm and report back your findings? Helm v3.5.4 is the latest.

**Comment by srinivasev** [comment]
Hi @bacongobbler,

I will attempt the above error using the latest helm chart v3.5.4 once, but is using the `--force` flag the only option/solution for the above scenario ?. Because I see the` --force` flag always consider delete and recreate all the Kubernetes objects of that release without respecting the corresponding resource in success/Running state.

This will bring in unnecessary overhead with deletions and re-creation of the Kubernetes objects during each helm rollback of the release.

**Comment by bacongobbler** [comment]
The `--force` flag does not delete and re-create resources. It changes the request from an HTTP PATCH to an HTTP PUT. It's similar to `kubectl apply --overwrite`.

**Comment by srinivasev** [comment]
Hi @bacongobbler ,
If it only performs the `kubectl apply --overwrite`, why it is trying to alter the service object in my case ?. Is it trying to re-create the chart's service object ?.

**Comment by bacongobbler** [comment]
Perhaps https://helm.sh/docs/faq/#improved-upgrade-strategy-3-way-strategic-merge-patches may help you better understand how `helm rollback` works.

Let me know if you have further questions.

**Comment by srinivasev** [comment]
HI @bacongobbler, I agree helm will work with a 3-way merge, but it only checks the deployment manifest and not the state of the current deployment as below.

Suppose my deployment is in the below state - 

`kubectl get pods`
`mymicroservice-9dc77ff6d-n6j4c        0/1     Init:0/1   0          83m` 

So, I made the necessary corrective actions and re-try the rollback. helm won't destroy this pod and re-create freshly. It only updates the release details as deployed.

And for the earlier problem using --force flag, I tried with the latest helm version. But still observing the same issue.

`helm.go:81: [debug] failed to replace object: Service "mymicroservice-monitoring" is invalid: spec.clusterIP: Invalid value: "": field is immutable
helm.sh/helm/v3/pkg/kube.(*Client).Update
        /home/circleci/helm.sh/helm/pkg/kube/client.go:246
helm.sh/helm/v3/pkg/action.(*Rollback).performRollback
        /home/circleci/helm.sh/helm/pkg/action/rollback.go:167
helm.sh/helm/v3/pkg/action.(*Rollback).Run
        /home/circleci/helm.sh/helm/pkg/action/rollback.go:79
main.newRollbackCmd.func2
        /home/circleci/helm.sh/helm/cmd/helm/rollback.go:69
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:80
runtime.main
        /usr/local/go/src/runtime/proc.go:204
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1374
`

Helm version 
`[package]$ helm version
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/cbnd/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/cbnd/.kube/config
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
`

**Comment by srinivasev** [comment]
Hi @bacongobbler ,
can you please check my comments? and update me.

**Comment by srinivasev** [comment]
Hi, Can anyone give me suggestions on the problem I faced when there is a failed deployment during rollback?

**Comment by srinivasev** [comment]
Hi, Is there any update on this thread? Please let me know,
