### ISSUE TITLE
naming convention for charts and variables

### ISSUE THREAD

**Issue by azamin** [helm/helm#9636]
Hello, the naming convention says that helm chart name can contain dashes, but variable name not:

`Chart names must be lower case letters and numbers. Words may be separated with dashes (-):`
  https://helm.sh/docs/chart_best_practices/conventions/

`Variable names should begin with a lowercase letter, and words should be separated with camelcase:`
  https://helm.sh/docs/chart_best_practices/values/

If i have a subchart named `subchart-name`, will I violate the naming convention with these values.yaml in my umbrella chart:
```
subchart-name:
  name: nginx
```

Here is an example: [confluentinc/cp-helm-charts](https://github.com/confluentinc/cp-helm-charts/blob/master/values.yaml#L43)

Thanks

**Comment by bacongobbler** [comment]
That is correct. In those cases https://github.com/helm/helm/issues/2192 may help provide workarounds. It is still okay to use dashes in chart names, but as you point out there it is a little more difficult to work with inside a template.

**Comment by azamin** [comment]
thank you @bacongobbler for the super quick response.
I have no suggestions ... it was just a question.

**Comment by jackson-chris** [comment]
This is a design flaw that seems like we're stuck with but all users using sub charts will face this problem if they use the conventions you've laid out. The closing statement in https://github.com/helm/helm/issues/2192 says that documentation was updated, but I see nothing that warns users of this problem and users are forced to do an internet search on how to work around this problem. I think you should update the documentation correctly. Either by stating that all sub charts should be aliased to a name without hyphens or that if you don't use alias than the workaround using `index` is required. And that workaround should be clearly documented.

**Comment by joejulian** [comment]
@jackson-chris documentation issues should be filed in https://github.com/helm/helm-www/issues
