### ISSUE TITLE
Helm erroneously thinks jobs have failed if `BackoffLimit=0`

### ISSUE THREAD

**Issue by dpp23** [helm/helm#9637]
If you have a job with `BackoffLimit=0` and run `helm install ... --wait-for-jobs` helm things the job has failed even if it has completed successfully.

**Comment by bacongobbler** [comment]
Hi @dpp23. Have you had a chance to look at the wait logic in Helm to confirm that behaviour? There may also be patches in the PR queue fixing or have fixed this issue in more recent releases.

https://github.com/helm/helm/blob/main/pkg/kube/wait.go

Which version of Helm are you testing with? Can you please provide more information?

**Comment by dpp23** [comment]
@bacongobbler the version is `version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}`

I did look at the logic, but couldn't figure out why it would behave the way it does (assuming so go gotcha). Let me see if I can repro and debug a bit

**Comment by dpp23** [comment]
ah. it appears to be fixed as part of https://github.com/helm/helm/issues/9312

so I guess I will have to wait for helm 3.6. I don't suppose it is likely that this will get backported to 3.5?

**Comment by bacongobbler** [comment]
Ah yes thank you for finding that. Yes this appears to be a duplicate issue.

It's not likely to be backported. 3.5.4 was the last scheduled patch release before 3.6.
