### ISSUE TITLE
Google qwiklab

### ISSUE THREAD

**Issue by thepankajtech** [helm/helm#9638]
rror: error parsing deployments/auth.yaml: error converting YAML to JSON: yaml: line 19: mapping values are not allowed in this context

**Comment by bacongobbler** [comment]
Hi @thepankajtech. I'm not sure what I'm supposed to make of this report. Please provide more information. Thanks.

**Comment by bacongobbler** [comment]
Closing as there's insufficient information here to determine the issue. Closing for now. We can re-open once more information has been provided. Thanks.
