### ISSUE TITLE
`helm lint` wrongly fails

### ISSUE THREAD

**Issue by cwrau** [helm/helm#9643]
Output of `helm version`: 

```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"dirty", GoVersion:"go1.16.3"}
```

Output of `kubectl version`:

Doesn't apply

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Doesn't apply

# Problem

Since at least this new release, the attached [helm chart](https://github.com/helm/helm/files/6365716/test.tar.gz) fails to `helm lint . --values values2.yaml`

As I understand the schema it should though.

If I remove `/oneOf/0` it fails, if I remove `/oneOf/1` it works, giving me the impression that only one of them validates, as it should and I expect.

But when both are used, it fails.

**Comment by bacongobbler** [comment]
When `-f` or `--values` is applied, the values are merged into each other. In other words, the properties in values2.yaml are merged and overwriting values in values.yaml. That would explain why the schema validation fails.

As a result, your computed values look like this by default:

```
><> helm install --dry-run . --generate-name --debug
[...]
COMPUTED VALUES:
mariadb:
  enabled: true
mysql:
  enabled: false
server:
  database: {}
```

And with values2.yaml merged in, your computed values now look like this:

```
><> helm install --dry-run . --generate-name --debug -f values2.yaml
[...]
COMPUTED VALUES:
mariadb:
  enabled: false
mysql:
  enabled: false
server:
  database:
    existing:
      host: host
```

Based on your schema, I'm assuming that you want to enable one or the other. To fix this, do not set both database values to `false` in values2.yaml. Instead set one to `true`.

You did mention though:

> Since at least this new release,

So I tested this with Helm v3.4.2. I still received the same result.

```
><> ./linux-amd64/helm version
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}
><> ./linux-amd64/helm lint .
==> Linting .
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, 0 chart(s) failed
><> ./linux-amd64/helm lint . -f values2.yaml
==> Linting .
[INFO] Chart.yaml: icon is recommended
[ERROR] values.yaml: - (root): Must validate one and only one schema (oneOf)


Error: 1 chart(s) linted, 1 chart(s) failed
```

If you can determine when this behaviour might've changed, then we can analyze what might've caused the change in behaviour. But as far as I know this has been the expected behaviour since Helm 2.

Hope this helps.

**Comment by cwrau** [comment]
It's intentionally either `mariadb.enabled`, `mysql.enabled` or `server.database.existing.host`;

(`mariadb.enabled`|`mysql.enabled`)|`server.database.existing.host`

Test matrix;

| mysql.enabled | mariadb.enabled | server.database.existing.host |  result |
|---------------|-----------------|-------------------------------|:-------:|
| true          | true            | set                           |   fail  |
| true          | true            | not set                       |   fail  |
| true          | false           | set                           |   fail  |
| true          | false           | not set                       | success |
| false         | true            | set                           |   fail  |
| false         | true            | not set                       | success |
| false         | false           | set                           | success |
| false         | false           | not set                       |   fail  |


And my testing with omitting one or the other `/oneOf/`s shows that, although only one of them work, both together don't, which doesn't make sense I think

I also found the last version in which this worked, it's 3.1.2

Using that version it works just as expected; if I change one or both of `mariadb.enabled` and `mysql.enabled` to `true` or remove `server.database.existing.host` it fails.

**Comment by cwrau** [comment]
You can use the following script to verify;

```bash
for ma in true false; do
  for my in true false; do
    for host in host ''; do
      echo "mariadb: $ma, mysql: $my, host: $host"
      helm lint . --values /dev/stdin <<EOF &>/dev/null
mariadb:
  enabled: $ma
mysql:
  enabled: $my
server:
  database:
    existing:
      host: $host
EOF
      result=$?
      if ([ "$ma" = 'true' ] && [ "$my" = 'false' ] && [ "$host" = '' ]) ||
        ([ "$ma" = 'false' ] && [ "$my" = 'true' ] && [ "$host" = '' ]) ||
        ([ "$ma" = 'false' ] && [ "$my" = 'false' ] && [ "$host" = 'host' ]); then
        if [ $result = 0 ]; then
          echo 'valid 👍️'
        else
          echo 'invalid 👎️'
        fi
      else
        if [ $result = 1 ]; then
          echo 'invalid 👍️'
        else
          echo "valid 👎️"
        fi
      fi
    done
  done
done
```

**Comment by cwrau** [comment]
Weirdly enough the `false`, `false`, `host` case is the only one the current helm fails

And `true`, `true`, `host` is the only one helm 3.1.2 fails 🙈

**Comment by cwrau** [comment]
Do you got any updates on this?

Can I do something to help?

**Comment by almson** [comment]
For what it's worth, Helm is using an unmaintained json schema library that hasn't been updated in 2 years https://github.com/xeipuuv/gojsonschema Doubt this issue is going to be addressed.

**Comment by cwrau** [comment]
This is still relevant, please reopen
