### ISSUE TITLE
Helm linting library templates in subcharts

### ISSUE THREAD

**Issue by usimd** [helm/helm#9645]
Output of `helm version`:
`version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}`

Output of `oc version`:
`Client Version: 4.6.0-202102050644.p0-e12ee36
Kubernetes Version: v1.11.0+d4cacc0`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): on premise OpenShift

## Problem
Given the following chart directory structure
```
$ tree
.
├── library
│   ├── Chart.yaml
│   └── templates
│       └── _included-template.yaml
└── mychart
    ├── charts
    │   └── mysubchart
    │       ├── Chart.yaml
    │       └── templates
    │           └── deployment.yaml
    ├── Chart.yaml
    └── values.yaml
```
with `library/Chart.yaml` being of type `library`, `_included-template.yaml` containing
```
{{- define "library.test" -}}
- name: FOO
  value: BAR
{{- end -}}
```
I declared the parent `mychart/Chart.yaml`'s dependencies as
```
dependencies:
  - name: library
    version: 0.1.0
    repository: file://../library
  - name: mysubchart
    version: 0.1.0
```
and the subchart's `deployment.yaml`
```apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "test"
          env:
            - name: BAR
              value: FOO
            {{- include "library.test" . | indent 12 }}
```
Now running `helm dependency update mychart && helm lint mychart --with-subcharts` fails with 
```==> Linting mychart/charts/mysubchart
[INFO] Chart.yaml: icon is recommended
[INFO] values.yaml: file does not exist
[ERROR] templates/: template: mysubchart/templates/deployment.yaml:14:16: executing "mysubchart/templates/deployment.yaml" at <include "library.test" .>: error calling include: template: no template "library.test" associated with template "gotpl"
```
Installation or upgrade of Helm charts is working fine. Am I missing something?

Thanks for your support!

Edit: fwiw, here's a full example demonstrating the problem.
[helm-lint-test.zip](https://github.com/helm/helm/files/6504219/helm-lint-test.zip)

**Comment by keviiin38** [comment]
Same issue here, I'm not using a library chart but the problem is the same.

`helm template`, `helm upgrade`, etc... just work fine, but running `helm lint` causes this error ...

**Comment by dnozay** [comment]
I have had the same issue when using the directory of the chart.
I have found that making the tgz with `helm package` and using the tgz as input rather than the directory works for me. YMMV

**Comment by voyachek** [comment]
I have had the same issue. `helm lint mychart --with-subcharts` does not work as expect with included templates.

**Comment by usimd** [comment]
> I have had the same issue when using the directory of the chart. I have found that making the tgz with `helm package` and using the tgz as input rather than the directory works for me. YMMV

Do you mean to package all dependencies separately? I tried both (individually and separately) but did not succeed, somehow.

**Comment by fbrodrigorezino** [comment]
I'm getting the same situation, the dependent charts render correctly but fail on linting.
