### ISSUE TITLE
Extend `genSignedCert` function parameter `ips` type

### ISSUE THREAD

**Issue by YuryHrytsuk** [helm/helm#9647]
# How to reproduce
The code below produces the error `... at <$ips>: wrong type for value; expected []interface {}; got []string`
```
{{- $ips := splitList "," "1.1.1.1,2.2.2.2" -}}
{{- $genCert := genSignedCert .cn $ips nil 3650 .ca }}
```

# Question/suggestion
Probably, the type `[]string` should be acceptable ? 
Reasons:
* it seems to be correct logically
* it is useful when dealing with raw user input.

# Workaround
Adding `compact` function does the trick
```
{{- $ips := splitList "," "1.1.1.1,2.2.2.2" | compact -}}
{{- $genCert := genSignedCert .cn $ips nil 3650 .ca }}
```

# Environment info
Output of `helm version`: 
```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"dirty", GoVersion:"go1.15.4"}
```

Output of `kubectl version`: 
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
```

**Comment by bacongobbler** [comment]
Hi @YuryHrytsuk.

`genSignedCert` is a function defined by the sprig library. If you wish to add enhancements to the functions, please file a ticket over at https://github.com/Masterminds/sprig

For reference: http://masterminds.github.io/sprig/crypto.html

Thanks.
