### ISSUE TITLE
Helm stripping comments from chart

### ISSUE THREAD

**Issue by bocajim** [helm/helm#9649]
Version 3.5.4 of helm on linux.

Let me start by saying I've seen several other issues from a year ago referencing a similar issue, but this seems different, and I can't tell where the problem is coming from.

My charts are stored in the Azure Container Registry as an OCI repo.  I have 2 charts, we'll call it "Chart1" and "Chart2", and "Chart2" depends on "Chart1".  In Chart2, I don't package Chart1, I just reference it in the dependencies of the Chart.yaml.

Here is the basic sequence to get to the problem...

```
#save and push chart1
helm chart save Chart1 xxx.azurecr.io/helm/Chart1:1.0.0
helm chart push xxx.azurecr.io/helm/Chart1:1.0.0

#save and push chart2
helm chart save Chart2 xxx.azurecr.io/helm/Chart2:1.0.0
helm chart push xxx.azurecr.io/helm/Chart2:1.0.0

#on another system where I want to deploy the chart

#get chart2
helm chart pull xxx.azurecr.io/helm/Chart2:1.0.0 
helm chart export . xxx.azurecr.io/helm/Chart2:1.0.0 

#pull dependency
helm dependency update Chart2

```

Now here is what I see, in Chart2/values.yaml, it was stripped of comments and sorted alphabetically.  I expected it to be the values.yaml that I submitted that had many comments and was organized logically instead of alphabetically.

In Chart2/charts/Chart1-1.0.0.tgz, the values.yaml file is in the original format (including comments and my ordering), so that one is preserved.  I only note pulling the dependencies and comparing here because the behavior is different than the values.yaml in the base chart.

Any idea why the values.yaml got re-written?

EDIT 4/28: Fixed helm commands from "helm save" and "helm push" to "helm chart save" and "helm chart push"

**Comment by bacongobbler** [comment]
Hi @bocajim. I notice you're using a couple third party plugins. `helm save` and `helm push` are commands that are not provided by Helm.

Can you share the output of `helm plugin list` for me?

**Comment by bacongobbler** [comment]
For reference, here is the official documentation on working with OCI chart registries. `helm chart save` and `helm chart push` are two commands provided by Helm. I'd suggest giving that a try and see if your results differ.

https://helm.sh/docs/topics/registries/

**Comment by bocajim** [comment]
Sorry for being an idiot, I am using helm chart save and helm chart push, my example was incorrect.  I updated my example.

**Comment by bacongobbler** [comment]
Please have a look at #9782 - `helm chart save` is being removed in favour of `helm package` and `helm push`. The chart should not be re-packaged any different than it would be for a chart repository.

Can you test that PR and provide feedback?
