### ISSUE TITLE
Implement helm install --dry-run=client (maybe for local testing purpose)

### ISSUE THREAD

**Issue by Laurianti** [helm/helm#9654]
Is it possibile to implement a "dry-run client" as in k8s?

https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands
![image](https://user-images.githubusercontent.com/20415513/116372799-137e0800-a80d-11eb-927e-447ff98cb4ea.png)

I would like to test without a server the output yaml.
Any alternative to this? I think it use "helm template".
https://github.com/Stono/helm-test

**Comment by bacongobbler** [comment]
`helm template`?

**Comment by Laurianti** [comment]
Are you sure about --dry-run?

![image](https://user-images.githubusercontent.com/20415513/116442130-6e861e00-a852-11eb-8278-a27cde8e30bd.png)

**Comment by bacongobbler** [comment]
Ah yes, sorry. `--dry-run` requires a live kubernetes cluster. `helm template` does not.

**Comment by Laurianti** [comment]
But in documentation:
https://helm.sh/docs/chart_template_guide/functions_and_pipelines/

![image](https://user-images.githubusercontent.com/20415513/117675060-85ab0100-b1ac-11eb-8579-1e25c55a7abe.png)

I'm confused.

**Comment by Laurianti** [comment]
I think should be possible.

**Comment by bacongobbler** [comment]
Use `helm template` for this.
