### ISSUE TITLE
helm lint not finding subchart imported values when templates in main chart

### ISSUE THREAD

**Issue by mederel** [helm/helm#9658]
While working on some complex helm charts I isolated a weird lint issue. I worked on isolating what triggered it and wrote a sample reproducer:

[helm-lint-issue-reproducer.zip](https://github.com/helm/helm/files/6923230/helm-lint-issue-reproducer.zip)

The following setup:

* `libchart` is a library chart defining a template and a value copied.value
* `subchart` depends on `libchart` and uses the template with `{{ template name . }}`
* `mainchart` is kind of an umbrella chart that depends on `subchart`, but defines a YAML file too

Linting on the mainchart after dependency builds are done breaks with the following error:

```
[ERROR] templates/: template: mainchart/charts/subchart/charts/libchart/templates/_object.yaml:5:19: executing "object.template" at <.Values.copied.value>: nil pointer evaluating interface {}.value
```

If you remove the templates folder from the mainchart, lint starts working again.

Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
```

This issue is independent of the version of kubectl or the cloud provider chosen: it is pure helm lint.

**Comment by technosophos** [comment]
This looks like a bug in the way the linter is loading the chart. Adding the bug label.

**Comment by mederel** [comment]
Hi, the reproducer was actually flawed so I fixed it. New version updated in issue description.

**Comment by loganknecht** [comment]
Is there any progress on this?

My organization is experiencing this issue as well, except we can't validate anything that's an abstraction away from the `libchart`?

Effectively with the same setup above we cannot `helm lint` the `sub chart` or the `main chart`.

It is quite frustrating

**Comment by stuartdrennan** [comment]
Just waiting for the maintainers to review and PR and me, first time committer to helm

**Comment by mederel** [comment]
Hi @loganknecht and @stuartdrennan may I say something too? This item was opened after suffering in my own orga. And I have had no time and no motivation to contribute. Kudos to you @stuartdrennan if you start contributing. @loganknecht I hope you measure the effort being put together here. Wish you all a good week's ending! @mederel
