### ISSUE TITLE
helm Chart.Version change causes pod restart

### ISSUE THREAD

**Issue by sunchill06** [helm/helm#9660]
Output of `helm version`: version.BuildInfo{Version:"v3.3.3", GitCommit:"597229301293487c18abdaf1d0a94f19718ad233", GitTreeState:"clean", GoVersion:"go1.13.10"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-23T07:48:43Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-23T07:40:51Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

on-prem

**Issue description:**

Inside my chart, I have Chart.yaml 

---
apiVersion: v1
appVersion: "4.0"
description: A Helm chart for deploying test-app on Kubernetes
name: test-app
**version: 1.0.0-20**

When the Chart.version i.e. **version: 1.0.0-20** is changed to **version: 1.0.0-21** and then I perform helm upgrade to let's say reset the value of a values.yaml parameter (this is not an image upgrade), it actually restarts the existing pods which is not desired.

Chart.version is used as a label in our deployment. When we take out the Chart.Version from the sts labels, this doesn't happen.

Why updating Chart.Version causes pod restart? Is this expected and if yes, how can we get around this as we do want to keep the Chart.Version as a label in the pods.

**Comment by bacongobbler** [comment]
Hi @sunchill06. Without any knowledge of how your template structure works I cannot determine whether this is intentional or not.

In an isolated environment, changing your chart version does not cause pods to restart. You can reproduce this yourself with the following test case to verify:

```
$ helm create test-9660
$ helm install foo .
$ vim Chart.yaml # change the version field
$ helm upgrade foo .
```

**Comment by sunchill06** [comment]
Hi @bacongobbler, Thanks for responding.

I tried with the chart test9660 (provided by you) and I can reproduce the issue with this chart as well if I use the Chart.Version label as part of PodTemplateSpec as well. Same is the setup in my deployment. Chart.version is being used a label in both the deployment and pod template spec.

So as can be seen in the following deployment template, the label  **helm.sh/chart: test9660-0.1.0**, if set in both the deployment and pod template spec, and when the Chart.Version is changed and helm upgrade is performed, pod is restarted.

Is this expected behavior?

`apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: testmiwithpsl
    meta.helm.sh/release-namespace: bam-ns
  creationTimestamp: "2021-04-30T07:57:14Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: testmiwithpsl
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: test9660
    app.kubernetes.io/version: 1.16.0
    **helm.sh/chart: test9660-0.1.0**
  name: testmiwithpsl-test9660
  namespace: bam-ns
  resourceVersion: "9683586"
  selfLink: /apis/apps/v1/namespaces/bam-ns/deployments/testmiwithpsl-test9660
  uid: 1d5f1543-575f-4114-b8fd-e96751ef20fe
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: testmiwithpsl
      app.kubernetes.io/name: test9660
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: testmiwithpsl
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: test9660
        app.kubernetes.io/version: 1.16.0
        **helm.sh/chart: test9660-0.1.0`**

**Comment by bacongobbler** [comment]
Yes.

**Comment by sunchill06** [comment]
Hi @bacongobbler , so pod label change is cobsidered a template change during helm upgrade. Is there any documentation that supports this? And why label change doesn't matter for deployment spec? Any clarification here would be great.

**Comment by technosophos** [comment]
Yes, any change to the rendered output is considered an upgrade change. This is because Helm does not have any knowledge about how other things use content, and things like labels are "functional" in Kubernetes.
