### ISSUE TITLE
Parametrize Helm binary name in output

### ISSUE THREAD

**Issue by viccuad** [helm/helm#9664]
Hello,

Currently, output of Helm's CLI contains the string `helm`. E.g: 
`show uninstalled releases (if 'helm uninstall --keep-history' was used)`, 
`Error: failed to download "somechart" (hint: running helm repo update may help)`,
etc.

It would be nice if that wasn't the case, so `cmd/` could be reused downstream (even if it isn't covered by semver assurances), or one could rename the helm binary transparently (for example, having a `helm3.4.0` and a `helm3.5.4` binaries, and getting their output to contain those).

A simple implementation would be to use `OS.Args[0]`.

**Comment by bacongobbler** [comment]
There are quite a few locations where the word "helm" is referenced in the code base; most are present in package `cmd`, but there are a few (like this error message) that are in `pkg/action` or `pkg/downloader`, which might be trickier as those packages are used in external dependencies.

**Comment by viccuad** [comment]
Seems that I missed the stale bot by 9h. I am still personally interested in this for consuming Helm as a dependency, as stated by Helm's API and SDK assurances.
