### ISSUE TITLE
Default running of v2 get script fails due to v2 versions not returning in first page of releases page.

### ISSUE THREAD

**Issue by danaucpe** [helm/helm#9666]
Output of `helm version`: v2.17.0

Output of `kubectl version`: v1.19.3

Cloud Provider/Platform (AKS, GKE, Minikube etc.): EKS

When trying to run an old pipeline that still fetches older helm versions I see the following error in our pipeline logs

```
Step 4/13 : RUN curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get > get_helm.sh
 ---> Running in 868fb71705f6
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7163  100  7163    0     0  69543      0 --:--:-- --:--:-- --:--:-- 69543
Removing intermediate container 868fb71705f6
 ---> 2eb0e72e8861
Step 5/13 : RUN chmod 700 get_helm.sh
 ---> Running in fdcb117b96d2
Removing intermediate container fdcb117b96d2
 ---> cfb7ad14ab05
Step 6/13 : RUN ./get_helm.sh
 ---> Running in f6d8376405fa
Downloading https://get.helm.sh/helm--linux-amd64.tar.gz
SHA sum of /tmp/helm-installer-JjiEaF/helm--linux-amd64.tar.gz does not match. Aborting.
Failed to install helm
	For support, go to https://github.com/helm/helm.
The command '/bin/sh -c ./get_helm.sh' returned a non-zero code: 1
make: *** [Makefile:23: image] Error 1
```

I believe this is still supported since the get script is still here: https://github.com/helm/helm/blob/main/scripts/get

I believe this is failing because the curl to fetch the release and grep for v2 versions is paginated and all v2 versions are showing on the next page. see - https://github.com/helm/helm/blob/main/scripts/get#L80

The right thing to do here is probably just hardcode to v2.17.0 as it is the latest v2, rather than parsing the release pages, since this is the process when no version is passed in.

**Comment by danaucpe** [comment]
suggested fix: https://github.com/helm/helm/blob/main/scripts/get#L76

```# checkDesiredVersion checks if the desired version is available.
checkDesiredVersion() {
  if [ "x$DESIRED_VERSION" == "x" ]; then
    # Get that last v2 version is none is supplied
    TAG=v2.17.0
  else
    TAG=$DESIRED_VERSION
  fi
}

**Comment by bacongobbler** [comment]
#9607
