### ISSUE TITLE
[Question] Can we ignore a template to be rendered but create the manifest as it is

### ISSUE THREAD

**Issue by viveksinghggits** [helm/helm#9667]
I have an usecase where I want to create a custom resource using the helm chart. The problem is the CR definition has go templates that is resolved by operator that is there to handle this CR.
The problem arises when we try to install this chart, helm tries to render the CR manifest and fails because it will not be able to find the template functions that are there in the CR.
Is there a way using which we can ignore the rendering of some of the manifests while helm install, and just apply the manifest on the cluster?
I was thinking if `.helmignore` would be useful but its not.

**Comment by technosophos** [comment]
Any file in the `crds/` folder will be loaded into Helm without going through the template renderer.

Otherwise, if you want it in the `templates/` folder, you will need to get creative with the escaping.

**Comment by joejulian** [comment]
I haven't tested this but you should be able to wrap your go template as a string literal, ie:
```
spec:
   interpretedTemplate: {{ .Value.something }}
   notInterpretedTemplate: {{`{{ .OperatorValue.somethingelse }}`}}
```

Give it a try and let me know how it works out.

**Comment by viveksinghggits** [comment]
Thanks @technosophos @joanrieu 
Both of the ways are working thank you for responding.
I am gonna go with the `crds` dir.
