### ISSUE TITLE
helm error failed to create: the server responded with the status code 413 but did not return more information (post secrets)

### ISSUE THREAD

**Issue by prab2014** [helm/helm#9668]
Output of `helm version`:3.5.3

Output of `kubectl version`: Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.8",
Client Version: version.Info{Major:"1", Minor:"21"

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  k8 ,kind

i am trying to install kube-prometheus-stack on my cluster and getting the below error.
Error: create: failed to create: the server responded with the status code 413 but did not return more information (post secrets)
Command : install kube-prom prometheus-community/kube-prometheus-stack

Reference  Links-- https://github.com/prometheus-community/helm-charts
https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack.

Ay help would be appreciated. i believe, it should not be issue with the cluster memory and all.

**Comment by yxxhero** [comment]
is your k8s cluster  proxy by nginx or other agency services?

**Comment by bacongobbler** [comment]
Hi @prab2014. Can you please open a ticket with the kube-prom chart maintainers? This appears to be a chart issue. I'm not sure there's anything we can do here to address this issue in Helm.
