### ISSUE TITLE
Compare Deployment vs Helm Chart Deployed

### ISSUE THREAD

**Issue by mhobotpplnet** [helm/helm#9669]
This is just a general question if there is a tool or a way to compare helm chart that was deployed vs say deployment/ingress/service. Reason I ask is because say someone made a manual change to deployment that is different than what was deployed via helm, I would like to find out the differences.

**Comment by barkardk** [comment]
Not sure if this is what you are asking for but you can compile the templates from the helm package to see what it will look like before it is installed , so for example  this command will show you the generated manifests as they would look at the time of deployment. 
```bash
$ helm3 template --debug <url or path to package>/grafana-5.2.11.tgz
```
You could  use that output and compare it with the deployed manifests and look for discrepancies ?

**Comment by bacongobbler** [comment]
Yes, there are third-party tools for diffing between what's currently installed and what will change during an upgrade. [helm-diff](https://github.com/databus23/helm-diff) is one such tool. It was built for Helm 2, however, and there's an open ticket to update it to work with 3-way merge patches as done in Helm 3 here: https://github.com/databus23/helm-diff/issues/176

If you are interested in that kind of functionality, I would suggest contributing to that project.

Hope this helps!

**Comment by bacongobbler** [comment]
See also https://github.com/helm/helm/issues/8718.

**Comment by mhobotpplnet** [comment]
Thank you @bacongobbler and @barkardk .I do use helm2 and helm3 and helm diff def works as far as like comparing revisions but not necessarily when say a Dev makes manual changes to a deployment file on fly that makes it diff from helm chart that was deployed. While I could go deployment to deployment it would take me quite some time. 
I do know that tools like ArgoCD checks whatever its in github/helm vs deployment.

Thank you for your input much appreciated!

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!
