### ISSUE TITLE
Auditing Helm 2 for GHSA-c38g-469g-cmgx

### ISSUE THREAD

**Issue by bitscuit** [helm/helm#9670]
Output of `helm version`:

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

I understand that Helm 2 is out of support, so there was no audit to determine if it was vulnerable to https://github.com/helm/helm/security/advisories/GHSA-c38g-469g-cmgx, but my organization uses an internal fork of Helm 2, specifically v2.16.12. Other than looking through the code, is there a series of steps/interactions I can perform with Helm to determine if it is vulnerable or not? I saw this in the advisory

> Core maintainers were able to send deceptive information to a terminal screen running the helm command, as well as obscure or alter information on the screen. In some cases, we could send codes that terminals used to execute higher-order logic, like clearing a terminal screen.

But are there any details on what exactly was done, so I could try and replicate it with Helm 2?

I also found the commit that fixes this issue https://github.com/helm/helm/commit/6ce9ba60b73013857e2e7c73d3f86ed70bc1ac9a. Are these all the changes that were necessary to resolve it?

**Comment by bacongobbler** [comment]
Hi @bitscuit. Generally speaking we do not disclose explicit details of a security vulnerability. We will not be providing further details other than what's been disclosed in the advisory. I'm sorry I cannot help you further.

The same code present in Helm 3 is there in Helm 2, so yes, it is to be assumed that there are parts of Helm 2 that are susceptible to the vulnerability.

As Helm 2's support lifecycle ended last November, I am going ahead and closing this.
