### ISSUE TITLE
proposal: helm install/upgrade CRD only

### ISSUE THREAD

**Issue by Jimmy-Newtron** [helm/helm#9671]
While reading the documentation about the CRDs [best practices](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/) I have detected a corner case.

Let say that I am a cluster administrator and that I want to install a chart from an open source community, for example the [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack)

The mentioned chart is built to be installed with the [method 1](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you): automatic install of all resources (CRDs before the other manifests)

Now lets imagine I want to use the [method 2](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you) separate installation for CRDs and the other manifests

To achieve this I was thinking to execute something like the following:
```sh
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update
# Helm
helm install prometheus-crds prometheus-community/kube-prometheus-stack --version 15.4.4 --only-crds
# ...
# Here install any resources that use the prometheus CRD (for example ServiceMonitors)
# ...
helm install prometheus-stack prometheus-community/kube-prometheus-stack --version 15.4.4 --skip-crds
```

**Comment by bacongobbler** [comment]
Hi @Jimmy-Newtron. We ask that any proposals to the project be written up as a Helm Improvement Proposal. Have a look at the [Contributing guide](https://github.com/helm/helm/blob/main/CONTRIBUTING.md#proposing-an-idea) for next steps. Thanks!

**Comment by Jimmy-Newtron** [comment]
> Issues that are labeled feature or proposal must write a Helm Improvement Proposal (HIP). See Proposing an Idea. Smaller quality-of-life enhancements are exempt.

I think that in this case the problem statement is perfectly clear in the first message description and we are in the second case

> Smaller quality-of-life enhancements are exempt.

@bacongobbler what will be the next step in this case?
I am not really a contributor today and I have not such possibility in the short term.

**Comment by bacongobbler** [comment]
Sorry for the confusion here. Quality-of-life enhancements are defined more as formatting cleanups on output, new compiler targets, code refactors, etc. Proposing a new feature to Helm's codebase needs to take into consideration other proposals as well as the existing features available, which is why I suggested writing a HIP.
