### ISSUE TITLE
Feature Request: Ability to override/omit subchart templates

### ISSUE THREAD

**Issue by Imunhatep** [helm/helm#9672]
I’ve written a helm parent chart to wrap a stable public chart. The public chart didn’t provide for the creation of a basic auth secret, and so my wrapper chart adds that. This works well.

However, now I’d like to see some features added to the child chart — such as anti-affinity, more than 1 replica, and so on.

Is there any way from a parent chart to override/omit the child chart templates, beyond what is exposed in values.yaml? In this example, child chart doesn’t parameterize the replica integer. I can always contribute parameterization upstream, but the intent is to not fork upstream for too long. And contributing upstream has lag time. Thoughts?

**Comment by bacongobbler** [comment]
Hi @Imunhatep. Have you looked at past issues/tickets asking for similar feature requests? I believe this has been asked in the past and there are some features that help address these cases such as the [post-renderer flag](https://helm.sh/docs/topics/advanced/#post-rendering). Hope that helps.

in any case, we ask that any proposals to the project be written up as a Helm Improvement Proposal. Have a look at the [Contributing guide](https://github.com/helm/helm/blob/main/CONTRIBUTING.md#proposing-an-idea) for next steps. Thanks!

**Comment by Imunhatep** [comment]
Hi @bacongobbler, 

yes this question has been asked before and `post-renderer flag` approach suggested. Yet this approach as mentioned in #3045 does not answers pointed out missing features. So my main point here is that post-render and chart extending/overriding are not the same features.. and one cant fully substitute the other. 

---
The `--post-renderer` option is good but doesn't let you utilize values from `values.yaml` into templates. For instance, I would like to add an extra template to an upstream chart and utilize one of the values from `values.yaml`. I don't think `post-renderer` can do that.

_Originally posted by @musabmasood in https://github.com/helm/helm/issues/3045#issuecomment-653664886_
