### ISSUE TITLE
Add option to `helm chart list` to avoid truncating refs with ellipsis

### ISSUE THREAD

**Issue by jsolbrig** [helm/helm#9678]
# Problem

Currently, if you call `helm chart list` and you have saved charts with long refs, the refs will be truncated with ellipsis. This is a problem because it cuts off the more changeable portions of the chart ref including the end of the registry and the tags. This makes it hard to determine what is stored in the local cache.

It would be helpful if a flag could be added to `helm chart list` that would force it to print the entire ref, no matter how long it is. Something like `helm chart list -l/--long`.

# Question

In the mean time, is there a way to work around this problem? I currently have several charts cached on my local machine whose refs always get truncated. I don't remember what tags they used and am unable to delete them.

Is there a way to find the full refs for existing saved charts?

Output of `helm version`: 
```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-07-04T15:01:15Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
```
*I should probably upgrade...*

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
On-prem

**Comment by bacongobbler** [comment]
No, there is no workaround. The maximum column width is hard-coded.

https://github.com/helm/helm/blob/43853ea772e779b617b011a8d4e69205636fa4f9/internal/experimental/registry/client.go#L282
