### ISSUE TITLE
Immutable revisions (for up-to-date Kuberrnetes clusters with Secret or ConfigMap revisions)?

### ISSUE THREAD

**Issue by ari-becker** [helm/helm#9693]
Since Kubernetes 1.19, the `ImmutableEphemeralVolumes` feature gate has reached Beta and has been enabled by default, reaching GA in Kubernetes 1.21. The feature gate permits adding `immutable: true` to Secrets and ConfigMaps, indicating that the `data` field will not be changed. See: https://kubernetes.io/docs/concepts/configuration/secret/#secret-immutable

If the target Kubernetes cluster is running 1.19+ (i.e. if it has the `ImmutableEphemeralVolumes` feature gate enabled), and if Helm is using Secrets or ConfigMaps to store release revisions, then shouldn't Helm try to add this field for the release revision? Do release revisions change after they have been created (except for changing the `status` label, which it sounds like is still legal for Immutable Secrets and ConfigMaps)?

The reason for doing so, as promised by the Kubernetes documentation (see link above): `[this] improves performance of your cluster by significantly reducing load on kube-apiserver, by closing watches for secrets marked as immutable.` and that it's supposed to be particularly apparent for large clusters where there are tens of thousands of secrets or more (understandable in environments where everything runs in a giant namespace and there are long Helm histories for everything that runs in that namespace).

**Comment by bacongobbler** [comment]
> Do release revisions change after they have been created (except for changing the `status` label, which it sounds like is still legal for Immutable Secrets and ConfigMaps)?

The data should not change, only the labels (specifically `modifiedTime` and `status`).

This seems like a useful feature. Because this may impact others, it would be useful to [write a HIP](https://github.com/helm/helm/blob/main/CONTRIBUTING.md#proposing-an-idea) so others can discuss it and answer questions like backwards compatibility, or if there may be cases where marking it as immutable may not be desirable.

**Comment by bacongobbler** [comment]
@ari-becker have you had the chance to look into my last comment? We're just waiting for your Helm Improvement Proposal on this subject for review. :)

**Comment by anvpetrov** [comment]
We are really looking forward to the opportunity to keep  release secrets with the tag _immutable: true_
For large dev clusters, this is a silver bullet
