### ISSUE TITLE
Delete installed chart

### ISSUE THREAD

**Issue by marenero1974** [helm/helm#9695]
Hi all,

i am using helm 2, and i have a previously installed chart that has some pv and pvc associated that has the Reatain policy. My question is if i delete it whit heml delete ... should i have data losses, and what other side effects should i have?

Thanks

**Comment by bridgetkromhout** [comment]
Hi, @marenero1974 - [Helm 2 is no longer supported](https://helm.sh/blog/helm-2-becomes-unsupported/). You can look at the legacy docs here: https://v2.helm.sh/docs/charts_tips_and_tricks/#tell-tiller-not-to-delete-a-resource

We strongly recommend that you [move to Helm 3](https://github.com/helm/helm-2to3), as Helm 2 receives no updates, including security updates.

**Comment by marenero1974** [comment]
Thanks @bridgetkromhout
