### ISSUE TITLE
Unable to nullify global values in sub chart

### ISSUE THREAD

**Issue by abhinaybyrisetty** [helm/helm#9696]
Output of `helm version`: 
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}

Output of `kubectl version`: 
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.10+IKS", GitCommit:"625e0232c45f878423cb1285322bf54ad8a3993f", GitTreeState:"clean", BuildDate:"2021-04-20T22:44:26Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Any cloud

Description:
I have been trying to nullify values in sub chart that are passed via global section in values.yaml.

values.yaml
```
global:
  sub1:
    key: value
```

When I use this in the subchart x as `.Values.global.sub1.key`, it works perfectly fine. I can also override it using `--set global.sub1.key=newValue`. However, when I try to nullify the value, it fetches the default value from the actual values.yaml. 

i.e `--set global.sub1.key=null`, it still fetches the default value from the original values.yaml.

Please let me know if you need any additional information.

**Comment by ingshtrom** [comment]
I am curious about this as well as I've run into this with the https://github.com/hashicorp/consul-helm chart as well. We cannot set the resources limit to null because the default `values.yaml` sets it to something low. 

I have made a minimal repository with two Helm charts showing off exactly how this works. https://github.com/ingshtrom/helm-test-null

**Comment by ingshtrom** [comment]
Even stranger, even though my manual test in my helm-test-null repo shows something working incorrectly, the tests for this actually pass (https://github.com/helm/helm/blob/main/pkg/chartutil/coalesce_test.go)

I even modified them manually by adding the following test `{"{{.pequod.ahab.nested.bar}}", "<no value>"},` and it passed there as well, in addition to some other manual modifications I thought would fail based on my testing. Are you still having the issue @abhinaybyrisetty?

**Comment by bacongobbler** [comment]
OP raised the issue with Helm 3.5.0. I believe there have been a few fixes in Helm 3.6.0 that could have fixed this issue.

Can you please test again using Helm 3.6.0?

**Comment by bacongobbler** [comment]
Apologies for the confusion; I meant if the OP can try again with 3.6.0.

**Comment by abhinaybyrisetty** [comment]
@bacongobbler I upgraded to 3.6.2, it doesn't work still.
