### ISSUE TITLE
The method(`pkg.action.Configuration#Init`)  should not panic

### ISSUE THREAD

**Issue by wuhuizuo** [helm/helm#9698]
Output of `helm version`: `3.5.4`
Output of `kubectl version`: `none`
Cloud Provider/Platform (AKS, GKE, Minikube etc.): `none`

method `pkg.action.Configuration#Init ` designed to return error, but  it will panic when error happend.

the references of `pkg.action.Configuration#Init`
- cmd/helm/helm.go:72 log.Fatal if err happend 
- cmd/helm/list.go:74 return the err if err happend

Above all, I think it should not panic in `Init` method.

**Comment by bacongobbler** [comment]
If you initialize a storage backend and it fails to initialize, how is the developer expected to recover?

This seems like one of the few cases where a `panic` makes the most sense. `panic` is designed to exit the program early if the error is irrecoverable or the program enters an abnormal state. We wrote `Init` with the assumption that if the storage driver fails to initialize, there is no way to recover. Therefore a stack trace should be returned to the user, and as a result a `panic` made sense here.

**Comment by wuhuizuo** [comment]
> If you initialize a storage backend and it fails to initialize, how is the developer expected to recover?
> 
> This seems like one of the few cases where a `panic` makes the most sense. `panic` is designed to exit the program early if the error is irrecoverable or the program enters an abnormal state. We wrote `Init` with the assumption that if the storage driver fails to initialize, there is no way for the program to recover. Therefore a stack trace should be returned to the user, and as a result a `panic` made sense here.
> 
> Can you provide an example where `panic` would not make sense? How do you envision the program can recover from a failed storage init?

Why the `Init` designed with a error return ? :question: 

And there are two using places, one panic(will never happen, bease no real error return from `Init`), anotherone return error(would  be never traveled)

**Comment by wuhuizuo** [comment]
If it should panic early, it should designed without error return.

I using `helm` pkg to develop upstream service, and I called the `Init` method.
@bacongobbler

**Comment by cndoit18** [comment]
Maybe we can have `Init() error` and `InitOrDie()`

**Comment by bacongobbler** [comment]
I will re-iterate the question: how is the developer expected to recover when they either provide an invalid storage driver, or the sql client fails to initialize?

In both of those cases, invalid input was provided.

**Comment by wuhuizuo** [comment]
> 我将再次重申这个问题：当开发人员提供无效的存储驱动程序或sql客户端无法初始化时，开发人员应如何恢复？
> 
> 在这两种情况下，都提供了无效的输入。
I do not mean to offend。
Mybe it's better to panic in caller when error returned from Init like: https://github.com/helm/helm/blob/main/cmd/helm/helm.go#L73 

Mybe it should be designed as `MustInit` without error returns。

Current `Init` Misleading people by the error returns: if any  server application using `Init` and only judge returned error it may cause the service to exit abnormally.
