### ISSUE TITLE
Chaging env order causes entries to disappear

### ISSUE THREAD

**Issue by dpp23** [helm/helm#9709]
I've noticed a weird bug when upgrading a chart and particularly a deployment inside it - the change was to move a envvar from the end of the list to the second element. The end result is that the envvar disappeared completely. `helm get all ...` had it inside the deployment config, but when checked with `kubectl describe deployment` it wasn't there. I've tried to reproduce with a small example to share, but to no avail. 

Output of `helm version`:
`version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AWS EKS 1.18

**Comment by bacongobbler** [comment]
Marking as a support issue until a reproducible test case is presented
