### ISSUE TITLE
helm template option "--show-only" and "--output-dir" together throws Error: could not find template

### ISSUE THREAD

**Issue by zensolution** [helm/helm#9722]
if I set "--show-only" and "--output-dir" altogether, "helm template" throws error. 

The command is as below,
    helm template vault  -s templates/server-ingress.yaml --output-dir=t

The output is like below, 

  wrote t/vault/templates/ui-service.yaml
  wrote t/vault/templates/server-statefulset.yaml
  wrote t/vault/templates/server-ingress.yaml
  Error: could not find template templates/server-ingress.yaml in chart

**Comment by bacongobbler** [comment]
Hi @zensolution. Please provide a sample chart to help reproduce the issue. Thanks.

**Comment by zensolution** [comment]
@bacongobbler I have digged into the code and find the logic is a little confusing. 

If outputDir has been defined (https://github.com/helm/helm/blob/main/pkg/action/action.go#L186), helm will not return Manifest to display. Then, the error was thrown at https://github.com/helm/helm/blob/main/cmd/helm/template.go#L160.

Looks to me the current logic is that "--outputDir" tell helm to send result to specified folder and don't print it out, while "--show-only" expects some output in the screen.

In my opinion, if both show-only and output-dir are defined, helm should send only specified template to output folder.

**Comment by joejulian** [comment]
Can duplicate this result:
```
$ helm template test --repo https://helm-hello-world.github.io/charts helloworld -s templates/service.yaml --output-dir /tmp/foo
wrote /tmp/foo/helloworld/templates/service.yaml
wrote /tmp/foo/helloworld/templates/deployment.yaml
Error: could not find template templates/service.yaml in chart
```
I also agree that the behavior described is what I would expect as well.

**Comment by StianOvrevage** [comment]
Can confirm that this is still a problem in version 3.17.2
