### ISSUE TITLE
 customJenkinsLabels is not working for me in helm chart version 3.2.1

### ISSUE THREAD

**Issue by KamatR** [helm/helm#9724]
Output of `helm version`: 
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

Hi,

I am adding the helm chart repo using below command  with the chart version 3.2.1
helm repo add jenkinsci https://charts.jenkins.io

I have added the  below configuration for master jenkins node.
 customJenkinsLabels: dynamic 
but this is not getting reflected in my jenkins web page.

once I have added a below configuration in _helpers.tpl , the information started to get reflected in the jenkins web page.
labelString: "{{ .Values.controller.customJenkinsLabels }}"

why is customJenkinsLabels is not working in my case without my workaround ?? If the workaround is correct could you add this   as a fix in next chart version ??

**Comment by bacongobbler** [comment]
Please file issues related to the jenkins chart with the jenkins cahrt maintainers.

**Comment by KamatR** [comment]
Hi,

Is this where I need to raise a issue ? If not could you please redirect me to the right link.
https://github.com/jenkinsci/helm-charts
