### ISSUE TITLE
Ordering of objects isn't documented

### ISSUE THREAD

**Issue by AssafKatz3** [helm/helm#9726]
Hi,

I cannot find documentation of ordering of objects before applying them. After some searches, I found [answer in stackoverflow](https://stackoverflow.com/a/51962615), but I think that this should be documented, I suggest to add at [template files](https://helm.sh/docs/topics/charts/#template-files) something similar to that answer.

Thanks

**Comment by bacongobbler** [comment]
https://github.com/helm/helm/blob/main/pkg/releaseutil/kind_sorter.go#L31

**Comment by AssafKatz3** [comment]
> https://github.com/helm/helm/blob/main/pkg/releaseutil/kind_sorter.go#L31

Hi,

It isn't accessible by end users :-(

Thanks

**Comment by bacongobbler** [comment]
I’m aware of that - I’m just pointing at the current location where this install order is defined.

Please feel free to write this up in the documentation somewhere!
