### ISSUE TITLE
Charts made with helm create don't follow best practices

### ISSUE THREAD

**Issue by scottashipp** [helm/helm#9729]
A spirited debate happened on our team just now due to inconsistencies between the helm docs and the chart that is created when `helm create...` is used.

The crux of the inconsistency is as follows:

In the created chart, values like `ingress.enabled` are used to then conditionally enable the resource in question.

The [best practices](https://helm.sh/docs/chart_best_practices/values/#flat-or-nested-values) section for values includes a section recommended against nested values like this.

**Comment by bacongobbler** [comment]
I think the very same document you linked to provides an explanation for this:

> When there are a large number of related variables, and at least one of them is non-optional, nested values may be used to improve readability

The alternative to `ingress.enabled` would be something like `ingressEnabled`, `ingressHosts`, `ingressClassName`, etc. All of which clearly does not follow best practices as it does not improve readablity. Since `ingress.enabled` is a non-optional flag, it is fine to nest the rest of the functionality under the `ingress` subfield.

Hope this clarifies things.

**Comment by mattfarina** [comment]
I think this is worth a conversation on. This best practice is from long ago and may have changed.

**Comment by rabidscorpio** [comment]
@mattfarina Agreed, I personally feel that nesting values that are related, regardless of whether or not they're optional, makes the values file far more readable than

**Comment by scottashipp** [comment]
@bacongobbler Yeah, that does make sense. I think it's a little subtle for most people. But I could spread this knowledge on my team like "If you see nested values it indicates that a) they are related and b) at least one of them is non-optional"

And I agree with the others, I personally like the nested values in many cases. Maybe the best practice could be worded less strongly, but maybe not. The doc is pretty fair already since it says things like "generally" and "in most cases" to my recollection.

I'm okay with either course. If you'd like to close this issue that is fine. If people think an update is warranted, also fine.
