### ISSUE TITLE
revision rendered in deployment and actual revision do not march

### ISSUE THREAD

**Issue by bigpeng93** [helm/helm#9730]
I uninstall a release and keep history , then install the release. I find the revision rendered in deployment is 1, but revision listed by `helm list` is history revision + 1.
The code in https://github.com/helm/helm/blob/main/pkg/action/install.go#L318 replace actual revision after rendering revision in resource of kubernetes https://github.com/helm/helm/blob/main/pkg/action/install.go#L237

**Comment by mattfarina** [comment]
This is happening because a Revision of 1 is set, the templates are rendered, then the code works out if this is picking up an existing release history.
