### ISSUE TITLE
`helm render` with `--repo` fails to find `Chart.yaml` with a values file in subdirectory with the same name as the chart

### ISSUE THREAD

**Issue by stpierre** [helm/helm#9731]
Output of `helm version`: `version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}`

Output of `kubectl version`: `Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): EKS

Y'all, this is a really bizarre one.

`helm render` fails when you use `--repo`, *and* provide a values file that is in a subdirectory with the same name as the chart name (not release name), that is exactly one layer deeper than the current directory. Consider a directory tree:

```
% tree helm-bug 
helm-bug
└── cert-manager
    └── values.yaml

1 directory, 1 file
```

`values.yaml` is empty here; its content doesn't matter.

This works fine:

```
helm template cert-manager cert-manager --repo https://charts.jetstack.io -f helm-bug/cert-manager/values.yaml
```

If I change directory into `helm-bug/cert-manager/`, this works fine:

```
helm template cert-manager cert-manager --repo https://charts.jetstack.io -f values.yaml
```

If I change directory into `helm-bug/`, this works fine:

```
helm repo add jetstack https://charts.jetstack.io
helm repo update
helm template cert-manager jetstack/cert-manager -f cert-manager/values.yaml
```

However, if I change directory into `helm-bug/`, *none* of the following work:

```
helm template cert-manager cert-manager --repo https://charts.jetstack.io -f cert-manager/values.yaml
helm template cert-manager cert-manager --repo https://charts.jetstack.io -f ./cert-manager/values.yaml
helm template cert-manager cert-manager --repo https://charts.jetstack.io -f "$(readlink -f cert-manager/values.yaml)"
```

Moreover, if I rename the `cert-manager` directory to `certmanager`, it works fine. Similarly, if I omit the values file, this works fine:

```
helm template cert-manager cert-manager --repo https://charts.jetstack.io
```

So something about passing that values file in makes helm look for the chart locally instead of in the repo that I've told it to use.

Debug output is pretty terse:

```
% helm --debug template cert-manager cert-manager --repo https://charts.jetstack.io -f cert-manager/values.yaml
install.go:173: [debug] Original chart version: ""
install.go:190: [debug] CHART PATH: /home/stpierre/helm-bug/cert-manager

Error: Chart.yaml file is missing
helm.go:81: [debug] Chart.yaml file is missing
helm.sh/helm/v3/pkg/chart/loader.LoadFiles
        /home/circleci/helm.sh/helm/pkg/chart/loader/load.go:158
helm.sh/helm/v3/pkg/chart/loader.LoadDir
        /home/circleci/helm.sh/helm/pkg/chart/loader/directory.go:119
helm.sh/helm/v3/pkg/chart/loader.DirLoader.Load
        /home/circleci/helm.sh/helm/pkg/chart/loader/directory.go:41
helm.sh/helm/v3/pkg/chart/loader.Load
        /home/circleci/helm.sh/helm/pkg/chart/loader/load.go:62
main.runInstall
        /home/circleci/helm.sh/helm/cmd/helm/install.go:199
main.newTemplateCmd.func2
        /home/circleci/helm.sh/helm/cmd/helm/template.go:73
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:80
runtime.main
        /usr/local/go/src/runtime/proc.go:204
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1374
```

That seems to indicate that it's looking for the `Chart.yaml` in the same directory as `values.yaml` instead of in the remote chart.

There are workarounds available, but the command I've given is run by `skaffold` so unfortunately the least disruptive one -- adding the repo and templating the chart from there -- isn't an option.

**Comment by stpierre** [comment]
Okay, looks like I was wrong and screwed something up while trying to test this; you do *not* have to pass in a values file to trigger this. If a subdirectory with the same name as the chart exists, that's sufficient to trigger this bug. So it's not as complicated as I originally thought, but that also means that it's more annoying to work around.

**Comment by andreaskaris** [comment]
Another easy reproducer:
~~~
$ helm repo add "stable" "https://charts.helm.sh/stable" --force-update
$ helm template nginx stable/nginx-ingress | tail -n 2
WARNING: This chart is deprecated
      serviceAccountName: nginx-nginx-ingress-backend
      terminationGracePeriodSeconds: 60
$ mkdir stable
$ helm template nginx stable/nginx-ingress | tail -n 2
WARNING: This chart is deprecated
      serviceAccountName: nginx-nginx-ingress-backend
      terminationGracePeriodSeconds: 60
$ mkdir nginx-ingress
$ helm template nginx stable/nginx-ingress | tail -n 2
WARNING: This chart is deprecated
      serviceAccountName: nginx-nginx-ingress-backend
      terminationGracePeriodSeconds: 60
$ mkdir stable/nginx-ingress
$ helm template nginx stable/nginx-ingress | tail -n 2
Error: Chart.yaml file is missing
~~~

**Comment by andreaskaris** [comment]
The problem is that  `stable/nginx-ingress` is mistaken for a relative path.

cmd/helm/install.go
~~~
185         cp, err := client.ChartPathOptions.LocateChart(chart, settings)
186         if err != nil {
187                 return nil, err
188         }
189 
190         debug("CHART PATH: %s\n", cp)
~~~

See here:
~~~
622 // LocateChart looks for a chart directory in known places, and returns either the full path or an error.
623 //
624 // This does not ensure that the chart is well-formed; only that the requested filename exists.
625 //
626 // Order of resolution:
627 // - relative to current working directory
628 // - if path is absolute or begins with '.', error out here
629 // - URL
630 //
631 // If 'verify' was set on ChartPathOptions, this will attempt to also verify the chart.
632 func (c *ChartPathOptions) LocateChart(name string, settings *cli.EnvSettings) (string, error) {
636         if _, err := os.Stat(name); err == nil {
637                 abs, err := filepath.Abs(name)
638                 if err != nil {
639                         return abs, err
640                 }
641                 if c.Verify {
642                         if _, err := downloader.VerifyChart(abs, c.Keyring); err != nil {
643                                 return "", err
644                         }
645                 }
646                 return abs, nil
647         }
(...)
~~~

So this may work as designed, I'll let the repository / project owners comment on that.

**Comment by mattfarina** [comment]
Thanks for all the work here.

First, Helm handling `path/to/chart` and `./path/to/chart` the same for relative paths is intentional. It's not just Helm but the handling built into the Go standard library. Many applications are this way in Go and in other languages. It is fairly common to handle them the same.

A bug I see is that `path/to/chart` and `./path/to/chart` should have the same error message. That is why I marked it as a bug.

This is mostly a works as designed situation with what I would call a small bug being discovered.

**Comment by stpierre** [comment]
The bug to me feels like the user explicitly specifying a repository to use, but that being ignored. Is there a use case for providing `--repo`, but using the local path instead?

**Comment by mattfarina** [comment]
You can have a repo on local disk and reference that. When I am testing I regularly do this.

**Comment by stpierre** [comment]
I'm not sure why you'd need the repo in that case. If you tell it to use your local repo, but there's a matching local directory, it will always ignore your `--repo` flag and look in the current directory first.

So: What's the use case for specifying `--repo` when you know or expect that it will be ignored? Could we at least emit a warning when the user has signaled their explicit intention to use a repo that isn't the current working directory, but helm ignores their intentions and uses the current working directory instead? It's an awful UX, and the least we could do is alert the user that helm is ignoring their explicit request.

**Comment by andreaskaris** [comment]
Hi,

So something like that?

~~~
$ bin/helm template cert-manager cert-manager --repo https://charts.jetstack.io -f values.yaml
WARNING: Chart found at local path '/home/akaris/development/helm/cert-manager'. Ignoring Repository URL 'https://charts.jetstack.io.'
Error: open values.yaml: no such file or directory
~~~

- Andreas

**Comment by stpierre** [comment]
Not as good as a fix IMO, but *definitely* an improvement. It would have saved me a bunch of troubleshooting time a couple of days ago for sure. :joy:

**Comment by cndoit18** [comment]
> Thanks for all the work here.
> 
> First, Helm handling `path/to/chart` and `./path/to/chart` the same for relative paths is intentional. It's not just Helm but the handling built into the Go standard library. Many applications are this way in Go and in other languages. It is fairly common to handle them the same.
> 
> A bug I see is that `path/to/chart` and `./path/to/chart` should have the same error message. That is why I marked it as a bug.
> 
> This is mostly a works as designed situation with what I would call a small bug being discovered.

It should be a problem caused by --repo (if you use --repo, you should not check the chart locally).

**Comment by spoletum** [comment]
FYI - I think it should be reopened as I have just encountered the same issue in version 2.11.0

```hcl
provider "registry.terraform.io/hashicorp/helm" {
  version = "2.11.0"
  ...
```
I used the same module folder name as the chart name and it fails to find the `Chart.yaml` file. Renaming the module folder to something different makes it work.

**Comment by lvijnck** [comment]
I also think this should be reopened, experienced it today as well. This should not be intended behaviour.
