### ISSUE TITLE
lookup causes lint to fail

### ISSUE THREAD

**Issue by anapsix** [helm/helm#9733]
It appears `lookup` function is causing `helm lint` to fail (similarly as in #7955).

 - Output of `helm version`: `version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}`
- Output of `kubectl version`:  `Client Version: v1.21.0, Server Version: v1.20.6`
- Cloud Provider/Platform (AKS, GKE, Minikube etc.): self-managed

This is my secret template
```
{{- $secretName := (include "my-chart.fullname" .) -}}
{{- $authMethod := (include "my-chart.authMethod" .) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "my-chart.labels" . | nindent 4 }}
data:
  {{- if .Release.IsInstall }}
  sessionCookieSecret: {{ default (randAlphaNum 32) .Values.myApp.sessionCookieSecret | b64enc }}
  {{- if eq $authMethod "none" }}
  fallbackToken: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
  {{- else }}
  sessionCookieSecret: {{ (lookup "v1" "Secret" .Release.Namespace $secretName).data.sessionCookieSecret }}
  {{- if eq $authMethod "none" }}
  fallbackToken: {{ (lookup "v1" "Secret" .Release.Namespace $secretName).data.fallbackToken }}
  {{- end }}
  {{- end }}
```

Lint returns the following
```
[ERROR] templates/: template: my-chart/templates/secret.yaml:17:67: executing "my-chart/templates/secret.yaml" at <$secretName>: nil pointer evaluating interface {}.sessionCookieSecret
```

Am I missing something here?

**Comment by mattfarina** [comment]
This is a good question.

Linting, like some of the other commands, is designed to run when Helm cannot connect to a cluster. This is done for some security reasons and some practical reasons.

There is a step in linting where templates are rendered to look at the output. When linting `.Release.IsInstall` is set to false. So, it goes to the else. In the else a lookup is performed. The response from that is an empty response as it cannot connect to the cluster. Getting `.data.fallbackToken` on that is the response is where the error happens. What if the fallback is not present? That situation isn't accounted for.

Helm is a package manager and this is mixing a bit of deployment logic in with package management. We usually recommend that live in a layer about Helm. Like the way Ansible sits above debian/apt packages.

Does that help explain what's going on?

**Comment by anapsix** [comment]
Thanks for the explanation @mattfarina, that makes perfect sense.
The part of Matt's comment (in the linked issue) that I've apparently missed is the 
> In both cases, the correct behavior is for lookup to return an empty dictionary regardless of what the input is. This follows the established pattern of other cluster-sensitive templating directives.

What I'm struggling with, is figuring out how to code it in a way to retain the logic.. so far I've come up with this
```
{{- $secretName := (include "my-chart.fullname" .) -}}
{{- $authMethod := (include "my-chart.authMethod" .) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "my-chart.labels" . | nindent 4 }}
data:
  {{- if .Release.IsInstall }}
  sessionCookieSecret: {{ default (randAlphaNum 32) .Values.myApp.sessionCookieSecret | b64enc }}
  {{- if eq $authMethod "none" }}
  fallbackToken: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
  {{- else }}
  sessionCookieSecret: {{ ((lookup "v1" "Secret" .Release.Namespace $secretName).data).sessionCookieSecret }}
  {{- if eq $authMethod "none" }}
  fallbackToken: {{ ((lookup "v1" "Secret" .Release.Namespace $secretName).data).fallbackToken }}
  {{- end }}
  {{- end }}
  ```
  But honestly I don't understand why this passes `helm list`

**Comment by mattfarina** [comment]
I'm not sure why it passes linting. But, I don't know what's in the `values.yaml` file. What is the value of `$authMethod`?

**Comment by anapsix** [comment]
It's pretty straight forward..

Here is a definition of `my-chart.authMethod` named template
```
{{- define "my-chart.authMethod" -}}
{{- if or (eq .Values.myApp.auth "none") (eq .Values.myApp.auth "userpass") (eq .Values.myApp.auth "ldap") }}
{{- default "none" .Values.myApp.auth }}
{{- else }}
{{- fail "myApp.auth must be one of: none, userpass, or ldap" }}
{{- end }}
{{- end }}
```

and `values.yaml` contains something like this
```yaml
myApp:
  auth: none # can be one of "none", "userpass" or "ldap"
  sessionCookieSecret: ~ # if null, will be generated
```

**Comment by bacongobbler** [comment]
Have you tried using the `if` pattern? i.e.

```
{{ if lookup "v1" "Secret" .Release.Namespace $secretName }}
{{ .data.sessionCookieSecret | base64env }}
{{ else }}
{{/* need to handle no Secret present, or a lookup failure */}}
{{ end }}
```

In a dry-run scenario, no Secret is present so a `null` value is returned. `if` will capture falsy values so it can be used to filter between a successful `lookup` and a failed one.

`helm lint` may be passing because the result is still valid YAML, which is all `helm lint` really looks for. As @mattfarina mentioed earlier, `helm lint` does no server-side validation compared to `helm install --dry-run` or `helm template --validate` so it can't catch things like an invalid Kubernetes resource template according to the [reference spec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/).

**Comment by anapsix** [comment]
Looking more at your recommendation, @bacongobbler , I see it's best to implement it. This way nothing unexpected happens. Also added a couple of extra secret keys for easier debugging.
Thank Matts!

```
{{- $secretName := (include "my-chart.fullname" .) -}}
{{- $authMethod := (include "my-chart.authMethod" .) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "my-chart.labels" . | nindent 4 }}
data:
  {{- if .Release.IsInstall }}
  releaseIsInstall: {{ b64enc "true" }}
  sessionCookieSecret: {{ default (randAlphaNum 32) .Values.myApp.sessionCookieSecret | b64enc }}
  {{- if eq $authMethod "none" }}
  fallbackToken: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
  {{- else }}
  releaseIsInstall: {{ b64enc "false" }}
  {{- with lookup "v1" "Secret" .Release.Namespace $secretName }}
  sessionCookieSecret: {{ b64enc .data.sessionCookieSecret }}
  sessionCookieSecretLookupSucceeded: {{ b64enc "true" }}
  {{- else }}
  sessionCookieSecret: {{ default (randAlphaNum 32) .Values.myApp.sessionCookieSecret | b64enc }}
  sessionCookieSecretLookupSucceeded: {{ b64enc "false" }}
  {{- end }}
  {{- if eq $authMethod "none" }}
  {{- with lookup "v1" "Secret" .Release.Namespace $secretName }}
  fallbackToken: {{ b64enc .data.fallbackToken }}
  fallbackTokenLookupSucceeded: {{ b64enc "true" }}
  {{- else }}
  fallbackToken: {{ randAlphaNum 32 | b64enc }}
  fallbackTokenLookupSucceeded: {{ b64enc "false" }}
  {{- end }}
  {{- end }}
  {{- end }}
```

I suppose the question about why wrapping lookup into parentheses make lint pass can remain a mystery..

Btw, how does one refer to a multitude of Matts? 🤔 Matterhorn of Matts?
