### ISSUE TITLE
[Question]  How can I judge platform (openshift or k8s etc.) before helm install?

### ISSUE THREAD

**Issue by gxglls** [helm/helm#9742]
My charts need to be correctly installed on two platforms at the same time: openshift and k8s. If the platform is openshift, a separate Security Context (apiVersion: security.openshift.io/v1) resource needs to be deployed to ensure that the application runs correctly. If the platform is k8s, it is not. I want to automate this judgment process. I try to use `Capabilities.APIVersions.Has apiVersion: security.openshift.io/v1` to judge whether the platform is openshift and it does not take effect. The output of Capabilities.APIVersions does not contain any openshift APIs. Is there any other way to determine the platform type through helm? Thank you

**Comment by mattfarina** [comment]
When you use the `.Capabilities.APIVersions.Has` function are you using it with `helm install` or `helm template`? `helm template` is meant for offline use. `helm install` will inspect the cluster it is communicating with to get the available resource. If you did that `.Capabilities.APIVersions.Has "security.openshift.io/v1"` would return true if the cluster listed that as being available.

Could you provide more detail about how you encountered the situation and which version of Helm you are using.

**Comment by gxglls** [comment]
@mattfarina thanks a lot! In my case I using `helm template` and check output it not expected. Now I try to use `helm install` it work well.  I think this detail should be reflected in the Helm built-in object document  https://helm.sh/docs/chart_template_guide/builtin_objects/
