### ISSUE TITLE
Checksum error in new helm version 3.6.0

### ISSUE THREAD

**Issue by trombini77** [helm/helm#9745]
Output of `helm version`:

Run curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
Helm v3.6.0 is available. Changing from version v3.5.4.
Downloading https://get.helm.sh/helm-v3.6.0-linux-amd64.tar.gz
Verifying checksum... SHA sum of /tmp/helm-installer-BReH1v/helm-v3.6.0-linux-amd64.tar.gz does not match. Aborting.
Failed to install helm
	For support, go to https://github.com/helm/helm.
Error: Process completed with exit code 1.

Output of `kubectl version`:
None

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
None

PS. Output from Github Actions

**Comment by bacongobbler** [comment]
Might've been a flake. Seems to be working for me.

```
><> ./get_helm.sh
Helm v3.6.0 is available. Changing from version v3.5.4.
Downloading https://get.helm.sh/helm-v3.6.0-linux-amd64.tar.gz
Verifying checksum... Done.
Preparing to install helm into /usr/local/bin
...
```

Can you please try again?

**Comment by trombini77** [comment]
Seems to be a pontual error. I did again without issue.
Thanks.
