### ISSUE TITLE
Resource created by `helm rollback` doesn't have `meta.helm.sh` annotations.

### ISSUE THREAD

**Issue by pangorgo** [helm/helm#9747]
Output of `helm version`: 3.3.4

Output of `kubectl version`: v1.19.9

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS EKS 

Resource created by `helm rollback` doesn't have `meta.helm.sh` annotations.

It seems `setMetadataVisitor` is executed by `upgrade` and `install` but not by `rollback`. Because of that resource created by `rollback` is not annotated and can't be "adopted" by helm if needed.

**Comment by bacongobbler** [comment]
Good catch. Thanks for finding this. Do you have a patch available to test?

**Comment by pangorgo** [comment]
I see @cndoit18 have already prepared PR. Thanks 🙇 . I hope it's going to be approved and merged 🤞

**Comment by needleshaped** [comment]
Hitting same problem in CI/CD (which does `--dry-run` before actual `upgrade --install` ).
Leaving and error here so the issue can be found easier.

```
Error: rendered manifests contain a resource that already exists. Unable to continue with install: Ingress "ingress-name" in namespace "namespace-name" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "ingress-name"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "namespace-name"
```
