### ISSUE TITLE
Extend kube/fake/client

### ISSUE THREAD

**Issue by cndoit18** [helm/helm#9752]
The current fakeKubeClient is not sufficient to support more operations.

https://github.com/helm/helm/blob/db4d20f3ad3ebbd8d17926e7a3cc7da7c177b52b/pkg/kube/fake/printer.go#L89-L92

It can be considered as a dependency of #9751

**Comment by bacongobbler** [comment]
As this would be a change in a public structure's behaviour, this could be considered a breaking change for third-party libraries utilizing the fake kube client.

As a result, any proposed changes would have to be slated for Helm 4, and would have to go through the [HIP process](https://github.com/helm/helm/blob/main/CONTRIBUTING.md#proposing-an-idea).

**Comment by cndoit18** [comment]
> As this would be a change in a public structure's behaviour, this could be considered a breaking change for third-party libraries utilizing the fake kube client.
> 
> As a result, any proposed changes would have to be slated for Helm 4, and would have to go through the [HIP process](https://github.com/helm/helm/blob/main/CONTRIBUTING.md#proposing-an-idea).

thank you. I agree, this seems like a very large project
