### ISSUE TITLE
[question] could I write a helm plugin that could read from terraform State files?

### ISSUE THREAD

**Issue by red8888** [helm/helm#9755]
I haven't written a helm plugin before so I don't know what you can do with them. Wanted to ask about my use case first before I go down the road of working on it.

Essentially all I want is to be able to create a custom function that can read a value from my terraform State files.

I would use it like this:
`value: {{ terraform-state 'packet_device.worker[0]'  }}`

So pretty much like terraform state show command

Helm is also written in golang so I was hoping I wouldn't need to Shell out with this custom plugin. I could just import some terraform libraries and use the actual method that the terraform executable is using to read state.

Can you do this with a custom helm plugin? Create your own function like I want to?

**Comment by bacongobbler** [comment]
Hi @red8888. Injecting custom functions into the template language is not something that the plugin system can handle at this time. more information on what is supported can be found in the [Plugins Guide](https://helm.sh/docs/topics/plugins/).

Hope this helps.
