### ISSUE TITLE
Invoking helm from electron-based app fails on MacOS

### ISSUE THREAD

**Issue by rpatrick00** [helm/helm#9759]
Output of `helm version`: 

`version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}`

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"8ff64bd4edf690c75fcf172eeaaad21b929f3cbf", GitTreeState:"clean", BuildDate:"2021-03-15T07:51:22Z", GoVersion:"go1.15.5 BoringCrypto", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): OKE

We are building a desktop application using Electron.  When we run the application is development mode, it is able to invoke helm to install our package.  However, when running it from the installer on MacOS (where the environment variables are not inherited from the user), I am getting the following error.  What do I need to do to redirect where helm is trying to create this directory?

```
Command failed: /usr/local/bin/helm repo add weblogic-operator https://oracle.github.io/weblogic-kubernetes-operator/charts/ --force-update
Error: mkdir Library/Preferences/helm: permission denied
 ```

**Comment by bacongobbler** [comment]
https://helm.sh/docs/faq/changes_since_helm2/#xdg-base-directory-support

`helm env` should provide you with the environment variables available to Helm's environment. From there you can change things such as where Helm stores its configuration.

**Comment by rpatrick00** [comment]
Thanks.  I simply needed to pass the appropriate environment variables down to the child process and that resolved my problem.
