### ISSUE TITLE
Feature request: dynamically handle api endpoints from k8s server version spec

### ISSUE THREAD

**Issue by danielhoherd** [helm/helm#9765]
## Description of problem

Maintaining charts with valid API versions for all kubernetes versions is difficult. [The documentation on this topic is quite short](https://helm.sh/docs/topics/kubernetes_apis/#chart-maintainers), and implies that maintainers need to do all of this work manually.

To help out, there is a project called [kubepug](https://github.com/rikatz/kubepug) that downloads the [swagger.json](https://raw.githubusercontent.com/kubernetes/kubernetes/v1.17.0/api/openapi-spec/swagger.json) for a given k8s version and reports problems about endpoints that has been deprecated or removed from the spec.

## Proposed feature improvement

It would be awesome if helm provided the reciprocal of kubepug: the ability to insert the default api endopint for the server version without having to template out `.Capabilities.KubeVersion.Version` semver comparison blocks.

For example, instead of having:

```
# templates/_apivers.tpl
{{- define "apiVersion.Ingress" -}}
{{- if semverCompare "^1.14-0" .Capabilities.KubeVersion.Version -}}
networking.k8s.io/v1beta1
{{- else -}}
extensions/v1beta1
{{- end -}}
{{- end -}}
```
```yaml
kind: Ingress
apiVersion: {{ template "apiVersion.Ingress" . }}
```

We could have something like:

```yaml
kind: Ingress
apiVersion: {{ template ".builtins.Ingress" . }}
```

Where `builtins` would dynamically handle inserting the relevant API endpoint for the server version that the template is being generated for. (This suggestion is just a pseudo-code idea, the implementation details are wide open for discussion.)

**Comment by bacongobbler** [comment]
This sounds like a good candidate for a [library chart](https://helm.sh/docs/topics/library_charts/).
