### ISSUE TITLE
Pass dictionary values through --set 

### ISSUE THREAD

**Issue by arjaiswa** [helm/helm#9768]
Values Yaml:

config:
  entries: {}

I want to set entries values in --set So it will come in Yaml as below :
config:
 entries:
    key1:value1
    key2:value2

Helm upgrade --install chart/ --set config.entries={key1:value1,key2:value2}

Output of Helm :
got "array", expected "map"

**Comment by bacongobbler** [comment]
https://helm.sh/docs/intro/using_helm/#the-format-and-limitations-of---set

> Multiple values are separated by , characters. So --set a=b,c=d becomes:

>     a: b
>     c: d


In your case, use `--set config.entries.key1=value1,config.entries.key2=value2`.
