### ISSUE TITLE
Accessing a helm chart repo running on a port other than 80

### ISSUE THREAD

**Issue by mrda** [helm/helm#9780]
Output of `helm version`:
version.BuildInfo{Version:"v3.5.0+6.el8", GitCommit:"77fb4bd2415712e8bfebe943389c404893ad53ce", GitTreeState:"clean", GoVersion:"go1.14.12"}

I'm seeing some unexpected behaviour when trying to access a helm chart repository running on a port other than 80.  It appears that this capability is almost all there, but isn't complete. (For what it's worth, I've tried this on x86_64, ppc64le and s390x and the behaviour is the same)

$ helm repo add local-repo http://0.0.0.0:8000
"local-repo" has been added to your repositories

$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "local-repo" chart repository
Update Complete. ⎈Happy Helming!⎈

$ helm repo list
NAME      	URL
local-repo	http://0.0.0.0:8000

$ helm pull local-repo/moo-chop
Error: Get "http://0.0.0.0/moo-chop-0.1.0.tgz": dial tcp 0.0.0.0:80: connect: connection refused

Note the port number here.  It's trying 80 instead of 8000

$ helm pull http://0.0.0.0:8000/moo-chop-0.1.0.tgz
$ ls -1 moo-chop-0.1.0.tgz
moo-chop-0.1.0.tgz

As you can see, it's possible to add a repository running on a high port (in this case, we're running `python3 -m http.server`), but when we try and do a `pull` (or a `show`) it seems to be ignoring the port number and defaulting back to port 80.

Is this a bug? (i.e. it should honour the port number specified in the repo list?) or is this a use case that isn't supported? (i.e. some input checking should be done on `repo add` to disallow specifying a port number?)

**Comment by mattfarina** [comment]
I just tried to reproduce this on the latest helm v3.6.0 and was not able to. I see you are using a version that's a commit that's not part of the Helm source tree.

Could you try reproducing on the latest Helm release?

**Comment by mrda** [comment]
Thanks @mattfarina on further investigation this issue occurred because on an incorrectly generated helm repo index file.  There's no issue.  Thanks for investigating.
