### ISSUE TITLE
helm repo upadte error when chart appVersion is a quoted scientific number

### ISSUE THREAD

**Issue by rootdeep** [helm/helm#9781]
When running command helm repo update, an error occurs , the output as follows:

Unable to get an update from the "market-test" chart repository (http://${ip:port}/chartrepo/opensource-stable):
        
error unmarshaling JSON: while decoding JSON: json: cannot unmarshal number into Go struct field ChartVersion.entries.appVersion of type string

I found this issue is induced by a chart uploaded before, because the appVersion in chart.yalm is a quoted scientific value.

the content of Chart.yaml is :
```
apiVersion: v2
appVersion: "1826e29"
description: A Helm chart for Kubernetes
name: admin
type: application
version: 0.1.0
```

I want the appVersion to be 1826e29,  if it's not qouted,  helm push will change the value to 1.826e+32.

Is there a way to keep the wanted version, and no errors ?

Output of `helm version`:

version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:31:31Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:23:21Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by mattfarina** [comment]
This issue has to do with YAML. The YAML spec covers floating point numbers using scientific notation.

```yaml
appVersion: 1826e29
```

The above example should be converted to a number. This is proper YAML. The below example should be a string...

```yaml
appVersion: "1826e29"
```

If you are not seeing this than an issue needs to be filed against the YAML parser. Helm uses the same one Kubernetes does. It is maintained by the Kubernetes project.

**Comment by rootdeep** [comment]
@mattfarina  , As you said , appVersion: "1826e29"  should be a string , however, the error  " cannot unmarshal number into Go struct field ChartVersion.entries.appVersion of type string"   hints the yaml parser view it as a number. 

Is the version of yaml used by helm 3.6 still older ? 
there is a similar case and solution  at https://github.com/helm/chartmuseum/issues/290

**Comment by mattfarina** [comment]
The version of yaml used by Helm is from the k8s project and the latest version they have released.

Are you seeing the issue with `helm chart push`?

**Comment by rootdeep** [comment]
Firstly , the issue in  helm/chartmuseum#290  happened with  helm repo add  
Secondly,  do you read  codes and locate where this error occurs?  
helm repo update : https://github.com/helm/helm/blob/v3.6.0/cmd/helm/repo_update.go#L98
helm repo add:  https://github.com/helm/helm/blob/v3.6.0/cmd/helm/repo_add.go#L183

Both errors throws by the same function   DownloadIndexFile() at 
 https://github.com/helm/helm/blob/v3.6.0/pkg/repo/chartrepo.go#L117

**Comment by mattfarina** [comment]
The metadata from the `Chart.yaml` is also in the `index.yaml` file. In the `index.yaml` file is the `appVersion` quoted for those with a scientific number? If not, I'd like to know what version of Helm produced the `index.yaml` file.

**Comment by rootdeep** [comment]
Yeah, thank you for giving me an clue. I tried locally with helm repo index (helm v3.6) , the  ```appVersion```   in  index yaml is quoted, this is we expected, then I checked the index.yaml in real chart repo  ,it's not quoted.  I will inspect the  chart repo server proplem.
