### ISSUE TITLE
Helm not respecting .netrc

### ISSUE THREAD

**Issue by thernstig** [helm/helm#9783]
I am adding something like this to `.netrc`:
```ini
machine some.url.com login myusername password foofofofoo
```

Using `helm install` like this fails:
```sh
helm install --debug awesome-release https://some.url.com/repo/path/foo-3.55.0-h3c38417.tgz
Error: failed to fetch https://some.url.com/repo/path/foo-3.55.0-h3c38417.tgzz : 401 Unauthorized
```

This works:
```sh
helm install --debug --username myusername --password foofofofoo awesome-release https://some.url.com/repo/path/foo-3.55.0-h3c38417.tgz
```

Is helm not respecting `.netrc` in some way? Note I am using `.netrc` for other things where it authentications fine.

Output of `helm version`:
version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:52:24Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"ec2760d6d916781de466541a6babb4309766c995", GitTreeState:"clean", BuildDate:"2021-02-27T17:18:03Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):
n/a

**Comment by mattfarina** [comment]
Helm does not follow `.netrc` files. We only recently had a request to support it. The feature request is at #9586. We would be happy to accept a pull request to support the feature.

**Comment by thernstig** [comment]
I searched but did not see that issue... no idea why. But this is a clone then, so closing. Thanks @mattfarina
