### ISSUE TITLE
helm template: show-only does not show files in crds directory

### ISSUE THREAD

**Issue by avorima** [helm/helm#9785]
A helm chart provides an easy way to fetch CRDs in a specific version. I want to install CRDs from a helm chart without applying the rest of the manifests. Currently there are at least 3 workflows which I use to do this:
- Pull CRDs from github and apply them with `kubectl`
- Render the full chart, extract the CRDs and then apply them
- Use a chart that has CRDs in the `templates/` directory, in which case `--show-only` works, and apply them directly

I'd like to be able to use `--show-only` with files in the `crds/` directory.

An example:
```
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update
helm template kube-prometheus-stack prometheus-community/kube-prometheus-stack --include-crds -s crds/*
```

Output of `helm version`:

`version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}`

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by mattfarina** [comment]
Might I suggest that this could go on the `helm show` command. Imagine `helm show crds foo-0.1.0.tgz` as a command. This would pipe out the CRDs.
