### ISSUE TITLE
How to define a value once and use it in all subcharts

### ISSUE THREAD

**Issue by 27149chen** [helm/helm#9787]
I have several subcharts (third party) which need the same value (for example "storageClass"), how to define a value in parent chart and apply it to all subcharts? Looks like a reusable variable or something similiar.

**Comment by mattfarina** [comment]
Have you looked at globals? They are documented at https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#helm.

**Comment by 27149chen** [comment]
@mattfarina thank for your reply, but globals doesn't work in my case, since I can't add/modify values in subcharts (they are from outside)

**Comment by mattfarina** [comment]
In that case you'll need to set the value multiple times in the `values.yaml` file for each subchart using the method of [overriding the subchart values](https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#overriding-values-from-a-parent-chart).
