### ISSUE TITLE
EnvSettings.namespace

### ISSUE THREAD

**Issue by zhilyaev** [helm/helm#9790]
I wanna make `helm install` programmable parallel. 

```
for i := range releases {
			go func(wg *parallel.WaitGroup) {
				defer wg.Done()
				release.Install()
			}(wg, releases[i])
}
```

Now I need to do something like that. It is very painful for me.

```
_ = os.Setenv("HELM_NAMESPACE", rel.Namespace)
s := helm.New()
append (helms, s)
```

**Can you make EnvSettings.Namespace as public or add new  method?**
```

func (s* EnvSettings) SetNS  (ns string) {
   s.namespace = ns
}
```

**Comment by bacongobbler** [comment]
`pkg/cli` is really meant for building command-line interfaces. It is designed to be used for one-off commands rather than parallel invocations.

[The documentation](https://helm.sh/docs/topics/advanced/#simple-example) describes how you can set up an `action.Configuration` object for each run. For posterity, the code looks like this:

```
func main() {
    settings := cli.New()

    actionConfig := new(action.Configuration)
    // You can pass an empty string instead of settings.Namespace() to list
    // all namespaces
    if err := actionConfig.Init(settings.RESTClientGetter(), settings.Namespace(), os.Getenv("HELM_DRIVER"), log.Printf); err != nil {
        log.Printf("%+v", err)
        os.Exit(1)
    }

    client := action.NewList(actionConfig)
    // Only list deployed
    client.Deployed = true
    results, err := client.Run()
    if err != nil {
        log.Printf("%+v", err)
        os.Exit(1)
    }

    for _, rel := range results {
        log.Printf("%+v", rel)
    }
}
```

However, you can replace `settings` (`pkg/cli`) with your own parameters. For example:

```
actionConfig := new(action.Configuration)
if err := actionConfig.Init(genericclioptions.NewConfigFlags(false), "mynamespace", "secret", log.Printf); err != nil {
    log.Printf("%+v", err)
    os.Exit(1)
}
```

That way yo do not have to interact with `pkg/cli`, and you can construct your own actions based on your requirements.

Hope that helps.

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!

**Comment by zhilyaev** [comment]
@bacongobbler , Can you help me again?) 
Action.Install or Action.Upgrade doesn't install in the chosen namespace. Because helm will use namespace from kube-context if namespace in manifests will empty.


if i have context with default namespace.
And I wanna install my release to "test" namespace. Helm will install my release to default and save history secret to test.

**solution 1:**
override `metadata.namespace` for each manifest file. Because helm chart install in specific namespace. 

```
helm install -n $ns
```

**solution 2:**

Override helm.Namespace with action.Namespace .

--- 
Currently i compelled create helm client for each release and override helm.namespace with  `pflag.FlagSet` . It is so painful for me 😢 

```go
func NewHelm(ns string) (*helm.EnvSettings, error) {
	env := helm.New()
	fs := &pflag.FlagSet{}
	env.AddFlags(fs)
	flag := fs.Lookup("namespace")
	err := flag.Value.Set(ns)
	if err != nil {
		return nil, err
	}

	return env, nil
}

```
