### ISSUE TITLE
schema validation using remote chart and local manifests

### ISSUE THREAD

**Issue by fusionx86** [helm/helm#9792]
helm version: 3.5.4
kubectl version: 1.17.0

Is it possible to use schema validation on local manifests that aren't part of a chart, but are applied to a chart? Let's say I have a local folder structure like this:

app-dir/
├─ values.yaml
├─ values.schema.json

and I use values.yaml for a deployment like:

`helm install some-app -f values.yaml remote-repo/app-chart`

It deploys, but the required values I set via values.schema.json aren't enforced. If I turn app-dir into a chart by adding Chart.yaml with dependencies for remote-repo/app-chart and redeploy from app-dir, it works fine. The obvious problem is that app-dir isn't a helm chart. That makes sense, but is there a way to work around that and use validation in this situation somehow?

**Comment by mattfarina** [comment]
It is not possible to pull in an outside schema.

Helm is a package manager and charts are the packages. Schema files allow the chart maintainer (which is often different from the chart consumer) to have a schema that can be validated.

**Comment by fusionx86** [comment]
Understood. Thanks for clarifying.
