### ISSUE TITLE
[question] how to sync cache with local changes?

### ISSUE THREAD

**Issue by hakuno** [helm/helm#9802]
Hey there!

I download the chart with `helm repo`, `helm fetch` and finally `helm template`.

But... I make changes to the chart before the `helm template`.

I add files to be used in templates by `.Files.Glob` / `.Files.Get`.

But the template can't see the files I added after.

So I guess I need to sync the cache with local changes. Is it?

How can I do that? Please, help me out.

Should I use `helm repo update` for that?

**Comment by hickeyma** [comment]
@hakuno Just trying to understand better your scenario. Did you make the changes to the chart locally? When you run `helm template`, do you run it against the local chart or the chart in the repo?

**Comment by hakuno** [comment]
@hickeyma two scenarios

1. In my local and "standalone" chart, it runs well. No problems.

2. But, when I run it remotely by downloading the chart from repo, add more files and run against the local chart... it happens.

At moment, I had to make some engineering with `--set-file` to access my files under `.Values`.

**Comment by hickeyma** [comment]
@hakuno Would you be able to show the commands you are using that causes you the issue? I am unsure what is causing the issue you are having.

**Comment by hakuno** [comment]
```
helm repo add the-charts gs://the-charts
```
```
helm fetch the-charts/one --untar -d ${OUTPUT_DIR}
```
So I added my files in `$OUTPUT_DIR` (yes, it's outside the `templates` folder). For instance,
```
echo "NAME=SOMEBODY" > $OUTPUT_DIR/one/newfile.txt
```
```
helm template my-chart the-charts/one --output-dir ${OUTPUT_DIR}
```
My template has
```
{{ ($.Files.Glob $source).AsConfig | indent 2 }}
```
Where `$source` is my file.

However, the files aren't found.
