### ISSUE TITLE
Cannot reset values in subcharts in global namespace

### ISSUE THREAD

**Issue by patrikbeno** [helm/helm#9806]
Use case is as follows:
- **app** chart depends on **service** chart, which depends on **utils** chart.
- all values are in shared `global` section/namespace

Observations/Issues:
- defaults propagate properly into subcharts
- overrides propagate properly into subcharts
- reset to null only applies in root global section but not in subcharts

**values.yaml**
```
global:
  aaa: default
```

[OK] Default run:

```
$ helm upgrade --install --dry-run qdh . --debug | grep aaa -B2

USER-SUPPLIED VALUES:
global:
  aaa: default
--
COMPUTED VALUES:
global:
  aaa: default
--
service:
  global:
    aaa: default
--
  utils:
    global:
      aaa: default
--
    global:
      aaa: default
--
    utils:
      global:
        aaa: default
```

[OK] Override `aaa` from command line:

```
$ helm upgrade --install --dry-run qdh . --debug --set global.aaa=override | grep aaa -B2

USER-SUPPLIED VALUES:
global:
  aaa: override
--
COMPUTED VALUES:
global:
  aaa: override
--
service:
  global:
    aaa: override
--
  utils:
    global:
      aaa: override
--
    global:
      aaa: override
--
    utils:
      global:
        aaa: override
```

[ERR] reset value from command line:

```
$ helm upgrade --install --dry-run qdh . --debug --set global.aaa=null | grep aaa -B2

USER-SUPPLIED VALUES:
global:
  aaa: null
--
service:
  global:
    aaa: default
--
  utils:
    global:
      aaa: default
--
    global:
      aaa: default
--
    utils:
      global:
        aaa: default
```

Output of `helm version`:
```
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}
```
Output of `kubectl version`:
```
N/A
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
N/A
```

**Comment by patrikbeno** [comment]
also tried v3.6.0, same results

**Comment by hstamminger** [comment]
This also applies to values in non-global namespace. 
Tried with helm version 3.6.3

**Comment by bacongobbler** [comment]
Have you looked into what may be causing this?

**Comment by patrikbeno** [comment]
Still an issue, and I don't have the knowledge to track down the cause.
