### ISSUE TITLE
Command to aid in generation of JSON schema

### ISSUE THREAD

**Issue by dvdmuckle** [helm/helm#9808]
Helm supports JSON schema to validate values before templating and deploying a Helm release. This works well, but actually creating the JSON schema can be painful. There are a few sites and tools out their to generate JSON schema given some arbitrary YAML, but they're very hit or miss and could be better if they were more aware of the ultimate use case (IE enforcing conformance for Helm charts).

To that end, there is a use case for some kind of JSON schema generator in Helm. Nothing fancy but something to get people started, that can then be finely tuned. I wonder as well if it would make sense to introduce some kind of decorators into the chart templates themselves that can be used to generate the schema.

**Comment by bacongobbler** [comment]
There are a few third-party tools that help with this. Some are listed in the [Related Projects](https://helm.sh/docs/community/related/) section of the docs. [helm-schema-gen](https://github.com/karuppiah7890/helm-schema-gen) is one example.

**Comment by dvdmuckle** [comment]
> There are a few third-party tools that help with this. Some are listed in the [Related Projects](https://helm.sh/docs/community/related/) section of the docs. [helm-schema-gen](https://github.com/karuppiah7890/helm-schema-gen) is one example.

I'll take a look at, however it looks like the plugin is no longer maintained.
