### ISSUE TITLE
Helm Chart.lock hash not same for same chart on diff. repos

### ISSUE THREAD

**Issue by KlavsKlavsen** [helm/helm#9810]
With latest helm version - if I do helm chart save "some upstream chart".. and then push this to my OCI repo (to use for cache as my k8s cluster does not have internet access directly - for security reasons) - then the Chart.lock hash for the SAME package is different.

If you do the same with apt or yum (creating a mirror of packages) - the hashes and gpg signatures are the same - no matter which repo its in.

This means I cannot easily confirm whats in OCI repo (cache) is the same as what upstream has.. 
I would really prefer that the Chart HASH - actually was a HASH of the package you get when you do: helm dep up and it puts a .tgz in your charts/ folder.. That way, I can commit the .lock file to my git repo and trust Helm ensures that no matter which repo it pulls from (OCI or upstream) - it verifes the hash matches whats in .lock file..
Currently I'd have to recalculate all .lock files - if I want them to fetch from a different OCI repo f.ex. :(

**Comment by bacongobbler** [comment]
Please have a look at https://github.com/helm/helm/pull/9782 - `helm chart save` is being removed in favour of `helm package` and `helm push`.

Can you test that PR and provide feedback?

**Comment by bacongobbler** [comment]
ping.

**Comment by KlavsKlavsen** [comment]
@bacongobbler I dl'ed the hip-6 repo from github and build that.
I can do helm registry login and helm package just fine.. but helm push says invalid command?
```
 ./bin/helm push /home/klavs/projects/upstream/helm-hip6-pr/velero-1.0.0.tgz oci://ghcr.io/Obmondo
```

**Comment by KlavsKlavsen** [comment]
and this is was I cloned: https://github.com/bloodorangeio/helm.git (its on branch main)..

**Comment by KlavsKlavsen** [comment]
doh.. switch to hip-6 branch and things work - will continue testing now :)

**Comment by KlavsKlavsen** [comment]
still same problem.
Helm push says:
Digest: sha256:3392d53652e8ed0d4e0efa3d9b8f3d3d640beaf769bd6ffcb68d6c10bf3abdfc
But Chart.lock (from doing helm dep up against upstream url - which is what I packaged) - says this in chart.lock:
digest: sha256:a0201e6c8d5326049c0538a78de3a3962acd3e9ff206d4da4ee0b19109e4a228
generated: "2021-06-23T09:16:39.029195131+02:00"

Which means I can't "just point helm to an OCI repo"..  In my mind this would be FANTASTIC - if one could simply add a "cache-repo" option - and then I didn't have to alter Chart.yaml repository (it could point to upstream) - and helm would try to pull from cache-repo (OCI) first atleast..  

Thats how we're using OCI - as Helm in production does not have public internet access, and we want to protect ourselves against supply chain attacks - so we NEED to have upstream helm charts stored in our own repo - so we control when we update (and can verify with gpg signature/checksum and compare to previous version and verify chart code helm dl's matches whats in git)

**Comment by KlavsKlavsen** [comment]
I tested with hip-6 image "a little while back" - and at that time it did not actually fix this issue.. I'll have to retest as soon as Helm 3.7.0 is out then - to confirm its actually resolved.. Really hoping it is :)
