### ISSUE TITLE
get-helm-3 script is failing with a checksum issue

### ISSUE THREAD

**Issue by gabriel-sada** [helm/helm#9811]
Installing Helm with `get-helm-3` is failing with a checksum issue right now.

## Steps to reproduce
-  `curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3`
- `chmod a+x get_helm.sh`
- `./get_helm.sh`

## Output 

```
Helm v3.6.1 is available. Changing from version v3.5.4.
Downloading https://get.helm.sh/helm-v3.6.1-darwin-amd64.tar.gz
Verifying checksum... SHA sum of /var/folders/fn/ddctnc4s4cn8l_qwcdlb998c0000gp/T/helm-installer-XXXXXX.qNgx8265/helm-v3.6.1-darwin-amd64.tar.gz does not match. Aborting.
Failed to install helm
	For support, go to https://github.com/helm/helm.
```

This shows up in both CircleCI and locally on my own machine.

**Comment by asloan7** [comment]
This was because although the v3.6.1 dir existed, the helm-v3.6.1-darwin-amd64.tar.gz was not in it (yet)

Only these existed in the dir for a while: 
Source code (zip)
Source code (tar.gz)

**Comment by gabriel-sada** [comment]
Looks like it's fixed now. Is there some way to prevent the release from happening before the `tar.gz` is uploaded?

**Comment by bacongobbler** [comment]
Apologies for the slight hiccup - CI caught up with the release and everything should now be available.
