### ISSUE TITLE
get-helm-3 script is failing on "latest"

### ISSUE THREAD

**Issue by asloan7** [helm/helm#9812]
"latest" right now is v3.6.1
Only source code is there
v3.6.1-linux-amd64.tar.gz is not  (yet, but it taking a log time to appear!)

If using "latest", get-helm-3 script should check for  the actual assets - like helm-v3.6.1-linux-amd64.tar.gz in my case

**Comment by nskalski** [comment]
i'll second this, it broke our ansible play, it would be nice to have a full "release" including packaged binaries or like asloan7 said, a check.

**Comment by waterfoul** [comment]
Agreed, It broke our CI for a half hour today as well

**Comment by bacongobbler** [comment]
#9811
