### ISSUE TITLE
Confusing behavior between HELM_PLUGIN and HELM_DATA_HOME

### ISSUE THREAD

**Issue by ahawkins** [helm/helm#9814]
Output of `helm version`: 3.5.2

A recent project required me to run Helm in a container with a persistent volume. My plan was to put `HELM_*_HOME` on the persistent volume and put `HELM_PLUGIN` to a file system in the image. I thought this would allow me create a Docker image with all the plugins preinstalled. Then, anything related to "transient" data like the added repos and their charts would be kept in `HELM_*_HOME` thus on the persistent volume. 

This did not work. `helm plugin install` writes plugins to `HELM_DATA_HOME/plugins`. This is unexpected because:

> $HELM_PLUGINS | set the path to the plugins directory

I assumed that `helm install` would write files to `HELM_PLUGINS`. That is not the case.

I dug around one of the plugins I'm using and found a [reference](https://github.com/jkroepke/helm-secrets/blob/main/plugin.yaml#L7) to `HELM_PLUGIN_DIR`. That led me to the [plugin docs](https://helm.sh/docs/topics/plugins/) which state:

> Plugins are installed using the $ helm plugin install <path|url> command. You can pass in a path to a plugin on your local file system or a url of a remote VCS repo. The helm plugin install command clones or copies the plugin at the path/url given into $HELM_PLUGINS

So my question is: what is the expected behavior here? If `HELM_PLUGINS` is set, then should all plugin installations go into that directory? If so, then why would files be written to `HELM_DATA_HOME`. 

I was able to reproduce this problem using a simple `Dockerfile`:

```Dockerfile
FROM alpine/helm:3.5.2

# uncomment this to fix the build
ENV HELM_PLUGINS=/var/lib/helm/plugins

RUN apk add git ncurses bash curl

RUN helm plugin install https://github.com/jkroepke/helm-secrets

# Fails with command not found
RUN helm secrets --version
```

The `docker build` fails with:

```
 => ERROR [4/4] RUN helm secrets --version                                                                                                                                                                      0.3s
------
 > [4/4] RUN helm secrets --version:
#7 0.257 Error: unknown command "secrets" for "helm"
#7 0.257 Run 'helm --help' for usage.
```

**Comment by bacongobbler** [comment]
I can reproduce the issue. Looks like the plugin installer installs plugins into $HELM_DATA_HOME/plugins. $HELM_PLUGINS is not respected.

https://github.com/helm/helm/blob/179f90151d5ecb4aa3d35ada35e82b5c1e791752/pkg/plugin/installer/base.go#L38
