### ISSUE TITLE
fromYaml not working for arrays

### ISSUE THREAD

**Issue by FlyingDogFood** [helm/helm#9815]
helm version
`version.BuildInfo{Version:"v3.6.1", GitCommit:"61d8e8c4a6f95540c15c6a65f36a6dd0a45e7a2f", GitTreeState:"clean", GoVersion:"go1.16.5"}`

I recent project required me to build an Application configuration string as Json. The Application accepts an json array. But when i tried to convert the templated Yaml array to a Json array i ran into the following error: `"{\"Error\":\"error unmarshaling JSON: while decoding JSON: json: cannot unmarshal array into Go value of type map[string]interface {}\"}"`

How to reproduce:
templates/test1.yaml: (Not working as expected)
```
test: {{ include "test1" . | fromYaml | toJson | quote }}

{{ define "test1" }}
- test: test
{{ end }}
```

templates/test2.yaml:
```
test: {{ include "test2" . | fromYaml | toJson | quote }}

{{ define "test2" }}
test:
- test: test
{{ end }}
```

templates/test3.yaml:
`test: {{ .Values.test | toJson | quote }}
`

values.yaml:
```
test:
  - test: test
```
  
 Output of ` helm template --debug test .`:
 ```
---
# Source: test/templates/test1.yaml
test: "{\"Error\":\"error unmarshaling JSON: while decoding JSON: json: cannot unmarshal array into Go value of type map[string]interface {}\"}"
---
# Source: test/templates/test2.yaml
test: "{\"test\":[{\"test\":\"test\"}]}"
---
# Source: test/templates/test3.yaml
test: "[{\"test\":\"test\"}]"
```
I would expect that test1.yaml produces the same output as test3.yaml

**Comment by yxxhero** [comment]
@FlyingDogFood You can use `fromYAML`

**Comment by yxxhero** [comment]
@bacongobbler I think it is not a bug.  he should use `fromYamlArray`. Do you think of? Thanks very much.

**Comment by bacongobbler** [comment]
I had assumed `fromYaml` would cast to the correct type. That appears to be incorrect, because Helm internally serializes objects as a `map[string]object`. The only way to do this in Go is to introduce a new function `fromYamlArray` which can cast it to a variable of type `[]object`.

Please use `fromYamlArray` when dealing with array types.

Thanks.

**Comment by FlyingDogFood** [comment]
I also thought that `fromYAML` would cast directly into the right type.

Thanks for your help i will use `fromYAMLArray`.
