### ISSUE TITLE
Development versions not found with `--devel` and `--version`

### ISSUE THREAD

**Issue by iss0** [helm/helm#9816]
Output of `helm version`:
`version.BuildInfo{Version:"v3.6.1", GitCommit:"61d8e8c4a6f95540c15c6a65f36a6dd0a45e7a2f", GitTreeState:"clean", GoVersion:"go1.16.5"}`

Installing/upgrading with `helm upgrade --install` along with e.g. `--version 0.0.0-ceb0ed161669` leads to the error message:
```
Release "test" does not exist. Installing it now.
Error: failed to download "my-repo/my-chart at version "0.0.0-ceb0ed161669" (hint: running `helm repo update` may help)
```
Just tested that using the following `helm version` everything works just fine:
`version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}`

That is the same for the following command:
`helm show chart --devel myrepo/mychart`

For Helm v3.5.4 it just prints the chart information of the latest chart version where v3.6.1 it gives me the following error:
`Error: failed to download "myrepo/mychart" at version ">0.0.0-0" (hint: running helm repo update may help)`

**Comment by philmtd** [comment]
Hey @iss0 !! 👋🏼😄 

We have the same problem here...

**Comment by iss0** [comment]
I just noticed that this is because of the new behavior with the new version. If I remove the helm repo and add it again with `--pass-credentials` everything works fine. 

Guess this can be closed then.

**Comment by philmtd** [comment]
Works for us, too. Guess we should read release notes more carefully 😅

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!

**Comment by iss0** [comment]
@philmtd Are you using Artifactory too?

I investigated further and found out that the index.yaml of the virtual helm repository contains slightly different URLs for download links of the charts than the helm repository URL:

That is a link in the index.yaml for a chart: https://artifactory.something.io/artifactory/api/helm/virtual_helm/some-chart-0.0.1.tgz
That is the actual repository URL: https://artifactory.something.io/artifactory/virtual_helm/

So there is an additional /api/helm/ segment in the path of the download URL. So the configured helm repository has a different URL than the download links for charts. This leads to behaviour like this:

1. helm repo update works fine
2. you find the repo index.yaml in your cache directory afterwards ($HOME/.cache/helm/repository)
3. you can do a helm search repo some-chart -l perfectly fine listing the available versions
4. BUT actually downloading the chart fails because Helm now sees that the URL of the download is different from the configured repository and doesn’t send the credentials when downloading. That leads to a "204 - no content" returned by Artifactory leaving helm unable to download the chart.

**Comment by philmtd** [comment]
No, we're using Harbor for Docker Images and Helm Charts.

Our repository URL looks like https://harbor.something.io/chartrepo/repo_name and the links in the index.yaml are relative links like `charts/some-chart-0.0.1.tgz` leading to https://harbor.something.io/chartrepo/repo_name/charts/some-chart-0.0.1.tgz.

Now I don't really understand why in my case we need the `--pass-credentials` flag. Could there still be a bug @bacongobbler?

**Comment by iss0** [comment]
@philmtd That sound like https://github.com/helm/helm/issues/9820 in your case. Maybe that both problems are related.

**Comment by iss0** [comment]
I tried fix proposed by @dol in https://github.com/helm/helm/issues/9820 and it works for my issue with artifactory too!
