### ISSUE TITLE
Allow go templates in template define statement

### ISSUE THREAD

**Issue by MartinGolding515** [helm/helm#9834]
template names require a string literal. It would be easier to reuse for new charts if they could be defined dynamically, e.g:

{{- define (printf "%.mytemplate" .Chart.name) -}}

{{ include (printf "%.mytemplate" .Chart.name) . }}

**Comment by bacongobbler** [comment]
Suggestions for `text/template` improvements should be filed with the Go maintainers. Thanks.

https://golang.org/pkg/text/template/

https://github.com/golang/go#contributing
