### ISSUE TITLE
Feature: Add Sha256HMAC function

### ISSUE THREAD

**Issue by f0o** [helm/helm#9837]
While Sha256Sum is implemented it would be great to have Sha256HMAC function implemented as well to generate secure salted passwords right inside helm-templates and not relying on very ugly initContainer hacks to get passwords auto-generated for internal communication (like health-checks etc).

**Comment by bacongobbler** [comment]
Please submit feature requests for template functions to sprig.  Thanks!

https://github.com/Masterminds/sprig
