### ISSUE TITLE
List of changes deployed to production through Helm

### ISSUE THREAD

**Issue by macielro** [helm/helm#9839]
Hi,
One of the auditors asked to extract the list of changes deployed to production through Helm. Could you please inform how I can extract this list of changes from Helm? 
Thank you  in advance.

**Comment by yxxhero** [comment]
@macielro  I think  you need this: https://github.com/databus23/helm-diff

**Comment by macielro** [comment]
> @macielro I think you need this: https://github.com/databus23/helm-diff

Hi yxxhero, thank you very much.

**Comment by yxxhero** [comment]
@macielro you can close this issue? please. thanks very much.

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!
