### ISSUE TITLE
helm dependecy build: missing repos are not added automatically in presence of Chart.lock

### ISSUE THREAD

**Issue by weisdd** [helm/helm#9840]
There's inconsistency in behaviour of `helm dependency build` function:

* if there's no `Chart.lock` in a chart, all the dependencies listed in the respective section of `Chart.yaml` are added automatically;
* if `Chart.lock` is there, helm fails with an error like: `Error: no repository definition for https://grafana.github.io/helm-charts. Please add the missing repos via 'helm repo add'`.

I think helm should behave exactly the same in both cases.

I narrowed it down to the `Manager.Build()` function (`pkg/downloader/manager.go`) and have an idea how to fix it. I'll open a PR for that in a few minutes.

Output of `helm version`:
`version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}`
Note: it should affect releases up to the last one (`v3.6.1`) included.

Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:11:29Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.10", GitCommit:"98d5dc5d36d34a7ee13368a7893dcb400ec4e566", GitTreeState:"clean", BuildDate:"2021-04-15T03:20:25Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.19) exceeds the supported minor version skew of +/-1
`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): microk8s

**Comment by mattfarina** [comment]
We discussed this on the Helm developer call today. The reason `helm dep build` doesn't automatically add repos is due to security. In Helm v4 we plan to make `helm dep update` not automatically add them either. More details are at #9903.

We realize there is some inconvenience with having to add each repo. It's an opt-in and awareness for security around supply chain attacks.
