### ISSUE TITLE
List of changes deployed to production through Helm for one year

### ISSUE THREAD

**Issue by macielro** [helm/helm#9846]
Is it possible to generate a list of all changes deployed to production through Helm for one year? If yes, how can I generate this?
Thank you in advance.

**Comment by bacongobbler** [comment]
Using a combination of `helm list --all --all-namespaces --date` to sort all releases by their date, then grep/awk based on the output should get you 90% of the way there.

From `helm list --help`:

> By default, it lists only releases that are deployed or failed. Flags like
'--uninstalled' and '--all' will alter this behavior. Such flags can be combined:
'--uninstalled --failed'.

> By default, items are sorted alphabetically. Use the '-d' flag to sort by
release date.

Hope this helps.

**Comment by macielro** [comment]
> Using a combination of `helm list --all --all-namespaces --date` to sort all releases by their date, then grep/awk based on the output should get you 90% of the way there.
> 
> From `helm list --help`:
> 
> > By default, it lists only releases that are deployed or failed. Flags like
> > '--uninstalled' and '--all' will alter this behavior. Such flags can be combined:
> > '--uninstalled --failed'.
> 
> > By default, items are sorted alphabetically. Use the '-d' flag to sort by
> > release date.
> 
> Hope this helps.

Hi bacongobbler, thank you very much. I really appreciate your help.

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!
