### ISSUE TITLE
version '1.0.1-demo_my_branch-SNAPSHOT' is not a valid SemVer (even though it is?)

### ISSUE THREAD

**Issue by dev-samples** [helm/helm#9860]
Using helm v3.5.4 on ubuntu I am trying to build a helm chart (from a feature branch) with the version:

**1.0.1-my_branch-SNAPSHOT**

but get this error:

```
[ERROR] Chart.yaml: version '1.0.1-my_branch-SNAPSHOT' is not a valid SemVer
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: validation: chart.metadata.version "1.0.1-my_branch-SNAPSHOT" is invalid
[ERROR] : unable to load chart
        validation: chart.metadata.version "1.0.1-my_branch-SNAPSHOT" is invalid
```
But from what I understand that is semver compatible:

https://jubianchi.github.io/semver-check/#/version/1.0.1-my_branch-SNAPSHOT

Is this a bug in helm or my understanding of semver?

**Comment by bacongobbler** [comment]
semver-check uses NPM semantic version checks. There are several incompatibilities between NPM semver and "official" semver.

https://semver.org/#backusnaur-form-grammar-for-valid-semver-versions

pre-release identifiers can only contain a single dash, then dot-separated alphanumeric characters.

`1.0.1-mybranch+SNAPSHOT` is valid input.

**Comment by mattfarina** [comment]
According to the spec, prereleases (the part after the `-`) are to be comprised of...

> Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-]

You'll notice that a `_` is not one of the allowed characters in a prerelease. I suspect this is the problem.

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!
