### ISSUE TITLE
Generate helm chart using go library

### ISSUE THREAD

**Issue by kotyara85** [helm/helm#9863]
Hello there,
Is there any docs on how to generate a helm chart using go client library?
I got *chart.Chart & value files generated.
So I guess it's the last step.
I pretty much need to implement helm template command.
Thanks!

**Comment by bacongobbler** [comment]
The source code for `helm template` can be found here: https://github.com/helm/helm/blob/fa558f7843e9a3ce317754b121f5ecd2a505b109/cmd/helm/template.go#L76-L82

There are no documentation. But you can look at the following packages for ideas:

https://pkg.go.dev/helm.sh/helm/v3@v3.6.1/pkg/action#Install
https://pkg.go.dev/helm.sh/helm/v3@v3.6.1/pkg/kube
