### ISSUE TITLE
Some repositories get downloaded multiple times

### ISSUE THREAD

**Issue by lucasmdrs** [helm/helm#9878]
Dependencies download can result in unnecessary work when two or more dependencies have different names but point to the same repository  

https://github.com/helm/helm/blob/ae8e88e0d93e2f0c0edc4521db18774ada6334bd/pkg/downloader/manager.go#L498

**Comment by bacongobbler** [comment]
Marking as a support question as there's not a whole lot of information to determine what is the issue or how to reproduce it.

**Comment by lucasmdrs** [comment]
Sorry about that, I assumed that an issue would not be necessary as stated here:

https://github.com/helm/helm/blob/main/CONTRIBUTING.md#pr-lifecycle
> It is preferred, but not required, to have a PR tied to a specific issue. There can be circumstances where if it is a quick fix then an issue might be overkill. The details provided in the PR description would suffice in this case.

I'll make sure to add more info in the future

**Comment by bacongobbler** [comment]
Sorry, I ageee that isn’t very clear. That is mostly meant for smaller changes like to fix a typo or adding a test case. Behavioural changes to the code should have an issue along with a full explanation tied to the change. That way we can test it and verify the issue before looking at specifics.
