### ISSUE TITLE
Define JSON schema in YAML format

### ISSUE THREAD

**Issue by j-zimnowoda** [helm/helm#9880]
It is much easier to maintain structures in YAML format. 
Can we support `values.schema.yaml` as an alternative to `values.schema.json`?

**Comment by bacongobbler** [comment]
duplicate of https://github.com/helm/helm/issues/5812.

**Comment by armsnyder** [comment]
@bacongobbler Can you consider re-opening this please? I also expected Helm to support a yaml format for JSON schemas, as that is the format I am used to seeing for schemas in Kubernetes. (See how custom resource definition schemas work.)
