### ISSUE TITLE
Helm go-SDK v3 OCI registry support

### ISSUE THREAD

**Issue by Jiawei0227** [helm/helm#9884]
This is a mirror of https://github.com/helm/helm/issues/8255 since that one is closed. I am wondering if there is a timeline on publishing the API?

**Comment by bacongobbler** [comment]
Hi @Jiawei0227. The answer is still the same as provided in #8255. [HIP 6](https://github.com/helm/community/blob/main/hips/hip-0006.md) describes in more detail on what changes need to occur before we begin to evaluate whether it is ready to be marked as stable. #9188 also provides more recent context around when and why we haven't published the API quite yet.

In any case, I'm going ahead and closing this as we already have another ticket discussing this: https://github.com/helm/helm/issues/9188

Thanks!
