### ISSUE TITLE
crd does not render

### ISSUE THREAD

**Issue by cndoit18** [helm/helm#9885]
https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/

Version conversion mechanism is provided in the CRD, and we wrote a webhook to upgrade our version. However, when we installed it, we found that the information from the CRD was not what we expected.

in `crds/`
![image](https://user-images.githubusercontent.com/55286565/123740203-a2290700-d8da-11eb-9906-e8566b5874be.png)

expected:
![image](https://user-images.githubusercontent.com/55286565/123740296-c553b680-d8da-11eb-8372-f09d794c218d.png)

results:
![image](https://user-images.githubusercontent.com/55286565/123740400-f633eb80-d8da-11eb-9720-07f9823212a2.png)

Does the result meet design expectations?

**Comment by cndoit18** [comment]
I will try to spend some time fixing it

**Comment by cndoit18** [comment]
We intend to migrate CRDs to templates.

**Comment by yxxhero** [comment]
I will help you! please wait. @cndoit18

**Comment by yxxhero** [comment]
@cndoit18 CRD files cannot be templated. They must be plain YAML documents.  https://helm.sh/docs/topics/charts/

**Comment by cndoit18** [comment]
> @cndoit18 CRD files cannot be templated. They must be plain YAML documents. https://helm.sh/docs/topics/charts/

So for now, in order to support the conversion of CRD ,  only migrate to templates

**Comment by cndoit18** [comment]
I would like to hear your advice
thank you
cc @bacongobbler
