### ISSUE TITLE
get_helm.sh fails on verifying checksum

### ISSUE THREAD

**Issue by missdoor** [helm/helm#9887]
Downloading https://get.helm.sh/helm-v3.6.2-linux-amd64.tar.gz
Verifying checksum... SHA sum of /tmp/helm-installer-AHik8q/helm-v3.6.2-linux-amd64.tar.gz does not match. Aborting.
Failed to install helm
	For support, go to https://github.com/helm/helm.

./get_helm.sh
Helm v3.6.2 is available. Changing from version v3.2.4.
Downloading https://get.helm.sh/helm-v3.6.2-darwin-amd64.tar.gz
Verifying checksum... SHA sum of /var/folders/gn/ms6vk7yd7h5_s7kzt9hjqtfr0000gn/T/helm-installer-XXXXXX.BTGvXFP1/helm-v3.6.2-darwin-amd64.tar.gz does not match. Aborting.
Failed to install helm
	For support, go to https://github.com/helm/helm.

**Comment by bacongobbler** [comment]
This has been fixed. There was a slight hiccup during the release. Thanks for the report.
