### ISSUE TITLE
Issue with helm upgrade when chart is in private git repo

### ISSUE THREAD

**Issue by DKurilo** [helm/helm#9891]
I always used the same `helm upgrade` command and recently (with new helm version) it stopped working.
This what I have now:
```
helm -n qa upgrade my-chart my-organization/my-chart --values my-chart-values-qa.yaml --debug
Error: failed to fetch https://raw.githubusercontent.com/my-organization/special-repo/master/charts/my-chart-0.2.2.tgz : 404 Not Found
helm.go:81: [debug] failed to fetch https://raw.githubusercontent.com/my-organization/special-repo/master/charts/my-chart-0.2.2.tgz : 404 Not Found
helm.sh/helm/v3/pkg/getter.(*HTTPGetter).get
        helm.sh/helm/v3/pkg/getter/httpgetter.go:90
helm.sh/helm/v3/pkg/getter.(*HTTPGetter).Get
        helm.sh/helm/v3/pkg/getter/httpgetter.go:42
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo
        helm.sh/helm/v3/pkg/downloader/chart_downloader.go:99
helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart
        helm.sh/helm/v3/pkg/action/install.go:704
main.newUpgradeCmd.func2
        helm.sh/helm/v3/cmd/helm/upgrade.go:130
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.1.3/command.go:852
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.1.3/command.go:960
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.1.3/command.go:897
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:80
runtime.main
        runtime/proc.go:225
runtime.goexit
        runtime/asm_amd64.s:1371
```

Part of `~/Library/Preferences/helm/repositories.yaml`:
```
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: my-repo-name
  pass_credentials_all: false
  password: <my github token>
  url: https://raw.githubusercontent.com/my-organization/special-repo/master/charts/
  username: my@email.here
```

After I chnged `  url: https://raw.githubusercontent.com/my-organization/special-repo/master/charts/` to `  url: https://my-token@raw.githubusercontent.com/my-organization/special-repo/master/charts/` I was able to upgrade it. But I believe it's not supposed to work this way. `helm repo update` works fine.

Output of `helm version`: version.BuildInfo{Version:"v3.6.1", GitCommit:"61d8e8c4a6f95540c15c6a65f36a6dd0a45e7a2f", GitTreeState:"dirty", GoVersion:"go1.16.5"}

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:52:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.18) exceeds the supported minor version skew of +/-1
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.):  EKS

**Comment by bacongobbler** [comment]
Hi @DKurilo. Have you had the chance to read through the Helm 3.6.1 release notes and the accompanying security advisory? A breaking change was introduced to chart repositories backed by authentication. The release notes and the advisory contains information and next steps to help with the upgrade.

**Comment by DKurilo** [comment]
Hi @bacongobbler , thank you so much for fast answer! Oh, I read this issue, but not release notes. :) Sorry.
And I thought about pass-credentials parameter, but was confused by description: `--pass-credentials           pass credentials to all domains`. I didn't get what is `all domains`.
Thank you. Will read release notes next time.
Maybe it's better not to name breaking changes as minor release.
