### ISSUE TITLE
helm install return error when use base authentication repo URL

### ISSUE THREAD

**Issue by lyzhang1999** [helm/helm#9894]
Output of `helm version`:

version.BuildInfo{Version:"v3.6.2", GitCommit:"ee407bdf364942bcb8e8c665f82e15aa28009b71", GitTreeState:"clean", GoVersion:"go1.16.5"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:09:16Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Minikube

When I use `helm install wepack wepack-testing --repo https://username:password@coding-public-helm.pkg.coding.net/wepack/wepack`, return:

```
Error: failed to download "https://coding-public-helm.pkg.coding.net/wepack/wepack/wepack-testing/wepack-testing-0.0.0-release.tgz" at version "0.0.0-release" (hint: running `helm repo update` may help)
```

It seem that `FindChartInAuthAndTLSAndPassRepoURL` can download index file `index.yaml`.

![image](https://user-images.githubusercontent.com/8142348/123902793-09f55580-d9a0-11eb-844a-0edf9b9c244f.png)

but next to `getter.WithBasicAuth`, It set empty username and password in `dl.Options`.

![image](https://user-images.githubusercontent.com/8142348/123903246-eaaaf800-d9a0-11eb-9ac6-d704fa35ee65.png)

so I create PR to fix it. #9893

**Comment by bacongobbler** [comment]
Again, please stop adding username/password credentials in the repository URL. Please use the `--username` and `--password` feature flags instead.

I'm getting a 401 because the username and password are incorrect. However the following should work assuming you use the correct credentials.

```
><> helm install wepack wepack-testing --repo https://coding-public-helm.pkg.coding.net/wepack/wepack --username username --password password
Error: looks like "https://coding-public-helm.pkg.coding.net/wepack/wepack" is not a valid chart repository or cannot be reached: failed to fetch https://coding-public-helm.pkg.coding.net/wepack/wepack/index.yaml : 401 Unauthorized
```

**Comment by bacongobbler** [comment]
Closing as documented in https://helm.sh/docs/topics/chart_repository/#share-your-charts-with-others
