### ISSUE TITLE
Basic Auth does not work for (nested) dependencies of Helm charts/Umbrella chart

### ISSUE THREAD

**Issue by renepardon** [helm/helm#9898]
My problem:
=========

I've a problem with Basic Auth. We have a private helm repository. `helm repo add` with username/password works. But as soon as I try `helm dep build` / `helm dep update` I receive: 

```
$ helm dep update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "our-helm-repo" chart repository
Update Complete. ⎈Happy Helming!⎈
Error: error unpacking common-0.1.0-latest.tgz in admin: gzip: invalid header
```

"admin" is a dependency of my umbrella chart. Both have the "common" (library) chart as a dependency from the same helm chart repository. Downloading and unzipping/untar the helm archive manually (from Browser or with curl) works.

What I expect:
===========

`helm dep update` should reuse the credentials used when adding the repository with "helm repo add"

MORE INFORMATION:
==================

**Output of `helm version`:** 
```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
```

**Output of `kubectl version`:** 
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"archive", BuildDate:"2021-05-10T15:36:22Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Cloud Provider/Platform (AKS, GKE, Minikube etc.):** IONOS / Gitlab

**Client: Docker Engine - Community:** Version: 20.10.7

**Comment by bacongobbler** [comment]
Hi @renepardon. can you please provide more information on your setup? It would be helpful to provide how someone can attempt to reproduce a similar environment so that a cause can be identified and a test case can be used to test solutions against. Without much more than the error message, I cannot determine how to even start testing for this failure case.

Thanks.

**Comment by bacongobbler** [comment]
Can you also try testing with Helm 3.6.2? A number of fixes have been made to Helm and chart repositories since Helm 3.5.4, so it is possible this has already been fixed in future updates.

**Comment by renepardon** [comment]
Hello @bacongobbler 

I will upgrade but looks like the problem was self-made. The response from the own Chart Repository was HTML for some reason but I could fix that.

Best
