### ISSUE TITLE
Is it possible to use Kustomize with Helm?

### ISSUE THREAD

**Issue by thesuperzapper** [helm/helm#9904]
Is there any way to have Helm apply a `kustomize template` within your helm `templates/` folder?

__For example, I might want to have a helm chart which looks like this:__
```
chart/
- kustomize_app/
   - base/
      - deployment.yaml
   - overlays/
      - option_1/
         - deploment-patch-1.yaml
      - option_2/
         - deploment-patch-2.yaml
   - kustomization.yaml
- templates/
   - reference-to-kustomize_app.yaml
- Chart.yaml
```

Can helm be made to view `reference-to-kustomize_app.yaml` not as its literal YAML, but as the output of running `kustomize template "../kustomize_app"`? This would let users paramaterize existing kustomize applications (that is, control which overlays are applied), with helm `values.yaml`.

Allowing this would open up a very nice pattern for Helm to be a "package manager" for kustomize templates, which is needed because kustomize is (by design) limited to only outputting plain YAML (in a purely deterministic way from your `kustomization.yaml`), making it hard for software-creators to package kustomize applications with configs for their users.

Right now, many kustomize apps are creating their own solutions using `bash` commands like `sed`, which is much less elegant than Helm, which is already widely understood.

**Comment by thesuperzapper** [comment]
There are similar issues https://github.com/helm/helm/issues/9855 and https://github.com/helm/helm/issues/9855, but no resolution has been made.

**Comment by mattfarina** [comment]
Thanks for the suggestion.

How would something like this work with Helm? Let's say kustomize isn't installed, how is that case handled? Or, kustomize is on its 4th major version which means backwards compatibility has been broken. How do we deal with different major and minor (feature) versions of kustomize that people make have installed? Or, kustomize doesn't ship on Windows and there are many Windows users. What do we tell them about these charts? (note, the docs say they publish binaries for Windows but looking at [the latest release you won't find one](https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv4.2.0))

Something like this would need to be filed as a [Helm Improvement Proposal (HIP)](https://github.com/helm/community/tree/main/hips). Would you consider filing one and try to fill in how the varying different situations should be handled.
