### ISSUE TITLE
'*chart.Chart' does not support concurrency, causing 'Chart.dependencies' to be nil

### ISSUE THREAD

**Issue by chijinxina** [helm/helm#9906]
// https://github.com/helm/helm/blob/main/pkg/chart/chart.go
// SetDependencies replaces the chart dependencies.
func (ch *Chart) SetDependencies(charts ...*Chart) {
	ch.dependencies = nil                        
	ch.AddDependency(charts...)          
}

// https://github.com/helm/helm/blob/main/pkg/chart/dependency.go
func processDependencyEnabled(c *chart.Chart, v map[string]interface{}, path string) error {
       ....
       c.SetDependencies(chartDependencies...)
}

// https://github.com/helm/helm/blob/main/pkg/action/upgrade.go
if err := chartutil.ProcessDependencies(chart, vals); err != nil {
      return nil, nil, err
}

Calling upgrade in a multi-threaded will cause 'chart.dependencies' and 'chart.parents' not to meet expectations

**Comment by chijinxina** [comment]
It is recommended to set 'chart.dependencies' and 'chart. parents' as exportable, allowing the caller to make a DeepCopy of them used in multi-thread

**Comment by yxxhero** [comment]
Can you make a PRs to the feature. @chijinxina
