### ISSUE TITLE
new crd (does not exist by name on cluster) in helm crds folder does not get deployed

### ISSUE THREAD

**Issue by Morriz** [helm/helm#9907]
Hi, we try to update istio operator, which was deployed before with one crd in the chart's `crds` folder. The crd in the new chart has another resource name, so we would expect it to be deployed. To be precise:

the old deployment has deployed one crd with name: `instances.config.istio.io`

the new deployment has one crd with name: `istiooperators.install.istio.io`

We fail to understand why helm does not seem to deploy the new crd, as it is not conflicting by name. Is there some overarching general logic that prohibits any new crds from being deployed from the crds` folder? Like in case the helm chart was once deployed with crds in it? If that is the case that logic could be fixed to allow new crds imo, when those are not conflicting.

Maybe our observation or evaluation is incorrect. We hope to be given more information if that is the case.

Output of `helm version`: 3.5.4

Output of `kubectl version`: 1.19.7

**Comment by Morriz** [comment]
And what would be a good way to get thorough helm output as to why it won't deploy a crd?

**Comment by yxxhero** [comment]
@Morriz https://helm.sh/docs/topics/charts/#limitations-on-crds please it. Thans very much.

**Comment by mattfarina** [comment]
CRDs are complicated to deal with. Brendan Burns (k8s co-creator) once described them as:

> The primary motivation for custom resources was to provide a simple easy to use extension mechanism
for Kubernetes clusters to enable customization by Kubernetes users and to facilitate a rich
ecosystem of plugins for Kubernetes clusters. If Kubernetes is the kernel, CustomResourceDefinitions
are intended to be loadable kernel modules.

We have [an informational doc that describes the details of CRDs and Helms current interactions](https://github.com/helm/community/blob/main/hips/hip-0011.md). It touches on how CRDs work, Helms general philosophy, ways you can caused destruction to resources to your cluster with CRD changes, and more.

Helm doesn't manage CRDs but will install them if you have permissions at install time. No other management is supported for reasons outlined in that document.

**Comment by Morriz** [comment]
Can it not deploy new crds by name? How can a chart evolve over time in the current setup? I have read those docs and contributed my views, but see no support from the helm devs that conform with api best practices.

**Comment by mattfarina** [comment]
@Morriz That's a good question. There are many ways that using Helm to manage CRDs can break a cluster easily. It has to do with automation making decisions without having full context. A person with context should make those decisions. The info doc I shared has the details.

The second method on https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#install-a-crd-declaration-before-using-the-resource can be used in a way to have CRDs being managed. I would suggest being very careful and do not uninstall the CRD chart unless you know what you're doing. Removing a CRD - even for a moment before reinstalling or upgrading - will remove all CRs for it in a cluster.

CRDs are like kernel extensions and not userspace programs. Care needs to be given to their change management.

**Comment by Morriz** [comment]
Tnx. I think we should leave responsibility to end users, and not assume anything about them. IMO code offers functionality that is designed and implemented with standards/best practices in mind, such as openapi/semver. Solutions that break those paradigms are subpar imo and create friction with the user base.

In that context, not installing _new_ crds that are not conflicting is a weird decision imo. Or is it just not thought about?

**Comment by mattfarina** [comment]
@Morriz There is consideration here. Let's say a user installs a chart and some CRDs are installed. Then a user goes to update that chart and there are CRD changes. If only the new/missing CRDs are installed but those that exist are not updated you will end up in a possibly unhealthy situation. The CRDs in the cluster will not match those in the charts due to a lack of updating the existing ones. We believe it's _safer_ for someone who is aware of the situation to make the appropriate updates. Note, the goal here is on safety rather than convenience. As the info doc I linked to earlier shows, it's not hard to make CRD changes that break workloads in a cluster.
