### ISSUE TITLE
Output JSON schema next to chart tarball

### ISSUE THREAD

**Issue by remcohaszing** [helm/helm#9920]
It would be useful if Helm outputs a chart’s JSON schema next to the generated tarball, so it can be downloaded for schema validation when working with that chart. When signing a Helm chart, a `.prov` file is also generated, so `helm package` already outputs multiple files.

I.e. the file structure would look like this:

```
├─ my-chart-1.2.3.json.schema
├─ my-chart-1.2.3.tgz
└─ my-chart-1.2.3.tgz.prov
```

If this is implemented, one can get completion using `yaml-language-server` using a modeline when editing a `values.yaml` file. For example:

```yaml
# yaml-language-server: $schema=https://helm.charts.example/my-chart.1.2.3.json.schema

# This will be validated and auto completed in the editor
foo: bar
```

This also allows to reference JSON schemas when developing a chart that consumes a dependency. For example, if a chart depends on `bitnami/postgresql`, the chart’s JSON schema could look like this:

```json
{
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "postgresql": {
      "$ref": "https://charts.bitnami.com/bitnami/postgresql-10.5.0.schema.json"
    }
  }
}
```

**Comment by mattfarina** [comment]
Thank you for the feature suggestion. This is the kind of change we typically take through a [Helm Improvement Process](https://github.com/helm/community/tree/main/hips). This allows us to consider all the implications of such a change. Would you consider going through that process with this feature request.
