### ISSUE TITLE
Move to GitHub Actions

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#9921]
The current CI setup has gotten more flaky and slower over time. For example, there have been numerous times where a PR has been submitted and the CI webhook gets a 400 (Bad Request) response from CircleCI. No details on why its bad are provided and resubmitting it also returns a 400.

In addition to that, test run times have gotten a lot longer. For example, we have had to increase the lint test timeout once and may need to again due to recent timeouts. All of this while the codebase is not significantly different in size. The time to build binaries for releases has also gone up a lot.

Moving to GitHub Actions will remove the 400 errors and should perform at a faster speed. In addition to that, we can add better windows testing.

**Comment by cndoit18** [comment]
This is great!

**Comment by bacongobbler** [comment]
Actions still need to be implemented:

- [ ] make build-pr trigger on merges to the main branch
- [ ] disable CircleCI builds
- [ ] create a "publish" action

**Comment by tylerauerbeck** [comment]
@bacongobbler Happy to help out here on 1 & 3 if this is still available.

**Comment by bacongobbler** [comment]
Feel free!
