### ISSUE TITLE
How can I control the startup sequence of the chart through Chart Hook?

### ISSUE THREAD

**Issue by kqkdChen** [helm/helm#9930]
Output of `helm version`:  v3.6.2

Output of `kubectl version`: {Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z",
GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  docker desktop for kubernetes

As shown in the figure, I rely on other charts through requirements.yaml
![image](https://user-images.githubusercontent.com/41674301/124963396-556bcb80-e052-11eb-948a-31622406747b.png)

Then I enable them in values.yml. The types of eureka and pg-run are both statefulset. I defined eureka's weight as a negative number and pg-run as a positive number through the chart hook. According to the official website, the weight of the negative number is executed first, so in theory, eureka starts first, but in fact, eureka and pg-run are at the same time How to use chart hook when it is started? Which step is wrong?

![image](https://user-images.githubusercontent.com/41674301/124963583-95cb4980-e052-11eb-94e8-fd5305e7e361.png)
![image](https://user-images.githubusercontent.com/41674301/124963855-e642a700-e052-11eb-9480-029b725b824b.png)

**Comment by mattfarina** [comment]
There is some information that may help understand what is happening.

Kubernetes is a declarative system. The idea is that you declare what you want, Kubernetes running reconcile loops tries to make it happen, along the way it updates the state (current state) to show where it is at. Sending many different manifests to Kubernetes should, in theory, eventually reconcile to make it work.

In practice you sometimes need ordering.

Helm sends all of the manifests to Kubernetes at one time. Weighting provides some ability to sort the manifests but they are still sent to Kubernetes at once.

If you want ordering with checking that things have come up you'll need a system on top of Helm. Helm is a package manager (like apt, yum, zypper) and not a deployment config manager (like ansible or chef). A system on top of Helm can install packages, check status, and install other tools. The people who installed OpenStack on Kubernetes did this. That software has now become [airship](https://www.airshipit.org/).
