### ISSUE TITLE
Helm runs out of memory parsing large index.yaml files

### ISSUE THREAD

**Issue by pranavmarla** [helm/helm#9931]
I have access to two privately hosted Helm repos that I was recently attempting to pull Helm charts from. For some reason, only for one of the repos, the _helm_ binary would crash due to a lack of memory whenever I tried the following command: `helm repo update` -- I even tried removing the repo and re-adding it (`helm repo add`) but I ran into the same issue: 
Specifically, _helm_ would fail with this error message: `fatal error: runtime: out of memory`. 
This was for version `3.2.1` of _helm_.

I then moved to a brand new machine to see if I could replicate this error. On that machine, I installed the latest version of Helm (`3.6.2`). I got similar behaviour: Only for that one repo, _helm_ would crash, but now the error message was different: `Killed`

Eventually though, after running the same `helm repo add` command multiple times, I guess I got lucky and the command completed. In the process though, _helm_ generated a MASSIVE amount of warning messages that looked like this:
```
index.go:339: skipping loading invalid entry for chart "..." "..." from ...: validation: chart.metadata.version "..." is invalid
```
This message appears to be generated when Helm checks the chart versions for SemVer compliance, as per [this security notice](https://github.com/helm/helm/security/advisories/GHSA-c38g-469g-cmgx).

Since the repo that kept causing _helm_ to run out of memory is also the one with apparently a massive amount of charts with noncompliant versions, **it seems like the Helm validation is inadvertently causing the memory issues -- i.e. since our Helm repo has so many noncompliant charts, _helm_ runs out of memory, and I am unable to even add that repo.**

Unfortunately, I do not own/control the repo, so is there any way we can mitigate this performance hit on the Helm side? Perhaps a flag to the _helm_ binary that tells it not to generate a separate warning message for every single noncompliant chart?

ps: The only confusing thing is that I saw this memory error on two different versions of Helm: `3.2.1` and `3.6.2`, but the security notice says that the patch was introduced in `3.5.1` -- so, not sure if my diagnosis of the issue is wrong.

Output of `helm version`:
- Machine 1: 
```
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```
- Machine 2:
```
version.BuildInfo{Version:"v3.6.2", GitCommit:"ee407bdf364942bcb8e8c665f82e15aa28009b71", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

Output of `kubectl version`:
- Machine 1: 
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Machine 2:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS

More information:
For more information on my setup, the error messages (including stack trace) that I saw, please see my comment below: [link](https://github.com/helm/helm/issues/9931#issuecomment-877733134)

**Comment by pranavmarla** [comment]
It looks like @rcousineau-xandr submitted a PR back in April that reduces the volume of warning messages to a single line: #9611

IF my diagnosis of this issue is correct, and the _helm_ memory issues are caused by the volume of warning messages, then I suspect that PR would solve this issue as well.

@mattfarina  @bacongobbler Would appreciate your thoughts on this issue and the linked PR when you get a chance!

**Comment by rcousineau-xandr** [comment]
@pranavmarla maybe check out my branch, build it, run it, see if it resolves the issue for you?

**Comment by mattfarina** [comment]
@pranavmarla How large is the repository? Can you share the size of the `index.yaml` file. Also, is this being run in a container or directly on the machine? What OS is it using?

**Comment by bacongobbler** [comment]
First off, sorry to hear you're running into this. 

> it seems like the Helm validation is inadvertently causing the memory issues

I think the first best step would be to come up with a test case to confirm your suspicion. I think it's more likely due to loading a huge index.yaml as @mattfarina is alluding to than dumping strings to standard error, or it could be a genuine memory allocation error. But more testing to prove your suspicions would be great here.

As a note, someone attempted to reproduce `helm install` memory issues using a project called [fiber](https://gofiber.io/) and its built-in profiler. Might be worth experimenting to see what could be causing the issue. Have a look at https://github.com/helm/helm/issues/9913 for more information.

Here's the project:

https://github.com/extbe/helm-ram-usage

**Comment by pranavmarla** [comment]
@mattfarina Thanks for checking this out! That's a good point, I hadn't considered that. I've gathered some more information on my setup -- hope it helps!

1. As mentioned above, I observed this behaviour on two machines, running different versions of _helm_ -- in both cases, _helm_ was installed (via the standard [script](https://helm.sh/docs/intro/install/#from-script)) directly on the machines. Here are the details of those machines:
- Machine 1: Ubuntu 18.04 with 1 core CPU and 2 GB RAM
```
> uname -a
Linux ... 4.15.0-143-generic #147-Ubuntu SMP Wed Apr 14 16:10:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
- Machine 2: Ubuntu 20.04 with 1 core CPU and 2 GB RAM
```
> uname -a
Linux ... 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

2. Helm repo _index.yaml_ sizes:
- Repo 1 (no issues): 4.42 MB
- Repo 2 (memory error): 65.56 MB

3. Here is the full stack trace produced by _helm_ when I try to add repo 2 (via `helm repo add`) on machine 1 (_helm_ v`3.2.1` only -- v`3.6.2` doesn't produce any stack trace):
```
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x1ab366e, 0x16)
        /usr/local/go/src/runtime/panic.go:774 +0x72
runtime.sysMap(0xc054000000, 0x4000000, 0x2aba5f8)
        /usr/local/go/src/runtime/mem_linux.go:169 +0xc5
runtime.(*mheap).sysAlloc(0x2a97340, 0x2556000, 0x10c, 0x7f49a3aebe10)
        /usr/local/go/src/runtime/malloc.go:701 +0x1cd
runtime.(*mheap).grow(0x2a97340, 0x12ab, 0xffffffff)
        /usr/local/go/src/runtime/mheap.go:1255 +0xa3
runtime.(*mheap).allocSpanLocked(0x2a97340, 0x12ab, 0x2aba608, 0x41dd75)
        /usr/local/go/src/runtime/mheap.go:1170 +0x266
runtime.(*mheap).alloc_m(0x2a97340, 0x12ab, 0x7f49a0290101, 0x7f49a0291c78)
        /usr/local/go/src/runtime/mheap.go:1022 +0xc2
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:1093 +0x4c
runtime.(*mheap).alloc(0x2a97340, 0x12ab, 0xc000010101, 0x7f49a0291c78)
        /usr/local/go/src/runtime/mheap.go:1092 +0x8a
runtime.largeAlloc(0x2554de1, 0x2ab0101, 0x7f49a0291c78)
        /usr/local/go/src/runtime/malloc.go:1138 +0x97
runtime.mallocgc.func1()
        /usr/local/go/src/runtime/malloc.go:1033 +0x46
runtime.systemstack(0xc000470300)
        /usr/local/go/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1146

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:330 fp=0xc034e8cb58 sp=0xc034e8cb50 pc=0x459ad0
runtime.mallocgc(0x2554de1, 0x17f6880, 0x203001, 0x203014)
        /usr/local/go/src/runtime/malloc.go:1032 +0x895 fp=0xc034e8cbf8 sp=0xc034e8cb58 pc=0x40c535
runtime.makeslice(0x17f6880, 0x2554de1, 0x2554de1, 0x1b7a238)
        /usr/local/go/src/runtime/slice.go:49 +0x6c fp=0xc034e8cc28 sp=0xc034e8cbf8 pc=0x44437c
bytes.makeSlice(0x2554de1, 0x0, 0x0, 0x0)
        /usr/local/go/src/bytes/buffer.go:229 +0x77 fp=0xc034e8cc90 sp=0xc034e8cc28 pc=0x4f5097
bytes.(*Buffer).grow(0xc04d80ad90, 0x9, 0x1849a80)
        /usr/local/go/src/bytes/buffer.go:142 +0x15b fp=0xc034e8cce0 sp=0xc034e8cc90 pc=0x4f49db
bytes.(*Buffer).WriteString(0xc04d80ad90, 0xc00e71c2f0, 0x9, 0x0, 0xc034e8cd70, 0x5ce204)
        /usr/local/go/src/bytes/buffer.go:184 +0xdd fp=0xc034e8cd10 sp=0xc034e8cce0 pc=0x4f4dfd
encoding/json.(*encodeState).string(0xc04d80ad90, 0xc00e71c2f0, 0x9, 0xc00e71c201)
        /usr/local/go/src/encoding/json/encode.go:957 +0x448 fp=0xc034e8cd70 sp=0xc034e8cd10 pc=0x5c4408
encoding/json.stringEncoder(0xc04d80ad90, 0x17f65c0, 0xc03dbcd290, 0x98, 0xc03dbc0100)
        /usr/local/go/src/encoding/json/encode.go:610 +0xd9 fp=0xc034e8ce08 sp=0xc034e8cd70 pc=0x5c18e9
encoding/json.(*encodeState).reflectValue(0xc04d80ad90, 0x17f65c0, 0xc03dbcd290, 0x98, 0xc03dbc0100)
        /usr/local/go/src/encoding/json/encode.go:337 +0x82 fp=0xc034e8ce40 sp=0xc034e8ce08 pc=0x5bf992
encoding/json.interfaceEncoder(0xc04d80ad90, 0x1847aa0, 0xc053b593a0, 0x94, 0xc053b50100)
        /usr/local/go/src/encoding/json/encode.go:619 +0xac fp=0xc034e8ce88 sp=0xc034e8ce40 pc=0x5c1c4c
encoding/json.mapEncoder.encode(0x1b7a120, 0xc04d80ad90, 0x184e400, 0xc04c5362a0, 0x15, 0x1840100)
        /usr/local/go/src/encoding/json/encode.go:706 +0x351 fp=0xc034e8cfd0 sp=0xc034e8ce88 pc=0x5c26f1
encoding/json.mapEncoder.encode-fm(0xc04d80ad90, 0x184e400, 0xc04c5362a0, 0x15, 0xc04c530100)
        /usr/local/go/src/encoding/json/encode.go:682 +0x64 fp=0xc034e8d010 sp=0xc034e8cfd0 pc=0x5ce104
encoding/json.(*encodeState).reflectValue(0xc04d80ad90, 0x184e400, 0xc04c5362a0, 0x15, 0xc04c530100)
        /usr/local/go/src/encoding/json/encode.go:337 +0x82 fp=0xc034e8d048 sp=0xc034e8d010 pc=0x5bf992
encoding/json.interfaceEncoder(0xc04d80ad90, 0x1847aa0, 0xc0498a8590, 0x194, 0x1840100)
        /usr/local/go/src/encoding/json/encode.go:619 +0xac fp=0xc034e8d090 sp=0xc034e8d048 pc=0x5c1c4c
encoding/json.arrayEncoder.encode(0x1b7a120, 0xc04d80ad90, 0x17bbca0, 0xc04c55af60, 0x97, 0x5b0100)
        /usr/local/go/src/encoding/json/encode.go:791 +0xd6 fp=0xc034e8d0e8 sp=0xc034e8d090 pc=0x5c3416
encoding/json.arrayEncoder.encode-fm(0xc04d80ad90, 0x17bbca0, 0xc04c55af60, 0x97, 0xc034e80100)
        /usr/local/go/src/encoding/json/encode.go:784 +0x64 fp=0xc034e8d128 sp=0xc034e8d0e8 pc=0x5ce204
encoding/json.sliceEncoder.encode(0xc000226c00, 0xc04d80ad90, 0x17bbca0, 0xc04c55af60, 0x97, 0x17b0100)
        /usr/local/go/src/encoding/json/encode.go:765 +0x8f fp=0xc034e8d170 sp=0xc034e8d128 pc=0x5c307f
encoding/json.sliceEncoder.encode-fm(0xc04d80ad90, 0x17bbca0, 0xc04c55af60, 0x97, 0xc04c550100)
        /usr/local/go/src/encoding/json/encode.go:760 +0x64 fp=0xc034e8d1b0 sp=0xc034e8d170 pc=0x5ce184
encoding/json.(*encodeState).reflectValue(0xc04d80ad90, 0x17bbca0, 0xc04c55af60, 0x97, 0xc04c550100)
        /usr/local/go/src/encoding/json/encode.go:337 +0x82 fp=0xc034e8d1e8 sp=0xc034e8d1b0 pc=0x5bf992
encoding/json.interfaceEncoder(0xc04d80ad90, 0x1847aa0, 0xc053b591a0, 0x94, 0xc04e920100)
        /usr/local/go/src/encoding/json/encode.go:619 +0xac fp=0xc034e8d230 sp=0xc034e8d1e8 pc=0x5c1c4c
encoding/json.mapEncoder.encode(0x1b7a120, 0xc04d80ad90, 0x184e400, 0xc0441ae720, 0x15, 0x1840100)
        /usr/local/go/src/encoding/json/encode.go:706 +0x351 fp=0xc034e8d378 sp=0xc034e8d230 pc=0x5c26f1
encoding/json.mapEncoder.encode-fm(0xc04d80ad90, 0x184e400, 0xc0441ae720, 0x15, 0xc0441a0100)
        /usr/local/go/src/encoding/json/encode.go:682 +0x64 fp=0xc034e8d3b8 sp=0xc034e8d378 pc=0x5ce104
encoding/json.(*encodeState).reflectValue(0xc04d80ad90, 0x184e400, 0xc0441ae720, 0x15, 0xc0441a0100)
        /usr/local/go/src/encoding/json/encode.go:337 +0x82 fp=0xc034e8d3f0 sp=0xc034e8d3b8 pc=0x5bf992
encoding/json.interfaceEncoder(0xc04d80ad90, 0x1847aa0, 0xc04e8b3910, 0x94, 0xc04e8b0100)
        /usr/local/go/src/encoding/json/encode.go:619 +0xac fp=0xc034e8d438 sp=0xc034e8d3f0 pc=0x5c1c4c
encoding/json.mapEncoder.encode(0x1b7a120, 0xc04d80ad90, 0x184e400, 0xc0441ae6c0, 0x15, 0x1840100)
        /usr/local/go/src/encoding/json/encode.go:706 +0x351 fp=0xc034e8d580 sp=0xc034e8d438 pc=0x5c26f1
encoding/json.mapEncoder.encode-fm(0xc04d80ad90, 0x184e400, 0xc0441ae6c0, 0x15, 0x7f49a7080100)
        /usr/local/go/src/encoding/json/encode.go:682 +0x64 fp=0xc034e8d5c0 sp=0xc034e8d580 pc=0x5ce104
encoding/json.(*encodeState).reflectValue(0xc04d80ad90, 0x184e400, 0xc0441ae6c0, 0x15, 0x400100)
        /usr/local/go/src/encoding/json/encode.go:337 +0x82 fp=0xc034e8d5f8 sp=0xc034e8d5c0 pc=0x5bf992
encoding/json.(*encodeState).marshal(0xc04d80ad90, 0x184e400, 0xc0441ae6c0, 0x1840100, 0x0, 0x0)
        /usr/local/go/src/encoding/json/encode.go:309 +0x10b fp=0xc034e8d678 sp=0xc034e8d5f8 pc=0x5bf43b
encoding/json.Marshal(0x184e400, 0xc0441ae6c0, 0xc034e8d620, 0x184e400, 0xc0441ae6c0, 0x0, 0x0)
        /usr/local/go/src/encoding/json/encode.go:161 +0x52 fp=0xc034e8d6f0 sp=0xc034e8d678 pc=0x5bea12
sigs.k8s.io/yaml.yamlToJSON(0xc014920000, 0x54820ec, 0x7fffe00, 0xc034e8d7c8, 0x1b7c3e0, 0xc01891fe00, 0xc00c91fe00, 0xc00005e380, 0x7f49a7082008, 0x0)
        /go/pkg/mod/sigs.k8s.io/yaml@v1.2.0/yaml.go:139 +0xff fp=0xc034e8d740 sp=0xc034e8d6f0 pc=0x9bc41f
sigs.k8s.io/yaml.yamlUnmarshal(0xc014920000, 0x54820ec, 0x7fffe00, 0x1927220, 0xc00071e050, 0xc000324000, 0x0, 0x0, 0x0, 0x8, ...)
        /go/pkg/mod/sigs.k8s.io/yaml@v1.2.0/yaml.go:53 +0x119 fp=0xc034e8d7f0 sp=0xc034e8d740 pc=0x9bbde9
sigs.k8s.io/yaml.Unmarshal(...)
        /go/pkg/mod/sigs.k8s.io/yaml@v1.2.0/yaml.go:36
helm.sh/helm/v3/pkg/repo.loadIndex(0xc014920000, 0x54820ec, 0x7fffe00, 0xc014920000, 0x54820ec, 0x7fffe00)
        /home/circleci/helm.sh/helm/pkg/repo/index.go:284 +0x9b fp=0xc034e8d8a8 sp=0xc034e8d7f0 pc=0x160b5eb
helm.sh/helm/v3/pkg/repo.(*ChartRepository).DownloadIndexFile(0xc0001cc320, 0xc000739c20, 0x1, 0x1, 0xc0001cc320)
        /home/circleci/helm.sh/helm/pkg/repo/chartrepo.go:140 +0x38e fp=0xc034e8da70 sp=0xc034e8d8a8 pc=0x160801e
main.(*repoAddOptions).run(0xc000028960, 0x1d28ec0, 0xc00000e020, 0x0, 0x0)
        /home/circleci/helm.sh/helm/cmd/helm/repo_add.go:133 +0x59e fp=0xc034e8dcc8 sp=0xc034e8da70 pc=0x16d584e
main.newRepoAddCmd.func1(0xc000024840, 0xc0006b0e40, 0x2, 0x6, 0x0, 0x0)
        /home/circleci/helm.sh/helm/cmd/helm/repo_add.go:68 +0xed fp=0xc034e8dd00 sp=0xc034e8dcc8 pc=0x16e924d
github.com/spf13/cobra.(*Command).execute(0xc000024840, 0xc0006b0de0, 0x6, 0x6, 0xc000024840, 0xc0006b0de0)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x460 fp=0xc034e8ddd8 sp=0xc034e8dd00 pc=0x5d6240
github.com/spf13/cobra.(*Command).ExecuteC(0xc000215600, 0x1d6bce0, 0xc0000c6630, 0xc000367500)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349 fp=0xc034e8deb0 sp=0xc034e8ddd8 pc=0x5d6d69
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:83 +0x206 fp=0xc034e8df60 sp=0xc034e8deb0 pc=0x16ca376
runtime.main()
        /usr/local/go/src/runtime/proc.go:203 +0x21e fp=0xc034e8dfe0 sp=0xc034e8df60 pc=0x43003e
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc034e8dfe8 sp=0xc034e8dfe0 pc=0x45ba21

goroutine 6 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x2a90600)
        /go/pkg/mod/k8s.io/klog@v1.0.0/klog.go:1010 +0x8b
created by k8s.io/klog.init.0
        /go/pkg/mod/k8s.io/klog@v1.0.0/klog.go:411 +0xd6

goroutine 11 [syscall]:
os/signal.signal_recv(0x45ba26)
        /usr/local/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:29 +0x41
```

4. Here's a screenshot from _top_ showing _helm's_ resource usage when I tried to add the two repos (taken on machine 1):
- Repo 1 (no issues):
![helm-stable](https://user-images.githubusercontent.com/6486632/125181313-9807e200-e1d1-11eb-85bc-7029abf11062.png)
- Repo 2 (memory error):
![helm-incubator](https://user-images.githubusercontent.com/6486632/125181336-bf5eaf00-e1d1-11eb-8c2f-60995e5beeb7.png)

**Comment by pranavmarla** [comment]
@bacongobbler  Thanks for checking this out! That's a good point, I'll see what I can do to validate if this actually is the cause of the error I'm seeing -- I'll comment back here if I find anything useful.

**Comment by mattfarina** [comment]
> Repo 2 (memory error): 65.56 MB

This might be the largest _index.yaml_ file I've seen. I suspect that yaml parsing is the issue. A few years ago I did some [YAML and JSON parsing benchmarks](https://github.com/mattfarina/yamlbench). YAML parsing is not very performant. The situation has improved a little since I ran those benchmarks (we're now using a fork of ghodss YAML parser maintained by Kubernetes).

YAML is more work to parse than JSON due to YAML anchors. In the parsers we have they take the easy route and load the whole thing into memory. The Kubernetes based parser (based on ghodss) is one I've seen that uses the most memory.

We've long talked about having an _index.json_ index file (alongside the _index.yaml_ for backwards compatibility) as it would reduce the memory usage when parsing. I wonder if we should start work on that.

**Comment by pranavmarla** [comment]
Workaround: No surprise given the error message but, once I added more memory to machine 1 (running Helm v`3.2.1`) (from 2GB RAM to 4 GB RAM), the error went away -- it still took ~1 minute 12 seconds, but eventually the problematic repo got added successfully.

**Comment by bacongobbler** [comment]
Glad to hear you've found a workaround.

Have you tried modifying the helm-ram-usage project I mentioned earlier to determine what could be the cause of the huge memory footprint?

https://github.com/helm/helm/issues/9931#issuecomment-877467382

Without a way to test this locally I'm afraid all we can do is help point you in the right direction. But if we can somehow determine where the memory leak may be coming from, we could potentially create an action plan either in the form of a ticket upstream or a bug fix.

**Comment by bacongobbler** [comment]
Updated the title to reflect the (more likely) issue at hand

**Comment by pranavmarla** [comment]
Thanks for updating the title! Kept slipping my mind to do that.

> Have you tried modifying the helm-ram-usage project I mentioned earlier to determine what could be the cause of the huge memory footprint?
No, haven't had a chance yet. Once I do, I'll make sure to post my findings here.

**Comment by thernstig** [comment]
Go support this if you care: https://github.com/helm/helm/issues/10542

**Comment by wurstbrot** [comment]
Hi,
because I am having the OOM error with an air-gapped artifactory.
I configured helm and helmv3. Now, I configured helmv3 only and disabled "helm" without oom! Woohoo.

helmv3 is better implemented without the need to fetch/parse the index.yaml in the way helm is doing it.
