### ISSUE TITLE
A feature to set values from multiple values.yaml files with `-f` option.

### ISSUE THREAD

**Issue by JhoLee** [helm/helm#9932]
Suggest a feature to set values from multiple values.yaml files with `-f` option.

When I use `-f` to directory, then helm says:
```
$ helm template . -f values
Error: read values/: is a directory
```

I'm using ArgoCD and I wanted to separate custom-values.yaml to multiple files. - To shorten the custom-values.yaml
But when I add a new custom-values file, I had to add it to ArgoCD cause Helm3 doesn't support "Setting values from directory".

This feature will be very useful to me and other guys like me! 

Thank you.

**Comment by marckhouzam** [comment]
@JhoLee you can use the `-f` flag multiple times so that you can use multiple `yaml` configuration files.

Is that enough for you or do you really need to point to a directory?

**Comment by JhoLee** [comment]
@marckhouzam  Yes, I'm using that. But I created a app with many sub-chart, and I wanted to add sub-charts continuously with a new custom-values.yaml for them. - to shorten those custom-values.yaml files.

**Comment by JhoLee** [comment]
Any updates?
