### ISSUE TITLE
Authentication to Artifactory fails in helm v3.6.2 but not in helm v3.6.0

### ISSUE THREAD

**Issue by jaredbischof** [helm/helm#9935]
I followed the same steps (listed below) to install a helm chart to AKS from Artifactory. With version 3.6.2, I receive an auth error but with version 3.6.0 the chart installs without error. Please note that I've replaced the username, password, URLs and chart names with placeholders as this is a private project.

```
helm repo add <chart-name> <url> --username <username> --password '<password>'
helm repo update
helm install <name> <chart-name> --debug
```

Error when installing with version 3.6.2:
```
install.go:173: [debug] Original chart version: ""
Error: failed to fetch <artifactory-url> : 401 Unauthorized
helm.go:81: [debug] failed to fetch <artifactory-url> : 401 Unauthorized
helm.sh/helm/v3/pkg/getter.(*HTTPGetter).get
	helm.sh/helm/v3/pkg/getter/httpgetter.go:90
helm.sh/helm/v3/pkg/getter.(*HTTPGetter).Get
	helm.sh/helm/v3/pkg/getter/httpgetter.go:42
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo
	helm.sh/helm/v3/pkg/downloader/chart_downloader.go:99
helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart
	helm.sh/helm/v3/pkg/action/install.go:704
main.runInstall
	helm.sh/helm/v3/cmd/helm/install.go:185
main.newInstallCmd.func2
	helm.sh/helm/v3/cmd/helm/install.go:120
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.1.3/command.go:852
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.1.3/command.go:960
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.1.3/command.go:897
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:80
runtime.main
	runtime/proc.go:225
runtime.goexit
	runtime/asm_amd64.s:1371
```

Output of `helm version`:
Working version:
version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}
Version with error:
version.BuildInfo{Version:"v3.6.2", GitCommit:"ee407bdf364942bcb8e8c665f82e15aa28009b71", GitTreeState:"clean", GoVersion:"go1.16.5"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"6c3860292226c4a349df8e901e1af270d83b5067", GitTreeState:"clean", BuildDate:"2021-03-10T23:40:48Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

**Comment by bacongobbler** [comment]
Please see the Helm 3.6.1 release notes as well as the accompanying security advisory for more details. In some cases you will need to add the `--pass-credentials` flag for certain repositories (like Artifactory) to work.

https://github.com/helm/helm/releases/tag/v3.6.1
https://github.com/helm/helm/security/advisories/GHSA-56hp-xqp3-w2jf

Please also see https://github.com/helm/helm/issues/9777 for more details.

Thanks.
