### ISSUE TITLE
How can I print the chart version specified in Chart.yaml

### ISSUE THREAD

**Issue by chandankumar-kr** [helm/helm#9936]
Output of `helm version`:

`version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"dirty", GoVersion:"go1.16.3"}`

Output of `kubectl version`:

`Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Minikube

------------
`helm inspect chart . ` is printing all the detail with version, but didn't found a way to print just the version which is specified in the Chart.yaml

**Comment by bacongobbler** [comment]
not currently possible. We have `--output json` flags for other commands other than `helm show chart` which used be passed to `jq` to parse specific fields.

Pull requests welcome.

**Comment by chandankumar-kr** [comment]
Thanks, @bacongobbler for the info, I'll raise the pull request soon for the `--output` flag support in `helm show`

**Comment by chandankumar-kr** [comment]
@bacongobbler Do we wanted to add `--output` flag support only for `helm show chart` or the parent one i.e. `helm show` ?

**Comment by bacongobbler** [comment]
Sorry, when I meant “helm show” I meant for all of its children commands that made sense. I.e `helm show chart” or “helm show all”.

**Comment by chandankumar-kr** [comment]
okay! I'm thinking of adding the output filter for `chart`, `values` because I don't think it is feasible for `readme` and `all` also for `values` I'm not sure how table format will look like.

**Comment by chandankumar4** [comment]
@bacongobbler I have the feature ready for chart, Just waiting for your opinion on the above statement :)

**Comment by dchandekstark** [comment]
Since the chart version is such an essential piece of information, making it easy to retrieve without dependencies seems like a good thing.

**Comment by rpressiani** [comment]
I'm trying to do something similar since I need the latest chart version in a CI/CD pipeline. Although this is not doable with helm commands as of right now, I was able to use this workaround:
```
helm show chart <CHART> | awk '/version/ {print $2}'
```
Hope this helps!

**Comment by rogeriovalente** [comment]
> [rpressiani](/rpressiani)

Yes! This helped.
But if a dependency is declared in chart the output shows all versions declared.
For example.
My chart's version is the "1.0.0" value and has a postgresql's chart version 13.2.7 dependency declared.
The command output shows both version numbers: 
13.2.7.
1.0.0

I found the command below as solution for this scenario.

`helm show chart . | grep -E "^version:" | awk '{print $2}'`

This shows only your chart's version.

**Comment by melroyvandenberg** [comment]
> Thanks, [@bacongobbler](https://github.com/bacongobbler) for the info, I'll raise the pull request soon for the `--output` flag support in `helm show`

would still be a cool if we would have a `--output` flag.
