### ISSUE TITLE
helm 3 install - HA sum of helm-v3.6.3-linux-amd64.tar.gz does not match

### ISSUE THREAD

**Issue by chudanie** [helm/helm#9943]
Obtain get_helm (version 3) script from https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 and grant execution permission.  The installation of helm fails upon running it ("Verifying checksum... SHA sum of /tmp/helm-installer-96l2g6/helm-v3.6.3-linux-amd64.tar.gz does not match. Aborting.").
```
# curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
# chmod 700 get_helm.sh
# ./get_helm.sh
Helm v3.6.3 is available. Changing from version v3.4.2.
Downloading https://get.helm.sh/helm-v3.6.3-linux-amd64.tar.gz
Verifying checksum... SHA sum of /tmp/helm-installer-96l2g6/helm-v3.6.3-linux-amd64.tar.gz does not match. Aborting.
Failed to install helm
        For support, go to https://github.com/helm/helm.
```

**Comment by hickeyma** [comment]
Hey @chudanie. It might be a flake as it seems to be working for me:

```console
$ ./get_helm.sh

Helm v3.6.3 is available. Changing from version v3.3.1.
Downloading https://get.helm.sh/helm-v3.6.3-linux-amd64.tar.gz
Verifying checksum... Done.
Preparing to install helm into /usr/local/bin
helm installed into /usr/local/bin/helm
```

Do you mind trying again?

**Comment by bacongobbler** [comment]
Slight hiccup during the release process. All seems good now or we would’ve heard more reports. Thanks!

**Comment by maxisam** [comment]
it happens again 

Downloading https://get.helm.sh/helm-3.6.3-linux-amd64.tar.gz
Verifying checksum... SHA sum of /tmp/helm-installer-W3uGLM/helm-3.6.3-linux-amd64.tar.gz does not match. Aborting.
Failed to install helm with the arguments provided: -v 3.6.3

**Comment by maxisam** [comment]
@bacongobbler  thx!
