### ISSUE TITLE
bug: version is NOT optional anymore for file://.. subcharts

### ISSUE THREAD

**Issue by tamalsaha** [helm/helm#9944]
Output of `helm version`: v3.6.3

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

PR: https://github.com/helm/helm/pull/9736/files has introduced a change that is breaking `helm dep up` command. In prior release of helm, `version` is optional for sub charts loaded from local filesystem `file://`. So, when the version is not set, https://github.com/helm/helm/pull/9736/files#diff-ff3593e6a6cb00f927118c829760e054ccca7686eae492f9f4f18b9b851a9a20R60-R63 line is throwing error `"dependency %q has an invalid version/constraint format"`. 

I think a possible solution will be to set the constraint to `*` is it was not set and dependency was loaded from `file://` .

**Comment by tamalsaha** [comment]
cc: @mattfarina @technosophos @cndoit18

**Comment by cndoit18** [comment]
Oh, sorry. Let me fix it.

**Comment by mattfarina** [comment]
I'm marking this as a bug but also bringing it up for discussion in the helm dev call. The [version field is documented as non-optional ](https://helm.sh/docs/topics/charts/#the-chartyaml-file)so it warrants discussion.

**Comment by mattfarina** [comment]
We discussed this on the Helm dev call. The version field is meant to be non-optional. That `file://` didn't require it before was a bug. The version field is important, even for `file://`. For example, what if the version specified is `2.0.0` and the archive being pointed at is `1.2.3`. There is an issue and this simple check will notice it.

The details for that discussion are the last item from this weeks developer call.

**Comment by tamalsaha** [comment]
(1) Could Helm follow the Go module replace syntax where when local file system is referenced, Go does not bother with version number (commit hash)? I think for local sub charts, this makes a lot of sense. When I am doing development work, this is an extra hassle.

(2) If version must be given, are we be able to set it to `version: "*"` to mean, take whatever is in the local folder?

(3) Lastly, it is too late to change the behavior in v3.x.x . At this point, every bug is a feature for v3 train, if we are following semver.

**Comment by mattfarina** [comment]
> (1) Could Helm follow the Go module replace syntax where when local file system is referenced, Go does not bother with version number (commit hash)? I think for local sub charts, this makes a lot of sense. When I am doing development work, this is an extra hassle.

There is a difference between Helm charts and Go modules. For example, with a Helm chart the chart MUST be pulled into the parent charts `charts` directory before it can be used. It doesn't pick it up from the existing location on the filesystem. Go, on the other hand, will pick it up from the location on the file system.

A change like this would be a definite change to charts and something to discuss for charts apiVersion v3, I think.

> (2) If version must be given, are we be able to set it to version: "*" to mean, take whatever is in the local folder?

That should work, yes.

> (3) Lastly, it is too late to change the behavior in v3.x.x . At this point, every bug is a feature for v3 train, if we are following semver.

Figuring out if something like this is a bug that could be changed or a bug that's a behavior in place well enough that you shouldn't touch it until a major version change isn't always easy to work out.

Note, there was some consistency that the lack of version checking was a bug. If someone wants to try to sway us on that they'll need to make a convincing argument which is possible.

In this case we assumed it was a bug that should have been fixed. With some bugs folks will debate this and that's ok.

**Comment by tamalsaha** [comment]
> (2) If version must be given, are we be able to set it to version: "*" to mean, take whatever is in the local folder?

> That should work, yes.

This is not working. I am getting an error like `Error: can't get a valid version for repositories kubevault-crds, kubevault-catalog, kubevault-operator, csi-vault. Try changing the version constraint in Chart.yaml`

My chart is here: https://github.com/kubevault/installer/tree/master/charts/kubevault

**Comment by cndoit18** [comment]
> > (2) If version must be given, are we be able to set it to version: "*" to mean, take whatever is in the local folder?
> 
> > That should work, yes.
> 
> This is not working. I am getting an error like `Error: can't get a valid version for repositories kubevault-crds, kubevault-catalog, kubevault-operator, csi-vault. Try changing the version constraint in Chart.yaml`
> 
> My chart is here: https://github.com/kubevault/installer/tree/master/charts/kubevault

I checked this situation and it is not caused by the version, it is another bug
