### ISSUE TITLE
Is there a way to do "helm dependency update" from go sdk of helm v3

### ISSUE THREAD

**Issue by yogesh-reddy** [helm/helm#9947]
`**<!--**` If you need help or think you have found a bug, please help us with your issue by entering the following information (otherwise you can delete this text): -->
I was trying to install some charts from the local folder it does not have charts folder (dependencies ) I was using go sdk to install the charts, so when I try to install it shows installed success but there are no resources getting deployed. So when I use `helm dependency update` and download dependencies in that folder manually then go code deploys the charts. so is there a way to download dependencies using go sdk ?

Thanks in advance.

**Comment by mattfarina** [comment]
It is possible to download the dependencies. A chart, at install time, is expected to have all the dependencies present.

The [download manager](https://github.com/helm/helm/blob/6a3daaa7aa5b89a150042cadcbe869b477bb62a1/cmd/helm/install.go#L218-L230) provides a way to download dependencies.

**Comment by yogesh-reddy** [comment]
I tried the above-mentioned way my `client.DependencyUpdate  ` bool variable is false so it skipping the download part so do I need to manually set it to true? or is there any mistake in my code if client.DependencyUpdate is false, and I tried setting it to true but I got an error while running ` man.Update()` it gives me invalid memory error :invalid memory address or nil pointer dereference

**Comment by yogesh-reddy** [comment]
The issue got resolved by Using Discard on io.Writer on which all Write calls succeed without doing anything. But don't know why writing into io.writer directly fails.

it actually fails at this point in updating repositories. `fmt.Fprintln(m.Out, "Hang tight while we grab the latest from your chart repositories...")`
Error:  `fmt.Fprintln(0x0, 0x0, 0xc0008d0f00, 0x1, 0x1, 0x7e, 0x5, 0x0)
        /usr/local/go/src/fmt/print.go:265 +0x5d
helm.sh/helm/v3/pkg/downloader.(*Manager).UpdateRepositories(0xc000333680, 0xc0008c4540, 0xc000713d70)
        /Users/katreddyveey/go/pkg/mod/helm.sh/helm/v3@v3.6.0/pkg/downloader/manager.go:635 +0xe5`
