### ISSUE TITLE
Get resource versions with `helm template` 

### ISSUE THREAD

**Issue by tommyknows** [helm/helm#9951]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.6.1", GitCommit:"61d8e8c4a6f95540c15c6a65f36a6dd0a45e7a2f", GitTreeState:"dirty", GoVersion:"go1.16.5"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): n/a

----
As raised in other issues already (for example #9088), a `helm template` does not populate the `.Capabilities.APIVersions` with the actual resources, but only with API Groups. 

This is an issue for users of local rendering, for example ArgoCD (https://github.com/argoproj/argo-cd/issues/6268) and has caused troubles in various upstream charts that rely on the capabilities feature (example https://github.com/traefik/traefik-helm-chart/issues/309).

The current code seems to simply ask the registered scheme for all groups https://github.com/helm/helm/blob/6a3daaa7aa5b89a150042cadcbe869b477bb62a1/pkg/chartutil/capabilities.go#L120 however I believe that it would be possible to also grab all resources with it too.

"All resources" is a bit much, as I figured out during testing, but we can filter some unwanted types & API groups out with a bit of code. As a small example:

<details>

```go
package main

import (
        "fmt"
        "strings"

        "k8s.io/apimachinery/pkg/runtime/schema"
        "k8s.io/client-go/kubernetes/scheme"

        apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
        apiextensionsv1beta1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1"
)

func main() {
        // We should register the built in extension APIs as well so CRDs are
        // supported in the default version set. This has caused problems with `helm
        // template` in the past, so let's be safe
        apiextensionsv1beta1.AddToScheme(scheme.Scheme)
        apiextensionsv1.AddToScheme(scheme.Scheme)

        allTypes := scheme.Scheme.AllKnownTypes()
        preferredVersions := scheme.Scheme.PreferredVersionAllGroups()
        for gvk := range allTypes {
                if contains(preferredVersions, gvk.GroupVersion()) && !isListType(gvk.Kind) && !isIgnored(gvk.Kind) {
                        fmt.Println(gvk.GroupVersion().String() + "/" + gvk.Kind)
                }
        }
}

func isListType(typ string) bool {
        return strings.HasSuffix(typ, "List")
}

var ignoredTypes = []string{"CreateOptions", "GetOptions", "ListOptions", "PatchOptions", "DeleteOptions", "UpdateOptions", "WatchEvent"}

func isIgnored(typ string) bool {
        for _, ign := range ignoredTypes {
                if typ == ign {
                        return true
                }
        }
        return false
}

func contains(gvs []schema.GroupVersion, gv schema.GroupVersion) bool {
        for _, ggv := range gvs {
                if ggv.String() == gv.String() {
                        return true
                }
        }
        return false
}
```
</details>

This returns a list of all resources that are registered by default at the given version:

<details>

```
apps/v1/Deployment
extensions/v1beta1/Deployment
rbac.authorization.k8s.io/v1/RoleBinding
apps/v1/ControllerRevision
networking.k8s.io/v1/IngressClass
autoscaling/v1/Scale
v1/ServiceAccount
v1/PodExecOptions
networking.k8s.io/v1/Ingress
extensions/v1beta1/DaemonSet
extensions/v1beta1/Ingress
certificates.k8s.io/v1/CertificateSigningRequest
v1/ServiceProxyOptions
rbac.authorization.k8s.io/v1/ClusterRole
v1/Node
v1/Binding
v1/Pod
v1/PodProxyOptions
rbac.authorization.k8s.io/v1/ClusterRoleBinding
rbac.authorization.k8s.io/v1/Role
extensions/v1beta1/NetworkPolicy
v1/Status
extensions/v1beta1/Scale
v1/SerializedReference
events.k8s.io/v1/Event
apiextensions.k8s.io/v1beta1/ConversionReview
authorization.k8s.io/v1/LocalSubjectAccessReview
coordination.k8s.io/v1beta1/Lease
v1/APIVersions
storage.k8s.io/v1beta1/StorageClass
autoscaling/v1/HorizontalPodAutoscaler
discovery.k8s.io/v1/EndpointSlice
storage.k8s.io/v1beta1/CSIDriver
v1/PersistentVolumeClaim
v1/PodTemplate
v1/Event
v1/PodPortForwardOptions
v1/RangeAllocation
authorization.k8s.io/v1/SelfSubjectAccessReview
v1/ResourceQuota
extensions/v1beta1/DeploymentRollback
flowcontrol.apiserver.k8s.io/v1alpha1/PriorityLevelConfiguration
v1/ComponentStatus
v1/Namespace
v1/PodLogOptions
admissionregistration.k8s.io/v1/ValidatingWebhookConfiguration
scheduling.k8s.io/v1alpha1/PriorityClass
v1/ConfigMap
v1/APIGroup
v1/LimitRange
admissionregistration.k8s.io/v1/MutatingWebhookConfiguration
storage.k8s.io/v1beta1/CSINode
storage.k8s.io/v1beta1/CSIStorageCapacity
internal.apiserver.k8s.io/v1alpha1/StorageVersion
authentication.k8s.io/v1/TokenRequest
v1/PodAttachOptions
apps/v1/StatefulSet
batch/v1/CronJob
batch/v1/Job
v1/EphemeralContainers
apiextensions.k8s.io/v1beta1/CustomResourceDefinition
storage.k8s.io/v1beta1/VolumeAttachment
authentication.k8s.io/v1/TokenReview
v1/Secret
v1/PersistentVolume
v1/Endpoints
extensions/v1beta1/PodSecurityPolicy
authorization.k8s.io/v1/SubjectAccessReview
v1/Service
authorization.k8s.io/v1/SelfSubjectRulesReview
apps/v1/ReplicaSet
policy/v1/PodDisruptionBudget
v1/NodeProxyOptions
v1/PodStatusResult
apps/v1/DaemonSet
extensions/v1beta1/ReplicaSet
node.k8s.io/v1/RuntimeClass
v1/ReplicationController
networking.k8s.io/v1/NetworkPolicy
flowcontrol.apiserver.k8s.io/v1alpha1/FlowSchema
```

</details>

There's some types in there that might need manual exclusion, for example `internal.apiserver.k8s.io/v1alpha1/StorageVersion`. This could be considered, I don't know what the impact of leaving this in would be.

I'm happy to submit a PR to include these changes, but wanted to address the idea first. What do you think, would it be possible to include this functionality?

**Comment by bacongobbler** [comment]
Have you tried using the `--validate` flag?

**Comment by tommyknows** [comment]
I know about the `--validate` flag, but this doesn't work for environments which are not connected to a cluster, which is the case for ArgoCD:

> The manifests are being rendered by the argocd-repo-server, and this component does not (and should not) have connection permissions to any Kubernetes cluster. 
[Source](https://github.com/argoproj/argo-cd/issues/5833#issuecomment-814324025)

I also think that it's weird that a `helm template` only populates the API versions, but not resources. Why not do both, if you have to do one already?

**Comment by sathieu** [comment]
@tommyknows Could you submit a PR for this?

**Comment by tommyknows** [comment]
Just started working on this and have an implementation question:
the only caller / user of the `DefaultVersionSet` appears to be `pkg/action` here: https://github.com/helm/helm/blob/6a3daaa7aa5b89a150042cadcbe869b477bb62a1/pkg/action/action.go#L310

The unit test to this function (https://github.com/helm/helm/blob/6a3daaa7aa5b89a150042cadcbe869b477bb62a1/pkg/action/action_test.go#L307) uses a fake clientset to get these results. Now the interesting thing is that the method I've described above returns the exact same result set as the fakeclientset does.

So instead of constructing this list ourselves, we could just fall back to the fake clientset.

My current version looks like this, in `capabilities.go`:
<details>

```go
func allKnownVersions() VersionSet {
        // We should register the built in extension APIs as well so CRDs are
        // supported in the default version set. This has caused problems with `helm
        // template` in the past, so let's be safe
        apiextensionsv1beta1.AddToScheme(scheme.Scheme)
        apiextensionsv1.AddToScheme(scheme.Scheme)

        versionMap := make(map[string]struct{})
        preferredVersions := scheme.Scheme.PreferredVersionAllGroups()
        for gvk := range scheme.Scheme.AllKnownTypes() {
                if isIgnored(gvk.Kind) || isListType(gvk.Kind) || !contains(preferredVersions, gvk.GroupVersion()) {
                        continue
                }

                // add the main group version
                versionMap[gvk.GroupVersion().String()] = struct{}{}

                // and add it with the kind
                versionMap[path.Join(gvk.GroupVersion().String(), gvk.Kind)] = struct{}{}
        }

        versions := make(VersionSet, 0, len(versionMap))
        for k := range versionMap {
                versions = append(versions, k)
        }

        return versions
}

func isListType(typ string) bool {
        return strings.HasSuffix(typ, "List")
}

// ignoredKinds is a list of kinds that are present in every group version and
// should be ignored when building the allKnownVersions set.
var ignoredKinds = []string{
        "CreateOptions",
        "GetOptions",
        "ListOptions",
        "PatchOptions",
        "DeleteOptions",
        "UpdateOptions",
        "WatchEvent",
}

func isIgnored(typ string) bool {
        for _, ign := range ignoredKinds {
                if typ == ign {
                        return true
                }
        }
        return false
}

func contains(gvs []schema.GroupVersion, gv schema.GroupVersion) bool {
        for _, ggv := range gvs {
                if ggv.String() == gv.String() {
                        return true
                }
        }
        return false
}
```
</details>

Instead, we could directly patch `pkg/action/action.go`, 
<details>
```go
// GetVersionSet retrieves a set of available k8s API versions
func GetVersionSet(client discovery.ServerResourcesInterface) (chartutil.VersionSet, error) {
        groups, resources, err := client.ServerGroupsAndResources()
        if err != nil && !discovery.IsGroupDiscoveryFailedError(err) {
                groups, resources, err = fakeclientset.NewSimpleClientset().Discovery().ServerGroupsAndResources()
                if err != nil {
                        return ???, errors.Wrap(err, "could not get apiVersions from Kubernetes")
                }
        }

        // FIXME: The Kubernetes test fixture for cli appears to always return nil
        // for calls to Discovery().ServerGroupsAndResources(). So in this case, we
        // return the default API list. This is also a safe value to return in any
        // other odd-ball case.
        if len(groups) == 0 && len(resources) == 0 {
                return chartutil.DefaultVersionSet, nil
        }

        versionMap := make(map[string]interface{})
        versions := []string{}

        // Extract the groups
        for _, g := range groups {
                for _, gv := range g.Versions {
                        versionMap[gv.GroupVersion] = struct{}{}
                }
        }

        // Extract the resources
        var id string
        var ok bool
        for _, r := range resources {
                for _, rl := range r.APIResources {

                        // A Kind at a GroupVersion can show up more than once. We only want
                        // it displayed once in the final output.
                        id = path.Join(r.GroupVersion, rl.Kind)
                        if _, ok = versionMap[id]; !ok {
                                versionMap[id] = struct{}{}
                        }
                }
        }

        // Convert to a form that NewVersionSet can use
        for k := range versionMap {
                versions = append(versions, k)
        }

        return chartutil.VersionSet(versions), nil
}
```
</details>
The only question is if the fakeclientset's `Discovery().ServerGroupsAndResources()` returns an error, what do we return to the caller? I don't know in which case it would return an error at all, and if it's possible to just return a zero-ed VersionSet in this case, or if we still need a fallback anyways.

If we don't, we could remove the whole `DefaultVersionSet` from the repo (ignoring that this would be a breaking change according to semver, but I don't see any other usages in the helm/helm repo). 

What do you think?

**Comment by sathieu** [comment]
Hi @tommyknows, have you read the discussion [here](https://github.com/helm/helm/pull/10108#issuecomment-915015711)? Could you propose a PR with hardcoded APIversions for each major Kubernetes versions?

(ping @Ragatzino)

**Comment by tommyknows** [comment]
I could hardcode the API Versions, though this should probably be done through some kind of code generation. I don't expect that anyone wants to update that hardcoded list for every new kubernetes release.

also, I wouldn't know exactly how to get all API versions per kubernetes major version (be it automated or by hand), spinning up an API server for each version and extracting the versionset seems like a ton of work :-) 

wdyt?

**Comment by sathieu** [comment]
@tommyknows Helm v2 was already generating this. No need for a K8s server, but you need the k8s libs for each version.

Code was in [pkg/chartutil/generator/capabilities_default_versions_generate.go](https://github.com/helm/helm/blob/v2.17.0/pkg/chartutil/generator/capabilities_default_versions_generate.go).

**Comment by bacongobbler** [comment]
> I could hardcode the API Versions

> Helm v2 was already generating this.

We did that for Helm 2, but only as a crutch until Kubernetes had an API to fetch any known GroupVersionKinds (GVKs). This can now be fetched through their client libraries, though the limitation being that it only represents the available GVKs to whichever version of Kubernetes you are compiling against (which in our case [is 1.22](https://github.com/helm/helm/blob/9fafb4ad6811afb017cc464b630be2ff8390ac63/go.mod#L37-L44)).

https://github.com/helm/helm/blob/eeac83883cb4014fe60267ec6373570374ce770b/pkg/chartutil/capabilities.go#L38

I do not feel comfortable reintroducing that piece of code and maintaining a list of all possible GVKs known to Kubernetes... And by extension any third party projects using their own custom CRDs. But feel free to re-use what's already available in `pkg/chartutil`.

**Comment by tommyknows** [comment]
Thanks @bacongobbler for your insights. Without being too familiar with Helm or it's codebase, personally I would also rather not hardcode these versions and instead just limit it to the given API version which Helm is compiled against.

As you seem to agree with this, what do you think about the situation I presented in my earlier comment https://github.com/helm/helm/issues/9951#issuecomment-915826696?
