### ISSUE TITLE
the `--devel` flag is unusable

### ISSUE THREAD

**Issue by XSAM** [helm/helm#9955]
Output of `helm version`: 

```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"dirty", GoVersion:"go1.16.5"}
```

---

Since `helm` will refuse to use a repo with an invalid version and the `--devel` flag will use version `>0.0.0-0`, which is not a valid Semver 2 name, it makes the `--devel` flag unusable.

I suggest the `--devel` flag should use a valid Semver 2 name like `0.0.0-0` instead of `>0.0.0-0`.

I'd like to address this, feel free to assign this to me.

**Comment by hickeyma** [comment]
@XSAM To try and better understand you request, do you mind giving an example of how you are using `devel` flag and what is not working when using it?

**Comment by XSAM** [comment]
@hickeyma Sure. Here is the example.

I like to use the `devel` flag when running `helm upgrade`. Because of `devel` flag will force helm to use version `>0.0.0-0`, so I need to publish a version `>0.0.0-0` first.

```sh
$ helm push foo chartmuseum -v ">0.0.0-0" -f
```

The thing goes well until I run `helm repo update` try to update this repo.

```sh
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
index.go:339: skipping loading invalid entry for chart "foo" ">0.0.0-0" from https://charts.foo.io: validation: chart.metadata.version ">0.0.0-0" is invalid
```

`helm` refuses to update a version that is required for the `devel` flag. Since version `>0.0.0-0` is not possible to import by `helm`, there is no way to use the `devel` flag.

**Comment by hickeyma** [comment]
@XSAM Can you try the following: `helm push foo chartmuseum -v "0.0.1-1" -f` ? 

Then the `repo update`.

**Comment by XSAM** [comment]
@hickeyma I can normally fetch a Semver 2 version like `0.0.1-1` by `helm`. But the point is to enable the `devel` flag we have to use `>0.0.0-0` version.

**Comment by hickeyma** [comment]
Don't think so. Just pass the version when you are installing/upgrading etc with the flag: `--devel 0.0.1-1` or whatever the dev version is.

**Comment by XSAM** [comment]
IIUC, `devel` is a bool type flag that can only accept `true` or `false`.

https://github.com/helm/helm/blob/a499b4b179307c267bdf3ec49b880e3dbd2a5591/cmd/helm/pull.go#L86

And `devel` use version `>0.0.0-0`, which is a hard-coded value that can't be changed.

https://github.com/helm/helm/blob/a499b4b179307c267bdf3ec49b880e3dbd2a5591/cmd/helm/show.go#L174-L177

**Comment by bacongobbler** [comment]
The version flag accepts a version range specifier. The specifier when using the devel flag means “match any version greater than v0.0.0-0”. It is not looking for an exact version number called “<0.0.0-0”.

https://helm.sh/docs/chart_template_guide/function_list/#hyphen-range-comparisons

**Comment by XSAM** [comment]
Thanks for the detailed reply! @hickeyma @bacongobbler 

I didn't realize `>0.0.0-0` is a version range specifier (Sorry about that). After reading some codes, I've noticed helm will use the biggest version from that range. The functionality of `devel` seems good.

Closing it.
