### ISSUE TITLE
Adopting resources into a new release leads to unexpected merge behaviour

### ISSUE THREAD

**Issue by mark007** [helm/helm#9958]
Output of `helm version`: version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Reproducable on AKS and GKE

I am trying to make the following use case successful. It is to move objects from one old helm release to another new helm release, followed by subsequent upgrades of that new helm release. I have been using the feature outline on the following page.

https://github.com/helm/helm/pull/7649

This feature involves annotating and labelling objects that you wish to 'move' to a new helm release.

`    metadata:
      annotations:
        meta.helm.sh/release-name: <release>
        meta.helm.sh/release-namespace: <namespace>
      labels:
        app.kubernetes.io/managed-by: Helm`

This feature allows me to do the following

1) Install an old helm chart, into an old helm release (release1)
2) Annotate/label some of the objects that are in that release, with the name of a new / target release (release2)
3) Perform a helm install of the new target chart into the new / target (release2) and see it not throw errors that the objects exist.

This does work. However I have spotted one issue, that is causing this to not work on certain objects. I noticed an issue when running through these steps on a deployment, whos container had changed its liveness probe from using a httpGet to using a exec. Only one of these can be used at any time, so this is expected to work. In the old chart/helm release, its using httpGet. In the new chart / release its using exec. However after running through this upgrade procedure, helm is somehow leaving both httpGet and the exec blocks in the resulting object.

To me this is not desirable, as I want whatever is in the new/target chart to be exactly reflected in the cluster, not some merge of the old and new manifests. Other users seemed to have noticed this issue, for example on this comment.

https://github.com/helm/helm/issues/6561#issuecomment-687382740

I have reproduced this with a very small example. If we create two charts, the old chart and the new chart.

Within the old chart, put a small Service object like below.

`apiVersion: v1
kind: Service
metadata:
  name: myservice
  labels:
    labela: a
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    a: b`

helm install that chart into a namespace, giving it a release name of release1.

Now prepare the second helm chart, with the very same Service object, however change the label from labela, to labelb as follows.

`apiVersion: v1
kind: Service
metadata:
  name: myservice
  labels:
    labelb: b
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    a: b`

Now annotate and label the existing Service within the cluster to indicate its going to be part of release2.

Perform a helm install of the new / target chart into release2.

The upgrade will be successful however both labela an labelb will be present. I assume this is not intended as it will of course corrupt many objects in the process. In my case any objects that decided to change liveness probes for example, from using httpGet, to using 'exec', will now have both, and fail to upgrade because of this.

Is this a bug or expected behavior? Any suggestions to get around it are very welcome.

**Comment by hickeyma** [comment]
Hey @jlegrone. You might be best placed to provide some feedback on this?

**Comment by hickeyma** [comment]
I will set to a bug in the meantime.

**Comment by TBBle** [comment]
@marcosdiez I think #2730 is the issue for that functionality.

**Comment by bacongobbler** [comment]
Closing in favour of #2730. That issue encompasses any discussion around introducing resource adoption as a helper command.

At this time, adopting existing resources into a release is not a workflow we support.
