### ISSUE TITLE
helm3 lint error on apiVersion and version of 1.0 (without quotes) should be reduced to warning or info

### ISSUE THREAD

**Issue by nngo** [helm/helm#9960]
helm v3.5.3

I have `Chart.yaml` with `appVersion: 1.0` and `version: 1.0` in it that fails the `helm3 lint` check, which outputs the following ERRORS:

```
[ERROR] Chart.yaml: version should be of type string but it's of type float64
[ERROR] Chart.yaml: appVersion should be of type string but it's of type float64

Error: 1 chart(s) linted, 1 chart(s) failed.
```

This has worked fine in helm v2 and the `helm3 package` still works without issue or warning here. I consider this a regression in behavior. Lots of Helm Charts I have seen have `version` and `appVersion` specified without quotes. Per the docs at https://helm.sh/docs/topics/charts/#the-appversion-field it says "This [appVersion] is informational, and has no impact on chart version calculations. Wrapping the version in quotes is highly recommended. It forces the YAML parser to treat the version number as a string." 

Additionally the docs for `helm3 lint` says it will emit [ERROR] messages for "things that will cause the chart to fail installation" and if it encounters issues that break with convention or recommendation, it will emit [WARNING] messages. IMHO this should be a [WARNING] message.

The docs for chart version: https://helm.sh/docs/topics/charts/#charts-and-versioning even gives examples of the version field without quotes, e.g. `For example, an nginx chart whose version field is set to version: 1.2.3 will be named:` and most string fields in the Chart.yaml are NOT quoted (e.g. `apiVersion: v1`, `kind: ReplicationController`, `namespace: deis`, etc.)

I suggest downgrading this ERROR message to a WARNING or INFO message and allowing the lint check to pass.

**Comment by bacongobbler** [comment]
You `appVersion` should have the value `1`, not `1.0`.

**Comment by bacongobbler** [comment]
To clarify here, this is a limitation of the YAML parser. If a value is left unquoted, its type is interpreted based on its value. So a `1` is an integer, `1.0` is a float, `100e10` is also a float (scientific notation), `NO` is a boolean.

This is not something we can control. The structure expects a string, and instead it received an integer.

**Comment by nngo** [comment]
> 
> 
> You `appVersion` should have the value `v1`, not `1.0`.

`appVersion` can be any application version string, I get the lint error of `appVersion should be of type string but it's of type float64` with either `1` or `1.0`.
Again, I would like to stress that the Chart is still installable via helm2 and helm3 without any issue (so I still believe this should be reduced to WARNING level msg vs ERROR during the lint checker.
