### ISSUE TITLE
How to only execute the given templates with helm v3.6.1

### ISSUE THREAD

**Issue by Thor-wl** [helm/helm#9964]
Output of `helm version`:
v3.6.1
Output of `kubectl version`:
v1.19.3
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
None

I alway used helm v2.13.0 and the following command worked well.
```
helm template [path-to-chart] --namespace [my-ns] --name-tempate [template-name] --set [my-values]
-x [path-to-tempate-1]
-x [path-to-tempate-2]
...
```
Recently I upgrades helm to v3.6.1 and `-x` does not work. After a tour of explore, I found that it seems not support this function any more after execute `helm template -h`. Anyone can help? THX.

**Comment by bacongobbler** [comment]
The —execute or -x flag was renamed as -s or —show-only for Helm 3.

https://github.com/helm/helm/blob/main/cmd/helm/template.go#L177

**Comment by hickeyma** [comment]
@Thor-wl You can use the ``--help` flag on any of the commands and that should help. If it is unclear then raise an issue to provide better description.

**Comment by Thor-wl** [comment]
> The —execute or -x flag was renamed as -s or —show-only for Helm 3.
> 
> https://github.com/helm/helm/blob/main/cmd/helm/template.go#L177

Thank you very much! I've tried `-s` but it throwed errors as follows:
https://github.com/volcano-sh/volcano/issues/1640.
Let me try `--show-only`.

**Comment by Thor-wl** [comment]
> @Thor-wl You can use the ``--help` flag on any of the commands and that should help. If it is unclear then raise an issue to provide better description.

Yes, I've tried but not got a clear idea about which flag to use. I've tried again. THX.

**Comment by Thor-wl** [comment]
I'm not sure whether it is a bug for v3.6.1. As what I tested, if execute `helm template` with only `--show-only` flag, everything goes well. But if I execute the following command, it doesn't work.
```
${HELM_BIN_DIR}/helm template ${VK_ROOT}/installer/helm/chart/volcano --namespace volcano-system \
      --name-template volcano --set basic.image_tag_version=${VOLCANO_IMAGE_TAG} --set basic.crd_version=${CRD_VERSION}\
      -s templates/admission.yaml \
      -s templates/batch_v1alpha1_job.yaml \
      -s templates/bus_v1alpha1_command.yaml \
      -s templates/controllers.yaml \
      -s templates/scheduler.yaml \
      -s templates/scheduling_v1beta1_podgroup.yaml \
      -s templates/scheduling_v1beta1_queue.yaml \
      -s templates/nodeinfo_v1alpha1_numatopologies.yaml \
      >> ${DEPLOYMENT_FILE}
```
The outputs as follows:
![截图](https://user-images.githubusercontent.com/61179420/126733946-1c8ef9f8-6a69-4b3d-a3fe-8f1bdedb6a34.PNG)
