### ISSUE TITLE
Ability to output chart metadata via `helm status`

### ISSUE THREAD

**Issue by seaneagan** [helm/helm#9968]
Currently the chart output gets stripped:
https://github.com/helm/helm/blob/29d273f985306bc508b32455d77894f3b1eb8d4d/cmd/helm/status.go#L70-L73

So the only way to get it is to [access the release secret directly and decode it](https://gist.github.com/DzeryCZ/c4adf39d4a1a99ae6e594a183628eaee) which relies on implementation details, or use the go API which is not very convenient for scripts. 

We have a python tool which in Helm 2 was using the chart metadata (via the grpc API) to determine if the new chart has any changes from the installed one to determine whether an upgrade was needed or not. In helm 3 we can get the new chart metadata via `helm install --dry-run --output json` but cannot get the existing release chart metadata via `helm status --output json`.

Since the chart metadata is already part of the public go API, any reason not to include it in `helm status -o json|yaml`? Since this output is generally for machine consumption, hopefully the output size increase wouldn't be too impactful, but if so could make it opt-in e.g. a `--show-chart` option which for the regular output (without `--output` option) could simply show the chart name/version from Chart.yaml.

**Comment by bacongobbler** [comment]
Chart metadata can be fetched using `helm get manifest`. Are there other parts of the metadata missing from that command?

**Comment by bacongobbler** [comment]
Err, `helm show chart`, actually. `helm show manifest` fetches and displays the fully-rendered templates from a release.

**Comment by seaneagan** [comment]
For diffing we are using the undendered chart metadata (templates, files, dependency metadata, etc) + values overrides. The reason is that the rendered manifests could contain irrelevant diffs due to non-deterministic templates e.g. timestamps or random generated keys, so we are looking to avoid unnecessary upgrades in these cases. Hence `helm get manifest <release>` does not provide this.

As far as getting the new chart info, if `helm show chart <repo>/<chart>` supported a `--output json|yaml` option, that would be nicer than having to do a dry run install e.g. `helm install <release> <repo>/<chart> --dry-run --output json`, but the latter does seem to work ok.

**Comment by bacongobbler** [comment]
Have you looked at other tools like [helm-diff](https://github.com/databus23/helm-diff) to see how they generate diffs?
