### ISSUE TITLE
Linting with subcharts fails if subchart references parent's named template

### ISSUE THREAD

**Issue by jwsomis** [helm/helm#9969]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"dirty", GoVersion:"go1.16.4"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:11:29Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-eks-6b7464", GitCommit:"6b746440c04cb81db4426842b4ae65c3f7035e53", GitTreeState:"clean", BuildDate:"2021-03-19T19:33:03Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  EKS

I have a chart that uses multiple internal and 3rd party subcharts. The internal subcharts reference a named template in the parent chart. This works correctly when deploying the chart, but fails linting.

Running `helm lint <parent-chart> --with-subcharts`
Results in
```
==> Linting <parent-chart>/charts/<child-chart-1>
[INFO] Chart.yaml: icon is recommended

==> Linting <parent-chart>/charts/<child-chart-2>
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: template: <child-chart-2>/templates/deployment.yaml:107:26: executing "<child-chart-2>/templates/deployment.yaml" at <include "<child-chart-2>.initContainers" .>: error calling include: template: child-chart-2/templates/_helpers.tpl:72:4: executing "child-chart-2.initContainers" at <include "init.wait_for_cassandra" .>: error calling include: template: no template "init.wait_for_cassandra" associated with template "gotpl"

==> Linting <parent-chart>/charts/redis-10.7.17.tgz

==> Linting <parent-chart>t/charts/<child-chart-3>
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: template: <child-chart-3>/templates/deployment.yaml:107:26: executing "<child-chart-3>/templates/deployment.yaml" at <include "<child-chart-3>.initContainers" .>: error calling include: template: <child-chart-3>/templates/_helpers.tpl:72:4: executing "<child-chart-3>.initContainers" at <include "init.wait_for_cassandra" .>: error calling include: template: no template "init.wait_for_cassandra" associated with template "gotpl"
```

I understand this would cause the chart to fail on it's own, but this chart won't be called on it's own. How can I reference a parent charts named template and pass linting? Most of the templating lives in the subcharts so can't drop the `--with-subcharts`. Is doing this with subchartsthe wrong way to handle this?

**Comment by hickeyma** [comment]
@jwsomis Would you be able to provide an example chart or how to create one using scaffolding (`helm create`) to test this scenario?

**Comment by jwsomis** [comment]
I'll work on creating something to share that replicates this.
The general structure is
```
├── Chart.yaml
├── README.md
├── charts
│   ├── subchart1                       # Created with `helm create subchart1`
│   ├── subchart2                       # Created with `helm create subchart2`
│   ├── subchart3                       # Created with `helm create subchart3`
│   ├── redis-10.7.17.tgz
│   └── zookeeper-2.1.6.tgz
├── templates
│   ├── NOTES.txt
│   ├── _helpers.tpl
│   ├── _init-containers.yml
│   ├── override.configmap.yml
└── values.yaml
```

The subcharts reference a named template `init.wait_for_cassandra` that lives in the parents `template/init-containers.yml` and linting produces the error above

**Comment by jwsomis** [comment]
This [chart](https://github.com/jwsomis/helm-charts-fails-linting) creates a valid template that I can deploy but fails linting. The error comes from the charts/cassandra/statefulset.yml which references the parent's named template "test.fullname".

**Comment by jwsomis** [comment]
@hickeyma Has there been any movement on this?

**Comment by hickeyma** [comment]
@jwsomis I can reproduce the issue using your chart. It seems to be a bug with `--with-subcharts` flag whereby the definitions are not be loaded from the parent chart during linting. I will set it to a bug.

**Comment by jwsomis** [comment]
@hickeyma  Can we reopen this? Would still like to see it fixed.

**Comment by rodrigodiez** [comment]
Is it possible to re-open this issue? Would also love to see it fixed. It's blocking our migration to a better linting solution

**Comment by ChadNedzlek** [comment]
This does make linting basically impossible for my scenarios, and I'd really like the linter to be useful.  Can we get some feedback from the team? It this just... not going to happen?

**Comment by ChadNedzlek** [comment]
For now I switched to running "helm template --debug", and that catches... many problems, but it's not ideal.

**Comment by ricardo-noyolalozano** [comment]
seconding this, would like to see this issue approved. have a helper template in the parent chart that is referenced by all the sub-charts
