### ISSUE TITLE
where can i find the description of  toYaml function ?

### ISSUE THREAD

**Issue by fffffreedom** [helm/helm#9972]
hi 

where can i find the description of  toYaml function ?
i had go through the following places:

https://masterminds.github.io/sprig/
https://helm.sh/docs/chart_template_guide/function_list/

thks

**Comment by yxxhero** [comment]
@fffffreedom https://github.com/helm/helm/blob/a499b4b179307c267bdf3ec49b880e3dbd2a5591/pkg/engine/funcs.go#L83

**Comment by yxxhero** [comment]
@fffffreedom can you close this issue.

**Comment by rmetzger** [comment]
I agree! It seems that this function is not documented anywhere, despite being quite important.

**Comment by Bengrunt** [comment]
In concur this function should be documented since it's quite often found in charts templates.

Moreover, without documentation we don't know if this is really supported or if it may disappear without warning in the near future.

Thanks!

**Comment by yxxhero** [comment]
@rmetzger  @bacongobbler PRs is welcome. Thanks very much.

**Comment by luisdavim** [comment]
Why does `helm/pkg/engine/funcs.go` even exist? Wouldn't it be better to maintain all these in https://github.com/Masterminds/sprig and have all the functions in one place? This would also be beneficial to other projects that use `sprig`
