### ISSUE TITLE
Is there a way to get helm values from go sdk ? 

### ISSUE THREAD

**Issue by yogesh-reddy** [helm/helm#9975]
`<!--` If you need help or think you have found a bug, please help us with your issue by entering the following information (otherwise you can delete this text): -->

example `helm get values <releasename> -n <ns>` provided all provided arguments that passed using set parameter while installing chart, can we get values by using helm sdk in GOlang?

Thank You

**Comment by bacongobbler** [comment]
Yes. Have a look at the following:

https://helm.sh/docs/topics/advanced/#simple-example
https://pkg.go.dev/helm.sh/helm/v3@v3.6.3/pkg/action#GetValues
https://pkg.go.dev/helm.sh/helm/v3@v3.6.3/pkg/action#NewGetValues

Let us know if you have any further questions.

**Comment by yogesh-reddy** [comment]
Thanks a lot it worked!
