### ISSUE TITLE
Can't use repo URLs that contain URL-encoded characters (e.g., Gitlab)

### ISSUE THREAD

**Issue by acnodal-tc** [helm/helm#9977]
Output of `helm version`:
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:59:07Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Vagrant/Libvirt/LVM, repo hosted on Gitlab

Thank you for Helm! We're using it with a Gitlab repo and I had a problem because it looks like Helm decodes any URL-encoding in the repo URL. For example, my project on gitlab is https://gitlab.com/api/v4/projects/acnodal%2FEGO/packages/helm/stable . The "%2F" is significant to Gitlab, it's not the same as "/". 

The "helm repo add" and "helm repo update" commands succeed, and I can search the repo and find packages, but an install command fails:

```
$ helm install --debug --namespace purelb --version=v0.3.2-ego20 ego ego/purelb
install.go:159: [debug] Original chart version: "v0.3.2-ego20"                                            
Error: failed to fetch https://gitlab.com/api/v4/projects/acnodal/EGO/packages/helm/stable/charts/purelb-v0.3.2-ego20.tgz : 404 Not Found                                                                            
helm.go:84: [debug] failed to fetch https://gitlab.com/api/v4/projects/acnodal/EGO/packages/helm/stable/charts/purelb-v0.3.2-ego20.tgz : 404 Not Found
helm.sh/helm/v3/pkg/getter.(*HTTPGetter).get                                                                                                                                                                                 /home/circleci/helm.sh/helm/pkg/getter/httpgetter.go:73
helm.sh/helm/v3/pkg/getter.(*HTTPGetter).Get                                                                                                                                                                                 /home/circleci/helm.sh/helm/pkg/getter/httpgetter.go:41                                           
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo
        /home/circleci/helm.sh/helm/pkg/downloader/chart_downloader.go:97
helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart
        /home/circleci/helm.sh/helm/pkg/action/install.go:667
main.runInstall
        /home/circleci/helm.sh/helm/cmd/helm/install.go:171
main.newInstallCmd.func1
        /home/circleci/helm.sh/helm/cmd/helm/install.go:117
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:83
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1357
```
Note that the original "/acnodal%2FEGO/" in the URL has become "/acnodal/EGO/" which is not the same URL. This causes Gitlab to return a 404.

**Comment by bacongobbler** [comment]
I believe https://github.com/helm/helm/pull/9825 attempts to fix this. Can you give that a shot and see if that fixes it for you?

Also,

> version.BuildInfo{Version:"v3.2.1"

In the future can you please test with a more recent version of Helm? That way we can determine whether this has been fixed with the latest release. Thanks!

See also https://github.com/helm/helm/issues/9821.

**Comment by hickeyma** [comment]
@acnodal-tc I went to reproduce this issue and failed when trying to add the repo as follows:

```console
$ helm repo add ego https://gitlab.com/api/v4/projects/acnodal%2FEGO/packages/helm/stable 

Error: looks like "https://gitlab.com/api/v4/projects/acnodal%2FEGO/packages/helm/stable" is not a valid chart repository or cannot be reached: failed to fetch https://gitlab.com/api/v4/projects/acnodal%2FEGO/packages/helm/stable/index.yaml : 401 Unauthorized
```

Is the repo open to the public?

**Comment by hickeyma** [comment]
I see using GitLab to host helm repo

**Comment by hickeyma** [comment]
I would like to test this manually first to reproduce the issue. not sure how to do this as GitHub is interpreting `%2f` as a `/` ! :) Any suggestions?

**Comment by acnodal-tc** [comment]
Hi, thank you for the speedy response!

Sorry about using an old version of helm - I'll upgrade and see what happens.

Unfortunately the repo I used is a private repo but I'll set up a test using a public one.

**Comment by acnodal-tc** [comment]
Hi @hickeyma thank you for the reminder. It turns out that #9825 didn't fix this bug, although it might well fix other bugs. I submitted PR #10020 which fixes the Gitlab repo use case.
