### ISSUE TITLE
Upgrade Failed :has been rollback due to atomic being set: timeout waiting for the condition.

### ISSUE THREAD

**Issue by thathireddy1982** [helm/helm#9982]
Hi  All
I am working with simple statefulset application deploying to GKE cluster using helm 3.0. while I am running the Job 
I am getting the error msg: UPGRADE FAILED: gke-release-app failed, and has been rollback due to atomic being set: timeout waiting for the condition.

could you please help me on this. what is the root cause of this error msg

Regards,
tk

**Comment by bacongobbler** [comment]
Hi @thathireddy1982. We need more information before we can help.

Output of `helm version`:

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

> timeout waiting for the condition.

Usually this means one of your resources were not marked by Kubernetes as "ready" within the timeframe allocated to `helm upgrade`. By default that timeout is 5 minutes.

https://helm.sh/docs/intro/using_helm/#helpful-options-for-installupgraderollback
