### ISSUE TITLE
Support for OCI registries in `helm search`

### ISSUE THREAD

**Issue by schra** [helm/helm#9983]
I am migrating our Helm charts on Azure to store them as Helm OCI artifacts. During this, I found that `helm search` only works with Helm 2-style (index.yaml-based) chart repositories and not OCI registries - at least on Azure. The Azure documentation says:

> The Helm OCI artifact repositories are not discoverable using Helm commands such as `helm search` and `helm repo list`.

(https://docs.microsoft.com/en-us/azure/container-registry/container-registry-helm-repos)

I'm not sure if it is possible at all for `helm search` to support OCI repos. If this is something that is not possible, it would be nice if the documentation stated that (neither https://helm.sh/docs/helm/helm_search/, nor https://helm.sh/docs/helm/helm_search_repo/ nor https://helm.sh/docs/topics/registries/ state anything about this).

**Comment by bacongobbler** [comment]
cc @jdolitsky - I think we discussed this two weeks ago during the Helm developer call.

**Comment by mattfarina** [comment]
I can give a little insight here. @jdolitsky may be able to give more as he is more involved in this area.

The [OCI distribution specification](https://github.com/opencontainers/distribution-spec), that tells Helm and others how to interact with registries, does not contain a search API. The topic of having a search API has come up in the past but has not become a reality and is not expected to anytime soon.

If there is no API specification we can follow, how do we make search work and work well? To do this we have to work with registries like ACR, ECR, Harbor, and others.

**Comment by toddysm** [comment]
Hey folks another question. Related to this issue, do `helm upgrade` and `helm show` have support for OCI artifacts?

**Comment by bacongobbler** [comment]
@toddysm see #9782 which implements `helm upgrade`/`helm show` support. Give that a shot and please provide feedback in that PR.
