### ISSUE TITLE
Support for `helm chart push` to fail if the chart already exists

### ISSUE THREAD

**Issue by schra** [helm/helm#9985]
I am migrating our Helm charts on Azure to store them as Helm OCI artifacts. The old Azure command was `az acr helm push`. By default, this command doesn't overwrite already existing charts. You can change the default behavior by providing `--force`. However, surprisingly, `helm chart push` overwrites existing charts.

It would be nice to have the same functionality in `helm chart push` too - i.e. to have the option to never overwrite already existing charts in the OCI registry. For example in the form of a `--dont-overwrite` flag.

**Comment by jdolitsky** [comment]
This is actually something that is typically enforced on the registry side.

See Amazon's "Image tag mutability" doc, for example:
https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-tag-mutability.html

Even though it can probably be achieved, we dont see this in other registry tools (e.g. `docker push`)

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!
