### ISSUE TITLE
Check if Chart is top level Chart or included as dependency

### ISSUE THREAD

**Issue by Ka0o0** [helm/helm#9991]
Hi,

is there a way to tell if a Chart is being installed/templated as the top level Chart or included as a dependency of another Chart?

I would like to have everything of the Chart in a named template so that it can be included n-times by a parent Chart dynamically and in case it is installed on its own I would like it to be rendered directly one time so that it can still be installed via helm install.

Thanks in advance.

**Comment by mattfarina** [comment]
Unfortunately, I am not aware of a way to know.

One option is to create the chart as a [library chart](https://helm.sh/docs/topics/library_charts/), that cannot be installed directly. Then have a second chart that does the install of it. This may not be ideal but may give you a way to handle it.

**Comment by Ka0o0** [comment]
Hi @mattfarina ,

thanks for the suggestion. The downside is that I would end up with three Charts where I could only have one.

I've had a look in the source code and found that internally Helm is already evaluating whether or not the currently processed/templated Chart is the root Chart. If I would have this information available inside the template I would be able to do exactly what I wanted to. I've already created a PR to discuss the possibility to expose this information to the template.
