### ISSUE TITLE
Strange behaviour with value names ending in `.n` 

### ISSUE THREAD

**Issue by mafonso** [helm/helm#9992]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"dirty", GoVersion:"go1.16.5"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:16:14Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-eks-6b7464", GitCommit:"6b746440c04cb81db4426842b4ae65c3f7035e53", GitTreeState:"clean", BuildDate:"2021-03-19T19:33:03Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
AKS
```

I bumped into a weird behavior when rendering the contents of variables named `n` or ending in `.n` 
e.g
 ```
n: "w3c7ZVF16RLCSt"
----
"n": {{ .Values.n | quote }}

->
renders "n": 
```
Renders an empty value

If I rename it to `m`or something else.
```
m: "w3c7ZVF16RLCSt"
----
"n": {{ .Values.m | quote }}

->
 renders "n": "w3c7ZVF16RLCSt"  as expected
```

The same is true if the value name is e.g `.Values.jwt.n`, `.Values.foo.n`, `.Values.foo.bar.n`

The original use case was:
```
JWT_AUTH["JWT_PRIVATE_SIGNING_JWK"] = json.dumps(
    {
        "kid": {{ .Values.jwt.kid | quote }},
        "kty": {{ .Values.jwt.kty | quote }},
        "e": {{ .Values.jwt.e | quote }},
        "d": {{ .Values.jwt.d | quote }},
        "n": {{ .Values.jwt.n | quote }}
        "p": {{ .Values.jwt.p | quote }},
        "q": {{ .Values.jwt.q | quote }}
    }
```
Is `n` a reserved value name, or is this an actual bug?

**Comment by mattfarina** [comment]
I've been able to replicate the problem and traced it to the [yaml parsing dependency](https://github.com/kubernetes-sigs/yaml).

In YAML "n" is the newline character but it needs to be `\n` for that to be processed [per the spec](https://yaml.org/spec/1.2/spec.html#id2776092). So, I think this is a bug in a library somewhere.
