### ISSUE TITLE
helm lint is too noisy

### ISSUE THREAD

**Issue by zmb3** [helm/helm#9994]
When running `helm lint` against a large number of charts, I see a lot of output even in the case when no problems are detected.

Each invocation prints `1 chart(s) linted, 0 chart(s) failed` and `Using values from 'foo/bar/baz.yaml'`. This makes it hard to tell when there actually is a problem.

It would be nice if `helm lint` had a "quiet" option or some other way to reduce the verbosity, such that the only text that is written to the console is lint warnings/errors, and a clean run with no issues presents no output.

**Comment by presztak** [comment]
Hey, I started working on this issue.

**Comment by hickeyma** [comment]
PR #10106 opened for this feature.
