### ISSUE TITLE
Helm reponds with 401 error on private repo

### ISSUE THREAD

**Issue by stavenko** [helm/helm#9997]
Hello, I have an issue with helm authentication in **private** repo.

Step to reproduce:
1. have a private repo
2. Authentication in repo with command: `helm repo add align <https-repo-url> --username=<user> --password=<password>`
3. make `helm repo update` (doesn't emit any error)
4. make `helm pull align/ccbackend-custom` //let me spoil chart name for ya

Expected: A chart file downloaded in current directory.
Actual: `Error: failed to fetch <specific repo-url>/ccbackend-custom/ccbackend-custom-1.2.2.tgz : 401 Unauthorized`

More info:
1. I encode in base64 string `<user>:<password>` (same as before)
2. run command `curl -H"Authorization: Basic <my-base64-string>" <same url where helm reports 401> -o ccbackend-custom`
3. I get helm-chart.

Output of `helm version`:
3.6.3

My current platform: 
Mac OS X Big Sur M1 (arm64)

Output of `kubectl version`:

unrelated

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

unrelated

**Comment by mattfarina** [comment]
I have an idea what might be going on. When a username and password are set for a repo they are only set for that repo location. If a chart archive is stored in another location (e.g., on a different domain) the credentials are not passed on by default. This is a security measure in order to not leak credentials. If you want to pass the credentials on to other domains you can use the `--pass-credentials` flag when you use `helm repo add`.

**Comment by stavenko** [comment]
That was my first idea.
I made several changes to my helm config.
And in the end, there are facts:
1. My helms are in the same domain with repo. 
2. I actually use --pass-credentials (this option also exists in helm pull)
3. I installed version 3.5.3 and it works with same config.

**Comment by bacongobbler** [comment]
@stavenko I can't really tell from your last comment.. Were you able to resolve this issue using the `--pass-credentials` flag or not?

Your steps to reproduce the issue does not pass the `--pass-credentials` flag to `helm repo add`.

If you add that flag, what happens?

**Comment by bacongobbler** [comment]
Ah... This might actually be a duplicate feature request for https://github.com/helm/helm/issues/9599, as you're asking that `helm pull` should use the same credentials provided with `helm repo add`. Is that correct?

**Comment by bacongobbler** [comment]
Please also take a look at https://github.com/helm/helm/pull/9760 and see if that resolves this issue for you

**Comment by stavenko** [comment]
@bacongobbler I am just telling, that I already tried what you proposing and this is not helping.
I have added this flag in helm config (`Library/Preferences/helm/repositories.yaml`) - result negative.
I have added this flag to `helm pull` command - same result.
I have added credentials to `helm pull` command - negative.

My chart's url is also has the same host with repo - so it doesn't even look like an issue here. 
This issue reproduces only in 3.6.x helm.
Helm 3.5 works as expected.

**Comment by stavenko** [comment]
Well, I checked this carefully and have updates:

When I set `pass_credentials_all: true` in `~/Library/Preferences/helm/repositories.yaml` It actually works. I have pulled chart from repository. 
Success.

But!

My url in repo is `https://repo.aligntech.com/helm-bld/` 
and url of downloaded chart is ` https://repo.aligntech.com:443/api/helm/helm-bld/ccbackend-custom/ccbackend-custom-1.2.2.tgz`

How is that supposed to be different domains?

**Comment by mattfarina** [comment]
I think I see what's going on here. The URL host portion is different. In one case it's `repo.aligntech.com` and in another case it's `repo.aligntech.com:443`. This is something, if I remember right, that artifactory does. Others may do it, too. #9886 was created to address this issue.
